### ISSUE TITLE
[VideoMega.TV] Download link 403 Forbidden.

### ISSUE THREAD

**Issue by MaeJhem** [ytdl-org/youtube-dl#10108]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.16**
- [x] Bug report (encountered problems with youtube-dl)

---

Here's the output.

```
youtube-dl -v http://videomega.tv/?ref=G64G3RFB0000BFR3G46G
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://videomega.tv/?ref=G64G3RFB0000BFR3G46G']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2016.07.16
[debug] Python version 2.6.6 - Linux-2.6.32-042stab113.21-x86_64-with-centos-6.8-Final
[debug] exe versions: none
[debug] Proxy map: {}
[VideoMega] G64G3RFB0000BFR3G46G: Downloading webpage
[debug] Invoking downloader on u'http://ack.cdn.vizplay.org/v/b5ef57919b73200c744121a8e358b69f.mp4?st=GeVLfNsXHwTO_VE0Mk95PA&hash=lP_d2XbYtNaUKmNjiMl3Mg'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1683, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1625, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1985, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

**Comment by dstftw** [comment]
This does not work for me in browser either.

**Comment by MaeJhem** [comment]
Also tried other videos...
http://videomega.tv/?ref=553lIodwIJJIwdoIl355

In the debug, it download. But when you try getting the link with `-g` command. and try `wget "downlaod link"`
It say 403 Forbidden.
