### ISSUE TITLE
[NBCLosAngeles] Falls back on generic extractor

### ISSUE THREAD

**Issue by vxbinaca** [ytdl-org/youtube-dl#10105]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.16**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Site support request (request for adding support for a new site)

---

`youtube-dl http://www.nbclosangeles.com/on-air/as-seen-on/De-Leon-Dismisses-Newsom-Gun-Control-Measure--385381181.html`

```
[debug] System config: []
[debug] User config: ['--download-archive', '~/.ytdlarchive', '--retries', '100', '--no-overwrites', '--call-home', '--continue', '--write-info-json', '--write-description', '--write-thumbnail', '--write-annotations', '--all-subs', '--write-sub', '--add-metadata', '-f', 'bestvideo+bestaudio/best', '--merge-output-format', 'mkv', '--prefer-ffmpeg', '--embed-thumbnail']
[debug] Command-line args: ['-v', 'http://www.nbclosangeles.com/on-air/as-seen-on/De-Leon-Dismisses-Newsom-Gun-Control-Measure--385381181.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.16
[debug] Python version 3.5.1+ - Linux-4.4.0-31-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.6-1ubuntu2, avprobe 2.8.6-1ubuntu2, ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Public IP address: 173.14.86.178
[generic] De-Leon-Dismisses-Newsom-Gun-Control-Measure--385381181: Requesting header
WARNING: Falling back on generic information extractor.
[generic] De-Leon-Dismisses-Newsom-Gun-Control-Measure--385381181: Downloading webpage
[generic] De-Leon-Dismisses-Newsom-Gun-Control-Measure--385381181: Extracting information
ERROR: Unsupported URL: http://www.nbclosangeles.com/on-air/as-seen-on/De-Leon-Dismisses-Newsom-Gun-Control-Measure--385381181.html
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 682, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/generic.py", line 2282, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.nbclosangeles.com/on-air/as-seen-on/De-Leon-Dismisses-Newsom-Gun-Control-Measure--385381181.html
```

**Comment by rudolphos** [comment]
Bump. Doesn't work on all local NBC news sites.

"Unsupported URL"

https://www.nbclosangeles.com/news/national-international/adidas-store-looted-in-los-angeles/2371376/
https://www.nbcchicago.com/news/national-international/adidas-store-looted-in-los-angeles/2280905/
https://www.nbcphiladelphia.com/news/national-international/adidas-store-looted-in-los-angeles/2413811/
https://www.nbcwashington.com/news/national-international/adidas-store-looted-in-los-angeles/2317759/
https://www.necn.com/news/national-international/adidas-store-looted-in-los-angeles/2279022/
https://www.nbcboston.com/news/national-international/adidas-store-looted-in-los-angeles/2134171/
