### ISSUE TITLE
[NosVideo] Support new url.

### ISSUE THREAD

**Issue by ghost** [ytdl-org/youtube-dl#10436]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.24.1**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
$ y -v http://nosvideo.com/jxymzsfkkygy 
[debug] System config: []
[debug] User config: ['-4', '-f', 'best', '--prefer-free-formats', '--no-cache-dir', '--no-mtime', '--youtube-skip-dash-manifest']
[debug] Command-line args: ['-v', 'http://nosvideo.com/jxymzsfkkygy']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.24.1
[debug] Python version 3.6.0a4 - Linux-4.7.0-rc7-686-i686-with-debian-stretch-sid
[debug] exe versions: ffmpeg 3.1.2, ffprobe 3.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] jxymzsfkkygy: Requesting header
WARNING: Falling back on generic information extractor.
[generic] jxymzsfkkygy: Downloading webpage
[generic] jxymzsfkkygy: Extracting information
ERROR: Unsupported URL: http://nosvideo.com/jxymzsfkkygy
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/generic.py", line 2377, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://nosvideo.com/jxymzsfkkygy
```

And replce test url with this one.

**Comment by dangarthwaite** [comment]
I ran it again on the latest branch and it handles the redirection to binge-watch.is.
It then fails because the redirect simply redirects to the root of binge-watch.is:

```
$ ipython3 -- ./youtube_dl/__main__.py -v http://nosvideo.com/jxymzsfkkygy
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://nosvideo.com/jxymzsfkkygy']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Git HEAD: aaf9d904a
[debug] Python version 3.7.4 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] jxymzsfkkygy: Requesting header
[redirect] Following redirect to https://binge-watch.is/
[generic] binge-watch: Requesting header
WARNING: Falling back on generic information extractor.
[generic] binge-watch: Downloading webpage
[generic] binge-watch: Extracting information
ERROR: Unsupported URL: https://binge-watch.is/
Traceback (most recent call last):
  File "/Users/dan/Projects/forks/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/Users/dan/Projects/forks/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/Users/dan/Projects/forks/youtube-dl/youtube_dl/extractor/generic.py", line 3355, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://binge-watch.is/
```
