### ISSUE TITLE
Adult Swim: support for free to watch anime episodes.

### ISSUE THREAD

**Issue by ghost** [ytdl-org/youtube-dl#10948]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.16**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

http://www.adultswim.com/misc/jojos-bizarre-adventure/
These episodes are free to watch without commercials and no cable login required.

And every episode of One Punch man was free for a week or so.

**Comment by thorsummoner** [comment]
youtube-dl recognizes adult swim as if it is supported; the Two AdultSwim titles I tried to view both failed with
> RegexNotFoundError: Unable to extract bootstraped data; please report this issue on ...

Verbose output follows for the first episodes of the two shows I tried.
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.adultswim.com/videos/jojos-bizarre-adventure/a-letter-from-the-past/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.18
[debug] Python version 2.7.6 - Linux-4.4.0-31-generic-x86_64-with-LinuxMint-17.3-rosa
[debug] exe versions: ffmpeg 2.8.1-1, ffprobe 2.8.1-1
[debug] Proxy map: {}
[AdultSwim] a-letter-from-the-past: Downloading webpage
ERROR: Unable to extract bootstraped data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/adultswim.py", line 152, in _real_extract
    r'var bootstrappedData = ({.*});', webpage, 'bootstraped data'), episode_path)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 660, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract bootstraped data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.adultswim.com/videos/space-ghost-coast-to-coast/spanish-translation/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.18
[debug] Python version 2.7.6 - Linux-4.4.0-31-generic-x86_64-with-LinuxMint-17.3-rosa
[debug] exe versions: ffmpeg 2.8.1-1, ffprobe 2.8.1-1
[debug] Proxy map: {}
[AdultSwim] spanish-translation: Downloading webpage
ERROR: Unable to extract bootstraped data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/adultswim.py", line 152, in _real_extract
    r'var bootstrappedData = ({.*});', webpage, 'bootstraped data'), episode_path)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 660, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract bootstraped data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
I think this Issue maybe should be turned into a bug report

**Comment by yan12125** [comment]
FYI: AdultSwim is broken - #11042
