### ISSUE TITLE
please support camwhores.tv

### ISSUE THREAD

**Issue by ghost** [ytdl-org/youtube-dl#11009]
example vids http://www.camwhores.tv/tags/kelseysbedroom/

```
$ youtube-dl -v 'http://www.camwhores.tv/videos/28542/kelseysbedroom-webcam-show-2015-november-24-21-11/'
[debug] System config: [u'--prefer-ffmpeg', u'--hls-prefer-native', u'-n']
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.camwhores.tv/videos/28542/kelseysbedroom-webcam-show-2015-november-24-21-11/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.21.1
[debug] Python version 2.7.10 - Darwin-16.0.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.1.4, ffprobe 3.1.4
[debug] Proxy map: {'http': 'http://localhost:8118', 'https': 'http://localhost:8118'}
[generic] kelseysbedroom-webcam-show-2015-november-24-21-11: Requesting header
WARNING: Falling back on generic information extractor.
[generic] kelseysbedroom-webcam-show-2015-november-24-21-11: Downloading webpage
[generic] kelseysbedroom-webcam-show-2015-november-24-21-11: Extracting information
ERROR: Unsupported URL: http://www.camwhores.tv/videos/28542/kelseysbedroom-webcam-show-2015-november-24-21-11/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1648, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2525, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2514, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 23, column 3
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2431, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.camwhores.tv/videos/28542/kelseysbedroom-webcam-show-2015-november-24-21-11/
```

thanks for your awesome job

**Comment by CiscoPress** [comment]
bump

**Comment by Mnblnk** [comment]
Bump

**Comment by hman9299** [comment]
Interested too

**Comment by dirkf** [comment]
https://github.com/ytdl-org/youtube-dl/pull/30571#issuecomment-2657278048.
