### ISSUE TITLE
Site support request:  bfmbusiness.bfmtv.com

### ISSUE THREAD

**Issue by loby66** [ytdl-org/youtube-dl#11523]
**[x ] Site support request**

`>youtube-dl.exe -U`
`youtube-dl is up-to-date (2016.12.22)`
` `
`>youtube-dl.exe -v http://bfmbusiness.bfmtv.com/mediaplayer/chroniques/olivier-delamarche/`
`[debug] System config: []`
`[debug] User config: []`
`[debug] Command-line args: ['-v', 'http://bfmbusiness.bfmtv.com/mediaplayer/chroniques/olivier-delamarche/']`
`[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252`
`[debug] youtube-dl version 2016.12.22`
`[debug] Python version 3.4.4 - Windows-10-10.0.14393`
`[debug] exe versions: ffmpeg 2.8.4, ffprobe N-81045-g450cf40, rtmpdump 2.4`
`[debug] Proxy map: {}`
`[generic] olivier-delamarche: Requesting header`
`WARNING: Falling back on generic information extractor.`
`[generic] olivier-delamarche: Downloading webpage`
`[generic] olivier-delamarche: Extracting information`
`ERROR: Unsupported URL: http://bfmbusiness.bfmtv.com/mediaplayer/chroniques/olivier-delamarche/`
`Traceback (most recent call last):`
`  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\build\youtube_dl\YoutubeDL.py", line 694, in extract_info`
`  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\build\youtube_dl\extractor\common.py", line 358, in extract`
`  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\build\youtube_dl\extractor\generic.py", line 2453, in _real_extract`
`youtube_dl.utils.UnsupportedError: Unsupported URL: http://bfmbusiness.bfmtv.com/mediaplayer/chroniques/olivier-delamarche/`

### Description of your *issue*, suggested solution and other information
Youtube-dl works perfectly with [bfmtv.com](http://www.bfmtv.com/mediaplayer/replay/19h-ruth-elkrief/) but NOT with [bfmbusiness.bfmtv.com](http://bfmbusiness.bfmtv.com/mediaplayer/chroniques/olivier-delamarche/)

**Comment by theamnesic** [comment]
Hi @dstftw !

I think we can re-open this one, bfmbusiness.bfmtv.com doesn't work anymore.
I'm running youtube-dl 2017.10.20.

```
[~] › youtube-dl --verbose http://bfmbusiness.bfmtv.com/mediaplayer/video/l-edito-quand-les-pubs-se-copient-2110-994365.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://bfmbusiness.bfmtv.com/mediaplayer/video/l-edito-quand-les-pubs-se-copient-2110-994365.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.20
[debug] Python version 2.7.10 - Darwin-17.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] l-edito-quand-les-pubs-se-copient-2110-994365: Requesting header
WARNING: Falling back on generic information extractor.
[generic] l-edito-quand-les-pubs-se-copient-2110-994365: Downloading webpage
[generic] l-edito-quand-les-pubs-se-copient-2110-994365: Extracting information
[download] Downloading playlist: L'édito: Quand les pubs se copient - 21/10
[generic] playlist L'édito: Quand les pubs se copient - 21/10: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:legacy] 5621058353001: Downloading webpage
[brightcove:legacy] 5621058353001: Extracting information
ERROR: Unable to extract video url for 5621058353001; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 304, in _real_extract
    videoPlayer[0], query, referer=referer)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 335, in _get_video_info
    return self._extract_video_info(video_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 448, in _extract_video_info
    raise ExtractorError('Unable to extract video url for %s' % video_id)
ExtractorError: Unable to extract video url for 5621058353001; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Thanks !

**Comment by flzara** [comment]
Hello there, 

Still not working. I tried today on an url talking about Open Source and no luck : 

```
$ youtube-dl --verbose http://bfmbusiness.bfmtv.com/mediaplayer/video/regards-croises-sur-l-open-source-1301-1023365.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://bfmbusiness.bfmtv.com/mediaplayer/video/regards-croises-sur-l-open-source-1301-1023365.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.07
[debug] Python version 2.7.13 (CPython) - Linux-4.10.0-42-generic-x86_64-with-Ubuntu-17.04-zesty
[debug] exe versions: ffmpeg 3.2.4-1build2, ffprobe 3.2.4-1build2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] regards-croises-sur-l-open-source-1301-1023365: Requesting header
WARNING: Falling back on generic information extractor.
[generic] regards-croises-sur-l-open-source-1301-1023365: Downloading webpage
[generic] regards-croises-sur-l-open-source-1301-1023365: Extracting information
[download] Downloading playlist: Regards croisés sur l'Open Source - 13/01
[generic] playlist Regards croisés sur l'Open Source - 13/01: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:legacy] 5711018454001: Downloading webpage
[brightcove:legacy] 5711018454001: Extracting information
ERROR: Unable to extract video url for 5711018454001; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 304, in _real_extract
    videoPlayer[0], query, referer=referer)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 335, in _get_video_info
    return self._extract_video_info(video_info)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 448, in _extract_video_info
    raise ExtractorError('Unable to extract video url for %s' % video_id)
ExtractorError: Unable to extract video url for 5711018454001; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
