### ISSUE TITLE
site download failure (USA)

### ISSUE THREAD

**Issue by tv21** [ytdl-org/youtube-dl#12358]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.05*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v --ap-mso Charter_Direct --ap-username PRIVATE --ap-password PRIVATE http://www.usanetwork.com/chrisleyknowsbest/videos/client-hell
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--ap-mso', u'Charter_Direct', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'http://www.usanetwork.com/chrisleyknowsbest/videos/client-hell']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.05
[debug] Python version 2.7.9 - Linux-4.4.50+-armv6l-with-debian-8.0
[debug] exe versions: avconv 11.8-6, avprobe 11.8-6
[debug] Proxy map: {}
[USANetwork] client-hell: Downloading webpage
[USANetwork] 3474319: Retrieving Media Token
[ThePlatform] 3474319: Downloading SMIL data
[ThePlatform] 3474319: Downloading m3u8 information
[ThePlatform] 3474319: Downloading JSON metadata
[debug] Invoking downloader on u'https://tveusa-vh.akamaihd.net/i/prod/video/155/171/170222_3474319_Client_Hell_,25,40,18,12,7,4,2,00.mp4.csmil/index_1_av.m3u8?null=0&id=MNpud5ptnMHW1AcMVOcB6ogvnLRmtcfo4hUtDPRDFrulHQkTWEfRJMlDa6oBDAge5VUG3RDaQrxf6mDZ%3d%3d&hdntl=exp=1488748282~acl=%2fi%2fprod%2fvideo%2f155%2f171%2f170222_3474319_Client_Hell_*~data=hdntl~hmac=7FzkFp31HvIJjeRb8sLRwJwm8rzuoX3SqeYGq8h9UPgJvahhldWC2ohrYwDuDoT9'
[download] Destination: /home/pi/Share/Client-Hell.mp4
[debug] avconv command line: avconv -y -headers 'Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: _alid_=XUuToUO009wVv9e2x5rerL==; hdntl=exp=1488748282~acl=%2fi%2fprod%2fvideo%2f155%2f171%2f170222_3474319_Client_Hell_*~data=hdntl~hmac=7FzkFp31HvIJjeRb8sLRwJwm8rzuoX3SqeYGq8h9UPgJvahhldWC2ohrYwDuDoT9
' -i 'https://tveusa-vh.akamaihd.net/i/prod/video/155/171/170222_3474319_Client_Hell_,25,40,18,12,7,4,2,00.mp4.csmil/index_1_av.m3u8?null=0&id=MNpud5ptnMHW1AcMVOcB6ogvnLRmtcfo4hUtDPRDFrulHQkTWEfRJMlDa6oBDAge5VUG3RDaQrxf6mDZ%3d%3d&hdntl=exp=1488748282~acl=%2fi%2fprod%2fvideo%2f155%2f171%2f170222_3474319_Client_Hell_*~data=hdntl~hmac=7FzkFp31HvIJjeRb8sLRwJwm8rzuoX3SqeYGq8h9UPgJvahhldWC2ohrYwDuDoT9' -c copy -f mp4 file:/home/pi/Share/Client-Hell.mp4.part
avconv version 11.8-6:11.8-1~deb8u1+rpi1, Copyright (c) 2000-2016 the Libav developers
  built on Oct  8 2016 02:37:00 with gcc 4.9.2 (Raspbian 4.9.2-10)
[https @ 0x143562] HTTP error 403 Forbidden
Unable to open key file https://tveusa-vh.akamaihd.net/i/prod/video/155/171/170222_3474319_Client_Hell_,25,40,18,12,7,4,2,00.mp4.csmil/crypt.key?null=0&id=MNpud5ptnMHW1AcMVOcB6ogvnLRmtcfo4hUtDPRDFrulHQkTWEfRJMlDa6oBDAge5VUG3RDaQrxf6mDZ%3d%3d&hdntl=exp=1488748282~acl=/i/prod/video/155/171/170222_3474319_Client_Hell_*~data=hdntl~hmac=7FzkFp31HvIJjeRb8sLRwJwm8rzuoX3SqeYGq8h9UPgJvahhldWC2ohrYwDuDoT9
[http @ 0x067653] HTTP error 403 Forbidden
[crypto @ 0x143562] Unable to open input
https://tveusa-vh.akamaihd.net/i/prod/video/155/171/170222_3474319_Client_Hell_,25,40,18,12,7,4,2,00.mp4.csmil/index_1_av.m3u8?null=0&id=MNpud5ptnMHW1AcMVOcB6ogvnLRmtcfo4hUtDPRDFrulHQkTWEfRJMlDa6oBDAge5VUG3RDaQrxf6mDZ%3d%3d&hdntl=exp=1488748282~acl=%2fi%2fprod%2fvideo%2f155%2f171%2f170222_3474319_Client_Hell_*~data=hdntl~hmac=7FzkFp31HvIJjeRb8sLRwJwm8rzuoX3SqeYGq8h9UPgJvahhldWC2ohrYwDuDoT9: Input/output error


ERROR: ffmpeg exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 457, in main
    _real_main(argv)
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 447, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1883, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 772, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 851, in process_ie_result
    new_result, download=download, extra_info=extra_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 826, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1527, in process_video_result
    self.process_info(new_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1791, in process_info
    success = dl(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1733, in dl
    return fd.download(name, info)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/external.py", line 44, in real_download
    self.get_basename(), retval))
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 162, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 589, in report_error
    self.trouble(error_message, tb)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 551, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

---

### Description of your *issue*, suggested solution and other information

When trying to use youtube-dl to get anything from the usa site it fails with a HTTP error 403 Forbidden.

**Comment by StevenDTX** [comment]
Maybe there is an issue with  the Charter AdobePass??  It works just fine without authentication, and with DTV authentication.

```
E:\>youtube-dl.exe http://www.usanetwork.com/chrisleyknowsbest/videos/client-hell
[USANetwork] client-hell: Downloading webpage
[USANetwork] 3474319: Retrieving Media Token
[ThePlatform] 3474319: Downloading SMIL data
[ThePlatform] 3474319: Downloading m3u8 information
[ThePlatform] 3474319: Downloading JSON metadata
[download] Destination: Client-Hell-3474319.mp4
ffmpeg version N-82966-g6993bb4 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 43.100 / 55. 43.100
  libavcodec     57. 70.100 / 57. 70.100
  libavformat    57. 61.100 / 57. 61.100
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 68.100 /  6. 68.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
Input #0, hls,applehttp, from 'https://tveusa-vh.akamaihd.net/i/prod/video/155/171/170222_3474319_Client_Hell_,25,40,18,12,7,4,2,00.mp4.csmil/index_1_av.m3u8?null=0&id=AgCtRzuLF9dipsZbvFhBHtqAC5%2flwyehd4GPLtfgD8cIx4nXj+GLd9k9lM3PuD3MFKAxulPnQmpA2Q%3d%3d&hdntl=exp=1488825670~acl=%2fi%2fprod%2fvideo%2f155%2f171%2f170222_3474319_Client_Hell_*~data=hdntl~hmac=3a2de693d1d5f6d194560e2f6860f76b536eff580a6cd9a42a42016fedc412c7':
  Duration: 00:21:35.00, start: 0.100511, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080, Closed Captions, 29.97 tbr, 90k tbn, 59.94 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Client-Hell-3474319.mp4.part':
  Metadata:
    encoder         : Lavf57.61.100
    Stream #0:0: Video: h264 (Main) ([33][0][0][0] / 0x0021), yuv420p, 1920x1080, q=2-31, 29.97 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  361 fps=229 q=-1.0 Lsize=    7158kB time=00:00:12.01 bitrate=4881.2kbits/s speed=7.62x
video:7010kB audio:138kB subtitle:0kB other streams:0kB global headers:1kB muxing overhead: 0.136923%
Exiting normally, received signal 2.

ERROR: Interrupted by user
```

```
E:\>youtube-dl.exe --ap-mso DTV --ap-username username --ap-password password http://www.usanetwork.com/chrisleyknowsbest/videos/client-hell
[USANetwork] client-hell: Downloading webpage
[USANetwork] 3474319: Retrieving Media Token
[ThePlatform] 3474319: Downloading SMIL data
[ThePlatform] 3474319: Downloading m3u8 information
[ThePlatform] 3474319: Downloading JSON metadata
[download] Destination: Client-Hell-3474319.mp4
ffmpeg version N-82966-g6993bb4 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 43.100 / 55. 43.100
  libavcodec     57. 70.100 / 57. 70.100
  libavformat    57. 61.100 / 57. 61.100
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 68.100 /  6. 68.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
Input #0, hls,applehttp, from 'https://tveusa-vh.akamaihd.net/i/prod/video/155/171/170222_3474319_Client_Hell_,25,40,18,12,7,4,2,00.mp4.csmil/index_1_av.m3u8?null=0&id=AgCtRzuLF9dipktcvFgaNSQ2GCPx%2fJzZm+ef7rOJrGT7ZG+8OuhZnLQNhlUaRUBXGKkQ%2fxBVnxKPoA%3d%3d&hdntl=exp=1488825803~acl=%2fi%2fprod%2fvideo%2f155%2f171%2f170222_3474319_Client_Hell_*~data=hdntl~hmac=95a68c93cc626e5fc028600863b96596114afafd8f8b40f81eab11b2708a2b01':
  Duration: 00:21:35.00, start: 0.100511, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080, Closed Captions, 29.97 tbr, 90k tbn, 59.94 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Client-Hell-3474319.mp4.part':
  Metadata:
    encoder         : Lavf57.61.100
    Stream #0:0: Video: h264 (Main) ([33][0][0][0] / 0x0021), yuv420p, 1920x1080, q=2-31, 29.97 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  349 fps=243 q=-1.0 Lsize=    6911kB time=00:00:11.63 bitrate=4866.7kbits/s speed=8.11x
video:6770kB audio:131kB subtitle:0kB other streams:0kB global headers:1kB muxing overhead: 0.137396%
Exiting normally, received signal 2.

ERROR: Interrupted by user

```

**Comment by tv21** [comment]
I had a media failure today so had to quickly set up a new system with Ubuntu Server 16.04, and installed youtube-dl from scratch, but it still would not work.  But then I updated it to the 2017.03.06 version and tried again.  This time it came up with:

ERROR: m3u8 download detected but ffmpeg or avconv could not be found. Please install one.

So I did **sudo apt-get install ffmpeg** which brought in 104 new packages (ffmpeg and all its dependencies, I guess) but after that it appears to be working now.

On the previous system I had installed avconf rather than ffmpeg because it was easier to install.  But in 16.04 ffmpeg is back in the official repository, apparently.  So I don't know if the new version fixed it or if adding ffmpeg did, I suspect it was the new version because when I tried it prior to upgrading to 2017.03.06 it never got far enough to detect that ffmpeg or avconf was missing.  So whatever you did, thank you!

**Comment by tv21** [comment]
USA is failing again today, I suspect this is not related to the above issue but that something has changed on their site.  The error I get is:

`ExtractorError: An extractor error has occurred. (caused by KeyError(u'data-mpx-guid',))`

Here's the output:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--restrict-filenames', u'--abort-on-error', u'--ap-mso', u'Charter_Direct', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'https://www.usanetwork.com/suits/videos/if-the-shoe-fits']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-159-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 4.1.3-static, ffprobe 4.1.3-static
[debug] Proxy map: {}
[USANetwork] if-the-shoe-fits: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError(u'data-mpx-guid',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/user/ytdl/youtube-dl-master/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/user/ytdl/youtube-dl-master/youtube_dl/extractor/usanetwork.py", line 36, in _real_extract
    video_id = player_params['data-mpx-guid']
KeyError: u'data-mpx-guid'
Traceback (most recent call last):
  File "/home/user/ytdl/youtube-dl-master/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/user/ytdl/youtube-dl-master/youtube_dl/extractor/common.py", line 543, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'data-mpx-guid',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
