### ISSUE TITLE
MSNBC Error on Downloading JSON metadata

### ISSUE THREAD

**Issue by Bl1z** [ytdl-org/youtube-dl#12576]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.26**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)
---
```
youtube-dl -v http://www.msnbc.com/msnbc-news/watch/hollywood-re
vives-russian-bad-guys-906946627922
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.msnbc.com/msnbc-news/watch/hollywo
od-revives-russian-bad-guys-906946627922']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.03.26
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[NBCNews] 906946627922: Downloading webpage
[ThePlatformFeed] n_msnbc_bad_170326: Downloading JSON metadata
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\bu
ild\youtube_dl\__init__.py", line 464, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\bu
ild\youtube_dl\__init__.py", line 454, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\bu
ild\youtube_dl\YoutubeDL.py", line 1884, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\bu
ild\youtube_dl\YoutubeDL.py", line 772, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\bu
ild\youtube_dl\YoutubeDL.py", line 838, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\bu
ild\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\bu
ild\youtube_dl\extractor\common.py", line 428, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\bu
ild\youtube_dl\extractor\theplatform.py", line 378, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\bu
ild\youtube_dl\extractor\theplatform.py", line 313, in _extract_feed_info
IndexError: list index out of range
```
---

**Comment by WindozeNT** [comment]
I'm having the same issue when trying to download a video from NBC.com using youtube-dl 2017.06.18. I tested downloading a YouTube video and it worked, but NBC.com always produces this error:

```
youtube-dl.exe -v https://www.nbc.com/saturday-night-live/video/nbc-aging-cold-open/2869143
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.nbc.com/saturday-night-live/video/nbc-aging-cold-open/2869143']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.06.18
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg 2.8.4
[debug] Proxy map: {}
[NBC] 2869143: Downloading JSON metadata
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_9wocfhk\build\youtube_dl\__init__.py", line 465
, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_9wocfhk\build\youtube_dl\__init__.py", line 455
, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_9wocfhk\build\youtube_dl\YoutubeDL.py", line 19
19, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_9wocfhk\build\youtube_dl\YoutubeDL.py", line 76
2, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_9wocfhk\build\youtube_dl\extractor\common.py",
line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_9wocfhk\build\youtube_dl\extractor\nbc.py", lin
e 78, in _real_extract
IndexError: list index out of range
```

**Comment by thomco** [comment]
Encountering the same error with MSNBC videos (also ThePlatform)

```
youtube-dl -v http://www.msnbc.com/all-in/watch/trump-thought-mueller-had-conflicts-of-interest-nyt-reporter-1146252867957
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.msnbc.com/all-in/watch/trump-thought-mueller-had-conflicts-of-interest-nyt-reporter-1146252867957']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2018.01.21
[debug] Python version 3.6.4 (CPython) - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[NBCNews] 1146252867957: Downloading webpage
[ThePlatformFeed] 1146252867957: Downloading JSON metadata
Traceback (most recent call last):
  File "c:\users\thomas\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\thomas\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Thomas\Anaconda3\Scripts\youtube-dl.exe\__main__.py", line 9, in <module>
  File "c:\users\thomas\anaconda3\lib\site-packages\youtube_dl\__init__.py", line 465, in main
    _real_main(argv)
  File "c:\users\thomas\anaconda3\lib\site-packages\youtube_dl\__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "c:\users\thomas\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 1988, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "c:\users\thomas\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 795, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\users\thomas\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 861, in process_ie_result
    extra_info=extra_info, download=False, process=False)
  File "c:\users\thomas\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\thomas\anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "c:\users\thomas\anaconda3\lib\site-packages\youtube_dl\extractor\theplatform.py", line 397, in _real_extract
    return self._extract_feed_info(provider_id, feed_id, filter_query, video_id)
  File "c:\users\thomas\anaconda3\lib\site-packages\youtube_dl\extractor\theplatform.py", line 332, in _extract_feed_info
    entry = self._download_json(real_url, video_id)['entries'][0]
IndexError: list index out of range

```

**Comment by douglasg14b** [comment]
Also getting this error

**Comment by ObjectInSpace** [comment]
Also getting this error for videos from nbcnews on most recent youtube-dl (2018-10-05 as of this writing).

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\theplatform.py", line 402, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\theplatform.py", line 337, in _extract_feed_info
KeyError: 'entries'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\theplatform.py", line 402, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\theplatform.py", line 337, in _extract_feed_info
KeyError: 'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 520, in extract
