### ISSUE TITLE
Dowload video from "www.telecinco.es"

### ISSUE THREAD

**Issue by gbogsal** [ytdl-org/youtube-dl#12673]
This is the youtubedl log (youtubedl is updated ):

youtube-dl.exe --verbose http://www.telecinco.es/lavozkids/a-carta/Cuartas-Audiciones-ciegas-Voz-Kids_2_2348355002.html

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://www.telecinco.es/lavozkids/a-carta/Cuartas-Audiciones-ciegas-Voz-Kids_2_2348355002.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.04.03
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-83781-g3016e91
[debug] Proxy map: {}
[Telecinco] Cuartas-Audiciones-ciegas-Voz-Kids_2_2348355002: Downloading webpage
[Ooyala] xjaWpsYTE6uCqIzMSPX4LerX4KlqxADt: Downloading JSON metadata
[Ooyala] xjaWpsYTE6uCqIzMSPX4LerX4KlqxADt: Downloading JSON metadata
[Ooyala] xjaWpsYTE6uCqIzMSPX4LerX4KlqxADt: Downloading MPD manifest
[Ooyala] xjaWpsYTE6uCqIzMSPX4LerX4KlqxADt: Downloading ISM manifest
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\extractor\ooyala.py", line 158, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\extractor\ooyala.py", line 80, in _extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\extractor\common.py", line 1042, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by remitamine** [comment]
no longer accessible.
