### ISSUE TITLE
[viafree] Support playlists

### ISSUE THREAD

**Issue by forthrin** [ytdl-org/youtube-dl#12686]
```
~$ youtube-dl -v --yes-playlist https://www.viafree.no/programmer/underholdning/paradise-hotel
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--yes-playlist', u'https://www.viafree.no/programmer/underholdning/paradise-hotel']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.03
[debug] Python version 2.7.10 - Darwin-16.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[Viafree] paradise-hotel: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tvplay.py", line 427, in _real_extract
    webpage, 'video id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 778, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by MrDemocracy** [comment]
Could someone please look into this? It's so tedious having to manually copy and paste the link to each episode, for every season. And then also having to do the same for the subtitle files, because of issue #12685
