### ISSUE TITLE
--skip-unavailable-fragments is being ignored

### ISSUE THREAD

**Issue by scholtzm** [ytdl-org/youtube-dl#12769]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Question

---

Verbose log:

```
$ youtube-dl --skip-unavailable-fragments -v http://www.ceskatelevize.cz/porady/11059301252-doktori/215562260300005-cesky-narod-je-vynalezavy/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--skip-unavailable-fragments', u'-v', u'http://www.ceskatelevize.cz/porady/11059301252-doktori/215562260300005-cesky-narod-je-vynalezavy/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 2.7.13 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3
[debug] Proxy map: {}
[CeskaTelevizePorady] 215562260300005-cesky-narod-je-vynalezavy: Downloading webpage
[CeskaTelevize] iFramePlayer.php: Downloading webpage
[CeskaTelevize] iFramePlayer.php: Downloading JSON metadata
[CeskaTelevize] iFramePlayer.php: Downloading JSON metadata
[CeskaTelevize] iFramePlayer.php: Downloading MPD manifest
[CeskaTelevize] iFramePlayer.php: Downloading MPD manifest
[CeskaTelevize] iFramePlayer.php: Downloading JSON metadata
[CeskaTelevize] iFramePlayer.php: Downloading JSON metadata
[CeskaTelevize] iFramePlayer.php: Downloading m3u8 information
[CeskaTelevize] iFramePlayer.php: Downloading m3u8 information
[download] Downloading playlist: iFramePlayer.php
[CeskaTelevize] playlist iFramePlayer.php: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Invoking downloader on u'http://80.188.78.212:80/aa/cb7a5149b985501a0520bf1e518f3fde/1492417235154/885db2148e423da4bd756134e4920504/dna-61924494877272833-pc/'
[dashsegments] Total fragments: 1352
[download] Destination: Doktoři-61924494877272833.fdash-main-1001-1505.mp4
[download]  99.9% of ~1.10GiB at Unknown speed ETA Unknown ETAERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2106, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal server error
```

The error itself is thrown by fragment 1350 which returns `HTTP 500` no matter what. This problem is very similar to what is described in #12593. However, using `--skip-unavailable-fragments` did not help and the process ends.

**Comment by ankenyr** [comment]
Did you ever get this working? I seem to be seeing this problem also.

**Comment by scholtzm** [comment]
Never got it to work.

Eventualy I sent an e-mail to Ceska Televize and they fixed the issue with fragment 1350 on their end. 😄

**Comment by ankenyr** [comment]
Weird, I used -f u'bestvideo+vestaudio/best' and that worked from the command line. This was for Youtube though

**Comment by mcepl** [comment]
I think this ticket should be closed as well, we don’t have a way how to reproduce it as the situation has changed (youtube-dl 2020.01.01 can download the show without a problem).
