### ISSUE TITLE
Plural Sight - ERROR: No video formats found; please report this issue

### ISSUE THREAD

**Issue by 1kaboom** [ytdl-org/youtube-dl#12763]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', 'https://app.pluralsight.com/library/courses/vnx-block-configuration-operations/table-of-contents', '-o', 'D:\\dwnld\\%(playlist)s/%(chapter_number)s. /%(playlist_index)s. %(title)s.%(ext)s', '--sleep-interval', '50', '--limit-rate', '450K', '--verbose', 'flag']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.04.17
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] vnx-block-configuration-operations: Downloading course JSON
[download] Downloading playlist: VNX Block - Configuration and Operations
[pluralsight:course] playlist VNX Block - Configuration and Operations: Collected 82 video ids (downloading 82 of them)
[download] Downloading video 1 of 82
[pluralsight] Downloading login page
[pluralsight] vnx-block-configuration-operations-m1-0: Downloading JSON metadata
[pluralsight] vnx-block-configuration-operations-m1-0: Downloading mp4-high-widescreen viewclip JSON
WARNING: Unable to download JSON metadata: HTTP Error 403: Unauthorized
[pluralsight] vnx-block-configuration-operations-m1-0: Waiting for 2 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7vri0rse\build\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7vri0rse\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7vri0rse\build\youtube_dl\extractor\pluralsight.py", line 287, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7vri0rse\build\youtube_dl\extractor\common.py", line 1042, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

# youtube-dl -U
youtube-dl is up-to-date (2017.04.17)

**Comment by 1kaboom** [comment]
any update on it.
