### ISSUE TITLE
Support for OnBase Training Videos

### ISSUE THREAD

**Issue by abarber229** [ytdl-org/youtube-dl#12918]
Can you guys add - https://training.onbase.com/en/courses/eLearning and https://training.onbase.com/en/courses/premium. We have a premium login through work, but it has been taking me awhile to grab them individually. I am on version 2017-04-28. Thank you and let me know if you have any questions. 

Here is the logs from the premium:
C:\Box Sync\IT\Austin's Folder\Apps\youtube-dl>youtube-dl --verbose --username XXXXX --password XXXXX"https://training.onbase.com/en/courses/premium/course?cid=P0963" -o "%USERPROFILE%\Downloads\OnBase\ %(playlist)s\%(chapter_number)s. %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s" --sleep-interval 10
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://training.onbase.com/en/courses/premium/course?cid=P0963', '-o', 'C:\\Users\\barbera\\Downloads\\OnBase\\ %(playlist)s\\%(chapter_number)s. %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s', '--sleep-interval', '10']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.04.17
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {}
[generic] course?cid=P0963: Requesting header
WARNING: Falling back on generic information extractor.
[generic] course?cid=P0963: Downloading webpage
[generic] course?cid=P0963: Extracting information
ERROR: Unsupported URL: https://training.onbase.com/en/courses/premium/course?cid=P0963
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7vri0rse\build\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7vri0rse\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7vri0rse\build\youtube_dl\extractor\generic.py", line 2765, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://training.onbase.com/en/courses/premium/course?cid=P0963

Here is the logs for the e-learning:
C:\Box Sync\IT\Austin's Folder\Apps\youtube-dl>youtube-dl --verbose "https://training.onbase.com/en/courses/eLearning/course?cid=E1162" -o "%USERPROFILE%\Downloads\OnBase\ %(playlist)s\%(chapter_number)s. %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s" --sleep-interval 10
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://training.onbase.com/en/courses/eLearning/course?cid=E1162', '-o', 'C:\\Users\\barbera\\Downloads\\OnBase\\ %(playlist)s\\%(chapter_number)s. %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s', '--sleep-interval', '10']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.04.28
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {}
[generic] course?cid=E1162: Requesting header
WARNING: Falling back on generic information extractor.
[generic] course?cid=E1162: Downloading webpage
[generic] course?cid=E1162: Extracting information
ERROR: Unsupported URL: https://training.onbase.com/en/courses/eLearning/course?cid=E1162
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpagq0np72\build\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpagq0np72\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpagq0np72\build\youtube_dl\extractor\generic.py", line 2781, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://training.onbase.com/en/courses/eLearning/course?cid=E1162

**Comment by abarber229** [comment]
Is there anything I can do to help with the support? Thank you!

**Comment by abarber229** [comment]
I tried using the --cookies option but I couldn't get it to work either.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--cookies', 'C:\\Users\\barbera\\Downloads\\cookies.txt', '-o', 'C:\\Users\\barbera\\Downloads\\OnBase\\%(playlist_index)s - %(title)s.%(ext)s', '--min-sleep-interval', '31', '--max-sleep-interval', '32', 'https://training.onbase.com/en/courses/premium/course?cid=P1389']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.07.30.1
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {}
[generic] course?cid=P1389: Requesting header
WARNING: Falling back on generic information extractor.
[generic] course?cid=P1389: Downloading webpage
[generic] course?cid=P1389: Extracting information
ERROR: Unsupported URL: https://training.onbase.com/en/courses/premium/course?cid=P1389
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\generic.py", line 2944, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://training.onbase.com/en/courses/premium/course?cid=P1389

**Comment by abarber229** [comment]
c:\Users\barbera\Box\Austin's Folder\Apps\youtube-dl>youtube-dl -U
youtube-dl is up-to-date (2019.03.09)

c:\Users\barbera\Box\Austin's Folder\Apps\youtube-dl>youtube-dl --verbose --cookies="C:\Temp\cookies.txt" "https://training.hyland.com/courses/E1255-Workflow-and-OnBase-Studio-A-Quick-Look" -o "%USERPROFILE%\Downloads\OnBase\%(playlist)s/%(chapter_number)s. %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s" --sleep-interval 15
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--cookies=C:\\Temp\\cookies.txt', 'https://training.hyland.com/courses/E1255-Workflow-and-OnBase-Studio-A-Quick-Look', '-o', 'C:\\Users\\barbera\\Downloads\\OnBase\\%(playlist)s/%(chapter_number)s. %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s', '--sleep-interval', '15']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.03.09
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[generic] E1255-Workflow-and-OnBase-Studio-A-Quick-Look: Requesting header
WARNING: Falling back on generic information extractor.
[generic] E1255-Workflow-and-OnBase-Studio-A-Quick-Look: Downloading webpage
[generic] E1255-Workflow-and-OnBase-Studio-A-Quick-Look: Extracting information
ERROR: Unsupported URL: https://training.hyland.com/courses/E1255-Workflow-and-OnBase-Studio-A-Quick-Look
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy110f8qy\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy110f8qy\build\youtube_dl\extractor\common.py", line 522, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy110f8qy\build\youtube_dl\extractor\generic.py", line 3320, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://training.hyland.com/courses/E1255-Workflow-and-OnBase-Studio-A-Quick-Look

I can email someone my username and password if they provide a email address please. 

Thank you!
