### ISSUE TITLE
Subtitle problem on some videos

### ISSUE THREAD

**Issue by keybounce** [ytdl-org/youtube-dl#13097]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.14**
 - git fetch of 7073015a23f96ce8ca0400286051d53cb9237a9f (master at this time)

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

I'm running into issues with subtitles on some videos.

```
keybounceMBP:AdultSwim michael$ youtube-dl -v http://www.adultswim.com/videos/samurai-jack/xcii/
[debug] System config: []
[debug] User config: ['-o', '%(series)s/s%(season_number)02d-e%(episode_number)02d-%(title)s.%(ext)s', '-f', '\nbest[ext=mp4][height>431][height<=576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', '--ap-mso', 'Dish', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--write-sub', '--write-auto-sub', '--sub-lang', 'en,enUS,en-us', '--sub-format', 'ass/srt/best', '--convert-subs', 'ass', '--embed-subs', '--recode-video', 'mp4', '--mark-watched']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.adultswim.com/videos/samurai-jack/xcii/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.14
[debug] Python version 3.6.1 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[AdultSwim] xcii: Downloading webpage
[AdultSwim] I3Yw7ynsSUqU5H2jNpRKKg: Downloading XML
[AdultSwim] I3Yw7ynsSUqU5H2jNpRKKg-0: Downloading m3u8 information
[AdultSwim] I3Yw7ynsSUqU5H2jNpRKKg-0: Downloading f4m manifest
[AdultSwim] I3Yw7ynsSUqU5H2jNpRKKg-0: Downloading f4m manifest
[AdultSwim] I3Yw7ynsSUqU5H2jNpRKKg-0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[AdultSwim] I3Yw7ynsSUqU5H2jNpRKKg-0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[AdultSwim] I3Yw7ynsSUqU5H2jNpRKKg-0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[AdultSwim] I3Yw7ynsSUqU5H2jNpRKKg-0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
WARNING: enUS subtitles not available for I3Yw7ynsSUqU5H2jNpRKKg
WARNING: en-us subtitles not available for I3Yw7ynsSUqU5H2jNpRKKg
[info] Writing video subtitles to: Samurai Jack/s05-e01-Samurai Jack - XCII.en.tt
[debug] Invoking downloader on 'http://amd.cdn.turner.com/adultswim/episodes/us_geo/samjack/2017/03/samjack_cc_092_Digital_XCII_bajtweuyuav8w6tva8/hls/samjack_cc_092_Digital_XCII_bajtweuyuav8w6tva8_stream_7.m3u8'
[download] Samurai Jack/s05-e01-Samurai Jack - XCII.mp4 has already been downloaded
[download] 100% of 581.29MiB
[ffmpeg] Not converting video file Samurai Jack/s05-e01-Samurai Jack - XCII.mp4 - already is in target format mp4
[ffmpeg] Converting subtitles
WARNING: You have requested to convert dfxp (TTML) subtitles into another format, which results in style information loss
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/michael/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/Users/michael/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/Users/michael/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1896, in download
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 771, in extract_info
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 825, in process_ie_result
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1539, in process_video_result
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1877, in process_info
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1942, in post_process
  File "/Users/michael/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 589, in run
  File "/Users/michael/bin/youtube-dl/youtube_dl/utils.py", line 2672, in dfxp2srt
  File "/Users/michael/bin/youtube-dl/youtube_dl/compat.py", line 2497, in compat_etree_fromstring
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/etree/ElementTree.py", line 1315, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
keybounceMBP:AdultSwim michael$ 
```

NB: The subtitle file is *empty*.

**Comment by arf1372** [comment]
@keybounce Is this still an issue? (I followed the link you provided and received a 404)

**Comment by keybounce** [comment]
I'll update & test this weekend.

**Comment by arf1372** [comment]
Any news on this?
