### ISSUE TITLE
BBC downloads failing (from within the UK)

### ISSUE THREAD

**Issue by larryy** [ytdl-org/youtube-dl#13110]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.14**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl --verbose -o have-i-got-a-bit-more-news-for-you-series-53-episode-4.mp4 http://www.bbc.co.uk/iplayer/episode/b08r8wp6/have-i-got-a-bit-more-news-for-you-series-53-episode-4
[debug] System config: []
[debug] User config: [u'--prefer-ffmpeg', u'--sub-lang', u'en', u'--write-sub', u'--convert-subtitles', u'srt', u'--merge-output-format', u'mp4']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-o', u'have-i-got-a-bit-more-news-for-you-series-53-episode-4.mp4', u'http://www.bbc.co.uk/iplayer/episode/b08r8wp6/have-i-got-a-bit-more-news-for-you-series-53-episode-4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.14
[debug] Python version 2.7.6 - Linux-3.13.0-79-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.6, avprobe 11.6, ffmpeg N-78590-g5590ab4, ffprobe N-78590-g5590ab4
[debug] Proxy map: {}
[bbc.co.uk] b08r8wp6: Downloading video page
[bbc.co.uk] b08r8wp6: Downloading playlist JSON
[bbc.co.uk] b08r8wp4: Downloading media selection XML
[bbc.co.uk] b08r8wp4: Downloading m3u8 information
[bbc.co.uk] b08r8wp4: Downloading m3u8 information
[bbc.co.uk] b08r8wp4: Downloading m3u8 information
[bbc.co.uk] b08r8wp4: Downloading m3u8 information
[bbc.co.uk] b08r8wp4: Downloading MPD manifest
[bbc.co.uk] b08r8wp4: Downloading MPD manifest
[bbc.co.uk] b08r8wp4: Downloading m3u8 information
[bbc.co.uk] b08r8wp4: Downloading m3u8 information
[bbc.co.uk] b08r8wp4: Downloading m3u8 information
[bbc.co.uk] b08r8wp4: Downloading m3u8 information
[bbc.co.uk] b08r8wp4: Downloading m3u8 information
[bbc.co.uk] b08r8wp4: Downloading m3u8 information
[bbc.co.uk] b08r8wp4: Downloading MPD manifest
[bbc.co.uk] b08r8wp4: Downloading MPD manifest
[bbc.co.uk] b08r8wp4: Downloading m3u8 information
[bbc.co.uk] b08r8wp4: Downloading m3u8 information
[bbc.co.uk] b08r8wp4: Downloading m3u8 information
[bbc.co.uk] b08r8wp4: Downloading m3u8 information
[bbc.co.uk] b08r8wp4: Downloading captions
[bbc.co.uk] b08r8wp4: Downloading captions
[bbc.co.uk] b08r8wp4: Downloading captions
[info] Writing video subtitles to: have-i-got-a-bit-more-news-for-you-series-53-episode-4.en.ttml
[debug] Invoking downloader on u'https://vod-dash-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_hd/18c194-b08r8wp4/vf_b08r8wp4_b5e319f6-6731-44de-b43b-ed59418f42d8.ism.hlsv2.ism/dash/'
[dashsegments] Total fragments: 661
[download] Destination: have-i-got-a-bit-more-news-for-you-series-53-episode-4.fstream-uk-iptv_streaming_concrete_combined_hd_mf_limelight_uk_dash_https-video=5070000.mp4
[download] 100% of 1.36GiB in 04:15
[debug] Invoking downloader on u'https://vod-dash-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_hd/18c194-b08r8wp4/vf_b08r8wp4_b5e319f6-6731-44de-b43b-ed59418f42d8.ism.hlsv2.ism/dash/'
[dashsegments] Total fragments: 661
[download] Destination: have-i-got-a-bit-more-news-for-you-series-53-episode-4.mp4.fstream-uk-iptv_streaming_concrete_combined_hd_mf_limelight_uk_dash_https-audio_eng=128000
[download] 100% of 38.40MiB in 02:06
[ffmpeg] Merging formats into "have-i-got-a-bit-more-news-for-you-series-53-episode-4.mp4"
[debug] ffmpeg command line: ffmpeg -y -i file:have-i-got-a-bit-more-news-for-you-series-53-episode-4.fstream-uk-iptv_streaming_concrete_combined_hd_mf_limelight_uk_dash_https-video=5070000.mp4 -i file:have-i-got-a-bit-more-news-for-you-series-53-episode-4.mp4.fstream-uk-iptv_streaming_concrete_combined_hd_mf_limelight_uk_dash_https-audio_eng=128000 -c copy -map 0:v:0 -map 1:a:0 file:have-i-got-a-bit-more-news-for-you-series-53-episode-4.temp.mp4
ERROR: Conversion failed!
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1942, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 479, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 204, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: Conversion failed!
```

---

### Description of your *issue*, suggested solution and other information

I have been using youtube-dl to download from BBC's iPlayer for a while.  About three days ago it stopped working.  Instead of the expected show-name.mp4 and show-name.en.srt files I get long, complicated filenames with extensions like .part, .part-Frag1, .ytdl, .temp.mp4, and no extension.  I had been running an earlier version of youtube-dl, but I upgraded to the latest version and it didn't help.  A complete example is shown above.  You'll need to be in the UK to get even this far, but presumably if you just try my exact command you should get my exact failure.

**Comment by larryy** [comment]
This appears to be due either to a -f flag or to some odd interaction amongst -o flags.  I had forgotten I set up a youtube-dl.config file, containing the following:

```
--sub-lang 'en'
--write-sub
--convert-subtitles 'srt'
--embed-subs
-o '/home/larryy/video/%(title)s [%(resolution)s].%(ext)s'
-f 'bestvideo+bestaudio/best'
--merge-output-format mp4
```

In some testing, I removed the -f flag from my config file and typed just this on the command line:

```
$ youtube-dl http://www.bbc.co.uk/iplayer/episode/b08r8wp6/have-i-got-a-bit-more-news-for-you-series-53-episode-4
```

And it downloaded successfully, to files named "Have I Got a Bit More News for You, Series 53, Episode 4-b08r8wp4.mp4" and "Have I Got a Bit More News for You, Series 53, Episode 4-b08r8wp4.en.srt".

Note that the name does not include the resolution, despite it being specified in the config's -o specification.  And it does include the PID on the end.

I am experimenting with restoring my command-line override of the -o value (I need a controllable, specifiable filename, as I normally run youtube-dl from a script and need to move the file once the download is complete).  That will tell me whether the better behavior is related to removing the config's -f param or the command-line's -o param.  Will update tomorrow sometime.

**Comment by larryy** [comment]
It's the -f 'bestvideo+bestaudio/best' flag.  I can override the -o flag as always and things work fine.  But if that -f flag is present the download is broken.

**Comment by mcepl** [comment]
yup, the same happened to me (from Czech Republic, I think UK location is a red herring here):
```
matej@mitmanek: ~$ youtube-dl --verbose 'http://www.bbc.com/news/av/world-us-canada-41687716/george-w-bush-decries-bigotry-and-conspiracy-theories'
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.bbc.com/news/av/world-us-canada-41687716/george-w-bush-decries-bigotry-and-conspiracy-theories']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.15.1
[debug] Python version 2.7.5 - Linux-3.10.0-733.el7.x86_64-x86_64-with-redhat-7.5-Maipo
[debug] exe versions: ffmpeg 2.8.13, ffprobe 2.8.13, rtmpdump 2.4
[debug] Proxy map: {}
[bbc] george-w-bush-decries-bigotry-and-conspiracy-theories: Downloading webpage
[bbc] p05kdqnm: Downloading media selection XML
[bbc] p05kdqnm: Downloading m3u8 information
[bbc] p05kdqnm: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc] p05kdqnm: Downloading MPD manifest
[bbc] p05kdqnm: Downloading m3u8 information
[bbc] p05kdqnm: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc] p05kdqnm: Downloading MPD manifest
[bbc] p05kdqnm: Downloading m3u8 information
[bbc] p05kdqnm: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc] p05kdqnm: Downloading MPD manifest
[bbc] p05kdqnm: Downloading m3u8 information
[bbc] p05kdqnm: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc] p05kdqnm: Downloading MPD manifest
[download] Downloading playlist: George W Bush: 'Bigotry seems emboldened'
[bbc] playlist George W Bush: 'Bigotry seems emboldened': Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://vod-dash-ww-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd/7d5177-p05kdqnm/vf_p05kdqnm_7f5e897c-fadd-4be6-8bdc-16100b1c4646.ism.hlsv2.ism/dash/'
[download] George W Bush decries bigotry and conspiracy theories-p05kdqnm.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-video=1570000.mp4 has already been downloaded
[download] 100% of 12.08MiB
[debug] Invoking downloader on u'https://vod-dash-ww-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd/7d5177-p05kdqnm/vf_p05kdqnm_7f5e897c-fadd-4be6-8bdc-16100b1c4646.ism.hlsv2.ism/dash/'
[download] George W Bush decries bigotry and conspiracy theories-p05kdqnm.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-audio_eng_1=128000.m4a has already been downloaded
[download] 100% of 1.01MiB
[ffmpeg] Merging formats into "George W Bush decries bigotry and conspiracy theories-p05kdqnm.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:George W Bush decries bigotry and conspiracy theories-p05kdqnm.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-video=1570000.mp4' -i 'file:George W Bush decries bigotry and conspiracy theories-p05kdqnm.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-audio_eng_1=128000.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:George W Bush decries bigotry and conspiracy theories-p05kdqnm.temp.mp4'
ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 2030, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/lib/python2.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 479, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/lib/python2.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 204, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
```
And yes, if I download particular format (not the automatic one), everything is perfectly working.

**Comment by dirkf** [comment]
Tested http://www.bbc.com/news/av/world-us-canada-41687716/george-w-bush-decries-bigotry-and-conspiracy-theories with
* yt-dl-2021.02.10, Linux x86, ffmpeg-4.3, python-3.5: all OK
* yt-dl-2021.03.25, Linux MIPS32, ffmpeg-4.1, python-2.7: all OK

Probably fixed ages ago.
 with pyth

**Comment by mcepl** [comment]
Yup, I can confirm. This ticket should be closed.
