### ISSUE TITLE
[BBCA / AMC] Class: Unable to extract media URL

### ISSUE THREAD

**Issue by keybounce** [ytdl-org/youtube-dl#13607]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.02**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

```
keybounceMBP:BBCA michael$ youtube-dl -v http://www.bbcamerica.com/shows/class/season-1/episode-01-for-tonight-we-might-die
[debug] System config: []
[debug] User config: ['-k', '-o', '%(title)s.%(ext)s', '-f', '\nbest[ext=mp4][height>431][height<=576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', '--ap-mso', 'Dish', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--write-sub', '--write-auto-sub', '--sub-lang', 'en,enUS,en-us', '--sub-format', 'ass/srt/best', '--convert-subs', 'ass', '--embed-subs', '--mark-watched', '--download-archive', 'downloaded-videos.txt']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.bbcamerica.com/shows/class/season-1/episode-01-for-tonight-we-might-die']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.02
[debug] Python version 3.6.1 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[AMCNetworks] episode-01-for-tonight-we-might-die: Downloading webpage
ERROR: Unable to extract media url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/amcnetworks.py", line 64, in _real_extract
    webpage, 'media url')
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 782, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract media url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

This is with master @ d852c6bc5995444096a6c07b66ea075269412cf7 (July 7th)

... and the same thing happens with master @ tag release 2017.07.02. Odd -- doctor who episodes gave me no trouble, only the new "class" show did.

```
keybounceMBP:BBCA michael$ ./yt-dl -v http://www.bbcamerica.com/shows/doctor-who/full-episodes/season-10/episode-12-the-doctor-falls
[debug] System config: []
[debug] User config: ['-k', '-o', '%(title)s.%(ext)s', '-f', '\nbest[ext=mp4][height>431][height<=576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', '--ap-mso', 'Dish', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--write-sub', '--write-auto-sub', '--sub-lang', 'en,enUS,en-us', '--sub-format', 'ass/srt/best', '--convert-subs', 'ass', '--embed-subs', '--mark-watched', '--download-archive', 'downloaded-videos.txt']
[debug] Custom config: []
[debug] Command-line args: ['--hls-prefer-native', '-o', '%(series)s/s%(season_number)02d-e%(episode_number)02d-%(title)s.%(ext)s', '-v', 'http://www.bbcamerica.com/shows/doctor-who/full-episodes/season-10/episode-12-the-doctor-falls']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.02
[debug] Python version 3.6.1 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[AMCNetworks] episode-12-the-doctor-falls: Downloading webpage
[AMCNetworks] episode-12-the-doctor-falls: Downloading JSON metadata
[AMCNetworks] JDb7A7KL9wvY: Retrieving Authorization Token
[AMCNetworks] JDb7A7KL9wvY: Retrieving Media Token
[AMCNetworks] JDb7A7KL9wvY: Downloading SMIL data
[AMCNetworks] JDb7A7KL9wvY: Downloading m3u8 information
WARNING: enUS subtitles not available for JDb7A7KL9wvY
WARNING: en-us subtitles not available for JDb7A7KL9wvY
[download] Doctor Who - Season 10 - The Doctor Falls has already been recorded in archive
keybounceMBP:BBCA michael$ 
```

**Comment by keybounce** [comment]
EDIT: Or, maybe not. It says on the website, 

 The first episode is available FREE on BBCAmerica.com, on the BBCA app, and On Demand. New episodes of Season 1 premiere on BBC America Saturdays after Doctor Who.	

But in fact I can't actually find it in a browser no matter where on the site I look.

Unless I want to buy it from iTunes, etc.

**Comment by gkoelln** [comment]
I had downloaded them all within a week after they were released online.  It looks like they've all expired by now.

**Comment by Fadavvi** [comment]
No media link found in target URL. They've all expired. Issue can be close after 2.5 year!
