### ISSUE TITLE
[common] _parse_mpd_formats doesn't handle range-based segment lists

### ISSUE THREAD

**Issue by glogachov** [ytdl-org/youtube-dl#13784]
this site has changed streaming procedure at 2007/7/31 
>youtube-dl.exe http://www.thisav.com/video/300708/99-06-0776.html --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.thisav.com/video/300708/99-06-0776.html', '--verbose']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2017.07.30.1
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[ThisAV] 300708: Downloading webpage
[ThisAV] 300708: Downloading MPD manifest
ERROR: An extractor error has occurred. (caused by KeyError('sourceURL',)); please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 433
, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\thisav.py", line 53,
 in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 216
4, in _parse_html5_media_entries
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 212
5, in _media_formats
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 173
7, in _extract_mpd_formats
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 187
1, in _parse_mpd_formats
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 179
8, in extract_multisegment_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 179
3, in extract_Initialization
KeyError: 'sourceURL'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 433
, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\thisav.py", line 53,
 in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 216
4, in _parse_html5_media_entries
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 212
5, in _media_formats
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 173
7, in _extract_mpd_formats
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 187
1, in _parse_mpd_formats
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 179
8, in extract_multisegment_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 179
3, in extract_Initialization
KeyError: 'sourceURL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\YoutubeDL.py", line 776, in ex
tract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 446
, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('sourceURL',)); please report this issu
e on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call yout
ube-dl with the --verbose flag and include its complete output.

**Comment by mogu1121** [comment]
310005.mpd > 310005_dashinit.mp4
