### ISSUE TITLE
iprima Change url

### ISSUE THREAD

**Issue by JZD3** [ytdl-org/youtube-dl#14504]
Hi, prima has changed the url from play.iprima.cz to prima.iprima.cz. I can't download anything from prima.iprima.cz anymore. Please help.
```
[as@localhost trube-dl]$ ./youtube-dl -v http://prima.iprima.cz/partie/08102017
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://prima.iprima.cz/partie/08102017']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.15.1
[debug] Python version 2.7.13 - Linux-4.12.14-desktop-1.mga7-x86_64-with-mageia-7-Cauldron
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 08102017: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 08102017: Downloading webpage
[generic] 08102017: Extracting information
ERROR: Unsupported URL: http://prima.iprima.cz/partie/08102017
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 2159, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "./youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "./youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 146, column 22
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 3059, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://prima.iprima.cz/partie/08102017

[as@localhost trube-dl]$

**Comment by jirih** [comment]
This example is not geo-restricted:
http://prima.iprima.cz/porady/polda/laska-na-klic
