### ISSUE TITLE
Cannot download someof the videos on http://bfmbusiness.bfmtv.com

### ISSUE THREAD

**Issue by ericgrancher** [ytdl-org/youtube-dl#14868]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
youtube-dl --verbose "http://bfmbusiness.bfmtv.com/mediaplayer/video/nicolas-sadirac-directeur-general-de-l-ecole-42-2311-22-1006155.html"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://bfmbusiness.bfmtv.com/mediaplayer/video/nicolas-sadirac-directeur-general-de-l-ecole-42-2311-22-1006155.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.26
[debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[generic] nicolas-sadirac-directeur-general-de-l-ecole-42-2311-22-1006155: Requesting header
WARNING: Falling back on generic information extractor.
[generic] nicolas-sadirac-directeur-general-de-l-ecole-42-2311-22-1006155: Downloading webpage
[generic] nicolas-sadirac-directeur-general-de-l-ecole-42-2311-22-1006155: Extracting information
[download] Downloading playlist: Nicolas Sadirac, directeur général de l'école 42 - 23/11 (2/2)
[generic] playlist Nicolas Sadirac, directeur général de l'école 42 - 23/11 (2/2): Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:legacy] 5656129553001: Downloading webpage
[brightcove:legacy] 5656129553001: Extracting information
ERROR: Unable to extract video url for 5656129553001; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 304, in _real_extract
    videoPlayer[0], query, referer=referer)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 335, in _get_video_info
    return self._extract_video_info(video_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 448, in _extract_video_info
    raise ExtractorError('Unable to extract video url for %s' % video_id)
ExtractorError: Unable to extract video url for 5656129553001; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

- Single video: http://bfmbusiness.bfmtv.com/mediaplayer/video/nicolas-sadirac-directeur-general-de-l-ecole-42-2311-22-1006155.html
- note that it works for some other videos like http://bfmbusiness.bfmtv.com/entreprise/droit-a-l-erreur-les-principales-mesures-du-projet-de-loi-1313821.html

**Comment by motdiem** [comment]
FWIW I can reproduce this on version **2018.02.08**


```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://bfmbusiness.bfmtv.com/mediaplayer/video/hello-startup-kumbu-aide-les-particuliers-a-enregistrer-de-facon-perenne-n-importe-quel-souvenir-numerique-0902-1032787.html', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.08
[debug] Python version 2.7.10 (CPython) - Darwin-17.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[generic] hello-startup-kumbu-aide-les-particuliers-a-enregistrer-de-facon-perenne-n-importe-quel-souvenir-numerique-0902-1032787: Requesting header
WARNING: Falling back on generic information extractor.
[generic] hello-startup-kumbu-aide-les-particuliers-a-enregistrer-de-facon-perenne-n-importe-quel-souvenir-numerique-0902-1032787: Downloading webpage
[generic] hello-startup-kumbu-aide-les-particuliers-a-enregistrer-de-facon-perenne-n-importe-quel-souvenir-numerique-0902-1032787: Extracting information
[download] Downloading playlist: Hello startup : Kumbu aide les particuliers à enregistrer de façon pérenne n'importe quel souvenir numérique - 09/02
[generic] playlist Hello startup : Kumbu aide les particuliers à enregistrer de façon pérenne n'importe quel souvenir numérique - 09/02: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:legacy] 5727303756001: Downloading webpage
[brightcove:legacy] 5727303756001: Extracting information
ERROR: Unable to extract video url for 5727303756001; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 304, in _real_extract
    videoPlayer[0], query, referer=referer)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 335, in _get_video_info
    return self._extract_video_info(video_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 448, in _extract_video_info
    raise ExtractorError('Unable to extract video url for %s' % video_id)
ExtractorError: Unable to extract video url for 5727303756001; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

Url : http://bfmbusiness.bfmtv.com/mediaplayer/video/hello-startup-kumbu-aide-les-particuliers-a-enregistrer-de-facon-perenne-n-importe-quel-souvenir-numerique-0902-1032787.html
