### ISSUE TITLE
Error in Medialaan Extractor Login Page

### ISSUE THREAD

**Issue by ndswaef** [ytdl-org/youtube-dl#14871]
- [ x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.26**

- [x  ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vtm.be/video/volledige-afleveringen/id/vtm_20171122_VM067B98C_vtmwatch', '--username', 'PRIVATE', '--password', 'PRIVATE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.11.26
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[Medialaan] vtm_20171122_VM067B98C_vtmwatch: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\YoutubeDL.py", line 1986, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\extractor\medialaan.py", line 168, in _real_extract
IndexError: list index out of range
...
<end of log>
```

**Comment by haveneersrobin** [comment]
I have the same error, even with one of the test-urls provided in medialaan.py:

```
youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' 'http://vtmkzoom.be/k3-dansstudio/een-nieuw-seizoen-van-k3-dansstudio' --username PRIVATE --password PRIVATE
[Medialaan] een-nieuw-seizoen-van-k3-dansstudio: Downloading webpage
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 471, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 461, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1989, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 785, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/medialaan.py", line 168, in _real_extract
IndexError: list index out of range
```

See also #14702.

**Comment by kenavera** [comment]
@dstftw I believe this issue can be closed, due to my pull request (referenced above).
