### ISSUE TITLE
[Vimeo] Downloading Channel/Album - Unable to extract list title

### ISSUE THREAD

**Issue by rudedogg** [ytdl-org/youtube-dl#15704]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

Attempted to download a channel/album and recieved this error. Tried both `2018.02.22` and `2018.02.26`

*Command:*

```shell
youtube-dl "https://vimeo.com/album/4786409" -v
```

*Output:*

```shell
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vimeo.com/album/4786409', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.26
[debug] Python version 3.6.3 (CPython) - Darwin-17.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[vimeo:album] 4786409: Downloading page 1
ERROR: Unable to extract list title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 855, in _real_extract
    return self._extract_videos(album_id, 'https://vimeo.com/album/%s' % album_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 791, in _extract_videos
    list_title = next(title_and_entries)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 768, in _title_and_entries
    yield self._extract_list_title(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 730, in _extract_list_title
    return self._TITLE or self._html_search_regex(self._TITLE_RE, webpage, 'list title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 805, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 796, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract list title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by kayb94** [comment]
I'm working on it.

**Comment by tempseptember** [comment]
`youtube-dl.exe --verbose "https://vimeo.com/album/5024368"`

> debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://vimeo.com/album/5024368']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.03.10
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 2.8.4
[debug] Proxy map: {}
[vimeo:album] 5024368: Downloading page 1
ERROR: Unable to extract list title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\extractor\vimeo.py", line 864, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\extractor\vimeo.py", line 800, in _extract_videos
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\extractor\vimeo.py", line 777, in _title_and_entries
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\extractor\vimeo.py", line 739, in _extract_list_title
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\extractor\common.py", line 805, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzznjsz2q\build\youtube_dl\extractor\common.py", line 796, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract list title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by PSlava** [comment]
It doesn't fix extraction of password protected albums!

**Comment by kayb94** [comment]
That's not what I tried to achieve. Step by step.

**Comment by pikurasa** [comment]
> It doesn't fix extraction of password protected albums!

I just ran into this issue trying to download a password protected album.

Thanks for all of the efforts so far. Please let us know once it has been fixed.

I am running `[debug] youtube-dl version 2018.04.16`

**Comment by jhormigo** [comment]
Any updates on this? I am getting the same error.

**Comment by ArondeParon** [comment]
Same.

**Comment by cyhojoey** [comment]
Any update? I have the same question.

**Comment by Vrihub** [comment]
FYI I am experiencing this problem also with albums that are NOT password-protected

**Comment by LearnSomethingNewEveryDay** [comment]
Same error for me.

**Comment by ckalinwi** [comment]
Same error for me.  Python version is 2.7.12.

**Comment by ckalinwi** [comment]
Still a problem under 2019.02.18
