### ISSUE TITLE
Support for NRK Radio podcasts

### ISSUE THREAD

**Issue by forthrin** [ytdl-org/youtube-dl#16097]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.03**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Site support request (request for adding support for a new site)

---

```
$ youtube-dl --verbose https://radio.nrk.no/podcast/ulrikkes_univers/nrkno-poddkast-26588-134079-05042018030000
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://radio.nrk.no/podcast/ulrikkes_univers/nrkno-poddkast-26588-134079-05042018030000']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.03
[debug] Python version 2.7.10 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] nrkno-poddkast-26588-134079-05042018030000: Requesting header
WARNING: Falling back on generic information extractor.
[generic] nrkno-poddkast-26588-134079-05042018030000: Downloading webpage
[generic] nrkno-poddkast-26588-134079-05042018030000: Extracting information
ERROR: Unsupported URL: https://radio.nrk.no/podcast/ulrikkes_univers/nrkno-poddkast-26588-134079-05042018030000
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2205, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 16, column 69
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3143, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://radio.nrk.no/podcast/ulrikkes_univers/nrkno-poddkast-26588-134079-05042018030000
$

```

**Comment by barsnick** [comment]
Strictly speaking, NRK Radio is already well supported. This URL is special as it is a (possibly new) podcast-only program.

(I suggest to rename this issue to "Support for NRK Radio podcasts", and make it a site request.)

I assume it uses the identical hosting to the other programs, so an adaptation of the NRKRadio extractor to support this URL might be sufficient. I haven't checked myself though.

(Forresten, elsker Ulrikkes podkast!)
