### ISSUE TITLE
Add Support for Hulu

### ISSUE THREAD

**Issue by EveryDirection** [ytdl-org/youtube-dl#1629]
Site support request: Please add support for Hulu. It is one of the most popular video streaming sites on the Internet. Thank you.

**Comment by TRox1972** [comment]
Geo-restricted to the US.

**Comment by yan12125** [comment]
From #9699:
http://www.hulu.com/watch/249832#i0,p0,d0
http://www.hulu.com/watch/372928#i0,p6,d2

**Comment by keybounce** [comment]
Wow, I also ran into hulu not working:

```
keybounceMBP:Keybounce michael$ youtube-dl -v 'http://www.hulu.com/grid/steven-universe?video_type=episode'
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s.%(ext)s', u'-f', u'\nbest[ext=mp4][height>431][height<=720]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', u'--write-sub', u'--embed-subs', u'--recode-video', u'mp4', u'--mark-watched']
[debug] Command-line args: [u'-v', u'http://www.hulu.com/grid/steven-universe?video_type=episode']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.16
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.1, ffprobe 3.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] steven-universe?video_type=episode: Requesting header
WARNING: Falling back on generic information extractor.
[generic] steven-universe?video_type=episode: Downloading webpage
[generic] steven-universe?video_type=episode: Extracting information
ERROR: Unsupported URL: http://www.hulu.com/grid/steven-universe?video_type=episode
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1565, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/Users/michael/bin/youtube-dl/youtube_dl/compat.py", line 2525, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/Users/michael/bin/youtube-dl/youtube_dl/compat.py", line 2514, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 57, column 151
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info
    ie_result = ie.extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2282, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.hulu.com/grid/steven-universe?video_type=episode
```

**Comment by yan12125** [comment]
It uses DRM. AFAIK there's no Python package to decrypt them yet, but only C++ modules (https://github.com/rg3/youtube-dl/issues/1753#issuecomment-228629747).

**Comment by DJPlaya** [comment]
> Geo-restricted to the US.
They even send Positioning Requests to the Browser.
Some VPNs are blocked, but had Success with Proton and the Opera VPN

**Comment by NSExceptional** [comment]
No one wants to work on Netflix or Hulu apparently 😐

**Comment by 89z** [comment]
Issue should be closed, no URL given
