### ISSUE TITLE
[prosiebensat1] Download from prosieben.de not possible (caused by KeyError('sources',))

### ISSUE THREAD

**Issue by duracell** [ytdl-org/youtube-dl#16325]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.25**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### Log

```
^C:\Users\username\Downloads>youtube-dl.exe -v https://www.prosieben.de/tv/beste-show-der-welt/videos/episode-05
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.prosieben.de/tv/beste-show-der-welt/videos/episode-05']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.04.25
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[prosiebensat1] tv/beste-show-der-welt/videos/episode-05: Downloading webpage
[prosiebensat1] 5450626: Downloading videos JSON
ERROR: An extractor error has occurred. (caused by KeyError('sources',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\prosiebensat1.py", line 450, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\prosiebensat1.py", line 399, in _extract_clip
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\prosiebensat1.py", line 35, in _extract_video_info
KeyError: 'sources'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\prosiebensat1.py", line 450, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\prosiebensat1.py", line 399, in _extract_clip
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\prosiebensat1.py", line 35, in _extract_video_info
KeyError: 'sources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\YoutubeDL.py", line 789, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\common.py", line 453, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('sources',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*
The download of the video is not possible, I tried different other episodes of this show, but it's always the same error "KeyError('sources',)". There were no other issues with this error or other helpful issues for this extractor.

**Comment by duracell** [comment]
Any idea how to fix this?

**Comment by remitamine** [comment]
there is no video on this page the actual video URL is:
https://www.prosieben.de/tv/beste-show-der-welt/videos/31-folge-5-ganze-folge
