### ISSUE TITLE
urlopen error unknown url type: abemafresh (error occurs at Freshlive)

### ISSUE THREAD

**Issue by gaeaearth** [ytdl-org/youtube-dl#16381]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
SangEunui-MacBook-Pro:Downloads gaeaearth$ youtube-dl https://freshlive.tv/sakuragakuin/199585 --cookies cookies.txt -f hls-3430 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://freshlive.tv/sakuragakuin/199585', u'--cookies', u'cookies.txt', u'-f', u'hls-3430', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.01
[debug] Python version 2.7.10 (CPython) - Darwin-17.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0
[debug] Proxy map: {}
[FreshLive] 199585: Downloading webpage
[FreshLive] 199585: Downloading m3u8 information
[debug] Invoking downloader on u'https://movie.freshlive.tv/playlist/2100414.m3u8?token=199585t0512d45b173531fb715ba3b7114e33cb6510&v=4'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1961
[download] Destination: #FRESHマンデー 「さくら学院の顔笑れ!!FRESH!マンデー」#43-199585.mp4
[download]   0.1% of ~1.36GiB at Unknown speed ETA Unknown ETAERROR: unable to download video data: <urlopen error unknown url type: abemafresh>
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1900, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1839, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 365, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 168, in real_download
    self._prepare_url(info_dict, decrypt_info['URI'])).read()
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2203, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 454, in _open
    'unknown_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1265, in unknown_open
    raise URLError('unknown url type: %s' % type)
URLError: <urlopen error unknown url type: abemafresh>

```

I install all the lastest version for ffmpeg and youtube-dl, and I also install pycrypto. but I obtain this error message. How can I solve this problem?
The video url is https://freshlive.tv/sakuragakuin/199585 (but it will be closed at 05/08 (because it is opened only for 1 weeks), then, I will replace into another url).
It will need cookies file, so I attach cookies file. https://www.dropbox.com/s/rempg686kkyc4j1/cookies.txt?dl=0

Please help me to solve this problem.

**Comment by gaeaearth** [comment]
I add new video url, https://freshlive.tv/sakuragakuin/219581
and cookie file, https://www.dropbox.com/s/vc1iqyt93n5ah9t/cookies.txt?dl=0
Now, My youtube-dl is lastest version, but still does not work for paid contents.
If you want, I will send my account. Please help me.
