### ISSUE TITLE
Download not working (?utm issue)

### ISSUE THREAD

**Issue by edxdebugging2** [ytdl-org/youtube-dl#16570]
youtube-dl version 2018.03.14
Python version 3.6.5 (CPython) - Linux-4.15.0-22-lowlatency-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs 2.1.1, rtmpdump 2.4

user@H3U1:~$ youtube-dl -v https://www.learndutch.org/free-dutch-grammar-preview-lesson/?utm_source=Weekly+newletter+Learndutch.org&utm_campaign=3b57dc5dcb-startsubclause_COPY_01&utm_medium=email&utm_term=0_efbe1f10f1-3b57dc5dcb-266208549&mc_cid=3b57dc5dcb&mc_eid=6b905899c0
[1] 4620
[2] 4621
[3] 4622
[4] 4623
[5] 4624
[2]   Done                    utm_campaign=3b57dc5dcb-startsubclause_COPY_01
[4]-  Done                    utm_term=0_efbe1f10f1-3b57dc5dcb-266208549
user@H3U1:~$ [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.learndutch.org/free-dutch-grammar-preview-lesson/?utm_source=Weekly+newletter+Learndutch.org']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.6.5 (CPython) - Linux-4.15.0-22-lowlatency-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ?utm_source=Weekly+newletter+Learndutch: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?utm_source=Weekly+newletter+Learndutch: Downloading webpage
[generic] ?utm_source=Weekly+newletter+Learndutch: Extracting information
ERROR: Unsupported URL: https://www.learndutch.org/free-dutch-grammar-preview-lesson/?utm_source=Weekly+newletter+Learndutch.org
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/generic.py", line 3151, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.learndutch.org/free-dutch-grammar-preview-lesson/?utm_source=Weekly+newletter+Learndutch.org

**Comment by mpenkov** [comment]
You should quote the URL because it contains ampersands and bash interprets them differently to what you expect.

    youtube-dl -v "https://www.learndutch.org/free-dutch-grammar-preview-lesson/?utm_source=Weekly+newletter+Learndutch.org&utm_campaign=3b57dc5dcb-startsubclause_COPY_01&utm_medium=email&utm_term=0_efbe1f10f1-3b57dc5dcb-266208549&mc_cid=3b57dc5dcb&mc_eid=6b905899c0"

Nevertheless, I can confirm the above command still fails.

**Comment by dirkf** [comment]
The problem page contains Vimeo links:
```html
...
 <div class="avia-video avia-video-16-9 av-lazyload-immediate
av-lazyload-video-embed " itemprop="video" itemtype="https://schema.org/VideoObject" data-original_url="https://vimeo.com/123670567">
   <script type="text/html" class="av-video-tmpl">
     <div class='avia-iframe-wrap'>
       <iframe src="https://player.vimeo.com/video/123670567?autoplay=0&loop=0&controls=1&muted=0" width="1280" height="720" frameborder="0" title="Lesson 41 - verb + om + te + infinitive - #dutchgrammar" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
     </div>
   </script>
 </div>
 <br>
 <div class="togglecontainer toggle_close_all avia-builder-el-14
el_after_av_video el_before_av_hr ">
   <section class="av_toggle_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork">
     <div role="tablist" class="single_toggle" data-tags="{All} ">
       <p data-fake-id="#toggle-id-1" class="toggler " itemprop="headline" role="tab" tabindex="0" aria-controls="toggle-id-1-container">Watch without background music <span class="toggle_icon">
           <span class="vert_icon"></span>
           <span class="hor_icon"></span>
         </span>
       </p>
       <div id="toggle-id-1-container" class="toggle_wrap ">
         <div class="toggle_content invers-color " itemprop="text">
           <div class="avia-video avia-video-16-9
av-lazyload-immediate av-lazyload-video-embed " itemprop="video" itemtype="https://schema.org/VideoObject" data-original_url="https://vimeo.com/248384267">
             <script type="text/html" class="av-video-tmpl">
               <div class='avia-iframe-wrap'>
                 <iframe loading="lazy" src="https://player.vimeo.com/video/248384267?dnt=1&amp;app_id=122963&autoplay=0&loop=0&controls=1&muted=0" width="1500" height="844" frameborder="0" allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media"></iframe>
               </div>
             </script>
             <div class="av-click-to-play-overlay">
               <div class="avia_playpause_icon"></div>
             </div>
           </div>
         </div>
       </div>
     </div>
   </section>
 </div>
...
But they don't work for me.

Probably site support here would only be useful for paid authenticated users. If so, please open a new issue.
```
