### ISSUE TITLE
NBCSports: AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by RingoTheDog** [ytdl-org/youtube-dl#16640]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.04**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
>youtube-dl.py -v "https://www.nbcsports.com/philadelphia/philadelphia-phillies/bru
ce-bochy-hector-neris-hes-idiot"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.nbcsports.com/philadelphia/philadelphia-phillies/bruc
e-bochy-hector-neris-hes-idiot']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.06.04
[debug] Python version 3.5.1 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[NBCSports] bruce-bochy-hector-neris-hes-idiot: Downloading webpage
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Transmogrifier\youtube-dl.py\__main__.py", line 19, in <module>
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\__init__.py", line 472, in main
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\__init__.py", line 462, in _real_main
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 2001, in download
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 803, in extract_info
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 847, in process_ie_result
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\utils.py", line 544, in sanitize_url
AttributeError: 'NoneType' object has no attribute 'startswith'
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.nbcsports.com/philadelphia/philadelphia-phillies/bruce-bochy-hector-neris-hes-idiot

---

Thanks
Ringo

**Comment by pranjalisnow** [comment]
Same issue here too.
Using latest version of YouTube-DL (2019.11.05)

-------------------------
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--ignore-errors', '--encoding', 'utf-8', '--get-title', 'https://www.nbcsports.com/video/nascars-double-yellow-line-rule-impacts-racing-talladega']
[debug] Encodings: locale cp65001, fs mbcs, out cp65001, pref utf-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-94014-g80e68ce116
[debug] Proxy map: {}
ERROR: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\YoutubeDL.py", line 807, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\YoutubeDL.py", line 851, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\utils.py", line 2129, in sanitize_url
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by PhilWinger** [comment]
It last worked for me in August 2019, but I am now experiencing this issue as well.
Using latest version of YouTube-DL (2019.11.22)

C:\stream2\test>youtube-dl --verbose "https://www.nbcsports.com/video/nascar-cup-playoffs-championship-4-kevin-harvick-vs-joe-gibbs-racing"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.nbcsports.com/video/nascar-cup-playoffs-championship-4-kevin-harvick-vs-joe-gibbs-racing']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.22
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-93884-g96c79d4e1f, ffprobe N-93884-g96c79d4e1f
[debug] Proxy map: {}
[NBCSports] nascar-cup-playoffs-championship-4-kevin-harvick-vs-joe-gibbs-racing: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\YoutubeDL.py", line 2018, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\YoutubeDL.py", line 807, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\YoutubeDL.py", line 851, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\utils.py", line 2129, in sanitize_url
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by PhilWinger** [comment]
I just realized that this is an old request and not likely related to my problem.  Should I submit a new issue?

**Comment by PhilWinger** [comment]
Just bumping this reported problem with NBCSports, which I believe is a supported site.

**Comment by PhilWinger** [comment]
I've been having a problem with NBC Sports for 2 months.  Do I need to create a new request with the newer templates?

**Comment by PhilWinger** [comment]
Nobody responded to my earlier questions so I opened a new issue.  Of course, it was closed within a matter of minutes.  Can someone confirm that this is still in the queue?  

I'm not trying to be difficult but the issue has been open since 2018 and the only feedback has been to quickly close a duplicate issue.

Thanks

**Comment by remitamine** [comment]
I suggest that you read [this](https://github.com/ytdl-org/youtube-dl#how-can-i-speed-up-work-on-my-issue) and follow the rules if people keep bumping the issue in a short period the issue will be locked.

**Comment by PhilWinger** [comment]
Fair enough, I won't comment more than once a month.

**Comment by PhilWinger** [comment]
Just in case anyone else is following this issue....

As a temporary work-around, you can add the **--force-generic-extractor** option and the videos will download successfully.
