### ISSUE TITLE
[CESKATELEVIZE.CZ] ČT still doesn't work after the 2018.07.21 release

### ISSUE THREAD

**Issue by NiesmialyGosc** [ytdl-org/youtube-dl#17047]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.21*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

`D:\MOVIE>youtube-dl -U
youtube-dl is up-to-date (2018.07.21)

D:\MOVIE>youtube-dl --no-check-certificate https://www.ceskatelevize.cz/ivysilani/898281-arabela/280350950200005-arabela-na-uteku
[CeskaTelevize] 280350950200005-arabela-na-uteku: Downloading webpage
[CeskaTelevize] 280350950200005-arabela-na-uteku: Downloading JSON metadata
Traceback (most recent call last):
File "main.py", line 19, in 
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl_init_.py", line 472, in main
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl_init_.py", line 462, in _real_main
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\YoutubeDL.py", line 2001, in download
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\common.py", line 502, in extract
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\ceskatelevize.py", line 130, in _real_extract
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\utils.py", line 561, in sanitized_Request
File "C:\Python\Python34\lib\urllib\request.py", line 267, in init
File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: 'Error'

D:\MOVIE>youtube-dl --no-check-certificate --proxy socks5://195.181.214.110:443
https://www.ceskatelevize.cz/ivysilani/898281-arabela/280350950200005-arabela-na-uteku
[CeskaTelevize] 280350950200005-arabela-na-uteku: Downloading webpage
Traceback (most recent call last):
File "main.py", line 19, in 
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl_init_.py", line 472, in main
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl_init_.py", line 462, in _real_main
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\YoutubeDL.py", line 2001, in download
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\common.py", line 502, in extract
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\ceskatelevize.py", line 74, in _real_extract
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\common.py", line 761, in _download_webpage
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\common.py", line 627, in _download_webpage_handle
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\common.py", line 599, in _request_webpage
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\YoutubeDL.py", line 2211, in urlopen
File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\utils.py", line 1102, in https_open
File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
File "C:\Python\Python34\lib\http\client.py", line 1137, in request
File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
File "C:\Python\Python34\lib\http\client.py", line 898, in send
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\utils.py", line 1068, in connect
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\socks.py", line 270, in connect
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\socks.py", line 266, in _make_proxy
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\socks.py", line 221, in _setup_socks5
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\socks.py", line 192, in _socks5_auth
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\socks.py", line 131, in _recv_bytes
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\socks.py", line 126, in recvall
EOFError: 2 bytes missing

D:\MOVIE>youtube-dl --no-check-certificate --proxy 185.142.208.139:41258 https://www.ceskatelevize.cz/ivysilani/898281-arabela/280350950200005-arabela-na-uteku
[CeskaTelevize] 280350950200005-arabela-na-uteku: Downloading webpage
ERROR: Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)> (caused by URLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:600)'),))

D:\MOVIE>youtube-dl --no-check-certificate --verbose https://www.ceskatelevize.cz/ivysilani/898281-arabela/280350950200005-arabela-na-uteku
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-check-certificate', '--verbose', 'https://www.ceskatelevize.cz/ivysilani/898281-arabela/280350950200005-arabela-na-uteku']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.07.21
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[CeskaTelevize] 280350950200005-arabela-na-uteku: Downloading webpage
[CeskaTelevize] 280350950200005-arabela-na-uteku: Downloading JSON metadata
Traceback (most recent call last):
File "main.py", line 19, in 
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl_init_.py", line 472, in main
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl_init_.py", line 462, in _real_main
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\YoutubeDL.py", line 2001, in download
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\common.py", line 502, in extract
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\ceskatelevize.py", line 130, in _real_extract
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\utils.py", line 561, in sanitized_Request
File "C:\Python\Python34\lib\urllib\request.py", line 267, in init
File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: 'Error'`

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

Still no luck.. I've used "youtube-dl -U" to make sure the version is up to date.. Could you help me troubleshoot this..? Thank you.

**Comment by arc-tic** [comment]
I have this same issue too, they must something changed. I hope that fix will be soon:
![ivysilani](https://user-images.githubusercontent.com/39046189/43130017-f2b82f76-8f35-11e8-976e-18c1eab3fafa.PNG)
debug:
![ivysilani-debug](https://user-images.githubusercontent.com/39046189/43130124-3b258b3c-8f36-11e8-8ed2-93e0dd8585ff.PNG)

**Comment by arc-tic** [comment]
I have this same issue too, they must something changed. I hope that fix will be soon:
![ivysilani](https://user-images.githubusercontent.com/39046189/43130017-f2b82f76-8f35-11e8-976e-18c1eab3fafa.PNG)
debug:
![ivysilani-debug](https://user-images.githubusercontent.com/39046189/43130124-3b258b3c-8f36-11e8-8ed2-93e0dd8585ff.PNG)

**Comment by arc-tic** [comment]
I have this same issue too, they must something changed. I hope that fix will be soon.

**Comment by arc-tic** [comment]
I have this same issue too, they must something changed. I hope that fix will be soon.

**Comment by mcepl** [comment]
Command ``youtube-dl --verbose --no-check-certificate https://www.ceskatelevize.cz/ivysilani/898281-arabela/280350950200005-arabela-na-uteku`` just works. This ticket should be closed, IMHO.
