### ISSUE TITLE
VRTnu mostly unable to download

### ISSUE THREAD

**Issue by smartbit** [ytdl-org/youtube-dl#17083]
### Latest version:
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.21** (see bug reports below) 

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

#### Succes
```
$ youtube-dl --netrc --verbose https://www.vrt.be/vrtnu/a-z/reizen-waes/2/reizen-waes-s2a5-noord-korea/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--netrc', u'--verbose', u'https://www.vrt.be/vrtnu/a-z/reizen-waes/2/reizen-waes-s2a5-noord-korea/']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2018.07.21
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[VrtNU] Logging in
[VrtNU] Requesting a token
[VrtNU] reizen-waes-s2a5-noord-korea: Downloading webpage
[VrtNU] reizen-waes-s2a5-noord-korea: Downloading JSON metadata
[Canvas] pbs-pub-9912c5f9-702b-4258-bf1d-0c6c2766d391$vid-a7cb68bd-b6da-4150-987f-93a8035379a1: Downloading JSON metadata
[Canvas] pbs-pub-9912c5f9-702b-4258-bf1d-0c6c2766d391$vid-a7cb68bd-b6da-4150-987f-93a8035379a1: Downloading m3u8 information
[Canvas] pbs-pub-9912c5f9-702b-4258-bf1d-0c6c2766d391$vid-a7cb68bd-b6da-4150-987f-93a8035379a1: Downloading MPD manifest
WARNING: [Canvas] Unknown MIME type application/mp4 in DASH manifest
[Canvas] pbs-pub-9912c5f9-702b-4258-bf1d-0c6c2766d391$vid-a7cb68bd-b6da-4150-987f-93a8035379a1: Downloading ISM manifest
[Canvas] pbs-pub-9912c5f9-702b-4258-bf1d-0c6c2766d391$vid-a7cb68bd-b6da-4150-987f-93a8035379a1: Downloading f4m manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://ondemand-aka.vrtcdn.be/content/vod/vid-dis-6657b75c-3bea-43cd-bf5c-b57b5bbceca2_4/vid-dis-6657b75c-3bea-43cd-bf5c-b57b5bbceca2_4_nodrm_e7c1dbe4-e361-407d-8d6c-f39840ae5459.ism/dash/'
[dashsegments] Total fragments: 1395
[download] Destination: Noord-Korea-pbs-pub-9912c5f9-702b-4258-bf1d-0c6c2766d391$vid-a7cb68bd-b6da-4150-987f-93a8035379a1.fMPEG_DASH-video=1961963.mp4
[download] 100% of 652.02MiB in 09:24
[debug] Invoking downloader on u'https://ondemand-aka.vrtcdn.be/content/vod/vid-dis-6657b75c-3bea-43cd-bf5c-b57b5bbceca2_4/vid-dis-6657b75c-3bea-43cd-bf5c-b57b5bbceca2_4_nodrm_e7c1dbe4-e361-407d-8d6c-f39840ae5459.ism/dash/'
[dashsegments] Total fragments: 1395
[download] Destination: Noord-Korea-pbs-pub-9912c5f9-702b-4258-bf1d-0c6c2766d391$vid-a7cb68bd-b6da-4150-987f-93a8035379a1.fMPEG_DASH-audio_nld=93375.m4a
[download] 100% of 31.80MiB in 07:27
[ffmpeg] Merging formats into "Noord-Korea-pbs-pub-9912c5f9-702b-4258-bf1d-0c6c2766d391$vid-a7cb68bd-b6da-4150-987f-93a8035379a1.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Noord-Korea-pbs-pub-9912c5f9-702b-4258-bf1d-0c6c2766d391$vid-a7cb68bd-b6da-4150-987f-93a8035379a1.fMPEG_DASH-video=1961963.mp4' -i 'file:Noord-Korea-pbs-pub-9912c5f9-702b-4258-bf1d-0c6c2766d391$vid-a7cb68bd-b6da-4150-987f-93a8035379a1.fMPEG_DASH-audio_nld=93375.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:Noord-Korea-pbs-pub-9912c5f9-702b-4258-bf1d-0c6c2766d391$vid-a7cb68bd-b6da-4150-987f-93a8035379a1.temp.mp4'
Deleting original file Noord-Korea-pbs-pub-9912c5f9-702b-4258-bf1d-0c6c2766d391$vid-a7cb68bd-b6da-4150-987f-93a8035379a1.fMPEG_DASH-video=1961963.mp4 (pass -k to keep)
Deleting original file Noord-Korea-pbs-pub-9912c5f9-702b-4258-bf1d-0c6c2766d391$vid-a7cb68bd-b6da-4150-987f-93a8035379a1.fMPEG_DASH-audio_nld=93375.m4a (pass -k to keep)
```

#### Fail

```
$ youtube-dl --netrc --verbose https://www.vrt.be/vrtnu/a-z/occupied/1/occupied-s1a3/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--netrc', u'--verbose', u'https://www.vrt.be/vrtnu/a-z/occupied/1/occupied-s1a3/']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2018.07.21
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[VrtNU] Logging in
[VrtNU] Requesting a token
[VrtNU] occupied-s1a3: Downloading webpage
[VrtNU] occupied-s1a3: Downloading JSON metadata
[Canvas] pbs-pub-143d15a4-5ad4-4b5d-a1ec-166240564d41$vid-d1c7eed8-039d-49cf-9b06-adb9e4cb5218: Downloading JSON metadata
[Canvas] pbs-pub-143d15a4-5ad4-4b5d-a1ec-166240564d41$vid-d1c7eed8-039d-49cf-9b06-adb9e4cb5218: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Canvas] pbs-pub-143d15a4-5ad4-4b5d-a1ec-166240564d41$vid-d1c7eed8-039d-49cf-9b06-adb9e4cb5218: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[Canvas] pbs-pub-143d15a4-5ad4-4b5d-a1ec-166240564d41$vid-d1c7eed8-039d-49cf-9b06-adb9e4cb5218: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 403: Forbidden
[Canvas] pbs-pub-143d15a4-5ad4-4b5d-a1ec-166240564d41$vid-d1c7eed8-039d-49cf-9b06-adb9e4cb5218: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/canvas.py", line 73, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1281, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
$ youtube-dl --netrc --verbose https://www.vrt.be/vrtnu/a-z/o-inferno/2011/o-inferno/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--netrc', u'--verbose', u'https://www.vrt.be/vrtnu/a-z/o-inferno/2011/o-inferno/']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2018.07.21
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[VrtNU] Logging in
[VrtNU] Requesting a token
[VrtNU] o-inferno: Downloading webpage
[VrtNU] o-inferno: Downloading JSON metadata
[Canvas] pbs-pub-1741e7e5-01ea-45ac-93da-3f8efb237fc2$vid-4530ba1d-d833-46fd-8e60-ff28cd8469a6: Downloading JSON metadata
[Canvas] pbs-pub-1741e7e5-01ea-45ac-93da-3f8efb237fc2$vid-4530ba1d-d833-46fd-8e60-ff28cd8469a6: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Canvas] pbs-pub-1741e7e5-01ea-45ac-93da-3f8efb237fc2$vid-4530ba1d-d833-46fd-8e60-ff28cd8469a6: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[Canvas] pbs-pub-1741e7e5-01ea-45ac-93da-3f8efb237fc2$vid-4530ba1d-d833-46fd-8e60-ff28cd8469a6: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 403: Forbidden
[Canvas] pbs-pub-1741e7e5-01ea-45ac-93da-3f8efb237fc2$vid-4530ba1d-d833-46fd-8e60-ff28cd8469a6: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/canvas.py", line 73, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1281, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
$ youtube-dl --netrc --verbose https://www.vrt.be/vrtnu/a-z/occupied/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--netrc', u'--verbose', u'https://www.vrt.be/vrtnu/a-z/occupied/']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2018.07.21
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[VrtNU] Logging in
[VrtNU] Requesting a token
[VrtNU] occupied: Downloading webpage
[VrtNU] occupied: Downloading JSON metadata
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 472, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 462, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/canvas.py", line 301, in _real_extract

IndexError: list index out of range
```
---

### Example URLs:
- Single *succes*: https://www.vrt.be/vrtnu/a-z/reizen-waes/2/reizen-waes-s2a5-noord-korea/
- Single *succes*: https://www.vrt.be/vrtnu/a-z/cinema-canvas-toni-erdmann/2016/cinema-canvas-toni-erdmann/
- Single *failure*: https://www.vrt.be/vrtnu/a-z/occupied/1/occupied-s1a3/
- Single *failure*: 
https://www.vrt.be/vrtnu/a-z/amazing-hotels--life-beyond-the-lobby/2/amazing-hotels--life-beyond-the-lobby-s2a2/
- Playlists *failure*: https://www.vrt.be/vrtnu/a-z/reizen-waes/ 
- Playlists *failure*: https://www.vrt.be/vrtnu/a-z/occupied/
---

### Description of  *issue*
The problem is that **most** downloads of https://www.vrt.be/vrtnu/ fail, *some* succeed. Find more failing links at https://www.vrt.be/vrtnu/a-z/. 

Account can be obtained at https://www.vrt.be/vrtnu/, click on the right top icon, click on **Nieuwe Gebruiker**, which redirects to https://login.vrt.be/login?client_id=vrtnu-site&login_hint=registration and register with 
- VOORNAAM: firstname
- ACHTERNAAM: family name
- GEBOORTEDATUM (DD/MM/JJJJ): date of birth
- GENDER: gender
- LAND: België 
- POSTCODE: [from official list](http://www.bpost.be/site/nl/verzenden/adressering/zoek-een-postcode)

No idea how this could be fixed. Seems like a repeat of issue #17018.

**Comment by smartbit** [comment]
Same failures for version **2018.07.21**:
```
$ youtube-dl --netrc --verbose https://www.vrt.be/vrtnu/a-z/occupied/1/occupied-s1a3/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--netrc', u'--verbose', u'https://www.vrt.be/vrtnu/a-z/occupied/1/occupied-s1a3/']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2018.07.21
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[VrtNU] Logging in
[VrtNU] Requesting a token
[VrtNU] occupied-s1a3: Downloading webpage
[VrtNU] occupied-s1a3: Downloading JSON metadata
[Canvas] pbs-pub-143d15a4-5ad4-4b5d-a1ec-166240564d41$vid-d1c7eed8-039d-49cf-9b06-adb9e4cb5218: Downloading JSON metadata
[Canvas] pbs-pub-143d15a4-5ad4-4b5d-a1ec-166240564d41$vid-d1c7eed8-039d-49cf-9b06-adb9e4cb5218: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Canvas] pbs-pub-143d15a4-5ad4-4b5d-a1ec-166240564d41$vid-d1c7eed8-039d-49cf-9b06-adb9e4cb5218: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[Canvas] pbs-pub-143d15a4-5ad4-4b5d-a1ec-166240564d41$vid-d1c7eed8-039d-49cf-9b06-adb9e4cb5218: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 403: Forbidden
[Canvas] pbs-pub-143d15a4-5ad4-4b5d-a1ec-166240564d41$vid-d1c7eed8-039d-49cf-9b06-adb9e4cb5218: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/canvas.py", line 73, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1281, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
```
$ youtube-dl --netrc --verbose https://www.vrt.be/vrtnu/a-z/o-inferno/2011/o-inferno/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--netrc', u'--verbose', u'https://www.vrt.be/vrtnu/a-z/o-inferno/2011/o-inferno/']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2018.07.21
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[VrtNU] Logging in
[VrtNU] Requesting a token
[VrtNU] o-inferno: Downloading webpage
[VrtNU] o-inferno: Downloading JSON metadata
[Canvas] pbs-pub-1741e7e5-01ea-45ac-93da-3f8efb237fc2$vid-4530ba1d-d833-46fd-8e60-ff28cd8469a6: Downloading JSON metadata
[Canvas] pbs-pub-1741e7e5-01ea-45ac-93da-3f8efb237fc2$vid-4530ba1d-d833-46fd-8e60-ff28cd8469a6: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Canvas] pbs-pub-1741e7e5-01ea-45ac-93da-3f8efb237fc2$vid-4530ba1d-d833-46fd-8e60-ff28cd8469a6: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[Canvas] pbs-pub-1741e7e5-01ea-45ac-93da-3f8efb237fc2$vid-4530ba1d-d833-46fd-8e60-ff28cd8469a6: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 403: Forbidden
[Canvas] pbs-pub-1741e7e5-01ea-45ac-93da-3f8efb237fc2$vid-4530ba1d-d833-46fd-8e60-ff28cd8469a6: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/canvas.py", line 73, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1281, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
```
$ youtube-dl -v --username xyz --password xyz https://www.vrt.be/vrtnu/a-z/occupied/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://www.vrt.be/vrtnu/a-z/occupied/']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2018.07.21
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[VrtNU] Logging in
[VrtNU] Requesting a token
[VrtNU] occupied: Downloading webpage
[VrtNU] occupied: Downloading JSON metadata
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 472, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 462, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/canvas.py", line 301, in _real_extract

IndexError: list index out of range
```

**Comment by dstftw** [comment]
No longer available.
