### ISSUE TITLE
ExtractorError: No video formats found

### ISSUE THREAD

**Issue by thamenz** [ytdl-org/youtube-dl#17385]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.28*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.28**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.vrt.be/vrtnu/a-z/de-witte-van-sichem/1980/de-witte-van-sichem-s1980/', u'--username', u'PRIVATE', u'--password', u'PRIVATE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.28
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-30-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1
[debug] Proxy map: {}
[VrtNU] Logging in
[VrtNU] Requesting a token
[VrtNU] de-witte-van-sichem-s1980: Downloading webpage
[VrtNU] de-witte-van-sichem-s1980: Downloading JSON metadata
[Canvas] pbs-pub-d402386d-1506-4a17-95b0-d7056ddfa47f$vid-4dbe5e03-ae82-4f8a-a138-332332cbe7c0: Downloading JSON metadata
[Canvas] pbs-pub-d402386d-1506-4a17-95b0-d7056ddfa47f$vid-4dbe5e03-ae82-4f8a-a138-332332cbe7c0: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno -2] Name or service not known>
[Canvas] pbs-pub-d402386d-1506-4a17-95b0-d7056ddfa47f$vid-4dbe5e03-ae82-4f8a-a138-332332cbe7c0: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [Errno -2] Name or service not known>
[Canvas] pbs-pub-d402386d-1506-4a17-95b0-d7056ddfa47f$vid-4dbe5e03-ae82-4f8a-a138-332332cbe7c0: Downloading ISM manifest
WARNING: Failed to download ISM manifest: <urlopen error [Errno -2] Name or service not known>
[Canvas] pbs-pub-d402386d-1506-4a17-95b0-d7056ddfa47f$vid-4dbe5e03-ae82-4f8a-a138-332332cbe7c0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: <urlopen error [Errno -2] Name or service not known>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/canvas.py", line 73, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1281, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
https://www.vrt.be/vrtnu/a-z/de-witte-van-sichem/1980/de-witte-van-sichem-s1980/

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Website is supported, other videos are working, but not able to download this one

**Comment by EWouters** [comment]
I get this error as well for a video that is not geo-resticted. I can watch in the browser just fine.

```
>youtube-dl.exe --cookie cookies.txt https://www.vrt.be/vrtnu/a-z/reizen-waes/4/reizen-waes-s4a1-spanje/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookie', 'cookies.txt', 'https://www.vrt.be/vrtnu/a-z/reizen-waes/4/reizen-waes-s4a1-spanje/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.02.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-82691-g2c908f2, ffprobe N-82691-g2c908f2
[debug] Proxy map: {'no': '192.168.99.100'}
[VrtNU] reizen-waes-s4a1-spanje: Downloading webpage
WARNING: [VrtNU] reizen-waes-s4a1-spanje: Failed to parse JSON Invalid \escape: line 9 column 31 (char 186)
[VrtNU] reizen-waes-s4a1-spanje: Downloading JSON metadata
[Canvas] pbs-pub-82640e7d-cd66-4187-a9f6-58a6fc8859a9$vid-ca724e0e-cbcb-4fc5-a54e-87557a21b9e1: Downloading JSON metadata
[Canvas] pbs-pub-82640e7d-cd66-4187-a9f6-58a6fc8859a9$vid-ca724e0e-cbcb-4fc5-a54e-87557a21b9e1: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 11001] getaddrinfo failed>
[Canvas] pbs-pub-82640e7d-cd66-4187-a9f6-58a6fc8859a9$vid-ca724e0e-cbcb-4fc5-a54e-87557a21b9e1: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [Errno 11001] getaddrinfo failed>
[Canvas] pbs-pub-82640e7d-cd66-4187-a9f6-58a6fc8859a9$vid-ca724e0e-cbcb-4fc5-a54e-87557a21b9e1: Downloading ISM manifest
WARNING: Failed to download ISM manifest: <urlopen error [Errno 11001] getaddrinfo failed>
[Canvas] pbs-pub-82640e7d-cd66-4187-a9f6-58a6fc8859a9$vid-ca724e0e-cbcb-4fc5-a54e-87557a21b9e1: Downloading f4m manifest
WARNING: Unable to download f4m manifest: <urlopen error [Errno 11001] getaddrinfo failed>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\extractor\canvas.py", line 73, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\extractor\common.py", line 1305, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
No longer available.
