### ISSUE TITLE
Yandex Disk 

### ISSUE THREAD

**Issue by behomonth** [ytdl-org/youtube-dl#17861]
**Yandex Disk Download Error RegexNotFoundError**

youtube-dl -v https://yadi.sk/i/Vuiuve1I3QXfQu
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://yadi.sk/i/Vuiuve1I3QXfQu']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-862.11.6.el7.x86_64-x86_64                                                                                                                                                             -with-centos-7.5.1804-Core
[debug] exe versions: ffmpeg N-92157-gf7affc6, ffprobe N-92157-gf7affc6
[debug] Proxy map: {}
[YandexDisk] Vuiuve1I3QXfQu: Downloading webpage
[YandexDisk] Vuiuve1I3QXfQu: Downloading webpage
ERROR: Unable to extract video JSON; please report this issue on https://yt-dl.o                                                                                                                                                             rg/bug . Make sure you are using the latest version; type  youtube-dl -U  to upd                                                                                                                                                             ate. Be sure to call youtube-dl with the --verbose flag and include its complete                                                                                                                                                              output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract                                                                                                                                                             _info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 507, in                                                                                                                                                              extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/yandexdisk.py", line 54,                                                                                                                                                              in _real_extract
    webpage, 'video JSON'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 977, in                                                                                                                                                              _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video JSON; please report this issue on ht                                                                                                                                                             tps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-                                                                                                                                                             dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include                                                                                                                                                              its complete output.

can you please check.

**Comment by vi** [comment]
Still reproducible for version `2018.11.23`.

**Comment by sanyarnd** [comment]
The problem is still here with 2019.06.21:
```sh
./youtube-dl.exe --verbose https://yadi.sk/i/VdOeDou8eZs6Y
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://yadi.sk/i/VdOeDou8eZs6Y']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.06.21
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[YandexDisk] VdOeDou8eZs6Y: Downloading webpage
[YandexDisk] VdOeDou8eZs6Y: Downloading webpage
ERROR: Unable to extract video JSON; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_g4\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_g4\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_g4\build\youtube_dl\extractor\yandexdisk.py", line 54, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_g4\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video JSON; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Himura2la** [comment]
Please fix Yandex Disk download, I need this functionality.
