### ISSUE TITLE
nrk.no fail to download.

### ISSUE THREAD

**Issue by AndKe** [ytdl-org/youtube-dl#17860]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
ndre@loke:~$ youtube-dl --version
2018.10.05
andre@loke:~$ youtube-dl https://www.nrk.no/troms/se-nordnytt-her_-1.14245014 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.nrk.no/troms/se-nordnytt-her_-1.14245014', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-33-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[NRKPlaylist] se-nordnytt-her_-1.14245014: Downloading webpage
[download] Downloading playlist: Se Nordnytt her:
[NRKPlaylist] playlist Se Nordnytt her:: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Using fake IP 84.208.85.181 (NO) as X-Forwarded-For.
[NRK] 82f7eee1-717b-4756-b987-299b6b0a3909: Downloading mediaelement JSON
[NRK] 82f7eee1-717b-4756-b987-299b6b0a3909: Downloading f4m manifest
WARNING: [NRK] 82f7eee1-717b-4756-b987-299b6b0a3909: Failed to parse XML syntax error: line 1, column 0
Traceback (most recent call last):
  File "/home/andre/.local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/home/andre/.local/lib/python2.7/site-packages/youtube_dl/__init__.py", line 472, in main
    _real_main(argv)
  File "/home/andre/.local/lib/python2.7/site-packages/youtube_dl/__init__.py", line 462, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/andre/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 2001, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/andre/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 803, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/andre/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1002, in process_ie_result
    extra_info=extra)
  File "/home/andre/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 864, in process_ie_result
    extra_info=extra_info)
  File "/home/andre/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/andre/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/home/andre/.local/lib/python2.7/site-packages/youtube_dl/extractor/nrk.py", line 94, in _real_extract
    formats = self._extract_akamai_formats(media_url, video_id)
  File "/home/andre/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 2476, in _extract_akamai_formats
    f4m_url, video_id, f4m_id='hds', fatal=False)
  File "/home/andre/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 1433, in _extract_f4m_formats
    transform_source=transform_source, fatal=fatal, m3u8_id=m3u8_id)
  File "/home/andre/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 1439, in _parse_f4m_formats
    akamai_pv = manifest.find('{http://ns.adobe.com/f4m/1.0}pv-2.0')
AttributeError: 'NoneType' object has no attribu
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.nrk.no/troms/se-nordnytt-her_-1.14245014

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

the terminal output above says it all.

**Comment by barsnick** [comment]
This is now a different error:
```
[barsnick@paradise RPM_tracking]$ ~/Downloads/youtube-dl-2020.06.16.1 --verbose https://www.nrk.no/troms/se-nordnytt-her_-1.14245014
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.nrk.no/troms/se-nordnytt-her_-1.14245014']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.3 (CPython) - Linux-5.6.19-300.fc32.x86_64-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3
[debug] Proxy map: {}
[NRKPlaylist] se-nordnytt-her_-1.14245014: Downloading webpage
WARNING: unable to extract OpenGraph description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -
U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] Downloading playlist: Se Nordnytt her:
[NRKPlaylist] playlist Se Nordnytt her:: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Using fake IP 84.215.111.15 (NO) as X-Forwarded-For.
[NRK] 82f7eee1-717b-4756-b987-299b6b0a3909: Downloading mediaelement JSON
[NRK] 82f7eee1-717b-4756-b987-299b6b0a3909: Downloading f4m manifest
WARNING: [NRK] 82f7eee1-717b-4756-b987-299b6b0a3909: Failed to parse XML syntax error: line 1, column 0
[NRK] 82f7eee1-717b-4756-b987-299b6b0a3909: Downloading m3u8 information
[download] Downloading playlist: Se Nordnytt 18:50
[NRK] playlist Se Nordnytt 18:50: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://www.nrk.no/playout/v1.1/�r�,e��R�H�uތy�l�1$\x06z�V3��'
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/home/barsnick/Downloads/youtube-dl-2020.06.16.1/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/home/barsnick/Downloads/youtube-dl-2020.06.16.1/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/home/barsnick/Downloads/youtube-dl-2020.06.16.1/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/home/barsnick/Downloads/youtube-dl-2020.06.16.1/youtube_dl/downloader/hls.py", line 62, in real_download
    urlh = self.ydl.urlopen(self._prepare_url(info_dict, man_url))
  File "/home/barsnick/Downloads/youtube-dl-2020.06.16.1/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib64/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

It does play in the browser.

I'm pretty sure the URL in "```Invoking downloader on 'https://www.nrk.no/playout/v1.1/...```" is incorrect.

**Comment by dstftw** [comment]
Works in the latest version.
