### ISSUE TITLE
Downloading YouTube History fails on parsing JSON

### ISSUE THREAD

**Issue by ealgase** [ytdl-org/youtube-dl#17940]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', ':ythistory', '--username', 'PRIVATE', '--password=PRIVATE', '-f', 'worstvideo+worstaudio']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91712-g26dc763245, ffprobe N-91712-g26dc763245
[debug] Proxy map: {}
[youtube:history] Downloading login page
[youtube:history] Looking up account info
[youtube:history] Logging in
[youtube:history] Checking cookie
[youtube:history] Youtube History: Downloading webpage
[download] Downloading playlist: Youtube History
[youtube:history] Youtube History: Downloading page #1
[youtube:history] Youtube History: Downloading page #2
[youtube:history] Youtube History: Downloading page #3
[youtube:history] Youtube History: Downloading page #4
[youtube:history] Youtube History: Downloading page #5
[youtube:history] Youtube History: Downloading page #6
[youtube:history] Youtube History: Downloading page #7
[youtube:history] Youtube History: Downloading page #8
[youtube:history] Youtube History: Downloading page #9
[youtube:history] Youtube History: Downloading page #10
[youtube:history] Youtube History: Downloading page #11
ERROR: Youtube History: Failed to parse JSON  (caused by ValueError('Invalid \\escape: line 1 column 587495 (char 587494)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 871, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 359, in raw_decode
ValueError: Invalid \escape: line 1 column 587495 (char 587494)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 871, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 359, in raw_decode
ValueError: Invalid \escape: line 1 column 587495 (char 587494)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\YoutubeDL.py", line 803, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\YoutubeDL.py", line 963, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\youtube.py", line 2796, in _entries
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 864, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 848, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 875, in _parse_json
youtube_dl.utils.ExtractorError: Youtube History: Failed to parse JSON  (caused by ValueError('Invalid \\escape: line 1 column 587495 (char 587494)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
<end of log>
```

### Description of your *issue*, suggested solution and other information

I am trying to download all of the videos I have watched on YouTube.  I've provided the correct username and password.  However, the program fails after downloading page 11 of the history list.

My suggested solution is to check if the JSON format that the page is provided in has changed, as this is probably a rarely used feature, and YouTube's redesign may have messed things up.

**Comment by ealgase** [comment]
The surrounding area is 
`class=\"yt-uix-sessionlink`
with the `l` being the character that causes the failure.

**Note:** I've watched more videos since making this issue, so I went to the new location the error was at.
