### ISSUE TITLE
Chaturbate.com -  Unable to find  stream URL

### ISSUE THREAD

**Issue by silvermindphasar** [ytdl-org/youtube-dl#17952]
youtube-dl.exe -U

youtube-dl is up-to-date (2018.10.05)

 youtube-dl.exe -v  https://chaturbate.com/the_secret_cam/

[debug] System config: []
[debug] User config: ['--write-sub', '--sub-lang', 'en', '--convert-subs', 'ass', '--embed-sub', '--user-agent', 'Mozilla/5.0 (Linux; Android 7.0; SM-G892A Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Mobile Safari/537.36', '--ffmpeg-location', 'ffmpeg.exe', '--external-downloader', 'ffmpeg.exe']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://chaturbate.com/the_secret_cam/']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.4.4 (CPython) - Windows-8-6.2.9200-SP0
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2, phantomjs 2.1.1
[debug] Proxy map: {}
[Chaturbate] the_secret_cam: Downloading webpage
ERROR: Unable to find stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\chaturbate.py", line 58, in _real_extract
youtube_dl.utils.ExtractorError: Unable to find stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by silvermindphasar** [comment]
with windows 8.0 fixes the problem by installing in the directory the version of ffmpeg 3.4.2 and everything works .. the latest version of ffmpeg 4.0.2 or beta are not supported.
