### ISSUE TITLE
LondonReal.TV - unsupported site

### ISSUE THREAD

**Issue by DiagonalArg** [ytdl-org/youtube-dl#18090]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Site needs a uname/pwd, but there is no paywall.

```
$:~/Data/Films/Anarchism$ youtube-dl --version
2018.11.03

$ youtube-dl -v -u XXX -p XXX --prefer-ffmpeg "https://londonreal.tv/e/david-graeber-american-anarchist/?freshLRtvReg"
ffmpeg "https://londonreal.tv/e/david-graeber-american-anarchist/?freshLRtvReg"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--prefer-ffmpeg', u'https://londonreal.tv/e/david-graeber-american-anarchist/?freshLRtvReg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.03
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-138-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 3.4.4-1, avprobe 3.4.4-1, ffmpeg 3.4.4-1, ffprobe 3.4.4-1, rtmpdump 2.4
[debug] Proxy map: {'socks': 'socks://localhost:9999/'}
[generic] ?freshLRtvReg: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?freshLRtvReg: Downloading webpage
[generic] ?freshLRtvReg: Extracting information
ERROR: Unsupported URL: https://londonreal.tv/e/david-graeber-american-anarchist/?freshLRtvReg
Traceback (most recent call last):
  File "/home/dev/bin/youtube-dl.new/youtube_dl/extractor/generic.py", line 2324, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/home/dev/bin/youtube-dl.new/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/home/dev/bin/youtube-dl.new/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 20, column 322
Traceback (most recent call last):
  File "/home/dev/bin/youtube-dl.new/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/dev/bin/youtube-dl.new/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/home/dev/bin/youtube-dl.new/youtube_dl/extractor/generic.py", line 3298, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://londonreal.tv/e/david-graeber-american-anarchist/?freshLRtvReg

```

**Comment by Neurognostic** [comment]
See [comment](https://github.com/ytdl-org/youtube-dl/issues/26224#issuecomment-694617022) in #26224
