### ISSUE TITLE
403 Permission Denied on Digital Trends YouTube channel videos if logged in

### ISSUE THREAD

**Issue by jgrg** [ytdl-org/youtube-dl#18841]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
$ youtube-dl -v --ignore-config --netrc O4yFpJ5OPZc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', '--netrc', 'O4yFpJ5OPZc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.10
[debug] Python version 3.6.8 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
[youtube] Checking cookie
[youtube] O4yFpJ5OPZc: Downloading webpage
[youtube] O4yFpJ5OPZc: Downloading video info webpage
[youtube] {22} signature length 107, html5 player vfl_235rs
[youtube] {43} signature length 107, html5 player vfl_235rs
[youtube] {18} signature length 107, html5 player vfl_235rs
[youtube] {36} signature length 103, html5 player vfl_235rs
[youtube] {17} signature length 107, html5 player vfl_235rs
[youtube] {137} signature length 107, html5 player vfl_235rs
[youtube] {248} signature length 107, html5 player vfl_235rs
[youtube] {299} signature length 107, html5 player vfl_235rs
[youtube] {303} signature length 107, html5 player vfl_235rs
[youtube] {136} signature length 107, html5 player vfl_235rs
[youtube] {247} signature length 107, html5 player vfl_235rs
[youtube] {298} signature length 103, html5 player vfl_235rs
[youtube] {302} signature length 107, html5 player vfl_235rs
[youtube] {135} signature length 107, html5 player vfl_235rs
[youtube] {244} signature length 107, html5 player vfl_235rs
[youtube] {134} signature length 107, html5 player vfl_235rs
[youtube] {243} signature length 107, html5 player vfl_235rs
[youtube] {133} signature length 107, html5 player vfl_235rs
[youtube] {242} signature length 107, html5 player vfl_235rs
[youtube] {160} signature length 107, html5 player vfl_235rs
[youtube] {278} signature length 107, html5 player vfl_235rs
[youtube] {140} signature length 107, html5 player vfl_235rs
[youtube] {171} signature length 107, html5 player vfl_235rs
[youtube] {249} signature length 107, html5 player vfl_235rs
[youtube] {250} signature length 103, html5 player vfl_235rs
[youtube] {251} signature length 107, html5 player vfl_235rs
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r2---sn-aigzrn7l.googlevideo.com/videoplayback?initcwndbps=3366250&lmt=1545277241895947&id=o-ACKL44ZbzwToUi4qAd5jGo0Jv7bZE_BSezHyWzaajVZ1&fvip=2&sparams=expire%2Cei%2Cip%2Cgir%2Crequiressl%2Csource%2Citag%2Caitags%2Cipbits%2Cclen%2Cid%2Clmt%2Cdur%2Ckeepalive%2Cmime&ipbits=0&source=youtube&ei=8TA7XOaeBcba1ga5z7K4Aw&mm=31%2C29&ip=2a02%3A8010%3A63c7%3A1%3A%3A2121&mime=video%2Fmp4&itag=299&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C298%2C299%2C302%2C303&mt=1547382947&mv=m&ms=au%2Crdu&lsparams=initcwndbps%2Cms%2Cmm%2Cpl%2Cmn%2Cmv&keepalive=yes&pl=29&requiressl=yes&dur=690.923&txp=5432432&expire=1547404625&c=WEB&gir=yes&clen=120115504&mn=sn-aigzrn7l%2Csn-aigl6nl7&lsig=ANVabiowRQIhAM1Krw4DCL2Kg2eq5FNrjLHoWPD8fb9hY4Oo4w75YvSHAiBcKtTR7K7A8QC1htZC-5ZhNBDq-jRaa0Can8qPOTc4pQ%3D%3D&signature=AMao4c4wRQIhAOlo1Pcw_Rhcl1QHmZGYo60qYb_8TjJK1BGozu7Pp62-AiAm7pav0cEwHV-rB7dxqfrQkFZqTM6sYoI9rFM5ZXFb8w==&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1903, in process_info
    partial_success = dl(fname, new_info)
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1848, in dl
    return fd.download(name, info)
  File "/opt/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/opt/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/opt/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2212, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

---

Seems to affect any video from the Digital Trends channel: https://www.youtube.com/user/DigitalTrends/videos
and happens with the `--netrc` command line option or `--username` and `--password`. *i.e.* It seems I get permission denied on their videos when I'm logged in with my account credentials. Download works as normal without credentials. I can play those videos in a browser when logged in. Have not seen this problem on any other channels.

**Comment by ealgase** [comment]
Works for me.  Are you banned from their channel or something?

**Comment by jgrg** [comment]
No, not banned. I just commented on a video.

**Comment by jgrg** [comment]
Oh, it's not only the Digital Trends channel. Just got the same on this video:

https://youtu.be/KyWnsfHIppY

**Comment by bew** [comment]
Same here, on https://www.youtube.com/watch?v=cXUkvswgOMs

I don't think there is any relation to being connected or not: This is a public video, and the link is the same when connected or not to my account on the browser

**Comment by mdawar** [comment]
Me too I'm getting `403: Forbidden` for some videos, it's been like that for about 2 weeks.

**Comment by Taemojitsu** [comment]
Failing on https://www.youtube.com/watch?v=fAqcVIZDvyM and several other videos. Seems related to disabling embeds, but it also seems that if you've downloaded or possibly watched too many videos, YouTube will give 403. (And this could be tied to your account.) I tried testing a video I had previously downloaded a few hours earlier and got 403; tried it again some time after that and it succeeded. But for 'embed disabled' videos, it's different.

Verbose output, though I don't think it's relevant:
```
$  youtube-dl https://www.youtube.com/watch?v=fAqcVIZDvyM -o video
[youtube] fAqcVIZDvyM: Downloading webpage
[youtube] fAqcVIZDvyM: Downloading video info webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
ERROR: unable to download video data: HTTP Error 403: Forbidden
misaki@dawn:/dev/shm$  youtube-dl -v fAqcVIZDvyM
[debug] System config: []
[debug] User config: [u'--no-mtime', u'-o', u'%(title)s [%(id)s].%(ext)s', u'-f', u'(bestvideo[vcodec=vp9]/bestvideo[ext=mp4]/bestvideo)[height<1800][width<1800]+(250/140/bestaudio)/bestvideo[height<1000]+bestaudio/bestvideo+bestaudio/best[height<1800][width<1800]/best[height<1000]/best', u'--cookies', u'/dev/shm/cookies']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'fAqcVIZDvyM']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.10
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.8.0-34-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] fAqcVIZDvyM: Downloading webpage
[youtube] fAqcVIZDvyM: Downloading video info webpage
[youtube] {43} signature length 105, html5 player vflsx9jEl
[youtube] {18} signature length 109, html5 player vflsx9jEl
[youtube] {36} signature length 109, html5 player vflsx9jEl
[youtube] {17} signature length 105, html5 player vflsx9jEl
[youtube] {135} signature length 109, html5 player vflsx9jEl
[youtube] {134} signature length 105, html5 player vflsx9jEl
[youtube] {133} signature length 109, html5 player vflsx9jEl
[youtube] {160} signature length 109, html5 player vflsx9jEl
[youtube] {140} signature length 109, html5 player vflsx9jEl
[youtube] {171} signature length 105, html5 player vflsx9jEl
[youtube] {249} signature length 109, html5 player vflsx9jEl
[youtube] {250} signature length 105, html5 player vflsx9jEl
[youtube] {251} signature length 105, html5 player vflsx9jEl
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r1---sn-o097znlk.googlevideo.com/videoplayback?mime=video%2Fmp4&requiressl=yes&mm=31%2C26&mn=sn-o097znlk%2Csn-a5msen7z&aitags=133%2C134%2C135%2C160&keepalive=yes&ipbits=0&mt=1547574755&mv=m&ei=Qx4-XJD9GMjewQGZvbfoDg&ms=au%2Conr&otf=1&fvip=4&expire=1547596451&ip=23.121.191.18&initcwndbps=946250&lsig=ANVabiowRQIhANePDa6xLgHPUxEnqL-TH-mibcHTUPy1B2RVTyV2FqeNAiAlhIW0AC1UmJhQqhaq1C2pf7rsOQmVS4MwxdtWP_WE3Q%3D%3D&source=yt_otf&pl=21&otfp=1&dur=0.000&lsparams=mm%2Cms%2Cinitcwndbps%2Cmn%2Cmv%2Cpl&sparams=expire%2Cei%2Cip%2Crequiressl%2Ckeepalive%2Cotf%2Cmime%2Clmt%2Cotfp%2Caitags%2Csource%2Cdur%2Cipbits%2Citag%2Cid&itag=135&id=o-AIju-W77DjUIbmZ2apSXSJcGbR8jAEdmvSDZy5esj7ZY&c=WEB&lmt=1481890747249702&signature=AMao4c4wRgIhAPh4voZahV01mf2FPAYrq49q0vF3rCOJCii18xte3nJiAiEAgO3_8bnA_pU-bll8KxKSZ5dftplUdPR9ZIDRwsu1ug8=&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last): [...]
```
This video is available in qualities up to 480p, mp4 only for DASH. youtube-dl fails for all, it seems; at least 135 (480p), 134 (360p), 43 (vp8 360p), 140 (m4a), and 18 (baseline h264 mp4 360p). I think many or most downloading sites are based off of youtube-dl, but they have more success.

On https://qdownloader.net/download?video=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DfAqcVIZDvyM, https://www.vidpaw.com/download/fAqcVIZDvyM/, https://keepvid.works/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DfAqcVIZDvyM, and https://savemedia.website/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DfAqcVIZDvyM, 480p and 360p are both listed, but only 360p has a detected size and works. (In Firefox, you can just click on the link and Firefox will play the video without sound.) This is format 134 as confirmed in the URL.

Format 135 is working if you watch the video on YouTube and look at 'Stats for nerds', or look at the traffic in the network analyzer in a browser (Ctrl-shift-E in Firefox). It shows chunks being retrieved. But these chunks aren't playable by ffplay if you download them individually.

In a 1080p video that has the same symptoms, 720p and 480p give HTTP 403 and aren't downloadable with the links provided by these sites or youtube-dl, but 1080p and 360p are.

The link detected by the add-on Video DownloadHelper also doesn't work. It detects a video link if you try to play the video at 480p, but this URL only results in ~800 bytes and no video data so the output file only has sound.

I think what may be happening is that the 'complete' file isn't included on YouTube's servers, it only has the chunks, but for some reason youtube-dl thinks the complete file is there. There are other videos where the video URL given by 'youtube-dl -g <video ID>' doesn't work with, say, ffmpeg, but youtube-dl can still download the chunks of video and combine them. So I think it should be possible for youtube-dl to do this with these formats if a browser can retrieve and play them.

**Comment by dsmudhar** [comment]
the issue is replicable by me, for encrypted videos. also fails on above given video, when logged in with one of my account (only which gives error):
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=fAqcVIZDvyM', u'-f', u'18', u'-v', u'-u', u'PRIVATE']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.17
[debug] Git HEAD: 379306ef5
[debug] Python version 2.7.15 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
[youtube] Checking cookie
[youtube] fAqcVIZDvyM: Downloading webpage
[youtube] fAqcVIZDvyM: Downloading video info webpage
[youtube] {43} signature length 110, html5 player vfl-jbnrr
[youtube] {18} signature length 110, html5 player vfl-jbnrr
[youtube] {36} signature length 110, html5 player vfl-jbnrr
[youtube] {17} signature length 110, html5 player vfl-jbnrr
[youtube] {134} signature length 110, html5 player vfl-jbnrr
[youtube] {140} signature length 110, html5 player vfl-jbnrr
[youtube] {171} signature length 110, html5 player vfl-jbnrr
[youtube] {249} signature length 110, html5 player vfl-jbnrr
[youtube] {250} signature length 110, html5 player vfl-jbnrr
[youtube] {251} signature length 110, html5 player vfl-jbnrr
[youtube] fAqcVIZDvyM: Downloading MPD manifest
[debug] Invoking downloader on u'https://r4---sn-xpgjvh-q0c6.googlevideo.com/videoplayback?fvip=4&id=o-AMg4qD1LthVSf8MfQafO8hjmt0mbOssSzeXMk--MP649&ei=I99DXISpGYu11wL-hrmoDQ&lsig=ANVabiowRgIhAK_tUiBJPW8NWhKZ5xZrbVpQdSEChPEvhDMw_ZoVWTs2AiEAgILWpEH8BmjeL0QrIjJsQQcOZYF4hO4RZFnaKd0lYYs%3D&ms=au%2Crdu&mt=1547951818&expire=1547973507&mv=m&pl=29&source=youtube&mm=31%2C29&mn=sn-xpgjvh-q0c6%2Csn-q0c7rn76&ipbits=0&ratebypass=yes&ip=2001%3Abb6%3A5e09%3Afb58%3Addd1%3A6ff8%3A42c3%3A83ed&c=WEB&gir=yes&clen=17093064&requiressl=yes&itag=18&lmt=1395105945684369&sparams=expire%2Cei%2Cip%2Clmt%2Cclen%2Cmime%2Cratebypass%2Cipbits%2Crequiressl%2Cgir%2Csource%2Cid%2Cdur%2Citag&dur=185.318&lsparams=mv%2Cpl%2Cmn%2Cinitcwndbps%2Cms%2Cmm&mime=video%2Fmp4&initcwndbps=936250&signature=AMao4c4wRQIhAMc1aZZkVGYUskbqeS8M030XK_txyNBtzILi01VlFEDSAiALZsSpBSocW29Bpuba8ZqlHtZN1SzmAZnWBS9JD-ZMbg=='
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 1909, in process_info
    success = dl(filename, info_dict)
  File "youtube_dl/YoutubeDL.py", line 1848, in dl
    return fd.download(name, info)
  File "youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "youtube_dl/YoutubeDL.py", line 2212, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

Pull request #18927 fixes the issue.

**Comment by boygiandi** [comment]
Same here
```
youtube-dl -4 -f 136 "https://www.youtube.com/watch?v=vZA1BY8TRUc"
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[youtube] vZA1BY8TRUc: Downloading webpage
ERROR: unable to download video data: HTTP Error 403: Forbidden
```
