### ISSUE TITLE
Unable to download videos from Facebook...

### ISSUE THREAD

**Issue by antdude** [ytdl-org/youtube-dl#18974]
It was working a few days ago, but not today. Examples:

Debian v8/oldstable/Jessie:
$ youtube-dl -v "https://www.facebook.com/bluemangroupberlin/posts/10155804012857477?__xts__%5B0%5D=68.ARC3Dn9ndbq-wjqWUr66YzPZH1Ne2gNSUHp-qg5hsIP9Yz9zXo-lOUdthDio-RHPIq6tO89whYnreQ68xSxwoMjwF6hbFc-4XXopA17lHbXmvaWogfDjmg_xi3RV09Os_aZdylOQ1Y0W2L815YUvQV8pMD_mzaJOlGaxbiiMLboBQjyNoF-qiZndnot-naXxNjAhPelkHXN3dpZqYkSIzz7tH5yLte9gBWAgzhHXnO2B3nrzgE9s5OwrtfwAxNqmFNJMY_dpklX3lqacVmqbas33CgRj7V54nVmMOv0diVcSSlQGh29J0wvr_dZswH1AEPuqX7sAn45rUqAyniUJ6vRUmCWEdPY3naW6NoMM_hpIj8ymfE_iavOeW6NHFV-DhN0XCynzUjnkT9p2TOCKRViBGUJYkTe0ut56KWDcPmG0VePsD_W3vP3p236NStu-tqtI9tjQ9w9Rg518gZlbacd44b4NEkHmgoupZyctuszB45Y76Ai3xPtWlGcNOlNI&__tn__=C-R"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.facebook.com/bluemangroupberlin/posts/10155804012857477?__xts__%5B0%5D=68.ARC3Dn9ndbq-wjqWUr66YzPZH1Ne2gNSUHp-qg5hsIP9Yz9zXo-lOUdthDio-RHPIq6tO89whYnreQ68xSxwoMjwF6hbFc-4XXopA17lHbXmvaWogfDjmg_xi3RV09Os_aZdylOQ1Y0W2L815YUvQV8pMD_mzaJOlGaxbiiMLboBQjyNoF-qiZndnot-naXxNjAhPelkHXN3dpZqYkSIzz7tH5yLte9gBWAgzhHXnO2B3nrzgE9s5OwrtfwAxNqmFNJMY_dpklX3lqacVmqbas33CgRj7V54nVmMOv0diVcSSlQGh29J0wvr_dZswH1AEPuqX7sAn45rUqAyniUJ6vRUmCWEdPY3naW6NoMM_hpIj8ymfE_iavOeW6NHFV-DhN0XCynzUjnkT9p2TOCKRViBGUJYkTe0ut56KWDcPmG0VePsD_W3vP3p236NStu-tqtI9tjQ9w9Rg518gZlbacd44b4NEkHmgoupZyctuszB45Y76Ai3xPtWlGcNOlNI&__tn__=C-R']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.24
[debug] Python version 3.4.2 (CPython) - Linux-3.16.0-7-amd64-x86_64-with-debian-8.11
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 10155804012857477: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ant/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/home/ant/bin/youtube-dl/youtube_dl/__init__.py", line 472, in main
  File "/home/ant/bin/youtube-dl/youtube_dl/__init__.py", line 462, in _real_main
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2005, in download
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 453, in _real_extract
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 340, in _extract_from_url
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 332, in extract_from_jsmods_instances
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 317, in extract_video_data
TypeError: 'NoneType' object is not subscriptable

--

Fedora v29:
$ youtube-dl -v "https://www.facebook.com/bluemangroupberlin/posts/10155804012857477?__xts__%5B0%5D=68.ARC3Dn9ndbq-wjqWUr66YzPZH1Ne2gNSUHp-qg5hsIP9Yz9zXo-lOUdthDio-RHPIq6tO89whYnreQ68xSxwoMjwF6hbFc-4XXopA17lHbXmvaWogfDjmg_xi3RV09Os_aZdylOQ1Y0W2L815YUvQV8pMD_mzaJOlGaxbiiMLboBQjyNoF-qiZndnot-naXxNjAhPelkHXN3dpZqYkSIzz7tH5yLte9gBWAgzhHXnO2B3nrzgE9s5OwrtfwAxNqmFNJMY_dpklX3lqacVmqbas33CgRj7V54nVmMOv0diVcSSlQGh29J0wvr_dZswH1AEPuqX7sAn45rUqAyniUJ6vRUmCWEdPY3naW6NoMM_hpIj8ymfE_iavOeW6NHFV-DhN0XCynzUjnkT9p2TOCKRViBGUJYkTe0ut56KWDcPmG0VePsD_W3vP3p236NStu-tqtI9tjQ9w9Rg518gZlbacd44b4NEkHmgoupZyctuszB45Y76Ai3xPtWlGcNOlNI&__tn__=C-R"
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.facebook.com/bluemangroupberlin/posts/10155804012857477?__xts__%5B0%5D=68.ARC3Dn9ndbq-wjqWUr66YzPZH1Ne2gNSUHp-qg5hsIP9Yz9zXo-lOUdthDio-RHPIq6tO89whYnreQ68xSxwoMjwF6hbFc-4XXopA17lHbXmvaWogfDjmg_xi3RV09Os_aZdylOQ1Y0W2L815YUvQV8pMD_mzaJOlGaxbiiMLboBQjyNoF-qiZndnot-naXxNjAhPelkHXN3dpZqYkSIzz7tH5yLte9gBWAgzhHXnO2B3nrzgE9s5OwrtfwAxNqmFNJMY_dpklX3lqacVmqbas33CgRj7V54nVmMOv0diVcSSlQGh29J0wvr_dZswH1AEPuqX7sAn45rUqAyniUJ6vRUmCWEdPY3naW6NoMM_hpIj8ymfE_iavOeW6NHFV-DhN0XCynzUjnkT9p2TOCKRViBGUJYkTe0ut56KWDcPmG0VePsD_W3vP3p236NStu-tqtI9tjQ9w9Rg518gZlbacd44b4NEkHmgoupZyctuszB45Y76Ai3xPtWlGcNOlNI&__tn__=C-R']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.24
[debug] Python version 2.7.15 (CPython) - Linux-4.19.13-300.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
[debug] exe versions: ffmpeg 4.0.3, ffprobe 4.0.3, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 10155804012857477: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ant/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/home/ant/bin/youtube-dl/youtube_dl/__init__.py", line 472, in main
  File "/home/ant/bin/youtube-dl/youtube_dl/__init__.py", line 462, in _real_main
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2005, in download
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 453, in _real_extract
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 340, in _extract_from_url
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 332, in extract_from_jsmods_instances
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 317, in extract_video_data
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by TaktakTaktouk** [comment]
For me, it takes a long time with some videos, for example with this video of 6 minutes it takes more than 40 minutes to download it. 
https://facebook.com/2279912002332224

**Comment by antdude** [comment]
TaktakTaktouk: Interesting, your URL worked and yes very slow. I also noticed that in the past as well when my downloads were working.

**Comment by TaktakTaktouk** [comment]
So I get this issue with all videos of this facebook page: https://www.facebook.com/ndugalpubg

**Comment by sayem314** [comment]
Same here
