### ISSUE TITLE
support rtl.de/cms 

### ISSUE THREAD

**Issue by Furty** [ytdl-org/youtube-dl#19155]
Can you please support rtl.de/cms? Below are 2 examples.
[ rtl.de/videos URLs work already, for example https://www.rtl.de/videos/igor-barbosa-spaltet-die-jury-mit-keine-rosen-5a2564a8a2ea503480788fba.html ]

D:\Downloads\Clip-Download>youtube-dl.exe -v https://www.rtl.de/cms/dsds-2016-jessica-holzhauer-stephen-klumb-und-manuela-iengo-fliegen-beim-jamaika-recall-raus-2780547.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.rtl.de/cms/dsds-2016-jessica-holzhauer-stephen-klumb-und-manuela-iengo-fliegen-beim-jamaika-recall-raus-2780547.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.01.30.1
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[generic] dsds-2016-jessica-holzhauer-stephen-klumb-und-manuela-iengo-fliegen-beim-jamaika-recall-raus-2780547: Requesting header
WARNING: Falling back on generic information extractor.
[generic] dsds-2016-jessica-holzhauer-stephen-klumb-und-manuela-iengo-fliegen-beim-jamaika-recall-raus-2780547: Downloading webpage
[generic] dsds-2016-jessica-holzhauer-stephen-klumb-und-manuela-iengo-fliegen-beim-jamaika-recall-raus-2780547: Extracting information
ERROR: Unsupported URL: https://www.rtl.de/cms/dsds-2016-jessica-holzhauer-stephen-klumb-und-manuela-iengo-fliegen-beim-jamaika-recall-raus-2780547.html
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp36zpl0n4\build\youtube_dl\YoutubeDL.py", line 793, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp36zpl0n4\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp36zpl0n4\build\youtube_dl\extractor\generic.py", line 3320, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.rtl.de/cms/dsds-2016-jessica-holzhauer-stephen-klumb-und-manuela-iengo-fliegen-beim-jamaika-recall-raus-2780547.html

D:\Downloads\Clip-Download>youtube-dl.exe -v https://www.rtl.de/cms/dsds-2016-igor-barbosa-ist-in-den-top-10-von-deutschland-sucht-den-superstar-2016-2828095.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.rtl.de/cms/dsds-2016-igor-barbosa-ist-in-den-top-10-von-deutschland-sucht-den-superstar-2016-2828095.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.01.30.1
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[generic] dsds-2016-igor-barbosa-ist-in-den-top-10-von-deutschland-sucht-den-superstar-2016-2828095: Requesting header
WARNING: Falling back on generic information extractor.
[generic] dsds-2016-igor-barbosa-ist-in-den-top-10-von-deutschland-sucht-den-superstar-2016-2828095: Downloading webpage
[generic] dsds-2016-igor-barbosa-ist-in-den-top-10-von-deutschland-sucht-den-superstar-2016-2828095: Extracting information
ERROR: Unsupported URL: https://www.rtl.de/cms/dsds-2016-igor-barbosa-ist-in-den-top-10-von-deutschland-sucht-den-superstar-2016-2828095.html
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp36zpl0n4\build\youtube_dl\YoutubeDL.py", line 793, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp36zpl0n4\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp36zpl0n4\build\youtube_dl\extractor\generic.py", line 3320, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.rtl.de/cms/dsds-2016-igor-barbosa-ist-in-den-top-10-von-deutschland-sucht-den-superstar-2016-2828095.html

**Comment by dirkf** [comment]
Please open a new issue to support current pages with actual video/audio. Videos at plus.rtl.de are DRM-protected and won't be supported.
