### ISSUE TITLE
urlopen error [Errno 0] Error on jailbroken iOS device

### ISSUE THREAD

**Issue by the-eric-kwok** [ytdl-org/youtube-dl#20330]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.09*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
mobile:~$ youtube-dl https://youtu.be/ZNaSf-RluBM -v
[debug] System config: []
[debug] User config: ['--write-thumbnail', '--output', '%(title)s.%(ext)s', '--format', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best']
[debug] Custom config: []
[debug] Command-line args: ['https://youtu.be/ZNaSf-RluBM', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2019.03.09
[debug] Python version 3.7.1 (CPython) - Darwin-18.2.0-iPhone8,1-arm64-64bit
[debug] exe versions: ffmpeg 2.6.1
[debug] Proxy map: {}
[youtube] ZNaSf-RluBM: Downloading webpage
[youtube] ZNaSf-RluBM: Downloading video info webpage
[youtube] {22} signature length 40.40, html5 player vflgQJQnf
[youtube] {43} signature length 40.40, html5 player vflgQJQnf
[youtube] {18} signature length 40.40, html5 player vflgQJQnf
[youtube] {137} signature length 40.40, html5 player vflgQJQnf
[youtube] {248} signature length 40.40, html5 player vflgQJQnf
[youtube] {136} signature length 40.40, html5 player vflgQJQnf
[youtube] {247} signature length 40.40, html5 player vflgQJQnf
[youtube] {135} signature length 40.40, html5 player vflgQJQnf
[youtube] {244} signature length 40.40, html5 player vflgQJQnf
[youtube] {134} signature length 40.40, html5 player vflgQJQnf
[youtube] {243} signature length 40.40, html5 player vflgQJQnf
[youtube] {133} signature length 40.40, html5 player vflgQJQnf
[youtube] {242} signature length 40.40, html5 player vflgQJQnf
[youtube] {160} signature length 40.40, html5 player vflgQJQnf
[youtube] {278} signature length 40.40, html5 player vflgQJQnf
[youtube] {140} signature length 40.40, html5 player vflgQJQnf
[youtube] {171} signature length 40.40, html5 player vflgQJQnf
[youtube] {249} signature length 40.40, html5 player vflgQJQnf
[youtube] {250} signature length 40.40, html5 player vflgQJQnf
[youtube] {251} signature length 40.40, html5 player vflgQJQnf
[youtube] ZNaSf-RluBM: Downloading thumbnail ...
[youtube] ZNaSf-RluBM: Writing thumbnail to: DILLON LLOYD #YEAROFTHEBUCK WETHEPEOPLE.jpg
[debug] Invoking downloader on 'https://r6---sn-i3b7kn7d.googlevideo.com/videoplayback?ei=eUqIXIXLJpizgAOlmrGICg&itag=137&pl=23&fvip=1&source=youtube&txp=5535432&expire=1552457433&ipbits=0&dur=246.245&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&lmt=1552391317723685&mime=video%2Fmp4&gir=yes&key=yt6&initcwndbps=748750&requiressl=yes&clen=97150182&c=WEB&id=o-ACOYF5IA_CK8HDNw6EFP7qDD3JHl1o1-gm7_a6sQ6Tpc&keepalive=yes&mm=31%2C26&mn=sn-i3b7kn7d%2Csn-npoe7nek&ms=au%2Conr&mt=1552435755&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mv=m&ip=119.28.83.189&signature=AC776740FAFAB3FCA77129380CF07ABAC1ECB081.6856FA419705078FE66DE731756D7DBA7724EBA1&ratebypass=yes'
ERROR: unable to download video data: <urlopen error [Errno 0] Error>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/usr/local/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/local/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1907, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1852, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2225, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/utils.py", line 1140, in https_open
    req, **kwargs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 0] Error>
```

### Description of your *issue*, suggested solution and other information

I’ve installed ffmpeg on my iOS with apt and YouTube-dl with pip3. And tried to download a video from YouTube. But this error occurs.

**Comment by dstftw** [comment]
Network/SSL issue on your side.
