### ISSUE TITLE
DisneyNow Not Available Outside of US on Random Videos

### ISSUE THREAD

**Issue by roadzy** [ytdl-org/youtube-dl#20335]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.09*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.09**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.03.09
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Disneynow throws a geolocation error on random videos:

ex: https://disneynow.go.com/shows/puppy-dog-pals/season-02/episode-11-dinner-thief-on-the-puppytown-express-o-brother-where-arf-thou/vdka8043586?pid=PL553044961

-- Plays fine in the browser

My guess is it doesn't like this piece *[debug] Using fake IP 3.212.7.136 (US) as X-Forwarded-For.*

youtube-dl --ap-mso auth_atlanticbb_net --ap-username --ap-password --no-check-certificate -v https://disneynow.go.com/shows/puppy-dog-pals/season-02/episode-11-dinner-thief-on-the-puppytown-express-o-brother-where-arf-thou/vdka8043586?pid=PL553044961
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ap-mso', 'auth_atlanticbb_net', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--no-check-certificate', '-v', 'https://disneynow.go.com/shows/puppy-dog-pals/season-02/episode-11-dinner-thief-on-the-puppytown-express-o-brother-where-arf-thou/vdka8043586?pid=PL553044961']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.09
[debug] Git HEAD: 2232f5d1f
[debug] Python version 3.7.2 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[Go] vdka8043586: Downloading webpage
[Go] VDKA8043586: Downloading JSON metadata
[debug] Using fake IP 3.212.7.136 (US) as X-Forwarded-For.
[Go] VDKA8043586: Downloading JSON metadata
ERROR: 1002:You appear to be outside the United States or its territories. Due to international rights agreements, we only offer this video to viewers located within the United States and its territories.
This video is available in United States.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 522, in extract
    ie_result = self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/extractor/go.py", line 153, in _real_extract
    error['message'], countries=['US'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 932, in raise_geo_restricted
    raise GeoRestrictedError(msg, countries=countries)
youtube_dl.utils.GeoRestrictedError: 1002:You appear to be outside the United States or its territories. Due to international rights agreements, we only offer this video to viewers located within the United States and its territories.

**Comment by darkhelmet2016** [comment]
Part of the issue appears to be in the detection of the format, they only release in 720p apparently and if you do not have the right configuration it will give you a geo location error, may have to do a listing of the episode you are trying to download to see what combination of audio/video is is using.

**Comment by 89z** [comment]
Issue should be closed, URL is dead
