### ISSUE TITLE
Pornhub ERROR: Unable to extract title;

### ISSUE THREAD

**Issue by delixia** [ytdl-org/youtube-dl#20345]
:~# youtube-dl -v -j --write-pages https://www.pornhub.com/view_video.php?viewkey=ph5c74e23f3d84d
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-j', '--write-pages', 'https://www.pornhub.com/view_video.php?viewkey=ph5c74e23f3d84d']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.09
[debug] Python version 3.6.7 (CPython) - Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 522, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/pornhub.py", line 198, in _real_extract
    group='title')
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 997, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by charon2019** [comment]
I can't reproduce this, works perfectly here:

```
$ python3 __main__.py https://de.pornhub.com/view_video.php?viewkey=ph5c74e23f3d84d --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://de.pornhub.com/view_video.php?viewkey=ph5c74e23f3d84d', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.09
[debug] Git HEAD: 6db03a2
[debug] Python version 3.5.2 (CPython) - Linux-4.15.0-041500-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 3.2.4-1yavdr0, avprobe 3.2.4-1yavdr0, ffmpeg 3.2.4-1yavdr0, ffprobe 3.2.4-1yavdr0, rtmpdump 2.4
[debug] Proxy map: {}
[PornHub] ph5c74e23f3d84d: Downloading pc webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://cv.phncdn.com/videos/201902/26/209950961/720P_1500K_209950961.mp4?im-JaggjQcQQiZ1xpkdx4kdp0I_5XN06VW7s0oNu917fgkQXjCAi-SfmZk2HVgtQ5XEDc4E3zOzA_lR7a4NNdjkdC_wP1AhRtdXWkOPdtAjUrsJIe1zTOOODxWCKm1SXVbHsS4BzSz2tA7gtKfTTFMwFSdlXhJAjzYwhpXvVPyePMVq08z7XJuQsO9iEgzY9yTHYE-Wknv6y'
[download] Resuming download at byte 5502976
[download] Destination: hot big tits girl enjoys mounted dildo fuck in shower-ph5c74e23f3d84d.mp4
[download]  11.1% of 65.27MiB at 317.77KiB/s ETA 03:06^C
ERROR: Interrupted by user
```

I didn't try Python 3.6 though.

**Comment by d34d0n** [comment]
Also having issues extracting titles, tags, etc from PH. Seems it's only doing it for every other video scraped. About half are missing titles and tags.

**Comment by charon2019** [comment]
Please provide logs, @d34d0n:

```
youtube-dl --verbose <link>
```

**Comment by d34d0n** [comment]
> Please provide logs, @d34d0n:
> 
> ```
> youtube-dl --verbose <link>
> ```

d191194r ~]# youtube-dl --verbose http://www.pornhub.com
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.pornhub.com']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.09
[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-957.5.1.el7.x86_64-x86_64-with-centos-7.6.1810-Core
[debug] exe versions: ffmpeg 4.1.1-static, ffprobe 4.1.1-static
[debug] Proxy map: {}
[generic] www.pornhub: Requesting header
[redirect] Following redirect to https://www.pornhub.com/
[generic] www.pornhub: Requesting header
WARNING: Falling back on generic information extractor.
[generic] www.pornhub: Downloading webpage
[generic] www.pornhub: Extracting information
[download] Downloading playlist: Free Porn Videos & Sex Movies - Porno, XXX, Porn Tube | Pornhub
[generic] playlist Free Porn Videos & Sex Movies - Porno, XXX, Porn Tube | Pornhub: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'data:"+o+";base64,"+i+"'
Traceback (most recent call last):
File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 472, in main
File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 462, in _real_main
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2006, in download
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 805, in extract_info
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 866, in process_ie_result
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 805, in extract_info
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1004, in process_ie_result
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 859, in process_ie_result
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1640, in process_video_result
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1913, in process_info
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1852, in dl
File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 364, in download
File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2225, in urlopen
File "/usr/lib64/python2.7/urllib2.py", line 431, in open
response = self._open(req, data)
File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
'_open', req)
File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
result = func(*args)
File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2476, in data_open
binascii.Error: Incorrect padding

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl/issues/20343#issuecomment-472986195

**Comment by d34d0n** [comment]
Now it's not getting titles for RedTube either

**Comment by userisuserisuser** [comment]
Did you find a fix for this? Happens for me.
