### ISSUE TITLE
This video is not available

### ISSUE THREAD

**Issue by zannix** [ytdl-org/youtube-dl#20392]
Video in question: https://www.youtube.com/watch?v=5_ARibfCMhw

```
youtube-dl --get-url -f 140 5_ARibfCMhw --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--get-url', u'-f', u'140', u'5_ARibfCMhw', u'--verbose']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2019.03.18
[debug] Python version 2.7.6 (CPython) - Linux-3.13.0-143-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: This video is not available.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1982, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is not available.
```

Strange thing is this is the response from a remote server. Locally it works fine. Both are running the same version of youtube-dl.

**Comment by Hrxn** [comment]
Remote server? Like running from a VPS from a big provider or something?

**Comment by zannix** [comment]
No I mean just my remote server hosted on online.net

**Comment by dstftw** [comment]
The error is self-explanatory.
Can you watch it in browser from the same machine and IP?

**Comment by zannix** [comment]
Didn't try that. Would having a proxy help in these cases?
