### ISSUE TITLE
Add support for series pages/playlists of 7TV (prosiebensat1 Extractor)

### ISSUE THREAD

**Issue by DerBunteBall** [ytdl-org/youtube-dl#20404]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.18*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.03.18
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.7tv.de/richterin-barbara-salesch/ganze-folgen']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.18
[debug] Python version 2.7.16 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[prosiebensat1] richterin-barbara-salesch/ganze-folgen: Downloading webpage
ERROR: Unsupported page type frontpage
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/prosiebensat1.py", line 455, in _real_extract
    'Unsupported page type %s' % page_type, expected=True)
ExtractorError: Unsupported page type frontpage
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

Playlist: https://www.7tv.de/richterin-barbara-salesch/ganze-folgen

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

The download of single videos is working fine. They have something like series pages which show all available full episodes of a series/show/whatever. It would be nice when they could be downloaded as a playlist like youtube:playlist, TVNowAnnual.

*As a note*: I know at least nothing about webdevelopment but it seems the page uses AJAX for loading e.g. more episodes. There is this "MEHR ANZEIGEN" button which loads more episodes. These button disappears after 4-5 times clicked when all apisodes are shown (as far as I know up to 120 episodes). These button has the CSS class "teaser-load-more" and has a click event. These event calls a JavaScript function named loadMoreItems. These function seems to build a URL which throws back the episodes in HTML (as article elements). I don't know how these calls work exactly, these are my thoughts:

The URL for the above link is this https://www.7tv.de/psdflow/ajaxblock/(block)/1600530d298d8cd1de1e560337538f82/(offset)/24/(limit)/24/(node_id)/2358

The URL is unique in a series or a call (not sure). The scheme stays the same. I think the URL gets modified in the number after offset. I think the values are steps like 0/1, 24, 48, 72, 96 (at 96 we would be at 120 (96 + limit = 96 + 24)). It seems these URL wants no cookies or auth. As far as I can see the page generates cookies in JavaScript.

That's all I could find out in a few minutes as a n00b.

Eventually someone is able to build an extractor for this.

Best Regards

P.S. Sorry for my bad english :-D

**Comment by DerBunteBall** [comment]
Portal closed.
