### ISSUE TITLE
 Invalid data found when processing input

### ISSUE THREAD

**Issue by jmliz** [ytdl-org/youtube-dl#20442]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
output:

```
[user@pc Downloads]$ youtube-dl -v https://old.reddit.com/r/Perfectfit/comments/b421jb/bf_told_me_it_wouldnt_fit/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://old.reddit.com/r/Perfectfit/comments/b421jb/bf_told_me_it_wouldnt_fit/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.18
[debug] Python version 2.7.15 (CPython) - Linux-4.20.16-200.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
[debug] exe versions: ffmpeg 4.0.3, ffprobe 4.0.3, phantomjs 2.1.1
[debug] Proxy map: {}
[RedditR] b421jb: Downloading JSON metadata
[Reddit] 2iukf3mzgmn21: Downloading m3u8 information
[Reddit] 2iukf3mzgmn21: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://v.redd.it/2iukf3mzgmn21/HLS_576_v4.m3u8'
[download] Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.fhls-15784.mp4 has already been downloaded
[download] 100% of 1.66MiB
[debug] Invoking downloader on u'https://v.redd.it/2iukf3mzgmn21/audio'
[download] Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.fdash-AUDIO-1.m4a has already been downloaded
[download] 100% of 2.85KiB
[ffmpeg] Merging formats into "Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.fhls-15784.mp4' -i 'file:Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.fdash-AUDIO-1.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.temp.mp4'
ERROR: file:Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.fdash-AUDIO-1.m4a: Invalid data found when processing input
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 2052, in post_process
    files_to_delete, info = pp.run(info)
  File "/home/user/.local/lib/python2.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/home/user/.local/lib/python2.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: file:Bf told me it wouldn\u2019t fit  -,)-2iukf3mzgmn21.fdash-AUDIO-1.m4a: Invalid data found when processing input
```
It downloads audio and video but it seems unable to merge both in a single file.

**Comment by remitamine** [comment]
update ffmpeg.

**Comment by jmliz** [comment]
there were pending updates for ffmpeg. I updated to 4.0.3-4.fc29 via packg manager but still not working. I'm using Fedora Workstation 29. there's nothing else to update, or should I install it with another method?

output:

```
[user@pc Downloads]$ youtube-dl -v https://old.reddit.com/r/Perfectfit/comments/b421jb/bf_told_me_it_wouldnt_fit/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://old.reddit.com/r/Perfectfit/comments/b421jb/bf_told_me_it_wouldnt_fit/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.18
[debug] Python version 2.7.15 (CPython) - Linux-4.20.16-200.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
[debug] exe versions: ffmpeg 4.0.3, ffprobe 4.0.3, phantomjs 2.1.1
[debug] Proxy map: {}
[RedditR] b421jb: Downloading JSON metadata
[Reddit] 2iukf3mzgmn21: Downloading m3u8 information
[Reddit] 2iukf3mzgmn21: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://v.redd.it/2iukf3mzgmn21/HLS_576_v4.m3u8'
[download] Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.fhls-15784.mp4 has already been downloaded
[download] 100% of 1.66MiB
[debug] Invoking downloader on u'https://v.redd.it/2iukf3mzgmn21/audio'
[download] Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.fdash-AUDIO-1.m4a has already been downloaded
[download] 100% of 2.85KiB
[ffmpeg] Merging formats into "Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.fhls-15784.mp4' -i 'file:Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.fdash-AUDIO-1.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.temp.mp4'
ERROR: file:Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.fdash-AUDIO-1.m4a: Invalid data found when processing input
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 2052, in post_process
    files_to_delete, info = pp.run(info)
  File "/home/user/.local/lib/python2.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/home/user/.local/lib/python2.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: file:Bf told me it wouldn\u2019t fit  -,)-2iukf3mzgmn21.fdash-AUDIO-1.m4a: Invalid data found when processing input
```

**Comment by remitamine** [comment]
the latest version of ffmpeg is 4.1.1.
```
youtube-dl --ignore-config -v https://old.reddit.com/r/Perfectfit/comments/b421jb/bf_told_me_it_wouldnt_fit/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', 'https://old.reddit.com/r/Perfectfit/comments/b421jb/bf_told_me_it_wouldnt_fit/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.18
[debug] Python version 3.7.2 (CPython) - Linux-5.0.2-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[RedditR] b421jb: Downloading JSON metadata
[Reddit] 2iukf3mzgmn21: Downloading m3u8 information
[Reddit] 2iukf3mzgmn21: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://v.redd.it/2iukf3mzgmn21/HLS_576_v4.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 2
[download] Destination: Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.fhls-15784.mp4
[download] 100% of 1.66MiB in 00:04
[debug] Invoking downloader on 'https://v.redd.it/2iukf3mzgmn21/audio'
[download] Destination: Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.fdash-AUDIO-1.m4a
[download] 100% of 98.20KiB in 00:00
[ffmpeg] Merging formats into "Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.fhls-15784.mp4' -i 'file:Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.fdash-AUDIO-1.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.temp.mp4'
Deleting original file Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.fhls-15784.mp4 (pass -k to keep)
Deleting original file Bf told me it wouldn’t fit  -,)-2iukf3mzgmn21.fdash-AUDIO-1.m4a (pass -k to keep)
```

**Comment by jmliz** [comment]
@remitamine ok I have my fedora completely updated and version is still 4.1.1. How can I install the required version to work with youtubedl?

**Comment by remitamine** [comment]
it's available on RPM Fusion Rawhide repo.

**Comment by jmliz** [comment]
@remitamine I am using stable fedora. rawhide is development branch. does that mean that I should wait for it to be available in a stable version?

**Comment by remitamine** [comment]
I don't use Fedora anymore, you can enable rawhide or use static builds or build it yourself or search online for any way to get an updated version of FFmpeg.
This is an issue tracker for youtube-dl and as I explained it's not a problem in youtube-dl.

**Comment by pzygielo** [comment]
@jmliz - remove .m4a file
> remitamine: [download] 100% of 98.20KiB in 00:00
> jmliz: [download] 100% of 2.85KiB

and your log

> file:Bf told me it wouldn\u2019t fit  -,)-2iukf3mzgmn21.fdash-AUDIO-1.m4a: Invalid data found when processing input

and re-download.
ffmpeg 4.0.3 handles it correctly.

**Comment by jmliz** [comment]
@pzygielo yes it works now if I delete the files and redownload. thanks yall.
