### ISSUE TITLE
[GO] Charter_Direct MSO is not supported anymore.

### ISSUE THREAD

**Issue by compguy284** [ytdl-org/youtube-dl#20466]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.18*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://disneynow.go.com/shows/star-wars-resistance/season-01/episode-01-the-recruit/vdka5557087?pid=PL553044961', '-n', '--ap-mso', 'Charter_Direct', '--write-pages', '--get-filename', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.18
[debug] Python version 3.7.2 (CPython) - Linux-4.19.30-1-lts-x86_64-with-arch
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1
[debug] Proxy map: {}
ERROR: It appears that your Spectrum subscription does not include Disney.  To sign up for Disney and start using Disney's service, or if you believe you have received this message in error, please call 1-888-438-2427
Traceback (most recent call last):
  File "/home/mcguyver/src/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/home/mcguyver/src/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/home/mcguyver/src/youtube-dl/youtube-dl/youtube_dl/extractor/go.py", line 137, in _real_extract
    url, video_id, requestor_id, resource)
  File "/home/mcguyver/src/youtube-dl/youtube-dl/youtube_dl/extractor/adobepass.py", line 1551, in _extract_mvpd_auth
    raise ExtractorError(xml_text(authorize, 'details'), expected=True)
youtube_dl.utils.ExtractorError: It appears that your Spectrum subscription does not include Disney.  To sign up for Disney and start using Disney's service, or if you believe you have received this message in error, please call 1-888-438-2427
```

---

Charter_Direct MSO is not supported anymore. Applying this patch works for me. Not sure how to make it work if logging in from a non Spectrum IP address.

```
diff --git a/youtube_dl/extractor/adobepass.py b/youtube_dl/extractor/adobepass.py
index 1cf2dcbf3..d121eff13 100644
--- a/youtube_dl/extractor/adobepass.py
+++ b/youtube_dl/extractor/adobepass.py
@@ -55,6 +55,11 @@ MSO_INFO = {
         'username_field': 'IDToken1',
         'password_field': 'IDToken2',
     },
+    'Spectrum': {
+        'name': 'Spectrum',
+        'username_field': 'IDToken1',
+        'password_field': 'IDToken2',
+    },
     'Verizon': {
         'name': 'Verizon FiOS',
         'username_field': 'IDToken1',
@@ -1507,7 +1512,8 @@ class AdobePassIE(InfoExtractor):
                         mso_info.get('username_field', 'username'): username,
                         mso_info.get('password_field', 'password'): password,
                     })
-                    if mso_id != 'Rogers':
+                    if mso_id not in {'Rogers', 'Spectrum'}:
+                        print(mso_id)
                         post_form(mvpd_confirm_page_res, 'Confirming Login')
 
                 session = self._download_webpage(

```

**Comment by tmthywynn8** [comment]
Do you want me to put this in as a pull request, since it seems there hasn't been any activity for a little under a year?
