### ISSUE TITLE
Mediasite Catalog batch download

### ISSUE THREAD

**Issue by th3picow** [ytdl-org/youtube-dl#20507]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.18*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://mediasite.video.ufl.edu/Mediasite/Catalog/Full/58a2c26a048c42de8950c7f68c1e754021#!']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.03.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 58a2c26a048c42de8950c7f68c1e754021#!: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 58a2c26a048c42de8950c7f68c1e754021#!: Downloading webpage
[generic] 58a2c26a048c42de8950c7f68c1e754021#!: Extracting information
ERROR: Unsupported URL: https://mediasite.video.ufl.edu/Mediasite/Catalog/Full/58a2c26a048c42de8950c7f68c1e754021#!
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpcs52imf5\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpcs52imf5\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpcs52imf5\build\youtube_dl\extractor\generic.py", line 3320, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://mediasite.video.ufl.edu/Mediasite/Catalog/Full/58a2c26a048c42de8950c7f68c1e754021#!
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Playlist: https://mediasite.video.ufl.edu/Mediasite/Catalog/Full/58a2c26a048c42de8950c7f68c1e754021#!

---

### Description of your *issue*, suggested solution and other information

Ability to download catalog of videos from mediasite, see link above for example of one such catalog. 
Downloading the videos individually by copy pasting the individual links for each video works no problem, but my university has lectures organized in catalogs and being able to use to catalog link to batch download would be much faster.

I'm in no way good enough at coding to do this but I'm gouessing this is what has to be done to make it work:

1. Make https://mediasite.  /Mediasite/Catalog/    a valid url

2. Make a list of all video links in the catalog, example of where the link is located from inspect element:
```
<a id="cardTitle" href="https://mediasite.video.ufl.edu/Mediasite/Play/215b650c9ed74fa2b5f439ac900e32301d?catalog=58a2c26a048c42de8950c7f68c1e754021" target="_new" class="titleLink " title="View Presentation">2019 Spring Commencement - College of Veterinary Medicine</a>
```
3. Download each video using the regular downloader

**Comment by th3picow** [comment]
Thank you very much for the added feature.
Unfortunately my university has a slightly different formatting on the url (my bad for not providing that link as an example):

https://mediasite.uis.no/Mediasite/Catalog/catalogs/sta100-v2019

From reading the added code /catalogs just needs to be added as a valid url alongside /Full

Not sure how login credentials are usually handled but just send me a pm and I'll give it to you
