### ISSUE TITLE
ERROR:   Stream #1:0 -> #0:1 (copy)

### ISSUE THREAD

**Issue by sikro94** [ytdl-org/youtube-dl#20515]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.18*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
youtube-dl -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best https://www.youtube.com/watch?v=HDwW9V85NOE --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', u'https://www.youtube.com/watch?v=HDwW9V85NOE', u'--verbose']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2019.03.18
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-8-amd64-x86_64-with-debian-9.5
[debug] exe versions: avconv 3.2.12-1, avprobe 3.2.12-1, ffmpeg 3.2.12-1, ffprobe 3.2.12-1
[debug] Proxy map: {}
[youtube] HDwW9V85NOE: Downloading webpage
[youtube] HDwW9V85NOE: Downloading video info webpage
[youtube] {18} signature length 46.43, html5 player vflUi8DdH
[youtube] {137} signature length 46.43, html5 player vflUi8DdH
[youtube] {248} signature length 46.43, html5 player vflUi8DdH
[youtube] {136} signature length 46.43, html5 player vflUi8DdH
[youtube] {247} signature length 46.43, html5 player vflUi8DdH
[youtube] {398} signature length 46.43, html5 player vflUi8DdH
[youtube] {135} signature length 46.43, html5 player vflUi8DdH
[youtube] {244} signature length 46.43, html5 player vflUi8DdH
[youtube] {397} signature length 46.43, html5 player vflUi8DdH
[youtube] {134} signature length 46.43, html5 player vflUi8DdH
[youtube] {243} signature length 46.43, html5 player vflUi8DdH
[youtube] {396} signature length 46.43, html5 player vflUi8DdH
[youtube] {133} signature length 46.43, html5 player vflUi8DdH
[youtube] {242} signature length 46.43, html5 player vflUi8DdH
[youtube] {395} signature length 46.43, html5 player vflUi8DdH
[youtube] {160} signature length 46.43, html5 player vflUi8DdH
[youtube] {278} signature length 46.43, html5 player vflUi8DdH
[youtube] {394} signature length 46.43, html5 player vflUi8DdH
[youtube] {140} signature length 46.43, html5 player vflUi8DdH
[youtube] {171} signature length 46.43, html5 player vflUi8DdH
[youtube] {249} signature length 46.43, html5 player vflUi8DdH
[youtube] {250} signature length 46.43, html5 player vflUi8DdH
[youtube] {251} signature length 46.43, html5 player vflUi8DdH
[debug] Invoking downloader on u'https://r1---sn-25glen7l.googlevideo.com/videoplayback?id=1c3c16f55f3934e1&aitags=133,134,135,136,137,160,242,243,244,247,248,278,394,395,396,397,398&itag=398&source=youtube&requiressl=yes&mm=31,26&mn=sn-25glen7l,sn-4g5edned&ms=au,onr&mv=m&pl=21&ei=DfSgXN64JciOVLvlvpAP&susc=yt&initcwndbps=355000&mime=video/mp4&gir=yes&clen=5118066&dur=273.873&lmt=1540553334827877&mt=1554052029&fvip=1&keepalive=yes&c=WEB&txp=5511222&ip=51.75.123.148&ipbits=0&expire=1554073709&sparams=ip,ipbits,expire,id,aitags,source,requiressl,mm,mn,ms,mv,pl,ei,susc,initcwndbps,mime,gir,clen,dur,lmt&key=yt8&signature=99711965275DF87D55B75EED61BC29A3E061A5A6.92E457F701FF0154FF3BC5F331315F11C119A79E&ratebypass=yes'
[download] Bir_ay_dogar_ilk_aksamdan_geceden_Daglar_Kisimis_-_Cengiz_Ozkan-HDwW9V85NOE.f398.mp4 has already been downloaded
[download] 100% of 4.88MiB
[debug] Invoking downloader on u'https://r1---sn-25glen7l.googlevideo.com/videoplayback?id=1c3c16f55f3934e1&itag=140&source=youtube&requiressl=yes&mm=31,26&mn=sn-25glen7l,sn-4g5edned&ms=au,onr&mv=m&pl=21&ei=DfSgXN64JciOVLvlvpAP&susc=yt&initcwndbps=355000&mime=audio/mp4&gir=yes&clen=4351293&dur=273.925&lmt=1540549014261812&mt=1554052029&fvip=1&keepalive=yes&c=WEB&txp=5533432&ip=51.75.123.148&ipbits=0&expire=1554073709&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,pl,ei,susc,initcwndbps,mime,gir,clen,dur,lmt&key=yt8&signature=453782F6F0B398FE8984AC0E1FB0EBEB1E1D5D64.3B5C586CEA07425B860260E848803C9F20D5C317&ratebypass=yes'
[download] Bir_ay_dogar_ilk_aksamdan_geceden_Daglar_Kisimis_-_Cengiz_Ozkan-HDwW9V85NOE.f140.m4a has already been downloaded
[download] 100% of 4.15MiB
[ffmpeg] Merging formats into "Bir_ay_dogar_ilk_aksamdan_geceden_Daglar_Kisimis_-_Cengiz_Ozkan-HDwW9V85NOE.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Bir_ay_dogar_ilk_aksamdan_geceden_Daglar_Kisimis_-_Cengiz_Ozkan-HDwW9V85NOE.f398.mp4' -i 'file:Bir_ay_dogar_ilk_aksamdan_geceden_Daglar_Kisimis_-_Cengiz_Ozkan-HDwW9V85NOE.f140.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:Bir_ay_dogar_ilk_aksamdan_geceden_Daglar_Kisimis_-_Cengiz_Ozkan-HDwW9V85NOE.temp.mp4'
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2052, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=HDwW9V85NOE

---

### Description of your *issue*, suggested solution and other information

Hello,

I have a personal php script that allows me to download the youtube videos of my choice. I'm looking to get the video in the best possible format, in mp4. I noticed today that it doesn't work for a video.

My server is running under debian 9, latest version of youtube-dl and ffmpeg.

Thank you

**Comment by dstftw** [comment]
Outdated ffmpeg.

**Comment by luckydonald** [comment]
I freshly installed it from homebrew and having the same issue @dstftw

**Comment by luckydonald** [comment]
Even 
```bash
brew install ffmpeg --HEAD --fetch-HEAD --build-from-source
```
didn't fix it for me (macOS Mojave)

Which version of ffmpeg do I need?

**Comment by 1vasari** [comment]
No idea if this helps but I was getting this error when doing `youtube-dl -f bestvideo+bestaudio --merge-output-format mp4 "<url>"`. Changing the `--merge-output-format` option to `mkv` worked.

This was on Mojave, latest `youtube-dl` and latest `ffmepg`, installed through Homebrew.

**Comment by bearstampede** [comment]
I am also getting this error when using the "default" profile, and after a lot of troubleshooting (and no changes in ffmpeg/python/youtube-dl versions), I was able to recreate and narrow down the issue. TL;DR--try disabling both "Embed thumbnail in audio file" and "Add metadata to file".

With both options enabled, I got the following result and 0 files downloaded: 

```
[06/08/20 19:16:26] [debug] System config: []
[06/08/20 19:16:26] [debug] User config: []
[06/08/20 19:16:26] [debug] Custom config: []
[06/08/20 19:16:26] [debug] Command-line args: ['--newline', '--write-auto-sub', '-o', 'E:\\resources\\Watch\\%(title)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', '--embed-thumbnail', '--add-metadata', '--force-ipv4', 'https://www.youtube.com/channel/UCfpnY5NnBl-8L7SvICuYkYQ']
[06/08/20 19:16:26] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[06/08/20 19:16:26] [debug] youtube-dl version 2020.05.08
[06/08/20 19:16:26] [debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[06/08/20 19:16:26] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[06/08/20 19:16:26] [debug] Proxy map: {}
[06/08/20 19:16:26] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[06/08/20 19:16:26] ERROR: Only mp3 and m4a/mp4 are supported for thumbnail embedding for now.
[06/08/20 19:16:26] Traceback (most recent call last):
[06/08/20 19:16:26]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 2065, in post_process
[06/08/20 19:16:26]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\postprocessor\embedthumbnail.py", line 91, in run
[06/08/20 19:16:26] youtube_dl.postprocessor.embedthumbnail.EmbedThumbnailPPError: Only mp3 and m4a/mp4 are supported for thumbnail embedding for now.
[06/08/20 19:16:26]
```
With only "Add metadata to file" enabled, I got the following result and _some_ files (47/999) downloaded. The "Requested formats are incompatible for merge" warning showed up 41 times, so I only included the warning once to keep it as concise as possible.

```
[06/08/20 19:26:47] [debug] System config: []
[06/08/20 19:26:47] [debug] User config: []
[06/08/20 19:26:47] [debug] Custom config: []
[06/08/20 19:26:47] [debug] Command-line args: ['--newline', '--write-auto-sub', '-o', 'E:\\resources\\Watch\\%(title)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', '--add-metadata', '--force-ipv4', 'https://www.youtube.com/channel/UCfpnY5NnBl-8L7SvICuYkYQ']
[06/08/20 19:26:47] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[06/08/20 19:26:47] [debug] youtube-dl version 2020.05.08
[06/08/20 19:26:47] [debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[06/08/20 19:26:47] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[06/08/20 19:26:47] [debug] Proxy map: {}
[06/08/20 19:26:47] WARNING: Requested formats are incompatible for merge and will be merged into mkv.
...
[06/08/20 19:26:48] ERROR:   Stream #1:0 -> #0:1 (copy)
[06/08/20 19:26:48] Traceback (most recent call last):
[06/08/20 19:26:48]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 2065, in post_process
[06/08/20 19:26:48]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\postprocessor\ffmpeg.py", line 512, in run
[06/08/20 19:26:48]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
[06/08/20 19:26:48] youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)
[06/08/20 19:26:48] 
```
This is the video that ultimately killed the job:
https://www.youtube.com/channel/UCfpnY5NnBl-8L7SvICuYkYQ

I tried re-running that video by itself but received the same error. Out of curiosity, I changed the profile from [default] to [mp4], re-enabled the problematic options--and got a different error complaining about AtomicParsley:

```
[06/08/20 20:14:08] [debug] System config: []
[06/08/20 20:14:08] [debug] User config: []
[06/08/20 20:14:08] [debug] Custom config: []
[06/08/20 20:14:08] [debug] Command-line args: ['--newline', '--write-auto-sub', '-o', 'C:\\Users\\dverm_000\\Desktop\\%(title)s.%(ext)s', '-f', 'mp4', '-v', '--ignore-config', '--hls-prefer-native', '--embed-thumbnail', '--add-metadata', '--force-ipv4', 'https://www.youtube.com/watch?v=Uf8QlLF2fIM']
[06/08/20 20:14:08] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[06/08/20 20:14:08] [debug] youtube-dl version 2020.05.08
[06/08/20 20:14:08] [debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[06/08/20 20:14:08] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[06/08/20 20:14:08] [debug] Proxy map: {}
[06/08/20 20:14:08] ERROR: AtomicParsley was not found. Please install.
[06/08/20 20:14:08] Traceback (most recent call last):
[06/08/20 20:14:08]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 2065, in post_process
[06/08/20 20:14:08]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\postprocessor\embedthumbnail.py", line 60, in run
[06/08/20 20:14:08] youtube_dl.postprocessor.embedthumbnail.EmbedThumbnailPPError: AtomicParsley was not found. Please install.
[06/08/20 20:14:08] 
```
Ultimately, the files downloaded in every case, but these errors cause the entire job to grind to a halt. There are also leftover "duplicate" .mp4 files whose filesize is 0 bytes (generated for an operation that was unable to be completed?).

Hopefully this is helpful rather than annoying; I don't post too often so I'm unsure if this is the right way to go about it. I just wanted to share my own findings with this specific issue.

**Comment by Closty** [comment]
If `--merge-output-format mp4 "<url>"` 
Then error
Because its original format is mp4,it doesn't need to change! Check it!

**Comment by Jimi-James** [comment]
I'm still running into this issue even nowadays. I think it may be best to either have those two options (embedding metadata and embedding thumbnails) result in an automatic implied MKV merge format (perhaps warning the user in case that matters to that), or have more logic within the program keeping better track of which formats can and can't be merged together and choosing compatible ones accordingly.

I can't think of why it matters which of those two options are chosen, and one of them is a lot less work. Until one of them is chosen, people who want to embed metadata and/or a thumbnail will continue to run into this issue and be very confused, and it's a crapshoot whether they stumble upon this bug report and learn what's going on.

**Comment by KAdelio** [comment]
I found myself with the same problem and I could solve it changing the audio source.
