### ISSUE TITLE
Error NBC Unable to extract SAML Login URL 

### ISSUE THREAD

**Issue by ehurdler** [ytdl-org/youtube-dl#20529]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.18*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ x] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v --ap-mso 'Verizon' --ap-username '***********' --ap-password '**********' https://www.nbc.com/superstore/video/back-to-school/3802458
[debug] System config: []
[debug] User config: ['--prefer-ffmpeg', '-f', 'best[height=720]', '-o', '%(series)s - s%(season_number)02de%(episode_number)02d - %(title)s.%(ext)s', '--audio-format', 'best']
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ap-mso', 'Verizon', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.nbc.com/superstore/video/back-to-school/3802458']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.18
[debug] Python version 3.7.2 (CPython) - Darwin-18.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[NBC] 3802458: Downloading JSON metadata
[NBC] 3802458: Downloading Provider Redirect Page
[NBC] 3802458: Downloading SAML Login Page
ERROR: Unable to extract SAML Login URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/nbc.py", line 106, in _real_extract
    url, video_id, 'nbcentertainment', resource)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/adobepass.py", line 1482, in _extract_mvpd_auth
    saml_login_page, 'SAML Login URL', group='url')
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract SAML Login URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I am using youtube-dl for tv shows on NBC's website.  I am using Verizon credentials and had been doing this for a while with the verizon mso settings with no issue.  I recently reimaged my macbook and installed everything fresh.  youtube-dl had been working from nbc's website getting past seasons of "Superstore" episodes with no issue.  https://www.nbc.com/superstore/video/baby-shower/3806777  Now I am getting the above stated issue.  I am not sure if I somehow am having issues based on python version?  Or if I have certain files in the wrong place and they are not being called by youtube-dl anymore?  If there is any advice or help anyone can provide please let me know.  I tried to follow info from here: https://github.com/ytdl-org/youtube-dl/pull/14363 as issue seemed similar.  I keep coming up with errors, and will not work.

**Comment by 89z** [comment]
URL is dead
