### ISSUE TITLE
FFMPEG failed to merge webm audio and mp4

### ISSUE THREAD

**Issue by hang333** [ytdl-org/youtube-dl#20533]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.01*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '137+251', '--merge-output-format', 'mp4', 'https://www.youtube.com/watch?v=siIE8i48hlg', '-v']
[debug] Encodings: locale cp65001, fs mbcs, out cp65001, pref cp65001
[debug] youtube-dl version 2019.04.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-93506-g27c94c57dc, ffprobe N-93506-g27c94c57dc
[debug] Proxy map: {}
[youtube] siIE8i48hlg: Downloading webpage
[youtube] siIE8i48hlg: Downloading video info webpage
[debug] Invoking downloader on 'https://r2---sn-uh-30aek.googlevideo.com/videoplayback?dur=1818.549&lmt=1540606332888827&key=yt6&ipbits=0&initcwndbps=695000&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&mime=video%2Fmp4&requiressl=yes&mn=sn-uh-30aek%2Csn-30a7yn7k&source=youtube&signature=28975EC3365A6E338241B3130221EA51EF22E4B3.7C10FD2B74662E8DC9CBBA99C5DCDB56B7FCABA5&ip=2001%3Ae68%3A5440%3A5023%3A35fb%3A85bb%3A269d%3A5a30&ei=VyijXM-WMJ2bz7sP6bu0mA4&ms=au%2Crdu&mt=1554196456&itag=137&pl=42&mv=m&expire=1554218167&clen=156977371&id=o-AI6kUR5OCRqGz-aRipFlMa9TDuRLwHtdGla5U2SzfxFU&fvip=2&keepalive=yes&c=WEB&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&gir=yes&txp=5533432&mm=31%2C29&ratebypass=yes'
[download] Destination: ボーカロイドたちが2コードくり返してﾃｯﾃｰﾃﾚｯﾃｰとか叫ぶだけ-siIE8i48hlg.f137.mp4
[download] 100% of 149.71MiB in 00:13
[debug] Invoking downloader on 'https://r2---sn-uh-30aek.googlevideo.com/videoplayback?dur=1818.601&lmt=1540609188466875&key=yt6&ipbits=0&initcwndbps=695000&mime=audio%2Fwebm&requiressl=yes&mn=sn-uh-30aek%2Csn-30a7yn7k&source=youtube&signature=4F73FEF1F9F42C8688F74A0FFF2E7D426E4FC2D1.09C38C85D613100AD630F6DCF67585B2C0E30C2A&ip=2001%3Ae68%3A5440%3A5023%3A35fb%3A85bb%3A269d%3A5a30&ei=VyijXM-WMJ2bz7sP6bu0mA4&ms=au%2Crdu&mt=1554196456&itag=251&pl=42&mv=m&expire=1554218167&clen=31111210&id=o-AI6kUR5OCRqGz-aRipFlMa9TDuRLwHtdGla5U2SzfxFU&fvip=2&keepalive=yes&c=WEB&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&gir=yes&txp=5511222&mm=31%2C29&ratebypass=yes'
[download] Destination: ボーカロイドたちが2コードくり返してﾃｯﾃｰﾃﾚｯﾃｰとか叫ぶだけ-siIE8i48hlg.f251.webm
[download] 100% of 29.67MiB in 00:02
[ffmpeg] Merging formats into "ボーカロイドたちが2コードくり返してﾃｯﾃｰﾃﾚｯﾃｰとか叫ぶだけ-siIE8i48hlg.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:ボーカロイドたちが2コードくり返してﾃｯﾃｰﾃﾚｯﾃｰとか叫ぶだけ-siIE8i48hlg.f137.mp4" -i "file:ボーカロイドたちが2コードくり返してﾃｯﾃｰﾃﾚｯﾃｰとか叫ぶだけ-siIE8i48hlg.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:ボーカロイドたちが2コードくり返してﾃｯﾃｰﾃﾚｯﾃｰとか叫ぶだけ-siIE8i48hlg.temp.mp4"
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\YoutubeDL.py", line 2052, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\postprocessor\ffmpeg.py", line 512, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)
```

### Description of your *issue*, suggested solution and other information

Video link : https://www.youtube.com/watch?v=siIE8i48hlg

```
[info] Available formats for siIE8i48hlg:
format code  extension  resolution note
249          webm       audio only DASH audio   65k , opus @ 50k, 11.30MiB
250          webm       audio only DASH audio   87k , opus @ 70k, 14.99MiB
140          m4a        audio only DASH audio  129k , m4a_dash container, mp4a.40.2@128k, 27.55MiB
171          webm       audio only DASH audio  141k , vorbis@128k, 28.31MiB
251          webm       audio only DASH audio  163k , opus @160k, 29.67MiB
160          mp4        256x144    144p  125k , avc1.4d400c, 30fps, video only, 8.67MiB
278          webm       256x144    144p  144k , webm container, vp9, 30fps, video only, 13.02MiB
242          webm       426x240    240p  238k , vp9, 30fps, video only, 18.73MiB
133          mp4        426x240    240p  332k , avc1.4d4015, 30fps, video only, 16.59MiB
243          webm       640x360    360p  539k , vp9, 30fps, video only, 33.69MiB
134          mp4        640x360    360p  672k , avc1.4d401e, 30fps, video only, 31.85MiB
244          webm       854x480    480p  843k , vp9, 30fps, video only, 51.30MiB
135          mp4        854x480    480p 1319k , avc1.4d401f, 30fps, video only, 53.07MiB
247          webm       1280x720   720p 1769k , vp9, 30fps, video only, 94.79MiB
136          mp4        1280x720   720p 2327k , avc1.4d401f, 30fps, video only, 84.35MiB
248          webm       1920x1080  1080p 2953k , vp9, 30fps, video only, 171.75MiB
137          mp4        1920x1080  1080p 4349k , avc1.640028, 30fps, video only, 149.71MiB
18           mp4        640x360    medium  428k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 92.99MiB (best)
```
Selecting format 137+251 to merge, but ffmpeg error.

**Comment by dstftw** [comment]
mp4+webm cant be merged into mp4 container.
