### ISSUE TITLE
Pluralsight - No video format found

### ISSUE THREAD

**Issue by rdzberisha** [ytdl-org/youtube-dl#20538]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.01*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### The purpose of this *issue* is a *bug report*. Provided full verbose output as follows:

```
youtube-dl --version
2019.04.01
youtube-dl --username "x" --password "x" -o"%(playlist_index)s - %(title)s.%(ext)s" --min-sleep-interval 30 --max-sleep-interval 60 https://app.pluralsight.com/library/courses/implementing-windows-server-2016-dhcp --all-subs --cookies /home/x/Desktop/cookies.txt -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'-o%(playlist_index)s - %(title)s.%(ext)s', u'--min-sleep-interval', u'30', u'--max-sleep-interval', u'60', u'https://app.pluralsight.com/library/courses/implementing-windows-server-2016-dhcp', u'--all-subs', u'--cookies', u'/home/x/Desktop/cookies.txt', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.01
[debug] Python version 2.7.15+ (CPython) - Linux-4.18.0-13-generic-x86_64-with-Ubuntu-18.10-cosmic
[debug] exe versions: ffmpeg 4.0.2-2, ffprobe 4.0.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[pluralsight:course] implementing-windows-server-2016-dhcp: Downloading JSON metadata
[download] Downloading playlist: Implementing Windows Server 2016 DHCP
[pluralsight:course] playlist Implementing Windows Server 2016 DHCP: Collected 62 video ids (downloading 62 of them)
[download] Downloading video 1 of 62
[pluralsight] Downloading login page
[pluralsight] Logging in
[pluralsight] implementing-windows-server-2016-dhcp-m0-0: Downloading JSON metadata
[pluralsight] implementing-windows-server-2016-dhcp-m0-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] implementing-windows-server-2016-dhcp-m0-0: Waiting for 2 seconds to avoid throttling
[pluralsight] implementing-windows-server-2016-dhcp-m0-0: Downloading captions JSON
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: 01 - Course Overview.en.srt
[debug] Invoking downloader on u'https://vid5.pluralsight.com/expiretime=1554249113/4e7e36aace5002905fd98c3d3b4a5bbd/clips/resolution/8ca1a99a-db38-4cd1-8d38-5a135b0d30b0/current/mp4/1280x720.mp4'
[download] 01 - Course Overview.mp4 has already been downloaded
[download] 100% of 3.42MiB
[download] Downloading video 2 of 62
[pluralsight] implementing-windows-server-2016-dhcp-m1-0: Downloading JSON metadata
[pluralsight] implementing-windows-server-2016-dhcp-m1-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] implementing-windows-server-2016-dhcp-m1-0: Waiting for 4 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 421, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1326, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

...
<end of log>
```
Every course i try to download gives the same symptoms, it downloads first video of the series, and the others fail. I've tried giving the -f specifying resolution, didn't work either. It stopped working from february update. Courses work on browser.

**Comment by rdzberisha** [comment]
Expired Plan!
