### ISSUE TITLE
Sonyliv extractor no longer working 

### ISSUE THREAD

**Issue by Coolguy249** [ytdl-org/youtube-dl#20576]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.01*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\youtube-dl>youtube-dl -v https://www.sonyliv.com/details/episodes/6022957026001/Ep.-326---Murari-Asked-For-The-Murari-Asked-For-The-Dowry---Jijaji-Chhat-Per-Hain---5-April-2019
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.sonyliv.com/details/episodes/6022957026001/Ep.-326---Murari-Asked-For-The-Murari-Asked-For-The-Dowry---Jijaji-Chhat-Per-Hain---5-April-2019']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.04.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] Using fake IP 117.194.232.232 (IN) as X-Forwarded-For.
[brightcove:new] ref:6022957026001: Downloading webpage
[brightcove:new] ref:6022957026001: Downloading JSON metadata
[brightcove:new] ref:6022957026001: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[brightcove:new] ref:6022957026001: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\extractor\brightcove.py", line 775, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\extractor\brightcove.py", line 680, in _parse_brightcove_metadata
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\extractor\common.py", line 1326, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

...
<end of log>
```

---

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden.
please Fix the issue

**Comment by Coolguy249** [comment]
After 15-20 minutes this Website is now working please see this issue.
C:\youtube-dl>youtube-dl -v https://www.sonyliv.com/details/episodes/6022957026001/Ep.-326---Murari-Asked-For-The-Murari-Asked-For-The-Dowry---Jijaji-Chhat-Per-Hain---5-April-2019
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.sonyliv.com/details/episodes/6022957026001/Ep.-326---Murari-Asked-For-The-Murari-Asked-For-The-Dowry---Jijaji-Chhat-Per-Hain---5-April-2019']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.04.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] Using fake IP 117.221.65.125 (IN) as X-Forwarded-For.
[brightcove:new] ref:6022957026001: Downloading webpage
[brightcove:new] ref:6022957026001: Downloading JSON metadata
[brightcove:new] ref:6022957026001: Downloading m3u8 information
[brightcove:new] ref:6022957026001: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://streaming.sonyliv.com/show_sab_jijajichhatperhai_ep327.mpd?__nn__=5606168722001&hdnea=1554510600_b736839a1efb627b786ed1f31769d262'
[dashsegments] Total fragments: 221
[download] Destination: Ep. 326 - Murari Asked For The Murari Asked For The Dowry - Jijaji Chhat Per Hain - 5 April 2019-ref -6022957026001.fdash-1.mp4
[download]   0.9% of ~60.93MiB at 268.44KiB/s ETA 09:16
ERROR: Interrupted by user
