### ISSUE TITLE
GDCVault has changed video formats

### ISSUE THREAD

**Issue by vvuk** [ytdl-org/youtube-dl#20575]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.01**
- [X] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)

---

GDCVault seems to have changed, and the current extractor doesn't seem to function.  This URL is public (no login required) for testing:  https://www.gdcvault.com/play/1026496/-Marvel-s-Spider-Man

Exception:
```
$ youtube-dl --verbose https://www.gdcvault.com/play/1026496/-Marvel-s-Spider-Man
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.gdcvault.com/play/1026496/-Marvel-s-Spider-Man']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.04.01
[debug] Python version 2.7.13 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[GDCVault] -Marvel-s-Spider-Man: Downloading webpage
WARNING: [GDCVault] It looks like http://www.gdcvault.com/play/1026496 requires a login. Try specifying a username and password and try again.
WARNING: [GDCVault] Could not login.
ERROR: Unable to extract xml filename; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\gdcvault.py", line 166, in _real_extract
    start_page, 'xml filename')
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 1013, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract xml filename; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by vvuk** [comment]
The latest player seems to be in iframe with an URL like [this one](https://cdnapisec.kaltura.com/p/1670711/sp/167071100/embedIframeJs/uiconf_id/43558772/partner_id/1670711?iframeembed=true&playerId=kaltura_player_1547062087&cache_st=1547072087&width=1000&height=570&entry_id=1_bln945rf&videoid=d40357b7890ec26ea5521026496) .  It looks like this player downloads a master.m3u8 which has a list of akamai hosted streams.

**Comment by remitamine** [comment]
for you can use:
```
youtube-dl --force-generic-extractor https://www.gdcvault.com/play/1026496/-Marvel-s-Spider-Man
```

**Comment by vvuk** [comment]
Ah, that works! Thank you, I should have tried that first.

**Comment by ed4053** [comment]
Same problem here but the work around doesn't work for https://www.gdcvault.com/play/1025784/Designing-Path-of-Exile-to
I get:
[generic] Designing-Path-of-Exile-to: Requesting header
WARNING: Forcing on generic information extractor.
[generic] Designing-Path-of-Exile-to: Downloading webpage
[generic] Designing-Path-of-Exile-to: Extracting information
[Kaltura] 0_7tsa3kxn: Downloading video info JSON
[Kaltura] 0_7tsa3kxn: Downloading m3u8 information
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by remitamine** [comment]
you can always choose another format when the best is not working:
```
youtube-dl -f mp4-785 --force-generic-extractor https://gdcvault.com/play/1025784/Designing-Path-of-Exile-to
```

**Comment by ed4053** [comment]
> you can always choose another format when the best is not working:
> 
> ```
> youtube-dl -f mp4-785 --force-generic-extractor https://gdcvault.com/play/1025784/Designing-Path-of-Exile-to
> ```

Thanks a lot, that worked :)

**Comment by rgarat** [comment]
Hi @remitamine do you have any guideline about how to make a proper fix so that the gdcvault extractor can handle all the variations? I would love to try to attempt and contribute a fix

**Comment by rgarat** [comment]
I found another kind of error 

$ ./youtube-dl.exe --verbose --force-generic-extractor https://www.gdcvault.com/play/1025772/-Into-the-Breach-Design
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--force-generic-extractor', 'https://www.gdcvault.com/play/1025772/-Into-the-Breach-Design']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2019.04.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[generic] -Into-the-Breach-Design: Requesting header
WARNING: Forcing on generic information extractor.
[generic] -Into-the-Breach-Design: Downloading webpage
[generic] -Into-the-Breach-Design: Extracting information
[Kaltura] 0_rotss160: Downloading video info JSON
[Kaltura] 0_rotss160: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1670711/sp/167071100/playManifest/entryId/0_rotss160/format/url/protocol/http/flavorId/0_3gzy5vj5?referrer=aHR0cHM6Ly93d3cuZ2RjdmF1bHQuY29t'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\YoutubeDL.py", line 1913, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\YoutubeDL.py", line 1852, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\YoutubeDL.py", line 2225, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 502, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 685, in http_error_302
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by MetanoKid** [comment]
Wouldn't want to pollute this issue, but also found a different error while trying the `--force-generic-extractor` flag on this one: https://www.gdcvault.com/play/1026180/Mastering-the-Apex-of-Scaling

    > youtube-dl.exe https://www.gdcvault.com/play/1026180/Mastering-the-Apex-of-Scaling --force-generic-extractor --verbose
    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: ['https://www.gdcvault.com/play/1026180/Mastering-the-Apex-of-Scaling', '--force-generic-extractor', '--verbose']
    [debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
    [debug] youtube-dl version 2019.04.07
    [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
    [debug] exe versions: ffmpeg N-93542-gecdaa4b4fa, ffprobe N-93542-gecdaa4b4fa
    [debug] Proxy map: {}
    [generic] Mastering-the-Apex-of-Scaling: Requesting header
    WARNING: Forcing on generic information extractor.
    [generic] Mastering-the-Apex-of-Scaling: Downloading webpage
    [generic] Mastering-the-Apex-of-Scaling: Extracting information
    ERROR: no suitable InfoExtractor for URL kaltura:1670711:       0_h1fg8j3p#__youtubedl_smuggle=%7B%22source_url%22%3A+%22https%3A%2F%2Fwww.gdcvault.com%2Fplay%2F1026180%2FMastering-the-Apex-of-Scaling%22%7D
      File "__main__.py", line 19, in <module>
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\__init__.py", line 474, in main
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\__init__.py", line 464, in _real_main
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\YoutubeDL.py", line 2008, in download
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\YoutubeDL.py", line 807, in extract_info
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\YoutubeDL.py", line 868, in process_ie_result
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\YoutubeDL.py", line 830, in extract_info
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\YoutubeDL.py", line 624, in report_error
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\YoutubeDL.py", line 586, in trouble

Hope it's useful.

**Comment by remitamine** [comment]
> I found another kind of error

@rgarat read previews comments.
