### ISSUE TITLE
[Site support request] : watch.tbn.tv

### ISSUE THREAD

**Issue by sebma** [ytdl-org/youtube-dl#20621]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.07*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`) :

```python
$ youtube-dl -v --ignore-config -F --username my_email@email_provider.fr https://watch.tbn.tv/joseph-prince-live-the-let-go-life/videos/joseph-prince-live-the-let-go-life
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', '-F', '--username', 'PRIVATE', 'https://watch.tbn.tv/joseph-prince-live-the-let-go-life/videos/joseph-prince-live-the-let-go-life']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.07
[debug] Python version 3.6.5 (CPython) - Linux-4.4.0-143-generic-x86_64-with-debian-jessie-sid
[debug] exe versions: avconv 4.1.1-0york1, avprobe 4.1.1-0york1, ffmpeg 4.1.1-0york1, ffprobe 4.1.1-0york1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] joseph-prince-live-the-let-go-life: Requesting header
WARNING: Falling back on generic information extractor.
[generic] joseph-prince-live-the-let-go-life: Downloading webpage
[generic] joseph-prince-live-the-let-go-life: Extracting information
ERROR: Unsupported URL: https://watch.tbn.tv/joseph-prince-live-the-let-go-life/videos/joseph-prince-live-the-let-go-life
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 3320, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://watch.tbn.tv/joseph-prince-live-the-let-go-life/videos/joseph-prince-live-the-let-go-life
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://watch.tbn.tv/joseph-prince-live-the-let-go-life/videos/joseph-prince-live-the-let-go-life
- Playlist: https://watch.tbn.tv/joseph-prince-live-the-let-go-life
---

### Description of your *issue*, suggested solution and other information

https://watch.tbn.tv/ provides free videos given you create a free account with a name + an email + a password.

Videos are available as 360p, 540p and 720p.

**Comment by sebma** [comment]
Hi, watch.tbn.tv has become watch.tbn.org which is the new CN of their ssl/tls certificate.

With a more upto date version of `youtube-dl`, the output would become : 

```python
$ youtube-dl -v --ignore-config -F --username my_email@email_provider.fr https://watch.tbn.org/joseph-prince-live-the-let-go-life/videos/joseph-prince-live-the-let-go-life
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', '-F', '--username', 'PRIVATE', 'https://watch.tbn.tv/joseph-prince-live-the-let-go-life/videos/joseph-prince-live-the-let-go-life']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-74-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] joseph-prince-live-the-let-go-life: Requesting header
[redirect] Following redirect to https://watch.tbn.org/joseph-prince-live-the-let-go-life/videos/joseph-prince-live-the-let-go-life
[generic] joseph-prince-live-the-let-go-life: Requesting header
WARNING: Falling back on generic information extractor.
[generic] joseph-prince-live-the-let-go-life: Downloading webpage
[generic] joseph-prince-live-the-let-go-life: Extracting information
ERROR: Unsupported URL: https://watch.tbn.org/joseph-prince-live-the-let-go-life/videos/joseph-prince-live-the-let-go-life
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/generic.py", line 3520, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://watch.tbn.org/joseph-prince-live-the-let-go-life/videos/joseph-prince-live-the-let-go-life

```
