### ISSUE TITLE
Youtube playlist stopped

### ISSUE THREAD

**Issue by wankio** [ytdl-org/youtube-dl#20623]
https://www.youtube.com/playlist?list=PLb_y3RjS2-KC4tdxgeihcFVc7gKJBd_at

Everytime i'm tried, it always stopped the playlist queue once error appear

```
[youtube] V1VFkR0aU3s: Downloading thumbnail ...
[youtube] V1VFkR0aU3s: Writing thumbnail to: D:\youtube-dl\youtube\green screen effect blue auraa super saiyan.jpg
[download] D:\youtube-dl\youtube\green screen effect blue auraa super saiyan.mp4 has already been downloaded and merged
[download] Downloading video 84 of 160
[youtube] njEcGE6-s0Q: Downloading webpage
[youtube] njEcGE6-s0Q: Downloading video info webpage
ERROR: This video is not available.
Traceback (most recent call last):
  File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\youtube.py", line 1982, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is not available.
```

**Comment by dstftw** [comment]
Stopping on errors by default is expected behavior.

**Comment by s104346** [comment]
@wankio 
```
    -i, --ignore-errors              Continue on download errors, for example to
                                     skip unavailable videos in a playlist
```

**Comment by wankio** [comment]
oh nice thank,
