### ISSUE TITLE
[Crackle] TypeError: exceptions must derive from BaseException

### ISSUE THREAD

**Issue by Coloradohusky** [ytdl-org/youtube-dl#20622]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.07*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
E:\Downloads>youtube-dl -v https://www.sonycrackle.com/watch/172
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.sonycrackle.com/watch/172']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.04.07
[debug] Python version 3.7.3 (CPython) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1
[debug] Proxy map: {}
[Crackle] 172: Downloading media JSON as US
[Crackle] 172: Downloading media JSON as AU
[Crackle] 172: Downloading media JSON as CA
[Crackle] 172: Downloading media JSON as AS
[Crackle] 172: Downloading media JSON as FM
[Crackle] 172: Downloading media JSON as GU
[Crackle] 172: Downloading media JSON as MP
[Crackle] 172: Downloading media JSON as PR
[Crackle] 172: Downloading media JSON as PW
[Crackle] 172: Downloading media JSON as MH
[Crackle] 172: Downloading media JSON as VI
Traceback (most recent call last):
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\my_name\AppData\Local\Programs\Python\Python37-32\Scripts\youtube-dl.exe\__main__.py", line 9, in <module>
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\__init__.py", line 474, in main
    _real_main(argv)
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2008, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\extractor\common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\extractor\crackle.py", line 200, in _real_extract
    raise last_e
TypeError: exceptions must derive from BaseException
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Trying to download Groundhog Day from [sonycrackle.com](sonycrackle.com). Am using Windows 10 Education Edition, with Python 3.7.3. Replaced all instances of my name with _my_name_.

**Comment by kaovilai** [comment]
bump
```
youtube-dl.exe https://www.crackle.com/watch/3543
[Crackle] 3543: Downloading media JSON as US
[Crackle] 3543: Downloading media JSON as AU
[Crackle] 3543: Downloading media JSON as CA
[Crackle] 3543: Downloading media JSON as AS
[Crackle] 3543: Downloading media JSON as FM
[Crackle] 3543: Downloading media JSON as GU
[Crackle] 3543: Downloading media JSON as MP
[Crackle] 3543: Downloading media JSON as PR
[Crackle] 3543: Downloading media JSON as PW
[Crackle] 3543: Downloading media JSON as MH
[Crackle] 3543: Downloading media JSON as VI
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", li
ne 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", li
ne 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ComputerName\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-pack
ages\Python37\Scripts\youtube-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\ComputerName\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-pack
ages\Python37\site-packages\youtube_dl\__init__.py", line 474, in main
    _real_main(argv)
  File "C:\Users\ComputerName\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-pack
ages\Python37\site-packages\youtube_dl\__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "C:\Users\ComputerName\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-pack
ages\Python37\site-packages\youtube_dl\YoutubeDL.py", line 2018, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "C:\Users\ComputerName\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-pack
ages\Python37\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\ComputerName\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-pack
ages\Python37\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\ComputerName\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-pack
ages\Python37\site-packages\youtube_dl\extractor\crackle.py", line 200, in _real_extract
    raise last_e
TypeError: exceptions must derive from BaseException
```

**Comment by nl255** [comment]
I am pretty sure this is a duplicate of issue #11775 .  The workaround is to use something like mitmproxy to get the right URL (which should contain "Service.svc/details/media" to pass to youtube-dl.  As this issue has been in place since 2017 I don't expect that it will be fixed anytime soon.

**Comment by kaovilai** [comment]
@nl555 The error traces are very different. And url structure different. I am not in a georestricted zone. I doubt it's a duplicate issue.

**Comment by nl255** [comment]
@kaovilai I wouldn't be so sure of that.  I get the same error with movies and the solution is the same, use mitmproxy to sniff the connection and get the correct URL to put in.  And it is definitely not a georestriction issue since it works just fine in the browser.

**Comment by mdajr** [comment]
Just ran into this as well.
