### ISSUE TITLE
ITV Hub downloads not working

### ISSUE THREAD

**Issue by ggdagg** [ytdl-org/youtube-dl#20664]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.07*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$./youtube-dl --verbose https://www.itv.com/hub/britains-got-talent/1a7470a0151
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.itv.com/hub/britains-got-talent/1a7470a0151']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.07
[debug] Python version 2.7.15 (CPython) - Linux-5.0.6-200.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
[debug] exe versions: ffmpeg 4.0.4, ffprobe 4.0.4, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 25.155.136.38 (GB) as X-Forwarded-For.
[ITV] 1a7470a0151: Downloading webpage
[ITV] 1a7470a0151: Downloading XML
WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out
[ITV] 1a7470a0151: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/itv.py", line 260, in _real_extract
    self._sort_formats(formats)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1326, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

<end of log>
```

---
---

### Description of your *issue*, suggested solution and other information

I used to download videos on itv hub, but it looks like it's not possible any more. I tried with the show (https://www.itv.com/hub/britains-got-talent/1a7470a0151) and others, but ended up with the same result.
Might be related to https://github.com/ytdl-org/youtube-dl/issues/20617

Thanks.

**Comment by ggdagg** [comment]
After further inspection it seems that there is nothing wrong with youtube-dl, but instead it looks like the VPN I use doesn't cover me properly, hence an error when I use youtube-dl since the website blocks me.
Sorry for the misleading issue.
