### ISSUE TITLE
popcornflix.com support

### ISSUE THREAD

**Issue by Diegus83** [ytdl-org/youtube-dl#20697]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.17*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.17**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

I found some closed issues that  suggest this site was supported before but now it returns an Unsupported URL message.

Maybe there is a reason why this site was dropped but I could not find it in the issues tracker. Thanks!

**Example URL**
https://www.popcornflix.com/watch/channel/comedy/movie/18-fa72dc53-875d-4517-b8a4-2cb58392e362-torrente-2-mission-in-marbella

**Verbose command output**
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.popcornflix.com/watch/channel/comedy/movie/18-fa72dc53-875d-4517-b8a4-2cb58392e362-torrente-2-mission-in-marbella']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.17
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 18-fa72dc53-875d-4517-b8a4-2cb58392e362-torrente-2-mission-in-marbella: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 18-fa72dc53-875d-4517-b8a4-2cb58392e362-torrente-2-mission-in-marbella: Downloading webpage
[generic] 18-fa72dc53-875d-4517-b8a4-2cb58392e362-torrente-2-mission-in-marbella: Extracting information
ERROR: Unsupported URL: https://www.popcornflix.com/watch/channel/comedy/movie/18-fa72dc53-875d-4517-b8a4-2cb58392e362-torrente-2-mission-in-marbella
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2337, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 149, column 96
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3320, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.popcornflix.com/watch/channel/comedy/movie/18-fa72dc53-875d-4517-b8a4-2cb58392e362-torrente-2-mission-in-marbella

**Comment by ealgase** [comment]
Just because you left out the "Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights." from your site support request doesn't mean that we'll ignore it.  This is a piracy site.

**Comment by Diegus83** [comment]
There seems to be some confusion. As far as I know the site is legal. They are on the Apple App Store and AppleTV. 

Sorry if I got it wrong but I don’t think so.

**Comment by ealgase** [comment]
Nah, you didn't, the site looks sketchy but on further inspection is legitimate.
