### ISSUE TITLE
udemy.com - Can't Find Course ID

### ISSUE THREAD

**Issue by kyleinprogress** [ytdl-org/youtube-dl#20718]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.17*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.17**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
When I try and download a course purchased on udemy.com, I get an error saying "unable to extract course ID". This was previously reported in [Bug 20491](https://github.com/ytdl-org/youtube-dl/issues/20491), but that was closed as not able to reproduce. I'm able to reproduce the issue every time.

```
$ youtube-dl --verbose -u <EMAIL> -p <PASSWORD> https://www.udemy.com/django-python-advanced
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.udemy.com/django-python-advanced']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.17
[debug] Python version 2.7.10 (CPython) - Darwin-18.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in
[udemy:course] django-python-advanced: Downloading webpage
[udemy:course] 2045310: Downloading course curriculum
[download] Downloading playlist: 2045310
[udemy:course] playlist 2045310: Collected 72 video ids (downloading 72 of them)
[download] Downloading video 1 of 72
[udemy] Downloading login popup
[udemy] 12896152: Downloading webpage
ERROR: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/udemy.py", line 216, in _real_extract
    course_id, _ = self._extract_course_info(webpage, lecture_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/udemy.py", line 79, in _extract_course_info
    r'data-course-id=["\'](\d+)', webpage, 'course id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

I created a new generic user that can be used to test with that is also causing the same issue.
Username: rehi@max-mail.info
Password: SuperStrongPassword
Course: https://www.udemy.com/vuejs-fast-crash-course/

```
$ youtube-dl --verbose -u rehi@max-mail.info -p SuperStrongPassword https://www.udemy.com/vuejs-fast-crash-course/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.udemy.com/vuejs-fast-crash-course/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.17
[debug] Python version 2.7.10 (CPython) - Darwin-18.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in
[udemy:course] vuejs-fast-crash-course: Downloading webpage
[udemy:course] 533430: Downloading course curriculum
[download] Downloading playlist: 533430
[udemy:course] playlist 533430: Collected 27 video ids (downloading 27 of them)
[download] Downloading video 1 of 27
[udemy] Downloading login popup
[udemy] 3355430: Downloading webpage
ERROR: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/udemy.py", line 216, in _real_extract
    course_id, _ = self._extract_course_info(webpage, lecture_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/udemy.py", line 79, in _extract_course_info
    r'data-course-id=["\'](\d+)', webpage, 'course id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by rcdonaldson** [comment]
Having same issue. Did you find a solution?

**Comment by kyleinprogress** [comment]
I did not, but it looks like a fix was put in place here:

https://github.com/ytdl-org/youtube-dl/commit/5de538787df3f13476489b4a7dfae442c046fab7

Hopefully it’ll be fixed in the next release.
