### ISSUE TITLE
udemy: youtube_dl.utils.RegexNotFoundError: Unable to extract course id

### ISSUE THREAD

**Issue by rajkarthik92** [ytdl-org/youtube-dl#20751]
I'm using "2019.04.17" version. Using this version I'm unable to download videos from UDEMY site. 
Below is the cmd & detailed log:

>youtube-dl -u *** -p *** -o '~/MyVideos/' -v https://www.udemy.com/java-tutorial/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-o', "'~/MyVideos/'", '-v', 'https://www.udemy.com/java-tutorial/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.04.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in
[udemy:course] java-tutorial: Downloading webpage
[udemy:course] 24823: Downloading course curriculum
[download] Downloading playlist: 24823
[udemy:course] playlist 24823: Collected 70 video ids (downloading 70 of them)
[download] Downloading video 1 of 70
[udemy] Downloading login popup
[udemy] 172757: Downloading webpage
ERROR: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\udemy.py", line 216, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\udemy.py", line 79, in _extract_course_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\common.py", line 1004, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by rajkarthik92** [comment]
@dstftw Can you link the original ticket for a follow-up purpose?

**Comment by rajkarthik92** [comment]
> @dstftw Can you link the original ticket for a follow-up purpose?

https://github.com/ytdl-org/youtube-dl/pull/20543
