### ISSUE TITLE
novaplus.cz - no video formats found

### ISSUE THREAD

**Issue by drubezarnakreveta** [ytdl-org/youtube-dl#20796]
Hello,

download video from novaplus.cz doesn't working.

C:\PORTABLE\youtube-dl>youtube-dl.exe --verbose https://novaplus.nova.cz/porad/kobra-11/epizoda/15098-loupezivy-rytir
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://novaplus.nova.cz/porad/kobra-11/epizoda/15098-loupezivy-rytir']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2019.04.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-93548-g4d2f62150d, ffprobe N-93548-g4d2f62150d
[debug] Proxy map: {}
[Nova] 15098-loupezivy-rytir: Downloading webpage
[NovaEmbed] 5bU0VjtuvLh: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\extractor\nova.py", line 66, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\extractor\common.py", line 1326, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thanks for update

**Comment by DonPhillip** [comment]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--add-metadata', '-x', '--no-continue', '--prefer-ffmpeg', '--extract-audio', '--write-thumbnail', '--embed-thumbnail', '-v', '--audio-format', 'mp3', '--output', 'audio.%%(ext)s', 'https://www.youtube.com/watch?v=v9v_GlPx86c']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.18
[debug] Python version 3.7.2 (CPython) - Linux-4.9.0-8-amd64-x86_64-with-arch
[debug] exe versions: ffmpeg 4.1.2, ffprobe 4.1.2
[debug] Proxy map: {}
[youtube] v9v_GlPx86c: Downloading webpage
[youtube] v9v_GlPx86c: Downloading video info webpage
ERROR: v9v_GlPx86c: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1693, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: v9v_GlPx86c: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

(<type 'exceptions.IOError'>, IOError('file not found: audio.mp3',), <traceback object at 0x7f1183a13488>)
