### ISSUE TITLE
YouTube said: This video is unavailable

### ISSUE THREAD

**Issue by quachduyy** [ytdl-org/youtube-dl#20804]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.24**

- [ x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

- [x ] Bug report (encountered problems with youtube-dl)

---

```
youtube-dl -v https://www.youtube.com/watch?v=taD9hqwCb1o
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=taD9hqwCb1o']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.24
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-1027-gcp-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0
[debug] Proxy map: {}
[youtube] taD9hqwCb1o: Downloading webpage
[youtube] taD9hqwCb1o: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 503: Service Unavailable
WARNING: unable to download video info webpage: HTTP Error 503: Service Unavailable
WARNING: unable to download video info webpage: HTTP Error 503: Service Unavailable
WARNING: unable to download video info webpage: HTTP Error 503: Service Unavailable
WARNING: unable to download video info webpage: HTTP Error 503: Service Unavailable
ERROR: taD9hqwCb1o: YouTube said: This video is unavailable.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1681, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: taD9hqwCb1o: YouTube said: This video is unavailable.
```

---

After upgrade *youtube-dl* to latest version *2019.04.24*. I cannot download any live video, ex: ```https://www.youtube.com/watch?v=taD9hqwCb1o```
It's work well for me before I'd upgrade to the latest version released from *2019.03.18*.  Could you give me some information, thank you.

**Comment by justtryinghelp** [comment]
I recently have encountered an error while  using it too

> ERROR: BQfKhwmlSVM: "token" parameter not in video info for unknown reason; please report this 
> issue on https://yt-dl.org/bug. Make sure you are using the latest version

I am also using version 2019.04.24

**Comment by dstftw** [comment]
```
PS C:\Dev\youtube-dl\master> py -2.7 .\youtube_dl\__main__.py https://www.youtube.com/watch?v=taD9hqwCb1o
[youtube] taD9hqwCb1o: Downloading webpage
[youtube] taD9hqwCb1o: Downloading video info webpage
[youtube] taD9hqwCb1o: Downloading m3u8 information
[youtube] taD9hqwCb1o: Downloading MPD manifest
[download] Destination: The Good Life Radio x Sensual Musique • 24_7 Live Radio _ Deep & Tropical House, Chill & Dance Music-taD9hqwCb1o.mp4
ffmpeg version N-85653-gb4330a0 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 61.100 / 55. 61.100
  libavcodec     57. 93.100 / 57. 93.100
  libavformat    57. 72.101 / 57. 72.101
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6. 87.100 /  6. 87.100
  libswscale      4.  7.101 /  4.  7.101
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Input #0, hls,applehttp, from '...':
  Duration: N/A, start: 53627.981467, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn, 60 tbc
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:The Good Life Radio x Sensual Musique┬атАв┬а24_7 Live Radio _ Deep & Tropical House, Chill & Dance Music-taD9hqwCb1o.mp4.part':
  Metadata:
    encoder         : Lavf57.72.101
    Stream #0:0: Video: h264 (High) ([33][0][0][0] / 0x0021), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 30 fps, 30 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
...
```
