### ISSUE TITLE
Download Status Error

### ISSUE THREAD

**Issue by MichioY** [ytdl-org/youtube-dl#20822]
[04/25/19 19:24:29] ERROR: p-vi1JiGmek: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[04/25/19 19:26:23] [debug] System config: []
[04/25/19 19:26:23] [debug] User config: []
[04/25/19 19:26:23] [debug] Custom config: []
[04/25/19 19:26:23] [debug] Command-line args: ['--newline', '-i', '-o', 'G:\\Downloads File\\Youtube\\2019.4.25\\%(title)s.%(ext)s', '-f', 'mp4', '-v', '--ignore-config', '--hls-prefer-native', '--add-metadata', 'https://www.youtube.com/watch?v=p-vi1JiGmek']
[04/25/19 19:26:23] [debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[04/25/19 19:26:23] [debug] youtube-dl version 2019.02.18
[04/25/19 19:26:23] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[04/25/19 19:26:23] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[04/25/19 19:26:23] [debug] Proxy map: {}
[04/25/19 19:26:23] ERROR: p-vi1JiGmek: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[04/25/19 19:26:23] Traceback (most recent call last):
[04/25/19 19:26:23]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
[04/25/19 19:26:23]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\extractor\common.py", line 508, in extract
[04/25/19 19:26:23]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\extractor\youtube.py", line 1689, in _real_extract
[04/25/19 19:26:23] youtube_dl.utils.ExtractorError: p-vi1JiGmek: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[04/25/19 19:26:23]

**Comment by theworryrock** [comment]
I'm running windows and getting this same error. I updated the exe and still no luck. Any idea how to fix this problem?

**Comment by javinc91** [comment]
same error in windows, i have updated version for the exe. any idea?

thanks a lot
