### ISSUE TITLE
NameError: name 'any_printing' is not defined

### ISSUE THREAD

**Issue by Fatalution** [ytdl-org/youtube-dl#20827]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.24*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
2019.04.24
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

The issue lies in full inability to use the program. 
Running ./youtube-dl.exe "https://www.youtube.com/watch?v=EuFfmnu34rs" results in the following error:
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\hackspanner\Documents\Projects\VRChat\youtube-dl\youtube_dl\__init__.py", line 485, in main
  File "C:\Users\hackspanner\Documents\Projects\VRChat\youtube-dl\youtube_dl\__init__.py", line 335, in _real_main
NameError: name 'any_printing' is not defined

**Comment by Fatalution** [comment]
Ahem, I've done everything that was asked from me in this guide, why is this issue closed?
