### ISSUE TITLE
youtube-dl doesn't download links

### ISSUE THREAD

**Issue by IoanPaleru** [ytdl-org/youtube-dl#20832]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.24**
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
- [x] Checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [x] Question

```
C:\Users\Computer User\Music\youtube-dl and libav 11.3 files cache and downloads>youtube-dl -v --ignore-errors --format "best[ext=mp4][height<=720]" -o %(title)s.%(ext)s --cache-dir "C:\Users\Computer User\Music\youtube-dl and libav 11.3 files cache and downloads" --batch-file Files.txt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-errors', '--format', 'best[ext=mp4][height<=720]', '-o', '%(title)s.%(ext)s', '--cache-dir', 'C:\\Users\\Computer User\\Music\\youtube-dl and libav 11.3 files cache and downloads', '--batch-file', 'Files.txt']
[debug] Batch file urls: ['https://www.youtube.com/watch?v=ezopeXwUukQ', 'https://www.youtube.com/watch?v=1WjxBLgsQy8', 'https://www.youtube.com/watch?v=0DdPkt2QOKk']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.12.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: avconv 11.3, avprobe 11.3, ffmpeg N-83657-g7e4f32f, ffprobe N-83657-g7e4f32f
[debug] Proxy map: {}
[youtube] ezopeXwUukQ: Downloading webpage
[youtube] ezopeXwUukQ: Downloading video info webpage
ERROR: ezopeXwUukQ: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\extractor\youtube.py", line 1670, in _real_extract
youtube_dl.utils.ExtractorError: ezopeXwUukQ: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[youtube] 1WjxBLgsQy8: Downloading webpage
[youtube] 1WjxBLgsQy8: Downloading video info webpage
ERROR: 1WjxBLgsQy8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\extractor\youtube.py", line 1670, in _real_extract
youtube_dl.utils.ExtractorError: 1WjxBLgsQy8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[youtube] 0DdPkt2QOKk: Downloading webpage
[youtube] 0DdPkt2QOKk: Downloading video info webpage
ERROR: 0DdPkt2QOKk: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\extractor\youtube.py", line 1670, in _real_extract
youtube_dl.utils.ExtractorError: 0DdPkt2QOKk: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output
```

Hi. When trying to download some links, youtube-dl doesn't download them. Is there any way to fix that? Thanks.

**Comment by IoanPaleru** [comment]
Yes, after updating youtube-dl (https://github.com/ytdl-org/youtube-dl/issues/20831) it downloads the files, but it doesn't download them in 720p or the next highest quality available using this command: "--ignore-errors --format "best[ext=mp4][height<=720]" -o %(title)s.%(ext)s --cache-dir "C:\Users\Computer User\Music\youtube-dl and libav 11.3 files cache and downloads" --batch-file Files.txt", it downloads them in 540x360 and 480x320 instead of the available 720x480 dash formats. Is there a way to fix that? Thanks.

**Comment by IoanPaleru** [comment]
Hi, is there a way to merge all of these similar service requests: "https://github.com/ytdl-org/youtube-dl/issues/20831", "https://github.com/ytdl-org/youtube-dl/issues/20832", "https://github.com/ytdl-org/youtube-dl/issues/20887", and "https://github.com/ytdl-org/youtube-dl/issues/20888" into one service request? Thanks.

Hi. You provided me with the "--format "best[ext=mp4][height<=720]" command to use to download and convert files as 720p mp4 a while ago when I wanted help with that, because I didn't know which command to use. Everything was working fine and youtube-dl was able to download videos properly and convert them in that format until recently. Can you please tell me what command to use for youtube-dl to download videos in 720p (in this case, in the available 720x480 resolution), and mux the available streams using ffmpeg into an mp4 file? So far, I've only found out how to get youtube-dl to download the videos in the correct 720x480 available resolution, but it saves them as mkv files, and I want to find out how to get it to use ffmpeg to convert them to mp4 files. I'd really appreciate it, since the faq is very confusting for average computer users. Youtube-dl is a very good program by the way, once people know how to use it. Thank you.
