### ISSUE TITLE
[Corus] Add Séries+

### ISSUE THREAD

**Issue by Europe12** [ytdl-org/youtube-dl#20861]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.04.24**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Possible to add support to the site serieplus.com group of Corus.

https://www.seriesplus.com/videos/

Thank.

```youtube-dl https://www.seriesplus.com/emissions/soupon-de-magie/videos/la-robe-idale/1490021955940/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.seriesplus.com/emissions/soupon-de-magie/videos/la-robe-idale/1490021955940/', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.04.24
[debug] Python version 3.7.3 (CPython) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg N-93678-g4b7166c9d5, ffprobe N-93678-g4b7166c9d5
[debug] Proxy map: {}
[generic] 1490021955940: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1490021955940: Downloading webpage
[generic] 1490021955940: Extracting information
ERROR: Unsupported URL: https://www.seriesplus.com/emissions/soupon-de-magie/videos/la-robe-idale/1490021955940/
Traceback (most recent call last):
  File "c:\users\barat\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\barat\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "c:\users\barat\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\generic.py", line 3320, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.seriesplus.com/emissions/soupon-de-magie/videos/la-robe-idale/1490021955940/```

**Comment by wolfy1339** [comment]
This one is pretty easy to do once #22075 is resolved
