### ISSUE TITLE
[youtube] ERROR: Did not get any data blocks (Got server HTTP error: Downloaded 359704 bytes, expected 112805186 bytes)

### ISSUE THREAD

**Issue by millivanilla** [ytdl-org/youtube-dl#20901]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.04.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=qL5ut8o5pfs']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.24
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-101-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] qL5ut8o5pfs: Downloading webpage
[youtube] qL5ut8o5pfs: Downloading video info webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r2---sn-vgqs7nlk.googlevideo.com/videoplayback?id=o-APxk4_6NHUkD8eMpq4mBGTSB-1SRXJQLDbtmWNCd8lBO&itag=22&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-vgqs7nlk%2Csn-ab5szn7s&ms=au%2Conr&mv=m&pl=15&ei=M0_HXMvKEqfUjAS3lIWwBg&initcwndbps=1951250&mime=video%2Fmp4&ratebypass=yes&dur=738.928&lmt=1554589806345508&mt=1556565700&fvip=2&c=WEB&txp=4532432&ip=73.50.161.196&ipbits=0&expire=1556587411&sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cinitcwndbps%2Cmime%2Cratebypass%2Cdur%2Clmt&signature=A6026F504039CB684F5F68340CA24687508CDC50.EE24BEA47442D1C916CF26C8077EA41E9BE17E65&key=yt8'
[download] Destination: How the 60-Year-Old IRS Computer System Failed on Tax Day-qL5ut8o5pfs.mp4
[download]   0.3% of 107.58MiB at  1.78MiB/s ETA 01:00[download] Got server HTTP error: Downloaded 359704 bytes, expected 112805186 bytes. Retrying (attempt 1 of 10)...


ERROR: Did not get any data blocks
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 342, in real_download
    return download()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 320, in download
    retry(err)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 225, in retry
    raise RetryDownload(e)
RetryDownload
```

## Description

This specific video (but not others from youtube) always gives error "ERROR: Did not get any data blocks"

**Comment by millivanilla** [comment]
Always stops at the same byte mark. Works fine in web browser.

**Comment by dstftw** [comment]
Server side youtube failure. Select another format.

**Comment by millivanilla** [comment]
How is this a server side issue if it works fine in firefox, chrome etc?

**Comment by dstftw** [comment]
Browser does not use format you request.

**Comment by millivanilla** [comment]
>Browser does not use format you request.


But I did not request any specific format, 

Youtube-dl should recognize this error and pick a format that will work

**Comment by dstftw** [comment]
It can't cause it impossible to know that beforehand.
