### ISSUE TITLE
[toutv] Gets a 400: Bad request on login

### ISSUE THREAD

**Issue by alexhuot1** [ytdl-org/youtube-dl#20913]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.04.30**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://ici.tou.tv/les-chefs/S09E05', u'-o', u'/Volumes/Fichiers/Series/Les chefs/Season 9/S09E05.mp4', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-92154-g7a6d88ee62-tessus, ffprobe N-92219-g9e21ba3dc3-tessus, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 99.254.93.186 (CA) as X-Forwarded-For.
[tou.tv] Logging in
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 626, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

```

## Description

When trying to log, i get a 400: Bad request. I have no idea what's causing the problem yet, the extractor has changed a lot since the last time I looked at it.
I can proving a username / password if needed.

**Comment by aulismedia** [comment]
All tou.tv is affected, looks like they changed logistics of stream output. https://ici.tou.tv/les-chefs/S09E05 does not require a login, you just need to have a Canadian IP. But you can use any other non-restricted program like https://ici.tou.tv/l-epicerie/S17E31.

**Comment by aulismedia** [comment]
tou.tv changed output to FairPlay, apple streamingkeydelivery protected stream. I'm not sure if youtube-dl can handle such streams, can anyone help understand the options in this case?

**Comment by Jncsilver** [comment]
Same thing... login won't work anymore

**Comment by cfreds** [comment]
Same problem :(

**Comment by hub2git** [comment]
Me too. I'm getting this error since 4 days ago.

```
youtube-dl -v https://www.youtube.com/playlist?list=WL 
[debug] System config: [u'--netrc', u'--mark-watched', u'--yes-playlist', u'-f', u'bestvideo[height<=?1080]+bestaudio/best', u'-o', u'~//Downloads/youtube-dl/%(title)s.%(ext)s']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/playlist?list=WL']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-51-generic-x86_64-with-LinuxMint-19.1-tessa
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[youtube:watchlater] Downloading login page
[youtube:watchlater] Looking up account info
[youtube:watchlater] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube:watchlater] WL: Downloading webpage
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 3081, in _real_extract
    _, playlist = self._extract_playlist('WL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2593, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist does not exist.

```


```
~ $ youtube-dl -v https://www.youtube.com/watch?v=Zi4LMpSDccc
[debug] System config: [u'--netrc', u'--mark-watched', u'--yes-playlist', u'-f', u'bestvideo[height<=?1080]+bestaudio/best', u'-o', u'~//Downloads/youtube-dl/%(title)s.%(ext)s']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=Zi4LMpSDccc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-51-generic-x86_64-with-LinuxMint-19.1-tessa
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube] Zi4LMpSDccc: Downloading webpage
[youtube] Zi4LMpSDccc: Downloading video info webpage
[youtube] Zi4LMpSDccc: Marking watched
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r2---sn-2aqu-hoald.googlevideo.com/videoplayback?expire=1560622379&ei=yuAEXbe9PIPA4wLH_IVo&ip=122.53.214.113&id=o-AEypJC6SgOY7ITLxjL-kugN2-1CVcty5dkBr4fyJBiFG&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-2aqu-hoald%2Csn-i3b7knld&ms=au%2Crdu&mv=m&pl=23&initcwndbps=382500&mime=video%2Fmp4&gir=yes&clen=24070265&dur=113.029&lmt=1560216176677216&mt=1560600660&fvip=2&keepalive=yes&c=WEB&txp=4535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIhAJJk09ITFE_GGvLYeNo-lxipHemWX8V8snIjZXKcqsyMAiAk7COFfqWkMjnmrtiudGcmjIeChlXedk36kfV6FvIMbg%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgDKHeQK-ejO3_CffIni6XzjpLL_98QVW7z-sDVFUHb5kCICsi40sEDYZN0ghiKsSlrIAAL4I5841AVDcnq-ltvjxL&ratebypass=yes'
[download] Destination: /home/hub2git//Downloads/youtube-dl/Frozen 2 Official Trailer.f137.mp4
[download] 100% of 22.96MiB in 00:09
[debug] Invoking downloader on u'https://r2---sn-2aqu-hoald.googlevideo.com/videoplayback?expire=1560622379&ei=yuAEXbe9PIPA4wLH_IVo&ip=122.53.214.113&id=o-AEypJC6SgOY7ITLxjL-kugN2-1CVcty5dkBr4fyJBiFG&itag=251&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-2aqu-hoald%2Csn-i3b7knld&ms=au%2Crdu&mv=m&pl=23&initcwndbps=382500&mime=audio%2Fwebm&gir=yes&clen=1824183&dur=113.061&lmt=1560217351806735&mt=1560600660&fvip=2&keepalive=yes&c=WEB&txp=3511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRAIgIM2fs1HL7nlKjmTmUoodPvPijDlITVQnvsTLG0pJMiECIFIEJqp9qIHLTinRhxKFn7IDz0BXLzTaQgQWWid8XQe3&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgDKHeQK-ejO3_CffIni6XzjpLL_98QVW7z-sDVFUHb5kCICsi40sEDYZN0ghiKsSlrIAAL4I5841AVDcnq-ltvjxL&ratebypass=yes'
[download] Destination: /home/hub2git//Downloads/youtube-dl/Frozen 2 Official Trailer.f251.webm
[download] 100% of 1.74MiB in 00:00
[ffmpeg] Merging formats into "/home/hub2git//Downloads/youtube-dl/Frozen 2 Official Trailer.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:/home/hub2git//Downloads/youtube-dl/Frozen 2 Official Trailer.f137.mp4' -i 'file:/home/hub2git//Downloads/youtube-dl/Frozen 2 Official Trailer.f251.webm' -c copy -map '0:v:0' -map '1:a:0' 'file:/home/hub2git//Downloads/youtube-dl/Frozen 2 Official Trailer.temp.mkv'
Deleting original file /home/hub2git//Downloads/youtube-dl/Frozen 2 Official Trailer.f137.mp4 (pass -k to keep)
Deleting original file /home/hub2git//Downloads/youtube-dl/Frozen 2 Official Trailer.f251.webm (pass -k to keep)

```
