### ISSUE TITLE
Can't run YouTube-dl from my latest Ubuntu update.  

### ISSUE THREAD

**Issue by CoastalControl** [ytdl-org/youtube-dl#20914]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-145-generic x86_64)

root@Job-Server:/home/job# sudo youtube-dl https://www.youtube.com/watch?v=uob0zr1MPQc -k && sudo youtube-dl https://www.youtube.com/watch?v=jzsJkpQPm1k -k
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 58, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/options.py", line 902, in parseOpts
  File "/usr/local/bin/youtube-dl/youtube_dl/options.py", line 52, in _readOptions
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2662, in compat_shlex_split
  File "/usr/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
root@Job-Server:/home/job# youtube-dl --version
2019.04.30
root@Job-Server:/

Can you tell from this if the update from Ubuntu is causing this error?

Thank you!

**Comment by CoastalControl** [comment]
I'm sorry, I found the issue when I made my change to the download directory in my youtube-dl configuration file.   I am getting old and messing up a lot!

I hope that this is ok......

Thank you to anyone that responded to this bug and again, I'm sorry..  My bad..
