### ISSUE TITLE
Brightcove rmcdecouverte

### ISSUE THREAD

**Issue by coverdu34** [ytdl-org/youtube-dl#20920]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.04.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\wamp64\www\ytdl>youtube-dl -F "http://players.brightcove.net/1969646226001/default_default/index.html?videoId=5500352445001" --verbose flag
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'http://players.brightcove.net/1969646226001/default_default/index.html?videoId=5500352445001', '--verbose', 'flag']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.04.30
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1
[debug] Proxy map: {}
[brightcove:new] 5500352445001: Downloading webpage
[brightcove:new] 5500352445001: Downloading JSON metadata
[brightcove:new] 5500352445001: Downloading m3u8 information
[info] Available formats for 5500352445001:
format code  extension  resolution note
hls-296      mp4        320x180     296k , avc1.66.30, mp4a.40.2
hls-696      mp4        512x288     696k , avc1.77.30, mp4a.40.2
hls-1096     mp4        848x480    1096k , avc1.77.30, mp4a.40.2 (best)
ERROR: 'flag' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:flag" ) to search YouTube
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\extractor\generic.py", line 2227, in _real_extract
youtube_dl.utils.ExtractorError: 'flag' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:flag" ) to search YouTube


C:\wamp64\www\ytdl>youtube-dl -f hls-296 -g "http://players.brightcove.net/1969646226001/default_default/index.html?videoId=5500352445001" --verbose flag
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'hls-296', '-g', 'http://players.brightcove.net/1969646226001/default_default/index.html?videoId=5500352445001', '--verbose', 'flag']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.04.30
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1
[debug] Proxy map: {}
https://nextmediahdslive-lh.akamaihd.net/i/RMCDECOUVERTE_KB@300868/index_200_av-p.m3u8?sd=10&rebase=on&id=AgAlqHtoWN1TZ8Y+yVzZvE6yzp+CuaMMVLaHqh6mlyBGwvcLu4ho2zBxmOU49V4belaYw+tg0c4Iiw%3d%3d&hdntl=exp=1556779078~acl=%2fi%2f*~data=hdntl~hmac=f8343c06c47d396124fe45c9415c4bcbb85168e70995721ba7215eb1efe7e966
ERROR: 'flag' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:flag" ) to search YouTube
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\extractor\generic.py", line 2227, in _real_extract
youtube_dl.utils.ExtractorError: 'flag' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:flag" ) to search YouTube


C:\wamp64\www\ytdl>ffplay -i "https://nextmediahdslive-lh.akamaihd.net/i/RMCDECOUVERTE_KB@300868/index_200_av-p.m3u8?sd=10&rebase=on&id=AgAlqHtoWN1TZ8Y+yVzZvE6yzp+CuaMMVLaHqh6mlyBGwvcLu4ho2zBxmOU49V4belaYw+tg0c4Iiw%3d%3d&hdntl=exp=1556779078~acl=%2fi%2f*~data=hdntl~hmac=f8343c06c47d396124fe45c9415c4bcbb85168e70995721ba7215eb1efe7e966"
ffplay version 4.1.1 Copyright (c) 2003-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20190212
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[https @ 000002ae13249dc0] HTTP error 403 Forbiddenq=    0B f=0/0
https://nextmediahdslive-lh.akamaihd.net/i/RMCDECOUVERTE_KB@300868/index_200_av-p.m3u8?sd=10&rebase=on&id=AgAlqHtoWN1TZ8Y+yVzZvE6yzp+CuaMMVLaHqh6mlyBGwvcLu4ho2zBxmOU49V4belaYw+tg0c4Iiw%3d%3d&hdntl=exp=1556779078~acl=%2fi%2f*~data=hdntl~hmac=f8343c06c47d396124fe45c9415c4bcbb85168e70995721ba7215eb1efe7e966: Server returned 403 Forbidden (access denied)
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0
```

## Description

Thanks @eMPee584, for explain me why my issues has been closed , even on that way https://github.com/ytdl-org/youtube-dl/issues/20894  it returns many errors before be able to get packets, so almost all players would already avoid the task ...

The command seems working but after, all the link are not playeable (only check for live stream) , same from the original website (brightcove) , So the workaround is not anymore working unfortunately , and to be clear my IP adress is in France, so its not a geo-restrictions problem
Thanks for your support

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser

**Comment by eMPee584** [comment]
the word "flag" after --verbose is not meant to be there...
--verbose *is* the flag!
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by coverdu34** [comment]
Thanks all for your help and really sorry for bothering you, just change
the user agent header is enough with Firefox gecko to play the link.

Again sorry and thanks for your great work

Le mer. 1 mai 2019 à 20:50, Marcel Partap <notifications@github.com> a
écrit :
