### ISSUE TITLE
[MPD] No video formats found

### ISSUE THREAD

**Issue by hypothermic** [ytdl-org/youtube-dl#20921]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.04.30**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
raven@WORKSTATION:~/Downloads$ youtube-dl 'https://wp18-vod-nl.horizon.tv/sdash;vxttoken=iFxMd2r6A2C0lMkZzZGFzaCUyRmMwNTg2NTk4LTY5YjAtNDZhZS05YTM1LTE2MzYxOGZlYWM4MyUyRmluZGV4Lm1wZCUyRiUyQSZleHBpcnk9MTU1NjcxMzM2MSZmbj1zaGEyNTYmcmV1c2U9LTEmYy1pcC11bmxvY2tlZD0xJnglM0FndWlkPTM2MDE4Mzg5LTg1NTMtNDJlMS04ZjdhLWZjMjZhZGYwYjBkMiZ4JTNBc3RyZWFtc2Vzc2lvbmlkPWM2NjMzYTYyLWNjMDEtNGExMC04MjIzLWNiNDZjYjQwYzFmOSwzMmYxNjczZGRjOGE5YzA3YTEzNTllY2JhZjAwN2ZmYWJlODg3MGIzM2U1ZWMwZjYzOTk1YjIDy0b4dM03xD5P/c0586598-69b0-46ae-9a35-163618feac83/index.mpd/Manifest?device=Orion-Replay-DASH' --verbose
t[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://wp18-vod-nl.horizon.tv/sdash;vxttoken=iFxMd2r6A2C0lMkZzZGFzaCUyRmMwNTg2NTk4LTY5YjAtNDZhZS05YTM1LTE2MzYxOGZlYWM4MyUyRmluZGV4Lm1wZCUyRiUyQSZleHBpcnk9MTU1NjcxMzM2MSZmbj1zaGEyNTYmcmV1c2U9LTEmYy1pcC11bmxvY2tlZD0xJnglM0FndWlkPTM2MDE4Mzg5LTg1NTMtNDJlMS04ZjdhLWZjMjZhZGYwYjBkMiZ4JTNBc3RyZWFtc2Vzc2lvbmlkPWM2NjMzYTYyLWNjMDEtNGExMC04MjIzLWNiNDZjYjQwYzFmOSwzMmYxNjczZGRjOGE5YzA3YTEzNTllY2JhZjAwN2ZmYWJlODg3MGIzM2U1ZWMwZjYzOTk1YjIDy0b4dM03xD5P/c0586598-69b0-46ae-9a35-163618feac83/index.mpd/Manifest?device=Orion-Replay-DASH', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.13.0-26-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] Manifest?device=Orion-Replay-DASH: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Manifest?device=Orion-Replay-DASH: Downloading webpage
[generic] Manifest?device=Orion-Replay-DASH: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2359, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1326, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

No video formats found when downloading an MPD stream from a manifest.

**Comment by hypothermic** [comment]
Manifest file contents:
```xml


<?xml version="1.0" encoding="UTF-8"?>
<!--Created with VSPP Streamer version 4.3.8.0 build 90834 context 3343012115132514613-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:cenc="urn:mpeg:cenc:2013" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="static" mediaPresentationDuration="PT1H16M58S" maxSegmentDuration="PT2.021S" minBufferTime="PT0S">
   <Period>
      <AdaptationSet id="1" group="1" bitstreamSwitching="true" segmentAlignment="true" contentType="video" mimeType="video/mp4" maxWidth="1280" maxHeight="720" par="16:9" maxFrameRate="25" startWithSAP="1">
         <ContentProtection schemeIdUri="urn:uuid:X" cenc:default_KID="X" />
         <SegmentTemplate timescale="10000000" media="S!d2ERT3Jpb24tUmVwbGF5LURBU0gSAlT-....ARYEnw__/QualityLevels($Bandwidth$)/Fragments(video=$Time$)" initialization="S!d2ERT3Jpb24tUmVwbGF5LURBU0gSAlT-....ARYEnw__/QualityLevels($Bandwidth$)/Fragments(video=Init)">
            <SegmentTimeline>
               <S d="20000000" r="2308" />
            </SegmentTimeline>
         </SegmentTemplate>
         <Representation id="dzFmZgaf" bandwidth="419430" codecs="avc1.4d400d" width="384" height="216" frameRate="25" sar="1:1" />
         <Representation id="dzEzMwuf" bandwidth="734003" codecs="avc1.4d4015" width="512" height="288" frameRate="25" sar="1:1" />
         <Representation id="dzGZmRGf" bandwidth="1153433" codecs="avc1.4d401e" width="704" height="396" frameRate="25" sar="1:1" />
         <Representation id="dzGZmRmf" bandwidth="1677721" codecs="avc1.4d401f" width="1024" height="576" frameRate="25" sar="1:1" />
         <Representation id="dzHMzCyf" bandwidth="2936012" codecs="avc1.4d401f" width="1280" height="720" frameRate="25" sar="1:1" />
      </AdaptationSet>
      <AdaptationSet id="2" group="32" bitstreamSwitching="true" segmentAlignment="true" contentType="video" mimeType="video/mp4" maxWidth="1280" maxHeight="720" par="16:9" maxFrameRate="25" startWithSAP="1" codingDependency="false">
         <ContentProtection schemeIdUri="urn:uuid:X" cenc:default_KID="X" />
         <EssentialProperty schemeIdUri="http://dashif.org/guidelines/trickmode" value="1" />
         <Role schemeIdUri="urn:mpeg:dash:role:2011" value="alternate" />
         <SegmentTemplate timescale="10000000" media="S!d2ERT3Jpb24tUmVwbGF5LURBU0gSAlT-....ARYEnw__/QualityLevels($Bandwidth$)/Fragments(trickmode=$Time$)" initialization="S!d2ERT3Jpb24tUmVwbGF5LURBU0gSAlT-....ARYEnw__/QualityLevels($Bandwidth$)/Fragments(trickmode=Init)">
            <SegmentTimeline>
               <S d="20000000" r="2308" />
            </SegmentTimeline>
         </SegmentTemplate>
         <Representation id="trickmodedzFmZgaf" bandwidth="419430" codecs="avc1.4d400d" width="384" height="216" frameRate="1" sar="1:1" maxPlayoutRate="25" />
         <Representation id="trickmodedzEzMwuf" bandwidth="734003" codecs="avc1.4d4015" width="512" height="288" frameRate="1" sar="1:1" maxPlayoutRate="25" />
         <Representation id="trickmodedzGZmRGf" bandwidth="1153433" codecs="avc1.4d401e" width="704" height="396" frameRate="1" sar="1:1" maxPlayoutRate="25" />
         <Representation id="trickmodedzGZmRmf" bandwidth="1677721" codecs="avc1.4d401f" width="1024" height="576" frameRate="1" sar="1:1" maxPlayoutRate="25" />
         <Representation id="trickmodedzHMzCyf" bandwidth="2936012" codecs="avc1.4d401f" width="1280" height="720" frameRate="1" sar="1:1" maxPlayoutRate="25" />
      </AdaptationSet>
      <AdaptationSet id="3" group="2" bitstreamSwitching="true" segmentAlignment="true" contentType="audio" mimeType="audio/mp4" lang="dut">
         <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2" />
         <ContentProtection schemeIdUri="urn:X" cenc:default_KID="X" />
         <SegmentTemplate timescale="44100" media="S!d2ERT3Jpb24tUmVwbGF5LURBU0gSAlT-....ARYEnw__/QualityLevels($Bandwidth$)/Fragments(audio_482_dut=$Time$)" initialization="S!d2ERT3Jpb24tUmVwbGF5LURBU0gSAlT-....ARYEnw__/QualityLevels($Bandwidth$)/Fragments(audio_482_dut=Init)">
            <SegmentTimeline>
               <S t="948" d="88064" r="5" /><S d="89088" /><S d="88064" r="6" /><S d="89088" /><S d="88064" r="5" /><S d="89088" /><S d="88064" r="6" /><S d="89088" /><S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" r="5" />
               <S d="89088" />
               <S d="88064" r="6" />
               <S d="89088" />
               <S d="88064" />
            </SegmentTimeline>
         </SegmentTemplate>
         <Representation id="dyHiAZ8." bandwidth="96000" codecs="mp4a.40.2" audioSamplingRate="44100" />
      </AdaptationSet>
   </Period>
</MPD>
```
