### ISSUE TITLE
UnicodeDecodeError when loading cookies.sqlite file.

### ISSUE THREAD

**Issue by kruug** [ytdl-org/youtube-dl#20927]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.04.30**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PS E:\Repo> & C:\Users\user\YouTube-DL\youtube-dl.exe -v --cookies "C:\Users\user\AppData\Roaming\Mozilla\Firefox\Profiles\5o0u1rza.default\cookies.sqlite" --mark-watched --skip-download https://www.youtube.com/user/RepoNut
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'C:\\Users\\user\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\5o0u1rza.default\\cookies.sqlite', '--mark-watched', '--skip-download', 'https://www.youtube.com/user/RepoNut']
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\__init__.py", line 441, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\YoutubeDL.py", line 418, in __init__
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\YoutubeDL.py", line 2318, in _setup_opener
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\utils.py", line 1164, in load
  File "C:\Python\Python34\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 7600: character maps to <undefined>
```

## Description

Attempting to mark an entire YouTube channel as "Watched".  Doing so without a cookie file would require me to login and use 2FA for each and every video in the channel.  When I pass the cookie file, I get a UnicodeDecodeError.

Looking into this, it appears that the issue lies with python2.  Moving to python3 should resolve the issue.  Normally, I would just install python3 and be done.  I do have python3.7 installed on this computer, so that means that youtube-dl.exe comes with a static python build included.

**Comment by dstftw** [comment]
Cookies must be in Netscape HTTP cookies format.

**Comment by kruug** [comment]
So most major browsers no longer use the Netscape HTTP cookie format.  How does one convert the cookies file to something youtube-dl can read?  Would be helpful if you actually helped instead of "Closed, not our problem."

**Comment by dstftw** [comment]
[RTFM](https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl).
