### ISSUE TITLE
Error downloading from Fox

### ISSUE THREAD

**Issue by ThomHehl** [ytdl-org/youtube-dl#20925]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2019.04.30**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
thomas@Westeros:~$ /usr/local/bin/youtube-dl -F "https://www.fox.com/watch/c6685553115446adf3870b699d8d7e5f/" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'https://www.fox.com/watch/c6685553115446adf3870b699d8d7e5f/', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 2.7.15+ (CPython) - Linux-4.18.0-18-generic-x86_64-with-Ubuntu-18.10-cosmic
[debug] exe versions: ffmpeg 4.0.2-2, ffprobe 4.0.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[FOX] Downloading JSON metadata
[FOX] c6685553115446adf3870b699d8d7e5f: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2008, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/fox.py", line 96, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/fox.py", line 69, in _call_api
AttributeError: 'HTTPError' object has no attribute 'status'

```

## Description

Trying to download new video. Never had youtube-dl working before, but was recommended for downloading from fox.com.

**Comment by dstftw** [comment]
You must pass authenticated cookies.

**Comment by ThomHehl** [comment]
Hi, thanks for the input.

I have attempted to download the cookies from www.fox.com and passed them in using --cookies my_cookies.txt and this did not seem to work for me.

I have looked for a forum and couldn't find it. It would be helpful if there were a site with pages for each site so we didn't have to bug devs. I would be happy to create one if one doesn't exist and I could get help documenting each of these.

Please advise.
