### ISSUE TITLE
Openload issue / PhantomJS

### ISSUE THREAD

**Issue by msdev20** [ytdl-org/youtube-dl#20938]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.04.30**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--get-filename', u'-o', u'%(title)s', u'https://openload.co/f/Of3tN9ZzslU']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-957.5.1.el7.x86_64-x86_64-with-centos-7.6.1810-Core
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15, phantomjs 2.1.1
[debug] Proxy map: {}
ERROR: Executing JS failed
:; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/openload.py", line 1982, in _real_extract
    webpage, _ = phantom.get(page_url, html=webpage, video_id=video_id, headers=headers)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/openload.py", line 237, in get
    'Executing JS failed\n:' + encodeArgument(err))
ExtractorError: Executing JS failed
:; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

I tried to download OpenLoad video using following command. Its fail due to "ERROR: Executing JS Failed".

`/usr/local/bin/youtube-dl --verbose --get-filename -o "%(title)s" https://openload.co/f/Of3tN9ZzslU`

**Comment by dstftw** [comment]
phantomjs is broken in your setup.
