### ISSUE TITLE
6play live

### ISSUE THREAD

**Issue by annetube** [ytdl-org/youtube-dl#20944]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.04.30**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

root@ubuntu:/home/anne# youtube-dl -j https://www.6play.fr/m6/direct -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-j', u'https://www.6play.fr/m6/direct', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.18.0-17-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: https://www.6play.fr/m6/direct
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2337, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 389, column 6197
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3320, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.6play.fr/m6/direct


```

## Description

The catchup replay videos works but not the live streaming of all channels. The extractor seems not recognise URL. Thanks for all your job

**Comment by annetube** [comment]
Thanks to this code : https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/sixplay.py 
about what i understand (I'm not familliar with python), the  URL https://pc.middleware.6play.fr/6play/v2/platforms/m6group_web/services/6play/live?channel=M6&with=service_display_images,nextdiffusion  where M6 has to be replaced by the channel  desired gives the json with link BUT unfortunately these links seems DRM protected : 

`ffplay -i https://m6.live.6cloud.fr/out/u/m6_sd_fp.m3u8
ffplay version 4.1.1 Copyright (c) 2003-2019 the FFmpeg developers
[hls,applehttp @ 000002af8c8e85c0] Opening 'https://m6.live.6cloud.fr/out/u/m6_sd_fp_1.m3u8?m=1556871867' for reading
[https @ 000002af951aff40] Opening 'https://m6.live.6cloud.fr/out/u/m6_sd_fp_2.m3u8?m=1556871867' for reading
[https @ 000002af951aff40] Opening 'https://m6.live.6cloud.fr/out/u/m6_sd_fp_3.m3u8?m=1556871867' for reading
[https @ 000002af951aff40] Opening 'https://m6.live.6cloud.fr/out/u/m6_sd_fp_4.m3u8?m=1556871867' for reading
[hls,applehttp @ 000002af8c8e85c0] SAMPLE-AES encryption is not supported yet
[hls,applehttp @ 000002af8c8e85c0] Failed to open segment 872951 of playlist 0
[hls,applehttp @ 000002af8c8e85c0] SAMPLE-AES encryption is not supported yet
[hls,applehttp @ 000002af8c8e85c0] Failed to open segment 872952 of playlist 0
[https @ 000002af951aff40] Opening 'https://m6.live.6cloud.fr/out/u/m6_sd_fp_1.m3u8?m=1556871867' for reading
[hls,applehttp @ 000002af8c8e85c0] SAMPLE-AES encryption is not supported yet
[hls,applehttp @ 000002af8c8e85c0] Failed to open segment 872953 of playlist 0
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0`

On the previous code it seems they extract key from API provided in JS page source to be able to send the correct headers (not sure about what I'm saying)

Hope this helps, my level is almost 0 on python so cant do it by myself unfortunately

**Comment by davinkevin** [comment]
Any news on this one?
