### ISSUE TITLE
Ustream 

### ISSUE THREAD

**Issue by takauya** [ytdl-org/youtube-dl#20959]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2019.04.30**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

Could anyone tell what is the problem? 

youtube-dl -v https://www.ustream.tv/embed/23240580?html5ui
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.ustream.tv/embed/23240580?html5ui']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2019.04.30
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-92246-gc2ac3b8e6a, ffprobe N-92246-gc2ac3b8e6a
[debug] Proxy map: {}
[ustream] 23240580: Downloading webpage
ERROR: Unable to extract content video IDs; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\extractor\ustream.py", line 178, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\extractor\common.py", line 1004, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract content video IDs; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by johnofthecross1** [comment]
I've the same issue and here is my verbose log. Thank you team for any insight.

`D:\Downloads>D:\Downloads\cli\youtube-dl.exe --verbose https://www.ustream.tv/embed/20082839
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.ustream.tv/embed/20082839']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[ustream] 20082839: Downloading webpage
ERROR: Unable to extract content video IDs; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\ustream.py", line 178, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract content video IDs; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by Niluge-KiWi** [comment]
It happens for live-only embed streams for which `ustream.vars.uumfOffAirContentVideoIds=[]`.
(url: https://www.ustream.tv/embed/{video_id}?html5ui=1)

I tried skipping the 2 `if m.group('type')` and `'https://api.ustream.tv/videos/%s.json' % video_id` to go directly to `_get_streams` and `_get_stream_info`:
- the first `self._download_json` on `'http://r%d-1-%s-recorded-lp-live.ums.ustream.tv/1/ustream' % (rnd(1e8), video_id)` does work:
`[{'args': [{'host': 'xxxx-lp-live.ums.services.video.ibm.com', 'connectionId': 'xxxxxxxx-xx'}], 'cmd': 'tracking'}]`
- but the second on `'http://%s/1/ustream?connectionId=%s' % (host, connection_id)` fails: `[{"args":[{"code":"INVALID_CONNECTIONID","message":"Invalid connectionId"}],"cmd":"warning"}]`


Anyway, the web page seems to get all its data from a websocket at `wss://rxxx-1-{video_id}-channel-wss-omega.ums.ustream.tv/1/ustream` with all the cdn config host and chunks metadata (among other things, like thumbnails).

**Comment by svz8** [comment]
The problem still remains to be solved. Unable to extract content video IDs from web pages 
https://ustream.tv/channel/24046197
https://ustream.tv/channel/24038333
