### ISSUE TITLE
ERROR: unable to download video data: ('The read operation timed out',)

### ISSUE THREAD

**Issue by flamablecharlie** [ytdl-org/youtube-dl#20979]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.04.30**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
 youtube-dl -v https://vimeo.com/314004205 -o "Hosted - Deadgar's Dark Coffin Classics - %(title)s.%(ext)s"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://vimeo.com/314004205', u'-o', u"Hosted - Deadgar's Dark Coffin Classics - %(title)s.%(ext)s"]
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-47-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[vimeo] 314004205: Downloading webpage
[vimeo] 314004205: Extracting information
[vimeo] 314004205: Downloading webpage
[vimeo] 314004205: Downloading JSON metadata
[vimeo] 314004205: Checking Original video URL
[vimeo] 314004205: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 314004205: Downloading fastly_skyfire m3u8 information
[vimeo] 314004205: Downloading akfire_interconnect_quic MPD information
[vimeo] 314004205: Downloading akfire_interconnect_quic MPD information
[vimeo] 314004205: Downloading fastly_skyfire MPD information
[vimeo] 314004205: Downloading fastly_skyfire MPD information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://skyfire.vimeocdn.com/1557226326-0x1ae9c77133efbf4dd775bd3e42f38a5142d82a70/314004205/sep/video/1211316454,1211316455/master.mpd?base64_init=1'
[dashsegments] Total fragments: 1173
[download] Destination: Hosted - Deadgar's Dark Coffin Classics - The Tingler - 1959.fdash-fastly_skyfire_sep-video-1211316454.mp4
[download] 100% of 660.21MiB in 06:51
[debug] Invoking downloader on u'https://skyfire.vimeocdn.com/1557226326-0x1ae9c77133efbf4dd775bd3e42f38a5142d82a70/314004205/sep/video/1211316454,1211316455/master.mpd?base64_init=1'
[dashsegments] Total fragments: 1173
[download] Destination: Hosted - Deadgar's Dark Coffin Classics - The Tingler - 1959.fdash-fastly_skyfire_sep-audio-1211316454.m4a
[download]   5.7% of ~114.78MiB at  1.29MiB/s ETA 05:17ERROR: unable to download video data: ('The read operation timed out',)
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1909, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1854, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/dash.py", line 48, in real_download
    success, frag_content = self._download_fragment(ctx, fragment_url, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/fragment.py", line 102, in _download_fragment
    'http_headers': headers or info_dict.get('http_headers'),
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 342, in real_download
    return download()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 230, in download
    data_block = ctx.data.read(block_size if not is_test else min(block_size, data_len - byte_counter))
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/httplib.py", line 597, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 772, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 659, in read
    v = self._sslobj.read(len)
SSLError: ('The read operation timed out',)
```

## Description

This just started happening today. Downloading ANY video from Vimeo.com fails with that timeout error, no matter the video length. It fails every time in the same spot, too, during the second set of fragments.

Network tests out solid and clear, and I can download the same videos by hand just fine on my desktop system on the same network Nothing has changed on the system, and everything is up to date.

**Comment by remitamine** [comment]
most likely a network issue on your side, you can choose another format:
```
youtube-dl -v https://vimeo.com/314004205
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vimeo.com/314004205']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 3.7.3 (CPython) - Linux-5.0.13-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 314004205: Downloading webpage
[vimeo] 314004205: Extracting information
[vimeo] 314004205: Downloading webpage
[vimeo] 314004205: Downloading JSON metadata
[vimeo] 314004205: Checking Original video URL
[vimeo] 314004205: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 314004205: Downloading fastly_skyfire m3u8 information
[vimeo] 314004205: Downloading akfire_interconnect_quic MPD information
[vimeo] 314004205: Downloading akfire_interconnect_quic MPD information
[vimeo] 314004205: Downloading fastly_skyfire MPD information
[vimeo] 314004205: Downloading fastly_skyfire MPD information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://skyfire.vimeocdn.com/1557241047-0x468f3f51584db960c887d95eec23a243a01ce404/314004205/sep/video/1211316454,1211316455/master.mpd?base64_init=1'
[dashsegments] Total fragments: 1173
[download] Destination: The Tingler - 1959-314004205.fdash-fastly_skyfire_sep-video-1211316454.mp4
[download] 100% of 660.21MiB in 24:04
[debug] Invoking downloader on 'https://skyfire.vimeocdn.com/1557241047-0x468f3f51584db960c887d95eec23a243a01ce404/314004205/sep/video/1211316454,1211316455/master.mpd?base64_init=1'
[dashsegments] Total fragments: 1173
[download] Destination: The Tingler - 1959-314004205.fdash-fastly_skyfire_sep-audio-1211316454.m4a
[download] 100% of 116.43MiB in 14:58
[ffmpeg] Merging formats into "The Tingler - 1959-314004205.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:The Tingler - 1959-314004205.fdash-fastly_skyfire_sep-video-1211316454.mp4' -i 'file:The Tingler - 1959-314004205.fdash-fastly_skyfire_sep-audio-1211316454.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:The Tingler - 1959-314004205.temp.mp4'
Deleting original file The Tingler - 1959-314004205.fdash-fastly_skyfire_sep-video-1211316454.mp4 (pass -k to keep)
Deleting original file The Tingler - 1959-314004205.fdash-fastly_skyfire_sep-audio-1211316454.m4a (pass -k to keep)
```
