### ISSUE TITLE
Soundcloud embedded hidden playlist 404 error

### ISSUE THREAD

**Issue by Solpo** [ytdl-org/youtube-dl#20976]
I'm Running the latest version 2019.04.30. 

When I'm trying to download the embedded soundcloud playlist from https://www.soundi.fi/jutut/kaannekohta-jolloin-joko-saadaan-tai-menetetaan-ote-elamasta-ennakkokuuntelussa-tahtiportin-abiristeily-albumi/ (direct link to the playlist https://w.soundcloud.com/player/?url=https://api.soundcloud.com/playlists/773458353?secret_token=s-hWZXT ) I get the following output:

```

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ignore-config', u'https://api.soundcloud.com/playlists/773458353?secret_token=s-hWZXT', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 2.7.13 (CPython) - Linux-4.14.102+-armv7l-with-debian-9.9
[debug] exe versions: avconv 4.0.3-Leia-RC5-Kodi, avprobe 4.0.3-Leia-RC5-Kodi, ffmpeg 4.0.3-Leia-RC5-Kodi, ffprobe 4.0.3-Leia-RC5-Kodi, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud:playlist] 773458353: Downloading playlist
[download] Downloading playlist: Tähtiportti - Abiristeily
[soundcloud:playlist] playlist Tähtiportti - Abiristeily: Collected 9 video ids (downloading 9 of them)
[download] Downloading video 1 of 9
[soundcloud] svart-records/abiristeily-i: Downloading webpage
WARNING: Unable to download webpage: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2008, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 807, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1006, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 868, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/soundcloud.py", line 446, in _real_extract
UnboundLocalError: local variable 'info_json_url' referenced before assignment

```

**Comment by Shirkit** [comment]
I'm having the same issue here:

```
C:\Users\SHiRKiT\Downloads>"youtube-dl(1).exe" "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/713024889%3Fsecret_token%3Ds-YkH1J&color=%23ff4d00&auto_play=false&hide_related=false&show_comments=false&show_user=false&show_reposts=false&show_teaser=false" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/713024889%3Fsecret_token%3Ds-YkH1J&color=%23ff4d00&auto_play=false&hide_related=false&show_comments=false&show_user=false&show_reposts=false&show_teaser=false', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[soundcloud:playlist] 713024889: Downloading playlist
[download] Downloading playlist: 12 Rules for Life-Jordan B Peterson
[soundcloud:playlist] playlist 12 Rules for Life-Jordan B Peterson: Collected 15 video ids (downloading 15 of them)
[download] Downloading video 1 of 15
[soundcloud] tokybook/12-rules-for-life-an-12: Downloading webpage
WARNING: Unable to download webpage: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\YoutubeDL.py", line 2008, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\YoutubeDL.py", line 807, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\YoutubeDL.py", line 868, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\YoutubeDL.py", line 807, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\YoutubeDL.py", line 1006, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\YoutubeDL.py", line 868, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\extractor\soundcloud.py", line 446, in _real_extract
UnboundLocalError: local variable 'info_json_url' referenced before assignment```

**Comment by uahim** [comment]
+1

**Comment by toph-allen** [comment]
Same here
