### ISSUE TITLE
Download from YouTube is interrupting

### ISSUE THREAD

**Issue by Jipok** [ytdl-org/youtube-dl#20989]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.04.30**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v "https://www.youtube.com/watch?v=1La4QzGeaaQ"
[debug] System config: []
[debug] User config: [u'-f', u'bestvideo[height<=?1080]+bestaudio/besty']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=1La4QzGeaaQ']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 2.7.16 (CPython) - Linux-4.19.37_1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[youtube] 1La4QzGeaaQ: Downloading webpage
[youtube] 1La4QzGeaaQ: Downloading video info webpage
WARNING: unable to download video info webpage: <urlopen error [Errno -3] Temporary failure in name resolution>
WARNING: unable to download video info webpage: <urlopen error [Errno -3] Temporary failure in name resolution>
WARNING: unable to extract channel id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r6---sn-ug5onuxaxjvh-jx3l.googlevideo.com/videoplayback?id=o-AGJqjrDjQQOuyRRAm2ZTD_0_Cj1rdoLP5itnlKAjoAov&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C272%2C278%2C298%2C299%2C302%2C303%2C308%2C313%2C315%2C330%2C331%2C332%2C333%2C334%2C335%2C336%2C337%2C394%2C395%2C396%2C397%2C398&itag=299&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-ug5onuxaxjvh-jx3l%2Csn-ug5onuxaxjvh-n8v6&ms=au%2Crdu&mv=m&pcm2cms=yes&pl=22&ei=B4XRXOiPIYWW7QTzt7P4DA&initcwndbps=1383750&mime=video%2Fmp4&gir=yes&clen=214332583&dur=337.704&lmt=1556991510694739&mt=1557234877&fvip=6&keepalive=yes&c=WEB&txp=5532232&ip=62.33.68.58&ipbits=0&expire=1557256551&sparams=ip%2Cipbits%2Cexpire%2Cid%2Caitags%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cei%2Cinitcwndbps%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&signature=5AF73B4FEF6E8E8B8E8431F6BA524B3B4D1F0A48.1AEF1F86ED3A15FD983248AC3C8733CF620D00AB&key=yt8&ratebypass=yes'
[download] Destination: Peru 8K HDR 60FPS (FUHD)-1La4QzGeaaQ.f299.mp4
[download]  14.6% of 204.40MiB at  1.13MiB/s ETA 02:34ERROR: unable to download video data: <urlopen error [Errno -3] Temporary failure in name resolution>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1909, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1854, in dl
    return fd.download(name, info)
  File "/usr/lib/python2.7/site-packages/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python2.7/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/lib/python2.7/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/site-packages/youtube_dl/utils.py", line 1140, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

```

## Description

For another video, the download doesn't even start:
```
youtube-dl "https://www.youtube.com/watch?v=H_yATzyi-3g"
[youtube] H_yATzyi-3g: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno -3] Temporary failure in name resolution> (caused by URLError(gaierror(-3, 'Temporary failure in name resolution'),))
```
A week ago, everything worked. Now I can not download any videos from YouTube.

**Comment by dstftw** [comment]
Network issue on your side.
