### ISSUE TITLE
Can't download from Udemy

### ISSUE THREAD

**Issue by Juhdege** [ytdl-org/youtube-dl#20991]
- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2019.04.30**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
Downloads $ youtube-dl -v https://www.udemy.com/bootstrap-komplettkurs/learn/v4/overview
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.udemy.com/bootstrap-komplettkurs/learn/v4/overview']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2019.04.30
[debug] Python version 2.7.16 (CPython) - Darwin-18.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[udemy:course] bootstrap-komplettkurs: Downloading webpage
ERROR: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/udemy.py", line 442, in _real_extract
    course_id, title = self._extract_course_info(webpage, course_path)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/udemy.py", line 82, in _extract_course_info
    ], webpage, 'course id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I'm issuing the following to see my course offline:

```
$ youtube-dl -v https://www.udemy.com/bootstrap-komplettkurs/learn/v4/overview
```

Result is that I receive the shown issue.

**Comment by s-sebastian** [comment]
You have to login first and I would also recommend to enable delay between downloads:
```
youtube-dl -u <an@exmaple.com> --sleep-interval 60 --max-sleep-interval 90 -f 'best' -o '%(playlist)s/%(chapter_number)s-%(chapter)s/%(playlist_index)s.%(title)s.%(ext)s' https://www.udemy.com/bootstrap-komplettkurs/learn/v4/overview```

**Comment by Juhdege** [comment]
Thanks for the hint - but unfortunately, that way I end up with a different error:

```
Udemy_Bootstrap4 $ youtube-dl -v -u XXXXX@gmail.com --sleep-interval 60 --max-sleep-interval 90 -f 'best' -o '%(playlist)s/%(chapter_number)s-%(chapter)s/%(playlist_index)s.%(title)s.%(ext)s' https://www.udemy.com/bootstrap-komplettkurs/learn/v4/overview
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'--sleep-interval', u'60', u'--max-sleep-interval', u'90', u'-f', u'best', u'-o', u'%(playlist)s/%(chapter_number)s-%(chapter)s/%(playlist_index)s.%(title)s.%(ext)s', u'https://www.udemy.com/bootstrap-komplettkurs/learn/v4/overview']
Type account password and press [Return]:
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2019.05.11
[debug] Python version 2.7.16 (CPython) - Darwin-18.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[udemy:course] Downloading login popup
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 626, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by s-sebastian** [comment]
Are you able to access/play this URL in the browser? You can try adding [cookies](https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl) if so.

Anyway this doesn't look like an issue with youtube-dl itself.

**Comment by luisenricke** [comment]
I just saw udemy change its platform.... You have to pass the url like this https://www.udemy.com/bootstrap-komplettkurs and check if you have the last update of youtube-dl

**Comment by Juhdege** [comment]
Hey @luisenricke ,

that did the trick for me! Thanks a lot!

BR

**Comment by luisenricke** [comment]
Your welcome 👍

**Comment by Juhdege** [comment]
Hmm - seems as if it just works for some Udemy courses or sometimes:

I've tried with 4 different courses and have similar issues; the strangest one starts to download but then stops working, apparently:

```
Udemy $ cat dllist.txt
https://www.udemy.com/introdjango
https://www.udemy.com/the-ultimate-beginners-guide-to-django-django-2-python-web-dev-website
https://www.udemy.com/computer-vision-mit-opencv-und-deep-learning
https://www.udemy.com/deep-learning-tensorflow
https://www.udemy.com/python-and-django-full-stack-web-developer-bootcamp

Udemy $ while IFS="" read -r line || [[ -n "$line" ]]; do echo "Processing $line ================"; mkdir $(echo $line | sed 's#https://www.udemy.com/##g'); cd $(echo $line | sed 's#https://www.udemy.com/##g'); youtube-dl -v --sleep-interval 60 --max-sleep-interval 90 -f 'best' -o '%(playlist)s/%(chapter_number)s-%(chapter)s/%(playlist_index)s.%(title)s.%(ext)s' $line; cd ..; echo "Finished processing $line ======="; done < dllist.txt
Processing https://www.udemy.com/introdjango ================
[debug] System config: []
[debug] User config: [u'--netrc']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--sleep-interval', u'60', u'--max-sleep-interval', u'90', u'-f', u'best', u'-o', u'%(playlist)s/%(chapter_number)s-%(chapter)s/%(playlist_index)s.%(title)s.%(ext)s', u'https://www.udemy.com/introdjango']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.7.16 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in
[udemy:course] introdjango: Downloading webpage
[udemy:course] 706204: Downloading course curriculum
[download] Downloading playlist: 706204
[udemy:course] playlist 706204: Collected 13 video ids (downloading 13 of them)
[download] Downloading video 1 of 13
[udemy] Downloading login popup
[udemy] 4252182: Downloading webpage
[udemy] 4252182: Downloading lecture JSON
[udemy] 5083720: Downloading m3u8 information
[debug] Invoking downloader on u'https://h.udemycdn-a.com/706204/5083720/2016-01-20_07-52-45-27b93f93096d48e4353c2921421b257e/hls/hls_1080_4300/dc45680b229b953bf7cac1a1b918f3b8.m3u8'
[download] Sleeping 78.47 seconds...
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 15
[download] Destination: 706204/1-Welcome!/01.About this Course.mp4
[download] 100% of 23.73MiB in 00:06
[debug] ffmpeg command line: ffprobe -show_streams 'file:706204/1-Welcome!/01.About this Course.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "706204/1-Welcome!/01.About this Course.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:706204/1-Welcome!/01.About this Course.mp4' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:706204/1-Welcome!/01.About this Course.temp.mp4'
[download] Downloading video 2 of 13
[udemy] 4231244: Downloading webpage
[udemy] 4231244: Downloading lecture JSON
[udemy] 4919962: Downloading m3u8 information
[debug] Invoking downloader on u'https://h.udemycdn-a.com/706204/4919962/2015-12-29_14-09-29-b0fd356b78d6e20bf474fab7b572084d/hls/hls_1080_4300/493ac3ab074ad22cb26f802acd02ff4b.m3u8'
[download] Sleeping 89.03 seconds...
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 24
[download] Destination: 706204/2-Getting Started/02.Requirements and Downloads.mp4
[download] 100% of 53.12MiB in 00:12
[debug] ffmpeg command line: ffprobe -show_streams 'file:706204/2-Getting Started/02.Requirements and Downloads.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "706204/2-Getting Started/02.Requirements and Downloads.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:706204/2-Getting Started/02.Requirements and Downloads.mp4' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:706204/2-Getting Started/02.Requirements and Downloads.temp.mp4'
[download] Downloading video 3 of 13
[udemy] 4252118: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 626, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

Finished processing https://www.udemy.com/introdjango =======
Processing https://www.udemy.com/the-ultimate-beginners-guide-to-django-django-2-python-web-dev-website ================
[debug] System config: []
[debug] User config: [u'--netrc']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--sleep-interval', u'60', u'--max-sleep-interval', u'90', u'-f', u'best', u'-o', u'%(playlist)s/%(chapter_number)s-%(chapter)s/%(playlist_index)s.%(title)s.%(ext)s', u'https://www.udemy.com/the-ultimate-beginners-guide-to-django-django-2-python-web-dev-website']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.7.16 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[udemy:course] Downloading login popup
ERROR: Unable to download webpage: HTTP Error 403: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 626, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

Finished processing https://www.udemy.com/the-ultimate-beginners-guide-to-django-django-2-python-web-dev-website =======
Processing https://www.udemy.com/computer-vision-mit-opencv-und-deep-learning ================
mkdir: computer-vision-mit-opencv-und-deep-learning: File exists
[debug] System config: []
[debug] User config: [u'--netrc']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--sleep-interval', u'60', u'--max-sleep-interval', u'90', u'-f', u'best', u'-o', u'%(playlist)s/%(chapter_number)s-%(chapter)s/%(playlist_index)s.%(title)s.%(ext)s', u'https://www.udemy.com/computer-vision-mit-opencv-und-deep-learning']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.7.16 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[udemy:course] Downloading login popup
ERROR: Unable to download webpage: HTTP Error 403: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 626, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

Finished processing https://www.udemy.com/computer-vision-mit-opencv-und-deep-learning =======
Processing https://www.udemy.com/deep-learning-tensorflow ================
[debug] System config: []
[debug] User config: [u'--netrc']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--sleep-interval', u'60', u'--max-sleep-interval', u'90', u'-f', u'best', u'-o', u'%(playlist)s/%(chapter_number)s-%(chapter)s/%(playlist_index)s.%(title)s.%(ext)s', u'https://www.udemy.com/deep-learning-tensorflow']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.7.16 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[udemy:course] Downloading login popup
ERROR: Unable to download webpage: HTTP Error 403: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 626, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

Finished processing https://www.udemy.com/deep-learning-tensorflow =======
Processing https://www.udemy.com/python-and-django-full-stack-web-developer-bootcamp ================
[debug] System config: []
[debug] User config: [u'--netrc']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--sleep-interval', u'60', u'--max-sleep-interval', u'90', u'-f', u'best', u'-o', u'%(playlist)s/%(chapter_number)s-%(chapter)s/%(playlist_index)s.%(title)s.%(ext)s', u'https://www.udemy.com/python-and-django-full-stack-web-developer-bootcamp']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.7.16 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[udemy:course] Downloading login popup
ERROR: Unable to download webpage: HTTP Error 403: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 626, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

Finished processing https://www.udemy.com/python-and-django-full-stack-web-developer-bootcamp =======
```

Am I doing something wrong or is this a bug? I mean - youtube-dl's output asks for filing this as a bug `please report this issue on https://yt-dl.org/bug` ... ;)

**Comment by Juhdege** [comment]
... just trying it once more with `--sleep-interval 60 --max-sleep-interval 90` removed and it works ...
Strange.
