### ISSUE TITLE
`--embed-subs` doesn't work with avconv

### ISSUE THREAD

**Issue by jaimeMF** [ytdl-org/youtube-dl#2101]
As reported in Debian: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=721317

```
$ youtube-dl QRS8MkLhQmM --embed-subs --write-sub
[debug] System config: []
[debug] User config: ['--keep-video', '--write-info-json', '--write-thumbnail', '--verbose']
[debug] Command-line args: ['QRS8MkLhQmM', '--embed-subs', '--write-sub']
[debug] Encodings: locale 'UTF-8', fs 'utf-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.01.05.5
[debug] Git HEAD: 1c0f31f
[debug] Python version 3.3.3 - Darwin-13.0.0-x86_64-i386-64bit
[debug] Proxy map: {}
[youtube] Setting language
[youtube] QRS8MkLhQmM: Downloading webpage
[youtube] QRS8MkLhQmM: Downloading video info webpage
[youtube] QRS8MkLhQmM: Extracting video information
[info] Writing video subtitles to: YouTube Captions and Subtitles-QRS8MkLhQmM.en.srt
[info] Writing video description metadata as JSON to: YouTube Captions and Subtitles-QRS8MkLhQmM.info.json
[youtube] QRS8MkLhQmM: Downloading thumbnail ...
[youtube] QRS8MkLhQmM: Writing thumbnail to: YouTube Captions and Subtitles-QRS8MkLhQmM.jpg
[download] YouTube Captions and Subtitles-QRS8MkLhQmM.mp4 has already been downloaded
[ffmpeg] Embedding subtitles in 'YouTube Captions and Subtitles-QRS8MkLhQmM.mp4'
[debug] ffmpeg command line: avconv -y -i 'YouTube Captions and Subtitles-QRS8MkLhQmM.mp4' -i 'YouTube Captions and Subtitles-QRS8MkLhQmM.en.srt' -map 0:0 -map 0:1 -c:v copy -c:a copy -map 1:0 -c:s:0 mov_text -metadata:s:s:0 language=eng -f mp4 'YouTube Captions and Subtitles-QRS8MkLhQmM.mp4.temp'
ERROR: Unknown encoder 'mov_text'
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 982, in post_process
    keep_video_wish, new_info = pp.run(info)
  File "youtube_dl/PostProcessor.py", line 479, in run
    self.run_ffmpeg_multiple_files(input_files, temp_filename, opts)
  File "youtube_dl/PostProcessor.py", line 100, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.PostProcessor.FFmpegPostProcessorError: Unknown encoder 'mov_text'
```

Avconv output

```
$ avconv -y -i 'YouTube Captions and Subtitles-QRS8MkLhQmM.mp4' -i 'YouTube Captions and Subtitles-QRS8MkLhQmM.en.srt' -map 0:0 -map 0:1 -c:v copy -c:a copy -map 1:0 -c:s:0 mov_text -metadata:s:s:0 language=eng -f mp4 'YouTube Captions and Subtitles-QRS8MkLhQmM.mp4.temp'
avconv version 9.10, Copyright (c) 2000-2013 the Libav developers
  built on Jan  2 2014 11:48:46 with Apple LLVM version 5.0 (clang-500.2.79) (based on LLVM 3.3svn)
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'YouTube Captions and Subtitles-QRS8MkLhQmM.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2013-12-06 04:38:41
  Duration: 00:01:36.61, start: 0.000000, bitrate: 473 kb/s
    Stream #0.0(und): Video: h264 (Constrained Baseline), yuv420p, 640x360, 374 kb/s, 29.97 fps, 29.97 tbr, 60k tbn, 59.94 tbc
    Stream #0.1(und): Audio: aac, 44100 Hz, stereo, fltp, 95 kb/s
    Metadata:
      creation_time   : 2013-12-06 04:38:41
[srt @ 0x7f952480b200] Estimating duration from bitrate, this may be inaccurate
Input #1, srt, from 'YouTube Captions and Subtitles-QRS8MkLhQmM.en.srt':
  Duration: N/A, bitrate: N/A
    Stream #1.0: Subtitle: srt
Unknown encoder 'mov_text'
```

**Comment by dirkf** [comment]
Historical _ffmpeg_ issue, I hope.
