### ISSUE TITLE
Everything is going wrong. What could be the issue?

### ISSUE THREAD

**Issue by qbektrix** [ytdl-org/youtube-dl#21013]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2019.04.30**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
**$ youtube-dl -v --verbose https://www.youtube.com/watch?v=kt1-hLsIjqg**
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--verbose', u'https://www.youtube.com/watch?v=kt1-hLsIjqg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.07
[debug] Python version 2.7.10 (CPython) - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[youtube] kt1-hLsIjqg: Downloading webpage
[youtube] kt1-hLsIjqg: Downloading video info webpage
ERROR: kt1-hLsIjqg: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1693, in _real_extract
    video_id=video_id)
ExtractorError: kt1-hLsIjqg: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**$ youtube-dl -U**
ERROR: can't find the current version. Please try again later.

**$ youtube-dl -f --verbose https://www.youtube.com/watch?v=kt1-hLsIjqg**
[youtube] kt1-hLsIjqg: Downloading webpage
[youtube] kt1-hLsIjqg: Downloading video info webpage
ERROR: kt1-hLsIjqg: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I am on OS X 10.11.6 using youtube-dl version 2019.04.07. Nothing is working, I am unable to update. I am very curious to know what is the issue. I used it a week back successfully and I didn't update my OS or any other software. I am curious to know what is causing the issue without any state change to my system.

**Comment by qbektrix** [comment]
What can I do? I am unable to even update the software?

**Comment by dstftw** [comment]
Update python.
