### ISSUE TITLE
Error While Downloading Premium Videos

### ISSUE THREAD

**Issue by RomanScott** [ytdl-org/youtube-dl#21026]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2019.04.30**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 1915, in process_info
  File "youtube_dl/YoutubeDL.py", line 1854, in dl
  File "youtube_dl/downloader/common.py", line 364, in download
  File "youtube_dl/downloader/http.py", line 341, in real_download
  File "youtube_dl/downloader/http.py", line 109, in establish_connection
  File "youtube_dl/YoutubeDL.py", line 2227, in urlopen
  File "urllib/request.py", line 531, in open
  File "urllib/request.py", line 641, in http_response
  File "urllib/request.py", line 569, in error
  File "urllib/request.py", line 503, in _call_chain
  File "urllib/request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "modules/downloaders/youtube.py", line 69, in downloadMedia
  File "youtube_dl/YoutubeDL.py", line 2008, in download
  File "youtube_dl/YoutubeDL.py", line 807, in extract_info
  File "youtube_dl/YoutubeDL.py", line 861, in process_ie_result
  File "youtube_dl/YoutubeDL.py", line 1642, in process_video_result
  File "youtube_dl/YoutubeDL.py", line 1917, in process_info
  File "youtube_dl/YoutubeDL.py", line 624, in report_error
  File "youtube_dl/YoutubeDL.py", line 594, in trouble
youtube_dl.utils.DownloadError: ERROR: unable to download video data: HTTP Error 403: Forbidden
```

## Description

Hello, I am running into a major error while running YouTube-DL. Everytime I try to download a premium video, I get this error. However, normal videos download fine. I am using the --cookies option in YouTube-DL and have signed into my account and have properly formatted the cookies file into a Netscape file format.

What is the issue here?

**Comment by Hrxn** [comment]
Premium videos? Which premium videos? Which site?
Your log does not include any URL whatsoever..
