### ISSUE TITLE
playout.3qsdn.com - No video formats found

### ISSUE THREAD

**Issue by fzuendeth** [ytdl-org/youtube-dl#21058]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.05.11**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --verbose https://playout.3qsdn.com/56d572c6-17e0-11e8-bcfd-0cc47a188158?js=true&container=sdnPlayer_tjRXknPmfNZWhHg&width=459&height=258
[1] 70425
[2] 70426
[3] 70427
[2]-  Done                    container=sdnPlayer_tjRXknPmfNZWhHg
[3]+  Done                    width=459
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://playout.3qsdn.com/56d572c6-17e0-11e8-bcfd-0cc47a188158?js=true']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.11
[debug] Python version 2.7.16 (CPython) - Darwin-18.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.1, ffprobe 4.0.1
[debug] Proxy map: {}
[3qsdn] 56d572c6-17e0-11e8-bcfd-0cc47a188158: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/threeqsdn.py", line 133, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1326, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I'm trying to download the free video (Season 4, Episode 1) from this page:
http://www.3plus.tv/episode/notruf/staffel-4-folge-1

I identified the video url to be:
https://playout.3qsdn.com/56d572c6-17e0-11e8-bcfd-0cc47a188158?js=true&container=sdnPlayer_tjRXknPmfNZWhHg&width=459&height=258
But I get the 'no video formats found' error.

It works fine for older seasons. For example Season 3, Episode 1:
http://www.3plus.tv/episode/notruf/staffel-3-folge-1
and video url:
http://playout.3qsdn.com/1a60d2b4-beb1-11e4-9476-002590c750be?timestamp=0&key=0&js=true&container=sdnPlayer&width=459&height=258&protocol=http&token=0
works fine:
```
youtube-dl --verbose http://playout.3qsdn.com/1a60d2b4-beb1-11e4-9476-002590c750be?timestamp=0&key=0&js=true&container=sdnPlayer&width=459&height=258&protocol=http&token=0
[1] 70455
[2] 70456
[3] 70457
[4] 70458
[5] 70459
[6] 70460
[7] 70461
[2]   Done                    key=0
[3]   Done                    js=true
[4]   Done                    container=sdnPlayer
[5]   Done                    width=459
[6]-  Done                    height=258
[7]+  Done                    protocol=http
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://playout.3qsdn.com/1a60d2b4-beb1-11e4-9476-002590c750be?timestamp=0']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.11
[debug] Python version 2.7.16 (CPython) - Darwin-18.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.1, ffprobe 4.0.1
[debug] Proxy map: {}
[3qsdn] 1a60d2b4-beb1-11e4-9476-002590c750be: Downloading webpage
WARNING: [3qsdn] 1a60d2b4-beb1-11e4-9476-002590c750be: Failed to parse JSON Expecting ',' delimiter: line 1 column 686 (char 685)
[3qsdn] 1a60d2b4-beb1-11e4-9476-002590c750be: Checking video URL
[3qsdn] 1a60d2b4-beb1-11e4-9476-002590c750be: Checking video URL
[3qsdn] 1a60d2b4-beb1-11e4-9476-002590c750be: Checking video URL
[3qsdn] 1a60d2b4-beb1-11e4-9476-002590c750be: Checking video URL
[3qsdn] 1a60d2b4-beb1-11e4-9476-002590c750be: Downloading MPD manifest
[3qsdn] 1a60d2b4-beb1-11e4-9476-002590c750be: Downloading m3u8 information
[3qsdn] 1a60d2b4-beb1-11e4-9476-002590c750be: Downloading f4m manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://sdn-global-streaming-cache.3qsdn.com/stream/2377/files/15/02/289740/2377-rZX4jDMNKy9tVGbJ.ism/manifest.mpd?key=ahv9-GB-nUIu_r0Tt3hQ0w&exp=1557603635&format=dash&mime=mp4&source=html5'
[dashsegments] Total fragments: 2408
[download] Destination: 1a60d2b4-beb1-11e4-9476-002590c750be-1a60d2b4-beb1-11e4-9476-002590c750be.fmpd-video=2520000.mp4
```

**Comment by redstang33** [comment]
This affects me as well with version 2019.10.29. The URL I'm trying to download is https://playout.3qsdn.com/f61c21b3-ee98-11e9-bce2-0cc47a188158 and here's the --verbose output:

`
$ youtube-dl --verbose "https://playout.3qsdn.com/f61c21b3-ee98-11e9-bce2-0cc47a188158"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://playout.3qsdn.com/f61c21b3-ee98-11e9-bce2-0cc47a188158']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.29
[debug] Python version 2.7.17rc1 (CPython) - Linux-5.3.0-19-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2, phantomjs 2.1.1
[debug] Proxy map: {}
[3qsdn] f61c21b3-ee98-11e9-bce2-0cc47a188158: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/xxx/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/xxx/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/xxx/bin/youtube-dl/youtube_dl/extractor/threeqsdn.py", line 133, in _real_extract
    self._sort_formats(formats)
  File "/home/xxx/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by therealmaxmoon** [comment]
I have similar issues with other videos from 3plus.tv, like: http://www.3plus.tv/episode/bauer-ledig-sucht/staffel-15-folge-18 

Any solutions yet?

**Comment by grexe** [comment]
Seems I'm also experiencing this issue while trying to download a live stream from:
https://konzertzuhaus.at/streaming-konzert/martha-argerich-sophie-pacini/

``` 
$ youtube-dl --verbose https://konzertzuhaus.at/streaming-konzert/martha-argerich-sophie-pacini/     
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://konzertzuhaus.at/streaming-konzert/martha-argerich-sophie-pacini/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.9.1 (CPython) - Linux-5.10.2-2-MANJARO-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] martha-argerich-sophie-pacini: Requesting header
WARNING: Falling back on generic information extractor.
[generic] martha-argerich-sophie-pacini: Downloading webpage
[generic] martha-argerich-sophie-pacini: Extracting information
[3qsdn] 6e0e2713-4b02-11eb-b839-0cc47a188158: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/threeqsdn.py", line 133, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1367, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
