### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 19: ordinal not in range(128)

### ISSUE THREAD

**Issue by itskando** [ytdl-org/youtube-dl#21056]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

```
root@plex:~ # python3 /usr/local/bin/youtube-dl "https://vimeo.com/133021237"
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[vimeo] 133021237: Downloading webpage
[vimeo] 133021237: Extracting information
[vimeo] 133021237: Downloading webpage
[vimeo] 133021237: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[vimeo] 133021237: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 133021237: Downloading fastly_skyfire m3u8 information
[vimeo] 133021237: Downloading akfire_interconnect_quic MPD information
[vimeo] 133021237: Downloading akfire_interconnect_quic MPD information
[vimeo] 133021237: Downloading fastly_skyfire MPD information
[vimeo] 133021237: Downloading fastly_skyfire MPD information
[vimeo] 133021237: Downloading thumbnail ...
[vimeo] 133021237: Writing thumbnail to: /media/movies/youtube-dl/WILDFIRE.jpg
[dashsegments] Total fragments: 42
[download] Destination: /media/movies/youtube-dl/WILDFIRE.fdash-fastly_skyfire_sep-video-415408490.mp4
[download] 100% of 98.65MiB in 00:23
[dashsegments] Total fragments: 42
[download] Destination: /media/movies/youtube-dl/WILDFIRE.fdash-fastly_skyfire_sep-audio-415408490.m4a
[download] 100% of 7.50MiB in 00:11
[ffmpeg] Merging formats into "/media/movies/youtube-dl/WILDFIRE.mp4"
Deleting original file /media/movies/youtube-dl/WILDFIRE.fdash-fastly_skyfire_sep-video-415408490.mp4 (pass -k to keep)
Deleting original file /media/movies/youtube-dl/WILDFIRE.fdash-fastly_skyfire_sep-audio-415408490.m4a (pass -k to keep)
[ffmpeg] Adding metadata to '/media/movies/youtube-dl/WILDFIRE.mp4'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2008, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 807, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 861, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1642, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1989, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2054, in post_process
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 498, in run
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 230, in run_ffmpeg_multiple_files
  File "/usr/local/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1295, in _execute_child
    restore_signals, start_new_session, preexec_fn)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 19: ordinal not in range(128)
```
This issue persisted on a variety of videos.
In all cases, the following warning occurred, independent of title, even for titles which I would assume had no special characters of any sort:

```
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
```

Even if `--restrict-filenames` is directly applied, the following error occurs each time:

```
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 19: ordinal not in range(128)
```

I believe the `\xe9` was the character in question in all cases.

**Comment by itskando** [comment]
Reposted with additional information in the bug category.
