### ISSUE TITLE
MatchTV: Unable to extract sources

### ISSUE THREAD

**Issue by wb027** [ytdl-org/youtube-dl#21078]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.05.11**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl --verbose 'https://match.tv/on-air'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://match.tv/on-air']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.11
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.18.0-18-generic-x86_64-with-LinuxMint-19.1-tessa
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[generic] on-air: Requesting header
WARNING: Falling back on generic information extractor.
[generic] on-air: Downloading webpage
[generic] on-air: Extracting information
[download] Downloading playlist: Матч ТВ: прямой эфир, футбольные трансляции, программы о спорте
[generic] playlist Матч ТВ: прямой эфир, футбольные трансляции, программы о спорте: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[SportBox] 133529: Downloading webpage
ERROR: Unable to extract sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/sportbox.py", line 62, in _real_extract
    webpage, 'sources'),
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

The video plays fine in Chromium, Firefox and Falkon browsers.

**Comment by SlazE888** [comment]
this one request is incorrect and may be closed because it's just web-page link. The URL on LiveTV stream is discussed here- #8313

**Comment by SlazE888** [comment]
> ## Description
> The video plays fine in Chromium, Firefox and Falkon browsers.
this one request is incorrect and may be closed because it's just web-page link. The URL on LiveTV stream is discussed here- #8313

**Comment by SlazE888** [comment]
> The video plays fine in Chromium, Firefox and Falkon browsers.

this one request is incorrect and may be closed because it's just web-page link. The URL on LiveTV stream is discussed here- #8313

**Comment by SlazE888** [comment]
> The video plays fine in Chromium, Firefox and Falkon browsers.

I got this error logs:
**Verbose log**
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://matchtv.ru/vdl/player/media/133529']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.08.02
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[SportBox] 133529: Downloading webpage
ERROR: Unable to extract sources
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\sportbox.py", line 62, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract sources
