### ISSUE TITLE
Problems extracting 

### ISSUE THREAD

**Issue by LordFaggot** [ytdl-org/youtube-dl#21081]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.05.11**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```╔══⦃zanefromtheinternet卐WeArEbTy⦄⌁⦃Music⦄
╙─╼$ youtube-dl --verbose --extract-audio --audio-format mp3 https://youtu.be/phr1pOFK1V8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--extract-audio', '--audio-format', 'mp3', 'https://youtu.be/phr1pOFK1V8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.6.7 (CPython) - Linux-4.18.0-18-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6-0ubuntu0.18.04.1, ffprobe 3.4.6-0ubuntu0.18.04.1
[debug] Proxy map: {}
[youtube] phr1pOFK1V8: Downloading webpage
[youtube] phr1pOFK1V8: Downloading video info webpage
ERROR: phr1pOFK1V8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1624, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: phr1pOFK1V8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.



## Description

<!--
Provide an explanation of your issue in an arbitrary form. Please make sure the description is worded well enough to be understood, see https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

WRITE DESCRIPTION HERE won't extract audio from any video

**Comment by LordFaggot** [comment]
what are you talking about out dated? i just reinstalled it LOL?

**Comment by LordFaggot** [comment]
nevermind i figured it out for some reason it wasn't downloading the correct version with wget 

so i curled it ;)
