### ISSUE TITLE
learning.oreilly.com video broken - youtube_dl.utils.RegexNotFoundError

### ISSUE THREAD

**Issue by zioalex** [ytdl-org/youtube-dl#21090]
## Checklist

- [ X ] I'm reporting a broken site support
- [ X ] I've verified that I'm running youtube-dl version **2019.05.11**
- [ X ] I've checked that all provided URLs are alive and playable in a browser
- [ X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v -n --sleep-interval 60 --write-sub --convert-subs srt --playlist-reverse --skip-unavailable-fragments -ic  --socket-timeout 5 --retries infinite --write-description --write-info-json --write-annotations -o "%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" https://learning.oreilly.com/videos/clean-code/9780134661742/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-n', '--sleep-interval', '60', '--write-sub', '--convert-subs', 'srt', '--playlist-reverse', '--skip-unavailable-fragments', '-ic', '--socket-timeout', '5', '--retries', 'infinite', '--write-description', '--write-info-json', '--write-annotations', '-o', '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', 'https://learning.oreilly.com/videos/clean-code/9780134661742/', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.11
[debug] Python version 3.4.2 (CPython) - Linux-4.4.38-v7+-armv7l-with-debian-8.0
[debug] exe versions: avconv 11.12-6, avprobe 11.12-6
[debug] Proxy map: {}
[safari:course] Downloading login form
ERROR: Unable to extract csrf token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/alex/.local/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/alex/.local/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 528, in extract
    self.initialize()
  File "/home/alex/.local/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 432, in initialize
    self._real_initialize()
  File "/home/alex/.local/lib/python3.4/site-packages/youtube_dl/extractor/safari.py", line 27, in _real_initialize
    self._login()
  File "/home/alex/.local/lib/python3.4/site-packages/youtube_dl/extractor/safari.py", line 51, in _login
    login_page, 'csrf token')
  File "/home/alex/.local/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 1013, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/alex/.local/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract csrf token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

This same command and URL was working few days ago. I guess that something changed server side. I cannot provide the credential but I can run further debug if needed.

**Comment by zzztianqi** [comment]
Hi, I was able to download yesterday and encounter the same problem now

**Comment by yaasin12** [comment]
they changed their login procedure just have to change some lines in the codes I think

**Comment by zioalex** [comment]
Can you point to the change they did?
May be we can try a workaround.

**Comment by gopherunner** [comment]
any updates on this?
