### ISSUE TITLE
site support: mediagoblin, libreplanet

### ISSUE THREAD

**Issue by jpritikin** [ytdl-org/youtube-dl#21097]
I'd like to download all the 2019 conference videos,

[libreplanet](https://media.libreplanet.org/u/libreplanet/tag/libreplanet-2019-video/)

Any chance of getting this working?

**Comment by jpritikin** [comment]
```
joshua@cocoa:~/OpenMx$ youtube-dl -v https://media.libreplanet.org/u/libreplanet/tag/libreplanet-2019-video/
[debug] System config: []
[debug] User config: ['-x', '--no-mtime', '--audio-format', 'opus', '--audio-quality', '96k', '--ignore-errors', '--download-archive', '/home/joshua/.config/youtube-dl/downloaded.txt']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://media.libreplanet.org/u/libreplanet/tag/libreplanet-2019-video/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 3.7.3 (CPython) - Linux-5.0.0-13-generic-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] libreplanet-2019-video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] libreplanet-2019-video: Downloading webpage
[generic] libreplanet-2019-video: Extracting information
ERROR: Unsupported URL: https://media.libreplanet.org/u/libreplanet/tag/libreplanet-2019-video/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/generic.py", line 3320, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://media.libreplanet.org/u/libreplanet/tag/libreplanet-2019-video/

```
