### ISSUE TITLE
[LinuxAcademy] TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by greatpilaf** [ytdl-org/youtube-dl#21129]
## Verbose log

```
system@debian:~/Downloads/test$ youtube-dl -u user -p pass https://linuxacademy.com/cp/modules/view/id/140

[LinuxAcademy] Downloading authorize page
[LinuxAcademy] Downloading login page
[LinuxAcademy] Downloading callback page
[LinuxAcademy] Downloading token validation page
[LinuxAcademy] 140: Downloading webpage
[download] Downloading playlist: LXC/LXD Deep Dive
[LinuxAcademy] playlist LXC/LXD Deep Dive: Collected 26 video ids (downloading 26 of them)
[download] Downloading video 1 of 26
[LinuxAcademy] 1310-1: Downloading webpage
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2008, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1006, in process_ie_result
    extra_info=extra)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 868, in process_ie_result
    extra_info=extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/linuxacademy.py", line 165, in _real_extract
    webpage, item_id, require_title=False, m3u8_id='hls',)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 2644, in _extract_jwplayer_data
    jwplayer_data, video_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 2650, in _parse_jwplayer_data
    if 'playlist' not in jwplayer_data:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by bew** [comment]
BIG WARNING @greatpilaf you included the username _and password_ of your linuxacademy account in the issue (arguments `-u` & `-p`), I'd suggest you to remove thoses quickly (or put fake ones instead)

**Comment by greatpilaf** [comment]
Thank you for the advise, I corrected the problem.

**Comment by karimmafadl** [comment]
I have the same issue anyone find a solution for that ?

**Comment by greatpilaf** [comment]
@karimmafadl yes, I create a pull request for fix this: https://github.com/ytdl-org/youtube-dl/pull/21132
this request was denied because affect other cases.
But you can clone my repository, compile it and use it in the same way.

**For Linux Enviroment**

`git clone https://github.com/greatpilaf/youtube-dl.git`
`cd youtube-dl/`
`make youtube-dl`

It is not the right thing but it is a temporary solution for this site.

**Comment by jpcert1** [comment]
It works. Thank you @greatpilaf!

**Comment by karimmafadl** [comment]
Working fine Thanks man :) @greatpilaf

**Comment by jediknight31** [comment]
@greatpilaf It just got broken again. Looks like instead of actual values, javascript variables are being used to create the json for the player setup.

Log below 
```
>youtube-dl -u <user> -p <password> -o %(title)s.%(ext)s https://linuxacademy.com/cp/modules/view/id/207 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-o', '%(title)s.%(ext)s', 'https://linuxacademy.com/cp/modules/view/id/207', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.06.08
[debug] Python version 3.6.5 (CPython) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg 4.1.3
[debug] Proxy map: {}
[LinuxAcademy] Downloading authorize page
[LinuxAcademy] Downloading login page
[LinuxAcademy] Downloading callback page
[LinuxAcademy] Downloading token validation page
[LinuxAcademy] 207: Downloading webpage
[download] Downloading playlist: Google Cloud Essentials
[LinuxAcademy] playlist Google Cloud Essentials: Collected 35 video ids (downloading 35 of them)
[download] Downloading video 1 of 35
[LinuxAcademy] 2077-1: Downloading webpage
Traceback (most recent call last):
  File "d:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\Scripts\youtube-dl.exe\__main__.py", line 9, in <module>
  File "d:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\youtube_dl\__init__.py", line 474, in main
    _real_main(argv)
  File "d:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\youtube_dl\__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "d:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\youtube_dl\YoutubeDL.py", line 2008, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "d:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\youtube_dl\YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "d:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\youtube_dl\YoutubeDL.py", line 1006, in process_ie_result
    extra_info=extra)
  File "d:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\youtube_dl\YoutubeDL.py", line 868, in process_ie_result
    extra_info=extra_info)
  File "d:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "d:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "d:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\youtube_dl\extractor\linuxacademy.py", line 165, in _real_extract
    webpage, item_id, require_title=False, m3u8_id='hls',)
  File "d:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\youtube_dl\extractor\common.py", line 2645, in _extract_jwplayer_data
    jwplayer_data, video_id, *args, **kwargs)
  File "d:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\youtube_dl\extractor\common.py", line 2651, in _parse_jwplayer_data
    if 'playlist' not in jwplayer_data:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by stratus-ss** [comment]
I also have the same problem
```youtube-dl -u <user> -p <password> https://linuxacademy.com/cp/courses/lesson/course/3376/lesson/2/module/274 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://linuxacademy.com/cp/courses/lesson/course/3376/lesson/2/module/274', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.27
[debug] Python version 3.7.3 (CPython) - Linux-5.1.15-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[LinuxAcademy] Downloading authorize page
[LinuxAcademy] Downloading login page
[LinuxAcademy] Downloading callback page
[LinuxAcademy] Downloading token validation page
[LinuxAcademy] 3376-2: Downloading webpage
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 11, in <module>
    load_entry_point('youtube-dl==2019.6.27', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.7/site-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/usr/lib/python3.7/site-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2008, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/linuxacademy.py", line 165, in _real_extract
    webpage, item_id, require_title=False, m3u8_id='hls',)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 2645, in _extract_jwplayer_data
    jwplayer_data, video_id, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 2651, in _parse_jwplayer_data
    if 'playlist' not in jwplayer_data:
TypeError: argument of type 'NoneType' is not iterable
```
