### ISSUE TITLE
site support: mediagoblin, libreplanet

### ISSUE THREAD

**Issue by jpritikin** [ytdl-org/youtube-dl#21122]
## Checklist

- [X ] I'm reporting a new site support request
- [X ] I've verified that I'm running youtube-dl version **2019.05.11**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that none of provided URLs violate any copyrights
- [ X] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Playlist: https://media.libreplanet.org/u/libreplanet/tag/libreplanet-2019-video/

Single videos from this site work fine.

## Description

```
joshua@cocoa:/tmp$ youtube-dl -v https://media.libreplanet.org/u/libreplanet/tag/libreplanet-2019-video/
[debug] System config: []
[debug] User config: ['-x', '--no-mtime', '--audio-format', 'opus', '--audio-quality', '96k', '--ignore-errors', '--download-archive', '/home/joshua/.config/youtube-dl/downloaded.txt']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://media.libreplanet.org/u/libreplanet/tag/libreplanet-2019-video/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.11
[debug] Python version 3.7.3 (CPython) - Linux-5.0.0-13-generic-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] libreplanet-2019-video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] libreplanet-2019-video: Downloading webpage
[generic] libreplanet-2019-video: Extracting information
ERROR: Unsupported URL: https://media.libreplanet.org/u/libreplanet/tag/libreplanet-2019-video/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/generic.py", line 3329, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://media.libreplanet.org/u/libreplanet/tag/libreplanet-2019-video/

```

**Comment by ealgase** [comment]
Libreplanet is just a mediagoblin instance, correct?

**Comment by jpritikin** [comment]
Yes

**Comment by ealgase** [comment]
Is there a list of mediagoblin instances?

**Comment by jpritikin** [comment]
> Is there a list of mediagoblin instances?

No idea. Maybe you could ask upstream to add some unique HTML to identify the page as mediagoblin?

**Comment by ealgase** [comment]
Yeah, the current PeerTube implementation is... subpar, so a different solution would be ideal for MediaGoblin
![Screenshot 2019-05-16 at 9 06 39 PM](https://user-images.githubusercontent.com/11603778/57896401-97a47400-781e-11e9-8ba9-6c0e784b1888.png)
