### ISSUE TITLE
unable to download

### ISSUE THREAD

**Issue by 4bb3y** [ytdl-org/youtube-dl#21151]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.05.11**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -f 22 --verbose ICtkpLqY3BY
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'22', u'--verbose', u'ICtkpLqY3BY']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.12 - Linux-4.15.0-50-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15-0ubuntu0.16.04.1, ffprobe 2.8.15-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] ICtkpLqY3BY: Downloading webpage
[youtube] ICtkpLqY3BY: Downloading video info webpage
ERROR: ICtkpLqY3BY: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 316, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1175, in _real_extract
    video_id=video_id)
ExtractorError: ICtkpLqY3BY: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

script unable to download anything from youtube

**Comment by bitraid** [comment]
>  I've verified that I'm running youtube-dl version 2019.05.11

You are using a very old version:

>[debug] youtube-dl version 2016.02.22

**Comment by 4bb3y** [comment]
thank you, i'll check the update version.
    Pada Minggu, 19 Mei 2019 18.24.38 WIB, bitraid <notifications@github.com> menulis:  
 
 

I've verified that I'm running youtube-dl version 2019.05.11


You are using a very old version:


[debug] youtube-dl version 2016.02.22
