### ISSUE TITLE
It's not working for New Safari Site. I have 2019.05.11 version

### ISSUE THREAD

**Issue by ManvendraSK** [ytdl-org/youtube-dl#21150]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.05.11**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--playlist-start', u'1', u'-o', u'.\\%(playlist_index)s - %(title)s.%(ext)s', u'--max-downloads', u'1', u'-v', u'https://learning.oreilly.com/videos/algorithms-in-motion/10000MNLV201715']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.11
[debug] Python version 2.7.16 (CPython) - Linux-5.0.13-300.fc30.x86_64-x86_64-with-fedora-30-Thirty
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[safari:course] Downloading login form
ERROR: Unable to extract csrf token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 528, in extract
    self.initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 432, in initialize
    self._real_initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/safari.py", line 27, in _real_initialize
    self._login()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/safari.py", line 51, in _login
    login_page, 'csrf token')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1013, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract csrf token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

This is the same issue reported in issue number https://github.com/ytdl-org/youtube-dl/issues/21090. But still, it does not seem to be working. Thanks. :smile:

**Comment by ManvendraSK** [comment]
Hello @dstftw, please provide the link to the duplicate issue.

**Comment by dstftw** [comment]
You already did.

**Comment by ManvendraSK** [comment]
Ok. But that one is also closed, but not resolved. That's why I opened this new one, as I couldn't find a re-open button anywhere. :-). I don't know the Python, or could have solved this one myself. 😊

Now how will I able to track the issue if it gets resolved sometime in future because it is closed.

**Comment by dstftw** [comment]
Again: it's closed since it's resolved. You must either run from sources or wait for the next release.
