### ISSUE TITLE
"token" parameter not in video info for unknown reason

### ISSUE THREAD

**Issue by MartenBE** [ytdl-org/youtube-dl#21162]
## Checklist

- [?] I'm reporting a broken site support issue (what does this mean?)
- [x] I've verified that I'm running youtube-dl version **2019.01.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl --version
2019.01.17

$ youtube-dl --verbose "https://www.youtube.com/watch?v=AMsoy2_ZJJg"
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=AMsoy2_ZJJg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.17
[debug] Python version 3.7.3 (CPython) - Linux-5.0.16-300.fc30.x86_64-x86_64-with-fedora-30-Thirty
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[youtube] AMsoy2_ZJJg: Downloading webpage
[youtube] AMsoy2_ZJJg: Downloading video info webpage
ERROR: AMsoy2_ZJJg: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1689, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: AMsoy2_ZJJg: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Youtube-dl is unable to dowload the youtube video (which is accessible and playable through my browser). It throws the error `"token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug .` and urges me to post this bug.

**Comment by MartenBE** [comment]
My apologies, apparently I had youtube-dl installed both via pip and the package manager and used the oldest of the 2. I should have seen it!

This may be deleted.
