### ISSUE TITLE
[bug] Cannot download from Funimation

### ISSUE THREAD

**Issue by blackoutworm** [ytdl-org/youtube-dl#21167]
Funimation is giving me the error "Unable to extract al:web:url;", whatever that means.
Before you ask, yes my funimation login credentials are correct.
And I'm also on the latest version.

**Comment by blackoutworm** [comment]
Here's the error youtube-dl gives me:

Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/funimation.py", line 100, in _real_extract
    ], webpage, fatal=True)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1135, in _html_search_meta
    html, display_name, fatal=fatal, group='content', **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract al:web:url;
