### ISSUE TITLE
[FrontendMasters.com] Course download is broken

### ISSUE THREAD

**Issue by MichaelDeBoey** [ytdl-org/youtube-dl#21177]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://frontendmasters.com/courses/api-design-nodejs-v3']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.7.3 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[FrontendMastersCourse] Downloading login page
[FrontendMastersCourse] Logging in
[FrontendMastersCourse] api-design-nodejs-v3: Downloading course JSON
[download] Downloading playlist: API Design in Node.js, v3
[FrontendMastersCourse] playlist API Design in Node.js, v3: Collected 43 video ids (downloading 43 of them)
[download] Downloading video 1 of 43
[FrontendMasters] Downloading login page
[FrontendMasters] Logging in
[FrontendMasters] FCTNhDyqII: Downloading webm-low source JSON
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2008, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 807, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1006, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 873, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/frontendmasters.py", line 161, in _real_extract
TypeError: 'bool' object is not subscriptable
```

## Description

I tried with all these links, but none worked:
- https://frontendmasters.com/courses/api-design-nodejs-v3
- https://frontendmasters.com/courses/graphql
- https://frontendmasters.com/courses/electron-v2
- https://frontendmasters.com/courses/firebase-react-v2
- https://frontendmasters.com/courses/typescript-v2
- https://frontendmasters.com/courses/deep-javascript-v3
- https://frontendmasters.com/courses/js-recent-parts
- https://frontendmasters.com/courses/python
- https://frontendmasters.com/courses/intermediate-python

**Comment by MichaelDeBoey** [comment]
@dstftw If you want, I can give you credentials to look into this one

**Comment by oluwajubelo1** [comment]
Same here

**Comment by kostaspa** [comment]
yeap it does not work

**Comment by Ayman97** [comment]
same here

**Comment by BrianVia** [comment]
Happy to try to assist in any way here as I have an active login

**Comment by Ayman97** [comment]
@BrianVia Be careful, They have a system that let them detect any scripting downloads, your account will be suspended automatically for 24 hours as a warning, and then they will suspended it forever.

**Comment by sujaldev** [comment]
For anyone still getting this error, not sure but I think you have to provide it the url for not the course page but index.m3u8 file associated, also provide the cookie header on this file's request to youtube-dl with the `--add-header` flag.
The above way worked for me...
