### ISSUE TITLE
tv4 play 

### ISSUE THREAD

**Issue by jonte1** [ytdl-org/youtube-dl#21210]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.05.20**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[05/25/19 08:23:38] [debug] System config: []
[05/25/19 08:23:38] [debug] User config: []
[05/25/19 08:23:38] [debug] Custom config: []
[05/25/19 08:23:38] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Nedladdningar\\Playsites\\%(title)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', 'https://www.tv4play.se/program/bert-karlsson-elefanten-i-folkhemmet/11961977']
[05/25/19 08:23:38] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[05/25/19 08:23:38] [debug] youtube-dl version 2019.05.20
[05/25/19 08:23:38] [debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[05/25/19 08:23:38] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[05/25/19 08:23:38] [debug] Proxy map: {}
[05/25/19 08:23:38] WARNING: [TV4] Unknown MIME type application/mp4 in DASH manifest
[05/25/19 08:23:38] ERROR: Conversion failed!
[05/25/19 08:23:38] Traceback (most recent call last):
[05/25/19 08:23:38]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\YoutubeDL.py", line 2054, in post_process
[05/25/19 08:23:38]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\postprocessor\ffmpeg.py", line 512, in run
[05/25/19 08:23:38]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
[05/25/19 08:23:38] youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
[05/25/19 08:23:38] 

## Description

WRITE DESCRIPTION HERE
When i download from this link i get error message and the result are 3 files and they are dont merged.

https://www.tv4play.se/program/bert-karlsson-elefanten-i-folkhemmet/11961977
I get this 3 files: 
Bert Karlsson - elefanten i folkhemmet del 1.fhls-133.mp4
Bert Karlsson - elefanten i folkhemmet del 1.fhls-5666.mp4
Bert Karlsson - elefanten i folkhemmet del 1.temp.mp4

**Comment by remitamine** [comment]
update ffmpeg.

**Comment by jonte1** [comment]
How do i update ffmpeg easily?
Please i need instructions

**Comment by rautamiekka** [comment]
> How do i update ffmpeg easily?
> Please i need instructions

Since you're on Window$,
1) go to https://ffmpeg.zeranoe.com/builds/
2) under `Version`, click `4.1.3`
3) under `Architecture`, click `64-bit` if you're running 64-bit OS, otherwise `32-bit`
4) under `Linking`, click `Static`
5) click `Download Build`
6) in the file, go to `ffmpeg-4.1.3-win64-static\bin\` and extract to `C:\Users\Public\Downloads\ffmpeg\`
7) add `--ffmpeg-location "C:\Users\Public\Downloads\ffmpeg\"` to your youtube-dl command or alternatively to https://github.com/ytdl-org/youtube-dl#configuration

**Comment by lelle10** [comment]
Hi
I have the same problem on how to update ffmpeg. I make an issue on youtube dlg but it seems that the project are sleeping. 
I downloaded the files you listed above earlier and replace the files. ffmpeg and ffprobe in the youtube dlg working directory.  Now the download works fine but I get error everytime but the files seems to work properly. Can I just ignore the error message or what?
