### ISSUE TITLE
I can not download courses from teamtreehouse.com

### ISSUE THREAD

**Issue by apache123** [ytdl-org/youtube-dl#21230]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
Last login: Mon May 27 15:46:04 on ttys000
apachees-MBP:~ apachee$ youtube-dl --username "mail@mail.com" --password "password" -o "~/Users/apachee/%(playlist)s/%(chapter)s/%(playlist_index)s-%(title)s.%(ext)s" --verbose -v --sleep-interval 5 "https://teamtreehouse.com/library/introducing-lists"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'-o', u'~/Users/apachee/%(playlist)s/%(chapter)s/%(playlist_index)s-%(title)s.%(ext)s', u'--verbose', u'-v', u'--sleep-interval', u'5', u'https://teamtreehouse.com/library/introducing-lists']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.7.15 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[TeamTreeHouse] Downloading signin page
[TeamTreeHouse] Logging in
[TeamTreeHouse] introducing-lists: Downloading webpage
[TeamTreeHouse] introducing-lists: Downloading stages page
[download] Downloading playlist: Introducing Lists
[TeamTreeHouse] playlist Introducing Lists: Collected 23 video ids (downloading 23 of them)
[download] Downloading video 1 of 23
[TeamTreeHouse] welcome-12: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://videos.teamtreehouse.com/videos/IntroducingLists-Python-S1-V1_v2-720p.mp4?token=5cee87b8_e67923b054d06f0d515dd728e9dd2417d8e0cf91'
[download] Sleeping 5 seconds...
[download] Destination: /Users/apachee/Users/apachee/Introducing Lists/Meet Lists/01-Welcome.mp4
[download] 100% of 17.12MiB in 00:06
[download] Downloading video 2 of 23
[TeamTreeHouse] creation-2: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://videos.teamtreehouse.com/videos/IntroducingLists-Python-S1-V2_v2-720p.mp4?token=5cee87ca_0da3cf1df9657c03d370923e3c782c94be74e2f0'
[download] Sleeping 5 seconds...
[download] Destination: /Users/apachee/Users/apachee/Introducing Lists/Meet Lists/02-Creation.mp4
[download] 100% of 8.66MiB in 00:08
[download] Downloading video 3 of 23
[TeamTreeHouse] introducing-lists: Downloading webpage
WARNING: unable to extract og:title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Unable to extract stages path; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/teamtreehouse.py", line 128, in _real_extract
    webpage, 'stages path')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract stages path; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

apachees-MBP:~ apachee$ 
```

## Description

when I want to download a course from [teamtreehouse.com](teamtreehouse.com), the first and the second video download without problems but the third item on the course actually is not a video it is a review questions so the youtube-dl does not recognize it and when it finds out there is no video on that link this error occur that I provided it above and the program stop downloading the video following that link that does not contain any video, I hope to fix that soon by skipping those links that does not contain a video
this image shows that the third item does not contain any video but it is review questions
<img width="730" alt="Screen Shot 2019-05-27 at 4 36 11 PM" src="https://user-images.githubusercontent.com/9536310/58424332-dac4d980-809f-11e9-9ddb-2787fd020706.png">
)

**Comment by remitamine** [comment]
```
-i, --ignore-errors              Continue on download errors, for example to
                                 skip unavailable videos in a playlist
```

**Comment by apache123** [comment]
thank you so much, but now the the title number is not ordered it skipped number 3 and other numbers, how can I fix that. I use this formatting option
-o "~/Users/apachee/%(playlist)s/%(chapter)s/%(playlist_index)s-%(title)s.%(ext)s"
<img width="252" alt="Screen Shot 2019-05-27 at 7 22 54 PM" src="https://user-images.githubusercontent.com/9536310/58431178-48c7cb80-80b5-11e9-9dc4-9fbfffb489f9.png">
