### ISSUE TITLE
MLB videos broken

### ISSUE THREAD

**Issue by lawlmart** [ytdl-org/youtube-dl#21241]
## Checklist

- [ X] I'm reporting a broken site support
- [X ] I've verified that I'm running youtube-dl version **2019.05.20**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

$ youtube-dl https://www.mlb.com/video/must-c-belli-s-impressive-throw --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.mlb.com/video/must-c-belli-s-impressive-throw', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.7.10 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] must-c-belli-s-impressive-throw: Requesting header
WARNING: Falling back on generic information extractor.
[generic] must-c-belli-s-impressive-throw: Downloading webpage
[generic] must-c-belli-s-impressive-throw: Extracting information
ERROR: Unsupported URL: https://www.mlb.com/video/must-c-belli-s-impressive-throw
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2340, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 110, column 83
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3329, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.mlb.com/video/must-c-belli-s-impressive-throw

## Description

MLB has a new video setup and it doesn't appear to be supported for newer URLs. Here's another one: https://www.mlb.com/video/yonny-chirinos-in-play-out-s-to-rowdy-tellez

**Comment by RingoTheDog** [comment]
Bump....
and new example:   
https://www.mlb.com/video/boone-on-implementing-mercy-rule?t=most-popular

>youtube-dl.py -v "https://www.mlb.com/video/boone-on-implementing-mercy-rule?t=mos
t-popular"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.mlb.com/video/boone-on-implementing-mercy-rule?t=most
-popular']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.08.13
[debug] Python version 3.5.1 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] boone-on-implementing-mercy-rule?t=most-popular: Requesting header
WARNING: Falling back on generic information extractor.
[generic] boone-on-implementing-mercy-rule?t=most-popular: Downloading webpage
[generic] boone-on-implementing-mercy-rule?t=most-popular: Extracting information
ERROR: Unsupported URL: https://www.mlb.com/video/boone-on-implementing-mercy-rule?t=most-popular
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 3333, in _real_extrac
t
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.mlb.com/video/boone-on-implementing-
mercy-rule?t=most-popular



Thanks
Ringo
