### ISSUE TITLE
can't download on crunchyroll (FFmpegPostProcessorError) on a raspi 3B+

### ISSUE THREAD

**Issue by Ara0n** [ytdl-org/youtube-dl#21240]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.05.20**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
xvfb-run -a youtube-dl --all-subs --embed-subs -v -f 'best' -o "shield%(episode_number)s.%(ext)s" "https://www.crunchyroll.com/the-rising-of-the-shield-hero"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--all-subs', u'--embed-subs', u'-v', u'-f', u'best', u'-o', u'shield%(episode_number)s.%(ext)s', u'https://www.crunchyroll.com/the-rising-of-the-shield-hero']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.7.13 (CPython) - Linux-4.19.42-v7+-armv7l-with-debian-9.9
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1, phantomjs 2
[debug] Proxy map: {}
[crunchyroll:playlist] the-rising-of-the-shield-hero: Downloading webpage
[download] Downloading playlist: The Rising of the Shield Hero
[crunchyroll:playlist] playlist The Rising of the Shield Hero: Collected 20 video ids (downloading 20 of them)
[download] Downloading video 1 of 20
[crunchyroll] 781148: Downloading webpage
[crunchyroll] 781148: Downloading media info for 1080p
[crunchyroll] 781148: Downloading stream info for 1080p
[crunchyroll] 781148: Downloading m3u8 information
[crunchyroll] 781148: Downloading media info for 720p
[crunchyroll] 781148: Downloading stream info for 720p
[crunchyroll] 781148: Downloading media info for 360p
[crunchyroll] 781148: Downloading stream info for 360p
[crunchyroll] 781148: Downloading m3u8 information
[crunchyroll] 781148: Downloading media info for 480p
[crunchyroll] 781148: Downloading stream info for 480p
[crunchyroll] 781148: Downloading media info
[info] Writing video subtitles to: shield1.ruRU.ass
[info] Writing video subtitles to: shield1.esES.ass
[info] Writing video subtitles to: shield1.ptBR.ass
[info] Writing video subtitles to: shield1.esLA.ass
[info] Writing video subtitles to: shield1.enUS.ass
[info] Writing video subtitles to: shield1.frFR.ass
[info] Writing video subtitles to: shield1.deDE.ass
[info] Writing video subtitles to: shield1.arME.ass
[info] Writing video subtitles to: shield1.itIT.ass
[debug] Invoking downloader on u'https://v.vrv.co/evs/db0f6fc58691ff66e12cb040fca53c75/assets/43265179ac409cfc297665c77bc22743_3612142.mp4/index-v1-a1.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly92LnZydi5jby9ldnMvZGIwZjZmYzU4NjkxZmY2NmUxMmNiMDQwZmNhNTNjNzUvYXNzZXRzLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1NTkyMjMwNjZ9fX1dfQ__&Signature=RLJ1kV202ouulX3SM4hOyDdNbGkHeKiRSLV8w6WLqpxe4W8Eblpy9HswrZ82no9oYiNUQwxh4XYXZYL2CFhNSx8laJWwyJsUYNmbkSUEWP1NLT7pZMPeWM7g1rlJKjN~d6bFtv6kXAs5UUTl-LNuPp42q0cl4I8y71JVvL1KEoNf2ea9SgJg8wflOmmmc3tsbTpUM9IwkKayUsiXDxfc4A9Nr0kpfwWEwJ3UCDJre92bGJyWh9jbdZkHqwYTnanGpdszR80tU2WKK7d50AwFwfPxG81xJEQ4oyW2U0q94Q~-IJDpTYBSfItrx3JcyuIBgPuPZK7JlryHzHZgJ-lAJQ__&Key-Pair-Id=APKAJKQQ2INNHTYFB44A'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 285
[download] Destination: shield1.mp4
[download] 100% of 307.94MiB in 02:51
[debug] ffmpeg command line: ffprobe -show_streams 'file:shield1.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "shield1.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:shield1.mp4' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:shield1.temp.mp4'
[ffmpeg] Embedding subtitles in 'shield1.mp4'
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:shield1.mp4' -i 'file:shield1.ruRU.ass' -i 'file:shield1.esES.ass' -i 'file:shield1.ptBR.ass' -i 'file:shield1.esLA.ass' -i 'file:shield1.enUS.ass' -i 'file:shield1.frFR.ass' -i 'file:shield1.deDE.ass' -i 'file:shield1.arME.ass' -i 'file:shield1.itIT.ass' -map 0 -c copy -map '-0:s' -map '-0:d' '-c:s' mov_text -map '1:0' '-metadata:s:s:0' 'language=rus' -map '2:0' '-metadata:s:s:1' 'language=spa' -map '3:0' '-metadata:s:s:2' 'language=por' -map '4:0' '-metadata:s:s:3' 'language=spa' -map '5:0' '-metadata:s:s:4' 'language=eng' -map '6:0' '-metadata:s:s:5' 'language=fra' -map '7:0' '-metadata:s:s:6' 'language=deu' -map '8:0' '-metadata:s:s:7' 'language=ara' -map '9:0' '-metadata:s:s:8' 'language=ita' 'file:shield1.temp.mp4'
ERROR: frame= 1846 fps=0.0 q=-1.0 size=    8180kB time=00:01:17.84 bitrate= 860.9kbits/s speed= 155x
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2054, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 426, in run
    self.run_ffmpeg_multiple_files(input_files, temp_filename, opts)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: frame= 1846 fps=0.0 q=-1.0 size=    8180kB time=00:01:17.84 bitrate= 860.9kbits/s speed= 155x
```

## Description

Tryied to download the episodes on my raspi pi 3B+, the ffmpeg is also up to date:
```
sudo apt install ffmpeg 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
ffmpeg is already the newest version (7:3.2.14-1~deb9u1).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
```
and same for xvfb:
```
sudo apt install xvfb 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
xvfb is already the newest version (2:1.19.2-1+rpt1+deb9u2).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
```
the exact same setup works well on my laptop

**Comment by dstftw** [comment]
>[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:shield1.mp4' -i 'file:shield1.ruRU.ass' -i 'file:shield1.esES.ass' -i 'file:shield1.ptBR.ass' -i 'file:shield1.esLA.ass' -i 'file:shield1.enUS.ass' -i 'file:shield1.frFR.ass' -i 'file:shield1.deDE.ass' -i 'file:shield1.arME.ass' -i 'file:shield1.itIT.ass' -map 0 -c copy -map '-0:s' -map '-0:d' '-c:s' mov_text -map '1:0' '-metadata:s:s:0' 'language=rus' -map '2:0' '-metadata:s:s:1' 'language=spa' -map '3:0' '-metadata:s:s:2' 'language=por' -map '4:0' '-metadata:s:s:3' 'language=spa' -map '5:0' '-metadata:s:s:4' 'language=eng' -map '6:0' '-metadata:s:s:5' 'language=fra' -map '7:0' '-metadata:s:s:6' 'language=deu' -map '8:0' '-metadata:s:s:7' 'language=ara' -map '9:0' '-metadata:s:s:8' 'language=ita' 'file:shield1.temp.mp4'

Run this command to get the full ffmpeg error.
