### ISSUE TITLE
Site support request: abc.net.au/btn

### ISSUE THREAD

**Issue by megascrapper** [ytdl-org/youtube-dl#21254]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.abc.net.au/btn/classroom/wwi-centenary/10527914

## Description

Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ignore-config', u'-v', u'https://www.abc.net.au/btn/classroom/wwi-centenary/10527914']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.7.16 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 10527914: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 10527914: Downloading webpage
[generic] 10527914: Extracting information
ERROR: Unsupported URL: https://www.abc.net.au/btn/classroom/wwi-centenary/10527914
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2340, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 52, column 17
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3329, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.abc.net.au/btn/classroom/wwi-centenary/10527914
```

**Comment by appleton-tom** [comment]
Two options for you to try.
1. view the video online. a download link is shown next to "share", "settings", "fullscreen".at the bottom.
or
2. view page source. search for MP4 for the video links.
Your example site:- https://www.abc.net.au/btn/classroom/wwi-centenary/10527914
.......
"url": "https://abcmedia.akamaized.net/btn/Classroom/20140805_ww1centenary_576.mp4",
"contentType": "video/mp4",
"label": 1280
},
{
"url": "https://abcmedia.akamaized.net/btn/Classroom/20140805_ww1centenary_288.mp4",
"contentType": "video/mp4",
"label": 470

**Comment by megascrapper** [comment]
> 1. view the video online. a download link is shown next to "share", "settings", "fullscreen".at the bottom.

Welp, didn't notice that the download is already there lol.

The second option did work on `youtube-dl` using the generic extractor, so I guess the only left to do is make it able to detect the site URL.

Just in case, here's a verbose log
```
$ youtube-dl -v --ignore-config https://abcmedia.akamaized.net/btn/Classroom/20140805_ww1centenary_576.mp4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--ignore-config', u'https://abcmedia.akamaized.net/btn/Classroom/20140805_ww1centenary_576.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.7.16 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 20140805_ww1centenary_576: Requesting header
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://abcmedia.akamaized.net/btn/Classroom/20140805_ww1centenary_576.mp4'
[download] Destination: 20140805_ww1centenary_576-20140805_ww1centenary_576.mp4
[download] 100% of 38.13MiB in 10:07
```
