### ISSUE TITLE
Error downloading from Instagram

### ISSUE THREAD

**Issue by jholton30062** [ytdl-org/youtube-dl#21261]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
Last login: Mon May 27 15:48:57 on ttys000
johlt@Farlow johlt $ cd Desktop/
johlt@Farlow Desktop $ sudo youtube-dl -U
Password:
youtube-dl is up-to-date (2019.05.20)
johlt@Farlow Desktop $ youtube-dl https://www.instagram.com/p/ByFoiPmjPHc-3GdFjNew3ykAAiXQBBE9YVwHEA0/
[Instagram] ByFoiPmjPHc-3GdFjNew3ykAAiXQBBE9YVwHEA0: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
johlt@Farlow Desktop $ youtube-dl --verbose https://www.instagram.com/p/ByFoiPmjPHc-3GdFjNew3ykAAiXQBBE9YVwHEA0/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.instagram.com/p/ByFoiPmjPHc-3GdFjNew3ykAAiXQBBE9YVwHEA0/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.7.16 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Instagram] ByFoiPmjPHc-3GdFjNew3ykAAiXQBBE9YVwHEA0: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/instagram.py", line 192, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1122, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1013, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

johlt@Farlow Desktop $ 

```

## Description

I've been able to download video with youtube-dl from Instagram before and was surprised by the message above. any ideas?

**Comment by dstftw** [comment]
>This Account is Private
