### ISSUE TITLE
[ProSiebenMaxx] Goblin Slayer: This video is unavailable

### ISSUE THREAD

**Issue by SebiderSushi** [ytdl-org/youtube-dl#21272]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

`youtube-dl https://www.prosiebenmaxx.de/anime/goblin-slayer/video/18-staffel-1-episode-8-fluestern-gebete-und-gesaenge-ganze-folge -v`
`[debug] System config: []`
`[debug] User config: []`
`[debug] Custom config: []`
`[debug] Command-line args: [u'https://www.prosiebenmaxx.de/anime/goblin-slayer/video/18-staffel-1-episode-8-fluestern-gebete-und-gesaenge-ganze-folge', u'-v']`
`[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8`
`[debug] youtube-dl version 2019.05.20`
`[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-50-generic-x86_64-with-Ubuntu-16.04-xenial`
`[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15, rtmpdump 2.4`
`[debug] Proxy map: {}`
`[prosiebensat1] anime/goblin-slayer/video/18-staffel-1-episode-8-fluestern-gebete-und-gesaenge-ganze-folge: Downloading webpage`
`[prosiebensat1] 5853876: Downloading videos JSON`
`[prosiebensat1] 5853876: Downloading sources JSON`
`[prosiebensat1] 5853876: Downloading urls JSON`
`ERROR: This video is unavailable`
`Traceback (most recent call last):`
`  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info`
`    ie_result = ie.extract(url)`
`  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract`
`    ie_result = self._real_extract(url)`
`  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/prosiebensat1.py", line 450, in _real_extract`
`    return self._extract_clip(url, webpage)`
`  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/prosiebensat1.py", line 399, in _extract_clip`
`    info = self._extract_video_info(url, clip_id)`
`  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/prosiebensat1.py", line 71, in _extract_video_info`
`    raise ExtractorError('This video is unavailable', expected=True)`
`ExtractorError: This video is unavailable`

## Description

If trying to download any of the following URLs with youtube-dl it yield the `ERROR: This video is unavailable`

`https://www.prosiebenmaxx.de/anime/goblin-slayer/video/17-staffel-1-episode-7-auf-in-den-tod-ganze-folge`
`https://www.prosiebenmaxx.de/anime/goblin-slayer/video/18-staffel-1-episode-8-fluestern-gebete-und-gesaenge-ganze-folge`
`https://www.prosiebenmaxx.de/anime/goblin-slayer/video/19-staffel-1-episode-9-hin-und-zurueck-ganze-folge`
`https://www.prosiebenmaxx.de/anime/goblin-slayer/video/110-staffel-1-episode-10-schlummer-ganze-folge`
`https://www.prosiebenmaxx.de/anime/goblin-slayer/video/111-staffel-1-episode-11-ein-festmahl-fuer-abenteurer-ganze-folge`
`https://www.prosiebenmaxx.de/anime/goblin-slayer/video/111-staffel-1-episode-11-ein-festmahl-fuer-abenteurer-ganze-folge`
`https://www.prosiebenmaxx.de/anime/goblin-slayer/video/112-preview-folge-12-die-finale-schlacht-gegen-die-goblins-clip`

Other videos I have tried download as expected, for example all full episode videos on the following pages:
`https://www.prosiebenmaxx.de/anime/blue-exorcist/video`
`https://www.prosiebenmaxx.de/anime/one-piece/video`
`https://www.prosiebenmaxx.de/anime/date-a-live/video`
`https://www.prosiebenmaxx.de/anime/gintama/video`
`https://www.sat1.de/tv/meine-klasse-voll-das-leben/video`
(even if probably unrelated i have included the link from sat1 since it uses the same extractor)

The suggested solution is of course to find the real issue here and to fix the extractor.

**Comment by SebiderSushi** [comment]
Your response time amazes me. Thank you very much for your work.
