### ISSUE TITLE
youtube embeds on recent (2019?) squarespace sites fail to download

### ISSUE THREAD

**Issue by galgeek** [ytdl-org/youtube-dl#21294]
## Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running youtube-dl version **2019.07.16**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs violate any copyrights
- [X] I've searched the bugtracker for similar site support requests including closed ones

## Description

youtube-dl fails on youtube embeds on some recent squarespace sites, including 
http://www.ootboxford.com/
https://www.harvardballetcompany.org/past-productions
http://www.immediategratification.org/

`youtube-dl --write-pages http://www.ootboxford.com`
produces a dump showing the site's youtube embed like so:
```
<div class="sqs-block video-block sqs-block-video" data-block-json="&#123;&quot;layout&quot;:&quot;caption-hidden&quot;,&quot;overlay&quot;:false,&quot;description&quot;:&#123;&quot;html&quot;:&quot;&lt;p&gt;Long-standing supporters of Helen &amp;amp; Douglas House, Out of the Blue performed at the last Childish Things - here they are, talking about the show, and their involvement with the charity.&lt;/p&gt;&quot;,&quot;source&quot;:&quot;&lt;p&gt;Long-standing supporters of Helen &amp;amp; Douglas House, Out of the Blue performed at the last Childish Things - here they are, talking about the show, and their involvement with the charity.&lt;/p&gt;&quot;&#125;,&quot;hSize&quot;:null,&quot;floatDir&quot;:null,&quot;html&quot;:&quot;&lt;iframe src=\&quot;//www.youtube.com/embed/Tc7b_JGdZfw?wmode=opaque&amp;amp;enablejsapi=1\&quot; height=\&quot;480\&quot; width=\&quot;854\&quot; scrolling=\&quot;no\&quot; frameborder=\&quot;0\&quot; allowfullscreen=\&quot;\&quot;&gt;\n&lt;/iframe&gt;&quot;,&quot;url&quot;:&quot;https://www.youtube.com/watch?v=Tc7b_JGdZfw&quot;,&quot;width&quot;:854,&quot;height&quot;:480,&quot;providerName&quot;:&quot;YouTube&quot;,&quot;thumbnailUrl&quot;:&quot;https://i.ytimg.com/vi/Tc7b_JGdZfw/hqdefault.jpg&quot;,&quot;resolvedBy&quot;:&quot;youtube&quot;&#125;" data-block-type="32" id="block-yui_3_17_2_22_1450272268012_7317">
```

```
youtube-dl -v http://www.ootboxford.com
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.ootboxford.com']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.16
[debug] Python version 3.5.6 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] www.ootboxford: Requesting header
WARNING: Falling back on generic information extractor.
[generic] www.ootboxford: Downloading webpage
[generic] www.ootboxford: Extracting information
ERROR: Unsupported URL: http://www.ootboxford.com
Traceback (most recent call last):
  File "/1/broz-venv/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/1/broz-venv/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/1/broz-venv/lib/python3.5/site-packages/youtube_dl/extractor/generic.py", line 3333, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.ootboxford.com
```

**Comment by dstftw** [comment]
This does not scale since any video can be embedded this way not only Youtube.
What should be done is unescaping and expanding embed code in place in generic extractor. This will allow supporting any video embedded this way.

**Comment by galgeek** [comment]
This issue is still present in youtube-dl version 2019.08.13.

```
$ youtube-dl -v http://ootboxford.com
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://ootboxford.com']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 3.5.6 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] ootboxford: Requesting header
[redirect] Following redirect to http://www.ootboxford.com/
[generic] www.ootboxford: Requesting header
WARNING: Falling back on generic information extractor.
[generic] www.ootboxford: Downloading webpage
[generic] www.ootboxford: Extracting information
ERROR: Unsupported URL: http://www.ootboxford.com/
Traceback (most recent call last):
  File "/1/broz-venv/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/1/broz-venv/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/1/broz-venv/lib/python3.5/site-packages/youtube_dl/extractor/generic.py", line 3333, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.ootboxford.com/
```
