### ISSUE TITLE
YTDL raising an OSError: [Errno 22]  'invalid argument' mid-download, but it's not an argument that I'm passing.

### ISSUE THREAD

**Issue by soilstack** [ytdl-org/youtube-dl#21307]
## Checklist

- [x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
(base) PS C:\Users\kanugu\Dropbox\leech_rip>
(base) PS C:\Users\kanugu\Dropbox\leech_rip> .\youtube-dl.exe --config-location  c:\Users\kanugu\Dropbox\leech_rip\youtube-dl.conf
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['--verbose', '--extract-audio', '--audio-format', 'mp3', '--download-archive', 'leech2-archive.txt', 'https://www.youtube.com/playlist?list=PLzF0zmFsscc3Pk4wmJDco1chmB0Rxo7HM', '-o', 'c:/Users/kanugu/Dropbox/leech_rip/leech/%(artist)s-%(title)s.%(ext)s', '--write-description', '--sleep-interval', '20', '--max-sleep-interval', '80', '--geo-bypass', '--ignore-errors']
[debug] Command-line args: ['--config-location', 'c:\\Users\\kanugu\\Dropbox\\leech_rip\\youtube-dl.conf']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-92988-g32fb83e431, ffprobe N-92988-g32fb83e431
[debug] Proxy map: {}
[youtube:playlist] PLzF0zmFsscc3Pk4wmJDco1chmB0Rxo7HM: Downloading webpage
[download] Downloading playlist: leech2
[youtube:playlist] playlist leech2: Downloading 24 videos
[download] Downloading video 1 of 24
[download] 1997 Hip Hop Compilation Volume 1 has already been recorded in archive
[download] Downloading video 2 of 24
[download] 1991 1992 Hip Hop Compilation Volume 1 has already been recorded in archive
[download] Downloading video 3 of 24
[download] 1994 Hip Hop Compilation Volume 1 has already been recorded in archive
[download] Downloading video 4 of 24
[download] 1994 Hip Hop compilation Volume 2 has already been recorded in archive
[download] Downloading video 5 of 24
[download] Tool - Live In Birmingham, AL - 2019.05.07. [FULL, CLEAR AUDIO] has already been recorded in archive
[download] Downloading video 6 of 24
[download] 1995 Hip Hop Compilation Volume 1 has already been recorded in archive
[download] Downloading video 7 of 24
[download] Tool - Live In Kansas City - 2019.05.14. [FULL] has already been recorded in archive
[download] Downloading video 8 of 24
[download] Tool - Live In St. Louis - 2019.05.13. [FULL] has already been recorded in archive
[download] Downloading video 9 of 24
[download] TAUK - Concord Music Hall Set 2 - 4.12.19 has already been recorded in archive
[download] Downloading video 10 of 24
[download] TAUK at Concord Music Hall - Set 1 has already been recorded in archive
[download] Downloading video 11 of 24
[download] February 1st, 2019  Brighton Music Hall; Allston, MA (Set 2) has already been recorded in archive
[download] Downloading video 12 of 24
[download] TAUK   Feb 1, 2019 Brighton Music Hall; Allston, MA  (Set 1) has already been recorded in archive
[download] Downloading video 13 of 24
[download] 1995 Hip Hop Compilation Volume 3 has already been recorded in archive
[download] Downloading video 14 of 24
[download] 90´s East coast Hip Hop | Special Mix. |The best songs.. has already been recorded in archive
[download] Downloading video 15 of 24
[download] Pete Rock DJs Live on Hot 97 (1994) has already been recorded in archive
[download] Downloading video 16 of 24
[download] Hot 97 "Street Jams" (May 1994) has already been recorded in archive
[download] Downloading video 17 of 24
[download] Kid Capri Spins 'Deja Vu' Live On Hot 97 + More! (1997) has already been recorded in archive
[download] Downloading video 18 of 24
[download] DJ Premier WBLS Thunderstorm Vol. 1 - Full has already been recorded in archive
[download] Downloading video 19 of 24
[download] DJ Premier WBLS Thunderstorm Vol. 2 - Part 2/2 has already been recorded in archive
[download] Downloading video 20 of 24
[download] DJ Premier  Rare Play Vol. 1 - Full Album has already been recorded in archive
[download] Downloading video 21 of 24
[download] Hip Hop & Rap | WBLS Radio Show : Thunder Storm Vol. 1 has already been recorded in archive
[download] Downloading video 22 of 24
[youtube] tF_Ij1-HsAw: Downloading webpage
[youtube] tF_Ij1-HsAw: Downloading video info webpage
[youtube] {18} signature length 104, html5 player vflRqBT2o
[youtube] {137} signature length 108, html5 player vflRqBT2o
[youtube] {134} signature length 108, html5 player vflRqBT2o
[youtube] {140} signature length 104, html5 player vflRqBT2o
[youtube] tF_Ij1-HsAw: Downloading MPD manifest
[info] Writing video description to: c:\Users\kanugu\Dropbox\leech_rip\leech\The Notorious B.I.G.-Hip Hop & Rap _ WBLS Radio Show  - Thunder Storm Vol. 6.description
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1559659867/ei/-jD2XJHsNYWQoQOhzJ3YDg/ip/103.6.150.109/id/b45fc88f5f87b00c/source/youtube/requiressl/yes/playback_host/r3---sn-htgx20capj-npol.googlevideo.com/mm/31%2C29/mn/sn-htgx20capj-npol%2Csn-npoe7ne6/ms/au%2Crdu/mv/m/pl/24/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1877500/mt/1559638136/fvip/1/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Citag/sig/ALgxI2wwRQIgO0cpXGbjADEiz2g711IQmsHu77PUPGRi1J0MS1wIcfECIQD8mGW_-MwjGAJtO6YvUL49E-FnviFdVRy9q1Y_1zXdNQ%3D%3D/lsparams/playback_host%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cinitcwndbps/lsig/AHylml4wRAIgNSJvZK7g6Lq0tujYP_mB6yl0y2jEXGHE18PgopGuy-ECIBnp7uS3NLIAHePNQFydQhsrLH99b_hGdkKYpyvjh-2F'
[download] Sleeping 48.67 seconds...
[dashsegments] Total fragments: 417
[download] Destination: c:\Users\kanugu\Dropbox\leech_rip\leech\The Notorious B.I.G.-Hip Hop & Rap _ WBLS Radio Show  - Thunder Storm Vol. 6.m4a
[download]  71.7% of ~64.04MiB at  5.95MiB/s ETA 00:08    ERROR: unable to download video data: [Errno 22] Invalid argument: 'c:\\Users\\kanugu\\Dropbox\\leech_rip\\leech\\The Notorious B.I.G.-Hip Hop & Rap _ WBLS Radio Show  - Thunder Storm Vol. 6.m4a.ytdl'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\YoutubeDL.py", line 1915, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\YoutubeDL.py", line 1854, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\downloader\dash.py", line 51, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\downloader\fragment.py", line 118, in _append_fragment
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\downloader\fragment.py", line 87, in _write_ytdl_file
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\utils.py", line 458, in sanitize_open
OSError: [Errno 22] Invalid argument: 'c:\\Users\\kanugu\\Dropbox\\leech_rip\\leech\\The Notorious B.I.G.-Hip Hop & Rap _ WBLS Radio Show  - Thunder Storm Vol. 6.m4a.ytdl'

[download] Downloading video 23 of 24
[download] Hip Hop & Rap | WBLS Radio Show : Thunder Storm Vol. 3 has already been recorded in archive
[download] Downloading video 24 of 24
[youtube] CABG2nT4o34: Downloading webpage
[youtube] CABG2nT4o34: Downloading video info webpage
[youtube] {18} signature length 108, html5 player vflRqBT2o
[youtube] {137} signature length 108, html5 player vflRqBT2o
[youtube] {134} signature length 108, html5 player vflRqBT2o
[youtube] {140} signature length 108, html5 player vflRqBT2o
[youtube] CABG2nT4o34: Downloading MPD manifest
[info] Writing video description to: c:\Users\kanugu\Dropbox\leech_rip\leech\Monduba Crew-Hip Hop & Rap _ WBLS Radio Show  - Thunder Storm Vol. 5.description
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1559659937/ei/QTH2XNHdDYm11Abbl7iYCw/ip/103.6.150.109/id/080046da74f8a37e/source/youtube/requiressl/yes/playback_host/r1---sn-htgx20capj-npol.googlevideo.com/mm/31%2C29/mn/sn-htgx20capj-npol%2Csn-npoeenee/ms/au%2Crdu/mv/m/pl/24/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1877500/mt/1559638209/fvip/1/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Citag/sig/ALgxI2wwRAIgSNtmmR5bsrzal-uahdPTANA_8_6bM_u1WhQS7WLM1o4CIBVWTODKpYLQ-mPyl0e8i8-VTcTinmBEr1ywjbs8qNUm/lsparams/playback_host%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cinitcwndbps/lsig/AHylml4wRgIhAIZFFM1X1J_EKRc3zYIL1H0Qfa3jkXvx4X-Z58rWIGW7AiEA8a74ekl8u8djh-3HF867-9KhwJqk1qpH2bWvEHeDRTs%3D'
[download] Sleeping 68.44 seconds...
[dashsegments] Total fragments: 436
[download] Destination: c:\Users\kanugu\Dropbox\leech_rip\leech\Monduba Crew-Hip Hop & Rap _ WBLS Radio Show  - Thunder Storm Vol. 5.m4a
[download]  47.7% of ~67.19MiB at  6.44MiB/s ETA 00:12         ERROR: unable to download video data: [Errno 22] Invalid argument: 'c:\\Users\\kanugu\\Dropbox\\leech_rip\\leech\\Monduba Crew-Hip Hop & Rap _ WBLS Radio Show  - Thunder Storm Vol. 5.m4a.ytdl'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\YoutubeDL.py", line 1915, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\YoutubeDL.py", line 1854, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\downloader\dash.py", line 51, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\downloader\fragment.py", line 118, in _append_fragment
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\downloader\fragment.py", line 87, in _write_ytdl_file
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\utils.py", line 458, in sanitize_open
OSError: [Errno 22] Invalid argument: 'c:\\Users\\kanugu\\Dropbox\\leech_rip\\leech\\Monduba Crew-Hip Hop & Rap _ WBLS Radio Show  - Thunder Storm Vol. 5.m4a.ytdl'

[download] Finished downloading playlist: leech2
(base) PS C:\Users\kanugu\Dropbox\leech_rip>


```

## Description

A couple of songs in a playlist I'm downloading cause the download to fail mid-download  complaining that an argument is invalid.  This argument is being created by ytdl, and as far as I can see, the download actually starts and runs for a while before falling over. Ultimately the stacktrace throws an OSError: [Errno 22]

I'm running this on Windows 10 and downloading inside a dropbox directory.

**Comment by dstftw** [comment]
>downloading inside a dropbox directory

This is the answer.

**Comment by soilstack** [comment]
> > downloading inside a dropbox directory
> 
> This is the answer.

Curious what's the issue with dropbox? I've used the same configuration to download many things via this playlist.   This is the first time it's caused any problem.

(And to be clear, I am rerunning this same setup away from Dropbox and it does appear to be working now)

**Comment by corto11** [comment]
Today, I received this error while downloading and my local SSD hiccuped. The error happened at different download percentages. No dropbox involved. Once the SSD was stable, the failing command lines were successful.

**Comment by dirkf** [comment]
The problem with a DropBox (or probably OneDrive, etc) folder is that the DropBox (or whatever) syncing code may lock your output file while yt-dl is trying to open or write to or close it.

No doubt some similar effect could occur if an SSD unexpectedly became read-only.
