### ISSUE TITLE
bitchute.com support needs love ("Unable to extract uploader", "No video formats found")

### ISSUE THREAD

**Issue by betathetatau** [ytdl-org/youtube-dl#21306]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
E:\>youtube-dl -f best -i --verbose https://www.bitchute.com/video/xmKef247HY0U/ https://www.bitchute.com/video/mwymYCxrGUih/ https://www.bitchute.com/video/X1Hav9UIatLV/ https://www.bitchute.com/video/zshd1XefKWWA/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '-i', '--verbose', 'https://www.bitchute.com/video/xmKef247HY0U/', 'https://www.bitchute.com/video/mwymYCxrGUih/', 'https://www.bitchute.com/video/X1Hav9UIatLV/', 'https://www.bitchute.com/video/zshd1XefKWWA/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.4.4 (CPython) - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
[BitChute] xmKef247HY0U: Downloading webpage
[BitChute] xmKef247HY0U: Checking video URL
[BitChute] xmKef247HY0U: Checking video URL
WARNING: unable to extract uploader; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Invoking downloader on 'https://seed20.bitchute.com/9c7qJvwx7YQT/xmKef247HY0U.mp4'
[download] Destination: Who Gave Big Tech The Order To Ban Winnie The Pooh-xmKef247HY0U.mp4
[download] 100% of 49.59MiB in 03:51
[BitChute] mwymYCxrGUih: Downloading webpage
[BitChute] mwymYCxrGUih: Checking video URL
[BitChute] mwymYCxrGUih: Checking video URL
WARNING: unable to extract uploader; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Invoking downloader on 'https://seed07.bitchute.com/Qh3xOfty8ojs/mwymYCxrGUih.mp4'
[download] Destination: Kurdish SDF - PYD - Asaysih Militia Burn Wheat Fields in Qamishli - Caught on Camera-mwymYCxrGUih.mp4
[download] 100% of 585.03KiB in 00:03
[BitChute] X1Hav9UIatLV: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\extractor\bitchute.py", line 59, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\extractor\common.py", line 1326, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[BitChute] zshd1XefKWWA: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\extractor\bitchute.py", line 59, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\extractor\common.py", line 1326, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE
(1) youtube-dl seems to be unable to extract uploader names for all videos lately.
(2) youtube-dl recently appears to fail to download certain videos at all.
Verbose log gives two examples of each category. First two URLs are examples of videos youtube-dl can download but cannot extract the uploader for. Second two URLs are examples of videos youtube-dl cannot download at all. (In the second two URLs' HTML source, the full .mp4 URL is plainly visible, so this issue is probably just about the .mp4 URL being moved to an unexpected location in the HTML source for some videos.)

(Thank you all so much for this wonderful tool. You are saints and gurus.)

**Comment by betathetatau** [comment]
CORRECTION TO THE REPORT:

Please disregard videos X1Hav9UIatLV and zshd1XefKWWA in the verbose log output above (the two which youtube-dl returns "No video formats found").  I sincerely apologize: I was not careful enough in choosing them as examples.  They match previous closed bitchute.com issues, where the error's cause was determined to be bitchute.com simply not providing their MP4 URLs in their video URLs' HTML sources.

Instead of those two videos, please instead substitute https://www.bitchute.com/video/aoS3FfY2ADHL/.  That video URL's HTML source does include a verified-working MP4 URL, and yet youtube-dl still reports it cannot download it.  Verbose log:

E:\>youtube-dl -f best -i --verbose https://www.bitchute.com/video/aoS3FfY2ADHL/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '-i', '--verbose', 'https://www.bitchute.com/video/aoS3FfY2ADHL/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.4.4 (CPython) - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
[BitChute] aoS3FfY2ADHL: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\extractor\bitchute.py", line 59, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\extractor\common.py", line 1326, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Proof of MP4 URL in video URL HTML source:
https://images2.imgbox.com/27/81/TULPjN8x_o.png

Log of downloading it:
E:\>wget -U "" https://seed27.bitchute.com/RXA1oESUqP1c/aoS3FfY2ADHL.mp4
--2019-06-05 01:58:34--  https://seed27.bitchute.com/RXA1oESUqP1c/aoS3FfY2ADHL.mp4
Resolving seed27.bitchute.com... 107.150.59.234
Connecting to seed27.bitchute.com|107.150.59.234|:443... connected.
HTTP request sent, awaiting response... 200
Length: 48573234 (46M) [video/mp4]
Saving to: `aoS3FfY2ADHL.mp4'

Again, please forgive the error in my original report.
