### ISSUE TITLE
Executing JS failed,  Unknown option '--ssl-protocol=any'

### ISSUE THREAD

**Issue by jakkarth** [ytdl-org/youtube-dl#21335]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2019.06.08**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: [u'-f', u'best']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://ihavenotv.com/private-moonshot-breakthrough']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-146-generic-x86_64-with-LinuxMint-18.3-sylvia
[debug] exe versions: avconv 2.8.15, avprobe 2.8.15, ffmpeg 2.8.15, ffprobe 2.8.15, phantomjs 2019, rtmpdump 2.4
[debug] Proxy map: {}
[generic] private-moonshot-breakthrough: Requesting header
WARNING: Falling back on generic information extractor.
[generic] private-moonshot-breakthrough: Downloading webpage
[generic] private-moonshot-breakthrough: Extracting information
[download] Downloading playlist: Private Moonshot - Breakthrough
[generic] playlist Private Moonshot - Breakthrough: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[Openload] ZS2rUrAp3Ak: Downloading embed webpage
[Openload] ZS2rUrAp3Ak: Executing JS on webpage
ERROR: Executing JS failed
:2019-06-08T10:34:04 [FATAL] Unknown option '--ssl-protocol=any'
; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/jakkarth/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/jakkarth/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/jakkarth/bin/youtube-dl/youtube_dl/extractor/openload.py", line 1995, in _real_extract
    webpage = self._extract_decrypted_page(page_url, webpage, video_id, headers)
  File "/home/jakkarth/bin/youtube-dl/youtube_dl/extractor/openload.py", line 1968, in _extract_decrypted_page
    webpage, _ = phantom.get(page_url, html=webpage, video_id=video_id, headers=headers)
  File "/home/jakkarth/bin/youtube-dl/youtube_dl/extractor/openload.py", line 237, in get
    'Executing JS failed\n:' + encodeArgument(err))
ExtractorError: Executing JS failed
:2019-06-08T10:34:04 [FATAL] Unknown option '--ssl-protocol=any'
; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

On a variety of sites, downloading fails trying to execute JS. Looks like a possible bug in the way phantom is being executed on https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/openload.py#L231. I'm using phantomjs 2.1.1, which appears to be the latest, and its output suggests that it does not support an "--ssl-protocol" argument. However, since 2.1.1 was released quite some time ago, and to the best of my knowledge I haven't updated it recently, this seems like quite an odd problem to encounter. I'm not sure what to make of it.

**Comment by jakkarth** [comment]
I had two versions of phantomjs on my system apparently, and it was using the wrong one.
