### ISSUE TITLE
Error in downloading from youtube

### ISSUE THREAD

**Issue by diazepan** [ytdl-org/youtube-dl#21334]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

youtube-dl --verbose -f 18 https://www.youtube.com/watch?v=vgG0ao6kKSU
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', '18', 'https://www.youtube.com/watch?v=vgG0ao6kKSU']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Python version 3.7.3 (CPython) - Linux-5.1.7-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] vgG0ao6kKSU: Downloading webpage
[youtube] vgG0ao6kKSU: Downloading video info webpage
[debug] Invoking downloader on 'https://r3---sn-5ouxa-h8q6.googlevideo.com/videoplayback?expire=1560025812&ei=c8b7XPvrM4GuxgTgiKTwDw&ip=2800%3Aa4%3A27a8%3A2000%3Af2de%3Af1ff%3Afea9%3A4467&id=o-AAnCq9oImTar67WyZeNXvqNMY3d9Fp7D18OLxtRtr_HW&itag=18&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-5ouxa-h8q6%2Csn-hp57kn67&ms=au%2Crdu&mv=m&pl=28&pcm2=no&initcwndbps=516250&mime=video%2Fmp4&gir=yes&clen=6490812&ratebypass=yes&dur=107.531&lmt=1559769984113748&mt=1560004129&fvip=3&c=WEB&txp=4531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIgZ-jfU_tuY1H9hXMCahidvvc8Orcd8E6yvwv0FO0LP1sCIQDZRRxjN_u2DiKguc6GWTDTTV2aFCOhJPQDwbwRWunQHw%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhAIvnsLT3Eb6Rybg-YDqOCa_NvAOz0GGkjis84nV74iRdAiEAqduurt9Tt-V-nDHxh81sUlAHfSjwL94fRqgGSVIhkdw%3D'
ERROR: unable to download video data: urlopen error _ssl.c:1039: The handshake operation timed out
Traceback (most recent call last):
  File "/usr/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1039: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1915, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1854, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/site-packages/youtube_dl/utils.py", line 1140, in https_open
    req, **kwargs)
  File "/usr/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: urlopen error _ssl.c:1039: The handshake operation timed out

## Description

The process of downloading gets stuck in calling the "googlevideo.com/videoplayback" URL. It ends with timeout

**Comment by dstftw** [comment]
Network issue on your side.
