### ISSUE TITLE
[archive.org] "Unable to extract jwplayer playlist" and a traceback (Not a #7154 dupe)

### ISSUE THREAD

**Issue by timetimetimetime** [ytdl-org/youtube-dl#21330]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://archive.org/details/cnn200109110848-0929']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-93886-gfbdb3aa179, ffprobe N-93886-gfbdb3aa179
[debug] Proxy map: {}
[archive.org] cnn200109110848-0929: Downloading webpage
ERROR: Unable to extract jwplayer playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\extractor\archiveorg.py", line 45, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\extractor\common.py", line 1004, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract jwplayer playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Attempting to download https://archive.org/details/cnn200109110848-0929 . Having the issue shown above. This is not a #7154 dupe as I am not trying to download a collection.

**Comment by timetimetimetime** [comment]
Still occurs on 2019.06.08, but there is no traceback.
