### ISSUE TITLE
WinError 10060 on downloading particular video

### ISSUE THREAD

**Issue by EugeneLoy** [ytdl-org/youtube-dl#21346]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
(venv) C:\Users\Leo\courses>youtube-dl -v https://youtube.com/watch?v=mzHqve2RAAw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://youtube.com/watch?v=mzHqve2RAAw']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.06.08
[debug] Python version 3.7.0 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] mzHqve2RAAw: Downloading webpage
[youtube] mzHqve2RAAw: Downloading video info webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r2---sn-03guxaxjvh-3c2y.googlevideo.com/videoplayback?expire=1560099161&ei=-eT8XKnOD-Lx7ASt85LYAw&ip=46.203.183.63&id=o-AFE6LY-UsPrjhTOkOz1uYXmPveZaRkcZqhQONQ96aRa2&itag=22&source=youtube&requiressl=yes&mm=31&mn=sn-03guxaxjvh-3c2y&ms=au&mv=m&pl=20&initcwndbps=148750&mime=video%2Fmp4&ratebypass=yes&dur=246.479&lmt=1472342350029103&mt=1560077443&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIhAK68HinYi1USMQjOZHRQrlhoj-3bgFYJOBYaaYgRk0xgAiAB98eYhDkWtMSr91hPFG3EcnWvYkwupWFsRmR11CZZSQ%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgcK7RCn4APQOgspRkBApSxSNFuhkAWwj-Qyk7IFlxOHgCICIx4WRLWtwuxbZ3aIMAh8q6WG8bWy1CGE7rRRQY6uYe'
ERROR: unable to download video data: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Program Files\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Program Files\Python37\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Program Files\Python37\lib\http\client.py", line 1384, in connect
    super().connect()
  File "C:\Program Files\Python37\lib\http\client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Program Files\Python37\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Program Files\Python37\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\leo\courses\venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 1915, in process_info
    success = dl(filename, info_dict)
  File "c:\users\leo\courses\venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 1854, in dl
    return fd.download(name, info)
  File "c:\users\leo\courses\venv\lib\site-packages\youtube_dl\downloader\common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "c:\users\leo\courses\venv\lib\site-packages\youtube_dl\downloader\http.py", line 341, in real_download
    establish_connection()
  File "c:\users\leo\courses\venv\lib\site-packages\youtube_dl\downloader\http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "c:\users\leo\courses\venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Program Files\Python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Program Files\Python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Program Files\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\users\leo\courses\venv\lib\site-packages\youtube_dl\utils.py", line 1140, in https_open
    req, **kwargs)
  File "C:\Program Files\Python37\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
```

## Description

I am unable to download this video: https://youtube.com/watch?v=mzHqve2RAAw
This video is part of edx demo course and I am also having identical errors when downloading other videos uploaded by edx.

Downloading other videos, like this one works fine: https://www.youtube.com/watch?v=B8dgoUa05H8

**Comment by dstftw** [comment]
Network issue on your side.
