### ISSUE TITLE
Update server returns 500 / 503

### ISSUE THREAD

**Issue by legraphista** [ytdl-org/youtube-dl#21358]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--update', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.7.14 (CPython) - Linux-4.13.0-39-generic-x86_64-with-Ubuntu-17.10-artful
[debug] exe versions: none
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/update.py", line 45, in update_self
    newversion = opener.open(VERSION_URL).read().decode('utf-8').strip()
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error

```

## Description

A couple of our servers have a cron task to update youtube-dl every 12h `0 */12 * * * /usr/local/bin/youtube-dl --update -v`
We experience 503 errors at 00:00 and 500 errors at 12:00
The server's timezone is CEST (UTC+2) so we are experiencing the issues at 02:00 UTC and 14:00 UTC respectively

Some servers have a cron task to update every 24h at 00:00 UTC. 
Those servers constantly get 503 while trying to update 

**Note**:
- Manual updates work via `youtube-dl --update -v`

**Comment by dstftw** [comment]
There are some gaps in access log around these times so most likely web server is just overloaded with requests as everybody updates at round times. You should avoid such times in the first place.
/cc @phihag
