### ISSUE TITLE
Biqle unable to extract embed URL

### ISSUE THREAD

**Issue by omgold** [ytdl-org/youtube-dl#21364]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
> youtube-dl --verbose https://biqle.ru/watch/-57814407_456239424
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://biqle.ru/watch/-57814407_456239424']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.7.3 (CPython) - Linux-5.1.5-arch1-2-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[BIQLE] -57814407_456239424: Downloading webpage
ERROR: Unable to extract embed url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/biqle.py", line 46, in _real_extract
    webpage, 'embed url'))
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract embed url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Nothing to add to the above. For me it seems to be broken for any video URL.

**Comment by omgold** [comment]
@dstftw: sorry, somehow managed prematurely click the create button. Let me know if the report is still incomplete after the last edit.

**Comment by dstftw** [comment]
Adding new host to iframe is not enough.
```
> py -2.7 .\youtube_dl\__main__.py https://biqle.ru/watch/-57814407_456239424 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://biqle.ru/watch/-57814407_456239424', u'-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.06.08
[debug] Git HEAD: 427cc21
[debug] Python version 2.7.12 (CPython) - Windows-10-10.0.10240
[debug] exe versions: ffmpeg N-85653-gb4330a0, ffprobe N-85653-gb4330a0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[BIQLE] -57814407_456239424: Downloading webpage
[BIQLE] -57814407_456239424: Downloading webpage
[BIQLE] -57814407_456239424: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError(u'response',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Dev\youtube-dl\master\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "C:\Dev\youtube-dl\master\youtube_dl\extractor\biqle.py", line 60, in _real_extract
    })['response']['items'][0]
KeyError: u'response'
Traceback (most recent call last):
  File "C:\Dev\youtube-dl\master\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "C:\Dev\youtube-dl\master\youtube_dl\extractor\common.py", line 543, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'response',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by remitamine** [comment]
can't reproduce this error:
```
python __main__.py https://biqle.ru/watch/-57814407_456239424
[BIQLE] -57814407_456239424: Downloading webpage
[BIQLE] -57814407_456239424: Downloading webpage
[BIQLE] -57814407_456239424: Downloading JSON metadata
[download] Destination: Sports Car vs Racing Drone--57814407_456239424.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  3 51.6M    3 1806k    0     0   299k      0  0:02:56  0:00:06  0:02:50  363k
```

**Comment by lucadibello** [comment]
Same problem
