### ISSUE TITLE
youtube-dl error - site: https://www.tf1.fr/tf1/jt-20h/videos/20-heures-11-juin-2019.html

### ISSUE THREAD

**Issue by northpole360** [ytdl-org/youtube-dl#21368]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --verbose --postprocessor-args "-bsf:a aac_adtstoasc" https://www.tf1.fr/tf1/jt-20h/videos/20-heures-11-juin-2019.html
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--postprocessor-args', '-bsf:a aac_adtstoasc', 'https://www.tf1.fr/tf1/jt-20h/videos/20-heures-11-juin-2019.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.30
[debug] Python version 3.6.8 (CPython) - Linux-3.10.0-957.12.2.el7.x86_64-x86_64-with-centos-7.6.1810-Core
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15, phantomjs 2.1.1
[debug] Proxy map: {}
[TF1] 20-heures-11-juin-2019: Downloading webpage
ERROR: Unable to extract wat id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/tf1.py", line 53, in _real_extract
    webpage, 'wat id', group='id')
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 992, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

```

## Description

youtube_dl.utils.RegexNotFoundError: Unable to extract wat id;

**Comment by rems28** [comment]
Hello, why this bug is closed, I've the same issue with the last cersion
