### ISSUE TITLE
Video is unavailable

### ISSUE THREAD

**Issue by darealShadow** [ytdl-org/youtube-dl#21378]
youtube-dl -v -F https://www.youtube.com/watch?v=sKlA0A3ufpc
[debug] System config: [u'-o', u'/xxx/Temp/%(title)s.%(ext)s']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.youtube.com/watch?v=sK1A0A3ufpc'
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-9-amd64-x86_64-with-debian-9.9
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] sK1A0A3ufpc: Downloading webpage
[youtube] sK1A0A3ufpc: Downloading video info webpage
WARNING: Unable to extract video title
ERROR: This video is unavailable.
Traceback (most recent call last):
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
ie_result = ie.extract(url)
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
ie_result = self._real_extract(url)
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2077, in _real_extract
raise ExtractorError(error_message, expected=True)
ExtractorError: This video is unavailable.

**Comment by remitamine** [comment]
```
youtube-dl https://www.youtube.com/watch?v=sKlA0A3ufpc
[youtube] sKlA0A3ufpc: Downloading webpage
[youtube] sKlA0A3ufpc: Downloading video info webpage
[download] Destination: Luis Fonsi - Sola-sKlA0A3ufpc.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.5M  100 11.5M    0     0   348k      0  0:00:34  0:00:34 --:--:--  457k
[curl] Downloaded 12148676 bytes
[download] 100% of 11.59MiB in 00:34
```

**Comment by SecTec** [comment]
```
C:\Users\user> youtube-dl -v -F "https://www.youtube.com/watch?v=SJ0Sa0VgZLk"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.youtube.com/watch?v=SJ0Sa0VgZLk']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.07.14
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube] SJ0Sa0VgZLk: Downloading webpage
[youtube] SJ0Sa0VgZLk: Downloading video info webpage
[info] Available formats for SJ0Sa0VgZLk:
format code  extension  resolution note
249          webm       audio only DASH audio   54k , opus @ 50k, 1.08MiB
250          webm       audio only DASH audio   72k , opus @ 70k, 1.43MiB
171          webm       audio only DASH audio  126k , vorbis@128k, 2.67MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k, 2.84MiB
251          webm       audio only DASH audio  137k , opus @160k, 2.84MiB
394          mp4        256x144    144p   95k , av01.0.05M.08, 30fps, video only, 1.84MiB
278          webm       256x144    144p   98k , webm container, vp9, 30fps, video only, 2.04MiB
160          mp4        256x144    144p  112k , avc1.4d400c, 30fps, video only, 2.16MiB
242          webm       426x240    240p  223k , vp9, 30fps, video only, 4.45MiB
395          mp4        426x240    240p  234k , av01.0.05M.08, 30fps, video only, 4.08MiB
243          webm       640x360    360p  407k , vp9, 30fps, video only, 8.36MiB
133          mp4        426x240    240p  410k , avc1.4d4015, 30fps, video only, 5.97MiB
396          mp4        640x360    360p  423k , av01.0.05M.08, 30fps, video only, 7.28MiB
397          mp4        854x480    480p  737k , av01.0.05M.08, 30fps, video only, 12.80MiB
244          webm       854x480    480p  775k , vp9, 30fps, video only, 15.25MiB
134          mp4        640x360    360p  777k , avc1.4d401e, 30fps, video only, 12.81MiB
135          mp4        854x480    480p 1290k , avc1.4d401f, 30fps, video only, 20.32MiB
247          webm       1280x720   720p 1535k , vp9, 30fps, video only, 28.45MiB
398          mp4        1280x720   720p 1563k , av01.0.05M.08, 30fps, video only, 25.81MiB
136          mp4        1280x720   720p 1914k , avc1.4d401f, 30fps, video only, 29.38MiB
248          webm       1920x1080  1080p 2675k , vp9, 30fps, video only, 46.01MiB
137          mp4        1920x1080  1080p 2728k , avc1.640028, 30fps, video only, 43.81MiB
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k, 16.11MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 20.00MiB
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)
```

```
C:\Users\user> youtube-dl -v -F "https://www.youtube.com/watch?v=m0SSPeBT3VI"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.youtube.com/watch?v=m0SSPeBT3VI']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.07.14
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube] m0SSPeBT3VI: Downloading webpage
[youtube] m0SSPeBT3VI: Downloading video info webpage
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphq4ewlx_\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphq4ewlx_\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphq4ewlx_\build\youtube_dl\extractor\youtube.py", line 2109, in _real_extract
youtube_dl.utils.ExtractorError: This video is unavailable.
```
