### ISSUE TITLE
Error when "Merging formats"

### ISSUE THREAD

**Issue by rsfinlayson** [ytdl-org/youtube-dl#21389]
## Checklist

- [ x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.06.08**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v 'https://www.youtube.com/watch?v=NSeL5c65v-g'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=NSeL5c65v-g']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Python version 2.7.14 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] NSeL5c65v-g: Downloading webpage
[youtube] NSeL5c65v-g: Downloading video info webpage
WARNING: Unknown codec unknown
WARNING: Unknown codec unknown
WARNING: Unknown codec unknown
WARNING: Unknown codec unknown
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r6---sn-a5meknle.googlevideo.com/videoplayback?expire=1560480192&ei=YLUCXbDuIqXJkwawmpuwDw&ip=2001%3A470%3A82e9%3A0%3A3d38%3A2269%3A7f75%3Ad666&id=o-AEoQovq4hQwsUdJns3pGzwzXSLW26GkG_7K6uYjCei5I&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397&source=youtube&requiressl=yes&mm=31&mn=sn-a5meknle&ms=au&mv=m&pl=36&initcwndbps=426250&mime=video%2Fmp4&gir=yes&clen=56416183&dur=375.641&lmt=1560449001319961&mt=1560458479&keepalive=yes&c=WEB&txp=4535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIhAICTbVkmw5_NJ-wzIDS0QCchA4XC39UBbV4Feq0CvN5lAiBa1oGCxAWItQgLsuJV_M9PFMQxPPaY5EfNEI1WvGsfMw%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgZjzHHBKZWwfC92-0soqK-oGjw6oeAbXIlkmpbpvxP5ECIQDJ-o5Nnf5FieTHrsc5njf-oKWukoQWBFFFtxpWO67sEA%3D%3D&ratebypass=yes'
[download] How a Manhole Cover Became the Fastest Manmade Object Ever-NSeL5c65v-g.f137.mp4 has already been downloaded
[download] 100% of 53.80MiB
[debug] Invoking downloader on u'https://r6---sn-a5meknle.googlevideo.com/videoplayback?expire=1560480192&ei=YLUCXbDuIqXJkwawmpuwDw&ip=2001%3A470%3A82e9%3A0%3A3d38%3A2269%3A7f75%3Ad666&id=o-AEoQovq4hQwsUdJns3pGzwzXSLW26GkG_7K6uYjCei5I&itag=397&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397&source=youtube&requiressl=yes&mm=31&mn=sn-a5meknle&ms=au&mv=m&pl=36&initcwndbps=426250&mime=video%2Fmp4&gir=yes&clen=10679728&dur=375.641&lmt=1560456520660605&mt=1560458479&keepalive=yes&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIgCGapeS_KVtUTLIW38PgzqtbZS-m4dkCC22hBVaKqhu8CIQDoJ8WQ3SiRyGsbAqTB8g3e9k85jL483BaHYl0-Q4y4iQ%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgZjzHHBKZWwfC92-0soqK-oGjw6oeAbXIlkmpbpvxP5ECIQDJ-o5Nnf5FieTHrsc5njf-oKWukoQWBFFFtxpWO67sEA%3D%3D&ratebypass=yes'
[download] How a Manhole Cover Became the Fastest Manmade Object Ever-NSeL5c65v-g.f397.mp4 has already been downloaded
[download] 100% of 10.18MiB
[ffmpeg] Merging formats into "How a Manhole Cover Became the Fastest Manmade Object Ever-NSeL5c65v-g.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:How a Manhole Cover Became the Fastest Manmade Object Ever-NSeL5c65v-g.f137.mp4' -i 'file:How a Manhole Cover Became the Fastest Manmade Object Ever-NSeL5c65v-g.f397.mp4' -c copy -map '0:v:0' -map '1:a:0' 'file:How a Manhole Cover Became the Fastest Manmade Object Ever-NSeL5c65v-g.temp.mp4'
ERROR: To ignore this, add a trailing '?' to the map.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2054, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: To ignore this, add a trailing '?' to the map.
```

## Description

youtube-dl fails when "Merging format", leaving two separate video (not video+audio) files, and displaying:
ERROR: To ignore this, add a trailing '?' to the map.
I'm not sure what "the map" is; however adding a trailing '?' to the URL did not solve the problem.

**Comment by rsfinlayson** [comment]
Please don't add a "duplicate" label without noting which specific issue this is is supposedly a duplicate of.
