### ISSUE TITLE
Crunchyroll Playlist Download Error

### ISSUE THREAD

**Issue by FoxMcloud5655** [ytdl-org/youtube-dl#21388]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
D:\Videos\Downloaded>youtube-dl.exe --merge-output-format mkv --ffmpeg-location ffmpeg\bin --cache-dir "cache" --download-archive downloaded.txt --fixup warn --add-metadata --sub-lang enUS --write-sub --cookies cookies.txt -a download.txt -o "%(uploader)s/%(title)s.%(ext)s" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--merge-output-format', 'mkv', '--ffmpeg-location', 'ffmpeg\\bin', '--cache-dir', 'cache', '--download-archive', 'downloaded.txt', '--fixup', 'warn', '--add-metadata', '--sub-lang', 'enUS', '--write-sub', '--cookies', 'cookies.txt', '-a', 'download.txt', '-o', '%(uploader)s/%(title)s.%(ext)s', '--verbose']
[debug] Batch file urls: ['https://www.crunchyroll.com/that-time-i-got-reincarnated-as-a-slime', 'https://www.crunchyroll.com/my-hero-academia', 'https://www.crunchyroll.com/black-clover', 'https://www.crunchyroll.com/overlord']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.06.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2, rtmpdump 2.3
[debug] Proxy map: {}
[crunchyroll:playlist] that-time-i-got-reincarnated-as-a-slime: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\extractor\crunchyroll.py", line 666, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\extractor\common.py", line 1014, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Attempting to download files from a playlist on Crunchyroll results in an error.  Not 100% sure if it's something I am doing wrong or not, but it was working fine the last time I used this exact script a couple of weeks ago.  Usually, updating youtube-dl fixes this particular issue.

Downloading individual files works fine, it's just playlists that do not work.

**Comment by FoxMcloud5655** [comment]
Didn't think to search for specifically the title extractor; my fault.
