### ISSUE TITLE
ffmpeg ERROR: To ignore this, add a trailing '?' to the map

### ISSUE THREAD

**Issue by buzo-ffm** [ytdl-org/youtube-dl#21382]
```
$ youtube-dl -v --playlist-end 2 https://www.youtube.com/channel/UC_F8DoJf9MZogEOU51TpTbQ/videos
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--playlist-end', '2', 'https://www.youtube.com/channel/UC_F8DoJf9MZogEOU51TpTbQ/videos']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Python version 3.7.3 (CPython) - Linux-5.1.9-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:channel] UC_F8DoJf9MZogEOU51TpTbQ: Downloading channel page
[youtube:playlist] UU_F8DoJf9MZogEOU51TpTbQ: Downloading webpage
[download] Downloading playlist: Uploads from Clash Royale
[youtube:playlist] playlist Uploads from Clash Royale: Downloading 2 videos
[download] Downloading video 1 of 2
[youtube] zMrVcQveaTY: Downloading webpage
[youtube] zMrVcQveaTY: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Clash Royale - Connect All Of Your Supercell Games With Supercell ID!-zMrVcQveaTY.mkv has already been downloaded and merged
[download] Downloading video 2 of 2
[youtube] 1-2hO6c1FdY: Downloading webpage
[youtube] 1-2hO6c1FdY: Downloading video info webpage
WARNING: Unknown codec unknown
WARNING: Unknown codec unknown
WARNING: Unknown codec unknown
WARNING: Unknown codec unknown
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r5---sn-4g5ednz7.googlevideo.com/videoplayback?expire=1560453681&ei=0U0CXfzvJsiW1gLxvq0I&ip=2a02%3A908%3A191%3A3a00%3A438d%3Ae526%3A61d3%3Aee97&id=o-AA8nHZOxjytT-W1xfAEOZd7W1GbrDDp60t5Kb6x4XnxT&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-4g5ednz7%2Csn-2gb7sn7s&ms=au%2Conr&mv=m&pl=33&initcwndbps=1662500&mime=video%2Fmp4&gir=yes&clen=43468530&dur=289.120&lmt=1558272613753090&mt=1560431802&fvip=6&keepalive=yes&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIhANtP8NhGNtTB4iJhXC-eV29oai84EXIpb0h-o5duzcSBAiBnBWYcrBO8XTpsIW6fwGJg-mPIXTfhocVe8T5lLysCgA%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgbuDThBo77isgKlXaNM3-lmXWk15JZ1i8MHj8vOB9y4oCIQCe9dTvtxPCQlS3ma2nyV6qwf-RB5TjlCxNMEeVYjNWcQ%3D%3D&ratebypass=yes'
[download] Clash Royale - Creating a Card - Goblin Cage! (Behind the Scenes Interviews)-1-2hO6c1FdY.f137.mp4 has already been downloaded
[download] 100% of 41.45MiB
[debug] Invoking downloader on 'https://r5---sn-4g5ednz7.googlevideo.com/videoplayback?expire=1560453681&ei=0U0CXfzvJsiW1gLxvq0I&ip=2a02%3A908%3A191%3A3a00%3A438d%3Ae526%3A61d3%3Aee97&id=o-AA8nHZOxjytT-W1xfAEOZd7W1GbrDDp60t5Kb6x4XnxT&itag=397&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-4g5ednz7%2Csn-2gb7sn7s&ms=au%2Conr&mv=m&pl=33&initcwndbps=1662500&mime=video%2Fmp4&gir=yes&clen=13385229&dur=289.120&lmt=1558277566967096&mt=1560431802&fvip=6&keepalive=yes&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIhAJR-gKVnoUgL6udyeyXjiJsgwp6dFjfJycVALj560wN5AiA_jpr9zj0t0DDbu8c5GROEcgiGsqkL_bCKLWIqX0NzaA%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgbuDThBo77isgKlXaNM3-lmXWk15JZ1i8MHj8vOB9y4oCIQCe9dTvtxPCQlS3ma2nyV6qwf-RB5TjlCxNMEeVYjNWcQ%3D%3D&ratebypass=yes'
[download] Clash Royale - Creating a Card - Goblin Cage! (Behind the Scenes Interviews)-1-2hO6c1FdY.f397.mp4 has already been downloaded
[download] 100% of 12.77MiB
[ffmpeg] Merging formats into "Clash Royale - Creating a Card - Goblin Cage! (Behind the Scenes Interviews)-1-2hO6c1FdY.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Clash Royale - Creating a Card - Goblin Cage! (Behind the Scenes Interviews)-1-2hO6c1FdY.f137.mp4' -i 'file:Clash Royale - Creating a Card - Goblin Cage! (Behind the Scenes Interviews)-1-2hO6c1FdY.f397.mp4' -c copy -map 0:v:0 -map 1:a:0 'file:Clash Royale - Creating a Card - Goblin Cage! (Behind the Scenes Interviews)-1-2hO6c1FdY.temp.mp4'
ERROR: To ignore this, add a trailing '?' to the map.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2054, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/lib/python3.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/lib/python3.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: To ignore this, add a trailing '?' to the map.

$ youtube-dl --version
2019.06.08
```

**Comment by buzo-ffm** [comment]
```
$ ffmpeg -version
ffmpeg version n4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181127
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
libavutil      56. 22.100 / 56. 22.100
libavcodec     58. 35.100 / 58. 35.100
libavformat    58. 20.100 / 58. 20.100
libavdevice    58.  5.100 / 58.  5.100
libavfilter     7. 40.101 /  7. 40.101
libswscale      5.  3.100 /  5.  3.100
libswresample   3.  3.100 /  3.  3.100
libpostproc    55.  3.100 / 55.  3.100
```
