### ISSUE TITLE
BitChute: No video formats found

### ISSUE THREAD

**Issue by mnn** [ytdl-org/youtube-dl#21400]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl 'https://www.bitchute.com/video/vvG7ICfsgbD4/' -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.bitchute.com/video/vvG7ICfsgbD4/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-150-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15, rtmpdump 2.4
[debug] Proxy map: {}
[BitChute] vvG7ICfsgbD4: Downloading webpage
[BitChute] vvG7ICfsgbD4: Checking video URL
[BitChute] vvG7ICfsgbD4: video URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bitchute.py", line 64, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Video plays in browser (Firefox 67), but cannot be downloaded. Tried multiple times.

**Comment by mtilbury** [comment]
Attempting to download via the [video source](https://seed21.bitchute.com/mGyHAnGhlnPX/vvG7ICfsgbD4.mp4) shows a cert error. A workaround would be to use the `--no-check-certificate` flag.

```youtube-dl https://seed21.bitchute.com/mGyHAnGhlnPX/vvG7ICfsgbD4.mp4
[generic] vvG7ICfsgbD4: Requesting header
WARNING: Could not send HEAD request to https://seed21.bitchute.com/mGyHAnGhlnPX/vvG7ICfsgbD4.mp4: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)>
[generic] vvG7ICfsgbD4: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
(env3) root@DESKTOP-RLQDPT8:/mnt/c/Users/mtilbury/Documents/Programming/youtube-dl# youtube-dl https://seed21.bitchute.com/mGyHAnGhlnPX/vvG7ICfsgbD4.mp4 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://seed21.bitchute.com/mGyHAnGhlnPX/vvG7ICfsgbD4.mp4', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Git HEAD: b85eae0f0
[debug] Python version 3.6.7 (CPython) - Linux-4.4.0-17763-Microsoft-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[generic] vvG7ICfsgbD4: Requesting header
WARNING: Could not send HEAD request to https://seed21.bitchute.com/mGyHAnGhlnPX/vvG7ICfsgbD4.mp4: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)>
[generic] vvG7ICfsgbD4: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
  File "/mnt/c/Users/mtilbury/Documents/Programming/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/mnt/c/Users/mtilbury/Documents/Programming/youtube-dl/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/mnt/c/Users/mtilbury/Documents/Programming/youtube-dl/youtube_dl/utils.py", line 1140, in https_open
    req, **kwargs)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)```

**Comment by mnn** [comment]
The flag works, thank you. Maybe this issue should be closed, since it looks like an issue with BitChute itself?
