### ISSUE TITLE
[dailymotion] User page regex modifications

### ISSUE THREAD

**Issue by limechord** [ytdl-org/youtube-dl#21415]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
m@bogon:~/y/youtube-dl$ ./youtube-dl https://www.dailymotion.com/bloomberg --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.dailymotion.com/bloomberg', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Git HEAD: 7c24a58bd
[debug] Python version 3.7.3 (CPython) - Linux-4.18.0-3-amd64-x86_64-with-debian-10.0
[debug] exe versions: ffmpeg 4.1.3-1, ffprobe 4.1.3-1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion:user] bloomberg: Downloading webpage
ERROR: Unable to extract user; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/m/y/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/m/y/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/m/y/youtube-dl/youtube_dl/extractor/dailymotion.py", line 486, in _real_extract
    webpage, 'user'))
  File "/home/m/y/youtube-dl/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/m/y/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract user; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

## Description

It seems that dailymotion changed its html page for user page so that `_html_search_regex` doesn't work anymore.

**Comment by TheFrenchGhosty** [comment]
Dailymotion user pages are stuff broken with youtube-dl version 2019.09.12.1
