### ISSUE TITLE
Can't download private playlists on youtube

### ISSUE THREAD

**Issue by BarbzYHOOL** [ytdl-org/youtube-dl#21436]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--extract-audio', u'--audio-format', u'mp3', u'--output', u'%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', u'--ignore-errors', u'--download-archive', u'/home/user/.config/youtube-dlg/.already_downloaded_list', u'https://www.youtube.com/watch?v=CfIMqJJAsvw&list=PLVaI0CTqZ5gwUA-1ctuJ05tt6ooV48eg-&index=1', u'-v', u'--username', u'PRIVATE']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Python version 2.7.6 (CPython) - Linux-3.13.0-139-generic-x86_64-with-Zorin-9-trusty
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6
[debug] Proxy map: {}
[youtube:playlist] Downloading login page
[youtube:playlist] Looking up account info
[youtube:playlist] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube:playlist] Downloading playlist PLVaI0CTqZ5gwUA-1ctuJ05tt6ooV48eg- - add --no-playlist to just download video CfIMqJJAsvw
[youtube:playlist] PLVaI0CTqZ5gwUA-1ctuJ05tt6ooV48eg-: Downloading webpage
ERROR: This playlist is private, use --username or --netrc to access it.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2670, in _real_extract
    has_videos, playlist = self._extract_playlist(playlist_id)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2593, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist is private, use --username or --netrc to access it.

```

## Description
Just wanted to backup this issue https://github.com/ytdl-org/youtube-dl/issues/20913

I got this too.

Note: i already tried years ago and also couldn't download from private playlists on youtube. Seems like it never worked for me :'(

**Comment by BarbzYHOOL** [comment]
@dstftw hmm to be fair, I just realized the issue I linked is for "toutv" and not "youtube" so it's different
