### ISSUE TITLE
This video is not available: QFIP7Wm_S_Q

### ISSUE THREAD

**Issue by xiaose** [ytdl-org/youtube-dl#21435]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PS C:\...> .\youtube_dl.exe --version
2019.06.08

PS C:\...> .\youtube_dl.exe --verbose https://www.youtube.com/watch?v=QFIP7Wm_S_Q                         
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=QFIP7Wm_S_Q']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.06.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-93129-g9e1e521393, ffprobe N-92435-g759589b55e
[debug] Proxy map: {}
[youtube] QFIP7Wm_S_Q: Downloading webpage
[youtube] QFIP7Wm_S_Q: Downloading video info webpage
ERROR: This video is not available.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\extractor\youtube.py", line 2077, in _real_extract
youtube_dl.utils.ExtractorError: This video is not available.
```

This video playable in browser. And really it's not available outside of US but for US no problem to play it. But youtube_dl all time tells me: "This video is not available" as in US as outside, for example, in Ukraine...

**Comment by dstftw** [comment]
Most likely you must authenticate.

**Comment by xiaose** [comment]
Well, how? 

I can see this video in US in browser, cannot in Ukraine but youtube_dl gives me an error as in US as in UA

**Comment by xiaose** [comment]
Again, my IP is: 204.152.207.194 this is US. 
In browser I can see this video.
but in terminal I cannot download it:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'QFIP7Wm_S_Q']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.06.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-93129-g9e1e521393, ffprobe N-92435-g759589b55e
[debug] Proxy map: {}
[youtube] QFIP7Wm_S_Q: Downloading webpage
[youtube] QFIP7Wm_S_Q: Downloading video info webpage
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\extractor\youtube.py", line 2077, in _real_extract
youtube_dl.utils.ExtractorError: This video is unavailable.
```
