### ISSUE TITLE
site support/feature request: tvnow.de/filme/

### ISSUE THREAD

**Issue by SeppSpenderRind** [ytdl-org/youtube-dl#21455]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Downloading movies from URLs starting with "www.tvnow.de/filme/" does not work.
Example:
```
youtube-dl https://www.tvnow.de/filme/pokemon-14-weiss-victini-und-zekrom-17225 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.tvnow.de/filme/pokemon-14-weiss-victini-und-zekrom-17225', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.06.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 3.4.2, ffprobe N-81741-g1212e34
[debug] Proxy map: {}
[generic] pokemon-14-weiss-victini-und-zekrom-17225: Requesting header
WARNING: Falling back on generic information extractor.
[generic] pokemon-14-weiss-victini-und-zekrom-17225: Downloading webpage
[generic] pokemon-14-weiss-victini-und-zekrom-17225: Extracting information
ERROR: Unsupported URL: https://www.tvnow.de/filme/pokemon-14-weiss-victini-und-zekrom-17225
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\extractor\generic.py", line 3316, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.tvnow.de/filme/pokemon-14-weiss-victini-und-zekrom-17225
```

Alternatively, there's no problem using the manifest URL of the same video:
`youtube-dl https://vodnowusodash-a.akamaihd.net/proxy195/clear/manifest/tvnow/1637947-1-19060.ism/.mpd`

Note: Content on tvnow.de in general may be geo-blocked outside of Germany.

**Comment by AlvoErrado2** [comment]
This movie: https://www.tvnow.de/filme/she-creature-der-todesengel-aus-der-tiefe-15907 can be viewed for free, but it presents this error at the time of download, besides the fact it is divided into chapters.

`youtube-dl.exe "https://www.tvnow.de/filme/she-creature-der-todesengel-aus-der-tiefe-15907" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.tvnow.de/filme/she-creature-der-todesengel-aus-der-tiefe-15907', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.04.30
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-92906-g54109b1d14, ffprobe N-92906-g54109b1d14, rtmpdump 2.4
[debug] Proxy map: {}
[generic] she-creature-der-todesengel-aus-der-tiefe-15907: Requesting header
WARNING: Falling back on generic information extractor.
[generic] she-creature-der-todesengel-aus-der-tiefe-15907: Downloading webpage
[generic] she-creature-der-todesengel-aus-der-tiefe-15907: Extracting information
ERROR: Unsupported URL: https://www.tvnow.de/filme/she-creature-der-todesengel-aus-der-tiefe-15907
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\extractor\generic.py", line 3320, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.tvnow.de/filme/she-creature-der-todesengel-aus-der-tiefe-15907`

**Comment by TinyToweringTree** [comment]
Pull request #22364 fixes this.

@AlvoErrado2 unfortunately the movie you linked is DRM protected and will not be supported.

**Comment by 89z** [comment]
Issue should be closed, URL is dead
