### ISSUE TITLE
[DouyuTV] - ExtractorError

### ISSUE THREAD

**Issue by ana-ka** [ytdl-org/youtube-dl#21468]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\annaka>youtube-dl https://www.douyu.com/255865 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.douyu.com/255865', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.06.08
[debug] Python version 2.7.16 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[DouyuTV] 255865: Downloading room info
ERROR: 255865: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 899, in _parse_json
    return json.loads(json_string)
  File "c:\python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "c:\python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\douyutv.py", line 88, in _real_extract
    note='Downloading room info')['data']
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 892, in _download_json
    expected_status=expected_status)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 876, in _download_json_handle
    fatal=fatal), urlh
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 903, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: 255865: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Douyu livestreams always fail with an ExtractorError as down above. I've checked for old issues but could only find ones with different causes. Douyu did not work for quite some while now but unfortunately I cannot tell since when exactly. It is just now that I decided to finally file an issue.

Note that the stream I used above might not be online when you decide to check it. But really any Douyu-stream should (not) work. If you need any more info, let me know.

**Comment by wearfears** [comment]
I have the same issue with 2019.07.02
