### ISSUE TITLE
[youtube] ERROR: unable to download video data: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by Alcaro** [ytdl-org/youtube-dl#21483]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2019.06.21**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ignore-config', u'-fbest', u'https://www.youtube.com/watch?v=1sdF1poRIPw', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2019.06.21
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-52-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 1sdF1poRIPw: Downloading webpage
[youtube] 1sdF1poRIPw: Downloading video info webpage
[debug] Invoking downloader on u'https://r6---sn-c5ioiv45c-hhme.googlevideo.com/videoplayback?expire=1561160641&ei=YRcNXdvtGpOHyQXNzpHgDg&ip=79.136.64.93&id=o-ACoAwN_Wodxw3EScXBKOPGbn7NPuURfdm9CHr_NX61Xl&itag=22&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-c5ioiv45c-hhme%2Csn-c5ioiv45c-5gol&ms=au%2Crdu&mv=m&pl=24&initcwndbps=1972500&mime=video%2Fmp4&ratebypass=yes&dur=3638.497&lmt=1533363498888378&mt=1561138893&fvip=8&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRAIgKdxiS4cpbl86XGCF3arbj1I5shK_wBtbW8UM3y-OFNQCIE6qkaDa66uG451WFyP7An49bxlHVJBtIg4NNhsQA6uw&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhAM0_D8kxK9fq3UT4h8zImSijX65aMwbCLocHlZuEXIyrAiEAk0CG_4zxTbUAkqgxlf5jsycO32FVHXeYbJjg2I6jmxA%3D'
[download] Destination: טוטיטו בעברית ברצף _ צעצועים לילדים למשחק ביתי-1sdF1poRIPw.mp4

[download]   0.0% of 252.68MiB at 178.98KiB/s ETA 24:20
[download]   0.0% of 252.68MiB at 495.78KiB/s ETA 08:44
[download]   0.0% of 252.68MiB at  1.07MiB/s ETA 03:57
[download]   0.0% of 252.68MiB at  2.18MiB/s ETA 01:56
[download]   0.0% of 252.68MiB at 933.37KiB/s ETA 04:37
[download]   0.0% of 252.68MiB at 905.55KiB/s ETA 04:45
[download]   0.0% of 252.68MiB at  1.17MiB/s ETA 03:35
[download]   0.1% of 252.68MiB at  1.26MiB/s ETA 03:19
[download]   0.2% of 252.68MiB at  1.21MiB/s ETA 03:29
[download]   0.4% of 252.68MiB at  1.28MiB/s ETA 03:17
[download]   0.6% of 252.68MiB at  1.11MiB/s ETA 03:46[download] Got server HTTP error: Downloaded 1671003 bytes, expected 264949747 bytes. Retrying (attempt 1 of 10)...
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1915, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1854, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found


```

## Description

`youtube-dl -fbest https://www.youtube.com/watch?v=1sdF1poRIPw` fails with some weird HTTP error. -fbestvideo+bestaudio works.

Originally reported by ytdlusr on IRC.

**Comment by dstftw** [comment]
Server side Youtube issue.
