### ISSUE TITLE
Some video cannot be downloaded.

### ISSUE THREAD

**Issue by zfdev** [ytdl-org/youtube-dl#21489]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.06.21**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\Administrator>youtube-dl --verbose --proxy socks5://127.0.0.1:10808 https://www.youtube.com/watch?v=B8igPU-MYQs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--proxy', 'socks5://127.0.0.1:10808', 'https://www.youtube.com/watch?v=B8igPU-MYQs']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dl version 2019.06.08
[debug] Python version 3.6.5 (CPython) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg N-93016-gb8ebce4f84, ffprobe N-93016-gb8ebce4f84
[debug] Proxy map: {'http': 'socks5://127.0.0.1:10808', 'https': 'socks5://127.0.0.1:10808'}
[youtube] B8igPU-MYQs: Downloading webpage
[youtube] B8igPU-MYQs: Downloading video info webpage
[youtube] {18} signature length 104, html5 player vfl49f_g4
[youtube] B8igPU-MYQs: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vfl49f_g4/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1986, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1352, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

First of all, the [video](https://www.youtube.com/watch?v=B8igPU-MYQs) is available. I can see it through the browser. It seems like the Youtube downloader can't extract the information of the video correctly.
I try to call the extract_info to debug the information of the video. It returns null.

`  with YoutubeDL(self.ydl_opts) as ydl:
            try:
                self.logger.info('start downloading, url - %s' % (self.url))
                info_dict = ydl.extract_info(self.url, download=False)
                print(json.dumps(info_dict, indent=4))
`

**Comment by e-dt** [comment]
I'm having the same problem on this video: https://www.youtube.com/watch?v=dN3GbF9Bx6E

**Comment by hejops** [comment]
Same problem on this video: https://www.youtube.com/watch?v=xEmMabF_IKI

**Comment by kenogo** [comment]
>  I've verified that I'm running youtube-dl version 2019.06.21

> 2019.06.08

I've had the same issue as you but updating just fixed it, and it's as simple as "sudo youtube-dl -U"

**Comment by zfdev** [comment]
I just found the updated version 2019.06.21 yesterday. 
Resolve the issue by `pip install --upgrade youtube-dl`.
Thanks all.

**Comment by AllOgreTheWorld** [comment]
This is correct. Using command `pip install --upgrade youtube-dl` will actually update the program. Instructions say to use `sudo -H pip install --upgrade youtube-dl` but that gives a response of `Requirement already up-to-date: youtube-dl in /usr/local/lib/python2.7/dist-packages`
