### ISSUE TITLE
7Plus (Australia) - "No video formats found"

### ISSUE THREAD

**Issue by section83** [ytdl-org/youtube-dl#21496]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2019.06.21**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

Not all videos are affected.  This is an example of the error:

youtube-dl -v https://7plus.com.au/mighty-trains?episode-id=MTRA01-002
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://7plus.com.au/mighty-trains?episode-id=MTRA01-002']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3-tessus, ffprobe 4.1.3-tessus
[debug] Proxy map: {}
[7plus] MTRA01-002: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/sevenplus.py", line 61, in _real_extract
    info = self._parse_brightcove_metadata(media, episode_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 680, in _parse_brightcove_metadata
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


This is an example of a video which works:

youtube-dl -v https://7plus.com.au/airport-247?episode-id=AIRP01-001
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://7plus.com.au/airport-247?episode-id=AIRP01-001']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.21
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3-tessus, ffprobe 4.1.3-tessus
[debug] Proxy map: {}
[7plus] AIRP01-001: Downloading JSON metadata
[7plus] AIRP01-001: Downloading m3u8 information
[7plus] AIRP01-001: Downloading MPD manifest
[7plus] AIRP01-001: Downloading MPD manifest
[7plus] AIRP01-001: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://manifest.prod.boltdns.net/manifest/v1/hls/v5/aes128/5303576322001/ba29acb8-843c-414c-917c-d102cc10b5d9/ec99b0d8-6244-4e1f-9684-be1d612bc25e/10s/rendition.m3u8?fastly_token=NWQwZWVkZGFfYzAxY2ViMjQ1ZmI1NmZiNzk3NTA2N2I3NjE5MTA4Yjk4OTA1M2Q4OTBkNjlhMDY4YWNiMGNlMWZkYzI1NWVlNg%3D%3D'
[hlsnative] Downloading m3u8 manifest
WARNING: hlsnative has detected features it does not support, extraction will be delegated to ffmpeg
[download] Destination: Season 1 Episode 1-AIRP01-001.fhls-1786.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
' -i 'https://manifest.prod.boltdns.net/manifest/v1/hls/v5/aes128/5303576322001/ba29acb8-843c-414c-917c-d102cc10b5d9/ec99b0d8-6244-4e1f-9684-be1d612bc25e/10s/rendition.m3u8?fastly_token=NWQwZWVkZGFfYzAxY2ViMjQ1ZmI1NmZiNzk3NTA2N2I3NjE5MTA4Yjk4OTA1M2Q4OTBkNjlhMDY4YWNiMGNlMWZkYzI1NWVlNg%3D%3D' -c copy -f mp4 'file:Season 1 Episode 1-AIRP01-001.fhls-1786.mp4.part'
ffmpeg version 4.1.3-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.1 (clang-1001.0.46.3)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[tcp @ 0x7fab4fe004c0] Starting connection attempt to 151.101.30.27 port 443

[Stopped download when clear it was working]

```

## Description

Have been able to DL these videos in the past.  Now, I get the error.  I am within Australia so, geo-blocking is not an issue.  Some videos work but others do not.  Could this be a DRM issue ?

**Comment by Carlz10** [comment]
Fellow Aussie here - I can replicate with your two examples. 
I started having this issue with a series on BBC yesterday too, where I was resuming a partially downloaded file, so I know it worked the day before so I assume its DRM related :(

**Comment by appleton-tom** [comment]
Playing through the browser won't work for me, black screen with these messages.
Seems to confirm DRM

DRM: LICENSE_REQUEST_FAILED
Error Code: LICENSE_REQUEST_FAILED
Session ID: 2019-06-23:b6be9e0f3f8c76bd7bca377f Player Element ID:player

**Comment by WolfganP** [comment]
Same happened with tenplay a couple of days ago https://github.com/ytdl-org/youtube-dl/issues/21450
