### ISSUE TITLE
FFmpegPostProcessorError

### ISSUE THREAD

**Issue by RangaSE** [ytdl-org/youtube-dl#21494]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
youtube-dl[2019.06.08] --merge-output-format mp4 -ci --no-playlist -f "bestvideo+bestaudio/best[ext=mp4]/best" --write-auto-sub --write-sub --embed-thumbnail -o "D:\Downloads\%(title)s (u%(upload_date)s; %(duration)s; %(height)sp%(fps)s)YT '%(uploader)s'.%(ext)s" -- xvU3UghOhCY
[youtube] xvU3UghOhCY: Downloading webpage
[youtube] xvU3UghOhCY: Downloading video info webpage
[youtube] Downloading just video xvU3UghOhCY because of --no-playlist
[youtube] xvU3UghOhCY: Looking for automatic captions
[info] Writing video subtitles to: D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.en.vtt
[youtube] xvU3UghOhCY: Downloading thumbnail ...
[youtube] xvU3UghOhCY: Writing thumbnail to: D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.jpg
[download] Destination: D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.f313.webm
[download] 100% of 1.26GiB in 29:29
[download] Destination: D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.f251.webm
[download] 100% of 8.38MiB in 00:10
[ffmpeg] Merging formats into "D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.mp4"
ERROR:   Stream #1:0 -> #0:1 (copy)
[atomicparsley] Adding thumbnail to "D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.mp4"
ERROR: AtomicParsley error: can't open D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.mp4 for reading: No such file or directory

< 22-06-2019 & 13:09:11.70 | C:\Users\admin> Cls
I was surprised see this and then I checked for solution; found the update of YouTube-DL, downloaded it and (with '-v') ...
< 22-06-2019 & 19:07:06.14 | C:\Users\admin> youtube-dl[2019.06.21] --merge-output-format mp4 -ci --no-playlist -f "bestvideo+bestaudio/best[ext=mp4]/best" --write-auto-sub --write-sub --embed-thumbnail -o "D:\Downloads\%(title)s (u%(upload_date)s; %(duration)s; %(height)sp%(fps)s)YT '%(uploader)s'.%(ext)s" -v -- xvU3UghOhCY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--merge-output-format', 'mp4', '-ci', '--no-playlist', '-f', 'bestvideo+bestaudio/best[ext=mp4]/best', '--write-auto-sub', '--write-sub', '--embed-thumbnail', '-o', "D:\\Downloads\\%(title)s (u%(upload_date)s; %(duration)s; %(height)sp%(fps)s)YT '%(uploader)s'.%(ext)s", '-v', '--', 'xvU3UghOhCY']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.06.21
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[youtube] xvU3UghOhCY: Downloading webpage
[youtube] xvU3UghOhCY: Downloading video info webpage
[youtube] Downloading just video xvU3UghOhCY because of --no-playlist
[youtube] xvU3UghOhCY: Looking for automatic captions
[info] Writing video subtitles to: D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.en.vtt
[youtube] xvU3UghOhCY: Downloading thumbnail ...
[youtube] xvU3UghOhCY: Writing thumbnail to: D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.jpg
[debug] Invoking downloader on 'https://r5---sn-cnoa-h55l.googlevideo.com/videoplayback?expire=1561232959&ei=3zEOXdvXFY2J3LUPrfmk-Ag&ip=117.193.155.142&id=o-AJsdLNFGHI-X8cr-Z94HloGzR9SzRBdVDkfP0-wz_qgd&itag=313&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-cnoa-h55l%2Csn-npoeenek&ms=au%2Conr&mv=m&pl=20&initcwndbps=308750&mime=video%2Fwebm&gir=yes&clen=1348487223&dur=641.166&lmt=1541031664484429&mt=1561211208&fvip=3&keepalive=yes&c=WEB&txp=5532432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRAIgaWXESQxj9w6Twzpnfq78mWQDs04W-SLC0smhoDiplVECID5xNjhkT5Ubb4piXDLfrUr61p4xGM36RpySnUbaCLi7&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgAJZoSX13gPcKNEXi7jt_miZhxcOgE8pP5ciSJN3K2aYCIQD4FgNsr4KuOI-df80eED6HDImIt11gDHREZtGlNjlYhg%3D%3D&ratebypass=yes'
[download] D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.f313.webm has already been downloaded
[download] 100% of 1.26GiB
[debug] Invoking downloader on 'https://r5---sn-cnoa-h55l.googlevideo.com/videoplayback?expire=1561232959&ei=3zEOXdvXFY2J3LUPrfmk-Ag&ip=117.193.155.142&id=o-AJsdLNFGHI-X8cr-Z94HloGzR9SzRBdVDkfP0-wz_qgd&itag=251&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-cnoa-h55l%2Csn-npoeenek&ms=au%2Conr&mv=m&pl=20&initcwndbps=308750&mime=audio%2Fwebm&gir=yes&clen=8782036&dur=641.181&lmt=1541035357348052&mt=1561211208&fvip=3&keepalive=yes&c=WEB&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIhAIm7f-Wki1t6AGs1ktUF6Ok7RuNAOG7woMDQ9iEA0EHxAiAE-WC3KB3j2vMAYx0yO-iYAs1vSKewBfXAp9LIoBcRqQ%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgAJZoSX13gPcKNEXi7jt_miZhxcOgE8pP5ciSJN3K2aYCIQD4FgNsr4KuOI-df80eED6HDImIt11gDHREZtGlNjlYhg%3D%3D&ratebypass=yes'
[download] D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.f251.webm has already been downloaded
[download] 100% of 8.38MiB
[ffmpeg] Merging formats into "D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.f313.webm" -i "file:D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.temp.mp4"
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_g4\build\youtube_dl\YoutubeDL.py", line 2054, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_g4\build\youtube_dl\postprocessor\ffmpeg.py", line 512, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_g4\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)

[atomicparsley] Adding thumbnail to "D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.mp4"
[debug] AtomicParsley command line: AtomicParsley "D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.mp4" --artwork "D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.jpg" -o "D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.temp.mp4"
ERROR: AtomicParsley error: can't open D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.mp4 for reading: No such file or directory
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_g4\build\youtube_dl\YoutubeDL.py", line 2054, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_g4\build\youtube_dl\postprocessor\embedthumbnail.py", line 79, in run
youtube_dl.postprocessor.embedthumbnail.EmbedThumbnailPPError: AtomicParsley error: can't open D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.mp4 for reading: No such file or directory

< 22-06-2019 & 19:19:24.95 | C:\Users\admin> Exit
... got the same result('--verbose' or '-v' listing still confuses me.). My FFlpeg is Version 4.1.3 (Latest Stable Version.). Am I missing something? Enlighten me, please.

**Comment by RangaSE** [comment]
!!SOLVED!! Greetings! I just changed to "bestaudio[ext=m4a]" from "bestaudio" and it works without a hitch. Thanks A Lot!! (still I di'nt know this.)
