### ISSUE TITLE
TLC GO downloads report a youtube_dl.utils.RegexNotFoundError Error

### ISSUE THREAD

**Issue by NormanMeowcat** [ytdl-org/youtube-dl#21510]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2019.06.21**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.tlcgo.com/tv-shows/i-am-jazz/full-episodes/the-final-countdown?', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.06.21
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-92906-g54109b1d14
[debug] Proxy map: {}
[debug] Using fake IP 3.9.154.198 (US) as X-Forwarded-For.
[DiscoveryGo] the-final-countdown: Downloading webpage
ERROR: Unable to extract video container; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_g4\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_g4\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_g4\build\youtube_dl\extractor\discoverygo.py", line 124, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_g4\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video container; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

When I try to download a Episode from tlcgo.com since tlc.com no longer works it just asks me to make sure i updated saying Unable to extract video container error. It didn't request any Login Information to attempt to start downloading however it does to view the video on the site . It works perfectly in the browser. if it doesn't have a lock on it using tlc.com starts the download so is tlc.com broken?

**Comment by merval** [comment]
I have the same issue, I downloaded the source and made a few changes to get the webpage output that youtube-dl is pulling down. The main problem is we're not authenticating, the page youtube-dl gets back says the episode is locked and you need to sign in. The second problem is, when I sign on a browser and inspect the page, the regex used to find the video-container doesn't match anything.
The last several comments on Issue #11257 cover this.
