### ISSUE TITLE
Youtube-DL python package overriding OS file unlock method

### ISSUE THREAD

**Issue by FabianNiehaus** [ytdl-org/youtube-dl#21545]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.06.27**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

As this is not an issue with youtube-dl's functionality itself, but rather it's interaction with another package, there is no log to be provided.

The following error is thrown when trying to store a file using the [Django Framework](https://www.djangoproject.com/) while the youtube_dl package is installed:
<br>
```python
Internal Server Error: /
Traceback (most recent call last):
  File "<<Project base directory removed for privacy>>\venv\lib\site-packages\django\core\files\move.py", line 61, in file_move_safe
    locks.lock(fd, locks.LOCK_EX)
  File "<<Project base directory removed for privacy>>\venv\lib\site-packages\django\core\files\locks.py", line 80, in lock
    ret = LockFileEx(hfile, flags, 0, 0, 0xFFFF0000, byref(overlapped))
ctypes.ArgumentError: argument 6: <class 'TypeError'>: expected LP_OVERLAPPED instance instead of pointer to OVERLAPPED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<<Project base directory removed for privacy>>\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "<<Project base directory removed for privacy>>\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "<<Project base directory removed for privacy>>\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "<<Project base directory removed for privacy>>\GenreClassificationWeb\webClassification\views.py", line 29, in upload
    name = fs.save(uploaded_file.name, uploaded_file)
  File "<<Project base directory removed for privacy>>\venv\lib\site-packages\django\core\files\storage.py", line 52, in save
    return self._save(name, content)
  File "<<Project base directory removed for privacy>>\venv\lib\site-packages\django\core\files\storage.py", line 261, in _save
    file_move_safe(content.temporary_file_path(), full_path)
  File "<<Project base directory removed for privacy>>\venv\lib\site-packages\django\core\files\move.py", line 67, in file_move_safe
    locks.unlock(fd)
  File " <<Project Directory>>\venv\lib\site-packages\django\core\files\locks.py", line 86, in unlock
    ret = UnlockFileEx(hfile, 0, 0, 0xFFFF0000, byref(overlapped))
ctypes.ArgumentError: argument 5: <class 'TypeError'>: expected LP_OVERLAPPED instance instead of pointer to OVERLAPPED
```

## Description

When trying to store a file using the FileSystemStorage.save() method in the Django Framework, the afromentioned exceptions is thrown upon unlocking the newly stored file using the OS unlock function in locks.py.

 Removing the youtube_dl package does immediately resolve this issue. Sadly, youtube-dl is necessary for this project due to a lack of working cross-platform alternatives.

This issue has been recreated with a Windows 10 and a Windows 7 machine using different VENVs.

I do believe this is a bug and have cross-posted a ticket with the Django Project (https://code.djangoproject.com/ticket/30603)

**Comment by baldoarturo** [comment]
I can confirm this happens only on windows systems

**Comment by Motiph** [comment]
any solution for this?

still happening in windows 10 with django 3

**Comment by shadowstriker15** [comment]
Yeah, having this issue as well...

**Comment by JeffreyCA** [comment]
I ended up just forking this repo and commented out this section of code: https://github.com/JeffreyCA/youtube-dl/commit/e97aade949c205e203c6b8bb1ca335c2f6b6b4ff. Not the best workaround but it works for my use case.

**Comment by Grub4K** [comment]
Bug can be reproduced with the following code:
```py
from django.core.files import locks

import yt_dlp.utils  # or youtube_dl

with open("./file", "w") as f:
    locks.lock(f, locks.LOCK_EX)
```
This happens since both django and ydl(p) mutate the global `windll.kernel32` instance.
This patch solves it:
```diff
diff --git a/yt_dlp/utils.py b/yt_dlp/utils.py
index 15e1f97cb..458239a12 100644
--- a/yt_dlp/utils.py
+++ b/yt_dlp/utils.py
@@ -2106,7 +2106,7 @@ class OVERLAPPED(ctypes.Structure):
             ('hEvent', ctypes.wintypes.HANDLE),
         ]

-    kernel32 = ctypes.windll.kernel32
+    kernel32 = ctypes.WinDLL('kernel32')
     LockFileEx = kernel32.LockFileEx
     LockFileEx.argtypes = [
         ctypes.wintypes.HANDLE,     # hFile
```

I have reported this bug to django ([Ticket](https://code.djangoproject.com/ticket/34294)) as well.
