### ISSUE TITLE
UnboundLocalError: local variable 'info_json_url' referenced before assignment

### ISSUE THREAD

**Issue by slackline** [ytdl-org/youtube-dl#21552]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.06.27**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
 youtube-dl --verbose "https://soundcloud.com/the-spirit-train/lotus-imane-live-afrikaburn-2019-wednesday-15h00-16h00-the-spirit-train" -o "Afrikaburn 2019 The Spirit Train - Lotus Imane.mp3"
[debug] System config: []
[debug] User config: ['--no-mtime', '--restrict-filenames', '--write-thumbnail', '--prefer-ffmpeg', '--audio-format', 'mp3', '--audio-quality', '0']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://soundcloud.com/the-spirit-train/lotus-imane-live-afrikaburn-2019-wednesday-15h00-16h00-the-spirit-train', '-o', 'Afrikaburn 2019 The Spirit Train - Lotus Imane.mp3']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.21
[debug] Python version 3.6.8 (CPython) - Linux-5.1.14-gentoo-x86_64-Intel-R-_Core-TM-_i7-6700_CPU_@_3.40GHz-with-gentoo-2.6
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[soundcloud] the-spirit-train/lotus-imane-live-afrikaburn-2019-wednesday-15h00-16h00-the-spirit-train: Downloading webpage
WARNING: Unable to download webpage: HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/youtube-dl", line 11, in <module>
    load_entry_point('youtube-dl==2019.6.21', 'console_scripts', 'youtube-dl')()
  File "/usr/lib64/python3.6/site-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2008, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/soundcloud.py", line 446, in _real_extract
    info_json_url, full_title, 'Downloading info JSON')
UnboundLocalError: local variable 'info_json_url' referenced before assignment
```

## Description

Similar to #21546 where the user is using Python 2.7.16 which also reports `500: Internal Server Error`, however I'm using Python 3.6.8 and have a different error.  

I updated to 2019.06.27 this morning and this error occurred, youtube-dl worked fine yesterday with 2019.06.21 yesterday but having reverted version the same error occurs with both suggesting to me something has changed elsewhere (perhaps server side) to cause this bug.

**Comment by slackline** [comment]
@dstftw : Is this a duplicate of #21546 or another issue?
