### ISSUE TITLE
Soundcloud unable to download songs

### ISSUE THREAD

**Issue by MrJoeSchmo** [ytdl-org/youtube-dl#21560]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.06.27**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://soundcloud.com/marshmellomusic/marshmello-x-sob-x-rbe-roll-the-dice?in=soundcloud-the-peak/sets/edm-crossovers', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.06.27
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[soundcloud] marshmellomusic/marshmello-x-sob-x-rbe-roll-the-dice: Downloading webpage
WARNING: Unable to download webpage: HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjzs7t34q\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjzs7t34q\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjzs7t34q\build\youtube_dl\YoutubeDL.py", line 2008, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjzs7t34q\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjzs7t34q\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjzs7t34q\build\youtube_dl\extractor\soundcloud.py", line 446, in _real_extract
UnboundLocalError: local variable 'info_json_url' referenced before assignment
```

## Description

I receive this error on any Soundcloud track I attempt to download, whether or not it is in a playlist. This started recently as I was able to download from Soundcloud earlier without issue.

**Comment by MrJoeSchmo** [comment]
@dstftw Can you point me to the similar issue I must have missed? I tried searching for Soundcloud issues but they all were very outdated at this point.
