### ISSUE TITLE
Disney Junior on Disney Now

### ISSUE THREAD

**Issue by vipul128** [ytdl-org/youtube-dl#21567]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.06.27**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', 'G:\\youtube-dl\\ffmpeg\\bin', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--batch-file', 'G:\\youtube-dl\\downloadlist.txt', '-v']
[debug] Batch file urls: ['https://disneynow.com/shows/handy-manny/season-01/episode-01-stretchs-cookies-page-turner/vdka0_qx1vxdv9']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.06.27
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-94129-g098ab93257, ffprobe N-94129-g098ab93257
[debug] Proxy map: {}
[Go] vdka0_qx1vxdv9: Downloading webpage
[Go] vdka0_qx1vxdv9: Downloading JSON metadata
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjzs7t34q\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjzs7t34q\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjzs7t34q\build\youtube_dl\YoutubeDL.py", line 2008, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjzs7t34q\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjzs7t34q\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjzs7t34q\build\youtube_dl\extractor\go.py", line 116, in _real_extract
IndexError: list index out of range
```

## Description

Trying to download files from Disney Junior and I'm getting the error above.  Everything worked fine about 1 month ago and now I'm getting this error.  Other sites like NickJr have no issue and will download fine.  I've made sure to update to the latest version as well.  Please assist if possible.

**Comment by vipul128** [comment]
I tried both a working Comcast Xfinity and Directv account without success. I also tried the cookie method without success. Credentials are correct because they work with NickJr. I don't understand the tag added to this question when I have infact used a TV provider account. Please explain if possible. Thanks for all you do!

**Comment by dstftw** [comment]
This means you must provide credentials for any work on this.

**Comment by bencollinz** [comment]
I'm having this exact same issue as well over the last 2 months. Have updated to newest version, tried other computers, tried gui, all the same. Disney Jr doesn't work.

**Comment by vipul128** [comment]
Just updated to version 2019.07.12 and the Disney Jr stuff is working properly again.  Thanks for fixing it even though I never provided the credentials!  You guys rock!
