### ISSUE TITLE
500: Soundcloud doesn't work.

### ISSUE THREAD

**Issue by mattjis** [ytdl-org/youtube-dl#21563]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.06.27**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose https://soundcloud.com/knxwledge/irealliwant

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://soundcloud.com/knxwledge/irealliwant']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.27
[debug] Python version 2.7.16 (CPython) - Darwin-19.0.0-x86_64-i386-64bit
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] knxwledge/irealliwant: Downloading webpage
WARNING: Unable to download webpage: HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2008, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/soundcloud.py", line 446, in _real_extract
UnboundLocalError: local variable 'info_json_url' referenced before assignment
```

## Description

Quite a few people reported this issue 14 hours ago, but they've all been closed and marked as either `Solved` or `Duplicate`. Does the update take a while because it's definitely still broken for me on the latest version `youtube-dl is up-to-date (2019.06.27)`.

**Comment by bitraid** [comment]
The fix  (f7a147e) is 14 hours old. You have to wait for a new release, or apply the patch yourself.

**Comment by anhphidiep** [comment]
We have testing soundcloud cant playing

**Comment by MrJoeSchmo** [comment]
@mattjis Thanks for putting this up. I was wondering when/where this was addressed after I put up my own duplicate issue unintentionally.

**Comment by josephecombs** [comment]
brew uninstall youtube-dl && brew install youtube-dl --HEAD
