### ISSUE TITLE
Soundcloud issues

### ISSUE THREAD

**Issue by LuigiTheHunter** [ytdl-org/youtube-dl#21583]
# Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2019.06.27**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://soundcloud.com/foxstevenson/killjoy-1', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.27
[debug] Python version 3.6.8 (CPython) - Linux-4.15.0-54-generic-x86_64-with-elementary-5.0-juno
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] foxstevenson/killjoy-1: Downloading webpage
WARNING: Unable to download webpage: HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "/home/phil/.local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/home/phil/.local/lib/python3.6/site-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/home/phil/.local/lib/python3.6/site-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/phil/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2008, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/phil/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/phil/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/phil/.local/lib/python3.6/site-packages/youtube_dl/extractor/soundcloud.py", line 446, in _real_extract
    info_json_url, full_title, 'Downloading info JSON')
UnboundLocalError: local variable 'info_json_url' referenced before assignment
```

## Description

I have tried so far three different Users on Soundcloud and also various tracks. When I try to download from a User I get this different error:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://soundcloud.com/dualistic', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.27
[debug] Python version 3.6.8 (CPython) - Linux-4.15.0-54-generic-x86_64-with-elementary-5.0-juno
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud:user] dualistic: Downloading user info
ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/phil/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/phil/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```
Thanks.

**Comment by LuigiTheHunter** [comment]
Sorry, I searched for it but did not find any other issue.

**Comment by bitraid** [comment]
Did you search closed issues as the checkbox you marked suggests?
> I've searched the bugtracker for similar issues including closed ones

**Comment by LuigiTheHunter** [comment]
Ahh no my fault. Sorry. Thanks for clearing this up.

**Comment by LuigiTheHunter** [comment]
I don't get this can't find the corresponding issue. I found one not marked as duplicate and marked as fixed 3 days ago but it is still not working. Will this mean there will be no soundcloud support in the future? Or it is TBD?

**Comment by bitraid** [comment]
The fix is on master but it's not released yet. Either wait for the new release or run from git.

**Comment by LuigiTheHunter** [comment]
Ah thanks got it :)
