### ISSUE TITLE
disneynow.com updated URL

### ISSUE THREAD

**Issue by gthrift** [ytdl-org/youtube-dl#21613]
Disney has updated its url from disneynow.go.com to disneynow.com.  I see some references to the new urls in go.py but I am getting the below errors.   

I am also using a custom mso that has not been merged in, please let me know how I can share the provider credentials privately for testing if needed.

```
    'ATT': {
        'name': 'AT&T U-Verse',
        'username_field': 'userid',
        'password_field': 'password'
    },
    'ATT2': {
        'name': 'AT&T U-Verse',
        'username_field': 'nameBox',
        'password_field': 'pwdBox',
    },
```

```
C:\Users\NetworkAdmin>pip install --upgrade youtube-dl
Requirement already up-to-date: youtube-dl in c:\users\networkadmin\appdata\local\programs\python\python37\lib\site-packages (2019.7.2)
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

```

**Using ATT MSO**
```
C:\Users\NetworkAdmin>youtube-dl --ffmpeg-location C:/ffmpeg/bin --ap-mso ATT2 --ap-username *********@att.net --ap-password ********* -f "[height=720]" -o H:/Downloads/%(title)s-%(id)s.%(ext)s https://disneynow.com/shows/vampirina/season-02/episode-10-big-bite-ghost/vdka10820631 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', 'C:/ffmpeg/bin', '--ap-mso', 'ATT2', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-f', '[height=720]', '-o', 'H:/Downloads/%(title)s-%(id)s.%(ext)s', 'https://disneynow.com/shows/vampirina/season-02/episode-10-big-bite-ghost/vdka10820631', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.07.02
[debug] Python version 3.7.3 (CPython) - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg N-93784-ge25bddf5fc, ffprobe N-93784-ge25bddf5fc
[debug] Proxy map: {}
[Go] vdka10820631: Downloading webpage
[Go] vdka10820631: Downloading JSON metadata
Traceback (most recent call last):
  File "c:\users\networkadmin\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\networkadmin\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\NetworkAdmin\AppData\Local\Programs\Python\Python37\Scripts\youtube-dl.exe\__main__.py", line 9, in <module>
  File "c:\users\networkadmin\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\__init__.py", line 474, in main
    _real_main(argv)
  File "c:\users\networkadmin\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "c:\users\networkadmin\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 2008, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "c:\users\networkadmin\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\networkadmin\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\users\networkadmin\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\go.py", line 116, in _real_extract
    video_data = self._extract_videos(brand, video_id)[0]
IndexError: list index out of range

```
**Using ATT2 MSO**
```
C:\Users\NetworkAdmin>youtube-dl --ffmpeg-location C:/ffmpeg/bin --ap-mso ATT --ap-username *********@att.net --ap-password ********* -f "[height=720]" -o H:/Downloads/%(title)s-%(id)s.%(ext)s https://disneynow.com/shows/vampirina/season-02/episode-10-big-bite-ghost/vdka10820631 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', 'C:/ffmpeg/bin', '--ap-mso', 'ATT', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-f', '[height=720]', '-o', 'H:/Downloads/%(title)s-%(id)s.%(ext)s', 'https://disneynow.com/shows/vampirina/season-02/episode-10-big-bite-ghost/vdka10820631', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.07.02
[debug] Python version 3.7.3 (CPython) - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg N-93784-ge25bddf5fc, ffprobe N-93784-ge25bddf5fc
[debug] Proxy map: {}
[Go] vdka10820631: Downloading webpage
[Go] vdka10820631: Downloading JSON metadata
Traceback (most recent call last):
  File "c:\users\networkadmin\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\networkadmin\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\NetworkAdmin\AppData\Local\Programs\Python\Python37\Scripts\youtube-dl.exe\__main__.py", line 9, in <module>
  File "c:\users\networkadmin\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\__init__.py", line 474, in main
    _real_main(argv)
  File "c:\users\networkadmin\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "c:\users\networkadmin\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 2008, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "c:\users\networkadmin\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\networkadmin\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\users\networkadmin\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\go.py", line 116, in _real_extract
    video_data = self._extract_videos(brand, video_id)[0]
IndexError: list index out of range
```

**Comment by dstftw** [comment]
You must provide credentials for any work on this.

**Comment by gthrift** [comment]
> You must provide credentials for any work on this.

How can credentials be provided confidentially?
