### ISSUE TITLE
sxyprn.com does not work for ubuntu but works for mac os

### ISSUE THREAD

**Issue by botzill** [ytdl-org/youtube-dl#21610]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

This is working on my mac os machine
```
youtube-dl https://sxyprn.com/cdn6/c9/g1d7p8qzo1d8iz74m2pzg104o5g/Izu3wS9vm3dkzgTcNRTU1Q/1562052497/e5ia2e5bf0sdb1scb07ak803s2j/fj56dk15a6dx9u5zeidp6dch0i1.mp4 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://sxyprn.com/cdn6/c9/g1d7p8qzo1d8iz74m2pzg104o5g/Izu3wS9vm3dkzgTcNRTU1Q/1562052497/e5ia2e5bf0sdb1scb07ak803s2j/fj56dk15a6dx9u5zeidp6dch0i1.mp4', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.02
[debug] Python version 3.7.2 (CPython) - Darwin-17.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] fj56dk15a6dx9u5zeidp6dch0i1: Requesting header
[redirect] Following redirect to https://c9.trafficdeposit.com/video/g1d7p8qzo1d8iz74m2pzg104o5g/Izu3wS9vm3dkzgTcNRTU1Q/1562052497/5aeb0d1c0a832/5d1ad95ed6c01.mp4
[generic] 5d1ad95ed6c01: Requesting header
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://c9.trafficdeposit.com/video/g1d7p8qzo1d8iz74m2pzg104o5g/Izu3wS9vm3dkzgTcNRTU1Q/1562052497/5aeb0d1c0a832/5d1ad95ed6c01.mp4'
[download] Destination: 5d1ad95ed6c01-5d1ad95ed6c01.mp4
[download]   4.9% of 279.26MiB at 724.07KiB/s ETA 06:15
```

This does not work on ubuntu:
```
youtube-dl https://sxyprn.com/cdn6/c9/g1d7p8qzo1d8iz74m2pzg104o5g/Izu3wS9vm3dkzgTcNRTU1Q/1562052497/e5ia2e5bf0sdb1scb07ak803s2j/fj56dk15a6dx9u5zeidp6dch0i1.mp4 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://sxyprn.com/cdn6/c9/g1d7p8qzo1d8iz74m2pzg104o5g/Izu3wS9vm3dkzgTcNRTU1Q/1562052497/e5ia2e5bf0sdb1scb07ak803s2j/fj56dk15a6dx9u5zeidp6dch0i1.mp4', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.02
[debug] Python version 3.7.3 (CPython) - Linux-4.15.0-52-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.1.3-0york1, ffprobe 4.1.3-0york1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] fj56dk15a6dx9u5zeidp6dch0i1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] fj56dk15a6dx9u5zeidp6dch0i1: Downloading webpage
WARNING: URL could be a direct video link, returning it as such.
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://sxyprn.com/cdn6/c9/g1d7p8qzo1d8iz74m2pzg104o5g/Izu3wS9vm3dkzgTcNRTU1Q/1562052497/e5ia2e5bf0sdb1scb07ak803s2j/fj56dk15a6dx9u5zeidp6dch0i1.mp4'


ERROR: Did not get any data blocks
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 2008, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 861, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 1642, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 1915, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 1854, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/downloader/http.py", line 342, in real_download
    return download()
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/downloader/http.py", line 312, in download
    self.report_error('Did not get any data blocks')
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/downloader/common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 586, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

Not sure what is the issue. Could there be a better explanation of the error? Is this because IP banned?  

Thx!

**Comment by dstftw** [comment]
You must use original URL.

**Comment by botzill** [comment]
Well, the same is for original url.

**Comment by botzill** [comment]
Here is what I get
```
youtube-dl https://sxyprn.com/post/5d19f7bb859d0.html -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://sxyprn.com/post/5d19f7bb859d0.html', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.02
[debug] Python version 3.7.3 (CPython) - Linux-4.15.0-52-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.1.3-0york1, ffprobe 4.1.3-0york1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[YourPorn] 5d19f7bb859d0: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://sxyprn.com/cdn5/c11/nv1p3k4fzb28069szc2k416gzy2e0l9/Y7p1GIojXU3nv_rzxeUaIw/1562063995/1h59b2d8850kb5e16kdw1k4007d/hb5wd91o91f87nbbb58r5c9dd50.mp4'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 1915, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 1854, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by botzill** [comment]
@dstftw Can you check the update I did?

Thx a lot.
