### ISSUE TITLE
Bandcamp – ERROR: No video formats found

### ISSUE THREAD

**Issue by quinncomendant** [ytdl-org/youtube-dl#21615]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://fourtet.bandcamp.com/album/new-energy']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.02
[debug] Python version 3.7.3 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[Bandcamp:album] new-energy: Downloading webpage
[download] Downloading playlist: New Energy
[Bandcamp:album] playlist New Energy: Collected 14 video ids (downloading 14 of them)
[download] Downloading video 1 of 14
[Bandcamp] alap: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bandcamp.py", line 196, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Downloading an album from Bandcamp fails with the error, `No video formats found`.

**Comment by dstftw** [comment]
This is expected behavior, track 1 does not have any formats.

**Comment by quinncomendant** [comment]
Track 1 doesn't have any files linked, but tracks 2, 6, 9, and 14 have files available. youtube-dl should be able to download those, and just ignore the tracks without files. Here's the `trackinfo` json from [the album page](https://fourtet.bandcamp.com/album/new-energy):

```json
[
    {
        "alt_link": null,
        "has_info": false,
        "video_source_id": null,
        "track_num": 1,
        "encoding_error": null,
        "is_downloadable": false,
        "streaming": null,
        "license_type": 1,
        "video_id": null,
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "private": null,
        "play_count": 0,
        "lyrics": null,
        "free_album_download": false,
        "video_caption": null,
        "title_link": "/track/alap",
        "id": 2064962617,
        "track_license_id": null,
        "is_capped": false,
        "is_draft": false,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "has_lyrics": false,
        "file": null,
        "track_id": 2064962617,
        "video_source_type": null,
        "duration": 81.7807,
        "encodings_id": 1968388805,
        "title": "Alap"
    },
    {
        "alt_link": null,
        "has_info": false,
        "video_source_id": null,
        "track_num": 2,
        "encoding_error": null,
        "is_downloadable": true,
        "streaming": 1,
        "license_type": 1,
        "video_id": null,
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "private": null,
        "play_count": 0,
        "lyrics": null,
        "free_album_download": false,
        "video_caption": null,
        "title_link": "/track/two-thousand-and-seventeen-2",
        "id": 403175781,
        "track_license_id": null,
        "is_capped": false,
        "is_draft": false,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "has_lyrics": false,
        "file": {
            "mp3-128": "https://t4.bcbits.com/stream/e858ff7a52628bc5743f37be9f097d99/mp3-128/403175781?p=0&ts=1562266458&t=4108c53bd012d234b7730e97a1ef6d816891b895&token=1562266458_e38e4d7102572abbf584ef74aaf00e3bf3fdea53"
        },
        "track_id": 403175781,
        "video_source_type": null,
        "duration": 252.256,
        "encodings_id": 849657207,
        "title": "Two Thousand And Seventeen"
    },
    {
        "alt_link": null,
        "has_info": false,
        "video_source_id": null,
        "track_num": 3,
        "encoding_error": null,
        "is_downloadable": false,
        "streaming": null,
        "license_type": 1,
        "video_id": null,
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "private": null,
        "play_count": 0,
        "lyrics": null,
        "free_album_download": false,
        "video_caption": null,
        "title_link": "/track/la-trance",
        "id": 2186323319,
        "track_license_id": null,
        "is_capped": false,
        "is_draft": false,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "has_lyrics": false,
        "file": null,
        "track_id": 2186323319,
        "video_source_type": null,
        "duration": 347.394,
        "encodings_id": 2783715802,
        "title": "LA Trance"
    },
    {
        "alt_link": null,
        "has_info": false,
        "video_source_id": null,
        "track_num": 4,
        "encoding_error": null,
        "is_downloadable": false,
        "streaming": null,
        "license_type": 1,
        "video_id": null,
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "private": null,
        "play_count": 0,
        "lyrics": null,
        "free_album_download": false,
        "video_caption": null,
        "title_link": "/track/tremper",
        "id": 3103892097,
        "track_license_id": null,
        "is_capped": false,
        "is_draft": false,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "has_lyrics": false,
        "file": null,
        "track_id": 3103892097,
        "video_source_type": null,
        "duration": 89.4026,
        "encodings_id": 2312242952,
        "title": "Tremper"
    },
    {
        "alt_link": null,
        "has_info": false,
        "video_source_id": null,
        "track_num": 5,
        "encoding_error": null,
        "is_downloadable": false,
        "streaming": null,
        "license_type": 1,
        "video_id": null,
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "private": null,
        "play_count": 0,
        "lyrics": null,
        "free_album_download": false,
        "video_caption": null,
        "title_link": "/track/lush",
        "id": 102322080,
        "track_license_id": null,
        "is_capped": false,
        "is_draft": false,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "has_lyrics": false,
        "file": null,
        "track_id": 102322080,
        "video_source_type": null,
        "duration": 311.893,
        "encodings_id": 1157262000,
        "title": "Lush"
    },
    {
        "alt_link": null,
        "has_info": false,
        "video_source_id": null,
        "track_num": 6,
        "encoding_error": null,
        "is_downloadable": true,
        "streaming": 1,
        "license_type": 1,
        "video_id": null,
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "private": null,
        "play_count": 0,
        "lyrics": null,
        "free_album_download": false,
        "video_caption": null,
        "title_link": "/track/scientists",
        "id": 3118170780,
        "track_license_id": null,
        "is_capped": false,
        "is_draft": false,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "has_lyrics": false,
        "file": {
            "mp3-128": "https://t4.bcbits.com/stream/048cae984fa1de2e8e5258f97dc79f9b/mp3-128/3118170780?p=0&ts=1562266458&t=43d35cfcace77f5b1704a2e1c098c32fe2ac7a7c&token=1562266458_0ed88f784533258a48a6ee0a9614a002ba1e363f"
        },
        "track_id": 3118170780,
        "video_source_type": null,
        "duration": 299.305,
        "encodings_id": 3517806124,
        "title": "Scientists"
    },
    {
        "alt_link": null,
        "has_info": false,
        "video_source_id": null,
        "track_num": 7,
        "encoding_error": null,
        "is_downloadable": false,
        "streaming": null,
        "license_type": 1,
        "video_id": null,
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "private": null,
        "play_count": 0,
        "lyrics": null,
        "free_album_download": false,
        "video_caption": null,
        "title_link": "/track/falls-2",
        "id": 3964215394,
        "track_license_id": null,
        "is_capped": false,
        "is_draft": false,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "has_lyrics": false,
        "file": null,
        "track_id": 3964215394,
        "video_source_type": null,
        "duration": 72.1676,
        "encodings_id": 4030793345,
        "title": "Falls 2"
    },
    {
        "alt_link": null,
        "has_info": false,
        "video_source_id": null,
        "track_num": 8,
        "encoding_error": null,
        "is_downloadable": false,
        "streaming": null,
        "license_type": 1,
        "video_id": null,
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "private": null,
        "play_count": 0,
        "lyrics": null,
        "free_album_download": false,
        "video_caption": null,
        "title_link": "/track/you-are-loved",
        "id": 624077491,
        "track_license_id": null,
        "is_capped": false,
        "is_draft": false,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "has_lyrics": false,
        "file": null,
        "track_id": 624077491,
        "video_source_type": null,
        "duration": 368.595,
        "encodings_id": 134136691,
        "title": "You Are Loved"
    },
    {
        "alt_link": null,
        "has_info": false,
        "video_source_id": null,
        "track_num": 9,
        "encoding_error": null,
        "is_downloadable": true,
        "streaming": 1,
        "license_type": 1,
        "video_id": null,
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "private": null,
        "play_count": 0,
        "lyrics": null,
        "free_album_download": false,
        "video_caption": null,
        "title_link": "/track/sw9-9sl-2",
        "id": 1431185311,
        "track_license_id": null,
        "is_capped": false,
        "is_draft": false,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "has_lyrics": false,
        "file": {
            "mp3-128": "https://t4.bcbits.com/stream/36931a5949ee54e6e00e3a271b599031/mp3-128/1431185311?p=0&ts=1562266458&t=809c902cf2d478aad441af97c3a1fb8be28a0e6a&token=1562266458_570fcea71ef19bc22ef5e5afcb9a3b8aac70e257"
        },
        "track_id": 1431185311,
        "video_source_type": null,
        "duration": 475.639,
        "encodings_id": 521978020,
        "title": "SW9 9SL"
    },
    {
        "alt_link": null,
        "has_info": false,
        "video_source_id": null,
        "track_num": 10,
        "encoding_error": null,
        "is_downloadable": false,
        "streaming": null,
        "license_type": 1,
        "video_id": null,
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "private": null,
        "play_count": 0,
        "lyrics": null,
        "free_album_download": false,
        "video_caption": null,
        "title_link": "/track/10-midi",
        "id": 342786057,
        "track_license_id": null,
        "is_capped": false,
        "is_draft": false,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "has_lyrics": false,
        "file": null,
        "track_id": 342786057,
        "video_source_type": null,
        "duration": 85.0561,
        "encodings_id": 2364883881,
        "title": "10 Midi"
    },
    {
        "alt_link": null,
        "has_info": false,
        "video_source_id": null,
        "track_num": 11,
        "encoding_error": null,
        "is_downloadable": false,
        "streaming": null,
        "license_type": 1,
        "video_id": null,
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "private": null,
        "play_count": 0,
        "lyrics": null,
        "free_album_download": false,
        "video_caption": null,
        "title_link": "/track/memories",
        "id": 2144410565,
        "track_license_id": null,
        "is_capped": false,
        "is_draft": false,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "has_lyrics": false,
        "file": null,
        "track_id": 2144410565,
        "video_source_type": null,
        "duration": 197.904,
        "encodings_id": 83399389,
        "title": "Memories"
    },
    {
        "alt_link": null,
        "has_info": false,
        "video_source_id": null,
        "track_num": 12,
        "encoding_error": null,
        "is_downloadable": false,
        "streaming": null,
        "license_type": 1,
        "video_id": null,
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "private": null,
        "play_count": 0,
        "lyrics": null,
        "free_album_download": false,
        "video_caption": null,
        "title_link": "/track/daughter",
        "id": 3819922541,
        "track_license_id": null,
        "is_capped": false,
        "is_draft": false,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "has_lyrics": false,
        "file": null,
        "track_id": 3819922541,
        "video_source_type": null,
        "duration": 295.131,
        "encodings_id": 3566547438,
        "title": "Daughter"
    },
    {
        "alt_link": null,
        "has_info": false,
        "video_source_id": null,
        "track_num": 13,
        "encoding_error": null,
        "is_downloadable": false,
        "streaming": null,
        "license_type": 1,
        "video_id": null,
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "private": null,
        "play_count": 0,
        "lyrics": null,
        "free_album_download": false,
        "video_caption": null,
        "title_link": "/track/gentle-soul",
        "id": 4273034241,
        "track_license_id": null,
        "is_capped": false,
        "is_draft": false,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "has_lyrics": false,
        "file": null,
        "track_id": 4273034241,
        "video_source_type": null,
        "duration": 72.185,
        "encodings_id": 2120607808,
        "title": "Gentle Soul"
    },
    {
        "alt_link": null,
        "has_info": false,
        "video_source_id": null,
        "track_num": 14,
        "encoding_error": null,
        "is_downloadable": true,
        "streaming": 1,
        "license_type": 1,
        "video_id": null,
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "private": null,
        "play_count": 0,
        "lyrics": null,
        "free_album_download": false,
        "video_caption": null,
        "title_link": "/track/planet-2",
        "id": 1906600355,
        "track_license_id": null,
        "is_capped": false,
        "is_draft": false,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "has_lyrics": false,
        "file": {
            "mp3-128": "https://t4.bcbits.com/stream/ba7221982cf00f4cab8c1ee933e3879d/mp3-128/1906600355?p=0&ts=1562266458&t=2b7eba0572ce6f1eef9a1bd4a048be0c27ea8083&token=1562266458_f60d1a5e9cdd1b722ac63ae05a48579dbf0606f1"
        },
        "track_id": 1906600355,
        "video_source_type": null,
        "duration": 438.48,
        "encodings_id": 2723230134,
        "title": "Planet"
    }
]
```

**Comment by dstftw** [comment]
Again: youtube-dl will not ignore errors by default, it's your responsibility to use proper options.
