### ISSUE TITLE
audio conversion failed: file

### ISSUE THREAD

**Issue by GiacomoLaw** [ytdl-org/youtube-dl#21632]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.07.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --extract-audio -v --audio-format mp3 https://www.youtube.com/watch?v=0yBnIUX0QAE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--extract-audio', '-v', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=0yBnIUX0QAE']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.07.02
[debug] Python version 3.7.3 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: ffmpeg N-93532-g772c73e61f, ffprobe N-93532-g772c73e61f
[debug] Proxy map: {}
[youtube] 0yBnIUX0QAE: Downloading webpage
[youtube] 0yBnIUX0QAE: Downloading video info webpage
[youtube] {18} signature length 108, html5 player vfliSA6ma
[youtube] {135} signature length 108, html5 player vfliSA6ma
[youtube] {244} signature length 104, html5 player vfliSA6ma
[youtube] {397} signature length 104, html5 player vfliSA6ma
[youtube] {134} signature length 108, html5 player vfliSA6ma
[youtube] {243} signature length 108, html5 player vfliSA6ma
[youtube] {396} signature length 108, html5 player vfliSA6ma
[youtube] {133} signature length 108, html5 player vfliSA6ma
[youtube] {242} signature length 108, html5 player vfliSA6ma
[youtube] {395} signature length 108, html5 player vfliSA6ma
[youtube] {160} signature length 104, html5 player vfliSA6ma
[youtube] {278} signature length 108, html5 player vfliSA6ma
[youtube] {394} signature length 108, html5 player vfliSA6ma
[youtube] {140} signature length 108, html5 player vfliSA6ma
[youtube] {171} signature length 108, html5 player vfliSA6ma
[youtube] {249} signature length 108, html5 player vfliSA6ma
[youtube] {250} signature length 108, html5 player vfliSA6ma
[youtube] {251} signature length 104, html5 player vfliSA6ma
[debug] Invoking downloader on 'https://r6---sn-aigl6n7z.googlevideo.com/videoplayback?expire=1562201965&ei=DfscXdD_DMmoVvmnoKAM&ip=195.206.183.251&id=o-AKCXBu_4zF58aNx08l68u54idAlM_ASJkV2XkgIeCSzc&itag=251&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-aigl6n7z%2Csn-5hne6ns6&ms=au%2Conr&mv=m&mvi=5&pl=24&gcr=gb&initcwndbps=1042500&mime=audio%2Fwebm&gir=yes&clen=3511761&dur=225.061&lmt=1540015396298697&mt=1562180250&fvip=5&keepalive=yes&c=WEB&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgdBrHk0EF5-POk0grp0RghO4VFaqFj3EFjjvHuECjGMYCIQCYhR8MrUYM1liYjNpCEtcqoVKp_ONnvRp__v3Sc6Zrgw%3D%3D&sig=ALgxI2wwRAIgLxYlyTuvpkRwgV9FAl6DQZHrKfovDmY-2HrVivijY8MCIHlrs-8MZZFm3Wo8Y1WHl90ms13u6yfAGMCA8jmYeXsJ&ratebypass=yes'
[download] Toploader - Dancing in the Moonlight (Official Video)-0yBnIUX0QAE.webm has already been downloaded
[download] 100% of 3.35MiB
[debug] ffmpeg command line: ffprobe -show_streams "file:Toploader - Dancing in the Moonlight (Official Video)-0yBnIUX0QAE.webm"
[ffmpeg] Destination: Toploader - Dancing in the Moonlight (Official Video)-0yBnIUX0QAE.mp3
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Toploader - Dancing in the Moonlight (Official Video)-0yBnIUX0QAE.webm" -vn -acodec libmp3lame "-q:a" 5 "file:Toploader - Dancing in the Moonlight (Official Video)-0yBnIUX0QAE.mp3"
ERROR: audio conversion failed: file:Toploader - Dancing in the Moonlight (Official Video)-0yBnIUX0QAE.mp3: Permission denied
Traceback (most recent call last):
  File "c:\users\giaco\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 265, in run_ffmpeg
    FFmpegPostProcessor.run_ffmpeg(self, path, out_path, opts)
  File "c:\users\giaco\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 239, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "c:\users\giaco\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:Toploader - Dancing in the Moonlight (Official Video)-0yBnIUX0QAE.mp3: Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\giaco\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 336, in run
    self.run_ffmpeg(path, new_path, acodec, more_opts)
  File "c:\users\giaco\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 267, in run_ffmpeg
    raise AudioConversionError(err.msg)
youtube_dl.postprocessor.common.AudioConversionError: file:Toploader - Dancing in the Moonlight (Official Video)-0yBnIUX0QAE.mp3: Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\giaco\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 2054, in post_process
    files_to_delete, info = pp.run(info)
  File "c:\users\giaco\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 339, in run
    'audio conversion failed: ' + e.msg)
youtube_dl.utils.PostProcessingError: audio conversion failed: file:Toploader - Dancing in the Moonlight (Official Video)-0yBnIUX0QAE.mp3: Permission denied
```

## Description

Attempting to download a music file. I have done this thousands of times, however only getting this error now.

Any idea how to fix it? Looks to be an issue with ffmpeg, however used to work. I also attempted to run with admin powers, however this also did not work.

Thanks!

**Comment by dstftw** [comment]
>Permission denied

**Comment by GiacomoLaw** [comment]
I saw that, but as mentioned running as admin didn't solve it.

**Comment by GiacomoLaw** [comment]
Fails in every directory, from downloads to documents.

**Comment by bitraid** [comment]
What happends if you run the ffmpeg command manually?

**Comment by GiacomoLaw** [comment]
Seems to be an issue with ffmpeg, gettign an error too.
