### ISSUE TITLE
Error with Drive video.

### ISSUE THREAD

**Issue by FrossGus** [ytdl-org/youtube-dl#21633]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X ] I've verified that I'm running youtube-dl version **2019.07.02**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
sudo youtube-dl --verbose --cookies cookies.txt -f 22 'https://drive.google.com/file/d/1-jVtoMFDEFPaGZEZTBWeJZJ-pMMLLg4-/view?ts=5d1ba252'
[sudo] password for gustavo: 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--cookies', u'cookies.txt', u'-f', u'22', u'https://drive.google.com/file/d/1-jVtoMFDEFPaGZEZTBWeJZJ-pMMLLg4-/view?ts=5d1ba252']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.02
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-54-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: none
[debug] Proxy map: {}
[GoogleDrive] 1-jVtoMFDEFPaGZEZTBWeJZJ-pMMLLg4-: Downloading webpage
ERROR: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/googledrive.py", line 179, in _real_extract
    default=None) or self._og_search_title(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1117, in _og_search_title
    return self._og_search_property('title', html, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1105, in _og_search_property
    escaped = self._search_regex(og_regexes, html, name, flags=re.DOTALL, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

I was able to download another video hosted on Drive, but I could not do it.
I have already verified the link to the video and it works perfectly.
Use Ubuntu 16.04 LTS.

**Comment by dstftw** [comment]
Either you don't have access to the video or cookies are expired. In any case you must provide reproducible environment for any work on this.
