### ISSUE TITLE
[YourPorn] HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by fugleman** [ytdl-org/youtube-dl#21645]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
~# youtube-dl -v 'https://sxyprn.com/post/5d1cfb174cf40.html'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://sxyprn.com/post/5d1cfb174cf40.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.02
[debug] Python version 2.7.16 (CPython) - Linux-5.0.0-15-generic-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: none
[debug] Proxy map: {}
[YourPorn] 5d1cfb174cf40: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://sxyprn.com/cdn5/c7/y4y5vz9707hz31y0467zw9r9s/wc7vSM4Ro-k3D5aEd0RWSw/1562271293/k5uaf695g3i41ed0o31b3b6b94c/659dp11cdfgbk1e754ocwfm4a0f.mp4'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1915, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1854, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```

## Description

I have tried multiple different posts and all of them return the same 404 error. I have also tried running the same commands on multiple different machines in case it's network-related and was able to reproduce the same issue on all the machines I've tested with.

**Comment by chuckn408** [comment]
The page:
`https://sxyprn.com/cdn5/c7/y4y5vz9707hz31y0467zw9r9s/wc7vSM4Ro-k3D5aEd0RWSw/1562271293/k5uaf695g3i41ed0o31b3b6b94c/659dp11cdfgbk1e754ocwfm4a0f.mp4`
does not exist. This would _not_ be an issue with youtube-dl itself.  I would suggest keeping this closed.
