### ISSUE TITLE
RedBullTV - Extractor Error caused by KeyError

### ISSUE THREAD

**Issue by mizmazz** [ytdl-org/youtube-dl#21669]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2019.07.02**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
F:\world cup>youtube-dl --verbose https://www.redbull.com/int-en/events/AP-1Z8TA
EXVS1W12/live/AP-1Z8K4CTP12511
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.redbull.com/int-en/events/
AP-1Z8TAEXVS1W12/live/AP-1Z8K4CTP12511']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.07.02
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2017-12-19-c94b094, ffprobe git-2017-12-19-c94b
094, phantomjs 2.1.1
[debug] Proxy map: {}
[RedBullTV] AP-1Z8K4CTP12511: Downloading access token
[RedBullTV] AP-1Z8K4CTP12511: Downloading video information
ERROR: An extractor error has occurred. (caused by KeyError('error',)); please r
eport this issue on https://yt-dl.org/bug . Make sure you are using the latest v
ersion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --ve
rbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\YoutubeDL.py", line 2227, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\extractor\redbulltv.py", line 67, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\extractor\common.py", line 892, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\extractor\common.py", line 870, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\extractor\common.py", line 660, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\extractor\common.py", line 645, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 40
4: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.
org/bug . Make sure you are using the latest version; type  youtube-dl -U  to up
date. Be sure to call youtube-dl with the --verbose flag and include its complet
e output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\extractor\redbulltv.py", line 72, in _real_extract
KeyError: 'error'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\YoutubeDL.py", line 2227, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\extractor\redbulltv.py", line 67, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\extractor\common.py", line 892, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\extractor\common.py", line 870, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\extractor\common.py", line 660, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\extractor\common.py", line 645, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 40
4: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.
org/bug . Make sure you are using the latest version; type  youtube-dl -U  to up
date. Be sure to call youtube-dl with the --verbose flag and include its complet
e output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\extractor\redbulltv.py", line 72, in _real_extract
KeyError: 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfku
ku\build\youtube_dl\extractor\common.py", line 543, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by Key
Error('error',)); please report this issue on https://yt-dl.org/bug . Make sure
you are using the latest version; type  youtube-dl -U  to update. Be sure to cal
l youtube-dl with the --verbose flag and include its complete output.

```

## Description

Extractor error.

**Comment by timklein003** [comment]
i have the same issue?

**Comment by mizmazz** [comment]
This has now manifested into changing support from redbull.tv into redbull.com. Should be fixed with **Support redbull.tv's migration to redbull.com #22063**
