### ISSUE TITLE
YouTube ERROR: giving up after 0 retries

### ISSUE THREAD

**Issue by PFython** [ytdl-org/youtube-dl#21660]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
```
video = 'qfuvp41SLrU'
with youtube_dl.YoutubeDL({'verbose': True}) as ydl:
    video = ydl.extract_info(video, download=True)
```
...
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.07.02
[debug] Python version 3.7.2 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[youtube] qfuvp41SLrU: Downloading webpage
[youtube] qfuvp41SLrU: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r6---sn-8pgbpohxqp5-aig6.googlevideo.com/videoplayback?expire=1562342067&ei=Uh4fXbfwO8XrV5zxhOgP&ip=86.25.44.26&id=o-AKV2XAz1Mx6Zy7IkIJPNNPu3aNgG-P3KaOB9iImAiPs8&itag=136&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-8pgbpohxqp5-aig6%2Csn-5hnednlr&ms=au%2Conr&mv=m&mvi=5&pl=20&initcwndbps=2268750&mime=video%2Fmp4&gir=yes&clen=62846115&dur=309.200&lmt=1408825852756509&mt=1562320334&fvip=1&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIgfCeEgx6xXXnxn-mox9pLFhMrXFMqC0cf_KtpgSGssSUCIQDdZWU9RTRrzRI5pLscnrAgx_V4Eo9WWa6A1vUgOtekRQ%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhAL24Gq4Z0G4BTsEQVgAUB0XHkqwV4jZII63F0prNF2ERAiEA5VYJ42Y1nz-B1LiuxW8dx0uQl5uh7Yc0O9X1Ca3B5qs%3D&ratebypass=yes'
ERROR: giving up after 0 retries
  File "<stdin>", line 2, in <module>
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 861, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1642, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1909, in process_info
    partial_success = dl(fname, new_info)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1854, in dl
    return fd.download(name, info)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\downloader\common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\downloader\http.py", line 353, in real_download
    self.report_error('giving up after %s retries' % retries)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\downloader\common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 586, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 861, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1642, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1909, in process_info
    partial_success = dl(fname, new_info)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1854, in dl
    return fd.download(name, info)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\downloader\common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\downloader\http.py", line 353, in real_download
    self.report_error('giving up after %s retries' % retries)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\downloader\common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: giving up after 0 retries
>>>

## Description

WRITE DESCRIPTION HERE
The video in question is public on YouTube and part of channel https://www.youtube.com/playlist?list=UUo2Zp6o4nH3sGHeP2DJr9Dw.  I successfully downloaded the 589 other videos from this channel using the two line Python snippet:

```
with youtube_dl.YoutubeDL({'verbose': True}) as ydl:
...             video = ydl.extract_info(video, download=True)
```
... but it failed with this one.  I tried downloading just this video (not the whole playlist) and it failed in the same way.

I'm afraid I can't suggest a solution as I've no clue why it might be failing _after 0 retries_.  I see a similar issue was raised in 2015 which was fixed apparently, so perhaps there's something there worth revisiting?

Good luck, and thanks for an otherwise excellent product!
...

**Comment by dstftw** [comment]
Server side youtube error.

**Comment by arysef** [comment]
This does not appear to be due to a server-side issue. The default number of retries is 0 and the client errors out if the number of errors is greater than **or equal to** the retries (https://github.com/ytdl-org/youtube-dl/blob/fe7e13066c20b10fe48bc154431440da36baec53/youtube_dl/downloader/dash.py#L69). This causes it to error out the first time by default if you haven't changed the retry count. The second time you run it, it doesn't hit the"real_download" function and passes. This can be fixed by just removing the "or equal to".
