### ISSUE TITLE
Openload: RegexNotFoundError

### ISSUE THREAD

**Issue by tmczar** [ytdl-org/youtube-dl#21673]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []                                                       
[debug] User config: []                                                           
[debug] Custom config: []                                                          
[debug] Command-line args: [u'--verbose', u'https://openload.co/f/oYZN5SNgIhs']      
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8                       
[debug] youtube-dl version 2019.07.02                                                     
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-54-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1                               
[debug] Proxy map: {}                                                                                
[Openload] oYZN5SNgIhs: Downloading embed webpage                                                      
[Openload] oYZN5SNgIhs: Executing JS on webpage                                                           
ERROR: Unable to extract stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.          
Traceback (most recent call last):                                                                                    
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info                                       
    ie_result = ie.extract(url)                                                                                                
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract                                            
    ie_result = self._real_extract(url)                                                                                               
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/openload.py", line 429, in _real_extract                                          
    'stream URL')                                                                                                                            
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex                                                  
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
## Description

Probably nothing smart to say. Support for Openload got broken recently. Everything else is in verbose log.

**Comment by dstftw** [comment]
```
> py -3.7 .\youtube_dl\__main__.py https://openload.co/f/oYZN5SNgIhs
[Openload] oYZN5SNgIhs: Downloading embed webpage
[Openload] oYZN5SNgIhs: Executing JS on webpage
[download] Destination: Shoujo Shuumatsu Ryokou - 12 [1080p]-oYZN5SNgIhs.mp4
[download]   0.2% of 248.95MiB at 1002.31KiB/s ETA 04:13
ERROR: Interrupted by user
```
