### ISSUE TITLE
youtube-dl reports content warnings and no way around it.

### ISSUE THREAD

**Issue by stickbear2015** [ytdl-org/youtube-dl#21677]
## Checklist

x [ ] I'm reporting a broken site support
x [ ] I've verified that I'm running youtube-dl version **2019.07.02**
x [ ] I've checked that all provided URLs are alive and playable in a browser
x [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
x [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-a', u'd:\\dropbox\\youtube-patty-mayo-download-urls.txt', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-v']
[debug] Batch file urls: [u'https://www.youtube.com/watch?v=19j1_7s0E48', u'https://www.youtube.com/watch?v=fNSDwWYm704', u'https://www.youtube.com/watch?v=UlJUcFOg3cE', u'https://www.youtube.com/watch?v=6o2QR5rT4-E', u'https://www.youtube.com/watch?v=hrtVKt608jg', u'https://www.youtube.com/watch?v=PiEjxPY2n4A', u'https://www.youtube.com/watch?v=vMytZoNmNsY', u'https://www.youtube.com/watch?v=Y_eWbkNY7gg', u'https://www.youtube.com/watch?v=cG42FXVy9FQ']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.07.02
[debug] Python version 2.7.15 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube] 19j1_7s0E48: Downloading webpage
[youtube] 19j1_7s0E48: Downloading embed webpage
[youtube] 19j1_7s0E48: Refetching age-gated info webpage
ERROR: Content Warning
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\youtube_dl-2019.7.2-py2.7.egg\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "C:\Python27\lib\site-packages\youtube_dl-2019.7.2-py2.7.egg\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "C:\Python27\lib\site-packages\youtube_dl-2019.7.2-py2.7.egg\youtube_dl\extractor\youtube.py", line 2097, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: Content Warning

```

## Description

The credentials are valid but these URL's are of course content age restricted 
but their's no command line to get around to download.

**Comment by stickbear2015** [comment]
@dstftw
IF your going to close an issue, please provide context for the reason you closed it, this includes providing issue numbers to what you perceive are duplicate issues. With over 21600 issues their's a lot and people MAY NOT BE able to find the same issues that you find that you consider duplicate issues OF OPENED issues.
Thank you.
