### ISSUE TITLE
Unable to extract Initial JS player signature function name caused by RegexNotFoundError.

### ISSUE THREAD

**Issue by AlekZeng** [ytdl-org/youtube-dl#21690]
## Checklist

- [x ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2019.07.02**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[youtube] fOk8Tm815lE: Downloading webpage
[youtube] fOk8Tm815lE: Downloading video info webpage
[youtube] fOk8Tm815lE: Downloading js player vfliSA6ma
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Ignoring exception in command play:
Traceback (most recent call last):
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\youtube.py", line 1989, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\youtube.py", line 1352, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:/Users/Alek/PycharmProjects/MetrixBotBeta/bot.py", line 207, in play
    ydl.download([url])
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\YoutubeDL.py", line 2008, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\YoutubeDL.py", line 819, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\discord\ext\commands\bot.py", line 859, in invoke
    await ctx.command.invoke(ctx)
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\discord\ext\commands\core.py", line 725, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\discord\ext\commands\core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "D:\robotics\anaconda\envs\MetrixBot\lib\site-packages\youtube_dl\extractor\common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE
Im coding a discord music bot, but this error keeps on occurring even though i re downloaded youtube-dl.  It is Unable to extract Initial JS player signature function name caused by RegexNotFoundError.

**Comment by AlekZeng** [comment]
wdym outdated version? I literally redownloaded and updated

**Comment by AlekZeng** [comment]
if there is anything you would like me to specify, please do. Thanks

**Comment by remitamine** [comment]
**full** verbose log.

**Comment by AlekZeng** [comment]
full verbose log added

**Comment by remitamine** [comment]
of youtube-dl output.

**Comment by AlekZeng** [comment]
> of youtube-dl output.

oh sorry

**Comment by AlekZeng** [comment]
so i its now an ffmpeg error for some reason. Sorry for wasting your time
