### ISSUE TITLE
Fix Extractor sxyprn.com and biqle.ru

### ISSUE THREAD

**Issue by jppoa** [ytdl-org/youtube-dl#21696]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
####
sxyprn.com
####
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'best', u'https://sxyprn.com/post/5c168ea91f5d0.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.02
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-54-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 3.4.4-1, avprobe 3.4.4-1, ffmpeg 3.4.4-1, ffprobe 3.4.4-1, rtmpdump 2.4
[debug] Proxy map: {}
[YourPorn] 5c168ea91f5d0: Downloading webpage
[debug] Invoking downloader on u'https://sxyprn.com/cdn5/s19/f71h7v7qzn1e3o59z2272gzy1o4/32ZEGkuMMx2VhYpvoGPLEA/1562672264/w5296c437fh6i156u0o1q8xby8g/hu55ci106i8ae2a39u1qf351de0.mp4'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1915, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1854, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

####
biqle.ru
####
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'best', u'https://biqle.ru/watch/-151226968_456240067']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.02
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-54-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 3.4.4-1, avprobe 3.4.4-1, ffmpeg 3.4.4-1, ffprobe 3.4.4-1, rtmpdump 2.4
[debug] Proxy map: {}
[BIQLE] -151226968_456240067: Downloading webpage
[BIQLE] -151226968_456240067: Downloading webpage
[BIQLE] -151226968_456240067: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError(u'response',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/biqle.py", line 60, in _real_extract
    })['response']['items'][0]
KeyError: u'response'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 543, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'response',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

The program fails to download videos from sxyprn.com and biqle.ru.
Both links provided are live... And is possible to download it with "DownloadHelper".
I believe that the path of extraction changed in both websites.

for sxyprn.com the video "https://sxyprn.com/post/5c168ea91f5d0.html" can be extracted using the following link: https://s19-1.trafficdeposit.com/video/q1g7w76zw1t325lz32220z81d40/uIMQvZzgFHPhfGPxcYxy7w/1562672217/59c3f616018b8/5c168ea91f5d0.mp4

for biqle.ru the video "https://biqle.ru/watch/-151226968_456240067" can be extracted using the following link: https://psv52-1.daxab.com/videos/-151226968/456240067/720.mp4?extra=YeZZHdp3wEEbilrcLeCodg

**Comment by jppoa** [comment]
Tks for replying. This is not a duplicate, since the one uploaded 4 days ago was removed from issues tab.

**Comment by Symbitic** [comment]
I don't have anything to help with biqle, but for sxyprn, here's how to fix it:

Let's say the environment variable `VNFO` is set to the value of `data-vnfo`.
Run this:
`node -e "let tmp = '$VNFO'.split('/');tmp[1]+='8';tmp[5]-=parseInt(tmp[6].replace(/[^0-9]/g,''))+parseInt(tmp[7].replace(/[^0-9]/g,''));console.log('https://sxyprn.com'+tmp.join('/'));"`

The URL printed is the correct URL to download.
I would fix it myself, but I don't know enough python to translate this into python.
