### ISSUE TITLE
Bandcamp song download broken

### ISSUE THREAD

**Issue by hololeap** [ytdl-org/youtube-dl#21699]
c9b0564ac141bed3766fa65011274cb5c1c5bccb

## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v 'http://youtube-dl.bandcamp.com/track/youtube-dl-test-song'[debug] System config: ['--output', '%(upload_date)s %(title)s %(id)s.%(ext)s', '--format', 'best[height<=1080]', '--no-mtime', '--write-info-json', '--add-metadata']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://youtube-dl.bandcamp.com/track/youtube-dl-test-song']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.02
[debug] Python version 3.6.5 (CPython) - Linux-5.1.9-gentoo-x86_64-Intel-R-_Core-TM-_i5-3210M_CPU_@_2.50GHz-with-gentoo-2.6
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[Bandcamp] youtube-dl-test-song: Downloading webpage
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 861, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1634, in process_video_result
    expected=True)
youtube_dl.utils.ExtractorError: requested format not available
```

## Description

Downloads from Bandcamp are not working. If you try to download an album, it fails on the first song. This was tested in Gentoo Linux, built from commit c9b0564ac141bed3766fa65011274cb5c1c5bccb.

**Comment by dstftw** [comment]
Bother to read error message.

**Comment by hololeap** [comment]
Oh, it was because of my system config. Sorry :)
