### ISSUE TITLE
[NBC] list index out of range 

### ISSUE THREAD

**Issue by omega13a** [ytdl-org/youtube-dl#21703]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -t -v https://www.nbcnews.com/video/woman-gives-birth-to-babies-who-are-not-hers-after-shocking-ivf-mix-up-63494725751?cid=referral_taboolafeed
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-t', '-v', 'https://www.nbcnews.com/video/woman-gives-birth-to-babies-who-are-not-hers-after-shocking-ivf-mix-up-63494725751?cid=referral_taboolafeed']
WARNING: --title is deprecated. Use -o "%(title)s-%(id)s.%(ext)s" instead.
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.02
[debug] Python version 3.7.0 (CPython) - Linux-5.0.14-200.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
[debug] exe versions: ffmpeg 4.0.4, ffprobe 4.0.4
[debug] Proxy map: {}
[ThePlatformFeed] 63494725751: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 11, in <module>
    load_entry_point('youtube-dl==2019.7.2', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.7/site-packages/youtube_dl/__init__.py", line 473, in main
    _real_main(argv)
  File "/usr/lib/python3.7/site-packages/youtube_dl/__init__.py", line 463, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2007, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 806, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 872, in process_ie_result
    extra_info=extra_info, download=False, process=False)
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 795, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/theplatform.py", line 411, in _real_extract
    return self._extract_feed_info(provider_id, feed_id, filter_query, video_id)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/theplatform.py", line 345, in _extract_feed_info
    entry = self._download_json(real_url, video_id)['entries'][0]
IndexError: list index out of range
```

## Description

Everytime I try to download a video off of NBC's website, I end up with a list index out of range error message. Its doesn't matter if the video is included in an article (like https://www.nbcnews.com/news/world/hong-kong-extradition-bill-dead-chief-executive-says-n1027641 ) or not.

**Comment by lwpVIM** [comment]
I have the same error for several weeks, several updates of youtube-dl, trying to download from msnbc.com.  Each URL that gives me this same error plays no problems from firefox.

Note that the only actual youtube-dl file in my machine's /usr/local/bin  is /usr/local/bin/youtube-dl.
There is no subdirectory /usr/local/bin/youtube-dl/   on this machine 

lwp@william:~/Desktop/Videos$    youtube-dl --verbose http://www.msnbc.com/rachel-maddow/watch/on-2016-russian-intrusion-us-intel-saw-dots-missed-connection-1184256067951
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.msnbc.com/rachel-maddow/watch/on-2016-russian-intrusion-us-intel-saw-dots-missed-connection-1184256067951']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.16
[debug] Python version 2.7.13 (CPython) - Linux-4.19.0-0.bpo.5-amd64-x86_64-with-debian-9.9
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1, rtmpdump 2.4
[debug] Proxy map: {}
[ThePlatformFeed] 1184256067951: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2008, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 807, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 873, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 411, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 345, in _extract_feed_info
IndexError: list index out of range

**Comment by lwpVIM** [comment]
Ahh, I see that I can have these subdirectory files, if I extract the zip file first.  Looking at the code, 
but scratching my head so far.

**Comment by gregbert42** [comment]
I've had this issue for months...  all nbcnews.com nighly news full broadcasts.
URL:
https://www.nbcnews.com/nightly-news-netcast/video/nightly-news-full-broadcast-october-22nd-71854661936
