### ISSUE TITLE
Facebook videos are not working

### ISSUE THREAD

**Issue by epiraces** [ytdl-org/youtube-dl#21712]
## Checklist

- [X ] I'm reporting a broken site support
- [X ] I've verified that I'm running youtube-dl version **2019.07.02**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'-v', u'https://www.facebook.com/100010620364862/videos/865583327139005/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.01
[debug] Python version 2.7.15+ - Linux-4.15.0-50-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: avconv 3.4.6-0ubuntu0.18.04.1, avprobe 3.4.6-0ubuntu0.18.04.1, ffmpeg 3.4.6-0ubuntu0.18.04.1, ffprobe 3.4.6-0ubuntu0.18.04.1
[debug] Proxy map: {}
[facebook] 865583327139005: Downloading webpage
[facebook] 865583327139005: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/epiraces/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 673, in extract_info
    ie_result = ie.extract(url)
  File "/home/epiraces/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/home/epiraces/.local/lib/python2.7/site-packages/youtube_dl/extractor/facebook.py", line 308, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/home/epiraces/.local/lib/python2.7/site-packages/youtube_dl/extractor/facebook.py", line 238, in _extract_from_url
    raise ExtractorError('Cannot parse data')
ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

Facebook videos are not downloading. I have tried with videos I was able to successfully download on prior dates but seems not be working now. This may be unrelated, but it seems FB is now forcing some videos to be displayed on Facebook Watch, which seems to be a list, rather than theater mode (this is speculative).

**Comment by epiraces** [comment]
Apologies, I pasted the wrong verbose log, as you can see even after running it with the current version I see the ExtractorError.

youtube-dl -F -v https://www.facebook.com/100010620364862/videos/865583327139005
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'-v', u'https://www.facebook.com/100010620364862/videos/865583327139005']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.01
[debug] Python version 2.7.15+ - Linux-4.15.0-50-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: avconv 3.4.6-0ubuntu0.18.04.1, avprobe 3.4.6-0ubuntu0.18.04.1, ffmpeg 3.4.6-0ubuntu0.18.04.1, ffprobe 3.4.6-0ubuntu0.18.04.1
[debug] Proxy map: {}
[facebook] 865583327139005: Downloading webpage
[facebook] 865583327139005: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/epiraces/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 673, in extract_info
    ie_result = ie.extract(url)
  File "/home/epiraces/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/home/epiraces/.local/lib/python2.7/site-packages/youtube_dl/extractor/facebook.py", line 308, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/home/epiraces/.local/lib/python2.7/site-packages/youtube_dl/extractor/facebook.py", line 238, in _extract_from_url
    raise ExtractorError('Cannot parse data')
ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by epiraces** [comment]
I know the log above says '2016.05.01', but I swaer it is running 2019.07.02! There seems to be an issue with the display of the version.

~/temp$ sudo -H pip install --upgrade youtube-dl
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting youtube-dl
  Using cached https://files.pythonhosted.org/packages/c2/2e/5605118b8d7bb639396df8cf7eb213d0d0fc73df95b9592c44434d5e7813/youtube_dl-2019.7.2-py2.py3-none-any.whl
Installing collected packages: youtube-dl
**Successfully installed youtube-dl-2019.7.2**
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
~/temp$ youtube-dl -v https://www.facebook.com/290644594604561/videos/418114008524285/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.facebook.com/290644594604561/videos/418114008524285/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
**[debug] youtube-dl version 2016.05.01**
