### ISSUE TITLE
[MGTV] HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by ZRJ868** [ytdl-org/youtube-dl#21726]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: [u'-o', u'/Volumes/DVR/Youtube/%(title)s.%(ext)s', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio', u'--merge-output-format', u'mp4']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'best', u'https://www.mgtv.com/b/328724/5898194.html', u'--verbose']
[debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII
[debug] youtube-dl version 2019.07.02
[debug] Python version 2.7.10 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 36.170.37.155 (CN) as X-Forwarded-For.
[MGTV] 5898194: Downloading JSON metadata
[MGTV] 5898194: Downloading JSON metadata
[MGTV] 5898194: Download video info for format #0
[MGTV] 5898194: Download video info for format #1
[MGTV] 5898194: Download video info for format #2
[debug] Invoking downloader on u'https://pcvideoyf.titan.mgtv.com/c1/2019/07/10_0/6D16243C1ECA18BF020CE5F39F481EF2_20190710_1_1_1686_mp4/CF734F8228F99B9FDAA02411A8E2B702.m3u8?arange=0&pm=m5C~y_pOtUy7S8vfo5mSlgMfvG55NHq943PoXPvL3DVN2vz0~GsA9XADlH0QHiLphmwQ~1rj5NiR0m3KMEf7fOX8~AfgsEjLzggonqTZ6YsgD1cZnE3a4tz~pmLUBwvWkeBhpvLTnWNPsiib_6E8jc46DQq2tgm6TINnkA6Nau3sfWI26c~88J8rWPAq79Ad5M8WwntWy1Idmkah8UnpesKi9ZWDVb8mXDsV9B2KePsbv_CuCCAQyaZBU_fGNAT22H1ykisNCMpAHcIeXZmUiQ23QHVADAKbHwawUr24f3kDUKpRSDY6tHqIhpI4xw6~9XTWVP2amZ6jAE1DV960SfAsQz1kkCJ5qkKRkci7DjqmunKCosXfcCq1Y9o5iiC4vqxPSrPNSH02RH6btHkKKdJCwhAKaGQwpKPIDvR3YWsAhzP2K0R3AqcKs5gU19cAP3gAWBb3vJTRjoq_MgL3yGgrljMCgdkijbjiky89Oe1gHG7SrWcKCVINfkf2SBCt~NDk~g--&did=064358b3-6b42-4bbb-84c6-f72394ff6cbf&mr=Lt1KB9wV9THlQQoAQviIfGhVb4O7d8S89HCQ~s25CWnH~sBpI5v7Sg6FdtGnxP4hwxCSqYRPmrQ2gjV~NFkIUKR9b~yKcS0XZGYuK7YAS9H8AzA~Q0bkDg04p9wMxOYaGo9T2VZ1PpmbQTFNhPZ8FPBWPiMHL0axTTcL5egtif8Qi3tNpgsv5fp0tZKRZ7izcVIEUw--&vcdn=0&scid=25022'
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1915, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1854, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 62, in real_download
    urlh = self.ydl.urlopen(self._prepare_url(info_dict, man_url))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

## Description

The support for mgtv seems to be broken since about 10 days ago. All attempt to download results in HTTP Error 403: Forbidden. I have tried previously downloadable links, new links, all available formats (all playable in browser) but none is working at the moment.

**Comment by chuckn408** [comment]
The link:
`https://pcvideoyf.titan.mgtv.com/c1/2019/07/10_0/6D16243C1ECA18BF020CE5F39F481EF2_20190710_1_1_1686_mp4/CF734F8228F99B9FDAA02411A8E2B702.m3u8?arange=0&pm=m5C~y_pOtUy7S8vfo5mSlgMfvG55NHq943PoXPvL3DVN2vz0~GsA9XADlH0QHiLphmwQ~1rj5NiR0m3KMEf7fOX8~AfgsEjLzggonqTZ6YsgD1cZnE3a4tz~pmLUBwvWkeBhpvLTnWNPsiib_6E8jc46DQq2tgm6TINnkA6Nau3sfWI26c~88J8rWPAq79Ad5M8WwntWy1Idmkah8UnpesKi9ZWDVb8mXDsV9B2KePsbv_CuCCAQyaZBU_fGNAT22H1ykisNCMpAHcIeXZmUiQ23QHVADAKbHwawUr24f3kDUKpRSDY6tHqIhpI4xw6~9XTWVP2amZ6jAE1DV960SfAsQz1kkCJ5qkKRkci7DjqmunKCosXfcCq1Y9o5iiC4vqxPSrPNSH02RH6btHkKKdJCwhAKaGQwpKPIDvR3YWsAhzP2K0R3AqcKs5gU19cAP3gAWBb3vJTRjoq_MgL3yGgrljMCgdkijbjiky89Oe1gHG7SrWcKCVINfkf2SBCt~NDk~g--&did=064358b3-6b42-4bbb-84c6-f72394ff6cbf&mr=Lt1KB9wV9THlQQoAQviIfGhVb4O7d8S89HCQ~s25CWnH~sBpI5v7Sg6FdtGnxP4hwxCSqYRPmrQ2gjV~NFkIUKR9b~yKcS0XZGYuK7YAS9H8AzA~Q0bkDg04p9wMxOYaGo9T2VZ1PpmbQTFNhPZ8FPBWPiMHL0axTTcL5egtif8Qi3tNpgsv5fp0tZKRZ7izcVIEUw--&vcdn=0&scid=25022`
Provides a 403 error in-browser as well as with the wget utility. It's a genuine permissions block- though I couldn't say just yet how to get around it. Perhaps it has to do with "Referrer Policy:strict-origin-when-cross-origin" being set?
