### ISSUE TITLE
Failed to parse JSON 

### ISSUE THREAD

**Issue by asukumari** [ytdl-org/youtube-dl#21723]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.07.02**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\username\Downloads>youtube-dl -v --cookies cookies.txt "https://www.lynda.com/Git-tutorials/Git-Branches-Merges-Remotes/5030980-2.html" -o "Lynda.com - %(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s" --write-sub
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'cookies.txt', 'https://www.lynda.com/Git-tutorials/Git-Branches-Merges-Remotes/5030980-2.html', '-o', 'Lynda.com - %(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s', '--write-sub']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.07.02
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[lynda:course] 5030980: Downloading course JSON
[download] Downloading playlist: Git: Branches, Merges, and Remotes
[lynda:course] playlist Git: Branches, Merges, and Remotes: Collected 44 video ids (downloading 44 of them)
[download] Downloading video 1 of 44
[lynda] 2222180: Downloading video JSON
[lynda] 2222180: Checking 1-540 video format URL
[lynda] 2222180: Checking 1-360 video format URL
[lynda] 2222180: Checking 1-720 video format URL
[lynda] 2222180: Checking 0-540 video format URL
[lynda] 2222180: Checking 0-360 video format URL
[lynda] 2222180: Checking 0-720 video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Lynda.com - Git - Branches, Merges, and Remotes\1 - Introduction\01 - Unlock powerful code management and collaboration tools in Git.en.srt
[debug] Invoking downloader on 'https://files3.lynda.com/secure/courses/5030980/VBR_MP4h264_main_HD720/5030980_00_01_WX30_intro.mp4?kWEe_NN_4enRIraHULYR1YS37ykz14FVWXFVB6-Us_7ZPh_FcPkwi7F7BVOIr-wspeR3jDGJ5OYGr9b4J1Vpj0ykGMY_7lnJpFFenqR5oq0NCxkhBrC8C3YI8M_DFDFEKZ5RmV6v2a-ADNm3ZVDb4lHcOqm0UO6wdZyzg2J7MYDfh_nK-dDSCCIPIItKVA&c3.ri=3774529162039544779'
[download] Destination: Lynda.com - Git - Branches, Merges, and Remotes\1 - Introduction\01 - Unlock powerful code management and collaboration tools in Git.mp4
[download] 100% of 9.08MiB in 00:00
[download] Downloading video 2 of 44
[lynda] 2220751: Downloading video JSON
[lynda] 2220751: Checking 1-540 video format URL
[lynda] 2220751: Checking 1-360 video format URL
[lynda] 2220751: Checking 1-720 video format URL
[lynda] 2220751: Checking 0-540 video format URL
[lynda] 2220751: Checking 0-360 video format URL
[lynda] 2220751: Checking 0-720 video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Lynda.com - Git - Branches, Merges, and Remotes\1 - Introduction\02 - What you should know.en.srt
[debug] Invoking downloader on 'https://files3.lynda.com/secure/courses/5030980/VBR_MP4h264_main_HD720/5030980_00_02_XR30_whatyoushouldknow.mp4?VVHrSN4m2s2mp5DeEKA6FbHpGvo86kYvUhIfw55r1uDNgRGl9q0-yeeXv06OvCRwFmgHvMpHEyaONmzaTUGIcaSRjsL9ym3Cq7fSltKhQ79e_RQupPlJ5MzqIJIX30mF5mxWfazmFtWzbnErbXCYi9YP-aRXAqsI__xeNzHFhwY7XJ0DRbudep33lZqDVDqo71BRPcijA7vHElg&c3.ri=3774529162039544783'
[download] Destination: Lynda.com - Git - Branches, Merges, and Remotes\1 - Introduction\02 - What you should know.mp4
[download] 100% of 2.39MiB in 00:00
[download] Downloading video 3 of 44
[lynda] 2222181: Downloading video JSON
[lynda] 2222181: Checking 1-540 video format URL
[lynda] 2222181: Checking 1-360 video format URL
[lynda] 2222181: Checking 1-720 video format URL
[lynda] 2222181: Checking 0-540 video format URL
[lynda] 2222181: Checking 0-360 video format URL
[lynda] 2222181: Checking 0-720 video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Lynda.com - Git - Branches, Merges, and Remotes\2 - 1. Navigate the Commit Tree\03 - Reference commits.en.srt
[debug] Invoking downloader on 'https://files3.lynda.com/secure/courses/5030980/VBR_MP4h264_main_HD720/5030980_01_01_XR30_referencecommits.mp4?3LU6DAq6da_wqWZ0MDGlut9vukm8bPHobMOD0ayuZ6s6MbQy6U1bf2nTxlokWq3SJSE0QPRB1o7jRuGIaUeOVzZIeGq8RPB_iVHHXsT0ZNRbiAtBesg9MZXKMfWT2yqzrqcAK430OmQhGrrG794wwXa4oqTTf_RlAys81bavVA5TWcgJ9eL8Ma-us4XcOBTRs2Iy8VpQt25YWA&c3.ri=3774529162039544793'
[download] Destination: Lynda.com - Git - Branches, Merges, and Remotes\2 - 1. Navigate the Commit Tree\03 - Reference commits.mp4
[download] 100% of 9.92MiB in 00:00
[download] Downloading video 4 of 44
[lynda] 2220752: Downloading video JSON
[lynda] 2220752: Checking 1-540 video format URL
[lynda] 2220752: Checking 1-360 video format URL
[lynda] 2220752: Checking 1-720 video format URL
[lynda] 2220752: Checking 0-540 video format URL
[lynda] 2220752: Checking 0-360 video format URL
[lynda] 2220752: Checking 0-720 video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Lynda.com - Git - Branches, Merges, and Remotes\2 - 1. Navigate the Commit Tree\04 - Ancestry.en.srt
[debug] Invoking downloader on 'https://files3.lynda.com/secure/courses/5030980/VBR_MP4h264_main_HD720/5030980_01_02_XR30_ancestry.mp4?NZzQ3InuV5Rv5o794bYwEKZ0ui5FUg1Xfb8yqnNSxI3-7JtC1ZzhEzu38Fq0-x-ueAmAreS3WLnftSolw7yGJIpPXiasvsMIVc1kiKQSNY5O3noIAH0gHUE3zXZluZl_yRO23KMsDy8Nsh7xZspUnTs9QtE1oZpUN9dI9PVWKExGsqdbgw2FqtCdqWb18dNbzwc&c3.ri=3774529162039544800'
[download] Destination: Lynda.com - Git - Branches, Merges, and Remotes\2 - 1. Navigate the Commit Tree\04 - Ancestry.mp4
[download] 100% of 9.68MiB in 00:00
[download] Downloading video 5 of 44
[lynda] 2220753: Downloading video JSON
[lynda] 2220753: Checking 1-540 video format URL
[lynda] 2220753: Checking 1-360 video format URL
[lynda] 2220753: Checking 1-720 video format URL
[lynda] 2220753: Checking 0-540 video format URL
[lynda] 2220753: Checking 0-360 video format URL
[lynda] 2220753: Checking 0-720 video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Lynda.com - Git - Branches, Merges, and Remotes\2 - 1. Navigate the Commit Tree\05 - Tree listings.en.srt
[debug] Invoking downloader on 'https://lynda_files2-a.akamaihd.net/secure/courses/5030980/VBR_MP4h264_main_HD720/5030980_01_03_XR30_treelistings.mp4?c3.ri=3774810668192416711&hashval=1562810963_df91005a2d7d25e924e36118e04ff38b'
[download] Destination: Lynda.com - Git - Branches, Merges, and Remotes\2 - 1. Navigate the Commit Tree\05 - Tree listings.mp4
[download] 100% of 11.91MiB in 00:02
[download] Downloading video 6 of 44
[lynda] 2221741: Downloading video JSON
[lynda] 2221741: Checking 1-540 video format URL
[lynda] 2221741: Checking 1-360 video format URL
[lynda] 2221741: Checking 1-720 video format URL
[lynda] 2221741: Checking 0-540 video format URL
[lynda] 2221741: Checking 0-360 video format URL
[lynda] 2221741: Checking 0-720 video format URL
ERROR: None: Failed to parse JSON  (caused by ValueError('Expecting property name enclosed in double quotes: line 1 column 3 (char 2)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfkuku\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 359, in raw_decode
ValueError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfkuku\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 359, in raw_decode
ValueError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfkuku\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfkuku\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfkuku\build\youtube_dl\extractor\lynda.py", line 217, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfkuku\build\youtube_dl\extractor\common.py", line 2880, in extract_subtitles
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfkuku\build\youtube_dl\extractor\lynda.py", line 250, in _get_subtitles
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfkuku\build\youtube_dl\extractor\common.py", line 892, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfkuku\build\youtube_dl\extractor\common.py", line 876, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphnjfkuku\build\youtube_dl\extractor\common.py", line 903, in _parse_json
youtube_dl.utils.ExtractorError: None: Failed to parse JSON  (caused by ValueError('Expecting property name enclosed in double quotes: line 1 column 3 (char 2)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Have downloaded several Lynda courses with the same syntax template as above but results in parsing error for this course.

**Comment by Coolwinter18** [comment]
Hello, Where can I find the non duplicate issue and the respective solution?... i'm sory but i'm not used to the labels and the topic organization. Greetings
