### ISSUE TITLE
No suitable InfoExtractor for Vimeo embed playlist with `--referer URL`

### ISSUE THREAD

**Issue by sbalk** [ytdl-org/youtube-dl#21733]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.07.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log of embed link
The video in the playlist can be watched in a browser using the first link in the youtube-dl command.
```
youtube-dl -v "https://vimeo.com/event/9751/embed" --referer "https://sigmod2019.org/live_streams"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vimeo.com/event/9751/embed', '--referer', 'https://sigmod2019.org/live_streams']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.02
[debug] Python version 3.6.8 (CPython) - Linux-4.18.0-25-generic-x86_64-with-debian-buster-sid
[debug] exe versions: none
[debug] Proxy map: {}
[generic] embed: Requesting header
WARNING: Falling back on generic information extractor.
[generic] embed: Downloading webpage
[generic] embed: Extracting information
[download] Downloading playlist: SIGMOD 2019 - Effectenbeurszaal on Vimeo
[generic] playlist SIGMOD 2019 - Effectenbeurszaal on Vimeo: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
ERROR: no suitable InfoExtractor for URL https://player.vimeo.com/video/346219137/fallback?noscript#__youtubedl_smuggle=%7B%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fvimeo.com%2Fevent%2F9751%2Fembed%22%7D%7D
  File "/home/stijn/miniconda3/bin/youtube-dl", line 10, in <module>
    sys.exit(main())
  File "/home/stijn/miniconda3/lib/python3.6/site-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/home/stijn/miniconda3/lib/python3.6/site-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/stijn/miniconda3/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2008, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/stijn/miniconda3/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/stijn/miniconda3/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1006, in process_ie_result
    extra_info=extra)
  File "/home/stijn/miniconda3/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 868, in process_ie_result
    extra_info=extra_info)
  File "/home/stijn/miniconda3/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 830, in extract_info
    self.report_error('no suitable InfoExtractor for URL %s' % url)
  File "/home/stijn/miniconda3/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/home/stijn/miniconda3/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 586, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```
## Verbose log of `player.vimeo.com/video/34...` link
As discussed in #3582 and #14600, the original player.vimeo link is used. However, this link doesn't work in my browser.
```
youtube-dl -v "https://player.vimeo.com/video/346219137" --referer "https://sigmod2019.org/live_streams"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://player.vimeo.com/video/346219137', '--referer', 'https://sigmod2019.org/live_streams']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.02
[debug] Python version 3.6.8 (CPython) - Linux-4.18.0-25-generic-x86_64-with-debian-buster-sid
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo] 346219137: Downloading webpage
[vimeo] 346219137: Extracting information
[vimeo] 346219137: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 404: Not Found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/stijn/miniconda3/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/stijn/miniconda3/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/stijn/miniconda3/lib/python3.6/site-packages/youtube_dl/extractor/vimeo.py", line 713, in _real_extract
    self._vimeo_sort_formats(formats)
  File "/home/stijn/miniconda3/lib/python3.6/site-packages/youtube_dl/extractor/vimeo.py", line 107, in _vimeo_sort_formats
    self._sort_formats(formats, field_preference=('preference', 'height', 'width', 'fps', 'tbr', 'format_id'))
  File "/home/stijn/miniconda3/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

- I have a Vimeo playlist from which I try to download one of the video's. The list is at https://vimeo.com/event/9751/embed.

- I have the link to the website where the playlist is located: https://sigmod2019.org/live_streams.

- If I run `youtube-dl -v "https://vimeo.com/event/9751/embed" --referer "https://sigmod2019.org/live_streams"`, I get an `ERROR: no suitable InfoExtractor for URL ...`.

- As discussed in #3582 and #14600, the original `player.vimeo.com/...` link is used. However, this link doesn't work in my browser (Chrome 75.0.3770.100-1 or Firefox 67.0.4 on Ubuntu 18.04). If I try with `youtube-dl -v "https://player.vimeo.com/video/346219137" --referer "https://sigmod2019.org/live_streams"`, I get a `WARNING: Unable to download JSON metadata: HTTP Error 404: Not Found
ERROR: No video formats found`.

Thanks for the great software!

**Comment by qudiqudi** [comment]
`youtube-dl -v "https://player.vimeo.com/video/120453574" --referer "https://dffb-archiv.de/dffb/plus-minus-null-0"`

The referrer argument still does not work.

```
ERROR: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/vimeo.py", line 651, in _real_extract
    config = self._parse_json(self._search_regex(
                              ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Sites like https://vimeovid.com/ can grab the video fine.

**Comment by thibaultmol** [comment]
Can also confirm this (can't share video url for legal reasons though)

**Comment by dirkf** [comment]
Fixed in git master.

For "Unable to extract info section": #30839.

Probably not the problem that OP had but new test-cases are needed. Create a new issue referencing this if required.
