### ISSUE TITLE
Youtube live stream broken

### ISSUE THREAD

**Issue by aonez** [ytdl-org/youtube-dl#21749]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.12**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v "https://www.youtube.com/watch?v=AVITTcATgYs"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=AVITTcATgYs']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.12
[debug] Python version 2.7.10 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] AVITTcATgYs: Downloading webpage
[youtube] AVITTcATgYs: Downloading video info webpage
[youtube] AVITTcATgYs: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r4---sn-h5q7knel.googlevideo.com/videoplayback?expire=1562942221&ei=rUYoXZLhKcikhAf23qSAAg&ip=83.35.59.42&id=AVITTcATgYs.1&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160&source=yt_live_broadcast&requiressl=yes&hcs=yes&mm=44%2C29&mn=sn-h5q7knel%2Csn-h5q7rn7l&ms=lva%2Crdu&mv=m&mvi=3&pl=16&shardbypass=yes&initcwndbps=963750&live=1&hang=1&noclen=1&mime=video%2Fmp4&gir=yes&mt=1562920521&fvip=3&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Clive%2Chang%2Cnoclen%2Cmime%2Cgir&sig=ALgxI2wwRQIhAPt_Z95Yon04n7lYSGIsNY3JZLhDpOkjgv9LMtC1KR17AiBhYVYeTHu7ReZlevWifY9gr9GOu5eVhUItCssJIl8a1g%3D%3D&lsparams=hcs%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cshardbypass%2Cinitcwndbps&lsig=AHylml4wRAIgVhb4nrkN6mHh6ei2izJQ5u6KkIYwr9r94kWT1VsSKs8CIC9Y_5yJfJXWOVp1tcQJi-PpgcEF8wY1w-C047M7QUmP&ratebypass=yes'
[download] Resuming download at byte 737675
[download] Destination: Cuartos de final femeninos - Estrella Damm Valencia Open 2019 - World Padel Tour-AVITTcATgYs.f137.mp4
[download] 100.0% of 740.77KiB at  690.99B/s ETA 00:00[download] Got server HTTP error: Downloaded 758550 bytes, expected 10899467 bytes. Retrying (attempt 1 of 10)...
[download] Unable to resume
[download] Destination: Cuartos de final femeninos - Estrella Damm Valencia Open 2019 - World Padel Tour-AVITTcATgYs.f137.mp4
[download]  87.1% of 740.77KiB at  4.10MiB/s ETA 00:00[download] Got server HTTP error: Downloaded 661048 bytes, expected 758550 bytes. Retrying (attempt 2 of 10)...
[download] Unable to resume


ERROR: Did not get any data blocks
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 342, in real_download
    return download()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 320, in download
    retry(err)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 225, in retry
    raise RetryDownload(e)
RetryDownload
```

```
$ youtube-dl -v "https://www.youtube.com/watch?v=AVITTcATgYs"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=AVITTcATgYs']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.12
[debug] Python version 2.7.10 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] AVITTcATgYs: Downloading webpage
[youtube] AVITTcATgYs: Downloading video info webpage
[youtube] AVITTcATgYs: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r2---sn-h5q7knel.googlevideo.com/videoplayback?expire=1562942813&ei=_EgoXefhOISqhAeTl4-wAg&ip=83.35.59.42&id=AVITTcATgYs.1&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160&source=yt_live_broadcast&requiressl=yes&hcs=yes&mm=44%2C29&mn=sn-h5q7knel%2Csn-h5q7knel&ms=lva%2Crdu&mv=m&mvi=1&pl=16&shardbypass=yes&initcwndbps=991250&live=1&hang=1&noclen=1&mime=video%2Fmp4&gir=yes&mt=1562921118&fvip=3&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Clive%2Chang%2Cnoclen%2Cmime%2Cgir&sig=ALgxI2wwRQIgBujyyb4XCZGMh7l7fQorU44agGzG9CFmzKbA-pUC9OwCIQCHKv8mZyqi9dagF6lwZiU3luiJZHGkkpxLLqEecGdxYA%3D%3D&lsparams=hcs%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cshardbypass%2Cinitcwndbps&lsig=AHylml4wRAIgYi0-NYnXCNYQJ-BJPL4AM12fq6sPzResm1qBA2PMfM0CICsXYNCPGTxqnQn36aDpbLvEQ-EyZuXgVOuWVo6E_pD2&ratebypass=yes'
[download] Unable to resume


ERROR: Did not get any data blocks
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2008, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 861, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1642, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1909, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1854, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 342, in real_download
    return download()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 312, in download
    self.report_error('Did not get any data blocks')
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 586, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

## Description

I'm unable to reproduce live streams. It randomly downloads less than 1MB chunks and hangs. In the first attached log it downloaded two chunks (with a hang in between) and failed. In the second log it failed immediately. I am watching the stream on Safari.

Tested with two streams and both failed.
Check this one: https://www.youtube.com/watch?v=AVITTcATgYs

Tested in macOS 10.14 and 10.15, with latest youtube-dl 2019.07.12 and prior one (since the first thing I did when the stream failed was updating youtube-dl 😉)

Anyone else has this issue?

**Comment by aonez** [comment]
Duplicate of which issue?

**Comment by aonez** [comment]
Ok I suppose this one: https://github.com/ytdl-org/youtube-dl/issues/21734
Missed this one! Thanks @dstftw!
