### ISSUE TITLE
einthusan broken again

### ISSUE THREAD

**Issue by treble2019** [ytdl-org/youtube-dl#21748]
- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2019.07.12**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
youtube-dl -v https://einthusan.com/movie/watch/3gnq/?lang=marathi
[debug] System config: []
[debug] User config: [u'--restrict-filenames', u'--no-mtime']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://einthusan.com/movie/watch/3gnq/?lang=marathi']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.12
[debug] Python version 2.7.9 (CPython) - Linux-4.9.35-v7+-armv7l-with-debian-8.0
[debug] exe versions: ffmpeg 3.2.2-1, ffprobe 3.2.2-1, phantomjs 2.1.1, rtmpdump 2.4-n78-git3a1e20c-ppa8
[debug] Proxy map: {}
[generic] ?lang=marathi: Requesting header
WARNING: Could not send HEAD request to https://einthusan.com/movie/watch/3gnq/?lang=marathi: HTTP Error 405: Method Not Allowed
[generic] ?lang=marathi: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] ?lang=marathi: Extracting information
ERROR: Unsupported URL: https://einthusan.com/movie/watch/3gnq/?lang=marathi
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2357, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 1, column 1577
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3333, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://einthusan.com/movie/watch/3gnq/?lang=marathi
```

## Description

Was working a month ago! Thanks for your great work!

**Comment by tlonic** [comment]
the script for einthusan only works for einthusan.tv, which is currently down

**Comment by tlonic** [comment]
should be resolved by https://github.com/ytdl-org/youtube-dl/pull/21775

**Comment by supritshah1289** [comment]
It is broken because they have changed the naming convention of their URL.
