### ISSUE TITLE
Got server HTTP error. Retrying 

### ISSUE THREAD

**Issue by D3vJust** [ytdl-org/youtube-dl#21758]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.07.12**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v -f 137+140 https://youtu.be/lK5fOLiC6e0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'137+140', u'https://youtu.be/lK5fOLiC6e0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.12
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-5-amd64-x86_64-with-debian-10.0
[debug] exe versions: ffmpeg 4.1.3-1, ffprobe 4.1.3-1
[debug] Proxy map: {}
[youtube] lK5fOLiC6e0: Downloading webpage
[youtube] lK5fOLiC6e0: Downloading video info webpage
[youtube] lK5fOLiC6e0: Downloading MPD manifest
[debug] Invoking downloader on u'https://r3---sn-5hne6nlr.googlevideo.com/videoplayback?expire=1562983352&ei=WOcoXaS_JtCtgAfuna74Dw&ip=2001%3A4ba0%3Affe7%3A18d%3A%3A1001&id=lK5fOLiC6e0.1&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160&source=yt_live_broadcast&requiressl=yes&mm=44%2C26&mn=sn-5hne6nlr%2Csn-4g5ednse&ms=lva%2Conr&mv=u&mvi=2&pl=45&live=1&hang=1&noclen=1&mime=video%2Fmp4&gir=yes&mt=1562961426&fvip=3&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Clive%2Chang%2Cnoclen%2Cmime%2Cgir&sig=ALgxI2wwRgIhAICSCveHXbq1695WMpc1icta3Sqwr2iSohuWQJajV883AiEA-pvha3H28QTje_6L6FWWo7WtydMQOYpb4lZy__f865U%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AHylml4wRQIgV_ZPM3EUJBQGCQO0J5ll1x8xN_BySLeGiWS3mk-dJc8CIQC5GLkDAg2Osc-caxfuDXvGvawHY6qayT8fAHsxG6eBqg%3D%3D&ratebypass=yes'
[download] Destination: RESISTANCE LIVE presents RESISTANCE Croatia - DAY 1-lK5fOLiC6e0.f137.mp4
[download] 100.0% of 1.65MiB at 56.00KiB/s ETA 00:00[download] Got server HTTP error: Downloaded 1728585 bytes, expected 10346841 bytes. Retrying (attempt 1 of 10)...
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2008, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 861, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1642, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1909, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1854, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 149, in establish_connection
    content_length = ctx.data.info()['Content-Length']
  File "/usr/lib/python2.7/rfc822.py", line 393, in __getitem__
    return self.dict[name.lower()]
KeyError: u'content-length'
```

## Description

If I'm trying to download a livestream from youtube, I'll always get an "HTTP error".
I tryed downloading the livestream with different qualities. I also tryed downloading other livestreams from youtube.
Always the same problem.
The first five seconds in the mp4-file seems to be okay.

Is it a youtube side issue?

**Comment by D3vJust** [comment]
cant find issue with the same issue... @dstftw
