### ISSUE TITLE
ITV (UK) SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by baffled-mart** [ytdl-org/youtube-dl#21754]
The following error also happens on programme broadcast in June.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--restrict-filenames', '--download-archive', 'youtube-dl-history.txt', 'https://www.itv.com/hub/britains-next-prime-minister-the-itv-debate/2a7392a0001','--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.07.12
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-93298-g0ce759defd, ffprobe N-93298-g0ce759defd, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 25.94.182.170 (GB) as X-Forwarded-For.
[ITV] 2a7392a0001: Downloading webpage
[ITV] 2a7392a0001: Downloading XML
WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out
[ITV] 2a7392a0001: Downloading JSON metadata
[ITV] 2a7392a0001: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://itvpnpdotcom-a.akamaihd.net/2-7392-0001-001/18/1/VAR012/2-7392-0001-001_18_1_VAR012.ism/2-7392-0001-001_18_1_VAR012-audio=97150-video=1486000.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 500
[download] Destination: Britain_s_Next_Prime_Minister_-_The_ITV_Debate_-_Tuesday_9_Jul_8pm-2a7392a0001.mp4
[download]   0.2% of ~582.52MiB at Unknown speed ETA Unknown ETAERROR: unable to
 download video data: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1287, in connect
  File "C:\Python\Python34\lib\ssl.py", line 362, in wrap_socket
  File "C:\Python\Python34\lib\ssl.py", line 580, in __init__
  File "C:\Python\Python34\lib\ssl.py", line 807, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1hnn\build\youtube_dl\YoutubeDL.py", line 1915, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1hnn\build\youtube_dl\YoutubeDL.py", line 1854, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1hnn\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1hnn\build\youtube_dl\downloader\hls.py", line 172, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1hnn\build\youtube_dl\YoutubeDL.py", line 2227, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1hnn\build\youtube_dl\utils.py", line 2724, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_openurllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>

**Comment by baffled-mart** [comment]
For solution see,
https://github.com/ytdl-org/youtube-dl/issues/5317#issuecomment-94205465

**Comment by baffled-mart** [comment]
Using Windows 7.
Adding following command line option enables download;
--no-check-certificate
