### ISSUE TITLE
Socks5 EOFError (Windows 7)

### ISSUE THREAD

**Issue by Tsuchimikado** [ytdl-org/youtube-dl#21771]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Am I only one who get EOFError when trying to download videos using some socks5 proxies? Can download videos using http and socks4 proxies but most of socks5 proxies give me this:
```
youtube-dl.exe --proxy socks5://217.23.6.40:1080 https://www.youtube.com/watch?v=Zdl7EK0Alvo --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--proxy', 'socks5://217.23.6.40:1080', 'https://www
.youtube.com/watch?v=Zdl7EK0Alvo', '--verbose']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.07.12
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-94275-g81d3d7dd44, ffprobe N-94275-g81d3d7dd44
[debug] Proxy map: {'https': 'socks5://217.23.6.40:1080', 'http': 'socks5://217.
23.6.40:1080'}
[youtube] Zdl7EK0Alvo: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1h
nn\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1h
nn\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1h
nn\build\youtube_dl\YoutubeDL.py", line 2008, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1h
nn\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1h
nn\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1h
nn\build\youtube_dl\extractor\youtube.py", line 1663, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1h
nn\build\youtube_dl\extractor\common.py", line 794, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1h
nn\build\youtube_dl\extractor\youtube.py", line 270, in _download_webpage_handle

  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1h
nn\build\youtube_dl\extractor\common.py", line 660, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1h
nn\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1h
nn\build\youtube_dl\YoutubeDL.py", line 2227, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1h
nn\build\youtube_dl\utils.py", line 2724, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1h
nn\build\youtube_dl\utils.py", line 2690, in connect
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1h
nn\build\youtube_dl\socks.py", line 270, in connect
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1h
nn\build\youtube_dl\socks.py", line 266, in _make_proxy
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1h
nn\build\youtube_dl\socks.py", line 235, in _setup_socks5
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1h
nn\build\youtube_dl\socks.py", line 131, in _recv_bytes
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1h
nn\build\youtube_dl\socks.py", line 126, in recvall
EOFError: 2 bytes missing
```
Tried on two different machines with Windows 7 (x86/x64)
P.S. It says "C:\Users\dst\" in console but I do not have user named "dst" on both my machines

**Comment by dstftw** [comment]
Your proxy is most likely dead/misfunctioning.
