### ISSUE TITLE
youtube live stream: ERROR: This video is unavailable.

### ISSUE THREAD

**Issue by k1nghat** [ytdl-org/youtube-dl#21788]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v https://youtu.be/-PyY8LOIcm8
[debug] System config: []
[debug] User config: [u'-o', u'~/Videos/%(title)s.%(ext)s', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', u'--no-mark-watched']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://youtu.be/-PyY8LOIcm8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.14
[debug] Python version 2.7.15+ (CPython) - Linux-4.18.0-22-generic-x86_64-with-neon-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[youtube] -PyY8LOIcm8: Downloading webpage
[youtube] -PyY8LOIcm8: Downloading video info webpage
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2109, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is unavailable.
```

## Description

trying the stream links:
https://youtu.be/-PyY8LOIcm8
https://www.youtube.com/watch?v=-PyY8LOIcm8
i get: "ERROR: This video is unavailable."

my config file:
```
# Save in ~/Videos
-o ~/Videos/%(title)s.%(ext)s
-f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'
--no-mark-watched
```

**Comment by k1nghat** [comment]
sorry @dstftw, i dont see the relation to the postprocessing cutting pr as i want the entire video.

**Comment by k1nghat** [comment]
fixed with todays update. tyvm.
