### ISSUE TITLE
[redbull.com] ERROR: No video formats found

### ISSUE THREAD

**Issue by ciases** [ytdl-org/youtube-dl#21781]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl https://www.redbull.com/int-en/tv/video/AP-1XH4Y6WCN1W11/men-s-dh-finals-les-gets --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.redbull.com/int-en/tv/video/AP-1XH4Y6WCN1W11/men-s-dh-finals-les-gets', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.14
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-20-generic-x86_64-with-LinuxMint-19-tara
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[RedBullTV] AP-1XH4Y6WCN1W11: Downloading access token
[RedBullTV] AP-1XH4Y6WCN1W11: Downloading video information
[RedBullTV] AP-1XH4Y6WCN1W11: Downloading m3u8 information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/redbulltv.py", line 82, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Hello there!
I've got an 'No video formats found' error on redbull.com site with these links: 
https://www.redbull.com/int-en/tv/video/AP-1XH4Y6WCN1W11/men-s-dh-finals-les-gets
https://www.redbull.com/int-en/tv/video/AP-1XH4Y6X2D1W11/women-s-dh-finals-les-gets

**Comment by gschaffner** [comment]
Unfortunately this seems to unreproducible now, as those two links 404. This issue should be closed, I believe.

**Comment by spuky** [comment]
ran into the same issue with this url

https://www.redbull.com/int-en/live/women-downhill-2020-maribor-round-2

**Comment by spuky** [comment]
a few hours later it is working... so i guess pages are changeing after some time...
