### ISSUE TITLE
youtube-dl is not working eventhough it is the latest version

### ISSUE THREAD

**Issue by yearmfew** [ytdl-org/youtube-dl#21792]
I cant use youtube-dl. The error message on terminal is down. I have read the issues same to this. It says youtube-dl should be the latest version. I upgraded it to latest version but the problem still continues. Actually I have just installed youtube-dl and it is not working. 

My distro is linux-mint 19.01 xfce. 

~$ youtube-dl -F https://www.youtube.com/watch?v=PXis0PtqdXw
[youtube] PXis0PtqdXw: Downloading webpage
[youtube] PXis0PtqdXw: Downloading video info webpage
[youtube] PXis0PtqdXw: Extracting video information
[youtube] PXis0PtqdXw: Downloading js player vflK6rDhN
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1191, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1102, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1163, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 796, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yearmfew** [comment]
I have solved the problem. It is explained here: 
https://forums.linuxmint.com/viewtopic.php?t=293598
