### ISSUE TITLE
YouTube download failing with when time-continue is specified

### ISSUE THREAD

**Issue by toluschr** [ytdl-org/youtube-dl#21798]
## Checklist
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.07.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
```
[tom@tom-linux Music]$ youtube-dl -v -x --audio-format mp3 https://www.youtube.com/watch?time_continue=130&v=IYzlVDlE72
[3] 19781
[2]   Exit 1                  youtube-dl https://www.youtube.com/watch?time_continue=130
[tom@tom-linux Music]$ [debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-x', '--audio-format', 'mp3', 'https://www.youtube.com/watch?time_continue=130']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.21
[debug] Python version 3.7.3 (CPython) - Linux-5.1.16-300.fc30.x86_64-x86_64-with-fedora-30-Thirty
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[generic] watch?time_continue=130: Requesting header
[redirect] Following redirect to https://www.youtube.com/
[generic] www.youtube: Requesting header
WARNING: Falling back on generic information extractor.
[generic] www.youtube: Downloading webpage
[generic] www.youtube: Extracting information
ERROR: Unsupported URL: https://www.youtube.com/
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 795, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/generic.py", line 3316, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.youtube.com/

```

## Description
When I download an url copied from genius.com (lyrics site), there is a time_continue argument specified. This argument causes youtube-dl to crash and produce weird errors. I expected youtube-dl to just use the v key instead of the first one.

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
