### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by AllOgreTheWorld** [ytdl-org/youtube-dl#21790]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.07.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl https://www.youtube.com/watch?v=5ZYgIrqELFw
[youtube] 5ZYgIrqELFw: Downloading webpage
[youtube] 5ZYgIrqELFw: Downloading video info webpage
[youtube] 5ZYgIrqELFw: Downloading js player vflK6rDhN
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1236, in _decrypt_signature
    video_id, player_url, s
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1144, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1208, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
riley@TzTok-Jad:~/Downloads/youtubedl/youtube-dl$ youtube-dl --verbose https://www.youtube.com/watch?v=5ZYgIrqELFw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=5ZYgIrqELFw']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.07
[debug] Python version 3.6.8 (CPython) - Linux-4.15.0-54-generic-x86_64-with-LinuxMint-19.1-tessa
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[youtube] 5ZYgIrqELFw: Downloading webpage
[youtube] 5ZYgIrqELFw: Downloading video info webpage
[youtube] {18} signature length 105, html5 player vflK6rDhN
[youtube] 5ZYgIrqELFw: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vflK6rDhN/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1236, in _decrypt_signature
    video_id, player_url, s
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1144, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1208, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1236, in _decrypt_signature
    video_id, player_url, s
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1144, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1208, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1236, in _decrypt_signature
    video_id, player_url, s
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1144, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1208, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1894, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1246, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1236, in _decrypt_signature
    video_id, player_url, s
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1144, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1208, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/home/riley/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Main issue is Signature extraction failed, Unable to extract Initial JS player signature function name. Similar issues I could find are marked as outdated versions.

**Comment by dstftw** [comment]
>Similar issues I could find are marked as outdated versions.

No comments.
