### ISSUE TITLE
Problem with a Youtube Channel

### ISSUE THREAD

**Issue by catalan63** [ytdl-org/youtube-dl#21793]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2019.07.14**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
catalan63@optimus-portable:~$ youtube-dl -v -F "https://www.youtube.com/watch?v=c3zbvF4FIOk&t"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.youtube.com/watch?v=c3zbvF4FIOk&t']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.14
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-54-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.1.3-0york1, ffprobe 4.1.3-0york1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] c3zbvF4FIOk: Downloading webpage
[youtube] c3zbvF4FIOk: Downloading video info webpage
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 2109, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is unavailable.

## Description

WRITE DESCRIPTION HERE

Youtube-dl is not working with my channel and was working well, i dont know whats happening.

My channel is public and is:
https://www.youtube.com/channel/UCx5C_mWEjqakn5kZH7ouS1w

Thanks in advance.

**Comment by catalan63** [comment]
Already solved by last commit. Thanks for your work.
