### ISSUE TITLE
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)

### ISSUE THREAD

**Issue by Katistic** [ytdl-org/youtube-dl#21818]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.07.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.07.16
[debug] Python version 3.7.2 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg N-94324-g806ac7da69, ffprobe N-94324-g806ac7da69
[debug] Proxy map: {}
[youtube] 1CxhiUXTQHM: Downloading webpage
[youtube] 1CxhiUXTQHM: Downloading video info webpage
[youtube] Downloading just video 1CxhiUXTQHM because of --no-playlist
[debug] Invoking downloader on 'https://r3---sn-uxanug5-ntqel.googlevideo.com/videoplayback?expire=1563400419&ei=g0QvXan4E9aEssUP7JKMsA0&ip=58.167.68.51&id=o-ANkjb633K85CBOrbfSZqPMk5PQX2fais5tljdnVd3gkf&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-uxanug5-ntqel%2Csn-npoeen7d&ms=au%2Conr&mv=m&mvi=2&pl=18&initcwndbps=1648750&mime=video%2Fwebm&gir=yes&clen=5275163&dur=181.300&lmt=1557523828550054&mt=1563378733&fvip=4&keepalive=yes&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRAIgJYWtlVcLLsdV6ZbZ-FL9waGtZb1qVB7jZwQ_v5KOE9ICIGVO4LPGwKQq4iT5pdnGr_kAs2dEbE6c75a__vyLtdOo&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhAPQQywW07BFygICyvg-JIYlx9MNsHX-EKBaPP4NqucMvAiAKgT-vGOxrrAK7dPn9bIgkR1YDjo_U9gFd1oQkh98Mnw%3D%3D&ratebypass=yes'
[download] Destination: videos\1CxhiUXTQHM.f248
[download] 100% of 5.03MiB in 00:02
[debug] Invoking downloader on 'https://r3---sn-uxanug5-ntqel.googlevideo.com/videoplayback?expire=1563400419&ei=g0QvXan4E9aEssUP7JKMsA0&ip=58.167.68.51&id=o-ANkjb633K85CBOrbfSZqPMk5PQX2fais5tljdnVd3gkf&itag=251&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-uxanug5-ntqel%2Csn-npoeen7d&ms=au%2Conr&mv=m&mvi=2&pl=18&initcwndbps=1648750&mime=audio%2Fwebm&gir=yes&clen=3060122&dur=181.341&lmt=1557523060644367&mt=1563378733&fvip=4&keepalive=yes&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRAIgc2pxvShIVL1D_2vhbaIlhbOq4wETvBAk1O3iY073rBMCIGEHiXRy31CQt2qseo9CeBhnRH3if2JwunQsLMaOvJzF&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhAPQQywW07BFygICyvg-JIYlx9MNsHX-EKBaPP4NqucMvAiAKgT-vGOxrrAK7dPn9bIgkR1YDjo_U9gFd1oQkh98Mnw%3D%3D&ratebypass=yes'
[download] Destination: videos\1CxhiUXTQHM.f251
[download] 100% of 2.92MiB in 00:01
[ffmpeg] Merging formats into "videos\1CxhiUXTQHM.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:videos\1CxhiUXTQHM.f248" -i "file:videos\1CxhiUXTQHM.f251" -c copy -map "0:v:0" -map "1:a:0" "file:videos\1CxhiUXTQHM.temp.mp4"
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2054, in post_process
    files_to_delete, info = pp.run(info)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)

Traceback (most recent call last):
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2054, in post_process
    files_to_delete, info = pp.run(info)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Princess\Desktop\Assignment\main.py", line 279, in run
    self.target(*self.args, **self.kwargs)
  File "C:\Users\Princess\Desktop\Assignment\main.py", line 387, in WaitForTurn
    self.Download()
  File "C:\Users\Princess\Desktop\Assignment\main.py", line 421, in Download
    ytdl.download(["https://www.youtube.com/watch?v=" + self.video.id])
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2008, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 861, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1642, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1989, in process_info
    self.post_process(filename, info_dict)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2056, in post_process
    self.report_error(e.msg)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR:   Stream #1:0 -> #0:1 (copy)
```

## Description

There was a bug report similar to this one, but was not related (I think?)
https://github.com/ytdl-org/youtube-dl/issues/20095

Using Python 3.7.2
Happens with both of the latest ffmpegs (stable '4.1.3' and nightly '20190716-806ac7d')

Does NOT happen with all youtube urls!

My opts

```
            ydl_opts = {
                'format': vq.lower()+'video+'+aq.lower()+'audio/'+fq.lower(),
                'noplaylist': True,
                'quiet': False,
                'outtmpl': "videos/"+self.video.id,
                'progress_hooks': [self.ProgHooks],
                "nocheckcertificate": True,
                "ffmpeglocation": resource_path("."),
                "merge_output_format": "mp4",
                "verbose": True,
                'postprocessors': [{
                    'key': 'FFmpegVideoConvertor',
                    'preferedformat': 'mp4'
                }],
            }
```

Work:
https://www.youtube.com/watch?v=ih2xubMaZWI
https://www.youtube.com/watch?v=qn-X5A0gbMA

Error:
https://www.youtube.com/watch?v=-AgSCGn4Nug
https://www.youtube.com/watch?v=1CxhiUXTQHM

**Comment by dstftw** [comment]
You are merging incompatible formats into mp4.
