### ISSUE TITLE
[twitch] New URLs for past-broadcasts, highlights and uploads

### ISSUE THREAD

**Issue by lel-amri** [ytdl-org/youtube-dl#21811]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.twitch.tv/spamfish/videos?filter=archives']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.16
[debug] Python version 2.7.15 (CPython) - Linux-4.19.57-gentoo-x86_64-AMD_Ryzen_5_2600_Six-Core_Processor-with-gentoo-2.6
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[twitch:stream] spamfish: Downloading stream JSON
ERROR: spamfish is offline
Traceback (most recent call last):
  File "/home/leo/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/leo/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/leo/bin/youtube-dl/youtube_dl/extractor/twitch.py", line 581, in _real_extract
    raise ExtractorError('%s is offline' % channel_id, expected=True)
ExtractorError: spamfish is offline
```

## Description

It looks like Twitch changed its URLs for users's videos lists (ie. going from `https://www.twitch.tv/user/videos/past-broadcasts` to `https://www.twitch.tv/user/videos?filter=archives`).

**Comment by lel-amri** [comment]
Opened PR #21812
