### ISSUE TITLE
Download Video from Drive without /view

### ISSUE THREAD

**Issue by FrossGus** [ytdl-org/youtube-dl#21828]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
sudo youtube-dl --verbose --cookies cookies.txt -f 22 'https://drive.google.com/drive/folders/1CgFTHCYCxMzTYCHwqxfsg_h9XZTE4qMa'
[sudo] password for gustavo: 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--cookies', u'cookies.txt', u'-f', u'22', u'https://drive.google.com/drive/folders/1CgFTHCYCxMzTYCHwqxfsg_h9XZTE4qMa']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.16
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-54-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 1CgFTHCYCxMzTYCHwqxfsg_h9XZTE4qMa: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1CgFTHCYCxMzTYCHwqxfsg_h9XZTE4qMa: Downloading webpage
[generic] 1CgFTHCYCxMzTYCHwqxfsg_h9XZTE4qMa: Extracting information
ERROR: Unsupported URL: https://drive.google.com/drive/folders/1CgFTHCYCxMzTYCHwqxfsg_h9XZTE4qMa
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2357, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1, column 631
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3333, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://drive.google.com/drive/folders/1CgFTHCYCxMzTYCHwqxfsg_h9XZTE4qMa

```

## Description

Until last week, the videos appeared with a route similar to "/ view /", but now they can not be downloaded with "download file" from the Drive.

**Comment by dstftw** [comment]
You must either provide credentials or unrestricted URL for any work on this.
