### ISSUE TITLE
ABC Iview Share Link

### ISSUE THREAD

**Issue by bpjh56** [ytdl-org/youtube-dl#21838]
## Checklist

- [x ] I'm reporting a broken site support issue
- [ x I've verified that I'm running youtube-dl version **2019.07.16**
- [ x I've checked that all provided URLs are alive and playable in a browser
- [ x I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x've searched the bugtracker for similar bug reports including closed ones
- [ x I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
# ./youtube-dl -v https://iview.abc.net.au/show/stargazing-moon-and-beyond
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://iview.abc.net.au/show/stargazing-moon-and-beyond']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.16
[debug] Python version 2.7.15+ (CPython) - Linux-4.9.163-lxpup-32-pae-i686-with-glibc2.15
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] stargazing-moon-and-beyond: Requesting header
WARNING: Falling back on generic information extractor.
[generic] stargazing-moon-and-beyond: Downloading webpage
[generic] stargazing-moon-and-beyond: Extracting information
ERROR: Unsupported URL: https://iview.abc.net.au/show/stargazing-moon-and-beyond
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 2357, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "./youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "./youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 6, column 635
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 3333, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://iview.abc.net.au/show/stargazing-moon-and-beyond
```

## Description

WRITE DESCRIPTION HERE
In ABC Iview click Share, click Copy Link. Paste link as URL for youtube-dl. Used to work. Now does not.
Thank you for this.

**Comment by remitamine** [comment]
https://iview.abc.net.au/show/stargazing-moon-and-beyond/video/SC1809H001S00
