### ISSUE TITLE
[TVN24] HTML changed

### ISSUE THREAD

**Issue by gjedeer** [ytdl-org/youtube-dl#21833]
- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2019.07.16**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v 'https://tvnmeteo.tvn24.pl/magazyny/maja-w-ogrodzie,13/odcinki-online,1,4,1,0/pnacza-ptaki-i-iglaki-odc-691-hgtv-odc-29,1771763.html'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://tvnmeteo.tvn24.pl/magazyny/maja-w-ogrodzie,13/odcinki-online,1,4,1,0/pnacza-ptaki-i-iglaki-odc-691-hgtv-odc-29,1771763.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.16
[debug] Python version 3.6.7 (CPython) - Linux-4.15.0-54-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 18
[debug] Proxy map: {}
[TVN24] pnacza-ptaki-i-iglaki-odc-691-hgtv-odc-29,1771763.html: Downloading webpage
ERROR: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/gdr/tmp/ansible_venv/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/gdr/tmp/ansible_venv/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/gdr/tmp/ansible_venv/lib/python3.6/site-packages/youtube_dl/extractor/tvn24.py", line 42, in _real_extract
    title = self._og_search_title(webpage)
  File "/home/gdr/tmp/ansible_venv/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1117, in _og_search_title
    return self._og_search_property('title', html, **kargs)
  File "/home/gdr/tmp/ansible_venv/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1105, in _og_search_property
    escaped = self._search_regex(og_regexes, html, name, flags=re.DOTALL, **kargs)
  File "/home/gdr/tmp/ansible_venv/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

This URL doesn't download: https://tvnmeteo.tvn24.pl/magazyny/maja-w-ogrodzie,13/odcinki-online,1,4,1,0/pnacza-ptaki-i-iglaki-odc-691-hgtv-odc-29,1771763.html

There doesn't seem to be og:title tag in the source code any more, the only opengraph tag is og:url

**Comment by gjedeer** [comment]
I was able to download the video by changing 

https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/tvn24.py#L42 

to

```
title = ''
```
