### ISSUE TITLE
Discovery channel returning an error

### ISSUE THREAD

**Issue by cas4** [ytdl-org/youtube-dl#21843]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\aspears\Desktop\YouTube-Dl>youtube-dl.exe --verbose --hls-prefer-native --cookies ./cookies_discovery.txt -o ".\Movies\battlebotstest.mp4" https://www.discovery.com/tv-shows/battlebots/full-episodes/buckers-and-brawlers-2
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--hls-prefer-native', '--cookies', './cookies_discovery.txt', '-o', '.\\Movies\\battlebotstest.mp4', 'https://www.discovery.com/tv-shows/battlebots/full-episodes/buckers-and-brawlers-2']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.07.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-61620-ge555e1b, ffprobe git-2017-12-23-d02289c
[debug] Proxy map: {}
[Discovery] buckers-and-brawlers-2: Downloading webpage
[Discovery] buckers-and-brawlers-2: Downloading JSON metadata
ERROR: Access to the requested resource path is unauthorized: v1/streaming/video/5d28a90585aeee0ab80c033c [The access token provided has expired]; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\YoutubeDL.py", line 2227, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\discovery.py", line 102, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\common.py", line 892, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\common.py", line 870, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\common.py", line 660, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\common.py", line 645, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\YoutubeDL.py", line 2227, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\discovery.py", line 102, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\common.py", line 892, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\common.py", line 870, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\common.py", line 660, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\common.py", line 645, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\discovery.py", line 113, in _real_extract
youtube_dl.utils.ExtractorError: Access to the requested resource path is unauthorized: v1/streaming/video/5d28a90585aeee0ab80c033c [The access token provided has expired]; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Users\aspears\Desktop\YouTube-Dl>youtube-dl.exe --verbose --hls-prefer-native --cookies ./cookies_discovery.txt -o ".\Movies\battlebotstest.mp4" https://go.discovery.com/tv-shows/battlebots/full-episodes/buckers-and-brawlers-2
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--hls-prefer-native', '--cookies', './cookies_discovery.txt', '-o', '.\\Movies\\battlebotstest.mp4', 'https://go.discovery.com/tv-shows/battlebots/full-episodes/buckers-and-brawlers-2']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.07.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-61620-ge555e1b, ffprobe git-2017-12-23-d02289c
[debug] Proxy map: {}
[generic] buckers-and-brawlers-2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] buckers-and-brawlers-2: Downloading webpage
[generic] buckers-and-brawlers-2: Extracting information
ERROR: Unsupported URL: https://go.discovery.com/tv-shows/battlebots/full-episodes/buckers-and-brawlers-2
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\generic.py", line 3333, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://go.discovery.com/tv-shows/battlebots/full-episodes/buckers-and-brawlers-2

```

## Description

I successfully downloaded a Battle Bots episode on 7/7/2019 (s04e05), now I'm getting the above errors.  I tried the URLs "go.discovery.com/" and "www.discovery.com/" and both failed (both outputs are above).  I started watching the episode in Chrome and downloaded the cookies file twice, replaced \n with \r\n (I'm on a Windows environment) with no success.   It appears something has changed in the past few weeks.

**Comment by dstftw** [comment]
You must provide account credentials.

**Comment by cas4** [comment]
It worked previously with only the cookies file and I get the exact same error messages when I add the "--ap-mso" args,  It appears something has changed with Discovery unless there is another command line argument I'm not aware of.

**Comment by Diegus83** [comment]
The problem is that Discovery changed the URLs to "go.discovery.com" and those are not picked up by the extractor. It has been fixed by this commit
https://github.com/ytdl-org/youtube-dl/commit/3b446ab3519948980630e3328b971385826ffba8

You can run the current code in developer mode or wait for the next release which will probably include the fix.
