### ISSUE TITLE
BBC No video formats found

### ISSUE THREAD

**Issue by kuehnert** [ytdl-org/youtube-dl#21855]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2019.07.16**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --verbose --output "/mnt/video/Incoming/Porridge S03E02 Poetic Justice.mp4" https://www.bbc.co.uk/iplayer/episode/b00787cr/porridge-series-3-2-poetic-justice --ignore-config
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--output', '/mnt/video/Incoming/Porridge S03E02 Poetic Justice.mp4', 'https://www.bbc.co.uk/iplayer/episode/b00787cr/porridge-series-3-2-poetic-justice', '--ignore-config']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.16
[debug] Python version 3.5.3 (CPython) - Linux-4.19.42-v7+-armv7l-with-debian-9.9
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1
[debug] Proxy map: {}
[bbc.co.uk] b00787cr: Downloading video page
[bbc.co.uk] b00787cr: Downloading playlist JSON
[bbc.co.uk] b0003mz0: Downloading media selection XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 577, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug
```

## Description

All other files of that series download fine, except this one, with this error. I have read up on other bug reports and tried using Python 2 and removing the cache. Many thanks for any help!

**Comment by sleaux-meaux** [comment]
This is a limitation of the BBC extractor. If the first place it looks doesn't contain any streams, it bails out without looking in other locations. When this happens, you can use [get_iplayer](https://github.com/get-iplayer/get_iplayer/wiki) to download the programme.

**Comment by dstftw** [comment]
For any work on this you must provide working GB proxy/vpn.

**Comment by tombsar** [comment]
I am also facing this issue for the same programme. Anything I can do to help get this resolved?
