### ISSUE TITLE
Youtube-dl Error ENOEN: no such file or directory

### ISSUE THREAD

**Issue by joepvandepol** [ytdl-org/youtube-dl#21864]
I am using express on a heroku nodejs server. and the URL parameters are coming from a other site. The url paramters are the youtube video url, format and location. 
If I put node index.js the video downloads perfectly and the function download() works like a charm. But when I host my code on a heroku server I got a error
 `
2019-07-22T16:29:10.640375+00:00 app[web.1]: C:/Users/J/Desktop
2019-07-22T16:29:10.648243+00:00 app[web.1]: events.js:174
2019-07-22T16:29:10.648247+00:00 app[web.1]: throw er; // Unhandled 'error' event
2019-07-22T16:29:10.648249+00:00 app[web.1]: ^
2019-07-22T16:29:10.648251+00:00 app[web.1]:
2019-07-22T16:29:10.648257+00:00 app[web.1]: Error: ENOENT: no such file or directory, open 'C:/Users/J/Desktop/2pac - Starin' Through My Rear View (Music Video).mp4'
2019-07-22T16:29:10.648259+00:00 app[web.1]: Emitted 'error' event at:
2019-07-22T16:29:10.648263+00:00 app[web.1]: at errorOrDestroy (internal/streams/destroy.js:107:12)
2019-07-22T16:29:10.648265+00:00 app[web.1]: at WriteStream.onerror (_stream_readable.js:717:7)
2019-07-22T16:29:10.648267+00:00 app[web.1]: at WriteStream.emit (events.js:198:13)
2019-07-22T16:29:10.648269+00:00 app[web.1]: at lazyFs.open (internal/fs/streams.js:277:12)
2019-07-22T16:29:10.648271+00:00 app[web.1]: at FSReqWrap.args [as oncomplete] (fs.js:140:20)
2019-07-22T16:29:10.725327+00:00 heroku[web.1]: State changed from up to crashed
2019-07-22T16:29:10.706740+00:00 heroku[web.1]: Process exited with status 1
2019-07-22T16:32:49.299084+00:00 heroku[web.1]: State changed from crashed to starting
2019-07-22T16:32:52.435442+00:00 heroku[web.1]: Starting process with command `node index.js`
2019-07-22T16:32:55.257848+00:00 app[web.1]: i am listeing
2019-07-22T16:32:56.859491+00:00 heroku[web.1]: State changed from starting to up
`

Here is  the function that receive's the parameters. If I print the parameters out they are all correct. 
`
app.get('/:var1:var2:var3' , function (req, res) {
    var var1= req.query.var1;
    var var2= req.query.var2;
    var var3 = req.query.var3;

    if(var1== null) {
      var1 = "test"
    }
    if(var2 == null) {
     var2 = "test"
    }
    if(var3 == null || var3 == '') {
      var3 = "test"
    }

    download(var1,var2,var3)
    res.send();
    //res.send(var1) sends results to browser
});

`

And this is the url where I sent the parameters
`
 window.open(' https://example.com/&var1=' + var1 + '&var2='+ var2 + '&var3='+ encodeURIComponent(var3));
`

The download() function is tested locally and is working. 
I seems almost that the download() function is forgotten to execute. 

Who can help me ?

**Comment by dstftw** [comment]
Wrong forum.

**Comment by joepvandepol** [comment]
And why is that ? This is a error with the youtube-dl
