### ISSUE TITLE
merge-output-format argument seems to fail

### ISSUE THREAD

**Issue by DeStilleGast** [ytdl-org/youtube-dl#21887]
## Checklist

- [x] I've verified that I'm running youtube-dl version **2019.07.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl.exe -v --format bestvideo[ext=mp4]+bestaudio/bestvideo+bestaudio --no-playlist --console-title --merge-output-format mp4 https://www.youtube.com/watch?v=UqLBxAn6XP4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--format', 'bestvideo[ext=mp4]+bestaudio/bestvideo+bestaudio', '--no-playlist', '--console-title', '--merge-output-format', 'mp4', 'https://www.youtube.com/watch?v=UqLBxAn6XP4']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.07.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-93825-gc967128952
[debug] Proxy map: {}
[youtube] UqLBxAn6XP4: Downloading webpage
[youtube] UqLBxAn6XP4: Downloading video info webpage
[youtube] Downloading just video UqLBxAn6XP4 because of --no-playlist
[youtube] {18} signature length 103, html5 player vflaOQ0i1
[youtube] {137} signature length 107, html5 player vflaOQ0i1
[youtube] {248} signature length 107, html5 player vflaOQ0i1
[youtube] {136} signature length 107, html5 player vflaOQ0i1
[youtube] {247} signature length 107, html5 player vflaOQ0i1
[youtube] {135} signature length 103, html5 player vflaOQ0i1
[youtube] {244} signature length 107, html5 player vflaOQ0i1
[youtube] {134} signature length 103, html5 player vflaOQ0i1
[youtube] {243} signature length 107, html5 player vflaOQ0i1
[youtube] {133} signature length 103, html5 player vflaOQ0i1
[youtube] {242} signature length 107, html5 player vflaOQ0i1
[youtube] {160} signature length 107, html5 player vflaOQ0i1
[youtube] {278} signature length 103, html5 player vflaOQ0i1
[youtube] {140} signature length 103, html5 player vflaOQ0i1
[youtube] {171} signature length 107, html5 player vflaOQ0i1
[youtube] {249} signature length 107, html5 player vflaOQ0i1
[youtube] {250} signature length 107, html5 player vflaOQ0i1
[youtube] {251} signature length 107, html5 player vflaOQ0i1
[debug] Invoking downloader on 'https://r5---sn-5hne6nsk.googlevideo.com/videoplayback?expire=1564011374&ei=Dpc4XYi2EJmH7gOH9ICYAg&ip=2001%3A1c00%3A2515%3A5a00%3Ab107%3A31f8%3A9968%3Ad05e&id=o-AFAZDYlA-QEOVqS1T9HOLLJiB2CTstiMdhrkEb7A-KCq&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-5hne6nsk%2Csn-4g5ednsk&ms=au%2Conr&mv=m&mvi=4&pl=24&initcwndbps=1742500&mime=video%2Fmp4&gir=yes&clen=52527366&dur=225.558&lmt=1540432717945246&mt=1563989610&fvip=5&keepalive=yes&c=WEB&txp=5533432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhALOVuYsFFIDLM1sgN0m2_JhUK3mtaybVpm-K55al42PtAiEAqG_hy8HYtwHgZgO67ec5c3PTiMe-SeigBbGdw-iy6O0%3D&sig=ALgxI2wwRQIhAKTf2mcV2e2mU9AyVhaZMYhbtfttrPfg7N_rpAUrnRdxAiAoM1z_Eu6C8OExTvZN74RUE3z_432D5W2OyRaiRr_MHw==&ratebypass=yes'
[download] Destination: Matryoshka -Club Mix- (English Cover)【JubyPhonic + rachie】マトリョシカ-UqLBxAn6XP4.f137.mp4
[download] 100% of 50.09MiB in 00:24
[debug] Invoking downloader on 'https://r5---sn-5hne6nsk.googlevideo.com/videoplayback?expire=1564011374&ei=Dpc4XYi2EJmH7gOH9ICYAg&ip=2001%3A1c00%3A2515%3A5a00%3Ab107%3A31f8%3A9968%3Ad05e&id=o-AFAZDYlA-QEOVqS1T9HOLLJiB2CTstiMdhrkEb7A-KCq&itag=251&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-5hne6nsk%2Csn-4g5ednsk&ms=au%2Conr&mv=m&mvi=4&pl=24&initcwndbps=1742500&mime=audio%2Fwebm&gir=yes&clen=3548677&dur=225.601&lmt=1540434500830367&mt=1563989610&fvip=5&keepalive=yes&c=WEB&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhALOVuYsFFIDLM1sgN0m2_JhUK3mtaybVpm-K55al42PtAiEAqG_hy8HYtwHgZgO67ec5c3PTiMe-SeigBbGdw-iy6O0%3D&sig=ALgxI2wwRQIgYhkvBvSKVzlrfJ8GrQqazzDDCR2KrZLDW-UYjCpMwoMCIQDORj-ppo4l-A1dljN_7GLHomh_Xc6mwFwjH-WxF_6cbw==&ratebypass=yes'
[download] Destination: Matryoshka -Club Mix- (English Cover)【JubyPhonic + rachie】マトリョシカ-UqLBxAn6XP4.f251.webm
[download] 100% of 3.38MiB in 00:01
[ffmpeg] Merging formats into "Matryoshka -Club Mix- (English Cover)【JubyPhonic + rachie】マトリョシカ-UqLBxAn6XP4.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Matryoshka -Club Mix- (English Cover)【JubyPhonic + rachie】マトリョシカ-UqLBxAn6XP4.f137.mp4" -i "file:Matryoshka -Club Mix- (English Cover)【JubyPhonic + rachie】マトリョシカ-UqLBxAn6XP4.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:Matryoshka -Club Mix- (English Cover)【JubyPhonic + rachie】マトリョシカ-UqLBxAn6XP4.temp.mp4"
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\YoutubeDL.py", line 2054, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\postprocessor\ffmpeg.py", line 512, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)
```

## Description

After converting I noticed that certain files aren't deleted from the given command (it kept an webm and a empty mp4 file) and the filled mp4 file is the video without sound. are my arguments wrong or is this a bug

**Comment by dstftw** [comment]
You can't merge mp4+webm into mp4.
