### ISSUE TITLE
Is this going to be handled? youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name

### ISSUE THREAD

**Issue by bileser** [ytdl-org/youtube-dl#21912]
youtube-dl --audio-format mp3 https://www.youtube.com/watch?v=VBWPI-95TSY --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--audio-format', 'mp3', 'https://www.youtube.com/watch?v=VBWPI-95TSY', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.24
[debug] Python version 3.5.3 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[youtube] VBWPI-95TSY: Downloading webpage
[youtube] VBWPI-95TSY: Downloading video info webpage
[youtube] {18} signature length 103, html5 player vfl7A19HM
[youtube] VBWPI-95TSY: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vfl7A19HM/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1236, in _decrypt_signature
    video_id, player_url, s
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1144, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1208, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1236, in _decrypt_signature
    video_id, player_url, s
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1144, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1208, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1236, in _decrypt_signature
    video_id, player_url, s
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1144, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1208, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1902, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1246, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1236, in _decrypt_signature
    video_id, player_url, s
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1144, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1208, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Hrxn** [comment]
Your version of youtube-dl is outdated!

**Comment by bileser** [comment]
Before: 
sudo pip3 install -U youtube-dl
...
Successfully installed youtube-dl-2019.7.27
How ist this outdated?
