### ISSUE TITLE
Steam Game Teaser Videos not downloaded any more

### ISSUE THREAD

**Issue by WalterZimmer** [ytdl-org/youtube-dl#21917]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.27**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
youtube-dl -v https://store.steampowered.com/app/812160
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://store.steampowered.com/app/812160']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.27
[debug] Python version 2.7.13 (CPython) - Linux-4.4.104-18.44-default-x86_64-with-SuSE-42.2-x86_64
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[Steam] 812160: Downloading webpage
ERROR: Unable to extract flash vars; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/steam.py", line 90, in _real_extract
    'flash vars'), playlist_id, js_to_json)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract flash vars; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE
Hi, I happily use youtube-dl to download the Steam game teaser videos. I noticed this is not working any more since a week or so. Probably just a small adaption to reference the correct flash vars. Relevant issue date back to 2018 and are surely not relevant as it was working weeks ago. Thanks!

**Comment by alterNERDtive** [comment]
Just hopping in here to say it’s still an issue in 2020.05.03, obviously :)

**Comment by WalterZimmer** [comment]
My current workaround is to cut'n'paste the video link from the player as a wget argument, and substitute "_480" by "_max" to get the highest resolution. Unfortunately the appid changes from video to video, I guess this is what the player code extracted in the older version which is now not working any more. Can anyone give top level directions on how to reinstate this functionality? Thanks!
