### ISSUE TITLE
youtube_dl.utils.ExtractorError: This video is unavailable.

### ISSUE THREAD

**Issue by nadermx** [ytdl-org/youtube-dl#21931]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.27**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -vvv "ytsearch10:requiem for a dream" --skip-download
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vvv', 'ytsearch10:requiem for a dream', '--skip-download']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.27
[debug] Python version 3.7.4 (CPython) - Linux-4.15.0-55-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:search] query "requiem for a dream": Downloading page 1
[download] Downloading playlist: requiem for a dream
[youtube:search] playlist requiem for a dream: Collected 10 video ids (downloading 10 of them)
[download] Downloading video 1 of 10
[youtube] yVIRcnlRKF8: Downloading webpage
[youtube] yVIRcnlRKF8: Downloading video info webpage
[youtube] {18} signature length 103, html5 player vfl7A19HM
[youtube] {137} signature length 107, html5 player vfl7A19HM
[youtube] {248} signature length 107, html5 player vfl7A19HM
[youtube] {136} signature length 107, html5 player vfl7A19HM
[youtube] {247} signature length 107, html5 player vfl7A19HM
[youtube] {135} signature length 103, html5 player vfl7A19HM
[youtube] {244} signature length 103, html5 player vfl7A19HM
[youtube] {134} signature length 107, html5 player vfl7A19HM
[youtube] {243} signature length 107, html5 player vfl7A19HM
[youtube] {133} signature length 107, html5 player vfl7A19HM
[youtube] {242} signature length 107, html5 player vfl7A19HM
[youtube] {160} signature length 107, html5 player vfl7A19HM
[youtube] {278} signature length 107, html5 player vfl7A19HM
[youtube] {140} signature length 103, html5 player vfl7A19HM
[youtube] {249} signature length 107, html5 player vfl7A19HM
[youtube] {250} signature length 107, html5 player vfl7A19HM
[youtube] {251} signature length 107, html5 player vfl7A19HM
[debug] Default format spec: best/bestvideo+bestaudio
[download] Downloading video 2 of 10
[youtube] 7YQEDu07Y8Y: Downloading webpage
[youtube] 7YQEDu07Y8Y: Downloading video info webpage
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/home/www/env/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/www/env/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/www/env/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 2108, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.

```

## Description
When trying to use the `ytsearch` funcion, on some search when trying to do 10 videos, it breaks if one of the videos has a issue.  For example the search `youtube-dl -vvv "ytsearch10:requiem for a dream" --skip-download`

**Comment by remitamine** [comment]
```
-i, --ignore-errors              Continue on download errors, for example to
                                 skip unavailable videos in a playlist
```

**Comment by Aaron98990** [comment]
Thanks @remitamine! Your comment has helped me resolve my issue.
