### ISSUE TITLE
[BUG][YOUTUBE] Unable to extract uploader name 

### ISSUE THREAD

**Issue by wildgeece96** [ytdl-org/youtube-dl#21949]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

I cannot download video. I checked the url, and it worked.  

```shell 
$ youtube-dl https://www.youtube.com/watch?v=1ZAw3oOacWs --verbose              
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=1ZAw3oOacWs', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.6.8 (CPython) - Linux-4.15.0-51-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6-0ubuntu0.18.04.1, ffprobe 3.4.6-0ubuntu0.18.04.1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 1ZAw3oOacWs: Downloading webpage
[youtube] 1ZAw3oOacWs: Downloading video info webpage
WARNING: Unable to extract video title
[youtube] 1ZAw3oOacWs: Extracting video information
ERROR: Unable to extract uploader name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1704, in _real_extract
    raise ExtractorError('Unable to extract uploader name')
youtube_dl.utils.ExtractorError: Unable to extract uploader name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$ youtube-dl --version                                                          
2018.03.14
```

**Comment by WolfgangFahl** [comment]
see e.g. https://askubuntu.com/questions/380438/how-can-i-update-youtube-dl

**Comment by nnicolopez** [comment]
I had the same problem due to an outdated version installled by ubuntu package manager, the solution for me was uninstall youtube-dl and installing it againg with snap.
`sudo apt-get remove -y youtube-dl`
`sudo snap install youtube-dl`

**Comment by guillermo-arrambide** [comment]
> I had the same problem due to an outdated version installled by ubuntu package manager, the solution for me was uninstall youtube-dl and installing it againg with snap.
> `sudo apt-get remove -y youtube-dl`
> `sudo snap install youtube-dl`

Yep, this turned out to be the solution for me as well. Seems like Snap packages are gaining traction and / or Canonical is favouring it's use over APT.
