### ISSUE TITLE
Linux Academy Download Issues

### ISSUE THREAD

**Issue by encript** [ytdl-org/youtube-dl#21940]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.27**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v -u username -p password 'https://linuxacademy.com/cp/modules/view/id/238'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://linuxacademy.com/cp/modules/view/id/238']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.27
[debug] Python version 2.7.16 (CPython) - Linux-5.1.19-300.fc30.x86_64-x86_64-with-fedora-30-Thirty
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4
[debug] Proxy map: {}
[LinuxAcademy] Downloading authorize page
[LinuxAcademy] Downloading login page
[LinuxAcademy] Downloading callback page
[LinuxAcademy] Downloading token validation page
[LinuxAcademy] 238: Downloading webpage
[download] Downloading playlist: 238
[LinuxAcademy] playlist 238: Collected 50 video ids (downloading 50 of them)
[download] Downloading video 1 of 50
[LinuxAcademy] 2530-1: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2008, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 807, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1006, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 868, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/linuxacademy.py", line 165, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2645, in _extract_jwplayer_data
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2651, in _parse_jwplayer_data
TypeError: argument of type 'NoneType' is not iterable

```

## Description

I am unable to download videos from Linux Academy. I have tried using various versions of youtube-dl. I am currently using the latest version noted in the above verbose output. Could something have changed in the site. I have tested using other sites which was successful in downloading videos. Video is indeed playable from browser. URLs are valid. Other issues which were posted of a similar nature have been closed or marked as incomplete. I have tried on different machines it doesn't appear to be working. The site may have changed. Please confirm.

**Comment by Th3G4mbl3r** [comment]
I am facing the same issue as well. Here is my output details:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://linuxacademy.com/cp/modules/view/id/305']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.02
[debug] Python version 2.7.11 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.2, avprobe 12.2, ffmpeg N-94433-gf60b1211b2, ffprobe N-94433-gf60b1211b2
[debug] Proxy map: {}
[LinuxAcademy] Downloading authorize page
[LinuxAcademy] Downloading login page
[LinuxAcademy] Downloading callback page
[LinuxAcademy] Downloading token validation page
[LinuxAcademy] 305: Downloading webpage
[download] Downloading playlist: Certified Kubernetes Application Developer (CKAD)
[LinuxAcademy] playlist Certified Kubernetes Application Developer (CKAD): Collected 31 video ids (downloading 31 of them)
[download] Downloading video 1 of 31
[LinuxAcademy] 3719-1: Downloading webpage
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2008, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 807, in extract_info
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1006, in process_ie_result
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 868, in process_ie_result
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "./youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "./youtube-dl/youtube_dl/extractor/linuxacademy.py", line 165, in _real_extract
  File "./youtube-dl/youtube_dl/extractor/common.py", line 2645, in _extract_jwplayer_data
  File "./youtube-dl/youtube_dl/extractor/common.py", line 2651, in _parse_jwplayer_data
TypeError: argument of type 'NoneType' is not iterable
