### ISSUE TITLE
[ITV] TLSV1_ALERT_INTERNAL_ERROR

### ISSUE THREAD

**Issue by ProgrammerAKL** [ytdl-org/youtube-dl#21951]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.30**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -o "C:/Video/Beecham House %(title)s.%(ext)s"  "https://www.itv.com/hub/beecham-house/2a5715a0005" --verbose --no-check-certificate --ignore-errors
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'C:/Video/Beecham House %(title)s.%(ext)s', 'https://www.itv.com/hub/beecham-house/2a5715a0005', '--verbose', '--no-check-certificate', '--ignore-errors']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.07.30
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.10586
[debug] exe versions: phantomjs 2.1.1
[debug] Proxy map: {}
[debug] Using fake IP 25.133.132.178 (GB) as X-Forwarded-For.
[ITV] 2a5715a0005: Downloading webpage
[ITV] 2a5715a0005: Downloading XML
WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out
[ITV] 2a5715a0005: Downloading JSON metadata
[ITV] 2a5715a0005: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://itvpnpdotcom-a.akamaihd.net/2-5715-0005-001/18/1/VAR012/2-5715-0005-001_18_1_VAR012.ism/2-5715-0005-001_18_1_VAR012-audio=128000-video=1423094.m3u8'
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:600)>
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1287, in connect
  File "C:\Python\Python34\lib\ssl.py", line 362, in wrap_socket
  File "C:\Python\Python34\lib\ssl.py", line 580, in __init__
  File "C:\Python\Python34\lib\ssl.py", line 807, in do_handshake
ssl.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3oef8xsp\build\youtube_dl\YoutubeDL.py", line 1915, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3oef8xsp\build\youtube_dl\YoutubeDL.py", line 1854, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3oef8xsp\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3oef8xsp\build\youtube_dl\downloader\hls.py", line 62, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3oef8xsp\build\youtube_dl\YoutubeDL.py", line 2227, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3oef8xsp\build\youtube_dl\utils.py", line 2724, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:600)>
```

```
youtube-dl -o "C:/Video/Beecham House %(title)s.%(ext)s"  "https://www.itv.com/hub/beecham-house/2a5715a0005" --verbose --no-check-certificate --ignore-errors
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'C:/Video/Beecham House %(title)s.%(ext)s', 'https://www.itv.com/hub/beecham-house/2a5715a0005', '--verbose', '--no-check-certificate', '--ignore-errors']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.07.30
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.10586
[debug] exe versions: phantomjs 2.1.1
[debug] Proxy map: {}
[debug] Using fake IP 25.143.160.84 (GB) as X-Forwarded-For.
[ITV] 2a5715a0005: Downloading webpage
[ITV] 2a5715a0005: Downloading XML
WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out
[ITV] 2a5715a0005: Downloading JSON metadata
[ITV] 2a5715a0005: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:600)>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3oef8xsp\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3oef8xsp\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3oef8xsp\build\youtube_dl\extractor\itv.py", line 260, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3oef8xsp\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
youtube-dl -o "C:/Video/Beecham House %(title)s.%(ext)s"  "https://www.itv.com/hub/beecham-house/2a5715a0006" --verbose --list-formats
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'C:/Video/Beecham House %(title)s.%(ext)s', 'https://www.itv.com/hub/beecham-house/2a5715a0006', '--verbose', '--list-formats']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.07.30
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.10586
[debug] exe versions: phantomjs 2.1.1
[debug] Proxy map: {}
[debug] Using fake IP 25.168.101.94 (GB) as X-Forwarded-For.
[ITV] 2a5715a0006: Downloading webpage
[ITV] 2a5715a0006: Downloading XML
WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out
[ITV] 2a5715a0006: Downloading JSON metadata
[ITV] 2a5715a0006: Downloading m3u8 information
[info] Available formats for 2a5715a0006:
format code  extension  resolution note
hls-136      mp4        audio only  136k , mp4a.40.2@128k
hls-582      mp4        512x288     582k , avc1.64001F@ 420k, 25.0fps, mp4a.40.2@128k
hls-770      mp4        512x288     770k , avc1.64001F@ 597k, 25.0fps, mp4a.40.2@128k
hls-1041     mp4        896x504    1041k , avc1.64001F@ 853k, 25.0fps, mp4a.40.2@128k
hls-1330     mp4        896x504    1330k , avc1.64001F@1126k, 25.0fps, mp4a.40.2@128k
hls-1605     mp4        896x504    1605k , avc1.64001F@1385k, 25.0fps, mp4a.40.2@128k (best)
```

```
youtube-dl -o "C:/Video/Beecham House %(title)s.%(ext)s"  "https://www.itv.com/hub/beecham-house/2a5715a0005" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'C:/Video/Beecham House %(title)s.%(ext)s', 'https://www.itv.com/hub/beecham-house/2a5715a0005', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.07.30
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.10586
[debug] exe versions: phantomjs 2.1.1
[debug] Proxy map: {}
[debug] Using fake IP 25.188.76.167 (GB) as X-Forwarded-For.
[ITV] 2a5715a0005: Downloading webpage
[ITV] 2a5715a0005: Downloading XML
WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out
[ITV] 2a5715a0005: Downloading JSON metadata
[ITV] 2a5715a0005: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://itvpnpdotcom-a.akamaihd.net/2-5715-0005-001/18/1/VAR012/2-5715-0005-001_18_1_VAR012.ism/2-5715-0005-001_18_1_VAR012-audio=128000-video=1423094.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 238
[download] Destination: C:\Video\Beecham House Episode 5.mp4
[download]   6.7% of ~537.66MiB at 194.97KiB/s ETA 43:53     ERROR: unable to download video data: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:600)>
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1287, in connect
  File "C:\Python\Python34\lib\ssl.py", line 362, in wrap_socket
  File "C:\Python\Python34\lib\ssl.py", line 580, in __init__
  File "C:\Python\Python34\lib\ssl.py", line 807, in do_handshake
ssl.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\YoutubeDL.py", line 1912, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\YoutubeDL.py", line 1851, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\downloader\hls.py", line 148, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\downloader\fragment.py", line 102, in _download_fragment
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\YoutubeDL.py", line 2215, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\utils.py", line 1140, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:600)>
```

```
youtube-dl -o "C:/Video/Beecham House %(title)s.%(ext)s"  "https://www.itv.com/hub/beecham-house/2a5715a0006" --verbose --list-formats
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'C:/Video/Beecham House %(title)s.%(ext)s', 'https://www.itv.com/hub/beecham-house/2a5715a0006', '--verbose', '--list-formats']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.07.30
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.10586
[debug] exe versions: phantomjs 2.1.1
[debug] Proxy map: {}
[debug] Using fake IP 25.154.127.145 (GB) as X-Forwarded-For.
[ITV] 2a5715a0006: Downloading webpage
[ITV] 2a5715a0006: Downloading XML
WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out
[ITV] 2a5715a0006: Downloading JSON metadata
[ITV] 2a5715a0006: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:600)>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3oef8xsp\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3oef8xsp\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3oef8xsp\build\youtube_dl\extractor\itv.py", line 260, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3oef8xsp\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Strangely, sometimes the verbose output includes the message 'No video formats found' and sometimes it doesn't. On one try, it actually successfully downloaded the first 3 minutes and then suddenly the download stopped with the error TLSV1_ALERT_INTERNAL_ERROR. Notice that using --list-formats sometimes managed to produce the list of format codes ... well, a little while earlier, it did, but not anymore.

**Comment by DerBunteBall** [comment]
This isn't extractor related.

See this:

`
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-c', u'https://www.tvnow.de/shows/das-familiengericht-10734']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.30
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[TVNowShow] 10734: Downloading JSON metadata
[download] Downloading playlist: 10734
[TVNowShow] playlist 10734: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[TVNowAnnual] 2019-07: Downloading JSON metadata
[download] Downloading playlist: 10734/2019-07
[TVNowAnnual] playlist 10734/2019-07: Collected 120 video ids (downloading 120 of them)
[download] Downloading video 1 of 120
[TVNow] das-familiengericht/vorstadttraeume-die-sterne-stehen-schlecht: Downloading JSON metadata
[TVNow] 1639749: Downloading MPD manifest
[TVNow] 1639749: Downloading MPD manifest
[TVNow] 1639749: Downloading ISM manifest
[TVNow] 1639749: Downloading ISM manifest
[TVNow] 1639749: Downloading m3u8 information
[TVNow] 1639749: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://vodnowusoawsdash-a.akamaihd.net/proxy195/clear/ngvod/tvnow/1639749-1-75887.ism/.mpd?filter='
[dashsegments] Total fragments: 1355
[download] Destination: Vorstadtträume _ Die Sterne stehen schlecht-1639749.fdash-video=3000000.mp4
[download]   1.3% of ~856.82MiB at  3.52MiB/s ETA 01:01ERROR: unable to download video data: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:727)>
Traceback (most recent call last):
  File "/usr/local/Own/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1909, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/Own/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1854, in dl
    return fd.download(name, info)
  File "/usr/local/Own/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/Own/bin/youtube-dl/youtube_dl/downloader/dash.py", line 48, in real_download
    success, frag_content = self._download_fragment(ctx, fragment_url, info_dict)
  File "/usr/local/Own/bin/youtube-dl/youtube_dl/downloader/fragment.py", line 102, in _download_fragment
    'http_headers': headers or info_dict.get('http_headers'),
  File "/usr/local/Own/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/Own/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/Own/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/Own/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Own/bin/youtube-dl/youtube_dl/utils.py", line 2724, in https_open
    req, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:727)>
`

This appears randomly. Other downloads work completely eg. this https://www.tvnow.de/shows/das-strafgericht-nitro-1819
