### ISSUE TITLE
DASH LiveTV stream from mediavitrina.ru not playing

### ISSUE THREAD

**Issue by SlazE888** [ytdl-org/youtube-dl#21969]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.07.30**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://edge02r.mediavitrina.ru/dash-live11/streams/iz/iz.mpd']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.07.30
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[generic] iz: Requesting header
WARNING: Falling back on generic information extractor.
[generic] iz: Downloading webpage
[generic] iz: Extracting information
ERROR: No video formats found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3oef8xsp\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3oef8xsp\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3oef8xsp\build\youtube_dl\extractor\generic.py", line 2379, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3oef8xsp\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found

**Comment by dstftw** [comment]
Stop mentioning unrelated 3rdp

**Comment by SlazE888** [comment]
@dstftw I don't see any duplicates from the link you gave. More over i try all URLs[template is the same- https://edge02r.mediavitrina.ru/dash-live11/streams/{AlphabeticTVstreamID}/{AlphabeticTVstreamID}.mpd] below on youtube-dl version 2019.08.02 and it all still fails:
 [https://edge02r.mediavitrina.ru/dash-live11/streams/ctc-dom/ctc-dom.mpd](url)
 [https://edge02r.mediavitrina.ru/dash-live11/streams/tv5/tv5.mpd](url)
[https://edge02r.mediavitrina.ru/dash-live11/streams/tk78/tk78.mpd](url)
