### ISSUE TITLE
Latest Bug - asked to report

### ISSUE THREAD

**Issue by superchap** [ytdl-org/youtube-dl#21963]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2019.07.30**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

Issues downloading a YouTube vid.  I LOVE your program, by the way. Here are the details. Hope this helps. Linux Mint 

xxxx@xxxx ~ $ youtube-dl -k --output --verbose "~/Desktop/GerardMorin/%(title)s.%(ext)s" https://youtu.be/KVeDKuHPDK8
ERROR: fixed output name but more than one file to download
xxxx@xxxx ~ $ youtube-dl -k --output "~/Desktop/GerardMorin/%(title)s.%(ext)s" https://youtu.be/KVeDKuHPDK8
[youtube] KVeDKuHPDK8: Downloading webpage
[youtube] KVeDKuHPDK8: Downloading video info webpage
WARNING: Unable to extract video title
[youtube] KVeDKuHPDK8: Downloading js player vflPI0brM
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by superchap** [comment]
I ran the update command but it stated 

xxxx@xxxx ~ $ sudo youtube-dl -U
[sudo] password for jeff: 
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.

The Synaptic Package Manager says I have the current version of youtube-dl (2016.02.22-1) ... but that looks like a 2016 year and version. What command should I run for linux mint to get this up-to-date? Thanks in advance.
![Is there a more current mint version - is synaptic package manager wrong](https://user-images.githubusercontent.com/6477792/62264690-a2ff4880-b3e6-11e9-8737-81a578930f84.png)

**Comment by superchap** [comment]
also just tried this ...


xxxx@xxxx ~ $ sudo apt-get install youtube-dl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
youtube-dl is already the newest version (2016.02.22-1).
The following packages were automatically installed and are no longer required:
  libwireshark8 libwiretap6 libwscodecs1 libwsutil7 mint-meta-core mintwelcome
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.


BUT, IT'S NOT WORKING ... was working fine this morning.

xxxx@xxxx ~ $ youtube-dl -k --output "~/Desktop/GerardMorin/%(title)s.%(ext)s" https://youtu.be/q1ZKqIOgYQM
[youtube] q1ZKqIOgYQM: Downloading webpage
[youtube] q1ZKqIOgYQM: Downloading video info webpage
WARNING: Unable to extract video title
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] /home/jeff/Desktop/GerardMorin/_.mkv has already been downloaded and merged
