### ISSUE TITLE
Unable to download video from PBS

### ISSUE THREAD

**Issue by jb-chauncy** [ytdl-org/youtube-dl#21984]
## Checklist

- [x ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2019.08.02**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log
youtube-dl --verbose "https://www.pbs.org/wgbh/nova/video/the-planets-inner-worlds"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.pbs.org/wgbh/nova/video/the-planets-inner-worlds']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.02
[debug] Python version 2.7.10 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4
[debug] Proxy map: {}
[debug] Using fake IP 3.88.126.194 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] the-planets-inner-worlds: Downloading webpage
[pbs] Downloading widget/partnerplayer page
[pbs] Downloading portalplayer page
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 661, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
## Description

WRITE DESCRIPTION HERE

**Comment by appleton-tom** [comment]
Try using https://www.pbs.org/video/the-planets-inner-worlds-jhasvd/ instead

**Comment by Vangelis66** [comment]
(Most probably) Duplicate of https://github.com/ytdl-org/youtube-dl/issues/21884 😉

**Comment by ryansonshine** [comment]
Also having this issue

```
  ~/Downloads/manual  youtube-dl --version
2019.10.16
  ~/Downloads/manual  youtube-dl https://www.pbs.org/wgbh/nova/video/why-bridges-collapse/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.pbs.org/wgbh/nova/video/why-bridges-collapse/', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.16
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-62-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.15, avprobe 2.8.15, ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[debug] Using fake IP 3.142.189.231 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] why-bridges-collapse: Downloading webpage
[pbs] Downloading widget/partnerplayer page
[pbs] Downloading portalplayer page
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 661, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Vangelis66** [comment]
@ryansonshine: The **NOVA** branding is a subset of the PBS video library that the youtube-dl **PBS** extractor does not immediately support; given that this issue has been communicated to the app maintainers some time ago, and no action has been taken thus far, signals that they either don't have the inclination or simply the time to deal with it - this is no criticism expressed on my part, just the harsh reality of a small team of devs having to deal and maintain a plethora of extractors - every community member with Python-fu is free to submit a PR fixing this issue...

As I had already posted just above your last comment, this issue is a duplicate of a previous one, and details of how to apply a workaround can be found [here](https://github.com/ytdl-org/youtube-dl/issues/21884#issuecomment-515638943); it just took me 2min to locate the equivalent plain (not NOVA) PBS link for the episode you're after, 

https://www.pbs.org/wgbh/nova/video/why-bridges-collapse/ => https://www.pbs.org/video/why-bridges-collapse-ym374u/

perhaps from now on you could do the same for future NOVA episodes you'd like to fetch? 

Best regards 😄

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/27605

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/25454
https://github.com/ytdl-org/youtube-dl/issues/28749
https://github.com/ytdl-org/youtube-dl/issues/30205

**Comment by 89z** [comment]
I have an alternate tool that works:

~~~
pbs https://www.pbs.org/wgbh/nova/video/the-planets-inner-worlds/
~~~

https://github.com/89z/mech

**Comment by 89z** [comment]
It seems each PBS show requires its own extractor. [Here is][1] one for Nova:

~~~
PS C:\> pbs -i -a https://www.pbs.org/wgbh/nova/video/the-planets-inner-worlds/
GET https://www.pbs.org/wgbh/nova/video/the-planets-inner-worlds/
GET https://player.pbs.org/partnerplayer/FvibjeL8klt7Hf9IWWVjTQ==/?topbar=false&end=0&endscreen=true&start=0&autoplay=false
GET https://urs.pbs.org/redirect/37610adc875d44a8873bb88cb5e4e98b/
Resolution:1280x720 Bandwidth:5299809 Codecs:avc1.64001f,mp4a.40.2
Resolution:1920x1080 Bandwidth:7515993 Codecs:avc1.640028,mp4a.40.2
Resolution:1280x720 Bandwidth:3578698 Codecs:avc1.64001f,mp4a.40.2
Resolution:960x540 Bandwidth:2447318 Codecs:avc1.64001f,mp4a.40.2
Resolution:768x432 Bandwidth:1415352 Codecs:avc1.64001e,mp4a.40.2
Resolution:640x360 Bandwidth:960346 Codecs:avc1.64001e,mp4a.40.2
Resolution:480x270 Bandwidth:511099 Codecs:avc1.640015,mp4a.40.2
Resolution:416x234 Bandwidth:252169 Codecs:avc1.64000c,mp4a.40.2
~~~

[1]://github.com/89z/mech/blob/v1.50.7/pbs/nova.go
