### ISSUE TITLE
An extractor error has occurred. [extractor: ZDF]

### ISSUE THREAD

**Issue by keanubb** [ytdl-org/youtube-dl#21993]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.08.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

$ youtube-dl -v --ignore-config https://www.zdf.de/serien/death-in-paradise/die-smaragdinsel-100.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--ignore-config', u'https://www.zdf.de/serien/death-in-paradise/die-smaragdinsel-100.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.02
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-55-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1
[debug] Proxy map: {}
[ZDF] die-smaragdinsel-100: Downloading webpage
[ZDF] die-smaragdinsel-100: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError(u'formitaeten',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/zdf.py", line 235, in _real_extract
    return self._extract_mobile(video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/zdf.py", line 196, in _extract_mobile
    for f in document['formitaeten']:
KeyError: u'formitaeten'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 543, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'formitaeten',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

The extractor ZDF works for some pages (e.g. https://www.zdf.de/serien/death-in-paradise/death-in-paradise-staffel-1-folge-6-102.html), for others it fails (e.g. https://www.zdf.de/serien/death-in-paradise/die-smaragdinsel-100.html)

**Comment by keanubb** [comment]
Sorry page is alive but does not play.

**Comment by agaylard** [comment]
I've just seen this same error.  Is this issue fixed? (I see it is closed)

My error log is:

```
youtube-dl --verbose https://www.zdf.de/serien/der-staatsanwalt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.zdf.de/serien/der-staatsanwalt']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.02
[debug] Python version 2.7.15+ (CPython) - Linux-5.0.0-23-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[ZDFChannel] der-staatsanwalt: Downloading webpage
[download] Downloading playlist: Der Staatsanwalt
[ZDFChannel] playlist Der Staatsanwalt: Collected 10 video ids (downloading 10 of them)
[download] Downloading video 1 of 10
[ZDF] der-schein-truegt-kriminalreihe-100: Downloading webpage
[ZDF] der-schein-truegt-kriminalreihe-100: Downloading JSON content
[ZDF] der-schein-truegt-kriminalreihe-100: Downloading JSON metadata
[ZDF] der-schein-truegt-kriminalreihe-100: Downloading m3u8 information
[ZDF] der-schein-truegt-kriminalreihe-100: Downloading m3u8 information
[ZDF] der-schein-truegt-kriminalreihe-100: Downloading f4m manifest
[ZDF] der-schein-truegt-kriminalreihe-100: Downloading f4m manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://zdfvodnone-vh.akamaihd.net/i/meta-files/zdf/smil/m3u8/300/16/01/160115_2015_sendung_sta/2/160115_2015_sendung_sta.smil/index_3296000_av.m3u8'
[download] Der Schein trügt-der-schein-truegt-kriminalreihe-100.mp4 has already been downloaded
[download] 100% of 1.09GiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:Der Schein trügt-der-schein-truegt-kriminalreihe-100.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "Der Schein trügt-der-schein-truegt-kriminalreihe-100.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Der Schein trügt-der-schein-truegt-kriminalreihe-100.mp4' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:Der Schein trügt-der-schein-truegt-kriminalreihe-100.temp.mp4'
[download] Downloading video 2 of 10
[ZDF] mord-nach-mitternacht-kriminalreihe-100: Downloading webpage
[ZDF] mord-nach-mitternacht-kriminalreihe-100: Downloading JSON content
[ZDF] mord-nach-mitternacht-kriminalreihe-100: Downloading JSON metadata
[ZDF] mord-nach-mitternacht-kriminalreihe-100: Downloading m3u8 information
[ZDF] mord-nach-mitternacht-kriminalreihe-100: Downloading m3u8 information
[ZDF] mord-nach-mitternacht-kriminalreihe-100: Downloading f4m manifest
[ZDF] mord-nach-mitternacht-kriminalreihe-100: Downloading f4m manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://zdfvodnone-vh.akamaihd.net/i/meta-files/zdf/smil/m3u8/300/16/01/160108_2015_sendung_sta/3/160108_2015_sendung_sta.smil/index_3296000_av.m3u8'
[download] Mord nach Mitternacht-mord-nach-mitternacht-kriminalreihe-100.mp4 has already been downloaded
[download] 100% of 1.09GiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:Mord nach Mitternacht-mord-nach-mitternacht-kriminalreihe-100.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "Mord nach Mitternacht-mord-nach-mitternacht-kriminalreihe-100.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Mord nach Mitternacht-mord-nach-mitternacht-kriminalreihe-100.mp4' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:Mord nach Mitternacht-mord-nach-mitternacht-kriminalreihe-100.temp.mp4'
[download] Downloading video 3 of 10
[ZDF] sport-ist-mord-116: Downloading webpage
[ZDF] sport-ist-mord-116: Downloading JSON content
[ZDF] sport-ist-mord-116: Downloading JSON metadata
[ZDF] sport-ist-mord-116: Downloading m3u8 information
[ZDF] sport-ist-mord-116: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[ZDF] sport-ist-mord-116: Downloading f4m manifest
[ZDF] sport-ist-mord-116: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://zdfvodnone-vh.akamaihd.net/i/meta-files/zdf/smil/m3u8/300/19/07/190706_2145_sendung_sta/2/190706_2145_sendung_sta.smil/index_3296000_av.m3u8'
[download] Sport ist Mord-sport-ist-mord-116.mp4 has already been downloaded
[download] 100% of 1.11GiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:Sport ist Mord-sport-ist-mord-116.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "Sport ist Mord-sport-ist-mord-116.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Sport ist Mord-sport-ist-mord-116.mp4' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:Sport ist Mord-sport-ist-mord-116.temp.mp4'
[download] Downloading video 4 of 10
[ZDF] toedlicher-ehrgeiz-100: Downloading webpage
[ZDF] toedlicher-ehrgeiz-100: Downloading JSON content
[ZDF] toedlicher-ehrgeiz-100: Downloading JSON metadata
[ZDF] toedlicher-ehrgeiz-100: Downloading m3u8 information
[ZDF] toedlicher-ehrgeiz-100: Downloading m3u8 information
[ZDF] toedlicher-ehrgeiz-100: Downloading f4m manifest
[ZDF] toedlicher-ehrgeiz-100: Downloading f4m manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://zdfvodnone-vh.akamaihd.net/i/meta-files/zdf/smil/m3u8/300/19/06/190622_2145_sendung_sta/2/190622_2145_sendung_sta.smil/index_3296000_av.m3u8'
[download] Tödlicher Ehrgeiz-toedlicher-ehrgeiz-100.mp4 has already been downloaded
[download] 100% of 1.10GiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:Tödlicher Ehrgeiz-toedlicher-ehrgeiz-100.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "Tödlicher Ehrgeiz-toedlicher-ehrgeiz-100.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Tödlicher Ehrgeiz-toedlicher-ehrgeiz-100.mp4' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:Tödlicher Ehrgeiz-toedlicher-ehrgeiz-100.temp.mp4'
[download] Downloading video 5 of 10
[ZDF] vom-tod-gezeichnet-100: Downloading webpage
[ZDF] vom-tod-gezeichnet-100: Downloading JSON content
[ZDF] vom-tod-gezeichnet-100: Downloading JSON metadata
[ZDF] vom-tod-gezeichnet-100: Downloading m3u8 information
[ZDF] vom-tod-gezeichnet-100: Downloading m3u8 information
[ZDF] vom-tod-gezeichnet-100: Downloading f4m manifest
[ZDF] vom-tod-gezeichnet-100: Downloading f4m manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://zdfvodnone-vh.akamaihd.net/i/meta-files/zdf/smil/m3u8/300/19/06/190615_2145_sendung_sta/2/190615_2145_sendung_sta.smil/index_3296000_av.m3u8'
[download] Vom Tod gezeichnet-vom-tod-gezeichnet-100.mp4 has already been downloaded
[download] 100% of 1.06GiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:Vom Tod gezeichnet-vom-tod-gezeichnet-100.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "Vom Tod gezeichnet-vom-tod-gezeichnet-100.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Vom Tod gezeichnet-vom-tod-gezeichnet-100.mp4' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:Vom Tod gezeichnet-vom-tod-gezeichnet-100.temp.mp4'
[download] Downloading video 6 of 10
[ZDF] im-falschen-leben-100: Downloading webpage
[ZDF] im-falschen-leben-100: Downloading JSON content
[ZDF] im-falschen-leben-100: Downloading JSON metadata
[ZDF] im-falschen-leben-100: Downloading m3u8 information
[ZDF] im-falschen-leben-100: Downloading m3u8 information
[ZDF] im-falschen-leben-100: Downloading f4m manifest
[ZDF] im-falschen-leben-100: Downloading f4m manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://zdfvodnone-vh.akamaihd.net/i/meta-files/zdf/smil/m3u8/300/19/06/190601_2145_sendung_sta/2/190601_2145_sendung_sta.smil/index_3296000_av.m3u8'
[download] Im falschen Leben-im-falschen-leben-100.mp4 has already been downloaded
[download] 100% of 1.09GiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:Im falschen Leben-im-falschen-leben-100.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "Im falschen Leben-im-falschen-leben-100.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Im falschen Leben-im-falschen-leben-100.mp4' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:Im falschen Leben-im-falschen-leben-100.temp.mp4'
[download] Downloading video 7 of 10
[ZDF] der-staatsanwalt-darsteller-rainer-hunold-100: Downloading webpage
[ZDF] der-staatsanwalt-darsteller-rainer-hunold-100: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError(u'formitaeten',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/zdf.py", line 235, in _real_extract
    return self._extract_mobile(video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/zdf.py", line 196, in _extract_mobile
    for f in document['formitaeten']:
KeyError: u'formitaeten'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 543, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'formitaeten',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
'''

**Comment by Hrxn** [comment]
@agaylard It's actually working, I'd say. (Almost)

The URL you've used is basically just an overview page (`https://www.zdf.de/serien/der-staatsanwalt`).

And it then fails at:
`https://www.zdf.de/serien/der-staatsanwalt/der-staatsanwalt-darsteller-rainer-hunold-100.html`

Which is just a page with background info (a character description). There's no video content.

I compared that overview page with a web app for searching those public catalogues
https://mediathekviewweb.de/#query=der%20staatsanwalt

And it's basically the same result. Look at "Thema" (topic), there are 8 episodes. (The ninth is just a trailer).

I blame these bad overview pages...
