### ISSUE TITLE
uol.com.br still not working!

### ISSUE THREAD

**Issue by ixxbxxx** [ytdl-org/youtube-dl#22007]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.9.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\User\Desktop>youtube-dl --verbose https://mais.uol.com.br/view/16704134
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://mais.uol.com.br/view/16704134']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.7.0b1 (CPython) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg N-94600-g661a9b274b
[debug] Proxy map: {}
[uol.com.br] 16704134: Downloading JSON metadata
ERROR: 16704134: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\extractor\common.py", line 899, in _parse_json
    return json.loads(json_string)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\json\__init__.py", line 355, in loads
    return _default_decoder.decode(s)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\json\decoder.py", line 340, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\json\decoder.py", line 358, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\extractor\common.py", line 899, in _parse_json
    return json.loads(json_string)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\json\__init__.py", line 355, in loads
    return _default_decoder.decode(s)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\json\decoder.py", line 340, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\json\decoder.py", line 358, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\extractor\uol.py", line 111, in _real_extract
    media_id)['item']
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\extractor\common.py", line 892, in _download_json
    expected_status=expected_status)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\extractor\common.py", line 876, in _download_json_handle
    fatal=fatal), urlh
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\extractor\common.py", line 903, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: 16704134: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

uol.com.br videos is not working despite trying different URLs / shortened links.

**Comment by ixxbxxx** [comment]
Pinging @remitamine and @dstftw who created the original extractor.

**Comment by ixxbxxx** [comment]
Tried with latest version and it's still spitting out the same error message which leads me to believe the issue lies with the extractor code. Hope @remitamine can have a go at it. Thank you.

**Comment by ixxbxxx** [comment]
Again tried with latest version under python/win32 and this site remains broken. Hope @remitamine can have a look at it. Thank you.
