### ISSUE TITLE
unable to download or even get info. about ndtv videos.v

### ISSUE THREAD

**Issue by shirishag75** [ytdl-org/youtube-dl#22019]
## Checklist

- [*] I'm reporting a broken site support
- [*] I've verified that I'm running youtube-dl version **2019.08.02**
- [*] I've checked that all provided URLs are alive and playable in a browser
- [* ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [*] I've searched the bugtracker for similar issues including closed ones

```
$ youtube-dl -v -F "https://www.ndtv.com/video/news/news/what-happened-in-kashmir-can-happen-in-your-state-too-ramachandra-guha-523554?t=0"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.ndtv.com/video/news/news/what-happened-in-kashmir-can-happen-in-your-state-too-ramachandra-guha-523554?t=0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[deybug] youtube-dl version 2019ys yssv.08.02
[dug] Python version 2.7.16+ (CPython) - Linux-4.19.0-5-amd64-x86_64-with-debian-bullseye-sid
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[NDTV] 523554: Downloading webpage
ERROR: Unable to extract video filename; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ndtv.py", line 91, in _real_extract
    r"(?:__)?filename\s*[:=]\s*'([^']+)'", webpage, 'video filename')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video filename; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Just to share, I tried various ways to see if this worked- but each time got the same error as above.  Maybe somebody could take a look and see if this can be fixed.

**Comment by shirishag75** [comment]
@dstftw shouldn't have u shared the link of the original bug-report so that it could be followed as well.
