### ISSUE TITLE
youku download error

### ISSUE THREAD

**Issue by dgbgg** [ytdl-org/youtube-dl#22018]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2019.08.02**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

d:\book>pip install -U youtube-dl
Collecting youtube-dl
  Downloading https://files.pythonhosted.org/packages/81/22/003c233640929d4ced90a0ff5565e36b013844e7bfeea1eec3eba91d93e2/youtube_dl-2019.8.2-py2.py3-none-any.whl (1.8MB)
     |████████████████████████████████| 1.8MB 74kB/s
Installing collected packages: youtube-dl
  Found existing installation: youtube-dl 2019.7.16
    Uninstalling youtube-dl-2019.7.16:
      Successfully uninstalled youtube-dl-2019.7.16
Successfully installed youtube-dl-2019.8.2

d:\book>youtube-dl https://v.youku.com/v_show/id_XNDI2OTMyNTUzNg==.html
[youku] XNDI2OTMyNTUzNg: Retrieving cna info
[youku] XNDI2OTMyNTUzNg: Downloading JSON metadata
ERROR: Youku server reported error -6005: 用户账户异常、请重新登录; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

d:\book>youtube-dl https://v.youku.com/v_show/id_XNDI2OTMyNTUzNg==.html --cookies D:\文档\youku_cookie.txt
[youku] XNDI2OTMyNTUzNg: Retrieving cna info
[youku] XNDI2OTMyNTUzNg: Downloading JSON metadata
ERROR: Youku server reported error -6005: 用户账户异常、请重新登录; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by zhuchuanwu** [comment]
解决了吗

**Comment by neil-rutherford** [comment]
I'm getting this on v2020.01.01 too. If y'all don't speak Chinese, the 6005 error message translates to: "Abnormal user account. Please sign in again." Here's my log:

```
youtube-dl --verbose  https://v.youku.com/v_show/id_XNDQ4Njc5MTcwNA==.html?s=efbfbdefbfbd5c43125e&scm=20140719.rcmd.7182.show_efbfbdefbfbd5c43125e
[1] 4169
(venv) neil@kali:~/Desktop/untitled/app$ [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://v.youku.com/v_show/id_XNDQ4Njc5MTcwNA==.html?s=efbfbdefbfbd5c43125e']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.01
[debug] Python version 3.7.4+ (CPython) - Linux-4.19.0-kali5-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
[debug] exe versions: none
[debug] Proxy map: {}
[youku] XNDQ4Njc5MTcwNA: Retrieving cna info
[youku] XNDQ4Njc5MTcwNA: Downloading JSON metadata
ERROR: Youku server reported error -6005: 用户账户异常、请重新登录; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/neil/Desktop/untitled/venv/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/neil/Desktop/untitled/venv/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/neil/Desktop/untitled/venv/lib/python3.7/site-packages/youtube_dl/extractor/youku.py", line 189, in _real_extract
    raise ExtractorError(msg)
youtube_dl.utils.ExtractorError: Youku server reported error -6005: 用户账户异常、请重新登录; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

youtube-dl --version
2020.01.01
[1]+  Exit 1                  youtube-dl --verbose https://v.youku.com/v_show/id_XNDQ4Njc5MTcwNA==.html?s=efbfbdefbfbd5c43125e
```

**Comment by ziyi-yan** [comment]
The problem still exists in version `2020.05.29`. I tried [you-get](https://github.com/soimort/you-get) instead and it works.
