### ISSUE TITLE
LinkedIn Learning - course extractor error

### ISSUE THREAD

**Issue by adamnock** [ytdl-org/youtube-dl#22028]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.08.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
I:\Work\LIL\Learn Apache Kakfa For Beginnners>youtube-dl.exe https://www.linkedin.com/learning/learn-apache-kafka-for-beginners/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.linkedin.com/learning/learn-apache-kafka-for-beginners/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.08.02
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-93403-g0739d5cd5c, ffprobe N-93403-g0739d5cd5c
[debug] Proxy map: {'no': '192.168.99.100'}
ERROR: An extractor error has occurred. (caused by KeyError('JSESSIONID',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\linkedin.py", line 158, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\linkedin.py", line 36, in _call_api
KeyError: 'JSESSIONID'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\linkedin.py", line 158, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\linkedin.py", line 36, in _call_api
KeyError: 'JSESSIONID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\common.py", line 543, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('JSESSIONID',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


I:\Work\LIL\Learn Apache Kakfa For Beginnners>youtube-dl.exe -U
youtube-dl is up-to-date (2019.08.02)
```

## Description

Attempting to download a LinkedIn Learning course for offline use. I do have access and can play the course fine in browser.
Version up to date and confirmed using updater.

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl

**Comment by adamnock** [comment]
OK, so ill ignore the error provided to log and add a cookie file, even though it would make sense for the error to mention its expected

No dice, even following another thread about cookie parsing issues, it still fails to download past the freely available videos. Ill keep debugging and open a new Issue once im done.
