### ISSUE TITLE
Merging to Matryoshka with ffmpeg fails (it works on almost all other videos though).

### ISSUE THREAD

**Issue by PuppyPi** [ytdl-org/youtube-dl#22048]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.08.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
root@firstmoon:/data# ./youtube-dl -v https://www.youtube.com/watch?v=ep2PAMrzwEU
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=ep2PAMrzwEU']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.02
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-9-amd64-x86_64-with-debian-9.9
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1
[debug] Proxy map: {}
[youtube] ep2PAMrzwEU: Downloading webpage
[youtube] ep2PAMrzwEU: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r3---sn-n0qqxoapo3-jaal.googlevideo.com/videoplayback?expire=1565348995&ei=IwBNXZT1E4HQjASx9JfYDA&ip=47.221.236.136&id=o-APJLtxTvbizpJ9nVSFM54tH1MZThwrmqDPj78lkSaUGd&itag=398&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C394%2C395%2C396%2C397%2C398&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-n0qqxoapo3-jaal%2Csn-q4flrnle&ms=au%2Crdu&mv=m&mvi=2&pl=22&initcwndbps=1732500&mime=video%2Fmp4&gir=yes&clen=47515714&dur=693.108&lmt=1545945801759058&mt=1565327262&fvip=3&keepalive=yes&c=WEB&txp=5532432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRAIgOtb_PGgvt9-ulKBnimzXT-GSISg68ZFgbsYWPVcsnCQCIDPsWdVmsSB-y1oHdI4VEEBRp8L-J0cFAwklMZ20iZ6U&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgFL4j7degTUCOAKrzcMn_iPZK9YDX5NfZS7jxcQz5YkcCIQCUdrAmcoRQ1P-EPy6SGYiUbF8BjuO4ihf6GlmL1HiGWA%3D%3D&ratebypass=yes'
[download] Destination: SuperMagnetMan - Fundamentals of Halbach Arrays-ep2PAMrzwEU.f398.mp4
[download] 100% of 45.31MiB in 00:18
[debug] Invoking downloader on u'https://r3---sn-n0qqxoapo3-jaal.googlevideo.com/videoplayback?expire=1565348995&ei=IwBNXZT1E4HQjASx9JfYDA&ip=47.221.236.136&id=o-APJLtxTvbizpJ9nVSFM54tH1MZThwrmqDPj78lkSaUGd&itag=140&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-n0qqxoapo3-jaal%2Csn-q4flrnle&ms=au%2Crdu&mv=m&mvi=2&pl=22&initcwndbps=1732500&mime=audio%2Fmp4&gir=yes&clen=11219128&dur=693.162&lmt=1545527877317141&mt=1565327262&fvip=3&keepalive=yes&c=WEB&txp=5533432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIhAKB8O8S1tx22xdAZrAfvE1W91liwZkS4QqJf0ju6o-d4AiASp6Bae1IwmlIS8civLIH52vs7XeBNaT9zTE0pB_9CTg%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgFL4j7degTUCOAKrzcMn_iPZK9YDX5NfZS7jxcQz5YkcCIQCUdrAmcoRQ1P-EPy6SGYiUbF8BjuO4ihf6GlmL1HiGWA%3D%3D&ratebypass=yes'
[download] Destination: SuperMagnetMan - Fundamentals of Halbach Arrays-ep2PAMrzwEU.f140.m4a
[download] 100% of 10.70MiB in 00:03
[ffmpeg] Merging formats into "SuperMagnetMan - Fundamentals of Halbach Arrays-ep2PAMrzwEU.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:SuperMagnetMan - Fundamentals of Halbach Arrays-ep2PAMrzwEU.f398.mp4' -i 'file:SuperMagnetMan - Fundamentals of Halbach Arrays-ep2PAMrzwEU.f140.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:SuperMagnetMan - Fundamentals of Halbach Arrays-ep2PAMrzwEU.temp.mp4'
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2054, in post_process
    files_to_delete, info = pp.run(info)
  File "./youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "./youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)

root@firstmoon:/data# 
```

## Description

Merging to Matryoshka with ffmpeg failed (it works on almost all other videos though).

**Comment by dstftw** [comment]
1. It's not merging into mkv in your log.
2. It fails because of outdated ffmpeg.

**Comment by PuppyPi** [comment]
1. Oh wow, perhaps that was a different url or I'm way too sleep deprived; very sorry.

2. This is the latest version of ffmpeg in the Debian 9 repo.  It'd be nice if youtube-dl gave a warning for version mismatch with external tools it depended on (and for that to be added to the checklist for bug reports so we don't end up bothering you all unnecessarily)

Thanks for your help, and keep up the incredibly wonderful work with this tool!
