### ISSUE TITLE
Broken site: bbc.co.uk/iplayer

### ISSUE THREAD

**Issue by Chaz6** [ytdl-org/youtube-dl#22067]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2019.08.02**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl --verbose https://www.bbc.co.uk/iplayer/episode/m00073t6/prime-ministers-questions-24072019
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.bbc.co.uk/iplayer/episode/m00073t6/prime-ministers-questions-24072019']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.02
[debug] Python version 3.6.8 (CPython) - Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with-centos-7.6.1810-Core
[debug] exe versions: ffmpeg 4.2-static, ffprobe 4.2-static
[debug] Proxy map: {}
[bbc.co.uk] m00073t6: Downloading video page
[bbc.co.uk] m00073t6: Downloading playlist JSON
[bbc.co.uk] m00073tc: Downloading media selection XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/chaz/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/chaz/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/chaz/.local/lib/python3.6/site-packages/youtube_dl/extractor/bbc.py", line 577, in _real_extract
    self._sort_formats(formats)
  File "/home/chaz/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I am not able to download the video at https://www.bbc.co.uk/iplayer/episode/m00073t6/prime-ministers-questions-24072019. It plays as expected in Firefox.

**Comment by dstftw** [comment]
For any work on this you must provide working GB proxy/vpn.
