### ISSUE TITLE
[Corus] must adjust extractor due to redesign

### ISSUE THREAD

**Issue by ProgrammerAKL** [ytdl-org/youtube-dl#22075]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.08.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -o "C:/Video/Aug_07_2019.%(ext)s" "https://etcanada.com/video/GLOB0055740140000100/aug-07-2019/" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'C:/Video/Aug_07_2019.%(ext)s', 'https://etcanada.com/video/GLOB0055740140000100/aug-07-2019/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.08.02
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-83507-g8fa18e0, ffprobe N-83507-g8fa18e0, rtmpdump 2.4
[debug] Proxy map: {}
[generic] aug-07-2019: Requesting header
WARNING: Falling back on generic information extractor.
[generic] aug-07-2019: Downloading webpage
[generic] aug-07-2019: Extracting information
ERROR: Unsupported URL: https://etcanada.com/video/GLOB0055740140000100/aug-07-2019/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\generic.py", line 3333, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://etcanada.com/video/GLOB0055740140000100/aug-07-2019/

```

## Description

youtube-dl is failing to recognize the new format of the URL. By comparison, it had no trouble with the format of the URL for the previous episode, as you can see below
```
youtube-dl -o "C:/Video/Aug_06_2019.%(ext)s" "https://etcanada.com/video/1583125059770/aug-06-2019/" --verbose --list-formats
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'C:/Video/Aug_06_2019.%(ext)s', 'https://etcanada.com/video/1583125059770/aug-06-2019/', '--verbose', '--list-formats']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.08.02
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-83507-g8fa18e0, ffprobe N-83507-g8fa18e0, rtmpdump 2.4
[debug] Proxy map: {}
[Corus] 1583125059770: Downloading JSON metadata
[Corus] 1583125059770: Downloading SMIL data for MP4 MBR
[Corus] 1583125059770: Downloading m3u8 information
[Corus] 1583125059770: Downloading SMIL data for Rendition
[Corus] 1583125059770: Downloading m3u8 information
[Corus] 1583125059770: Downloading JSON metadata
[info] Available formats for 1583125059770:
format code                   extension  resolution note
hls-audio-aacl-128-English-0  mp4        audio only [en] 
hls-audio-aacl-128-English-1  mp4        audio only [en] 
hls-audio-aacl-96-English-0   mp4        audio only [en] 
hls-audio-aacl-96-English-1   mp4        audio only [en] 
hls-973-0                     mp4        640x360     973k , avc1.42C01E, 29.97fps, video only
hls-973-1                     mp4        640x360     973k , avc1.42C01E, 29.97fps, video only
hls-1316-0                    mp4        640x360    1316k , avc1.42C01E, 29.97fps, video only
hls-1316-1                    mp4        640x360    1316k , avc1.42C01E, 29.97fps, video only
hls-1849-0                    mp4        960x540    1849k , avc1.4D401F, 29.97fps, video only
hls-1849-1                    mp4        960x540    1849k , avc1.4D401F, 29.97fps, video only
hls-2799-0                    mp4        1280x720   2799k , avc1.4D401F, 29.97fps, video only
hls-2799-1                    mp4        1280x720   2799k , avc1.4D401F, 29.97fps, video only
hls-5449-0                    mp4        1280x720   5449k , avc1.4D401F, 29.97fps, video only
hls-5449-1                    mp4        1280x720   5449k , avc1.4D401F, 29.97fps, video only (best)
```

**Comment by wolfy1339** [comment]
This also affects globaltv.com
