### ISSUE TITLE
Unable to extract stream URL (openload)

### ISSUE THREAD

**Issue by vassilisw** [ytdl-org/youtube-dl#22077]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.08.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl --verbose "http://openload.co/f/2s172zXFKLI"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://openload.co/f/2s172zXFKLI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.02
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-55-generic-x86_64-with-LinuxMint-19-tara
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 5
[debug] Proxy map: {}
[Openload] 2s172zXFKLI: Downloading embed webpage
[Openload] 2s172zXFKLI: Executing JS on webpage
ERROR: Unable to extract stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/openload.py", line 432, in _real_extract
    'stream URL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Unable to extract stream URL

**Comment by vassilisw** [comment]
cant-reproduce? Meaning **you can download the video?** I don't think so! 
This bug exists many months. I hope someone will finally fix it despite the "cant-reproduce" responses.

**Comment by dstftw** [comment]
```
> py -3.7 .\youtube_dl\__main__.py http://openload.co/f/2s172zXFKLI
[Openload] 2s172zXFKLI: Downloading embed webpage
[Openload] 2s172zXFKLI: Executing JS on webpage
[download] Destination: 1967 GAMPROS AP' TO LONDINO DVDRIP.mp4.mp4
[download]   0.1% of 459.02MiB at 247.12KiB/s ETA 31:41
ERROR: Interrupted by user
```
There is no bug. Either you are banned by openload or your phantomjs setup is broken.

**Comment by vassilisw** [comment]
Thanks for the useful recommendations!
