### ISSUE TITLE
[byutv] [ooyala]

### ISSUE THREAD

**Issue by ProgrammerAKL** [ytdl-org/youtube-dl#22070]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.08.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -o "C:/Video/%(title)s.%(ext)s" "https://www.byutv.org/player/fd0ab13f-c37b-44f9-9c43-9489324c0d27/extinct-e106-true-or-false" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'C:/Video/%(title)s.%(ext)s', 'https://www.byutv.org/player/fd0ab13f-c37b-44f9-9c43-9489324c0d27/extinct-e106-true-or-false', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.08.02
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}
[BYUtv] extinct-e106-true-or-false: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('dvr',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\byutv.py", line 78, in _real_extract
KeyError: 'dvr'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\byutv.py", line 78, in _real_extract
KeyError: 'dvr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\common.py", line 543, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('dvr',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

byutv download is not working at all in the latest version of youtube-dl, even though the problem was supposedly addressed in https://github.com/ytdl-org/youtube-dl/commit/ab116745020f2edd30de34e8ad7800209cdc4c72

**Comment by curtisgibby** [comment]
I'm experiencing the same problem, which is distinct from #20574. BYU TV has changed their providers, and now provides keys in the format `dash1` and `hls1` instead of `ooyalaVOD` or `dvr`.

Why was this issue closed, and what does the "DRM" label signify? Can youtube-dl not handle either of these updated formats?
