### ISSUE TITLE
ERROR: This video is unavailable.

### ISSUE THREAD

**Issue by dannymeijer** [ytdl-org/youtube-dl#22086]
### Output of command with -v flag
```
 youtube-dl -x -v --prefer-ffmpeg --audio-format m4a --audio-quality 0 https://www.youtube.com/watch\?v\=wmin5WkOuPw\&list\=RDAOP_M3S90ksn-ASgqyXkeYGg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-x', u'-v', u'--prefer-ffmpeg', u'--audio-format', u'm4a', u'--audio-quality', u'0', u'https://www.youtube.com/watch?v=wmin5WkOuPw&list=RDAOP_M3S90ksn-ASgqyXkeYGg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.02
[debug] Python version 2.7.10 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg N-94484-gaf3ddd581f-tessus, ffprobe N-94484-gaf3ddd581f-tessus
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist RDAOP_M3S90ksn-ASgqyXkeYGg - add --no-playlist to just download video wmin5WkOuPw
[youtube:playlist] RDAOP_M3S90ksn-ASgqyXkeYGg: Downloading page 1 of Youtube mix
[youtube:playlist] RDAOP_M3S90ksn-ASgqyXkeYGg: Downloading page 2 of Youtube mix
[youtube:playlist] RDAOP_M3S90ksn-ASgqyXkeYGg: Downloading page 3 of Youtube mix
[youtube:playlist] RDAOP_M3S90ksn-ASgqyXkeYGg: Downloading page 4 of Youtube mix
[youtube:playlist] RDAOP_M3S90ksn-ASgqyXkeYGg: Downloading page 5 of Youtube mix
[youtube:playlist] RDAOP_M3S90ksn-ASgqyXkeYGg: Downloading page 6 of Youtube mix
[download] Downloading playlist: Mix - The Prodigy
[youtube:playlist] playlist Mix - The Prodigy: Collected 121 video ids (downloading 121 of them)
[download] Downloading video 1 of 121
[youtube] ASgqyXkeYGg: Downloading webpage
[youtube] ASgqyXkeYGg: Downloading video info webpage
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2105, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is unavailable.
```

### Issue Description:
trying to download a playlist from Youtube and getting error that video is unavailable.
I was able to download the video from the playlist itself (on its own), but it does not appear to traverse the playlist or at least it is encountering some kind of problem. I have been able to download other playlist (on the same day, computer and from the same connection), so I can pretty much rule out that that is the issue.

### Are you using the latest version?
Yes

### Is the issue already documented?
Does not seem to be. I see similar issues, but not about this specific playlist.

### Why are existing options not enough?
N/A

### Is there enough context in your bug report?
A good thing to note is that this playlist was originally from music.youtube.com, which I then stored and accessed through regular youtube (as music is just a UI wrapper really). Another playlist I had on music.youtube downloaded just fine - this one did not.

### Does the issue involve one problem, and one problem only?
Yes

### Is anyone going to need the feature?
Yes, I think so - since this is obviously some kind of bug that is being hit.

### Is your question about youtube-dl?
Yes

**Comment by dstftw** [comment]
This is expected behavior. You must explicitly use `-i`.
