### ISSUE TITLE
stream.cz - Unsupported URL

### ISSUE THREAD

**Issue by pasimonek** [ytdl-org/youtube-dl#22114]
Supported web page stopped to work - ends with Unsupported URL:

youtube-dl -F --verbose https://www.televizeseznam.cz/video/lajna/trener-hrouzek-se-vraci-druha-serie-serialu-lajna-63933601
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'--verbose', u'https://www.televizeseznam.cz/video/lajna/trener-hrouzek-se-vraci-druha-serie-serialu-lajna-63933601']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.7.10 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] trener-hrouzek-se-vraci-druha-serie-serialu-lajna-63933601: Requesting header
WARNING: Falling back on generic information extractor.
[generic] trener-hrouzek-se-vraci-druha-serie-serialu-lajna-63933601: Downloading webpage
[generic] trener-hrouzek-se-vraci-druha-serie-serialu-lajna-63933601: Extracting information
ERROR: Unsupported URL: https://www.televizeseznam.cz/video/lajna/trener-hrouzek-se-vraci-druha-serie-serialu-lajna-63933601
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2357, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1, column 1957
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3333, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.televizeseznam.cz/video/lajna/trener-hrouzek-se-vraci-druha-serie-serialu-lajna-63933601

**Comment by schunka** [comment]
Will someone process the `add extractor` pull request and fix this issue?
