### ISSUE TITLE
ERROR: Sorry about that.

### ISSUE THREAD

**Issue by titirino159** [ytdl-org/youtube-dl#22117]
## Checklist

- [ *] I'm reporting a broken site support issue
- [ *] I've verified that I'm running youtube-dl version **2019.08.13**
- [ *] I've checked that all provided URLs are alive and playable in a browser
- [* ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [* ] I've searched the bugtracker for similar bug reports including closed ones
- [* ] I've read bugs section in FAQ

## Verbose log

```
XX~/test# youtube-dl https://www.youtube.com/watch?v=s3O1Xro7oAI --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=s3O1Xro7oAI', u'--verbose']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-9-amd64-x86_64-with-debian-9.9
[debug] exe versions: ffmpeg 4.1.2, ffprobe 4.1.2, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube] s3O1Xro7oAI: Downloading webpage
[youtube] s3O1Xro7oAI: Downloading video info webpage
ERROR: Sorry about that.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 2108, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: Sorry about that.

```

## Description

Hello, when I try to download a video with youtube-dl, I have this error since today.

**Comment by Hrxn** [comment]
> `WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.`

> `[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968`

This looks.. wrong. Something or someone changed some system settings?

**Comment by quakig** [comment]
I am getting the same error.

You seem to suggest that that this is a `geo-restricted`  issue.
If that is the case, the --geo-bypass flag should work. But it doesnt. 

```
youtube-dl --geo-bypass --verbose http://www.youtube.com/watch?v=bo_efYhYU2A
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--geo-bypass', '--verbose', 'http://www.youtube.com/watch?v=bo_efYhYU2A']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 3.7.3 (CPython) - Linux-5.0.0-15-generic-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube] bo_efYhYU2A: Downloading webpage
[youtube] bo_efYhYU2A: Downloading video info webpage
ERROR: Sorry about that.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2108, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: Sorry about that.
```

**Comment by AndrewMcSwain** [comment]
I'm getting the same unhelpful error on some YouTube videos.

**Comment by Lpsd** [comment]
I was getting the same, however I fixed it by using the `--force-ipv4` option.

**Comment by bijij** [comment]
I don't think this is Geo-Restriction, ytdl just doesn't seem to work on any videos uploaded to a "Official Artist" YouTube channel.

**Comment by bijij** [comment]
This didn't work for me.
The videos which won't download are all uploaded by "Official Artists" YouTube channels, perhaps those videos are now treated differently?

**Comment by genthruB** [comment]
the hell is happening with ydl???
