### ISSUE TITLE
[mixcloud] Unable to extract play info

### ISSUE THREAD

**Issue by michielappelman** [ytdl-org/youtube-dl#22115]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
i ➜ youtube-dl --version
2019.08.13

~ took 2s
i ➜ youtube-dl -U
youtube-dl is up-to-date (2019.08.13)

~ took 2s
i ➜ youtube-dl -v 'http://www.mixcloud.com/gillespeterson/caribou-7-inch-vinyl-mix-chat/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.mixcloud.com/gillespeterson/caribou-7-inch-vinyl-mix-chat/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 3.6.5 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4, rtmpdump 2.4
[debug] Proxy map: {}
[mixcloud] gillespeterson-caribou-7-inch-vinyl-mix-chat: Downloading webpage
ERROR: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mixcloud.py", line 87, in _real_extract
    webpage, 'play info'), 'play info')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Unable to download due to failure to extract `play info`. Also seen in Travis job [Job #18805.18](https://travis-ci.org/ytdl-org/youtube-dl/jobs/572631452):

```
======================================================================
ERROR: test_Mixcloud (test.test_download.TestDownload):
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ytdl-org/youtube-dl/test/test_download.py", line 159, in test_template
    force_generic_extractor=params.get('force_generic_extractor', False))
  File "/home/travis/build/ytdl-org/youtube-dl/youtube_dl/YoutubeDL.py", line 819, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/home/travis/build/ytdl-org/youtube-dl/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/home/travis/build/ytdl-org/youtube-dl/youtube_dl/YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: [0;31mERROR:[0m Unable to extract [0;34mplay info[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
-------------------- >> begin captured stdout << ---------------------
[mixcloud] dholbach-cryptkeeper: Downloading webpage
[0;31mERROR:[0m Unable to extract [0;34mplay info[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/travis/build/ytdl-org/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/travis/build/ytdl-org/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/travis/build/ytdl-org/youtube-dl/youtube_dl/extractor/mixcloud.py", line 87, in _real_extract
    webpage, 'play info'), 'play info')
  File "/home/travis/build/ytdl-org/youtube-dl/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/travis/build/ytdl-org/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract [0;34mplay info[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


--------------------- >> end captured stdout << ----------------------
```

**Comment by greentornado** [comment]
it still works for me

```
└🤘-> youtube-dl -v 'http://www.mixcloud.com/gillespeterson/caribou-7-inch-vinyl-mix-chat/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.mixcloud.com/gillespeterson/caribou-7-inch-vinyl-mix-chat/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.30
[debug] Python version 3.6.5 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[mixcloud] gillespeterson-caribou-7-inch-vinyl-mix-chat: Downloading webpage
[mixcloud] gillespeterson-caribou-7-inch-vinyl-mix-chat: Downloading JS
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://rss.acast.com/gillespetersonww/caribou-7-inch-vinyl-mix-chat/media.mp3'
[download] Destination: Caribou 7 inch Vinyl Mix & Chat-gillespeterson-caribou-7-inch-vinyl-mix-chat.mp3
[download]  10.6% of 45.73MiB at  2.05MiB/s ETA 00:19^C
```

**Comment by michielappelman** [comment]
Fascinating, seems to work now for me as well. Although I am now behind a VPN... Getting served different versions of the page perhaps?

**Comment by michielappelman** [comment]
This seems not reproducible anymore. Potentially caused by different versions of the Mixcloud page being served to different IP subnets.
