### ISSUE TITLE
ExtractorError: No video formats found on soundcloud

### ISSUE THREAD

**Issue by smmsadrnezh** [ytdl-org/youtube-dl#22123]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-t', u'https://soundcloud.com/mana-s/kamar-barik-by-turku']
WARNING: --title is deprecated. Use -o "%(title)s-%(id)s.%(ext)s" instead.
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-58-generic-x86_64-with-elementary-0.4.1-loki
[debug] exe versions: ffmpeg 3.2-1001, ffprobe 3.2-1001, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] mana-s/kamar-barik-by-turku: Downloading webpage
[soundcloud] mana-s/kamar-barik-by-turku: Downloading info JSON
[soundcloud] 41552272: Downloading track url
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
[soundcloud] 41552272: Checking fallback video format URL
[soundcloud] 41552272: fallback video format URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dll/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dll/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dll/youtube_dl/extractor/soundcloud.py", line 449, in _real_extract
    merge_dicts(info, new_info), full_title, secret_token=token)
  File "/usr/local/bin/youtube-dll/youtube_dl/extractor/soundcloud.py", line 388, in _extract_info_dict
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dll/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://soundcloud.com/deccarecords/experience', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-58-generic-x86_64-with-elementary-0.4.1-loki
[debug] exe versions: ffmpeg 3.2-1001, ffprobe 3.2-1001, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] deccarecords/experience: Downloading webpage
[soundcloud] deccarecords/experience: Downloading info JSON
[soundcloud] 71706008: Downloading track url
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
[soundcloud] 71706008: Checking fallback video format URL
[soundcloud] 71706008: fallback video format URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dll/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dll/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dll/youtube_dl/extractor/soundcloud.py", line 449, in _real_extract
    merge_dicts(info, new_info), full_title, secret_token=token)
  File "/usr/local/bin/youtube-dll/youtube_dl/extractor/soundcloud.py", line 388, in _extract_info_dict
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dll/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://soundcloud.com/angusandjuliastone/the-beast']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-58-generic-x86_64-with-elementary-0.4.1-loki
[debug] exe versions: ffmpeg 3.2-1001, ffprobe 3.2-1001, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] angusandjuliastone/the-beast: Downloading webpage
[soundcloud] angusandjuliastone/the-beast: Downloading info JSON
[soundcloud] 19253313: Downloading track url
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
[soundcloud] 19253313: Checking fallback video format URL
[soundcloud] 19253313: fallback video format URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dll/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dll/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dll/youtube_dl/extractor/soundcloud.py", line 449, in _real_extract
    merge_dicts(info, new_info), full_title, secret_token=token)
  File "/usr/local/bin/youtube-dll/youtube_dl/extractor/soundcloud.py", line 388, in _extract_info_dict
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dll/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://soundcloud.com/official-david-foster/05-quiz-s-quiz-s-quiz-s']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-58-generic-x86_64-with-elementary-0.4.1-loki
[debug] exe versions: ffmpeg 3.2-1001, ffprobe 3.2-1001, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] official-david-foster/05-quiz-s-quiz-s-quiz-s: Downloading webpage
[soundcloud] official-david-foster/05-quiz-s-quiz-s-quiz-s: Downloading info JSON
[soundcloud] 77474236: Downloading track url
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
[soundcloud] 77474236: Checking fallback video format URL
[soundcloud] 77474236: fallback video format URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dll/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dll/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dll/youtube_dl/extractor/soundcloud.py", line 449, in _real_extract
    merge_dicts(info, new_info), full_title, secret_token=token)
  File "/usr/local/bin/youtube-dll/youtube_dl/extractor/soundcloud.py", line 388, in _extract_info_dict
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dll/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I got this error when I want to download these four sound files:

https://soundcloud.com/mana-s/kamar-barik-by-turku
https://soundcloud.com/deccarecords/experience
https://soundcloud.com/angusandjuliastone/the-beast
https://soundcloud.com/official-david-foster/05-quiz-s-quiz-s-quiz-s

**Comment by vtyutin** [comment]
Is there any progress with analysis this issue. I faced same issue with SoundCloud. I need it solved ASAP. Thanks.

**Comment by vtyutin** [comment]
Here is my log showing same issue:

youtube-dl.exe -v -o "%(title)s" --no-playlist --skip-download --restrict-filenames --write-info-json "https://soundcloud.com/nero/nero-into-the-past"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-o', '%(title)s', '--no-playlist', '--skip-download', '--restrict-filenames', '--write-info-json', 'https://soundcloud.co
m/nero/nero-into-the-past']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.08.13
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[soundcloud] nero/nero-into-the-past: Downloading webpage
[soundcloud] nero/nero-into-the-past: Downloading info JSON
[soundcloud] 89121986: Downloading track url
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
[soundcloud] 89121986: Checking fallback video format URL
[soundcloud] 89121986: fallback video format URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to updat
e. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\common.py", line 530, in extract
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\soundcloud.py", line 449, in real_extract
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72\build\youtube_dl\extractor\soundcloud.py", line 388, in extract_info_dic
t
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; typ
e youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
