### ISSUE TITLE
[Suggestion] Supporting MEO Go

### ISSUE THREAD

**Issue by Abernecio** [ytdl-org/youtube-dl#22127]
Hi!
I would like to request support for meogo.meo.pt

MEO is a portuguese ISP that allows you to watch recorded TV and live TV when you login into the site. It uses JW Player and fragmented video.

I tried using --cookies, but this was the output:

```C:\Users\abernecio>youtube-dl --cookies "C:\Users\abernecio\Downloads\cookies.txt" -F -v https://meogo.meo.pt/ver?programa=10771158
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'C:\\Users\\abernecio\\Downloads\\cookies.txt', '-F', '-v', 'https://meogo.meo.pt/ver?programa=10771158']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.07.27
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-92833-gfccba32b4c, rtmpdump 2.3
[debug] Proxy map: {}
[generic] ver?programa=10771158: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ver?programa=10771158: Downloading webpage
[generic] ver?programa=10771158: Extracting information
ERROR: Unsupported URL: https://meogo.meo.pt/ver?programa=10771158
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpzo5f6a6e\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpzo5f6a6e\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpzo5f6a6e\build\youtube_dl\extractor\generic.py", line 3333, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://meogo.meo.pt/ver?programa=10771158```

Thank you and keep up the good work!

**Comment by dstftw** [comment]
You must provide account credentials.
