### ISSUE TITLE
--ignore-errors to ignore when video is not available

### ISSUE THREAD

**Issue by gregormci** [ytdl-org/youtube-dl#22139]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I have a list of previously downloaded urls, i would like to attempt to redownload them all without needed to individually check each file on youtube to see if the video is still available.

there is an option i see to ignore errors `--ignore-errors` . however after reading online it appears that it does not support not finding the video. see below for the .py error because `url` is NULL.
so, `ie_result = self._real_extract(url)` where `url` is not found throws this error and is not captured by the --ignore-error flag.

```bash
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Sorry about that.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 2108, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: Sorry about that.
```

**Comment by dstftw** [comment]
```
> py -3.7 .\youtube_dl\__main__.py https://www.youtube.com/playlist?list=PLa1F2ddGya_-UvuAqHAksYnB0qL9yWDO6 --playlist-start 31 --ignore-errors
[youtube:playlist] PLa1F2ddGya_-UvuAqHAksYnB0qL9yWDO6: Downloading webpage
[download] Downloading playlist: Blender Fundamentals 2.8
[youtube:playlist] playlist Blender Fundamentals 2.8: Downloading 11 videos
[download] Downloading video 1 of 11
[youtube] fx33sPEAZEk: Downloading webpage
[youtube] fx33sPEAZEk: Downloading video info webpage
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: This video is unavailable.
Sorry about that.
[download] Downloading video 2 of 11
[youtube] aGBOu-dNZ-w: Downloading webpage
[youtube] aGBOu-dNZ-w: Downloading video info webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: Tracking Constraints - Blender 2.80 Fundamentals.f137.mp4
[download]  36.2% of 18.23MiB at  3.65MiB/s ETA 00:03
ERROR: Interrupted by user
```

**Comment by gregormci** [comment]
why did you assume it was a playlist i was referring too?
try this and you'll see what i'm requesting:
```
python youtube_dl/__main__.py --ignore-errors https://www.youtube.com/watch?v=MF1qEhBSfq4 && python youtube_dl/__main__.py --ignore-errors https://www.youtube.com/watch?v=wrongvidecode && python youtube_dl/__main__.py --ignore-errors https://www.youtube.com/watch?v=9Q7xaqjZDMw
```

**Comment by dstftw** [comment]
I'm not a black magician to fortune tell what did you mean by that. If you are requested to provide complete verbose log then you must provide it.
`--ignore-errors` means exactly what it spells: ignore errors while downloading, it does not affect return code. Now bother to read doc on how your shell's `&&` works.
Bottomline: you must either pass all URLs in a single invocation of youtube-dl or use `&`.
