### ISSUE TITLE
No video formats found (7plus)

### ISSUE THREAD

**Issue by Stuntaneous** [ytdl-org/youtube-dl#22136]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[7plus] PORE01-002: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\sevenplus.py", line 61, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\brightcove.py", line 695, in _parse_brightcove_metadata
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

7plus video fails to download with error "no video formats found". Episode 1 downloads fine (https://7plus.com.au/police-rescue?episode-id=PORE01-001) but this second episode does not (https://7plus.com.au/police-rescue?episode-id=PORE01-002). Login not required.

**Comment by Stuntaneous** [comment]
I don't understand the closing + DRM label. I've downloaded whole shows from the same site without issue, including another episode from this same season.

**Comment by dstftw** [comment]
https://7plus.com.au/police-rescue?episode-id=PORE01-001 is not DRM protected.
https://7plus.com.au/police-rescue?episode-id=PORE01-002 is DRM protected.
What's not clear?

**Comment by Stuntaneous** [comment]
Why would that be the case? Comparable shows have no issue, the first episode has no issue, why would there suddenly be DRM on episode 2 of this long forgotten show on lowly 7plus? It seems bizarre.

**Comment by dstftw** [comment]
Ask them why.
