### ISSUE TITLE
WARNING: Unable to extract video title 

### ISSUE THREAD

**Issue by fredsavoir** [ytdl-org/youtube-dl#22132]
youtube-dl -vUo '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' https://www.youtube.com/playlist?list=PLa1F2ddGya_-UvuAqHAksYnB0qL9yWDO6

WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2105, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is unavailable.

**Comment by fredsavoir** [comment]
Why closing ?

**Comment by fredsavoir** [comment]
It's when Private link are inserted in the playlist

**Comment by fredsavoir** [comment]
Ok is you use '-I' it's skip to the next one :)
Thanks
