### ISSUE TITLE
ERROR: Unable to extract OpenGraph title (--cookies bug)

### ISSUE THREAD

**Issue by michealespinola** [ytdl-org/youtube-dl#22142]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2019.08.13**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
C:\bin>youtube-dl --verbose https://twitter.com/vincentpeone/status/1160977452299984896
[debug] System config: []
[debug] User config: ['--sub-lang', 'en,EN,eng,ENG,en-us,en-US,EN-US', '--write-sub', '--write-auto-sub', '--write-thumbnail', '--write-all-thumbnails', '--write-description', '--write-info-json', '--add-metadata', '--xattrs', '--no-playlist', '--cookies', 'C:\\bin\\cookies.txt', '--no-check-certificate', '--user-agent', '', '--abort-on-unavailable-fragment', '--socket-timeout', '3', '--retries', '999', '--hls-prefer-native', '--ffmpeg-location', 'C:\\Program Files\\ffmpeg\\bin\\ffmpeg.exe', '--merge-output-format', 'mkv', '--no-mtime', '--output', 'C:\\Downloads\\%(title)s [%(resolution)s] [%(id)s].%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://twitter.com/vincentpeone/status/1160977452299984896']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.08.13
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-94066-g18dab6175b, ffprobe N-94066-g18dab6175b, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[twitter] 1160977452299984896: Downloading webpage
ERROR: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\twitter.py", line 464, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\common.py", line 1117, in _og_search_title
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\common.py", line 1105, in _og_search_property
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

This error occurs against multiple video hosting websites.  The above twitter URL is an example of a systemic problem.  From what I have been able to deduce so far is that this issue is being caused by the `--cookies` option.    Tested details:

1. This error does not occur when I remove the cookies option from my config file.
2. This error does not occur when I use `--ignore-config` and no other options.
3. This error *does* occur when I use --`cookies 'C:\bin\cookies.txt'` as an option at the command line.
4. This problem did not exist with my config options (~2) versions back - as far as I am aware.

My cookies.txt file is a properly formatted "Netscape HTTP Cookie File".

Thank you for your attention to this.

**Comment by michealespinola** [comment]
@dstftw Not to question your expertise here, but are you certain this is a duplicate?  As I stated, this happens ONLY when I use the --cookies option.  This happens before any download occurs.  This happens even if `--prefer-avconv` is used.

**Comment by dstftw** [comment]
Use search? #20855.
