### ISSUE TITLE
[YouTube] "token" parameter not in video (using 2018-08-13 version)

### ISSUE THREAD

**Issue by aliveawakened** [ytdl-org/youtube-dl#22146]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2019.08.13**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
D:\Users\steve\Downloads>youtube-dl -v -x https://www.youtube.com/watch?v=FwkIwNEX7hM
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-x', 'https://www.youtube.com/watch?v=FwkIwNEX7hM']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-94575-gcff309097a, ffprobe N-94575-gcff309097a
[debug] Proxy map: {}
[youtube] FwkIwNEX7hM: Downloading webpage
[youtube] FwkIwNEX7hM: Downloading video info webpage
ERROR: FwkIwNEX7hM: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\YoutubeDL.py", line 793, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\youtube.py", line 1674, in _real_extract
youtube_dl.utils.ExtractorError: FwkIwNEX7hM: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Attempting download from YouTube public page produces a "'token' parameter not in video" error, and this is is with the latest available version (so if you flag this as "outdated" you didn't read the ticket).

**Comment by aliveawakened** [comment]
NM, apparently have a version conflict (the version in python is the latest, but there's another copy on the system that's old.
