### ISSUE TITLE
Cannot download playlist and convert to mp3

### ISSUE THREAD

**Issue by conteit** [ytdl-org/youtube-dl#22147]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2019.08.13**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--extract-audio', u'--audio-format', u'mp3', u'-o', u'%(id)s.%(ext)s', u'https://www.youtube.com/watch?v=9jK-NcRmVcw&list=RDQMPD5lL89FpdA', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.7.15 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.2, ffprobe 4.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist RDQMPD5lL89FpdA - add --no-playlist to just download video 9jK-NcRmVcw
[youtube:playlist] RDQMPD5lL89FpdA: Downloading page 1 of Youtube mix
[youtube:playlist] RDQMPD5lL89FpdA: Downloading page 2 of Youtube mix
[youtube:playlist] RDQMPD5lL89FpdA: Downloading page 3 of Youtube mix
[youtube:playlist] RDQMPD5lL89FpdA: Downloading page 4 of Youtube mix
[youtube:playlist] RDQMPD5lL89FpdA: Downloading page 5 of Youtube mix
[download] Downloading playlist: Mix - Mix anni 80
[youtube:playlist] playlist Mix - Mix anni 80: Collected 82 video ids (downloading 82 of them)
[download] Downloading video 1 of 82
[youtube] PD5lL89FpdA: Downloading webpage
[youtube] PD5lL89FpdA: Downloading video info webpage
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Sorry about that.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2108, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: Sorry about that.
```

## Description

I'm trying to run the following command and the tool fails extracting data. So the procedure aborts and assert to open an issue.

Command:
```
youtube-dl --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=9jK-NcRmVcw&list=RDQMPD5lL89FpdA
```

**Comment by dstftw** [comment]
`-i`.
