### ISSUE TITLE
[Globo] Globosatplay + Globoplay 

### ISSUE THREAD

**Issue by D3rel** [ytdl-org/youtube-dl#22169]
Hi Guys!! 

I would like to request fix the download for the Globo sites. Currently the program downloads videos that do not require login, but for those who need login and password, it does not recognize the video links to download

```
[Globo] Downloading JSON metadata
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\YoutubeDL.py", line 2229, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\globo.py", line 83, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\common.py", line 892, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\common.py", line 870, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\common.py", line 660, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\common.py", line 645, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\YoutubeDL.py", line 2010, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\common.py", line 433, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\globo.py", line 89, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 312, in loads
TypeError: the JSON object must be str, not 'bytes'.
```

**Comment by DESKTOP-RX90B689** [comment]
@dstftw 

currently globe extractor is having problems authenticating with globoplay platform videos

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--cookies', u'cookies.txt', u'https://globoplay.globo.com/v/6002976/programa/', u'-F', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 2.7.13 (CPython) - Linux-4.15.0-30deepin-generic-x86_64-with-Deepin-15.11-stable
[debug] exe versions: avconv 3.2.12-1, avprobe 3.2.12-1, ffmpeg 3.2.12-1, ffprobe 3.2.12-1, rtmpdump 2.4
[debug] Proxy map: {}
[Globo] 6002976: Downloading JSON metadata
[Globo] 6002976: Downloading security hash for 6002976_manifest_360_1080_m3u8
[Globo] 6002976_manifest_360_1080_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 6002976: Downloading security hash for 6002976_manifest_360_1080_l_m3u8
[Globo] 6002976_manifest_360_1080_l_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 6002976: Downloading security hash for 6002976_manifest_90_720_m3u8
[Globo] 6002976_manifest_90_720_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 6002976: Downloading security hash for 6002976_manifest_240_720_m3u8
[Globo] 6002976_manifest_240_720_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 6002976: Downloading security hash for 6002976_manifest_90_720_l_m3u8
[Globo] 6002976_manifest_90_720_l_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 6002976: Downloading security hash for 6002976_manifest_90_480_m3u8
[Globo] 6002976_manifest_90_480_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 6002976: Downloading security hash for 6002976_manifest_360_1080_mpd
[Globo] 6002976_manifest_360_1080_mpd: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[Globo] 6002976: Downloading security hash for 6002976_manifest_360_2160_m3u8
[Globo] 6002976_manifest_360_2160_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 6002976: Downloading security hash for 6002976_manifest_240_720_l_m3u8
[Globo] 6002976_manifest_240_720_l_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 6002976: Downloading security hash for 6002976_manifest_360_2160_l_m3u8
[Globo] 6002976_manifest_360_2160_l_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 6002976: Downloading security hash for 6002976_manifest_360_1080_l_manifest
[Globo] 6002976_manifest_360_1080_l_manifest: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 403: Forbidden
[Globo] 6002976: Downloading security hash for 6002976_manifest_360_1080_l_mpd
[Globo] 6002976_manifest_360_1080_l_mpd: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[Globo] 6002976: Downloading security hash for 6002976_manifest_360_2160_mpd
[Globo] 6002976_manifest_360_2160_mpd: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[Globo] 6002976: Downloading security hash for 6002976_manifest_90_720_mpd
[Globo] 6002976_manifest_90_720_mpd: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/globo.py", line 155, in _real_extract
    self._sort_formats(formats)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
