### ISSUE TITLE
Youtube: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info

### ISSUE THREAD

**Issue by gradha** [ytdl-org/youtube-dl#22163]
- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2019.08.13**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

Might be a duplicate of #21814, which indicates temporal problems. 

## Verbose log

```
$ youtube-dl --verbose  http://www.youtube.com/watch?v=-LDlW8b0qBE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.youtube.com/watch?v=-LDlW8b0qBE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.7.15 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {}
[youtube] -LDlW8b0qBE: Downloading webpage
[youtube] -LDlW8b0qBE: Downloading video info webpage
ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/gradha/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/Users/gradha/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/Users/gradha/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2109, in _real_extract
    raise ExtractorError('no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info')
ExtractorError: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Found video https://www.youtube.com/watch?v=-LDlW8b0qBE which fails to download. The previous video in the stream (https://www.youtube.com/watch?v=NK6ZJsOio9Q) downloads fine:

```
$ youtube-dl  https://www.youtube.com/watch?v=NK6ZJsOio9Q
[youtube] NK6ZJsOio9Q: Downloading webpage
[youtube] NK6ZJsOio9Q: Downloading video info webpage
[youtube] NK6ZJsOio9Q: Downloading MPD manifest
[dashsegments] Total fragments: 18
[download] Destination: Woohyun-NK6ZJsOio9Q.f247.webm
^C
ERROR: Interrupted by user
```

**Comment by ktorn** [comment]
I'm having this issue with every video, including videos that I had previously downloaded.
```
$ youtube-dl --verbose https://www.youtube.com/watch?v=_zdW9qJhImA
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=_zdW9qJhImA']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 3.7.4 (CPython) - Linux-4.19.66-1-MANJARO-x86_64-with-arch-Manjaro-Linux
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] _zdW9qJhImA: Downloading webpage
[youtube] _zdW9qJhImA: Downloading video info webpage
ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 2109, in _real_extract
    raise ExtractorError('no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info')
youtube_dl.utils.ExtractorError: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
