### ISSUE TITLE
Hotstar extractor not working, gives Geo-Restriction error.

### ISSUE THREAD

**Issue by Y4shSHD** [ytdl-org/youtube-dl#22172]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v https://www.hotstar.com/tv/kahaan-hum-kahaan-tum/s-2196/rohit-in-a-tough-spot/1000241332
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.hotstar.com/tv/kahaan-hum-kahaan-tum/s-2196/rohit-in-a-tough-spot/1000241332']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.7.10 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[hotstar] 1000241332: Downloading webpage
[hotstar] 1000241332: Downloading JSON metadata
[hotstar] 1000241332: Downloading m3u8 information
[hotstar] 1000241332: Downloading MPD manifest
[hotstar] 1000241332: Downloading MPD manifest
[hotstar] 1000241332: Downloading m3u8 information
[hotstar] 1000241332: Downloading MPD manifest
[hotstar] 1000241332: Downloading m3u8 information
[hotstar] 1000241332: Downloading MPD manifest
ERROR: This video is not available from your location due to geo restriction
This video is available in India.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/hotstar.py", line 139, in _real_extract
    format_url, video_id, mpd_id='dash'))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2019, in _extract_mpd_formats
    fatal=fatal)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 820, in _download_xml_handle
    expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 660, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 645, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Failed to download MPD manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/hotstar.py", line 154, in _real_extract
    self.raise_geo_restricted(countries=['IN'])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 940, in raise_geo_restricted
    raise GeoRestrictedError(msg, countries=countries)
GeoRestrictedError: This video is not available from your location due to geo-restriction
```

## Description

Hotstar has updated its resource security. The extractor was working till yesterday. And today, it has stopped working.

**Comment by Y4shSHD** [comment]
"hses.akamized.net" based mpd and m3u8 urls have been protected.

**Comment by dstftw** [comment]
Does not play in browser either.

**Comment by Y4shSHD** [comment]
It works on Browser. Youtube-dl isn’t able to extract information

**Comment by brijeshkamani11** [comment]
same issues please give me solution....
