### ISSUE TITLE
Playlist Support for ARD-Mediathek Series Overview

### ISSUE THREAD

**Issue by riconeitzel** [ytdl-org/youtube-dl#22209]
# Checklist

[x] - First of, make sure you are using the latest version of youtube-dl. Run `youtube-dl --version` and ensure your version is 2019.08.13. If it's not, see https://yt-dl.org/update on how to update. Issues with outdated version will be REJECTED.

```
# youtube-dl -U
Updating to version 2019.08.13 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
```

- [x] Make sure that all provided video/audio/playlist URLs (if any) are alive and playable in a browser.

[x] - Search the bugtracker for similar site support requests: http://yt-dl.org/search-issues. DO NOT post duplicates.

there are some tickets but all share the same "ampersand in url" issue.

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

Playlist URL:
https://www.ardmediathek.de/hr/shows/Y3JpZDovL2hyLW9ubGluZS8zODIyMDAzMw/mittendrin-flughafen-frankfurt

## Description

Playlist pages can't be parsed:

```

# youtube-dl https://www.ardmediathek.de/hr/shows/Y3JpZDovL2hyLW9ubGluZS8zODIyMDAzMw/mittendrin-flughafen-frankfurt --verbose
[debug] System config: []
[debug] User config: [u'-f', u'299+141/299+140/299+139/138+141/138+140/138+139/266+141/266+140/266+139/264+141/264+140/264+139/137+141/137+140/137+139/136+141/136+140/136+139/22+141/22+140/22+139/135+141/135+140/135+139/134+141/134+140/134+139/133+141/133+140/133+139/best', u'--add-metadata']
[debug] Custom config: []
[debug] Command-line args: [u'https://www.ardmediathek.de/hr/shows/Y3JpZDovL2hyLW9ubGluZS8zODIyMDAzMw/mittendrin-flughafen-frankfurt', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.7.15 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[ARD:mediathek] mittendrin-flughafen-frankfurt: Downloading webpage
ERROR: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ard.py", line 229, in _real_extract
    r'/play/(?:config|media)/(\d+)', webpage, 'media id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by TinyToweringTree** [comment]
Pull request #22283 fixes this. Feedback's welcome. :)

**Comment by martin54** [comment]
There's an updated pull request #25783 to support ARD playlists. Feedback's welcome. :)

**Comment by oneiros-de** [comment]
Bug is still present in 2020.12.05

**Comment by martin54** [comment]
I made a test with my version of ard.py, which is probably different to 2020.12.05.
Result: The URL from the issue above ( https://www.ardmediathek.de/hr/shows/Y3JpZDovL2hyLW9ubGluZS8zODIyMDAzMw/mittendrin-flughafen-frankfurt )
is processed by the old [ARD:mediathek] with error.
A search on ardmediathek returns another URL: https://www.ardmediathek.de/hr/sendung/mittendrin-flughafen-frankfurt/staffel-1/Y3JpZDovL2hyLW9ubGluZS8zODIyMDAzMw/1/
That's processed by the new [ARD**Beta**Mediathek], but also with error.
BUT: if removing "/1/" from the end of the URL, then playlist download is successful :-)
```
>%ytdl% "https://www.ardmediathek.de/ard/sendung/mittendrin-flughafen-frankfurt/staffel-1/Y3JpZDovL2hyLW9ubGluZS8zODIyMDAzMw"
[ARDBetaMediathekPlaylist] mittendrin-flughafen-frankfurt/staffel-1: Downloading JSON metadata
[download] Downloading playlist: mittendrin-flughafen-frankfurt/staffel-1
[ARDBetaMediathekPlaylist] playlist mittendrin-flughafen-frankfurt/staffel-1: Collected 32 video ids (downloading 32 of them)
[download] Downloading video 1 of 32
[ARDBetaMediathek] mittendrin-flughafen-frankfurt/staffel-1/mammutaufgabe-flughafen-koordination-s01-e01: Downloading JSON metadata
[ARDBetaMediathek] 82494032: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 266
[download] Destination: Mammutaufgabe Flughafen-Koordination (S01_E01)-82494032.mp4
[download]   1.1% of ~2.31GiB at  5.84MiB/s ETA 07:46

```

It's still a bug, but at least a workaround exists ...
