### ISSUE TITLE
Unable to download JSON metadata for SoundCloud

### ISSUE THREAD

**Issue by vtyutin** [ytdl-org/youtube-dl#22230]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dl.exe -v -o "%(title)s" --no-playlist --skip-download --restrict-filenames --write-info-json "https://soundcloud.com/nero/nero-into-the-past"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-o', '%(title)s', '--no-playlist', '--skip-download', '--restrict-filenames', '--write-info-json', 'https://soundcloud.co
m/nero/nero-into-the-past']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.08.13
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[soundcloud] nero/nero-into-the-past: Downloading webpage
[soundcloud] nero/nero-into-the-past: Downloading info JSON
[soundcloud] 89121986: Downloading track url
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
[soundcloud] 89121986: Checking fallback video format URL
[soundcloud] 89121986: fallback video format URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to updat
e. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\soundcloud.py", line 449, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\soundcloud.py", line 388, in _extract_info_dic
t
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; typ
e  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE
This link for SoundCloud can't be processed by youtube-dl "https://soundcloud.com/nero/the-satisfy-mix". Still it works fine in browser. I use the latest version 13.08 for youtube-dl. Please analyse the log and fix the issue.

**Comment by vtyutin** [comment]
Please give me a link to duplicate issue.
