### ISSUE TITLE
Unable to download theonion.com's embedded videos.

### ISSUE THREAD

**Issue by antdude** [ytdl-org/youtube-dl#22237]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2019.08.13**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl -v https://www.theonion.com/a-look-at-the-class-of-2023-1837408900
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.theonion.com/a-look-at-the-class-of-2023-1837408900']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 3.4.2 (CPython) - Linux-3.16.0-10-amd64-x86_64-with-debian-8.11
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] a-look-at-the-class-of-2023-1837408900: Requesting header
WARNING: Falling back on generic information extractor.
[generic] a-look-at-the-class-of-2023-1837408900: Downloading webpage
[generic] a-look-at-the-class-of-2023-1837408900: Extracting information
ERROR: Unsupported URL: https://www.theonion.com/a-look-at-the-class-of-2023-1837408900
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3333, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.theonion.com/a-look-at-the-class-of-2023-1837408900
```

## Description

WRITE DESCRIPTION HERE
Unable to download theonion.com's embedded videos like https://www.theonion.com/a-look-at-the-class-of-2023-1837408900.

**Comment by antdude** [comment]
My original post was from my decade old, updated Debian Jessie v8. Here's from my friend's Fedora:

```
$ youtube-dl -v https://www.theonion.com/a-look-at-the-class-of-2023-1837408900
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.theonion.com/a-look-at-the-class-of-2023-1837408900']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.7.16 (CPython) - Linux-4.20.8-200.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
[debug] exe versions: ffmpeg 4.0.4, ffprobe 4.0.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] a-look-at-the-class-of-2023-1837408900: Requesting header
WARNING: Falling back on generic information extractor.
[generic] a-look-at-the-class-of-2023-1837408900: Downloading webpage
[generic] a-look-at-the-class-of-2023-1837408900: Extracting information
ERROR: Unsupported URL: https://www.theonion.com/a-look-at-the-class-of-2023-1837408900
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2357, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/home/ant/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/home/ant/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 8, column 20
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3333, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.theonion.com/a-look-at-the-class-of-2023-1837408900
```
