### ISSUE TITLE
Some NHK shows result in "IndexError: list index out of range"

### ISSUE THREAD

**Issue by DHandspikerWade** [ytdl-org/youtube-dl#22249]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2019240/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-58-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 17, rtmpdump 2.4
[debug] Proxy map: {}
[NhkVod] 2019-240: Downloading JSON metadata
[Ooyala] nw_vod_v_en_2019_240_20190823233000_02_1566873477: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2010, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 807, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 873, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ooyala.py", line 170, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ooyala.py", line 28, in _extract
IndexError: list index out of range
```

## Description

Using the command `youtube-dl -v  https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2019240/` results in the above traceback and an exit code of 1. The show for this URL is "Dining with chief".

However the command `youtube-dl -v  https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2032106/` results in the expected video being downloaded without error. The show for this URL is "Japanology Plus".

**Comment by VietTPham** [comment]
Not the problem with the program. The site changed their url for all the .m3u8 files
