### ISSUE TITLE
[Zattoo] Update site web

### ISSUE THREAD

**Issue by Europe57** [ytdl-org/youtube-dl#22258]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

```
NEW ADRESS:
youtube-dl https://zattoo.com/channels\?channel\=rts_un --username **** --password *** -f hls-3002-A-1500 --o "RTS Un - NCIS S16E13.mp4" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://zattoo.com/channels?channel=rts_un', '--username', 'PRIVATE', '--password', 'PRIVATE', '-f', 'hls-3002-A-1500', '--o', 'RTS Un - NCIS S16E13.mp4', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 3.5.3 (CPython) - Linux-4.19.0-0.bpo.5-amd64-x86_64-with-debian-9.9
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1
[debug] Proxy map: {}
[generic] channels?channel=rts_un: Requesting header
WARNING: Falling back on generic information extractor.
[generic] channels?channel=rts_un: Downloading webpage
[generic] channels?channel=rts_un: Extracting information
ERROR: Unsupported URL: https://zattoo.com/channels?channel=rts_un
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/generic.py", line 3333, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://zattoo.com/channels?channel=rts_un

[1]    2458 exit 1     youtube-dl https://zattoo.com/channels\?channel\=rts_un --username  --passwor

OLD ADRESS:

youtube-dl https://zattoo.com/watch/rts_un --username **** --password *** -f hls-3002-A-1500 --o "RTS Un - NCIS S16E13.mp4" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://zattoo.com/watch/rts_un', '--username', 'PRIVATE', '--password', 'PRIVATE', '-f', 'hls-3002-A-1500', '--o', 'RTS Un - NCIS S16E13.mp4', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 3.5.3 (CPython) - Linux-4.19.0-0.bpo.5-amd64-x86_64-with-debian-9.9
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1
[debug] Proxy map: {}
[ZattooLive] Downloading app token
[ZattooLive] Opening session
ERROR: Unable to download webpage: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 2229, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

[1]    2502 exit 1     youtube-dl https://zattoo.com/watch/rts_un --username ****


```

## Description

New website, with new address to access the channel.
Example for RTS One, formerly: https://zattoo.com/watch/rts_un
New address: https://zattoo.com/channels?channel=rts_un
The 2 addresses no longer works on Youtube-DL
If need ids to make tests, thank you to contact me in private at the address rectv.forum@gmail.com
Thank.

**Comment by goggle** [comment]
I'm the original author of this information extractor. To get all the features working again, I need access to a premium account. If anyone can provide one, let me know. You find my email on my github profile.

**Comment by goggle** [comment]
For anyone interested: You find an adoption of the information extractor here: https://github.com/goggle/youtube-dl/tree/zattoo-new-website
It supports live TV, on-demand videos and recorded videos for the new zattoo website. To get the replay feature working, I need access to a premium account. If someone can provide one, let me know. After that I will make a PR to get the changes included into youtube-dl.

**Comment by Europe57** [comment]
Thank you.

**Comment by MrShoenel** [comment]
Thanks, @goggle! Did you make a PR so it's fixed in the official release as well?

**Comment by goggle** [comment]
@MrShoenel Yes, there is a PR, see https://github.com/ytdl-org/youtube-dl/pull/22759. Unfortunately, I did not have the time yet to completely go through all the points from the review... I also don't have a Zattoo premium account, which makes it somewhat difficult. So if anyone can give me access to a premium account, that would still help a lot.

**Comment by MrShoenel** [comment]
@goggle I sent you account details for a premium account :)

**Comment by seiz** [comment]
@goggle hey, your fork just stopped working as it can't get the app token anymore. Any chance to get this fixed somehow? I ask, because zattoo will turn off recordings soon for premium accounts and i'd like to download my existing recordings.

**Comment by goggle** [comment]
@seiz Is there any chance to have access to your premium account (I do not have one)?
You can find my email address on my github user page.

**Comment by seiz** [comment]
@goggle thought, @MrShoenel sent you one already. I'll happily buy you one for a month, if he didn't.

**Comment by goggle** [comment]
@seiz Yes, but it expired during the review process of #22759 if I remember correctly...
Let's discuss this further via email.

**Comment by seiz** [comment]
@goggle OK, account info is underway to your email.

**Comment by misteranonymus** [comment]
Okay, my Issue is closed because this is the Issue for the problem

Zattoo changed the login.
The app.token is now requested differently
The Applikation [Streamlink](https://github.com/streamlink/streamlink/issues) changed the part with the app.token.

A member of the [VU+ Support](https://www.vuplus-support.org/wbb4/index.php?thread/111677-streamlink-der-nachfolger-von-livestreamer/&postID=1994909#post1994909) says:
Change the line 158 from [zattoo.py](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/zattoo.py) to this
`res = self.session.http.get(self.base_url + '/ch')
       `
and it works.
But the different is for some members it works with **/int** and for some members it work with **/ch**
