### ISSUE TITLE
Fail to download CBS videos

### ISSUE THREAD

**Issue by hixon6823** [ytdl-org/youtube-dl#22264]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2019/07/24/1575704131720/75725_cenc_dash/stream.mpd
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2019/07/24/1575704131720/75725_cenc_dash/stream.mpd']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.7.16 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2
[debug] Proxy map: {'ftp': 'ftp://127.0.0.1:1061', 'http': 'http://127.0.0.1:1061', 'https': 'https://127.0.0.1:1061'}
[generic] stream: Requesting header
WARNING: Falling back on generic information extractor.
[generic] stream: Downloading webpage
[generic] stream: Extracting information
WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\generic.py", line 2379, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

tried youtube-dl with .mpd file of a cbs video, failed to download it.
corresponding url: https://www.cbs.com/shows/million-dollar-mile/video/bxwlP_chYJNhorJaDhB75Q9KvcOOlMGI/million-dollar-mile-i-was-born-ready-for-this/

**Comment by remitamine** [comment]
use the original URL.
