### ISSUE TITLE
onlystream.tv

### ISSUE THREAD

**Issue by condor0765** [ytdl-org/youtube-dl#22275]
## Checklist

- [x] I'm reporting a new site support request
- [X] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://onlystream.tv/y4wuipaeondd

## Description

Not downloading
```
youtube-dl -v "https://onlystream.tv/e/k3sac37kvvwd"
[debug] System config: []
[debug] User config: [u'-i', u'-o', u'%(uploader)s (%(uploader_id)s)/%(upload_date)s - %(title)s - (%(duration)ss) [%(resolution)s] [%(id)s].%(ext)s', u'--download-archive', u'~/youtube-dl-archive.txt', u'--prefer-ffmpeg', u'--merge-output-format', u'mkv', u'--format', u'22', u'--write-sub', u'--all-subs', u'--convert-subs', u'srt', u'--embed-subs', u'--add-metadata', u'--write-description', u'--write-thumbnail']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://onlystream.tv/e/k3sac37kvvwd']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-58-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: avconv 3.4.6, avprobe 3.4.6, ffmpeg 3.4.6, ffprobe 3.4.6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] k3sac37kvvwd: Requesting header
WARNING: Falling back on generic information extractor.
[generic] k3sac37kvvwd: Downloading webpage
[generic] k3sac37kvvwd: Extracting information
[generic] master: Downloading m3u8 information
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 861, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1634, in process_video_result
    expected=True)
ExtractorError: requested format not available

```

**Comment by dstftw** [comment]
>requested format not available

**Comment by cpeakdot** [comment]
Their system sucks. I've been messaging to their support team for a year now. Only answer i got is " our support team will answer".. I bought premium bandwith from them and still they can't even solve my one problem...
