### ISSUE TITLE
SVT extractor not working

### ISSUE THREAD

**Issue by larkov** [ytdl-org/youtube-dl#22297]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-a', u'url.txt', u'--download-archive', u'./archive.file', u'--verbose']
[debug] Batch file urls: [u'https://www.svtplay.se/kommissarie-banks']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.01
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-58-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, rtmpdump 2.3
[debug] Proxy map: {}
[debug] Using fake IP 78.67.9.49 (SE) as X-Forwarded-For.
[SVTSeries] kommissarie-banks: Downloading series page
ERROR: An extractor error has occurred. (caused by KeyError(u'relatedVideosAccordion',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/svt.py", line 283, in _real_extract
    for season in root['relatedVideoContent']['relatedVideosAccordion']:
KeyError: u'relatedVideosAccordion'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 543, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'relatedVideosAccordion',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete
output.
```

## Description

Several other sites also seem to have extractor problems also. I'm using the latest Ubuntu LTS server version.

**Comment by mattiasa** [comment]
It looks like SVT has changed the json structure they return. I pushed a fix to https://github.com/mattiasa/youtube-dl/tree/svt which at least solves downloading a whole series. There was some code which downloads a single season which I haven't re-implemented yet. I'll see if I get time to clean this up and create a PR for it.

**Comment by larkov** [comment]
Single episode download works as normal so I solved my problem by fetching those episode urls from the rss feed.
