### ISSUE TITLE
[UFC.com] Add support?

### ISSUE THREAD

**Issue by channelmars** [ytdl-org/youtube-dl#22291]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.09.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

##

- Single video: https://www.ufc.com/video/ufc-242-countdown-full-episode
- Single video: https://www.ufc.com/video/ufc-242-free-fight-poirier-vs-alvarez-2

## Description

youtube-dl https://www.ufc.com/video/ufc-242-countdown-full-episode
[generic] ufc-242-countdown-full-episode: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ufc-242-countdown-full-episode: Downloading webpage
[generic] ufc-242-countdown-full-episode: Extracting information
ERROR: Unsupported URL: https://www.ufc.com/video/ufc-242-countdown-full-episode

-----

Verbose:

-----

youtube-dl https://www.ufc.com/video/ufc-242-countdown-full-episode
[generic] ufc-242-countdown-full-episode: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ufc-242-countdown-full-episode: Downloading webpage
[generic] ufc-242-countdown-full-episode: Extracting information
ERROR: Unsupported URL: https://www.ufc.com/video/ufc-242-countdown-full-episode

youtube-dl --verbose https://www.ufc.com/video/ufc-242-countdown-full-episode
[debug] System config: []
[debug] User config: ['--format', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4', '-i', '-o', 'E:\\Videos\\%(upload_date)s - %(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.ufc.com/video/ufc-242-countdown-full-episode']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.09.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4
[debug] Proxy map: {}
[generic] ufc-242-countdown-full-episode: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ufc-242-countdown-full-episode: Downloading webpage
[generic] ufc-242-countdown-full-episode: Extracting information
ERROR: Unsupported URL: https://www.ufc.com/video/ufc-242-countdown-full-episode
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\generic.py", line 3355, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.ufc.com/video/ufc-242-countdown-full-episode

**Comment by channelmars** [comment]
Sorry for the duplicate post.
