### ISSUE TITLE
Markiza broken support/no longer working

### ISSUE THREAD

**Issue by 76spiderman76** [ytdl-org/youtube-dl#22301]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://videoarchiv.markiza.sk/video/oteckovia/epizoda/24093-oteckovia-112']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.09.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-93005-gd92f06eb66, ffprobe N-93005-gd92f06eb66
[debug] Proxy map: {}
[generic] 24093-oteckovia-112: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 24093-oteckovia-112: Downloading webpage
[generic] 24093-oteckovia-112: Extracting information
ERROR: Unsupported URL: https://videoarchiv.markiza.sk/video/oteckovia/epizoda/24093-oteckovia-112
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\generic.py", line 3355, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://videoarchiv.markiza.sk/video/oteckovia/epizoda/24093-oteckovia-112
```

## Description

Hello, using youtube-dl on Markzia website does not work. They changed URL a little, maybe updating python script will work?

**Comment by torbs723** [comment]
Is this fixable?
