### ISSUE TITLE
Problem downloading MPEG-DASH video

### ISSUE THREAD

**Issue by Canta** [ytdl-org/youtube-dl#22326]
Hi there.

`youtube-dl` is great, and so I'm trying to use it for a simple use case: downloading some private streams I have on some private servers. This is mostly for backup purposes, but also other marginal use cases. I'm looking for a command line MPEG-DASH downloading tool, and `youtube-dl` seems to be the best around.

Please note this issue is about **DOWNLOADING** the files; **not PLAYING, not DECRIPTING, not TRANSCODING**, nor any other operation but downloading. That means parsing the MPD manifest, interpreting the chunks paths, and downloading them just as they are. I say this because the files are DRM protected, and every time I say "DRM protected" the chat deviates to "you can't play it if it's protected". I just want to download the manifest AND the chunks: something I would do with curl/wget, if manifest parsing wasn't involved.

So, It should be piece of cake, but `youtube-dl` doesn't seems to like my manifest.
As it will be clear in the logs, the manifest is perfectly valid, and I've playing this streams for years on different players without any problem. It's weird. Maybe I'm doing something wrong, but I see that "No video formats found" error at the end, so I think this could also be a problem with the MPD parsing logic, and that's why I bring this issue here.

Here are the logs, manifest and HTTP server dialog data included:

```
$ curl -v "https://REDACTED_HOST/manifest.mpd" 
*   Trying REDACTED_IP...
* TCP_NODELAY set
* Connected to REDACTED_HOST (REDACTED_IP) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.REDACTED_HOST
*  start date: Mar 27 00:00:00 2018 GMT
*  expire date: Apr  1 23:59:59 2020 GMT
*  subjectAltName: host "REDACTED_HOST" matched cert's "*.REDACTED_HOST"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
> GET /manifest.mpd HTTP/1.1
> Host: REDACTED_HOST
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Date: Fri, 06 Sep 2019 14:32:14 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Origin
< Access-Control-Allow-Credentials: true
< Content-Type: application/dash+xml
< 
<?xml version="1.0"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:DASH:schema:MPD:2011" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:cenc="urn:mpeg:cenc:2013" xmlns:mspr="urn:microsoft:playready" xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" type="static" mediaPresentationDuration="PT1H31M11.466S" minBufferTime="PT1.5S"><Period id="1567726124-90000" duration="PT1H31M11.466S"><AdaptationSet mimeType="video/mp4" maxWidth="1280" maxHeight="720" par="16:9" frameRate="30000/1001" lang="en" group="1" id="0"><ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="REDACTED"/><ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95" value="Microsoft PlayReady"><cenc:pssh>REDACTED_PSSH</cenc:pssh><mspr:pro>REDACTED_MSPRPRO</mspr:pro></ContentProtection><ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed" value="Widevine"><cenc:pssh>REDACTED_PSSH</cenc:pssh></ContentProtection><SegmentTemplate timescale="90000" initialization="dash/video/$Bandwidth$/init.m4s" media="dash/video/$Bandwidth$/$Number$.m4s" presentationTimeOffset="0" startNumber="1"><SegmentTimeline><S d="540540" r="161"/><S d="360360"/><S d="540540" r="332"/><S d="360360"/><S d="540540" r="331"/><S d="360360"/><S d="540540" r="81"/></SegmentTimeline></SegmentTemplate><Representation codecs="avc1.4d400d" id="p0va0br256000" bandwidth="256000" width="320" height="180"/><Representation codecs="avc1.4d401e" id="p0va0br1228800" bandwidth="1228800" width="640" height="360"/><Representation codecs="avc1.4d401f" id="p0va0br2048000" bandwidth="2048000" width="854" height="480"/><Representation codecs="avc1.4d401f" id="p0va0br3072000" bandwidth="3072000" width="1280" height="720"/></AdaptationSet><AdaptationSet mimeType="audio/mp4" lang="en" group="2" id="1"><AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/><ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="REDACTED"/><ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95" value="Microsoft PlayReady"><cenc:pssh>REDACTED_PSSH</cenc:pssh><mspr:pro>REDACTED_MSPRPRO</mspr:pro></ContentProtection><ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed" value="Widevine"><cenc:pssh>REDACTED_PSSH</cenc:pssh></ContentProtection><SegmentTemplate timescale="48000" initialization="dash/audio/$Bandwidth$/init.m4s" media="dash/audio/$Bandwidth$/$Number$.m4s" presentationTimeOffset="0" startNumber="1"><SegmentTimeline><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="192528"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="191472"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="191520"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768" r="1"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287760"/><S d="288768"/><S d="287712"/><S d="288768"/><S d="287760"/><S d="288768"/></SegmentTimeline></SegmentTemplate><Representation codecs="mp4a.40.2" id="p0aa0br65536" bandwidth="65536" audioSamplingRate="48000"/></AdaptationSet></Period><UTCTiming schemeIdUri="urn:mpeg:dash:utc:direct:2014" value="2019-09-06T14:31:44.785Z"/></MPD>

$ youtube-dl "https://REDACTED_HOST/manifest.mpd" --keep-fragments --all-formats --verbose 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://REDACTED_HOST/manifest.mpd', u'--keep-fragments', u'--all-formats', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.01
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-60-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: avconv 3.4.6, avprobe 3.4.6, ffmpeg 3.4.6, ffprobe 3.4.6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest: Downloading webpage
[generic] manifest: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2395, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

Thanks.

**Comment by remitamine** [comment]
you can modify [this line](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/common.py#L2048) to always return true.
