### ISSUE TITLE
Video Blocked by UMG

### ISSUE THREAD

**Issue by Aleksbgbg** [ytdl-org/youtube-dl#22329]
## Checklist
- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.09.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/user/UKFDubstep', u'-i', u'--get-id', u'--get-title', u'--get-duration', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.01
[debug] Python version 2.7.15+ (CPython) - Linux-5.0.0-27-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Writing cache to u'/home/aleksbgbg/.cache/youtube-dl/youtube-sigfuncs/js_vfl9X5OgR_105.json' failed: Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/cache.py", line 53, in store
    write_json_file(data, fn)
  File "./youtube-dl/youtube_dl/utils.py", line 1822, in write_json_file
    tf = tempfile.NamedTemporaryFile(**compat_kwargs(args))
  File "/usr/lib/python2.7/tempfile.py", line 475, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 13] Permission denied: '/home/aleksbgbg/.cache/youtube-dl/youtube-sigfuncs/js_vfl9X5OgR_105.json.GvA066.tmp'

WARNING: Writing cache to u'/home/aleksbgbg/.cache/youtube-dl/youtube-sigfuncs/js_vfl9X5OgR_101.json' failed: Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/cache.py", line 53, in store
    write_json_file(data, fn)
  File "./youtube-dl/youtube_dl/utils.py", line 1822, in write_json_file
    tf = tempfile.NamedTemporaryFile(**compat_kwargs(args))
  File "/usr/lib/python2.7/tempfile.py", line 475, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 13] Permission denied: '/home/aleksbgbg/.cache/youtube-dl/youtube-sigfuncs/js_vfl9X5OgR_101.json.wbnyuq.tmp'

# ... (video output)

ERROR: This video contains content from UMG, who has blocked it in your country on copyright grounds.
Sorry about that.
```

## Description
I just tried to list the [UKF Dubstep](https://www.youtube.com/user/UKFDubstep) channel.

I started youtube-dl with these parameters:
```
./youtube-dl https://www.youtube.com/user/UKFDubstep -i --get-id --get-title --get-duration
```

Several minutes into the listing, youtube-dl errored with the UMG block error, even though I explicitly passed `-i` to ignore errors (I've also tried passing the full-form `--ignore-errors`). I tried this 4 times and it happened every time.

As you can see from the log, permission to read or write files is disabled, however youtube-dl worked for listing other channels and playlists, such as [Monstercat: Uncaged](https://www.youtube.com/user/MonstercatMedia).

How can I skip the UMG blocked video, and just keep listing the available videos? It seems that the option for this is `-i`, however it's obviously not ignoring the errors.

**Comment by Aleksbgbg** [comment]
Nevermind, it seems this has something to do with the particular environment, as it seems to work on a different device. I'll investigate further and inform if I find a bug.
