### ISSUE TITLE
Discovery/HGTV

### ISSUE THREAD

**Issue by tv21** [ytdl-org/youtube-dl#22320]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--ap-mso', u'Charter_Direct', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'https://watch.hgtv.com/tv-shows/flip-or-flop/full-episodes/alarming-flip']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.01
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-161-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 4.1.3-static, ffprobe 4.1.3-static
[debug] Proxy map: {}
[Discovery] alarming-flip: Downloading token JSON metadata
[Discovery] alarming-flip: Downloading content JSON metadata
[Discovery] alarming-flip: Downloading streaming JSON metadata
ERROR: This video is only available via cable service provider subscription that is not currently supported. You may want to use --cookies.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/discovery.py", line 105, in _real_extract
    display_id, 'Downloading streaming JSON metadata', headers=headers)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 892, in _download_json
    expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 870, in _download_json_handle
    expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 660, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 645, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/discovery.py", line 115, in _real_extract
    ' is not currently supported. You may want to use --cookies.', expected=True)
ExtractorError: This video is only available via cable service provider subscription that is not currently supported. You may want to use --cookies.
```

## Description

WRITE DESCRIPTION HERE

The HGTV extractor has not worked properly for many months but until about three or four weeks ago it was possible to use --cookies and an extracted link if you could obtain it.  However they have made several changes to the site in the past month or so, and now whether you have a regular video link as shown above or a more direct link, and whether you try to use a cookies file or not, it fails with a 403: Forbidden error, sometimes after downloading a very small initial block (less than 1%). The video will play in a web browser.

**Comment by tv21** [comment]
What did I leave out that caused this to be marked as incomplete?

**Comment by remitamine** [comment]
the log does not show the problem you're explaining.

**Comment by tv21** [comment]
I was showing what currently happens when attempting to use youtube-dl with a HGTV video link.  I did use a valid cable provider subscription so I have no idea why that last line is printed, if that's what you are talking about.

**Comment by remitamine** [comment]
```
[debug] Command-line args: [u'-v', u'--ap-mso', u'Charter_Direct', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'https://watch.hgtv.com/tv-shows/flip-or-flop/full-episodes/alarming-flip']
ERROR: This video is only available via cable service provider subscription that is not currently supported. You may want to use --cookies.
```
the error message explicitly instruct you to supply cookies which you didn't do and instead you're using adobe pass options.

**Comment by remitamine** [comment]
and again you exlaing something and provide an unrelated log.

**Comment by tv21** [comment]
Well I was hoping that maybe there was a way to avoid using a cookies file because it makes things more complicated, however I just now tried that and this is the error output I am getting now:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--cookies', u'/home/user/cookies.txt', u'-v', u'https://watch.hgtv.com/tv-shows/flip-or-flop/full-episodes/alarming-flip']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.01
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-161-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 4.1.3-static, ffprobe 4.1.3-static
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2010, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/discovery.py", line 69, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2819, in _get_cookies
  File "/usr/lib/python2.7/Cookie.py", line 583, in __init__
    if input: self.load(input)
  File "/usr/lib/python2.7/Cookie.py", line 643, in load
    for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'

**Comment by remitamine** [comment]
this a known bug with python 2, and it has been reported before, I will lock this issue and you can open a new one once you have a log with the error you have explained.
