### ISSUE TITLE
Censored Facebook videos

### ISSUE THREAD

**Issue by daeron767** [ytdl-org/youtube-dl#22322]
- [x ] I'm reporting a site feature request
- [ x] I've verified that I'm running youtube-dl version **2019.09.01**
- [ x] I've searched the bugtracker for similar site feature requests including closed ones

Facebook videos that are censored with "This video may show graphic or violent content." for which you need to click a "Uncover video" graphic/button.

# When a valid name & password a response such as below is provided:

 % youtube-dl --username "NAME" --password "PASSWORD" "https://www.facebook.com/syafaat.muzakki/videos/2145011278957932/"
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[facebook] Downloading login page
[facebook] Logging in
WARNING: unable to log in: bad username/password, or exceeded login rate limit (~3/min). Check credentials or wait.
[facebook] 2145011278957932: Downloading webpage
[facebook] 2145011278957932: Downloading webpage
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.

# When adding the "--cookies" option I receive the follow:

andrew@certhas:~/Videos % youtube-dl --username "NAME" --password "PASSWORD" --cookies ~/.config/APPLICATION/profiles/default/Cookies "https://www.facebook.com/syafaat.muzakki/videos/2145011278957932/"
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 469, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 440, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 418, in __init__
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2318, in _setup_opener
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2748, in load
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8d in position 26: ordinal not in range(128)

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30681
