### ISSUE TITLE
[FRANCE.TV] Video playable but not downloadable

### ISSUE THREAD

**Issue by daumnet** [ytdl-org/youtube-dl#22344]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.09.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\video>youtube-dl --proxy 163.172.152.52:8811 --all-subs --convert-subs srt --retries 20000 -o "3881.mp4" -v https://www.france.tv/france-3/plus-belle-la-vie/plus-belle-la-vie-saison-15/1056867-plus-belle-la-vie.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--proxy', '163.172.152.52:8811', '--all-subs', '--convert-subs', 'srt', '--retries', '20000', '-o', '3881.mp4', '-v', 'https://www.france.tv/france-3/plus-belle-la-vie/plus-belle-la-vie-saison-15/1056867-plus-belle-la-vie.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.09.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-89508-g1f1207145a, ffprobe N-89508-g1f1207145a
[debug] Proxy map: {'https': '163.172.152.52:8811', 'http': '163.172.152.52:8811'}
[FranceTVSite] 1056867-plus-belle-la-vie: Downloading webpage
[FranceTV] 3b927485-1ab6-4550-a08a-28afc905db77: Downloading video JSON
[FranceTV] 3b927485-1ab6-4550-a08a-28afc905db77: Downloading geo restriction info
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\francetv.py", line 209, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\francetv.py", line 169, in _extract_video
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

This video is perfectly playable in my browser with a geo-VPN, however, when I try to download it I run into an error message "No video formats found":
https://www.france.tv/france-3/plus-belle-la-vie/plus-belle-la-vie-saison-15/1056867-plus-belle-la-vie.html

All the precedent episodes in the same series https://www.france.tv/france-3/plus-belle-la-vie/ (? -E3880) are downloadable except this newest one: E3881, see the link above.

(I've made sure I've downloaded the newest YTDL version (v2019.09.01) from http://youtube-dl.org/.)

Why?? 

Thank you,
Jacob

**Comment by daumnet** [comment]
Not sure why this happens, but the video suddenly becomes downloadable.

Closing this ticket for now.
