### ISSUE TITLE
Some bug with Instagram

### ISSUE THREAD

**Issue by marabu88** [ytdl-org/youtube-dl#22354]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe --verbose https://www.instagram.com/baby.animal_s/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.instagram.com/baby.animal_s/']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.09.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-89794-gc51301db14, rtmpdump 2.4
[debug] Proxy map: {}
[instagram:user] baby.animal_s: Downloading webpage
[download] Downloading playlist: baby.animal_s
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\YoutubeDL.py", line 2010, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\YoutubeDL.py", line 807, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\YoutubeDL.py", line 967, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\instagram.py", line 259, in _extract_graphql
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\instagram.py", line 389, in _query_vars_for
KeyError: 'ProfilePage'
```

## Description

The error occurs when trying to download video from any IG account. in the browser opens without problems.

**Comment by marabu88** [comment]
As I understand it, this is due to the fact that it is impossible to view the user's page if it does not log in.

But even if youtube-dl supports the ability to log in to Instagram, now the login can be immediately blocked for abuse. This is a common facebook practice. I hope there is some solution to this problem. I note that specific photos and videos are still available without the need for authorization.

**Comment by dstftw** [comment]
```
> py -3.4 .\youtube_dl\__main__.py https://www.instagram.com/baby.animal_s/
[instagram:user] baby.animal_s: Downloading webpage
[download] Downloading playlist: baby.animal_s
[instagram:user] baby.animal_s: Downloading JSON page 1
[instagram:user] baby.animal_s: Downloading JSON page 2
[instagram:user] baby.animal_s: Downloading JSON page 3
[instagram:user] baby.animal_s: Downloading JSON page 4
[instagram:user] baby.animal_s: Downloading JSON page 5
[instagram:user] baby.animal_s: Downloading JSON page 6
[instagram:user] baby.animal_s: Downloading JSON page 7
[instagram:user] baby.animal_s: Downloading JSON page 8
[instagram:user] baby.animal_s: Downloading JSON page 9
[instagram:user] baby.animal_s: Downloading JSON page 10
[instagram:user] baby.animal_s: Downloading JSON page 11
[instagram:user] baby.animal_s: Downloading JSON page 12
[instagram:user] baby.animal_s: Downloading JSON page 13
[instagram:user] baby.animal_s: Downloading JSON page 14
[instagram:user] baby.animal_s: Downloading JSON page 15
[instagram:user] baby.animal_s: Downloading JSON page 16
[instagram:user] baby.animal_s: Downloading JSON page 17
[instagram:user] baby.animal_s: Downloading JSON page 18
[instagram:user] baby.animal_s: Downloading JSON page 19
[instagram:user] baby.animal_s: Downloading JSON page 20
[instagram:user] baby.animal_s: Downloading JSON page 21
[instagram:user] baby.animal_s: Downloading JSON page 22
[instagram:user] baby.animal_s: Downloading JSON page 23
[instagram:user] baby.animal_s: Downloading JSON page 24
[instagram:user] baby.animal_s: Downloading JSON page 25
[instagram:user] baby.animal_s: Downloading JSON page 26
[instagram:user] baby.animal_s: Downloading JSON page 27
[instagram:user] baby.animal_s: Downloading JSON page 28
[instagram:user] baby.animal_s: Downloading JSON page 29
[instagram:user] baby.animal_s: Downloading JSON page 30
[instagram:user] baby.animal_s: Downloading JSON page 31
[instagram:user] baby.animal_s: Downloading JSON page 32
[instagram:user] baby.animal_s: Downloading JSON page 33
[instagram:user] baby.animal_s: Downloading JSON page 34
[instagram:user] baby.animal_s: Downloading JSON page 35
[instagram:user] baby.animal_s: Downloading JSON page 36
[instagram:user] baby.animal_s: Downloading JSON page 37
[instagram:user] baby.animal_s: Downloading JSON page 38
[instagram:user] baby.animal_s: Downloading JSON page 39
[instagram:user] baby.animal_s: Downloading JSON page 40
[instagram:user] baby.animal_s: Downloading JSON page 41
[instagram:user] baby.animal_s: Downloading JSON page 42
[instagram:user] baby.animal_s: Downloading JSON page 43
[instagram:user] baby.animal_s: Downloading JSON page 44
[instagram:user] baby.animal_s: Downloading JSON page 45
[instagram:user] baby.animal_s: Downloading JSON page 46
[instagram:user] baby.animal_s: Downloading JSON page 47
[instagram:user] baby.animal_s: Downloading JSON page 48
[instagram:user] baby.animal_s: Downloading JSON page 49
[instagram:user] baby.animal_s: Downloading JSON page 50
[instagram:user] baby.animal_s: Downloading JSON page 51
[instagram:user] baby.animal_s: Downloading JSON page 52
[instagram:user] baby.animal_s: Downloading JSON page 53
[instagram:user] baby.animal_s: Downloading JSON page 54
[instagram:user] baby.animal_s: Downloading JSON page 55
[instagram:user] baby.animal_s: Downloading JSON page 56
[instagram:user] playlist baby.animal_s: Downloading 97 videos
[download] Downloading video 1 of 97
[Instagram] B1F6zi4hAKA: Downloading webpage
[download] Destination: Video by baby.animal_s-B1F6zi4hAKA.mp4
[download] 100% of 1.08MiB in 00:01
[download] Downloading video 2 of 97
[Instagram] B01DB7ohf38: Downloading webpage
[download] Destination: Video by baby.animal_s-B01DB7ohf38.mp4
[download]  78.7% of 324.20KiB at 464.17KiB/s ETA 00:00
ERROR: Interrupted by user
```
Post the output with `--dump-pages`.
