### ISSUE TITLE
please add support for quint.com 

### ISSUE THREAD

**Issue by shirishag75** [ytdl-org/youtube-dl#22360]
Dear Developers please add support for quint.com 

```
$ youtube-dl --version
2019.09.01
```

```
$ youtube-dl -c -F --verbose "https://www.thequint.com/news/india/non-approved-company-private-engineers-checked-evm-in-elections"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-c', '-F', '--verbose', 'https://www.thequint.com/news/india/non-approved-company-private-engineers-checked-evm-in-elections']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.01
[debug] Python version 3.7.4+ (CPython) - Linux-5.2.0-2-amd64-x86_64-with-debian-bullseye-sid
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] non-approved-company-private-engineers-checked-evm-in-elections: Requesting header
WARNING: Falling back on generic information extractor.
[generic] non-approved-company-private-engineers-checked-evm-in-elections: Downloading webpage
[generic] non-approved-company-private-engineers-checked-evm-in-elections: Extracting information
ERROR: Unsupported URL: https://www.thequint.com/news/india/non-approved-company-private-engineers-checked-evm-in-elections
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/generic.py", line 3355, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.thequint.com/news/india/non-approved-company-private-engineers-checked-evm-in-elections
```

**Comment by shirishag75** [comment]
@remitamine could you look into this and see if something can be done. I am using the latest released version.

**Comment by remitamine** [comment]
it's Dailymotion embed:
https://www.dailymotion.com/embed/video/x7l0ng6

**Comment by shirishag75** [comment]
@remitamine Seems dailymotion does not work. For e.g. - 

```
$ youtube-dl --verbose -F "https://www.dailymotion.com/embed/video/x7gpkpl"
[debug] System config: []
[debug] User config: [u'-f', u'bestvideo[height<=720]+bestaudio/best[height<=720]']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-F', u'https://www.dailymotion.com/embed/video/x7gpkpl']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-2-amd64-x86_64-with-debian-bullseye-sid
[debug] exe versions: ffmpeg 4.2.1-2, ffprobe 4.2.1-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 235, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 50, in _call_api
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 31, in _get_dailymotion_cookies
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2831, in _get_cookies
  File "/usr/lib/python2.7/Cookie.py", line 583, in __init__
    if input: self.load(input)
  File "/usr/lib/python2.7/Cookie.py", line 643, in load
    for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'
```
