### ISSUE TITLE
ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map

### ISSUE THREAD

**Issue by manyoyo-co** [ytdl-org/youtube-dl#22375]
## Checklist

I think I've checked everything. Sorry if I've missed something obvious.

## Verbose log

```
youtube-dl -i -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 --add-metadata --write-sub https://www.youtube.com/watch?v=s6txpumkY5I --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-i', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio', '--merge-output-format', 'mp4', '--add-metadata', '--write-sub', 'https://www.youtube.com/watch?v=s6txpumkY5I', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 3.7.3 (CPython) - Linux-4.19.66-v7l+-armv7l-with-debian-10.1
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1
[debug] Proxy map: {}
[youtube] s6txpumkY5I: Downloading webpage
[youtube] s6txpumkY5I: Downloading video info webpage
ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/pi/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/pi/.local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 2109, in _real_extract
    raise ExtractorError('no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info')
youtube_dl.utils.ExtractorError: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

I got this message this evening. I was able to download a different video today, but not this one.

**Comment by manyoyo-co** [comment]
When I upgrade with pip I see this:

`Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already up-to-date: youtube_dl in /usr/local/lib/python2.7/dist-packages (2019.9.12.1)
`

Any reason why I'm not seeing the right version in the output?

**Comment by dstftw** [comment]
Most likely you have multiple versions installed.

**Comment by manyoyo-co** [comment]
I upgraded with pip, then pip3, then apt-get... Is there an easy way of purging it and then reinstalling?

**Comment by manyoyo-co** [comment]
Thank you, @dstftw -- I got it working again.
