### ISSUE TITLE
Unable to download a specific SoundCloud song: HTTP 401

### ISSUE THREAD

**Issue by sonothingatall** [ytdl-org/youtube-dl#22387]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://soundcloud.com/epicmountain/trust-kurzgesagt', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18975
[debug] exe versions: ffmpeg N-94391-g052d41377a, ffprobe N-94391-g052d41377a
[debug] Proxy map: {}
[soundcloud] epicmountain/trust-kurzgesagt: Downloading webpage
[soundcloud] epicmountain/trust-kurzgesagt: Downloading info JSON
[soundcloud] 583436445: Downloading track url
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
[soundcloud] 583436445: Checking fallback video format URL
[soundcloud] 583436445: fallback video format URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\extractor\soundcloud.py", line 449, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\extractor\soundcloud.py", line 388, in _extract_info_dict
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Looks like #6930...
https://soundcloud.com/epicmountain/the-egg works but https://soundcloud.com/epicmountain/trust-kurzgesagt doesn't work

**Comment by sp00p** [comment]
Make sure you're logged into Soundcloud before downloading. You only get a 401 Error when you haven't logged into the specific webpage with a valid username and password.
