### ISSUE TITLE
Unsupported URL: https://player.twitch.tv/...

### ISSUE THREAD

**Issue by Keith94** [ytdl-org/youtube-dl#22395]
## Checklist

- [ x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

C:\Program Files\mpv>youtube-dl -v https://player.twitch.tv/?video=480452374
[debug] System config: []
[debug] User config: ['--add-metadata', '--audio-format', 'best', '--embed-thumbnail', '--extract-audio', '--output', '/songs/%(title)s.%(ext)s', '--ignore-errors']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://player.twitch.tv/?video=480452374']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[generic] ?video=480452374: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?video=480452374: Downloading webpage
[generic] ?video=480452374: Extracting information
ERROR: Unsupported URL: https://player.twitch.tv/?video=480452374
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\extractor\generic.py", line 3355, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://player.twitch.tv/?video=480452374

## Description

1. Open https://player.twitch.tv/?video=480452374 in mpv with youtube-dl installed
2. mpv window exits unexpectedly

**Comment by TheSnoozer** [comment]
try
```
youtube-dl https://www.twitch.tv/videos/480452374
```
instead

**Comment by Keith94** [comment]
Yes, but I posted this in hopes that player.twitch.tv can be supported as well.
