### ISSUE TITLE
SonyLIV brightcove ERROR No video formats found

### ISSUE THREAD

**Issue by techprice** [ytdl-org/youtube-dl#22400]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--ignore-errors', '--geo-bypass', '--continue', '-f', 'best', '-o', '%(title)s.%(ext)s', 'https://www.sonyliv.com/details/episodes/5677622640001/Episode-206---Taarak-Mehta-Ka-Oolta-Chashmah---London-Trip-Canceled']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 3.4.3 (CPython) - Linux-3.13.0-95-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg N-94130-g2edb262, ffprobe N-94130-g2edb262, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 117.218.100.57 (IN) as X-Forwarded-For.
[brightcove:new] ref:5677622640001: Downloading webpage
[brightcove:new] ref:5677622640001: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/brightcove.py", line 797, in _real_extract
    json_data, video_id, headers=headers)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/brightcove.py", line 695, in _parse_brightcove_metadata
    self._sort_formats(formats)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found;
```

## Description

Unable to download some videos from SonyLIV. Here's the list of other URLs which are giving same error:
* https://www.sonyliv.com/details/episodes/5677835843001/Episode-231---Taarak-Mehta-Ka-Oolta-Chashmah---Jethalal's-Intervention
* https://www.sonyliv.com/details/episodes/5677837984001/Episode-232---Taarak-Mehta-Ka-Oolta-Chashmah---Jethalal-Is-Angry-
* https://www.sonyliv.com/details/episodes/5677849240001/Episode-233---Taarak-Mehta-Ka-Oolta-Chashmah---Goli-Sees-Jethalal-Getting-A-Haircut

**Comment by krishnabalajee** [comment]
I'm having the same issue. Is there any reason why this bug is in closed state without a comment? I can provide login details if that's the issue.

Below is the verbose log:
```
D:\Youtube-DL>youtube-dl -f best --all-subs --add-metadata -o "G:\TheHandMaidsTale\%(title)s.%(ext)s" -i --cookies ".\sonyliv_cookies.txt" "https://www.sonyliv.com/details/episodes/5824679084001/Ep.-1---Offred" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', '--add-metadata', '-o', 'G:\\TheHandMaidsTale\\%(title)s.%(ext)s', '-i', '--cookies', '.\\sonyliv_cookies.txt', 'https://www.sonyliv.com/details/episodes/5824679084001/Ep.-1---Offred', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-05-27-8b5ffae, ffprobe git-2020-05-27-8b5ffae
[debug] Proxy map: {}
[debug] Using fake IP 117.252.133.100 (IN) as X-Forwarded-For.
[brightcove:new] ref:5824679084001: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\brightcove.py", line 677, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\brightcove.py", line 551, in _parse_brightcove_metadata
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 1350, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by theincognito-inc** [comment]
@krishnabalajee Youtube-dl doesn't support DRM content downloading. Some videos in SonyLIV are DRM enabled, some aren't. The link you posted above and the OP's links consist of DRM videos. That's why the issue was closed.
