### ISSUE TITLE
Downloading as an mp4 with audio works but gives an error

### ISSUE THREAD

**Issue by RandomTomato** [ytdl-org/youtube-dl#22411]
**Checklist**
- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

**Verbose**
```
Unsure of how to paste the verbose link as I am using python
```

**Description**
Hey! so I was trying to get youtubedl to download an mp4 file with audio merged and I ran the code and the file is playable with video and audio, but in the console an error is sent and for the life of me i cannot figure out what is causing it. Some help would be much appreciated.

**My Code:**
```
ydl_options_mp4_merge = {
    'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4',
    'outtmpl': '%(title)s-%(id)s.%(ext)s',
    'ffmpeg_location': "ffmpeg/bin/ffmpeg.exe",
    'postprocessors': [{
        'key': 'FFmpegMerger',
    }]
}

with youtube_dl.YoutubeDL(ydl_options_mp4_merge) as ydl:
      ydl.download([link])
```
**Error:**
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\RandomTomato\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\RandomTomato\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "e:/Start Menu Folders/Coding/Youtube downloader/youtube-downloader.pyw", line 61, in download
    ydl.download([link])
  File "C:\Users\RandomTomato\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2010, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "C:\Users\RandomTomato\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\RandomTomato\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 861, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\RandomTomato\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1642, in process_video_result
    self.process_info(new_info)
  File "C:\Users\RandomTomato\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1991, in process_info
    self.post_process(filename, info_dict)
  File "C:\Users\RandomTomato\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2056, in post_process
    files_to_delete, info = pp.run(info)
  File "C:\Users\RandomTomato\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "C:\Users\RandomTomato\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 210, in run_ffmpeg_multiple_files
    os.stat(encodeFilename(path)).st_mtime for path in input_paths)
  File "C:\Users\RandomTomato\AppData\Local\Programs\Python\Python37-32\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 210, in <genexpr>
    os.stat(encodeFilename(path)).st_mtime for path in input_paths)
FileNotFoundError: [WinError 2] The system cannot find the file specified: "Vance Joy - 'Riptide' Official Video-uJ_1HMAGb4k.f137.mp4"
```

**Comment by dstftw** [comment]
You must not use `FFmpegMerger` on your own.
