### ISSUE TITLE
Pluralsight.com - Unable to log in

### ISSUE THREAD

**Issue by KarlG1965** [ytdl-org/youtube-dl#22424]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-o%(playlist_index)s - %(title)s.%(ext)s', '-v', '--min-sleep-interval', '40', '--max-sleep-interval', '70', '--limit-rate', '350K', '--playlist-start', '1', 'https://www.pluralsight.com/courses/xxxxxxxxxxxxxx']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 3.6.8 (CPython) - Linux-5.2.14-050214-generic-x86_64-with-LinuxMint-19.1-tessa
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2, phantomjs 5
[debug] Proxy map: {}
[pluralsight:course] xxx: Downloading JSON metadata
[download] Downloading playlist: xxx
[pluralsight:course] playlist xxx Collected 64 video ids (downloading 64 of them)
[download] Downloading video 1 of 64
[pluralsight] Downloading login page
[pluralsight] Logging in
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 529, in extract
    self.initialize()
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 433, in initialize
    self._real_initialize()
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/pluralsight.py", line 165, in _real_initialize
    self._login()
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/pluralsight.py", line 215, in _login
    raise ExtractorError('Unable to log in')
youtube_dl.utils.ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by KarlG1965** [comment]
Apolgies, for some reason I used the wrong template. I'll close this issue and raise a new one with the proper template
