### ISSUE TITLE
Fix Globo extractor

### ISSUE THREAD

**Issue by DESKTOP-RX90B689** [ytdl-org/youtube-dl#22438]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'cookies.txt', '-v', '-F', 'https://globoplay.globo.com/v/7928258/programa/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 3.6.3 (CPython) - Linux-4.15.0-30deepin-generic-x86_64-with-debian-9.0
[debug] exe versions: avconv 3.2.12-1, avprobe 3.2.12-1, ffmpeg 3.2.12-1, ffprobe 3.2.12-1, rtmpdump 2.4
[debug] Proxy map: {}
[Globo] 7928258: Downloading JSON metadata
[Globo] 7928258: Downloading security hash for 7928258_manifest_360_1080_m3u8
[Globo] 7928258_manifest_360_1080_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 7928258: Downloading security hash for 7928258_manifest_360_1080_l_m3u8
[Globo] 7928258_manifest_360_1080_l_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 7928258: Downloading security hash for 7928258_manifest_90_720_m3u8
[Globo] 7928258_manifest_90_720_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 7928258: Downloading security hash for 7928258_manifest_240_720_m3u8
[Globo] 7928258_manifest_240_720_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 7928258: Downloading security hash for 7928258_manifest_90_720_l_m3u8
ERROR: Globo returned error: User has exceeded the simultaneous access limit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/globo.py", line 122, in _real_extract
    '%s returned error: %s' % (self.IE_NAME, message), expected=True)
youtube_dl.utils.ExtractorError: Globo returned error: User has exceeded the simultaneous access limit.

```

## Description

This error is now happening to all content using this globe extractor. I checked my account access and only my browser and youtube-dl are logged in. So, I wish you could help us solve this problem.

**Comment by lucasmcoelho** [comment]
@dstftw 
Could you please show the issue that was duplicated?
