### ISSUE TITLE
FX Shows have a new url that are falling back to a generic parsing and failing

### ISSUE THREAD

**Issue by cyperous** [ytdl-org/youtube-dl#22467]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[debug] System config: []
[debug] User config: ['-f', 'bestvideo[ext=webm]+bestaudio/best', '--postprocessor-args=-strict unofficial', '--merge-output-format', 'mkv']
[debug] Custom config: []
[debug] Command-line args: ['https://fxnow.fxnetworks.com/shows/american-horror-story/episode-guide/season-09/episode-01-camp-redwood/vdka12829318', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 3.7.4 (CPython) - Darwin-19.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: https://fxnow.fxnetworks.com/shows/american-horror-story/episode-guide/season-09/episode-01-camp-redwood/vdka12829318
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3355, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://fxnow.fxnetworks.com/shows/american-horror-story/episode-guide/season-09/episode-01-camp-redwood/vdka12829318

## Description

WRITE DESCRIPTION HERE

FX Shows with a new url are falling back to generic parsing and then failing.

**Comment by cyperous** [comment]
Still an issue on version 2019.09.28

[debug] System config: []
[debug] User config: ['-f', 'bestvideo[ext=webm]+bestaudio/best', '--postprocessor-args=-strict unofficial', '--merge-output-format', 'mkv']
[debug] Custom config: []
[debug] Command-line args: ['https://fxnow.fxnetworks.com/shows/american-horror-story/episode-guide/season-09/episode-01-camp-redwood/vdka12829318', '-F', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.7.4 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] vdka12829318: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vdka12829318: Downloading webpage
[generic] vdka12829318: Extracting information
ERROR: Unsupported URL: https://fxnow.fxnetworks.com/shows/american-horror-story/episode-guide/season-09/episode-01-camp-redwood/vdka12829318
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3355, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://fxnow.fxnetworks.com/shows/american-horror-story/episode-guide/season-09/episode-01-camp-redwood/vdka12829318
