### ISSUE TITLE
[rai] not every link works

### ISSUE THREAD

**Issue by mattia-b89** [ytdl-org/youtube-dl#22484]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.raiplay.it/video/2019/09/missione-compiuta-stop-bacioni-matt-helm-c08a21f8-93ad-4a32-a9e9-4ee25a6c98ce.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 3.7.4 (CPython) - Linux-5.2.13-1-ck-x86_64-with-arch
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[RaiPlay] c08a21f8-93ad-4a32-a9e9-4ee25a6c98ce: Downloading video JSON
WARNING: "url" field is missing or empty - skipping format, there is an error in extractor
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 11, in <module>
    load_entry_point('youtube-dl==2019.9.12.1', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.7/site-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/usr/lib/python3.7/site-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2010, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 861, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1587, in process_video_result
    if formats[0] is not info_dict:
IndexError: list index out of range
```

## Description

Not every RAI links work; e.g.:
- not working, https://www.raiplay.it/video/2019/09/missione-compiuta-stop-bacioni-matt-helm-c08a21f8-93ad-4a32-a9e9-4ee25a6c98ce.html
- working, https://www.raiplay.it/video/2019/09/Model-shop---Lamante-perduta-2615b38e-e163-44bc-bf8b-5bc878325e1a.html

NB: both are playable from browser; only the second works in ytdl

**Comment by remitamine** [comment]
No longer accessible.
