### ISSUE TITLE
NRLTV Not able to extract video data

### ISSUE THREAD

**Issue by spicerackk** [ytdl-org/youtube-dl#22494]
C:\Tools\Youtube-DL>youtube-dl.exe -v https://www.nrl.com/tv/matches/telstra-premiership/2019/round-1/full-match-replay-panthers-v-eels---round-1-2019/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.nrl.com/tv/matches/telstra-premiership/2019/round-1/full-match-replay-panthers-v-eels---round-1-2019/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 2.7.16 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[NRLTV] full-match-replay-panthers-v-eels---round-1-2019: Downloading webpage
ERROR: Unable to extract player data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\nrl.py", line 27, in _real_extract
    r"(?s)q-data='({.+?})'", webpage, 'player data'), display_id)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract player data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

What the problem is: unable to download from NRL TV
How it could be fixed: could possibly be a different URL than what is configured for youtube-dl

**Comment by remitamine** [comment]
you have to provide a valid(after logging to you're account in the browser) cookie file.
```
youtube-dl --cookies ~/Downloads/cookies.txt https://www.nrl.com/tv/matches/telstra-premiership/2019/round-1/full-match-replay-panthers-v-eels---round-1-2019/
[NRLTV] full-match-replay-panthers-v-eels---round-1-2019: Downloading webpage
[Ooyala] 8ybmVnaDE6RilCpbkjWQGNXCqW1k_jUv: Downloading JSON metadata
[Ooyala] 8ybmVnaDE6RilCpbkjWQGNXCqW1k_jUv: Downloading JSON metadata
[Ooyala] 8ybmVnaDE6RilCpbkjWQGNXCqW1k_jUv: Downloading m3u8 information
[download] Destination: Full Match Replay - Panthers v Eels - Round 1, 2019-8ybmVnaDE6RilCpbkjWQGNXCqW1k_jUv.fhls-1884.mp4
ffmpeg version n4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[hls @ 0x563ee4917080] Skip ('#EXT-X-VERSION:4')
[hls @ 0x563ee4917080] Skip ('#EXT-X-PROGRAM-DATE-TIME:1970-01-01T00:00:00Z')
[hls @ 0x563ee4917080] Opening 'https://ooauseast.keydelivery.australiasoutheast.media.azure.net/?KID=b3c17f33-5e7c-4f11-afd3-e34311b95573&token=urn%253Amicrosoft%253Aazure%253Amediaservices%253Acontentkeyidentifier%3Db3c17f33-5e7c-4f11-afd3-e34311b95573%26Audience%3Dpcode%253A%257BBjZ2oyOsA0g9SvHHgrgYMEu0p1j1%257D%26Issuer%3Dhttp%253A%252F%252Fooyala%26ExpiresOn%3D1569342957%26HMACSHA256%3DjcCmFQkVoMBV63jyixRgwWregmS6rXpIofEDbx7TX9k%253D' for reading
[hls @ 0x563ee4917080] Opening 'crypto+https://vcdn2.nrl.com/f82815c7-0ecc-4350-bb41-1f8f9ece49c0/8ybmVnaDE6RilCpbkjWQGNXCqW1k_jUv.ism/QualityLevels%281796000%29/Fragments%28video=0,format=m3u8-aapl%29?hdnea=st%3D1569321361~exp%3D1569342961~acl%3D%2Ff82815c7-0ecc-4350-bb41-1f8f9ece49c0%2F8ybmVnaDE6RilCpbkjWQGNXCqW1k_jUv.ism%2F%2A~hmac%3D92e58c8678a5a5be69226b275426a6f6adfd1879f8dd11360885268224333291' for reading
Input #0, hls, from 'http://player.ooyala.com/hls/proxy/8ybmVnaDE6RilCpbkjWQGNXCqW1k_jUv/media/Manifest(video,format=m3u8-aapl)?source=https%3A%2F%2Fvcdn2.nrl.com%2Ff82815c7-0ecc-4350-bb41-1f8f9ece49c0%2F8ybmVnaDE6RilCpbkjWQGNXCqW1k_jUv.ism%2FQualityLevels%25281796000%2529%2FManifest%2528video%2Cformat%3Dm3u8-aapl%2529%3Fhdnea%3Dst%253D1569321358~exp%253D1569342958~acl%253D%252Ff82815c7-0ecc-4350-bb41-1f8f9ece49c0%252F8ybmVnaDE6RilCpbkjWQGNXCqW1k_jUv.ism%252F%252A~hmac%253Dd1c8987ed444e2c3bcd6ae09f175c43c9fc40217e352469ddca6dc841310ec91&token=token%3Durn%25253Amicrosoft%25253Aazure%25253Amediaservices%25253Acontentkeyidentifier%253Db3c17f33-5e7c-4f11-afd3-e34311b95573%2526Audience%253Dpcode%25253A%25257BBjZ2oyOsA0g9SvHHgrgYMEu0p1j1%25257D%2526Issuer%253Dhttp%25253A%25252F%25252Fooyala%2526ExpiresOn%253D1569342957%2526HMACSHA256%253DjcCmFQkVoMBV63jyixRgwWregmS6rXpIofEDbx7TX9k%25253D':
  Duration: 01:42:23.32, start: 0.080000, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Full Match Replay - Panthers v Eels - Round 1, 2019-8ybmVnaDE6RilCpbkjWQGNXCqW1k_jUv.fhls-1884.mp4.part':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
[hls @ 0x563ee4917080] Opening 'crypto+https://vcdn2.nrl.com/f82815c7-0ecc-4350-bb41-1f8f9ece49c0/8ybmVnaDE6RilCpbkjWQGNXCqW1k_jUv.ism/QualityLevels%281796000%29/Fragments%28video=60000000,format=m3u8-aapl%29?hdnea=st%3D1569321361~exp%3D1569342961~acl%3D%2Ff82815c7-0ecc-4350-bb41-1f8f9ece49c0%2F8ybmVnaDE6RilCpbkjWQGNXCqW1k_jUv.ism%2F%2A~hmac%3D92e58c8678a5a5be69226b275426a6f6adfd1879f8dd11360885268224333291' for reading
frame=  150 fps= 46 q=-1.0 size=    1280kB time=00:00:05.88 bitrate=1783.4kbits
```
