### ISSUE TITLE
Failed to Get Video info from vk using youtube-dl with Unable to extract player params Error 

### ISSUE THREAD

**Issue by Mohamed-Hossam** [ytdl-org/youtube-dl#22509]
Youtube-dl version : 2019.09.12.1
Command : youtube-dl https://vk.com/video-143221468_456240738 -u USERNAME -p PASSWORD --print-json --skip-download --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vk.com/video-143221468_456240738', '-u', 'PRIVATE', '-p', 'PRIVATE', '--print-json', '--skip-download', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91434-gcced03dd66, ffprobe N-91434-gcced03dd66
[debug] Proxy map: {}
ERROR: Unable to extract player params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\extractor\vk.py", line 406, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract player params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by eust102** [comment]
I'm having the issue.

**Comment by mixaxdd** [comment]
**Same issue**
youtube-dl -U
youtube-dl is up-to-date (2019.09.12.1)

youtube-dl -f best https://vk.com/video-101982925_456247710  print-json --skip-download --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'best', u'https://vk.com/video-101982925_456247710', u'print-json', u'--skip-download', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-6-amd64-x86_64-with-debian-10.1
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1
[debug] Proxy map: {}
[vk] -101982925_456247710: Downloading webpage
ERROR: Unable to extract player params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vk.py", line 406, in _real_extract
    'player params'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

**Comment by eust102** [comment]
Ok here was my solution. You have to update the youtube_dl. However when you do it you have to do it in the "Script" folder. So you have to go your command prompt. Then navigate to the "Script" folder. Uninstall the old youtube_dl by using the "pip uninstall youtube_dl" then install it by using the "pip install youtube_dl" Also put a copy of youtube_dl in the "Lib" folder.
