### ISSUE TITLE
Facebook live videos

### ISSUE THREAD

**Issue by seisdr** [ytdl-org/youtube-dl#22526]
## Checklist

- [ ] I'm reporting a feature request
- [ ] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [ ] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
It would be epic if I can download Facebook live videos thanks

**Comment by seisdr** [comment]
Also I can't install video from vk I tried that
https://vk.com/video-102087446_456264980
```
$ youtube-dl "https://vk.com/video-102087446_456264338"
[vk] -102087446_456264338: Downloading webpage
ERROR: Unable to extract player params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
$ youtube-dl -v "https://vk.com/video-102087446_456264338"      [debug] System config: []                                       [debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vk.com/video-102087446_456264338']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 3.7.4 (CPython) - Linux-3.10.86-g0c14827-aarch64-with-libc
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2
[debug] Proxy map: {}
[vk] -102087446_456264338: Downloading webpage
ERROR: Unable to extract player params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/youtube_dl/extractor/vk.py", line 406, in _real_extract
    'player params'),
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract player params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$
```
