### ISSUE TITLE
unable to extract player params ( VK.com, вконтакте)

### ISSUE THREAD

**Issue by LandisTwo** [ytdl-org/youtube-dl#22522]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
landis@linux-e6510:~/Downloads/batch>youtube-dl -vf 'best' --username 'landis.xxxx@xxxxxx.ru' --password xxxxxxxx          https://vk.com/video-181548123_456239030
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vf', u'best', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://vk.com/video-181548123_456239030']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 2.7.12 (CPython) - Linux-3.16.7-53-default-x86_64-with-SuSE-13.2-x86_64
[debug] exe versions: ffmpeg 3.0.5, ffprobe 3.0.5
[debug] Proxy map: {}
[vk] Downloading login page
[vk] Logging in
[vk] -181548123_456239030: Downloading webpage
ERROR: Unable to extract player params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/vk.py", line 406, in _real_extract
    'player params'),
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract player params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

landis@linux-e6510:~/Downloads/batch>
```

## Description

In the last 3 days (2019.09.25 ~ 27) i'm getting above error,
it started with one small music video, became more videos, now it seems all videos at VK.com

**Comment by elsancho74** [comment]
I stumbled upon the same problem the last days. My output looks the same.
