### ISSUE TITLE
youtube-dl not working

### ISSUE THREAD

**Issue by wankio** [ytdl-org/youtube-dl#22546]
last time i'm use it, it still working but i dont know why it have error now.

```
C:\Users\GEN32UC>youtube-dl
Traceback (most recent call last):
  File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python37\Scripts\youtube-dl.exe\__main__.py", line 9, in <module>
  File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\__init__.py", line 474, in main
    _real_main(argv)
  File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\__init__.py", line 441, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 418, in __init__
    self._setup_opener()
  File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 2328, in _setup_opener
    self.cookiejar.load(ignore_discard=True, ignore_expires=True)
  File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\utils.py", line 2748, in load
    for line in f:
  File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 532: character maps to <undefined>
```

**Comment by dstftw** [comment]
Most likely you are using custom unofficial youtube-dl.exe build.

**Comment by wankio** [comment]
> 
> 
> Most likely you are using custom unofficial youtube-dl.exe build.

but i'm using youtube-dl with pip
