### ISSUE TITLE
[Viewlift] Hochoi.tv Broken

### ISSUE THREAD

**Issue by sumit-1988** [ytdl-org/youtube-dl#22545]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\XXXXX\Downloads\ydl>youtube-dl -v https://www.hoichoi.tv/films/title/rosogolla
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.hoichoi.tv/films/title/rosogolla']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.04.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-93090-g7cab5471b2, ffprobe N-93090-g7cab5471b2
[debug] Proxy map: {}
[ViewLift] rosogolla: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('videoAssets',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\extractor\viewlift.py", line 184, in _real_extract
KeyError: 'videoAssets'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\extractor\viewlift.py", line 184, in _real_extract
KeyError: 'videoAssets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp48z7ci11\build\youtube_dl\extractor\common.py", line 542, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('videoAssets',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

**Comment by dstftw** [comment]
You must pass authenticated cookies.

**Comment by jag007-king** [comment]
What I have to do. It's shows error when I tried to download from hoichoi.
