### ISSUE TITLE
Facebook video download filename too long when using strange characters in title.

### ISSUE THREAD

**Issue by blieb** [ytdl-org/youtube-dl#22558]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.facebook.com/StreetJumpHaarlem/videos/899095860469861/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.5 (CPython) - Linux-4.9.127-32.el7.x86_64-x86_64-with-centos-7.5.1804-Core
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[facebook] 899095860469861: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://video-amt2-1.xx.fbcdn.net/v/t42.1790-2/10000000_1808553285954851_475925888710475776_n.mp4?_nc_cat=103&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjRfaHE1X2ZyYWdfMl92aWRlbyJ9&_nc_oc=AQmjLrcGQ-hKYWP0CTFRxagmQ3mPWqkgm1uwr6Dbm8-cu4SJCOkPrfhwUWVpkVn_83I54qENCW4i1F-PSWXx0DR0&_nc_ht=video-amt2-1.xx&oh=08458d08394762a7b5cf044aae506c5c&oe=5D924596'
ERROR: unable to open for writing: [Errno 36] File name too long: '\xf0\x9d\x90\x92\xf0\x9d\x90\xa9\xf0\x9d\x90\x9a\xf0\x9d\x90\x9a\xf0\x9d\x90\xab \xf0\x9d\x90\xaf\xf0\x9d\x90\xa8\xf0\x9d\x90\xa8\xf0\x9d\x90\xab \xf0\x9d\x90\x9e\xf0\x9d\x90\x9e\xf0\x9d\x90\xa7 \xf0\x9d\x9f\x90\xf0\x9d\x90\x9e \xf0\x9d\x90\xa4\xf0\x9d\x90\x9a\xf0\x9d\x90\x9a\xf0\x9d\x90\xab\xf0\x9d\x90\xad\xf0\x9d\x90\xa3\xf0\x9d\x90\x9e \xf0\x9d\x90\xa0\xf0\x9d\x90\xab\xf0\x9d\x90\x9a\xf0\x9d\x90\xad\xf0\x9d\x90\xa2\xf0\x9d\x90\xac \xf0\x9d\x90\xa3\xf0\x9d\x90\xae\xf0\x9d\x90\xa6\xf0\x9d\x90\xa9\xf0\x9d\x90\x9e\xf0\x9d\x90\xa7 \xf0\x9d\x90\x9b\xf0\x9d\x90\xa2\xf0\x9d\x90\xa3 \xf0\x9d\x90\x80\xf0\x9d\x90\xa5\xf0\x9d\x90\x9b\xf0\x9d\x90\x9e\xf0\x9d\x90\xab\xf0\x9d\x90\xad \xf0\x9d\x90\x87\xf0\x9d\x90\x9e\xf0\x9d\x90\xa2\xf0\x9d\x90\xa3\xf0\x9d\x90\xa7 \xf0\x9d\x90\x95\xf0\x9d\x90\xa8\xf0\x9d\x90\xac!\xf0\x9f\x92\xa5\xf0\x9f\x92\xa5 Vanaf aanstaa...-899095860469861.f1808553269288186v.mp4.part'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 250, in download
    ctx.tmpfilename, ctx.open_mode)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2042, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
IOError: [Errno 36] File name too long: '\xf0\x9d\x90\x92\xf0\x9d\x90\xa9\xf0\x9d\x90\x9a\xf0\x9d\x90\x9a\xf0\x9d\x90\xab \xf0\x9d\x90\xaf\xf0\x9d\x90\xa8\xf0\x9d\x90\xa8\xf0\x9d\x90\xab \xf0\x9d\x90\x9e\xf0\x9d\x90\x9e\xf0\x9d\x90\xa7 \xf0\x9d\x9f\x90\xf0\x9d\x90\x9e \xf0\x9d\x90\xa4\xf0\x9d\x90\x9a\xf0\x9d\x90\x9a\xf0\x9d\x90\xab\xf0\x9d\x90\xad\xf0\x9d\x90\xa3\xf0\x9d\x90\x9e \xf0\x9d\x90\xa0\xf0\x9d\x90\xab\xf0\x9d\x90\x9a\xf0\x9d\x90\xad\xf0\x9d\x90\xa2\xf0\x9d\x90\xac \xf0\x9d\x90\xa3\xf0\x9d\x90\xae\xf0\x9d\x90\xa6\xf0\x9d\x90\xa9\xf0\x9d\x90\x9e\xf0\x9d\x90\xa7 \xf0\x9d\x90\x9b\xf0\x9d\x90\xa2\xf0\x9d\x90\xa3 \xf0\x9d\x90\x80\xf0\x9d\x90\xa5\xf0\x9d\x90\x9b\xf0\x9d\x90\x9e\xf0\x9d\x90\xab\xf0\x9d\x90\xad \xf0\x9d\x90\x87\xf0\x9d\x90\x9e\xf0\x9d\x90\xa2\xf0\x9d\x90\xa3\xf0\x9d\x90\xa7 \xf0\x9d\x90\x95\xf0\x9d\x90\xa8\xf0\x9d\x90\xac!\xf0\x9f\x92\xa5\xf0\x9f\x92\xa5 Vanaf aanstaa...-899095860469861.f1808553269288186v.mp4.part'

```

## Description

When I want to download a video from facebook with strange characters in title like https://www.facebook.com/StreetJumpHaarlem/videos/899095860469861/. it is unable to download it.

**Comment by blieb** [comment]
With which issue is this a dublicate? I'm trying to find it but can't find it. Then I can follow that one.

**Comment by superclarkk** [comment]
@dstftw This bug still exists.

You have closed two of these issues without linking to the original ticket. Can you provide the ticket number, please?
