### ISSUE TITLE
Some CBSNews videos cannot be downloaded

### ISSUE THREAD

**Issue by MaximVol** [ytdl-org/youtube-dl#22560]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2019.09.28**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.cbsnews.com/news/nancy-pelosi-on-trump-impeachment-inquiry-ukraine-president-phone-call-and-the-whistleblower-in-60-minutes-interview/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-11-amd64-x86_64-with-debian-9.11
[debug] exe versions: ffmpeg 3.3.9, ffprobe 3.3.9
[debug] Proxy map: {}
[cbsnews] nancy-pelosi-on-trump-impeachment-inquiry-ukraine-president-phone-call-and-the-whistleblower-in-60-minutes-interview: Downloading webpage
ERROR: Unable to extract video JSON info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/cbsnews.py", line 107, in _real_extract
    webpage, 'video JSON info'), display_id)['items'][0]
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video JSON info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

Some videos cannot be downloaded from the cbsnews.com website. Youtube-dl returns error "Unable to extract video JSON info".

This is an example of the video:
[https://www.cbsnews.com/news/nancy-pelosi-on-trump-impeachment-inquiry-ukraine-president-phone-call-and-the-whistleblower-in-60-minutes-interview/](url)

**Comment by dirkf** [comment]
The problem URL no longer has a video (empty manifest), but  the extractor tries to get preview snippet videos that used to be hosted at Google. Superseded by #32011.
