### ISSUE TITLE
Authorization for vk.com with login and password

### ISSUE THREAD

**Issue by langKeeper** [ytdl-org/youtube-dl#22568]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-s', u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://vk.com/annaanton90?z=video-108516935_456242585%2F4f1013712df550a461%2Fpl_post_-22798006_717036']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-957.5.1.el7.x86_64-x86_64-with-centos-7.6.1810-Core
[debug] exe versions: ffmpeg git-2016-07-06-3e4357e, ffprobe git-2016-07-06-3e4357e
[debug] Proxy map: {}
[vk] Downloading login page
[vk] Logging in
[vk] -108516935_456242585: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vk.py", line 416, in _real_extract
TypeError: string indices must be integers
```

## Description

Hello.
I’m trying to download a video from vk.com accessible to logged in users and get an error.

**Comment by langKeeper** [comment]
Hi.
Sent your account details to you via email.
