### ISSUE TITLE
DJ Akme Youtube channel - Multiple tracks cannot be extracted

### ISSUE THREAD

**Issue by karendar** [ytdl-org/youtube-dl#22575]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\temp\playlist>..\youtube-dl -x --verbose https://www.youtube.com/watch?v=ykSMrgjSeGE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', '--verbose', 'https://www.youtube.com/watch?v=ykSMrgjSeGE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-94396-g47b6ca0b02, ffprobe N-94396-g47b6ca0b02
[debug] Proxy map: {}
[youtube] ykSMrgjSeGE: Downloading webpage
[youtube] ykSMrgjSeGE: Downloading video info webpage
[youtube] ykSMrgjSeGE: Downloading MPD manifest
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1569991793/ei/EdiTXdzXGeLz8gS5lpsg/ip/70.50.204.11/id/ca448cae08d27861/source/youtube/requiressl/yes/playback_host/r7---sn-cxaaj5o5q5-t0a6.googlevideo.com/mm/31%2C26/mn/sn-cxaaj5o5q5-t0a6%2Csn-tt1eln7e/ms/au%2Conr/mv/m/mvi/6/pl/22/tx/23813233/txs/23813232%2C23813233%2C23813234%2C23813235%2C23813236%2C23813237%2C23813238/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1658750/mt/1569970097/fvip/1/fexp/23842630/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Citag/sig/ALgxI2wwRgIhAJeZ-_uAZauRxTlMNcnaOfa4KafWpjUoqvOjk19PowcaAiEA-bCIfs9YszaNCDadddpff0IQjFjuR1DHsxIcmW9ZlkE%3D/lsparams/playback_host%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AHylml4wRgIhAIWBR_zvshDauxVWsqL2wWWCwnNqD2h80pcT6u1iSDSSAiEAtfHIuw2-P246T9pOhVo6UF8o-t-r7z2fl2GcxwqvDcs%3D'
[download] My Vibe x Dj Switch [Flow Promo] By 🇯 🇲  Dj Akme 🔥 🇺 🇬  🇳 🇬  🇸 🇱  🇬
🇭  🇹 🇿 -ykSMrgjSeGE.webm has already been downloaded
[download] 100% of 3.65MiB
[debug] ffmpeg command line: ffprobe -show_streams "file:My Vibe x Dj Switch [Flow Promo] By 🇯 🇲  Dj Akme 🔥 🇺 🇬  🇳 🇬  🇸 🇱  🇬 🇭  🇹 🇿 -ykSMrgjSeGE.webm"
[ffmpeg] Destination: My Vibe x Dj Switch [Flow Promo] By 🇯 🇲  Dj Akme 🔥 🇺 🇬  �ERROR: error running ffmpeg
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\postprocessor\ffmpeg.py", line 335, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\YoutubeDL.py", line 502, in to_screen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\YoutubeDL.py", line 516, in to_stdout
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\YoutubeDL.py", line 505, in _write_string
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\utils.py", line 3074, in write_string
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\utils.py", line 3058, in _windows_write_string
OSError: Failed to write string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\YoutubeDL.py", line 2064, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\postprocessor\ffmpeg.py", line 341, in run
youtube_dl.utils.PostProcessingError: error running ffmpeg


C:\temp\playlist>..\youtube-dl --verbose https://www.youtube.com/watch?v=ykSMrgjSeGE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=ykSMrgjSeGE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-94396-g47b6ca0b02, ffprobe N-94396-g47b6ca0b02
[debug] Proxy map: {}
[youtube] ykSMrgjSeGE: Downloading webpage
[youtube] ykSMrgjSeGE: Downloading video info webpage
[youtube] ykSMrgjSeGE: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1569991804/ei/HNiTXd2vK4y-hgaGjry4CA/ip/70.50.204.11/id/ca448cae08d27861/source/youtube/requiressl/yes/playback_host/r7---sn-cxaaj5o5q5-t0a6.googlevideo.com/mm/31%2C26/mn/sn-cxaaj5o5q5-t0a6%2Csn-tt1e7n7e/ms/au%2Conr/mv/m/mvi/6/pcm2cms/yes/pl/22/tx/23813238/txs/23813232%2C23813233%2C23813234%2C23813235%2C23813236%2C23813237%2C23813238/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1658750/mt/1569970097/fvip/1/fexp/23842630/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Citag/sig/ALgxI2wwRQIge9nFyeCNiRbZ38Gvb9day3P6SpTUvWLGSPiFfk8KAowCIQDk3pflTHzGAy287BHkifIqh_YOUn9VwzdcI2eKIjlB2w%3D%3D/lsparams/playback_host%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps/lsig/AHylml4wRgIhALNR-gxQVTfU14n1d3k0huXfrB4aaCZs7EizlZyCm2cLAiEAn67m1gEBDdPhLAE5UrHq_2VZDR-gH2JTxkvgX7wrXbU%3D'
[dashsegments] Total fragments: 43
[download] Destination: My Vibe x Dj Switch [Flow Promo] By 🇯 🇲  Dj Akme 🔥 🇺 🇬
 🇳 🇬  🇸 🇱  🇬 🇭  🇹 🇿 -ykSMrgjSeGE.f137.mp4
[download] 100% of 111.12MiB in 00:16
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1569991804/ei/HNiTXd2vK4y-hgaGjry4CA/ip/70.50.204.11/id/ca448cae08d27861/source/youtube/requiressl/yes/playback_host/r7---sn-cxaaj5o5q5-t0a6.googlevideo.com/mm/31%2C26/mn/sn-cxaaj5o5q5-t0a6%2Csn-tt1e7n7e/ms/au%2Conr/mv/m/mvi/6/pcm2cms/yes/pl/22/tx/23813238/txs/23813232%2C23813233%2C23813234%2C23813235%2C23813236%2C23813237%2C23813238/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1658750/mt/1569970097/fvip/1/fexp/23842630/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Citag/sig/ALgxI2wwRQIge9nFyeCNiRbZ38Gvb9day3P6SpTUvWLGSPiFfk8KAowCIQDk3pflTHzGAy287BHkifIqh_YOUn9VwzdcI2eKIjlB2w%3D%3D/lsparams/playback_host%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps/lsig/AHylml4wRgIhALNR-gxQVTfU14n1d3k0huXfrB4aaCZs7EizlZyCm2cLAiEAn67m1gEBDdPhLAE5UrHq_2VZDR-gH2JTxkvgX7wrXbU%3D'
[dashsegments] Total fragments: 23
[download] Destination: My Vibe x Dj Switch [Flow Promo] By 🇯 🇲  Dj Akme 🔥 🇺 🇬
 🇳 🇬  🇸 🇱  🇬 🇭  🇹 🇿 -ykSMrgjSeGE.f251.webm
[download] 100% of 3.65MiB in 00:01
[ffmpeg] Merging formats into "My Vibe x Dj Switch [Flow Promo] By 🇯 🇲  Dj Akme 🔥 🇺 🇬  🇳 🇬  🇸 🇱  🇬 🇭  🇹 🇿 -ykSMrgjSeGE.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:My Vibe x Dj Switch [Flow Promo] By 🇯 🇲  Dj Akme 🔥 🇺 🇬  🇳 🇬  🇸 🇱  🇬 🇭  🇹 🇿 -ykSMrgjSeGE.f137.mp4" -i "file:My Vibe x Dj Switch [Flow Promo] By 🇯 🇲  Dj Akme 🔥 🇺 🇬  🇳 �Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\YoutubeDL.py", line 2018, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\YoutubeDL.py", line 807, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\YoutubeDL.py", line 862, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\YoutubeDL.py", line 1643, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\YoutubeDL.py", line 1999, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\YoutubeDL.py", line 2064, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\postprocessor\ffmpeg.py", line 512, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\postprocessor\ffmpeg.py", line 229, in run_ffmpeg_multiple_files
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\YoutubeDL.py", line 502, in to_screen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\YoutubeDL.py", line 516, in to_stdout
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\YoutubeDL.py", line 505, in _write_string
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\utils.py", line 3074, in write_string
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\utils.py", line 3058, in _windows_write_string
OSError: Failed to write string
```

## Description

I have a youtuber which posts songs on a regular basis. He has a massive love for random special characters. Here are three failing URL's: 

https://www.youtube.com/watch?v=dlhJsonLQ3c
https://www.youtube.com/watch?v=8GZsvUHJvfQ
https://www.youtube.com/watch?v=ykSMrgjSeGE

I've sampled the last one with two commands, one to convert to MP3 and one that doesn't. It fails extracting everytime I attempt something, which makes it tedious to extract a big playlist with these songs in them. 

Thanks

**Comment by dstftw** [comment]
```
> youtube-dl https://www.youtube.com/watch?v=ykSMrgjSeGE -x
[youtube] ykSMrgjSeGE: Downloading webpage
[youtube] ykSMrgjSeGE: Downloading video info webpage
[youtube] ykSMrgjSeGE: Downloading MPD manifest
[dashsegments] Total fragments: 23
[download] Destination: My Vibe x Dj Switch [Flow Promo] By 🇯🇲 Dj Akme 🔥 🇺🇬 🇳🇬 🇸🇱 🇬🇭 🇹🇿-ykSMrgjSeGE.webm
[download] 100% of 3.65MiB in 00:01
[ffmpeg] Destination: My Vibe x Dj Switch [Flow Promo] By 🇯🇲 Dj Akme 🔥 🇺🇬 🇳🇬 🇸🇱 🇬🇭 🇹🇿-ykSMrgjSeGE.opus
Deleting original file My Vibe x Dj Switch [Flow Promo] By 🇯🇲 Dj Akme 🔥 🇺🇬 🇳🇬 🇸🇱 🇬🇭 🇹🇿-ykSMrgjSeGE.webm (pass -k to keep)
```

**Comment by karendar** [comment]
Just an added comment for this issue for anyone wondering: The issue is while converting in ffmpeg. The string fails because of special characters: 

I ran this command: 

C:\temp\playlist\test>C:\temp\ffmpeg -y -loglevel "repeat+info" -i "file:Teneneh - Rahim x Dallas B [Flow Promo] By 🇿🇿 Dj Akme 🇿 🇿🇿 🇿🇿 🇿🇿 🇿🇿 🇿🇿-8GZsvUHJvfQ.webm" test.mp3 

And it works. However, the way that the youtube-dl exec hands off the string to ffmpeg, it fails everytime. Here is how ffmpeg interprets the filename, which might be the cause due to special characters: 

Input #0, matroska,webm, from 'file:Teneneh - Rahim x Dallas B [Flow Promo] By ≡ƒç»≡ƒç▓ Dj Akme ≡ƒöÑ ≡ƒç║≡ƒç¼ ≡ƒç│≡ƒç¼ ≡ƒç╕≡ƒç▒ ≡ƒç¼≡ƒç¡ ≡ƒç╣≡ƒç┐-8GZsvUHJvfQ.webm':
  Metadata:

So is the issue with the extraction part of youtube-dl? No, this works fine to pull the webm. The issue is post extraction and during conversion, but ONLY when using youtube-dl commands to invoke ffmpeg, as running the SAME command manually through ffmpeg handles the conversion well.

**Comment by karendar** [comment]
@dstftw Don't know if there's anything more you can do to investigate this, is there a way to strip special characters? Can we rename the file post extraction with a command? I'd really like to get this to work, because the workaround right now is that everything DJ Akme needs to be saved to a separate file, needs to be extracted manually and needs to be converted manually. Becomes pretty tedious a task to manage...
