### ISSUE TITLE
Unable to download video - Yahoo finance???

### ISSUE THREAD

**Issue by chris2614** [ytdl-org/youtube-dl#22576]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2019.09.28**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

Chriss-MacBook-Air:~ chriswarren$ youtube-dl --verbose https://uk.finance.yahoo.com/video/nigel-farage-falls-prank-call-114242755.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://uk.finance.yahoo.com/video/nigel-farage-falls-prank-call-114242755.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.10 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Yahoo] nigel-farage-falls-prank-call: Downloading webpage
ERROR: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/yahoo.py", line 350, in _real_extract
    CONTENT_ID_REGEXES, webpage, 'content ID')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

## Description

WRITE DESCRIPTION HERE

**Comment by Danieldavid521** [comment]
I get the same error, will try and investigate. similar issue here https://github.com/ytdl-org/youtube-dl/issues/14210

**Comment by MobiDotS** [comment]
This is due to a consent pop-up when you visit the site:

![image](https://user-images.githubusercontent.com/13970649/66781764-c12efd80-ee99-11e9-9651-79ea5f79703f.png)

We will have to modify the Extractor to handle clicking OK on the consent popup which leads to the correct URL.
