### ISSUE TITLE
"Unable to extract encoded url" error

### ISSUE THREAD

**Issue by danb35** [ytdl-org/youtube-dl#22591]
## Checklist

- [ x ] I'm reporting a broken site support
- [ x ] I've verified that I'm running youtube-dl version **2019.09.28**
- [ x ] I've checked that all provided URLs are alive and playable in a browser
- [ x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
root@jdownloader:/media/jdownloader/indigo # youtube-dl --recode-video mp4 -w -o "%(upload_date)s-%(title)s.%(ext)s" "https://www.pornhub.com/pornstar/indigo-white/videos" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--recode-video', 'mp4', '-w', '-o', '%(upload_date)s-%(title)s.%(ext)s', 'https://www.pornhub.com/pornstar/indigo-white/videos', '--verbose']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale US-ASCII, fs ascii, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.6.8 (CPython) - FreeBSD-11.2-STABLE-amd64-64bit-ELF
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[PornHubPagedVideoList] pornstar/indigo-white/videos: Downloading page 1
[PornHubPagedVideoList] pornstar/indigo-white/videos: Downloading page 2
[PornHubPagedVideoList] pornstar/indigo-white/videos: Downloading page 3
[PornHubPagedVideoList] pornstar/indigo-white/videos: Downloading page 4
[PornHubPagedVideoList] pornstar/indigo-white/videos: Downloading page 5
[PornHubPagedVideoList] pornstar/indigo-white/videos: Downloading page 6
[download] Downloading playlist: pornstar/indigo-white/videos
[PornHubPagedVideoList] playlist pornstar/indigo-white/videos: Collected 229 video ids (downloading 229 of them)
[download] Downloading video 1 of 229
[PornHub] ph5d94d59ba8322: Downloading pc webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://cv.phncdn.com/videos/201910/02/252310512/1080P_4000K_252310512.mp4?9XghjLJORHI5Al8YtzrwGjgmBzINpZDpiZKQZSAdkXk7E5seKZ6bU2bEuheViMjgs2nICCGm4axi54x7oeslL_260ds0JG0PhaHAAuzGuUh5evHMrRSRFOcumFYS-9_jWKie0LXjgSvmuFyXNl2pc80Fz-R50IR0n32YgJm8sL8f05cz83HI1cqkhkbBSWkMxAIGsg7f--93HUMoLA'
[download] 20191002-420_NURSE_HELPS_YOU_CHILL_TF_OUT_-_INDIGO_WHITE.mp4 has already been downloaded
[download] 100% of 574.51MiB
[ffmpeg] Not converting video file 20191002-420_NURSE_HELPS_YOU_CHILL_TF_OUT_-_INDIGO_WHITE.mp4 - already is in target format mp4
[download] Downloading video 2 of 229
[PornHub] ph5d8c15819ffad: Downloading pc webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://dv.phncdn.com/videos/201909/26/250862062/1080P_4000K_250862062.mp4?ttl=1570103062&ri=51200000&rs=400000&hash=3cae368b86667d0c5fafb089058b899c'
[download] 20190926-WHAT_TEDDY-CHAN_DOES_WHILE_YOU_RE_AT_WORK_-_INDIGO_WHITE.mp4 has already been downloaded
[download] 100% of 786.00MiB
[ffmpeg] Not converting video file 20190926-WHAT_TEDDY-CHAN_DOES_WHILE_YOU_RE_AT_WORK_-_INDIGO_WHITE.mp4 - already is in target format mp4
[download] Downloading video 3 of 229
[PornHub] ph5d88fc0bbd8e0: Downloading pc webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://dv.phncdn.com/videos/201909/23/250333811/1080P_4000K_250333811.mp4?ttl=1570103063&ri=51200000&rs=400000&hash=962cddd7b03efb087245dc03006567d6'
[download] 20190923-SHIELD_BRO_HAS_TO_CHOOSE_-_INDIGO_WHITE.mp4 has already been downloaded
[download] 100% of 1.41GiB
[ffmpeg] Not converting video file 20190923-SHIELD_BRO_HAS_TO_CHOOSE_-_INDIGO_WHITE.mp4 - already is in target format mp4
[download] Downloading video 4 of 229
[PornHub] ph5d841783785cb: Downloading pc webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://cv.phncdn.com/videos/201909/20/249533381/1080P_4000K_249533381.mp4?supKf81M8vTwWpSW1TaijMJc_bRiGSk2mcga2YzlZjAnMV0mrTEjNRLRYJ0nllDxG0TPf_nUqqnhQlctI4YKL729Aqo6bYIRGGNWTcyX0ev6U_Lt5Z_O7Ge5_ZZabh3lxcp-fdvCZK95Df9c4PALJJROLnLzGPFFc60RtJaE9QeMyKp-BndSCa2xXDpAECBwlyad5jxray-tUEI02w'
[download] 20190920-RAIDING_AREA_51_-_INDIGO_WHITE.mp4 has already been downloaded
[download] 100% of 875.56MiB
[ffmpeg] Not converting video file 20190920-RAIDING_AREA_51_-_INDIGO_WHITE.mp4 - already is in target format mp4
[download] Downloading video 5 of 229
[PornHub] ph5d83af35f3673: Downloading pc webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://ev.phncdn.com/videos/201909/19/249464471/1080P_4000K_249464471.mp4?validfrom=1570095865&validto=1570103065&rate=50000k&burst=50000k&hash=w5OLjnYSb0eOzxzUnCmOnulinCw%3D'
[download] 20190919-COW_WAIFU_TAKES_A_MILK_BATH_Slow_Motion_-_INDIGO_WHITE.mp4 has already been downloaded
[download] 100% of 1.09GiB
[ffmpeg] Not converting video file 20190919-COW_WAIFU_TAKES_A_MILK_BATH_Slow_Motion_-_INDIGO_WHITE.mp4 - already is in target format mp4
[download] Downloading video 6 of 229
[PornHub] ph5ca26a850d6b8: Downloading pc webpage
[PornHub] ph5ca26a850d6b8: Downloading tv webpage
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhub.py", line 235, in _real_extract
    'encoded url').split(';')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

I think the issue is pretty well described by the command output above--trying to download a channel from PornHub succeeds in downloading a few videos, then ends with an error of "unable to extract encoded url".

**Comment by molnarjani** [comment]
It seems that it cannot extract the URL for the Premium videos, you can pass `-i` flag to ignore the erros.

> youtube-dl --help
> ...
> -i, --ignore-errors              Continue on download errors, for example to skip unavailable videos in a playlist

**Comment by danb35** [comment]
That does seem to have fixed it (and seems like an obvious thing for me to have tried in the first place)--thanks.

**Comment by cewatkins** [comment]
Well, then it's changed again recently to everything. Including simple playlists, I was actually using that d/ler, but the command line alone looked simpler, so i just grabs a playlist,s the behavior change  is across bistros, -i lets it fail, but after a -U and such, it got worse behavior wise complain for regex. The behavior of it with playlists is certainly recently chained, it used to go throughout pages and now it is stuck to 36 or less before it vomits.  I just assumed because ph is changing stuff regularly  one was sol on the youtube-dl client flowing them.  this was a new ubuntu 16 container 
I tried updating with -U , pip and then apt-get to becertain and a container as well as fixed die, around two weeks ago it quite reading page1,2,,3,4,,5,6, if it was apart of a playlist.
Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
ie_result = ie.extract(url)
File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
ie_result = self._real_extract(url)
File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/pornhub.py",line 235, in _real_extract
'encoded url').split(';')
File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
