### ISSUE TITLE
Youtube Login Doesn't Work with -username -password

### ISSUE THREAD

**Issue by jmitz5** [ytdl-org/youtube-dl#22600]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

Here is one atempt:

youtube-dl -v --username 'Jacob Mitz' --password ‘password’ https://www.youtube.com/watch?v=Z7Os4WzELek
[debug] System config: [u'-o', u'~/Downloads/%(title)s-DL.%(ext)s', u'-f', u'bestvideo[ext=webm]+258/bestvideo[ext=webm]+251/bestvideo[ext=webm]+bestaudio/bestvideo[ext=mp4]+258/bestvideo[ext=mp4]+251/bestvideo[ext=mp4]+bestaudio/best', u'--no-playlist', u'--write-sub', u'--write-auto-sub', u'--sub-lang', u'en,en-GB', u'--embed-subs', u'--add-metadata', u'--sub-format', u'ttml/srv3/srv2/srv1/vtt', u'--convert-subs', u'vtt']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://www.youtube.com/watch?v=Z7Os4WzELek']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.1, ffprobe 4.0.1
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
WARNING: Unable to extract user hash
[youtube] Z7Os4WzELek: Downloading webpage
[youtube] Z7Os4WzELek: Downloading embed webpage
[youtube] Z7Os4WzELek: Refetching age-gated info webpage
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] Downloading just video Z7Os4WzELek because of --no-playlist
ERROR: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2148, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.




Here is a different atempt:

youtube-dl -v --username 'jmitzenmacher5' --password ‘password’ https://www.youtube.com/watch?v=Z7Os4WzELek
[debug] System config: [u'-o', u'~/Downloads/%(title)s-DL.%(ext)s', u'-f', u'bestvideo[ext=webm]+258/bestvideo[ext=webm]+251/bestvideo[ext=webm]+bestaudio/bestvideo[ext=mp4]+258/bestvideo[ext=mp4]+251/bestvideo[ext=mp4]+bestaudio/best', u'--no-playlist', u'--write-sub', u'--write-auto-sub', u'--sub-lang', u'en,en-GB', u'--embed-subs', u'--add-metadata', u'--sub-format', u'ttml/srv3/srv2/srv1/vtt', u'--convert-subs', u'vtt']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://www.youtube.com/watch?v=Z7Os4WzELek']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.1, ffprobe 4.0.1
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
WARNING: Unable to extract result entry
[youtube] Z7Os4WzELek: Downloading webpage
[youtube] Z7Os4WzELek: Downloading embed webpage
[youtube] Z7Os4WzELek: Refetching age-gated info webpage
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] Downloading just video Z7Os4WzELek because of --no-playlist
ERROR: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2148, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.
```

## Description

WRITE DESCRIPTION HERE

I am trying to download a private youtube video by using the --username --password options, but the login process never seems to work. In the verbose logs, you can see I tried it with my username, but I also tried it with my Gmail login (both with and without the @gmail.com part). I also tried all of those combinations with and without the escaping tick marks. I'm not sure what else to try, other than just going the cookie route (I did try that too, but all of the tutorials on it don't seem to be fully up to date regarding google's security).

**Comment by dstftw** [comment]
Invalid quotes for password.

**Comment by overgara2012** [comment]
I have same issue:

C:\Users\overg\Downloads>youtube-dl --verbose --username "overgara@gmail.com" --password "xxxxxxx" "https://www.youtube.com/watch?time_continue=985&v=wpWvdcHZqnk"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.youtube.com/watch?time_continue=985&v=wpWvdcHZqnk']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.10.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
WARNING: Unable to extract result entry
[youtube] wpWvdcHZqnk: Downloading webpage
[youtube] wpWvdcHZqnk: Downloading embed webpage
[youtube] wpWvdcHZqnk: Refetching age-gated info webpage
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\youtube.py", line 2148, in _real_extract
youtube_dl.utils.ExtractorError: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.

**Comment by jjuri-socialmining** [comment]
same here

**Comment by laerne** [comment]
I'm reporting the issue as well. `-u X -p Y` never, ever works regardless of the version of youtube-dl.

**Comment by laerne** [comment]
I'm reporting the issue as well. `-u X -p Y` never, ever works regardless of the version of youtube-dl.
Here is the attempt closest to what should work :
```
$ youtube-dl https://www.youtube.com/watch?v=oPkxD-etLec --verbose --print-traffic --username PRIVATE --password "PRIVATE"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=oPkxD-etLec', '--verbose', '--print-traffic', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.0 (CPython) - Linux-6.0.12-300.fc37.x86_64-x86_64-with-glibc2.36
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2
[debug] Proxy map: {}
[youtube] Downloading login page
send: b'GET /ServiceLogin HTTP/1.1\r\nHost: accounts.google.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3611.1 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 302 Moved Temporarily\r\n'
header: Content-Type: text/html; charset=UTF-8
header: X-Frame-Options: DENY
header: Cache-Control: no-cache, no-store, max-age=0, must-revalidate
header: Pragma: no-cache
header: Expires: Mon, 01 Jan 1990 00:00:00 GMT
header: Date: Sun, 18 Dec 2022 15:30:38 GMT
header: Location: https://accounts.google.com/v3/signin/identifier?dsh=S872678440%3A1671377438921956&flowName=GlifWebSignIn&flowEntry=ServiceLogin&ifkv=AeAAQh5-4Sj880W5_m4qiP69pHquYCRo6P9Xx2TarQqK3JiQk0uYSwj5JCfGaStjMCNJEjyDshbFiQ
header: Strict-Transport-Security: max-age=31536000; includeSubDomains
header: Report-To: {"group":"coop_gse_qebhlk","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/gse_qebhlk"}]}
header: Content-Security-Policy: script-src 'report-sample' 'nonce-AcBtqBQc0EU_pkkY82Aj1A' 'unsafe-inline' 'unsafe-eval';object-src 'none';base-uri 'self';report-uri /cspreport
header: Content-Security-Policy: require-trusted-types-for 'script';report-uri /cspreport
header: Cross-Origin-Opener-Policy-Report-Only: same-origin; report-to="coop_gse_qebhlk"
header: Content-Encoding: gzip
header: X-Content-Type-Options: nosniff
header: X-XSS-Protection: 1; mode=block
header: Server: GSE
header: Set-Cookie: __Host-GAPS=1:jLqEZ6ZkPOPm-oFMgvnARwc7f0DbnQ:neeH0BS2lAMOqVbn;Path=/;Expires=Tue, 17-Dec-2024 15:30:38 GMT;Secure;HttpOnly;Priority=HIGH
header: Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
header: Connection: close
header: Transfer-Encoding: chunked
send: b'GET /v3/signin/identifier?dsh=S872678440%3A1671377438921956&flowName=GlifWebSignIn&flowEntry=ServiceLogin&ifkv=AeAAQh5-4Sj880W5_m4qiP69pHquYCRo6P9Xx2TarQqK3JiQk0uYSwj5JCfGaStjMCNJEjyDshbFiQ HTTP/1.1\r\nHost: accounts.google.com\r\nCookie: __Host-GAPS=1:jLqEZ6ZkPOPm-oFMgvnARwc7f0DbnQ:neeH0BS2lAMOqVbn\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3611.1 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: text/html; charset=utf-8
header: X-Frame-Options: DENY
header: Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site
header: x-auto-login: realm=com.google&args=continue%3Dhttps://accounts.google.com/ManageAccount?nc%253D1
header: x-ua-compatible: IE=edge
header: Cache-Control: no-cache, no-store, max-age=0, must-revalidate
header: Pragma: no-cache
header: Expires: Mon, 01 Jan 1990 00:00:00 GMT
header: Date: Sun, 18 Dec 2022 15:30:39 GMT
header: Strict-Transport-Security: max-age=31536000; includeSubDomains
header: Cross-Origin-Opener-Policy-Report-Only: same-origin
header: Content-Security-Policy: require-trusted-types-for 'script';report-uri /v3/signin/_/AccountsSignInUi/cspreport
header: Content-Security-Policy: script-src 'report-sample' 'nonce-QhRSB-OFR07DMNqwCWyIDg' 'unsafe-inline';object-src 'none';base-uri 'self';report-uri /v3/signin/_/AccountsSignInUi/cspreport;worker-src 'self'
header: Content-Security-Policy: script-src 'unsafe-inline' 'self' https://apis.google.com https://ssl.gstatic.com https://www.google.com https://www.gstatic.com https://www.google-analytics.com;report-uri /v3/signin/_/AccountsSignInUi/cspreport/allowlist
header: Permissions-Policy: ch-ua-arch=*, ch-ua-bitness=*, ch-ua-full-version=*, ch-ua-full-version-list=*, ch-ua-model=*, ch-ua-wow64=*, ch-ua-platform=*, ch-ua-platform-version=*
header: Cross-Origin-Resource-Policy: same-site
header: Accept-CH: Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Model, Sec-CH-UA-WoW64, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version
header: Content-Encoding: gzip
header: Server: ESF
header: X-XSS-Protection: 0
header: X-Content-Type-Options: nosniff
header: Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
header: Connection: close
header: Transfer-Encoding: chunked
[youtube] Looking up account info
send: b'POST /_/signin/sl/lookup HTTP/1.1\r\nContent-Length: 1006\r\nHost: accounts.google.com\r\nCookie: __Host-GAPS=1:jLqEZ6ZkPOPm-oFMgvnARwc7f0DbnQ:neeH0BS2lAMOqVbn\r\nContent-Type: application/x-www-form-urlencoded;charset=utf-8\r\nGoogle-Accounts-Xsrf: 1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3611.1 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
send: b'usi=S872678440%3A1671377438921956&domain=&region=FR&pstMsg=1&checkConnection=youtube&checkedDomains=youtube&hl=en&deviceinfo=%5Bnull%2Cnull%2Cnull%2C%5B%5D%2Cnull%2C%22US%22%2Cnull%2Cnull%2C%5B%5D%2C%22GlifWebSignIn%22%2Cnull%2C%5Bnull%2Cnull%2C%5B%5D%5D%5D&f.req=%5B%228dX08adjCBmU%40gmail.com%22%2C+null%2C+%5B%5D%2C+null%2C+%22US%22%2C+null%2C+null%2C+2%2C+false%2C+true%2C+%5Bnull%2C+null%2C+%5B2%2C+1%2C+null%2C+1%2C+%22https%3A%2F%2Faccounts.google.com%2FServiceLogin%3Fpassive%3Dtrue%26continue%3Dhttps%253A%252F%252Fwww.youtube.com%252Fsignin%253Fnext%253D%25252F%2526action_handle_signin%253Dtrue%2526hl%253Den%2526app%253Ddesktop%2526feature%253Dsign_in_button%26hl%3Den%26service%3Dyoutube%26uilel%3D3%26requestPath%3D%252FServiceLogin%26Page%3DPasswordSeparationSignIn%22%2C+null%2C+%5B%5D%2C+4%5D%2C+1%2C+%5Bnull%2C+null%2C+%5B%5D%5D%2C+null%2C+null%2C+null%2C+true%5D%2C+%228dX08adjCBmU%40gmail.com%22%5D&flowName=GlifWebSignIn&flowEntry=ServiceLogin&bgRequest=%5B%22identifier%22%2C%22%22%5D'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Cache-Control: no-cache, no-store, max-age=0, must-revalidate
header: Pragma: no-cache
header: Expires: Mon, 01 Jan 1990 00:00:00 GMT
header: Date: Sun, 18 Dec 2022 15:30:39 GMT
header: Content-Type: text/html; charset=utf-8
header: Content-Encoding: gzip
header: X-Content-Type-Options: nosniff
header: X-XSS-Protection: 1; mode=block
header: Server: GSE
header: Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
header: Connection: close
header: Transfer-Encoding: chunked
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
[youtube] oPkxD-etLec: Downloading webpage
send: b'GET /watch?v=oPkxD-etLec&bpctr=9999999999&has_verified=1 HTTP/1.1\r\nHost: www.youtube.com\r\nCookie: CONSENT=YES+cb.20210328-17-p0.en+FX+551\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3611.1 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: text/html; charset=utf-8
header: X-Content-Type-Options: nosniff
header: Cache-Control: no-cache, no-store, max-age=0, must-revalidate
header: Pragma: no-cache
header: Expires: Mon, 01 Jan 1990 00:00:00 GMT
header: Date: Sun, 18 Dec 2022 15:30:39 GMT
header: X-Frame-Options: SAMEORIGIN
header: Strict-Transport-Security: max-age=31536000
header: Cross-Origin-Opener-Policy-Report-Only: same-origin-allow-popups; report-to="youtube_main"
header: Accept-CH: Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Model, Sec-CH-UA-WoW64, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version
header: Vary: Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Model, Sec-CH-UA-WoW64, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version
header: Report-To: {"group":"youtube_main","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/youtube_main"}]}
header: Permissions-Policy: ch-ua-arch=*, ch-ua-bitness=*, ch-ua-full-version=*, ch-ua-full-version-list=*, ch-ua-model=*, ch-ua-wow64=*, ch-ua-platform=*, ch-ua-platform-version=*
header: P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
header: Content-Encoding: gzip
header: Server: ESF
header: X-XSS-Protection: 0
header: Set-Cookie: GPS=1; Domain=.youtube.com; Expires=Sun, 18-Dec-2022 16:00:39 GMT; Path=/; Secure; HttpOnly
header: Set-Cookie: YSC=h1n4Y0cwDBc; Domain=.youtube.com; Path=/; Secure; HttpOnly; SameSite=none
header: Set-Cookie: __Secure-YEC=; Domain=.youtube.com; Expires=Mon, 23-Mar-2020 15:30:39 GMT; Path=/; Secure; HttpOnly; SameSite=lax
header: Set-Cookie: VISITOR_INFO1_LIVE=g9kM0lXR314; Domain=.youtube.com; Expires=Fri, 16-Jun-2023 15:30:39 GMT; Path=/; Secure; HttpOnly; SameSite=none
header: Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
header: Connection: close
header: Transfer-Encoding: chunked
[youtube] oPkxD-etLec: Refetching age-gated info webpage
send: b'GET /get_video_info?video_id=oPkxD-etLec&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FoPkxD-etLec&html5=1&c=TVHTML5&cver=6.20180913 HTTP/1.1\r\nHost: www.youtube.com\r\nCookie: CONSENT=YES+cb.20210328-17-p0.en+FX+551; GPS=1; YSC=h1n4Y0cwDBc; VISITOR_INFO1_LIVE=g9kM0lXR314\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3611.1 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 410 Gone\r\n'
header: Content-Type: text/html; charset=utf-8
header: X-Content-Type-Options: nosniff
header: Expires: Mon, 19 Dec 2022 15:30:39 GMT
header: Date: Sun, 18 Dec 2022 15:30:39 GMT
header: Cache-Control: public, max-age=86400
header: Strict-Transport-Security: max-age=31536000
header: X-Frame-Options: SAMEORIGIN
header: Cross-Origin-Opener-Policy-Report-Only: same-origin; report-to="youtube_main"
header: Accept-CH: Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Model, Sec-CH-UA-WoW64, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version
header: Vary: Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Model, Sec-CH-UA-WoW64, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version
header: Report-To: {"group":"youtube_main","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/youtube_main"}]}
header: Permissions-Policy: ch-ua-arch=*, ch-ua-bitness=*, ch-ua-full-version=*, ch-ua-full-version-list=*, ch-ua-model=*, ch-ua-wow64=*, ch-ua-platform=*, ch-ua-platform-version=*
header: Server: ESF
header: Content-Length: 0
header: X-XSS-Protection: 0
header: Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
header: Connection: close
WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
```

Aren't the `--username` and `--password` option specifically meant to "Sign to confirm your age" ? Why doesn't it attempts to "sign in" ?

**Comment by MarioVilas** [comment]
Why is it closed if it's still happening?

**Comment by dirkf** [comment]
No-one was able to re-implement the YT login procedure based on username and password after YT changed the scheme. So for YT, login using `--username ... --password ...` is expected to fail. 

You can authenticate using cookies exported from a logged-in session, ideally in a private browser window and then closed.
