### ISSUE TITLE
Vivo.sx not working?

### ISSUE THREAD

**Issue by OfficialCRUGG** [ytdl-org/youtube-dl#22621]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
tux@cruggserver:~$ youtube-dl -v https://vivo.sx/87dd0aed90
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://vivo.sx/87dd0aed90']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.16 (CPython) - Linux-5.0.0-31-generic-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: none
[debug] Proxy map: {}
[Vivo] 87dd0aed90: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/shared.py", line 26, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/shared.py", line 120, in _extract_video_url
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/shared.py", line 116, in decode_url
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2947, in compat_b64decode
  File "/usr/lib/python2.7/base64.py", line 75, in b64decode
    return binascii.a2b_base64(s)
TypeError: a2b_base64() argument 1 must be string or buffer, not None
```

## Description

Vivo.sx doesn't seem to work. While there are already closed issues, all I've found say that it's fixed, which is isn't...

**Comment by OfficialCRUGG** [comment]
Duplicate? What is this a duplicate of?

**Comment by OfficialCRUGG** [comment]
Okay, I now found a Pull Request which fixes this, however it's not merged, so this doesn't help me at all...
https://github.com/ytdl-org/youtube-dl/pull/22279

**Comment by byteholding** [comment]
It has been changed again. Could someone fix it, please?
