### ISSUE TITLE
YouTube said: Unable to extract video data

### ISSUE THREAD

**Issue by masoudkazemi** [ytdl-org/youtube-dl#22646]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
➜ ./youtube-dl -j -v https://www.youtube.com/watch\?v\=eLfpeg3Fofo
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-j', u'-v', u'https://www.youtube.com/watch?v=eLfpeg3Fofo']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-8-amd64-x86_64-with-debian-9.6
[debug] exe versions: avconv 3.2.12-1, avprobe 3.2.12-1, ffmpeg 3.2.12-1, ffprobe 3.2.12-1
[debug] Proxy map: {}
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: eLfpeg3Fofo: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "./ytdl/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "./ytdl/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "./ytdl/youtube-dl/youtube_dl/extractor/youtube.py", line 1836, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: eLfpeg3Fofo: YouTube said: Unable to extract video data
```

## Description

It seems youtube extractor is broken.

**Comment by srhinos** [comment]
@dstftw what is this a duplicate of? Of https://github.com/ytdl-org/youtube-dl/issues/22641 ?
