### ISSUE TITLE
[Go] Verizon failing to log in

### ISSUE THREAD

**Issue by spookyahell** [ytdl-org/youtube-dl#22647]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
>youtube-dl -F https://abc.go.com/shows/this-week-with-george-stephanopoulos/episode-guide/2019-10/06-100619-2nd-whistleblower-has-firsthand-knowledge-on-allegations-against-trump -v
[debug] System config: []
[debug] User config: ['-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--hls-use-mpegts', '--write-sub', '--all-subs', '--sub-format', 'srt/ssa/ass/vtt/dfxp/ttml/best', '--convert-subs', 'srt', '--ap-mso', 'Verizon', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE']
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://abc.go.com/shows/this-week-with-george-stephanopoulos/episode-guide/2019-10/06-100619-2nd-whistleblower-has-firsthand-knowledge-on-allegations-against-trump', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.7.4 (CPython) - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg N-94982-gea673a0edb, ffprobe N-94982-gea673a0edb
[debug] Proxy map: {}
[Go] 06-100619-2nd-whistleblower-has-firsthand-knowledge-on-allegations-against-trump: Downloading webpage
[Go] VDKA13272719: Downloading JSON metadata
[Go] VDKA13272719: Downloading Provider Redirect Page
[Go] VDKA13272719: Downloading SAML Login Page
ERROR: Unable to extract SAML Login URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\lucas\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\lucas\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\users\lucas\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\go.py", line 146, in _real_extract
    url, video_id, requestor_id, resource)
  File "c:\users\lucas\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\adobepass.py", line 1487, in _extract_mvpd_auth
    saml_login_page, 'SAML Login URL', group='url')
  File "c:\users\lucas\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract SAML Login URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

The authorization of a Verizon user for the Go "plugin" fails and needs fixing
(works correctly in the browser)

[I do not know how else to describe the issue]

I wonder if it's related to https://github.com/ytdl-org/youtube-dl/issues/16084 and subsequentually https://github.com/rg3/youtube-dl/pull/14363 but I doubt it actually...

**Comment by spookyahell** [comment]
I could provide sb willing to work with this with credentials if necessary (=not preferred, but possible)

**Comment by beren12** [comment]
Yeah looks like I can't use it for Disney stuff either now.

**Comment by 89z** [comment]
I dont think you need login for that one:

~~~
PS C:\> abc -i -a https://abc.com/shows/this-week-with-george-stephanopoulos/episode-guide/2019-10/06-100619-2nd-whistleblower-has-firsthand-knowledge-on-allegations-against-trump
GET http://prod.gatekeeper.us-abc.symphony.edgedatg.com/api/ws/pluto/v1/layout/route?brand=001&device=033_05&url=%2Fshows%2Fthis-week-with-george-stephanopoulos%2Fepisode-guide%2F2019-10%2F06-100619-2nd-whistleblower-has-firsthand-knowledge-on-allegations-against-trump
GET http://prod.gatekeeper.us-abc.symphony.edgedatg.com/api/ws/pluto/v1/module/videoplayer/2124246?brand=001&device=033_05&authlevel=0&layout=3715253&show=SH559082&video=VDKA13272719
POST http://api.entitlement.watchabc.go.com/vp2/ws-secure/entitlement/2020/authorize.json
GET http://content-dtci.uplynk.com/d5855ad2b2c041abbf5b40b82fab4a72.m3u8?cqs=BkHmJnqWz7l4iEULXirQneja9ic2SbGBt8wNgzCx6qK0QtQPHlibQQvhqs8wGkVfBRkY3yl_J3qan3g-qEa4wzyzWjL5yLO6R_RReludFasJDtNUWsCz0s85hYxEpdjBDsN9J4PqihoiEcj8igv0TxH2LCtzrCeQeGEfx96rjszG7uZHtjny5sujXR8_ykfhqqlUlER650QJJ4rlgfuRjMLXEdZGPQQ_vtMpZVEVX0uv9pWSGsgPUhQ20gmPY0lppiHkl1uzx8L_YUhpPnyqiGDIIFNxdkv1x8Q5Ubd7x7SkMgaP6eRcIch4FPZjGpNUO7ZF0K2-0i5hX9BFNwSayGs0ueDG9DgUnmHXCG7lHWyQrTg6jTq7SOGJfOVEe-Flcb5QZKnESzplaq1sQBOaWby6iv0g9wSomx3n30XpTtIsFNv2eIh22hCJks2npumS&kid=6dca329412b547d2a649ae8651130e91
ID: VDKA13272719
Show: This Week with George Stephanopoulos
Title: This Week 10/06/19: 2nd Whistleblower Has 'Firsthand Knowledge' On Allegations Against Trump
Season: 10
Episode: 40
Resolution:1152x648 Bandwidth:2762351 Codecs:mp4a.40.5,avc1.4d001f
Resolution:1088x612 Bandwidth:2198351 Codecs:mp4a.40.5,avc1.4d001f
Resolution:1280x720 Bandwidth:3749351 Codecs:mp4a.40.5,avc1.64001f
Resolution:1056x594 Bandwidth:1787101 Codecs:mp4a.40.5,avc1.4d001f
Resolution:992x558 Bandwidth:1258351 Codecs:mp4a.40.5,avc1.4d001f
Resolution:768x432 Bandwidth:753101 Codecs:mp4a.40.5,avc1.4d001e
Resolution:448x252 Bandwidth:435851 Codecs:mp4a.40.5,avc1.420015
Resolution:288x162 Bandwidth:253726 Codecs:mp4a.40.5,avc1.42000c
Resolution:192x108 Bandwidth:174681 Codecs:mp4a.40.5,avc1.42000b
Resolution:96x54 Bandwidth:71556 Codecs:mp4a.40.5,avc1.42000a
~~~

**Comment by 89z** [comment]
Looks like link is different now:

https://abc.com/shows/this-week-with-george-stephanopoulos/episode-guide/2019-10/06-100619-2nd-whistleblower-has-firsthand-knowledge-on-allegations-against-trump

**Comment by spookyahell** [comment]
For those just wanting a quick fix...
I think this may have been fixed for a while already over in the yt-dlp fork
https://github.com/yt-dlp/yt-dlp
