### ISSUE TITLE
cc.com can only download first video

### ISSUE THREAD

**Issue by ballo** [ytdl-org/youtube-dl#22676]
- [X ] I'm reporting a broken site support
- [X ] I've verified that I'm running youtube-dl version **2019.09.28**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
python3 `which youtube-dl` -v -f hls-1280 https://southpark.cc.com/full-episodes/s23e0

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'hls-1280', 'https://southpark.cc.com/full-episodes/s23e02-band-in-china#source=2b6c5ab4-d717-4e84-9143-918793a3b636:63a32034-1ea6-492d-b95b-9433e3f62f8d&position=1&sort=airdate']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.7.4 (CPython) - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[southpark.cc.com] s23e02-band-in-china: Downloading webpage
[southpark.cc.com] ac8de7f5-b355-11e9-9fb2-70df2f866ace: Downloading info
[southpark.cc.com] a5ce827a-b08c-412f-978a-f1df7426fca1: Extracting information
[southpark.cc.com] a5ce827a-b08c-412f-978a-f1df7426fca1: Downloading video urls
[southpark.cc.com] a5ce827a-b08c-412f-978a-f1df7426fca1: Downloading m3u8 information
[southpark.cc.com] eaeba7c4-dd00-4a91-8aad-4edeb33efe45: Extracting information
[southpark.cc.com] eaeba7c4-dd00-4a91-8aad-4edeb33efe45: Downloading video urls
[southpark.cc.com] eaeba7c4-dd00-4a91-8aad-4edeb33efe45: Downloading m3u8 information
[southpark.cc.com] 588e5e89-a369-4dbf-9cf7-b10e23bce6f8: Extracting information
[southpark.cc.com] 588e5e89-a369-4dbf-9cf7-b10e23bce6f8: Downloading video urls
[southpark.cc.com] 588e5e89-a369-4dbf-9cf7-b10e23bce6f8: Downloading m3u8 information
[download] Downloading playlist: Band in China
[southpark.cc.com] playlist Band in China: Collected 3 video ids (downloading 3 of them)
[download] Downloading video 1 of 3
[debug] Invoking downloader on 'https://dlvrsvc.mtvnservices.com/api/playlist/gsp.comedystor/com/sp/season-23/2302/acts/0/stream_1280x720_1199140_2162681544.m3u8?tk=st=1570759294~exp=1570773694~acl=/api/playlist/gsp.comedystor/com/sp/season-23/2302/acts/0/stream_1280x720_1199140_2162681544.m3u8*~hmac=31de189a9b31feab534027da404a9b6963c8ad1be1571aba311a9ec99ffbef17&account=southparkstudios.com&cdn=level3'
[download] South Park_October 02, 2019_23_2302_South Park 2302 - Band in China - Act 1-a5ce827a-b08c-412f-978a-f1df7426fca1.mp4 has already been downloaded
[download] 100% of 84.66MiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:South Park_October 02, 2019_23_2302_South Park 2302 - Band in China - Act 1-a5ce827a-b08c-412f-978a-f1df7426fca1.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "South Park_October 02, 2019_23_2302_South Park 2302 - Band in China - Act 1-a5ce827a-b08c-412f-978a-f1df7426fca1.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:South Park_October 02, 2019_23_2302_South Park 2302 - Band in China - Act 1-a5ce827a-b08c-412f-978a-f1df7426fca1.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:South Park_October 02, 2019_23_2302_South Park 2302 - Band in China - Act 1-a5ce827a-b08c-412f-978a-f1df7426fca1.temp.mp4'
[download] Downloading video 2 of 3
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1007, in process_ie_result
    extra_info=extra)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 862, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1635, in process_video_result
    expected=True)
youtube_dl.utils.ExtractorError: requested format not available```


## Description

youtube-dl will download the first of three video segments only. In times past all three would have been downloaded. I'm not sure why the playlist isn't being followed.

**Comment by dstftw** [comment]
>ERROR: requested format not available

**Comment by ballo** [comment]
Except it IS available on the web site. Again, this USED TO WORK

**Comment by robertg042** [comment]
It appears that if you pass a format as an option, youtube-dl will fail at first video in a playlist that does not have that format. There are at least two easy solutions:
- do not pass any format and youtube-dl will auto choose best format for each video
- download single videos (acts) by using playlist options like --playlist-start --playlist-end or --playlist-items
