### ISSUE TITLE
ERROR: Conversion failed! when disk is full

### ISSUE THREAD

**Issue by davidak** [ytdl-org/youtube-dl#22680]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2019.09.28** (2019.07.30, but the issue probably still exists)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
[davidak@X230:~]$ youtube-dl https://youtu.be/ptxzxEy-goI
[youtube] ptxzxEy-goI: Downloading webpage
[youtube] ptxzxEy-goI: Downloading video info webpage
[youtube] ptxzxEy-goI: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Fandom as an Alternative Network-ptxzxEy-goI.f137.mp4 has already been downloaded
[download] 100% of 615.10MiB
[download] Fandom as an Alternative Network-ptxzxEy-goI.f251.webm has already been downloaded
[download] 100% of 54.49MiB
[ffmpeg] Merging formats into "Fandom as an Alternative Network-ptxzxEy-goI.mkv"
ERROR: Conversion failed!
```

(i don't have a verbose log, but the issue is obvious)

## Description

When the disk is full (0 byte free), i get this error.

Please show helpful error message like when downloading.

`ERROR: unable to download video data: [Errno 28] No space left on device`

**Comment by davidak** [comment]
OK, now i have tested it with the latest version and have steps to reproduce!

### Steps to reproduce:

1. see how much free disk space you have

```
[davidak@X230:~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        386M     0  386M   0% /dev
tmpfs           3,8G  792M  3,0G  21% /dev/shm
tmpfs           1,9G  5,8M  1,9G   1% /run
tmpfs           3,8G  408K  3,8G   1% /run/wrappers
/dev/dm-2       220G  197G   12G  95% /
tmpfs           3,8G     0  3,8G   0% /sys/fs/cgroup
/dev/sda1       477M   94M  354M  21% /boot
tmpfs           3,8G   32M  3,8G   1% /tmp
tmpfs           771M  108K  771M   1% /run/user/1000
```

I have 12 GB on /.

2. fill the free space with zeroes

```
[davidak@X230:~]$ dd if=/dev/zero of=file.txt count=1024 bs=12024000
1024+0 records in
1024+0 records out
12312576000 bytes (12 GB, 11 GiB) copied, 75,8542 s, 162 MB/s
```

3. check the disk is fill

```
[davidak@X230:~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        386M     0  386M   0% /dev
tmpfs           3,8G  802M  3,0G  21% /dev/shm
tmpfs           1,9G  5,8M  1,9G   1% /run
tmpfs           3,8G  408K  3,8G   1% /run/wrappers
/dev/dm-2       220G  209G     0 100% /
tmpfs           3,8G     0  3,8G   0% /sys/fs/cgroup
/dev/sda1       477M   94M  354M  21% /boot
tmpfs           3,8G   32M  3,8G   1% /tmp
tmpfs           771M   96K  771M   1% /run/user/1000
```

avail should be 0

3. execute command

the download fails first before conversion even starts...

the behavior here is that the download of one fragment fails because disk is full (clear error message) and it is skipped, next fragment is downloaded and fails also... it might be better to directly fail when disk is full

```
[davidak@X230:~]$ youtube-dl --verbose https://youtu.be/ptxzxEy-goI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://youtu.be/ptxzxEy-goI']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.29
[debug] Lazy loading extractors enabled
[debug] Python version 3.7.5 (CPython) - Linux-4.19.80-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] ptxzxEy-goI: Downloading webpage
[youtube] ptxzxEy-goI: Downloading video info webpage
[youtube] ptxzxEy-goI: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1572752126/ei/nva9XeH4HY2d1wLjkbqgCA/ip/77.21.70.136/id/a6dc73c44cbe8282/source/youtube/requiressl/yes/playback_host/r1---sn-5hnedn7z.googlevideo.com/mm/31%2C29/mn/sn-5hnedn7z%2Csn-5hne6nsr/ms/au%2Crdu/mv/m/mvi/0/pl/24/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/996250/mt/1572730436/fvip/1/fexp/23842630/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Citag/sig/ALgxI2wwRQIgc4a_eDA267RizH9Wy28Zb4Kczw3PHJAxT9fvoinVbTUCIQC3I-q0KLXGklEEEpfC0BXh4ioFdeb8rCYwRNcKN22pFg%3D%3D/lsparams/playback_host%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AHylml4wRQIgMKanjV_IHIOfis3FGxS_irLUHFJMxaMDupHEv7J2F5oCIQCrIKJrUSrB0lG1hc_RoeQCAD_Sfj__7CJFlmfTinJ_kA%3D%3D'
[dashsegments] Total fragments: 744
[download] Destination: Fandom as an Alternative Network-ptxzxEy-goI.f137.mp4
[download]   0.3% of ~363.63MiB at  5.91MiB/s ETA 12:04

ERROR: unable to write data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 265, in download
    ctx.stream.write(data_block)
OSError: [Errno 28] No space left on device

[download] Skipping fragment 4...
[download]   0.5% of ~311.29MiB at 646.50KiB/s ETA 09:59

ERROR: unable to write data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 265, in download
    ctx.stream.write(data_block)
OSError: [Errno 28] No space left on device

[download] Skipping fragment 5...
[download]   0.5% of ~312.33MiB at 607.81KiB/s ETA 11:45

ERROR: unable to write data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 265, in download
    ctx.stream.write(data_block)
OSError: [Errno 28] No space left on device

[download] Skipping fragment 6...
[download]   0.5% of ~313.02MiB at 512.40KiB/s ETA 13:30

ERROR: unable to write data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 265, in download
    ctx.stream.write(data_block)
OSError: [Errno 28] No space left on device

[download] Skipping fragment 7...
[download]   0.5% of ~318.67MiB at 550.51KiB/s ETA 15:14

ERROR: unable to write data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 265, in download
    ctx.stream.write(data_block)
OSError: [Errno 28] No space left on device

[download] Skipping fragment 8...
[download]   0.5% of ~324.51MiB at 583.03KiB/s ETA 17:08

ERROR: unable to write data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 265, in download
    ctx.stream.write(data_block)
OSError: [Errno 28] No space left on device

[download] Skipping fragment 9...
[download]   0.4% of ~338.95MiB at 664.43KiB/s ETA 19:55

ERROR: unable to write data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 265, in download
    ctx.stream.write(data_block)
OSError: [Errno 28] No space left on device

[download] Skipping fragment 10...
[download]   0.4% of ~328.07MiB at 338.93KiB/s ETA 21:03

ERROR: unable to write data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 265, in download
    ctx.stream.write(data_block)
OSError: [Errno 28] No space left on device

[download] Skipping fragment 11...
[download]   0.5% of ~320.00MiB at 450.74KiB/s ETA 23:05

ERROR: unable to write data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 265, in download
    ctx.stream.write(data_block)
OSError: [Errno 28] No space left on device

[download] Skipping fragment 12...
[download]   0.5% of ~316.71MiB at 696.23KiB/s ETA 24:18

ERROR: unable to write data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 265, in download
    ctx.stream.write(data_block)
OSError: [Errno 28] No space left on device

[download] Skipping fragment 13...
[download]   0.5% of ~321.32MiB at 780.34KiB/s ETA 26:31

ERROR: unable to write data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 265, in download
    ctx.stream.write(data_block)
OSError: [Errno 28] No space left on device

[download] Skipping fragment 14...
[download]   0.4% of ~332.98MiB at 553.22KiB/s ETA 29:09

ERROR: unable to write data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 265, in download
    ctx.stream.write(data_block)
OSError: [Errno 28] No space left on device

[download] Skipping fragment 15...
[download]   0.5% of ~304.89MiB at 398.12KiB/s ETA 28:25

ERROR: unable to write data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 265, in download
    ctx.stream.write(data_block)
OSError: [Errno 28] No space left on device

[download] Skipping fragment 16...
[download]   0.5% of ~316.05MiB at 550.46KiB/s ETA 31:03

ERROR: unable to write data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 265, in download
    ctx.stream.write(data_block)
OSError: [Errno 28] No space left on device

[download] Skipping fragment 17...
[download]   0.5% of ~309.89MiB at 485.04KiB/s ETA 31:56

ERROR: unable to write data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 265, in download
    ctx.stream.write(data_block)
OSError: [Errno 28] No space left on device

[download] Skipping fragment 18...
[download]   0.4% of ~341.45MiB at 506.11KiB/s ETA 36:58

ERROR: unable to write data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 265, in download
    ctx.stream.write(data_block)
OSError: [Errno 28] No space left on device

[download] Skipping fragment 19...
[download]   0.5% of ~321.15MiB at 573.99KiB/s ETA 36:22

ERROR: unable to write data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 265, in download
    ctx.stream.write(data_block)
OSError: [Errno 28] No space left on device

[download] Skipping fragment 20...
[download]   0.5% of ~320.76MiB at 516.62KiB/s ETA 38:06

ERROR: unable to write data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 265, in download
    ctx.stream.write(data_block)
OSError: [Errno 28] No space left on device

[download] Skipping fragment 21...
[download]   0.5% of ~211.38MiB at  6.03MiB/s ETA 04:59ERROR: unable to download video data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1919, in process_info
    partial_success = dl(fname, new_info)
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1864, in dl
    return fd.download(name, info)
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/dash.py", line 51, in real_download
    self._append_fragment(ctx, frag_content)
  File "/nix/store/2k66s3rzla435f1zmcymx9cfpzs9w11p-python3.7-youtube-dl-2019.10.29/lib/python3.7/site-packages/youtube_dl/downloader/fragment.py", line 114, in _append_fragment
    ctx['dest_stream'].write(frag_content)
OSError: [Errno 28] No space left on device
```
