### ISSUE TITLE
Unable to download video from vidbom.com 

### ISSUE THREAD

**Issue by Medow** [ytdl-org/youtube-dl#22695]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl https://www.vidbom.com/rdyku4pjbufy.html -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.vidbom.com/rdyku4pjbufy.html', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-54-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: phantomjs 2.1.1
[debug] Proxy map: {}
[XFileShare] rdyku4pjbufy: Downloading webpage
ERROR: Unable to extract packed code; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/xfileshare.py", line 202, in _real_extract
    webpage, 'packed code'))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract packed code; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I am trying to download files from  vidbom.com , https://www.vidbom.com/rdyku4pjbufy.html as an example. The video work very well from the browser but youtube-dl doesn't able to extract links.
P.S: Most videos website site that use xvideosharing video script is not working.

**Comment by Medow** [comment]
@remitamine , would you please let me know the duplicated issue URL so i can find the solution?
Thanks.
