### ISSUE TITLE
[YouTube] Conversion fail on encrypted video/audio files

### ISSUE THREAD

**Issue by RuneMagle** [ytdl-org/youtube-dl#22700]
### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
C:\Users\Desktop\youtube-dl>youtube-dl.exe -f 225+329 --all-subs --convert-subs srt https://www.youtube.com/watch?v=QavMsSB-H0E --username PRIVATE--password PRIVATE -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '225+329', '--all-subs', '--convert-subs', 'srt', 'https://www.youtube.com/watch?v=QavMsSB-H0E', '--username', 'PRIVATE', '--password', 'PRIVATE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-94099-gdd662bbdd2, ffprobe N-94099-gdd662bbdd2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
[youtube] Checking cookie
[youtube] QavMsSB-H0E: Downloading webpage
[youtube] QavMsSB-H0E: Downloading video info webpage
[youtube] {146} signature length 113, html5 player vflNSW9LL
[youtube] {226} signature length 113, html5 player vflNSW9LL
[youtube] {227} signature length 113, html5 player vflNSW9LL
[youtube] {275} signature length 109, html5 player vflNSW9LL
[youtube] {359} signature length 113, html5 player vflNSW9LL
[youtube] {360} signature length 113, html5 player vflNSW9LL
[youtube] {145} signature length 109, html5 player vflNSW9LL
[youtube] {224} signature length 113, html5 player vflNSW9LL
[youtube] {225} signature length 109, html5 player vflNSW9LL
[youtube] {274} signature length 109, html5 player vflNSW9LL
[youtube] {357} signature length 113, html5 player vflNSW9LL
[youtube] {358} signature length 113, html5 player vflNSW9LL
[youtube] {144} signature length 109, html5 player vflNSW9LL
[youtube] {222} signature length 113, html5 player vflNSW9LL
[youtube] {223} signature length 113, html5 player vflNSW9LL
[youtube] {273} signature length 113, html5 player vflNSW9LL
[youtube] {317} signature length 113, html5 player vflNSW9LL
[youtube] {318} signature length 109, html5 player vflNSW9LL
[youtube] {143} signature length 109, html5 player vflNSW9LL
[youtube] {280} signature length 109, html5 player vflNSW9LL
[youtube] {142} signature length 113, html5 player vflNSW9LL
[youtube] {279} signature length 109, html5 player vflNSW9LL
[youtube] {161} signature length 113, html5 player vflNSW9LL
[youtube] {148} signature length 113, html5 player vflNSW9LL
[youtube] {149} signature length 113, html5 player vflNSW9LL
[youtube] {150} signature length 109, html5 player vflNSW9LL
[youtube] {261} signature length 109, html5 player vflNSW9LL
[youtube] {326} signature length 113, html5 player vflNSW9LL
[youtube] {329} signature length 113, html5 player vflNSW9LL
[youtube] {350} signature length 113, html5 player vflNSW9LL
[youtube] {351} signature length 113, html5 player vflNSW9LL
[youtube] {352} signature length 113, html5 player vflNSW9LL
[youtube] {381} signature length 113, html5 player vflNSW9LL
[youtube] QavMsSB-H0E: Downloading MPD manifest
[info] Writing video subtitles to: Chapter Fifty-Eight - 'In Memoriam'-QavMsSB-H0E.en.vtt
[debug] Invoking downloader on 'https://r4---sn-4pcp5q3-j2ie.googlevideo.com/videoplayback?expire=1571024724&ei=9JqjXcuyI5jF1gKT2oWwDw&ip=5.186.125.16&id=o-AELOtvO8eQMa49lujzhUsIfGNU9rAau3kUDQhELUZO1z&itag=225&aitags=142%2C143%2C144%2C145%2C146%2C161%2C222%2C223%2C224%2C225%2C226%2C227%2C273%2C274%2C275%2C279%2C280%2C317%2C318%2C357%2C358%2C359%2C360&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-4pcp5q3-j2ie%2Csn-5hne6nsr&ms=au%2Crdu&mv=m&mvi=3&pl=21&ctier=A&pfa=5&gcr=dk&initcwndbps=1962500&hightc=yes&mime=video%2Fmp4&gir=yes&clen=1061594088&dur=2528.609&lmt=1570634707938274&mt=1571002957&fvip=4&keepalive=yes&fexp=23842630&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cctier%2Cpfa%2Cgcr%2Chightc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgHss2SBqzcGTARtgReutfgwZfgvPHg4iPx8J8WT-1UjACIQC28KFAsIcasCLiD7gX__A4X4-AkRCpdj8r4v3BGJ76dg%3D%3D&sig=ALgxI2wwRAIgF7w22zjBtbl8EPSI8avLbkiFt-sqWAVD-QSWKBHaZ30CIGiv76PD2eOROnzv0OmUlzwMNtnxModFV4txFB9LziY2&ratebypass=yes'
[download] Destination: Chapter Fifty-Eight - 'In Memoriam'-QavMsSB-H0E.f225.mp4
[download] 100% of 1012.42MiB in 01:40
[debug] Invoking downloader on 'https://r4---sn-4pcp5q3-j2ie.googlevideo.com/videoplayback?expire=1571024724&ei=9JqjXcuyI5jF1gKT2oWwDw&ip=5.186.125.16&id=o-AELOtvO8eQMa49lujzhUsIfGNU9rAau3kUDQhELUZO1z&itag=329&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-4pcp5q3-j2ie%2Csn-5hne6nsr&ms=au%2Crdu&mv=m&mvi=3&pl=21&ctier=A&pfa=5&gcr=dk&initcwndbps=1962500&hightc=yes&mime=audio%2Fmp4&gir=yes&clen=122048695&dur=2528.704&lmt=1570634634937181&mt=1571002957&fvip=4&keepalive=yes&fexp=23842630&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cpfa%2Cgcr%2Chightc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgHss2SBqzcGTARtgReutfgwZfgvPHg4iPx8J8WT-1UjACIQC28KFAsIcasCLiD7gX__A4X4-AkRCpdj8r4v3BGJ76dg%3D%3D&sig=ALgxI2wwRQIhAJptnopTETjJtuve7GNwWx7mW6XQI5g2qFlCnQhT_JbNAiAhZ95LvqrIyPnLXAcELuPLc6vDHdRv1vTEdveojdWUrg==&ratebypass=yes'
[download] Destination: Chapter Fifty-Eight - 'In Memoriam'-QavMsSB-H0E.f329.m4a
[download] 100% of 116.39MiB in 00:14
[ffmpeg] Merging formats into "Chapter Fifty-Eight - 'In Memoriam'-QavMsSB-H0E.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Chapter Fifty-Eight - 'In Memoriam'-QavMsSB-H0E.f225.mp4" -i "file:Chapter Fifty-Eight - 'In Memoriam'-QavMsSB-H0E.f329.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:Chapter Fifty-Eight - 'In Memoriam'-QavMsSB-H0E.temp.mp4"
ERROR: Conversion failed!
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\YoutubeDL.py", line 2064, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\postprocessor\ffmpeg.py", line 512, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
...
<end of log>
```

---
- Single video: https://www.youtube.com/watch?v=QavMsSB-H0E

---

### Description of *issue*
Conversion fails. And using MediaInfo, I can see the files have an encryption. Is it possible to fix this with a decryption key?

**Comment by dstftw** [comment]
You must provide credentials for any work on this.

**Comment by RuneMagle** [comment]
What's the mail I can send the credentials to? :)

**Comment by RuneMagle** [comment]
Nevermind, found your email on your profile. I have sent my YT credentials on which I have purchased the episode. :)
