### ISSUE TITLE
[aenetworks] ERROR: Unable to download webpage: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by StevenDTX** [ytdl-org/youtube-dl#22714]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2019.09.28**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
E:\>c:\support\youtube-dl.exe --verbose https://www.aetv.com/shows/60-days-in-narcoland/season-1/episode-9
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.aetv.com/shows/60-days-in-narcoland/season-1/episode-9']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-92986-gaceb9131c1, ffprobe N-92986-gaceb9131c1, rtmpdump 2.4
[debug] Proxy map: {}
[aenetworks] 60-days-in-narcoland/season-1/episode-9: Downloading webpage
[aenetworks] 1603939907827: Downloading JSON metadata
[aenetworks] 1603939907827: Retrieving Authorization Token
ERROR: Unable to download webpage: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

## Description

ERROR: Unable to download webpage: HTTP Error 400: Bad Request (caused by HTTPError());

**Comment by remitamine** [comment]
try with a clean cache(`--rm-cache-dir`) and repost the verbose output.

**Comment by StevenDTX** [comment]
```
E:\>c:\support\youtube-dl.exe --verbose https://www.aetv.com/shows/60-days-in-narcoland/season-1/episode-9 --rm-cache-dir
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.aetv.com/shows/60-days-in-narcoland/season-1/episode-9', '--rm-cache-dir']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-92986-gaceb9131c1, ffprobe N-92986-gaceb9131c1, rtmpdump 2.4
[debug] Proxy map: {}
Removing cache dir C:\Users\steven/.cache\youtube-dl ..
[aenetworks] 60-days-in-narcoland/season-1/episode-9: Downloading webpage
[aenetworks] 1603939907827: Downloading JSON metadata
ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\extractor\aenetworks.py", line 188, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\extractor\adobepass.py", line 1414, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\extractor\adobepass.py", line 1379, in raise_mvpd_required
youtube_dl.utils.ExtractorError: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
```

I pass it a valid MSO login, and I get the same error 400.

**Comment by remitamine** [comment]
post the verbose output with clean cache and **while you're using MSO options**.

**Comment by StevenDTX** [comment]
```
E:\>c:\support\youtube-dl.exe --verbose https://www.aetv.com/shows/60-days-in-narcoland/season-1/episode-9 --rm-cache-dir --ap-mso Charter_Direct --ap-username <username> --ap-password <password>
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.aetv.com/shows/60-days-in-narcoland/season-1/episode-9', '--rm-cache-dir', '--ap-mso', 'Charter_Direct', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-92986-gaceb9131c1, ffprobe N-92986-gaceb9131c1, rtmpdump 2.4
[debug] Proxy map: {}
Removing cache dir C:\Users\steven/.cache\youtube-dl ..
[aenetworks] 60-days-in-narcoland/season-1/episode-9: Downloading webpage
[aenetworks] 1603939907827: Downloading JSON metadata
[aenetworks] 1603939907827: Downloading Provider Redirect Page
ERROR: Unable to download webpage: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

Thanks @remitamine

**Comment by StevenDTX** [comment]
@remitamine 

I saw your recent update to the aenetworks extractor. Unfortunately, that didn't address this issue.  I can provide a login to help fix this issue.

Thanks.

**Comment by remitamine** [comment]
Does Charter Direct support Auto-Login and if so, do you get automatically Loged when you access the videos in the browser, if it's an Auto-Login issue then i'm afraid that i can't help otherwise you can contact me via e-mail(address in my profile).

**Comment by StevenDTX** [comment]
> 
> 
> Does Charter Direct support Auto-Login and if so, do you get automatically LoggedIn when you access the videos in the browser, if it's an Auto-Login issue then i'm afraid that i can't help otherwise you can contact me via e-mail(address in my profile).

No, it does prompt for a login.  I will contact you via email.

**Comment by remitamine** [comment]
so, this is issue is invalid(using an MSO ID unsupported by the network), for Spectrum there is an open PR for it.
