### ISSUE TITLE
[YouTube] Some CPPCon 2019 Videos Fail to Download

### ISSUE THREAD

**Issue by RandomDSdevel** [ytdl-org/youtube-dl#22712]
## Checklist

- [x] I'm reporting broken site support.  
- [x] I've verified that I'm running youtube-dl version **2019.09.28**.  
- [x] I've checked that all provided URLs are alive and playable in a browser.  
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped.  
- [x] I've searched the bugtracker for similar issues including closed ones.  

## Verbose log

```
…$ ~/bin/tmp/youtube-dl -v "https://www.youtube.com/watch?v=IAdLwUXRUvg" -o "%(title)s.%(ext)s" # I currently have some…nasty outstanding package-management issues, so this a a temporary `youtube-dl` installation fetched straight from GitHub, hence its path.  
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=IAdLwUXRUvg', u'-o', u'%(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.15 (CPython) - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[youtube] IAdLwUXRUvg: Downloading webpage
[youtube] IAdLwUXRUvg: Downloading video info webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r4---sn-vgqsenek.googlevideo.com/videoplayback?expire=1571101015&ei=98SkXb6RNJPxwQH8kabYBw&ip=2601%3A803%3A4300%3A6%3Af97d%3A477e%3Ae370%3Ae8e&id=o-ALCPaP5DS9x5PtQ9LVQWrq9IFoMReEVdaTRHCNDvex-x&itag=22&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-vgqsenek%2Csn-p5qs7n7l&ms=au%2Conr&mv=m&mvi=3&pl=26&initcwndbps=1817500&mime=video%2Fmp4&ratebypass=yes&dur=3142.147&lmt=1569528067583926&mt=1571079346&fvip=6&fexp=23842630&beids=9466586&c=WEB&txp=3416222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRAIgVHkSAtlBBLsPyzyukybAkKFu-oS26BCDCK6keO4towgCIDi2WvyEroIApvq7wfl_9osP9FVanf2jNSMu9Bgxp2bN&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgXZPwcCKq5w2fRwOCBH-TAQLFB2T3S_DmiLIuMaZEmmQCIGgA_heqpx8gTtarvnzvYxe6kYUQNtMhtJVwgG9mKTe5'
[download] Destination: CppCon 2019 - Miro Knejp “Non-conforming C++ - the Secrets the Committee Is Hiding From You”.mp4
[download]   0.6% of 200.34MiB at  1.49MiB/s ETA 02:13[download] Got server HTTP error: Downloaded 1200091 bytes, expected 210076867 bytes. Retrying (attempt 1 of 10)...


ERROR: Did not get any data blocks
Traceback (most recent call last):
  File "/Users/zadmin/bin/tmp/youtube-dl/youtube_dl/downloader/http.py", line 342, in real_download
    return download()
  File "/Users/zadmin/bin/tmp/youtube-dl/youtube_dl/downloader/http.py", line 320, in download
    retry(err)
  File "/Users/zadmin/bin/tmp/youtube-dl/youtube_dl/downloader/http.py", line 225, in retry
    raise RetryDownload(e)
RetryDownload

…$ ~/bin/tmp/youtube-dl -v "https://www.youtube.com/watch?v=Lb3hlLlHTrs" -o "%(title)s.%(ext)s" # Again, the reason for this non-standard `youtube-dl` invocation path is the same as I stated above.  
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=Lb3hlLlHTrs', u'-o', u'%(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.15 (CPython) - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Lb3hlLlHTrs: Downloading webpage
[youtube] Lb3hlLlHTrs: Downloading video info webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r5---sn-vgqsdn7s.googlevideo.com/videoplayback?expire=1571101059&ei=I8WkXbXwHISWDr3HhvgE&ip=2601%3A803%3A4300%3A6%3Af97d%3A477e%3Ae370%3Ae8e&id=o-ACE_yRPuj3AxCeEJULcu1ySH6XN0ef4VAkTWKeucyuBs&itag=22&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-vgqsdn7s%2Csn-p5qlsndd&ms=au%2Conr&mv=m&mvi=4&pl=26&initcwndbps=1772500&mime=video%2Fmp4&ratebypass=yes&dur=1883.440&lmt=1569518454784847&mt=1571079346&fvip=5&fexp=23842630&c=WEB&txp=3416222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRAIgLTRj6DrJYUHr2FvssF4DBWreLHQNaZdbWtZ3_84B8L4CIHkc48NsHMwCuorOVF_jF8SVZvcnjgH4yjbtVe_XUZ-R&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhAJb43sNiTk56eQ4gAqy1LMhzWHLwaclH2qXWXu9_UsgFAiBkRjjnt_KrONY_AFhXT6jMEiAJAEjp1dquk18VRVfu8A%3D%3D'
[download] Destination: CppCon 2019 - Robert Schumacher “How to Herd 1,000 Libraries”.mp4
[download]   0.5% of 125.74MiB at  1.66MiB/s ETA 01:15[download] Got server HTTP error: Downloaded 690851 bytes, expected 131850173 bytes. Retrying (attempt 1 of 10)...


ERROR: Did not get any data blocks
Traceback (most recent call last):
  File "/Users/zadmin/bin/tmp/youtube-dl/youtube_dl/downloader/http.py", line 342, in real_download
    return download()
  File "/Users/zadmin/bin/tmp/youtube-dl/youtube_dl/downloader/http.py", line 320, in download
    retry(err)
  File "/Users/zadmin/bin/tmp/youtube-dl/youtube_dl/downloader/http.py", line 225, in retry
    raise RetryDownload(e)
RetryDownload

```

## Description

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Some videos from [CPPCon](https://cppcon.org) 2019 fail to download properly.  Those I've tried and had trouble with so far include:  

 - [CppCon 2019:  Miro Knejp “Non-conforming C++:  the Secrets the Committee Is Hiding From You”](https://www.youtube.com/watch?v=IAdLwUXRUvg)
 - [CppCon 2019:  Robert Schumacher “How to Herd 1,000 Libraries”](https://www.youtube.com/watch?v=Lb3hlLlHTrs)

**Comment by dstftw** [comment]
Server side Youtube error for format 22.

**Comment by RandomDSdevel** [comment]
@dstftw:  Hmm, is my issue a duplicate of #20296…?
