### ISSUE TITLE
Pornhub ERROR: Unable to extract encoded url

### ISSUE THREAD

**Issue by lorenzyet** [ytdl-org/youtube-dl#22737]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.10.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\Lorenzo\Downloads\youtube-dl-master>youtube-dl https://it.pornhub.com/model/rosieandalena/videos --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://it.pornhub.com/model/rosieandalena/videos', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.07.30
[debug] Python version 3.7.4 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg N-95216-ge6625ca41f, ffprobe N-95216-ge6625ca41f
[debug] Proxy map: {}
[PornHubPagedVideoList] model/rosieandalena/videos: Downloading page 1
[PornHubPagedVideoList] model/rosieandalena/videos: Downloading page 2
[PornHubPagedVideoList] model/rosieandalena/videos: Downloading page 3
[PornHubPagedVideoList] model/rosieandalena/videos: Downloading page 4
[download] Downloading playlist: model/rosieandalena/videos
[PornHubPagedVideoList] playlist model/rosieandalena/videos: Collected 139 video ids (downloading 139 of them)
[download] Downloading video 1 of 139
[PornHub] ph5d3c7aaaa4642: Downloading pc webpage
[PornHub] ph5d3c7aaaa4642: Downloading tv webpage
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Lorenzo\AppData\Roaming\Python\Python37\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Lorenzo\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Lorenzo\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\pornhub.py", line 235, in _real_extract
    'encoded url').split(';')
  File "C:\Users\Lorenzo\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I can't download any video from pornhub, I tryed with single video, playlist and channel but nothing to do

**Comment by lorenzyet** [comment]
Now with single videos it works

**Comment by a62527776a** [comment]
我也有这个情况

**Comment by Kattus** [comment]
I'm getting the exact same issue but only if setting `--cookies`.

**Comment by a62527776a** [comment]
> I'm getting the exact same issue but only if setting `--cookies`.

我将pornhub的链接单独处理了

**Comment by ntstatic** [comment]
same issue

**Comment by dstftw** [comment]
>Fan Only Video
