### ISSUE TITLE
Subtitle Not Embedding 

### ISSUE THREAD

**Issue by ExodusHour** [ytdl-org/youtube-dl#22753]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.10.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
D:\Kpop\Youtube-dl\Japan Youtube Channel>youtube-dl --config-location youtube-dl.conf
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['-i', '-o', 'D:\\Kpop\\Twice\\Twice Youtube\\Twice Japan Youtube Channel/%(upload_date)s - %(title)s', '--download-archive', 'youtube-dl-archive.txt', '-a', 'youtube-dl-channels.txt', '-f', '272+140/315+140/313+140/308+14/271+140/299+140/137+140/298+140/136+140/135+140/134+140/133+140/bestvideo+bestaudio', '--merge-output-format', 'mp4', '--write-thumbnail', '--embed-thumbnail', '--add-metadata', '--write-description', '--write-sub', '--all-subs', '--embed-subs', '-v']
[debug] Command-line args: ['--config-location', 'youtube-dl.conf']
[debug] Batch file urls: ['https://www.youtube.com/channel/UCCRb6nYKaT8tzLA8CwDdUtw']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.10.16
[debug] Python version 3.7.4 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg N-95171-g6ca3d34ff8, ffprobe N-95171-g6ca3d34ff8
[debug] Proxy map: {}
[youtube:channel] UCCRb6nYKaT8tzLA8CwDdUtw: Downloading channel page
[youtube:playlist] UUCRb6nYKaT8tzLA8CwDdUtw: Downloading webpage
[download] Downloading playlist: Uploads from TWICE JAPAN OFFICIAL YouTube Channel
[youtube:playlist] playlist Uploads from TWICE JAPAN OFFICIAL YouTube Channel: Downloading 48 videos
[download] Downloading video 1 of 48
[download] TWICE 「Fake & True」 Music Video has already been recorded in archive
[download] Downloading video 2 of 48
[download] TWICE 「Fake & True」 Teaser #2 has already been recorded in archive
[download] Downloading video 3 of 48
[download] TWICE 「Fake & True」 Teaser #1 has already been recorded in archive
[download] Downloading video 4 of 48
[download] TWICE POPUP STORE "Twaii's Shop" Teaser has already been recorded in archive
[download] Downloading video 5 of 48
[download] TWICE「HAPPY HAPPY」Dance Making Video In Hawaii has already been recorded in archive
[download] Downloading video 6 of 48
[download] TWICE「HAPPY HAPPY」「Breakthrough」Information Video has already been recorded in archive
[download] Downloading video 7 of 48
[download] TWICE「Breakthrough」Music Video has already been recorded in archive
[download] Downloading video 8 of 48
[download] TWICE「HAPPY HAPPY」Music Video has already been recorded in archive
[download] Downloading video 9 of 48
[download] TWICE「HAPPY HAPPY」Teaser has already been recorded in archive
[download] Downloading video 10 of 48
[download] TWICE「Breakthrough」Teaser has already been recorded in archive
[download] Downloading video 11 of 48
[download] TWICE JAPAN 4th & 5th SINGLE Release！ has already been recorded in archive
[download] Downloading video 12 of 48
[download] TWICE『#TWICE2』Information Video has already been recorded in archive
[download] Downloading video 13 of 48
[download] 「TWICE LOVELYS」introduction has already been recorded in archive
[download] Downloading video 14 of 48
[download] TWICE『#TWICE2 -Japanese ver.-』Spoiler Video has already been recorded in archive
[download] Downloading video 15 of 48
[download] TWICE「What is Love? -Japanese ver.-」Music Video has already been recorded in archive
[download] Downloading video 16 of 48
[youtube] N7MKlhS2ysU: Downloading webpage
[youtube] N7MKlhS2ysU: Downloading video info webpage
[youtube] {18} signature length 102, html5 player vflWNgP-p
[youtube] {137} signature length 102, html5 player vflWNgP-p
[youtube] {248} signature length 106, html5 player vflWNgP-p
[youtube] {136} signature length 106, html5 player vflWNgP-p
[youtube] {247} signature length 106, html5 player vflWNgP-p
[youtube] {398} signature length 106, html5 player vflWNgP-p
[youtube] {135} signature length 106, html5 player vflWNgP-p
[youtube] {244} signature length 102, html5 player vflWNgP-p
[youtube] {397} signature length 106, html5 player vflWNgP-p
[youtube] {134} signature length 106, html5 player vflWNgP-p
[youtube] {243} signature length 106, html5 player vflWNgP-p
[youtube] {396} signature length 106, html5 player vflWNgP-p
[youtube] {133} signature length 106, html5 player vflWNgP-p
[youtube] {242} signature length 106, html5 player vflWNgP-p
[youtube] {395} signature length 106, html5 player vflWNgP-p
[youtube] {160} signature length 106, html5 player vflWNgP-p
[youtube] {278} signature length 102, html5 player vflWNgP-p
[youtube] {394} signature length 106, html5 player vflWNgP-p
[youtube] {140} signature length 102, html5 player vflWNgP-p
[youtube] {249} signature length 102, html5 player vflWNgP-p
[youtube] {250} signature length 102, html5 player vflWNgP-p
[youtube] {251} signature length 106, html5 player vflWNgP-p
[info] Writing video description to: D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel\20190110 - TWICE「LIKEY -Japanese ver.-」Music Video.description
[info] Writing video subtitles to: D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel\20190110 - TWICE「LIKEY -Japanese ver.zh-Hant.vtt
[info] Writing video subtitles to: D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel\20190110 - TWICE「LIKEY -Japanese ver.en.vtt
[info] Writing video subtitles to: D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel\20190110 - TWICE「LIKEY -Japanese ver.ko.vtt
[youtube] N7MKlhS2ysU: Downloading thumbnail ...
[youtube] N7MKlhS2ysU: Writing thumbnail to: D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel\20190110 - TWICE「LIKEY -Japanese ver.jpg
[debug] Invoking downloader on 'https://r4---sn-vgqsknes.googlevideo.com/videoplayback?expire=1571361837&ei=zb-oXczMBYOpkwbI5IG4Bg&ip=2600%3A6c46%3A7880%3Ad4%3A8c70%3Ac967%3A5dd3%3Ac5f7&id=o-AI73TaxNLHRoXbG4FnWBQWGvydagDUqAfbajm8yMVQb8&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-vgqsknes%2Csn-vgqs7nlz&ms=au%2Crdu&mv=m&mvi=3&pl=37&initcwndbps=2017500&mime=video%2Fmp4&gir=yes&clen=104343266&dur=217.584&lmt=1556976586257695&mt=1571340060&fvip=4&keepalive=yes&fexp=23842630&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhAIubej2phqgukTSt_pDIzR6OzmjMKpFFTp6qWNd1lbXdAiEAmtqGndxWFWBGFB6PQH6-ZFr5M5VU2ltTU0Vm3pQuFnE%3D&sig=ALgxI2wwRAIgfEDthgG3c0eyWwUN8Rg1C-EGIiKDcYsStNj9nBQsofQCIBi57ucCZ_wnoRdg-k0JUpwudJC4NfqtI6RszNM-ErDN&ratebypass=yes'
[download] Destination: D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel\20190110 - TWICE「LIKEY -Japanese ver.- 」Music Video.f137
[download] 100% of 99.51MiB in 00:12
[debug] Invoking downloader on 'https://r4---sn-vgqsknes.googlevideo.com/videoplayback?expire=1571361837&ei=zb-oXczMBYOpkwbI5IG4Bg&ip=2600%3A6c46%3A7880%3Ad4%3A8c70%3Ac967%3A5dd3%3Ac5f7&id=o-AI73TaxNLHRoXbG4FnWBQWGvydagDUqAfbajm8yMVQb8&itag=140&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-vgqsknes%2Csn-vgqs7nlz&ms=au%2Crdu&mv=m&mvi=3&pl=37&initcwndbps=2017500&mime=audio%2Fmp4&gir=yes&clen=3522982&dur=217.640&lmt=1556975628086726&mt=1571340060&fvip=4&keepalive=yes&fexp=23842630&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhAIubej2phqgukTSt_pDIzR6OzmjMKpFFTp6qWNd1lbXdAiEAmtqGndxWFWBGFB6PQH6-ZFr5M5VU2ltTU0Vm3pQuFnE%3D&sig=ALgxI2wwRAIgZqK1p8snIdFqQ9yeb4oJTUUWSCQXvc4Bl563FUx8GDoCIH4DDXRqNg64SWDc62AJiz60I8MAx03w4069BaEV3lV-&ratebypass=yes'
[download] Destination: D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel\20190110 - TWICE「LIKEY -Japanese ver.- 」Music Video.f140
[download] 100% of 3.36MiB in 00:00
[ffmpeg] Merging formats into "D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel\20190110 - TWICE「LIKEY -Japanese ver.-」Music Video.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel\20190110 - TWICE「LIKEY -Japanese ver.-」Music Video.f137" -i "file:D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel\20190110 - TWICE「LIKEY -Japanese ver.-」Music Video.f140" -c copy -map "0:v:0" -map "1:a:0" "file:D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel\20190110 - TWICE「LIKEY -Japanese ver.-」Music Video.temp.mp4"
Deleting original file D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel\20190110 - TWICE「LIKEY -Japanese ver.-」Music Video.f137 (pass -k to keep)
Deleting original file D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel\20190110 - TWICE「LIKEY -Japanese ver.-」Music Video.f140 (pass -k to keep)
[ffmpeg] Adding metadata to 'D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel\20190110 - TWICE「LIKEY -Japanese ver.-」Music Video.mp4'
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel\20190110 - TWICE「LIKEY -Japanese ver.-」Music Video.mp4" -c copy -metadata "title=TWICE   LIKEY JPNver MASTER" -metadata "date=20190110" -metadata "description=TWICE 2nd BEST ALBUM『#TWICE2』
2019.03.06(wed) Release！




【いい音楽で一度、素晴らしいパフォーマンスで二度魅了させる】と言う意味を持つ、Asia No.1最強
ガールズグループTWICE。

日本デビューを果たした2017年には社会現象となった「TT -Japanese ver.-」と同楽曲での紅白歌合戦出場、「One More Time」から のオリコンウィークリーランキング1位獲得と海外アーティストとしての記録更新、そして、そのままの勢いで2018年も「Candy Pop」が40万枚、さらに「Wake Me Up」が50万枚を突破、海外アーティストとしての新記録突破の快挙を続け、10代の女性を中心に大ブレイクし、さらに進化を続けている。同年9月12日にリリースした、待望のJAPAN 1st ALBUM『BDZ』（読み：ビー・ディー・ゼット）はオ リコンウィークリーアルバムランキング、デジタルランキグ共に初登場1位を獲得。これによりTWICEは、CDシングル・アルバム両ランキングでの1位を達成。海外⼥性アーティストによるシングル・アルバム双方での1位獲得が史上5組目となった。『BDZ』は現在出荷枚数が42万枚を突破しプラチナディスクに認定された。オリコンの月間アルバムランキングでも堂々1位を獲得。「BDZ」をひっさげたアリーナツアーでは2019年春にドームツアーの開催を緊急発表！本国デビューから最速での東京ドーム公演を実施、海外アーティストとして日本史上最速記録更新の快挙を成し遂げる！！！※１
さらに韓国でデビューしたガールズグループとしては初のドームツアーの実施となる！！※１
※１　2019年1月現在 、当社調べ

アルバムのリード曲「BDZ」はYouTubeでのMUSIC VIDEOの再生回数をすでに3,000万回を目前に、アルバムも大ヒットし同作品のリパッケージアルバムも12月にリリース！
第60回日本レコード大賞、優秀作品賞に「Wake Me Up」が受賞し、レコード大賞特別バージョンのパフォーマンスも番組にて披露、さらに第69回紅白歌合戦に2年連続で出場など、TWICEらしく、そして“ブルドーザー（BDZ）”のごとく突き進んだ。
2019年春にもドームツアーが決定し、勢いとどまることを知らないTWICEが3月6日（水）に『デビューにして最強ベストアルバム「#TWICE」』の第二弾作品「#TWICE2」（ハッシュタグ トゥワイス ツー）をリリースすることが決定した！
「#TWICE2」は韓国でリリースしたアルバムリード曲「LIKEY」から「Heart Shaker」「What is Love?」「Dance The Night Away」「YES or YES」の5曲とその全ての日本語バージョン5曲の計10曲が収録！
「#TWICE」とは世界中のONCE（TWICEのファンの総称）とTWICEがつながっているキーワードであり、TWICE9人の魅力を「#TWICE」でカテゴライズしてSNS拡散することで、デビューから今までTWICEを支えてくれているキーワードでもある。TWICE9人とファンの夢であったドーム公演を控え、「TWICEの第一章」の作品としての大事なアルバムでもある。


---------------------------------
TWICE OFFICIAL FANCLUB ONCE JAPAN
http://oncejapan.com

TWICE JAPAN OFFICIAL SITE
http://www.twicejapan.com

TWICE JAPAN OFFICIAL TWITTER
https://twitter.com/jypetwice_japan

TWICE JAPAN OFFICIAL INSTAGRAM
https://www.instagram.com/jypetwice_japan/

TWICE JAPAN OFFICIAL YouTube Channel
https://www.youtube.com/c/twicejapanofficial
---------------------------------" -metadata "comment=TWICE 2nd BEST ALBUM『#TWICE2』
2019.03.06(wed) Release！




【いい音楽で一度、素晴らしいパフォーマンスで二度魅了させる】と言う意味を持つ、Asia No.1最強
ガールズグループTWICE。

日本デビューを果たした2017年には社会現象となった「TT -Japanese ver.-」と同楽曲での紅白歌合戦出場、「One More Time」から のオリコンウィークリーランキング1位獲得と海外アーティストとしての記録更新、そして、そのままの勢いで2018年も「Candy Pop」が40万枚、さらに「Wake Me Up」が50万枚を突破、海外アーティストとしての新記録突破の快挙を続け、10代の女性を中心に大ブレイクし、さらに進化を続けている。同年9月12日にリリースした、待望のJAPAN 1st ALBUM『BDZ』（読み：ビー・ディー・ゼット）はオ リコンウィークリーアルバムランキング、デジタルランキグ共に初登場1位を獲得。これによりTWICEは、CDシングル・アルバム両ランキングでの1位を達成。海外⼥性アーティストによるシングル・アルバム双方での1位獲得が史上5組目となった。『BDZ』は現在出荷枚数が42万枚を突破しプラチナディスクに認定された。オリコンの月間アルバムランキングでも堂々1位を獲得。「BDZ」をひっさげたアリーナツアーでは2019年春にドームツアーの開催を緊急発表！本国デビューから最速での東京ドーム公演を実施、海外アーティストとして日本史上最速記録更新の快挙を成し遂げる！！！※１
さらに韓国でデビューしたガールズグループとしては初のドームツアーの実施となる！！※１
※１　2019年1月現在 、当社調べ

アルバムのリード曲「BDZ」はYouTubeでのMUSIC VIDEOの再生回数をすでに3,000万回を目前に、アルバムも大ヒットし同作品のリパッケージアルバムも12月にリリース！
第60回日本レコード大賞、優秀作品賞に「Wake Me Up」が受賞し、レコード大賞特別バージョンのパフォーマンスも番組にて披露、さらに第69回紅白歌合戦に2年連続で出場など、TWICEらしく、そして“ブルドーザー（BDZ）”のごとく突き進んだ。
2019年春にもドームツアーが決定し、勢いとどまることを知らないTWICEが3月6日（水）に『デビューにして最強ベストアルバム「#TWICE」』の第二弾作品「#TWICE2」（ハッシュタグ トゥワイス ツー）をリリースすることが決定した！
「#TWICE2」は韓国でリリースしたアルバムリード曲「LIKEY」から「Heart Shaker」「What is Love?」「Dance The Night Away」「YES or YES」の5曲とその全ての日本語バージョン5曲の計10曲が収録！
「#TWICE」とは世界中のONCE（TWICEのファンの総称）とTWICEがつながっているキーワードであり、TWICE9人の魅力を「#TWICE」でカテゴライズしてSNS拡散することで、デビューから今までTWICEを支えてくれているキーワードでもある。TWICE9人とファンの夢であったドーム公演を控え、「TWICEの第一章」の作品としての大事なアルバムでもある。


---------------------------------
TWICE OFFICIAL FANCLUB ONCE JAPAN
http://oncejapan.com

TWICE JAPAN OFFICIAL SITE
http://www.twicejapan.com

TWICE JAPAN OFFICIAL TWITTER
https://twitter.com/jypetwice_japan

TWICE JAPAN OFFICIAL INSTAGRAM
https://www.instagram.com/jypetwice_japan/

TWICE JAPAN OFFICIAL YouTube Channel
https://www.youtube.com/c/twicejapanofficial
---------------------------------" -metadata "purl=https://www.youtube.com/watch?v=N7MKlhS2ysU" -metadata "artist=TWICE JAPAN OFFICIAL YouTube Channel" "file:D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel\20190110 - TWICE「LIKEY -Japanese ver.-」Music Video.temp.mp4"
[ffmpeg] Embedding subtitles in 'D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel\20190110 - TWICE「LIKEY -Japanese ver.-」Music Video.mp4'
ERROR: [WinError 2] The system cannot find the file specified: 'D:\\Kpop\\Twice\\Twice Youtube\\Twice Japan Youtube Channel\\20190110 - TWICE「LIKEY -Japanese ver.-」Music Video.zh-Hant.vtt'
Traceback (most recent call last):
  File "c:\users\joshj\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\users\joshj\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 862, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "c:\users\joshj\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1643, in process_video_result
    self.process_info(new_info)
  File "c:\users\joshj\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1999, in process_info
    self.post_process(filename, info_dict)
  File "c:\users\joshj\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2064, in post_process
    files_to_delete, info = pp.run(info)
  File "c:\users\joshj\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 426, in run
    self.run_ffmpeg_multiple_files(input_files, temp_filename, opts)
  File "c:\users\joshj\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 210, in run_ffmpeg_multiple_files
    os.stat(encodeFilename(path)).st_mtime for path in input_paths)
  File "c:\users\joshj\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 210, in <genexpr>
    os.stat(encodeFilename(path)).st_mtime for path in input_paths)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\Kpop\\Twice\\Twice Youtube\\Twice Japan Youtube Channel\\20190110 - TWICE「LIKEY -Japanese ver.-」Music Video.zh-Hant.vtt'

[download] Downloading video 17 of 48
[download] TWICE「BDZ -Repackage-」Information Video has already been recorded in archive
[download] Downloading video 18 of 48
[download] TWICE DOME TOUR 2019開催決定！ has already been recorded in archive
[download] Downloading video 19 of 48
[download] TWICE JAPAN SEASON’S GREETINGS 2019 “TWICE AIRLINES” Teaser 2 has already been recorded in archive
[download] Downloading video 20 of 48
[download] TWICE「STAY BY MY SIDE」Making Music Video has already been recorded in archive
[download] Downloading video 21 of 48
[download] TWICE 2019年ドームツアー開催決定！ has already been recorded in archive
[download] Downloading video 22 of 48
[download] TWICE JAPAN SEASON’S GREETINGS 2019 “TWICE AIRLINES” Teaser has already been recorded in archive
[download] Downloading video 23 of 48
[download] TWICE「BDZ」with ONCE has already been recorded in archive
[download] Downloading video 24 of 48
[download] TWICE「Be as ONE」Document Video has already been recorded in archive
[download] Downloading video 25 of 48
[download] TWICE『BDZ』Spoiler Video has already been recorded in archive
[download] Downloading video 26 of 48
[download] TWICE「BDZ」Information Video has already been recorded in archive
[download] Downloading video 27 of 48
[download] TWICE「BDZ」Music Video has already been recorded in archive
[download] Downloading video 28 of 48
[download] TWICE JAPAN DEBUT 1周年 感謝コメント has already been recorded in archive
[download] Downloading video 29 of 48
[download] TWICE「I WANT YOU BACK」Music Video has already been recorded in archive
[download] Downloading video 30 of 48
[download] TWICE 2018 秋 告知映像 has already been recorded in archive
[download] Downloading video 31 of 48
[download] TWICE「Wake Me Up」Information Video has already been recorded in archive
[download] Downloading video 32 of 48
[download] TWICE「Wake Me Up」Music Video has already been recorded in archive
[download] Downloading video 33 of 48
[download] TWICE「BRAND NEW GIRL」Music Video has already been recorded in archive
[download] Downloading video 34 of 48
[download] TWICE「Candy Pop」Dance Practice ver. has already been recorded in archive
[download] Downloading video 35 of 48
[download] TWICE「Candy Pop」Information Video has already been recorded in archive
[download] Downloading video 36 of 48
[download] TWICE「Candy Pop」Music Video has already been recorded in archive
[download] Downloading video 37 of 48
[download] TWICE SPOT has already been recorded in archive
[download] Downloading video 38 of 48
[download] TWICE DEBUT SHOWCASE “Touchdown in JAPAN” Digest Video has already been recorded in archive
[download] Downloading video 39 of 48
[download] TWICE SEASON'S GREETINGS 2018 "TWISTAR" has already been recorded in archive
[download] Downloading video 40 of 48
[download] TWICE「One More Time」Music Video has already been recorded in archive
[download] Downloading video 41 of 48
[download] TWICE「One More Time」TEASER 2 has already been recorded in archive
[download] Downloading video 42 of 48
[download] TWICE「One More Time」 Information MOVIE has already been recorded in archive
[download] Downloading video 43 of 48
[download] TWICE「One More Time」TEASER has already been recorded in archive
[download] Downloading video 44 of 48
[download] TWICE「#TWICE」SPOT MOVIE has already been recorded in archive
[download] Downloading video 45 of 48
[download] TWICE「TT -Japanese ver.-」Music Video has already been recorded in archive
[download] Downloading video 46 of 48
[download] TWICE「SIGNAL -Japanese ver.-」Music Video（Short ver.） has already been recorded in archive
[download] Downloading video 47 of 48
[download] TWICE- #TWICE 「-Japanese ver.-」SPOILER MOVIE has already been recorded in archive
[download] Downloading video 48 of 48
[download] TWICE「Like OOH-AHH -Japanese ver.-」Making Music Video （short ver.） has already been recorded in archive
[download] Finished downloading playlist: Uploads from TWICE JAPAN OFFICIAL YouTube Channel
```

## Description

WRITE DESCRIPTION HERE

When downloading this channel https://www.youtube.com/channel/UCCRb6nYKaT8tzLA8CwDdUtw from a batch file one of the videos has an error.

This is my config file
```
-i
-o "D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel/%(upload_date)s - %(title)s"

--download-archive youtube-dl-archive.txt
-a youtube-dl-channels.txt

-f 272+140/315+140/313+140/308+14/271+140/299+140/137+140/298+140/136+140/135+140/134+140/133+140/bestvideo+bestaudio --merge-output-format mp4

--write-thumbnail
--embed-thumbnail

--add-metadata
--write-description

--write-sub
--all-subs
--embed-subs

-v
```
When downloading the whole channel all the other subs embed fine and are deleted after they are embedded. When it gets to this video the subtitle are downloaded but when attempting to embed the subs the files aren't found but I can see them in the folder.

When downloading the video by itself with "youtube-dl -f 137+140 --merge-output-format mp4 --write-thumbnail --embed-thumbnail --add-metadata --write-description --write-sub --all-subs --embed-subs https://www.youtube.com/watch?v=N7MKlhS2ysU" the sub files are found and are embedded.

Out of the 48 videos on the channel this is the only video I'm having problems with.

**Comment by dstftw** [comment]
For any work on this you must provide reproducible environment.

**Comment by ExodusHour** [comment]
If you can't reproduce it do you have any idea what could be going wrong on my end?
