### ISSUE TITLE
Subtitle Not Embedding 

### ISSUE THREAD

**Issue by ExodusHour** [ytdl-org/youtube-dl#22751]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.10.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.10.16
[debug] Python version 3.7.4 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg N-95171-g6ca3d34ff8, ffprobe N-95171-g6ca3d34ff8
[debug] Proxy map: {}
```

## Description

WRITE DESCRIPTION HERE

When downloading this channel https://www.youtube.com/channel/UCCRb6nYKaT8tzLA8CwDdUtw from a batch file one of the videos has an error.
```
[ffmpeg] Embedding subtitles in 'D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel\20190110 - TWICE「LIKEY -Japanese ver.-」Music Video.mp4'
ERROR: [WinError 2] The system cannot find the file specified: 'D:\\Kpop\\Twice\\Twice Youtube\\Twice Japan Youtube Channel\\20190110 - TWICE「LIKEY -Japanese ver.-」Music Video.zh-Hant.vtt'
Traceback (most recent call last):
  File "c:\users\joshj\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\users\joshj\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 862, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "c:\users\joshj\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1643, in process_video_result
    self.process_info(new_info)
  File "c:\users\joshj\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1999, in process_info
    self.post_process(filename, info_dict)
  File "c:\users\joshj\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2064, in post_process
    files_to_delete, info = pp.run(info)
  File "c:\users\joshj\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 426, in run
    self.run_ffmpeg_multiple_files(input_files, temp_filename, opts)
  File "c:\users\joshj\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 210, in run_ffmpeg_multiple_files
    os.stat(encodeFilename(path)).st_mtime for path in input_paths)
  File "c:\users\joshj\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 210, in <genexpr>
    os.stat(encodeFilename(path)).st_mtime for path in input_paths)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\Kpop\\Twice\\Twice Youtube\\Twice Japan Youtube Channel\\20190110 - TWICE「LIKEY -Japanese ver.-」Music Video.zh-Hant.vtt'
```
This is my config file
```
-i
-o "D:\Kpop\Twice\Twice Youtube\Twice Japan Youtube Channel/%(upload_date)s - %(title)s"

--download-archive youtube-dl-archive.txt
-a youtube-dl-channels.txt

-f 272+140/315+140/313+140/308+14/271+140/299+140/137+140/298+140/136+140/135+140/134+140/133+140/bestvideo+bestaudio --merge-output-format mp4

--write-thumbnail
--embed-thumbnail

--add-metadata
--write-description

--write-sub
--all-subs
--embed-subs

-v
```
When downloading the whole channel all the other subs embed fine and are deleted after they are embedded. When it gets to this video the subtitle are downloaded but when attempting to embed the subs the files aren't found but I can see them in the folder.

When downloading the video by itself with "youtube-dl -f 137+140 --merge-output-format mp4 --write-thumbnail --embed-thumbnail --add-metadata --write-description --write-sub --all-subs --embed-subs https://www.youtube.com/watch?v=N7MKlhS2ysU" the sub files are found and are embedded.

Out of the 48 videos on the channel this is the only video I'm having problems with.

**Comment by dstftw** [comment]
Post the **full verbose** output.
