### ISSUE TITLE
ERROR: YouTube said: Unable to extract video data

### ISSUE THREAD

**Issue by Yagyansh** [ytdl-org/youtube-dl#22758]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Till yesterday everything was working fine, but since yesterday I have been getting this error while downloading any video. Its happening on 2 of my servers out of 3.

Here is the output that I am getting.

yagyansh@VER-BLR-LT1868:~$ youtube-dl --verbose --dump-json --format=18 https://www.youtube.com/watch?v=SEP_Pn82ZU8 >> testdump
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--dump-json', '--format=18', 'https://www.youtube.com/watch?v=SEP_Pn82ZU8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.16
[debug] Python version 3.6.8 (CPython) - Linux-4.15.0-20-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: SEP_Pn82ZU8: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1836, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: SEP_Pn82ZU8: YouTube said: Unable to extract video data

Any idea why this is happening?

**Comment by Yagyansh** [comment]
Duplicate.

**Comment by Yagyansh** [comment]
I know its a duplicate but haven't been able to find a solution. Please point me towards the right Issue number.
