### ISSUE TITLE
fetching from https://www.bnnbloomberg.ca/video stopped working

### ISSUE THREAD

**Issue by MMADave** [ytdl-org/youtube-dl#22762]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.10.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe --verbose https://www.bnnbloomberg.ca/video/asia-growth-clima
te-war-on-talent-among-key-trends-for-next-decade-ontario-teachers-ceo~1807790
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.bnnbloomberg.ca/video/asia
-growth-climate-war-on-talent-among-key-trends-for-next-decade-ontario-teachers-
ceo~1807790']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.10.16
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-75563-g235381e, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 99.233.4.138 (CA) as X-Forwarded-For.
[9c9media] 1807790: Downloading JSON metadata
ERROR: 1807790: Failed to parse JSON  (caused by ValueError('Expecting value: li
ne 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug .
Make sure you are using the latest version; type  youtube-dl -U  to update. Be s
ure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfc5s43
s4\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfc5s43
s4\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfc5s43
s4\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfc5s43
s4\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfc5s43
s4\build\youtube_dl\extractor\ninecninemedia.py", line 25, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfc5s43
s4\build\youtube_dl\extractor\common.py", line 892, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfc5s43
s4\build\youtube_dl\extractor\common.py", line 876, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfc5s43
s4\build\youtube_dl\extractor\common.py", line 903, in _parse_json
youtube_dl.utils.ExtractorError: 1807790: Failed to parse JSON  (caused by Value
Error('Expecting value: line 1 column 1 (char 0)',)); please report this issue o
n https://yt-dl.org/bug . Make sure you are using the latest version; type  yout
ube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and inc
lude its complete output.
```

## Description

used to work, now it doesn't.

**Comment by remitamine** [comment]
works fine the latest version:
```
youtube-dl https://www.bnnbloomberg.ca/video/asia-growth-climate-war-on-talent-among-key-trends-for-next-decade-ontario-teachers-ceo~1807790
[9c9media] 1807790: Downloading JSON metadata
[9c9media] 1807790: Downloading JSON metadata
[9c9media] 1807790: Downloading m3u8 information
[9c9media] 1807790: Downloading f4m manifest
[9c9media] 1807790: Downloading MPD manifest
[download] Destination: Asia growth, climate, 'war on talent' among key trends for next decade - Ontario Teachers' CEO-1807790.fhls-1856.mp4
...
```
