### ISSUE TITLE
Disney Now Extractor Error

### ISSUE THREAD

**Issue by pierce3215** [ytdl-org/youtube-dl#22763]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.10.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Command-line args: ['--verbose', '--ap-mso', 'mid030', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://disneynow.com/shows/tots/season-01/episode-01-youve-gotta-be-kitten-me-whale-hello-there/vdka10353']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.10.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2019-10-18-feaec3b, ffprobe git-2019-10-18-feaec3b
[debug] Proxy map: {}
[Go] vdka10353: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('video',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfc5s43s4\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfc5s43s4\build\youtube_dl\extractor\go.py", line 122, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfc5s43s4\build\youtube_dl\extractor\go.py", line 87, in _extract_videos
KeyError: 'video'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfc5s43s4\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfc5s43s4\build\youtube_dl\extractor\go.py", line 122, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfc5s43s4\build\youtube_dl\extractor\go.py", line 87, in _extract_videos
KeyError: 'video'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfc5s43s4\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfc5s43s4\build\youtube_dl\extractor\common.py", line 543, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('video',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I am trying to use youtube-dl to download videos off of DisneyNow using the code listed above and getting several errors. Is there a current issue with Disney or is this more related to my code. I have input the mso, username, password, site, etc.

Thanks

**Comment by user-3003150** [comment]
Hey! Your site is incomplete! You have not pasted the link correctly. It's too short. Try the link again, and it should work!
