### ISSUE TITLE
[YouTube] Unable to download from youtube playlist

### ISSUE THREAD

**Issue by harroguk** [ytdl-org/youtube-dl#22794]
## Checklist
- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2019.10.22**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
PS I:\scripts\Powershell> $youTubeUser = "[Snipped]"
PS I:\scripts\Powershell> $youTubePassword = "[SnippedToo]"
PS I:\scripts\Powershell> $downloadlocation = "I:\TV\YouTube\WatchLater - s01e%(epoch)s - %(title)s.%(ext)s"
PS I:\scripts\Powershell> $downloadthis = "https://www.youtube.com/playlist?list=WL"
PS I:\scripts\Powershell> youtube-dl `
>> --username $youTubeUser `
>> --password $youTubePassword `
>> --yes-playlist `
>> --verbose `
>> --output $downloadlocation `
>> $downloadthis
>>
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--yes-playlist', '--verbose', '--output', 'I:\\TV\\YouTube\\WatchLater - s01e%(epoch)s - %(title)s.%(ext)s', 'https://www.youtube.com/playlist?list=WL']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.10.22
[debug] Python version 3.7.2 (CPython) - Windows-2008ServerR2-6.1.7601-SP1
[debug] exe versions: ffmpeg N-92103-gebc3d04b8d, ffprobe N-92103-gebc3d04b8d
[debug] Proxy map: {}
[youtube:watchlater] Downloading login page
[youtube:watchlater] Looking up account info
[youtube:watchlater] Logging in
WARNING: Unable to extract result entry
[youtube:watchlater] WL: Downloading webpage
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "c:\installedprograms\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\installedprograms\python37\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\installedprograms\python37\lib\site-packages\youtube_dl\extractor\youtube.py", line 3227, in _real_extract
    _, playlist = self._extract_playlist('WL')
  File "c:\installedprograms\python37\lib\site-packages\youtube_dl\extractor\youtube.py", line 2730, in _extract_playlist
    raise ExtractorError(message, expected=True)
youtube_dl.utils.ExtractorError: This playlist does not exist.
```

## Description
It looks like I am not logging into YouTube Correctly as my Watch Later Playlist is not available. The playlist exists and has videos on it when browsing it in YouTube.

**Comment by Joshfindit** [comment]
@dstftw Duplicate of which please? Having this issue.

**Comment by harroguk** [comment]
> @dstftw Duplicate of which please? Having this issue.

I never found the duplicate issue. I solved the issue by using cookie based authentication.

**Comment by Joshfindit** [comment]
@harroguk Thank you. Such a frustrating that it's hard to find the 'master issue' in the pile of dulicates.
After searching for a while I *think* they're marked as duplicates of the 'Youtube: authentication failure' issue linked in the reply I made on 'Youtube : Can't download my "liked" playlist'
