### ISSUE TITLE
[theplatform.eu] video from DigitalTheatre.com

### ISSUE THREAD

**Issue by lankque** [ytdl-org/youtube-dl#22798]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.10.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: http://player.theplatform.eu/p/lCpzgC/dt-vp/embed/select/media/bcl_3606

## Description

```
C:\Users\Ardis>youtube-dl -v http://player.theplatform.eu/p/lCpzgC/dt-p/embed/select/media/bcl_3606
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://player.theplatform.eu/p/lCpzgC/dt-vp/embed/select/media/bcl_3606']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.10.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[generic] bcl_3606: Requesting header
WARNING: Could not send HEAD request to http://player.theplatform.eu/p/lCpzgC/dt-vp/embed/select/media/bcl_3606: HTTP Error 405: Method Not Allowed
[generic] bcl_3606: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] bcl_3606: Extracting information
[generic] bcl_3606?autoPlay=false: Requesting header
WARNING: Could not send HEAD request to https://player.theplatform.eu/p/lCpzgC/dt-vp/embed/select/media/bcl_3606?autoPlay=false: HTTP Error 405: Method Not Allowed
[generic] bcl_3606?autoPlay=false: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] bcl_3606?autoPlay=false: Extracting information
ERROR: Unsupported URL: https://player.theplatform.eu/p/lCpzgC/dt-vp/embed/select/media/bcl_3606?autoPlay=false
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\generic.py", line 3353, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: `https://player.theplatform.eu/p/lCpzgC/dt-vp/embed/select/media/bcl_3606?autoPlay=false
```

**Comment by runch-randa** [comment]
I'm getting the same "Unsupported URL" issue when trying to download https://player.theplatform.eu/p/lCpzgC/dt-vp/embed/select/media/bcl_3720, and will likely get the same error regardless of the link. The video file works fine on the browser.
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://player.theplatform.eu/p/lCpzgC/dt-vp/embed/select/media/bcl_3720']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.6.9 (CPython) - Linux-5.3.0-46-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6-0ubuntu0.18.04.1, ffprobe 3.4.6-0ubuntu0.18.04.1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[generic] bcl_3720: Requesting header
WARNING: Could not send HEAD request to https://player.theplatform.eu/p/lCpzgC/dt-vp/embed/select/media/bcl_3720: HTTP Error 405: Method Not Allowed
[generic] bcl_3720: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] bcl_3720: Extracting information
[generic] bcl_3720?autoPlay=false: Requesting header
WARNING: Could not send HEAD request to https://player.theplatform.eu/p/lCpzgC/dt-vp/embed/select/media/bcl_3720?autoPlay=false: HTTP Error 405: Method Not Allowed
[generic] bcl_3720?autoPlay=false: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] bcl_3720?autoPlay=false: Extracting information
ERROR: Unsupported URL: https://player.theplatform.eu/p/lCpzgC/dt-vp/embed/select/media/bcl_3720?autoPlay=false
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/generic.py", line 3151, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://player.theplatform.eu/p/lCpzgC/dt-vp/embed/select/media/bcl_3720?autoPlay=false
```
theplatform.eu part of the long list of supported sites, so I'm not quite sure why it's saying it's not.
