### ISSUE TITLE
[PornHub] 2 Persistent Errors

### ISSUE THREAD

**Issue by ytdlph** [ytdl-org/youtube-dl#22807]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.10.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--proxy', 'socks5://127.0.0.1:9050', '--max-downloads', '5', '--dump-json', 'https://www.pornhub.com/model/mini-diva/videos/upload']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.22
[debug] Python version 3.7.4 (CPython) - Linux-5.2.5-1-ARCH-aarch64-with-arch
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, phantomjs 2.1.1
[debug] Proxy map: {'http': 'socks5://127.0.0.1:9050', 'https': 'socks5://127.0.0.1:9050'}
ERROR: Unable to download webpage: Remote end closed connection without response (caused by RemoteDisconnected('Remote end closed connection without response')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/site-packages/youtube_dl/utils.py", line 2724, in https_open
    req, **kwargs)
  File "/usr/lib/python3.7/urllib/request.py", line 1320, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"

---------------------------------------------------------------------------------------------------------------------

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--proxy', 'socks5://127.0.0.1:9050', '--max-downloads', '5', '--dump-json', 'https://www.pornhub.com/model/siasiberia/videos/upload', '--verbose', '--write-pages']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.22
[debug] Python version 3.7.4 (CPython) - Linux-5.2.5-1-ARCH-aarch64-with-arch
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, phantomjs 2.1.1
[debug] Proxy map: {'http': 'socks5://127.0.0.1:9050', 'https': 'socks5://127.0.0.1:9050'}
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/pornhub.py", line 235, in _real_extract
    'encoded url').split(';')
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I'm using youtube-dl to create a PornHub client that fetches videos over TOR for me and every single URL gives those 2 errors. I'm not using youtube-dl embedded, I'm using os.subprocess (seems like the options I'm using doesn't work together in embedded mode, I think it has to do with the download count when using both max downloads and skip download since I only want the first 5 video's JSON, but this is for another issue). Here is the URL list (all of them fail, sometimes with the first error, sometimes with the second):
https://www.pornhub.com/model/coffincouple
https://www.pornhub.com/model/jade_skyee
https://www.pornhub.com/model/littlereislin
https://www.pornhub.com/model/lyra-fae
https://www.pornhub.com/model/marcelin-abadir
https://www.pornhub.com/model/mattiedoll
https://www.pornhub.com/model/mini-diva
https://www.pornhub.com/model/rosieandalena
https://www.pornhub.com/model/siasiberia
https://www.pornhub.com/model/solazola
https://www.pornhub.com/model/tweetney
https://www.pornhub.com/pornstar/cherry-crush
https://www.pornhub.com/pornstar/elles
https://www.pornhub.com/pornstar/flora-rodgers
https://www.pornhub.com/pornstar/indigo-white
https://www.pornhub.com/pornstar/ivy-aura
https://www.pornhub.com/pornstar/leda-elizabeth
https://www.pornhub.com/pornstar/liz-vicious
https://www.pornhub.com/pornstar/lure-lady
https://www.pornhub.com/users/fioreholland1
Maybe PornHub is trying to avoid youtube-dl? Thanks.
Dumps here: https://anonymousfiles.io/PW1q5Njh/ (is it okay to be zipped?)

**Comment by dstftw** [comment]
It's pretty obvious that all free proxies are banned.
