### ISSUE TITLE
Playlist download bug

### ISSUE THREAD

**Issue by spiffzilla** [ytdl-org/youtube-dl#22802]
`youtube-dl --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s" https://www.youtube.com/playlist?list=OLAK5uy_ldqX73mbfNjVaJxIgB9NtGsOsFe_PlpBI
[youtube:playlist] OLAK5uy_ldqX73mbfNjVaJxIgB9NtGsOsFe_PlpBI: Downloading webpage
[download] Downloading playlist: Deva Premal's Healing Mantras
[youtube:playlist] playlist Deva Premal's Healing Mantras: Downloading 17 videos
[download] Downloading video 1 of 17
[youtube] Ugz-CVP6m44: Downloading webpage
[youtube] Ugz-CVP6m44: Downloading video info webpage
WARNING: Unable to extract video title
[youtube] Ugz-CVP6m44: Downloading js player vflrnurMS
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
shalafi@virtzilla:~/deva$ youtube-dl --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s" https://www.youtube.com/playlist?list=OLAK5uy_ldqX73mbfNjVaJxIgB9NtGsOsFe_PlpBI --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--extract-audio', u'--audio-format', u'mp3', u'-o', u'%(title)s.%(ext)s', u'https://www.youtube.com/playlist?list=OLAK5uy_ldqX73mbfNjVaJxIgB9NtGsOsFe_PlpBI', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-5-amd64-x86_64-with-debian-10.1
[debug] exe versions: avconv 4.1.4-1, avprobe 4.1.4-1, ffmpeg 4.1.4-1, ffprobe 4.1.4-1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] OLAK5uy_ldqX73mbfNjVaJxIgB9NtGsOsFe_PlpBI: Downloading webpage
[download] Downloading playlist: Deva Premal's Healing Mantras
[youtube:playlist] playlist Deva Premal's Healing Mantras: Downloading 17 videos
[download] Downloading video 1 of 17
[youtube] Ugz-CVP6m44: Downloading webpage
[youtube] Ugz-CVP6m44: Downloading video info webpage
WARNING: Unable to extract video title
[youtube] {18} signature length 109, html5 player vflrnurMS
[youtube] Ugz-CVP6m44: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vflrnurMS/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1989, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1352, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/home/shalafi/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

`

**Comment by Ben-Banso** [comment]
Hi @spiffzilla 
Please try to update first. I see that you're using a version from May. Very likely your problem was solved in a more recent version.

```
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-5-amd64-x86_64-with-debian-10.1
```

Please update the issue if the problem persist after the update.
