### ISSUE TITLE
youtube-dl error downloading from it.dplay.com

### ISSUE THREAD

**Issue by palmer1956** [ytdl-org/youtube-dl#22826]
error executing this command:

youtube-dl  https://it.dplay.com/nove/fake-la-fabbrica-delle-notizie/stagione-1-episodio-1-ferruccio-de-bortoli-nina-palmieri --verbose

output and standard error: 
 
[debug] Using fake IP 79.29.132.153 (IT) as X-Forwarded-For.
[DPlayIt] stagione-1-episodio-1-ferruccio-de-bortoli-nina-palmieri: Downloading webpage
[DPlayIt] stagione-1-episodio-1-ferruccio-de-bortoli-nina-palmieri: Downloading JSON metadata

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://it.dplay.com/nove/fake-la-fabbrica-delle-notizie/stagione-1-episodio-1-ferruccio-de-bortoli-nina-palmieri', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2019.10.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: An extractor error has occurred. (caused by KeyError('errors',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\dplay.py", line 326, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 892, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 870, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 660, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 645, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\dplay.py", line 333, in _real_extract
KeyError: 'errors'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\dplay.py", line 326, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 892, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 870, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 660, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 645, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\dplay.py", line 333, in _real_extract
KeyError: 'errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 543, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('errors',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

best regards. ep.

**Comment by fpusersuggest** [comment]
I have the same problem, I tried to downgrade it but I haven't solved it.

**Comment by felisucoibi** [comment]
Is hapening also with es.dplay.com

**Comment by Maryna3** [comment]
I've the same problem. I hope someone could help us

**Comment by mpercich** [comment]
Same problem here:

MacBook-Pro-13:michele$ youtube-dl https://it.dplay.com/nove/fratelli-di-crozza/stagione-3-episodio-17-del-18-ottobre-2019/ --output ~/Downloads/dplay/crozza_3_17.mp4 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://it.dplay.com/nove/fratelli-di-crozza/stagione-3-episodio-17-del-18-ottobre-2019/', u'--output', u'/Users/michele/Downloads/dplay/crozza_3_17.mp4', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.22
[debug] Python version 2.7.15 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 79.39.69.29 (IT) as X-Forwarded-For.
[DPlayIt] stagione-3-episodio-17-del-18-ottobre-2019: Downloading webpage
[DPlayIt] stagione-3-episodio-17-del-18-ottobre-2019: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError(u'errors',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dplay.py", line 333, in _real_extract
    error = info['errors'][0]
KeyError: u'errors'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 543, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'errors',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by fabiovin70** [comment]
Same problem here  :-(

**Comment by nestukh** [comment]
temporal workaround
(I'm not the dev maintaining the `dplay` extractor)

- open firefox
- go to the page of the video you'd like to download, e.g.
https://it.dplay.com/nove/fratelli-di-crozza/stagione-3-episodio-18-del-25-ottobre-2019/
- right click on page --> inspect Element (Q)
- Inspector is now open in the bottom half of the window, go to its 'Network' tab
- reload page (Inspector will remain open)
- search "mux_audio=true" (no quotes)
- a single "https://dplaysouth-vod.akamaized.net/dplaydni....." is now selected
- on its 'headers' tab on the right, copy the Request URL, something like "https://dplaysouth-vod.akamaized.net/dplaydni/98480/0/hls/9286577004.........."
- download it with a command like:

`youtube-dl -f mp4 "$LINK"`

full example:
`youtube-dl --ignore-errors --console-title --newline --force-ipv4 --sleep-interval 1 --max-sleep-interval 5 --add-header "Content-Language: en-us,en" --add-header "Accept-Language: en-us,en" --user-agent  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.39 (KHTML, like Gecko) Version/9.0 Safari/601.1.39" --retries 256 --socket-timeout 999 --prefer-ffmpeg --no-cache-dir --output "Fratelli di Crozza 2019-10-25.mp4" --continue -f "worst[format_id*=360]/best[height<=?360]" "https://dplaysouth-vod.akamaized.net/dplaydni/98480/0/hls/9286577004/playlist.m3u8?hdnts=st=1572077068~exp=1572163468~acl=/dplaydni/98480/0/hls/9286577004/*~hmac=25683bc9e6875c0af7a7c3b38f69a92f4a90a8286d24a18e904234c0b3427ea6&mux_audio=true"`

(cancel the _-f "worst[format_id*=360]/best[height<=?360]"_ switch for max video resolution)

(rename the _---output "Fratelli di Crozza 2019-10-25.mp4"_ switch with the proper video name)

there's probably some error with cookie replies, request tokens and stuff; usually they rename or rearrange json fields or something like it, it was the same problem with the old greasemonkey script

**Comment by felisucoibi** [comment]
If possible when fixed add es.dplay.com

**Comment by felisucoibi** [comment]
any news?
