### ISSUE TITLE
Videos on tatort.tube cannot be downloaded

### ISSUE THREAD

**Issue by habi** [ytdl-org/youtube-dl#22874]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.10.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
(base) anomalocaris:Downloads habi$ youtube-dl --version
2019.10.22
(base) anomalocaris:Downloads habi$ youtube-dl -v https://www.tatort.tube/Stream/Russisches-Roulette-377
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.tatort.tube/Stream/Russisches-Roulette-377']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.22
[debug] Python version 3.7.3 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] Russisches-Roulette-377: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Russisches-Roulette-377: Downloading webpage
[generic] Russisches-Roulette-377: Extracting information
[download] Downloading playlist: Russisches Roulette (1998) - Stream | Tatort.Tube - Alle Tatort-Folgen als Stream
[generic] playlist Russisches Roulette (1998) - Stream | Tatort.Tube - Alle Tatort-Folgen als Stream: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s.tatort.tube/377.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1925, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1864, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Users/habi/anaconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Users/habi/anaconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/habi/anaconda3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Users/habi/anaconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/habi/anaconda3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

(base) anomalocaris:Downloads habi$
```

## Description

About 20 years ago I was an extra in a Tatort.
This episode of the Tatort cannot be found in the ARD Mediathek anymore, but is streamable from https://www.tatort.tube/Stream/Russisches-Roulette-377 (on OS X 10.14.6 (18G103) with Safari Version 13.0.2 (14608.2.40.1.3) and Firefox 69.0.3 (64-bit).
But downloading a copy for safekeeping with `youtube-dl` doesn't work as seen in the verbose log above.
I also tried downloading *while* playing in the browser, but this also didn't help...

**Comment by dstftw** [comment]
youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).
