### ISSUE TITLE
Safari/O'Reilly Learning authentication issues

### ISSUE THREAD

**Issue by onthesafari** [ytdl-org/youtube-dl#22878]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.10.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-i', '-c', '-f', 'bestvideo[height<=480]+bestaudio/best[h
eight<=480]', '-o', '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', 'https://www.oreilly.com/library/view/hadoop-
fundamentals-livelessons/9780133392838', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.10.22
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-93626-gb272d5b9b6-sherpya, ffprobe N-93626-gb272d5b9b6-sherpya
[debug] Proxy map: {}
[safari:course] Downloading login page
[safari:course] Logging in
ERROR: None: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report t
his issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure
 to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py"
, line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py"
, line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\YoutubeDL.py", line
796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py"
, line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py"
, line 433, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\safari.py"
, line 30, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\safari.py"
, line 63, in _login
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py"
, line 876, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py"
, line 903, in _parse_json
youtube_dl.utils.ExtractorError: None: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (ch
ar 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube
-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

The login JSON data returns an incorrect value. Was working just fine around yesterday afternoon. Seems to have been changed.

**Comment by funky-monkey** [comment]
I tried this as well; the main O'Reilly site says that they are experiencing an outage due to the Californian fires.
