### ISSUE TITLE
'source_address': '0.0.0.0' causes failure to extract data

### ISSUE THREAD

**Issue by infowolfe** [ytdl-org/youtube-dl#22876]
## Checklist
- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2019.10.22**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log
```
freya:/dev/shm$ youtube-dl -v --source-address 192.168.1.114 https://www.youtube.com/watch?v=HtmkoL3Fz38
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--source-address', '192.168.1.114', 'https://www.youtube.com/watch?v=HtmkoL3Fz38']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.22
[debug] Python version 3.7.4 (CPython) - Linux-5.2.13-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] HtmkoL3Fz38: Downloading webpage
[youtube] HtmkoL3Fz38: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: HtmkoL3Fz38: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1836, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: HtmkoL3Fz38: YouTube said: Unable to extract video data


freya:/dev/shm$ youtube-dl -v https://www.youtube.com/watch?v=HtmkoL3Fz38
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=HtmkoL3Fz38']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.22
[debug] Python version 3.7.4 (CPython) - Linux-5.2.13-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] HtmkoL3Fz38: Downloading webpage
[youtube] HtmkoL3Fz38: Downloading video info webpage
[youtube] {18} signature length 103, html5 player vflsEMaQv
[youtube] {137} signature length 103, html5 player vflsEMaQv
[youtube] {248} signature length 103, html5 player vflsEMaQv
[youtube] {299} signature length 107, html5 player vflsEMaQv
[youtube] {303} signature length 103, html5 player vflsEMaQv
[youtube] {136} signature length 107, html5 player vflsEMaQv
[youtube] {247} signature length 103, html5 player vflsEMaQv
[youtube] {298} signature length 107, html5 player vflsEMaQv
[youtube] {302} signature length 107, html5 player vflsEMaQv
[youtube] {135} signature length 107, html5 player vflsEMaQv
[youtube] {244} signature length 107, html5 player vflsEMaQv
[youtube] {134} signature length 103, html5 player vflsEMaQv
[youtube] {243} signature length 103, html5 player vflsEMaQv
[youtube] {133} signature length 107, html5 player vflsEMaQv
[youtube] {242} signature length 107, html5 player vflsEMaQv
[youtube] {160} signature length 103, html5 player vflsEMaQv
[youtube] {278} signature length 107, html5 player vflsEMaQv
[youtube] {140} signature length 103, html5 player vflsEMaQv
[youtube] {249} signature length 107, html5 player vflsEMaQv
[youtube] {250} signature length 107, html5 player vflsEMaQv
[youtube] {251} signature length 103, html5 player vflsEMaQv
[debug] Default format spec: bestvideo+bestaudio/best
[download] [House] - Mr FijiWiji - Yours Truly (feat. Danyka Nadeau) (Aaron Jackson Remix) [Monstercat Release]-HtmkoL3Fz38.webm has already been downloaded and merged
```

## Description
`--source-address 0.0.0.0` / `--source-address 192.168.1.114` (the ipv4 address of the calling machine)
or:
```
import youtube_dl

ytdl_format_options = {
    'source_address': '0.0.0.0',
}

with youtube_dl.YoutubeDL(ytdl_format_options) as ydl:
    ydl.download(['https://www.youtube.com/watch?v=HtmkoL3Fz38'])
```

Will cause erroneous error 429's.

**Comment by infowolfe** [comment]
Invalid, related to ipv6 vs ipv4 rate limiting by ip by youtube.
