### ISSUE TITLE
BROKEN SITE : abc7.com

### ISSUE THREAD

**Issue by AdamDanischewski** [ytdl-org/youtube-dl#22905]
## Checklist
- [X ] I'm reporting a broken site support
- [ X] I've verified that I'm running youtube-dl version **2019.10.29**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
$ youtube-dl -v "https://abc7.com/dashcam-video-shows-start-of-getty-fire/5657318/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://abc7.com/dashcam-video-shows-start-of-getty-fire/5657318/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.29
[debug] Python version 2.7.17rc1 (CPython) - Linux-5.0.0-29-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] 5657318: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 5657318: Downloading webpage
[generic] 5657318: Extracting information
ERROR: Unsupported URL: https://abc7.com/dashcam-video-shows-start-of-getty-fire/5657318/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2373, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: syntax error: line 2, column 8
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3354, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://abc7.com/dashcam-video-shows-start-of-getty-fire/5657318/
```

**Comment by PlaceboPRS** [comment]
It's working, try this: 

youtube-dl.exe --no-check-certificate https://content-aeuf1.uplynk.com/eb7f1b60255c44779aa973deebe065b7/g.m3u8?pbs=4ce68b2f02b64ff393ab22697a1971ac

**Comment by AdamDanischewski** [comment]
You used the m3u8 - you can get the file with ffmpeg once you have that. The video URL doesn't work for me. 
```
$ youtube-dl --no-check-certificate "https://abc7.com/dashcam-video-shows-start-of-getty-fire/5657318"
[generic] 5657318: Requesting header
[redirect] Following redirect to https://abc7.com/dashcam-video-shows-start-of-getty-fire/5657318/
[generic] 5657318: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 5657318: Downloading webpage
[generic] 5657318: Extracting information
ERROR: Unsupported URL: https://abc7.com/dashcam-video-shows-start-of-getty-fire/5657318/
```
`youtube-dl --version
2019.10.29`

**Comment by PlaceboPRS** [comment]
Yeah I get the URLs via Chrome extensions "Stream Video Downloader" or "Video DownloadHelper", I guess I'm so used to doing it that way as I use Streamlink with 10 download threads most of the time because it's so much faster :)
