### ISSUE TITLE
La7 again

### ISSUE THREAD

**Issue by avagraha** [ytdl-org/youtube-dl#22918]
## Checklist

- [ x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.10.29**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

C:\Users\>y -v https://www.la7.it/atlantide/rivedila7/atlantide-prese
nta-hitler-il-grande-inganno-e-linvasione-della-polonia-24-10-2019-289316
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.la7.it/atlantide/rivedila7/atlant
ide-presenta-hitler-il-grande-inganno-e-linvasione-della-polonia-24-10-2019-2893
16']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.09.29.1
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6002-SP2
[debug] exe versions: ffmpeg N-94137-g89b9690-Reino, ffprobe present
[debug] Proxy map: {}
[la7.it] atlantide-presenta-hitler-il-grande-inganno-e-linvasione-della-polonia-
24-10-2019-289316: Downloading webpage
[Kaltura] 0_ahf0vc74: Downloading video info JSON
ERROR: 0_ahf0vc74: Failed to parse JSON (caused by ValueError('Expecting value:
line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug
. Make sure you are using the latest version; type youtube-dl -U to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs
4t\build\youtube_dl\extractor\common.py", line 899, in _parse_json
File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs
4t\build\youtube_dl\extractor\common.py", line 899, in _parse_json
File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs
4t\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs
4t\build\youtube_dl\extractor\common.py", line 530, in extract
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs
4t\build\youtube_dl\extractor\kaltura.py", line 229, in _real_extract
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs
4t\build\youtube_dl\extractor\kaltura.py", line 219, in _get_video_info
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs
4t\build\youtube_dl\extractor\kaltura.py", line 173, in _kaltura_api_call
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs
4t\build\youtube_dl\extractor\common.py", line 892, in _download_json
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs
4t\build\youtube_dl\extractor\common.py", line 876, in _download_json_handle
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs
4t\build\youtube_dl\extractor\common.py", line 903, in _parse_json
youtube_dl.utils.ExtractorError: 0_ahf0vc74: Failed to parse JSON (caused by Va
lueError('Expecting value: line 1 column 1 (char 0)',)); please report this issu
e on https://yt-dl.org/bug . Make sure you are using the latest version; type y
outube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and
include its complete output.

## Description

WRITE DESCRIPTION HERE

Not a duplicate of resolved #22358 and see  last post of #22671 
Ok playback of this long video on phone. Ytdl fails. Thanks for investigating further.

**Comment by avagraha** [comment]
Please re-open, here NOT an outdated.
29th october:

C:\Users>y -v https://www.la7.it/atlantide/rivedila7/atlantide-presen
ta-hitler-il-grande-inganno-e-linvasione-della-polonia-24-10-2019-289316
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.la7.it/atlantide/rivedila7/a
tlantide-presenta-hitler-il-grande-inganno-e-linvasione-della-polonia-24-10
-2019-289316']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.10.29
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6002-SP2
[debug] exe versions: ffmpeg N-94698-g83e0b71-Reino, ffprobe N-94698-g83e0b
71-Reino, rtmpdump 2.4
[debug] Proxy map: {}
[la7.it] atlantide-presenta-hitler-il-grande-inganno-e-linvasione-della-pol
onia-24-10-2019-289316: Downloading webpage
[Kaltura] 0_ahf0vc74: Downloading video info JSON
[Kaltura] 0_ahf0vc74: Checking mp4-0 URL
[Kaltura] 0_ahf0vc74: mp4-0 URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.or
g/bug . Make sure you are using the latest version; type  youtube-dl -U  to
 update. Be sure to call youtube-dl with the --verbose flag and include its
 complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmps
7501na1\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmps
7501na1\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmps
7501na1\build\youtube_dl\extractor\kaltura.py", line 343, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmps
7501na1\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this
 issue on https://yt-dl.org/bug . Make sure you are using the latest versio
n; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --ve
rbose flag and include its complete output.





  ----- Original Message -----

**Comment by avagraha** [comment]
are you able to download it?

thanks.
