### ISSUE TITLE
player.stv.tv currently broken

### ISSUE THREAD

**Issue by james-wallace-ghub** [ytdl-org/youtube-dl#22928]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.10.29**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://player.st
v.tv/episode/30je/get-wet', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.10.29
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
[stv:player] 30je: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmps7501n
a1\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmps7501n
a1\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmps7501n
a1\build\youtube_dl\YoutubeDL.py", line 2018, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmps7501n
a1\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmps7501n
a1\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmps7501n
a1\build\youtube_dl\extractor\stv.py", line 52, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmps7501n
a1\build\youtube_dl\utils.py", line 2001, in extract_attributes
  File "C:\Python\Python34\lib\html\parser.py", line 164, in feed
TypeError: Can't convert 'NoneType' object to str implicitly
```

## Description

While parsing seemingly correctly, the download does not work at all, with a Python error when parsing the page. The page seems standard Brightcove otherwise. Any video seems to work for this, but I'm quoting a test case that should last longer and be active longer than the one already in the code

**Comment by james-wallace-ghub** [comment]
To get an account from player.stv.tv, you will need proof of being in Scotland - a postcode from [https://www.townscountiespostcodes.co.uk/postcodes-in-scotland/](here) should do it
