### ISSUE TITLE
 Downloading webpage  raise RegexNotFoundError('Unable to extract %s' % _name)

### ISSUE THREAD

**Issue by developcreativo** [ytdl-org/youtube-dl#22936]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2019.10.29**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
[PlatziCourse] firebase-web: Downloading webpage
ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\laragon\bin\python\python-3.6.1\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\laragon\bin\python\python-3.6.1\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\laragon\bin\python\python-3.6.1\lib\site-packages\youtube_dl\extractor\platzi.py", line 190, in _real_extract
    self._search_regex(r'data\s*=\s*({.+?})\s*;', webpage, 'data'),
  File "c:\laragon\bin\python\python-3.6.1\lib\site-packages\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment]
I've updated the PR code for #30548. Please test and follow up [there](https://github.com/ytdl-org/youtube-dl/pull/30548).
