### ISSUE TITLE
Unable to extract description and "Watch this video on YouTube"

### ISSUE THREAD

**Issue by shader301202** [ytdl-org/youtube-dl#22956]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.10.29**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PS Q:\> youtube-dl --verbose -F https://www.youtube.com/watch?v=stdYgxgJ5IE
[debug] System config: []
[debug] User config: ['--write-sub', '--sub-lang', 'en', '--convert-subs', 'ass', '--embed-sub', '--user-agent', 'Mozilla/5.0 (Linux; Android 7.0; SM-G892A Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Mobile Safari/537.36', '--ffmpeg-location', 'C:\\Users\\Filip\\AppData\\Roaming\\youtube-dl\\ffmpeg.exe', '--external-downloader', 'ffmpeg.exe']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-F', 'https://www.youtube.com/watch?v=stdYgxgJ5IE']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.10.29
[debug] Python version 3.7.4 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: ffmpeg N-91943-g1b98bfb932
[debug] Proxy map: {}
[youtube] stdYgxgJ5IE: Downloading webpage
[youtube] stdYgxgJ5IE: Downloading video info webpage
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\python37\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\python37\lib\site-packages\youtube_dl\extractor\youtube.py", line 2148, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.
```

## Description

So I've got two problems but only one of them is important. 
The first one is that youtube-dl does not extract descriptions. This error shows every time and I don't really mind.
The important problem is that I could not download a [YouTube video](https://www.youtube.com/watch?v=stdYgxgJ5IE)  I had wanted to. I tried `youtube-dl --verbose -F https://www.youtube.com/watch?v=stdYgxgJ5IE` but with no success as the end line is "Watch this video on YouTube. Playback on other websites has been disabled by the video owner."

How can I fix this?

**Comment by remitamine** [comment]
```
youtube-dl https://www.youtube.com/watch?v=stdYgxgJ5IE
[youtube] stdYgxgJ5IE: Downloading webpage
[youtube] stdYgxgJ5IE: Downloading video info webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: Asking You Insanely Personal Questions ASMR-stdYgxgJ5IE.f303.webm
[download]   0.1% of 523.82MiB at 66.18KiB/s ETA 02:14:55
```
