### ISSUE TITLE
Twitter video post (without text content) fails with: RegexNotFoundError: Unable to extract OpenGraph title

### ISSUE THREAD

**Issue by jm3** [ytdl-org/youtube-dl#22960]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.10.29**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose 'https://twitter.com/xc/status/1152273396022910976'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://twitter.com/xc/status/1152273396022910976']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.29
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, rtmpdump 2.4
[debug] Proxy map: {}
[twitter] 1152273396022910976: Downloading webpage
ERROR: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/twitter.py", line 464, in _real_extract
    username = remove_end(self._og_search_title(webpage), ' on Twitter')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1117, in _og_search_title
    return self._og_search_property('title', html, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1105, in _og_search_property
    escaped = self._search_regex(og_regexes, html, name, flags=re.DOTALL, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Twitter video links that also include text content appear to work, e.g.:
youtube-dl 'https://twitter.com/jm3/status/1166890480916783104?s=20' works

But as shown in the log above, youtube-dl 'https://twitter.com/xc/status/1152273396022910976' fails with "RegexNotFoundError: Unable to extract OpenGraph title;"

**Comment by remitamine** [comment]
the tweet is not accessible:
> Sorry, you are not authorized to see this status.
