### ISSUE TITLE
CBS.com not working anymore

### ISSUE THREAD

**Issue by invisan** [ytdl-org/youtube-dl#22985]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --no-part --restrict-filenames --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0" --referer "https://www.cbs.com/shows/bull/video/gJn44j3rXR4w4ICLwvmLKoKNJkjbD_3Z/bull-doctor-killer/" "https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2019/10/30/1633003587922/133153_cenc_dash/stream.mpd" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-part', '--restrict-filenames', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0', '--referer', 'https://www.cbs.com/shows/bull/video/gJn44j3rXR4w4ICLwvmLKoKNJkjbD_3Z/bull-doctor-killer/', 'https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2019/10/30/1633003587922/133153_cenc_dash/stream.mpd', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-92602-g8ef0fdaafc, ffprobe N-92602-g8ef0fdaafc
[debug] Proxy map: {}
[generic] stream: Requesting header
WARNING: Falling back on generic information extractor.
[generic] stream: Downloading webpage
[generic] stream: Extracting information
WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\generic.py", line 2395, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I dont know specifically when but it seems CBS is not working anymore with ytdl for me. I tried to Download the newest Episode of Bull but it seems CBS changed to mpd now. I tried with the command seen above and with the simpler one with the site directly **https://www.cbs.com/shows/bull/video/gJn44j3rXR4w4ICLwvmLKoKNJkjbD_3Z/bull-doctor-killer/**

I dont know if this is just an issue for me or if anyone else has that issue too.

**Comment by remitamine** [comment]
use the original URL directly:
```
youtube-dl https://www.cbs.com/shows/bull/video/gJn44j3rXR4w4ICLwvmLKoKNJkjbD_3Z/bull-doctor-killer/
[CBS] gJn44j3rXR4w4ICLwvmLKoKNJkjbD_3Z: Downloading XML
[CBS] gJn44j3rXR4w4ICLwvmLKoKNJkjbD_3Z: Downloading StreamPack SMIL data
[CBS] gJn44j3rXR4w4ICLwvmLKoKNJkjbD_3Z: Downloading m3u8 information
[CBS] gJn44j3rXR4w4ICLwvmLKoKNJkjbD_3Z: Downloading HLS_AES SMIL data
[CBS] gJn44j3rXR4w4ICLwvmLKoKNJkjbD_3Z: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[CBS] gJn44j3rXR4w4ICLwvmLKoKNJkjbD_3Z: Downloading JSON metadata
[download] Destination: Bull - Doctor Killer-gJn44j3rXR4w4ICLwvmLKoKNJkjbD_3Z.mp4
ffmpeg version n4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[hls @ 0x55e2ac70a5c0] Skip ('#EXT-X-ALLOW-CACHE:YES')
[hls @ 0x55e2ac70a5c0] Skip ('#EXT-X-VERSION:3')
[hls @ 0x55e2ac70a5c0] Opening 'https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2019/10/30/1633003587922/CBS_BULL_407_ms_2398_30M_6CH_133024_,2228,4628,3128,1628,848,503,000.mp4.csmil/crypt.key?null=0&id=AgBo7FfDFzI1fWbzwV1ZlIsTX2cT6Iqw39ftqTxiby4%2fek%2fgrQvk+BVO3zrnhFes7rMDYNVDQm08SA%3d%3d&hdntl=exp=1573078246~acl=/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2019/10/30/1633003587922/CBS_BULL_407_ms_2398_30M_6CH_133024_*~data=hdntl~hmac=718c374cf8aae575022402557fd586f62567f3eecb762d0cbfa5e0dfd5a2ff07' for reading
[hls @ 0x55e2ac70a5c0] Opening 'crypto+https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2019/10/30/1633003587922/CBS_BULL_407_ms_2398_30M_6CH_133024_,2228,4628,3128,1628,848,503,000.mp4.csmil/segment1_2_av.ts?null=0&id=AgBo7FfDFzI1fWbzwV1ZlIsTX2cT6Iqw39ftqTxiby4%2fek%2fgrQvk+BVO3zrnhFes7rMDYNVDQm08SA%3d%3d&hdntl=exp=1573078246~acl=/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2019/10/30/1633003587922/CBS_BULL_407_ms_2398_30M_6CH_133024_*~data=hdntl~hmac=718c374cf8aae575022402557fd586f62567f3eecb762d0cbfa5e0dfd5a2ff07' for reading
Input #0, hls, from 'https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2019/10/30/1633003587922/CBS_BULL_407_ms_2398_30M_6CH_133024_,2228,4628,3128,1628,848,503,000.mp4.csmil/index_2_av.m3u8?null=0&id=AgBo7FfDFzI1fWbzwV1ZlIsTX2cT6Iqw39ftqTxiby4%2fek%2fgrQvk+BVO3zrnhFes7rMDYNVDQm08SA%3d%3d&hdntl=exp=1573078246~acl=%2fi%2ftemp_hd_gallery_video%2fCBS_Production_Outlet_VMS%2fvideo_robot%2fCBS_Production_Entertainment%2f2019%2f10%2f30%2f1633003587922%2fCBS_BULL_407_ms_2398_30M_6CH_133024_*~data=hdntl~hmac=718c374cf8aae575022402557fd586f62567f3eecb762d0cbfa5e0dfd5a2ff07':
  Duration: 00:42:38.19, start: 0.100667, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Bull - Doctor Killer-gJn44j3rXR4w4ICLwvmLKoKNJkjbD_3Z.mp4.part':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   43 fps=0.0 q=-1.0 size=       0kB time=00:00:01.79 bitrate=   0.2kbits
```

**Comment by invisan** [comment]
If i do that i get this response:

youtube-dl https://www.cbs.com/shows/bull/video/gJn44j3rXR4w4ICLwvmLKoKNJkjbD_3Z/bull-doctor-killer/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.cbs.com/shows/bull/video/gJn44j3rXR4w4ICLwvmLKoKNJkjbD_3Z/bull-doctor-killer/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-92602-g8ef0fdaafc, ffprobe N-92602-g8ef0fdaafc
[debug] Proxy map: {}
[CBS] gJn44j3rXR4w4ICLwvmLKoKNJkjbD_3Z: Downloading XML
[CBS] gJn44j3rXR4w4ICLwvmLKoKNJkjbD_3Z: Downloading StreamPack SMIL data
[CBS] gJn44j3rXR4w4ICLwvmLKoKNJkjbD_3Z: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[CBS] gJn44j3rXR4w4ICLwvmLKoKNJkjbD_3Z: Downloading HLS_AES SMIL data
[CBS] gJn44j3rXR4w4ICLwvmLKoKNJkjbD_3Z: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\cbs.py", line 112, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\cbs.py", line 94, in _extract_video_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
