### ISSUE TITLE
UKTV Play - ERROR: Unsupported URL

### ISSUE THREAD

**Issue by ZackaryH8** [ytdl-org/youtube-dl#22987]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2019.11.05**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --ffmpeg-location "C:\ITV-Downloads\ff" --force-generic-extractor -v -o "C:\ITV-Downloads\%%(series)s\%%(series)s - S%%(season_number)sE%%(episode_number)s.%%(ext)s" "https://uktvplay.uktv.co.uk/shows/train-truckers/watch-online/6083371508001"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', 'C:\\ITV-Downloads\\ff', '--force-generic-extractor', '-v', '-o', 'C:\\ITV-Downloads\\%%(series)s\\%%(series)s - S%%(season_number)sE%%(episode_number)s.%%(ext)s', 'https://uktvplay.uktv.co.uk/shows/train-truckers/watch-online/6083371508001']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.7.3 (CPython) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg git-2019-11-01-53c21c2, ffprobe git-2019-11-01-53c21c2
[debug] Proxy map: {}
[generic] 6083371508001: Requesting header
WARNING: Forcing on generic information extractor.
[generic] 6083371508001: Downloading webpage
[generic] 6083371508001: Extracting information
ERROR: Unsupported URL: https://uktvplay.uktv.co.uk/shows/train-truckers/watch-online/6083371508001
Traceback (most recent call last):
  File "c:\users\zack\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\zack\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\users\zack\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\generic.py", line 3354, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://uktvplay.uktv.co.uk/shows/train-truckers/watch-online/6083371508001
```

## Description

I insert the link https://uktvplay.uktv.co.uk/shows/train-truckers/watch-online/6083371508001 which is supposedly supported by this tool however it seems to think it isn't.

**Comment by Danker1990** [comment]
The website changed it site format and thus this tool was now unable to grab the data. there has been calls for the site to be pulled from the list
