### ISSUE TITLE
Unable to download publicly available youtube video

### ISSUE THREAD

**Issue by zenny** [ytdl-org/youtube-dl#23015]
Hi, I am running:

```
$ youtube-dl --version
2019.11.05
```
to download the links from publicly available webinar recordings from https://nam.edu/event/globalroadmap-workshop/ with

```
$ youtube-dl -v https://youtu.be/t36ICau6BuM
$ youtube-dl -v https://youtu.be/auNfQWjal84

```

```
$ youtube-dl -v https://youtu.be/t36ICau6BuM
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://youtu.be/t36ICau6BuM']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 2.7.6 (CPython) - Linux-4.4.0-148-lowlatency-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 3.4, avprobe 3.4, ffmpeg 3.4, ffprobe 3.4, phantomjs 2.1.1, rtmpdump 2.4-n111-gitfa8646d-ppa9p2
[debug] Proxy map: {}
[youtube] t36ICau6BuM: Downloading webpage
[youtube] t36ICau6BuM: Downloading video info webpage
ERROR: This video contains content from WMG, who has blocked it on copyright grounds.
Sorry about that.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2148, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video contains content from WMG, who has blocked it on copyright grounds.
Sorry about that.
```

```
$ youtube-dl -v https://youtu.be/auNfQWjal84
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://youtu.be/auNfQWjal84']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 2.7.6 (CPython) - Linux-4.4.0-148-lowlatency-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 3.4, avprobe 3.4, ffmpeg 3.4, ffprobe 3.4, phantomjs 2.1.1, rtmpdump 2.4-n111-gitfa8646d-ppa9p2
[debug] Proxy map: {}
[youtube] auNfQWjal84: Downloading webpage
[youtube] auNfQWjal84: Downloading video info webpage
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: This video is unavailable.
Sorry about that.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2148, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is unavailable.
Sorry about that.
```

## Description

Even using the latest versions of yt-dl, the webinar recordings which is publicly available and can be downloaded with newpipe app in android devices are not accessible via command line with youtube-dl as stated above. Both videos were available online via newpipe app in android till these lines are written.

Cheers,
/z

**Comment by dstftw** [comment]
Both does not play in browser.
