### ISSUE TITLE
HTTP Error 429 when downloading from Youtube

### ISSUE THREAD

**Issue by crs00** [ytdl-org/youtube-dl#23013]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -o "~/Desktop/%(id)s - %(title)s.%(ext)s" 'https://youtu.be/2R9WwhRVkbU' --retries 9001 --fragment-retries 9001 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', '~/Desktop/%(id)s - %(title)s.%(ext)s', 'https://youtu.be/2R9WwhRVkbU', '--retries', '9001', '--fragment-retries', '9001', '--verbose']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[youtube] 2R9WwhRVkbU: Downloading webpage
[youtube] 2R9WwhRVkbU: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: 2R9WwhRVkbU: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\youtube.py", line 1836, in _real_extract
youtube_dl.utils.ExtractorError: 2R9WwhRVkbU: YouTube said: Unable to extract video data
```

## Description

I'm getting an error claiming that I'm making too many requests of youtube.

**Comment by Zuccace** [comment]
@crs00 see [this](https://github.com/ytdl-org/youtube-dl/issues/22983#issuecomment-551657104).
