### ISSUE TITLE
Add support for Mixer clips to beampro.py Extractor

### ISSUE THREAD

**Issue by TheGilias** [ytdl-org/youtube-dl#23020]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

The current implementation of the beampro.py Extractor (used for Mixer streams) currently supports downloading streams live as well as downloading VODs, but I was wondering if it might also be possible to add on support for downloading a streamer's clips as well. The format for the URL is https://mixer.com/*ChannelName*?clip=*ClipID*. If you attempt to download a clip from a channel currently it attempts to use the live stream extractor which fails if the user is not currently live and downloads their current stream instead of the clip if they are live.

An example of a clip which you could attempt to download until it expires on 11/22 is https://mixer.com/PermaNoob?clip=DB1mDsthm0eTtpsXv35vJw

Here is the output of youtube-dl when attempting to download that clip.
    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: ['https://mixer.com/PermaNoob?clip=DB1mDsthm0eTtpsXv35vJw', '--verbose']
    [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
    [debug] youtube-dl version 2019.11.05
    [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
    [debug] exe versions: ffmpeg N-94383-g3883c9d147, ffprobe N-94383-g3883c9d147
    [debug] Proxy map: {}
    [Mixer:live] PermaNoob: Downloading JSON metadata
    ERROR: PermaNoob is offline
    Traceback (most recent call last):
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 530, in extract
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\beampro.py", line 70, in _real_extract
    youtube_dl.utils.ExtractorError: PermaNoob is offline

I would be happy to provide anything else if needed.

**Comment by TheGilias** [comment]
I found the API location for obtaining the clip manifest. It's on the Mixer API as /clips/*ClipID* (Example: https://mixer.com/api/v1/clips/DB1mDsthm0eTtpsXv35vJw)
