### ISSUE TITLE
YouTube.com can't download while proxying over Tor anymore: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by EauBureau** [ytdl-org/youtube-dl#23028]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v -4 --geo-bypass --proxy "socks4a://127.0.0.1:9150" -F https://www.youtube.com/watch?v=VbrfXDFuzu0
[debug] System config: []
[debug] User config: [u'-o', u'~/Videos/youtube-dl/%(title)s.%(ext)s', u'--user-agent', u'Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-4', u'--geo-bypass', u'--proxy', u'socks4a://127.0.0.1:9150', u'-F', u'https://www.youtube.com/watch?v=VbrfXDFuzu0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 2.7.16 (CPython) - Linux-5.0.0-32-generic-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {u'http': u'socks4a://127.0.0.1:9150', u'https': u'socks4a://127.0.0.1:9150'}
[youtube] VbrfXDFuzu0: Downloading webpage
[youtube] VbrfXDFuzu0: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: VbrfXDFuzu0: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1836, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: VbrfXDFuzu0: YouTube said: Unable to extract video data
```

## Description

When proxying over tor (via the Tor Browser) I can't get any videos anymore. 
It returns the erros:
```
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: VbrfXDFuzu0: YouTube said: Unable to extract video data
```

Same issue was happening with 2019.10.22

**Comment by EauBureau** [comment]
Sorry about the duplicate. 
Could you post the bug number so I can keep an eye on it? 
I can't quite find it myself. I found these similar ones #21729 #22839 #444 but most are old. None mention proxing over tor.
(youtube-dl works fine for me over regular internet.)
Thanks.
