### ISSUE TITLE
instagram blocked since 2am 

### ISSUE THREAD

**Issue by LaticePrime** [ytdl-org/youtube-dl#23030]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v https://www.instagram.com/daily.memes/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.instagram.com/daily.memes/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.7.4 (CPython) - Darwin-19.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, rtmpdump 2.4
[debug] Proxy map: {}
[instagram:user] daily.memes: Downloading webpage
[download] Downloading playlist: daily.memes
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2018, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 968, in process_ie_result
    ie_entries, playliststart, playlistend))
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/instagram.py", line 262, in _extract_graphql
    variables.update(self._query_vars_for(data))
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/instagram.py", line 392, in _query_vars_for
    'id': data['entry_data']['ProfilePage'][0]['graphql']['user']['id']
KeyError: 'ProfilePage'

```

## Description

Blocked from downloading from instagram for 17 hours now. Can still access the content on smart phones and web browsers. Blocked after heavy downloading of videos. It happens often but doesn't usually last this long? I thought it might be an IP block but can still access instagram on desktop and mobile device. You may not be able to recreate this error without downloading a LOT of content! It does happen sometimes but never for this long? Can't understand it because it feels like an IP ban yet can still access on desktop and devices. HELP!

**Comment by LaticePrime** [comment]
Not sure if this helps, but, I've just tried it with instaloader and it says it's caused by error 429 too many requests and is redirecting to login so it's obviously caused by too many downloads; it just usually resets after a few hours but on this occasion has not reset after almost a day.

This explains why you'd would not be able to recreate the error without a lot of downloads.
