### ISSUE TITLE
[nbc] All network support

### ISSUE THREAD

**Issue by StevenDTX** [ytdl-org/youtube-dl#23049]
## Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running youtube-dl version **2019.11.05**
- [X] I've searched the bugtracker for similar site feature requests including closed ones

## Description

NBC.com now streams all of their networks (Bravo, E!, CNBC, Oxygen, etc).  It would be awesome if the NBC extractor could download all of these networks/shows.

There is another similar Issue posted, but it was closed with "Account required".  There are currently some free URLs that could be tested against:

https://www.nbc.com/e-live-from-the-red-carpet/video/e-peoples-choice-awards-red-carpet/4064509

https://www.nbc.com/back-in-the-game/video/evander-holyfield-featuring-marcus-lemonis/4060395

https://www.nbc.com/the-real-housewives-of-new-jersey/video/sex-lies-and-video-debates/4059276

```
C:\>c:\support\youtube-dl.exe https://www.nbc.com/e-live-from-the-red-carpet/video/e-peoples-choice-awards-red-carpet/4064509 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.nbc.com/e-live-from-the-red-carpet/video/e-peoples-choice-awards-red-carpet/4064509', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-95216-ge6625ca41f
[debug] Proxy map: {}
[NBC] 4064509: Downloading JSON metadata
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\YoutubeDL.py", line 2018, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\nbc.py", line 116, in _real_extract
TypeError: 'NoneType' object is not subscriptable
```

Thanks!

**Comment by sufr3ak** [comment]
I wanted to add support for this. I keep getting errors with NBC.

**Comment by tony-izzo** [comment]
I'm getting the same error with all content from E! network.  Example:

https://www.nbc.com/keeping-up-with-the-kardashians/video/hard-candy/4063177

**Comment by roadzy** [comment]
I can provide an account to test with.

**Comment by StevenDTX** [comment]
Thanks a lot @remitamine.  You can probably close out all the site requests for Oxygen, CNBC and E! now, and redirect folks to this extractor.

**Comment by roadzy** [comment]
I tried a video from oxygen and it failed. Do you want me to post the error message or open a new ticket?

**Comment by StevenDTX** [comment]
> 
> 
> I tried a video from oxygen and it failed. Do you want me to post the error message or open a new ticket?

Are you using a link like https://www.oxygen.com/dateline-secrets-uncovered/season-8/the-threat or https://www.nbc.com/dateline-secrets-uncovered/video/the-threat/4099435 ?

You must use the nbc.com link from: https://www.nbc.com/networks/oxygen

Also, did you build a new version of youtube-dl?  The latest version does not include the updated NBC extractor.

**Comment by roadzy** [comment]
I did the nbc.com url. I assumed this was in the newest update. I’ll apply the patch manually and try again. Thnx.

**Comment by roadzy** [comment]
@StevenDTX still no luck.  I created a new nbc.py and here's what I get.

 youtube-dl-abb https://www.nbc.com/aaron-hernandez-uncovered/video/part-one/3682681 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ap-mso', 'auth_atlanticbb_net', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.nbc.com/aaron-hernandez-uncovered/video/part-one/3682681', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.15
[debug] Python version 3.7.2 (CPython) - Linux-3.10.0-1062.4.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2
[debug] Proxy map: {}
[NBC] 3682681: Downloading JSON metadata
[NBC] 3682681: Retrieving Media Token
ERROR: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known')))
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/utils.py", line 2728, in https_open
    req, **kwargs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)

**Comment by roadzy** [comment]
Recreated the nbc file again and it seems to be working this time.  No clue... oh well thanks!
