### ISSUE TITLE
dr.dk not working after update

### ISSUE THREAD

**Issue by nem0rder** [ytdl-org/youtube-dl#23059]
### svtplay-dl versions:
```
# youtube-dl --version
2019.11.05
```
### Operating system and Python version:
```
# cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
# python3 -V
Python 3.5.3
# python -V
Python 2.7.13

```

### What is the issue:

Can not download from dr.dk after they have updated the interface:

If i use a link from the old interface i get the following:
```
# youtube-dl --verbose https://www.dr.dk/tv/se/boern/ramasjang/gurli-gris-tv/gurli-gris-7/gurli-gris-2019-08-20
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.dr.dk/tv/se/boern/ramasjang/gurli-gris-tv/gurli-gris-7/gurli-gris-2019-08-20']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 2.7.13 (CPython) - Linux-4.19.66-v7+-armv7l-with-debian-9.11
[debug] exe versions: avconv 3.2.14-1, avprobe 3.2.14-1, ffmpeg 3.2.14-1, ffprobe 3.2.14-1
[debug] Proxy map: {}
[drtv] gurli-gris-2019-08-20: Downloading webpage
ERROR: Unable to extract urn; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/drtv.py", line 105, in _real_extract
    webpage, 'urn'))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract urn; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
If i use a link from the new interface i get the following (same content):
```
# youtube-dl --verbose https://www.dr.dk/drtv/episode/gurli-gris_-graeskargildet_146041
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.dr.dk/drtv/episode/gurli-gris_-graeskargildet_146041']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 2.7.13 (CPython) - Linux-4.19.66-v7+-armv7l-with-debian-9.11
[debug] exe versions: avconv 3.2.14-1, avprobe 3.2.14-1, ffmpeg 3.2.14-1, ffprobe 3.2.14-1
[debug] Proxy map: {}
[generic] gurli-gris_-graeskargildet_146041: Requesting header
WARNING: Falling back on generic information extractor.
[generic] gurli-gris_-graeskargildet_146041: Downloading webpage
[generic] gurli-gris_-graeskargildet_146041: Extracting information
ERROR: Unsupported URL: https://www.dr.dk/drtv/episode/gurli-gris_-graeskargildet_146041
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2373, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: mismatched tag: line 5, column 14
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3354, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.dr.dk/drtv/episode/gurli-gris_-graeskargildet_146041
```

**Comment by Marge-Innovera** [comment]
Confirming that the site dr.dk has an updated layout and that the issue with youtube-dl can be confirmed with other URLs as well and other OS.

**Comment by Symbiot78** [comment]
I am seeing the same issue on newest .exe . 
from reading @Marge-Innovera 's comment, I assume this is fixed in the next version that will be released?
If you need more debug info, don't hesitate to ask.

`ERROR: Unsupported URL: https://www.dr.dk/drtv/se/paw-patrol_-vovserne-redder-luke-stars_149929
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\generic.py", line 3354, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.dr.dk/drtv/se/paw-patrol_-vovserne-redder-luke-stars_149929`
