### ISSUE TITLE
Inconsistent downloading from Twitter

### ISSUE THREAD

**Issue by josephomorrow** [ytdl-org/youtube-dl#23062]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-a', u'/home/Joseph/Documents/plainText/ytdltw.txt', u'--no-part', u'--restrict-filenames']
[debug] Batch file urls: [u'https://twitter.com/i/status/1180524380985679872']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 2.7.17 (CPython) - Linux-5.3.8-200.fc30.x86_64-x86_64-with-fedora-30-Thirty
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4
[debug] Proxy map: {}
[twitter] 1180524380985679872: Downloading webpage
[twitter:card] 1180524380985679872: Downloading webpage
[twitter:card] 1180524380985679872: Downloading guest token
[twitter:card] 1180524380985679872: Downloading JSON metadata
[twitter:card] 1180524380985679872: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://video.twimg.com/ext_tw_video/1180524198667653125/pu/pl/672x848/oFbQ_db8z8Eep9kH.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 47
[download] Destination: Benny_-_Mahalet_was_born_in_Ethiopia._Abandoned_by_her_parents_she_lived_as_an_impoverished_orphan._Mahalet_was_adopted_by_a_loving_Christian_American_family_at_11._This_week_@TPUSA_brought_her_to_the_WH._She_asked_to_pray_for_our_President._He_brought_her_onstage-then_this_happened_--1180524380985679872.mp4
ERROR: unable to download video
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 900, in process_ie_result
    new_result, download=download, extra_info=extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 862, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1643, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1930, in process_info
    raise UnavailableVideoError(err)
UnavailableVideoError: [Errno 36] File name too long: 'Benny_-_Mahalet_was_born_in_Ethiopia._Abandoned_by_her_parents_she_lived_as_an_impoverished_orphan._Mahalet_was_adopted_by_a_loving_Christian_American_family_at_11._This_week_@TPUSA_brought_her_to_the_WH._She_asked_to_pray_for_our_President._He_brought_her_onstage-then_this_happened_--1180524380985679872.mp4.ytdl'


```

## Description

Downloading from Twitter works intermittently. Seems that youtube-dl doesn't like file names that are "too long".

**Comment by josephomorrow** [comment]
Duplicate of which Issue?

**Comment by josephomorrow** [comment]
For what it's worth, I discovered that forcing a smaller file name for the destination file works OK.

**Comment by shillshocked** [comment]
> For what it's worth, I discovered that forcing a smaller file name for the destination file works OK.

How?

**Comment by josephomorrow** [comment]
Downloading from Twitter can cause a too-lengthy file name. When that happens, try again with using the --id switch, which suppresses the video title from appearing in the destination file name.

**Comment by StyxBzh** [comment]
> 
> 
> try again with using the --id 
Thanks it works really great ! I got some difficult to understand errors particularly on twitter and it solves them
use ^youtube-dl --id [http what you want]
for a simple download with a filename made of a string of number and rename the file later
