### ISSUE TITLE
Frontend Masters - Unable to log in

### ISSUE THREAD

**Issue by andrerfcsantos** [ytdl-org/youtube-dl#23071]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://frontendmasters.com/courses/vue/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.7.4 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg N-93544-g0a347ff422, ffprobe N-93544-g0a347ff422
[debug] Proxy map: {}
[FrontendMastersCourse] Downloading login page
[FrontendMastersCourse] Logging in
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\andre\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\andre\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\common.py", line 529, in extract
    self.initialize()
  File "c:\users\andre\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\common.py", line 433, in initialize
    self._real_initialize()
  File "c:\users\andre\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\frontendmasters.py", line 32, in _real_initialize
    self._login()
  File "c:\users\andre\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\frontendmasters.py", line 70, in _login
    raise ExtractorError('Unable to log in')
youtube_dl.utils.ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I was trying to download a course from FrontendMasters. I provided my login with the `-u` and `-p` flags but it gives me this error. Tried both Python 2 and Python 3, Windows and Linux, same error. I also checked several times my credentials and they are correct, my FrontendMasters account is active and i can watch the videos via browser.

**Comment by andrerfcsantos** [comment]
@remitamine I can provide you my account if needed be for testing.

**Comment by andrerfcsantos** [comment]
So, i did a bit of digging around to see if i could fix the problem and not sure if it'll be easy.

Currently the login is performed by sending the login data via form, waiting for the reply and checking if the reply page has some form of "logout" text, indicating the login succeeded:

https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/frontendmasters.py#L56

The problem i see with this approach is that the page has a captcha that must be fulfilled. Unless the program tries to go around that, i'm not sure if it's possible to pass the captcha.

I downloaded the source and changed the program to write the downloaded page to a file. I could confirm that the page that comes as a reply after sending the form is the regular login page of a logged out user.

There's an API to get the course information, and that includes the links for the videos, but when trying to get the video using the URL i get the error that saying only the web client can use that endpoint of the API.

**Comment by 5hay** [comment]
Can confirm that login fails. I can provide an account if needed.

**Comment by ZafarAqil** [comment]
I can provide an account as well. I just want this to get fixed asap.

**Comment by brkn** [comment]
Any updates on this? It's still tagged as `account-needed`.

**Comment by RaDeleon** [comment]
> Any updates on this? It's still tagged as `account-needed`.

search npm for frontend-masters-downloader works right now

**Comment by Buzut** [comment]
It seems to not work any more.
