### ISSUE TITLE
Playlist extractor returns only the first 36 entries

### ISSUE THREAD

**Issue by ajilpappachan** [ytdl-org/youtube-dl#23095]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '--verbose', 'https://www.pornhub.com/playlist/43180982']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[PornHubPagedVideoList] playlist/43180982: Downloading page 1
[download] Downloading playlist: playlist/43180982
[PornHubPagedVideoList] playlist playlist/43180982: Collected 36 video ids (downloading 36 of them)
[download] Downloading video 1 of 36
[PornHub] 1060449039: Downloading pc webpage
[PornHub] 1060449039: Downloading tv webpage
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\pornhub.py", line 235, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Pornhub recently changed it's playlist formatting from multiple pages to a single page with more content being loaded as you scroll down. As a result, when trying to download a playlist using youtube-dl, only the first 36 videos are being picked up by the extractor, and not the complete playlist. I tried using VPN as well, and sometimes the extraction doesn't work at and at other times, the first 36 videos are extracted, but never the complete playlist.

**Comment by kuarthepirat** [comment]
[pornhub.patch.txt](https://github.com/ytdl-org/youtube-dl/files/3875030/pornhub.patch.txt)

I made a rough patch to fix this issue for me. It does probably not adhere to the coding standards of youtube-dl because I am not really good at python. But maybe someone can take it as a basis to fix this issue in the upstream.

**Comment by patsulee** [comment]
I think i searched everywhere for a solution to the problem of downloading only the first 36 videos of a given playlist,. and this is the only thread that comes close to giving an answer - unless someone else can guide me to another.

 The problem is... how do i apply this patch? (and of course if it still works in 2020)

**Comment by dirkf** [comment]
If you think that this problem still exists, please open a new issue according to #30839.

Probably other issues exist with PH if that is the site of interest.
