### ISSUE TITLE
pluzz tv -france tv

### ISSUE THREAD

**Issue by campones** [ytdl-org/youtube-dl#23097]
Hello
I m facing an issue while trying to use the plugin for pluzz-france tv.
Since the segment video audio are now split, ytdl only seems to grab the video but not the audio, resulting in a video without audio.

ex: 

 /usr/local/bin/youtube-dl https://www.france.tv/france-2/direct.html
[FranceTVSite] direct: Downloading webpage
[FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading video JSON
[FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading signed hls manifest URL
[FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading m3u8 information
[download] Destination: France 2 en direct 2019-11-15 21_55-006194ea-117d-4bcf-94a9-153d999c59ae.fhls-2866.mp4
ffmpeg version N-95098-gb9f8ab3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
  configuration: --enable-gpl --enable-version3 --enable-nonfree --enable-libfdk_aac --enable-libtheora --enable-libvorbis --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libvpx --enable-libass --enable-libfreetype --extra-libs=-ldl --enable-openssl
  libavutil      56. 35.100 / 56. 35.100
  libavcodec     58. 59.100 / 58. 59.100
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 59.100 /  7. 59.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[hls @ 0x5600ff9d1c40] Skip ('#EXT-X-VERSION:5')
[hls @ 0x5600ff9d1c40] Skip ('#EXT-X-INDEPENDENT-SEGMENTS')
[hls @ 0x5600ff9d1c40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2019-11-15T12:54:10.398Z')
[hls @ 0x5600ff9d1c40] Opening 'https://livefrancetv.akamaized.net/keys/hls.key' for reading
[hls @ 0x5600ff9d1c40] Opening 'crypto+https://livefrancetv.akamaized.net/simulcast/France_2/hls/ZXhwPTE1NzM4NDQxMDl+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV8yJTJmaGxzKn5obWFjPWNhODEzMTc5MmE0MzBiYWI5NTRlZjE3ZjgzYjg0ODMzMWM3OGM0ODE1YzM3ZmQxOTA2YjQ3ZTQxMDI5YTc4OWY=/France_2-video=2600000-15377200.ts' for reading
Input #0, hls, from 'https://livefrancetv.akamaized.net/simulcast/France_2/hls/ZXhwPTE1NzM4NDQxMDl+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV8yJTJmaGxzKn5obWFjPWNhODEzMTc5MmE0MzBiYWI5NTRlZjE3ZjgzYjg0ODMzMWM3OGM0ODE1YzM3ZmQxOTA2YjQ3ZTQxMDI5YTc4OWY=/France_2-video=2600000.m3u8':
  Duration: N/A, start: 87694.919089, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:France 2 en direct 2019-11-15 21_55-006194ea-117d-4bcf-94a9-153d999c59ae.fhls-2866.mp4.part':
  Metadata:
    encoder         : Lavf58.33.100
    Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)

---

 /usr/local/bin/youtube-dl https://www.france.tv/france-2/direct.html -F
[FranceTVSite] direct: Downloading webpage
[FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading video JSON
[FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading signed hls manifest URL
[FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading m3u8 information
[info] Available formats for 006194ea-117d-4bcf-94a9-153d999c59ae:
format code                          extension  resolution note
hls-audio-aacl-98-Audio_Description  mp4        audio only [qad]
hls-audio-aacl-98-Francais           mp4        audio only [fra]
hls-audio-aacl-98-Version_Originale  mp4        audio only [qaa]
hls-235                              mp4        256x144     235k , avc1.42C01E, 25.0fps, video only
hls-534                              mp4        384x216     534k , avc1.42C01E, 25.0fps, video only
hls-1117                             mp4        640x360    1117k , avc1.42C01E, 25.0fps, video only
hls-1594                             mp4        960x540    1594k , avc1.4D401F, 25.0fps, video only
hls-2866                             mp4        1280x720   2866k , avc1.4D401F, 25.0fps, video only (best)

**Comment by FM33** [comment]
I have similar issue. There is audio only for the first minutes of the video. I also tried to download it separately, but the just-listed "format" is declared unavailable when trying to download.
```
$ ~/.config/youtube-dlg/youtube-dl -F https://www.france.tv/france-5/le-monde-en-face/1138467-reve-pavillonnaire-les-dessous-d-un-modele.html
[FranceTVSite] 1138467-reve-pavillonnaire-les-dessous-d-un-modele: Downloading webpage
[FranceTV] 4c72480d-8bdf-4eb5-980a-f051f6ecad78: Downloading video JSON
[FranceTV] 4c72480d-8bdf-4eb5-980a-f051f6ecad78: Downloading geo restriction info
[FranceTV] 4c72480d-8bdf-4eb5-980a-f051f6ecad78: Downloading signed hls_v5_os manifest URL
[FranceTV] 4c72480d-8bdf-4eb5-980a-f051f6ecad78: Downloading m3u8 information
[FranceTV] 4c72480d-8bdf-4eb5-980a-f051f6ecad78: Downloading signed m3u8-download manifest URL
[FranceTV] 4c72480d-8bdf-4eb5-980a-f051f6ecad78: Downloading m3u8 information
[info] Available formats for 4c72480d-8bdf-4eb5-980a-f051f6ecad78:
format code                             extension  resolution note
hls_v5_os-audio-aacl-64-Audio_Français  mp4        audio only [fr] 
hls_v5_os-191                           mp4        384x216     191k , avc1.42C01E, 25.0fps, video only
hls_v5_os-321                           mp4        640x360     321k , avc1.4D401F, 25.0fps, video only
hls_v5_os-609                           mp4        960x540     609k , avc1.4D401F, 25.0fps, video only
hls_v5_os-880                           mp4        1280x720    880k , avc1.64001F, 25.0fps, video only
m3u8-download-519                       mp4        384x216     519k , avc1.66.30, mp4a.40.2
m3u8-download-1085                      mp4        640x360    1085k , avc1.77.30, mp4a.40.2
m3u8-download-1543                      mp4        960x540    1543k , avc1.77.30, mp4a.40.2
m3u8-download-2164                      mp4        1280x720   2164k , avc1.64001f, mp4a.40.2 (best)

$ ~/.config/youtube-dlg/youtube-dl -f 'hls_v5_os-audio-aacl-64-Audio_Français' https://www.france.tv/france-5/le-monde-en-face/1138467-reve-pavillonnaire-les-dessous-d-un-modele.html
[FranceTVSite] 1138467-reve-pavillonnaire-les-dessous-d-un-modele: Downloading webpage
[FranceTV] 4c72480d-8bdf-4eb5-980a-f051f6ecad78: Downloading video JSON
[FranceTV] 4c72480d-8bdf-4eb5-980a-f051f6ecad78: Downloading geo restriction info
[FranceTV] 4c72480d-8bdf-4eb5-980a-f051f6ecad78: Downloading signed hls_v5_os manifest URL
[FranceTV] 4c72480d-8bdf-4eb5-980a-f051f6ecad78: Downloading m3u8 information
[FranceTV] 4c72480d-8bdf-4eb5-980a-f051f6ecad78: Downloading signed m3u8-download manifest URL
[FranceTV] 4c72480d-8bdf-4eb5-980a-f051f6ecad78: Downloading m3u8 information
ERROR: requested format not available
```

**Comment by Shnoulle** [comment]
Hi,

Confirm this issue
````
$ youtubedl --version
2020.01.24
````

````
$ youtubedl -Fv https://www.france.tv/france-3/pieces-a-conviction/1183045-qui-va-garder-mon-enfant-enquete-derriere-les-murs-des-creches-privees.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-Fv', u'https://www.france.tv/france-3/pieces-a-conviction/1183045-qui-va-garder-mon-enfant-enquete-derriere-les-murs-des-creches-privees.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-8-amd64-x86_64-with-debian-10.3
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[FranceTVSite] 1183045-qui-va-garder-mon-enfant-enquete-derriere-les-murs-des-creches-privees: Downloading webpage
[FranceTV] 6d716c77-0011-4ffa-bd27-e7ae0124d2ce: Downloading video JSON
[FranceTV] 6d716c77-0011-4ffa-bd27-e7ae0124d2ce: Downloading geo restriction info
[FranceTV] 6d716c77-0011-4ffa-bd27-e7ae0124d2ce: Downloading signed hls_v5_os manifest URL
[FranceTV] 6d716c77-0011-4ffa-bd27-e7ae0124d2ce: Downloading m3u8 information
[FranceTV] 6d716c77-0011-4ffa-bd27-e7ae0124d2ce: Downloading signed m3u8-download manifest URL
[FranceTV] 6d716c77-0011-4ffa-bd27-e7ae0124d2ce: Downloading m3u8 information
[info] Available formats for 6d716c77-0011-4ffa-bd27-e7ae0124d2ce:
format code                             extension  resolution note
hls_v5_os-audio-aacl-64-Audio_Français  mp4        audio only [fr] 
hls_v5_os-191                           mp4        384x216     191k , avc1.42C01E, 25.0fps, video only
hls_v5_os-321                           mp4        640x360     321k , avc1.4D401F, 25.0fps, video only
hls_v5_os-609                           mp4        960x540     609k , avc1.4D401F, 25.0fps, video only
hls_v5_os-880                           mp4        1280x720    880k , avc1.64001F, 25.0fps, video only
m3u8-download-519                       mp4        384x216     519k , avc1.66.30, mp4a.40.2
m3u8-download-1085                      mp4        640x360    1085k , avc1.77.30, mp4a.40.2
m3u8-download-1545                      mp4        960x540    1545k , avc1.77.30, mp4a.40.2
m3u8-download-2166                      mp4        1280x720   2166k , avc1.64001f, mp4a.40.2 (best)
````

````
$ youtubedl -v --format hls_v5_os-audio-aacl-64-Audio_Français https://www.france.tv/france-3/pieces-a-conviction/1183045-qui-va-garder-mon-enfant-enquete-derriere-les-murs-des-creches-privees.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--format', u'hls_v5_os-audio-aacl-64-Audio_Fran\xe7ais', u'https://www.france.tv/france-3/pieces-a-conviction/1183045-qui-va-garder-mon-enfant-enquete-derriere-les-murs-des-creches-privees.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-8-amd64-x86_64-with-debian-10.3
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[FranceTVSite] 1183045-qui-va-garder-mon-enfant-enquete-derriere-les-murs-des-creches-privees: Downloading webpage
[FranceTV] 6d716c77-0011-4ffa-bd27-e7ae0124d2ce: Downloading video JSON
[FranceTV] 6d716c77-0011-4ffa-bd27-e7ae0124d2ce: Downloading geo restriction info
[FranceTV] 6d716c77-0011-4ffa-bd27-e7ae0124d2ce: Downloading signed hls_v5_os manifest URL
[FranceTV] 6d716c77-0011-4ffa-bd27-e7ae0124d2ce: Downloading m3u8 information
[FranceTV] 6d716c77-0011-4ffa-bd27-e7ae0124d2ce: Downloading signed m3u8-download manifest URL
[FranceTV] 6d716c77-0011-4ffa-bd27-e7ae0124d2ce: Downloading m3u8 information
ERROR: requested format not available
Traceback (most recent call last):
  File "/home/shnoulle/bin/youtubedl/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/shnoulle/bin/youtubedl/youtube_dl/YoutubeDL.py", line 862, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/shnoulle/bin/youtubedl/youtube_dl/YoutubeDL.py", line 1635, in process_video_result
    expected=True)
ExtractorError: requested format not available
````

**Comment by Shnoulle** [comment]
Can be closed : reported with detail here: https://github.com/ytdl-org/youtube-dl/issues/22674
