### ISSUE TITLE
chaturbate unsupported anymore

### ISSUE THREAD

**Issue by zhaodefang** [ytdl-org/youtube-dl#23093]
E:\tools\youtubesaver>youtube-dl https://zh.chaturbate.com/allayalove/
[Chaturbate] allayalove: Downloading webpage
ERROR: Room is currently offline

E:\tools\youtubesaver>youtube-dl https://zh.chaturbate.com/allayalove/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://zh.chaturbate.com/allayalove/', '-v']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.1
[debug] Proxy map: {}
[Chaturbate] allayalove: Downloading webpage
ERROR: Room is currently offline
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\chaturbate.py", line 61, in _real_extract
youtube_dl.utils.ExtractorError: Room is currently offline

**Comment by kenorb** [comment]
Dup of #23133
