### ISSUE TITLE
Some problems with TOR-proxy and chaturbate

### ISSUE THREAD

**Issue by marabu88** [ytdl-org/youtube-dl#23108]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
NEW VERSION

...>youtube-dl -v --ignore-config --proxy socks5://192.168.1.2:9050 --hls-use-mpegts "https://chaturbate.com/selenatotman"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', '--proxy', 'socks5://192.168.1.2:9050', '--hls-use-mpegts', 'https://chaturbate.com/selenatotman']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.7.4 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg N-89794-gc51301db14, rtmpdump 2.4
[debug] Proxy map: {'http': 'socks5://192.168.1.2:9050', 'https': 'socks5://192.168.1.2:9050'}
[Chaturbate] selenatotman: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python37\lib\site-packages\youtube_dl\extractor\common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "c:\python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "c:\python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

OLD VERSION

...>CB_youtube-dl -v --ignore-config --proxy socks5://192.168.1.2:9050 --hls-use-mpegts "https://chaturbate.com/selenatotman"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', '--proxy', 'socks5://192.168.1.2:9050', '--hls-use-mpegts', 'https://chaturbate.com/selenatotman']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.05.11
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-89794-gc51301db14, rtmpdump 2.4
[debug] Proxy map: {'http': 'socks5://192.168.1.2:9050', 'https': 'socks5://192.168.1.2:9050'}
[Chaturbate] selenatotman: Downloading webpage
ERROR: Room is currently offline
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4jj6sgve\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4jj6sgve\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4jj6sgve\build\youtube_dl\extractor\chaturbate.py", line 57, in _real_extract
youtube_dl.utils.ExtractorError: Room is currently offline

```

## Description

I am aware that the Сhaturbate page format has been changed and a patch is required for this site. But this problem arose a long time ago. And I just used the old version, where this problem was not. But when the new version comes out, it will not work for me through the TOR proxy, since this problem arose earlier and has not been fixed so far. It occurs already at the stage of requesting a page from Сhaturbate , before its parsing. I ask you to check what this may be connected with, because the old version worked without problems and did not give an error 403. I also know that Сhaturbate may require captcha input if you consider the traffic to be suspicious. But why did the old version work fine?

By the way, it would be very nice to have the opportunity to explicitly indicate why use a proxy. In this case, everything works automatically, since ffmpeg does not support downloading through a proxy. But for YouTube, it is desirable to be able to download a page with video through a proxy, and a page with search results, a playlist, etc. - directly, since it is now the page with the video that is being blocked.

**Comment by marabu88** [comment]
what i duplicate? and if this is "duplicate" - why you don't fix it LONG time?

**Comment by kenorb** [comment]
Dup of #23133
