### ISSUE TITLE
[Chaturbate] 403: Forbidden for socks5 proxy

### ISSUE THREAD

**Issue by marabu88** [ytdl-org/youtube-dl#23133]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
NEW VERSION (2019.11.05)

...>youtube-dl -v --ignore-config --proxy socks5://192.168.1.2:9050 --hls-use-mpegts "https://chaturbate.com/selenatotman"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', '--proxy', 'socks5://192.168.1.2:9050', '--hls-use-mpegts', 'https://chaturbate.com/selenatotman']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.7.4 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg N-89794-gc51301db14, rtmpdump 2.4
[debug] Proxy map: {'http': 'socks5://192.168.1.2:9050', 'https': 'socks5://192.168.1.2:9050'}
[Chaturbate] selenatotman: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python37\lib\site-packages\youtube_dl\extractor\common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "c:\python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "c:\python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

OLD VERSION (2019.05.11)

...>CB_youtube-dl -v --ignore-config --proxy socks5://192.168.1.2:9050 --hls-use-mpegts "https://chaturbate.com/selenatotman"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', '--proxy', 'socks5://192.168.1.2:9050', '--hls-use-mpegts', 'https://chaturbate.com/selenatotman']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.05.11
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-89794-gc51301db14, rtmpdump 2.4
[debug] Proxy map: {'http': 'socks5://192.168.1.2:9050', 'https': 'socks5://192.168.1.2:9050'}
[Chaturbate] selenatotman: Downloading webpage
ERROR: Room is currently offline
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4jj6sgve\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4jj6sgve\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4jj6sgve\build\youtube_dl\extractor\chaturbate.py", line 57, in _real_extract
youtube_dl.utils.ExtractorError: Room is currently offline
```

## Description

I KNOW ABOUT PROBLEM WITH CHATURBATE-EXTRACTOR!!! THIS IS DIFFERENT BUG! I TRY SEARCH SOMETHING LIKE THIS - BUT I DONT SEE IT AM HERE!!! If you claim that this is a duplicate, then you can probably write a message number about the same bug?! I tried changing the new extractor to the old one, with which everything works (UP TO TIME), but the problem is apparently not in it. because I just don’t understand the reasons for this error. if necessary, I can check all versions and find in which one this problem appeared. but it exists for a long time and does NOT change anything.

Why, in later versions, the page from the chaturbate site reports a 403 error, while through the same proxy at the same time the old version works fine?! Maybe me need to add some parameters? What is the point of writing here about some problems if they are simply ignored?! I have certain problems and it’s hard for me to write all these messages in a language that I don’t know well. I realized for a long time that you were sick of it, but really there are no other people who can also deal with this project more carefully?

**Comment by kenorb** [comment]
Related: GH-23012

**Comment by kenorb** [comment]
Fix in: #23012

**Comment by dstftw** [comment]
You're getting standard cloudflare captcha that is expectable for tor nodes. Why don't you get captcha on some other version? Possibly due to different order of HTTP headers sent or whatever heuristics cloudflare use. Solving captcha in browser and passing authenticated cookies to youtube-dl may help.

**Comment by marabu88** [comment]
>>> Possibly due to different order of HTTP headers sent or whatever heuristics cloudflare use. 

But if this problem was not in the old versions, then maybe YOU will help me find out what exactly affects this and make some adjustments to the program? I iterate over different TOR_proxy, but very quickly this error appears again. As I said, the new version works fine, but error 403 appears very quickly. The old version did not produce this error AT ALL. So the old version is more preferable? The easiest way for me would be to compile my own version with the same foundation, but a new extractor. Know I have no clear instructions on how I can do this on windows 10.
 
Why are you closing my request, although the problem remains relevant? Somehow, I think that you or I should not be happy that the old version WORKS better than the new one.

**Comment by marabu88** [comment]
P.s. I went through the TOR browser (this URL https://chaturbate.com/midzukki_01/ )and did not receive a request to enter captcha !!! At the same time, when I use the same browser as socks5-proxy in youtube-dl (i.e. the same IP) - I get 403 error:
[Chaturbate] midzukki_01: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by marabu88** [comment]
it seems the problem is not in youtube-dl, but in the python version.
```
OLD COMPILED EXE

...>CB_youtube-dl.exe -v
[debug] System config: []
[debug] User config: ['--cookies', 'C:\\Users\\Yuri\\AppData\\Roaming\\youtube-dl\\cookies.txt', '--sleep-interval', '1', '--max-sleep-interval', '2']
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.05.11
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-89794-gc51301db14, rtmpdump 2.4
[debug] Proxy map: {}
Usage: CB_youtube-dl.exe [OPTIONS] URL [URL...]


...>CB_youtube-dl.exe --ignore-config --proxy socks5://192.168.1.2:9050 https://chaturbate.com/lucy_lew/
[Chaturbate] lucy_lew: Downloading webpage
ERROR: Room is currently offline

=================================================================

THIS VERSION FROM PYTHON  3.7.4

...>C:\Python37\Scripts\youtube-dl.exe -v
[debug] System config: []
[debug] User config: ['--cookies', 'C:\\Users\\Yuri\\AppData\\Roaming\\youtube-dl\\cookies.txt', '--sleep-interval', '1', '--max-sleep-interval', '2']
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2019.05.11
[debug] Python version 3.7.4 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg N-89794-gc51301db14, rtmpdump 2.4
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

...>C:\Python37\Scripts\youtube-dl.exe -v --ignore-config --proxy socks5://192.168.1.2:9050 https://chaturbate.com/lucy_lew/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', '--proxy', 'socks5://192.168.1.2:9050', 'https://chaturbate.com/lucy_lew/']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2019.05.11
[debug] Python version 3.7.4 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg N-89794-gc51301db14, rtmpdump 2.4
[debug] Proxy map: {'http': 'socks5://192.168.1.2:9050', 'https': 'socks5://192.168.1.2:9050'}
[Chaturbate] lucy_lew: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python37\lib\site-packages\youtube_dl\extractor\common.py", line 626, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "c:\python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "c:\python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```
