### ISSUE TITLE
BBC video download fails

### ISSUE THREAD

**Issue by chris2614** [ytdl-org/youtube-dl#23155]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.11.05**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
chris@chris-Mpox:~$ youtube-dl -v https://www.bbc.com/news/av/stories-50425629/sucking-up-co2-from-one-of-the-world-s-worst-emitters[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.bbc.com/news/av/stories-50425629/sucking-up-co2-from-one-of-the-world-s-worst-emitters']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-166-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15, rtmpdump 2.4
[debug] Proxy map: {}
[bbc] sucking-up-co2-from-one-of-the-world-s-worst-emitters: Downloading webpage
[bbc] p07vfw4x: Downloading media selection XML
[bbc] p07vfw4x: Downloading m3u8 information
[bbc] p07vfw4x: Downloading m3u8 information
[bbc] p07vfw4x: Downloading MPD manifest
[bbc] p07vfw4x: Downloading m3u8 information
[bbc] p07vfw4x: Downloading m3u8 information
[bbc] p07vfw4x: Downloading MPD manifest
[bbc] p07vfw4x: Downloading m3u8 information
[bbc] p07vfw4x: Downloading m3u8 information
[bbc] p07vfw4x: Downloading MPD manifest
[bbc] p07vfw4x: Downloading m3u8 information
[bbc] p07vfw4x: Downloading m3u8 information
[bbc] p07vfw4x: Downloading MPD manifest
[download] Downloading playlist: Sucking up CO2 from one of the world's worst emitters
[bbc] playlist Sucking up CO2 from one of the world's worst emitters: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://vod-dash-ww-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd/7925d4-p07vfw4x/vf_p07vfw4x_96eed87c-7702-4994-a870-3c6ce076df73.ism.hlsv2.ism/iptv_hd_abr_v1_dash_master.mpd?s=1574262031&e=1574305231&h=52611c4c02bb8699bc04828e6414f457'
[download] Making concrete more environmentally friendly.-p07vfw4x.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-video=1570000.mp4 has already been downloaded
[download] 100% of 56.38MiB
[debug] Invoking downloader on u'https://vod-dash-ww-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd/7925d4-p07vfw4x/vf_p07vfw4x_96eed87c-7702-4994-a870-3c6ce076df73.ism.hlsv2.ism/iptv_hd_abr_v1_dash_master.mpd?s=1574262031&e=1574305231&h=52611c4c02bb8699bc04828e6414f457'
[download] Making concrete more environmentally friendly.-p07vfw4x.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-audio_eng_1=128000.m4a has already been downloaded
[download] 100% of 4.73MiB
[ffmpeg] Merging formats into "Making concrete more environmentally friendly.-p07vfw4x.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Making concrete more environmentally friendly.-p07vfw4x.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-video=1570000.mp4' -i 'file:Making concrete more environmentally friendly.-p07vfw4x.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-audio_eng_1=128000.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:Making concrete more environmentally friendly.-p07vfw4x.temp.mp4'
ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2064, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

chris@chris-Mpox:~$ 

```

## Description

First - previous versiopn of youtube-dl downloaded two files [audio, other] but did not finalise.

Upgraded to current version - and no download at all.

**Comment by dstftw** [comment]
Outdated ffmpeg.
