### ISSUE TITLE
match_filter

### ISSUE THREAD

**Issue by vista-narvas** [ytdl-org/youtube-dl#23167]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.11.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.22
[debug] Python version 3.5.3 (CPython) - Linux-4.9.0-11-amd64-x86_64-with-debian-9.11
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1
[debug] Proxy map: {}
[youtube] U0WnMWnttpQ: Downloading webpage
[youtube] U0WnMWnttpQ: Downloading video info webpage
[youtube] {18} signature length 108, html5 player vfl8EyRMW
[youtube] {22} signature length 108, html5 player vfl8EyRMW
[youtube] {43} signature length 108, html5 player vfl8EyRMW
[youtube] {137} signature length 108, html5 player vfl8EyRMW
[youtube] {248} signature length 108, html5 player vfl8EyRMW
[youtube] {136} signature length 108, html5 player vfl8EyRMW
[youtube] {247} signature length 108, html5 player vfl8EyRMW
[youtube] {135} signature length 108, html5 player vfl8EyRMW
[youtube] {244} signature length 108, html5 player vfl8EyRMW
[youtube] {134} signature length 104, html5 player vfl8EyRMW
[youtube] {243} signature length 108, html5 player vfl8EyRMW
[youtube] {133} signature length 104, html5 player vfl8EyRMW
[youtube] {242} signature length 104, html5 player vfl8EyRMW
[youtube] {160} signature length 108, html5 player vfl8EyRMW
[youtube] {278} signature length 108, html5 player vfl8EyRMW
[youtube] {140} signature length 108, html5 player vfl8EyRMW
[youtube] {249} signature length 104, html5 player vfl8EyRMW
[youtube] {250} signature length 108, html5 player vfl8EyRMW
[youtube] {251} signature length 108, html5 player vfl8EyRMW
[debug] Default format spec: bestvideo+bestaudio/best
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./get-subscriptions", line 96, in __init__
    self.run()
  File "./get-subscriptions", line 125, in run
    ydl.download([self.video_id])
  File "/home/youtube/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2018, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/youtube/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/youtube/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 862, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/youtube/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1643, in process_video_result
    self.process_info(new_info)
  File "/home/youtube/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1743, in process_info
    reason = self._match_entry(info_dict, incomplete=False)
  File "/home/youtube/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 758, in _match_entry
    ret = match_filter(info_dict)
TypeError: 'str' object is not callable
```

## Description

im working on a python script to download videos but when i use `match_filter` in the ydl_opts i get the error above  
i tried it with `'!is_live'`, `!is_live'` or just empty  
it does work when i don't use match_filter at all

**Comment by dstftw** [comment]
`match_filter` must be a function not string.
