### ISSUE TITLE
fix vivo

### ISSUE THREAD

**Issue by MrIcedTea** [ytdl-org/youtube-dl#23179]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've searched the bugtracker for similar issues including closed ones

- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped

## Verbose log

```
ytdl https://vivo.sx/b4eb3f649f -v
DISPLAY is unset
DISPLAY is set to ':1'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--all-subs', u'--write-info-json', u'--hls-use-mpegts', u'https://vivo.sx/b4eb3f649f', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.22
[debug] Python version 2.7.9 (CPython) - Linux-3.10.106+-armv7l-with-debian-8.11
[debug] exe versions: avconv 2.6.9, avprobe 2.6.9, ffmpeg 2.6.9, ffprobe 2.6.9, phantomjs 2
[debug] Proxy map: {}
[Vivo] b4eb3f649f: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/treaki/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/home/treaki/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/home/treaki/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/home/treaki/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "/home/treaki/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/shared.py", line 26, in _real_extract
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/shared.py", line 120, in _extract_video_url
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/shared.py", line 116, in decode_url
  File "/home/treaki/bin/youtube-dl/youtube_dl/compat.py", line 2947, in compat_b64decode
  File "/usr/lib/python2.7/base64.py", line 73, in b64decode
    return binascii.a2b_base64(s)
TypeError: must be string or buffer, not None

```

## Description

please fix vivo.sx or switch it pack to default extractor which should be compatible to

thanks

**Comment by MrIcedTea** [comment]
BTW im aware of  #22328 and even  #22279 so ive opened this cause were still waiting, but thanks to that i am now able to learn git and python somehow at least ;) (that thanks was irony in case you also missed this)

no offence but please keep up with your work or add donation requests, im willing to donate but only if one site is fixed within 24 h

**Comment by MrIcedTea** [comment]
thanks  @dstftw , could you also do some merging?
