### ISSUE TITLE
Reopen 23155 - not fixed

### ISSUE THREAD

**Issue by chris2614** [ytdl-org/youtube-dl#23195]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.11.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
chris@chris-Mpox:~$ youtube-dl -v https://www.bbc.com/news/av/embed/p07vfw4x/50425629
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.bbc.com/news/av/embed/p07vfw4x/50425629']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-169-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15, rtmpdump 2.4
[debug] Proxy map: {}
[bbc] 50425629: Downloading webpage
[bbc] p07vfw4x: Downloading media selection XML
[bbc] p07vfw4x: Downloading m3u8 information
[bbc] p07vfw4x: Downloading m3u8 information
[bbc] p07vfw4x: Downloading MPD manifest
[bbc] p07vfw4x: Downloading m3u8 information
[bbc] p07vfw4x: Downloading m3u8 information
[bbc] p07vfw4x: Downloading MPD manifest
[bbc] p07vfw4x: Downloading m3u8 information
[bbc] p07vfw4x: Downloading m3u8 information
[bbc] p07vfw4x: Downloading MPD manifest
[bbc] p07vfw4x: Downloading m3u8 information
[bbc] p07vfw4x: Downloading m3u8 information
[bbc] p07vfw4x: Downloading MPD manifest
[download] Downloading playlist: Sucking up CO2 from one of the world's worst emitters
[bbc] playlist Sucking up CO2 from one of the world's worst emitters: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://vod-dash-ww-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd/7925d4-p07vfw4x/vf_p07vfw4x_96eed87c-7702-4994-a870-3c6ce076df73.ism.hlsv2.ism/iptv_hd_abr_v1_dash_master.mpd?s=1574608320&e=1574651520&h=a3e51a41889eb83e65e147253449e31d'
[download] Making concrete more environmentally friendly.-p07vfw4x.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-video=1570000.mp4 has already been downloaded
[download] 100% of 56.38MiB
[debug] Invoking downloader on u'https://vod-dash-ww-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd/7925d4-p07vfw4x/vf_p07vfw4x_96eed87c-7702-4994-a870-3c6ce076df73.ism.hlsv2.ism/iptv_hd_abr_v1_dash_master.mpd?s=1574608320&e=1574651520&h=a3e51a41889eb83e65e147253449e31d'
[download] Making concrete more environmentally friendly.-p07vfw4x.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-audio_eng_1=128000.m4a has already been downloaded
[download] 100% of 4.73MiB
[ffmpeg] Merging formats into "Making concrete more environmentally friendly.-p07vfw4x.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Making concrete more environmentally friendly.-p07vfw4x.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-video=1570000.mp4' -i 'file:Making concrete more environmentally friendly.-p07vfw4x.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-audio_eng_1=128000.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:Making concrete more environmentally friendly.-p07vfw4x.temp.mp4'
ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2064, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

chris@chris-Mpox:~$ ffmpeg -version
ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
chris@chris-Mpox:~$ 

```

## Description

WRITE DESCRIPTION HERE

**Comment by remitamine** [comment]
Again, update FFmpeg, the latest version is `4.2.1` not `2.8.15`.

**Comment by chris2614** [comment]
Fixed now
