### ISSUE TITLE
eroprofile.com site updates from ~2wks back broke youtube-dl

### ISSUE THREAD

**Issue by ta-ytdl** [ytdl-org/youtube-dl#23200]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2019.11.22**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.eroprofile.com/m/videos/view/Wow-574']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2019.11.22
[debug] Python version 3.8.0 (CPython) - Linux-5.3.12-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, rtmpdump 2.4
[debug] Proxy map: {}
[EroProfile] Wow-574: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/eroprofile.py", line 82, in _real_extract
    title = self._html_search_regex(
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

EroProfile restyled their website so youtube-dl is no longer in sync with it - the page elements are not where they're expected to be.

**Comment by khaosis** [comment]
Only the title element changed, now they use <title> in the HTML header. Here you go:
```
--- a/youtube_dl/extractor/eroprofile.py
+++ b/youtube_dl/extractor/eroprofile.py
@@ -80,7 +80,7 @@ class EroProfileIE(InfoExtractor):
         video_url = unescapeHTML(self._search_regex(
             r'<source src="([^"]+)', webpage, 'video url'))
         title = self._html_search_regex(
-            r'Title:</th><td>([^<]+)</td>', webpage, 'title')
+            r'<title>([^<]+)</title>', webpage, 'title')
         thumbnail = self._search_regex(
             r'onclick="showVideoPlayer\(\)"><img src="([^"]+)',
             webpage, 'thumbnail', fatal=False)
```

**Comment by richjn** [comment]
I note that @YetAnotherGhost has a patch pending-fixes but just wanted to comment that @khaosis patch here does resolve the issue for me.
