### ISSUE TITLE
<urlopen error [Errno 101] Network is unreachable> (Access Denied from link from extractor)

### ISSUE THREAD

**Issue by SwissCheese5** [ytdl-org/youtube-dl#23213]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.11.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[youtube] {394} signature length 105, html5 player vfly7X4ko
[youtube] {140} signature length 105, html5 player vfly7X4ko
[youtube] {249} signature length 105, html5 player vfly7X4ko
[youtube] {250} signature length 105, html5 player vfly7X4ko
[youtube] {251} signature length 105, html5 player vfly7X4ko
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r3---sn-vgqsknel.googlevideo.com/videoplayback?expire=1574799606&ei=lTTdXYu5PMfIwQHuiJigBg&ip=35.209.189.190&id=o-APYq2Wo-W_sG62bi8Bo9xDN7Iicb247A4jAOCA8O-6vt&itag=18&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-vgqsknel%2Csn-q4flrner&ms=au%2Conr&mv=u&mvi=2&pl=21&gcr=us&mime=video%2Fmp4&gir=yes&clen=10546029&ratebypass=yes&dur=229.366&lmt=1570189913691762&mt=1574777789&fvip=3&fexp=23842630&beids=9466585&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AHylml4wRQIhAKrUXchxy3PHPw8XyARN018s3OaqD2rrNUGWksOnY0ZEAiBteMEe5_tp4c8d36Sv4wFE7m0Y5j4ExEDsp3j4Rm80Tg%3D%3D&sig=ALgxI2wwRAIgfsLa-kMCnXn13rUpNcWegE9-r2AiH5tybXAXG3qcb2QCIEJsl1ceXxKNb8Z8fuRoYXpkpkRapnQ4_5vhsSIawruM'
ERROR: unable to download video data: <urlopen error [Errno 101] Network is unreachable>
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1925, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1864, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2724, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 101] Network is unreachable>
```

## Description

This is running on my Google Compute Engine (GCE) server. The returned URL from the verbose command leads to this page:
![image](https://user-images.githubusercontent.com/7407478/69641710-5dd3e600-1069-11ea-997e-09f503b76a2c.png)
My server, myself, my friend, and both our discord clients are receiving the Access Denied error (we're in completely different parts of the world).

I didn't download anything too many times, it didn't work from the first time.

My firewall rules allow all traffic of all types: 
![image](https://user-images.githubusercontent.com/7407478/69642069-e18dd280-1069-11ea-9b4f-a442ccb6687d.png)

**Comment by dstftw** [comment]
Your server does not receive access denied as clearly seen from the log but network is unreachable error indicating connectivity issue between your server and download host.

**Comment by SwissCheese5** [comment]
The thing is that all ports are open, and I've verified this. I can ping google.com and youtube.com, I can use both curl and wget to download youtube-dl, I can access my server webpage through my browser so it's definitely able to process everything. I've made sure both http and https are supported by the server.

I even uninstalled curl and youtube-dl then redownloaded youtube-dl with wget.

wget'ting the link yields the following log (nothing different)
```
Resolving r2---sn-5uaeznyz.googlevideo.com (r2---sn-5uaeznyz.googlevideo.com)... 173.194.144.71, 2607:f8b0:4002:3e::7
Connecting to r2---sn-5uaeznyz.googlevideo.com (r2---sn-5uaeznyz.googlevideo.com)|173.194.144.71|:443... failed: Connection timed out.
Connecting to r2---sn-5ualdn7s.googlevideo.com (r2---sn-5ualdn7s.googlevideo.com)|2607:f8b0:4002:2f::8|:443... failed: Network is unreachable.
failed: Connection timed out.
Connecting to r2---sn-5ualdn7s.googlevideo.com (r2---sn-5ualdn7s.googlevideo.com)|2607:f8b0:4002:2f::8|:443... failed: Network is unreachable.
failed: Connection timed out.
Connecting to r2---sn-5uaeznyz.googlevideo.com (r2---sn-5uaeznyz.googlevideo.com)|2607:f8b0:4002:3e::7|:443... failed: Network is unreachable.
[2]-  Exit 4                  wget https://r2---sn-5ualdn7s.googlevideo.com/videoplayback?expire=1574808322
[3]+  Exit 4                  wget https://r2---sn-5ualdn7s.googlevideo.com/videoplayback?expire=1574808322
```

Not sure what possible connectivity issues can exist that I'm missing, What else can I verify?

**Comment by Producer86** [comment]
@dstftw Same issue here, http host reached, webpage download succeeds but downloader gives 101

**Comment by dstftw** [comment]
As already pointed out: network issue on your side, nothing to do with youtube-dl.
