### ISSUE TITLE
Unable to extract swf url for adobeconnect

### ISSUE THREAD

**Issue by hnmrhhgkd** [ytdl-org/youtube-dl#23228]
I've verified that I'm running youtube-dl version 2019.11.22

E:\youtube-dl>youtube-dl --verbose https://ianimate.adobeconnect.com/_a959616276/pgbw94i9lmfz/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://ianimate.adobeconnect.com/_a959616276/pgbw94i9lmfz/']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2019.11.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2019-11-25-d5e3d8e, ffprobe git-2019-11-25-d5e3d8e
[debug] Proxy map: {'https': 'https://127.0.0.1:1972', 'http': 'http://127.0.0.1:1972', 'ftp': 'ftp://127.0.0.1:1972'}
[AdobeConnect] _a959616276: Downloading webpage
ERROR: Unable to extract swf url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\extractor\adobeconnect.py", line 18, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract swf url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by hnmrhhgkd** [comment]
rtmpdump-2.3
youtube-dl 2019.11.22

E:\youtube-dl>youtube-dl --cookies cookies.txt https://ianimate.adobeconnect.com/_a959616276/peyls8ec65eg
[AdobeConnect] _a959616276: Downloading webpage
[download] Destination: week-8-_a959616276.flv
[rtmpdump] Downloaded 0 bytes


ERROR: rtmpdump exited with code 1

**Comment by remitamine** [comment]
outdated `rtmpdump`.
