### ISSUE TITLE
ERROR: Unable to extract uploader name

### ISSUE THREAD

**Issue by prabhatsoni99** [ytdl-org/youtube-dl#23247]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2019.11.22**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
prabhat@PrabhatsPC:~$ youtube-dl --verbose --extract-audio --audio-format mp3 # the command I gave

https://www.youtube.com/watch?v=WPni755-Krg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--extract-audio', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=WPni755-Krg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-70-generic-x86_64-with-LinuxMint-19.2-tina
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] WPni755-Krg: Downloading webpage
[youtube] WPni755-Krg: Downloading video info webpage
WARNING: Unable to extract video title
[youtube] WPni755-Krg: Extracting video information
ERROR: Unable to extract uploader name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1704, in _real_extract
    raise ExtractorError('Unable to extract uploader name')
youtube_dl.utils.ExtractorError: Unable to extract uploader name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

This is strange. Also, I tried downloading this video from a few other websites like `https://sconverter.com/` and it also gave error after downloading around 10-15 MB.

**Comment by prabhatsoni99** [comment]
Ok just realised my version was not `2019.11.22`. I had installed from apt repository
