### ISSUE TITLE
[youtube] Sporadic download failure on some vevo videos

### ISSUE THREAD

**Issue by MCterra10** [ytdl-org/youtube-dl#23262]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2019.11.28**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=Um7pMggPnug']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-94054-gdd357d76e5
[debug] Proxy map: {}
[youtube] Um7pMggPnug: Downloading webpage
[youtube] Um7pMggPnug: Downloading video info webpage
ERROR: This video is not available.
Sorry about that.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\youtube.py", line 2148, in _real_extract
youtube_dl.utils.ExtractorError: This video is not available.
Sorry about that.
```
and
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'www.youtube.com/watch?v=MYxAiK6VnXw']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-94054-gdd357d76e5
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[youtube] MYxAiK6VnXw: Downloading webpage
[youtube] MYxAiK6VnXw: Downloading video info webpage
ERROR: The uploader has not made this video available in your country.
Sorry about that.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\youtube.py", line 2148, in _real_extract
youtube_dl.utils.ExtractorError: The uploader has not made this video available in your country.
Sorry about that.
```

## Description

Known broken URLs
https://www.youtube.com/watch?v=L_jWHffIx5E (Smash Mouth - All Star)
https://www.youtube.com/watch?v=Um7pMggPnug (Katy Perry - Chained to the Rhythm)
https://www.youtube.com/watch?v=WS7f5xpGYn8 (Katy Perry - Hey Hey Hey)
https://www.youtube.com/watch?v=MYxAiK6VnXw (OutKast - Ms. Jackson)

Only occurs on Vevo channels as far as my testing shows, and not all Vevo channels and videos are broken, for example Smash Mouth - I'm a Believer (https://www.youtube.com/watch?v=0mYBSayCsH0) works fine despite another video on their channel being broken.

In addition, the last video listed above (Ms. Jackson) has a different error (ERROR: The uploader has not made this video available in your country.) despite playing fine in my browser. Full debug log for that included above too. Actual error in youtube-dl code is identical as far as I can tell.

From my limited and poorly informed debugging of youtube-dl code, it seems to be an error from YouTube itself, and not one coded into youtube-dl. Hopefully this is enough information to debug.

**Comment by MCterra10** [comment]
Error still ongoing, issue really shouldn't be closed without a follow up. It helps to at least ask for more information.
