### ISSUE TITLE
drtv ramasjang fails to download

### ISSUE THREAD

**Issue by signout** [ytdl-org/youtube-dl#23278]
- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2019.11.28**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

youtube-dl -v https://www.dr.dk/drtv/program/hugo-og-holger_152801
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.dr.dk/drtv/program/hugo-og-holger_152801']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.2.1, ffprobe 4.2.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] hugo-og-holger_152801: Requesting header
WARNING: Falling back on generic information extractor.
[generic] hugo-og-holger_152801: Downloading webpage
[generic] hugo-og-holger_152801: Extracting information
ERROR: Unsupported URL: https://www.dr.dk/drtv/program/hugo-og-holger_152801
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2372, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: mismatched tag: line 5, column 14
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3347, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.dr.dk/drtv/program/hugo-og-holger_152801

## Description

Fails to download video. Nothing more to add :)

**Comment by barsnick** [comment]
I believe DR's complete URL scheme has changed. Possibly even the download scheme.

I was trying to download this non-geoblocked show, which plays fine in the browser:
https://www.dr.dk/drtv/se/troldspejlet-and-co_-star-wars-gyserspil-_-og-iben-hjejle_152168
(Ja, på grunn av Iben Hjejle. ;-))

**Comment by signout** [comment]
They changed the entire streaming platform, but youtube-dl was uploaded to support the new form. drtv obviously changed something else after that update.

**Comment by LouisDK1** [comment]
A workaround for now is to convert a link to the url URL scheme. It works at least if the show has published prior to the launch of the new DR TV platform.

> youtube-dl -v https://www.dr.dk/drtv/program/hugo-og-holger_152801
> Fails to download video. Nothing more to add :)

Try: `youtube-dl https://www.dr.dk/tv/se/hugo-og-holger/hugo-og-holger`

**Comment by signout** [comment]
Thank you for the workaround that helped fetching the example URL.

The issue still needs some work in order to work for new content as well :)

**Comment by signout** [comment]
This issue has been solved in the 2020.01.01 release

**Comment by signout** [comment]
Sorry. https://www.dr.dk/drtv/program/hugo-og-holger_152801 still won't download. I tried using https://www.dr.dk/drtv/se/troldspejlet-and-co_-star-wars-gyserspil-_-og-iben-hjejle_152168 and that worked. Original issue is still not fixed.

**Comment by naffit** [comment]
https://www.dr.dk/drtv/program/hugo-og-holger_152801 contains a "play now" button that leads to https://www.dr.dk/drtv/se/hugo-og-holger_152801 and the 2020.01.01 release can download that. I agree that it would be nice that the original url works as well, but the /se/ (danish for "see") URL works fine..

**Comment by signout** [comment]
https://www.dr.dk/drtv/se/saa-er-der-tegnefilm_160544 can't be downloaded. Works fine in my browser, but returns 404 when trying youtube-dl.

youtube-dl https://www.dr.dk/drtv/se/saa-er-der-tegnefilm_160544
[drtv] saa-er-der-tegnefilm_160544: Downloading webpage
[drtv] 00851907130: Downloading video JSON
[drtv] 00851907130: Downloading m3u8 information
[drtv] 00851907130: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 121
[download] Destination: Så er der tegnefilm-00851907130.mp4
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 10 of 10)...
[download] Skipping fragment 1...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 10 of 10)...
[download] Skipping fragment 2...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3 (attempt 6 of 10)...

**Comment by signout** [comment]
the 404 issue was observed with both 2020.02.16 and 2020.03.08
