### ISSUE TITLE
Tracks in Bandcamp albums without play button fail entire download

### ISSUE THREAD

**Issue by Fabian42** [ytdl-org/youtube-dl#23282]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
fabian@fabian:~/drive/music/a0/circles$ youtube-dl -v https://music.biggiantcircles.com/album/the-glory-days
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://music.biggiantcircles.com/album/the-glory-days']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-11-amd64-x86_64-with-debian-9.11
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] the-glory-days: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-glory-days: Downloading webpage
[generic] the-glory-days: Extracting information
[Bandcamp:album] the-glory-days: Downloading webpage
[download] Downloading playlist: The Glory Days
[Bandcamp:album] playlist The Glory Days: Collected 32 video ids (downloading 32 of them)
[download] Downloading video 1 of 32
[Bandcamp] go-for-distance: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/8aca2ef5d9b3d2d4ae52755b911c9905/mp3-128/3723528121?p=0&ts=1575293754&t=9210fe8f9fa5dcfc882584f5acf8e1c331bdedeb&token=1575293754_12bd3e292a5dc715edc610ce581c2cd11c122fcc'
[download] Big Giant Circles - Go For Distance-3723528121.mp3 has already been downloaded
[download] 100% of 4.58MiB
[download] Downloading video 2 of 32
[Bandcamp] relapse: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/a2bd1b5c325b017d135b6051c6f877a6/mp3-128/3349349138?p=0&ts=1575293756&t=35e29f110e1e542dc16459af5ddf0b317873cac8&token=1575293756_8c36fafb8d9b2a612cead96343b9053e02393c53'
[download] Big Giant Circles - Relapse-3349349138.mp3 has already been downloaded
[download] 100% of 2.49MiB
[download] Downloading video 3 of 32
[Bandcamp] no-party-like-a-mojang-party: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/4d8cf74c42e9aab5f7f06880f15b56fe/mp3-128/595907577?p=0&ts=1575293758&t=8966160c35c6bdd10b5ee7a2808c3f225d8e7c9e&token=1575293758_e3a3633975f58dc8743e9011e3d3a20d5d7fbac3'
[download] Big Giant Circles - No Party Like a Mojang Party-595907577.mp3 has already been downloaded
[download] 100% of 5.61MiB
[download] Downloading video 4 of 32
[Bandcamp] a-rose-in-a-field: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/e0c9506957797dc0e00a4eebd5b52ef5/mp3-128/3449427748?p=0&ts=1575293759&t=2299edc50d0b7010169bf7ae1e58c3bd585d05f6&token=1575293759_2dd8181ec9579d6736597f6e4d407061c1f46c12'
[download] Big Giant Circles - A Rose in a Field-3449427748.mp3 has already been downloaded
[download] 100% of 3.17MiB
[download] Downloading video 5 of 32
[Bandcamp] sevcon: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/a898fd68e7c1cdca15891c4dd710704f/mp3-128/2915127326?p=0&ts=1575293761&t=97f7d62d6d335cfbdbb28cce8509e02251cfcbac&token=1575293761_f6b98d46cb8f89086c325c192399ab1cd294e7b4'
[download] Big Giant Circles - Sevcon-2915127326.mp3 has already been downloaded
[download] 100% of 4.47MiB
[download] Downloading video 6 of 32
[Bandcamp] chip-zeal: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/cfbc37a26fbb47b9330b83623af59629/mp3-128/3382903921?p=0&ts=1575293763&t=76429416c8dd1f7870a9c72a0cab725891e191ee&token=1575293763_856d8805bbabfbc19851bf072e677aee8275e069'
[download] Big Giant Circles - Chip Zeal-3382903921.mp3 has already been downloaded
[download] 100% of 3.48MiB
[download] Downloading video 7 of 32
[Bandcamp] houston: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/62a1a02b140161cb77268923e1647677/mp3-128/2888313275?p=0&ts=1575293764&t=d7a324c145d356d38706ac8b05367b0af960e48b&token=1575293764_0f57d9b464b343838219b713f8ee02b8d6ef3696'
[download] Big Giant Circles - Houston-2888313275.mp3 has already been downloaded
[download] 100% of 5.18MiB
[download] Downloading video 8 of 32
[Bandcamp] gront-is-a-muppet: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/3c172f13c8de54b7da0465a20ea1dfa2/mp3-128/303892001?p=0&ts=1575293766&t=c6e9ee401b47e48277850bff03062821b9e29c06&token=1575293766_9b55b5d3995a7fbd2b2e1ecdd916d73138277e29'
[download] Big Giant Circles - Gront is a Muppet-303892001.mp3 has already been downloaded
[download] 100% of 3.54MiB
[download] Downloading video 9 of 32
[Bandcamp] interlude: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/12c9b026dc1cd7f2fb3813bb8c370657/mp3-128/2697669589?p=0&ts=1575293768&t=e78b135ac4e5b74cc36c5fff2b23a2d3a53cb664&token=1575293768_e2cd2bdc662a4a6f7ad167a70182ee165ccb9811'
[download] Big Giant Circles - Interlude-2697669589.mp3 has already been downloaded
[download] 100% of 1.20MiB
[download] Downloading video 10 of 32
[Bandcamp] the-trials-of-man: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/34214e629a2f8ba7dde611255c346f00/mp3-128/2531766176?p=0&ts=1575293769&t=7383ec2a71dae2f182de44b781f5101a5a5ae7b1&token=1575293769_042993e13b45108f174fcb083fbdc5ec5403ec53'
[download] Big Giant Circles - The Trials of MAN-2531766176.mp3 has already been downloaded
[download] 100% of 3.75MiB
[download] Downloading video 11 of 32
[Bandcamp] snowcones: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/1ea2366fef043f07f94ab9502ac6d997/mp3-128/2281840736?p=0&ts=1575293771&t=fe21c949f72144dd3e17762cb135a61bd8d4e290&token=1575293771_d319123524f252a0659aa451c46f3f27d79d7ff6'
[download] Big Giant Circles - Snowcones-2281840736.mp3 has already been downloaded
[download] 100% of 3.05MiB
[download] Downloading video 12 of 32
[Bandcamp] viceroy-danny-von-b: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/858a5ee5f378e498a3c093db1fab80a5/mp3-128/2862262663?p=0&ts=1575293773&t=379618849462b8a3e31b40e3eb0dddb35fb187e9&token=1575293773_3fb4ba3a5af775b416d6e5ad575e391e86e5d3d9'
[download] Big Giant Circles - Viceroy Danny Von B-2862262663.mp3 has already been downloaded
[download] 100% of 3.86MiB
[download] Downloading video 13 of 32
[Bandcamp] artifact-hunter: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/431c9ffefa50adf858e0d8b3f8440f38/mp3-128/4222873677?p=0&ts=1575293775&t=6100c0eda271ab2c6cc6879e687e46ec681b40ab&token=1575293775_5ccddb67e6fe422ed61339cf2971f61d99388d3e'
[download] Big Giant Circles - Artifact Hunter-4222873677.mp3 has already been downloaded
[download] 100% of 3.03MiB
[download] Downloading video 14 of 32
[Bandcamp] virtuoso-sexy: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/76bf1ddb19af547acbf67aad7cba9479/mp3-128/1778830333?p=0&ts=1575293777&t=a42ade0b7fcf955ee11ef93a1c30a13080c55b14&token=1575293777_17d9d55c14cc6f0b6c0d8c1b93a5d089e88d4230'
[download] Big Giant Circles - VIRTuoso Sexy-1778830333.mp3 has already been downloaded
[download] 100% of 3.01MiB
[download] Downloading video 15 of 32
[Bandcamp] vindicate-me-instrumental: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/fa7dbfa43b973b58342e6547f20839e2/mp3-128/3798577245?p=0&ts=1575293779&t=31763d63b8fa620e3d7f30f89b1853ba39182e53&token=1575293779_a31bd4c2d1e6a04980bdae0244a4f3f86d368ec5'
[download] Big Giant Circles - Vindicate Me (instrumental)-3798577245.mp3 has already been downloaded
[download] 100% of 3.42MiB
[download] Downloading video 16 of 32
[Bandcamp] wintory-fresh: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/3818791a05409de450f343a67e82a6d4/mp3-128/2075221840?p=0&ts=1575293781&t=5a09d883c84aae862bb9c1728b2f29a704070de3&token=1575293781_58b6aef868c4cd17cfdeea3d79d3235e8a8e0d56'
[download] Big Giant Circles - Wintory Fresh-2075221840.mp3 has already been downloaded
[download] 100% of 2.16MiB
[download] Downloading video 17 of 32
[Bandcamp] biceps-blaster: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/939d4c9618db8583b56591aaae37358f/mp3-128/1690260940?p=0&ts=1575293783&t=d1c4d631f16a20a90e3e66c38e9bb4cc397b25d8&token=1575293783_9b50b20a7752d737e5f5a1ba39394b3723293c9b'
[download] Big Giant Circles - Biceps Blaster-1690260940.mp3 has already been downloaded
[download] 100% of 2.59MiB
[download] Downloading video 18 of 32
[Bandcamp] micksplosions: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/32e63f26512d962acbeefc1aff5b54af/mp3-128/3316742562?p=0&ts=1575293785&t=9186aa1a11edadc8a7a5271ed9e63876484f8f96&token=1575293785_1a7813cd48c90621e43bc077f85d66e36f56b8b3'
[download] Big Giant Circles - Micksplosions-3316742562.mp3 has already been downloaded
[download] 100% of 4.10MiB
[download] Downloading video 19 of 32
[Bandcamp] peanut-butter-cupquakes: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/ad2f1d9b4ce6d9275938326ddf219707/mp3-128/2320409568?p=0&ts=1575293786&t=6a8f5ab410cb141ddd4d464f1eafb48319146977&token=1575293786_e4f388d50fc36d760f031050f8dca502ccbc84d4'
[download] Big Giant Circles - Peanut Butter Cupquakes-2320409568.mp3 has already been downloaded
[download] 100% of 4.92MiB
[download] Downloading video 20 of 32
[Bandcamp] the-glory-days: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/1d52c655e5d303b4052bc3e7084554e5/mp3-128/729056741?p=0&ts=1575293788&t=5f6f450e8b2d7d497476d47d0460708566aeaf7e&token=1575293788_aea19298ce489923de1ad544122b82094260a8e1'
[download] Big Giant Circles - The Glory Days-729056741.mp3 has already been downloaded
[download] 100% of 5.32MiB
[download] Downloading video 21 of 32
[Bandcamp] the-chiptune-legacy: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://t4.bcbits.com/stream/b715af44b4bb8557c2d11c82bef7294c/mp3-128/2214542757?p=0&ts=1575293790&t=30e71c1845ba62e32f35d975ec2813441d4c7f00&token=1575293790_755fcdad9f3d87a15a50d3534dbbb3db3f73c33a'
[download] Big Giant Circles - The Chiptune Legacy-2214542757.mp3 has already been downloaded
[download] 100% of 3.42MiB
[download] Downloading video 22 of 32
[Bandcamp] artifact-hunter-loopable-bonus: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bandcamp.py", line 196, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Some tracks in this Bandcamp album have no play button and when clicked on lead to a page that mentions "sold out": https://music.biggiantcircles.com/album/the-glory-days I don't know what this is about and how a digital track can be sold out, but it makes youtube-dl fail and stop downloading the album completely, so I'm reporting it here.

**Comment by dstftw** [comment]
`-i`.

**Comment by Fabian42** [comment]
Sure, that would work around the problem, but isn't it still a bug that it tries to download the track and fails?
