### ISSUE TITLE
token" parameter not in video info for unknown reason

### ISSUE THREAD

**Issue by philipdw** [ytdl-org/youtube-dl#23285]
First of all, thank you for such an amazing piece of software.

I got the following bug while trying to download https://www.youtube.com/watch?v=uu5T3sWAg0w

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['uu5T3sWAg0w', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.18.1
[debug] Python version 3.5.3 - Linux-4.19.44-04937-gd773af751792-x86_64-with-debian-9.11
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] uu5T3sWAg0w: Downloading webpage
[youtube] uu5T3sWAg0w: Downloading video info webpage
ERROR: uu5T3sWAg0w: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1502, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: uu5T3sWAg0w: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by philipdw** [comment]
I downloaded the app through sudo apt-get install just now. Will check if it's outdated though...

**Comment by philipdw** [comment]
I have solved this by using pip
