### ISSUE TITLE
[tv2dk] TV2bornholm doesn't work

### ISSUE THREAD

**Issue by hakanw** [ytdl-org/youtube-dl#23291]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-x', u'http://play.tv2bornholm.dk/?area=specifikTV&id=781067', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Git HEAD: 42f8bfef8
[debug] Python version 2.7.10 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ?area=specifikTV&id=781067: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?area=specifikTV&id=781067: Downloading webpage
[generic] ?area=specifikTV&id=781067: Extracting information
ERROR: Unsupported URL: http://play.tv2bornholm.dk/?area=specifikTV&id=781067
Traceback (most recent call last):
  File "/Users/hakan/youtube-dl/youtube_dl/extractor/generic.py", line 2372, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/Users/hakan/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/Users/hakan/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 11, column 77
Traceback (most recent call last):
  File "/Users/hakan/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/Users/hakan/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/Users/hakan/youtube-dl/youtube_dl/extractor/generic.py", line 3347, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://play.tv2bornholm.dk/?area=specifikTV&id=781067
```

## Description

TV2.dk support was recently added (tv2lorry.dk, tv2fyn.dk and other related domains). I would like to request the ability to also parse this site: tv2bornholm.dk.

Example video: http://play.tv2bornholm.dk/?area=specifikTV&id=781067

**Comment by hakanw** [comment]
We'll gladly donate to the project if this can be fixed. Thanks a lot!
