### ISSUE TITLE
Request support for paramountnetwork.it

### ISSUE THREAD

**Issue by tudo75** [ytdl-org/youtube-dl#23295]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.paramountnetwork.it/episodi/zqgq1b/eye-candy-episodio-9-stagione-1-ep-9
- Single video: https://www.paramountnetwork.it/episodi/w4f9xh/una-coppia-in-affari-episodio-9-stagione-1-ep-9
- Single video: https://www.paramountnetwork.it/episodi/oyiiyq/hotel-da-incubo-episodio-12-stagione-7-ep-12

## Description

Here is my response when I tried

# youtube-dl.exe -v -F https://www.paramountnetwork.it/episodi/zqgq1b/eye-candy-episodio-9-stagione-1-ep-9
[debug] System config: []
[debug] User config: ['-v', '-o', '.\\%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.paramountnetwork.it/episodi/zqgq1b/eye-candy-episodio-9-stagione-1-ep-9']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] eye-candy-episodio-9-stagione-1-ep-9: Requesting header
WARNING: Falling back on generic information extractor.
[generic] eye-candy-episodio-9-stagione-1-ep-9: Downloading webpage
[generic] eye-candy-episodio-9-stagione-1-ep-9: Extracting information
ERROR: Unsupported URL: https://www.paramountnetwork.it/episodi/zqgq1b/eye-candy-episodio-9-stagione-1-ep-9
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\generic.py", line 3347, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.paramountnetwork.it/episodi/zqgq1b/eye-candy-episodio-9-stagione-1-ep-9

**Comment by ElRattin** [comment]
it would be great to have support for paramount network.
Since it's a viacom channel it uses mtvnservices for the streaming

**Comment by miltonjoe3** [comment]
Please include  support for all paramount networks, not just '.it' domain. 

Also, please include support for https://daftsex.com/

**Comment by remitamine** [comment]
for any unrelated requests open a new issue.
