### ISSUE TITLE
Vlive Fanship - No video formats found

### ISSUE THREAD

**Issue by wiznaibus** [ytdl-org/youtube-dl#23309]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: ['--yes-playlist']
[debug] Custom config: []
[debug] Command-line args: ['-o', '%(playlist)s/%(title)s-%(id)s.%(ext)s', '--write-sub', '--embed-subs', '--sub-format', 'ass', '--sub-lang', 'en,en_US', '--yes-playlist', '--ignore-errors', '--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose', 'https://www.vlive.tv/video/162774?channelCode=ADBA2F']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-89894-g18e2ac032e, ffprobe N-89894-g18e2ac032e
[debug] Proxy map: {}
[vlive] Downloading login cookies
[vlive] Logging in
[vlive] Downloading login info
[vlive] 162774: Downloading webpage
[vlive] 162774: Downloading live webpage
[vlive] 162774: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\vlive.py", line 124, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\vlive.py", line 209, in _replay
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I am trying to download a video from Vlive using a Fanship subscription and am running into a "no video formats found" error. I am able to download non-Fanship videos using the same command without issue. The video appears to be MPEG-DASH format using `.ts` file segments, but I don't know enough about streaming formats to provide additional information.

URL of Fanship video throwing errors: https://www.vlive.tv/video/162774?channelCode=ADBA2F
URL of video that downloads successfully: https://www.vlive.tv/video/163350?channelCode=ADBA2F

Please email me for my account credentials: wiznaibuswaltz@gmail.com

Thank you!

**Comment by wiznaibus** [comment]
Did some digging and saw the video was DRM protected. Thanks!
