### ISSUE TITLE
Build error on Heroku: ERROR: unable to locate `youtube-dl` at ' + binPath

### ISSUE THREAD

**Issue by jjg77** [ytdl-org/youtube-dl#23336]
Getting the following build error:

2019-12-06T17:28:12.044805+00:00 app[web.1]: /app/node_modules/youtube-dl/lib/get-binary.js:11
2019-12-06T17:28:12.044809+00:00 app[web.1]: throw new Error('ERROR: unable to locate `youtube-dl` at ' + binPath)
2019-12-06T17:28:12.044811+00:00 app[web.1]: ^
2019-12-06T17:28:12.044881+00:00 app[web.1]: /app/node_modules/youtube-dl/lib/get-binary.js:1
2019-12-06T17:28:12.044884+00:00 app[web.1]: Error: ERROR: unable to locate `youtube-dl` at /app/node_modules/youtube-dl/bin
2019-12-06T17:28:12.044886+00:00 app[web.1]: at module.exports (/app/node_modules/youtube-dl/lib/get-binary.js:11:11)
2019-12-06T17:28:12.044888+00:00 app[web.1]: at Object.<anonymous> (/app/node_modules/youtube-dl/lib/youtube-dl.js:18:41)
2019-12-06T17:28:12.044891+00:00 app[web.1]: at Generator.next (<anonymous>)
2019-12-06T17:28:12.044893+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
2019-12-06T17:28:12.105947+00:00 app[web.1]: npm ERR! code ELIFECYCLE

**Comment by remitamine** [comment]
report to the relevant project(most likely `node-youtube-dl` project).
