### ISSUE TITLE
Unable to extract video description

### ISSUE THREAD

**Issue by PedroMSantosD** [ytdl-org/youtube-dl#23335]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2019.11.28**
```
$ pip freeze | grep youtu
youtube-dl==2019.11.28

```
- [x ] I've checked that all provided URLs are alive and playable in a browser
```
$ cat LISTAMUSICA 
https://www.youtube.com/watch?v=3fxq7kqyWO8
https://www.youtube.com/watch?v=DT61L8hbbJ4
https://www.youtube.com/watch?v=Gc3tqnhmf5U
https://www.youtube.com/watch?v=U-ZNfo_NlIU
https://www.youtube.com/watch?v=B7xai5u_tnk

```
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
This [#23331](https://github.com/ytdl-org/youtube-dl/issues/23331)    has been closed without comments

- [x] I've read bugs section in FAQ

## Verbose log

PASTE VERBOSE LOG HERE

```
$ youtube-dl LISTAMUSICA --verbose -i
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['LISTAMUSICA', '--verbose', '-i']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.6.9 (CPython) - Linux-5.0.0-36-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] LISTAMUSICA: Downloading webpage
[youtube] LISTAMUSICA: Downloading video info webpage
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: This video is unavailable.
Sorry about that.
Traceback (most recent call last):
  File "/home/obiwan/Music/youtubedl/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/obiwan/Music/youtubedl/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/obiwan/Music/youtubedl/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 2148, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.
Sorry about that.
```

## Description

WRITE DESCRIPTION HERE
Latest youube dl is failing to download videos from list.
I guess a new release might be needed?
Tested and I am able to play each video on my Firefox browser

**Comment by remitamine** [comment]
incorrect option order(`-i` option should be followed by batch file name).
