### ISSUE TITLE
ufc.tv updated 

### ISSUE THREAD

**Issue by Energyboost** [ytdl-org/youtube-dl#23343]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://ufcfightpass.imggaming.com/video/105290', u'--username', u'PRIVATE', u'--password', u'PRIVATE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 2.7.12 (CPython) - Linux-2.6.32-042stab140.4-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[generic] 105290: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 105290: Downloading webpage
[generic] 105290: Extracting information
ERROR: Unsupported URL: https://ufcfightpass.imggaming.com/video/105290
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2372, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3347, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://ufcfightpass.imggaming.com/video/105290
```

## Description

ufc.tv updated to ufcfightpass.com

**Comment by Energyboost** [comment]
do i have to wait for a release for this fix to be applied ?

**Comment by remitamine** [comment]
yes.

**Comment by Energyboost** [comment]
ok thank you

**Comment by culturedivined** [comment]
> do i have to wait for a release for this fix to be applied ?

I already requested this fix a day or more before you requested this, i'm just replying as i noticed "I've searched the bugtracker for similar issues including closed ones"remitamine has already done the fix
