### ISSUE TITLE
dailymotion.com not working :(

### ISSUE THREAD

**Issue by shirishag75** [ytdl-org/youtube-dl#23352]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

I tried and dailymotion.com downloading just doesn't work - 
```

$ youtube-dl --verbose -F "https://www.dailymotion.com/embed/video/x7gpkpl"
[debug] System config: []
[debug] User config: [u'-f', u'bestvideo[height<=720]+bestaudio/best[height<=720]']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-F', u'https://www.dailymotion.com/embed/video/x7gpkpl']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-2-amd64-x86_64-with-debian-bullseye-sid
[debug] exe versions: ffmpeg 4.2.1-2, ffprobe 4.2.1-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 235, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 50, in _call_api
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 31, in _get_dailymotion_cookies
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2831, in _get_cookies
  File "/usr/lib/python2.7/Cookie.py", line 583, in __init__
    if input: self.load(input)
  File "/usr/lib/python2.7/Cookie.py", line 643, in load
    for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'
```

**Comment by remitamine** [comment]
I already responded to you in https://github.com/ytdl-org/youtube-dl/issues/23350#issuecomment-562982613, again this has been already reported.

**Comment by gulfpearl** [comment]
How on earth is this related to #23350 ... @remitamine I think you linked the wrong issue in your response.

**Comment by remitamine** [comment]
@gulfpearl no I didn't, the same user has opened two issues related to the problem(in the other issue(#23350) he is linking to comment in another issue(https://github.com/ytdl-org/youtube-dl/issues/22360#issuecomment-562966694) that has the same log in this issue), so instead of replying twice, I have redirected him to the issue where I did respond to him.
