### ISSUE TITLE
CBS News does not download

### ISSUE THREAD

**Issue by cdn-content** [ytdl-org/youtube-dl#23359]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE

C:\>youtube-dl -v "https://www.cbsnews.com/news/harvard-geneticist-george-church-goal-to-protect-humans-from-viruses-genetic-diseases-and-aging-60-minutes-2019-12-08/" --ffmpeg-location "C:\Program Files (x86)\youtube-dl\ffmpeg\bin"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.cbsnews.com/news/harvard-geneticist-george-church-goal-to-protect-humans-from-viruses-genetic-diseases-and-aging-60-minutes-2019-12-08/', '--ffmpeg-location', 'C:\\Program Files (x86)\\youtube-dl\\ffmpeg\\bin']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-86175-g64ea4d1, ffprobe N-86175-g64ea4d1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[cbsnews] harvard-geneticist-george-church-goal-to-protect-humans-from-viruses-genetic-diseases-and-aging-60-minutes-2019-12-08: Downloading webpage
[download] Downloading playlist: A Harvard geneticist's goal: to protect humans from viruses, genetic diseases, and aging
[cbsnews] playlist A Harvard geneticist's goal: to protect humans from viruses, genetic diseases, and aging: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 2018, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 807, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 1007, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 869, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\cbsnews.py", line 29, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 312, in loads
TypeError: the JSON object must be str, not 'bytes'
```

## Description

Can't download videos from CBS News/60 Minutes. I've done so in the past, and it seems like youtube-dl recognizes a video but isn't able to extract it. Is this an issue with the site or with the program itself?

**Comment by michaelcrossland1979** [comment]
That happens from time to time on the cbsnew.com site they change stuff there all the time.
Ifg it's not working there it's almost 99% working on the cbs.com site and no you don't have to have the all access stuff to do 60 minutes or face or the nightly news.

**Comment by anonvoy** [comment]
cbs.com won't work outside the US (and possibly Canada and Australia), not even the news shows ("This video isn't available in your region. ") cbsnews.com however works.

**Comment by merval** [comment]
@cdn-content have you tried updating to 2020.07.28? I can download cbsnews videos with it.

**Comment by lkintact** [comment]
Since this issue isn't closed, I didn't open a new one. Having the same problem as op: 

## Checklist
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.cbsnews.com/news/last-pandemic-science-military-60-minutes-2021-04-11/']
[debug] Encodings: locale cp1251, fs mbcs, out cp1251, pref cp1251
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[cbsnews] last-pandemic-science-military-60-minutes-2021-04-11: Downloading webpage
[download] Downloading playlist: Military programs aiming to end pandemics forever
[cbsnews] playlist Military programs aiming to end pandemics forever: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\__init__.py", line 465, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 2060, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 799, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 838, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 924, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 1058, in __process_playlist
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 1068, in __process_iterable_entry
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 879, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 799, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\cbsnews.py", line 29, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\common.py", line 906, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 312, in loads
TypeError: the JSON object must be str, not 'bytes'

```

**Comment by anonvoy** [comment]
> Since this issue isn't closed, I didn't open a new one. Having the same problem as op:

I was able to download that "60 minutes" video from your URL, using youtube-dl version 2021.04.07 with Python 3.6.12 on Linux. Just a hunch: Both you and op are using Python 3.4.4. Have you tried updating Python? 3.4.4 is over 5 years old and does no longer receive any bugfixes security updates. I'm not saying that is the cause of your problem (I simply don't know), but it's something I would try.

**Comment by lkintact** [comment]
Thank you, @anonvoy, you were right. I didn't even notice that the Python version was obsolete, because I use the Windows binary at https://github.com/ytdl-org/youtube-dl/releases/, updating it with `youtube-dl -U` as new versions are released, and somehow I was sure it comes with a Python version that works best. Installing youtube-dl with Python 3.8.7's pip (`py -3 -m pip install --upgrade youtube_dl`) solved the issue.
