### ISSUE TITLE
pluralsight.com videos download failed

### ISSUE THREAD

**Issue by viveksinghrpc** [ytdl-org/youtube-dl#23396]
Error while downloding videos from pluralsight.com. PSB the error details:
**I'm using latest version :** 2019.11.28

**Error**
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose', '--sleep-interval', '120', 'https://www.pluralsight.com/courses/spring-security-fundamentals/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] spring-security-fundamentals: Downloading JSON metadata
[download] Downloading playlist: Spring Security Fundamentals
[pluralsight:course] playlist Spring Security Fundamentals: Collected 104 video ids (downloading 104 of them)
[download] Downloading video 1 of 104
[pluralsight] Downloading login page
[pluralsight] Logging in
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 433, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\pluralsight.py", line 165, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\pluralsight.py", line 215, in _login
youtube_dl.utils.ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by viveksinghrpc** [comment]
Please help to share the link of the bug under which this issue is resolved. I tried searching but can't see the resolution.

Thanks :)
