### ISSUE TITLE
6play extractor is no longer working.

### ISSUE THREAD

**Issue by enikar** [ytdl-org/youtube-dl#23411]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'best', 'https://www.6play.fr/n-c-i-s-p_843/saison-16-episode-4-c_12557347']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.7.5 (CPython) - Linux-5.3.13-e1-x86_64-with-debian-bullseye-sid
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, phantomjs 5, rtmpdump 2.4
[debug] Proxy map: {}
[6play] 12557347: Downloading JSON metadata
[6play] 12557347: Downloading webpage
[6play] 12557347: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12557347: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[6play] 12557347: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12557347: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[6play] 12557347: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12557347: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/sixplay.py", line 113, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
## Description

The 6play extractor was working last week, but not today. It seems 6play have changed again
his format. Thanks for your very good job.

**Comment by enikar** [comment]
So , that's no longer possible to use youtube-dl on linux for downloading videos from 6play. I don't know how to get DRM working on linux, create an account is not sufficient.

**Comment by dknguyengit** [comment]
So does it work in Windows or Mac?

**Comment by enikar** [comment]
On Sat, Dec 21, 2019 at 06:37:32AM -0800, K Nguyen wrote:
> So does it work in Windows or Mac?
I don't know. I use only linux. What I know is that is no way
to play video on 6play from linux due to DRM in a browser.
At least, I don't know of playing theses.
