### ISSUE TITLE
CBS.com is now acting up with just this video only.

### ISSUE THREAD

**Issue by michaelcrossland1979** [ytdl-org/youtube-dl#23426]
## Checklist

- [ x] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2019.11.28**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\micha>youtube-dl --verbose -F https://www.cbs.com/shows/face-the-nation/video/1rndYwvQbUXxp2H_Ot2XEHvs_BCgiLcm/12-15-graham-durbin-lightizer/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-F', u'https://www.cbs.com/shows/face-the-nation/video/1rndYwvQbUXxp2H_Ot2XEHvs_BCgiLcm/12-15-graham-durbin-lightizer/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 2.7.17 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-92043-g0f36ad514c, ffprobe N-92043-g0f36ad514c
[debug] Proxy map: {}
[CBS] 1rndYwvQbUXxp2H_Ot2XEHvs_BCgiLcm: Downloading XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\cbs.py", line 112, in _real_extract
    return self._extract_video_info(content_id)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\cbs.py", line 94, in _extract_video_info
    self._sort_formats(formats)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I don't know what is going on here there CBS nightly New and 60 minutes downloaded just fine for to night but for whatever reason this one will not download anything. It's there Face the Nation Sunday round up show. I have checked and it plays the video if you go in to that page URL both on chrome and firefox. As they have not yet posted it to there cbsnews site yet I am stuck trying to figure out why it's not getting anything when there clearly is video feeds. Any help you could shed on this would be greatly welcome.

**Comment by mfocht** [comment]
I know it's been a while but this link seems to be working now. Not sure if it was something on their end causing the issue or if it was something in youtube-dl that got fixed between then and now.
