### ISSUE TITLE
[mitele] Stopped working today 2019-12-19 new api.

### ISSUE THREAD

**Issue by felisucoibi** [ytdl-org/youtube-dl#23456]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

youtube-dl -v https://www.mitele.es/miniseries/11m/tv-movie/primera-parte-40_1006367575560/player/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.mitele.es/miniseries/11m/tv-movie/primera-parte-40_1006367575560/player/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 2.7.17rc1 (CPython) - Linux-5.3.0-24-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2
[debug] Proxy map: {}
[MiTele] primera-parte-40_1006367575560: Downloading paths JSON
[MiTele] primera-parte-40_1006367575560: Downloading data JSON
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mitele.py", line 77, in _real_extract
IndexError: list index out of range

## Description

There is a new API today 2019-12-19

**Comment by Ackman303** [comment]
Sí, parece ser que han cambiado algo, espero que lo podáis arreglar.
Gracias por vuestro trabajo.

**Comment by gr01d** [comment]
I too can't download any video:
The error is:
`ERROR: This video is unavailable.`

**Comment by ecarvalho123** [comment]
Same issue for me here. URL is https://www.mitele.es/programas-tv/cuarto-milenio/temporada-15/Programa-608-40_1008202075001/player/
