### ISSUE TITLE
 "token" parameter not in video info for unknown reason;

### ISSUE THREAD

**Issue by TheRealRWJ** [ytdl-org/youtube-dl#23457]
Video does not download

 youtube-dl https://www.youtube.com/watch?v=q9eKLPCciWw
[youtube] q9eKLPCciWw: Downloading webpage
[youtube] q9eKLPCciWw: Downloading video info webpage
ERROR: q9eKLPCciWw: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by TheRealRWJ** [comment]
verbose output
youtube-dl -v https://www.youtube.com/watch?v=q9eKLPCciWw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=q9eKLPCciWw']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.6.9 (CPython) - Linux-5.0.0-37-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6-0ubuntu0.18.04.1, ffprobe 3.4.6-0ubuntu0.18.04.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] q9eKLPCciWw: Downloading webpage
[youtube] q9eKLPCciWw: Downloading video info webpage
ERROR: q9eKLPCciWw: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1627, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: q9eKLPCciWw: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by TheRealRWJ** [comment]
Ubuntu Budgie 10.04
Video play fine in Firefox.Please let me know if you like me to test some stuff

**Comment by TheRealRWJ** [comment]
Works again after update AND reboot
