### ISSUE TITLE
7plus DRM issue - is it possible to tell which shows are protected?

### ISSUE THREAD

**Issue by ringofyre** [ytdl-org/youtube-dl#23467]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl.exe -v https://7plus.com.au/19-2?episode-id=NINT03-001
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://7plus.com.au/19-2?episode-id=NINT03-001']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, phantomjs 2.1.1
[debug] Proxy map: {}
[7plus] NINT03-001: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\sevenplus.py", line 61, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\brightcove.py", line 549, in _parse_brightcove_metadata
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I have checked https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+7plus+is%3Aclosed
and despite there being a number of closed threads it seems there's no rhyme or reason to which shows are drm protected or not. Is there a way looking at the logs which can determine so.

Apologies for duplicate.

**Comment by section83** [comment]
+1 from me.

For discussion on this also see: https://forums.whirlpool.net.au/thread/970lpxj3?p=27#bottom

I can't see a solution at present as Plus7 seem to randomly DRM their videos – even turning DRM on/off or off/on with some videos.  I think it will take some rigorous checking of all their catch-up videos both at a point in time and over time to try to find a pattern.

If you happen to notice a pattern please let people know on Whirlpool.

Cheers.
