### ISSUE TITLE
Site support request: metrotvnews.com

### ISSUE THREAD

**Issue by megascrapper** [ytdl-org/youtube-dl#23478]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- https://www.metrotvnews.com/play/bw6C5eeJ-nasib-tanggul-pelindung-jakarta-1
- https://www.metrotvnews.com/play/b3JCVYYV-nasib-tanggul-pelindung-jakarta-2
- https://www.metrotvnews.com/play/K5nC0224-nasib-tanggul-pelindung-jakarta-3

The videos above is part of a single show

## Description

The first video downloads just fine using the generic extractor, but the video is downloaded twice. However the 2nd and 3rd video couldn't be downloaded, giving an error:
```
[debug] System config: []
[debug] User config: [u'-R', u'10', u'-o', u'~/Downloads/%(title)s-%(id)s.%(ext)s', u'--add-metadata']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.metrotvnews.com/play/b3JCVYYV-nasib-tanggul-pelindung-jakarta-2']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 2.7.17 (CPython) - Darwin-19.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] b3JCVYYV-nasib-tanggul-pelindung-jakarta-2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] b3JCVYYV-nasib-tanggul-pelindung-jakarta-2: Downloading webpage
[generic] b3JCVYYV-nasib-tanggul-pelindung-jakarta-2: Extracting information
[download] Downloading playlist: Nasib Tanggul Pelindung Jakarta (2)
[generic] playlist Nasib Tanggul Pelindung Jakarta (2): Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 807, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1007, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 869, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 235, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 50, in _call_api
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 31, in _get_dailymotion_cookies
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2831, in _get_cookies
  File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 583, in __init__
    if input: self.load(input)
  File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 643, in load
    for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'
```
Judging from the webpage it appears that the 1st video uses a different player than the other two.

**Comment by dstftw** [comment]
This is expected behavior. 2nd and 3rd videos don't play in browser.

**Comment by HussainMustafa** [comment]
But I have seen that 2nd and third videos can be played on browser. Atleast in my browser.
