### ISSUE TITLE
Can't download 

### ISSUE THREAD

**Issue by drazde** [ytdl-org/youtube-dl#23473]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
./youtube-dl   --audio-format mp3 'https://www.youtube.com/watch?v=CQAT5qdG8tI&list=RDEMbHaAxpOZhcVmmF6I3y0siA&index=2'  --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--audio-format', 'mp3', 'https://www.youtube.com/watch?v=CQAT5qdG8tI&list=RDEMbHaAxpOZhcVmmF6I3y0siA&index=2', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.6.9 (CPython) - Linux-4.19.86-gentoo-x86_64-Intel-R-_Core-TM-2_Duo_CPU_T5870_@_2.00GHz-with-gentoo-2.6
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist RDEMbHaAxpOZhcVmmF6I3y0siA - add --no-playlist to
just download video CQAT5qdG8tI
[youtube:playlist] RDEMbHaAxpOZhcVmmF6I3y0siA: Downloading page 1 of Youtube mix
[youtube:playlist] RDEMbHaAxpOZhcVmmF6I3y0siA: Downloading page 2 of Youtube mix
[download] Downloading playlist: Mix - Queen
[youtube:playlist] playlist Mix - Queen: Collected 21 video ids (downloading 21 of them)
[download] Downloading video 1 of 21
[youtube] mmF6I3y0siA: Downloading webpage
[youtube] mmF6I3y0siA: Downloading video info webpage
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug
. Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: This video is unavailable.
Sorry about that.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 2148, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.
Sorry about that.
```

## Description
Seems the resource is unavailable, but it isn't. I'm connected on internet and the resource exist.
I use the latest version on github (master) 

WRITE DESCRIPTION HERE

**Comment by remitamine** [comment]
```
-i, --ignore-errors              Continue on download errors, for example to
                                 skip unavailable videos in a playlist
```
