### ISSUE TITLE
LinkedIn learning does not work , only the first 5 videos get download from the course and the rest doesn't , says the video format is not supported

### ISSUE THREAD

**Issue by koshala123** [ytdl-org/youtube-dl#23489]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE

```[12/23/19 11:33:37] [debug] System config: []
[12/23/19 11:33:37] [debug] User config: []
[12/23/19 11:33:37] [debug] Custom config: []
[12/23/19 11:33:37] [debug] Command-line args: ['--newline', '-u', 'PRIVATE', '-p', 'PRIVATE', '-i', '-o', 'C:\\Users\\(username)\\%(title)s.%(ext)s', '-f', 'mp4', '--ignore-config', '--hls-prefer-native', '-2', '(two way autorization)', '--verbose', 'https://www.linkedin.com/learning/linq-with-c-sharp-essential-training/']
[12/23/19 11:33:37] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[12/23/19 11:33:37] [debug] youtube-dl version 2019.11.28
[12/23/19 11:33:37] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[12/23/19 11:33:37] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[12/23/19 11:33:37] [debug] Proxy map: {}
[12/23/19 11:33:37] ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[12/23/19 11:33:37] Traceback (most recent call last):
[12/23/19 11:33:37]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
[12/23/19 11:33:37]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 530, in extract
[12/23/19 11:33:37]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\linkedin.py", line 127, in _real_extract
[12/23/19 11:33:37]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
[12/23/19 11:33:37] youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[12/23/19 11:33:37] 


## Description

<!--
Provide an explanation of your issue in an arbitrary form. Please make sure the description is worded well enough to be understood, see https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

WRITE DESCRIPTION HERE

imagine there are 39 videos in this specific course just 8 videos get downloaded not the others. 5 from the beginning and some from the middle .

**Comment by koshala123** [comment]
Out from 39 videos from the specific course , only 8 or 5 can be downloaded , few from the top and few from middle .

**Comment by koshala123** [comment]
@remitamine  why you say this is duplicate if there is any similar issue please send a  link :/

**Comment by eirnym** [comment]
@koshala123 I have similar experience with them. as far as I see on the list, they doesn't search good enough to distinguish topics from each other. 

Or they just put the topic and search for it. If GitHub return any results, they'll close an issue, even this is about another flag or resource (which could be crucial).
