### ISSUE TITLE
Mediaset support seems broken

### ISSUE THREAD

**Issue by antonioag95** [ytdl-org/youtube-dl#23508]
I found out that with latest youtube-dl version (2019.11.28) Mediaset is not working anymore, I downgraded to version "2019.9.28" and after a couple of these lines it eventually works.

    WARNING: Failed to download ISM manifest: HTTP Error 403: Forbidden

While with latest version it does not work:

    youtube-dl "https://www.mediasetplay.mediaset.it/video/indaginiadaltaquota/laereo-perduto_F309625801000802"
    [Mediaset] F309625801000802: Downloading JSON metadata
    [Mediaset] F309625801000802: Downloading MPEG4 SD SMIL data
    Traceback (most recent call last):
      File "/usr/local/bin/youtube-dl", line 10, in <module>
        sys.exit(main())
      File "/Library/Python/2.7/site-packages/youtube_dl/__init__.py", line 474, in main
        _real_main(argv)
      File "/Library/Python/2.7/site-packages/youtube_dl/__init__.py", line 464, in _real_main
        retcode = ydl.download(all_urls)
      File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 2018, in download
        url, force_generic_extractor=self.params.get('force_generic_extractor', False))
      File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
        ie_result = ie.extract(url)
      File "/Library/Python/2.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
        ie_result = self._real_extract(url)
      File "/Library/Python/2.7/site-packages/youtube_dl/extractor/mediaset.py", line 145, in _real_extract
        }), guid, 'Downloading %s %s SMIL data' % (f.split('+')[0], asset_type))
      File "/Library/Python/2.7/site-packages/youtube_dl/extractor/theplatform.py", line 59, in _extract_theplatform_smil
        transform_rtmp_url=lambda streamer, src: (streamer, 'mp4:' + src))
      File "/Library/Python/2.7/site-packages/youtube_dl/extractor/mediaset.py", line 126, in _parse_smil_formats
        return super()._parse_smil_formats(smil, smil_url, video_id, namespace, f4m_params, transform_rtmp_url)
    TypeError: super() takes at least 1 argument (0 given)

**Comment by felisucoibi** [comment]
maybe you can give a url example

**Comment by antonioag95** [comment]
Edited the first post for link example and a discovery that I've just made, downgrading to a previous version makes it work again.
