### ISSUE TITLE
vhx:embed not working

### ISSUE THREAD

**Issue by heptathlon** [ytdl-org/youtube-dl#23500]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://embed.vhx.tv/videos/435821']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 2.7.17 (CPython) - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.2.1, ffprobe 4.2.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[vhx:embed] 435821: Downloading webpage
ERROR: Unable to extract ott data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 1124, in _real_extract
    'ott data'), video_id, js_to_json)['config_url']
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract ott data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

vhx:embed is not working:

```sh
# youtube-dl 'https://embed.vhx.tv/videos/435821'
[vhx:embed] 435821: Downloading webpage
ERROR: Unable to extract ott data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Refs: https://github.com/ytdl-org/youtube-dl/issues/22817 and https://github.com/ytdl-org/youtube-dl/issues/22976

**Comment by ArtOfficialIntelligence** [comment]
Same error here
