### ISSUE TITLE
Redtube: Error: Unable to extract OpenGraph title

### ISSUE THREAD

**Issue by radiolondra** [ytdl-org/youtube-dl#23518]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2019.12.25**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v "https://www.redtube.com/1075637"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.redtube.com/1075637']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.12.25
[debug] Python version 2.7.15+ (CPython) - Linux-5.0.0-37-generic-i686-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[RedTube] 1075637: Downloading webpage
ERROR: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/redtube.py", line 56, in _real_extract
    default=None) or self._og_search_title(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1117, in _og_search_title
    return self._og_search_property('title', html, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1105, in _og_search_property
    escaped = self._search_regex(og_regexes, html, name, flags=re.DOTALL, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

This happens for some Redtube videos.

**Comment by dstftw** [comment]
>This Video Is Private
