### ISSUE TITLE
Unable to download Wistia video on youtube-dl

### ISSUE THREAD

**Issue by yungsora** [ytdl-org/youtube-dl#23528]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.12.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```C:\Users\sora>cd downloads

C:\Users\sora\Downloads>cd youtube-dl

C:\Users\sora\Downloads\youtube-dl>youtube-dl -v https://academy.tailoredtutors.co.uk/courses/108779/lectures/1955313
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://academy.tailoredtutors.co.uk/courses/108779/lectures/1955313']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.12.25
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 1955313: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1955313: Downloading webpage
[generic] 1955313: Extracting information
[Teachable] 1955313: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\YoutubeDL.py", line 2018, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\YoutubeDL.py", line 807, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\YoutubeDL.py", line 869, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\YoutubeDL.py", line 807, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\YoutubeDL.py", line 851, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\utils.py", line 2133, in sanitize_url
AttributeError: 'NoneType' object has no attribute 'startswith'


## Description

<!--
Provide an explanation of your issue in an arbitrary form. Please make sure the description is worded well enough to be understood, see https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

WRITE DESCRIPTION HERE
Unable to download some Wistia videos from an online course. Some videos are able to be downloaded on the playlist but some reasons some aren't even though they seem to be the same format.

**Comment by dstftw** [comment]
Pass credentials to youtube-dl.
