### ISSUE TITLE
[YouTube] "urlopen error Tunnel connection failed: 403 Forbidden" while using proxy

### ISSUE THREAD

**Issue by Kithaitaa** [ytdl-org/youtube-dl#23521]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.12.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
# youtube-dl -v --prefer-ffmpeg --ffmpeg-location /usr/local/bin/ffmpeg -f 308+251 --merge-output-format webm --proxy "https://lum-customerXXX.lum-superproxy.io:22225" 7HhUpLqHyv4 -o "/XXX.webm"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--prefer-ffmpeg', u'--ffmpeg-location', u'/usr/local/bin/ffmpeg', u'-f', u'308+251', u'--merge-output-format', u'webm', u'--proxy', u'https://lum-customerXXX.lum-superproxy.io:22225', u'7HhUpLqHyv4', u'-o', u'/XXX.webm']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.12.25
[debug] Python version 2.7.9 (CPython) - Linux-3.16.0-4-amd64-x86_64-with-debian-8.11
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {u'http': u'https://lum-customerXXX.lum-superproxy.io:22225', u'https': u'https://lum-customerXXX.lum-superproxy.io:22225'}
[youtube] 7HhUpLqHyv4: Downloading webpage
[youtube] 7HhUpLqHyv4: Downloading video info webpage
[debug] Invoking downloader on u'https://r3---sn-4g5e6nsz.googlevideo.com/videoplayback?expire=1577303661&ei=DWoDXpSlC8ykgQfXwLSYDw&ip=167.71.54.43&id=o-ABBcoV9zfOtLcUt4MdsPDPA51g9qDByUdM6oN6brhKwc&itag=308&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C298%2C299%2C302%2C303%2C308%2C313%2C315%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-4g5e6nsz%2Csn-h0jeen7d&ms=au%2Conr&mv=m&mvi=2&pl=23&initcwndbps=147500&mime=video%2Fwebm&gir=yes&clen=107095717&dur=109.532&lmt=1576631425922185&mt=1577281926&fvip=3&keepalive=yes&fexp=23842630%2C23860862&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRAIgGZQd6UkZWC3OKxK_cvdCPBzkU3PIUm8pWdmnJcUX8gUCIGtE7R8OwBCt3ih5Tp2H5o_LWzjQYly9ndbCD-sitsXL&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgG3nDUho2PD3ybLpc010lKI8zQ_m12JbElvqM3Yg11fsCIDcbjOZ-CvsQaA88EZv853WZmRKlUR_Xts0SPO73I3S8&ratebypass=yes'
ERROR: unable to download video data: <urlopen error Tunnel connection failed: 403 Forbidden>
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1919, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1864, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2728, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error Tunnel connection failed: 403 Forbidden>
```

## Description

Since today i'm receiving an "urlopen error Tunnel connection failed: 403 Forbidden" while using youtube-dl with proxy for any YouTube-files. I'm using Luminati.io as a proxy service and it was working like a charm until today. I've already switched to new proxy-ips, with no success.

Maybe the proxy-routine with YouTube has changed? Or maybe YouTube might have disabled all proxy access through Luminati at all?

**Comment by dstftw** [comment]
Obviously proxy issue, nothing to do with youtube-dl.
