### ISSUE TITLE
Servus TV is broken

### ISSUE THREAD

**Issue by domaniko** [ytdl-org/youtube-dl#23535]
Following is shown when dl a Servus TV stream (it was working until beginning od December):
youtube-dl version is 2019.12.25

>youtube-dl -v https://www.servustv.com/videos/aa-1jkrg7c4d1w14/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.servustv.com/videos/aa-1jkrg7c4d1w14/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.12.25
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-94077-g01d8c72b95, ffprobe N-94077-g01d8c72b95, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] aa-1jkrg7c4d1w14: Requesting header
WARNING: Falling back on generic information extractor.
[generic] aa-1jkrg7c4d1w14: Downloading webpage
[generic] aa-1jkrg7c4d1w14: Extracting information
ERROR: Unsupported URL: https://www.servustv.com/videos/aa-1jkrg7c4d1w14/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\generic.py", line 3347, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.servustv.com/videos/aa-1jkrg7c4d1w14/

**Comment by domaniko** [comment]
same reported in https://github.com/ytdl-org/youtube-dl/issues/23475
