### ISSUE TITLE
Broken support for pornhub.com

### ISSUE THREAD

**Issue by AlengirCenk** [ytdl-org/youtube-dl#23555]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.12.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.12.25
[debug] Python version 3.6.6 (CPython) - Linux-4.15.0-36-generic-x86_64-with-LinuxMint-19-tara
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 5
[debug] Proxy map: {}
try 1 for url https://www.pornhub.com/view_video.php?viewkey=ph5df8599998341
[PornHub] ph5df8599998341: Downloading pc webpage
[PornHub] Executing JS on webpage
[PornHub] ph5df8599998341: Downloading pc webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ney/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/ney/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/ney/.local/lib/python3.6/site-packages/youtube_dl/extractor/pornhub.py", line 195, in _real_extract
    webpage, 'title', group='title')
  File "/home/ney/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Additional info: 
the line which starts with `try one for [url]` is a part of my custom script and includes the actual 
URL that I've tried to download. It is not the only one though, support is broken for all urls.  
Since I'm running the youtube-dl from a python script, clargs are not shown there.
The dictionary I'm passing as arguments is as follows: 
ydl_opts = {
    'nocheckcertificate': True,
    'progress_hooks': [finish_hook],
    'socket_timeout': 20,
    'restrictfilenames': True,
    'verbose': True,
    'ignoreerrors': True,
    'noplaylist': True,
    'playlistend': 1,
}
```
## Description

I'm using the youtube-dl from a python script which automates the download by reading a csv file. It was working fine two days ago including the pornhub.com. I've made a new list of url's, now all sites except the pornhub.com works great, but somehow download from pornhub.com seems to be broken.

**Comment by abesnowman** [comment]
They added a js element to the site over the last few days.  After installing PhantomJS (using the 2.1.1 binary, as the Ubuntu package is broken on headless, non-X installs - see https://github.com/ariya/phantomjs/issues/15217 ), it works for me.

**Comment by AlengirCenk** [comment]
I'm on LinuxMint. PhantomJS seems to be already installed already through PIP and seems to be working fine. Do I have to install the binary anyway? Because it WAS working a few days ago.

**Comment by AlengirCenk** [comment]
Update: I've installed the binary, still does not work for me.

**Comment by AlengirCenk** [comment]
Update: I've just tried it again, without changing anything since the last attempt. We seem to be back on track, weirdly...
