### ISSUE TITLE
Problem in ivi.ru/ivi.tv

### ISSUE THREAD

**Issue by kritik** [ytdl-org/youtube-dl#23552]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.12.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v --username my_username --password my_password https://www.ivi.ru/watch/393617
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://www.ivi.ru/watch/393617']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.12.25
[debug] Python version 2.7.16 (CPython) - Darwin-19.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[ivi] 393617: Downloading timestamp JSON
[ivi] 393617: Downloading video JSON
[ivi] 393617: Downloading video JSON
ERROR: Unable to download video 393617: Контент 393617 недоступен для просмотра на площадке 183
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ivi.py", line 153, in _real_extract
    raise ExtractorError(extractor_msg % video_id, expected=True)
ExtractorError: Unable to download video 393617: \u041a\u043e\u043d\u0442\u0435\u043d\u0442 393617 \u043d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u0435\u043d \u0434\u043b\u044f \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430 \u043d\u0430 \u043f\u043b\u043e\u0449\u0430\u0434\u043a\u0435 183

```

## Description

I try to download video from https://www.ivi.ru/watch/393617 and getting an error Контент 393617 недоступен для просмотра на площадке 183. Checked username and password by copy-paste and they are fine. And everything works in browser. For me it seems it doesn't read u/p attributes

**Comment by remitamine** [comment]
user authentication is not currently supported for ivi.ru, try to use cookies.

**Comment by kritik** [comment]
@remitamine Tried to use cookies as well

youtube-dl -v --add-header 'Cookie: sessivi=91ca261b17238....cookies_from_FF' https://www.ivi.ru/watch/393617
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--add-header', u'Cookie: sessivi=91ca261b17238....cookies_from_FF', u'https://www.ivi.ru/watch/393617']
[debug] Adding header from command line option Cookie: sessivi=91ca261b17238....cookies_from_FF
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.12.25
[debug] Python version 2.7.16 (CPython) - Darwin-19.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[ivi] 393617: Downloading timestamp JSON
[ivi] 393617: Downloading video JSON
[ivi] 393617: Downloading video JSON
ERROR: Unable to download video 393617: Контент 393617 недоступен для просмотра на площадке 183
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ivi.py", line 153, in _real_extract
    raise ExtractorError(extractor_msg % video_id, expected=True)
ExtractorError: Unable to download video 393617: \u041a\u043e\u043d\u0442\u0435\u043d\u0442 393617 \u043d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u0435\u043d \u0434\u043b\u044f \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430 \u043d\u0430 \u043f\u043b\u043e\u0449\u0430\u0434\u043a\u0435 183
```

**Comment by remitamine** [comment]
no, [use `--cookies` option](https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl).

**Comment by kritik** [comment]
Hmm... I totally lost :)
I exported cookies via https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/ and ran command
 ```youtube-dl -v --cookies ./cookies.txt https://www.ivi.ru/watch/393617```

but still getting the same issue :(
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', './cookies.txt', 'https://www.ivi.ru/watch/393617']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.12.25
[debug] Python version 3.7.4 (CPython) - Darwin-19.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[ivi] 393617: Downloading timestamp JSON
[ivi] 393617: Downloading video JSON
[ivi] 393617: Downloading video JSON
ERROR: Unable to download video 393617: Контент 393617 недоступен для просмотра на площадке 183
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/ivi.py", line 153, in _real_extract
    raise ExtractorError(extractor_msg % video_id, expected=True)
youtube_dl.utils.ExtractorError: Unable to download video 393617: Контент 393617 недоступен для просмотра на площадке 183
```

Any idea what I'm missing?

**Comment by remitamine** [comment]
it appears that cookies have no effect, so an account would be needed for developers to add support for authentication.

**Comment by kritik** [comment]
Should I put it here or to someone personal message? BTW, ivi.tv has free 15 days trial period :)19:27, December 29, 2019, remitamine <notifications@github.com>:it appears that cookies have no effect, so an account would be needed for developers to add support for authentication.

**Comment by remitamine** [comment]
no, if a developer is interested in adding support for authentication he can comment here, and then you can send the credentials privately via email.

**Comment by kritik** [comment]
@remitamine I opened python code and debugged ivi.ru website. Seems that code was just outdated. I did updates here https://github.com/kritik/youtube-dl/commit/c65c6fe2ee9963c48fc30f3c579ae84cb9ae22cc but I'm stack with video formats. When I fetch videos I get this list:
```
[
   {
      'mdrm_asset_id':'f4f5e834ec054aee8df9dab72debecd4',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/dash-mdrm-lo/OOByD6pT9bvJ0729FkXfcQ,1577748315/storage31/contents/5/8/aa630dab35b2f4f902153d05ec9b99/manifest.mpd',
      'size_in_bytes':198445573,
      'height':None,
      'content_format':'DASH-MDRM-lo',
      'id':13835629
   },
   {
      'mdrm_asset_id':'32226a2cabfb489c9e498dbe4994ff31',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/dash-mdrm-hi/j0JU5nzHocxLqAqptxMq0w,1577748315/storage15/contents/4/3/6f0a1688bd4219b1f7e84ce658dd00/manifest.mpd',
      'size_in_bytes':392038917,
      'height':None,
      'content_format':'DASH-MDRM-hi',
      'id':13835637
   },
   {
      'mdrm_asset_id':'f19c6cad241b453c966319eea5134586',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/dash-mdrm-hd720/Glqvz9r2e7gA6O8lmPbs9A,1577748315/storage33/contents/7/1/badf4c84427f95dbe56656859833ee/manifest.mpd',
      'size_in_bytes':895748613,
      'height':None,
      'content_format':'DASH-MDRM-HD720',
      'id':13835693
   },
   {
      'mdrm_asset_id':'34adc77059ac42c8b098b3dece60c90b',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/dash-mdrm-shq/MNOZVddG5kiTk4QVG3AzIQ,1577748315/storage4/contents/f/5/f8fbfa75648cb5c08bbe5bcf842021/manifest.mpd',
      'size_in_bytes':612502021,
      'height':None,
      'content_format':'DASH-MDRM-SHQ',
      'id':13835701
   },
   {
      'mdrm_asset_id':'54af074be40b4fdf8a9293755e79d422',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/dash-mdrm-hd1080/NIbSDZpDxlJybEiBG02oPw,1577748315/storage33/contents/b/2/aa6f5de27ca07524ce6ea728695c2c/manifest.mpd',
      'size_in_bytes':1703283205,
      'height':None,
      'content_format':'DASH-MDRM-HD1080',
      'id':13836085
   },
   {
      'mdrm_asset_id':'6e7577f537acf10706483cdb3d380fa4',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/voddash-mdrm-lo,4000/sxokI3LEnyD834H9fKk2oA,1577748315/storage8/contents/6/e/7577f537acf10706483cdb3d380fa4.ks/f7873f67febcb35faff5e44d196a1d10-f1.mpd',
      'size_in_bytes':200272773,
      'height':None,
      'content_format':'VODDASH-MDRM-lo',
      'vod_stream_id':'6/e/7577f537acf10706483cdb3d380fa4:4000',
      'id':0
   },
   {
      'mdrm_asset_id':'6e7577f537acf10706483cdb3d380fa4',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/voddash-mdrm-hi,4000/eA3dNZOqN1SBKCbZYQalnw,1577748315/storage8/contents/6/e/7577f537acf10706483cdb3d380fa4.ks/429cdd6869a21cfe6d6d3335118242a3-f2.mpd',
      'size_in_bytes':397604291,
      'height':None,
      'content_format':'VODDASH-MDRM-hi',
      'vod_stream_id':'6/e/7577f537acf10706483cdb3d380fa4:4000',
      'id':0
   },
   {
      'fps_asset_id':'fc76f67faa4fa3a4754cdeb5e6209575',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/vodhls-fps-shq,4000/zIax_WyMDwFK7PtyCmyF_g,1577748315/storage8/contents/f/c/76f67faa4fa3a4754cdeb5e6209575.ks/ae9f2fc5efd3395c19837a21c7e1e769-f3.m3u8',
      'size_in_bytes':622342963,
      'height':None,
      'content_format':'VODHLS-FPS-SHQ',
      'vod_stream_id':'f/c/76f67faa4fa3a4754cdeb5e6209575:4000',
      'id':0
   },
   {
      'mdrm_asset_id':'6e7577f537acf10706483cdb3d380fa4',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/voddash-mdrm-abrshq,4000/s24xkC7lGeTwnA20WmORmA,1577748315/storage8/contents/6/e/7577f537acf10706483cdb3d380fa4.ks/829d3c985d4b050076893a50d03d936d.mpd',
      'size_in_bytes':0,
      'height':None,
      'content_format':'VODDASH-MDRM-ABRSHQ',
      'vod_stream_id':'6/e/7577f537acf10706483cdb3d380fa4:4000',
      'id':0
   },
   {
      'mdrm_asset_id':'6e7577f537acf10706483cdb3d380fa4',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/voddash-mdrm-abrhd720,4000/kcFRJXg0WWhPs20h0D5ZXg,1577748315/storage8/contents/6/e/7577f537acf10706483cdb3d380fa4.ks/c17a8fb17733b2414e83a90264147c36.mpd',
      'size_in_bytes':0,
      'height':None,
      'content_format':'VODDASH-MDRM-ABRHD720',
      'vod_stream_id':'6/e/7577f537acf10706483cdb3d380fa4:4000',
      'id':0
   },
   {
      'fps_asset_id':'fc76f67faa4fa3a4754cdeb5e6209575',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/vodhls-fps-lo,4000/yMpHIzEfYPji3K3ExKqv9Q,1577748315/storage8/contents/f/c/76f67faa4fa3a4754cdeb5e6209575.ks/e6fcee98a76abb491ded900539a5c6a4-f1.m3u8',
      'size_in_bytes':200272773,
      'height':None,
      'content_format':'VODHLS-FPS-lo',
      'vod_stream_id':'f/c/76f67faa4fa3a4754cdeb5e6209575:4000',
      'id':0
   },
   {
      'fps_asset_id':'fc76f67faa4fa3a4754cdeb5e6209575',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/vodhls-fps-hd1080,4000/F9OfNIfEG9pA5jDCzu5uSw,1577748315/storage8/contents/f/c/76f67faa4fa3a4754cdeb5e6209575.ks/ec8e26ec6b68fa356adc648218a886f3-f5.m3u8',
      'size_in_bytes':1735073464,
      'height':None,
      'content_format':'VODHLS-FPS-HD1080',
      'vod_stream_id':'f/c/76f67faa4fa3a4754cdeb5e6209575:4000',
      'id':0
   },
   {
      'fps_asset_id':'fc76f67faa4fa3a4754cdeb5e6209575',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/vodhls-fps-hi,4000/xC6oXdk4_RtJRpgMjewjNw,1577748315/storage8/contents/f/c/76f67faa4fa3a4754cdeb5e6209575.ks/d81c9f52d43bf70f66560ea7ac9e1006-f2.m3u8',
      'size_in_bytes':397604291,
      'height':None,
      'content_format':'VODHLS-FPS-hi',
      'vod_stream_id':'f/c/76f67faa4fa3a4754cdeb5e6209575:4000',
      'id':0
   },
   {
      'mdrm_asset_id':'6e7577f537acf10706483cdb3d380fa4',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/voddash-mdrm-hd720,4000/pnQUa3BdFFmQ48mCyXavOA,1577748315/storage8/contents/6/e/7577f537acf10706483cdb3d380fa4.ks/c17a8fb17733b2414e83a90264147c36-f4.mpd',
      'size_in_bytes':911388180,
      'height':None,
      'content_format':'VODDASH-MDRM-HD720',
      'vod_stream_id':'6/e/7577f537acf10706483cdb3d380fa4:4000',
      'id':0
   },
   {
      'fps_asset_id':'fc76f67faa4fa3a4754cdeb5e6209575',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/vodhls-fps-abrshq,4000/EqJVsUj-JF97yUPdcaiiMw,1577748315/storage8/contents/f/c/76f67faa4fa3a4754cdeb5e6209575.ks/ae9f2fc5efd3395c19837a21c7e1e769.m3u8',
      'size_in_bytes':0,
      'height':None,
      'content_format':'VODHLS-FPS-ABRSHQ',
      'vod_stream_id':'f/c/76f67faa4fa3a4754cdeb5e6209575:4000',
      'id':0
   },
   {
      'fps_asset_id':'fc76f67faa4fa3a4754cdeb5e6209575',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/vodhls-fps-abrhd720,4000/XSebYp_s-LdQRYBzJuPTkQ,1577748315/storage8/contents/f/c/76f67faa4fa3a4754cdeb5e6209575.ks/532782cde32d15606dc9ad8415b12db7.m3u8',
      'size_in_bytes':0,
      'height':None,
      'content_format':'VODHLS-FPS-ABRHD720',
      'vod_stream_id':'f/c/76f67faa4fa3a4754cdeb5e6209575:4000',
      'id':0
   },
   {
      'mdrm_asset_id':'6e7577f537acf10706483cdb3d380fa4',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/voddash-mdrm-hd1080,4000/Ip6QQl8yMTNgVBzSW2ACPA,1577748315/storage8/contents/6/e/7577f537acf10706483cdb3d380fa4.ks/1b4cdaacc3ab1d888733b69abcbba089-f5.mpd',
      'size_in_bytes':1735073464,
      'height':None,
      'content_format':'VODDASH-MDRM-HD1080',
      'vod_stream_id':'6/e/7577f537acf10706483cdb3d380fa4:4000',
      'id':0
   },
   {
      'fps_asset_id':'fc76f67faa4fa3a4754cdeb5e6209575',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/vodhls-fps-abrhd1080,4000/jXjtgf0qfcxTEii9OYaDcw,1577748315/storage8/contents/f/c/76f67faa4fa3a4754cdeb5e6209575.ks/ec8e26ec6b68fa356adc648218a886f3.m3u8',
      'size_in_bytes':0,
      'height':None,
      'content_format':'VODHLS-FPS-ABRHD1080',
      'vod_stream_id':'f/c/76f67faa4fa3a4754cdeb5e6209575:4000',
      'id':0
   },
   {
      'mdrm_asset_id':'6e7577f537acf10706483cdb3d380fa4',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/voddash-mdrm-abrhd1080,4000/yM0jlwtDBtHXY_Vx2mmoWA,1577748315/storage8/contents/6/e/7577f537acf10706483cdb3d380fa4.ks/1b4cdaacc3ab1d888733b69abcbba089.mpd',
      'size_in_bytes':0,
      'height':None,
      'content_format':'VODDASH-MDRM-ABRHD1080',
      'vod_stream_id':'6/e/7577f537acf10706483cdb3d380fa4:4000',
      'id':0
   },
   {
      'fps_asset_id':'fc76f67faa4fa3a4754cdeb5e6209575',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/vodhls-fps-hd720,4000/kI8lcP6p5VQlHn27qiRyjA,1577748315/storage8/contents/f/c/76f67faa4fa3a4754cdeb5e6209575.ks/532782cde32d15606dc9ad8415b12db7-f4.m3u8',
      'size_in_bytes':911388180,
      'height':None,
      'content_format':'VODHLS-FPS-HD720',
      'vod_stream_id':'f/c/76f67faa4fa3a4754cdeb5e6209575:4000',
      'id':0
   },
   {
      'mdrm_asset_id':'6e7577f537acf10706483cdb3d380fa4',
      'width':None,
      'url':'https://plus.dfs.ivi.ru/jW1JJB9fujJkVu58XgofnwoWbu5TodpQaav5VW0gYYiQrTLQqDu681257/voddash-mdrm-shq,4000/M173mJ9h5WfSRL7ED_Hxeg,1577748315/storage8/contents/6/e/7577f537acf10706483cdb3d380fa4.ks/829d3c985d4b050076893a50d03d936d-f3.mpd',
      'size_in_bytes':622342963,
      'height':None,
      'content_format':'VODDASH-MDRM-SHQ',
      'vod_stream_id':'6/e/7577f537acf10706483cdb3d380fa4:4000',
      'id':0
   }
]
```
When youtube-dl downloads best quality it get's xml file
```
curl https://plus.dfs.ivi.ru/jW1GWhymInDIBJuV2RSyfmx1qf2XlL9PTPHxrhxGe1zhNo7y15o880135/dash-mdrm-hd1080/VBY-08ICrGFeOH007E9qQw,1577747840/storage33/contents/b/2/aa6f5de27ca07524ce6ea728695c2c/manifest.mpd
<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns="urn:mpeg:DASH:schema:MPD:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd" xmlns:cenc="urn:mpeg:cenc:2013" minBufferTime="PT2S" type="static" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" mediaPresentationDuration="PT2531.09375S">
  <Period>
    <AdaptationSet id="0" contentType="video" width="1920" height="1080" frameRate="12800/512" subSegmentAlignment="true" par="16:9">
      <Representation id="0" bandwidth="5122560" codecs="avc1.640028" mimeType="video/mp4" sar="1:1" width="1920" height="1080" frameRate="12800/512">
        <ContentProtection value="cenc" schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="f6433bb1-897c-54a2-8916-d874f741c2d1"/>
        <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
          <cenc:pssh>AAAAOHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABgiEFSvB0vkC0/fipKTdV551CJI49yVmwY=</cenc:pssh>
        </ContentProtection>
        <BaseURL>video_0.mp4</BaseURL>
        <SegmentBase indexRange="959-4794" timescale="12800">
          <Initialization range="0-958"/>
        </SegmentBase>
      </Representation>
    </AdaptationSet>
    <AdaptationSet id="1" contentType="audio" lang="en" subSegmentAlignment="true">
      <Representation id="1" bandwidth="260663" codecs="mp4a.40.2" mimeType="audio/mp4" audioSamplingRate="48000">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
        <ContentProtection value="cenc" schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="ffd513dc-5b8c-5a7e-95cc-c9ac94356f70"/>
        <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
          <cenc:pssh>AAAAOHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABgiEFSvB0vkC0/fipKTdV551CJI49yVmwY=</cenc:pssh>
        </ContentProtection>
        <BaseURL>audio_0.mp4</BaseURL>
        <SegmentBase indexRange="819-5182" timescale="48000">
          <Initialization range="0-818"/>
        </SegmentBase>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```
Any idea what I can do next?

**Comment by remitamine** [comment]
all formats are DRM protected.

**Comment by kritik** [comment]
Anything I can do here? Like emulating browser?

**Comment by remitamine** [comment]
youtube-dl does not support this type of videos.

**Comment by kritik** [comment]
I would say this ticket can be closed once pull request merged

**Comment by 89z** [comment]
Issue should be closed, account needed
