### ISSUE TITLE
Extractor Error on Mediaset Play

### ISSUE THREAD

**Issue by ercofra** [ytdl-org/youtube-dl#23581]
- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2019.12.25**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.mediasetplay.mediaset.it/video/igrandiimperidellastoria/i-maya_F309199101000405']
[debug] Encodings: locale cp850, fs mbcs, out cp850, pref cp850
[debug] youtube-dl version 2019.12.25
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg git-2019-12-07-ff2b75d
[debug] Proxy map: {}
[Mediaset] F309199101000405: Downloading JSON metadata
[Mediaset] F309199101000405: Downloading MPEG4 SD SMIL data
[Mediaset] F309199101000405: Downloading MPEG4 HD SMIL data
ERROR: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\mediaset.py", line 155, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\mediaset.py", line 145, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\theplatform.py", line 52, in _extract_theplatform_smil
youtube_dl.utils.ExtractorError: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences

## Description

The above video of mediasetplay and others similar are not downloaded due the error in the log, many others video from the same site are downloaded without problems, the issue affects only a few.
No account credentials are required to access the example video.

**Comment by dstftw** [comment]
Wrong.
![image](https://user-images.githubusercontent.com/1908898/71624004-e1f22e00-2c12-11ea-897b-af0f2cf28446.png)

**Comment by ercofra** [comment]
I've sent account credentials to dstftw.
I can send them to anyone else needs them.
