### ISSUE TITLE
Unable to merge YouTube video and audio on both Linux and Mac

### ISSUE THREAD

**Issue by mattcaruso** [ytdl-org/youtube-dl#23616]
I've chosen the Question issue type because I'm sure this isn't a software bug but instead something I'm missing. I've spent most of the day trying to get this to work so I'm finally asking for help! 

I'm running 2020.01.01.

I'm downloading all content from https://www.youtube.com/channel/UCw0WzNn6m2Na6ZW7rKqWI3g. 

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.01.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

### Verbose Log
```
Matts-MBP:~ matt.caruso$ youtube-dl -ciw https://www.youtube.com/channel/UCw0WzNn6m2Na6ZW7rKqWI3g --write-description -f 'bestvideo+bestaudio/best' --merge-output-format mp4 -o '/Users/matt.caruso/Downloads/discpro/%(title)s.%(ext)s'
[youtube:channel] UCw0WzNn6m2Na6ZW7rKqWI3g: Downloading channel page
[youtube:playlist] UUw0WzNn6m2Na6ZW7rKqWI3g: Downloading webpage
[download] Downloading playlist: Uploads from Disc Golf Pro Tour
[youtube:playlist] UUw0WzNn6m2Na6ZW7rKqWI3g: Downloading page #1
[youtube:playlist] UUw0WzNn6m2Na6ZW7rKqWI3g: Downloading page #2
[youtube:playlist] UUw0WzNn6m2Na6ZW7rKqWI3g: Downloading page #3
[youtube:playlist] UUw0WzNn6m2Na6ZW7rKqWI3g: Downloading page #4
[youtube:playlist] UUw0WzNn6m2Na6ZW7rKqWI3g: Downloading page #5
[youtube:playlist] playlist Uploads from Disc Golf Pro Tour: Downloading 557 videos
[download] Downloading video 1 of 557
[youtube] oCk8dATc9oU: Downloading webpage
[youtube] oCk8dATc9oU: Downloading video info webpage
[info] Writing video description to: /Users/matt.caruso/Downloads/discpro/2019 Disc Golf Pro Tour Championship - MPO Finals _ Gibson, Dickerson, Jones, Heimburg.description
[download] Destination: /Users/matt.caruso/Downloads/discpro/2019 Disc Golf Pro Tour Championship - MPO Finals _ Gibson, Dickerson, Jones, Heimburg.f137.mp4
[download] 100% of 4.36GiB in 10:28
[download] Destination: /Users/matt.caruso/Downloads/discpro/2019 Disc Golf Pro Tour Championship - MPO Finals _ Gibson, Dickerson, Jones, Heimburg.f251.webm
[download] 100% of 156.65MiB in 00:22
[ffmpeg] Merging formats into "/Users/matt.caruso/Downloads/discpro/2019 Disc Golf Pro Tour Championship - MPO Finals _ Gibson, Dickerson, Jones, Heimburg.mp4"
ERROR:   Stream #1:0 -> #0:1 (copy)
[download] Downloading video 2 of 557
[youtube] uMESx8Pgh1U: Downloading webpage
[youtube] uMESx8Pgh1U: Downloading video info webpage
[youtube] uMESx8Pgh1U: Downloading MPD manifest
[info] Writing video description to: /Users/matt.caruso/Downloads/discpro/2019 Disc Golf Pro Tour Championship - FPO Finals _ Pierce, Allen, Hokom, Cox.description
[dashsegments] Total fragments: 3064
[download] Destination: /Users/matt.caruso/Downloads/discpro/2019 Disc Golf Pro Tour Championship - FPO Finals _ Pierce, Allen, Hokom, Cox.f137.mp4
[download]  85.8% of ~7.25GiB at  6.08MiB/s ETA 02:34^C
ERROR: Interrupted by user
Matts-MBP:~ matt.caruso$ youtube-dl --version
2020.01.01
Matts-MBP:~ matt.caruso$ youtube-dl -ciw https://www.youtube.com/channel/UCw0WzNn6m2Na6ZW7rKqWI3g --write-description -f 'bestvideo+bestaudio/best' --merge-output-format mp4 -o '/Users/matt.caruso/Downloads/discpro/%(title)s.%(ext)s' -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-ciw', 'https://www.youtube.com/channel/UCw0WzNn6m2Na6ZW7rKqWI3g', '--write-description', '-f', 'bestvideo+bestaudio/best', '--merge-output-format', 'mp4', '-o', '/Users/matt.caruso/Downloads/discpro/%(title)s.%(ext)s', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.01
[debug] Python version 3.7.6 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:channel] UCw0WzNn6m2Na6ZW7rKqWI3g: Downloading channel page
[youtube:playlist] UUw0WzNn6m2Na6ZW7rKqWI3g: Downloading webpage
[download] Downloading playlist: Uploads from Disc Golf Pro Tour
[youtube:playlist] UUw0WzNn6m2Na6ZW7rKqWI3g: Downloading page #1
[youtube:playlist] UUw0WzNn6m2Na6ZW7rKqWI3g: Downloading page #2
[youtube:playlist] UUw0WzNn6m2Na6ZW7rKqWI3g: Downloading page #3
[youtube:playlist] UUw0WzNn6m2Na6ZW7rKqWI3g: Downloading page #4
[youtube:playlist] UUw0WzNn6m2Na6ZW7rKqWI3g: Downloading page #5
[youtube:playlist] playlist Uploads from Disc Golf Pro Tour: Downloading 557 videos
[download] Downloading video 1 of 557
[youtube] oCk8dATc9oU: Downloading webpage
[youtube] oCk8dATc9oU: Downloading video info webpage
[info] Video description is already present
[debug] Invoking downloader on 'https://r5---sn-8xgp1vo-ab5e.googlevideo.com/videoplayback?expire=1578108245&ei=9bAPXt3kLYjV8wSV_YiICA&ip=108.50.147.110&id=o-APwXTFd3MjYtRAsMYn7PNnIiGjh7RV6nfZqnC-I5GIqH&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-8xgp1vo-ab5e%2Csn-ab5l6n6e&ms=au%2Crdu&mv=m&mvi=4&pl=17&initcwndbps=1802500&mime=video%2Fmp4&gir=yes&clen=4684266139&dur=11870.632&lmt=1571835646669229&mt=1578086561&fvip=5&keepalive=yes&fexp=23842630&c=WEB&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIgOxfJefqbkp4xZWVCUNTE4Sfui631r5rzREEU-O55cD4CIQCoyz0z2s_Ycmb_xZE6sp5FLvaz7xADl4GSgl1zOzkKSw%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgKSxfx_ahHkP_Cw_aP3ZgvJAcncz8xb-PEd4HU8Y2GXICIGNONDsQLAZjnG_luVkJpveNhSTXsNqKpHm6XavoT9ia&ratebypass=yes'
[download] /Users/matt.caruso/Downloads/discpro/2019 Disc Golf Pro Tour Championship - MPO Finals _ Gibson, Dickerson, Jones, Heimburg.f137.mp4 has already been downloaded
[download] 100% of 4.36GiB
[debug] Invoking downloader on 'https://r5---sn-8xgp1vo-ab5e.googlevideo.com/videoplayback?expire=1578108245&ei=9bAPXt3kLYjV8wSV_YiICA&ip=108.50.147.110&id=o-APwXTFd3MjYtRAsMYn7PNnIiGjh7RV6nfZqnC-I5GIqH&itag=251&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-8xgp1vo-ab5e%2Csn-ab5l6n6e&ms=au%2Crdu&mv=m&mvi=4&pl=17&initcwndbps=1802500&mime=audio%2Fwebm&gir=yes&clen=164262306&dur=11870.661&lmt=1571833194406293&mt=1578086561&fvip=5&keepalive=yes&fexp=23842630&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIgJ8AGepyR_ek83kHED-LWSgaupaAf5zAZC89QgNIKepMCIQCcDMs1BlziBW5f0S4N2i5AOVOjBtntpkQ6YeohFHcmPg%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgKSxfx_ahHkP_Cw_aP3ZgvJAcncz8xb-PEd4HU8Y2GXICIGNONDsQLAZjnG_luVkJpveNhSTXsNqKpHm6XavoT9ia&ratebypass=yes'
[download] /Users/matt.caruso/Downloads/discpro/2019 Disc Golf Pro Tour Championship - MPO Finals _ Gibson, Dickerson, Jones, Heimburg.f251.webm has already been downloaded
[download] 100% of 156.65MiB
[ffmpeg] Merging formats into "/Users/matt.caruso/Downloads/discpro/2019 Disc Golf Pro Tour Championship - MPO Finals _ Gibson, Dickerson, Jones, Heimburg.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/Users/matt.caruso/Downloads/discpro/2019 Disc Golf Pro Tour Championship - MPO Finals _ Gibson, Dickerson, Jones, Heimburg.f137.mp4' -i 'file:/Users/matt.caruso/Downloads/discpro/2019 Disc Golf Pro Tour Championship - MPO Finals _ Gibson, Dickerson, Jones, Heimburg.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:/Users/matt.caruso/Downloads/discpro/2019 Disc Golf Pro Tour Championship - MPO Finals _ Gibson, Dickerson, Jones, Heimburg.temp.mp4'
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2064, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)
```

## Description

If I remove the -f flag, I get 720p videos downloaded without any errors. However, when trying to use the bestvideo+bestaudio format to pull 1080 and merge, I get the stream error from ffmpeg.

**Comment by dstftw** [comment]
mp4 and webm cant be merged into mp4. Do not touch `--merge-output-format` if you have no idea of what you are doing.

**Comment by mattcaruso** [comment]
So is it not possible to download 1080p videos and merge with audio for
these particular videos?

**Comment by dstftw** [comment]
Are you trolling or what?

**Comment by mattcaruso** [comment]
No, I'm not trolling.

I just spent some more time going through the documentation and realized I
can use -f 'bestvideo+bestaudio[ext=m4a]' to achieve what I need to do.

I appreciate your help. Sometimes it's helpful to say this stuff "aloud".
