### ISSUE TITLE
Seznam zpravy

### ISSUE THREAD

**Issue by jtrmal** [ytdl-org/youtube-dl#23661]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.01.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.televizeseznam.cz/video/poledni-zpravy-219/utok-v-ostrave-nemocnice-zada-o-krev-provoz-nemocnice-ochromil-pocitacovy-virus-az-80-tisic-lidi-na-demonstraci-proti-babisovi-64009511
- Single video: https://www.televizeseznam.cz/video/vecerni-zpravy-porad/roztrzka-mezi-ruskem-a-ceskem-trumpuv-impeachment-a-babisovo-capi-hnizdo-64011641
- Playlist: https://www.televizeseznam.cz/porad/vecerni-zpravy-porad

## Description

WRITE DESCRIPTION HERE
The tv should not need any credentials.
I was able to download links looking like this (using network monitor from chrome developer utils)
```
'https://v39-ng.sdn.cz/~SEC1~expire-1578495160~scope-video~Jbih5dt6Vrb/v_39/vmd_ng_5da58aff96f5a660fd514551/1571130111?fl=mdk,203ff101|hlsp4,h264_aac_480p_ts,segmented_video,4,VOD,,,1'
```
but I didn't find any way how to track how the links are created. Plus I assume they expire. But they return normal m3u8 playlist:
```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:6
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:6,
../vd_ng_5da58aff96f5a660fd514551_1571130111/h264_aac_480p_ts/0/203ff101.ts
#EXTINF:6,
../vd_ng_5da58aff96f5a660fd514551_1571130111/h264_aac_480p_ts/1/203ff101.ts
#EXTINF:6,
../vd_ng_5da58aff96f5a660fd514551_1571130111/h264_aac_480p_ts/2/203ff101.ts
......... and so on
```

**Comment by jtrmal** [comment]
```
$ youtube-dl -v  "https://www.televizeseznam.cz/video/poledni-zpravy-219/utok-v-ostrave-nemocnice-zada-o-krev-provoz-nemocnice-ochromil-pocitacovy-virus-az-80-tisic-lidi-na-demonstraci-proti-babisovi-64009511"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.televizeseznam.cz/video/poledni-zpravy-219/utok-v-ostrave-nemocnice-zada-o-krev-provoz-nemocnice-ochromil-pocitacovy-virus-az-80-tisic-lidi-na-demonstraci-proti-babisovi-64009511']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.01
[debug] Python version 3.7.3 (CPython) - Linux-5.3.0-0.bpo.2-amd64-x86_64-with-debian-10.2
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] utok-v-ostrave-nemocnice-zada-o-krev-provoz-nemocnice-ochromil-pocitacovy-virus-az-80-tisic-lidi-na-demonstraci-proti-babisovi-64009511: Requesting header
WARNING: Falling back on generic information extractor.
[generic] utok-v-ostrave-nemocnice-zada-o-krev-provoz-nemocnice-ochromil-pocitacovy-virus-az-80-tisic-lidi-na-demonstraci-proti-babisovi-64009511: Downloading webpage
[generic] utok-v-ostrave-nemocnice-zada-o-krev-provoz-nemocnice-ochromil-pocitacovy-virus-az-80-tisic-lidi-na-demonstraci-proti-babisovi-64009511: Extracting information
ERROR: Unsupported URL: https://www.televizeseznam.cz/video/poledni-zpravy-219/utok-v-ostrave-nemocnice-zada-o-krev-provoz-nemocnice-ochromil-pocitacovy-virus-az-80-tisic-lidi-na-demonstraci-proti-babisovi-64009511
Traceback (most recent call last):
  File "/home/jtrmal/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/jtrmal/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/jtrmal/.local/lib/python3.7/site-packages/youtube_dl/extractor/generic.py", line 3347, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.televizeseznam.cz/video/poledni-zpravy-219/utok-v-ostrave-nemocnice-zada-o-krev-provoz-nemocnice-ochromil-pocitacovy-virus-az-80-tisic-lidi-na-demonstraci-proti-babisovi-64009511
```

**Comment by schunka** [comment]
#21774
