### ISSUE TITLE
Twitter downloads result in ERROR: unable to open for writing: [Errno 36] File name too long:

### ISSUE THREAD

**Issue by Wikinaut** [ytdl-org/youtube-dl#23681]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.01.01**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v https://twitter.com/DvSchneid/status/1213829315613405185
[debug] System config: []
[debug] User config: [u'-f', u'best', u'--all-subs', u'-o', u'~/Videos/youtube-dl/%(title)s-%(id)s.%(ext)s', u'--user-agent', u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:21.0) Gecko/20100101 Firefox/38.0']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://twitter.com/DvSchneid/status/1213829315613405185']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.01
[debug] Python version 2.7.17 (CPython) - Linux-5.0.0-37-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, rtmpdump 2.4
[debug] Proxy map: {}
[twitter] 1213829315613405185: Downloading guest token
[twitter] 1213829315613405185: Downloading JSON metadata
[twitter] 1213829315613405185: Downloading m3u8 information
[debug] Invoking downloader on u'https://video.twimg.com/ext_tw_video/1213829227222454274/pu/vid/1280x720/WN0NO-cU_EIXO5D-.mp4?tag=10'
 '/home/benutzer/Videos/youtube-dl/Dirk Schneidemesser - We were hoping for a protected bike lane on the #Oberbaumbruecke in Berlin for Christmas. But Santa forgot to put them under the tree...so we used the trees as protection.  @MonikaHerrmann1 @f_schmidt_BB @RegBerlin @RegineGuenther  @LieblingXhain-1213829315613405185.mp4.part'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 250, in download
    ctx.tmpfilename, ctx.open_mode)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2046, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
IOError: [Errno 36] File name too long: '/home/benutzer/Videos/youtube-dl/Dirk Schneidemesser - We were hoping for a protected bike lane on the #Oberbaumbruecke in Berlin for Christmas. But Santa forgot to put them under the tree...so we used the trees as protection.  @MonikaHerrmann1 @f_schmidt_BB @RegBerlin @RegineGuenther  @LieblingXhain-1213829315613405185.mp4.part'
```

## Description

Example: https://twitter.com/DvSchneid/status/1213829315613405185 cannot be downloaded, because the title results in a filename which is too long.

I suggest a parameter to restrict (crop) the ```%(title)d``` element.

**Comment by Wikinaut** [comment]
Duplicate to what issue?
