### ISSUE TITLE
NYTimes fails to download video

### ISSUE THREAD

**Issue by OverlordQ** [ytdl-org/youtube-dl#23688]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.01.01**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.nytimes.com/2020/01/09/video/iran-plane-missile.html']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.01.01
[debug] Python version 3.7.4 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg N-93083-g8522d219ce, ffprobe N-93083-g8522d219ce
[debug] Proxy map: {}
[NYTimesArticle] iran-plane-missile: Downloading webpage
ERROR: Unable to extract podcast data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\575065\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\575065\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\users\575065\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\nytimes.py", line 222, in _real_extract
    webpage, 'podcast data')
  File "c:\users\575065\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract podcast data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Fails to download video from NYTimes

**Comment by Kleckkinator** [comment]
Here is a similar issue downloading a Podcast from NYTimes:

youtube-dl version 2021.02.10

The URL is verified to be alive well, and playing: [https://www.nytimes.com/2020/07/30/podcasts/nice-white-parents-serial.html](https://www.nytimes.com/2020/07/30/podcasts/nice-white-parents-serial.html)

Log:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.nytimes.com/2020/07/30/podcasts/nice-white-parents-serial.html', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.02.10
[debug] Python version 3.8.7 (CPython) - Windows-10-10.0.21301-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-10-01-full_build-www.gyan.dev, ffprobe 4.3.1-2020-10-01-full_build-www.gyan.dev
[debug] Proxy map: {}
[NYTimesArticle] nice-white-parents-serial: Downloading webpage
ERROR: Unable to extract podcast data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\program files\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "c:\program files\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "c:\program files\python\python38\lib\site-packages\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\program files\python\python38\lib\site-packages\youtube_dl\extractor\nytimes.py", line 219, in _real_extract
    podcast_data = self._search_regex(
  File "c:\program files\python\python38\lib\site-packages\youtube_dl\extractor\common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract podcast data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
