### ISSUE TITLE
Support RTP 

### ISSUE THREAD

**Issue by peterpt** [ytdl-org/youtube-dl#23707]
I am using the 2020-01-01 version of youtube-dl in windows environment .
Last year youtube-dl worked perfectly on this website , however probably some changes were probably made in website streaming service .

Example of streaming link :
https://www.rtp.pt/play/p6383/italia-selvagem-os-maiores-predadores

Error from youtube-dl :

youtube-dl --verbose -F https://www.rtp.pt/play/p6383/italia-selvagem-
os-maiores-predadores
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-F', 'https://www.rtp.pt/play/p6383/it
alia-selvagem-os-maiores-predadores']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.01.01
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-92458-gfc94e9704e, ffprobe N-92458-gfc94e9704e
[debug] Proxy map: {}
[RTP] italia-selvagem-os-maiores-predadores: Downloading webpage
ERROR: italia-selvagem-os-maiores-predadores: Failed to parse JSON  (caused by V
alueError("Expecting ',' delimiter: line 11 column 11 (char 715)",)); please rep
ort this issue on https://yt-dl.org/bug . Make sure you are using the latest ver
sion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verb
ose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7
ln\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 359, in raw_decode
ValueError: Expecting ',' delimiter: line 11 column 11 (char 715)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7
ln\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 359, in raw_decode
ValueError: Expecting ',' delimiter: line 11 column 11 (char 715)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7
ln\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7
ln\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7
ln\build\youtube_dl\extractor\rtp.py", line 37, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7
ln\build\youtube_dl\extractor\common.py", line 903, in _parse_json
youtube_dl.utils.ExtractorError: italia-selvagem-os-maiores-predadores: Failed t
o parse JSON  (caused by ValueError("Expecting ',' delimiter: line 11 column 11
(char 715)",)); please report this issue on https://yt-dl.org/bug . Make sure yo
u are using the latest version; type  youtube-dl -U  to update. Be sure to call
youtube-dl with the --verbose flag and include its complete output.

**Comment by israel-lugo** [comment]
I've found the problem.

The RTP InfoExtractor is parsing the HTML [here](https://github.com/ytdl-org/youtube-dl/blob/be96f9924f4b93ab4632b602a7e7b97518a1ddab/youtube_dl/extractor/rtp.py#L35-L37) to get its config.

This captures the following snippet:

```javascript
{
          id: "player_prog",
          fileKey: "/nas2.share/pt/h264/512x384/p6265/p6265_1_201912152233180805.mp4",
          file : "https://ondemand-streaming.rtp.pt/nas2.share/pt/h264/512x384/p6265/index.m3u8?tlm=hls&streams=p6265_1_201912152233180805.mp4.m3u8:1024",
                                  seekBarThumbnailsLoc: '//cdn-images.rtp.pt/multimedia/screenshots/p6265/preview/p6265_1_201912152233180805_preview.vtt',
                      adsType: 'dfp',
          subadUnit: 'Play',
          streamType:"ondemand",
          googleCast: true,
          //extraSettings: { googleCastReceiverAppId:'1A6F2224', skin:'s3',  skinAccentColor: '0073FF'},
          extraSettings: { googleCastReceiverAppId:'1A6F2224'},
          mediaType: "video",
          poster: "https://cdn-images.rtp.pt/EPG/imagens/37684_55429_70561.jpg?v=3&w=1170"
        }
```

Note the commented `//extraSettings...` line. This _should_ be dealt with by [js_to_json](https://github.com/ytdl-org/youtube-dl/blob/be96f9924f4b93ab4632b602a7e7b97518a1ddab/youtube_dl/utils.py#L3977). But the transformed output (caught after [transformation](https://github.com/ytdl-org/youtube-dl/blob/be96f9924f4b93ab4632b602a7e7b97518a1ddab/youtube_dl/extractor/common.py#L897)) is:

```json
{
          "id": "player_prog",
          "fileKey": "/nas2.share/pt/h264/512x384/p6265/p6265_1_201912152233180805.mp4",
          "file" : "https://ondemand-streaming.rtp.pt/nas2.share/pt/h264/512x384/p6265/index.m3u8?tlm=hls&streams=p6265_1_201912152233180805.mp4.m3u8:1024",
                                  "seekBarThumbnailsLoc": "//cdn-images.rtp.pt/multimedia/screenshots/p6265/preview/p6265_1_201912152233180805_preview.vtt",
                      "adsType": "dfp",
          "subadUnit": "Play",
          "streamType":"ondemand",
          "googleCast": true
          
          "extraSettings": { "googleCastReceiverAppId":"1A6F2224"},
          "mediaType": "video",
          "poster": "https://cdn-images.rtp.pt/EPG/imagens/37684_55429_70561.jpg?v=3&w=1170"
        }
```

Note the missing trailing `,` after `"googleCast": true"`.

This is a bug in `js_to_json`. It's eating up the trailing comma on the previous line, when it skips a line which is entirely commented.

**Comment by israel-lugo** [comment]
Incidentally, this issue should be tagged with broken-IE (broken information extractor), probably more than site-support-request (which is IIUC requesting support for a new site). RTP is already supported, it's just broken.

**Comment by norca-avocado** [comment]
Seeing this same issue with:

Streaming link:
https://www.americastestkitchen.com/episode/647-eggs-for-the-holidays

Error from youtube-dl:
C:\>youtube-dl --verbose https://www.americastestkitchen.com/episode/647-eggs-fo
r-the-holidays
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.americastestkitchen.com/ep
isode/647-eggs-for-the-holidays']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.01.15
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-93994-gd81913e680, ffprobe N-93994-gd81913e680, r
tmpdump 2.4
[debug] Proxy map: {}
[AmericasTestKitchen] 647: Downloading webpage
ERROR: 647: Failed to parse JSON  (caused by ValueError('Expecting value: line 1
 column 43 (char 42)',)); please report this issue on https://yt-dl.org/bug . Ma
ke sure you are using the latest version; type  youtube-dl -U  to update. Be sur
e to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zy
g3\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 43 (char 42)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zy
g3\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 43 (char 42)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zy
g3\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zy
g3\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zy
g3\build\youtube_dl\extractor\americastestkitchen.py", line 50, in _real_extract

  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zy
g3\build\youtube_dl\extractor\common.py", line 903, in _parse_json
youtube_dl.utils.ExtractorError: 647: Failed to parse JSON  (caused by ValueErro
r('Expecting value: line 1 column 43 (char 42)',)); please report this issue on
https://yt-dl.org/bug . Make sure you are using the latest version; type  youtub
e-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and inclu
de its complete output.

**Comment by lcnittl** [comment]
Just want to link a(nother) PR that aims to fix this: https://github.com/ytdl-org/youtube-dl/pull/29824
