### ISSUE TITLE
[archive.org] Unable to extract jwplayer playlist

### ISSUE THREAD

**Issue by alx-xlx** [ytdl-org/youtube-dl#23700]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.01.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://archive.org/details/beyond_bengal', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.01.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg git-2019-12-04-d5274f8, ffprobe git-2019-12-04-d5274f8
[debug] Proxy map: {}
[archive.org] beyond_bengal: Downloading webpage
ERROR: Unable to extract jwplayer playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\archiveorg.py", line 45, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract jwplayer playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I have tried multiple archive.org video links but to no avail, I even tried passing username & password but no success.
I think "**Unable to extract jwplayer playlist**" is where the issue is

Thank You

**Comment by alx-xlx** [comment]
Closed this issue at first because I saw someone already opened this issue https://github.com/ytdl-org/youtube-dl/issues/23586
but then it was not properly made so opened mine again :)
