### ISSUE TITLE
Twitter: File name too long

### ISSUE THREAD

**Issue by buzo-ffm** [ytdl-org/youtube-dl#23723]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v https://twitter.com/atulkasbekar/status/1215128694584270849/video/1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://twitter.com/atulkasbekar/status/1215128694584270849/video/1']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.01.01
[debug] Python version 3.8.1 (CPython) - Linux-5.4.11-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[twitter] 1215128694584270849: Downloading guest token
[twitter] 1215128694584270849: Downloading JSON metadata
[twitter] 1215128694584270849: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://video.twimg.com/ext_tw_video/1215128591484248064/pu/vid/640x416/iBxXlPWlm17uEWSB.mp4?tag=10'
ERROR: unable to open for writing: [Errno 36] File name too long: 'atul kasbekar - An astrophotographer has clicked an exceptional video, wherein we can feel the rotation of the earth  Using a tracking mount, aligned with North Star, he kept clicking images every 12 seconds for the next 3 hours.  The camera is looking at the same portion of the Milky Way  Fab!-1215128694584270849.mp4.part'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 249, in download
    ctx.stream, ctx.tmpfilename = sanitize_open(
  File "/usr/lib/python3.8/site-packages/youtube_dl/utils.py", line 2046, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
OSError: [Errno 36] File name too long: 'atul kasbekar - An astrophotographer has clicked an exceptional video, wherein we can feel the rotation of the earth  Using a tracking mount, aligned with North Star, he kept clicking images every 12 seconds for the next 3 hours.  The camera is looking at the same portion of the Milky Way  Fab!-1215128694584270849.mp4.part'
```

## Description

You have to provide a file name via the `-o` option, otherwise it does not work – see above.

**Comment by buzo-ffm** [comment]
Duplicate of which issue?

**Comment by StyxBzh** [comment]
It's a problem with the length of the auto title, outputing Errno 36 or Errno 2 (from what I found)
Duplicate of #23062 and other
You can solve you problem with
>youtube-dl --id https://twitter.com/atulkasbekar/status/1215128694584270849/video/1

The name of your file will be a string of number so you should rename it but the download will work now
