### ISSUE TITLE
[UFC.com] Add support

### ISSUE THREAD

**Issue by channelmars** [ytdl-org/youtube-dl#23737]
## Checklist

- [ x] I'm reporting a new site support request
- [x ] I've verified that I'm running youtube-dl version **2020.01.01**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that none of provided URLs violate any copyrights
- [x ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.ufc.com/video/ufc-246-embedded-episode-1-mcgregor-cowboy
- Single video: https://www.ufc.com/video/ufc-246-countdown-mcgregor-vs-cowboy
- Single video: https://www.ufc.com/video/ufc-246-top-finishes-conor-mcgregor-highlights

## Description

youtube-dl -v https://www.ufc.com/video/ufc-246-top-finishes-conor-mcgregor-highlights
[debug] System config: []
[debug] User config: ['-c', '-i', '-o', 'E:\\Downloads\\%(upload_date)s - %(title)s.%(ext)s', '--format', 'bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best', '--merge-output-format', 'mp4', '--youtube-skip-dash-manifest']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.ufc.com/video/ufc-246-top-finishes-conor-mcgregor-highlights']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.01.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-92982-g282a471857
[debug] Proxy map: {}
[generic] ufc-246-top-finishes-conor-mcgregor-highlights: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ufc-246-top-finishes-conor-mcgregor-highlights: Downloading webpage
[generic] ufc-246-top-finishes-conor-mcgregor-highlights: Extracting information
ERROR: Unsupported URL: https://www.ufc.com/video/ufc-246-top-finishes-conor-mcgregor-highlights
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\generic.py", line 3347, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.ufc.com/video/ufc-246-top-finishes-conor-mcgregor-highlights

**Comment by channelmars** [comment]
@dstftw Any chance you can look into this and add support? Thanks a lot.
