### ISSUE TITLE
Twitter video does not work anymore with version 2020.01.15

### ISSUE THREAD

**Issue by StyxBzh** [ytdl-org/youtube-dl#23746]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.15**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
D:\Video\Rip internet>youtube-dl -v https://twitter.com/NXOnNetflix/status/1216766859955056640
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://twitter.com/NXOnNetflix/status/1216766859955056640']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.01.15
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-01-01-7b58702, ffprobe git-2020-01-01-7b58702
[debug] Proxy map: {}
[twitter] 1216766859955056640: Downloading guest token
[twitter] 1216766859955056640: Downloading JSON metadata
[twitter] 1216766859955056640: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://video.twimg.com/amplify_video/1216457274975064064/vid/1280x720/SVylb1vbWJGQIPGg.mp4?tag=13'
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'NX - The furry murder mystery romance Beastars finally drops March 13th! Join anxious wolf boy Legosi on his journey to solve a friend’s murder and, even harder, understand his feelings toward dwarf rabbit Haru. #Beastars-1216766859955056640.mp4.part'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\downloader\http.py", line 250, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\utils.py", line 2046, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'NX - The furry murder mystery romance Beastars finally drops March 13th! Join anxious wolf boy Legosi on his journey to solve a friend’s murder and, even harder, understand his feelings toward dwarf rabbit Haru. #Beastars-1216766859955056640.mp4.part'

```

## Description

As requested by using the comand line to update youtube-dl, I'm up to date with version 2020.010.15 But now every try to download a twitter video it ends up in a fail with the error : FileNotFoundError: [Errno 2]; I've tryed some other vid on the twitter platform that end up with the same problem.
I've tryed some other sites like youtube.com and downloads works perfectly
I dunno if it's a recent change in the twitter code or a bug from the new youtube-dl update (for the time being I use 9xbuddy on twitter and it works)

I hope I'll be of some help.
Have a Nice day, a happy 2020 year
AND THANK YOU FOR YOUR WORK ♥♥

**Comment by StyxBzh** [comment]
Found a workaround
Duplicate of #23062 and other
You can solve the problem with

    youtube-dl --id https://twitter.com/XXXXXXXXXXXXXX

The name of your file will be a string of number so you should rename it but the download will work now
