### ISSUE TITLE
Unable to download dailymotion.com videos in two different Linux boxes.

### ISSUE THREAD

**Issue by antdude** [ytdl-org/youtube-dl#23744]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.01.15**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
Unable to download dailymotion.com's videos like these:

$ youtube-dl -v https://www.dailymotion.com/video/x6pko54
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.dailymotion.com/video/x6pko54']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.15
[debug] Python version 2.7.9 (CPython) - Linux-3.16.0-10-amd64-x86_64-with-debia                                      n-8.11
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1, rtmpdump 2.4
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ant/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/home/ant/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/home/ant/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_mai                                      n
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in downloa                                      d
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_                                      info
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in e                                      xtract
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 235,                                       in _real_extract
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 50,                                       in _call_api
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 31,                                       in _get_dailymotion_cookies
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 2831, in                                       _get_cookies
  File "/usr/lib/python2.7/Cookie.py", line 582, in __init__
    if input: self.load(input)
  File "/usr/lib/python2.7/Cookie.py", line 642, in load
    for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'

AND

$ youtube-dl -v https://www.dailymotion.com/video/x6pko54
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.dailymotion.com/video/x6pko54']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.15
[debug] Python version 2.7.17 (CPython) - Linux-5.2.18-100.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
[debug] exe versions: ffmpeg 4.0.5, ffprobe 4.0.5, rtmpdump 2.4
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ant/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/home/ant/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/home/ant/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 235, in _real_extract
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 50, in _call_api
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 31, in _get_dailymotion_cookies
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 2831, in _get_cookies
  File "/usr/lib64/python2.7/Cookie.py", line 583, in __init__
    if input: self.load(input)
  File "/usr/lib64/python2.7/Cookie.py", line 643, in load
    for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'

```

## Description

WRITE DESCRIPTION HERE
Unable to download dailymotion.com videos in both 64-bit Fedora and Debian.

**Comment by antdude** [comment]
Where?
