### ISSUE TITLE
rai

### ISSUE THREAD

**Issue by avagraha** [ytdl-org/youtube-dl#23750]
## Checklist

- [x ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2020.01.15**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x  links expired] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

1 of 3):

C:\Users\andreaa>y -v
https://www.raiplay.it/video/2020/01/il-paradiso-delle-
signore-daily-s4e62-30ea2039-6c0a-43d1-93fb-3ae502758859.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.raiplay.it/video/2020/01/il-
paradiso-delle-signore-daily-s4e62-30ea2039-6c0a-43d1-93fb-3ae502758859.htm
l']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.01.15
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6002-SP2
[debug] exe versions: ffmpeg N-94698-g83e0b71-Reino, ffprobe N-94698-g83e0b
71-Reino, rtmpdump 2.4
[debug] Proxy map: {}
[RaiPlay] 30ea2039-6c0a-43d1-93fb-3ae502758859: Downloading video JSON
ERROR: 30ea2039-6c0a-43d1-93fb-3ae502758859: Failed to parse JSON  (caused
by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report
 this issue on https://yt-dl.org/bug . Make sure you are using the latest v
ersion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the
 --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4
3n_zyg3\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4
3n_zyg3\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4
3n_zyg3\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4
3n_zyg3\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4
3n_zyg3\build\youtube_dl\extractor\rai.py", line 174, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4
3n_zyg3\build\youtube_dl\extractor\common.py", line 892, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4
3n_zyg3\build\youtube_dl\extractor\common.py", line 876, in _download_json_
handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4
3n_zyg3\build\youtube_dl\extractor\common.py", line 903, in _parse_json
youtube_dl.utils.ExtractorError: 30ea2039-6c0a-43d1-93fb-3ae502758859: Fail
ed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (
char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure
you are using the latest version; type  youtube-dl -U  to update. Be sure t
o call youtube-dl with the --verbose flag and include its complete output.

===============

2 of 3):

C:\Users\andreaa>y -v
https://www.raiplay.it/video/2020/01/festival-di-sanrem
o---conferenza-stampa-cc8f0c34-e347-4e71-ba9a-a09e560b12b1.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.raiplay.it/video/2020/01/fes
tival-di-sanremo---conferenza-stampa-cc8f0c34-e347-4e71-ba9a-a09e560b12b1.h
tml']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.01.15
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6002-SP2
[debug] exe versions: ffmpeg N-94698-g83e0b71-Reino, ffprobe N-94698-g83e0b
71-Reino, rtmpdump 2.4
[debug] Proxy map: {}
[RaiPlay] cc8f0c34-e347-4e71-ba9a-a09e560b12b1: Downloading video JSON
ERROR: cc8f0c34-e347-4e71-ba9a-a09e560b12b1: Failed to parse JSON  (caused
by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report
 this issue on https://yt-dl.org/bug . Make sure you are using the latest v
ersion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the
 --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4
3n_zyg3\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4
3n_zyg3\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4
3n_zyg3\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4
3n_zyg3\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4
3n_zyg3\build\youtube_dl\extractor\rai.py", line 174, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4
3n_zyg3\build\youtube_dl\extractor\common.py", line 892, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4
3n_zyg3\build\youtube_dl\extractor\common.py", line 876, in _download_json_
handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4
3n_zyg3\build\youtube_dl\extractor\common.py", line 903, in _parse_json
youtube_dl.utils.ExtractorError: cc8f0c34-e347-4e71-ba9a-a09e560b12b1: Fail
ed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (
char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure
you are using the latest version; type  youtube-dl -U  to update. Be sure t
o call youtube-dl with the --verbose flag and include its complete output.

================

3 of 3):

C:\Users\andreaa>y -v https://www.raiplay.it/dirette/rai3
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.raiplay.it/dirette/rai3']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.01.15
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6002-SP2
[debug] exe versions: ffmpeg N-94698-g83e0b71-Reino, ffprobe N-94698-g83e0b
71-Reino, rtmpdump 2.4
[debug] Proxy map: {}
[RaiPlayLive] rai3: Downloading webpage
[RaiPlay] 1aa5c4a0-a2d4-4415-b268-e2fe47fe7164: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused
by HTTPError()); please report this issue on https://yt-dl.org/bug . Make s
ure you are using the latest version; type  youtube-dl -U  to update. Be su
re to call youtube-dl with the --verbose flag and include its complete outp
ut.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4
3n_zyg3\build\youtube_dl\extractor\common.py", line 627, in _request_webpag
e
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4
3n_zyg3\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_respon
se
  File "C:\Python\Python34\lib\urllib\request.py", line 502, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain

  File "C:\Python\Python34\lib\urllib\request.py", line 685, in http_error_
302
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_respon
se
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain

  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_
default

## Description

WRITE DESCRIPTION HERE
The site has been updated, *NO* account required.
only the first two logs are the same thing I guess.

**Comment by avagraha** [comment]
In the main thred the links expired, therefore here you find the updated 
working links.


  ----- Original Message -----
