### ISSUE TITLE
LiveTV stream from webcaster.pro issue

### ISSUE THREAD

**Issue by SlazE888** [ytdl-org/youtube-dl#23759]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.15**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://bl.webcaster.pro/media/start/free_ba0
c823b66f4ff43c2e1098fa9fc5153_hd/65_97993691/da6ef3662bcd0e3fd878ea24d30378f0/46
70217901.m3u8']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2020.01.15
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Webcaster] ba0c823b66f4ff43c2e1098fa9fc5153_hd: Downloading XML
ERROR: ba0c823b66f4ff43c2e1098fa9fc5153_hd: Failed to parse XML  (caused by Pars
eError('syntax error: line 1, column 0',)); please report this issue on https://
yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U
 to update. Be sure to call youtube-dl with the --verbose flag and include its c
omplete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zy
g3\build\youtube_dl\extractor\common.py", line 849, in _parse_xml
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zy
g3\build\youtube_dl\compat.py", line 2522, in compat_etree_fromstring
  File "C:\Python\Python34\lib\xml\etree\ElementTree.py", line 1335, in XML
  File "<string>", line None
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zy
g3\build\youtube_dl\extractor\common.py", line 849, in _parse_xml
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zy
g3\build\youtube_dl\compat.py", line 2522, in compat_etree_fromstring
  File "C:\Python\Python34\lib\xml\etree\ElementTree.py", line 1335, in XML
  File "<string>", line None
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zy
g3\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zy
g3\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zy
g3\build\youtube_dl\extractor\webcaster.py", line 33, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zy
g3\build\youtube_dl\extractor\common.py", line 842, in _download_xml
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zy
g3\build\youtube_dl\extractor\common.py", line 826, in _download_xml_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zy
g3\build\youtube_dl\extractor\common.py", line 853, in _parse_xml
youtube_dl.utils.ExtractorError: ba0c823b66f4ff43c2e1098fa9fc5153_hd: Failed to
parse XML  (caused by ParseError('syntax error: line 1, column 0',));
```

## Description

LiveTV-stream plays fine in Google Chrome browser through this extension:
[chrome-extension://cjfbmleiaobegagekpmlhmaadepdeedn/index.html#https://bl.webcaster.pro/media/start/free_ba0c823b66f4ff43c2e1098fa9fc5153_hd/65_97993691/da6ef3662bcd0e3fd878ea24d30378f0/4670217901.m3u8](url)

**Comment by dstftw** [comment]
You must use the original URL.

**Comment by SlazE888** [comment]
For what? URL above  been working for months! I got it from this site:
 https://obl1.ru/online
