### ISSUE TITLE
youtube playlist format listing fails

### ISSUE THREAD

**Issue by jmayer** [ytdl-org/youtube-dl#23752]
- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version GIT HEAD
- [ x] I've checked that all provided URLs are alive and playable in a browser (at least the first 4 videos play in browser continously)
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose -F "https://www.youtube.com/watch?v=haECT-SerHk&list=RDEMWdkULuu9su9qCNSO_vSQZw&start_radio=1"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-F', u'https://www.youtube.com/watch?v=haECT-SerHk&list=RDEMWdkULuu9su9qCNSO_vSQZw&start_radio=1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.15
[debug] Python version 2.7.16 (CPython) - Darwin-19.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-96108-g191df4f2d1, ffprobe N-96108-g191df4f2d1
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist RDEMWdkULuu9su9qCNSO_vSQZw - add --no-playlist to just download video haECT-SerHk
[youtube:playlist] RDEMWdkULuu9su9qCNSO_vSQZw: Downloading page 1 of Youtube mix
[youtube:playlist] RDEMWdkULuu9su9qCNSO_vSQZw: Downloading page 2 of Youtube mix
[youtube:playlist] RDEMWdkULuu9su9qCNSO_vSQZw: Downloading page 3 of Youtube mix
[youtube:playlist] RDEMWdkULuu9su9qCNSO_vSQZw: Downloading page 4 of Youtube mix
[youtube:playlist] RDEMWdkULuu9su9qCNSO_vSQZw: Downloading page 5 of Youtube mix
[download] Downloading playlist: Mix - Helene Fischer
[youtube:playlist] playlist Mix - Helene Fischer: Collected 92 video ids (downloading 92 of them)
[download] Downloading video 1 of 92
[youtube] qCNSO_vSQZw: Downloading webpage
[youtube] qCNSO_vSQZw: Downloading video info webpage
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: This video is unavailable.
Sorry about that.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2152, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is unavailable.
Sorry about that.

```

## Description

Trying to list available formats for a playlist on youtube fails.

**Comment by dstftw** [comment]
qCNSO_vSQZw is not available.
