### ISSUE TITLE
[bug] pornhub.com user

### ISSUE THREAD

**Issue by azev** [ytdl-org/youtube-dl#23766]
```
yt-dl --verbose https://www.pornhub.com/model/rosieandalena
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.pornhub.com/model/rosieandalena']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.01.15
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-94129-g098ab93257, ffprobe N-94129-g098ab93257
[debug] Proxy map: {}
[PornHubPagedVideoList] model/rosieandalena/videos: Downloading page 1
[PornHubPagedVideoList] model/rosieandalena/videos: Downloading page 2
[PornHubPagedVideoList] model/rosieandalena/videos: Downloading page 3
[PornHubPagedVideoList] model/rosieandalena/videos: Downloading page 4
[download] Downloading playlist: model/rosieandalena/videos
[PornHubPagedVideoList] playlist model/rosieandalena/videos: Collected 146 video ids (downloading 146 of them)
[download] Downloading video 1 of 146
[PornHub] ph5d3c7aaaa4642: Downloading pc webpage
[PornHub] ph5d3c7aaaa4642: Downloading tv webpage
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\extractor\pornhub.py", line 286, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\extractor\pornhub.py", line 233, in extract_js_vars
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by azev** [comment]
why tagged as invalid?

**Comment by dstftw** [comment]
ph5d3c7aaaa4642 is not publicly available.
