### ISSUE TITLE
Broken/Misfunctioning Site: VIU

### ISSUE THREAD

**Issue by NaufalAriqS21** [ytdl-org/youtube-dl#23774]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.15**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\nasa>youtube-dl --version
2020.01.15
C:\Users\nasa>youtube-dl -v https://www.viu.com/ott/id/id/all/video-indonesian-drama-tv_shows-assalamualaikum_calon_imam_episode_1-1165642117?containerId=playlist-26089250
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.viu.com/ott/id/id/all/video-indonesian-drama-tv_shows-assalamualaikum_calon_imam_episode_1-1165642117?containerId=playlist-26089250']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.01.15
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[generic] video-indonesian-drama-tv_shows-assalamualaikum_calon_imam_episode_1-1165642117?containerId=playlist-26089250: Requesting header
WARNING: Falling back on generic information extractor.
[generic] video-indonesian-drama-tv_shows-assalamualaikum_calon_imam_episode_1-1165642117?containerId=playlist-26089250: Downloading webpage
[generic] video-indonesian-drama-tv_shows-assalamualaikum_calon_imam_episode_1-1165642117?containerId=playlist-26089250: Extracting information
ERROR: Unsupported URL: https://www.viu.com/ott/id/id/all/video-indonesian-drama-tv_shows-assalamualaikum_calon_imam_episode_1-1165642117?containerId=playlist-26089250
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\extractor\generic.py", line 3347, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.viu.com/ott/id/id/all/video-indonesian-drama-tv_shows-assalamualaikum_calon_imam_episode_1-1165642117?containerId=playlist-26089250
```

## Description

Viu change the page,
e.g. :  https://www.viu.com/ott/id/id/all/video-indonesian-drama-tv_shows-assalamualaikum_calon_imam_episode_1-1165642117?containerId=playlist-26089250

**id** is region, and written twice.

**Comment by kazakore** [comment]
Still not working in 2020.06.16.1

This is listed as a supported site and there is a youtube_dl/extractor/viu.py packge.

Is this being worked on?

**Comment by kazakore** [comment]
$ youtube-dl --version
2020.06.16.1


$ youtube-dl -v "https://www.viu.com/ott/gh/en/all/video-english-drama-movies-miss_taken-1165605457?containerId=playlist-26125888"[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.viu.com/ott/gh/en/all/video-english-drama-movies-miss_taken-1165605457?containerId=playlist-26125888']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.2 (CPython) - Linux-5.6.10-1-rt5-MANJARO-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] video-english-drama-movies-miss_taken-1165605457?containerId=playlist-26125888: Requesting header
WARNING: Falling back on generic information extractor.
[generic] video-english-drama-movies-miss_taken-1165605457?containerId=playlist-26125888: Downloading webpage
[generic] video-english-drama-movies-miss_taken-1165605457?containerId=playlist-26125888: Extracting information
Traceback (most recent call last):
  File "/home/me/.local/bin/youtube-dl", line 8, in <module>
    sys.exit(main())
  File "/home/me/.local/lib/python3.8/site-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/home/me/.local/lib/python3.8/site-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/me/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2018, in download
    res = self.extract_info(
  File "/home/me/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/me/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/me/.local/lib/python3.8/site-packages/youtube_dl/extractor/generic.py", line 3286, in _real_extract
    json_ld = self._search_json_ld(
  File "/home/me/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1202, in _search_json_ld
    json_ld = self._json_ld(json_ld, video_id, fatal=fatal, expected_type=expected_type)
  File "/home/me/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1312, in _json_ld
    extract_video_object(e)
  File "/home/me/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1266, in extract_video_object
    'timestamp': unified_timestamp(e.get('uploadDate')),
  File "/home/me/.local/lib/python3.8/site-packages/youtube_dl/utils.py", line 2963, in unified_timestamp
    date_str = re.sub(r'[,|]', '', date_str)
  File "/usr/lib/python3.8/re.py", line 208, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
