### ISSUE TITLE
[YouTube] Ignore private videos

### ISSUE THREAD

**Issue by Lastique** [ytdl-org/youtube-dl#23788]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.01.15**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Please, add an option to ignore/skip any private videos in a YouTube playlist.

Currently, if there is a private video in the middle of a playlist, youtube-dl will fail obtaining parameters of the video (such as its id) and will not process any videos after it. Here is an example:

```
./youtube-dl -v -s --get-id -f "bestvideo[height<=?1080]+bestaudio/best" 'https://www.youtube.com/playlist?list=PLj_Goi54wf0crhejwwkQlGucYtD0LbNBL'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-s', u'--get-id', u'-f', u'bestvideo[height<=?1080]+bestaudio/best', u'https://www.youtube.com/playlist?list=PLj_Goi54wf0crhejwwkQlGucYtD0LbNBL']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2020.01.15
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-26-lowlatency-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.2.1-1mind3, ffprobe 4.2.1-1mind3, rtmpdump 2.4
[debug] Proxy map: {}
-vEyzktsit8
h0TLSEgtPG4
p4dFfjHWq7Y
p6MUcLMdUQ0
QcmfrTKMEmI
-5mCdDQnYNc
mWFhndPp47Y
P8ICVz3l8nM
IkxujHlFfJY
KMTiANXi8C8
mCH-nhXns1M
lw7F7xASa9E
AG-sCzAMx8A
LN8XRp1FjpQ
V7c6TaxOMO4
aVKuPpPIqno
dABB-joZfT8
eWuu1v0myyE
dzXN3qRabzA
v20yjdl90WY
eUVytQ9S0t4
xSpldxFt7mI
zNR10xc_gfY
VT3P1xZ3rWk
Yhup-eFAeiE
E7ePU34bFsI
ivp35wvwR_c
VQbShONDCFw
ZvZJvIy7x0Y
RUYKaZDhVJo
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 2152, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.
```

**Comment by dstftw** [comment]
`-i`.

**Comment by Lastique** [comment]
Thanks, I missed it.
