### ISSUE TITLE
americastestkitchen.com ERROR: 649: Failed to parse JSON

### ISSUE THREAD

**Issue by teridon** [ytdl-org/youtube-dl#23787]
Downloading from this site used to work; I'm not sure what changed.
This is youtube-dl version 2020.01.15.  The video works in the browser.

```
# youtube-dl --verbose https://www.americastestkitchen.com/episode/632-summer-picnic-party
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.americastestkitchen.com/episode/632-summer-picnic-party']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.01.15
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-80906-gd5edb6c, ffprobe N-80906-gd5edb6c, rtmpdump 2.3
[debug] Proxy map: {}
[AmericasTestKitchen] 632: Downloading webpage
ERROR: 632: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 43 (char 42)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using th
e latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 43 (char 42)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 43 (char 42)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\extractor\americastestkitchen.py", line 50, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\extractor\common.py", line 903, in _parse_json
youtube_dl.utils.ExtractorError: 632: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 43 (char 42)',)); please report this issue on https://yt-dl.org/bug .
Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

I tried with generic extractor also, but that gives the error
```ERROR: Unsupported URL```

**Comment by remitamine** [comment]
already fixed, wait for next release.

**Comment by StevenDTX** [comment]
Thanks @remitamine , I confirmed this fixes the issue.
