### ISSUE TITLE
itunes

### ISSUE THREAD

**Issue by Albretch** [ytdl-org/youtube-dl#23801]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by Albretch** [comment]
$ python ./youtube-dl --verbose "https://podcasts.apple.com/de/podcast/ausgabe-01-guten-appetit/id343005093?i=1000079203487"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://podcasts.apple.com/de/podcast/ausgabe-01-guten-appetit/id343005093?i=1000079203487']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-11-amd64-x86_64-with-debian-9.11
[debug] exe versions: avconv 3.2.14-1, avprobe 3.2.14-1, ffmpeg 3.2.14-1, ffprobe 3.2.14-1
[debug] Proxy map: {}
[generic] id343005093?i=1000079203487: Requesting header
WARNING: Falling back on generic information extractor.
[generic] id343005093?i=1000079203487: Downloading webpage
[generic] id343005093?i=1000079203487: Extracting information
ERROR: Unsupported URL: https://podcasts.apple.com/de/podcast/ausgabe-01-guten-appetit/id343005093?i=1000079203487
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 2373, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "./youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "./youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: duplicate attribute: line 2, column 51
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 3355, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://podcasts.apple.com/de/podcast/ausgabe-01-guten-appetit/id343005093?i=1000079203487

$

**Comment by remitamine** [comment]
fill the proper issue template.
