### ISSUE TITLE
http://www.pbs.org/frontlineworld

### ISSUE THREAD

**Issue by ole-tange** [ytdl-org/youtube-dl#23808]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.15**
- [x] I've checked that all provided URLs are alive (but missing flash 9 I cannot test playable in a browser)
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.pbs.org/frontlineworld/stories/pakistan802/video/video_index.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.15
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-72-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Using fake IP 6.180.170.49 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] video_index: Downloading webpage
ERROR: Unable to extract OpenGraph url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 540, in _real_extract
    video_id, display_id, upload_date, description = self._extract_webpage(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 505, in _extract_webpage
    url = self._og_search_url(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1126, in _og_search_url
    return self._og_search_property('url', html, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1105, in _og_search_property
    escaped = self._search_regex(og_regexes, html, name, flags=re.DOTALL, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract OpenGraph url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Playing in browser requires Flash 9. I have not access to a machine with that.

**Comment by 89z** [comment]
here you go:

https://pbs.org/video/frontlineworld-children-of-the-taliban
