### ISSUE TITLE
[Twitter] cannot download video

### ISSUE THREAD

**Issue by SpaceRacet5w2A6l0I** [ytdl-org/youtube-dl#23803]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.15**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\abc> youtube-dl -v https://twitter.com/DraganDjilas/status/1219328167971885056
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://twitter.com/DraganDjilas/status/1219328167971885056']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.01.15
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
[twitter] 1219328167971885056: Downloading guest token
[twitter] 1219328167971885056: Downloading JSON metadata
[twitter] 1219328167971885056: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://video.twimg.com/ext_tw_video/1219328127039627265/pu/vid/576x320/zA7xurQ4uysd_Vq5.mp4?tag=10'
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'Dragan Djilas - Vucicu, na dan kad je ubijen Oliver, na mrezama su tvoji sledbenici pustili spot za Mariniku identican onome koji je prethodio Oliverovom ubistvu! Javno ti porucujem da za  sve sto se desi ti ces biti direktno odgovoran.-1219328167971885056.mp4.part'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\downloader\http.py", line 250, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\utils.py", line 2046, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'Dragan Djilas - Vucicu, na dan kad je ubijen Oliver, na mrezama su tvoji sledbenici pustili spot za Mariniku identican onome koji je prethodio Oliverovom ubistvu! Javno ti porucujem da za  sve sto se desi ti ces biti direktno odgovoran.-1219328167971885056.mp4.part'
```

## Description

Everything is in the verbose log.

**Comment by SpaceRacet5w2A6l0I** [comment]
@remitamine Fuck you, why did you close the issue without leting me know which one is the actual duplicate? Go fuck yourself. Also fuck @dstftw for being very unwelcoming. This repository is shit.

**Comment by kcubeterm** [comment]
@ghost , don't be angry bro
