### ISSUE TITLE
ExtractorError: Unsupported JS expression

### ISSUE THREAD

**Issue by theraw** [ytdl-org/youtube-dl#23829]
```bash
root@dope:/home/radio/music# ./down https://www.youtube.com/watch?v=IKFuaExJ-EI
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[youtube] IKFuaExJ-EI: Downloading webpage
[youtube] IKFuaExJ-EI: Downloading video info webpage
[youtube] IKFuaExJ-EI: Downloading js player vfl7lL1_p
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1384, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1297, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1360, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by theraw** [comment]
```bash
root@dope:/home/radio/music# youtube-dl --version
2020.01.15
```

**Comment by h1z1** [comment]
Though they keep closing and locking these tickets rather then keeping one open with an actual update - The problem doesn't affect all videos.  I've even hit the same caches where one works but the other doesn't.

[This](https://www.youtube.com/watch?v=fqa3npnLimg "Level1 Linux") for example works. 

It is interesting the number of projects (and products), that are/were using ytdl and are now also down.  That I have little sympathy for.  Youtube has an API.

**Comment by theraw** [comment]
actually after updating it worked with no problems i had like 10 links not being able to dl after update was able to download them all

**Comment by NucleaPeon** [comment]
FYI (this issue helped me track down the issue), Gentoo's youtube-dl version is 2020.01.15, which IS out of date even though I sync'd and emerge'd the latest. 

@theraw your link worked, but this one did not: https://www.youtube.com/watch?v=wC4TASbzXrU

**Comment by h1z1** [comment]
Link worked for me.

```Turmion Kätilöt - Faster Than God-wC4TASbzXrU.webm```
