### ISSUE TITLE
NFL.com: No video formats found error

### ISSUE THREAD

**Issue by wrldwzrd89** [ytdl-org/youtube-dl#23844]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: [u'-o', u'~/Movies/Unsorted/%(title)s@%(id)s.%(ext)s', u'--ignore-errors', u'--no-overwrites', u'--youtube-skip-dash-manifest', u'-f', u'best', u'--fixup', u'detect_or_warn']
[debug] Custom config: []
[debug] Command-line args: [u'http://www.nfl.com/videos/game-theory/0ap3000001098622/Game-Theory-Final-Super-Bowl-LIV-score-projection', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out None, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 2.7.16 (CPython) - Darwin-19.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[nfl.com] Game-Theory-Final-Super-Bowl-LIV-score-projection: Downloading webpage
[nfl.com] 0ap3000001098622: Downloading player config
[nfl.com] 0ap3000001098622: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/nfl.py", line 215, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Trying to download one of Cynthia Frelund's NFL analysis videos fails, after the JSON metadata is downloaded, saying that no downloadable format was found. Guessing NFL.com updated their player. Video plays in Chrome A-OK.

**Comment by remitamine** [comment]
support for the website will be restored in the next version.
