### ISSUE TITLE
Error: Signature extraction failed: Traceback (most recent call last): Al convertir el audio a MP3

### ISSUE THREAD

**Issue by kingdsand** [ytdl-org/youtube-dl#23840]
## Checklist

- [X ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2020.01.24**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1383, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1297, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1360, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 91, in interpret_expression
    right_val = self.interpret_expression(
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 188, in interpret_expression
    x, abort = self.interpret_statement(
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 188, in interpret_expression
    x, abort = self.interpret_statement(
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE

**Comment by kingdsand** [comment]
por que cierran mis reportes sin darles solucion
