### ISSUE TITLE
Vimeo albums stopped downloading

### ISSUE THREAD

**Issue by asert777** [ytdl-org/youtube-dl#23864]
## Checklist

- [*] I'm reporting a broken site support
- [*] I've verified that I'm running youtube-dl version **2020.01.24**
- [*] I've checked that all provided URLs are alive and playable in a browser
- [*] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [*] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://vimeo.com/showcase/6734903']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo:album] 6734903: Downloading webpage
ERROR: Unable to extract vimeo config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\vimeo.py", line 977, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\vimeo.py", line 108, in _extract_vimeo_config
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract vimeo config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

**Comment by remitamine** [comment]
getting this message in the browser:
```
This showcase is private
```

**Comment by asert777** [comment]
I have a password.
powershell output:
`
.\youtube-dl.exe https://vimeo.com/showcase/3118216 --video-password tor16-oz
[vimeo:album] 3118216: Downloading webpage
ERROR: Unable to extract vimeo config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`
There is one video to download, then everything works. If you try to download the album, an error appears.

Album for example:
https://vimeo.com/showcase/3118216
Pass: tor16-oz

Thanks!
