### ISSUE TITLE
TestDownload.test_YoutubePlaylist broken

### ISSUE THREAD

**Issue by jxu** [ytdl-org/youtube-dl#23872]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

N/A 

## Description

`YoutubePlaylist` test is broken. `YoutubePlaylists` works.

```
$ python3 test/test_download.py TestDownload.test_YoutubePlaylist
[youtube:playlist] PLwiyx1dc3P2JR9N8gQaQN_BCvlSlap7re: Downloading webpage
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "/home/jx/Documents/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/jx/Documents/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/jx/Documents/youtube-dl/youtube_dl/extractor/youtube.py", line 2815, in _real_extract
    has_videos, playlist = self._extract_playlist(playlist_id)
  File "/home/jx/Documents/youtube-dl/youtube_dl/extractor/youtube.py", line 2738, in _extract_playlist
    raise ExtractorError(message, expected=True)
youtube_dl.utils.ExtractorError: This playlist does not exist.

E
======================================================================
ERROR: test_YoutubePlaylist (__main__.TestDownload):
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jx/Documents/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/jx/Documents/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/jx/Documents/youtube-dl/youtube_dl/extractor/youtube.py", line 2815, in _real_extract
    has_videos, playlist = self._extract_playlist(playlist_id)
  File "/home/jx/Documents/youtube-dl/youtube_dl/extractor/youtube.py", line 2738, in _extract_playlist
    raise ExtractorError(message, expected=True)
youtube_dl.utils.ExtractorError: This playlist does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test/test_download.py", line 159, in test_template
    force_generic_extractor=params.get('force_generic_extractor', False))
  File "/home/jx/Documents/youtube-dl/youtube_dl/YoutubeDL.py", line 819, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/home/jx/Documents/youtube-dl/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/home/jx/Documents/youtube-dl/youtube_dl/YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: This playlist does not exist.

----------------------------------------------------------------------
Ran 1 test in 0.549s

FAILED (errors=1)
```

**Comment by dstftw** [comment]
Feel free to file a PR.

**Comment by jxu** [comment]
For info: https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L2497-L2658 

Playlists that do not exist any more:
- 'ytdl test PL' https://www.youtube.com/playlist?list=PLwiyx1dc3P2JR9N8gQaQN_BCvlSlap7re
- 'YDL_Empty_List' https://www.youtube.com/playlist?list=PLtPgu7CB4gbZDA7i_euNxn75ISqxwZPYx
- 'YDL_safe_search' https://www.youtube.com/playlist?list=PLtPgu7CB4gbY9oDN3drwC3cMbJggS7dKl

**Comment by jxu** [comment]
@dstftw why is this issue closed when it has not been resolved or marked as duplicate, invalid, etc.?
