### ISSUE TITLE
la7

### ISSUE THREAD

**Issue by avagraha** [ytdl-org/youtube-dl#23889]
## Checklist

- [ x] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2020.01.24**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

  Two different logs.

C:\Users>y -v https://www.la7.it/nonelarena/video/amadeusconfermare-j
unior-cally-a-sanremo-assolutamente-si-29-01-2020-304754
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.la7.it/nonelarena/video/amad
eusconfermare-junior-cally-a-sanremo-assolutamente-si-29-01-2020-304754']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6002-SP2
[debug] exe versions: ffmpeg N-94698-g83e0b71-Reino, ffprobe N-94698-g83e0b
71-Reino, rtmpdump 2.4
[debug] Proxy map: {}
[la7.it] amadeusconfermare-junior-cally-a-sanremo-assolutamente-si-29-01-20
20-304754: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 11001] getaddrinfo
 failed> (caused by URLError(gaierror(11001, 'getaddrinfo failed'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw
0w300z1\build\youtube_dl\extractor\common.py", line 627, in _request_webpag
e
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw
0w300z1\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain

  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw
0w300z1\build\youtube_dl\utils.py", line 2728, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open

==================================================

C:\Users>y -v https://www.la7.it/nonelarena/video/amadeusconfermare-j
unior-cally-a-sanremo-assolutamente-si-29-01-2020-304754
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.la7.it/nonelarena/video/amad
eusconfermare-junior-cally-a-sanremo-assolutamente-si-29-01-2020-304754']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6002-SP2
[debug] exe versions: ffmpeg N-94698-g83e0b71-Reino, ffprobe N-94698-g83e0b
71-Reino, rtmpdump 2.4
[debug] Proxy map: {}
[la7.it] amadeusconfermare-junior-cally-a-sanremo-assolutamente-si-29-01-20
20-304754: Downloading webpage
ERROR: amadeusconfermare-junior-cally-a-sanremo-assolutamente-si-29-01-2020
-304754: Failed to parse JSON  (caused by ValueError('Expecting value: line
 4 column 32 (char 497)',)); please report this issue on https://yt-dl.org/
bug . Make sure you are using the latest version; type  youtube-dl -U  to u
pdate. Be sure to call youtube-dl with the --verbose flag and include its c
omplete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw
0w300z1\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 4 column 32 (char 497)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw
0w300z1\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 4 column 32 (char 497)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw
0w300z1\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw
0w300z1\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw
0w300z1\build\youtube_dl\extractor\la7.py", line 55, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw
0w300z1\build\youtube_dl\extractor\common.py", line 903, in _parse_json
youtube_dl.utils.ExtractorError: amadeusconfermare-junior-cally-a-sanremo-a
ssolutamente-si-29-01-2020-304754: Failed to parse JSON  (caused by ValueEr
ror('Expecting value: line 4 column 32 (char 497)',)); please report this i
ssue on https://yt-dl.org/bug . Make sure you are using the latest version;
 type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verb
ose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE
please re-fix la7 thanks

**Comment by dstftw** [comment]
Stop posting duplicates.

**Comment by avagraha** [comment]
If you search engine gives me always "zero items found" (by typing La7) how 
can I know *in advance* if my post is a duplicate or not? good question.


  ----- Original Message -----
