### ISSUE TITLE
Youtube.com: youtube_dl.utils.ExtractorError: Unsupported JS expression '[1376500448,'; 

### ISSUE THREAD

**Issue by nazmifr** [ytdl-org/youtube-dl#23909]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.01.24**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
nazmi@debian:~$ youtube-dl --verbose https://www.youtube.com/watch?v=uDdCrHOKpxw --write-info
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=uDdCrHOKpxw', '--write-info']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.5.3 (CPython) - Linux-4.19.0-0.bpo.6-amd64-x86_64-with-debian-9.11
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] uDdCrHOKpxw: Downloading webpage
[youtube] uDdCrHOKpxw: Downloading video info webpage
[youtube] {18} signature length 106, html5 player vfl1GpCbm
[youtube] uDdCrHOKpxw: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vfl1GpCbm/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1380, in _decrypt_signature
    video_id, player_url, s
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1293, in _extract_signature_function
    cache_res = res(test_string)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1356, in <lambda>
    return lambda s: initial_function([s])
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '[1376500448,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '[1376500448,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1380, in _decrypt_signature
    video_id, player_url, s
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1293, in _extract_signature_function
    cache_res = res(test_string)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1356, in <lambda>
    return lambda s: initial_function([s])
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '[1376500448,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1380, in _decrypt_signature
    video_id, player_url, s
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1293, in _extract_signature_function
    cache_res = res(test_string)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1356, in <lambda>
    return lambda s: initial_function([s])
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '[1376500448,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 2043, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1390, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1380, in _decrypt_signature
    video_id, player_url, s
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1293, in _extract_signature_function
    cache_res = res(test_string)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1356, in <lambda>
    return lambda s: initial_function([s])
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/nazmi/.local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '[1376500448,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '[1376500448,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Hi, I've been encountering this bug on one particular video, checked the closed issues, there are a lot of similar ones but none with the same error:
```
Unsupported JS expression %r' % expr
```
```
youtube_dl.utils.ExtractorError: Unsupported JS expression '[1376500448,'; 
 (caused by ExtractorError("Unsupported JS expression '[1376500448,'; 
```

Is there any info about what's going on on these few videos that are having a hard time being dled? Anything I can help with?

**Comment by nazmifr** [comment]
The video that's causing issues

https://youtu.be/uDdCrHOKpxw

**Comment by nazmifr** [comment]
Oh crap indeed, to everyone that's stupid as I am, if you update youtube-dl on linux with pip, don't use sudo or the updated version will only be available as root...
```
pip3 install --upgrade youtube-dl
```
