### ISSUE TITLE
'Unable to extract %s' % _name'

### ISSUE THREAD

**Issue by ftdomingo** [ytdl-org/youtube-dl#23926]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
❯ youtube-dl  --verbose --all-sub --cookies cookies.txt "https://www.ondemandkorea.com/youns-kitchen-season-2-e1.html"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--all-sub', '--cookies', 'cookies.txt', 'https://www.ondemandkorea.com/youns-kitchen-season-2-e1.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.6.9 (CPython) - Linux-5.3.0-28-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[debug] Using fake IP 99.248.153.72 (CA) as X-Forwarded-For.
[OnDemandKorea] youns-kitchen-season-2-e1: Downloading webpage
ERROR: Unable to extract jw config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/ondemandkorea.py", line 52, in _real_extract
    webpage, 'jw config', group='options'),
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract jw config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

- Tried different web browsers (firefox, chrome, brave) to download cookies with cookies.txt extension.
- Replaced new lines with '\n'
- Tried with and without VPN
-  Haven't tried it on different OS

**Comment by Blunderchips** [comment]
Same error

**Comment by t3chnoshark** [comment]
Same here I think, cant use it at all. Tried multiple links with multiple options
