### ISSUE TITLE
[dailymotion] python errors after unattended-upgrade including python-apt

### ISSUE THREAD

**Issue by seahorse41** [ytdl-org/youtube-dl#23925]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v -F https://www.dailymotion.com/video/x7rbku3
[debug] System config: []
[debug] User config: [u'--restrict-filenames', u'-o', u'~/Downloads/%(title)s.%(uploader)s.%(id)s.%(format_id)s-%(height)sp.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.dailymotion.com/video/x7rbku3']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-11-686-pae-i686-with-debian-9.11
[debug] exe versions: ffmpeg N-96573-g73aab08d9d, ffprobe N-96573-g73aab08d9d, rtmpdump 2.4
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 235, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 50, in _call_api
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 31, in _get_dailymotion_cookies
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2831, in _get_cookies
  File "/usr/lib/python2.7/Cookie.py", line 583, in __init__
    if input: self.load(input)
  File "/usr/lib/python2.7/Cookie.py", line 643, in load
    for k, v in rawdata.items():

```

## Description

I am seeing this issue after an unattended-upgrade this morning. It was working last time this week I visited dailymotion. My os is debian.

/var/log/unattended-upgrades/unattended-upgrades-dpkg.log says:
Unpacking python-apt-common (1.4.1) over (1.4.0beta3) ...
Unpacking python3-apt (1.4.1) over (1.4.0beta3) ...
Unpacking python-apt (1.4.1) over (1.4.0~beta3) ...

This looks similar to https://github.com/ytdl-org/youtube-dl/issues/20673

**Comment by seahorse41** [comment]
Where is the open issue I should've posted at?

**Comment by seahorse41** [comment]
Still broken. Where is the open issue please?

**Comment by Surkal** [comment]
Upgrade to python 3.

**Comment by seahorse41** [comment]
Thank you! for replying,

$ alias python=python3
$ python --version
Python 3.5.3
$ youtube-dl -F https://www.dailymotion.com/video/x7r9v01
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 235, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 50, in _call_api
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 31, in _get_dailymotion_cookies
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2831, in _get_cookies
  File "/usr/lib/python2.7/Cookie.py", line 583, in __init__
    if input: self.load(input)
  File "/usr/lib/python2.7/Cookie.py", line 643, in load
    for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'

If I uninstall python2.7 it will break other programs expecting it. If python3 is required why doesn't youtube-dl specifically call for it?
Why is this only affecting dailymotion (that I know of)
Is this caused by the upgrade or did dailymotion change?
Is this a debian problem?
