### ISSUE TITLE
why was issue #23819 closed?  It is still a problem

### ISSUE THREAD

**Issue by sagcats** [ytdl-org/youtube-dl#23937]
https://github.com/ytdl-org/youtube-dl/issues/23819

**Comment by sagcats** [comment]
Script iniciado en 2020-02-01 23:48:35-07:00 [TERM="xterm" TTY="/dev/pts/2" COLUMNS="80" LINES="32"]

]0;stephen@trifid: ~/Music/tools/dlsstephen@trifid:~/Music/tools/dls$ ../grab-Chrome-videos.sh ../junk.htm
QsnZMee16lk
1  hash is QsnZMee16lk
downloading Bob Seger - Shame On The Moon
+ for x in $@
+ youtube-dl -x --verbose --audio-format mp3 --audio-quality 0 --no-playlist -o '%(title)s.%(ext)s' 'https://youtube.com/watch?v=QsnZMee16lk'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', '--verbose', '--audio-format', 'mp3', '--audio-quality', '0', '--no-playlist', '-o', '%(title)s.%(ext)s', 'https://youtube.com/watch?v=QsnZMee16lk']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.01
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-6-amd64-x86_64-with-debian-10.2
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] QsnZMee16lk: Downloading webpage
[youtube] QsnZMee16lk: Downloading video info webpage
[youtube] Downloading just video QsnZMee16lk because of --no-playlist
[youtube] {18} signature length 106, html5 player vfl1GpCbm
[youtube] QsnZMee16lk: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vfl1GpCbm/en_US/base.js
[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/youtube.py", line 1384, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/youtube.py", line 1297, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/youtube.py", line 1360, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '[1376500448,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '[1376500448,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
