### ISSUE TITLE
[tvnow.de] videos play in browser but don't work in youtube-dl

### ISSUE THREAD

**Issue by a1johnson** [ytdl-org/youtube-dl#23940]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.tvnow.de/serien/medical-detectives-1021/staffel-1/episode-1-mord-in-serie-2954171']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.7.2 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[TVNow] medical-detectives/mord-in-serie: Downloading JSON metadata
[TVNow] 2954171: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[TVNow] 2954171: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[TVNow] 2954171: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 403: Forbidden
[TVNow] 2954171: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 403: Forbidden
[TVNow] 2954171: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[TVNow] 2954171: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: Video 2954171 is DRM protected
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/tvnow.py", line 178, in _real_extract
    return self._extract_video(info, display_id)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/tvnow.py", line 72, in _extract_video
    'Video %s is DRM protected' % video_id, expected=True)
youtube_dl.utils.ExtractorError: Video 2954171 is DRM protected
```

## Description

The episodes play in the browser but give a DRM error in youtube-dl. This is different from videos that are premium only. Premium only videos are protected in the browser and when using youtube-dl. I use no login while using the browser and the video is accessible without an account or premium subscription.

**Comment by dstftw** [comment]
Does not play in browser.
![image](https://user-images.githubusercontent.com/1908898/73606654-440dcc80-45df-11ea-852e-b213dd745bd7.png)

**Comment by a1johnson** [comment]
<img width="1034" alt="screenshot" src="https://user-images.githubusercontent.com/40057661/73607670-5a089680-45b9-11ea-961d-6a1bf2158fac.png">

In my browser (Safari) the episode plays just fine.
