### ISSUE TITLE
7Plus downloads not working and reporting error "No video formats found"

### ISSUE THREAD

**Issue by ChrisGD-Melb** [ytdl-org/youtube-dl#23953]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[SysOps-iMac:~ chris$ youtube-dl -v https://7plus.com.au/my-greek-odyssey?episode-id=MYGO02-002
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://7plus.com.au/my-greek-odyssey?episode-id=MYGO02-002']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 2.7.16 (CPython) - Darwin-19.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2-tessus, ffprobe 4.2.2-tessus
[debug] Proxy map: {}
[7plus] MYGO02-002: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/sevenplus.py", line 61, in _real_extract
    info = self._parse_brightcove_metadata(media, episode_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 549, in _parse_brightcove_metadata
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

The error message below results when trying to download from 7Plus.
URL works when connected to 7plus.com.au 
https://7plus.com.au/my-greek-odyssey?episode-id=MYGO02-002
I'm not sure if the "?" in the URL is causing the issue

ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

MacYTDL Settings:
Download folder: 		/Users/chris/Downloads/MacYTDL/Downloads
youtube-dl version:	2020.01.24
FFmpeg version:		4.2.2
Python version:		2.7.16
Download file format:	Default
Audio only:			No
Description:			No
Download subtitles:	No
Remux download:		No remux
Write thumbnails:		No
Embed thumbnails	        No
Verbose feedback:	        Yes 
Add metadata:		No
Over-write existing:	No

**Comment by ChrisGD-Melb** [comment]
The program was working earlier, I have downloaded all of season 1 and season 2 episode 1 before this site resulted in above error message.
Just updated youtube-dl  (Your current version is 2020.02.16) with the same result.

youtube-dl --verbose https://7plus.com.au/my-greek-odyssey?episode-id=MYGO02-002
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://7plus.com.au/my-greek-odyssey?episode-id=MYGO02-002']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.02.16
[debug] Python version 2.7.16 (CPython) - Darwin-19.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2-tessus, ffprobe 4.2.2-tessus
[debug] Proxy map: {}
[7plus] MYGO02-002: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/sevenplus.py", line 61, in _real_extract
    info = self._parse_brightcove_metadata(media, episode_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 549, in _parse_brightcove_metadata
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
