### ISSUE TITLE
Dailymotion downloads are broken

### ISSUE THREAD

**Issue by dckjnls** [ytdl-org/youtube-dl#23971]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-C', u'https://www.dailymotion.com/video/x78i894', u'https://www.dailymotion.com/video/x78i895', u'https://www.dailymotion.com/video/x78i896', u'https://www.dailymotion.com/video/x76sh2m', u'https://www.dailymotion.com/video/x76sh2n', u'https://www.dailymotion.com/video/x76kq3k', u'https://www.dailymotion.com/video/x76kq3l', u'https://www.dailymotion.com/video/x76kq3m', u'https://www.dailymotion.com/video/x76fq7d', u'https://www.dailymotion.com/video/x76fq7e', u'https://www.dailymotion.com/video/x76fq7c', u'https://www.dailymotion.com/video/x7647mz', u'https://www.dailymotion.com/video/x7647mx', u'https://www.dailymotion.com/video/x7647my', u'https://www.dailymotion.com/video/x75lwfl', u'https://www.dailymotion.com/video/x75lwfk', u'https://www.dailymotion.com/video/x75lwfj', u'https://www.dailymotion.com/video/x756oxf', u'https://www.dailymotion.com/video/x756oxe', u'https://www.dailymotion.com/video/x756oxg', u'https://www.dailymotion.com/video/x74vw7q', u'https://www.dailymotion.com/video/x74vw7r', u'https://www.dailymotion.com/video/x74vw7p', u'https://www.dailymotion.com/video/x74o6ld', u'https://www.dailymotion.com/video/x74o6lf', u'https://www.dailymotion.com/video/x74o6le', u'https://www.dailymotion.com/video/x74i8l8', u'https://www.dailymotion.com/video/x74i8l9', u'https://www.dailymotion.com/video/x74i8la', u'https://www.dailymotion.com/video/x74e0lu', u'https://www.dailymotion.com/video/x74e0lv', u'https://www.dailymotion.com/video/x745hdd', u'https://www.dailymotion.com/video/x745hde', u'https://www.dailymotion.com/video/x745hdc', u'https://www.dailymotion.com/video/x73s2ks', u'https://www.dailymotion.com/video/x73s2kr', u'https://www.dailymotion.com/video/x73s2kt', u'https://www.dailymotion.com/video/x73if9j', u'https://www.dailymotion.com/video/x73if9i', u'https://www.dailymotion.com/video/x73if9h', u'https://www.dailymotion.com/video/x73f6wu', u'https://www.dailymotion.com/video/x73f6wv', u'https://www.dailymotion.com/video/x72opih', u'https://www.dailymotion.com/video/x72opig', u'https://www.dailymotion.com/video/x72opif', u'https://www.dailymotion.com/video/x72mbr9', u'https://www.dailymotion.com/video/x72mbr7', u'https://www.dailymotion.com/video/x72mbr8', u'https://www.dailymotion.com/video/x72k17b', u'https://www.dailymotion.com/video/x72k17a', u'https://www.dailymotion.com/video/x72k179', u'https://www.dailymotion.com/video/x72h97v', u'https://www.dailymotion.com/video/x72h97x', u'https://www.dailymotion.com/video/x72h97w', u'https://www.dailymotion.com/video/x72esw2', u'https://www.dailymotion.com/video/x72esw0', u'https://www.dailymotion.com/video/x72esw1', u'https://www.dailymotion.com/video/x722hg3', u'https://www.dailymotion.com/video/x722hg5', u'https://www.dailymotion.com/video/x722hg4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 2.7.16 (CPython) - Linux-5.0.0-29-generic-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Public IP address: 2003:d3:ff12:4334:74f0:c8ee:efe7:673f
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 235, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 50, in _call_api
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 31, in _get_dailymotion_cookies
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2831, in _get_cookies
  File "/usr/lib/python2.7/Cookie.py", line 583, in __init__
    if input: self.load(input)
  File "/usr/lib/python2.7/Cookie.py", line 643, in load
    for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'

```

## Description

When I'm trying to download videos from dailymotion it throws the upper mentioned error but if I try to download videos from youtube it works. This error is only happening since I've updated to 2020.01.24 (I don't know which version I was running before).

**Comment by TaktakTaktouk** [comment]
@dstftw Please when the Dailymotion will be fixed? we need it really
