### ISSUE TITLE
www.thegreatcoursesplus.com site support request.

### ISSUE THREAD

**Issue by cheedaTalli** [ytdl-org/youtube-dl#24016]
## Checklist

- [x ] I'm reporting a new site support request
- [x ] I've verified that I'm running youtube-dl version **2020.01.24**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that none of provided URLs violate any copyrights
- [x ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.thegreatcoursesplus.com/films/title/roosevelt-isolationism-and-lend-lease
- Single video: https://www.thegreatcoursesplus.com/films/title/the-battle-of-moscow-december-1941
- Playlist: https://www.thegreatcoursesplus.com/show/world_war_ii_battlefield_europe

## Description

I've got subscription of The Great Courses video courses and I want to download and copy them to my home NAS which I've connected to my TV. I tried using version 2020.1.24 but it doesn't work. I'm also attaching a the verbose output below.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-check-certificate', '--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', '-o', '%(playlist)s/%(chapter_number)s_%(chapter)s/%(playlist_index)s-%(title)s.%(ext)s', 'https://www.thegreatcoursesplus.com/show/world_war_ii_battlefield_europe']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.8.1 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[generic] world_war_ii_battlefield_europe: Requesting header
WARNING: Falling back on generic information extractor.
[generic] world_war_ii_battlefield_europe: Downloading webpage
[generic] world_war_ii_battlefield_europe: Extracting information
ERROR: Unsupported URL: https://www.thegreatcoursesplus.com/show/world_war_ii_battlefield_europe
Traceback (most recent call last):
  File "c:\users\win10\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\win10\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\users\win10\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\generic.py", line 3350, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.thegreatcoursesplus.com/show/world_war_ii_battlefield_europe

**Comment by cheedaTalli** [comment]
Let me know if you want me to arrange a trial account for your testing.

**Comment by cheedaTalli** [comment]
@dstftw  #14195 is stagnant since 2017 and new comments are blocked. What's the way out? Can you instead close that and let a new issue be taken care by a contributor?

**Comment by cheedaTalli** [comment]
@remitamine can you please close #14195 if you are unable to work on it?
