### ISSUE TITLE
Mixcloud issue

### ISSUE THREAD

**Issue by endquote** [ytdl-org/youtube-dl#24035]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v https://www.mixcloud.com/hospitalrecords/hospital-podcast-406-with-bop-x-subwave/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.mixcloud.com/hospitalrecords/hospital-podcast-406-with-bop-x-subwave/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 2.7.17 (CPython) - Darwin-19.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[mixcloud] hospitalrecords_hospital-podcast-406-with-bop-x-subwave: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mixcloud.py", line 137, in _real_extract
AttributeError: 'NoneType' object has no attribute 'get'
```

## Description

Mixcloud has generally been working fine for me, but I'm finding a few URLs with this error. Not sure what's unique about it.

**Comment by endquote** [comment]
On the site I see "sorry, this show is not available in your country", so... probably has to do with that.

**Comment by remitamine** [comment]
```
youtube-dl https://www.mixcloud.com/hospitalrecords/hospital-podcast-406-with-bop-x-subwave/
[mixcloud] hospitalrecords_hospital-podcast-406-with-bop-x-subwave: Downloading JSON metadata
[mixcloud] hospitalrecords_hospital-podcast-406-with-bop-x-subwave: Downloading m3u8 information
[mixcloud] hospitalrecords_hospital-podcast-406-with-bop-x-subwave: Downloading MPD manifest
[download] Destination: Hospital Podcast 406 with Bop x Subwave-hospitalrecords_hospital-podcast-406-with-bop-x-subwave.m4a
[download] 100% of 29.84MiB in 00:42
```

**Comment by endquote** [comment]
I'm in the US, but if I connect via a London-based VPN it works ok. So it would probably repro if you connect from the US.

I tried some of the `--geo-bypass` settings without luck.

It's fine, I'll just detect the crash in my program and move on.
