### ISSUE TITLE
Unable to access https://www.cbs.com/movies/star-trek-first-contact/iTGmLzm3gQN57pAqWamGAFpjatqCYgs_/

### ISSUE THREAD

**Issue by lonegeek** [ytdl-org/youtube-dl#24044]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.01.24**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by lonegeek** [comment]
[debug] Command-line args: [u'-v', u'https://www.cbs.com/movies/star-trek-first-contact/iTGmLzm3gQN57pAqWamGAFpjatqCYgs_/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[generic] iTGmLzm3gQN57pAqWamGAFpjatqCYgs_: Requesting header
WARNING: Falling back on generic information extractor.
[generic] iTGmLzm3gQN57pAqWamGAFpjatqCYgs_: Downloading webpage
[generic] iTGmLzm3gQN57pAqWamGAFpjatqCYgs_: Extracting information
ERROR: Unsupported URL: https://www.cbs.com/movies/star-trek-first-contact/iTGmLzm3gQN57pAqWamGAFpjatqCYgs_/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2375, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 3350, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.cbs.com/movies/star-trek-first-contact/iTGmLzm3gQN57pAqWamGAFpjatqCYgs_/

**Comment by dstftw** [comment]
You must provide account credentials.

**Comment by lonegeek** [comment]
I passed username and password via youtube-dl -u "username" and -p "password" with the same url and still receive the error message "URL not Supported"

**Comment by lonegeek** [comment]
I have a cbs allaccess account and I don't have the issue when downloading tv shows via youtube-dl
