### ISSUE TITLE
Broken Xtube Support - Failed to parse JSON

### ISSUE THREAD

**Issue by nolimit777** [ytdl-org/youtube-dl#24041]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.01.24**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\youtube-dl>youtube-dl -v http://www.xtube.com/profile/greenshowers-4056496
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.xtube.com/profile/greenshowers-4056496']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-93554-gce92ee4b4f, ffprobe N-93554-gce92ee4b4f
[debug] Proxy map: {}
[XTubeUser] greenshowers-4056496: Downloading videos JSON page 1
ERROR: greenshowers-4056496: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\xtube.py", line 164, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\common.py", line 892, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\common.py", line 876, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\common.py", line 903, in _parse_json
youtube_dl.utils.ExtractorError: greenshowers-4056496: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Xtube support is broken since several months (at least since early December), videos can't be downloaded at all (using profile URL like https://www.xtube.com/profile/greenshowers-4056496 or direct video URL like https://www.xtube.com/video-watch/renaissance-man-18992622).
Tried from different IP.
Xtube probably updated the site.
Would be nice if you could update youtube-dl parser for Xtube as well to download videos from a profile URL as before, youtube-dl is literally a wonderful time saver to grab them.
Thanks.

**Comment by affinityv** [comment]
Both of those links worked for me, but I am going through a proxy (sock5 Tor).  Perhaps there is some other blocking going on with your connection.

**Comment by nolimit777** [comment]
This is really strange, I'm confused by your answer.
I tested through 3 computers located in 3 different places with different IP/configuration (so 3 totally different connection).

You don't get a parse error and youtube-dl is parsing correctly all the pages and able to grab all the videos ?

**Comment by nolimit777** [comment]
@dstftw 
Can you give some details please ?
You don't get a parse error and you are able to download videos ?

**Comment by nolimit777** [comment]
@affinityv 
I did like you and tried through a similar proxy (SOCKS5 TOR) and... IT WORKS !
Can't believe that Xtube is someways blocking IP range of 3 majors ISP from France, that's simply crazy.
Many thanks for your hint, it have been months without success !

**Comment by affinityv** [comment]
@nolimit777 It might be the Internet police ;-)

It's a good change that Tor works and non-Tor is blocked!  Or at least, one method works.... none should be blocked.

**Comment by nolimit777** [comment]
@affinityv It's true, I'm totally guilty to use too much youtube-dl with Xtube ;-D

I wish nothing was blocked, but at least, like you said, something is working ! ^^
Thanks again for testing and the hint.

Did you also tried with a direct connection, does it work ?

**Comment by affinityv** [comment]
@nolimit777 Direct downloads worked too (including your two URLs), except for premium content, which, I expect, needs a login anyway regardless of network path used.
