### ISSUE TITLE
Twitch.tv broken for all videos.

### ISSUE THREAD

**Issue by marchom** [ytdl-org/youtube-dl#24043]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

On Windows:
```
> youtube-dl --version
2020.01.24
> ffmpeg -version
ffmpeg version git-2020-02-13-6d37ca8 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9.2.1 (GCC) 20200122
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
libavutil      56. 41.100 / 56. 41.100
libavcodec     58. 68.102 / 58. 68.102
libavformat    58. 38.100 / 58. 38.100
libavdevice    58.  9.103 / 58.  9.103
libavfilter     7. 75.100 /  7. 75.100
libswscale      5.  6.100 /  5.  6.100
libswresample   3.  6.100 /  3.  6.100
libpostproc    55.  6.100 / 55.  6.100
> youtube-dl -vf bestvideo+bestaudio https://www.twitch.tv/criticalrole
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vf', 'bestvideo+bestaudio', 'https://www.twitch.tv/criticalrole']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.8.1 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg git-2020-02-13-6d37ca8, ffprobe git-2020-02-13-6d37ca8
[debug] Proxy map: {}
[twitch:stream] criticalrole: Downloading stream JSON
[twitch:stream] criticalrole: Downloading channel access token
[twitch:stream] criticalrole: Downloading m3u8 information
ERROR: requested format not available
Traceback (most recent call last):
  File "c:\dev\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\dev\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 862, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "c:\dev\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 1634, in process_video_result
    raise ExtractorError('requested format not available',
youtube_dl.utils.ExtractorError: requested format not available
```
Linux:
```
$ youtube-dl --version
2020.01.24
$ ffmpeg -version
ffmpeg version N-51730-gf15007afa9-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 8 (Debian 8.3.0-6)
configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzimg
libavutil      56. 39.100 / 56. 39.100
libavcodec     58. 68.102 / 58. 68.102
libavformat    58. 38.100 / 58. 38.100
libavdevice    58.  9.103 / 58.  9.103
libavfilter     7. 75.100 /  7. 75.100
libswscale      5.  6.100 /  5.  6.100
libswresample   3.  6.100 /  3.  6.100
libpostproc    55.  6.100 / 55.  6.100
$ youtube-dl -vf bestvideo+bestaudio https://www.twitch.tv/criticalrole
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vf', 'bestvideo+bestaudio', 'https://www.twitch.tv/criticalrole']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.6.9 (CPython) - Linux-4.19.102-v8+-aarch64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg N-51730-gf15007afa9-static, ffprobe N-51730-gf15007afa9-static
[debug] Proxy map: {}
[twitch:stream] criticalrole: Downloading stream JSON
[twitch:stream] criticalrole: Downloading channel access token
[twitch:stream] criticalrole: Downloading m3u8 information
ERROR: requested format not available
Traceback (most recent call last):
  File "/home/marcho/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/marcho/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 862, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/marcho/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1635, in process_video_result
    expected=True)
youtube_dl.utils.ExtractorError: requested format not available
```

## Description

Errors trying to download any videos from twitch. Requested format not available. My guess is they changed the API.

If criticalrole is down, the issue is reproducible with any video on twitch..
 Eg. : https://www.twitch.tv/videos/549337847

**Comment by dstftw** [comment]
There are no formats satisfying `bestvideo+bestaudio` as clearly stated in the error message.

**Comment by marchom** [comment]
It might be helpful to return the requested format as part of the error message, so that it's clear it comes from the user and not from the site. Up to this ```bestvideo+bestaudio``` has always been available on twitch.tv. That confused me.

Thanks and sorry for the noise.

**Comment by dstftw** [comment]
FYI, `bestvideo` was never available on twitch.
