### ISSUE TITLE
LinuxAcademy - TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by patpicos** [ytdl-org/youtube-dl#24062]
## Checklist

- [X] I'm reporting a broken site support
- [X I've verified that I'm running youtube-dl version **2020.02.16**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

youtube-dl --version
2020.02.16

```
youtube-dl --cookies la.txt --verbose  http://linuxacademy.com/cp/modules/view/id/285 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--cookies', u'la.txt', u'--verbose', u'http://linuxacademy.com/cp/modules/view/id/285']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.02.16
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-39-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[LinuxAcademy] 285: Downloading webpage
[download] Downloading playlist: 285
[LinuxAcademy] playlist 285: Collected 24 video ids (downloading 24 of them)
[download] Downloading video 1 of 24
[LinuxAcademy] 3536-1: Downloading webpage
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2018, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1007, in process_ie_result
    extra_info=extra)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 869, in process_ie_result
    extra_info=extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/linuxacademy.py", line 165, in _real_extract
    webpage, item_id, require_title=False, m3u8_id='hls',)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 2657, in _extract_jwplayer_data
    jwplayer_data, video_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 2663, in _parse_jwplayer_data
    if 'playlist' not in jwplayer_data:
TypeError: argument of type 'NoneType' is not iterable
```

## Description

I am attempting to download one of the course from LinuxAcademy. I tried about a month ago w/o success. I tried again with the latest version and Im still getting the same errors. Looking at previous bug reports, looks like many comments were deleted, but no resolution

**Comment by patpicos** [comment]
Attempt using user/password combination
```
youtube-dl -u '******'-p '****' --verbose  http://linuxacademy.com/cp/modules/view/id/285 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--verbose', u'http://linuxacademy.com/cp/modules/view/id/285']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.02.16
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-39-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[LinuxAcademy] Downloading authorize page
[LinuxAcademy] Downloading login page
[LinuxAcademy] Downloading callback page
[LinuxAcademy] Downloading token validation page
[LinuxAcademy] 285: Downloading webpage
[download] Downloading playlist: 285
[LinuxAcademy] playlist 285: Collected 24 video ids (downloading 24 of them)
[download] Downloading video 1 of 24
[LinuxAcademy] 3536-1: Downloading webpage
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2018, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1007, in process_ie_result
    extra_info=extra)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 869, in process_ie_result
    extra_info=extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/linuxacademy.py", line 165, in _real_extract
    webpage, item_id, require_title=False, m3u8_id='hls',)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 2657, in _extract_jwplayer_data
    jwplayer_data, video_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 2663, in _parse_jwplayer_data
    if 'playlist' not in jwplayer_data:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by patpicos** [comment]
@dstftw please advise if there is a resolution for this or whether support for LA will not be available? none of the existing issues had resolutions and were closed.
