### ISSUE TITLE
ERROR: Signature extraction failed: Traceback

### ISSUE THREAD

**Issue by 3Dtechnics** [ytdl-org/youtube-dl#24070]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2020.02.16**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

20200217

Error as follows.    This was when downloading a series of training videos on youtube.   Half the videos (4 of 8) downloaded fine.   The other half (4 of 8) gave this error.    The URL syntax appears the same on all of the videos.     Tried this on 20200101 and 20200115 versions with same results.

j167 ~ # youtube-dl --verbose https://www.youtube.com/watch?v=KUxOnJWyMoM&list=PLck3bHtKT2CaTIovOLqXpIfj2KCXDUcuq&
index=4
[1] 3352
[2] 3353
j167 ~ # [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=KUxOnJWyMoM']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL env
ironment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ascii, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2020.01.15
[debug] Python version 3.6.9 (CPython) - Linux-4.19.97-gentoo-i686-Intel-R-_Core-TM-_i3-2100_CPU_@_3.10GHz-with-ge
ntoo-2.6
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[youtube] KUxOnJWyMoM: Downloading webpage
[youtube] KUxOnJWyMoM: Downloading video info webpage
[youtube] {18} signature length 101, html5 player vflp5fPn0
[youtube] KUxOnJWyMoM: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vflp5fPn0/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1384, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1297, in _extract_signature_functi
on
    cache_res = res(test_string)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1360, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '[1596180896,'; please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure 
to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '[1596180896,'; please report this issue on https://yt-dl.or
g/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to ca
ll youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt
-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure
 to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1384, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1297, in _extract_signature_functi
on
    cache_res = res(test_string)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1360, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '[1596180896,'; please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure 
to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1384, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1297, in _extract_signature_functi
on
    cache_res = res(test_string)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1360, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '[1596180896,'; please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure 
to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 2047, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1394, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1384, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1297, in _extract_signature_functi
on
    cache_res = res(test_string)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1360, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement    v = self.inte
rpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '[1596180896,'; please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure 
to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '[1596180896,'; please report this issue on https://yt-dl.or
g/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to ca
ll youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt
-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure
 to call youtube-dl with the --verbose flag and include its complete output.

Thanks!

**Comment by 3Dtechnics** [comment]
I should have said that I use gentoo linux, and the latest version of youtube-dl available is the 20200115 version in the package repo.
