### ISSUE TITLE
No status line received - the server has closed the connection

### ISSUE THREAD

**Issue by gokaybalci** [ytdl-org/youtube-dl#24083]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones
- [x] I've verified that I'm running youtube-dl version **2020.02.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
```
gokay@gokay-core:~$ youtube-dl -v -r 300k --playlist-items 59-139  --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s" https://www.youtube.com/playlist?list=PLKEPtx2hQJXUS0kyoUMQ6Z5Nj5wdgqoui
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-r', u'300k', u'--playlist-items', u'59-139', u'--extract-audio', u'--audio-format', u'mp3', u'-o', u'%(title)s.%(ext)s', u'https://www.youtube.com/playlist?list=PLKEPtx2hQJXUS0kyoUMQ6Z5Nj5wdgqoui']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.02.16
[debug] Python version 2.7.16 (CPython) - Linux-5.0.0-38-generic-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PLKEPtx2hQJXUS0kyoUMQ6Z5Nj5wdgqoui: Downloading webpage
[download] Downloading playlist: SONMEZ REIS 2019 2020 FULL KAYITLAR
[youtube:playlist] PLKEPtx2hQJXUS0kyoUMQ6Z5Nj5wdgqoui: Downloading page #1
[youtube:playlist] playlist SONMEZ REIS 2019 2020 FULL KAYITLAR: Downloading 81 videos
[download] Downloading video 1 of 81
[youtube] InT7wdyHNY4: Downloading webpage
[youtube] InT7wdyHNY4: Downloading embed webpage
[youtube] InT7wdyHNY4: Refetching age-gated info webpage
[youtube] InT7wdyHNY4: Downloading MPD manifest
[debug] Invoking downloader on u'https://manifest.googlevideo.com/api/manifest/dash/expire/1582060391/ei/B_9LXtb-Jdyz8gOSm4rgDA/ip/95.7.131.13/id/2274fbc1dc87358e/source/youtube/requiressl/yes/playback_host/r1---sn-nv47ln7s.googlevideo.com/mm/31%2C26/mn/sn-nv47ln7s%2Csn-h0jeenek/ms/au%2Conr/mv/m/mvi/0/pl/21/tx/23791946/txs/23791272%2C23791946/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/660000/vprv/1/mt/1582038704/fvip/1/keepalive/yes/fexp/23842630/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag/sig/ALgxI2wwRgIhAMBUvDSIdlg2NOezZikANlETvqgR3fuhgXNxgBju4JDXAiEAp8CVe9AjjviDsiWcljsNIjMxBuPjIzd3VIU_Dlb_g6M%3D/lsparams/playback_host%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AHylml4wRAIgAIzpYZLK_Q-Y0YFnLq8Kg5BaD1m4_ZjcESyKPEL2_nECIDQHdKxU7kt8auBIgvhQsoxJaa09nYaVLOGTeX9UO147'
[dashsegments] Total fragments: 50
[download] Destination: Sonmez Reis  KAYIT 46 KILLIATOR VE FULUTCULERE OZEL KOMIK SOHBET mudurıyet ASIDAYI.m4a
[download]   6.0% of ~5.15MiB at 299.23KiB/s ETA 00:32ERROR: unable to download video data: No status line received - the server has closed the connection
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1925, in process_info
    success = dl(filename, info_dict)
 File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1864, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/dash.py", line 48, in real_download
    success, frag_content = self._download_fragment(ctx, fragment_url, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/fragment.py", line 102, in _download_fragment
    'http_headers': headers or info_dict.get('http_headers'),
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2728, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1137, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 448, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 412, in _read_status
    raise BadStatusLine("No status line received - the server has closed the connection")
BadStatusLine: No status line received - the server has closed the connection

gokay@gokay-core:~$

```

## Description
I was downloading a playlist from YouTube with youtube-dl (2020.02.16), it successfully downloaded 58 videos but for the 59. video, the download speed decreased a lot and then youtube-dl stopped saying that the server has closed the connection. I searched the issues in here, there was only one guy complaining about this issue but it got closed because it is a duplicate post. However, I couldn't find the original post about this, search both resolved and unresolved cases. It this happening because YouTube banned me in a way?

**Comment by dstftw** [comment]
Most likely network error on either side.
