### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by atomar09** [ytdl-org/youtube-dl#24096]
Hi,

Here is the error trace, it was mentioned in the error trace to file a bug with this information:

ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    self.initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in initialize
    self._real_initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/udemy.py", line 172, in _real_initialize
    self._login()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/udemy.py", line 212, in _login
    raise ExtractorError('Unable to log in')

**Comment by atomar09** [comment]
Can you please at least add comments on why it was closed?
