### ISSUE TITLE
Cartoon network media_id error

### ISSUE THREAD

**Issue by g4m3r7ag** [ytdl-org/youtube-dl#24103]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2020.02.16**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
administrator@DL03:~$ sudo youtube-dl -U
[sudo] password for administrator: 
Updating to version 2020.02.16 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
administrator@DL03:~$ youtube-dl https://www.cartoonnetwork.com/video/ben-10/ben-in-rome-part-1-a-slice-of-life-episode.html
[CartoonNetwork] ben-in-rome-part-1-a-slice-of-life: Downloading webpage
ERROR: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
administrator@DL03:~$ sudo youtube-dl --verbose https://www.cartoonnetwork.com/video/ben-10/ben-in-rome-part-1-a-slice-of-life-episode.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.cartoonnetwork.com/video/ben-10/ben-in-rome-part-1-a-slice-of-life-episode.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.02.16
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-88-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[CartoonNetwork] ben-in-rome-part-1-a-slice-of-life: Downloading webpage
ERROR: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cartoonnetwork.py", line 36, in _real_extract
    media_id = find_field('mediaId', 'media id', 'id', '[0-9a-f]{40}', True)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cartoonnetwork.py", line 34, in find_field
    webpage, name, fatal=fatal)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Downloads from Cartoon Network are failing.

**Comment by darkhelmet2016** [comment]
Are the episodes in question free to download or require a subscription as any episode that has a lock on it will not work unless you have a cable log in but they do offer free to watch episodes for testing. https://www.cartoonnetwork.com/video/unlocked/index.html?atclk_vn=vn_link_unlocked

**Comment by g4m3r7ag** [comment]
I was under the impression it was unlocked because it played without logging in and also said unlocked at the top but apparently that was not the case as it's only playing a 2 minute teaser. I will try to login and sort it out on my end. Thank you.

**Comment by darkhelmet2016** [comment]
Checked on my end after logging in to my provider and was able to download it.
