### ISSUE TITLE
No video formats found on voyo.nova.cz

### ISSUE THREAD

**Issue by svob** [ytdl-org/youtube-dl#24114]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.02.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\phila>youtube-dl --verbose "https://nova-voyo-cz-usp.ssl.cdn.cra.cz/pre4mmWsCspM53OiftHBwA==,1582353425/2020/01/30/1668826/1668826.ism/1668826.mpd"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://nova-voyo-cz-usp.ssl.cdn.cra.cz/pre4mmWsCspM53OiftHBwA==,1582353425/2020/01/30/1668826/1668826.ism/1668826.mpd']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2020.02.16
[debug] Python version 2.7.14 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 1668826: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1668826: Downloading webpage
[generic] 1668826: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\generic.py", line 2397, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I have a problem with downloading a video from https://voyo.nova.cz/
Video from example is freely available on https://voyo.nova.cz/product/serialy/72083-ulice-3835-dil
I tried to use that address, `*.mpd` and `*/Manifest` address and every of them results in `ERROR: No video formats found`

**Comment by dstftw** [comment]
You must provide account credentials.
