### ISSUE TITLE
atv

### ISSUE THREAD

**Issue by avagraha** [ytdl-org/youtube-dl#24113]
## Checklist

- [ x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2020.02.16**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

C:\Users\andreaa>y -v --geo-bypass-country AT
https://www.atv.at/lugner-am-op
ernball-2019/opernball-2019/d2512785/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--geo-bypass-country', 'AT', 'https://ww
w.atv.at/lugner-am-opernball-2019/opernball-2019/d2512785/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.02.16
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6002-SP2
[debug] exe versions: ffmpeg N-94698-g83e0b71-Reino, ffprobe N-94698-g83e0b
71-Reino, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 77.118.188.157 (AT) as X-Forwarded-For.
[ATVAt] d2512785: Downloading webpage
[ATVAt] 2512830: Downloading m3u8 information
[ATVAt] 2513079: Downloading m3u8 information
[ATVAt] 2512788: Downloading m3u8 information
[ATVAt] 2512776: Downloading m3u8 information
[download] Downloading playlist: Opernball 2019
[ATVAt] playlist Opernball 2019: Collected 4 video ids (downloading 4 of th
em)
[download] Downloading video 1 of 4
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://blocked-multiscreen.atv.cdn.tvnext.
tv/2019/02/HD/6091570/6091570_layer0_5000000/6091570_index0.m3u8'
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpu
z77jgzq\build\youtube_dl\YoutubeDL.py", line 1925, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpu
z77jgzq\build\youtube_dl\YoutubeDL.py", line 1864, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpu
z77jgzq\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpu
z77jgzq\build\youtube_dl\downloader\hls.py", line 62, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpu
z77jgzq\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_respon
se
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain

  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_
default
urllib.error.HTTPError: HTTP Error 403: Forbidden

## Description

WRITE DESCRIPTION HERE

**Comment by avagraha** [comment]
why invalid???


  ----- Original Message -----
