### ISSUE TITLE
Possible email-related error?

### ISSUE THREAD

**Issue by rusemode** [ytdl-org/youtube-dl#24127]
## Checklist

- [ x] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.02.16**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\user\Downloads\youtube-dl>youtube-dl -v https://player.vimeo.com/video/
240868660 -u'xxxxxx' -p'xxxxxx'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://player.vimeo.com/video/240868660', "-
u'luu.pinkfloyd@gmail.com'", "-p'Temporal03'"]
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.02.16
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2020-02-18-ebee808, ffprobe git-2020-02-18-ebee
808
[debug] Proxy map: {}
[vimeo] Downloading login page
[vimeo] Logging in
ERROR: Unable to log in: bad username or password
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jg
zq\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jg
zq\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt
urllib.error.HTTPError: HTTP Error 418: I'm a teapot

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jg
zq\build\youtube_dl\extractor\vimeo.py", line 67, in _login
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jg
zq\build\youtube_dl\extractor\common.py", line 794, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jg
zq\build\youtube_dl\extractor\common.py", line 660, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jg
zq\build\youtube_dl\extractor\common.py", line 645, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 418: I'm
 a teapot (caused by HTTPError()); please report this issue on https://yt-dl.org
/bug . Make sure you are using the latest version; type  youtube-dl -U  to updat
e. Be sure to call youtube-dl with the --verbose flag and include its complete o
utput.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jg
zq\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jg
zq\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt
urllib.error.HTTPError: HTTP Error 418: I'm a teapot

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jg
zq\build\youtube_dl\extractor\vimeo.py", line 67, in _login
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jg
zq\build\youtube_dl\extractor\common.py", line 794, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jg
zq\build\youtube_dl\extractor\common.py", line 660, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jg
zq\build\youtube_dl\extractor\common.py", line 645, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 418: I'm
 a teapot (caused by HTTPError()); please report this issue on https://yt-dl.org
/bug . Make sure you are using the latest version; type  youtube-dl -U  to updat
e. Be sure to call youtube-dl with the --verbose flag and include its complete o
utput.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jg
zq\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jg
zq\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jg
zq\build\youtube_dl\extractor\common.py", line 433, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jg
zq\build\youtube_dl\extractor\vimeo.py", line 561, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jg
zq\build\youtube_dl\extractor\vimeo.py", line 73, in _login
youtube_dl.utils.ExtractorError: Unable to log in: bad username or password

```

## Description

I have seen more than 10 solutions to downloading vimeo on demand, but I cant even login, maybe because there is a dot (.) in the email? I have confirmed that the username and password work using the normal login, but as you can see it says bad -u -p any help? I can give you the credentials
YES I AM A NEWBORN WHEN IT COMES TO CODING but so far I hadnt had any issues using youtube-dl since you beautiful bastards have built it so smoothly.

**Comment by rusemode** [comment]
BTW this is a rented film, so I only gotz about 20 hours left

**Comment by dstftw** [comment]
Missing spaces before arguments.
