### ISSUE TITLE
Udemy log in not possible

### ISSUE THREAD

**Issue by xundeenergie** [ytdl-org/youtube-dl#24147]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2020.02.16**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -u my@email --verbose  -o '~/Videos/udemy/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s' https://www.udemy.com/course/programmieren-lernen-mit-java-ein-kurs-fur-einsteiger
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'--verbose', u'-o', u'~/Videos/udemy/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s', u'https://www.udemy.com/course/programmieren-lernen-mit-java-ein-kurs-fur-einsteiger']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.02.16
[debug] Git HEAD: bb6b47e
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-6-amd64-x86_64-with-debian-10.3
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, rtmpdump 2.4
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 529, in extract
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 433, in initialize
    self._real_initialize()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/udemy.py", line 172, in _real_initialize
    self._login()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/udemy.py", line 212, in _login
    raise ExtractorError('Unable to log in')
ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I tried only to download the course, if just watched in Firefox

**Comment by rgalang81** [comment]
Issue still exists in 2020.03.01 build

**Comment by ragavanrajan** [comment]
any update on this please

**Comment by edwinguerra** [comment]
same issue

**Comment by dirkf** [comment]
Continued in #29410.
