### ISSUE TITLE
Unable to download 144p or 240p vids from youtube, however i am able to watch 144p and 240p on youtube.

### ISSUE THREAD

**Issue by Coaggly** [ytdl-org/youtube-dl#24150]
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.02.16**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v -f 'best[height<=144]' https://www.youtube.com/watch?v=rjMoXP9x99A
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'best[height<=144]', u'https://www.youtube.com/watch?v=rjMoXP9x99A']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.02.16
[debug] Python version 2.7.16 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] rjMoXP9x99A: Downloading webpage
[youtube] rjMoXP9x99A: Downloading video info webpage
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 862, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1635, in process_video_result
    expected=True)
ExtractorError: requested format not available

```

## Description

On youtube, i can switch the  quality to 144p and 240p and the vid plays. On youtube dl, i get the error message above. Youtube-dl works for 360p.

**Comment by dstftw** [comment]
Read format selection on what does `best` mean.
