### ISSUE TITLE
Instagram  Unable to extract video url

### ISSUE THREAD

**Issue by tucomel** [ytdl-org/youtube-dl#24155]
## Checklist

- [ x] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2020.02.16**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
arthur@blackpower ~ % youtube-dl https://www.instagram.com/p/B9Bq5MLpJGELJ22zX1j0JkLmmFxwVUtGOZBkLw0/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.instagram.com/p/B9Bq5MLpJGELJ22zX1j0JkLmmFxwVUtGOZBkLw0/', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.02.16
[debug] Python version 2.7.16 (CPython) - Darwin-19.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[Instagram] B9Bq5MLpJGELJ22zX1j0JkLmmFxwVUtGOZBkLw0: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/instagram.py", line 195, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1123, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

arthur@blackpower ~ % 
```

## Description

Error when downloading video from instagram public links

**Comment by rishu1601** [comment]
- Hi I checked for the above url, it shows that the account is private

**Comment by rishu1601** [comment]
- Tried this and it worked 
```
 youtube-dl https://www.instagram.com/p/B8waiGXgLlD/
[Instagram] B8waiGXgLlD: Downloading webpage
[download] Destination: Video by instagram-B8waiGXgLlD.mp4
[download] 100% of 984.27KiB in 00:00
(base) Administrators-MacBook-Pro:~ rikuma$ youtube-dl https://www.instagram.com/p/B8waiGXgLlD/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.instagram.com/p/B8waiGXgLlD/', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.02.16
[debug] Python version 3.7.3 (CPython) - Darwin-19.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Instagram] B8waiGXgLlD: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://instagram.fblr11-1.fna.fbcdn.net/v/t50.2886-16/86847894_193244281742164_6965809955669184876_n.mp4?_nc_ht=instagram.fblr11-1.fna.fbcdn.net&_nc_cat=104&_nc_ohc=_uC5auplDrsAX9ynuBY&oe=5E5AC400&oh=4254f7bcf970dc4a7dc7829692c3404d'
[download] Video by instagram-B8waiGXgLlD.mp4 has already been downloaded
[download] 100% of 984.27KiB
```

**Comment by tucomel** [comment]
Whoa, you are right, I didn't realize that the link was private, thanks !
