### ISSUE TITLE
ExtractorError: No video formats found

### ISSUE THREAD

**Issue by Questor-2020** [ytdl-org/youtube-dl#24151]
Why do all the other videos submitted by this author download just fine w. youtube-dl, but this one alone does not.  It also plays fine in firefox, just wont download.

fran@fran-Satellite-L775:~$ youtube-dl https://www.bitchute.com/video/ywePKYY4KPU/
[BitChute] ywePKYY4KPU: Downloading webpage
[BitChute] ywePKYY4KPU: Checking video URL
[BitChute] ywePKYY4KPU: video URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
fran@fran-Satellite-L775:~$ youtube-dl --verbose https://www.bitchute.com/video/ywePKYY4KPU/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.bitchute.com/video/ywePKYY4KPU/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.02.16
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-72-generic-i686-with-LinuxMint-19.1-tessa
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[BitChute] ywePKYY4KPU: Downloading webpage
[BitChute] ywePKYY4KPU: Checking video URL
[BitChute] ywePKYY4KPU: video URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bitchute.py", line 66, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Questor-2020** [comment]
when do I close this issue, after I post it, to get it to publish, or after I get a satisfactory answer to the problem?

**Comment by Questor-2020** [comment]
Dear remitaminewhy did you close my ticket?If it was a dupe, could you at least link me to the original post that I am unknowingly "duping".   That might tell me if a solution is pending or if it has already been solved, and thus what the solution is.Francis K.


-------- Original Message --------
Subject: Re: [ytdl-org/youtube-dl] ExtractorError: No video formats
found (#24151)
