### ISSUE TITLE
PornHub video title missing for private videos

### ISSUE THREAD

**Issue by thisisbobsalmon** [ytdl-org/youtube-dl#24184]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.02.16**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v -i --cookies "/mnt/d/scripts/cookies.txt" https://www.pornhub.com/view_video.php?viewkey=ph5d7ca4e23a68e

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-i', '--cookies', '/mnt/d/scripts/cookies.txt', 'https://www.pornhub.com/view_video.php?viewkey=ph5d7ca4e23a68e']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.02.16
[debug] Python version 3.6.9 (CPython) - Linux-4.19.84-microsoft-standard-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[PornHub] ph5d7ca4e23a68e: Downloading pc webpage
[PornHub] ph5d7ca4e23a68e: Downloading m3u8 information
[PornHub] ph5d7ca4e23a68e: Downloading m3u8 information
[PornHub] ph5d7ca4e23a68e: Downloading m3u8 information
[PornHub] ph5d7ca4e23a68e: Downloading m3u8 information
[PornHub] ph5d7ca4e23a68e: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://dd1.phncdn.com/videos/201909/14/248305971/1080P_4000K_248305971.mp4?ttl=1582956514&ri=51200000&rs=400000&clientip=73.66.81.98&hash=f30f4e023a2adf59a884b86b998778c7'
[download] Destination:                         -ph5d7ca4e23a68e.mp4
[download] 100% of 27.35MiB in 00:01
```

## Description

Private videos downloaded from PornHub don't seem to be extracting the video name properly. It looks like the issues here (#23649 and #23694) are the same issue, but the video that user provided did not have an issue.

This private video should be good example as the user is very quick to accept a request (might even be automatic)

```
youtube-dl -v -i --cookies "/mnt/d/scripts/cookies.txt" https://www.pornhub.com/view_video.php?viewkey=ph5d7ca4e23a68e
```
For completeness, here's the output without authentication with the cookies

```
youtube-dl -v -i https://www.pornhub.com/view_video.php?viewkey=ph5d7ca4e23a68e
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-i', 'https://www.pornhub.com/view_video.php?viewkey=ph5d7ca4e23a68e']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.02.16
[debug] Python version 3.6.9 (CPython) - Linux-4.19.84-microsoft-standard-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[PornHub] ph5d7ca4e23a68e: Downloading pc webpage
ERROR: ph5d7ca4e23a68e: PornHub said: Sorry, but this video is private. You must be friends with FUCK-FUNK to view this video.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/pornhub.py", line 186, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: ph5d7ca4e23a68e: PornHub said: Sorry, but this video is private. You must be friends with FUCK-FUNK to view this video.
```

**Comment by dstftw** [comment]
You must provide account credentials.

**Comment by thisisbobsalmon** [comment]
Emailed cookies.txt to you, Sergey
