### ISSUE TITLE
[bitchute] ExtractorError when extracting audio

### ISSUE THREAD

**Issue by nj2534** [ytdl-org/youtube-dl#24197]
## Checklist

- [x] I'm reporting a broken site support

- [x] I've verified that I'm running youtube-dl version **2020.02.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
>youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 https://www.bitchute.com/video/MUDxJTLuXTss/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestaudio', '--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0', 'https://www.bitchute.com/video/MUDxJTLuXTss/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.02.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2019-12-19-99f505d, ffprobe git-2019-12-19-99f505d
[debug] Proxy map: {}
[BitChute] MUDxJTLuXTss: Downloading webpage
[BitChute] MUDxJTLuXTss: Checking video URL
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\YoutubeDL.py", line 807, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\YoutubeDL.py", line 862, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\YoutubeDL.py", line 1635, in process_video_result
youtube_dl.utils.ExtractorError: requested format not available
```

## Description

The video can be downloaded with `youtube-dl https://www.bitchute.com/video/MUDxJTLuXTss/`, and I had the same issue when trying to convert other bitchute videos to MP3.

**Comment by dstftw** [comment]
bitchute does not provide audio only formats.
