### ISSUE TITLE
Some YouTube video can't be downloaded without manifest

### ISSUE THREAD

**Issue by toorich** [ytdl-org/youtube-dl#24191]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.02.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PS C:\WINDOWS\system32> youtube-dl -f 137 https://www.youtube.com/watch?v=1lcm1M4CV6Y --youtube-skip-dash-manifest --ver
bose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '137', 'https://www.youtube.com/watch?v=1lcm1M4CV6Y', '--youtube-skip-dash-manifest', '--verbose']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dl version 2020.02.16
[debug] Python version 3.6.2 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: ffmpeg N-86994-g92da230
[debug] Proxy map: {'http': 'http://127.0.0.1:1081', 'https': 'https://127.0.0.1:1081', 'ftp': 'ftp://127.0.0.1:1081'}
[youtube] 1lcm1M4CV6Y: Downloading webpage
[youtube] 1lcm1M4CV6Y: Downloading video info webpage
[debug] Invoking downloader on 'https://r5---sn-p5qlsndk.googlevideo.com/videoplayback?expire=1583002854&ei=hmBaXvOsAsiJhwbBsZDoAw&ip=198.98.58.82&id=d65726d4ce0257a6&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=yt_otf&requiressl=yes&mm=31%2C26&mn=sn-p5qlsndk%2Csn-vgqsrnes&ms=au%2Conr&mv=m&mvi=4&pl=23&initcwndbps=96250&vprv=1&mime=video%2Fmp4&otf=1&otfp=1&dur=0.000&lmt=1455968812291948&mt=1582981171&fvip=5&keepalive=yes&fexp=23842630&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cotf%2Cotfp%2Cdur%2Clmt&sig=ADKhkGMwRQIhAICZqtXQRadTCzOQmIIyMGuV1HKm_sr3Kl2lNDeYhZrAAiBeLKaoEenAYsWFoeVskQGNGfpxXkdwHU-uY2GtCUSf0g%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABSNjpQwRQIgSdvs44FVO3pzUkztjdRyd7WGHxMnFC9ev1QT_ogc4aECIQDUCU_U2xO2KPAS4-24LJnSAqJYF4nkox0D8sM-auD5Gw%3D%3D&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "d:\program files\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 1925, in process_info
    success = dl(filename, info_dict)
  File "d:\program files\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 1864, in dl
    return fd.download(name, info)
  File "d:\program files\python\python36\lib\site-packages\youtube_dl\downloader\common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "d:\program files\python\python36\lib\site-packages\youtube_dl\downloader\http.py", line 341, in real_download
    establish_connection()
  File "d:\program files\python\python36\lib\site-packages\youtube_dl\downloader\http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "d:\program files\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "d:\program files\python\python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "d:\program files\python\python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\program files\python\python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "d:\program files\python\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "d:\program files\python\python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

## Description

It returned HTTP 404 error, and the problem seems to appear only in some specific formats.

**Comment by dstftw** [comment]
This is what they return. Blame Youtube for that.

**Comment by toorich** [comment]
> This is what they return. Blame Youtube for that.

So it isn't a bug? OK, I know. Thanks.
