### ISSUE TITLE
Site support request: audius.co

### ISSUE THREAD

**Issue by megascrapper** [ytdl-org/youtube-dl#24216]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.03.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single track: https://audius.co/laxcitymusic/delete-3337
- Artist page: https://audius.co/laxcitymusic
- Charts: https://audius.co/trending

## Description

Verbose log: 
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', 'https://audius.co/laxcitymusic/delete-3337']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[generic] delete-3337: Requesting header
WARNING: Falling back on generic information extractor.
[generic] delete-3337: Downloading webpage
[generic] delete-3337: Extracting information
ERROR: Unsupported URL: https://audius.co/laxcitymusic/delete-3337
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpavop71lg\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpavop71lg\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpavop71lg\build\youtube_dl\extractor\generic.py", line 3351, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://audius.co/laxcitymusic/delete-3337
```

**Comment by shirtjs** [comment]
It looks like most of the work required to download from Audius is already done at https://github.com/mrwnwttk/audius-dl.
