### ISSUE TITLE
Vimeo Password protected videos RegexNotFoundError 

### ISSUE THREAD

**Issue by someziggyman** [ytdl-org/youtube-dl#24224]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
./youtube-dl --verbose -F https://vimeo.com/showcase/6733390/video/389861851
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-F', u'https://vimeo.com/showcase/6733390/video/389861851']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.01
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo] 389861851: Downloading webpage
[vimeo] 389861851: Extracting information
ERROR: Unable to extract info section (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34minfo section\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/vimeo.py", line 656, in _real_extract
    flags=re.DOTALL)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/vimeo.py", line 670, in _real_extract
    cause=e)
ExtractorError: Unable to extract info section (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34minfo section\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Regular videos download just fine. Password protected are giving Regex error. Will DM a password to that video in case needed. Using the latest version of YT-dl with Python 2.7

**Comment by remitamine** [comment]
you did not pass the password to the command in the first place.

**Comment by someziggyman** [comment]
OK, my bad. Pasted the password with --video-password the log is pretty much the same. 

./youtube-dl --verbose --video-password XXXXX -F https://vimeo.com/showcase/6733390/video/389861851
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--video-password', u'PRIVATE', u'-F', u'https://vimeo.com/showcase/6733390/video/389861851']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.01
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo] 389861851: Downloading webpage
[vimeo] 389861851: Extracting information
ERROR: Unable to extract info section (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34minfo section\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/vimeo.py", line 656, in _real_extract
    flags=re.DOTALL)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/vimeo.py", line 670, in _real_extract
    cause=e)
ExtractorError: Unable to extract info section (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34minfo section\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by remitamine** [comment]
if the URL is not accessible to a developer, there is no way to fix the problem.

**Comment by someziggyman** [comment]
Where can I send you a password? It's not mine, so I can not share it for everyone to see.

**Comment by remitamine** [comment]
you can find my email address in my profile.

**Comment by someziggyman** [comment]
Sent. Thank you so much for everything you do and apologies for the confusion!

**Comment by someziggyman** [comment]
Will this fix be reimplemented into the next version of youtube-dl? Any specific reason, why has it been reverted? Just curious.

**Comment by remitamine** [comment]
it has caused a regression #24338, a proper fix would require more changes.

**Comment by yaci** [comment]
This issue ranks high in google for "youtube-dl vimeo showcase" phrase, so here's a workaround for those looking for a solution.

I managed to download password protected Vimeo videos by passing `XXXXXX_albumpassword` cookie to youtube-dl, where xxxxx is the id of Vimeo showcase (in the example provided by the OP it is 6733390 - the first number from the url). You need to get the value of the cookie by accessing Vimeo in your browser and copying the value from browser's dev tools.
Sticking to OP's example, the full command is:

youtube-dl --add-header 'Cookie: 6733390_albumpassword=PASTE.VALUE.HERE;' -F https://vimeo.com/showcase/6733390/video/389861851
