### ISSUE TITLE
NPR extractor failures

### ISSUE THREAD

**Issue by DragoonAethis** [ytdl-org/youtube-dl#24230]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl https://www.npr.org/2020/03/02/811280651/the-economic-lessons-of-a-free-solo-climb --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.npr.org/2020/03/02/811280651/the-economic-lessons-of-a-free-solo-climb', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.01
[debug] Python version 3.8.1 (CPython) - Linux-5.5.7-2-ck-skylake-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[Npr] 811280651: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('story')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
ie_result = self._real_extract(url)
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/npr.py", line 61, in _real_extract
story = self._download_json(
KeyError: 'story'
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
ie_result = self._real_extract(url)
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/npr.py", line 61, in _real_extract
story = self._download_json(
KeyError: 'story'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
ie_result = ie.extract(url)
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 543, in extract
raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('story')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure tocall youtube-dl with the --verbose flag and include its complete output.
```

## Description

Some NPR links fail to download with the log above. Example links:

- https://www.npr.org/2020/03/02/811280651/the-economic-lessons-of-a-free-solo-climb
- https://www.npr.org/2020/02/28/810546698/coronavirus-a-view-from-hong-kong
- https://www.npr.org/2020/02/26/809732454/the-rise-and-fall-and-rise-of-nascar

Downloads fail regardless of the download link availability on the NPR site.

**Comment by HussainMustafa** [comment]
hi
