### ISSUE TITLE
youtube_dl.utils.RegexNotFoundError: Unable to extract data (TikTok High-Bitrate Video Extraction Error)

### ISSUE THREAD

**Issue by Skylekko** [ytdl-org/youtube-dl#24236]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2020.03.01**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Tyler Economou>cd C:\youtube-dl

C:\youtube-dl>youtube-dl -g -v https://m.tiktok.com/v/6799635490321599750.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-g', '-v', 'https://m.tiktok.com/v/6799635490321599750.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg present, ffprobe present
[debug] Proxy map: {}
ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpavop71lg\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpavop71lg\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpavop71lg\build\youtube_dl\extractor\tiktok.py", line 101, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpavop71lg\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I Attempted to download a TikTok video using this Reddit post as a guide ( if I'm allowed to post links --> https://www.reddit.com/r/bonbibonkers/comments/alhn56/how_to_download_highbitrate_versions_from_tik_tok/ ) summarizing the Reddit post: to get a high-bitrate version of a TikTok video, the Tik Tok webpage URL needs to be figured out for the clip first, and apparently should appear as https//m.tiktok...etc format (mobile), otherwise youtube-dl uses the generic extraction, which contains the low-bitrate and watermark. 

I have tried the following before issuing the bug report:

- Tried different videos from TikTok
- Updated Python 
- Tried videos from YouTube

Downloading high-bitrate videos on YouTube worked.

I'm not sure if I'm missing any crucial details, so I apologize if I am, and I will provide any more information if necessary.

Thank you :)

- Tyler

**Comment by Skylekko** [comment]
I've been trying to search for this issue, but can only find similar issues that have been closed for being duplicates. I can't find an issue that has had any solutions or information regarding the problem. I searched issues regarding TikTok specifically, then I searched for the main error: youtube_dl.utils.RegexNotFoundError: Unable to extract data... The issues that contained this code, were closed for being duplicates. Ones that weren't, or were closed for other reasons, did not contain the "...Unable to extract data." 

Where do I go from here?
