### ISSUE TITLE
Unable to download DFXP subs

### ISSUE THREAD

**Issue by SwimmingLink** [ytdl-org/youtube-dl#24293]
## Checklist

- [x] I'm reporting a broken support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments do not have special characters
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/2137104/English/2137104_English_0b47ea98-123e-ea11-82a8-dd291e252010.vtt', 'https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/2137104/English/2137104_English_2347ea98-123e-ea11-82a8-dd291e252010.srt', 'https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/2137104/English/2137104_English_1947ea98-123e-ea11-82a8-dd291e252010.dfxp', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] 2137104_English_0b47ea98-123e-ea11-82a8-dd291e252010: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2137104_English_0b47ea98-123e-ea11-82a8-dd291e252010: Downloading webpage
WARNING: URL could be a direct video link, returning it as such.
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/2137104/English/2137104_English_0b47ea98-123e-ea11-82a8-dd291e252010.vtt'
[download] Destination: 2137104_English_0b47ea98-123e-ea11-82a8-dd291e252010-2137104_English_0b47ea98-123e-ea11-82a8-dd291e252010.vtt
[download] 100% of 28.95KiB in 00:00
[generic] 2137104_English_2347ea98-123e-ea11-82a8-dd291e252010: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2137104_English_2347ea98-123e-ea11-82a8-dd291e252010: Downloading webpage
WARNING: URL could be a direct video link, returning it as such.
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/2137104/English/2137104_English_2347ea98-123e-ea11-82a8-dd291e252010.srt'
[download] Destination: 2137104_English_2347ea98-123e-ea11-82a8-dd291e252010-2137104_English_2347ea98-123e-ea11-82a8-dd291e252010.srt
[download] 100% of 25.88KiB in 00:00
[generic] 2137104_English_1947ea98-123e-ea11-82a8-dd291e252010: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2137104_English_1947ea98-123e-ea11-82a8-dd291e252010: Downloading webpage
[generic] 2137104_English_1947ea98-123e-ea11-82a8-dd291e252010: Extracting information
ERROR: Unsupported URL: https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/2137104/English/2137104_English_1947ea98-123e-ea11-82a8-dd291e252010.dfxp
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\generic.py", line 3351, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/2137104/English/2137104_English_1947ea98-123e-ea11-82a8-dd291e252010.dfxp
```

## Description

DFXP subtitles (from Funimation) can't be grabbed even with a direct file link despite both VTT & SRT working fine the same way.

**Comment by dstftw** [comment]
You must provide funimation URL and use options to extract subtitles.
