### ISSUE TITLE
ERROR: Could not write header for output file

### ISSUE THREAD

**Issue by kannerke** [ytdl-org/youtube-dl#24308]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.vrt.be/vrtnu/a-z/de-eeuwige-oorlog/1/de-eeuwige-oorlog-a3-afghanistan/', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.08
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-174-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[VrtNU] de-eeuwige-oorlog-a3-afghanistan: Downloading webpage
WARNING: [VrtNU] de-eeuwige-oorlog-a3-afghanistan: Failed to parse JSON Invalid \escape: line 9 column 52 (char 212)
[VrtNU] de-eeuwige-oorlog-a3-afghanistan: Downloading JSON metadata
[Canvas] pbs-pub-81c57d06-8e37-4c73-a22b-d19bbc15333d$vid-94ae687a-759d-4dbb-8a26-ce8adb6156ec: Downloading asset JSON
[Canvas] pbs-pub-81c57d06-8e37-4c73-a22b-d19bbc15333d$vid-94ae687a-759d-4dbb-8a26-ce8adb6156ec: Downloading m3u8 information
[Canvas] pbs-pub-81c57d06-8e37-4c73-a22b-d19bbc15333d$vid-94ae687a-759d-4dbb-8a26-ce8adb6156ec: Downloading MPD manifest
WARNING: [Canvas] Unknown MIME type application/mp4 in DASH manifest
[Canvas] pbs-pub-81c57d06-8e37-4c73-a22b-d19bbc15333d$vid-94ae687a-759d-4dbb-8a26-ce8adb6156ec: Downloading ISM manifest
WARNING: [Canvas] AACH is not a supported codec
[Canvas] pbs-pub-81c57d06-8e37-4c73-a22b-d19bbc15333d$vid-94ae687a-759d-4dbb-8a26-ce8adb6156ec: Downloading f4m manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://remix-cf-vrt.akamaized.net/remix/a51d2376-7fa7-4fd5-8c1f-d2a51732fa21/remix.ism/.mpd'
[download] Afghanistan-pbs-pub-81c57d06-8e37-4c73-a22b-d19bbc15333d$vid-94ae687a-759d-4dbb-8a26-ce8adb6156ec.fMPEG_DASH-video=1989455.mp4 has already been downloaded
[download] 100% of 769.48MiB
[debug] Invoking downloader on u'https://remix-cf-vrt.akamaized.net/remix/a51d2376-7fa7-4fd5-8c1f-d2a51732fa21/remix.ism/.mpd'
[download] Afghanistan-pbs-pub-81c57d06-8e37-4c73-a22b-d19bbc15333d$vid-94ae687a-759d-4dbb-8a26-ce8adb6156ec.fMPEG_DASH-audio=96000.m4a has already been downloaded
[download] 100% of 38.04MiB
[ffmpeg] Merging formats into "Afghanistan-pbs-pub-81c57d06-8e37-4c73-a22b-d19bbc15333d$vid-94ae687a-759d-4dbb-8a26-ce8adb6156ec.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Afghanistan-pbs-pub-81c57d06-8e37-4c73-a22b-d19bbc15333d$vid-94ae687a-759d-4dbb-8a26-ce8adb6156ec.fMPEG_DASH-video=1989455.mp4' -i 'file:Afghanistan-pbs-pub-81c57d06-8e37-4c73-a22b-d19bbc15333d$vid-94ae687a-759d-4dbb-8a26-ce8adb6156ec.fMPEG_DASH-audio=96000.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:Afghanistan-pbs-pub-81c57d06-8e37-4c73-a22b-d19bbc15333d$vid-94ae687a-759d-4dbb-8a26-ce8adb6156ec.temp.mp4'
ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Traceback (most recent call last):
  File "../youtube-dl/youtube_dl/YoutubeDL.py", line 2065, in post_process
    files_to_delete, info = pp.run(info)
  File "../youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "../youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

```

## Description

95% of the other videos on this site merge without issues, but for this series 2 of the 3 videos don't merge with the audio. Only the first episode merges without issues.

**Comment by dstftw** [comment]
Outdated ffmpeg.

**Comment by kannerke** [comment]
Time to upgrade to Ubuntu 20.04 when it becomes available :-)
