### ISSUE TITLE
error download with verbose output

### ISSUE THREAD

**Issue by irfji** [ytdl-org/youtube-dl#24305]
youtube-dl -x https://youtu.be/lVf9ueCyx48 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', 'https://youtu.be/lVf9ueCyx48', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.7.5 (CPython) - Linux-5.3.0-40-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] lVf9ueCyx48: Downloading webpage
[youtube] lVf9ueCyx48: Downloading video info webpage
[youtube] {18} signature length 110, html5 player vfle4a9aa
[youtube] lVf9ueCyx48: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vfle4a9aa/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1380, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1293, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1356, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '[522481285,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '[522481285,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1380, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1293, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1356, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '[522481285,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1380, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1293, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1356, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '[522481285,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 2043, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1390, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1380, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1293, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1356, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '[522481285,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '[522481285,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by irfji** [comment]
youtube-dl -x https://youtu.be/lVf9ueCyx48 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', 'https://youtu.be/lVf9ueCyx48', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.7.4 (CPython) - Linux-5.3.0-40-generic-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] lVf9ueCyx48: Downloading webpage
[youtube] {18} signature length 110, html5 player vfle4a9aa
[youtube] {135} signature length 110, html5 player vfle4a9aa
[youtube] {244} signature length 106, html5 player vfle4a9aa
[youtube] {134} signature length 110, html5 player vfle4a9aa
[youtube] {243} signature length 110, html5 player vfle4a9aa
[youtube] {133} signature length 106, html5 player vfle4a9aa
[youtube] {242} signature length 106, html5 player vfle4a9aa
[youtube] {160} signature length 110, html5 player vfle4a9aa
[youtube] {278} signature length 110, html5 player vfle4a9aa
[youtube] {140} signature length 110, html5 player vfle4a9aa
[youtube] {249} signature length 110, html5 player vfle4a9aa
[youtube] {250} signature length 106, html5 player vfle4a9aa
[youtube] {251} signature length 110, html5 player vfle4a9aa
[debug] Invoking downloader on 'https://r3---sn-hpa7zned.googlevideo.com/videoplayback?expire=1583809970&ei=UrFmXr7XBZrsgAe3s57YBw&ip=79.143.112.251&id=o-ACATKpvg0J3yAAgYPa1Txdt0cYEPMck3ludnl3Giyg2A&itag=251&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-hpa7zned%2Csn-hpa7kn7z&ms=au%2Crdu&mv=m&mvi=2&pl=22&initcwndbps=763750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=2955745&dur=176.001&lmt=1540908683896870&mt=1583788269&fvip=3&keepalive=yes&fexp=23842630&c=WEB&txp=5411222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABSNjpQwRAIgL2Jol_RMPznWrCl9-OJ4pJSDp12nnW0UtKbG99Si0GECIGVTCGTVviA0b2a3d_LXjEdhAukBP409eBSFf9LoTVZO&sig=ADKhkGMwRQIgTf_yZ4iac_UMMVaXRpM2ZqXlK4qPcTngQLd9KCH_lkECIQDaycC8heR6KNZUpGiBvqspe3pWZ6-qak4JDIvnGJsGkQ==&ratebypass=yes'
ERROR: unable to open for writing: [Errno 13] Permission denied: 'pollon sigla completa-lVf9ueCyx48.webm.part'
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/downloader/http.py", line 250, in download
    ctx.tmpfilename, ctx.open_mode)
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 2046, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
PermissionError: [Errno 13] Permission denied: 'pollon sigla completa-lVf9ueCyx48.webm.part'

**Comment by irfji** [comment]
./youtube-dl -x https://youtu.be/lVf9ueCyx48
[youtube] lVf9ueCyx48: Downloading webpage
ERROR: unable to open for writing: [Errno 13] Permission denied: 'pollon sigla completa-lVf9ueCyx48.webm.part'
