### ISSUE TITLE
Age restricted youtube videos fail to download, HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by woopsoop382n** [ytdl-org/youtube-dl#24320]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
>youtube-dl -v ZGVgI1TTqo8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'ZGVgI1TTqo8']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-93103-gd20902fd23, ffprobe N-93103-gd20902fd23
[debug] Proxy map: {}
[youtube] ZGVgI1TTqo8: Downloading webpage
[youtube] ZGVgI1TTqo8: Downloading embed webpage
[youtube] ZGVgI1TTqo8: Refetching age-gated info webpage
[youtube] {18} signature length 105, html5 player vflset
[youtube] {22} signature length 105, html5 player vflset
[youtube] {136} signature length 105, html5 player vflset
[youtube] {247} signature length 105, html5 player vflset
[youtube] {398} signature length 101, html5 player vflset
[youtube] {135} signature length 105, html5 player vflset
[youtube] {244} signature length 105, html5 player vflset
[youtube] {397} signature length 101, html5 player vflset
[youtube] {134} signature length 101, html5 player vflset
[youtube] {243} signature length 105, html5 player vflset
[youtube] {396} signature length 105, html5 player vflset
[youtube] {133} signature length 105, html5 player vflset
[youtube] {242} signature length 101, html5 player vflset
[youtube] {395} signature length 105, html5 player vflset
[youtube] {160} signature length 105, html5 player vflset
[youtube] {278} signature length 105, html5 player vflset
[youtube] {394} signature length 105, html5 player vflset
[youtube] {140} signature length 105, html5 player vflset
[youtube] {249} signature length 105, html5 player vflset
[youtube] {250} signature length 105, html5 player vflset
[youtube] {251} signature length 101, html5 player vflset
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r6---sn-gvnuxaxjvh-3046.googlevideo.com/videoplayback?expire=1583931029&ei=NYpoXqiEMIzFyAWs1pK4Bw&ip=80.234.24.183&id=o-AOdGeSCWAX9WZWZiDiMOVl-QA_TqlSM-MIdHAzM9W6Vn&itag=136&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C394%2C395%2C396%2C397%2C398&source=youtube&requiressl=yes&mh=m6&mm=31%2C29&mn=sn-gvnuxaxjvh-3046%2Csn-gvnuxaxjvh-bvwz&ms=au%2Crdu&mv=m&mvi=5&pl=17&gcr=ru&initcwndbps=1065000&vprv=1&mime=video%2Fmp4&gir=yes&clen=8986829&dur=219.510&lmt=1582070895202141&mt=1583909366&fvip=6&keepalive=yes&fexp=23842630&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABSNjpQwRgIhAP2IHl0MCtO_n-rGo6KTvxn9A4g2pDYdR0ByXWnD4EtVAiEAyXcwm3scIIJ9SDSp8gGu6hot87coO0ClVDL07ZHFB10%3D&sig=ChkGMwRQIgW1aBu9SGK2x5XWCRxmXeotls-7fJVtm6jSA872YMkjMKIQD4AgAATZ2Bxpl2Cr1Mm0bf8n=BRlEk1xfXkpC8Uopoa&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 1920, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

## Description

Age restricted youtube videos fail to download now. I wonder if it's a regional thing, I'm in russia.

**Comment by dstftw** [comment]
You must authenticate for age-gated videos.

**Comment by aearil** [comment]
Actually, it seems age-gated videos are accessible via youtube embed links. Could youtube-dl use this to allow downloading without logging in ?

**Comment by dstftw** [comment]
Again: age-gated videos are no longer accessed without logging in.

**Comment by mpfaff** [comment]
@dstftw that isn't true. I use the Boost for Reddit app, and it uses an embedded YouTube player, which can be used to watch age restricted videos without logging in.
