### ISSUE TITLE
[CCMA] Videos with several subtitles won't download

### ISSUE THREAD

**Issue by guillemglez** [ytdl-org/youtube-dl#24347]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.03.08**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.ccma.cat/tv3/alacarta/crims/crims-mataiaies/video/6033780/', u'-v', u'2']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2020.03.08
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[CCMA] 6033780: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2019, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ccma.py", line 82, in _real_extract
AttributeError: 'list' object has no attribute 'get'
```

## Description

When a video contains more than one subtitles' file, the program crashes.
This is addressed in #24157.

**Comment by felisucoibi** [comment]
i confir happens to me too

**Comment by guillemglez** [comment]
This is still happening and pretty annoying since it completely blocks downloading for the site while a fix has already been proposed... Any chances of reviewing/merging it for the upcoming release? @dstftw
