### ISSUE TITLE
PornhubPremium Unable to extract title

### ISSUE THREAD

**Issue by kasslover530** [ytdl-org/youtube-dl#24343]
Trying this out on a pornhubpremium website and cannot download due to title extraction error.
Note that on pornhub it works, just not premium.

```
youtube-dl -v --cookies "cookies.txt" "https://www.pornhubpremium.com/view_video.php?viewkey=1342824528"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'cookies.txt', 'https://www.pornhubpremium.com/view_video.php?viewkey=1342824528']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[PornHub] 1342824528: Downloading pc webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\pornhub.py", line 206, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 1014, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

I found quite a few issues regarding 'Unable to extract title'. I was wondering if there could be a flag to skip that check/ ignore that error.

Thanks.

**Comment by dstftw** [comment]
You must provide account credentials.

**Comment by kasslover530** [comment]
I provided --username, and it asked my password interactively. I then put my PW and that error came out again. 

youtube_dl.utils.RegexNotFoundError: Unable to extract title;

**Comment by dstftw** [comment]
You must provide account credentials **to the developer**.

**Comment by bfr1** [comment]
hi and sorry for the trouble, having same issue

**Comment by Nottt** [comment]
Any news on this? Anyone can signup for a free trial nowadays

**Comment by myqueue** [comment]
> You must provide account credentials **to the developer**.

How does one do this?
