### ISSUE TITLE
Some YT links have stopped working with version 2020.03.08

### ISSUE THREAD

**Issue by bitshifter52** [ytdl-org/youtube-dl#24361]
## Checklist

- [Y ] I'm reporting a broken site support
- [Y ] I've verified that I'm running youtube-dl version **2020.03.08**
- [Y ] I've checked that all provided URLs are alive and playable in a browser
- [Y ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [Y ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
youtube-dl -v --ignore-config https://www.youtube.com/watch?v=EoooPBECtco
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--ignore-config', u'https://www.youtube.com/watch?v=EoooPBECtco']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.08
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-40-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.1.3-0ppa1, ffprobe 4.1.3-0ppa1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] EoooPBECtco: Downloading webpage
[youtube] EoooPBECtco: Downloading embed webpage
[youtube] EoooPBECtco: Refetching age-gated info webpage
[youtube] {18} signature length 106, html5 player vflset
[youtube] {135} signature length 106, html5 player vflset
[youtube] {244} signature length 106, html5 player vflset
[youtube] {134} signature length 106, html5 player vflset
[youtube] {243} signature length 106, html5 player vflset
[youtube] {133} signature length 106, html5 player vflset
[youtube] {242} signature length 106, html5 player vflset
[youtube] {160} signature length 106, html5 player vflset
[youtube] {278} signature length 106, html5 player vflset
[youtube] {140} signature length 106, html5 player vflset
[youtube] {249} signature length 106, html5 player vflset
[youtube] {250} signature length 106, html5 player vflset
[youtube] {251} signature length 106, html5 player vflset
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r2---sn-q4fl6nss.googlevideo.com/videoplayback?expire=1584312344&ei=uFtuXqW7EcOTDYqEg-AG&ip=173.239.232.30&id=o-ALkPx179QgTJrXg77bt5rcW9Q6k6FntNyzao1d2jwDg3&itag=244&aitags=133%2C134%2C135%2C160%2C242%2C243%2C244%2C278&source=youtube&requiressl=yes&mh=vC&mm=31%2C26&mn=sn-q4fl6nss%2Csn-vgqsener&ms=au%2Conr&mv=m&mvi=1&pl=24&initcwndbps=832500&vprv=1&mime=video%2Fwebm&gir=yes&clen=4137508&dur=251.240&lmt=1542004022650562&mt=1584290684&fvip=2&keepalive=yes&fexp=23842630%2C23882513&c=WEB&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABSNjpQwRQIgNiaG9Oo0BbJfhpb3BhVhz1si1y9esARsbx0Zp0TbS7YCIQDzGxGiKq0-avxMeQ1QWKHxa4Ly0CoAKL5uO-l6agCMFA%3D%3D&sig==FqiUknYndGoh9lbgdix0OPBAs5YkVcP30_TcXjgNrAEiAcz5yeMAzXHuN92qVksw15q31jnZiolOyagEgI8GfOP7AhIgRwMGkhKDADL&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden


```

## Description

WRITE DESCRIPTION HERE
It appears that something with either youtube.com or youtube-dl has stopped working as expected. Anyway, thank you for looking at this.

**Comment by SolidTux** [comment]
I can confirm that the same happens for me under Fedora 31 with youtube-dl 2020.03.08.

**Comment by dstftw** [comment]
You must authenticate for age-gated videos.

**Comment by kardoqadir** [comment]
I have the same issue and fixed by running  
```
youtube-dl --rm-cache-dir URL
```
