### ISSUE TITLE
Medialaan.py: IndexError: list index out of range

### ISSUE THREAD

**Issue by Jomme5** [ytdl-org/youtube-dl#24364]
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--output', 'D:\\Muziek\\Youtube_other\\download\\%(title)s.%(ext)s', 'https://vtm.be/vtmgo/afspelen/ecdd91b8e-18b3-458d-8ba5-317afb183187', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-71262-g511585c, ffprobe N-71262-g511585c
[debug] Proxy map: {}
[Medialaan] ecdd91b8e-18b3-458d-8ba5-317afb183187: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\medialaan.py", line 169, in _real_extract
IndexError: list index out of range
```

## Description
Extractor is 2 years old and propably not updated.
Current VTM-video-site works now with a Microsoft PlayReady manfest mpd- with cenc/dash-encryption. No idea if this is compatible with youtube-dl or if y-dl can handle this kind of manifests. 

I also tried the link `<BaseURL>` from within the manifest.mpd directly with youtube-dl, but no succes either

**Comment by dstftw** [comment]
You must provide account credentials.

**Comment by Jomme5** [comment]
Did the same with --username & --password. Exact same result. 
Can youtube-dl handle DRM with PlayReady/cenc:pssh/mspr:pro manifests?

thx
