### ISSUE TITLE
Hotstar videos are not getting downloaded.

### ISSUE THREAD

**Issue by don252** [ytdl-org/youtube-dl#24380]
It was working few weeks back . Now it is not working.

youtube-dl -v https://www.hotstar.com/us/tv/yeh-rishtey-hain-pyaar-ke/s-1826/kunal-apologises-to-meenakshi/1000249007
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.hotstar.com/us/tv/yeh-rishtey-hain-pyaar-ke/s-1826/kunal-apologises-to-meenakshi/1000249007']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {'https': 'https://127.0.0.1:55438', 'socks': 'socks://127.0.0.1:55437', 'http': 'http://127.0.0.1:55438'}
[hotstar] 1000249007: Downloading webpage
[hotstar] 1000249007: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 475: Unknown (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**All episodes are also not getting downloaded . It is returning "Unsupported URL " . In the past I had downloaded all episodes form this site . Now it is not working**

youtube-dl -v https://www.hotstar.com/us/tv/yeh-rishtey-hain/s-1826/list/episodes/t-1_2_1826
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.hotstar.com/us/tv/yeh-rishtey-hain/s-1826/list/episodes/t-1_2_1826']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {'https': 'https://127.0.0.1:55438', 'http': 'http://127.0.0.1:55438', 'socks': 'socks://127.0.0.1:55437'}
[generic] t-1_2_1826: Requesting header
WARNING: Falling back on generic information extractor.
[generic] t-1_2_1826: Downloading webpage
[generic] t-1_2_1826: Extracting information
ERROR: Unsupported URL: https://www.hotstar.com/us/tv/yeh-rishtey-hain/s-1826/list/episodes/t-1_2_1826
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\generic.py", line 3351, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.hotstar.com/us/tv/yeh-rishtey-hain/s-1826/list/episodes/t-1_2_1826

**Comment by dstftw** [comment]
Most likely proxy is banned.

**Comment by don252** [comment]
> 
> 
> Most likely proxy is banned.

@dstftw The link is playing on my  browser.

**Comment by MLGMAG** [comment]
It is possible to download streams from Indian hotstar.
You should consider to use Indian proxy (not Amazon, will get 403) (better residential one) and use user-agent like in browser.
You will get 475 error if something is wrong with proxy (it is not Indian proxy, it is banned or something else...)

> The link is playing on my browser.

@don252 have you tried to use the user-agent from the browser?
It helps me to download the stream.

You can check my investigation, if it is still relevant for you (it is done with help of  `curl`):
https://gist.github.com/MLGMAG/5247a837663203ac9193ab56a58d238b
