### ISSUE TITLE
403 (Forbidden) on Soundcloud

### ISSUE THREAD

**Issue by buzo-ffm** [ytdl-org/youtube-dl#24394]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl --verbose 'https://soundcloud.com/kaiserdisco/kd-music-radio-show-078?in=kaiserdisco/sets/kd-music-radio'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://soundcloud.com/kaiserdisco/kd-music-radio-show-078?in=kaiserdisco/sets/kd-music-radio']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.8.2 (CPython) - Linux-5.5.9-arch1-2-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] kaiserdisco/kd-music-radio-show-078: Downloading info JSON
[soundcloud] 707143777: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[soundcloud] 707143777: Downloading JSON metadata
[soundcloud] 707143777: Downloading JSON metadata
[soundcloud] 707143777: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://api.soundcloud.com/tracks/707143777/download?client_id=F2xyJN5cBsPtVnnj3fHhK6uPbEPaBbjU'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

## Description

See verbose log

**Comment by 0xpr03** [comment]
I'm experiencing the same here on public available links like [this](https://soundcloud.com/rocketbeanstv/plauschangriff-anime-serien-im?in=rocketbeanstv/sets/plauschangriff)
@remitamine any reason for this to be "account-needed" ?

**Comment by buzo-ffm** [comment]
FWIW, I tried `--cookies cookies-from-logged-inbrowser.txt` and `--user-agent` _"my browser's user agent"_, without any change.

**Comment by nikit0zzz** [comment]
> 
> 
> FWIW, I tried `--cookies cookies-from-logged-inbrowser.txt` and `--user-agent` _"my browser's user agent"_, without any change.

I tried it, does not work

**Comment by radusuciu** [comment]
It seems that client_ids obtained from the browser are not working with the API.

**Comment by remitamine** [comment]
> @remitamine any reason for this to be "account-needed"?

because the issue is related to the download URL, and downloading in the browser requires an account(checking browser traffic is needed to fix the issue).

**Comment by grr** [comment]
soundcloud locked down what the website client_id is allowed to do. and they also no longer allow you to register for new apps so you can't get a new client_id. but if you have an existing client_id (or find one through github source search) you can get it to work by using that.
