### ISSUE TITLE
403 Forbidden on single youtube video

### ISSUE THREAD

**Issue by dzek69** [ytdl-org/youtube-dl#24401]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

I have found some topics about the same issue, but all of them seems outdated: in example: https://github.com/ytdl-org/youtube-dl/issues/6451

## Verbose log

```
dzek@dzek-pc:/mnt/d/Temp/Youtube$ youtube-dl "http://www.youtube.com/watch?v=6vQyUNivi58" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.youtube.com/watch?v=6vQyUNivi58', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.08
[debug] Python version 2.7.16 (CPython) - Linux-4.4.0-18362-Microsoft-x86_64-with-debian-10.0
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1
[debug] Proxy map: {}
[youtube] 6vQyUNivi58: Downloading webpage
[youtube] 6vQyUNivi58: Downloading embed webpage
[youtube] 6vQyUNivi58: Refetching age-gated info webpage
[youtube] {18} signature length 107, html5 player vflset
[youtube] {22} signature length 103, html5 player vflset
[youtube] {271} signature length 107, html5 player vflset
[youtube] {137} signature length 107, html5 player vflset
[youtube] {248} signature length 107, html5 player vflset
[youtube] {136} signature length 107, html5 player vflset
[youtube] {247} signature length 107, html5 player vflset
[youtube] {135} signature length 107, html5 player vflset
[youtube] {244} signature length 107, html5 player vflset
[youtube] {134} signature length 103, html5 player vflset
[youtube] {243} signature length 103, html5 player vflset
[youtube] {133} signature length 107, html5 player vflset
[youtube] {242} signature length 103, html5 player vflset
[youtube] {160} signature length 107, html5 player vflset
[youtube] {278} signature length 103, html5 player vflset
[youtube] {140} signature length 107, html5 player vflset
[youtube] {249} signature length 107, html5 player vflset
[youtube] {250} signature length 107, html5 player vflset
[youtube] {251} signature length 107, html5 player vflset
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r3---sn-vnuoxu-g1xe.googlevideo.com/videoplayback?expire=1584633054&ei=fkBzXqOeA5W-yQX8mYPwCw&ip=62.133.141.242&id=o-APvSmoocGwrD6l37SXXmv7FIFNA2HaJrUiHRVz_0Tvgr&itag=271&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278&source=youtube&requiressl=yes&mh=mD&mm=31%2C29&mn=sn-vnuoxu-g1xe%2Csn-f5f7lnee&ms=au%2Crdu&mv=m&mvi=2&pl=19&initcwndbps=1256250&vprv=1&mime=video%2Fwebm&gir=yes&clen=68288964&dur=79.999&lmt=1584574948150566&mt=1584611329&fvip=3&keepalive=yes&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABSNjpQwRAIgHt3rJBrUo0fILOYwxfQKliFh3iik-mFz_3DXiLAQKRQCIGPDUMl81GF_8UEYnkTjoxlb_AlZW3Cxrm1eggN8uUXT&sig==43jtxwrx9dzPI3weAxBwQxbVgbVEzi-UzYLsHCrlkHlAEiAOg-bLCZ=J5_DbKZNl2JlLjD_aG2vcHp1WJCoqe9aAxNAhIgRwMGk&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

## Description

Single YouTube video gives me 403. As stated before - it works just fine in the browser.
The issue happens on:
- Windows exe version,
- Linux version within WSL,
- real Linux machine

I tried changing my IP with VPN (normally not used, I'm on clean machine) in case of some kind of ban from Google for intensive download for example (but I'm not doing any intensive downloads anyway) - no luck.

Other videos than `http://www.youtube.com/watch?v=6vQyUNivi58` seems to work just fine. This is the only video I found having troubles downloading.

**Comment by dstftw** [comment]
You must authenticate.

**Comment by dzek69** [comment]
@dstftw sorry, i did not expected that (would be nice to get this info more clear)

Still - i've tried authenticating and i'm getting 400 Bad Request during login then I'm getting the same 403 error

I'm logging in into account without any 2FA.
I've tried passing just username and password via command line arguments and via `.netrc` file - both giving the same result
Logging in into that account from another browser seems to pass without any problem so it's not a problem with credentials
I don't have any "special" chars in both of my login and password.

`-v` gives nothing useful about logging in

Any suggestions?
