### ISSUE TITLE
HTTP Error 404: Not Found error with mastersofscale.com podcast

### ISSUE THREAD

**Issue by eadixian** [ytdl-org/youtube-dl#24405]
Date: Thu, 19 Mar 2020 14:38:09 PDT

Hello,

When attempting a youtube-dl (version 2020.03.08) on the "(>)" (play) button link:
        https://mastersofscale.com/barry-diller-infinite-learner/6b514a79-1119-4173-8e68-2442ee46fea4
on web page:
        https://mastersofscale.com/barry-diller-infinite-learner/
, I get "HTTP Error 404: Not Found". Yet when I click that link, the browser brings up an embedded player and plays the podcast just fine. (I don't know what kind of embedded player it is.)

I'm including the full "youtube-dl -v" debug output below.

(When I attempt a youtube-dl on the web page itself [2nd URL above], I get "ERROR: Unsupported URL". I'm including debug output of that, as well, below.)

Thank you!
Eric D.

--------CUT HERE--------BEGIN DEBUG OUTPUT 1 of 2--------

```
% youtube-dl -v https://mastersofscale.com/barry-diller-infinite-learner/6b514a79-1119-4173-8e68-2442ee46fea4 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://mastersofscale.com/barry-diller-infinite-learner/6b514a79-1119-4173-8e68-2442ee46fea4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.08
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-12-amd64-x86_64-with-debian-9
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1
[debug] Proxy map: {}
[generic] 6b514a79-1119-4173-8e68-2442ee46fea4: Requesting header
WARNING: Could not send HEAD request to https://mastersofscale.com/barry-diller-infinite-learner/6b514a79-1119-4173-8e68-2442ee46fea4: HTTP Error 404: Not Found
[generic] 6b514a79-1119-4173-8e68-2442ee46fea4: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/ead/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/ead/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

% 
```

--------CUT HERE--------END DEBUG OUTPUT 1 OF 2--------

--------CUT HERE--------BEGIN DEBUG OUTPUT 2 OF 2--------

```
% youtube-dl -v https://mastersofscale.com/barry-diller-infinite-learner/                       
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://mastersofscale.com/barry-diller-infinite-learner/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.08
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-12-amd64-x86_64-with-debian-9
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1
[debug] Proxy map: {}
[generic] barry-diller-infinite-learner: Requesting header
WARNING: Falling back on generic information extractor.
[generic] barry-diller-infinite-learner: Downloading webpage
[generic] barry-diller-infinite-learner: Extracting information
ERROR: Unsupported URL: https://mastersofscale.com/barry-diller-infinite-learner/
Traceback (most recent call last):
  File "/home/ead/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2375, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/home/ead/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/home/ead/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 4, column 40
Traceback (most recent call last):
  File "/home/ead/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/ead/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/ead/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3351, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://mastersofscale.com/barry-diller-infinite-learner/

%
```

--------CUT HERE--------END DEBUG OUTPUT 2 OF 2--------

EOF

**Comment by shadinaif** [comment]
Looks like the website isn't supported. See list here https://ytdl-org.github.io/youtube-dl/supportedsites.html
