### ISSUE TITLE
youtube download error

### ISSUE THREAD

**Issue by asimhassan28** [ytdl-org/youtube-dl#24400]
F:\cp>F:\ffmpeg-4.2.1-win64-static\ffmpeg-4.2.1-win64-static\bin\youtube-dl.exe --verbose -f 18 "https://www.youtube.com/watch?v=yr4izp00DW0"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', '18', 'https://www.youtube.com/watch?v=yr4izp00DW0']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.01.01
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[youtube] yr4izp00DW0: Downloading webpage
[youtube] yr4izp00DW0: Downloading video info webpage
[youtube] {18} signature length 107, html5 player vfl7QQYEK
[youtube] yr4izp00DW0: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vfl7QQYEK/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\youtube.py", line 1384, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\youtube.py", line 1297, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\youtube.py", line 1360, in <lambda>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 258, in resf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 92, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 189, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to upda
te. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\youtube.py", line 1384, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\youtube.py", line 1297, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\youtube.py", line 1360, in <lambda>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 258, in resf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 92, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 189, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\youtube.py", line 1384, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\youtube.py", line 1297, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\youtube.py", line 1360, in <lambda>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 258, in resf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 92, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 189, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\youtube.py", line 2047, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\youtube.py", line 1394, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\youtube.py", line 1384, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\youtube.py", line 1297, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\youtube.py", line 1360, in <lambda>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 258, in resf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 92, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 189, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\jsinterp.py", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to upda
te. Be sure to call youtube-dl with the --verbose flag and include its complete output.

F:\cp>pause
Press any key to continue . . .

**Comment by dzek69** [comment]
> [debug] youtube-dl version 2020.01.01

Your youtube-dl version is very old. Please update.

**Comment by krisc24** [comment]
I get this same issue with version 2020.3.8
