### ISSUE TITLE
having the following problem

### ISSUE THREAD

**Issue by mehenuf** [ytdl-org/youtube-dl#24410]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
C:\Users\mehen\Downloads\youtube-dl>youtube-dl --verbose --cookies cookies.txt --username malkiaayusha69 --password qwerty222 -i https://www.pornhubpremium.com/view_video.php?viewkey=ph5da5f00d9885d
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--cookies', 'cookies.txt', '--username', 'PRIVATE', '--password', 'PRIVATE', '-i', 'https://www.pornhubpremium.com/view_video.php?viewkey=ph5da5f00d9885d']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-03-15-c467328, ffprobe git-2020-03-15-c467328
[debug] Proxy map: {}
[PornHub] ph5da5f00d9885d: Downloading pc webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\pornhub.py", line 206, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 1014, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

![image](https://user-images.githubusercontent.com/40866680/77144956-6e451c00-6ab1-11ea-81d4-423b999e112c.png)
Used same command lines to download and that worked but now its showing this problem
version : 2020.03.08

**Comment by mehenuf** [comment]
see at top at first i tried with --username and --password
