### ISSUE TITLE
Tele5 fails with 403: Forbidden

### ISSUE THREAD

**Issue by em-jay-es** [ytdl-org/youtube-dl#24418]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

C:\youtube-dl>youtube-dl -v --cookies cookies-tele5.txt --no-check-certificate https://www.tele5.de/filme/schlefaz-ich-ein-groupie/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'cookies-tele5.txt', '--no-check-certificate', 'https://www.tele5.de/filme/schlefaz-ich-ein-groupie/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Tele5] schlefaz-ich-ein-groupie: Downloading webpage
[Nexx] 1612864: Downloading JSON metadata
[Nexx] 1612864: Downloading m3u8 information
[Nexx] 1612864: Downloading MPD manifest
[Nexx] 1612864: Downloading ISM manifest
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'http://tele5nexx.akamaized.net/1afc9ae5-1bfc-4426-8d8c-f354531988bb/1612864_src_1024x576_1500.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 1926, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

## Description

Trying to download video from Tele5 fails with 403 forbidden, as shown above.

**Comment by em-jay-es** [comment]
I don't think this is a duplicate of #22810. #22810 was resolved by adding cookies. Note that cookies are included in the log above, and the error still occurs, suggesting a different root cause.
