### ISSUE TITLE
Vidio - Unable to extract hls url

### ISSUE THREAD

**Issue by NaufalAriqS21** [ytdl-org/youtube-dl#24427]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
E:\>youtube-dl --version
2020.03.08
E:\>youtube-dl -v -F https://www.vidio.com/watch/1623345-petualangan-sherina
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.vidio.com/watch/1623345-petualangan-sherina']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg git-2020-03-15-c467328, ffprobe git-2020-03-15-c467328
[debug] Proxy map: {}
[Vidio] petualangan-sherina: Downloading webpage
ERROR: Unable to extract hls url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\vidio.py", line 53, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract hls url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Even with cookies:
```
E:\>youtube-dl -v -F --cookies cookies.txt https://www.vidio.com/watch/1623345-petualangan-sherina
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', '--cookies', 'cookies.txt', 'https://www.vidio.com/watch/1623345-petualangan-sherina']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg git-2020-03-15-c467328, ffprobe git-2020-03-15-c467328
[debug] Proxy map: {}
[Vidio] petualangan-sherina: Downloading webpage
ERROR: Unable to extract hls url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\vidio.py", line 53, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract hls url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Here the working example - 1:
```
E:\>youtube-dl -v -F https://www.vidio.com/watch/1885132-pendekar-tongkat-emas
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.vidio.com/watch/1885132-pendekar-tongkat-emas']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg git-2020-03-15-c467328, ffprobe git-2020-03-15-c467328
[debug] Proxy map: {}
[Vidio] pendekar-tongkat-emas: Downloading webpage
[Vidio] pendekar-tongkat-emas: Downloading m3u8 information
WARNING: unable to extract like count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[info] Available formats for 1885132:
format code     extension  resolution note
audio-und_mp4a  mp4        audio only
222             mp4        256x144     222k , avc1.64080d, video only
326             mp4        480x270     326k , avc1.640815, video only
421             mp4        640x360     421k , avc1.64081e, video only
566             mp4        853x480     566k , avc1.64081e, video only
916             mp4        1280x720    916k , avc1.64081f, video only
1758            mp4        1920x1080  1758k , avc1.640828, video only (best)
```

Working example - 2 :
```
E:\>youtube-dl -v -F https://www.vidio.com/watch/1922206-covid-19-update
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.vidio.com/watch/1922206-covid-19-update']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg git-2020-03-15-c467328, ffprobe git-2020-03-15-c467328
[debug] Proxy map: {}
[Vidio] covid-19-update: Downloading webpage
[Vidio] covid-19-update: Downloading m3u8 information
WARNING: unable to extract like count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[info] Available formats for 1922206:
format code  extension  resolution note
144p         mp4        256x144     400k , avc1.640029, mp4a.40.2
270p         mp4        480x270     600k , avc1.640029, mp4a.40.2
360p         mp4        640x360     700k , avc1.640029, mp4a.40.2
480p         mp4        854x480     900k , avc1.640029, mp4a.40.2
720p         mp4        1280x720   1200k , avc1.640029, mp4a.40.2 (best)
```

## Description

Youtube-dl unable to extract hls url. I only test to check the video format.

**Comment by dstftw** [comment]
You must provide account credentials for any work on this.

**Comment by NaufalAriqS21** [comment]
Oh, I can provide account for testing.

**Comment by NaufalAriqS21** [comment]
Hello, I can provide account credentials for fixing Vidio.

**Comment by shygnome** [comment]
Hello! I am also interested in this issue. Any news for this fix? Is there anything I can help?
