### ISSUE TITLE
site add request - nickelodeon.dk

### ISSUE THREAD

**Issue by nem0rder** [ytdl-org/youtube-dl#24420]
## Checklist

- [ x] I'm reporting a new site support request
- [ x] I've verified that I'm running youtube-dl version **2020.03.08**

```
$ youtube-dl --version
2020.03.08
```
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that none of provided URLs violate any copyrights
- [ x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

https://www.nickelodeon.dk/episodes/pb4q9b/lego-r-city-adventures-buster-shirley-staedare-saeson-1
https://www.nickelodeon.dk/episodes/hsc2x0/lego-r-city-adventures-rovere-og-lover-billen-billy-saeson-1-af-1
https://www.nickelodeon.dk/episodes/08q2ru/lego-r-city-adventures-hele-byens-dormand-vilde-fendrich-saeson-1-af-4
https://www.nickelodeon.dk/episodes/mdpdb8/lego-r-city-adventures-poppy-starr-skumle-ting-saeson-1-af-3
https://www.nickelodeon.dk/episodes/o9zfoh/lego-r-city-adventures-actionjul-forbryderhuler-saeson-1
https://www.nickelodeon.dk/episodes/o27csi/lego-r-city-adventures-lille-carol-sidste-mand-i-lobet-saeson-1-af-1

## Description

I would like to request that www.nickelodeon.dk will be added to youtube-dl

**Comment by hazcod** [comment]
Same for nickelodeon.nl or nickelodeon.be:

```
% youtube-dl --version
2020.12.09

% youtube-dl -f best -v 'https://www.nickelodeon.nl/episodes/vk6yzc/spongebob-gaan-op-die-maan-seizoen-seasonnumber-11-afl-22'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '-v', 'https://www.nickelodeon.nl/episodes/vk6yzc/spongebob-gaan-op-die-maan-seizoen-seasonnumber-11-afl-22']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.09
[debug] Python version 3.9.0 (CPython) - macOS-10.16-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[nick.de] spongebob-gaan-op-die-maan-seizoen-seasonnumber-11-afl-22: Downloading webpage
ERROR: Unable to extract mrss url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2020.12.9/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2020.12.9/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2020.12.9/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2020.12.9/libexec/lib/python3.9/site-packages/youtube_dl/extractor/nick.py", line 191, in _real_extract
    mrss_url = self._extract_mrss_url(webpage, host)
  File "/usr/local/Cellar/youtube-dl/2020.12.9/libexec/lib/python3.9/site-packages/youtube_dl/extractor/nick.py", line 180, in _extract_mrss_url
    return update_url_query(self._search_regex(
  File "/usr/local/Cellar/youtube-dl/2020.12.9/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract mrss url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by N-Games** [comment]
Could this please be fixed in an update? It's still broken in the latest version of youtube-dl

**Comment by J0hsHH** [comment]
same for nickelodeon.no

**Comment by J0hsHH** [comment]
@nicolajthulin @hazcod  it works for nickelodeon.no youtube-dlc maybe have a try?

https://github.com/blackjack4494/youtube-dlc/commit/51707d9a7a4b7808d350bfa6565f8668e4a30dd9

**Comment by hazcod** [comment]
@J0hsHH broken for a while now https://github.com/yt-dlp/yt-dlp/issues/169

**Comment by N-Games** [comment]
will nickelodeon sites ever be fixed
