### ISSUE TITLE
Unable to extract video format from mpd manifest

### ISSUE THREAD

**Issue by NaufalAriqS21** [ytdl-org/youtube-dl#24428]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
E:\>youtube-dl --version
2020.03.08
E:\>youtube-dl -v -F https://liveanevia.mncnow.id/vod/eds/bima-x-spesial-episode-apl-anv6/_/sa_dash_vmx/bima-x-spesial-episode-apl-anv6.mpd
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://liveanevia.mncnow.id/vod/eds/bima-x-spesial-episode-apl-anv6/_/sa_dash_vmx/bima-x-spesial-episode-apl-anv6.mpd']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg git-2020-03-15-c467328, ffprobe git-2020-03-15-c467328
[debug] Proxy map: {}
[generic] bima-x-spesial-episode-apl-anv6: Requesting header
[redirect] Following redirect to https://anevia115.mncnow.id:443/vod/eds/bima-x-spesial-episode-apl-anv6/_/sa_dash_vmx/bima-x-spesial-episode-apl-anv6.mpd
[generic] bima-x-spesial-episode-apl-anv6: Requesting header
WARNING: Falling back on generic information extractor.
[generic] bima-x-spesial-episode-apl-anv6: Downloading webpage
[generic] bima-x-spesial-episode-apl-anv6: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\generic.py", line 2397, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Working example:
```
E:\>youtube-dl -v -F https://cdn-accedo-01.akamaized.net/Content/DASH/VOD/15892/19062/89544539-bd39-4e01-8b95-a5c5d9c66c70/a7e4ab17-a5cf-3227-e855-c9907ebb5f13/manifest.mpd
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://cdn-accedo-01.akamaized.net/Content/DASH/VOD/15892/19062/89544539-bd39-4e01-8b95-a5c5d9c66c70/a7e4ab17-a5cf-3227-e855-c9907ebb5f13/manifest.mpd']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg git-2020-03-15-c467328, ffprobe git-2020-03-15-c467328
[debug] Proxy map: {}
[generic] manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest: Downloading webpage
[generic] manifest: Extracting information
[info] Available formats for manifest:
format code  extension  resolution note
stream_5     m4a        audio only [eng] DASH audio   40k , m4a_dash container, mp4a.40.5 (48000Hz)
stream_0     mp4        320x180    DASH video  200k , mp4_dash container, avc1.4d4020, 50fps, video only
stream_1     mp4        480x270    DASH video  500k , mp4_dash container, avc1.4d4020, 50fps, video only
stream_2     mp4        640x360    DASH video  800k , mp4_dash container, avc1.4d4020, 50fps, video only
stream_3     mp4        960x540    DASH video 1200k , mp4_dash container, avc1.4d4020, 50fps, video only
stream_4     mp4        1280x720   DASH video 1600k , mp4_dash container, avc1.4d4020, 50fps, video only (best)
```

## Description

In the first mpd manifest url, I can't extract video format. But, in the second mpd manifest url I can extract the format. Is it related to the content protection in the first url? If yes, can I extract video format from the first url like the second url? (I just want to check the format available from the manifest)

**Comment by KeyCode17** [comment]
did you had license key for 
`https://liveanevia.mncnow.id/vod/eds/bima-x-spesial-episode-apl-anv6/_/sa_dash_vmx/bima-x-spesial-episode-apl-anv6.mpd`

**Comment by 89z** [comment]
in this case, the MPD URL is not enough, as the license server information is also needed

**Comment by KeyCode17** [comment]
Yeah i know it, cause of that i ask him, did he had it or not

**Comment by 89z** [comment]
you should be able to get the license server info by watching the public URL. If all you have is the MPD URL, then you cant get it.
