### ISSUE TITLE
FranceTV: some videos are not working, but a similar video works

### ISSUE THREAD

**Issue by EB2000** [ytdl-org/youtube-dl#24426]
## Checklist

- [ X] I'm reporting a broken site support
- [X ] I've verified that I'm running youtube-dl version **2020.03.08**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

 % youtube-dl -v -F 'https://www.france.tv/970585-symphonies-n-1-et-n-5-de-tchaikovski-a-l-opera-de-paris.html'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.france.tv/970585-symphonies-n-1-et-n-5-de-tchaikovski-a-l-opera-de-paris.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.7.6 (CPython) - Linux-5.5.8-200.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[FranceTVSite] 970585-symphonies-n-1-et-n-5-de-tchaikovski-a-l-opera-de-paris: Downloading webpage
[FranceTV] 406e49ca-eb67-46c6-bc84-7ac584539132: Downloading video JSON
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2019, in download
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 870, in process_ie_result
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 209, in _real_extract
  File "/usr/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 103, in _extract_video
IndexError: list index out of range

## Description

The three following urls work in browser:

https://www.france.tv/970585-symphonies-n-1-et-n-5-de-tchaikovski-a-l-opera-de-paris.html
https://www.france.tv/971153-tchaikovski-symphonie-n-2-4-dirigees-par-philippe-jordan.html
https://www.france.tv/971277-tchaikovski-symphonie-n-3-6-dirigees-par-philippe-jordan.html

However, only the third one works with youtube-dl.

I have pasted the output of youtube-dl -v '[first url]'; the error message for the second url is the same (except where the url is printed, obviously, and for the hexadecimal sequence on the "Downloading video JSON" line)

The three videos have been posted at the same time and obviously form a sequence. It is weird that one works but not the others.

**Comment by dstftw** [comment]
You must provide FR proxy for any work on this.

**Comment by flzara** [comment]
Hi @dstftw ,
I'm facing the same issue here and I understand that you need an french IP to be able to work on it. If I provide you with a temp SSH access to a server based in France, will you be able to setup a tunnel and test it ?
If yes, how to send them to you privately ?
Thank you.
