### ISSUE TITLE
Workaround for  #10766

### ISSUE THREAD

**Issue by ThePirate42** [ytdl-org/youtube-dl#24422]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have the problem described in [https://github.com/ytdl-org/youtube-dl/issues/10766](https://github.com/ytdl-org/youtube-dl/issues/10766), but I had activated ISS only for curiosity, and since then, even after deactivating it (I don't need it), youtube-dl binaries on my PC fail with this error:
`C:\Users\piez>youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\__init__.py", line 441, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 419, in __init__
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 2345, in _setup_opener
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\utils.py", line 2288, in make_HTTPS_handler
  File "C:\Python\Python34\lib\ssl.py", line 439, in create_default_context
  File "C:\Python\Python34\lib\ssl.py", line 390, in load_default_certs
  File "C:\Python\Python34\lib\ssl.py", line 377, in _load_windows_store_certs
PermissionError: [WinError 5] Accesso negato`
(unless I have administrative privileges). I need to use the youtube-dl exe version for compability with MPC-HC ([https://github.com/clsid2/mpc-hc/issues/301](https://github.com/clsid2/mpc-hc/issues/301)), what I have to do to make youtube-dl work again?

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl/issues/17048#issuecomment-407117427

**Comment by ThePirate42** [comment]
But before it worked, and ISS now is deactivated. What has changed in my system?
