### ISSUE TITLE
New site support: arhiiv.err.ee

### ISSUE THREAD

**Issue by lameslime** [ytdl-org/youtube-dl#24434]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: http://arhiiv.err.ee/vaata/eesti-aja-lood-okupatsioonid-muusad-soja-varjus
- Playlist: http://arhiiv.err.ee/seeria/eesti-aja-lood-okupatsioonid/info/0/default/koik
- Main site: http://arhiiv.err.ee/err-videoarhiiv

## Description

WRITE DESCRIPTION HERE
It's an archive with many TV-Shows, Movies and Documentaries aired in ETV (Estonia).

`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://arhiiv.err.ee/vaata/eesti-aja-lood-okupatsioonid-muusad-soja-varjus', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1
[debug] Proxy map: {}
[generic] eesti-aja-lood-okupatsioonid-muusad-soja-varjus: Requesting header
WARNING: Falling back on generic information extractor.
[generic] eesti-aja-lood-okupatsioonid-muusad-soja-varjus: Downloading webpage
[generic] eesti-aja-lood-okupatsioonid-muusad-soja-varjus: Extracting information
ERROR: Unsupported URL: http://arhiiv.err.ee/vaata/eesti-aja-lood-okupatsioonid-muusad-soja-varjus
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\generic.py", line 3351, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://arhiiv.err.ee/vaata/eesti-aja-lood-okupatsioonid-muusad-soja-varjus`

**Comment by hatienl0i261299** [comment]
Source in var clip
```
var clip = {
  autoplay: false,
   sources: '://media.err.ee/arhiiv/@2009-002267-0068_0001_D10_EESTI-AJA-LOOD-OKUPATSIOONID.mp4',
type: 'video',
src: {'hls': '//jv.err.ee/arhiiv/2009-002267-0068_0001_D10_EESTI-AJA-LOOD-OKUPATSIOONID.mp4/master.m3u8'}
  };          
```

**Comment by jtagcat** [comment]
It would be nice to also support etv.err.ee in the same go.
