### ISSUE TITLE
[DouyuShow] TypeError: string indices must be integers

### ISSUE THREAD

**Issue by ZM-J** [ytdl-org/youtube-dl#24444]
## Checklist

- [ x ] I'm reporting a broken site support issue
- [ x ] I've verified that I'm running youtube-dl version **2020.03.08**
- [ x ] I've checked that all provided URLs are alive and playable in a browser
- [ x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x ] I've searched the bugtracker for similar bug reports including closed ones
- [ x ] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v https://v.douyu.com/show/ZB5Kv95KAzKva93x
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://v.douyu.com/show/ZB5Kv95KAzKva93x']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-01-13-7225479, ffprobe git-2020-01-13-7225479
[debug] Proxy map: {}
[DouyuShow] ZB5Kv95KAzKva93x: Downloading webpage
[DouyuShow] ZB5Kv95KAzKva93x: Downloading JSON metadata
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\douyutv.py", line 176, in _real_extract
TypeError: string indices must be integers
```

## Description

This link is official streaming videos archive of DouyuTV. I did not try whether youtube-dl works or not on other videos in DouyuTV.

**Comment by jc3213** [comment]
Same problem confirmed on version 2019.03.24. This bug prevent me downloading douyu live archives
@dstftw  
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo+bestaudio/best', '-o', 'R:\\Youtube-DL\\%(title)s.%(ext)s', '--download-archive', 'R:\\Temp\\youtube-dl.txt', 'https://v.douyu.com/show/DrwnvzAO9ljWPNaX', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.2.2
[debug] Proxy map: {}
[DouyuShow] DrwnvzAO9ljWPNaX: Downloading webpage
[DouyuShow] DrwnvzAO9ljWPNaX: Downloading JSON metadata
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\douyutv.py", line 176, in _real_extract
TypeError: string indices must be integers
```

**Comment by simonewebdesign** [comment]
I'm seeing this issue on version 2021.12.17 as well:

```
youtube-dl -f bestaudio 'https://www.youtube.com/watch?v=QRTNm6GLJYI' --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestaudio', 'https://www.youtube.com/watch?v=QRTNm6GLJYI', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.9.12 (CPython) - macOS-12.3.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 5.0.1, ffprobe 5.0.1, phantomjs present, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] QRTNm6GLJYI: Downloading webpage
[youtube] QRTNm6GLJYI: Downloading player 0c665041
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/local/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1265, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1332, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/lib/python3.9/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/lib/python3.9/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/lib/python3.9/site-packages/youtube_dl/jsinterp.py", line 150, in interpret_expression
    return obj[member]
TypeError: string indices must be integers
```
