### ISSUE TITLE
ERROR: Signature extraction failed with certain YT URL

### ISSUE THREAD

**Issue by MarByteBeep** [ytdl-org/youtube-dl#24445]
Hi there,

I noticed that `youtube-dl` fails sometimes. Some videos fail and some work fine. 

OS: Windows 10
Downloader version: 2019.12.25

An example of a failure: 

When executing:

```
youtube-dl 9UNuqYFP-pM --verbose
```

I'm getting the following error:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['9UNuqYFP-pM', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.12.25
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2019-11-22-89aa134, ffprobe git-2019-11-22-89aa134
[debug] Proxy map: {}
[youtube] 9UNuqYFP-pM: Downloading webpage
[youtube] 9UNuqYFP-pM: Downloading video info webpage
[youtube] {18} signature length 110, html5 player vflEO2H8R
[youtube] 9UNuqYFP-pM: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vflEO2H8R/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\youtube.py", line 1384, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\youtube.py", line 1297, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\youtube.py", line 1360, in <lambda>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 258, in resf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 92, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 189, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\youtube.py", line 1384, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\youtube.py", line 1297, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\youtube.py", line 1360, in <lambda>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 258, in resf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 92, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 189, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\youtube.py", line 1384, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\youtube.py", line 1297, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\youtube.py", line 1360, in <lambda>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 258, in resf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 92, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 189, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\youtube.py", line 2047, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\youtube.py", line 1394, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\youtube.py", line 1384, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\youtube.py", line 1297, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\youtube.py", line 1360, in <lambda>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 258, in resf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 92, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 189, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\jsinterp.py", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

I guess it's a bug, since some other URLs seem to work fine.

**Comment by MarByteBeep** [comment]
My wrong; my code used an older path. Apologies!
