### ISSUE TITLE
cda.pl Broken Extractor

### ISSUE THREAD

**Issue by MaybeYesMaybeNot** [ytdl-org/youtube-dl#24458]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.03.24**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.cda.pl/video/14954728b', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
[debug] exe versions: none
[debug] Proxy map: {}
[CDA] 14954728b: Downloading webpage
[CDA] 14954728b: Downloading 360p version information
[CDA] 14954728b: Downloading 720p version information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'G86C_bg%5D452%5DA%3D%5EE8%3A%23Hp08hAy8gtczBCurF8%5E%60dgd_hffec%5ED557a6_afae4%605g572gggbc56gdd2e3%6024'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2019, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1926, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
  File "/usr/lib64/python2.7/urllib2.py", line 423, in open
    protocol = req.get_type()
  File "/usr/lib64/python2.7/urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: G86C_bg%5D452%5DA%3D%5EE8%3A%23Hp08hAy8gtczBCurF8%5E%60dgd_hffec%5ED557a6_afae4%605g572gggbc56gdd2e3%6024

```

## Description

My guess is that they have encrypted displayed urls to base64 but i can be wrong.

**Comment by fraunos** [comment]
Experiencing the same problem

**Comment by someziggyman** [comment]
Same thing here for URL: https://www.cda.pl/video/83970839
unknown url type error in the log.


[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'best', u'https://www.cda.pl/video/83970839']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[CDA] 83970839: Downloading webpage
[CDA] 83970839: Downloading 360p version information
[CDA] 83970839: Downloading 720p version information
[CDA] 83970839: Downloading 1080p version information
[debug] Invoking downloader on u'GH2H_gf%5D452%5DA%3D%5Eg_d6%21xrsGH5%3C0d%7D_u%3Bgu58%5E%60dgd%60ed_bc%5E95baah3hc3fhdg457h7he43ff2cfe_gdhf'
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2019, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1926, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: GH2H_gf%5D452%5DA%3D%5Eg_d6%21xrsGH5%3C0d%7D_u%3Bgu58%5E%60dgd%60ed_bc%5E95baah3hc3fhdg457h7he43ff2cfe_gdhf

**Comment by Kondzio18** [comment]
Same problem - win10 

`youtube-dl https://www.cda.pl/video/250195141/vfilm -v 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.cda.pl/video/250195141/vfilm', '-v', '-F']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.1, ffprobe 3.2
[debug] Proxy map: {}
[CDA] 250195141: Downloading webpage
[CDA] 250195141: Downloading 480p version information
WARNING: Unable to download webpage: HTTP Error 404:
WARNING: [CDA] Unable to download 480p version information
[CDA] 250195141: Downloading 720p version information
WARNING: Unable to download webpage: HTTP Error 404:
WARNING: [CDA] Unable to download 720p version information
[CDA] 250195141: Downloading 1080p version information
WARNING: Unable to download webpage: HTTP Error 404:
WARNING: [CDA] Unable to download 1080p version information
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 863, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1582, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1396, in _calc_headers
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1408, in _calc_cookies
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\utils.py", line 2149, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
    origin_req_host = request_host(self)
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
    def data(self):
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse

ValueError: unknown url type: 'GH2Hdah%5D452%5DA%3D%5E%263b%23%29%3BE38FgE%3F6gv%3Fsu%2B3p%5E%60dgd%60fcd%60d%5EG%3D3a%606g4cb3f4_f3b_7af4hg33afccff4_'

C:\Users\XxxXx>youtube-dl -U
youtube-dl is up-to-date (2020.03.24)
`

**Comment by stachuman** [comment]
Nop, no encoded path to file, 
when searching in page source for: pb-video-player-content - getting video class with src=full path to mp4 (not encoded)

I believe - shouldn't be complicated to fix

**Comment by Mikolaj98p** [comment]
I have same problem:
```
./youtube-dl -f hd https://www.cda.pl/video/294230158 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'hd', u'https://www.cda.pl/video/294230158', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Darwin-19.4.0-x86_64-i386-64bit
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[CDA] 294230158: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "./youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by divadsn** [comment]
I've managed to decrypt the file from player_data, see my work here:
https://gist.github.com/divadsn/e1e7691b0bc6bb88a0d3680912bb0842

**Comment by divadsn** [comment]
Implemented into extractor, see PR #24518

**Comment by cb1986ster** [comment]
In line:
https://github.com/ytdl-org/youtube-dl/pull/24518/files#diff-ef1160d73154dc227734eb1d150ff7e9R150
also can check `video['file'].endswith('_XDDD')` should be fine :)

**Comment by divadsn** [comment]
@cb1986ster I already noticed their ridiculous cringy way to break the extractor again and checked the new code again. Really funny, although it took me 15 minutes to break down.

But unfortunately it looks like ytdl-org collaborators are not interested into accepting nor reviewing the PR as they locked down the conversation for further comments regarding my work.

**Comment by divadsn** [comment]
@dstftw can we get **any** update on what is going on with the PR? If you do not intend on merging the fix then at least be transparent about the information why you locked down the PR while other fixes are being merged and reviewed.

**Comment by divadsn** [comment]
CDA unfortunately keeps breaking the extractor by adding more obfuscation crap, it's now a cat and mouse game until CDA gives up and starts using DRM on non-premium videos.

**Comment by olesio** [comment]
Hello. It is my first comment on Git Hub so sorry for all error and my bad English :) I have the same situation as Kondzio18. But as I see crypted algorythm seems to be the same as in his issue. So if more than 20 days past go by, probable cda.pl do not change web code to oft.

Anyway, at this moment when I write this answer, only quick and working way to download video from cda.pl is FireFox addon at 

https://addons.mozilla.org/pl/firefox/addon/cda-pl-linkacz/?src=search

The code of addon is very simple but tricky for me... So maybe is any way to implement JS support and let work youtube-dl as some simple JS engine in Web Browser. But it is too much work, maybe you guys with great knowledge will implement fixes when cda.pl change something as soon as possible and someone post new issue here about cda.pl changes.

I do not have to much knowledge about Python. Anyway thanks to whole Team for hard work developing this useful utility :) And we hope cda.pl give up to change to much the algorythms or implement DRMS in future.

let link = document.querySelector("#player .pb-post-fl .pb-video-player").src;
let style = "position:absolute;right:0;top:7px;bottom:7px;border-radius:5px;background:#f50;padding:0 10px;color:white;display:flex;align-items:center;font-size:0.8em;"
let a = document.createElement("a");
a.href = link;
a.setAttribute("style", style);
a.innerHTML = "OtwĂłrz MP4";
a.target = "_blank";
document.querySelector("#player .brdPlayerWrapper #naglowek>span").appendChild(a);
document.querySelector("#player .brdPlayerWrapper .wrapqualitybtn").style.right = "110px";

**Comment by bato3** [comment]
I think, that they can track changes in this repository.

@divadsn Because comments in PR are locked:

- change quotes from `"` to `'` in whole file (and test it by `flake8`)
- they added more suffixes, which is why I'm thinking about declaring a _joke list_ on the beginning of the file or even use a regular expression `a = re.sub(r'_[a-zA-Z]+$', '', a)`

**Comment by divadsn** [comment]
@bato3 yes I am aware of the unsolved changes in the PR.

Regarding that list, I already made such change in my demo project here: https://github.com/divadsn/cda-video-extractor/blob/master/server.py#L38

But the goal would be to scrape the player.js on the go and extract the current "joke" list before extracting the video, kinda like the extractor for soundcloud does to get the client id.

**Comment by bato3** [comment]
As I look quickly, this soundcloud uses an API to update the key. (Although I may not have noticed something.) Extracting it from _player.js_ Pulling it out of player.js is like shooting a mosquito cannon.

This is not some dynamically generated key. All they need to do is change the file structure a bit and everything is falling apart...

We either risk a regular expression, or we need to apply an openload domain approach: update, after they change.

**Comment by divadsn** [comment]
Soundcloud extractor pulls the client id using a regular expression from any possible javascript file, which can be seen here: https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/soundcloud.py#L277

We have two options: Implement such similar regex to grab the list from player.js or have a file containing all "jokes" hosted on github pages that will be updated after they change.

**Comment by Sylvvvia** [comment]
If you need any hosting for decoding service or autoupdate service let me know, i'll provide it for free.

**Comment by nawordar** [comment]
Since the previous PR has been abandoned, I have created a new PR for this. Hopefully they won't change their script so fast this time.

As for observing changes in the repo, I don't think that we can do much more than play cat and mouse game.

**Comment by divadsn** [comment]
Well it ain't abandoned, I still keep a maintained list of words in my own
demo project, I plan to potentially change the PR so the list will be
pulled from a text file independently of youtube-dl releases.

niedz., 2 sie 2020, 18:27 użytkownik Cezary Drożak <notifications@github.com>
napisał:

**Comment by nawordar** [comment]
GitHub shows origin branch as `unknown repository` in the pull request, so I thought that the branch has been removed.
I think that it would be better to merge the PR, either yours or mine, for an ad-hoc solution.

If you maintain a project with a list of words, then I don't understand why you won't share it, so someone else could open a PR adding support for pulling word list from your repository.

**Comment by divadsn** [comment]
It's on my GitHub, so it's free for everyone to use.

pon., 3 sie 2020, 14:34 użytkownik Cezary Drożak <notifications@github.com>
napisał:

**Comment by nawordar** [comment]
I've found it, thank you. Also sorry for being mean

**Comment by dkja** [comment]
Fixed on my github: https://github.com/dkja/youtube-dl ;) I'm not python programmer, but...

**Comment by selfisekai** [comment]
Fixed in [haruhi-dl](https://haruhi.download), a libre fork of youtube-dl.
