### ISSUE TITLE
Some emojis in video titles break youtube-dl

### ISSUE THREAD

**Issue by Infinitay** [ytdl-org/youtube-dl#24456]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
Microsoft Windows [Version 10.0.18363.720]
(c) 2019 Microsoft Corporation. All rights reserved.

<redacted-path>>cd <redacted-path>\extracted

<redacted-path>\extracted>youtube-dl --no-part --hls-prefer-native -f best -v https://www.vlive.tv/video/181711
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-part', '--hls-prefer-native', '-f', 'best', '-v', 'https://www.vlive.tv/video/181711']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[vlive] 181711: Downloading webpage
[vlive] 181711: Downloading live webpage
[vlive] 181711: Downloading m3u8 information
[vlive] 181711: Downloading m3u8 information
[vlive] 181711: Downloading m3u8 information
[vlive] 181711: Downloading m3u8 information
[vlive] 181711: Downloading m3u8 information
[vlive] 181711: Downloading m3u8 information
[vlive] 181711: Downloading m3u8 information
[debug] Invoking downloader on 'https://vlive-hls.akamaized.net/lip2_kr2/anmss0161/ddf4r90gyo6puyls4ru8igeliedcgjm4sltb1apg/4000.stream/chunklist.m3u8?__agda__=1585081667_3ab14f6db5fafec8ec9448be7273d065'
[download] Destination: [V LIVE] 누누가 만든 초코가 참 달고나🍫🥛 2020-03-24 07_27-181711.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.37 Safari/537.36
Accept-Encoding: gzip, deflate
" -i "https://vlive-hls.akamaized.net/lip2_kr2/anmss0161/ddf4r90gyo6puyls4ru8igeliedcgjm4sltb1apg/4000.stream/chunklist.m3u8?__agda__=1585081667_3ab14f6db5fafec8ec9448be7273d065" -c copy -f mp4 "file:[V LIVE] 누누가 만든 초코가 참 달고나🍫�ERROR: unable to download video data: Failed to write string
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1926, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\external.py", line 35, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\external.py", line 334, in _call_downloader
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\common.py", line 391, in _debug_cmd
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\common.py", line 150, in to_screen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 503, in to_screen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 517, in to_stdout
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 506, in _write_string
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\utils.py", line 3092, in write_string
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\utils.py", line 3076, in _windows_write_string
OSError: Failed to write string
```

## Description

It seems as if some emojis break youtube-dl when passing in the **verbose** argument. For example, current livestream (will change to a VOD depending on when this is read) found on VLive is titled ['누누가 만든 초코가 참 달고나🍫🥛'](https://www.vlive.tv/video/181711). When I attempt to run the following command: `youtube-dl --no-part --hls-prefer-native -f best -v https://www.vlive.tv/video/181711`, youtube-dl breaks and returns `OSError: Failed to write string`. 

I believe this is as a result of passing in `-v`, because if I choose not to have a verbose output, youtube-dl continues with no issue.

Another concern I want to raise is that I assume only certain emojis affects this verbose bug. The reason is there is another current livestream (could be a VOD depending on when this is read) found on VLive is titled ['ATINY 1기 키트 언박싱해요🎁'](https://www.vlive.tv/video/181714). When I ran the same command above and replacing the links, it continued just fine with the verbose output.

**Comment by Infinitay** [comment]
I noticed you marked this as a duplicate, are you referring to #5042? Because isn't that issue for transforming the name, as the title of the issue states? 

However, I do see an explicit mention of an issue regarding emojis #14474. However, this was issue was closed once more and essentially stated to be a duplicate of #5042.

**Comment by olivicus** [comment]
Did you happen to find a solution? There seems to be a workaround here for Linux users https://github.com/ytdl-org/youtube-dl/issues/5042 but I'm on Windows.
