### ISSUE TITLE
[ATRESPLAYER] unknown url type

### ISSUE THREAD

**Issue by jEsuSdA** [ytdl-org/youtube-dl#24462]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.atresplayer.com/lasexta/programas/lo-de-evole/temporada-1/especial-coronavirus_5e74a86b7ed1a815ffc98485/', '--username=PRIVATE', '--password=PRIVATE', '-o', 'lo-de-evole.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.7.5 (CPython) - Linux-5.2.0-20.1-liquorix-amd64-x86_64-with-debian-bullseye-sid
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[AtresPlayer] Downloading login page
[AtresPlayer] Logging in
[AtresPlayer] Following Target URL
Traceback (most recent call last):
  File "/usr/bin/yd", line 11, in <module>
    load_entry_point('youtube-dl==2020.3.24', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3/dist-packages/youtube_dl/__init__.py", line 479, in main
    _real_main(argv)
  File "/usr/lib/python3/dist-packages/youtube_dl/__init__.py", line 469, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 529, in extract
    self.initialize()
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 433, in initialize
    self._real_initialize()
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/atresplayer.py", line 45, in _real_initialize
    self._login()
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/atresplayer.py", line 75, in _login
    self._request_webpage(target_url, None, 'Following Target URL')
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    req = sanitized_Request(req)
  File "/usr/lib/python3/dist-packages/youtube_dl/utils.py", line 2149, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib/python3.7/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/usr/lib/python3.7/urllib/request.py", line 354, in full_url
    self._parse()
  File "/usr/lib/python3.7/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/api/oauth/authorize?client_id=atresplayer&redirect_uri=https%3A%2F%2Fapi.atresplayer.com%2FauthCallback&response_type=code&scope=openid&state=Eh03HD'

```

## Description

atresplayer links stop working.

I hope the log information helps you to try solving the problem.
Thanks a lot. ;)

**Comment by marium0505** [comment]
I also get the same (well, some of the same) error message as well.
There are some differences, particularly in the traceback. But the valueerror seems to be the same (besides a different state). 

`[debug] System config: []
[debug] User config: ['--console-title', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['https://www.atresplayer.com/antena3/series/la-embajada/temporada-1/capitulo-1-captulo-mano-fuego_5a941f8b7ed1a8cd76210f5b/', '-F', '-u', 'PRIVATE', '-p', 'PRIVATE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.20175
[debug] exe versions: ffmpeg git-2020-06-12-38737b3, ffprobe git-2020-06-12-38737b3
[debug] Proxy map: {}
[AtresPlayer] Downloading login page
[AtresPlayer] Logging in
[AtresPlayer] Following Target URL
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 433, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\atresplayer.py", line 45, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\atresplayer.py", line 75, in _login
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\utils.py", line 2157, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: '/api/oauth/authorize?client_id=atresplayer&redirect_uri=https%3A%2F%2Fapi.atresplayer.com%2FauthCallback&response_type=code&scope=openid&state=cCAjWX'`

I get the same when trying several others: 
<details>
  <summary>See more</summary>
  
https://www.atresplayer.com/antena3/series/el-secreto-de-puente-viejo/el-resurgir-de-puente-viejo/capitulo-final_5ec3d2407ed1a8470a02dff2/
  ```
[debug] System config: []
[debug] User config: ['--console-title', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['https://www.atresplayer.com/antena3/series/el-secreto-de-puente-viejo/el-resurgir-de-puente-viejo/capitulo-final_5ec3d2407ed1a8470a02dff2/', '-F', '-u', 'PRIVATE', '-p', 'PRIVATE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.20175
[debug] exe versions: ffmpeg git-2020-06-12-38737b3, ffprobe git-2020-06-12-38737b3
[debug] Proxy map: {}
[AtresPlayer] Downloading login page
[AtresPlayer] Logging in
[AtresPlayer] Following Target URL
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 433, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\atresplayer.py", line 45, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\atresplayer.py", line 75, in _login
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\utils.py", line 2157, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: '/api/oauth/authorize?client_id=atresplayer&redirect_uri=https%3A%2F%2Fapi.atresplayer.com%2FauthCallback&response_type=code&scope=openid&state=7TxNzy'
```

https://www.atresplayer.com/antena3/series/los-protegidos/temporada-1/capitulo-1-captulo-ahora_5a94246e7ed1a8cd80148520/
```
[debug] System config: []
[debug] User config: ['--console-title', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['https://www.atresplayer.com/antena3/series/los-protegidos/temporada-1/capitulo-1-captulo-ahora_5a94246e7ed1a8cd80148520/', '-F', '-u', 'PRIVATE', '-p', 'PRIVATE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.20175
[debug] exe versions: ffmpeg git-2020-06-12-38737b3, ffprobe git-2020-06-12-38737b3
[debug] Proxy map: {}
[AtresPlayer] Downloading login page
[AtresPlayer] Logging in
[AtresPlayer] Following Target URL
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 433, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\atresplayer.py", line 45, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\atresplayer.py", line 75, in _login
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\utils.py", line 2157, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: '/api/oauth/authorize?client_id=atresplayer&redirect_uri=https%3A%2F%2Fapi.atresplayer.com%2FauthCallback&response_type=code&scope=openid&state=RgeOr4'
```
  
https://www.atresplayer.com/novelas-nova/telenovelas/la-patrona/temporada-1/capitulo-1-captulo_5ad679b07ed1a88e0c97ecdf/
```
[debug] System config: []
[debug] User config: ['--console-title', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['https://www.atresplayer.com/novelas-nova/telenovelas/la-patrona/temporada-1/capitulo-1-captulo_5ad679b07ed1a88e0c97ecdf/', '-F', '-u', 'PRIVATE', '-p', 'PRIVATE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.20175
[debug] exe versions: ffmpeg git-2020-06-12-38737b3, ffprobe git-2020-06-12-38737b3
[debug] Proxy map: {}
[AtresPlayer] Downloading login page
[AtresPlayer] Logging in
[AtresPlayer] Following Target URL
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 433, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\atresplayer.py", line 45, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\atresplayer.py", line 75, in _login
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\utils.py", line 2157, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: '/api/oauth/authorize?client_id=atresplayer&redirect_uri=https%3A%2F%2Fapi.atresplayer.com%2FauthCallback&response_type=code&scope=openid&state=49u1lR'
```
  
</details>
