### ISSUE TITLE
Doesn't work on PHPremium 

### ISSUE THREAD

**Issue by gpy-dev** [ytdl-org/youtube-dl#24479]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--proxy', '127.0.0.1:36936', '--cookies', 'cookies.txt', 'https://www.pornhubpremium.com/view_video.php?viewkey=ph5e766962b0355']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.7.5 (CPython) - Linux-5.3.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {'http': '127.0.0.1:36936', 'https': '127.0.0.1:36936'}
[PornHub] ph5e766962b0355: Downloading pc webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/pornhub.py", line 206, in _real_extract
    webpage, 'title', group='title')
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

It worked a few hours ago, but it doesn't work now.
I don't think it's my account problem. Because it works well on the website.

**Comment by gpy-dev** [comment]
I used cookies option before.

**Comment by HASJ** [comment]
Stopped working this morning.

**Comment by gpy-dev** [comment]
> Stopped working this morning.

I solved this issue. I edited cookies file!

My orignal cookies
```
.pornhubpremium.com	TRUE	/	FALSE	1587708585	platform_cookie_reset	VALUE
.pornhubpremium.com	TRUE	/	FALSE	1585721385	platform	VALUE
.pornhubpremium.com	TRUE	/	FALSE	1900476585	bs	VALUE
.pornhubpremium.com	TRUE	/	FALSE	1616652585	ss	VALUE
.pornhubpremium.com	TRUE	/	FALSE	1648291296	_ga	VALUE
.pornhubpremium.com	TRUE	/	FALSE	1585305696	_gid	VALUE
.pornhubpremium.com	TRUE	/	FALSE	1587890409	expiredEnterModalShown	VALUE
.pornhubpremium.com	TRUE	/	FALSE	1585295595	ua	VALUE
```

and fixed cookies
```
.pornhubpremium.com	TRUE	/	FALSE	1587708585	platform_cookie_reset	VALUE
.pornhubpremium.com	TRUE	/	FALSE	1585721385	platform	VALUE
.pornhubpremium.com	TRUE	/	FALSE	1900476585	bs	VALUE
.pornhubpremium.com	TRUE	/	FALSE	1616652585	ss	VALUE
.pornhubpremium.com	TRUE	/	FALSE	1648291296	_ga	VALUE
.pornhubpremium.com	TRUE	/	FALSE	1585305696	_gid	VALUE
.pornhubpremium.com	TRUE	/	FALSE	1587890409	expiredEnterModalShown	VALUE
.pornhubpremium.com	TRUE	/	FALSE	1585295595	ua	VALUE
# Add cookie values
.pornhubpremium.com	TRUE	/	FALSE	1585219670	_gat	VALUE
.pornhubpremium.com	TRUE	/	FALSE	0	il	VALUE
```

I used development tools in Firefox browser for get cookies.

**Comment by 4ndriH** [comment]
@gpy-dev Could you please explain how I have to use the cookie file? I have never done this before.
I added the comment at the top but what values do I have to provide?
