### ISSUE TITLE
Merida on cda.pl reports unknown url (https://www.cda.pl/video/461790515)

### ISSUE THREAD

**Issue by ChewbaccaKL** [ytdl-org/youtube-dl#24472]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
script -c './youtube-dl -v https://www.cda.pl/video/461790515'
Script started on 2020-03-25 17:59:38+01:00 [TERM="xterm-256color" TTY="/dev/pts/3" COLUMNS="90" LINES="22"]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.cda.pl/video/461790515']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.2 (CPython) - Linux-5.5.11-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[CDA] 461790515: Downloading webpage
[CDA] 461790515: Downloading 360p version information
[CDA] 461790515: Downloading 720p version information
[CDA] 461790515: Downloading 1080p version information
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "./youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1582, in process_video_result
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1396, in _calc_headers
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1408, in _calc_cookies
  File "./youtube-dl/youtube_dl/utils.py", line 2149, in sanitized_Request
  File "/usr/lib/python3.8/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/usr/lib/python3.8/urllib/request.py", line 354, in full_url
    self._parse()
  File "/usr/lib/python3.8/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'GH2Hb_c%5D452%5DA%3D%5E%22%28%26xvg%3C6%2Atf%7D2D7%60fJBt7p%5E%60dgd%60hgfg%60%5EG%3D57h27b5__2b_3_%603g4_2d3e6chf4_a4e'

Script done on 2020-03-25 17:59:42+01:00 [COMMAND_EXIT_CODE="1"]


```

## Description

WRITE DESCRIPTION HERE
Just reported a probable bug

**Comment by Kondzio18** [comment]
duplicate [here]( https://github.com/ytdl-org/youtube-dl/issues/24458)

**Comment by ChewbaccaKL** [comment]
Thanks for reporting a duplicate. My fault.
