### ISSUE TITLE
player.pbs.org/partnerplayer/SUqFPV2uM5NtB9tzWhYbwQ

### ISSUE THREAD

**Issue by Davem734** [ytdl-org/youtube-dl#24484]
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
$ youtube-dl https://player.pbs.org/partnerplayer/SUqFPV2uM5NtB9tzWhYbwQ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://player.pbs.org/partnerplayer/SUqFPV2uM5NtB9tzWhYbwQ', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.15+ (CPython) - Linux-5.3.0-40-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.2.1-0york0, ffprobe 4.2.1-0york0, rtmpdump 2.4
[debug] Proxy map: {}
[generic] SUqFPV2uM5NtB9tzWhYbwQ: Requesting header
[redirect] Following redirect to https://player.pbs.org/partnerplayer/SUqFPV2uM5NtB9tzWhYbwQ/
[debug] Using fake IP 6.19.35.215 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] SUqFPV2uM5NtB9tzWhYbwQ: Downloading player page
ERROR: An extractor error has occurred. (caused by KeyError(u'contentID',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 540, in _real_extract
    video_id, display_id, upload_date, description = self._extract_webpage(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 524, in _extract_webpage
    video_info.get('id') or video_info['contentID'])
KeyError: u'contentID'
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 543, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'contentID',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

WRITE DESCRIPTION HERE

Unable to download URL
https://player.pbs.org/partnerplayer/SUqFPV2uM5NtB9tzWhYbwQ
From page:
https://www.tptoriginals.org/the-ramones-1978-live-in-minneapolis/

**Comment by 89z** [comment]
I think this is the current URL:

https://player.pbs.org/widget/partnerplayer/3016754074
