### ISSUE TITLE
NRL.com Error not working!

### ISSUE THREAD

**Issue by meib123** [ytdl-org/youtube-dl#24491]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.03.24**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\User\Downloads\youtube-dl>youtube-dl --verbose https://www.nrl.com/tv/matches/telstra-premiership/2005/preliminary-finals/full-match-replay-dragons-v-wests-tigers-preliminary-final-2005/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.nrl.com/tv/matches/telstra-premiership/2005/preliminary-finals/full-match-replay-dragons-v-wests-tigers-preliminary-final-2005/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-02-27-9b22254, ffprobe git-2020-02-27-9b22254
[debug] Proxy map: {}
[NRLTV] full-match-replay-dragons-v-wests-tigers-preliminary-final-2005: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('videoId',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\nrl.py", line 28, in _real_extract
KeyError: 'videoId'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\nrl.py", line 28, in _real_extract
KeyError: 'videoId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 543, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('videoId',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I have checked that NRL.com is a compatible site and when tring to download from it i just keep getting an error message!

Thanks!

**Comment by meib123** [comment]
Got it working mate thanks

**Comment by Laurie0006** [comment]
Hi @meib123 . I'm having the same issue as above. What did you do to resolve your issues?

I've tried without cookies, and with. Both with the same issue:

**Verbose log:**

[CODE]
youtube-dl.exe --verbose --cookies .\cookies\cookies.txt https://www.nrl.com/tv/matches/telstra-premiership/1998/preliminary-final/full-match-replay-bulldogs-v-eels---preliminary-final-1998/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--cookies', '.\\cookies\\cookies.txt', 'https://www.nrl.com/tv/matches/telstra-premiership/1998/preliminary-final/full-match-replay-bulldogs-v-eels---preliminary-final-1998/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-06-04-7f81785, ffprobe git-2020-06-04-7f81785
[debug] Proxy map: {}
[NRLTV] full-match-replay-bulldogs-v-eels---preliminary-final-1998: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('videoId',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\nrl.py", line 28, in _real_extract
KeyError: 'videoId'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\nrl.py", line 28, in _real_extract
KeyError: 'videoId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 543, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('videoId',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[CODE]

**Comment by meib123** [comment]
Are you still having issues? As I can help

**Comment by Laurie0006** [comment]
@meib123 yes I am. Thanks!

**Comment by meib123** [comment]
So what you want to do is play a vid on nrl then find the manifest, make
sure it's the lowercase manifest in the page source but you have to be
quick as this changes then copy and paste that after the youtube-dl and I
will download video and audio then if you have set Youtube-dl up correctly
it will then put both files into 1

**Comment by Laurie0006** [comment]
@meib123 thanks! Got it working with those instructions.

**Comment by swedishstyle** [comment]
I'm confused at this solution, although it may have changed since this was over a year ago now - I found 'manifest' in the source, but it's a massive URL that doesn't work in youtubeDL at all, it just gives back a 404. I don't see any part that could be stripped out to use as an Ooyala ID or anything either - any thoughts?

**Comment by rautamiekka** [comment]
I wonder if the request's missing some headers in which case.

**Comment by swedishstyle** [comment]
> I wonder if the request's missing some headers in which case.

Do you mean you have an idea of how to work around this issue?

**Comment by rautamiekka** [comment]
Hardly. Even the 'might be missing headcers' was learnt from other contexts, and it's the only idea I got right now.
