### ISSUE TITLE
Random 403 Forbidden on YouTube

### ISSUE THREAD

**Issue by titirino159** [ytdl-org/youtube-dl#24510]
## Checklist

- [* ] I'm reporting a broken site support
- [ *] I've verified that I'm running youtube-dl version **2020.03.24**
- [ *] I've checked that all provided URLs are alive and playable in a browser
- [ *] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [* ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=Ndpryp2OlUQ', u'--source-address', u'XXXX, u'--proxy', u'XXXX/', u'-o', u'test4.mp4', u'--verbose']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-11-amd64-x86_64-with-debian-9.11
[debug] exe versions: ffmpeg 4.1.2, ffprobe 4.1.2, phantomjs 2.1.1
[debug] Proxy map: {u'http': u'XXXX/', u'https': u'XXXX/'}
[youtube] Ndpryp2OlUQ: Downloading webpage
[youtube] {18} signature length 107, html5 player vflset
[youtube] {137} signature length 107, html5 player vflset
[youtube] {248} signature length 107, html5 player vflset
[youtube] {399} signature length 103, html5 player vflset
[youtube] {136} signature length 107, html5 player vflset
[youtube] {247} signature length 107, html5 player vflset
[youtube] {398} signature length 107, html5 player vflset
[youtube] {135} signature length 103, html5 player vflset
[youtube] {244} signature length 103, html5 player vflset
[youtube] {397} signature length 107, html5 player vflset
[youtube] {134} signature length 103, html5 player vflset
[youtube] {243} signature length 107, html5 player vflset
[youtube] {396} signature length 107, html5 player vflset
[youtube] {133} signature length 107, html5 player vflset
[youtube] {242} signature length 107, html5 player vflset
[youtube] {395} signature length 107, html5 player vflset
[youtube] {160} signature length 107, html5 player vflset
[youtube] {278} signature length 107, html5 player vflset
[youtube] {394} signature length 103, html5 player vflset
[youtube] {140} signature length 103, html5 player vflset
[youtube] {249} signature length 103, html5 player vflset
[youtube] {250} signature length 107, html5 player vflset
[youtube] {251} signature length 107, html5 player vflset
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r3---sn-aigl6nek.googlevideo.com/videoplayback?expire=1585411736&ei=OCJ_XqDHJdu0mLAP8vCtkAI&ip=XXXX&id=o-ALKCRrgOc1O2XIF5Otzb8317he9kOYqTonmjpAJwYk2A&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=5D&mm=31%2C26&mn=sn-aigl6nek%2Csn-c0q7lnsl&ms=au%2Conr&mv=m&mvi=2&pl=24&initcwndbps=240000&vprv=1&mime=video%2Fmp4&gir=yes&clen=92310990&dur=287.245&lmt=1556978070239260&mt=1585390109&fvip=3&keepalive=yes&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABSNjpQwRQIgUVBU-WhiYDd3zHM-hCHfYtqD1DAsNkpQ3-RMDdD06TYCIQDgxd-47HvTYRzS8NENgHBl56qQJOYo2Fnie7Y8Yt0THg%3D%3D&sig=hkGMwRgIhANKtwBc4RQPKRytUZa6XbYfS37PnQUKAmY1kjEVeRhBnAiEAoa8FJHkcKfDid=QGfDfMp87wRyyuT1Niv8DukQED6f8&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

## Description

Hello! Since about 1 week, I've been observing a new problem with youtube dl.

Randomly, my youtube videos don't download with a 403 error.

I think it's not a problem of ip blocking because when I retry a download just after this error, it works. Also, a curl to the youtube url doesn't indicate any error.

Any idea to fix this?

**Comment by titirino159** [comment]
Why did you close the subject? Is it possible to know what this error means? Thank you

**Comment by heshang233** [comment]
I have this problem, the same version

**Comment by titirino159** [comment]
> I have this problem, the same version

Hey! Can you create a new post with the details and mentioning this post so that it can be seen by the devs?

**Comment by MSauce** [comment]
Hey - I'm giving this another go on #24713. Seems to be only with signature videos.
