### ISSUE TITLE
if use --merge-output-format, ERROR:   Stream #1:0 -> #0:1 (copy) is occured.

### ISSUE THREAD

**Issue by mtnmso1** [ytdl-org/youtube-dl#24529]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: ['-f', 'bestvideo+bestaudio', '--merge-output-format', 'mp4', '--audio-quality', '0']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=CMvep1V6rZQ']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-03-27-e34157f, ffprobe git-2020-03-27-e34157f
[debug] Proxy map: {}
[youtube] CMvep1V6rZQ: Downloading webpage
[youtube] {18} signature length 108, html5 player vfl2qqKyf
[youtube] {137} signature length 108, html5 player vfl2qqKyf
[youtube] {248} signature length 108, html5 player vfl2qqKyf
[youtube] {136} signature length 104, html5 player vfl2qqKyf
[youtube] {247} signature length 104, html5 player vfl2qqKyf
[youtube] {135} signature length 108, html5 player vfl2qqKyf
[youtube] {244} signature length 108, html5 player vfl2qqKyf
[youtube] {134} signature length 108, html5 player vfl2qqKyf
[youtube] {243} signature length 108, html5 player vfl2qqKyf
[youtube] {133} signature length 108, html5 player vfl2qqKyf
[youtube] {242} signature length 108, html5 player vfl2qqKyf
[youtube] {160} signature length 108, html5 player vfl2qqKyf
[youtube] {278} signature length 108, html5 player vfl2qqKyf
[youtube] {140} signature length 108, html5 player vfl2qqKyf
[youtube] {249} signature length 108, html5 player vfl2qqKyf
[youtube] {250} signature length 108, html5 player vfl2qqKyf
[youtube] {251} signature length 108, html5 player vfl2qqKyf
[debug] Invoking downloader on 'https://r8---sn-ji0c0uxa-obvz.googlevideo.com/videoplayback?expire=1585511801&ei=GamAXu_7IoaZ4ALbrp3oDA&ip=14.133.186.20&id=o-ALeILdWgHMc73FWLScBR6_ZKExlqQYPfLLIuIIt1Zi96&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=2N&mm=31%2C29&mn=sn-ji0c0uxa-obvz%2Csn-3pm7sn7r&ms=au%2Crdu&mv=m&mvi=7&pl=16&initcwndbps=1161250&vprv=1&mime=video%2Fmp4&gir=yes&clen=77571679&dur=274.107&lmt=1581762101795462&mt=1585490072&fvip=2&keepalive=yes&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABSNjpQwRAIgdmVveFALSquVqQcWQ20JrVyjjq3768I9P69XrqqZ1bQCIByXbq4ID3Au2gTdlNdi1kv0SPDVQlJDQ8GRtm_fimvP&sig=ADKhkGMwRgIhAIZ6UQMWz5y4kqqttP3kbfW2rM8rMkRLoiwgZurFYUx6AiEAtX4N7Qo8IlGnpCVtA1-_yxDYvgcyRy190NaNRBQ5iYw=&ratebypass=yes'
[download] Destination: 緑黄色社会 『Shout Baby』Live Video (TVアニメ『僕のヒーローアカデミア』4期「文化祭編」EDテーマ _ 「MY HERO ACADEMIA」Ending Theme)-CMvep1V6rZQ.f137.mp4
[download] 100% of 73.98MiB in 00:02
[debug] Invoking downloader on 'https://r8---sn-ji0c0uxa-obvz.googlevideo.com/videoplayback?expire=1585511801&ei=GamAXu_7IoaZ4ALbrp3oDA&ip=14.133.186.20&id=o-ALeILdWgHMc73FWLScBR6_ZKExlqQYPfLLIuIIt1Zi96&itag=251&source=youtube&requiressl=yes&mh=2N&mm=31%2C29&mn=sn-ji0c0uxa-obvz%2Csn-3pm7sn7r&ms=au%2Crdu&mv=m&mvi=7&pl=16&initcwndbps=1161250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=4303572&dur=274.121&lmt=1581761005099320&mt=1585490072&fvip=2&keepalive=yes&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABSNjpQwRAIgdmVveFALSquVqQcWQ20JrVyjjq3768I9P69XrqqZ1bQCIByXbq4ID3Au2gTdlNdi1kv0SPDVQlJDQ8GRtm_fimvP&sig=ADKhkGMwRQIhAOSpneT7KBfc_ZLF_N2mnJRfm3X9qjgFx65gtSgJRCSWAiBug4mC56HMyIRgB_8tn8NXlSv8z4mmT2ibct5qyq7piQ==&ratebypass=yes'
[download] Destination: 緑黄色社会 『Shout Baby』Live Video (TVアニメ『僕のヒーローアカデミア』4期「文化祭編」EDテーマ _ 「MY HERO ACADEMIA」Ending Theme)-CMvep1V6rZQ.f251.webm
[download] 100% of 4.10MiB in 00:00
[ffmpeg] Merging formats into "緑黄色社会 『Shout Baby』Live Video (TVアニメ『僕のヒーローアカデミア』4期「文化祭編」EDテーマ _ 「MY HERO ACADEMIA」Ending Theme)-CMvep1V6rZQ.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:緑黄色社会 『Shout Baby』Live Video (TVアニメ『僕のヒーローアカデミア』4期「文化祭編」EDテーマ _ 「MY HERO ACADEMIA」Ending Theme)-CMvep1V6rZQ.f137.mp4" -i "file:緑 黄色社会 『Shout Baby』Live Video (TVアニメ『僕のヒーローアカデミア』4期「文化祭編」EDテーマ _ 「MY HERO ACADEMIA」Ending Theme)-CMvep1V6rZQ.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:緑黄色社会 『Shout Baby』Live Video (TVアニメ『僕のヒーローアカデミア』4期「文化祭編」EDテーマ _ 「MY HERO ACADEMIA」Ending Theme)-CMvep1V6rZQ.temp.mp4"
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2065, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\postprocessor\ffmpeg.py", line 512, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)
```

## Description

I tried to download this video:https://www.youtube.com/watch?v=CMvep1V6rZQ
Command line:youtube-dl -v https://www.youtube.com/watch?v=CMvep1V6rZQ
I use config.txt and contents is 
```
-f bestvideo+bestaudio
--merge-output-format mp4
--audio-quality 0
```

I tried to discover solution so I executed ffmpeg command. this is a result.

```
ffmpeg version git-2020-03-27-e34157f Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 42.101 / 56. 42.101
  libavcodec     58. 76.100 / 58. 76.100
  libavformat    58. 42.100 / 58. 42.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 77.100 /  7. 77.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:緑黄色社会 『Shout Baby』Live Video (TVアニメ『僕のヒーローアカデミア』4期「文化祭編」EDテーマ _ 「MY HERO ACADEMIA」Ending Theme)-CMvep1V6rZQ.f137.mp4':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6avc1mp41
    creation_time   : 2020-02-15T10:18:22.000000Z
  Duration: 00:04:34.11, start: 0.000000, bitrate: 2263 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2020-02-15T10:18:22.000000Z
      handler_name    : ISO Media file produced by Google Inc.
Input #1, matroska,webm, from 'file:緑黄色社会 『Shout Baby』Live Video (TVアニメ『僕のヒーローアカデミア』4期「文化祭編」EDテーマ _ 「MY HERO ACADEMIA」Ending Theme)-CMvep1V6rZQ.f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:04:34.12, start: -0.007000, bitrate: 125 kb/s
    Stream #1:0(jpn): Audio: opus, 48000 Hz, stereo, fltp (default)
[mp4 @ 06d4d3c0] track 1: codec frame size is not set
[mp4 @ 06d4d3c0] opus in MP4 support is experimental, add '-strict -2' if you want to use it.
Could not write header for output file #0 (incorrect codec parameters ?): Experimental feature
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)

```

Maybe ffmpeg requires -strict option.But youtube-dl application is not specified so error is occurred.

**Comment by dstftw** [comment]
mp4+webm can't be merged into mp4.

**Comment by adams-family** [comment]
I confirm the same problem. Is there a list of which formats can be converted to mp4?

**Comment by EthanSK** [comment]
any updates on where we can find a list of compatible formats?
