### ISSUE TITLE
can't download from youtube (video not found)

### ISSUE THREAD

**Issue by seductiveapps** [ytdl-org/youtube-dl#24523]
rene@crow:~/data1/2020 music/2020 magic playlist$ youtube-dl --ignore-errors --extract-audio --audio-format mp3 --verbose https://www.youtube.com/playlist?list=PLN9FZ3ijwb1FZgDJhvjoOHO9S93Tg6Opy
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-errors', '--extract-audio', '--audio-format', 'mp3', '--verbose', 'https://www.youtube.com/playlist?list=PLN9FZ3ijwb1FZgDJhvjoOHO9S93Tg6Opy']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.6.9 (CPython) - Linux-5.3.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6-0ubuntu0.18.04.1, ffprobe 3.4.6-0ubuntu0.18.04.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PLN9FZ3ijwb1FZgDJhvjoOHO9S93Tg6Opy: Downloading webpage
[download] Downloading playlist: 2020 magic playlist
[youtube:playlist] PLN9FZ3ijwb1FZgDJhvjoOHO9S93Tg6Opy: Downloading page #1
[youtube:playlist] playlist 2020 magic playlist: Downloading 118 videos
[download] Downloading video 1 of 118
[youtube] NeQM1c-XCDc: Downloading webpage
[youtube] NeQM1c-XCDc: Downloading embed webpage
[youtube] NeQM1c-XCDc: Refetching age-gated info webpage
ERROR: NeQM1c-XCDc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1627, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: NeQM1c-XCDc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[download] Downloading video 2 of 118
[youtube] QObZCmp46eY: Downloading webpage
[youtube] QObZCmp46eY: Downloading video info webpage
ERROR: QObZCmp46eY: YouTube said: This video is unavailable.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1623, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: QObZCmp46eY: YouTube said: This video is unavailable.

[download] Downloading video 3 of 118
[youtube] LXPCR5JgJUg: Downloading webpage
[youtube] LXPCR5JgJUg: Downloading video info webpage
ERROR: LXPCR5JgJUg: YouTube said: This video is unavailable.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1623, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: LXPCR5JgJUg: YouTube said: This video is unavailable.

[download] Downloading video 4 of 118
[youtube] 0FiuDrfu2D8: Downloading webpage
[youtube] 0FiuDrfu2D8: Downloading video info webpage
ERROR: 0FiuDrfu2D8: YouTube said: This video is unavailable.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1623, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: 0FiuDrfu2D8: YouTube said: This video is unavailable.

[download] Downloading video 5 of 118
[youtube] jhdFe3evXpk: Downloading webpage
[youtube] jhdFe3evXpk: Downloading video info webpage
ERROR: jhdFe3evXpk: YouTube said: This video is unavailable.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1623, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: jhdFe3evXpk: YouTube said: This video is unavailable.

[download] Downloading video 6 of 118
[youtube] cF3OWCYLLVQ: Downloading webpage
[youtube] cF3OWCYLLVQ: Downloading video info webpage
^C
ERROR: Interrupted by user

**Comment by ChillerDragon** [comment]
Well thats not a video. It is a playlist. Maybe try the individual videos.
