### ISSUE TITLE
Downloading from mail.ru seems broken

### ISSUE THREAD

**Issue by Megavoxel01** [ytdl-org/youtube-dl#24530]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --proxy socks5://127.0.0.1:10808 --no-cache-dir -f "1080p"--merge-output-format mp4 "https://my.mail.ru/community/gotivim.mm/video/_groupvideo/288.html" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--proxy', 'socks5://127.0.0.1:10808', '--no-cache-dir', '-f', '1080p', '--merge-output-format', 'mp4', 'https://my.mail.ru/community/gotivim.mm/video/_groupvideo/288.html', '-v']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.7.4 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {'http': 'socks5://127.0.0.1:10808', 'https': 'socks5://127.0.0.1:10808'}
[mailru] community/gotivim.mm/_groupvideo/288: Downloading webpage
[mailru] community/gotivim.mm/_groupvideo/288: Downloading video meta JSON
[debug] Invoking downloader on 'http://cdn7.my.mail.ru/hv/62465402.mp4?slave[]=s%3Ahttp%3A%2F%2Fvideo-cephgw1.i%3A8003%2Frados3%2F62465402-hv&p=f&expire_at=1585504800&touch=1499087450&reg=188&sign=db04c5f100a3c50f30e86d49a6ab5caa1b32f314'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "c:\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "c:\python37\lib\site-packages\youtube_dl\downloader\common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "c:\python37\lib\site-packages\youtube_dl\downloader\http.py", line 341, in real_download
    establish_connection()
  File "c:\python37\lib\site-packages\youtube_dl\downloader\http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "c:\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "c:\python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "c:\python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

## Description

It seems like mail.ru has updated their online player recently and you can't access their cdn directly to download video. Accessing CDN through browser directly returns permission denied errors as well. I've tried adding user agent and cookies but doesn't help. Is there any way to bypass this restriction? Thanks in advance.

**Comment by comsomisha** [comment]
You should see the #23458:
Let"s try:
youtube-dl --add-header 'Referer: https://my.mail.ru/' [DASH_URL]

**Comment by goonis** [comment]
Yes, with --add-header "Cookie:video_key=da498ac65a8271fe4e5b489afff638e.........." and even without any referers download works fine.
Cookie I've got from Google Chrome for site my.mail.ru

**Comment by comsomisha** [comment]
> Yes, with --add-header "Cookie:video_key=da498ac65a8271fe4e5b489afff638e.........." and even without any referers download works fine.
> Cookie I've got from Google Chrome for site my.mail.ru
This way works fine.
