### ISSUE TITLE
thisoldhouse.com Video ID problem

### ISSUE THREAD

**Issue by AndrewMBL** [ytdl-org/youtube-dl#24548]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.03.24**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v https://www.thisoldhouse.com/21083431/seaside-transformation-the-westerly-project
[debug] System config: []
[debug] User config: ['-o', 'C:\\Users\\Andrew\\Downloads\\%(title)s - (%(duration)ss) [%(resolution)s] [%(id)s].%(ext)s', '--prefer-ffmpeg', '--merge-output-format', 'mkv', '--embed-sub', '--all-subs', '--convert-subs', 'srt', '--add-metadata', '-v']
[debug] Custom config: []
[debug] Command-line args: ['https://www.thisoldhouse.com/21083431/seaside-transformation-the-westerly-project']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2
[debug] Proxy map: {}
[ThisOldHouse] seaside-transformation-the-westerly-project: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\thisoldhouse.py", line 42, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Another(?) this old house video URL, where the extractor fails to find the Video URL, providing a direct link to the video file works correctly e.g. ```https://www.thisoldhouse.com/videos/zype/5e2b70e95216cc0001615120``` 

I think it may be this section of youtube-dl/youtube_dl/extractor/thisoldhouse.py that isn't working:
```
video_id = self._search_regex(
    r'<iframe[^>]+src=[\'"](?:https?:)?//thisoldhouse\.chorus\.build/videos/zype/([0-9a-f]{24})',
    webpage, 'video id')
```

if replaced with this:
```
video_id = self._search_regex(
    r'<iframe[^>]+src=[\'"](?:https?:)?//(?:www\.|)thisoldhouse(?:\.chorus\.build|\.com)/videos/zype/([0-9a-f]{24})',
    webpage, 'video id')
```
It now validated correctly on older URL's 
```
<iframe src="https://thisoldhouse.chorus.build/videos/zype/5e33baec27d2e50001d5f52f
```
and newer ones
```
<iframe src="https://www.thisoldhouse.com/videos/zype/5e2b70e95216cc0001615120
```
I think I successfully submitted a Pull request for this, but i'm not experienced with git.

**Comment by AndrewMBL** [comment]
See this pull request https://github.com/ytdl-org/youtube-dl/pull/24549
