### ISSUE TITLE
[twitch] OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by pva** [ytdl-org/youtube-dl#24575]
## Checklist
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v https://www.twitch.tv/videos/576778836
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.twitch.tv/videos/576778836']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.7.6 (CPython) - Linux-5.4.24-x86_64-Intel-R-_Core-TM-_i7-3520M_CPU_@_2.90GHz-with-gentoo-2.6
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[twitch:vod] 576778836: Downloading my vod info JSON
[twitch:vod] 576778836: Downloading vod access token
[twitch:vod] 576778836: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://d2nvs31859zcd8.cloudfront.net/abecf4b0970e9ddda88d_kinkmoscow_983036369_61498773/chunked/index-dvr.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 312
[download] Destination: Сегодня 5 день - контроль положения тела модели при грудных обвязках, разбор физиологии (база), разные варианты грудных обвязок -v576778836.mp4
ERROR: unable to open for writing: [Errno 36] File name too long: 'Сегодня 5 день - контроль положения тела модели при грудных обвязках, разбор физиологии (база), разные варианты грудных обвязок -v576778836.mp4.part-Frag0.part'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 250, in download
    ctx.tmpfilename, ctx.open_mode)
  File "/usr/lib/python3.7/site-packages/youtube_dl/utils.py", line 2046, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
OSError: [Errno 36] File name too long: 'Сегодня 5 день - контроль положения тела модели при грудных обвязках, разбор физиологии (база), разные варианты грудных обвязок -v576778836.mp4.part-Frag0.part'
```

## Description

Most filesystems have limit of 255 bytes on the filename. Since Unicode takes twice (or even more) in bytes it's very easy to overcome this limit.

**Comment by pva** [comment]
I'm sorry but why is is ticket a duplicate? As I see there are tickets for youtube and vimeo but I failed to find for twitch. And as for twitch it's easy to fix issue by stripping length of title.

**Comment by sputnick-dev** [comment]
Hi,

what I does in a bash wrapper script :  https://github.com/sputnick-dev/youtube-dl-wrapper/blob/master/y
