### ISSUE TITLE
Hotstar DRM Protection Problem...Help me for this

### ISSUE THREAD

**Issue by Abhijit47** [ytdl-org/youtube-dl#24585]
F:\python\youtube-dl>youtube-dl -v https://www.hotstar.com/in/tv/special-ops/s-2559/kaagaz-ke-phool/1260022902
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.hotstar.com/in/tv/special-ops/s-2559/kaagaz-ke-phool/1260022902']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-02-13-6d37ca8, ffprobe git-2020-02-13-6d37ca8
[debug] Proxy map: {}
[hotstar] 1260022902: Downloading webpage
ERROR: This video is DRM protected.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\hotstar.py", line 119, in _real_extract
youtube_dl.utils.ExtractorError: This video is DRM protected.

F:\python\youtube-dl>youtube-dl -U
youtube-dl is up-to-date (2020.03.24)

F:\python\youtube-dl>

**Comment by Abhijit47** [comment]
plz help me ...what error with me
