### ISSUE TITLE
I can't download from dmax

### ISSUE THREAD

**Issue by siati38** [ytdl-org/youtube-dl#24602]
I am trying to download this "https://es.dplay.com/dmax/grandes-imperios/temporada-1-episodio-6/", but the web has changed and now it asks for username and password, I have tried to pass the credentials to it but it seems will not work:

root@DESKTOP-MT422A9:/mnt/d/Documentales/Grandes Imperios# youtube-dl --username myuser@gmail.com --password Mypass -v -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' "https://es.dplay.com/dmax/grandes-imperios/temporada-1-episodio-6/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'-v', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', u'https://es.dplay.com/dmax/grandes-imperios/temporada-1-episodio-6/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[debug] Using fake IP 88.14.159.118 (ES) as X-Forwarded-For.
[DPlay] grandes-imperios/temporada-1-episodio-6: Downloading token
[DPlay] grandes-imperios/temporada-1-episodio-6: Downloading JSON metadata
[DPlay] grandes-imperios/temporada-1-episodio-6: Downloading JSON metadata
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/dplay.py", line 163, in _get_disco_api_info
    display_id, headers=headers)['data']['attributes']['streaming']
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 892, in _download_json
    expected_status=expected_status)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 870, in _download_json_handle
    expected_status=expected_status)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 660, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 645, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/dplay.py", line 247, in _real_extract
    url, display_id, host, 'dplay' + country, country)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/dplay.py", line 172, in _get_disco_api_info
    self.raise_login_required()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 936, in raise_login_required
    expected=True)
ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.

**Comment by siati38** [comment]
why closed, duplicated who?
