### ISSUE TITLE
ndr.de broken again

### ISSUE THREAD

**Issue by philiip11** [ytdl-org/youtube-dl#24617]
Hi there!

I tried to download Büttenwarder op Platt: Reisefieber from this[1] page, but it does not work. If I however use the .m3u8-URL[2] directly (found via Chrome Dev Tools), the download works fine.

Seems to be related to #24315, which got closed, but somehow it doesn't work with this page.

Below are the URLs and the output from youtube-dl.
[1] https://www.ndr.de/fernsehen/sendungen/neues_aus_buettenwarder/Buettenwarder-op-Platt-Reisefieber,buettenwarder1848.html
[2] https://ndrod-vh.akamaihd.net/i/ndr/2018/1031/TV-20181031-1253-5200.,lo,hi,hq,hd,.mp4.csmil/index_3_av.m3u8?null=0

Output:
```
E:\Serien\2D\Büttenwarder op Platt>youtube-dl https://www.ndr.de/fernsehen/sendungen/neues_aus_buettenwarder/Buettenwarder-op-Platt-Reisefieber,buettenwarder1848.html -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.ndr.de/fernsehen/sendungen/neues_aus_buettenwarder/Buettenwarder-op-Platt-Reisefieber,buettenwarder1848.html', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp65001, pref cp1252
[debug] youtube-dl version 2020.01.15
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-04-01-afa5e38, ffprobe git-2020-04-01-afa5e38
[debug] Proxy map: {}
[ndr] Buettenwarder-op-Platt-Reisefieber: Downloading webpage
ERROR: Unable to extract embed URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\extractor\ndr.py", line 22, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\extractor\ndr.py", line 90, in _extract_embed
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\extractor\common.py", line 1135, in _html_search_meta
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\extractor\common.py", line 1014, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract embed URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by kiersch** [comment]
It definitely works with version 2020.03.24. Your output shows "youtube-dl version 2020.01.15" have you since updated?

**Comment by philiip11** [comment]
Oh, thank you. I thought I had updated, but apparently I did not. 
You are right, with 2020.03.24 it works as expected.
