### ISSUE TITLE
[Mitele.es] Exception while extracting metadata of recent episodes

### ISSUE THREAD

**Issue by Roman2K** [ytdl-org/youtube-dl#24624]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.mitele.es/programas-tv/first-dates/temporada-3/Programa-1102-40_1008349075005/player/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.7.5 (CPython) - Linux-5.3.0-45-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2
[debug] Proxy map: {}
[MiTele] Programa-1102-40_1008349075005: Downloading webpage
[Ooyala] e30060fe-912a-4f71-8a94-4054db4b2f30: Downloading JSON metadata
Traceback (most recent call last):
  File "/home/roman/.local/bin/youtube-dl", line 10, in <module>
    sys.exit(main())
  File "/home/roman/.local/lib/python3.7/site-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/home/roman/.local/lib/python3.7/site-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/roman/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/roman/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/roman/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 875, in process_ie_result
    extra_info=extra_info, download=False, process=False)
  File "/home/roman/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/roman/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/roman/.local/lib/python3.7/site-packages/youtube_dl/extractor/ooyala.py", line 173, in _real_extract
    return self._extract(content_tree_url, embed_code, domain, supportedformats, embed_token)
  File "/home/roman/.local/lib/python3.7/site-packages/youtube_dl/extractor/ooyala.py", line 28, in _extract
    metadata = content_tree[list(content_tree)[0]]
IndexError: list index out of range
```

## Description

When downloading episodes of First Dates [on Mitele.es](https://www.mitele.es/programas-tv/first-dates/), I get the above error *only* starting from [episode 1102](https://www.mitele.es/programas-tv/first-dates/temporada-3/Programa-1102-40_1008349075005/player/) and newer. From 1101 and below, they download fine. They changed something after 1101.

**Comment by felisucoibi** [comment]
Me too having problems with new things of mitele.es 
Example: https://www.mitele.es/series-online/verdades-secretas/temporada-1/capitulo-1-40_1008367075002/player/

**Comment by felisucoibi** [comment]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2019, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 875, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ooyala.py", line 173, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ooyala.py", line 28, in _extract
IndexError: list index out of range

**Comment by felisucoibi** [comment]
Still not fixed, not any pr, and probably fix is easy. :( btw almost all of the spanish websites are broken in yotuube-dl:
atresplayer
mitele
es.dplay.com
rtve.es infantil

**Comment by Rukko** [comment]
Still happening in version 2020.05.08

I tried to fix it, but did not work.

**Comment by Rukko** [comment]
Attaching the results from download a simple link and the execution of tests.

[error.log](https://github.com/ytdl-org/youtube-dl/files/4673535/error.log)

```
youtube-dl https://www.mitele.es/programas-tv/first-dates/temporada-3/programa-1105-40_1008415075028/player/

[MiTele] programa-1105-40_1008415075028: Downloading webpage
[Ooyala] a1e06228-855d-410d-935f-644e3cf88b57: Downloading JSON metadata
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\youtube-dl.exe\__main__.py", line 7, in <module>
  File "c:\python27\lib\site-packages\youtube_dl\__init__.py", line 474, in main
    _real_main(argv)
  File "c:\python27\lib\site-packages\youtube_dl\__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 875, in process_ie_result
    extra_info=extra_info, download=False, process=False)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\ooyala.py", line 173, in _real_extract
    return self._extract(content_tree_url, embed_code, domain, supportedformats, embed_token)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\ooyala.py", line 28, in _extract
    metadata = content_tree[list(content_tree)[0]]
IndexError: list index out of range
```

[tests.log](https://github.com/ytdl-org/youtube-dl/files/4673536/tests.log)
```
python test/test_download.py TestDownload.test_MiTele
[MiTele] 57b0dfb9c715da65618b4afa: Downloading webpage
[Ooyala] FhYW1iNTE6J6H7NkQRIEzfne6t2quqPg: Downloading JSON metadata
[Ooyala] FhYW1iNTE6J6H7NkQRIEzfne6t2quqPg: Downloading JSON metadata
[Ooyala] FhYW1iNTE6J6H7NkQRIEzfne6t2quqPg: Downloading m3u8 information
ERROR: Failed to download m3u8 information: HTTP Error 404: Not Found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Jona\Desktop\youtube-dl\youtube_dl\extractor\common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Jona\Desktop\youtube-dl\youtube_dl\YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\Jona\Desktop\youtube-dl\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Jona\Desktop\youtube-dl\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Jona\Desktop\youtube-dl\youtube_dl\extractor\ooyala.py", line 173, in _real_extract
    return self._extract(content_tree_url, embed_code, domain, supportedformats, embed_token)
  File "C:\Users\Jona\Desktop\youtube-dl\youtube_dl\extractor\ooyala.py", line 62, in _extract
    m3u8_id='hls', fatal=False))
  File "C:\Users\Jona\Desktop\youtube-dl\youtube_dl\extractor\common.py", line 1618, in _extract_m3u8_formats
    fatal=fatal, data=data, headers=headers, query=query)
  File "C:\Users\Jona\Desktop\youtube-dl\youtube_dl\extractor\common.py", line 660, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "C:\Users\Jona\Desktop\youtube-dl\youtube_dl\extractor\common.py", line 647, in _request_webpage
    self._downloader.report_warning(errmsg)
  File "C:\Users\Jona\Desktop\youtube-dl\test\helper.py", line 271, in _report_warning
    real_warning(w)
  File "test/test_download.py", line 52, in report_warning
    raise ExtractorError(message)
ExtractorError: Failed to download m3u8 information: HTTP Error 404: Not Found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

E
======================================================================
ERROR: test_MiTele (__main__.TestDownload) [Ooyala]:
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_download.py", line 159, in test_template
    force_generic_extractor=params.get('force_generic_extractor', False))
  File "C:\Users\Jona\Desktop\youtube-dl\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Jona\Desktop\youtube-dl\youtube_dl\YoutubeDL.py", line 875, in process_ie_result
    extra_info=extra_info, download=False, process=False)
  File "C:\Users\Jona\Desktop\youtube-dl\youtube_dl\YoutubeDL.py", line 820, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\Jona\Desktop\youtube-dl\youtube_dl\YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Jona\Desktop\youtube-dl\youtube_dl\YoutubeDL.py", line 595, in trouble
    raise DownloadError(message, exc_info)
DownloadError: ERROR: Failed to download m3u8 information: HTTP Error 404: Not Found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

----------------------------------------------------------------------
Ran 1 test in 2.268s

FAILED (errors=1)
```

**Comment by felisucoibi** [comment]
what @djmoren did makes old links to work again but new ones require registration. Maybe we need cookies.txt to work.
