### ISSUE TITLE
Include site credential during development

### ISSUE THREAD

**Issue by nixklai** [ytdl-org/youtube-dl#24632]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I am trying to implement an extractor for [Microsoft Stream](https://www.microsoftstream.com/), which requires users to log in to access any video. Is it possible to pass the username-password pair and/or the `.netrc` file to the extractor during development? I have tried the following:

1. Defining a `.netrc` file without the `--netrc` argument
2. Defining a `_netrc` file without the `--netrc` argument
3. Defining a `.netrc` file with the `--netrc` argument
4. Defining a `_netrc` file with the `--netrc` argument
5. Defining the credential with the `--username` and `--password` arguments

A workaround I can think of it to hard-code a testing credential in [`NewSiteIE._get_login_info()`](https://github.com/ytdl-org/youtube-dl/blob/eda86b4335a464c2744adb537f1296eff24f5bde/youtube_dl/extractor/common.py#L1007) during development and remove it before pushing it GitHub. Am I missing something in the documentation?

I am developing the extractor on my Windows 10 laptop running Python 3.7.6, based on commit https://github.com/ytdl-org/youtube-dl/commit/049c0486bbd57a9bb5fb5a6a5eeff82fd4ac03ff

Many thanks!

### Output of defining `.netrc` or `_netrc` file without `netrc` argument
```
PS D:\Users\user\Code\youtube-dl> python test/test_download.py TestDownload.test_MicrosoftStream   
[microsoftstream] c883c6a5-9895-4900-9a35-62f4b5d506c9: Downloading webpage
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "D:\Users\user\Code\youtube-dl\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "D:\Users\user\Code\youtube-dl\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "D:\Users\user\Code\youtube-dl\youtube_dl\extractor\microsoftstream.py", line 135, in _real_extract
    return self.raise_login_required()
  File "D:\Users\user\Code\youtube-dl\youtube_dl\extractor\common.py", line 936, in raise_login_required
    expected=True)
youtube_dl.utils.ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.

E
======================================================================
ERROR: test_MicrosoftStream (__main__.TestDownload):
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\user\Code\youtube-dl\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "D:\Users\user\Code\youtube-dl\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "D:\Users\user\Code\youtube-dl\youtube_dl\extractor\microsoftstream.py", line 135, in _real_extract
    return self.raise_login_required()
  File "D:\Users\user\Code\youtube-dl\youtube_dl\extractor\common.py", line 936, in raise_login_required
    expected=True)
youtube_dl.utils.ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test/test_download.py", line 159, in test_template
    force_generic_extractor=params.get('force_generic_extractor', False))
  File "D:\Users\user\Code\youtube-dl\youtube_dl\YoutubeDL.py", line 820, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "D:\Users\user\Code\youtube-dl\youtube_dl\YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "D:\Users\user\Code\youtube-dl\youtube_dl\YoutubeDL.py", line 595, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.

----------------------------------------------------------------------
Ran 1 test in 1.163s

FAILED (errors=1)
```

### Defining a `_netrc` or `.netrc` file with the `--netrc` argument
```
PS D:\Users\user\Code\youtube-dl> python test/test_download.py --netrc TestDownload.test_MicrosoftStream
usage: test_download.py [-h] [-v] [-q] [--locals] [-f] [-c] [-b]
                        [-k TESTNAMEPATTERNS]
                        [tests [tests ...]]
test_download.py: error: unrecognized arguments: --netrc
```

### Defining the username-password pair with the `--username` and `--password` arguments
```
PS D:\Users\user\Code\youtube-dl> python test/test_download.py --username [username] --password [password] TestDownload.test_MicrosoftStream
usage: test_download.py [-h] [-v] [-q] [--locals] [-f] [-c] [-b]
                        [-k TESTNAMEPATTERNS]
                        [tests [tests ...]]
test_download.py: error: unrecognized arguments: --username --password [password] TestDownload.test_MicrosoftStream
```

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl/blob/049c0486bbd57a9bb5fb5a6a5eeff82fd4ac03ff/youtube_dl/YoutubeDL.py#L143-L144

in test's `params`.
