### ISSUE TITLE
WinError 10060

### ISSUE THREAD

**Issue by numlockkey** [ytdl-org/youtube-dl#24645]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\T5400-3>youtube-dl -v -i -f 22/(bestvideo+(140/bestaudio))/best -o "d:\YT Downloads/%(title)s.%(ext)s" https://www.youtube.com/watch?v=k5De0CP04EI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-i', '-f', '22/(bestvideo+(140/bestaudio))/best', '-o', 'd:\\YT Downloads/%(title)s.%(ext)s', 'https://www.youtube.com/watch?v=k5De0CP04EI']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[youtube] k5De0CP04EI: Downloading webpage
[debug] Invoking downloader on 'https://r3---sn-p5qlsns6.googlevideo.com/videoplayback?expire=1586158139&ei=24WKXp-8A43khwa01KjQBA&ip=216.55.242.167&id=o-AHdDP8-tiFJxer9pN7ERzqGuGfomWlyr5JGg3bu9EtLJ&itag=22&source=youtube&requiressl=yes&mh=68&mm=31%2C26&mn=sn-p5qlsns6%2Csn-ab5sznlk&ms=au%2Conr&mv=m&mvi=2&pl=20&initcwndbps=3665000&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=229.413&lmt=1471743002052666&mt=1586136460&fvip=3&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AJpPlLswRQIgTpKwpXBNXfExsmrr6yI1MNBHo8i6Q4Uw-OyADK2zO1oCIQDoHObG20PtctDPiYECVxEPH6xmpdVwH4DNZOOi6os3dA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRAIgTUIjt1pdHO0iuFAeblNd-2uT8tTsEsdPbbw7DLqzufsCIHg8vJmx5CapmPD7lXmx1u2rDKUz4Bj73rMO5Y-yNIJy'
ERROR: unable to download video data: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1279, in connect
  File "C:\Python\Python34\lib\http\client.py", line 871, in connect
  File "C:\Python\Python34\lib\socket.py", line 516, in create_connection
  File "C:\Python\Python34\lib\socket.py", line 507, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1926, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\utils.py", line 2728, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
```

## Description

Trying to download this file: 

youtube-dl -v -i -f 22/(bestvideo+(140/bestaudio))/best -o "d:\YT Downloads/%(title)s.%(ext)s" https://www.youtube.com/watch?v=k5De0CP04EI

It fails with this error:  [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The same file downloads OK with Internet Download Manager.

**Comment by dstftw** [comment]
Network issue on your side for selected format.
