### ISSUE TITLE
Brightcove URL variant not working.

### ISSUE THREAD

**Issue by sevaran** [ytdl-org/youtube-dl#24658]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[04/06/20 19:40:39] [debug] System config: []
[04/06/20 19:40:39] [debug] User config: []
[04/06/20 19:40:39] [debug] Custom config: []
[04/06/20 19:40:39] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\Curty\\Desktop\\%(title)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', '--write-srt', '--sub-lang', 'en', '--verbose', 'https://metoperafree.brightcove.services/?videoId=6146555333001']
[04/06/20 19:40:39] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[04/06/20 19:40:39] [debug] youtube-dl version 2020.03.24
[04/06/20 19:40:39] [debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[04/06/20 19:40:39] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[04/06/20 19:40:39] [debug] Proxy map: {}
[04/06/20 19:40:39] WARNING: Falling back on generic information extractor.
[04/06/20 19:40:39] ERROR: Unsupported URL: https://metoperafree.brightcove.services/?videoId=6146555333001
[04/06/20 19:40:39] Traceback (most recent call last):
[04/06/20 19:40:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
[04/06/20 19:40:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
[04/06/20 19:40:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\generic.py", line 3352, in _real_extract
[04/06/20 19:40:39] youtube_dl.utils.UnsupportedError: Unsupported URL: https://metoperafree.brightcove.services/?videoId=6146555333001
[04/06/20 19:40:39] 

## Description

WRITE DESCRIPTION HERE

This version of the brightcove URL isn't working. Is it copy protected? Their URLs have worked for the last few weeks but this one won't work, so I'm unsure.

https://metoperafree.brightcove.services/?videoId=6146555333001

**Comment by OmarWKH** [comment]
The website has the info needed by youtube-dl but the new URL format is not recognized.

The [recognized format](https://github.com/ytdl-org/youtube-dl/blob/6a6e1a0cd8bacf5a23f731eedaa1783503470227/youtube_dl/extractor/brightcove.py#L340) is https://players.brightcove.net/<`account_id`>/<`player_id`>_<`embed`>/index.html?<`content_type`>Id=<`video_id`>.

From https://metoperafree.brightcove.services/?videoId=6146555333001 we can get `content_type` and `video_id` (video and 6146555333001).

When the page is loaded, it contains the URL https://players.brightcove.net/102076671001/ShNTDWXQ_default/index.min.js which includes `account_id`, `player_id`, and `embed` (102076671001, ShNTDWXQ, and default).

You can put it all together in the recognized format which youtube-dl is able to download: https://players.brightcove.net/102076671001/ShNTDWXQ_default/index.html?videoId=6146555333001

**Comment by sevaran** [comment]
Thanks so much Omar.

**Comment by OmarWKH** [comment]
@sevaran see https://github.com/ytdl-org/youtube-dl/issues/24668
