### ISSUE TITLE
ERROR: Unsupported URL: https://metoperafree.brightcove.services/?videoId=6146555333001

### ISSUE THREAD

**Issue by hurwitzilan** [ytdl-org/youtube-dl#24668]
Hi!
I'm trying to download from https://metoperafree.brightcove.services/?videoId=6146555333001.
I run the following script:
youtube-dl -v  https://metoperafree.brightcove.services/?videoId=6146555333001
And this is the output:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://metoperafree.brightcove.services/?videoId=6146555333001']
[debug] Encodings: locale cp65001, fs mbcs, out cp65001, pref cp65001
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg git-2020-04-03-52523b6, ffprobe git-2020-04-03-52523b6
[debug] Proxy map: {}
[generic] ?videoId=6146555333001: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?videoId=6146555333001: Downloading webpage
[generic] ?videoId=6146555333001: Extracting information
ERROR: Unsupported URL: https://metoperafree.brightcove.services/?videoId=6146555333001
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\generic.py", line 3352, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://metoperafree.brightcove.services/?videoId=6146555333001

I am running V 2020.03.24 which I just downloaded a few days ago :)
Thanks in advance for the amazing work you all do!!

**Comment by sethpjohnson** [comment]
Sucks.. these were working over the weekend

**Comment by OmarWKH** [comment]
> Just put the video ID where the xxxx are

To do this automatically, add this extractor to brightcove.py and import it in extractors.py :
```
class BrightcoveServicesIE(InfoExtractor):
    IE_NAME = 'brightcove:services'
    _VALID_URL = r'https?://.*\.brightcove\.services/\?(?P<content_type>video|playlist)Id=(?P<video_id>\d+)'
    _TESTS = [{
        'url': 'https://metoperafree.brightcove.services/?videoId=6146555333001',
    }]

    def _real_extract(self, url):
        content_type, video_id = re.match(self._VALID_URL, url).groups()
        webpage = self._download_webpage(url, video_id)
        player_url = self._html_search_regex(r'(https://players.brightcove.net/\d+/[^/]+_[^/]+/index.min.js)', webpage, 'player_url')
        valid_player_url = r'https://players.brightcove.net/(?P<account_id>\d+)/(?P<player_id>[^/]+)_(?P<embed>[^/]+)/index.min.js'
        account_id, player_id, embed = re.match(valid_player_url, player_url).groups()
        return {
            '_type': 'url',
            'url': 'https://players.brightcove.net/%s/%s_%s/index.html?%sId=%s' % (account_id, player_id, embed, content_type, video_id),
            'ie_key': 'BrightcoveNew'
        }
```

If anyone wants to make it a proper PR feel free. I might if I have the time.

**Comment by greenjd** [comment]
Code as contributed by OmarWKH in issue thread. I'm afraid I don't know how the testing works but this certainly works with the feeds from https://www.metopera.org for the last 3 days

**Comment by someziggyman** [comment]
This seems to still be a problem with this URL: https://metoperafree.brightcove.services/?videoId=6146559234001

**Comment by superian** [comment]
As of tonight, this no longer works :(

"ERROR: The policy key provided does not permit this account or video, or the requested resource is inactive."

**Comment by superian** [comment]
Ah, it looks like the video number changed at some point. Able to get it now.

**Comment by tactus72** [comment]
This URL https://players.brightcove.net/102076671001/ShNTDWXQ_default/index.html?videoId=6194585151001 (only active for less than 24 hours from now) will load in the browser, but "no matches found" for ytdl. However, when I load the master m3u8 playlist from this URL https://metoperafree.brightcove-services.com/?videoId=6194585151001 I get:
`% youtube-dl --verbose https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/102076671001/0f13b222-5d8d-4fa8-ac5a-769eab1b8c9c/10s/master.m3u8   
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/102076671001/0f13b222-5d8d-4fa8-ac5a-769eab1b8c9c/10s/master.m3u8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] master: Requesting header
WARNING: Could not send HEAD request to https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/102076671001/0f13b222-5d8d-4fa8-ac5a-769eab1b8c9c/10s/master.m3u8: HTTP Error 403: Forbidden
[generic] master: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)`

**Comment by tactus72** [comment]
Because of the 403 errors, does one now have to apply the `--cookies` option?

**Comment by tactus72** [comment]
Nope, cookies did nothing either:
`
% youtube-dl -F https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/102076671001/16c42289-160b-4ace-8c34-3b70acfbef61/10s/master.m3u8 --cookies cookies.txt --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/102076671001/16c42289-160b-4ace-8c34-3b70acfbef61/10s/master.m3u8', u'--cookies', u'cookies.txt', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] master: Requesting header
WARNING: Could not send HEAD request to https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/102076671001/16c42289-160b-4ace-8c34-3b70acfbef61/10s/master.m3u8: HTTP Error 403: Forbidden
[generic] master: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
`

**Comment by rootless4real** [comment]
This seems to still be a problem.  I tried various permutations, without success.  Using the latest ytdl (2021.04.07).

`D:\downloads\youtubedl>youtube-dl`` -v --all-subs https://metoperafree.brightcove-services.com/?videold=6245231944001
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--all-subs', 'https://metoperafree.brightcove-services.com/?videold=6245231944001']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[generic] ?videold=6245231944001: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?videold=6245231944001: Downloading webpage
[generic] ?videold=6245231944001: Extracting information
ERROR: Unsupported URL: https://metoperafree.brightcove-services.com/?videold=6245231944001
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\generic.py", line 3506, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://metoperafree.brightcove-services.com/?videold=6245231944001`


`D:\downloads\youtubedl>youtube-dl -v --cookies --all-subs https://metoperafree.brightcove-services.com/?videold=6245231944001
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', '--all-subs', 'https://metoperafree.brightcove-services.com/?videold=6245231944001']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[generic] ?videold=6245231944001: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?videold=6245231944001: Downloading webpage
[generic] ?videold=6245231944001: Extracting information
ERROR: Unsupported URL: https://metoperafree.brightcove-services.com/?videold=6245231944001
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\generic.py", line 3506, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://metoperafree.brightcove-services.com/?videold=6245231944001`


`D:\downloads\youtubedl>youtube-dl -v --cookies --all-subs https://metoperafree.brightcove-services.com/102076671001/ShNTDWXQ/index.html?videold=6245231944001
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', '--all-subs', 'https://metoperafree.brightcove-services.com/102076671001/ShNTDWXQ/index.html?videold=6245231944001']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[generic] index: Requesting header
WARNING: Could not send HEAD request to https://metoperafree.brightcove-services.com/102076671001/ShNTDWXQ/index.html?videold=6245231944001: HTTP Error 403: Forbidden
[generic] index: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 2279, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default`

Is this fixable? Or is there a work-around?

Thank you.
