### ISSUE TITLE
Some tv4 episodes not working

### ISSUE THREAD

**Issue by hakanw** [ytdl-org/youtube-dl#24667]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -x https://www.tv4play.se/program/nyhetsmorgon/12534705 -v          1 ↵
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-x', u'https://www.tv4play.se/program/nyhetsmorgon/12534705', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 78.66.72.88 (SE) as X-Forwarded-For.
[TV4] 12534705: Downloading video info JSON
[TV4] 12534705: Downloading JSON metadata
[TV4] 12534705: Downloading m3u8 information
[TV4] 12534705: Downloading MPD manifest
[TV4] 12534705: Downloading f4m manifest
[TV4] 12534705: Downloading ISM manifest
WARNING: [TV4] 12534705: Failed to parse XML syntax error: line 1, column 0
Traceback (most recent call last):
  File "/Users/hakan/.virtualenvs/foo2/bin/youtube-dl", line 8, in <module>
    sys.exit(main())
  File "/Users/hakan/.virtualenvs/foo2/lib/python2.7/site-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/Users/hakan/.virtualenvs/foo2/lib/python2.7/site-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/Users/hakan/.virtualenvs/foo2/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/Users/hakan/.virtualenvs/foo2/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/Users/hakan/.virtualenvs/foo2/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/Users/hakan/.virtualenvs/foo2/lib/python2.7/site-packages/youtube_dl/extractor/tv4.py", line 103, in _real_extract
    video_id, ism_id='mss', fatal=False))
  File "/Users/hakan/.virtualenvs/foo2/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 2344, in _extract_ism_formats
    return self._parse_ism_formats(ism_doc, urlh.geturl(), ism_id)
  File "/Users/hakan/.virtualenvs/foo2/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 2353, in _parse_ism_formats
    if ism_doc.get('IsLive') == 'TRUE' or ism_doc.find('Protection') is not None:
AttributeError: 'NoneType' object has no attribute 'get'
```

## Description

This site used to work (even through login wall), now it suddenly doesn't. Seems to be a parsing of JSON/XML problem.

**Comment by hakanw** [comment]
Awesome, thanks @dstftw !
