### ISSUE TITLE
[es.dplay.com] Not working any more it needs user and password

### ISSUE THREAD

**Issue by felisucoibi** [ytdl-org/youtube-dl#24666]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
felisuco@felisuco-GL753VD:~$ youtube-dl -v https://es.dplay.com/dmax/pandemia-covid-19/temporada-1-episodio-1/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://es.dplay.com/dmax/pandemia-covid-19/temporada-1-episodio-1/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-42-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2
[debug] Proxy map: {}
[debug] Using fake IP 88.2.19.187 (ES) as X-Forwarded-For.
[DPlay] pandemia-covid-19/temporada-1-episodio-1: Downloading token
[DPlay] pandemia-covid-19/temporada-1-episodio-1: Downloading JSON metadata
[DPlay] pandemia-covid-19/temporada-1-episodio-1: Downloading JSON metadata
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dplay.py", line 163, in _get_disco_api_info
    display_id, headers=headers)['data']['attributes']['streaming']
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 892, in _download_json
    expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 870, in _download_json_handle
    expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 660, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 645, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dplay.py", line 247, in _real_extract
    url, display_id, host, 'dplay' + country, country)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dplay.py", line 172, in _get_disco_api_info
    self.raise_login_required()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 936, in raise_login_required
    expected=True)
ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.

```

## Description

Now it needs user name and pasword, and is nto working the --username and --password arguments.

Example:
https://es.dplay.com/dmax/pandemia-covid-19/temporada-1-episodio-1/

**Comment by felisucoibi** [comment]
Hi @dsftw please tell me duplicate of which bug? i can't see any active one of dpay, but lots of duplicate ones.
