### ISSUE TITLE
Tele5: Download fails, [Nexx] "Unable to download JSON metadata"

### ISSUE THREAD

**Issue by Newillye573** [ytdl-org/youtube-dl#24674]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

Version 2020.03.24
```
youtube-dl -f bestvideo+bestaudio https://www.tele5.de/filme/schlefaz-sharknado-5-2/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo+bestaudio', 'https://www.tele5.de/filme/schlefaz-sharknado-5-2/', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.7.3 (CPython) - Linux-4.19.97-v7l+-armv7l-with-debian-10.3
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[Tele5] schlefaz-sharknado-5-2: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/tele5.py", line 53, in _real_extract
    r'\bdata-id\s*=\s*["\'](\d{6,})'), webpage, 'video id')
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Version 2020.03.24 with Update-Code 2020.04.05 (issue case: #24553 )
```
youtube-dl -f bestvideo+bestaudio https://www.tele5.de/filme/schlefaz-sharknado-5-2/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo+bestaudio', 'https://www.tele5.de/filme/schlefaz-sharknado-5-2/', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.7.3 (CPython) - Linux-4.19.97-v7l+-armv7l-with-debian-10.3
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[Tele5] schlefaz-sharknado-5-2: Downloading webpage
[Tele5] schlefaz-sharknado-5-2: Downloading JSON metadata
[Nexx] 1612871: Downloading JSON metadata
[Nexx] 1612871: Downloading session/init JSON
[Nexx] 1612871: Downloading videos/byid/1612871 JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/pi/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/pi/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

## Description

Hi,
i had the same issue described in case #24553, so i updated the python-code.
The error "Unable to extract video id" is no longer occurring, but now there is another error when I try to use the program on this page: https://www.tele5.de/filme/schlefaz-sharknado-5-2/

Please tell me, if you need more data to verify the problem. I'm new here on GitHub.

**Comment by Newillye573** [comment]
Hi @dstftw , 
you labeled this issue as duplicate. 

I searched, but i cant find an open case for the Tele5 download with this error message.
Can you show me the case?

Thanks :)

**Comment by hammy1988** [comment]
The same here

**Comment by hammy1988** [comment]
@dstftw why you closed it? i cant find an open issue, too.

**Comment by SebiderSushi** [comment]
I can confirm this issue. Even if the prior fix to #24553 works for some videos, this one does yield the described error.

For example, having `youtube-dl` release `2020.03.24` installed, running
`youtube-dl https://www.tele5.de/filme/boy-culture/`
yields the id extraction error reporteded in #24553. But if i
`git clone https://github.com/ytdl-org/youtube-dl && cd youtube-dl`, followed by
`python -m youtube_dl --verbose https://www.tele5.de/filme/boy-culture/`
this starts a successful download.
However, running
`python -m youtube_dl --verbose https://www.tele5.de/filme/schlefaz-sharknado-5-2/`
immediatley after, yields the 404 error and log as reported by OP.

**Comment by Newillye573** [comment]
It seems there is an issue with movies that have been re-uploaded since april.

URL with failture:
- https://www.tele5.de/filme/schlefaz-der-polyp-die-bestie-mit-den-todesarmen-ab-13042018/ 
(reupload on 2020-04-04)
- https://www.tele5.de/filme/schlefaz-sharknado-5-2/ 
(reupload on 2020-04-05)

**Comment by tobiasholler** [comment]
same here, please reopen issue
Version: installed from git commit dcc8522 (2020-04-08)

```
youtube-dl https://www.tele5.de/filme/schlefaz-der-polyp-die-bestie-mit-den-todesarmen-ab-13042018/ --verbose --print-traffic

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.tele5.de/filme/schlefaz-der-polyp-die-bestie-mit-den-todesarmen-ab-13042018/', '--verbose', '--print-traffic']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.2 (CPython) - Linux-5.4.28-1-MANJARO-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[Tele5] schlefaz-der-polyp-die-bestie-mit-den-todesarmen-ab-13042018: Downloading webpage
send: b'GET /filme/schlefaz-der-polyp-die-bestie-mit-den-todesarmen-ab-13042018/ HTTP/1.1\r\nHost: www.tele5.de\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3763.2 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 08 Apr 2020 20:36:30 GMT
header: Server: Apache/2.4.41 (Debian)
header: Link: <https://www.tele5.de/wp-json/>; rel="https://api.w.org/", <https://www.tele5.de/?p=36926>; rel=shortlink
header: Strict-Transport-Security: max-age=0
header: Vary: Accept-Encoding
header: Upgrade: h2
header: Connection: keep-alive, close
header: Cache-Control: private, must-revalidate
header: Expires: Wed, 08 Apr 2020 20:36:30 GMT
header: Content-Encoding: gzip
header: Transfer-Encoding: chunked
header: Content-Type: text/html; charset=UTF-8
[Tele5] schlefaz-der-polyp-die-bestie-mit-den-todesarmen-ab-13042018: Downloading JSON metadata
send: b'GET /v2/media/XSWj0xbO HTTP/1.1\r\nHost: cdn.jwplayer.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3763.2 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: application/json; charset=utf-8
header: Content-Length: 811
header: Connection: close
header: Access-Control-Allow-Origin: *
header: Cache-Control: max-age=1200, max-stale=180
header: Content-Encoding: gzip
header: Date: Wed, 08 Apr 2020 20:38:40 GMT
header: Expires: Wed, 08 Apr 2020 20:58:40
header: Server: openresty
header: X-Cache: Miss from cloudfront
header: Via: 1.1 a7dcca466407f1871feceef50bc84272.cloudfront.net (CloudFront)
header: X-Amz-Cf-Pop: FRA6-C1
header: X-Amz-Cf-Id: G50Wn_KQka656cJOH-ohMQV9KCsimvaSHFYJ1YVwnSccyKORHIAKiA==
[Nexx] 1432923: Downloading JSON metadata
send: b'GET /api/video/1432923.json HTTP/1.1\r\nHost: arc.nexx.cloud\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3763.2 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 08 Apr 2020 20:38:40 GMT
header: Content-Type: application/json; charset=utf-8
header: Content-Length: 156
header: Connection: close
header: Vary: Accept-Encoding
header: Server: BunnyCDN-DE1-487
header: CDN-PullZone: 40982
header: CDN-Uid: 9d795e6d-2822-40d5-96de-4e6daf2cf439
header: CDN-RequestCountryCode: DE
header: CDN-EdgeStorageId: 487
header: Cache-Control: public, max-age=3600
header: Content-Encoding: gzip
header: Content-MD5: CiJGEggROUiom3H3E1/fVg==
header: Last-Modified: Tue, 02 Apr 2019 17:02:37 GMT
header: x-ms-request-id: a1457fd0-101e-0152-3116-0c1151000000
header: x-ms-version: 2017-11-09
header: x-ms-creation-time: Wed, 04 Apr 2018 10:02:49 GMT
header: x-ms-lease-status: unlocked
header: x-ms-lease-state: available
header: x-ms-blob-type: BlockBlob
header: x-ms-server-encrypted: true
header: Access-Control-Expose-Headers: x-ms-request-id,Server,x-ms-version,Content-Type,Content-Encoding,Cache-Control,Last-Modified,ETag,x-ms-creation-time,Content-MD5,x-ms-lease-status,x-ms-lease-state,x-ms-blob-type,x-ms-server-encrypted,Accept-Ranges,Content-Length,Date,Transfer-Encoding
header: Access-Control-Allow-Origin: *
header: CDN-CachedAt: 2020-04-06 13:20:57
header: CDN-RequestId: 6a1aec2b231e9acfbf005be7cb00ead4
header: CDN-Cache: HIT
header: Accept-Ranges: bytes
[Nexx] 1432923: Downloading session/init JSON
send: b'POST /v3/759/session/init HTTP/1.1\r\nContent-Length: 209\r\nHost: api.nexx.cloud\r\nX-Request-Enable-Auth-Fallback: 1\r\nContent-Type: application/x-www-form-urlencoded; charset=UTF-8\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3763.2 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
send: b'nxp_devh=2%3A1586378322%3A766023&nxp_userh=&precid=0&playlicense=0&screenx=1920&screeny=1080&playerversion=6.0.00&gateway=html5&adGateway=&explicitlanguage=en-US&addTextTemplates=1&addDomainData=1&addAdModel=1'
reply: 'HTTP/1.0 201 Created\r\n'
header: Date: Wed, 08 Apr 2020 20:38:40 GMT
header: Server: Apache
header: X-Powered-By: nexxOMNIA
header: Content-Length: 14074
header: X-Client-Token: SBJ759YVPB2KGP9FXRQV
header: Keep-Alive: timeout=30, max=148
header: Access-Control-Allow-Origin: *
header: Access-Control-Allow-Credentials: true
header: Access-Control-Max-Age: 86400
header: Timing-Allow-Origin: *
header: Cache-Control: no-cache, must-revalidate
header: Pragma: no-cache
header: Expires: Mon, 26 Jul 1997 05:00:00 GMT
header: Last-Modified: Wed, 08 Apr 2020 20:38:40 GMT
header: Connection: close
header: Content-Type: application/json
[Nexx] 1432923: Downloading videos/byid/1432923 JSON
send: b'POST /v3/759/videos/byid/1432923 HTTP/1.1\r\nContent-Length: 240\r\nHost: api.nexx.cloud\r\nX-Request-Cid: 2158637832007259752\r\nX-Request-Token: e40c07933eee1500e9251dff3afcceb0\r\nContent-Type: application/x-www-form-urlencoded; charset=UTF-8\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3763.2 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
send: b'additionalfields=language%2Cchannel%2Cactors%2Cstudio%2Clicenseby%2Cslug%2Csubtitle%2Cteaser%2Cdescription&addInteractionOptions=1&addStatusDetails=1&addStreamDetails=1&addCaptions=1&addScenes=1&addHotSpots=1&addBumpers=1&captionFormat=data'
reply: 'HTTP/1.0 404 Not Found\r\n'
header: Date: Wed, 08 Apr 2020 20:38:43 GMT
header: Server: Apache
header: X-Powered-By: nexxOMNIA
header: Content-Length: 180
header: Keep-Alive: timeout=30, max=148
header: Access-Control-Allow-Origin: *
header: Access-Control-Allow-Credentials: true
header: Access-Control-Max-Age: 86400
header: Timing-Allow-Origin: *
header: Cache-Control: no-cache, must-revalidate
header: Pragma: no-cache
header: Expires: Mon, 26 Jul 1997 05:00:00 GMT
header: Last-Modified: Wed, 08 Apr 2020 20:38:43 GMT
header: Connection: close
header: Content-Type: application/json
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3.8/site-packages/youtube_dl-2020.3.24-py3.8.egg/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.8/site-packages/youtube_dl-2020.3.24-py3.8.egg/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by FliegendeWurst** [comment]
Issue fixed in my fork: https://github.com/FliegendeWurst/youtube-dl/tree/fix-tele5-again

I'll open a PR soon.

**Comment by Newillye573** [comment]
Hi @FliegendeWurst,

thx for the response.

I tested your fix, but unfortunately now none of the links work.

With the master of `ytdl-org` this link (as example) works fine: https://www.tele5.de/filme/schlefaz-dragon-crusaders/

But with the code of this https://github.com/FliegendeWurst/youtube-dl/commit/32766d525a49fe020154e22c953da158fcd3c12e there show up the following error message:

```
youtube-dl -f bestvideo+bestaudio https://www.tele5.de/filme/schlefaz-dragon-crusaders/ -v

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo+bestaudio', 'https://www.tele5.de/filme/schlefaz-dragon-crusaders/', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.5.3 (CPython) - Linux-4.19.97-v7+-armv7l-with-debian-9.11
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1
[debug] Proxy map: {}
[Tele5] schlefaz-dragon-crusaders: Downloading webpage
[Tele5] schlefaz-dragon-crusaders: Downloading JSON metadata
[Tele5] 1F8PHGxn: Downloading m3u8 information
ERROR: requested format not available
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/pi/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/pi/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1636, in process_video_result
    expected=True)
youtube_dl.utils.ExtractorError: requested format not available
```

**Comment by Newillye573** [comment]
It seems that the command line argument `-f bestvideo+bestaudio` doesn't work.
With `-f bestvideo+bestaudio/best` all works fine.

**Comment by FliegendeWurst** [comment]
That's because Nexx offers more formats.
Nexx works for most of the videos, but I don't know how to "try" the Nexx extractor in this extractor.

**Comment by hammy1988** [comment]
> And at least one of the 404 errors is correct: https://www.tele5.de/filme/schlefaz-sharknado-5-2/ is not found in the browser too.
> https://www.tele5.de/filme/schlefaz-sharknado-5/ works with my patch.

Yes, since two days the site https://www.tele5.de/filme/schlefaz-sharknado-5-2/ is offline. But here the wrong link is still available: https://www.tele5.de/schlefaz/mediathek/
I think there was a mistake with the re-upload.
