### ISSUE TITLE
Zattoo recordings stopped working due to url change

### ISSUE THREAD

**Issue by seiz** [ytdl-org/youtube-dl#24676]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v --username PRIVATE --password PRIVATE https://zattoo.com/recording/233957045
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://zattoo.com/recording/233957045']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.4, ffprobe 2.8.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 233957045: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 233957045: Downloading webpage
[generic] 233957045: Extracting information
ERROR: Unsupported URL: https://zattoo.com/recording/233957045
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2375, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1, column 1851
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3352, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://zattoo.com/recording/233957045
```

## Description

Downloading Zattoo-Recordings used to work just fine, but they changed the URL to access the recordings and that seems to have broken youtube-dl access to these recordings.

I found a similar, closed issue, which was closed as a "duplicate", however there isn't a duplicate issue i could find and the issue exists since quite some time now. 
The "closed as duplicate" issue is: https://github.com/ytdl-org/youtube-dl/issues/23945

**Comment by seiz** [comment]
@dstftw why is this a duplicate? Please let me know the issue, this is duplicating. I don't understand and searched the issues before posting this. Thanks!

**Comment by dstftw** [comment]
#22258.
