### ISSUE TITLE
nova.cz stopped working

### ISSUE THREAD

**Issue by filip11111** [ytdl-org/youtube-dl#24701]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://novaplus.nova.cz/porad/superstar-2020/epizoda/43471-superstar-2020-7-dil']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg git-2019-12-15-ed9279a
[debug] Proxy map: {}
[Nova] 43471-superstar-2020-7-dil: Downloading webpage
[NovaEmbed] GRlTXX064Hr: Downloading webpage
ERROR: Unable to extract formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\nova.py", line 38, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

nova.cz stopped working

**Comment by filip11111** [comment]
you can use this proxy http://www.a.dukovany.cz/

**Comment by dstftw** [comment]
That's not a proxy at all.

**Comment by filip11111** [comment]
Here are others:
http://free-proxy.cz/cs/proxylist/country/CZ/all/ping/all
http://free-proxy.cz/cs/web-proxylist/country/CZ/all/ping/all

**Comment by dstftw** [comment]
They are all dead.
