### ISSUE TITLE
HTTP 403 on SoundCloud download

### ISSUE THREAD

**Issue by tripulse** [ytdl-org/youtube-dl#24715]
## Checklist
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestaudio', '-o', 'test02.%(ext)s', 'https://soundcloud.com/majorleaguewobs/minecraft-trap-remix', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.8.2 (CPython) - Linux-5.3.0-2-amd64-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.2-1, ffprobe 4.2.2-1
[debug] Proxy map: {}
[soundcloud] majorleaguewobs/minecraft-trap-remix: Downloading info JSON
[soundcloud] 186832309: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[soundcloud] 186832309: Downloading JSON metadata
[soundcloud] 186832309: Downloading JSON metadata
[soundcloud] 186832309: Downloading JSON metadata
[debug] Invoking downloader on 'https://api.soundcloud.com/tracks/186832309/download?client_id=OdgVKzzPYXN6cljKY5A6iOga2Cb0OUXf'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/tripulse/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/home/tripulse/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/home/tripulse/.local/lib/python3.8/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/home/tripulse/.local/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/home/tripulse/.local/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/tripulse/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```
## Description
I was attempting to download a single track from SoundCloud by [this](https://soundcloud.com/majorleaguewobs/minecraft-trap-remix) URL. But, it throws a `urllib.error.HTTPError` with status code of 403. Guessing from the log it seems that SoundCloud denies the request because the API key isn't valid or something else.

**Comment by cappert** [comment]
I cannot reproduce the bug.
Your version of youtube-dl is outdated (version 2020.03.08), please upgrade.

**Comment by efraim-il** [comment]
tripulse, are you sure you want to download media from Soundcloud? as far I'm aware the quality is 128kbps

**Comment by tripulse** [comment]
Updated to the latest version from PyPI, that bug is fixed.
