### ISSUE TITLE
Please add space.bilibili.com

### ISSUE THREAD

**Issue by tujidelv** [ytdl-org/youtube-dl#24719]
## Checklist

- [x ] I'm reporting a new site support request
- [x ] I've verified that I'm running youtube-dl version **2020.03.24**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that none of provided URLs violate any copyrights
- [x ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://space.bilibili.com/178781504
- Single video: https://space.bilibili.com/178781504/video
- Playlist: https://space.bilibili.com/178781504

## Description

[root@144 ~]# youtube-dl -v -F -i https://space.bilibili.com/178781504
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'-i', u'https://space.bilibili.com/178781504']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.5 (CPython) - Linux-4.14.129-bbrplus-x86_64-with-centos-7.7.1908-Core
[debug] exe versions: ffmpeg 3.1, ffprobe 3.1
[debug] Proxy map: {}
[generic] 178781504: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 178781504: Downloading webpage
[generic] 178781504: Extracting information
ERROR: Unsupported URL: https://space.bilibili.com/178781504
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2375, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1, column 613
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3352, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://space.bilibili.com/178781504

[root@144 ~]# youtube-dl -v -F -i https://space.bilibili.com/178781504/video
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'-i', u'https://space.bilibili.com/178781504/video']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.5 (CPython) - Linux-4.14.129-bbrplus-x86_64-with-centos-7.7.1908-Core
[debug] exe versions: ffmpeg 3.1, ffprobe 3.1
[debug] Proxy map: {}
[generic] video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] video: Downloading webpage
[generic] video: Extracting information
ERROR: Unsupported URL: https://space.bilibili.com/178781504/video
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2375, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1, column 613
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3352, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://space.bilibili.com/178781504/video

**Comment by tomac4t** [comment]
Bilibili have been supported. Your example URLs doesn't have any videos.
