### ISSUE TITLE
Seeing "Got server HTTP error: HTTP Error 500: Internal Server Error." error for every YT video

### ISSUE THREAD

**Issue by cowboy** [ytdl-org/youtube-dl#24720]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

Failure 1

```
$ youtube-dl -v "https://www.youtube.com/watch?v=KTJuWES1J0Y"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=KTJuWES1J0Y']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Darwin-19.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] KTJuWES1J0Y: Downloading webpage
[youtube] KTJuWES1J0Y: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r2---sn-gjo-cvnl.googlevideo.com/videoplayback?expire=1586551583&ei=v4aQXuPBNJOshgbssYqIDA&ip=111.111.111.111&id=o-AIWbRRvQz6LPqp9wYcDbUGBUb_CAqVuGLm8rcRoS034k&itag=22&source=youtube&requiressl=yes&mh=9e&mm=31%2C29&mn=sn-gjo-cvnl%2Csn-ab5l6nzd&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=1837500&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=2780.984&lmt=1471943888636537&mt=1586529880&fvip=6&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AJpPlLswRAIgDtdGnmrAuBm5EQynBRoAH--hIWFaec8CNbFLZls-wvYCIF0uQkfSNL2EUxY21lhkqJeLVZzVA9I7uY2mn8QQX8ts&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIgdDWMKs5_De34BZkta6lIf4v1ZXfAmhmTWLwDABMNxF0CIQD-dZdanq5NqTekXV7lfYr6jTrsIycArZHnzLQUiUiuEw%3D%3D'
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 182, in establish_connection
    raise RetryDownload(err)
RetryDownload
```

Failure 2

```
$ youtube-dl -v "https://www.youtube.com/watch?v=ZVKof7rziac"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=ZVKof7rziac']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Darwin-19.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] ZVKof7rziac: Downloading webpage
[youtube] ZVKof7rziac: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r2---sn-gjo-cvnl.googlevideo.com/videoplayback?expire=1586551600&ei=0IaQXtzHHZOshgbN64SgCQ&ip=111.111.111.111&id=o-AM3T0muINV-HpAFxaVpbSmutfPPh1-522eY05Y3E3EpG&itag=22&source=youtube&requiressl=yes&mh=9h&mm=31%2C29&mn=sn-gjo-cvnl%2Csn-ab5szn7l&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=1837500&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=2814.328&lmt=1473138645056146&mt=1586529880&fvip=4&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AJpPlLswRQIgarE8FxYc1lO-rDc1kNDow1VYH136oFVD8WHkGiBh8ZgCIQDGVIVihD5yeiBjUH0zFDMLtLrv3arQm9UHHTTbqBww1g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIgcUEkgZXmUcRieNvZtEMKHl9FWq2Sa4_q-yvkRQquVnACIQDKZc8zZYHjWPIwzKrFrNmR4eJSc59HgbG9aIiSyG4cOw%3D%3D'
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 182, in establish_connection
    raise RetryDownload(err)
RetryDownload
```

Failure 3

```
$ youtube-dl -v "https://www.youtube.com/watch?v=m535INKq13c"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=m535INKq13c']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Darwin-19.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] m535INKq13c: Downloading webpage
[youtube] m535INKq13c: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r2---sn-gjo-cvne.googlevideo.com/videoplayback?expire=1586551630&ei=7oaQXuPNFqKt8gSRkLqYAw&ip=111.111.111.111&id=o-AFJT1jjyo67lBIJsxw7QtmwH_-11HU6MpqkAoFH1fMnr&itag=22&source=youtube&requiressl=yes&mh=hq&mm=31%2C29&mn=sn-gjo-cvne%2Csn-ab5szn7y&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=1798750&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=2217.528&lmt=1472308235715785&mt=1586529941&fvip=2&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AJpPlLswRQIgXuq8R0W1AkUfweLPBfyyHVZ1dPR2DfckUueaRwJiRzACIQCjXNVlKR7Yu1ZYo4yCgvdc5EOw2QEUDN01O-A-ImkPCQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRgIhANUoTBPjPjQltcWIfhGJhWn-iQy2wNrE-hagl8vMAi5NAiEAqWG7JxATc0Lnig9mvjBlgk3m7HqXfG0j6Dqt1OmfT60%3D'
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 182, in establish_connection
    raise RetryDownload(err)
RetryDownload
```

## Description

I don't know what's going on, but I'm getting `Got server HTTP error: HTTP Error 500: Internal Server Error.` for every video I try to download. This started happening within the last 2 days, and I've never seen the issue before that. Note that I have replaced my IP in the download URL with `111.111.111.111`, and I'm not behind any kind of VPN.

Thanks for your help!

**Comment by dstftw** [comment]
Server side Youtube issue for format 22.

**Comment by SamRoger** [comment]
Same issue as @dstftw
