### ISSUE TITLE
Funimation JSON Error

### ISSUE THREAD

**Issue by Nz17** [ytdl-org/youtube-dl#24742]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'https://www.funimation.com/shows/sakura-wars-the-animation/the-curtain-rises-the-new-combat-revue/', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-8-amd64-x86_64-with-debian-10.3
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1
[debug] Proxy map: {}
[Funimation] the-curtain-rises-the-new-combat-revue: Downloading webpage
WARNING: [Funimation] the-curtain-rises-the-new-combat-revue: Failed to parse JSON No JSON object could be decoded
ERROR: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/sean/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/sean/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/sean/bin/youtube-dl/youtube_dl/extractor/funimation.py", line 100, in _real_extract
    ], webpage, fatal=True)
  File "/home/sean/bin/youtube-dl/youtube_dl/extractor/common.py", line 1135, in _html_search_meta
    html, display_name, fatal=fatal, group='content', **kwargs)
  File "/home/sean/bin/youtube-dl/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/sean/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

The Funimation Web site appears to give youtube-dl a JSON error caused by something like the JSON file having been moved from where it was previously located or changes in the JSON file format at the Web site or some parsing issue found with the JSON at the URL [https://www.funimation.com/shows/sakura-wars-the-animation/the-curtain-rises-the-new-combat-revue/](https://www.funimation.com/shows/sakura-wars-the-animation/the-curtain-rises-the-new-combat-revue/).

**Comment by Nz17** [comment]
A [solution for "JSON parsing errors" from Funimation when using youtube-dl](https://github.com/ytdl-org/youtube-dl/pull/13515#issuecomment-489892303) was found after searching some more through the youtube-dl issue tracker.  I leave this link here for those seeking a workaround to their problem in the future such as via a Web search.

When you have completed the steps you should have a command like this:

`youtube-dl --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" --cookies funimation-cookies.txt --format hls-2431-0 https://www.funimation.com/shows/the-show/the-episode/`
