### ISSUE TITLE
Unrecognized option 'ignorelength'

### ISSUE THREAD

**Issue by davFaithid** [ytdl-org/youtube-dl#24752]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [?] I've checked that all URLs and arguments with special characters are properly quoted or escaped
I believe they are, but I'm not sure. =P
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --all-subs --sub-format "ass" -v --exec "ffmpeg -vsync 0 -i {} -an -crf 25 -s 1280x720 -sws_flags lanczos out.mp4 ^&^& ffmpeg -i {} -vn out.wav ^&^& neroaacenc -q 0.6 -ignorelength -if out.wav -of out.m4a ^&^& ffmpeg -i out.mp4 -i out.m4a -i {}.enUS.ass ^-map 0:v ^-map 1:a -map 2:s -c copy out.mkv ^&^& del {} ^&^& ren out.mkv {} ^&^& del *.wav && *.mp4 ^&^& del *.m4a ^&^& del *.ass" -o "Example Show - S1E%(episode_number)s - %(episode)s.mkv" -- http://example.com/video
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--all-subs', '--sub-format', 'ass', '-v', '--exec', 'ffmpeg -vsync 0 -i {} -an -crf 25 -s 1280x720 -sws_flags lanczos out.mp4 ^&^& ffmpeg -i {} -vn out.wav ^&^& neroaacenc -q 0.6 -ignorelength -if out.wav -of out.m4a ^&^& ffmpeg -i out.mp4 -i out.m4a -i {}.enUS.ass ^-map 0:v ^-map 1:a -map 2:s -c copy out.mkv ^&^& del {} ^&^& ren out.mkv {} ^&^& del *.wav && *.mp4 ^&^& del *.m4a ^&^& del *.ass', '-o', 'Example Show - S1E%(episode_number)s - %(episode)s.mkv', '--', 'http://example.com/video']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.0 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg 4.2, ffprobe git-2019-12-24-287620f
[debug] Proxy map: {}
[example:playlist] video: Downloading webpage
[download] Downloading playlist: Example
[example:playlist] playlist Example: Collected 169 video ids (downloading 169 of them)
[download] Downloading video 1 of 169
[example] 693467: Downloading webpage
[example] 693467: Downloading adaptive_hls-audio-jaJP-hardsub-enUS information
[example] 693467: Downloading adaptive_hls-audio-jaJP information
[example] 693467: Downloading media info
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Example Show - S1E806 - Example Episode (Part One).mkv.enUS.ass
[debug] Invoking downloader on 'https://v.vrv.co/evs/34fff33fa71317ff7185e05fd6923fee/assets/c4lg6u8f13xgj5y_2469883.mp4/index-v1-a1.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly92LnZydi5jby9ldnMvMzRmZmYzM2ZhNzEzMTdmZjcxODVlMDVmZDY5MjNmZWUvYXNzZXRzL2M0bGc2dThmMTN4Z2o1eV8yNDY5ODgzLm1wNC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTg2OTE1NjkwfX19XX0_&Signature=QJKYrKGWfOxShn5izj8im7KjwFwdA6uXAzz3UesdywTxUvlAKogMs9s7xtXHE0pNJW98Srge3bcHgHxWyMaZ1c~xy9CD8~uDj7TAS6-GhujUay1M3Ryhq6DmMFt5N~VLQV8exckxAs0jJgxfS8O26zNr7wpHzqaSADmzaqj7JOQv97BdjlqKPSA~ySUbr8jvxDL0AsYDlz4kudp2tvyNaZtSKk~owCdu9rq3jzKXD8z4Y~4RJVODDZe8QGQiXy3PmtVRyFa6adIOiOeEQQZ~skUwIYw9avRniIjoM2upz4I9-gvsrZ1xCj6Yg-09iDmhjS8iv6GVxdLqL2AzXx69Bw__&Key-Pair-Id=APKAJKQQ2INNHTYFB44A'
[download] Example Show - S1E806 - Example Episode (Part One).mkv has already been downloaded
[download] 100% of 1.19GiB
[exec] Executing command: ffmpeg -vsync 0 -i "Example Show - S1E806 - Example Episode (Part One).mkv" -an -crf 25 -s 1280x720 -sws_flags lanczos out.mp4 ^&^& ffmpeg -i "Example Show - S1E806 - Example Episode (Part One).mkv" -vn out.wav ^&^& neroaacenc -q 0.6 -ignorelength -if out.wav -of out.m4a ^&^& ffmpeg -i out.mp4 -i out.m4a -i "Example Show - S1E806 - Example Episode (Part One).mkv".enUS.ass ^-map 0:v ^-map 1:a -map 2:s -c copy out.mkv ^&^& del "Example Show - S1E806 - Example Episode (Part One).mkv" ^&^& ren out.mkv "Example Show - S1E806 - Example Episode (Part One).mkv" ^&^& del *.wav && *.mp4 ^&^& del *.m4a ^&^& del *.ass
ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190807
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Unrecognized option 'ignorelength'.
Error splitting the argument list: Option not found
ERROR: Command returned error code 1
Traceback (most recent call last):
  File "c:\users\davfa\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2065, in post_process
    files_to_delete, info = pp.run(info)
  File "c:\users\davfa\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\postprocessor\execafterdownload.py", line 28, in run
    raise PostProcessingError(
youtube_dl.utils.PostProcessingError: Command returned error code 1
```

## Description

I think this is a problem with the `--exec` command. I don't know why, but it always returns this when I try using these commands. Am I missing something? Thank you.

PS No, I don't think its an ffmpeg issue as it is followed by `Error splitting the argument list: Option not found`

**Comment by dstftw** [comment]
This is problem with your ffmpeg as it's an output from ffmpeg.
