### ISSUE TITLE
Viki with an account. Getting a 403 : Forbidden (caused by HTTPError()) when downloading on Windows 10.

### ISSUE THREAD

**Issue by AlecHex** [ytdl-org/youtube-dl#24754]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
Case 1: Logged in but no account details input: Limited to only 480p 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.viki.com/videos/1161765v-forest-episode-1', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2019-12-08-9f7b2b3, ffprobe git-2019-12-08-9f7b2b3
[debug] Proxy map: {}
[viki] 1161765v: Downloading video JSON
[viki] 1161765v: Downloading video streams JSON
[info] Available formats for 1161765v:
format code  extension  resolution note
mpd-http     mpd        unknown
240p-https   mp4        240p
360p-https   mp4        360p
480p-https   mp4        480p       (best)

Case 2 : Logged in and account details added: HTTP Error
C:\Youtube-dl>youtube-dl --username USERNAME --password PASSWORD -F https://www.viki.com/videos/1161765v-forest-episode-1 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '-F', 'https://www.viki.com/videos/1161765v-forest-episode-1', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2019-12-08-9f7b2b3, ffprobe git-2019-12-08-9f7b2b3
[debug] Proxy map: {}
[viki] Logging in
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

```

## Description

Hopefully I have created this issue properly. So basically when streaming through the browser I am getting 1080p HD quality for this video, but when going to youtube-dl to download them, I am getting the issues given above. I have posted two logs with two different cases. I have run the --cookies command instead of the username and password, and that doesn't seem to work also. 

If an account is needed I can give the account to the dev to reproduce and check the problem for a fix. I am on Windows 10 if that is relevant anyhow. If there are anymore details required, please let me know and I'll provide them too.
Thank you.

**Comment by tanymb1688** [comment]
I can confirm this issue exist, and is definitely a very recent one, this issue did not exist on 12th Apr local time.

**Comment by heendher** [comment]
Try increse the --socket-timeout, in my case i set it to 10 seconds and works again.

**Comment by charlietango1** [comment]
I have the exact same issue on Mac OS. Since this morning, trying to download Viki Pass HD videos results in a 403 forbidden error. I am a Viki Pass subscriber with a valid account. Downloading standard definition videos without a login on Viki still works, but the HD video downloads for Viki Pass subscribers are no longer working.

The suggested fix of increasing the --socket-timeout did not work for me.

**Comment by NJARAM** [comment]
same problem here as at 15th april.Any solution?

**Comment by maferv** [comment]
I'm getting the feeling that this is not a problem of youtube-dl, but a new limit implemented by youtube/google themselves

**Comment by guilhermelucasfreitas** [comment]
> Try increase the --socket-timeout, in my case i set it to 10 seconds and works again.

Yess!!! 30seconds for me

**Comment by dryshirt** [comment]
Trying to download using the cookies.txt workaround gives a 401 error instead of a 403; maybe this will be helpful in determining the cause of the error.

I used [cookies.txt](https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg) for Chrome and exported the cookies from a tab playing an episode.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', 'https://www.viki.com/videos/1118521v', '--cookies', 'cookies.txt', '--verbose', '--socket-timeout', '30']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[viki] 1118521v: Downloading video JSON
[viki] 1118521v: Downloading video streams JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

**Comment by AlecHex** [comment]
> 
> 
> Try increase the --socket-timeout, in my case i set it to 10 seconds and works again.

Still doesn't work, can you post the command you input?

**Comment by AlecHex** [comment]
> 
> 
> > Try increase the --socket-timeout, in my case i set it to 10 seconds and works again.
> 
> Yess!!! 30seconds for me

Doesn't work for me. Can you post the command?

**Comment by keksimusmaximus** [comment]
Happens for me on regular Youtube Videos too:

`youtube-dl --version
2020.03.24

youtube-dl https://www.youtube.com/watch?v=zXKTRu4mAA0 -v

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=zXKTRu4mAA0', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.2 (CPython) - Linux-5.6.3-2-MANJARO-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] zXKTRu4mAA0: Downloading webpage
[youtube] {18} signature length 102, html5 player vflset
[youtube] {134} signature length 106, html5 player vflset
[youtube] {243} signature length 106, html5 player vflset
[youtube] {133} signature length 102, html5 player vflset
[youtube] {242} signature length 102, html5 player vflset
[youtube] {160} signature length 102, html5 player vflset
[youtube] {278} signature length 106, html5 player vflset
[youtube] {140} signature length 106, html5 player vflset
[youtube] {249} signature length 106, html5 player vflset
[youtube] {250} signature length 102, html5 player vflset
[youtube] {251} signature length 106, html5 player vflset
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on !!--snip--!!
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`
