### ISSUE TITLE
[youtube] HTTP Error 403: Forbidden for any music video

### ISSUE THREAD

**Issue by vice** [ytdl-org/youtube-dl#24760]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.03.24**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: ['-o', '%(title)s.%(id)s.f%(format_id)s.%(ext)s', '-f', 'Original/((272/337/401/313/336/400/271/303/335/399/248/302/398/334/247/397/333/244/396/332/243/395/331/242/bestvideo)+(251/140/250/bestaudio))/best', '--add-metadata']
[debug] Custom config: []
[debug] Command-line args: ['-v', '1NarDEEhOsM']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.7.5 (CPython) - Linux-5.3.0-45-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2
[debug] Proxy map: {}
[youtube] 1NarDEEhOsM: Downloading webpage
[youtube] {18} signature length 112, html5 player vflset
[youtube] {137} signature length 112, html5 player vflset
[youtube] {136} signature length 112, html5 player vflset
[youtube] {135} signature length 112, html5 player vflset
[youtube] {134} signature length 112, html5 player vflset
[youtube] {133} signature length 112, html5 player vflset
[youtube] {160} signature length 108, html5 player vflset
[youtube] {140} signature length 108, html5 player vflset
[youtube] {249} signature length 112, html5 player vflset
[youtube] {250} signature length 112, html5 player vflset
[youtube] {251} signature length 112, html5 player vflset
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r1---sn-h5nhv8pa-n89e.googlevideo.com/videoplayback?expire=1586805967&ei=b2iUXtDZBJKX1gbSh6KYBw&ip=213.194.165.97&id=o-AIbHvuCK81Y8Ij9AblbE-UGTrcjfFG7IFKCoxmsPbIOR&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160&source=youtube&requiressl=yes&mh=Vv&mm=31%2C29&mn=sn-h5nhv8pa-n89e%2Csn-h5q7dned&ms=au%2Crdu&mv=m&mvi=0&pcm2cms=yes&pl=20&gcr=es&initcwndbps=1203750&vprv=1&mime=video%2Fmp4&gir=yes&clen=44104344&dur=227.320&lmt=1586765446510054&mt=1586784281&fvip=5&keepalive=yes&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIgYtwefvlGL__lJ0V9PniN0BlR7zNN0FwDIS74s_quIkECIQCk-L-zdlpbX6eOoj9VJfY2-o1BiytPkFLAPk6j-NjYpQ%3D%3D&sig=PEEPEEE===w1q3p_R4PgrbFc6DiCUGWfK67GPIlCS2EoitHuXCpeeAiAb=1rO2S58LLXtShteNO7EvadjGnG0Jorx14T8C86PhLAhIQRwsLlP&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

## Description

Today April the 13th any youtube video tried does not download due to a 403 HTTP Error.

**Comment by vice** [comment]
Previously, I had sporadic forbidden errors that solved by just trying again. I don't know if this could be related.
For completeness, any music video fails. Previously they worked.

**Comment by Jeronimo17** [comment]
It works for me with non-drm videos

**Comment by vice** [comment]
Thanks for quick reply. Finally it was a signature problem. Solved after removing .cache/youtube-dl as commented in https://github.com/ytdl-org/youtube-dl/issues/24713#issuecomment-612037468

Sorry for the noise. But It was first time I needed to do it.
