### ISSUE TITLE
Some videos won't download from Elonet

### ISSUE THREAD

**Issue by mrderp** [ytdl-org/youtube-dl#24774]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.03.24**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
C:\Programs\download>youtube-dl -v "https://elonet.finna.fi/Record/kavi.elonet_elokuva_107867"
[debug] System config: []
[debug] User config: ['-f', 'bestvideo[height<=?1080]+bestaudio', '--merge-output-format', 'mkv']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://elonet.finna.fi/Record/kavi.elonet_elokuva_107867']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-04-03-52523b6
[debug] Proxy map: {}
[generic] kavi: Requesting header
WARNING: Falling back on generic information extractor.
[generic] kavi: Downloading webpage
[generic] kavi: Extracting information
ERROR: Unsupported URL: https://elonet.finna.fi/Record/kavi.elonet_elokuva_107867
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\generic.py", line 3352, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://elonet.finna.fi/Record/kavi.elonet_elokuva_107867
```

## Description

WRITE DESCRIPTION HERE
Most of the videos from Elonet download just fine with the Vimeo plugin (for example: https://elonet.finna.fi/Record/kavi.elonet_elokuva_123238), but some won't at all (for example: https://elonet.finna.fi/Record/kavi.elonet_elokuva_107867). There is a similar issue in the closed issues (https://github.com/ytdl-org/youtube-dl/issues/23304), but I can't comment on that.

**Comment by vkk800** [comment]
I can confirm this. In fact, I can't get youtube-dl to work with any videos on Elonet. It used to work so it looks like Elonet changed something.
