### ISSUE TITLE
[pluralsight] - ERROR: unable to open for writing: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by a-wip0** [ytdl-org/youtube-dl#24798]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[download] Downloading video 16 of 36
[pluralsight] 7c17e38f-73b4-48e8-988e-355ea9f08121-4: Downloading JSON metadata
[pluralsight] 7c17e38f-73b4-48e8-988e-355ea9f08121-4: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] 7c17e38f-73b4-48e8-988e-355ea9f08121-4: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] 7c17e38f-73b4-48e8-988e-355ea9f08121-4: Waiting for 5 seconds to avoid throttling
[pluralsight] 7c17e38f-73b4-48e8-988e-355ea9f08121-4: Downloading captions JSON
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Demo - Installing Apache, Working with the httpd Service, and Apache Configuration Files-923f80db-1b21-4cc0-a861-d033e971ce35.en.srt
[debug] Invoking downloader on 'https://vid5.pluralsight.com/expiretime=1586969497/359017ed3ac9ad4ff5120477b54fa6d3/clips/resolution/923f80db-1b21-4cc0-a861-d033e971ce35/current/mp4/1280x720.mp4'
[download] Sleeping 60 seconds...
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'Demo - Installing Apache, Working with the httpd Service, and Apache Configuration Files-923f80db-1b21-4cc0-a861-d033e971ce35.mp4.part'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\http.py", line 250, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\utils.py", line 2046, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'Demo - Installing Apache, Working with the httpd Service, and Apache Configuration Files-923f80db-1b21-4cc0-a861-d033e971ce35.mp4.part'
```

## Description

I meet this error while downloading this course 
```
https://app.pluralsight.com/library/courses/linux-http-services-administration
```
the video that causing the error
```
https://app.pluralsight.com/player?course=linux-http-services-administration&author=anthony-nocentino&name=7c17e38f-73b4-48e8-988e-355ea9f08121&clip=4&mode=live
```
i can watch the video but i can't download it

this is the command i used to download that course
```
youtube-dl -v --username "myemail" --all-subs --password "mypassword" --verbose --sleep-interval 60 "https://app.pluralsight.com/library/courses/linux-http-services-administration"
```

**Comment by a-wip0** [comment]
@dstftw  did i miss something?
