### ISSUE TITLE
403 forbidden on alot of youtube urls

### ISSUE THREAD

**Issue by worstenbrood** [ytdl-org/youtube-dl#24796]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=ypq3E3sPWTg', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-03-28-3362330, ffprobe git-2020-03-28-3362330
[debug] Proxy map: {}
[youtube] ypq3E3sPWTg: Downloading webpage
[youtube] {18} signature length 106, html5 player vflset
[youtube] {136} signature length 106, html5 player vflset
[youtube] {247} signature length 102, html5 player vflset
[youtube] {135} signature length 106, html5 player vflset
[youtube] {244} signature length 106, html5 player vflset
[youtube] {134} signature length 106, html5 player vflset
[youtube] {243} signature length 106, html5 player vflset
[youtube] {133} signature length 106, html5 player vflset
[youtube] {242} signature length 106, html5 player vflset
[youtube] {160} signature length 106, html5 player vflset
[youtube] {278} signature length 106, html5 player vflset
[youtube] {140} signature length 106, html5 player vflset
[youtube] {249} signature length 102, html5 player vflset
[youtube] {250} signature length 102, html5 player vflset
[youtube] {251} signature length 106, html5 player vflset
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r4---sn-uxaxoxu-cg0r.googlevideo.com/videoplayback?expire=1586976866&ei=AgSXXt_gHOP_7gPkjpKgBQ&ip=141.134.96.179&id=o-AIhcIQvcK2uXo_0Bz9B1Xsn8OctsSXdWeXZM-n6azGG0&itag=136&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=youtube&requiressl=yes&mh=F7&mm=31%2C29&mn=sn-uxaxoxu-cg0r%2Csn-5hnekn7k&ms=au%2Crdu&mv=m&mvi=3&pl=17&initcwndbps=1541250&vprv=1&mime=video%2Fmp4&gir=yes&clen=6388944&dur=489.999&lmt=1586944880482290&mt=1586955160&fvip=4&keepalive=yes&c=WEB&txp=2316222&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIgRuhxuYV23LHP3x7vboUzyZTfxsMTTZkMAfrAzQZ_mBwCIQDUT1LrxJr5_UY39j7tO1iHBsCU7f1l8qZe93LaVGBvYg%3D%3D&sig=8JAJpPlAswRQIgHUAVQX_rxyJrtCdEn2X__-thLiti_v60IEPK6K_dj1kKIQDMtRv3vvMQNC3Q2=3ENT29rN4Va-qJ8VkUvIsHpDppKC&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1920, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

```

## Description

Since today it get alot of 403 forbidden errors on youtube urls.

**Comment by Oneboy1979** [comment]
Hi, i've testet your link and it seems to work:

```
youtube-dl https://www.youtube.com/watch?v=ypq3E3sPWTg -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=ypq3E3sPWTg', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Linux-4.19.97-v7+-armv7l-with-debian-10.3
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1
[debug] Proxy map: {}
[youtube] ypq3E3sPWTg: Downloading webpage
[youtube] {18} signature length 106, html5 player vflset
[youtube] {136} signature length 106, html5 player vflset
[youtube] {247} signature length 106, html5 player vflset
[youtube] {135} signature length 106, html5 player vflset
[youtube] {244} signature length 106, html5 player vflset
[youtube] {134} signature length 106, html5 player vflset
[youtube] {243} signature length 106, html5 player vflset
[youtube] {133} signature length 106, html5 player vflset
[youtube] {242} signature length 106, html5 player vflset
[youtube] {160} signature length 106, html5 player vflset
[youtube] {278} signature length 106, html5 player vflset
[youtube] {140} signature length 106, html5 player vflset
[youtube] {249} signature length 102, html5 player vflset
[youtube] {250} signature length 106, html5 player vflset
[youtube] {251} signature length 102, html5 player vflset
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r4---sn-h0jeenek.googlevideo.com/videoplayback?expire=1586977425&ei=MQaXXt3jLojvgAfypoqYDw&ip=80.108.42.171&id=o-ACYeHNu7oAiTFSvqGyhKStPJWPHDNZoMvRfu65ij31pF&itag=136&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=youtube&requiressl=yes&mh=F7&mm=31%2C29&mn=sn-h0jeenek%2Csn-h0jeln7e&ms=au%2Crdu&mv=m&mvi=3&pl=16&initcwndbps=1598750&vprv=1&mime=video%2Fmp4&gir=yes&clen=6388944&dur=489.999&lmt=1586944880482290&mt=1586955697&fvip=4&keepalive=yes&fexp=23882514&beids=9466586&c=WEB&txp=2316222&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIhAIW9PA2R7tnonSXsW3072mh7mrFQ7Xbpis40mr92halBAiAcX1vHrCBrGcDoiZR7E1MuKbYZ2aJuw_DOBPLTDm589g%3D%3D&sig=AJpPlLswRQIgEG5fX1ZMyXaKuu75RiHQOfTH9DubMFzxVgZUkz9KGYwCIQCmeEN0Hlyu_sJQl8Th_893tYPBeUAm1hCNtAdBk9GHjg==&ratebypass=yes'
[download] Destination: Dynacom - Cloud Mattress [Auditen Music]-ypq3E3sPWTg.f136.mp4
[download] 100% of 6.09MiB in 00:01
[debug] Invoking downloader on u'https://r4---sn-h0jeenek.googlevideo.com/videoplayback?expire=1586977425&ei=MQaXXt3jLojvgAfypoqYDw&ip=80.108.42.171&id=o-ACYeHNu7oAiTFSvqGyhKStPJWPHDNZoMvRfu65ij31pF&itag=251&source=youtube&requiressl=yes&mh=F7&mm=31%2C29&mn=sn-h0jeenek%2Csn-h0jeln7e&ms=au%2Crdu&mv=m&mvi=3&pl=16&initcwndbps=1598750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=8801946&dur=490.021&lmt=1586944886409260&mt=1586955697&fvip=4&keepalive=yes&fexp=23882514&beids=9466586&c=WEB&txp=2311222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIhAIW9PA2R7tnonSXsW3072mh7mrFQ7Xbpis40mr92halBAiAcX1vHrCBrGcDoiZR7E1MuKbYZ2aJuw_DOBPLTDm589g%3D%3D&sig=AJpPlLswRAIgP0SdeCp4r120qak2VVsk4M6Q4LXbYvvlMmI4yqf5B1cCIDgsM4guaH6ztoN6GJ3EJpfZe2NV9C1onE6YGDgS6-xR&ratebypass=yes'
[download] Destination: Dynacom - Cloud Mattress [Auditen Music]-ypq3E3sPWTg.f251.webm
[download] 100% of 8.39MiB in 00:01
[ffmpeg] Merging formats into "Dynacom - Cloud Mattress [Auditen Music]-ypq3E3sPWTg.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Dynacom - Cloud Mattress [Auditen Music]-ypq3E3sPWTg.f136.mp4' -i 'file:Dynacom - Cloud Mattress [Auditen Music]-ypq3E3sPWTg.f251.webm' -c copy -map '0:v:0' -map '1:a:0' 'file:Dynacom - Cloud Mattress [Auditen Music]-ypq3E3sPWTg.temp.mkv'
Deleting original file Dynacom - Cloud Mattress [Auditen Music]-ypq3E3sPWTg.f136.mp4 (pass -k to keep)
Deleting original file Dynacom - Cloud Mattress [Auditen Music]-ypq3E3sPWTg.f251.webm (pass -k to keep)
```

regards Oneboy1979

**Comment by dstftw** [comment]
`--rm-cache-dir`.

**Comment by worstenbrood** [comment]
sorry for wasting your time, maybe a better error would make things a bit clearer?
Thanks!
