### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by CouponCodeSwap** [ytdl-org/youtube-dl#24801]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl -v --add-metadata -f 'bestvideo[ext=webm]+bestaudio[ext=webm]' -o '%(title)s.%(ext)s' --write-all-thumbnails --write-info-json "https://www.youtube.com/watch?v=rrVDATvUitA";

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--add-metadata', '-f', 'bestvideo[ext=webm]+bestaudio[ext=webm]', '-o', '%(title)s.%(ext)s', '--write-all-thumbnails', '--write-info-json', 'https://www.youtube.com/watch?v=rrVDATvUitA']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.2 (CPython) - Linux-5.6.4-zen1-1-zen-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[youtube] rrVDATvUitA: Downloading webpage
[youtube] {18} signature length 106, html5 player vflset
[youtube] {135} signature length 106, html5 player vflset
[youtube] {244} signature length 106, html5 player vflset
[youtube] {397} signature length 106, html5 player vflset
[youtube] {134} signature length 106, html5 player vflset
[youtube] {243} signature length 106, html5 player vflset
[youtube] {396} signature length 106, html5 player vflset
[youtube] {133} signature length 106, html5 player vflset
[youtube] {242} signature length 106, html5 player vflset
[youtube] {395} signature length 106, html5 player vflset
[youtube] {160} signature length 106, html5 player vflset
[youtube] {278} signature length 106, html5 player vflset
[youtube] {394} signature length 102, html5 player vflset
[youtube] {140} signature length 106, html5 player vflset
[youtube] {249} signature length 102, html5 player vflset
[youtube] {250} signature length 106, html5 player vflset
[youtube] {251} signature length 106, html5 player vflset
[info] Writing video description metadata as JSON to: Air - Johann Sebastian Bach.info.json
[youtube] rrVDATvUitA: Downloading thumbnail ...
[youtube] rrVDATvUitA: Writing thumbnail to: Air - Johann Sebastian Bach.jpg
[debug] Invoking downloader on 'https://r1---sn-hp57knsl.googlevideo.com/videoplayback?expire=1586994721&ei=wUmXXquMLImthgaDtKWICg&ip=86.106.87.68&id=o-AOIpyuLThp3QZ_r_d0mwX1ID8itrvzXDYkvE9HWJWdOX&itag=244&aitags=133%2C134%2C135%2C160%2C242%2C243%2C244%2C278%2C394%2C395%2C396%2C397&source=youtube&requiressl=yes&mh=Z1&mm=31%2C29&mn=sn-hp57knsl%2Csn-hp57yn7y&ms=au%2Crdu&mv=m&mvi=0&pl=24&initcwndbps=448750&vprv=1&mime=video%2Fwebm&gir=yes&clen=6062782&dur=338.600&lmt=1575002887235581&mt=1586973029&fvip=1&keepalive=yes&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIhAIznwegwKvfmLflVcnF7aqxjIo0MLHBq6iOv9ZBNGgSpAiAw6hTrOiP-q-8Uz3efrI5R5Mo42Ymw2H7o8G2kGfVVMQ%3D%3D&sig=zJAJpPlAswRQIgWEqGi7hzLgl1J3yxHKbglnwuL_UZLxzIkjNz0dURywcVIQCQwiE1-nhGt9-Ql=zqVA0dil0DxGxOkfJ4bet2CrgieC&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

## Description

Since yesterday, I am receiving the following error when attempting any download from YouTube.

`ERROR: unable to download video data: HTTP Error 403: Forbidden
`

There is no problem downloading from YouTube using other plugins.

**Comment by CouponCodeSwap** [comment]
For anyone who stumbles on this issue, the fix is as follows… Run:

`youtube-dl --rm-cache-dir";
`
After doing so, youtube-dl is functioning properly again. If not too difficult to add, including instructions to do this with the error message would help anyone in the future to fix it themselves. For example:

`ERROR: unable to download video data: HTTP Error 403: Forbidden
If you are receiving this error, try running the following command: youtube-dl --rm-cache-dir. If the problem persists, file a bug report.`

Thanks for the great plugin btw, glad it is working again!
