### ISSUE TITLE
Trying to download any Youtube Video results in: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by keksimusmaximus** [ytdl-org/youtube-dl#24809]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl https://youtube.com/watch?v=dX3k_QDnzHE -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://youtube.com/watch?v=dX3k_QDnzHE', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.2 (CPython) - Linux-5.6.3-2-MANJARO-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] dX3k_QDnzHE: Downloading webpage
[youtube] {18} signature length 106, html5 player vflset
[youtube] {136} signature length 106, html5 player vflset
[youtube] {247} signature length 106, html5 player vflset
[youtube] {398} signature length 102, html5 player vflset
[youtube] {135} signature length 106, html5 player vflset
[youtube] {244} signature length 106, html5 player vflset
[youtube] {397} signature length 102, html5 player vflset
[youtube] {134} signature length 102, html5 player vflset
[youtube] {243} signature length 106, html5 player vflset
[youtube] {396} signature length 102, html5 player vflset
[youtube] {133} signature length 106, html5 player vflset
[youtube] {242} signature length 102, html5 player vflset
[youtube] {395} signature length 106, html5 player vflset
[youtube] {160} signature length 106, html5 player vflset
[youtube] {278} signature length 106, html5 player vflset
[youtube] {394} signature length 106, html5 player vflset
[youtube] {140} signature length 106, html5 player vflset
[youtube] {249} signature length 106, html5 player vflset
[youtube] {250} signature length 102, html5 player vflset
[youtube] {251} signature length 102, html5 player vflset
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r2---sn-fvcjvh-cfxe.googlevideo.com/videoplayback?expire=1587042694&ei=JgWYXrC0GMfMgAebw4nwBA&ip=XXX.XXX.XXX.XXX&id=o-AIBqukg-KjbDaY-vkpcPv1IvyRj2LgAyK-sysHl4shF4&itag=247&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C394%2C395%2C396%2C397%2C398&source=youtube&requiressl=yes&mh=bJ&mm=31%2C29&mn=sn-fvcjvh-cfxe%2Csn-4g5ednly&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=23&initcwndbps=1183750&vprv=1&mime=video%2Fwebm&gir=yes&clen=11882038&dur=243.160&lmt=1584143713711843&mt=1587020977&fvip=3&keepalive=yes&beids=9466586&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIhANj_noEqDdaNyOb5nEDfD09QYm85lXu14rDyMKVW93nRAiA_mw7ix0W8h-kLO_vBaOw-vzOPZSbxJfc8-oUVQ1z8zw%3D%3D&sig=yHKr5rO-_wih5fycfEmCkcovlBtY4hFgSOPB4cUwEWDQICMZRJdXZKa2zQJ2ibqyLXkAemFaX-mksN7y2TH2t6TbSgIQRwsAlPp&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

```

## Description

Trying to download a youtube video results in HTTP Error 403. I've tried several yt videos but the result is the same on any of them.

**Comment by kiney** [comment]
I found several similiar tickets with "duplicate" label, but where is the real ticket?

**Comment by adamiss5138** [comment]
**--rm-cache-dir** did not help. Still getting **ERROR: This video is unavailable** on every video. Tried with cookies and without.

**Comment by irgendwr** [comment]
@kiney https://github.com/ytdl-org/youtube-dl/issues/23638 mentions the solution:
`youtube-dl --rm-cache-dir`.

It was mention multiple times already, e.g. in https://github.com/ytdl-org/youtube-dl/issues/24713

**Comment by heshang233** [comment]
> @kiney #23638 mentions the solution:
> `youtube-dl --rm-cache-dir`.
> 
> It was mentioned multiple times already, e.g. in #24713

It doesn't solve the problem completely.
It happens every once in a while.
I think it should be fixed.
