### ISSUE TITLE
Adult Swim non credential videos failing to download

### ISSUE THREAD

**Issue by defekTiVEGT** [ytdl-org/youtube-dl#24807]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe --verbose -f best https://www.adultswim.com/videos/samurai-jack/xxv
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'best', 'https://www.adultswim.com/videos/samurai-jack/xxv']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[AdultSwim] xxv: Downloading JSON metadata
[AdultSwim] 78baf6795f23fcf2b88bff965f66bf814b54a0a1: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('media',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\adultswim.py", line 163, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\turner.py", line 200, in _extract_ngtv_info
KeyError: 'media'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\adultswim.py", line 163, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\turner.py", line 200, in _extract_ngtv_info
KeyError: 'media'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 543, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('media',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Certain unlocked/public episodes of shows fail to download.
known broken are https://www.adultswim.com/videos/samurai-jack/xxv
and https://www.adultswim.com/videos/samurai-jack/xxxvi

**Comment by HaskuldrKrionskij** [comment]
**X** I've checked that all provided URLs are alive and playable in a browser
> Certain unlocked/public episodes of shows fail to download.

![image](https://user-images.githubusercontent.com/56414180/79439963-20eb9a00-7fde-11ea-9a68-958f9de8a12a.png)
![image](https://user-images.githubusercontent.com/56414180/79440469-b6872980-7fde-11ea-979a-a5a73166ec74.png)
Other episodes blocked.

**Comment by defekTiVEGT** [comment]
The episodes/shows in question are indeed unlocked for free with no login in the USA and playable in browser.

**Comment by HaskuldrKrionskij** [comment]
@defekTiVEGT 
Oh, sorry, I thought about it, but believed in the power of democracy. Sorry again for the "fake", I should have checked this nuance.

**Comment by Blockmaster987** [comment]
I've run into the same issue. I hope this thread becomes solved before April 30th and the episodes lock again.
