### ISSUE TITLE
Youtube-dl stopped working after update - please help

### ISSUE THREAD

**Issue by ijbh** [ytdl-org/youtube-dl#24810]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, I updated to the latest version of youtube-dl and it suddenly stopped working on all sites for me. I'm using brew on Terminal. This is the error message that I get:

ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 16, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 15, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/options.py", line 8, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/__init__.py", line 3, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 10, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 29, in <module>
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: dlopen(/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so
  Reason: image not found

**Comment by dstftw** [comment]
Broken SSL setup, nothing to do with youtube-dl.

**Comment by potsky** [comment]
@ijbh Do you have found a solution ? Same problem this morning :-(

**Comment by nicooprat** [comment]
I got the same issue on Mac OSX High Sierra (10.13.6), resolved with `brew switch openssl 1.0.2s`.

https://stackoverflow.com/a/59184347/758728

**Comment by potsky** [comment]
I did not work for me because I use `youtube-dl` to extract a m3u8 file and `youtube-dl` uses  `ffmpeg` :
- `youtube-dl` ssl 1.0.0
- `ffmpeg` ssl 1.1
- `me` 🔫

It finally works:
- reinstall ssl 1.0.0 (`youtube-dl` starts but crashes as soon as it uses `ffmpeg`)
- backup directory `/usr/local/opt/openssl/lib` soemwhere
- reinstall ssl 1.1 (`youtube-dl` crashes at start)
- `cp ~/Desktop/libcrypto.1.0.0.dylib /usr/local/opt/openssl/lib/.`
- `cp ~/Desktop/libssl.1.0.0.dylib /usr/local/opt/openssl/lib/.`
- everybody is happy ;-)

**Comment by mulholio** [comment]
Uninstalling with brew and reinstalling with pip fixed this for me.

**Comment by threalboss** [comment]
> I got the same issue on Mac OSX High Sierra (10.13.6), resolved with `brew switch openssl 1.0.2s`.
> 
> https://stackoverflow.com/a/59184347/758728

It seams that Brew has removed the switch command. I am not the most knowledgeable so do you have any other recommendations for fixing this issue?

**Comment by threalboss** [comment]
> > I got the same issue on Mac OSX High Sierra (10.13.6), resolved with `brew switch openssl 1.0.2s`.
> > https://stackoverflow.com/a/59184347/758728
> 
> It seams that Brew has removed the switch command. I am not the most knowledgeable so do you have any other recommendations for fixing this issue?

I was able to get it to work by doing: 
`brew install rbenv/tap/openssl@1.0`
`ln -sfn /usr/local/Cellar/openssl@1.0/1.0.2t /usr/local/opt/openssl
`

From: https://stackoverflow.com/a/65494858
