### ISSUE TITLE
Viki.com is now using manifest.mpd and Error 403 with using premium account

### ISSUE THREAD

**Issue by zackmark29** [ytdl-org/youtube-dl#24826]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

HERE'S THE LOG FOR VIKI MANIFEST.MPD LINK
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://manifest-kcp.viki.io/v1/1080827v/akamai/main/mpd/normal/kcp/high/mpdhd/kcp/dt2_dt3/manifest.mpd?app=100000a&tag=mpdhd:high:kcp:sourceKCP:mpd:uncached:dt2_dt3&h_timestamp=1587086837&u=13306070u&h_request_id=&h_country=us&h_host=hyperion-595f9dfdff-pq77m&h_data_center=iowa&sig=723ad2dc1fd8e11469084750bac4e4e2320b155c', '--verbose', 'flag']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[generic] manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest: Downloading webpage
[generic] manifest: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\generic.py", line 2397, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

AND HERE'S THE LOG FOR THE ORIGINAL LINK WITH PREMIUM ACCOUNT

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'C:\\Users\\MARK\\Downloads\\cookies (6).txt', '--username', 'PRIVATE', '--password', 'PRIVATE', '--socket-timeout', '30', '--skip-download', 'https://www.viki.com/videos/1080827v-you-are-the-best-episode-14', '--verbose', 'flag']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[viki] Logging in
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

## Description

Here's the link for the video: 
https://www.viki.com/videos/1080827v-you-are-the-best-episode-14

and here's the link for manifest.mpd
https://manifest-kcp.viki.io/v1/1080827v/akamai/main/mpd/normal/kcp/high/mpdhd/kcp/dt2_dt3/manifest.mpd?app=100000a&tag=mpdhd:high:kcp:sourceKCP:mpd:uncached:dt2_dt3&h_timestamp=1587086837&u=13306070u&h_request_id=&h_country=us&h_host=hyperion-595f9dfdff-pq77m&h_data_center=iowa&sig=723ad2dc1fd8e11469084750bac4e4e2320b155c

Just this week, viki.com already changed the m3u8 to manifest.mpd that's why maybe we are getting error when downloading with using credential.

I already tried using cookies and increasing time out but I still getting the error

**Comment by zackmark29** [comment]
If i tried to download for example subtitle, I can download without account
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--proxy', '89.33.192.136:3128', '--write-sub', '--sub-lang', 'en', '--sub-format', 'srt', '--skip-download', '-f', 'best', 'https://www.viki.com/videos/1080827v-you-are-the-best-episode-14', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {'http': '89.33.192.136:3128', 'https': '89.33.192.136:3128'}
[viki] 1080827v: Downloading video JSON
[viki] 1080827v: Downloading video streams JSON
[info] Writing video subtitles to: You Are The Best - Episode 14-1080827v.en.srt


But if I use my premium account, I'm getting the same error
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--write-sub', '--sub-lang', 'en', '--sub-format', 'srt', '--skip-download', '-f', 'best', 'https://www.viki.com/videos/1080827v-you-are-the-best-episode-14', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[viki] Logging in
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default


I want to use with account so that I can download 1080p resolution like before.

**Comment by zackmark29** [comment]
Could you link me the duplicate issue? so that i can subscribe
