### ISSUE TITLE
YouTube 403 Forbidden error

### ISSUE THREAD

**Issue by probablykasper** [ytdl-org/youtube-dl#24842]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
kasper-imac-2019:Downloads kasper$ youtube-dl "https://www.youtube.com/watch?v=hY-yijB6CgE" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=hY-yijB6CgE', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.1 (CPython) - macOS-10.14.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] hY-yijB6CgE: Downloading webpage
[youtube] {18} signature length 108, html5 player vflset
[youtube] {137} signature length 108, html5 player vflset
[youtube] {248} signature length 108, html5 player vflset
[youtube] {299} signature length 108, html5 player vflset
[youtube] {303} signature length 108, html5 player vflset
[youtube] {399} signature length 108, html5 player vflset
[youtube] {136} signature length 108, html5 player vflset
[youtube] {247} signature length 108, html5 player vflset
[youtube] {298} signature length 108, html5 player vflset
[youtube] {302} signature length 108, html5 player vflset
[youtube] {398} signature length 108, html5 player vflset
[youtube] {135} signature length 104, html5 player vflset
[youtube] {244} signature length 108, html5 player vflset
[youtube] {397} signature length 108, html5 player vflset
[youtube] {134} signature length 108, html5 player vflset
[youtube] {243} signature length 108, html5 player vflset
[youtube] {396} signature length 108, html5 player vflset
[youtube] {133} signature length 108, html5 player vflset
[youtube] {242} signature length 108, html5 player vflset
[youtube] {395} signature length 104, html5 player vflset
[youtube] {160} signature length 108, html5 player vflset
[youtube] {278} signature length 104, html5 player vflset
[youtube] {394} signature length 104, html5 player vflset
[youtube] {140} signature length 108, html5 player vflset
[youtube] {249} signature length 108, html5 player vflset
[youtube] {250} signature length 108, html5 player vflset
[youtube] {251} signature length 108, html5 player vflset
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r1---sn-585pav-ch5e.googlevideo.com/videoplayback?expire=1587166377&ei=SeiZXoiSD6XJ7gSJqLTQAQ&ip=77.247.153.244&id=o-AI98Tlu3nd9UoXZYCCiCS6AzBgmYkno5lq6Ds6S2kVkw&itag=399&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C298%2C299%2C302%2C303%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=1N&mm=31%2C29&mn=sn-585pav-ch5e%2Csn-5goeen7y&ms=au%2Crdu&mv=m&mvi=0&pcm2cms=yes&pl=24&initcwndbps=1512500&vprv=1&mime=video%2Fmp4&gir=yes&clen=27949912&dur=208.949&lmt=1576467020802919&mt=1587144706&fvip=1&keepalive=yes&fexp=23882514&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIgddMcHpqItKq-h0_NmBTUoDRtq03Nqe9a0gPFI6IBaOUCIQDxlEJuFCFJbW6gSUHPuFK6-Z9D6C9JnMf8z4hbMu5Bgw%3D%3D&sig=AJpPlLswRQIgBUcqzvGOmdG1D6rPTAoNLZvI4I6zEeSu=d5sH8JT8EECIQCgtLayQ==s35VAWTw5TzcSYjVuEjiy8b6sQOxH8Nlg&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/Users/kasper/.pyenv/versions/3.8.1/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/Users/kasper/.pyenv/versions/3.8.1/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/Users/kasper/.pyenv/versions/3.8.1/lib/python3.8/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/Users/kasper/.pyenv/versions/3.8.1/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/Users/kasper/.pyenv/versions/3.8.1/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/Users/kasper/.pyenv/versions/3.8.1/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Users/kasper/.pyenv/versions/3.8.1/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Users/kasper/.pyenv/versions/3.8.1/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/Users/kasper/.pyenv/versions/3.8.1/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Users/kasper/.pyenv/versions/3.8.1/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Users/kasper/.pyenv/versions/3.8.1/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

## Description

Downloading from YouTube results in a 403 Forbidden error. First noticed the issue today, may have started happening up to 2 days ago. Using `--no-cache-dir` or deleting `~/.cache/youtube-dl` fixes it.

Here's the `~/.cache` folder where the issue happens:
[cache folder with error.zip](https://github.com/ytdl-org/youtube-dl/files/4494471/cache.folder.with.error.zip)
Here's the `~/.cache` folder after deleting it and re-running youtube-dl:
[cache folder working.zip](https://github.com/ytdl-org/youtube-dl/files/4494476/cache.folder.working.zip)

**Comment by osi** [comment]
I also observed this. Last used v 2020.03.24 to download from Youtube on April 14. `--no-cache-dir` got me past the error as well.

**Comment by CRTejaswi** [comment]
Hey, I was facing the same issue. `--no-cache-dir` does solve it, but I don't know why. It would be helpful if someone explained what disabling caching of files does to help with the download process.

**Comment by ITALIA195** [comment]
Same probably should be reopened
