### ISSUE TITLE
6play.fr Unsupported URL

### ISSUE THREAD

**Issue by ZorGleH** [ytdl-org/youtube-dl#24859]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v https://www.6play.fr/kaamelott-p_888/livre-i-tome-i-episodes-1-a-15-p_1632
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.6play.fr/kaamelott-p_888/livre-i-tome-i-episodes-1-a-15-p_1632']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Darwin-19.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] livre-i-tome-i-episodes-1-a-15-p_1632: Requesting header
WARNING: Falling back on generic information extractor.
[generic] livre-i-tome-i-episodes-1-a-15-p_1632: Downloading webpage
[generic] livre-i-tome-i-episodes-1-a-15-p_1632: Extracting information
ERROR: Unsupported URL: https://www.6play.fr/kaamelott-p_888/livre-i-tome-i-episodes-1-a-15-p_1632
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2375, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 640, column 51
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3352, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.6play.fr/kaamelott-p_888/livre-i-tome-i-episodes-1-a-15-p_1632
```

## Description

Hi,

Trying to download the URL `https://www.6play.fr/kaamelott-p_888/livre-i-tome-i-episodes-1-a-15-p_1632` gives me an `UnsupportedError: Unsupported URL`

Thanks a lot

**Comment by dirkf** [comment]
This looks like a series page, which isn't supported. If anyone can show a series page with a playable episode that can be downloaded, please open a new site feature request, quoting this issue. See #24967.
