### ISSUE TITLE
[generic] WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden (cloudvideo.tv)

### ISSUE THREAD

**Issue by bato3** [ytdl-org/youtube-dl#24854]
## Checklist

- [ ] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://cloudvideo.tv/embed-yb46qfa158gf.html', u'-v', u'-g']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-8-amd64-x86_64-with-debian-9.6
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1, phantomjs 2.1.1
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: Unsupported URL: https://cloudvideo.tv/embed-yb46qfa158gf.html
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 2375, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "./youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "./youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 22, column 309
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 3352, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://cloudvideo.tv/embed-yb46qfa158gf.html

```

## Description
in raw HTML is this link, but they can't download
```
<source src="https://s26.cdncv.net/hls/,mfqjwu6bvpo6sr7qw53e3mi7xpv2ltbazpiresng755flapk6hndr5ufrg7a,.urlset/master.m3u8" type="application/x-mpegURL"></source>
```

Headers from browser
```
Host: s26.cdncv.net
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
Accept: */*
Accept-Language: pl
Accept-Encoding: gzip, deflate, br
Referer: https://cloudvideo.tv/embed-yb46qfa158gf.html
Origin: https://cloudvideo.tv
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

I can download video by `curl` and raw link:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'https://s26.cdncv.net/hls/,mfqjwu6bvpo6sr7qw53e3mi7xpv2ltbazpiresng755flapk6hndr5ufrg7a,.urlset/master.m3u8', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-8-amd64-x86_64-with-debian-9.6
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] master: Requesting header
[generic] master: Downloading m3u8 information
[info] Available formats for master:
format code  extension  resolution note
798          mp4        1280x720    798k , avc1.64001f, 30.0fps, mp4a.40.2
```

**Comment by Isayso** [comment]
get similar error 403 on many Youtube videos. Sometimes only video part will be downloaded.    

    youtube-dl  -v https://www.youtube.com/watch?v=ia1iuXbEaYQ
    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=ia1iuXbEaYQ']
    [debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
    [debug] youtube-dl version 2020.03.24
    [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
    [debug] exe versions: ffmpeg N-94911-g197985c5bf, ffprobe N-94911-g197985c5bf
    [debug] Proxy map: {}
    [youtube] ia1iuXbEaYQ: Downloading webpage
    [youtube] {18} signature length 104, html5 player vflset
    [youtube] {137} signature length 108, html5 player vflset
    [youtube] {248} signature length 108, html5 player vflset
    [youtube] {399} signature length 108, html5 player vflset
    [youtube] {136} signature length 108, html5 player vflset
    [youtube] {247} signature length 108, html5 player vflset
    [youtube] {398} signature length 108, html5 player vflset
    [youtube] {135} signature length 108, html5 player vflset
    [youtube] {244} signature length 104, html5 player vflset
    [youtube] {397} signature length 104, html5 player vflset
    [youtube] {134} signature length 104, html5 player vflset
    [youtube] {243} signature length 104, html5 player vflset
    [youtube] {396} signature length 108, html5 player vflset
    [youtube] {133} signature length 104, html5 player vflset
    [youtube] {242} signature length 104, html5 player vflset
    [youtube] {395} signature length 108, html5 player vflset
    [youtube] {160} signature length 108, html5 player vflset
    [youtube] {278} signature length 108, html5 player vflset
    [youtube] {394} signature length 108, html5 player vflset
    [youtube] {140} signature length 108, html5 player vflset
    [youtube] {249} signature length 108, html5 player vflset
    [youtube] {250} signature length 108, html5 player vflset
    [youtube] {251} signature length 108, html5 player vflset
    [debug] Default format spec: bestvideo+bestaudio/best
    WARNING: Requested formats are incompatible for merge and will be merged into mkv.
    [debug] Invoking downloader on 'https://r6---sn-8xgn5uxa-quhl.googlevideo.com/videoplayback?expire=1587327457&ei=gV2cXt3kM6aR8gOZ85WwBw&ip=92.116.12.63&id=o-AKD890_hRZV0_irk7TqLbkd2zrwkTkWHhueDTQNNU5fI&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=pX&mm=31%2C26&mn=sn-8xgn5uxa-quhl%2Csn-5hne6nsr&ms=au%2Conr&mv=m&mvi=5&pl=20&gcr=de&initcwndbps=1540000&vprv=1&mime=video%2Fmp4&gir=yes&clen=105074900&dur=223.514&lmt=1579463278267525&mt=1587305735&fvip=4&keepalive=yes&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRAIgS9VmBZBVjmR3IoSrpXM71XVpb2g91ShDf51xJElNLh0CIDHYIhqHmmLhOKdTEcScmRVv4vKmGpua0mccwl1xz4iJ&sig=AJpPlLswRgIhALYo_fLGt4cAPotnpNT7umL3sifQ01kj=TNlafrTN69GAiE7-XLFpooAxF1n6e9xkAacL2W0ZZMq-BOaaJxSO71e&ratebypass=yes'
    ERROR: unable to download video data: HTTP Error 403: Forbidden
    Traceback (most recent call last):
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1920, in process_info
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1865, in dl
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\common.py", line 366, in download
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\http.py", line 341, in real_download
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\http.py", line 109, in establish_connection
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
      File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
      File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
      File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
      File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
      File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
    urllib.error.HTTPError: HTTP Error 403: Forbidden
