### ISSUE TITLE
usatoday.com results with "no video on page"

### ISSUE THREAD

**Issue by someziggyman** [ytdl-org/youtube-dl#24865]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v -F https://www.usatoday.com/story/money/2020/04/17/remdesivir-coronavirus-drug-gilead-sciences-covid-19-treatment/5150793002/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.usatoday.com/story/money/2020/04/17/remdesivir-coronavirus-drug-gilead-sciences-covid-19-treatment/5150793002/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[USAToday] 5150793002: Downloading webpage
ERROR: no video on the webpage
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/usatoday.py", line 50, in _real_extract
    raise ExtractorError('no video on the webpage', expected=True)
ExtractorError: no video on the webpage


## Description

<!--
Provide an explanation of your issue in an arbitrary form. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

However, I'm able to download a video using this URL:
https://hlsmedia.gannett-cdn.com/authoring/video-renditions/d2fb38fe-811e-4b93-acd7-ded8dda8efb8/065950b2-f0ee-4b37-ae6a-03c9082cf922/1080p_30fps,720p_30fps,480p_30fps,master.m3u8
Had to use "inspect element" in browser for it. Is this something that can be fixed? or am I missing something?

**Comment by socialAPIS** [comment]
.m3u8 is not a video format
