### ISSUE TITLE
[youtube] Age-gate bypass broken

### ISSUE THREAD

**Issue by tr13dm03** [ytdl-org/youtube-dl#24869]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--embed-thumbnail', u'--add-metadata', u'--all-subs', u'--embed-subs', u'-i', u'-v', u'https://www.youtube.com/watch?v=HNK1YjheVUA']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-8-amd64-x86_64-with-debian-10.3
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1
[debug] Proxy map: {}
[youtube] HNK1YjheVUA: Downloading webpage
[youtube] HNK1YjheVUA: Downloading embed webpage
[youtube] HNK1YjheVUA: Refetching age-gated info webpage
[youtube] {18} signature length 108, html5 player vflset
[youtube] {137} signature length 108, html5 player vflset
[youtube] {248} signature length 108, html5 player vflset
[youtube] {299} signature length 104, html5 player vflset
[youtube] {303} signature length 108, html5 player vflset
[youtube] {399} signature length 108, html5 player vflset
[youtube] {136} signature length 108, html5 player vflset
[youtube] {247} signature length 108, html5 player vflset
[youtube] {298} signature length 108, html5 player vflset
[youtube] {302} signature length 104, html5 player vflset
[youtube] {398} signature length 108, html5 player vflset
[youtube] {135} signature length 104, html5 player vflset
[youtube] {244} signature length 108, html5 player vflset
[youtube] {397} signature length 108, html5 player vflset
[youtube] {134} signature length 108, html5 player vflset
[youtube] {243} signature length 104, html5 player vflset
[youtube] {396} signature length 104, html5 player vflset
[youtube] {133} signature length 108, html5 player vflset
[youtube] {242} signature length 108, html5 player vflset
[youtube] {395} signature length 104, html5 player vflset
[youtube] {160} signature length 108, html5 player vflset
[youtube] {278} signature length 108, html5 player vflset
[youtube] {394} signature length 104, html5 player vflset
[youtube] {140} signature length 104, html5 player vflset
[youtube] {249} signature length 108, html5 player vflset
[youtube] {250} signature length 108, html5 player vflset
[youtube] {251} signature length 108, html5 player vflset
WARNING: video doesn't have subtitles
[debug] Default format spec: bestvideo+bestaudio/best
[youtube] HNK1YjheVUA: Downloading thumbnail ...
[youtube] HNK1YjheVUA: Writing thumbnail to: MMV -  United Sexi Boyz - Can't Get You Out Of My Head (La La La)-HNK1YjheVUA.jpg
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r1---sn-xaxjugvopjcvm-t0as.googlevideo.com/videoplayback?expire=1587290269&ei=PcybXpqZD5XhgwPa-q7gBw&ip=192.222.188.157&id=o-AI6j-Ye1GqlBHilcfFlzRyxIJhnn_te3PZzgfSZ9Th4l&itag=299&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C298%2C299%2C302%2C303%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=ca&mm=31%2C29&mn=sn-xaxjugvopjcvm-t0as%2Csn-t0a7ln7d&ms=au%2Crdu&mv=m&mvi=0&pl=19&initcwndbps=1051250&vprv=1&mime=video%2Fmp4&gir=yes&clen=134675427&dur=186.866&lmt=1577539476030300&mt=1587268656&fvip=5&keepalive=yes&c=WEB&txp=5311222&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIgS-NnTVUH8XBTLxkkVGtbdKGJ47rk8poL0wn2g4w8boACIQDKZ_5BFofrzSkX1jsZgYT086HzjE-uGFtrb_QAE3cTwg%3D%3D&sig=AJpPlLswRAIgEumY7CUOApLFWYrwiGXE4MEu3y2zQ4fMbabYmcQEvdMRIC4UW_sjilGoYZnTQL_IB35VV7zuTkwDttFy1521pCZRZ&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/alice/.local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/home/alice/.local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/home/alice/.local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/home/alice/.local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/home/alice/.local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/alice/.local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

## Description

All videos which require login for age-gating are no longer downloadable from youtube-dl with the age-gate bypass.

This issue differs from similar ones in the error message it returns and how many steps are seemingly successfully completed before an error.

The issue has existed since early March at minimum.

**Comment by dstftw** [comment]
You must authenticate. There is no longer way to bypass.

**Comment by vaaski** [comment]
@dstftw but you're still able to watch age-restricted videos through the embedded player in a fresh unauthenticated incognito session.
