### ISSUE TITLE
unable to extract html5 player

### ISSUE THREAD

**Issue by ddestan21** [ytdl-org/youtube-dl#24873]
```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1385, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js';```

**Comment by ddestan21** [comment]
curl binary directory from org and it worked. Issue was on fedora.
