### ISSUE TITLE
[youtube] Error 404: Not Found on googlevideo.com

### ISSUE THREAD

**Issue by ddevault** [ytdl-org/youtube-dl#24876]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
WARNING: parsing .netrc: No authenticators for youtube (None, line None)
[youtube] mZyvIHYn2zk: Downloading webpage
[youtube] mZyvIHYn2zk: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
ERROR: unable to download video data: HTTP Error 404: Not Found
[2:20:53] homura /tmp $ youtube-dl -v "https://www.youtube.com/watch?v=mZyvIHYn2zk"
[debug] System config: []
[debug] User config: ['--netrc']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=mZyvIHYn2zk']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.2 (CPython) - Linux-5.6.4-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: parsing .netrc: No authenticators for youtube (None, line None)
[youtube] mZyvIHYn2zk: Downloading webpage
[youtube] mZyvIHYn2zk: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r3---sn-8xgp1vo-2iae.googlevideo.com/videoplayback?expire=1587330905&ei=-WqcXpWqMcXj8gTRt5_YDw&ip=173.49.88.209&id=o-AOUR7SwcFxm94rIwS9cg3TqP1RizMRIURILjn7tXRkN0&itag=247&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=yt_otf&requiressl=yes&mh=mm&mm=31%2C29&mn=sn-8xgp1vo-2iae%2Csn-ab5l6n6l&ms=au%2Crdu&mv=m&mvi=2&pl=16&initcwndbps=873750&vprv=1&mime=video%2Fwebm&otf=1&otfp=1&dur=3755.199&lmt=1520178130015828&mt=1587309221&fvip=3&keepalive=yes&fexp=23882514&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cotf%2Cotfp%2Cdur%2Clmt&sig=AJpPlLswRAIgSR_mYrxGFVg3kKd9XG9oyVVVIeHXmQFKW5kvqc3EZuUCIHSsXEAmpKjfEiKmqGHXuOXpA3ICsblkdTTPx5bBZ3SR&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRgIhAI9LQLqC2egQQUf701TZ4nxuMRJJQzIHdmYDZcS1kPvhAiEA5ddI8JkUeNhQ0c6sDI_9q7NahXyIEzaQmcEcszMSsuw%3D&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

## Description

`youtube-dl "https://www.youtube.com/watch?v=mZyvIHYn2zk"` fails with a 404 error, but is playable in the browser. I updated to the latest git master and was still able to reproduce this problem.

**Comment by dstftw** [comment]
Server side Youtube issue for format 247.

**Comment by ddevault** [comment]
I don't understand - it plays fine on the web.

**Comment by faxotherapy** [comment]
Same issue here :
```shell
$ youtube-dl --version
2020.03.24

$ youtube-dl -F https://www.youtube.com/watch\?v\=02Q9IO7kcH4                                           [youtube] 02Q9IO7kcH4: Downloading webpage
[info] Available formats for 02Q9IO7kcH4:
format code  extension  resolution note
140          m4a        audio only tiny  130k , m4a_dash container, mp4a.40.2@128k (44100Hz), 9.76MiB
251          webm       audio only tiny  141k , opus @160k (48000Hz), 10.02MiB
278          webm       256x144    144p   95k , webm container, vp9, 30fps, video only
160          mp4        256x144    144p  108k , avc1.4d400b, 30fps, video only
242          webm       426x240    240p  220k , vp9, 30fps, video only
133          mp4        426x240    240p  242k , avc1.4d400c, 30fps, video only
134          mp4        640x360    360p  250k , avc1.4d401e, 30fps, video only, 5.83MiB
243          webm       640x360    360p  405k , vp9, 30fps, video only
244          webm       854x480    480p  752k , vp9, 30fps, video only
135          mp4        854x480    480p 1155k , avc1.4d4014, 30fps, video only
247          webm       1280x720   720p 1505k , vp9, 30fps, video only
136          mp4        1280x720   720p 2310k , avc1.4d4016, 30fps, video only
302          webm       1280x720   720p60 2646k , vp9, 60fps, video only
248          webm       1920x1080  1080p 2646k , vp9, 30fps, video only
298          mp4        1280x720   720p60 3465k , avc1.4d4016, 60fps, video only
137          mp4        1920x1080  1080p 4331k , avc1.64001e, 30fps, video only
303          webm       1920x1080  1080p60 4410k , vp9, 60fps, video only
299          mp4        1920x1080  1080p60 4478k , avc1.64002a, 60fps, video only, 49.22MiB
18           mp4        640x360    360p  254k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 19.14MiB
22           mp4        1280x720   720p  687k , avc1.64001F, mp4a.40.2@192k (44100Hz) (best)

$ youtube-dl -f 137+140 https://www.youtube.com/watch\?v\=02Q9IO7kcH4                                   [youtube] 02Q9IO7kcH4: Downloading webpage
ERROR: unable to download video data: HTTP Error 404: Not Found
```

Yet, this video is playable on YouTube itself.
