### ISSUE TITLE
ExtractorError: No video formats found

### ISSUE THREAD

**Issue by tbhaxor** [ytdl-org/youtube-dl#24881]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '-o', '%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s', '--min-sleep-interval', '30', '--max-sleep-interval', '60', 'https://app.pluralsight.com/library/courses/windows-debugging-fundamentals', '--playlist-start', '1', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.7.7 (CPython) - Linux-5.4.31-1-MANJARO-x86_64-with-arch-Manjaro-Linux
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, rtmpdump 2.4
[debug] Proxy map: {}
[pluralsight:course] windows-debugging-fundamentals: Downloading JSON metadata
[download] Downloading playlist: Windows Kernel Debugging Fundamentals
[pluralsight:course] playlist Windows Kernel Debugging Fundamentals: Collected 61 video ids (downloading 61 of them)
[download] Downloading video 1 of 61
[pluralsight] Downloading login page
[pluralsight] Logging in
[pluralsight] windows-debugging-fundamentals-m1-intro-0: Downloading JSON metadata
[pluralsight] windows-debugging-fundamentals-m1-intro-0: Downloading mp4-high viewclip graphql
[pluralsight] windows-debugging-fundamentals-m1-intro-0: Downloading mp4-high viewclip JSON
```

## Description

Unable to download the videos from Pluralsight. The playlist consists of 61 videos as you can see in the debug log. Earlier with the same command, I downloaded 40 videos, it then raised the same error, so I tried executing the same command once again and getting this error again and again. Some time luckily it progresses to 3rd video on the playlist then same error `

**Comment by jaimebl** [comment]
I can't see any error message in the log provided.

If you were able to download 40 videos. Are you executing the command again starting from video 41 by doing this? `--playlist-start 41`

Have you tried yourself getting into pluralsight with your browser and playing the video you're unable to download? Your account might be banned.

**Comment by tbhaxor** [comment]
@jaimebl Account is not banned. I can access my enrolled courses on web

**Comment by tbhaxor** [comment]
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '-o', '%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s', '--min-sleep-interval', '30', '--max-sleep-interval', '60', 'https://app.pluralsight.com/library/courses/windows-debugging-fundamentals', '--playlist-start', '41', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.7.7 (CPython) - Linux-5.4.31-1-MANJARO-x86_64-with-arch-Manjaro-Linux
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, rtmpdump 2.4
[debug] Proxy map: {}
[pluralsight:course] windows-debugging-fundamentals: Downloading JSON metadata
[download] Downloading playlist: Windows Kernel Debugging Fundamentals
[pluralsight:course] playlist Windows Kernel Debugging Fundamentals: Collected 61 video ids (downloading 21 of them)
[download] Downloading video 1 of 21
[pluralsight] Downloading login page
[pluralsight] Logging in
[pluralsight] windows-debugging-fundamentals-m8-processors-0: Downloading JSON metadata
[pluralsight] windows-debugging-fundamentals-m8-processors-0: Downloading mp4-high viewclip graphql
[pluralsight] windows-debugging-fundamentals-m8-processors-0: Downloading mp4-high viewclip JSON
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] windows-debugging-fundamentals-m8-processors-0: Waiting for 3 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/terabyte/anaconda3/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/terabyte/anaconda3/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/terabyte/anaconda3/lib/python3.7/site-packages/youtube_dl/extractor/pluralsight.py", line 421, in _real_extract
    self._sort_formats(formats)
  File "/home/terabyte/anaconda3/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

PS: I have also tried using different IP and TOR, same error

**Comment by jaimebl** [comment]
Can't reproduce your issue, I'm using same youtube-dl version, same python version, ubuntu wsl OS.
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--min-sleep-interval', '30', '--max-sleep-interval', '60', 'https://app.pluralsight.com/library/courses/windows-debugging-fundamentals', '--playlist-start', '41', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Git HEAD: 049c0486b
[debug] Python version 3.7.7 (CPython) - Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] windows-debugging-fundamentals: Downloading JSON metadata
[download] Downloading playlist: Windows Kernel Debugging Fundamentals
[pluralsight:course] playlist Windows Kernel Debugging Fundamentals: Collected 61 video ids (downloading 21 of them)
[download] Downloading video 1 of 21
[pluralsight] Downloading login page
[pluralsight] Logging in
[pluralsight] windows-debugging-fundamentals-m8-processors-0: Downloading JSON metadata
[pluralsight] windows-debugging-fundamentals-m8-processors-0: Downloading mp4-high viewclip graphql
[pluralsight] windows-debugging-fundamentals-m8-processors-0: Downloading mp4-high viewclip JSON
[pluralsight] windows-debugging-fundamentals-m8-processors-0: Waiting for 2 seconds to avoid throttling
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://vid.pluralsight.com/clips/resolution/11e4fb37-8f56-4469-8c61-91609f84713a/current/mp4/1024x768.mp4?eVKlNH_LYUsSFPRQkXINnGdC9xxMLWFt8VKQ0w3jqSlrcM1F-ifTfY1jZcFPGsQBuxSZkF4v8VboPJf0lIm3z1BuorOHL_hQekH1eP1Z3nbbn7DKeOZwfluRoHhIMFcCacFEKZ7GtcopiCyZC922gjNr-V-hxwEdXRUjpQTL6p5B7rlOSj677VInzawT'
[download] Sleeping 32.71 seconds...
```

**Comment by tbhaxor** [comment]
This is a limitation of Pluralsight itself
