### ISSUE TITLE
ExtractorError: requested format not available

### ISSUE THREAD

**Issue by sebnun** [ytdl-org/youtube-dl#24885]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
~ ❯ youtube-dl -J -flat-playlist -v  https://www.youtube.com/user/RedLetterMedia
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-J', u'-flat-playlist', u'-v', u'https://www.youtube.com/user/RedLetterMedia']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Darwin-19.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1636, in process_video_result
    expected=True)
ExtractorError: requested format not available
```

## Description
```
youtube-dl -J -flat-playlist -v  https://www.youtube.com/user/RedLetterMedia
```

This command used to work a couple of days ago without issue.
I'm using the same youtube-dl version (latest).
I've tested with different IPs on Mac and Linux.

I found this issue https://github.com/ytdl-org/youtube-dl/issues/1667
I tried running:

```
youtube-dl -J -flat-playlist -v --ignore-errors https://www.youtube.com/user/RedLetterMedia
```
looks like it throws the errors for all videos?

```
youtube-dl -J -flat-playlist -v -f 37/22/18/best https://www.youtube.com/user/RedLetterMedia
```

the command never exit

**Comment by sebnun** [comment]
never mind. wrong syntax on my part
