### ISSUE TITLE
Twitter unsupported URL error

### ISSUE THREAD

**Issue by dmitriykalmykov** [ytdl-org/youtube-dl#24896]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe -v "https://twitter.com/VictorKvert2008/statuses/1251621111357456384"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://twitter.com/VictorKvert2008/statuses/1251621111357456384']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 1251621111357456384: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1251621111357456384: Downloading webpage
[generic] 1251621111357456384: Extracting information
ERROR: Unsupported URL: https://twitter.com/VictorKvert2008/statuses/1251621111357456384
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\generic.py", line 3351, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://twitter.com/VictorKvert2008/statuses/1251621111357456384
```

## Description

Can't download some videos from Twitter (unsupported URL error).

**Comment by zanseb** [comment]
Could you try with this url? https://twitter.com/i/status/1251621111357456384

**Comment by Oneboy1979** [comment]
you need only the id so this regex is better:
`https?://(?:(?:www|m(?:obile)?)\.)?twitter\.com/(?:(?:i/web|[^/]+)/(?:status|statuses))/(?P<id>\d+)`

https://regex101.com/r/Fv38pg/6

regards Oneboy1979

**Comment by dmitriykalmykov** [comment]
> Could you try with this url? https://twitter.com/i/status/1251621111357456384
Yes, this URL works. Thanks!
