### ISSUE TITLE
ERROR: Signature extraction failed

### ISSUE THREAD

**Issue by angusyuhin** [ytdl-org/youtube-dl#24894]
## Checklist

-  I'm reporting a broken site support
-  I've verified that I'm running youtube-dl version **2020.03.24**
-  I've checked that all provided URLs are alive and playable in a browser
-  I've checked that all URLs and arguments with special characters are properly quoted or escaped
-  I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/pi/env/local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1385, in _decrypt_signature
    video_id, player_url, s
  File "/home/pi/env/local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

About a month ago, my program can still download youtube videos using youtube-dl. I didn't touch it by modifying the source code or upgrade any package, but when I run the code today this error appear from nowhere. I checked the closed related issues and upgrade my youtube-dl to the newest version but still, the problem exists.

`Requirement already up-to-date: youtube_dl in ./.local/lib/python2.7/site-packages (2020.3.24)`

Actual URL tested: https://www.youtube.com/watch?v=3AtDnEC4zak

Side note: I didn't directly use youtube-dl. Instead, I use pafy and vlc-python to play the music.

**Comment by angusyuhin** [comment]
Later I found out I mixed up the version of the youtube-dl of the entire device and the virtualenv, the package inside the virtualenv didn't update to the newest version. Problem solved after the upgrade.

Sorry for bothering you.
