### ISSUE TITLE
YouTube cannot identify player

### ISSUE THREAD

**Issue by vadimkantorov** [ytdl-org/youtube-dl#24902]
## Checklist

- [v] I'm reporting a broken site support
- [v] I've verified that I'm running youtube-dl version **2020.03.24**
- [v] I've checked that all provided URLs are alive and playable in a browser
- [v] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
vadimkantorov@DESKTOP-4UF8FID:/mnt/c/Users/user/1213$ ../Downloads/youtube-dl.exe 'https://www.youtube.com/embed/Qk3FmuuYeeU' --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/embed/Qk3FmuuYeeU', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.02.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[youtube] Qk3FmuuYeeU: Downloading webpage
[youtube] Qk3FmuuYeeU: Downloading video info webpage
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube
-dl with the --verbose flag and include its complete output.
[youtube] {18} signature length 108, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\youtube.py", line 1385, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\youtube.py", line 1262, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make su
re you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure yo
u are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\youtube.py", line 1385, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\youtube.py", line 1262, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make su
re you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\youtube.py", line 1385, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\youtube.py", line 1262, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make su
re you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\youtube.py", line 2048, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\youtube.py", line 1395, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\youtube.py", line 1385, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\youtube.py", line 1262, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make su
re you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure yo
u are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

WRITE DESCRIPTION HERE

`youtube-dl.exe 'https://youtube.com/watch?v=Qk3FmuuYeeU'` can't find the player plugin (same problem with `streamlink`, so I think this video uses some trick player). In browser everything is well.

**Comment by vadimkantorov** [comment]
Despite running `youtube-dl.exe -U` and printing info about that it updated itself, it did not. So maybe there is some problem in update process.

Sorry for creating this issue. Video works okay on the last version.

**Comment by vadimkantorov** [comment]
I ran this prior to trying this video:
```
vadimkantorov@DESKTOP-4UF8FID:/mnt/c/Users/user/Downloads$ ./youtube-dl.exe -U
Updating to version 2020.03.24 ...
```

But apparently it didn't work
