### ISSUE TITLE
No video formats found

### ISSUE THREAD

**Issue by gerijani** [ytdl-org/youtube-dl#24924]
- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[Git]$./youtube-dl --version
2020.03.24
[Git]$youtube-dl -F --cookies cookies.txt --verbose https://www.linkedin.com/learning/aws-devops-continuous-docker-deployment-to-aws-fargate-from-gitlab/installing-docker
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '--cookies', 'cookies.txt', '--verbose', 'https://www.linkedin.com/learning/aws-devops-continuous-docker-deployment-to-aws-fargate-from-gitlab/installing-docker']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.7.6 (CPython) - Linux-5.5.15-200.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[linkedin:learning] installing-docker: Downloading 360p JSON metadata
[linkedin:learning] installing-docker: Downloading 540p JSON metadata
[linkedin:learning] installing-docker: Downloading 720p JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/linkedin.py", line 127, in _real_extract
    self._sort_formats(formats, ('width', 'height', 'source_preference', 'tbr', 'abr'))
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

The Introduction chapter of https://www.linkedin.com/learning/aws-devops-continuous-docker-deployment-to-aws-fargate-from-gitlab was dowloaded alright but from first chapter I getting the "ERROR: No video formats found" message:

[download] Downloading video 3 of 23
[linkedin:learning] course-outline: Downloading 360p JSON metadata
[linkedin:learning] course-outline: Downloading 540p JSON metadata
[linkedin:learning] course-outline: Downloading 720p JSON metadata
[linkedin:learning] course-outline: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://files3.lynda.com/secure/courses/2814040/VBR_MP4h264_main_HD720/2814040_00_03_XR30_CourseOutline.mp4?9EGqx5kzBHAo5YZxJ6Md2SRL3kBZIrbRX9xxtDh1cjYwJmOIjzZ4MGjC3msdJtZTfT_VbESsKgofq9jHaWLu96DEFMsVFFgzv7y5y149Pl34IlcmFGw1ett1UfADW8PVj7scBqTFDhcKm7FmnDwCHUMh7og6XPjLErKb_mCUErQW_pHYt9I-J_LhKMX6UmDWDw'
[download] Sleeping 60 seconds...
[download] Destination: Course outline-2230903.mp4
[download] 100% of 2.15MiB in 00:04
[download] Downloading video 4 of 23
[linkedin:learning] gitlab-server-requirement: Downloading 360p JSON metadata
[linkedin:learning] gitlab-server-requirement: Downloading 540p JSON metadata
[linkedin:learning] gitlab-server-requirement: Downloading 720p JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/linkedin.py", line 127, in _real_extract
    self._sort_formats(formats, ('width', 'height', 'source_preference', 'tbr', 'abr'))
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by gerijani** [comment]
@remitamine: Of which issue is this a duplication? Can you refer to the ticket number?
