### ISSUE TITLE
unable to extract html5 player; Signature extraction failed

### ISSUE THREAD

**Issue by monolied** [ytdl-org/youtube-dl#24932]
hth, regards, m

Updating to version 2020.03.24 ...
Waiting for file handle to be closed ...
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'bestaudio', 'https://www.youtube.com/watch?v=m-6xWpcPmlk']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: avconv 11.3, avprobe 11.3
[debug] Proxy map: {}
[youtube] m-6xWpcPmlk: Downloading webpage
[youtube] m-6xWpcPmlk: Downloading video info webpage
Access is denied.
Updated youtube-dl to version 2020.03.24.
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {18} signature length 104, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\youtube.py", line 1385, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\youtube.py", line 1262, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by monolied** [comment]
I very much hope it's not a "403 issue", though. I mean, "403 Forbidden" is quite similar to "Access is denied", but I wouldn't know how to decide if this is the "403 issue" you're referring to. I want to add that this was also remedied by using the --rm-cache-dir switch between update and download. Could be a coincidence though. Hard to say. Your threats are frightening however. I don't really know if I should report an issue on this tool again.
