### ISSUE TITLE
Cannot merge video on OS X 10.4 -- ERROR:   Reason: image not found

### ISSUE THREAD

**Issue by ledlamp** [ytdl-org/youtube-dl#24935]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PowerMac-G4:~/Desktop Lamp$ youtube-dl https://www.youtube.com/watch?v=QH2-TGUlwu4 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=QH2-TGUlwu4', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.7.0 (CPython) - Darwin-8.11.0-Power_Macintosh-powerpc-32bit
[debug] exe versions: ffmpeg present, ffprobe present
[debug] Proxy map: {}
[youtube] QH2-TGUlwu4: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r4---sn-a5m7lnlz.googlevideo.com/videoplayback?expire=1587546457&ei=-bSfXqOCA9eJsfIP_JS-2A8&ip=2600%3A8801%3A3800%3A4cf0%3A230%3A65ff%3Afeed%3A1586&id=o-ABUhu0Htg0IcA9Yycy0-SpWoo5jD2xElFG7iEgvMc8WQ&itag=135&aitags=133%2C134%2C135%2C160%2C242%2C243%2C244%2C278%2C394%2C395%2C396%2C397&source=youtube&requiressl=yes&mh=po&mm=31%2C29&mn=sn-a5m7lnlz%2Csn-a5mekney&ms=au%2Crdu&mv=m&mvi=3&pl=33&initcwndbps=1801250&vprv=1&mime=video%2Fmp4&gir=yes&clen=4752708&dur=216.816&lmt=1575192442577468&mt=1587524736&fvip=4&keepalive=yes&fexp=23882513&c=WEB&txp=5532432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJpPlLswRQIgZxPGcpbDyNQzPlneSMciMepkWWLlaVh2ZM8_HMVFwgECIQCKqqDrwKuNiN6UD_emiFhdCWfMrD7Ocr6MKzLG13t9Jw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRAIgMvSmDx7cFoOhquSzMYt8ETK3XkY5xxXij2qalCsQm2sCIHOq_HufVUe3Ulg6uid8u20VjjnZG2NIgrRM22TYj_PS&ratebypass=yes'
[download] Destination: Nyan Cat [original]-QH2-TGUlwu4.f135.mp4
[download] 100% of 4.53MiB in 00:03
[debug] Invoking downloader on 'https://r4---sn-a5m7lnlz.googlevideo.com/videoplayback?expire=1587546457&ei=-bSfXqOCA9eJsfIP_JS-2A8&ip=2600%3A8801%3A3800%3A4cf0%3A230%3A65ff%3Afeed%3A1586&id=o-ABUhu0Htg0IcA9Yycy0-SpWoo5jD2xElFG7iEgvMc8WQ&itag=251&source=youtube&requiressl=yes&mh=po&mm=31%2C29&mn=sn-a5m7lnlz%2Csn-a5mekney&ms=au%2Crdu&mv=m&mvi=3&pl=33&initcwndbps=1801250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=3521927&dur=216.841&lmt=1575192425674655&mt=1587524736&fvip=4&keepalive=yes&fexp=23882513&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJpPlLswRAIgPGNMHWGZkQeCxXp8SDu6hNtV5aET5WQPKQp4jaK3hR8CIA5XoUdd3FkyPGFTylpsh_nvkmH_SVj-YMuzV_hpCJMJ&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRAIgMvSmDx7cFoOhquSzMYt8ETK3XkY5xxXij2qalCsQm2sCIHOq_HufVUe3Ulg6uid8u20VjjnZG2NIgrRM22TYj_PS&ratebypass=yes'
[download] Destination: Nyan Cat [original]-QH2-TGUlwu4.f251.webm
[download] 100% of 3.36MiB in 00:02
[ffmpeg] Merging formats into "Nyan Cat [original]-QH2-TGUlwu4.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Nyan Cat [original]-QH2-TGUlwu4.f135.mp4' -i 'file:Nyan Cat [original]-QH2-TGUlwu4.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Nyan Cat [original]-QH2-TGUlwu4.temp.mkv'
ERROR:   Reason: image not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2065, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Reason: image not found
```

## Description

Python3 and ffmpeg are installed with Tigerbrew. But with the default format of bestvideo+bestaudio, when it tries to merge with ffmpeg it encounters an error, `ERROR:   Reason: image not found`. This is not a big issue as I can specify `-f mp4` to download one file but I would like to download bestvideo+bestaudio.

Oops, github suggested some similar issues and I found #8323. How did I not find that when searching the very exact error message 😕 
I don't feel like deleting all this work so I will submit and close it.

**Comment by ledlamp** [comment]
Wait, but unlike that issue, it is NOT using avconv. Turns out there is something wrong with ffmpeg itself:
![](https://nyc8.qonq.gq)
Obvoiusly not a youtube-dl issue now so this stays closed.
