### ISSUE TITLE
[rtve] No video formats found for videos in collection 'arqueomania'

### ISSUE THREAD

**Issue by Martin-Laclaustra** [ytdl-org/youtube-dl#24957]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.rtve.es/alacarta/videos/arqueomania/arqueomania-primeras-civilizaciones/5562600/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-96-generic-x86_64-with-LinuxMint-18.2-sonya
[debug] exe versions: avconv 2.8.15, avprobe 2.8.15, ffmpeg 2.8.15, ffprobe 2.8.15, phantomjs 2.1.1
[debug] Proxy map: {}
[rtve.es:alacarta] Fetching manager info
[rtve.es:alacarta] 5562600: Downloading JSON metadata
[rtve.es:alacarta] 5562600: Downloading url information
[rtve.es:alacarta] 5562600: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 400: Bad Request
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/rtve.py", line 152, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Most videos in rtve.es work without any problem. However, videos in this collection page fail with the problem described in this issue.
https://www.rtve.es/alacarta/videos/arqueomania/

**Comment by felisucoibi** [comment]
this bug i think is because these videos are very old and use .swf flash video, is like the oldets format you can find in rtve website.

**Comment by felisucoibi** [comment]
this bug can be closed i think
