### ISSUE TITLE
6play - No video formats found

### ISSUE THREAD

**Issue by fearhack** [ytdl-org/youtube-dl#24967]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
.\youtube-dl.exe "https://www.6play.fr/tous-en-cuisine-avec-cyril-lignac-p_16703/emission-du-22-avril-c_12616125" --username xxxxx@xxxxx.com --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.6play.fr/tous-en-cuisine-avec-cyril-lignac-p_16703/emission-du-22-avril-c_12616125', '--username', 'PRIVATE', '--verbose']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[6play] 12616125: Downloading JSON metadata
[6play] 12616125: Downloading webpage
[6play] 12616125: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12616125: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[6play] 12616125: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12616125: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[6play] 12616125: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12616125: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\sixplay.py", line 113, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Nothing more to say. Please help :)

**Comment by rs** [comment]
+1

**Comment by gecastan** [comment]
+1

Also, a demo account was created specifically for youtube-dl in a previous issue

See :
https://github.com/ytdl-org/youtube-dl/issues/14719#issuecomment-343651381

**Comment by ilike2burnthing** [comment]
DRM - Widevine, PlayReady, and Marlin

Sorry all, it's not happening.

**Comment by gecastan** [comment]
Weird



`youtube-dl --version
2020.03.24

youtube-dl -v --extract-audio -u cafehaine@gmail.com -p demoaccount https://www.6play.fr/tous-en-cuisine-avec-cyril-lignac-p_16703/emission-du-23-avril-c_12616287
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--extract-audio', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.6play.fr/tous-en-cuisine-avec-cyril-lignac-p_16703/emission-du-23-avril-c_12616287']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.6.9 (CPython) - Linux-5.3.0-40-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[6play] 12616287: Downloading JSON metadata
[6play] 12616287: Downloading webpage
[6play] 12616287: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12616287: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[6play] 12616287: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12616287: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[6play] 12616287: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12616287: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/sixplay.py", line 113, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by fearhack** [comment]
> [Manifest.txt](https://github.com/ytdl-org/youtube-dl/files/4525919/Manifest.txt)
> 
> DRM - Widevine, PlayReady, and Marlin
> 
> Sorry all, it's not happening.

:( Ok

**Comment by gecastan** [comment]
Closed?
Didn't get the fix on that one.
How can you make that work?

**Comment by dirkf** [comment]
Some browsers may contain unverifiable proprietary code (EME) that is able to play the encrypted material, and might also do anything else that its creators fancy. If your browser allows you to disable this code and some video still plays, it's not DRM-protected and yt-dl should be able to fetch it. In that case, post details.
