### ISSUE TITLE
youtube error 403

### ISSUE THREAD

**Issue by museum-future** [ytdl-org/youtube-dl#24975]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
=>youtube-dl -v https://www.youtube.com/watch?v=MC2bNPOPKIU
[debug] System config: []
[debug] User config: ['--ignore-errors', '--no-warnings', '--no-call-home', '--geo-bypass', '--continue', '--no-part', '--console-title', '--restrict-filenames', '--encoding', 'UTF-8', '--prefer-ffmpeg', '--hls-prefer-native', '--retries', '100', '--yes-playlist', '--buffer-size', '4k', '--bidi-workaround', '--fragment-retries', '100', '--audio-format', 'best', '--audio-quality', '0', '--recode-video', 'mp4', '--format', '313+140/264+140/271+140/313+172/264+172/271+172/137+140/137+140/248+251/bestvideo[height>=1920,ext=mp4]+bestaudio[ext=m4a]/bestvideo[height>=720,ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio/best[ext!=webm]', '--merge-output-format', 'mp4', '--output=%(playlist_index)s_%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=MC2bNPOPKIU']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.7.7 (CPython) - Darwin-19.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-97190-gca76a5ba1a-tessus, ffprobe N-97190-gca76a5ba1a-tessus, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] MC2bNPOPKIU: Downloading webpage
[youtube] {18} signature length 100, html5 player vflset
[youtube] {137} signature length 104, html5 player vflset
[youtube] {248} signature length 104, html5 player vflset
[youtube] {136} signature length 104, html5 player vflset
[youtube] {247} signature length 100, html5 player vflset
[youtube] {135} signature length 100, html5 player vflset
[youtube] {244} signature length 104, html5 player vflset
[youtube] {134} signature length 104, html5 player vflset
[youtube] {243} signature length 100, html5 player vflset
[youtube] {133} signature length 104, html5 player vflset
[youtube] {242} signature length 104, html5 player vflset
[youtube] {160} signature length 104, html5 player vflset
[youtube] {278} signature length 104, html5 player vflset
[youtube] {140} signature length 104, html5 player vflset
[youtube] {249} signature length 104, html5 player vflset
[youtube] {250} signature length 104, html5 player vflset
[youtube] {251} signature length 104, html5 player vflset
[debug] Invoking downloader on 'https://r1---sn-ui0pn-5hne.googlevideo.com/videoplayback?expire=158774
8037&ei=ZciiXuzZKJHR1gKk8JOoCw&ip=31.21.212.115&id=o-AM97_apGclab_vhWx6ku84Msj1FWeJUEAR3xCvxkfzZl&itag
=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requi
ressl=yes&mh=Xk&mm=31%2C29&mn=sn-ui0pn-5hne%2Csn-5hne6nsk&ms=au%2Crdu&mv=m&mvi=0&pcm2cms=yes&pl=16&ini
tcwndbps=1681250&vprv=1&mime=video%2Fmp4&gir=yes&clen=91727868&dur=167.000&lmt=1577148842685796&mt=158
7726332&fvip=5&keepalive=yes&c=WEB&txp=1306222&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequi
ressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cin
itcwndbps&lsig=ALrAebAwRAIgfN4O1qzADR0pMXpR93teJfJE-OGfFcHCJkHhmGODWpYCIBpYlw2F7XwRephC9XrkI8WP53xFlRi
BB-kt1-rDU0VR&sig=UMn5c1cJOOTrjowzaLAfkThUr=Kk_HYKeMl9bbHGRE3-AEiA70lsnnWsxZyDXc-25lieAdZigqdmGXlF4iqT
HwI_pWJAhIgRwpLV&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/Users/glen/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/Users/glen/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/Users/glen/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/Users/glen/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/Users/glen/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/Users/glen/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", 
line 531, in open
    response = meth(req, response)
```

## Description

WRITE DESCRIPTION HERE

**Comment by linus-dev** [comment]
Having same issue

**Comment by cpyb** [comment]
same ...

**Comment by cpyb** [comment]
FIXED after cleaning the cash.
