### ISSUE TITLE
Cannot dl a youtube video

### ISSUE THREAD

**Issue by Lotus907efi** [ytdl-org/youtube-dl#24981]
## Checklist

- [X] I'm reporting a broken site support
- [X ] I've verified that I'm running youtube-dl version **2020.03.24**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-U', u'--verbose', u'--restrict-filenames', u'https://www.youtube.com/watch?v=07IDFmknr5g']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.6 (CPython) - Linux-3.19.8-992-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-95906-g2952d9c, ffprobe N-95906-g2952d9c
[debug] Proxy map: {}
youtube-dl is up-to-date (2020.03.24)
[youtube] 07IDFmknr5g: Downloading webpage
[youtube] {18} signature length 104, html5 player vflset
[youtube] {137} signature length 104, html5 player vflset
[youtube] {248} signature length 104, html5 player vflset
[youtube] {136} signature length 104, html5 player vflset
[youtube] {247} signature length 104, html5 player vflset
[youtube] {135} signature length 104, html5 player vflset
[youtube] {244} signature length 104, html5 player vflset
[youtube] {134} signature length 100, html5 player vflset
[youtube] {243} signature length 104, html5 player vflset
[youtube] {133} signature length 104, html5 player vflset
[youtube] {242} signature length 104, html5 player vflset
[youtube] {160} signature length 104, html5 player vflset
[youtube] {278} signature length 104, html5 player vflset
[youtube] {140} signature length 104, html5 player vflset
[youtube] {249} signature length 104, html5 player vflset
[youtube] {250} signature length 104, html5 player vflset
[youtube] {251} signature length 104, html5 player vflset
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r4---sn-vgqsknlz.googlevideo.com/videoplayback?expire=1587770744&ei=GCGjXqfgEo_gigTUvL-oBw&ip=76.189.36.251&id=o-ALMpl776cPKb5OjRVfSxhGVgmkUNb1YigojaJnsFM6cP&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=s5&mm=31%2C26&mn=sn-vgqsknlz%2Csn-ab5szn76&ms=au%2Conr&mv=m&mvi=3&pl=15&initcwndbps=1745000&vprv=1&mime=video%2Fmp4&gir=yes&clen=67988719&dur=251.999&lmt=1587748115329762&mt=1587749081&fvip=4&keepalive=yes&c=WEB&txp=6316222&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIhAMXk04B1AoBV9Of_LkR5AN2g8YNjsVBP_0k03JYUsmoZAiAMbkWqnhmCKbO19sUOBIv6kDGE0Yd-eaSL2-jfVRmjHA%3D%3D&sig=B=g5_NoPSDkRkqAbJjmXgNDcr=9LCE5qTxTJaIgXFg9UNBiALwFuRfVsLu2Qzv4_PlwpAVOeqbOt1MQLyDJLtwHLOGOAhIQRwpLt&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/sad/bin/youtube-dl-2017.11.15.py/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/home/sad/bin/youtube-dl-2017.11.15.py/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
    return fd.download(name, info)
  File "/home/sad/bin/youtube-dl-2017.11.15.py/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/home/sad/bin/youtube-dl-2017.11.15.py/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/home/sad/bin/youtube-dl-2017.11.15.py/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/sad/bin/youtube-dl-2017.11.15.py/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

## Description

Ran youtube-dl as 

~/bin/youtube-dl -U --restrict-filenames https://www.youtube.com/watch?v=07IDFmknr5g

on a Linux system (debian 14.04 with many updates)

WRITE DESCRIPTION HERE

**Comment by Lotus907efi** [comment]
Nevermind. I ran youtube-dl with --rm-cache-dir and now it works.

**Comment by Lotus907efi** [comment]
Nevermind. I ran youtube-dl with --rm-cache-dir and now it works.
