### ISSUE TITLE
 [ADN] no way to extract subtitles

### ISSUE THREAD

**Issue by gamersalpha** [ytdl-org/youtube-dl#25007]
## Checklist
Youtubedll version :

```
E:\>youtube-dl.exe --version
2020.03.24
```
- [X ] I'm reporting a broken site support issue
- [ X] I've verified that I'm running youtube-dl version **2020.03.24**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ ]X I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar bug reports including closed ones
- [ X] I've read bugs section in FAQ

## Verbose log

```
E:\>youtube-dl.exe -v https://animedigitalnetwork.fr/video/boruto-naruto-next-generations/7937-episode-2-le-fils-du-hokage  --list-subs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://animedigitalnetwork.fr/video/boruto-naruto-next-generations/7937-episode-2-le-fils-du-hokage', '--list-subs']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[ADN] 7937: Downloading webpage
[ADN] 7937: Downloading player config JSON metadata
[ADN] 7937: Downloading links JSON metadata
[ADN] 7937: Downloading vostf mobile JSON metadata
[ADN] 7937: Downloading m3u8 information
[ADN] 7937: Downloading vostf sd JSON metadata
[ADN] 7937: Downloading m3u8 information
[ADN] 7937: Downloading subtitles location
[ADN] 7937: Downloading subtitles data
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\adn.py", line 204, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 2892, in extract_subtitles
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\adn.py", line 80, in _get_subtitles
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 1: invalid start byte
```

## Description

Hello, 
i can't downlaod subtitle
i got this error : 
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 1: invalid start byte
do u know how fix this please

**Comment by gamersalpha** [comment]
@dstftw where is the original please ?

**Comment by ilike2burnthing** [comment]
https://github.com/ytdl-org/youtube-dl/issues?q=adn+subtitles
