### ISSUE TITLE
hentai.animestigma.com

### ISSUE THREAD

**Issue by off-cmd** [ytdl-org/youtube-dl#25019]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
py.exe "C:\Program Files\Python38\Lib\site-packages\youtube_dl" -v "http://hentai.animestigma.com/inyouchuu-etsu-bonus/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://hentai.animestigma.com/inyouchuu-etsu-bonus/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.2 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg git-2020-04-24-a501947, ffprobe git-2020-04-24-a501947
[debug] Proxy map: {}
[HentaiStigma] inyouchuu-etsu-bonus: Downloading webpage
[HentaiStigma] inyouchuu-etsu-bonus: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\extractor\hentaistigma.py", line 31, in _real_extract
    video_url = self._html_search_regex(
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\extractor\common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Site migrated to new video player selection and [old extractor](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/hentaistigma.py) does not support. The old and new players are now flowplayer and video-js based respectively. The new player (player 2) embeds a direct link (ex:<source src="https://v2.animestigma.com/videos/hd1/Inyouchuu_Etsu_-_Bonusssub.mp4" type="video/mp4">)
Tested on extractor example link as well as a random selection from the site's [search function](https://hentai.animestigma.com/?s=&x=8&y=10).

**Comment by ifixthat-gmx** [comment]
@off-cmd
please check my modification in my fork [here](https://github.com/ifixthat-gmx/ytdl-org---youtube-dl/blob/tmp-hentaistigma/youtube_dl/extractor/hentaistigma.py) .

**Comment by dirkf** [comment]
The link in the iframe in the test video page is a standard HTML5 video page that can be handled by the Generic extractor. The extractor will need to be updated to call the same HTML5 extraction routine (`IE._parse_html5_media_entries()`).
```console
$ python -m youtube_dl -vF 'https://hentai.animestigma.com/p/player.php?fn=Inyouchuu_Etsu_-_Bonusssub.mp4' --force-generic
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vF', u'https://hentai.animestigma.com/p/player.php?fn=Inyouchuu_Etsu_-_Bonusssub.mp4', u'--force-generic']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: a4d4bbdb0
[debug] Python 2.7.15 (CPython i686 32bit) - Linux-6.1.0-25-686-pae-i686-with-debian-12.7 - OpenSSL 1.1.1a  20 Nov 2018 - glibc 2.1.3
[debug] exe versions: ffmpeg 5.1.6-0, ffprobe 5.1.6-0
[debug] Proxy map: {}
[generic] player.php?fn=Inyouchuu_Etsu_-_Bonusssub: Requesting header
WARNING: Forcing on generic information extractor.
[generic] player.php?fn=Inyouchuu_Etsu_-_Bonusssub: Downloading webpage
[generic] player.php?fn=Inyouchuu_Etsu_-_Bonusssub: Extracting information
[download] Downloading playlist: Hentai
[generic] playlist Hentai: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[info] Available formats for player.php?fn=Inyouchuu_Etsu_-_Bonusssub:
format code  extension  resolution note
0            mp4        unknown    
[download] Finished downloading playlist: Hentai
$
```
