### ISSUE TITLE
Youtube: HTTP 403 when trying to download video data

### ISSUE THREAD

**Issue by BitBargain** [ytdl-org/youtube-dl#25016]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=hqVJpfFkJ9k']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Linux-5.0.0-38-generic-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube] hqVJpfFkJ9k: Downloading webpage
[youtube] {18} signature length 104, html5 player vflset
[youtube] {134} signature length 104, html5 player vflset
[youtube] {243} signature length 104, html5 player vflset
[youtube] {133} signature length 100, html5 player vflset
[youtube] {242} signature length 104, html5 player vflset
[youtube] {160} signature length 104, html5 player vflset
[youtube] {278} signature length 104, html5 player vflset
[youtube] {140} signature length 104, html5 player vflset
[youtube] {249} signature length 104, html5 player vflset
[youtube] {250} signature length 100, html5 player vflset
[youtube] {251} signature length 104, html5 player vflset
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r1---sn-2guxaxjvh-c0ql.googlevideo.com/videoplayback?expire=1587944655&ei=b8ilXqWeDIeL7gOU6aaYDw&ip=88.132.145.65&id=o-AI1vFGx6JXqk2t2YJ9LCGteduebMlnXZC9FRBFDf2l5k&itag=134&aitags=133%2C134%2C160%2C242%2C243%2C278&source=youtube&requiressl=yes&mh=vF&mm=31%2C29&mn=sn-2guxaxjvh-c0ql%2Csn-c0q7lnsl&ms=au%2Crdu&mv=m&mvi=0&pl=19&initcwndbps=1068750&vprv=1&mime=video%2Fmp4&gir=yes&clen=23307681&dur=5003.500&lmt=1537712795710863&mt=1587922950&fvip=1&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIgSvy-Gw3aBMjq-txZ7dKSh7iHSzLWiFb-m7_Uq0D1JdICIQDHnTBjGhPOgBTrwJ39lekkPlfv8DmOqKfijZozgx2ZvQ%3D%3D&sig=1=ANdkVS8DxlFa9n_PeFqMufG=Vi8SgdDiEUuiARjUNg7AiAKj8ByTVsl3tcxdYQwlQXAR88I2wSfIt1rrK-_7fAbcNAhIQRwpL7&ratebypass=yes'
[download] Hard Neurofunk Drum & Bass Mix (N422)-hqVJpfFkJ9k.f134.mp4 has already been downloaded
[download] 100% of 22.23MiB
[debug] Invoking downloader on u'https://r1---sn-2guxaxjvh-c0ql.googlevideo.com/videoplayback?expire=1587944655&ei=b8ilXqWeDIeL7gOU6aaYDw&ip=88.132.145.65&id=o-AI1vFGx6JXqk2t2YJ9LCGteduebMlnXZC9FRBFDf2l5k&itag=251&source=youtube&requiressl=yes&mh=vF&mm=31%2C29&mn=sn-2guxaxjvh-c0ql%2Csn-c0q7lnsl&ms=au%2Crdu&mv=m&mvi=0&pl=19&initcwndbps=1068750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=80440364&dur=5003.581&lmt=1537715171720995&mt=1587922950&fvip=1&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIgSvy-Gw3aBMjq-txZ7dKSh7iHSzLWiFb-m7_Uq0D1JdICIQDHnTBjGhPOgBTrwJ39lekkPlfv8DmOqKfijZozgx2ZvQ%3D%3D&sig=UgXfKZS8mmnk6QP8gMedvIr9U=YmCpm_3NKzAiElzBV8AEiApl5JPUfsE6JznHjEWlDHADLTVblrxOEMSxZsWD7g7KOAhIgRwpL_&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

```

## Description

Recently I've started running into more and more videos that can't be downloaded due to an "error 403" I assume returned by Youtube.

Thanks for looking into this. Great project, have donated, will do in the future as well.

**Comment by BitBargain** [comment]
EDIT: missed the giant sticky. Note to self and everyone for when a video doesn't download:
- check for updates
- delete the cache: youtube-dl --rm-cache-dir

Sorry to trouble you. Thanks for the help.
