### ISSUE TITLE
UnboundLocalError in xtube.py

### ISSUE THREAD

**Issue by jeff-kelley** [ytdl-org/youtube-dl#25013]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

$ youtube-dl -v https://www.xtube.com/video-watch/catsuit-latex-babe-laurens-outdoor-fetish-wear-posing-43326501
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.xtube.com/video-watch/catsuit-latex-babe-laurens-outdoor-fetish-wear-posing-43326501']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-169-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg N-78590-g5590ab4, ffprobe N-78590-g5590ab4, rtmpdump 2.4
[debug] Proxy map: {}
[XTube] catsuit-latex-babe-laurens-outdoor-fetish-wear-posing: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2019, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/xtube.py", line 103, in _real_extract
UnboundLocalError: local variable 'sources' referenced before assignment

## Description

Same error using Python3
$ python3 /usr/local/bin/youtube-d [url]

**Comment by dstftw** [comment]
```
> py -3.7 -m youtube_dl https://www.xtube.com/video-watch/catsuit-latex-babe-laurens-outdoor-fetish-wear-posing-43326501
[XTube] catsuit-latex-babe-laurens-outdoor-fetish-wear-posing: Downloading webpage
[download] Destination: Catsuit latex-babe Laurens outdoor fetish-wear posing-43326501.mp4
[download]   1.6% of 63.09MiB at  2.24MiB/s ETA 00:27
ERROR: Interrupted by user
```
