### ISSUE TITLE
tele5 real_extract fails

### ISSUE THREAD

**Issue by fionnb** [ytdl-org/youtube-dl#25035]
data-id apparently does contain not only decimals.

example:

data-id="56B5qbkl"

result:

```
youtube-dl -v "https://www.tele5.de/filme/bang-boom-bang-ein-todsicheres-ding-alles-auf-horst-fassung/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.tele5.de/filme/bang-boom-bang-ein-todsicheres-ding-alles-auf-horst-fassung/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, rtmpdump 2.4
[debug] Proxy map: {}
[Tele5] bang-boom-bang-ein-todsicheres-ding-alles-auf-horst-fassung: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tele5.py", line 53, in _real_extract
    r'\bdata-id\s*=\s*["\'](\d{6,})'), webpage, 'video id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```

**Comment by fionnb** [comment]
I am sorry, this issue seems to be handled in #24874 already. Closing.
