### ISSUE TITLE
YouTube: unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by xiaose** [ytdl-org/youtube-dl#25045]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe Zk11vI-7czE -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['Zk11vI-7czE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[youtube] Zk11vI-7czE: Downloading webpage
[youtube] {18} signature length 104, html5 player vflset
[youtube] {22} signature length 100, html5 player vflset
[youtube] {137} signature length 104, html5 player vflset
[youtube] {248} signature length 104, html5 player vflset
[youtube] {136} signature length 104, html5 player vflset
[youtube] {247} signature length 104, html5 player vflset
[youtube] {135} signature length 104, html5 player vflset
[youtube] {244} signature length 104, html5 player vflset
[youtube] {134} signature length 104, html5 player vflset
[youtube] {243} signature length 104, html5 player vflset
[youtube] {133} signature length 104, html5 player vflset
[youtube] {242} signature length 104, html5 player vflset
[youtube] {160} signature length 104, html5 player vflset
[youtube] {278} signature length 104, html5 player vflset
[youtube] {140} signature length 104, html5 player vflset
[youtube] {249} signature length 104, html5 player vflset
[youtube] {250} signature length 104, html5 player vflset
[youtube] {251} signature length 104, html5 player vflset
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r18---sn-3c27sn7y.googlevideo.com/videoplayback?expire=1588103411&ei=kzSoXpSBIpa77QSpva-QBQ&ip=109.95.32.79&id=o-ADmBIXDHqakdkkm3vmR0qOOGDPpf7xLEYVu60oAnDZSy&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=m3&mm=31%2C26&mn=sn-3c27sn7y%2Csn-f5f7ln7y&ms=au%2Conr&mv=m&mvi=17&nh=IgpwcjAyLmticDAyKgkxMjcuMC4wLjE%2C&pl=21&initcwndbps=1005000&vprv=1&mime=video%2Fwebm&gir=yes&clen=1335266859&dur=6001.541&lmt=1587551959548280&mt=1588081721&fvip=4&keepalive=yes&fexp=23882514&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cnh%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRAIgcrWoH47bTE6vuTpd8yqhyfnzzBP_r_0uoJVfgSJ0Yv0CIAFnvQ6MipQZdZGTxwQiu4DeMoQad8GaWNg4qMnxbTTE&sig===AyT1NXyQyQJCH9wfLB7rjrGNB_X4cIZpZIW2jS32SuACQICQSLTidsqVikIuFOXlOHxAmXu5owHwRh_ikLLq_N3IXdgKQnwpLk&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1920, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\http.py", line 109, in establish_conn
ection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

second one: 

youtube-dl.exe -v Frws0SAEy9A
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'Frws0SAEy9A']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[youtube] Frws0SAEy9A: Downloading webpage
[youtube] {18} signature length 104, html5 player vflset
[youtube] {135} signature length 104, html5 player vflset
[youtube] {244} signature length 104, html5 player vflset
[youtube] {134} signature length 104, html5 player vflset
[youtube] {243} signature length 100, html5 player vflset
[youtube] {133} signature length 104, html5 player vflset
[youtube] {242} signature length 104, html5 player vflset
[youtube] {160} signature length 104, html5 player vflset
[youtube] {278} signature length 104, html5 player vflset
[youtube] {140} signature length 104, html5 player vflset
[youtube] {249} signature length 104, html5 player vflset
[youtube] {250} signature length 104, html5 player vflset
[youtube] {251} signature length 104, html5 player vflset
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r5---sn-3c27sne7.googlevideo.com/videoplayback?expire=1588103572&ei=NDWoXo7TLOqEv_IP29yC2AQ&ip=109.95.32.79&id=o-AKvGjJORU2Z3AVEbdN7mgzkQGSAyPUNrEJ0R2DPyp-2d&itag=135&aitags=133%2C134%2C135%2C160%2C242%2C243%2C244%2C278&source=youtube&requiressl=yes&mh=mx&mm=31%2C26&mn=sn-3c27sne7%2Csn-c0q7lns7&ms=au%2Conr&mv=m&mvi=4&nh=IgpwcjAyLmticDAzKgkxMjcuMC4wLjE%2C&pl=21&initcwndbps=1065000&vprv=1&mime=video%2Fmp4&gir=yes&clen=1464164&dur=246.412&lmt=1573794671868009&mt=1588081897&fvip=5&keepalive=yes&c=WEB&txp=1306222&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cnh%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIhAPYhpXJ9kZmwlRktdK14O-sCPCN6lbu00WT0uSEXagfZAiBnvPsMW4TXAoDlnbS0bjCaeIZFgOVoLLAh4-WxPHSNCg%3D%3D&sig===Q6u3nTNyn_Lu5nYwokf9TSObUgWf0anlHAkHuqFAkByDQICEbOeb0syB7jI7P2GlH9bAw0W3K34ArsN0b99YEwvWxHglQewpLs&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1920, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\http.py", line 109, in establish_conn
ection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

third one: 

youtube-dl.exe -v UpStDgySVQI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'UpStDgySVQI']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[youtube] UpStDgySVQI: Downloading webpage
[youtube] {18} signature length 104, html5 player vflset
[youtube] {137} signature length 104, html5 player vflset
[youtube] {248} signature length 104, html5 player vflset
[youtube] {136} signature length 104, html5 player vflset
[youtube] {247} signature length 104, html5 player vflset
[youtube] {135} signature length 104, html5 player vflset
[youtube] {244} signature length 104, html5 player vflset
[youtube] {134} signature length 104, html5 player vflset
[youtube] {243} signature length 104, html5 player vflset
[youtube] {133} signature length 104, html5 player vflset
[youtube] {242} signature length 104, html5 player vflset
[youtube] {160} signature length 104, html5 player vflset
[youtube] {278} signature length 104, html5 player vflset
[youtube] {140} signature length 100, html5 player vflset
[youtube] {249} signature length 104, html5 player vflset
[youtube] {250} signature length 100, html5 player vflset
[youtube] {251} signature length 104, html5 player vflset
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r4---sn-3c27sn7r.googlevideo.com/videoplayback?expire=1588103628&ei=bDWoXr7QB_SEv_IP1qKiuA0&ip=109.95.32.79&id=o-AFnTCQn4SRgJCPaoghtUhiRt-33wa7lrMAZpGNFsL7aa&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=PJ&mm=31%2C26&mn=sn-3c27sn7r%2Csn-c0q7lnse&ms=au%2Conr&mv=m&mvi=3&nh=IgpwcjAyLmticDAzKgkxMjcuMC4wLjE%2C&pl=21&initcwndbps=1132500&vprv=1&mime=video%2Fmp4&gir=yes&clen=80507991&dur=229.028&lmt=1587329686437242&mt=1588081955&fvip=4&keepalive=yes&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cnh%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIgXMQMeG9JAbe4hXZHk6cMqemyna0s5wR9tqcDwC9GFYACIQDclBWWGOhP9tFzcdPJIsBfhU3iHjnVAKnGGs2WRl0JQQ%3D%3D&sig==cDTs1hNf_eUODY9rw3bth0hFsMhjwZV1fe1mDGms818AEiAPn4tESisXmR6IUw-vl9eGAx-U6K6K-58-MOQ2udwe7MAhEgbwpLn&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1920, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\http.py", line 109, in establish_conn
ection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

last one:

youtube-dl.exe -v -f 18 KebDuZJtBK4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '18', 'KebDuZJtBK4']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[youtube] KebDuZJtBK4: Downloading webpage
[youtube] {18} signature length 104, html5 player vflset
[youtube] {135} signature length 100, html5 player vflset
[youtube] {244} signature length 104, html5 player vflset
[youtube] {134} signature length 104, html5 player vflset
[youtube] {243} signature length 100, html5 player vflset
[youtube] {133} signature length 100, html5 player vflset
[youtube] {242} signature length 104, html5 player vflset
[youtube] {160} signature length 100, html5 player vflset
[youtube] {278} signature length 104, html5 player vflset
[youtube] {140} signature length 104, html5 player vflset
[youtube] {249} signature length 104, html5 player vflset
[youtube] {250} signature length 104, html5 player vflset
[youtube] {251} signature length 104, html5 player vflset
[youtube] KebDuZJtBK4: Downloading MPD manifest
[debug] Invoking downloader on 'https://r3---sn-3c27sn7d.googlevideo.com/videoplayback?expire=1588103692&ei=rDWoXpi5GoOh7ATIsKjgCA&ip=109.95.32.79&i
d=o-ACspjyZJLWd4nFcfzEk5awWPdHqxoJApTNK_Z8nQ2fmL&itag=18&source=youtube&requiressl=yes&mh=7C&mm=31%2C26&mn=sn-3c27sn7d%2Csn-f5f7lne7&ms=au%2Conr&mv=
m&mvi=2&nh=IgpwcjAyLmticDAyKgkxMjcuMC4wLjE%2C&pl=21&initcwndbps=973750&vprv=1&mime=video%2Fmp4&gir=yes&clen=814049171&ratebypass=yes&dur=8963.297&lm
t=1493495404655201&mt=1588081955&fvip=3&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cd
ur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cnh%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRAIgGd_bbeCRNJV1qeAwJVO59k0lW_Tf_FlXOW2mIjzEcbYCIA0q7XeWJ6c6XdEO
3bsyl9MsnE8yMxlD-E3ejTSYom37&sig==oigJK1CbBRh2-TmDP2bFNDPUS3OWvT_6cDvCUzI49slAEiAzPTA0uosrk7cISwrtlJ7GAy-Rbh4sE2_Sngns2JN6GJAhsgOwpLf'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1926, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\http.py", line 109, in establish_conn
ection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

## Description

I tied to download some files and all time get 403 error.
Here are some examples:
https://www.youtube.com/watch?v=KebDuZJtBK4
https://www.youtube.com/watch?v=Frws0SAEy9A
https://www.youtube.com/watch?v=Zk11vI-7czE
https://www.youtube.com/watch?v=UpStDgySVQI

It happened not with all files, for example, with https://www.youtube.com/watch?v=0Oazb7IWzbA everything is fine, but some of that links (which I can open in YouTube without any problems) cannot be downloaded by youtube-dl.

I found it 2-3 day before.

**Comment by tcaddy** [comment]
See this document: https://github.com/ytdl-org/youtube-dl/issues/23638

Try adding the `--rm-cache-dir` option as suggested in the document.

**Comment by xiaose** [comment]
Really thank you. How I do not found that topic??? And thank you again
