### ISSUE TITLE
Crunchyroll download not working anymore

### ISSUE THREAD

**Issue by federicorosso1993** [ytdl-org/youtube-dl#25064]
#10645  Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl https://www.crunchyroll.com/tower-of-god/episode-4-the-green-april-794522 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.crunchyroll.com/tower-of-god/episode-4-the-green-april-794522', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, rtmpdump 2.3
[debug] Proxy map: {}
[crunchyroll] 794522: Downloading webpage
ERROR: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\crunchyroll.py", line 446, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 1014, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Cannot download any video from crunchyroll. Also log in is not working anymore (I tried that too, it fail to log in with the right credentials).

**Comment by MarkIvanowich** [comment]
They changed their video page layout ever so slightly. Page no longer has a `<h1>...<span itemprop="title">` tag where we pulled the video_title from:

https://github.com/ytdl-org/youtube-dl/blob/d415957dbc0eed1123fd5139a30a9a05808f0f13/youtube_dl/extractor/crunchyroll.py#L444-L446

Perhaps grabbing video_title from the facebook meta tag instead? I don't notice any ellipsis shortening the title just a "Watch " prefix.
```
<meta name="og:description" content="Watch My Teen Romantic Comedy SNAFU TOO! Episode 10 - The Thing That the Light in Each of Their Hands Shines On.">
```

**Comment by MarkIvanowich** [comment]
Duplicate Issue https://github.com/ytdl-org/youtube-dl/issues/25047 will be closed by PR# https://github.com/ytdl-org/youtube-dl/pull/25060
