### ISSUE TITLE
[nick.de] Migrated to cc.com infrastructure from Viacom

### ISSUE THREAD

**Issue by SebiderSushi** [ytdl-org/youtube-dl#25065]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.nick.de/episodes/1xja87/die-legende-von-korra-nach-all-den-jahren-staffel-2-ep-29', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.2 (CPython) - Linux-5.4.35-1-MANJARO-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[nick.de] die-legende-von-korra-nach-all-den-jahren-staffel-2-ep-29: Downloading webpage
ERROR: Unable to extract mrss url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/nick.py", line 191, in _real_extract
    mrss_url = self._extract_mrss_url(webpage, host)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/nick.py", line 180, in _extract_mrss_url
    return update_url_query(self._search_regex(
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract mrss url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```


## Description

<!--
Provide an explanation of your issue in an arbitrary form. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

As it appears, nick.de was recently migrated to use the same infrastructure as cc.com, as they both belong to Viacom.

As a result, youtube-dl no longer works with any video on nick.de
I guess switching to the cc.com extractor would be enough in this case?
Might as well be a good call to check any othe nickelodeon or viacom backed website for continued youtube-dl support.

Some example links even though the whole site is affected:
```
https://www.nick.de/episodes/5gv9n1/die-legende-von-korra-das-gift-des-roten-lotus-staffel-2-ep-28
https://www.nick.de/episodes/aq2nkz/spongebob-schwammkopf-entsorgungs-irrsinn-seehasenjagd-staffel-2-ep-8
https://www.nick.de/episodes/yel6cu/big-time-rush-willkommen-zurueck-big-time-rush-staffel-2-ep-1
https://www.nick.de/episodes/yg7wwp/avatar-der-herr-der-elemente-zosins-komet-teil-3-von-angesicht-zu-angesicht-staffel-3-ep-21
https://www.nick.de/episodes/97ppz2/drake-josh-maedchen-und-andere-sorgen-staffel-3-ep-1
```

**Comment by SeppSpenderRind** [comment]
Since even more Nickelodeon shows were added to nick.de recently, support for this site would be really helpful! Thanks!

**Comment by hazcod** [comment]
Same for nickelodeon.nl or nickelodeon.be:

```
% youtube-dl --version
2020.12.09

% youtube-dl -f best -v 'https://www.nickelodeon.nl/episodes/vk6yzc/spongebob-gaan-op-die-maan-seizoen-seasonnumber-11-afl-22'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '-v', 'https://www.nickelodeon.nl/episodes/vk6yzc/spongebob-gaan-op-die-maan-seizoen-seasonnumber-11-afl-22']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.09
[debug] Python version 3.9.0 (CPython) - macOS-10.16-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[nick.de] spongebob-gaan-op-die-maan-seizoen-seasonnumber-11-afl-22: Downloading webpage
ERROR: Unable to extract mrss url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2020.12.9/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2020.12.9/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2020.12.9/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2020.12.9/libexec/lib/python3.9/site-packages/youtube_dl/extractor/nick.py", line 191, in _real_extract
    mrss_url = self._extract_mrss_url(webpage, host)
  File "/usr/local/Cellar/youtube-dl/2020.12.9/libexec/lib/python3.9/site-packages/youtube_dl/extractor/nick.py", line 180, in _extract_mrss_url
    return update_url_query(self._search_regex(
  File "/usr/local/Cellar/youtube-dl/2020.12.9/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract mrss url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by SebiderSushi** [comment]
I have been using `youtube-dlc` for the past months now and their patch (mentioned in issue discussion at https://github.com/blackjack4494/youtube-dlc/issues/44) works perfectly. Can it be merged into upsream `youtube-dl` or what are the issues?
