### ISSUE TITLE
Unable to extract video_title on Crunchyroll

### ISSUE THREAD

**Issue by TrentexTech** [ytdl-org/youtube-dl#25061]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
H:\yt-dl\Series>H:\yt-dl\youtube-dl https://www.crunchyroll.com/one-piece --playlist-start 1142 --playlist-end 1142 --verbose
[debug] System config: []
[debug] User config: ['--retries', 'infinite', '--fragment-retries', 'infinite', '--output', 'D:/Download/yt-dl/%(series)s-%(season_number)s/%(series)s-%(episode_number)s.%(ext)s', '--write-thumbnail', '--embed-thumbnail', '--all-subs', '--embed-subs']
[debug] Custom config: []
[debug] Command-line args: ['https://www.crunchyroll.com/one-piece', '--playlist-start', '1142', '--playlist-end', '1142', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-94150-g231d0c819f, ffprobe N-94150-g231d0c819f, phantomjs 2.1.1
[debug] Proxy map: {}
[crunchyroll:playlist] one-piece: Downloading webpage
[download] Downloading playlist: One Piece
[crunchyroll:playlist] playlist One Piece: Collected 1142 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[crunchyroll] 794472: Downloading webpage
ERROR: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\crunchyroll.py", line 446, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 1014, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

This exact setup worked two weeks ago, now it doesn't.
I even tried a different episode but it still doesn't work.

**Comment by jasoninfosec** [comment]
Hey @TrentexTech, I'm having the same issue with crunchyroll support. 
2020-04-29 14:08:11,773 - ERROR - ERROR: Unable to extract video_title;
