### ISSUE TITLE
Unlisted Youtube Video Results in "FFmpegPostProcessorError: Conversion failed!"

### ISSUE THREAD

**Issue by feerlessleadr** [ytdl-org/youtube-dl#25074]
## Checklist

- [X ] I'm reporting a broken site support issue
- [ X] I've verified that I'm running youtube-dl version **2020.03.24**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar bug reports including closed ones
- [ X] I've read bugs section in FAQ

## Verbose log

```
kevin@linuxserver:~/youtube-dl/scripts$ ./ytdl-kidsyoutube-singlevideo-verbose https://youtu.be/VZu7iFWrzs8
[debug] System config: []
[debug] User config: []
[debug] Custom config: [u'--format', u'(bestvideo[vcodec=vp9][height>=1080][fps>30]/bestvideo[vcodec=vp9][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec=vp9][height>=720][fps>30]/bestvideo[vcodec=vp9][height>=720]/bestvideo[height>=720]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best', u'--merge-output-format', u'mkv', u'--write-info-json', u'--write-all-thumbnails', u'--add-metadata', u'--embed-subs', u'--ignore-errors', u'--proxy', u'', u'--download-archive', u'/home/kevin/scripts/youtube/downloaded.txt']
[debug] Command-line args: [u'--config-location', u'/home/kevin/youtube-dl/config2.txt', u'-v', u'-o', u'/home/kevin/youtube-dl/kidstmp/%(title)s.%(ext)s', u'https://youtu.be/VZu7iFWrzs8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-51-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.2.1-2, ffprobe 4.2.1-2
[debug] Proxy map: {}
[youtube] VZu7iFWrzs8: Downloading webpage
[youtube] VZu7iFWrzs8: Downloading MPD manifest
[info] Writing video description metadata as JSON to: /home/kevin/youtube-dl/kidstmp/Hickory Dickory Dock + More Kids Songs & Music Classes _ The Jam Cats Music.info.json
[youtube] VZu7iFWrzs8: Downloading thumbnail ...
[youtube] VZu7iFWrzs8: Writing thumbnail to: /home/kevin/youtube-dl/kidstmp/Hickory Dickory Dock + More Kids Songs & Music Classes _ The Jam Cats Music.jpg
[debug] Invoking downloader on u'https://manifest.googlevideo.com/api/manifest/dash/expire/1588275172/ei/hNOqXp2eHIH3hwbI6YmgDg/ip/71.187.72.15/id/559bbb8855abcecf/source/youtube/requiressl/yes/playback_host/r3---sn-8xgp1vo-ab5s.googlevideo.com/mh/4O/mm/31%2C29/mn/sn-8xgp1vo-ab5s%2Csn-ab5szn7z/ms/au%2Crdu/mv/m/mvi/2/pl/16/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1190000/vprv/1/mt/1588253494/fvip/3/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AJpPlLswRgIhANdJMl_r6pAtXfGTl-jTmDXeFBiv-axEivq1-nmpXLTNAiEA2PUQ6iRaJM2UBv7lapGrvrh_veTkQbcxWq0fj5ww20s%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/ALrAebAwRAIgSq0Yat4Yl9fidwprUPVto-akBuGAo1NozRAiD2Z-KskCIFQLty-asb1eQOkBgaQuRiLly9Nd0OLErvEUuX9zGbUf'
[dashsegments] Total fragments: 305
[download] Destination: /home/kevin/youtube-dl/kidstmp/Hickory Dickory Dock + More Kids Songs & Music Classes _ The Jam Cats Music.f303.webm
[download] 100% of 541.05MiB in 02:15
[debug] Invoking downloader on u'https://manifest.googlevideo.com/api/manifest/dash/expire/1588275172/ei/hNOqXp2eHIH3hwbI6YmgDg/ip/71.187.72.15/id/559bbb8855abcecf/source/youtube/requiressl/yes/playback_host/r3---sn-8xgp1vo-ab5s.googlevideo.com/mh/4O/mm/31%2C29/mn/sn-8xgp1vo-ab5s%2Csn-ab5szn7z/ms/au%2Crdu/mv/m/mvi/2/pl/16/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1190000/vprv/1/mt/1588253494/fvip/3/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AJpPlLswRgIhANdJMl_r6pAtXfGTl-jTmDXeFBiv-axEivq1-nmpXLTNAiEA2PUQ6iRaJM2UBv7lapGrvrh_veTkQbcxWq0fj5ww20s%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/ALrAebAwRAIgSq0Yat4Yl9fidwprUPVto-akBuGAo1NozRAiD2Z-KskCIFQLty-asb1eQOkBgaQuRiLly9Nd0OLErvEUuX9zGbUf'
[dashsegments] Total fragments: 164
[download] Destination: /home/kevin/youtube-dl/kidstmp/Hickory Dickory Dock + More Kids Songs & Music Classes _ The Jam Cats Music.f251.webm
[download] 100% of 20.12MiB in 00:27
[ffmpeg] Merging formats into "/home/kevin/youtube-dl/kidstmp/Hickory Dickory Dock + More Kids Songs & Music Classes _ The Jam Cats Music.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:/home/kevin/youtube-dl/kidstmp/Hickory Dickory Dock + More Kids Songs & Music Classes _ The Jam Cats Music.f303.webm' -i 'file:/home/kevin/youtube-dl/kidstmp/Hickory Dickory Dock + More Kids Songs & Music Classes _ The Jam Cats Music.f251.webm' -c copy -map '0:v:0' -map '1:a:0' 'file:/home/kevin/youtube-dl/kidstmp/Hickory Dickory Dock + More Kids Songs & Music Classes _ The Jam Cats Music.temp.mkv'
ERROR: Conversion failed!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2065, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: Conversion failed!

[ffmpeg] Adding metadata to '/home/kevin/youtube-dl/kidstmp/Hickory Dickory Dock + More Kids Songs & Music Classes _ The Jam Cats Music.mkv'
ERROR: [Errno 2] No such file or directory: '/home/kevin/youtube-dl/kidstmp/Hickory Dickory Dock + More Kids Songs & Music Classes _ The Jam Cats Music.mkv'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2000, in process_info
    self.post_process(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2065, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 498, in run
    self.run_ffmpeg_multiple_files(in_filenames, temp_filename, options)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 210, in run_ffmpeg_multiple_files
    os.stat(encodeFilename(path)).st_mtime for path in input_paths)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 210, in <genexpr>
    os.stat(encodeFilename(path)).st_mtime for path in input_paths)
OSError: [Errno 2] No such file or directory: '/home/kevin/youtube-dl/kidstmp/Hickory Dickory Dock + More Kids Songs & Music Classes _ The Jam Cats Music.mkv'
```

## Description

Every week my daughter's music class posts 2 unlisted youtube videos while we are all in quarantine. I download these videos for her normally without problem. 

This week, I was able to download the first video, but the second video keeps throwing the above error. As far as I can tell, there is nothing different about this video than the 10 others that they've posted. Additionally, I am using the same script/options on this video as I am on the others (with the exception of adding the -v flag for debug purposes). 

I searched the issue tracker, and it seems that this error can mostly be related to DRM, or needing an account to access the video, but neither of those things seem to apply to this video, as I am able to play it in an in-private window without logging in on a completely separate network (in addition to being able to play it on my own account on my own LAN).

Any help would be greatly appreciated as to what I may be missing. Thanks

**Comment by ericcao119** [comment]
https://github.com/ytdl-org/youtube-dl/issues/25687
