### ISSUE TITLE
Crunchyroll

### ISSUE THREAD

**Issue by davFaithid** [ytdl-org/youtube-dl#25081]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v -s https://www.crunchyroll.com/case-closed/episode-927-the-scarlet-school-trip-bright-red-arc-779983
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-s', 'https://www.crunchyroll.com/case-closed/episode-927-the-scarlet-school-trip-bright-red-arc-779983']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.0 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg 4.2, ffprobe git-2019-12-24-287620f
[debug] Proxy map: {}
[crunchyroll] 779983: Downloading webpage
ERROR: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\davfa\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\davfa\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\users\davfa\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\crunchyroll.py", line 444, in _real_extract
    video_title = self._html_search_regex(
  File "c:\users\davfa\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "c:\users\davfa\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

So I use mpv to stream Crunchyroll, and when I was trying to play it kept giving 
```
mpv https://www.crunchyroll.com/case-closed/episode-927-the-scarlet-school-trip-bright-red-arc-779983 --demuxer-max-back-bytes=1000000
Warning: option --display-fps was replaced with --override-display-fps and might be removed in the future.
Warning: option --video-aspect was replaced with --video-aspect-override and might be removed in the future.
Auto-loading profile 'protocol.https'
[ytdl_hook] ERROR: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[ytdl_hook] youtube-dl failed: unexpected error ocurred
Failed to recognize file format.

Exiting... (Errors when loading file)
```

So I tried running a skip download test on youtube-dl and had the same issue. 

Thank you,
davFaithid

**Comment by OhNiice** [comment]
Have a look at issue #25047 and PR #25060 :)

**Comment by davFaithid** [comment]
Thank you very much! @OhNiice 

Now all I have to fix is
```
Auto-loading profile 'protocol.https'
 (+) Video --vid=1 (h264 1920x1080 23.976fps)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
     Subs  --sid=1 --slang=enUS 'ass' (ass) (external)
Using hardware decoding (nvdec).
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 cuda[nv12]
[vo/gpu/cuda-nvdec] cuda_ext_vk_init failed
```
but I'm sure I can figure it out. =)
