### ISSUE TITLE
[Youtube] Cannot download lastest video released

### ISSUE THREAD

**Issue by Kochise** [ytdl-org/youtube-dl#25088]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

youtube-dl_videos_m4u.bat:
```
youtube-dl -v --ignore-errors --continue --hls-prefer-native --no-overwrites --no-progress --no-mark-watched --no-call-home --all-subs --sub-format "srt/best" -f "bestaudio[ext=m4a]" --write-thumbnail --write-description --batch-file youtube-dl_videos.txt 1>youtube-dl_stdout.txt 2>youtube-dl_stderr.txt
```

youtube-dl_videos.txt:
```
https://www.youtube.com/watch?v=PNX5CC5FrSc
```

youtube-dl_stdout.txt:
```
[youtube] PNX5CC5FrSc: Downloading webpage
[youtube] {18} signature length 104, html5 player vflset
[youtube] {136} signature length 104, html5 player vflset
[youtube] {247} signature length 100, html5 player vflset
[youtube] {398} signature length 104, html5 player vflset
[youtube] {135} signature length 104, html5 player vflset
[youtube] {244} signature length 104, html5 player vflset
[youtube] {397} signature length 104, html5 player vflset
[youtube] {134} signature length 100, html5 player vflset
[youtube] {243} signature length 100, html5 player vflset
[youtube] {396} signature length 104, html5 player vflset
[youtube] {133} signature length 104, html5 player vflset
[youtube] {242} signature length 104, html5 player vflset
[youtube] {395} signature length 104, html5 player vflset
[youtube] {160} signature length 104, html5 player vflset
[youtube] {278} signature length 104, html5 player vflset
[youtube] {394} signature length 104, html5 player vflset
[youtube] {140} signature length 104, html5 player vflset
[youtube] {249} signature length 104, html5 player vflset
[youtube] {250} signature length 100, html5 player vflset
[youtube] {251} signature length 100, html5 player vflset
[info] Video description is already present
[youtube] PNX5CC5FrSc: Thumbnail is already present
[debug] Invoking downloader on 'https://r5---sn-5goeen7y.googlevideo.com/videoplayback?expire=1588356080&ei=kA-sXtDcAYq_yQWvqpTQBQ&ip=185.65.135.188&id=o-AJIGbLJk0VzXBi4iC2b0hNL8GeUkhK9cYIozMJPiPulK&itag=140&source=youtube&requiressl=yes&mh=eN&mm=31%2C26&mn=sn-5goeen7y%2Csn-5hne6n7s&ms=au%2Conr&mv=m&mvi=4&pl=24&initcwndbps=2612500&vprv=1&mime=audio%2Fmp4&gir=yes&clen=58260611&dur=3599.835&lmt=1587806185081660&mt=1588334369&fvip=5&keepalive=yes&fexp=23882513&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRgIhANK540k3cgYLrZAhYfoOfYsRMdv9ySpAK453zNd3gFlvAiEA470QBaV4xTnR7GWfD5Rdz-OljAXn6Rvxw2fQDg4t1z0%3D&sig=B=ASwTRPzzJM6o-EWDSi7BITgUDHnLaL1F5xEt_ghzbvkAiAzZ69GcHsZbQWWP4A9lk5e=ZBFOKGpk8YQsAYaoJh4fOAhIQRwpLg&ratebypass=yes' 
```

youtube-dl_stderr.txt:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-errors', '--continue', '--hls-prefer-native', '--no-overwrites', '--no-progress', '--no-mark-watched', '--no-call-home', '--all-subs', '--sub-format', 'srt/best', '-f', 'bestaudio[ext=m4a]', '--write-thumbnail', '--write-description', '--batch-file', 'youtube-dl_videos.txt']
[debug] Batch file urls: ['https://www.youtube.com/watch?v=PNX5CC5FrSc']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-04-17-889ad93, ffprobe git-2020-04-17-889ad93
[debug] Proxy map: {}
WARNING: video doesn't have subtitles
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1926, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
 ```

## Description

The latests video released cannot be downloaded/resumed:

https://www.youtube.com/user/OfficialFatBoySlim/videos?view=0&flow=grid
Lastest is: Fatboy Slim - Lockdown Mixtape (Week 5)
https://www.youtube.com/watch?v=PNX5CC5FrSc

Happens with every channel.

**Comment by mutusmurum** [comment]
Same here. Many (but not all) videos are getting error 403 lately. It seems like it happens more often with music videos.

**Comment by Kochise** [comment]
Please add the issue number it duplicates.
