### ISSUE TITLE
Unable to extract video_title - Crunchyroll

### ISSUE THREAD

**Issue by FoxMcloud5655** [ytdl-org/youtube-dl#25093]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--merge-output-format', 'mkv', '--ffmpeg-location', 'ffmpeg\\bin', '--cache-dir', 'cache', '--fixup', 'warn', '--add-metadata', '--no-call-home', '--sub-lang', 'enUS', '--write-sub', '-o', '%%(uploader)s/%%(title)s.%%(ext)s', 'https://www.crunchyroll.com/black-clover/episode-131-a-new-resolve-794726', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2, rtmpdump 2.3
[debug] Proxy map: {}
[crunchyroll] 794726: Downloading webpage
ERROR: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\crunchyroll.py", line 446, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 1014, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

When attempting to download pretty much any new video from Crunchyroll, it is unable to find the video_title.  I wish I could provide more, but I'm not privy to the details of how this all works.

**Comment by TaciturnShadow** [comment]
https://github.com/ytdl-org/youtube-dl/pull/25060

**Comment by FoxMcloud5655** [comment]
Nice!  Glad there's a pull request already.  Didn't think to search there.
