### ISSUE TITLE
youtube-dl fails on particular youtube url

### ISSUE THREAD

**Issue by mcloaked** [ytdl-org/youtube-dl#25090]
## Checklist

- [ x] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2020.03.24**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

$ youtube-dl -v -x --audio-format mp3 https://www.youtube.com/watch?v=9Qy1gUkd9_s
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-x', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=9Qy1gUkd9_s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.2 (CPython) - Linux-5.6.8-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, phantomjs 18, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 9Qy1gUkd9_s: Downloading webpage
[youtube] {18} signature length 104, html5 player vflset
[youtube] {135} signature length 104, html5 player vflset
[youtube] {244} signature length 104, html5 player vflset
[youtube] {134} signature length 100, html5 player vflset
[youtube] {243} signature length 104, html5 player vflset
[youtube] {133} signature length 104, html5 player vflset
[youtube] {242} signature length 104, html5 player vflset
[youtube] {160} signature length 104, html5 player vflset
[youtube] {278} signature length 104, html5 player vflset
[youtube] {140} signature length 104, html5 player vflset
[youtube] {249} signature length 104, html5 player vflset
[youtube] {250} signature length 104, html5 player vflset
[youtube] {251} signature length 104, html5 player vflset
[debug] Invoking downloader on 'https://r3---sn-cu-ac5e.googlevideo.com/videoplayback?expire=1588368480&ei=AECsXuaKNKn5sAL--a3QCg&ip=2a00%3A23c6%3A1c83%3A2500%3Ac5b5%3Adac1%3A3928%3A6966&id=o-AABXNy41hXZt5u-72FM8fRK0SRJBlyznsIXjkWL1GLmU&itag=251&source=youtube&requiressl=yes&mh=zv&mm=31%2C29&mn=sn-cu-ac5e%2Csn-cu-c9ie&ms=au%2Crdu&mv=m&mvi=2&pl=41&initcwndbps=1578750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=4212885&dur=231.201&lmt=1472799824717241&mt=1588346792&fvip=12&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRgIhAKRqPAh44KO40MZu3dYeB6oWLQ9bmH27Rv8d6jce1c5VAiEAj4_lUeZbQAkQyEdOzQICn2zOb4VRz1p2KLxP9QYXAuA%3D&sig==JpPlLsw_gIhALjM0NkuiBHXnnG3IuRNoqI6yejEA7ARftH9AgPNuNanAiEAl-gpliSpLi3t6_mbgX6Pku8jW8Cx9glx0wmpDtSXkj4K&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
The command should have downloaded the .mp3 audio file for the youtube url provided - the url plays normally in the chrome browser in the plasma desktop of my arch linux system.  Other urls for youtube videos as video files download fine.

**Comment by mcloaked** [comment]
My apologies - the addition of the --rm-cache-dir flag does resolve this.
