### ISSUE TITLE
John E Hoover YouTube won't download = error message

### ISSUE THREAD

**Issue by superchap** [ytdl-org/youtube-dl#25097]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

~ $ youtube-dl -v -k --output "~/Desktop/GerardMorin/%(title)s.%(ext)s"  https://www.youtube.com/watch?v=t8Cw9vYhBSs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-k', u'--output', u'~/Desktop/GerardMorin/%(title)s.%(ext)s', u'https://www.youtube.com/watch?v=t8Cw9vYhBSs']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-178-generic-x86_64-with-LinuxMint-18.1-serena
[debug] exe versions: ffmpeg 3.2.2-2, ffprobe 3.2.2-2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] t8Cw9vYhBSs: Downloading webpage
[youtube] {18} signature length 100, html5 player vflset
[youtube] {22} signature length 104, html5 player vflset
[youtube] {313} signature length 104, html5 player vflset
[youtube] {271} signature length 100, html5 player vflset
[youtube] {137} signature length 104, html5 player vflset
[youtube] {248} signature length 104, html5 player vflset
[youtube] {136} signature length 100, html5 player vflset
[youtube] {247} signature length 100, html5 player vflset
[youtube] {135} signature length 100, html5 player vflset
[youtube] {244} signature length 104, html5 player vflset
[youtube] {134} signature length 100, html5 player vflset
[youtube] {243} signature length 104, html5 player vflset
[youtube] {133} signature length 100, html5 player vflset
[youtube] {242} signature length 104, html5 player vflset
[youtube] {160} signature length 104, html5 player vflset
[youtube] {278} signature length 104, html5 player vflset
[youtube] {140} signature length 104, html5 player vflset
[youtube] {249} signature length 100, html5 player vflset
[youtube] {250} signature length 104, html5 player vflset
[youtube] {251} signature length 100, html5 player vflset
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r1---sn-ni5f-tfbl.googlevideo.com/videoplayback?expire=1588403017&ei=6casXva-FJjSkgaFsLegBg&ip=2604%3A3d09%3Aab83%3Aea00%3A109d%3A5eb5%3Acd12%3A1a22&id=o-AAArP7i17OwPnJwvalOQWBCtgRuNjTe11zuEVDAtha63&itag=313&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313&source=youtube&requiressl=yes&mh=f2&mm=31%2C29&mn=sn-ni5f-tfbl%2Csn-vgqsener&ms=au%2Crdu&mv=m&mvi=0&pl=36&initcwndbps=1795000&vprv=1&mime=video%2Fwebm&gir=yes&clen=561600074&dur=893.475&lmt=1588365488045366&mt=1588381350&fvip=1&keepalive=yes&beids=23886215&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRgIhAPZYkNci7sbwYErKs2I4osXi6lPwxOXw73dNooqag_rTAiEAu7kagEpJf8lnO8Hc00NDoFMjBmgGH1EmadPt0eMQdcU%3D&sig=x=An_ozMHAger8848iyEL2n5qkgIdmjcgMgQqMeMxG8XmBiAR-57HLnsZIBEcSRArl-Q3=WHdjy9dNkslevkc1DPWCJAhIQRwpLq&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

[2]+  Exit 1                  youtube-dl -k --output "~/Desktop/GerardMorin/%(title)s.%(ext)s" https://www.youtube.com/watch?v=t8Cw9vYhBSs

## Description

WRITE DESCRIPTION HERE

Simply, there's a video that I'm looking to download off of youtube. It's 'sensitive' material. I can play it just fine. Just won't download. This is the error message. Weird.

~ $ [youtube] t8Cw9vYhBSs: Downloading webpage
ERROR: unable to download video data: HTTP Error 403: Forbidden

Thanks in advance.
Love YouTube-dl !!!

**Comment by superchap** [comment]
Hello? Is there a fix to this download that I'm not seeing here? Thanks in advance.

**Comment by superchap** [comment]
Please ignore > I've clicked on the 'duplicate' and studied that info. I'll give it a try. Thanks so much.

**Comment by superchap** [comment]
Worked like a charm! Thanks so much everyone.
