### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by Rathindholakia** [ytdl-org/youtube-dl#25102]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.05.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '18', 'https://www.youtube.com/playlist?list=PL61035752268BE45B']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.7.5 (CPython) - Linux-5.4.0-26-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PL61035752268BE45B: Downloading webpage
[download] Downloading playlist: Sri Vidya Tantra Lectures
[youtube:playlist] playlist Sri Vidya Tantra Lectures: Downloading 41 videos
[download] Downloading video 1 of 41
[youtube] -X6l_UWJ6Kk: Downloading webpage
[youtube] -X6l_UWJ6Kk: Downloading video info webpage
[debug] Invoking downloader on 'https://r5---sn-ci5gup-cagd.googlevideo.com/videoplayback?expire=1588467193&ei=mcGtXv3mMI-WvwSEmYaQCg&ip=122.181.39.106&id=o-AEBwJawGGzOyZyHjcsGl6Loj0PI_LfboNnBNwF31Tlbb&itag=18&source=youtube&requiressl=yes&mh=LL&mm=31%2C29&mn=sn-ci5gup-cagd%2Csn-ci5gup-h55z&ms=au%2Crdu&mv=m&mvi=4&pl=19&initcwndbps=686250&vprv=1&mime=video%2Fmp4&gir=yes&clen=16935772&ratebypass=yes&dur=589.136&lmt=1409363605345671&mt=1588445490&fvip=5&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJpPlLswRQIgSCikPS41SBwuasLS8I8O8zVtWB4fgk431l3aWdOVbiACIQC4VUeBEmj4Nayu_kC4DqlzM5jk36GC_yp10C2PaHI_Kw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIgBEtODTYkV5DFX4T8p1BLKZ7Om27TUCtoQEYBUwjwJ9ICIQDNhwY2UFnxUKrihNT940JyqdFws2vfroxetVo1I8Wdxg%3D%3D'
[download] Sri Vidya (01_41) Tantra Kundalini Kriya Yoga Meditation Swami Rama--X6l_UWJ6Kk.mp4 has already been downloaded
[download] 100% of 16.15MiB
[download] Downloading video 2 of 41
[youtube] r1MmE-vD-Tg: Downloading webpage
[youtube] r1MmE-vD-Tg: Downloading video info webpage
[debug] Invoking downloader on 'https://r6---sn-ci5gup-cags.googlevideo.com/videoplayback?expire=1588467195&ei=m8GtXu35NpG8oQOTgb7IBw&ip=122.181.39.106&id=o-AEC_oBOC3bAwn3frMKapszVP0k1KEcoiefejRpr3v_yW&itag=18&source=youtube&requiressl=yes&mh=IV&mm=31%2C29&mn=sn-ci5gup-cags%2Csn-ci5gup-h55e&ms=au%2Crdu&mv=m&mvi=5&pcm2cms=yes&pl=19&initcwndbps=718750&vprv=1&mime=video%2Fmp4&gir=yes&clen=18655045&ratebypass=yes&dur=596.102&lmt=1559492968514627&mt=1588445490&fvip=6&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJpPlLswRQIgEoelcnZFB_XXUdhpH0GMQIkHHvMptVwTHtKdAijplC4CIQD-qW1v0WUbUFbXuIURl9prmcREM3-1CkGMhdkLYJ9ZLg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRAIgLBu87KO1L5Uf3p2wxrSqCuin3235FImHHyjjCfxLzfoCIFvz09LUokxY-J1dWK9jrI7nbfNPyBfCDeov6oW5Xpwv'
[download] Sri Vidya (02_41) Tantra Kundalini Kriya Yoga Meditation Swami Rama-r1MmE-vD-Tg.mp4 has already been downloaded
[download] 100% of 17.79MiB
[download] Downloading video 3 of 41
[youtube] y8Ltup6DZsY: Downloading webpage
[youtube] y8Ltup6DZsY: Downloading video info webpage
[debug] Invoking downloader on 'https://r5---sn-ci5gup-cag6.googlevideo.com/videoplayback?expire=1588467197&ei=ncGtXua4K-a31Aa-h6fICQ&ip=122.181.39.106&id=o-ABiGOiH_2T8sO_JOm0LYmwpZZNH7oViOT86dUNaXRrCW&itag=18&source=youtube&requiressl=yes&mh=ES&mm=31%2C29&mn=sn-ci5gup-cag6%2Csn-ci5gup-h55z&ms=au%2Crdu&mv=m&mvi=4&pl=19&initcwndbps=720000&vprv=1&mime=video%2Fmp4&gir=yes&clen=17671436&ratebypass=yes&dur=557.093&lmt=1559589630455669&mt=1588445490&fvip=5&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJpPlLswRgIhAJOML7d9cTz7GLnUClFg2Vi_BjtJoqSawMjlKMnkVTGYAiEAonhXaKTd-y4CcQ1XjC9FeGpHXwvN3XKtBIWAzBoOCj4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIgbl5Q1lRMgDFsmY3O31pq30ItGj48whStfPa0h_GdbpwCIQChxduf9J7MpBRJHUI3Es6NP1pik9qVxmKOjMRQ9U151g%3D%3D'
[download] Sri Vidya (03_41) Tantra Kundalini Kriya Yoga Meditation Swami Rama-y8Ltup6DZsY.mp4 has already been downloaded
[download] 100% of 16.85MiB
[download] Downloading video 4 of 41
[youtube] w8sbnXS6auk: Downloading webpage
[youtube] w8sbnXS6auk: Downloading video info webpage
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {18} signature length 104, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1380, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1258, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/s/player/64dddad9/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/s/player/64dddad9/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1380, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1258, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/s/player/64dddad9/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1380, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1258, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/s/player/64dddad9/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 2043, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1390, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1380, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1258, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/s/player/64dddad9/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/s/player/64dddad9/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

I am running Ubuntu -19.10. I am trying to download all videos in the following playlist: "https://www.youtube.com/playlist?list=PL61035752268BE45B" but my download stops after 3rd video. I tried changing format to no avail. it throws warning ofHTML5 player then throws Signature extraction failure.. and it terminates.

**Comment by Rathindholakia** [comment]
Oh I am really sorry to bother with this ticket! apparently my system was running old version in tab, had to restart the terminal fixed the issue. Thank you!
