### ISSUE TITLE
ok.ru 

### ISSUE THREAD

**Issue by treble2019** [ytdl-org/youtube-dl#25105]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.05.03**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
./youtube-dl  https://ok.ru/video/c1466275 --verbose
[debug] System config: []
[debug] User config: [u'--no-mtime']
[debug] Custom config: []
[debug] Command-line args: [u'https://ok.ru/video/c1466275', u'--verbose']
[debug] Encodings: locale ISO-8859-1, fs ISO-8859-1, out ISO-8859-1, pref ISO-8859-1
[debug] youtube-dl version 2020.05.03
[debug] Python version 2.7.17 (CPython) - Linux-4.18.0-25-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[generic] c1466275: Requesting header
WARNING: Falling back on generic information extractor.
[generic] c1466275: Downloading webpage
[generic] c1466275: Extracting information
ERROR: Unsupported URL: https://ok.ru/video/c1466275
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 2378, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "./youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "./youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 8, column 54
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 3370, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://ok.ru/video/c1466275

```

## Description

Related
https://github.com/ytdl-org/youtube-dl/issues/23874
WRITE DESCRIPTION HERE

Thanks

**Comment by kfur** [comment]
i think https://ok.ru/video/c1466275 it's not a video url
maybe playlist 
i assume ok.ru extractor doesn't support playlists
