### ISSUE TITLE
Long videos downloads from globoplay always stops near 1%

### ISSUE THREAD

**Issue by vico93** [ytdl-org/youtube-dl#25119]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.05.03**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
youtube-dl https://globoplay.globo.com/v/8528009/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://globoplay.globo.com/v/8528009/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[Globo] 8528009: Downloading JSON metadata
[Globo] 8528009: Downloading security hash for 5eaee02f24c7b3582206e8a8_90_720_m3u8
[Globo] 5eaee02f24c7b3582206e8a8_90_720_m3u8: Downloading m3u8 information
[Globo] 8528009: Downloading security hash for 5eaee02f24c7b3582206e8a8_360_720_l_m3u8
[Globo] 5eaee02f24c7b3582206e8a8_360_720_l_m3u8: Downloading m3u8 information
[Globo] 8528009: Downloading security hash for 5eaee02f24c7b3582206e8a8_240_720_m3u8
[Globo] 5eaee02f24c7b3582206e8a8_240_720_m3u8: Downloading m3u8 information
[Globo] 8528009: Downloading security hash for 5eaee02f24c7b3582206e8a8_360_720_m3u8
[Globo] 5eaee02f24c7b3582206e8a8_360_720_m3u8: Downloading m3u8 information
[Globo] 8528009: Downloading security hash for 5eaee02f24c7b3582206e8a8_90_720_l_m3u8
[Globo] 5eaee02f24c7b3582206e8a8_90_720_l_m3u8: Downloading m3u8 information
[Globo] 8528009: Downloading security hash for 5eaee02f24c7b3582206e8a8_90_480_m3u8
[Globo] 5eaee02f24c7b3582206e8a8_90_480_m3u8: Downloading m3u8 information
[Globo] 8528009: Downloading security hash for 5eaee02f24c7b3582206e8a8_360_720_mpd
[Globo] 5eaee02f24c7b3582206e8a8_360_720_mpd: Downloading MPD manifest
[Globo] 8528009: Downloading security hash for 5eaee02f24c7b3582206e8a8_240_720_l_m3u8
[Globo] 5eaee02f24c7b3582206e8a8_240_720_l_m3u8: Downloading m3u8 information
[Globo] 8528009: Downloading security hash for 5eaee02f24c7b3582206e8a8_360_720_l_manifest
[Globo] 5eaee02f24c7b3582206e8a8_360_720_l_manifest: Downloading ISM manifest
[Globo] 8528009: Downloading security hash for 5eaee02f24c7b3582206e8a8_360_720_l_mpd
[Globo] 5eaee02f24c7b3582206e8a8_360_720_l_mpd: Downloading MPD manifest
[Globo] 8528009: Downloading security hash for 5eaee02f24c7b3582206e8a8_90_720_mpd
[Globo] 5eaee02f24c7b3582206e8a8_90_720_mpd: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://vodstreaming02a.video.globo.com/p3653/r90_720/v0/be/8f/c8/8528009_c8afd4c0124f35ab483e6aa8f991eed7360e50d1/8528009-52rqHT8-manifest.ism/8528009.mpd?h=0411588557470189690685615886438709147602878GKsP4encv7CA3H-jHTfZ5A&k=html5&a=A&u='
[dashsegments] Total fragments: 5840
[download] Destination: GP do Japão de 1988, o primeiro título mundial de Ayrton Senna-8528009.fdash-video_por=1961000-2.mp4
[download]   0.9% of ~1.20GiB at 424.31KiB/s ETA 03:17:51  ERROR: unable to download video data: ''
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 1920, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\dash.py", line 48, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\fragment.py", line 102, in _download_fragment
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\utils.py", line 2728, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1186, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1227, in getresponse
  File "C:\Python\Python34\lib\http\client.py", line 386, in begin
  File "C:\Python\Python34\lib\http\client.py", line 356, in _read_status
http.client.BadStatusLine: ''
```

## Description

I'm trying to download [a 1:37 hour-long video from globoplay](https://globoplay.globo.com/v/8528009/) (using 2020.05.03) but no matter if i use --continue or not the download always stops near the 1% mark, and trying to resume the download recalling the same command line makes the download restart on 0%.

I'm using the standalone executable on Windows 10 x64.

**Comment by dstftw** [comment]
You must provide working proxy/VPN.

**Comment by vico93** [comment]
> You must provide working proxy/VPN.

@dstftw Strange. I live in Brazil (same country of Globo) and can watch the video without issues on Chrome. Didnt use any VPN for that or have any Proxy between my computer and my ISP.

**Comment by dstftw** [comment]
This does not mean everybody live in Brazil at all.

**Comment by vico93** [comment]
I kinda didnt understand. Did you mean you cant access the website for test?
