### ISSUE TITLE
[puhutv] Download a whole series

### ISSUE THREAD

**Issue by marium0505** [ytdl-org/youtube-dl#25125]
## Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running youtube-dl version **2020.05.03**
- [X] I've searched the bugtracker for similar site feature requests including closed ones

## Description

I had originally a pretty long request , but my browser refreshed for some reason so lost all of it (why no autosave feature 😭). Here we go again...

It would be nice if we could download whole series on puhutv similar to how we can download entire playlists on YouTube. 

I have currently used a workaround where I extract all the episode links in the series, and then put them in a batch file which I use to download using the `--batch-file` parameter. This method works, but would be great if we could just use the show link. 

### **`youtube-dl.exe --verbose -f "(bestvideo+bestaudio/best)[protocol^=m3u8_native]" https://puhutv.com/cilek-kokusu-detay`**
PS: I use `-f "(bestvideo+bestaudio/best)[protocol^=m3u8_native]"` as the default protocol doesn't work on puhutv (see #25124 ).
```
[debug] System config: []
[debug] User config: ['--console-title', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', '(bestvideo+bestaudio/best)[protocol^=m3u8_native]', 'https://puhutv.com/cilek-kokusu-detay']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19613
[debug] exe versions: ffmpeg N-90908-g0807a77160
[debug] Proxy map: {}
[puhutv:serie] cilek-kokusu: Downloading JSON metadata
[puhutv] cilek-kokusu-detay: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\puhutv.py", line 66, in _real_extract
KeyError: 'id'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\puhutv.py", line 66, in _real_extract
KeyError: 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\common.py", line 543, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### **`youtube-dl.exe --verbose -f "(bestvideo+bestaudio/best)[protocol^=m3u8_native]" https://puhutv.com/carpisma-detay`**
PS: I use `-f "(bestvideo+bestaudio/best)[protocol^=m3u8_native]"` as the default protocol doesn't work on puhutv (see #25124 ).
```
C:\bin>youtube-dl.exe --verbose -f "(bestvideo+bestaudio/best)[protocol^=m3u8_native]" https://puhutv.com/carpisma-detay
[debug] System config: []
[debug] User config: ['--console-title', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', '(bestvideo+bestaudio/best)[protocol^=m3u8_native]', 'https://puhutv.com/carpisma-detay']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19613
[debug] exe versions: ffmpeg N-90908-g0807a77160
[debug] Proxy map: {}
[puhutv:serie] carpisma: Downloading JSON metadata
[puhutv] carpisma-detay: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\puhutv.py", line 66, in _real_extract
KeyError: 'id'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\puhutv.py", line 66, in _real_extract
KeyError: 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\common.py", line 543, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by ahmedtds** [comment]
I think this is already supported but just doesn't work anymore

```
class PuhuTVSerieIE(InfoExtractor):
    _VALID_URL = r'https?://(?:www\.)?puhutv\.com/(?P<id>[^/?#&]+)-detay'
```

I remember downloading a whole series with just one link some time ago. Tried now but didn't work.

**Comment by marium0505** [comment]
> I think this is already supported but just doesn't work anymore
> 
> ```
> class PuhuTVSerieIE(InfoExtractor):
>     _VALID_URL = r'https?://(?:www\.)?puhutv\.com/(?P<id>[^/?#&]+)-detay'
> ```
> 
> I remember downloading a whole series with just one link some time ago. Tried now but didn't work.

@ahmedtds Yeah, I actually noticed that too when I looked at the code. Wonder why it stopped working. Tried quite a few series with the same result. 

It is possible that puhutv has done a lot of modifications recently, as the download of single videos has also been broken.  I made a ticket about it #25124 and it was just solved in https://github.com/ytdl-org/youtube-dl/commit/f7f304910d1c1fc19313231d424daba304e1de71.
