### ISSUE TITLE
[puhutv] Downloading from puhutv with http protocol (default protocol) does not work

### ISSUE THREAD

**Issue by marium0505** [ytdl-org/youtube-dl#25124]
## Checklist

- [x] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.05.03**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

### **`youtube-dl.exe --verbose https://puhutv.com/bana-sevmeyi-anlat-1-bolum-izle`**
```
[debug] System config: []
[debug] User config: ['--console-title', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://puhutv.com/bana-sevmeyi-anlat-1-bolum-izle']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19613
[debug] exe versions: ffmpeg N-90908-g0807a77160
[debug] Proxy map: {}
[puhutv] bana-sevmeyi-anlat-1-bolum: Downloading JSON metadata
[puhutv] bana-sevmeyi-anlat-1-bolum: Downloading video JSON
[puhutv] 5296: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://7eoxlokk.rocketcdn.com/4151/mp4/1080p.mp4?token=4X_m13VgnW7FhzEEE2NqMA&expires=1588640468&p=1'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 1926, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

### **`youtube-dl.exe --verbose https://puhutv.com/siyah-inci-1-bolum-izle`**
```
[debug] System config: []
[debug] User config: ['--console-title', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://puhutv.com/siyah-inci-1-bolum-izle']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19613
[debug] exe versions: ffmpeg N-90908-g0807a77160
[debug] Proxy map: {}
[puhutv] siyah-inci-1-bolum: Downloading JSON metadata
[puhutv] siyah-inci-1-bolum: Downloading video JSON
[puhutv] 15824: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://7eoxlokk.rocketcdn.com/14104/mp4/1080p.mp4?token=jn-35D66TNsKFpswj2lghQ&expires=1588641153&p=1'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 1926, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

## Description

Youtube-dl is unable to download from puhutv. When trying to download it gives the error code 404: Not Found.

I have added the code output for two commands with episodes from two shows above (you can see the command used above the output in bold). 

It took me quite a lot of testing, but it seems that the issue is limited to when downloading with the http protocol (which seems to be the default). The issue doesn't happen when using `-f "(bestvideo+bestaudio/best)[protocol^=m3u8_native]"`. So the cause of the issue seems to be limited to when you download using the HTTP protocol. 

### **`youtube-dl.exe --verbose -f "(bestvideo+bestaudio/best)[protocol^=http]" https://puhutv.com/bana-sevmeyi-anlat-1-bolum-izle`**
```
[debug] System config: []
[debug] User config: ['--console-title', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', '(bestvideo+bestaudio/best)[protocol^=http]', 'https://puhutv.com/bana-sevmeyi-anlat-1-bolum-izle']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19613
[debug] exe versions: ffmpeg N-90908-g0807a77160
[debug] Proxy map: {}
[puhutv] bana-sevmeyi-anlat-1-bolum: Downloading JSON metadata
[puhutv] bana-sevmeyi-anlat-1-bolum: Downloading video JSON
[puhutv] 5296: Downloading m3u8 information
[debug] Invoking downloader on 'http://7eoxlokk.rocketcdn.com/4151/mp4/1080p.mp4?token=aojgmsI36DBs2Pe0EeoSlA&expires=1588642099&p=1'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 1926, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

### **`youtube-dl.exe --verbose -f "(bestvideo+bestaudio/best)[protocol^=http]" https://puhutv.com/siyah-inci-1-bolum-izle`**
```
[debug] System config: []
[debug] User config: ['--console-title', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', '(bestvideo+bestaudio/best)[protocol^=http]', 'https://puhutv.com/siyah-inci-1-bolum-izle']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19613
[debug] exe versions: ffmpeg N-90908-g0807a77160
[debug] Proxy map: {}
[puhutv] siyah-inci-1-bolum: Downloading JSON metadata
[puhutv] siyah-inci-1-bolum: Downloading video JSON
[puhutv] 15824: Downloading m3u8 information
[debug] Invoking downloader on 'http://7eoxlokk.rocketcdn.com/14104/mp4/1080p.mp4?token=jn-35D66TNsKFpswj2lghQ&expires=1588641153&p=1'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 1926, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

### **`youtube-dl.exe --verbose -f "(bestvideo+bestaudio/best)[protocol^=m3u8_native]" https://puhutv.com/bana-sevmeyi-anlat-1-bolum-izle`**
```
[debug] System config: []
[debug] User config: ['--console-title', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', '(bestvideo+bestaudio/best)[protocol^=m3u8_native]', 'https://puhutv.com/bana-sevmeyi-anlat-1-bolum-izle']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19613
[debug] exe versions: ffmpeg N-90908-g0807a77160
[debug] Proxy map: {}
[puhutv] bana-sevmeyi-anlat-1-bolum: Downloading JSON metadata
[puhutv] bana-sevmeyi-anlat-1-bolum: Downloading video JSON
[puhutv] 5296: Downloading m3u8 information
[debug] Invoking downloader on 'http://7eoxlokk.rocketcdn.com/4151/hls/1080p/chunklist.m3u8?token=kCuYZiXiJDY-OVmgHbgfOA&expires=1588641779&p=1'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 702
[download] Destination: 1. Bölüm 1. Sezon 1. Bölüm-5296.mp4
[download]   0.4% of ~1.82GiB at  8.56MiB/s ETA 05:20      ^C
```

### **`youtube-dl.exe --verbose -f "(bestvideo+bestaudio/best)[protocol^=m3u8_native]" https://puhutv.com/siyah-inci-1-bolum-izle`**
```
[debug] System config: []
[debug] User config: ['--console-title', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', '(bestvideo+bestaudio/best)[protocol^=m3u8_native]', 'https://puhutv.com/siyah-inci-1-bolum-izle']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19613
[debug] exe versions: ffmpeg N-90908-g0807a77160
[debug] Proxy map: {}
[puhutv] siyah-inci-1-bolum: Downloading JSON metadata
[puhutv] siyah-inci-1-bolum: Downloading video JSON
[puhutv] 15824: Downloading m3u8 information
[debug] Invoking downloader on 'http://7eoxlokk.rocketcdn.com/14104/hls/1080p/chunklist.m3u8?token=gVN7UleCa7FFaEdUzAOwEw&expires=1588641866&p=1'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 862
[download] Destination: 1. Bölüm 1. Sezon 1. Bölüm-15824.mp4
[download]   0.1% of ~329.03MiB at 443.85KiB/s ETA 30:13     ^C
```

**Comment by marium0505** [comment]
That was quick, @dstftw!  👌👍
