### ISSUE TITLE
[ARD] Falling back on generic information extractor -> Unsupported URL

### ISSUE THREAD

**Issue by mklein-de** [ytdl-org/youtube-dl#25134]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.05.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.daserste.de/information/reportage-dokumentation/erlebnis-erde/videosextern/woelfe-und-herdenschutzhunde-ungleiche-brueder-100.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.03
[debug] Python version 2.7.17 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] woelfe-und-herdenschutzhunde-ungleiche-brueder-100: Requesting header
WARNING: Falling back on generic information extractor.
[generic] woelfe-und-herdenschutzhunde-ungleiche-brueder-100: Downloading webpage
[generic] woelfe-und-herdenschutzhunde-ungleiche-brueder-100: Extracting information
ERROR: Unsupported URL: https://www.daserste.de/information/reportage-dokumentation/erlebnis-erde/videosextern/woelfe-und-herdenschutzhunde-ungleiche-brueder-100.html
Traceback (most recent call last):
  File "/Volumes/Users/michael/youtube-dl/youtube_dl/extractor/generic.py", line 2378, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/Volumes/Users/michael/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/Volumes/Users/michael/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: mismatched tag: line 144, column 2
Traceback (most recent call last):
  File "/Volumes/Users/michael/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/Volumes/Users/michael/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/Volumes/Users/michael/youtube-dl/youtube_dl/extractor/generic.py", line 3370, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.daserste.de/information/reportage-dokumentation/erlebnis-erde/videosextern/woelfe-und-herdenschutzhunde-ungleiche-brueder-100.html
```

## Description

Video fails to download, works fine in browser

**Comment by mklein-de** [comment]
thank you for the fast response. Would you mind pointing me to the original issue?

**Comment by sajid415** [comment]
WARNING: [generic] Falling back on generic information extractor
ERROR: Unsupported URL: https://github.com/yt-dlp/yt-dlp/issues?q=
WARNING: [generic] Falling back on generic information extractor
ERROR: Unsupported URL: https://github.com/yt-dlp/yt-dlp/issues?q=

See what is this sir i unable to download video from seal please do something 😔

**Comment by sajid415** [comment]
Could not fetch video info 
Please fix that problem fast
