### ISSUE TITLE
Downloading from site requiring cookies failed

### ISSUE THREAD

**Issue by IndustrialOne** [ytdl-org/youtube-dl#25143]
Command:

youtube-dl --cookies "C:\Users\Admin\AppData\Roaming\Mozilla\Firefox\Profiles\ueuez3vw.temp\cookies.sqlite" "www.webpage.com"

C:\Users\Admin>youtube-dl --cookies "C:\Users\Admin\AppData\Roaming\Mozilla\Firefox\Profiles\abcdef.temp\cookies.sqlite" "www.webpage.com"
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\
__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\
__init__.py", line 441, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\
YoutubeDL.py", line 419, in __init__
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\
YoutubeDL.py", line 2329, in _setup_opener
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\
utils.py", line 2757, in load
  File "C:\Python\Python34\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 111: character maps to <undef
ined>

C:\Users\Admin>

Hopefully cookies.sqlite is the correct file, the documentation said it's a text file. If it is the right file, what am I doing wrong? Thanks.

**Comment by dstftw** [comment]
>Hopefully cookies.sqlite is the correct file, the documentation said it's a text file

Are you troll or what?

**Comment by IndustrialOne** [comment]
No, I am not a troll. What did I do wrong? I have no cookies.txt anywhere, what the hell else was I supposed to select?

________________________________

**Comment by dstftw** [comment]
Read [FAQ](https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl)?
