### ISSUE TITLE
Paramount Network ERROR: ParamountNetwork returned error: not_found - Sorry, this video is not found or no longer available due to date or rights restrictions.

### ISSUE THREAD

**Issue by roadzy** [ytdl-org/youtube-dl#25179]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

So Paramount Network is reporting that video not found.  It now says the same thing on the video image (this is new).  If I click it, log in with my provider it plays.  So then I opened up the chrome dev tools and grabbed the m3u8 string and that gives me a different error.  This all worked fine 2 weeks ago using youtube-dl with no work around.

Error output:

 youtube-dl-abb -v https://www.paramountnetwork.com/episodes/6rlnqh/yellowstone-the-remembering-season-1-ep-6
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--hls-prefer-native', '--ap-mso', 'auth_atlanticbb_net', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-v', 'https://www.paramountnetwork.com/episodes/6rlnqh/yellowstone-the-remembering-season-1-ep-6']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.7.2 (CPython) - Linux-3.10.0-1062.18.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[debug] Using fake IP 6.184.207.240 (US) as X-Forwarded-For.
[ParamountNetwork] yellowstone-the-remembering-season-1-ep-6: Downloading webpage
[ParamountNetwork] 0c802423-744d-11e8-881b-70df2f866ace: Downloading info
[ParamountNetwork] 0c802423-744d-11e8-881b-70df2f866ace: Extracting information
[ParamountNetwork] 0c802423-744d-11e8-881b-70df2f866ace: Downloading video urls
ERROR: ParamountNetwork returned error: not_found -
      Sorry, this video is not found or no longer available due to date or rights restrictions.

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/mtv.py", line 287, in _real_extract
    videos_info = self._get_videos_info(mgid)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/mtv.py", line 216, in _get_videos_info
    return self._get_videos_info_from_url(info_url, video_id, use_hls)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/mtv.py", line 228, in _get_videos_info_from_url
    info = self._get_video_info(item, use_hls)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/mtv.py", line 156, in _get_video_info
    raise ExtractorError(message, expected=True)
youtube_dl.utils.ExtractorError: ParamountNetwork returned error: not_found -
      Sorry, this video is not found or no longer available due to date or rights restrictions.

Other error:

youtube-dl -v https://dlvrsvc.mtvnservices.com/api/playlist/gsp.alias/mediabus/paramount-network.com/2020/04/29/10/39/24/af5714cf007548eca6c058ce1a5fc632/2071375/0/stream_1920x1080_4685914_1537434755.m3u8?tk=st=1588875901~exp=1588890301~acl=/api/playlist/gsp.alias/mediabus/paramount-network.com/2020/04/29/10/39/24/af5714cf007548eca6c058ce1a5fc632/2071375/0/stream_1920x1080_4685914_1537434755.m3u8*~hmac=eaf0b64192f5a31f0d19254730ba06d5f42a633532b76f3bab1f898653081656&account=paramountnetwork.com&cdn=stackpath
[1] 3160
[2] 3161
[2]+  Done                    account=paramountnetwork.com

[root@hostname newfolder]# [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--hls-prefer-native', '-v', 'https://dlvrsvc.mtvnservices.com/api/playlist/gsp.alias/mediabus/paramount-network.com/2020/04/29/10/39/24/af5714cf007548eca6c058ce1a5fc632/2071375/0/stream_1920x1080_4685914_1537434755.m3u8?tk=st=1588875901~exp=1588890301~acl=/api/playlist/gsp.alias/mediabus/paramount-network.com/2020/04/29/10/39/24/af5714cf007548eca6c058ce1a5fc632/2071375/0/stream_1920x1080_4685914_1537434755.m3u8*~hmac=eaf0b64192f5a31f0d19254730ba06d5f42a633532b76f3bab1f898653081656']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.7.2 (CPython) - Linux-3.10.0-1062.18.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[generic] stream_1920x1080_4685914_1537434755: Requesting header
WARNING: Could not send HEAD request to https://dlvrsvc.mtvnservices.com/api/playlist/gsp.alias/mediabus/paramount-network.com/2020/04/29/10/39/24/af5714cf007548eca6c058ce1a5fc632/2071375/0/stream_1920x1080_4685914_1537434755.m3u8?tk=st=1588875901~exp=1588890301~acl=/api/playlist/gsp.alias/mediabus/paramount-network.com/2020/04/29/10/39/24/af5714cf007548eca6c058ce1a5fc632/2071375/0/stream_1920x1080_4685914_1537434755.m3u8*~hmac=eaf0b64192f5a31f0d19254730ba06d5f42a633532b76f3bab1f898653081656: HTTP Error 404: Not Found
[generic] stream_1920x1080_4685914_1537434755: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

[1]+  Exit 1                  /root/youtube-dl-master/bin/youtube-dl --hls-prefer-native -v https://dlvrsvc.mtvnservices.com/api/playlist/gsp.alias/mediabus/paramount-network.com/2020/04/29/10/39/24/af5714cf007548eca6c058ce1a5fc632/2071375/0/stream_1920x1080_4685914_1537434755.m3u8?tk=st=1588875901~exp=1588890301~acl=/api/playlist/gsp.alias/mediabus/paramount-network.com/2020/04/29/10/39/24/af5714cf007548eca6c058ce1a5fc632/2071375/0/stream_1920x1080_4685914_1537434755.m3u8*~hmac=eaf0b64192f5a31f0d19254730ba06d5f42a633532b76f3bab1f898653081656

Couple last things... Yes my provider isn't officially supported but someone helped me a while ago write the code for it to work. I maintain it and add it back in every time a new release is added.  Also 
 if the command looks odd, it's because I have an alias setup. (alias youtube-dl-abb='/root/youtube-dl-master/bin/youtube-dl --hls-prefer-native --ap-mso auth_atlanticbb_net --ap-username xxxxx --ap-password xxxxx'

Thanks for any input.

**Comment by roadzy** [comment]
@dstftw can you provide any details?  Is the site the issue?

**Comment by roadzy** [comment]
@dstftw Site is no longer saying that the videos are unavailable, but still getting the same error.
