### ISSUE TITLE
Writing Cache Permission Error [Errno 13] 

### ISSUE THREAD

**Issue by Teresawithoutah** [ytdl-org/youtube-dl#25178]
Receiving a writing permission issue to cache when running version 2020.05.03 of `youtube-dl`. Any tips?
```
[youtube] PALMMqZLAQk: Downloading webpage
[youtube] PALMMqZLAQk: Downloading js player 52b1e972
WARNING: Writing cache to '/Users/teresawithoutah/.cache/youtube-dl/youtube-sigfuncs/js_52b1e972_101.json' failed: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/youtube_dl/cache.py", line 49, in store
    os.makedirs(os.path.dirname(fn))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/teresawithoutah/.cache/youtube-dl'

[youtube] PALMMqZLAQk: Downloading js player 52b1e972
WARNING: Writing cache to '/Users/teresawithoutah/.cache/youtube-dl/youtube-sigfuncs/js_52b1e972_105.json' failed: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/youtube_dl/cache.py", line 49, in store
    os.makedirs(os.path.dirname(fn))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/teresawithoutah/.cache/youtube-dl'

```

**Comment by dstftw** [comment]
Read error message?
