### ISSUE TITLE
pornhub.com - Specifically report "Video is not available in your country" when it is opportune instead of "Unable to extract title"

### ISSUE THREAD

**Issue by ale5000-git** [ytdl-org/youtube-dl#25199]
## Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running youtube-dl version **2020.05.08**
- [X] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Specifically report "Video is not available in your country" when it is opportune instead of "Unable to extract title".

Output:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.pornhub.com/view_video.php?viewkey=ph5dffec575cfff']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[PornHub] ph5dffec575cfff: Downloading pc webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\pornhub.py", line 206, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 1014, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by kcubeterm** [comment]
Use vpn or proxy,

**Comment by ale5000-git** [comment]
Thanks, I know but here I'm just asking to have a more correct error message.

**Comment by dirkf** [comment]
This should be working now, but the test video is 404 (and we would have needed to know which countries were allowed/blocked). Please open a new issue if not.
