### ISSUE TITLE
Vimeo "Conversion failed!"

### ISSUE THREAD

**Issue by mockdeep** [ytdl-org/youtube-dl#25194]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.05.08**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://vimeo.com/415656502', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-99-generic-x86_64-with-LinuxMint-18.3-sylvia
[debug] exe versions: avconv 2.8.15, avprobe 2.8.15, ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[vimeo] 415656502: Downloading webpage
[vimeo] 415656502: Extracting information
[vimeo] 415656502: Downloading JSON metadata
[vimeo] 415656502: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[vimeo] 415656502: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 415656502: Downloading fastly_skyfire m3u8 information
[vimeo] 415656502: Downloading akfire_interconnect_quic MPD information
[vimeo] 415656502: Downloading fastly_skyfire MPD information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://skyfire.vimeocdn.com/1588962330-0x94aca96b83569050293f98c87d2fc9044a1fbed8/6644cf92-2c4d-4662-8805-081862299c38/sep/video/2691010a/playlist.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 26
[download] Destination: The Rickety Lady (horror short)-415656502.fhls-fastly_skyfire-2343.mp4
[download] 100% of 40.18MiB in 00:08
[debug] Invoking downloader on u'https://skyfire.vimeocdn.com/1588962330-0x94aca96b83569050293f98c87d2fc9044a1fbed8/6644cf92-2c4d-4662-8805-081862299c38/sep/audio/b7917808/playlist.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 26
[download] Destination: The Rickety Lady (horror short)-415656502.fhls-fastly_skyfire-audio-medium-audio.mp4
[download] 100% of 2.45MiB in 00:05
[ffmpeg] Merging formats into "The Rickety Lady (horror short)-415656502.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:The Rickety Lady (horror short)-415656502.fhls-fastly_skyfire-2343.mp4' -i 'file:The Rickety Lady (horror short)-415656502.fhls-fastly_skyfire-audio-medium-audio.mp4' -c copy -map '0:v:0' -map '1:a:0' 'file:The Rickety Lady (horror short)-415656502.temp.mp4'
ERROR: Conversion failed!
Traceback (most recent call last):
  File "/home/fletch/Sync/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2065, in post_process
    files_to_delete, info = pp.run(info)
  File "/home/fletch/Sync/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/home/fletch/Sync/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: Conversion failed!
```

## Description

I'm unable to download certain videos from Vimeo. It complains about "Conversion failed!" when trying to merge formats. One video for example:

https://vimeo.com/415656502

**Comment by Hrxn** [comment]
Your FFmpeg versions are pretty old. Also, maybe best to also remove avconv as well. You don't need it, a recent FFmpeg is enough.
