### ISSUE TITLE
Cannot download videos from mediaite

### ISSUE THREAD

**Issue by ObjectInSpace** [ytdl-org/youtube-dl#25217]
- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.05.08**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.mediaite.com/politics/were-so-vexxed-don-lemon-says-communities-of-color-are-under-siege-after-ahmaud-arbery-shooting-pandemic/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[generic] were-so-vexxed-don-lemon-says-communities-of-color-are-under-siege-after-ahmaud-arbery-shooting-pandemic: Requesting header
WARNING: Falling back on generic information extractor.
[generic] were-so-vexxed-don-lemon-says-communities-of-color-are-under-siege-after-ahmaud-arbery-shooting-pandemic: Downloading webpage
[generic] were-so-vexxed-don-lemon-says-communities-of-color-are-under-siege-after-ahmaud-arbery-shooting-pandemic: Extracting information
ERROR: Unsupported URL: https://www.mediaite.com/politics/were-so-vexxed-don-lemon-says-communities-of-color-are-under-siege-after-ahmaud-arbery-shooting-pandemic/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\generic.py", line 3370, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.mediaite.com/politics/were-so-vexxed-don-lemon-says-communities-of-color-are-under-siege-after-ahmaud-arbery-shooting-pandemic/

-->

This site worked until a few months ago. It uses jwplatform as the CDN, which has a YDL extractor, but it is not being recognized. The URL for the iframe that loads this video is https://content.jwplatform.com/players/XKsbG4QT-KfS9hzfO.html
Loading this URL into YDL loads the appropriate extractor and successfully downloads the video.
I suspect this issue affects more sites, but did not have one to test.

**Comment by ObjectInSpace** [comment]
Here is the script that displays the video on the page:
  <script>
    (() => {
      window.amJwVideos = window.amJwVideos || [];
      const iframe = document.createElement('iframe');
      const jwBaseUrl = 'https://content.jwplatform.com/players/';
      iframe.setAttribute('allowfullscreen', true);
      iframe.jwUrlWithAds = jwBaseUrl + 'XKsbG4QT-KfS9hzfO.html';
      iframe.jwUrlWithNoAds = jwBaseUrl + 'XKsbG4QT-I23UVzQH.html';
      amJwVideos.push(iframe);
    })();
  </script>

Can the jwplatform extractor handle sites that embed content this way, or will they require their own extractors to be written?

**Comment by ObjectInSpace** [comment]
I also found this pull request, which looks related, but I'm not sure of the status:
https://github.com/ytdl-org/youtube-dl/pull/14828
