### ISSUE TITLE
Twitter video that plays normally on site gives 404 error when attempting to download with 'bestvideo+bestaudio' option.

### ISSUE THREAD

**Issue by Basillica85** [ytdl-org/youtube-dl#25242]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ ./youtube-dl.exe -v -f http-2176 https://twitter.com/WuffFluff/status/1259010650530918402
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'http-2176', 'https://twitter.com/WuffFluff/status/1259010650530918402']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-74324-gecc806a, ffprobe N-74324-gecc806a
[debug] Proxy map: {}
[twitter] 1259010650530918402: Downloading guest token
[twitter] 1259010650530918402: Downloading JSON metadata
[twitter] 1259010650530918402: Downloading m3u8 information
[debug] Invoking downloader on 'https://video.twimg.com/ext_tw_video/1259010206215794689/pu/vid/1280x720/1UxuUP3SBFX3nqEx.mp4?tag=10'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 1926, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

```

## Description

Trying to download this video in http-2176 format results in a 404 error, even though it's listed in the available formats (marked as the best option).
The derived video URL (https://video.twimg.com/ext_tw_video/1259010206215794689/pu/vid/1280x720/1UxuUP3SBFX3nqEx.mp4?tag=10) also gives a 404 error in browser.
Downloading it in hls-2176 format works fine.

```
$ ./youtube-dl.exe -v -F https://twitter.com/WuffFluff/status/1259010650530918402
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://twitter.com/WuffFluff/status/1259010650530918402']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-74324-gecc806a, ffprobe N-74324-gecc806a
[debug] Proxy map: {}
[twitter] 1259010650530918402: Downloading guest token
[twitter] 1259010650530918402: Downloading JSON metadata
[twitter] 1259010650530918402: Downloading m3u8 information
[info] Available formats for 1259010650530918402:
format code  extension  resolution note
hls-256      mp4        480x270     256k , avc1.4d001e, mp4a.40.2
http-256     mp4        480x270     256k
hls-832      mp4        640x360     832k , avc1.4d001f, mp4a.40.2
http-832     mp4        640x360     832k
hls-2176     mp4        1280x720   2176k , avc1.640020, mp4a.40.2
http-2176    mp4        1280x720   2176k  (best)
```

**Comment by remitamine** [comment]
just choose another format.
