### ISSUE TITLE
Signature Extraction Failed for https://www.youtube.com/watch?v=gfkts0u-m6w

### ISSUE THREAD

**Issue by HadManySons** [ytdl-org/youtube-dl#25243]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

PS H:\Users\--redacted--\Desktop> youtube-dl.exe --verbose "https://www.youtube.com/watch?v=gfkts0u-m6w"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=gfkts0u-m6w']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] gfkts0u-m6w: Downloading webpage
[youtube] gfkts0u-m6w: Downloading video info webpage
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {18} signature length 108, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\youtube.py", line 1385, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\youtube.py", line 1262, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/s/player/0acb4375/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/s/player/0acb4375/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\youtube.py", line 1385, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\youtube.py", line 1262, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/s/player/0acb4375/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\youtube.py", line 1385, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\youtube.py", line 1262, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/s/player/0acb4375/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\youtube.py", line 2048, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\youtube.py", line 1395, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\youtube.py", line 1385, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\youtube.py", line 1262, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/s/player/0acb4375/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/s/player/0acb4375/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

Get a signature extraction failed for https://www.youtube.com/watch?v=gfkts0u-m6w. I verified that the url was properly escaped and youtube-dl was updated to latest version.

**Comment by HadManySons** [comment]
I also tried "https://youtu.be/gfkts0u-m6w" and that did not work either.

**Comment by HadManySons** [comment]
It's not outdated though. I updated it 5 minutes before creating this bug report.

**Comment by Hrxn** [comment]
It is outdated...
> [debug] youtube-dl version 2020.01.24

**Comment by HadManySons** [comment]
But I ran an update right before this. That's so weird
