### ISSUE TITLE
it doesnt login on youtube

### ISSUE THREAD

**Issue by userdessa** [ytdl-org/youtube-dl#25265]
that's what i'm getting, "unable to log in", what's happening?

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-o', 'C:\\Users\\ACER-PC\\OneDrive\\Área de Trabalho\\Downloads Temp\\youtube-dl\\já colocado\\%(uploader)s _ %(upload_date)s, %(title)s.%(ext)s', '--ffmpeg-location', 'c:\\users\\acer-pc\\onedrive\\documentos\\downloads\\youtube-dl\\ffmpeg', 'https://youtu.be/gVeioo_xHZU', '-F', '--username', 'PRIVATE', '--password', 'PRIVATE', '--cookies', '\\file.txt']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2019-11-26-59d264b, ffprobe git-2019-11-26-59d264b
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube] gVeioo_xHZU: Downloading webpage
[youtube] gVeioo_xHZU: Downloading embed webpage
[youtube] gVeioo_xHZU: Refetching age-gated info webpage
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\youtube.py", line 2134, in _real_extract
youtube_dl.utils.ExtractorError: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.

**Comment by dstftw** [comment]
Use cookies.
