### ISSUE TITLE
LinkedIn stalls at "Downloading m3u8 information".

### ISSUE THREAD

**Issue by Geremia** [ytdl-org/youtube-dl#25293]
## Checklist
- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.05.08**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'cookies.txt', 'https://www.linkedin.com/learning/learning-moodle-3-7']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.8.2 (CPython) - Linux-5.4.35-x86_64-AMD_Ryzen_Threadripper_2990WX_32-Core_Processor-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[linkedin:learning:course] Downloading JSON metadata
[download] Downloading playlist: Learning Moodle 3.7
[linkedin:learning:course] playlist Learning Moodle 3.7: Collected 36 video ids (downloading 36 of them)
[download] Downloading video 1 of 36
[linkedin:learning] develop-effective-online-instruction-with-moodle: Downloading 360p JSON metadata
[linkedin:learning] develop-effective-online-instruction-with-moodle: Downloading 540p JSON metadata
[linkedin:learning] develop-effective-online-instruction-with-moodle: Downloading 720p JSON metadata
[linkedin:learning] develop-effective-online-instruction-with-moodle: Downloading m3u8 information
```

## Description
LinkedIn stalls at "Downloading m3u8 information". After a few minutes, it will continue, though.

**Comment by wescravn** [comment]
I'm having the same issue
Tyrones-MBP:Downloads twilliams$ youtube-dl --cookies cookies-www-linkedin-com.txt https://www.linkedin.com/learning/adobe-xd-essential-training-design-3 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'cookies-www-linkedin-com.txt', 'https://www.linkedin.com/learning/adobe-xd-essential-training-design-3', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.7.6 (CPython) - Darwin-19.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[linkedin:learning:course] Downloading JSON metadata
[download] Downloading playlist: Adobe XD Essential Training: Design
[linkedin:learning:course] playlist Adobe XD Essential Training: Design: Collected 38 video ids (downloading 38 of them)
[download] Downloading video 1 of 38
[linkedin:learning] take-your-design-to-the-next-level: Downloading 360p JSON metadata
[linkedin:learning] take-your-design-to-the-next-level: Downloading 540p JSON metadata
[linkedin:learning] take-your-design-to-the-next-level: Downloading 720p JSON metadata
[linkedin:learning] take-your-design-to-the-next-level: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://files3.lynda.com/secure/courses/2814153/VBR_MP4h264_main_HD720/2814153_00_01_WX30_Welcome.mp4?Lu9tFJ2nBiiQxwigoXFdwablJ8fnxgEVjkzpwJYUKR5dd0Alzq9NCUXvmP9CpAX9TL1ylm6VG5SVJiW9KiGQLrXU6A2zI7anXuI9WE8Pn0Wtz9FeuugE1sn06ZlZDvc3TT8f_9oeD57Vm96txuUAq8mfeJYRiFWjM13wwMXWOD9dB5qTM_oQMLRpFA'
[download] Destination: Take your design to the next level-2289156.mp4
[download] 100% of 4.50MiB in 00:00
[download] Downloading video 2 of 38
[linkedin:learning] what-is-adobe-xd: Downloading 360p JSON metadata
[linkedin:learning] what-is-adobe-xd: Downloading 540p JSON metadata
[linkedin:learning] what-is-adobe-xd: Downloading 720p JSON metadata
[linkedin:learning] what-is-adobe-xd: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://files3.lynda.com/secure/courses/2814153/VBR_MP4h264_main_HD720/2814153_00_02_XR15_WhatsXD.mp4?Am6foRLrfWi4YPNaKC9yWW_QbRn0Ln3YZoxRCB7d_n4RABRpuKclm1-HYIPnFwgj_p6UHyZrRFQNvvenxxGM4DYCTUJVtxXvJ2p5Gwmr8g77GnYUjhlwzvinI5c6qK9fnvEpiYU9cSGF7nl80gV62_iQhSenW3VNxxCLcDEHf8iWK8Dj4kVqYFC40w'
[download] Destination: What is Adobe XD-2290085.mp4
[download] 100% of 9.90MiB in 00:01
[download] Downloading video 3 of 38
[linkedin:learning] just-one-point-before-you-start: Downloading 360p JSON metadata
[linkedin:learning] just-one-point-before-you-start: Downloading 540p JSON metadata
[linkedin:learning] just-one-point-before-you-start: Downloading 720p JSON metadata
[linkedin:learning] just-one-point-before-you-start: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://files3.lynda.com/secure/courses/2814153/VBR_MP4h264_main_HD720/2814153_00_03_XR15_BeforeWeStart.mp4?3CqIzhM5ECO-Mib5LQvWsGNEutUk60IgHeYUGHQGXUxHDPRxbdmKxtgJEZhdi21_3BQYxlTafBFmo8YFtLHlZxRWMrCDfyQBOu4of-PQMTHpIMvNJ5ZfBnj9UhYcn7zc3iRQfwAInd8YnpobPj-yDe4oIMRWQLzihmpurIOLGTKlbVX4Ml_EUIP98aIAwzgB9g'
[download] Destination: Just one point before you start-2289157.mp4
[download] 100% of 2.55MiB in 00:00
[download] Downloading video 4 of 38
[linkedin:learning] ui-overview-mac: Downloading 360p JSON metadata
[linkedin:learning] ui-overview-mac: Downloading 540p JSON metadata
[linkedin:learning] ui-overview-mac: Downloading 720p JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/linkedin.py", line 127, in _real_extract
    self._sort_formats(formats, ('width', 'height', 'source_preference', 'tbr', 'abr'))
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Tyrones-MBP:Downloads twilliams$
