### ISSUE TITLE
[CWTV] Downloading series is broken

### ISSUE THREAD

**Issue by marium0505** [ytdl-org/youtube-dl#25320]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.05.08**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe -v https://www.cwtv.com/shows/katy-keene
[debug] System config: []
[debug] User config: ['--console-title', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.cwtv.com/shows/katy-keene']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19628
[debug] exe versions: ffmpeg N-90908-g0807a77160
[debug] Proxy map: {}
[generic] katy-keene: Requesting header
[redirect] Following redirect to https://www.cwtv.com/shows/katy-keene/
[generic] katy-keene: Requesting header
WARNING: Falling back on generic information extractor.
[generic] katy-keene: Downloading webpage
[generic] katy-keene: Extracting information
ERROR: Unsupported URL: https://www.cwtv.com/shows/katy-keene/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\generic.py", line 3370, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.cwtv.com/shows/katy-keene/
```

## Description

Hey,

Not sure if this is a broken site issue or a feature request issue, but it isn't possible to download entire series on CW TV. I just get an `Unsupported URL:` error when trying to download using a series page rather than a single episode page.

Downloading using episode links still work (as shown in the log below):
```
youtube-dl.exe -v https://www.cwtv.com/shows/katy-keene/pilot/?play=ae53f26d-c371-478d-8b79-c06942cac5bb
[debug] System config: []
[debug] User config: ['--console-title', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.cwtv.com/shows/katy-keene/pilot/?play=ae53f26d-c371-478d-8b79-c06942cac5bb']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19628
[debug] exe versions: ffmpeg N-90908-g0807a77160
[debug] Proxy map: {}
[CWTV] ae53f26d-c371-478d-8b79-c06942cac5bb: Downloading JSON metadata
[ThePlatform] ae53f26d-c371-478d-8b79-c06942cac5bb: Downloading SMIL data
[ThePlatform] ae53f26d-c371-478d-8b79-c06942cac5bb: Downloading m3u8 information
[ThePlatform] ae53f26d-c371-478d-8b79-c06942cac5bb: Downloading m3u8 information
[ThePlatform] ae53f26d-c371-478d-8b79-c06942cac5bb: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://stream-hls.cwtv.com/nosec/The_CW/317/1013/77641797849/KatyKeene-101-Pilot-T8201001-CW_77643333704_m3u8_video_1920x1080_8000000_primary_audio_eng_8.m3u8'
[download] Destination: Pilot-ae53f26d-c371-478d-8b79-c06942cac5bb.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3650.0 Safari/537.36
" -i "https://stream-hls.cwtv.com/nosec/The_CW/317/1013/77641797849/KatyKeene-101-Pilot-T8201001-CW_77643333704_m3u8_video_1920x1080_8000000_primary_audio_eng_8.m3u8" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:Pilot-ae53f26d-c371-478d-8b79-c06942cac5bb.mp4.part"
ffmpeg version N-90908-g0807a77160 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 18.100 / 56. 18.100
  libavcodec     58. 19.100 / 58. 19.100
  libavformat    58. 13.100 / 58. 13.100
  libavdevice    58.  4.100 / 58.  4.100
  libavfilter     7. 21.100 /  7. 21.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
[AVIOContext @ 0000021287bfa8c0] The "user-agent" option is deprecated: use the "user_agent" option instead
[hls,applehttp @ 00000212876ea300] HLS request for url 'https://stream-hls.cwtv.com/nosec/The_CW/317/1013/77641797849/KatyKeene-101-Pilot-T8201001-CW_77643333704_m3u8_video_1920x1080_8000000_primary_audio_eng_8_00001.ts', offset 0, playlist 0
[hls,applehttp @ 00000212876ea300] Opening 'https://stream-hls.cwtv.com/nosec/The_CW/317/1013/77641797849/KatyKeene-101-Pilot-T8201001-CW_77643333704_m3u8_video_1920x1080_8000000_primary_audio_eng_8_00001.ts' for reading
[https @ 0000021287cea5c0] The "user-agent" option is deprecated: use the "user_agent" option instead
[hls,applehttp @ 00000212876ea300] HLS request for url 'https://stream-hls.cwtv.com/nosec/The_CW/317/1013/77641797849/KatyKeene-101-Pilot-T8201001-CW_77643333704_m3u8_video_1920x1080_8000000_primary_audio_eng_8_00002.ts', offset 0, playlist 0
[hls,applehttp @ 00000212876ea300] Opening 'https://stream-hls.cwtv.com/nosec/The_CW/317/1013/77641797849/KatyKeene-101-Pilot-T8201001-CW_77643333704_m3u8_video_1920x1080_8000000_primary_audio_eng_8_00002.ts' for reading
[https @ 0000021287cee000] The "user-agent" option is deprecated: use the "user_agent" option instead
[h264 @ 00000212884a7640] Reinit context to 1920x1088, pix_fmt: yuv420p
[mpegts @ 0000021287c999c0] parser not found for codec timed_id3, packets or times may be invalid.
Input #0, hls,applehttp, from 'https://stream-hls.cwtv.com/nosec/The_CW/317/1013/77641797849/KatyKeene-101-Pilot-T8201001-CW_77643333704_m3u8_video_1920x1080_8000000_primary_audio_eng_8.m3u8':
  Duration: 00:42:26.09, start: 2.059589, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High), 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(left), 1920x1080 (1920x1088) [SAR 1:1 DAR 16:9], Closed Captions, 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Pilot-ae53f26d-c371-478d-8b79-c06942cac5bb.mp4.part':
  Metadata:
    encoder         : Lavf58.13.100
    Stream #0:0: Video: h264 (High), 1 reference frame (avc1 / 0x31637661), yuv420p(left), 1920x1080 (0x0) [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[hls,applehttp @ 00000212876ea300] HLS request for url 'https://stream-hls.cwtv.com/nosec/The_CW/317/1013/77641797849/KatyKeene-101-Pilot-T8201001-CW_77643333704_m3u8_video_1920x1080_8000000_primary_audio_eng_8_00003.ts', offset 0, playlist 0
[https @ 0000021287cea5c0] Opening 'https://stream-hls.cwtv.com/nosec/The_CW/317/1013/77641797849/KatyKeene-101-Pilot-T8201001-CW_77643333704_m3u8_video_1920x1080_8000000_primary_audio_eng_8_00003.ts' for reading
[hls,applehttp @ 00000212876ea300] HLS request for url 'https://stream-hls.cwtv.com/nosec/The_CW/317/1013/77641797849/KatyKeene-101-Pilot-T8201001-CW_77643333704_m3u8_video_1920x1080_8000000_primary_audio_eng_8_00004.ts', offset 0, playlist 0
[https @ 0000021287cee000] Opening 'https://stream-hls.cwtv.com/nosec/The_CW/317/1013/77641797849/KatyKeene-101-Pilot-T8201001-CW_77643333704_m3u8_video_1920x1080_8000000_primary_audio_eng_8_00004.ts' for reading
frame=  374 fps=103 q=-1.0 Lsize=   15635kB time=00:00:15.55 bitrate=8235.7kbits/s speed=4.29x
video:15391kB audio:231kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.084168%
Input file #0 (https://stream-hls.cwtv.com/nosec/The_CW/317/1013/77641797849/KatyKeene-101-Pilot-T8201001-CW_77643333704_m3u8_video_1920x1080_8000000_primary_audio_eng_8.m3u8):
  Input stream #0:0 (video): 374 packets read (15760192 bytes);
  Input stream #0:1 (audio): 647 packets read (240836 bytes);
  Input stream #0:2 (data): 1 packets read (266 bytes);
  Total: 1022 packets (16001294 bytes) demuxed
Output file #0 (file:Pilot-ae53f26d-c371-478d-8b79-c06942cac5bb.mp4.part):
  Output stream #0:0 (video): 374 packets muxed (15760192 bytes);
  Output stream #0:1 (audio): 647 packets muxed (236307 bytes);
  Total: 1021 packets (15996499 bytes) muxed
Exiting normally, received signal 2.

ERROR: Interrupted by user
```

Would be great being able to download entire series.

**Comment by marium0505** [comment]
@remitamine Link to the issue the issue is a duplicate of? Couldn't find anything matching when I tried to search.

**Comment by marium0505** [comment]
@remitamine  PS: Note that this issue is about CW TV, not CW Seed.

**Comment by remitamine** [comment]
> @remitamine PS: Note that this issue is about CW TV, not CW Seed.

the CWTV extractor covers both CW TV and CW Seed.
