### ISSUE TITLE
AdultSwim.Com Extractor Error

### ISSUE THREAD

**Issue by generallund** [ytdl-org/youtube-dl#25323]
Using latest .exe version on Windows 10 Pro v1909 

C:\Users\Jake\Videos\youtubedl>youtube-dl.exe https://www.adultswim.com/videos/aqua-teen-hunger-force/bus-of-the-undead
[AdultSwim] bus-of-the-undead: Downloading JSON metadata
[AdultSwim] 2967b08c1b9e3b1dbedea20bffc42a83811de126: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('media',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Users\Jake\Videos\youtubedl>youtube-dl.exe -u
Usage: youtube-dl.exe [OPTIONS] URL [URL...]

youtube-dl.exe: error: -u option requires 1 argument

C:\Users\Jake\Videos\youtubedl>youtube-dl.exe https://www.adultswim.com/videos/aqua-teen-hunger-force/bus-of-the-undead
[AdultSwim] bus-of-the-undead: Downloading JSON metadata
[AdultSwim] 2967b08c1b9e3b1dbedea20bffc42a83811de126: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('media',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Users\Jake\Videos\youtubedl>youtube-dl.exe -v https://www.adultswim.com/videos/aqua-teen-hunger-force/bus-of-the-undead
[debug] System config: []
[debug] User config: ['--recode-video', 'mkv']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.adultswim.com/videos/aqua-teen-hunger-force/bus-of-the-undead']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-05-15-b18fd2b, ffprobe git-2020-05-15-b18fd2b
[debug] Proxy map: {}
[AdultSwim] bus-of-the-undead: Downloading JSON metadata
[AdultSwim] 2967b08c1b9e3b1dbedea20bffc42a83811de126: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('media',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\adultswim.py", line 163, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\turner.py", line 200, in _extract_ngtv_info
KeyError: 'media'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\adultswim.py", line 163, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\turner.py", line 200, in _extract_ngtv_info
KeyError: 'media'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 543, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('media',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by generallund** [comment]
This is not a duplicate.
