### ISSUE TITLE
Conversion failed! When downloading webm_dash container

### ISSUE THREAD

**Issue by w10dd** [ytdl-org/youtube-dl#25339]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo[vcodec=vp9]+bestaudio[acodec=opus]', 'https://youtu.be/CmUUdrtAduM', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.8.3 (CPython) - Linux-4.9.186-18339435-aarch64-with-libc
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[youtube] CmUUdrtAduM: Downloading webpage
[youtube] CmUUdrtAduM: Downloading MPD manifest
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1590048553/ei/yeLFXpymLYrj7QTh8az4DQ/ip/95.72.201.30/id/0a651476bb4076e3/source/youtube/requiressl/yes/playback_host/r8---sn-gvnuxaxjvh-n8vr.googlevideo.com/mh/ZE/mm/31%2C26/mn/sn-gvnuxaxjvh-n8vr%2Csn-c0q7lnly/ms/au%2Conr/mv/m/mvi/7/pcm2cms/yes/pl/21/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1425000/vprv/1/mt/1590026853/fvip/5/keepalive/yes/beids/9466585/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIhAICo_sHrOG5-YgXeVJXrtviyFeUZEKclUHPih8mTr9J6AiBhDLUG-SeUhWmkbixVM9Xi2uIXW8WvVcNfT9OOopXUgw%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIgThaCnOBajBDWvMjQdCYjWrWhHAWKVfc8GSEPHliW_RwCIQDudN5Eq2OsExw4XqRCMS9e40r9CqAoz6Dfg64mEkI7Nw%3D%3D'
[dashsegments] Total fragments: 8
[download] Destination: itpedia про перезаливщиков стримов-CmUUdrtAduM.f303.webm

[download]  12.5% of ~2.15KiB at 59.94KiB/s ETA 00:00
[download]  12.5% of ~2.15KiB at 59.94KiB/s ETA 00:00
[download]   0.1% of ~1.94MiB at 313.73KiB/s ETA 04:10
[download]   0.2% of ~1.94MiB at 526.09KiB/s ETA 01:37
[download]   0.4% of ~1.94MiB at 834.59KiB/s ETA 00:44
[download]   0.8% of ~1.94MiB at  1.61MiB/s ETA 00:21
[download]   1.6% of ~1.94MiB at  3.07MiB/s ETA 00:10
[download]   3.2% of ~1.94MiB at  5.66MiB/s ETA 00:05
[download]   6.4% of ~1.94MiB at  8.01MiB/s ETA 00:02
[download]  12.9% of ~1.94MiB at  8.90MiB/s ETA 00:01
[download]  25.0% of ~1.94MiB at  9.56MiB/s ETA 00:00
[download]  25.0% of ~1.94MiB at  9.56MiB/s ETA 00:00
[download]  17.8% of ~2.73MiB at 284.98KiB/s ETA 00:01
[download]  17.9% of ~2.73MiB at 344.20KiB/s ETA 00:01
[download]  18.0% of ~2.73MiB at 752.01KiB/s ETA 00:01
[download]  18.3% of ~2.73MiB at  1.47MiB/s ETA 00:01
[download]  18.9% of ~2.73MiB at  2.79MiB/s ETA 00:01
[download]  20.0% of ~2.73MiB at  5.31MiB/s ETA 00:01
[download]  22.3% of ~2.73MiB at  8.17MiB/s ETA 00:01
[download]  26.9% of ~2.73MiB at  8.74MiB/s ETA 00:00
[download]  36.1% of ~2.73MiB at  9.71MiB/s ETA 00:00
[download]  37.5% of ~2.73MiB at  9.70MiB/s ETA 00:00
[download]  37.5% of ~2.73MiB at  9.70MiB/s ETA 00:00
[download]  34.2% of ~2.99MiB at 297.32KiB/s ETA 00:00
[download]  34.3% of ~2.99MiB at 589.56KiB/s ETA 00:00
[download]  34.4% of ~2.99MiB at 753.50KiB/s ETA 00:00
[download]  34.7% of ~2.99MiB at  1.46MiB/s ETA 00:00
[download]  35.2% of ~2.99MiB at  2.82MiB/s ETA 00:00
[download]  36.3% of ~2.99MiB at  5.30MiB/s ETA 00:00
[download]  38.3% of ~2.99MiB at  7.91MiB/s ETA 00:00
[download]  42.5% of ~2.99MiB at  8.96MiB/s ETA 00:00
[download]  50.0% of ~2.99MiB at 10.03MiB/s ETA 00:00
[download]  50.0% of ~2.99MiB at 10.03MiB/s ETA 00:00
[download]  47.4% of ~3.15MiB at 307.48KiB/s ETA 00:00
[download]  47.5% of ~3.15MiB at 705.48KiB/s ETA 00:00
[download]  47.6% of ~3.15MiB at  1.42MiB/s ETA 00:00
[download]  47.9% of ~3.15MiB at  2.70MiB/s ETA 00:00
[download]  48.4% of ~3.15MiB at  4.93MiB/s ETA 00:00
[download]  49.4% of ~3.15MiB at  4.38MiB/s ETA 00:00
[download]  51.4% of ~3.15MiB at  6.69MiB/s ETA 00:00
[download]  55.3% of ~3.15MiB at  7.51MiB/s ETA 00:00
[download]  62.5% of ~3.15MiB at  9.08MiB/s ETA 00:00
[download]  62.5% of ~3.15MiB at  9.08MiB/s ETA 00:00
[download]  59.7% of ~3.30MiB at 120.54KiB/s ETA 00:00
[download]  59.8% of ~3.30MiB at 305.44KiB/s ETA 00:00
[download]  59.9% of ~3.30MiB at 673.55KiB/s ETA 00:00
[download]  60.1% of ~3.30MiB at  1.33MiB/s ETA 00:00
[download]  60.6% of ~3.30MiB at  2.30MiB/s ETA 00:00
[download]  61.6% of ~3.30MiB at  3.95MiB/s ETA 00:00
[download]  63.5% of ~3.30MiB at  7.53MiB/s ETA 00:00
[download]  67.2% of ~3.30MiB at  9.80MiB/s ETA 00:00
[download]  74.8% of ~3.30MiB at  9.82MiB/s ETA 00:00
[download]  75.0% of ~3.30MiB at  9.49MiB/s ETA 00:00
[download]  75.0% of ~3.30MiB at  9.49MiB/s ETA 00:00
[download]  69.8% of ~3.55MiB at 116.99KiB/s ETA 00:00
[download]  69.9% of ~3.55MiB at 316.97KiB/s ETA 00:00
[download]  70.0% of ~3.55MiB at 696.83KiB/s ETA 00:00
[download]  70.2% of ~3.55MiB at  1.25MiB/s ETA 00:00
[download]  70.7% of ~3.55MiB at  2.40MiB/s ETA 00:00
[download]  71.6% of ~3.55MiB at  3.80MiB/s ETA 00:00
[download]  73.3% of ~3.55MiB at  6.23MiB/s ETA 00:00
[download]  76.8% of ~3.55MiB at  8.25MiB/s ETA 00:00
[download]  83.9% of ~3.55MiB at  9.63MiB/s ETA 00:00
[download]  87.5% of ~3.55MiB at 10.06MiB/s ETA 00:00
[download]  87.5% of ~3.55MiB at 10.06MiB/s ETA 00:00
[download]  95.5% of ~3.25MiB at 106.24KiB/s ETA 00:00
[download]  95.5% of ~3.25MiB at 287.96KiB/s ETA 00:00
[download]  95.6% of ~3.25MiB at 635.29KiB/s ETA 00:00
[download]  95.9% of ~3.25MiB at  1.25MiB/s ETA 00:00
[download]  96.4% of ~3.25MiB at  2.43MiB/s ETA 00:00
[download]  97.3% of ~3.25MiB at  3.65MiB/s ETA 00:00
[download]  99.2% of ~3.25MiB at  6.46MiB/s ETA 00:00
[download] 100.0% of ~3.25MiB at  7.08MiB/s ETA 00:00
[download] 100.0% of ~3.25MiB at  7.08MiB/s ETA 00:00
[download] 100% of 3.25MiB in 00:01
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1590048553/ei/yeLFXpymLYrj7QTh8az4DQ/ip/95.72.201.30/id/0a651476bb4076e3/source/youtube/requiressl/yes/playback_host/r8---sn-gvnuxaxjvh-n8vr.googlevideo.com/mh/ZE/mm/31%2C26/mn/sn-gvnuxaxjvh-n8vr%2Csn-c0q7lnly/ms/au%2Conr/mv/m/mvi/7/pcm2cms/yes/pl/21/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1425000/vprv/1/mt/1590026853/fvip/5/keepalive/yes/beids/9466585/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIhAICo_sHrOG5-YgXeVJXrtviyFeUZEKclUHPih8mTr9J6AiBhDLUG-SeUhWmkbixVM9Xi2uIXW8WvVcNfT9OOopXUgw%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIgThaCnOBajBDWvMjQdCYjWrWhHAWKVfc8GSEPHliW_RwCIQDudN5Eq2OsExw4XqRCMS9e40r9CqAoz6Dfg64mEkI7Nw%3D%3D'
[dashsegments] Total fragments: 5
[download] Destination: itpedia про перезаливщиков стримов-CmUUdrtAduM.f251.webm

[download]  20.0% of ~1.26KiB at 82.69KiB/s ETA 00:00
[download]  20.0% of ~1.26KiB at 82.69KiB/s ETA 00:00
[download]   0.3% of ~376.58KiB at 124.16KiB/s ETA 00:43
[download]   0.9% of ~376.58KiB at 311.93KiB/s ETA 00:16
[download]   1.9% of ~376.58KiB at 684.43KiB/s ETA 00:07
[download]   4.1% of ~376.58KiB at  1.34MiB/s ETA 00:03
[download]   8.3% of ~376.58KiB at  2.60MiB/s ETA 00:01
[download]  16.8% of ~376.58KiB at  4.57MiB/s ETA 00:00
[download]  33.8% of ~376.58KiB at  6.62MiB/s ETA 00:00
[download]  40.0% of ~376.58KiB at  7.23MiB/s ETA 00:00
[download]  40.0% of ~376.58KiB at  7.23MiB/s ETA 00:00
[download]  30.8% of ~492.00KiB at 148.97KiB/s ETA 00:00
[download]  31.2% of ~492.00KiB at 343.38KiB/s ETA 00:00
[download]  32.0% of ~492.00KiB at 754.70KiB/s ETA 00:00
[download]  33.7% of ~492.00KiB at  1.43MiB/s ETA 00:00
[download]  36.9% of ~492.00KiB at  2.78MiB/s ETA 00:00
[download]  43.4% of ~492.00KiB at  5.12MiB/s ETA 00:00
[download]  56.4% of ~492.00KiB at  6.24MiB/s ETA 00:00
[download]  60.0% of ~492.00KiB at  6.78MiB/s ETA 00:00
[download]  60.0% of ~492.00KiB at  6.78MiB/s ETA 00:00
[download]  53.9% of ~549.49KiB at 227.60KiB/s ETA 00:00
[download]  54.3% of ~549.49KiB at 560.04KiB/s ETA 00:00
[download]  55.0% of ~549.49KiB at  1.10MiB/s ETA 00:00
[download]  56.5% of ~549.49KiB at  2.14MiB/s ETA 00:00
[download]  59.4% of ~549.49KiB at  2.77MiB/s ETA 00:00
[download]  65.2% of ~549.49KiB at  5.22MiB/s ETA 00:00
[download]  76.8% of ~549.49KiB at  6.53MiB/s ETA 00:00
[download]  80.0% of ~549.49KiB at  6.73MiB/s ETA 00:00
[download]  80.0% of ~549.49KiB at  6.73MiB/s ETA 00:00
[download]  90.4% of ~487.53KiB at 153.72KiB/s ETA 00:00
[download]  90.8% of ~487.53KiB at 409.92KiB/s ETA 00:00
[download]  91.6% of ~487.53KiB at 885.49KiB/s ETA 00:00
[download]  93.2% of ~487.53KiB at  1.72MiB/s ETA 00:00
[download]  96.5% of ~487.53KiB at  3.30MiB/s ETA 00:00
[download] 100.0% of ~487.53KiB at  4.48MiB/s ETA 00:00
[download] 100.0% of ~487.53KiB at  4.48MiB/s ETA 00:00
[download] 100% of 487.53KiB in 00:00
[ffmpeg] Merging formats into "itpedia про перезаливщиков стримов-CmUUdrtAduM.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:itpedia про перезаливщиков стримов-CmUUdrtAduM.f303.webm' -i 'file:itpedia про перезаливщиков стримов-CmUUdrtAduM.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:itpedia про перезаливщиков стримов-CmUUdrtAduM.temp.webm'
ERROR: Conversion failed!
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2065, in post_process
    files_to_delete, info = pp.run(info)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```
# List formats

```
[youtube] CmUUdrtAduM: Downloading webpage
[youtube] CmUUdrtAduM: Downloading MPD manifest
[info] Available formats for CmUUdrtAduM:
format code  extension  resolution note
139          m4a        audio only DASH audio   49k , m4a_dash container, mp4a.40.5@ 48k (22050Hz)
251          webm       audio only DASH audio  124k , webm_dash container, opus @160k (48000Hz)
140          m4a        audio only DASH audio  130k , m4a_dash container, mp4a.40.2@128k (44100Hz)
278          webm       256x144    DASH video   95k , webm_dash container, vp9, 30fps, video only
160          mp4        256x144    DASH video  108k , mp4_dash container, avc1.4d400b, 30fps, video only
242          webm       426x240    DASH video  220k , webm_dash container, vp9, 30fps, video only
134          mp4        640x360    DASH video  233k , mp4_dash container, avc1.4d401e, 30fps, video only
133          mp4        426x240    DASH video  242k , mp4_dash container, avc1.4d400c, 30fps, video only
243          webm       640x360    DASH video  405k , webm_dash container, vp9, 30fps, video only
244          webm       854x480    DASH video  752k , webm_dash container, vp9, 30fps, video only
135          mp4        854x480    DASH video 1155k , mp4_dash container, avc1.4d4014, 30fps, video only
247          webm       1280x720   DASH video 1505k , webm_dash container, vp9, 30fps, video only
136          mp4        1280x720   DASH video 2310k , mp4_dash container, avc1.4d4016, 30fps, video only
302          webm       1280x720   DASH video 2646k , webm_dash container, vp9, 60fps, video only
248          webm       1920x1080  DASH video 2646k , webm_dash container, vp9, 30fps, video only
298          mp4        1280x720   DASH video 3465k , mp4_dash container, avc1.4d4016, 60fps, video only
137          mp4        1920x1080  DASH video 4331k , mp4_dash container, avc1.64001e, 30fps, video only
303          webm       1920x1080  DASH video 4410k , webm_dash container, vp9, 60fps, video only
299          mp4        1920x1080  DASH video 5775k , mp4_dash container, avc1.64001e, 60fps, video only
18           mp4        640x360    360p  209k , avc1.42001E, 30fps, mp4a.40.2@ 96k (44100Hz), 847.40KiB
22           mp4        1280x720   720p  515k , avc1.64001F, 30fps, mp4a.40.2@192k (44100Hz) (best)
```

# ffmpeg log
```
Conversion failed!
$ ffmpeg -y -loglevel repeat+info -i 'file:itpedia про перезаливщиков стримов-CmUUdrtAduM.f303.webm' -i 'file:itpedia про перезаливщиков стримов-CmUUdrtAduM.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:itpedia про перезаливщиков стримов-CmUUdrtAduM.temp.webm' > ffmpeg.txt
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
  configuration: --arch=aarch64 --as=aarch64-linux-android-clang --cc=aarch64-linux-android-clang --cxx=aarch64-linux-android-clang++ --cross-prefix=aarch64-linux-android- --disable-indevs --disable-outdevs --enable-indev=lavfi --disable-static --disable-symver --enable-cross-compile --enable-gnutls --enable-gpl --enable-libass --enable-libdav1d --enable-libmp3lame --enable-libfreetype --enable-libvorbis --enable-libopus --enable-libx264 --enable-libx265 --enable-libxvid --enable-libvpx --enable-shared --enable-libsoxr --enable-libvidstab --enable-libwebp --prefix=/data/data/com.termux/files/usr --target-os=android --extra-libs=-landroid-glob --enable-neon
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, matroska,webm, from 'file:itpedia про перезаливщиков стримов-CmUUdrtAduM.f303.webm':
  Metadata:
    encoder         : google/video-file
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 7
                    : Segment-Durations-Ms: 5333(r=5),1133,
                    :
                    :
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1920x1080, SAR 1:1 DAR 16:9, 60 fps, 60 tbr, 1k tbn, 1k tbc (default)
Input #1, matroska,webm, from 'file:itpedia про перезаливщиков стримов-CmUUdrtAduM.f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:00:33.16, start: -0.007000, bitrate: 120 kb/s
    Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Output #0, webm, to 'file:itpedia про перезаливщиков стримов-CmUUdrtAduM.temp.webm':
  Metadata:
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 7
                    : Segment-Durations-Ms: 5333(r=5),1133,
                    :
                    :
    encoder         : Lavf58.29.100
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 60 fps, 60 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[webm @ 0x7cbaa3ac00] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 5350 >= 5333
av_interleaved_write_frame(): Invalid argument
frame=  323 fps=0.0 q=-1.0 Lsize=     579kB time=00:00:05.36 bitrate= 885.0kbits/s speed= 445x
video:532kB audio:81kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
```
On PC the same error. It is actually a YouTube problem, giving broken webm? Or it's YouTube-dl incorrectly joining DASH parts? I've seen the same exact error that was ignored, on other service  https://github.com/ytdl-org/youtube-dl/issues/16781#issuecomment-399200974

**Comment by w10dd** [comment]
If it definitely YouTube's fault, please completely delete this issue, I'm accidentally posted this from my alt account, I can resend it from my main account if needed

**Comment by w10dd** [comment]
@dstftw Please delete this, it is youtube's fault

**Comment by w10dd** [comment]
@dstftw delete this issue
