### ISSUE TITLE
Downloading playlist failed after 6th video (6 out of 126 videos)

### ISSUE THREAD

**Issue by gwpl** [ytdl-org/youtube-dl#25342]
## Checklist

- [x] I'm reporting a problem with downloading playlist
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl --version
2020.05.08

$ youtube-dl -f mp4 --verbose 'https://www.youtube.com/playlist?list=PL591B8E48C736AF17'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'mp4', '--verbose', 'https://www.youtube.com/playlist?list=PL591B8E48C736AF17']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.8.2 (CPython) - Linux-5.6.12-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PL591B8E48C736AF17: Downloading webpage
[download] Downloading playlist: OSHO Lectures
[youtube:playlist] PL591B8E48C736AF17: Downloading page #1
[youtube:playlist] playlist OSHO Lectures: Downloading 126 videos
[download] Downloading video 1 of 126
[youtube] otGQqO2TYMI: Downloading webpage
[debug] Invoking downloader on 'https://r1---sn-pf5t-1gie.googlevideo.com/videoplayback?expire=1590081948&ei=PGXGXqeWC4yW1wKj7ZKAAg&ip=2001%3A8e0%3A2000%3Aba00%3Ab102%3A1f43%3Af812%3Ad577&id=o-AAvfEyopqFDLGMlz2ZgyUb0wwTJmICv6A9NMAA0GBB35&itag=18&source=youtube&requiressl=yes&mh=Tk&mm=31%2C29&mn=sn-pf5t-1gie%2Csn-1gieen7e&ms=au%2Crdu&mv=m&mvi=0&pcm2cms=yes&pl=32&initcwndbps=1188750&vprv=1&mime=video%2Fmp4&gir=yes&clen=31133396&ratebypass=yes&dur=619.949&lmt=1540406232344348&mt=1590060266&fvip=5&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALtA7dsrL1oTzzHXoZSRnRYgPRKx2sSP6-TKeAN_PvTOAiEA8J5YO6XsBNUUrokDXMR5ZJq2PUEFnC2gxYtLhpm8ik0%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAPDPAscoUY2NOq1tlNIuqX52LiljhnGzQpjbwi7SzM4cAiA6QynhMwlXpwWZMrTjD2akNWclJm3Kc0EVMyZxfEDNMQ%3D%3D'
[download] Absolutely Free to Be Funny-otGQqO2TYMI.mp4 has already been downloaded
[download] 100% of 29.69MiB
[download] Downloading video 2 of 126
[youtube] 6D7rWLzloOI: Downloading webpage
[debug] Invoking downloader on 'https://r2---sn-pf5t-1gie.googlevideo.com/videoplayback?expire=1590081948&ei=PGXGXo2VK8Le7gOe_a3wBQ&ip=2001%3A8e0%3A2000%3Aba00%3Ab102%3A1f43%3Af812%3Ad577&id=o-AOkHEneGB-lcvQcAWfZfnT0keulXJR-WAHthnxuQFGQ2&itag=18&source=youtube&requiressl=yes&mh=5g&mm=31%2C29&mn=sn-pf5t-1gie%2Csn-1gi7znes&ms=au%2Crdu&mv=m&mvi=1&pl=32&gcr=ch&initcwndbps=1188750&vprv=1&mime=video%2Fmp4&gir=yes&clen=18645689&ratebypass=yes&dur=407.533&lmt=1540022440252795&mt=1590060266&fvip=4&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAPcVe4y8rtmWuxJc0pOKlLJtupYqICUyny9mxP_JhcquAiEA9lPNnP-F136QwMuhQoNUSNBeG8jobmOD-mFlRMwnmsc%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgAlOqzsgkiEEcg6YWpCUBW7eligJtA4HaHtvSpzWKZFYCIQCvmpnCy1uwsWqYUgG13GcBa7TqwVtpsPOqhGq3e7_hUQ%3D%3D'
[download] OSHO - Strange Consequences _ Spiritually Incorrect ®-6D7rWLzloOI.mp4 has already been downloaded
[download] 100% of 17.78MiB
[download] Downloading video 3 of 126
[youtube] 8LfUvi1bof8: Downloading webpage
[debug] Invoking downloader on 'https://r1---sn-pf5t-1gie.googlevideo.com/videoplayback?expire=1590081949&ei=PWXGXsKjDdrbgQfp_5DwAg&ip=2001%3A8e0%3A2000%3Aba00%3Ab102%3A1f43%3Af812%3Ad577&id=o-AJRPlA6-q2yqHM89UW7YF8frxlVvSUZytEOrEk_E-EGJ&itag=18&source=youtube&requiressl=yes&mh=Tr&mm=31%2C29&mn=sn-pf5t-1gie%2Csn-1gi7znes&ms=au%2Crdu&mv=m&mvi=0&pl=32&initcwndbps=1188750&vprv=1&mime=video%2Fmp4&gir=yes&clen=35572237&ratebypass=yes&dur=603.138&lmt=1540012345564341&mt=1590060266&fvip=4&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgLredsCP2zcq6q8-b0WKsjh0vD_MNGhuYQrJtEjfNBRoCIQCel1XMt8A7pqzYd-MJXye4MXRFMxWJSD1pKWks0JZ3yw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKNVy3UvhLto5sKma2fq_sW_wxg9tkxBTRzp-5FEU0AfAiEAvGGYymRH9OoK3gp5zEP0MKcPNwc6gVSf9JE9utmvlzQ%3D'
[download] Being In Love-8LfUvi1bof8.mp4 has already been downloaded
[download] 100% of 33.92MiB
[download] Downloading video 4 of 126
[youtube] kK4aVB1uPOg: Downloading webpage
[debug] Invoking downloader on 'https://r1---sn-pf5t-1gie.googlevideo.com/videoplayback?expire=1590081949&ei=PWXGXsynLdrbgQeEm5ygCQ&ip=2001%3A8e0%3A2000%3Aba00%3Ab102%3A1f43%3Af812%3Ad577&id=o-AOzMyCwpoy9yPXJLUTQGwT96wtCjIMEU2vj4C7tkrqGF&itag=18&source=youtube&requiressl=yes&mh=VH&mm=31%2C29&mn=sn-pf5t-1gie%2Csn-1gi7znes&ms=au%2Crdu&mv=m&mvi=0&pcm2cms=yes&pl=32&initcwndbps=1188750&vprv=1&mime=video%2Fmp4&gir=yes&clen=28983136&ratebypass=yes&dur=450.885&lmt=1570716313024139&mt=1590060266&fvip=3&c=WEB&txp=1311222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAJx2smmw0vVrqTfWy2pDPWbdIYX83NPuouGAxFrHBnhFAiA3nRtx-CbM3GRSwc_NvtDPpTXKsccRUB7E8LoCc-3SFQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAOZKDwN1QSjT9W2Gox4SNq_NzwA9snIm5PvIGaaqXR9NAiAEw7WFsFAYPL_qeKUe9tHwhNu5NerZ5JQnwyN4CKcJMQ%3D%3D'
[download] OSHO -  My Way Of Life Is Not a  Philosophy-kK4aVB1uPOg.mp4 has already been downloaded
[download] 100% of 27.64MiB
[download] Downloading video 5 of 126
[youtube] 5ocbZhRQS9I: Downloading webpage
[debug] Invoking downloader on 'https://r2---sn-pf5t-1gie.googlevideo.com/videoplayback?expire=1590081950&ei=PmXGXoSeDo2g4gHp57eoBg&ip=2001%3A8e0%3A2000%3Aba00%3Ab102%3A1f43%3Af812%3Ad577&id=o-AM6IsABaMMwqWLwX21Y9IMWQrAklRtCGyHfRNunFH7h7&itag=18&source=youtube&requiressl=yes&mh=yS&mm=31%2C29&mn=sn-pf5t-1gie%2Csn-1gi7znes&ms=au%2Crdu&mv=m&mvi=1&pl=32&initcwndbps=1188750&vprv=1&mime=video%2Fmp4&gir=yes&clen=27354294&ratebypass=yes&dur=623.989&lmt=1531854465610000&mt=1590060266&fvip=3&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgdMyFG-XX0wsboQ4R5uVL2hAYbrSXl5oncpcRPZnBGFgCIQC_4DkL2oW-ty_oqnImv2ijiA1l0OdVvepvyWFB8nvAwA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAPYz6g6Ymwl7KoShHgpx86oz22acbOy4jKs8UdF8VvSdAiEAssvzNY2i4I_ApajFA_Uw6GA7CYK-yjMRkbyXi-nbtvA%3D'
[download] OSHO - Marriage and Children-5ocbZhRQS9I.mp4 has already been downloaded
[download] 100% of 26.09MiB
[download] Downloading video 6 of 126
[youtube] npnN9htA1FE: Downloading webpage
[youtube] npnN9htA1FE: Downloading embed webpage
[youtube] npnN9htA1FE: Refetching age-gated info webpage
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 2134, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.
```

Also fails without `-f mp4` flag.

## Description

Fails after downloading 6 out of 126 videos from playlists and asks me to file this report.

**Comment by dstftw** [comment]
>If the owner of this video has granted you access, please sign in.
       This video is private.

**Comment by gwpl** [comment]
That's not correct.

Bug seems to me , like youtube-dl giving up on first private video.

Whilte playlist may consist both : public, private , maybe some deleted or not available in given country videos.

Therefore, IMHO youtube-dl should go over whole playlist and try to download whatever it can.

**Comment by dstftw** [comment]
This is expected behavior. You must skip error with `-i` on your own.
