### ISSUE TITLE
robcosman.com/vimeo woodworking videos embedded on Vimeo - mixed results

### ISSUE THREAD

**Issue by dentedbread** [ytdl-org/youtube-dl#25379]
- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

MacBook Pro (Retina, 15-inch, Mid 2014) macOS High Sierra 10.13.6 (17G65)
Using iTerm 2 Build 3.3.6, cygwin/ssh to CentOS 7; results consistent across all execution methods (all same version of youtube-dl)

First: youtube-dl is a fabulous tool and I am grateful to all of the volunteers who have created it.

I have a paid subscription to Rob Cosman's woodworking videos.  I would like to download them to watch when I am working away from home, as often I am without an internet connection even close to supporting streaming video.

Some URLs:
- Rob Cosman's main site https://robcosman.com/
- List of all freebie videos https://robcosman.com/blogs/membership
- Project freebie video "Lumber Rack" https://robcosman.com/blogs/membership/lumber-rack
- List of all paid-for videos (subscription required) https://robcosman.com/apps/downloads/orders/3143823786050
- Project paid-for video "Lumber Rack" https://robcosman.com/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/collections/21828

The freebie project videos download fine but the paid-for project videos do not.

So this command to download the freebie Lumber Rack video works as expected:
`youtube-dl https://robcosman.com/blogs/membership/lumber-rack`

This command to download the paid-for project series for the same Lumber Rack:
`youtube-dl -v https://robcosman.com/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/collections/21828 --cookies cookies.txt`
or
`youtube-dl -v https://robcosman.com/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/collections/21828 --username username --password password`

Results in:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://robcosman.com/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/collections/21828', u'--cookies', u'cookies.txt']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 2.7.17 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 21828: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 21828: Downloading webpage
[generic] 21828: Extracting information
ERROR: Unsupported URL: https://robcosman.com/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/collections/21828
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2378, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2562, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in _XML
    parser.feed(text)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3370, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://robcosman.com/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/collections/21828
```
So the downloads work on the robcosman.com domain for one style of URLs (the freebies) but not the others (paid-for).

I was hoping to download the video archive before I next go away for work, which will be soon.

Happy to provide account credentials and any other information.

**Comment by dentedbread** [comment]
So, attached is the source of one of the paid-for pages on robcosman.com where the videos are available and playable.
![image](https://user-images.githubusercontent.com/65827320/82834225-62fadc00-9eb8-11ea-89f2-af285fdcae04.png)

This is (I think) the relevant source:
```
    <div class="sky-pilot-videos">
      <div id="sky-pilot-video-player-wrapper" class="sky-pilot-video-player-wrapper">
        <div id='sky-pilot-embed-103542' class='sky-pilot-embed' data-vimeo-defer data-vimeo-url="https://vimeo.com/310901196" data-video-id="103542" data-item-id="36884745" data-order-id="24472804" data-vimeo-id="310901196" data-vimeo-width="640" data-vimeo-maxwidth="720" data-vimeo-maxheight="480">
</div>


      </div>

      <div class="sky-pilot-video-list match-video-player-height" data-height-restriction-breakpoint="768" data-autoselect-next-video=true data-autoplay-next-video=true>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103542" class="sky-pilot-video-link active" data-video-id='103542' data-video-vimeo-url="https://vimeo.com/310901196" data-item-id="36884745" data-video-vimeo-id="310901196" data-order-id="24472804" data-video-index="0">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/310901196">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 1
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103568" class="sky-pilot-video-link " data-video-id='103568' data-video-vimeo-url="https://vimeo.com/311230074" data-item-id="36884745" data-video-vimeo-id="311230074" data-order-id="24472804" data-video-index="1">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/311230074">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 2
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103569" class="sky-pilot-video-link " data-video-id='103569' data-video-vimeo-url="https://vimeo.com/311470612" data-item-id="36884745" data-video-vimeo-id="311470612" data-order-id="24472804" data-video-index="2">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/311470612">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 3
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103570" class="sky-pilot-video-link " data-video-id='103570' data-video-vimeo-url="https://vimeo.com/312095873" data-item-id="36884745" data-video-vimeo-id="312095873" data-order-id="24472804" data-video-index="3">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/312095873">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 4
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103571" class="sky-pilot-video-link " data-video-id='103571' data-video-vimeo-url="https://vimeo.com/313090499" data-item-id="36884745" data-video-vimeo-id="313090499" data-order-id="24472804" data-video-index="4">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/313090499">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 5
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103572" class="sky-pilot-video-link " data-video-id='103572' data-video-vimeo-url="https://vimeo.com/313588222" data-item-id="36884745" data-video-vimeo-id="313588222" data-order-id="24472804" data-video-index="5">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/313588222">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 6
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103573" class="sky-pilot-video-link " data-video-id='103573' data-video-vimeo-url="https://vimeo.com/313915211" data-item-id="36884745" data-video-vimeo-id="313915211" data-order-id="24472804" data-video-index="6">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/313915211">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 7
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103574" class="sky-pilot-video-link " data-video-id='103574' data-video-vimeo-url="https://vimeo.com/314527687" data-item-id="36884745" data-video-vimeo-id="314527687" data-order-id="24472804" data-video-index="7">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/314527687">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 8
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103575" class="sky-pilot-video-link " data-video-id='103575' data-video-vimeo-url="https://vimeo.com/314558180" data-item-id="36884745" data-video-vimeo-id="314558180" data-order-id="24472804" data-video-index="8">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/314558180">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 9
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103576" class="sky-pilot-video-link " data-video-id='103576' data-video-vimeo-url="https://vimeo.com/315623850" data-item-id="36884745" data-video-vimeo-id="315623850" data-order-id="24472804" data-video-index="9">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/315623850">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 10
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103577" class="sky-pilot-video-link " data-video-id='103577' data-video-vimeo-url="https://vimeo.com/316013767" data-item-id="36884745" data-video-vimeo-id="316013767" data-order-id="24472804" data-video-index="10">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/316013767">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 11
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103578" class="sky-pilot-video-link " data-video-id='103578' data-video-vimeo-url="https://vimeo.com/316808658" data-item-id="36884745" data-video-vimeo-id="316808658" data-order-id="24472804" data-video-index="11">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/316808658">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 12
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103579" class="sky-pilot-video-link " data-video-id='103579' data-video-vimeo-url="https://vimeo.com/317152540" data-item-id="36884745" data-video-vimeo-id="317152540" data-order-id="24472804" data-video-index="12">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/317152540">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 13
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103580" class="sky-pilot-video-link " data-video-id='103580' data-video-vimeo-url="https://vimeo.com/318654762" data-item-id="36884745" data-video-vimeo-id="318654762" data-order-id="24472804" data-video-index="13">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/318654762">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 14
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103581" class="sky-pilot-video-link " data-video-id='103581' data-video-vimeo-url="https://vimeo.com/318911423/9fe0cd0679" data-item-id="36884745" data-video-vimeo-id="318911423" data-order-id="24472804" data-video-index="14">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/318911423/9fe0cd0679">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 15
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103582" class="sky-pilot-video-link " data-video-id='103582' data-video-vimeo-url="https://vimeo.com/324417324" data-item-id="36884745" data-video-vimeo-id="324417324" data-order-id="24472804" data-video-index="15">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/324417324">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 16
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103583" class="sky-pilot-video-link " data-video-id='103583' data-video-vimeo-url="https://vimeo.com/325179267" data-item-id="36884745" data-video-vimeo-id="325179267" data-order-id="24472804" data-video-index="16">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/325179267">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 17
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103584" class="sky-pilot-video-link " data-video-id='103584' data-video-vimeo-url="https://vimeo.com/325764983" data-item-id="36884745" data-video-vimeo-id="325764983" data-order-id="24472804" data-video-index="17">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/325764983">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 18
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103585" class="sky-pilot-video-link " data-video-id='103585' data-video-vimeo-url="https://vimeo.com/326032112" data-item-id="36884745" data-video-vimeo-id="326032112" data-order-id="24472804" data-video-index="18">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/326032112">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 19
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103586" class="sky-pilot-video-link " data-video-id='103586' data-video-vimeo-url="https://vimeo.com/326668723" data-item-id="36884745" data-video-vimeo-id="326668723" data-order-id="24472804" data-video-index="19">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/326668723">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 20
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103587" class="sky-pilot-video-link " data-video-id='103587' data-video-vimeo-url="https://vimeo.com/327161290" data-item-id="36884745" data-video-vimeo-id="327161290" data-order-id="24472804" data-video-index="20">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/327161290">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 21
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103588" class="sky-pilot-video-link " data-video-id='103588' data-video-vimeo-url="https://vimeo.com/327545442" data-item-id="36884745" data-video-vimeo-id="327545442" data-order-id="24472804" data-video-index="21">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/327545442">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 22
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103589" class="sky-pilot-video-link " data-video-id='103589' data-video-vimeo-url="https://vimeo.com/327922661" data-item-id="36884745" data-video-vimeo-id="327922661" data-order-id="24472804" data-video-index="22">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/327922661">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 23
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103590" class="sky-pilot-video-link " data-video-id='103590' data-video-vimeo-url="https://vimeo.com/328460870" data-item-id="36884745" data-video-vimeo-id="328460870" data-order-id="24472804" data-video-index="23">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/328460870">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 24
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103591" class="sky-pilot-video-link " data-video-id='103591' data-video-vimeo-url="https://vimeo.com/328937585" data-item-id="36884745" data-video-vimeo-id="328937585" data-order-id="24472804" data-video-index="24">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/328937585">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 25
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103592" class="sky-pilot-video-link " data-video-id='103592' data-video-vimeo-url="https://vimeo.com/329472178" data-item-id="36884745" data-video-vimeo-id="329472178" data-order-id="24472804" data-video-index="25">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/329472178">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 26
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103593" class="sky-pilot-video-link " data-video-id='103593' data-video-vimeo-url="https://vimeo.com/330011311" data-item-id="36884745" data-video-vimeo-id="330011311" data-order-id="24472804" data-video-index="26">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/330011311">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 27
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103594" class="sky-pilot-video-link " data-video-id='103594' data-video-vimeo-url="https://vimeo.com/330199225" data-item-id="36884745" data-video-vimeo-id="330199225" data-order-id="24472804" data-video-index="27">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/330199225">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 28
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103595" class="sky-pilot-video-link " data-video-id='103595' data-video-vimeo-url="https://vimeo.com/331335177" data-item-id="36884745" data-video-vimeo-id="331335177" data-order-id="24472804" data-video-index="28">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/331335177">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 29
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103596" class="sky-pilot-video-link " data-video-id='103596' data-video-vimeo-url="https://vimeo.com/331348425" data-item-id="36884745" data-video-vimeo-id="331348425" data-order-id="24472804" data-video-index="29">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/331348425">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 30
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103597" class="sky-pilot-video-link " data-video-id='103597' data-video-vimeo-url="https://vimeo.com/331778058" data-item-id="36884745" data-video-vimeo-id="331778058" data-order-id="24472804" data-video-index="30">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/331778058">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 31
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103598" class="sky-pilot-video-link " data-video-id='103598' data-video-vimeo-url="https://vimeo.com/332218068" data-item-id="36884745" data-video-vimeo-id="332218068" data-order-id="24472804" data-video-index="31">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/332218068">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 32
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103599" class="sky-pilot-video-link " data-video-id='103599' data-video-vimeo-url="https://vimeo.com/337644955" data-item-id="36884745" data-video-vimeo-id="337644955" data-order-id="24472804" data-video-index="32">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/337644955">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 33
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103600" class="sky-pilot-video-link " data-video-id='103600' data-video-vimeo-url="https://vimeo.com/338373286" data-item-id="36884745" data-video-vimeo-id="338373286" data-order-id="24472804" data-video-index="33">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/338373286">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 34
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103601" class="sky-pilot-video-link " data-video-id='103601' data-video-vimeo-url="https://vimeo.com/338599307" data-item-id="36884745" data-video-vimeo-id="338599307" data-order-id="24472804" data-video-index="34">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/338599307">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 35
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103602" class="sky-pilot-video-link " data-video-id='103602' data-video-vimeo-url="https://vimeo.com/339008499" data-item-id="36884745" data-video-vimeo-id="339008499" data-order-id="24472804" data-video-index="35">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/339008499">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 36
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103603" class="sky-pilot-video-link " data-video-id='103603' data-video-vimeo-url="https://vimeo.com/339250109" data-item-id="36884745" data-video-vimeo-id="339250109" data-order-id="24472804" data-video-index="36">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/339250109">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 37
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103604" class="sky-pilot-video-link " data-video-id='103604' data-video-vimeo-url="https://vimeo.com/339720977" data-item-id="36884745" data-video-vimeo-id="339720977" data-order-id="24472804" data-video-index="37">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/339720977">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 38
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103605" class="sky-pilot-video-link " data-video-id='103605' data-video-vimeo-url="https://vimeo.com/340208105" data-item-id="36884745" data-video-vimeo-id="340208105" data-order-id="24472804" data-video-index="38">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/340208105">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 39
              </div>
            </div>
          </a>

          <a href="/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/videos/103606" class="sky-pilot-video-link " data-video-id='103606' data-video-vimeo-url="https://vimeo.com/341091876" data-item-id="36884745" data-video-vimeo-id="341091876" data-order-id="24472804" data-video-index="39">
            <div class="sky-pilot-video-item">
              <img class='sky-pilot-thumbnail' data-video-url="https://vimeo.com/341091876">
</img>

              <div class="sky-pilot-video-title">
                Standing Desk Episode 40
              </div>
            </div>
          </a>

      </div>

    </div>
```

This displays the current video with a list of other videos in the series in a right-hand sidebar.

If I enter one of the Vimeo embedded URLs into a browser, such as this one:
`https://vimeo.com/310901196`

I get essentially a 404 page: "Sorry, we couldn’t find that page".

If I start youtube-dl with the same embedded URL with this command:
`youtube-dl -v https://vimeo.com/310901196 --add-header Referer:https://robcosman.com/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/collections/21830 --cookies cookies.txt`

Or this:
`youtube-dl -v https://vimeo.com/310901196 --referer https://robcosman.com/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/collections/21830 --cookies cookies.txt`

Then this is the output:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://vimeo.com/240770945', u'--add-header', u'Referer:https://robcosman.com/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/collections/21830', u'--cookies', u'cookies.txt']
[debug] Adding header from command line option Referer:https://robcosman.com/apps/downloads/customers/3143823786050/orders/24472804/order_items/36884745/collections/21830
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 2.7.17 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo] 240770945: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

Can youtube-dl download these embedded Vimeo videos?

**Comment by dentedbread** [comment]
Apparently no one is interested in this issue, commenting or helping or whatever so it may as well be closed.  Ultimately I achieved the goal but by other means.
