### ISSUE TITLE
Bilibili some links seem to be broken or not supported Failed to parse JSON

### ISSUE THREAD

**Issue by someziggyman** [ytdl-org/youtube-dl#25377]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v -F https://www.bilibili.com/bangumi/play/ep316831
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.bilibili.com/bangumi/play/ep316831']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] ep316831: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ep316831: Downloading webpage
[generic] ep316831: Extracting information
WARNING: [generic] ep316831: Failed to parse JSON Invalid control character at: line 11 column 69 (char 508)
ERROR: Unsupported URL: https://www.bilibili.com/bangumi/play/ep316831
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2378, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2562, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 5, column 684
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3370, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.bilibili.com/bangumi/play/ep316831

```

## Description

Links you can try:
https://www.bilibili.com/bangumi/play/ep324720
https://www.bilibili.com/bangumi/play/ep316830
https://www.bilibili.com/bangumi/play/ep316831

**Comment by ganc56141** [comment]
bilibili might have changed their URL format for all anime related content—no longer do they use 'bangumi' as a subdomain. Perhaps an update to the parser is needed.

**Comment by stevenleeS0ht** [comment]
@dstftw , what is your opinion toward this issue?
