### ISSUE TITLE
Can't download from Tumblr - unsupported URL

### ISSUE THREAD

**Issue by mapofthe** [ytdl-org/youtube-dl#25390]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\MiningRig\Downloads\yt-dl>youtube-dl -v https://retrogamingblog2.tumblr.com/post/618778238111678464
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://retrogamingblog2.tumblr.com/post/618778238111678464']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[Tumblr] 618778238111678464: Downloading webpage
[generic] 618778238111678464#_=_: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 618778238111678464#_=_: Downloading webpage
[generic] 618778238111678464#_=_: Extracting information
ERROR: Unsupported URL: https://retrogamingblog2.tumblr.com/post/618778238111678464#_=_
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\generic.py", line 3370, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://retrogamingblog2.tumblr.com/post/618778238111678464#_=_
```

## Description

Hello! I can't download anything from Tumblr. Neither photos nor videos. The error is: Unsupported URL. Could you help me please?

**Comment by KMouratidis** [comment]
Are you sure this tool is suitable for tumblr downloads? It isn't mentioned in the readme...

**Comment by remitamine** [comment]
youtube-dl does not support downloading photos.
