### ISSUE TITLE
Downloading from 9NOW.COM.AU website no longer working - youtube_dl.utils.RegexNotFoundError: Unable to extract page data

### ISSUE THREAD

**Issue by andadc3** [ytdl-org/youtube-dl#25391]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\_Instal Kits\youtube-dl>youtube-dl -f bestvideo+bestaudio "https://www.9now.com.au/the-voice/season-9/clip-ckakqgukd001l0god4td4hd2n" --geo-bypass --geo-bypass-country AU --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo+bestaudio', 'https://www.9now.com.au/the-voice/season-9/clip-ckakqgukd001l0god4td4hd2n', '--geo-bypass', '--geo-bypass-country', 'AU', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-91449-g09628cb1b4, ffprobe N-91449-g09628cb1b4
[debug] Proxy map: {}
[debug] Using fake IP 1.142.90.109 (AU) as X-Forwarded-For.
[9now.com.au] clip-ckakqgukd001l0god4td4hd2n: Downloading webpage
ERROR: Unable to extract page data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\ninenow.py", line 52, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract page data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Downloading clips from The Voice Australia from the official website, 9now.com.au, used to work in the past years. However, this year it fails with the error mentioned above. I have checked other videos on the same website as well, and obtain the same error, so I suppose there must have been changes made to the website.

**Comment by neilaja** [comment]
Just getting the following now:

ERROR: This video is DRM protected.

**Comment by 89z** [comment]
Issue should be closed, URL is dead
