### ISSUE TITLE
Mixcloud - Links with "Sorry, not available in your country" crash parser

### ISSUE THREAD

**Issue by alamone** [ytdl-org/youtube-dl#25408]
d

## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.mixcloud.com/otographic/uploads/']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[mixcloud:user] otographic_uploads: Downloading JSON metadata
[mixcloud:user] otographic_uploads: Downloading JSON metadata
[mixcloud:user] otographic_uploads: Downloading JSON metadata
[download] Downloading playlist: Otographic Music (uploads)
[mixcloud:user] playlist Otographic Music (uploads): Collected 238 video ids (downloading 238 of them)
[download] Downloading video 1 of 238
[mixcloud] otographic_nhato-otographic-live-2020-day-2-part-5-2020-05-17: Downloading JSON metadata
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 1008, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 870, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\mixcloud.py", line 137, in _real_extract
AttributeError: 'NoneType' object has no attribute 'get'

## Description

WRITE DESCRIPTION HERE

Links on Mixcloud that are marked as "Sorry, this show is not available in your country" cause the parser to crash - these links should be detected and skipped to allow the other links to be downloaded

**Comment by alamone** [comment]
Note - able to fix by using -i option to ignore errors, but should be detected as geoblock instead of 'NoneType' object has no attribute 'get'
