### ISSUE TITLE
[ARD:mediathek] ERROR: Unable to extract media id

### ISSUE THREAD

**Issue by 13thirteen** [ytdl-org/youtube-dl#25405]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
F:\Video>youtube-dl -v -F https://www.ardmediathek.de/ard/video/krimis-im-ersten/dupin-bretonisches-vermaechtnis/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2tyaW1pcy1pbS1lcnN0ZW4vZTc5ZTcwZGMtMTQ4MS00ZTcyLWI2ZjktYjczZmQ5MzBmZGNl/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.ardmediathek.de/ard/video/krimis-im-ersten/dupin-bretonisches-vermaechtnis/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2tyaW1pcy1pbS1lcnN0ZW4vZTc5ZTcwZGMtMTQ4MS00ZTcyLWI2ZjktYjczZmQ5MzBmZGNl/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.6.4 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg N-69568-g21051af, ffprobe N-69568-g21051af
[debug] Proxy map: {}
[debug] Using fake IP 53.158.217.60 (DE) as X-Forwarded-For.
[ARD:mediathek] Y3JpZDovL2Rhc2Vyc3RlLmRlL2tyaW1pcy1pbS1lcnN0ZW4vZTc5ZTcwZGMtMTQ4MS00ZTcyLWI2ZjktYjczZmQ5MzBmZGNl: Downloading webpage
ERROR: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "c:\python36\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\python36\lib\site-packages\youtube_dl\extractor\ard.py", line 236, in _real_extract
    r'/play/(?:config|media)/(\d+)', webpage, 'media id')
  File "c:\python36\lib\site-packages\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


F:\Video>
```

## Description

Looks like the URL format of the ARD Mediathek has changed recently?

**Comment by riconeitzel** [comment]
Can second that … Player and URL Scheme have been changed last week

**Comment by pgeorgi** [comment]
--- youtube_dl/extractor/ard.py
+++ youtube_dl/extractor/ard.py
@@ -233,7 +233,7 @@ class ARDMediathekIE(ARDMediathekBaseIE):
         else:  # request JSON file
             if not document_id:
                 video_id = self._search_regex(
-                    r'/play/(?:config|media)/(\d+)', webpage, 'media id')
+                    r'/play/(?:config|media|sola)/(\d+)', webpage, 'media id')
             info = self._extract_media_info(
                 'http://www.ardmediathek.de/play/media/%s' % video_id,
                 webpage, video_id)

fixes it for me.

**Comment by jas-per** [comment]
thanks @pgeorgi - your fix works fine!
