### ISSUE TITLE
[ardmediathek.de] Unable to extract media id

### ISSUE THREAD

**Issue by someziggyman** [ytdl-org/youtube-dl#25413]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v -F https://www.ardmediathek.de/ard/video/filme-im-ersten/zimmer-mit-stall-waschbaeren-sind-los/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2Zlcm5zZWhmaWxtZSBpbSBlcnN0ZW4vMWE3MzU5MmMtZjY1NC00OWJiLWI2MmMtZDE1MTYxNWY0Yjdj/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.ardmediathek.de/ard/video/filme-im-ersten/zimmer-mit-stall-waschbaeren-sind-los/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2Zlcm5zZWhmaWxtZSBpbSBlcnN0ZW4vMWE3MzU5MmMtZjY1NC00OWJiLWI2MmMtZDE1MTYxNWY0Yjdj/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Using fake IP 53.234.242.13 (DE) as X-Forwarded-For.
[ARD:mediathek] Y3JpZDovL2Rhc2Vyc3RlLmRlL2Zlcm5zZWhmaWxtZSBpbSBlcnN0ZW4vMWE3MzU5MmMtZjY1NC00OWJiLWI2MmMtZDE1MTYxNWY0Yjdj: Downloading webpage
ERROR: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ard.py", line 236, in _real_extract
    r'/play/(?:config|media)/(\d+)', webpage, 'media id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

URL to try: 
https://www.ardmediathek.de/ard/video/filme-im-ersten/zimmer-mit-stall-waschbaeren-sind-los/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2Zlcm5zZWhmaWxtZSBpbSBlcnN0ZW4vMWE3MzU5MmMtZjY1NC00OWJiLWI2MmMtZDE1MTYxNWY0Yjdj/

**Comment by varac** [comment]
Dup of #25405
