### ISSUE TITLE
vivo.sx unable to extract filesize

### ISSUE THREAD

**Issue by alexlehm** [ytdl-org/youtube-dl#25420]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
λ youtube-dl https://vivo.sx/5ec5b4cd00 --verbose                                                                                             
[debug] System config: []                                                                                                                     
[debug] User config: []                                                                                                                       
[debug] Custom config: []                                                                                                                     
[debug] Command-line args: ['https://vivo.sx/5ec5b4cd00', '--verbose']                                                                        
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252                                                                             
[debug] youtube-dl version 2020.05.08                                                                                                         
[debug] Python version 3.5.2 (CPython) - Windows-10-10.0.18362-SP0                                                                            
[debug] exe versions: phantomjs 2.1.1                                                                                                         
[debug] Proxy map: {}                                                                                                                         
[Vivo] 5ec5b4cd00: Downloading webpage                                                                                                        
WARNING: unable to extract filesize; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  http
s://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.                   
[debug] Default format spec: best/bestvideo+bestaudio                                                                                         
[debug] Invoking downloader on 'https://node--liana.vivo.sx/vod/B6d4EjWgTSSlP1HfWIWtug/1590543121/0000097887'                                 
[download] Resuming download at byte 20454698                                                                                                 
[download] Destination: big_buck_bunny_480p_surround-fix-5ec5b4cd00.mp4                                                                       
[download]  31.5% of 68.27MiB at  1.49MiB/s ETA 00:31                                                                                         
ERROR: Interrupted by user                                                                                                                    ```


## Description

<!--
Provide an explanation of your issue in an arbitrary form. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

WRITE DESCRIPTION HERE
the tool reports that it is unable to extract the file size and this should be reported as bug.

**Comment by monolied** [comment]
Still the same issue with later versions, but additional output and no video:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'bestvideo+bestaudio', 'https://vivo.sx/db69eb58a9']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: avconv 11.3, avprobe 11.3
[debug] Proxy map: {}
[Vivo] db69eb58a9: Downloading webpage
WARNING: unable to extract filesize; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 863, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 1636, in process_video_result
youtube_dl.utils.ExtractorError: requested format not available
```

**Comment by knilch0r** [comment]
Still true for recent version. Download works however:
```
; youtube-dl --verbose https://vivo.sx/cf2137f496
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://vivo.sx/cf2137f496']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-5-amd64-x86_64-with-debian-10.7
[debug] exe versions: ffmpeg 4.1.6, ffprobe 4.1.6
[debug] Proxy map: {}
[Vivo] cf2137f496: Downloading webpage
WARNING: unable to extract filesize; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://node--andrea.vivo.sx/vod/azez-DJnjCZUPdh0Kq-Cgw/1608512535/0034965847'
[download] Destination: Big Buck Bunny-cf2137f496.mp4
[download]  25.1% of 111.37MiB at  5.84MiB/s ETA 00:14^C
ERROR: Interrupted by user
```
