### ISSUE TITLE
Dailymotion Error 403: No video formats found

### ISSUE THREAD

**Issue by ks202005** [ytdl-org/youtube-dl#25459]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.05.29**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
C:\Users\User>youtube-dl -v https://www.dailymotion.com/video/x57snnv
[debug] System config: []
[debug] User config: ['-i', '--add-header', 'Referer: https://play.vidyard.com/', '--hls-prefer-native', '--format', 'bestvideo+bestaudio/best', '--merge-output-format', 'mkv', '--youtube-skip-dash-manifest', '--add-metadata', '--embed-subs', '--sub-lang', 'en', '--wri
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.dailymotion.com/video/x57snnv']
[debug] Adding header from command line option Referer: https://play.vidyard.com/
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2020.05.29
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[dailymotion] Downloading Access Token
[dailymotion] x57snnv: Downloading media JSON metadata
[dailymotion] x57snnv: Downloading metadata JSON
[dailymotion] x57snnv: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\dailymotion.py", line 285, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\common.py", line 1350, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

Attempted to download [this](https://www.dailymotion.com/video/x77achl) and [this](https://www.dailymotion.com/video/x57snnv) video; both failed with this error.

**Comment by luizcieslak** [comment]
Try to update to `2020.06.06` version. I had this problem which solved by updating.
