### ISSUE TITLE
PBS Frontline is broken

### ISSUE THREAD

**Issue by dspraus** [ytdl-org/youtube-dl#25454]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.05.29**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

youtube-dl --verbose https://www.pbs.org/wgbh/frontline/film/inside-italys-covid-war/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.pbs.org/wgbh/frontline/film/inside-italys-covid-war/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.29
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-02-13-6d37ca8
[debug] Proxy map: {}
[debug] Using fake IP 6.255.102.220 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] inside-italys-covid-war: Downloading webpage
[pbs] inside-italys-covid-war: Downloading widget/partnerplayer page
[pbs] inside-italys-covid-war: Downloading portalplayer page
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\pbs.py", line 661, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\common.py", line 1350, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

I was previously able to download films from PBS Frontline using regular page URL - eg. https://www.pbs.org/wgbh/frontline/film/inside-italys-covid-war/

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/27605

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/21984

**Comment by Vangelis66** [comment]
Original report was made **1 1/2 years ago**, with a now obsolete `yt-dl` version (**2020.05.29**); without ignoring the fact latest git HEAD `yt-dl` snapshot _does_ have issues with various PBS.org offerings, the "Frontline Film" cited in OP, 

https://www.pbs.org/wgbh/frontline/film/inside-italys-covid-war/

doesn't seem to be one of those "issues" 😉 ; FWIW, that URI doesn't seem to be US-only, as the test below was done from an offshore IP address: 
```
youtube-dl -v --no-geo-bypass -F "https://www.pbs.org/wgbh/frontline/film/inside-italys-covid-war/" => 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-geo-bypass', '-F', 'https://www.pbs.org/wgbh/frontline/film/inside-italys-covid-war/']
[debug] Encodings: locale cp1253, fs utf-8, out utf-8, pref cp1253
[debug] youtube-dl version 2021.06.06+18-git-20210701-ga803582+PR#28955v2
[debug] Python version 3.7.12 (CPython) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, phantomjs 2.1.1, rtmpdump 2.4

[debug] Proxy map: {}
[pbs] Downloading JSON metadata
[pbs] inside-italys-covid-war: Downloading webpage
[pbs] inside-italys-covid-war: Downloading widget/partnerplayer page
[pbs] inside-italys-covid-war: Downloading portalplayer page
[pbs] inside-italys-covid-war: Downloading 0 video url info
[pbs] inside-italys-covid-war: Downloading m3u8 information
[pbs] inside-italys-covid-war: Downloading 1 video url info
[pbs] inside-italys-covid-war: Checking http-2000k video URL
[pbs] inside-italys-covid-war: http-2000k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] inside-italys-covid-war: Checking http-6500k video URL
[pbs] inside-italys-covid-war: http-6500k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] inside-italys-covid-war: Checking http-4500k video URL
[pbs] inside-italys-covid-war: http-4500k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] inside-italys-covid-war: Checking http-3000k video URL
[pbs] inside-italys-covid-war: Checking http-1100k video URL
[pbs] inside-italys-covid-war: http-1100k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] inside-italys-covid-war: Checking http-730k video URL
[pbs] inside-italys-covid-war: http-730k video URL is invalid, skipping: HTTP Error 403: Forbidden
[info] Available formats for 3042636767:
format code  extension  resolution note
0            mp4        unknown
hls-204      mp4        416x234     204k , avc1.4d400c, mp4a.40.5
hls-493      mp4        480x270     493k , avc1.4d4015, mp4a.40.5
hls-886      mp4        640x360     886k , avc1.64001e, mp4a.40.5
hls-1268     mp4        768x432    1268k , avc1.64001e, mp4a.40.5
hls-2196     mp4        960x540    2196k , avc1.64001f, mp4a.40.5
hls-3228     mp4        1280x720   3228k , avc1.64001f, mp4a.40.5
http-3228    mp4        1280x720   3228k , avc1.64001f, mp4a.40.5
hls-4848     mp4        1280x720   4848k , avc1.64001f, mp4a.40.2
hls-6913     mp4        1920x1080  6913k , avc1.640028, mp4a.40.2 (best)
```
:smile:

**Comment by 89z** [comment]
With all due respect, who are you even talking to? Check OPs history, they havent had any activity in at least a year.

**Comment by 89z** [comment]
It seems that videos are available on Frontline (which you linked), but also on the PBS site:

https://pbs.org/video/inside-italys-covid-war-kjangp

The PBS URLs (`pbs.org/video/`) are much easier to extract, as the URL includes the slug that you can plug directly into PBS API.

**Comment by 89z** [comment]
It seems each PBS show requires its own extractor. [Here is][1] one for Frontline:

~~~
PS C:\> pbs -i -a https://www.pbs.org/wgbh/frontline/film/inside-italys-covid-war/
GET https://www.pbs.org/wgbh/frontline/film/inside-italys-covid-war/
GET https://video.pbs.org/widget/partnerplayer/3042636767/?autoplay=true&start=0&end=0&chapterbar=false&topbar=false&endscreen=true
GET https://urs.pbs.org/redirect/ea5961146ffe409eb723bee51e3622e6/
Resolution:1280x720 Bandwidth:5596803 Codecs:avc1.64001f,mp4a.40.2
Resolution:1280x720 Bandwidth:3639299 Codecs:avc1.64001f,mp4a.40.5
Resolution:1920x1080 Bandwidth:8154554 Codecs:avc1.640028,mp4a.40.2
Resolution:960x540 Bandwidth:2511925 Codecs:avc1.64001f,mp4a.40.5
Resolution:768x432 Bandwidth:1417356 Codecs:avc1.64001e,mp4a.40.5
Resolution:640x360 Bandwidth:993902 Codecs:avc1.64001e,mp4a.40.5
Resolution:480x270 Bandwidth:541900 Codecs:avc1.4d4015,mp4a.40.5
Resolution:416x234 Bandwidth:224623 Codecs:avc1.4d400c,mp4a.40.5
~~~

[1]://github.com/89z/mech/blob/v1.50.7/pbs/frontline.go
