### ISSUE TITLE
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug - (2020.03.24-1.fc32)

### ISSUE THREAD

**Issue by msocorcim** [ytdl-org/youtube-dl#25479]
[dennis@localhost Audio Files]$ youtube-dl -x --audio-quality 0 --audio-format mp3 -o "Omid (Hope) - Thievery Corporation.%(ext)s" https://youtu.be/NCnQEA-eI30
[youtube] NCnQEA-eI30: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[dennis@localhost Audio Files]$ youtube-dl --verbose -x --audio-quality 0 --audio-format mp3 -o "Omid (Hope) - Thievery Corporation.%(ext)s" https://youtu.be/NCnQEA-eI30
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-x', '--audio-quality', '0', '--audio-format', 'mp3', '-o', 'Omid (Hope) - Thievery Corporation.%(ext)s', 'https://youtu.be/NCnQEA-eI30']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.3 (CPython) - Linux-5.6.14-300.fc32.x86_64-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3
[debug] Proxy map: {}
[youtube] NCnQEA-eI30: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 2364, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[dennis@localhost Audio Files]$

**Comment by msocorcim** [comment]
Thanks - my use case is fixed with /2020.05.29/ I'll let the Fedora maintainer know.
