### ISSUE TITLE
Add support for faz.net/podcasts

### ISSUE THREAD

**Issue by tom-9** [ytdl-org/youtube-dl#25473]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running youtube-dl version **2020.05.29**
- [X] I've searched the bugtracker for similar site feature requests including closed ones

### Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.faz.net/podcasts/f-a-z-digitec-podcast/elon-musk-und-die-nasa-zum-mond-und-noch-viel-weiter-16792188.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.29
[debug] Python version 3.7.7 (CPython) - Linux-5.4.28-gentoo-x86_64-x86_64-Intel-R-_Core-TM-_i7-4790S_CPU_@_3.20GHz-with-gentoo-2.6
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3
[debug] Proxy map: {}
[faz.net] 16792188: Downloading webpage
ERROR: Unable to extract media; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/faz.py", line 51, in _real_extract
    webpage, 'media')
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract media; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### Description

#1582 adds support for URLs like [https://www.faz.net/multimedia/videos/](https://www.faz.net/multimedia/videos/)...

Please add support for URLs like [https://www.faz.net/podcasts](https://www.faz.net/podcasts) ...
for example [https://www.faz.net/podcasts/f-a-z-digitec-podcast/elon-musk-und-die-nasa-zum-mond-und-noch-viel-weiter-16792188.html](https://www.faz.net/podcasts/f-a-z-digitec-podcast/elon-musk-und-die-nasa-zum-mond-und-noch-viel-weiter-16792188.html)

Thanks!

**Comment by tom-9** [comment]
The URL can be extracted by saving the page completely and then dig into the file player.htm:

`sed 's/http/\nhttp/g' <player.htm | egrep '\.(mp|ogg)' | sed 's/\?.*//' | head -n1`
