### ISSUE TITLE
Can't download Facebook Private Video, ERROR: Unable to extract lsd.

### ISSUE THREAD

**Issue by AbdullahTrees** [ytdl-org/youtube-dl#25500]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.05.29**
- [x] I've checked that all provided URLs are alive and playable in a browser 
   **NOTE:This is not possible since it's a private video, I've provided it, but you can't test it, try out your own private video on Facebook**
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--format', '(1125248847854583v)+(540950106591663a)', 'https://www.facebook.com/mqschoolofma
thematics/videos/284508766067599/', '--username', 'PRIVATE', '--password', 'PRIVATE', '--cookies', 'cookies', '--verbose
']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.05.29
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg git-2020-05-28-c0f01ea, ffprobe git-2020-05-28-c0f01ea
[debug] Proxy map: {}
[facebook] Downloading login page
ERROR: Unable to extract lsd; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest ver
sion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output
.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\YoutubeDL.py", line
797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\common.py"
, line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\common.py"
, line 433, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\facebook.p
y", line 306, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\facebook.p
y", line 254, in _login
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\common.py"
, line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract lsd; please report this issue on https://yt-dl.org/bug . Make sur
e you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag a
nd include its complete output.
```

## Description

Hello there! I was recently trying to download Facebook videos using youtube-dl as it's the only one I've seen that can grab high quality streams(all the other downloaders only find 360p :( ), however, after learning to use it a bit, I see that attempting to download this video has caused this problem. I'm mainly here since the console told me to report this, and I really need to get on downloading these videos as it's a part of my online class. Any help would be appreciated.

NOTE: I also have a problem with facebook locking my account if I use youtube-dl to download videos. They claim that someone has gotten access to my password. This has forced me to change my password twice already. I am now using `--cookies "cookies"`, if you guys have a better suggestion, please let me know.

**Comment by nguyenmanhthao996tn** [comment]
I've faced the same problem since last week! Still don't know how to fix this! If you have any solution (or alternative method), please tell me :(

**Comment by AbdullahTrees** [comment]
> I've faced the same problem since last week! Still don't know how to fix this! If you have any solution (or alternative method), please tell me :(

Good, that means it's reproducible i.e. an actual bug.

**Comment by ajm339** [comment]
How did you get it working with cookies?

**Comment by AbdullahTrees** [comment]
> How did you get it working with cookies?

`--cookies '<filename>'` creates a file storing the cookies required for saving your logins into FaceBook. This file generates in the root directory where youtube-dl executable exists. Possibly not having write permissions may cause you to not be able to save cookies...?

**Comment by dstftw** [comment]
No longer available.

**Comment by frakman1** [comment]
@dstftw 

> No longer available.

What does this mean?

I am getting this error using the same command that used to work for me in the past. All I changed was the URL and updated the cookies file.

I am using the latest version of `youtube-dl` on MacOS High Sierra.
Logs (parts redacted with xxxxx):

``` 
$youtube-dl --verbose --username xxxxx@xxxxx.com --cookies fbcookies.txt  https://www.facebook.com/xxxxx/videos/xxxxx/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--username', 'PRIVATE', '--cookies', 'fbcookies.txt', 'https://www.facebook.com/xxxxx/videos/xxxxx/']
Type account password and press [Return]:
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.1 (CPython) - macOS-10.13.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] Downloading login page
ERROR: Unable to extract lsd; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 533, in extract
    self.initialize()
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 437, in initialize
    self._real_initialize()
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/facebook.py", line 378, in _real_initialize
    self._login()
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/facebook.py", line 324, in _login
    lsd = self._search_regex(
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract lsd; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by 89z** [comment]
@frakman1 just post a new issue please.
