### ISSUE TITLE
Using Proxy  No video formats found (France TV)

### ISSUE THREAD

**Issue by dictdl30** [ytdl-org/youtube-dl#25505]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ X ] I've verified that I'm running youtube-dl version **2020.05.29**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X ] I've searched the bugtracker for similar bug reports including closed ones
- [X ] I've read bugs section in FAQ

## Verbose log

```
C:\Users\b>youtube-dl https://www.france.tv/spectacles-et-culture/theatre-et-danse/510921-les-rustres.html --verbose
[debug] System config: []
[debug] User config: ['-o', 'c:\\download\\%(title)s.%(ext)s', '--all-subs', '-f', '(bestvideo+bestaudio/best)[protocol^=http]', '--proxy', 'http://51.158.68.68:8811']
[debug] Custom config: []
[debug] Command-line args: ['https://www.france.tv/spectacles-et-culture/theatre-et-danse/510921-les-rustres.html', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.29
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-05-04-5767a2e, ffprobe git-2020-05-04-5767a2e
[debug] Proxy map: {'http': 'http://51.158.68.68:8811', 'https': 'http://51.158.68.68:8811'}
[FranceTVSite] 510921-les-rustres: Downloading webpage
[FranceTV] 7cdf2bfc-144e-45b2-aebc-50bd05e658cb: Downloading video JSON
[FranceTV] 7cdf2bfc-144e-45b2-aebc-50bd05e658cb: Downloading geo restriction info
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\francetv.py", line 209, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\francetv.py", line 169, in _extract_video
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\common.py", line 1350, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

with Firefox i can watch die video from the url https://www.france.tv/spectacles-et-culture/theatre-et-danse/510921-les-rustres.html by using proxy http 51.158.68.68 : 8811. youtube-dl.exe cannot find any video format. Error: No video formats found

**Comment by dictdl30** [comment]
dstftw, could you please tell me where is the message/issue, which I duplicated? I tried industriously to look for it but I could't find it.
