### ISSUE TITLE
bbc video does not get downloaded (win10) youtube-dl --version -->2020.05.29

### ISSUE THREAD

**Issue by wrhwebmaster** [ytdl-org/youtube-dl#25509]
## Checklist

- [ x] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2020.05.29**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
youtube-dl.exe --verbose "https://www.bbc.com/news/av/embed/p08fvzqq/52900486"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.bbc.com/news/av/embed/p08fvzqq/52900486']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.05.29
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-05-15-b18fd2b
[debug] Proxy map: {}
[bbc] 52900486: Downloading webpage
[bbc] p08fvzqq: Downloading media selection XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\bbc.py", line 937, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\common.py", line 1350, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE
BBC video is not extracted. Video is here: 
https://www.bbc.com/news/av/embed/p08fvzqq/52900486

**Comment by dirkf** [comment]
Works with https://github.com/ytdl-org/youtube-dl/pull/26821.

**Comment by dirkf** [comment]
Still broken at https://github.com/ytdl-org/youtube-dl/commit/e465b25c1fb0e72b97a032220399d4a959662095 (`unable to extract playlist data`).
