### ISSUE TITLE
CBS News download not working; 2020-06-03

### ISSUE THREAD

**Issue by Akaito** [ytdl-org/youtube-dl#25519]
## Checklist
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.05.29**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.cbsnews.com/news/thomas-mcclay-denver-police-officer-fired-lets-start-a-riot-george-floyd-protest/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.05.29
[debug] Python version 3.8.2 (CPython) - Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.29
[debug] exe versions: none
[debug] Proxy map: {}
[cbsnews] thomas-mcclay-denver-police-officer-fired-lets-start-a-riot-george-floyd-protest: Downloading webpage
ERROR: Unable to extract video JSON info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cbsnews.py", line 105, in _real_extract
    item = self._parse_json(self._html_search_regex(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video JSON info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description
I haven't tried CBS News downloads before, but I can see the video playing fine in-browser (Firefox).  I see there are other open issues for CBS News, but those are geo-blocked.  I'm in the US and not proxying/VPNing to view the video normally in the browser.

**Comment by merval** [comment]
Seems to work on 2020.07.28. Try updating and giving it another go.

**Comment by 89z** [comment]
Issue should be closed, download works as expected
