### ISSUE TITLE
Unable to complete download of sciencechannel.com video

### ISSUE THREAD

**Issue by sitymarz** [ytdl-org/youtube-dl#25529]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.05.29**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose https://www.sciencechannel.com/tv-shows/nasa-spacex-journey-to-the-future/full-episodes/nasa-spacex-journey-to-the-future
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.sciencechannel.com/tv-shows/nasa-spacex-journey-to-the-future/full-episodes/nasa-spacex-journey-to-the-future']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.29
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-71883-geb9fb50, ffprobe N-71883-geb9fb50
[debug] Proxy map: {}
[Discovery] nasa-spacex-journey-to-the-future: Downloading token JSON metadata
[Discovery] nasa-spacex-journey-to-the-future: Downloading content JSON metadata
[Discovery] nasa-spacex-journey-to-the-future: Downloading streaming JSON metadata
[Discovery] nasa-spacex-journey-to-the-future: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://content-ausw1-up-5.uplynk.com/30eff5286dab4bda8fbe7ddd4eb32997/i.m3u8?tc=1&exp=1591314515&rn=1385582529&ct=a&cid=30eff5286dab4bda8fbe7ddd4eb32997&ad.pingf=3&pp2ip=0&ad.cping=1&ad=fw&rays=cdefghiba&v=2&ad.customer_id=&ad.nw=&ad.prof=&ad.csid=&ad.vip=195.181.168.37&ad.kv=_fw_enable_lat_fc%2C1&ap.use=0&sig=7e5b54096c07ae8673822ae6d5c60c92abd5e91a1ad9d97db51877006a616acb&pbs=2067f6bc0f834cd797a6c2cd603b6c7c'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1229
[download] Destination: NASA & SpaceX - Journey to the Future-5ecd4cfcfdbe2159390d96b9.mp4
[download]  24.6% of ~3.04GiB at Unknown speed ETA Unknown ETATraceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\YoutubeDL.py", line 863, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\YoutubeDL.py", line 1644, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\YoutubeDL.py", line 1926, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\downloader\hls.py", line 174, in real_download
  File "C:\Python\Python34\lib\site-packages\Crypto\Cipher\blockalgo.py", line 295, in decrypt
ValueError: Input strings must be a multiple of 16 in length
```

## Description

Download fails each time at 24.6%

**Comment by sitymarz** [comment]
Seems to work with Python27.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29634

**Comment by dirkf** [comment]
URL no longer valid.
