### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'unicode'

### ISSUE THREAD

**Issue by heygitty** [ytdl-org/youtube-dl#25540]
The following command breaks with an TypeError.

\# youtube-dl --all-subs --embed-subs --merge-output-format mkv 'https://players.brightcove.net/102076671001/ShNTDWXQ_default/index.html?videoId=6159321787001'
[brightcove:new] 6159321787001: Downloading JSON metadata
[brightcove:new] 6159321787001: Downloading m3u8 information
[brightcove:new] 6159321787001: Downloading m3u8 information
[brightcove:new] 6159321787001: Downloading MPD manifest
[brightcove:new] 6159321787001: Downloading MPD manifest
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2019, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1818, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 3006, in subtitles_filename
TypeError: unsupported operand type(s) for +: 'NoneType' and 'unicode'

**Comment by tortycat3** [comment]
I'm getting exactly the same messages. Any ideas? All worked fine yesterday!

Thanks

**Comment by tortycat3** [comment]
I do not know how to fix this, could I have a hint, please? How do I install the file mentioned? Thank you.

**Comment by heygitty** [comment]
Perfect, thank you for fixing it so quickly!

**Comment by tortycat3** [comment]
Could you give me some advice as to how to implement this? Sorry but very limited programming experience. 
Thanks,
Eric. 


Sent from Yahoo Mail for iPhone


On Friday, June 5, 2020, 5:36 pm, Sergey M. <notifications@github.com> wrote:




Closed #25540 via b4eb0bc.

**Comment by heygitty** [comment]
Eric, try to update with "youtube-dl -U"

**Comment by tortycat3** [comment]
Thanks, tried that already got:

ERROR: can't find the current version. Please try again later.

Any other thoughts?

**Comment by tortycat3** [comment]
Solved it for the moment. Curl returned an invalid certificate error so I managed to use curl with the -k option which worked, now all works well.Brew did not work, no idea why. Thank you.
