### ISSUE TITLE
Downloads from WWE broken

### ISSUE THREAD

**Issue by kingbee88** [ytdl-org/youtube-dl#25557]
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
D:\unsorted\WWE>youtube-dl.exe -v --username xxxx --password xxxxx https://watch.wwe.com/episode/WWE-Money-in-the-Bank-2020-136533
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://watch.wwe.com/episode/WWE-Money-in-the-Bank-2020-136533']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-04-24-a501947, ffprobe git-2020-04-24-a501947
[debug] Proxy map: {}
[generic] WWE-Money-in-the-Bank-2020-136533: Requesting header
WARNING: Falling back on generic information extractor.
[generic] WWE-Money-in-the-Bank-2020-136533: Downloading webpage
[generic] WWE-Money-in-the-Bank-2020-136533: Extracting information
ERROR: Unsupported URL: https://watch.wwe.com/episode/WWE-Money-in-the-Bank-2020-136533
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\generic.py", line 3370, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://watch.wwe.com/episode/WWE-Money-in-the-Bank-2020-136533


D:\unsorted\WWE>
```

## Description

Downloading from WWE site gives unsupported URL error, although WWE is one of the officially supported sites of youtube-dl.

Note that I replaced my user name and password with xxxxxx in the verbose log above.

As far as I have been able to find out, in the fall of 2019 WWE changed their URL structure and this might cause the site detection to fail. It is now using the site: https://watch.wwe.com

**Comment by kingbee88** [comment]
What issue is this a duplicate of? I can't find any.
