### ISSUE TITLE
YouTube ERROR: No video formats found for specific video

### ISSUE THREAD

**Issue by Zipdox** [ytdl-org/youtube-dl#25566]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
zipdox@zipdox-pc:~/Videos$ youtube-dl https://www.youtube.com/watch?v=tPqOc4lOYuk
[youtube] tPqOc4lOYuk: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
zipdox@zipdox-pc:~/Videos$ youtube-dl --verbose https://www.youtube.com/watch?v=tPqOc4lOYuk
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=tPqOc4lOYuk']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.3 (CPython) - Linux-5.6.0-2-amd64-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.2-1, ffprobe 4.2.2-1, phantomjs 03, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] tPqOc4lOYuk: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/zipdox/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/zipdox/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/zipdox/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 2364, in _real_extract
    self._sort_formats(formats)
  File "/home/zipdox/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

It won't extract any formats for this specific video.

**Comment by ahmedtds** [comment]
your youtube-dl version is 3 months old
