### ISSUE TITLE
Mixcloud changed procedures, gives: urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by Ambusy** [ytdl-org/youtube-dl#25578]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\martin\Documents\Visual Studio\Projects\YoutubeDownloader\YoutubeDownloader\bin\Debug>youtube-dl -v ""https://www.mixcloud.com/wim-janssen3/laser-558-chris-carson-daily-closedown-14-04-1985-2315-0000/" -i -o "C:\Users\martin\Music\(ext)s" --ffmpeg-location ffmpeg\bin
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.mixcloud.com/wim-janssen3/laser-558-chris-carson-daily-closedown-14-04-1985-2315-0000/ -i -o C:\\Users\\martin\\Music\\(ext)s --ffmpeg-location ffmpeg\\bin']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[mixcloud] wim-janssen3_laser-558-chris-carson-daily-closedown-14-04-1985-2315-0000: Downloading JSON metadata
[mixcloud] wim-janssen3_laser-558-chris-carson-daily-closedown-14-04-1985-2315-0000: Downloading m3u8 informationWARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[mixcloud] wim-janssen3_laser-558-chris-carson-daily-closedown-14-04-1985-2315-0000: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://stream11.mixcloud.com/secure/c/m4a/64/4/0/b/4/6848-0065-48a2-a8df-58598a0c2e81.m4a?sig=PD0_jX3WCjoV_oj_mIM8hw'
ERROR: unable to download video data: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1287, in connect
  File "C:\Python\Python34\lib\ssl.py", line 362, in wrap_socket
  File "C:\Python\Python34\lib\ssl.py", line 580, in __init__
  File "C:\Python\Python34\lib\ssl.py", line 807, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 1926, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\utils.py", line 2736, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_openurllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>


C:\Users\martin\Documents\Visual Studio\Projects\YoutubeDownloader\YoutubeDownloader\bin\Debug>pause
Press any key to continue . . .
```

## Description

From Mixcloud until some time (3 - 5 months?) ago I could download media tracks in Windows 7 using Chrome by right clicking on the page name in the search results and choosing "Copy link address". This address was then used in the call for youtube-dl. No longer works, alas.

**Comment by Ambusy** [comment]
I searched on "mixcloud", sorry I did not see the TVP VOD problem. Added --no-check-certificate and it's resolved.
