### ISSUE TITLE
Czech TV

### ISSUE THREAD

**Issue by tomasptacek** [ytdl-org/youtube-dl#25573]
Cannot download video from Czech TV portal 

https://www.ceskatelevize.cz/ivysilani/12843499686-detektiv-endeavour-morse/219381484980004-sklizen

C:\YoutubeDL>youtube-dl.exe -v https://www.ceskatelevize.cz/ivysilani/12843499686-detektiv-endeavour-morse/219381484980004-sklizen
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.ceskatelevize.cz/ivysilani/12843499686-detektiv-endeavour-morse/219381484980004-sklizen']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-04-17-889ad93, ffprobe git-2020-04-17-889ad93
[debug] Proxy map: {}
[CeskaTelevize] 219381484980004-sklizen: Downloading webpage
[CeskaTelevize] 219381484980004-sklizen: Downloading JSON metadata
[CeskaTelevize] 219381484980004-sklizen: Downloading JSON metadata
[CeskaTelevize] 219381484980004-sklizen: Downloading JSON metadata
[CeskaTelevize] 219381484980004-sklizen: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\ceskatelevize.py", line 201, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 1350, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2020.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by jbubik** [comment]
Duplicate of #23896
