### ISSUE TITLE
Format not avalible (am I being dumb?)

### ISSUE THREAD

**Issue by BigCasper** [ytdl-org/youtube-dl#25583]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
## Verbose log
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '[height=720]', 'https://www.youtube.com/watch?v=VD0z_YB6gWc']
[debug] Encodings: locale cp1250, fs utf-8, out utf-8, pref cp1250
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.8.3 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] VD0z_YB6gWc: Downloading webpage
[youtube] {18} signature length 109, html5 player 39dd62a0
[youtube] {137} signature length 109, html5 player 39dd62a0
[youtube] {248} signature length 109, html5 player 39dd62a0
[youtube] {136} signature length 109, html5 player 39dd62a0
[youtube] {247} signature length 109, html5 player 39dd62a0
[youtube] {135} signature length 109, html5 player 39dd62a0
[youtube] {244} signature length 105, html5 player 39dd62a0
[youtube] {134} signature length 109, html5 player 39dd62a0
[youtube] {243} signature length 109, html5 player 39dd62a0
[youtube] {133} signature length 109, html5 player 39dd62a0
[youtube] {242} signature length 109, html5 player 39dd62a0
[youtube] {160} signature length 105, html5 player 39dd62a0
[youtube] {278} signature length 109, html5 player 39dd62a0
[youtube] {140} signature length 109, html5 player 39dd62a0
[youtube] {249} signature length 109, html5 player 39dd62a0
[youtube] {250} signature length 109, html5 player 39dd62a0
[youtube] {251} signature length 105, html5 player 39dd62a0
ERROR: requested format not available
Traceback (most recent call last):
  File "c:\users\user1\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\users\user1\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "c:\users\user1\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 1635, in process_video_result
    raise ExtractorError('requested format not available',
youtube_dl.utils.ExtractorError: requested format not available
```

## Description

The Video is playable on YT in 720 and 1080, but yt-dl only wants to do 360 for some reason. I hope I'm just doing something wrong. Video only download works fine. What's the matter here? (am I just being dislectic or smthn?)

**Comment by dstftw** [comment]
`[height=720]` means `best[height=720]`, for what does `best` mean read FAQ.

**Comment by BigCasper** [comment]
maybe you misunderstood. The Downloader doesn't want to download an mp4 formatted file in anything higher then 360p, even though the video is avalible in higher qualities. Parsing nothing results in a 360, parsing the you want something higher in a combined vid-aud results in it being not avalible.

**Comment by dstftw** [comment]
Again: read what does `best` mean.
