### ISSUE TITLE
All unlocked Good Morining America play on browser, but youtube-dl reports authenitcation error

### ISSUE THREAD

**Issue by DarF234** [ytdl-org/youtube-dl#25589]
Below is the verbose log for two different episodes.  Both play in the browser and have no lock symbols on them. but youtube-dl reports "ERROR: This video is only available for users of participating TV providers." on these and ALL GMA unlocked episodes.  I don't have this problem with any other program on the ABC web site.  
  This is on a Windows 7 system if that is not evident.

  BY file splits stdout and stderr into two files. The text in bold is the stdout file.  The rest is the stderr file.

**[Go] 31-sunday-may-31-2020: Downloading webpage
[Go] VDKA0_uixgx8ru: Downloading JSON metadata**[Go] 30-saturday-may-30-2020: Downloading webpage
[Go] VDKA0_uixgx8ru: Downloading JSON metadata
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--geo-bypass', '--verbose', '--retries', '100', '--fragment-retries', '3', '--socket-timeout', '240', '--ignore-errors', '--no-overwrites', '--console-title', '--write-all-thumbnails', '--write-description', '--write-info-json', '--write-annotations', '--write-sub', '--sub-format', 'srt/best', '--all-subs', '-o', "Q:\\NetworkShows\\200608\\%(series)s\\%(series)s [S%(season_number)02d E%(episode_number)02d] ''%(title)s'' d%(upload_date)s [%(resolution)s].%(ext)s", '--batch-file', 'TV200608GMAT.txt']
[debug] Batch file urls: ['https://abc.com/shows/good-morning-america/episode-guide/2020-05/31-sunday-may-31-2020', 'https://abc.com/shows/good-morning-america/episode-guide/2020-05/30-saturday-may-30-2020']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-95085-g525de95679, ffprobe N-95085-g525de95679, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\go.py", line 187, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\adobepass.py", line 1414, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\adobepass.py", line 1379, in raise_mvpd_required
youtube_dl.utils.ExtractorError: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.

ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\go.py", line 187, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\adobepass.py", line 1414, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\adobepass.py", line 1379, in raise_mvpd_required
youtube_dl.utils.ExtractorError: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.

**Comment by dstftw** [comment]
Bother to read whole error message.

**Comment by DarF234** [comment]
I read it fully before I sent it.  I read it now again. Okay. So what did I miss?  I already told you they were flagged by youtube-dl as "ERROR: This video is only available for users of participating TV providers." But these files play in the browser and have no lock symbol on them. (At the time I reported this.)  The ones with the lock symbol will not play in the browser.
If there's something else I missed, please enlighten me.
With everything else on ABC:
Locked; browser won't play and error message from youtube-dl.
No Locked: browser will play and youtube-dl will work.
So what is different here with GMA that it's not locked, the browser will play it, but youtube-dl sees a sign-in requirement?
