### ISSUE TITLE
itv.com (aka ITV Hub) broken

### ISSUE THREAD

**Issue by 0ddb0d** [ytdl-org/youtube-dl#25581]
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.06.06**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.itv.com/hub/the-ellen-degeneres-show/2a4350a0788']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.06
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-1020-gcp-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.1.4
[debug] Proxy map: {}
[debug] Using fake IP 25.226.227.51 (GB) as X-Forwarded-For.
[ITV] 2a4350a0788: Downloading webpage
[ITV] 2a4350a0788: Downloading XML
WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out
[ITV] 2a4350a0788: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/itv.py", line 260, in _real_extract
    self._sort_formats(formats)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--no-geo-bypass', u'https://www.itv.com/hub/the-ellen-degeneres-show/2a4350a0788']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.06
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-1020-gcp-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.1.4
[debug] Proxy map: {}
[ITV] 2a4350a0788: Downloading webpage
[ITV] 2a4350a0788: Downloading XML
WARNING: Unable to download XML: HTTP Error 403: Forbidden
[ITV] 2a4350a0788: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/itv.py", line 260, in _real_extract
    self._sort_formats(formats)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Something has changed on itv.com. I thought at first it may be geoblocking problem but both test runs shown above were performed on a server in London i.e. I was wrong ;) Playback via browser is fine and pulling the mpd manually gets ffmpeg going (see example log below) but I don't know exactly what the problem is.

```
Input #0, dash, from 'https://itvpnpdotcom.content.itv.com/2-4350-0788-001/18/1/VAR014/2-4350-0788-001_18_1_VAR014.ism/.mpd?hdnea=st=1591633858~exp=1591655458~acl=/*~data=nohubplus~hmac=4fb897a6b6219463266a151850c93a3dff6e0f5418fbd999bb6b61ddd653ac1f':
  Duration: 00:39:01.00, start: 0.000000, bitrate: 0 kb/s
  Program 0
    Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p, 512x288 [SAR 1:1 DAR 16:9], 456 kb/s, 50 fps, 50 tbr, 50 tbn, 100 tbc
    Metadata:
      variant_bitrate : 458656
      id              : video=458656
    Stream #0:1: Video: h264 (High) (avc1 / 0x31637661), yuv420p, 512x288 [SAR 1:1 DAR 16:9], 656 kb/s, 50 fps, 50 tbr, 50 tbn, 100 tbc
    Metadata:
      variant_bitrate : 652064
      id              : video=652064
    Stream #0:2: Video: h264 (High) (avc1 / 0x31637661), yuv420p, 896x504 [SAR 1:1 DAR 16:9], 927 kb/s, 50 fps, 50 tbr, 50 tbn, 100 tbc
    Metadata:
      variant_bitrate : 933437
      id              : video=933437
    Stream #0:3: Video: h264 (High) (avc1 / 0x31637661), yuv420p, 896x504 [SAR 1:1 DAR 16:9], 1215 kb/s, 50 fps, 50 tbr, 50 tbn, 100 tbc
    Metadata:
      variant_bitrate : 1213894
      id              : video=1213894
    Stream #0:4: Video: h264 (High) (avc1 / 0x31637661), yuv420p, 896x504 [SAR 1:1 DAR 16:9], 1504 kb/s, 50 fps, 50 tbr, 50 tbn, 100 tbc
    Metadata:
      variant_bitrate : 1505036
      id              : video=1505036
    Stream #0:5: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 96 kb/s
    Metadata:
      variant_bitrate : 128000
      id              : audio=128000
Output #0, matroska, to 'output.mkv':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p, 896x504 [SAR 1:1 DAR 16:9], q=2-31, 927 kb/s, 50 fps, 50 tbr, 1k tbn, 50 tbc
    Metadata:
      variant_bitrate : 933437
      id              : video=933437
    Stream #0:1: Audio: aac (LC) ([255][0][0][0] / 0x00FF), 48000 Hz, stereo, fltp, 96 kb/s
    Metadata:
      variant_bitrate : 128000
      id              : audio=128000

**Comment by 0ddb0d** [comment]
Closing this issue as the underlying cause isn't youtube-dl it's the ITV website. Some shows download fine, others don't.

Will re-open only if I can establish a pattern.
