### ISSUE TITLE
It stopped working with the domain mitele.es

### ISSUE THREAD

**Issue by Krosgore** [ytdl-org/youtube-dl#25582]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X ] I've verified that I'm running youtube-dl version **2020.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
D:\Escritorio\atresplayer>youtube-dl -F https://www.mitele.es/series-online/la-pecera-de-eva/temporada-1/capitulo-1-40_1007017075001/player/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.mitele.es/series-online/la-pecera-de-eva/temporada-1/capitulo-1-40_1007017075001/player/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-04-17-889ad93, ffprobe git-2020-04-17-889ad93
[debug] Proxy map: {}
[MiTele] capitulo-1-40_1007017075001: Downloading webpage
[Ooyala] 9kdmw0ZDE6uSob5PFG8MUISHWAzi1vU-: Downloading JSON metadata
[Ooyala] 9kdmw0ZDE6uSob5PFG8MUISHWAzi1vU-: Downloading JSON metadata
[Ooyala] 9kdmw0ZDE6uSob5PFG8MUISHWAzi1vU-: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
ERROR: Ooyala said: movie expired
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\ooyala.py", line 173, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\ooyala.py", line 89, in _extract
youtube_dl.utils.ExtractorError: Ooyala said: movie expired
```

## Description

It stopped working with the domain mitele.es

**Comment by dstftw** [comment]
You must provide account credentials.
