### ISSUE TITLE
Bitchute video URL invalid / No video formats found.

### ISSUE THREAD

**Issue by a-raccoon** [ytdl-org/youtube-dl#25586]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
>youtube-dl -v "https://www.bitchute.com/video/YZITyNc9QPc/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bitchute.com/video/YZITyNc9QPc/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[BitChute] YZITyNc9QPc: Downloading webpage
[BitChute] YZITyNc9QPc: Checking video URL
[BitChute] YZITyNc9QPc: video URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\bitchute.py", line 66, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 1350, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

The site Bitchute doesn't appear to download. The error staets "video URL is invalid, skipping" and "No video formats found."

Test with `https://www.bitchute.com/video/YZITyNc9QPc/`

**Comment by a-raccoon** [comment]
@dstftw if this can't be reproduced, what issue might I be experiencing per the debug logs?

**Comment by TegraMorgan** [comment]
I have the same issue here

**Comment by TegraMorgan** [comment]
@dstftw I'll try to see by myself what I can do. Can you get me in contact with person who originally added support for bitchute?
