### ISSUE TITLE
https://www.raiplay.it/video/2020/06/report---La-comunita-energetica-7da05d08-63e5-4f9d-96c3-c7f1f8028511.html

### ISSUE THREAD

**Issue by giovannitriboli** [ytdl-org/youtube-dl#25595]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dl --verbose 'https://www.raiplay.it/video/2020/06/report---La-comunita-energetica-7da05d08-63e5-4f9d-96c3-c7f1f8028511.html'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.raiplay.it/video/2020/06/report---La-comunita-energetica-7da05d08-63e5-4f9d-96c3-c7f1f8028511.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.6.9 (CPython) - Linux-5.3.0-53-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[RaiPlay] 7da05d08-63e5-4f9d-96c3-c7f1f8028511: Downloading video JSON
ERROR: 7da05d08-63e5-4f9d-96c3-c7f1f8028511: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 899, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 899, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rai.py", line 174, in _real_extract
    '%s?json' % url, video_id, 'Downloading video JSON')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 892, in _download_json
    expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 876, in _download_json_handle
    fatal=fatal), urlh
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 903, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: 7da05d08-63e5-4f9d-96c3-c7f1f8028511: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE
There's nothing in particular to add.

**Comment by giovannitriboli** [comment]
Excuse me but I can't find the youtube-dl bug tracker.

**Comment by giovannitriboli** [comment]
Hi Sergey, Please be patient with me. I'm a newbie here on github.
I reported the issue following the instruction at https://yt-dl.org/bug, as clearly stated in the youtube-dl's output.
I have a question. Did you close this issue because you already have it in your to-be-processed queue or because I'm supposed to decode the instructions found in the duplicated case list that you pointed out to me?
In the former case, will you alert me when the issue will be solved?
In the latter case, unfortunately, I tried to decode the directions at no avail.
I hope you can clarify.
TIA
Giovanni
