### ISSUE TITLE
XTube Python Extraction Failure

### ISSUE THREAD

**Issue by AlphaLunaFurry** [ytdl-org/youtube-dl#25602]
Tried to download a video from XTube, and this happened.

`$ youtube-dl "https://www.xtube.com/video-watch/wife-using-a-toy-32459942"
[XTube] wife-using-a-toy: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/xtube.py", line 103, in _real_extract
UnboundLocalError: local variable 'sources' referenced before assignment`

Thank you in advance. If you need anything else, feel free to send me a message or reply here.

UPDATE:

Updated script to latest version, python traceback is a little different, but same bug.

`$ youtube-dl "https://www.xtube.com/video-watch/wife-using-a-toy-32459942"
[XTube] wife-using-a-toy: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/xtube.py", line 103, in _real_extract
UnboundLocalError: local variable 'sources' referenced before assignment`

Version string:

`$ youtube-dl --version
2020.06.06`

**Comment by dstftw** [comment]
>Amateur Videos can be watched only by members.

Pass authenticated cookies to youtube-dl.
