### ISSUE TITLE
6play.fr - replay 

### ISSUE THREAD

**Issue by campones** [ytdl-org/youtube-dl#25603]
youtube-dl https://www.6play.fr/turbo-p_884/emission-du-08-mars-c_12592431 -vv
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.6play.fr/turbo-p_884/emission-du-08-mars-c_12592431', u'-vv']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.06
[debug] Python version 2.7.6 (CPython) - Linux-3.13.0-170-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-76159-gda43e9e, ffprobe N-76159-gda43e9e, rtmpdump 2.4
[debug] Proxy map: {}
[6play] 12592431: Downloading JSON metadata
[6play] 12592431: Downloading webpage
[6play] 12592431: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12592431: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[6play] 12592431: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12592431: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[6play] 12592431: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12592431: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/sixplay.py", line 113, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found;

**Comment by dirkf** [comment]
See #24967.
