### ISSUE TITLE
cant dl video from FB

### ISSUE THREAD

**Issue by magvay** [ytdl-org/youtube-dl#25612]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.06.06**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
 youtube-dl.exe -v https://www.facebook.com/slava.poe/videos/3061937543897946
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.facebook.com/slava.poe/videos/3061937543897946']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-06-03-b6d7c4c, ffprobe git-2020-06-03-b6d7c4c
[debug] Proxy map: {}
[facebook] 3061937543897946: Downloading webpage
[facebook] 3061937543897946: Downloading webpage
[facebook] 3061937543897946: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\facebook.py", line 481, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\facebook.py", line 380, in _extract_from_url
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

ERROR: Cannot parse data;

**Comment by dstftw** [comment]
>This Content Isn't Available Right Now
