### ISSUE TITLE
[Youtube] Can't extract title from unavailable video

### ISSUE THREAD

**Issue by Coloradohusky** [ytdl-org/youtube-dl#25615]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-jv', 'https://www.youtube.com/watch?v=00C7AQDQJII']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.8.2 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1
[debug] Proxy map: {}
ERROR: 00C7AQDQJII: YouTube said: This video is not available.
Sorry about that.
Traceback (most recent call last):
  File "c:\users\riley\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\riley\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\users\riley\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\youtube.py", line 1827, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: 00C7AQDQJII: YouTube said: This video is not available.
Sorry about that.
```

## Description

Attempting to retrieve video title using -j, video title shows up on YouTube but can't be extracted by YoutubeDL because the video is unavailable.

**Comment by dstftw** [comment]
This is expected behavior.

**Comment by Coloradohusky** [comment]
How would I get the title then?
