### ISSUE TITLE
[Youtube] ERROR: unable to download video data: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by NavnDK** [ytdl-org/youtube-dl#25633]
## Checklist

- [ x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2020.06.06**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-cf', '22/18', 'https://www.youtube.com/watch?v=MMJVZ48IRkM', '-o', '/media/navndk/Media/Media/Shows/Luke Smith/Season 1/Luke Smith - %(upload_date)s - %(title)s.%(ext)s', '--download-archive', '/media/navndk/Media/Media/Shows/Luke Smith/.youtube-dl', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.8.2 (CPython) - Linux-5.4.0-7634-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] MMJVZ48IRkM: Downloading webpage
[debug] Invoking downloader on 'https://r2---sn-h5q7rn7l.googlevideo.com/videoplayback?expire=1591968953&ei=WTDjXtzeLbW1xN8Pguij-AI&ip=212.102.48.70&id=o-AL0vKLt5FFDUOF5SVyJq4ASpUNunq28YRqMeYgC32R-O&itag=22&source=youtube&requiressl=yes&mh=F1&mm=31%2C26&mn=sn-h5q7rn7l%2Csn-5hnekn7s&ms=au%2Conr&mv=m&mvi=1&pl=25&pcm2=yes&initcwndbps=2812500&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=742.179&lmt=1559226901074163&mt=1591947274&fvip=2&fexp=23882514&c=WEB&txp=2316222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJanHAAxPkBZiC6YTatUFgvGVgnBqUu1GUgDpUaRLxQEAiEAxon_HA7UNSF66Ku7tIm8lcyeH3sMzSytFuy2QyTHK0c%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgFwpGE1w6lsB9bSX9dRX7WXrfYyJRcg-V5eCQmuntsj8CIGd13oXnIiiDTB3xet-r_IfxFwGKghGYoufdEuCz6_-n'
[download] Resuming download at byte 506070
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/navndk/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/home/navndk/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/home/navndk/.local/lib/python3.8/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/home/navndk/.local/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/home/navndk/.local/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/navndk/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found```


## Description

<!--
Provide an explanation of your issue in an arbitrary form. Please make sure the description is worded well enough to be understood, see https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

ehh idk how to word this but like i can't download the video i get 404 error i tested that i can play the video i played the whole video and works just fine i deleted cache dir and everything https://www.youtube.com/watch?v=MMJVZ48IRkM is the broken video

**Comment by garoto** [comment]
The mp4 with format id #22 appears to be broken on this video. Format #18 is working fine, as is `bestvideo+bestaudio`.
