### ISSUE TITLE
Cannot Download A Particular Video on youtube using YTDL

### ISSUE THREAD

**Issue by aakashalloria007** [ytdl-org/youtube-dl#25641]
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.06.06**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\aakas>youtube-dl -v --age-limit 20 https://www.youtube.com/watch?v=1ER67r8OCW8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--age-limit', '20', 'https://www.youtube.com/watch?v=1ER67r8OCW8']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.8.3 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3
[debug] Proxy map: {}
[youtube] 1ER67r8OCW8: Downloading webpage
[youtube] 1ER67r8OCW8: Downloading embed webpage
[youtube] 1ER67r8OCW8: Refetching age-gated info webpage
[youtube] {18} signature length 109, html5 player 16a691a1
[youtube] {137} signature length 109, html5 player 16a691a1
[youtube] {248} signature length 105, html5 player 16a691a1
[youtube] {136} signature length 109, html5 player 16a691a1
[youtube] {247} signature length 109, html5 player 16a691a1
[youtube] {135} signature length 105, html5 player 16a691a1
[youtube] {244} signature length 109, html5 player 16a691a1
[youtube] {397} signature length 105, html5 player 16a691a1
[youtube] {134} signature length 109, html5 player 16a691a1
[youtube] {243} signature length 109, html5 player 16a691a1
[youtube] {396} signature length 109, html5 player 16a691a1
[youtube] {133} signature length 109, html5 player 16a691a1
[youtube] {242} signature length 109, html5 player 16a691a1
[youtube] {395} signature length 109, html5 player 16a691a1
[youtube] {160} signature length 109, html5 player 16a691a1
[youtube] {278} signature length 109, html5 player 16a691a1
[youtube] {394} signature length 105, html5 player 16a691a1
[youtube] {140} signature length 109, html5 player 16a691a1
[youtube] {249} signature length 109, html5 player 16a691a1
[youtube] {250} signature length 109, html5 player 16a691a1
[youtube] {251} signature length 109, html5 player 16a691a1
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r14---sn-ci5gup-qxad.googlevideo.com/videoplayback?expire=1592009613&ei=Lc_jXtP4MImywgPc4aLIDA&ip=122.161.113.108&id=o-AOWXQMmpi6sJzVVQSUg9dk7nR3RqM1jO4gB0bOsgODaO&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397&source=youtube&requiressl=yes&mh=Dg&mm=31%2C26&mn=sn-ci5gup-qxad%2Csn-cvh7knes&ms=au%2Conr&mv=m&mvi=13&pcm2cms=yes&pl=20&initcwndbps=765000&vprv=1&mime=video%2Fwebm&gir=yes&clen=7335306&dur=185.999&lmt=1556912854239446&mt=1591987897&fvip=3&keepalive=yes&fexp=23882513&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgAMqx5yGhdYEHv8W6YvM2PiNP-tmrSTqfZttMREpQk7ECIHgzjioqnD9306oMuaIHam8ZrSUnEqd8VD-COXG6HAl4&sig=AOq0QJ8wRAIgPP2I7bV80gJ4KRWSI8BFvgZtQJxJzwePA5mi4jeePwsCIAGlDwlUXsln91yPS4lX2iPZW5C37se9GVfO0lhk_jRU&ratebypass=yes'
ERROR: unable to download video data: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
Traceback (most recent call last):
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\urllib\request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\http\client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\http\client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\http\client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\http\client.py", line 1006, in _send_output
    self.send(msg)
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\http\client.py", line 946, in send
    self.connect()
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\http\client.py", line 1402, in connect
    super().connect()
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\http\client.py", line 917, in connect
    self.sock = self._create_connection(
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\socket.py", line 808, in create_connection
    raise err
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\downloader\common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\downloader\http.py", line 341, in real_download
    establish_connection()
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\downloader\http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\utils.py", line 2734, in https_open
    return self.do_open(functools.partial(
  File "c:\users\aakas\appdata\local\programs\python\python38\lib\urllib\request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
```

## Description

This issue is while trying to download Hentai-S3RL from youtube. Link attached in verbose. I thought it was an issue with age restricted videos as the python shell gets stuck on [youtube] 1ER67r8OCW8: Refetching age-gated info webpage. But other age restricted videos are working properly. And one more important fact that this video was downloadable till yesterday i.e 11/6/2020

Edit: This is my first report I tried my best in following all the rules. Sorry in advance if i made any mistakes.

**Comment by dstftw** [comment]
Most likely network issue on your side.

**Comment by aakashalloria007** [comment]
But every single video except this one is working
