### ISSUE TITLE
[VRV.co] Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>

### ISSUE THREAD

**Issue by thegreatestminer** [ytdl-org/youtube-dl#25654]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://vrv.co/watch/GRNV9WVG6/SING-YESTERDAY-FOR-ME:A-Spring-Storm']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2019-10-23-1f327f5, ffprobe git-2019-10-23-1f327f5
[debug] Proxy map: {}
[vrv] None: Downloading webpage
[vrv] Downloading Token Credentials JSON metadata
[vrv] GRNV9WVG6: Downloading resource path JSON metadata
[vrv] GRNV9WVG6: Downloading CMS Signing JSON metadata
[vrv] GRNV9WVG6: Downloading object JSON metadata
[vrv] GRNV9WVG6: Downloading video JSON metadata
[vrv] GRNV9WVG6: Downloading streams JSON metadata
[vrv] GRNV9WVG6: Downloading dash-audio-ja-JP information
WARNING: Failed to download MPD manifest: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[vrv] GRNV9WVG6: Downloading dash-audio-ja-JP-hardsub-ar-ME information
WARNING: Failed to download MPD manifest: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[vrv] GRNV9WVG6: Downloading dash-audio-ja-JP-hardsub-ru-RU information
WARNING: Failed to download MPD manifest: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[vrv] GRNV9WVG6: Downloading dash-audio-ja-JP-hardsub-fr-FR information
WARNING: Failed to download MPD manifest: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[vrv] GRNV9WVG6: Downloading dash-audio-ja-JP-hardsub-es-LA information
WARNING: Failed to download MPD manifest: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[vrv] GRNV9WVG6: Downloading dash-audio-ja-JP-hardsub-de-DE information
WARNING: Failed to download MPD manifest: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[vrv] GRNV9WVG6: Downloading dash-audio-ja-JP-hardsub-en-US information
WARNING: Failed to download MPD manifest: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[vrv] GRNV9WVG6: Downloading dash-audio-ja-JP-hardsub-it-IT information
WARNING: Failed to download MPD manifest: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[vrv] GRNV9WVG6: Downloading dash-audio-ja-JP-hardsub-es-ES information
WARNING: Failed to download MPD manifest: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[vrv] GRNV9WVG6: Downloading dash-audio-ja-JP-hardsub-pt-BR information
WARNING: Failed to download MPD manifest: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[vrv] GRNV9WVG6: Downloading hls-audio-ja-JP information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[vrv] GRNV9WVG6: Downloading hls-audio-ja-JP-hardsub-ar-ME information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[vrv] GRNV9WVG6: Downloading hls-audio-ja-JP-hardsub-ru-RU information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[vrv] GRNV9WVG6: Downloading hls-audio-ja-JP-hardsub-fr-FR information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[vrv] GRNV9WVG6: Downloading hls-audio-ja-JP-hardsub-es-LA information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[vrv] GRNV9WVG6: Downloading hls-audio-ja-JP-hardsub-de-DE information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[vrv] GRNV9WVG6: Downloading hls-audio-ja-JP-hardsub-en-US information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[vrv] GRNV9WVG6: Downloading hls-audio-ja-JP-hardsub-it-IT information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[vrv] GRNV9WVG6: Downloading hls-audio-ja-JP-hardsub-es-ES information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[vrv] GRNV9WVG6: Downloading hls-audio-ja-JP-hardsub-pt-BR information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\vrv.py", line 206, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 1350, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Trying to download an episode on VRV, but I get a `WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>` error. I can indeed watch the video on Chrome 83 Stable.

Example URL: https://vrv.co/watch/GRNV9WVG6/SING-YESTERDAY-FOR-ME:A-Spring-Storm
Local time: 2020-06-13 14:21 EST

**Comment by thegreatestminer** [comment]
I have a feeling this might just be an expired certificate, as passing `--no-check-certificate` causes this to work just fine.

I am also experiencing the same issue as #25541.

**Comment by thegreatestminer** [comment]
Manually building youtube-dl with Python 3.8.2 + PyInstaller 3.6 causes this error to disappear. Version of Python used to build .exe the cause of this error?

**Comment by toyotabedzrock** [comment]
This is also happening on xvideos since the beginning of the month. --no-check-certificate fixes it. I'm guessing that since browsers work around the bad config they won't ever fix it.

**Comment by ValZapod** [comment]
Python 3.8.2 has newer openssl. This happened becasue Addtrust expired.

**Comment by andi448** [comment]
Also experiencing this problem with Soundcloud and the Windows-version of yt-dl (2020.11.21.1), but already on JSON metadata.

`ERROR: Unable to download JSON metadata: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))`

**Comment by Technetium1** [comment]
This failure is because of an expired cert. Duplicate of https://github.com/ytdl-org/youtube-dl/issues/883
