### ISSUE TITLE
download from watch.travelchannel not working

### ISSUE THREAD

**Issue by philp0w** [ytdl-org/youtube-dl#25664]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://watch.travelchannel.com/tv-shows/ghost-nation/full-episodes/a-nightmare-in-the-nursery']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.06
[debug] Python version 2.7.16 (CPython) - Darwin-19.4.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.2.3, ffprobe 4.2.3, rtmpdump 2.4
[debug] Proxy map: {}
[Discovery] a-nightmare-in-the-nursery: Downloading token JSON metadata
[Discovery] a-nightmare-in-the-nursery: Downloading content JSON metadata
[Discovery] a-nightmare-in-the-nursery: Downloading streaming JSON metadata
ERROR: This video is only available via cable service provider subscription that is not currently supported. You may want to use --cookies.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/discovery.py", line 104, in _real_extract
    display_id, 'Downloading streaming JSON metadata', headers=headers)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 892, in _download_json
    expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 870, in _download_json_handle
    expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 660, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 645, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/discovery.py", line 114, in _real_extract
    ' is not currently supported. You may want to use --cookies.', expected=True)
ExtractorError: This video is only available via cable service provider subscription that is not currently supported. You may want to use --cookies.
```

## Description

I am not able to download the video from this link
[https://watch.travelchannel.com/tv-shows/ghost-nation/full-episodes/a-nightmare-in-the-nursery](url)
or any other video after watching/downloading one already.
I am working on a Mac.
The first one worked fine with youtube-dl.
youtube-dl tells me to use `--cookies` but that didn't work either.

**Comment by dirkf** [comment]
URL no longer valid
