### ISSUE TITLE
Warning and Error logs in iOS

### ISSUE THREAD

**Issue by fangyuxi** [ytdl-org/youtube-dl#25672]
## Checklist

- [ x] I've verified that I'm running youtube-dl version **2020.06.06**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
[0;33mWARNING:[0m Writing cache to u'/private/var/mobile/Containers/Data/Application/14660BAA-0E13-42BD-987F-124A7CE1D113/.cache/youtube-dl/youtube-sigfuncs/js_16a691a1_109.json' failed: Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/14660BAA-0E13-42BD-987F-124A7CE1D113/Documents/lib_root/project/youtube_dl/cache.py", line 49, in store
    os.makedirs(os.path.dirname(fn))
  File "/Users/rkm/projects/beeware/Python-Apple-support/2.7/build/iOS/Python-2.7.12-iphonesimulator.x86_64/dist/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Users/rkm/projects/beeware/Python-Apple-support/2.7/build/iOS/Python-2.7.12-iphonesimulator.x86_64/dist/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Users/rkm/projects/beeware/Python-Apple-support/2.7/build/iOS/Python-2.7.12-iphonesimulator.x86_64/dist/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 1] Operation not permitted: '/private/var/mobile/Containers/Data/Application/14660BAA-0E13-42BD-987F-124A7CE1D113/.cache'

[0;33mWARNING:[0m Writing cache to u'/private/var/mobile/Containers/Data/Application/14660BAA-0E13-42BD-987F-124A7CE1D113/.cache/youtube-dl/youtube-sigfuncs/js_16a691a1_105.json' failed: Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/14660BAA-0E13-42BD-987F-124A7CE1D113/Documents/lib_root/project/youtube_dl/cache.py", line 49, in store
    os.makedirs(os.path.dirname(fn))
  File "/Users/rkm/projects/beeware/Python-Apple-support/2.7/build/iOS/Python-2.7.12-iphonesimulator.x86_64/dist/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Users/rkm/projects/beeware/Python-Apple-support/2.7/build/iOS/Python-2.7.12-iphonesimulator.x86_64/dist/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Users/rkm/projects/beeware/Python-Apple-support/2.7/build/iOS/Python-2.7.12-iphonesimulator.x86_64/dist/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 1] Operation not permitted: '/private/var/mobile/Containers/Data/Application/14660BAA-0E13-42BD-987F-124A7CE1D113/.cache'
```


## Description

I use youtube-dl in iOS and call youtube-dl through Python-Apple-Support. So far, it can be used perfect, but it will generate warning and error logs. I don’t know what the reason is? Are some of my options not set correctly? ? These logs are output on the real device.

These logs look like youtube-dl is writing to the cache in some directories, but the written directories do not have permissions. Are some APIs able to set other paths?

I found this option --no-cache-dir but I don't know how to set it programmatically.

Best Regards.

**Comment by dstftw** [comment]
You have no permissions to create directory `.cache` in your `~`.

**Comment by fangyuxi** [comment]
@

**Comment by fangyuxi** [comment]
@dstftw Yes I know that, is there any api to change the path when programming ?

**Comment by dstftw** [comment]
Set `XDG_CACHE_HOME` env variable.

**Comment by fangyuxi** [comment]
@dstftw Thank you. It works.
