### ISSUE TITLE
No video Formats found" error when trying to download from LinkedIn learning

### ISSUE THREAD

**Issue by NathBabs** [ytdl-org/youtube-dl#25679]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-i', '-c', '--all-subs', '--no-warnings', '--console-title', '--batch-file=batch-file.txt', '--max-sleep-interval', '80', '--min-sleep-interval', '60', '-o', '%(playlist_title)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s', '-f', 'best[height<=720]/worst[height>540]']
[debug] Custom config: []
[debug] Command-line args: ['--verbose']
[debug] Batch file urls: ['https://www.linkedin.com/learning/node-js-microservices/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[linkedin:learning:course] Downloading login page
[linkedin:learning:course] Logging in
[linkedin:learning:course] Downloading JSON metadata
[download] Downloading playlist: Node.js: Microservices
[linkedin:learning:course] playlist Node.js: Microservices: Collected 34 video ids (downloading 34 of them)
[download] Downloading video 1 of 34
[linkedin:learning] Downloading login page
[linkedin:learning] Logging in
[linkedin:learning] understand-how-microservices-are-built-and-used-2: Downloading 360p JSON metadata
[linkedin:learning] understand-how-microservices-are-built-and-used-2: Downloading 540p JSON metadata
[linkedin:learning] understand-how-microservices-are-built-and-used-2: Downloading 720p JSON metadata
[linkedin:learning] understand-how-microservices-are-built-and-used-2: Downloading m3u8 information
[debug] Invoking downloader on 'https://files3.lynda.com/secure/courses/5016730/VBR_MP4h264_main_HD720/5016730_00_01_WX30_welcome.mp4?h010PQus74cruEkrF3Y7uujuuC0s3-XnvEMfI4PMaId5sW7NU4vxLStOdT7f7JRznH-hBAgtef2QlOMfNDKODocbslHdkKEm4y8c2GfuE2bUcrZ1tMFcJbRoh8kmZgFNld7ZJL-mfK2iKN1iuL0muWBGI8BFNEW4zyEa09AHMKv40OrjuTcjP7TAOA'
[download] Node.js - Microservices\1 - Introduction\01-Understand how microservices are built and used.mp4 has already been downloaded
[download] 100% of 7.83MiB
[download] Downloading video 2 of 34
[linkedin:learning] what-you-should-know-2: Downloading 360p JSON metadata
[linkedin:learning] what-you-should-know-2: Downloading 540p JSON metadata
[linkedin:learning] what-you-should-know-2: Downloading 720p JSON metadata
[linkedin:learning] what-you-should-know-2: Downloading m3u8 information
[debug] Invoking downloader on 'https://files3.lynda.com/secure/courses/5016730/VBR_MP4h264_main_HD720/5016730_00_02_XR30_what_you_should_know.mp4?eaEuaqcX67dJKEh15hHYmSPfvB3k8WOZ9duk2FzEjuCBES901P5DWC7hrbymyl8QYqTLCduATJbNVnUOIsBw9plv53hRQhEh5rQxsIGUQtaAZJiCcYhr9B3ezbUk86a8yYn16KsagEquDOp_7LCJEjYdBP_DGGgFe7TnPPnR-27B2O4S20UjAv8p0w9UN4BMM3bdQ0MX44E'
[download] Node.js - Microservices\1 - Introduction\02-What you should know.mp4 has already been downloaded
[download] 100% of 2.00MiB
[download] Downloading video 3 of 34
[linkedin:learning] getting-your-tools-ready-2: Downloading 360p JSON metadata
[linkedin:learning] getting-your-tools-ready-2: Downloading 540p JSON metadata
[linkedin:learning] getting-your-tools-ready-2: Downloading 720p JSON metadata
[linkedin:learning] getting-your-tools-ready-2: Downloading m3u8 information
[debug] Invoking downloader on 'https://files3.lynda.com/secure/courses/5016730/VBR_MP4h264_main_HD720/5016730_00_03_XR15_tools.mp4?nycV_NZHnVkR16ptpsB4cJvPgGUpd2GcFgTnANbKDpvA24l2fp2s4V0AKSlM2nQK1oemotZlN8v-X6h6OhDi8iIs1-fOTRiypLk_um2hX4SGXohF5Eih0pFk1FJ9x17G4p_rPIawUieu5CNJLtFC7Q6OKJ0KvBNUwXJJxeg3oqP5Jyn4yY_0LUU'
[download] Node.js - Microservices\1 - Introduction\03-Getting your tools ready.mp4 has already been downloaded
[download] 100% of 5.09MiB
[download] Downloading video 4 of 34
[linkedin:learning] introduction-to-microservices-2: Downloading 360p JSON metadata
[linkedin:learning] introduction-to-microservices-2: Downloading 540p JSON metadata
[linkedin:learning] introduction-to-microservices-2: Downloading 720p JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\linkedin.py", line 127, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 1350, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

It starts throwing no video formats found after just downloading the first chapter. I tried using another tool and it seems the json response changes after the first chapter. The videos in the first chapter have a json property of "url", but subsequent videos in other chapters don't seem to have it.
Please can anyone help with a fix.
https://www.linkedin.com/learning/node-js-microservices/

**Comment by pgenderson** [comment]
Did you figure anything out? I had this same problem (canceled LinkedIn Learning subscription though).

**Comment by NathBabs** [comment]
Nah I haven't, spent hours looking for a fix .I've given up , I'm going to manually to download with IDM.
