### ISSUE TITLE
ERROR: 'content_html'

### ISSUE THREAD

**Issue by numlockkey** [ytdl-org/youtube-dl#25678]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
C:\Users\T5400-3>youtube-dl --download-archive h:\YT-dl\archive.txt -v -i -f bestvideo+(140/bestaudio)/best -o "i:\YT Downloads\%(uploader)s\%(playlist)s\%(playlist_index)s - %(title)s.%(ext)s" -a h:\YT-dl\p.txt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--download-archive', 'h:\\YT-dl\\archive.txt', '-v', '-i', '-f', 'bestvideo+(140/bestaudio)/best', '-o', 'i:\\YT Downloads\\%(uploader)s\\%(playlist)s\\%(playlist_index)s - %(title)s.%(ext)s', '-a', 'h:\\YT-dl\\p.txt']
[debug] Batch file urls: ['https://www.youtube.com/playlist?list=PLWPirh4EWFpHukXICQrDcmjZUa2WlLMAb', 'https://www.youtube.com/playlist?list=PLWPirh4EWFpHTPJZ7ATErCFsKxN0C7St7', 'https://www.youtube.com/playlist?list=PLWPirh4EWFpHJrW1D9UB24wsbM3zx7QMx']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[youtube:playlist] PLWPirh4EWFpHukXICQrDcmjZUa2WlLMAb: Downloading webpage
[download] Downloading playlist: Computer Graphics
[youtube:playlist] PLWPirh4EWFpHukXICQrDcmjZUa2WlLMAb: Downloading page #1
ERROR: 'content_html'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 969, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\youtube.py", line 313, in _entries
KeyError: 'content_html'

[youtube:playlist] PLWPirh4EWFpHTPJZ7ATErCFsKxN0C7St7: Downloading webpage
[download] Downloading playlist: Thermodynamics and Power Plant Engineering for GATE Mechanical Engineering
[youtube:playlist] PLWPirh4EWFpHTPJZ7ATErCFsKxN0C7St7: Downloading page #1
ERROR: 'content_html'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 969, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\youtube.py", line 313, in _entries
KeyError: 'content_html'

[youtube:playlist] PLWPirh4EWFpHJrW1D9UB24wsbM3zx7QMx: Downloading webpage
[download] Downloading playlist: Computer Networks
[youtube:playlist] PLWPirh4EWFpHJrW1D9UB24wsbM3zx7QMx: Downloading page #1
ERROR: 'content_html'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 969, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\youtube.py", line 313, in _entries
KeyError: 'content_html'

## Description

WRITE DESCRIPTION HERE

Starting today I'm getting ERROR: 'content_html' when downloading certain playlists

**Comment by JonathanSum** [comment]
@dstftw I think we should not close it because there is no fix for it. In addition, the for the 2017 patching one, it just does not work at all. It is meaningless to refer people to there. If youtube-dl can not download more than 100 videos, don't we just say it?

**Comment by dstftw** [comment]
Bother to update before posting nonsense.

**Comment by JonathanSum** [comment]
@dstftw  I was about to delete my comment. Can you give me 5 more mins before telling me to update??

**Comment by dstftw** [comment]
🤦
