### ISSUE TITLE
Youtube ERROR: 'content_html'

### ISSUE THREAD

**Issue by McFlat** [ytdl-org/youtube-dl#25675]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v https://www.youtube.com/user/PreciousTestimonies
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/user/PreciousTestimonies']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-8-amd64-x86_64-with-debian-10.4
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:user] PreciousTestimonies: Downloading channel page
[youtube:playlist] UUUFfRr75RtMmT3ArGNZeZgg: Downloading webpage
[download] Downloading playlist: Uploads from Precious Testimonies
[youtube:playlist] UUUFfRr75RtMmT3ArGNZeZgg: Downloading page #1
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 870, in process_ie_result
    extra_info=extra_info)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 969, in process_ie_result
    ie_entries, playliststart, playlistend))
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/youtube.py", line 313, in _entries
    content_html = more['content_html']
KeyError: 'content_html'
```

## Description

Unable to download any videos at all from youtube at this time

**Comment by razor91111** [comment]
I got a similar error today when I tried to download a news channel with a video, although yesterday everything worked like a clock

**Comment by ragymorkos** [comment]
Confirming that I am getting the same error when downloading any channels. Also using most recent version (2020.06.06).

**Comment by TheFrenchGhosty** [comment]
YouTube changed something. Invidious is broken See: https://github.com/omarroth/invidious/issues/1241

YouTube-DL still works for individual videos but ```%(upload_date)s``` doesn't return the date anymore.

**Comment by tuxayo** [comment]
> Unable to download any videos at all from youtube at this time

I tried downloading the first video in the playlist and started downloading. Do you have an example without a playlist?

**Comment by tuxayo** [comment]
> YouTube-DL still works for individual videos but %(upload_date)s doesn't return the date anymore.

Sorry, I missing this.

It has issues with nickname and thumbnail. Did they worked before?

```
WARNING: unable to extract uploader nickname
WARNING: unable to extract video thumbnail

```

**Comment by McFlat** [comment]
what if youtube changes the client-version number in the header? it will break again? seems unreliable but its all we have to work with for now, we have to keep on eye on this to change in the future

**Comment by Kochise** [comment]
Works : https://www.youtube.com/channel/xxx/videos
Breaks : https://www.youtube.com/user/xxx/videos

**Comment by johnr14** [comment]
I am having similar problem on a channel/user with more than 100 videos.
There seems to be a fix available that never was merged and is a recurrent issue #14074 and #14083 if this is the same as reported by others.

[debug] youtube-dl version 2020.06.06
[debug] Python version 3.8.3 (CPython) - Linux-5.6.14-300.fc32.x86_64-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3

**Comment by mohammadmasoumi** [comment]
I had the same issue with `python3.8`. 

So how I fixed that used a `python3.7` virtual env

**Comment by Xatenev** [comment]
Can we get a new windows release with this fix?

**Comment by Uraharadono** [comment]
Having same issue here as well:

```
[07/20/20 01:35:54] ERROR: 'content_html'
[07/20/20 01:35:54] Traceback (most recent call last):
[07/20/20 01:35:54]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 807, in extract_info
[07/20/20 01:35:54]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 968, in process_ie_result
[07/20/20 01:35:54]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\youtube.py", line 314, in _entries
[07/20/20 01:35:54] KeyError: 'content_html'
[07/20/20 01:35:54] 
```

**Comment by jrdutra** [comment]
Its just execute the youtube-dl as sudo in linux, like this:

`sudo youtube-dl https://www.youtube.com/playlist?list=PLAYLIST-CODE-HERE`
