### ISSUE TITLE
[abc.com] Unable to extract post URL

### ISSUE THREAD

**Issue by jaylweb** [ytdl-org/youtube-dl#25688]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: ['--no-part', '--external-downloader-args', '-loglevel fatal -stats', '--no-check-certificate', '--cookies', 'cookies.txt', '-o', '%(series)s - s%(season_number)02de%(episode_number)02d.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['--get-filename', '--ap-mso', 'DTV', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--verbose', 'https://abc.com/shows/marvels-agents-of-shield/episode-guide/season-07/01-the-new-deal']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-92963-g1ea5529dd2, ffprobe N-92963-g1ea5529dd2, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\go.py", line 187, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\adobepass.py", line 1516, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\adobepass.py", line 1365, in post_form
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 1014, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Unable to download videos from abc.com.  I am able to watch the video in Chrome.  I have a current export of my cookies.txt file.  I have the latest version of youtube-dl.  

I get the same results from the following URLs:
https://abc.com/shows/marvels-agents-of-shield/episode-guide/season-07/01-the-new-deal
https://abc.com/shows/marvels-agents-of-shield/episode-guide/season-07/02-know-your-onions
https://abc.com/shows/marvels-agents-of-shield/episode-guide/season-07/03-alien-commies-from-the-future
https://abc.com/shows/dont/episode-guide/season-01/01-dont-be-a-wiseguy

I am willing to test and help anyway that I can.  Thanks.

**Comment by jaylweb** [comment]
What is this a duplicate of?  I searched and could not find this issue with abc.com
