### ISSUE TITLE
EmbedthumnailPPError with atomic parsley

### ISSUE THREAD

**Issue by silverhikari** [ytdl-org/youtube-dl#25684]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.06.16**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--embed-thumbnail', '-o', '%(title)s-%(uploader)s.%(ext)s', '-x', '-f', 'bestaudio[ext=m4a]/bestaudio[ext=opus]', '--audio-quality', '0', 'https://www.youtube.com/watch?v=ZpeqOKnW3es', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16
[debug] Python version 3.8.2 (CPython) - Linux-5.4.0-33-lowlatency-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[youtube] ZpeqOKnW3es: Downloading webpage
[youtube] ZpeqOKnW3es: Downloading thumbnail ...
[youtube] ZpeqOKnW3es: Writing thumbnail to: Saving the Vampire Roommate [F4M][audio][roleplay][series]-Urban Nymph.webp
[debug] Invoking downloader on 'https://r8---sn-8xgp1vo-2ial.googlevideo.com/videoplayback?expire=1592280736&ei=QPLnXvO1FpDU8wSiy5zACg&ip=108.2.115.149&id=o-AKKYsOyWw__W6p1wxsuI7cH1Kwt8rIzfcGyOTXFETcNN&itag=140&source=youtube&requiressl=yes&mh=qK&mm=31%2C29&mn=sn-8xgp1vo-2ial%2Csn-ab5sznle&ms=au%2Crdu&mv=m&mvi=7&pl=16&initcwndbps=1740000&vprv=1&mime=audio%2Fmp4&gir=yes&clen=17422641&dur=1076.500&lmt=1592238619407755&mt=1592259033&fvip=4&keepalive=yes&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgZcr7hBjoQKLu13b33GrIY1RtvYVZoanHXIlCG6eoydUCIQDHZ6QG2TJ-fYuESkyVl-gw1ZTI38qpEP3gWETMS2SBxA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgH5pMMk8OLLPEA4FNaPZTjGWzgj5Gt6fAc2Y68QCaWyACID6m1ULWYlmaX4JLBlSY5Js_7xW8ZSALQaiMCE0z79FZ&ratebypass=yes'
[download] Saving the Vampire Roommate [F4M][audio][roleplay][series]-Urban Nymph.m4a has already been downloaded
[download] 100% of 16.60MiB
[ffmpeg] Correcting container in "Saving the Vampire Roommate [F4M][audio][roleplay][series]-Urban Nymph.m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Saving the Vampire Roommate [F4M][audio][roleplay][series]-Urban Nymph.m4a' -c copy -f mp4 'file:Saving the Vampire Roommate [F4M][audio][roleplay][series]-Urban Nymph.temp.m4a'
[debug] ffmpeg command line: ffprobe -show_streams 'file:Saving the Vampire Roommate [F4M][audio][roleplay][series]-Urban Nymph.m4a'
[ffmpeg] Post-process file Saving the Vampire Roommate [F4M][audio][roleplay][series]-Urban Nymph.m4a exists, skipping
[atomicparsley] Adding thumbnail to "Saving the Vampire Roommate [F4M][audio][roleplay][series]-Urban Nymph.m4a"
[debug] AtomicParsley command line: AtomicParsley 'Saving the Vampire Roommate [F4M][audio][roleplay][series]-Urban Nymph.m4a' --artwork 'Saving the Vampire Roommate [F4M][audio][roleplay][series]-Urban Nymph.webp' -o 'Saving the Vampire Roommate [F4M][audio][roleplay][series]-Urban Nymph.temp.m4a'
ERROR: 
Traceback (most recent call last):
  File "/home/silver/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2065, in post_process
    files_to_delete, info = pp.run(info)
  File "/home/silver/.local/lib/python3.8/site-packages/youtube_dl/postprocessor/embedthumbnail.py", line 79, in run
    raise EmbedThumbnailPPError(msg)
youtube_dl.postprocessor.embedthumbnail.EmbedThumbnailPPError
```

## Description

when embedding thumbnail using the version 2020.06.16 atomic parsley gives the supplied error with youtube-dl's postprocessor

**Comment by gcost12** [comment]
same issue here, with the --embed-thumbnail option an empty audio file is resulted

**Comment by gcost12** [comment]
still the same issue with version 2020.06.16.1, now just getting in addition the message "ERROR: Conversion failed!" after the message "[ffmpeg] Adding thumbnail to ..." and the file is not empty, but no embed thumbnail

**Comment by githubjohn25** [comment]
My current workaround is the following 3 steps. I have installed youtube-dl, atomicparsley and ffmpeg in windows 10. Example for this mix https://www.youtube.com/watch?v=z8CDcmo48RE .

1. download m4a with cover, creates errormessage but picture is saved:
`youtube-dl -f bestaudio[ext=m4a] --embed-thumbnail https://www.youtube.com/watch?v=z8CDcmo48RE`
2. convert .webp to .png
`ffmpeg.exe -i "Paul van Dyk's VONYC Sessions 709-z8CDcmo48RE.webp" "Paul van Dyk's VONYC Sessions 709-z8CDcmo48RE.png"`
3. put .png into .m4a
`AtomicParsley.exe "Paul van Dyk's VONYC Sessions 709-z8CDcmo48RE.m4a" --artwork "Paul van Dyk's VONYC Sessions 709-z8CDcmo48RE.png"`

Would be great to get a shorter way. And i have to set ID3tags manually, as youtube-dl only is able to set the first track of the mix as ID3tag afaik.

**Comment by alvvays-debug** [comment]
Having the same issue today too!
