### ISSUE TITLE
extractor/niconico.py: failed with invalid_v1 error

### ISSUE THREAD

**Issue by jg1uaa** [ytdl-org/youtube-dl#25702]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
uaa@framboise:~/z/youtube-dl/build/lib$ python3.7 youtube_dl -v -u USERNAME -p PASSWORD -r 300k https://www.nicovideo.jp/watch/so37002707
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '-r', '300k', 'https://www.nicovideo.jp/watch/so37002707']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.7.7 (CPython) - OpenBSD-6.7-amd64-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4-git-fa8646da
[debug] Proxy map: {}
[niconico] Logging in
[niconico] so37002707: Downloading webpage
[niconico] so37002707: Downloading flv info
ERROR: niconico reports error: invalid_v1
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/niconico.py", line 288, in _real_extract
    video_real_url = api_data['video']['smileInfo']['url']
KeyError: 'video'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/niconico.py", line 288, in _real_extract
    video_real_url = api_data['video']['smileInfo']['url']
KeyError: 'video'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/niconico.py", line 305, in _real_extract
    self.IE_NAME, flv_info['error'][0]), expected=True)
youtube_dl.utils.ExtractorError: niconico reports error: invalid_v1

uaa@framboise:~/z/youtube-dl/build/lib$
```

## Description

I could not download recent video on nicovideo. Old one was no problem like this.

```
uaa@framboise:~/z/youtube-dl/build/lib$ python3.7 youtube_dl -v -u USERNAME -p PASSWORD -r 300k https://www.nicovideo.jp/watch/sm33716741
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '-r', '300k', 'https://www.nicovideo.jp/watch/sm33716741']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.7.7 (CPython) - OpenBSD-6.7-amd64-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4-git-fa8646da
[debug] Proxy map: {}
[niconico] Logging in
[niconico] sm33716741: Downloading webpage
[niconico] sm33716741: Downloading JSON metadata for h264_1800kbps_720p-aac_128kbps
[niconico] sm33716741: Downloading JSON metadata for h264_1600kbps_540p-aac_128kbps
[niconico] sm33716741: Downloading JSON metadata for h264_600kbps_360p-aac_128kbps
[niconico] sm33716741: Downloading JSON metadata for h264_300kbps_360p-aac_128kbps
[niconico] sm33716741: Downloading JSON metadata for h264_1800kbps_720p-aac_64kbps
[niconico] sm33716741: Downloading JSON metadata for h264_1600kbps_540p-aac_64kbps
[niconico] sm33716741: Downloading JSON metadata for h264_600kbps_360p-aac_64kbps
[niconico] sm33716741: Downloading JSON metadata for h264_300kbps_360p-aac_64kbps
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://vodedge011.dmc.nico/vod/ht2_nicovideo/nicovideo-sm33716741_52cd4d08e5af30e0c0ad0dbfa5e84582472312b74c1b1601c61fdd6e9a563d5f?ht2_nicovideo=4915839.478yqiwf21_qc2l8d_122pohnsfayto'
[download] Destination: ｵｰｶﾞﾏﾝと見る修羅の国の戦士-sm33716741.mp4
```

I tweeted at https://twitter.com/uaa/status/1273226483977207808 (see attached photo), JSON from old video returns "archive_h264_1600kbps_540p" contains bitrate. But new one returns "archive_h264_720p", no rate.

I think these difference made the problem. hope this help.

**Comment by jg1uaa** [comment]
sorry,  URL problem. close this.
