### ISSUE TITLE
Youtube extractor: "token" not in video info for unknown reason

### ISSUE THREAD

**Issue by robhol** [ytdl-org/youtube-dl#25712]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe https://www.youtube.com/watch?v=PukuQPUKfyU --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=PukuQPUKfyU', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.02.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-91510-gd134b8d85f
[debug] Proxy map: {}
[youtube] PukuQPUKfyU: Downloading webpage
[youtube] PukuQPUKfyU: Downloading video info webpage
ERROR: PukuQPUKfyU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\youtube.py", line 2415, in _real_extract
youtube_dl.utils.ExtractorError: PukuQPUKfyU: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Nothing more to really write. Wanted to download. Didn't work. Now I'm here.

**Comment by Zirro** [comment]
Your version of youtube-dl is several months old. As the error message says - try with the latest version.

**Comment by robhol** [comment]
Right, missed that in the log because I literally just did youtube-dl -U without any errors, which might be an issue in its own right.
