### ISSUE TITLE
ERROR: An extractor error has occurred. (caused by KeyError(1));

### ISSUE THREAD

**Issue by Midorina** [ytdl-org/youtube-dl#25719]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```py
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.2 (CPython) - Linux-4.15.0-96-generic-x86_64-with-glibc2.27
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 2995, in _real_extract
    return self._get_n_results(query, 1)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 3180, in _get_n_results
    html_content = data[1]['body']['content']
KeyError: 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 2995, in _real_extract
    return self._get_n_results(query, 1)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 3180, in _get_n_results
    html_content = data[1]['body']['content']
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 543, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError(1)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

After attempting to use a cookies file, this error started to raise.
If you want to reproduce this issue, simply use a `cookiefile` and attempt to `extract_info()` of any video.

**Comment by Midorina** [comment]
May I ask why this got closed? Could you please provide reasons while closing issues? Thank you.

**Comment by dstftw** [comment]
Bother to read new issue template.

**Comment by Midorina** [comment]
> Bother to read new issue template.

I read everything in the template. What was missing in my issue?

**Comment by dstftw** [comment]
Are you trolling or what?

```
## Verbose log

<!--
Provide the complete verbose output of youtube-dl that clearly demonstrates the problem.
Add the `-v` flag to your command line you run youtube-dl with (`youtube-dl -v <your command line>`), copy the WHOLE output and insert it below. It should look similar to this:
 [debug] System config: []
 [debug] User config: []
 [debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
 [debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
 [debug] youtube-dl version 2020.06.16.1
 [debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
 [debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
 [debug] Proxy map: {}
 <more lines>
-->
```

**Comment by Midorina** [comment]
I am using the youtube-dl library in my Python application and the 'verbose' arg was giving me all of that above. I guess I'll reproduce this issue in the command line and post the issue again. Thank you.
