### ISSUE TITLE
Youtube only ERROR: Conversion failed! TikTok ok

### ISSUE THREAD

**Issue by amarCosmospace** [ytdl-org/youtube-dl#25714]
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
aze@aze:~/web$ youtube-dl -o 'e943a36662272ab14aa5f8456eb752c6.%(ext)s' -x "https://www.youtube.com/watch?v=AFnfAyY0Ock" --no-part --prefer-ffmpeg --embed-thumbnail --add-metadata --postprocessor-args "-id3v2_version 3" --audio-quality 94K --audio-format mp3 --restrict-filenames  -r 1500k --write-info-json  --proxy http://bd5jf:e96np8so@162.244.132.210:6027 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-o', u'e943a36662272ab14aa5f8456eb752c6.%(ext)s', u'-x', u'https://www.youtube.com/watch?v=AFnfAyY0Ock', u'--no-part', u'--prefer-ffmpeg', u'--embed-thumbnail', u'--add-metadata', u'--postprocessor-args', u'-id3v2_version 3', u'--audio-quality', u'94K', u'--audio-format', u'mp3', u'--restrict-filenames', u'-r', u'1500k', u'--write-info-json', u'--proxy', u'http://bd5jf:e96np8so@162.244.132.210:6027', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.2.2-0york0, ffprobe 4.2.2-0york0
[debug] Proxy map: {u'http': u'http://bd5jf:e96np8so@162.244.132.210:6027', u'https': u'http://bd5jf:e96np8so@162.244.132.210:6027'}
[youtube] AFnfAyY0Ock: Downloading webpage
[youtube] {18} signature length 105, html5 player 0c5285fd
[youtube] {135} signature length 105, html5 player 0c5285fd
[youtube] {244} signature length 105, html5 player 0c5285fd
[youtube] {397} signature length 105, html5 player 0c5285fd
[youtube] {134} signature length 105, html5 player 0c5285fd
[youtube] {243} signature length 105, html5 player 0c5285fd
[youtube] {396} signature length 105, html5 player 0c5285fd
[youtube] {133} signature length 101, html5 player 0c5285fd
[youtube] {242} signature length 105, html5 player 0c5285fd
[youtube] {395} signature length 105, html5 player 0c5285fd
[youtube] {160} signature length 105, html5 player 0c5285fd
[youtube] {278} signature length 105, html5 player 0c5285fd
[youtube] {394} signature length 101, html5 player 0c5285fd
[youtube] {140} signature length 105, html5 player 0c5285fd
[youtube] {249} signature length 101, html5 player 0c5285fd
[youtube] {250} signature length 101, html5 player 0c5285fd
[youtube] {251} signature length 105, html5 player 0c5285fd
[info] Writing video description metadata as JSON to: e943a36662272ab14aa5f8456eb752c6.info.json
[youtube] AFnfAyY0Ock: Downloading thumbnail ...
[youtube] AFnfAyY0Ock: Writing thumbnail to: e943a36662272ab14aa5f8456eb752c6.jpg
[debug] Invoking downloader on u'https://r5---sn-a5meknl6.googlevideo.com/videoplayback?expire=1592495098&ei=mjfrXqmHCJiFkwaNoxI&ip=45.42.87.30&id=o-AFADyAcDpsyWAEtUny4fdqYCBFoWEX_5XhNc6bdagbd7&itag=251&source=youtube&requiressl=yes&mh=MB&mm=31%2C26&mn=sn-a5meknl6%2Csn-n4v7sney&ms=au%2Conr&mv=u&mvi=4&pl=22&vprv=1&mime=audio%2Fwebm&gir=yes&clen=4382801&dur=239.941&lmt=1547745634829790&mt=1592472942&fvip=5&keepalive=yes&c=WEB&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRQIgTIbWTu8ldwSvy8TxtBzqNiHolgLbJbPWGzlkWJ_okYICIQCavbRjmsuKkYGP6dYhIB3wR-vxqNKKBGoxG3fWOn3sZA%3D%3D&sig=AOq0QJ8wRQIgPkRBqIh_4GA82n4hqWF2ZxsWau8yGg-CoP-K9cRWgWgCIQD1jRXvgz4K0S4i8r5TofMbTK-E9h5tdXytOe25dQYNQA==&ratebypass=yes'
[download] Destination: e943a36662272ab14aa5f8456eb752c6.webm
[download] 100% of 4.18MiB in 00:03
[debug] ffmpeg command line: ffprobe -show_streams 'file:e943a36662272ab14aa5f8456eb752c6.webm'
[ffmpeg] Destination: e943a36662272ab14aa5f8456eb752c6.mp3
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:e943a36662272ab14aa5f8456eb752c6.webm' -vn -acodec libmp3lame '-b:a' 94k -id3v2_version 3 'file:e943a36662272ab14aa5f8456eb752c6.mp3'
Deleting original file e943a36662272ab14aa5f8456eb752c6.webm (pass -k to keep)
[ffmpeg] Adding metadata to 'e943a36662272ab14aa5f8456eb752c6.mp3'
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:e943a36662272ab14aa5f8456eb752c6.mp3' -c copy -metadata 'comment=A beatifull and amazing song, to remember.
Una cancion muy romantica y espectacular para recordar.' -metadata 'description=A beatifull and amazing song, to remember.
Una cancion muy romantica y espectacular para recordar.' -metadata 'artist=UB40' -metadata 'title=Kingston Town' -metadata 'date=20100622' -metadata 'purl=https://www.youtube.com/watch?v=AFnfAyY0Ock' -id3v2_version 3 'file:e943a36662272ab14aa5f8456eb752c6.temp.mp3'
[ffmpeg] Adding thumbnail to "e943a36662272ab14aa5f8456eb752c6.mp3"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:e943a36662272ab14aa5f8456eb752c6.mp3' -i 'file:e943a36662272ab14aa5f8456eb752c6.jpg' -c copy -map 0 -map 1 '-metadata:s:v' 'title="Album cover"' '-metadata:s:v' 'comment="Cover (Front)"' -id3v2_version 3 'file:e943a36662272ab14aa5f8456eb752c6.temp.mp3'
ERROR: Conversion failed!
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2065, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/embedthumbnail.py", line 51, in run
    self.run_ffmpeg_multiple_files([filename, thumbnail_filename], temp_filename, options)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: Conversion failed!

```

## Description

Since the last update to youtube-dl is up-to-date (2020.06.16.1) this appears.

The version of ffmpeg has not changed.

And i've tested with another tiktok video it worked well

**Comment by cancerousname69** [comment]
Not a youtube-dl issue, but a FFmpeg one. Also, instead of using -x, it is often better to choose some of the audio formats available, for example:
```
youtube-dl -f'bestaudio[acodec=opus]' <URL>
```

**Comment by amarCosmospace** [comment]
i'm not sure, but using your format i cant download it on mp3 format, it's webm format. Any idea ?

**Comment by CodingKoopa** [comment]
I'm having this issue too. I ran `youtube-dl --verbose -x --audio-format mp3 --embed-thumbnail 'https://youtu.be/MShbP3OpASA'` to get the ffmpeg command used. Here is the output of that exact ffmpeg command, if it helps:
```sh
$ ffmpeg -y -loglevel repeat+info -i 'file:Aalto Talk with Linus Torvalds [Full-length]-MShbP3OpASA.mp3' -i 'file:Aalto Talk with Linus Torvalds [Full-length]-MShbP3OpASA.webp' -c copy -map 0 -map 1 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (Front)"' 'file:Aalto Talk with Linus Torvalds [Full-length]-MShbP3OpASA.temp.mp3'
ffmpeg version n4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mp3, from 'file:Aalto Talk with Linus Torvalds [Full-length]-MShbP3OpASA.mp3':
  Metadata:
    encoder         : Lavf58.29.100
  Duration: 01:03:55.92, start: 0.000000, bitrate: 79 kb/s
    Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 79 kb/s
    Metadata:
      encoder         : Lavc58.54
Input #1, webp_pipe, from 'file:Aalto Talk with Linus Torvalds [Full-length]-MShbP3OpASA.webp':
  Duration: N/A, bitrate: N/A
    Stream #1:0: Video: webp, yuv420p(tv, bt470bg/unknown/unknown), 1280x720, 25 tbr, 25 tbn, 25 tbc
Output #0, mp3, to 'file:Aalto Talk with Linus Torvalds [Full-length]-MShbP3OpASA.temp.mp3':
  Metadata:
    TSSE            : Lavf58.29.100
    Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 79 kb/s
    Metadata:
      encoder         : Lavc58.54
    Stream #0:1: Video: webp, yuv420p(tv, bt470bg/unknown/unknown), 1280x720, q=2-31, 25 tbr, 25 tbn, 25 tbc
    Metadata:
      title           : "Album cover"
      comment         : "Cover (Front)"
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[mp3 @ 0x55cb85e842c0] No mimetype is known for stream 1, cannot write an attached picture.
av_interleaved_write_frame(): Invalid argument
[mp3 @ 0x55cb85e842c0] No packets were sent for some of the attached pictures.
frame=    1 fps=0.0 q=-1.0 Lsize=       0kB time=00:00:00.04 bitrate=  95.4kbits/s speed= 188x    
video:38kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
```
I can confirm that the youtube-dl operation works on version `2020.06.06` but not on `2020.06.16`. Thanks.
