### ISSUE TITLE
Periscope: Can't download with primary URLs, invalid format code

### ISSUE THREAD

**Issue by altimumdelta** [ytdl-org/youtube-dl#25746]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.pscp.tv/w/1yNGaBonYnQJj']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg git-2020-01-21-fc6fde2, ffprobe git-2020-01-21-fc6fde2
[debug] Proxy map: {}
[periscope] 1yNGaBonYnQJj: Downloading JSON metadata
[periscope] 1yNGaBonYnQJj: Downloading m3u8 information
[info] Available formats for 1yNGaBonYnQJj:
format code  extension  resolution note
replay-500   mp4        480x270     500k , avc1.640015, 28.986fps, mp4a.40.2
replay-1000  mp4        848x480    1000k , avc1.64001f, 28.986fps, mp4a.40.2
replay-2000  mp4        1280x720   2000k , avc1.64001f, 28.986fps, mp4a.40.2
replay-4000  mp4        1280x720   4000k , avc1.64001f, 28.986fps, mp4a.40.2 (best)
```
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.pscp.tv/arstechnica/1yNGaBonYnQJj']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg git-2020-01-21-fc6fde2, ffprobe git-2020-01-21-fc6fde2
[debug] Proxy map: {}
[periscope] 1yNGaBonYnQJj: Downloading JSON metadata
[periscope] 1yNGaBonYnQJj: Downloading m3u8 information
[info] Available formats for 1yNGaBonYnQJj:
format code  extension  resolution note
replay-500   mp4        480x270     500k , avc1.640015, 28.986fps, mp4a.40.2
replay-1000  mp4        848x480    1000k , avc1.64001f, 28.986fps, mp4a.40.2
replay-2000  mp4        1280x720   2000k , avc1.64001f, 28.986fps, mp4a.40.2
replay-4000  mp4        1280x720   4000k , avc1.64001f, 28.986fps, mp4a.40.2 (best)
```
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'replay-4000', 'https://www.pscp.tv/arstechnica/1yNGaBonYnQJj']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg git-2020-01-21-fc6fde2, ffprobe git-2020-01-21-fc6fde2
[debug] Proxy map: {}
[periscope] 1yNGaBonYnQJj: Downloading JSON metadata
[periscope] 1yNGaBonYnQJj: Downloading m3u8 information
[debug] Invoking downloader on 'https://prod-ec-us-east-1.video.periscope.tv/Transcoding/v1/hls/hquH_cbvcgkrGpzbzQaZ17lsCZUaUcoxSusoIzN6OYtv0Hurbo3j_YpcCxbycbE2SuBWtCywnnpDpOUAXrwQUw/transcode/us-east-1/periscope-replay-direct-prod-us-east-1-public/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJIZWlnaHQiOjcyMCwiS2JwcyI6NDAwMCwiV2lkdGgiOjEyODB9._lwcUhHeo_ZcTvj7C11_mnFYldhjIywdpF0kk3OHkBE/playlist_16854414256280746052.m3u8?type=replay'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1387
[download] Destination: Ars Technica - Alright #CommandAndConquer fans, @samred is beginning his Q&A with EA's lead dev for the recent remaster, Jim Vessella. Tune in, bring your Qs - https -_arstechnica.com_gaming_2020_06_ready-commander-join-us-tuesday-for-a-live-command-conquer-remaster-qa-1yNGaBonYnQJj.mp4
ERROR: unable to download video data: [Errno 22] Invalid argument: "Ars Technica - Alright #CommandAndConquer fans, @samred is beginning his Q&A with EA's lead dev for the recent remaster, Jim Vessella. Tune in, bring your Qs - https -_arstechnica.com_gaming_2020_06_ready-commander-join-us-tuesday-for-a-live-command-conquer-remaster-qa-1yNGaBonYnQJj.mp4.ytdl"
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 1926, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\downloader\hls.py", line 110, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\downloader\fragment.py", line 69, in _prepare_and_start_frag_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\downloader\fragment.py", line 179, in _prepare_frag_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\downloader\fragment.py", line 87, in _write_ytdl_file
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\utils.py", line 2054, in sanitize_open
OSError: [Errno 22] Invalid argument: "Ars Technica - Alright #CommandAndConquer fans, @samred is beginning his Q&A with EA's lead dev for the recent remaster, Jim Vessella. Tune in, bring your Qs - https -_arstechnica.com_gaming_2020_06_ready-commander-join-us-tuesday-for-a-live-command-conquer-remaster-qa-1yNGaBonYnQJj.mp4.ytdl"
```

## Description

The primary links do not function, while the querying seems to work and displays a list of available downloads and their quality format codes, the codes do not work and are invalid. 

It did work by manually inspecting and finding out the .m3u8 URL and using the different codes it provided. Notice the omission of "replay-" from the codes.

## Verbose log - Working Case

```
C:\Program Files Manual\YoutubeDL>youtube-dl -v -F https://prod-fastly-us-east-1.video.pscp.tv/Transcoding/v1/hls/hquH_cbvcgkrGpzbzQaZ17lsCZUaUcoxSusoIzN6OYtv0Hurbo3j_YpcCxbycbE2SuBWtCywnnpDpOUAXrwQUw/non_transcode/us-east-1/periscope-replay-direct-prod-us-east-1-public/master_dynamic_16854414256280746052.m3u8?type=replay
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://prod-fastly-us-east-1.video.pscp.tv/Transcoding/v1/hls/hquH_cbvcgkrGpzbzQaZ17lsCZUaUcoxSusoIzN6OYtv0Hurbo3j_YpcCxbycbE2SuBWtCywnnpDpOUAXrwQUw/non_transcode/us-east-1/periscope-replay-direct-prod-us-east-1-public/master_dynamic_16854414256280746052.m3u8?type=replay']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg git-2020-01-21-fc6fde2, ffprobe git-2020-01-21-fc6fde2
[debug] Proxy map: {}
[generic] master_dynamic_16854414256280746052: Requesting header
[generic] master_dynamic_16854414256280746052: Downloading m3u8 information
[info] Available formats for master_dynamic_16854414256280746052:
format code  extension  resolution note
500          mp4        480x270     500k , avc1.640015, 28.986fps, mp4a.40.2
1000         mp4        848x480    1000k , avc1.64001f, 28.986fps, mp4a.40.2
2000         mp4        1280x720   2000k , avc1.64001f, 28.986fps, mp4a.40.2
4000         mp4        1280x720   4000k , avc1.64001f, 28.986fps, mp4a.40.2 (best)
```

**Comment by altimumdelta** [comment]
What is it a duplicate of, I didn't find it.

**Comment by altimumdelta** [comment]
I don't really find anything that makes this a duplicate, what ??? There's not much issues with periscope anyway.

**Comment by remitamine** [comment]
the issue is not related specifically to periscope, it's caused by the long title.

**Comment by altimumdelta** [comment]
Oh okay, thanks.
