### ISSUE TITLE
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug

### ISSUE THREAD

**Issue by hedbonker** [ytdl-org/youtube-dl#25748]
Running version 1.0.8

Getting this error on a lot of Youtube videos.  Here is the log:

2020-06-21 09:32:51.700 MVRP[16782:148215] launching task 0x600001d38e80
2020-06-21 09:32:51.705 MVRP[16782:148215] task 0x600001d38e80 launched
2020-06-21 09:32:52.495 MVRP[16782:148215] <ERROR 0x600001d38e80> [debug] System config: []
2020-06-21 09:32:52.495 MVRP[16782:148215] <ERROR 0x600001d38e80> [debug] User config: []
2020-06-21 09:32:52.495 MVRP[16782:148215] <ERROR 0x600001d38e80> 
2020-06-21 09:32:52.496 MVRP[16782:148215] <ERROR 0x600001d38e80> [debug] Custom config: []
2020-06-21 09:32:52.496 MVRP[16782:148215] <ERROR 0x600001d38e80> [debug] Command-line args: [u'--ignore-config', u'--no-color', u'--no-call-home', u'--newline', u'--verbose', u'--no-playlist', u'--prefer-ffmpeg', u'--ffmpeg-location', u'/Applications/Mac VideoRipper Pro.app/Contents/Resources/ffmpeg', u'--merge-output-format', u'mp4', u'-f', u'bestaudio[ext=m4a]/bestaudio', u'https://www.youtube.com/watch?v=ubvYQxTXO3U']
2020-06-21 09:32:52.496 MVRP[16782:148215] <ERROR 0x600001d38e80> 
2020-06-21 09:32:52.503 MVRP[16782:148215] <ERROR 0x600001d38e80> [debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII
2020-06-21 09:32:52.503 MVRP[16782:148215] <ERROR 0x600001d38e80> [debug] youtube-dl version 2020.03.08
2020-06-21 09:32:52.503 MVRP[16782:148215] <ERROR 0x600001d38e80> 
2020-06-21 09:32:52.524 MVRP[16782:148215] <ERROR 0x600001d38e80> [debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
2020-06-21 09:32:52.524 MVRP[16782:148215] <ERROR 0x600001d38e80> 
2020-06-21 09:32:53.061 MVRP[16782:148215] <ERROR 0x600001d38e80> [debug] exe versions: ffmpeg 3.2.2-tessus, ffprobe 3.2.2-tessus, rtmpdump 2.4
2020-06-21 09:32:53.061 MVRP[16782:148215] <ERROR 0x600001d38e80> [debug] Proxy map: {}
2020-06-21 09:32:53.061 MVRP[16782:148215] <ERROR 0x600001d38e80> 
2020-06-21 09:32:53.385 MVRP[16782:148215] <OUTPUT 0x600001d38e80> [youtube] ubvYQxTXO3U: Downloading webpage
2020-06-21 09:32:53.385 MVRP[16782:148215] <OUTPUT 0x600001d38e80> 
2020-06-21 09:32:54.137 MVRP[16782:148215] <OUTPUT 0x600001d38e80> [youtube] Downloading just video ubvYQxTXO3U because of --no-playlist
2020-06-21 09:32:54.137 MVRP[16782:148215] <OUTPUT 0x600001d38e80> 
2020-06-21 09:32:54.175 MVRP[16782:148215] <ERROR 0x600001d38e80> ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2020-06-21 09:32:54.175 MVRP[16782:148215] <ERROR 0x600001d38e80> 
2020-06-21 09:32:54.179 MVRP[16782:148215] <ERROR 0x600001d38e80> Traceback (most recent call last):
2020-06-21 09:32:54.179 MVRP[16782:148215] <ERROR 0x600001d38e80>   File "/var/folders/sm/595blnp15l11b3zxhf9csq880000gn/T/mvrp.xCC5w1/youtube_dl/YoutubeDL.py", line 797, in extract_info
2020-06-21 09:32:54.179 MVRP[16782:148215] <ERROR 0x600001d38e80>     ie_result = ie.extract(url)
2020-06-21 09:32:54.180 MVRP[16782:148215] <ERROR 0x600001d38e80>   File "/var/folders/sm/595blnp15l11b3zxhf9csq880000gn/T/mvrp.xCC5w1/youtube_dl/extractor/common.py", line 530, in extract
2020-06-21 09:32:54.180 MVRP[16782:148215] <ERROR 0x600001d38e80>     ie_result = self._real_extract(url)
2020-06-21 09:32:54.180 MVRP[16782:148215] <ERROR 0x600001d38e80>   File "/var/folders/sm/595blnp15l11b3zxhf9csq880000gn/T/mvrp.xCC5w1/youtube_dl/extractor/youtube.py", line 2364, in _real_extract
2020-06-21 09:32:54.180 MVRP[16782:148215] <ERROR 0x600001d38e80>     self._sort_formats(formats)
2020-06-21 09:32:54.180 MVRP[16782:148215] <ERROR 0x600001d38e80>   File "/var/folders/sm/595blnp15l11b3zxhf9csq880000gn/T/mvrp.xCC5w1/youtube_dl/extractor/common.py", line 1327, in _sort_formats
2020-06-21 09:32:54.180 MVRP[16782:148215] <ERROR 0x600001d38e80>     raise ExtractorError('No video formats found')
2020-06-21 09:32:54.180 MVRP[16782:148215] <ERROR 0x600001d38e80> ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2020-06-21 09:32:54.180 MVRP[16782:148215] <ERROR 0x600001d38e80> 
2020-06-21 09:32:54.180 MVRP[16782:148215] <ERROR 0x600001d38e80> 
2020-06-21 09:32:54.199 MVRP[16782:148353] task 0x600001d38e80 done
2020-06-21 09:33:01.548 MVRP[16782:148215] downloadUrl: https://www.youtube.com/watch?v=ubvYQxTXO3U ripMode: 0
2020-06-21 09:33:01.548 MVRP[16782:148215] s: https://www.youtube.com/watch?v=ubvYQxTXO3U d: /Users/mikee/Desktop/Youtube Video Captures
2020-06-21 09:33:01.548 MVRP[16782:148626] version 1.0.8 toolOriVersion 1.0.8
2020-06-21 09:33:01.548 MVRP[16782:148626] time since last update check: 10
2020-06-21 09:33:01.800 MVRP[16782:148215] osv 10.14.6
2020-06-21 09:33:01.800 MVRP[16782:148215] task env: {
    "Apple_PubSub_Socket_Render" = "/private/tmp/com.apple.launchd.iSbvx2j5kN/Render";
    HOME = "/Users/mikee";
    LOGNAME = mikee;
    PATH = "/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Mac VideoRipper Pro.app/Contents/Resources";
    SHELL = "/bin/bash";
    "SSH_AUTH_SOCK" = "/private/tmp/com.apple.launchd.Mmxu0gQun1/Listeners";
    TMPDIR = "/var/folders/sm/595blnp15l11b3zxhf9csq880000gn/T/";
    USER = mikee;
    "XPC_FLAGS" = 0x0;
    "XPC_SERVICE_NAME" = "com.mvrp.MVRP.38556";
    "__CF_USER_TEXT_ENCODING" = "0x1F5:0x0:0x0";
}
2020-06-21 09:33:01.800 MVRP[16782:148215] launching task 0x600001d3a600
2020-06-21 09:33:01.806 MVRP[16782:148215] task 0x600001d3a600 launched
2020-06-21 09:33:02.588 MVRP[16782:148215] <ERROR 0x600001d3a600> [debug] System config: []
2020-06-21 09:33:02.588 MVRP[16782:148215] <ERROR 0x600001d3a600> [debug] User config: []
2020-06-21 09:33:02.588 MVRP[16782:148215] <ERROR 0x600001d3a600> 
2020-06-21 09:33:02.588 MVRP[16782:148215] <ERROR 0x600001d3a600> [debug] Custom config: []
2020-06-21 09:33:02.588 MVRP[16782:148215] <ERROR 0x600001d3a600> [debug] Command-line args: [u'--ignore-config', u'--no-color', u'--no-call-home', u'--newline', u'--verbose', u'--no-playlist', u'--prefer-ffmpeg', u'--ffmpeg-location', u'/Applications/Mac VideoRipper Pro.app/Contents/Resources/ffmpeg', u'--merge-output-format', u'mp4', u'-f', u'best[height=2160][ext=mp4]/bestvideo[height<=2160][vcodec!=vp9]+bestaudio[ext=m4a]/best[height<=2160][ext=mp4]/best', u'--recode-video', u'mp4', u'https://www.youtube.com/watch?v=ubvYQxTXO3U']
2020-06-21 09:33:02.588 MVRP[16782:148215] <ERROR 0x600001d3a600> 
2020-06-21 09:33:02.596 MVRP[16782:148215] <ERROR 0x600001d3a600> [debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII
2020-06-21 09:33:02.596 MVRP[16782:148215] <ERROR 0x600001d3a600> [debug] youtube-dl version 2020.03.08
2020-06-21 09:33:02.596 MVRP[16782:148215] <ERROR 0x600001d3a600> 
2020-06-21 09:33:02.610 MVRP[16782:148215] <ERROR 0x600001d3a600> [debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
2020-06-21 09:33:02.610 MVRP[16782:148215] <ERROR 0x600001d3a600> 
2020-06-21 09:33:02.657 MVRP[16782:148215] <ERROR 0x600001d3a600> [debug] exe versions: ffmpeg 3.2.2-tessus, ffprobe 3.2.2-tessus, rtmpdump 2.4
2020-06-21 09:33:02.657 MVRP[16782:148215] <ERROR 0x600001d3a600> [debug] Proxy map: {}
2020-06-21 09:33:02.657 MVRP[16782:148215] <ERROR 0x600001d3a600> 
2020-06-21 09:33:03.026 MVRP[16782:148215] <OUTPUT 0x600001d3a600> [youtube] ubvYQxTXO3U: Downloading webpage
2020-06-21 09:33:03.026 MVRP[16782:148215] <OUTPUT 0x600001d3a600> 
2020-06-21 09:33:03.718 MVRP[16782:148215] <OUTPUT 0x600001d3a600> [youtube] Downloading just video ubvYQxTXO3U because of --no-playlist
2020-06-21 09:33:03.718 MVRP[16782:148215] <OUTPUT 0x600001d3a600> 
2020-06-21 09:33:03.752 MVRP[16782:148215] <ERROR 0x600001d3a600> ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2020-06-21 09:33:03.753 MVRP[16782:148215] <ERROR 0x600001d3a600> 
2020-06-21 09:33:03.756 MVRP[16782:148215] <ERROR 0x600001d3a600> Traceback (most recent call last):
2020-06-21 09:33:03.756 MVRP[16782:148215] <ERROR 0x600001d3a600>   File "/var/folders/sm/595blnp15l11b3zxhf9csq880000gn/T/mvrp.Ymtx4g/youtube_dl/YoutubeDL.py", line 797, in extract_info
2020-06-21 09:33:03.756 MVRP[16782:148215] <ERROR 0x600001d3a600>     ie_result = ie.extract(url)
2020-06-21 09:33:03.756 MVRP[16782:148215] <ERROR 0x600001d3a600>   File "/var/folders/sm/595blnp15l11b3zxhf9csq880000gn/T/mvrp.Ymtx4g/youtube_dl/extractor/common.py", line 530, in extract
2020-06-21 09:33:03.756 MVRP[16782:148215] <ERROR 0x600001d3a600>     ie_result = self._real_extract(url)
2020-06-21 09:33:03.756 MVRP[16782:148215] <ERROR 0x600001d3a600>   File "/var/folders/sm/595blnp15l11b3zxhf9csq880000gn/T/mvrp.Ymtx4g/youtube_dl/extractor/youtube.py", line 2364, in _real_extract
2020-06-21 09:33:03.756 MVRP[16782:148215] <ERROR 0x600001d3a600>     self._sort_formats(formats)
2020-06-21 09:33:03.756 MVRP[16782:148215] <ERROR 0x600001d3a600>   File "/var/folders/sm/595blnp15l11b3zxhf9csq880000gn/T/mvrp.Ymtx4g/youtube_dl/extractor/common.py", line 1327, in _sort_formats
2020-06-21 09:33:03.756 MVRP[16782:148215] <ERROR 0x600001d3a600>     raise ExtractorError('No video formats found')
2020-06-21 09:33:03.756 MVRP[16782:148215] <ERROR 0x600001d3a600> ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2020-06-21 09:33:03.756 MVRP[16782:148215] <ERROR 0x600001d3a600> 
2020-06-21 09:33:03.756 MVRP[16782:148215] <ERROR 0x600001d3a600> 
2020-06-21 09:33:03.778 MVRP[16782:148600] task 0x600001d3a600 done
2020-06-21 09:33:53.324 MVRP[16782:148215] downloadUrl: https://www.youtube.com/watch?v=ubvYQxTXO3U ripMode: 1
2020-06-21 09:33:53.324 MVRP[16782:148215] s: https://www.youtube.com/watch?v=ubvYQxTXO3U d: /Users/mikee/Desktop/Youtube Video Captures
2020-06-21 09:33:53.324 MVRP[16782:150208] version 1.0.8 toolOriVersion 1.0.8
2020-06-21 09:33:53.324 MVRP[16782:150208] time since last update check: 62
2020-06-21 09:33:53.576 MVRP[16782:148215] osv 10.14.6
2020-06-21 09:33:53.576 MVRP[16782:148215] task env: {
    "Apple_PubSub_Socket_Render" = "/private/tmp/com.apple.launchd.iSbvx2j5kN/Render";
    HOME = "/Users/mikee";
    LOGNAME = mikee;
    PATH = "/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Mac VideoRipper Pro.app/Contents/Resources";
    SHELL = "/bin/bash";
    "SSH_AUTH_SOCK" = "/private/tmp/com.apple.launchd.Mmxu0gQun1/Listeners";
    TMPDIR = "/var/folders/sm/595blnp15l11b3zxhf9csq880000gn/T/";
    USER = mikee;
    "XPC_FLAGS" = 0x0;
    "XPC_SERVICE_NAME" = "com.mvrp.MVRP.38556";
    "__CF_USER_TEXT_ENCODING" = "0x1F5:0x0:0x0";
}
2020-06-21 09:33:53.576 MVRP[16782:148215] launching task 0x600001d12a00
2020-06-21 09:33:53.582 MVRP[16782:148215] task 0x600001d12a00 launched
2020-06-21 09:33:54.325 MVRP[16782:148215] <ERROR 0x600001d12a00> [debug] System config: []
2020-06-21 09:33:54.325 MVRP[16782:148215] <ERROR 0x600001d12a00> [debug] User config: []
2020-06-21 09:33:54.325 MVRP[16782:148215] <ERROR 0x600001d12a00> [debug] Custom config: []
2020-06-21 09:33:54.325 MVRP[16782:148215] <ERROR 0x600001d12a00> 
2020-06-21 09:33:54.325 MVRP[16782:148215] <ERROR 0x600001d12a00> [debug] Command-line args: [u'--ignore-config', u'--no-color', u'--no-call-home', u'--newline', u'--verbose', u'--no-playlist', u'--prefer-ffmpeg', u'--ffmpeg-location', u'/Applications/Mac VideoRipper Pro.app/Contents/Resources/ffmpeg', u'--merge-output-format', u'mp4', u'-f', u'bestaudio[ext=m4a]/bestaudio', u'https://www.youtube.com/watch?v=ubvYQxTXO3U']
2020-06-21 09:33:54.325 MVRP[16782:148215] <ERROR 0x600001d12a00> 
2020-06-21 09:33:54.333 MVRP[16782:148215] <ERROR 0x600001d12a00> [debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII
2020-06-21 09:33:54.333 MVRP[16782:148215] <ERROR 0x600001d12a00> [debug] youtube-dl version 2020.03.08
2020-06-21 09:33:54.333 MVRP[16782:148215] <ERROR 0x600001d12a00> 
2020-06-21 09:33:54.347 MVRP[16782:148215] <ERROR 0x600001d12a00> [debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
2020-06-21 09:33:54.347 MVRP[16782:148215] <ERROR 0x600001d12a00> 
2020-06-21 09:33:54.392 MVRP[16782:148215] <ERROR 0x600001d12a00> [debug] exe versions: ffmpeg 3.2.2-tessus, ffprobe 3.2.2-tessus, rtmpdump 2.4
2020-06-21 09:33:54.392 MVRP[16782:148215] <ERROR 0x600001d12a00> [debug] Proxy map: {}
2020-06-21 09:33:54.392 MVRP[16782:148215] <ERROR 0x600001d12a00> 
2020-06-21 09:33:54.695 MVRP[16782:148215] <OUTPUT 0x600001d12a00> [youtube] ubvYQxTXO3U: Downloading webpage
2020-06-21 09:33:54.695 MVRP[16782:148215] <OUTPUT 0x600001d12a00> 
2020-06-21 09:33:55.297 MVRP[16782:148215] <OUTPUT 0x600001d12a00> [youtube] Downloading just video ubvYQxTXO3U because of --no-playlist
2020-06-21 09:33:55.297 MVRP[16782:148215] <OUTPUT 0x600001d12a00> 
2020-06-21 09:33:55.323 MVRP[16782:148215] <ERROR 0x600001d12a00> ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2020-06-21 09:33:55.323 MVRP[16782:148215] <ERROR 0x600001d12a00> 
2020-06-21 09:33:55.326 MVRP[16782:148215] <ERROR 0x600001d12a00> Traceback (most recent call last):
2020-06-21 09:33:55.326 MVRP[16782:148215] <ERROR 0x600001d12a00>   File "/var/folders/sm/595blnp15l11b3zxhf9csq880000gn/T/mvrp.0rcRKI/youtube_dl/YoutubeDL.py", line 797, in extract_info
2020-06-21 09:33:55.326 MVRP[16782:148215] <ERROR 0x600001d12a00>     ie_result = ie.extract(url)
2020-06-21 09:33:55.326 MVRP[16782:148215] <ERROR 0x600001d12a00>   File "/var/folders/sm/595blnp15l11b3zxhf9csq880000gn/T/mvrp.0rcRKI/youtube_dl/extractor/common.py", line 530, in extract
2020-06-21 09:33:55.326 MVRP[16782:148215] <ERROR 0x600001d12a00>     ie_result = self._real_extract(url)
2020-06-21 09:33:55.326 MVRP[16782:148215] <ERROR 0x600001d12a00>   File "/var/folders/sm/595blnp15l11b3zxhf9csq880000gn/T/mvrp.0rcRKI/youtube_dl/extractor/youtube.py", line 2364, in _real_extract
2020-06-21 09:33:55.326 MVRP[16782:148215] <ERROR 0x600001d12a00>     self._sort_formats(formats)
2020-06-21 09:33:55.326 MVRP[16782:148215] <ERROR 0x600001d12a00>   File "/var/folders/sm/595blnp15l11b3zxhf9csq880000gn/T/mvrp.0rcRKI/youtube_dl/extractor/common.py", line 1327, in _sort_formats
2020-06-21 09:33:55.326 MVRP[16782:148215] <ERROR 0x600001d12a00>     raise ExtractorError('No video formats found')
2020-06-21 09:33:55.326 MVRP[16782:148215] <ERROR 0x600001d12a00> ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2020-06-21 09:33:55.326 MVRP[16782:148215] <ERROR 0x600001d12a00> 
2020-06-21 09:33:55.326 MVRP[16782:148215] <ERROR 0x600001d12a00> 
2020-06-21 09:33:55.346 MVRP[16782:150068] task 0x600001d12a00 done

**Comment by hedbonker** [comment]
According to the application, the version that I am running is the current version.

**Comment by SpyceTewan** [comment]
I had this error too but updating helped on my end..
