### ISSUE TITLE
issue on viki.com

### ISSUE THREAD

**Issue by TehranShop** [ytdl-org/youtube-dl#25752]
youtube-dl -f best -v --write-sub --sub-lang en https://www.viki.com/videos/1159724v-joy-of-life-episode-10
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '-v', '--write-sub', '--sub-lang', 'en', 'https://www.viki.com/videos/1159724v-joy-of-life-episode-10']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.6.8 (CPython) - Linux-3.10.0-1127.10.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[viki] 1159724v: Downloading video JSON
[viki] 1159724v: Downloading video streams JSON
[info] Writing video subtitles to: Joy of Life - Episode 10-1159724v.en.vtt
[debug] Invoking downloader on 'https://v4.viki.io/1159724v/1159724v_high_480p_2744c5_1912090247.mp4?e=1592774769&h=1df7aad0958524547c24b3b906aab854'
[download] Resuming download at byte 19964371
[download] Destination: Joy of Life - Episode 10-1159724v.mp4
[download]  57.4% of 206.37MiB at  1.52MiB/s ETA 00:57ERROR: unable to download video data: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2334)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/downloader/http.py", line 342, in real_download
    return download()
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/downloader/http.py", line 230, in download
    data_block = ctx.data.read(block_size if data_len is None else min(block_size, data_len - byte_counter))
  File "/usr/lib64/python3.6/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/usr/lib64/python3.6/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.6/ssl.py", line 968, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 830, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 587, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2334)

**Comment by TehranShop** [comment]
Hi again
I try --verbose and maybe the issue is corrected and downloading all videos with speedy

i don't know what is the --verbose options

**Comment by TehranShop** [comment]
it's my fault 
i do install to different python version
python 2.7.5
python 3.6.8

how to remove python 2.7.5 from centos 7?

thanks
