### ISSUE TITLE
Zattoo - not able to extract app token

### ISSUE THREAD

**Issue by gray30000000** [ytdl-org/youtube-dl#25755]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
with master branch:
gray@gray-H110-D3A:~/Documents/yt-dl-2020.06.16.1/youtube-dl-master/youtube_dl$ python __main__.py https://zattoo.com/recordings?recording=256380267 --username *****@gmail.com --password ************ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://zattoo.com/recordings?recording=256380267', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.18rc1 (CPython) - Linux-5.4.0-212005281620-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[generic] recordings?recording=256380267: Requesting header
WARNING: Falling back on generic information extractor.
[generic] recordings?recording=256380267: Downloading webpage
[generic] recordings?recording=256380267: Extracting information
ERROR: Unsupported URL: https://zattoo.com/recordings?recording=256380267
Traceback (most recent call last):
  File "home/gray/Documents/yt-dl-2020.06.16.1/youtube-dl-master/youtube_dl/extractor/generic.py", line 2387, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/home/gray//Documents/yt-dl-2020.06.16.1/youtube-dl-master/youtube_dl/compat.py", line 2562, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/home/gray//Documents/yt-dl-2020.06.16.1/youtube-dl-master/youtube_dl/compat.py", line 2551, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1, column 1851
Traceback (most recent call last):
  File "/home/gray//Documents/yt-dl-2020.06.16.1/youtube-dl-master/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/gray//Documents/yt-dl-2020.06.16.1/youtube-dl-master/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "home/gray//Documents/yt-dl-2020.06.16.1/youtube-dl-master/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://zattoo.com/recordings?recording=256380267






with zattoo-new-website branch:
gray@gray-H110-D3A:~/Documents/youtube-dl-zattoo-new-website/youtube_dl$ python __main__.py https://zattoo.com/recordings?recording=256380267 --username ********@gmail.com --password ******************* -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://zattoo.com/recordings?recording=256380267', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.7.18rc1 (CPython) - Linux-5.4.0-212005281620-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[Zattoo] Downloading app token
ERROR: Unable to extract app token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/gray//Documents/youtube-dl-zattoo-new-website/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/gray//Documents/youtube-dl-zattoo-new-website/youtube_dl/extractor/common.py", line 529, in extract
    self.initialize()
  File "/Documents/youtube-dl-zattoo-new-website/youtube_dl/extractor/common.py", line 433, in initialize
    self._real_initialize()
  File "/home/gray/Documents/youtube-dl-zattoo-new-website/youtube_dl/extractor/zattoo.py", line 59, in _real_initialize
    webpage, 'app token', group='token')
  File "/home/gray//Documents/youtube-dl-zattoo-new-website/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/gray//Documents/youtube-dl-zattoo-new-website/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract app token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I'm trying to download some recordings I made with Zattoo (witch is on the list of supported sites). So I tried it and it came up with an error. I did a little bit of research and found a branch that was specifically made to counteract this issue. It managed to get further than the master branch but it still didn't work. 

Zattoo is restricted to Germany and Switzerland but can easily be acessed with a VPN such as PIA (other VPN's are available).

(sorry if I got any of the formatting wrong, this is the first time I've written an issue)

**Comment by gray30000000** [comment]
Don't worry, I've found a way around it.
I just manually got the mpd manifest and then used youtube-dl from there.
Thanks for everyone that bothered reading though.

**Comment by omueller** [comment]
Hi @gray30000000 , getting the same "ERROR: Unable to extract app token" error with zattoo.com and youtube-dl version 2021.01.16, if it is still actual, would you mind sharing how you solved this ?  Thanks :)

**Comment by omueller** [comment]
PS: @goggle from https://github.com/ytdl-org/youtube-dl/issues/22258 :  "You find an adoption of the information extractor here: https://github.com/goggle/youtube-dl/tree/zattoo-new-website" : this pages currently displays the DMCA notice, probably from last year's ytdl takedown. Maybe you will have more information to solve this issue too ?  thanks!
