### ISSUE TITLE
downloading error

### ISSUE THREAD

**Issue by rafalfr** [ytdl-org/youtube-dl#25758]
Cannot download videos from this youtube channel
https://www.youtube.com/channel/UCcb7sTcOwcbneg6Zo5F4SGQ

Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 11, in <module>
    load_entry_point('youtube-dl==2020.5.29', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.8/site-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/usr/lib/python3.8/site-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2018, in download
    res = self.extract_info(
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 867, in process_ie_result
    return self.extract_info(ie_result['url'],
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 968, in process_ie_result
    entries = list(itertools.islice(
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 313, in _entries
    content_html = more['content_html']
KeyError: 'content_html'

**Comment by alif-bae** [comment]
You are not using the latest version of youtube-dl, update to the latest version and try again. It works for me on `2020.06.16.1`
