### ISSUE TITLE
Instagram URL Extractor failing for Linux-4.14.177-104.253.amzn2.x86_64-x86_64-with-glibc2.2.5

### ISSUE THREAD

**Issue by ajm339** [ytdl-org/youtube-dl#25763]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```

1592878715420 | START RequestId: 7becff83-8548-4eff-8c00-33398d1873ca Version: $LATEST
-- | --
1592878715432 | [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
1592878715432 | [debug] youtube-dl version 2020.06.16.1
1592878715435 | [debug] Python version 3.8.3 (CPython) - Linux-4.14.177-104.253.amzn2.x86_64-x86_64-with-glibc2.2.5
1592878715448 | [debug] exe versions: none
1592878715448 | [debug] Proxy map: {}
1592878715451 | [Instagram] B7_RmlfHIh1: Downloading webpage
1592878715640 | ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
1592878715644 | Traceback (most recent call last):
1592878715644 | File "/var/task/youtube_dl/YoutubeDL.py", line 797, in extract_info
1592878715644 | ie_result = ie.extract(url)
1592878715644 | File "/var/task/youtube_dl/extractor/common.py", line 530, in extract
1592878715644 | ie_result = self._real_extract(url)
1592878715644 | File "/var/task/youtube_dl/extractor/instagram.py", line 195, in _real_extract
1592878715644 | video_url = self._og_search_video_url(webpage, secure=False)
1592878715644 | File "/var/task/youtube_dl/extractor/common.py", line 1123, in _og_search_video_url
1592878715644 | return self._html_search_regex(regexes, html, name, **kargs)
1592878715644 | File "/var/task/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
1592878715644 | res = self._search_regex(pattern, string, name, default, fatal, flags, group)
1592878715644 | File "/var/task/youtube_dl/extractor/common.py", line 1005, in _search_regex
1592878715644 | raise RegexNotFoundError('Unable to extract %s' % _name)
1592878715644 | youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
1592878715645 | [ERROR] DownloadError: ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):   File "/var/task/youtube_downloader.py", line 82, in lambda_handler     info_dict = ydl.extract_info(url, download=True) # https://github.com/ytdl-org/youtube-dl/issues/5710#issuecomment-370744916   File "/var/task/youtube_dl/YoutubeDL.py", line 820, in extract_info     self.report_error(compat_str(e), e.format_traceback())   File "/var/task/youtube_dl/YoutubeDL.py", line 625, in report_error     self.trouble(error_message, tb)   File "/var/task/youtube_dl/YoutubeDL.py", line 595, in trouble     raise DownloadError(message, exc_info)
1592878715647 | END RequestId: 7becff83-8548-4eff-8c00-33398d1873ca
1592878715647 | REPORT RequestId: 7becff83-8548-4eff-8c00-33398d1873ca	Duration: 224.07 ms	Billed Duration: 300 ms	Memory Size: 3008 MB	Max Memory Used: 149 MB


```

## Description

I have an AWS Lambda function that handles downloading my videos.  There is something wrong specifically for Instagram videos and the `outtmpl` attribute in Python for Linux-4.14.177-104.253.amzn2.x86_64-x86_64-with-glibc2.2.5.

Basically, locally running the script I can get YouTube, Vimeo, and Instagram Videos to all work.

In Production on AWS Lambda, I previously could get all 3 to work.  Now Instagram videos fail with the error `ERROR: Unable to extract video url;`.  Since this works fine with YouTube and Vimeo, I suspect there is a niche edge case with the latest update for the Amazon Linux Kernel that is breaking when trying to extract an Instagram URL.

Attaching my code so you can see deeper what I mean.

URL that work Locally and Production: https://www.youtube.com/watch?v=JVM49MXcCWQ
URL that works Locally but NOT Production: https://www.instagram.com/p/B7_RmlfHIh1/

The logs linked show YouTube successfully working and Instagram Failing
[youtube-dl-logs.pdf](https://github.com/ytdl-org/youtube-dl/files/4816911/youtube-dl-logs.pdf)

This is a text file of my python program running in Lambda. Note there are differences in prod vs development because Lambda only lets you write to `/tmp`.
[youtube_downloader.txt](https://github.com/ytdl-org/youtube-dl/files/4816921/youtube_downloader.txt)

**Comment by ajm339** [comment]
@remitamine what additional information can I provide you to help reproduce and mark this as not incomplete?
