### ISSUE TITLE
educative site support

### ISSUE THREAD

**Issue by tnmils** [ytdl-org/youtube-dl#25772]
Hello,
Please can you add support for this children educative site lumni.fr. i can't dowload video from the following url :
https://www.lumni.fr/video/lutilisation-de-plusieurs-droites-graduees-24-juin#containerType=serie&containerSlug=la-maison-lumni-primaire
thanks. 
the verbose output of youtube-dl 
" sc@PC-IP02:~$ youtube-dl -v -F https://www.lumni.fr/video/lutilisation-de-plusieurs-droites-graduees-24-juin#containerType=serie&containerSlug=la-maison-lumni-primaire
[1] 26280
sc@PC-IP02:~$ [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.lumni.fr/video/lutilisation-de-plusieurs-droites-graduees-24-juin#containerType=serie']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-59-generic-x86_64-with-neon-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] lutilisation-de-plusieurs-droites-graduees-24-juin#containerType=serie: Requesting header
WARNING: Falling back on generic information extractor.
[generic] lutilisation-de-plusieurs-droites-graduees-24-juin#containerType=serie: Downloading webpage
[generic] lutilisation-de-plusieurs-droites-graduees-24-juin#containerType=serie: Extracting information
ERROR: Unsupported URL: https://www.lumni.fr/video/lutilisation-de-plusieurs-droites-graduees-24-juin#containerType=serie
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2387, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2562, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1, column 622
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.lumni.fr/video/lutilisation-de-plusieurs-droites-graduees-24-juin#containerType=serie
"

**Comment by darkRaspberry** [comment]
#meTOO

**Comment by taokann** [comment]
Doublon de/ Duplicate of #24574
@tnmils @darkRaspberry Suivez les instructions dans ce ticket. / Follow the instructions there.
