### ISSUE TITLE
Adobe Pass broken for AT&T TV (DirecTV Now) and/or Science Channel

### ISSUE THREAD

**Issue by ryaniskira** [ytdl-org/youtube-dl#25782]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -i --ap-mso ATTOTT --ap-username "<REDACTED>"  -a Sinkholes.txt --download-archive DL.txt --verbose -o Sinkholes:\ Swallowed\ Alive/'%(title)s.%(ext)s' 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-i', '--ap-mso', 'ATTOTT', '--ap-username', 'PRIVATE', '-a', 'Sinkholes.txt', '--download-archive', 'DL.txt', '--verbose', '-o', 'Sinkholes: Swallowed Alive/%(title)s.%(ext)s']
[debug] Batch file urls: ['https://www.sciencechannel.com/tv-shows/sinkholes-swallowed-alive/full-episodes/florida-hell-hole', 'https://www.sciencechannel.com/tv-shows/sinkholes-swallowed-alive/full-episodes/pit-of-doom-nyc', 'https://www.sciencechannel.com/tv-shows/sinkholes-swallowed-alive/full-episodes/man-eating-monster', 'https://www.sciencechannel.com/tv-shows/sinkholes-swallowed-alive/full-episodes/nightmare-in-the-bayou', 'https://www.sciencechannel.com/tv-shows/sinkholes-swallowed-alive/full-episodes/the-thing-that-ate-florida', 'https://www.sciencechannel.com/tv-shows/sinkholes-swallowed-alive/full-episodes/gothams-gates-of-hell', 'https://www.sciencechannel.com/tv-shows/sinkholes-swallowed-alive/full-episodes/terror-in-texas', 'https://www.sciencechannel.com/tv-shows/sinkholes-swallowed-alive/full-episodes/wrath-of-the-jersey-devil', 'https://www.sciencechannel.com/tv-shows/sinkholes-swallowed-alive/full-episodes/when-florida-attacks']
Type TV provider account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.3 (CPython) - Linux-5.7.0-3-MANJARO-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3, rtmpdump 2.4
[debug] Proxy map: {}
[Discovery] florida-hell-hole: Downloading token JSON metadata
[Discovery] florida-hell-hole: Downloading content JSON metadata
[Discovery] florida-hell-hole: Downloading streaming JSON metadata
ERROR: This video is only available via cable service provider subscription that is not currently supported. You may want to use --cookies.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/discovery.py", line 102, in _real_extract
    stream = self._download_json(
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 888, in _download_json
    res = self._download_json_handle(
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 867, in _download_json_handle
    res = self._download_webpage_handle(
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 660, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 645, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/discovery.py", line 102, in _real_extract
    stream = self._download_json(
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 888, in _download_json
    res = self._download_json_handle(
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 867, in _download_json_handle
    res = self._download_webpage_handle(
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 660, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 645, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/discovery.py", line 112, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: This video is only available via cable service provider subscription that is not currently supported. You may want to use --cookies.

```

## Description

Youtube-DL falsely claims that my my current cable provider subscription is unsupported and errors out even though I can log onto the site right now and view any video I please with my subscription:
![Screenshot at 2020-06-24 19-49-09](https://user-images.githubusercontent.com/5086636/85638431-e2183700-b653-11ea-8e17-bfd30972190e.png)
As well as successfully use a cookie file to download videos (which is not ideal since cookies for these sites expire hourly or less).

**Comment by dstftw** [comment]
You must provide TV provider credentials and proxy/VPN for any work on this.

**Comment by ryaniskira** [comment]
@dstftw It asks for the password when you fail to provide one:
```
