### ISSUE TITLE
Cancelling download/accessing folder that the video files being downloaded into seizes up explorer, unable to read any other folder; "infects" that particular folder with problems and has to be deleted.

### ISSUE THREAD

**Issue by pxssy** [ytdl-org/youtube-dl#25785]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --verbose https://www.youtube.com/channel/UCI7ktPB6toqucpkkCiolwLg
[debug] System config: []
[debug] User config: ['--output', './ytdl/%(uploader)s (%(uploader_id)s)/[%(upload_date)s] %(title)s %(fps)s[%(resolution)s] (%(id)s).%(ext)s', '--format', 'bestvideo[height>=7680][fps>=60]+bestaudio/bestvideo[height>=7680][fps>=30]+bestaudio/bestvideo[width>=7680][fps>=60]+bestaudio/bestvideo[width>=7680][fps>=30]+bestaudio/bestvideo[height>=5120][fps>=60]+bestaudio/bestvideo[height>=5120][fps>=30]+bestaudio/bestvideo[width>=5120][fps>=60]+bestaudio/bestvideo[width>=5120][fps>=30]+bestaudio/bestvideo[height>=3840][fps>=60]+bestaudio/bestvideo[height>=3840][fps>=30]+bestaudio/bestvideo[width>=3840][fps>=60]+bestaudio/bestvideo[width>=3840][fps>=30]+bestaudio/bestvideo[height>=2560][fps>=60]+bestaudio/bestvideo[height>=2560][fps>=30]+bestaudio/bestvideo[width>=2560][fps>=60]+bestaudio/bestvideo[width>=2560][fps>=30]+bestaudio/bestvideo[height>=2160][fps>=60]+bestaudio/bestvideo[height>=2160][fps>=30]+bestaudio/bestvideo[width>=2160][fps>=60]+bestaudio/bestvideo[width>=2160][fps>=30]+bestaudio/bestvideo[height>=1920][fps>=60]+bestaudio/bestvideo[height>=1920][fps>=30]+bestaudio/bestvideo[width>=1920][fps>=60]+bestaudio/bestvideo[width>=1920][fps>=30]+bestaudio/bestvideo+bestaudio/best', '--write-description', '--write-info-json', '--write-annotations', '--write-all-thumbnails', '--all-subs', '--add-metadata', '--ignore-errors']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/channel/UCI7ktPB6toqucpkkCiolwLg']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-06-04-7f81785, ffprobe git-2020-06-04-7f81785
[debug] Proxy map: {}
[youtube:channel] UCI7ktPB6toqucpkkCiolwLg: Downloading channel page
[youtube:playlist] UUI7ktPB6toqucpkkCiolwLg: Downloading webpage
[download] Downloading playlist: Uploads from Pan Piano
[youtube:playlist] UUI7ktPB6toqucpkkCiolwLg: Downloading page #1
[youtube:playlist] UUI7ktPB6toqucpkkCiolwLg: Downloading page #2
[youtube:playlist] playlist Uploads from Pan Piano: Downloading 252 videos
[download] Downloading video 1 of 252
[youtube] 55xcuX-YMlw: Downloading webpage
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\youtube.py", line 2212, in _real_extract
youtube_dl.utils.ExtractorError: This video is unavailable.

[download] Downloading video 2 of 252
[youtube] S-zNZ1AB_K4: Downloading webpage
WARNING: video doesn't have subtitles
[info] Writing video description to: ytdl\Pan Piano (UCI7ktPB6toqucpkkCiolwLg)\[20200623] 棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ] 30[1920x1080] (S-zNZ1AB_K4).description
WARNING: There are no annotations to write.
[info] Writing video description metadata as JSON to: ytdl\Pan Piano (UCI7ktPB6toqucpkkCiolwLg)\[20200623] 棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ] 30[1920x1080] (S-zNZ1AB_K4).info.json
[youtube] S-zNZ1AB_K4: Downloading thumbnail 0 ...
[youtube] S-zNZ1AB_K4: Writing thumbnail 0 to: ytdl\Pan Piano (UCI7ktPB6toqucpkkCiolwLg)\[20200623] 棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ] 30[1920x1080] (S-zNZ1AB_K4)_0.jpg
[youtube] S-zNZ1AB_K4: Downloading thumbnail 1 ...
[youtube] S-zNZ1AB_K4: Writing thumbnail 1 to: ytdl\Pan Piano (UCI7ktPB6toqucpkkCiolwLg)\[20200623] 棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ] 30[1920x1080] (S-zNZ1AB_K4)_1.jpg
[youtube] S-zNZ1AB_K4: Downloading thumbnail 2 ...
[youtube] S-zNZ1AB_K4: Writing thumbnail 2 to: ytdl\Pan Piano (UCI7ktPB6toqucpkkCiolwLg)\[20200623] 棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ] 30[1920x1080] (S-zNZ1AB_K4)_2.jpg
[youtube] S-zNZ1AB_K4: Downloading thumbnail 3 ...
[youtube] S-zNZ1AB_K4: Writing thumbnail 3 to: ytdl\Pan Piano (UCI7ktPB6toqucpkkCiolwLg)\[20200623] 棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ] 30[1920x1080] (S-zNZ1AB_K4)_3.jpg
[youtube] S-zNZ1AB_K4: Downloading thumbnail 4 ...
[youtube] S-zNZ1AB_K4: Writing thumbnail 4 to: ytdl\Pan Piano (UCI7ktPB6toqucpkkCiolwLg)\[20200623] 棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ] 30[1920x1080] (S-zNZ1AB_K4)_4.jpg
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r2---sn-npoeeney.googlevideo.com/videoplayback?expire=1593085256&ei=6Dj0XrXYL4jiogOp5IPIBQ&ip=103.254.153.113&id=o-ADRqMhawor6Ut3kYZRam_clV4zl1VBUTbIjfSE-ToF8P&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=9F&mm=31%2C29&mn=sn-npoeeney%2Csn-npoe7ner&ms=au%2Crdu&mv=m&mvi=1&pl=25&initcwndbps=621250&vprv=1&mime=video%2Fmp4&gir=yes&clen=1263203773&dur=3632.928&lmt=1592893153298857&mt=1593063633&fvip=2&keepalive=yes&c=WEB&txp=6416222&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKu78A6wQODY8HWWsdfKlgHM4rsLwaQ73mwOhbWGDRUBAiEAmYPCx5kC7QSKaH-fWWYtZ0UX3RrWnDM7HIS79vhK4Tk%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgHh05lEK-34ksf3vYdCPQk0wCWLPbJuItbW1_BgrcXfICIH3jPm4aE0idzrSQQcj_PGURI3qn_KOJPY-BW6cFRykT&ratebypass=yes'
[download] Destination: ytdl\Pan Piano (UCI7ktPB6toqucpkkCiolwLg)\[20200623] 棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ] 30[1920x1080] (S-zNZ1AB_K4).f137.mp4
[download] 100% of 1.18GiB in 00:54
[debug] Invoking downloader on 'https://r2---sn-npoeeney.googlevideo.com/videoplayback?expire=1593085256&ei=6Dj0XrXYL4jiogOp5IPIBQ&ip=103.254.153.113&id=o-ADRqMhawor6Ut3kYZRam_clV4zl1VBUTbIjfSE-ToF8P&itag=251&source=youtube&requiressl=yes&mh=9F&mm=31%2C29&mn=sn-npoeeney%2Csn-npoe7ner&ms=au%2Crdu&mv=m&mvi=1&pl=25&initcwndbps=621250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=71376532&dur=3632.961&lmt=1592893195471488&mt=1593063633&fvip=2&keepalive=yes&c=WEB&txp=6411222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAKNWXKR_A0a-mXDqeu4BT7nAIt-J2epEAP58-yL_1iU6AiAJAMU_aJCybBjpQzyESTyMcnpIR95ChQtjyaZX5hZ0DA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgHh05lEK-34ksf3vYdCPQk0wCWLPbJuItbW1_BgrcXfICIH3jPm4aE0idzrSQQcj_PGURI3qn_KOJPY-BW6cFRykT&ratebypass=yes'
[download] Destination: ytdl\Pan Piano (UCI7ktPB6toqucpkkCiolwLg)\[20200623] 棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ] NA[NA] (S-zNZ1AB_K4).f251.webm
[download] 100% of 68.07MiB in 00:02
[ffmpeg] Merging formats into "ytdl\Pan Piano (UCI7ktPB6toqucpkkCiolwLg)\[20200623] 棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ] 30[1920x1080] (S-zNZ1AB_K4).mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:ytdl\Pan Piano (UCI7ktPB6toqucpkkCiolwLg)\[20200623] 棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ] 30[1920x1080] (S-zNZ1AB_K4).f137.mp4" -i "file:ytdl\Pan Piano (UCI7ktPB6toqucpkkCiolwLg)\[20200623] 棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ] NA[NA] (S-zNZ1AB_K4).f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:ytdl\Pan Piano (UCI7ktPB6toqucpkkCiolwLg)\[20200623] 棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ] 30[1920x1080] (S-zNZ1AB_K4).temp.mkv"
Deleting original file ytdl\Pan Piano (UCI7ktPB6toqucpkkCiolwLg)\[20200623] 棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ] 30[1920x1080] (S-zNZ1AB_K4).f137.mp4 (pass -k to keep)
Deleting original file ytdl\Pan Piano (UCI7ktPB6toqucpkkCiolwLg)\[20200623] 棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ] NA[NA] (S-zNZ1AB_K4).f251.webm (pass -k to keep)
[ffmpeg] Adding metadata to 'ytdl\Pan Piano (UCI7ktPB6toqucpkkCiolwLg)\[20200623] 棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ] 30[1920x1080] (S-zNZ1AB_K4).mkv'
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:ytdl\Pan Piano (UCI7ktPB6toqucpkkCiolwLg)\[20200623] 棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ] 30[1920x1080] (S-zNZ1AB_K4).mkv" -c copy -metadata "purl=https://www.youtube.com/watch?v=S-zNZ1AB_K4" -metadata "title=棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ]" -metadata "description=棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ]
Coffin Dance Astronomia One hour BGM For WORK [piano]
Cover by pan piano

編集ソフトで作ってみました！
棺桶ダンス 1時間作業用BGM です(*´▽`*)

#棺桶ダンス
#Astronomia
#CoffinDance
#黑人抬棺
#1時間耐久
#弾いてみた

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Support me by Patreon!!(*´∀`)~♥
https://www.patreon.com/panpiano

♫Learn piano easily♫
https://tinyurl.com/PanPiano-flowkey

My Instagram
https://www.instagram.com/panpianoatelier/

My Blog(中文)
http://panpiano.com

小P的音樂工房鋼琴初級課程(中文)
http://panpiano.com/basic_class/

My Twitter!(日本語)
https://twitter.com/panpianoatelier

My facebook page(中文/English):
https://www.facebook.com/panpianoatelier
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -" -metadata "comment=棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ]
Coffin Dance Astronomia One hour BGM For WORK [piano]
Cover by pan piano

編集ソフトで作ってみました！
棺桶ダンス 1時間作業用BGM です(*´▽`*)

#棺桶ダンス
#Astronomia
#CoffinDance
#黑人抬棺
#1時間耐久
#弾いてみた

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Support me by Patreon!!(*´∀`)~♥
https://www.patreon.com/panpiano

♫Learn piano easily♫
https://tinyurl.com/PanPiano-flowkey

My Instagram
https://www.instagram.com/panpianoatelier/

My Blog(中文)
http://panpiano.com

小P的音樂工房鋼琴初級課程(中文)
http://panpiano.com/basic_class/

My Twitter!(日本語)
https://twitter.com/panpianoatelier

My facebook page(中文/English):
https://www.facebook.com/panpianoatelier
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -" -metadata "artist=Pan Piano" -metadata "date=20200623" "file:ytdl\Pan Piano (UCI7ktPB6toqucpkkCiolwLg)\[20200623] 棺桶ダンス Astronomia 1時間 作業用 BGM [ピアノ] 30[1920x1080] (S-zNZ1AB_K4).temp.mkv"
```

## Description

Cancelling/accessing folder that the video files being downloaded into seizes up explorer; explorer loads indefinitely on other folders including the offending one. 

As you can see its downloading properly, however, if i am to in any interrupt the process, like stopping it (ctrl+C), or accessing the folder in which the files are being downloaded into, (./ytd/Pan Piano) it seizes up my explorer indefinitely, i have to physically restart explorer, which still doesn't solve the issue; opening up the offending folder (./ytd/Pan Piano) seizes up explorer again, EVEN WHEN THE DOWNLOAD IS DONE AND OVER.

using youtube-dl to download into a particular folder, and then accessing it while its being downloaded/cancelling it while its downloading then accessing it, seems to "infect" that particular folder with some issue such that explorer can't read any other folder properly anymore. Explorer has to be restarted, offending folder deleted, and redownloaded and i have to ensure i don't access it or any programs attempt to. Then the new folder containing the videos can be accessed. 

Its extremely fustrating. 

I believe it might have something to do with attributes or perhaps saving metadata to the videos, which did not occur for previous versions of youtube-dl and i did not come across any similar issues with previous versions.

**Comment by dstftw** [comment]
Nothing to do with youtube-dl.

**Comment by pxssy** [comment]
> 
> 
> Nothing to do with youtube-dl.

it HAS everything to do with youtube-dl. Only youtube-dl is causing this, specifically this v2020.06.16.1. I've already stated quite clearly it creates an issue specifically when youtube-dl is downloading into that folder, and only opening that folder WHILE youtube-dl is running, creates an issue.
