### ISSUE TITLE
Downloads from Crackle no longer work

### ISSUE THREAD

**Issue by BillyCreek** [ytdl-org/youtube-dl#25791]
- [X ] I'm reporting a broken site support issue
- [ X] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar bug reports including closed ones
- [ X] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl --verbose "https://www.crackle.com/cleanin-up-the
-town-remembering-ghostbusters/2513246"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.crackle.com/cleanin-up-the-town-remembering-ghostbusters/2513246']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.2 (CPython) - Linux-5.4.45-sunxi64-aarch64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[Crackle] 2513246: Downloading media JSON as US
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/hunter/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/hunter/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/hunter/bin/youtube-dl/youtube_dl/extractor/crackle.py", line 133, in _real_extract
    self._sort_formats(formats)
  File "/home/hunter/bin/youtube-dl/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$
```

## Description

I've been able to download from Crackle with no problems for many months, but now, all attempts fail with the errors above. Crackle has obviously changed their setup, but I've been unable to figure out how. This is the URL I'm attempting, but I've tried a dozen others, all with the same results.

https://www.crackle.com/cleanin-up-the-town-remembering-ghostbusters/2513246

Thanks

**Comment by magnum32** [comment]
When is this issue going to be fixed?

**Comment by andonagio** [comment]
After a little digging around, it looks like Crackle may have recently switched to DRM encoding for their video files. Some evidence to this effect:

- If I go to any Crackle video, I can use the Video DownloadHelper to download an .mp4 file of the right size, but it won't play in any media player. That suggests the media is encrypted.
- The actual URLs for these .mp4 files all look something like the following:
`https://widevinedashus-crackle-com.akamaized.net/1/o/km/enc_azvyb_Crackle-L08-1080hd-3800k.mp4`
- The youtube-dl extractor for Crackle tries to get a JSON of the video metadata from sites like the following:
`https://web-api-us.crackle.com/Service.svc/details/media/6749/US?disableProtocols=true`
However, these sites are now all blank and generating 401 errors because they need some kind of username/password authentication (although I don't know why these errors aren't causing the Python script to raise exceptions). I also get the following message in my browser console:

`The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.`

All this suggests that there is no fix, and youtube-dl is now useless when it comes to Crackle. I won't be surprised if Crackle ends up getting removed from the list of supported sites in the near future.

**Comment by BillyCreek** [comment]
Thanks, andonagio!

I, too, had tried using Video DownloadHelper and noticed the same thing and wondered if that were the case. I should have mentioned it. You dug farther than I did. I appreciate the response.

It was nice while it lasted.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29335
