### ISSUE TITLE
Site support request for noodlemagazine.com

### ISSUE THREAD

**Issue by svardumps** [ytdl-org/youtube-dl#25803]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://noodlemagazine.com/watch/281711238_456240128

## Description

Greatings!
Add this site support, please.

**Comment by Menard01** [comment]
I request this support too

**Comment by Menard01** [comment]
`youtube-dl -v https://adult.noodlemagazine.com/watch/-10605510_456252663
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://adult.noodlemagazine.com/watch/-10605510_456252663']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.13.0-21-generic-x86_64-with-LinuxMint-20.1-ulyssa
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] -10605510_456252663: Requesting header
WARNING: Falling back on generic information extractor.
[generic] -10605510_456252663: Downloading webpage
[generic] -10605510_456252663: Extracting information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://noodlemagazine.com/videofile/-10605510_456252663.mp4'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1976, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
HTTPError: HTTP Error 404: Not Found
`

**Comment by smarek** [comment]
This ticket can be closed, noodlemagazine works 

```
> yt-dlp -F "https://noodlemagazine.com/watch/-redacted"
[NoodleMagazine] Extracting URL: https://noodlemagazine.com/watch/-redacted
[NoodleMagazine] -redacted: Downloading webpage
[info] Available formats for -redacted:
ID  EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
────────────────────────────────────────────
144 mp4 144p       │ https │ unknown unknown
240 mp4 240p       │ https │ unknown unknown
360 mp4 360p       │ https │ unknown unknown
480 mp4 480p       │ https │ unknown unknown
```
