### ISSUE TITLE
[linkedin] No video formats found

### ISSUE THREAD

**Issue by camillehuot** [ytdl-org/youtube-dl#25800]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl --list-format --username "$user" --password "$pass" --verbose https://www.linkedin.com/learning/decouvrir-microsoft-azure-2/creer-un-compte-azure
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--list-format', '--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose', 'https://www.linkedin.com/learning/decouvrir-microsoft-azure-2/creer-un-compte-azure']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.6.8 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[linkedin:learning] Downloading login page
[linkedin:learning] Logging in
[linkedin:learning] creer-un-compte-azure: Downloading 360p JSON metadata
[linkedin:learning] creer-un-compte-azure: Downloading 540p JSON metadata
[linkedin:learning] creer-un-compte-azure: Downloading 720p JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/gentoo/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/gentoo/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/gentoo/usr/lib/python3.6/site-packages/youtube_dl/extractor/linkedin.py", line 127, in _real_extract
    self._sort_formats(formats, ('width', 'height', 'source_preference', 'tbr', 'abr'))
  File "/gentoo/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Some videos from this training cannot be downloaded due to no format found.

They all play fine in the browser.

Some other videos of the same training can be downloaded properly:

```
URL: https://www.linkedin.com/learning/decouvrir-microsoft-azure-2/bienvenue-dans-decouvrir-microsoft-azure

[linkedin:learning] bienvenue-dans-decouvrir-microsoft-azure: Downloading 360p JSON metadata
[linkedin:learning] bienvenue-dans-decouvrir-microsoft-azure: Downloading 540p JSON metadata
[linkedin:learning] bienvenue-dans-decouvrir-microsoft-azure: Downloading 720p JSON metadata
[linkedin:learning] bienvenue-dans-decouvrir-microsoft-azure: Downloading m3u8 information
[debug] Invoking downloader on 'https://files3.lynda.com/secure/courses/753099/VBR_MP4h264_main_HD720/FR_1928_u1_trailer_WL25R.mp4?4u2ef-BjSsH2F_c3S7ZT0OrnDqvHVCT-8M5OChUclQOu5GlQnCZuwOqsXb4bbTQneC0aT-vtxjo5B4KO5e9-4hs5OFD5pseWfyfM266zBmyoawvJhWQlx8ifWtl3fcmoMOqwMZO6B5aKuQ-qBDrlkCty9oxvAsdbMkGsVDOPId4U4UTKKLsKwA'
[download] Sleeping 30 seconds...
[download] Destination: Découvrir Microsoft Azure/1 - Introduction/01 - Bienvenue dans « Découvrir Microsoft Azure ».mp4
[download] 100% of 6.63MiB in 00:27
```

It seems that non-working videos lacks this line:

```
[linkedin:learning] bienvenue-dans-decouvrir-microsoft-azure: Downloading m3u8 information
```

Is there a workaround?

**Comment by D3boker1** [comment]
I have the same problem... Any solution?

**Comment by D3boker1** [comment]
Hi, @camillehuot how did you install youtube-dl? 
curl? apt (or other package managers)? 

If you are on debian based systems I recommend you to uninstall and install by curl (i don't test in other systems), I have the same problem and is now solved!

**Comment by camillehuot** [comment]
Hi, I'm closing since I do not have access to Linkedin Learning anymore. And thanks to @D3boker1, the feedback is that it seems to be solved.
