### ISSUE TITLE
need help about Gaia

### ISSUE THREAD

**Issue by jaan143** [ytdl-org/youtube-dl#25802]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
i was able to use gaia.com for downloading videos and it was working fine 3 days before but now its not working on my side i dont know i am doing mistake in command or site have problem 
but same command i always use and it worked fine here is issue please help me to solve it
==================
![Capture](https://user-images.githubusercontent.com/15013833/85855110-24b24e80-b7cf-11ea-918f-f00a0712f080.JPG)

PS C:\Users\HDNLSR> youtube-dl --verbose -o 'P:\contents\New folder/%(playlist)s/%(chapter_number)s - %(chapter)s/%(t
itle)s.%(ext)s' --ignore-errors -u *******.com -p ** https://www.gaia.com/video/flow-rejuvenation?fullplayer=f
eature
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-o', 'P:\\contents\\New folder/%(playlist)s/%(chapter_number)s - %(chapter)s/%
(title)s.%(ext)s', '--ignore-errors', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.gaia.com/video/flow-rejuvenation?fu
llplayer=feature']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.6.0 (CPython) - Windows-2012ServerR2-6.3.9600-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[Gaia] Downloading JSON metadata
[Gaia] flow-rejuvenation: Downloading JSON metadata
[Gaia] 200811: Downloading JSON metadata
[Gaia] 200693: Downloading JSON metadata
[Gaia] 200693: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://hls.gaia.com/hls/200693/5/rendition.m3u8?provider=bc-ak&expiration=1593259200&to
ken=a9129c9fa9267bcb50c2299e187e0b7692d1d8c43972c2c962efc74af9dd47aa'
[download] Destination: P:\contents\New folder\NA\NA - NA\Flow for Rejuvenation.mp4
ERROR: m3u8 download detected but ffmpeg or avconv could not be found. Please install one.
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\youtube-dl.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\program files\python36\lib\site-packages\youtube_dl\__init__.py", line 474, in main
    _real_main(argv)
  File "c:\program files\python36\lib\site-packages\youtube_dl\__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "c:\program files\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "c:\program files\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\program files\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "c:\program files\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 1644, in process_video_result
    self.process_info(new_info)
  File "c:\program files\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "c:\program files\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "c:\program files\python36\lib\site-packages\youtube_dl\downloader\common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "c:\program files\python36\lib\site-packages\youtube_dl\downloader\external.py", line 35, in real_download
    retval = self._call_downloader(tmpfilename, info_dict)
  File "c:\program files\python36\lib\site-packages\youtube_dl\downloader\external.py", line 227, in _call_downloader
    self.report_error('m3u8 download detected but ffmpeg or avconv could not be found. Please install one.')
  File "c:\program files\python36\lib\site-packages\youtube_dl\downloader\common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "c:\program files\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "c:\program files\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 587, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

ERROR: unable to download video data: [WinError 2] The system cannot find the file specified: 'P:\\contents\\New folder\
\NA\\NA - NA\\Flow for Rejuvenation.mp4.part'
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "c:\program files\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "c:\program files\python36\lib\site-packages\youtube_dl\downloader\common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "c:\program files\python36\lib\site-packages\youtube_dl\downloader\external.py", line 52, in real_download
    fsize = os.path.getsize(encodeFilename(tmpfilename))
  File "c:\program files\python36\lib\genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'P:\\contents\\New folder\\NA\\NA - NA\\Flow
for Rejuvenation.mp4.part'

PS C:\Users\HDNLSR>

**Comment by kikuyan** [comment]
> ERROR: m3u8 download detected but ffmpeg or avconv could not be found. Please install one.

As shown in the log, you need to install ffmpeg.
