### ISSUE TITLE
[YouTube] Failing to download videos from channel page. Python issues.

### ISSUE THREAD

**Issue by notacompletemoron** [ytdl-org/youtube-dl#25828]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PS D:\Videos> .\youtube-dl.exe https://www.youtube.com/channel/UC6G1JXzujoBrE7MC6mV-peQ -v
[debug] System config: []
[debug] User config: ['--external-downloader', 'aria2c', '--external-downloader-args', '-c -j 3 -x 3 -s 3 -k 1M', '--add-metadata', '--write-all-thumbnails', '--write-info-json', '--embed-subs', '--all-subs', '-o', 'D:/Videos/%(uploader)s/%(title)s.%(ext)s', '-f', 'best', '--ffmpeg-location', 'C:/ffmpeg/bin', '--download-archive', 'D:/Videos/downloaded.txt']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/channel/UC6G1JXzujoBrE7MC6mV-peQ', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-02-11-f15007a, ffprobe git-2020-02-11-f15007a
[debug] Proxy map: {}
[youtube:channel] UC6G1JXzujoBrE7MC6mV-peQ: Downloading channel page
[youtube:playlist] UU6G1JXzujoBrE7MC6mV-peQ: Downloading webpage
[download] Downloading playlist: Uploads from William Maranci
[youtube:playlist] UU6G1JXzujoBrE7MC6mV-peQ: Downloading page #1
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 870, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 969, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\youtube.py", line 313, in _entries
KeyError: 'content_html'
```

## Description

I updated youtube-dl (which was successful), and now I cannot download videos from YouTube. I searched for relevant issues (both open and closed) and found SOMETHING about a cert issue with no real solution (Issue #25491 ), so I'm opening a new bug report.

**Comment by notacompletemoron** [comment]
I'm an idiot. The first update said it's good. Reading the log, it wasn't.

Updated again, and it's now working.
