### ISSUE TITLE
[rtlnl] changed url

### ISSUE THREAD

**Issue by ddland** [ytdl-org/youtube-dl#25821]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.rtlxl.nl/programma/rtl-nieuws/da2963c3-c468-3d89-b764-0edb0450c211']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Git HEAD: e942cfd1a
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-9-amd64-x86_64-with-debian-10.4
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] da2963c3-c468-3d89-b764-0edb0450c211: Requesting header
WARNING: Falling back on generic information extractor.
[generic] da2963c3-c468-3d89-b764-0edb0450c211: Downloading webpage
[generic] da2963c3-c468-3d89-b764-0edb0450c211: Extracting information
ERROR: Unsupported URL: https://www.rtlxl.nl/programma/rtl-nieuws/da2963c3-c468-3d89-b764-0edb0450c211
Traceback (most recent call last):
  File "/home/derek/test/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/derek/test/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/derek/test/youtube-dl/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.rtlxl.nl/programma/rtl-nieuws/da2963c3-c468-3d89-b764-0edb0450c211
```

## Description

rtlxl.nl changed their website. In the url 'programma' is added. With an updated regexp everything works again, fixed in  #25816

In order to test the new regexp also the unittests are updated, old episodes were not available anymore.

**Comment by jscoursera** [comment]
A fix for this change would be highly appreciated :-)
