### ISSUE TITLE
BBC iPlayer - fails to log in

### ISSUE THREAD

**Issue by bitplane** [ytdl-org/youtube-dl#25830]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.bbc.co.uk/iplayer/episode/m000kjlh/glastonbury-david-bowie', '-u', 'PRIVATE', '--verbose']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.2 (CPython) - Linux-5.4.0-37-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[bbc.co.uk] Downloading signin page
[bbc.co.uk] Logging in
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 529, in extract
    self.initialize()
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 433, in initialize
    self._real_initialize()
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/bbc.py", line 297, in _real_initialize
    self._login()
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/bbc.py", line 294, in _login
    raise ExtractorError('Unable to log in')
youtube_dl.utils.ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

BBC iPlayer downloads require sign-in nowadays, and youtube-dl fails to log in. Accounts are available for free to anyone in the UK who says they have a TV license, or any liar with a decent proxy.

I've dumped the URL from the failing step (where it POSTs the password) and it looks like it's missing `userOrigin` and `ptrt` query parameters. I get the same error for a good login and password or a bad one.

I haven't looked at the cookies or compared the form data yet. Will update if I get chance to dump those.

**Comment by ilike2burnthing** [comment]
Login is not needed for youtube-dl

**Comment by bitplane** [comment]
Oh, you're right! I guess this doesn't matter until they finally block it then :)

I'll close
