### ISSUE TITLE
TF1 broken

### ISSUE THREAD

**Issue by tactactac** [ytdl-org/youtube-dl#25836]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
london@debian:~$ youtube-dl --verbose "https://www.tf1.fr/tf1/direct" 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.tf1.fr/tf1/direct']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-9-amd64-x86_64-with-debian-10.4
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[TF1] direct: Downloading webpage
ERROR: Unable to extract wat id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tf1.py", line 78, in _real_extract
    for key, video in data.items()
StopIteration
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tf1.py", line 90, in _real_extract
    webpage, 'wat id', group='id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract wat id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

london@debian:~$ 

## Description

Hi,
I just discovered that youtube-dl had a feature to watch normal Tv channels beside youtube and others.
So naturally I chacked my local TV stations.
France TV  OK
TF1    doesn't work
I first tried to catch the link with "youtube-dl -g URL" but I don't think it's relevant.

I guess it is fixable ?

Thanks!

WRITE DESCRIPTION HERE
TF1 BROKEN

**Comment by tactactac** [comment]
Hi,
I just discovered that youtube-dl had a feature to watch normal Tv channels beside youtube and others.
So naturally I chacked my local TV stations.
France TV OK
TF1 doesn't work

I guess it is fixable ?

Thanks!

**Comment by tactactac** [comment]
Hi,
I just discovered that youtube-dl had a feature to watch normal Tv channels beside youtube and others.
So naturally I chacked my local TV stations.
France TV OK
TF1 doesn't work

I guess it is fixable ?

Thanks!
