### ISSUE TITLE
Can't self-update: "ERROR: can't find the current version. Please try again later."

### ISSUE THREAD

**Issue by grishka** [ytdl-org/youtube-dl#25859]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ sudo youtube-dl -U -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-U', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1-tessus, ffprobe N-91679-g4d87cd2882
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/update.py", line 46, in update_self
    newversion = opener.open(VERSION_URL).read().decode('utf-8').strip()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2736, in https_open
    req, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>

ERROR: can't find the current version. Please try again later.


$ sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
```

## Description

Updating fails with an expired SSL certificate error, when both using `youtube-dl -U` and curl. The exact same URL works fine in the browser. Using curl with an http URL instead of https works too. I'm running macOS 10.14.6.

Now, I have no idea which SSL certificate has expired, because OpenSSL accepts the entire chain just fine:
```
$ openssl s_client -connect yt-dl.org:443
CONNECTED(00000005)
depth=2 C = BE, O = GlobalSign nv-sa, OU = Root CA, CN = GlobalSign Root CA
verify return:1
depth=1 C = BE, O = GlobalSign nv-sa, CN = AlphaSSL CA - SHA256 - G2
verify return:1
depth=0 OU = Domain Control Validated, CN = *.aries.uberspace.de
verify return:1
---
Certificate chain
 0 s:/OU=Domain Control Validated/CN=*.aries.uberspace.de
   i:/C=BE/O=GlobalSign nv-sa/CN=AlphaSSL CA - SHA256 - G2
 1 s:/C=BE/O=GlobalSign nv-sa/CN=AlphaSSL CA - SHA256 - G2
   i:/C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIHcTCCBlmgAwIBAgIMEQ4ywOKoHkgaAEokMA0GCSqGSIb3DQEBCwUAMEwxCzAJ
BgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMSIwIAYDVQQDExlB
bHBoYVNTTCBDQSAtIFNIQTI1NiAtIEcyMB4XDTE5MDQxMDA5NDQxMloXDTIxMDYw
OTE1MDc0MlowQjEhMB8GA1UECxMYRG9tYWluIENvbnRyb2wgVmFsaWRhdGVkMR0w
GwYDVQQDDBQqLmFyaWVzLnViZXJzcGFjZS5kZTCCAiIwDQYJKoZIhvcNAQEBBQAD
ggIPADCCAgoCggIBALV7px7LnBh9E51F/Vhedy2zxe4xA0SGfglqV/rbSo/69kpu
D07C0c6yn0MS8ufyu4nNNzZ5UHWMir1kx3LLVl58/LUOSnG1Jb6tiApOf3HpwMI+
pl5DzVKeTM0gsgW/PyhlHwOJiicVCs0C/7pT1t8Zu1zC0XzTnL8ghHxZzhz8/OFw
CUnOTNBLwtP2dwB5qrM3M2ZDmmoznZKfACIty5GXFAKquruE4ee69E5LPKxj2Tgt
ke/0wzWjfgS9pJiHYXwDXdQGSc654Q7s5Rv5YJy7BPoz6Lm1x/PQE50RocI4eMiT
rWbe+HGeNTWfFXcE66cXswzCRzFrS7Xa/HqEVXUt9gYYsu2IFrIGjR/5VNyXjvxY
7R9BnWL3qgUCTV0w2rJdG82GgpkIIEYcMkXXmqoNWxZZlSNOIDHedyWwLKbKRpAv
dfJOsa2ZWd/PkaCU2uaziIS8CFuIExlBRRXhOm/15Bg1+cPLsnPDBYUo+6jcc3Yw
tclgu2FZE1KQDkftz4VLeFcu50vHZDvCdJrvY6yhp70zTI8/AQD26VUkHR9jfdru
oZzypYyRKGJhn7bcBl117R3MmwUFrNCCldoCkq3Nggj28/SzARXY0xqa8jXS++F3
wQ5do6rVyZEbxN8ZLjBo94App0cyZKwPXu+81nXN4A5H+Qezsk1/vnoGuB4HAgMB
AAGjggNbMIIDVzAOBgNVHQ8BAf8EBAMCBaAwgYkGCCsGAQUFBwEBBH0wezBCBggr
BgEFBQcwAoY2aHR0cDovL3NlY3VyZTIuYWxwaGFzc2wuY29tL2NhY2VydC9nc2Fs
cGhhc2hhMmcycjEuY3J0MDUGCCsGAQUFBzABhilodHRwOi8vb2NzcDIuZ2xvYmFs
c2lnbi5jb20vZ3NhbHBoYXNoYTJnMjBXBgNVHSAEUDBOMEIGCisGAQQBoDIBCgow
NDAyBggrBgEFBQcCARYmaHR0cHM6Ly93d3cuZ2xvYmFsc2lnbi5jb20vcmVwb3Np
dG9yeS8wCAYGZ4EMAQIBMAkGA1UdEwQCMAAwPgYDVR0fBDcwNTAzoDGgL4YtaHR0
cDovL2NybDIuYWxwaGFzc2wuY29tL2dzL2dzYWxwaGFzaGEyZzIuY3JsMDMGA1Ud
EQQsMCqCFCouYXJpZXMudWJlcnNwYWNlLmRlghJhcmllcy51YmVyc3BhY2UuZGUw
HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMB0GA1UdDgQWBBSZjgQIVctl
CF+sKO+d48AN7F+NDzAfBgNVHSMEGDAWgBT1zdU8CFD5ak86t5faVoPmadJo9zCC
AX8GCisGAQQB1nkCBAIEggFvBIIBawFpAHcAVYHUwhaQNgFK6gubVzxT8MDkOHhw
JQgXL6OqHQcT0wwAAAFqBqIy7AAABAMASDBGAiEAslIiepBs7c3zz+N/6EwQ7+nU
q+PH0998qoOGMm1vpdECIQDYIi3nindz4eCxP/LP7kKouCQ1UK92yHDNf4MnNp0O
DAB1ALvZ37wfinG1k5Qjl6qSe0c4V5UKq1LoGpCWZDaOHtGFAAABagaiMs0AAAQD
AEYwRAIgSmptGS5wHnGoZGWJSFw++BJvgd1KNVhb7KTjdR606gACIGtwIiSf5neh
/kEZfJnUZxqvwFMP0bVttzvygAYtpthXAHcAb1N2rDHwMRnYmQCkURX/dxUcEdkC
wQApBo2yCJo32RMAAAFqBqIzGAAABAMASDBGAiEAgWDwvg8l1f764e+rprVq68cM
oIr1KXj/ZY7gULuWNj4CIQCHB+xsaTzFezLhxK1tdEmHQy3ZgqL723TWC7qk5Ky7
5jANBgkqhkiG9w0BAQsFAAOCAQEAJNZxEK7q3hEk4RGyYMW7e9/MumATBxfN3fLO
sfGyycpKfaDoB7ygqm1LX577Oc8lf2MCoqIW6UpAjawhrYlfc4dY2P7u0dc12xem
pYe2j7DphC3vTyaQyz1Ah3yJlFIuIRqD+jZhhVIJwVWsXT8I1DLx3p2lKNrVxuwe
kyYzMsctF9J1TIGYdCWat+qyjbEqrS8+jD6e33AAJ8SbczSASD74lsVCjv0SzpCh
h+NMGpcApK3WF/KMWYYXW1XhgBaCp3MLWvAZDimhnVJfO6bB6TlqydaF82zh38xa
N4792+nFz80FcFpk+MDjYJxYnF1RFjlAcMb5BBUnaRJOsoCFZQ==
-----END CERTIFICATE-----
subject=/OU=Domain Control Validated/CN=*.aries.uberspace.de
issuer=/C=BE/O=GlobalSign nv-sa/CN=AlphaSSL CA - SHA256 - G2
---
No client certificate CA names sent
Server Temp Key: DH, 4096 bits
---
SSL handshake has read 4897 bytes and written 774 bytes
---
New, TLSv1/SSLv3, Cipher is DHE-RSA-AES256-GCM-SHA384
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : DHE-RSA-AES256-GCM-SHA384
    Session-ID: AA71EB20F3A5A9E9F0BECC5BDA8B28853BB74968051FE33E0A6204294E2D3513
    Session-ID-ctx: 
    Master-Key: C513BBC529912DFC962E215AF6AC684C0E397C923B2E799D2548E0E8BC7F4B3C48C332280013AB23FFC79207B6DEEA10
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - d8 50 bc b5 48 ed 1c 3d-6b 8d 50 78 9e 84 2a 9c   .P..H..=k.Px..*.
    0010 - 7a 7a 34 d4 11 ac e2 8a-eb 80 04 b1 75 d8 d5 7e   zz4.........u..~
    0020 - df 80 6a 8b 35 1e 58 16-e8 76 c5 fd 4b bb 49 c1   ..j.5.X..v..K.I.
    0030 - e0 2b 52 17 69 a9 85 69-10 b0 21 4c 9e 17 54 83   .+R.i..i..!L..T.
    0040 - b2 59 b7 22 10 b4 bf 7f-73 f9 ba 3e 32 3e 54 7c   .Y."....s..>2>T|
    0050 - 56 00 5b 12 68 d1 b1 27-6d f5 56 b5 84 1a fd 3b   V.[.h..'m.V....;
    0060 - f0 4f af 20 30 38 5c 0b-6b d3 f0 24 55 01 07 91   .O. 08\.k..$U...
    0070 - 33 28 7e a4 22 19 b1 5b-f0 ec 7f 45 f4 55 bb de   3(~."..[...E.U..
    0080 - b3 e5 9b 81 c2 93 06 25-f9 e9 02 db 88 4d ad 0c   .......%.....M..
    0090 - 87 50 9a ac 1f 5c 16 15-1c 07 fb f1 d2 f3 bb 8a   .P...\..........
    00a0 - 78 c7 8c 0d e6 3a 09 ab-9b e2 be 5c 2e 30 f3 79   x....:.....\.0.y

    Start Time: 1593601868
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
```
I'd happily provide anything else needed to debug this issue, but I'm kinda clueless as to what else to check.

**Comment by serge-sb** [comment]
@grishka Could you please update your python installation to the latest version (3.8.5) and try again?
