### ISSUE TITLE
Download Playlist error on youtube (Unable to extract video title)

### ISSUE THREAD

**Issue by c4tom** [ytdl-org/youtube-dl#25878]
## Checklist

- [ x ] I'm reporting a broken site support issue
- [ x ] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [ x ] I've checked that all provided URLs are alive and playable in a browser
- [ x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'mp4', u'--playlist-start', u'488', u'--verbose', u'https://www.youtube.com/playlist?list=PLShoj3jUBZKmDucSdpCIS0Utw7mq8F95Y']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-108-generic-x86_64-with-LinuxMint-19.2-tina
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PLShoj3jUBZKmDucSdpCIS0Utw7mq8F95Y: Downloading webpage
[download] Downloading playlist: Mensagens de poder!
[youtube:playlist] PLShoj3jUBZKmDucSdpCIS0Utw7mq8F95Y: Downloading page #1
[youtube:playlist] PLShoj3jUBZKmDucSdpCIS0Utw7mq8F95Y: Downloading page #2
[youtube:playlist] PLShoj3jUBZKmDucSdpCIS0Utw7mq8F95Y: Downloading page #3
[youtube:playlist] PLShoj3jUBZKmDucSdpCIS0Utw7mq8F95Y: Downloading page #4
[youtube:playlist] PLShoj3jUBZKmDucSdpCIS0Utw7mq8F95Y: Downloading page #5
[youtube:playlist] PLShoj3jUBZKmDucSdpCIS0Utw7mq8F95Y: Downloading page #6
[youtube:playlist] playlist Mensagens de poder!: Downloading 196 videos
[download] Downloading video 1 of 196
[youtube] rbam0WHQRZ0: Downloading webpage
[youtube] rbam0WHQRZ0: Downloading MPD manifest
[debug] Invoking downloader on u'https://r3---sn-cg51pauxax-jfcz.googlevideo.com/videoplayback?expire=1593766147&ei=o5z-XpudJ6m65gTJvqz4Bw&ip=177.3.74.170&id=o-AP7mKMhmIDW9LjaEKihQW4KfwIsOQR4KMXgsgCrMd7g5&itag=22&source=youtube&requiressl=yes&mh=Ok&mm=31%2C29&mn=sn-cg51pauxax-jfcz%2Csn-bg0eznek&ms=au%2Crdu&mv=m&mvi=2&pl=23&initcwndbps=432500&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=2638.181&lmt=1593736676078884&mt=1593744450&fvip=3&c=WEB&txp=6216222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAK2yRf9jf0WtRMEJZnff8HT6Vz_GxYB3vmshQOR6l_7iAiEAhmf0O9C2Lygs-USgvnXw4-28w7CBgVSDQfa1W2pcDnc%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhANA_1e_kraODPctuFFoDMDJ9CEL_CcqrPI8g_5ONX4LVAiEAxiX54xwHJpFsnTRabF6FPEitWKNwpU2LxSnr6Z3m5CU%3D'
[download] 203   Como Deus terminará de preparar Seu povo para a vinda de Cristo (04- 03-2015)-rbam0WHQRZ0.mp4 has already been downloaded
[download] 100% of 196.41MiB
[download] Downloading video 2 of 196
[youtube] BtvowHu_iig: Downloading webpage
[youtube] BtvowHu_iig: Downloading embed webpage
[youtube] BtvowHu_iig: Refetching age-gated info webpage
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2212, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.

```

## Description

i try to download this playlist, command here:

`youtube-dl -f mp4 --playlist-start 488 --verbose 	 https://www.youtube.com/playlist?list=PLShoj3jUBZKmDucSdpCIS0Utw7mq8F95Y`

the video is public, and i can download it directly

**Comment by dstftw** [comment]
Video is private as clearly seen from browser.
