### ISSUE TITLE
ERROR: Conversion failed!

### ISSUE THREAD

**Issue by TarekSalama** [ytdl-org/youtube-dl#25883]
- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
```
D:\Youtube-dl>youtube-dl -v --no-overwrites --no-cache-dir --batch-file "D:\Youtube-dl\batchmusic.txt" -o "D:\Youtube-dl\music\%(uploader)s\%(title)s.%(ext)s"--extract-audio --audio-format mp3 --audio-quality 0 --embed-thumbnail --metadata-from-title "(?P<artist>.+?) - (?P<title>.+)" --add-metadata
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-overwrites', '--no-cache-dir', '--batch-file', 'D:\\Youtube-dl\\batchmusic.txt', '-o', 'D:\\Youtube-dl\\music\\%(uploader)s\\%(title)s.%(ext)s--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0', '--embed-thumbnail', '--metadata-from-title', '(?P<artist>.+?) - (?P<title>.+)', '--add-metadata']
[debug] Batch file urls: ['https://www.youtube.com/playlist?list=PLK62AmUirhOjQ5r0RWriz15Y565qkstS7']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3
[debug] Proxy map: {}
[youtube:playlist] PLK62AmUirhOjQ5r0RWriz15Y565qkstS7: Downloading webpage
[download] Downloading playlist: Music to download
[youtube:playlist] playlist Music to download: Downloading 15 videos
[download] Downloading video 1 of 15
[youtube] aO9T6pNhnjE: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[youtube] aO9T6pNhnjE: Thumbnail is already present
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] D:\Youtube-dl\music\EuphoricHardStyleZ\Adventuner - Tropic (Snowstylez Remix) [Free Release].mp4--extract-audio.mkv has already been downloaded and merged
[fromtitle] parsed artist: Adventuner
[fromtitle] parsed title: Tropic (Snowstylez Remix) [Free Release]
[ffmpeg] Adding metadata to 'D:\Youtube-dl\music\EuphoricHardStyleZ\Adventuner - Tropic (Snowstylez Remix) [Free Release].mp4--extract-audio.mkv'
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:D:\Youtube-dl\music\EuphoricHardStyleZ\Adventuner - Tropic (Snowstylez Remix) [Free Release].mp4--extract-audio.mkv" -c copy -metadata "artist=Adventuner" -metadata "purl=https://www.youtube.com/watch?v=aO9T6pNhnjE" -metadata "description=#atmospheric #euphoric #hardstyle

...:..::..:::  .Upload.Info.  :::..::..:...

.Artist: Adventuner
.Title: Tropic (Snowstylez Remix)
.Label: Upcoming Free Release
.Date: n/a
.Quality: 1411 kbps WAV / 44.100Hz / Stereo

...:..::..:::  .Artist.Info.  :::..::..:...

https://www.facebook.com/snowstylez
https://soundcloud.com/snowstylez
https://www.youtube.com/channel/UCQs7EdXdZb-iEDn0r6Ex4oQ
https://www.instagram.com/snowstylezofficial

..:.::  .EuphoricHardStyleZ.Info.  ::.:..

.YouTube: https://is.gd/ehsz_youtube
.Facebook: https://is.gd/ehsz_facebook
.SoundCloud: https://is.gd/ehsz_soundcloud
.Spotify: https://is.gd/ehsz_spotify

...:..::..:::  .Artwork.Info.  :::..::..:...

.Wallpapers: https://is.gd/ehsz_wallpapers

Special thanks goes to Alexiuss: http://alexiuss.deviantart.com with the art \"Machinery of the Stars\" http://fav.me/d15glb1

...:..::..:::  .Channel.Info.  :::..::..:...

This channel is dedicated to the more melodic, uplifting and euphoric side of hardstyle. I'm always trying my best to upload in the best possible sound quality by remastering if necessary.

Both latest and greatest from both non-signed and signed artists as well as older classics will be featured. Requests and suggestions are welcome.

...:..::..:::  .Contact.Info.  :::..::..:...

If you are an upcoming producer with minimum 3 years of experience don't hesitate to contact me at euphorichardstylez@gmail.com or give me a PM either here on YouTube or Facebook and I might concider uploading your track(s). Every track will be auditioned but every demo will not recieve a reply due to limited amount of time at hand.

I can also master your tracks if desired for free using professional mastering tools and my own experience. I might not accept every track for mastering depending on how busy I am.

...:..::..:::  .Legal.Info.  :::..::..:...

I'm doing this out of promoting point of view only, I do not take advantage of advertising or sponsorship, I'm doing this mostly for free as a hobby! All rights goes to the producers and the labels and other involved acts.

If YOU, the artist, label manager or a 3rd party find some of my uploads inappropriate, please email me at euphorichardstylez@gmail.com or give me a private message and I'll remove it as soon as possible, thanks!

. EuphoricHardStyleZ - The best of the Euphoric Stylez ." -metadata "comment=#atmospheric #euphoric #hardstyle

...:..::..:::  .Upload.Info.  :::..::..:...

.Artist: Adventuner
.Title: Tropic (Snowstylez Remix)
.Label: Upcoming Free Release
.Date: n/a
.Quality: 1411 kbps WAV / 44.100Hz / Stereo

...:..::..:::  .Artist.Info.  :::..::..:...

https://www.facebook.com/snowstylez
https://soundcloud.com/snowstylez
https://www.youtube.com/channel/UCQs7EdXdZb-iEDn0r6Ex4oQ
https://www.instagram.com/snowstylezofficial

..:.::  .EuphoricHardStyleZ.Info.  ::.:..

.YouTube: https://is.gd/ehsz_youtube
.Facebook: https://is.gd/ehsz_facebook
.SoundCloud: https://is.gd/ehsz_soundcloud
.Spotify: https://is.gd/ehsz_spotify

...:..::..:::  .Artwork.Info.  :::..::..:...

.Wallpapers: https://is.gd/ehsz_wallpapers

Special thanks goes to Alexiuss: http://alexiuss.deviantart.com with the art \"Machinery of the Stars\" http://fav.me/d15glb1

...:..::..:::  .Channel.Info.  :::..::..:...

This channel is dedicated to the more melodic, uplifting and euphoric side of hardstyle. I'm always trying my best to upload in the best possible sound quality by remastering if necessary.

Both latest and greatest from both non-signed and signed artists as well as older classics will be featured. Requests and suggestions are welcome.

...:..::..:::  .Contact.Info.  :::..::..:...

If you are an upcoming producer with minimum 3 years of experience don't hesitate to contact me at euphorichardstylez@gmail.com or give me a PM either here on YouTube or Facebook and I might concider uploading your track(s). Every track will be auditioned but every demo will not recieve a reply due to limited amount of time at hand.

I can also master your tracks if desired for free using professional mastering tools and my own experience. I might not accept every track for mastering depending on how busy I am.

...:..::..:::  .Legal.Info.  :::..::..:...

I'm doing this out of promoting point of view only, I do not take advantage of advertising or sponsorship, I'm doing this mostly for free as a hobby! All rights goes to the producers and the labels and other involved acts.

If YOU, the artist, label manager or a 3rd party find some of my uploads inappropriate, please email me at euphorichardstylez@gmail.com or give me a private message and I'll remove it as soon as possible, thanks!

. EuphoricHardStyleZ - The best of the Euphoric Stylez ." -metadata "date=20200422" -metadata "title=Tropic (Snowstylez Remix) [Free Release]" "file:D:\Youtube-dl\music\EuphoricHardStyleZ\Adventuner - Tropic (Snowstylez Remix) [Free Release].mp4--extract-audio.temp.mkv"
ERROR: Only mp3 and m4a/mp4 are supported for thumbnail embedding for now.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 2065, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\postprocessor\embedthumbnail.py", line 91, in run
youtube_dl.postprocessor.embedthumbnail.EmbedThumbnailPPError: Only mp3 and m4a/mp4 are supported for thumbnail embedding for now.


D:\Youtube-dl>
```

## Description

Recently I have been getting `ERROR: Conversion failed!` a lot. It seems like the mp3 file is downloaded fine and it plays fine but it doesn't have the thumbnail.
I have tried on Windows 10 and Ubuntu (WSL). I also tried an older ffmpeg installation and an older youtube-dl version. Nothing works. I am not sure what changed. Everything worked fine like a couple of weeks ago.
I am not sure how to troubleshoot at this point.

Let me know if you need more logs/info. Thanks!

EDIT1: I also noticed that the whole playlist download terminates randomly as well since the list has more than 2 Youtube videos.
EDIT2: This is my configuration file which has been working for over a year without any problems
```
--no-overwrites --no-cache-dir --batch-file "D:\Youtube-dl\batchmusic.txt" -o "D:\Youtube-dl\music\%(uploader)s\%(title)s.%(ext)s"
--extract-audio --audio-format mp3 --audio-quality 0 --embed-thumbnail --metadata-from-title "(?P<artist>.+?) - (?P<title>.+)" --add-metadata 
```

**Comment by unixgirl** [comment]
Hi there guys, I'm getting the same error on a debian 64 bit, it has been installed the alternatively way - sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl

After the download and conversion process I get three files - the image, .mp3 and tem mp3 
There is no thumbnail image in the mp3 file, and the error is - Conversion failed!
Would be nice some workaround, thank you.

**Comment by dstftw** [comment]
There is no `Conversion failed!` in your log at all.

**Comment by unixgirl** [comment]
Yes there is, please look at the last row!
