### ISSUE TITLE
ERROR: Conversion failed!

### ISSUE THREAD

**Issue by unixgirl** [ytdl-org/youtube-dl#25889]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X ] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar bug reports including closed ones
- [ X] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
nixgirl@digitaliskupleraj:~$ youtube-dl -v --extract-audio --add-metadata --embed-thumbnail --audio-quality 0 --audio-format mp3 https://www.youtube.com/watch?v=r0GQrp2DeCc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--extract-audio', u'--add-metadata', u'--embed-thumbnail', u'--audio-quality', u'0', u'--audio-format', u'mp3', u'https://www.youtube.com/watch?v=r0GQrp2DeCc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.18 (CPython) - Linux-5.6.0-kali2-amd64-x86_64-with-debian-kali-rolling
[debug] exe versions: ffmpeg 4.3-2, ffprobe 4.3-2
[debug] Proxy map: {}
[youtube] r0GQrp2DeCc: Downloading webpage
[youtube] {18} signature length 107, html5 player 54668ca9
[youtube] {136} signature length 107, html5 player 54668ca9
[youtube] {247} signature length 107, html5 player 54668ca9
[youtube] {135} signature length 103, html5 player 54668ca9
[youtube] {244} signature length 103, html5 player 54668ca9
[youtube] {134} signature length 107, html5 player 54668ca9
[youtube] {243} signature length 107, html5 player 54668ca9
[youtube] {133} signature length 107, html5 player 54668ca9
[youtube] {242} signature length 107, html5 player 54668ca9
[youtube] {160} signature length 103, html5 player 54668ca9
[youtube] {278} signature length 107, html5 player 54668ca9
[youtube] {140} signature length 107, html5 player 54668ca9
[youtube] {251} signature length 107, html5 player 54668ca9
[youtube] r0GQrp2DeCc: Downloading MPD manifest
[youtube] r0GQrp2DeCc: Downloading thumbnail ...
[youtube] r0GQrp2DeCc: Writing thumbnail to: Baila Morena 2020 (Julio Iglesias) - cover version [ guitar & saxophone ]-r0GQrp2DeCc.webp
[debug] Invoking downloader on u'https://manifest.googlevideo.com/api/manifest/dash/expire/1593872771/ei/Iz0AX8_-I46cgQffj7xI/ip/91.82.133.12/id/af4190ae9d837827/source/youtube/requiressl/yes/playback_host/r3---sn-qpbpu8-c0qs.googlevideo.com/mh/OH/mm/31%2C29/mn/sn-qpbpu8-c0qs%2Csn-c0q7lnse/ms/au%2Crdu/mv/m/mvi/2/pl/22/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1446250/vprv/1/mt/1593851135/fvip/3/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgPzz8Q2hQVrVhQShwKmkiwUi5F-XALz5KvsTkpPjMckwCIQDPIpPtdjaZcoPEvYwc6KxbQvs2OcEUAIkXPm4GhwDmYA%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIgbM6vVKnVYmiOSeNlBriuj3SkCIUOf_sVVSrBDgD1eP8CIQD9bunx7YfWwWIYmJgp9zyC87IE3Sz_NBjyS-MwegOrTA%3D%3D'
[dashsegments] Total fragments: 28
[download] Destination: Baila Morena 2020 (Julio Iglesias) - cover version [ guitar & saxophone ]-r0GQrp2DeCc.webm
[download] 100% of 4.57MiB in 00:00
[debug] ffmpeg command line: ffprobe -show_streams 'file:Baila Morena 2020 (Julio Iglesias) - cover version [ guitar & saxophone ]-r0GQrp2DeCc.webm'
[ffmpeg] Destination: Baila Morena 2020 (Julio Iglesias) - cover version [ guitar & saxophone ]-r0GQrp2DeCc.mp3
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Baila Morena 2020 (Julio Iglesias) - cover version [ guitar & saxophone ]-r0GQrp2DeCc.webm' -vn -acodec libmp3lame '-q:a' 0 'file:Baila Morena 2020 (Julio Iglesias) - cover version [ guitar & saxophone ]-r0GQrp2DeCc.mp3'
Deleting original file Baila Morena 2020 (Julio Iglesias) - cover version [ guitar & saxophone ]-r0GQrp2DeCc.webm (pass -k to keep)
[ffmpeg] Adding metadata to 'Baila Morena 2020 (Julio Iglesias) - cover version [ guitar & saxophone ]-r0GQrp2DeCc.mp3'
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Baila Morena 2020 (Julio Iglesias) - cover version [ guitar & saxophone ]-r0GQrp2DeCc.mp3' -c copy -metadata 'comment=Karaoke demo version -
COMPLETE  KARAOKE  TRACK  LIST: http://bit.ly/33IUHLq
Compra de karaoke de esta cancion escribeme / Buying a karaoke of this song write me: y.l.nikitenko@gmail.com
#JulioIglesias #BailaMorena #guitar #saxophone' -metadata 'description=Karaoke demo version -
COMPLETE  KARAOKE  TRACK  LIST: http://bit.ly/33IUHLq
Compra de karaoke de esta cancion escribeme / Buying a karaoke of this song write me: y.l.nikitenko@gmail.com
#JulioIglesias #BailaMorena #guitar #saxophone' -metadata 'artist=Yevgeniy Nikitenko Music' -metadata 'title=Baila Morena 2020 (Julio Iglesias) - cover version [ guitar & saxophone ]' -metadata 'date=20190918' -metadata 'purl=https://www.youtube.com/watch?v=r0GQrp2DeCc' 'file:Baila Morena 2020 (Julio Iglesias) - cover version [ guitar & saxophone ]-r0GQrp2DeCc.temp.mp3'
[ffmpeg] Adding thumbnail to "Baila Morena 2020 (Julio Iglesias) - cover version [ guitar & saxophone ]-r0GQrp2DeCc.mp3"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Baila Morena 2020 (Julio Iglesias) - cover version [ guitar & saxophone ]-r0GQrp2DeCc.mp3' -i 'file:Baila Morena 2020 (Julio Iglesias) - cover version [ guitar & saxophone ]-r0GQrp2DeCc.webp' -c copy -map 0 -map 1 '-metadata:s:v' 'title="Album cover"' '-metadata:s:v' 'comment="Cover (Front)"' 'file:Baila Morena 2020 (Julio Iglesias) - cover version [ guitar & saxophone ]-r0GQrp2DeCc.temp.mp3'
ERROR: Conversion failed!
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2065, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/embedthumbnail.py", line 51, in run
    self.run_ffmpeg_multiple_files([filename, thumbnail_filename], temp_filename, options)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: Conversion failed!


```

## Description

WRITE DESCRIPTION HERE
I get a conversation failed error, also the thumbnail is not created in the mp3.

This is not s spam please do not delete it. From the log obviously you can see there is a error.

**Comment by unixgirl** [comment]
ok fakitt
