### ISSUE TITLE
[niconico] unable to download links that start with live/live2

### ISSUE THREAD

**Issue by KindredMantis** [ytdl-org/youtube-dl#25890]
## Checklist
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser,
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-geo-bypass', '-u,', '--username', 'PRIVATE', '-p,', '--password', 'PRIVATE', 'https://live2.nicovideo.jp/watch/lv326842348?ref=top_rookie']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[generic] lv326842348?ref=top_rookie: Requesting header
WARNING: Falling back on generic information extractor.
[generic] lv326842348?ref=top_rookie: Downloading webpage
[generic] lv326842348?ref=top_rookie: Extracting information
ERROR: Unsupported URL: https://live2.nicovideo.jp/watch/lv326842348?ref=top_rookie
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://live2.nicovideo.jp/watch/lv326842348?ref=top_rookie
```

## Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u,', '--username', 'PRIVATE', '-p,', '--password', 'PRIVATE', 'https://live2.nicovideo.jp/watch/lv326814636']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[generic] lv326814636: Requesting header
WARNING: Falling back on generic information extractor.
[generic] lv326814636: Downloading webpage
[generic] lv326814636: Extracting information
ERROR: Unsupported URL: https://live2.nicovideo.jp/watch/lv326814636
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://live2.nicovideo.jp/watch/lv326814636
```

## Description
I'm trying to download from niconico but whenever I use a link thats starts with "live" or "live2" it falls back to the generic information extractor, while for other niconico links that **DON'T** start with "live" or "live2" it will use the niconico extractor as it should. I think the bug is that it doesn't recognize live/live2 links as niconico links. It's hard to provide live/live2 links because they expire over time. the link that I provided in this report is probably also expired unless you have premium for niconico. go to https://live.nicovideo.jp/ and click any available video/stream and I still get the same issue. ( sometimes it's required to remove everything that comes after the question mark in the link, including the question mark), I have tried several links to make sure it's not just one specific video that might be bugged

**Comment by rolyli** [comment]
Someone made a fork with the ability to download live videos. See #17415.

**Comment by yuusakuri** [comment]
That fork no longer works.
Probably because the URL is live2.nicovideo.jp.

**Comment by nudnyzjeb** [comment]
streamlink works nanodesu
