### ISSUE TITLE
AtomicParsley NOT working

### ISSUE THREAD

**Issue by RangaSE** [ytdl-org/youtube-dl#25906]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
Ji, I'm having severe headache for the past two(2) days. So, I just giving Bug Verbose to you for Peace of mind of fellow users. Verbose as follows:
( 05-07-2020 |  0:01:48.60 ) C:\Users\VENKAT> youtube-dl[2020.06.16.1] --playlist-items 11 --yes-playlist -ciw --write-auto-sub --write-sub --embed-subs --embed-thumbnail -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" -o "F:\Videos\%(playlist)s\%(title)s(u%(upload_date)s; %(duration)s; %(height)sp%(fps)s)YT '%(uploader)s'.%(ext)s" -v https://www.youtube.com/playlist?list=PLjhrDIztP9pdKJCdrPrrRxs5hasj7dm_i
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--playlist-items', '11', '--yes-playlist', '-ciw', '--write-auto-sub', '--write-sub', '--embed-subs', '--embed-thumbnail', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '-o', "F:\\Videos\\%(playlist)s\\%(title)s(u%(upload_date)s; %(duration)s; %(height)sp%(fps)s)YT '%(uploader)s'.%(ext)s", '-v', 'https://www.youtube.com/playlist?list=PLjhrDIztP9pdKJCdrPrrRxs5hasj7dm_i']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[youtube:playlist] PLjhrDIztP9pdKJCdrPrrRxs5hasj7dm_i: Downloading webpage
[download] Downloading playlist: SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018
[youtube:playlist] playlist SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018: Downloading 1 videos
[download] Downloading video 1 of 1
[youtube] Q5NLXMnWPbo: Downloading webpage
WARNING: video doesn't have subtitles
[youtube] Q5NLXMnWPbo: Looking for automatic captions
WARNING: Couldn't find automatic captions for Q5NLXMnWPbo
[youtube] Q5NLXMnWPbo: Downloading MPD manifest
[youtube] Q5NLXMnWPbo: Thumbnail is already present
[download] F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam-English Subtitles _ EP 67 _ 14-12-18 _ SVBC TTD(u20181214; 1535; 720p30)YT 'SVBC TTD'.mp4 has already been downloaded and merged
[ffmpeg] There aren't any subtitles to embed
[atomicparsley] Adding thumbnail to "F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam-English Subtitles _ EP 67 _ 14-12-18 _ SVBC TTD(u20181214; 1535; 720p30)YT 'SVBC TTD'.mp4"
[debug] AtomicParsley command line: AtomicParsley "F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam-English Subtitles _ EP 67 _ 14-12-18 _ SVBC TTD(u20181214; 1535; 720p30)YT 'SVBC TTD'.mp4" --artwork "F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam-English Subtitles _ EP 67 _ 14-12-18 _ SVBC TTD(u20181214; 1535; 720p30)YT 'SVBC TTD'.jpg" -o "F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam-English Subtitles _ EP 67 _ 14-12-18 _ SVBC TTD(u20181214; 1535; 720p30)YT 'SVBC TTD'.temp.mp4"
ERROR:
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 2065, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\postprocessor\embedthumbnail.py", line 79, in run
youtube_dl.postprocessor.embedthumbnail.EmbedThumbnailPPError

[download] Finished downloading playlist: SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018

( 05-07-2020 |  0:02:38.19 ) C:\Users\VENKAT> Exit

Please Help! Thanking you,
Rgds, RS.
## Description

WRITE DESCRIPTION HERE
AtomicParsley NOT working! (GitHub/wez version is downloaded, but, AV says It's Dangerous!!)

**Comment by RangaSE** [comment]
Greetings! I think, Google makes pictures in its new picture format, WebP'; you are experts and up to date in programming, can do, such as "Any other Pic. format to .jpg" and using it with AtomicParsley to do its "Artpork". It may be a bleek idea, but, ... worth a try! No hard feelings!!
ATB! Rgds,

**Comment by freewizard** [comment]
should be same as #25717

**Comment by JohnTroke** [comment]
It's the same as  #25687 and #25717 but I can comment on this one and I can give other people some help on how to fix this issue, until the patch comes out i guess.
Basically in the file [https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/postprocessor/embedthumbnail.py](url) you will need to convert .webp to another file that AtomicParsley can read, let's say .png
To do that you can use ffmpeg, here I added a little snippet of code after line 58:
```python
thumbnail_ext = thumbnail_filename[-4:]
if thumbnail_ext == 'webp' :
   old_thumbnail = thumbnail_filename
   new_thumbnail =  thumbnail_filename[:-4] + "png"
   cmd = 'ffmpeg -i ' + old_thumbnail + " " + new_thumbnail + " && rm " + old_thumbnail
   subprocess.call(cmd, shell=True)
   thumbnail_filename = new_thumbnail
```
This is **unsafe**, especially the subprocess call. I don't recommend doing it, but for now it does the job.

**Comment by 89z** [comment]
You can embed image with FFmpeg now, so you don't even need AtomicParsley:

~~~
youtube-dl -x -o audio.m4a Q5NLXMnWPbo

ffmpeg -i audio.m4a -i http://i.ytimg.com/vi/Q5NLXMnWPbo/mqdefault.jpg `
-c:a copy -c:v mjpeg -disposition:v attached_pic media.m4a
~~~
