### ISSUE TITLE
Is it possible to download content from CBS.COM?

### ISSUE THREAD

**Issue by D3ltaq** [ytdl-org/youtube-dl#25901]
## Checklist

- [X] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

```
root@kali:~/Desktop/CBS.COM# youtube-dl -v https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2019/02/07/1438873667622/174171_cenc_dash/stream.mpd
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2019/02/07/1438873667622/174171_cenc_dash/stream.mpd']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.18 (CPython) - Linux-5.6.0-kali2-amd64-x86_64-with-debian-kali-rolling
[debug] exe versions: none
[debug] Proxy map: {}
[generic] stream: Requesting header
WARNING: Falling back on generic information extractor.
[generic] stream: Downloading webpage
[generic] stream: Extracting information
WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2409, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

Hi there, 

I'm trying to use this amazing tool in order to download content from CBS.COM as i noticed it was possible before.

i tried;
 youtube-dl -v https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2019/02/07/1438873667622/174171_cenc_dash/stream.mpd
 youtube-dl -v https://www.cbs.com/movies/charlies-angels-full-throttle/NDpW19Jf_w5UtXedtji8C1qXH_AOSfR3/

Always with the same error.

Is it still possible to download from CBS.com? or i am wasting my time?

Thank you very much in advanced.

**Comment by merval** [comment]
As noted in #17870 cbs.com/movies are DRM locked. cbs.com/shows works though.

**Comment by 89z** [comment]
Issue should be closed, URLs are dead
