### ISSUE TITLE
[tvp] trying to download something else

### ISSUE THREAD

**Issue by selfisekai** [ytdl-org/youtube-dl#25916]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
 self@isekai  ~/youtube-dl   tvp-extractor-fixes ●  youtube-dl -v https://wiadomosci.tvp.pl/48836336/medialne-hieny-atakuja-prezydenta-polski
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://wiadomosci.tvp.pl/48836336/medialne-hieny-atakuja-prezydenta-polski']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.3 (CPython) - Linux-5.6.0-2-amd64-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.2-1, ffprobe 4.2.2-1
[debug] Proxy map: {}
[tvp] 48836336: Downloading webpage
[tvp:embed] 48543077: Downloading webpage
ERROR: tvp:embed said: Transmisja została zakończona lub materiał niedostępny
Traceback (most recent call last):
  File "/home/self/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/self/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/self/.local/lib/python3.8/site-packages/youtube_dl/extractor/tvp.py", line 128, in _real_extract
    raise ExtractorError('%s said: %s' % (
youtube_dl.utils.ExtractorError: tvp:embed said: Transmisja została zakończona lub materiał niedostępny
```

## Description

extractor chooses this video in the sidebar instead of the linked one
![image](https://user-images.githubusercontent.com/11798442/86611606-2dfda100-bfaf-11ea-86d2-b5a855f8e50e.png)

**Comment by selfisekai** [comment]
Fixed in https://haruhi.download, a libre fork of youtube-dl.
