### ISSUE TITLE
brandnewtube.com can list but not download

### ISSUE THREAD

**Issue by ballo** [ytdl-org/youtube-dl#25921]
## Checklist

- [ *] I'm reporting a broken site support
- [ *] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [ *] I've checked that all provided URLs are alive and playable in a browser
- [ *] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ *] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dl -v -f best https://brandnewtube

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'best', u'https://brandnewtube.com/watch/the-spinning-squirrel_WJGgG2PVaVW3r7C.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.16 (CPython) - Darwin-19.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] the-spinning-squirrel_WJGgG2PVaVW3r7C: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-spinning-squirrel_WJGgG2PVaVW3r7C: Downloading webpage
[generic] the-spinning-squirrel_WJGgG2PVaVW3r7C: Extracting information
[download] Downloading playlist: The Spinning Squirrel
[generic] playlist The Spinning Squirrel: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Invoking downloader on u'https://brandnewtube.FRA1.digitaloceanspaces.com/upload/videos/2020/07/HrGE5tItFxnODoZ2RHiJ_06_48e6ff1fc0a282ce2867215b97cfd7ec_video_720p_converted.mp4'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

## Description

WRITE DESCRIPTION HERE

Apparently some videos I can download, but some I cannot. I haven't seen a pattern as yet. I can always list the videos using -F.

**Comment by Mennaruuk** [comment]
I was able to download three videos from brandnewtube (including your example link). Issue can be closed.
