### ISSUE TITLE
NBC's Days of our Lives most recent episode fails to download (but previous ep. works)

### ISSUE THREAD

**Issue by fpl9000** [ytdl-org/youtube-dl#25934]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ffmpeg-location', 'C:\\apps\\ffmpeg\\bin\\ffmpeg.exe', '--format', 'best', '-o', 'ytdl-4194114.mp4', 'https://www.nbc.com/days-of-our-lives/video/tuesday-july-7-2020/4194114']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1, phantomjs 2.1.1
[debug] Proxy map: {}
[NBC] 4194114: Downloading JSON metadata
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\nbc.py", line 135, in _real_extract
TypeError: 'NoneType' object is not subscriptable
```

## Description

The following URL for NBC's "Days of Our Lives" fails to download (see verbose output above). Here is the full command line that I executed in a Bash shell on Windows 10:

`youtube-dl.exe -v --ffmpeg-location 'C:\apps\ffmpeg\bin\ffmpeg.exe' --format best -o 'ytdl-4194114.mp4' 'https://www.nbc.com/days-of-our-lives/video/tuesday-july-7-2020/4194114'`

The same thing happens if I include switch `--no-check-certificate`. This may be caused by a change at NBC's end, because the previous episode can be successfully downloaded — from URL:

https://www.nbc.com/days-of-our-lives/video/monday-july-6-2020/4194113

Let me know if any additional information is needed.
--
Fran

**Comment by 89z** [comment]
URL dead, do you have updated URL?
