### ISSUE TITLE
[TheWeatherChannel] broken extractor

### ISSUE THREAD

**Issue by 2011** [ytdl-org/youtube-dl#25930]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

```
$ youtube-dl -v -f best 'https://weather.com/science/space/video/rare-and-surprising-comet-will-be-visible-this-month'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--restrict-filenames', '-o', '%(title)s-%(id)s-%(uploader)s.%(ext)s', '-w', '-v', '-f', 'best', 'https://weather.com/science/space/video/rare-and-surprising-comet-will-be-visible-this-month']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.6.10 (CPython) - Linux-4.4.221-gentoo-x86_64-Intel-R-_Core-TM-_i5_CPU_750_@_2.67GHz-with-gentoo-2.4.1
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, rtmpdump 2.4
[debug] Proxy map: {}
[TheWeatherChannel] rare-and-surprising-comet-will-be-visible-this-month: Downloading webpage
ERROR: Unable to extract drupal settings; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/theweatherchannel.py", line 31, in _real_extract
    webpage, 'drupal settings'), display_id)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract drupal settings; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Same story (.m3u8 link visible in URL given on command line). I assume the regex in the extractor needs updating.

**Comment by wrldwzrd89** [comment]
Confirmed this is still broken in version 2020-12-22.

**Comment by wrldwzrd89** [comment]
Tested with Python 2.7 and 3.9, just to be sure. Same failure in both cases.
