### ISSUE TITLE
Issue with "--embed-thumbnail" in v2020.06.16.1 when downloading YouTube videos

### ISSUE THREAD

**Issue by AryanNateq** [ytdl-org/youtube-dl#25931]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
./youtube-dl https://www.youtube.com/watch?v=ZiIHyUbLFJg -xv -ciw --audio-quality 0 --audio-format mp3 --embed-thumbnail --ffmpeg-location "C:\Program Files\ffmpeg\bin\ffmpeg.exe"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=ZiIHyUbLFJg', '-xv', '-ciw', '--audio-quality', '0', '--audio-format', 'mp3', '--embed-thumbnail', '--ffmpeg-location', 'C:\\Program Files\\ffmpeg\\bin\\ffmpeg.exe']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] ZiIHyUbLFJg: Downloading webpage
[youtube] {18} signature length 103, html5 player 54668ca9
[youtube] {136} signature length 107, html5 player 54668ca9
[youtube] {247} signature length 107, html5 player 54668ca9
[youtube] {135} signature length 107, html5 player 54668ca9
[youtube] {244} signature length 103, html5 player 54668ca9
[youtube] {134} signature length 103, html5 player 54668ca9
[youtube] {243} signature length 107, html5 player 54668ca9
[youtube] {133} signature length 107, html5 player 54668ca9
[youtube] {242} signature length 107, html5 player 54668ca9
[youtube] {160} signature length 107, html5 player 54668ca9
[youtube] {278} signature length 107, html5 player 54668ca9
[youtube] {140} signature length 107, html5 player 54668ca9
[youtube] {249} signature length 107, html5 player 54668ca9
[youtube] {250} signature length 103, html5 player 54668ca9
[youtube] {251} signature length 103, html5 player 54668ca9
[youtube] ZiIHyUbLFJg: Downloading thumbnail ...
[youtube] ZiIHyUbLFJg: Writing thumbnail to: Am I Not Merciful-ZiIHyUbLFJg.webp
[debug] Invoking downloader on 'https://r1---sn-u2bpouxgoxu-ntqr.googlevideo.com/videoplayback?expire=1594235793&ei=MccFX7OtKpOe3LUP1ai-8Ao&ip=203.166.236.188&id=o-AIm6xEZwlx-G__Mhfr6pcK9rXq3E3O3v-Qkusoc_8GAk&itag=251&source=youtube&requiressl=yes&mh=Bi&mm=31%2C29&mn=sn-u2bpouxgoxu-ntqr%2Csn-ntqe6nee&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=22&gcr=au&initcwndbps=1195000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=6585696&dur=393.481&lmt=1565924338150273&mt=1594214075&fvip=1&keepalive=yes&c=WEB&txp=2311222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOy6CHueIvPAjbBCcDv7seOsHCbs3Cr7iIVqIcRIYu-CAiEAnJEVtaO-qihm0ZFK0GsH0KbCPIK_vGpYluFS_gkgdQE%3D&sig=AOq0QJ8wRAIgMmUkD3UI4oIka-QJshLbydR672yfNgbsC1MgaudEL58CIHS_bnbXDskemMo6Wi03sU3Z5yWfphUqDYFV_Nq9qesX&ratebypass=yes'
[download] Destination: Am I Not Merciful-ZiIHyUbLFJg.webm
[download] 100% of 6.28MiB in 00:01
[debug] ffmpeg command line: "C:\Program Files\ffmpeg\bin\ffprobe" -show_streams "file:Am I Not Merciful-ZiIHyUbLFJg.webm"
[ffmpeg] Destination: Am I Not Merciful-ZiIHyUbLFJg.mp3
[debug] ffmpeg command line: "C:\Program Files\ffmpeg\bin\ffmpeg" -y -loglevel "repeat+info" -i "file:Am I Not Merciful-ZiIHyUbLFJg.webm" -vn -acodec libmp3lame "-q:a" 0 "file:Am I Not Merciful-ZiIHyUbLFJg.mp3"
Deleting original file Am I Not Merciful-ZiIHyUbLFJg.webm (pass -k to keep)
[ffmpeg] Adding thumbnail to "Am I Not Merciful-ZiIHyUbLFJg.mp3"
[debug] ffmpeg command line: "C:\Program Files\ffmpeg\bin\ffmpeg" -y -loglevel "repeat+info" -i "file:Am I Not Merciful-ZiIHyUbLFJg.mp3" -i "file:Am I Not Merciful-ZiIHyUbLFJg.webp" -c copy -map 0 -map 1 "-metadata:s:v" "title=\"Album cover\"" "-metadata:s:v" "comment=\"Cover (Front)\"" "file:Am I Not Merciful-ZiIHyUbLFJg.temp.mp3"
ERROR: Conversion failed!
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 2065, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\postprocessor\embedthumbnail.py", line 51, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

## Description

There appears to be an issue with the ```--embed-thumbnail``` argument. When I include it in my youtube-dl command to download and convert to mp3 any YouTube video, an ```ERROR: Conversion failed!``` error occurs. But when I omit  ```--embed-thumbnail```, then the command works error-free. Two months back when I tried this command, this command would work, however now it does not. I've tried updating to the latest ffmpeg, but that does not solve the issue.

**Comment by alexacallmebaka** [comment]
I was also having this problem. Based on issue #25687 this appears to currently be a bug in the newest release. As a temporary fix, I have rolled back to version 2020.06.06, which can be downloaded [here](https://github.com/ytdl-org/youtube-dl/releases/download/2020.06.06/youtube-dl).
