### ISSUE TITLE
YT unavailable videos don't give anymore the reason why it was removed

### ISSUE THREAD

**Issue by nastia-diaphan** [ytdl-org/youtube-dl#25945]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
~$ youtube-dl --verbose https://www.youtube.com/watch?v=BHuW1XMEyEI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=BHuW1XMEyEI']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.7.5 (CPython) - Linux-5.3.0-62-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] BHuW1XMEyEI: Downloading webpage
ERROR: BHuW1XMEyEI: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/youtube.py", line 1893, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: BHuW1XMEyEI: YouTube said: Unable to extract video data
```

## Description

Since this morning, youtube-dl don't give anymore the reason why the videos were removed or unavailable

### For the sample of the log, instead of :
ERROR: BHuW1XMEyEI: YouTube said: This video has been removed for violating YouTube's Terms of Service.
Sorry about that.

### youtube-dl give :
ERROR: BHuW1XMEyEI: YouTube said: Unable to extract video data

This information exist as it is displayed by the browser.

Many thanks for solving this.

**Comment by nastia-diaphan** [comment]
Probably related to [https://github.com/ytdl-org/youtube-dl/issues/25937](url) as both are started today and concern videos information

**Comment by marburger93** [comment]
I can confirm that. All exist videos with age restrictions are also affected. 

The download was possible yesterday:
- https://www.youtube.com/watch?v=IEpj765QuXY
- https://www.youtube.com/watch?v=o43oI5x86dI
- https://www.youtube.com/watch?v=Q0ILiXbxQCY

`ERROR: IEpj765QuXY: YouTube said: Unable to extract video data`
