### ISSUE TITLE
ERROR: Conversion failed!

### ISSUE THREAD

**Issue by lookfirst** [ytdl-org/youtube-dl#25946]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-x', '--audio-format', 'mp3', '--audio-quality', '4', '--embed-thumbnail', '--add-metadata', '--xattrs', 'https://www.youtube.com/watch?v=jKnOhO9AF0A']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.7.7 (CPython) - Darwin-19.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] jKnOhO9AF0A: Downloading webpage
[youtube] jKnOhO9AF0A: Downloading thumbnail ...
[youtube] jKnOhO9AF0A: Writing thumbnail to: Thievery Corporation • Manu Chao • Hugo Kant - Special Coffeeshop Selection [Seven Beats Music]-jKnOhO9AF0A.webp
[debug] Invoking downloader on 'https://r3---sn-n4v7sney.googlevideo.com/videoplayback?expire=1594345027&ei=43EHX6ekKM6Tkga3_pJ4&ip=2601%3A644%3A1%3Ae8d0%3A6017%3A597b%3A982f%3A6944&id=o-ADSxIhUy2xtY6D1eqzwS0Mc2Wv5schiREoqkicll3LY4&itag=251&source=youtube&requiressl=yes&mh=fq&mm=31%2C26&mn=sn-n4v7sney%2Csn-a5mekne7&ms=au%2Conr&mv=m&mvi=3&pl=34&initcwndbps=2120000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=87948015&dur=5380.641&lmt=1566469241661824&mt=1594323339&fvip=3&keepalive=yes&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgVo2wG2yFqWp81fQ8UM9aAO3G24ixxeDHYR0_IFOa-qMCIQDB2ykASI61XSJeXOoWajoKx_r26FKir4RRqrVHw7gWGg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAI7ggcWYLgnpdtwElVzzzS69FCPexuPa5JF00JwunKHVAiA7kJpV4omt7Sfajqy9F6NS3FPj3P65ATUUSZ4gj9QfAw%3D%3D&ratebypass=yes'
[download] Destination: Thievery Corporation • Manu Chao • Hugo Kant - Special Coffeeshop Selection [Seven Beats Music]-jKnOhO9AF0A.webm
[download] 100% of 83.87MiB in 00:06
[debug] ffmpeg command line: ffprobe -show_streams 'file:Thievery Corporation • Manu Chao • Hugo Kant - Special Coffeeshop Selection [Seven Beats Music]-jKnOhO9AF0A.webm'
[ffmpeg] Destination: Thievery Corporation • Manu Chao • Hugo Kant - Special Coffeeshop Selection [Seven Beats Music]-jKnOhO9AF0A.mp3
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Thievery Corporation • Manu Chao • Hugo Kant - Special Coffeeshop Selection [Seven Beats Music]-jKnOhO9AF0A.webm' -vn -acodec libmp3lame -q:a 4 'file:Thievery Corporation • Manu Chao • Hugo Kant - Special Coffeeshop Selection [Seven Beats Music]-jKnOhO9AF0A.mp3'
Deleting original file Thievery Corporation • Manu Chao • Hugo Kant - Special Coffeeshop Selection [Seven Beats Music]-jKnOhO9AF0A.webm (pass -k to keep)
[ffmpeg] Adding metadata to 'Thievery Corporation • Manu Chao • Hugo Kant - Special Coffeeshop Selection [Seven Beats Music]-jKnOhO9AF0A.mp3'
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Thievery Corporation • Manu Chao • Hugo Kant - Special Coffeeshop Selection [Seven Beats Music]-jKnOhO9AF0A.mp3' -c copy -metadata 'title=Thievery Corporation • Manu Chao • Hugo Kant - Special Coffeeshop Selection [Seven Beats Music]' -metadata date=20190730 -metadata 'description=Soooo, previous Special Coffeeshop Selection has more than 300.000 views in less than three weeks! That'"'"'s really unbelievable! This one is a gift to all of y...' -metadata 'comment=Soooo, previous Special Coffeeshop Selection has more than 300.000 views in less than three weeks! That'"'"'s really unbelievable! This one is a gift to all of y...' -metadata 'purl=https://www.youtube.com/watch?v=jKnOhO9AF0A' -metadata 'artist=Seven Beats Music' 'file:Thievery Corporation • Manu Chao • Hugo Kant - Special Coffeeshop Selection [Seven Beats Music]-jKnOhO9AF0A.temp.mp3'
[ffmpeg] Adding thumbnail to "Thievery Corporation • Manu Chao • Hugo Kant - Special Coffeeshop Selection [Seven Beats Music]-jKnOhO9AF0A.mp3"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Thievery Corporation • Manu Chao • Hugo Kant - Special Coffeeshop Selection [Seven Beats Music]-jKnOhO9AF0A.mp3' -i 'file:Thievery Corporation • Manu Chao • Hugo Kant - Special Coffeeshop Selection [Seven Beats Music]-jKnOhO9AF0A.webp' -c copy -map 0 -map 1 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (Front)"' 'file:Thievery Corporation • Manu Chao • Hugo Kant - Special Coffeeshop Selection [Seven Beats Music]-jKnOhO9AF0A.temp.mp3'
ERROR: Conversion failed!
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2065, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/embedthumbnail.py", line 51, in run
    self.run_ffmpeg_multiple_files([filename, thumbnail_filename], temp_filename, options)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

## Description

Trying to download a video results in `ERROR: Conversion failed!`.

Here is the script that I use:

```
#!/bin/bash

(
  cd $HOME/Music/ytdls && \
  youtube-dl -v -x --audio-format mp3 --audio-quality 4 --embed-thumbnail --add-metadata --xattrs $1 
)
```

And how I execute it:

```
yt https://www.youtube.com/watch?v=jKnOhO9AF0A
```

I am on OSX 10.15.5 and everything is installed with brew.

**Comment by lookfirst** [comment]
@dstftw duplicate of which issue please? thank you.

**Comment by lookfirst** [comment]
#25717

**Comment by lookfirst** [comment]
#24882

**Comment by lookfirst** [comment]
#25687

**Comment by lookfirst** [comment]
Anyone else who finds this:

https://github.com/ytdl-org/youtube-dl/pull/25717#issuecomment-656724858

I uninstalled it via brew and just pip installed it. Works great.

**Comment by zhangguanzhang** [comment]
same issue
