### ISSUE TITLE
youtube-dl takes several minutes trying to "Extract information" 

### ISSUE THREAD

**Issue by pyIDM** [ytdl-org/youtube-dl#25969]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
[xx@xx-pc ~]$ youtube-dl -v -F https://vod.tvp.pl/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://vod.tvp.pl/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.3 (CPython) - Linux-4.19.126-1-MANJARO-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] vod.tvp: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vod.tvp: Downloading webpage
[generic] vod.tvp: Extracting information
ERROR: Unsupported URL: https://vod.tvp.pl/
Traceback (most recent call last):
  File "/home/xx/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/xx/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/xx/.local/lib/python3.8/site-packages/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://vod.tvp.pl/
```

## Description

WRITE DESCRIPTION HERE

I'm using youtube-dl module thru my python application, letting youtub-dl run from a different thread 
when i give youtube-dl this url  https://vod.tvp.pl/      it will take around 3 minutes with high cpu usage,
while this is not a big deal if you run youtube-dl in terminal,  this issue will cause my GUI to be unresponsive for 3 minutes once youtube-dl starts `[generic] vod.tvp: Extracting information` then it will work again after youtube-dl finish
any idea how to prevent this from happening?

I mad a very simple and minimal gui to show this case 

```
import tkinter as tk
from tkinter import ttk
from threading import Thread
import youtube_dl as ytdl

def callback():
    Thread(target=foo, args=[url_variable.get()]).start()
    
def foo(url):
    with ytdl.YoutubeDL() as ydl:
        # process=False is faster and youtube-dl will not download every videos webpage in the playlist
        info = ydl.extract_info(url, download=False, process=True)
    
    print(info)

root = tk.Tk()
root.config(bg='grey')
root.geometry('+300+300')

url_variable = tk.StringVar()
url_variable.set('https://vod.tvp.pl/')
url_text = ttk.Entry(root, width=40, textvariable=url_variable)
url_text.grid(row=0, column=0, columnspan=2)

tk.Button(root, text='test', command=lambda: print('GUI still responsive')).grid(row=1, column=0)
go_btn = tk.Button(root, text='Go',command=callback)
go_btn.grid(row=1, column=1)

for w in root.winfo_children():
    w.grid(pady=5, padx=5)

root.mainloop()
```

also tried making gui with qt as a gui and same effect, it will get frozen

**Comment by pyIDM** [comment]
@dstftw 
Thanks a lot just tested your fix and it works as expected :)
