### ISSUE TITLE
Unable to 'login' (authenticate) and downloade from VK (unable to -Update)

### ISSUE THREAD

**Issue by LandisTwo** [ytdl-org/youtube-dl#25975]
## Checklist

- [x ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
prompt$ youtube-dl -v --username 'Login_ID@Somewhere.ru' --password 'PassWord' https://vk.com/video-101039094_456249292 > youtube-debug.txt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://vk.com/video-101039094_456249292']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 2.7.12 (CPython) - Linux-3.16.7-53-default-x86_64-with-SuSE-13.2-x86_64
[debug] exe versions: ffmpeg 3.0.5, ffprobe 3.0.5
[debug] Proxy map: {}
ERROR: Access denied (5)
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/vk.py", line 318, in _real_extract
    payload = self._download_payload('al_video', video_id, data)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/vk.py", line 74, in _download_payload
    raise ExtractorError(clean_html(payload[0][1:-1]), expected=True)
ExtractorError: Access denied (5)
```

## Description

as of this morning (cst), i am unable to dl videos from VK.com (worked AM gmt)
I have logged in and viewed the videos via browser, I am able to view, post, reply so my login is good.

I am unable to Update youtube-dl, get following message:
prompt$ sudo youtube-dl -U
ERROR: can't find the current version. Please try again later.

**Comment by LandisTwo** [comment]
do you have a VK login?
I can reproduce error on 3 different linux systems with 3 different yt-dl versions.
I have verified my VK account is working and in good standing via browser login, navigation, viewing, etc.
I can Not update yt-dl due to following error.
"ERROR: can't find the current version. Please try again later."
Nothing has changed with my systems since 5am (cst) (noon gmt).
