### ISSUE TITLE
infoq broken: videoURL is invalid

### ISSUE THREAD

**Issue by ongardie** [ytdl-org/youtube-dl#25984]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

In addition to testing with 2020.06.16.1, I've verified the same behavior using the latest commit on the master branch (718393c).

## Verbose log

```
$ youtube-dl -v 'http://www.infoq.com/presentations/A-Few-of-My-Favorite-Python-Things'       
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.infoq.com/presentations/A-Few-of-My-Favorite-Python-Things']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-9-amd64-x86_64-with-debian-10.4
[debug] exe versions: avconv 4.1.6-1, avprobe 4.1.6-1, ffmpeg 4.1.6-1, ffprobe 4.1.6-1, rtmpdump 2.4
[debug] Proxy map: {}
[InfoQ] A-Few-of-My-Favorite-Python-Things: Downloading webpage
[InfoQ] A-Few-of-My-Favorite-Python-Things: Checking video URL
[InfoQ] A-Few-of-My-Favorite-Python-Things: video URL is invalid, skipping
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://videoh.infoq.com/presentations/12-jan-pythonthings.mp4?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6IioiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1OTQ1OTE1ODJ9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19fV19&Signature=JmOgm~vupatnQqO2P81XRAHsjtN82OGNKMebzpitd3NMYCEln9XssOqCyHTt4K-tIvpIe5l5CqSdizX91YBxCurxQMXlI6Hlfm7zpfS5YIMB800Q7blKxX9GBKjI0rEK40teY~Dc7uhTEvfZPdYjUXGyjyDFH4iHEUwzKldUbzE_&Key-Pair-Id=APKAIMZVI7QH4C5YKH6Q'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/lib/python3/dist-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3/dist-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/lib/python3/dist-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

## Description

Seems like support for InfoQ is currently broken. I took that URL from the InfoQ tests (BTW, where do these run?). I see the same behavior with https and with a different video. Thanks for your help!

**Comment by meoyawn** [comment]
InfoQ's CloudFront now needs `Referer` and `Cookie` to be set correctly to access video streams

And AFAIU it's setting it's `Cookie` with a fair bit of JS

**Comment by ongardie** [comment]
I'm a little late here, but thanks for investigating and fixing this @meoyawn and @remitamine!
