### ISSUE TITLE
[YouTube] "unable to extract video data" error

### ISSUE THREAD

**Issue by 5af64758** [ytdl-org/youtube-dl#25995]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=LXxW1d6q_mw']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.3 (CPython) - Linux-5.7.7-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3
[debug] Proxy map: {}
[youtube] LXxW1d6q_mw: Downloading webpage
ERROR: LXxW1d6q_mw: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1892, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: LXxW1d6q_mw: YouTube said: Unable to extract video data

```

## Description

https://www.youtube.com/watch?v=LXxW1d6q_mw

when i try to download this video, i get this error:

```
ERROR: LXxW1d6q_mw: YouTube said: Unable to extract video data
```

**Comment by 5af64758** [comment]
sorry ive just realised this is an age restricted video, this is a duplicate of this: https://github.com/ytdl-org/youtube-dl/issues/25954
