### ISSUE TITLE
Can't Download Due to Character Limit

### ISSUE THREAD

**Issue by holygamer** [ytdl-org/youtube-dl#25991]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```

Z:\YouTube-DL>cd /D "Z:\YouTube-DL\"

Z:\YouTube-DL>youtube-dl https://www.youtube.com/channel/UCJCFJWc0NnkyMbbNmB32d_Q --config-location config.txt
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['-o', 'L:/YouTube/Politics/%(uploader)s/%(title)s/%(upload_date)s.  %(title)s  .%(id)s, %(location)s, %(height)sp %(vcodec)s %(acodec)s YouTube %(uploader)s, Views %(view_count)s, Likes %(like_count)s Dislikes %(dislike_count)s Comments %(comment_count)s Vidrate Audrate %(abr)s FPS %(fps)s', '--verbose', '--merge-output-format', 'mkv', '--write-thumbnail', '--embed-thumbnail', '--write-info-json', '--add-metadata', '--no-playlist', 'youtube-dl', '-U', '--format', '(bestvideo[width>=1920]/bestvideo)+bestaudio/best', '--embed-subs', '--sub-lang', 'en', '--ignore-errors', '--restrict-filenames', '--write-description']
[debug] Command-line args: ['https://www.youtube.com/channel/UCJCFJWc0NnkyMbbNmB32d_Q', '--config-location', 'config.txt']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-65018-gad91bf8, ffprobe N-65018-gad91bf8
[debug] Proxy map: {}
youtube-dl is up-to-date (2020.06.16.1)
ERROR: 'youtube-dl' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:youtube-dl" ) to search YouTube
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\generic.py", line 2277, in _real_extract
youtube_dl.utils.ExtractorError: 'youtube-dl' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:youtube-dl" ) to search YouTube

[youtube:channel] UCJCFJWc0NnkyMbbNmB32d_Q: Downloading channel page
[youtube:playlist] UUJCFJWc0NnkyMbbNmB32d_Q: Downloading webpage
[download] Downloading playlist: Uploads from channel with 1 video with 1000 subs
[youtube:playlist] playlist Uploads from channel with 1 video with 1000 subs: Downloading 1 videos
[download] Downloading video 1 of 1
[youtube] biS0LCX5LUk: Downloading webpage
[youtube] Downloading just video biS0LCX5LUk because of --no-playlist
[youtube] biS0LCX5LUk: Downloading MPD manifest
[info] Writing video description to: L:\YouTube\Politics\channel_with_1_video_with_1000_subs\TANKS_4_0_SUBSCRIENVEBERS_@\20190913.  TANKS_4_0_SUBSCRIENVEBERS_@  .biS0LCX5LUk, NA, 360p vp9 mp4a.40.2 YouTube channel_with_1_video_with_1000_subs, Views 2, Likes NA Dislikes NA Comments NA Vidrate Audrate 128 FPS 30.description
ERROR: Cannot write description file L:\YouTube\Politics\channel_with_1_video_with_1000_subs\TANKS_4_0_SUBSCRIENVEBERS_@\20190913.  TANKS_4_0_SUBSCRIENVEBERS_@  .biS0LCX5LUk, NA, 360p vp9 mp4a.40.2 YouTube channel_with_1_video_with_1000_subs, Views 2, Likes NA Dislikes NA Comments NA Vidrate Audrate 128 FPS 30.description
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 1785, in process_info
FileNotFoundError: [Errno 2] No such file or directory: 'L:\\YouTube\\Politics\\channel_with_1_video_with_1000_subs\\TANKS_4_0_SUBSCRIENVEBERS_@\\20190913.  TANKS_4_0_SUBSCRIENVEBERS_@  .biS0LCX5LUk, NA, 360p vp9 mp4a.40.2 YouTube channel_with_1_video_with_1000_subs, Views 2, Likes NA Dislikes NA Comments NA Vidrate Audrate 128 FPS 30.description'

[download] Finished downloading playlist: Uploads from channel with 1 video with 1000 subs

Z:\YouTube-DL>PAUSE
Press any key to continue . . .
```

## Description

WRITE DESCRIPTION HERE

**Comment by VADemon** [comment]
Use 

`-o "\\?\L:\YouTube/Politics/%(uploader)s/%(title)s/%(upload_date)s. %(title)s .%(id)s, %(location)s, %(height)sp %(vcodec)s %(acodec)s YouTube %(uploader)s, Views %(view_count)s, Likes %(like_count)s Dislikes %(dislike_count)s Comments %(comment_count)s Vidrate &(vbr)s, Audrate %(abr)s, FPS %(fps)s"`

Only works on Windows, each individual segment of the path must be max ~255 chars still. All the problems of deleting/playing back these files after download are your problem :3
