### ISSUE TITLE
Cannot download from france.tv

### ISSUE THREAD

**Issue by drcoks282** [ytdl-org/youtube-dl#25996]
Hi I can't download video from https://www.france.tv/france-2/avignon/963901-cour-d-honneur-de-jerome-bel-avignon-2013.html

**Comment by zz64** [comment]
## Checklist



- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones


## Verbose log



youtube-dl -vvv https://france3-regions.francetvinfo.fr/nouvelle-aquitaine/emissions/jt-local-1920-perigords
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vvv', 'https://france3-regions.francetvinfo.fr/nouvelle-aquitaine/emissions/jt-local-1920-perigords']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.4 (CPython) - Linux-5.7.7-gentoo-x86_64-Intel-R-_Core-TM-_i5-5200U_CPU_@_2.20GHz-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[francetvinfo.fr] jt-local-1920-perigords: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 374, in _real_extract
    video_id = self._search_regex(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```

```


## Description

<!--
Provide an explanation of your issue in an arbitrary form. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

Hi, i can't get video from francetv site using latest (2020.06.16.1) version of youtube-dl.
Thanks.

**Comment by zz64** [comment]
urls from web browser:
https://pastebin.com/raw/MRPEsK8H


youtube-dl version 2020.07.28
Python version 3.8.4 (CPython)
exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, phantomjs 2.1.1, rtmpdump 2.4

any solution ?

**Comment by zz64** [comment]
is work after apply Surkal patch.
Thanks.
