### ISSUE TITLE
Facebook ERROR: Unable to extract lgnrnd;

### ISSUE THREAD

**Issue by seisdr** [ytdl-org/youtube-dl#26030]
```
u0_a96@localhost:~$ youtube-dl --verbose  --username "" --password "" --user-agent "Mozilla/5.0 (Linux; Android 6.0; CAM-L21) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Mobile Safari/537.36" "https://www.facebook.com/omer.ballawi.7/videos/680758666112954/?app=fbl"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', '--user-agent', 'Mozilla/5.0 (Linux; Android 6.0; CAM-L21) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Mobile Safari/537.36', 'https://www.facebook.com/omer.ballawi.7/videos/680758666112954/?app=fbl']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.0 (CPython) - Linux-3.10.86-g0c14827-aarch64-with-libc
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[facebook] Downloading login page
ERROR: Unable to extract lgnrnd; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 529, in extract
    self.initialize()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 433, in initialize
    self._real_initialize()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/extractor/facebook.py", line 306, in _real_initialize
    self._login()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/extractor/facebook.py", line 255, in _login
    lgnrnd = self._search_regex(r'name="lgnrnd" value="([^"]*?)"', login_page, 'lgnrnd')
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract lgnrnd; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

u0_a96@localhost:~$
```

**Comment by Celsyum** [comment]
same with youtube:
youtube-dl -g -v -f best https://www.youtube.com/watch?v=KLDIDG1ED3o

`ERROR: KLDIDG1ED3o: YouTube said: Unable to extract video data
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-g', u'-v', u'-f', u'best', u'https://www.youtube.com/watch?v=KLDIDG1ED3o']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.9 (CPython) - Linux-3.16.0-4-amd64-x86_64-with-debian-8.11
[debug] exe versions: avconv 3.2.10-1, ffmpeg 3.2.10-1, ffprobe 3.2.10-1
[debug] Proxy map: {}
ERROR: KLDIDG1ED3o: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1893, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: KLDIDG1ED3o: YouTube said: Unable to extract video data`
