### ISSUE TITLE
OnDemandKorea

### ISSUE THREAD

**Issue by SmileyJetson** [ytdl-org/youtube-dl#26055]
I can't download a video from [OnDemandKorea](https://www.ondemandkorea.com/new-journey-to-the-west-season-3-e1.html), and got these instructions: 

youtube-dl -f best https://www.ondemandkorea.com/new-journey-to-the-west-season-3-e1.html
[OnDemandKorea] new-journey-to-the-west-season-3-e1: Downloading webpage
ERROR: Unable to extract jw config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I have the latest version of youtube-dl. Any advice would be appreciated.

**Comment by SmileyJetson** [comment]
I'm not sure if I did this correctly, but I tried to call youtube-dl with the --verbose flag.

youtube-dl --verbose https://www.ondemandkorea.com/new-journey-to-the-west-season-3-e1.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.ondemandkorea.com/new-journey-to-the-west-season-3-e1.html']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.3 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg git-2020-05-22-38490cb, ffprobe git-2020-05-22-38490cb
[debug] Proxy map: {}
[debug] Using fake IP 6.78.218.42 (US) as X-Forwarded-For.
[OnDemandKorea] new-journey-to-the-west-season-3-e1: Downloading webpage
ERROR: Unable to extract jw config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\theon\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\theon\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\users\theon\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\ondemandkorea.py", line 50, in _real_extract
    self._search_regex(
  File "c:\users\theon\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract jw config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

When trying a broswer add-on called OpenVideo on Firefox to download the video, it says 
/// HLS videos can't be downloaded! Try downloading that video from a different hoster.  \\\

I hope this can add some detail to what the issue might be.

**Comment by kartara** [comment]
Yup, I also had the same problem. Here's my log:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.ondemandkorea.com/my-little-television-e99.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.6.9 (CPython) - Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[debug] Using fake IP 99.224.119.73 (CA) as X-Forwarded-For.
[OnDemandKorea] my-little-television-e99: Downloading webpage
ERROR: Unable to extract jw config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/ondemandkorea.py", line 52, in _real_extract
    webpage, 'jw config', group='options'),
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract jw config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
