### ISSUE TITLE
Dailymotion issue with some videos

### ISSUE THREAD

**Issue by BastienMottier** [ytdl-org/youtube-dl#26076]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.dailymotion.com/video/k2FvrKaizE7unQfIglh']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] Downloading Access Token
[dailymotion] k2FvrKaizE7unQfIglh: Downloading media JSON metadata
[dailymotion] k2FvrKaizE7unQfIglh: Downloading metadata JSON
[dailymotion] k2FvrKaizE7unQfIglh: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://proxy-038.ix7.dailymotion.com/sec(pr9ckrBoZ4BM2UeWP5XuD001A7efx1shME357IUCBT-lbHjxODMaHfOkzFQJALdbHIEn-xHWjASH3fYbMUXk7A)/video/592/491/232194295_mp4_h264_aac_fhd.mp4'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```

## Description

I found some videos on Dailymotion which are not uploaded by youtube-dl. 
I think these are old videos because the IDs are different from usual (too long). 
In the browser the videos are playable but I noticed some 404 on m3u8 in the console.
![image](https://user-images.githubusercontent.com/10697872/88025865-42a47200-cb35-11ea-9ee0-5d647c59fff3.png)

**Comment by remitamine** [comment]
Not Playable in the browser.

**Comment by BastienMottier** [comment]
Playable in my browser. Tested on another device, able to play too.

**Comment by remitamine** [comment]
![Screenshot from 2020-07-23 14-53-19](https://user-images.githubusercontent.com/10879694/88294910-ae810900-ccf4-11ea-9417-e9f6f0b10930.png)

**Comment by BastienMottier** [comment]
![image](https://user-images.githubusercontent.com/10697872/88295802-30c1fb00-ccfe-11ea-9c05-6116f525e243.png)

Maybe geographic restriction ?

**Comment by remitamine** [comment]
downloadable now(most likely a temporary server side problem), anyway there nothing to be done if the problem can't be relieably reproduced:
```
youtube-dl https://www.dailymotion.com/video/k2FvrKaizE7unQfIglh
[dailymotion] Downloading Access Token
[dailymotion] k2FvrKaizE7unQfIglh: Downloading media JSON metadata
[dailymotion] k2FvrKaizE7unQfIglh: Downloading metadata JSON
[dailymotion] k2FvrKaizE7unQfIglh: Downloading m3u8 information
[download] Destination: Interview  - où trouver des fossiles de dinosaures -k2FvrKaizE7unQfIglh.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 64.5M  100 64.5M    0     0   206k      0  0:05:19  0:05:19 --:--:--  545k
[curl] Downloaded 67718594 bytes
[download] 100% of 64.58MiB in 05:19
```
