### ISSUE TITLE
kika.de has "TypeError: %d format: a number is required, not NoneType"

### ISSUE THREAD

**Issue by tophee** [ytdl-org/youtube-dl#26087]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones
**Note: this is possibly a duplicate of #24346 but since my output is not 100% identical, I thought it might provide additional info.**

## Verbose log

```
>youtube-dl.exe --verbose https://www.kika.de/lieselotte/sendungen/sendung119678.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.kika.de/lieselotte/sendungen/sendung119678.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 2.8.4, ffprobe N-79277-g0c90b2e
[debug] Proxy map: {'http': 'http://192.168.1.4:8888', 'https': 'https://192.168.1.4:8888', 'ftp': 'ftp://192.168.1.4:8888'}
[MDR] 119678: Downloading webpage
[MDR] 119678: Downloading XML
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\mdr.py", line 131, in _real_extract
TypeError: %d format: a number is required, not NoneType
```

## Description

Dowload from many (all?) videos from kika.de fail with this error

**Comment by 1100101** [comment]
I'm having the same issue with the latest release.
I've verified that I'm running youtube-dl version **2020.09.20**
```
E:\Downloads>youtube-dl.exe https://www.kika.de/petronella-apfelmus/sendungen/sendung124504.html
[MDR] 124504: Downloading webpage
[MDR] 124504: Downloading XML
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\mdr.py", line 131, in _real_extract
TypeError: %d format: a number is required, not NoneType

E:\Downloads>youtube-dl.exe --verbose https://www.kika.de/petronella-apfelmus/sendungen/sendung124504.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.kika.de/petronella-apfelmus/sendungen/sendung124504.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-93686-g8019395889, ffprobe N-93686-g8019395889
[debug] Proxy map: {}
[MDR] 124504: Downloading webpage
[MDR] 124504: Downloading XML
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\mdr.py", line 131, in _real_extract
TypeError: %d format: a number is required, not NoneType
```

**Comment by azrdev** [comment]
duplicate in #24346

**Comment by 1100101** [comment]
@remitamine why was this issue closed, even though it has comments, and a pull request?
The other issue has no comments, and restricted access (I can’t comment on it).

**Comment by remitamine** [comment]
> even though it has comments

the comments you're referring to are the same(there is a problem and here is the verbose log, they don't add value towards fixing the problem).

> a pull request?

the pull request is still open and can be linked to the other issue.

> restricted access (I can’t comment on it)

will unlock the conversation there as long as users respect the rules on https://github.com/ytdl-org/youtube-dl#how-can-i-speed-up-work-on-my-issue.
