### ISSUE TITLE
facebook JSON parsing error for videos specifically in sub-comments: caused by ValueError(Expecting , delimiter...

### ISSUE THREAD

**Issue by jasonbuechler** [ytdl-org/youtube-dl#26080]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
c:\bin>youtube-dl -U
youtube-dl is up-to-date (2020.06.16.1)

c:\bin>youtube-dl --verbose --cookies "c:\users\j2\downloads\fb.txt" "https://www.facebook.com/memes/posts/5796912083659664?comment_id=5797102346973971&reply_comment_id=5797108526973353"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--cookies', 'c:\\users\\j2\\downloads\\fb.txt', 'https://www.facebook.com/memes/posts/5796912083659664?comment_id=5797102346973971&reply_comment_id=5797108526973353']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-93447-g5252d594a1, ffprobe N-93447-g5252d594a1
[debug] Proxy map: {}
[facebook] 5796912083659664: Downloading webpage
ERROR: 5796912083659664: Failed to parse JSON  (caused by ValueError("Expecting ',' delimiter: line 1 column 21 (char 20)",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 359, in raw_decode
ValueError: Expecting ',' delimiter: line 1 column 21 (char 20)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 359, in raw_decode
ValueError: Expecting ',' delimiter: line 1 column 21 (char 20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\facebook.py", line 475, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 903, in _parse_json
youtube_dl.utils.ExtractorError: 5796912083659664: Failed to parse JSON  (caused by ValueError("Expecting ',' delimiter: line 1 column 21 (char 20)",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


....non-verbose....
c:\bin>youtube-dl --cookies "c:\users\j2\downloads\fb.txt" "https://www.facebook.com/memes/posts/5796912083659664?comment_id=5797102346973971&reply_comment_id=5797108526973353"
[facebook] 5796912083659664: Downloading webpage
ERROR: 5796912083659664: Failed to parse JSON  (caused by ValueError("Expecting ',' delimiter: line 1 column 21 (char 20)",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Originally I encountered this issue when attempting to download a video from my own facebook, with this hierarchy: [my post on my timeline] > [top-level reply] > [sub-comment with uploaded video] ... just in case it was a cookies issue, I found a public link to test, to the same outcome: https://www.facebook.com/memes/posts/5796912083659664?comment_id=5797102346973971&reply_comment_id=5797108526973353

I did not have any problem catching top-level comment videos.

This seems similar to: https://github.com/ytdl-org/youtube-dl/issues/25562

**Comment by remitamine** [comment]
no video is accessible when the URL is directly accessed.
