### ISSUE TITLE
TikTok Unsupported URL

### ISSUE THREAD

**Issue by bpenven** [ytdl-org/youtube-dl#26138]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
c:\yt>youtube-dl.exe --verbose https://www.tiktok.com/@sukhikmann/video/6834534062259014918
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.tiktok.com/@sukhikmann/video/6834534062259014918']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 6834534062259014918: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 6834534062259014918: Downloading webpage
[generic] 6834534062259014918: Extracting information
ERROR: Unsupported URL: https://www.tiktok.com/@sukhikmann/video/6834534062259014918
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.tiktok.com/@sukhikmann/video/6834534062259014918
```

## Description

TikTok Unsupported URL, bug issue from another user has been closed and tagged as duplicate, however there's no duplicate of this issue anywhere. This was working last week, doesnt work since Thursday 23th of July.

**Comment by notpushkin** [comment]
The issue this duplicates is #23264 – spent some time looking for it
