### ISSUE TITLE
Youtube video broken, Unable to extract video data

### ISSUE THREAD

**Issue by fabi321** [ytdl-org/youtube-dl#26148]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=z0NfI2NeDHI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.8.2 (CPython) - Linux-5.4.0-40-lowlatency-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] z0NfI2NeDHI: Downloading webpage
ERROR: z0NfI2NeDHI: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1892, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: z0NfI2NeDHI: YouTube said: Unable to extract video data
```

## Description

I was just trying to download the video, works fine in the browser.

**Comment by ethanbreck** [comment]
I am having the same error. Here is my verbose output as well: 

`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=p0xg_pu6hMc']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.3 (CPython) - Linux-5.4.52-1-MANJARO-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] p0xg_pu6hMc: Downloading webpage
[youtube] {18} signature length 108, html5 player f82a8c37
[youtube] p0xg_pu6hMc: Downloading player https://www.youtube.com/s/player/f82a8c37/player_ias.vflset/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1425, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1338, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1402, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 91, in interpret_expression
    right_val = self.interpret_expression(
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 188, in interpret_expression
    x, abort = self.interpret_statement(
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1425, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1338, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1402, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 91, in interpret_expression
    right_val = self.interpret_expression(
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 188, in interpret_expression
    x, abort = self.interpret_statement(
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1425, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1338, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1402, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 91, in interpret_expression
    right_val = self.interpret_expression(
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 188, in interpret_expression
    x, abort = self.interpret_statement(
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 2106, in _real_extract
    signature = self._decrypt_signature(
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1435, in _decrypt_signature
    raise ExtractorError(
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1425, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1338, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1402, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 91, in interpret_expression
    right_val = self.interpret_expression(
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 188, in interpret_expression
    x, abort = self.interpret_statement(
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by Pectacius** [comment]
I also have the same error but it seems that the error is thrown for a majority of the videos. Some videos like the test download video (https://www.youtube.com/watch?v=BaW_jenozKc) seems to work fine.

**Comment by ethanbreck** [comment]
I was going to say it was a duration issue, cause i was able to get a 20 minute video, when my 1hr 12min video wasnt working, but the OG video was a 4min video that was having the same issue, so that isnt it.

**Comment by RingoTheDog** [comment]
This one is similar the first example  (the second example may be different....)


>youtube-dl.py -v "https://www.youtube.com/watch?v=muERUkudmgM&feature=youtu.be"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=muERUkudmgM&f
eature=youtu.be']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.6.3 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] muERUkudmgM: Downloading webpage
ERROR: muERUkudmgM: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 797, in e
xtract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 53
0, in extract
    ie_result = self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\youtube.py", line 1
893, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: muERUkudmgM: YouTube said: Unable to extract vi
deo data
