### ISSUE TITLE
ExtractorError: Unsupported JS expression u'['

### ISSUE THREAD

**Issue by thompcha** [ytdl-org/youtube-dl#26140]
Download fails when running the following:
youtube-dl --verbose https://www.youtube.com/watch?v=bAZM6ghdwUI

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=bAZM6ghdwUI']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.14 (CPython) - Darwin-19.5.0-x86_64-i386-64bit
[debug] exe versions: avconv present, avprobe present, ffmpeg 4.3, ffprobe 4.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] bAZM6ghdwUI: Downloading webpage
[youtube] {18} signature length 104, html5 player f82a8c37
[youtube] bAZM6ghdwUI: Downloading player https://www.youtube.com/s/player/f82a8c37/player_ias.vflset/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1426, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1338, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1402, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Unsupported JS expression u'['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1426, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1338, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1402, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2107, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1436, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1426, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1338, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1402, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Unsupported JS expression u'['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by love124356** [comment]
See [this answer](https://github.com/ytdl-org/youtube-dl/issues/18921#issuecomment-455802208) first.
You can try to uninstall youtube-dl and reinstall it.

**Comment by koshikas** [comment]
happens also with Python 3.8.3

[debug] System config: []
[debug] User config: ['-o', '/mnt/reserve/%(title)s.%(ext)s', '--no-playlist', '--no-overwrite', '--no-mtime', '-f', 'bestvideo[height<=480]+bestaudio[abr<=128]/best[height<=480]']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=chM5rDjajB4']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.3 (CPython) - Linux-5.4.52-1-MANJARO-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] chM5rDjajB4: Downloading webpage
[youtube] Downloading just video chM5rDjajB4 because of --no-playlist
[youtube] {18} signature length 104, html5 player f82a8c37
[youtube] chM5rDjajB4: Downloading player https://www.youtube.com/s/player/f82a8c37/player_ias.vflset/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1425, in _decrypt_signature
func = self._extract_signature_function(
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1338, in _extract_signature_function
cache_res = res(test_string)
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1402, in <lambda>
return lambda s: initial_function([s])
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 258, in resf
res, abort = self.interpret_statement(stmt, local_vars)
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
v = self.interpret_expression(expr, local_vars, allow_recursion)
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 91, in interpret_expression
right_val = self.interpret_expression(
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 188, in interpret_expression
x, abort = self.interpret_statement(
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
v = self.interpret_expression(expr, local_vars, allow_recursion)
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Makesure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1425, in _decrypt_signature
func = self._extract_signature_function(
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1338, in _extract_signature_function
cache_res = res(test_string)
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1402, in <lambda>
return lambda s: initial_function([s])
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 258, in resf
res, abort = self.interpret_statement(stmt, local_vars)
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
v = self.interpret_expression(expr, local_vars, allow_recursion)
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 91, in interpret_expression
right_val = self.interpret_expression(
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 188, in interpret_expression
x, abort = self.interpret_statement(
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
v = self.interpret_expression(expr, local_vars, allow_recursion)
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1425, in _decrypt_signature
func = self._extract_signature_function(
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1338, in _extract_signature_function
cache_res = res(test_string)
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1402, in <lambda>
return lambda s: initial_function([s])
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 258, in resf
res, abort = self.interpret_statement(stmt, local_vars)
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
v = self.interpret_expression(expr, local_vars, allow_recursion)
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 91, in interpret_expression
right_val = self.interpret_expression(
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 188, in interpret_expression
x, abort = self.interpret_statement(
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
v = self.interpret_expression(expr, local_vars, allow_recursion)
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
ie_result = ie.extract(url)
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
ie_result = self._real_extract(url)
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 2106, in _real_extract
signature = self._decrypt_signature(
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1435, in _decrypt_signature
raise ExtractorError(
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1425, in _decrypt_signature
func = self._extract_signature_function(
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1338, in _extract_signature_function
cache_res = res(test_string)
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1402, in <lambda>
return lambda s: initial_function([s])
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 258, in resf
res, abort = self.interpret_statement(stmt, local_vars)
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
v = self.interpret_expression(expr, local_vars, allow_recursion)
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 91, in interpret_expression
right_val = self.interpret_expression(
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 188, in interpret_expression
x, abort = self.interpret_statement(
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
v = self.interpret_expression(expr, local_vars, allow_recursion)
File "/usr/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Makesure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by koshikas** [comment]
> See [this answer](https://github.com/ytdl-org/youtube-dl/issues/18921#issuecomment-455802208) first.
> You can try to uninstall youtube-dl and reinstall it.

thanks, getting the latest youtube-dl indeed fixed it. turns out arch packages are out of date ATM

**Comment by shriDeveloper** [comment]
@love124356  Tried the step but no help. Still the same issue.

**Comment by koshikas** [comment]
> @love124356 Tried the step but no help. Still the same issue.
> 
> Here's the error dump:
> ![image](https://user-images.githubusercontent.com/33655616/88619963-6da13f80-d0ba-11ea-9d4d-5f2a0ff87609.png)

you will run into it unless you are running the latest version 2020.07.28
if you are running packaged version you most probably are not using the latest version,
