### ISSUE TITLE
#25594 #25838 Still Not Fixed in 2020.07.28

### ISSUE THREAD

**Issue by moftot** [ytdl-org/youtube-dl#26156]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose --list-formats "http://tv.nrk.no//serie/das-boot/sesong/2/episode/1"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--list-formats', u'http://tv.nrk.no//serie/das-boot/sesong/2/episode/1']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 2.7.13 (CPython) - Linux-4.14.79-v7+-armv7l-with-debian-9.6
[debug] exe versions: avconv 3.2.10-1, avprobe 3.2.10-1, ffmpeg 4.1.1-static, ffprobe 4.1.1-static, phantomjs 2.1.1, rtmpdump 2.4-n78-git3a1e20c-ppa8
[debug] Proxy map: {}
[generic] 1: Requesting header
[redirect] Following redirect to https://tv.nrk.no/serie/das-boot/sesong/2/episode/1
[NRKTVEpisode] das-boot/sesong/2/episode/1: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError(u'@id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/nrk.py", line 430, in _real_extract
    display_id)['@id']
KeyError: u'@id'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 543, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'@id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Issues #25594 #25838 are still not fixed in 2020.07.28. Didn't the fix make it to this release or doesn't the fix work?

**Comment by moftot** [comment]
Please explain instead of just closing.
