### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by LaGrabow** [ytdl-org/youtube-dl#26176]
opensuse Tumbleweed and 15.1   youtube-dl version  2020.07.28 using BRAVE browser.

Getting an error when downloading from youtube.com. 
Following directions within error page to report this. 
I have tried to download other videos from youtube.com and get the same error.

`labud@localhost:~> youtube-dl --verbose https://www.youtube.com/watch?v=bBNIlzKsgq0
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/youtube-dl/__main__.py", line 16, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 15, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/options.py", line 8, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/downloader/__init__.py", line 3, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 9, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 22, in <module>
ImportError: No module named xml.etree.ElementTree
labud@localhost:~>`

![youtube dl error](https://user-images.githubusercontent.com/55149603/88868569-8f93e280-d1de-11ea-88e1-a28401d69ea1.jpg)
![youtube dl verbose](https://user-images.githubusercontent.com/55149603/88868575-93c00000-d1de-11ea-97cd-bb9a8761b262.jpg)
![youtube dl version](https://user-images.githubusercontent.com/55149603/88868585-97538700-d1de-11ea-81ee-4cc40bbe5407.jpg)

**Comment by eNV25** [comment]
`$ youtube-dl -i --max-downloads "132" -f bestaudio/best -x --audio-format mp3 --no-playlist "https://www.youtube.com/watch?v=YgiyWGyJcIc&list=LLwiJ3P4tbggxu66a_wEj-xQ&index=2&t=0s"
[youtube:playlist] Downloading just video YgiyWGyJcIc because of --no-playlist
[youtube] YgiyWGyJcIc: Downloading webpage
[youtube] Downloading just video YgiyWGyJcIc because of --no-playlist
[youtube] YgiyWGyJcIc: Downloading js player f82a8c37
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\youtube.py", line 1412, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\youtube.py", line 1324, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\youtube.py", line 1388, in <lambda>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 258, in resf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 92, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 189, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by eNV25** [comment]
same
```
$ youtube-dl -i --max-downloads "132" -f bestaudio/best -x --audio-format mp3 --no-playlist "https://www.youtube.com/watch?v=YgiyWGyJcIc&list=LLwiJ3P4tbggxu66a_wEj-xQ&index=2&t=0s" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-i', '--max-downloads', '132', '-f', 'bestaudio/best', '-x', '--audio-format', 'mp3', '--no-playlist', 'https://www.youtube.com/watch?v=YgiyWGyJcIc&list=LLwiJ3P4tbggxu66a_wEj-xQ&index=2&t=0s', '-v']
[debug] Encodings: locale cp65001, fs mbcs, out cp65001, pref cp65001
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube:playlist] Downloading just video YgiyWGyJcIc because of --no-playlist
[youtube] YgiyWGyJcIc: Downloading webpage
[youtube] Downloading just video YgiyWGyJcIc because of --no-playlist
[youtube] {18} signature length 108, html5 player f82a8c37
[youtube] YgiyWGyJcIc: Downloading player https://www.youtube.com/s/player/f82a8c37/player_ias.vflset/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\youtube.py", line 1412, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\youtube.py", line 1324, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\youtube.py", line 1388, in <lambda>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 258, in resf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 92, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 189, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\youtube.py", line 1412, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\youtube.py", line 1324, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\youtube.py", line 1388, in <lambda>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 258, in resf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 92, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 189, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\youtube.py", line 1412, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\youtube.py", line 1324, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\youtube.py", line 1388, in <lambda>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 258, in resf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 92, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 189, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\youtube.py", line 2029, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\youtube.py", line 1422, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\youtube.py", line 1412, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\youtube.py", line 1324, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\youtube.py", line 1388, in <lambda>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 258, in resf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 92, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 189, in interpret_expression
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\jsinterp.py", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by budowski** [comment]
Same:
```
./youtube-dl --verbose -f bestaudio -x --audio-quality 0 --audio-format mp3 -o "output-youtube/%(title)s.%(ext)s"  https://www.youtube.com/watch?v=Ywq6FMLbWH4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-f', u'bestaudio', u'-x', u'--audio-quality', u'0', u'--audio-format', u'mp3', u'-o', u'output-youtube/%(title)s.%(ext)s', u'https://www.youtube.com/watch?v=Ywq6FMLbWH4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.17 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Ywq6FMLbWH4: Downloading webpage
[youtube] {18} signature length 104, html5 player f82a8c37
[youtube] Ywq6FMLbWH4: Downloading player https://www.youtube.com/s/player/f82a8c37/player_ias.vflset/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1426, in _decrypt_signature
    video_id, player_url, s
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1338, in _extract_signature_function
    cache_res = res(test_string)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1402, in <lambda>
    return lambda s: initial_function([s])
  File "./youtube-dl/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Unsupported JS expression u'['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1426, in _decrypt_signature
    video_id, player_url, s
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1338, in _extract_signature_function
    cache_res = res(test_string)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1402, in <lambda>
    return lambda s: initial_function([s])
  File "./youtube-dl/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 2107, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1436, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1426, in _decrypt_signature
    video_id, player_url, s
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1338, in _extract_signature_function
    cache_res = res(test_string)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1402, in <lambda>
    return lambda s: initial_function([s])
  File "./youtube-dl/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "./youtube-dl/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Unsupported JS expression u'['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Version: 
```
youtube-dl --version
2020.07.28
```

**Comment by budowski** [comment]
@dstftw - please look at my version in the message posted above - it's the latest version and this bug is still happening there

**Comment by dstftw** [comment]
Bother to even read version from your log.
