### ISSUE TITLE
Probleme with ffmpeg embeding Thumbail

### ISSUE THREAD

**Issue by Elixir-Nathan** [ytdl-org/youtube-dl#26174]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['-v', '-x', '--audio-format', 'mp3', '-o', '%(title)s - %(uploader)s.%(ext)s', '--embed-thumbnail', 'https://www.youtube.com/playlist?list=PL1u-HNy_N5zKynLUjDGC2oxx7HuNEXssx']
[debug] Command-line args: ['-C', '--config-location', 'config.txt']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1
[debug] Proxy map: {}
[debug] Public IP address: XXXXXXXXXXXXXXXXXXXXXX
[youtube:playlist] PL1u-HNy_N5zKynLUjDGC2oxx7HuNEXssx: Downloading webpage
[download] Downloading playlist: Nightcore
[youtube:playlist] PL1u-HNy_N5zKynLUjDGC2oxx7HuNEXssx: Downloading page #1
[youtube:playlist] playlist Nightcore: Downloading 149 videos
[download] Downloading video 1 of 149
[youtube] kkzInFlMOp4: Downloading webpage
[youtube] {18} signature length 108, html5 player f82a8c37
[youtube] {137} signature length 108, html5 player f82a8c37
[youtube] {248} signature length 108, html5 player f82a8c37
[youtube] {136} signature length 108, html5 player f82a8c37
[youtube] {247} signature length 108, html5 player f82a8c37
[youtube] {135} signature length 104, html5 player f82a8c37
[youtube] {244} signature length 108, html5 player f82a8c37
[youtube] {134} signature length 104, html5 player f82a8c37
[youtube] {243} signature length 108, html5 player f82a8c37
[youtube] {133} signature length 108, html5 player f82a8c37
[youtube] {242} signature length 108, html5 player f82a8c37
[youtube] {160} signature length 108, html5 player f82a8c37
[youtube] {278} signature length 104, html5 player f82a8c37
[youtube] {140} signature length 104, html5 player f82a8c37
[youtube] {249} signature length 108, html5 player f82a8c37
[youtube] {250} signature length 108, html5 player f82a8c37
[youtube] {251} signature length 108, html5 player f82a8c37
[youtube] kkzInFlMOp4: Downloading thumbnail ...
[youtube] kkzInFlMOp4: Writing thumbnail to: Si mes larmes tombent-Nightcore AMV - Shishi 's.webp
[debug] Invoking downloader on 'https://r1---sn-25glen7l.googlevideo.com/videoplayback?expire=1596084244&ei=tPshX_XeIcuqW-HzsPgL&ip=2a01%3Acb05%3A8056%3A0%3A6532%3A1113%3A5c8%3A3f45&id=o-APu5-hOIcrO3mwT_0eKWGN_5iPMRvcRliLvleMNZESqr&itag=251&source=youtube&requiressl=yes&mh=j6&mm=31%2C29&mn=sn-25glen7l%2Csn-25ge7nsl&ms=au%2Crdu&mv=m&mvi=1&pl=30&pcm2=no&initcwndbps=898750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=3252856&dur=190.001&lmt=1577674968965561&mt=1596062492&fvip=1&keepalive=yes&fexp=23883098&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgWAeydNxjJYPVVu9U5UUJFbaRLdwlZI52JUUR9ZKbVKwCIE0-r1jteAeYA3Q_CR7FClm2LOcZFbkWUZWy3mTawmbE&sig=AOq0QJ8wRQIhALFh9j56FDcOpA493LX4ZrQl4FmwnkDVVSud0nKiGH14AiB1vQerbsdVAzy-u3qtYM5cCJdu8gcXdyJpGsfe0NviFA==&ratebypass=yes'
[download] Destination: Si mes larmes tombent-Nightcore AMV - Shishi 's.webm
[download]   0.0% of 3.10MiB at 31.54KiB/s ETA 01:40
[download]   0.1% of 3.10MiB at 94.63KiB/s ETA 00:33
[download]   0.2% of 3.10MiB at 220.81KiB/s ETA 00:14
[download]   0.5% of 3.10MiB at 473.16KiB/s ETA 00:06
[download]   1.0% of 3.10MiB at 234.35KiB/s ETA 00:13
[download]   2.0% of 3.10MiB at 369.73KiB/s ETA 00:08
[download]   4.0% of 3.10MiB at 341.80KiB/s ETA 00:08
[download]   8.0% of 3.10MiB at 609.36KiB/s ETA 00:04
[download]  16.1% of 3.10MiB at 532.85KiB/s ETA 00:05
[download]  31.0% of 3.10MiB at 623.91KiB/s ETA 00:03
[download]  55.1% of 3.10MiB at 801.77KiB/s ETA 00:01
[download]  94.9% of 3.10MiB at 900.01KiB/s ETA 00:00
[download] 100.0% of 3.10MiB at 920.30KiB/s ETA 00:00
[download] 100% of 3.10MiB in 00:03                  
[debug] ffmpeg command line: ffmpeg -i "file:Si mes larmes tombent-Nightcore AMV - Shishi 's.webm"
[ffmpeg] Destination: Si mes larmes tombent-Nightcore AMV - Shishi 's.mp3
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Si mes larmes tombent-Nightcore AMV - Shishi 's.webm" -vn -acodec libmp3lame "-q:a" 5 "file:Si mes larmes tombent-Nightcore AMV - Shishi 's.mp3"
Deleting original file Si mes larmes tombent-Nightcore AMV - Shishi 's.webm (pass -k to keep)
[ffmpeg] Adding thumbnail to "Si mes larmes tombent-Nightcore AMV - Shishi 's.mp3"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Si mes larmes tombent-Nightcore AMV - Shishi 's.mp3" -i "file:Si mes larmes tombent-Nightcore AMV - Shishi 's.webp" -c copy -map 0 -map 1 "-metadata:s:v" "title=\"Album cover\"" "-metadata:s:v" "comment=\"Cover (Front)\"" "file:Si mes larmes tombent-Nightcore AMV - Shishi 's.temp.mp3"
ERROR: Conversion failed!
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 2065, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\postprocessor\embedthumbnail.py", line 51, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

## Description

The problem here is a concern on the FFmpeg side when it has to integrate the image into the mp3 files.

Not knowing the program well and how it works, I will not be able to propose a solution, nor propose a solution to fix it, I do it for information purposes, so that the people working on the project have consistency of this problem. I am aware that this project is large and complex.

(PS : Transale do with Reverso, the original message :
Le problème ici est un soucis du coté de FFmpeg lors du moment ou il doit intégrer l\'image au fichiers mp3.

Ne connaissant pas bien le programme et comment il fonctionne, je ne pourrai ni proposer une solution, ni proposer un solution pour le fixer, je fait se poste a titre informatif, pour que les personne travaillant sur le projet ai consistance de ce problème. Je suis au courant que ce projet est gros, et complexe.)

**Comment by atrzaska** [comment]
The problem is with ffmpeg. It doesn't know how to decode webp thumbnail.

**Comment by AgentConDier** [comment]
I'm having the same issue with AtomicParsley. If I do a `mogrify -format jpg *.jpg` and re-run AtomicParsley it works fine.

**Comment by TeguhTeknisi** [comment]
> I'm having the same issue with AtomicParsley. If I do a `mogrify -format jpg *.jpg` and re-run AtomicParsley it works fine.

I'am having the same issue with release 2020.07.28 
teguh@Teguh-X201EV:/media/teguh/ROOTFS/MyData/Ceramah$ youtube-dl --write-description --embed-thumbnail -f 18 ExHjoDpuIEs waPEYCQ3GMQ
[youtube] ExHjoDpuIEs: Downloading webpage
[info] Writing video description to: Pengajian Islam - Terhina Karena Hutang - Ustadz Ahmad Zainuddin, Lc.-ExHjoDpuIEs.description
[youtube] ExHjoDpuIEs: Downloading thumbnail ...
[youtube] ExHjoDpuIEs: Writing thumbnail to: Pengajian Islam - Terhina Karena Hutang - Ustadz Ahmad Zainuddin, Lc.-ExHjoDpuIEs.jpg
[download] Resuming download at byte 440587897
[download] Destination: Pengajian Islam - Terhina Karena Hutang - Ustadz Ahmad Zainuddin, Lc.-ExHjoDpuIEs.mp4
[download] 100% of 539.79MiB in 01:14:38
[atomicparsley] Adding thumbnail to "Pengajian Islam - Terhina Karena Hutang - Ustadz Ahmad Zainuddin, Lc.-ExHjoDpuIEs.mp4"
ERROR: 
teguh@Teguh-X201EV:/media/teguh/ROOTFS/MyData/Ceramah$

i have to convert the jpg, because its PAM format.
the webp its not supported too

**Comment by Tumultuous-RGR-SiM** [comment]
I have the same problem. On the bright side, at least with the youtube-dl command line I have set up, it puts the webp file right next to the mp3, so I can manually convert the image to jpeg.

Does anyone know close to when YT started using webp files instead of jpgs for their video thumbnails? It feels like it only happened within the last 3 or so months.
