### ISSUE TITLE
can't login to youtube WARNING: Unable to look up account info: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by celloh123** [ytdl-org/youtube-dl#26196]
## Checklist

- [ x] I'm reporting a broken site support
- [ ]x I've verified that I'm running youtube-dl version **2020.07.28**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'cookies.txt', '--user-agent=Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)', '-f', '141', '-u', 'PRIVATE', '-p', 'PRIVATE', '-v', 'https://music.youtube.com/watch?v=Leq8J0E2TQ0']
[debug] Encodings: locale cp1254, fs mbcs, out cp857, pref cp1254
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-07-16-d11cc74, ffprobe git-2020-07-16-d11cc74
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
[youtube] Leq8J0E2TQ0: Downloading webpage
[youtube] {18} signature length 105, html5 player c718385a
[youtube] {137} signature length 105, html5 player c718385a
[youtube] {248} signature length 105, html5 player c718385a
[youtube] {136} signature length 105, html5 player c718385a
[youtube] {247} signature length 101, html5 player c718385a
[youtube] {135} signature length 105, html5 player c718385a
[youtube] {244} signature length 105, html5 player c718385a
[youtube] {134} signature length 101, html5 player c718385a
[youtube] {243} signature length 105, html5 player c718385a
[youtube] {133} signature length 105, html5 player c718385a
[youtube] {242} signature length 105, html5 player c718385a
[youtube] {160} signature length 101, html5 player c718385a
[youtube] {278} signature length 105, html5 player c718385a
[youtube] {140} signature length 105, html5 player c718385a
[youtube] {249} signature length 105, html5 player c718385a
[youtube] {250} signature length 105, html5 player c718385a
[youtube] {251} signature length 101, html5 player c718385a
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 863, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 1636, in process_video_result
youtube_dl.utils.ExtractorError: requested format not available
```

## Description

So, here is the thing. I have an Youtube Music Premium subscription which lets me download music with audio format 141. To do that obviously, I need to login to youtube. So I tried my darn hardest to do so, I've tried cookies, I've tried user agent, I even tried changing my gmail address but none of them worked! I either get error 404 unable to look up account data or error 400 bad request
also if you are going to tag this as duplicate, at least tell me what issue's duplicate this is!

**Comment by antwal** [comment]
same problem

**Comment by Shulyaka** [comment]
I have a similar error, but instead HTTP 400 on "Looking up account info" error I get HTTP 404.
It looks like Google has changed something with authenticating mechanism so authenticating with `-u` and `-p` is not working.

I have tried to investigate the issue but with no luck so far. I tried to output the request URL and data it tries to POST then sending the same request with curl (same headers, same URL, same DATA) and it returns HTTP 200 with something that looks like a malformed JSON with additional symbols in front of it. I couldn't understand why the results with CURL is different so far, there must be some difference that I considered insignifocant.

**Comment by jjemil749** [comment]
Me too. I am having similar error
I have the .netrc file in ~/.netrc

Content of the .netrc file is:
machine youtube login <youtube gmail username> password <gmail password>

I am using the youtube-dl command line:
youtube-dl --netrc -o - "https://m.youtube.com/watch?v=xCl5BtloMy4" | mpv -

I am getting the error:
`Resuming playback. This behavior can be disabled with --no-resume-playback.
[file] Reading from stdin...
[youtube] Downloading login page
[youtube] Looking up account info
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
`

**Comment by klaygomes** [comment]
same problem here

**Comment by selfisekai** [comment]
CR (fake credentials, the same happens on real ones):
```
 laura@iino  ~  youtube-dl --verbose --username daybyday --password imfedupwithallthis --print-traffic https://www.youtube.com/watch\?v\=T_Rn8TAIL2w\&list\=RDMMT_Rn8TAIL2w\&start_radio\=1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', '--print-traffic', 'https://www.youtube.com/watch?v=T_Rn8TAIL2w&list=RDMMT_Rn8TAIL2w&start_radio=1']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.8.4 (CPython) - Linux-5.7.13_1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube:playlist] Downloading login page
send: b'GET /ServiceLogin?disable_polymer=true HTTP/1.1\r\nHost: accounts.google.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3632.1 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: text/html; charset=utf-8
header: X-Frame-Options: DENY
header: x-auto-login: realm=com.google&args=continue%3Dhttps%253A%252F%252Faccounts.google.com%252FManageAccount%253Fnc%253D1
header: Cache-Control: no-cache, no-store, max-age=0, must-revalidate
header: Pragma: no-cache
header: Expires: Mon, 01 Jan 1990 00:00:00 GMT
header: Date: Fri, 07 Aug 2020 00:25:05 GMT
header: Content-Encoding: gzip
header: Strict-Transport-Security: max-age=31536000; includeSubDomains
header: Content-Security-Policy: script-src 'report-sample' 'nonce-ER88lXDu96PS54/7LXROLQ' 'unsafe-inline' 'unsafe-eval';object-src 'none';base-uri 'self';report-uri /cspreport
header: X-Content-Type-Options: nosniff
header: X-XSS-Protection: 1; mode=block
header: Server: GSE
header: Set-Cookie: GAPS=1:avwYaG2g2zAziX7kKij1XisxeQCDZQ:I_UHO-8jwP1KJaAO;Path=/;Expires=Sun, 07-Aug-2022 00:25:05 GMT;Secure;HttpOnly;Priority=HIGH
header: Set-Cookie: __Host-GAPS=1:avwYaG2g2zAziX7kKij1XisxeQCDZQ:I_UHO-8jwP1KJaAO;Path=/;Expires=Sun, 07-Aug-2022 00:25:05 GMT;Secure;HttpOnly;Priority=HIGH
header: Alt-Svc: h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
header: Connection: close
header: Transfer-Encoding: chunked
[youtube:playlist] Looking up account info
send: b'POST /_/signin/sl/lookup?disable_polymer=true HTTP/1.1\r\nContent-Length: 1035\r\nHost: accounts.google.com\r\nCookie: GAPS=1:avwYaG2g2zAziX7kKij1XisxeQCDZQ:I_UHO-8jwP1KJaAO; __Host-GAPS=1:avwYaG2g2zAziX7kKij1XisxeQCDZQ:I_UHO-8jwP1KJaAO\r\nContent-Type: application/x-www-form-urlencoded;charset=utf-8\r\nGoogle-Accounts-Xsrf: 1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3632.1 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
send: b'__msgId__=%27%2B_.R%28a.Fr%29%2B%27&pstMsg=1&checkConnection=youtube&checkedDomains=youtube&ct=%27%2B_.R%28c%29%2B%27&%27%2B_.R%28a.name%29%2B%27=%27%2B_.R%28b%29%2B%27&hl=en&deviceinfo=%5Bnull%2Cnull%2Cnull%2C%5B%5D%2Cnull%2C%22US%22%2Cnull%2Cnull%2C%5B%5D%2C%22GlifWebSignIn%22%2Cnull%2C%5Bnull%2Cnull%2C%5B%5D%5D%5D&f.req=%5B%22daybyday%22%2C+null%2C+%5B%5D%2C+null%2C+%22US%22%2C+null%2C+null%2C+2%2C+false%2C+true%2C+%5Bnull%2C+null%2C+%5B2%2C+1%2C+null%2C+1%2C+%22https%3A%2F%2Faccounts.google.com%2FServiceLogin%3Fpassive%3Dtrue%26continue%3Dhttps%253A%252F%252Fwww.youtube.com%252Fsignin%253Fnext%253D%25252F%2526action_handle_signin%253Dtrue%2526hl%253Den%2526app%253Ddesktop%2526feature%253Dsign_in_button%26hl%3Den%26service%3Dyoutube%26uilel%3D3%26requestPath%3D%252FServiceLogin%26Page%3DPasswordSeparationSignIn%22%2C+null%2C+%5B%5D%2C+4%5D%2C+1%2C+%5Bnull%2C+null%2C+%5B%5D%5D%2C+null%2C+null%2C+null%2C+true%5D%2C+%22daybyday%22%5D&flowName=GlifWebSignIn&flowEntry=ServiceLogin&bgRequest=%5B%22identifier%22%2C%22%22%5D'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Cache-Control: no-cache, no-store, max-age=0, must-revalidate
header: Pragma: no-cache
header: Expires: Mon, 01 Jan 1990 00:00:00 GMT
header: Date: Fri, 07 Aug 2020 00:25:06 GMT
header: Content-Type: text/html; charset=utf-8
header: Content-Encoding: gzip
header: X-Content-Type-Options: nosniff
header: X-XSS-Protection: 1; mode=block
header: Server: GSE
header: Alt-Svc: h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
header: Connection: close
header: Transfer-Encoding: chunked
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
[youtube:playlist] Downloading playlist RDMMT_Rn8TAIL2w - add --no-playlist to just download video T_Rn8TAIL2w
[youtube:playlist] RDMMT_Rn8TAIL2w: Downloading page 1 of Youtube mix
send: b'GET /watch?v=T_Rn8TAIL2w&list=RDMMT_Rn8TAIL2w&disable_polymer=true HTTP/1.1\r\nHost: www.youtube.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3632.1 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: X-Content-Type-Options: nosniff
header: Accept-CH: DPR
header: P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
header: X-Frame-Options: SAMEORIGIN
header: Strict-Transport-Security: max-age=31536000
header: Content-Encoding: gzip
header: Content-Type: text/html; charset=utf-8
header: Expires: Tue, 27 Apr 1971 19:44:06 GMT
header: Accept-CH-Lifetime: 2592000
header: Cache-Control: no-cache
header: Date: Fri, 07 Aug 2020 00:25:06 GMT
header: Server: YouTube Frontend Proxy
header: X-XSS-Protection: 0
header: Set-Cookie: VISITOR_INFO1_LIVE=kPZZR5ugzBI; path=/; domain=.youtube.com; secure; expires=Wed, 03-Feb-2021 00:25:06 GMT; httponly; samesite=None
header: Set-Cookie: GPS=1; path=/; domain=.youtube.com; expires=Fri, 07-Aug-2020 00:55:06 GMT
header: Set-Cookie: YSC=W3w416LjTF0; path=/; domain=.youtube.com; secure; httponly; samesite=None
header: Set-Cookie: CONSENT=WP.289b92; expires=Fri, 01-Jan-2038 00:00:00 GMT; path=/; domain=.youtube.com
header: Alt-Svc: h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
header: Connection: close
header: Transfer-Encoding: chunked
[download] Downloading playlist: RDMMT_Rn8TAIL2w
[youtube:playlist] playlist RDMMT_Rn8TAIL2w: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: RDMMT_Rn8TAIL2w
```

**Comment by egormasalitin** [comment]
Кто кому что должен?

**Comment by egormasalitin** [comment]
Any updates on this one?

**Comment by celloh123** [comment]
> Any updates on this one?

nope. still gives the same error

**Comment by Legion495** [comment]
I have to add I also ran into this issue. I noticed it that the login is needed for age restricted videos.

**Comment by arisboch** [comment]
JDownloader 2 can download these videos, why is this program unable to do so? JDownloader is open-source, why don't have a look over there?

**Comment by selfisekai** [comment]
does really anyone expect youtube-dl to do anything else than quickfixing youtube extractor when it starts breaking for all videos?

**Comment by pubdigital** [comment]
> Edit: Why am I getting down votes for mentioning how others solved the problem or never had it in the first place? An odd kind of online tribalism?

Because Sir, you are not very polite. Thanks to selfisekai i can test my self the same problem with de HTTP dialog. The problem is clearly the post to /_/signin/sl/lookup is not accepted by the domain https://accounts.google.com/ anymore. For sure google change something in the authorization method. I'm not proficiency enough for resolve the issue. I hope the developer see these message and have time to study the subject.

> does really anyone expect youtube-dl to do anything else than quickfixing youtube extractor when it starts breaking for all videos?

At these time is irrelevant to most of youtube-dl users because these problems only arise when you need to login. Mostly videos can be watch in anonymous way. The other possible solution is to use cookies sessions but i hope these bug can be fixed in the future soon.

Thanks.

**Comment by arisboch** [comment]
>Because Sir, you are not very polite. 

What about my comment was impolite?

**Comment by celloh123** [comment]
> Because Sir, you are not very polite. 
lmao he was not being impolite at all.

**Comment by Shulyaka** [comment]
Let's not get into this please...

**Comment by Toxlen** [comment]
Any new of this issue ??

**Comment by strenkml** [comment]
I am also having this issue.  Running version: 2020.09.20

**Comment by CEOGavin** [comment]
Issue unresolved.
I am using version: 2020.12.02

**Comment by nt4f04uNd** [comment]
i guess that's still a thing related to dealing with 2fa? any chance this issue being picked on after a few years of reporting?

**Comment by QuantumWarpCode** [comment]
I don't have 2fa enabled and am having the same problem. This is a different issue. Google probably changed the headers required for login.

**Comment by ServerBBQ** [comment]
Tried on two accounts, one with 2fa and one without, same issue on both
Im using version: `2021.01.16`

**Comment by lixaotec** [comment]
+1

**Comment by mozillamonks** [comment]
Seeing this as well on age-gated videos. App-specific passwords also don't work.

**Comment by lixaotec** [comment]
I could get it working with cookies..

**Comment by sebma** [comment]
@lixaotec Interesting. Can you please give the command line you have used ?

**Comment by lixaotec** [comment]
use chrome extension Get Cookies
copy the cookie and save as file.txt

then pass arg -cookies pathtothefile.txt

**Comment by sebma** [comment]
@lixaotec OK, thanks. So I guess `youtube-dl` cannot connect to a YouTube account on its own without using the help of an external browser, is that right ?

**Comment by lixaotec** [comment]
@sebma , no, its not right. Yes it can do it without a browser, however, I suspect that at this moment, login method by user and pass is not working anymore, so you need to trick it by using cookies.

**Comment by sebma** [comment]
@lixaotec Does `youtube-dl` provide another login method for YouTube.com ?

**Comment by aphex3k** [comment]
It's still not working in version `2021.03.03`.

**Comment by Poilaucul** [comment]
Solved my issue by commenting --netrc, it seems to override --cookies.
Without --netrc no more HTTP Error 400: Bad Request errrors.

**Comment by sebma** [comment]
@Poilaucul I have not used the `--netrc` option and have no `~/.netrc` file still `youtube-dl` does return a HTTP 400 Error.

**Comment by ChristopherW** [comment]
Still broken in 2021.04.01. `--print-traffic` also seems to do nothing on Windows even forcibly specifying `-v`.

Example: 

```
youtube-dl.exe -v --print-traffic -F -u myusername@gmail.com -p app-password --cookies C:\ytdl\ytmcookies.txt https://music.youtube.com/watch?v=nwa9pb2fawY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--print-traffic', '-F', '-u', 'PRIVATE', '-p', 'PRIVATE', '--cookies', 'C:\\ytdl\\ytmcookies.txt', 'https://music.youtube.com/watch?v=nwa9pb2fawY']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.04.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-86848-g03a9e6f, ffprobe git-2020-01-15-0dc0837
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
[youtube] nwa9pb2fawY: Downloading webpage
[info] Available formats for nwa9pb2fawY:
format code  extension  resolution note
249          webm       audio only tiny   46k , webm_dash container, opus @ 46k (48000Hz), 1.27MiB
250          webm       audio only tiny   61k , webm_dash container, opus @ 61k (48000Hz), 1.68MiB
251          webm       audio only tiny  123k , webm_dash container, opus @123k (48000Hz), 3.36MiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 3.51MiB
160          mp4        144x144    144p   10k , mp4_dash container, avc1.4d400b@  10k, 25fps, video only, 303.83KiB
278          webm       144x144    144p   19k , webm_dash container, vp9@  19k, 25fps, video only, 532.60KiB
394          mp4        144x144    144p   19k , mp4_dash container, av01.0.00M.08@  19k, 25fps, video only, 538.76KiB
133          mp4        240x240    240p   19k , mp4_dash container, avc1.4d400c@  19k, 25fps, video only, 535.04KiB
242          webm       240x240    240p   34k , webm_dash container, vp9@  34k, 25fps, video only, 961.72KiB
... etc.
```

(no difference if I use `--cookies=C:\path\to\file.txt`, as opposed to separating the option and path with a space)

**Comment by section83** [comment]
This is a problem for me also.

Using a cookies.txt file DOES work – I used the Firefox addin to save my YouTube cookies and supplied that file to youtube-dl.  i.e. youtube-dl --cookies "/Users/[home]/Desktop/cookies.txt"   "https://www.youtube.com/playlist?list=WL", worked perfectly.  

But, I can't find a way to do that by supplying credentials directly i.e. youtube-dl --username <username> --password <password> URL returns "WARNING: Unable to look up account info: HTTP Error 400: Bad Request".

Anyway, I'm happy as long as the cookies method works while work is being done on the credentials method.

**Comment by Faeb35** [comment]
@section83 Are you able to download in a better quality than 128Kbits (format code 141)? I wasn't by doing as you described.

**Comment by section83** [comment]
Tested just now and used the YTDL defaults to DL a video with format codes f313 and f140:

140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 13.32MiB
313          webm       3840x1920  2160p 9469k , webm_dash container, vp9@9469k, 24fps, video only, 973.75MiB

It looks really good on my 2560x1440 screen.

Does that help ?

**Comment by Faeb35** [comment]
This issue is about getting YouTube Music Premium media in good quality, not about video.
`I have an Youtube Music Premium subscription which lets me download music with audio format 141...`

**Comment by section83** [comment]
My apologies – I should have read the first posts more carefully.

I don't have a YT Music Premium subscription so, can't test.  Is your problem the same as the OP ?  If so, what sound quality do you get through a normal download in the YouTube Music app ? If you can't get better than 128Kbits, complain to Google/YouTube – they promise 256Kbits so as a Premium subscriber, you should be able to download it in their app.  From reading online discussions, it seems that YT do not offer downloads via the desktop – only in their app.  So, I would not be surprised if YTDL can't access Premium accounts.

Another possibility is that your cookies file doesn't have the required data to login to your Premium account.  You might need to play with the relevant extensions in Chrome and/or Firefox to fix that.

Another post has been lodged (#28883) about the same problem.  So, maybe the YTDL developers will look at the issue some more.

**Comment by MrJmpl3** [comment]
> use chrome extension Get Cookies
> copy the cookie and save as file.txt
> 
> then pass arg -cookies pathtothefile.txt

That's works for me

**Comment by section83** [comment]
MrJmpl3 , thanks.

Yes, there's a known problem with YTDL – the "--username --password" parameters don't login to YT.  So far the only way I've seen which works is using the cookies method as you've found.  It might be possible to get a ".netrc" file to work but, I've not added that option to MacYTDL as yet.  Maybe in v1.19.

Cheers.

**Comment by DDvO** [comment]
As mentioned above, a workaround is to log in to YouTube on a browser, copy (e.g. using a browser extension) the cookies stored for the `youtube.com` domain to a text file and pass the resulting file to `youtube-dl` via the `--cookies` option.

Since many users have this problem, see also #28147, I wonder why `youtube-dl` does not give this hint upon 
```
ERROR: Private video
```
or at least upon the more specific
```
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
```

**Comment by sam01101** [comment]
I suggest re-code the auth function and fallback to old google login page
`https://accounts.google.com/ServiceLogin?service=youtube&hl=en`
![image](https://user-images.githubusercontent.com/25792361/123786862-c6054080-d90c-11eb-8a68-05701daf7ec0.png)

For bgResponse, it's recommend to open the `devtools` and copy the code out
Actually reversing the bgResponse is not recommended since Google will patch it really quick
![image](https://user-images.githubusercontent.com/25792361/123787029-ef25d100-d90c-11eb-8e86-284c331faf6e.png)

Note that the token only available about 10 minutes around, after that you need to do the process again
When using the bgResponse token, make sure `Email or phone` and the value of `-u` stay same to prevent [being rejected](https://accounts.google.com/signin/rejected?rrk=46)

It success, you'll be redirected to `pwd/1` and you can enter the password there
Tips: Watch out `gxf` value

For most people without `2FA enabled`, you should be redirected to `CheckCookie` page and get your cookie there
For people who with `2FA enabled`, you'll first meet a verification or jumped to `selectchallenge` page
![image](https://user-images.githubusercontent.com/25792361/123787925-fe594e80-d90d-11eb-9a90-c40f6c63e92b.png)

![image](https://user-images.githubusercontent.com/25792361/123788008-16c96900-d90e-11eb-8048-3bc28f23391e.png)
It's just a simple list + form, all you need is select `data-challengeentry` and `data-unavailable` is unavailable method
For those method please do it yourself, I'm just telling the workflow

To select another challenge, you'll need to `GET` `/skip/?` url and jump back to `selectchallenge` page

After that you should be redirected to `CheckCookie` page and get your cookie there

This is the best I could do, hope someone will notice this

**Comment by genevera** [comment]
Still broken 2021.09.22

**Comment by majorgear** [comment]
Yep. I setup youtube-dl running in a docker container periodically polling a public but hidden playlist where I put videos I want it to download. It looks like I'll have to stop it and go back to manually saving a cookie and then downloading videos. Google doesn't make things easy for us. That is for sure. 

I may modify my container so it can skip over videos that require a login, and it can log which ones I need to d/l manually.

**Comment by sebma** [comment]
@majorgear The `youtube-dl` has not released any new version since `v2021.06.06` : #29965. I propose you switch like me (and maybe many others) to [`yt-dlp`](https://github.com/yt-dlp/yt-dlp) (which options' are `youtube-dl` compatible).

**Comment by Faeb35** [comment]
@sebma Thanks a lot for the hint, I was already wondering, why there's no update in youtube-dl anymore.
For all others, yt-dlp fixed my issue:
yt-dlp --extract-audio --cookies cookies.txt https://music.youtube.com/playlist?list=XXXXXX
