### ISSUE TITLE
FreedomPlatform.tv Broken

### ISSUE THREAD

**Issue by specializedtom** [ytdl-org/youtube-dl#26224]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://freedomplatform.tv/dr-sherri-tenpenny-face-masks-are-not-effective-against-covid-19-how-masks-are-being-used-to-control-the-population/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.8.5 (CPython) - Linux-5.7.10-201.fc32.x86_64-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg N-97931-g1ebbb493cc, ffprobe N-97931-g1ebbb493cc
[debug] Proxy map: {}
[generic] dr-sherri-tenpenny-face-masks-are-not-effective-against-covid-19-how-masks-are-being-used-to-control-the-population: Requesting header
WARNING: Falling back on generic information extractor.
[generic] dr-sherri-tenpenny-face-masks-are-not-effective-against-covid-19-how-masks-are-being-used-to-control-the-population: Downloading webpage
[generic] dr-sherri-tenpenny-face-masks-are-not-effective-against-covid-19-how-masks-are-being-used-to-control-the-population: Extracting information
ERROR: Unsupported URL: https://freedomplatform.tv/dr-sherri-tenpenny-face-masks-are-not-effective-against-covid-19-how-masks-are-being-used-to-control-the-population/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://freedomplatform.tv/dr-sherri-tenpenny-face-masks-are-not-effective-against-covid-19-how-masks-are-being-used-to-control-the-population/

## Description

WRITE DESCRIPTION HERE
FreedomPlatform.tv is no longer allowing direct access to the 'm3u8' file, nor its related 'ts' files. It seems they have implemented on their Wordpress site 'VideoJS' to serve up access to the m3u8 and ts files only in a browser context. 

For instance : 
Executing 'wget' on the m3u8 yields a 403 error. 

wget https://vod.freedomplatform.tv/mp4/vod/LR532-Dr-Sherri-Tenpenny-FULLEPISODE_HLSprofile.smil/LR532-Dr-Sherri-Tenpenny-FULLEPISODE__HLSprofile.mp4_chunk.m3u8?nimble_video_index=1
--2020-08-03 15:15:22--  https://vod.freedomplatform.tv/mp4/vod/LR532-Dr-Sherri-Tenpenny-FULLEPISODE_HLSprofile.smil/LR532-Dr-Sherri-Tenpenny-FULLEPISODE__HLSprofile.mp4_chunk.m3u8?nimble_video_index=1
Resolving vod.freedomplatform.tv (vod.freedomplatform.tv)... 23.1.240.136, 104.72.70.11, 2600:1415:11::6848:460b, ...
Connecting to vod.freedomplatform.tv (vod.freedomplatform.tv)|23.1.240.136|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-08-03 15:15:22 ERROR 403: Forbidden. 

Access to the website to play the full video requires a free username/password.

**Comment by rhawk301** [comment]
I confirm this is a problem. I cannot figure out how to download or get around these restrictions. I did find out if I set my VPN to London, I can get around certain blocking rules but not the ones for VideoJS .vod files using the playlist.

**Comment by Neurognostic** [comment]
I tried [exporting the cookies](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/) (after the dumb email list signup) and reading them into `youtube-dl` with the `--cookies` option and still get a 403 when trying to read any `m3u8` on a video page.

Anyone here have any luck figuring it out yet?

**Comment by Neurognostic** [comment]
I think I figured it out. Use the `--referer` option to specify the URL of the video's page. For example:

```shell
youtube-dl --referer 'https://londonreal.tv/alex-jones-behind-the-pandemic-how-the-globalist-agenda-will-caus
e-a-massive-world-depression-destroy-society/' 'https://vod.freedomplatform.tv/mp4/raw/Alex%20Jones%20160920_HL
Sprofile.smil/playlist.m3u8'
```

**Comment by specializedtom** [comment]
I wasn't able to download the example you highlighted. However, I was able to download other videos using the '--referer' flag. Thanks for pointing this feature out.

**Comment by Neurognostic** [comment]
>I wasn't able to download the example you highlighted.

I removed a newline character from the example, works now.

**Comment by specializedtom** [comment]
I get a HTTP 400 Bad Request error when I try it. 

``[fedora@localhost Videos]$ youtube-dl --referer 'https://freedomplatform.tv/alex-jones-behind-the-pandemic-how-the-globalist-agenda-will-cause-a-massive-world-depression-destroy-society/' 'https://vod.freedomplatform.tv/mp4/raw/Alex%20Jones%20160920_HLSprofile.smil/playlist.m3u8'
[generic] playlist: Requesting header
[generic] playlist: Downloading m3u8 information
[download] Destination: playlist-playlist.mp4
ffmpeg version 4.2.4 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' --extra-cflags=' ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librsvg --enable-libsrt --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg --enable-libzvbi --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[https @ 0x557245877200] HTTP error 400 Bad Request
https://vod.freedomplatform.tv/mp4/raw/Alex%20Jones%20160920_HLSprofile.smil/Alex Jones 160920__HLSprofile.mp4_chunk.m3u8?nimble_video_index=3: Server returned 400 Bad Request

**Comment by Neurognostic** [comment]
>I get a HTTP 400 Bad Request error when I try it.Not sure, it's working for me on version `2020.09.14`. Try with `--ignore-config`.

**Comment by specializedtom** [comment]
Still no good. 

``[fedora@localhost Videos]$ youtube-dl --ignore-config --verbose --referer 'https://freedomplatform.tv/alex-jones-behind-the-pandemic-how-the-globalist-agenda-will-cause-a-massive-world-depression-destroy-society/' 'https://vod.freedomplatform.tv/mp4/raw/Alex%20Jones%20160920_HLSprofile.smil/playlist.m3u8'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '--verbose', '--referer', 'https://freedomplatform.tv/alex-jones-behind-the-pandemic-how-the-globalist-agenda-will-cause-a-massive-world-depression-destroy-society/', 'https://vod.freedomplatform.tv/mp4/raw/Alex%20Jones%20160920_HLSprofile.smil/playlist.m3u8']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.14
[debug] Python version 3.8.5 (CPython) - Linux-5.8.7-200.fc32.x86_64-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[generic] playlist: Requesting header
[generic] playlist: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://vod.freedomplatform.tv/mp4/raw/Alex%20Jones%20160920_HLSprofile.smil/Alex Jones 160920__HLSprofile.mp4_chunk.m3u8?nimble_video_index=3'
[download] Destination: playlist-playlist.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3617.0 Safari/537.36
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-us,en;q=0.5
Referer: https://freedomplatform.tv/alex-jones-behind-the-pandemic-how-the-globalist-agenda-will-cause-a-massive-world-depression-destroy-society/
' -i 'https://vod.freedomplatform.tv/mp4/raw/Alex%20Jones%20160920_HLSprofile.smil/Alex Jones 160920__HLSprofile.mp4_chunk.m3u8?nimble_video_index=3' -c copy -f mp4 file:playlist-playlist.mp4.part
ffmpeg version 4.2.4 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' --extra-cflags=' ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librsvg --enable-libsrt --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg --enable-libzvbi --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[tcp @ 0x55899e6a6740] Starting connection attempt to 116.255.21.217 port 443
[tcp @ 0x55899e6a6740] Successfully connected to 116.255.21.217 port 443
[https @ 0x55899e6a4240] HTTP error 400 Bad Request
https://vod.freedomplatform.tv/mp4/raw/Alex%20Jones%20160920_HLSprofile.smil/Alex Jones 160920__HLSprofile.mp4_chunk.m3u8?nimble_video_index=3: Server returned 400 Bad Request


ERROR: ffmpeg exited with code 1

**Comment by Neurognostic** [comment]
> Still no good.

Hmm, that IP address is Australian. When I connect I get a UK IP (even though I am in North America). Maybe try using a VPN to the US or UK; like @rhawk301 suggested.
