### ISSUE TITLE
support for instagram reels

### ISSUE THREAD

**Issue by jdimpson** [ytdl-org/youtube-dl#26234]
## Checklist

- [ x] I'm reporting a feature request
- [x ] I've verified that I'm running youtube-dl version **2020.07.28**
- [x ] I've searched the bugtracker for similar feature requests including closed ones

## Description

When i attempt to download an instagram reel (tik tok knockoff), youtube-dl uses the generic parser, which fails (first failing HEAD command, then failing generic extractor)

Since this new "feature' seems to be more of a UI/UX change, I'm hopeful that the only thing youtube-dl needs are some minor changes to invoke the instagram extractor on URLs that have '/reel/' in them.

Example reel: https://www.instagram.com/reel/CDUMkliABpa/

**Comment by basicmaster** [comment]
Until the merge request is merged, you might want to just replace `reel` by `p` in the URL to download the video anyway.

**Comment by omps** [comment]
nice hack works ;)

**Comment by telegrambotdev** [comment]
> Until the merge request is merged, you might want to just replace `reel` by `p` in the URL to download the video anyway.

not working right now

**Comment by tranthanhtuan269** [comment]
Please check in this link. https://www.instagram.com/reels/audio/287067466499785/

**Comment by frakman1** [comment]
I tried the first post in the above link and replaced `reel` with `p` but it still doesn't work:

``` bash
youtube-dl --verbose  https://www.instagram.com/p/ChWV4aAjEIE/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.instagram.com/p/ChWV4aAjEIE/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.05.16
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, rtmpdump 2.4
[debug] Proxy map: {}
[Instagram] ChWV4aAjEIE: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/instagram.py", line 240, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1130, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
