### ISSUE TITLE
YouTube extractor - p2mPGqtdRqI: YouTube said: Unable to extract video data

### ISSUE THREAD

**Issue by bitplane** [ytdl-org/youtube-dl#26257]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.07.28**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=p2mPGqtdRqI', '-vvv']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.8.2 (CPython) - Linux-5.4.0-42-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube] p2mPGqtdRqI: Downloading webpage
ERROR: p2mPGqtdRqI: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1892, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: p2mPGqtdRqI: YouTube said: Unable to extract video data
```

## Description

Youtube extractor not working for this specific video: https://www.youtube.com/watch?v=p2mPGqtdRqI

**Comment by bitplane** [comment]
Apparently `age_restricted` and needs login
