### ISSUE TITLE
Youtube-DL unable to update

### ISSUE THREAD

**Issue by sxflynn** [ytdl-org/youtube-dl#26260]
## Checklist

- [x] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-U', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.2
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/update.py", line 46, in update_self
    newversion = opener.open(VERSION_URL).read().decode('utf-8').strip()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2728, in https_open
    req, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>

```

## Description

I noticed that Youtube-DL was giving me an error that it was unable to download a Youtube video. I then tried to update youtube-dl by doing youtube-dl -U and it gave me the above error. I have already tried updating python via brew and the error still persists. I'm on macOS 10.14.6

**Comment by selfisekai** [comment]
I personally suggest reinstalling youtube-dl from pip like this:
```sh
rm -rf /usr/local/bin/youtube-dl
brew install python3
pip3 install youtube-dl
```

**Comment by zrneely** [comment]
FYI, https://github.com/ytdl-org/youtube-dl/issues/25541 appears to be tracking the root cause, a bad certificate on yt-dl.org.
