### ISSUE TITLE
Can download video but no channel: "not available in your country" although set "--geo-bypass-country US"

### ISSUE THREAD

**Issue by sapereaudete** [ytdl-org/youtube-dl#26272]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ # video URI:

$  youtube-dl --write-description --no-post-overwrite --rm-cache-dir --ignore-errors  --geo-bypass-country US  -f 18        https://www.youtube.com/watch?v=3lZiwteg-kw
Removing cache dir /home/peter/.cache/youtube-dl ..
[youtube] 3lZiwteg-kw: Downloading webpage
[info] Writing video description to: Die Post ist da! Der Postvertrag regiert die Welt.-3lZiwteg-kw.description
[download] Die Post ist da! Der Postvertrag regiert die Welt.-3lZiwteg-kw.mp4 has already been downloaded
[download] 100% of 27.19MiB

$ # identical channel as video before, using channel URI instead of video URI:

youtube-dl --write-description --no-post-overwrite --rm-cache-dir --ignore-errors  --geo-bypass-country US  -v  -f 18        **https://www.youtube.com/channel/UCaU13kUFBJF5QGTY8ZPDBAA**
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--write-description', '--no-post-overwrite', '--rm-cache-dir', '--ignore-errors', '--geo-bypass-country', 'US', '-v', '-f', '18', 'https://www.youtube.com/channel/UCaU13kUFBJF5QGTY8ZPDBAA']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.6.10 (CPython) - Linux-5.3.18-lp152.33-default-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4
[debug] Proxy map: {}
Removing cache dir /home/peter/.cache/youtube-dl ..
[debug] Using fake IP 6.7.65.158 (US) as X-Forwarded-For.
[youtube:channel] UCaU13kUFBJF5QGTY8ZPDBAA: Downloading channel page
[youtube:channel] UCaU13kUFBJF5QGTY8ZPDBAA: Downloading page #1
ERROR: Youtube said: This channel is not available in your country.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2998, in _real_extract
    next(self._entries(channel_page, channel_id))
StopIteration
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2998, in _real_extract
    next(self._entries(channel_page, channel_id))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 3004, in _real_extract
    raise ExtractorError('Youtube said: %s' % alert_message, expected=True)
youtube_dl.utils.ExtractorError: Youtube said: This channel is not available in your country.



```

## Description

I can download video of a channel using the video URI but I cannot all videos of the channel using the channel URI.
Error message: "not available in your country" 
I have set --geo-bypass-country US

**Comment by dstftw** [comment]
Geo bypass will only work if `X-Forwarded-For` is respected be the server.

**Comment by sapereaudete** [comment]
I think the real issue is that you can download the video normally but not  the channel videos.

**Comment by sapereaudete** [comment]
Try video and channel URI with --geo-bypass-country.
