### ISSUE TITLE
Video can be watched via youtube.com but not downloaded

### ISSUE THREAD

**Issue by sapereaudete** [ytdl-org/youtube-dl#26299]
## Checklist

- [x] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.07.28**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --write-description --no-post-overwrite --rm-cache-dir --ignore-errors  -F -v      https://www.youtube.com/watch?v=HfxnzAmJ6dQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--write-description', '--no-post-overwrite', '--rm-cache-dir', '--ignore-errors', '-F', '-v', 'https://www.youtube.com/watch?v=HfxnzAmJ6dQ']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.6.10 (CPython) - Linux-5.3.18-lp152.33-default-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4
[debug] Proxy map: {}
Removing cache dir /home/peter/.cache/youtube-dl ..
[youtube] HfxnzAmJ6dQ: Downloading webpage
ERROR: HfxnzAmJ6dQ: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1893, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: HfxnzAmJ6dQ: YouTube said: Unable to extract video data

```

## Description

Video can be watched via youtube.com but not downloaded.

**Comment by llacb47** [comment]
https://github.com/ytdl-org/youtube-dl/issues/26152
