### ISSUE TITLE
Issue on https://www.6play.fr/

### ISSUE THREAD

**Issue by HubGit01** [ytdl-org/youtube-dl#26291]
youtube-dl.py -v -- https://www.6play.fr/justin-et-la-legende-des-chevaliers-p_17455/justin-et-la-legende-des-chevaliers-c_12647453
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--', 'https://www.6play.fr/justin-et-la-legende-des-chevaliers-p_17455/justin-et-la-legende-des-chevaliers-c_12647453']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.2 (CPython) - Windows-8-6.2.9200
[debug] exe versions: ffmpeg git-2020-03-15-c467328, ffprobe git-2020-03-15-c467328, phantomjs 2.1.1
[debug] Proxy map: {}
[6play] 12647453: Downloading JSON metadata
[6play] 12647453: Downloading webpage
[6play] 12647453: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12647453: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[6play] 12647453: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12647453: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[6play] 12647453: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12647453: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\WINDOWS\youtube-dl.py\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "C:\WINDOWS\youtube-dl.py\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "C:\WINDOWS\youtube-dl.py\youtube_dl\extractor\sixplay.py", line 113, in _real_extract
    self._sort_formats(formats)
  File "C:\WINDOWS\youtube-dl.py\youtube_dl\extractor\common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
See #24967.
