### ISSUE TITLE
'Unable to extract podcast data' on nytimes.com

### ISSUE THREAD

**Issue by dhowe** [ytdl-org/youtube-dl#26305]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl --verbose https://www.nytimes.com/2019/04/24/technology/ecuador-surveillance-cameras-police-government.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.nytimes.com/2019/04/24/technology/ecuador-surveillance-cameras-police-government.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[NYTimesArticle] ecuador-surveillance-cameras-police-government: Downloading webpage
ERROR: Unable to extract podcast data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/nytimes.py", line 222, in _real_extract
    webpage, 'podcast data')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract podcast data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Failed to download video https://www.nytimes.com/2019/04/24/technology/ecuador-surveillance-cameras-police-government.html with ERROR: Unable to extract podcast data

**Comment by dhowe** [comment]
Note that youtube-dl _does_ work on the shareable link obtained by right-clicking the video and selecting 'get url': https://www.nytimes.com/video/world/americas/100000006007030/china-ecuador-surveillance.html

**Comment by Rava77** [comment]
I had a similar issue with the newest yt-dl version (2021.12.17) and the URLs https://www.nytimes.com/interactive/2021/12/18/us/airstrikes-pentagon-records-civilian-deaths.html and https://www.nytimes.com/2021/12/19/magazine/victims-airstrikes-middle-east-civilians.html
And here how I solved it with Palemoon and wget:
I did not find any link as  @dhowe said above. But when I started playing the audio, and then used tools/page Info (or ^I) - selected the tab "Media" - there you then find the direct URL to the mp3, like these two from the example URLs above:
 https://static.nytimes.com/podcasts/2021/12/20/magazine/20audm-human-toll-air/211220-human-toll-air-khan-nytmag-audm.mp3
https://static.nytimes.com/podcasts/2021/12/18/us/18airstrikes-audm/211218-hidden-pentagon-airstrikes-khan-nyt-audm.mp3
HTH!
