### ISSUE TITLE
BBC iPlayer: No video formats found

### ISSUE THREAD

**Issue by namgee** [ytdl-org/youtube-dl#26303]
## Checklist
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
❯ youtube-dl https://www.bbc.co.uk/iplayer/episode/b09d981q/nigella-at-my-table-series-1-episode-1 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.bbc.co.uk/iplayer/episode/b09d981q/nigella-at-my-table-series-1-episode-1', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.8.5 (CPython) - Linux-4.20.5-arch1-1-ARCH-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] b09d981q: Downloading video page
[bbc.co.uk] b09d981q: Downloading playlist JSON
[bbc.co.uk] b09d9816: Downloading media selection XML
[bbc.co.uk] b09d9816: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 503: Service Temporarily Unavailable
[bbc.co.uk] b09d9816: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 503: Service Temporarily Unavailable
[bbc.co.uk] b09d9816: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 503: Service Temporarily Unavailable
[bbc.co.uk] b09d9816: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 503: Service Temporarily Unavailable
[bbc.co.uk] b09d9816: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 503: Service Temporarily Unavailable
[bbc.co.uk] b09d9816: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 503: Service Temporarily Unavailable
[bbc.co.uk] b09d9816: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 111] Connection refused>
[bbc.co.uk] b09d9816: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 111] Connection refused>
[bbc.co.uk] b09d9816: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)>
[bbc.co.uk] b09d9816: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)>
[bbc.co.uk] b09d9816: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)>
[bbc.co.uk] b09d9816: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)>
[bbc.co.uk] b09d9816: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)>
[bbc.co.uk] b09d9816: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)>
[bbc.co.uk] b09d9816: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b09d9816: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/bbc.py", line 592, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description
BBC iPlayer videos are not available for download. I tried the same video a couple of days ago and it worked perfectly. It appears to be that something has changed.

**Comment by ilike2burnthing** [comment]
Working fine here

**Comment by johnaaronrose** [comment]
I'm a newbie to youtube-dl. Are login credentials require when running youtube-dl? 
When I try running youtube-dl, I get  a number of http 403 warnings:
[bbc.co.uk] b01kvmmq: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
Are they of importance?
It then starts the download (for Line of Duty Series 1 Episode 3 which was shown live on BBC One on Monday 10 August 2020 at 9pm) but it says that it will take nearly 3 hours. Is that sort of download time standard for youtube-dl?

**Comment by ilike2burnthing** [comment]
Login credentials aren't need for iPlayer when using youtube-dl.

So long as the download starts, those 403 errors can be ignored (I get them as well).

Most videos from iPlayer take a few minutes for me to download, but this will depend on your download speed and the size of the video.

Not sure why the download would start but then give you an SSL error.

**Comment by dirkf** [comment]
Works fine with the version implementing PR https://github.com/ytdl-org/youtube-dl/pull/26821
