### ISSUE TITLE
Private Vimeo video results in extractor error "caused by KeyError(u'title',)" with no login details

### ISSUE THREAD

**Issue by LordAro** [ytdl-org/youtube-dl#26309]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://player.vimeo.com/video/341290775']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-91-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[vimeo] 341290775: Downloading webpage
[vimeo] 341290775: Extracting information
[vimeo] 341290775: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 404: Not Found
ERROR: An extractor error has occurred. (caused by KeyError(u'title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/cpigott/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/cpigott/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 740, in _real_extract
    info_dict_config = self._parse_config(config, video_id)
  File "/home/cpigott/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 123, in _parse_config
    video_title = video_data['title']
KeyError: u'title'
Traceback (most recent call last):
  File "/home/cpigott/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/cpigott/bin/youtube-dl/youtube_dl/extractor/common.py", line 543, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Crash report as above. The video is private, so I don't expect it to work (without providing username/password), but I don't feel that it should crash either.

**Comment by remitamine** [comment]
```
youtube-dl https://player.vimeo.com/video/341290775
[vimeo] 341290775: Downloading webpage
[vimeo] 341290775: Extracting information
ERROR: This video is protected by a password, use the --video-password option
```
