### ISSUE TITLE
HistoryVault.com is broken

### ISSUE THREAD

**Issue by thegreatestminer** [ytdl-org/youtube-dl#26336]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-u', 'PRIVATE', '-p', 'PRIVATE', '-v', 'https://watch.historyvault.com/shows/hunting-hitler/season-1/episode-1/full-episode']

[debug] Encodings: locale cp932, fs utf-8, out utf-8, pref cp932
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.8.3 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2019-10-23-1f327f5, ffprobe git-2019-10-23-1f327f5
[debug] Proxy map: {}
[generic] full-episode: Requesting header
WARNING: Falling back on generic information extractor.
[generic] full-episode: Downloading webpage
[generic] full-episode: Extracting information
ERROR: Unsupported URL: https://watch.historyvault.com/shows/hunting-hitler/season-1/episode-1/full-episode
Traceback (most recent call last):
  File "c:\users\zzzz\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\zzzz\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\users\zzzz\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://watch.historyvault.com/shows/hunting-hitler/season-1/episode-1/full-episode
```

## Description

Tried downloading an episode of Hunting Hitler on History Vault but it doesn't even detect the website anymore.

**Comment by thegreatestminer** [comment]
@remitamine May I ask why this is considered a duplicate? The only other issue existing for this site is #18460 and that was asking for the site to be implemented. That was almost two years ago.

I have good faith this is not a duplicate issue.

**Comment by llacb47** [comment]
It's a duplicate of https://github.com/ytdl-org/youtube-dl/issues/23363

**Comment by thegreatestminer** [comment]
@llacb47 Thank you for giving an issue number.
