### ISSUE TITLE
[RRUTV

### ISSUE THREAD

**Issue by kveke** [ytdl-org/youtube-dl#26333]
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2020.07.28**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by kveke** [comment]
Hi,
youtube-dl has stopped working since yesterday for this site. Sorry, I probably have an outdated version of firefox, I can't copy the log nicely at the top.

Log:
`
d:\>youtube-dl -v --list-format "https://russia.tv/video/show/brand_id/5402/episode_id/2431661/video_id/2323134/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--list-format', 'https://russia.tv/video/show/brand_id/
5402/episode_id/2431661/video_id/2323134/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[generic] 2323134: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2323134: Downloading webpage
[generic] 2323134: Extracting information
[RUTV] 2213974: Downloading JSON
ERROR: 2213974: Failed to parse JSON  (caused by ValueError('Expecting value: li
ne 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug .
Make sure you are using the latest version; type  youtube-dl -U  to update. Be s
ure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whux
ta\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whux
ta\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whux
ta\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whux
ta\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whux
ta\build\youtube_dl\extractor\rutv.py", line 143, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whux
ta\build\youtube_dl\extractor\common.py", line 892, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whux
ta\build\youtube_dl\extractor\common.py", line 876, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whux
ta\build\youtube_dl\extractor\common.py", line 903, in _parse_json
youtube_dl.utils.ExtractorError: 2213974: Failed to parse JSON  (caused by Value
Error('Expecting value: line 1 column 1 (char 0)',)); please report this issue o
n https://yt-dl.org/bug . Make sure you are using the latest version; type  yout
ube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and inc
lude its complete output.
`
