### ISSUE TITLE
Yandex Music not working

### ISSUE THREAD

**Issue by jLapa** [ytdl-org/youtube-dl#26449]
Hello.

C:\Users\RED\AppData\Roaming\AIMP\aimp_youtubedl>youtube-dl.exe https://music.yandex.ru/album/11817010/track/70116183 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://music.yandex.ru/album/11817010/track/70116183', '-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[yandexmusic:track] 70116183: Downloading track JSON
[yandexmusic:track] 70116183: Downloading track location url JSON
[yandexmusic:track] 70116183: Downloading track location JSON
ERROR: An extractor error has occurred. (caused by KeyError('storageDir',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\yandexmusic.py", line 112, in _real_extract
KeyError: 'storageDir'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\yandexmusic.py", line 112, in _real_extract
KeyError: 'storageDir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\common.py", line 543, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('storageDir',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by akimdi** [comment]
I confirm. I have this problem too. OS Archlinux.
```
youtube-dl --verbose https://music.yandex.ru/album/11522234/track/69096002

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://music.yandex.ru/album/11522234/track/69096002']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.06
[debug] Python version 3.8.5 (CPython) - Linux-5.4.63-1-lts-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[yandexmusic:track] 69096002: Downloading track JSON
[yandexmusic:track] 69096002: Downloading track location url JSON
[yandexmusic:track] 69096002: Downloading track location JSON
ERROR: An extractor error has occurred. (caused by KeyError('storageDir')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/yandexmusic.py", line 112, in _real_extract
    storage = track['storageDir'].split('.')
KeyError: 'storageDir'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/yandexmusic.py", line 112, in _real_extract
    storage = track['storageDir'].split('.')
KeyError: 'storageDir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 543, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('storageDir')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by ss-pl** [comment]
I confirm. I have this problem too.
```
youtube-dl --verbose https://music.yandex.ru/album/540508/track/4878838
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://music.yandex.ru/album/540508/track/4878838']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2020.09.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[yandexmusic:track] 4878838: Downloading track JSON
[yandexmusic:track] 4878838: Downloading track location url JSON
[yandexmusic:track] 4878838: Downloading track location JSON
ERROR: An extractor error has occurred. (caused by KeyError('storageDir',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\extractor\yandexmusic.py", line 112, in _real_extract
KeyError: 'storageDir'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\extractor\yandexmusic.py", line 112, in _real_extract
KeyError: 'storageDir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\extractor\common.py", line 543, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('storageDir',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
also with cookies.txt

```
youtube-dl https://music.yandex.ru/album/540508/track/4878838 --cookies cookies.txt
[yandexmusic:track] 4878838: Downloading track JSON
[yandexmusic:track] 4878838: Downloading track location url JSON
[yandexmusic:track] 4878838: Downloading track location JSON
ERROR: An extractor error has occurred. (caused by KeyError('storageDir',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by audthmbs** [comment]
the same here

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://music.yandex.ru/album/4923330']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.09.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[yandexmusic:album] 4923330: Downloading album JSON
[download] Downloading playlist: Billie Eilish - dont smile at me (2017)
[yandexmusic:album] playlist Billie Eilish - dont smile at me (2017): Collected 9 video ids (downloading 9 of them)
[download] Downloading video 1 of 9
[yandexmusic:track] 36083710: Downloading track JSON
[yandexmusic:track] 36083710: Downloading track location url JSON
[yandexmusic:track] 36083710: Downloading track location JSON
ERROR: An extractor error has occurred. (caused by KeyError('storageDir',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\extractor\yandexmusic.py", line 112, in _real_extract
KeyError: 'storageDir'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\extractor\yandexmusic.py", line 112, in _real_extract
KeyError: 'storageDir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\extractor\common.py", line 543, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('storageDir',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ildar** [comment]
same on Linux

**Comment by UncleKolya** [comment]
I confirm. I have this problem too. Win 10

**Comment by Geograph-us** [comment]
### Fix.
File _./youtube-dl/extractor/yandexmusic.py_  Line: 112-113

Find:
```
storage = track['storageDir'].split('.')
f_url = 'http://%s/get-mp3/%s/%s?track-id=%s ' % (fd_data['host'], key, fd_data['ts'] + fd_data['path'], storage[1])
```

Replace to:
```
storage = track['realId']
f_url = 'http://%s/get-mp3/%s/%s?track-id=%s ' % (fd_data['host'], key, fd_data['ts'] + fd_data['path'], storage)
```

repack `youtube-dl` binary with new `yandexmusic.py`
