### ISSUE TITLE
youtube-dl not picking up .netrc

### ISSUE THREAD

**Issue by anphetamina** [ytdl-org/youtube-dl#26465]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.facebook.com/xxxxxxxxxxxxx/videos/4287339688002603']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[facebook] 4287339688002603: Downloading webpage
[facebook] 4287339688002603: Downloading webpage
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\facebook.py", line 484, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\facebook.py", line 351, in _extract_from_url
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\common.py", line 936, in raise_login_required
youtube_dl.utils.ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
```

## Description

I've put a `config.txt` file inside the same folder of the youtube-dl executable that contains

`--netrc`

In the same folder I've put a `.netrc` file that contains

`machine facebook login "my_address" password "password_that_contains_special_character"`

Adding a `HOME` system variable pointing to the folder in which the three files are placed doesn't help

**Comment by merval** [comment]
What's interesting is, my facebook let me know I had logged in from a device that was unrecognized. so it's authenticating but not working somehow.

**Comment by dstftw** [comment]
Read FAQ on where configuration file is supposed to be located.

**Comment by anphetamina** [comment]
> 
> 
> What's interesting is, my facebook let me know I had logged in from a device that was unrecognized. so it's authenticating but not working somehow.

this
