### ISSUE TITLE
www.svtplay.se has stopped working

### ISSUE THREAD

**Issue by r0lle** [ytdl-org/youtube-dl#26476]
## Checklist

- [ yes] I'm reporting a broken site support
- [ yes] I've verified that I'm running youtube-dl version **2020.07.28**
- [ yes] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

$ youtube-dl --version
2020.07.28
$ youtube-dl -v https://www.svtplay.se/video/27909115/kvartsamtalet/kvartsamtalet-ebba-busch-jag-ar-en-no-ass-politician
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.svtplay.se/video/27909115/kvartsamtalet/kvartsamtalet-ebba-busch-jag-ar-en-no-ass-politician']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.8.2 (CPython) - Linux-5.4.0-42-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 78.78.254.5 (SE) as X-Forwarded-For.
[SVTPlay] 27909115: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/svt.py", line 227, in _real_extract
    svt_id = self._search_regex(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

youtube-dl used to work very fine with Swedish public service television on www.svtplay.se but on last friday they changed something on the page that stops this program from downloading videos.
The video above is chosen because I think it should not have any regional blocking, which otherwise could stop the kind and resourceful person who may try to figure this problem out from doing the job.

**Comment by r0lle** [comment]
I forgot to tell, the older version of youtube-dl also could not download anything after last friday's changes on www.svtplay.se, accordingly it is www.svtplay.se who are causing this.

**Comment by r0lle** [comment]
Sorry found a few similar issues:
#26469 and #26428
