### ISSUE TITLE
Youtube "No video formats found" error

### ISSUE THREAD

**Issue by psrpsrpsrpsr** [ytdl-org/youtube-dl#26480]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
REDACTED'S-MacBook-Pro:~ (my name)$ youtube-dl https://www.youtube.com/watch?v=TNJJEArxBOA
[youtube] TNJJEArxBOA: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
REDACTED'S-MacBook-Pro:~ (my name)$ youtube-dl --verbose https://www.youtube.com/watch?v=TNJJEArxBOA
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=TNJJEArxBOA']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.6.2 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] TNJJEArxBOA: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2394, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

## Description

Unable to download videos from YouTube. I am on version 2020.07.28.

**Comment by nicolaasjan** [comment]
You say that you are on version on version 2020.07.28, but your verbose log states:
`[debug] youtube-dl version 2020.05.03`...

With version 2020.07.28 it works just fine here:
```
youtube-dl https://www.youtube.com/watch?v=TNJJEArxBOA -v
[debug] System config: []
[debug] User config: ['-o', '~/Desktop/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1280][ext=mp4]+bestaudio[ext=m4a]/best', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=TNJJEArxBOA', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-112-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: ffmpeg N-98759-g1c7e55d, ffprobe N-98759-g1c7e55d
[debug] Proxy map: {}
[youtube] TNJJEArxBOA: Downloading webpage
[youtube] {18} signature length 104, html5 player 54d6fa95
[youtube] {137} signature length 108, html5 player 54d6fa95
[youtube] {248} signature length 108, html5 player 54d6fa95
[youtube] {136} signature length 108, html5 player 54d6fa95
[youtube] {247} signature length 108, html5 player 54d6fa95
[youtube] {135} signature length 108, html5 player 54d6fa95
[youtube] {244} signature length 108, html5 player 54d6fa95
[youtube] {134} signature length 108, html5 player 54d6fa95
[youtube] {243} signature length 104, html5 player 54d6fa95
[youtube] {133} signature length 108, html5 player 54d6fa95
[youtube] {242} signature length 108, html5 player 54d6fa95
[youtube] {160} signature length 104, html5 player 54d6fa95
[youtube] {278} signature length 108, html5 player 54d6fa95
[youtube] {140} signature length 108, html5 player 54d6fa95
[youtube] {249} signature length 108, html5 player 54d6fa95
[youtube] {250} signature length 108, html5 player 54d6fa95
[youtube] {251} signature length 104, html5 player 54d6fa95
[debug] Invoking downloader on 'https://r4---sn-5hne6nsy.googlevideo.com/videoplayback?expire=1598892136&ei=CNRMX4HZGIi81gLZ65qIBQ&ip=*.*.*.*&id=o-AIrozaq3Xe6JMufqKLIVnoNNW62I5ckjkH9JZPKAdsZK&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=mB&mm=31%2C26&mn=sn-5hne6nsy%2Csn-4g5e6nsz&ms=au%2Conr&mv=m&mvi=4&pl=15&gcr=nl&initcwndbps=2050000&vprv=1&mime=video%2Fmp4&gir=yes&clen=8089837&dur=981.440&lmt=1593168494107449&mt=1598870438&fvip=4&keepalive=yes&c=WEB&txp=1311222&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAMebP5QCUFA3L8SBvznPBZDvzLHla_-_Y5esfMbA5EcWAiBhdBXD5mRo4URrg-f8c4zkXbvNgtZH8lWcv_BD1kx2CA%3D%3D&sig=AOq0QJ8wRgIhAIp_NJHcoSk-kWQ9W01IaIb8M4ihI11F5GYr3oUmIjOZAiEAth8ff6mN9ULR0WF0e-5gGkQ-3p1pO8R_LjcwbWpOV9g=&ratebypass=yes'
[download] Destination: /home/nico/Desktop/Chords (Live).f137.mp4
[download] 100% of 7.72MiB in 00:01
[debug] Invoking downloader on 'https://r4---sn-5hne6nsy.googlevideo.com/videoplayback?expire=1598892136&ei=CNRMX4HZGIi81gLZ65qIBQ&ip=*.*.*.*&id=o-AIrozaq3Xe6JMufqKLIVnoNNW62I5ckjkH9JZPKAdsZK&itag=140&source=youtube&requiressl=yes&mh=mB&mm=31%2C26&mn=sn-5hne6nsy%2Csn-4g5e6nsz&ms=au%2Conr&mv=m&mvi=4&pl=15&gcr=nl&initcwndbps=2050000&vprv=1&mime=audio%2Fmp4&gir=yes&clen=15885899&dur=981.466&lmt=1593168431969861&mt=1598870438&fvip=4&keepalive=yes&c=WEB&txp=1311222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgdBEeN4y39uenJneUGC4j4eHmU7XE_YUDwUWiwZEz1IkCIAv1nRWgpNRGAnX0PA0hL94rKqzxbFpAWg3-I98Oa-rQ&sig=AOq0QJ8wRQIhAK-XvxSoBaop8NlgkADC7lbUk4-DelfbkOeoHvPp5LhdAiAmTR70y3xmThn45xD12r9iI9jsgn0qnqOern3jOISU5g==&ratebypass=yes'
[download] Destination: /home/nico/Desktop/Chords (Live).f140.m4a
[download] 100% of 15.15MiB in 00:02
[ffmpeg] Merging formats into "/home/nico/Desktop/Chords (Live).mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/home/nico/Desktop/Chords (Live).f137.mp4' -i 'file:/home/nico/Desktop/Chords (Live).f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:/home/nico/Desktop/Chords (Live).temp.mp4'
Deleting original file /home/nico/Desktop/Chords (Live).f137.mp4 (pass -k to keep)
Deleting original file /home/nico/Desktop/Chords (Live).f140.m4a (pass -k to keep)
```
