### ISSUE TITLE
Cannot download GDCVault's video

### ISSUE THREAD

**Issue by icyblue0108** [ytdl-org/youtube-dl#26496]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\Asus\Documents\youtube-dl>youtube-dl.exe
[debug] System config: []
[debug] User config: ['--verbose', '--cookies', 'C:\\Users\\Asus\\AppData\\Roaming\\youtube-dl\\cookies.txt', '--username', 'PRIVATE', '--password', 'PRIVATE', '--force-generic-extractor', '-a', 'C:\\Users\\Asus\\AppData\\Roaming\\youtube-dl\\list.txt']
[debug] Custom config: []
[debug] Command-line args: []
[debug] Batch file urls: ['https://gdcvault.com/play/1024900/AI-Wish-List-What-Do']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg git-2020-08-28-ccc7120, ffprobe git-2020-08-28-ccc7120
[debug] Proxy map: {}
[generic] AI-Wish-List-What-Do: Requesting header
WARNING: Forcing on generic information extractor.
[generic] AI-Wish-List-What-Do: Downloading webpage
[generic] AI-Wish-List-What-Do: Extracting information
ERROR: Unsupported URL: https://gdcvault.com/play/1024900/AI-Wish-List-What-Do
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://gdcvault.com/play/1024900/AI-Wish-List-What-Do
```

## Description

While using the same configuration, I was able to download both member exclusive and free content over GDCVault last week. However, now youtube-dl always claimed the video as the Unsupported URL error and refused to download it.

**Comment by minexew** [comment]
Now the error has turned into
```
WARNING: [GDCVault] It looks like http://www.gdcvault.com/play/1024900 requires a login. Try specifying a username and password and try again.
```
which is demonstrably untrue. I'll try to look into it, perhaps it's a simple problem.
