### ISSUE TITLE
Youtube "No video formats found" error (using latest version)

### ISSUE THREAD

**Issue by solarboy2020** [ytdl-org/youtube-dl#26521]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --verbose https://www.bbc.co.uk/iplayer/episode/m000m2k7/gravity
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.bbc.co.uk/iplayer/episode/m000m2k7/gravity']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.8.2 (CPython) - Linux-5.4.0-45-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.3.1-static, ffprobe 4.3.1-static
[debug] Proxy map: {}
[bbc.co.uk] m000m2k7: Downloading video page
[bbc.co.uk] m000m2k7: Downloading playlist JSON
[bbc.co.uk] m000m2k6: Downloading media selection XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
ie_result = ie.extract(url)
File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
ie_result = self._real_extract(url)
File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/bbc.py", line 592, in _real_extract
self._sort_formats(formats)
File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 1350, in _sort_formats
raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

My version of youtube-dl also reports ERROR: No video formats found but I have checked, I am using the latest version: [debug] youtube-dl version 2020.07.28.

**Comment by Private61** [comment]
I also have had this on a number of BBC downloads using version 2020-06-16-1 and 2020-07-28. Some downloads work, some fail, some are TV programmes and some are audio radio/podcasts.
Latest giving similar error was Battlestar Galactica on 5th Sep 2020.

[Verbose 2020-09-05.txt](https://github.com/ytdl-org/youtube-dl/files/5178933/Verbose.2020-09-05.txt)
