### ISSUE TITLE
[ntv.ru] ntv.ru/tv - add support for live stream

### ISSUE THREAD

**Issue by spvkgn** [ytdl-org/youtube-dl#2652]
Please add support for live stream from http://www.ntv.ru/tv/

```
youtube-dl -v http://www.ntv.ru/tv/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.ntv.ru/tv/']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.03.29
[debug] Python version 2.7.3 - Linux-3.2.0-39-generic-i686-with-LinuxMint-13-maya
[debug] Proxy map: {}
[NTV] tv/: Downloading page
ERROR: No media links available for tv/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/home/pavel/apps/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 509, in extract_info
    ie_result = ie.extract(url)
  File "/home/pavel/apps/bin/youtube-dl/youtube_dl/extractor/common.py", line 161, in extract
    return self._real_extract(url)
  File "/home/pavel/apps/bin/youtube-dl/youtube_dl/extractor/ntv.py", line 107, in _real_extract
    raise ExtractorError('No media links available for %s' % video_id)
ExtractorError: No media links available for tv/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by llacb47** [comment]
That's an old issue...
