### ISSUE TITLE
Youtube: Age-locked urls broken

### ISSUE THREAD

**Issue by hseg** [ytdl-org/youtube-dl#26537]
Consider <https://www.youtube.com/embed/9nheskbsU5g> -- it is available via embed, though is age-locked on youtube itself. The various sites availble through <http://deturl.com> are smart enough to avoid this problem. youtube-dl, however:
```
$ youtube-dl --verbose --config-location /dev/null https://www.youtube.com/embed/9nheskbsU5g
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--config-location', '/dev/null', 'https://www.youtube.com/embed/9nheskbsU5g']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.8.5 (CPython) - Linux-5.8.5-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] 9nheskbsU5g: Downloading webpage
ERROR: 9nheskbsU5g: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1892, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: 9nheskbsU5g: YouTube said: Unable to extract video data
```

**Comment by blackjack4494** [comment]
> [debug] youtube-dl version 2020.07.28

not the newest version.

**Comment by hseg** [comment]
Oops. Missed the updates, can't reproduce on new versions. Sorry for the noise.
