### ISSUE TITLE
youtube-dl automatic update bug

### ISSUE THREAD

**Issue by MPeti1** [ytdl-org/youtube-dl#26538]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```

c:\Users\[USER]\Downloads>youtube-dl-test.exe -v -U
[debug] System config: []
[debug] User config: ['--output', 'H:\\Videos-Streams\\%(extractor_key)s\\%(uploader)s\\%(upload_date)s_%(uploader)s_%(title)s_%(resolution)s-%(fps)dfps.%(ext)s', '--no-overwrites', '--write-description', '--write-info-json', '--console-title', '--merge-output-format', '
mkv', '--add-metadata', '-f', 'bestvideo[height<=?1080]+bestaudio/best', '--ignore-errors', '--retries', '200', '--fragment-retries', 'infinite']
[debug] Custom config: []
[debug] Command-line args: ['-v', '-U']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2019-11-17-b741a84, ffprobe git-2019-11-17-b741a84
[debug] Proxy map: {}
Updating to version 2020.09.06 ...
Waiting for file handle to be closed ...

c:\Users\[USER]\Downloads>Updated youtube-dl to version 2020.09.06.

```

## Description

When I update youtube-dl with the `-U` argument, it'll fail to overwrite the old .exe with the new one.
What happens can be seen in the log above, and it's important to note that the last line (`
c:\Users\[USER]\Downloads>Updated youtube-dl to version 2020.09.06.`) isn't closed, before writing any more commands I need to hit Ctrl+C, because youtube-dl won't exit otherwise after an update.
The result is that when I run `youtube-dl --version`, I'll see that it's still the old version, and if I go to the directory in which youtube-dl is, I'll see that there is the old file from 2019 (in my case), and a new one made just a few seconds ago, named `youtube-dl.exe.new`

**Comment by Jannie62** [comment]
Same kind of issue here: When running f
_youtube-dl -U<enter>_
rom windows command prompt I see:
"ERROR: can't find the current version. Please try again later."

**Comment by naffit** [comment]
With --update --verbose I get some certificate error:

D:\>youtube-dl.exe --update --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--update', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.1
[debug] Proxy map: {}
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1287, in connect
  File "C:\Python\Python34\lib\ssl.py", line 362, in wrap_socket
  File "C:\Python\Python34\lib\ssl.py", line 580, in __init__
  File "C:\Python\Python34\lib\ssl.py", line 807, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\update.py", line 46, in update_self
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\utils.py", line 2736, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>

ERROR: can't find the current version. Please try again later.

**Comment by dstftw** [comment]
You must provide reproducible environment for any work on this.
