### ISSUE TITLE
SRF.CH not working anymore

### ISSUE THREAD

**Issue by gubernatorius** [ytdl-org/youtube-dl#26555]
- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.09.06**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

```
youtube-dl -v https://www.srf.ch/play/tv/tagesschau/video/tagesschau-vom-08-09-2020-hauptausgabe?urn=urn:srf:video:5fd5a804-a22d-4d0e-bf42-2bee9bc80eac
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.srf.ch/play/tv/tagesschau/video/tagesschau-vom-08-09-2020-hauptausgabe?urn=urn:srf:video:5fd5a804-a22d-4d0e-bf42-2bee9bc80eac']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.09.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-93789-g06ba4783a0, ffprobe N-93789-g06ba4783a0
[debug] Proxy map: {}
[generic] tagesschau-vom-08-09-2020-hauptausgabe?urn=urn:srf:video:5fd5a804-a22d-4d0e-bf42-2bee9bc80eac: Requesting header
WARNING: Falling back on generic information extractor.
[generic] tagesschau-vom-08-09-2020-hauptausgabe?urn=urn:srf:video:5fd5a804-a22d-4d0e-bf42-2bee9bc80eac: Downloading webpage
[generic] tagesschau-vom-08-09-2020-hauptausgabe?urn=urn:srf:video:5fd5a804-a22d-4d0e-bf42-2bee9bc80eac: Extracting information
ERROR: Unsupported URL: https://www.srf.ch/play/tv/tagesschau/video/tagesschau-vom-08-09-2020-hauptausgabe?urn=urn:srf:video:5fd5a804-a22d-4d0e-bf42-2bee9bc80eac
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.srf.ch/play/tv/tagesschau/video/tagesschau-vom-08-09-2020-hauptausgabe?urn=urn:srf:video:5fd5a804-a22d-4d0e-bf42-2bee9bc80eac
```

## Description

The download of videos on play.srf.ch don't work anymore.

**Comment by mevin13** [comment]
Thanks for reporting, habi.
I can confirm the issue.
work-around: replace in the URL "urn=urn:srf:video:" with "id="
