### ISSUE TITLE
Unable to download videos from platzi.com

### ISSUE THREAD

**Issue by aaRonRJ** [ytdl-org/youtube-dl#26566]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2020.09.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
Kubuntu 20.04.1 LTS: 
❯ youtube-dl --all-subs --cookies /home/aaronux/Descargas/cookies.txt --verbose 'https://platzi.com/clases/svelte/' 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--all-subs', u'--cookies', u'/home/aaronux/Descargas/cookies.txt', u'--verbose', u'https://platzi.com/clases/svelte/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.06
[debug] Python version 2.7.18rc1 (CPython) - Linux-5.4.0-47-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: none
[debug] Proxy map: {}
[PlatziCourse] svelte: Downloading webpage
ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/platzi.py", line 190, in _real_extract
    self._search_regex(r'data\s*=\s*({.+?})\s*;', webpage, 'data'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Unable to download class from platzi.com. Thank you for reading and hopefully fixing. :)

**Comment by adrianheine** [comment]
I currently get 503 for all Platzi URLs.

**Comment by GlowerTvg** [comment]
> I currently get 503 for all Platzi URLs.

I too

**Comment by GlowerTvg** [comment]
Usé los flags `-4 --rm-cache-file ` y me solucionó el error

**Comment by dirkf** [comment]
I've updated the PR code. Please test and follow up [there](https://github.com/ytdl-org/youtube-dl/pull/30548).

However URLs like the OP's problem URL all seem to lead to an `Oops` page (not a list of courses in object-oriented programming!).
