### ISSUE TITLE
ndr.de link broken - mismatched  tag

### ISSUE THREAD

**Issue by FelixBer** [ytdl-org/youtube-dl#26563]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.09.06**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://daserste.ndr.de/panorama/Volksverhetzerin-Haverbeck-Den-Holocaust-gab-es-nicht,haverbeck118.html', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.06
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-115-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] Volksverhetzerin-Haverbeck-Den-Holocaust-gab-es-nicht,haverbeck118: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Volksverhetzerin-Haverbeck-Den-Holocaust-gab-es-nicht,haverbeck118: Downloading webpage
[generic] Volksverhetzerin-Haverbeck-Den-Holocaust-gab-es-nicht,haverbeck118: Extracting information
ERROR: Unsupported URL: https://daserste.ndr.de/panorama/Volksverhetzerin-Haverbeck-Den-Holocaust-gab-es-nicht,haverbeck118.html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2387, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2562, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: mismatched tag: line 79, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://daserste.ndr.de/panorama/Volksverhetzerin-Haverbeck-Den-Holocaust-gab-es-nicht,haverbeck118.html

## Description

https://daserste.ndr.de/panorama/Volksverhetzerin-Haverbeck-Den-Holocaust-gab-es-nicht,haverbeck118.html

This links is broken, seems it's working with more recent links, but not this one.

**Comment by blackjack4494** [comment]
Easiest workaround would be using this site
`https://www.ndr.de/haverbeck118-ppjson.json`  
So you simply take the last part (id) of your original URL and replace it `https://www.ndr.de/<id>-ppjson.json` 

I made a quick and dirty fix (as in there appears a warning which can be ignored)
https://github.com/blackjack4494/youtube-dlc/tree/daserste-ndr

This however isn't fixing the 'Archiv' videos.
The whole ard/ndr extractor will need a total makeover to be honest as quite some other german sites.

I will merge the fix (despite not fixing the 'Archiv' yet) to youtube-dlc the next few days.  
I don't see any reason to open a PR in the main project at this time (just no activity)  

> PS D:\gitkraken\youtube-dl> python3 -m youtube_dlc "https://daserste.ndr.de/panorama/Volksverhetzerin-Haverbeck-Den-Holocaust-gab-es-nicht,haverbeck118.html" -F -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://daserste.ndr.de/panorama/Volksverhetzerin-Haverbeck-Den-Holocaust-gab-es-nicht,haverbeck118.html', '-F', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.09.06
[debug] Git HEAD: dc9d8f44d
[debug] Python version 3.6.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[ndr] Volksverhetzerin-Haverbeck-Den-Holocaust-gab-es-nicht: Downloading webpage
WARNING: unable to extract embed URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
[ndr:embed:base] haverbeck118: Downloading JSON metadata
[ndr:embed:base] haverbeck118: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[ndr:embed:base] haverbeck118: Downloading m3u8 information
[info] Available formats for haverbeck118:
format code  extension  resolution note
hls-181      mp4        320x180     181k , avc1.66.30, mp4a.40.2
hls-604      mp4        512x288     604k , avc1.77.30, mp4a.40.2
hls-1987     mp4        960x540    1987k , avc1.77.30, mp4a.40.2
hls-3770     mp4        1280x720   3770k , avc1.64001f, mp4a.40.2
s            mp4        unknown
m            mp4        unknown
l            mp4        unknown
xl           mp4        unknown    (best)
