### ISSUE TITLE
BitChute: weird error with geoblocked video

### ISSUE THREAD

**Issue by csehszlovakze** [ytdl-org/youtube-dl#26564]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -vs https://www.bitchute.com/video/bYnCyiBcPRSR/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vs', u'https://www.bitchute.com/video/bYnCyiBcPRSR/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8                                                                  
[debug] youtube-dl version 2020.09.06                                                                                             
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-112-generic-x86_64-with-Ubuntu-18.04-bionic                                
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs 2.1.1, rtmpdump 2.4                                                  
[debug] Proxy map: {}                                                                                                             
[BitChute] bYnCyiBcPRSR: Downloading webpage                                                                                      
Traceback (most recent call last):                                                                                                
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main                                                            
    "__main__", fname, loader, pkg_name)                                                                                          
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code                                                                       
    exec code in run_globals                                                                                                      
  File "/home/csehszlovakze/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/home/csehszlovakze/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/home/csehszlovakze/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/home/csehszlovakze/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2019, in download
  File "/home/csehszlovakze/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
  File "/home/csehszlovakze/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/home/csehszlovakze/bin/youtube-dl/youtube_dl/extractor/bitchute.py", line 63, in _real_extract
IndexError: list index out of range
```

## Description

The following error appears when I open the video from Hungary:

```
VIDEO UNAVAILABLE
This video is unavailable as the contents have been deemed illegal by the authorities within your country.
```

The expected output would be to see the same error message in youtube-dl and/or suggest to use a proxy.

### Additional info

If I use a USA proxy, the download succeeds.

```
$ youtube-dl -v --proxy socks5://35.188.76.46:1080 https://www.bitchute.com/video/bYnCyiBcPRSR/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--proxy', u'socks5://35.188.76.46:1080', u'https://www.bitchute.com/video/bYnCyiBcPRSR/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.06
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-112-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {u'http': u'socks5://35.188.76.46:1080', u'https': u'socks5://35.188.76.46:1080'}
[BitChute] bYnCyiBcPRSR: Downloading webpage
[BitChute] bYnCyiBcPRSR: Checking video URL
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://seed132.bitchute.com/FcXBauA5GM4a/bYnCyiBcPRSR.mp4'
[download] Destination: Yuri Bezmenov Full Interview & Lecture (1983)-bYnCyiBcPRSR.mp4
[download] 100% of 281.70MiB in 01:39
```

**Comment by adrianheine** [comment]
Does anybody have an up-to-date link to something geoblocked? Also, you really shouldn't watch this stuff.

**Comment by 89z** [comment]
> Also, you really shouldn't watch this stuff.

Wow, true that.

**Comment by dirkf** [comment]
Video no longer available.
