### ISSUE TITLE
Unable to download from Spectrum Originals 

### ISSUE THREAD

**Issue by vega69-ux** [ytdl-org/youtube-dl#26570]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
PS C:\Users\*****\Desktop\youtube-dl> ./youtube-dl -v https://watch.spectrum.net/ondemand/play/spectrum.com::INMV1119243000689696
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://watch.spectrum.net/ondemand/play/spectrum.com::INMV1119243000689696']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.09.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-06-03-b6d7c4c, ffprobe git-2020-06-03-b6d7c4c
[debug] Proxy map: {}
[generic] spectrum: Requesting header
WARNING: Falling back on generic information extractor.
[generic] spectrum: Downloading webpage
[generic] spectrum: Extracting information
ERROR: Unsupported URL: https://watch.spectrum.net/ondemand/play/spectrum.com::INMV1119243000689696
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://watch.spectrum.net/ondemand/play/spectrum.com::INMV1119243000689696

PS C:\Users\*****\Desktop\youtube-dl>
PS C:\Users\*****\Desktop\youtube-dl> ./youtube-dl --cookies cookies.txt --no-part --restrict-filenames "https://edge-vod.spectrum.net/DASH_DRM/INMV1119243000689696/manifest.mpd?adId=ae077801-b2bc-448c-991e-4d3c1d5ae33b&streamSessionId=1ecfcb31-ee24-4b3d-807f-f0895741684f%7C1599881557647"
[generic] manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest: Downloading webpage
[generic] manifest: Extracting information
WARNING: [generic] Unknown MIME type application/ttml+xml in DASH manifest
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I have a Spectrum TV subscription. I'm trying to download the reboot of the TV show Mad About You on Spectrum Originals. I get the following message(s). Does youtube-dl support Spectrum Originals? I'm not too familiar with MPDs and how they work. Any help would be appreciated.

**Comment by stinkteeth** [comment]
The presence of "DASH_DRM" within the manifest.mpd url means, unsurprisingly, that these dash sources are encrypted with drm (widevine and others).  The only thing in the manifest that is in the clear is the ttml subtitles.  Sorry.

**Comment by vega69-ux** [comment]
Thank you for responding. I'm not sure if you can help me, I have a manifest.mpd file. Would you know how to take this manifest.mpd file and make a .mp4 file out of it? I have asked questions on Bento4 on GitHub, but know one as answered my questions.

**Comment by 89z** [comment]
You need more than just the MPD. You also need the license server info. First you download the encrypted media, then you can get a key from the license server, in order to decrypt the media. So the MPD on its own, is only enough to download the encrypted media.
