### ISSUE TITLE
Unable to download "La garçonne", event 5 and 6 from https://www.france.tv/

### ISSUE THREAD

**Issue by Piyou29** [ytdl-org/youtube-dl#26574]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.09.06**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [] I've read bugs section in FAQ

## Verbose log

youtube-dl https://www.france.tv/france-2/la-garconne/la-garconne-saison-1/1934485-episode-5.html -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.france.tv/france-2/la-garconne/la-garconne-saison-1/1934485-episode-5.html', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.06
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-117-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: avconv 3.4.8, avprobe 3.4.8, ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[FranceTVSite] 1934485-episode-5: Downloading webpage
[FranceTV] 13f05147-1c0e-4949-91cb-625fa1b82659: Downloading video JSON
[FranceTV] 13f05147-1c0e-4949-91cb-625fa1b82659: Downloading geo restriction info
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 209, in _real_extract
    return self._extract_video(video_id, catalog)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 169, in _extract_video
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

<!--
I often download from www.france.tv,  i use Linux Ubuntu 18.04.
"The garçonne" is a small serial, with six events. The download of the event 1,2,3 and 4 are ok.
But for the 5 and 6, there is a error "no video format found".

I tried for an other serial from the same site, "[Alex Hugo](https://www.france.tv/france-2/alex-hugo/alex-hugo-saison-6/1924655-le-prix-de-la-liberte.html)" and it's ok.

Thank you for this software.
Piyou
-->

**Comment by Piyou29** [comment]
To day (2020-09-13) it's ok.
