### ISSUE TITLE
SonyLIV videos are giving error at the parsing JSON level

### ISSUE THREAD

**Issue by shortthirdman** [ytdl-org/youtube-dl#26573]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-v', '--hls-prefer-native', '--hls-use-mpegts', '--no-cache-dir', 'https://www.sonyliv.com/shows/rishta-likhenge-hum-naya-1700000142/store-room-s-secrets-1000016896']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.7.8 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[generic] store-room-s-secrets-1000016896: Requesting header
WARNING: Falling back on generic information extractor.
[generic] store-room-s-secrets-1000016896: Downloading webpage
[generic] store-room-s-secrets-1000016896: Extracting information
WARNING: [generic] store-room-s-secrets-1000016896: Failed to parse JSON Extra data: line 15 column 19 (char 691)
ERROR: Unsupported URL: https://www.sonyliv.com/shows/rishta-likhenge-hum-naya-1700000142/store-room-s-secrets-1000016896
Traceback (most recent call last):
  File "c:\softwares\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "c:\softwares\python37\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\softwares\python37\lib\site-packages\youtube_dl\extractor\generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.sonyliv.com/shows/rishta-likhenge-hum-naya-1700000142/store-room-s-secrets-1000016896
```

## Description

Though SonyLIV is available in the extractors list of the application, but still it gives unsupported error.

**Comment by shortthirdman** [comment]
@dstftw Could you please initiate a release regarding this fix.
