### ISSUE TITLE
BFM unsupported site

### ISSUE THREAD

**Issue by francoisdamien-gh** [ytdl-org/youtube-dl#26615]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v https://www.bfmtv.com/sante/covid-19-rassemblements-heure-de-fermeture-des-bars-nice-durcit-a-son-tour-ses-restrictions_AV-202009180170.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bfmtv.com/sante/covid-19-rassemblements-heure-de-fermeture-des-bars-nice-durcit-a-son-tour-ses-restrictions_AV-202009180170.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.09.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2020-09-16-git-c79f07cc0c-full_build-www.gyan.dev, ffprobe 2020-09-16-git-c79f07cc0c-full_build-www.gyan.dev
[debug] Proxy map: {}
[generic] covid-19-rassemblements-heure-de-fermeture-des-bars-nice-durcit-a-son-tour-ses-restrictions_AV-202009180170: Requesting header
WARNING: Could not send HEAD request to https://www.bfmtv.com/sante/covid-19-rassemblements-heure-de-fermeture-des-bars-nice-durcit-a-son-tour-ses-restrictions_AV-202009180170.html: HTTP Error 404: Not Found
[generic] covid-19-rassemblements-heure-de-fermeture-des-bars-nice-durcit-a-son-tour-ses-restrictions_AV-202009180170: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] covid-19-rassemblements-heure-de-fermeture-des-bars-nice-durcit-a-son-tour-ses-restrictions_AV-202009180170: Extracting information
ERROR: Unsupported URL: https://www.bfmtv.com/sante/covid-19-rassemblements-heure-de-fermeture-des-bars-nice-durcit-a-son-tour-ses-restrictions_AV-202009180170.html
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1sp1mtlp\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1sp1mtlp\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1sp1mtlp\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.bfmtv.com/sante/covid-19-rassemblements-heure-de-fermeture-des-bars-nice-durcit-a-son-tour-ses-restrictions_AV-202009180170.html
```

## Description

BFM website use the Brightcove player for many years now but it's broken :(

**Comment by lazyletucce** [comment]
Live steam freeze when ads are played
