### ISSUE TITLE
Tiktok downloads are not stable (likely invalid token problem)

### ISSUE THREAD

**Issue by someziggyman** [ytdl-org/youtube-dl#26639]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v https://www.tiktok.com/@justin_agustin/video/6868009735342312709
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.tiktok.com/@justin_agustin/video/6868009735342312709']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 6868009735342312709: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 6868009735342312709: Downloading webpage
[generic] 6868009735342312709: Extracting information
ERROR: Unsupported URL: https://www.tiktok.com/@justin_agustin/video/6868009735342312709
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2387, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2562, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 6, column 7323
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.tiktok.com/@justin_agustin/video/6868009735342312709

```

## Description

Experiencing a very strange problem - sometimes Tiktok video will download just fine, the next minute youtube-dl may return an "Unsupported URL" error for the same video and next one I try.. Using the latest version, no VPNs, no firewalls, network monitors managing connections, stable and fast internet connection. Nothing seems to be able to cause the problem. Maybe, I'm missing some parameter. Please give this URL a try. 
https://www.tiktok.com/@justin_agustin/video/6868009735342312709

Try like, maybe 3-5 times and hopefully you will be able to reproduce the issue.

**Comment by makeworld-the-better-one** [comment]
Could this be caused by #26411?
