### ISSUE TITLE
Yandex.Music downloading run time error

### ISSUE THREAD

**Issue by audthmbs** [ytdl-org/youtube-dl#26669]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://music.yandex.ru/album/4923330']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[yandexmusic:album] 4923330: Downloading album JSON
[download] Downloading playlist: Billie Eilish - dont smile at me (2017)
[yandexmusic:album] playlist Billie Eilish - dont smile at me (2017): Collected 9 video ids (downloading 9 of them)
[download] Downloading video 1 of 9
[yandexmusic:track] 36083710: Downloading track JSON
[yandexmusic:track] 36083710: Downloading track location url JSON
[yandexmusic:track] 36083710: Downloading track location JSON
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 1008, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 870, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\yandexmusic.py", line 113, in _real_extract
IndexError: list index out of range

```

## Description

see the Traceback

**Comment by jLapa** [comment]
I confirm that the previous Fix did not fix problems with Yandex.Music

```
C:\>youtube-dl.exe https://music.yandex.ru/album/11817010/track/70116183 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://music.yandex.ru/album/11817010/track/70116183', '-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2020.11.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[yandexmusic:track] 70116183: Downloading track JSON
[yandexmusic:track] 70116183: Downloading track location url JSON
[yandexmusic:track] 70116183: Downloading track location JSON
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7fh9ngey\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7fh9ngey\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7fh9ngey\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7fh9ngey\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7fh9ngey\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7fh9ngey\build\youtube_dl\extractor\yandexmusic.py", line 113, in _real_extract
IndexError: list index out of range
```

**Comment by Sality777** [comment]
@dstftw 
$ ydl -v --cookies /tmp/yandex.cookies https://music.yandex.ru/album/4923330
[debug] System config: []
[debug] User config: ['--external-downloader', 'aria2c']
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', '/tmp/yandex.cookies', 'https://music.yandex.ru/album/4923330']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.19
[debug] Git HEAD: 039e715b3
[debug] Python version 3.8.6 (CPython) - Linux-5.9.8-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[yandexmusic:album] 4923330: Downloading album JSON
[download] Downloading playlist: Billie Eilish - dont smile at me (2017)
[yandexmusic:album] playlist Billie Eilish - dont smile at me (2017): Collected 9 video ids (downloading 9 of them)
[download] Downloading video 1 of 9
[yandexmusic:track] 36083710: Downloading track JSON
[yandexmusic:track] 36083710: Downloading track location url JSON
[yandexmusic:track] 36083710: Downloading track location JSON
Traceback (most recent call last):
 

>  File "/home/dstftw_Serega_ty_zayebal_ignorirovat_russkoyazychnyye_sayty/.src/youtube-dl/youtube_dl/__main__.py", line 19, in <module>
>     youtube_dl.main()
>   File "/home/dstftw_Serega_ty_zayebal_ignorirovat_russkoyazychnyye_sayty/.src/youtube-dl/youtube_dl/__init__.py", line 474, in main
>     _real_main(argv)
>   File "/home/dstftw_Serega_ty_zayebal_ignorirovat_russkoyazychnyye_sayty/.src/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
>     retcode = ydl.download(all_urls)
>   File "/home/dstftw_Serega_ty_zayebal_ignorirovat_russkoyazychnyye_sayty/.src/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
>     res = self.extract_info(
>   File "/home/dstftw_Serega_ty_zayebal_ignorirovat_russkoyazychnyye_sayty/.src/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
>     return self.process_ie_result(ie_result, download, extra_info)
>   File "/home/dstftw_Serega_ty_zayebal_ignorirovat_russkoyazychnyye_sayty/.src/youtube-dl/youtube_dl/YoutubeDL.py", line 1006, in process_ie_result
>     entry_result = self.process_ie_result(entry,
>   File "/home/dstftw_Serega_ty_zayebal_ignorirovat_russkoyazychnyye_sayty/.src/youtube-dl/youtube_dl/YoutubeDL.py", line 867, in process_ie_result
>     return self.extract_info(ie_result['url'],
>   File "/home/dstftw_Serega_ty_zayebal_ignorirovat_russkoyazychnyye_sayty/.src/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
>     ie_result = ie.extract(url)
>   File "/home/dstftw_Serega_ty_zayebal_ignorirovat_russkoyazychnyye_sayty/.src/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
>     ie_result = self._real_extract(url)
>   File "/home/dstftw_Serega_ty_zayebal_ignorirovat_russkoyazychnyye_sayty/.src/youtube-dl/youtube_dl/extractor/yandexmusic.py", line 113, in _real_extract
>     f_url = 'http://%s/get-mp3/%s/%s?track-id=%s ' % (fd_data['host'], key, fd_data['ts'] + fd_data['path'], storage[1])
> IndexError: list index out of range
>

**Comment by Sality777** [comment]
@remitamine 
Is the fix for this error being ignored due to geographic restrictions?
Need some help? Provide a Russian VPN & proxy?

**Comment by ildar** [comment]
The fix works just fine for me. What prevents it from merging?
