### ISSUE TITLE
Please add support for www.fnn-news.com

### ISSUE THREAD

**Issue by hermi362** [ytdl-org/youtube-dl#2666]
Thank you for creating and maintaing youtube-dl. I live in South Africa where bandwidth is expensive and unreliable, so your tool has been indispensable.

I would be very grateful if you could add support for www.fnn-news.com. Here is an example of my attempt to download a video:

$ youtube-dl --verbose http://www.fnn-news.com/news/headlines/articles/CONN00265752.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.fnn-news.com/news/headlines/articles/CONN00265752.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.03.30.1
[debug] Python version 2.7.5 - Darwin-13.1.0-x86_64-i386-64bit
[debug] Proxy map: {}
[generic] CONN00265752: Requesting header
WARNING: Falling back on generic information extractor.
[generic] CONN00265752: Downloading webpage
[generic] CONN00265752: Extracting information
ERROR: Unsupported URL: http://www.fnn-news.com/news/headlines/articles/CONN00265752.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 379, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1315, in parse_xml
    return xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 68, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 511, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 161, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 612, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.fnn-news.com/news/headlines/articles/CONN00265752.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dirkf** [comment]
Now fnn.jp
