### ISSUE TITLE
la1ere.francetvinfo.fr

### ISSUE THREAD

**Issue by magicvince** [ytdl-org/youtube-dl#26671]
- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.09.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- https://la1ere.francetvinfo.fr/guyane/emissions/kazadok/kazadoc-du-93-amazonie-750527.html
- https://la1ere.francetvinfo.fr/emissions/tutos-lolo/tutos-lolo-860308.html

## Description

Unable to dl or view this stream with yt-dl

$ youtube-dl https://la1ere.francetvinfo.fr/guyane/emissions/kazadok/kazadoc-du-93-amazonie-750527.html -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://la1ere.francetvinfo.fr/guyane/emissions/kazadok/kazadoc-du-93-amazonie-750527.html', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.14
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-10-amd64-x86_64-with-LinuxMint-4-debbie
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs 5, rtmpdump 2.4
[debug] Proxy map: {}
[generic] kazadoc-du-93-amazonie-750527: Requesting header
WARNING: Falling back on generic information extractor.
[generic] kazadoc-du-93-amazonie-750527: Downloading webpage
[generic] kazadoc-du-93-amazonie-750527: Extracting information
ERROR: Unsupported URL: https://la1ere.francetvinfo.fr/guyane/emissions/kazadok/kazadoc-du-93-amazonie-750527.html
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://la1ere.francetvinfo.fr/guyane/emissions/kazadok/kazadoc-du-93-amazonie-750527.html

**Comment by raphgilles** [comment]
Same request here. It That would be wonderful !

I think it's exactly the same method than franceinfotv.

Thanks guys and keep the good work !
