### ISSUE TITLE
Bandcamp is broken

### ISSUE THREAD

**Issue by kvorobyov** [ytdl-org/youtube-dl#26681]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v https://proper-t.bandcamp.com/album/the-project-ivy-part-2-beauty-sleep
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://proper-t.bandcamp.com/album/the-project-ivy-part-2-beauty-sleep']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.8.5 (CPython) - macOS-10.15.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[Bandcamp:album] the-project-ivy-part-2-beauty-sleep: Downloading webpage
WARNING: unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] Downloading playlist: the-project-ivy-part-2-beauty-sleep
[Bandcamp:album] playlist the-project-ivy-part-2-beauty-sleep: Collected 7 video ids (downloading 7 of them)
[download] Downloading video 1 of 7
[Bandcamp] beauty-sleep: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/extractor/bandcamp.py", line 196, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1359, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Bandcamp links return error today

**Comment by morrah** [comment]
some albums have free download urls (`download_link` regex) which key is quoted too now
test track for free download is http://benprunty.bandcamp.com/track/lanius-battle - .aiff format should be downloaded (but test fails anyway because md5 doesn't match for some reason)
also `track_id` regex changed

i tried to patch it myself, though not sure if using `unescapeHTML` on the whole page is the correct way https://github.com/morrah/youtube-dl/commit/8bc998aee583cba8589020e0ee1681c2be492097

**Comment by mkrupczak3** [comment]
Some example failure output:
```
[bobjoe@miho Of Mud and Mushrooms]$ youtube-dl https://davidszymanski.bandcamp.com/album/of-mud-and-mushrooms
[Bandcamp:album] of-mud-and-mushrooms: Downloading webpage
WARNING: unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] Downloading playlist: of-mud-and-mushrooms
[Bandcamp:album] playlist of-mud-and-mushrooms: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[Bandcamp] mud-light-refinery: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[bobjoe@miho Of Mud and Mushrooms]$ youtube-dl --version
2020.09.20
[bobjoe@miho Of Mud and Mushrooms]$ youtube-dl https://davidszymanski.bandcamp.com/album/of-mud-and-mushrooms
[Bandcamp:album] of-mud-and-mushrooms: Downloading webpage
WARNING: unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] Downloading playlist: of-mud-and-mushrooms
[Bandcamp:album] playlist of-mud-and-mushrooms: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[Bandcamp] mud-light-refinery: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[bobjoe@miho Of Mud and Mushrooms]$ youtube-dl --ignore-errors --verbose https://davidszymanski.bandcamp.com/album/of-mud-and-mushrooms 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ignore-errors', u'--verbose', u'https://davidszymanski.bandcamp.com/album/of-mud-and-mushrooms']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-957.el7.x86_64-x86_64-with-centos-7.6.1810-Core
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[Bandcamp:album] of-mud-and-mushrooms: Downloading webpage
WARNING: unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] Downloading playlist: of-mud-and-mushrooms
[Bandcamp:album] playlist of-mud-and-mushrooms: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[Bandcamp] mud-light-refinery: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/bandcamp.py", line 196, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 1359, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[download] Downloading video 2 of 2
[Bandcamp] the-mushroom-song: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/bandcamp.py", line 196, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 1359, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[download] Finished downloading playlist: of-mud-and-mushrooms
```

**Comment by mkrupczak3** [comment]
Bump!

**Comment by Sharpieman20** [comment]
Having similar issue here: https://www.reddit.com/r/youtubedl/comments/j0avwd/downloading_bandcamp_albums_not_working/

**Comment by quinncomendant** [comment]
I noticed the data structures in the Bandcamp HTML file have changed. I have a custom Bandcamp HTML parser (for extracting metadata to use for IDv3 tags) that stopped working at the same time that youtube-dl stopped working. It must have broke for the same reason.

Previously, album metadata was saved to a JS variable in a HTML `<script>` tag like this:

```
var TralbumData = { 
    …
};
```

Now, the same data has been moved inside the `data-tralbum` attribute of a script tag:

```
<script type="text/javascript"  …  data-tralbum="{ … }"  …  ></script>
```

The script tag contains several `data-` attributes, but the `data-tralbum` attribute is the one that contains the file URL links – it appears to me to contain the same data that was previously available in the `TralbumData` variable.

I don't have time to offer any help to update youtube-dl, but hopefully the above hints help someone who can help.

**Comment by akadaedalus** [comment]
It's more than the metadata, it's looking for file formats and download URLs.  That data has also been moved to a different data structure.  

I tried a little bit to parse out the URLs and was able to identify them (search the source for mp3-128) but it needs more analysis to match files with their metadata, and possibly a more general solution for multiple file types.

**Comment by djvs** [comment]
Working example in Ruby:

```#!/usr/bin/env ruby

require 'curb'
require 'nokogiri'
require 'ostruct'
require 'pry'
require 'securerandom'
require 'json'

def getnoko(curl_res)
  Nokogiri::HTML.parse(curl_res.body_str)
end

def gethref(str, domain)
  str.match(/^\//) ? "https://#{domain}#{str}" : str
end

url = ARGV[0].gsub("http://","https://")

puts url.inspect

page = getnoko(Curl.get(url))

#binding.pry

trackViews = page.css('.track_row_view')

trackNames = trackViews.map{|x| x.css('.title-col a').inner_text }

mp3script = page.css('script').select{|x|x.to_html.include?('bcbits.com/stream')}

tralbum = mp3script[0].attr('data-tralbum')

manifest = JSON.parse(tralbum)

tracks = manifest['trackinfo']

list = manifest['trackinfo'].map{|x| [x['title'], x['file']['mp3-128']] }
# ^ are mp3-128s really the only format? 

list.each.with_index do |x, i|
  puts "downloading #{x[0]} from #{x[1]}..."
  Curl::Easy.download(x[1], (i + 1).to_s.rjust(2, "0") + " - " + x[0].gsub(/[^a-zA-Z0-9 _'"-]/, '') + ".mp3")
end
```

**Comment by JDCourtney1969** [comment]
Hi.  I'm just a spectator here - a heavy user of Bandcamp who has used a couple of programs and web sites to convert many Bandcamp tracks to WAV files.   As of about a week ago, I am no longer able to produce large WAV files.   Someone told me it has something to do with "youtube-dl"...?  I am guessing it's a result of some changes made by people at Bandcamp....?     Is anyone else aware of this and has anyone tried to address this?   Either here, or in a different place (pull request?) on this site?   I am very new to this site and am having trouble navigating.  I'm just desperate to get this issue resolved.   Can anyone please help, or tell me where to go to find help?    Thank you!

**Comment by cleslie577** [comment]
Having the same issue, hoping there's a fix soon!

**Comment by vberlier** [comment]
Same here :+1:

**Comment by vberlier** [comment]
Just letting everyone know that [this pull request](https://github.com/ytdl-org/youtube-dl/pull/26684) fixes the problem. If you want to download an entire album check out [my comment](https://github.com/ytdl-org/youtube-dl/pull/26684#issuecomment-705253522).

**Comment by remitamine** [comment]
Will be fixed in the next version.

**Comment by mkrupczak3** [comment]
Blessed.

BTW, what is the status of yt-dl on GitHub? It was removed earlier due to some kind of bogus copyright strike?

Does this put further development of this tool on this platform at risk?

**Comment by PiotrDabrowskey** [comment]
@mkrupczak3 not really related to this issue, but here's a partial answer to your question:
https://github.blog/2020-11-16-standing-up-for-developers-youtube-dl-is-back/

**Comment by mkrupczak3** [comment]
<3

Glad to see Microsoft/GitHub standing up for the little guy.

The DMCA is a disaster piece of legislation, and the anti-circumvention clause is so broad I'm surprised it hasn't been rendered worthless by case law

**Comment by mkrupczak3** [comment]
Def will be using the contact option at the bottom of the letter.

Uh, I hate to ask this, but could this latest update to yt-dl for bandcamp de-obfuscation be in anyway perceived as an anti-circumvention measure? 

Might be better to be proactive than reactive to this in light of recent events

**Comment by 532910** [comment]
I confirm it work fine now!
