### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014'

### ISSUE THREAD

**Issue by chiaweilee** [ytdl-org/youtube-dl#26688]
## Checklist

- [ x ] I'm asking a question
- [ x ] I've looked through the README and FAQ for similar questions
- [ x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

```
youtube-dl -—proxy socks5://127.0.0.1:19181/ https://www.youtube.com/watch?v=mJv8xr****

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 58, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/options.py", line 888, in parseOpts
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1402, in parse_args
    self.error(str(err))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 17: ordinal not in range(128)
```

**Comment by dstftw** [comment]
Invalid non-ASCII dash in `-—proxy`.
