### ISSUE TITLE
PornHubPremium: Unable to extract title; youtube-dl version **2020.09.20**

### ISSUE THREAD

**Issue by kokos108** [ytdl-org/youtube-dl#26700]
## Checklist
* [x] I'm reporting a broken site support issue
* [x] I've verified that I'm running youtube-dl version **2020.09.20**
* [x] I've checked that all provided URLs are alive and playable in a browser
* [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
* [x] I've searched the bugtracker for similar bug reports including closed ones
* [x] I've read bugs section in FAQ

## Verbose log
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'cookies.txt', '--format', 'best', '--output', '%(upload_date)s %(title)s_%(height)sp.%(ext)s', 'https://www.pornhubpremium.com/view_video.php?viewkey=ph5ee2bb56e2203']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-93308-g1144d5c96d, ffprobe N-93308-g1144d5c96d
[debug] Proxy map: {}
[PornHub] ph5f648de8e4ddb: Downloading pc webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\pornhub.py", line 209, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 1019, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 1010, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Comment
Everything worked fine until 12-14 September, when Pornhub has updated user interface. The error occurs regardless of whether the "title" parameter in the command line is or not

**Comment by kokos108** [comment]
Seems like for now everything works fine on the same version
