### ISSUE TITLE
RTVS.sk not working

### ISSUE THREAD

**Issue by MiNH0** [ytdl-org/youtube-dl#26731]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl https://www.rtvs.sk/televizia/archiv/14076/242474 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.rtvs.sk/televizia/archiv/14076/242474', '--verbose']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[RTVS] 242474: Downloading webpage
ERROR: Unable to extract playlist url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\rtvs.py", line 43, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 1010, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract playlist url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Looks like they made another change on website, so download is not working again.

**Comment by palos-ba** [comment]
RTVS support is stil broken in version 2021.01.03
Maybe this could help - it's how I'm playing videos from RTVS television archive:
```
#!/bin/bash
#URL example: https://www.rtvs.sk/televizia/archiv/16987/257523
URL="$1"
#the last path part contains video ID
VID="${URL##*/}"
URL_PROTO=${URL%%//*}
#find URL of JSON playlist specification in original URL content
PLAYLIST_JSON=`curl -s $URL | grep "id=$VID" | cut -d '"' -f 2`
#parameters b, p, v, d are optional; ruurl="b="+$.browser.name+"&p="+$.browser.platform+"&v="+$.browser.versionNumber+"&d="+Number($.browser.desktop||0)
#jq tool is from https://stedolan.github.io/jq/
PLAYLIST=`curl -s "$URL_PROTO$PLAYLIST_JSON&b=mozilla&p=linux&v=84&d=1" | jq -r .clip.sources[0].src`
mpv "$PLAYLIST"
```
