### ISSUE TITLE
Unable to download from ok.ru

### ISSUE THREAD

**Issue by jalalsfs** [ytdl-org/youtube-dl#26745]
Hello there,

When I tried to download a video from ok.ru I get an error:

`$ youtube-dl --verbose https://ok.ru/video/1963340008068
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://ok.ru/video/1963340008068']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.8.5 (CPython) - Linux-5.8.10-200.fc32.x86_64-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[Odnoklassniki] 1963340008068: Downloading webpage
ERROR: Unable to extract player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/odnoklassniki.py", line 149, in _real_extract
    unescapeHTML(self._search_regex(
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

I am not sure if 'youtube-dl' is supported ok.ru website or not.
Thank you.

**Comment by october262** [comment]
video downloads ok here on my end. try just like this > youtube-dl https://ok.ru/video/1963340008068

**Comment by namekal** [comment]
+1 I'm having issues also. I even tested @october262's command above as well just in case. Just did a fresh download of youtube-dl moments ago just to pull a video.


```
➜  other youtube-dl --verbose https://ok.ru/video/1908413827609
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://ok.ru/video/1908413827609']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-26-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[Odnoklassniki] 1908413827609: Downloading webpage
[Odnoklassniki] 1908413827609: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 400: Bad Request
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://vd298.mycdn.me/?expires=1602447170702&srcIp=45.77.221.186&srcAg=CHROME&ms=185.226.53.7&type=5&sig=ZW2R6UIFni4&ct=4&urls=185.226.52.8&clientType=0&id=871628016153'
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 348, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 114, in establish_connection
    raise err
HTTPError: HTTP Error 400: Bad Request
```
```
➜  other youtube-dl --verbose  https://ok.ru/video/1963340008068
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://ok.ru/video/1963340008068']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-26-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[Odnoklassniki] 1963340008068: Downloading webpage
[Odnoklassniki] 1963340008068: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 400: Bad Request
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://vd303.mycdn.me/?expires=1602447215528&srcIp=45.77.221.186&srcAg=CHROME&ms=185.226.53.12&type=2&sig=Ogd6YRcesQA&ct=4&urls=185.226.52.22&clientType=0&id=808918321796'
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 348, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 114, in establish_connection
    raise err
HTTPError: HTTP Error 400: Bad Request
```
```
➜  other youtube-dl https://ok.ru/video/1963340008068
[Odnoklassniki] 1963340008068: Downloading webpage
[Odnoklassniki] 1963340008068: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 400: Bad Request
ERROR: unable to download video data: HTTP Error 400: Bad Request
```

**Comment by october262** [comment]
> https://ok.ru/video/1908413827609



> +1 I'm having issues also. I even tested @october262's command above as well just in case. Just did a fresh download of youtube-dl moments ago just to pull a video.
> 
> ```
> ➜  other youtube-dl --verbose https://ok.ru/video/1908413827609
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'--verbose', u'https://ok.ru/video/1908413827609']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2020.09.20
> [debug] Python version 2.7.18 (CPython) - Linux-5.4.0-26-generic-x86_64-with-Ubuntu-20.04-focal
> [debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
> [debug] Proxy map: {}
> [Odnoklassniki] 1908413827609: Downloading webpage
> [Odnoklassniki] 1908413827609: Downloading m3u8 information
> WARNING: Failed to download m3u8 information: HTTP Error 400: Bad Request
> [debug] Default format spec: bestvideo+bestaudio/best
> [debug] Invoking downloader on u'https://vd298.mycdn.me/?expires=1602447170702&srcIp=45.77.221.186&srcAg=CHROME&ms=185.226.53.7&type=5&sig=ZW2R6UIFni4&ct=4&urls=185.226.52.8&clientType=0&id=871628016153'
> ERROR: unable to download video data: HTTP Error 400: Bad Request
> Traceback (most recent call last):
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1926, in process_info
>     success = dl(filename, info_dict)
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
>     return fd.download(name, info)
>   File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
>     return self.real_download(filename, info_dict)
>   File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 348, in real_download
>     establish_connection()
>   File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 114, in establish_connection
>     raise err
> HTTPError: HTTP Error 400: Bad Request
> ```
> 
> ```
> ➜  other youtube-dl --verbose  https://ok.ru/video/1963340008068
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'--verbose', u'https://ok.ru/video/1963340008068']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2020.09.20
> [debug] Python version 2.7.18 (CPython) - Linux-5.4.0-26-generic-x86_64-with-Ubuntu-20.04-focal
> [debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
> [debug] Proxy map: {}
> [Odnoklassniki] 1963340008068: Downloading webpage
> [Odnoklassniki] 1963340008068: Downloading m3u8 information
> WARNING: Failed to download m3u8 information: HTTP Error 400: Bad Request
> [debug] Default format spec: bestvideo+bestaudio/best
> [debug] Invoking downloader on u'https://vd303.mycdn.me/?expires=1602447215528&srcIp=45.77.221.186&srcAg=CHROME&ms=185.226.53.12&type=2&sig=Ogd6YRcesQA&ct=4&urls=185.226.52.22&clientType=0&id=808918321796'
> ERROR: unable to download video data: HTTP Error 400: Bad Request
> Traceback (most recent call last):
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1926, in process_info
>     success = dl(filename, info_dict)
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
>     return fd.download(name, info)
>   File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
>     return self.real_download(filename, info_dict)
>   File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 348, in real_download
>     establish_connection()
>   File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 114, in establish_connection
>     raise err
> HTTPError: HTTP Error 400: Bad Request
> ```
> 
> ```
> ➜  other youtube-dl https://ok.ru/video/1963340008068
> [Odnoklassniki] 1963340008068: Downloading webpage
> [Odnoklassniki] 1963340008068: Downloading m3u8 information
> WARNING: Failed to download m3u8 information: HTTP Error 400: Bad Request
> ERROR: unable to download video data: HTTP Error 400: Bad Request
> ```

just tried your link, works ok for me.
may want to run sudo apt update & sudo apt upgrade see if you are 
up to date on everything.

**Comment by sam2kb** [comment]
I was having the same problem until I realized that my VPN was on. Disabled it and the download went through.
I have a DNS blocker on the VPN so it could be that and not the actual VPN.
