### ISSUE TITLE
macOS: "ERROR: requested format not available” Twitch

### ISSUE THREAD

**Issue by ghost** [ytdl-org/youtube-dl#26742]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.09.20**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v https://www.twitch.tv/videos/754438999
[debug] System config: []
[debug] User config: ['-i', '-f', 'bestvideo+bestaudio', '--merge-output-format', 'mp4', '--write-sub', '--add-metadata', '--recode-video', 'mp4', '-o', '~/Movies/%(uploader)s/%(upload_date)s %(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.twitch.tv/videos/754438999']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.8.5 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[twitch:vod] 754438999: Downloading video info JSON
[twitch:vod] 754438999: Downloading vod access token
[twitch:vod] 754438999: Downloading m3u8 information
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1635, in process_video_result
    raise ExtractorError('requested format not available',
youtube_dl.utils.ExtractorError: requested format not available
```

## Description

When attempting to download from Twitch.tv in macOS, I get the above error. Works fine on Raspberry Pi 4.

**Comment by stevenbuehler** [comment]
Update: Didn’t like `-f bestaudio+bestvideo` as an option in my config file.

**Comment by geoffmacintosh** [comment]
Same issue, same solution, basically. I was using custom settings in mpv that supplied `-f` options and Twitch no longer seems to be okay with them. I'm running the same version of YouTube-dl.
