### ISSUE TITLE
VrtNU canvas.py extractor fails to download file

### ISSUE THREAD

**Issue by ymajik** [ytdl-org/youtube-dl#26755]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```bash
youtube-dl --verbose 'https://www.vrt.be/vrtnu/a-z/beweeg-in-uw-kot-/1/beweeg-in-uw-kot--s1a28'                
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.vrt.be/vrtnu/a-z/beweeg-in-uw-kot-/1/beweeg-in-uw-kot--s1a28']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-1127.19.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[VrtNU] beweeg-in-uw-kot--s1a28: Downloading webpage
[VrtNU] beweeg-in-uw-kot--s1a28: Downloading JSON metadata
[Canvas] pbs-pub-b4785add-6fc4-458d-aac5-258674270700$vid-9ffae04d-f46e-428a-bba1-d6ef68059efc: Downloading asset JSON
WARNING: Unable to download asset JSON: HTTP Error 410: Gone
[Canvas] pbs-pub-b4785add-6fc4-458d-aac5-258674270700$vid-9ffae04d-f46e-428a-bba1-d6ef68059efc: Downloading token
[Canvas] pbs-pub-b4785add-6fc4-458d-aac5-258674270700$vid-9ffae04d-f46e-428a-bba1-d6ef68059efc: Downloading video JSON
ERROR: An extractor error has occurred. (caused by KeyError(u'title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ymajik/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/ymajik/.local/lib/python2.7/site-packages/youtube_dl/extractor/canvas.py", line 74, in _real_extract
    title = data['title']
KeyError: u'title'
Traceback (most recent call last):
  File "/home/ymajik/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/ymajik/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 545, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Youtube-dl Canvas extractor for VRTnu fails to download json (warning) and eventually the file fails as well. From what I've looked at using `git blame` none of the code seemed to be altered recently, I guess something has changed on the content provider site, that needs to be matched in the Python code, regarding the title of the content. The issue is present for all the URL's I've tried on VRTnu. An account (https://www.vrt.be/vrtnu/#popover:profile) is needed to access this content

**Comment by Michaelseay** [comment]
![image](https://user-images.githubusercontent.com/66641244/94759917-388dc380-036f-11eb-8619-0bdf999ce889.jpeg)

**Comment by ymajik** [comment]
I did some further debugging, issue is with the extractor in combination with a .netrc file. User and pass on the command line just works fine. Closing this issue.
