### ISSUE TITLE
mtv.fi login information doesn't work

### ISSUE THREAD

**Issue by svalavuo** [ytdl-org/youtube-dl#26760]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dl --verbose https://www.mtv.fi/sarja/muumilaakson-tarinoita-33003620001/jakso-17-villin-lannen-seikkailu-1295385
[debug] System config: []
[debug] User config: [u'--netrc']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.mtv.fi/sarja/muumilaakson-tarinoita-33003620001/jakso-17-villin-lannen-seikkailu-1295385']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.10 (CPython) - Linux-4.14.x-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2
[debug] Proxy map: {}
[debug] Using fake IP 91.152.236.89 (FI) as X-Forwarded-For.
[Katsomo] 1295385: Downloading play JSON
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tv2.py", line 51, in _real_extract
    video_id, 'Downloading play JSON')['playback']
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 897, in _download_json
    expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 875, in _download_json_handle
    expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 665, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 650, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tv2.py", line 59, in _real_extract
    self.raise_login_required()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 941, in raise_login_required
    expected=True)
ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.

## Description

.netrc includes row for Katsomo
Tried with --username --passwrd -combo too, but got the same result.

**Comment by dirkf** [comment]
#22477
