### ISSUE TITLE
Unable to download from Miomio.us

### ISSUE THREAD

**Issue by taike48** [ytdl-org/youtube-dl#26769]
## Checklist
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
youtube-dl -v https://miomio.us/gamecenter201001.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://miomio.us/gamecenter201001.html']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[generic] gamecenter201001: Requesting header
WARNING: Falling back on generic information extractor.
[generic] gamecenter201001: Downloading webpage
[generic] gamecenter201001: Extracting information
ERROR: Unsupported URL: https://miomio.us/gamecenter201001.html
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://miomio.us/gamecenter201001.html

## Description
I am unable to download videos from Miomio.us, i.e. https://miomio.us/gamecenter201001.html

**Comment by txmutt** [comment]
The URL regex in the miomio extractor seems to only match URLs with the ".tv" extension, not ".us". All test cases for the extractor fail, since the "miomio.tv" domain no longer exists.

**Comment by taike48** [comment]
Any chances of this new domain being added?

**Comment by october262** [comment]
try using the addon video download helper
it's detecting the video files

**Comment by txmutt** [comment]
As for the current extractor, it seems like it will need a pretty major rework. At a glance, miomio stores JSON data in the `options` attribute in a div element whose `class` element equals `vid-card_cnt h-mod`. Within the `metadata` key of this data lies a big string of JSON data about the video specifically. From there, you can find direct links to all of the video variants sorted from lowest quality to highest in an array called `videos` (use `-1` as an index to select the last video in the array.)

**Comment by txmutt** [comment]
This data also contains other valuable info like the title, ID, and thumbnail of the video in the `movie` key.

**Comment by Kenniq** [comment]
I've been trying to follow as you said but I'm having trouble finding. Could you help me out?

**Comment by txmutt** [comment]
Seems like there are multiple different players Miomio embeds in an iframe, mainly JWPlayer and the OdnoKlassniki player.

For the OK player, right click on it while it's playing, and click "Link to video". Paste that link into youtube-dl to download the video. As for JWPlayer, I'll examine it when I find some spare time.

**Comment by txmutt** [comment]
Or just use a browser add-on that can detect these streams, like @october262 suggested.

**Comment by SamuSoft** [comment]
it seems as if miomio has been renamed now, and now goes by jshow.tv
