### ISSUE TITLE
[TikTok] Unsupported URL

### ISSUE THREAD

**Issue by Kelmaks** [ytdl-org/youtube-dl#26776]
## Checklist

- [ x] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2020.09.20**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

I tried many URLS like ...

youtube-dl https://vt.tiktok.com/ZSu1kHk5/
youtube-dl https://vm.tiktok.com/ZSm72LcV/
YouTube-dl https://www.tiktok.com/@4d_buildss/video/6877602760854981893?lang=en

Every time "Unsupported URL" - Is it possible to change the extractor that all possible urls are working?

Regards

**Comment by mralext20** [comment]
verbose logs:

``` PS C:\Users\alext> youtube-dl https://vt.tiktok.com/ZSu1kHk5/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vt.tiktok.com/ZSu1kHk5/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-06-20-29ea4e1, ffprobe git-2020-06-20-29ea4e1
[debug] Proxy map: {}
[generic] ZSu1kHk5: Requesting header
[redirect] Following redirect to https://www.tiktok.com/@fiya_dhiraaisyah/video/6876762295918234881?_d=secCgsIARCbDRgBIAMoARI%2BCjwbzTfXYXgN2EUh%2BpyU1NMq%2FvBwptyOFg86FZxdExHeGQJS8r3i8qfjGzeH2lVWvoYbNZ7mdkeE2nbeVgEaAA%3D%3D&language=id&mid=6876762322782669569&preview_pb=0&region=ID&sec_user_id=MS4wLjABAAAAElrG7dSWnB0Yp-mlXZ4W-_1kpO5x0JVi65i9A_bVT6TDAP2SIxN0gETece9guuhg&share_app_name=tiktok&share_item_id=6876762295918234881&share_link_id=18b23f6f-f36c-4293-9e9a-de92f76bc1dd&timestamp=1601191655&u_code=dbh5d6ck35ce3m&user_id=6809962401056900098&utm_campaign=client_share&utm_medium=android&utm_source=copy&source=h5_t
[generic] 6876762295918234881?_d=secCgsIARCbDRgBIAMoARI+CjwbzTfXYXgN2EUh+pyU1NMq/vBwptyOFg86FZxdExHeGQJS8r3i8qfjGzeH2lVWvoYbNZ7mdkeE2nbeVgEaAA==&language=id&mid=6876762322782669569&preview_pb=0&region=ID&sec_user_id=MS4wLjABAAAAElrG7dSWnB0Yp-mlXZ4W-_1kpO5x0JVi65i9A_bVT6TDAP2SIxN0gETece9guuhg&share_app_name=tiktok&share_item_id=6876762295918234881&share_link_id=18b23f6f-f36c-4293-9e9a-de92f76bc1dd&timestamp=1601191655&u_code=dbh5d6ck35ce3m&user_id=6809962401056900098&utm_campaign=client_share&utm_medium=android&utm_source=copy&source=h5_t: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 6876762295918234881?_d=secCgsIARCbDRgBIAMoARI+CjwbzTfXYXgN2EUh+pyU1NMq/vBwptyOFg86FZxdExHeGQJS8r3i8qfjGzeH2lVWvoYbNZ7mdkeE2nbeVgEaAA==&language=id&mid=6876762322782669569&preview_pb=0&region=ID&sec_user_id=MS4wLjABAAAAElrG7dSWnB0Yp-mlXZ4W-_1kpO5x0JVi65i9A_bVT6TDAP2SIxN0gETece9guuhg&share_app_name=tiktok&share_item_id=6876762295918234881&share_link_id=18b23f6f-f36c-4293-9e9a-de92f76bc1dd&timestamp=1601191655&u_code=dbh5d6ck35ce3m&user_id=6809962401056900098&utm_campaign=client_share&utm_medium=android&utm_source=copy&source=h5_t: Downloading webpage
[generic] 6876762295918234881?_d=secCgsIARCbDRgBIAMoARI+CjwbzTfXYXgN2EUh+pyU1NMq/vBwptyOFg86FZxdExHeGQJS8r3i8qfjGzeH2lVWvoYbNZ7mdkeE2nbeVgEaAA==&language=id&mid=6876762322782669569&preview_pb=0&region=ID&sec_user_id=MS4wLjABAAAAElrG7dSWnB0Yp-mlXZ4W-_1kpO5x0JVi65i9A_bVT6TDAP2SIxN0gETece9guuhg&share_app_name=tiktok&share_item_id=6876762295918234881&share_link_id=18b23f6f-f36c-4293-9e9a-de92f76bc1dd&timestamp=1601191655&u_code=dbh5d6ck35ce3m&user_id=6809962401056900098&utm_campaign=client_share&utm_medium=android&utm_source=copy&source=h5_t: Extracting information
[download] Downloading playlist: Asssalamu'alaikum, pati sudah pada hafal sama shalawat ini, alhamdulillah, #allahulkafi #shalawat #fiya_dhiraaisyah
[generic] playlist Asssalamu'alaikum, pati sudah pada hafal sama shalawat ini, alhamdulillah, #allahulkafi #shalawat #fiya_dhiraaisyah: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://v16-web-newkey.tiktokcdn.com/12b9daef10416758009485cf64ef1ac5/5f7a8b30/video/tos/alisg/tos-alisg-pve-0037c001/b4dc0b394d6f42f7a2077697f6e84197/?a=1988&br=4330&bt=2165&cr=0&cs=0&cv=1&dr=3&ds=3&er=&l=20201004205523010190176042279FE1FA&lr=tiktok&mime_type=video_mp4&qs=0&rc=amRsOGd1ajZsdzMzMzgzM0ApPDs3ODQ5NDw2NzM4NWlnPGdrcmZwY2lraGtfLS1hLzRzc19gM2FiLjRiYDUyXjUwXzU6Yw==&vl=&vr='
ERROR: unable to open for writing: [Errno 2] No such file or directory: "Asssalamu'alaikum, pati sudah pada hafal sama shalawat ini, alhamdulillah, #allahulkafi #shalawat #fiya_dhiraaisyah-6876762295918234881_d=secCgsIARCbDRgBIAMoARI+CjwbzTfXYXgN2EUh+pyU1NMq_vBwptyOFg86FZxdExHeGQJS8r3i8qfjGzeH2lVWvoYbNZ7mdkeE2nbeVgEaAA==&language=id&mid=6876762322782669569&preview_pb=0&region=ID&sec_user_id=MS4wLjABAAAAElrG7dSWnB0Yp-mlXZ4W-_1kpO5x0JVi65i9A_bVT6TDAP2SIxN0gETece9guuhg&share_app_name=tiktok&share_item_id=6876762295918234881&share_link_id=18b23f6f-f36c-4293-9e9a-de92f76bc1dd&timestamp=1601191655&u_code=dbh5d6ck35ce3m&user_id=6809962401056900098&utm_campaign=client_share&utm_medium=android&utm_source=copy&source=h5_t.unknown_video.part"
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\downloader\http.py", line 257, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\utils.py", line 2054, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: "Asssalamu'alaikum, pati sudah pada hafal sama shalawat ini, alhamdulillah, #allahulkafi #shalawat #fiya_dhiraaisyah-6876762295918234881_d=secCgsIARCbDRgBIAMoARI+CjwbzTfXYXgN2EUh+pyU1NMq_vBwptyOFg86FZxdExHeGQJS8r3i8qfjGzeH2lVWvoYbNZ7mdkeE2nbeVgEaAA==&language=id&mid=6876762322782669569&preview_pb=0&region=ID&sec_user_id=MS4wLjABAAAAElrG7dSWnB0Yp-mlXZ4W-_1kpO5x0JVi65i9A_bVT6TDAP2SIxN0gETece9guuhg&share_app_name=tiktok&share_item_id=6876762295918234881&share_link_id=18b23f6f-f36c-4293-9e9a-de92f76bc1dd&timestamp=1601191655&u_code=dbh5d6ck35ce3m&user_id=6809962401056900098&utm_campaign=client_share&utm_medium=android&utm_source=copy&source=h5_t.unknown_video.part"
```

**Comment by jayvgithub** [comment]
any update still unable to download
