### ISSUE TITLE
southpark.cc.com not working

### ISSUE THREAD

**Issue by 2ShedsJackson** [ytdl-org/youtube-dl#26777]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://southpark.cc.com/episodes/yy0vjs/south-park-the-pandemic-special-season-24-ep-1']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.8.2 (CPython) - FreeBSD-12.0-RELEASE-p3-amd64-64bit-ELF
[debug] exe versions: none
[debug] Proxy map: {}
[southpark.cc.com] south-park-the-pandemic-special-season-24-ep-1: Downloading webpage
Traceback (most recent call last):
  File "/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
  File "/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
  File "/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 287, in _real_extract
  File "/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 213, in _get_videos_info
  File "/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 39, in _id_from_uri
AttributeError: 'NoneType' object has no attribute 'split'
```

## Description

Using youtube-dl just results in the error message "AttributeError: 'NoneType' object has no attribute 'split'"
The video's master.m3u8 files are accessible and allow the video to be downloaded and played.

**Comment by SkiTheSlicer** [comment]
They changed their URL structure a little while ago. Similar issue to https://github.com/ytdl-org/youtube-dl/issues/26763#issuecomment-702511337

**Comment by ParadoxGBB** [comment]
Error with latest CC / MTV fixes is now:

PS F:\GREG\OneDrive\tools\CinAdmin> C:\Python\python.exe  F:\GREG\OneDrive\Projects\youtube-dl\youtube-dl -o "F:\GREG\DATA\CinAdmin\data\Subscriptions\i3j24ra1.wp3\%(title)s.%(ext)s" --fixup detect_or_warn --verbose --recode-video mp4 --ffmpeg-location F:\GREG\OneDrive\tools\ffmpeg "https://southpark.cc.com/episodes/z4ipl3/south-park-christmas-snow-season-23-ep-
10"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'F:\\GREG\\DATA\\CinAdmin\\data\\Subscriptions\\i3j24ra1.wp3\\%(title)s.%(ext)s', '--fixup', 'detect_or_warn', '--verbose', '--recode-video', 'mp4', '--ffmpeg-location', 'F:\\GREG\\OneDrive\\tools\\ffmpeg', 'https://southpark.cc.com/episodes/z4ipl3/south-park-christmas-snow-season-23-ep-10']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-03-15-c467328, ffprobe git-2020-03-15-c467328
[debug] Proxy map: {}
[southpark.cc.com] south-park-christmas-snow-season-23-ep-10: Downloading webpage
[southpark.cc.com] ac8dec94-b355-11e9-9fb2-70df2f866ace: Downloading info
ERROR: Unable to download XML: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "F:\GREG\OneDrive\Projects\youtube-dl\youtube-dl\youtube_dl\extractor\common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "F:\GREG\OneDrive\Projects\youtube-dl\youtube-dl\youtube_dl\YoutubeDL.py", line 2275, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Python\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Python\lib\urllib\request.py", line 555, in error
    result = self._call_chain(*args)
  File "C:\Python\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Python\lib\urllib\request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Python\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Python\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Python\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Python\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by icsllcweb** [comment]
I am getting an SSL error, not a 404 error:

C:\_FILES\ytdl>youtube-dl https://southpark.cc.com/episodes/yy0vjs/south-park-the-pandemic-special-season-24-ep-1
[southpark.cc.com] south-park-the-pandemic-special-season-24-ep-1: Downloading webpage
[southpark.cc.com] 230a4f02-f583-11ea-834d-70df2f866ace: Downloading info
[southpark.cc.com] 5c1a7f3a-d929-4b65-a71d-949551509499: Extracting information
[southpark.cc.com] 5c1a7f3a-d929-4b65-a71d-949551509499: Downloading video urls
[southpark.cc.com] 5c1a7f3a-d929-4b65-a71d-949551509499: Downloading m3u8 information
[southpark.cc.com] 8fe4ba73-89cd-444e-a877-6d1bb7c04c36: Extracting information
[southpark.cc.com] 8fe4ba73-89cd-444e-a877-6d1bb7c04c36: Downloading video urls
[southpark.cc.com] 8fe4ba73-89cd-444e-a877-6d1bb7c04c36: Downloading m3u8 information
[southpark.cc.com] badf8592-8a42-4afa-b23b-fe67ae282bfc: Extracting information
[southpark.cc.com] badf8592-8a42-4afa-b23b-fe67ae282bfc: Downloading video urls
[southpark.cc.com] badf8592-8a42-4afa-b23b-fe67ae282bfc: Downloading m3u8 information
[southpark.cc.com] 227346f3-4259-43b8-ab9a-330569ed685c: Extracting information
[southpark.cc.com] 227346f3-4259-43b8-ab9a-330569ed685c: Downloading video urls
[southpark.cc.com] 227346f3-4259-43b8-ab9a-330569ed685c: Downloading m3u8 information
[southpark.cc.com] ba5f81ec-d127-414b-afe8-d4490d7953c2: Extracting information
[southpark.cc.com] ba5f81ec-d127-414b-afe8-d4490d7953c2: Downloading video urls
[southpark.cc.com] ba5f81ec-d127-414b-afe8-d4490d7953c2: Downloading m3u8 information
[southpark.cc.com] 0a884b95-1d12-4094-8957-d14fdc02a5cd: Extracting information
[southpark.cc.com] 0a884b95-1d12-4094-8957-d14fdc02a5cd: Downloading video urls
[southpark.cc.com] 0a884b95-1d12-4094-8957-d14fdc02a5cd: Downloading m3u8 information
[southpark.cc.com] 0594d49e-2c8d-4065-ae82-13783af4f1f5: Extracting information
[southpark.cc.com] 0594d49e-2c8d-4065-ae82-13783af4f1f5: Downloading video urls
[southpark.cc.com] 0594d49e-2c8d-4065-ae82-13783af4f1f5: Downloading m3u8 information
[download] Downloading playlist: The Pandemic Special
[southpark.cc.com] playlist The Pandemic Special: Collected 7 video ids (downloading 7 of them)
[download] Downloading video 1 of 7
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 99
[download] Destination: South Park _ 2401 _ E 2401 _ HDSS2401Z eng _ Version - 1033856 _ Comedy Central S1-5c1a7f3a-d929-4b65-a71d-949551509499.mp4
**ERROR: unable to download video data: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>**

C:\_FILES\ytdl>

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30731
