### ISSUE TITLE
[Funimation] betting-on-the-handshake-event: Failed to parse JSON No JSON object could be decoded

### ISSUE THREAD

**Issue by Disinterpreter** [ytdl-org/youtube-dl#26773]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.funimation.com/shows/tsukiuta-the-animation/betting-on-the-handshake-event/?qid=d4ad92c7c2d924b', u'--verbose']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[Funimation] betting-on-the-handshake-event: Downloading webpage
WARNING: [Funimation] betting-on-the-handshake-event: Failed to parse JSON No JSON object could be decoded
ERROR: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/funimation.py", line 100, in _real_extract
    ], webpage, fatal=True)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1140, in _html_search_meta
    html, display_name, fatal=fatal, group='content', **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1019, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
PASTE VERBOSE LOG HERE
```

## Description

There is a problem with downloading from Funimation.

**Comment by october262** [comment]
install the firefox addon called the stream detector
to get the m3u8 playlists. set it to youtub-dl command
click copy the url and paste into the terminal

**Comment by Disinterpreter** [comment]
> 
> 
> install the firefox addon called the stream detector
> to get the m3u8 playlists. set it to youtub-dl command
> click copy the url and paste into the terminal

Oh... Sorry I found solving of the problem.

I add a user-agent and cookies for it works.
```
youtube-dl --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" --cookies funimation-cookies.txt 'animelink'
```

P.S I suggest to add a notify in parser about users have to add ua and cookies arguments. The message notify people for adding arguments and they won't to create duplicate issues.

**Comment by novasharper** [comment]
That does not seem to be working for me, which is odd since just using straight cURL with a cookiejar works for fetching the video metadata.

**Comment by Elliander** [comment]
I am having the same issue. In the command prompt, using the windows latest version installed tonight, Here's my command line information, with my actual username and password replaced as USERNAME and PASSWORD. I was testing with the first episode of "Black Clover" which I have no problem playing in a browser.

```
C:\compile>youtube-dl https://www.funimation.com/shows/black-clover/asta-and-yuno/?qid= --username USERNAME --password PASSWORD
[Funimation] Logging in
[Funimation] asta-and-yuno: Downloading webpage
WARNING: [Funimation] asta-and-yuno: Failed to parse JSON Expecting value: line 1 column 1 (char 0)
ERROR: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

And here's the output using the verbose flag:

```
C:\compile>youtube-dl https://www.funimation.com/shows/black-clover/asta-and-yuno/?qid= --username USERNAME --password PASSWORD --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.funimation.com/shows/black-clover/asta-and-yuno/?qid=', '--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.02.04.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}
[Funimation] Logging in
[Funimation] asta-and-yuno: Downloading webpage
WARNING: [Funimation] asta-and-yuno: Failed to parse JSON Expecting value: line 1 column 1 (char 0)
ERROR: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpgi7ngq0n\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpgi7ngq0n\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpgi7ngq0n\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpgi7ngq0n\build\youtube_dl\extractor\funimation.py", line 100, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpgi7ngq0n\build\youtube_dl\extractor\common.py", line 1140, in _html_search_meta
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpgi7ngq0n\build\youtube_dl\extractor\common.py", line 1019, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpgi7ngq0n\build\youtube_dl\extractor\common.py", line 1010, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Now, I also tried the suggestion above, but it didn't work for me either:

```
C:\compile>youtube-dl --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" --cookies funimation-cookies.txt 'https://www.funimation.com/shows/black-clover/asta-and-yuno/?qid='
ERROR: "'https://www.funimation.com/shows/black-clover/asta-and-yuno/?qid='" is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:'https://www.funimation.com/shows/black-clover/asta-and-yuno/?qid='" ) to search YouTube
```

I also tried using the youtube-dl GUI front end from [here](https://github.com/MrS0m30n3/youtube-dl-gui) which had the following error after giving it the login information:



I don't have problems downloading from other sites with either the command prompt or the GUI front end, so there's definately a problem with youtube-dl specifically with Funimation. Here's the logs it generated:

```
[02/07/21 23:21:26] WARNING: Unable to look up account info: HTTP Error 400: Bad Request
[02/07/21 23:22:27] WARNING: [Funimation] asta-and-yuno: Failed to parse JSON Expecting value: line 1 column 1 (char 0)
[02/07/21 23:22:27] ERROR: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 
```
