### ISSUE TITLE
ERROR: No video formats found in ruutu.fi

### ISSUE THREAD

**Issue by svalavuo** [ytdl-org/youtube-dl#26782]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
**Try #1:**
youtube-dl --verbose -f best -ci -o "/volume1/Video/leffat//%(title)s.%(ext)s" https://www.ruutu.fi/video/3632828
[debug] System config: []
[debug] User config: [u'--netrc']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-f', u'best', u'-ci', u'-o', u'/volume1/Video/leffat//%(title)s.%(ext)s', u'https://www.ruutu.fi/video/3632828']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.10 (CPython) - Linux-4.14.x-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2
[debug] Proxy map: {}
[Ruutu] 3632828: Downloading XML
[Ruutu] 3632828: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Ruutu] 3632828: Checking https URL
[Ruutu] 3632828: https URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ruutu.py", line 143, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1359, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Try #2**
python3 youtube_dl --verbose -f best -ci -o "/volume1/Video/leffat//%(title)s.%(ext)s" https://www.ruutu.fi/video/3632828
[debug] System config: []
[debug] User config: ['--netrc']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'best', '-ci', '-o', '/volume1/Video/leffat//%(title)s.%(ext)s', 'https://www.ruutu.fi/video/3632828']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.7.0 (CPython) - Linux-4.14.x-x86_64-with-glibc2.9
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2
[debug] Proxy map: {}
[Ruutu] 3632828: Downloading XML
[Ruutu] 3632828: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Ruutu] 3632828: Checking https URL
[Ruutu] 3632828: https URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/AppCentral/python3/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/AppCentral/python3/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/AppCentral/python3/lib/python3.7/site-packages/youtube_dl/extractor/ruutu.py", line 143, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/AppCentral/python3/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1359, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Try #3**
python3 -m youtube_dl --verbose -f best -ci -o "/volume1/Video/leffat//%(title)s.%(ext)s" https://www.ruutu.fi/video/3632828
[debug] System config: []
[debug] User config: ['--netrc']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'best', '-ci', '-o', '/volume1/Video/leffat//%(title)s.%(ext)s', 'https://www.ruutu.fi/video/3632828']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.11
[debug] Git HEAD: 05807d9c1
[debug] Python version 3.7.0 (CPython) - Linux-4.14.x-x86_64-with-glibc2.9
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2
[debug] Proxy map: {}
[Ruutu] 3632828: Downloading XML
[Ruutu] 3632828: Checking if video is available without authentication
WARNING: Authentication required: HTTP Error 403: Forbidden
[Ruutu] 3632828: Authenticating video url
[Ruutu] 3632828: Downloading m3u8 information
[Ruutu] 3632828: Checking if video is available without authentication
WARNING: Authentication required: HTTP Error 403: Forbidden
[Ruutu] 3632828: Authenticating video url
[Ruutu] 3632828: Checking if video is available without authentication
WARNING: Authentication required: HTTP Error 403: Forbidden
[Ruutu] 3632828: Authenticating video url
[Ruutu] 3632828: Checking https URL
[Ruutu] 3632828: https URL is invalid, skipping
[debug] Invoking downloader on 'http://nelonenmedia-stream-video-t.nm-stream.nelonenmedia.fi/86/online/video/video_episode_115144586.smil/index-f4-v1-a1.m3u8?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDE2NTU2MDUsIm5iZiI6MTYwMTY1NTMwNSwiZXhwIjoxNjAxNzQyMDA1LCJpcCI6IjgyLjE4MS41MC4xNjciLCJwYXRoIjoiLzg2L29ubGluZS92aWRlby92aWRlb19lcGlzb2RlXzExNTE0NDU4Ni5zbWlsLyJ9._KeeQrt8YvJc1eZpqP4YhkjeWjDqCTWcJH2baU9ohBE'
[download] Destination: /volume1/Video/leffat//Elokuva - Juliet, Naked (S) 25.06.2020 10_15.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-us,en;q=0.5
' -i 'http://nelonenmedia-stream-video-t.nm-stream.nelonenmedia.fi/86/online/video/video_episode_115144586.smil/index-f4-v1-a1.m3u8?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDE2NTU2MDUsIm5iZiI6MTYwMTY1NTMwNSwiZXhwIjoxNjAxNzQyMDA1LCJpcCI6IjgyLjE4MS41MC4xNjciLCJwYXRoIjoiLzg2L29ubGluZS92aWRlby92aWRlb19lcGlzb2RlXzExNTE0NDU4Ni5zbWlsLyJ9._KeeQrt8YvJc1eZpqP4YhkjeWjDqCTWcJH2baU9ohBE' -c copy -f mp4 'file:/volume1/Video/leffat//Elokuva - Juliet, Naked (S) 25.06.2020 10_15.mp4.part'
ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 4.6.4 (crosstool-NG crosstool-ng-1.22.0 - x86_64 64-bit toolchain - ASUSTOR Inc.)
  configuration: --enable-cross-compile --target-os=linux --arch=x86_64 --cross-prefix=x86_64-asustor-linux-gnu- --sysinclude=/AS6XX/x64_g3/staging/usr/include --extra-cflags='-I/AS6XX/x64_g3/staging/usr/include -I/AS6XX/x64_g3/staging/usr/builtin/include -I/AS6XX/x64_g3/staging/usr/local/include' --extra-ldflags='-Wl,--as-needed -L/AS6XX/x64_g3/staging/lib -L/AS6XX/x64_g3/staging/lib64 -L/AS6XX/x64_g3/staging/usr/lib -L/AS6XX/x64_g3/staging/usr/lib64 -L/AS6XX/x64_g3/staging/usr/builtin/lib -L/AS6XX/x64_g3/staging/usr/builtin/lib64 -L/AS6XX/x64_g3/staging/usr/local/lib' --prefix=/usr/local --pkg-config=pkg-config --enable-libmp3lame --enable-libvorbis --enable-libtheora --enable-libvpx --enable-libx264 --enable-vaapi --enable-libxvid --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libfdk-aac --enable-openssl --enable-libsoxr --enable-avresample --disable-decoder=dca --disable-decoder=ac3 --disable-decoder=ac3_fixed --disable-decoder=atrac3 --disable-decoder=atrac3al --disable-decoder=atrac3p --disable-decoder=atrac3pal --disable-decoder=eac3 --disable-decoder=truehd --disable-encoder=dca --disable-encoder=ac3 --disable-encoder=ac3_fixed --disable-encoder=eac3 --disable-encoder=truehd --enable-shared --enable-gpl --enable-nonfree --enable-version3 --disable-static --disable-doc --disable-debug
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100

```

## Description

I have youtube-dl installed in my Asustor AS6404T NAS
For some reason version 2020.09.20 doesn't work.
Try #1 is run with installed binary
Try #2 is run with python3 from the source directory of 2020.09.20
Try #3 is run with python3 and -m parameter in old source directory. _This one works, but lacks mtv.fi support_

I can live with this, but I'd like to have support for katsomo (mtv.fi) -videos. I have another issue regarding that #26760 

- Samuli

**Comment by svalavuo** [comment]
Downloading from youtube success (with both python -versions). Ruutu is failing, and katsomo as well (though different error).

**Comment by u2n** [comment]
Try removing the "s" in https://etc.?

**Comment by svalavuo** [comment]
Hi,

http doesn't work. Site redirects it to https. Something seems to be changed in youtube-dl, because with old source ruutu works (as stated in the start).

- Samuli
