### ISSUE TITLE
OnDemandKorea Cannot Pull Videos

### ISSUE THREAD

**Issue by kairushinjuu** [ytdl-org/youtube-dl#26818]
## Checklist

- [✓] I'm reporting a broken site support
- [✓] I've verified that I'm running youtube-dl version **2020.09.20**
- [✓] I've checked that all provided URLs are alive and playable in a browser
- [✓] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [✓] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

youtube-dl.exe --verbose https://www.ondemandkorea.com/nokdu-flower-e02-1.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.ondemandkorea.com/nokdu-flower-e02-1.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Using fake IP 99.239.165.161 (CA) as X-Forwarded-For.
[OnDemandKorea] nokdu-flower-e02-1: Downloading webpage
ERROR: Unable to extract jw config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\ondemandkorea.py", line 52, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 1010, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract jw config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Is the error I am getting

**Comment by october262** [comment]
use generic extractor >  youtube-dl  --force-generic-extractor https://www.ondemandkorea.com/nokdu-flower-e02-1.html

**Comment by kairushinjuu** [comment]
Thanks that got me further, however I am now getting this error message 
` [generic] nokdu-flower-e04-1: Requesting header
WARNING: Forcing on generic information extractor.
[generic] nokdu-flower-e04-1: Downloading webpage
[generic] nokdu-flower-e04-1: Extracting information
ERROR: Unsupported URL: https://www.ondemandkorea.com/nokdu-flower-e04-1.html ` I thought this was due to needing a premium account when I tried putting in both parameters got the same message ` youtube-dl.exe -u USERNAME -p PASSWORD  --force...`  any suggestions?

**Comment by october262** [comment]
do you have ffmpeg installed ??

**Comment by kairushinjuu** [comment]
Yes, I managed to get that bit working but now I am back at the original problem ```  C:\Users\NAME >C:\Users\NAME\Downloads\youtube-dl\youtube-dl.exe --username USERNAME --password PASSWORD --force-generic-extractor https://www.ondemandkorea.com/nokdu-flower-e04-1.html
[generic] nokdu-flower-e04-1: Requesting header
WARNING: Forcing on generic information extractor.
[generic] nokdu-flower-e04-1: Downloading webpage
[generic] nokdu-flower-e04-1: Extracting information
ERROR: Unsupported URL: https://www.ondemandkorea.com/nokdu-flower-e04-1.htm l```

I appreciate the help though

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by october262** [comment]
don't use the username & password option just use youtube-dl --force-generic-extractor https://www.ondemandkorea.com/nokdu-flower-e04-1.html
the video downloads just fine this way

**Comment by kartara** [comment]
Thanks October, that actually worked! :)

**Comment by IsaacMercado** [comment]
This is already fixed in #25877 to download it without the need for an additional command, but they have not done the merge
