### ISSUE TITLE
Can't extract public Facebook group video

### ISSUE THREAD

**Issue by kartara** [ytdl-org/youtube-dl#26823]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.facebook.com/groups/203844543912465/permalink/235228274107425/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.6.9 (CPython) - Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 235228274107425: Downloading webpage
[facebook] 235228274107425: Downloading webpage
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/facebook.py", line 484, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/facebook.py", line 351, in _extract_from_url
    self.raise_login_required()
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 941, in raise_login_required
    expected=True)
youtube_dl.utils.ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
```

## Description

Hello! i was trying to download this video frm a facebook page. They posted it to a group, but the group is public, so anyone can view the video. When I first tried it, it said I had to login, so i put in my credentials. However, it still said I had to login even after I logged in. What's the issue?

**Comment by tinybug** [comment]
try to use proxy, maybe you're limited by facebook

**Comment by kartara** [comment]
I've tried using a few proxies but they never work. Can you give me a proxy command that actually works?

**Comment by kartara** [comment]
Any update on this issue? Was it fixed?
