### ISSUE TITLE
USA Network Unsupported URL

### ISSUE THREAD

**Issue by jsmith1299** [ytdl-org/youtube-dl#26837]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe https://www.usanetwork.com/csi/video/in-a-dark-dark-house/3983276 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.usanetwork.com/csi/video/in-a-dark-dark-house/3983276', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-93485-g5282cbae61, ffprobe N-93485-g5282cbae61
[debug] Proxy map: {}
[generic] 3983276: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 3983276: Downloading webpage
[generic] 3983276: Extracting information
ERROR: Unsupported URL: https://www.usanetwork.com/csi/video/in-a-dark-dark-house/3983276
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.usanetwork.com/csi/video/in-a-dark-dark-house/3983276
```

## Description

USA Network links are not working

**Comment by remitamine** [comment]
Fixed in the latest version(2020.11.17).
