### ISSUE TITLE
Pluralsight Video Download Video Format Error

### ISSUE THREAD

**Issue by rinotom** [ytdl-org/youtube-dl#26878]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: ['--abort-on-error', '--no-warnings', '--console-title', '--batch-file=batch-file.txt', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36', '--cookies', 'pluralsight.com_cookies.txt', '--socket-timeout', '10', '--retries', '10', '--continue', '--fragment-retries', '10', '--min-sleep-interval', '60', '--max-sleep-interval', '80', '-f', 'best[height<=720]/worst[height>720]', '-o', '%(playlist_title)s/%(chapter_number)s - %(chapter)s/%(playlist_index)d-%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['--verbose']
[debug] Batch file urls: ['https://app.pluralsight.com/library/courses/openid-and-oauth2-securing-angular-apps']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] openid-and-oauth2-securing-angular-apps: Downloading JSON metadata
[download] Downloading playlist: Securing Angular Apps with OpenID Connect and OAuth 2
[pluralsight:course] playlist Securing Angular Apps with OpenID Connect and OAuth 2: Collected 58 video ids (downloading 58 of them)
[download] Downloading video 1 of 58
[pluralsight] 22a3299d-dc01-4351-adba-8f97ce3aa040-0: Downloading JSON metadata
[pluralsight] 22a3299d-dc01-4351-adba-8f97ce3aa040-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] 22a3299d-dc01-4351-adba-8f97ce3aa040-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] 22a3299d-dc01-4351-adba-8f97ce3aa040-0: Waiting for 5 seconds to avoid throttling
[debug] Invoking downloader on 'https://vid.pluralsight.com/clips/resolution/36aa5d15-58eb-4051-b7f2-e76d2f071fee/current/mp4/1280x720.mp4?8LwUzq5_aYiVXiUvlaYPjwmVkxfmbfb7j1IDVKBp8dN8UvMMZzztaeUg7d2XOj6VoWmWew4ZoM9fXwlhq5eeAiYinIQALkB61h-8ZJn97x8Dc2DsVYK04IiZEDHU0iVodigR25I3N79LkdKy3FMyORWjVK6GPEbfins9MqDG6GEcDuJ-P8dKD23c1NDI'
[download] Securing Angular Apps with OpenID Connect and OAuth 2\1 - Course Overview\1-Course Overview.mp4 has already been downloaded
[download] 100% of 4.83MiB
[download] Downloading video 2 of 58
[pluralsight] 3f8ec296-1c9c-461e-9886-af7a653de50b-0: Downloading JSON metadata
[pluralsight] 3f8ec296-1c9c-461e-9886-af7a653de50b-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] 3f8ec296-1c9c-461e-9886-af7a653de50b-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] 3f8ec296-1c9c-461e-9886-af7a653de50b-0: Waiting for 4 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\pluralsight.py", line 421, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 1359, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I am using a PluralSight free account but able to access courses now due to one-week free access to it.
I downloaded 5 courses for the first day within 9 hours.

Post to that I am facing the above error on downloading of any course in any system using youtube-dl and in the web browser, all course videos are still accessible.

**Comment by Largetable** [comment]
I'm having the same issue, I downloaded a course on the first day but I could only download 1 video from a course on the second day, then I get the same error as yours

**Comment by IlyaMrz** [comment]
same
Downloading video 21 of 46
WARNING: Unable to download JSON metadata: HTTP Error 429: Too Many Requests

**Comment by Largetable** [comment]
Well I found a solution that works, simply I Just created another account and it worked.

**Comment by correaguilherme** [comment]
Same issue here, but i can't download any file. Already tried with different accounts.

WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] 932e10e9-9238-486d-b754-e788a4dff9be-0: Waiting for 2 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
