### ISSUE TITLE
Cookies breaks ytsearch

### ISSUE THREAD

**Issue by sj-dan** [ytdl-org/youtube-dl#26898]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.8.6 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-07-30-134a48a, ffprobe git-2020-07-30-134a48a
[debug] Proxy map: {}
```

## Description

When I pass cookies to youtube_dl (python3), it gives me this error. The cookies are completely valid, and they work fine when I try to play an age-restricted video, and also prevent HTTP 429, but when I try to use the ytsearch feature, the following happens:

```
Traceback (most recent call last):
  File "C:\Users\Saro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Saro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Saro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\youtube_dl\extractor\common.py", line 3004, in _real_extract
    return self._get_n_results(query, 1)
  File "C:\Users\Saro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\youtube_dl\extractor\youtube.py", line 3200, in _get_n_results
    data = self._download_json(
  File "C:\Users\Saro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\youtube_dl\extractor\common.py", line 893, in _download_json
    res = self._download_json_handle(
  File "C:\Users\Saro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\youtube_dl\extractor\common.py", line 879, in _download_json_handle
    return self._parse_json(
  File "C:\Users\Saro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\youtube_dl\extractor\common.py", line 908, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: query "poo": Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```

**Comment by sj-dan** [comment]
cf

**Comment by neotherack** [comment]
> 
> 
> Well, what am I supposed to do? I searched previous ones, and got 0 answers.

Did you find anything? cannot find a solution for this.
