### ISSUE TITLE
itv.com support broken

### ISSUE THREAD

**Issue by jamesrc** [ytdl-org/youtube-dl#26896]
## Checklist

- [ x ] I'm reporting a broken site support
- [ x ] I've verified that I'm running youtube-dl version **2020.09.20**
- [ x ] I've checked that all provided URLs are alive and playable in a browser
- [ x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--no-geo-bypass', u'https://www.itv.com/hub/the-chase/1a7842a1441']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.13 (CPython) - Linux-4.19.66-v7+-armv7l-with-debian-9.11
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1
[debug] Proxy map: {}
[ITV] 1a7842a1441: Downloading webpage
[ITV] 1a7842a1441: Downloading XML
WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out
[ITV] 1a7842a1441: Downloading JSON metadata
[ITV] 1a7842a1441: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://itvpnpdotcom.content.itv.com/1-7842-1441-002/18/1/VAR012/1-7842-1441-002_18_1_VAR012.ism/1-7842-1441-002_18_1_VAR012-audio=128000-video=1442583.m3u8?redirect=1'
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 503: Service Unavailable
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 62, in real_download
    urlh = self.ydl.urlopen(self._prepare_url(info_dict, man_url))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
```

## Description

Downloading from itv.com seems broken, with a variety of 504, 503 and time out errors depending on the video.  Opening the video in a web browser works without issue.  Passing a username and password makes no difference (and was never required before).  Tried from two locations.

**Comment by ilike2burnthing** [comment]
Ignore everything beneath this for now and try redownloading. After all that testing it just started working again no matter what I did, so I'm wondering if it was a temporary site issue.

***************

Confirmed also not working properly in the UK, with or without `--no-geo-bypass` and for all formats, although `hls-1100` results in:
```
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 226
[download] Destination: The Chase - Monday 21 Sept 5pm-1a7842a1441.mp4
ERROR: giving up after 10 retries
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 863, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 1644, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 1926, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\downloader\hls.py", line 148, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\downloader\fragment.py", line 102, in _download_fragment
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\downloader\http.py", line 360, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\downloader\common.py", line 165, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 625, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 587, in trouble
```
Tried with ffmpeg instead  - `youtube-dl -v https://www.itv.com/hub/the-chase/1a7842a1441 -f hls-1100 --hls-prefer-ffmpeg`. Had to run it twice for it to actually work, and even then it ran with errors and unreachable segments:
```
[...]
[hls @ 0000021be794e480] Opening 'crypto+https://itvpnpdotcom.content.itv.com/1-7842-1441-002/18/1/VAR012/1-7842-1441-002_18_1_VAR012.ism/1-7842-1441-002_18_1_VAR012-audio=128000-video=909379-1.ts?redirect=1' for reading
[tcp @ 0000021be7bc4340] Starting connection attempt to 23.213.161.23 port 443
[tcp @ 0000021be7bc4340] Successfully connected to 23.213.161.23 port 443
[https @ 0000021be7bc3c00] HTTP error 503 Service Unavailable
[crypto @ 0000021be7bc3880] Unable to open resource: https://itvpnpdotcom.content.itv.com/1-7842-1441-002/18/1/VAR012/1-7842-1441-002_18_1_VAR012.ism/1-7842-1441-002_18_1_VAR012-audio=128000-video=909379-1.ts?redirect=1
[hls @ 0000021be794e480] Failed to open segment 1 of playlist 0
[hls @ 0000021be794e480] HLS request for url 'https://itvpnpdotcom.content.itv.com/1-7842-1441-002/18/1/VAR012/1-7842-1441-002_18_1_VAR012.ism/1-7842-1441-002_18_1_VAR012-audio=128000-video=909379-2.ts?redirect=1', offset 0, playlist 0
[hls @ 0000021be794e480] Opening 'crypto+https://itvpnpdotcom.content.itv.com/1-7842-1441-002/18/1/VAR012/1-7842-1441-002_18_1_VAR012.ism/1-7842-1441-002_18_1_VAR012-audio=128000-video=909379-2.ts?redirect=1' for reading
[...]
[mp4 @ 0000021be83344c0] Invalid DTS: 39600 PTS: 37800 in output stream 0:0, replacing by guess
[mp4 @ 0000021be83344c0] Invalid DTS: 41400 PTS: 39600 in output stream 0:0, replacing by guess
[hls @ 0000021be794e480] Invalid timestamps stream=1, pts=2023200, dts=2025000, size=219
[mp4 @ 0000021be83344c0] Invalid DTS: 45000 PTS: 43200 in output stream 0:0, replacing by guess
[mpegts @ 0000021be7cf6fc0] Invalid timestamps stream=1, pts=2028600, dts=2030400, size=312
[mpegts @ 0000021be7cf6fc0] Invalid timestamps stream=1, pts=2030400, dts=2032200, size=240
[hls @ 0000021be794e480] Invalid timestamps stream=1, pts=2028600, dts=2030400, size=312
[mp4 @ 0000021be83344c0] Invalid DTS: 50400 PTS: 48600 in output stream 0:0, replacing by guess
[hls @ 0000021be794e480] Invalid timestamps stream=1, pts=2030400, dts=2032200, size=240
[mp4 @ 0000021be83344c0] Invalid DTS: 52200 PTS: 50400 in output stream 0:0, replacing by guess
[mpegts @ 0000021be7cf6fc0] Invalid timestamps stream=1, pts=2034000, dts=2035800, size=182
[hls @ 0000021be794e480] Invalid timestamps stream=1, pts=2034000, dts=2035800, size=182
[...]
```
The resulting video seemed to work fine though.

Other formats failed with 503 error when using ffmpeg.

Trying `youtube-dl -v https://www.itv.com/hub/the-chase/1a7842a1441 -f hls-1100 --skip-unavailable-fragments -i` also failed.

**Comment by jamesrc** [comment]
Confirmed it seems to be working right now.  It's very curious, because I was able to play via the website from the same machine with no issue.

I'll run a few more tests and then close this issue.

**Comment by torbs723** [comment]
I did also notice this. Thankfully it does seem to have been a temporary server issue on their side which has now been resolved.

**Comment by jamesrc** [comment]
Closing this out as the problem seems to have righted itself.
