### ISSUE TITLE
ERROR: Conversion failed! when merging formats

### ISSUE THREAD

**Issue by literaldehyde** [ytdl-org/youtube-dl#26915]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\literaldehyde>youtube-dl https://www.youtube.com/watch?v=eRiF8mX_iVc -v
[debug] System config: []
[debug] User config: ['-o', 'C:/Users/literaldehyde/Desktop/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=eRiF8mX_iVc', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 2.2.2
[debug] Proxy map: {}
[youtube] eRiF8mX_iVc: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r4---sn-a5meknl7.googlevideo.com/videoplayback?expire=1602965699&ei=YvyKX5TXOtGmkgamlamQCg&ip=66.215.215.131&id=o-AJh-aNBJWqOlAq-mLyWalXutvVJnkY7tGhrKeoKCetiB&itag=244&aitags=133%2C134%2C135%2C160%2C242%2C243%2C244%2C278&source=youtube&requiressl=yes&mh=t2&mm=31%2C29&mn=sn-a5meknl7%2Csn-a5msen76&ms=au%2Crdu&mv=m&mvi=4&pl=18&initcwndbps=1857500&vprv=1&mime=video%2Fwebm&gir=yes&clen=994337&dur=246.847&lmt=1559225169800149&mt=1602943963&fvip=4&keepalive=yes&fexp=23915654&c=WEB&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgeBQZMANQ7WGQUcxdI3sOH5OMojjMGPsYHJxIBgmjnWoCIHOB9p0b4Gn2NGvnAMHAHSRLkjW0TYH3iRnYq_EVeo1E&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgOx3rw3HJvDS7pCj2ws7amXpMkHyFmerTnppBFu8Ek60CIFaF8XKmGsNzh1xfqkGbRTXou_UeMjyaKbUDc2n6kB0X&ratebypass=yes'
[download] Destination: C:\Users\literaldehyde\Desktop\Limbo Soundtrack 1 - Title Theme.f244.webm
[download] 100% of 971.03KiB in 00:00
[debug] Invoking downloader on 'https://r4---sn-a5meknl7.googlevideo.com/videoplayback?expire=1602965699&ei=YvyKX5TXOtGmkgamlamQCg&ip=66.215.215.131&id=o-AJh-aNBJWqOlAq-mLyWalXutvVJnkY7tGhrKeoKCetiB&itag=251&source=youtube&requiressl=yes&mh=t2&mm=31%2C29&mn=sn-a5meknl7%2Csn-a5msen76&ms=au%2Crdu&mv=m&mvi=4&pl=18&initcwndbps=1857500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=3535085&dur=246.921&lmt=1559225006769890&mt=1602943963&fvip=4&keepalive=yes&fexp=23915654&c=WEB&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAOIFPvUU3T2rBNqLFc1sDG0SEMdbkjQbH5sS-5Ulbvn3AiBJkAm0u5zQSFPwe4M92HUB-LdaFO2CSlcSXT3E4xSn4w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgOx3rw3HJvDS7pCj2ws7amXpMkHyFmerTnppBFu8Ek60CIFaF8XKmGsNzh1xfqkGbRTXou_UeMjyaKbUDc2n6kB0X&ratebypass=yes'
[download] Destination: C:\Users\literaldehyde\Desktop\Limbo Soundtrack 1 - Title Theme.f251.webm
[download] 100% of 3.37MiB in 00:00
[ffmpeg] Merging formats into "C:\Users\literaldehyde\Desktop\Limbo Soundtrack 1 - Title Theme.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\Users\literaldehyde\Desktop\Limbo Soundtrack 1 - Title Theme.f244.webm" -i "file:C:\Users\literaldehyde\Desktop\Limbo Soundtrack 1 - Title Theme.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:C:\Users\literaldehyde\Desktop\Limbo Soundtrack 1 - Title Theme.temp.webm"
ERROR: Conversion failed!
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 2065, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\postprocessor\ffmpeg.py", line 523, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

## Description

When downloading videos on youtube using no arguments besides (-o 'C:/Users/literaldehyde/Desktop/%(title)s.%(ext)s') in my config file, it errors out when converting component files. If I add the argument (--merge-output-format mkv), it works perfectly fine, but why does it fail with no arguments? Is it actually an ffmpeg error like it suggests, and if so how do I fix it?

**Comment by dstftw** [comment]
Outdated ffmpeg.
