### ISSUE TITLE
No video found on iVysilani/CeskaTelevize

### ISSUE THREAD

**Issue by nothrem** [ytdl-org/youtube-dl#26925]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.ceskatelevize.cz/ivysilani/898901-dobrodruzstvi-kriminalistiky/200310910500001-pismo']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.1
[debug] Proxy map: {}
[CeskaTelevize] 200310910500001-pismo: Downloading webpage
[CeskaTelevize] 200310910500001-pismo: Downloading JSON metadata
[CeskaTelevize] 200310910500001-pismo: Downloading JSON metadata
[CeskaTelevize] 200310910500001-pismo: Downloading JSON metadata
[CeskaTelevize] 200310910500001-pismo: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\ceskatelevize.py", line 201, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 1359, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Some parts of this series report that there is no video on the page (but in browser they play):
https://www.ceskatelevize.cz/ivysilani/898901-dobrodruzstvi-kriminalistiky/200310910500001-pismo
https://www.ceskatelevize.cz/ivysilani/898901-dobrodruzstvi-kriminalistiky/200310910500002-prvni-detektivni-sbor
https://www.ceskatelevize.cz/ivysilani/898901-dobrodruzstvi-kriminalistiky/200310910500003-modus-operandi
https://www.ceskatelevize.cz/ivysilani/898901-dobrodruzstvi-kriminalistiky/200310910500004-antropologie
https://www.ceskatelevize.cz/ivysilani/898901-dobrodruzstvi-kriminalistiky/200310910500005-krevni-skupina
https://www.ceskatelevize.cz/ivysilani/898901-dobrodruzstvi-kriminalistiky/200310910500006-mechanoskopie
https://www.ceskatelevize.cz/ivysilani/898901-dobrodruzstvi-kriminalistiky/200310910500007-identifikacni-kresba
https://www.ceskatelevize.cz/ivysilani/898901-dobrodruzstvi-kriminalistiky/200310910500008-paprsek
https://www.ceskatelevize.cz/ivysilani/898901-dobrodruzstvi-kriminalistiky/200353910560001-pinkertonova-detektivni-agentura
https://www.ceskatelevize.cz/ivysilani/898901-dobrodruzstvi-kriminalistiky/200353910560002-posledni-odvolani
https://www.ceskatelevize.cz/ivysilani/898901-dobrodruzstvi-kriminalistiky/200353910560003-pes
https://www.ceskatelevize.cz/ivysilani/898901-dobrodruzstvi-kriminalistiky/200353910560004-duplikat
https://www.ceskatelevize.cz/ivysilani/898901-dobrodruzstvi-kriminalistiky/200353910560005-padelek

While these parts can be downloaded without a problem:
https://www.ceskatelevize.cz/ivysilani/898901-dobrodruzstvi-kriminalistiky/289310910380001-stopa
https://www.ceskatelevize.cz/ivysilani/898901-dobrodruzstvi-kriminalistiky/289310910380007-rekonstrukce
https://www.ceskatelevize.cz/ivysilani/898901-dobrodruzstvi-kriminalistiky/289310910380008-tym
(for more parts see one of the above link)

**Comment by nothrem** [comment]
It seems the reason files cannot be downloaded is that **they contain DRM**.
