### ISSUE TITLE
youtube-dl says it requires an account to view/download the content from afreecaTV, but an account is already added in the command

### ISSUE THREAD

**Issue by chorong761** [ytdl-org/youtube-dl#26926]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.09.20**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '-v', 'http://vod.afreecatv.com/PLAYER/STATION/61942973']
[debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[afreecatv] Logging in
[afreecatv] 61942973: Downloading webpage
[afreecatv] 61942973: Downloading video info XML
ERROR: afreecatv said: Only users older than 19 are able to watch this video. Provide account credentials to download this content.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\afreecatv.py", line 271, in _real_extract
youtube_dl.utils.ExtractorError: afreecatv said: Only users older than 19 are able to watch this video. Provide account credentials to download this content.

## Description

WRITE DESCRIPTION HERE

Some age-restricted videos on afreecaTV would ask for an account when downloading, but an account has already been provided in the command. An afreecaTV account could be obtained by simply signing up on their site.

Example Link: http://vod.afreecatv.com/PLAYER/STATION/61942973

**Comment by artiblaster** [comment]
Still happening as of jan 24, 2021

**Comment by dmfp** [comment]
@wlritchi Thanks so much for the fix - which I have tested to work by manually compiling youtube-dl with your extractor. Would you be so kind to complete all the pull request checklist items so your fix may be accepted and merged into the codebase proper? Thanks again!
