### ISSUE TITLE
Couldn't Download. It told me to report to you.  Here it is:

### ISSUE THREAD

**Issue by abrogard** [ytdl-org/youtube-dl#26940]
S C:\youtubedl> youtube-dl --verbose https://www.patreon.com/posts/just-practicing-42940451?utm_medium=post_notification_email"&"utm_source=post_link"&"utm_campaign=patron_engagement"&"token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZWRpc19rZXkiOiJpbnN0YW50LWFjY2VzczoxM2ZlYjUyZi1jMzI1LTQ5ZTctYWUzNi00NWZiZTY4MGM5MzgifQ.MOm7IyWFjCD7MqlLWkSZzF5s7uLqQfJsoyVEj0y_xI4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.patreon.com/posts/just-practicing-42940451?utm_medium=post_notification_email&utm_source=post_link&utm_campaign=patron_engagement&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZWRpc19rZXkiOiJpbnN0YW50LWFjY2VzczoxM2ZlYjUyZi1jMzI1LTQ5ZTctYWUzNi00NWZiZTY4MGM5MzgifQ.MOm7IyWFjCD7MqlLWkSZzF5s7uLqQfJsoyVEj0y_xI4']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.1
[debug] Proxy map: {}
[Patreon] 42940451: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('post_file',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\patreon.py", line 148, in _real_extract
KeyError: 'post_file'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\patreon.py", line 148, in _real_extract
KeyError: 'post_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 545, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('post_file',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

PS C:\youtubedl>

**Comment by tameTNT** [comment]
Duplicate of #26920

**Comment by underhandedness** [comment]
You might receive more favorable attention by both editing your title to include _Patreon.com_ as netiquette expects and cleaning up the URL so others can load it in a browser.

A better title would be:  Patreon.com extractor KeyError

Must one be logged in to view the video?
