### ISSUE TITLE
Request support for site www.cinetecamilano.it

### ISSUE THREAD

**Issue by tarrasque73** [ytdl-org/youtube-dl#26944]
## Checklist

- [x ] I'm reporting a new site support request
- [x ] I've verified that I'm running youtube-dl version **2020.09.20**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that none of provided URLs violate any copyrights
- [x ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

Single video: https://www.cinetecamilano.it/film/1784

## Description

WRITE DESCRIPTION HERE

Credentials for the site can be obtained by registering.

Here's the dump.

$ youtube-dl --verbose https://www.cinetecamilano.it/film/1784
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.cinetecamilano.it/film/1784']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.7.2 (CPython) - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg N-94609-gc87237d105, ffprobe N-94609-gc87237d105
[debug] Proxy map: {}
[generic] 1784: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1784: Downloading webpage
[generic] 1784: Extracting information
ERROR: Unsupported URL: https://www.cinetecamilano.it/film/1784
Traceback (most recent call last):
  File "c:\personal\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "c:\personal\python\python37-32\lib\site-packages\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\personal\python\python37-32\lib\site-packages\youtube_dl\extractor\generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.cinetecamilano.it/film/1784

**Comment by tarrasque73** [comment]
Hi.

Is the issue still open because I missed or provided some wrong information?
