### ISSUE TITLE
ERROR: Unable to extract media id

### ISSUE THREAD

**Issue by heis2201** [ytdl-org/youtube-dl#26955]
Tying to fetch 
https://www.ardmediathek.de/ard/video/filmmittwoch-im-ersten/exit-oder-near-future-thriller/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2ZpbG1taXR0d29jaCBpbSBlcnN0ZW4vODQ4YTZjOTYtYjdhOC00ODM1LTlkMjItNmFhZjZjMzI4OGUw/

While streaming works (it may be geo-blocked for you if ISP not located in Germany), download using youtube-dl fails:

 `youtube-dl --verbose https://www.ardmediathek.de/ard/video/filmmittwoch-im-ersten/exit-oder-near-future-thriller/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2ZpbG1taXR0d29jaCBpbSBlcnN0ZW4vODQ4YTZjOTYtYjdhOC00ODM1LTlkMjItNmFhZjZjMzI4OGUw/`
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.ardmediathek.de/ard/video/filmmittwoch-im-ersten/exit-oder-near-future-thriller/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2ZpbG1taXR0d29jaCBpbSBlcnN0ZW4vODQ4YTZjOTYtYjdhOC00ODM1LTlkMjItNmFhZjZjMzI4OGUw/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Using fake IP 53.123.234.143 (DE) as X-Forwarded-For.
[ARD:mediathek] Y3JpZDovL2Rhc2Vyc3RlLmRlL2ZpbG1taXR0d29jaCBpbSBlcnN0ZW4vODQ4YTZjOTYtYjdhOC00ODM1LTlkMjItNmFhZjZjMzI4OGUw: Downloading webpage
ERROR: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpavop71lg\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpavop71lg\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpavop71lg\build\youtube_dl\extractor\ard.py", line 236, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpavop71lg\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output
```.

**Comment by heis2201** [comment]
I thought I had updated youtube-dl, but apparently I didn't. The updated version works fine for that media. Apologies for the noise!
