### ISSUE TITLE
query number+one: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',));

### ISSUE THREAD

**Issue by obifrz** [ytdl-org/youtube-dl#26961]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--user-agent', u'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0', u'--ignore-config', u'--no-cache-dir', u'--ignore-errors', u'--quiet', u'--no-warnings', u'-j', u'ytsearch50:caparezza+chi+se+ne+frega+della+musica']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-11-amd64-x86_64-with-debian-10.6
[debug] exe versions: ffmpeg 4.1.6, ffprobe 4.1.6
[debug] Proxy map: {}
ERROR: query "caparezza+chi+se+ne+frega+della+musica": Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 904, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 3014, in _real_extract
    return self._get_n_results(query, n)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 3204, in _get_n_results
    query={'spf': 'navigate'})
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 897, in _download_json
    expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 881, in _download_json_handle
    fatal=fatal), urlh
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 908, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
```

## Description

i work with option -j
since this version you won't find anything with + with ytsearch see debug

**Comment by obifrz** [comment]
two questions
1. is it because of youtube or the program?
2. does it seem to me that it is getting worse and worse?
