### ISSUE TITLE
[ADN] ERROR: Unable to extract config URL

### ISSUE THREAD

**Issue by Droid-prog** [ytdl-org/youtube-dl#26963]
C:\Windows\system32>youtube-dl --verbose https://animedigitalnetwork.fr/video/clannad/12828-episode-1-sur-la-pente-aux-cerisiers
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://animedigitalnetwork.fr/video/clannad/12828-episode-1-sur-la-pente-aux-cerisiers']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1-2020-10-01-full_build-www.gyan.dev, ffprobe 4.3.1-2020-10-01-full_build-www.gyan.dev
[debug] Proxy map: {}
[ADN] 12828: Downloading webpage
ERROR: Unable to extract config url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\adn.py", line 129, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract config url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I think they updated their player

**Comment by bgette** [comment]
Issou

**Comment by amidj** [comment]
up.
Any date or any plan to face this code rewriting please ?!?
The key method for subtitles downloading seems to be also outdated :(
Thanks a lot for your consideration. 
Take care !
