### ISSUE TITLE
ServusTV-changes

### ISSUE THREAD

**Issue by Z25forwarded** [ytdl-org/youtube-dl#26983]
## Checklist

- [X] I'm reporting a broken site support
- [X ] I've verified that I'm running youtube-dl version **2020.09.20**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -F https://www.servustv.com/videos/aa-2575dep351w12/
[Servus] AA-2575DEP351W12: Downloading webpage
[Servus] AA-2575DEP351W12: Downloading m3u8 information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[clemi@BLECHKAESTCHEN selinux]$ youtube-dl --verbose -F https://www.servustv.com/videos/aa-2575dep351w12/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-F', 'https://www.servustv.com/videos/aa-2575dep351w12/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.6.8 (CPython) - Linux-4.18.0-193.el8.x86_64-x86_64-with-centos-8.2.2004-Core
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[Servus] AA-2575DEP351W12: Downloading webpage
[Servus] AA-2575DEP351W12: Downloading m3u8 information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/clemi/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/clemi/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/clemi/.local/lib/python3.6/site-packages/youtube_dl/extractor/servus.py", line 61, in _real_extract
    self._sort_formats(formats)
  File "/home/clemi/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1359, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

WRITE DESCRIPTION HERE
Changes on the Austrian/German "ServusTV"

**Comment by LetsMelon** [comment]
Maybe look into #26967
