### ISSUE TITLE
Vimeo giving up after 10 fragment retries

### ISSUE THREAD

**Issue by TaktakTaktouk** [ytdl-org/youtube-dl#26984]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl https://vimeo.com/331404905 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://vimeo.com/331404905', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.13 (CPython) - Linux-5.3.9-x86_64-with-debian-9.13
[debug] exe versions: ffmpeg 3.2.15-0, ffprobe 3.2.15-0
[debug] Proxy map: {}
[vimeo] 331404905: Downloading webpage
[vimeo] 331404905: Extracting information
[vimeo] 331404905: Downloading JSON metadata
[vimeo] 331404905: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[vimeo] 331404905: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 331404905: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 331404905: Downloading fastly_skyfire m3u8 information
[vimeo] 331404905: Downloading fastly_skyfire m3u8 information
[vimeo] 331404905: Downloading akfire_interconnect_quic MPD information
[vimeo] 331404905: Downloading akfire_interconnect_quic MPD information
[vimeo] 331404905: Downloading fastly_skyfire MPD information
[vimeo] 331404905: Downloading fastly_skyfire MPD information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://skyfire.vimeocdn.com/1603445696-0x5083e346ed674ffa4244d27c8177d8c0c56c35e0/331404905/sep/video/1303099786,1303099787,1303099790,1303099779,1303099783/master.mpd?base64_init=1'
[dashsegments] Total fragments: 44
[download] Destination: 10 000 valandų iki tobulo margučio-331404905.fdash-fastly_skyfire_sep-video-1303099779.mp4
[download] 100% of 81.74MiB in 00:09
[debug] Invoking downloader on u'https://skyfire.vimeocdn.com/1603445696-0x5083e346ed674ffa4244d27c8177d8c0c56c35e0/331404905/sep/video/1303099786,1303099787,1303099790,1303099779,1303099783/master.mpd?base64_init=1'
[dashsegments] Total fragments: 44
[download] Destination: 10 000 valandų iki tobulo margučio-331404905.fdash-fastly_skyfire_sep-audio-1303099786.m4a
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 10 of 10)...
ERROR: giving up after 10 fragment retries
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/dash.py", line 48, in real_download
    success, frag_content = self._download_fragment(ctx, fragment_url, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/fragment.py", line 102, in _download_fragment
    'http_headers': headers or info_dict.get('http_headers'),
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 348, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 114, in establish_connection
    raise err
HTTPError: HTTP Error 404: Not Found
```

## Description

Each time I try to download a video from Vimeo I get this error. It downloads the video file but stuck with the audio file (m4a).

**Comment by dkoao** [comment]
I can confirm that this issue is affecting me as well when downloading audio fragments.

**Comment by hawk911** [comment]
Yep, youtube-dl doesn't work with audio fragments of Vimeo.

**Comment by TaktakTaktouk** [comment]
This commande helped me to baypass the issue `youtube-dl -f 'http-1080p/http-720p' URL`

**Comment by dkoao** [comment]
> This commande helped me to baypass the issue `youtube-dl -f 'http-1080p/http-720p' URL`

Does this format contain audio as well?

**Comment by TaktakTaktouk** [comment]
> > This commande helped me to baypass the issue `youtube-dl -f 'http-1080p/http-720p' URL`
> 
> Does this format contain audio as well?

Yes! it downloads one file with both video and audio

**Comment by october262** [comment]
just tried this link > https://vimeo.com/331404905
downloads ok for me.

**Comment by remitamine** [comment]
```
youtube-dl https://vimeo.com/331404905
[vimeo] 331404905: Downloading webpage
[vimeo] 331404905: Extracting information
[vimeo] 331404905: Downloading JSON metadata
[vimeo] 331404905: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[vimeo] 331404905: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 331404905: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 331404905: Downloading fastly_skyfire m3u8 information
[vimeo] 331404905: Downloading fastly_skyfire m3u8 information
[vimeo] 331404905: Downloading akfire_interconnect_quic MPD information
[vimeo] 331404905: Downloading akfire_interconnect_quic MPD information
[vimeo] 331404905: Downloading fastly_skyfire MPD information
[vimeo] 331404905: Downloading fastly_skyfire MPD information
[dashsegments] Total fragments: 44
[download] Destination: 10 000 valandų iki tobulo margučio-331404905.fdash-fastly_skyfire_sep-video-1303099779.mp4
[download] 100% of 81.74MiB in 12:21
[dashsegments] Total fragments: 44
[download] Destination: 10 000 valandų iki tobulo margučio-331404905.fdash-fastly_skyfire_sep-audio-1303099786.m4a
[download] 100% of 4.32MiB in 00:34
[ffmpeg] Merging formats into "10 000 valandų iki tobulo margučio-331404905.mp4"
Deleting original file 10 000 valandų iki tobulo margučio-331404905.fdash-fastly_skyfire_sep-video-1303099779.mp4 (pass -k to keep)
Deleting original file 10 000 valandų iki tobulo margučio-331404905.fdash-fastly_skyfire_sep-audio-1303099786.m4a (pass -k to keep)
```
