### ISSUE TITLE
[Broken] V LIVE

### ISSUE THREAD

**Issue by heismauri** [ytdl-org/youtube-dl#26999]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.11**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: ['-o', '~/Downloads/%(title)s-%(id)s.%(ext)s', '-f', '137+140']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.vlive.tv/video/151336']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.01.1
[debug] Python version 3.9.0 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[vlive] 151336: Downloading webpage
ERROR: Unable to extract video params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2020.11.1.1/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2020.11.1.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2020.11.1.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/vlive.py", line 112, in _real_extract
    params = self._search_regex(
  File "/usr/local/Cellar/youtube-dl/2020.11.1.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Hello there, I am not able to download any video from vlive, I thought that the problem was in my computer but I have tested the same thing on another computer with the same result. I tried this link `https://www.vlive.tv/video/151336` and other ones with the same result.

**Comment by remitamine** [comment]
will be fixed in the next version.
