### ISSUE TITLE
Youtube Error 400 since a few weeks ago...

### ISSUE THREAD

**Issue by White7561** [ytdl-org/youtube-dl#26992]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.11.12**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'best', u'https://www.youtube.com/watch?v=LPzKGbYVwZo']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.12
[debug] Python version 2.7.16 (CPython) - Linux-5.4.72-v7l+-armv7l-with-debian-10.6
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[youtube] LPzKGbYVwZo: Downloading webpage
[debug] Invoking downloader on u'https://r2---sn-bpb-jb3e.googlevideo.com/videoplayback?expire=1605565730&ei=waiyX_n4OpPgvwTCuavwCw&ip=182.30.125.161&id=o-AChbuIAKkoLsQlSBoXAnBGu8Gigb9UZijNeAslUS1Jwp&itag=22&source=youtube&requiressl=yes&mh=Yx&mm=31%2C29&mn=sn-bpb-jb3e%2Csn-poqvn5u-jb3k&ms=au%2Crdu&mv=m&mvi=2&pl=20&initcwndbps=596250&vprv=1&mime=video%2Fmp4&ns=I7ZbCEruXSdd2eoJrEpHVI0F&ratebypass=yes&dur=6110.005&lmt=1605542243995782&mt=1605544014&fvip=7&beids=9466586&c=WEB&txp=6416222&n=uyo9R5NgXMAfBe0it&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgFJbOHTEefgI5pfPC3NQXtikwYKlhqRMwEFELnLWDGLgCIQCskyWL5S3SWh7iNwprheq8IiYne5mwUNPNAKTuS5QTag%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgQnRGb6FIgwU9LiojY7_ORjuy6fimrTApf-RtUAH42oMCIQDPldDJIBcUyAtCRCt3hjXel1Ere0x0oNQDgM-PgcdpGw%3D%3D'
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 349, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 114, in establish_connection
    raise err
HTTPError: HTTP Error 400: Bad Request
```

## Description

So its been happening these last few weeks. i cant download any youtube videos. weird. i have tried using Python 3 and same results. tried removing the cache dir, same .. i even tried downloading and using youtube-dl in my Mac which usually works too but it doesnt. 

Sometimes, it does download just for a few seconds or so and then it shows the error like above. weird. although i tried using third party app that use youtube-dl too i presume and it works fine. so i think its a bug or something... Twitch vods works fine tho, just youtube.. even youtube livestreams are fine too.. just videos as far as im aware.

If you need any more information let me know . i'll be sure to help!!  Thanks !!

**Comment by Lirk88** [comment]
Have the same issue on version 2021.02.04.1, so it works with --cookies option.
