### ISSUE TITLE
Odnoklassniki Unable to extract player data

### ISSUE THREAD

**Issue by mantikafasiCorp** [ytdl-org/youtube-dl#27006]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PS C:\Users\Aaaaa\Desktop\test> & '.\youtube-dl (1).exe' https://odnoklassniki.ru/video/VideoID--verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://odnoklassniki.ru/video/VideoID', '--verbose']
[debug] Encodings: locale cp1254, fs mbcs, out cp857, pref cp1254
[debug] youtube-dl version 2020.11.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2020-10-21-git-289e964873-full_build-www.gyan.dev, ffprobe 2020-10-21-git-289e964873-full_build-www.gyan.dev
[debug] Proxy map: {}
[Odnoklassniki] 32507103775: Downloading webpage
ERROR: Unable to extract player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\extractor\odnoklassniki.py", line 151, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\extractor\common.py", line 1010, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by remitamine** [comment]
```
youtube-dl https://odnoklassniki.ru/video/32507103775
[Odnoklassniki] 32507103775: Downloading webpage
[Odnoklassniki] 32507103775: Downloading m3u8 information
[download] Destination: [TR] Gintama 008-32507103775.mp4
...
```
