### ISSUE TITLE
Add new site - golfpass.com Golf Channel tv shows

### ISSUE THREAD

**Issue by abarber229** [ytdl-org/youtube-dl#27017]
Are the devs for youtube-dl still supporting new links? Trying to download the season for the Big Break. Here is a link to the first episode - "https://www.golfpass.com/big-break/episode-1-make-or-break". You can create a free account to watch the videos. I didn’t have to subscribe to anything to watch the video in the link above. I’m on the latest version. Below is the code that I used:

`
    c:\YoutubeDL>youtube-dl --cookies C:/Users/user/Downloads/golfpass.com_cookies.txt -v -i -o "C:\Temp\%(uploader)s (%(uploader_id)s)/%(upload_date)s - %(title)s.%(ext)s" --prefer-ffmpeg --ffmpeg-location "C:\youtubedl\bin\ffmpeg.exe" --merge-output-format mkv --write-sub --all-subs --convert-subs srt --add-metadata --write-description --write-thumbnail "https://www.golfpass.com/big-break/episode-1-make-or-break"
    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: ['--cookies', 'C:/Users/user/Downloads/golfpass.com_cookies.txt', '-v', '-i', '-o', 'C:\\Temp\\%(uploader)s (%(uploader_id)s)/%(upload_date)s - %(title)s.%(ext)s', '--prefer-ffmpeg', '--ffmpeg-location', 'C:\\youtubedl\\bin\\ffmpeg.exe', '--merge-output-format', 'mkv', '--write-sub', '--all-subs', '--convert-subs', 'srt', '--add-metadata', '--write-description', '--write-thumbnail', 'https://www.golfpass.com/big-break/episode-1-make-or-break']
    [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
    [debug] youtube-dl version 2020.06.16.1
    [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
    [debug] exe versions: ffmpeg N-86950-g1bef008, ffprobe N-86950-g1bef008
    [debug] Proxy map: {}
    [generic] episode-1-make-or-break: Requesting header
    WARNING: Falling back on generic information extractor.
    [generic] episode-1-make-or-break: Downloading webpage
    [generic] episode-1-make-or-break: Extracting information
    ERROR: Unsupported URL: https://www.golfpass.com/big-break/episode-1-make-or-break
    Traceback (most recent call last):
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 530, in extract
      File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
    youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.golfpass.com/big-break/episode-1-make-or-break `

Thanks for taking a look and helping. Let me know if you need anything else.

**Comment by october262** [comment]
use the Firefox addon called the stream detector to easily grab the m3u8 files
just set it to youtube-dl open a terminal right click and paste to download the episodes

**Comment by abarber229** [comment]
This would be good for only one episode at a time right? Or can it do a
whole season? The main show I would like to download is "The Big Break". It
has 23 seasons with 10-11 episodes per season.

Thank you for the suggestion. I will keep it in mind.

**Comment by kennell** [comment]
Just FYI:

> You can create a free account to watch the videos.

I was able to see the video wtihout an account

**Comment by abarber229** [comment]
Hey @kennell. Thanks for the FYI. I see that you are a contributor. Do you think it would be something easy to add to youtube-dl or do you recommend another program to help download the seasons in bulk?

Thank you!
