### ISSUE TITLE
Youtube watch later broken

### ISSUE THREAD

**Issue by Jan-PieterBaert** [ytdl-org/youtube-dl#27011]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: ['--netrc']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=BedJN4Uk0qg&list=WL&index=1', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.12
[debug] Python version 3.8.6 (CPython) - Linux-5.9.8-zen1-1-zen-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: parsing .netrc: No authenticators for youtube (None, line None)
[youtube:tab] WL: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('contents')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 2982, in _real_extract
    tabs = data['contents']['twoColumnBrowseResultsRenderer']['tabs']
KeyError: 'contents'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 2982, in _real_extract
    tabs = data['contents']['twoColumnBrowseResultsRenderer']['tabs']
KeyError: 'contents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 545, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('contents')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

When putting one of my youtube watch later files into youtube-dl it fails, but when I remove everything starting from `&list=WL` it does work

**Comment by codl** [comment]
I've also run into this, as well as with videos from the queue or private playlists. I believe this is related to #27009

**Comment by Jan-PieterBaert** [comment]
Thanks for the quick solution :smiley:
