### ISSUE TITLE
Youtube: "This video is only available to Music Premium members" even when using session cookies

### ISSUE THREAD

**Issue by defvs** [ytdl-org/youtube-dl#27036]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PS E:\Music\Mixing music BUFFER\to copy> youtube-dl -x --embed-thumbnail --cookies "../cookies.txt" --download-archive "../archive.txt" --rm-cache-dir -o "Hardcore\%%(artist)s - %%(title)s.%%(ext)s" -w --audio-format mp3 "https://www.youtube.com/playlist?list=PLwTtWOam6qr0L_TEPIK7g1cn870FfXfIv" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', '--embed-thumbnail', '--cookies', '../cookies.txt', '--download-archive', '../archive.txt', '--rm-cache-dir', '-o', 'Hardcore\\%%(artist)s - %%(title)s.%%(ext)s', '-w', '--audio-format', 'mp3', 'https://www.youtube.com/playlist?list=PLwTtWOam6qr0L_TEPIK7g1cn870FfXfIv', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.11.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.3.1-2020-09-21-full_build-www.gyan.dev, ffprobe 4.3.1-2020-09-21-full_build-www.gyan.dev
[debug] Proxy map: {}
Removing cache dir C:\Users\danit/.cache\youtube-dl ..
[youtube:tab] PLwTtWOam6qr0L_TEPIK7g1cn870FfXfIv: Downloading webpage
[download] Downloading playlist: PLwTtWOam6qr0L_TEPIK7g1cn870FfXfIv
[youtube:tab] Downloading page 1
[youtube:tab] playlist PLwTtWOam6qr0L_TEPIK7g1cn870FfXfIv: Downloading 161 videos
[download] Downloading video 1 of 161
[download] You are the Miserable (Laur Remix) has already been recorded in archive
[download] Downloading video 2 of 161

(lots of downloading)

[download] Downloading video 149 of 161
[download] Call Me It. (500 Tortures) has already been recorded in archive
[download] Downloading video 150 of 161
[youtube] wW_wGyXbKak: Downloading webpage
ERROR: wW_wGyXbKak: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\extractor\youtube.py", line 1705, in _real_extract
youtube_dl.utils.ExtractorError: wW_wGyXbKak: YouTube said: Unable to extract video data

```

## Description

A few videos errors out the download, with "This video is only available to Music Premium members" even though I am using a correct cookies.txt file.
Example: wW_wGyXbKak is playable in my browser when logged in

Tried to refresh my cookies.txt; nothing new.

**Comment by defvs** [comment]
Fixed: the cookies.txt file was outdated and it didn't want to be overwritten.
