### ISSUE TITLE
Direct youtube links to 720p videos (22) extracted via youtube-dl are not played or downloaded

### ISSUE THREAD

**Issue by MegaCron** [ytdl-org/youtube-dl#27046]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.11.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
root@antiX1:~/youtube_720p_fail# youtube-dl -v -f 22 'https://www.youtube.com/watch?v=7Z3u88lBtiM'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'22', u'https://www.youtube.com/watch?v=7Z3u88lBtiM']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.17
[debug] Python version 2.7.3 (CPython) - Linux-3.7.10-antix.5-486-smp-i686-with-debian-7.2
[debug] exe versions: avconv 0.8.18-6, avprobe 0.8.18-6, ffmpeg 0.8.6-6, ffprobe 0.8.18-6
[debug] Proxy map: {}
[youtube] 7Z3u88lBtiM: Downloading webpage
[debug] Invoking downloader on u'https://r3---sn-gvnuxaxjvh-3i8l.googlevideo.com/videoplayback?expire=1605599213&ei=jSuzX8-GDImi7QTpz7i4Aw&ip=x.x.x.x&id=o-ACauvGgveKgLMcIEwQyxOCypcq21M-ITrmR-tTEg7N9y&itag=22&source=youtube&requiressl=yes&mh=1c&mm=31%2C29&mn=sn-gvnuxaxjvh-3i8l%2Csn-n8v7kn7l&ms=au%2Crdu&mv=m&mvi=3&pl=18&initcwndbps=1205000&vprv=1&mime=video%2Fmp4&ns=SwnNxTP4iM8oRz0kNcv2zX0F&ratebypass=yes&dur=1191.926&lmt=1605492656301976&mt=1605577482&fvip=18&beids=9466587&c=WEB&txp=4432432&n=cPOfFrUKe6QZwHx&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAOpMkTEK-i3nzYOTGssHwjnZouR6aJvlq8f-uRtEcpNEAiBK3_pMSmRhpJ4c8-IA6kcwhgYMeJEQvr-PlF5ok7GOTg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgb2cLtTk9Oy0OHAqW5tkpCT6qIiAweQFnAWi-nmR_GE4CIQCtuCFQrJHilNe_BRWMWHWFzR9OEE7r-tDhL0xnrL8dAw%3D%3D'
[download] Destination: 'Сегодня' - 12 ноября 2020 года. 13_00-7Z3u88lBtiM.mp4
[download]   0.1% of 130.87MiB at 45.00KiB/s ETA 49:35[download] Got server HTTP error: Downloaded 137508 bytes, expected 137225562 bytes. Retrying (attempt 1 of 10)...
[download] Destination: 'Сегодня' - 12 ноября 2020 года. 13_00-7Z3u88lBtiM.mp4
[download]   0.2% of 130.87MiB at  1.80MiB/s ETA 01:12[download] Got server HTTP error: Downloaded 333940 bytes, expected 137225562 bytes. Retrying (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 4 of 10)...
[download] Destination: 'Сегодня' - 12 ноября 2020 года. 13_00-7Z3u88lBtiM.mp4
[download]   0.4% of 130.87MiB at 70.47KiB/s ETA 31:34[download] Got server HTTP error: Downloaded 524276 bytes, expected 137225562 bytes. Retrying (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 349, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 187, in establish_connection
    raise RetryDownload(err)
RetryDownload

root@antiX1:~/youtube_720p_fail# youtube-dl -v -f 22 'https://www.youtube.com/watch?v=pjuukLUCEac'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'22', u'https://www.youtube.com/watch?v=pjuukLUCEac']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.17
[debug] Python version 2.7.3 (CPython) - Linux-3.7.10-antix.5-486-smp-i686-with-debian-7.2
[debug] exe versions: avconv 0.8.18-6, avprobe 0.8.18-6, ffmpeg 0.8.6-6, ffprobe 0.8.18-6
[debug] Proxy map: {}
[youtube] pjuukLUCEac: Downloading webpage
[debug] Invoking downloader on u'https://r3---sn-gvnuxaxjvh-3i8l.googlevideo.com/videoplayback?expire=1605599254&ei=tiuzX7naL4K-yQWSloDgDA&ip=x.x.x.x&id=o-AK-tF_rWAInpt58kLveRRzJCONWG4K5Vf1PhhClGHrRb&itag=22&source=youtube&requiressl=yes&mh=RX&mm=31%2C29&mn=sn-gvnuxaxjvh-3i8l%2Csn-n8v7znly&ms=au%2Crdu&mv=m&mvi=3&pl=18&pcm2=no&initcwndbps=1241250&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=5656.752&lmt=1605025820848506&mt=1605577607&fvip=12&c=WEB&txp=3516222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgGepP4gGatKTe8GWiGH7fmsYicf-J4ygI9omQqPtf2VkCIFMZxNNyrG43y0Hj3sSxRZZJ_rwU_e7yhLu9YbRiUpge&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgX2zHUSG7D4KWIPuEe51ICPWBZJPejbT9-VbWL2MeveUCIQCWyj35khJKd7j3llZveGErztfCpILS2WVx9ynO5jAI9w%3D%3D'
[download] Destination: 'Место встречи' - Сняли напряжение! (10.11.2020)-pjuukLUCEac.mp4
[download]   0.2% of 1.25GiB at 608.09KiB/s ETA 35:55[download] Got server HTTP error: Downloaded 2162672 bytes, expected 1344012948 bytes. Retrying (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 349, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 187, in establish_connection
    raise RetryDownload(err)
RetryDownload

```

## Description

Direct links to 720p videos (22) extracted via youtube-dl via links https://www.youtube.com/watch?v=7Z3u88lBtiM , https://www.youtube.com/watch?v=pjuukLUCEac and https://www.youtube.com/watch?v=VUtJR8qOF-U are not played via VLC or downloaded via curl or browser (with 360p everything is OK), but through the browser (via youtube web interface) 720p it is played and downloaded (via flashgot, mp4, not dash). youtube-dl also downloads part of the file with errors.

p.s. In the log, I replaced my ip in the links to x.x.x.x

**Comment by nao20010128nao** [comment]
I think it's temporary problem. Because I don't understand Russian language, but the video looks playing well.

**Comment by MegaCron** [comment]
This problem has been occurring on random 720p videos for a long time :( The video plays through the browser without any problems. Maybe the direct link is transmitted to the browser by YouTube in a different way?

**Comment by dstftw** [comment]
Server side Youtube error for format 22.

**Comment by MegaCron** [comment]
>Server side Youtube error for format 22.

But through the browser, videos from YouTube in 720p are downloaded and played. WITHOUT any errors. Direct links from the browser to 720p videos are loaded via curl without errors.

**Comment by Torvin** [comment]
I'm having the same problem. Can we please reopen this issue?

**Comment by MegaCron** [comment]
The size of the 720p '7Z3u88lBtiM' video from the browser is 112 MiB (Content-Length: 118001468) and the direct link from youtube-dl is 130 MiB (Content-Length: 137225562). These are different files (and probably sources too). Link from the browser - downloaded and played correctly, from youtube-dl - not correctly. Here are some more examples: https://www.youtube.com/watch?v=ZBMJl9J90Os https://www.youtube.com/watch?v=qcz_9-HZG3I https://www.youtube.com/watch?v=VUtJR8qOF-U

```
bash-4.4# youtube-dl -v -f 22 'https://www.youtube.com/watch?v=ZBMJl9J90Os'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'22', u'https://www.youtube.com/watch?v=ZBMJl9J90Os']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.17
[debug] Python version 2.7.14 (CPython) - Linux-3.10.65-aarch64-with-glibc2.4
[debug] exe versions: ffmpeg 3.3.2
[debug] Proxy map: {}
[youtube] ZBMJl9J90Os: Downloading webpage
[debug] Invoking downloader on u'https://r4---sn-gvnuxaxjvh-3i8l.googlevideo.com/videoplayback?expire=1605694267&ei=2560X-DmL4iBpASm0aeoCQ&ip=x.x.x.x&id=o-AGPWekWJLL_z9fDC2FYjZO1nUALr_Fz3zEw_bu_aAQO1&itag=22&source=youtube&requiressl=yes&mh=Yn&mm=31%2C29&mn=sn-gvnuxaxjvh-3i8l%2Csn-n8v7kn7k&ms=au%2Crdu&mv=m&mvi=4&pl=18&initcwndbps=1175000&vprv=1&mime=video%2Fmp4&ns=TPJca99oNnMTCkzG2za0L9IF&ratebypass=yes&dur=2127.505&lmt=1605634610900454&mt=1605672538&fvip=13&c=WEB&txp=3416222&n=uxnoVNFUdZ-kwL-&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgVo1rfe_wpwvW-In2qEmSr83AYfeYBCfijfrr1A6pzcUCIFRgLJqaOKC652tJ0g_hgRP11mroO2RiJRHsSqVGWfSr&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgJ9-G-K7HDu7TidJwNTMO73-YykV8hzFOyW3YiizrVGwCIF1DfUr01tJ_fpeqh0WauKHlNKUuHtUbM5BJTFbr0u1d'
[download] Destination: 'Сегодня' - 17 ноября 2020 года. 19_00-ZBMJl9J90Os.mp4
[download]   0.1% of 450.64MiB at 83.62KiB/s ETA 01:31:56[download] Got server HTTP error: Downloaded 244960 bytes, expected 472534522 bytes. Retrying (attempt 1 of 10)...
[download] Destination: 'Сегодня' - 17 ноября 2020 года. 19_00-ZBMJl9J90Os.mp4
[download]   0.1% of 450.64MiB at  1.64MiB/s ETA 04:35[download] Got server HTTP error: Downloaded 459272 bytes, expected 472534522 bytes. Retrying (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 3 of 10)...
[download] Destination: 'Сегодня' - 17 ноября 2020 года. 19_00-ZBMJl9J90Os.mp4
[download]   0.2% of 450.64MiB at 125.34KiB/s ETA 01:01:15[download] Got server HTTP error: Downloaded 786432 bytes, expected 472534522 bytes. Retrying (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/opt/bin/youtube-dl/youtube_dl/downloader/http.py", line 349, in real_download
    establish_connection()
  File "/opt/bin/youtube-dl/youtube_dl/downloader/http.py", line 187, in establish_connection
    raise RetryDownload(err)
RetryDownload

```
