### ISSUE TITLE
 facebook - ERROR: requested format not available

### ISSUE THREAD

**Issue by Rava77** [ytdl-org/youtube-dl#27066]
I checked https://github.com/ytdl-org/youtube-dl#faq
After updating to yt-dl V-2020.11.18 most facebook - ERROR: requested format not available have been resolved but some remain:

```/video/yt-dl-test$ youtube-dl -vF https://www.facebook.com/kalkofe/videos/kalkofes-mattscheibe-die-sch%C3%B6nen-und-die-schlauen/1122435248120630/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vF', 'https://www.facebook.com/kalkofe/videos/kalkofes-mattscheibe-die-sch%C3%B6nen-und-die-schlauen/1122435248120630/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.18
[debug] Python version 3.8.1 (CPython) - Linux-5.4.30-porteus-x86_64-Intel-R-_Core-TM-_i7_CPU_______Q_720__@_1.60GHz-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 1122435248120630: Downloading webpage
[facebook] 1122435248120630: Downloading webpage
[facebook] 1122435248120630: Downloading webpage
[info] Available formats for 1122435248120630:
format code               extension  resolution note
284967695958745a          m4a        audio only DASH audio   65k , m4a_dash container, mp4a.40.5 (48000Hz)
752674422182915v          webm       426x240    DASH video   95k , webm_dash container, vp9, video only
318399926063392v          webm       640x360    DASH video  208k , webm_dash container, vp9, video only
969946753433474v          webm       854x480    DASH video  396k , webm_dash container, vp9, video only
669781710562069v          webm       1280x720   DASH video  742k , webm_dash container, vp9, video only
3325181254243736v         webm       1920x1080  DASH video 1483k , webm_dash container, vp9, video only
dash_sd_src               mp4        unknown    
dash_sd_src_no_ratelimit  mp4        unknown    
dash_hd_src               mp4        unknown    (best)

/video/yt-dl-test$ youtube-dl -vf 694656221028751v+284967695958745a https://www.facebook.com/kalkofe/videos/kalkofes-mattscheibe-die-sch%C3%B6nen-und-die-schlauen/1122435248120630/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vf', '694656221028751v+284967695958745a', 'https://www.facebook.com/kalkofe/videos/kalkofes-mattscheibe-die-sch%C3%B6nen-und-die-schlauen/1122435248120630/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.18
[debug] Python version 3.8.1 (CPython) - Linux-5.4.30-porteus-x86_64-Intel-R-_Core-TM-_i7_CPU_______Q_720__@_1.60GHz-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 1122435248120630: Downloading webpage
[facebook] 1122435248120630: Downloading webpage
[facebook] 1122435248120630: Downloading webpage
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1635, in process_video_result
    raise ExtractorError('requested format not available',
youtube_dl.utils.ExtractorError: requested format not available```

Same error trying these formats:
1148897185487713v+284967695958745a
3105675426155345v+284967695958745a
or 634259680512477v+284967695958745a

Only the full sized version via 
```$ youtube-dl  https://www.facebook.com/kalkofe/videos/kalkofes-mattscheibe-die-sch%C3%B6nen-und-die-schlauen/1122435248120630/```
works.

**Comment by Rava77** [comment]
Editing the above is not working.

The first CLI command was missing, here it is:
```/video/yt-dl-test$ youtube-dl -vF https://www.facebook.com/kalkofe/videos/kalkofes-mattscheibe-die-sch%C3%B6nen-und-die-schlauen/1122435248120630/```

**Comment by dstftw** [comment]
No format `694656221028751v` exists for this video.
