### ISSUE TITLE
Broken site: UKTV Play

### ISSUE THREAD

**Issue by GainfulShrimp** [ytdl-org/youtube-dl#27074]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.18**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://uktvplay.uktv.co.uk/shows/bangers-and-cash/watch-online/6199143244001']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.18
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-10-amd64-x86_64-with-debian-10.6
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[generic] 6199143244001: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 6199143244001: Downloading webpage
[generic] 6199143244001: Extracting information
ERROR: Unsupported URL: https://uktvplay.uktv.co.uk/shows/bangers-and-cash/watch-online/6199143244001
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2387, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2562, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://uktvplay.uktv.co.uk/shows/bangers-and-cash/watch-online/6199143244001

```

## Description

UKTV is in the list of supported sites, but I can't get it to work.  It requires a (free) account to watch in a browser, but once signed-in, the supplied URL above works fine in a browser.

I found some old issues reporting similar problems, but I'm assuming that I'm doing something wrong given that UKTV is still in the supported sites list even for v2020.11.18?

**Comment by ufcpride** [comment]
pretty sure its not supported as they use DRM now for that site

**Comment by emdubya77** [comment]
So if the site isn't supported, shouldn't it be removed from the list of supported sites to avoid further confusion?
