### ISSUE TITLE
No video formats found

### ISSUE THREAD

**Issue by allenfengjr** [ytdl-org/youtube-dl#27073]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
Provide the complete verbose output of youtube-dl that clearly demonstrates the problem.
Add the `-v` flag to your command line you run youtube-dl with (`youtube-dl -v <your command line>`), copy the WHOLE output and insert it below. It should look similar to this:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=kTxRm9HD7lo', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.1 (CPython) - macOS-10.16-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {'http': 'http://127.0.0.1:1087', 'https': 'http://127.0.0.1:1087'}
[youtube] kTxRm9HD7lo: Downloading webpage
ERROR: kTxRm9HD7lo: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1788, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: kTxRm9HD7lo: YouTube said: Unable to extract video data

## Description

WRITE DESCRIPTION HERE
I pasted the URL to the terminal like that:

` youtube-dl -g 'https://www.youtube.com/watch?v=kTxRm9HD7lo'    `

` brew upgrade youtube-dl`

`Updating Homebrew...`

`Warning: You are using macOS 11.0.`

`We do not provide support for this released but not yet supported version.You will encounter build failures with some formulae Please create pull requests instead of asking for help on Homebrew's GitHub, Twitter or any other official channels. You are responsible for resolvingany issues you experience while you are running this released but not yet supported version.`

It is strange that I could download some videos from YouTube while others failed. For example I try to download this video but failed. I am not sure if it releated with Big Sur <br>**https://www.youtube.com/watch?v=n3L23bEJfKg**

**The full log is above**

**Comment by allenfengjr** [comment]
I finally solved a part of this problem.<br>
***DO NOT USE HOMEBREW TO UPGRADE!***<br>
I used pip3 to reinstall the youtube-dl and upgrade it, then it worked. I download the second video, but for the first video a new error appears.<br>
`ERROR: unable to download video data: HTTP Error 403: Forbidden
`

**Comment by allenfengjr** [comment]
I guess the problem is about proxy, after restart my mac and flash DNS. It worked.
