### ISSUE TITLE
Trying to download videos from Bitchute returns 'No video formats found'

### ISSUE THREAD

**Issue by Ashdemai** [ytdl-org/youtube-dl#27072]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.18**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bitchute.com/video/fPjvjOHeS44/']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2020.11.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[BitChute] fPjvjOHeS44: Downloading webpage
[BitChute] fPjvjOHeS44: Checking video URL
[BitChute] fPjvjOHeS44: video URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7fh9ngey\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7fh9ngey\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7fh9ngey\build\youtube_dl\extractor\bitchute.py", line 66, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7fh9ngey\build\youtube_dl\extractor\common.py", line 1359, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

I saw someone post on Reddit that you cannot download using youtube-dl on the site bitchute.com even though it's under the list of supported sites. I remember being able downloading a few months ago, so I figured I would try it myself and (using the latest version) it gives me the error in the title of the issue. That's it pretty much.

**Comment by Ashdemai** [comment]
I guess I found a workaround for this issue from other still open issue https://github.com/ytdl-org/youtube-dl/issues/21400#issuecomment-502925335
