### ISSUE TITLE
[VK] Trynna download an album from VK but VK sends youtube-dl to badbrowser.php

### ISSUE THREAD

**Issue by veronikazaglotova** [ytdl-org/youtube-dl#27080]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.18**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v "https://vk.com/album505128880_0" --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vk.com/album505128880_0', '--user-agent', 'Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.18
[debug] Python version 3.8.6 (CPython) - Linux-5.9.8-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[generic] album505128880_0: Requesting header
WARNING: Could not send HEAD request to https://vk.com/album505128880_0: HTTP Error 418:
[generic] album505128880_0: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] album505128880_0: Extracting information
[redirect] Following redirect to https://vk.com/badbrowser.php
[generic] badbrowser: Requesting header
WARNING: Could not send HEAD request to https://vk.com/badbrowser.php: HTTP Error 418:
[generic] badbrowser: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] badbrowser: Extracting information
ERROR: Unsupported URL: https://vk.com/badbrowser.php
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://vk.com/badbrowser.php
```

## Description

I thought that adding a user agent that my browser has would fix the issue but it doesn't.

**Comment by dstftw** [comment]
There are no videos on this page.

**Comment by veronikazaglotova** [comment]
I thought youtube-dl is for downloading things in general, no?

**Comment by dstftw** [comment]
No, only videos and accompanying data.
