### ISSUE TITLE
[YouTube] Unsupported URL when providing Search URL

### ISSUE THREAD

**Issue by strudinox** [ytdl-org/youtube-dl#27083]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.11.19**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
> youtube-dl.exe "https://www.youtube.com/results?search_query=test" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/results?search_query=test', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.11.19
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[generic] results?search_query=test: Requesting header
WARNING: Falling back on generic information extractor.
[generic] results?search_query=test: Downloading webpage
[generic] results?search_query=test: Extracting information
ERROR: Unsupported URL: https://www.youtube.com/results?search_query=test
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1_szunss\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1_szunss\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1_szunss\build\youtube_dl\extractor\generic.py", line 3381, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.youtube.com/results?search_query=test
```

## Description

When providing a search URL "https://www.youtube.com/results?search_query=test" the error above is produced.

**Comment by PerhapsSomeone** [comment]
...that's because search URLs are not a link to a video. Not to forget that the search results youtube-dl would get would be different from yours.
