### ISSUE TITLE
Youtube playlists: local variable 'playlist_id' referenced before assignment

### ISSUE THREAD

**Issue by Vrihub** [ytdl-org/youtube-dl#27094]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.11.19**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v https://www.youtube.com/watch?list=PLYPsRgFn5c4ufVj25cnV7RSYxjHLylV28
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?list=PLYPsRgFn5c4ufVj25cnV7RSYxjHLylV28']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.19
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-9-amd64-x86_64-with-debian-10.4
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] PLYPsRgFn5c4ufVj25cnV7RSYxjHLylV28: Downloading webpage
Traceback (most recent call last):
  File "/home/x/bin/youtube-dl", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/youtube.py", line 2942, in _real_extract
    return self._extract_from_tabs(item_id, webpage, data, tabs, identity_token)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/youtube.py", line 2908, in _extract_from_tabs
    playlist_id=playlist_id, playlist_title=title,
UnboundLocalError: local variable 'playlist_id' referenced before assignment
```

## Description

See the above log.

**Comment by remitamine** [comment]
invalid URL.

**Comment by Vrihub** [comment]
Ah, thanks. FYI, URLs like  `/watch?list=...` used to work in past versions of the program.
