### ISSUE TITLE
ERROR: Unable to extract title

### ISSUE THREAD

**Issue by jykhow** [ytdl-org/youtube-dl#27091]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.11.19**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\extractor\common.py", line 532,
in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\extractor\pornhub.py", line 209, in _real_extract
    webpage, 'title', group='title')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\extractor\common.py", line 1019, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\extractor\common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and
include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\test2.py", line 31, in <module>
    ydl.download([video_url])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 820, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 595, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

There is an error "Unable to extract title" when using youtubeDL to download pornhub premium video

**Comment by weisk** [comment]
😂😂😂😂 :rofl: :rofl: :rofl: :rofl: :rofl:

**Comment by huntears** [comment]
> There is an error "Unable to extract title" when using youtubeDL to download pornhub premium video

rofl this is some master move

**Comment by alessiocelentano** [comment]
> There is an error "Unable to extract title" when using youtubeDL to download pornhub premium video

"I'm gonna do what's called a pro-player move"
