### ISSUE TITLE
video unavailable even though it is played through browser(youtube)

### ISSUE THREAD

**Issue by johnlong21** [ytdl-org/youtube-dl#27107]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.19**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--embed-thumbnail', '-o', '%(title)s-%(uploader)s.%(ext)s', '-x', '-f', 'bestaudio[ext=m4a]/bestaudio[ext=opus]', '--audio-quality', '0', 'https://www.youtube.com/watch?v=era55t-z2z4', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.19
[debug] Python version 3.8.6 (CPython) - Linux-5.8.0-26-lowlatency-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] era55t-z2z4: Downloading webpage
[youtube] era55t-z2z4: Downloading embed webpage
[youtube] era55t-z2z4: Refetching age-gated info webpage
ERROR: Video unavailable
Traceback (most recent call last):
  File "/home/silver/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/silver/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/silver/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 2016, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: Video unavailable
```

## Description

i wish i had more answers to what i think may be the issue but all i get is video unavailable, even though it should not be as i can view the video fine in my browser. i thought it could be the cache which i then deleted but still does not work.

**Comment by remitamine** [comment]
[use cookie](https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl).
