### ISSUE TITLE
Trueid will not download

### ISSUE THREAD

**Issue by ualaa1** [ytdl-org/youtube-dl#27124]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.19**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v "https://cdn208.stm.trueid.net/svod_aes/ASS202007004926_m_auto.smil/playlist.m3u8?appid=trueid&type=svod&visitor=web&uid=3c4b44f461&mpass=KcgOeXt6dxb2F2HjfQDPCGzg3OLlkpyU5O6g43zt-Iww_w_DjliRHzYTzblaVHV4yikiG8ZOF1xOS_q-Nm8OzYhFRrwSHeuKI4wVDryd-DM6Ogrc9w56wc7kVBLzcelWPAo" --proxy https://125.26.238.100:8080
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://cdn208.stm.trueid.net/svod_aes/ASS202007004926_m_auto.smil/playlist.m3u8?appid=trueid&type=svod&visitor=web&uid=3c4b44f461&mpass=KcgOeXt6dxb2F2HjfQDPCGzg3OLlkpyU5O6g43zt-Iww_w_DjliRHzYTzblaVHV4yikiG8ZOF1xOS_q-Nm8OzYhFRrwSHeuKI4wVDryd-DM6Ogrc9w56wc7kVBLzcelWPAo', '--proxy', 'https://125.26.238.100:8080']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.19
[debug] Python version 3.6.4 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {'http': 'https://125.26.238.100:8080', 'https': 'https://125.26.238.100:8080'}
[generic] playlist: Requesting header
WARNING: Could not send HEAD request to https://cdn208.stm.trueid.net/svod_aes/ASS202007004926_m_auto.smil/playlist.m3u8?appid=trueid&type=svod&visitor=web&uid=3c4b44f461&mpass=KcgOeXt6dxb2F2HjfQDPCGzg3OLlkpyU5O6g43zt-Iww_w_DjliRHzYTzblaVHV4yikiG8ZOF1xOS_q-Nm8OzYhFRrwSHeuKI4wVDryd-DM6Ogrc9w56wc7kVBLzcelWPAo: <urlopen error Remote end closed connection without response>
[generic] playlist: Downloading webpage
[generic] playlist: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://cdn208.stm.trueid.net/svod_aes/ASS202007004926_m_auto.smil/chunklist_w1044415643_b3685889_vo.m3u8?ccuid=bus8o4hm7p8hl1vrcn70&appid=trueid&type=svod&visitor=web&uid=3c4b44f461&mpass=KcgOeXt6dxb2F2HjfQDPCGzg3OLlkpyU5O6g43zt-Iww_w_DjliRHzYTzblaVHV4yikiG8ZOF1xOS_q-Nm8OzYhFRrwSHeuKI4wVDryd-DM6Ogrc9w56wc7kVBLzcelWPAo'
[download] Destination: playlist-playlist.f3685.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3679.1 Safari/537.36
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-us,en;q=0.5
' -i 'https://cdn208.stm.trueid.net/svod_aes/ASS202007004926_m_auto.smil/chunklist_w1044415643_b3685889_vo.m3u8?ccuid=bus8o4hm7p8hl1vrcn70&appid=trueid&type=svod&visitor=web&uid=3c4b44f461&mpass=KcgOeXt6dxb2F2HjfQDPCGzg3OLlkpyU5O6g43zt-Iww_w_DjliRHzYTzblaVHV4yikiG8ZOF1xOS_q-Nm8OzYhFRrwSHeuKI4wVDryd-DM6Ogrc9w56wc7kVBLzcelWPAo' -c copy -f mp4 file:playlist-playlist.f3685.mp4.part
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[tcp @ 0x7fd445f044c0] Starting connection attempt to 171.102.7.208 port 443
[tcp @ 0x7fd445f044c0] Connection attempt to 171.102.7.208 port 443 failed: Operation timed out
[tcp @ 0x7fd445f044c0] Connection to tcp://cdn208.stm.trueid.net:443 failed: Operation timed out
https://cdn208.stm.trueid.net/svod_aes/ASS202007004926_m_auto.smil/chunklist_w1044415643_b3685889_vo.m3u8?ccuid=bus8o4hm7p8hl1vrcn70&appid=trueid&type=svod&visitor=web&uid=3c4b44f461&mpass=KcgOeXt6dxb2F2HjfQDPCGzg3OLlkpyU5O6g43zt-Iww_w_DjliRHzYTzblaVHV4yikiG8ZOF1xOS_q-Nm8OzYhFRrwSHeuKI4wVDryd-DM6Ogrc9w56wc7kVBLzcelWPAo: Operation timed out


ERROR: ffmpeg exited with code 1
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/youtube-dl", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
    self.process_info(new_info)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/downloader/external.py", line 64, in real_download
    self.get_basename(), retval))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/downloader/common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 587, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

## Description

Trying to download stuff on Trueid. It always times out for some reason. Maybe because I'm using a proxy?
Sample link that I used: https://movie.trueid.net/series/vg7jWEqrZvkM/0ewYZNwZ4dxX

**Comment by ualaa1** [comment]
Trying again with native hls:
youtube-dl -v "https://cdn206.stm.trueid.net/svod_aes/ASS202007004926_m_auto.smil/playlist.m3u8?appid=trueid&type=svod&visitor=web&uid=86d3a87916&mpass=6nbusBYee6CTLICMhDtU7abAvSstT7VUxny3B3NaPgolFHCqLSEK474vRHEcCF6g_JzCGm2PhRC88z4mYbITOwN0PzJAt9cqPtP3RGF446k6OqXosd4h3Bi6Au1FMCfyrVk" --proxy http://183.89.152.55:8080 --hls-prefer-native
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://cdn206.stm.trueid.net/svod_aes/ASS202007004926_m_auto.smil/playlist.m3u8?appid=trueid&type=svod&visitor=web&uid=86d3a87916&mpass=6nbusBYee6CTLICMhDtU7abAvSstT7VUxny3B3NaPgolFHCqLSEK474vRHEcCF6g_JzCGm2PhRC88z4mYbITOwN0PzJAt9cqPtP3RGF446k6OqXosd4h3Bi6Au1FMCfyrVk', '--proxy', 'http://183.89.152.55:8080', '--hls-prefer-native']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.19
[debug] Python version 3.6.4 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://183.89.152.55:8080', 'https': 'http://183.89.152.55:8080'}
[generic] playlist: Requesting header
[generic] playlist: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://cdn206.stm.trueid.net/svod_aes/ASS202007004926_m_auto.smil/chunklist_w1722009064_b3685889_vo.m3u8?ccuid=buu1svu1ndc0jcvro2jg&appid=trueid&type=svod&visitor=web&uid=86d3a87916&mpass=6nbusBYee6CTLICMhDtU7abAvSstT7VUxny3B3NaPgolFHCqLSEK474vRHEcCF6g_JzCGm2PhRC88z4mYbITOwN0PzJAt9cqPtP3RGF446k6OqXosd4h3Bi6Au1FMCfyrVk'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 70
[download] Destination: playlist-playlist.f3685.mp4
[download]   1.4% of ~224.45MiB at Unknown speed ETA Unknown ETATraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/youtube-dl", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
    self.process_info(new_info)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/downloader/hls.py", line 174, in real_download
    decrypt_info['KEY'], AES.MODE_CBC, iv).decrypt(frag_content)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Crypto/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Crypto/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Crypto/Cipher/AES.py", line 93, in _create_base_cipher
    raise ValueError("Incorrect AES key length (%d bytes)" % len(key))
ValueError: Incorrect AES key length (0 bytes)
