### ISSUE TITLE
Bug sound download from youtube video

### ISSUE THREAD

**Issue by axel578** [ytdl-org/youtube-dl#27170]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.11.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v --extract-audio --audio-format mp3 -o myvideoaudio.mp3   https://www.youtube.com/watch?v=qvUWA45GOMg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--extract-audio', '--audio-format', 'mp3', '-o', 'myvideoaudio.mp3', 'https://www.youtube.com/watch?v=qvUWA45GOMg']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.11.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.3.1-2020-10-01-full_build-www.gyan.dev, ffprobe 4.3.1-2020-10-01-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] qvUWA45GOMg: Downloading webpage
[youtube] {18} signature length 107, html5 player a3726513
[youtube] {137} signature length 107, html5 player a3726513
[youtube] {248} signature length 107, html5 player a3726513
[youtube] {399} signature length 107, html5 player a3726513
[youtube] {136} signature length 103, html5 player a3726513
[youtube] {247} signature length 107, html5 player a3726513
[youtube] {398} signature length 107, html5 player a3726513
[youtube] {135} signature length 107, html5 player a3726513
[youtube] {244} signature length 107, html5 player a3726513
[youtube] {397} signature length 107, html5 player a3726513
[youtube] {134} signature length 107, html5 player a3726513
[youtube] {243} signature length 107, html5 player a3726513
[youtube] {396} signature length 107, html5 player a3726513
[youtube] {133} signature length 107, html5 player a3726513
[youtube] {242} signature length 107, html5 player a3726513
[youtube] {395} signature length 107, html5 player a3726513
[youtube] {160} signature length 103, html5 player a3726513
[youtube] {278} signature length 107, html5 player a3726513
[youtube] {394} signature length 107, html5 player a3726513
[youtube] {140} signature length 107, html5 player a3726513
[youtube] {249} signature length 107, html5 player a3726513
[youtube] {250} signature length 107, html5 player a3726513
[youtube] {251} signature length 107, html5 player a3726513
[debug] Invoking downloader on 'https://r4---sn-4gxx-hgns.googlevideo.com/videoplayback?expire=1606189605&ei=xS28X7W4NMPaW-fzvpgH&ip=82.244.21.87&id=o-ABvB2n95DMf9VNcDXPYN4YAKhguMa0SifxkFrB1fE8sQ&itag=251&source=youtube&requiressl=yes&mh=QU&mm=31%2C29&mn=sn-4gxx-hgns%2Csn-4gxx-25gee&ms=au%2Crdu&mv=m&mvi=4&pl=22&nh=%2CEAE&initcwndbps=938750&vprv=1&mime=audio%2Fwebm&ns=OT6DJXIR-afAo4XqcUwbx5IF&gir=yes&clen=90354813&dur=5175.101&lmt=1603573267027731&mt=1606167639&fvip=4&keepalive=yes&c=WEB&txp=5431432&n=svMmEaP9Hrk7bO3&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cnh%2Cinitcwndbps&lsig=AG3C_xAwRQIgR6jEwov7ADr3NPlUDqkhrKwQxZVYuptM_yH9i0SQxn0CIQCrqBoQAkT9m-5y4QajNQpI41Oqd-J652PD9tOZL9Z8iA%3D%3D&sig=AOq0QJ8wRQIhAI0Og2qOA7tPd3uu_BPCUSAR2kiegR6LPUx-qPuar0VcAiApbdisYcUjWygR0vGmDofhU2sotg3qBhFrZ9IlEon11w==&ratebypass=yes'
ERROR: unable to download video data: <urlopen error [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu>
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1279, in connect
  File "C:\Python\Python34\lib\http\client.py", line 871, in connect
  File "C:\Python\Python34\lib\socket.py", line 516, in create_connection
  File "C:\Python\Python34\lib\socket.py", line 507, in create_connection
TimeoutError: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxu6cdb_m\build\youtube_dl\YoutubeDL.py", line 1936, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxu6cdb_m\build\youtube_dl\YoutubeDL.py", line 1875, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxu6cdb_m\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxu6cdb_m\build\youtube_dl\downloader\http.py", line 351, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxu6cdb_m\build\youtube_dl\downloader\http.py", line 116, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxu6cdb_m\build\youtube_dl\downloader\http.py", line 110, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxu6cdb_m\build\youtube_dl\YoutubeDL.py", line 2248, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxu6cdb_m\build\youtube_dl\utils.py", line 2736, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu>
```

## Description

WRITE DESCRIPTION HERE

On the latest version of youtube dl : youtube-dl 2020.11.24

the following command does not work at all :
```
youtube-dl --extract-audio --audio-format mp3 -o myvideoaudio.mp3   https://www.youtube.com/watch?v=LO9vChXMBp8
```
I expected it to download the audio, but it just shut down itself

**Comment by dstftw** [comment]
Network issue on your side. You may try selecting different format with `-f`.
```
> py -3.7 .\youtube_dl\__main__.py qvUWA45GOMg -f 251
[youtube] qvUWA45GOMg: Downloading webpage
[download] Destination: Chill Lo-fi Hip-Hop Beats FREE _ Lofi Hip Hop Chillhop Music Mix _ GEMN-qvUWA45GOMg.webm
[download] 100% of 86.17MiB in 00:08
```
```
