### ISSUE TITLE
Fox.com not downloading

### ISSUE THREAD

**Issue by jriker1** [ytdl-org/youtube-dl#27173]
When I try to convert a video from Fox.com I get the below error. as you can see from my call I am passing the Comcast login info as I do with other networks.

C:\Users\jriker\source\repos\ShowWebsiteDownloader\ShowWebsiteDownloader\bin\Debug>youtube-dlc --audio-quality 0 --add-metadata --ap-mso Comcast_SSO --ap-username jriker --ap-password PASSWORD https://www.fox.com/watch/fac8008934fc490dc6e29fef9d22f965 -o "The Masked Singer S4E8.mp4" -v

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--audio-quality', '0', '--add-metadata', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.fox.com/watch/fac8008934fc490dc6e29fef9d22f965', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.11.01.1
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-10-01-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[FOX] Downloading JSON metadata
[FOX] fac8008934fc490dc6e29fef9d22f965: Downloading JSON metadata
ERROR: This video is only available via cable service provider subscription. You may want to use --cookies.
Traceback (most recent call last):
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\fox.py", line 65, in _call_api
    return self._download_json(
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 893, in _download_json
    res = self._download_json_handle(
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 872, in _download_json_handle
    res = self._download_webpage_handle(
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\adobepass.py", line 1336, in _download_webpage_handle
    return super(AdobePassIE, self)._download_webpage_handle(
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 665, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 650, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\fox.py", line 65, in _call_api
    return self._download_json(
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 893, in _download_json
    res = self._download_json_handle(
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 872, in _download_json_handle
    res = self._download_webpage_handle(
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\adobepass.py", line 1336, in _download_webpage_handle
    return super(AdobePassIE, self)._download_webpage_handle(
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 665, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 650, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\fox.py", line 96, in _real_extract
    video = self._call_api('vodplayer/' + video_id, video_id)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\fox.py", line 74, in _call_api
    raise ExtractorError(
youtube_dl.utils.ExtractorError: This video is only available via cable service provider subscription. You may want to use --cookies.

Using 11/11/2020 version on Windows

**Comment by october262** [comment]
retry this link - https://www.fox.com/watch/fac8008934fc490dc6e29fef9d22f965
with the Firefox addon called the stream detector it does grab the m3u8 files.
just set it to youtube-dl or youtube-dlc and just right click and paste into a terminal.

**Comment by jriker1** [comment]
Not sure if I can write here since it was closed but not fully getting what you wrote.  I point to that link with youtube-dl or dlc and get the above error.  Not sure what "out of scope" means.  Are you saying I shouldn't be using the SSO piece as that doesn't work:

youtube-dl https://www.fox.com/watch/fac8008934fc490dc6e29fef9d22f965
[FOX] Downloading JSON metadata
[FOX] fac8008934fc490dc6e29fef9d22f965: Downloading JSON metadata
ERROR: This video is only available via cable service provider subscription. You may want to use --cookies.

**Comment by remitamine** [comment]
this issue tracker is an issue tracker for youtube-dl, report the issue to the relevant fork you're using.

**Comment by jriker1** [comment]
I'm using both but this and youtube-dlc, both same deal.
