### ISSUE TITLE
steampowered.com (Steam game store) dose not work anymore...

### ISSUE THREAD

**Issue by warichnict** [ytdl-org/youtube-dl#27190]
## Description

hi, it lookes like ytdl dose not download videos from steampowered.com dose not work anymore, probably they kissed flash goodby and you dont grab html5 videos yet
thanks for fixing it in advance

## Verbose log

````
/tmp $ 
/tmp $ youtube-dl -U 
youtube-dl is up-to-date (2020.11.24)
/tmp $ youtube-dl --verbose https://store.steampowered.com/app/1067850/Kindergarten_2/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://store.steampowered.com/app/1067850/Kindergarten_2/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.24
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-8-amd64-x86_64-with-debian-10.3
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, phantomjs 5, rtmpdump 2.4
[debug] Proxy map: {}
[Steam] 1067850: Downloading webpage
ERROR: Unable to extract flash vars; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/treaki/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/home/treaki/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/steam.py", line 90, in _real_extract
    'flash vars'), playlist_id, js_to_json)
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract flash vars; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

/tmp $   

````

_edit: removed newline that broke url in command which probably happened do to terminal resize_

**Comment by remitamine** [comment]
do not post duplicates.
