### ISSUE TITLE
No video formats found

### ISSUE THREAD

**Issue by shreetechnical1** [ytdl-org/youtube-dl#27196]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.11.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--sleep-interval', '250', 'https://app.pluralsight.com/library/courses/angular-nodejs-restful-services/table-of-contents', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.11.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] angular-nodejs-restful-services: Downloading JSON metadata
[download] Downloading playlist: Integrating Angular with Node.js RESTful Services
[pluralsight:course] playlist Integrating Angular with Node.js RESTful Services: Collected 52 video ids (downloading 52 of them)
[download] Downloading video 1 of 52
[pluralsight] Downloading login page
[pluralsight] Logging in
[pluralsight] angular-nodejs-restful-services-m0-0: Downloading JSON metadata
[pluralsight] angular-nodejs-restful-services-m0-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] angular-nodejs-restful-services-m0-0: Downloading mp4-high-widescreen viewclip JSON
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] angular-nodejs-restful-services-m0-0: Waiting for 3 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\extractor\pluralsight.py", line 421, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\extractor\common.py", line 1359, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Getting error from pluralsight - No video formats found

**Comment by shreetechnical1** [comment]
do you have the solution link from original issue? pls share. I got this error from latest version too.
