### ISSUE TITLE
[YouTube] Unable to download alive and playable video - HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by fosam** [ytdl-org/youtube-dl#27200]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\user>youtube-dl --verbose https://www.youtube.com/watch?v=SmGUAoJ-XAM
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=SmGUAoJ-XAM']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.11.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2020-11-25-git-3de3d2f5e2, ffprobe 2020-11-25-git-3de3d2f5e2
[debug] Proxy map: {}
[youtube] SmGUAoJ-XAM: Downloading webpage
[youtube] SmGUAoJ-XAM: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r4---sn-uxaxovg-vnae7.googlevideo.com/videoplayback?expire=1606378874&ei=GhG_X6SwKsG67ATtrqpQ&ip=82.164.193.144&id=o-AAOslEIR_zmYmIJ_QiZZSIjxoSp6_uIusTE4xGbl0iS1&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=yt_otf&requiressl=yes&mh=8P&mm=31%2C29&mn=sn-uxaxovg-vnae7%2Csn-5goeen7d&ms=au%2Crdu&mv=m&mvi=4&pcm2cms=yes&pl=16&initcwndbps=1648750&vprv=1&mime=video%2Fwebm&ns=aHZenQVnnOxMxcHgFvsXy-gF&otf=1&otfp=1&dur=879.111&lmt=1489552536986074&mt=1606357005&fvip=4&keepalive=yes&c=WEB&n=zWvngvvEmFe3JNo8q2Z&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cotf%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAJkxXYJeuyFESEzx_styYCUa_cMFJjzoXTYu88mON8wJAiBisZwIBf6AioXZZPe1C3c7ASdlqOhOottHSFtCbHdzIg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOUAMIpTNHoqGlLxBXUOf85Vpl5I4RZ8C1J_-YJjZzovAiEA85sfCHmvhS7H-tOm8wHQX5_Oc2crN46WbrkrPd9juWI%3D&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\YoutubeDL.py", line 1930, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\YoutubeDL.py", line 1875, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\downloader\http.py", line 351, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\downloader\http.py", line 116, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\downloader\http.py", line 110, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\YoutubeDL.py", line 2248, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found


C:\Users\user>
```

## Description

Video is alive and playable on the browser but youtube-dl gives: `ERROR: unable to download video data: HTTP Error 404: Not Found`
[Here is the video](https://www.youtube.com/watch?v=SmGUAoJ-XAM)

**Comment by october262** [comment]
try youtube-dl https://www.youtube.com/watch?v=SmGUAoJ-XAM -f 22

**Comment by fosam** [comment]
> try youtube-dl https://www.youtube.com/watch?v=SmGUAoJ-XAM -f 22

Works, but only 720p not sure why?

How can i proceed with this if i want to download a channel? (i always go for the default quality which is best+best)

**Comment by october262** [comment]
> > try youtube-dl https://www.youtube.com/watch?v=SmGUAoJ-XAM -f 22
> 
> Works, but only 720p not sure why?
> 
> How can i proceed with this if i want to download a channel? (i always go for the default quality which is best+best)

you can you youtube-dl https://www.youtube.com/watch?v=SmGUAoJ-XAM  -F
to see available formats for the video

**Comment by fosam** [comment]
But i'm downloading the whole channel

**Comment by dstftw** [comment]
webm formats for this video are not available at Youtube side.

**Comment by fosam** [comment]
@dstftw is it possibe to skip to the next best format? when downloading a channel this causes the download to stop if, you use `--skip-errors` the video will not be downloaded.

**Comment by xexiyong** [comment]
> > > try youtube-dl https://www.youtube.com/watch?v=SmGUAoJ-XAM -f 22
> > 
> > 
> > Works, but only 720p not sure why?
> > How can i proceed with this if i want to download a channel? (i always go for the default quality which is best+best)
> 
> you can you youtube-dl https://www.youtube.com/watch?v=SmGUAoJ-XAM -F to see available formats for the video

after the -F option, could change another format, it may be works!
