### ISSUE TITLE
Error while downloading pluralsight video - No video formats found (youtube-dl version 2020.11.26)

### ISSUE THREAD

**Issue by shreetechnical1** [ytdl-org/youtube-dl#27201]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.11.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--sleep-interval', '250', 'https://app.pluralsight.com/library/courses/angular-nodejs-restful-services/table-of-contents', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.11.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] angular-nodejs-restful-services: Downloading JSON metadata
[download] Downloading playlist: Integrating Angular with Node.js RESTful Services
[pluralsight:course] playlist Integrating Angular with Node.js RESTful Services: Collected 52 video ids (downloading 52 of them)
[download] Downloading video 1 of 52
[pluralsight] Downloading login page
[pluralsight] Logging in
[pluralsight] angular-nodejs-restful-services-m0-0: Downloading JSON metadata
[pluralsight] angular-nodejs-restful-services-m0-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] angular-nodejs-restful-services-m0-0: Downloading mp4-high-widescreen viewclip JSON
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] angular-nodejs-restful-services-m0-0: Waiting for 3 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\extractor\pluralsight.py", line 421, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\extractor\common.py", line 1359, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Getting the error while downloading videos from Pluralsight. Error : No video formats found;

youtube-dl version used is 2020.11.26

OS: Windows 10

**Comment by dkocich** [comment]
I get this err from youtube

```
❯ youtube-dl https://www.youtube.com/watch?v=BDCU5OFXZ2c
[youtube] BDCU5OFXZ2c: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
❯ youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-54-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]
```

**Comment by remitamine** [comment]
> I've searched the bugtracker for similar bug reports including closed ones

**Comment by shreetechnical1** [comment]
@remitamine is there a fix available for this issue? it happened in the latest version. (2020.11.26)
It looks like pluralsight schema changed!

**Comment by remitamine** [comment]
> is there a fix available for this issue?
no.

**Comment by lexusprime** [comment]
Can you please give us a reference to the issue which this issue is duplicate to, so that we can track that. 

Moreover, I have some insights that I want to share. For example, if I change the IP then the error goes away. And suddenly it finds the video format.

**Comment by unboundthoughts** [comment]
@remitamine do you have a probably fix date or release for this please?

**Comment by remitamine** [comment]
> do you have a probably fix date or release for this please?

no, there isn't, and i'm not working on it.

**Comment by blueray453** [comment]
Please check video 10 (Dream Big: 10x the Solution) & 11 (Staying True to the Task) from

https://app.pluralsight.com/library/courses/using-your-tech-skills-times-crisis

```
% youtube-dl --verbose --playlist-start 10
[debug] System config: ['--abort-on-error', '--no-warnings', '--console-title', '--batch-file=batch-file.txt', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36', '--cookies', '/media/blueray/Documents/cookies.txt', '--retries', '10', '--continue', '--fragment-retries', '10', '--min-sleep-interval', '120', '--max-sleep-interval', '240', '-f', 'best[height<=720]/worst[height>720]', '-o', '%(playlist_title)s/%(chapter_number)s - %(chapter)s/%(playlist_index)d-%(title)s.%(ext)s']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--playlist-start', '10']
[debug] Batch file urls: ['https://app.pluralsight.com/library/courses/using-your-tech-skills-times-crisis']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.8.5 (CPython) - Windows-10-10.0.17134
[debug] exe versions: avconv 11.3, avprobe 11.3
[debug] Proxy map: {}
[pluralsight:course] using-your-tech-skills-times-crisis: Downloading JSON metadata
[download] Downloading playlist: Using Your Tech Skills in Times of Crisis
[pluralsight:course] playlist Using Your Tech Skills in Times of Crisis: Collected 12 video ids (downloading 3 of them)
[download] Downloading video 1 of 3
[pluralsight] 3e1244c2-9c82-4ea2-adcb-12101f56e601-0: Downloading JSON metadata
[pluralsight] 3e1244c2-9c82-4ea2-adcb-12101f56e601-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] 3e1244c2-9c82-4ea2-adcb-12101f56e601-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] 3e1244c2-9c82-4ea2-adcb-12101f56e601-0: Waiting for 2 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

% youtube-dl --verbose --playlist-start 11
[debug] System config: ['--abort-on-error', '--no-warnings', '--console-title', '--batch-file=batch-file.txt', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36', '--cookies', '/media/blueray/Documents/cookies.txt', '--retries', '10', '--continue', '--fragment-retries', '10', '--min-sleep-interval', '120', '--max-sleep-interval', '240', '-f', 'best[height<=720]/worst[height>720]', '-o', '%(playlist_title)s/%(chapter_number)s - %(chapter)s/%(playlist_index)d-%(title)s.%(ext)s']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--playlist-start', '11']
[debug] Batch file urls: ['https://app.pluralsight.com/library/courses/using-your-tech-skills-times-crisis']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.8.5 (CPython) - Windows-10-10.0.17134
[debug] exe versions: avconv 11.3, avprobe 11.3
[debug] Proxy map: {}
[pluralsight:course] using-your-tech-skills-times-crisis: Downloading JSON metadata
[download] Downloading playlist: Using Your Tech Skills in Times of Crisis
[pluralsight:course] playlist Using Your Tech Skills in Times of Crisis: Collected 12 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[pluralsight] 3e1244c2-9c82-4ea2-adcb-12101f56e601-1: Downloading JSON metadata
[pluralsight] 3e1244c2-9c82-4ea2-adcb-12101f56e601-1: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] 3e1244c2-9c82-4ea2-adcb-12101f56e601-1: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] 3e1244c2-9c82-4ea2-adcb-12101f56e601-1: Waiting for 3 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
