### ISSUE TITLE
ERROR: No video formats found;

### ISSUE THREAD

**Issue by arsanysamuel** [ytdl-org/youtube-dl#27228]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.11.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.linkedin.com/learning/cert-prep-certified-solidworks-professional-3/certification-exam-software-settings', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.26
[debug] Python version 3.8.6 (CPython) - Linux-5.9.10-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[linkedin:learning] Downloading login page
[linkedin:learning] Logging in
[linkedin:learning] certification-exam-software-settings: Downloading 360p JSON metadata
[linkedin:learning] certification-exam-software-settings: Downloading 540p JSON metadata
[linkedin:learning] certification-exam-software-settings: Downloading 720p JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/admonz/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/home/admonz/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/home/admonz/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/admonz/.local/lib/python3.8/site-packages/youtube_dl/extractor/linkedin.py", line 127, in _real_extract
    self._sort_formats(formats, ('width', 'height', 'source_preference', 'tbr', 'abr'))
  File "/home/admonz/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1359, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

I'm trying to download videos from linkedin learning, I started by downloading the first two videos and it worked well but this error started to occur on the third video.

Here is the link to one of the successfully downloaded videos:
https://www.linkedin.com/learning/cert-prep-certified-solidworks-professional-3/how-to-use-the-exercise-files

I tried to play all videos on the browser and everything works well.
Thanks in advance.

**Comment by arsanysamuel** [comment]
I found the solution in [this](https://github.com/ytdl-org/youtube-dl/issues/20326?fbclid=IwAR0QBHSTkB2PcPXAMhsQM7Y4yY-dIGedkXeNjh_SVFO5XPmcCvIyRtr0Eh4#issuecomment-586537418) comment, sorry I didn't do enough search, thanks for closing.
