### ISSUE TITLE
[AZMedien] Downloading JSON metadata: An extractor error has occurred

### ISSUE THREAD

**Issue by Foensi10** [ytdl-org/youtube-dl#27245]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.11.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.telezueri.ch/zuerinews/unfall-in-henau-sg-autofahrerin-hatte-grosses-glueck-140031937', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.11.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[AZMedien] unfall-in-henau-sg-autofahrerin-hatte-grosses-glueck-140031937: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('data',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\extractor\azmedien.py", line 62, in _real_extract
KeyError: 'data'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\extractor\azmedien.py", line 62, in _real_extract
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\extractor\common.py", line 545, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('data',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

The following Video is not abe to download: https://www.telezueri.ch/zuerinews/unfall-in-henau-sg-autofahrerin-hatte-grosses-glueck-140031937

**Comment by october262** [comment]
try youtube-dl --force-generic-extractor https://www.telezueri.ch/zuerinews/unfall-in-henau-sg-autofahrerin-hatte-grosses-glueck-140031937

**Comment by remitamine** [comment]
```
youtube-dl https://www.telezueri.ch/zuerinews/unfall-in-henau-sg-autofahrerin-hatte-grosses-glueck-140031937
[AZMedien] unfall-in-henau-sg-autofahrerin-hatte-grosses-glueck-140031937: Downloading JSON metadata
[Kaltura] 1_ybw4lkrn: Downloading video info JSON
[Kaltura] 1_ybw4lkrn: Downloading m3u8 information
[download] Destination: Unfall in Henau (SG) - Autofahrerin hatte grosses Glück-1_ybw4lkrn.mp4
```
