### ISSUE TITLE
Youtube age-gated link fails even with cookies

### ISSUE THREAD

**Issue by someziggyman** [ytdl-org/youtube-dl#27259]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.11.29**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
**Python 2.7 log**
youtube-dl -v --cookies /Users/username/Downloads/cookies.txt -F https://www.youtube.com/watch?v=XgnwCQzjau8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--cookies', u'/Users/username/Downloads/cookies.txt', u'-F', u'https://www.youtube.com/watch?v=XgnwCQzjau8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.29
[debug] Python version 2.7.16 (CPython) - Darwin-20.1.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] XgnwCQzjau8: Downloading webpage
[youtube] XgnwCQzjau8: Downloading embed webpage
[youtube] XgnwCQzjau8: Refetching age-gated info webpage
ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 2053, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

**Python 3.9 log**
python3 ./youtube-dl -v --cookies /Users/username/Downloads/cookies.txt -F https://www.youtube.com/watch?v=XgnwCQzjau8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', '/Users/username/Downloads/cookies.txt', '-F', 'https://www.youtube.com/watch?v=XgnwCQzjau8']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.29
[debug] Python version 3.9.0 (CPython) - macOS-10.16-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] XgnwCQzjau8: Downloading webpage
[youtube] XgnwCQzjau8: Downloading embed webpage
[youtube] XgnwCQzjau8: Refetching age-gated info webpage
ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.
Traceback (most recent call last):
  File "/Users/sy/Downloads/youtube-dl-master/./youtube-dl/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/sy/Downloads/youtube-dl-master/./youtube-dl/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/sy/Downloads/youtube-dl-master/./youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/Users/sy/Downloads/youtube-dl-master/./youtube-dl/youtube_dl/extractor/youtube.py", line 2053, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.


```

## Description

Test link:
https://www.youtube.com/watch?v=XgnwCQzjau8

With and without cookies, no matter what Python version it is the output is always the same - ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.
Two log for each python version above.

Is this a bug that can be fixed or am I doing something wrong?

**Comment by october262** [comment]
youtube-dl will work on some age gated videos, however ones like this link - https://www.youtube.com/watch?v=XgnwCQzjau8
will work youtube-dlc with cookies and being signed into youtube.
