### ISSUE TITLE
youtube-dl does not download music playlist from VK. I tried to use double quotes and change the user agent

### ISSUE THREAD

**Issue by cpuuntery** [ytdl-org/youtube-dl#27262]
## Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running youtube-dl version **2020.11.29**
- [X] I've searched the bugtracker for similar site feature requests including closed ones

## Description

First, I want to say that I'm a computer science student. And I know how hard programming can be. And some time the websites change their behaviour. That causes youtube-dl to stop working on the specific website. Then someone has to analyse the behaviour of the website. So thanks to the maintainer and everyone who contributed to the youtube-dl project. And because youtube-dl is a very popular project. Sometime people create duplicate issue without using the search bar. For example, there are three issues about youtube-dl not working in ubuntu 20.04 because of the removal of python 2. I noticed that  vk.py is last updated in 2016, so I believe it needs and deserve an update. And I believe it was only created to download videos not for music playlist when I looked at the code.  Here is the error that I am getting.
```
youtube-dl.exe -v -F "https://vk.com/music/playlist/-71195928_1142" --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
[debug] System config: []
[debug] User config: ['--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://vk.com/music/playlist/-71195928_1142', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36']
[debug] Encodings: locale cp1256, fs mbcs, out cp720, pref cp1256
[debug] youtube-dl version 2020.11.29
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[generic] -71195928_1142: Requesting header
WARNING: Could not send HEAD request to https://vk.com/music/playlist/-71195928_1142: HTTP Error 418:
[generic] -71195928_1142: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] -71195928_1142: Extracting information
[redirect] Following redirect to https://vk.com/badbrowser.php
[generic] badbrowser: Requesting header
WARNING: Could not send HEAD request to https://vk.com/badbrowser.php: HTTP Error 418:
[generic] badbrowser: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] badbrowser: Extracting information
ERROR: Unsupported URL: https://vk.com/badbrowser.php
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpc5iwv3dp\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpc5iwv3dp\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpc5iwv3dp\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpc5iwv3dp\build\youtube_dl\extractor\generic.py", line 3381, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://vk.com/badbrowser.php
```

**Comment by CubeBag** [comment]
This isn't fixed yet

**Comment by jhipster122** [comment]
Any news about this issue?

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/8389

**Comment by Ultrafeel** [comment]
https://www.downthemall.org/ plugin can actually download video from m.vk.com counterpart.

**Comment by beguy** [comment]
Cause vk change url signature to
`https://vk.com/video/playlist/-111905078_115`
from old format
`https://vk.com/videos-111905078?section=album_115`.

Just modify your url to old format.
