### ISSUE TITLE
Can't update for no apparent reason

### ISSUE THREAD

**Issue by stemy2** [ytdl-org/youtube-dl#27289]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
stem@debian:~$ youtube-dl https://www.youtube.com/watch?v=N8NcQzMQN_U -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=N8NcQzMQN_U', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.30
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-12-amd64-x86_64-with-debian-10.6
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] N8NcQzMQN_U: Downloading webpage
[youtube] N8NcQzMQN_U: Downloading video info webpage
ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/stem/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/stem/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/stem/.local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 2100, in _real_extract
    raise ExtractorError('no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info')
youtube_dl.utils.ExtractorError: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Hello,

As you can see in the log, the version seems outdated. But i don't understand why since i used the pip installation method and the command `sudo -H pip install --upgrade youtube-dl` says `Requirement already up-to-date: youtube-dl in /usr/local/lib/python2.7/dist-packages (2020.12.2) `. What did i do wrong ?

**Comment by remitamine** [comment]
you have multiple versions installed.
