### ISSUE TITLE
TubiTV inconsistent download failures

### ISSUE THREAD

**Issue by TheGrimKeeper** [ytdl-org/youtube-dl#27288]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v https://tubitv.com/movies/556428/mixed-nuts
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://tubitv.com/movies/556428/mixed-nuts']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.02
[debug] Python version 3.8.5 (CPython) - Linux-5.8.0-7630-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[debug] Using fake IP 6.198.104.59 (US) as X-Forwarded-For.
[TubiTv] 556428: Downloading JSON metadata
[TubiTv] 556428: Downloading m3u8 information
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2028, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in wrapper
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 824, in __extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tubitv.py", line 65, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1624, in _extract_m3u8_formats
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 665, in _download_webpage_handle
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2157, in sanitized_Request
  File "/usr/lib/python3.8/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/usr/lib/python3.8/urllib/request.py", line 354, in full_url
    self._parse()
  File "/usr/lib/python3.8/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: ''
```

## Description

Most links on TubiTV work, but certain programs fail to download with the above error.  Similar examples include:

https://tubitv.com/movies/563160/max-payne
https://tubitv.com/movies/563038/deuce-bigalow-male-gigolo
https://tubitv.com/movies/563042/king-arthur
https://tubitv.com/tv-shows/565922/s01-e01-rub-of-sugar-land-the

Many other programs will download correctly, but more and more each month are failing in this manner, suggesting that something has changed.

**Comment by remitamine** [comment]
youtube-dl does not support DRM protected videos.
