### ISSUE TITLE
ZDF: heute-journal: empty playlist (0 videos)

### ISSUE THREAD

**Issue by ipatix** [ytdl-org/youtube-dl#27297]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl -v "https://www.zdf.de/nachrichten/heute-journal"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.zdf.de/nachrichten/heute-journal']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.02
[debug] Python version 3.8.6 (CPython) - Linux-5.9.0-3-amd64-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.3.1-5, ffprobe 4.3.1-5
[debug] Proxy map: {}
[ZDFChannel] heute-journal: Downloading webpage
[download] Downloading playlist: heute-journal
[ZDFChannel] playlist heute-journal: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: heute-journal
```

## Description

Since about a couple days ago, downloading the most recent video (or playing through mpv) of the ZDF news (`https://www.zdf.de/nachrichten/heute-journal`) no longer works. Instead, an empty playlist is reported.

**Comment by october262** [comment]
try it with youtube-dl --force-generic-extractor "https://www.zdf.de/nachrichten/heute-journal"

**Comment by ipatix** [comment]
I think someone suggested I tried using the generic extractor and it won't work either:
```
$ youtube-dl --force-generic-extractor -v "https://www.zdf.de/nachrichten/heute-journal"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--force-generic-extractor', '-v', 'https://www.zdf.de/nachrichten/heute-journal']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.02
[debug] Python version 3.8.6 (CPython) - Linux-5.9.0-3-amd64-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.3.1-5, ffprobe 4.3.1-5
[debug] Proxy map: {}
[generic] heute-journal: Requesting header
WARNING: Forcing on generic information extractor.
[generic] heute-journal: Downloading webpage
[generic] heute-journal: Extracting information
ERROR: Unsupported URL: https://www.zdf.de/nachrichten/heute-journal
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/generic.py", line 3381, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.zdf.de/nachrichten/heute-journal
```
