### ISSUE TITLE
YOUTUBE new feature (?) request

### ISSUE THREAD

**Issue by nmr50** [ytdl-org/youtube-dl#27305]
- [x ] I'm reporting a site feature request
- [ x] I've verified that I'm running youtube-dl version **2020.12.05**
- [ x] I've searched the bugtracker for similar site feature requests including closed ones
## Description
I've tried to get video from youtube, and met very strange denial error:
This video contains content from CTB Film Company, who has blocked it from display on this website or application. Watch on YouTube.
The debug:
R:\>youtube-dl.exe -v -F https://youtu.be/uTfz6hq3NQo
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://youtu.be/uTfz6hq3NQo']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2020.12.05
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] uTfz6hq3NQo: Downloading webpage
[youtube] uTfz6hq3NQo: Downloading embed webpage
[youtube] uTfz6hq3NQo: Refetching age-gated info webpage
ERROR: This video contains content from CTB Film Company, who has blocked it from display on this website or application. Watch on YouTube
Traceback (most recent call last):  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\extractor\youtube.py", line 2059, in _real_extract
youtube_dl.utils.ExtractorError: This video contains content from CTB Film Company, who has blocked it from display on this website or application. Watch on YouTube

**Comment by dstftw** [comment]
You must authenticate.

**Comment by nmr50** [comment]
Using username and password being written OR asked while running the ydl - does not help, giving the same 'blocked' message:
R:\>youtube-dl -v -F -u MYLOGIN -p MYPASWORD https://youtu.be/uTfz6hq3NQo
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://youtu.be/uTfz6hq3NQo']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2020.12.05
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
[youtube] uTfz6hq3NQo: Downloading webpage
[youtube] uTfz6hq3NQo: Downloading embed webpage
[youtube] uTfz6hq3NQo: Refetching age-gated info webpage
ERROR: This video contains content from CTB Film Company, who has blocked it from display on this website or application. Watch on YouTube
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\extractor\youtube.py", line 2059, in _real_extract
youtube_dl.utils.ExtractorError: This video contains content from CTB Film Company, who has blocked it from display on this website or application. Watch on YouTube

Any ideas ?

**Comment by dstftw** [comment]
Use authenticated cookies.

**Comment by nmr50** [comment]
I use chrome fork 'srware iron', and I am trying to use 'Cookies' file that has SQL database obviously - ydl won't use it...
Can you tell, please, what exact filename/filename format should be used as cookies files ?

**Comment by Cathgao** [comment]
i guess this will never get fixed
