### ISSUE TITLE
[Youtube] Conversion failed! error after attempting subtitle embed.

### ISSUE THREAD

**Issue by WildManiac** [ytdl-org/youtube-dl#27330]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: ['-o', 'F:/VideoDownloads/%(extractor_key)s/%(uploader)s/%(title)s-%(id)s.%(ext)s', '--add-metadata', '--embed-thumbnail', '--sub-lang', 'en', '--write-sub', '--embed-sub', '--merge-output-format', 'mp4', '-f', 'bestvideo+bestaudio/best']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=W4e4gTmoGi4', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.12.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2020-12-06-git-2aab42bc40-full_build-www.gyan.dev, ffprobe 2020-12-06-git-2aab42bc40-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] W4e4gTmoGi4: Downloading webpage
[info] Writing video subtitles to: F:\VideoDownloads\Youtube\Geek & Sundry\Best Laid Plans... _ Critical Role - VOX MACHINA _ Episode 50-W4e4gTmoGi4.en.vtt
[youtube] W4e4gTmoGi4: Downloading thumbnail ...
[youtube] W4e4gTmoGi4: Writing thumbnail to: F:\VideoDownloads\Youtube\Geek & Sundry\Best Laid Plans... _ Critical Role - VOX MACHINA _ Episode 50-W4e4gTmoGi4.webp
[download] F:\VideoDownloads\Youtube\Geek & Sundry\Best Laid Plans... _ Critical Role - VOX MACHINA _ Episode 50-W4e4gTmoGi4.mp4 has already been downloaded and merged
[ffmpeg] Adding metadata to 'F:\VideoDownloads\Youtube\Geek & Sundry\Best Laid Plans... _ Critical Role - VOX MACHINA _ Episode 50-W4e4gTmoGi4.mp4'
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:F:\VideoDownloads\Youtube\Geek & Sundry\Best Laid Plans... _ Critical Role - VOX MACHINA _ Episode 50-W4e4gTmoGi4.mp4" -c copy -metadata "title=Best Laid Plans... | Critical Role: VOX MACHINA | Episode 50" -metadata "artist=Geek & Sundry" -metadata "purl=https://www.youtube.com/watch?v=W4e4gTmoGi4" -metadata "description=Catch Critical Role live Thursdays at 7PM PT on Twitch: https://goo.gl/D9fsrS

Listen to the Critical Role podcast: https://goo.gl/jVwPBr

Happy 50th episode everybody! Grog has a sword problem and the group stages an intervention, after which they begin to plan their attack on the Goliaths currently pillaging Westrunn. Everything is going to go great.

For more RPGs we love, go to http://bit.ly/GS_RPG

Visit us on http://geekandsundry.com
Subscribe to Geek and Sundry: http://goo.gl/B62jl
Join our community at: http://geekandsundry.com/community
Twitter: http://twitter.com/geekandsundry
Facebook: http://facebook.com/geekandsundry
Instagram: http://instagram.com/geekandsundry
Google+: https://plus.google.com/+GeekandSundry/" -metadata "date=20160608" -metadata "comment=Catch Critical Role live Thursdays at 7PM PT on Twitch: https://goo.gl/D9fsrS

Listen to the Critical Role podcast: https://goo.gl/jVwPBr

Happy 50th episode everybody! Grog has a sword problem and the group stages an intervention, after which they begin to plan their attack on the Goliaths currently pillaging Westrunn. Everything is going to go great.

For more RPGs we love, go to http://bit.ly/GS_RPG

Visit us on http://geekandsundry.com
Subscribe to Geek and Sundry: http://goo.gl/B62jl
Join our community at: http://geekandsundry.com/community
Twitter: http://twitter.com/geekandsundry
Facebook: http://facebook.com/geekandsundry
Instagram: http://instagram.com/geekandsundry
Google+: https://plus.google.com/+GeekandSundry/" "file:F:\VideoDownloads\Youtube\Geek & Sundry\Best Laid Plans... _ Critical Role - VOX MACHINA _ Episode 50-W4e4gTmoGi4.temp.mp4"
[ffmpeg] Embedding subtitles in 'F:\VideoDownloads\Youtube\Geek & Sundry\Best Laid Plans... _ Critical Role - VOX MACHINA _ Episode 50-W4e4gTmoGi4.mp4'
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:F:\VideoDownloads\Youtube\Geek & Sundry\Best Laid Plans... _ Critical Role - VOX MACHINA _ Episode 50-W4e4gTmoGi4.mp4" -i "file:F:\VideoDownloads\Youtube\Geek & Sundry\Best Laid Plans... _ Critical Role - VOX MACHINA _ Episode 50-W4e4gTmoGi4.en.vtt" -map 0 -c copy -map "-0:s" -map "-0:d" "-c:s" mov_text -map "1:0" "-metadata:s:s:0" "language=eng" "file:F:\VideoDownloads\Youtube\Geek & Sundry\Best Laid Plans... _ Critical Role - VOX MACHINA _ Episode 50-W4e4gTmoGi4.temp.mp4"
ERROR: Conversion failed!
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpz3dfuc4o\build\youtube_dl\YoutubeDL.py", line 2075, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpz3dfuc4o\build\youtube_dl\postprocessor\ffmpeg.py", line 426, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpz3dfuc4o\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

## Description

_While I have seen other reports similar to this one, none appear to concern embedded subtitles._
Youtube-dl is running into a **Conversion failed!** error after subtitles are embedded. The subtitles end before the end of the video, which may be the cause of the issue (just a shot in the dark here) because the .temp.mp4 file is about 2+hrs shorter than the .mp4 file (More info on this below). This is also affecting other links, but those I have yet to test with 2020.12.07.

**Additional Information**
Link affected: https://www.youtube.com/watch?v=W4e4gTmoGi4

Normal video length (first .mp4 file downloaded): 5:55:44
After attempted subtitle embed(.temp.mp4 file created): 3:01:41
Last section in the .en.vtt subtitle file:
```
03:01:41.278 --> 05:55:44.020
[end of transcript]
```

If more information is needed please let me know.

**Comment by kikuyan** [comment]
You need to report this to ffmpeg.

If you manually run ffmpeg with the options shown in the log, you'll see the error like this:
`[mp4 @ 0x7fa278000600] Application provided duration: 10442742000 is invalid`
This duration 10442742000 is of 03:01:41.278 --> 05:55:44.020, that is, 02:54:02.742.

And if you use mkv, you'll succeed. 

I only tried with smaller formats -f 278+249, but the story would be the same.
