### ISSUE TITLE
YT Playlist - Unable to recognize tab page;

### ISSUE THREAD

**Issue by cnguye** [ytdl-org/youtube-dl#27340]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2020.12.07**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', '--force-ipv4', '--external-downloader', 'ffmpeg', '--audio-format', 'mp3', '--audio-quality', '320k', '-o', '%(title)s.%(ext)s', '--yes-playlist', '--verbose', 'https://www.youtube.com/playlist?list=PLuog5kp6jhZ3rilKVTqxJjdWZyQdAH4hf']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.12.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-04-20-cacdac8, ffprobe git-2020-04-20-cacdac8
[debug] Proxy map: {}
[youtube:tab] PLuog5kp6jhZ3rilKVTqxJjdWZyQdAH4hf: Downloading webpage
ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpz3dfuc4o\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpz3dfuc4o\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpz3dfuc4o\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpz3dfuc4o\build\youtube_dl\extractor\youtube.py", line 3131, in _real_extract
youtube_dl.utils.ExtractorError: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

This has worked before the December 7th update.  I always use the same command (saved on notepad and copy pasted) when downloading playlists.

**Comment by llacb47** [comment]
You dummy, the playlist does not exist.

**Comment by cnguye** [comment]
> You dummy, the playlist does not exist.

Sorry! It was set to private.  **That was the cause.**  The playlist did exist, but you lead me in the right direction.  Upon checking previous playlists, they were all set to public.
