### ISSUE TITLE
big playlist error http 431

### ISSUE THREAD

**Issue by leshasmlesha** [ytdl-org/youtube-dl#27355]
## Checklist

- [x] I've verified that I'm running youtube-dl version **2020.12.09**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://music.yandex.ru/users/smorkaloff.al/playlists/3', '-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2020.12.09
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[yandexmusic:playlist] 3: Downloading playlist JSON
[yandexmusic:playlist] 3: Downloading missing tracks JSON
WARNING: Unable to download JSON metadata: HTTP Error 431: Request Header Fields Too Large
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\YoutubeDL.py", line 2029, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\extractor\yandexmusic.py", line 329, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\extractor\yandexmusic.py", line 214, in _extract_tracks
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\extractor\yandexmusic.py", line 59, in _call_api
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\extractor\yandexmusic.py", line 45, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\extractor\common.py", line 897, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\extractor\common.py", line 875, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\extractor\yandexmusic.py", line 40, in _download_webpage_handle
TypeError: argument of type 'bool' is not iterable
```

## Description

I wanted to download my own playlist with more than 700 tracks, but I got an error, but another playlist is being downloaded.

**Comment by danil-tolkachev** [comment]
Same problem on 2021.01.24.1 with about 500 items in playlist.

Wait here for solution.

**Comment by Arksault** [comment]
I still haven't figured out how to get a solution to the problem?

for a program from under windows

**Comment by leshasmlesha** [comment]
wait release.

**Comment by TheAndrey** [comment]
The problem is still relevant. For a large playlist of 800+ tracks, the limit has to be lowered to 200.
