### ISSUE TITLE
Failed to Download from Mixcloud - Apparent SSL Certificate Failure

### ISSUE THREAD

**Issue by Gho57X90** [ytdl-org/youtube-dl#27359]
Checklist:
--------------------------------------
- [x]  I've verified that I'm running youtube-dl version 2020.12.09
- [x]  I've checked that all provided URLs are alive and playable in a browser
- [x]  I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x]  I've searched the bugtracker for similar bug reports including closed ones
- [x]  I've read bugs section in FAQ

Description:
--------------------------------------
I attempted to download a radio show episode hosted on Mixcloud, but I appear to only be getting SSL certificate errors with any uploaded episode I attempt to download. I am not aware of how to solve an SSL certificate issue, or if there's even anything I can personally do to fix it.

The target content appears to play just fine, so I'm unsure of what steps to take with this.

Verbose Log:
--------------------------------------
```
C:\youtube-dl>youtube-dl.exe --verbose https://www.mixcloud.com/deadmau5/deadmau5-presents-mau5trap-radio-065-with-posij-guest-mix/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.mixcloud.com/deadmau5/deadmau5-presents-mau5trap-radio-065-with-posij-guest-mix/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.12.09
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-07-24-21442a8
[debug] Proxy map: {}
[mixcloud] deadmau5_deadmau5-presents-mau5trap-radio-065-with-posij-guest-mix: Downloading JSON metadata
[mixcloud] deadmau5_deadmau5-presents-mau5trap-radio-065-with-posij-guest-mix: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[mixcloud] deadmau5_deadmau5-presents-mau5trap-radio-065-with-posij-guest-mix: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://stream4.mixcloud.com/secure/c/m4a/64/3/c/f/4/ead2-2924-4af1-a939-44cd3b07847c.m4a?sig=q9gFWiVFTuKeXI1-oXrb4Q'
ERROR: unable to download video data: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1287, in connect
  File "C:\Python\Python34\lib\ssl.py", line 362, in wrap_socket
  File "C:\Python\Python34\lib\ssl.py", line 580, in __init__
  File "C:\Python\Python34\lib\ssl.py", line 807, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\YoutubeDL.py", line 1936, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\YoutubeDL.py", line 1875, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\downloader\http.py", line 351, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\downloader\http.py", line 116, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\downloader\http.py", line 110, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\YoutubeDL.py", line 2248, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\utils.py", line 2736, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
```

**Comment by october262** [comment]
try  youtube-dl --no-part --restrict-filenames "https://audio8.mixcloud.com/secure/dash2/3/c/f/4/ead2-2924-4af1-a939-44cd3b07847c.m4a/manifest.mpd"

**Comment by ThePadawan** [comment]
I also have this issue using version 2020.12.31.

@october262 Unfortunately, your suggestion did not fix the issue.
