### ISSUE TITLE
Unable to extract video title while trying to download private  videos

### ISSUE THREAD

**Issue by skeptronex** [ytdl-org/youtube-dl#27368]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.09**
- [x] I've checked that all provided URLs are alive and playable in a browser [note that the video is private]
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=SvC4LBSZm7Q', '--cookies', 'cookies.txt', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.12.09
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] SvC4LBSZm7Q: Downloading webpage
[youtube] SvC4LBSZm7Q: Downloading embed webpage
[youtube] SvC4LBSZm7Q: Refetching age-gated info webpage
WARNING: Unable to extract video title
ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\extractor\youtube.py", line 2055, in _real_extract
youtube_dl.utils.ExtractorError: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; 

```

## Description

I am getting the error described  above only while tryng to download any of my private videos.

**Comment by dstftw** [comment]
Most likely expired cookies.

**Comment by skeptronex** [comment]
> 
> 
> Most likely expired cookies.

This is not due to expired cookies, as the cookies used were freshly exported. The exact same error also happens when I log in using -u username -p password method. 


Also if it is worth mentioning, the private videos were uploaded by a different user and access was given to the account I am using to download.

**Comment by skeptronex** [comment]
#27301 seems to be related
