### ISSUE TITLE
Any URL that contains º char brokes youtube-dl º

### ISSUE THREAD

**Issue by felisucoibi** [ytdl-org/youtube-dl#27363]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.09**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--cookies', u'atresplayer.com-cookies.txt', u'--get-filename', u'-o', u'%(title)s', u'https://www.atresplayer.com/kidz/series-infantiles/pucca/temporada-2/capitulo-16-1\xbaparte-secuestro-de-cocineros_5c7402b27ed1a80783fd2ac7/']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2020.12.07
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-53-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
ERROR: An extractor error has occurred. (caused by KeyError(u'href',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/atresplayer.py", line 113, in _real_extract
    metadata = self._download_json(link_info['href'], video_id)
KeyError: u'href'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 545, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'href',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description
Any URL that contains º char brokes youtube-dl º

Example https://www.atresplayer.com/kidz/series-infantiles/pucca/temporada-2/capitulo-16-1%C2%BAparte-secuestro-de-cocineros_5c7402b27ed1a80783fd2ac7/

**Comment by felisucoibi** [comment]
I tried with this url https://www.atresplayer.com/kidz/series-infantiles/pucca/temporada-2/capitulo-16-1%C2%BAparte-secuestro-de-cocineros_5c7402b27ed1a80783fd2ac7/
and also does not work.

Tested with python2 and 3 same problem.
