### ISSUE TITLE
cannot download anything - contant errors 

### ISSUE THREAD

**Issue by britmotley** [ytdl-org/youtube-dl#27374]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.12.09**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

## Description

WRITE DESCRIPTION HERE

**Comment by britmotley** [comment]
Why is it incomplete ?

**Comment by remitamine** [comment]
you didn't provide any details to know what is the problem you have.

**Comment by britmotley** [comment]
Ok, I don't know what you say , I'm not a professional ,I provided the
error log , i don't know what else I can do

**Comment by britmotley** [comment]
[12/09/20 23:05:54] [debug] System config: []

[12/09/20 23:05:54] [debug] User config: []

[12/09/20 23:05:54] [debug] Custom config: []

[12/09/20 23:05:54] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\palmer\\Desktop\\IDM\\%(title)s.%(ext)s', '-f', 'mp4', '-v', '--ignore-config', '--hls-prefer-native', 'https://www.itv.com/hub/coronation-street/1a0694a10189']

[12/09/20 23:05:54] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252

[12/09/20 23:05:54] [debug] youtube-dl version 2020.07.28

[12/09/20 23:05:54] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362

[12/09/20 23:05:54] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2

[12/09/20 23:05:54] [debug] Proxy map: {}

[12/09/20 23:05:54] WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out

[12/09/20 23:05:54] ERROR: unable to download video data: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:600)>

[12/09/20 23:05:54] Traceback (most recent call last):

[12/09/20 23:05:54] File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open

[12/09/20 23:05:54] File "C:\Python\Python34\lib\http\client.py", line 1137, in request

[12/09/20 23:05:54] File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request

[12/09/20 23:05:54] File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders

[12/09/20 23:05:54] File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output

[12/09/20 23:05:54] File "C:\Python\Python34\lib\http\client.py", line 898, in send

[12/09/20 23:05:54] File "C:\Python\Python34\lib\http\client.py", line 1287, in connect

[12/09/20 23:05:54] File "C:\Python\Python34\lib\ssl.py", line 362, in wrap_socket

[12/09/20 23:05:54] File "C:\Python\Python34\lib\ssl.py", line 580, in __init__

[12/09/20 23:05:54] File "C:\Python\Python34\lib\ssl.py", line 807, in do_handshake

[12/09/20 23:05:54] ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:600)

[12/09/20 23:05:54]

[12/09/20 23:05:54] During handling of the above exception, another exception occurred:

[12/09/20 23:05:54]

[12/09/20 23:05:54] Traceback (most recent call last):

[12/09/20 23:05:54] File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 1926, in process_info

[12/09/20 23:05:54] File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 1865, in dl

[12/09/20 23:05:54] File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\downloader\common.py", line 366, in download

[12/09/20 23:05:54] File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\downloader\hls.py", line 148, in real_download

[12/09/20 23:05:54] File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\downloader\fragment.py", line 102, in _download_fragment

[12/09/20 23:05:54] File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\downloader\common.py", line 366, in download

[12/09/20 23:05:54] File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\downloader\http.py", line 341, in real_download

[12/09/20 23:05:54] File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\downloader\http.py", line 109, in establish_connection

[12/09/20 23:05:54] File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen

[12/09/20 23:05:54] File "C:\Python\Python34\lib\urllib\request.py", line 464, in open

[12/09/20 23:05:54] File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open

[12/09/20 23:05:54] File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain

[12/09/20 23:05:54] File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\utils.py", line 2736, in https_open

[12/09/20 23:05:54] File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open

[12/09/20 23:05:54] urllib.error.URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:600)>

[12/09/20 23:05:54]

**Comment by remitamine** [comment]
try to update to the latest version and then try again.

**Comment by britmotley** [comment]
I primarily use youtube-DLG      will the update affect that ?

**Comment by remitamine** [comment]
i don't use it, so i'm not sure, it might has it own update method, anyway try to update youtube-dl first, if it still does not work, then it might be a problem with system Certificate Store.

**Comment by britmotley** [comment]
How would I fix. Certificate store issue ?

**Comment by remitamine** [comment]
did you update youtube-dl?

> How would I fix. Certificate store issue ?

i don't use windows, so i can't help here.
