### ISSUE TITLE
ERROR: unable to download video data: <urlopen error [Errno 0] Error>

### ISSUE THREAD

**Issue by aleen42** [ytdl-org/youtube-dl#27403]
When I tried to run the following command, and get the error `urlopen error [Errno 0] Error`

``` bash
$  youtube-dl -v -f 272 --proxy socks5://127.0.0.1:1080/ https://www.youtube.com/watch?v=kA3k8LNHX4Y
```

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '272', '--proxy', 'socks5://127.0.0.1:1080/', 'https://www.youtube.com/watch?v=kA3k8LNHX4Y']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.12
[debug] Python version 3.8.2 (CPython) - Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {'http': 'socks5://127.0.0.1:1080/', 'https': 'socks5://127.0.0.1:1080/'}
[youtube] kA3k8LNHX4Y: Downloading webpage
[debug] Invoking downloader on 'https://r3---sn-i3b7kns6.googlevideo.com/videoplayback?expire=1607857730&ei=4qHVX7ThF4XpgQOLnrygBw&ip=203.184.132.208&id=o-ABlGAj5auHuS-J_dZCnhrHHyATK3IqSyOolTRjknlGUc&itag=272&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C272%2C278%2C298%2C299%2C302%2C303%2C308%2C315&source=youtube&requiressl=yes&mh=uQ&mm=31%2C26&mn=sn-i3b7kns6%2Csn-npoe7n7y&ms=au%2Conr&mv=m&mvi=3&pl=24&initcwndbps=1188750&vprv=1&mime=video%2Fwebm&ns=0udl7fhHKFQ6LVwcaDQ49ucF&gir=yes&clen=1433874617&dur=729.040&lmt=1606936309848945&mt=1607835646&fvip=3&keepalive=yes&c=WEB&txp=6411222&n=S9OVKQ8Ql5Is-M3cN&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAP8dpfH2NAG0rfhOrZALAygRjhXun3KDbI3PlTfdsCnfAiAd7_gg5NVcESGNJQLclQWn4wBZn2YpgO1oBpB9-nZsPg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgfbHu9fYA_CDiTDmtcfWhWXm16fL_6F9nLQ5izX-Dey4CIQC40MksFcVWqeC6maXj9LyNVDYsvokMXmVoXKlxwZiNsw%3D%3D&ratebypass=yes'
[download] Resuming download at byte 692626499
[download] Destination: 京都の穴場スポット ⑥ - A secret spot in Kyoto（Kyoto, Japan）-kA3k8LNHX4Y.webm
[download]  50.5% of 1.34GiB at  5.90MiB/s ETA 01:54
ERROR: unable to download video data: <urlopen error [Errno 0] Error>
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1326, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 2706, in connect
    self.sock = self._context.wrap_socket(
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1936, in process_info
    success = dl(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1875, in dl
    return fd.download(name, info)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/bin/youtube-dl/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
  File "/usr/bin/youtube-dl/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2248, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 2734, in https_open
    return self.do_open(functools.partial(
  File "/usr/lib/python3.8/urllib/request.py", line 1329, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 0] Error>
```

**Comment by aleen42** [comment]
How can I fix it?

**Comment by imba-tjd** [comment]
try `-f best`
不过只治标

**Comment by aleen42** [comment]
Why closed?
