### ISSUE TITLE
404 Error on available video

### ISSUE THREAD

**Issue by btwood** [ytdl-org/youtube-dl#27401]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.12**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v https://www.youtube.com/watch?v=3Hk__Hk5c9M
[debug] System config: ['-o', '%(uploader)s_%(upload_date)s_%(title)s-%(id)s.%(ext)s', '--write-info-json', '--cookies', '/root/Downloads/cookies.txt']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=3Hk__Hk5c9M']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.12
[debug] Python version 3.6.9 (CPython) - Linux-5.4.60-1-pve-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[youtube] 3Hk__Hk5c9M: Downloading webpage
[youtube] 3Hk__Hk5c9M: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video description metadata as JSON to: David Oranchak_20180928_What is Zodiac's 340-Character Cipher  2018 ACA Presentation-3Hk__Hk5c9M.info.json
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r1---sn-vgqsrned.googlevideo.com/videoplayback?expire=1607853491&ei=U5HVX5TAD8_Zkga5u43IAg&ip=154.29.131.201&id=o-AOlDkbYsvJ3cGaR4Tc9Cwo0T9GYfvpS4WBRTkTw06r6Q&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=yt_otf&requiressl=yes&mh=K8&mm=31%2C26&mn=sn-vgqsrned%2Csn-q4fl6nlz&ms=au%2Conr&mv=m&mvi=1&pl=25&initcwndbps=636250&vprv=1&mime=video%2Fwebm&ns=pGwfWfq52VwNJ3Vz-SoQVAwF&otf=1&otfp=1&dur=0.000&lmt=1538131932427427&mt=1607831566&fvip=1&keepalive=yes&beids=9466588&c=WEB&n=WHqEeshQiKpuA51XW&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cotf%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIrNSo6tdkN_TMm7ocbETttQFEMfRDxlG2-krUCL-AnqAiAe90y9TyKOFr47Y81mvpQvYBfVT0C4oPPQzEiBnmJr7Q%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANfaZHBZ2ieBNsZnNrPZ1TUtGt3QsOf5L8GFQUYLfyPzAiBwV2MDLu1XosQnFC4F-2Q9JOGHarjvsB8Mgyt8JVTaDg%3D%3D&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1930, in process_info
    partial_success = dl(fname, new_info)
  File "/root/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1875, in dl
    return fd.download(name, info)
  File "/root/.local/lib/python3.6/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/root/.local/lib/python3.6/site-packages/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/root/.local/lib/python3.6/site-packages/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
  File "/root/.local/lib/python3.6/site-packages/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/root/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2248, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

## Description

This video plays in browser, but does not download. At first I thought it must be an error with the youtube ID containing two underscores, but the verbose shows that it fails at the googlevideo CDN. If I had to guess it's a problem with urllib parsing some part of the URL.

**Comment by btwood** [comment]
@dstftw Why did you close this as duplicate? This is a discrete example of a broken URL, and not a failed video download.

It works for every other site/video. Please tell me why. If you're leaving it up to me to start digging through the code. I'll do it.

Are you in the habit of closing tickets without even investigating? I've tried this video on two different machines on two different networks, both get the same 404 error. 

This is strange, because if you read the output, you'd notice that the 404 happens after a JSON file is written. Meaning the youtube URL was valid, and the MPD manifest looked good, and there is something wrong with the googlevideo part.
