### ISSUE TITLE
Certain movies on Tubitv.com won't download using youtube-dl. 

### ISSUE THREAD

**Issue by dwalkerdon** [ytdl-org/youtube-dl#27408]
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2020.12.12**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
Certain movies on tubitv.com, are not able to be downloaded using youtube-dl, the log says this:  ERROR: unknown url type: ''

here are a few url examples of movies that wont Download using youtube DL:
 http://tubitv.com/movies/563044/the-sixth-man
http://tubitv.com/movies/563667/gravity
http://tubitv.com/movies/563164/white-men-can-t-jump
http://tubitv.com/movies/563168/predators
http://tubitv.com/movies/563162/street-kings
http://tubitv.com/movies/563166/28-weeks-later
http://tubitv.com/movies/563160/max-payne
http://tubitv.com/movies/565093/baggage-claim
http://tubitv.com/movies/563170/jumper

**Comment by dstftw** [comment]
>Content Unavailable
Sorry, this video is not currently available.

**Comment by dwalkerdon** [comment]
All of those links are currently available at the moment in the United States

**Comment by tortured1** [comment]
I'm totally unable to download 563667 (Gravity) from the US.  I get that same error with version 2020.12.31:

[TubiTv] 563667: Downloading JSON metadata
[TubiTv] 563667: Downloading m3u8 information
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 33, in <module>
    sys.exit(load_entry_point('youtube-dl==2020.12.31', 'console_scripts', 'youtube-dl')())
  File "/usr/lib/python3.9/site-packages/youtube_dl/__init__.py", line 473, in main
    _real_main(argv)
  File "/usr/lib/python3.9/site-packages/youtube_dl/__init__.py", line 463, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2027, in download
    res = self.extract_info(
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 795, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 802, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 823, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/tubitv.py", line 78, in _real_extract
    formats = self._extract_m3u8_formats(
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1632, in _extract_m3u8_formats
    res = self._download_webpage_handle(
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 665, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    url_or_request = sanitized_Request(url_or_request, data, headers)
  File "/usr/lib/python3.9/site-packages/youtube_dl/utils.py", line 2156, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib64/python3.9/urllib/request.py", line 320, in __init__
    self.full_url = url
  File "/usr/lib64/python3.9/urllib/request.py", line 346, in full_url
    self._parse()
  File "/usr/lib64/python3.9/urllib/request.py", line 375, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: ''
