### ISSUE TITLE
slideslive.com -> "invalid data found when processing input"

### ISSUE THREAD

**Issue by dbieber** [ytdl-org/youtube-dl#27400]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.12**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://slideslive.com/38935933/laminaspecific-neuronal-properties-promote-robust-stable-signal-propagation-in-feedforward-networks']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.12
[debug] Python version 3.9.1 (CPython) - macOS-10.15.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[SlidesLive] 38935933: Downloading JSON metadata
[SlidesLive] u8dpShPqW0YO: Downloading m3u8 information
[SlidesLive] u8dpShPqW0YO: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://01.cdn.yoda.slideslive.com/u8dpShPqW0YO/media_4.m3u8'
[download] Lamina-specific neuronal properties promote robust, stable signal propagation in feedforward networks-u8dpShPqW0YO.fhls-4629.mp4 has already been downloaded
[download] 100% of 101.98MiB
[debug] Invoking downloader on 'https://01.cdn.yoda.slideslive.com/u8dpShPqW0YO/master.mpd'
[download] Lamina-specific neuronal properties promote robust, stable signal propagation in feedforward networks-u8dpShPqW0YO.fdash-5.m4a has already been downloaded
[download] 100% of 2.92MiB
[ffmpeg] Merging formats into "Lamina-specific neuronal properties promote robust, stable signal propagation in feedforward networks-u8dpShPqW0YO.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Lamina-specific neuronal properties promote robust, stable signal propagation in feedforward networks-u8dpShPqW0YO.fhls-4629.mp4' -i 'file:Lamina-specific neuronal properties promote robust, stable signal propagation in feedforward networks-u8dpShPqW0YO.fdash-5.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Lamina-specific neuronal properties promote robust, stable signal propagation in feedforward networks-u8dpShPqW0YO.temp.mp4'
ERROR: file:Lamina-specific neuronal properties promote robust, stable signal propagation in feedforward networks-u8dpShPqW0YO.fhls-4629.mp4: Invalid data found when processing input
Traceback (most recent call last):
  File "/Users/dbieber/.virtualenvs/_3/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2075, in post_process
    files_to_delete, info = pp.run(info)
  File "/Users/dbieber/.virtualenvs/_3/lib/python3.9/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 523, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/Users/dbieber/.virtualenvs/_3/lib/python3.9/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:Lamina-specific neuronal properties promote robust, stable signal propagation in feedforward networks-u8dpShPqW0YO.fhls-4629.mp4: Invalid data found when processing input
```

## Description

I am trying to download this video https://slideslive.com/38935933/laminaspecific-neuronal-properties-promote-robust-stable-signal-propagation-in-feedforward-networks
from SlidesLive. The audio downloads and plays successfully, but the video seems to be corrupt.
It plays when I visit it in the browser though.

When I run the ffmpeg command manually in verbose mode I get this additional debug info:
```
>  ffmpeg -y -loglevel repeat+info -i 'file:Analytical Probability Distributions and EM-Learning for Deep Generative Networks-l6f0wWftel8u.fhls-4629.mp4' -i 'file:Analytical Probability Distributions and EM-Learning for Deep Generative Networks-l6f0wWftel8u.fdash-5.m4a'   'file:Analytical Probability Distributions and EM-Learning for Deep Generative Networks-l6f0wWftel8u.temp.mp4'
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.27)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.1_4 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fa78e808200] could not find corresponding track id 1
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fa78e808200] could not find corresponding trex (id 1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fa78e808200] could not find corresponding track id 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fa78e808200] trun track id unknown, no tfhd was found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fa78e808200] error reading header
file:Analytical Probability Distributions and EM-Learning for Deep Generative Networks-l6f0wWftel8u.fhls-4629.mp4: Invalid data found when processing input
```

I get the same error when trying to download any other NeurIPS 2020 video from SlidesLive. (These are the only videos I've tried to download.) Another example video I get the same error with is: https://slideslive.com/38937467/neural-execution-engines-learning-to-execute-subroutines.

Here's the verbose output for that one:

```
> youtube-dl -v https://slideslive.com/38937467/neural-execution-engines-learning-to-execute-subroutines
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://slideslive.com/38937467/neural-execution-engines-learning-to-execute-subroutines']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.12
[debug] Python version 3.9.1 (CPython) - macOS-10.15.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[SlidesLive] 38937467: Downloading JSON metadata
[SlidesLive] xtHyapHLt8Mo: Downloading m3u8 information
[SlidesLive] xtHyapHLt8Mo: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://01.cdn.yoda.slideslive.com/xtHyapHLt8Mo/media_4.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 51
[download] Destination: Neural Execution Engines - Learning to Execute Subroutines-xtHyapHLt8Mo.fhls-4629.mp4
[download] 100% of 105.00MiB in 00:27
[debug] Invoking downloader on 'https://01.cdn.yoda.slideslive.com/xtHyapHLt8Mo/master.mpd'
[dashsegments] Total fragments: 52
[download] Destination: Neural Execution Engines - Learning to Execute Subroutines-xtHyapHLt8Mo.fdash-5.m4a
[download] 100% of 2.75MiB in 00:08
[ffmpeg] Merging formats into "Neural Execution Engines - Learning to Execute Subroutines-xtHyapHLt8Mo.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Neural Execution Engines - Learning to Execute Subroutines-xtHyapHLt8Mo.fhls-4629.mp4' -i 'file:Neural Execution Engines - Learning to Execute Subroutines-xtHyapHLt8Mo.fdash-5.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Neural Execution Engines - Learning to Execute Subroutines-xtHyapHLt8Mo.temp.mp4'
ERROR: file:Neural Execution Engines - Learning to Execute Subroutines-xtHyapHLt8Mo.fhls-4629.mp4: Invalid data found when processing input
Traceback (most recent call last):
  File "/Users/dbieber/.virtualenvs/_3/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2075, in post_process
    files_to_delete, info = pp.run(info)
  File "/Users/dbieber/.virtualenvs/_3/lib/python3.9/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 523, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/Users/dbieber/.virtualenvs/_3/lib/python3.9/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:Neural Execution Engines - Learning to Execute Subroutines-xtHyapHLt8Mo.fhls-4629.mp4: Invalid data found when processing input
```

**Comment by kikuyan** [comment]
try with --hls-prefer-ffmpeg option

**Comment by remitamine** [comment]
similar to #24868.

**Comment by remitamine** [comment]
as been suggested by @kikuyan, for now either use `--hls-prefer-ffmpeg` or select dash formats.

**Comment by dbieber** [comment]
Thanks @kikuyan and @remitamine. This worked 👍 
I really appreciate the speed with which you were able to provide a solution to my issue. 🙏

As a note for future people hitting this issue,
I had to delete the already-downloaded files before rerunning the command for it to work. Otherwise it tried reusing the already downloaded files.
