### ISSUE TITLE
Video IDs/URLs with hyphens (dashes) in them won't work

### ISSUE THREAD

**Issue by nekohayo** [ytdl-org/youtube-dl#27416]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.12**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v "https://www.youtube.com/watch?v=-\PJ5pKo5iOU"
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=-\\PJ5pKo5iOU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.12
[debug] Python version 3.9.0 (CPython) - Linux-5.9.11-200.fc33.x86_64-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[generic] watch?v=-\PJ5pKo5iOU: Requesting header
[redirect] Following redirect to https://www.youtube.com/watch?v=-%5CPJ5pKo5iO
[generic] watch?v=-\PJ5pKo5iO: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch?v=-\PJ5pKo5iO: Downloading webpage
[generic] watch?v=-\PJ5pKo5iO: Extracting information
ERROR: Unsupported URL: https://www.youtube.com/watch?v=-%5CPJ5pKo5iO
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 802, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 823, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/generic.py", line 3418, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.youtube.com/watch?v=-%5CPJ5pKo5iO
```

## Description

In some rare cases, you encounter a video with a "-" in its ID/URL, such as this one: https://www.youtube.com/watch?v=-PJ5pKo5iOU

Trying to archive it with youtube-dl does not seem to work, as I have tried various permutations:

```
$ youtube-dl \-PJ5pKo5iOU
Usage: youtube-dl [OPTIONS] URL [URL...]
youtube-dl: error: no such option: -P

$ youtube-dl \-\PJ5pKo5iOU
Usage: youtube-dl [OPTIONS] URL [URL...]
youtube-dl: error: no such option: -P

$ youtube-dl "\-\PJ5pKo5iOU"
ERROR: '\\-\\PJ5pKo5iOU' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:\-\PJ5pKo5iOU" ) to search YouTube

$ youtube-dl "\-PJ5pKo5iOU"
ERROR: '\\-PJ5pKo5iOU' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:\-PJ5pKo5iOU" ) to search YouTube

$ youtube-dl "https://www.youtube.com/watch?v=\-PJ5pKo5iOU"
[generic] watch?v=\-PJ5pKo5iOU: Requesting header
[redirect] Following redirect to https://www.youtube.com/watch?v=%5C-PJ5pKo5iO
[generic] watch?v=\-PJ5pKo5iO: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch?v=\-PJ5pKo5iO: Downloading webpage
[generic] watch?v=\-PJ5pKo5iO: Extracting information
ERROR: Unsupported URL: https://www.youtube.com/watch?v=%5C-PJ5pKo5iO

$ youtube-dl "https://www.youtube.com/watch?v=-\PJ5pKo5iOU"
[generic] watch?v=-\PJ5pKo5iOU: Requesting header
[redirect] Following redirect to https://www.youtube.com/watch?v=-%5CPJ5pKo5iO
[generic] watch?v=-\PJ5pKo5iO: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch?v=-\PJ5pKo5iO: Downloading webpage
[generic] watch?v=-\PJ5pKo5iO: Extracting information
ERROR: Unsupported URL: https://www.youtube.com/watch?v=-%5CPJ5pKo5iO
```

I was able to work around the problem with `youtube-dl ytsearch:"The Monolith Commands You To Visit Utah"` in this case (which proves that, ultimately, youtube-dl is technically able to download this video and that there is nothing particular except the ID), but it would be nice if youtube-dl was able to handle hyphen characters, especially when I escape them.

**Comment by dstftw** [comment]
Read FAQ.

**Comment by nekohayo** [comment]
I did. The FAQ covers ampersands, but not hyphens. It just says to escape the characters and/or to put things in quotes, which is what I did, and it still didn't work. Otherwise what did I miss in the FAQ?

**Comment by im-coooding** [comment]
You can stop it from trying to read options by adding `--` as a separator before you type any video IDs or urls. Anything after `--` will always be treated as a url or video id.

So if you do `youtube-dl -- -PJ5pKo5iOU` then it should work 👍

It's a good habit to get into to always add the double-dash I think.

Also, to avoid any confusion: You only add them once per command line to mark "end-of-options", not in front of every video ID.
