### ISSUE TITLE
Cookies for Instagram not working

### ISSUE THREAD

**Issue by smnthermes** [ytdl-org/youtube-dl#27422]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose --cookies /home/tim/Documentos/cookies.txt https://instagram.com/p/aye83DjauH/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--cookies', '/home/tim/Documentos/cookies.txt', 'https://instagram.com/p/aye83DjauH/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-58-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[Instagram] aye83DjauH: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/tim/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tim/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/home/tim/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/tim/.local/lib/python3.8/site-packages/youtube_dl/extractor/instagram.py", line 195, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/home/tim/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1128, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/home/tim/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1019, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/tim/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

EDIT: The video is public, but Instagram blocks VPN or Tor if not logged in.
I used a cookies.txt file generated by the Firefox extension mentioned in README.md:
```
# Netscape HTTP Cookie File
# https://curl.haxx.se/rfc/cookie_spec.html
# This is a generated file! Do not edit.

#HttpOnly_.instagram.com	TRUE	/	TRUE	1670969703	ig_did	63C9A59C-B283-4A86-A59F-0F54D3D892C9
.instagram.com	TRUE	/	TRUE	1639433703	ig_nrcb	1
.instagram.com	TRUE	/	TRUE	1670969703	mid	X9aSZwAEAAGTRatw-HhQSiWT0ad4
#HttpOnly_.instagram.com	TRUE	/	TRUE	0	rur	FRC
#HttpOnly_.instagram.com	TRUE	/	TRUE	1639433717	sessionid	41350652408%3ApctTdR5YAduwKK%3A11
.instagram.com	TRUE	/	TRUE	1639347323	csrftoken	217h7kyTQfEViXVOUCzHwzbjSOYa4D0d
.instagram.com	TRUE	/	TRUE	1615673723	ds_user_id	41350652408
#HttpOnly_.instagram.com	TRUE	/	TRUE	0	urlgen	"{\"191.189.237.226\": 28573}:1koZeF:FfvxP483Z-SaQIMB3XDXTNTf4hE"
```

cookies.txt file after being modified by youtube-dl:
```
# Netscape HTTP Cookie File
# This file is generated by youtube-dl.  Do not edit.

.instagram.com	TRUE	/	TRUE	1639348003	csrftoken	217h7kyTQfEViXVOUCzHwzbjSOYa4D0d
.instagram.com	TRUE	/	TRUE	1615674403	ds_user_id	41350652408
.instagram.com	TRUE	/	TRUE	1670969703	ig_did	63C9A59C-B283-4A86-A59F-0F54D3D892C9
.instagram.com	TRUE	/	TRUE	1639433703	ig_nrcb	1
.instagram.com	TRUE	/	TRUE	1670969703	mid	X9aSZwAEAAGTRatw-HhQSiWT0ad4
.instagram.com	TRUE	/	TRUE	0	rur	FRC
.instagram.com	TRUE	/	TRUE	1639433717	sessionid	41350652408%3ApctTdR5YAduwKK%3A11
.instagram.com	TRUE	/	TRUE	0	urlgen	"{\"191.189.237.226\": 28573}:1koZpC:Tk6OuEr4mAOX8oUbyvz8LD-4H0o"
```

**Comment by midexe6380** [comment]
@smnthermes 
The problem is on your side. Everything works fine for me. I downloaded your video without cookies.txt file.  ```youtube-dl version 2020.12.14```

```
youtube-dl --verbose --add-metadata --rm-cache-dir https://www.instagram.com/p/aye83DjauH
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--add-metadata', '--rm-cache-dir', 'https://www.instagram.com/p/aye83DjauH']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.9.0 (CPython) - Linux-5.4.82-1-lts-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
Removing cache dir ~/.cache/youtube-dl ..
[Instagram] aye83DjauH: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://scontent-arn2-1.cdninstagram.com/v/t50.2886-16/11539930_919766514753417_231041833_n.mp4?efg=eyJxZV9ncm91cHMiOiJbXCJpZ19wcm9ncmVzc2l2ZV91cmxnZW4ucHJvZHVjdF90eXBlLmZlZWRcIl0ifQ&_nc_ht=scontent-arn2-1.cdninstagram.com&_nc_cat=109&_nc_ohc=zmLlgFQ6ky0AX-2xmBI&oe=5FD8E47E&oh=8ea5dc6b9e34ac17bac27d1942587be5'
[download] Destination: Video by naomipq-aye83DjauH.mp4
[download] 100% of 1.16MiB in 00:10
[ffmpeg] Adding metadata to 'Video by naomipq-aye83DjauH.mp4'
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Video by naomipq-aye83DjauH.mp4' -c copy -metadata 'title=Video by naomipq' -metadata date=20130620 -metadata 'description=If Abel was a booger, Luke would definitely pick him. See it in action by playing this video. Yes! That'"'"'s right, folks. This is a video and Instagram made that possible! Read about this new capability and check out the promo video (with our cameo appearance) by clicking on the link in my profile. Also, be sure to download the latest version of Instagram and start sharing your videos!' -metadata 'comment=If Abel was a booger, Luke would definitely pick him. See it in action by playing this video. Yes! That'"'"'s right, folks. This is a video and Instagram made that possible! Read about this new capability and check out the promo video (with our cameo appearance) by clicking on the link in my profile. Also, be sure to download the latest version of Instagram and start sharing your videos!' -metadata purl=https://www.instagram.com/p/aye83DjauH -metadata 'artist=B E A U T Y  F O R  A S H E S' 'file:Video by naomipq-aye83DjauH.temp.mp4'
```

**Comment by xihuny** [comment]
Not working for me either. How to solve this issue?
