### ISSUE TITLE
error in video downloading from youtube.

### ISSUE THREAD

**Issue by rzzzvikashkumar** [ytdl-org/youtube-dl#27429]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\V\Desktop>youtube-dl -v -f 136+140 https://www.youtube.com/watch?v=8ext
9G7xspg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '136+140', 'https://www.youtube.com/watc
h?v=8ext9G7xspg']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] 8ext9G7xspg: Downloading webpage
[debug] Invoking downloader on 'https://r2---sn-gwpa-b506.googlevideo.com/videop
layback?expire=1607944696&ei=mPXWX5-uLfzg4-EPqayAkAY&ip=2405%3A201%3Aa409%3A9842
%3Ac40a%3A8433%3Af2d%3Aff2e&id=o-AHGCLs15LcpnNwPGhGmAr47SrW4MMdgg862YvPik9KwU&it
ag=136&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C
278&source=youtube&requiressl=yes&mh=Fh&mm=31%2C29&mn=sn-gwpa-b506%2Csn-qxa7sn7r
&ms=au%2Crdu&mv=m&mvi=2&pl=39&initcwndbps=996250&vprv=1&mime=video%2Fmp4&ns=NUNx
EjQlPtMV1Fr0Evz7hckF&gir=yes&clen=506558397&dur=10828.516&lmt=1607011073921989&m
t=1607922779&fvip=5&keepalive=yes&c=WEB&txp=6316222&n=NY54pOh5s89DeGwym&sparams=
expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2C
clen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgfCtJAkE08GRCm_v79-EB745k_R-V_jyuVIBgEgfc6UoCIQC
_xkBMV0cGCQxO9QzcmLDrwp8ONAwFdKfSPOhxLKXQxQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cm
v%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhALSnufT7mwloQ8lXSYrBKqU-NlEdPrp-jKyD
eVLL6ddMAiAhRex1EZtj3AHJNX0jmEeuiumuJQjyOcd77DD0DN4B8g%3D%3D&ratebypass=yes'
[download] Resuming download at byte 360847799
[download] Destination: 12 Beginner Python Projects - Coding Course-8ext9G7xspg.
f136.mp4
[download] 100% of 483.09MiB in 03:32
[debug] Invoking downloader on 'https://r2---sn-gwpa-b506.googlevideo.com/videop
layback?expire=1607944696&ei=mPXWX5-uLfzg4-EPqayAkAY&ip=2405%3A201%3Aa409%3A9842
%3Ac40a%3A8433%3Af2d%3Aff2e&id=o-AHGCLs15LcpnNwPGhGmAr47SrW4MMdgg862YvPik9KwU&it
ag=140&source=youtube&requiressl=yes&mh=Fh&mm=31%2C29&mn=sn-gwpa-b506%2Csn-qxa7s
n7r&ms=au%2Crdu&mv=m&mvi=2&pl=39&initcwndbps=996250&vprv=1&mime=audio%2Fmp4&ns=N
UNxEjQlPtMV1Fr0Evz7hckF&gir=yes&clen=175249186&dur=10828.578&lmt=160701165505327
8&mt=1607922779&fvip=5&keepalive=yes&c=WEB&txp=6311222&n=NY54pOh5s89DeGwym&spara
ms=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2
Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgVqTEtHPu-8vpFnP_WkQTIx1e_3_i2k9lhBD3McPH2TQCIG
-RQHEPt-FJYdQDHSqSoG5jD8aVqINezdkNzycUnriP&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi
%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhALSnufT7mwloQ8lXSYrBKqU-NlEdPrp-jKyDeVLL6dd
MAiAhRex1EZtj3AHJNX0jmEeuiumuJQjyOcd77DD0DN4B8g%3D%3D&ratebypass=yes'
ERROR: unable to download video data: <urlopen error [WinError 10061] No connect
ion could be made because the target machine actively refused it>
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1279, in connect
  File "C:\Python\Python34\lib\http\client.py", line 871, in connect
  File "C:\Python\Python34\lib\socket.py", line 516, in create_connection
  File "C:\Python\Python34\lib\socket.py", line 507, in create_connection
ConnectionRefusedError: [WinError 10061] No connection could be made because the
 target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikk
p6\build\youtube_dl\YoutubeDL.py", line 1930, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikk
p6\build\youtube_dl\YoutubeDL.py", line 1875, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikk
p6\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikk
p6\build\youtube_dl\downloader\http.py", line 351, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikk
p6\build\youtube_dl\downloader\http.py", line 116, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikk
p6\build\youtube_dl\downloader\http.py", line 110, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikk
p6\build\youtube_dl\YoutubeDL.py", line 2248, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikk
p6\build\youtube_dl\utils.py", line 2736, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be ma
de because the target machine actively refused it>

```

## Description

WRITE DESCRIPTION HERE
I noticed that youtube-dl is unable to download file completely at once. I have to run command multiple time to download file. I would like to add that I have interrupted the download first time.
![1mO4cCwTKz](https://user-images.githubusercontent.com/75368279/102043970-d7b54980-3dfb-11eb-8739-09730509187f.png)

**Comment by dstftw** [comment]
Network issue on your side.
