### ISSUE TITLE
skysports.com "unsupported URL"

### ISSUE THREAD

**Issue by pshankland** [ytdl-org/youtube-dl#27435]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe -v -F https://www.skysports.com/watch/video/sports/f1/12160544/abu-dhabi-gp-the-notebook
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.skysports.com/watch/video/sports/f1/12160544/abu-dhabi-gp-the-notebook']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-essentials_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[generic] abu-dhabi-gp-the-notebook: Requesting header
WARNING: Could not send HEAD request to https://www.skysports.com/watch/video/sports/f1/12160544/abu-dhabi-gp-the-notebook: HTTP Error 404: Not Found
[generic] abu-dhabi-gp-the-notebook: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] abu-dhabi-gp-the-notebook: Extracting information
ERROR: Unsupported URL: https://www.skysports.com/watch/video/sports/f1/12160544/abu-dhabi-gp-the-notebook
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\extractor\generic.py", line 3418, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.skysports.com/watch/video/sports/f1/12160544/abu-dhabi-gp-the-notebook
```

## Description

Trying to download from the following site which is on skysports.com. Looking at the list of supported sites, this is on there but just get a "Unsupport URL" error.

https://www.skysports.com/watch/video/sports/f1/12160544/abu-dhabi-gp-the-notebook

**Comment by pshankland** [comment]
How do I use the new / modified file with the Windows EXE version of youtube-dl? Sorry for what is probably a stupid question but it looks as though you have fixed the problem I was having, just have no understanding on how to use that fix. Thanks.

**Comment by remitamine** [comment]
it will be included in the next version, for now you download this video using this command:
```
youtube-dl ooyala:Uxa3d1ajE6eiRRam5INxHN13TGsO0cJ6
```
