### ISSUE TITLE
[youtube] cannot download specific youtube video, but the rest of the channel's videos work

### ISSUE THREAD

**Issue by mechalincoln** [ytdl-org/youtube-dl#27436]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.12.14**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
Y:\youtube-dl>youtube-dl -v https://www.youtube.com/watch?v=6rgx3OR-Xu0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=6rgx3OR-Xu0']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] 6rgx3OR-Xu0: Downloading webpage
[youtube] 6rgx3OR-Xu0: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r5---sn-ab5l6n6l.googlevideo.com/videoplayback?expire=1607997518&ei=7sPXX_OWA438igTJ-IiwBA&ip=2601%3A246%3A100%3Aed%3A9582%3A65ae%3A8491%3A3c1e&id=o-ADRYxEAUNJv1G0TnSzRZ_PzUZX67Nz5Mlibn_RFZoJI2&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=yt_otf&requiressl=yes&mh=eX&mm=31%2C29&mn=sn-ab5l6n6l%2Csn-vgqs7nes&ms=au%2Crdu&mv=m&mvi=5&pl=26&pcm2=yes&initcwndbps=2555000&vprv=1&mime=video%2Fwebm&ns=Y0nByxtSAY3jHPXsdRoan7AF&otf=1&otfp=1&dur=1144.009&lmt=1489605219773214&mt=1607975580&fvip=5&keepalive=yes&beids=9466587&c=WEB&n=qIbE8PJRl1a-mhNPL&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cns%2Cotf%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAO25mWpXCDd47PQX8elzgAElOpGn84rOnUUI2q_9Uh4jAiEAuGvZpYsgfgFgN78OHFeX1svdrjohCVUO5VJ9fEQ14lA%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKzhLC1p-IrdTcqYefzjHKDcaPL2K2x6PgH5c82LRqlUAiEA2VDuH6ruL9vf9ChiEATD17_DiJwygXUWHFNyHpwuMKA%3D&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\YoutubeDL.py", line 1930, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\YoutubeDL.py", line 1875, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\downloader\http.py", line 351, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\downloader\http.py", line 116, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\downloader\http.py", line 110, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\YoutubeDL.py", line 2248, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

## Description

Hello. I have updated youtube-dl to the latest version (youtube-dl is up-to-date (2020.12.14)), and have looked for existing bugs similar to this one.

This concerns [one particular video](youtube.com/watch?v=6rgx3OR-Xu0) from the Vapor Memory channel; the rest of the channel works.

youtube-dl refuses to download the video, stating that it received a 404, but I can clearly see that the video works in Chrome, and that it is not private or location-locked. I even verified that the video was viewable in an incognito window.

I am using this on Windows 10 x64.

Please let me know if any further information is needed.

**Comment by october262** [comment]
has the specific video been deleted or is it a private video ??

**Comment by whamer100** [comment]
the link appears to have been broken in the OP, `https://www.youtube.com/watch?v=6rgx3OR-Xu0`

**Comment by october262** [comment]
try this -  youtube-dl https://www.youtube.com/watch?v=6rgx3OR-Xu0 -f 137+140
video will now download.

**Comment by mechalincoln** [comment]
That worked. Thank you for your help.

Was the URL malformed?

**Comment by dstftw** [comment]
Server side Youtube issue.
