### ISSUE TITLE
AVGN on youtube unsupported URL

### ISSUE THREAD

**Issue by linuxpng** [ytdl-org/youtube-dl#27437]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ /usr/local/bin/youtube-dl -v --playlist-reverse --playlist-end 15 --add-metadata --download-archive=/mnt/nas/Media/Youtube/.Downloaded -i -o "/mnt/nas/Media/Youtube/%(uploader)s [%(channel_id)s]/%(playlist_index)s - %(title)s [%(id)s].%(ext)s" -f best -ci --batch-file=/mnt/nas/Media/Youtube/channels --merge-output-format --write-info-json --write-thumbnail
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--playlist-reverse', u'--playlist-end', u'15', u'--add-metadata', u'--download-archive=/mnt/nas/Media/Youtube/.Downloaded', u'-i', u'-o', u'/mnt/nas/Media/Youtube/%(uploader)s [%(channel_id)s]/%(playlist_index)s - %(title)s [%(id)s].%(ext)s', u'-f', u'best', u'-ci', u'--batch-file=/mnt/nas/Media/Youtube/channels', u'--merge-output-format', u'--write-info-json', u'--write-thumbnail']
[debug] Batch file urls: [u'https://www.youtube.com/AngryNintendoNerd/videos']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.14
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-56-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[generic] videos: Requesting header
WARNING: Falling back on generic information extractor.
[generic] videos: Downloading webpage
[generic] videos: Extracting information
ERROR: Unsupported URL: https://www.youtube.com/AngryNintendoNerd/videos
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2428, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2562, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1, column 181
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3418, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.youtube.com/AngryNintendoNerd/videos
```

## Description

Trying to download from https://www.youtube.com/AngryNintendoNerd/videos generates an Unsupported URL error.

**Comment by october262** [comment]
downloading playlists works ok for me.
just click playlists - view full playlists - copy the URL 
and use it to download all the videos in the playlists.

**Comment by linuxpng** [comment]
The playlists do work, yes.  Other channels work via the video link such as https://www.youtube.com/c/tested/videos.  Of the channels I have tried (only about 10) this is the only one that failed.   It is a greedy ask, so I understand if it will not (or cannot) be fixed.

**Comment by linuxpng** [comment]
Ah, I actually misunderstood what you were say.  Apologies I'm new to youtube-dl and a casual youtube user.  I was able to get his full playlist working.  Marking resolved.
