### ISSUE TITLE
Youtube-dl not starting - Reporting missing lazy_extractors

### ISSUE THREAD

**Issue by glucini** [ytdl-org/youtube-dl#27449]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X ] I've verified that I'm running youtube-dl version **2020.12.14**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar bug reports including closed ones
- [ X] I've read bugs section in FAQ

## Verbose log

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/__init__.py", line 4, in <module>
    from .lazy_extractors import *
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 6, in <module>
    from youtube_dl import main
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/__init__.py", line 9, in <module>
    from .extractors import *
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/extractors.py", line 45, in <module>
    from .anvato import AnvatoIE
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/anvato.py", line 12, in <module>
    from .anvato_token_generator import NFLTokenGenerator
ModuleNotFoundError: No module named 'youtube_dl.extractor.anvato_token_generator'
```

## Description

WRITE DESCRIPTION HERE

**Comment by samoht0** [comment]
Broke with b34c9551aae2609c4ac3ee53cc7ce40e8f14d586
Release 2020.12.14 is not affected, just git packaged versions.
