### ISSUE TITLE
Downloading own "watch later" playlist fails

### ISSUE THREAD

**Issue by XZenon2000** [ytdl-org/youtube-dl#27447]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: ['-o', 'D:/name-pc/Users/user/Desktop/Misc/Musik, Videos/Zu Bearbeiten/YouTube Downloads/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/playlist?list=WL', '-v', '--cookies', 'C:\\Users\\user\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Cookies', '--username', 'PRIVATE']
Type account password and press [Return]:
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\__init__.py", line 441, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\YoutubeDL.py", line 419, in __init__
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\YoutubeDL.py", line 2339, in _setup_opener
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\utils.py", line 2831, in load
  File "C:\Python\Python34\lib\codecs.py", line 319, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 26: invalid start byte
```

## Description

 qwertz19281 commented in [this Reddit thread ](https://www.reddit.com/r/youtubedl/comments/csr9qf/youtube_watch_later/) that downloading your own "watch later" playlist through youtube-dl is possible by signing in to your YouTube Account and/or loading your cookies. Neither has worked for me thus far and doing both has yielded this result.

**Comment by dstftw** [comment]
Cookie file must be in UTF-8.
