### ISSUE TITLE
YouTube video download times out

### ISSUE THREAD

**Issue by jgrg** [ytdl-org/youtube-dl#27452]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: ['--restrict-filenames', '--no-overwrites', '--output', '%(title)s.%(ext)s', '--merge-output-format', 'mp4', '--format', '96/bestvideo[ext=mp4][width<=1920]+bestaudio[ext=m4a]/bestvideo[ext=mp4][width<=1920]+bestaudio[ext=aac]/best', '--write-thumbnail', '--write-info-json', '--sub-lang', 'en', '--convert-subs', 'srt', '--write-sub', '--embed-subs', '--all-subs']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=nQOroZNr_fw']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.8.6 (CPython) - macOS-10.13.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] nQOroZNr_fw: Downloading webpage
[info] Writing video subtitles to: The_Never-Used_Road_Where_The_BBC_Crash_Cars.en.vtt
[info] Writing video description metadata as JSON to: The_Never-Used_Road_Where_The_BBC_Crash_Cars.info.json
[youtube] nQOroZNr_fw: Downloading thumbnail ...
[youtube] nQOroZNr_fw: Writing thumbnail to: The_Never-Used_Road_Where_The_BBC_Crash_Cars.jpg
[debug] Invoking downloader on 'https://r1---sn-1xopouxgoxu-aige.googlevideo.com/videoplayback?expire=1608142483&ei=M_rZX-TWDMHW1gb4u624Cw&ip=2a02%3A8010%3A63c7%3A1%3A0%3A0%3A0%3A2121&id=o-AOZq9mDtyZ935IloQS0Amyrt-Z7kp-Ni6ubvYYO_Q00Q&itag=299&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C308%2C315&source=youtube&requiressl=yes&mh=bI&mm=31%2C29&mn=sn-1xopouxgoxu-aige%2Csn-aigzrn7s&ms=au%2Crdu&mv=m&mvi=1&pl=29&initcwndbps=1191250&vprv=1&mime=video%2Fmp4&ns=TL0y8UvouVX2q2jxVdozhJsF&gir=yes&clen=115938707&dur=165.031&lmt=1608016132352072&mt=1608120522&fvip=1&keepalive=yes&beids=9466587&c=WEB&txp=5532434&n=1puHuc0yAFs2C_-9N&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgKJ2ukKWekPac0BT4OxPVcYewHQqZBqUTBPcy64bnLDQCIQCrCf_xQqwjsabVZ-nqec3oyS3k7-HR3lBxyrlI5dOmjQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAPQE_bFPm_vzUUFvPOV0khQ_EaGEuSLEnoYSB_txeQq0AiAbnqLlvZp-TgsCdKrb1ezFsziQwno6n9lCGc7uOPZOyg%3D%3D&ratebypass=yes'
ERROR: unable to download video data: <urlopen error [Errno 60] Operation timed out>
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1417, in connect
    super().connect()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jgrg/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1930, in process_info
    partial_success = dl(fname, new_info)
  File "/Users/jgrg/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1875, in dl
    return fd.download(name, info)
  File "/Users/jgrg/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/Users/jgrg/bin/youtube-dl/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/Users/jgrg/bin/youtube-dl/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
  File "/Users/jgrg/bin/youtube-dl/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/Users/jgrg/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2248, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Users/jgrg/bin/youtube-dl/youtube_dl/utils.py", line 2734, in https_open
    return self.do_open(functools.partial(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>

```

## Description

Today I find that I cannot download any video from YouTube - they all timeout. The video in my example (nQOroZNr_fw) plays fine in my browser, and youtube-dl successfully downloaded it yesterday.

**Comment by dstftw** [comment]
Network issue, nothing to do with youtube-dl.

**Comment by irk3n-dev** [comment]
Try this: "youtube-dl --retries infinite --no-check-certificate --prefer-insecure [URL]"
