### ISSUE TITLE
Atresplayer: Login error

### ISSUE THREAD

**Issue by heroku-miraheze** [ytdl-org/youtube-dl#27467]
## Checklist

- [y] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2020.12.14**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\youtube-dl.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\youtube_dl\__init__.py", line 474, in main
    _real_main(argv)
  File "c:\python39\lib\site-packages\youtube_dl\__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "c:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2028, in download
    res = self.extract_info(
  File "c:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "c:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "c:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "c:\python39\lib\site-packages\youtube_dl\extractor\common.py", line 531, in extract
    self.initialize()
  File "c:\python39\lib\site-packages\youtube_dl\extractor\common.py", line 435, in initialize
    self._real_initialize()
  File "c:\python39\lib\site-packages\youtube_dl\extractor\atresplayer.py", line 45, in _real_initialize
    self._login()
  File "c:\python39\lib\site-packages\youtube_dl\extractor\atresplayer.py", line 75, in _login
    self._request_webpage(target_url, None, 'Following Target URL')
  File "c:\python39\lib\site-packages\youtube_dl\extractor\common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2247, in urlopen
    req = sanitized_Request(req)
  File "c:\python39\lib\site-packages\youtube_dl\utils.py", line 2157, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "c:\python39\lib\urllib\request.py", line 320, in __init__
    self.full_url = url
  File "c:\python39\lib\urllib\request.py", line 346, in full_url
    self._parse()
  File "c:\python39\lib\urllib\request.py", line 375, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/api/oauth/authorize?client_id=atresplayer&redirect_uri=https%3A%2F%2Fapi.atresplayer.com%2FauthCallback&response_type=code&scope=openid&state=4G06VP'
```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by mmoya** [comment]
It still happens with version 2021.03.14.

**Comment by mmoya** [comment]
Duplicate of #24462.
