### ISSUE TITLE
[francetv] Not found m3u8 information

### ISSUE THREAD

**Issue by Titome** [ytdl-org/youtube-dl#27468]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.12.14**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
timothee@arch-game ~/video [1]> youtube-dl -vvv https://www.france.tv/documentaires/science-sante/2128331-titanic-au-coeur-de-l-epave.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vvv', 'https://www.france.tv/documentaires/science-sante/2128331-titanic-au-coeur-de-l-epave.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.9.1 (CPython) - Linux-5.9.14-arch1-1-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[FranceTVSite] 2128331-titanic-au-coeur-de-l-epave: Downloading webpage
[FranceTV] 122aebff-8cd9-4cf3-8c6d-6ffe21e4de3b: Downloading video JSON
[FranceTV] 122aebff-8cd9-4cf3-8c6d-6ffe21e4de3b: Downloading geo restriction info
[FranceTV] 122aebff-8cd9-4cf3-8c6d-6ffe21e4de3b: Downloading signed m3u8-download manifest URL
[FranceTV] 122aebff-8cd9-4cf3-8c6d-6ffe21e4de3b: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 503: Service Unavailable
[FranceTV] 122aebff-8cd9-4cf3-8c6d-6ffe21e4de3b: Downloading signed hls_v5_os manifest URL
[FranceTV] 122aebff-8cd9-4cf3-8c6d-6ffe21e4de3b: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 503: Service Unavailable
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py", line 234, in _real_extract
    return self._extract_video(video_id, catalog)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py", line 194, in _extract_video
    self._sort_formats(formats)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1367, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Hi ! I have trouble to download this video : https://www.france.tv/documentaires/science-sante/2128331-titanic-au-coeur-de-l-epave.html
youtube-dl seem to looking for m3u8 file but if I check the request network in my web-browser I see a dash file (see screenshot).

![tmp](https://user-images.githubusercontent.com/748679/102552316-4aa31680-40c1-11eb-9119-c7733f90f0a4.png)

Thanks for your help & thanks for your work :)

**Comment by Titome** [comment]
I will try to download & now it's work ! May be m3u8 file is not available short time the broadcasting & available after several hours...
