### ISSUE TITLE
Youtube-dl not working on british ITV

### ISSUE THREAD

**Issue by JoeBlackX** [ytdl-org/youtube-dl#27465]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.12.14**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe --verbose https://www.itv.com/hub/dinner-date/1a8783a0274
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.itv.com/hub/dinner-date/1a8783a0274']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2019-11-08-e700038
[debug] Proxy map: {}
[debug] Using fake IP 25.214.11.71 (GB) as X-Forwarded-For.
[ITV] 1a8783a0274: Downloading webpage
[ITV] 1a8783a0274: Downloading JSON metadata
[ITV] 1a8783a0274: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\extractor\itv.py", line 115, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\extractor\common.py", line 1367, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Download from ITV (https://www.itv.com) no longer possible. A few months ago it went without any problems. Download from Germany also had no problems (Geo restrictions)

**Comment by remitamine** [comment]
nothing to do with `youtube-dl`, ITV serves the HLS manifest and segments from different CDNs, for me when the manifest is served from:
`itvpnpdotcom.content.itv.com` works fine(Akamai).
`itvpnpdotcom.cdn1.content.itv.com` fails for whatever reason(Amazon S3).

**Comment by emdubya77** [comment]
@JoeBlackX just keep trying, over and over again - it'll work eventually.
