### ISSUE TITLE
swf doesnt reconized

### ISSUE THREAD

**Issue by thel0** [ytdl-org/youtube-dl#27489]
## Checklist

- [X ] I'm asking a question
- [X ] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, i try to save a old swf video on my pc .
$ ./youtube-dl -v http://unf3s.cerimes.fr/media/paces/Grenoble_1112/lunardi_joel/lunardi_joel_p04/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://unf3s.cerimes.fr/media/paces/Grenoble_1112/lunardi_joel/lunardi_joel_p04/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.14
[debug] Python version 2.7.16 (CPython) - Linux-5.4.41-1-pve-x86_64-with-debian-10.7
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] lunardi_joel_p04: Requesting header
WARNING: Falling back on generic information extractor.
[generic] lunardi_joel_p04: Downloading webpage
[generic] lunardi_joel_p04: Extracting information
ERROR: Unsupported URL: http://unf3s.cerimes.fr/media/paces/Grenoble_1112/lunardi_joel/lunardi_joel_p04/
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 2428, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "./youtube-dl/youtube_dl/compat.py", line 2562, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "./youtube-dl/youtube_dl/compat.py", line 2551, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: mismatched tag: line 36, column 3
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 3418, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://unf3s.cerimes.fr/media/paces/Grenoble_1112/lunardi_joel/lunardi_joel_p04/

youtube-dl said unsupported url. Why does it not download flash video on this url ?

thanks for your help

**Comment by dstftw** [comment]
This is not a video in the first place.
