### ISSUE TITLE
pornhub download error

### ISSUE THREAD

**Issue by SeeleLink** [ytdl-org/youtube-dl#27505]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--proxy', 'socks5://127.0.0.1:1080/', 'https://cn.pornhub.com/model/sexdeti']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2020.12.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {'http': 'socks5://127.0.0.1:1080/', 'https': 'socks5://127.0.0.1:1080/'}
[PornHubPagedVideoList] model/sexdeti/videos: Downloading page 1
[download] Downloading playlist: model/sexdeti/videos
[PornHubPagedVideoList] playlist model/sexdeti/videos: Collected 37 video ids (downloading 37 of them)
[download] Downloading video 1 of 37
[PornHub] ph5fceabef929ce: Downloading pc webpage
[PornHub] ph5fceabef929ce: Downloading tv webpage
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmprhhzjl7r\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmprhhzjl7r\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmprhhzjl7r\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmprhhzjl7r\build\youtube_dl\extractor\pornhub.py", line 307, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmprhhzjl7r\build\youtube_dl\extractor\pornhub.py", line 254, in extract_js_vars
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmprhhzjl7r\build\youtube_dl\extractor\common.py", line 1010, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

**Comment by dstftw** [comment]
Premium content.
