### ISSUE TITLE
Sveriges Radio article URL broken

### ISSUE THREAD

**Issue by robalni** [ytdl-org/youtube-dl#27510]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.22**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://sverigesradio.se/artikel/7632995']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.22
[debug] Python version 3.9.1 (CPython) - Linux-5.9.0-5-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.1-5, ffprobe 4.3.1-5
[debug] Proxy map: {}
[generic] 7632995: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 7632995: Downloading webpage
[generic] 7632995: Extracting information
ERROR: Unsupported URL: https://sverigesradio.se/artikel/7632995
Traceback (most recent call last):
  File "/home/a/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/home/a/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/home/a/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/a/.local/lib/python3.9/site-packages/youtube_dl/extractor/generic.py", line 3446, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://sverigesradio.se/artikel/7632995

```

## Description

Sveriges Radio is using a new URL format:

New format: https://sverigesradio.se/artikel/7632888

This new format is unrecognized by youtube-dl. The old format still works with youtube-dl but it seems to not be used anymore on the website.

Old format: https://sverigesradio.se/sida/artikel.aspx?programid=83&artikel=7632888

So all that needs to be done is to extract the article number from the new URL format and then play it the same way as is currently done.

**Comment by october262** [comment]
for this link - https://sverigesradio.se/artikel/7632888  play the  radio audio file
and press F 12  on your keyboard to bring up the debug menu, select network - media
and wait for the program to show, copy the link and feed it into youtube-dl  to download the program.

**Comment by to-duck** [comment]
There are other new URL formats as well, for example:
https://sverigesradio.se/avsnitt/radioapans-godnattkvart-26-december
