### ISSUE TITLE
VHX/Vimeo sites no longer working

### ISSUE THREAD

**Issue by spoonys** [ytdl-org/youtube-dl#27546]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
<!--
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://embed.vhx.tv/videos/532213?api=1&auth-user-token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMzkwNDYyMiwiZXhwIjoxNjA5MDM2NDkxfQ.9N9yZ5zN3LHGYaHyPgC8Tn2ywQcimkEODDZ4LVHWKF0'
]
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.26
[debug] Python version 3.6.9 (CPython) - Linux-5.4.0-1029-gcp-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[vhx:embed] 532213: Downloading webpage
ERROR: Unable to extract ott data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the
 --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/vimeo.py", line 1127, in _real_extract
    'ott data'), video_id, js_to_json)['config_url']
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract ott data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be su
re to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I used to use youtube-dl for these types of VHX/vimeo sites - however I can't seem to get them working anymore. Any thoughts?

**Comment by llacb47** [comment]
Link that won't expire: `https://embed.vhx.tv/videos/725881`

**Comment by remitamine** [comment]
> It seems easy to extract the iframe url from the video page:

generic support VHX Embeds will be added in the next version.

**Comment by llacb47** [comment]
`https://embed.vhx.tv/videos/1218381` doesn't work on latest release. @remitamine

**Comment by remitamine** [comment]
@llacb47 Adding `&vimeo=1` for all URLs might break the extraction for other URLs, and the website that i've been testing on previously for non public content has switched to another platform(IndieFlix no longer uses VHX).

**Comment by githubarooski** [comment]
For anyone that makes it here and is scratching their head about this, the VHX VoD works in yt-dlp, but you do have to paste the entire long string from the embed source

ie
```
$ yt-dlp -Uv --cookies vhx.tv_cookies.txt -v 'https://embed.vhx.tv/videos/923926?api=1&autoplay=1&back=xxxxxxxxxxxxx&collection_id=162241&color=3b6691&context=yaddayaddayadda'
``` 

tested on Ubuntu 20 on WSL2.0
yt-dlp is up to date (2021.11.10.1)
