### ISSUE TITLE
media.ccc.de extractor broken

### ISSUE THREAD

**Issue by kennell** [ytdl-org/youtube-dl#27558]
- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.12.26**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\k\Downloads>youtube-dl --verbose https://media.ccc.de/v/rc3-11512-cia_vs_wikileaks
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://media.ccc.de/v/rc3-11512-cia_vs_wikileaks']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.12.26
[debug] Python version 3.8.3 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.3
[debug] Proxy map: {}
[media.ccc.de] rc3-11512-cia_vs_wikileaks: Downloading webpage
ERROR: Unable to extract event id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\k\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\k\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\k\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\k\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\ccc.py", line 40, in _real_extract
    event_id = self._search_regex(r"data-id='(\d+)'", webpage, 'event id')
  File "c:\users\k\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract event id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Extraction fails

**Comment by evilpie** [comment]
Maybe something changed since yesterday, because this works for me.

**Comment by remitamine** [comment]
```
youtube-dl https://media.ccc.de/v/rc3-11512-cia_vs_wikileaks
[media.ccc.de] rc3-11512-cia_vs_wikileaks: Downloading webpage
[media.ccc.de] 9186: Downloading JSON metadata
[download] Destination: CIA vs. Wikileaks-9186.webm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  209M    0 98268    0     0  25623      0  2:23:00  0:00:03  2:22:57 33031
```

**Comment by tmulzer** [comment]
Can reproduce on recent manjaro with updated youtube-dl .. right now:
```
youtube-dl --verbose https://media.ccc.de/v/rc3-11360-careables
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://media.ccc.de/v/rc3-11360-careables']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.9.1 (CPython) - Linux-5.10.2-2-MANJARO-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[media.ccc.de] rc3-11360-careables: Downloading webpage
ERROR: Unable to extract event id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/ccc.py", line 40, in _real_extract
    event_id = self._search_regex(r"data-id='(\d+)'", webpage, 'event id')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract event id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by tmulzer** [comment]
Well - I dived into it a bit .. seems, that the videos in the relive-area, of which there are no final recordings relased, don't have the data-id value - and therefore no event-id can be pulled insid the _real_extract function.

Solution could be to get that value e.g. from the second comma separated field inside the "meta content" header.. or to just simply wait until the final recording is released.
