### ISSUE TITLE
support posts with multiple videos on sxyprn.com

### ISSUE THREAD

**Issue by schn0sch** [ytdl-org/youtube-dl#27554]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vo', '/dev/null', 'https://sxyprn.com/post/5af15f6799de9.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.12
[debug] Lazy loading extractors enabled
[debug] Git HEAD: 222c704
[debug] Python version 3.8.5 (CPython) - Linux-5.9.14-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[YourPorn] 5af15f6799de9: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('5af15f6799de9')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/nix/store/5kz4xxh3l3pvjza4vaynp4k0rnpsjh6d-python3.8-youtube-dl-2020.12.12/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/nix/store/5kz4xxh3l3pvjza4vaynp4k0rnpsjh6d-python3.8-youtube-dl-2020.12.12/lib/python3.8/site-packages/youtube_dl/extractor/yourporn.py", line 37, in _real_extract
    parts = self._parse_json(
KeyError: '5af15f6799de9'
Traceback (most recent call last):
  File "/nix/store/5kz4xxh3l3pvjza4vaynp4k0rnpsjh6d-python3.8-youtube-dl-2020.12.12/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/nix/store/5kz4xxh3l3pvjza4vaynp4k0rnpsjh6d-python3.8-youtube-dl-2020.12.12/lib/python3.8/site-packages/youtube_dl/extractor/yourporn.py", line 37, in _real_extract
    parts = self._parse_json(
KeyError: '5af15f6799de9'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/5kz4xxh3l3pvjza4vaynp4k0rnpsjh6d-python3.8-youtube-dl-2020.12.12/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/nix/store/5kz4xxh3l3pvjza4vaynp4k0rnpsjh6d-python3.8-youtube-dl-2020.12.12/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/nix/store/5kz4xxh3l3pvjza4vaynp4k0rnpsjh6d-python3.8-youtube-dl-2020.12.12/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 545, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('5af15f6799de9')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Posts containing multiple videos are not supported.

**Comment by doubledave04** [comment]
Is there a way to download all videos with a search tag? Like all 1349 vids here:?
https://sxyprn.com/VrSmartphone.html

Thanks!

**Comment by schn0sch** [comment]
@doubledave04
I added rudimentary support for that [here](https://github.com/ytdl-org/youtube-dl/compare/master...schn0sch:yourporn-search) but it's not polished enough for a pull request.
