### ISSUE TITLE
SunPorno 403 Error

### ISSUE THREAD

**Issue by TheGrimKeeper** [ytdl-org/youtube-dl#27579]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.29**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v https://www.sunporno.com/videos/1339244/brunette-babe-stephanie-moretti-is-repeatedly-fucked-like-a-whore
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.sunporno.com/videos/1339244/brunette-babe-stephanie-moretti-is-repeatedly-fucked-like-a-whore']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.29
[debug] Python version 2.7.18 (CPython) - Linux-5.8.0-7630-generic-x86_64-with-Pop-20.10-groovy
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[SunPorno] 1339244: Downloading webpage
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://stream.sunporno.com/key=oWv2m7-51pJQQeIkXIsauA,end=1609305173/sec=sk_hl/speed=76717/480x320_600k_h264_2380623.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1936, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1875, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
HTTPError: HTTP Error 403: Forbidden
```

## Description

Getting a 403 Forbidden error on SunPorno.  Other examples are:

https://www.sunporno.com/videos/558358/naughty-rich-girl-britney-beth
https://www.sunporno.com/videos/1036018/assassins-bibi-jone-jesse-jane-scene-5

**Comment by TheGrimKeeper** [comment]
Just as an update, if you use --referer="https://sunporno.com" the download seems to work.  Still throws an unable to extract description warning, so work is needed on this extractor, but the main problem may not be so serious.
