### ISSUE TITLE
Error while downloading video playlist from youtube.com

### ISSUE THREAD

**Issue by harbhim** [ytdl-org/youtube-dl#27571]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.29**
- [x] I've checked that all provided http://yt-dl.org/search-issuesURLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
F:\New folder>youtube-dl -o "%(playlist_index)s-%(title)s.%(ext)s" -a aa.txt --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', '%(playlist_index)s-%(title)s.%(ext)s', '-a', 'aa.txt', '--verbose']
[debug] Batch file urls: ['https://www.youtube.com/playlist?list=PL_7viLFyJ7sDGXtD_ukhQRq_z00ROt1WS']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.12.29
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 2020-12-12-git-5148740e79-full_build-www.gyan.dev, ffprobe 2020-12-12-git-5148740e79-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube:tab] PL_7viLFyJ7sDGXtD_ukhQRq_z00ROt1WS: Downloading webpage
[download] Downloading playlist: GIMP 2.10 Tutorials
[youtube:tab] Downloading page 1
[youtube:tab] playlist GIMP 2.10 Tutorials: Downloading 191 videos
[download] Downloading video 1 of 191
[youtube] GSsqrRXF578: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] 001-5 Hidden GIMP Tricks I LOVE for 2020.mkv has already been downloaded and merged
[download] Downloading video 2 of 191
[youtube] dvWoQ8_HhBI: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] 002-GIMP Layers and Layer Masks 2020 _ In-Depth GIMP Basics Tutorial.mkv has already been downloaded and merged
[download] Downloading video 3 of 191
[youtube] iXG5x7ilDlU: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] 003-How to Animate a Still Photo with GIMP.mkv has already been downloaded and merged
[download] Downloading video 4 of 191
[youtube] KRHwyLcutyE: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] 004-GIMP Quick Mask In-Depth Tutorial.mkv has already been downloaded and merged
[download] Downloading video 5 of 191
[youtube] dY7g2JGyJeQ: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] 005-Make GIMP 2.10 Look Like Photoshop CC 2020.mkv has already been downloaded and merged
[download] Downloading video 6 of 191
[youtube] -NkZ-2PY8a4: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] 006-GIMP vs Inkscape - Which Should You Use A Beginner's Guide.mkv has already been downloaded and merged
[download] Downloading video 7 of 191
[youtube] 2EPIUyFJ4ag: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] 007-GIMP 2.10 Basics - Complete Overview Tutorial for Beginners.mkv has already been downloaded and merged
[download] Downloading video 8 of 191
[youtube] st_mENbhGUk: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] 008-GIMP 2.10 Tutorial - Top 10 New Features.webm has already been downloaded and merged
[download] Downloading video 9 of 191
[youtube] R0Sk755osjg: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] 009-How to Open RAW Images in GIMP 2.10.mkv has already been downloaded and merged
[download] Downloading video 10 of 191
[youtube] b_q8h0Z8iEk: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] 010-How to Edit Like Brandon Woelfel in GIMP 2.10.webm has already been downloaded and merged
[download] Downloading video 11 of 191
[youtube] 2X1c4zDAgCk: Downloading webpage
[youtube] 2X1c4zDAgCk: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] 011-GIMP 2.10 Tutorial - Improve Exposure with Shadow Recovery.webm has already been downloaded and merged
[download] Downloading video 12 of 191
[youtube] oxUMtv07Sys: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] 012-GIMP Tutorial - 5 Things You Didn't Know GIMP Could Do.mkv has already been downloaded and merged
[download] Downloading video 13 of 191
[youtube] 3Izcmh1ZB4U: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] 013-GIMP 2.10 Photography Tutorial - Using Luminosity Masks  to Fix Dark Objects.webm has already been downloaded and merged
[download] Downloading video 14 of 191
[youtube] WcnEvjbwU8Q: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] 014-'Is GIMP a Complete Alternative to Photoshop' Your GIMP Questions Answered.webm has already been downloaded and merged
[download] Downloading video 15 of 191
[youtube] 2yhn5q2jTWM: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] 015-How to Design a Bi-fold Brochure (A3) in GIMP 2.10.mkv has already been downloaded and merged
[download] Downloading video 16 of 191
[youtube] aEsqVMCgpJ8: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] 016-GIMP Tutorial - Why GEGL is the Future of GIMP.mkv has already been downloaded and merged
[download] Downloading video 17 of 191
[youtube] V8QE8u2gDJk: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] 017-GIMP 2.10 Tutorial - Design a Business Card for Print.webm has already been downloaded and merged
[download] Downloading video 18 of 191
[youtube] WsKZTUd5w-o: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] 018-What's New in GIMP 2.10.2.mkv has already been downloaded and merged
[download] Downloading video 19 of 191
[youtube] 3ZymFyAdn0I: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] 019-GIMP 2.10 Tutorial - Stunning Portrait Brush Effects.webm has already been downloaded and merged
[download] Downloading video 20 of 191
[youtube] G4AOLbDmp9k: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] 020-GIMP 2.10 Tutorial - How to Color Grade Using Gradient Maps.webm has already been downloaded and merged
[download] Downloading video 21 of 191
[youtube] m_Q2avUQQPk: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] 021-Design and Export a Multi-Page PDF in GIMP 2.10.webm has already been downloaded and merged
[download] Downloading video 22 of 191
[youtube] rc42DyGiDJQ: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] 022-Fix Dark and Grainy Night Photos with GIMP 2.10 + Darktable.webm has already been downloaded and merged
[download] Downloading video 23 of 191
[youtube] XWSbNUCfbrk: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] 023-What's New in GIMP 2.10.4.webm has already been downloaded and merged
[download] Downloading video 24 of 191
[youtube] Mpbp1d0JJc4: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] 024-GIMP vs. Photoshop - 10 Photoshop CC Features Found in GIMP 2.10.mkv has already been downloaded and merged
[download] Downloading video 25 of 191
[youtube] Pc-bVlKbmQI: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] 025-GIMP 2.10 Tutorial - Glass Window Reflection (Beginners).webm has already been downloaded and merged
[download] Downloading video 26 of 191
[youtube] m39szwBRcsc: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] 026-GIMP 2.10 Tutorial - 3D Shapes Photo Manipulation.webm has already been downloaded and merged
[download] Downloading video 27 of 191
[youtube] 2_DAfak_x98: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] 027-GIMP 2.10 Tutorial - Make Cell Phone Photos Look Professional.mkv has already been downloaded and merged
[download] Downloading video 28 of 191
[youtube] MpzIBMl6DSk: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] 028-GIMP 2.10 Tutorial - Create Photographic Text.webm has already been downloaded and merged
[download] Downloading video 29 of 191
[youtube] hEF3spB6v50: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] 029-GIMP 2.10 Tutorial - How to Design a Magazine Cover.mkv has already been downloaded and merged
[download] Downloading video 30 of 191
[youtube] xGqKJWRMnh4: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] 030-Stitch Panoramic Images with GIMP 2.10 (Two Methods).webm has already been downloaded and merged
[download] Downloading video 31 of 191
[youtube] gpCuGDSbI9E: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] 031-How to Replace the Sky in Images Using GIMP.webm has already been downloaded and merged
[download] Downloading video 32 of 191
[youtube] 1Zigo9gTzL8: Downloading webpage
[youtube] 1Zigo9gTzL8: Downloading embed webpage
[youtube] 1Zigo9gTzL8: Refetching age-gated info webpage
WARNING: Unable to extract video title
ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp581_vk6o\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp581_vk6o\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp581_vk6o\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp581_vk6o\build\youtube_dl\extractor\youtube.py", line 2076, in _real_extract
youtube_dl.utils.ExtractorError: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 

```

## Description

Trying to download youtube playlist, the link is    :    https://www.youtube.com/playlist?list=PL_7viLFyJ7sDGXtD_ukhQRq_z00ROt1WS
using this command,
~~~
youtube-dl -o "%(playlist_index)s-%(title)s.%(ext)s" -a aa.txt
~~~
But it gives an error on 32nd video as shown in verbose output.

**Comment by dstftw** [comment]
Video 32 has restricted access.
