### ISSUE TITLE
Max Download Reached Exits Python Program.

### ISSUE THREAD

**Issue by rbretmounet** [ytdl-org/youtube-dl#27570]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.29**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
[youtube:tab] PLjTI-fmjC4hWzJWz4_GTx1OzU8IZPUpfO: Downloading webpage
[download] Downloading playlist: Movie Clips
[youtube:tab] Downloading page 1
[youtube:tab] playlist Movie Clips: Downloading 192 videos
[download] Downloading video 1 of 192
[download] Sing (2016) - Shake It Off Scene (6/10) | Movieclips has already been recorded in archive
[download] Downloading video 2 of 192
[download] Despicable Me 2 (9/10) Movie CLIP - The Purple Minion Attacks (2013) HD has already been recorded in archive
[download] Downloading video 3 of 192
[download] Despicable Me 2 (10/10) Movie CLIP - Battling the Minions (2013) HD has already been recorded in archive
[download] Downloading video 4 of 192
[download] Despicable Me 2 (8/10) Movie CLIP - Worst Date Ever (2013) HD has already been recorded in archive
[download] Downloading video 5 of 192
[download] Despicable Me 2 (7/10) Movie CLIP - Margo In Love (2013) HD has already been recorded in archive
[download] Downloading video 6 of 192
[download] Despicable Me 2 (1/10) Movie CLIP - The Most Magical Fairy Princess (2013) HD has already been recorded in archive
[download] Downloading video 7 of 192
[download] Despicable Me 2 (4/10) Movie CLIP - A Minion in Love (2013) HD has already been recorded in archive
[download] Downloading video 8 of 192
[download] Fast & Furious 6 (8/10) Movie CLIP - Dom Saves Letty (2013) HD has already been recorded in archive
[download] Downloading video 9 of 192
[download] Full Frontal (7/8) Movie CLIP - Happy Ending (2002) HD has already been recorded in archive
[download] Downloading video 10 of 192
[download] Fast Five (4/10) Movie CLIP - A Woman's Job (2011) HD has already been recorded in archive
[download] Downloading video 11 of 192
[youtube] TIbZNmvyLBI: Downloading webpage
[18532:23840:1229/002903.219:ERROR:device_event_log_impl.cc(211)] [00:29:03.219] Bluetooth: bluetooth_adapter_winrt.cc:1073 Getting Default Adapter failed.
[download] Destination: raw_videos\Fast Five (5_10) Movie CLIP - You're Under Arrest (2011) HD.mp4
[download] 100% of 7.58MiB in 00:00
[download] Downloading video 12 of 192
[youtube] k2PsfXZ3wyY: Downloading webpage
[download] Destination: raw_videos\Fast Five (7_10) Movie CLIP - Hobbs vs. Toretto (2011) HD.mp4
[download] 100% of 12.22MiB in 00:00
[download] Downloading video 13 of 192
[youtube] uzHwlt3dmmo: Downloading webpage
[download] Destination: raw_videos\Fast & Furious 6 (7_10) Movie CLIP - They Got a Tank (2013) HD.mp4
[download] 100% of 14.21MiB in 00:01
[download] Downloading video 14 of 192
[youtube] xEAsC8A1Ins: Downloading webpage
[download] Destination: raw_videos\Fast Five (10_10) Movie CLIP - The Bridge Showdown (2011) HD.mp4
[download] 100% of 16.29MiB in 00:00
[download] Downloading video 15 of 192
[youtube] gN1BjYlhKvc: Downloading webpage
[download] Destination: raw_videos\Fast Five (6_10) Movie CLIP - Million Dollar Race (2011) HD.mp4
[download] 100% of 12.59MiB in 00:00
[download] Downloading video 16 of 192
[youtube] 9aldDI2WF7g: Downloading webpage
[download] Destination: raw_videos\Fast Five (8_10) Movie CLIP - Street Ambush (2011) HD.mp4
[download] 100% of 16.71MiB in 00:00
[download] Downloading video 17 of 192
[youtube] frE9rXnaHpE: Downloading webpage
[download] Destination: raw_videos\Ben-Hur (3_10) Movie CLIP - The Chariot Race (1959) HD.mp4
[download] 100% of 47.96MiB in 00:01
[download] Downloading video 18 of 192
[youtube] km3VtR6mqmg: Downloading webpage
[download] Destination: raw_videos\Fast & Furious 6 (9_10) Movie CLIP - Boarding the Plane (2013) HD.mp4
[download] 100% of 23.36MiB in 00:01
[download] Downloading video 19 of 192
[youtube] Atb5LNPuxyU: Downloading webpage
[download] Destination: raw_videos\Fast & Furious 6 (10_10) Movie CLIP - The End of Owen Shaw (2013) HD.mp4
[download] 100% of 15.55MiB in 00:00
[download] Downloading video 20 of 192
[youtube] 4lNoSUurdKc: Downloading webpage
[download] Destination: raw_videos\Despicable Me 2 (5_10) Movie CLIP - That Pollo is Loco (2013) HD.mp4
[download] 100% of 15.97MiB in 00:00
[download] Downloading video 21 of 192
[youtube] vmm8P0V1W4g: Downloading webpage
[info] Maximum number of downloaded files reached.
Traceback (most recent call last):
  File "C:\Users\rbret\Documents\GitHub\Downloader\upload.py", line 149, in <module>
    download_new_videos()
  File "C:\Users\rbret\Documents\GitHub\Downloader\upload.py", line 68, in download_new_videos
    ydl.download(["https://www.youtube.com/playlist?list=PLjTI-fmjC4hWzJWz4_GTx1OzU8IZPUpfO"])
  File "C:\Users\rbret\AppData\Local\Programs\Python\Python39-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2028, in download
    res = self.extract_info(
  File "C:\Users\rbret\AppData\Local\Programs\Python\Python39-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\rbret\AppData\Local\Programs\Python\Python39-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\rbret\AppData\Local\Programs\Python\Python39-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 835, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\rbret\AppData\Local\Programs\Python\Python39-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1012, in process_ie_result
    entry_result = self.__process_iterable_entry(entry, download, extra)
  File "C:\Users\rbret\AppData\Local\Programs\Python\Python39-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\rbret\AppData\Local\Programs\Python\Python39-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1044, in __process_iterable_entry
    return self.process_ie_result(
  File "C:\Users\rbret\AppData\Local\Programs\Python\Python39-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 906, in process_ie_result
    return self.process_ie_result(
  File "C:\Users\rbret\AppData\Local\Programs\Python\Python39-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 869, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\rbret\AppData\Local\Programs\Python\Python39-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1654, in process_video_result
    self.process_info(new_info)
  File "C:\Users\rbret\AppData\Local\Programs\Python\Python39-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1746, in process_info
    raise MaxDownloadsReached()
youtube_dl.utils.MaxDownloadsReached
```

## Description

I'm using the python library for youtube-dl and I've specified max_downloads in the ydl_opts. The problem I'm having is that after the max download has been reached the program exits with a traceback error. I would like to continue the program after the max download has been reached and I'm not sure how to do that. Thanks

**Comment by dstftw** [comment]
Catch the exception obviously.
