### ISSUE TITLE
List index out of range error

### ISSUE THREAD

**Issue by offta** [ytdl-org/youtube-dl#27597]
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

Verbose Log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', "'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4'", 'ooyala:6Lerp2kUAAAAABYscFaWwboSP3DaaFwY9TjZOR26']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.12.31
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[Ooyala] 6Lerp2kUAAAAABYscFaWwboSP3DaaFwY9TjZOR26: Downloading JSON metadata
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\YoutubeDL.py", line 2029, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\extractor\ooyala.py", line 173, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\extractor\ooyala.py", line 28, in _extract
IndexError: list index out of range

## Description

I am trying to download a video from NRL.com and I get a liste index out of range error

**Comment by remitamine** [comment]
you should use the website URL.

**Comment by offta** [comment]
C:\Users\zachd\Desktop\youtube-dl>youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4' https://www.nrl.com/tv/matches/holden-state-of-origin/2005/game-2/full-match-replay-blues-v-maroons---game-2-2005/
[NRLTV] full-match-replay-blues-v-maroons---game-2-2005: Downloading webpage
ERROR: Unable to extract player data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by remitamine** [comment]
it looks like the website support is broked, there already an open issue related to this problem.

**Comment by offta** [comment]
That is unfortunate, thank you for your time
