### ISSUE TITLE
[yandexvideo] unsupported operand type(s)

### ISSUE THREAD

**Issue by goonis** [ytdl-org/youtube-dl#27598]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

D:\youtube-dl>youtube-dl -v "https://yandex.ru/efir?stream_active=watching&stream_id=4ea3690321e7c8468f048e45868acb4e&from_block=efir_newtab"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://yandex.ru/efir?stream_active=watching&stream_id=4ea3690321e7c8468f048e45868acb4e&from_block=efir_newtab']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2020.12.31
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev, ffprobe 4.3.1-2020-10-01-full_build-www.gyan.dev
[debug] Proxy map: {}
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\YoutubeDL.py", line 2029, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\extractor\yandexvideo.py", line 89, in _real_extract TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'
```

**Comment by remitamine** [comment]
will be fixed in the next version.
