### ISSUE TITLE
PBS Video Not Downloading (version: 2020.12.31)

### ISSUE THREAD

**Issue by Blackstar-debug** [ytdl-org/youtube-dl#27605]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\YouTubeDL>youtube-dl -v https://www.pbs.org/wgbh/nova/video/the-impossible-flight/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.pbs.org/wgbh/nova/video/the-impossible-flight/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.12.31
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[debug] Using fake IP 6.64.187.149 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] the-impossible-flight: Downloading webpage
[pbs] Downloading widget/partnerplayer page
[pbs] Downloading portalplayer page
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\extractor\pbs.py", line 661, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\extractor\common.py", line 1367, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Cannot get PBS video to download on either the Windows or Linux version of 2020.12.31

URL: https://www.pbs.org/wgbh/nova/video/the-impossible-flight/

**Comment by october262** [comment]
try youtube-dl https://ga.video.cdn.pbs.org/videos/nova/cb6c6210-67f0-49b3-8938-b98f86b92841/2000210212/hd-16x9-mezzanine-1080p/nova4503_r-hls-16x9-1080p-234p-145k.m3u8

**Comment by StevenDTX** [comment]
Dont use the wgbh link. This works just fine:

https://www.pbs.org/video/the-impossible-flight-riui2e/

**Comment by Carlz10** [comment]
> Dont use the wgbh link. This works just fine:
> 
> https://www.pbs.org/video/the-impossible-flight-riui2e/

I just tried this on v2021-01-16 and it didnt work...The endpoint given by @october262 kicked off without issues, though.

**Comment by StevenDTX** [comment]
> 
> 
> > Dont use the wgbh link. This works just fine:
> > https://www.pbs.org/video/the-impossible-flight-riui2e/
> 
> I just tried this on v2021-01-16 and it didnt work...The endpoint given by @october262 kicked off without issues, though.

Works just fine:

```
E:\>c:\support\youtube-dl.exe https://www.pbs.org/video/the-impossible-flight-riui2e/ --hls-prefer-native --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.pbs.org/video/the-impossible-flight-riui2e/', '--hls-prefer-native', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-100433-g50a9210739, ffprobe N-100433-g50a9210739
[debug] Proxy map: {}
[debug] Using fake IP 6.45.164.255 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] the-impossible-flight-riui2e: Downloading webpage
[pbs] the-impossible-flight-riui2e: Downloading widget/partnerplayer page
[pbs] the-impossible-flight-riui2e: Downloading portalplayer page
[pbs] the-impossible-flight-riui2e: Downloading 0 video url info
[pbs] the-impossible-flight-riui2e: Downloading m3u8 information
[pbs] the-impossible-flight-riui2e: Downloading 1 video url info
[pbs] the-impossible-flight-riui2e: Checking http-2000k video URL
[pbs] the-impossible-flight-riui2e: http-2000k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] the-impossible-flight-riui2e: Checking http-6500k video URL
[pbs] the-impossible-flight-riui2e: http-6500k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] the-impossible-flight-riui2e: Checking http-4500k video URL
[pbs] the-impossible-flight-riui2e: http-4500k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] the-impossible-flight-riui2e: Checking http-3000k video URL
[pbs] the-impossible-flight-riui2e: Checking http-1100k video URL
[pbs] the-impossible-flight-riui2e: http-1100k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] the-impossible-flight-riui2e: Checking http-730k video URL
[pbs] the-impossible-flight-riui2e: http-730k video URL is invalid, skipping: HTTP Error 403: Forbidden
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://ga.video.cdn.pbs.org/videos/nova/cb6c6210-67f0-49b3-8938-b98f86b92841/2000210212/hd-16x9-mezzanine-1080p/nova4503_r-hls-16x9-1080p-1080p-6500k.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1134
[download] Destination: NOVA - The Impossible Flight-3008829324.mp4
[download]   0.5% of ~5.49GiB at  8.15MiB/s ETA 19:14
ERROR: Interrupted by user
```

**Comment by Carlz10** [comment]
Yeah weird, I just retried the exact same cmd again and it's running now too. 
Maybe a VPN issue, which I didn't suspect seeing as the other link worked without any problems 🤷‍♀️

**Comment by Mennaruuk** [comment]
This command:
`youtube-dl "https://www.pbs.org/video/the-impossible-flight-riui2e/"`
produces this error:
```
C:\Users\Menna\Downloads>youtube-dl --verbose "https://www.pbs.org/video/the-impossible-flight-riui2e/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.pbs.org/video/the-impossible-flight-riui2e/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Using fake IP 6.135.193.79 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] the-impossible-flight-riui2e: Downloading webpage
[pbs] the-impossible-flight-riui2e: Downloading widget/partnerplayer page
[pbs] the-impossible-flight-riui2e: Downloading portalplayer page
[pbs] the-impossible-flight-riui2e: Downloading 0 video url info
[pbs] the-impossible-flight-riui2e: Downloading m3u8 information
[pbs] the-impossible-flight-riui2e: Downloading 1 video url info
[pbs] the-impossible-flight-riui2e: Checking http-2000k video URL
[pbs] the-impossible-flight-riui2e: http-2000k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] the-impossible-flight-riui2e: Checking http-6500k video URL
[pbs] the-impossible-flight-riui2e: http-6500k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] the-impossible-flight-riui2e: Checking http-4500k video URL
[pbs] the-impossible-flight-riui2e: http-4500k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] the-impossible-flight-riui2e: Checking http-3000k video URL
[pbs] the-impossible-flight-riui2e: Checking http-1100k video URL
[pbs] the-impossible-flight-riui2e: http-1100k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] the-impossible-flight-riui2e: Checking http-730k video URL
[pbs] the-impossible-flight-riui2e: http-730k video URL is invalid, skipping: HTTP Error 403: Forbidden
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://ga.video.cdn.pbs.org/videos/nova/cb6c6210-67f0-49b3-8938-b98f86b92841/2000210212/hd-16x9-mezzanine-1080p/nova4503_r-hls-16x9-1080p-1080p-6500k.m3u8'
[download] Destination: NOVA - The Impossible Flight-3008829324.mp4
ERROR: m3u8 download detected but ffmpeg or avconv could not be found. Please install one.
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\__init__.py", line 465, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\YoutubeDL.py", line 2056, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\YoutubeDL.py", line 799, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\YoutubeDL.py", line 838, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\YoutubeDL.py", line 872, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\YoutubeDL.py", line 1679, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\YoutubeDL.py", line 1963, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\YoutubeDL.py", line 1902, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\downloader\external.py", line 35, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\downloader\external.py", line 227, in _call_downloader
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\downloader\common.py", line 165, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\YoutubeDL.py", line 628, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\YoutubeDL.py", line 590, in trouble
```
This command:
`youtube-dl --hls-prefer-native "https://www.pbs.org/video/the-impossible-flight-riui2e/"`
starts downloading the file:
```
C:\Users\Menna\Downloads>youtube-dl --hls-prefer-native "https://www.pbs.org/video/the-impossible-flight-riui2e/
[pbs] Downloading JSON metadata
[pbs] the-impossible-flight-riui2e: Downloading webpage
[pbs] the-impossible-flight-riui2e: Downloading widget/partnerplayer page
[pbs] the-impossible-flight-riui2e: Downloading portalplayer page
[pbs] the-impossible-flight-riui2e: Downloading 0 video url info
[pbs] the-impossible-flight-riui2e: Downloading m3u8 information
[pbs] the-impossible-flight-riui2e: Downloading 1 video url info
[pbs] the-impossible-flight-riui2e: Checking http-2000k video URL
[pbs] the-impossible-flight-riui2e: http-2000k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] the-impossible-flight-riui2e: Checking http-6500k video URL
[pbs] the-impossible-flight-riui2e: http-6500k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] the-impossible-flight-riui2e: Checking http-4500k video URL
[pbs] the-impossible-flight-riui2e: http-4500k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] the-impossible-flight-riui2e: Checking http-3000k video URL
[pbs] the-impossible-flight-riui2e: Checking http-1100k video URL
[pbs] the-impossible-flight-riui2e: http-1100k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] the-impossible-flight-riui2e: Checking http-730k video URL
[pbs] the-impossible-flight-riui2e: http-730k video URL is invalid, skipping: HTTP Error 403: Forbidden
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1134
[download] Destination: NOVA - The Impossible Flight-3008829324.mp4
[download]   0.0% of ~5.50GiB at  2.18MiB/s ETA 01:09:52
```

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/21984
https://github.com/ytdl-org/youtube-dl/issues/25454
https://github.com/ytdl-org/youtube-dl/issues/28749
https://github.com/ytdl-org/youtube-dl/issues/30205

**Comment by 89z** [comment]
Last comment is not longer valid, looks like the video has been pulled.

**Comment by Mennaruuk** [comment]
> 
> 
> Last comment is not longer valid, looks like the video has been pulled.

Right. But the error is reproducible with other online videos, such as the following URL: https://www.pbs.org/video/pandora-papersmassacre-in-el-salvador-v2wjzz

```
youtube-dl -v "https://www.pbs.org/video/pandora-papersmassacre-in-el-salvador-v2wjzz"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.pbs.org/video/pandora-papersmassacre-in-el-salvador-v2wjzz']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Using fake IP 6.138.213.157 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Downloading webpage
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Downloading widget/partnerplayer page
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Downloading portalplayer page
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Downloading 0 video url info
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Downloading m3u8 information
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Downloading 1 video url info
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Checking http-2000k video URL
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: http-2000k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Checking http-6500k video URL
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: http-6500k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Checking http-4500k video URL
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: http-4500k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Checking http-3000k video URL
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Checking http-1100k video URL
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: http-1100k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Checking http-730k video URL
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: http-730k video URL is invalid, skipping: HTTP Error 403: Forbidden
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://ga.video.cdn.pbs.org/videos/frontline/fbc5696b-ac83-4af4-8f76-d2e9e247f71d/2000264985/hd-16x9-mezzanine-1080p/00004011-hls-16x9-1080p-1080p-6500k.m3u8'
[download] Destination: FRONTLINE - Pandora Papers_Massacre in El Salvador-3061353278.mp4
ERROR: m3u8 download detected but ffmpeg or avconv could not be found. Please install one.
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\__init__.py", line 465, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2069, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 847, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 881, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 1692, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 1976, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 1915, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\downloader\external.py", line 35, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\downloader\external.py", line 227, in _call_downloader
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\downloader\common.py", line 165, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 628, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 590, in trouble
```

vs
```

youtube-dl -v --hls-prefer-native "https://www.pbs.org/video/pandora-papersmassacre-in-el-salvador-v2wjzz"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--hls-prefer-native', 'https://www.pbs.org/video/pandora-papersmassacre-in-el-salvador-v2wjzz']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Using fake IP 6.111.176.158 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Downloading webpage
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Downloading widget/partnerplayer page
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Downloading portalplayer page
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Downloading 0 video url info
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Downloading m3u8 information
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Downloading 1 video url info
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Checking http-2000k video URL
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: http-2000k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Checking http-6500k video URL
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: http-6500k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Checking http-4500k video URL
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: http-4500k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Checking http-3000k video URL
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Checking http-1100k video URL
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: http-1100k video URL is invalid, skipping: HTTP Error 403: Forbidden
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: Checking http-730k video URL
[pbs] pandora-papersmassacre-in-el-salvador-v2wjzz: http-730k video URL is invalid, skipping: HTTP Error 403: Forbidden
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://ga.video.cdn.pbs.org/videos/frontline/fbc5696b-ac83-4af4-8f76-d2e9e247f71d/2000264985/hd-16x9-mezzanine-1080p/00004011-hls-16x9-1080p-1080p-6500k.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 543
[download] Destination: FRONTLINE - Pandora Papers_Massacre in El Salvador-3061353278.mp4
[download]   0.1% of ~2.56GiB at  1.44MiB/s ETA 33:58
```

FWIW, switch over to [yt-dlp](https://github.com/yt-dlp/yt-dlp). No need to pass `--hls-prefer-native` with it.

**Comment by 89z** [comment]
> FWIW, switch over to [yt-dlp](https://github.com/yt-dlp/yt-dlp). No need to pass `--hls-prefer-native` with it.

No thanks, I will use my own ;)

https://github.com/89z/mech

**Comment by 89z** [comment]
> FWIW, switch over to [yt-dlp](https://github.com/yt-dlp/yt-dlp). No need to pass `--hls-prefer-native` with it.

Actually, YT-DLP doesnt work:

~~~
PS C:\> yt-dlp https://www.pbs.org/wgbh/nova/video/nova-universe-revealed-milky-way/
[pbs] Downloading JSON metadata
[pbs] nova-universe-revealed-milky-way: Downloading webpage
[pbs] Downloading widget/partnerplayer page
[pbs] Downloading portalplayer page
ERROR: 'NoneType' object has no attribute 'get'
~~~

Mine is does:

~~~
PS C:\> pbs https://www.pbs.org/wgbh/nova/video/nova-universe-revealed-milky-way/
GET /wgbh/nova/api/video/nova-universe-revealed-milky-way/ HTTP/1.1
Host: www.pbs.org

GET /v3/android/screens/video-assets/nova-universe-revealed-milky-way-4io957/ HTTP/1.1
Host: content.services.pbs.org
Authorization: Basic YW5kcm9pZDpiYVhFN2h1bXVWYXQ=
X-Pbs-Platformversion: 5.4.2

GET https://urs.pbs.org/redirect/74acdaaf8670428c8808f01beda49548/
0% 0.000 B
0% 10.016 MB
1% 20.020 MB
~~~

https://github.com/89z/mech

**Comment by Mennaruuk** [comment]
Interesting. Not sure why it can download some videos but not others. I filed an [issue ](https://github.com/yt-dlp/yt-dlp/issues/1643)over at yt-dlp. BTW, nice repo you have there! Starred.

**Comment by 89z** [comment]
> While I do appreciate your coding efforts and feel you genuinely wish to help people fetch things for which yt-dl, in its current state, has handicaps with (rather than simply promote your "own" solution[s]), please don't turn this into a pis\*ing contest 😉

Dont tell me what to do. Regarding this video [1], it currently fails with both YouTube-DL and YT-DLP. So if I want to post a tool that actually works, I am in my right to do so. Back off.

> BTW, I'd really appreciate it if you'd be king enough to also release **win32** editions of your "tools" (as currently am in a 32-bit WinOS...).

This is pretty galling, considering your previous comment. If you hadnt started off so poorly, I wouldve went ahead and built it for you. But since you want to be rude, you can build it yourself [2].

1. https://www.pbs.org/wgbh/nova/video/nova-universe-revealed-milky-way/
2. https://github.com/89z/mech#how-to-build
