### ISSUE TITLE
[VRT.BE/VRTNU] ERROR: No video formats found

### ISSUE THREAD

**Issue by BelgianNoise** [ytdl-org/youtube-dl#27602]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://ondemand-cf-vrt.akamaized.net/content/vod/vid-66a12e4a-e920-4823-b217-78099d547208-CDN_4/vid-66a12e4a-e920-4823-b217-78099d547208-CDN_4_drm_0ea7a4b8-fa86-471e-8f56-0e639eb178ab.ism/.mpd']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.12.31
[debug] Python version 3.8.3 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-06-23-ce297b4, ffprobe git-2020-06-23-ce297b4
[debug] Proxy map: {}
[generic] .mpd: Requesting header
WARNING: Falling back on generic information extractor.
[generic] .mpd: Downloading webpage
[generic] .mpd: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\kinga\AppData\Roaming\Python\Python38\site-packages\youtube_dl\YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\kinga\AppData\Roaming\Python\Python38\site-packages\youtube_dl\YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\kinga\AppData\Roaming\Python\Python38\site-packages\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\kinga\AppData\Roaming\Python\Python38\site-packages\youtube_dl\extractor\generic.py", line 2476, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "C:\Users\kinga\AppData\Roaming\Python\Python38\site-packages\youtube_dl\extractor\common.py", line 1367, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

As mentioned in [another issue](https://github.com/ytdl-org/youtube-dl/issues/26957), when trying to download from vrt.be/vrtnu you get a 410 Gone.

My workaround was going into the network tab of my browser and directly copying the .mpd file link and using it like this youtube-dl [link](https://ondemand-cf-vrt.akamaized.net/content/vod/vid-66a12e4a-e920-4823-b217-78099d547208-CDN_4/vid-66a12e4a-e920-4823-b217-78099d547208-CDN_4_drm_0ea7a4b8-fa86-471e-8f56-0e639eb178ab.ism/.mpd) .
However this doesnt seem to work anymore. Check verbose log above.

[Link to the video of this example](https://www.vrt.be/vrtnu/a-z/zero-zero-zero/1/zero-zero-zero-s1a2/).

Any help is welcome.

**Comment by remitamine** [comment]
DRM Protected.
