### ISSUE TITLE
Hotstar downloading error

### ISSUE THREAD

**Issue by Admire1231** [ytdl-org/youtube-dl#27614]
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2020.12.31**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

youtube-dl -v "https://www.hotstar.com/in/tv/saanjher-baati/1260007251/chinis-innocent-demand/1000256251"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.hotstar.com/in/tv/saanjher-baati/1260007251/chinis-innocent-demand/1000256251']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.12.31
[debug] Python version 3.4.4 (CPython) - Windows-2012ServerR2-6.3.9600
[debug] exe versions: ffmpeg N-92391-g07bc603757
[debug] Proxy map: {}
[hotstar] 1000256251: Downloading webpage
[hotstar] 1000256251: Downloading JSON metadata
ERROR: 1000256251: Failed to parse JSON  (caused by ValueError('Expecting value:
 line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3
hs\build\youtube_dl\extractor\common.py", line 904, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3
hs\build\youtube_dl\extractor\common.py", line 904, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3
hs\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3
hs\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3
hs\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3
hs\build\youtube_dl\extractor\hotstar.py", line 146, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3
hs\build\youtube_dl\extractor\hotstar.py", line 63, in _call_api_v2
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3
hs\build\youtube_dl\extractor\common.py", line 908, in _parse_json
youtube_dl.utils.ExtractorError: 1000256251: Failed to parse JSON  (caused by Va
lueError('Expecting value: line 1 column 1 (char 0)',)); please report this issu
e on https://yt-dl.org/bug . Make sure you are using the latest version; type  y
outube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and
include its complete output.
```

## Description

I m getting this error in downloading "ERROR: 1000256251: Failed to parse JSON  (caused by ValueError('Expecting value:
 line 1 column 1 (char 0)',));"
 
 can anyone please guide me how to fix it or solve it if this is extractor error

**Comment by remitamine** [comment]
```
youtube-dl https://www.hotstar.com/in/tv/saanjher-baati/1260007251/chinis-innocent-demand/1000256251
[hotstar] 1000256251: Downloading webpage
[hotstar] 1000256251: Downloading JSON metadata
[hotstar] 1000256251: Downloading JSON metadata
[hotstar] 1000256251: Downloading MPD manifest
[hotstar] 1000256251: Downloading MPD manifest
[hotstar] 1000256251: Downloading m3u8 information
[hotstar] 1000256251: Downloading m3u8 information
[hotstar] 1000256251: Downloading m3u8 information
[hotstar] 1000256251: Downloading MPD manifest
[hotstar] 1000256251: Downloading m3u8 information
[hotstar] 1000256251: Downloading m3u8 information
[hotstar] 1000256251: Downloading MPD manifest
[hotstar] 1000256251: Downloading MPD manifest
[hotstar] 1000256251: Downloading m3u8 information
[hotstar] 1000256251: Downloading m3u8 information
[hotstar] 1000256251: Downloading m3u8 information
[hotstar] 1000256251: Downloading MPD manifest
[hotstar] 1000256251: Downloading m3u8 information
[hotstar] 1000256251: Downloading m3u8 information
[hotstar] 1000256251: Downloading MPD manifest
[hotstar] 1000256251: Downloading MPD manifest
[download] Destination: Chini's Innocent Demand-1000256251.mp4
...
```

**Comment by Admire1231** [comment]
whats the reason i m getting this error: "ERROR: 1000256251: Failed to parse JSON (caused by ValueError('Expecting value:
line 1 column 1 (char 0)',));", i m unable to fix it can some one please guide me

**Comment by manikchathli** [comment]
I am also getting the same error

**Comment by Mennaruuk** [comment]
Should be tagged **account-needed.** Also **geo-restricted**.
![image](https://user-images.githubusercontent.com/52135169/106547880-071f3300-64dc-11eb-912f-ff04068688d7.png)
