### ISSUE TITLE
Workaround request: autoretry on SSLV3_ALERT_HANDSHAKE_FAILURE and other download failures

### ISSUE THREAD

**Issue by gjvnq** [ytdl-org/youtube-dl#27623]
## Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running youtube-dl version **2020.12.31**
- [X] I've searched the bugtracker for similar feature requests including closed ones

## Description

I keep getting SSL errors in the middle of downloads from the BBC. The "solution" I managed to find was to run youtube-dl inside a forever loop, i.e.: ```while true; do youtube-dl URL; done```

The errors are always like the following:
```
[download] Destination: Doctor Who, Revolution of the Daleks-m000qr8h.fmf_limelight-audio_eng_1=128000-1.m4a
[download]  56.9% of ~66.17MiB at 144.17KiB/s ETA 18:43ERROR: unable to download video data: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)>
Traceback (most recent call last):
  File "/usr/lib/python3.9/urllib/request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.9/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 1930, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 1875, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/dash.py", line 48, in real_download
    success, frag_content = self._download_fragment(ctx, fragment_url, info_dict)
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/fragment.py", line 104, in _download_fragment
    success = ctx['dl'].download(fragment_filename, fragment_info_dict)
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2248, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/site-packages/youtube_dl/utils.py", line 2734, in https_open
    return self.do_open(functools.partial(
  File "/usr/lib/python3.9/urllib/request.py", line 1345, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)>
```

Anyway, the requested feature is simple¹: if a download fails, just retry it instead of crashing the program and only stop the program if the average download speed (across retries) is below a certain threshold (e.g. 10 KiB/s).

¹simple to describe, no idea if this is simple to implement.

**Comment by dstftw** [comment]
You must provide reproducible environment.
