### ISSUE TITLE
Funimation download Error (caused by KeyError('items',))

### ISSUE THREAD

**Issue by bossofthetimtams** [ytdl-org/youtube-dl#27625]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--cookies', 'Cookie.txt', 'https://www.funimation.com/shows/star-blazers/farewell-to-the-solar-system/?qid=undefined', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.12.31
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1-2021-01-01-essentials_build-www.gyan.dev, ffprobe 4.3.1-2021-01-01-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[Funimation] Logging in
[Funimation] farewell-to-the-solar-system: Downloading webpage
[Funimation] 536884: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('items',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\extractor\funimation.py", line 117, in _real_extract
KeyError: 'items'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\extractor\funimation.py", line 117, in _real_extract
KeyError: 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\extractor\common.py", line 545, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('items',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

i was having with previous version, ver 2020.12.31 resolved those... for about an hour...
downloaded first 5 episodes of https://www.funimation.com/shows/star-blazers... after which funimation's website appeared to hang for a moment, and after that, downloads failed (including download of previously successful episodes)
have rebooted, renewed cookie etc to no avail

**Comment by jaroslawjanas** [comment]
@dstftw
Update: I think it is just rude and unpolite to simply close issues without even bothering to reference if, and where, the problem has been already been opened/fixed.
Ask yourself a question: if many people are opening the same issue after looking for it in the bugtracker, maybe is because the solution/duplicate issue is not that easy to to find.

https://github.com/ytdl-org/youtube-dl/issues/22917
