### ISSUE TITLE
Youtube download error: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by williamycyh** [ytdl-org/youtube-dl#27638]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=2mY7AFTtYwQ']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.03
[debug] Git HEAD: 8e953dcbb
[debug] Python version 3.8.2 (CPython) - macOS-10.15.6-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 2mY7AFTtYwQ: Downloading webpage
[youtube] {18} signature length 110, html5 player 5dd3f3b2
[youtube] {313} signature length 110, html5 player 5dd3f3b2
[youtube] {271} signature length 110, html5 player 5dd3f3b2
[youtube] {137} signature length 110, html5 player 5dd3f3b2
[youtube] {248} signature length 110, html5 player 5dd3f3b2
[youtube] {399} signature length 110, html5 player 5dd3f3b2
[youtube] {136} signature length 110, html5 player 5dd3f3b2
[youtube] {247} signature length 106, html5 player 5dd3f3b2
[youtube] {398} signature length 110, html5 player 5dd3f3b2
[youtube] {135} signature length 110, html5 player 5dd3f3b2
[youtube] {244} signature length 106, html5 player 5dd3f3b2
[youtube] {397} signature length 110, html5 player 5dd3f3b2
[youtube] {134} signature length 110, html5 player 5dd3f3b2
[youtube] {243} signature length 106, html5 player 5dd3f3b2
[youtube] {396} signature length 110, html5 player 5dd3f3b2
[youtube] {133} signature length 110, html5 player 5dd3f3b2
[youtube] {242} signature length 110, html5 player 5dd3f3b2
[youtube] {395} signature length 110, html5 player 5dd3f3b2
[youtube] {160} signature length 110, html5 player 5dd3f3b2
[youtube] {278} signature length 106, html5 player 5dd3f3b2
[youtube] {394} signature length 110, html5 player 5dd3f3b2
[youtube] {140} signature length 110, html5 player 5dd3f3b2
[youtube] {249} signature length 106, html5 player 5dd3f3b2
[youtube] {250} signature length 110, html5 player 5dd3f3b2
[youtube] {251} signature length 110, html5 player 5dd3f3b2
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r2---sn-ibj-i3bs.googlevideo.com/videoplayback?expire=1609667154&ei=8T3xX8TrOovMgQOHnpuwCw&ip=203.81.177.38&id=o-AM98fkc-5a8kh3nlwY4OkZ4nn1QfI1fT3USkkknB-SDn&itag=18&source=youtube&requiressl=yes&mh=t0&mm=31%2C29&mn=sn-ibj-i3bs%2Csn-i3belnls&ms=au%2Crdu&mv=m&mvi=2&pl=26&gcr=tw&initcwndbps=953750&vprv=1&mime=video%2Fmp4&ns=P9fBR8f0pYW_9n4TmYcw0XwF&gir=yes&clen=18145266&ratebypass=yes&dur=210.256&lmt=1585274392033151&mt=1609645230&fvip=2&c=WEB&txp=5531432&n=bJ19dMHY_vzST7JE&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgdm6ZpcYLQtwDKRaINCEWh_CF1zth3P9j1XGZq_cWEMcCIGfFQTwXIBaXxRcBSoj6o_Eazg_RPTxYRsQpDm0i7cvs&sig=AOq0QJ8wRgIhAIbDZK98T1BMHPXETVCH8l_VgUNHWHfi8mMSvqjLJRMKAiEArCc31vG4knwnkcQlIlrX_QniQwCotdFlNVF-8nKMWLA='
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/Users/egbert/work/youtube-dl/youtube_dl/YoutubeDL.py", line 1936, in process_info
    success = dl(filename, info_dict)
  File "/Users/egbert/work/youtube-dl/youtube_dl/YoutubeDL.py", line 1875, in dl
    return fd.download(name, info)
  File "/Users/egbert/work/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/Users/egbert/work/youtube-dl/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/Users/egbert/work/youtube-dl/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
  File "/Users/egbert/work/youtube-dl/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/Users/egbert/work/youtube-dl/youtube_dl/YoutubeDL.py", line 2248, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by fossdd** [comment]
Look at https://github.com/ytdl-org/youtube-dl/pull/25068.

Short: Append `--rm-cache-dir`

I guess, this issue can be closed
