### ISSUE TITLE
Kinopoisk moved to new domain

### ISSUE THREAD

**Issue by F5-afk** [ytdl-org/youtube-dl#27644]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\MrAnd>youtube-dl -v "https://hd.kinopoisk.ru/film/466ae356618feb9296e9e2d0ecd50bdf?from_block=kp-button-online&watch="
[debug] System config: []
[debug] User config: ['--netrc']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://hd.kinopoisk.ru/film/466ae356618feb9296e9e2d0ecd50bdf?from_block=kp-button-online&watch=']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2021.01.03
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-99920-g46e362b765, ffprobe N-99920-g46e362b765
[debug] Proxy map: {}
[generic] 466ae356618feb9296e9e2d0ecd50bdf?from_block=kp-button-online&watch=: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 466ae356618feb9296e9e2d0ecd50bdf?from_block=kp-button-online&watch=: Downloading webpage
[generic] 466ae356618feb9296e9e2d0ecd50bdf?from_block=kp-button-online&watch=: Extracting information
ERROR: Unsupported URL: https://hd.kinopoisk.ru/film/466ae356618feb9296e9e2d0ecd50bdf?from_block=kp-button-online&watch=
Traceback (most recent call last):
  File "c:\users\mrand\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\mrand\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\mrand\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\mrand\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\generic.py", line 3467, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://hd.kinopoisk.ru/film/466ae356618feb9296e9e2d0ecd50bdf?from_block=kp-button-online&watch=
```

## Description

Kinopoisk.ru moved all his movies on a new domain: `hd.kinopoisk.ru`

Example of a new URL for movie **Jurassic World**: 
* Database: https://www.kinopoisk.ru/film/594554/
* New movie info page: https://hd.kinopoisk.ru/film/466ae356618feb9296e9e2d0ecd50bdf
* New movie watch page: https://hd.kinopoisk.ru/film/466ae356618feb9296e9e2d0ecd50bdf?watch=

**Comment by fossdd** [comment]
Okay, i guess it just enhance this Line with the new URLs:

https://github.com/ytdl-org/youtube-dl/blob/19ec46863587758fa6de274df293ede09b10eeb3/youtube_dl/extractor/kinopoisk.py#L13

**Comment by F5-afk** [comment]
Ok, I tried replace to this regex:
```py
_VALID_URL = r'https?://(?:www\.|hd\.)?kinopoisk\.ru/(?:film/|\?rt=)(?P<id>\w+)(?:[\?&].+)?'
```
and I get this error:
```
[debug] System config: []
[debug] User config: ['--netrc']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://hd.kinopoisk.ru/?rt=4189d22bb48823c3844f122ee7b9d048']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2021.01.03
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-99920-g46e362b765, ffprobe N-99920-g46e362b765
[debug] Proxy map: {}
[debug] Using fake IP 5.140.220.117 (RU) as X-Forwarded-For.
[KinoPoisk] 4189d22bb48823c3844f122ee7b9d048: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 400: 400 (caused by <HTTPError 400: '400'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\users\mrand\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\mrand\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2248, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\mrand\appdata\local\programs\python\python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "c:\users\mrand\appdata\local\programs\python\python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "c:\users\mrand\appdata\local\programs\python\python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "c:\users\mrand\appdata\local\programs\python\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\users\mrand\appdata\local\programs\python\python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```
