### ISSUE TITLE
Unable to extract OpenGraph title on Washington Post article

### ISSUE THREAD

**Issue by UnicornsOnLSD** [ytdl-org/youtube-dl#27652]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.washingtonpost.com/politics/trump-raffensperger-call-georgia-vote/2021/01/03/d45acb92-4dc4-11eb-bda4-615aaefd0555_story.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.03
[debug] Python version 3.9.1 (CPython) - Linux-5.9.14-arch1-1-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[washingtonpost:article] d45acb92-4dc4-11eb-bda4-615aaefd0555_story.html: Downloading webpage
ERROR: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/washingtonpost.py", line 102, in _real_extract
    title = self._og_search_title(webpage)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1122, in _og_search_title
    return self._og_search_property('title', html, **kargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1110, in _og_search_property
    escaped = self._search_regex(og_regexes, html, name, flags=re.DOTALL, **kargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

When trying to download a Washington Post article, youtube-dl says it was "Unable to extract OpenGraph title". This error also happens when trying to view quality options with the -F argument. I'm trying to download the videos from this article: https://www.washingtonpost.com/politics/trump-raffensperger-call-georgia-vote/2021/01/03/d45acb92-4dc4-11eb-bda4-615aaefd0555_story.html

**Comment by andlabs** [comment]
Downloading the actual video in question itself also doesn't work. The video ID was extracted by inspecting links to the audio clip from other websites and on the Post's playlist page.

```
$ youtube-dl --write-pages --print-traffic --verbose 'https://www.washingtonpost.com/video/c/embed/aba64f5f-8c3c-490f-af34-618ccea732d7'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--write-pages', '--print-traffic', '--verbose', 'https://www.washingtonpost.com/video/c/embed/aba64f5f-8c3c-490f-af34-618ccea732d7']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.31
[debug] Python version 3.7.9 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[washingtonpost] aba64f5f-8c3c-490f-af34-618ccea732d7: Downloading JSON metadata
send: b'GET /posttv/c/videojson/aba64f5f-8c3c-490f-af34-618ccea732d7?resType=jsonp HTTP/1.1\r\nHost: www.washingtonpost.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.11 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 301 Moved Permanently\r\n'
header: Server: AkamaiGHost
header: Content-Length: 0
header: Location: https://www.washingtonpost.com/posttv/c/videojson/aba64f5f-8c3c-490f-af34-618ccea732d7?resType=jsonp
header: Cache-Control: max-age=0
header: Expires: Mon, 04 Jan 2021 04:47:41 GMT
header: Date: Mon, 04 Jan 2021 04:47:41 GMT
header: Connection: close
header: Set-Cookie: wp_devicetype=0; expires=Wed, 03-Feb-2021 04:47:41 GMT; path=/; domain=.washingtonpost.com; secure; SameSite=None
header: Set-Cookie: wp_country=US; expires=Mon, 04-Jan-2021 05:47:41 GMT; path=/; domain=.washingtonpost.com; secure; SameSite=None
header: Set-Cookie: rplampr=0a|20181213; expires=Tue, 04-Jan-2022 04:47:41 GMT; path=/; domain=.washingtonpost.com
header: Set-Cookie: wp_ak_subs=0|20201116; expires=Mon, 25-Jan-2021 19:19:29 GMT; path=/; domain=.washingtonpost.com; SameSite=None; secure
header: Set-Cookie: wp_ak_v_m=0|20201116; expires=Mon, 25-Jan-2021 19:19:29 GMT; path=/; domain=.washingtonpost.com; SameSite=None; secure
header: Content-Security-Policy: upgrade-insecure-requests
send: b'GET /posttv/c/videojson/aba64f5f-8c3c-490f-af34-618ccea732d7?resType=jsonp HTTP/1.1\r\nHost: www.washingtonpost.com\r\nCookie: wp_devicetype=0; wp_country=US; rplampr=0a|20181213; wp_ak_subs=0|20201116; wp_ak_v_m=0|20201116\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.11 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 301 Moved Permanently\r\n'
header: Content-Type: text/html
header: Content-Length: 178
header: Server: nginx
header: Location: https://www.washingtonpost.com/posttv/c/videojson/aba64f5f-8c3c-490f-af34-618ccea732d7/?resType=jsonp
header: Access-Control-Allow-Origin: *
header: Cache-Control: max-age=294
header: Expires: Mon, 04 Jan 2021 04:52:47 GMT
header: Date: Mon, 04 Jan 2021 04:47:53 GMT
header: Connection: close
header: Set-Cookie: wp_country=US; expires=Mon, 04-Jan-2021 05:47:53 GMT; path=/; domain=.washingtonpost.com; secure; SameSite=None
header: Set-Cookie: rplampr=0a|20181213; expires=Tue, 04-Jan-2022 04:47:53 GMT; path=/; domain=.washingtonpost.com
header: Content-Security-Policy: upgrade-insecure-requests
send: b'GET /posttv/c/videojson/aba64f5f-8c3c-490f-af34-618ccea732d7/?resType=jsonp HTTP/1.1\r\nHost: www.washingtonpost.com\r\nCookie: wp_devicetype=0; wp_country=US; rplampr=0a|20181213; wp_ak_subs=0|20201116; wp_ak_v_m=0|20201116\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.11 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 301 Moved Permanently\r\n'
header: Content-Length: 0
header: Server: nginx
header: Location: http://www.washingtonpost.com/video/politics/audio-trump-berates-ga-secretary-of-state-urges-him-to-find-votes/2021/01/03/aba64f5f-8c3c-490f-af34-618ccea732d7_video.html
header: X-Served-By: pb
header: X-Backend: http://pagebuilder-app.wpit.nile.works/pb
header: Access-Control-Allow-Origin: *
header: Strict-Transport-Security: max-age=0; includeSubdomains
header: Cache-Control: max-age=120, s-maxage=120
header: Expires: Mon, 04 Jan 2021 04:50:03 GMT
header: Date: Mon, 04 Jan 2021 04:48:03 GMT
header: Connection: close
header: Set-Cookie: wp_country=US; expires=Mon, 04-Jan-2021 05:48:03 GMT; path=/; domain=.washingtonpost.com; secure; SameSite=None
header: Set-Cookie: rplampr=0a|20181213; expires=Tue, 04-Jan-2022 04:48:03 GMT; path=/; domain=.washingtonpost.com
header: Content-Security-Policy: upgrade-insecure-requests
send: b'GET /video/politics/audio-trump-berates-ga-secretary-of-state-urges-him-to-find-votes/2021/01/03/aba64f5f-8c3c-490f-af34-618ccea732d7_video.html HTTP/1.1\r\nHost: www.washingtonpost.com\r\nCookie: rplampr=0a|20181213\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.11 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 301 Moved Permanently\r\n'
header: Server: AkamaiGHost
header: Content-Length: 0
header: Location: https://www.washingtonpost.com/video/politics/audio-trump-berates-ga-secretary-of-state-urges-him-to-find-votes/2021/01/03/aba64f5f-8c3c-490f-af34-618ccea732d7_video.html
header: Cache-Control: max-age=0
header: Expires: Mon, 04 Jan 2021 04:48:13 GMT
header: Date: Mon, 04 Jan 2021 04:48:13 GMT
header: Connection: close
header: Set-Cookie: wp_devicetype=0; expires=Wed, 03-Feb-2021 04:48:13 GMT; path=/; domain=.washingtonpost.com; secure; SameSite=None
header: Set-Cookie: wp_country=US; expires=Mon, 04-Jan-2021 05:48:13 GMT; path=/; domain=.washingtonpost.com; secure; SameSite=None
header: Set-Cookie: rplampr=0a|20181213; expires=Tue, 04-Jan-2022 04:48:13 GMT; path=/; domain=.washingtonpost.com
header: Set-Cookie: wp_ak_subs=0|20201116; expires=Mon, 25-Jan-2021 19:19:29 GMT; path=/; domain=.washingtonpost.com; SameSite=None; secure
header: Set-Cookie: wp_ak_v_m=0|20201116; expires=Mon, 25-Jan-2021 19:19:29 GMT; path=/; domain=.washingtonpost.com; SameSite=None; secure
header: Content-Security-Policy: upgrade-insecure-requests
send: b'GET /video/politics/audio-trump-berates-ga-secretary-of-state-urges-him-to-find-votes/2021/01/03/aba64f5f-8c3c-490f-af34-618ccea732d7_video.html HTTP/1.1\r\nHost: www.washingtonpost.com\r\nCookie: wp_devicetype=0; wp_country=US; rplampr=0a|20181213; wp_ak_subs=0|20201116; wp_ak_v_m=0|20201116\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.11 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: text/html;charset=UTF-8
header: Server: nginx
header: PB-RID: rgYMAa15OEEDZr
header: PB-PID: video-leaf-page-2018
header: X-Served-By: pb
header: X-Backend: http://pagebuilder-app.wpit.nile.works/pb
header: Access-Control-Allow-Origin: *
header: Strict-Transport-Security: max-age=0; includeSubdomains
header: Content-Encoding: gzip
header: Content-Length: 93619
header: Vary: Accept-Encoding
header: Cache-Control: max-age=120, s-maxage=120
header: Expires: Mon, 04 Jan 2021 04:50:28 GMT
header: Date: Mon, 04 Jan 2021 04:48:28 GMT
header: Connection: close
header: Set-Cookie: wp_country=US; expires=Mon, 04-Jan-2021 05:48:28 GMT; path=/; domain=.washingtonpost.com; secure; SameSite=None
header: Set-Cookie: rplampr=0a|20181213; expires=Tue, 04-Jan-2022 04:48:28 GMT; path=/; domain=.washingtonpost.com
header: Content-Security-Policy: upgrade-insecure-requests
[washingtonpost] Saving request to aba64f5f-8c3c-490f-af34-618ccea732d7_https_-_www.washingtonpost.com_video_politics_audio-trump-berates-ga-secretary-of-state-urges-him-to-find-votes_2021_01_03_aba64f5f-8c3c-490f-af34-618ccea732d7_video.html.dump
ERROR: aba64f5f-8c3c-490f-af34-618ccea732d7: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 904, in _parse_json
    return json.loads(json_string)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 904, in _parse_json
    return json.loads(json_string)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/extractor/washingtonpost.py", line 40, in _real_extract
    video_id, transform_source=strip_jsonp)[0]['contentConfig']
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 897, in _download_json
    expected_status=expected_status)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 881, in _download_json_handle
    fatal=fatal), urlh
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 908, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: aba64f5f-8c3c-490f-af34-618ccea732d7: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

[`--write-pages` only produced one file.](https://github.com/ytdl-org/youtube-dl/files/5763090/dump.zip)

**Comment by remitamine** [comment]
@andlabs the version you're using is outdataed.

**Comment by andlabs** [comment]
All right; mine is from MacPorts so I'll just wait for them to update. But what about @UnicornsOnLSD? Is this a duplicate of #25774?

**Comment by remitamine** [comment]
> But what about @UnicornsOnLSD?

i can't reproduce the problem he is getting.
> Is this a duplicate of #25774?

not, it's duplicate of the other Washington Post issue that has a problem with an article that has the same layout, fixing the other issue, should fix this as well.

**Comment by andlabs** [comment]
Got it; thanks!
