### ISSUE TITLE
Only some videos can be downloaded from Lecturio

### ISSUE THREAD

**Issue by Abelcl7** [ytdl-org/youtube-dl#27668]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
 youtube-dl -v --cookies cookies.txt https://app.lecturio.com/#/lecture/c/8466/8468/29284
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--cookies', u'cookies.txt', u'https://app.lecturio.com/#/lecture/c/8466/8468/29284']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.29
[debug] Python version 2.7.18 (CPython) - Linux-4.4.0-19041-Microsoft-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[Lecturio] 8468: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError(u'content',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/lecturio.py", line 122, in _real_extract
    for format_ in video['content']['media']:
KeyError: u'content'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 545, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'content',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE

Some videos from this platform can be downloaded, but the vast majority cannot, I tried to download this and other videos and I always got this problem.

I attach video with a video that I can download and another that I cannot download

https://user-images.githubusercontent.com/58005697/103598392-19e81d00-4ec8-11eb-83b0-dc8b1a18979e.mp4

**Comment by Abelcl7** [comment]
I saw that they added a tag, I have a Lecturio account, but I don't know how to log in to download the videos.

**Comment by xlfpx** [comment]
Having the exact same issue:
`
youtube_dl\extractor\lecturio.py", line 122, in _real_extract
KeyError: 'content'
`
