### ISSUE TITLE
Problem with ABC 

### ISSUE THREAD

**Issue by Farmer09442** [ytdl-org/youtube-dl#27675]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

C:\Users\Florent>youtube-dl -v https://abc.com/shows/general-hospital/episode-guide/2020-12/28-general-hospital-122820
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://abc.com/shows/general-hospital/episode-guide/2020-12/28-general-hospital-122820']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.01.03
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg 2020-11-18-git-e3081d6f4f-full_build-www.gyan.dev, ffprobe 2020-11-18-git-e3081d6f4f-full_build-www.gyan.dev
[debug] Proxy map: {}
[Go] 28-general-hospital-122820: Downloading webpage
[Go] VDKA4974899: Downloading JSON metadata
[debug] Using fake IP 6.129.211.33 (US) as X-Forwarded-For.
[Go] VDKA4974899: Downloading JSON metadata
ERROR: Go said: 1025:Unable to retrieve required files for playback. Please try again in a few minutes.
Traceback (most recent call last):
  File "c:\users\florent\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\florent\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\florent\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\florent\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\go.py", line 222, in _real_extract
    raise ExtractorError('%s said: %s' % (self.IE_NAME, error_message), expected=True)
youtube_dl.utils.ExtractorError: Go said: 1025:Unable to retrieve required files for playback. Please try again in a few minutes.
```


## Description

Sorry for my english , i'm french ;) 

Hi everybody since a few day i can't download episode from ABC.Com , until this days everything was fine to me . 
I'm using a vpn since i'm in france , but the playback on the site is ok . and i using the vpn since a long time and everything was fine to me 

Hope someone can help me .

**Comment by Farmer09442** [comment]
Hi ,


Just foud that you closed the thread for duplicate , i understand , but can't find the same problem on the thread list ... Can you show me ?

thank you


Envoyé à partir d’Outlook<http://aka.ms/weboutlook>

________________________________
De : remitamine <notifications@github.com>
Envoyé : mardi 5 janvier 2021 11:26
À : ytdl-org/youtube-dl <youtube-dl@noreply.github.com>
Cc : Farmer09442 <farmer09442@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [ytdl-org/youtube-dl] Problem with ABC (#27675)


Closed #27675<https://github.com/ytdl-org/youtube-dl/issues/27675>.
