### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get on mixcloud extractor.

### ISSUE THREAD

**Issue by b1scoito** [ytdl-org/youtube-dl#27674]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.01.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestaudio', '--external-downloader', 'aria2c', '-o', 'C:\\Users\\biscoito\\Desktop\\otographic\\%(uploader)s/%(title)s.%(ext)s', '--add-metadata', '--cookies', 'C:\\Users\\biscoito\\Desktop\\otographic\\cookies.txt', '--audio-format', 'mp3', '--audio-quality', '0', 'https://www.mixcloud.com/otographic/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.01.03
[debug] Python version 3.9.1 (CPython) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-essentials_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-essentials_build-www.gyan.dev
[debug] Proxy map: {}
```

## Description

On the 15th download I get this error: 
```
[download] Downloading video 15 of 252
[mixcloud] otographic_nhato-otographic-live-2020-day-2-part-5-2020-05-17: Downloading JSON metadata
Traceback (most recent call last):
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\biscoito\AppData\Local\Programs\Python\Python39\Scripts\youtube-dl.exe\__main__.py", line 7, in <module>
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\__init__.py", line 474, in main
    _real_main(argv)
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2028, in download
    res = self.extract_info(
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 835, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 1012, in process_ie_result
    entry_result = self.__process_iterable_entry(entry, download, extra)
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 1044, in __process_iterable_entry
    return self.process_ie_result(
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 873, in process_ie_result
    return self.extract_info(ie_result['url'],
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\biscoito\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\mixcloud.py", line 137, in _real_extract
    format_url = stream_info.get(url_key)
AttributeError: 'NoneType' object has no attribute 'get'
```

This is the command I'm using: `youtube-dl -v -f bestaudio --external-downloader aria2c -o "C:\Users\biscoito\Desktop\otographic\%(uploader)s/%(title)s.%(ext)s" --add-metadata --cookies "C:\Users\biscoito\Desktop\otographic\cookies.txt" --audio-format mp3 --audio-quality 0 https://www.mixcloud.com/otographic/`

**Comment by b1scoito** [comment]
Update: Was able to run, with the `-i` flag, I figured out that it's a geolocation block, and should be ignored by default by youtube-dl.
