### ISSUE TITLE
Dplay.se - Changed name to Discovery+

### ISSUE THREAD

**Issue by SYSophie** [ytdl-org/youtube-dl#27680]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Dplay announced during fall that they would transit and change the name of the plattform to strengthen the brand. Today this transition took affect.

The changes has resulted in a broken extractor.

The changes that are needed not much more then to change the domains for API calls and for the check of the url itself. Usage of cookies remains the same.

Also maybe it would be appropriate to change the name of the extractor from dplay to Discovery+.

**Comment by Pirrevirr** [comment]
I'm really trying to understand what you wrote there, but I do not.

What is an extractor and where is it so that I can change it's name? The only file I've downloaded is the youtube-dl.exe. There are no additional files or folders that I've found. Nor have I made an installation for youtube-dl.exe to work, so there can't be any other files or folders somethere else.

How or rather where do I change the domains for the API calls?

I tried to just make a new cookie.txt from the "Get cookie.txt" plug-in. That hasn't worked.

Please help?

**Comment by remitamine** [comment]
either download the source to use the latest changes directly or wait for the next release.

**Comment by Pirrevirr** [comment]
What does that mean?

The source code to youtube-dl.exe?

**Comment by Its-its** [comment]
> 
> 
> What does that mean?
> 
> The source code to youtube-dl.exe?

Update youtube-dl. It was just released. Although it seems like they forgot the ".com" domain. dk,es,fi,it,se,no domains are in there but no .com

**Comment by Pirrevirr** [comment]
> > What does that mean?
> > The source code to youtube-dl.exe?
> 
> Update youtube-dl. It was just released. Although it seems like they don't have the ".com" domain in there. dk, es, fi, it, se, no domains are in there but no .com

Thank you, thank you, thank you, thank you!! :1st_place_medal:

**Comment by thedreamer91** [comment]
> > What does that mean?
> > The source code to youtube-dl.exe?
> 
> Update youtube-dl. It was just released. Although it seems like they don't have the ".com" domain in there. dk, es, fi, it, se, no domains are in there but no .com

I've just updated youtube-dl but i can't download from it domain

.\youtube-dl -f "best[height=720]" --cookie cookie.txt  --verbose https://www.discoveryplus.it/programmi/bake-off-italia-dolci-sotto-un-tetto
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best[height=720]', '--cookie', 'cookie.txt', '--verbose', 'https://www.discoveryplus.it/programmi/bake-off-italia-dolci-sotto-un-tetto']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1-2020-11-08-full_build-www.gyan.dev
[debug] Proxy map: {}
[generic] bake-off-italia-dolci-sotto-un-tetto: Requesting header
WARNING: Falling back on generic information extractor.
[generic] bake-off-italia-dolci-sotto-un-tetto: Downloading webpage
[generic] bake-off-italia-dolci-sotto-un-tetto: Extracting information
ERROR: Unsupported URL: https://www.discoveryplus.it/programmi/bake-off-italia-dolci-sotto-un-tetto
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\extractor\generic.py", line 3467, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.discoveryplus.it/programmi/bake-off-italia-dolci-sotto-un-tetto

**Comment by Pirrevirr** [comment]
Have you made a new cookie.txt from discoveryplus.it?

**Comment by thedreamer91** [comment]
> Have you made a new cookie.txt from discoveryplus.it?

either made a new cookie and tried without cookie

**Comment by remitamine** [comment]
#14960

**Comment by AchillesPDX** [comment]
How do we get discoveryplus.com added to the DPlus extractor? My python is terrible and I have no idea how to fix it.

**Comment by SYSophie** [comment]
> > > What does that mean?
> > > The source code to youtube-dl.exe?
> > 
> > 
> > Update youtube-dl. It was just released. Although it seems like they don't have the ".com" domain in there. dk, es, fi, it, se, no domains are in there but no .com
> 
> I've just updated youtube-dl but i can't download from it domain
> 
> .\youtube-dl -f "best[height=720]" --cookie cookie.txt --verbose https://www.discoveryplus.it/programmi/bake-off-italia-dolci-sotto-un-tetto
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['-f', 'best[height=720]', '--cookie', 'cookie.txt', '--verbose', 'https://www.discoveryplus.it/programmi/bake-off-italia-dolci-sotto-un-tetto']
> [debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
> [debug] youtube-dl version 2021.01.08
> [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
> [debug] exe versions: ffmpeg 4.3.1-2020-11-08-full_build-www.gyan.dev
> [debug] Proxy map: {}
> [generic] bake-off-italia-dolci-sotto-un-tetto: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] bake-off-italia-dolci-sotto-un-tetto: Downloading webpage
> [generic] bake-off-italia-dolci-sotto-un-tetto: Extracting information
> ERROR: Unsupported URL: https://www.discoveryplus.it/programmi/bake-off-italia-dolci-sotto-un-tetto
> Traceback (most recent call last):
> File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
> File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
> File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\extractor\common.py", line 532, in extract
> File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\extractor\generic.py", line 3467, in _real_extract
> youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.discoveryplus.it/programmi/bake-off-italia-dolci-sotto-un-tetto

seems like you are using the show URL instead of a specific episode URL.

**Comment by SYSophie** [comment]
> How do we get discoveryplus.com added to the DPlay extractor? My python is terrible and I have no idea how to fix it.

It has been added in the latest version of yt-dl and therefore has this ticket been closed.

Use cookies and find the right URLs guys

**Comment by remitamine** [comment]
> It has been added in the latest version of yt-dl and therefore has this ticket been closed.

no, this issue is about Dplay websites changing their domains to dicoveryplus domains, there is already an open issue related to discoveryplus.com.
@SYSophie again, i already linked to the issue related to you're problem.
