### ISSUE TITLE
Unable to download from CBS local sites that use the Anvato embedded player

### ISSUE THREAD

**Issue by crispyjones** [ytdl-org/youtube-dl#27699]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\FFAStrans\Processors\ffmpeg>youtube-dl.exe --verbose https://denver.cbslocal.com/2020/05/07/coronavirus-boulder-valley-school-district-imapct-education-food-bank
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://denver.cbslocal.com/2020/05/07/coronavirus-boulder-valley-school-district-imapct-education-food-bank']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.01.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[CBSLocalArticle] coronavirus-boulder-valley-school-district-imapct-education-food-bank: Downloading webpage
ERROR: Unable to extract Anvato player data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\extractor\cbslocal.py", line 107, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\extractor\anvato.py", line 365, in _extract_anvato_videos
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\extractor\common.py", line 1019, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\extractor\common.py", line 1010, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract Anvato player data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Can't download from CBS local sites that use the embedded anvato player.

**Comment by october262** [comment]
play the video and press F12 on your keyboard,  the debug menu shows,
go to network - media - type m3u8 in the search box and look for prog.m3u8,
copy the link and feed it into youtube-dl to download the video.

**Comment by crispyjones** [comment]
A search of this URL [https://denver.cbslocal.com/2020/05/07/coronavirus-boulder-valley-school-district-imapct-education-food-bank]( https://denver.cbslocal.com/2020/05/07/coronavirus-boulder-valley-school-district-imapct-education-food-bank) from the debug report does not reveal any m3u8/hls content. I think you are referring to the CBSN national/local live streams which. This issue is on the station's site (ie KCNC, KDKA, WFOR etc) where they post standalone content like news or weather segments.

**Comment by crispyjones** [comment]
@october262 that works great. I use youtube-dl as part of this [front end](https://www.ffastrans.com/) to make it easier for non-tech folks to grab web video. Is it possible that youtube-dl will be able to handle these video URLs directly without the F12 trick? Or is there a technical limitation that prevents it?

**Comment by BillyCreek** [comment]
> play the video and press F12 on your keyboard, the debug menu shows,
> go to network - media - type m3u8 in the search box and look for prog.m3u8,
> copy the link and feed it into youtube-dl to download the video.

I don't see an m3u8 file. The only things I see are .mp4 files (a file with blank in the name, and URls for ads).

**Comment by october262** [comment]
try  refreshing the page ctrl +R once the page reloads,you should see a master.m3u8 file, copy the one that has master.m3u8?i=
    On Thursday, January 14, 2021, 12:45:44 PM CST, BillyCreek <notifications@github.com> wrote:  
 
 



play the video and press F12 on your keyboard, the debug menu shows,
go to network - media - type m3u8 in the search box and look for prog.m3u8,
copy the link and feed it into youtube-dl to download the video.


I don't see an m3u8 file. The only things I see are .mp4 files (a file with blank in the name, and URls for ads).

**Comment by BillyCreek** [comment]
Thanks. I had tried that, and tried again now, but no master.m3u8.

**Comment by MichaelKuz** [comment]
I'm experiencing the same problem. There is no m3u8 file in the network pane. 

The video files I can find in the network pane are in the format [long hash]-[increment].ts. 

When I feed one of those URLs to youtube-dl, it successfully downloads a file. 

However, each file is only a few seconds – in order to download the entire video I have to manually increment all of the filenames and then combine them myself.

**Comment by llacb47** [comment]
It's right there...

![image](https://user-images.githubusercontent.com/16567977/107466813-b4c0c080-6b32-11eb-8401-5e15e5e073d8.png)

**Comment by MichaelKuz** [comment]
Indeed... thanks. I'm not sure what I was doing wrong but whatever it was, I'm not proud of it! Was able to successfully download the video using the master m3u8 file.
