### ISSUE TITLE
webcaster broken

### ISSUE THREAD

**Issue by gthreepw00d** [ytdl-org/youtube-dl#27757]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2021.01.08**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://start.webcaster.pro/iframe/feed/start/free_995f7f31248f3be39606a964fa3a216d_hd/33_2711111319/53c7af8beeada7307929eaef372de470/4765903776']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.8.6 (CPython) - Linux-5.10.6-100.fc32.x86_64-x86_64
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[generic] 4765903776: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 4765903776: Downloading webpage
[generic] 4765903776: Extracting information
ERROR: Unsupported URL: https://start.webcaster.pro/iframe/feed/start/free_995f7f31248f3be39606a964fa3a216d_hd/33_2711111319/53c7af8beeada7307929eaef372de470/4765903776
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 802, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 823, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/generic.py", line 3467, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://start.webcaster.pro/iframe/feed/start/free_995f7f31248f3be39606a964fa3a216d_hd/33_2711111319/53c7af8beeada7307929eaef372de470/4765903776
```

## Description

URL is playable in browser but not detected by youtube-dl

**Comment by georgeahill** [comment]
Hi! Thanks for opening an issue. Looks like that particular format of URL isn't supported right now - are you able to get a `bl.webcaster.pro` link? That should work. If not I can look into it further for you.

**Comment by gthreepw00d** [comment]
This one works
`https://bl.webcaster.pro/feed/start/free_995f7f31248f3be39606a964fa3a216d_hd/33_2711111319/53c7af8beeada7307929eaef372de470/4765903776`

**Comment by georgeahill** [comment]
Ah excellent! We can probably close this issue then I think.
