### ISSUE TITLE
HOTSTAR DRM SUPPORT!!

### ISSUE THREAD

**Issue by manikchathli** [ytdl-org/youtube-dl#27759]
C:\ffmpeg\bin>youtube-dl --verbose https://www.hotstar.com/in/tv/game-of-thrones/8184/the-iron-throne/1770005178
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.hotstar.com/in/tv/game-of-thrones/8184/the-iron-throne/1770005178']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.01.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-01-05-git-66deab3a26-full_build-www.gyan.dev, ffprobe 2021-01-05-git-66deab3a26-full_build-www.gyan.dev
[debug] Proxy map: {}
[hotstar] 1770005178: Downloading webpage
ERROR: This video is DRM protected.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\extractor\hotstar.py", line 132, in _real_extract
youtube_dl.utils.ExtractorError: This video is DRM protected.

**Comment by manikchathli** [comment]
Why it has been closed?
