### ISSUE TITLE
Adobeconnect extractor not working

### ISSUE THREAD

**Issue by oussj** [ytdl-org/youtube-dl#27777]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.01.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl  --verbose --no-check-certificate "https://lamaisondessavoirs.adobeconnect.com/_a1099539575/conf"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--no-check-certificate', 'https://lamaisondessavoirs.adobeconnect.com/_a1099539575/conf']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.8.2 (CPython) - macOS-10.15.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[AdobeConnect] _a1099539575: Downloading webpage
ERROR: Unable to extract swf url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/oussamah/.virtualenvs/vlj3/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/oussamah/.virtualenvs/vlj3/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/oussamah/.virtualenvs/vlj3/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/Users/oussamah/.virtualenvs/vlj3/lib/python3.8/site-packages/youtube_dl/extractor/adobeconnect.py", line 18, in _real_extract
    qs = compat_parse_qs(self._search_regex(r"swfUrl\s*=\s*'([^']+)'", webpage, 'swf url').split('?')[1])
  File "/Users/oussamah/.virtualenvs/vlj3/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract swf url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

From what I see the adobeconnect extractor is broken. 
I tried at first downloading recordings needing authentication, but I had this `Unable to extract swf url;` issue. I tried with a public link (the one provided) and I had the same issue. 

From what I see the format of the url changed and the extractor is now outdated. I tried looking at it, but could not understand how to use a local version of youtube-dl. 

Help would be much appreciated. If you're short on time, give me some explanation on how to make my own build of youtube-dl and I'll try to debug it

**Comment by remitamine** [comment]
you have to use cookies with this command.

**Comment by oussj** [comment]
@remitamine actually I did it also maybe I was unclear

I tried to download a recording like this : 
youtube-dl --cookies ~/Downloads/adobeconnect.com_cookies.txt --verbose --no-check-certificate "https://lamaisondessavoirs.adobeconnect.com/_a1099539575/conf"

and I have the same issue, that's why I think it's due to the extractor being outdated

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', '/Users/oussamah/Downloads/adobeconnect.com_cookies.txt', '--verbose', '--no-check-certificate', 'https://lamaisondessavoirs.adobeconnect.com/_a1099539575/conf']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.8.2 (CPython) - macOS-10.15.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[AdobeConnect] _a1099539575: Downloading webpage
Traceback (most recent call last):
  File "/Users/oussamah/.virtualenvs/vlj3/bin/youtube-dl", line 10, in <module>
    sys.exit(main())
  File "/Users/oussamah/.virtualenvs/vlj3/lib/python3.8/site-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/Users/oussamah/.virtualenvs/vlj3/lib/python3.8/site-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/Users/oussamah/.virtualenvs/vlj3/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2028, in download
    res = self.extract_info(
  File "/Users/oussamah/.virtualenvs/vlj3/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/Users/oussamah/.virtualenvs/vlj3/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/oussamah/.virtualenvs/vlj3/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/oussamah/.virtualenvs/vlj3/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/Users/oussamah/.virtualenvs/vlj3/lib/python3.8/site-packages/youtube_dl/extractor/adobeconnect.py", line 18, in _real_extract
    qs = compat_parse_qs(self._search_regex(r"swfUrl\s*=\s*'([^']+)'", webpage, 'swf url').split('?')[1])
IndexError: list index out of range
```

What do you think ? Am I not using the cookies correctly ?

**Comment by remitamine** [comment]
i know that Adobe Connect started moving from relying on Flash Player by offering an HTML5 player that serves RTMP streams over WebSocket, i'm not sure if this is related or not.

**Comment by oussj** [comment]
@remitamine I sent you the credentials on your gmail remitamine@gmail.com
Did you receive them ?

**Comment by remitamine** [comment]
yes, i will check later, if it's the same problem(RTMP over Websocket) then i'm not plaining to work on it.

**Comment by oussj** [comment]
ok, let me know !

**Comment by remitamine** [comment]
from [Adobe Flash Player EOL General Information Page](https://www.adobe.com/products/flashplayer/end-of-life.html#):
> Adobe will block Flash content from running in Flash Player beginning January 12, 2021

the Flash Player plugin in Chrome now refuse to load flash content, which is needed to check what has changed in relation to raw RTMP streams, so this will likely end up with RTMP over Websocket path as the only way to bringback support for the website.

**Comment by oussj** [comment]
ok thanks for looking at it, do you know another tool able to handle such streams ?

**Comment by remitamine** [comment]
> do you know another tool able to handle such streams?

no.
