### ISSUE TITLE
[redbulltv.com] specific video causes an exception

### ISSUE THREAD

**Issue by katbyte** [ytdl-org/youtube-dl#27775]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[12:10:48] kt@katbook:~/Downloads$ youtube-dl -F -v https://www.redbull.com/ca-en/films/full-moon
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-w', '-o', '%(title)s.%(ext)s', '-v', 'https://www.redbull.com/ca-en/films/full-moon']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.9.1 (CPython) - macOS-11.1-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[RedBull] full-moon: Downloading JSON metadata
[RedBullEmbed] rrn:content:films:c82b9742-a6c4-53a3-b0fb-4d16a47d8a25:en-INT: Downloading JSON metadata
[RedBullEmbed] AA-1Q8UWHFXW1W12: Downloading access token
[RedBullEmbed] AA-1Q8UWHFXW1W12: Downloading video information
ERROR: An extractor error has occurred. (caused by KeyError('error')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2248, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/extractor/redbulltv.py", line 70, in extract_info
    video = self._download_json(
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 893, in _download_json
    res = self._download_json_handle(
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 872, in _download_json_handle
    res = self._download_webpage_handle(
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 665, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 650, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/extractor/redbulltv.py", line 145, in _real_extract
    return self.extract_info(asset_id)
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/extractor/redbulltv.py", line 77, in extract_info
    error_message = self._parse_json(
KeyError: 'error'
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2248, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/extractor/redbulltv.py", line 70, in extract_info
    video = self._download_json(
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 893, in _download_json
    res = self._download_json_handle(
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 872, in _download_json_handle
    res = self._download_webpage_handle(
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 665, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 650, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/extractor/redbulltv.py", line 145, in _real_extract
    return self.extract_info(asset_id)
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/extractor/redbulltv.py", line 77, in extract_info
    error_message = self._parse_json(
KeyError: 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.8/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 545, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('error')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

Out of the many videos i've downloaded from this site, this one causes an exception

**Comment by katbyte** [comment]
this one also fails: https://www.redbull.com/ca-en/films/supervention

**Comment by october262** [comment]
for this link -  https://www.redbull.com/ca-en/films/supervention
you can press F12 on your keyboard to bring up the debug menu 
there, select network - all - type m3u8 in the search box and select either playlist.m3u8
or playlist.m3u8?namespace, both will copy and playback but for some reason,
there's no audio

**Comment by katbyte** [comment]
Thats probably because the audio and video are streamed separately, an example from another video on redbull tv:

```
[info] Available formats for AA-1Q6WWGFWW1W12:
format code        extension  resolution note
hls-audio-English  mp4        audio only [eng]
hls-572            mp4        426x240     572k , avc1.4D401E, video only
hls-911            mp4        640x360     911k , avc1.4D401E, video only
hls-1588           mp4        960x540    1588k , avc1.4D401F, video only
hls-2985           mp4        1280x720   2985k , avc1.4D401F, video only
hls-5975           mp4        1920x1080  5975k , avc1.640028, video only (best)
```
