### ISSUE TITLE
[iPrima] now requires a login (via oauth2) to watch any videos

### ISSUE THREAD

**Issue by Wlezley** [ytdl-org/youtube-dl#27789]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://prima.iprima.cz/porady/sefem-za-par-minut/8-epizoda']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.08
[debug] Python version 2.7.13 (CPython) - Linux-3.16.6-042stab145.3-x86_64-with-debian-9.13
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1, rtmpdump 2.4
[debug] Proxy map: {}
[IPrima] 8-epizoda: Downloading webpage
[IPrima] p772895: Downloading player
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/iprima.py", line 141, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1367, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

iPrima now requires a login to watch any videos. Login seems to be done via oauth2 on "https://auth.iprima.cz/user/login" URL.
When I'm logged in and I manually find the manifest.mpd file, the video can be downloaded using this link.
I also tried to use the --cookies option (with my cookies.txt file), but it doesn't work.
Login via -u -p does not work because iPrima downloader does not have it (yet).

**Comment by pinochico** [comment]
I can't find any manifest.mpd file. Where is?

**Comment by pinochico** [comment]
Ok, the last function solution is only find file playlist.m3u8 and convert by vlc (if is not problem by DRM)
I'm waiting for right solution.

**Comment by 89z** [comment]
Issue should be closed, account required
