### ISSUE TITLE
wstream.video site support request

### ISSUE THREAD

**Issue by auscia** [ytdl-org/youtube-dl#27788]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.01.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

-  https://wstream.video/video6zvimpy52/gkrdbr4pnww4

## Description

WRITE DESCRIPTION HERE

C:\dplay>youtube-dl https://wstream.video/video6zvimpy52/gkrdbr4pnww4 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://wstream.video/video6zvimpy52/gkrdbr4pnww4', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Proxy map: {}
[generic] gkrdbr4pnww4: Requesting header
WARNING: Falling back on generic information extractor.
[generic] gkrdbr4pnww4: Downloading webpage
[generic] gkrdbr4pnww4: Extracting information
ERROR: Unsupported URL: https://wstream.video/video6zvimpy52/gkrdbr4pnww4
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\extractor\generic.py", line 3467, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://wstream.video/video6zvimpy52/gkrdbr4pnww4

**Comment by october262** [comment]
youtube-dl --no-check-certificate https://wdex97.fastcdn.stream/hls/lnhoijxxfx5ee35huvjkci5hlinad2evq3hbwourrptkf2klmnbgd2qzx6ja/index-v1-a1.m3u8

**Comment by Mennaruuk** [comment]
The .m3u8 URL changes regularly, so this is a little tricky.
