### ISSUE TITLE
Convert audio codec failed!

### ISSUE THREAD

**Issue by llwmagic** [ytdl-org/youtube-dl#27799]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.01.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--proxy', 'http://127.0.0.1:10809', 'https://www.youtube.com/watch?v=f-gdp4Tu3HQ', '-i', '-f', '139', '--add-metadata', '--xattrs', '--prefer-ffmpeg', '--ffmpeg-location', 'E:/VideoProc_Release/videopro_win/VideoPro/debug', '--hls-use-mpegts', '--no-part', '--rm-cache-dir', '--no-playlist', '--embed-thumbnail', '-x', '--audio-format', 'mp3', '--cookies', 'C:\\\\Users\\\\kaifaniuB2\\\\AppData\\\\Roaming\\\\VideoProc\\\\cookies1.txt', '-o', 'temp.mp3', '-v']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {'https': 'http://127.0.0.1:10809', 'http': 'http://127.0.0.1:10809'}
Removing cache dir C:\Users\kaifaniuB2/.cache\youtube-dl ...
[youtube] f-gdp4Tu3HQ: Downloading webpage
[youtube] Downloading just video f-gdp4Tu3HQ because of --no-playlist
[youtube] {18} signature length 108, html5 player 9f996d3e
[youtube] f-gdp4Tu3HQ: Downloading player https://www.youtube.com/s/player/9f996d3e/player_ias.vflset/en_US/base.js
[youtube] {22} signature length 108, html5 player 9f996d3e
[youtube] {137} signature length 108, html5 player 9f996d3e
[youtube] {248} signature length 104, html5 player 9f996d3e
[youtube] f-gdp4Tu3HQ: Downloading player https://www.youtube.com/s/player/9f996d3e/player_ias.vflset/en_US/base.js
[youtube] {136} signature length 104, html5 player 9f996d3e
[youtube] {247} signature length 104, html5 player 9f996d3e
[youtube] {135} signature length 108, html5 player 9f996d3e
[youtube] {244} signature length 108, html5 player 9f996d3e
[youtube] {134} signature length 108, html5 player 9f996d3e
[youtube] {243} signature length 104, html5 player 9f996d3e
[youtube] {133} signature length 108, html5 player 9f996d3e
[youtube] {242} signature length 104, html5 player 9f996d3e
[youtube] {160} signature length 108, html5 player 9f996d3e
[youtube] {278} signature length 108, html5 player 9f996d3e
[youtube] {140} signature length 108, html5 player 9f996d3e
[youtube] {251} signature length 108, html5 player 9f996d3e
[youtube] f-gdp4Tu3HQ: Downloading MPD manifest
[youtube] f-gdp4Tu3HQ: Downloading thumbnail ...
[youtube] f-gdp4Tu3HQ: Writing thumbnail to: temp.mp3.jpg
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1610553914/ei/2sX-X_2IC5SxkgaR7ojwCg/ip/2605%3A52c0%3A2%3A536%3A0%3A0%3A0%3A0/id/7fe81da784eedc74/source/youtube/requiressl/yes/playback_host/r4---sn-a5meknle.googlevideo.com/mh/kc/mm/31%2C29/mn/sn-a5meknle%2Csn-a5mlrnek/ms/au%2Crdu/mv/m/mvi/4/pl/48/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/2370000/vprv/1/mt/1610532036/fvip/4/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRgIhAMHklE1GU25R8G6smqTZJnBg6gSpkajkiPyVqFCB5rusAiEA8GtDlaaaekGVqW0g3WV9jcYYW2_wHdr5QcaoTBTJvGw%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRgIhALPI6F7Cqhrx9Iox8tQflrIDmhue8pRau80JSqmB6Bb8AiEA5NayHf_5XQ8O0_1YSIXufKasJiDii3-QCq0ISQajaY0%3D'
[dashsegments] Total fragments: 39
[download] Destination: temp.mp3

[download]   2.6% of ~22.62KiB at 144.99KiB/s ETA 00:35
[download]   2.6% of ~22.62KiB at 144.99KiB/s ETA 00:35
[download]   0.3% of ~586.85KiB at 144.99KiB/s ETA 16:16
[download]   0.6% of ~586.85KiB at 144.99KiB/s ETA 07:09
[download]   1.3% of ~586.85KiB at 144.99KiB/s ETA 03:21
[download]   2.7% of ~586.85KiB at 144.99KiB/s ETA 01:36
[download]   5.1% of ~586.85KiB at 144.99KiB/s ETA 00:48
[download]   5.1% of ~586.85KiB at 144.99KiB/s ETA 00:48
[download]   4.0% of ~772.08KiB at 52.63KiB/s ETA 01:44 
[download]   4.3% of ~772.08KiB at 157.89KiB/s ETA 01:37
[download]   4.8% of ~772.08KiB at 349.98KiB/s ETA 01:26
[download]   5.8% of ~772.08KiB at 749.96KiB/s ETA 01:10
[download]   7.7% of ~772.08KiB at  1.43MiB/s ETA 00:52 
[download]   7.7% of ~772.08KiB at  1.43MiB/s ETA 00:52 
[download]   7.0% of ~861.82KiB at  1.43MiB/s ETA 01:09 
[download]   7.2% of ~861.82KiB at  1.43MiB/s ETA 01:07 
[download]   7.7% of ~861.82KiB at  1.43MiB/s ETA 01:03 
[download]   8.6% of ~861.82KiB at  7.32MiB/s ETA 00:55 
[download]  10.3% of ~861.82KiB at 537.03KiB/s ETA 00:46
[download]  10.3% of ~861.82KiB at 537.03KiB/s ETA 00:46
[download]   9.7% of ~917.28KiB at 45.45KiB/s ETA 00:55 
[download]  10.0% of ~917.28KiB at 130.43KiB/s ETA 00:54
[download]  10.4% of ~917.28KiB at 304.34KiB/s ETA 00:51
[download]  11.3% of ~917.28KiB at 624.98KiB/s ETA 00:47
[download]  12.8% of ~917.28KiB at  1.10MiB/s ETA 00:40 
[download]  12.8% of ~917.28KiB at  1.10MiB/s ETA 00:40 
[download]  12.4% of ~953.65KiB at 45.45KiB/s ETA 00:48 
[download]  12.6% of ~953.65KiB at 136.36KiB/s ETA 00:47
[download]  13.1% of ~953.65KiB at 304.34KiB/s ETA 00:45
[download]  13.9% of ~953.65KiB at 652.15KiB/s ETA 00:42
[download]  15.4% of ~953.65KiB at  1.14MiB/s ETA 00:37 
[download]  15.4% of ~953.65KiB at  1.14MiB/s ETA 00:37 
[download]  15.1% of ~978.04KiB at 999.83KiB/s ETA 00:43
[download]  15.3% of ~978.04KiB at  2.93MiB/s ETA 00:42 
[download]  15.7% of ~978.04KiB at  6.83MiB/s ETA 00:41 
[download]  16.5% of ~978.04KiB at  7.32MiB/s ETA 00:39 
[download]  17.9% of ~978.04KiB at 14.07MiB/s ETA 00:35 
[download]  17.9% of ~978.04KiB at 14.07MiB/s ETA 00:35 
[download]  17.7% of ~999.21KiB at 55.55KiB/s ETA 00:43 
[download]  17.9% of ~999.21KiB at 166.66KiB/s ETA 00:43
[download]  18.3% of ~999.21KiB at 388.87KiB/s ETA 00:41
[download]  19.1% of ~999.21KiB at 833.28KiB/s ETA 00:39
[download]  20.5% of ~999.21KiB at  1.51MiB/s ETA 00:36 
[download]  20.5% of ~999.21KiB at  1.51MiB/s ETA 00:36 
[download]  20.3% of ~1013.79KiB at  1.51MiB/s ETA 00:42
[download]  20.5% of ~1013.79KiB at  1.51MiB/s ETA 00:41
[download]  20.9% of ~1013.79KiB at  1.51MiB/s ETA 00:40
[download]  21.7% of ~1013.79KiB at  1.51MiB/s ETA 00:38
[download]  23.1% of ~1013.79KiB at  1.51MiB/s ETA 00:35
[download]  23.1% of ~1013.79KiB at  1.51MiB/s ETA 00:35
[download]  22.9% of ~1.00MiB at 998.88KiB/s ETA 00:39  
[download]  23.1% of ~1.00MiB at  2.93MiB/s ETA 00:39   
[download]  23.5% of ~1.00MiB at  6.83MiB/s ETA 00:38   
[download]  24.3% of ~1.00MiB at 14.63MiB/s ETA 00:36   
[download]  25.6% of ~1.00MiB at 28.31MiB/s ETA 00:34   
[download]  25.6% of ~1.00MiB at 28.31MiB/s ETA 00:34   
[download]  25.5% of ~1.01MiB at 50.00KiB/s ETA 00:38   
[download]  25.7% of ~1.01MiB at 142.85KiB/s ETA 00:38  
[download]  26.1% of ~1.01MiB at 333.32KiB/s ETA 00:37  
[download]  26.8% of ~1.01MiB at 681.79KiB/s ETA 00:36  
[download]  28.2% of ~1.01MiB at 427.28KiB/s ETA 00:33  
[download]  28.2% of ~1.01MiB at 427.28KiB/s ETA 00:33  
[download]  28.1% of ~1.02MiB at 45.45KiB/s ETA 00:38   
[download]  28.3% of ~1.02MiB at 130.42KiB/s ETA 00:37  
[download]  28.6% of ~1.02MiB at 304.32KiB/s ETA 00:37  
[download]  29.4% of ~1.02MiB at 624.95KiB/s ETA 00:35  
[download]  30.8% of ~1.02MiB at  1.14MiB/s ETA 00:33   
[download]  30.8% of ~1.02MiB at  1.14MiB/s ETA 00:33   
[download]  30.7% of ~1.03MiB at 45.45KiB/s ETA 00:35   
[download]  30.9% of ~1.03MiB at 136.36KiB/s ETA 00:35  
[download]  31.2% of ~1.03MiB at 304.33KiB/s ETA 00:34  
[download]  32.0% of ~1.03MiB at 652.14KiB/s ETA 00:33  
[download]  33.3% of ~1.03MiB at  1.18MiB/s ETA 00:31   
[download]  33.3% of ~1.03MiB at  1.18MiB/s ETA 00:31   
[download]  33.2% of ~1.03MiB at 50.00KiB/s ETA 00:35   
[download]  33.4% of ~1.03MiB at 142.85KiB/s ETA 00:34  
[download]  33.8% of ~1.03MiB at 333.32KiB/s ETA 00:34  
[download]  34.5% of ~1.03MiB at 681.79KiB/s ETA 00:33  
[download]  35.9% of ~1.03MiB at 436.54KiB/s ETA 00:31  
[download]  35.9% of ~1.03MiB at 436.54KiB/s ETA 00:31  
[download]  35.8% of ~1.04MiB at 436.54KiB/s ETA 00:34  
[download]  36.0% of ~1.04MiB at 436.54KiB/s ETA 00:34  
[download]  36.4% of ~1.04MiB at 436.54KiB/s ETA 00:33  
[download]  37.1% of ~1.04MiB at 436.54KiB/s ETA 00:32  
[download]  38.5% of ~1.04MiB at 692.15KiB/s ETA 00:30  
[download]  38.5% of ~1.04MiB at 692.15KiB/s ETA 00:30  
[download]  38.4% of ~1.04MiB at 692.15KiB/s ETA 00:32  
[download]  38.6% of ~1.04MiB at 692.15KiB/s ETA 00:32  
[download]  39.0% of ~1.04MiB at 692.15KiB/s ETA 00:31  
[download]  39.7% of ~1.04MiB at 692.15KiB/s ETA 00:30  
[download]  41.0% of ~1.04MiB at 692.15KiB/s ETA 00:28  
[download]  41.0% of ~1.04MiB at 692.15KiB/s ETA 00:28  
[download]  41.0% of ~1.05MiB at 692.15KiB/s ETA 00:31  
[download]  41.1% of ~1.05MiB at 692.15KiB/s ETA 00:30  
[download]  41.5% of ~1.05MiB at 692.15KiB/s ETA 00:30  
[download]  42.3% of ~1.05MiB at 692.15KiB/s ETA 00:29  
[download]  43.6% of ~1.05MiB at 14.25MiB/s ETA 00:27   
[download]  43.6% of ~1.05MiB at 14.25MiB/s ETA 00:27   
[download]  43.5% of ~1.05MiB at 999.83KiB/s ETA 00:30  
[download]  43.7% of ~1.05MiB at  1.46MiB/s ETA 00:29   
[download]  44.1% of ~1.05MiB at  3.42MiB/s ETA 00:29   
[download]  44.8% of ~1.05MiB at  4.88MiB/s ETA 00:28   
[download]  46.2% of ~1.05MiB at 633.64KiB/s ETA 00:27  
[download]  46.2% of ~1.05MiB at 633.64KiB/s ETA 00:27  
[download]  46.1% of ~1.05MiB at 633.64KiB/s ETA 00:28  
[download]  46.3% of ~1.05MiB at 633.64KiB/s ETA 00:28  
[download]  46.7% of ~1.05MiB at  3.42MiB/s ETA 00:27   
[download]  47.4% of ~1.05MiB at  7.32MiB/s ETA 00:27   
[download]  48.7% of ~1.05MiB at  9.41MiB/s ETA 00:25   
[download]  48.7% of ~1.05MiB at  9.41MiB/s ETA 00:25   
[download]  48.7% of ~1.05MiB at  9.41MiB/s ETA 00:26   
[download]  48.9% of ~1.05MiB at  9.41MiB/s ETA 00:26   
[download]  49.2% of ~1.05MiB at  9.41MiB/s ETA 00:25   
[download]  50.0% of ~1.05MiB at  9.41MiB/s ETA 00:25   
[download]  51.3% of ~1.05MiB at  9.41MiB/s ETA 00:23   
[download]  51.3% of ~1.05MiB at  9.41MiB/s ETA 00:23   
[download]  51.2% of ~1.06MiB at 52.63KiB/s ETA 00:25   
[download]  51.4% of ~1.06MiB at 157.89KiB/s ETA 00:25  
[download]  51.8% of ~1.06MiB at 349.98KiB/s ETA 00:24  
[download]  52.5% of ~1.06MiB at 749.96KiB/s ETA 00:24  
[download]  53.8% of ~1.06MiB at 434.98KiB/s ETA 00:22  
[download]  53.8% of ~1.06MiB at 434.98KiB/s ETA 00:22  
[download]  53.8% of ~1.06MiB at 58.82KiB/s ETA 00:23   
[download]  54.0% of ~1.06MiB at 176.46KiB/s ETA 00:23  
[download]  54.4% of ~1.06MiB at 388.87KiB/s ETA 00:23  
[download]  55.1% of ~1.06MiB at 789.43KiB/s ETA 00:22  
[download]  56.4% of ~1.06MiB at 437.36KiB/s ETA 00:21  
[download]  56.4% of ~1.06MiB at 437.36KiB/s ETA 00:21  
[download]  56.4% of ~1.06MiB at 999.83KiB/s ETA 00:22  
[download]  56.6% of ~1.06MiB at  1.46MiB/s ETA 00:21   
[download]  56.9% of ~1.06MiB at  3.42MiB/s ETA 00:21   
[download]  57.7% of ~1.06MiB at  4.88MiB/s ETA 00:20   
[download]  59.0% of ~1.06MiB at 619.56KiB/s ETA 00:19  
[download]  59.0% of ~1.06MiB at 619.56KiB/s ETA 00:19  
[download]  59.0% of ~1.06MiB at 619.56KiB/s ETA 00:20  
[download]  59.1% of ~1.06MiB at 619.56KiB/s ETA 00:20  
[download]  59.5% of ~1.06MiB at  3.42MiB/s ETA 00:20   
[download]  60.2% of ~1.06MiB at  7.32MiB/s ETA 00:19   
[download]  61.5% of ~1.06MiB at  7.13MiB/s ETA 00:18   
[download]  61.5% of ~1.06MiB at  7.13MiB/s ETA 00:18   
[download]  61.5% of ~1.06MiB at 47.62KiB/s ETA 00:19   
[download]  61.7% of ~1.06MiB at 136.36KiB/s ETA 00:19  
[download]  62.1% of ~1.06MiB at 318.17KiB/s ETA 00:19  
[download]  62.8% of ~1.06MiB at 652.15KiB/s ETA 00:18  
[download]  64.1% of ~1.06MiB at  1.17MiB/s ETA 00:17   
[download]  64.1% of ~1.06MiB at  1.17MiB/s ETA 00:17   
[download]  64.1% of ~1.07MiB at 45.45KiB/s ETA 00:18   
[download]  64.3% of ~1.07MiB at 136.36KiB/s ETA 00:18  
[download]  64.6% of ~1.07MiB at 318.17KiB/s ETA 00:17  
[download]  65.4% of ~1.07MiB at 652.15KiB/s ETA 00:17  
[download]  66.7% of ~1.07MiB at  1.19MiB/s ETA 00:16   
[download]  66.7% of ~1.07MiB at  1.19MiB/s ETA 00:16   
[download]  66.7% of ~1.07MiB at  3.89KiB/s ETA 00:17   
[download]  66.8% of ~1.07MiB at 11.67KiB/s ETA 00:16   
[download]  67.2% of ~1.07MiB at 27.13KiB/s ETA 00:16   
[download]  67.9% of ~1.07MiB at 57.91KiB/s ETA 00:16   
[download]  69.2% of ~1.07MiB at 112.38KiB/s ETA 00:15  
[download]  69.2% of ~1.07MiB at 112.38KiB/s ETA 00:15  
[download]  69.2% of ~1.07MiB at 112.38KiB/s ETA 00:16  
[download]  69.4% of ~1.07MiB at 112.38KiB/s ETA 00:15  
[download]  69.8% of ~1.07MiB at 112.38KiB/s ETA 00:15  
[download]  70.5% of ~1.07MiB at 112.38KiB/s ETA 00:15  
[download]  71.8% of ~1.07MiB at 112.38KiB/s ETA 00:14  
[download]  71.8% of ~1.07MiB at 112.38KiB/s ETA 00:14  
[download]  71.8% of ~1.07MiB at 112.38KiB/s ETA 00:15  
[download]  72.0% of ~1.07MiB at  2.93MiB/s ETA 00:15   
[download]  72.3% of ~1.07MiB at  6.83MiB/s ETA 00:14   
[download]  73.1% of ~1.07MiB at 14.64MiB/s ETA 00:14   
[download]  74.4% of ~1.07MiB at 14.17MiB/s ETA 00:13   
[download]  74.4% of ~1.07MiB at 14.17MiB/s ETA 00:13   
[download]  74.4% of ~1.07MiB at 14.17MiB/s ETA 00:13   
[download]  74.5% of ~1.07MiB at 14.17MiB/s ETA 00:13   
[download]  74.9% of ~1.07MiB at 14.17MiB/s ETA 00:13   
[download]  75.6% of ~1.07MiB at 14.17MiB/s ETA 00:12   
[download]  76.9% of ~1.07MiB at 14.24MiB/s ETA 00:11   
[download]  76.9% of ~1.07MiB at 14.24MiB/s ETA 00:11   
[download]  76.9% of ~1.07MiB at 14.24MiB/s ETA 00:12   
[download]  77.1% of ~1.07MiB at 14.24MiB/s ETA 00:12   
[download]  77.5% of ~1.07MiB at  3.42MiB/s ETA 00:11   
[download]  78.2% of ~1.07MiB at  7.32MiB/s ETA 00:11   
[download]  79.5% of ~1.07MiB at  9.45MiB/s ETA 00:10   
[download]  79.5% of ~1.07MiB at  9.45MiB/s ETA 00:10   
[download]  79.5% of ~1.07MiB at  9.45MiB/s ETA 00:10   
[download]  79.7% of ~1.07MiB at  1.46MiB/s ETA 00:10   
[download]  80.0% of ~1.07MiB at  3.42MiB/s ETA 00:10   
[download]  80.8% of ~1.07MiB at  4.88MiB/s ETA 00:10   
[download]  82.1% of ~1.07MiB at  7.11MiB/s ETA 00:09   
[download]  82.1% of ~1.07MiB at  7.11MiB/s ETA 00:09   
[download]  82.1% of ~1.08MiB at  7.11MiB/s ETA 00:09   
[download]  82.2% of ~1.08MiB at  7.11MiB/s ETA 00:09   
[download]  82.6% of ~1.08MiB at  3.42MiB/s ETA 00:09   
[download]  83.3% of ~1.08MiB at  7.32MiB/s ETA 00:08   
[download]  84.6% of ~1.08MiB at  9.50MiB/s ETA 00:08   
[download]  84.6% of ~1.08MiB at  9.50MiB/s ETA 00:08   
[download]  84.6% of ~1.08MiB at  3.69KiB/s ETA 00:08   
[download]  84.8% of ~1.08MiB at 11.07KiB/s ETA 00:08   
[download]  85.2% of ~1.08MiB at 25.73KiB/s ETA 00:08   
[download]  85.9% of ~1.08MiB at 55.14KiB/s ETA 00:07   
[download]  87.2% of ~1.08MiB at 106.72KiB/s ETA 00:06  
[download]  87.2% of ~1.08MiB at 106.72KiB/s ETA 00:06  
[download]  87.2% of ~1.08MiB at 106.72KiB/s ETA 00:07  
[download]  87.4% of ~1.08MiB at 106.72KiB/s ETA 00:06  
[download]  87.8% of ~1.08MiB at  3.42MiB/s ETA 00:06   
[download]  88.5% of ~1.08MiB at  7.32MiB/s ETA 00:06   
[download]  89.7% of ~1.08MiB at  7.04MiB/s ETA 00:05   
[download]  89.7% of ~1.08MiB at  7.04MiB/s ETA 00:05   
[download]  89.8% of ~1.08MiB at  7.04MiB/s ETA 00:05   
[download]  89.9% of ~1.08MiB at  7.04MiB/s ETA 00:05   
[download]  90.3% of ~1.08MiB at  7.04MiB/s ETA 00:05   
[download]  91.0% of ~1.08MiB at 14.64MiB/s ETA 00:04   
[download]  92.3% of ~1.08MiB at 28.50MiB/s ETA 00:04   
[download]  92.3% of ~1.08MiB at 28.50MiB/s ETA 00:04   
[download]  92.3% of ~1.08MiB at 28.50MiB/s ETA 00:04   
[download]  92.5% of ~1.08MiB at  2.93MiB/s ETA 00:04   
[download]  92.9% of ~1.08MiB at  6.83MiB/s ETA 00:03   
[download]  93.6% of ~1.08MiB at  7.32MiB/s ETA 00:03   
[download]  94.9% of ~1.08MiB at  9.45MiB/s ETA 00:02   
[download]  94.9% of ~1.08MiB at  9.45MiB/s ETA 00:02   
[download]  94.9% of ~1.08MiB at  5.78KiB/s ETA 00:02   
[download]  95.1% of ~1.08MiB at 17.34KiB/s ETA 00:02   
[download]  95.4% of ~1.08MiB at 40.46KiB/s ETA 00:02   
[download]  96.2% of ~1.08MiB at 86.20KiB/s ETA 00:02   
[download]  97.4% of ~1.08MiB at 167.83KiB/s ETA 00:01  
[download]  97.4% of ~1.08MiB at 167.83KiB/s ETA 00:01  
[download]  98.4% of ~1.07MiB at 167.83KiB/s ETA 00:00  
[download]  98.6% of ~1.07MiB at 167.83KiB/s ETA 00:00  
[download]  99.0% of ~1.07MiB at 167.83KiB/s ETA 00:00  
[download]  99.7% of ~1.07MiB at  7.32MiB/s ETA 00:00   
[download] 100.0% of ~1.07MiB at  9.00MiB/s ETA 00:00   
[download] 100.0% of ~1.07MiB at  9.00MiB/s ETA 00:00   
[download] 100% of 1.07MiB in 00:52                     
[ffmpeg] Correcting container in "temp.mp3"
[debug] ffmpeg command line: "E:/VideoProc_Release/videopro_win/VideoPro/debug\ffmpeg" -y -loglevel "repeat+info" -i "file:temp.mp3" -c copy -f mp4 "file:temp.temp.mp3"
[debug] ffmpeg command line: "E:/VideoProc_Release/videopro_win/VideoPro/debug\ffprobe" -show_streams "file:temp.mp3"
[ffmpeg] Post-process file temp.mp3 exists, skipping
[ffmpeg] Adding metadata to 'temp.mp3'
[debug] ffmpeg command line: "E:/VideoProc_Release/videopro_win/VideoPro/debug\ffmpeg" -y -loglevel "repeat+info" -i "file:temp.mp3" -c copy -metadata "title=佳人曲 中国古典舞 美国 A Beauty in the North" -metadata "purl=https://www.youtube.com/watch?v=f-gdp4Tu3HQ" -metadata "date=20180712" -metadata "comment=" -metadata "artist=Maxi Billion" -metadata "description=" "file:temp.temp.mp3"
ERROR: exit program 1 (fftools/ffmpeg.c:4897)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\YoutubeDL.py", line 2075, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\postprocessor\ffmpeg.py", line 509, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: exit program 1 (fftools/ffmpeg.c:4897)

[ffmpeg] Correcting extension to webp and escaping path for thumbnail "temp.mp3.jpg"
[ffmpeg] Converting thumbnail "temp.mp3.webp" to JPEG
[debug] ffmpeg command line: "E:/VideoProc_Release/videopro_win/VideoPro/debug\ffmpeg" -y -loglevel "repeat+info" -i "file:temp.mp3.webp" "-bsf:v" mjpeg2jpeg "file:temp.mp3.jpg"
[ffmpeg] Adding thumbnail to "temp.mp3"
[debug] ffmpeg command line: "E:/VideoProc_Release/videopro_win/VideoPro/debug\ffmpeg" -y -loglevel "repeat+info" -i "file:temp.mp3" -i "file:temp.mp3.jpg" -c copy -map 0 -map 1 "-metadata:s:v" "title=\"Album cover\"" "-metadata:s:v" "comment=\"Cover (Front)\"" "file:temp.temp.mp3"
ERROR: exit program 1 (fftools/ffmpeg.c:4897)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\YoutubeDL.py", line 2075, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\postprocessor\embedthumbnail.py", line 84, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: exit program 1 (fftools/ffmpeg.c:4897)

[metadata] Writing metadata to file's xattrs

```

## Description

WRITE DESCRIPTION HERE
Hi, I've find a bug here! 
Wrong file will be generated when I input arguments which include "-x --audio-format mp3 -o temp.mp3".
It seems like downloaded file will change name first(-o temp.mp3) then convert audio codec(-x --audio-format mp3),
As a result, FFmpegExtractAudioPP will get a input path which is the same as new_path(temp.mp3).

**Comment by remitamine** [comment]
don't hardcode file extension.
