### ISSUE TITLE
ERROR: unable to download video data: <urlopen error [Errno 0] Error> again!

### ISSUE THREAD

**Issue by iBobbyTS** [ytdl-org/youtube-dl#27800]
Command: 
`youtube-dl "https://www.youtube.com/watch?v=linlz7-Pnvw" -f 337+251 --proxy "socks5://127.0.0.1:1086" --verbose -R infinite`
Output:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=linlz7-Pnvw', '-f', '337+251', '--proxy', 'socks5://127.0.0.1:1086', '--verbose', '-R', 'infinite']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.8.5 (CPython) - macOS-10.16-x86_64-i386-64bit
[debug] exe versions: ffmpeg git-2020-12-02-0c8a0d3, ffprobe git-2020-12-02-0c8a0d3, rtmpdump 2.4
[debug] Proxy map: {'http': 'socks5://127.0.0.1:1086', 'https': 'socks5://127.0.0.1:1086'}
[youtube] linlz7-Pnvw: Downloading webpage
[debug] Invoking downloader on 'https://r5---sn-gvnuxaxjvh-v8cs.googlevideo.com/videoplayback?expire=1610558254&ei=ztb-X9CTH9TR7QSKn6co&ip=45.8.158.225&id=o-APM8yloMkXmivYYITSmMQTwS8abHun74dlLBbFJ2IkHl&itag=337&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C272%2C278%2C298%2C299%2C302%2C303%2C308%2C315%2C330%2C331%2C332%2C333%2C334%2C335%2C336%2C337&source=youtube&requiressl=yes&mh=Ot&mm=31%2C29&mn=sn-gvnuxaxjvh-v8cs%2Csn-n8v7znlr&ms=au%2Crdu&mv=m&mvi=5&pcm2cms=yes&pl=23&initcwndbps=1436250&vprv=1&mime=video%2Fwebm&ns=2Zjuj4_dl6TYLSMVE4_YYggF&gir=yes&clen=4131592924&dur=1214.133&lmt=1607213042935453&mt=1610536352&fvip=5&keepalive=yes&c=WEB&txp=5531232&n=AR8TYJuS7lh_DW&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgJvEGlouOyziqbsBx21wzlDWWBrqVrY8o9VYF_dYNaHoCIC5qZ4D_ML08Ld4_GjoHOZtNefMJ3PCqbrGs4RROfVGx&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgewB9MuWGHysrtc2iV_1KPkfFoOS6NfpjNGF3vr88a9kCIQDxkUdXWGlUQFqyl2Vkg2NNLw5xKNCYvCo_xKA5ICkkqQ%3D%3D&ratebypass=yes'
[download] Destination: Switzerland in 8K ULTRA HD HDR - Heaven of Earth (60 FPS)-linlz7-Pnvw.f337.webm
[download]   4.5% of 3.85GiB at  5.14MiB/s ETA 12:12ERROR: unable to download video data: <urlopen error [Errno 0] Error>
Traceback (most recent call last):
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/site-packages/youtube_dl-2021.1.8-py3.8.egg/youtube_dl/utils.py", line 2706, in connect
    self.sock = self._context.wrap_socket(
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/site-packages/youtube_dl-2021.1.8-py3.8.egg/youtube_dl/YoutubeDL.py", line 1930, in process_info
    partial_success = dl(fname, new_info)
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/site-packages/youtube_dl-2021.1.8-py3.8.egg/youtube_dl/YoutubeDL.py", line 1875, in dl
    return fd.download(name, info)
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/site-packages/youtube_dl-2021.1.8-py3.8.egg/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/site-packages/youtube_dl-2021.1.8-py3.8.egg/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/site-packages/youtube_dl-2021.1.8-py3.8.egg/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/site-packages/youtube_dl-2021.1.8-py3.8.egg/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/site-packages/youtube_dl-2021.1.8-py3.8.egg/youtube_dl/YoutubeDL.py", line 2248, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/site-packages/youtube_dl-2021.1.8-py3.8.egg/youtube_dl/utils.py", line 2734, in https_open
    return self.do_open(functools.partial(
  File "/Users/ibobby/opt/anaconda3/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 0] Error>
```

Why I set retries to infinite, I also tried 10000, non of them will retry by it self. If I run the command second time manually, it will continue downloading. 
Is there an option that can really retry by it self?

**Comment by GAS85** [comment]
Have similar problem, simply try to update an app as per here https://github.com/ytdl-org/youtube-dl/issues/22415#issuecomment-531579709
