### ISSUE TITLE
An extractor error has occurred

### ISSUE THREAD

**Issue by jefferson018200306** [ytdl-org/youtube-dl#27812]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.01.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--list-format', '--verbose', 'https://www.viu.com/ott/ph/en-us/vod/318142/True-Beauty', '--no-cache-dir']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.08
[debug] Lazy loading extractors enabled
[debug] Python version 3.8.0 (CPython) - Linux-3.10.65-gd1ee5ec-armv7l-with-libc
[debug] exe versions: libffmpeg.bin.so 4.2.1, libffprobe.bin.so 4.2.1
[debug] Proxy map: {}
ERROR: An extractor error has occurred. (caused by KeyError('data')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/viu.py", line 226, in _real_extract
    stream_data = self._download_json(
KeyError: 'data'
Traceback (most recent call last):
  File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/viu.py", line 226, in _real_extract
    stream_data = self._download_json(
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/common.py", line 545, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('data')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

## Description

I don't know if the problem is the site or the youtube-dl.... Maybe you can obtain the video if there is a built-in account created on YouTube-dl... If nothing works, then maybe the problem is the site... It always saying "Sorry error occurs"

**Comment by jefferson018200306** [comment]
`why duplicate`

**Comment by jefferson018200306** [comment]
@dstftw I'm sorry for asking but could you please give me the Issue number related on this issue?
