### ISSUE TITLE
DiscoveryPlus falling back to general extractor

### ISSUE THREAD

**Issue by Sipherdrakon** [ytdl-org/youtube-dl#27814]
D:\>youtube-dln -v -o "%(title)s [WEBDL-%(height)s].%(ext)s" -f best -i --newline --cookies cookies.txt --console-title --all-subs --embed-subs https://www.discoveryplus.com/video/1990s-the-deadliest-decade/a-dangerous-man
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-o', '%(title)s [WEBDL-%(height)s].%(ext)s', '-f', 'best', '-i', '--newline', '--cookies', 'cookies.txt', '--console-title', '--all-subs', '--embed-subs', 'https://www.discoveryplus.com/video/1990s-the-deadliest-decade/a-dangerous-man']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-05-10-fc99a24, ffprobe git-2020-05-10-fc99a24
[debug] Proxy map: {}
[generic] a-dangerous-man: Requesting header
WARNING: Falling back on generic information extractor.
[generic] a-dangerous-man: Downloading webpage
[generic] a-dangerous-man: Extracting information
ERROR: Unsupported URL: https://www.discoveryplus.com/video/1990s-the-deadliest-decade/a-dangerous-man
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\extractor\generic.py", line 3467, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.discoveryplus.com/video/1990s-the-deadliest-decade/a-dangerous-man

**Comment by Sipherdrakon** [comment]
I'm confused.....I'm using the new version that is supposed to have this issue fixed. I'm providing evidence that it was not, and my issue gets closed?
