### ISSUE TITLE
add-metadata on CW fails

### ISSUE THREAD

**Issue by goodevilgenius** [ytdl-org/youtube-dl#27820]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--add-metadata', 'https://www.cwtv.com/shows/charmed/the-enemy-of-my-frenemy/?play=5f73899b-2c4c-4b1a-9a11-2b6a678e8068']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.9.0 (CPython) - Linux-5.9.14-200.fc33.x86_64-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[CWTV] 5f73899b-2c4c-4b1a-9a11-2b6a678e8068: Downloading JSON metadata
[ThePlatform] 5f73899b-2c4c-4b1a-9a11-2b6a678e8068: Downloading SMIL data
[ThePlatform] 5f73899b-2c4c-4b1a-9a11-2b6a678e8068: Downloading m3u8 information
[ThePlatform] 5f73899b-2c4c-4b1a-9a11-2b6a678e8068: Downloading m3u8 information
[ThePlatform] 5f73899b-2c4c-4b1a-9a11-2b6a678e8068: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://stream-hls.cwtv.com/nosec/The_CW/891/9/81463877640/Charmed-216-TheEnemyOfMyFrenemy-P216-CW_81463365697_m3u8_video_1920x1080_8000000_primary_audio_eng_8.m3u8'
[download] Destination: The Enemy of My Frenemy-5f73899b-2c4c-4b1a-9a11-2b6a678e8068.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.121 Safari/537.36
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-us,en;q=0.5
' -i https://stream-hls.cwtv.com/nosec/The_CW/891/9/81463877640/Charmed-216-TheEnemyOfMyFrenemy-P216-CW_81463365697_m3u8_video_1920x1080_8000000_primary_audio_eng_8.m3u8 -c copy -f mp4 'file:The Enemy of My Frenemy-5f73899b-2c4c-4b1a-9a11-2b6a678e8068.mp4.part'
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' --extra-cflags=' ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-liblensfun --enable-libmp3lame --enable-libmysofa --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librav1e --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-vapoursynth --enable-libvpx --enable-vulkan --enable-libglslang --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg --enable-libzvbi --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-lto --enable-libmfx --enable-runtime-cpudetect
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[tcp @ 0x561c6378d840] Starting connection attempt to 8.251.184.124 port 443
[tcp @ 0x561c6378d840] Starting connection attempt to 8.251.182.252 port 443
[tcp @ 0x561c6378d840] Successfully connected to 8.251.184.124 port 443
[hls @ 0x561c63789540] Skip ('#EXT-X-VERSION:4')
[hls @ 0x561c63789540] HLS request for url 'https://stream-hls.cwtv.com/nosec/The_CW/891/9/81463877640/Charmed-216-TheEnemyOfMyFrenemy-P216-CW_81463365697_m3u8_video_1920x1080_8000000_primary_audio_eng_8_00001.ts', offset 0, playlist 0
[hls @ 0x561c63789540] Opening 'https://stream-hls.cwtv.com/nosec/The_CW/891/9/81463877640/Charmed-216-TheEnemyOfMyFrenemy-P216-CW_81463365697_m3u8_video_1920x1080_8000000_primary_audio_eng_8_00001.ts' for reading
[tcp @ 0x561c639c38c0] Starting connection attempt to 8.251.184.124 port 443
[tcp @ 0x561c639c38c0] Successfully connected to 8.251.184.124 port 443
[hls @ 0x561c63789540] HLS request for url 'https://stream-hls.cwtv.com/nosec/The_CW/891/9/81463877640/Charmed-216-TheEnemyOfMyFrenemy-P216-CW_81463365697_m3u8_video_1920x1080_8000000_primary_audio_eng_8_00002.ts', offset 0, playlist 0
[hls @ 0x561c63789540] Opening 'https://stream-hls.cwtv.com/nosec/The_CW/891/9/81463877640/Charmed-216-TheEnemyOfMyFrenemy-P216-CW_81463365697_m3u8_video_1920x1080_8000000_primary_audio_eng_8_00002.ts' for reading
[tcp @ 0x561c63b4d800] Starting connection attempt to 8.251.184.124 port 443
[tcp @ 0x561c63b4d800] Successfully connected to 8.251.184.124 port 443
[h264 @ 0x561c63a30f80] Reinit context to 1920x1088, pix_fmt: yuv420p
[mpegts @ 0x561c638c4700] parser not found for codec timed_id3, packets or times may be invalid.
Input #0, hls, from 'https://stream-hls.cwtv.com/nosec/The_CW/891/9/81463877640/Charmed-216-TheEnemyOfMyFrenemy-P216-CW_81463365697_m3u8_video_1920x1080_8000000_primary_audio_eng_8.m3u8':
  Duration: 00:40:28.47, start: 2.059589, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High), 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(left), 1920x1080 (1920x1088) [SAR 1:1 DAR 16:9], Closed Captions, 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:The Enemy of My Frenemy-5f73899b-2c4c-4b1a-9a11-2b6a678e8068.mp4.part':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (High), 1 reference frame (avc1 / 0x31637661), yuv420p(left), 1920x1080 (0x0) [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
Automatically inserted bitstream filter 'aac_adtstoasc'; args=''
frame=   27 fps=0.0 q=-1.0 size=       0kB time=00:00:01.07 bitrate=   0.4kbits/s speed=1.65x    
frame=   28 fps= 20 q=-1.0 size=       0kB time=00:00:01.12 bitrate=   0.3kbits/s speed=0.784x    
frame=   36 fps= 17 q=-1.0 size=       0kB time=00:00:01.45 bitrate=   0.3kbits/s speed=0.669x    
frame=   38 fps= 12 q=-1.0 size=       0kB time=00:00:01.53 bitrate=   0.2kbits/s speed=0.476x    
frame=   40 fps= 11 q=-1.0 size=       0kB time=00:00:01.62 bitrate=   0.2kbits/s speed=0.43x    
frame=   45 fps= 10 q=-1.0 size=    1024kB time=00:00:01.82 bitrate=4584.8kbits/s speed=0.408x    
  --- trimmed similar output ---
frame=58153 fps=6.6 q=-1.0 size= 2405120kB time=00:40:25.41 bitrate=8123.4kbits/s speed=0.277x    
frame=58156 fps=6.6 q=-1.0 size= 2405120kB time=00:40:25.54 bitrate=8123.0kbits/s speed=0.277x    
frame=58159 fps=6.6 q=-1.0 size= 2405632kB time=00:40:25.66 bitrate=8124.3kbits/s speed=0.277x    
frame=58163 fps=6.6 q=-1.0 size= 2405632kB time=00:40:25.83 bitrate=8123.8kbits/s speed=0.277x    
frame=58166 fps=6.6 q=-1.0 size= 2405632kB time=00:40:25.95 bitrate=8123.4kbits/s speed=0.277x    
frame=58170 fps=6.6 q=-1.0 size= 2406144kB time=00:40:26.12 bitrate=8124.5kbits/s speed=0.277x    
frame=58173 fps=6.6 q=-1.0 size= 2406144kB time=00:40:26.25 bitrate=8124.1kbits/s speed=0.277x    
frame=58174 fps=6.6 q=-1.0 size= 2406400kB time=00:40:26.29 bitrate=8124.8kbits/s speed=0.277x    
No more output streams to write to, finishing.
Not writing 'clli' atom. No content light level info.
Not writing 'mdcv' atom. Missing mastering metadata.
frame=58225 fps=6.6 q=-1.0 Lsize= 2411127kB time=00:40:28.45 bitrate=8133.5kbits/s speed=0.277x    
video:2372011kB audio:37945kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.048599%
Input file #0 (https://stream-hls.cwtv.com/nosec/The_CW/891/9/81463877640/Charmed-216-TheEnemyOfMyFrenemy-P216-CW_81463365697_m3u8_video_1920x1080_8000000_primary_audio_eng_8.m3u8):
  Input stream #0:0 (video): 58225 packets read (2428939281 bytes); 
  Input stream #0:1 (audio): 104586 packets read (38855714 bytes); 
  Input stream #0:2 (data): 13 packets read (3458 bytes); 
  Total: 162824 packets (2467798453 bytes) demuxed
Output file #0 (file:The Enemy of My Frenemy-5f73899b-2c4c-4b1a-9a11-2b6a678e8068.mp4.part):
  Output stream #0:0 (video): 58225 packets muxed (2428939281 bytes); 
  Output stream #0:1 (audio): 104586 packets muxed (38855714 bytes); 
  Total: 162811 packets (2467794995 bytes) muxed
[AVIOContext @ 0x561c63892440] Statistics: 28 seeks, 9437 writeouts
[AVIOContext @ 0x561c63af0080] Statistics: 967021052 bytes read, 0 seeks
[AVIOContext @ 0x561c63b54200] Statistics: 985814848 bytes read, 0 seeks
[AVIOContext @ 0x561c63c42700] Statistics: 51554 bytes read, 0 seeks

[ffmpeg] Downloaded 2468994314 bytes

[download] 100% of 2.30GiB in 02:26:25
[ffmpeg] Adding metadata to 'The Enemy of My Frenemy-5f73899b-2c4c-4b1a-9a11-2b6a678e8068.mp4'
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:The Enemy of My Frenemy-5f73899b-2c4c-4b1a-9a11-2b6a678e8068.mp4' -i 'file:The Enemy of My Frenemy-5f73899b-2c4c-4b1a-9a11-2b6a678e8068.meta' -c copy -metadata 'title=The Enemy of My Frenemy' -metadata date=20200404 -metadata 'description=The Charmed Ones must join forces with Parker when Mel is endangered in the demon world.' -metadata 'comment=The Charmed Ones must join forces with Parker when Mel is endangered in the demon world.' -metadata 'purl=https://www.cwtv.com/shows/charmed/the-enemy-of-my-frenemy/?play=5f73899b-2c4c-4b1a-9a11-2b6a678e8068' -metadata artist=CWTV -metadata show=Charmed -metadata season_number=2 -metadata 'episode_id=Episode 16' -metadata episode_sort=16 -map_metadata 1 'file:The Enemy of My Frenemy-5f73899b-2c4c-4b1a-9a11-2b6a678e8068.temp.mp4'
ERROR: file:The Enemy of My Frenemy-5f73899b-2c4c-4b1a-9a11-2b6a678e8068.meta: Cannot allocate memory
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2074, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/lib/python3.9/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 509, in run
    self.run_ffmpeg_multiple_files(in_filenames, temp_filename, options)
  File "/usr/lib/python3.9/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:The Enemy of My Frenemy-5f73899b-2c4c-4b1a-9a11-2b6a678e8068.meta: Cannot allocate memory

```

## Description

When doing `--add-metadata` on shows downloaded from cwtv, the step to add the metadata fails with the message "Cannot allocate memory". Any additional steps that come after, such as `--embed-subs` or `--xattrs` are never run.

I've only seen this happen on cwtv.com, and I've used `--add-metadata` with multiple sites without issue.

Using ffmpeg, version 4.3.1.

## Metadata file

What follows is the `.meta` file that the ffmpeg error references:

```
;FFMETADATA1
[CHAPTER]
TIMEBASE=1/1000
START=0
END=541042
[CHAPTER]
TIMEBASE=1/1000
START=541042
END=1150459
[CHAPTER]
TIMEBASE=1/1000
START=1150459
END=1504083
[CHAPTER]
TIMEBASE=1/1000
START=1504083
END=1700042
[CHAPTER]
TIMEBASE=1/1000
START=1700042
END=1982500
[CHAPTER]
TIMEBASE=1/1000
START=1982500
END=0
```

**Comment by dstftw** [comment]
If you believe the error message is invalid and enough memory is available then report to ffmpeg.
