### ISSUE TITLE
Twitter - Youtube embed failure

### ISSUE THREAD

**Issue by RingoTheDog** [ytdl-org/youtube-dl#27826]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.01.08**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.py -v "https://twitter.com/BrooklynNets/status/1349794411333394432?s=20"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://twitter.com/BrooklynNets/status/13497
94411333394432?s=20']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.6.3 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[twitter] 1349794411333394432: Downloading guest token
[twitter] 1349794411333394432: Downloading JSON metadata
[twitter] 1349794411333394432: Downloading XML
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_mai
n
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Transmogrifier\youtube-dl.py\__main__.py", line 19, in <module>
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\__init__.py", line 474, in ma
in
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\__init__.py", line 464, in _r
eal_main
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 2029, in
download
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 796, in e
xtract_info
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 803, in w
rapper
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 824, in _
_extract_info
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 53
2, in extract
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\twitter.py", line 5
01, in _real_extract
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\twitter.py", line 5
5, in _extract_formats_from_vmap_url
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 84
7, in _download_xml
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 82
5, in _download_xml_handle
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 66
5, in _download_webpage_handle
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 63
2, in _request_webpage
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 2248, in
urlopen
  File "C:\Program Files\Python36\lib\urllib\request.py", line 517, in open
    req.timeout = timeout
AttributeError: 'NoneType' object has no attribute 'timeout'

```

## Description

This tweet has a link to a youtube clip (youtube embed?)

This tweet fails: 
https://twitter.com/BrooklynNets/status/1349794411333394432?s=20

The embedded youtube URL DOES download correctly:  https://www.youtube.com/watch?v=yUMUPyii1m8

thanks
Ringo

**Comment by october262** [comment]
for this link - https://twitter.com/BrooklynNets/status/1349794411333394432?s=20
play the video and press F12 on your keyboard to bring up the debug menu, select network,
type m3u8 in the search box and copy the first liink that starts with DAbSHzR7NiFE
paste into youtube-dl to download the video.
