### ISSUE TITLE
[FUNimation] Extractor error KeyError('items',)

### ISSUE THREAD

**Issue by jnaypauer** [ytdl-org/youtube-dl#27845]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\Josh\youtubedl>youtube-dl --verbose -u xxxxxx@gmail.com -p xxxxxx --cookies cookies.txt https://www.funimation.com/shows/fruits-basket/theyre-all-animals/uncut/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', '--cookies', 'cookies.txt', 'https://www.funimation.com/shows/fruits-basket/theyre-all-animals/uncut/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1-2021-01-01-full_build-www.gyan.dev, ffprobe 4.3.1-2021-01-01-full_build-www.gyan.dev
[debug] Proxy map: {}
[Funimation] Logging in
[Funimation] theyre-all-animals: Downloading webpage
[Funimation] 961037: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('items',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\funimation.py", line 117, in _real_extract
KeyError: 'items'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\funimation.py", line 117, in _real_extract
KeyError: 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\YoutubeDL.py", line 805, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\YoutubeDL.py", line 826, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\common.py", line 545, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('items',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Hello, I am new here, just started using youtube-dl a few days ago.  I was able to download one episode of the anime Fruits Basket from Funimation on Wednesday night (and unrelated, I was able to download an episode of a show from Adult Swim as well).  I then ran into the posted error this morning when trying to download episode 2 of Fruits Basket from Funimation.  This happened before updating to the newest version and continues to happen after updating to 1.16.21 version.  Login information x'd out.

**Comment by NobleKangaroo** [comment]
I'm also experiencing this. Seems related to #21787.
- Chrome addon [Get cookies.txt](https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid) to get cookies.txt
- youtube-dl versions 2020.11.17 and 2021.01.16 both report the same error

```
C:\Users\NobleKangaroo\BlackButler>youtube-dl --verbose -u XXXXXXXX@XXX.XXX -p XXXXXXXXXXXXXXXX --cookies cookies.txt https://www.funimation.com/shows/black-butler/his-butler-able/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', '--cookies', 'cookies.txt', 'https://www.funimation.com/shows/black-butler/his-butler-able/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-04-22-2e38c63, ffprobe git-2020-04-22-2e38c63
[debug] Proxy map: {}
[Funimation] Logging in
[Funimation] his-butler-able: Downloading webpage
[Funimation] 22209: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('items',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\funimation.py", line 117, in _real_extract
KeyError: 'items'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\funimation.py", line 117, in _real_extract
KeyError: 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\YoutubeDL.py", line 805, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\YoutubeDL.py", line 826, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\common.py", line 545, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('items',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
