### ISSUE TITLE
YT [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by nastia-diaphan** [ytdl-org/youtube-dl#27848]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
~$ youtube-dl -v https://www.youtube.com/watch?v=jakfkE6OH9Q
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=jakfkE6OH9Q']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-62-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube] jakfkE6OH9Q: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r2---sn-cxab5jvh-cg0ez.googlevideo.com/videoplayback?expire=1610832594&ei=cgYDYK6dBsWbgQfQjr64DA&ip=193.121.197.244&id=o-AOH3RkKktD_gNzrAv8Gd5eT7W9Q5b_okcE5ndVCEHupo&itag=136&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=youtube&requiressl=yes&mh=qR&mm=31%2C29&mn=sn-cxab5jvh-cg0ez%2Csn-25ge7nsk&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=16&initcwndbps=1206250&vprv=1&mime=video%2Fmp4&ns=s9Bc5ZwcwlaeHv3LqTsgbGIF&gir=yes&clen=82570546&dur=684.766&lmt=1610728200936921&mt=1610810676&fvip=2&keepalive=yes&c=WEB&txp=6432432&n=0nOH5NqO_1YEJa&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgHSmPI_X6hzoz_zC_uOTFrziTVAmBSnkNLJ1AeTUlCnoCIHxhuFPCecKyzUirn0hxTLUaXW5wPUvcd3rUF7lpoVs8&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgGdk53eJNUkkZrRKoWcBYJFWKKNv7X7xB-Fjz3RnVAKgCIEoo3mz_WRuJRE8PPDVEvlhGQZFXcmutEvNabM0_qLJN&ratebypass=yes'
[download] Destination: Pleine Lune du Jeudi 28 Janvier 2021-jakfkE6OH9Q.f136.mp4
[download]  12.3% of 78.75MiB at 10.06MiB/s ETA 00:06ERROR: unable to download video data: <urlopen error [Errno 101] Network is unreachable>
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1417, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 1956, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 1901, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 2274, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/utils.py", line 2734, in https_open
    return self.do_open(functools.partial(
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>

```

Some videos but not all, the above sample is one, may be downloaded with help of wget
Here is the success log
```

~$ youtube-dl -v --external-downloader='wget' https://www.youtube.com/watch?v=jakfkE6OH9Q
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--external-downloader=wget', 'https://www.youtube.com/watch?v=jakfkE6OH9Q']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-62-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube] jakfkE6OH9Q: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r2---sn-cxab5jvh-cg0ez.googlevideo.com/videoplayback?expire=1610833271&ei=FgkDYPaSO4ScgAeF4LyQDA&ip=193.121.197.244&id=o-APHI_XHpTHBqLC1HbjvRK7wFhLwMnJA5yxF7NKYG8aF1&itag=136&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=youtube&requiressl=yes&mh=qR&mm=31%2C29&mn=sn-cxab5jvh-cg0ez%2Csn-25ge7nsk&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=16&initcwndbps=1216250&vprv=1&mime=video%2Fmp4&ns=qU-4TSgmFdarq8giT8TPi9wF&gir=yes&clen=82570546&dur=684.766&lmt=1610728200936921&mt=1610811160&fvip=2&keepalive=yes&c=WEB&txp=6432432&n=lNPtOAz8wRobtJ&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAOO_zYXCenDXRMOq92hkpJSJ55WcvEDqCPgFTJuA0LXVAiEAiymCWb4oMXV8eyKxv42fOE5HznE4dzFkX2ulVydZOaQ%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOT5up8FeRiCteb21tyFVImJ5C0nWFZOVCSsEIyPNOKuAiEA3LGpWnA6zrkvnEr9oI1piWGBRLZNluXBo9lwDT0ySiw%3D&ratebypass=yes'
[download] Destination: Pleine Lune du Jeudi 28 Janvier 2021-jakfkE6OH9Q.f136.mp4
[debug] wget command line: wget -O 'Pleine Lune du Jeudi 28 Janvier 2021-jakfkE6OH9Q.f136.mp4.part' -nv --no-cookies --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.60 Safari/537.36' --header 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Encoding: gzip, deflate' --header 'Accept-Language: en-us,en;q=0.5' --tries 10 -- 'https://r2---sn-cxab5jvh-cg0ez.googlevideo.com/videoplayback?expire=1610833271&ei=FgkDYPaSO4ScgAeF4LyQDA&ip=193.121.197.244&id=o-APHI_XHpTHBqLC1HbjvRK7wFhLwMnJA5yxF7NKYG8aF1&itag=136&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=youtube&requiressl=yes&mh=qR&mm=31%2C29&mn=sn-cxab5jvh-cg0ez%2Csn-25ge7nsk&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=16&initcwndbps=1216250&vprv=1&mime=video%2Fmp4&ns=qU-4TSgmFdarq8giT8TPi9wF&gir=yes&clen=82570546&dur=684.766&lmt=1610728200936921&mt=1610811160&fvip=2&keepalive=yes&c=WEB&txp=6432432&n=lNPtOAz8wRobtJ&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAOO_zYXCenDXRMOq92hkpJSJ55WcvEDqCPgFTJuA0LXVAiEAiymCWb4oMXV8eyKxv42fOE5HznE4dzFkX2ulVydZOaQ%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOT5up8FeRiCteb21tyFVImJ5C0nWFZOVCSsEIyPNOKuAiEA3LGpWnA6zrkvnEr9oI1piWGBRLZNluXBo9lwDT0ySiw%3D&ratebypass=yes'
[wget] Downloaded 82570546 bytes
[download] 100% of 78.75MiB in 05:27
[debug] Invoking downloader on 'https://r2---sn-cxab5jvh-cg0ez.googlevideo.com/videoplayback?expire=1610833271&ei=FgkDYPaSO4ScgAeF4LyQDA&ip=193.121.197.244&id=o-APHI_XHpTHBqLC1HbjvRK7wFhLwMnJA5yxF7NKYG8aF1&itag=140&source=youtube&requiressl=yes&mh=qR&mm=31%2C29&mn=sn-cxab5jvh-cg0ez%2Csn-25ge7nsk&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=16&initcwndbps=1216250&vprv=1&mime=audio%2Fmp4&ns=qU-4TSgmFdarq8giT8TPi9wF&gir=yes&clen=11083857&dur=684.826&lmt=1610728086116144&mt=1610811160&fvip=2&keepalive=yes&c=WEB&txp=6431432&n=lNPtOAz8wRobtJ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgYZDysE9-vET_LdiQ-MhSiIfrXF3tZJTmv3ztEy2DbYwCIE0Y6iceoBtAqnARN3DCaEBx391997Gwv2vISDB-bFB8&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOT5up8FeRiCteb21tyFVImJ5C0nWFZOVCSsEIyPNOKuAiEA3LGpWnA6zrkvnEr9oI1piWGBRLZNluXBo9lwDT0ySiw%3D&ratebypass=yes'
[download] Destination: Pleine Lune du Jeudi 28 Janvier 2021-jakfkE6OH9Q.f140.m4a
[debug] wget command line: wget -O 'Pleine Lune du Jeudi 28 Janvier 2021-jakfkE6OH9Q.f140.m4a.part' -nv --no-cookies --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.60 Safari/537.36' --header 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Encoding: gzip, deflate' --header 'Accept-Language: en-us,en;q=0.5' --tries 10 -- 'https://r2---sn-cxab5jvh-cg0ez.googlevideo.com/videoplayback?expire=1610833271&ei=FgkDYPaSO4ScgAeF4LyQDA&ip=193.121.197.244&id=o-APHI_XHpTHBqLC1HbjvRK7wFhLwMnJA5yxF7NKYG8aF1&itag=140&source=youtube&requiressl=yes&mh=qR&mm=31%2C29&mn=sn-cxab5jvh-cg0ez%2Csn-25ge7nsk&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=16&initcwndbps=1216250&vprv=1&mime=audio%2Fmp4&ns=qU-4TSgmFdarq8giT8TPi9wF&gir=yes&clen=11083857&dur=684.826&lmt=1610728086116144&mt=1610811160&fvip=2&keepalive=yes&c=WEB&txp=6431432&n=lNPtOAz8wRobtJ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgYZDysE9-vET_LdiQ-MhSiIfrXF3tZJTmv3ztEy2DbYwCIE0Y6iceoBtAqnARN3DCaEBx391997Gwv2vISDB-bFB8&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOT5up8FeRiCteb21tyFVImJ5C0nWFZOVCSsEIyPNOKuAiEA3LGpWnA6zrkvnEr9oI1piWGBRLZNluXBo9lwDT0ySiw%3D&ratebypass=yes'
[wget] Downloaded 11083857 bytes
[download] 100% of 10.57MiB in 00:49
[ffmpeg] Merging formats into "Pleine Lune du Jeudi 28 Janvier 2021-jakfkE6OH9Q.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Pleine Lune du Jeudi 28 Janvier 2021-jakfkE6OH9Q.f136.mp4' -i 'file:Pleine Lune du Jeudi 28 Janvier 2021-jakfkE6OH9Q.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Pleine Lune du Jeudi 28 Janvier 2021-jakfkE6OH9Q.temp.mp4'
Deleting original file Pleine Lune du Jeudi 28 Janvier 2021-jakfkE6OH9Q.f136.mp4 (pass -k to keep)
Deleting original file Pleine Lune du Jeudi 28 Janvier 2021-jakfkE6OH9Q.f140.m4a (pass -k to keep)
```

## Description

Most of the YT videos are no more downloading since one day
They begin downloading or not, and after some time raise an ERROR: unable to download video data: 
<urlopen error [Errno 101] Network is unreachable>
Of course I can watch them with my browser (Firefox)

There are some similar issues, old, closed, and without real solution (from recent to old):

- ERROR: unable to download video data: <urlopen error [Errno -2] Name or service not known> on Centos  https://github.com/ytdl-org/youtube-dl/issues/23188 
- <urlopen error [Errno 101] Network is unreachable> (Access Denied from link from extractor) https://github.com/ytdl-org/youtube-dl/issues/23213
- All YouTube DLs start, then get [Errno 101] Network is unreachable https://github.com/ytdl-org/youtube-dl/issues/23188 Here there is the [beginning of a solution](https://github.com/ytdl-org/youtube-dl/issues/23188#issuecomment-623256138) by crystaler4
- [Youtube] urlopen error [Errno 101] Network is unreachable https://github.com/ytdl-org/youtube-dl/issues/22812
- ERROR: unable to download video data: <urlopen error [Errno 101] Network is unreachable> https://github.com/ytdl-org/youtube-dl/issues/13264 Yup, that seems to work. I am not sure what is the problem, but looks like hiding my location / region seems to work.
- [MAJOR] Cannot download ANY YouTube DASH video format : ERROR: unable to download video data: <urlopen error [Errno 101] Network is unreachable> https://github.com/ytdl-org/youtube-dl/issues/12667
- Cannot download YouTube DASH audio format 140 : ERROR: unable to download video data: <urlopen error [Errno 101] Network is unreachable> https://github.com/ytdl-org/youtube-dl/issues/12666
- <urlopen error [Errno 101] Network is unreachable> (Access Denied from link from extractor) https://github.com/ytdl-org/youtube-dl/issues/3205

One video have **once** raised another error but maybe related:
Error: <urlopen error [Errno -2] Name or service not known>

```

~$ youtube-dl -v https://www.youtube.com/watch?v=abU3rxecuBY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=abU3rxecuBY']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-62-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube] abU3rxecuBY: Downloading webpage
[youtube] abU3rxecuBY: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1610836205/ei/jRQDYNerCbqmx_APsviD-A8/ip/193.121.197.244/id/69b537af179cb816/source/youtube/requiressl/yes/playback_host/r1---sn-cxab5jvh-cg0ez.googlevideo.com/mh/ff/mm/31%2C29/mn/sn-cxab5jvh-cg0ez%2Csn-25ge7nsl/ms/au%2Crdu/mv/m/mvi/1/pcm2cms/yes/pl/16/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1262500/vprv/1/mt/1610814041/fvip/1/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgcJADfWKZlfDL54ed9KPyttRCQ4t7cFYtgOjtYX2yLbsCIQDXJkU0C9_xenvoX89h4WPgEyQ8Q7vxmSccesyFODMGSQ%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIgVnL9_C5WF7Y-klN1XGDtEZ4OUrmVk-GS4Ml31nxzMSQCIQCTP36tEuraivNA6CkV0qD-Rjp7rcSCGwYusJCxDENI-w%3D%3D'
[dashsegments] Total fragments: 3
[download] Destination: 16 janvier 2021-abU3rxecuBY.f243.webm
ERROR: unable to download video data: <urlopen error [Errno -2] Name or service not known>
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1417, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 1956, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 1901, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/downloader/dash.py", line 48, in real_download
    success, frag_content = self._download_fragment(ctx, fragment_url, info_dict)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/downloader/fragment.py", line 104, in _download_fragment
    success = ctx['dl'].download(fragment_filename, fragment_info_dict)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 2274, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/utils.py", line 2734, in https_open
    return self.do_open(functools.partial(
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

```

Here is a table with 20 videos.

Some random videos from a list returned by:
https://www.youtube.com/results?search_query=janvier&sp=EgIIAQ%253D%253D
As I have had success with wget, I have tested all failed with this downloader.
Result seems better with wget, but when I got the file without it, I have not tested

```
video_id    size    direct_download     wget_download
jakfkE6OH9Q 11:25   12.3%   Errno 101   ok
a_qJhGDjLaU 10:03   ok                  ok
le6rDfT6M-I 7:35    14.0%   Errno 101   3.5%    Errno 101
4M4_jJYn6Eo 0:25    0       Errno 101   ok
cq1UCiAcPt4 0:12    66.7%   Errno 101   ok
6mxLyEJrWmI 0:13    ok
UHGQ3dGFhQk 0:20    ok
zf2XPhdhn7A 0:30    ok
NcUoJW7uHHw 0:42    33.3%               ok
abU3rxecuBY 0:09    0       Errno -2    0       Errno -2
5e3qX8gg-Oc 0:31    ok
C7ZhfdBX7mM 0:03    0       Errno 101   ok
BoBaQ53AZuo 3:57    ok
PqBxb594imc 0:51    9.1%    Errno 101   18.2%   Errno 101
_jSKrcG0Nmw 7:07    0       Errno 101   ok
Lr1V-JjTJSg 0:07    ok
id_js3WUrwE 2:00    12.0%   Errno 101   0       Errno 101
T_-Zb4Mr2Lk 1:46    ok
cP6G95FoH7w 1:40:24 0.2%    Errno 101   100% of 1.44GiB in 04:43 but audio never came 0.2% Errno 101
03e99dno2oc 16:46   ok

```

Only one **Errno -2** then retesting now

```
video_id    size    direct_download     wget_download
abU3rxecuBY 0:09    33.3%   Errno 101   33.3%   Errno 101

```

I have not retested all this video, but some, because the delay to raise error is long
Those I have retested have given similar responce.

With the [beginning of a solution](https://github.com/ytdl-org/youtube-dl/issues/23188#issuecomment-623256138) posted by crystaler4, I think that I can investigate to know why my browser can play a video that is unreachable to ytdl.
More in a few day...

**Comment by dstftw** [comment]
Network issues on your side.

**Comment by nastia-diaphan** [comment]
SOLVED
You are right this issues was in my side.
I found that my ISP have problem with IPv6. (same error 101 with apt upgrade)
This is why only some and always the same videos had problems and never with browser.
