### ISSUE TITLE
Viu:Ott extractor error

### ISSUE THREAD

**Issue by jefferson018200306** [ytdl-org/youtube-dl#27863]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: ['--no-mtime', '-o', '/data/data/com.termux/files/home/storage/shared/Youtube/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1280][ext=mp4]+bestaudio[ext=m4a]']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.viu.com/ott/ph/en-us/vod/320287/Mr-Queen?utm_medium=social_share_sender_android']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.9.1 (CPython) - Linux-3.10.65-gd1ee5ec-armv7l-with-libc
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[viu:ott] 320287: Downloading video info
[viu:ott] 320287: Downloading stream info
ERROR: An extractor error has occurred. (caused by KeyError('data')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/viu.py", line 226, in _real_extract
    stream_data = self._download_json(
KeyError: 'data'
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/viu.py", line 226, in _real_extract
    stream_data = self._download_json(
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 805, in wrapper
    return func(self, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 826, in __extract_info
    ie_result = ie.extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 545, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('data')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Viu:Ott is having extractor error. Please fix this ASAP, Korean dramas is our favorite

**Comment by jefferson018200306** [comment]
If this is A duplicate, just give me the issue number with this same error
