### ISSUE TITLE
Unable to Download Subtitltes from any video

### ISSUE THREAD

**Issue by ldrabeck** [ytdl-org/youtube-dl#27875]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.01.16**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```

youtube-dl -v --write-auto-sub --sub-format vtt --sub-lang en --restrict-filenames --convert-subs srt https://www.youtube.com/watch?v=00AAnwgl2DI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--write-auto-sub', '--sub-format', 'vtt', '--sub-lang', 'en', '--restrict-filenames', '--convert-subs', 'srt', 'https://www.youtube.com/watch?v=00AAnwgl2DI']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.7.4 (CPython) - Linux-4.15.0-106-generic-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://proxy.lbs.alcatel-lucent.com:8000/', 'ftp': 'ftp://proxy.lbs.alcatel-lucent.com:8000/', 'https': 'http://proxy.lbs.alcatel-lucent.com:8000/', 'no': '127.0.0.1,135.104.238.154,.bell-labs.com,.135.104.238,.135.104.54,blipp40', 'socks': 'socks://proxy.lbs.alcatel-lucent.com:8000/'}
[youtube] 00AAnwgl2DI: Downloading webpage
[youtube] 00AAnwgl2DI: Looking for automatic captions
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Example_of_Distance_Vector_Routing_1_-_Georgia_Tech_-_Network_Implementation-00AAnwgl2DI.en.vtt
WARNING: Unable to download subtitle for "en": Unable to download webpage: HTTP Error 429: unknown (caused by <HTTPError 429: 'unknown'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Invoking downloader on 'https://r5---sn-vgqsknes.googlevideo.com/videoplayback?expire=1611089251&ei=A_EGYOPoN9jXigTQ9IWACQ&ip=135.245.48.77&id=o-ALVzAHwx9waqX41-7YbqFIE3DPPpQOi-PNeAkHUB_TEL&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=t5&mm=31%2C29&mn=sn-vgqsknes%2Csn-vgqs7nlk&ms=au%2Crdu&mv=m&mvi=5&pl=24&initcwndbps=8550000&vprv=1&mime=video%2Fmp4&ns=vq6Hy01kpcOelP79rir1y1IF&gir=yes&clen=8040033&dur=115.715&lmt=1433656357349976&mt=1611067250&fvip=5&keepalive=yes&c=WEB&n=zJYphgF7ezrzUM&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgbLohMM2jIS0Ijm3KPTkaj7H00n2CuvD3v-ngq0M3cx0CIEU88-62pySlytChAS82b6zx2DRKdOLBzfHvIs-9FPIx&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAPB_YQGYpsSECdHIRPN020mZaR46SkW9_33eBnezYBHuAiEA_z3gbKLstg21UgbFiQW287mDNk0YWVG32LpCLvD3awk%3D&ratebypass=yes'
[download] Destination: Example_of_Distance_Vector_Routing_1_-_Georgia_Tech_-_Network_Implementation-00AAnwgl2DI.f137.mp4
[download] 100% of 7.67MiB in 00:01
[debug] Invoking downloader on 'https://r5---sn-vgqsknes.googlevideo.com/videoplayback?expire=1611089251&ei=A_EGYOPoN9jXigTQ9IWACQ&ip=135.245.48.77&id=o-ALVzAHwx9waqX41-7YbqFIE3DPPpQOi-PNeAkHUB_TEL&itag=140&source=youtube&requiressl=yes&mh=t5&mm=31%2C29&mn=sn-vgqsknes%2Csn-vgqs7nlk&ms=au%2Crdu&mv=m&mvi=5&pl=24&initcwndbps=8550000&vprv=1&mime=audio%2Fmp4&ns=vq6Hy01kpcOelP79rir1y1IF&gir=yes&clen=1839405&dur=115.774&lmt=1433656361980544&mt=1611067250&fvip=5&keepalive=yes&c=WEB&n=zJYphgF7ezrzUM&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgIRn6QVvAHW0rv5S2JI09o8puO0yiV073RfPBud6e8_UCIQDkJEitGJAR52TzqMeETZybYGiWsFIySzLdPzGHsfaEcg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAPB_YQGYpsSECdHIRPN020mZaR46SkW9_33eBnezYBHuAiEA_z3gbKLstg21UgbFiQW287mDNk0YWVG32LpCLvD3awk%3D&ratebypass=yes'
[download] Destination: Example_of_Distance_Vector_Routing_1_-_Georgia_Tech_-_Network_Implementation-00AAnwgl2DI.f140.m4a
[download] 100% of 1.75MiB in 00:00
[ffmpeg] Merging formats into "Example_of_Distance_Vector_Routing_1_-_Georgia_Tech_-_Network_Implementation-00AAnwgl2DI.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:Example_of_Distance_Vector_Routing_1_-_Georgia_Tech_-_Network_Implementation-00AAnwgl2DI.f137.mp4 -i file:Example_of_Distance_Vector_Routing_1_-_Georgia_Tech_-_Network_Implementation-00AAnwgl2DI.f140.m4a -c copy -map 0:v:0 -map 1:a:0 file:Example_of_Distance_Vector_Routing_1_-_Georgia_Tech_-_Network_Implementation-00AAnwgl2DI.temp.mp4
Deleting original file Example_of_Distance_Vector_Routing_1_-_Georgia_Tech_-_Network_Implementation-00AAnwgl2DI.f137.mp4 (pass -k to keep)
Deleting original file Example_of_Distance_Vector_Routing_1_-_Georgia_Tech_-_Network_Implementation-00AAnwgl2DI.f140.m4a (pass -k to keep)
[ffmpeg] Converting subtitles
Traceback (most recent call last):
  File "/nas1/drabeck/anaconda3/bin/youtube-dl", line 8, in <module>
    sys.exit(main())
  File "/nas1/drabeck/anaconda3/lib/python3.7/site-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/nas1/drabeck/anaconda3/lib/python3.7/site-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/nas1/drabeck/anaconda3/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2055, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/nas1/drabeck/anaconda3/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 798, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/nas1/drabeck/anaconda3/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 805, in wrapper
    return func(self, *args, **kwargs)
  File "/nas1/drabeck/anaconda3/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 837, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/nas1/drabeck/anaconda3/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 871, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/nas1/drabeck/anaconda3/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1678, in process_video_result
    self.process_info(new_info)
  File "/nas1/drabeck/anaconda3/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2036, in process_info
    self.post_process(filename, info_dict)
  File "/nas1/drabeck/anaconda3/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2101, in post_process
    files_to_delete, info = pp.run(info)
  File "/nas1/drabeck/anaconda3/lib/python3.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 649, in run
    self.run_ffmpeg(old_file, new_file, ['-f', new_format])
  File "/nas1/drabeck/anaconda3/lib/python3.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 239, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/nas1/drabeck/anaconda3/lib/python3.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 210, in run_ffmpeg_multiple_files
    os.stat(encodeFilename(path)).st_mtime for path in input_paths)
  File "/nas1/drabeck/anaconda3/lib/python3.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 210, in <genexpr>
    os.stat(encodeFilename(path)).st_mtime for path in input_paths)
FileNotFoundError: [Errno 2] No such file or directory: 'Example_of_Distance_Vector_Routing_1_-_Georgia_Tech_-_Network_Implementation-00AAnwgl2DI.en.vtt'

youtube-dl -v --list-subs https://www.youtube.com/watch?v=00AAnwgl2DI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--list-subs', 'https://www.youtube.com/watch?v=00AAnwgl2DI']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.7.4 (CPython) - Linux-4.15.0-106-generic-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://proxy.lbs.alcatel-lucent.com:8000/', 'ftp': 'ftp://proxy.lbs.alcatel-lucent.com:8000/', 'https': 'http://proxy.lbs.alcatel-lucent.com:8000/', 'no': '127.0.0.1,135.104.238.154,.bell-labs.com,.135.104.238,.135.104.54,blipp40', 'socks': 'socks://proxy.lbs.alcatel-lucent.com:8000/'}
[youtube] 00AAnwgl2DI: Downloading webpage
WARNING: unable to download video subtitles: Unable to download XML: HTTP Error 429: unknown (caused by <HTTPError 429: 'unknown'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] 00AAnwgl2DI: Looking for automatic captions
Available automatic captions for 00AAnwgl2DI:
Language formats
af       vtt, ttml, srv3, srv2, srv1
sq       vtt, ttml, srv3, srv2, srv1
am       vtt, ttml, srv3, srv2, srv1
ar       vtt, ttml, srv3, srv2, srv1
hy       vtt, ttml, srv3, srv2, srv1
az       vtt, ttml, srv3, srv2, srv1
bn       vtt, ttml, srv3, srv2, srv1
eu       vtt, ttml, srv3, srv2, srv1
be       vtt, ttml, srv3, srv2, srv1
bs       vtt, ttml, srv3, srv2, srv1
bg       vtt, ttml, srv3, srv2, srv1
my       vtt, ttml, srv3, srv2, srv1
ca       vtt, ttml, srv3, srv2, srv1
ceb      vtt, ttml, srv3, srv2, srv1
zh-Hans  vtt, ttml, srv3, srv2, srv1
zh-Hant  vtt, ttml, srv3, srv2, srv1
co       vtt, ttml, srv3, srv2, srv1
hr       vtt, ttml, srv3, srv2, srv1
cs       vtt, ttml, srv3, srv2, srv1
da       vtt, ttml, srv3, srv2, srv1
nl       vtt, ttml, srv3, srv2, srv1
en       vtt, ttml, srv3, srv2, srv1
eo       vtt, ttml, srv3, srv2, srv1
et       vtt, ttml, srv3, srv2, srv1
fil      vtt, ttml, srv3, srv2, srv1
fi       vtt, ttml, srv3, srv2, srv1
fr       vtt, ttml, srv3, srv2, srv1
gl       vtt, ttml, srv3, srv2, srv1
ka       vtt, ttml, srv3, srv2, srv1
de       vtt, ttml, srv3, srv2, srv1
el       vtt, ttml, srv3, srv2, srv1
gu       vtt, ttml, srv3, srv2, srv1
ht       vtt, ttml, srv3, srv2, srv1
ha       vtt, ttml, srv3, srv2, srv1
haw      vtt, ttml, srv3, srv2, srv1
iw       vtt, ttml, srv3, srv2, srv1
hi       vtt, ttml, srv3, srv2, srv1
hmn      vtt, ttml, srv3, srv2, srv1
hu       vtt, ttml, srv3, srv2, srv1
is       vtt, ttml, srv3, srv2, srv1
ig       vtt, ttml, srv3, srv2, srv1
id       vtt, ttml, srv3, srv2, srv1
ga       vtt, ttml, srv3, srv2, srv1
it       vtt, ttml, srv3, srv2, srv1
ja       vtt, ttml, srv3, srv2, srv1
jv       vtt, ttml, srv3, srv2, srv1
kn       vtt, ttml, srv3, srv2, srv1
kk       vtt, ttml, srv3, srv2, srv1
km       vtt, ttml, srv3, srv2, srv1
rw       vtt, ttml, srv3, srv2, srv1
ko       vtt, ttml, srv3, srv2, srv1
ku       vtt, ttml, srv3, srv2, srv1
ky       vtt, ttml, srv3, srv2, srv1
lo       vtt, ttml, srv3, srv2, srv1
la       vtt, ttml, srv3, srv2, srv1
lv       vtt, ttml, srv3, srv2, srv1
lt       vtt, ttml, srv3, srv2, srv1
lb       vtt, ttml, srv3, srv2, srv1
mk       vtt, ttml, srv3, srv2, srv1
mg       vtt, ttml, srv3, srv2, srv1
ms       vtt, ttml, srv3, srv2, srv1
ml       vtt, ttml, srv3, srv2, srv1
mt       vtt, ttml, srv3, srv2, srv1
mi       vtt, ttml, srv3, srv2, srv1
mr       vtt, ttml, srv3, srv2, srv1
mn       vtt, ttml, srv3, srv2, srv1
ne       vtt, ttml, srv3, srv2, srv1
no       vtt, ttml, srv3, srv2, srv1
ny       vtt, ttml, srv3, srv2, srv1
or       vtt, ttml, srv3, srv2, srv1
ps       vtt, ttml, srv3, srv2, srv1
fa       vtt, ttml, srv3, srv2, srv1
pl       vtt, ttml, srv3, srv2, srv1
pt       vtt, ttml, srv3, srv2, srv1
pa       vtt, ttml, srv3, srv2, srv1
ro       vtt, ttml, srv3, srv2, srv1
ru       vtt, ttml, srv3, srv2, srv1
sm       vtt, ttml, srv3, srv2, srv1
gd       vtt, ttml, srv3, srv2, srv1
sr       vtt, ttml, srv3, srv2, srv1
sn       vtt, ttml, srv3, srv2, srv1
sd       vtt, ttml, srv3, srv2, srv1
si       vtt, ttml, srv3, srv2, srv1
sk       vtt, ttml, srv3, srv2, srv1
sl       vtt, ttml, srv3, srv2, srv1
so       vtt, ttml, srv3, srv2, srv1
st       vtt, ttml, srv3, srv2, srv1
es       vtt, ttml, srv3, srv2, srv1
su       vtt, ttml, srv3, srv2, srv1
sw       vtt, ttml, srv3, srv2, srv1
sv       vtt, ttml, srv3, srv2, srv1
tg       vtt, ttml, srv3, srv2, srv1
ta       vtt, ttml, srv3, srv2, srv1
tt       vtt, ttml, srv3, srv2, srv1
te       vtt, ttml, srv3, srv2, srv1
th       vtt, ttml, srv3, srv2, srv1
tr       vtt, ttml, srv3, srv2, srv1
tk       vtt, ttml, srv3, srv2, srv1
uk       vtt, ttml, srv3, srv2, srv1
ur       vtt, ttml, srv3, srv2, srv1
ug       vtt, ttml, srv3, srv2, srv1
uz       vtt, ttml, srv3, srv2, srv1
vi       vtt, ttml, srv3, srv2, srv1
cy       vtt, ttml, srv3, srv2, srv1
fy       vtt, ttml, srv3, srv2, srv1
xh       vtt, ttml, srv3, srv2, srv1
yi       vtt, ttml, srv3, srv2, srv1
yo       vtt, ttml, srv3, srv2, srv1
zu       vtt, ttml, srv3, srv2, srv1
00AAnwgl2DI has no subtitles




```

## Description

This morning was downloading subtitles and wav files for multiple videos with no problem.  Between one run and the next, all of a sudden I cannot download any subtitles for any videos.

**Comment by nixxo** [comment]
HTTP 429 is TOO MANY REQUESTS.

probably youtube was loaded, now it's working.
