### ISSUE TITLE
Not downloading public playlist - 0 videos found; Then "YouTube is not currently available on this device."

### ISSUE THREAD

**Issue by kwinz** [ytdl-org/youtube-dl#27885]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.01.16**
- [~] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ sudo youtube-dl -U
youtube-dl is up-to-date (2021.01.16)

$ youtube-dl -v "https://www.youtube.com/watch?list=UUMtJYS0PrtiUwlk6zjGDEMA"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?list=UUMtJYS0PrtiUwlk6zjGDEMA']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-112-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[youtube:playlist] UUMtJYS0PrtiUwlk6zjGDEMA: Downloading webpage
[download] Downloading playlist: UUMtJYS0PrtiUwlk6zjGDEMA
[youtube:playlist] playlist UUMtJYS0PrtiUwlk6zjGDEMA: **Downloading 0 videos**
[download] Finished downloading playlist: UUMtJYS0PrtiUwlk6zjGDEMA
```

I also tried:

```
$ youtube-dl -v "https://www.youtube.com/watch?v=j3qJB7yswwo&list=UUMtJYS0PrtiUwlk6zjGDEMA&index=1"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=j3qJB7yswwo&list=UUMtJYS0PrtiUwlk6zjGDEMA&index=1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-112-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist UUMtJYS0PrtiUwlk6zjGDEMA - add --no-playlist to just download video j3qJB7yswwo
[youtube:playlist] UUMtJYS0PrtiUwlk6zjGDEMA: Downloading webpage
[youtube] j3qJB7yswwo: Downloading webpage
ERROR: j3qJB7yswwo: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/home/markus/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/markus/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/markus/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1789, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: j3qJB7yswwo: YouTube said: Unable to extract video data
```

## Description

Downloading the public youtube playlist `UUMtJYS0PrtiUwlk6zjGDEMA` fails.
`youtube-dl` parses 0 videos and finishes without downloading anything.

What's more: After using `youtube-dl`, I apparently got soft-banned by Youtube.
Using a different computer, but on the same public IP I now get served 1minute long unlisted video titled "YouTube is not currently available on this device." instead of the playlist videos, inside a Chrome browser.

**Comment by remitamine** [comment]
```
youtube-dl https://www.youtube.com/watch?list=UUMtJYS0PrtiUwlk6zjGDEMA
[youtube:tab] UUMtJYS0PrtiUwlk6zjGDEMA: Downloading webpage
[youtube:tab] UUMtJYS0PrtiUwlk6zjGDEMA: Downloading webpage
[download] Downloading playlist: Uploads from EllioTrades Crypto
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] Downloading page 3
[youtube:tab] Downloading page 4
[youtube:tab] Downloading page 5
[youtube:tab] playlist Uploads from EllioTrades Crypto: Downloading 542 videos
[download] Downloading video 1 of 542
[youtube] j3qJB7yswwo: Downloading webpage
[download] Destination: THE ABSOLUTE BEST ALTCOIN OF 2021 REVEALED! Altcoin & NFT Holders Must Watch!-j3qJB7yswwo.mp4
...
```
```
youtube-dl "https://www.youtube.com/watch?v=j3qJB7yswwo&list=UUMtJYS0PrtiUwlk6zjGDEMA&index=1"
[youtube:tab] Downloading playlist UUMtJYS0PrtiUwlk6zjGDEMA - add --no-playlist to just download video j3qJB7yswwo
[youtube:tab] UUMtJYS0PrtiUwlk6zjGDEMA: Downloading webpage
[youtube:tab] UUMtJYS0PrtiUwlk6zjGDEMA: Downloading webpage
[download] Downloading playlist: Uploads from EllioTrades Crypto
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] Downloading page 3
[youtube:tab] Downloading page 4
[youtube:tab] Downloading page 5
[youtube:tab] playlist Uploads from EllioTrades Crypto: Downloading 542 videos
[download] Downloading video 1 of 542
[youtube] j3qJB7yswwo: Downloading webpage
[download] Destination: THE ABSOLUTE BEST ALTCOIN OF 2021 REVEALED! Altcoin & NFT Holders Must Watch!-j3qJB7yswwo.mp4
...
```

**Comment by kwinz** [comment]
Thanks @remitamine. I can confirm that after removing `youtube-dl` via `pip3 uninstall youtube-dl` and then reinstalling it via https://github.com/ytdl-org/youtube-dl#installation it now works as expected.

**Comment by piyush-panpaliya** [comment]
installing it from **apt** in ubuntu creates same issue but can be resolved by installing it from https://github.com/ytdl-org/youtube-dl#installation
