### ISSUE TITLE
[ComedyCentral] extractor appears to be broken

### ISSUE THREAD

**Issue by laurentlasalle** [ytdl-org/youtube-dl#27905]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.cc.com/video/k3sdvm/the-daily-show-with-jon-stewart-exclusive-the-fourth-estate']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-91330-ga990184007, ffprobe N-91330-ga990184007
[debug] Proxy map: {}
[generic] the-daily-show-with-jon-stewart-exclusive-the-fourth-estate: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-daily-show-with-jon-stewart-exclusive-the-fourth-estate: Downloading webpage
[generic] the-daily-show-with-jon-stewart-exclusive-the-fourth-estate: Extracting information
ERROR: Unsupported URL: https://www.cc.com/video/k3sdvm/the-daily-show-with-jon-stewart-exclusive-the-fourth-estate
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\YoutubeDL.py", line 805, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\YoutubeDL.py", line 826, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\generic.py", line 3467, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.cc.com/video/k3sdvm/the-daily-show-with-jon-stewart-exclusive-the-fourth-estate
```

## Description

Extracting videos from The Daily Show with Jon Stewart worked fine yesterday, but cc.com changed their URL structure overnight, which might cause issues with the current [ComedyCentral] extrator. 

http://www.cc.com/video-clips/k3sdvm/the-daily-show-with-jon-stewart-exclusive---the-fourth-estate became https://www.cc.com/video/k3sdvm/the-daily-show-with-jon-stewart-exclusive-the-fourth-estate through a 301 redirect. Same goes for any /video-clips/ URLs from The Daily Show subsite.

**Comment by Glagnar** [comment]
Can confirm also a problem on macOS.
