### ISSUE TITLE
--proxy and --geo-verification-proxy not working?

### ISSUE THREAD

**Issue by davFaithid** [ytdl-org/youtube-dl#27910]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --geo-verification-proxy "socks4://185.198.188.54:8080" --proxy "socks4://185.198.188.54:8080" --verbose https://www.youtube.com/watch?v=TQ74-ydHK0I
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--geo-verification-proxy', 'socks4://185.198.188.54:8080', '--proxy', 'socks4://185.198.188.54:8080', '--verbose', 'https://www.youtube.com/watch?v=TQ74-ydHK0I']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.8.3 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg git-2019-12-24-287620f, ffprobe git-2019-12-24-287620f
[debug] Proxy map: {'http': 'socks4://185.198.188.54:8080', 'https': 'socks4://185.198.188.54:8080'}
[youtube] TQ74-ydHK0I: Downloading webpage
Traceback (most recent call last):
  File "c:\users\davfa\miniconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\davfa\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\davfa\miniconda3\Scripts\youtube-dl.exe\__main__.py", line 7, in <module>
  File "c:\users\davfa\miniconda3\lib\site-packages\youtube_dl\__init__.py", line 474, in main
    _real_main(argv)
  File "c:\users\davfa\miniconda3\lib\site-packages\youtube_dl\__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "c:\users\davfa\miniconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 2054, in download
    res = self.extract_info(
  File "c:\users\davfa\miniconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 798, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "c:\users\davfa\miniconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 805, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\davfa\miniconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 826, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\davfa\miniconda3\lib\site-packages\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\davfa\miniconda3\lib\site-packages\youtube_dl\extractor\youtube.py", line 1645, in _real_extract
    video_webpage, urlh = self._download_webpage_handle(url, video_id)
  File "c:\users\davfa\miniconda3\lib\site-packages\youtube_dl\extractor\common.py", line 665, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "c:\users\davfa\miniconda3\lib\site-packages\youtube_dl\extractor\common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\davfa\miniconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 2274, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\davfa\miniconda3\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "c:\users\davfa\miniconda3\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "c:\users\davfa\miniconda3\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "c:\users\davfa\miniconda3\lib\site-packages\youtube_dl\utils.py", line 2734, in https_open
    return self.do_open(functools.partial(
  File "c:\users\davfa\miniconda3\lib\urllib\request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "c:\users\davfa\miniconda3\lib\http\client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\davfa\miniconda3\lib\http\client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\davfa\miniconda3\lib\http\client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\davfa\miniconda3\lib\http\client.py", line 1006, in _send_output
    self.send(msg)
  File "c:\users\davfa\miniconda3\lib\http\client.py", line 946, in send
    self.connect()
  File "c:\users\davfa\miniconda3\lib\site-packages\youtube_dl\utils.py", line 2702, in connect
    self.sock.connect((self.host, self.port))
  File "c:\users\davfa\miniconda3\lib\site-packages\youtube_dl\socks.py", line 270, in connect
    self._make_proxy(socket.socket.connect, address)
  File "c:\users\davfa\miniconda3\lib\site-packages\youtube_dl\socks.py", line 266, in _make_proxy
    setup_funcs[self._proxy.type](address)
  File "c:\users\davfa\miniconda3\lib\site-packages\youtube_dl\socks.py", line 167, in _setup_socks4
    version, resp_code, dstport, dsthost = compat_struct_unpack('!BBHI', self.recvall(8))
  File "c:\users\davfa\miniconda3\lib\site-packages\youtube_dl\socks.py", line 126, in recvall
    raise EOFError('{0} bytes missing'.format(cnt - len(data)))
EOFError: 8 bytes missing
```

## Description

I am trying to download a video not available in my region, and thus I tried using the --proxy and --geo-verification-proxy commands but they keep failing with different errors. The log I included was the most common error I got and I do not understand it or how to fix it.
Any help would be greatly appreciated.

**Comment by dstftw** [comment]
Your proxy is dead.
