### ISSUE TITLE
[Wakanim] HTTP Error 414: Request-URI Too Long

### ISSUE THREAD

**Issue by Toufailleur** [ytdl-org/youtube-dl#27913]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.01.16**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
youtube-dl https://www.wakanim.tv/fr/v2/catalogue/episode/10587/azur-lane-saison-1-episode-1-vostfr --cookies cookies.txt --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.wakanim.tv/fr/v2/catalogue/episode/10587/azur-lane-saison-1-episode-1-vostfr', '--cookies', 'cookies.txt', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-13-amd64-x86_64-with-debian-10.7
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[Wakanim] 10587: Downloading webpage
[Wakanim] 10587: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://www.wakanim.tv/fr/v2/video/<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http:/www.w3.org/2001/XMLSchema-instance" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="static" xmlns:cenc="urn:mpeg:cenc:2013" id="n6WVi3ziDku3icY12rgdWQ" xmlns:mspr="urn:microsoft:playready" xmlns:ms="urn:microsoft" mediaPresentationDuration="PT23M58.104S" minBufferTime="PT3S"><Period><AdaptationSet id="1" group="1" profiles="ccff" bitstreamSwitching="false" segmentAlignment="true" contentType="video" mimeType="video/mp4" maxWidth="1920" maxHeight="1080" startWithSAP="1"><ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="D69DD247-2F1F-45A7-B163-3D674A2507A7"/><ContentProtection schemeIdUri="urn:uuid:9A04F079-9840-4286-AB92-E65BE0885F95" value="2.0" cenc:default_KID="D69DD247-2F1F-45A7-B163-3D674A2507A7"><mspr:pro>UgMAAAEAAQBIAzwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADAALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsARQBZAEwARQBOAD4AMQA2ADwALwBLAEUAWQBMAEUATgA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEAD4AUgA5AEsAZAAxAGgAOAB2AHAAMABXAHgAWQB6ADEAbgBTAGkAVQBIAHAAdwA9AD0APAAvAEsASQBEAD4APABDAEgARQBDAEsAUwBVAE0APgBEAHUASwBVACsAWQB5AHQAUgBkAHcAPQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APABMAEEAXwBVAFIATAA+AGgAdAB0AHAAcwA6AC8ALwB3AGEAawBhAHQAZQBzAHQALgBrAGUAeQBkAGUAbABpAHYAZQByAHkALgBuAG8AcgB0AGgAZQB1AHIAbwBwAGUALgBtAGUAZABpAGEALgBhAHoAdQByAGUALgBuAGUAdAAvAFAAbABhAHkAUgBlAGEAZAB5AC8APAAvAEwAQQBfAFUAUgBMAD4APABDAFUAUwBUAE8ATQBBAFQAVABSAEkAQgBVAFQARQBTAD4APABJAEkAUwBfAEQAUgBNAF8AVgBFAFIAUwBJAE8ATgA+ADgALgAwAC4AMgAwADEAMgAuADQAPAAvAEkASQBTAF8ARABSAE0AXwBWAEUAUgBTAEkATwBOAD4APAAvAEMAVQBTAFQATwBNAEEAVABUAFIASQBCAFUAVABFAFMAPgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</mspr:pro></ContentProtection><ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed" cenc:default_KID="D69DD247-2F1F-45A7-B163-3D674A2507A7"><cenc:pssh>AAAAMnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABISENad0kcvH0WnsWM9Z0olB6c=</cenc:pssh><ms:laurl licenseUrl="https:/wakatest.keydelivery.northeurope.media.azure.net/Widevine/?kid=d69dd247-2f1f-45a7-b163-3d674a2507a7"/></ContentProtection><SegmentTemplate timescale="10000000" media="https://wakanim-vid.akamaized.net/5037ebac-0101-4cef-bdcb-4d85407a85b3/Azur_Lane_01_FR_HD.ism/QualityLevels($Bandwidth$)/Fragments(video=$Time$,format=mpd-time-cmaf,encryption=cenc)" initialization="https://wakanim-vid.akamaized.net/5037ebac-0101-4cef-bdcb-4d85407a85b3/Azur_Lane_01_FR_HD.ism/QualityLevels($Bandwidth$)/Fragments(video=i,format=mpd-time-cmaf,encryption=cenc)"><SegmentTimeline><S d="20020000" r="3"/><S d="20860000"/><S d="20020000" r="712"/><S d="5839166"/></SegmentTimeline></SegmentTemplate><Representation id="1_V_video_1" bandwidth="4046596" codecs="avc1.640028" width="1920" height="1080"/><Representation id="1_V_video_2" bandwidth="2370346" codecs="avc1.64001F" width="1280" height="720"/><Representation id="1_V_video_3" bandwidth="912355" codecs="avc1.64001F" width="960" height="540"/><Representation id="1_V_video_4" bandwidth="641667" codecs="avc1.64001E" width="640" height="360"/></AdaptationSet><AdaptationSet id="2" group="5" profiles="ccff" bitstreamSwitching="false" segmentAlignment="true" contentType="audio" mimeType="audio/mp4"><ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="D69DD247-2F1F-45A7-B163-3D674A2507A7"/><ContentProtection schemeIdUri="urn:uuid:9A04F079-9840-4286-AB92-E65BE0885F95" value="2.0" cenc:default_KID="D69DD247-2F1F-45A7-B163-3D674A2507A7"><mspr:pro>UgMAAAEAAQBIAzwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADAALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsARQBZAEwARQBOAD4AMQA2ADwALwBLAEUAWQBMAEUATgA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEAD4AUgA5AEsAZAAxAGgAOAB2AHAAMABXAHgAWQB6ADEAbgBTAGkAVQBIAHAAdwA9AD0APAAvAEsASQBEAD4APABDAEgARQBDAEsAUwBVAE0APgBEAHUASwBVACsAWQB5AHQAUgBkAHcAPQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APABMAEEAXwBVAFIATAA+AGgAdAB0AHAAcwA6AC8ALwB3AGEAawBhAHQAZQBzAHQALgBrAGUAeQBkAGUAbABpAHYAZQByAHkALgBuAG8AcgB0AGgAZQB1AHIAbwBwAGUALgBtAGUAZABpAGEALgBhAHoAdQByAGUALgBuAGUAdAAvAFAAbABhAHkAUgBlAGEAZAB5AC8APAAvAEwAQQBfAFUAUgBMAD4APABDAFUAUwBUAE8ATQBBAFQAVABSAEkAQgBVAFQARQBTAD4APABJAEkAUwBfAEQAUgBNAF8AVgBFAFIAUwBJAE8ATgA+ADgALgAwAC4AMgAwADEAMgAuADQAPAAvAEkASQBTAF8ARABSAE0AXwBWAEUAUgBTAEkATwBOAD4APAAvAEMAVQBTAFQATwBNAEEAVABUAFIASQBCAFUAVABFAFMAPgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</mspr:pro></ContentProtection><ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed" cenc:default_KID="D69DD247-2F1F-45A7-B163-3D674A2507A7"><cenc:pssh>AAAAMnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABISENad0kcvH0WnsWM9Z0olB6c=</cenc:pssh><ms:laurl licenseUrl="https://wakatest.keydelivery.northeurope.media.azure.net/Widevine/?kid=d69dd247-2f1f-45a7-b163-3d674a2507a7"/></ContentProtection><Label>aac_UND_2_127</Label><SegmentTemplate timescale="10000000" media="https://wakanim-vid.akamaized.net/5037ebac-0101-4cef-bdcb-4d85407a85b3/Azur_Lane_01_FR_HD.ism/QualityLevels($Bandwidth$)/Fragments(aac_UND_2_127=$Time$,format=mpd-time-cmaf,encryption=cenc)" initialization="https://wakanim-vid.akamaized.net/5037ebac-0101-4cef-bdcb-4d85407a85b3/Azur_Lane_01_FR_HD.ism/QualityLevels($Bandwidth$)/Fragments(aac_UND_2_127=i,format=mpd-time-cmaf,encryption=cenc)"><SegmentTimeline><S d="20053333" r="1"/><S d="20053334"/><S d="20060000"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="2346667"/></SegmentTimeline></SegmentTemplate><Representation id="5_A_aac_UND_2_127_1" bandwidth="127999" codecs="mp4a.40.2" audioSamplingRate="48000"/></AdaptationSet></Period></MPD>'
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 414: Request-URI Too Long
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1962, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1901, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 64, in real_download
    urlh = self.ydl.urlopen(self._prepare_url(info_dict, man_url))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2274, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 414: Request-URI Too Long

```

## Description

I tried to download from Wakanim and got this error. I guess their site is awful. Seems like nobody reported this yet.

**Comment by nitish770** [comment]
It's because they have use captcha to verify is the request is sent from human not bot like youtube-dl.

**Comment by Azzuray** [comment]
And its also DRM Protected so.

**Comment by Toufailleur** [comment]
That's new then... Crunchyroll is also DRM Protected but it's still working fine. I might be completely out of subject saying this tho. Thanks for your patience.

**Comment by bgette** [comment]
Juste pour info :
C'est très compliqué de télécharger du Wakanim. N'espère pas pouvoir télécharger (à nouveau) avec youtube-dl.

**Comment by NotErikUden** [comment]
I have the same issue, any solutions? 
https://ytdl-org.github.io/youtube-dl/supportedsites.html
This list of supported sites still lists Wakanim as supported, so should that be removed?

**Comment by Toufailleur** [comment]
Wakanim has been merged with Crunchyroll, this issue won't last anymore.
