### ISSUE TITLE
cms.nova.cz unsupported

### ISSUE THREAD

**Issue by hanzi2** [ytdl-org/youtube-dl#27927]
**% youtube-dl -F -v "https://media.cms.nova.cz/embed/G6ZCSVyNecD"**
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-v', 'https://media.cms.nova.cz/embed/G6ZCSVyNecD']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.9.1 (CPython) - macOS-11.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[NovaEmbed] G6ZCSVyNecD: Downloading webpage
ERROR: Unable to extract formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.16/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 805, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.1.16/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 826, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.16/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.16/libexec/lib/python3.9/site-packages/youtube_dl/extractor/nova.py", line 72, in _real_extract
    self._search_regex(
  File "/usr/local/Cellar/youtube-dl/2021.1.16/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by xmstspider** [comment]
/usr/local/bin/youtube-dl -F -C -v --write-pages https://novaplus.nova.cz/porad/tvoje-tvar-ma-znamy-hlas/epizoda/69851-1-dil
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-C', '-v', '--write-pages', 'https://novaplus.nova.cz/porad/tvoje-tvar-ma-znamy-hlas/epizoda/69851-1-dil', '--proxy', 'socks5://localhost:10080/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.25
[debug] Python version 3.8.6 (CPython) - Linux-5.8.0-45-generic-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[Nova] 69851-1-dil: Downloading webpage
[Nova] Saving request to 69851-1-dil_https_-_novaplus.nova.cz_porad_tvoje-tvar-ma-znamy-hlas_epizoda_69851-1-dil.dump
[NovaEmbed] DOr5C5RMljh: Downloading webpage
[NovaEmbed] Saving request to DOr5C5RMljh_https_-_media.cms.nova.cz_embed_DOr5C5RMljh.dump
ERROR: Unable to extract formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/nova.py", line 72, in _real_extract
    self._search_regex(
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[69851-1-dil_https_-_novaplus.nova.cz_porad_tvoje-tvar-ma-znamy-hlas_epizoda_69851-1-dil.dump.txt](https://github.com/ytdl-org/youtube-dl/files/6202638/69851-1-dil_https_-_novaplus.nova.cz_porad_tvoje-tvar-ma-znamy-hlas_epizoda_69851-1-dil.dump.txt)
[DOr5C5RMljh_https_-_media.cms.nova.cz_embed_DOr5C5RMljh.dump.txt](https://github.com/ytdl-org/youtube-dl/files/6202639/DOr5C5RMljh_https_-_media.cms.nova.cz_embed_DOr5C5RMljh.dump.txt)
