### ISSUE TITLE
[abcnews] Unable to extract video URL

### ISSUE THREAD

**Issue by xavdr** [ytdl-org/youtube-dl#27920]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
H:\films\python -m youtube_dl --verbose https://abcnews.go.com/Politics/biden-promises-unity-redemption-amid-divisions-challenges-analysis/story?id=75380552
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://abcnews.go.com/Politics/biden-promises-unity-redemption-amid-divisions-challenges-analysis/story?id=75380552']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.7.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2019-12-15-ed9279a, ffprobe git-2019-12-15-ed9279a
[debug] Proxy map: {}
[abcnews] 75380552: Downloading webpage
ERROR: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update.
 Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "H:\MACH-L\python-LIB\youtube_dl\YoutubeDL.py", line 805, in wrapper
    return func(self, *args, **kwargs)
  File "H:\MACH-L\python-LIB\youtube_dl\YoutubeDL.py", line 826, in __extract_info
    ie_result = ie.extract(url)
  File "H:\MACH-L\python-LIB\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "H:\MACH-L\python-LIB\youtube_dl\extractor\abcnews.py", line 112, in _real_extract
    r'window\.abcnvideo\.url\s*=\s*"([^"]+)"', webpage, 'video URL')
  File "H:\MACH-L\python-LIB\youtube_dl\extractor\common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by october262** [comment]
play the video and press F12 on your keyboard to bring up the debug menu,
go to network - all - type m3u8 in the search box, copy the master.m3u8 link
and feed it into youtube-dl to download the video.

**Comment by xavdr** [comment]
> 
> 
> play the video and press F12 on your keyboard to bring up the debug menu,
> go to network - all - type m3u8 in the search box, copy the master.m3u8 link
> and feed it into youtube-dl to download the video.

thx didn't know that playlists exist usually looked for media files.
