### ISSUE TITLE
Certain CBS shows no longer downloading - NCIS, NCIS LA, NCIS New Orleans etc

### ISSUE THREAD

**Issue by mshiels** [ytdl-org/youtube-dl#27939]
## Checklist

- [X ] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.01.16**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\YouTubeDL5>\python37-32\python -m youtube_dl -v -i -w --cookies cbscookies.tx
t --download-archive DownloadedCBS.txt --no-check-certificate --hls-prefer-nativ
e --output "X:\NCIS\Season %(season_number)d\NCIS - s%(season_number)03de%(episo
de_number)03d - %(title)s.mp4" --write-sub --all-subs --convert-subs srt "https:
//www.cbs.com/shows/ncis/video/wP_KR1psumjev4oICpyLkWzhgm_OPz1S/ncis-head-of-the
-snake/"
[debug] System config: []
[debug] User config: ['--socket-timeout', '60']
[debug] Custom config: []
[debug] Command-line args: ['-v', '-i', '-w', '--cookies', 'cbscookies.txt', '--
download-archive', 'DownloadedCBS.txt', '--no-check-certificate', '--hls-prefer-
native', '--output', 'X:\\NCIS\\Season %(season_number)d\\NCIS - s%(season_numbe
r)03de%(episode_number)03d - %(title)s.mp4', '--write-sub', '--all-subs', '--con
vert-subs', 'srt', 'https://www.cbs.com/shows/ncis/video/wP_KR1psumjev4oICpyLkWz
hgm_OPz1S/ncis-head-of-the-snake/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.01.16
[debug] Git HEAD: f08c31cf3
[debug] Python version 3.7.4 (CPython) - Windows-2012ServerR2-6.3.9600-SP0
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.3
[debug] Proxy map: {}
[CBS] wP_KR1psumjev4oICpyLkWzhgm_OPz1S: Downloading XML
ERROR: Could not find XML element title; please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/
update  on how to update. Be sure to call youtube-dl with the --verbose flag and
 include its complete output.
Traceback (most recent call last):
  File "C:\YouTubeDL5\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "C:\YouTubeDL5\youtube_dl\YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "C:\YouTubeDL5\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "C:\YouTubeDL5\youtube_dl\extractor\cbs.py", line 112, in _real_extract
    return self._extract_video_info(content_id)
  File "C:\YouTubeDL5\youtube_dl\extractor\cbs.py", line 62, in _extract_video_i
nfo
    title = xpath_text(video_data, 'videoTitle', 'title', True)
  File "C:\YouTubeDL5\youtube_dl\utils.py", line 1910, in xpath_text
    n = xpath_element(node, xpath, name, fatal=fatal, default=default)
  File "C:\YouTubeDL5\youtube_dl\utils.py", line 1903, in xpath_element
    raise ExtractorError('Could not find XML element %s' % name)
youtube_dl.utils.ExtractorError: Could not find XML element title; please report
 this issue on https://yt-dl.org/bug . Make sure you are using the latest versio
n; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl w
ith the --verbose flag and include its complete output.

```

## Description

It was working for last season, and a fair number of shows do work.  Tried to debug/find out what piece has changed, with no luck so far.

**Comment by mshiels** [comment]
Update NCIS New Orleans is actually working, that was my mistake to list it.  But NCIS and NCIS LA are both failing for some reason i can not figure otu.

**Comment by Jon171** [comment]
I'm having an issue with downloading season 5 of Teenage Mutant Ninja Turtles 2003. It keeps saying "No video formats found". All of the other season download just fine for some reason.

**Comment by Sipherdrakon** [comment]
Because at the time you wrote this only season 5 had ```DRM``` by now I am sure they all do, but when it can't find a video, it's most likely because they added ```DRM``` for those videos.
