### ISSUE TITLE
Facebook video page no longer parses

### ISSUE THREAD

**Issue by JackPo** [ytdl-org/youtube-dl#27944]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.facebook.com/MVPLibrary/videos/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.9.1 (CPython) - macOS-11.1-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] videos: Requesting header
WARNING: Falling back on generic information extractor.
[generic] videos: Downloading webpage
[generic] videos: Extracting information
[redirect] Following redirect to https://www.facebook.com/MVPLibrary/videos/?_fb_noscript=1
[generic] ?_fb_noscript=1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?_fb_noscript=1: Downloading webpage
[generic] ?_fb_noscript=1: Extracting information
ERROR: Unsupported URL: https://www.facebook.com/MVPLibrary/videos/?_fb_noscript=1
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.16/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 805, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.1.16/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 826, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.16/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.16/libexec/lib/python3.9/site-packages/youtube_dl/extractor/generic.py", line 3467, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.facebook.com/MVPLibrary/videos/?_fb_noscript=1

## Description

it used to be able to parse a generic facebook page, but now no videos download, anyone know how to fix?

i.e.

https://www.facebook.com/MVPLibrary/videos/

**Comment by JackPo** [comment]
Why is this a duplicate? I don’t actually see a duplicate issue.
