### ISSUE TITLE
TF1 stopped working

### ISSUE THREAD

**Issue by octavioj** [ytdl-org/youtube-dl#27952]
Since last week something changed in the TF1 websites that broke TF1. Please find attached the output of youtube-dl --verbose : 

youtube-dl --verbose https://www.tf1.fr/tf1/jt-we/videos/xxxxxxx
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.tf1.fr/tf1/jt-we/videos/xxxxxxx']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.9.1 (CPython) - macOS-10.14.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[TF1] le-20-heures-du-vendredi-22-janvier-2021-59777704: Downloading webpage
[wat.tv] 13761867: Downloading JSON metadata
[wat.tv] 13761867: Downloading JSON metadata
[wat.tv] 13761867: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[wat.tv] 13761867: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
[wat.tv] 13761867: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[wat.tv] 13761867: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
[wat.tv] 13761867: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [Errno 8] nodename nor servname provided, or not known>
[wat.tv] 13761867: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [Errno 8] nodename nor servname provided, or not known>
[wat.tv] 13761867: Checking http-264 URL
[wat.tv] 13761867: http-264 URL is invalid, skipping: <urlopen error [Errno 8] nodename nor servname provided, or not known>
[wat.tv] 13761867: Checking http-464 URL
[wat.tv] 13761867: http-464 URL is invalid, skipping: <urlopen error [Errno 8] nodename nor servname provided, or not known>
[wat.tv] 13761867: Checking http-664 URL
[wat.tv] 13761867: http-664 URL is invalid, skipping: <urlopen error [Errno 8] nodename nor servname provided, or not known>
[wat.tv] 13761867: Checking http-1264 URL
[wat.tv] 13761867: http-1264 URL is invalid, skipping: <urlopen error [Errno 8] nodename nor servname provided, or not known>
[wat.tv] 13761867: Checking http-1864 URL
[wat.tv] 13761867: http-1864 URL is invalid, skipping: <urlopen error [Errno 8] nodename nor servname provided, or not known>
[wat.tv] 13761867: Checking http-2564 URL
[wat.tv] 13761867: http-2564 URL is invalid, skipping: <urlopen error [Errno 8] nodename nor servname provided, or not known>
ERROR: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.16/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 805, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.1.16/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 837, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/Cellar/youtube-dl/2021.1.16/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 871, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/Cellar/youtube-dl/2021.1.16/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 1559, in process_video_result
    raise ExtractorError('No video formats found!')
youtube_dl.utils.ExtractorError: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Running on MacOS 10.14.6 . I also tried on Ubuntu 20.10 and the same result happens

**Comment by octavioj** [comment]
Thank you for the quick reply. As of this morning, it had not yet been updated.
