### ISSUE TITLE
"ERROR: unable to open for writing: [Errno 22] Invalid argument: " for specific Twitter video

### ISSUE THREAD

**Issue by bogdanmilosavljevic** [ytdl-org/youtube-dl#27967]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.01.24.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
G:\aaaa>youtube-dl -v https://twitter.com/malagurski/status/1353659288779173889
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://twitter.com/malagurski/status/1353659288779173889']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.8.5 (CPython) - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Proxy map: {}
[twitter] 1353659288779173889: Downloading guest token
[twitter] 1353659288779173889: Downloading JSON metadata
[twitter] 1353659288779173889: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://video.twimg.com/ext_tw_video/1353656173204037632/pu/vid/540x274/5Y5i1xod6T6JaclM.mp4?tag=10'
ERROR: unable to open for writing: [Errno 22] Invalid argument: 'Boris Malagurski - Elderly Serbian woman claims #Serbia’s President @avucic invented COVID-19 vaccine. This is the result of state-sponsored propaganda in Serbia. When asked what she’d do to those who offend the President, she responds - “I’d slaughter them.”-1353659288779173889.mp4.part'
Traceback (most recent call last):
  File "c:\python\lib\site-packages\youtube_dl\downloader\http.py", line 259, in download
    ctx.stream, ctx.tmpfilename = sanitize_open(
  File "c:\python\lib\site-packages\youtube_dl\utils.py", line 2054, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
OSError: [Errno 22] Invalid argument: 'Boris Malagurski - Elderly Serbian woman claims #Serbia’s President @avucic invented COVID-19 vaccine. This is the result of state-sponsored propaganda in Serbia. When asked what she’d do to those who offend the President, she responds - “I’d slaughter them.”-1353659288779173889.mp4.part'
```

## Description

Getting this error when trying to download that particular Twitter video. Tried with other Twitter videos and they download with no issue. What I think might be an issue based on provided debug logs is that the video title contains quotes (note that quotes are in title, not URL, so I can't escape them)

**Comment by october262** [comment]
for this link - https://twitter.com/malagurski/status/1353659288779173889
just press F12 to open the debug menu, go to network - type m3u8 in the search box
copy the first link that starts with 3Kv1 and feed it into youtube-dl to download the video.
