### ISSUE TITLE
Vivo.sx not working?

### ISSUE THREAD

**Issue by lapuertas** [ytdl-org/youtube-dl#27979]
## Checklist

- [x ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.01.24.1**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
hades@PAR-267305:/lapustore/serienNEW$ youtube-dl https://vivo.sx/a5d99f8933 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://vivo.sx/a5d99f8933', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-134-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[Vivo] a5d99f8933: Downloading webpage
ERROR: Unable to extract stream; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/shared.py", line 31, in _real_extract
    video_url = self._extract_video_url(webpage, video_id, url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/shared.py", line 137, in _extract_video_url
    'stream'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract stream; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

 all works  only the vivo  download   dont work  thanks for help

**Comment by Mennaruuk** [comment]
Hmm. It worked for me. Can you reinstall youtube-dl?
```
C:\Users\alifl\Downloads>youtube-dl --verbose "https://vivo.sx/a5d99f8933"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://vivo.sx/a5d99f8933']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[Vivo] a5d99f8933: Downloading webpage
WARNING: unable to extract filesize; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://node--olivia.vivo.sx/vod/zIC20wMA-Y2S-8sh_39XfQ/1612251896/0037049773'
[download] Destination: Watzmann.ermittelt.S01E01.GERMAN.AC3.720p.HDTV.x264-hrs-a5d99f8933.mp4
[download] 100% of 218.97MiB in 04:14
```
