### ISSUE TITLE
[Bloomberg] Unable to extract id

### ISSUE THREAD

**Issue by 2011** [ytdl-org/youtube-dl#27971]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.24.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -f best -v 'https://www.bloomberg.com/multimedia/api/embed/iframe?id=57275bd9-857a-47a4-b7ad-e08068bca31a'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--restrict-filenames', '-o', '%(title)s-%(id)s-%(uploader)s.%(ext)s', '-w', '-f', 'best', '-v', 'https://www.bloomberg.com/multimedia/api/embed/iframe?id=57275bd9-857a-47a4-b7ad-e08068bca31a']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.8.7 (CPython) - Linux-5.4.80-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[Bloomberg] iframe: Downloading webpage
ERROR: Unable to extract id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/bloomberg.py", line 57, in _real_extract
    bplayer_data = self._parse_json(self._search_regex(
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

This represents (I believe) an unexpected form of a Bloomberg video link (embedded in a web page belonging to a different domain). I have no problem opening the embedded link in a browser (and playing it), and (of course) no problem obtaining the correct .m3u8 files from the embedded link when opened in a browser.

**Comment by marcpage** [comment]
I am seeing the same exact issue without any reference to Bloomberg. Please update the title to remove Bloomberg.

```
% youtube-dl -f mp4 'https://www.youtube.com/watch?v=EIR4jmjtUgU&t=3s'
[youtube] EIR4jmjtUgU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

% youtube-dl --version
2021.12.17

% youtube-dl -i -f mp4 'https://www.youtube.com/watch?v=EIR4jmjtUgU&t=3s'
[youtube] EIR4jmjtUgU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

% youtube-dl -v -f mp4 'https://www.youtube.com/watch?v=EIR4jmjtUgU&t=3s'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'mp4', 'https://www.youtube.com/watch?v=EIR4jmjtUgU&t=3s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: ba6d87eed
[debug] Python version 3.10.9 (CPython) - macOS-13.2.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] EIR4jmjtUgU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

It might be helpful if debug mode is turned on to dump the text we're searching in on line 1012

**Comment by 2011** [comment]
> I am seeing the same exact issue without any reference to Bloomberg. Please update the title to remove Bloomberg.

Sorry, no. YouTube rolled out a format change on or near 0216. See here:

https://github.com/yt-dlp/yt-dlp/issues/6247

The youtube-dl developers have committed a patch to fix this. See here:

https://github.com/ytdl-org/youtube-dl/commit/f7ce98a21e15cb094c772e9082796d009c61578b

However, until they make another release, you have two choices: switch to yt-dlp or use the master branch.

**Comment by dirkf** [comment]
>Sorry, no. YouTube rolled out a format change on or near 0216. See here:
>
>yt-dlp/yt-dlp#6247

More relevant: #31530.

**Comment by dirkf** [comment]
Still reproduces with current versions.

**Comment by CatsEyeXI** [comment]
> Still reproduces with current versions, but new test-cases are needed. URLs like the problem URL are used in tests that succeed in current yt-dl.

this URL fails with yl-dlp `https://www.youtube.com/watch?v=UDZQU6kTULc&ab_channel=Spaceroast`
