### ISSUE TITLE
support for likee.video

### ISSUE THREAD

**Issue by Joseph65** [ytdl-org/youtube-dl#27999]
## Checklist

- [ x] I'm reporting a new site support request
- [ x] I've verified that I'm running youtube-dl version **2021.01.24.1**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that none of provided URLs violate any copyrights
- [ x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- video url : https://l.likee.video/v/k6QcOp
- channel url : https://l.likee.video/p/Gp6YGd

## Description
site support for likee.video

WRITE DESCRIPTION HERE

**Comment by Mennaruuk** [comment]
[There is support for likee videos](https://github.com/ytdl-org/youtube-dl/issues/24533#issuecomment-605809247).

This is the verbose log I got for your video:
```
C:\Users\Menna\Downloads>youtube-dl --verbose "https://likee.video/v/k6QcOp"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://likee.video/v/k6QcOp']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[generic] k6QcOp: Requesting header
WARNING: Falling back on generic information extractor.
[generic] k6QcOp: Downloading webpage
[generic] k6QcOp: Extracting information
[download] Downloading playlist: None
[generic] playlist None: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://video.like.video/na_live/4ax/2ST6lv_4.mp4?crc=612432523&type=5'
[download] Destination: Agua challenge     😳😱 (1)-2ST6lv_4.mp4
[download] 100% of 8.09MiB in 00:09
[download] Downloading video 2 of 2
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'http://video.like.video/na_live/4ax/2ST6lv_4.mp4?crc=612432523&type=5'
[download] Destination: Agua challenge     😳😱 (2)-2ST6lv_4.mp4
[download] 100% of 8.09MiB in 00:04
[download] Finished downloading playlist: None
```
However, channel support isn't yet implemented. Relevant verbose log:
```
C:\Users\Menna\Downloads>youtube-dl --verbose "https://likee.video/p/Gp6YGd"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://likee.video/p/Gp6YGd']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[generic] Gp6YGd: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Gp6YGd: Downloading webpage
[generic] Gp6YGd: Extracting information
ERROR: Unsupported URL: https://likee.video/p/Gp6YGd
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\extractor\generic.py", line 3467, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://likee.video/p/Gp6YGd
```

**Comment by babbittw** [comment]
I'll work on channel support!

**Comment by Mennaruuk** [comment]
> 
> 
> I'll work on channel support!

Thanks a bunch!
