### ISSUE TITLE
Vimeo download fails on Unable to extract info section (caused by JSONDecodeError)

### ISSUE THREAD

**Issue by clippermadness** [ytdl-org/youtube-dl#28009]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.24.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[vimeo] 506241526: Downloading webpage
[vimeo] 506241526: Extracting information
ERROR: Unable to extract info section (caused by JSONDecodeError('Extra data: line 1 column 3 (char 2)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Richards-MBP-2:Downloads rich$ youtube-dl --verbose --no-part --id --newline --no-call-home --no-color --write-info-json --no-playlist -f mp4/best --recode-video mp4 https://vimeo.com/506241526/1a5611a077
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--no-part', '--id', '--newline', '--no-call-home', '--no-color', '--write-info-json', '--no-playlist', '-f', 'mp4/best', '--recode-video', 'mp4', 'https://vimeo.com/506241526/1a5611a077']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.9.1 (CPython) - macOS-11.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 506241526: Downloading webpage
[vimeo] 506241526: Extracting information
ERROR: Unable to extract info section (caused by JSONDecodeError('Extra data: line 1 column 3 (char 2)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/vimeo.py", line 635, in _real_extract
    page_config = self._parse_json(self._search_regex(
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract page config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/vimeo.py", line 658, in _real_extract
    config = json.loads(config)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/vimeo.py", line 635, in _real_extract
    page_config = self._parse_json(self._search_regex(
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract page config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/vimeo.py", line 658, in _real_extract
    config = json.loads(config)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/vimeo.py", line 670, in _real_extract
    raise ExtractorError('Unable to extract info section',
youtube_dl.utils.ExtractorError: Unable to extract info section (caused by JSONDecodeError('Extra data: line 1 column 3 (char 2)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Invoking youtube-dl version 2021.01.24.1 to download the Vimeo video https://vimeo.com/506241526/1a5611a077.

`youtube-dl --verbose --no-part --id --newline --no-call-home --no-color --write-info-json --no-playlist -f mp4/best --recode-video mp4 https://vimeo.com/506241526/1a5611a077`

Fails with this output (verbose output above):
```
[vimeo] 506241526: Downloading webpage
[vimeo] 506241526: Extracting information
ERROR: Unable to extract info section (caused by JSONDecodeError('Extra data: line 1 column 3 (char 2)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by filmo** [comment]
I'm having similar issue with Vimeo videos that are parts of showcases. I upgraded to 2021.01.24

**Comment by walksonair** [comment]
I have youtube-dl version 2021.02.04.1 and am having the same issue w VIMEO showcase...here is part of my output:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://vimeo.com/showcase/[redacted]/embed']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.02.04.1
[debug] Python version 3.9.1 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo:album] 7473583: Downloading JSON metadata
[vimeo:album] 7473583: Downloading JSON metadata
[download] Downloading playlist: Day Trading Live Streams
[vimeo:album] 7473583: Downloading page 1
[vimeo:album] 7473583: Downloading page 2
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/Cellar/youtube-dl/2021.2.4.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/Cellar/youtube-dl/2021.2.4.1/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2275, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

```

**Comment by rhymeswithmogul** [comment]
I'm having this same issue with youtube-dl version 2021.02.10.  My video is also part of a showcase, too.

**Comment by remitamine** [comment]
The first URL is no longer accessible.
The second works fine(Not reproducible).
The issue with the third URL is tracked in another issue.
