### ISSUE TITLE
Unable to extract video title; no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info

### ISSUE THREAD

**Issue by ndsvw** [ytdl-org/youtube-dl#28016]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.01.24.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
root@ubuntu-x:~/y# youtube-dl -a tmp --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-a', 'tmp', '--verbose']
[debug] Batch file urls: ['https://www.youtube.com/playlist?list=PLQrsocOZ_VClJijiPEjyUSUwJkCm-Bler']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-52-generic-x86_64-with-glibc2.29
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:tab] PLQrsocOZ_VClJijiPEjyUSUwJkCm-Bler: Downloading webpage
[download] Downloading playlist: Panorama - NDR
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] Downloading page 3
[youtube:tab] Downloading page 4
[youtube:tab] Downloading page 5
[youtube:tab] Downloading page 6
[youtube:tab] Downloading page 7
[youtube:tab] Downloading page 8
[youtube:tab] playlist Panorama - NDR: Downloading 813 videos
[download] Downloading video 1 of 813
[youtube] B4qcbzvQR0U: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r5---sn-4g5edns7.googlevideo.com/videoplayback?expire=1612041152&ei=YHcVYJ6OFcez8gPdt5DICQ&ip=2a01%3A4f8%3A1c0c%3A681f%3A0%3A0%3A0%3A1&id=o-AOAyNn3pXbR5ygVHQ2isMQhBdytv7OA3LS2WVM2LB8Ia&itag=22&source=youtube&requiressl=yes&mh=1r&mm=31%2C29&mn=sn-4g5edns7%2Csn-4g5e6nze&ms=au%2Crdu&mv=m&mvi=5&pl=36&initcwndbps=531250&vprv=1&mime=video%2Fmp4&ns=FCRlasncxGdE3m2-kpvN-JsF&ratebypass=yes&dur=691.768&lmt=1611884926705852&mt=1612019085&fvip=5&c=WEB&txp=5432434&n=KBYvrmGGIliAuiYJK&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgSR1-BQUKf75GMkxc9l_AaOpUQv_zJ5yv9zej8WhBb44CIQCojJpw0K8WR_pYoJCXbL_JUZUJi-yMYEQktAVLvvOGlQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAN9bCMum8WZ3FRcHFyI6Yb5atN9utGKkI-Hooeiz1k_ZAiB8XmGm9rtYBawMJwaUqFamNhDMgSfgMnfQpTQitPwKcw%3D%3D'
[download] Destination: Hamburger Hafen - Elbvertiefung um jeden Preis _ Panorama 3 _ NDR-B4qcbzvQR0U.mp4
[download] 100% of 122.75MiB in 00:03
[download] Downloading video 2 of 813
[youtube] 3_Z_NHI9I_c: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r4---sn-4g5e6nes.googlevideo.com/videoplayback?expire=1612041156&ei=ZHcVYNyCCNmJ1wKzuaXoCg&ip=2a01%3A4f8%3A1c0c%3A681f%3A0%3A0%3A0%3A1&id=o-AFLmlwP7u9HiYhca_mUxRr_pnXaF1oVGQ6-bxQerQyvD&itag=22&source=youtube&requiressl=yes&mh=CV&mm=31%2C26&mn=sn-4g5e6nes%2Csn-5go7ynez&ms=au%2Conr&mv=m&mvi=4&pl=36&initcwndbps=531250&vprv=1&mime=video%2Fmp4&ns=-Y65T0ddS2GF5anRtY5943AF&ratebypass=yes&dur=324.893&lmt=1611733242326763&mt=1612019085&fvip=4&c=WEB&txp=2316222&n=LNRa4I1PB42gDxXig&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAKBSW-dEuGe6YuI9IAkvXhVfvgF0JF43h2qa0HKuqAX1AiA6m99mPaMl21H4YDXGIHrWlIV2FqU0oEwdALJqCHHUiQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANBPnL4v6A89Lu1d5LfNuY1NkTiX1oZbmi5sME4uM9leAiAkAY4H-BNV0v1FJvEIFGjViw_KmlMsDt3hsYt6_XB8_g%3D%3D'
[download] Destination: Das Kita-Dilemma - Erzieher_innen an der Belastungsgrenze _ Panorama 3 _ NDR-3_Z_NHI9I_c.mp4
[download] 100% of 67.96MiB in 00:02
[download] Downloading video 3 of 813
[youtube] spIc8SB3a74: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r4---sn-4g5edne6.googlevideo.com/videoplayback?expire=1612041158&ei=ZncVYLuJMtKB6dsP3NiqqAs&ip=2a01%3A4f8%3A1c0c%3A681f%3A0%3A0%3A0%3A1&id=o-APpnZvOlvQzwUTWyLw3cK_4xOLbFSlYA1_HCXvXmKrgz&itag=22&source=youtube&requiressl=yes&mh=Dq&mm=31%2C26&mn=sn-4g5edne6%2Csn-5go7yner&ms=au%2Conr&mv=m&mvi=4&pl=36&initcwndbps=510000&vprv=1&mime=video%2Fmp4&ns=GDokOsvDZo9HC6n1qpCHS70F&ratebypass=yes&dur=423.485&lmt=1611733344331583&mt=1612019324&fvip=4&c=WEB&txp=2316222&n=QJVxHzzYdtw3D74jT&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIzEhwIK7ZZIBNoF70IeZz2n2Dh0qeRmvCdZt1_wgk0iAiBG62EpE2vauJ_hMMCf-bFoUj2mfb1WO8mx68lXC_bbXQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgLA_gyKKv-tiCqHCj9Njg7Q10XbxbXDrf-ygKdTFLlb4CIQDh_wgVNS0kEeAruQdykaMATNXmg3XFRhelWtv6n9ldag%3D%3D'
[download] Destination: Ambulante Pflegekräfte - Beim Impfen vergessen _ Panorama 3 _ NDR-spIc8SB3a74.mp4
[download] 100% of 70.75MiB in 00:01
[download] Downloading video 4 of 813
[youtube] 1FTMQcGVuQU: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r5---sn-4g5e6nzz.googlevideo.com/videoplayback?expire=1612041161&ei=aXcVYJHREriF6dsPzNep2A4&ip=2a01%3A4f8%3A1c0c%3A681f%3A0%3A0%3A0%3A1&id=o-AN2lLglOwqZLqh5NdwF4DtMFSBqBX2W0djwLC2dQczKO&itag=22&source=youtube&requiressl=yes&mh=88&mm=31%2C29&mn=sn-4g5e6nzz%2Csn-4g5ednsk&ms=au%2Crdu&mv=m&mvi=5&pl=36&initcwndbps=566250&vprv=1&mime=video%2Fmp4&ns=QD0ODAzD2rSl6C0rp6heInAF&ratebypass=yes&dur=331.302&lmt=1611733207143195&mt=1612019085&fvip=5&c=WEB&txp=2316222&n=DPcNK5tbHKO656B--&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhANu0GM0PF1ho375V2JfbP3TslfUYoigFWsqkfzt-LmtNAiBETak8ZnRaqXzm2cQXMt492GeJ1nZjMWIwvenE6D4tAA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIvrlsPmKRY6dPX0hpIprDazKnizOeR2ThOy4sijXrOXAiBMfCcewUha8zFjLadUfo5qAMbavjsmALFXAjR6bPEHGA%3D%3D'
[download] Destination: Impfzentrum Hamburg - Fragwürdige Auftragsvergabe  _ Panorama 3 _ NDR-1FTMQcGVuQU.mp4
[download] 100% of 49.19MiB in 00:01
[download] Downloading video 5 of 813
[youtube] SJ7sr7ssVU8: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r6---sn-4g5ednll.googlevideo.com/videoplayback?expire=1612041162&ei=ancVYK7ENZyD6dsPmN6FMA&ip=2a01%3A4f8%3A1c0c%3A681f%3A0%3A0%3A0%3A1&id=o-AKTTr1ejTq10jNSfVjUMMjLtSPx-F42qitLSTFVXLLBR&itag=22&source=youtube&requiressl=yes&mh=NV&mm=31%2C29&mn=sn-4g5ednll%2Csn-4g5e6nsy&ms=au%2Crdu&mv=m&mvi=6&pl=36&initcwndbps=531250&vprv=1&mime=video%2Fmp4&ns=CAJ442EyZzTZwpv0YGdaluEF&ratebypass=yes&dur=920.555&lmt=1611635677150899&mt=1612019085&fvip=4&c=WEB&txp=5432434&n=V9X-TQZmjJxojtky8&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgeGMQdiWH7JiPwIJxFPJDNsU0dwwa_HEc97kE5WrtfuUCIQCBAxwT_vJMr8vOUGuEiUejlF5Scm-u0c5tVcWWZySp0Q%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAM4IaohIRPDzhugFWemKKEiInM9VXKQyRSwkO22bgctRAiBO3_uS5eASjB_JG4UU_eX6LfgtKIOO9Hh5dV9Q7RCCcw%3D%3D'
[download] Destination: Corona - Wem gehört der Impfstoff _ Panorama _ NDR-SJ7sr7ssVU8.mp4
[download] 100% of 153.04MiB in 00:04
[download] Downloading video 6 of 813
[youtube] MwBjuwz3pVo: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r3---sn-4g5ednsr.googlevideo.com/videoplayback?expire=1612041167&ei=b3cVYMzqNJnP1wLTpr6YCw&ip=2a01%3A4f8%3A1c0c%3A681f%3A0%3A0%3A0%3A1&id=o-APo_YExIkQTkcvGaO5Cr4ETApKUD6DIxmcPvkvA7KPQs&itag=22&source=youtube&requiressl=yes&mh=va&mm=31%2C29&mn=sn-4g5ednsr%2Csn-4g5e6nle&ms=au%2Crdu&mv=m&mvi=3&pl=36&initcwndbps=531250&vprv=1&mime=video%2Fmp4&ns=yrksU7EqRun1d9oHDj4VzHkF&ratebypass=yes&dur=503.060&lmt=1611653299604714&mt=1612019085&fvip=3&c=WEB&txp=5532434&n=3PJAVjJ2epIgmwgy7&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgQZVRzT_Gk66Pfdgzw-CN9pb2stG4cW1AEdIsNvJ33q4CIQCLjdjZymPnseW5hDOmP9-1aBjRTOKJ0-Z5ZkXazI6PoA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIqf4iSa0sNt4TXzC9yI8TNJRCx_n1z05nB_MXzNA1IPAiAIUaRzJCTaMx5pKeJPFRYtgmR_nRMwD7Yv0UertRm3Fg%3D%3D'
[download] Destination: Getränkepfand - Neues Gesetz, neue Ausnahmen _ Panorama _ NDR-MwBjuwz3pVo.mp4
[download] 100% of 58.29MiB in 00:00
[download] Downloading video 7 of 813
[youtube] mgfoWoPyfgk: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r5---sn-4g5e6nl7.googlevideo.com/videoplayback?expire=1612041169&ei=cHcVYLKjO5Wh1gLJkph4&ip=2a01%3A4f8%3A1c0c%3A681f%3A0%3A0%3A0%3A1&id=o-AEt9R0zSl5LDqmfA_Ot7FMnJtT1wTNSt1vLgfKdIwXVF&itag=22&source=youtube&requiressl=yes&mh=NE&mm=31%2C29&mn=sn-4g5e6nl7%2Csn-4g5ednll&ms=au%2Crdu&mv=m&mvi=5&pl=36&initcwndbps=566250&vprv=1&mime=video%2Fmp4&ns=sMyXCNg1DqtFvv0F52OxLI8F&ratebypass=yes&dur=290.342&lmt=1611300148814975&mt=1612019085&fvip=5&c=WEB&txp=2316222&n=8stS4jP0rs_0W23Y5&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgTGKJofvoR89RftD9NnUqKRl8PWn_1R70_1I_jdlfw3UCIQDmeoexmNgr1b8gV15pFnLItZryClwIyG4CXSHKraBwdw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAM-Kwm0_sNs4q-9PhDen0wJdRFCkdyYjq4atLvuevQCXAiEAzAVZxzOFzvMwNMDdYn287p-eLh8KMG9aifTQFsTeFf4%3D'
[download] Destination: Flüchtlinge auf Lesbos - Die gewollte Not _ Panorama _ NDR-mgfoWoPyfgk.mp4
[download] 100% of 51.74MiB in 00:01
[download] Downloading video 8 of 813
[youtube] ScwO-VbEnWA: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r4---sn-4g5ednz7.googlevideo.com/videoplayback?expire=1612041171&ei=c3cVYOMulJTXAtvNpKAP&ip=2a01%3A4f8%3A1c0c%3A681f%3A0%3A0%3A0%3A1&id=o-ABVsG25pm874hnX4q9pDPW09X5kwiYXVvA_EvqSmQOo7&itag=22&source=youtube&requiressl=yes&mh=np&mm=31%2C26&mn=sn-4g5ednz7%2Csn-5goeen7k&ms=au%2Conr&mv=m&mvi=4&pl=36&initcwndbps=566250&vprv=1&mime=video%2Fmp4&ns=JfVL-KwVC3KOWXyfFQjFMjEF&ratebypass=yes&dur=478.516&lmt=1611130612330395&mt=1612019085&fvip=4&c=WEB&txp=2316222&n=VMnzFCzj0sn8szD04&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAO189tNR9zaVvQ91EoocS3Qppx5T8oqjm-cjlg8VYTeDAiEAgBZCGEmEpMCxQ13HqBbopsm7nn3WxZStzl_LX3MKb94%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgJHF_UIASSM3G9GNR6T0d2Q6_lKZCucXgB0poglVZVKQCIQD-xLMETc20A3ke3U9HGo1KH_wnTjquKer7M2kPjr8EYg%3D%3D'
[download] Destination: Falsche Flächenpolitik - Der zugebaute Norden _ Panorama 3 _ NDR-ScwO-VbEnWA.mp4
[download] 100% of 90.57MiB in 00:03
[download] Downloading video 9 of 813
[youtube] o8ZBmmt9JNg: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r2---sn-4g5e6ns6.googlevideo.com/videoplayback?expire=1612041174&ei=dncVYPusONeW8gOTzanIAw&ip=2a01%3A4f8%3A1c0c%3A681f%3A0%3A0%3A0%3A1&id=o-AL9qvcJxQrKHXlHKNraAQD2kQn7zArzbOpLBW5P3oEH6&itag=22&source=youtube&requiressl=yes&mh=oe&mm=31%2C29&mn=sn-4g5e6ns6%2Csn-4g5ednz7&ms=au%2Crdu&mv=m&mvi=2&pl=36&initcwndbps=531250&vprv=1&mime=video%2Fmp4&ns=yKOiL_ljpGH5fvHsYaohjh8F&ratebypass=yes&dur=464.979&lmt=1611127306762519&mt=1612019085&fvip=2&c=WEB&txp=2316222&n=AmeIugHQUbf6Na6O6&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAOPhK49Wt0e6gZNABcK7fUuRifZz_52YW0EopzetYskxAiEA1czdwDxfXrT2HPJTDqM37DWQPOjGKkRLSnS2gPSvy84%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgWwtDv4-azxaQ38hQ7Vh9XauSumyned6qk7wTId7_6a0CIQC4pI0xSQwHjVDhxnDxUHa4CmmrOflCNZvwmPfZha6iBg%3D%3D'
[download] Destination: Iranischer Diplomat unter Terrorverdacht - Die Spur nach Deutschland _ report-o8ZBmmt9JNg.mp4
[download] 100% of 69.53MiB in 00:01
[download] Downloading video 10 of 813
[youtube] T2JRuwtBTk0: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r3---sn-4g5e6nsy.googlevideo.com/videoplayback?expire=1612041177&ei=eXcVYOTTEcTK8gPbiL3wAg&ip=2a01%3A4f8%3A1c0c%3A681f%3A0%3A0%3A0%3A1&id=o-AMAkYkAxmjIxIdxnvYOt3ELuI3SNQ8dyUAHtDOHT_aH1&itag=22&source=youtube&requiressl=yes&mh=Cl&mm=31%2C29&mn=sn-4g5e6nsy%2Csn-4g5edney&ms=au%2Crdu&mv=m&mvi=3&pl=36&initcwndbps=531250&vprv=1&mime=video%2Fmp4&ns=FK3aR2fFZBzHygtzmvBQKBMF&ratebypass=yes&dur=492.611&lmt=1611091543440666&mt=1612019085&fvip=3&c=WEB&txp=2316222&n=ehUtTbV-UC13rsNnl&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAPzUd-2hywx2pzPfB1VeAT1FKyZh2bUiZx-V31ZFqLF1AiAtQQn1LQzbU6zMONz0t-q3D6SAhhYHKeV3eMHIQCZe3A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgN9T3q6GSnTQ-eVObsjx5II3tmlrPEeSbTGrz-9enHJcCIHt-LVFxzP58J5pij2rYuRv1yLCH6DP1cpyvQJyfHaFg'
[download] Destination: Vergessene Risikogruppe - Menschen mit Behinderung _ Panorama 3 _ NDR-T2JRuwtBTk0.mp4
[download] 100% of 74.05MiB in 00:04
[download] Downloading video 11 of 813
[youtube] uzrOLdOhpnI: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r5---sn-4g5ednek.googlevideo.com/videoplayback?expire=1612041182&ei=fncVYNnkD8iD1wLQ56OwBg&ip=2a01%3A4f8%3A1c0c%3A681f%3A0%3A0%3A0%3A1&id=o-ANPKGoYtz5-GdTBQ3Yey0fmERHW71J8fEvTn75Odcuc-&itag=22&source=youtube&requiressl=yes&mh=ed&mm=31%2C29&mn=sn-4g5ednek%2Csn-4g5e6nss&ms=au%2Crdu&mv=m&mvi=5&pl=36&initcwndbps=531250&vprv=1&mime=video%2Fmp4&ns=kETaJwBw3qO7IGOcNIFWSNEF&ratebypass=yes&dur=425.436&lmt=1611091597155425&mt=1612019085&fvip=5&c=WEB&txp=2316222&n=J5tlCaa99mmcxuhMU&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIwLQ4AlSNrk4SNk4XJf5Hbs6GcvryOF9EyJuaU76yT3AiBHX0DVPrpbM1WLrk6tjRbTyr7ojlbUH815pENulP5sHQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgdbrAp1rMkGkTFq5nZBjUN-EO03DwfhzcnAN-Pn7ZA04CIQCzv3ua04bvwMOrbC0lvvPWdJ4r3JPcP6uWjPaArrUQuQ%3D%3D'
[download] Destination: Impfen in der Pflege - Wie groß ist die Skepsis wirklich _ Panorama 3 _ NDR-uzrOLdOhpnI.mp4
[download] 100% of 58.22MiB in 00:02
[download] Downloading video 12 of 813
[youtube] ksp_sT6iiDo: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r3---sn-4g5e6nsd.googlevideo.com/videoplayback?expire=1612041185&ei=gXcVYI6nBdip8gOhzr7YDg&ip=2a01%3A4f8%3A1c0c%3A681f%3A0%3A0%3A0%3A1&id=o-ANsI8GQs1q28Xs3ykO04b7dN8ddGsD-dFB_z3RBwI_OH&itag=22&source=youtube&requiressl=yes&mh=Tw&mm=31%2C26&mn=sn-4g5e6nsd%2Csn-5goeen7y&ms=au%2Conr&mv=m&mvi=3&pl=36&initcwndbps=568750&vprv=1&mime=video%2Fmp4&ns=vWN6cGFO1_es0CQLZSj1W10F&ratebypass=yes&dur=546.667&lmt=1611091455901674&mt=1612019324&fvip=3&c=WEB&txp=2316222&n=D2V5ZQlFoNYLyLI9l&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAKIhVpkCADZ2D0tPQBDM9k0jAgAaFSeqRDDDb8AZbRuvAiBi623sHG8KNvTiEcBO9k3HC7voEXGNXQiMl7QYbSeEmQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAL6unV_qzxUtp-HBBwcJRF_W63QN1kURWwDsAZ3UGKs4AiBMTxL0DLMfEc-2rFc-V2AJfrJuiOoLEIY70_Pd56qqdA%3D%3D'
[download] Destination: Arbeiten im Lockdown - Streit ums Homeoffice _ Panorama 3 _ NDR-ksp_sT6iiDo.mp4
[download] 100% of 76.94MiB in 00:02
[download] Downloading video 13 of 813
[youtube] c7l9RaYK0Ng: Downloading webpage
[youtube] c7l9RaYK0Ng: Downloading embed webpage
[youtube] c7l9RaYK0Ng: Refetching age-gated info webpage
WARNING: Unable to extract video title
ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 2106, in _real_extract
    raise ExtractorError('no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info')
youtube_dl.utils.ExtractorError: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

So I created a file tmp with the content:
```
https://www.youtube.com/playlist?list=PLQrsocOZ_VClJijiPEjyUSUwJkCm-Bler
```
Then I run `youtube-dl -a tmp --verbose`

The URL is a German playlist and youtube-dl always crashes at the 13th video. Edit: It's a private one.

**Comment by ivo-bloechliger** [comment]
First many thanks to the developpers for this fantastic piece of software!

I wanted to report the same issue trying to download a playlist, then I checked on the actual YouTube-Webseite and the videos in question were private and not visible to me in the browser neither. So not really a bug, but a nicer error message, explaining that the videos are private and possibly automatically skipping them would be just perfect. For reference, I tried to download with the following command:

youtube-dl --verbose --playlist-start 40 PLCRbP81QwKIxc0ewRdgCDCT5m7tQ1WfGx

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--playlist-start', '40', 'PLCRbP81QwKIxc0ewRdgCDCT5m7tQ1WfGx']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-65-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] PLCRbP81QwKIxc0ewRdgCDCT5m7tQ1WfGx: Downloading webpage
[download] Downloading playlist: Les as de la jungle à la rescousse   Saison 1
[youtube:tab] playlist Les as de la jungle à la rescousse   Saison 1: Downloading 12 videos
[download] Downloading video 1 of 12
[youtube] c6ER1WlxFwU: Downloading webpage
[youtube] c6ER1WlxFwU: Downloading embed webpage
[youtube] c6ER1WlxFwU: Refetching age-gated info webpage
WARNING: Unable to extract video title
ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 2106, in _real_extract
    raise ExtractorError('no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info')
youtube_dl.utils.ExtractorError: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ndsvw** [comment]
> and possibly automatically skipping them would be just perfect.

BTW: If someone has this issue: You can skip the unavailable/buggy videos of a playlist automatically with `-i` or `--ignore-errors`.
