### ISSUE TITLE
Instagram - Unable to extract video url

### ISSUE THREAD

**Issue by dustball** [ytdl-org/youtube-dl#28021]
## Checklist

- [ x] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.01.24.1**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
root@transcode-dev:/var/www/html/test_vids# youtube-dl -U
youtube-dl is up-to-date (2021.01.24.1)
root@transcode-dev:/var/www/html/test_vids# youtube-dl --verbose "https://www.instagram.com/p/CKewfsjoAzj/?igshid=1kf2sdnzbqax7"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.instagram.com/p/CKewfsjoAzj/?igshid=1kf2sdnzbqax7']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 2.7.17 (CPython) - Linux-5.4.0-1035-aws-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[Instagram] CKewfsjoAzj: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/instagram.py", line 216, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1128, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1019, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug

**Comment by Mennaruuk** [comment]
Hmm not sure why you're getting this error. I just downloaded the binary on Windows and ran the same command, and it downloaded fine. Can you try [reinstalling youtube-dl](https://github.com/mps-youtube/mps-youtube/issues/884#issuecomment-419880156) and retry the command?

```
C:\Users\Menna\Downloads>youtube-dl -U
youtube-dl is up-to-date (2021.01.24.1)
C:\Users\Menna\Downloads>youtube-dl --verbose "https://www.instagram.com/p/CKewfsjoAzj/?igshid=1kf2sdnzbqax7"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.instagram.com/p/CKewfsjoAzj/?igshid=1kf2sdnzbqax7']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[Instagram] CKewfsjoAzj: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://instagram.fdet1-2.fna.fbcdn.net/v/t50.2886-16/137656404_842667346310932_3836972731516903527_n.mp4?_nc_ht=instagram.fdet1-2.fna.fbcdn.net&_nc_cat=104&_nc_ohc=z41hEHFL780AX8wVA5c&oe=601AE236&oh=54e4091e650639b5c06337dd1e384624'
[download] Destination: Video by funkyae-CKewfsjoAzj.mp4
[download] 100% of 3.82MiB in 00:02
```

**Comment by xihuny** [comment]
I had the same problem. You need to use cookies with `--cookies` flag.

**Comment by yoelcabo** [comment]
This is happening to me when downloading through a proxy, but not when directly. Here is the dump of the intermediate page:


[CKMWCTThlM4_https_-_www.instagram.com_accounts_login_next=_p_CKMWCTThlM4_.txt](https://github.com/ytdl-org/youtube-dl/files/5970549/CKMWCTThlM4_https_-_www.instagram.com_accounts_login_next._p_CKMWCTThlM4_.txt)

```
<meta content="Welcome back to Instagram. Sign in to check out what your friends, family &amp; interests have been capturing &amp; sharing around the world." name="description" />
```

It would seem instagram is asking for a login

**Comment by xihuny** [comment]
This is with cookies?

**Comment by yoelcabo** [comment]
yep, I tried adding `--cookies cookie_file`

This is my cookies file if it helps
```
# Netscape HTTP Cookie File
# This file is generated by youtube-dl.  Do not edit.

.instagram.com	TRUE	/	TRUE	1644569602	csrftoken	j8LkzNb0F5dcwV7l7KhvyY3DoeaCFCuW
.instagram.com	TRUE	/	TRUE	1676192001	ig_did	925253B3-1D74-4DCA-AFF0-F816E3985A32
.instagram.com	TRUE	/	TRUE	1644656001	ig_nrcb	1
.instagram.com	TRUE	/	TRUE	1676192001	mid	YCZCAgALAAFR0xRChZDcLFcxX1PF
```

**Comment by yoelcabo** [comment]
I am not sure this is something that we can fix in youtube-dl. It is Instagram asking for a login. Something to fix in my proxy perhaps.

However one thing that would help a lot is that youtube-dl gives a nice error message. `ERROR: Login required`

**Comment by xihuny** [comment]
How did you generate the cookie file? Using any addon? Which browser did you use?

At first I used cookies without logging in to instagram (cookies generated when I visit instagram page) - This didn't work. 

Then I logged into Instagram and generated cookies. - This worked.

Do you mind sending the url of the video you are trying to download? I setup youtube-dl on my server very recently. I will check whether it works on my server.

**Comment by yoelcabo** [comment]
thanks @xihuny . Indeed I did not generate the cookies by logging in to instagram. 

Makes sense, thanks for pointing this out.

I still think we could handle this case better in youtube-dl by printing a nicer error message

**Comment by dustball** [comment]
As the original reporter, yeah, if something literally instructs me to file a bug report, I am going to do that 100% of the time.  (If I shouldn't be filing a bug report, then that error text itself is a bug.)

**Comment by taxen** [comment]
Up to some time this year, I had no problem downloading from Instagram without cookies. Now I have trouble with Instagram without cookies. And when I used cookies.txt file retrieved from web browser by using some add-on thanks to @xihuny, youtube-dl worked just fine. Not sure why cookies file is now required. Maybe Instagram has changed?

**Comment by Esoppant** [comment]
This error message seems to be appearing for every Instagram video since yesterday. Is there something one can do on the user end?

**Comment by dirkf** [comment]
WFM with no `--cookies`:
```
$ youtube-dl --test -v 'https://www.instagram.com/p/CKewfsjoAzj/?igshid=1kf2sdnzbqax7'
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--test', '-v', 'https://www.instagram.com/p/CKewfsjoAzj/?igshid=1kf2sdnzbqax7']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[Instagram] CKewfsjoAzj: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://instagram.flhr4-4.fna.fbcdn.net/v/t50.2886-16/141094358_1013397295818514_7895315071352646921_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InZ0c192b2RfdXJsZ2VuLjk2MC5mZWVkLmRlZmF1bHQiLCJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSJ9&_nc_ht=instagram.flhr4-4.fna.fbcdn.net&_nc_cat=110&_nc_ohc=J43B0UxrXkoAX8CWWwj&edm=AABBvjUBAAAA&vs=17873329199147765_2070584163&_nc_vs=HBksFQAYJEdOYnRhQWdTWjlYeHJaa0RBQWt0d19rNXk1RnRia1lMQUFBRhUAAsgBABUAGCRHS3NnYlFqTm5BYl8zWW9CQVBVUS1QVDFoRnhPYmtZTEFBQUYVAgLIAQAoABgAGwAVAAAm6qCU9tXsvz8VAigCQzMsF0A8zMzMzMzNGBJkYXNoX2Jhc2VsaW5lXzFfdjERAHXqBwA%3D&_nc_rid=2ac7dcb789&ccb=7-4&oe=610B7E08&oh=37622058a95f44e68cfc016e13e73e56&_nc_sid=83d603'
[download] Destination: Video by funkyae-CKewfsjoAzj.mp4
[download] 100% of 10.00KiB in 00:00
$
```

**Comment by mesposito-pattan** [comment]
Not working as of today. Two different URL's. 

```
$ youtube-dl -v https://www.instagram.com/p/CRu0To5ruQx/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.instagram.com/p/CRu0To5ruQx/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.10 (CPython) - Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[Instagram] CRu0To5ruQx: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/instagram.py", line 240, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1130, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
```
$ youtube-dl -v https://www.instagram.com/p/CSZ64OTlsVK/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.instagram.com/p/CSZ64OTlsVK/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.10 (CPython) - Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[Instagram] CSZ64OTlsVK: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/instagram.py", line 240, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1130, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment]
Both WFM without `--cookies`.

**Comment by 89z** [comment]
I have an alternative tool that works:

~~~
instagram -s CKewfsjoAzj
~~~

https://github.com/89z/mech

**Comment by ddelange** [comment]
The redirect to login (ref https://github.com/ytdl-org/youtube-dl/issues/30106#issuecomment-979419782) only happens under VPN for me. From my residential IP the download works, without providing cookies/credentials.

**Comment by 89z** [comment]
Also, for some reason Instagram returns totally different JSON, depending on if youre logged in [1] or not [2].

1. https://github.com/89z/mech/blob/v1.47.0/instagram/item.go#L141-L157
2. https://github.com/89z/mech/blob/v1.47.0/instagram/graph.go#L23-L34
