### ISSUE TITLE
[Tagesschau.de] New webdesign prevents all downloads

### ISSUE THREAD

**Issue by silsha** [ytdl-org/youtube-dl#28027]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.24.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.tagesschau.de/multimedia/sendung/ts-41249.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.9.1 (CPython) - macOS-11.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[Tagesschau] ts-41249: Downloading webpage
ERROR: Unable to extract download links; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/tagesschau.py", line 293, in _real_extract
    download_text = self._search_regex(
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract download links; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Tagesschau.de has launched a new web design. The permalinks have not changed, but the structure of the website has. youtube-dl is no longer able to download the videos.

**Comment by Nudin** [comment]
Some context: Tagesschau is the most known news format of German public broadcasting. Due to that their audio and video content can be legally downloaded – they offer a download button, however in the new web design the download button is integrated into the player and therefore is not accessible for browsers without javascript, some RSS readers and other use cases.

**Comment by Quix0r** [comment]
2021-03-03 ist still affected by this bug:
````
$ youtube-dl https://www.tagesschau.de/multimedia/video/video-69475.html
[Tagesschau] video-69475: Downloading webpage
ERROR: Unable to extract download links; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
quix0r@daedalus:~/Nextcloud/Screenshots$ youtube-dl --verbose https://www.tagesschau.de/multimedia/video/video-69475.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.tagesschau.de/multimedia/video/video-69475.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Python version 3.9.1+ (CPython) - Linux-5.4.0-4-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.2, ffprobe present, rtmpdump 2.4
[debug] Proxy map: {}
[Tagesschau] video-69475: Downloading webpage
ERROR: Unable to extract download links; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/tagesschau.py", line 293, in _real_extract
    download_text = self._search_regex(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract download links; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
$
````

**Comment by makuser** [comment]
#28435 would fix this. We now have to wait for it to be merged eventually.
