### ISSUE TITLE
 No video formats found crunchyroll

### ISSUE THREAD

**Issue by developcreativo** [ytdl-org/youtube-dl#28030]
**Command:** `youtube-dl --verbose --all-formats https://www.crunchyroll.com/dragon-ball-super/episode-105-a-desperate-battle-master-roshis-sacrifice-741903 -u "" -p ""`
```
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/crunchyroll.py", line 578, in _real_extract
    self._sort_formats(formats, ('preference', 'language_preference', 'height', 'width', 'tbr', 'fps'))
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1302, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output
```

**Comment by dirkf** [comment]
WFM:
```shellsession
$ python -m youtube_dl --ignore-config -F -v --user-agent 'Mozilla/5.0' 'https://www.crunchyroll.com/dragon-ball-super/episode-105-a-desperate-battle-master-roshis-sacrifice-741903'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ignore-config', u'-F', u'-v', u'--user-agent', u'Mozilla/5.0', u'https://www.crunchyroll.com/dragon-ball-super/episode-105-a-desperate-battle-master-roshis-sacrifice-741903']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: cc179df34
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[crunchyroll] 741903: Downloading webpage
[crunchyroll] 741903: Downloading adaptive_hls-audio-jaJP-hardsub-enUS information
[crunchyroll] 741903: Downloading adaptive_hls-audio-jaJP information
[crunchyroll] 741903: Downloading media info
WARNING: Unable to download XML: HTTP Error 404: Not Found
[info] Available formats for 741903:
format code                                  extension  resolution note
adaptive_hls-audio-jaJP-hardsub-enUS-562-0   mp4        428x240    [jaJP]  562k , avc1.42c015, 23.974fps, mp4a.40.2
adaptive_hls-audio-jaJP-hardsub-enUS-562-1   mp4        428x240    [jaJP]  562k , avc1.42c015, 23.974fps, mp4a.40.2
adaptive_hls-audio-jaJP-hardsub-enUS-1092-0  mp4        640x360    [jaJP] 1092k , avc1.4d401e, 23.974fps, mp4a.40.2
adaptive_hls-audio-jaJP-hardsub-enUS-1092-1  mp4        640x360    [jaJP] 1092k , avc1.4d401e, 23.974fps, mp4a.40.2
adaptive_hls-audio-jaJP-hardsub-enUS-2088-0  mp4        848x480    [jaJP] 2088k , avc1.4d401f, 23.974fps, mp4a.40.2
adaptive_hls-audio-jaJP-hardsub-enUS-2088-1  mp4        848x480    [jaJP] 2088k , avc1.4d401f, 23.974fps, mp4a.40.2
adaptive_hls-audio-jaJP-hardsub-enUS-4125-0  mp4        1280x720   [jaJP] 4125k , avc1.640028, 23.974fps, mp4a.40.2
adaptive_hls-audio-jaJP-hardsub-enUS-4125-1  mp4        1280x720   [jaJP] 4125k , avc1.640028, 23.974fps, mp4a.40.2
adaptive_hls-audio-jaJP-hardsub-enUS-8122-0  mp4        1920x1080  [jaJP] 8122k , avc1.640028, 23.974fps, mp4a.40.2
adaptive_hls-audio-jaJP-hardsub-enUS-8122-1  mp4        1920x1080  [jaJP] 8122k , avc1.640028, 23.974fps, mp4a.40.2
adaptive_hls-audio-jaJP-562-0                mp4        428x240    [jaJP]  562k , avc1.42c015, 23.974fps, mp4a.40.2
adaptive_hls-audio-jaJP-562-1                mp4        428x240    [jaJP]  562k , avc1.42c015, 23.974fps, mp4a.40.2
adaptive_hls-audio-jaJP-1093-0               mp4        640x360    [jaJP] 1093k , avc1.4d401e, 23.974fps, mp4a.40.2
adaptive_hls-audio-jaJP-1093-1               mp4        640x360    [jaJP] 1093k , avc1.4d401e, 23.974fps, mp4a.40.2
adaptive_hls-audio-jaJP-2089-0               mp4        848x480    [jaJP] 2089k , avc1.4d401f, 23.974fps, mp4a.40.2
adaptive_hls-audio-jaJP-2089-1               mp4        848x480    [jaJP] 2089k , avc1.4d401f, 23.974fps, mp4a.40.2
adaptive_hls-audio-jaJP-4111-0               mp4        1280x720   [jaJP] 4111k , avc1.640028, 23.974fps, mp4a.40.2
adaptive_hls-audio-jaJP-4111-1               mp4        1280x720   [jaJP] 4111k , avc1.640028, 23.974fps, mp4a.40.2
adaptive_hls-audio-jaJP-8124-0               mp4        1920x1080  [jaJP] 8124k , avc1.640028, 23.974fps, mp4a.40.2
adaptive_hls-audio-jaJP-8124-1               mp4        1920x1080  [jaJP] 8124k , avc1.640028, 23.974fps, mp4a.40.2 (best)
$
```
