### ISSUE TITLE
URL Unsupported for Tuckbot.tv, possibly due to hash/pound (#) ?

### ISSUE THREAD

**Issue by brettalton** [ytdl-org/youtube-dl#28050]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.24.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
% youtube-dl -v 'https://tuckbot.tv/#/watch/lat4hb'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://tuckbot.tv/#/watch/lat4hb']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.9.1 (CPython) - macOS-11.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] lat4hb: Requesting header
WARNING: Falling back on generic information extractor.
[generic] lat4hb: Downloading webpage
[generic] lat4hb: Extracting information
ERROR: Unsupported URL: https://tuckbot.tv/#/watch/lat4hb
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/generic.py", line 3467, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://tuckbot.tv/#/watch/lat4hb
```

## Description

I believe I escaped the URL properly [after viewing instructions for escaping](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).

Turns out is was easily downloadable, so posting in case it is a real error and can help future URL error cases.

**Comment by adrianheine** [comment]
I think tuckbot.tv is just not supported yet.

**Comment by Mennaruuk** [comment]
Correct. It does have a pretty simple pattern. A URL like
https://tuckbot.tv/#/watch/lanc5v
has a download link of
https://cdn.tuckbot.tv/lanc5v.mp4
