### ISSUE TITLE
[YouTube] - Error while merging video in webm

### ISSUE THREAD

**Issue by rstp14** [ytdl-org/youtube-dl#28068]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.02.04**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
D:\youtube-dl>youtube-dl -v --merge-output-format webm --recode-video webm https://www.youtube.com/watch?v=ElraGCidSZ0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--merge-output-format', 'webm', '--recode-video', 'webm', 'https://www.youtube.com/watch?v=ElraGCidSZ0']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2021.02.04
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-02-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube] ElraGCidSZ0: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r5---sn-n8v7znzl.googlevideo.com/videoplayback?expire=1612420709&ei=BUIbYMPXLoSk7QSAyKP4DQ&ip=95.28.127.181&id=o-AHvfj_In4A35zk85iqnSGoAfMtVgzeaWjVEGpI6yjQ2B&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=G7&mm=31%2C29&mn=sn-n8v7znzl%2Csn-n8v7snl7&ms=au%2Crdu&mv=m&mvi=5&pl=19&initcwndbps=2043750&vprv=1&mime=video%2Fmp4&ns=HQ5r2h-Kxck3qInYhqiF26kF&gir=yes&clen=21080069&dur=246.746&lmt=1612209694260512&mt=1612397809&fvip=5&keepalive=yes&c=WEB&txp=6316222&n=-JRQL3wjJJzu78Clm&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMgHdwqPsFzeJiJa1pqID_gF2TdqO5hCIP2HBJ8NBTq0AiEAnMGEUHwpltrAy5z6x92FlzVEMGE5QSvojyCU7TDi9nY%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgJ8EDhII6_DHzHGfNjBIZsohJvFB1UIUSLs7F4IxHfoUCIHXpkk1Oji2YpuxWCT13yHHB3oVrX57rJxV0dcpoOcnU'
[download] 4everfreebrony - Bound With Time (Acoustic)-ElraGCidSZ0.f137.mp4 has already been downloaded
[download] 100% of 20.10MiB
[debug] Invoking downloader on 'https://r5---sn-n8v7znzl.googlevideo.com/videoplayback?expire=1612420709&ei=BUIbYMPXLoSk7QSAyKP4DQ&ip=95.28.127.181&id=o-AHvfj_In4A35zk85iqnSGoAfMtVgzeaWjVEGpI6yjQ2B&itag=251&source=youtube&requiressl=yes&mh=G7&mm=31%2C29&mn=sn-n8v7znzl%2Csn-n8v7snl7&ms=au%2Crdu&mv=m&mvi=5&pl=19&initcwndbps=2043750&vprv=1&mime=audio%2Fwebm&ns=HQ5r2h-Kxck3qInYhqiF26kF&gir=yes&clen=4159732&dur=246.761&lmt=1612209695052315&mt=1612397809&fvip=5&keepalive=yes&c=WEB&txp=6311222&n=-JRQL3wjJJzu78Clm&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhALhZdK2_FzDGIeb0K41B5ZAE-mLmcfzEVZ0kUQivmeXBAiBrAx3jc5648OPSmec-HqRQPNlTcYQMFqRyiatEgHCzlA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgJ8EDhII6_DHzHGfNjBIZsohJvFB1UIUSLs7F4IxHfoUCIHXpkk1Oji2YpuxWCT13yHHB3oVrX57rJxV0dcpoOcnU'
[download] Destination: 4everfreebrony - Bound With Time (Acoustic)-ElraGCidSZ0.f251.webm
[download] 100% of 3.97MiB in 00:01
[ffmpeg] Merging formats into "4everfreebrony - Bound With Time (Acoustic)-ElraGCidSZ0.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:4everfreebrony - Bound With Time (Acoustic)-ElraGCidSZ0.f137.mp4" -i "file:4everfreebrony - Bound With Time (Acoustic)-ElraGCidSZ0.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:4everfreebrony - Bound With Time (Acoustic)-ElraGCidSZ0.temp.webm"
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2xgtxgc\build\youtube_dl\YoutubeDL.py", line 2102, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2xgtxgc\build\youtube_dl\postprocessor\ffmpeg.py", line 523, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2xgtxgc\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)
```

## Description

When trying to download the video "https://www.youtube.com/watch?v=ElraGCidSZ0" with the flags "--merge-output-format webm --recode-video webm", the result is the error "youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)"

**Comment by remitamine** [comment]
you can't merge `mp4` and `webm` files into a single `webm` file, either select compatible formats or don't use `--merge-output-format` to let youtube-dl select the appropriate container(`mkv` in this case).
