### ISSUE TITLE
NBA URL falls to generic and fails...

### ISSUE THREAD

**Issue by RingoTheDog** [ytdl-org/youtube-dl#28062]
## Checklist

- [x] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.02.04**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.py -v "https://ca.nba.com/videos/fred-vanvleet-sets-new-franchise-record-with-54-points-vs/bsec74zs7yb71muafoyvrxs7s"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://ca.nba.com/videos/fred-vanvleet-sets-new-franchise-record-with-54-points-vs/bsec74zs7yb71muafoyvrxs7s']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.02.04
[debug] Python version 3.6.6 (CPython) - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg N-71727-g46778ab, ffprobe N-87871-g7480f232d2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] bsec74zs7yb71muafoyvrxs7s: Requesting header
WARNING: Falling back on generic information extractor.
[generic] bsec74zs7yb71muafoyvrxs7s: Downloading webpage
[generic] bsec74zs7yb71muafoyvrxs7s: Extracting information
ERROR: Unsupported URL: https://ca.nba.com/videos/fred-vanvleet-sets-new-franchise-record-with-54-points-vs/bsec74zs7yb71muafoyvrxs7s
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 3490, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://ca.nba.com/videos/fred-vanvleet-sets-new-franchise-record-with-54-points-vs/bsec74zs7yb71muafoyvrxs7s
```

## Description

I am in Canada, so was provided link that started with ca.nba.com ....I'm guessing nba parser needs ca.nba.com added as valid URL?

**Comment by adrianheine** [comment]
They seem to be pretty different from each other, so I think this qualifies as a site-support-request.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31256

**Comment by vivandiu** [comment]
Ok

**Comment by vivandiu** [comment]
Ok
