### ISSUE TITLE
Tubi has changed their video URL youtube-dl may need to be updated

### ISSUE THREAD

**Issue by choc96208** [ytdl-org/youtube-dl#28067]
I have been unable to download new releases from tubitv.com. However I checked with video downloader extension and it still able to be downloaded. They seem to have changed the URL from cloudfront.tubi to fastly2.tubi.video. The older videos still use cloudfront.tubi though. I am also unable to download subtitles for either type of video.

Sorry if a post like this is not allowed. I'm bit confused about whether it is a pull release or an issue. 

```
    $ youtube-dl --list-subs -g -v -F https://tubitv.com/movies/544338/d-e-b-s?start=true
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--list-subs', '-g', '-v', '-F', 'https://tubitv.com/movies/544338/d-e-b-s?start=true']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.9.1 (CPython) - macOS-10.14.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 33, in <module>
    sys.exit(load_entry_point('youtube-dl==2021.1.24.1', 'console_scripts', 'youtube-dl')())
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/__init__.py", line 475, in main
    _real_main(argv)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2055, in download
    res = self.extract_info(
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 799, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/tubitv.py", line 78, in _real_extract
    formats = self._extract_m3u8_formats(
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1632, in _extract_m3u8_formats
    res = self._download_webpage_handle(
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 665, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    url_or_request = sanitized_Request(url_or_request, data, headers)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/utils.py", line 2157, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 320, in __init__
    self.full_url = url
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 346, in full_url
    self._parse()
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 375, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: ''
```
    
**VideoDownload Helper**
    
```
    pageUrl	
    https://tubitv.com/movies/544338/d-e-b-s?start=true
    
    url	
    https://fastly2.tubi.video/73bbe032-1dd5-47ca-92e5-18c77cc21f99/t494rp0y.mp4
```

```
$ youtube-dl -F -v https://tubitv.com/tv-shows/454378/s01-e09-sunday-morning?start=true
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-v', 'https://tubitv.com/tv-shows/454378/s01-e09-sunday-morning?start=true']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.9.1 (CPython) - macOS-10.14.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 6.192.237.82 (US) as X-Forwarded-For.
[TubiTv] 454378: Downloading JSON metadata
[TubiTv] 454378: Downloading m3u8 information
[info] Available formats for 454378:
format code  extension  resolution note
735          mp4        640x360     735k , avc1.4D401E, mp4a.40.2
1378         mp4        854x480    1378k , avc1.640028, mp4a.40.2
1993         mp4        1024x576   1993k , avc1.640028, mp4a.40.2 (best)
```

**Comment by choc96208** [comment]
Thanks for confirming that DRM is the issue. It would be nice if the youtube-dl developers added a DRM error message to the output instead of the default python output.
