### ISSUE TITLE
Svtplay.se is broken again

### ISSUE THREAD

**Issue by ijbh** [ytdl-org/youtube-dl#28060]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.24.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/svt.py", line 255, in _real_extract
    svt_id = self._search_regex(
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

As far as I can tell, no video link is working at the moment for this site. 

Here is an example of a video link: https://www.svtplay.se/video/18017043/beppes-smakresa/beppes-smakresa-sasong-1-kor

Thank you in advance!

**Comment by ijbh** [comment]
Why is this closed for outdated version? I have checked and gotten confirmation that I am using the latest version of youtube-dl
