### ISSUE TITLE
France.tv no video format found

### ISSUE THREAD

**Issue by FM33** [ytdl-org/youtube-dl#28099]
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2021.02.04.1**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v "https://www.france.tv/documentaires/societe/trolls/2156425-episode-3.html"
[debug] System config: []
[debug] User config: ['-o', '/media/fabien/Archives/%(title)s-%(id)s.%(ext)s', '--hls-prefer-ffmpeg']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.france.tv/documentaires/societe/trolls/2156425-episode-3.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.02.04.1
[debug] Python version 3.8.5 (CPython) - Linux-5.8.0-41-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[FranceTVSite] 2156425-episode-3: Downloading webpage
[FranceTV] 297f3670-d73b-43b6-91b6-70c23e8142d1: Downloading video JSON
[FranceTV] 297f3670-d73b-43b6-91b6-70c23e8142d1: Downloading geo restriction info
[FranceTV] 297f3670-d73b-43b6-91b6-70c23e8142d1: Downloading signed m3u8-download manifest URL
[FranceTV] 297f3670-d73b-43b6-91b6-70c23e8142d1: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[FranceTV] 297f3670-d73b-43b6-91b6-70c23e8142d1: Downloading signed hls_v5_os manifest URL
[FranceTV] 297f3670-d73b-43b6-91b6-70c23e8142d1: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 234, in _real_extract
    return self._extract_video(video_id, catalog)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 194, in _extract_video
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1367, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Error 404 then no video format found while video is playable on web page.

**Comment by florentk** [comment]
I got the same error, but with 503 HTTP error :

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.france.tv/france-2/cash-investigation/2344391-alcool-les-strategies-pour-nous-faire-boire.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.01
[debug] Python version 2.7.9 (CPython) - Linux-3.16.0-4-686-pae-i686-with-debian-8.10
[debug] exe versions: avconv 11.12-6, avprobe 11.12-6
[debug] Proxy map: {}
[FranceTVSite] 2344391-alcool-les-strategies-pour-nous-faire-boire: Downloading webpage
[FranceTV] 1812645b-fb68-47b4-b51c-ff21af3e2b75: Downloading video JSON
[FranceTV] 1812645b-fb68-47b4-b51c-ff21af3e2b75: Downloading geo restriction info
[FranceTV] 1812645b-fb68-47b4-b51c-ff21af3e2b75: Downloading signed m3u8-download manifest URL
[FranceTV] 1812645b-fb68-47b4-b51c-ff21af3e2b75: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 503: Service Unavailable
[FranceTV] 1812645b-fb68-47b4-b51c-ff21af3e2b75: Downloading signed hls_v5_os manifest URL
[FranceTV] 1812645b-fb68-47b4-b51c-ff21af3e2b75: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 503: Service Unavailable
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 234, in _real_extract
    return self._extract_video(video_id, catalog)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 194, in _extract_video
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1369, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by florentk** [comment]
When I analyse HTTP messages, I get a URL to a MPD file. I try this : `youtube-dl https://cloudreplay.ftven.fr/e8660d4636606/980280410_france-domtom_TA.ism/ZXhwPTE2MTc0NzU2ODN+YWNsPSUyZmU4NjYwZDQ2MzY2MDYlMmY5ODAyODA0MTBfZnJhbmNlLWRvbXRvbV9UQS5pc20qfmhtYWM9ODAxY2U0MmZhMjZjYjI4ZWE3MGQ5MzQ1YjBlOGZiYjlmOGU1ZTllMGI2ODc0OTg0YzVkNjVhNjMxMGZmNGE1OA==/manifest.mpd
`
And the video download ! Can we change the code to make this ?

![Capture d’écran de 2021-04-03 14-50-39](https://user-images.githubusercontent.com/5081764/113479079-1e06e500-948d-11eb-8912-8c3930be6c05.png)

**Comment by dirkf** [comment]
Video no longer available.
