### ISSUE TITLE
abc iview not working?

### ISSUE THREAD

**Issue by drelephant** [ytdl-org/youtube-dl#28095]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.02.04.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: [u'-f', u'(bestvideo[vcodec=vp9]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)', u'--merge-output-format', u'mkv', u'--add-metadata', u'--write-info-json', u'--embed-subs', u'--all-subs']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://iview.abc.net.au/show/media-bites/series/0/video/FR2035H002S00']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.02.04.1
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-154-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv N-48601-ge2f766e13f-static, avprobe 2.8.17, ffmpeg N-87201-g837c55e, ffprobe N-87201-g837c55e, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 1.149.95.7 (AU) as X-Forwarded-For.
[abc.net.au:iview] FR2035H002S00: Downloading JSON metadata
[abc.net.au:iview] FR2035H002S00: Downloading webpage
[abc.net.au:iview] FR2035H002S00: Downloading m3u8 information
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 838, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 872, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1671, in process_video_result
    expected=True)
ExtractorError: requested format not available

```

## Description

I can't seem to get any iview videos to download. Not sure how to proceed but I always get the error "requested format not available. I'm running ubuntu 16.04 which is pretty old, not sure if that's a reason why.

**Comment by Mennaruuk** [comment]
I can't seem to reproduce the errors:

```
C:\Users\Menna\Downloads>youtube-dl --verbose -F "https://iview.abc.net.au/show/media-bites/series/0/video/FR2035H002S00"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-F', 'https://iview.abc.net.au/show/media-bites/series/0/video/FR2035H002S00']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.02.04.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-essentials_build-www.gyan.dev, ffprobe 4.3.2-2021-02-02-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[debug] Using fake IP 1.131.224.43 (AU) as X-Forwarded-For.
[abc.net.au:iview] FR2035H002S00: Downloading JSON metadata
[abc.net.au:iview] FR2035H002S00: Downloading webpage
[abc.net.au:iview] FR2035H002S00: Downloading m3u8 information
[info] Available formats for FR2035H002S00:
format code  extension  resolution note
hls-291      mp4        320x180     291k , avc1.77.30, mp4a.40.2
hls-500      mp4        512x288     500k , avc1.77.30, mp4a.40.2
hls-608      mp4        640x360     608k , avc1.77.30, mp4a.40.2
hls-907      mp4        800x450     907k , avc1.640028, mp4a.40.2
hls-1280     mp4        1024x576   1280k , avc1.640028, mp4a.40.2
hls-1784     mp4        1280x720   1784k , avc1.640028, mp4a.40.2
hls-1813     mp4        1280x720   1813k , avc1.640028, mp4a.40.2 (best)
```

```
C:\Users\Menna\Downloads>youtube-dl --verbose -f best "https://iview.abc.net.au/show/media-bites/series/0/video/FR2035H002S00"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'best', 'https://iview.abc.net.au/show/media-bites/series/0/video/FR2035H002S00']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.02.04.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-essentials_build-www.gyan.dev, ffprobe 4.3.2-2021-02-02-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[debug] Using fake IP 1.128.116.32 (AU) as X-Forwarded-For.
[abc.net.au:iview] FR2035H002S00: Downloading JSON metadata
[abc.net.au:iview] FR2035H002S00: Downloading webpage
[abc.net.au:iview] FR2035H002S00: Downloading m3u8 information
[debug] Invoking downloader on 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/fr2/FR2035H002S00MA1D1_20210204180758_,4500000,3000000,1500000,1000000,650000,500000,220000,.mp4.csmil/index_0_av.m3u8?null=0&id=AgBEKCbFFyFUB9MMH2Avaj1MIeB7zIJ3AM6IUBfCx4W7amGWsf1q+AeQuQz7d9ElIxT360%2f79HJf3Q%3d%3d'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 22
[download] Destination: Systemic Eddie-FR2035H002S00.mp4
[download] 100% of 49.32MiB in 00:28
[debug] ffmpeg command line: ffprobe -show_streams "file:Systemic Eddie-FR2035H002S00.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "Systemic Eddie-FR2035H002S00.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Systemic Eddie-FR2035H002S00.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:Systemic Eddie-FR2035H002S00.temp.mp4"
```

**Comment by adrianheine** [comment]
Works for me, too.

**Comment by dstftw** [comment]
Read error message.

**Comment by drelephant** [comment]
@dstftw ahh ok, so I guess it is because of my user config file.

u'(bestvideo[vcodec=vp9]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)'

I set this up for youtube so it gets the highest-res vp9 video and opus audio preferentially, and bestvideo/bestaudio otherwise.

This seems to work fine for youtube but not in this case apparently.

Why isn't it getting "bestvideo"/"bestaudio" in this case because vp9/opus isn't available??

If you know, would you mind telling me how I can get it to work like I would like?

Thanks.
