### ISSUE TITLE
tiktok no longer works

### ISSUE THREAD

**Issue by kapatz** [ytdl-org/youtube-dl#28096]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.02.04.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
youtube-dl https://www.tiktok.com/@bruno.barbieri/video/6912333073854074114 --verbose
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.tiktok.com/@bruno.barbieri/video/6912333073854074114', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.02.04.1
[debug] Python version 3.6.8 (CPython) - Linux-3.10.0-1160.6.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[TikTok] Setting up session
[TikTok] 6912333073854074114: Downloading webpage
ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/tiktok.py", line 112, in _real_extract
    webpage, 'data'), video_id)['props']['pageProps']['itemInfo']['itemStruct']
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Mennaruuk** [comment]
I couldn't reproduce.

```
C:\Users\Menna\Downloads>youtube-dl https://www.tiktok.com/@bruno.barbieri/video/6912333073854074114 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.tiktok.com/@bruno.barbieri/video/6912333073854074114', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.02.04.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-essentials_build-www.gyan.dev, ffprobe 4.3.2-2021-02-02-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[TikTok] Setting up session
[TikTok] 6912333073854074114: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://v16-web.tiktok.com/video/tos/alisg/tos-alisg-pve-0037c001/aaebfd8a8b584cb38fe1a17d11354f75/?a=1988&br=2190&bt=1095&cd=0%7C0%7C1&ch=0&cr=0&cs=0&cv=1&dr=0&ds=3&er=&expire=1612656242&l=2021020618034701019020908300E9CEDA&lr=tiktok_m&mime_type=video_mp4&pl=0&policy=2&qs=0&rc=M2tpOG1rbGtyeTMzZDczM0ApaWk6ZTVoOTxpNzs1NzY3OGdocWtnMzRlaGpfLS1iMTRzczMtYDAwLzZjNjMuMjIxXzA6Yw%3D%3D&signature=7a4aa202fa0ec0ad3eaa6975c0d27c78&tk=tt_webid_v2&vl=&vr='
[download] Destination: BrunoBarbieriChef-6912333073854074114.mp4
[download] 100% of 2.06MiB in 00:01
```

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by kapatz** [comment]
I'm so sorry, now it works correctly

**Comment by saidattax** [comment]
Doesn't work for me, I'm using a VPN btw

Opening it on browser works fine

- [X]  I'm reporting a broken site support
- [X]  I've verified that I'm running youtube-dl version 2021.04.01
- [X]  I've checked that all provided URLs are alive and playable in a browser
- [X]  I've checked that all URLs and arguments with special characters are properly quoted or escaped

```
PS C:\Users\myuser\Desktop> youtube-dl 'https://www.tiktok.com/@sosatisfying/video/6922980332232871173' --dump-pages --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.tiktok.com/@sosatisfying/video/6922980332232871173', '--dump-pages', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.04.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-101185-g029e3c1c70, ffprobe N-101185-g029e3c1c70
[debug] Proxy map: {}
[TikTok] Setting up session
[TikTok] 6922980332232871173: Downloading webpage
[TikTok] Dumping request to https://www.tiktok.com/@sosatisfying/video/6922980332232871173
PCFET0NUWVBFIGh0bWw+CjxodG1sPgogICAgPEhlYWQ+CiAgICAgICAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogICAgICAgIDx0aXRsZT5UaWtUb2s8L3RpdGxlPgogICAgICAgIDxsaW5rIHJlbD0ic2hvcnRjdXQgaWNvbiIgdHlwZT0iaW1hZ2UveC1pY29uIiBpZD0iZmF2aWNvbiI+CiAgICAgICAgPG1ldGEgbmFtZT0ic2NyZWVuLW9yaWVudGF0aW9uIiBjb250ZW50PSJwb3J0cmFpdCI+CiAgICAgICAgPG1ldGEgbmFtZT0ieDUtb3JpZW50YXRpb24iIGNvbnRlbnQ9InBvcnRyYWl0Ij4KICAgICAgICA8bWV0YSBuYW1lPSJmb3JtYXQtZGV0ZWN0aW9uIiBjb250ZW50PSJ0ZWxlcGhvbmU9bm8iPgogICAgICAgIDxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MSwgdXNlci1zY2FsYWJsZT1ubywgbWluaW11bS1zY2FsZT0xLCBtYXhpbXVtLXNjYWxlPTEsIG1pbmltYWwtdWksIHZpZXdwb3J0LWZpdD1jb3ZlciI+CiAgICAgICAgPG1ldGEgbmFtZT0iYXBwbGUtbW9iaWxlLXdlYi1hcHAtY2FwYWJsZSIgY29udGVudD0ieWVzIj4KICAgICAgICA8bWV0YSBuYW1lPSJhcHBsaWNhYmxlLWRldmljZSIgY29udGVudD0icGMsbW9iaWxlIi8+CiAgICAgICAgPGxpbmsgcmVsPSJkbnMtcHJlZmV0Y2giIGhyZWY9Imh0dHBzOi8vc2YxNi1zY21jZG4tdmEuaWJ5dGVkdG9zLmNvbSIgLz4KICAgICAgICA8c2NyaXB0IGFzeW5jIHNyYz0iaHR0cHM6Ly9zZjE2LXNjbWNkbi12YS5pYnl0ZWR0b3MuY29tL2dvb2Z5L2xvZy1zZGsvY29sbGVjdC9jb2xsZWN0LXRjcHkuanMiPjwvc2NyaXB0PgogICAgICAgIDxzY3JpcHQ+CiAgICAgICAgICAgIGNvbnN0IG9wdGlvbiA9IHsidGl0bGUiOiJ0aWt0b2stdmVyaWZ5LXBhZ2UiLCJpaWQiOiIwIiwiZGlkIjoiMCIsImFwcF9uYW1lIjoidGlrdG9rIiwiYWlkIjoxMjg0LCJmYXZpY29uIjoiaHR0cHM6Ly9zMTYudGlrdG9rY2RuLmNvbS9tdXNpY2FsL3Jlc291cmNlL210YWN0L3N0YXRpYy9pbWFnZXMvdGlrdG9rLWxvZ28vbG9nby5wbmciLCJtb2JpbGVJY29ucyI6WyJodHRwczovL3MxNi50aWt0b2tjZG4uY29tL211c2ljYWwvcmVzb3VyY2UvbXRhY3Qvc3RhdGljL2ltYWdlcy90aWt0b2stbG9nby90aWt0b2tfbS5wbmciLCJodHRwczovL3MxNi50aWt0b2tjZG4uY29tL211c2ljYWwvcmVzb3VyY2UvbXRhY3Qvc3RhdGljL2ltYWdlcy90aWt0b2stbG9nby90aWt0b2tfbTJ4LnBuZyIsImh0dHBzOi8vczE2LnRpa3Rva2Nkbi5jb20vbXVzaWNhbC9yZXNvdXJjZS9tdGFjdC9zdGF0aWMvaW1hZ2VzL3Rpa3Rvay1sb2dvL3Rpa3Rva19tM3gucG5nIl0sImljb25zIjpbImh0dHBzOi8vczE2LnRpa3Rva2Nkbi5jb20vbXVzaWNhbC9yZXNvdXJjZS9tdGFjdC9zdGF0aWMvaW1hZ2VzL3Rpa3Rvay1sb2dvL3Rpa3Rva193LnBuZyIsImh0dHBzOi8vczE2LnRpa3Rva2Nkbi5jb20vbXVzaWNhbC9yZXNvdXJjZS9tdGFjdC9zdGF0aWMvaW1hZ2VzL3Rpa3Rvay1sb2dvL3Rpa3Rva193MngucG5nIiwiaHR0cHM6Ly9zMTYudGlrdG9rY2RuLmNvbS9tdXNpY2FsL3Jlc291cmNlL210YWN0L3N0YXRpYy9pbWFnZXMvdGlrdG9rLWxvZ28vdGlrdG9rX3czeC5wbmciXSwicmVnaW9uIjoidmEiLCJ0eXBlIjoic2xpZGUiLCJ2ZXJpZnlDb25maWciOnsiY29kZSI6MTAwMDAsInR5cGUiOiJ2ZXJpZnkiLCJzdWJ0eXBlIjoic2xpZGUiLCJmcCI6InZlcmlmeV84MjJjMTVhMzM5OGQxODBmYzZmMjg0Yjk0ZDFmNDJlMCIsInJlZ2lvbiI6InZhIiwiZGV0YWlsIjoidEdaTypHWUJLUlROallZRGZpeDZ3VmY0UHlvVmtpb1NQMkdqNGRrZEFQSDBnNVg2bDBlYktlOENQMVBYVVNCeHNWNU8wNWgqRWxmajZVRXpkN3UtYmhIQndMRWdFZERna2VSeEMwbndFTW5YWk9XRlBDRTRld0owR0o3VHFPdTUzOFpwd2ZnU2N6WnBXYUYxM1FFRzVZcVlkMDBhckVZcUVqNmFIOHU2Y3NTdDdoWTFhc1hQT1hHN1JUWSpNSTJFWmpOeEo0N2VlTXZIYkV0dWxROFc5eG0qLVlBakhTM1RkVGtteGdEVVBYLU0tUXdneDBIUWpXbGw5LVJ3dkpvRnhXaWw3aCpNeHNpOWYtaFBaNjVpcnEyZjAxMjB0RFRQZnhPLWFDS1lDckltRjNnZHk4cDlncmY5anRNR3JyR1FVdjBORTF3Nmk4Zk1DdzVUWWs2NWpzbEpUQURrQVl2T2YxaU4tSDRpVS11NUc3VkllcE55N0RtS1oyT3JvOG1iSHZCMCppcVNvd0FVdVlsZm5ILUMzTWwzdjd0KmRnMzdOZy4uIn0sImxhbmciOiJlbiJ9OwoKICAgICAgICAgICAgaWYoIW9wdGlvbi5yZWdpb24pIHsKICAgICAgICAgICAgICAgIG9wdGlvbi5yZWdpb24gPSAndmEnOwogICAgICAgICAgICB9CiAgICAgICAgICAgIHZhciB2ZXJpZnlUaW1lID0gbmV3IERhdGUoKS5nZXRUaW1lKCk7CiAgICAgICAgICAgIChmdW5jdGlvbih3aW4sIGV4cG9ydF9vYmopIHsKICAgICAgICAgICAgICAgIHdpblsnVGVhQW5hbHl0aWNzT2JqZWN0J10gPSBleHBvcnRfb2JqOwogICAgICAgICAgICAgICAgaWYgKCF3aW5bZXhwb3J0X29ial0pIHsKICAgICAgICAgICAgICAgICAgICBmdW5jdGlvbiBfY29sbGVjdCgpIHsKICAgICAgICAgICAgICAgICAgICAgICAgX2NvbGxlY3QucS5wdXNoKGFyZ3VtZW50cyk7CiAgICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgICAgIF9jb2xsZWN0LnEgPSBfY29sbGVjdC5xIHx8IFtdOwogICAgICAgICAgICAgICAgICAgIHdpbltleHBvcnRfb2JqXSA9IF9jb2xsZWN0OyAgICAgICAgICAgIAogICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgd2luW2V4cG9ydF9vYmpdLmwgPSArbmV3IERhdGUoKTsKICAgICAgICAgICAgfSkod2luZG93LCAnY29sbGVjdEV2ZW50Jyk7CgogICAgICAgICAgICB3aW5kb3cuY29sbGVjdEV2ZW50KCdwYWdlLmluaXQnLCB7CiAgICAgICAgICAgICAgICBhcHBfaWQ6IG9wdGlvbi5yZWdpb24gPT09ICdjbicgPyAyMDE4IDogMjc0MCwKICAgICAgICAgICAgICAgIGNoYW5uZWw6IG9wdGlvbi5yZWdpb24gPT09ICdib2UnID8gJ2NuJyA6IG9wdGlvbi5yZWdpb24sCiAgICAgICAgICAgICAgICBsb2c6IHRydWUsCiAgICAgICAgICAgIH0pOwoKICAgICAgICAgICAgd2luZG93LmNvbGxlY3RFdmVudCgncGFnZS5zdGFydCcpOwogICAgICAgICAgICB3aW5kb3cuY29sbGVjdEV2ZW50KCdwYWdlLnZlcmlmeV9wYWdlX2xvYWQnLCB7CiAgICAgICAgICAgICAgICBhaWQ6IG9wdGlvbi5haWQsCiAgICAgICAgICAgICAgICBwcm9kdWN0X2hvc3Q6IGxvY2F0aW9uLmhvc3QsCiAgICAgICAgICAgICAgICBwcm9kdWN0X3BhdGg6IGxvY2F0aW9uLnBhdGhuYW1lLAogICAgICAgICAgICAgICAgdGltZTogbmV3IERhdGUoKS5nZXRUaW1lKCksCiAgICAgICAgICAgICAgICBpc19zdWNjZXNzOiAwLAogICAgICAgICAgICAgICAgZHVyYXRpb246IG5ldyBEYXRlKCkuZ2V0VGltZSgpIC0gdmVyaWZ5VGltZQogICAgICAgICAgICB9KQogICAgICAgICAgICB3aW5kb3cub25iZWZvcmV1bmxvYWQgPSBmdW5jdGlvbiAoKSB7CiAgICAgICAgICAgICAgICB3aW5kb3cuY29sbGVjdEV2ZW50KGRvY3VtZW50LnJlYWR5U3RhdGUgPT09ICdjb21wbGV0ZScgPyAncGFnZS52ZXJpZnlfcGFnZV9jbG9zZScgOiAncGFnZS52ZXJpZnlfcGFnZV9sb2FkX2Nsb3NlJywgewogICAgICAgICAgICAgICAgICAgIHByb2R1Y3RfaG9zdDogbG9jYXRpb24uaG9zdCwKICAgICAgICAgICAgICAgICAgICBwcm9kdWN0X3BhdGg6IGxvY2F0aW9uLnBhdGhuYW1lLAogICAgICAgICAgICAgICAgICAgIGFpZDogb3B0aW9uLmFpZCwKICAgICAgICAgICAgICAgICAgICB0aW1lOiBuZXcgRGF0ZSgpLmdldFRpbWUoKSwKICAgICAgICAgICAgICAgICAgICBmcDogKGRvY3VtZW50LmNvb2tpZS5tYXRjaCgvc192X3dlYl9pZD0oXHcrKS8pIHx8IFtdKVsxXSwKICAgICAgICAgICAgICAgICAgICBpc19zdWNjZXNzOiBOdW1iZXIoISF3aW5kb3cudmVyaWZ5X2lzX3N1Y2Nlc3MpCiAgICAgICAgICAgICAgICB9KQogICAgICAgICAgICB9CiAgICAgICAgPC9zY3JpcHQ+CiAgICAgICAgPHNjcmlwdCBzcmM9Imh0dHBzOi8vc2YxNi1zY21jZG4tdmEuaWJ5dGVkdG9zLmNvbS9nb29meS9zZWNfc2RrX2J1aWxkLzMuMS4zL2NhcHRjaGEvaW5kZXguanMiPjwvc2NyaXB0PgogICAgICAgIDxzY3JpcHQgYXN5bmMgc3JjPSJodHRwczovL3NmMTYtbXVzZS12YS5pYnl0ZWR0b3MuY29tL29iai9lZGVuLXZhMi9mdml5bGNsc2plaDdib2d1YmZiZC90dC13ZWJhcHAvc3RhcmxpbmcuYnJvd3Nlci5qcyI+PC9zY3JpcHQ+CiAgICA8L0hlYWQ+CiAgICA8Ym9keT4KICAgICAgICA8ZGl2IGNsYXNzPSJjb250ZW50Ij4KICAgICAgICAgICAgPGRpdiBjbGFzcz0iYXBwX2ljb24iPjwvZGl2PgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJ2ZXJpZnktd3JhcCI+CiAgICAgICAgICAgICAgICA8ZGl2IGlkPSJ2ZXJpZnktZWxlIj48L2Rpdj4KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgIDxwIGNsYXNzPSJwYWdlLWRlc2MiIGlkPSJ2ZXJpZnlFbGUiPjwvcD4KICAgICAgICA8L2Rpdj4KICAgIDxzY3JpcHQgdHlwZT0idGV4dC9qYXZhc2NyaXB0IiA+dmFyIF9jZiA9IF9jZiB8fCBbXTsgICAgX2NmLnB1c2goWydfc2V0Qm0nLCB0cnVlXSk7ICBfY2YucHVzaChbJ19zZXRBdScsICcvcmVzb3VyY2UvMmZhNzZiYWM5ZnJuMjUwMmI5NjBmYTcxZWJhNzY3NTAnXSk7IDwvc2NyaXB0PjxzY3JpcHQgdHlwZT0idGV4dC9qYXZhc2NyaXB0IiAgc3JjPSIvcmVzb3VyY2UvMmZhNzZiYWM5ZnJuMjUwMmI5NjBmYTcxZWJhNzY3NTAiPjwvc2NyaXB0PjwvYm9keT4KICAgIDxzdHlsZT4KICAgICAgICBodG1sLCBib2R5IHsKICAgICAgICAgICAgbWluLWhlaWdodDogNTAwcHg7CiAgICAgICAgfQogICAgICAgIGJvZHkgewogICAgICAgICAgICBiYWNrZ3JvdW5kOiAjRURGMEY1OwogICAgICAgICAgICBkaXNwbGF5OiBmbGV4OwogICAgICAgIH0KICAgICAgICAuY29udGVudCB7IAogICAgICAgICAgICB3aWR0aDogMzAwcHg7CiAgICAgICAgICAgIG1hcmdpbjogYXV0bzsKICAgICAgICB9CgogICAgICAgIC52ZXJpZnktd3JhcCB7CiAgICAgICAgICAgIG1pbi1oZWlnaHQ6IDMwNnB4OwogICAgICAgIH0KCiAgICAgICAgQG1lZGlhIChtaW4td2lkdGg6IDEyODFweCkgewogICAgICAgICAgICAuY29udGVudCB7CiAgICAgICAgICAgICAgICB3aWR0aDogMzgwcHg7CiAgICAgICAgICAgIH0KCiAgICAgICAgICAgIC52ZXJpZnktd3JhcCB7CiAgICAgICAgICAgICAgICBtaW4taGVpZ2h0OiAzODZweDsKICAgICAgICAgICAgfQogICAgICAgIH0KICAgICAgICAKICAgICAgICAuY2FwdGNoYV92ZXJpZnlfY29udGFpbmVyIHsKICAgICAgICAgICAgYm9yZGVyOiAxcHggc29saWQgI0U4RThFODsKICAgICAgICB9CgogICAgICAgIC5jYXB0Y2hhX3ZlcmlmeV9jb250YWluZXIgI3ZlcmlmeS1iYXItY2xvc2UgewogICAgICAgICAgICBkaXNwbGF5OiBub25lOwogICAgICAgIH0KCiAgICAgICAgLmFwcF9pY29uIGltZyB7CiAgICAgICAgICAgIG1hcmdpbi1ib3R0b206IDIwcHg7CiAgICAgICAgfQoKICAgICAgICAucGFnZS1kZXNjewogICAgICAgICAgICBtYXJnaW4tdG9wOiAzMnB4OwogICAgICAgICAgICBmb250LWZhbWlseTogUGluZ0ZhbmdTQy1NZWRpdW07CiAgICAgICAgICAgIGZvbnQtc2l6ZTogMTJweDsKICAgICAgICAgICAgY29sb3I6ICM1MDUwNTA7CiAgICAgICAgICAgIGxpbmUtaGVpZ2h0OiAxOXB4OwogICAgICAgIH0KCiAgICAgICAgLnBhZ2UtZGVzYyBzcGFuIHsKICAgICAgICAgICAgZm9udC1mYW1pbHk6ICdQaW5nRmFuZ1NDLVJlZ3VsYXInOwogICAgICAgICAgICBjb2xvcjogIzUwNTA1MDsKCiAgICAgICAgfQogICAgPC9zdHlsZT4KICAgIDxzY3JpcHQ+CiAgICAgICAgY29uc3QgcGFnZURlc2NLZXkgPSAndXNlcl92ZXJpZnlfcGFnZV9kZXNjcmlwdGlvbic7CiAgICAgICAgY29uc3QgdWEgPSBuYXZpZ2F0b3IudXNlckFnZW50OwogICAgICAgIGNvbnN0IGlzTW9iaWxlID0gL0FuZHJvaWR8d2ViT1N8aVBob25lfGlQb2R8QmxhY2tCZXJyeXxXaW5kb3dzIFBob25lfGlQYWQvaS50ZXN0KHVhKTsKICAgICAgICBjb25zdCBob3N0cyA9IHsKICAgICAgICAgICAgY246ICcvL3ZlcmlmeS5zbnNzZGsuY29tJywKICAgICAgICAgICAgYm9lOiAnLy9ib2UtdmVyaWZ5LnNuc3Nkay5jb20nLAogICAgICAgICAgICBzZzogJy8vdmVyaWZ5LXNnLmJ5dGVvdmVyc2VhLmNvbScsCiAgICAgICAgICAgIHZhOiAnLy92ZXJpZmljYXRpb24tdmEuYnl0ZW92ZXJzZWEuY29tJwogICAgICAgIH07CgogICAgICAgIHdpbmRvdy5UVEdDYXB0Y2hhLmluaXQoewogICAgICAgICAgY29tbW9uT3B0aW9uczogewogICAgICAgICAgICBhaWQ6IG9wdGlvbi5haWQgfHwgMCwKICAgICAgICAgICAgZGlkOiAnMCcsCiAgICAgICAgICAgIGlpZDogJzAnLAogICAgICAgICAgfSwKICAgICAgICAgIGNhcHRjaGFPcHRpb25zOiB7CiAgICAgICAgICAgIGVsZTogJ3ZlcmlmeS1lbGUnLAogICAgICAgICAgICBob3N0OiBob3N0c1tvcHRpb24ucmVnaW9uXSwKICAgICAgICAgICAgbGFuZzogb3B0aW9uLmxhbmcubWF0Y2goL3poLykgPyAnemgtSGFudCcgOiBvcHRpb24ubGFuZywKICAgICAgICAgICAgcmVnaW9uOiBvcHRpb24ucmVnaW9uLAogICAgICAgICAgICBhcHBfbmFtZTogb3B0aW9uLmFwcF9uYW1lIHx8ICcnLAogICAgICAgICAgICBoaWRlQ2xvc2VCdG46IHRydWUsCiAgICAgICAgICAgIHN1Y2Nlc3NDYjogc3VjY2Vzc0NiLAogICAgICAgICAgICBmZWVkYmFja1N1Ym1pdENiOiBmZWVkYmFja1N1Ym1pdENiLAogICAgICAgICAgICBhdXRvQ2xvc2U6IGZhbHNlCiAgICAgICAgICB9LAogICAgICAgIH0pOwogICAgICAgCiAgICAgICAgd2luZG93Lm9ubG9hZCA9IGZ1bmN0aW9uICgpIHsKICAgICAgICAgICAgd2luZG93LnZlcmlmeV9pc19zdWNjZXNzID0gdHJ1ZTsKICAgICAgICAgICAgZG9jdW1lbnQucXVlcnlTZWxlY3RvcignI2Zhdmljb24nKS5ocmVmID0gb3B0aW9uLmZhdmljb247CiAgICAgICAgICAgIGRvY3VtZW50LnRpdGxlID0gb3B0aW9uLnRpdGxlIHx8ICdzZWN1cml0eSB2ZXJpZmljYXRpb24nOwogICAgICAgICAgICBjb25zdCBpY29uID0gaXNNb2JpbGUgPyBvcHRpb24ubW9iaWxlSWNvbnMgOiBvcHRpb24uaWNvbnM7CiAgICAgICAgICAgIGlmIChvcHRpb24uaWNvbnMgfHwgdHJ1ZSkgewogICAgICAgICAgICAgICAgbGV0IGltZyA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2ltZycpOwogICAgICAgICAgICAgICAgaW1nLnNyY3NldCA9IGAke2ljb25bMF19IDF4LAogICAgICAgICAgICAgICAgICAgICR7aWNvblsxXX0gMngsCiAgICAgICAgICAgICAgICAgICAgJHtpY29uWzJdfSAzeGA7CiAgICAgICAgICAgICAgICBpbWcuYWx0ID0gJ2FwcCBsb2dvJzsKICAgICAgICAgICAgICAgIGltZy5zcmMgPSBpY29uWzBdOwogICAgICAgICAgICAgICAgZG9jdW1lbnQucXVlcnlTZWxlY3RvcignLmFwcF9pY29uJykuYXBwZW5kQ2hpbGQoaW1nKTsKICAgICAgICAgICAgfQoKICAgICAgICAgICAgd2luZG93LmNvbGxlY3RFdmVudChsb2NhdGlvbi5ocmVmID09PSBkb2N1bWVudC5yZWZlcnJlciA/ICdwYWdlLnZlcmlmeV9wYWdlX3JlZnJlc2gnIDogJ3BhZ2UudmVyaWZ5X3BhZ2VfaW5pdCcsIHsKICAgICAgICAgICAgICAgIGR1cmF0aW9uOiBuZXcgRGF0ZSgpLmdldFRpbWUoKSAtIHZlcmlmeVRpbWUsCiAgICAgICAgICAgICAgICBhaWQ6IG9wdGlvbi5haWQsCiAgICAgICAgICAgICAgICByZWdpb246IG9wdGlvbi5yZWdpb24sCiAgICAgICAgICAgICAgICBmcDogKGRvY3VtZW50LmNvb2tpZS5tYXRjaCgvc192X3dlYl9pZD0oXHcrKS8pIHx8IFtdKVsxXSwKICAgICAgICAgICAgICAgIGlzX3N1Y2Nlc3M6IDEsCiAgICAgICAgICAgICAgICBwcm9kdWN0X2hvc3Q6IGxvY2F0aW9uLmhvc3QsCiAgICAgICAgICAgICAgICBwcm9kdWN0X3BhdGg6IGxvY2F0aW9uLnBhdGhuYW1lLAogICAgICAgICAgICB9KQoKICAgICAgICAgICAgY29uc3Qgc3RhcmxpbmcgPSBuZXcgU3RhcmxpbmcoewogICAgICAgICAgICAgICAgYXBpX2tleTogJzVkYzI2Y2YwMDhkNTExZTliNTcxZTFiYzBjOWUyM2I1JywKICAgICAgICAgICAgICAgIG5hbWVzcGFjZTogJ0NhcHRjaGEnLAogICAgICAgICAgICAgICAgbG9jYWxlOiBvcHRpb24ubGFuZywKICAgICAgICAgICAgICAgIHpvbmU6IChvcHRpb24ucmVnaW9uIHx8ICdTRycpLnRvVXBwZXJDYXNlKCksCiAgICAgICAgICAgICAgICB0ZXN0OiBmYWxzZSwKICAgICAgICAgICAgICAgIGZhbGxiYWNrTGFuZzogWydlbiddLAogICAgICAgICAgICB9KTsKICAgICAgICAgICAgc3RhcmxpbmcubG9hZCgodGV4dHMpID0+IHsKICAgICAgICAgICAgICAgIGxldCBkZXNjID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignI3ZlcmlmeUVsZScpOwogICAgICAgICAgICAgICAgZGVzYy5pbm5lclRleHQgPSB0ZXh0c1twYWdlRGVzY0tleV07CiAgICAgICAgICAgIH0pOwoKICAgICAgICAgICAgd2luZG93LlRUR0NhcHRjaGEucmVuZGVyKHsKICAgICAgICAgICAgICAgIHZlcmlmeV9kYXRhOiBKU09OLnN0cmluZ2lmeSh7CiAgICAgICAgICAgICAgICAgIHN1YnR5cGU6IG9wdGlvbi50eXBlLAogICAgICAgICAgICAgICAgICAuLi4ob3B0aW9uLnZlcmlmeUNvbmZpZyB8fCB7fSksCiAgICAgICAgICAgICAgICB9KQogICAgICAgICAgICB9KTsKCiAgICAgICAgICAgIC8vIHR0IGVtYmVkIGlmcmFtZQogICAgICAgICAgICBpZiAod2luZG93LnNlbGYgIT09IHdpbmRvdy50b3AgJiYgd2luZG93Lm5hbWUuaW5kZXhPZignX190dF9lbWJlZF9fJykgIT09IC0xKSB7CiAgICAgICAgICAgICAgICBjb25zdCByZXNpemVEYXRhID0gSlNPTi5zdHJpbmdpZnkoewogICAgICAgICAgICAgICAgICAgIHNpZ25hbFNvdXJjZTogd2luZG93Lm5hbWUsCiAgICAgICAgICAgICAgICAgICAgaGVpZ2h0OiA2MDAsCiAgICAgICAgICAgICAgICB9KTsKICAgICAgICAgICAgICAgIHdpbmRvdy5wYXJlbnQucG9zdE1lc3NhZ2UocmVzaXplRGF0YSwgJyonKTsKICAgICAgICAgICAgfQogICAgICAgIH0KCiAgICAgICAgZnVuY3Rpb24gc3VjY2Vzc0NiKCkgewogICAgICAgICAgICBsb2NhdGlvbi5yZWxvYWQoKTsKICAgICAgICB9CgogICAgICAgIGZ1bmN0aW9uIGZlZWRiYWNrU3VibWl0Q2IoKSB7CiAgICAgICAgICAgIHdpbmRvdy5UVEdDYXB0Y2hhLnJlbmRlcih7CiAgICAgICAgICAgICAgICB2ZXJpZnlfZGF0YTogSlNPTi5zdHJpbmdpZnkoewogICAgICAgICAgICAgICAgICBzdWJ0eXBlOiBvcHRpb24udHlwZSwKICAgICAgICAgICAgICAgICAgLi4uKG9wdGlvbi52ZXJpZnlDb25maWcgfHwge30pLAogICAgICAgICAgICAgICAgfSkKICAgICAgICAgICAgfSk7CiAgICAgICAgfQogICAgPC9zY3JpcHQ+CjwvaHRtbD4=
ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\extractor\tiktok.py", line 112, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
