### ISSUE TITLE
[cda_pl] cannot download videos

### ISSUE THREAD

**Issue by elvisef** [ytdl-org/youtube-dl#28106]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.02.04.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

For a free video:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.cda.pl/video/540114ae/vfilm']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.02.04.1
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-14-amd64-x86_64-with-debian-10.8
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[CDA] 540114ae: Downloading webpage
WARNING: unable to extract default player_json; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cda.py", line 207, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1367, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

For a premium video:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.cda.pl/video/65105665c/vfilm', u'-u', u'PRIVATE', u'-p', u'PRIVATE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.02.04.1
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-14-amd64-x86_64-with-debian-10.8
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[CDA] 65105665c: Downloading webpage
ERROR: This video is only available for premium users.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cda.py", line 96, in _real_extract
    raise ExtractorError('This video is only available for premium users.', expected=True)
ExtractorError: This video is only available for premium users.
```

## Description

**Command used**: youtube-dl -v https://www.cda.pl/video/540114ae/vfilm
**OS**: Linux Debian 10 (Buster)

Sample links:
**free**: `https://www.cda.pl/video/540114ae/vfilm`
**premium**: `https://www.cda.pl/video/65105665c/vfilm`

I've tested als with "-u" and "-p" arguments - ie. with my premium account credentials (my pass stars from " sign, but I've escaped the whole pass with ' signs), but it didn't work.

My python version is: 2.7.16
While testing downloading, no VPN or Proxy were active. Direct connection only.

**Comment by dstftw** [comment]
You must provide PL proxy/VPN/SSH and account credentials for any work on this.

**Comment by elvisef** [comment]
> You must provide PL proxy/VPN/SSH and account credentials for any work on this.

Write me what location are You connecting from, I will check if it works from Your current location first.
Credentials for premium account will be sent later.

**Comment by dstftw** [comment]
I've already checked that.

**Comment by elvisef** [comment]
Ok, here's a 24h access to CG vpn service:

- the app: [https://www.cyberghostvpn.com/download/cg8/winold/cgsetup_en_jQWW8b8CRmbvrnjSNqM3.exe](https://www.cyberghostvpn.com/download/cg8/winold/cgsetup_en_jQWW8b8CRmbvrnjSNqM3.exe)
- **where to send login/pass ?**

**Comment by elvisef** [comment]
Refreshing a problem. What do do next then ? Do You need additional data ? How cna I download videos from cda.pl ?
