### ISSUE TITLE
No Video Formats Found; For a Youtube link

### ISSUE THREAD

**Issue by Sirri69** [ytdl-org/youtube-dl#28109]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.02.04.1**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed 

## Verbose log

```
 youtube-dl --verbose -o "kop.mp3" --extract-audio -x --audio-format mp3 https://www.youtube.com/watch?v=eWfI4tvRdL8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-o', 'kop.mp3', '--extract-audio', '-x', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=eWfI4tvRdL8']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.02.04.1
[debug] Python version 3.8.7 (CPython) - Linux-5.4.0-1019-gcp-x86_64-with-glibc2.27
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[youtube] eWfI4tvRdL8: Downloading webpage
WARNING: Unable to download webpage: HTTP Error 429: Too Many Requests
[youtube] eWfI4tvRdL8: Downloading API JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1592, in _real_extract
    self._sort_formats(formats)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1367, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I'm trying to download [this](https://www.youtube.com/watch?v=eWfI4tvRdL8) Youtube video, but it keeps saying **No video formats found**. I found a command [here](https://stackoverflow.com/questions/63874184/youtube-dl-doesnt-work-as-expected-in-pycharm), it solves the issue for the specific video, but doesn't work for me.

Also, I see a few more issues related to **No Formats Found** error. [Same issue with PluralSight](https://github.com/ytdl-org/youtube-dl/issues/27991), [with France.tv](https://github.com/ytdl-org/youtube-dl/issues/28099).

Happy Debugging !!

**Comment by Sirri69** [comment]
Wait, is this issue resolved ?

**Comment by TENTHARSOS** [comment]
Hey, I'm having similar problems as yours; did you ever figure it out?

**Comment by Sirri69** [comment]
@TENTHARSOS Well, I ran the same code a few hours after and it worked.

I don't have any clue how or why, but hey, that's what most of coding is....
