### ISSUE TITLE
ERROR: No video formats found Xhamster

### ISSUE THREAD

**Issue by smut-getter** [ytdl-org/youtube-dl#28110]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.02.04.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose https://xhamster.com/videos/wife-s-bbc-gb-ends-with-bukake-xheFOIL
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://xhamster.com/videos/wife-s-bbc-gb-ends-with-bukake-xheFOIL']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.02.04.1
[debug] Python version 3.7.7 (CPython) - Darwin-20.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[XHamster] xheFOIL: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/anaconda3/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/opt/anaconda3/lib/python3.7/site-packages/youtube_dl/extractor/xhamster.py", line 178, in _real_extract
    self._sort_formats(formats)
  File "/opt/anaconda3/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1367, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Newly added videos on Xhamster site no longer are downloadable. Older URLS still work

**Comment by taxhelp101** [comment]
I'm getting the same error as I am trying to archive someone's channel. Kinda new here. Should I open up my own ticket to with the code that I see in my command prompt?

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.
