### ISSUE TITLE
[Youtube]Cannot download private video with username and password

### ISSUE THREAD

**Issue by sebma** [ytdl-org/youtube-dl#28147]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.02.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', '-u', 'PRIVATE', 'https://youtu.be/GccIPxHQodc']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.02.10
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-58-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
[youtube] GccIPxHQodc: Downloading webpage
ERROR: Private video
Sign in if you've been granted access to this video
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1630, in _real_extract
    raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: Private video
Sign in if you've been granted access to this video
$ echo $?
1
```

## Description

Hi,

I cannot download any YouTube private video with username and password, can you help ?
My video will be published soon so it will download soon.
But you can try with any of your private video to investigate this.

Thanks for the great job you've done so far, god bless you !

**Comment by october262** [comment]
try using the cookies.file

**Comment by sebma** [comment]
@october262 Same behavior : 
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', '-u', 'PRIVATE', '--cookies', 'cookies.txt', 'https://youtu.be/nQlTUSn_Iro']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.02.10
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-58-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
[youtube] nQlTUSn_Iro: Downloading webpage
ERROR: Private video
Sign in if you've been granted access to this video
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1630, in _real_extract
    raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: Private video
Sign in if you've been granted access to this video

$ echo $?
1
```

**Comment by sebma** [comment]
#26196

**Comment by sebma** [comment]
@october262 I've just discoverd the `--print-traffic` option to show more information and here what I get : 
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '--verbose', '--username', 'PRIVATE', '--cookies', 'cookies.txt', '--print-traffic', 'https://youtu.be/pU3T64LBPPY']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.14
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-60-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Downloading login page
send: b'GET /ServiceLogin HTTP/1.1\r\nHost: accounts.google.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: text/html; charset=utf-8
header: X-Frame-Options: DENY
header: x-auto-login: realm=com.google&args=continue%3Dhttps%253A%252F%252Faccounts.google.com%252FManageAccount%253Fnc%253D1
header: Cache-Control: no-cache, no-store, max-age=0, must-revalidate
header: Pragma: no-cache
header: Expires: Mon, 01 Jan 1990 00:00:00 GMT
header: Date: Tue, 16 Mar 2021 11:51:31 GMT
header: Content-Encoding: gzip
header: Strict-Transport-Security: max-age=31536000; includeSubDomains
header: Content-Security-Policy: script-src 'report-sample' 'nonce-X4h+x+JqPfHNLy+nPoXKIA' 'unsafe-inline' 'unsafe-eval';object-src 'none';base-uri 'self';report-uri /cspreport
header: X-Content-Type-Options: nosniff
header: X-XSS-Protection: 1; mode=block
header: Server: GSE
header: Set-Cookie: __Host-GAPS=1:W1EApeBawbTh_KRJeAiHkpHN7fPopQ:Rj5L5o4NHUSguM6K;Path=/;Expires=Thu, 16-Mar-2023 11:51:31 GMT;Secure;HttpOnly;Priority=HIGH
header: Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
header: Connection: close
header: Transfer-Encoding: chunked
[youtube] Looking up account info
send: b'POST /_/signin/sl/lookup HTTP/1.1\r\nContent-Length: 1057\r\nHost: accounts.google.com\r\nCookie: __Host-GAPS=1:W1EApeBawbTh_KRJeAiHkpHN7fPopQ:Rj5L5o4NHUSguM6K\r\nContent-Type: application/x-www-form-urlencoded;charset=utf-8\r\nGoogle-Accounts-Xsrf: 1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
send: b'__msgId__=%27%2B_.L%28a%29%2B%27&pstMsg=1&checkConnection=youtube&checkedDomains=youtube&ct=%27%2B_.L%28a%29%2B%27&%27%2B_.L%28a%29%2B%27=%27%2B_.L%28b%29%2B%27&hl=en&deviceinfo=%5Bnull%2Cnull%2Cnull%2C%5B%5D%2Cnull%2C%22US%22%2Cnull%2Cnull%2C%5B%5D%2C%22GlifWebSignIn%22%2Cnull%2C%5Bnull%2Cnull%2C%5B%5D%5D%5D&f.req=%5B%22seb02christ%40gmail.com%22%2C+null%2C+%5B%5D%2C+null%2C+%22US%22%2C+null%2C+null%2C+2%2C+false%2C+true%2C+%5Bnull%2C+null%2C+%5B2%2C+1%2C+null%2C+1%2C+%22https%3A%2F%2Faccounts.google.com%2FServiceLogin%3Fpassive%3Dtrue%26continue%3Dhttps%253A%252F%252Fwww.youtube.com%252Fsignin%253Fnext%253D%25252F%2526action_handle_signin%253Dtrue%2526hl%253Den%2526app%253Ddesktop%2526feature%253Dsign_in_button%26hl%3Den%26service%3Dyoutube%26uilel%3D3%26requestPath%3D%252FServiceLogin%26Page%3DPasswordSeparationSignIn%22%2C+null%2C+%5B%5D%2C+4%5D%2C+1%2C+%5Bnull%2C+null%2C+%5B%5D%5D%2C+null%2C+null%2C+null%2C+true%5D%2C+%22seb02christ%40gmail.com%22%5D&flowName=GlifWebSignIn&flowEntry=ServiceLogin&bgRequest=%5B%22identifier%22%2C%22%22%5D'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Cache-Control: no-cache, no-store, max-age=0, must-revalidate
header: Pragma: no-cache
header: Expires: Mon, 01 Jan 1990 00:00:00 GMT
header: Date: Tue, 16 Mar 2021 11:51:31 GMT
header: Content-Type: text/html; charset=utf-8
header: Content-Encoding: gzip
header: X-Content-Type-Options: nosniff
header: X-XSS-Protection: 1; mode=block
header: Server: GSE
header: Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
header: Connection: close
header: Transfer-Encoding: chunked
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
[youtube] pU3T64LBPPY: Downloading webpage
send: b'GET /watch?v=pU3T64LBPPY&bpctr=9999999999 HTTP/1.1\r\nHost: www.youtube.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: text/html; charset=utf-8
header: X-Content-Type-Options: nosniff
header: Cache-Control: no-cache, no-store, max-age=0, must-revalidate
header: Pragma: no-cache
header: Expires: Mon, 01 Jan 1990 00:00:00 GMT
header: Date: Tue, 16 Mar 2021 11:51:31 GMT
header: X-Frame-Options: SAMEORIGIN
header: Strict-Transport-Security: max-age=31536000
header: P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
header: Content-Encoding: gzip
header: Server: ESF
header: X-XSS-Protection: 0
header: Set-Cookie: GPS=1; Domain=.youtube.com; Expires=Tue, 16-Mar-2021 12:21:31 GMT; Path=/; Secure; HttpOnly
header: Set-Cookie: YSC=FTfkiZOaTaE; Domain=.youtube.com; Path=/; Secure; HttpOnly; SameSite=none
header: Set-Cookie: VISITOR_INFO1_LIVE=zYKH58wEQ_A; Domain=.youtube.com; Expires=Sun, 12-Sep-2021 11:51:31 GMT; Path=/; Secure; HttpOnly; SameSite=none
header: Set-Cookie: CONSENT=PENDING+459; expires=Fri, 01-Jan-2038 00:00:00 GMT; path=/; domain=.youtube.com
header: Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
header: Connection: close
header: Transfer-Encoding: chunked
ERROR: Private video
Sign in if you've been granted access to this video
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1658, in _real_extract
    raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: Private video
Sign in if you've been granted access to this video
```

I see 4 `header: Set-Cookie: ` lines in this output but I have 5 cookies lines in the generated `cookies.txt` : 
4 for the `.youtube.com` domain and 1 for `accounts.google.com`

There's also this line : 
`header: P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."`
Google says according to this [link](http://support.google.com/accounts/answer/151657?hl=en) that : 
> Some browsers require third party cookies to use the P3P protocol 

Does `youtube-dl` support the P3P protocol ?

Does `youtube-dl` accept 3rd party cookies ?

**Comment by robin92** [comment]
Any update?

**Comment by DDvO** [comment]
As mentioned above, a workaround is log in to YouTube on a browser, copy (e.g. using a browser extension) the cookies stored for the `youtube.com` domain to a text file and pass the resulting file to `youtube-dl` via the `--cookies` option.

Since many users have this problem, see also #26196, I wonder why `youtube-dl` does not give this hint upon 
```
ERROR: Private video
```
or at least upon the more specific
```
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
```
