### ISSUE TITLE
Cannot download spotify podcast episodes. open.spotify.com is an unsupported URL.

### ISSUE THREAD

**Issue by Subash-Chandra** [ytdl-org/youtube-dl#28143]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.02.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
X:\youtubedl>youtube-dl https://open.spotify.com/playlist/2puj7vyduPpBRNtfmyakAH --verbose
[debug] System config: []
[debug] User config: ['--output', 'X:\\youtubedl\\Downloads\\%(id)s.%(ext)s', '--no-overwrites', '--geo-bypass', '--format', 'bestvideo+bestaudio', '--merge-output-format', 'mp4', '--prefer-ffmpeg', '--ffmpeg-location', 'F:\\Workspace\\ffmpeg\\bin\\ffmpeg.exe']
[debug] Custom config: []
[debug] Command-line args: ['https://open.spotify.com/playlist/2puj7vyduPpBRNtfmyakAH', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.02.10
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.3.1-2020-09-21-full_build-www.gyan.dev, ffprobe 4.3.1-2020-09-21-full_build-www.gyan.dev
[debug] Proxy map: {}
[generic] 2puj7vyduPpBRNtfmyakAH: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2puj7vyduPpBRNtfmyakAH: Downloading webpage
[generic] 2puj7vyduPpBRNtfmyakAH: Extracting information
ERROR: Unsupported URL: https://open.spotify.com/playlist/2puj7vyduPpBRNtfmyakAH
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym44\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym44\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym44\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym44\build\youtube_dl\extractor\generic.py", line 3490, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://open.spotify.com/playlist/2puj7vyduPpBRNtfmyakAH

```

## Description

I checked the issues, and 15 days ago, there was a commit which added the ability to download Spotify podcast episodes as video. I am however, unable to do so at the moment. I am trying to download the Joe Rogan podcast episode 1609, and am unable to download it. My youtube DL version is updated, and I am able to download other stuff. It's just this spotify link that is not supported for some reason. Any help?

**Comment by october262** [comment]
did you try using the user name & password option with youtube-dl ??

**Comment by ogrim** [comment]
I'm pretty sure you have the wrong url - this works for me to download a single episode:

`youtube-dl -F https://open.spotify.com/episode/3EukYb1XzWD2G19WS5gAHe?si=mnHBUYuSQoS3eLhO3hl1Mg`
