### ISSUE TITLE
EmbedThumbnailPPError caused by "AtomicParsley error: unsupported MPEG-4 file brand found 'dash"  in youtube-dl-2021-02-10

### ISSUE THREAD

**Issue by silverhikari** [ytdl-org/youtube-dl#28165]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.02.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--embed-thumbnail', '-o', '%(title)s-%(uploader)s.%(ext)s', '-x', '-f', 'bestaudio[ext=m4a]/bestaudio[ext=opus]', '--audio-quality', '0', 'https://www.youtube.com/watch?v=vQVHlfgwYv8', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.02.10
[debug] Python version 3.8.6 (CPython) - Linux-5.8.0-26-lowlatency-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] vQVHlfgwYv8: Downloading webpage
[youtube] vQVHlfgwYv8: Downloading thumbnail ...
[youtube] vQVHlfgwYv8: Writing thumbnail to: Kegare Naki Yume - Asriel-AlonE illuioN.webp
[debug] Invoking downloader on 'https://r4---sn-8xgp1vo-ab5l.googlevideo.com/videoplayback?expire=1613359671&ei=15UpYKHYFeHkgwOMurvIDA&ip=2600%3A1002%3Ab12b%3Ac0ba%3A60ef%3Ab5e7%3A6550%3Abeb3&id=o-AGgsPlK6Eqlao9htxeMOp4xP-p7uuALyg12XAP3wt5DJ&itag=140&source=youtube&requiressl=yes&mh=Mz&mm=31%2C29&mn=sn-8xgp1vo-ab5l%2Csn-p5qlsnrl&ms=au%2Crdu&mv=m&mvi=4&pl=44&initcwndbps=427500&vprv=1&mime=audio%2Fmp4&ns=s_Plxu95rd6RXm1Hp6lK2qQF&gir=yes&clen=4830716&dur=304.111&lmt=1471545385593192&mt=1613337636&fvip=4&keepalive=yes&c=WEB&n=rukBTkDhsa5lLT4fDm&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgDo8aUJr-bDVVM-BKW79IApxhErvDIx24YGFMZypQP28CIFsti73JLBlJR6F4LeP0vkjFAEBLJGvw2lKKrfhxRBJg&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAN5r-lNRCFvmyc8eqhsM10of2oYHrC8moiAnnzHO3IjRAiANYc1veWVFK1G46MW4gVWVOs08luqT0QpEg0UBlp_OSw%3D%3D'
[download] Destination: Kegare Naki Yume - Asriel-AlonE illuioN.m4a
[download] 100% of 4.61MiB in 00:03
[debug] ffmpeg command line: ffprobe -show_streams 'file:Kegare Naki Yume - Asriel-AlonE illuioN.m4a'
[ffmpeg] Post-process file Kegare Naki Yume - Asriel-AlonE illuioN.m4a exists, skipping
[ffmpeg] Converting thumbnail "Kegare Naki Yume - Asriel-AlonE illuioN.webp" to JPEG
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Kegare Naki Yume - Asriel-AlonE illuioN.webp' -bsf:v mjpeg2jpeg 'file:Kegare Naki Yume - Asriel-AlonE illuioN.jpg'
[atomicparsley] Adding thumbnail to "Kegare Naki Yume - Asriel-AlonE illuioN.m4a"
[debug] AtomicParsley command line: AtomicParsley 'Kegare Naki Yume - Asriel-AlonE illuioN.m4a' --artwork 'Kegare Naki Yume - Asriel-AlonE illuioN.jpg' -o 'Kegare Naki Yume - Asriel-AlonE illuioN.temp.m4a'
ERROR: 
Traceback (most recent call last):
  File "/home/silver/.local/pipx/venvs/youtube-dl/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2102, in post_process
    files_to_delete, info = pp.run(info)
  File "/home/silver/.local/pipx/venvs/youtube-dl/lib/python3.8/site-packages/youtube_dl/postprocessor/embedthumbnail.py", line 112, in run
    raise EmbedThumbnailPPError(msg)
youtube_dl.postprocessor.embedthumbnail.EmbedThumbnailPPError
```

## Description

when trying to download youtube video with thumbnail, i can not download it with the thumbnail in the newer youtube-dl, it worked with the older youtube-dl.(i am running youtube-dl using pipx incase that is of any help)

EDIT:

the issue seems to be this "AtomicParsley error: unsupported MPEG-4 file brand found 'dash'"

**Comment by silverhikari** [comment]
after trying out different versions of youtube-dl it seems the problem happens after version 2021.02.04.1 as 2021.02.04.1 can still embed images

**Comment by JeffreyShran** [comment]
I think that I have the same issue on `2021.06.06` running against mixcloud - should I raise a new issue or track it here?

Ran: 

`youtube-dl -v --add-metadata --embed-thumbnail https://www.mixcloud.com/Dizzyuk/dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294/`

Error:

```
[atomicparsley] Adding thumbnail to "DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94-Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294.m4a"
[debug] AtomicParsley command line: AtomicParsley 'DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94-Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294.m4a' --artwork 'DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94-Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294.jpg' -o 'DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94-Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294.temp.m4a'
ERROR:
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2115, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/embedthumbnail.py", line 116, in run
    raise EmbedThumbnailPPError(msg)
youtube_dl.postprocessor.embedthumbnail.EmbedThumbnailPPError
```

**Comment by kikuyan** [comment]
Not a same problem.

I manually ran AtomicParsley command line in the debug log and got this:
`image file is not jpg/png and cannot be embedded.`

AtomicParsley doesn't seem to recognize this file. Though file and identify commands say it's JPEG.
I don't know how to solve this. Maybe try this fork: https://github.com/wez/atomicparsley
