### ISSUE TITLE
Batch processing stops after error

### ISSUE THREAD

**Issue by myself248** [ytdl-org/youtube-dl#28161]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.02.10**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: [u'--no-mark-watched', u'--yes-playlist', u'--restrict-filenames', u'--write-description', u'--write-info-json', u'--write-annotations', u'--write-thumbnail', u'--write-sub', u'--all-subs', u'--embed-thumbnail', u'--min-sleep-interval', u'20', u'--max-sleep-interval', u'40', u'--download-archive', u'archive.txt']
[debug] Custom config: []
[debug] Command-line args: [u'--batch-file', u'20201006.playlist', u'-v']

...

[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.02.10
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-135-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}

...
[download] Destination: I_Built_an_Unethical_Zoo_Where_Nobody_Is_Safe_-_Planet_Zoo-19JYOVPmwDM.f251.webm
[download] 100% of 22.02MiB in 00:09
[ffmpeg] Merging formats into "I_Built_an_Unethical_Zoo_Where_Nobody_Is_Safe_-_Planet_Zoo-19JYOVPmwDM.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:I_Built_an_Unethical_Zoo_Where_Nobody_Is_Safe_-_Planet_Zoo-19JYOVPmwDM.f303.webm' -i 'file:I_Built_an_Unethical_Zoo_Where_Nobody_Is_Safe_-_Planet_Zoo-19JYOVPmwDM.f251.webm' -c copy -map '0:v:0' -map '1:a:0' 'file:I_Built_an_Unethical_Zoo_Where_Nobody_Is_Safe_-_Planet_Zoo-19JYOVPmwDM.temp.webm'
Deleting original file I_Built_an_Unethical_Zoo_Where_Nobody_Is_Safe_-_Planet_Zoo-19JYOVPmwDM.f303.webm (pass -k to keep)
Deleting original file I_Built_an_Unethical_Zoo_Where_Nobody_Is_Safe_-_Planet_Zoo-19JYOVPmwDM.f251.webm (pass -k to keep)
[ffmpeg] Converting thumbnail "I_Built_an_Unethical_Zoo_Where_Nobody_Is_Safe_-_Planet_Zoo-19JYOVPmwDM.webp" to JPEG
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:I_Built_an_Unethical_Zoo_Where_Nobody_Is_Safe_-_Planet_Zoo-19JYOVPmwDM.webp' '-bsf:v' mjpeg2jpeg 'file:I_Built_an_Unethical_Zoo_Where_Nobody_Is_Safe_-_Planet_Zoo-19JYOVPmwDM.jpg'
ERROR: Only mp3 and m4a/mp4 are supported for thumbnail embedding for now.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2102, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/embedthumbnail.py", line 124, in run
    raise EmbedThumbnailPPError('Only mp3 and m4a/mp4 are supported for thumbnail embedding for now.')
EmbedThumbnailPPError: Only mp3 and m4a/mp4 are supported for thumbnail embedding for now.
```

## Description

I have a file containing many URLs, which I'm passing with --batch-file myplaylist 

I have --embed-thumbnails specified in my user config

Everything works as expected, until a video is encountered which both has a thumbnail and is in a format which doesn't support thumbnail embedding. This results in the error pasted above, and rather than continuing to the next line in the batchfile, it simply stops. All subsequent videos are not downloaded.

I could work around this by using my shell to invoke youtube-dl once per line in the file, but that defeats the purpose of --batch-file and the sleep intervals. 

I think it would be reasonable if this error was nonfatal, so thumbnails are embedded where they can be, but if they can't be, just keep going. 

(Also thank you tremendously for this awesome tool!)

**Comment by dstftw** [comment]
`-i`.
