### ISSUE TITLE
Download Problem ZDF Mediathek

### ISSUE THREAD

**Issue by andreas-muc** [ytdl-org/youtube-dl#28199]
root@raspberrypi:/opt/tvgrabber# youtube-dl --verbose https://www.zdf.de/comedy/zdf-magazin-royale/zdf-magazin-royale-vom-19-februar-2021-100.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.zdf.de/comedy/zdf-magazin-royale/zdf-magazin-royale-vom-19-februar-2021-100.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.02.10
[debug] Python version 2.7.13 (CPython) - Linux-4.14.79-v7+-armv7l-with-debian-9.6
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 53.69.0.84 (DE) as X-Forwarded-For.
[ZDF] zdf-magazin-royale-vom-19-februar-2021-100: Downloading webpage
[ZDF] zdf-magazin-royale-vom-19-februar-2021-100: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError(u'formitaeten',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/zdf.py", line 236, in _real_extract
    return self._extract_mobile(video_id)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/zdf.py", line 197, in _extract_mobile
    for f in document['formitaeten']:
KeyError: u'formitaeten'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 545, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'formitaeten',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by retoter** [comment]
Similar here:

[reto@macbook]$ youtube-dl --version
2021.03.03
[reto@macbook]$ youtube-dl --verbose https://www.zdf.de/comedy/zdf-magazin-royale/zdf-magazin-royale-vom-26-maerz-2021-100.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.zdf.de/comedy/zdf-magazin-royale/zdf-magazin-royale-vom-26-maerz-2021-100.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Python version 3.9.2 (CPython) - macOS-11.2.2-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 53.2.55.121 (DE) as X-Forwarded-For.
[ZDF] zdf-magazin-royale-vom-26-maerz-2021-100: Downloading webpage
[ZDF] zdf-magazin-royale-vom-26-maerz-2021-100: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('basename')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/extractor/zdf.py", line 294, in _real_extract
    return self._extract_mobile(video_id)
  File "/usr/local/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/extractor/zdf.py", line 251, in _extract_mobile
    content_id = document['basename']
KeyError: 'basename'
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/extractor/zdf.py", line 294, in _real_extract
    return self._extract_mobile(video_id)
  File "/usr/local/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/extractor/zdf.py", line 251, in _extract_mobile
    content_id = document['basename']
KeyError: 'basename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 545, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('basename')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
