### ISSUE TITLE
3Sat error

### ISSUE THREAD

**Issue by fahrer17** [ytdl-org/youtube-dl#28198]
Downloading a video from 3Sat Mediathek doesn't work (anymore), tested with Manjaro 20.2.1 Nibia.

```
[rico@H67A-MJRO Videos]$ youtube-dl --version
2021.02.04.1
```

Error message:
```
[rico@H67A-MJRO Videos]$ youtube-dl -v https://www.3sat.de/dokumentation/natur/der-rhein-von-oben-1-alpenrhein-100.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.3sat.de/dokumentation/natur/der-rhein-von-oben-1-alpenrhein-100.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.02.04.1
[debug] Python version 3.9.1 (CPython) - Linux-5.10.15-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] der-rhein-von-oben-1-alpenrhein-100: Requesting header
WARNING: Falling back on generic information extractor.
[generic] der-rhein-von-oben-1-alpenrhein-100: Downloading webpage
[generic] der-rhein-von-oben-1-alpenrhein-100: Extracting information
WARNING: [generic] der-rhein-von-oben-1-alpenrhein-100: Failed to parse JSON Expecting ',' delimiter: line 23 column 26 (char 594)
ERROR: Unsupported URL: https://www.3sat.de/dokumentation/natur/der-rhein-von-oben-1-alpenrhein-100.html
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/generic.py", line 3490, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.3sat.de/dokumentation/natur/der-rhein-von-oben-1-alpenrhein-100.html

```
Arte-Mediathek e.g. is fine:
```
rico@H67A-MJRO Videos]$ youtube-dl https://www.arte.tv/de/videos/044339-002-A/der-rhein-von-oben/
[ArteTV] 044339-002-A: Downloading JSON metadata
[ArteTV] 044339-002-A: Downloading m3u8 information
[ArteTV] 044339-002-A: Downloading m3u8 information
[download] Destination: Der Rhein von oben-044339-002-A.mp4
[download]  14.5% of 716.60MiB at 19.07MiB/s ETA 00:32^C
ERROR: Interrupted by user
```

**Comment by october262** [comment]
for this link - https://www.3sat.de/dokumentation/natur/der-rhein-von-oben-1-alpenrhein-100.html
just search for the webm video file via the debug menu (F12)
