### ISSUE TITLE
[youtube] ERROR: Conversion failed!

### ISSUE THREAD

**Issue by requiredregistration** [ytdl-org/youtube-dl#28208]
youtube-dl https://www.youtube.com/watch?v=mqAYRgLotU8 - succeeded
youtube-dl -f302+251 https://www.youtube.com/watch?v=mqAYRgLotU8 - failed

```
[debug] Command-line args: ['-vf302+251', 'mqAYRgLotU8']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.02.10
[debug] Python version 3.9.1 (CPython) - Linux-5.11.arch2-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[youtube] mqAYRgLotU8: Downloading webpage
[youtube] mqAYRgLotU8: Refetching age-gated info webpage
[youtube] mqAYRgLotU8: Downloading MPD manifest

[download] C64 - The Visible Solar System-mqAYRgLotU8.f302.webm has already been downloaded
[download] 100% of 7.06MiB
[download] C64 - The Visible Solar System-mqAYRgLotU8.f251.webm has already been downloaded
[download] 100% of 5.69MiB

[ffmpeg] Merging formats into "C64 - The Visible Solar System-mqAYRgLotU8.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:C64 - The Visible Solar System-mqAYRgLotU8.f302.webm' -i 'file:C64 - The Visible Solar System-mqAYRgLotU8.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:C64 - The Visible Solar System-mqAYRgLotU8.temp.webm'
ERROR: Conversion failed!
Traceback (most recent call last):
  File "/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 2102, in post_process
    files_to_delete, info = pp.run(info)
  File "/scripts/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 523, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/scripts/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

**Comment by remitamine** [comment]
incomplete verbose log.

**Comment by requiredregistration** [comment]
incomplete? all the required information is there.

**Comment by requiredregistration** [comment]
does this make you happy?

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vf302+251', 'mqAYRgLotU8']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.02.10
[debug] Python version 3.9.1 (CPython) - Linux-5.11-arch2-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] mqAYRgLotU8: Downloading webpage
[youtube] mqAYRgLotU8: Refetching age-gated info webpage
[youtube] mqAYRgLotU8: Downloading MPD manifest
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1613777197/ei/zfQvYMvsNpbj1wLT2IOABw/ip/IPADDRESS/id/9aa0184602e8b54f/source/youtube/requiressl/yes/playback_host/r3---sn-1gi7znes.googlevideo.com/mh/yF/mm/31%2C26/mn/sn-1gi7znes%2Csn-hpa7kn7l/ms/au%2Conr/mv/m/mvi/3/pl/20/tx/9417362/txs/9417361%2C9417362%2C9430863/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1886250/vprv/1/mt/1613755246/fvip/3/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRAIgPQX93tod1RPd7iXJTxPO0iEx0ErH1uI4dnbwtHm4bBcCIB3_p1VVTDlCjGQw3m8jgfva2jqLepf9oGcaAT2NtwsX/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIhAOXFc4Ls4zewmwixjg4Xsvwp6UEH5AjPe1ngzcoAVrWtAiBLFpCb27BxT8DCKwqbgUMwslzPRK8Px8OICMNpWpA3LA%3D%3D'
[download] C64 - The Visible Solar System-mqAYRgLotU8.f302.webm has already been downloaded
[download] 100% of 7.06MiB
[debug] Invoking downloader on 'https://r3---sn-1gi7znes.googlevideo.com/videoplayback?expire=1613777197&ei=zfQvYMvsNpbj1wLT2IOABw&ip=IPADDRESS&id=o-AGnsE7rz2NyTf68O3beK79UXb-Czgba9zC52bJl1CqwZ&itag=251&source=youtube&requiressl=yes&mh=yF&mm=31%2C26&mn=sn-1gi7znes%2Csn-hpa7kn7l&ms=au%2Conr&mv=m&mvi=3&pl=20&initcwndbps=1886250&vprv=1&mime=audio%2Fwebm&ns=lHChR6G6SAiY26OiLncKG-0F&gir=yes&clen=5962938&otfp=1&dur=501.101&lmt=1563414384824939&mt=1613755246&fvip=3&keepalive=yes&c=WEB&n=w4dUlL3DtSkoJtAZ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIgKnnodOQ-cWuIbsphsQl8va6igT53E2rJWc3xN44YIM8CIQDl3qzN3qJSp7sIGtFDzV3JOoQk8hylFwjXu9lXLzFpcg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAO8_TE_VuO5sb0jU8VttCgiM-BGgVDYH7mx57H5Gxc82AiABijPmI3Xnqu2BVmeTLlbLG5HWH8WP1Y1urozhyEr3qQ%3D%3D'
[download] C64 - The Visible Solar System-mqAYRgLotU8.f251.webm has already been downloaded
[download] 100% of 5.69MiB
[ffmpeg] Merging formats into "C64 - The Visible Solar System-mqAYRgLotU8.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:C64 - The Visible Solar System-mqAYRgLotU8.f302.webm' -i 'file:C64 - The Visible Solar System-mqAYRgLotU8.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:C64 - The Visible Solar System-mqAYRgLotU8.temp.webm'
ERROR: Conversion failed!
Traceback (most recent call last):
  File "/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 2102, in post_process
    files_to_delete, info = pp.run(info)
  File "/scripts/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 523, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/scripts/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

**Comment by remitamine** [comment]
is it hard to selecting the proper issue template and fill all the details needed, the full verbose log is important to make sure that there no options that interfere in the process(arguments can be passed to ffmpeg in the user config and cause conversion failure).

anyway, it's most likely a problem with ffmpeg(youtube-dl does not modify the files served by Youtube).

this is the error reported by ffmpeg.

> [webm @ 0x559ca4067c40] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 5350 >= 5333
av_interleaved_write_frame(): Invalid argument
