### ISSUE TITLE
running in termux

### ISSUE THREAD

**Issue by Pranay0302** [ytdl-org/youtube-dl#28216]

**Comment by Pranay0302** [comment]
```
$ youtube-dl --help                             Traceback (most recent call last):                File "/data/data/com.termux/files/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main                                                   return _run_code(code, main_globals, None,    File "/data/data/com.termux/files/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)                       File "/data/data/com.termux/files/usr/bin/youtube-dl/_main_.py", line 16, in <module>         File "<frozen zipimport>", line 259, in load_module
  File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/_init_.py", line 15, in <module>                                              File "<frozen zipimport>", line 259, in load_module
  File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/options.py", line 8, in <module>                                                File "<frozen zipimport>", line 259, in load_module
  File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/downloader/_init_.py", line 3, in <module>                                    File "<frozen zipimport>", line 259, in load_module                                             File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 10, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/utils.py", line 30, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.9/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: dlopen failed: cannot locate symbol "COMP_get_type" referenced by "/data/data/com.termux/files/usr/lib/python3.9/lib-dynload/_ssl.cpython-39.so"...
```

the following error is being recorded, any solution?

**Comment by dstftw** [comment]
Address this to termux support.
