### ISSUE TITLE
TMZ : An extractor error has occurred. (caused by KeyError('dataUrl',))

### ISSUE THREAD

**Issue by RingoTheDog** [ytdl-org/youtube-dl#28211]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.02.10**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.py -v "https://www.tmz.com/videos/2021-02-19-021921-floyd-mayweather-1043872/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.tmz.com/videos/2021-02-19-021921-floyd-mayweather-1043872/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.02.10
[debug] Python version 3.6.6 (CPython) - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-02-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Proxy map: {}
[Kaltura] 2021_02_19_021921_floyd_mayweather_1043872: Downloading video info JSON
ERROR: An extractor error has occurred. (caused by KeyError('dataUrl',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\kaltura.py", line 298, in _real_extract
    data_url = info['dataUrl']
KeyError: 'dataUrl'
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\kaltura.py", line 298, in _real_extract
    data_url = info['dataUrl']
KeyError: 'dataUrl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 545, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('dataUrl',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

URL: https://www.tmz.com/videos/2021-02-19-021921-floyd-mayweather-1043872/

I see there is an open TMZ issue opened here: https://github.com/ytdl-org/youtube-dl/issues/24603
...but I believe this is a different error (apologies if this is a repost)

thanks
Ringo

**Comment by RingoTheDog** [comment]
Actually as I go over the error again...I think this might be the same as the first example in #24603
