### ISSUE TITLE
ERROR: Unable to extract title

### ISSUE THREAD

**Issue by Elixiry** [ytdl-org/youtube-dl#28237]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.02.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
D:\Programs\youtube-dl\cmd>CMD /D /T:06 /K D:\Programs\youtube-dl\cmd\youtube-dl.exe --ignore-config --verbose --output D:\tmp "https://rt.pornhub.com/view_video.php?viewkey=ph5c68c732ae7de"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '--verbose', '--output', 'D:\\tmp', 'https://rt.pornhub.com/view_video.php?viewkey=ph5c68c732ae7de']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2021.02.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg n4.2.2-1-gece596698c-g7b0c22768e
[debug] Proxy map: {}
[PornHub] ph5c68c732ae7de: Downloading pc webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\extractor\pornhub.py", line 284, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\extractor\common.py", line 1019, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\extractor\common.py", line 1010, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

ERROR: Unable to extract title. This error appears frequently.

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by Elixiry** [comment]
These are geographic restrictions
