### ISSUE TITLE
AOL videos get 404 when trying to download video data

### ISSUE THREAD

**Issue by jillh510** [ytdl-org/youtube-dl#2823]
python -m youtube_dl --no-playlist -v -f mp4 http://on.aol.com/video/nikes-struggle-to-balance-cost-and-worker-safety-518204577
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--no-playlist', '-v', '-f', 'mp4', 'http://on.aol.com/video/nikes-struggle-to-balance-cost-and-worker-safety-518204577']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.04.21.6
[debug] Python version 2.7.5 - Darwin-13.1.0-x86_64-i386-64bit
[debug] Proxy map: {}
[5min] 518204577: Downloading embed page
[5min] 518204577: Downloading JSON metadata
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/Users/jill/june/.virtualenv/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1007, in process_info
    success = dl(filename, info_dict)
  File "/Users/jill/june/.virtualenv/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 983, in dl
    return fd.download(name, info)
  File "/Users/jill/june/.virtualenv/lib/python2.7/site-packages/youtube_dl/downloader/common.py", line 291, in download
    return self.real_download(filename, info_dict)
  File "/Users/jill/june/.virtualenv/lib/python2.7/site-packages/youtube_dl/downloader/http.py", line 54, in real_download
    data = self.ydl.urlopen(request)
  File "/Users/jill/june/.virtualenv/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

**Comment by remitamine** [comment]
it's working using the latest version:
```
python2 __main__.py http://on.aol.com/video/nikes-struggle-to-balance-cost-and-worker-safety-518204577
[5min] 518204577: Downloading embed page
[5min] 518204577: Downloading JSON metadata
[5min] 518204577: Downloading m3u8 information
[download] Destination: Nike's Struggle to Balance Cost and Worker Safety-518204577.mp4
[#af89c8 32MiB/32MiB(99%) CN:1 DL:182KiB]                                      
10/16 17:13:16 [NOTICE] Download complete: /home/amine/youtube-dl/youtube_dl/Nike's Struggle to Balance Cost and Worker Safety-518204577.mp4.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
af89c8|OK  |   215KiB/s|/home/amine/youtube-dl/youtube_dl/Nike's Struggle to Balance Cost and Worker Safety-518204577.mp4.part

Status Legend:
(OK):download completed.
[aria2c] Downloaded 34265769 bytes
[download] 100% of 32.68MiB
```

**Comment by brunnoattorre** [comment]
I'm getting a different error now:

youtube-dl https://www.aol.com/article/2016/04/22/a-daring-eye-makeup-look-for-every-eye-color/21331368/?data-bh-cid=93283
[on.aol.com] 21331368: Downloading JSON metadata
ERROR: on.aol.com said: Not found - id

**Comment by mpenkov** [comment]
@brunnoattorre Confirmed to still be broken with most recent version.

```$ youtube-dl https://www.aol.com/article/2016/04/22/a-daring-eye-makeup-look-for-every-eye-color/21331368/?data-bh-cid=93283 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.aol.com/article/2016/04/22/a-daring-eye-makeup-look-for-every-eye-color/21331368/?data-bh-cid=93283', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2018.09.18
[debug] Git HEAD: 4ac73fc17
[debug] Python version 3.6.5 (CPython) - Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[on.aol.com] 21331368: Downloading JSON metadata
ERROR: on.aol.com said: Not found - id
Traceback (most recent call last):
  File "/home/misha/git/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/misha/git/youtube-dl/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/home/misha/git/youtube-dl/youtube_dl/extractor/aol.py", line 72, in _real_extract
    raise ExtractorError('%s said: %s' % (self.IE_NAME, response['statusText']), expected=True)
youtube_dl.utils.ExtractorError: on.aol.com said: Not found - id
```
