### ISSUE TITLE
facebook video no longer working

### ISSUE THREAD

**Issue by wankio** [ytdl-org/youtube-dl#28255]
## Verbose log
 

```
C:\Users\GEN32UC>youtube-dl https://www.facebook.com/explosm/videos/376741973485522 --verbose
[debug] System config: []
[debug] User config: ['-o', 'I:/youtube-dl/%(extractor)s/%(title)s-%(uploader)s-%(channel_id)s-%(channel)s-%(id)s.%(ext)s', '-f', 'bestvideo[height<=?1080]+bestaudio/best', '--write-thumbnail', '--cookies', 'C:UsersGEN32UCAppDataRoamingyoutube-dlcookies.txt', '--write-sub', '--write-auto-sub', '--sub-lang', 'en-GB']
[debug] Custom config: []
[debug] Command-line args: ['https://www.facebook.com/explosm/videos/376741973485522', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.02.22
[debug] Python version 3.8.2 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-92966-gd52a1be4e3, ffprobe N-92966-gd52a1be4e3
[debug] Proxy map: {}
[facebook] 376741973485522: Downloading webpage
[facebook] 376741973485522: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\gen32uc\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\gen32uc\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\gen32uc\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\gen32uc\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\facebook.py", line 677, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "c:\users\gen32uc\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\facebook.py", line 591, in _extract_from_url
    raise ExtractorError('Cannot parse data')
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

 I'm trying to download facebook video but seem like it's not working anymore

https://www.facebook.com/explosm/videos/376741973485522

**Comment by remitamine** [comment]
[pass cookies to youtube-dl](https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl).
