### ISSUE TITLE
Site that don't work Anymore : https://www.cinematheque.fr/henri/

### ISSUE THREAD

**Issue by Tim2460** [ytdl-org/youtube-dl#28272]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.02.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
D:\>youtube-dl -v https://www.cinematheque.fr/henri/film/67927-blue-jeans-jacques-rozier-1957/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.cinematheque.fr/henri/film/67927-blue-jeans-jacques-rozier-1957/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.02.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2020-09-16-git-c79f07cc0c-full_build-www.gyan.dev, ffprobe 2020-09-16-git-c79f07cc0c-full_build-www.gyan.dev
[debug] Proxy map: {}
[generic] 67927-blue-jeans-jacques-rozier-1957: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 67927-blue-jeans-jacques-rozier-1957: Downloading webpage
[generic] 67927-blue-jeans-jacques-rozier-1957: Extracting information
ERROR: Unsupported URL: https://www.cinematheque.fr/henri/film/67927-blue-jeans-jacques-rozier-1957/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\extractor\generic.py", line 3506, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.cinematheque.fr/henri/film/67927-blue-jeans-jacques-rozier-1957/
```

## Description

I used to be able to youtube-dl fiebn from the FRENCH cinematheque site HENRI... But no more.
I see that Python is used ... i installed Visual Studio with Python support... it may be linked ?

Youtube-dling from youtube works fine

**Comment by gaumut** [comment]
I've got the same issue. It's not linked to your Visual Studio install.
The website use embedded Vimeo video. I don't why they are not detected by youtube-dl generic extractor. They must have changed something.

**Comment by gaumut** [comment]
You can still download the video using the --referer argument. To get the url on firefox do : right-click on the video, this frame -> show only this frame.
and then : youtube-dl "player.vimeo.com/..." --referer "cinematheque.fr/henri/..."

**Comment by diligiant** [comment]
@gaumut thank you!
