### ISSUE TITLE
Can't extract post URL for tntdrama.com

### ISSUE THREAD

**Issue by Pickle2503** [ytdl-org/youtube-dl#28301]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.02.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\dylan\Documents\youtube-dl>youtube-dl -v  --no-check-certificate --ap-mso Brighthouse --ap-username EMAIL --ap-password PASSWORD -F https://www.tntdrama.com/movies/avengers-infinity-war
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-check-certificate', '--ap-mso', 'Brighthouse', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-F', 'https://www.tntdrama.com/movies/avengers-infinity-war']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.02.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2020-11-04-git-cfdddec0c8-full_build-www.gyan.dev, ffprobe 2020-11-04-git-cfdddec0c8-full_build-www.gyan.dev
[debug] Proxy map: {}
[TBS] avengers-infinity-war: Downloading webpage
[TBS] 1f03d950a50db02e0e5b1b370d91df8751bcbf62: Downloading JSON metadata
[TBS] 1f03d950a50db02e0e5b1b370d91df8751bcbf62: Downloading Provider Redirect Page
[TBS] 1f03d950a50db02e0e5b1b370d91df8751bcbf62: Downloading Provider Login Page
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\extractor\tbs.py", line 59, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\extractor\turner.py", line 238, in _extract_ngtv_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\extractor\turner.py", line 41, in _add_akamai_spe_token
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\extractor\adobepass.py", line 1513, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\extractor\adobepass.py", line 1365, in post_form
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\extractor\common.py", line 1019, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6ovysl5t\build\youtube_dl\extractor\common.py", line 1010, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Youtube-dl can't extract post URL when trying to login to tntdrama.com . Also the --cookies function does not work either for this website for some reason.

**Comment by SerpentDrago** [comment]
I have the same issue

**Comment by SerpentDrago** [comment]
I actually solved my issue by changing from TWC-Spectrum to just Spectrum  as my --ap-mso

**Comment by dirkf** [comment]
The backtrace shows that the AP-MSO page where yt-dl wants to submit your credentials is somehow not as expected: either the provider-name has changed (as above) or the page served by the provider has changed.

Maybe `--print-traffic` would provide some more information.

Otherwise, this has to be debugged in-region and probably with the AP-MSO credentials.

But also, what happens if `--no-check-certificate` is omitted?

Regarding https://github.com/ytdl-org/youtube-dl/issues/28301#issuecomment-1774351599, actually `--ap-mso Spectrum` is only supported in _yt-dlp_ and not (yet) here.
