### ISSUE TITLE
VoxMedia (The Verge) Broken

### ISSUE THREAD

**Issue by Crystal-RainSlide** [ytdl-org/youtube-dl#28338]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -F --verbose https://www.theverge.com/2018/5/17/17344250/google-x-selfish-ledger-video-data-privacy
[debug] System config: []
[debug] User config: ['--proxy', '[a working proxy]/']
[debug] Custom config: []
[debug] Command-line args: ['-F', '--verbose', 'https://www.theverge.com/2018/5/17/17344250/google-x-selfish-ledger-video-data-privacy']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2021.03.03
[debug] Python version 3.4.4 (CPython) - Windows-10-[version code]
[debug] exe versions: ffmpeg 4.3.2-2021-02-27-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-27-full_build-www.gyan.dev
[debug] Proxy map: {'http': '[a working proxy]', 'https': '[a working proxy]'}
[VoxMedia] google-x-selfish-ledger-video-data-privacy: Downloading webpage
[VoxMediaVolume] b624f2415: Downloading webpage
ERROR: Unable to find provider video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\voxmedia.py", line 66, in _real_extract
youtube_dl.utils.ExtractorError: Unable to find provider video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

- The web page: https://www.theverge.com/2018/5/17/17344250/google-x-selfish-ledger-video-data-privacy
- The embed Vox Media Volume: https://volume.vox-cdn.com/embed/b624f2415
- The m3u8 file which should be found: https://volume-assets.voxmedia.com/production/7e3bd02a2c59cf3b5f5cd5f779a75eac/116881/playlist.m3u8
- The raise Error code: [youtube_dl/extractor/voxmedia.py#L66](https://github.com/ytdl-org/youtube-dl/blob/f68692b004f1c65f08a9a7d9c2ee4ab2ec255ea6/youtube_dl/extractor/voxmedia.py#L66)

From `view-source:https://volume.vox-cdn.com/embed/b624f2415`, I can find the target m3u8 link in:

``` HTML
<meta name="twitter:player:stream" content="https://volume-assets.voxmedia.com/production/7e3bd02a2c59cf3b5f5cd5f779a75eac/116881/playlist.m3u8" />
```

``` HTML
<script>
/* some props are omitted */
var setup = {
  "embed_assets":{
    "chorus":{
      "hls_url":"https://volume-assets.voxmedia.com/production/7e3bd02a2c59cf3b5f5cd5f779a75eac/116881/playlist.m3u8",
      "mp4_url":"https://volume-assets.voxmedia.com/production/7e3bd02a2c59cf3b5f5cd5f779a75eac/116881/video-764k.mp4"
    }
  }
}
// ...
</script>
```

I'm not familiar with many functions/methods used in the voxmedia.py, but I found:

1. From [line 29](https://github.com/ytdl-org/youtube-dl/blob/f68692b004f1c65f08a9a7d9c2ee4ab2ec255ea6/youtube_dl/extractor/voxmedia.py#L29) and [line 32](https://github.com/ytdl-org/youtube-dl/blob/f68692b004f1c65f08a9a7d9c2ee4ab2ec255ea6/youtube_dl/extractor/voxmedia.py#L32),
   it didn't try to find `hls_url` or `mp4_url` inside the `embed_assets` or `chorus` object,
   because it only tried to find it in `asset` or `params` object.
   AND **It can just try to find the url in the whole `setup` object.**
2. `<meta name="twitter:player:stream" content="hls_url">` is not supported yet, I think this m3u8 file url source may last longer than the js objects.

**Comment by Crystal-RainSlide** [comment]
My fix to this would be replacing line 29 to line 36 with:
``` Python
        formats = []
        hls_url = setup.get('hls_url')
        if hls_url:
            formats.extend(self._extract_m3u8_formats(
                hls_url, video_id, 'mp4', 'm3u8_native', m3u8_id='hls', fatal=False))
        mp4_url = setup.get('mp4_url')
```

But I can't do the `<meta name="twitter:player:stream" content="hls_url">`.
