### ISSUE TITLE
Youtube premium or member Videos Download Failed

### ISSUE THREAD

**Issue by williamsAu4a83** [ytdl-org/youtube-dl#28340]
## Checklist

- [V] I'm reporting a broken site support issue
- [V] I've verified that I'm running youtube-dl version **2021.03.03**
- [V] I've checked that all provided URLs are alive and playable in a browser
- [V] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [V] I've searched the bugtracker for similar bug reports including closed ones
- [V] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-g', u'--get-url', u'https://www.youtube.com/watch?v=gdGL2P3Wyp8']
Type account password and press [Return]: 
[debug] Encodings: locale None, fs None, out None, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Python version 2.7.12 (CPython) - Linux-4.1.35-armv8l-with-libc
[debug] exe versions: rtmpdump present
[debug] Proxy map: {}
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
ERROR: Join this channel to get access to members-only content like this video, and other exclusive perks.
Traceback (most recent call last):
  File "/usr/lib/python2.7/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python2.7/youtube_dl/extractor/youtube.py", line 1658, in _real_extract
    raise ExtractorError(reason, expected=True)
ExtractorError: Join this channel to get access to members-only content like this video, and other exclusive perks.
```

## Description

Is there a solution to this problem?

**Comment by dstftw** [comment]
Pass authenticated cookies.

**Comment by rugk** [comment]
Hmm… it is not planned to implement a workaround?
