### ISSUE TITLE
svtplay.se does not work with --geo-bypass

### ISSUE THREAD

**Issue by eevvoor** [ytdl-org/youtube-dl#28350]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v  --geo-bypass https://www.svtplay.se/luo-bao-bei
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--geo-bypass', u'https://www.svtplay.se/luo-bao-bei']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Python version 2.7.18 (CPython)
[debug] exe versions: ffmpeg 4.3.1-5, ffprobe 4.3.1-5, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] Using fake IP 78.75.29.183 (SE) as X-Forwarded-For.
[SVTSeries] luo-bao-bei: Downloading series page
[download] Downloading playlist: Luo Bao Bei
[SVTSeries] playlist Luo Bao Bei: Collected 9 video ids (downloading 9 of them)
[download] Downloading video 1 of 9
[debug] Using fake IP 78.72.1.255 (SE) as X-Forwarded-For.
[SVTPlay] KVkqvmX: Downloading JSON metadata
[SVTPlay] KVkqvmX: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
...
ERROR: This video is only available in Sweden
This video is available in Sweden.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/svt.py", line 225, in _real_extract
    return self._extract_by_video_id(svt_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/svt.py", line 208, in _extract_by_video_id
    info_dict = self._extract_video(data, video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/svt.py", line 52, in _extract_video
    countries=self._GEO_COUNTRIES)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 945, in raise_geo_restricted
    raise GeoRestrictedError(msg, countries=countries)
GeoRestrictedError: This video is only available in Sweden
```

## Description

Geo-bypass does not work for svtplay.se anymore. It did before.

**Comment by afe2c3** [comment]
They likely fixed it. Nothing ytdl can do about it.

**Comment by eevvoor** [comment]
> They likely fixed it. Nothing ytdl can do about it.

Does that mean that svtplay does block urls with only the x-foreward-from flag on purpose to exclude faked Swedish location?
