### ISSUE TITLE
TubiTv - ValueError: unknown url type: ''

### ISSUE THREAD

**Issue by leptoid** [ytdl-org/youtube-dl#28369]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl https://tubitv.com/movies/574451/underworld-blood-wars -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://tubitv.com/movies/574451/underworld-blood-wars', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.03.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-02-20-git-51a9f487ae-full_build-www.gyan.dev, ffprobe 2021-02-20-git-51a9f487ae-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] Using fake IP 6.86.131.92 (US) as X-Forwarded-For.
[TubiTv] 574451: Downloading JSON metadata
[TubiTv] 574451: Downloading m3u8 information
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\__init__.py", line 465, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\YoutubeDL.py", line 2056, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\YoutubeDL.py", line 799, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\tubitv.py", line 80, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\common.py", line 1636, in _extract_m3u8_formats
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\common.py", line 665, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\utils.py", line 2157, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: ''
```

## Description

WRITE DESCRIPTION HERE

**Comment by leptoid** [comment]
Issue self resolved.  If you run in to it, try manually naming the output file.  Silly... but whatever works at the time.

**Comment by dare2** [comment]
I'm getting this on certain Tubi links. What do you mean by "manually naming the file"?
