### ISSUE TITLE
Ffprobe problem

### ISSUE THREAD

**Issue by jefferson018200306** [ytdl-org/youtube-dl#28380]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://music.youtube.com/watch?v=1tkdmY7sdUc&feature=share', '-f', 'bestaudio', '-x', '--audio-format', 'flac', '--audio-quality', '0', '-o', '/storage/0040-18A0/testing from youtube-dl/%(artist)s - %(title)s.%(ext)s', '-v', '--no-cache-dir']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Lazy loading extractors enabled
[debug] Python version 3.8.0 (CPython) - Linux-3.10.65-gd1ee5ec-armv7l-with-libc
[debug] exe versions: libffmpeg.bin.so 4.2.1, libffprobe.bin.so 4.2.1
[debug] Proxy map: {}
ERROR: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/YoutubeDL.py", line 2102, in post_process
    files_to_delete, info = pp.run(info)
  File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 274, in run
    raise PostProcessingError('WARNING: unable to obtain file audio codec with ffprobe')
youtube_dl.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe


```

## Description

It just happened last night, I don't think this is just a bug or something. Because after trying multiple times, it will begin downloading without any problems... Please fix this problem ☺️ thank you 💕

**Comment by kikuyan** [comment]
> [debug] Lazy loading extractors enabled
> [debug] exe versions: libffmpeg.bin.so 4.2.1, libffprobe.bin.so 4.2.1

It seems that you are using youtube-dl in some special development environment, and since you cannot reproduce the problem, I don't think this report needs to be investigated.
