### ISSUE TITLE
FFMpeg error causes youtube-dl to fail merging video and audio

### ISSUE THREAD

**Issue by nipponese** [ytdl-org/youtube-dl#28410]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
➜  ~ youtube-dl -v https://www.youtube.com/watch\?v\=MD32m2o7Hcw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=MD32m2o7Hcw']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Git HEAD: 8b677c0dd
[debug] Python version 3.9.2 (CPython) - macOS-11.2.3-arm64-arm-64bit
[debug] exe versions: ffmpeg present, ffprobe present, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] MD32m2o7Hcw: Downloading webpage
[youtube] MD32m2o7Hcw: Downloading player 34a43f74
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r5---sn-n4v7knls.googlevideo.com/videoplayback?expire=1615510179&ei=Q2ZKYKCfK4P0kgbS5qPoDw&ip=2601%3A645%3A8800%3Aa0%3Ac1fb%3A8c72%3A3d3d%3A5fde&id=o-ABDqU1ME2Gu7TxHYW9T37JS8YdrnsHLXYQCrN3BaagSK&itag=136&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=youtube&requiressl=yes&mh=RB&mm=31%2C26&mn=sn-n4v7knls%2Csn-a5mlrn7s&ms=au%2Conr&mv=m&mvi=5&pl=34&initcwndbps=1797500&vprv=1&mime=video%2Fmp4&ns=vfckBKSwwACJs8SQFckAB0gF&gir=yes&clen=1182835135&dur=4090.586&lmt=1612249545732354&mt=1615488303&fvip=5&keepalive=yes&fexp=24001374%2C24007246&c=WEB&txp=5432434&n=SjHCC02AILnLTWccn&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgU7vvht8JpOu55qxiG7P7AhJSbTe9qkD-DguciY4BUTUCIEGgBJroEo2LFKQG6pGTbGDvFQX_qPy4M9THI7CHwBK-&sig=AOq0QJ8wRAIgSQZr3m4nL5O6tSsItkBl6DnZ1d_lvBvwOIyEd0_nro4CIAJ5W5M6BSBAknaK_xYfBN-4LR-bPzY8Gwfgln5Q7ShC'
[download] Destination: TRAPPIN IN ＰＡＲＡＤＩＳＥ  79-MD32m2o7Hcw.f136.mp4
[download] 100% of 1.10GiB in 01:18
[debug] Invoking downloader on 'https://r5---sn-n4v7knls.googlevideo.com/videoplayback?expire=1615510179&ei=Q2ZKYKCfK4P0kgbS5qPoDw&ip=2601%3A645%3A8800%3Aa0%3Ac1fb%3A8c72%3A3d3d%3A5fde&id=o-ABDqU1ME2Gu7TxHYW9T37JS8YdrnsHLXYQCrN3BaagSK&itag=251&source=youtube&requiressl=yes&mh=RB&mm=31%2C26&mn=sn-n4v7knls%2Csn-a5mlrn7s&ms=au%2Conr&mv=m&mvi=5&pl=34&initcwndbps=1797500&vprv=1&mime=audio%2Fwebm&ns=vfckBKSwwACJs8SQFckAB0gF&gir=yes&clen=69163957&dur=4090.601&lmt=1612230567090688&mt=1615488303&fvip=5&keepalive=yes&fexp=24001374%2C24007246&c=WEB&txp=5432434&n=SjHCC02AILnLTWccn&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgH9WpOCwJOypFc9lCkoJRZFlkEo8ET_2SxFY1AF0P_gcCIAbFB6xF9dJx7Oj6tEKSUMF722CAB1Q7_QpKeGN568qa&sig=AOq0QJ8wRQIgIf1Kjzf0aU24t-hf9LwVt7WmM0PFIl1i5mih8_7uAbYCIQCh_c3pxPrAWmcfKKx8NhFRWk94vhX2J8p79MotIu6ynA=='
[download] Destination: TRAPPIN IN ＰＡＲＡＤＩＳＥ  79-MD32m2o7Hcw.f251.webm
[download] 100% of 65.96MiB in 00:04
[ffmpeg] Merging formats into "TRAPPIN IN ＰＡＲＡＤＩＳＥ  79-MD32m2o7Hcw.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:TRAPPIN IN ＰＡＲＡＤＩＳＥ  79-MD32m2o7Hcw.f136.mp4' -i 'file:TRAPPIN IN ＰＡＲＡＤＩＳＥ  79-MD32m2o7Hcw.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:TRAPPIN IN ＰＡＲＡＤＩＳＥ  79-MD32m2o7Hcw.temp.mkv'
ERROR: 
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2102, in post_process
    files_to_delete, info = pp.run(info)
  File "/opt/homebrew/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 523, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/opt/homebrew/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError
```

## Description

Tried running youtube-dl with only -v option. Usually this downloads the video and audio and merges them, but it fails when FFMpeg tries to merge video and audio:
```
ERROR: 
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2102, in post_process
    files_to_delete, info = pp.run(info)
  File "/opt/homebrew/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 523, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/opt/homebrew/Cellar/youtube-dl/2021.3.3/libexec/lib/python3.9/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError
```

**Comment by slhck** [comment]
I am not an expert on `youtube-dl`, but for diagnosing the issue, it may help if you could provide the full command-line output of:

`ffmpeg -y -loglevel repeat+info -i 'file:TRAPPIN IN ＰＡＲＡＤＩＳＥ  79-MD32m2o7Hcw.f136.mp4' -i 'file:TRAPPIN IN ＰＡＲＡＤＩＳＥ  79-MD32m2o7Hcw.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:TRAPPIN IN ＰＡＲＡＤＩＳＥ  79-MD32m2o7Hcw.temp.mkv'`

That should show any errors from ffmpeg specifically.

**Comment by dstftw** [comment]
Most likely broken ffmpeg setup.

**Comment by slhck** [comment]
@dstftw Since the only message we get from `youtube-dl` is the name of the exception, it's hard to know what really went wrong. Such an error should include the entire stdout/stderr printed by ffmpeg in order to allow diagnosing the issue.
