### ISSUE TITLE
Options `-f [filesize]` and `--max-filesize` are both broken with Pinterest

### ISSUE THREAD

**Issue by mattiagiuffrida-st** [ytdl-org/youtube-dl#28426]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've checked that all provided URLs are alive and playable in a browser (kinda: I'm providing reproduction steps so the link is working, but it can't simply be opened on the browser as it's a `.m3u8` link)
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'[filesize<10M]', u'https://v.pinimg.com/videos/mc/hls/eb/87/05/eb870543b922a1915f2d7e39f3cadd12.m3u8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Python version 2.7.16 (CPython) - Darwin-20.3.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] eb870543b922a1915f2d7e39f3cadd12: Requesting header
[generic] eb870543b922a1915f2d7e39f3cadd12: Downloading m3u8 information
ERROR: requested format not available
Traceback (most recent call last):
  File "/Users/mattiagiuffrida/Library/Python/2.7/lib/python/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/mattiagiuffrida/Library/Python/2.7/lib/python/site-packages/youtube_dl/YoutubeDL.py", line 838, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Users/mattiagiuffrida/Library/Python/2.7/lib/python/site-packages/youtube_dl/YoutubeDL.py", line 872, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/Users/mattiagiuffrida/Library/Python/2.7/lib/python/site-packages/youtube_dl/YoutubeDL.py", line 1671, in process_video_result
    expected=True)
ExtractorError: requested format not available
```

## Description

I'm trying to download a video from Pinterest with multiple formats available, so I'm putting a constraint on the `filesize` to avoid downloading videos that are too big. However, when I do that, I get the error that you can see in the verbose log above: `ExtractorError: requested format not available`. I've been able to pinpoint the problem to the `filesize` format constraint because I did the following tests:

1. First, I checked for available formats, as you can see the `best` video is less than 4MB:
```
$ /usr/local/bin/youtube-dl -v -F https://v.pinimg.com/videos/mc/hls/eb/87/05/eb870543b922a1915f2d7e39f3cadd12.m3u8

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://v.pinimg.com/videos/mc/hls/eb/87/05/eb870543b922a1915f2d7e39f3cadd12.m3u8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Python version 2.7.16 (CPython) - Darwin-20.3.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] eb870543b922a1915f2d7e39f3cadd12: Requesting header
[generic] eb870543b922a1915f2d7e39f3cadd12: Downloading m3u8 information
[info] Available formats for eb870543b922a1915f2d7e39f3cadd12:
format code  extension  resolution note
642          mp4        240x424     642k , avc1.4d4015, 25.0fps, mp4a.40.5
1026         mp4        360x640    1026k , avc1.77.30, 25.0fps, mp4a.40.5
1186         mp4        480x852    1186k , avc1.77.30, 25.0fps, mp4a.40.5
1765         mp4        640x1136   1765k , avc1.4d401f, 25.0fps, mp4a.40.5
2867         mp4        720x1280   2867k , avc1.64001f, 25.0fps, mp4a.40.5 (best)
```

2. Then, I tried my command with a `filesize` limit of `10MB`, which failed:

```
$ youtube-dl -v -f "[filesize<10M]" https://v.pinimg.com/videos/mc/hls/eb/87/05/eb870543b922a1915f2d7e39f3cadd12.m3u8

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'[filesize<10M]', u'https://v.pinimg.com/videos/mc/hls/eb/87/05/eb870543b922a1915f2d7e39f3cadd12.m3u8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Python version 2.7.16 (CPython) - Darwin-20.3.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] eb870543b922a1915f2d7e39f3cadd12: Requesting header
[generic] eb870543b922a1915f2d7e39f3cadd12: Downloading m3u8 information
ERROR: requested format not available
Traceback (most recent call last):
  File "/Users/mattiagiuffrida/Library/Python/2.7/lib/python/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/mattiagiuffrida/Library/Python/2.7/lib/python/site-packages/youtube_dl/YoutubeDL.py", line 838, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Users/mattiagiuffrida/Library/Python/2.7/lib/python/site-packages/youtube_dl/YoutubeDL.py", line 872, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/Users/mattiagiuffrida/Library/Python/2.7/lib/python/site-packages/youtube_dl/YoutubeDL.py", line 1671, in process_video_result
    expected=True)
ExtractorError: requested format not available
```

3. I then tried removing the constraint on the `filesize`, which resulted in the video being correctly downloaded.

```
$ youtube-dl -v https://v.pinimg.com/videos/mc/hls/eb/87/05/eb870543b922a1915f2d7e39f3cadd12.m3u8

# Log here is really long, so I won't put it all, but it ends with a video of 3.45MB being successfully downloaded
[ffmpeg] Downloaded 3614800 bytes
[download] 100% of 3.45MiB in 00:00
```

4. I even tried the max-filesize option, but in this case I got the opposite issue: the option is simply ignored...

```
$ /usr/local/bin/youtube-dl -v --max-filesize 2m https://v.pinimg.com/videos/mc/hls/eb/87/05/eb870543b922a1915f2d7e39f3cadd12.m3u8

# Same really long log as step 3, ending in
[ffmpeg] Downloaded 3614800 bytes
[download] 100% of 3.45MiB in 00:00
# Which is surprising, since I limited the `max-filesize` to `2MB`
```

I'm unsure if I'm doing something wrong here, but the issue is easily reproducible and I'd really like some help to understand what's going wrong 😄 
Thanks!

**Comment by remitamine** [comment]
the file size is not known before finishing the download process for HLS formats.

**Comment by mattiagiuffrida-st** [comment]
Thanks for the prompt reply @remitamine!
Do you have any suggestion on how to overcome this limitation? Maybe a less elegant but at least working solution?

**Comment by remitamine** [comment]
passing webpage URL to youtube-dl, you should be able to access a direct mp4 URL that would work with `-max-filesize` option.
