### ISSUE TITLE
ExtractorError: Failed to parse XML

### ISSUE THREAD

**Issue by tampe125** [ytdl-org/youtube-dl#28424]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://live.top-ix.org/play/regio/od-001-cosifantutte

## Description

It seems that the extractor can't find the correct XML and parse it. Below you can find the output:
```
 youtube-dl https://live.top-ix.org/play/regio/od-001-cosifantutte --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://live.top-ix.org/play/regio/od-001-cosifantutte', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-136-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[generic] od-001-cosifantutte: Requesting header
WARNING: Falling back on generic information extractor.
[generic] od-001-cosifantutte: Downloading webpage
[generic] od-001-cosifantutte: Extracting information
[generic] smil:20210311-cosi_fan_tutte: Downloading SMIL file
ERROR: smil:20210311-cosi_fan_tutte: Failed to parse XML  (caused by ParseError(ExpatError('syntax error: line 1, column 0',),)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 854, in _parse_xml
    return compat_etree_fromstring(xml_string.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2562, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3541, in _real_extract
    entry_info_dict['formats'] = self._extract_smil_formats(video_url, video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1839, in _extract_smil_formats
    smil = self._download_smil(smil_url, video_id, fatal=fatal, transform_source=transform_source)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1859, in _download_smil
    'Unable to download SMIL file', fatal=fatal, transform_source=transform_source)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 847, in _download_xml
    expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 831, in _download_xml_handle
    fatal=fatal), urlh
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 858, in _parse_xml
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: smil:20210311-cosi_fan_tutte: Failed to parse XML  (caused by ParseError(ExpatError('syntax error: line 1, column 0',),)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by tampe125** [comment]
My fault, I passed the wrong URL. Should I keep this open to handle these kind of errors?
