### ISSUE TITLE
[Funimation] Fails on search for HTML metatags (youtube_dl.utils.RegexNotFoundError: Unable to extract al:web:url)

### ISSUE THREAD

**Issue by SuperSonicHub1** [ytdl-org/youtube-dl#28439]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.funimation.com/shows/cells-at-work-code-black/the-liver-alcohol-and-pride/?qid=undefined', '--no-check-certificate']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Python version 3.7.3 (CPython) - Linux-5.4.74-10576-gb6cc41974db3-x86_64-with-debian-10.8
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[Funimation] the-liver-alcohol-and-pride: Downloading webpage
WARNING: [Funimation] the-liver-alcohol-and-pride: Failed to parse JSON Expecting value: line 1 column 1 (char 0)
ERROR: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/kyleanthonywilliams2/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kyleanthonywilliams2/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/home/kyleanthonywilliams2/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/kyleanthonywilliams2/.local/lib/python3.7/site-packages/youtube_dl/extractor/funimation.py", line 100, in _real_extract
    ], webpage, fatal=True)
  File "/home/kyleanthonywilliams2/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1140, in _html_search_meta
    html, display_name, fatal=fatal, group='content', **kwargs)
  File "/home/kyleanthonywilliams2/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1019, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/kyleanthonywilliams2/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

In order to obtain a video ID, the Funimation extractor [searches for a URL](https://github.com/ytdl-org/youtube-dl/blob/416da574ec0df3388f652e44f7fe71b1e3a4701f/youtube_dl/extractor/funimation.py#L95) from a small handful of `<meta>` tags:

```python
if not video_id:
            player_url = self._html_search_meta([
                'al:web:url',
                'og:video:url',
                'og:video:secure_url',
            ], webpage, fatal=True)
            video_id = self._search_regex(r'/player/(\d+)', player_url, 'video id')
```
youtube-dl's regex search function then outputs an error, complaining that none of the metatags can be found, as the search is set to be fatal. Looking at the HTML page, all three `<meta>` tags can still be found:
```html
<meta property="al:web:url" content="/player/1326190">

<meta property="og:type" content="video">
<meta property="og:video:url" content="/player/1326190">
<meta property="og:video:secure_url" content="/player/1326190">
<meta property="og:video:width" content="1920">
<meta property="og:video:height" content="1080">
```
This makes me believe that there's something wrong with YTDL's regex finder and not the code written here nor the expected content of the page changing. Thoughts?

**Comment by Sophira** [comment]
I believe this is caused by not having up-to-date cookies; I also encountered this error, but going back to the Funimation website and re-exporting the cookies fixed it.

**Comment by CHJ85** [comment]
@Sophira is right.
Update the cookies file and use a valid user-agent string.
