### ISSUE TITLE
[SVT] No video formats found

### ISSUE THREAD

**Issue by haraldmartin** [ytdl-org/youtube-dl#28448]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
> youtube_dl --verbose 'https://www.svtplay.se/video/30101494/sportspegeln/sportspegeln-14-mars-19-00'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.svtplay.se/video/30101494/sportspegeln/sportspegeln-14-mars-19-00']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.14
[debug] Git HEAD: 3be098010
[debug] Python version 2.7.16 (CPython) - Darwin-20.3.0-x86_64-i386-64bit
[debug] exe versions: avconv present, avprobe present, ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 78.66.165.55 (SE) as X-Forwarded-For.
[SVTPlay] 30101494: Downloading webpage
[SVTPlay] jBMzdLm: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "youtube_dl/extractor/svt.py", line 321, in _real_extract
    info_dict = self._extract_by_video_id(svt_id, webpage)
  File "youtube_dl/extractor/svt.py", line 246, in _extract_by_video_id
    info_dict = self._extract_video(data, video_id)
  File "youtube_dl/extractor/svt.py", line 69, in _extract_video
    self._sort_formats(formats)
  File "youtube_dl/extractor/common.py", line 1369, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Trying to download videos doesn't work. The site was recently redesigned which might have broken extractors. 
Some urls still work such as https://www.svtplay.se/video/30141448/morgonstudion/morgonstudion-12-mars-06-00-1?modalId=Kkp3QnA

**Comment by haraldmartin** [comment]
THANKS @dstftw <3
