### ISSUE TITLE
Vimeo dowloads failing

### ISSUE THREAD

**Issue by MMitsialis** [ytdl-org/youtube-dl#28455]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
marcm@RAZA:~/WinHome/OneDrive/acim$ youtube-dl --verbose  https://vimeo.com/515227699/b4c0cd170d
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://vimeo.com/515227699/b4c0cd170d']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.31
[debug] Python version 3.8.5 (CPython) - Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[vimeo] 515227699: Downloading webpage
[vimeo] 515227699: Extracting information
ERROR: Unable to extract info section (caused by JSONDecodeError('Extra data: line 1 column 3 (char 2)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/marcm/.local/lib/python3.8/site-packages/youtube_dl/extractor/vimeo.py", line 635, in _real_extract
    page_config = self._parse_json(self._search_regex(
  File "/home/marcm/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract page config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marcm/.local/lib/python3.8/site-packages/youtube_dl/extractor/vimeo.py", line 658, in _real_extract
    config = json.loads(config)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)
Traceback (most recent call last):
  File "/home/marcm/.local/lib/python3.8/site-packages/youtube_dl/extractor/vimeo.py", line 635, in _real_extract
    page_config = self._parse_json(self._search_regex(
  File "/home/marcm/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract page config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marcm/.local/lib/python3.8/site-packages/youtube_dl/extractor/vimeo.py", line 658, in _real_extract
    config = json.loads(config)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marcm/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/home/marcm/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/home/marcm/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/marcm/.local/lib/python3.8/site-packages/youtube_dl/extractor/vimeo.py", line 670, in _real_extract
    raise ExtractorError('Unable to extract info section',
youtube_dl.utils.ExtractorError: Unable to extract info section (caused by JSONDecodeError('Extra data: line 1 column 3 (char 2)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

- This site posts short video daily. I have been using youtube-dl to dowload the dailly video message for future viewing. Suddenly the downloads are failing. 

- I have tries on three different computers, two using Ubuntu 20.04LTS on WSL, and on running Debian Buster. All yield the same result. 

- Both older and new video post yield the same result.

**Comment by mic1060** [comment]
Hi, I have the same issue on another video. Linux Debian 9-11 x64
---------------------------------
$youtube-dl -F -v https://vimeo.com/512309078/4c76d1b3fd
[debug] System config: []
[debug] User config: [u'--abort-on-error', u'--abort-on-unavailable-fragment', u'--retries', u'infinite', u'--fragment-retries', u'infinite', u'--write-description', u'--write-info-json', u'--write-annotations', u'--write-sub', u'--all-subs', u'--write-thumbnail', u'--write-all-thumbnails', u'--fixup', u'warn', u'--keep-video', u'--verbose']
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'-v', u'https://vimeo.com/512309078/4c76d1b3fd']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.14
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-15-amd64-x86_64-with-debian-9.13
[debug] exe versions: ffmpeg 3.2.15-0, ffprobe 3.2.15-0, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 512309078: Downloading webpage
[vimeo] 512309078: Extracting information
ERROR: Unable to extract info section (caused by ValueError('Extra data: line 1 column 3 - line 1 column 104 (char 2 - 103)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 665, in _real_extract
    config = json.loads(config)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 3 - line 1 column 104 (char 2 - 103)
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 678, in _real_extract
    cause=e)
ExtractorError: Unable to extract info section (caused by ValueError('Extra data: line 1 column 3 - line 1 column 104 (char 2 - 103)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
--------------------------------------------
This video will be available until April 5
