### ISSUE TITLE
Bitchute downloads not working

### ISSUE THREAD

**Issue by sturmsignal** [ytdl-org/youtube-dl#28461]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.03.14**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
**1**) for video https://www.bitchute.com/video/T0dUeOSq0H5y/

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bitchute.com/video/T0dUeOSq0H5y/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.03.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[BitChute] T0dUeOSq0H5y: Downloading webpage
[BitChute] T0dUeOSq0H5y: Checking video URL
[BitChute] T0dUeOSq0H5y: video URL is invalid, skipping: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\bitchute.py", line 66, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\common.py", line 1369, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**2**) for video https://www.bitchute.com/video/BCiuXSSSGjBX/

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bitchute.com/video/BCiuXSSSGjBX/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.03.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[BitChute] BCiuXSSSGjBX: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\__init__.py", line 465, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\YoutubeDL.py", line 2060, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\YoutubeDL.py", line 799, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\bitchute.py", line 63, in _real_extract
IndexError: list index out of range

**3)** for video https://www.bitchute.com/video/SUilY6fjBa9L/ 

[BitChute] SUilY6fjBa9L: Downloading webpage
[BitChute] SUilY6fjBa9L: Checking video URL
[BitChute] SUilY6fjBa9L: video URL is invalid, skipping: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

I tried around 20 Bitchute videos to download without success. The above mentioned error messages are returned.

**Comment by kikuyan** [comment]
Seems to be working now with version 2021.06.06. If you still get `<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>`, that might be of your python or OS problem.

```
$ youtube-dl -o "%(id)s.%(ext)s" https://www.bitchute.com/video/T0dUeOSq0H5y/
[BitChute] T0dUeOSq0H5y: Downloading webpage
[BitChute] T0dUeOSq0H5y: Checking video URL
[download] Destination: T0dUeOSq0H5y.mp4
[download]   6.8% of 59.01MiB at  2.06MiB/s ETA 00:26^C
ERROR: Interrupted by user
```
```
$ youtube-dl -o "%(id)s.%(ext)s" https://www.bitchute.com/video/BCiuXSSSGjBX/
[BitChute] BCiuXSSSGjBX: Downloading webpage
[BitChute] BCiuXSSSGjBX: Checking video URL
[download] Destination: BCiuXSSSGjBX.mp4
[download]   6.6% of 60.91MiB at  2.25MiB/s ETA 00:25^C
ERROR: Interrupted by user
```
```
$ youtube-dl -o "%(id)s.%(ext)s" https://www.bitchute.com/video/SUilY6fjBa9L/
[BitChute] SUilY6fjBa9L: Downloading webpage
[BitChute] SUilY6fjBa9L: Checking video URL
[download] Destination: SUilY6fjBa9L.mp4
[download]   1.3% of 33.15MiB at 199.13KiB/s ETA 02:48^C
ERROR: Interrupted by user
```

**Comment by bubul01** [comment]
I've the same error with youtubedl on windows 10 , in fact i've tried since month to download video from bichute and it never work for me, always an error , but other websites like youtube, odysee, or peertube websites work and i have last version (youtube-dl is up-to-date (2021.06.06)):

 [BitChute] Yv4pgeXCFpM: Downloading webpage
 [BitChute] Yv4pgeXCFpM: Checking video URL
 [BitChute] Yv4pgeXCFpM: video URL is invalid, skipping: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
