### ISSUE TITLE
Patreon KeyError (post_file)

### ISSUE THREAD

**Issue by Lucrio** [ytdl-org/youtube-dl#28512]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.patreon.com/posts/stephanie-p-e-e-41880166', '-o', '~/Videos/Enigmatt/%(title)s.%(ext)s']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.03.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[Patreon] 41880166: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('post_file',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\patreon.py", line 148, in _real_extract
KeyError: 'post_file'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\patreon.py", line 148, in _real_extract
KeyError: 'post_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\common.py", line 547, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('post_file',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Attempting to data hoard some patreon content. Content hosted on vimeo/youtube works fine, content embedded in patreon itself is giving me this error. I see a similar issue posted based on "KeyError (embed)" but it's closed with no fix or workaround that I can see, and the error message tells me to post it here, so that's what I'm doing.

**Comment by Lucrio** [comment]
This may be related to open issue #28414 regarding unlisted content on vimeo as it appears the content is hosted there, but the unlisted nature changes the interface and made me think it was hosted elsewhere.
