### ISSUE TITLE
L-zKZ3iFf68: YouTube said: Invalid parameters.

### ISSUE THREAD

**Issue by hajoko1** [ytdl-org/youtube-dl#28527]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.03.14**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ ]x I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
pi@raspberrypi:~ $ sudo youtube-dl -U
youtube-dl is up-to-date (2021.03.14)
pi@raspberrypi:~ $ youtube-dl --version
2019.01.17

Version is up to date, but --version reports an older one. ?????????

## Description

WRITE DESCRIPTION HERE

pi@raspberrypi:~ $ youtube-dl -v https://www.youtube.com/watch?v=L-zKZ3iFf68
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=L-zKZ3iFf68']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.17
[debug] Python version 3.7.3 (CPython) - Linux-5.4.72-v7l+-armv7l-with-debian-10.8
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs 2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] L-zKZ3iFf68: Downloading webpage
[youtube] L-zKZ3iFf68: Downloading video info webpage
ERROR: L-zKZ3iFf68: YouTube said: Invalid parameters.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1688, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: L-zKZ3iFf68: YouTube said: Invalid parameters.

Whats wrong? Where are my mistakes? What can I do? Please help. Thank you.

**Comment by hajoko1** [comment]
THANK YOU VERY MUCH FOR YOUR HELP!!
Why did you close this report without any hint how to solve this problem?

**Comment by hajoko1** [comment]
pi@raspberrypi:~ $ sudo youtube-dl -U
youtube-dl is up-to-date (2021.03.14)
pi@raspberrypi:~ $ youtube-dl --version
2019.01.17

Version is up to date, but --version reports an older one. ?????????
