### ISSUE TITLE
youtube-dl cookies in config.txt

### ISSUE THREAD

**Issue by wankio** [ytdl-org/youtube-dl#28526]
## Checklist

- [x ] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

```
-o I:/youtube-dl/%(extractor)s/%(title)s-%(uploader)s-%(channel_id)s-%(channel)s-%(id)s.%(ext)s
-f bestvideo[height<=?1080]+bestaudio/best
--write-thumbnail 
--cookies C:\Users\GEN32UC\AppData\Roaming\youtube-dl\cookies.txt
--write-sub
--write-auto-sub
--sub-lang en-GB
```

i'm download video on facebook, but cookies wont work, i need to add it into command instead

eg:
youtube-dl facebookURL --cookies C:\Users\GEN32UC\AppData\Roaming\youtube-dl\cookies.txt

did my config file is wrong ? ty

**Comment by dstftw** [comment]
Post verbose log.

**Comment by wankio** [comment]
```
[debug] System config: []
[debug] User config: ['-o', 'I:/youtube-dl/%(extractor)s/%(title)s-%(uploader)s-%(channel_id)s-%(channel)s-%(id)s.%(ext)s', '-f', 'bestvideo[height<=?1080]+bestaudio/best', '--write-thumbnail', '--cookies', 'C:UsersGEN32UCAppDataRoamingyoutube-dlcookies.txt', '--write-sub', '--write-auto-sub', '--sub-lang', 'en-GB']
[debug] Custom config: []
[debug] Command-line args: ['https://www.facebook.com/bryan.castillo.5836711/videos/1825626214282572', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.03.14
[debug] Python version 3.8.2 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-92966-gd52a1be4e3, ffprobe N-92966-gd52a1be4e3
[debug] Proxy map: {}
[facebook] 1825626214282572: Downloading webpage
[facebook] 1825626214282572: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\gen32uc\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\gen32uc\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\gen32uc\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\users\gen32uc\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\facebook.py", line 677, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "c:\users\gen32uc\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\facebook.py", line 591, in _extract_from_url
    raise ExtractorError('Cannot parse data')
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by FoxMcloud5655** [comment]
I think I found your problem...  Are you running this from a batch script?  If so, you need to double escape your `\` symbols.
```
'C:UsersGEN32UCAppDataRoamingyoutube-dlcookies.txt',
```
The above is what's passed to youtube-dl.

**Comment by pukkandan** [comment]
Use `/` instead of `\` as a workaround

**Comment by wankio** [comment]
> 
> 
> I think I found your problem... Are you running this from a batch script? If so, you need to double escape your `\` symbols.
> 
> ```
> C:UsersGEN32UCAppDataRoamingyoutube-dlcookies.txt
> ```
> 
> The above is what's passed to youtube-dl.

no i'm just calling youtube-dl in command

**Comment by Ahmed9914** [comment]
@dstftw Issue can be closed now.
