### ISSUE TITLE
platzi: download not working

### ISSUE THREAD

**Issue by JuanAliagaPerez** [ytdl-org/youtube-dl#28536]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

youtube-dl.exe --cookies p_cookies.txt --no-check-certificate https://platzi.com/clases/1325-financiera-startups/12690-gastos/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'p_cookies.txt', '--no-check-certificate', 'https://platzi.com/clases/1325-financiera-startups/12690-gastos/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.03.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.10240
[debug] exe versions: none
[debug] Proxy map: {}
[Platzi] 12690: Downloading webpage
ERROR: Unable to extract client data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\platzi.py", line 114, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract client data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description
I am subscribed to platzi and, due to download speed, I download the videos at work so that I can study them at home at night.
Until yesterday (March 23, 2021) I have been able to download the videos from the platform, but today it was not possible for me to do it, I have tried with other videos from other video services (such as YouTube) and it works perfectly, I assume the service was somehow patched.

**Comment by Jjaraa** [comment]
I have de same issue, and if I update ytdl the error persists

**Comment by JeanCarlosDEV17** [comment]
puedo aportar que de igual manera me funcionaba hasta el dia 23/03/2021 y me sucede lo mismo  ya no lo permite

**Comment by JeanCarlosDEV17** [comment]
I used it until 03/24/2021 and 25 / update youtube-dl to the latest version and the error persists in the same way as it happens to juanAliaga, apparently platzi patched this way of making backup copies

**Comment by DimaSheiko** [comment]
@JeanCarlosDEV17 You mean platzi patched this yesterday before launching platzi day?

**Comment by JeanCarlosDEV17** [comment]
> @JeanCarlosDEV17 You mean platzi patched this yesterday before launching platzi day?

I've been using it for some time to make backup copies of my courses, my electrical network is unstable, for some time platzi has been patching not being able to login with username and password in youtube-dl, apparently because of platzi day I have patched it completely

**Comment by GlowerTvg** [comment]
> 
> 
> @JeanCarlosDEV17 You mean platzi patched this yesterday before launching platzi day?

I have the same problem, previously I also used youtube-dl to download content from platzi and I had no problem, but now it is impossible to download content from this platform, I tried in several ways and with several parameters and always sends the same error

**Comment by Anonteam798** [comment]
There is not any way to download, platzi videos guys  ?

**Comment by mocasda** [comment]
is there another way to download videos from platzi now?

**Comment by DimaSheiko** [comment]
It looks like there won't be time to do this.
But remember guys. Never stop learning. ☺

**Comment by NotoriusElectron** [comment]
Hi guys well I think Platzi thought about the free learning days and wants to nobody downloaded any videos from they, today I tried, first my youtube-dl was not in the last version, but it kept working as usual, but today when I tried with platzi, I couldn't download any video, so I upgrade the youtube-dl and the error kept there. If somebody knows another method i'll be so glad with you. I wanna learn but I can't buy it, i hate the latinamerican economics
for spanish speakers: Raza trate de aprovechar los dias gratis del platzi pero no pude, si saben alguna forma de descargar los videos lo apreciaria mucho.

**Comment by Devil64-Dev** [comment]
Hola, imagino que aún no se ha solucionado el problema, pero pensando en ello cree este proyecto que soluciona el error que empezó desde el platzi day al momento descargar videos de platzi, [link del proyecto](https://github.com/Devil64-Dev/platzi-dtool), de momento solo funciona para distribuciones basadas en GNU, pero en puede usarse en Windows mediante WSL (WIndows Subsystem For Linux).

El error se ocasiono debido a que antes de lanzar el cambiaron la estructura de los datos de los servidores de streaming por lo tanto el extractor normal dejo de funcionar arrojando un error de búsqueda.

**Comment by JeanCarlosDEV17** [comment]
te agradezco le voy a hechar un ojito con wsl , no tengo mal internet pero
si mal servicio de energia y pues cuando se va la energia no tengo servicio
de internet

**Comment by BabyWhite69** [comment]
@NotoriusElectron https://github.com/Devil64-Dev/automated-dtool

**Comment by EduTel** [comment]
what they need to do is add the cookies youtube-dl --cookies '{path}/platzi.com_cookies.txt' 'download_url' these cookies can be extracted with https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid after sing in platzi and once logged in download the cookies with the extension

**Comment by ingmferrer** [comment]
> what they need to do is add the cookies youtube-dl --cookies '{path}/platzi.com_cookies.txt' 'download_url' these cookies can be extracted with https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid after sing in platzi and once logged in download the cookies with the extension

it's not working even with your PR changes

**Comment by dirkf** [comment]
I've updated the PR code. Please test and follow up [there](https://github.com/ytdl-org/youtube-dl/pull/30548).
