### ISSUE TITLE
ARDMediathek fails

### ISSUE THREAD

**Issue by Tatortfan** [ytdl-org/youtube-dl#28549]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe -v https://www.ardmediathek.de/video/tatort/tatort-sterben-fuer-die-erben/swr-fernsehen/Y3JpZDovL3N3ci5kZS9hZXgvbzE0Mjk4MjI/
[debug] System config: []
[debug] User config: ['--write-sub']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.ardmediathek.de/video/tatort/tatort-sterben-fuer-die-erben/swr-fernsehen/Y3JpZDovL3N3ci5kZS9hZXgvbzE0Mjk4MjI/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.03.25
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-05-28-c0f01ea, ffprobe git-2020-05-28-c0f01ea
[debug] Proxy map: {}
[debug] Using fake IP 53.144.233.63 (DE) as X-Forwarded-For.
[ARD:mediathek] Y3JpZDovL3N3ci5kZS9hZXgvbzE0Mjk4MjI: Downloading webpage
ERROR: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\extractor\ard.py", line 236, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

youtube-dl fails to download files from ARDmediathek, also those that could be downloaded a few days ago.

**Comment by wpnhenry** [comment]
I had the same problem, went through the same checklist

Verbose log:

 › youtube-dl --verbose "https://www.ardmediathek.de/sendung/walulis-woche/Y3JpZDovL3N3ci5kZS9zZGIvc3RJZC8xMjQw/" >> yt-error.txt                                            1
[debug] System config: []
[debug] User config: ['--no-cache-dir', '--restrict-filenames', '-o', '~/Desktop/yt-dl/%(title)s.%(ext)s', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.ardmediathek.de/sendung/walulis-woche/Y3JpZDovL3N3ci5kZS9zZGIvc3RJZC8xMjQw/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8                                                                                                             5:51
[debug] youtube-dl version 2021.03.25
[debug] Python version 3.9.2 (CPython) - macOS-11.2.3-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.3.25/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.3.25/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.3.25/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.3.25/libexec/lib/python3.9/site-packages/youtube_dl/extractor/ard.py", line 235, in _real_extract
    video_id = self._search_regex(
  File "/usr/local/Cellar/youtube-dl/2021.3.25/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
~ ›                                                                                                                                                                           1

**Comment by leogaggl** [comment]
Same on Ubuntu 20.04 LTS:

youtube-dl https://www.ardmediathek.de/video/krimis-im-ersten/das-verschwinden-der-irland-krimi/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2tyaW1pcy1pbS1lcnN0ZW4vZDJiZTUwYTMtM2FhZC00OTA3LTkzZmMtZGM2ZWM5Y2JmMDhj/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.ardmediathek.de/video/krimis-im-ersten/das-verschwinden-der-irland-krimi/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2tyaW1pcy1pbS1lcnN0ZW4vZDJiZTUwYTMtM2FhZC00OTA3LTkzZmMtZGM2ZWM5Y2JmMDhj/', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.25
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-67-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
Y3JpZDovL2Rhc2Vyc3RlLmRlL2tyaW1pcy1pbS1lcnN0ZW4vZDJiZTUwYTMtM2FhZC00OTA3LTkzZmMtZGM2ZWM5Y2JmMDhj: Downloading webpage
ERROR: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/lgaggl/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/home/lgaggl/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/home/lgaggl/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/lgaggl/.local/lib/python3.8/site-packages/youtube_dl/extractor/ard.py", line 235, in _real_extract
    video_id = self._search_regex(
  File "/home/lgaggl/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by domhaase** [comment]
I am having the same issue on macOS 11.2.3
$> youtube-dl https://www.ardmediathek.de/video/die-story/boeing-das-toedliche-system/wdr-fernsehen/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTY4YjQ4OTdhLTg5ZDEtNGU2NC05M2FjLTk5ZWY3ZTVmNmFkMQ
--verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.ardmediathek.de/video/die-story/boeing-das-toedliche-system/wdr-fernsehen/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTY4YjQ4OTdhLTg5ZDEtNGU2NC05M2FjLTk5ZWY3ZTVmNmFkMQ', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.25
[debug] Python version 3.9.2 (CPython) - macOS-11.2.3-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 53.118.35.79 (DE) as X-Forwarded-For.
[ARD:mediathek] Y3JpZDovL3dkci5kZS9CZWl0cmFnLTY4YjQ4OTdhLTg5ZDEtNGU2NC05M2FjLTk5ZWY3ZTVmNmFkMQ: Downloading webpage
ERROR: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.3.25/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.3.25/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.3.25/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.3.25/libexec/lib/python3.9/site-packages/youtube_dl/extractor/ard.py", line 235, in _real_extract
    video_id = self._search_regex(
  File "/usr/local/Cellar/youtube-dl/2021.3.25/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
