### ISSUE TITLE
Xvideos: Video exists, but YouTube-DL gives 404 error

### ISSUE THREAD

**Issue by Rekrullurker** [ytdl-org/youtube-dl#28546]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.03.25**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[debug] System config: []                                                       
[debug] User config: []                                                         
[debug] Custom config: []                                                       
[debug] Command-line args: ['-v', 'https://www.xvideos.com/video60816899/how_to_make_a_super_realistic_pussy_at_home_without_money_version_2_']                 
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252              
[debug] youtube-dl version 2021.03.25                                           
[debug] Python version 3.4.4 (CPython) - Windows-XP-5.1.2600-SP3                
[debug] exe versions: ffmpeg N-93954-g76ef18fd39                                
[debug] Proxy map: {}                                                           
[debug] Default format spec: bestvideo+bestaudio/best                           
ERROR: unable to download video data: HTTP Error 404: Not Found                 
Traceback (most recent call last):                                              
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\YoutubeDL.py", line 1967, in process_info                   
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\YoutubeDL.py", line 1906, in dl                             
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\downloader\common.py", line 366, in download                
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\downloader\hls.py", line 64, in real_download               
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\YoutubeDL.py", line 2279, in urlopen                        
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open            
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response   
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error           
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain     
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default                                                                              
urllib.error.HTTPError: HTTP Error 404: Not Found                               

## Description

WRITE DESCRIPTION HERE
This video popped up on the front page of Xvideos, so I decided to try downloading it. YouTube-DL gave a 404: Not found error, but the video does play in the browser. It can also be downloaded if you view the page source and search for MP4, then feed that URL to the browser.

I tried some previous versions going back to November and they gave the same result.

**Comment by Rekrullurker** [comment]
Even though it's contained in the log, I neglected to add a copy of the URL by itself and I'm not able to edit my post, so here's the URL;

https://www.xvideos.com/video60816899/how_to_make_a_super_realistic_pussy_at_home_without_money_version_2_

**Comment by ottersarecool** [comment]
stop cooming

**Comment by NO-ob** [comment]
![image](https://user-images.githubusercontent.com/15161159/112638632-5e37e900-8e37-11eb-9293-c82dc512ef71.png)
