### ISSUE TITLE
Website videos will not download.

### ISSUE THREAD

**Issue by sterling1989** [ytdl-org/youtube-dl#28543]
## Checklist

- [x] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.03.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\DL>ytdl2 -v -f best https://txxx.com/videos/14808252/tiny-teen-pussy-gets-destroyed-by-big-dick
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'best', 'https://txxx.com/videos/14808252/tiny-teen-pussy-gets-destroyed-by-big-dick']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.03.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: avconv present, ffmpeg 4.3.2-2021-02-27-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[generic] tiny-teen-pussy-gets-destroyed-by-big-dick: Requesting header
[redirect] Following redirect to https://txxx.com/videos/14808252/tiny-teen-pussy-gets-destroyed-by-big-dick/
[generic] tiny-teen-pussy-gets-destroyed-by-big-dick: Requesting header
WARNING: Falling back on generic information extractor.
[generic] tiny-teen-pussy-gets-destroyed-by-big-dick: Downloading webpage
[generic] tiny-teen-pussy-gets-destroyed-by-big-dick: Extracting information
ERROR: Unsupported URL: https://txxx.com/videos/14808252/tiny-teen-pussy-gets-destroyed-by-big-dick/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\generic.py", line 3506, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://txxx.com/videos/14808252/tiny-teen-pussy-gets-destroyed-by-big-dick/
```

## Description

No videos on the website txxx.com will work. All give the same error.

**Comment by sebma** [comment]
#9015
