### ISSUE TITLE
getting video unavailable on every video on my discord py music bot utilizing youtube dl. Everything redownloaded and updated to most current version.

### ISSUE THREAD

**Issue by lartzam** [ytdl-org/youtube-dl#28555]
## Checklist

- [ x] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.03.25**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
bot is ready.
[youtube] oqlbyopdg6c: Downloading webpage
ERROR: Video unavailable
Ignoring exception in command play:
Traceback (most recent call last):
  File "C:\Users\Lauri\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Lauri\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Lauri\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Lauri\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\youtube.py", line 1658, in _real_extract
    raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: Video unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lauri\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Lauri\Documents\Bot\Raccoon\music.py", line 36, in play
    ydl.download([url])
  File "C:\Users\Lauri\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2059, in download
    res = self.extract_info(
  File "C:\Users\Lauri\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 799, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\Lauri\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\Lauri\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Lauri\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Video unavailable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lauri\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Lauri\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Lauri\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: DownloadError: ERROR: Video unavailable

## Description

WRITE DESCRIPTION HERE
Getting video unavailable on every video on my discord py music bot utilizing youtube dl. Everything redownloaded and updated to most current version.

**Comment by remitamine** [comment]
The same message in the browser(Video unavailable).

**Comment by lartzam** [comment]
This is not true, the video is very much playable in browser. https://www.youtube.com/watch?v=OQlByoPdG6c 
![image](https://user-images.githubusercontent.com/38312898/112721726-4717fa80-8f0e-11eb-9636-5d4c0501f072.png)

**Comment by remitamine** [comment]
> [youtube] oqlbyopdg6c: Downloading webpage

Youtube Video IDs are case-sensitive, so pass the correct Video ID `OQlByoPdG6c` not `oqlbyopdg6c`).

**Comment by lartzam** [comment]
Hi, thank you for the response. It is being given the correct url though I have no idea why it is making it all lowercase when youtube dl searches for it. I haven't made any changes to the code and have gone over it multiple times now by myself and shown it to others. If anyone has the slightest idea why this might be happening it would be appreciated. There isn't anything editing the inputted url in anyway so it makes no sense why it is making it lowercase... The only thing I know is that I have updated the youtube-dl module itself...

`song_there = os.path.isfile("song.wav")
            try:
                if song_there:
                    os.remove("song.wav")
            except PermissionError:
                await ctx.send("Am already busy!")
                return
            await ctx.send("Wait a little, am loading the music.")
            voiceChannel=ctx.message.author.voice.channel
            await voiceChannel.connect()
            voice = discord.utils.get(self.client.voice_clients, guild=ctx.guild)
            ydl_opts = {
                'format': 'bestaudio/best',
                'postprocessors': [{
                    'key': 'FFmpegExtractAudio',
                    'preferredcodec': 'wav',
                    'preferredquality': '192',
                }],
            }
            with youtube_dl.YoutubeDL(ydl_opts) as ydl:
                ydl.download([url])
            for file in os.listdir("./"):
                if file.endswith(".wav"):
                    os.rename(file, "song.wav")
            voice.play(discord.FFmpegPCMAudio("song.wav"))
            await ctx.send("Enjoy.")`
