### ISSUE TITLE
Add support for "sport" on ServusTV

### ISSUE THREAD

**Issue by arminfuerst** [ytdl-org/youtube-dl#28561]
## Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running youtube-dl version **2021.03.25**
- [X] I've searched the bugtracker for similar site feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
Downloading from ServusTV is working well for URLs starting with "https://www.servustv.com/videos/..." but not for other URLs, here is an example for URL for sports events:
https://www.servustv.com/sport/v/aa-26u9qxfd52111/
I've tried just extending _VALID_URL to match this type of URLs, but there are additional changes needed. After extending _VALID_URL the verbose output was:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.servustv.com/sport/v/aa-26u9qxrbw1w11/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.25
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-16-amd64-x86_64-with-debian-10.9
[debug] exe versions: avconv 4.1.6, avprobe 4.1.6, ffmpeg 4.1.6, ffprobe 4.1.6, rtmpdump 2.4
[debug] Proxy map: {}
[Servus] AA-26U9QXRBW1W11: Downloading token
[Servus] AA-26U9QXRBW1W11: Downloading video JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/servus.py", line 111, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1369, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by arminfuerst** [comment]
Did you do a successful download with this change? This is close to what I tried myself and the result was that the link was detected but the download was not working...

**Comment by arminfuerst** [comment]
I'm not sure whether this is a different issue or to be handled here. When trying to download https://www.servustv.com/sport/v/aa-26ua568w12111/ I the following error:
[Servus] AA-26UA568W12111: Downloading token
[Servus] AA-26UA568W12111: Downloading video JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

The link you posted above is working properly.
