### ISSUE TITLE
[ADN] Can't download subtitles from ADN

### ISSUE THREAD

**Issue by Gaby13627** [ytdl-org/youtube-dl#28560]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '-f', 'best[height=480]', '--all-subs', 'https://animedigitalnetwork.fr/video/my-hero-academia-saison-5/14397-episode-1-la-seconde-a-part-en-mission', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.03.25
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1-2021-01-01-full_build-www.gyan.dev, ffprobe 4.3.1-2021-01-01-full_build-www.gyan.dev
[debug] Proxy map: {}
[ADN] Logging in
[ADN] 14397: Downloading player config JSON metadata
[ADN] 14397: Downloading access token
[ADN] 14397: Downloading links JSON metadata
[ADN] 14397: Downloading vostf fhd JSON metadata
[ADN] 14397: Downloading m3u8 information
[ADN] 14397: Downloading vostf sd JSON metadata
[ADN] 14397: Downloading m3u8 information
[ADN] 14397: Downloading vostf mobile JSON metadata
[ADN] 14397: Downloading m3u8 information
[ADN] 14397: Downloading vostf hd JSON metadata
[ADN] 14397: Downloading m3u8 information
[ADN] 14397: Downloading vostf auto JSON metadata
[ADN] 14397: Downloading m3u8 information
[ADN] 14397: Downloading additional video metadata
[ADN] 14397: Downloading subtitles location
[ADN] 14397: Downloading subtitles data
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\__init__.py", line 465, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\YoutubeDL.py", line 2060, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\YoutubeDL.py", line 799, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\extractor\adn.py", line 260, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\extractor\common.py", line 2963, in extract_subtitles
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\extractor\adn.py", line 96, in _get_subtitles
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 1: invalid continuation byte
```

## Description

Hello,

Youtube-dl manages to download the videos from the ADN site without any problem but can't download the subtitles anymore.
I think this is caused by the recent update of the site.

Does anyone have a solution to download the subtitles again?

Thank you.

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl/issues/12724#issuecomment-481673353
