### ISSUE TITLE
BBC iPlayer urlopen error

### ISSUE THREAD

**Issue by Zettexe** [ytdl-org/youtube-dl#28581]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v https://www.bbc.co.uk/iplayer/episodes/b006q2x0/doctor-who?seriesId=b006v193
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bbc.co.uk/iplayer/episodes/b006q2x0/doctor-who?seriesId=b006v193']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.03.25
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-03-24-git-a77beea6c8-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[bbc.co.uk:iplayer:episodes] b006q2x0: Downloading JSON metadata
[download] Downloading playlist: Doctor Who
[bbc.co.uk:iplayer:episodes] b006q2x0: Downloading JSON metadata
[bbc.co.uk:iplayer:episodes] playlist Doctor Who: Downloading 14 videos
[download] Downloading video 1 of 14
[bbc.co.uk] b0074gly: Downloading video page
[bbc.co.uk] b0074gly: Downloading playlist JSON
[bbc.co.uk] p068k0ly: Downloading media selection JSON
[bbc.co.uk] p068k0ly: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[bbc.co.uk] p068k0ly: Downloading MPD manifest
[bbc.co.uk] p068k0ly: Downloading MPD manifest
[bbc.co.uk] p068k0ly: Downloading MPD manifest
[bbc.co.uk] p068k0ly: Downloading MPD manifest
[bbc.co.uk] p068k0ly: Downloading MPD manifest
[bbc.co.uk] p068k0ly: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] p068k0ly: Downloading m3u8 information
[bbc.co.uk] p068k0ly: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] p068k0ly: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] p068k0ly: Downloading m3u8 information
[bbc.co.uk] p068k0ly: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[download] Doctor Who, Series 3, Smith and Jones-p068k0ly.mp4 has already been downloaded and merged
[download] Downloading video 2 of 14
[bbc.co.uk] b0074gmy: Downloading video page
[bbc.co.uk] b0074gmy: Downloading playlist JSON
[bbc.co.uk] b0071xzn: Downloading media selection JSON
[bbc.co.uk] b0071xzn: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b0071xzn: Downloading m3u8 information
[bbc.co.uk] b0071xzn: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b0071xzn: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b0071xzn: Downloading m3u8 information
[bbc.co.uk] b0071xzn: Downloading m3u8 information
[bbc.co.uk] b0071xzn: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[bbc.co.uk] b0071xzn: Downloading MPD manifest
[bbc.co.uk] b0071xzn: Downloading MPD manifest
[bbc.co.uk] b0071xzn: Downloading MPD manifest
[bbc.co.uk] b0071xzn: Downloading MPD manifest
[bbc.co.uk] b0071xzn: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://vod-dash-uk.live.cf.md.bbci.co.uk/usp/auth/vod/piff_abr_full_sd/e75fdd-b0071xzn/vf_b0071xzn_d5ce6041-b68b-46e1-b5ba-2c17e1c54505.ism/iptv_hd_abr_v1_dash_master.mpd?Expires=1617012419&Signature=PpOIP5l50cJXjE9D-FTyM0QwTWaZ7SZb6L-TAWupt1pXQzbVA-xIv1xliBFDphsN5uB4aJ5ZSeHn-PT0qCoG7a97o1~hKCJKiGANmipoQDwVsczIagRJzv2zDmDqIxy0Bk-tDivFV~~L6qOgF9-yRGPP1oGR0FKLcEi~FXXadlJFaPUP6TzQPG8v~~njPnfFlmjXwX9XzulLxpX9v2gOkV2zU7p4bFIVq9cBpaOukjzKQwcWmRAfz6snSm5tjG0xa4p2Qk-SzIm-zX3~txd6YnIIYeEEnA5SNBBZYMiKUsCSnwfTq-3tkm5pw621mZqFpOXyIZxLdJXpk-AKgzfmpg__&Key-Pair-Id=K2VWLYKQ4HU1FJ'
[dashsegments] Total fragments: 713
[download] Destination: Doctor Who, Series 3, The Shakespeare Code-b0071xzn.fmf_cloudfront-video=1570000-1.mp4
[download] 100% of 510.80MiB in 03:51
[debug] Invoking downloader on 'https://vod-dash-uk.live.cf.md.bbci.co.uk/usp/auth/vod/piff_abr_full_sd/e75fdd-b0071xzn/vf_b0071xzn_d5ce6041-b68b-46e1-b5ba-2c17e1c54505.ism/iptv_hd_abr_v1_dash_master.mpd?Expires=1617012419&Signature=PpOIP5l50cJXjE9D-FTyM0QwTWaZ7SZb6L-TAWupt1pXQzbVA-xIv1xliBFDphsN5uB4aJ5ZSeHn-PT0qCoG7a97o1~hKCJKiGANmipoQDwVsczIagRJzv2zDmDqIxy0Bk-tDivFV~~L6qOgF9-yRGPP1oGR0FKLcEi~FXXadlJFaPUP6TzQPG8v~~njPnfFlmjXwX9XzulLxpX9v2gOkV2zU7p4bFIVq9cBpaOukjzKQwcWmRAfz6snSm5tjG0xa4p2Qk-SzIm-zX3~txd6YnIIYeEEnA5SNBBZYMiKUsCSnwfTq-3tkm5pw621mZqFpOXyIZxLdJXpk-AKgzfmpg__&Key-Pair-Id=K2VWLYKQ4HU1FJ'
[dashsegments] Total fragments: 713
[download] Destination: Doctor Who, Series 3, The Shakespeare Code-b0071xzn.fmf_cloudfront-audio_eng_1=128000-1.m4a
[download]  46.7% of ~42.22MiB at  2.38MiB/s ETA 03:10    [download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 334 (attempt 1 of 10)...
[download]  73.6% of ~42.26MiB at  1.14MiB/s ETA 02:20    ERROR: unable to download video data: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1287, in connect
  File "C:\Python\Python34\lib\ssl.py", line 362, in wrap_socket
  File "C:\Python\Python34\lib\ssl.py", line 580, in __init__
  File "C:\Python\Python34\lib\ssl.py", line 807, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\YoutubeDL.py", line 1961, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\YoutubeDL.py", line 1906, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\downloader\dash.py", line 48, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\downloader\fragment.py", line 104, in _download_fragment
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\downloader\http.py", line 351, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\downloader\http.py", line 116, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\downloader\http.py", line 110, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\YoutubeDL.py", line 2279, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\utils.py", line 2736, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>
```

## Description

This error always pops up eventually when trying to download from the BBC iPlayer, can be either single episode links or playlist as used here. I am using a VPN to bypass the geolock and I have not tried any other sites.

An additional issue is the 403 errors popping up but I am unsure how relevant those are to this issue.

**Comment by macr2hoyipbjtn** [comment]
DRM? Last I checked, the DASH streams were using some sort of encryption with the key supplied.

**Comment by Zettexe** [comment]
It does work sometimes if you try downloading the link multiple times so its not permanently blocked

**Comment by dirkf** [comment]
The 403 errors used to be typical but I thought they'd disappeared with the switch to v6 JSON playlists at the end of 2020. They didn't appear with my test run from the UK. The current version seems to pick up the episodes without the 403s.

You seem to have had a networking error perhaps related to a VPN, or to interference with it at one end or the other, which is causing the HTTPS connection to fail to be established.  The error at `_ssl.c:600` comes from negotiating the SSL connection, or, rather, failing to do so.

**Comment by Lyoko-Jeremie** [comment]
@dirkf Yes, i face the same error.
but i think need retry when it happend, but it not.

**Comment by Lyoko-Jeremie** [comment]
```
> youtube-dl.exe --proxy "socks5://127.0.0.1:5000/"  --retries infinite --fragment-retries infinite -f "bestvideo+bestaudio/best" --cookies "cookies.txt" --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefo
x/83.0" -o "\\192.168.137.164\data_root6\downloadedData\ytb\%(title)s.%(ext)s" -v "https://www.youtube.com/watch?v=spxtEt6RaS4"                                                                                                                 
[debug] System config: []                                                                                                                                                                                                                       
[debug] User config: []                                                                                                                                                                                                                         
[debug] Custom config: []                                                                                                                                                                                                                       
[debug] Command-line args: ['--proxy', 'socks5://127.0.0.1:5000/', '--retries', 'infinite', '--fragment-retries', 'infinite', '-f', 'bestvideo+bestaudio/best', '--cookies', 'cookies.txt', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64
; x64; rv:83.0) Gecko/20100101 Firefox/83.0', '-o', '\\\\192.168.137.164\\data_root6\\downloadedData\\ytb\\%(title)s.%(ext)s', '-v', 'https://www.youtube.com/watch?v=spxtEt6RaS4']                                                             
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936                                                                                                                                                                                 
[debug] youtube-dl version 2021.06.06                                                                                                                                                                                                           
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041                                                                                                                                                                                  
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-full_build-www.gyan.dev                                                                                                                         
[debug] Proxy map: {'http': 'socks5://127.0.0.1:5000/', 'https': 'socks5://127.0.0.1:5000/'}                                                                                                                                                    
[youtube] spxtEt6RaS4: Downloading webpage                                                                                                                                                                                                      
[debug] Invoking downloader on 'https://r2---sn-a5meknzr.googlevideo.com/videoplayback?expire=1631736914&ei=8v9BYaK5Fo2Hkwb_9rLABQ&ip=155.94.151.16&id=o-AGwCrySFlQXldwhmtGkFHpg2vJ9tV4xsMInnSQqBNUTL&itag=313&aitags=133%2C134%2C135%2C136%2C13
7%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313&source=youtube&requiressl=yes&mh=kH&mm=31%2C29&mn=sn-a5meknzr%2Csn-a5mlrn7d&ms=au%2Crdu&mv=m&mvi=2&pl=24&initcwndbps=1212500&vprv=1&mime=video%2Fwebm&ns=9KMuSI89MJ1agAwI3ouhTlQG&gir=ye
s&clen=81878394895&dur=40311.687&lmt=1616020531284211&mt=1631714945&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5532432&n=gtjc8608dWppd6yY&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cc
len%2Cdur%2Clmt&sig=AOq0QJ8wRAIgG9VI8ZOvbS-jqZwb_iKzNkv7oNoxXjQuIzQdqg_YhbwCIDbI_Q3jPPGXx7jYlkw4vfKEXA4Uz0G96xd3JIPb3-3M&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgXpAuIg7zbMYSdLyHZnUHflyKq28-cdhaIeCUoktRgOYCI
BbUMIKxgukuCp8HLn4QqjHTOTgIlXYq8RoGNLJZ4xfa'                                                                                                                                                                                                    
[download] Resuming download at byte 73177940392                                                                                                                                                                                                
[download] Destination: \\192.168.137.164\data_root6\downloadedData\ytb\11HRS of 4K Turtle Paradise - Undersea Nature Relaxation Film + Meditation Music by Jason Stephenson.f313.webm                                                          
[download]  90.0% of 76.26GiB at  1.15MiB/s ETA 01:53:01      ERROR: unable to download video data: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>                                                                          
Traceback (most recent call last):                                                                                                                                                                                                              
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open                                                                                                                                                                        
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request                                                                                                                                                                           
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request                                                                                                                                                                     
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders                                                                                                                                                                        
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output                                                                                                                                                                       
  File "C:\Python\Python34\lib\http\client.py", line 898, in send                                                                                                                                                                               
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\utils.py", line 2708, in connect                                                                                                            
  File "C:\Python\Python34\lib\ssl.py", line 362, in wrap_socket                                                                                                                                                                                
  File "C:\Python\Python34\lib\ssl.py", line 580, in __init__                                                                                                                                                                                   
  File "C:\Python\Python34\lib\ssl.py", line 807, in do_handshake                                                                                                                                                                               
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:600)                                                                                                                                                                             
                                                                                                                                                                                                                                                
During handling of the above exception, another exception occurred:                                                                                                                                                                             
                                                                                                                                                                                                                                                
Traceback (most recent call last):                                                                                                                                                                                                              
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 1970, in process_info                                                                                                   
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 1915, in dl                                                                                                             
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\downloader\common.py", line 366, in download                                                                                                
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\downloader\http.py", line 351, in real_download                                                                                             
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\downloader\http.py", line 116, in establish_connection                                                                                      
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\downloader\http.py", line 110, in establish_connection                                                                                      
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen                                                                                                        
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open                                                                                                                                                                            
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open                                                                                                                                                                           
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain                                                                                                                                                                     
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\utils.py", line 2737, in https_open                                                                                                         
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open                                                                                                                                                                        
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>                                                                                                                                                       
```
