### ISSUE TITLE
No video format found

### ISSUE THREAD

**Issue by geiras** [ytdl-org/youtube-dl#28599]
youtube-dl https://cdnapisec.kaltura.com/p/2723521/sp/272352100/playManifest/entryId/1_hdokzqdc/protocol/https/format/mpegdash/flavorIds/1_vb2hqto8,1_6nx5nygi,1_qetc3jdo,1_g6xs8ugj,1_lnwz8m2r,1_5gva7en1/a.mpd

**Comment by geiras** [comment]
```
youtube-dl https://cdnapisec.kaltura.com/p/2723521/sp/272352100/playManifest/entryId/1_hdokzqdc/protocol/https/format/mpegdash/flavorIds/1_vb2hqto8,1_6nx5nygi,1_qetc3jdo,1_g6xs8ugj,1_lnwz8m2r,1_5gva7en1/a.mpd --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://cdnapisec.kaltura.com/p/2723521/sp/272352100/playManifest/entryId/1_hdokzqdc/protocol/https/format/mpegdash/flavorIds/1_vb2hqto8,1_6nx5nygi,1_qetc3jdo,1_g6xs8ugj,1_lnwz8m2r,1_5gva7en1/a.mpd', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.25
[debug] Python version 3.9.2 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2
[debug] Proxy map: {}
[generic] a: Requesting header
[redirect] Following redirect to https://cfvod.kaltura.com/edash/p/2723521/sp/272352100/serveFlavor/entryId/1_hdokzqdc/v/11/ev/13/flavorId/1_,vb2hqto8,6nx5nygi,qetc3jdo,g6xs8ugj,lnwz8m2r,5gva7en1,/forceproxy/true/name/a.mp4.urlset/manifest.mpd
[generic] manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest: Downloading webpage
[generic] manifest: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.3.25/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.3.25/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.3.25/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.3.25/libexec/lib/python3.9/site-packages/youtube_dl/extractor/generic.py", line 2519, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "/usr/local/Cellar/youtube-dl/2021.3.25/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1369, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by llacb47** [comment]
DRM. Check the mpd before filing pointless issues.

**Comment by geiras** [comment]
@remitamine, I'm sorry for filing pointless issues.

I don't have enough knowledge to read the mpd and understand it was due to DRM and I just followed the advice given on the console to file a bug report.

Again, sorry for the pointless issue that I opened. 🙏
