### ISSUE TITLE
Unable to extract player URL & No video formats found

### ISSUE THREAD

**Issue by mohammadmomeni** [ytdl-org/youtube-dl#28605]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.03.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.31
[debug] Python version 3.7.10 (CPython) - Linux-3.10.0-962.3.2.lve1.5.49.el7.x86_64-x86_64-with-glibc2.2.5
[debug] exe versions: none
[debug] Proxy map: {}
[download] Downloading playlist: ('drake',) Pain 1993 (with Playboi Carti)
[youtube:search] query "('drake',) Pain 1993 (with Playboi Carti)": Downloading page 1
[youtube:search] playlist ('drake',) Pain 1993 (with Playboi Carti): Downloading 1 videos
[download] Downloading video 1 of 1
[youtube] Q5jnuOCJvK0: Downloading webpage
[youtube] Q5jnuOCJvK0: Downloading API JSON
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1661, in _real_extract
    self._sort_formats(formats)
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1369, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Traceback (most recent call last):
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1661, in _real_extract
    self._sort_formats(formats)
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1369, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "create.py", line 227, in <module>
    if confirm == "": create.artistWithAlbumsAndTracks(ready[0])
  File "create.py", line 180, in artistWithAlbumsAndTracks
    self.multipleAlbums(albums)
  File "create.py", line 120, in multipleAlbums
    self.downloadTracks()
  File "create.py", line 165, in downloadTracks
    mode=self.modeContainer)
  File "/home/neodiomc/Python/v1/download.py", line 291, in multipleTracks
    artistName, requestedTracks=listOfNeodiomTracksDicts)
  File "/home/neodiomc/Python/v1/download.py", line 316, in availableTracksForDownload
    artistName, requestedTracks)
  File "/home/neodiomc/Python/v1/download.py", line 91, in availableTracksFor
    self.track(track)
  File "/home/neodiomc/Python/v1/download.py", line 43, in track
    result = ydl.extract_info(q, download=download)
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 799, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 838, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 924, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1058, in __process_playlist
    entry_result = self.__process_iterable_entry(entry, download, extra)
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1068, in __process_iterable_entry
    entry, download=download, extra_info=extra_info)
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 884, in process_ie_result
    extra_info=extra_info, download=False, process=False)
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 799, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "/home/neodiomc/virtualenv/Python/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Here's my options :
``` python
  q = f"ytsearch{number}:{search}" # q = ('drake',) Pain 1993 (with Playboi Carti)

  with YoutubeDL({'source_address': '0.0.0.0', 'verbose': True}) as ydl:
      result = ydl.extract_info(q, download=False)
```

**Comment by mohammadmomeni** [comment]
@remitamine I did not find any **exact** duplicate issue and naturally the solution for this problem , could you please tag/mention the duplicates that are closed and helpful ?

**Comment by mohammadmomeni** [comment]
Solution for now : https://github.com/ytdl-org/youtube-dl/issues/28602#issuecomment-811385668
