### ISSUE TITLE
sporadic error: Unable to extract yt initial data

### ISSUE THREAD

**Issue by buzo-ffm** [ytdl-org/youtube-dl#28602]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

Similar to #28585 – I'm in Europe (Germany) too.

## Verbose log

```
$ youtube-dl -v --playlist-end 2 https://www.youtube.com/c/ClashOfClans/videos
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--playlist-end', '2', 'https://www.youtube.com/c/ClashOfClans/videos']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.31
[debug] Python version 3.9.2 (CPython) - Linux-5.11.10-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] ClashOfClans: Downloading webpage
ERROR: Unable to extract yt initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 2694, in _real_extract
    data = self._extract_yt_initial_data(item_id, webpage)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 284, in _extract_yt_initial_data
    self._search_regex(
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract yt initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

In about every second/third try, the above command fails as shown above. So in order to download successfully, I have to execute this command a few times. It doesn't seem to matter which playlist is given – it happens with a lot of them.

This looks like #28585: I'm in Europe (Germany) too. But that one is closed already – too early IMHO.

**Comment by fobin** [comment]
I've also started to see this recently. I'm from Finland.

**Comment by veikk0** [comment]
I'm experiencing this too, and I'm in Finland as well.

Things were fine as I was downloading a playlist this morning (I terminated the download early), but now that I tried to continue the download I'm getting the same issue that's being reported here multiple times.

Other report for the same issue, it seems: #28604 #28605 #28600

I've updated to the latest version available from pip. Here's my command, and the output:
```
youtube-dl -f 397+251/244+251 --playlist-start=30 --verbose -o "%(playlist_index)s-%(title)s.%(ext)s" https://www.youtube.com/playlist?list=PLlZm75oytJByjuDh6nTCVNTMEdanLFumA
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '397+251/244+251', '--playlist-start=30', '--verbose', '-o', '%(playlist_index)s-%(title)s.%(ext)s', 'https://www.youtube.com/playlist?list=PLlZm75oytJByjuDh6nTCVNTMEdanLFumA']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.31
[debug] Python version 3.8.5 (CPython) - Linux-5.8.0-44-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg N-101778-g84ac35e, ffprobe N-101778-g84ac35e
[debug] Proxy map: {}
[youtube:tab] PLlZm75oytJByjuDh6nTCVNTMEdanLFumA: Downloading webpage
ERROR: Unable to extract yt initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/veikk0/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/home/veikk0/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/home/veikk0/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/veikk0/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 2694, in _real_extract
    data = self._extract_yt_initial_data(item_id, webpage)
  File "/home/veikk0/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 284, in _extract_yt_initial_data
    self._search_regex(
  File "/home/veikk0/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract yt initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by tameTNT** [comment]
I'm getting the same error in the UK after just updating to latest.

**Comment by buzo-ffm** [comment]
@dstftw Why are you closing this bug?

Today it failed for me in 95% of the tries. After editing the cookie file (passed with the `--cookies` option) to include this line

> `.youtube.com TRUE / FALSE 2145916800 CONSENT YES+DE.de`

… it worked for me again. This workaround could be added to _youtube-dl_, couldn't it?

**Comment by dstftw** [comment]
> @dstftw Why are you closing this bug?
> 
> Today it failed for me in 95% of the tries. After editing the cookie file (passed with the `--cookies` option) to include this line
> 
> > `.youtube.com TRUE / FALSE 2145916800 CONSENT YES+DE.de`
> 
> … it worked for me again. This workaround could be added to _youtube-dl_, couldn't it?

It's already fixed. Bothet to check releases.
