### ISSUE TITLE
[File name too long] Need way of preserving video names

### ISSUE THREAD

**Issue by gabefair** [ytdl-org/youtube-dl#28626]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.04.01**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl -v --embed-subs --embed-thumbnail --add-metadata --fixup warn --download-archive
 archive.txt -i --yes-playlist --include-ads --console-title -o "%(uploader)s/%(id)s-%(title)s-%(upload_date)s.%(ext)s" "https://www.youtube.com/playlist?lis
t=UUeqUUXaM75wrK5Aalo6UorQ&playnext=1&index=1" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--embed-subs', '--embed-thumbnail', '--add-metadata', '--fixup', 'warn', '--download-archive', 'archive.txt', '-i', '--yes-playlist', '--include-ads', '--console-title', '-o', '%(uploader)s/%(id)s-%(title)s-%(upload_date)s.%(ext)s', 'https://www.youtube.com/playlist?list=UUeqUUXaM75wrK5Aalo6UorQ&playnext=1&index=1', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.01
[debug] Python version 3.8.5 (CPython) - Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube:tab] UUeqUUXaM75wrK5Aalo6UorQ: Downloading webpage
[youtube:tab] UUeqUUXaM75wrK5Aalo6UorQ: Downloading webpage
[download] Downloading playlist: Uploads from 蘋果動新聞 HK Apple Daily
[youtube:tab] Downloading page 1
...
[youtube:tab] Downloading page 199
[youtube:tab] playlist Uploads from 蘋果動新聞 HK Apple Daily: Downloading 19998 videos
[download] Downloading video 1 of 19998
[youtube] vHFYxV9DrdM: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[youtube] vHFYxV9DrdM: Downloading thumbnail ...
WARNING: Unable to download thumbnail "https://i.ytimg.com/vi/vHFYxV9DrdM/maxresdefault.jpg": [Errno 36] File name too long: '蘋果動新聞 HK Apple Daily/vHFYxV9DrdM-9點半蘋果新聞報道 字幕版重溫（2021年3月31日）︱李宇軒被安排非家屬委託大狀代表︱美國強烈譴責中方進一步削弱港人民意代表︱艾未未斥容海恩「極端納粹」︱蘋 果日報 Apple Daily #香港新聞-20210331.jpg'
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r7---sn-8xgp1vo-p5ql.googlevideo.com/videoplayback?expire=1617308641&ei=gddlYOrjJqmP8gTRorXYAg&ip=108.18.207.69&id=o-AM_ozfE2p3R1kP3JDvh7aeQjAe6e_-zws77dXIaI4axW&itag=303&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303&source=youtube&requiressl=yes&mh=fi&mm=31%2C29&mn=sn-8xgp1vo-p5ql%2Csn-p5qlsndr&ms=au%2Crdu&mv=m&mvi=7&pl=16&initcwndbps=1590000&vprv=1&mime=video%2Fwebm&ns=uR_LffjyC7uPm-0vI7BL054F&gir=yes&clen=571971182&dur=1865.240&lmt=1617235882900838&mt=1617286849&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5535432&n=ZcyIwSaFZeS8hU_MY&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgb2AuvrM1uJSXYjg8J9_Hgigv9OynLexSab9Gx98K2p0CIQDZGy27s6U7gE4ZSCHPIvULg2iUC0klKz0zfr20mAhX8A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAO2q5w4Fr6-NUq2PPjm8EpNbtkLNSb-hX6XVUVLGwtzZAiAVmt7aUzt8AflDrfHysgL7DoAdPMe6YsZcMLHpKsJLLw%3D%3D'
ERROR: unable to open for writing: [Errno 36] File name too long: '蘋果動新聞 HK Apple Daily/vHFYxV9DrdM-9點半蘋果新聞報道 字幕版重溫（2021年3月31日）︱李宇 軒被安排非家屬委託大狀代表︱美國強烈譴責中方進一步削弱港人民意代表︱艾未未斥容海恩「極端納粹」︱蘋果日報 Apple Daily #香港新聞-20210331.f303.webm.part'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 259, in download
    ctx.stream, ctx.tmpfilename = sanitize_open(
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2054, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
OSError: [Errno 36] File name too long: '蘋果動新聞 HK Apple Daily/vHFYxV9DrdM-9點半蘋果新聞報道 字幕版重溫（2021年3月31日）︱李宇軒被安排非家屬委託大狀代表 ︱美國強烈譴責中方進一步削弱港人民意代表︱艾未未斥容海恩「極端納粹」︱蘋果日報 Apple Daily #香港新聞-20210331.f303.webm.part'

[debug] Invoking downloader on 'https://r7---sn-8xgp1vo-p5ql.googlevideo.com/videoplayback?expire=1617308641&ei=gddlYOrjJqmP8gTRorXYAg&ip=108.18.207.69&id=o-AM_ozfE2p3R1kP3JDvh7aeQjAe6e_-zws77dXIaI4axW&itag=140&source=youtube&requiressl=yes&mh=fi&mm=31%2C29&mn=sn-8xgp1vo-p5ql%2Csn-p5qlsndr&ms=au%2Crdu&mv=m&mvi=7&pl=16&initcwndbps=1590000&vprv=1&mime=audio%2Fmp4&ns=uR_LffjyC7uPm-0vI7BL054F&gir=yes&clen=30188667&dur=1865.305&lmt=1617234250692576&mt=1617286849&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5531432&n=ZcyIwSaFZeS8hU_MY&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgZF6OYDFo5PyDgayz71A2ndm0VJmPvdPssTq0-F2NHOQCICoAQ_Csqbq56BMqaDUtDbjaSjr8f7DYIeA6DWcKYph_&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAO2q5w4Fr6-NUq2PPjm8EpNbtkLNSb-hX6XVUVLGwtzZAiAVmt7aUzt8AflDrfHysgL7DoAdPMe6YsZcMLHpKsJLLw%3D%3D'
ERROR: unable to open for writing: [Errno 36] File name too long: '蘋果動新聞 HK Apple Daily/vHFYxV9DrdM-9點半蘋果新聞報道 字幕版重溫（2021年3月31日）︱李宇 軒被安排非家屬委託大狀代表︱美國強烈譴責中方進一步削弱港人民意代表︱艾未未斥容海恩「極端納粹」︱蘋果日報 Apple Daily #香港新聞-20210331.f140.m4a.part'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 259, in download
    ctx.stream, ctx.tmpfilename = sanitize_open(
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2054, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
OSError: [Errno 36] File name too long: '蘋果動新聞 HK Apple Daily/vHFYxV9DrdM-9點半蘋果新聞報道 字幕版重溫（2021年3月31日）︱李宇軒被安排非家屬委託大狀代表 ︱美國強烈譴責中方進一步削弱港人民意代表︱艾未未斥容海恩「極端納粹」︱蘋果日報 Apple Daily #香港新聞-20210331.f140.m4a.part'
```

## Description

Example URL: `https://www.youtube.com/watch?v=DAO2peb3t5g`

**What the problem is**:  _Currently video is skipped if the filename is too long. Video titles in non-Latin characters often exceed the 256 character limit. No fallback option when filename is too long._

**How it could be fixed**:  _I am not an expert, but one option is to provide a parameter to write video title to text file if a "file name is too long" error occurs._

**How your proposed solution would look like**: `--write-title-to-text-archive ON-ERROR`

**Comment by october262** [comment]
try again with youtube-dl -o '%(title).50s-%(id)s.%(ext)s' "https://www.youtube.com/watch?v=DAO2peb3t5g"

**Comment by gabefair** [comment]
This works. Thank you
