### ISSUE TITLE
Error converting subtitles when language is not available

### ISSUE THREAD

**Issue by DADi590** [ytdl-org/youtube-dl#28632]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --no-overwrites --format "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --write-thumbnail --restrict-filenames --output "%(upload_date)s - %(title)s/%(id)s; %(view_count)s; %(comment_count)s; %(like_count)s vs %(dislike_count)s.%(ext)s" --write-description --write-info-json --write-annotations --no-continue --write-sub --write-auto-sub --sub-format "srt/best" --console-title --sub-lang pt,en --retries infinite --fragment-retries infinite --convert-subs srt --fixup detect_or_warn --ffmpeg-location "C:\FFmpeg\bin" --verbose "https://www.youtube.com/watch?v=tdszvDemgcg&list=PLZ4bp4FXracIkjcxbEb5N1s8opR0NqeXr
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-overwrites', '--format', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--write-thumbnail', '--restrict-filenames', '--output', '%(upload_date)s - %(title)s/%(id)s; %(view_count)s; %(comment_count)s; %(like_count)s vs %(dislike_count)s.%(ext)s', '--write-description', '--write-info-json', '--write-annotations', '--no-continue', '--write-sub', '--write-auto-sub', '--sub-format', 'srt/best', '--console-title', '--sub-lang', 'pt,en', '--retries', 'infinite', '--fragment-retries', 'infinite', '--convert-subs', 'srt', '--fixup', 'detect_or_warn', '--ffmpeg-location', 'C:\\FFmpeg\\bin', '--verbose', 'https://www.youtube.com/watch?v=tdszvDemgcg&list=PLZ4bp4FXracIkjcxbEb5N1s8opR0NqeXr']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.04.01
[debug] Python version 3.9.2 (CPython) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg 2021-03-09-git-c35e456f54-essentials_build-www.gyan.dev, ffprobe 2021-03-09-git-c35e456f54-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[youtube:tab] Downloading playlist PLZ4bp4FXracIkjcxbEb5N1s8opR0NqeXr - add --no-playlist to just download video tdszvDemgcg
[youtube:tab] PLZ4bp4FXracIkjcxbEb5N1s8opR0NqeXr: Downloading webpage
[youtube:tab] PLZ4bp4FXracIkjcxbEb5N1s8opR0NqeXr: Downloading webpage
[download] Downloading playlist: Rework & Repair Lessons - Portuguese
[youtube:tab] playlist Rework & Repair Lessons - Portuguese: Downloading 8 videos
[download] Downloading video 1 of 8
[youtube] tdszvDemgcg: Downloading webpage
[info] Writing video description to: 20140708 - PACE_Rework_Repair_Lesson_PORTUGUESE_-_Introduction\tdszvDemgcg; 362; NA; 5 vs 0.description
WARNING: There are no annotations to write.
[info] Writing video subtitles to: 20140708 - PACE_Rework_Repair_Lesson_PORTUGUESE_-_Introduction\tdszvDemgcg; 362; NA; 5 vs 0.pt.vtt
[info] Writing video subtitles to: 20140708 - PACE_Rework_Repair_Lesson_PORTUGUESE_-_Introduction\tdszvDemgcg; 362; NA; 5 vs 0.en.vtt
WARNING: Unable to download subtitle for "en": Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[info] Writing video description metadata as JSON to: 20140708 - PACE_Rework_Repair_Lesson_PORTUGUESE_-_Introduction\tdszvDemgcg; 362; NA; 5 vs 0.info.json
[youtube] tdszvDemgcg: Downloading thumbnail ...
[youtube] tdszvDemgcg: Writing thumbnail to: 20140708 - PACE_Rework_Repair_Lesson_PORTUGUESE_-_Introduction\tdszvDemgcg; 362; NA; 5 vs 0.jpg
[debug] Invoking downloader on 'https://r2---sn-8vq54vox2u-apnz.googlevideo.com/videoplayback?expire=1617327054&ei=bh9mYIenLcOumLAPwIiFyAE&ip=95.136.53.112&id=o-APYjHS6m2jDpdjxCr0tFltT0jAcLaYIXyDkJPm5PAbeU&itag=135&aitags=133%2C134%2C135%2C160%2C242%2C243%2C244%2C278&source=youtube&requiressl=yes&mh=79&mm=31%2C29&mn=sn-8vq54vox2u-apnz%2Csn-8vq54vox2u-apns&ms=au%2Crdu&mv=m&mvi=2&pl=19&pcm2=no&initcwndbps=1783750&vprv=1&mime=video%2Fmp4&ns=PJ1jBROSGcYUyIanEbwESW8F&gir=yes&clen=63162621&dur=767.533&lmt=1404855422549045&mt=1617305091&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&n=oaYNsw0cM0KGXzlT_&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOg0TaRYWPhvrHnSf38M9NeGc_qAhXhQt9pmHYPB4pxRAiEAlNl3AL0RD9hf6DAUE1CgSiOd1T2Np-Qbstslihfd0hY%3D&sig=AOq0QJ8wRAIgNLNbAsipbTALrOzUPnsJtHBRlJ0ctC0NHlfRH6nOC2ECIHNWAinR_8xnnqOf-g0R6-0Um2gzYVolXhZfoe4UgRRJ'
[download] Destination: 20140708 - PACE_Rework_Repair_Lesson_PORTUGUESE_-_Introduction\tdszvDemgcg; 362; NA; 5 vs 0.f135.mp4
[download] 100% of 60.24MiB in 00:11
[debug] Invoking downloader on 'https://r2---sn-8vq54vox2u-apnz.googlevideo.com/videoplayback?expire=1617327054&ei=bh9mYIenLcOumLAPwIiFyAE&ip=95.136.53.112&id=o-APYjHS6m2jDpdjxCr0tFltT0jAcLaYIXyDkJPm5PAbeU&itag=140&source=youtube&requiressl=yes&mh=79&mm=31%2C29&mn=sn-8vq54vox2u-apnz%2Csn-8vq54vox2u-apns&ms=au%2Crdu&mv=m&mvi=2&pl=19&pcm2=no&initcwndbps=1783750&vprv=1&mime=audio%2Fmp4&ns=PJ1jBROSGcYUyIanEbwESW8F&gir=yes&clen=12323682&dur=767.604&lmt=1404855419654880&mt=1617305091&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&n=oaYNsw0cM0KGXzlT_&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgV_m8dx6YQIlXMnduOX8CBOgmHYI8B3CxBAkAbiJ9lQMCIEUSqC_XXzgHmgZsz5HxJBry-Wxj3HLl38ult9cu9aLq&sig=AOq0QJ8wRQIhAJbDfKIEOtSSEWkR0410zd7eNkdLN8Kkw0ONSvqVlya9AiBu9XaOMSvxcrRqXCaRcz5u356doBG6x7K9mekgob27HA=='
[download] Destination: 20140708 - PACE_Rework_Repair_Lesson_PORTUGUESE_-_Introduction\tdszvDemgcg; 362; NA; 5 vs 0.f140.m4a
[download] 100% of 11.75MiB in 00:02
[ffmpeg] Merging formats into "20140708 - PACE_Rework_Repair_Lesson_PORTUGUESE_-_Introduction\tdszvDemgcg; 362; NA; 5 vs 0.mp4"
[debug] ffmpeg command line: "C:\FFmpeg\bin\ffmpeg" -y -loglevel "repeat+info" -i "file:20140708 - PACE_Rework_Repair_Lesson_PORTUGUESE_-_Introduction\tdszvDemgcg; 362; NA; 5 vs 0.f135.mp4" -i "file:20140708 - PACE_Rework_Repair_Lesson_PORTUGUESE_-_Introduction\tdszvDemgcg; 362; NA; 5 vs 0.f140.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:20140708 - PACE_Rework_Repair_Lesson_PORTUGUESE_-_Introduction\tdszvDemgcg; 362; NA; 5 vs 0.temp.mp4"
Deleting original file 20140708 - PACE_Rework_Repair_Lesson_PORTUGUESE_-_Introduction\tdszvDemgcg; 362; NA; 5 vs 0.f135.mp4 (pass -k to keep)
Deleting original file 20140708 - PACE_Rework_Repair_Lesson_PORTUGUESE_-_Introduction\tdszvDemgcg; 362; NA; 5 vs 0.f140.m4a (pass -k to keep)
[ffmpeg] Converting subtitles
[debug] ffmpeg command line: "C:\FFmpeg\bin\ffmpeg" -y -loglevel "repeat+info" -i "file:20140708 - PACE_Rework_Repair_Lesson_PORTUGUESE_-_Introduction\tdszvDemgcg; 362; NA; 5 vs 0.pt.vtt" -f srt "file:20140708 - PACE_Rework_Repair_Lesson_PORTUGUESE_-_Introduction\tdszvDemgcg; 362; NA; 5 vs 0.pt.srt"
Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\youtube-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\__init__.py", line 475, in main
    _real_main(argv)
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 2059, in download
    res = self.extract_info(
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 799, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 838, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 876, in process_ie_result
    return self.extract_info(ie_result['url'],
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 799, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 838, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 924, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 1058, in __process_playlist
    entry_result = self.__process_iterable_entry(entry, download, extra)
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 1067, in __process_iterable_entry
    return self.process_ie_result(
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 909, in process_ie_result
    return self.process_ie_result(
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 872, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 1683, in process_video_result
    self.process_info(new_info)
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 2041, in process_info
    self.post_process(filename, info_dict)
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 2106, in post_process
    files_to_delete, info = pp.run(info)
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 649, in run
    self.run_ffmpeg(old_file, new_file, ['-f', new_format])
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 239, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 209, in run_ffmpeg_multiple_files
    oldest_mtime = min(
  File "C:\Users\DADi590\AppData\Roaming\Python\Python39\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 210, in <genexpr>
    os.stat(encodeFilename(path)).st_mtime for path in input_paths)
FileNotFoundError: [WinError 2] O sistema não conseguiu localizar o ficheiro especificado: '20140708 - PACE_Rework_Repair_Lesson_PORTUGUESE_-_Introduction\\tdszvDemgcg; 362; NA; 5 vs 0.en.vtt'
```

## Description

On [this video](https://www.youtube.com/watch?v=tdszvDemgcg), there are no subtitle languages other than Portuguese (Portugal) ones.
Still, in a general command I have for downloading videos always with the same format, I have there to attemp to download EN and PT subtitles. In case it can't, it shouldn't attempt to do anything on them. But seems it's still trying to convert the EN subtitles, even when they were not downloaded, since they don't exist in the first place. Can this be fixed?

Thank you.

**Comment by DJviolin** [comment]
Confirming I have the same issue since the latest updates. I run youtube-dl with the following command:
```sh
"C:\youtube-dl\youtube-dl.exe" -o "E:\youtube-dl\%(playlist_index)s.%(title)s.f%(format_id)s.%(ext)s" --write-sub --write-auto-sub --sub-lang "hu,hun,hungarian,magyar,en,eng,english,de,deu,deutsch,ger,german,it,ita,italiano,italian,es,espanol,spa,spanish,fr,fra,francais,fre,french" --sub-format "srt/best" --embed-subs --add-metadata --embed-thumbnail --restrict-filenames -f "bestvideo+bestaudio/best" --merge-output-format mp4 --audio-format m4a --audio-quality 0 --prefer-ffmpeg --ffmpeg-location "C:\youtube-dl\ffmpeg\bin" "https://www.youtube.com/watch?v=aI6qN7JtVyY"
```

**Comment by DADi590** [comment]
It seems I can't reproduce the error anymore... The exact same command as above. It's downloading all videos and including all the subtitles. Not sure why it happened in the first place then. Does youtube-dl use a server to do things? Or it's all with local code? If it doesn't use any servers (aside from YouTube ones to get the videos from), then maybe YouTube did something there that messed this up? Weird.

I won't close the issue though, as it seems I wasn't the only one with the problem and I don't know if it's still happening with others (doesn't seem to be happening with me for now, at least).
