### ISSUE TITLE
[prosiebensat1] Audio not downloadable

### ISSUE THREAD

**Issue by Akamaru** [ytdl-org/youtube-dl#28638]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
akamaru@hakase:~/Festplatten/Entei/Downloads/720$ youtube-dl -v "https://www.prosieben.de/tv/joko-klaas-gegen-prosieben/video/41-joko-klaas-live-pflege-ist-nichtselbstverstaendlich-ganze-folge"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.prosieben.de/tv/joko-klaas-gegen-prosieben/video/41-joko-klaas-live-pflege-ist-nichtselbstverstaendlich-ganze-folge']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.01
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-206-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.17, ffprobe 2.8.17, rtmpdump 2.4
[debug] Proxy map: {}
[prosiebensat1] tv/joko-klaas-gegen-prosieben/video/41-joko-klaas-live-pflege-ist-nichtselbstverstaendlich-ganze-folge: Downloading webpage
[prosiebensat1] 6755423: Downloading videos JSON
[prosiebensat1] 6755423: Downloading protocols JSON
[prosiebensat1] 6755423: Downloading urls JSON
[prosiebensat1] 6755423: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[prosiebensat1] 6755423: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'http://vas-v4.p7s1video.net/4.0/playlist.m3u8?x=01&y=6PCxpZmGy9ZjNGUmPlZoxJpJ7IImO6vtWnsmieeB-mgNjlqHfKhM3DjZY6Y2aYm-BOmPDIrfx8COOSYtooCkgMx3w8I3k7196mIKYysl6etOgALbo1qzfquFUZcP9EmoDnHcISCxWeJ44-kAPg8DMgasFVmnp1VT8eI-dTtRtWMwUYwFb4PIOc5KmP_bEDF6EDbb6auu_qYoud00ON6IxT-bbacy6pwXEMFcGzwKH7JELQGop40EAFdPbRnG_5UIrT2tJzbsnKFHaSVLPzZ4uW5yFyA8Z27rll483t1gkkTeYpHTD6FVCgsI3QNvQdKlx4Bou1I8t-q2osDSoUDajm_qGYkIVwbUwoKpLR7L2YsyHSko4TsVCQfhpwQ9-LuBlVdUGjk-s1iqLV0dcjC95A'
[download] Joko & Klaas gegen ProSieben - Joko & Klaas LIVE - Pflege ist #NichtSelbstverständlich-6755423.fhls-3652.mp4 has already been downloaded
[download] 100% of 10.38GiB
[debug] Invoking downloader on u'http://vas-v4.p7s1video.net/4.0/playlist.m3u8?x=01&y=5ZqAMmNgUYceESDR_Gde-BhejHEwEJ4_qYavrrL-JNlrfEczHu8q-iYRmgnJUU68bFucK_Xfwu5ooa4oKR-FM4aG6y6Q3paZLMxlvaE2Ohlr6jrvYvGQZk2ps6aqkZJdXJy9szm9px5APLQbhnUgl1LKzQ0mUgzsuUrAqvd8Kjgb_byoCxf_T1WWBJpak4dQd80-MPY071YyJzWjlwi_uXSk-NwKVklN-hhIQ42hNusgmpGVOgrwpX7OOzbdiIpeXnaslTXXIt_sfIMqT6_r_sJspt09JTK8cKarMf5gh2BgOd3GpRnbEUPFU5zZ8XP6BVAIHkmC6p5Ri7_7YODaowYSvKTsiFeQl7z_kz5nZ-tPJokyFNCKrQl7OufVn0wuLIFMp0vEfpYroNszkVPL0w'
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1961, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1906, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 64, in real_download
    urlh = self.ydl.urlopen(self._prepare_url(info_dict, man_url))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2279, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

```

## Description

I try to download this video from prosieben.de: https://www.prosieben.de/tv/joko-klaas-gegen-prosieben/video/41-joko-klaas-live-pflege-ist-nichtselbstverstaendlich-ganze-folge
The video downloaded without problem, but not the audio. I tryed -F option and it shows
```
akamaru@hakase:~/Festplatten/Entei/Downloads/720$ youtube-dl -F "https://www.prosieben.de/tv/joko-klaas-gegen-prosieben/video/41-joko-klaas-live-pflege-ist-nichtselbstverstaendlich-ganze-folge"
[prosiebensat1] tv/joko-klaas-gegen-prosieben/video/41-joko-klaas-live-pflege-ist-nichtselbstverstaendlich-ganze-folge: Downloading webpage
[prosiebensat1] 6755423: Downloading videos JSON
[prosiebensat1] 6755423: Downloading protocols JSON
[prosiebensat1] 6755423: Downloading urls JSON
[prosiebensat1] 6755423: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[prosiebensat1] 6755423: Downloading m3u8 information
[info] Available formats for 6755423:
format code         extension  resolution note
hls-audio0-default  mp4        audio only
hls-415             mp4        640x360     415k , avc1.4d401e, 25.0fps, video only
hls-565             mp4        640x360     565k , avc1.4d401e, 25.0fps, video only
hls-915             mp4        768x432     915k , avc1.4d401e, 25.0fps, video only
hls-1264            mp4        768x432    1264k , avc1.4d401e, 25.0fps, video only
hls-2659            mp4        1024x576   2659k , avc1.4d401f, 25.0fps, video only
hls-3652            mp4        1280x720   3652k , avc1.4d401f, 25.0fps, video only
progressive         mp4        unknown    (best)
```
So I tryed "-f hls-audio0-default", but still I got the 404. On the website the video has audio.
The Video is 10gb big and 7h long. Could this be a problem?
Other Videos from prosieben.de are working as expected.

**Comment by macr2hoyipbjtn** [comment]
Reproduced. Seems like an issue with the extractor not extracting certain formats and extracting false ones. 

On an unrelated note, please update your OS with `sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade && reboot`. It's ancient.

**Comment by Akamaru** [comment]
I tried today again with the newest yt-dl version and it's working now.
Can someone confirm?

**Comment by Akamaru** [comment]
A friend of me told me it's working for him too. So I close this issue.
