### ISSUE TITLE
--console-title should check if the output is a TTY

### ISSUE THREAD

**Issue by gardenappl** [ytdl-org/youtube-dl#28651]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.01**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: ['-f', 'best[fps>30][height<=?768][ext=mp4]/bestvideo[fps>30][height<=?768][ext=mp4]+bestaudio/bestvideo[height<=?768][ext=mp4]+bestaudio/best[height<=?768][ext=mp4]/best[height<=?768]/bestvideo[height<=?768]+bestaudio/best/bestvideo+bestaudio']
[debug] User config: ['-f', 'best[fps>30][height<=?768][ext=mp4]/bestvideo[fps>30][height<=?768][ext=mp4]+bestaudio/bestvideo[height<=?768][ext=mp4]+bestaudio/best[height<=?768][ext=mp4]/best[height<=?768]/bestvideo[height<=?768]+bestaudio/best/bestvideo+bestaudio', '--console-title']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=xQ4KJF-6Agc', '--print-json', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.01
[debug] Python version 3.9.2 (CPython) - Linux-5.11.11-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, rtmpdump 2.4
[debug] Proxy map: {}
parse error: Invalid numeric literal at line 1, column 2
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2059, in download
    res = self.extract_info(
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 799, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 838, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 872, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 1683, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 1793, in process_info
    self.__forced_printings(info_dict, filename, incomplete=False)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 1765, in __forced_printings
    self.to_stdout(json.dumps(info_dict))
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 520, in to_stdout
    self._write_string(output, self._screen_file)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 509, in _write_string
    write_string(s, out=out, encoding=self.params.get('encoding'))
  File "/usr/lib/python3.9/site-packages/youtube_dl/utils.py", line 3180, in write_string
    out.buffer.write(byt)
BrokenPipeError: [Errno 32] Broken pipe



## Description

I use the `--print-json` option to pipe data into `jq`, and then parse it.

But then when I include `--console-title`, `youtube-dl` outputs escape sequences alongside the JSON data, causing `jq` to break because it does not receive valid JSON.

It would be nicer to just disable this option if stdout is not a TTY (or try redirecting to stderr instead)

**Comment by dirkf** [comment]
Currently (unix-like) the progress escape sequences go to `stdout`, or `stderr` when the downloaded file is sent to `stdout`. While this makes sense it doesn't help with your issue.

This patch to l.365-7 of `youtube_dl/__init__.py` should solve the issue (by sending the progress escape sequences to `stderr` in the quoted case):

```
         'noplaylist': opts.noplaylist,
-        'logtostderr': opts.outtmpl == '-',
+        'logtostderr': opts.outtmpl == '-' or opts.print_json,
         'consoletitle': opts.consoletitle,
```
Possibly the flags set by some other diagnostic options should be added to the list of `or`ed items.

**Comment by gardenappl** [comment]
That patch might be helpful, but `stderr` can also be redirected to a file that's not a terminal.

I think for terminal escape sequences it would make sense to explicitly check for `sys.stdout.isatty()` or `sys.stderr.isatty()`.

**Comment by dirkf** [comment]
That would be in line with what is done for some other terminal escape sequences, where a test like this is used:

```
if some_condition and compat_os_name != 'nt' and sys.stderr.isatty():
```
However, the console-title code (unix-like) uses the test `'TERM' in os.environ` rather than `isatty()`. Actually both tests might be needed: one tells whether the escape sequences should be understood, the other that they're actually going to a terminal.

So there are two issues:
* avoid mixing stuff written to `stdout` with logging, progress messages, etc, which the mod suggested above addresses;
* only send escape sequences to actual terminals, which needs the tests for `TERM` and `isatty()`.
