### ISSUE TITLE
CuriosityStream

### ISSUE THREAD

**Issue by ron-s** [ytdl-org/youtube-dl#28668]
## Checklist

- [ X] I'm reporting a broken site support
- [ X] I've verified that I'm running youtube-dl version **2021.04.01**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
c:\temp\youtubedl>youtube-dl -u username -p password --verbose -f best https://curiositystream.com/video/2127
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--verbose', '-f', 'best', 'https://curiositystream.com/video/2127']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] **youtube-dl version 2021.04.01**
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg 2021-04-04-git-b1b7cc698b-full_build-www.gyan.dev, ffprobe 2021-04-04-git-b1b7cc698b-full_build-www.gyan.dev
[debug] Proxy map: {}
[curiositystream] Downloading JSON metadata
[curiositystream] 2127: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\extractor\curiositystream.py", line 109, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\extractor\common.py", line 1369, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Starting today I began having issues viewing an available list of video formats for all videos. No issues yesterday. I've tried this using a local computer as well as an EC2 instance. both error out the same way.

I'm still able to manually detect an MPD file using the browser's web developer tools. For some reason youtube-dl 2021.04.01 and earlier are having issues, so I suspect they updated their API. 

In order to view videos with youtube-dl you need a username and password.

**Comment by ron-s** [comment]
`c:\temp\youtubedl>youtube-dl -u username -p password -F --verbose https://curiositystream.com/video/4134
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-F', '--verbose', 'https://curiositystream.com/video/4134']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.04.01
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg 2021-04-04-git-b1b7cc698b-full_build-www.gyan.dev, ffprobe 2021-04-04-git-b1b7cc698b-full_build-www.gyan.dev
[debug] Proxy map: {}
[curiositystream] Downloading JSON metadata
[curiositystream] 4134: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\extractor\curiositystream.py", line 109, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\extractor\common.py", line 1369, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`
