### ISSUE TITLE
--xattrs fails for certain attribute values if setfattr is used

### ISSUE THREAD

**Issue by Cebtenzzre** [ytdl-org/youtube-dl#28665]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl -v --xattrs 'https://www.youtube.com/watch?v=GbaPn5Yfk_U'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--xattrs', 'https://www.youtube.com/watch?v=GbaPn5Yfk_U']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.01
[debug] Python version 3.9.2 (CPython) - Linux-5.10.13-3-ck-patched-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] GbaPn5Yfk_U: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r4---sn-vgqsknee.googlevideo.com/videoplayback?expire=1617657643&ei=yyprYJiREI_IigTW54moCg&ip=2603%3A7081%3A3406%3A8f26%3Ae0f7%3A4814%3A3d49%3A3bb9&id=o-AMAUr6nhBqzUbQ-K54BmxZadf5HFOrPVGnIyeYiXP650&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=o5&mm=31%2C26&mn=sn-vgqsknee%2Csn-ab5sznlk&ms=au%2Conr&mv=m&mvi=4&pl=38&gcr=us&initcwndbps=1677500&vprv=1&mime=video%2Fmp4&ns=ksPNpcuSStp7hMJn4v3rMJAF&gir=yes&clen=9359173&dur=157.840&lmt=1609798081953406&mt=1617635817&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=2316222&n=W-75lt-5oHhCSFml8&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAOJRvJUbEHbl1ugk4RhhTCqY7Q-FUIuX4hVW28_UJzn4AiBuUNuj-Rve9uANmBxlIEwRd6YM32F0-Ook_5oBJcuN_Q%3D%3D&sig=AOq0QJ8wRQIhAI9zhiUFl3Z6DNU2y1phEOCtaFutJPAXjWf89H4g5jSbAiA70rkViUSpe3M2dfc0Qy6U7AhY1y8jRnAYhc6eehSx8Q=='
[download] Destination: 0xBAADF00D (What Are They Giving Us)-GbaPn5Yfk_U.f137.mp4
[download] 100% of 8.93MiB in 00:00
[debug] Invoking downloader on 'https://r4---sn-vgqsknee.googlevideo.com/videoplayback?expire=1617657643&ei=yyprYJiREI_IigTW54moCg&ip=2603%3A7081%3A3406%3A8f26%3Ae0f7%3A4814%3A3d49%3A3bb9&id=o-AMAUr6nhBqzUbQ-K54BmxZadf5HFOrPVGnIyeYiXP650&itag=251&source=youtube&requiressl=yes&mh=o5&mm=31%2C26&mn=sn-vgqsknee%2Csn-ab5sznlk&ms=au%2Conr&mv=m&mvi=4&pl=38&gcr=us&initcwndbps=1677500&vprv=1&mime=audio%2Fwebm&ns=ksPNpcuSStp7hMJn4v3rMJAF&gir=yes&clen=2585456&dur=157.861&lmt=1609798072241242&mt=1617635817&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=2311222&n=W-75lt-5oHhCSFml8&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANEwCgREVrikuidHs6wjtsiDNiJSEqWHBOVKERNZWEgoAiB9ORJ0VApAHDAOdAMldt_Rbl-T4qgWO03X3m28WTDS4A%3D%3D&sig=AOq0QJ8wRAIgazCCTXu_OPNj9BxuYe7cMr-16MuaescBkcbpj65OTEwCIHYSMPzUUnMoYTvBdZJq0jS2ym5n0Fd5g_3QHhfKODV_'
[download] Destination: 0xBAADF00D (What Are They Giving Us)-GbaPn5Yfk_U.f251.webm
[download] 100% of 2.47MiB in 00:00
[ffmpeg] Merging formats into "0xBAADF00D (What Are They Giving Us)-GbaPn5Yfk_U.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:0xBAADF00D (What Are They Giving Us)-GbaPn5Yfk_U.f137.mp4' -i 'file:0xBAADF00D (What Are They Giving Us)-GbaPn5Yfk_U.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:0xBAADF00D (What Are They Giving Us)-GbaPn5Yfk_U.temp.mkv'
Deleting original file 0xBAADF00D (What Are They Giving Us)-GbaPn5Yfk_U.f137.mp4 (pass -k to keep)
Deleting original file 0xBAADF00D (What Are They Giving Us)-GbaPn5Yfk_U.f251.webm (pass -k to keep)
[metadata] Writing metadata to file's xattrs
ERROR: This filesystem doesn't support extended attributes. (You may have to enable them in your /etc/fstab)
Traceback (most recent call last):
  File "/home/jared/.local/lib/python3.9/site-packages/youtube_dl/utils.py", line 5619, in write_xattr
    import xattr
ModuleNotFoundError: No module named 'xattr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jared/.local/lib/python3.9/site-packages/youtube_dl/postprocessor/xattrpp.py", line 55, in run
    write_xattr(filename, xattrname, byte_value)
  File "/home/jared/.local/lib/python3.9/site-packages/youtube_dl/utils.py", line 5682, in write_xattr
    raise XAttrMetadataError(p.returncode, stderr)
youtube_dl.utils.XAttrMetadataError: bad input encoding
```

## Description

Using the --xattrs option without the xattr module causes youtube-dl to execute setfattr. With certain videos (such as `https://www.youtube.com/watch?v=GbaPn5Yfk_U`), youtube-dl unhelpfully prints this error:
```
ERROR: This filesystem doesn't support extended attributes. (You may have to enable them in your /etc/fstab)
```

The problem is that youtube-dl is calling setfattr like this:
```
$ setfattr -n 'user.dublincore.title' -v '0xBAADF00D (What Are They Giving Us?)' '0xBAADF00D (What Are They Giving Us)-GbaPn5Yfk_U.mkv'
bad input encoding
$ echo $?
1
```

setfattr fails because it is trying to interpret the video's title as a hexadecimal number. From `man 1 setfattr`:
```
       -v value, --value=value
           Specifies the new value of the extended attribute. There are  three
           methods  available  for encoding the value.  If the given string is
           enclosed in double quotes, the inner string is treated as text.  In
           that  case, backslashes and double quotes have special meanings and
           need to be escaped by a preceding backslash. Any control characters
           can be encoded as a backslash followed by three digits as its ASCII
           code in octal. If the given string begins with 0x  or  0X,  it  ex‐
           presses a hexadecimal number. If the given string begins with 0s or
           0S, base64 encoding is expected.  Also see the --encoding option of
           getfattr(1).
```
<br>

One fix would be to simply enclose the value in double quotes, so it is interpreted as text (`"0xBAADF00D (What Are They Giving Us?)"`). That prevents the text from being interpreted as hex or base64, but would require backslashes and double quotes in the value to be escaped. The best option is probably to use the `--raw` flag, so the value is not decoded at all. From `man 1 setfattr`:
```
       --raw
           Do  not  decode  the attribute value. Can be used to set values ob‐
           tained with getfattr --only-values.
```
`--raw` has been supported since attr v2.4.48 released in 2017 (added in commit [c252ef4](https://git.savannah.nongnu.org/cgit/attr.git/commit/?id=c252ef434219891f616d891b46aad6b06efdd185)).

**Comment by dirkf** [comment]
Something like this would avoid a dependency on the version of `setfattr`:

utils.py l.5662-6
```
                 value = value.decode('utf-8')
                 if user_has_setfattr:
                     executable = 'setfattr'
-                    opts = ['-n', key, '-v', value]
+                    opts = ['-n', key, '-v', '0s' + base64.b64encode(value)]
                 elif user_has_xattr:
```
As `value` is guaranteed to be a UTF-8 string (or `bytes.decode()` throws), it shouldn't be necessary to do this for `xattr` (l.5666-9):
```
                 elif user_has_xattr:
                     executable = 'xattr'
-                    opts = ['-wx', key, value]
+                    opts = ['-wx', key, binascii.hexlify(value, ' ')]

```
Both referenced modules are already imported in `utils.py`.
