### ISSUE TITLE
Support for open.spotify.com

### ISSUE THREAD

**Issue by jefferson018200306** [ytdl-org/youtube-dl#28660]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2021.04.01**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

In the readme file of Youtube-dl, it says they can also supports Spotify. But,, upon trying one track, it says unsupported url. Please 🙏 fix this soon. thanks!

**Comment by jefferson018200306** [comment]
```
$ youtube-dl -F "https://open.spotify.com/track/37ZtpRBkHcaq6hHy0X98zn?si=rF991YAyS-6hT_AmyqS6Jg"
[generic] 37ZtpRBkHcaq6hHy0X98zn?si=rF991YAyS-6hT_AmyqS6Jg: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 37ZtpRBkHcaq6hHy0X98zn?si=rF991YAyS-6hT_AmyqS6Jg: Downloading webpage
[generic] 37ZtpRBkHcaq6hHy0X98zn?si=rF991YAyS-6hT_AmyqS6Jg: Extracting information
ERROR: Unsupported URL: https://open.spotify.com/track/37ZtpRBkHcaq6hHy0X98zn?si=rF991YAyS-6hT_AmyqS6Jg
```

**Comment by jefferson018200306** [comment]
### The verbose

```
$ youtube-dl -F "https://open.spotify.com/track/37ZtpRBkHcaq6hHy0X98zn?si=rF991YAyS-6hT_AmyqS6Jg" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://open.spotify.com/track/37ZtpRBkHcaq6hHy0X98zn?si=rF991YAyS-6hT_AmyqS6Jg', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.01
[debug] Python version 3.9.2 (CPython) - Linux-3.10.65-gd1ee5ec-armv7l-with-libc
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[generic] 37ZtpRBkHcaq6hHy0X98zn?si=rF991YAyS-6hT_AmyqS6Jg: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 37ZtpRBkHcaq6hHy0X98zn?si=rF991YAyS-6hT_AmyqS6Jg: Downloading webpage
[generic] 37ZtpRBkHcaq6hHy0X98zn?si=rF991YAyS-6hT_AmyqS6Jg: Extracting information
ERROR: Unsupported URL: https://open.spotify.com/track/37ZtpRBkHcaq6hHy0X98zn?si=rF991YAyS-6hT_AmyqS6Jg
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl-2021.4.1-py3.9.egg/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl-2021.4.1-py3.9.egg/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl-2021.4.1-py3.9.egg/youtube_dl/extractor/common.py", line 535, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl-2021.4.1-py3.9.egg/youtube_dl/extractor/generic.py", line 3506, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://open.spotify.com/track/37ZtpRBkHcaq6hHy0X98zn?si=rF991YAyS-6hT_AmyqS6Jg
```

**Comment by llacb47** [comment]
DRM. Search the issues before wasting maintainer's time.

**Comment by jefferson018200306** [comment]
> DRM. Search the issues before wasting maintainers' time.

All issues are closed

**Comment by Rubbesh** [comment]
❤️
