### ISSUE TITLE
twitcasting.tv not working (vods/lives)

### ISSUE THREAD

**Issue by Ronam22** [ytdl-org/youtube-dl#28675]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: ['-o', 'D:\\Videos\\%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['https://twitcasting.tv/c:riinukun', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.04.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[generic] c:riinukun: Requesting header
WARNING: Falling back on generic information extractor.
[generic] c:riinukun: Downloading webpage
[generic] c:riinukun: Extracting information
[generic] twplayer?r8705: Requesting header
WARNING: Falling back on generic information extractor.
[generic] twplayer?r8705: Downloading webpage
[generic] twplayer?r8705: Extracting information
ERROR: Unsupported URL: https://ssl.twitcasting.tv/c:riinukun/twplayer?r8705
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwt56m8wg\build\youtube_dl\extractor\generic.py", line 3506, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://ssl.twitcasting.tv/c:riinukun/twplayer?r8705
```

## Description

Trying to download lives and vods on twitcasting.tv without any luck. Even the index.m3u8 mentioned a few months ago doesn't work anymore.

**Comment by Igetin** [comment]
The website doesn’t seem to use playlists anymore, or at least there are no requests to an `M3U8` file like there used to be.

Just leaving this here for others looking for a solution: streamlink does still support Twitcasting currently. Example usage:

```
streamlink -o output_file.ts https://twitcasting.tv/USERNAME/movie/MOVIE_ID best
```

Password-protected video:
```
streamlink -o output_file.ts --twitcasting-password password_here https://twitcasting.tv/USERNAME/movie/MOVIE_ID best
```

Also works for live streams (i.e. URL format ` https://twitcasting.tv/USERNAME`).
