### ISSUE TITLE
AfreecaTV livestreams

### ISSUE THREAD

**Issue by iukibkim** [ytdl-org/youtube-dl#28677]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://play.afreecatv.com/dth03119/23225086']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.01
[debug] Python version 3.8.5 (CPython) - Linux-5.8.0-48-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[generic] 23225086: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 23225086: Downloading webpage
[generic] 23225086: Extracting information
[generic] embed: Requesting header
WARNING: Falling back on generic information extractor.
[generic] embed: Downloading webpage
[generic] embed: Extracting information
ERROR: Unsupported URL: https://play.afreecatv.com/dth03119/embed
Traceback (most recent call last):
  File "/home/icarus/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/home/icarus/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/home/icarus/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/icarus/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3506, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://play.afreecatv.com/dth03119/embed
```

## Description

I remember watching AfreecaTV livestreams through youtube-dl a while ago and I haven't been able watch them.
The VODs seem to work but live streams don't.
The link above (https://play.afreecatv.com/dth03119/23225086) is currently live but won't be later on. More livestreams can be found on the [AfreecaTV](https://www.afreecatv.com/) homepage.

**Comment by Hydro5** [comment]
I think it's a simple matter of Afreeca updated their player, and ytdl hasn't been updated to reflect that.
