### ISSUE TITLE
Facebook watchparty "login_data" not found in webpage " Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)'));"

### ISSUE THREAD

**Issue by Udhayarajan** [ytdl-org/youtube-dl#28688]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-playlist', 'https://www.facebook.com/watchparty/211641140192478', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.04.07
[debug] Git HEAD: 72a2c0a9e
[debug] Python version 3.9.1 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] 211641140192478: Downloading webpage
[facebook] 211641140192478: Downloading JSON metadata
ERROR: 211641140192478: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "E:\PROJECTS\PycharmProjects\youtube_dl\extractor\common.py", line 906, in _parse_json
    return json.loads(json_string)
  File "C:\Users\UDHAYARAJAN M\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\UDHAYARAJAN M\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\UDHAYARAJAN M\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "E:\PROJECTS\PycharmProjects\youtube_dl\extractor\common.py", line 906, in _parse_json
    return json.loads(json_string)
  File "C:\Users\UDHAYARAJAN M\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\UDHAYARAJAN M\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\UDHAYARAJAN M\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\PROJECTS\PycharmProjects\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "E:\PROJECTS\PycharmProjects\youtube_dl\YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "E:\PROJECTS\PycharmProjects\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "E:\PROJECTS\PycharmProjects\youtube_dl\extractor\facebook.py", line 686, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "E:\PROJECTS\PycharmProjects\youtube_dl\extractor\facebook.py", line 552, in _extract_from_url
    living_room = self._download_json(
  File "E:\PROJECTS\PycharmProjects\youtube_dl\extractor\common.py", line 895, in _download_json
    res = self._download_json_handle(
  File "E:\PROJECTS\PycharmProjects\youtube_dl\extractor\common.py", line 881, in _download_json_handle
    return self._parse_json(
  File "E:\PROJECTS\PycharmProjects\youtube_dl\extractor\common.py", line 910, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: 211641140192478: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


Process finished with exit code 1

```

## Description

I have tried to download Facebooks's watch party video (URL: From test URL). I couldn't pass username and password as args(Facebook lock my profile and asking to verify with G-mail if I pass username and password ) so I have modified HTTPS request with Cookies (got from facebook.com's request header). What is a workaround for this?

**Comment by remitamine** [comment]
[use cookies](https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl) without `--username` and `--password` or `--netrc` options.

**Comment by Udhayarajan** [comment]
@remitamine Still same error

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-playlist', 'https://www.facebook.com/watchparty/211641140192478', '--cookies', 'C:/Users/UDHAYARAJAN M\\Downloads/facebook.com_cookies.txt', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.04.07
[debug] Git HEAD: 72a2c0a9e
[debug] Python version 3.9.1 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] 211641140192478: Downloading webpage
[facebook] 211641140192478: Downloading JSON metadata
ERROR: 211641140192478: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "E:\PROJECTS\PycharmProjects\youtube_dl\extractor\common.py", line 906, in _parse_json
    return json.loads(json_string)
  File "C:\Users\UDHAYARAJAN M\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\UDHAYARAJAN M\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\UDHAYARAJAN M\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "E:\PROJECTS\PycharmProjects\youtube_dl\extractor\common.py", line 906, in _parse_json
    return json.loads(json_string)
  File "C:\Users\UDHAYARAJAN M\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\UDHAYARAJAN M\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\UDHAYARAJAN M\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\PROJECTS\PycharmProjects\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "E:\PROJECTS\PycharmProjects\youtube_dl\YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "E:\PROJECTS\PycharmProjects\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "E:\PROJECTS\PycharmProjects\youtube_dl\extractor\facebook.py", line 682, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "E:\PROJECTS\PycharmProjects\youtube_dl\extractor\facebook.py", line 550, in _extract_from_url
    living_room = self._download_json(
  File "E:\PROJECTS\PycharmProjects\youtube_dl\extractor\common.py", line 895, in _download_json
    res = self._download_json_handle(
  File "E:\PROJECTS\PycharmProjects\youtube_dl\extractor\common.py", line 881, in _download_json_handle
    return self._parse_json(
  File "E:\PROJECTS\PycharmProjects\youtube_dl\extractor\common.py", line 910, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: 211641140192478: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


Process finished with exit code 1
```

[https://github.com/ytdl-org/youtube-
dl/blob/006eea564d55130bb2e2ea7feb3a0e286d75d91f/youtube_dl/extractor/facebook.py#L535](url) prefetched_data is None

**Comment by dstftw** [comment]
No longer available.
