### ISSUE TITLE
Merging fail

### ISSUE THREAD

**Issue by ybbuc** [ytdl-org/youtube-dl#28692]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Why does merging fail? It says error, but gives no description of the error. How do I resolve this problem?

```➜  ~ youtube-dl -v https://vimeo.com/292414849
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vimeo.com/292414849']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.01
[debug] Git HEAD: 0ad2564c5
[debug] Python version 3.9.2 (CPython) - macOS-11.2.3-arm64-arm-64bit
[debug] exe versions: ffmpeg present, ffprobe present, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 292414849: Downloading webpage
[vimeo] 292414849: Extracting information
[vimeo] 292414849: Downloading JSON metadata
[vimeo] 292414849: Downloading JSON metadata
[vimeo] 292414849: Checking Original video URL
[vimeo] 292414849: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 292414849: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 292414849: Downloading fastly_skyfire m3u8 information
[vimeo] 292414849: Downloading fastly_skyfire m3u8 information
[vimeo] 292414849: Downloading akfire_interconnect_quic MPD information
[vimeo] 292414849: Downloading akfire_interconnect_quic MPD information
WARNING: Failed to download MPD manifest: <urlopen error EOF occurred in violation of protocol (_ssl.c:1123)>
[vimeo] 292414849: Downloading fastly_skyfire MPD information
[vimeo] 292414849: Downloading fastly_skyfire MPD information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://skyfire.vimeocdn.com/1617455809-0x16625301582c3dae01919ca12048ea5fdd50711b/292414849/sep/video/1109767785/playlist.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 15
[download] Destination: Instagram 'Light Forest'-292414849.fhls-fastly_skyfire_sep-2318.mp4
[download] 100% of 24.19MiB in 00:55
[debug] Invoking downloader on 'https://skyfire.vimeocdn.com/1617455809-0x16625301582c3dae01919ca12048ea5fdd50711b/292414849/sep/video/1109767784,1109767791,1109767785,1109767792/master.mpd?base64_init=1'
[dashsegments] Total fragments: 16
[download] Destination: Instagram 'Light Forest'-292414849.fdash-fastly_skyfire_sep-audio-1109767784.m4a
[download] 100% of 1.46MiB in 00:45
[ffmpeg] Merging formats into "Instagram 'Light Forest'-292414849.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Instagram '"'"'Light Forest'"'"'-292414849.fhls-fastly_skyfire_sep-2318.mp4' -i 'file:Instagram '"'"'Light Forest'"'"'-292414849.fdash-fastly_skyfire_sep-audio-1109767784.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Instagram '"'"'Light Forest'"'"'-292414849.temp.mp4'
ERROR: 
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.4.1/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2106, in post_process
    files_to_delete, info = pp.run(info)
  File "/opt/homebrew/Cellar/youtube-dl/2021.4.1/libexec/lib/python3.9/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 523, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/opt/homebrew/Cellar/youtube-dl/2021.4.1/libexec/lib/python3.9/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError```

**Comment by dstftw** [comment]
See the output of:
```
ffmpeg -y -loglevel repeat+info -i 'file:Instagram '"'"'Light Forest'"'"'-292414849.fhls-fastly_skyfire_sep-2318.mp4' -i 'file:Instagram '"'"'Light Forest'"'"'-292414849.fdash-fastly_skyfire_sep-audio-1109767784.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Instagram '"'"'Light Forest'"'"'-292414849.temp.mp4'
```

**Comment by ybbuc** [comment]
```
ffmpeg -y -loglevel repeat+info -i 'file:Instagram '"'"'Light Forest'"'"'-292414849.fhls-fastly_skyfire_sep-2318.mp4' -i 'file:Instagram '"'"'Light Forest'"'"'-292414849.fdash-fastly_skyfire_sep-audio-1109767784.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Instagram '"'"'Light Forest'"'"'-292414849.temp.mp4'

[1]    47101 killed     ffmpeg -y -loglevel repeat+info -i  -i  -c copy -map 0:v:0 -map 1:a:0 
```

**Comment by kikuyan** [comment]
Similar to this: https://github.com/Homebrew/homebrew-core/issues/70522
