### ISSUE TITLE
Youtube download all user videos fails with "Unable to extract yt initial data;"

### ISSUE THREAD

**Issue by ghmrs356** [ytdl-org/youtube-dl#28705]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
 cmd$ youtube-dl --verbose https://www.youtube.com/c/ДНЕВНИКТОКАРЯ/videos
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/c/\u0414\u041d\u0415\u0412\u041d\u0418\u041a\u0422\u041e\u041a\u0410\u0420\u042f/videos']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.07
[debug] Python version 2.7.16 (CPython) - Darwin-20.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.5.3, ffprobe 2.5.3
[debug] Proxy map: {}
[youtube:tab] ДНЕВНИКТОКАРЯ: Downloading webpage
ERROR: Unable to extract yt initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/TheUser/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/TheUser/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/TheUser/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/Users/TheUser/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2764, in _real_extract
    data = self._extract_yt_initial_data(item_id, webpage)
  File "/Users/TheUser/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 302, in _extract_yt_initial_data
    self._YT_INITIAL_DATA_RE), webpage, 'yt initial data'),
  File "/Users/TheUser/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract yt initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Trying to download all videos, this worked without problem a couple of days ago. I didn't download all of them then, so I just tried  again and it fails with "Unable to extract yt initial data;"

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by ghmrs356** [comment]
The dump pages argument produces what looks like binary output which is >64k. Want it emailed?
