### ISSUE TITLE
CDA.pl extractor is broken

### ISSUE THREAD

**Issue by BearShire** [ytdl-org/youtube-dl#28709]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\*deleted*>youtube-dl -v https://www.cda.pl/video/16762605f/vfilm?wersja=720p
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.cda.pl/video/16762605f/vfilm?wersja=720p']
[debug] Encodings: locale cp1250, fs mbcs, out cp850, pref cp1250
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Proxy map: {}
[CDA] 16762605f: Downloading webpage
[CDA] 16762605f: Downloading 360p version information
WARNING: Unable to download webpage: HTTP Error 404:
WARNING: [CDA] Unable to download 360p version information
[CDA] 16762605f: Downloading 720p version information
WARNING: Unable to download webpage: HTTP Error 404:
WARNING: [CDA] Unable to download 720p version information
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\__init__.py", line 465, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 2060, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 799, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\cda.py", line 212, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\common.py", line 1192, in _search_json_ld
  File "C:\Python\Python34\lib\re.py", line 219, in finditer
TypeError: expected string or buffer
```

## Description

Hello,

Extractor for CDA.pl stopped working. It was fine, just few days ago (it was working 05.04.2021).
I've deleted username in the Verbose log. I've tested it also for below variants of url - the results were the same.
https://www.cda.pl/video/16705934b
http://www.cda.pl/video/16705934b

Best Regards,
BearShire

**Comment by BearShire** [comment]
Problem still occurs on youtube-dl version: **2021.04.17**
I've tested both links, the traceback message is the same as earlier.
