### ISSUE TITLE
Unable to extract post url - SyFy show

### ISSUE THREAD

**Issue by codethought** [ytdl-org/youtube-dl#28717]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.04.07**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.syfy.com/resident-alien/videos/110-heroes-of-patience', '--ap-mso', 'ATTOTT', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.9.4 (CPython) - macOS-11.2.3-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[Syfy] 110-heroes-of-patience: Downloading webpage
[Syfy] 4333614: Downloading Provider Redirect Page
[Syfy] 4333614: Downloading Provider Login Page
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/extractor/syfy.py", line 46, in _real_extract
    query['auth'] = self._extract_mvpd_auth(
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/extractor/adobepass.py", line 1511, in _extract_mvpd_auth
    mvpd_confirm_page_res = post_form(provider_login_page_res, 'Logging in', {
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/extractor/adobepass.py", line 1365, in post_form
    post_url = self._html_search_regex(r'<form[^>]+action=(["\'])(?P<url>.+?)\1', form_page, 'post url', group='url')
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Trying download an episode from SyFy or NBC of the same show results in the above failure. All of the shows from the series are failing with the same error `Unable to extract post url;  please report this issue on https://yt-dl.org/bug`

https://www.syfy.com/resident-alien/videos/110-heroes-of-patience

https://www.nbc.com/resident-alien/video/heroes-of-patience/4333614

**Comment by codethought** [comment]
@remitamine  - I've updated to include the missing debug output.. can you please re-open and review again?

**Comment by codethought** [comment]
@remitamine is a TV provider account something I need to provide? And if so, how?

**Comment by october262** [comment]
try signing in with your tv provider account and then try downloading the episode
using the cookies file command

**Comment by codethought** [comment]
@october262  - tried that .. same problem..


```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.nbc.com/resident-alien/video/pilot/4299898', '--cookies', 'nbc.com_resalien_cookies.txt', '--ap-mso', 'ATTOTT', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.9.4 (CPython) - macOS-11.2.3-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[NBC] 4299898: Downloading JSON metadata
[NBC] 4299898: Downloading Provider Redirect Page
[NBC] 4299898: Downloading Provider Login Page
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/extractor/nbc.py", line 140, in _real_extract
    query['auth'] = self._extract_mvpd_auth(
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/extractor/adobepass.py", line 1511, in _extract_mvpd_auth
    mvpd_confirm_page_res = post_form(provider_login_page_res, 'Logging in', {
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/extractor/adobepass.py", line 1365, in post_form
    post_url = self._html_search_regex(r'<form[^>]+action=(["\'])(?P<url>.+?)\1', form_page, 'post url', group='url')
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
