### ISSUE TITLE
[PBS] No video formats found

### ISSUE THREAD

**Issue by ytdlbps** [ytdl-org/youtube-dl#28749]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

❯ youtube-dl https://www.pbs.org/wgbh/nova/video/australias-first-4-billion-years-awakening/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.pbs.org/wgbh/nova/video/australias-first-4-billion-years-awakening/', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.9.4 (CPython) - macOS-11.2.3-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Using fake IP 6.97.189.19 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] australias-first-4-billion-years-awakening: Downloading webpage
[pbs] Downloading widget/partnerplayer page
[pbs] Downloading portalplayer page
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/extractor/pbs.py", line 661, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/Cellar/youtube-dl/2021.4.7/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

Self explanatory.  Links works in browser, not in ytdl.  

Issue  #27605 indicates to use "non-wgbh" links, but that's N/A for this particular page, as removing "/wgbh" results in a redirect back to "/wgbh/..." and removing "wgbh/nova/" results in a 404.

**Comment by TheGrimKeeper** [comment]
It's not enough to just remove parts of the WGBH URL; the proper structure is different.  This is the correct link: https://www.pbs.org/video/nova-australias-first-4-billion-years-strange-creatures/

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/27605

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/21984
