### ISSUE TITLE
Can't download videos from Facebook

### ISSUE THREAD

**Issue by nhatanhit** [ytdl-org/youtube-dl#28743]
## Checklist

- [Y ] I'm reporting a broken site support issue
- [ Y] I've verified that I'm running youtube-dl version **2021.04.07**
- [ Y] I've checked that all provided URLs are alive and playable in a browser
- [ Y] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ Y] I've searched the bugtracker for similar bug reports including closed ones
- [ Y] I've read bugs section in FAQ

## Verbose log

```
youtube-dl  -o "H:/MyPC/Yan FB/YAN Latest News/%(title)s.%(ext)s" -f bestvideo+bestaudio --batch-file="./contents/YAN Latest News.txt" -v --download-archive "H:/MyPC/Yan FB/YAN Latest News/done.txt" --ignore-errors --add-metadata --write-info-json --write-description --merge-output-format mp4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'H:/MyPC/Yan FB/YAN Latest News/%(title)s.%(ext)s', '-f', 'bestvideo+bestaudio', '--batch-file=./contents/YAN Latest News.txt', '-v', '--download-archive', 'H:/MyPC/Yan FB/YAN Latest News/done.txt', '--ignore-errors', '--add-metadata', '--write-info-json', '--write-description', '--merge-output-format', 'mp4']
[debug] Batch file urls: ['https://www.facebook.com/watch/?v=4235562773143261', 'https://www.facebook.com/watch/?v=4089436201107258', 'https://www.facebook.com/watch/?v=355093369264287', 'https://www.facebook.com/watch/?v=184841076785756', 'https://www.facebook.com/watch/?v=791631541466667', 'https://www.facebook.com/watch/?v=467784431129877', 'https://www.facebook.com/watch/?v=167081861939052', 
'https://www.facebook.com/watch/?v=2857329301149260', 'https://www.facebook.com/watch/?v=459483941797941', 'https://www.facebook.com/watch/?v=789596251663818', 'https://www.facebook.com/watch/?v=516943846179571', 'https://www.facebook.com/watch/?v=240299167841988', 
'https://www.facebook.com/watch/?v=598440404027041', 'https://www.facebook.com/watch/?v=2426412997678646', 'https://www.facebook.com/watch/?v=819491185175392', 'https://www.facebook.com/watch/?v=586045608817175', 'https://www.facebook.com/watch/?v=2470626663212997', 'https://www.facebook.com/watch/?v=499709450644318', 'https://www.facebook.com/watch/?v=1733742263448594', 'https://www.facebook.com/watch/?v=2658731164341150', 'https://www.facebook.com/watch/?v=518899578758868', 'https://www.facebook.com/watch/?v=184491352903225', 'https://www.facebook.com/watch/?v=206540330486182', 'https://www.facebook.com/watch/?v=185885136096454', 'https://www.facebook.com/watch/?v=2144977529130608', 'https://www.facebook.com/watch/?v=487058615494621', 'https://www.facebook.com/watch/?v=824801374606585', 'https://www.facebook.com/watch/?v=2626138907468737', 'https://www.facebook.com/watch/?v=923910511342315', 'https://www.facebook.com/watch/?v=2589376324514343', 'https://www.facebook.com/watch/?v=193148779051999', 'https://www.facebook.com/watch/?v=4027713793910157', 'https://www.facebook.com/watch/?v=1253988934994438', 'https://www.facebook.com/watch/?v=1238496449850456', 'https://www.facebook.com/watch/?v=337406224203273', 'https://www.facebook.com/watch/?v=1273773332959059', 'https://www.facebook.com/watch/?v=261361455338293', 'https://www.facebook.com/watch/?v=413925999677702', 'https://www.facebook.com/watch/?v=760872858197742', 'https://www.facebook.com/watch/?v=414325612978741', 'https://www.facebook.com/watch/?v=1745978355579818', 'https://www.facebook.com/watch/?v=2816663388589446', 'https://www.facebook.com/watch/?v=752623592306466', 'https://www.facebook.com/watch/?v=398664051237220', 'https://www.facebook.com/watch/?v=436744870846096', 'https://www.facebook.com/watch/?v=3741666535891809', 'https://www.facebook.com/watch/?v=715001309195092', 'https://www.facebook.com/watch/?v=233215501686766', 'https://www.facebook.com/watch/?v=209565157492163', 'https://www.facebook.com/watch/?v=460820094917163', 'https://www.facebook.com/watch/?v=2705604696419175', 'https://www.facebook.com/watch/?v=1381202255549303', 'https://www.facebook.com/watch/?v=219759196399500', 'https://www.facebook.com/watch/?v=196671668843572', 'https://www.facebook.com/watch/?v=728621531406766', 'https://www.facebook.com/watch/?v=2797455150508374', 'https://www.facebook.com/watch/?v=637844343595716', 'https://www.facebook.com/watch/?v=3559425804079548', 'https://www.facebook.com/watch/?v=358751578590077', 'https://www.facebook.com/watch/?v=325204645434428', 'https://www.facebook.com/watch/?v=356422492384937', 'https://www.facebook.com/watch/?v=1416168478742731', 'https://www.facebook.com/watch/?v=354374225995614', 'https://www.facebook.com/watch/?v=1339296539611471', 'https://www.facebook.com/watch/?v=733202824194000', 'https://www.facebook.com/watch/?v=625198341453733', 'https://www.facebook.com/watch/?v=2658128487831998', 'https://www.facebook.com/watch/?v=654103155268211', 'https://www.facebook.com/watch/?v=758363041422882', 'https://www.facebook.com/watch/?v=736614307011130', 'https://www.facebook.com/watch/?v=463567974889195', 'https://www.facebook.com/watch/?v=1106015796543688', 'https://www.facebook.com/watch/?v=1027553851111751', 'https://www.facebook.com/watch/?v=490527345435385', 'https://www.facebook.com/watch/?v=773849336824103', 'https://www.facebook.com/watch/?v=2906017816347901', 'https://www.facebook.com/watch/?v=919893712175480', 'https://www.facebook.com/watch/?v=3719548164840081', 'https://www.facebook.com/watch/?v=288780019403768', 'https://www.facebook.com/watch/?v=157504606251141', 'https://www.facebook.com/watch/?v=503462954159966', 'https://www.facebook.com/watch/?v=456090862291923', 'https://www.facebook.com/watch/?v=468604124386213', 'https://www.facebook.com/watch/?v=885735731987033', 'https://www.facebook.com/watch/?v=752480282119581', 'https://www.facebook.com/watch/?v=3855367547882904', 'https://www.facebook.com/watch/?v=458208998836740', 'https://www.facebook.com/watch/?v=179893597293630', 'https://www.facebook.com/watch/?v=266344861865432', 'https://www.facebook.com/watch/?v=762283284713500', 'https://www.facebook.com/watch/?v=483040412892618', 'https://www.facebook.com/watch/?v=542433303385174', 'https://www.facebook.com/watch/?v=195853419012594', 'https://www.facebook.com/watch/?v=1132776780570853', 'https://www.facebook.com/watch/?v=481353606344164', 'https://www.facebook.com/watch/?v=763098697680828', 'https://www.facebook.com/watch/?v=731147820905799', 'https://www.facebook.com/watch/?v=993548994514947', 'https://www.facebook.com/watch/?v=354936009268736', 'https://www.facebook.com/watch/?v=252913919906248', 'https://www.facebook.com/watch/?v=836513913875745', 'https://www.facebook.com/watch/?v=1832206440262038', 'https://www.facebook.com/watch/?v=274493117508308', 'https://www.facebook.com/watch/?v=124051436317068', 'https://www.facebook.com/watch/?v=923522638478474', 'https://www.facebook.com/watch/?v=156224303064272', 'https://www.facebook.com/watch/?v=516964589315768', 'https://www.facebook.com/watch/?v=1546068469062606', 'https://www.facebook.com/watch/?v=372836817188268', 'https://www.facebook.com/watch/?v=3881978048564968', 'https://www.facebook.com/watch/?v=759133738296079', 'https://www.facebook.com/watch/?v=917597709091278', 'https://www.facebook.com/watch/?v=479105423284774', 'https://www.facebook.com/watch/?v=309639897410686', 'https://www.facebook.com/watch/?v=165024005478195', 'https://www.facebook.com/watch/?v=493000548407213', 'https://www.facebook.com/watch/?v=498598271550124', 'https://www.facebook.com/watch/?v=1176142979510458', 'https://www.facebook.com/watch/?v=463108054938214', 'https://www.facebook.com/watch/?v=313904716924592']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-100563-g66deab3a26, ffprobe N-100563-g66deab3a26
[debug] Proxy map: {}
[facebook] 4235562773143261: Downloading webpage
[facebook] 4235562773143261: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[facebook] 4089436201107258: Downloading webpage
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\facebook.py", line 677, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\facebook.py", line 591, in _extract_from_url
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I am using Youtube-dl to download facebook videos from batch file . List of videos can be found in this file 
[YAN Latest News.txt](https://github.com/ytdl-org/youtube-dl/files/6295927/YAN.Latest.News.txt)
As you can see, these videos are not private videos , I mean we don't need to login to see watch them, but when I try running the command. After download 2,3 videos successfully, the error is   thrown for remaining videos  (I provided the trace log)
One note: When I provided my facebook cookie to the command youtube-dl. All of them are downloaded successfully. But after 2 days download successfully, my account is blocked by Facebook.
Can you please help to check why youtube-dl can't download public videos without using cookie ?
Thanks

**Comment by Sipherdrakon** [comment]
Those are super small files and I can only assume that facebook blocked you after a few files because you were downloading them too fast. Try the --sleep-interval or the max and min option to randomize it and see if that helps.

**Comment by anhtranweallnet** [comment]
Thank @Sipherdrakon 
I tried with --sleep-interval = 30 seconds, 4-5 videos were downloaded successfully, then the error is back for remaining videos. 
Then i tried with option max / min to randomize  and it doesn't work.

**Comment by nhatanhit** [comment]
Thanks @Sipherdrakon 
I tried with --sleep-interval  = 30 seconds  and 4,5 videos are downloaded successfully. Then the error is appeared again for remaining videos. 
I tried with min , max options to randomize download process also. But it doesn't work.
