### ISSUE TITLE
NameError: name 'parse_qs' is not defined   

### ISSUE THREAD

**Issue by ousta2** [ytdl-org/youtube-dl#28780]

**Comment by Vouivre** [comment]
@dstftw 

I have exactly the same problem. I will report it with more information. Could you reopen this issue or I create a new one ? 
I'll report it later today.

**Comment by Vouivre** [comment]
It seems to be the same problem as reported [here](https://github.com/yausername/youtubedl-lazy/issues/7). 

I assume [this commit](https://github.com/ytdl-org/youtube-dl/commit/06159135ef148a6ddc632d0c89b90c937d5bb021) introduced the error. With the latest version, 2021.04.17 I get the error:

```
 youtube-dl https://www.youtube.com/watch\?v=3WA34hxlejg
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 475, in main
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 465, in _real_main
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2059, in download
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 791, in extract_info
  File "/usr/bin/youtube-dl/youtube_dl/extractor/lazy_extractors.py", line 7120, in suitable
NameError: name 'parse_qs' is not defined
```

I have tested with youtube-dl 2021.04.07 and it works fine. Perhpas some infos on my system:

```
uname -a 
Linux HOSTNAME 5.7.12 #7 SMP Wed Oct 21 07:21:26 UTC 2020 x86_64 GNU/Linux
```

And the version of `python`

```
python --version
Python 3.9.4
```

**Comment by xibr** [comment]
> It seems to be the same problem as reported [here](https://github.com/yausername/youtubedl-lazy/issues/7). 

The problem that you mentioned is for [youtubedl-android](https://github.com/yausername/youtubedl-android) and it has been resolved in [https://github.com/yausername/youtubedl-lazy/issues/8](https://github.com/yausername/youtubedl-lazy/issues/8) and it works without any problems.
