### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character '\U0001f913' in position 24: ordinal not in range(256)

### ISSUE THREAD

**Issue by sonygod** [ytdl-org/youtube-dl#28808]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE

root@test1:~/youtube_srt_test/srts# youtube-dl --write-auto-sub --sub-lang 'zh-Hans,en'  -o '%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' 'https://www.youtube.com/watch?v=QRQRq9h03GA&list=PL43LpQQbTd7Q6dZjZQ1Wm1VPpBWLj6-fA' --skip-download
[youtube:tab] Downloading playlist PL43LpQQbTd7Q6dZjZQ1Wm1VPpBWLj6-fA - add --no-playlist to just download video QRQRq9h03GA
[youtube:tab] PL43LpQQbTd7Q6dZjZQ1Wm1VPpBWLj6-fA: Downloading webpage
[youtube:tab] PL43LpQQbTd7Q6dZjZQ1Wm1VPpBWLj6-fA: Downloading webpage
[download] Downloading playlist: Fashion 
[youtube:tab] playlist Fashion : Downloading 12 videos
[download] Downloading video 1 of 12
[youtube] QRQRq9h03GA: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 475, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2060, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 799, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 838, in __extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 879, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 799, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 838, in __extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 924, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1058, in __process_playlist
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1068, in __process_iterable_entry
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 879, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 799, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 838, in __extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 872, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1683, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1814, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1805, in ensure_dir_exists
  File "/usr/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'latin-1' codec can't encode character '\U0001f380' in position 21: ordinal not in range(256)



```

## Description

can't download anyfiles from this url

https://www.youtube.com/watch?v=QRQRq9h03GA&list=PL43LpQQbTd7Q6dZjZQ1Wm1VPpBWLj6-fA

**Comment by nikoskoutr** [comment]
Could you add the --verbose flag so that we can better understand your setup?

**Comment by sonygod** [comment]
```python
 youtube-dl --verbose  --write-auto-sub --sub-lang 'zh-Hans,en'  -o '%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' 'https://www.youtube.com/watch?v=QRQRq9h03GA&list=PL43LpQQbTd7Q6dZjZQ1Wm1VPpBWLj6-fA' --skip-download
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--write-auto-sub', '--sub-lang', 'zh-Hans,en', '-o', '%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', 'https://www.youtube.com/watch?v=QRQRq9h03GA&list=PL43LpQQbTd7Q6dZjZQ1Wm1VPpBWLj6-fA', '--skip-download']
[debug] Encodings: locale ISO-8859-1, fs iso8859-1, out ISO-8859-1, pref ISO-8859-1
[debug] youtube-dl version 2021.04.17
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-126-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:tab] Downloading playlist PL43LpQQbTd7Q6dZjZQ1Wm1VPpBWLj6-fA - add --no-playlist to just download video QRQRq9h03GA
[youtube:tab] PL43LpQQbTd7Q6dZjZQ1Wm1VPpBWLj6-fA: Downloading webpage
[youtube:tab] PL43LpQQbTd7Q6dZjZQ1Wm1VPpBWLj6-fA: Downloading webpage
[download] Downloading playlist: Fashion 
[youtube:tab] playlist Fashion : Downloading 12 videos
[download] Downloading video 1 of 12
[youtube] QRQRq9h03GA: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 475, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2060, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 799, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 838, in __extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 879, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 799, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 838, in __extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 924, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1058, in __process_playlist
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1068, in __process_iterable_entry
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 879, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 799, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 838, in __extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 872, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1683, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1814, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1805, in ensure_dir_exists
  File "/usr/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'latin-1' codec can't encode character '\U0001f380' in position 21: ordinal not in range(256)
root@test1:~/test# 

```

**Comment by nikoskoutr** [comment]
It seems that indeed it is an encoding issue. You could try to force uff-8 encoding with the following flag:
```
--encoding "UTF-8"
```

**Comment by sonygod** [comment]
after add 

`--restrict-filenames`

it's fixed.
