### ISSUE TITLE
(ok.ru) HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by arg0nx** [ytdl-org/youtube-dl#28800]
- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.04.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

> [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://ok.ru/video/381828403604']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.17
[debug] Python version 3.8.6 (CPython) - Linux-5.8.0-50-generic-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[Odnoklassniki] 381828403604: Downloading webpage
[Odnoklassniki] 381828403604: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 400: Bad Request
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://vd297.mycdn.me/?expires=1618913293719&srcIp=XXX.XXX.XXX.XXX&srcAg=CHROME&ms=185.226.53.6&type=5&sig=2Q7MMATljB8&ct=4&urls=185.226.52.6&clientType=0&id=358157257424'
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1967, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1906, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2279, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
<

## Description

I've got this error when downloading from OK.RU, 
Tested it on windows and it works great...

Tried ipv4, ipv6, proxy, geo restrictions, no help, still same problem

BR

**Comment by dstftw** [comment]
You must provide reproducible environment.
