### ISSUE TITLE
download problem

### ISSUE THREAD

**Issue by PeterSchwalm** [ytdl-org/youtube-dl#28817]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.zdf.de/serien/line-of-duty/unter-druck-120.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2021.04.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-80011-gaf3e944, ffprobe N-93276-g3b23eb283a
[debug] Proxy map: {}
[debug] Using fake IP 53.165.131.88 (DE) as X-Forwarded-For.
[ZDF] unter-druck-120: Downloading webpage
[ZDF] unter-druck-120: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('basename',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\extractor\zdf.py", line 294, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\extractor\zdf.py", line 251, in _extract_mobile
KeyError: 'basename'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\extractor\zdf.py", line 294, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\extractor\zdf.py", line 251, in _extract_mobile
KeyError: 'basename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\extractor\common.py", line 547, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('basename',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by PeterSchwalm** [comment]
sorry, video was not yet available.
