### ISSUE TITLE
Unable to extract video url for Instagram video

### ISSUE THREAD

**Issue by YADA005** [ytdl-org/youtube-dl#28838]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.instagram.com/tv/BkfuX9UB-eK/', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.04.17
[debug] Python version 3.9.1 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-02-13-git-d5d6751a55-full_build-www.gyan.dev, ffprobe 2021-02-13-git-d5d6751a55-full_build-www.gyan.dev
[debug] Proxy map: {}
[Instagram] BkfuX9UB-eK: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on
 how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "D:\GitHub\SME-SM-CAS\YouTube_DL\youtube-dl_venv\lib\site-packages\youtube_dl-2021.4.17-py3.9.egg\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "D:\GitHub\SME-SM-CAS\YouTube_DL\youtube-dl_venv\lib\site-packages\youtube_dl-2021.4.17-py3.9.egg\youtube_dl\YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "D:\GitHub\SME-SM-CAS\YouTube_DL\youtube-dl_venv\lib\site-packages\youtube_dl-2021.4.17-py3.9.egg\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "D:\GitHub\SME-SM-CAS\YouTube_DL\youtube-dl_venv\lib\site-packages\youtube_dl-2021.4.17-py3.9.egg\youtube_dl\extractor\instagram.py", line 240, in _real_extra
ct
    video_url = self._og_search_video_url(webpage, secure=False)
  File "D:\GitHub\SME-SM-CAS\YouTube_DL\youtube-dl_venv\lib\site-packages\youtube_dl-2021.4.17-py3.9.egg\youtube_dl\extractor\common.py", line 1130, in _og_search_vi
deo_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "D:\GitHub\SME-SM-CAS\YouTube_DL\youtube-dl_venv\lib\site-packages\youtube_dl-2021.4.17-py3.9.egg\youtube_dl\extractor\common.py", line 1021, in _html_search_
regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "D:\GitHub\SME-SM-CAS\YouTube_DL\youtube-dl_venv\lib\site-packages\youtube_dl-2021.4.17-py3.9.egg\youtube_dl\extractor\common.py", line 1012, in _search_regex

    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see
  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Tried on couple of Instagram Video URL'S but not working for any. Checked the version its is latest (2021.04.17).

**Comment by YADA005** [comment]
It seems like it has issue with all Facebook services (Facebook, Instagram, etc.) for some interval of time. Now it is working fine. But still its has to work as those video are available on Webpage.
