### ISSUE TITLE
TikTok "ERROR: This video is private"

### ISSUE THREAD

**Issue by TheBallOfAeolus** [ytdl-org/youtube-dl#28834]
I am trying to download a private TikTok video which I can access if I log in with my account

My youtube-dl version is up to date:
```
:~$ youtube-dl -U
youtube-dl is up-to-date (2021.04.17)
```

I have tried using --netrc 
```
:~$ youtube-dl -v --netrc https://www.tiktok.com/@xq9xfrnj6/video/6953905882576981254
[debug] System config: []
[debug] User config: [u'-o', u'~/Videos/youtube-dl/%(title)s.%(ext)s', u'--write-thumbnail', u'--all-subs', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', u'--user-agent', u'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0', u'--cache-dir', u'~/.cache/youtube-dl', u'--yes-playlist']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--netrc', u'https://www.tiktok.com/@xq9xfrnj6/video/6953905882576981254']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.17
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-72-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[TikTok] Setting up session
[TikTok] 6953905882576981254: Downloading webpage
ERROR: This video is private
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tiktok.py", line 115, in _real_extract
    raise ExtractorError('This video is private', expected=True)
ExtractorError: This video is private
```
or using -u 
```
:~$ youtube-dl -v -u myemail@gmail.com  https://www.tiktok.com/@xq9xfrnj6/video/6953905882576981254
[debug] System config: []
[debug] User config: [u'-o', u'~/Videos/youtube-dl/%(title)s.%(ext)s', u'--write-thumbnail', u'--all-subs', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', u'--user-agent', u'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0', u'--cache-dir', u'~/.cache/youtube-dl', u'--yes-playlist']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'https://www.tiktok.com/@xq9xfrnj6/video/6953905882576981254']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.17
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-72-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[TikTok] Setting up session
[TikTok] 6953905882576981254: Downloading webpage
ERROR: This video is private
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tiktok.py", line 115, in _real_extract
    raise ExtractorError('This video is private', expected=True)
ExtractorError: This video is private
```

If I try to download a random public video, it works properly
```
:~$ youtube-dl -v --netrc https://www.tiktok.com/@minoushiva/video/6930292370114235653
[debug] System config: []
[debug] User config: [u'-o', u'~/Videos/youtube-dl/%(title)s.%(ext)s', u'--write-thumbnail', u'--all-subs', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', u'--user-agent', u'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0', u'--cache-dir', u'~/.cache/youtube-dl', u'--yes-playlist']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--netrc', u'https://www.tiktok.com/@minoushiva/video/6930292370114235653']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.17
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-72-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[TikTok] Setting up session
[TikTok] 6930292370114235653: Downloading webpage
[TikTok] 6930292370114235653: Downloading thumbnail ...
[TikTok] 6930292370114235653: Writing thumbnail to: /home/USER/Videos/youtube-dl/Minou&Shiva.jpg
[debug] Invoking downloader on u'https://v16-web.tiktok.com/video/tos/useast2a/tos-useast2a-pve-0068/2019047cb9394a949bb30c5cfa086dae/?a=1988&br=1896&bt=948&cd=0%7C0%7C1&ch=0&cr=0&cs=0&cv=1&dr=0&ds=3&er=&expire=1619104958&l=202104220922210101890361332A032E03&lr=tiktok_m&mime_type=video_mp4&net=0&pl=0&policy=2&qs=0&rc=M3l1PDtweWZvMzMzaDczM0ApZTQ6ZGRmOWVkNzU6Ojs4NGcuYzFta2puZGpgLS0yMTZzc2IyXjVeL2MvMzRgYjIvXi86Yw%3D%3D&signature=d6fce4c861359e1504aeef01be83b67d&tk=tt_webid_v2&vl=&vr='
[download] Destination: /home/USER/Videos/youtube-dl/Minou&Shiva.mp4
[download] 100% of 1.89MiB in 00:00
```

Any idea?
Thank you!

**Comment by s104346** [comment]
Try using cookies: https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl

**Comment by TheBallOfAeolus** [comment]
> Try using cookies: https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl

Thank you!
It now works without any issues.
