### ISSUE TITLE
Heroku Error: Video Unavailable

### ISSUE THREAD

**Issue by Elielson68** [ytdl-org/youtube-dl#28840]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
2021-04-22T14:17:07.186717+00:00 app[web.1]: ERROR: Video unavailable

2021-04-22T14:17:07.191191+00:00 app[web.1]: [2021-04-22 14:17:07,187] ERROR in app: Exception on /bot [POST]

2021-04-22T14:17:07.191195+00:00 app[web.1]: Traceback (most recent call last):

2021-04-22T14:17:07.191196+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper

2021-04-22T14:17:07.191196+00:00 app[web.1]:     return func(self, *args, **kwargs)

2021-04-22T14:17:07.191197+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info

2021-04-22T14:17:07.191198+00:00 app[web.1]:     ie_result = ie.extract(url)

2021-04-22T14:17:07.191198+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract

2021-04-22T14:17:07.191198+00:00 app[web.1]:     ie_result = self._real_extract(url)

2021-04-22T14:17:07.191205+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1658, in _real_extract

2021-04-22T14:17:07.191205+00:00 app[web.1]:     raise ExtractorError(reason, expected=True)

2021-04-22T14:17:07.191206+00:00 app[web.1]: youtube_dl.utils.ExtractorError: Video unavailable

2021-04-22T14:17:07.191207+00:00 app[web.1]: 

2021-04-22T14:17:07.191207+00:00 app[web.1]: During handling of the above exception, another exception occurred:

2021-04-22T14:17:07.191207+00:00 app[web.1]: 

2021-04-22T14:17:07.191208+00:00 app[web.1]: Traceback (most recent call last):

2021-04-22T14:17:07.191208+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app

2021-04-22T14:17:07.191209+00:00 app[web.1]:     response = self.full_dispatch_request()

2021-04-22T14:17:07.191209+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request

2021-04-22T14:17:07.191210+00:00 app[web.1]:     rv = self.handle_user_exception(e)

2021-04-22T14:17:07.191210+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception

2021-04-22T14:17:07.191210+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)

2021-04-22T14:17:07.191210+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise

2021-04-22T14:17:07.191211+00:00 app[web.1]:     raise value

2021-04-22T14:17:07.191211+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request

2021-04-22T14:17:07.191211+00:00 app[web.1]:     rv = self.dispatch_request()

2021-04-22T14:17:07.191212+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request

2021-04-22T14:17:07.191212+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)

2021-04-22T14:17:07.191212+00:00 app[web.1]:   File "/app/app/main.py", line 90, in bot

2021-04-22T14:17:07.191213+00:00 app[web.1]:     ydl.download([str(url)])

2021-04-22T14:17:07.191213+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2055, in download

2021-04-22T14:17:07.191213+00:00 app[web.1]:     res = self.extract_info(

2021-04-22T14:17:07.191213+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 799, in extract_info

2021-04-22T14:17:07.191214+00:00 app[web.1]:     return self.__extract_info(url, ie, download, extra_info, process)

2021-04-22T14:17:07.191214+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper

2021-04-22T14:17:07.191214+00:00 app[web.1]:     self.report_error(compat_str(e), e.format_traceback())

2021-04-22T14:17:07.191215+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 628, in report_error

2021-04-22T14:17:07.191215+00:00 app[web.1]:     self.trouble(error_message, tb)

2021-04-22T14:17:07.191215+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 598, in trouble

2021-04-22T14:17:07.191215+00:00 app[web.1]:     raise DownloadError(message, exc_info)

2021-04-22T14:17:07.191215+00:00 app[web.1]: youtube_dl.utils.DownloadError: ERROR: Video unavailable
```

## Description

I am using a Flask application on Heroku where I request a Youtube URL to download a video and convert it to mp3. The moment I pass the URL to the download method in the form of a list it returns this error. The URL I'm using is this one: https://www.youtube.com/watch?v=oizkx2wbhn8

I'm passing this parameter as an option:

```python
ydl_opts = {
     'format': 'bestaudio / best',
     'postprocessors': [{
         'key': 'FFmpegExtractAudio',
         'preferredcodec': 'mp3',
         'preferredquality': '192',
     }]
}
```

**Comment by Elielson68** [comment]
The error was being caused because of using a .lower in the URL making the URL invalid.
