### ISSUE TITLE
ERROR: Stream #1:0 -> #0:1 (copy) when trying to --merge-output-format

### ISSUE THREAD

**Issue by suntong** [ytdl-org/youtube-dl#28846]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl --version
2021.04.17

$ youtube-dl -v -f worstvideo+bestaudio --merge-output-format webm 'https://www.youtube.com/watch?v=8fJy_j0h8oU'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'worstvideo+bestaudio', '--merge-output-format', 'webm', 'https://www.youtube.com/watch?v=8fJy_j0h8oU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.17
[debug] Python version 3.9.2 (CPython) - Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0
[debug] Proxy map: {}
[youtube] 8fJy_j0h8oU: Downloading webpage
[debug] Invoking downloader on 'https://r2---sn-gvbxgn-tt1el.googlevideo.com/videoplayback?expire=1619169601&ei=4TyCYOLxHILxigTCi7WYBg&ip=97.108.3.116&id=o-ABWxlBWyqT9BAR4eGuHaREq-qE7eCmkxZjv0FKi1N8Mz&itag=160&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=a9&mm=31%2C26&mn=sn-gvbxgn-tt1el%2Csn-vgqsknez&ms=au%2Conr&mv=m&mvi=2&pl=24&initcwndbps=1792500&vprv=1&mime=video%2Fmp4&ns=d3wjE71KmAKiTgFZX9PE1osF&gir=yes&clen=80188509&dur=11344.399&lmt=1614634737079609&mt=1619147560&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5535432&n=7u3j4ZOFncGRFRDbzK&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMMOEdsbTeNYyzjA7CSK8E7UhoCm9ZsyqDGAqBeM864KAiEA_EOPgC8xEC6XGEnqLC8TjHHlibry2Yan9OSrWebViPU%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgKxn5GBn67UZY8Qm64eAQPdiRYd4RmRko5zWsnyHEP_sCIBzUI6Sc7PwZQRcLeSuBs67uu7qIlcdztZUOc_o-vPGY'
[download] Destination: Warm Light â¢ Relaxing Flute, Guitar & Piano Music with Birds Singing-8fJy_j0h8oU.f160.mp4
[download] 100% of 76.47MiB in 00:11
[debug] Invoking downloader on 'https://r2---sn-gvbxgn-tt1el.googlevideo.com/videoplayback?expire=1619169601&ei=4TyCYOLxHILxigTCi7WYBg&ip=97.108.3.116&id=o-ABWxlBWyqT9BAR4eGuHaREq-qE7eCmkxZjv0FKi1N8Mz&itag=251&source=youtube&requiressl=yes&mh=a9&mm=31%2C26&mn=sn-gvbxgn-tt1el%2Csn-vgqsknez&ms=au%2Conr&mv=m&mvi=2&pl=24&initcwndbps=1792500&vprv=1&mime=audio%2Fwebm&ns=d3wjE71KmAKiTgFZX9PE1osF&gir=yes&clen=190976563&dur=11344.421&lmt=1614629208666121&mt=1619147560&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5531432&n=7u3j4ZOFncGRFRDbzK&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgHqJfZd_GCc8GgQLaJ-46XJ6aYC163FRD5I-rMU4Z1qECIQCuBEAzpgrceJxu6PacyoEWqUmm6c_TNq9QykHrUCimUA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgKxn5GBn67UZY8Qm64eAQPdiRYd4RmRko5zWsnyHEP_sCIBzUI6Sc7PwZQRcLeSuBs67uu7qIlcdztZUOc_o-vPGY'
[download] Destination: Warm Light â¢ Relaxing Flute, Guitar & Piano Music with Birds Singing-8fJy_j0h8oU.f251.webm
[download] 100% of 182.13MiB in 00:28
[ffmpeg] Merging formats into "Warm Light â¢ Relaxing Flute, Guitar & Piano Music with Birds Singing-8fJy_j0h8oU.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Warm Light â¢ Relaxing Flute, Guitar & Piano Music with Birds Singing-8fJy_j0h8oU.f160.mp4' -i 'file:Warm Light â¢ Relaxing Flute, Guitar & Piano Music with Birds Singing-8fJy_j0h8oU.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Warm Light â¢ Relaxing Flute, Guitar & Piano Music with Birds Singing-8fJy_j0h8oU.temp.webm'
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2106, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 523, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)

$ python -V
Python 3.9.2

$ apt-cache policy python3
python3:
  Installed: 3.9.2-2
  Candidate: 3.9.2-2
  Version table:
 *** 3.9.2-2 100
         80 http://deb.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
     3.7.3-1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages

$ apt-cache policy ffmpeg
ffmpeg:
  Installed: 7:4.3.2-0+deb11u1
  Candidate: 7:4.3.2-0+deb11u1
  Version table:
 *** 7:4.3.2-0+deb11u1 100
         80 http://deb.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
     7:4.1.6-1~deb10u1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        500 http://security.debian.org/debian-security buster/updates/main amd64 Packages

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

```

## Description

- Unlike #27799 & #28061, I'm not hardcoding file extension.

- Similar to #28208, but entirely different error reported by `ffmpeg`.

Seems to me that `ffmpeg` does not accept the syntax that `youtube-dl` used to merge the output. Is my `ffmpeg` too new?

**Comment by suntong** [comment]
Found that without using `--merge-output-format` would be OK:

```
$ youtube-dl -v -f worstvideo+bestaudio 'https://www.youtube.com/watch?v=8fJy_j0h8oU'
. . . 
[download] Warm Light â¢ Relaxing Flute, Guitar & Piano Music with Birds Singing-8fJy_j0h8oU.f160.mp4 has already been downloaded
[download] 100% of 76.47MiB
[debug] Invoking downloader on 'https://r2---sn-gvbxgn-tt1el.googlevideo.com/videoplayback?expire=1619170973&ei=PUKCYIqkA-eEir4Pn4CfiAc&ip=97.108.3.116&id=o-ACXnjv69-dRwDOkHCb2I5OpBeDmgFymCY-NyhFFU8OQK&itag=251&source=youtube&requiressl=yes&mh=a9&mm=31%2C26&mn=sn-gvbxgn-tt1el%2Csn-vgqsrnld&ms=au%2Conr&mv=m&mvi=2&pcm2cms=yes&pl=24&initcwndbps=1896250&vprv=1&mime=audio%2Fwebm&ns=U87YKMld-qmua6T4O0G_5xAF&gir=yes&clen=190976563&dur=11344.421&lmt=1614629208666121&mt=1619149000&fvip=2&keepalive=yes&fexp=24001373%2C24007246&beids=9466586&c=WEB&txp=5531432&n=wOlLb75Gt0kZtUfPKQ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgU5R9tbEb-0dttdGUdqUdvaNxFH31YD2ZAvb5IVhNqvcCIB122tVdXEpFlCfXNFBY-kHxUI1AB9fZGE5cSzQ_seQZ&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgKYgAmAY_gkPJcLQ9vDnLwzKlGjqPp6QjhrFX_m4YFdQCIQCgqhi8rooBiTiWJIJt4XQQC0H8BT_oxEIfUPRdmwrT3Q%3D%3D'
[download] Warm Light â¢ Relaxing Flute, Guitar & Piano Music with Birds Singing-8fJy_j0h8oU.f251.webm has already been downloaded
[download] 100% of 182.13MiB
[ffmpeg] Merging formats into "Warm Light â¢ Relaxing Flute, Guitar & Piano Music with Birds Singing-8fJy_j0h8oU.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Warm Light â¢ Relaxing Flute, Guitar & Piano Music with Birds Singing-8fJy_j0h8oU.f160.mp4' -i 'file:Warm Light â¢ Relaxing Flute, Guitar & Piano Music with Birds Singing-8fJy_j0h8oU.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Warm Light â¢ Relaxing Flute, Guitar & Piano Music with Birds Singing-8fJy_j0h8oU.temp.mkv'
Deleting original file Warm Light â¢ Relaxing Flute, Guitar & Piano Music with Birds Singing-8fJy_j0h8oU.f160.mp4 (pass -k to keep)
Deleting original file Warm Light â¢ Relaxing Flute, Guitar & Piano Music with Birds Singing-8fJy_j0h8oU.f251.webm (pass -k to keep)
```

So the merged file has to be a `.mkv` file (instead of a `.webm` one)?

**Comment by kikuyan** [comment]
You instructed to merge mp4 video and opus audio into webm.
If you run ffmpeg as shown in the verbose log, you will see the error from ffmpeg.
`[webm @ 0x7f81df800000] Only VP8 or VP9 or AV1 video and Vorbis or Opus audio and WebVTT subtitles are supported for WebM.`

If you do need webm, try to refine format selection like `-f worstvideo[ext=webm]+bestaudio[ext=webm]`.

**Comment by suntong** [comment]
Thanks!!!
