### ISSUE TITLE
CBS McGyver download issues

### ISSUE THREAD

**Issue by lightronics** [ytdl-org/youtube-dl#28855]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.04.17**
- [X] I've checked that all provided URLs are alive and playable in a browser (Firefox 88.0 64-bit)
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
youtube-dl --verbose https://www.cbs.com/shows/macgyver/video/VMs_h0rz02Q1dJpWfuc1P93n1B843F9w/macgyver-h2o-orthophosphates-mission-city-corrosion-origins/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.cbs.com/shows/macgyver/video/VMs_h0rz02Q1dJpWfuc1P93n1B843F9w/macgyver-h2o-orthophosphates-mission-city-corrosion-origins/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.04.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
[CBS] VMs_h0rz02Q1dJpWfuc1P93n1B843F9w: Downloading XML
ERROR: Could not find XML element title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\extractor\cbs.py", line 115, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\extractor\cbs.py", line 65, in _extract_video_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\utils.py", line 1911, in xpath_text
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\utils.py", line 1904, in xpath_element
youtube_dl.utils.ExtractorError: Could not find XML element title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description
McGyver show can not be downloaded from CBS.
https://www.cbs.com/shows/macgyver/video/VMs_h0rz02Q1dJpWfuc1P93n1B843F9w/macgyver-h2o-orthophosphates-mission-city-corrosion-origins/

**Comment by TheGrimKeeper** [comment]
It's DRM (as far as I can tell).  CBS has been inconsistently locking the latest MacGyver episodes all season.  There is now a newer episode available, so the DRM has been removed from this one and the download should now work.
