### ISSUE TITLE
Facebook Live "DVR" videos don't download

### ISSUE THREAD

**Issue by GTAXL** [ytdl-org/youtube-dl#28865]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.04.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
[gtaxl@jetstream:youtube]./youtube-dl -v --username vic@likeacoss.com -F https://www.facebook.com/watch/?v=803064316999820
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--username', u'PRIVATE', u'-F', u'https://www.facebook.com/watch/?v=803064316999820']
Type account password and press [Return]:
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.17
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-8-amd64-x86_64-with-debian-10.8
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 803064316999820: Downloading webpage
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/facebook.py", line 677, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "./youtube-dl/youtube_dl/extractor/facebook.py", line 525, in _extract_from_url
    self.raise_login_required()
  File "./youtube-dl/youtube_dl/extractor/common.py", line 943, in raise_login_required
    expected=True)
ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.

[gtaxl@jetstream:youtube]


```

## Description

Hello, I'm trying to download a "recorded live" video from Facebook. It requires me to login, which I do, but yet still says the video is only available to registered users. I can fully view the video just fine from the same account on the web browser. Also your facebook downloader needs to support the url "fb.watch" otherwise it will use the generic downloader at first.

**Comment by llacb47** [comment]
Pass cookies.

**Comment by october262** [comment]
use caution when using cookies with facebook, as they can 
lock your account for suspicious activity.

**Comment by GTAXL** [comment]
Yes that worked, I used "Get cookies.txt" and passed the --cookies file and it worked. The original cookies.txt Chrome plugin was removed from the Chrome store. Wonder why the login method doesn't work?
