### ISSUE TITLE
Broken support private video on vk.com with cookies

### ISSUE THREAD

**Issue by uh-zuh** [ytdl-org/youtube-dl#28862]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
>youtube-dl.exe -v --cookies cookies.txt "https://vk.com/video-202656183_456239060"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'cookies.txt', 'https://vk.com/video-202656183_456239060']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2021.04.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Proxy map: {}
[vk] -202656183_456239060: Downloading JSON metadata
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\extractor\vk.py", line 318, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\extractor\vk.py", line 72, in _download_payload
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\extractor\common.py", line 943, in raise_login_required
youtube_dl.utils.ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
```

## Description

youtube-dl isn't working for private video with cookies for now.
It was working for a long time.
Last time it worked about a week ago or less.

Reproduce:
* Sign in/log in to vk.com
* Navigate to Video in left menu
* Upload video and set privacy to "Only me" -- it means video is private for all users except me
* Save video
* Wait until video is converted
* Open video in new tab and copy link of the video
* Save cookies of vk.com to file, I use this plugin https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/
* Run command like this: youtube-dl.exe -v --cookies cookies.txt "https://vk.com/video-202656183_456239060"

**Comment by dstftw** [comment]
Most likely expired cookies.

**Comment by uh-zuh** [comment]
I save cookies in same time as copy url hence cookies is not expired.
