### ISSUE TITLE
svtplay.se broken

### ISSUE THREAD

**Issue by Adriyst** [ytdl-org/youtube-dl#28876]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.svtplay.se/video/30684086/rapport/rapport-24-apr-18-00-7?id=e72gVpa', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.9.4 (CPython) - Linux-5.11.16-200.fc33.x86_64-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2
[debug] Proxy map: {}
[debug] Using fake IP 78.72.145.167 (SE) as X-Forwarded-For.
[SVTPlay] 30684086: Downloading webpage
[SVTPlay] jv1NoQE: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/adrian/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/home/adrian/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/home/adrian/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/adrian/.local/lib/python3.9/site-packages/youtube_dl/extractor/svt.py", line 270, in _real_extract
    info_dict = self._extract_by_video_id(svt_id, webpage)
  File "/home/adrian/.local/lib/python3.9/site-packages/youtube_dl/extractor/svt.py", line 212, in _extract_by_video_id
    info_dict = self._extract_video(data, video_id)
  File "/home/adrian/.local/lib/python3.9/site-packages/youtube_dl/extractor/svt.py", line 53, in _extract_video
    self._sort_formats(formats)
  File "/home/adrian/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

This has worked up until very recently. There were some problems about a month ago that were seemingly solved.

**Comment by ijbh** [comment]
I just want to add that the problem seems to be unique for some shows that have a list of episodes. If a show only has one "episode" (like if it's a movie) then everything seems to be working. Like this [link](https://www.svtplay.se/video/18873434/the-queen) for example. But for a show [like this one](https://www.svtplay.se/morgonstudion), no episode is downloadable. I have also seen shows where some episodes are downloadable and some are not.

**Comment by ijbh** [comment]
It is working now. Thank you!! :)
