### ISSUE TITLE
download from linkedin learning not woerking

### ISSUE THREAD

**Issue by shadowdragon007** [ytdl-org/youtube-dl#28880]
- [ ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.04.26**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Description

Cant download from linkedin learning

**Comment by shadowdragon007** [comment]
G:\New folder (2)\youtube_dl>youtube-dl --verbose --cookies .\cookies.txt "https://www.linkedin.com/learning/giving-your-elevator-pitch" -o "%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s" --write-sub
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--cookies', '.\\cookies.txt', 'https://www.linkedin.com/learning/giving-your-elevator-pitch', '-o', '%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s', '--write-sub']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[linkedin:learning:course] Downloading JSON metadata
[download] Downloading playlist: Giving Your Elevator Pitch
[linkedin:learning:course] playlist Giving Your Elevator Pitch: Collected 5 video ids (downloading 5 of them)
[download] Downloading video 1 of 5
[linkedin:learning] welcome: Downloading 360p JSON metadata
[linkedin:learning] welcome: Downloading 540p JSON metadata
[linkedin:learning] welcome: Downloading 720p JSON metadata
[linkedin:learning] welcome: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://dms.licdn.com/playlist/C4E0DAQGOwFX6f2fPqQ/learning-original-video-vbr-720/0/1598784134251?e=1619532000&v=beta&t=_MVpNMhHHw2BB2ZGJPpnQga81eRRdrOnOZLjGRKd-gA#.mp4'
[download] Giving Your Elevator Pitch\1 - Introduction\1 - Welcome.unknown_video has already been downloaded
[download] 100% of 31.87MiB
[download] Downloading video 2 of 5
[linkedin:learning] benefits-to-an-elevator-speech: Downloading 360p JSON metadata
[linkedin:learning] benefits-to-an-elevator-speech: Downloading 540p JSON metadata
[linkedin:learning] benefits-to-an-elevator-speech: Downloading 720p JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\linkedin.py", line 127, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
