### ISSUE TITLE
[7plus] No longer works, unsupported URL

### ISSUE THREAD

**Issue by chrstphrcrnsch** [ytdl-org/youtube-dl#28882]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\chris\Downloads\Unsorted>youtube-dl -v https://7plus.com.au/the-93rd-annual-academy-awards
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://7plus.com.au/the-93rd-annual-academy-awards']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-08-14-a762fd2, ffprobe N-92767-g53d3a1c514
[debug] Proxy map: {}
[generic] the-93rd-annual-academy-awards: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-93rd-annual-academy-awards: Downloading webpage
[generic] the-93rd-annual-academy-awards: Extracting information
ERROR: Unsupported URL: https://7plus.com.au/the-93rd-annual-academy-awards
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\generic.py", line 3506, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://7plus.com.au/the-93rd-annual-academy-awards
```

## Description

7plus is listed as supported on the yt-dl list of websites, but doesn't seem to parse the URL properly, as it falls back to 'generic' extractor. I believe the site got a refresh not too long ago so it may have broken the way youtube-dl extracts from 7plus.

**Comment by section83** [comment]
You need to find the correct URL.  7Plus has what you could call "Show" pages that list the episodes available for that show.  You need the URL of an episode for YTDL to work.  So, the URL for the Oscars is: https://7plus.com.au/the-93rd-annual-academy-awards?episode-id=SPCL21-001.

But, like nearly everything on 7plus, it is DRM protected.  YTDL does not break DRM.

**Comment by 89z** [comment]
Issue should be closed, URL is dead
