### ISSUE TITLE
Help-me error to download funimation

### ISSUE THREAD

**Issue by Mytic-Slander** [ytdl-org/youtube-dl#28895]
Any help?

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-f', 'best', '--cookies', 'cookies.txt', 'https://www.funimation.com/shows/the-promised-neverland/121045/Simulcast/?lang=english', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-04-25-git-d98884be41-full_build-www.gyan.dev, ffprobe 2021-04-25-git-d98884be41-full_build-www.gyan.dev
[Funimation] Logging in
[Funimation] 121045: Downloading webpage
WARNING: [Funimation] 121045: Failed to parse JSON Expecting value: line 1 column 1 (char 0)
ERROR: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\funimation.py", line 100, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\common.py", line 1142, in _html_search_meta
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\common.py", line 1021, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by en1gma713** [comment]
#28879

**Comment by Mytic-Slander** [comment]
Thanks bro, do you know how to solve?

**Comment by en1gma713** [comment]
It'll be solved when the extractor is updated. I'm nowhere near good enough to fix the problem entirely but I'm working on a temporary solution.

**Comment by Mytic-Slander** [comment]
Okay, thanks for ur help
