### ISSUE TITLE
Error while downloading a music and/or playlist

### ISSUE THREAD

**Issue by FreckledCoder** [ytdl-org/youtube-dl#28905]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/playlist?list=PL08MW4hWrm0L_FjhrPNgNcv-gAKHIHaGK']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-142-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] PL08MW4hWrm0L_FjhrPNgNcv-gAKHIHaGK: Downloading webpage
[download] Downloading playlist: CANZONI 2021 2022 ITALIANE Aprile Maggio - Musica Italiana 2021 - Canzoni del momento Hits Italia 2021 - Classifica Canzoni Italiane 2021 2022
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] playlist CANZONI 2021 2022 ITALIANE Aprile Maggio - Musica Italiana 2021 - Canzoni del momento Hits Italia 2021 - Classifica Canzoni Italiane 2021 2022: Downloading 299 videos
[download] Downloading video 1 of 299
[youtube] F92zPP2FbwE: Downloading webpage
WARNING: Unable to download webpage: HTTP Error 429: Too Many Requests
[youtube] F92zPP2FbwE: Downloading API JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1714, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

When I try to download a playlist or a song I get an error that cancels the download.

**Comment by kikuyan** [comment]
>WARNING: Unable to download webpage: HTTP Error 429: Too Many Requests

Pinned issue #23638.
