### ISSUE TITLE
How to avoid the [AttributeError: 'stderr_logger' object has no attribute 'isatty'] issue

### ISSUE THREAD

**Issue by vivi90** [ytdl-org/youtube-dl#28914]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

I try to use the `youtube_dl` package in Python.
So my first test was this and it works fine:
```python
#!/usr/bin/env python3
import youtube_dl as ydl

url = "https://www.youtube.com/watch?v=6qEzh3wKVJc"

with ydl.YoutubeDL(
    {
        "forcejson": True,
        "noplaylist": True,
        "format": "bestaudio"
    }
) as parser:
    meta = parser.extract_info(
        url,
        download=False
    )

print(meta['thumbnail'])
print(meta['title'])
print(meta['url'])
```
But i don't want to use it standalone. 
I need to use it inside a [OBS python script](https://obsproject.com/wiki/Getting-Started-With-OBS-Scripting):
```python
#!/usr/bin/env python3
import obspython as obs
import youtube_dl as ydl

class Playlist:
    '''Simple playlist'''

    def __init__(self, list = []) -> None:
        '''Constructor'''
        self.index = 0
        self.list = list
        self.size = len(self.list)

    def parse(self, url):
        '''Parses a track by it's url and returns it's meta data'''
        with ydl.YoutubeDL(
            {
                "quiet": True,
                "forcejson": True,
                "noplaylist": True,
                "format": "bestaudio"
            }
        ) as parser:
            meta = parser.extract_info(
                url,
                download=False
            )
            print("OK")
            #print(meta['thumbnail'], meta['title'], meta['url'])

    def current(self):
        '''Plays the current track, if not empty'''
        if self.size == 0:
            return None
        else:
            print("TEST")
            item = self.list[self.index]
            print(item)
            self.parse(item)

    def next(self) -> None:
        '''Plays the next track, if not empty'''
        if self.size == 0:
            return None
        else:
            self.index += 1
            if self.index >= self.size:
                self.index = 0
            #return self.parse(self.list[self.index])

    def previous(self) -> None:
        '''Plays the previous track, if not empty'''
        if self.size == 0:
            return None
        else:
            self.index -= 1
            if self.index <= -1:
                self.index = self.size - 1
            #return parse(self.list[self.index])

# Local variables for the usage with OBS

playlist = Playlist(
    [
        "https://www.youtube.com/watch?v=bHnh8HUfrHE",
        "https://www.youtube.com/watch?v=UfVF3NWzeAY",
        "https://www.youtube.com/watch?v=uIaimLil2ZE"
    ]
)

def script_properties():
    '''Script settings UI in OBS'''
    props = obs.obs_properties_create()
    obs.obs_properties_add_button(props, "playOrStopBtn", "(Re)load Playlist", lambda props, prop: playlist.current())
    return props
```
But here i get the following output on the OBS Scriptlog:
```
[mau.py] TEST
[mau.py] https://www.youtube.com/watch?v=bHnh8HUfrHE
[mau.py] Traceback (most recent call last):
[mau.py]   File "/home/vivien/Projekte/Python/mau.py", line 74, in <lambda>
[mau.py]     obs.obs_properties_add_button(props, "playOrStopBtn", "(Re)load Playlist", lambda props, prop: playlist.current())
[mau.py]   File "/home/vivien/Projekte/Python/mau.py", line 39, in current
[mau.py]     self.parse(item)
[mau.py]   File "/home/vivien/Projekte/Python/mau.py", line 24, in parse
[mau.py]     meta = parser.extract_info(
[mau.py]   File "/home/vivien/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 799, in extract_info
[mau.py]     return self.__extract_info(url, ie, download, extra_info, process)
[mau.py]   File "/home/vivien/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
[mau.py]     return func(self, *args, **kwargs)
[mau.py]   File "/home/vivien/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
[mau.py]     ie_result = ie.extract(url)
[mau.py]   File "/home/vivien/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
[mau.py]     ie_result = self._real_extract(url)
[mau.py]   File "/home/vivien/.local/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1486, in _real_extract
[mau.py]     player_response = self._extract_yt_initial_variable(
[mau.py]   File "/home/vivien/.local/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1472, in _extract_yt_initial_variable
[mau.py]     return self._parse_json(self._search_regex(
[mau.py]   File "/home/vivien/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 998, in _search_regex
[mau.py]     if not self._downloader.params.get('no_color') and compat_os_name != 'nt' and sys.stderr.isatty():
[mau.py] AttributeError: 'stderr_logger' object has no attribute 'isatty'
```
Here without the `quiet` option:
```
[mau.py] TEST
[mau.py] https://www.youtube.com/watch?v=bHnh8HUfrHE
[mau.py] [youtube] bHnh8HUfrHE: Downloading webpage
[mau.py] Traceback (most recent call last):
[mau.py]   File "/home/vivien/Projekte/Python/mau.py", line 74, in <lambda>
[mau.py]     obs.obs_properties_add_button(props, "playOrStopBtn", "(Re)load Playlist", lambda props, prop: playlist.current())
[mau.py]   File "/home/vivien/Projekte/Python/mau.py", line 39, in current
[mau.py]     self.parse(item)
[mau.py]   File "/home/vivien/Projekte/Python/mau.py", line 24, in parse
[mau.py]     meta = parser.extract_info(
[mau.py]   File "/home/vivien/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 799, in extract_info
[mau.py]     return self.__extract_info(url, ie, download, extra_info, process)
[mau.py]   File "/home/vivien/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
[mau.py]     return func(self, *args, **kwargs)
[mau.py]   File "/home/vivien/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
[mau.py]     ie_result = ie.extract(url)
[mau.py]   File "/home/vivien/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
[mau.py]     ie_result = self._real_extract(url)
[mau.py]   File "/home/vivien/.local/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1486, in _real_extract
[mau.py]     player_response = self._extract_yt_initial_variable(
[mau.py]   File "/home/vivien/.local/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1472, in _extract_yt_initial_variable
[mau.py]     return self._parse_json(self._search_regex(
[mau.py]   File "/home/vivien/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 998, in _search_regex
[mau.py]     if not self._downloader.params.get('no_color') and compat_os_name != 'nt' and sys.stderr.isatty():
[mau.py] AttributeError: 'stderr_logger' object has no attribute 'isatty'
```
What can i do to fix this issue?
Sounds for me like it is not a bug.
Maybe i need to change some settings?

*I have found some similar issues but every time in another context with completely different solutions.
So they were not applicable for me or i am just not familiar enough with Python, i don't know.*

### Environment
youtube-dl-version: `2021.4.26` (installed by pip)
python-version: `3.9.4`
os: `Manjaro Linux`
obs: `26.1.2`

Thank you, very much for you help!

**Comment by vivi90** [comment]
Maybe related: https://github.com/ytdl-org/youtube-dl/issues/16659

**Comment by vivi90** [comment]
Okay, fixed by adding:
```python
import sys

sys.stderr.isatty = lambda: False
```
Thanks to this approach:
```python
import sys

sys.stdout.isatty = lambda: False
sys.stdout.encoding = sys.getdefaultencoding()
```
From: https://stackoverflow.com/a/47069974/3699361
And the `... sys.stderr.isatty() ...` part of the error message. 😃
