### ISSUE TITLE
cda: unable to download webpage: HTTP Error 404

### ISSUE THREAD

**Issue by gucio321** [ytdl-org/youtube-dl#28935]
Hi there!

## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.cda.pl/video/391687948/vfilm']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.9.4 (CPython) - Linux-5.11.15-200.fc33.x86_64-x86_64-with-glibc2.32
[debug] exe versions: avconv v13_dev0-1643-g0676de935, avprobe v13_dev0-1643-g0676de935, ffmpeg 4.3.2, ffprobe 4.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[CDA] 391687948: Downloading webpage
[CDA] 391687948: Downloading 360p version information
WARNING: Unable to download webpage: HTTP Error 404: 
WARNING: [CDA] Unable to download 360p version information
[CDA] 391687948: Downloading 720p version information
WARNING: Unable to download webpage: HTTP Error 404: 
WARNING: [CDA] Unable to download 720p version information
[CDA] 391687948: Downloading 1080p version information
WARNING: Unable to download webpage: HTTP Error 404: 
WARNING: [CDA] Unable to download 1080p version information
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.9/site-packages/youtube_dl/__init__.py", line 475, in main
    _real_main(argv)
  File "/home/user/.local/lib/python3.9/site-packages/youtube_dl/__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/user/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2059, in download
    res = self.extract_info(
  File "/home/user/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 799, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/home/user/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/home/user/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/user/.local/lib/python3.9/site-packages/youtube_dl/extractor/cda.py", line 212, in _real_extract
    info = self._search_json_ld(webpage, video_id, default={})
  File "/home/user/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1192, in _search_json_ld
    json_ld_list = list(re.finditer(JSON_LD_RE, html))
  File "/usr/lib64/python3.9/re.py", line 248, in finditer
    return _compile(pattern, flags).finditer(string)
TypeError: expected string or bytes-like object

```

## Description

I'm trying to download a video from cda.pl and see the bug (see above).
It doesn't occure for every video. It looks, like a problem with downloading series films (url looks like https://cda.pl/video/{id}/vfilm). For single videos it works (https://cda.pl/video/{id})
l

**Comment by gucio321** [comment]
@dstftw could you give me issue number?
