### ISSUE TITLE
ValueError: Empty certificate data! What can i do ?

### ISSUE THREAD

**Issue by MinhajBoss** [ytdl-org/youtube-dl#28943]
**I Dont Know What this is ? i am getting this error on every comand. what can i do ?

https://prnt.sc/12ds9th**

`C:\Users\Minhajul Islam Rahat\Downloads\youtube-dl>youtube-dl -U
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\__init__.py", line 442, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\YoutubeDL.py", line 422, in __init__
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\YoutubeDL.py", line 2386, in _setup_opener
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\utils.py", line 2297, in make_HTTPS_handler
  File "C:\Python\Python34\lib\ssl.py", line 439, in create_default_context
  File "C:\Python\Python34\lib\ssl.py", line 390, in load_default_certs
  File "C:\Python\Python34\lib\ssl.py", line 382, in _load_windows_store_certs
ValueError: Empty certificate data`

**Comment by kikuyan** [comment]
You seem to be using python version 3.4. Update python version to 3.5+ if you can, or use Windows binary version youtube-dl should resolve the problem.
Ref. https://bugs.python.org/issue26313, #8132.
