### ISSUE TITLE
Facebook fb.watch URL no longer working

### ISSUE THREAD

**Issue by sdan41517** [ytdl-org/youtube-dl#28952]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://fb.watch/5fHH6IobEs/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-132-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 5fHH6IobEs: Requesting header
[redirect] Following redirect to https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2Fwatch%2F%3Fv%3D443024927031269
[generic] ?next=https://www.facebook: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?next=https://www.facebook: Downloading webpage
[generic] ?next=https://www.facebook: Extracting information
[redirect] Following redirect to https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2Fwatch%2F%3Fv%3D443024927031269&_fb_noscript=1
[generic] ?next=https://www.facebook: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?next=https://www.facebook: Downloading webpage
[generic] ?next=https://www.facebook: Extracting information
ERROR: Unsupported URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2Fwatch%2F%3Fv%3D443024927031269&_fb_noscript=1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2497, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2571, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2560, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 3, column 1487
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 3506, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2Fwatch%2F%3Fv%3D443024927031269&_fb_noscript=1
```

## Description

Hi,

youtube-dl is unable to download Facebook videos for **fb.watch** URL like https://fb.watch/5fHH6IobEs. It seems that Facebook redirects such links to the login page. Can it be fixed?

**Comment by sejalrj** [comment]
@sdan41517  Can I work on this? I believe I can solve this issue

**Comment by sdan41517** [comment]
> @sdan41517 Can I work on this? I believe I can solve this issue

Create a PR so they will review your fix.
