### ISSUE TITLE
RTBF.be

### ISSUE THREAD

**Issue by ericjooris** [ytdl-org/youtube-dl#28953]
Youtube-dl is no longer working with the site indicated in the subject line, for instance with this video stream:

https://www.rtbf.be/auvio/detail_shift-parcours-d-un-ex-coursier?id=2763989

The --verbose flag does not provide any detail. Output is simply:
_zsh: no matches found: https://www.rtbf.be/auvio/detail_shift-parcours-d-un-ex-coursier?id=2763989_

Here is the verbose output when trying to download the same video using the m3u8 file:

youtube-dl --verbose https://rtbf-vod.fl.freecaster.net/vod/rtbf/geo/be/e/ekdFkJ37uF/master.m3u8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://rtbf-vod.fl.freecaster.net/vod/rtbf/geo/be/e/ekdFkJ37uF/master.m3u8']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.9.4 (CPython) - macOS-11.2.3-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] master: Requesting header
[generic] master: Downloading m3u8 information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.4.26/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.4.26/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.4.26/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.4.26/libexec/lib/python3.9/site-packages/youtube_dl/extractor/generic.py", line 2446, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/Cellar/youtube-dl/2021.4.26/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')

Thanks for all the work and support.

**Comment by kikuyan** [comment]
>Output is simply:
zsh: no matches found: https://www.rtbf.be/auvio/detail_shift-parcours-d-un-ex-coursier?id=2763989

You must quote the url or escape '?' character.

**Comment by ericjooris** [comment]
Thank you very much, this solves the issue.
