### ISSUE TITLE
YouTube live streams return Errno 111

### ISSUE THREAD

**Issue by misuchiru03** [ytdl-org/youtube-dl#28964]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.04.26**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose https://www.youtube.com/watch?v=CVGjhpUxRzg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=CVGjhpUxRzg']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.9.4 (CPython) - Linux-5.11.16_1-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2
[debug] Proxy map: {}
[youtube] CVGjhpUxRzg: Downloading webpage
[youtube] CVGjhpUxRzg: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 111] Connection refused>
[youtube] CVGjhpUxRzg: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [Errno 111] Connection refused>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1714, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

When attempting to use `youtube-dl` on any youtube live stream, `Errno 111: connection refused` returns. All other youtube videos are fine.

**Comment by dstftw** [comment]
Network issue on your side.

**Comment by misuchiru03** [comment]
Just to check back in, it was, indeed, an internal network issue. Running pihole (forgot I was doing that) will result in this. The address blocked was `manifest.googlevideo.com`. Remove it and go.
