### ISSUE TITLE
Twitter: AttributeError: 'NoneType' object has no attribute 'timeout'

### ISSUE THREAD

**Issue by aliparlakci** [ytdl-org/youtube-dl#28981]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
❯ youtube-dl -v https://twitter.com/MatveyNikonorov/status/1389889641537540097
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://twitter.com/MatveyNikonorov/status/1389889641537540097']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.9.4 (CPython) - Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.28
[debug] exe versions: none
[debug] Proxy map: {}
[twitter] 1389889641537540097: Downloading guest token
[twitter] 1389889641537540097: Downloading JSON metadata
[twitter] 1389889641537540097: Downloading XML
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 8, in <module>
    sys.exit(main())
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/youtube_dl/__init__.py", line 475, in main
    _real_main(argv)
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/youtube_dl/__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2059, in download
    res = self.extract_info(
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 799, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/youtube_dl/extractor/twitter.py", line 543, in _real_extract
    formats = self._extract_formats_from_vmap_url(vmap_url, content_id or twid)
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/youtube_dl/extractor/twitter.py", line 55, in _extract_formats_from_vmap_url
    vmap_data = self._download_xml(vmap_url, video_id)
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 845, in _download_xml
    res = self._download_xml_handle(
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 824, in _download_xml_handle
    res = self._download_webpage_handle(
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 667, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2279, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 507, in open
    req.timeout = timeout
AttributeError: 'NoneType' object has no attribute 'timeout'
```

## Description

youtube-dl throws exception and quits unexpectedly when it is called with "https://twitter.com/MatveyNikonorov/status/1389889641537540097". I am not a regular user of youtube-dl but we use it as a downloader in my project, bulk-downloader-for-reddit. Thus, I don't exactly know what to expect from youtube-dl when there is no media in the tweet but I surely do not expect it to quit.

**Comment by aliparlakci** [comment]
Could you give a link to the original issue? I cannot find it.
