### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by tralalalalalalalalala** [ytdl-org/youtube-dl#28993]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.04.26**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

Last login: Fri May  7 12:01:22 on ttys000
ipad-laurence:~ renaudk$ youtube-dl --verbose https://sexu.com/20101464/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://sexu.com/20101464/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4
[debug] Proxy map: {}
[Sexu] 20101464: Downloading webpage
ERROR: Unable to extract jwvideo; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/sexu.py", line 27, in _real_extract
    self._search_regex(r'\.setup\(\s*({.+?})\s*\);', webpage, 'jwvideo'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract jwvideo; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

Hello
i am using this app to dwonload porn. many sites dont work because of something which i don't understand.

i encounter the problem on youtube sometimes with you video uplaods.

just so you knox. 

have a nice day

**Comment by tralalalalalalalalala** [comment]
and no it's not used on an ipad. but on mac so 10.14.
