### ISSUE TITLE
ValueError: Empty certificate data! What can i do ?

### ISSUE THREAD

**Issue by MinhajBoss** [ytdl-org/youtube-dl#29010]
**I Dont Know What this is ? i am getting this error on every comand. what can i do ?

https://prnt.sc/12ds9th**

    ```
C:\Users\Minhajul Islam Rahat\Downloads\youtube-dl>youtube-dl -U
    Traceback (most recent call last):
    File "main.py", line 19, in
    File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl_init_.py", line 475, in main
    File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl_init_.py", line 442, in _real_main
    File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\YoutubeDL.py", line 422, in init
    File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\YoutubeDL.py", line 2386, in _setup_opener
    File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\utils.py", line 2297, in make_HTTPS_handler
    File "C:\Python\Python34\lib\ssl.py", line 439, in create_default_context
    File "C:\Python\Python34\lib\ssl.py", line 390, in load_default_certs
    File "C:\Python\Python34\lib\ssl.py", line 382, in _load_windows_store_certs
    ValueError: Empty certificate data

```

**Comment by julenuri** [comment]
What enviroment are you using?
I have exactly the same issue in Wine, in ReactOS, but I don't have it on Windows XP (using the MSVC binary version).
Here I have my ReactOS report: https://jira.reactos.org/browse/CORE-17548

**Comment by MinhajBoss** [comment]
> 
> 
> What enviroment are you using?
> I have exactly the same issue in Wine, in ReactOS, but I don't have it on Windows XP (using the MSVC binary version).
> Here I have my ReactOS report: https://jira.reactos.org/browse/CORE-17548

I am using windows 10.

**Comment by julenuri** [comment]
Some library lacks in your Windows 10 lite, in ReactOS, in Wine, but not in Windows XP SP3, neither in WS2003SP1/SP2, neither in every Windows standard version after that. 
I don't know what is the Python function that fails. But I will try to guess what is.

**Comment by julenuri** [comment]
@MinhajBoss  Something related to SHGetSpecialFolderPathW in Shell32.dll lacks at least in Wine, according to Dependency Walker. Can you tell me or send me the exact version of the Windows 10 lite are you using? Thanks.
