### ISSUE TITLE
Can't download from Weibo

### ISSUE THREAD

**Issue by imgettingridofbritta** [ytdl-org/youtube-dl#29031]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
.\youtube-dl.exe https://weibo.com/1053932022/KfbfupgTV?ref=home"&"rid=0_0_1_5046670436339028950_0_0_0
[Weibo] KfbfupgTV: Downloading webpage
[Weibo] KfbfupgTV: Generating first-visit data
[Weibo] KfbfupgTV: Running first-visit callback
[Weibo] KfbfupgTV: Revisiting webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

**Comment by rautamiekka** [comment]
1) Missing `--verbose` flag. I add it twice just in case even if it's redundant.
2) You should double-quote the whole address, not only the chars under all circumstances.

But yeah, it still doesn't work:
With 2x `--verbose`:
```
# youtube-dl --verbose --verbose "https://weibo.com/1053932022/KfbfupgTV?ref=home&rid=0_0_1_5046670436339028950_0_0_0"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--verbose', 'https://weibo.com/1053932022/KfbfupgTV?ref=home&rid=0_0_1_5046670436339028950_0_0_0']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.8.8 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[Weibo] KfbfupgTV: Downloading webpage
[Weibo] KfbfupgTV: Generating first-visit data
[Weibo] KfbfupgTV: Running first-visit callback
[Weibo] KfbfupgTV: Revisiting webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\extractor\weibo.py", line 76, in _real_extract
    title = self._html_search_regex(
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Without `-verbose`:
```
# youtube-dl "https://weibo.com/1053932022/KfbfupgTV?ref=home&rid=0_0_1_5046670436339028950_0_0_0"
[Weibo] KfbfupgTV: Downloading webpage
[Weibo] KfbfupgTV: Generating first-visit data
[Weibo] KfbfupgTV: Running first-visit callback
[Weibo] KfbfupgTV: Revisiting webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by MS-1999** [comment]
same issue, any idea? Thanks in advance!
