### ISSUE TITLE
twitch.tv email 2fa challenge for subscriber video

### ISSUE THREAD

**Issue by Nzen** [ytdl-org/youtube-dl#29051]
## Checklist

- [x] I'm reporting a site feature request (yup, not a bug report)
- [x] I've verified that I'm running youtube-dl version **2021.04.26** (yup, just downloaded it)
- [x] I've searched the bugtracker for similar site feature requests including closed ones (yup, not resolved by https://github.com/ytdl-org/youtube-dl/pull/27790 ;; did not try ancient https://github.com/ytdl-org/youtube-dl/pull/20522)

## Description

Twitch has introduced an email based 2fa challenge for subscriber only videos. Is there some mechanism to have youtube-dl prompt me to provide the required code ?

### steps

0. (precondition) subscribe to the relevant twitch acccount, choose video link that requires subscription
1. use editcookie chrome extension to export twitch cookie to clipboard
2. save clipboard cookie json as twitchcookie.txt
3. curl -b twitchcookie.txt --cookie-jar twitch.txt https://www.twitch.tv/galacticluna
4. youtube-dl.exe --verbose -u ____ -p _____ --cookies=twitch.txt https://www.twitch.tv/videos/1018674451

Expected : video to download

#### Saw

Email in inbox with six digit code.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', '--cookies=twitch.txt', 'https://www.twitch.tv/videos/1018674451']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-92982-g282a471857, ffprobe N-92982-g282a471857
[debug] Proxy map: {}
[twitch:vod] Downloading login page
[twitch:vod] Logging in
ERROR: Unable to login. Twitch said: Please enter a Login Verification Code.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\common.py", line 533, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\common.py", line 437, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\twitch.py", line 57, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\twitch.py", line 112, in _login
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\twitch.py", line 89, in login_step
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\twitch.py", line 66, in fail
youtube_dl.utils.ExtractorError: Unable to login. Twitch said: Please enter a Login Verification Code.
```

**Comment by Nzen** [comment]
I guess it's worth noting that this email 2fa is their fallback for a user with 2fa disabled. At this time, they offer options for sms and authenticator app 2fa. Hopefully, the same input mechanism would serve for all three.
