### ISSUE TITLE
I can't download from Paramount Plus

### ISSUE THREAD

**Issue by AlejandroMesa22** [ytdl-org/youtube-dl#29089]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.05.16**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've searched the bugtracker for similar bug reports including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-F', 'https://www.paramountplus.com/shows/yo-soy-franky/video/GvrmB2nmQgk4posE5Se7GUOrMqxa08aO/yo-soy-franky-nace-franky/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.05.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[CBS] GvrmB2nmQgk4posE5Se7GUOrMqxa08aO: Downloading XML
ERROR: Could not find XML element title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\extractor\cbs.py", line 115, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\extractor\cbs.py", line 65, in _extract_video_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\utils.py", line 1911, in xpath_text
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\utils.py", line 1904, in xpath_element
youtube_dl.utils.ExtractorError: Could not find XML element title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I would like to know why I cannot download a paramount plus series from ytdl, I am new to using ytdl so I don't understand much.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30491

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/pull/30085
