### ISSUE TITLE
New version throws error when downloading from Safar "Unable to log in"

### ISSUE THREAD

**Issue by anishkgt** [ytdl-org/youtube-dl#29098]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.05.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: ['-u', 'PRIVATE', '--ignore-errors', '-c', '--no-warnings', '--console-title', '--batch-file=batch-file.txt', '--cookies', 'cookies.txt', '-o', '%(playlist_title)s/%(playlist_index)s-%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['--verbose']
[debug] Batch file urls: ['https://learning.oreilly.com/videos/total-comptia-cysa/9781789138672/']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.05.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[safari:course] Downloading login page
[safari:course] Logging in
[safari:course] Completing login
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\extractor\common.py", line 533, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\extractor\common.py", line 437, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\extractor\safari.py", line 29, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\extractor\safari.py", line 82, in _login
youtube_dl.utils.ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I tried to download a video from safari and i get the error mentioned in the verbose. I uses cookies instead of a username and password. It worked earlier but does not seem to be working with the new version.

**Comment by anishkgt** [comment]
I was using cookies earlier as my authentication is SSO via university but i still use the -u tag but when asked during execution i hit enter and it logs in using the cookies. All worked well before the new version.

**Comment by anishkgt** [comment]
So i enter the password now and i get this error 'Unable to download JSON metadata: HTTP Error 406: Not Acceptable (caused by HTTPError())'
Verbose error
`[debug] System config: []
[debug] User config: ['-u', 'PRIVATE', '-i', '--ignore-errors', '-c', '--no-warnings', '--console-title', '--batch-file=batch-file.txt', '--cookies', 'cookies.txt', '-o', '%(playlist_title)s/%(playlist_index)s-%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['--verbose']
[debug] Batch file urls: ['https://learning.oreilly.com/videos/total-comptia-cysa/9781789138672/']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.05.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[safari:course] Downloading login page
[safari:course] Logging in
ERROR: Unable to download JSON metadata: HTTP Error 406: Not Acceptable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default`

**Comment by anishkgt** [comment]
Trying with username and blank password with cookies file
`[debug] System config: []
[debug] User config: ['-u', 'PRIVATE', '-i', '--ignore-errors', '-c', '--no-warnings', '--console-title', '--batch-file=batch-file.txt', '--cookies', 'cookies.txt', '-o', '%(playlist_title)s/%(playlist_index)s-%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['--verbose']
[debug] Batch file urls: ['https://learning.oreilly.com/videos/total-comptia-cysa/9781789138672/']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.05.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[safari:course] Downloading login page
[safari:course] Logging in
ERROR: Unable to download JSON metadata: HTTP Error 406: Not Acceptable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default`

**Comment by anishkgt** [comment]
ok managed to solve it, here is the verbose output. When using Cookies the -u tag is mandatory but when asked for the password enter blank, i earlier used learning.orielly.com which gave also those errors and now tried with orielly.com
`[debug] System config: []
[debug] User config: ['-u', 'PRIVATE', '--ignore-errors', '-c', '--no-warnings', '--console-title', '--batch-file=batch-file.txt', '--cookies', 'cookies.txt', '-o', '%(playlist_title)s/%(playlist_index)s-%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['--verbose']
[debug] Batch file urls: ['https://learning.oreilly.com/videos/total-comptia-cysa/9781789138672/']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.05.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[safari:course] Downloading login page
[safari:course] 9781789138672: Downloading course JSON
[download] Downloading playlist: TOTAL: CompTIA CySA+ Cybersecurity Analyst (CS0-002)
[safari:course] playlist TOTAL: CompTIA CySA+ Cybersecurity Analyst (CS0-002): Collected 96 video ids (downloading 96 of them)
[download] Downloading video 1 of 96
[safari:api] Downloading login page
[safari:api] 9781789138672/video1_1: Downloading part JSON
[safari] Downloading login page
[safari] 9781789138672-video1_1: Downloading webpage
[safari] 9781789138672-video1_1: Downloading kaltura session JSON
[Kaltura] 9781789138672-video1_1: Downloading webpage
[Kaltura] 0_nlcbdrgp: Downloading video info JSON
[Kaltura] 0_nlcbdrgp: Checking mp4-10291 URL
[Kaltura] 0_nlcbdrgp: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1926081/sp/192608100/playManifest/entryId/0_nlcbdrgp/format/url/protocol/http/flavorId/0_u9mpgui8/ks/djJ8MTkyNjA4MXxzMCXtBj7uiSh_MU5s4KuCiypeuFsbWEZjZPOHdivWl0tYu1hO3mFRx9m0HXnRy79-xOElwB9RQjhZveRCorSCgMxFgfVKILjf44oR1NOP5g=='
[download] Destination: TOTAL - CompTIA CySA+ Cybersecurity Analyst (CS0-002)\01-Welcome to the Course.mp4
[download] 100% of 146.64MiB in 00:23`

**Comment by dev-sharan** [comment]
@anishkgt 

can you help how to get cookies and download from https://learning.oreilly.com/

**Comment by anishkgt** [comment]
Hi,
Assuming you have ytdl already up and running, you would need to install a plugin for Firefox that can export specific cookies. Once installed, login into your account on oreilly.com and click on the new cookie plugin you've just installed. Select cookies for oreilly.com and not learning.oreilly.com and save it to a folder that your ytdl installed. Once installed add this line '--cookies 'cookies.txt ' in youtube-dl.conf file. Now running the youtube-dl.exe should use the cookies to download the video from oreilly.com When running the file you would still need the -u and -p tags in the conf file. Leave them blank and when prompted in DOS hit enter.




    On Wednesday, June 2, 2021, 3:59:24 AM GMT+1, dev-sharan ***@***.***> wrote:  
 
 


@anishkgt

can you help how to get cookies and download from https://learning.oreilly.com/
