### ISSUE TITLE
[ComedyCentral] format selection broken

### ISSUE THREAD

**Issue by aphex3k** [ytdl-org/youtube-dl#29092]
## Checklist

- [X] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.05.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

Step 1: Format introspection
```
➜  The Daily Show youtube-dl -v --ignore-config -F https://www.cc.com/episodes/jre6kl/the-daily-show-with-trevor-noah-may-19-2021-barry-jenkins-logan-paul-season-26-ep-99
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--ignore-config', u'-F', u'https://www.cc.com/episodes/jre6kl/the-daily-show-with-trevor-noah-may-19-2021-barry-jenkins-logan-paul-season-26-ep-99']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.05.16
[debug] Python version 2.7.18 (CPython) - Linux-5.8.0-53-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg git-2021-05-15-bc40cd62, ffprobe git-2021-05-15-bc40cd62, rtmpdump 2.4
[debug] Proxy map: {}
[ComedyCentral] the-daily-show-with-trevor-noah-may-19-2021-barry-jenkins-logan-paul-season-26-ep-99: Downloading webpage
[ComedyCentral] 6f12d84c-8d2b-11eb-8774-70df2f866ace: Downloading info
[ComedyCentral] 9e60f3c5-63f0-4464-8e60-e748ad6b60a3: Extracting information
[ComedyCentral] 9e60f3c5-63f0-4464-8e60-e748ad6b60a3: Downloading video urls
[ComedyCentral] 9e60f3c5-63f0-4464-8e60-e748ad6b60a3: Downloading m3u8 information
[ComedyCentral] 831a63dc-bc85-4611-af85-21ff29fdd96b: Extracting information
[ComedyCentral] 831a63dc-bc85-4611-af85-21ff29fdd96b: Downloading video urls
[ComedyCentral] 831a63dc-bc85-4611-af85-21ff29fdd96b: Downloading m3u8 information
[ComedyCentral] 3809f26d-0724-434b-9518-ed54cd3e988b: Extracting information
[ComedyCentral] 3809f26d-0724-434b-9518-ed54cd3e988b: Downloading video urls
[ComedyCentral] 3809f26d-0724-434b-9518-ed54cd3e988b: Downloading m3u8 information
[ComedyCentral] ff0627c5-e906-4f26-98d6-afecd026abd0: Extracting information
[ComedyCentral] ff0627c5-e906-4f26-98d6-afecd026abd0: Downloading video urls
[ComedyCentral] ff0627c5-e906-4f26-98d6-afecd026abd0: Downloading m3u8 information
[download] Downloading playlist: May 19, 2021 - Barry Jenkins & Logan Paul
[ComedyCentral] playlist May 19, 2021 - Barry Jenkins & Logan Paul: Collected 4 video ids (downloading 4 of them)
[download] Downloading video 1 of 4
[info] Available formats for 9e60f3c5-63f0-4464-8e60-e748ad6b60a3:
format code  extension  resolution note
hls-583      mp4        384x216     583k , avc1.4D401E, 29.97fps, mp4a.40.2
hls-870      mp4        512x288     870k , avc1.4D401F, 29.97fps, mp4a.40.2
hls-1086     mp4        640x360    1086k , avc1.4D401F, 29.97fps, mp4a.40.2
hls-1268     mp4        768x432    1268k , avc1.4D401F, 29.97fps, mp4a.40.2
hls-1887     mp4        960x540    1887k , avc1.4D401F, 29.97fps, mp4a.40.2
hls-2893     mp4        1280x720   2893k , avc1.640028, 29.97fps, mp4a.40.2
hls-5799     mp4        1920x1080  5799k , avc1.640028, 29.97fps, mp4a.40.2 (best)
[download] Downloading video 2 of 4
[info] Available formats for 831a63dc-bc85-4611-af85-21ff29fdd96b:
format code  extension  resolution note
hls-660      mp4        384x216     660k , avc1.4D401E, 29.97fps, mp4a.40.2
hls-1004     mp4        512x288    1004k , avc1.4D401F, 29.97fps, mp4a.40.2
hls-1320     mp4        640x360    1320k , avc1.4D401F, 29.97fps, mp4a.40.2
hls-1519     mp4        768x432    1519k , avc1.4D401F, 29.97fps, mp4a.40.2
hls-2201     mp4        960x540    2201k , avc1.4D401F, 29.97fps, mp4a.40.2
hls-3212     mp4        1280x720   3212k , avc1.640028, 29.97fps, mp4a.40.2
hls-6228     mp4        1920x1080  6228k , avc1.640028, 29.97fps, mp4a.40.2 (best)
[download] Downloading video 3 of 4
[info] Available formats for 3809f26d-0724-434b-9518-ed54cd3e988b:
format code  extension  resolution note
hls-554      mp4        384x216     554k , avc1.4D401E, 29.97fps, mp4a.40.2
hls-799      mp4        512x288     799k , avc1.4D401F, 29.97fps, mp4a.40.2
hls-1062     mp4        640x360    1062k , avc1.4D401F, 29.97fps, mp4a.40.2
hls-1195     mp4        768x432    1195k , avc1.4D401F, 29.97fps, mp4a.40.2
hls-1747     mp4        960x540    1747k , avc1.4D401F, 29.97fps, mp4a.40.2
hls-2591     mp4        1280x720   2591k , avc1.640028, 29.97fps, mp4a.40.2
hls-5213     mp4        1920x1080  5213k , avc1.640028, 29.97fps, mp4a.40.2 (best)
[download] Downloading video 4 of 4
[info] Available formats for ff0627c5-e906-4f26-98d6-afecd026abd0:
format code  extension  resolution note
hls-352      mp4        384x216     352k , avc1.4D401E, 29.97fps, mp4a.40.2
hls-571      mp4        512x288     571k , avc1.4D401F, 29.97fps, mp4a.40.2
hls-972      mp4        640x360     972k , avc1.4D401F, 29.97fps, mp4a.40.2
hls-1316     mp4        768x432    1316k , avc1.4D401F, 29.97fps, mp4a.40.2
hls-2001     mp4        960x540    2001k , avc1.4D401F, 29.97fps, mp4a.40.2
hls-2909     mp4        1280x720   2909k , avc1.640028, 29.97fps, mp4a.40.2
hls-4983     mp4        1920x1080  4983k , avc1.640028, 29.97fps, mp4a.40.2 (best)
[download] Finished downloading playlist: May 19, 2021 - Barry Jenkins & Logan Paul
```

Step 2: Format selection
```
➜  The Daily Show youtube-dl -v --ignore-config -f "bestvideo[height<720]" https://www.cc.com/episodes/jre6kl/the-daily-show-with-trevor-noah-may-19-2021-barry-jenkins-logan-paul-season-26-ep-99
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--ignore-config', u'-f', u'bestvideo[height<720]', u'https://www.cc.com/episodes/jre6kl/the-daily-show-with-trevor-noah-may-19-2021-barry-jenkins-logan-paul-season-26-ep-99']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.05.16
[debug] Python version 2.7.18 (CPython) - Linux-5.8.0-53-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg git-2021-05-15-bc40cd62, ffprobe git-2021-05-15-bc40cd62, rtmpdump 2.4
[debug] Proxy map: {}
[ComedyCentral] the-daily-show-with-trevor-noah-may-19-2021-barry-jenkins-logan-paul-season-26-ep-99: Downloading webpage
[ComedyCentral] 6f12d84c-8d2b-11eb-8774-70df2f866ace: Downloading info
[ComedyCentral] 9e60f3c5-63f0-4464-8e60-e748ad6b60a3: Extracting information
[ComedyCentral] 9e60f3c5-63f0-4464-8e60-e748ad6b60a3: Downloading video urls
[ComedyCentral] 9e60f3c5-63f0-4464-8e60-e748ad6b60a3: Downloading m3u8 information
[ComedyCentral] 831a63dc-bc85-4611-af85-21ff29fdd96b: Extracting information
[ComedyCentral] 831a63dc-bc85-4611-af85-21ff29fdd96b: Downloading video urls
[ComedyCentral] 831a63dc-bc85-4611-af85-21ff29fdd96b: Downloading m3u8 information
[ComedyCentral] 3809f26d-0724-434b-9518-ed54cd3e988b: Extracting information
[ComedyCentral] 3809f26d-0724-434b-9518-ed54cd3e988b: Downloading video urls
[ComedyCentral] 3809f26d-0724-434b-9518-ed54cd3e988b: Downloading m3u8 information
[ComedyCentral] ff0627c5-e906-4f26-98d6-afecd026abd0: Extracting information
[ComedyCentral] ff0627c5-e906-4f26-98d6-afecd026abd0: Downloading video urls
[ComedyCentral] ff0627c5-e906-4f26-98d6-afecd026abd0: Downloading m3u8 information
[download] Downloading playlist: May 19, 2021 - Barry Jenkins & Logan Paul
[ComedyCentral] playlist May 19, 2021 - Barry Jenkins & Logan Paul: Collected 4 video ids (downloading 4 of them)
[download] Downloading video 1 of 4
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1077, in __process_iterable_entry
    entry, download=download, extra_info=extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 881, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1684, in process_video_result
    expected=True)
ExtractorError: requested format not available
```

Step 3: different format selection
```
➜  The Daily Show youtube-dl -i -v --ignore-config -f "worstvideo" https://www.cc.com/episodes/jre6kl/the-daily-show-with-trevor-noah-may-19-2021-barry-jenkins-logan-paul-season-26-ep-99
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-i', u'-v', u'--ignore-config', u'-f', u'worstvideo', u'https://www.cc.com/episodes/jre6kl/the-daily-show-with-trevor-noah-may-19-2021-barry-jenkins-logan-paul-season-26-ep-99']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.05.16
[debug] Python version 2.7.18 (CPython) - Linux-5.8.0-53-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg git-2021-05-15-bc40cd62, ffprobe git-2021-05-15-bc40cd62, rtmpdump 2.4
[debug] Proxy map: {}
[ComedyCentral] the-daily-show-with-trevor-noah-may-19-2021-barry-jenkins-logan-paul-season-26-ep-99: Downloading webpage
[ComedyCentral] 6f12d84c-8d2b-11eb-8774-70df2f866ace: Downloading info
[ComedyCentral] 9e60f3c5-63f0-4464-8e60-e748ad6b60a3: Extracting information
[ComedyCentral] 9e60f3c5-63f0-4464-8e60-e748ad6b60a3: Downloading video urls
[ComedyCentral] 9e60f3c5-63f0-4464-8e60-e748ad6b60a3: Downloading m3u8 information
[ComedyCentral] 831a63dc-bc85-4611-af85-21ff29fdd96b: Extracting information
[ComedyCentral] 831a63dc-bc85-4611-af85-21ff29fdd96b: Downloading video urls
[ComedyCentral] 831a63dc-bc85-4611-af85-21ff29fdd96b: Downloading m3u8 information
[ComedyCentral] 3809f26d-0724-434b-9518-ed54cd3e988b: Extracting information
[ComedyCentral] 3809f26d-0724-434b-9518-ed54cd3e988b: Downloading video urls
[ComedyCentral] 3809f26d-0724-434b-9518-ed54cd3e988b: Downloading m3u8 information
[ComedyCentral] ff0627c5-e906-4f26-98d6-afecd026abd0: Extracting information
[ComedyCentral] ff0627c5-e906-4f26-98d6-afecd026abd0: Downloading video urls
[ComedyCentral] ff0627c5-e906-4f26-98d6-afecd026abd0: Downloading m3u8 information
[download] Downloading playlist: May 19, 2021 - Barry Jenkins & Logan Paul
[ComedyCentral] playlist May 19, 2021 - Barry Jenkins & Logan Paul: Collected 4 video ids (downloading 4 of them)
[download] Downloading video 1 of 4
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1077, in __process_iterable_entry
    entry, download=download, extra_info=extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 881, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1684, in process_video_result
    expected=True)
ExtractorError: requested format not available

[download] Downloading video 2 of 4
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1077, in __process_iterable_entry
    entry, download=download, extra_info=extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 881, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1684, in process_video_result
    expected=True)
ExtractorError: requested format not available

[download] Downloading video 3 of 4
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1077, in __process_iterable_entry
    entry, download=download, extra_info=extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 881, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1684, in process_video_result
    expected=True)
ExtractorError: requested format not available

[download] Downloading video 4 of 4
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1077, in __process_iterable_entry
    entry, download=download, extra_info=extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 881, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1684, in process_video_result
    expected=True)
ExtractorError: requested format not available

[download] Finished downloading playlist: May 19, 2021 - Barry Jenkins & Logan Paul
```

## Description

In step 1 I can see many different video formats available for the URL provided.
In step 2 I select a specific format for download "bestvideo[height<720]" which should be available according to step 1.
In step 3 I selected a different format

The actual result is that the format selection fails and no video is downloaded.

When not selecting any format, it will download the 1080p version of all 4 videos in the playlist.

**Comment by aphex3k** [comment]
Of course that works. I feel stupid now...
