### ISSUE TITLE
extractor:ID number not working with Twitter

### ISSUE THREAD

**Issue by bonacker1** [ytdl-org/youtube-dl#29106]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by bonacker1** [comment]
For some reason the check boxes for the checklist before posting are greyed out.

I'm asking a question
I've looked through the README and FAQ for similar questions: Yes
I've searched the bugtracker for similar questions including closed ones: Yes
-----------------
I can get youtube-dl facebook:15digits  -- where 15 digits is the facebook ID for the video  --  as well as some other extractors to work, but twitter:[twitter ID] doesn't work. I see in the list of extractors that there are 4 different extractors for twitter: twitter, twitter:amplify, twitter:broadcast, and twitter:card. None of them  seem to work. Is the Twitter ID # a known issue not to work with the extractor name:ID # ?

I want to use it in a macro. The video downloads with youtube-dl when using the whole URL.

https://mobile.twitter.com/KatyTurNBC/status/1390691774490759170

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'twitter:1390691774490759170']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2021.02.04.1
[debug] Python version 3.4.4 (CPython) - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-76684-g1fe82ab
[debug] Proxy map: {}
ERROR: 'twitter:1390691774490759170' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:twitter:1390691774490759170" ) to search YouTube
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpgi7ngq0n\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpgi7ngq0n\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpgi7ngq0n\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpgi7ngq0n\build\youtube_dl\extractor\generic.py", line 2374, in _real_extract
youtube_dl.utils.ExtractorError: 'twitter:1390691774490759170' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:twitter:1390691774490759170" ) to search YouTube

**Comment by pukkandan** [comment]
the `key:id` style is only enabled for a few extractors. For most extractors, the URL must be given.  Except for the search/feeds, I don't think they are meant to be used by the end user anyway (since they are undocumented). For twitter, only the id part is ever used for the actual extraction, but not all websites are like so. So this style cannot be generalized

As a workaround, you can just use `https://twitter.com/whatever/status/<id>`
