### ISSUE TITLE
Periscope : AttributeError : 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by abayet** [ytdl-org/youtube-dl#29108]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.05.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
Traceback (most recent call last):
  File "d:\Test\Fuzzer\replay.py", line 28, in <module>
    ydl.download([url])
  File "C:\Users\antho\AppData\Local\Programs\Python\Python39\lib\youtube_dl\YoutubeDL.py", line 2059, in download
    res = self.extract_info(
  File "C:\Users\antho\AppData\Local\Programs\Python\Python39\lib\youtube_dl\YoutubeDL.py", line 799, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\antho\AppData\Local\Programs\Python\Python39\lib\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\antho\AppData\Local\Programs\Python\Python39\lib\youtube_dl\YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\antho\AppData\Local\Programs\Python\Python39\lib\youtube_dl\extractor\common.py", line 535, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\antho\AppData\Local\Programs\Python\Python39\lib\youtube_dl\extractor\twitter.py", line 653, in _real_extract
    info = self._parse_broadcast_data(broadcast, broadcast_id)
  File "C:\Users\antho\AppData\Local\Programs\Python\Python39\lib\youtube_dl\extractor\periscope.py", line 24, in _parse_broadcast_data
    is_live = broadcast.get('state').lower() == 'running'
AttributeError: 'NoneType' object has no attribute 'lower'
```

## Description

I am running youtube-dl embedded in a python script and the url "https://twitter.com/i/broadcasts/31XvxLzXUGlEh" generate the exception above. I investigated a bit on the bug and I think it happens because the broadcast dictionary keys have changed, and the key "state" is no more there.

**Comment by dirkf** [comment]
Replacing line 24 of `youtube_dl\extractor\periscope.py`:
```
        is_live = broadcast.get('state').lower() == 'running'                   
 ```
with
```
        is_live = (broadcast.get('state') or '').lower() == 'running'
 ```
would prevent the crash for non-live streams. No idea about live, though.

**Comment by dstftw** [comment]
>Hmm...this page doesn’t exist. Try searching for something else.
