### ISSUE TITLE
[Reddit]: requested format not available

### ISSUE THREAD

**Issue by 2011** [ytdl-org/youtube-dl#29125]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.05.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -f best -v 'https://v.redd.it/pdv6ctgpud071/HLSPlaylist.m3u8'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--restrict-filenames', '-o', '%(title)s-%(id)s-%(uploader)s.%(ext)s', '-w', '-f', 'best', '-v', 'https://v.redd.it/pdv6ctgpud071/HLSPlaylist.m3u8']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.05.16
[debug] Python version 3.8.9 (CPython) - Linux-5.10.27...
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[Reddit] pdv6ctgpud071: Downloading m3u8 information
[Reddit] pdv6ctgpud071: Downloading MPD manifest
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 847, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 881, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1683, in process_video_result
    raise ExtractorError('requested format not available',
youtube_dl.utils.ExtractorError: requested format not available
```

## Description

Don't really understand much here (never tried to download anything from Reddit before).

Downloading the .m3u8 file gives:

```
$ dog HLSPlaylist.m3u8     
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-MEDIA:URI="HLS_AUDIO_64_K.m3u8",TYPE=AUDIO,GROUP-ID="0",NAME="audio 0",DEFAULT=YES,AUTOSELECT=YES
#EXT-X-MEDIA:URI="HLS_AUDIO_160_K.m3u8",TYPE=AUDIO,GROUP-ID="1",NAME="audio 1",DEFAULT=YES,AUTOSELECT=YES
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,BANDWIDTH=384000,AVERAGE-BANDWIDTH=347000,RESOLUTION=400x226,CODECS="avc1.42001e,mp4a.40.2",AUDIO="0"
HLS_224.m3u8
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,BANDWIDTH=604000,AVERAGE-BANDWIDTH=543000,RESOLUTION=480x270,CODECS="avc1.42001e,mp4a.40.2",AUDIO="0"
HLS_270.m3u8
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,BANDWIDTH=482000,AVERAGE-BANDWIDTH=444000,RESOLUTION=400x226,CODECS="avc1.42001e,mp4a.40.2",AUDIO="1"
HLS_224.m3u8
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,BANDWIDTH=702000,AVERAGE-BANDWIDTH=640000,RESOLUTION=480x270,CODECS="avc1.42001e,mp4a.40.2",AUDIO="1"
HLS_270.m3u8
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=77934,RESOLUTION=400x226,CODECS="avc1.42001e",URI="HLS_224-iframe.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=127840,RESOLUTION=480x270,CODECS="avc1.42001e",URI="HLS_270-iframe.m3u8"
```

Downloaded HLS_270-iframe.m3u8, but have never seen this particular format (byteranges) before.

```
$ dog HLS_270-iframe.m3u8 
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:3
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-I-FRAMES-ONLY
#EXTINF:3,
#EXT-X-BYTERANGE:20680@376
HLS_270.ts
#EXTINF:3,
#EXT-X-BYTERANGE:24816@172020
HLS_270.ts
#EXTINF:3,
#EXT-X-BYTERANGE:23876@345168
HLS_270.ts
#EXTINF:3,
#EXT-X-BYTERANGE:23876@526212
HLS_270.ts
#EXTINF:3,
#EXT-X-BYTERANGE:18800@713836
HLS_270.ts
#EXTINF:3,
#EXT-X-BYTERANGE:24440@892812
HLS_270.ts
#EXTINF:3,
#EXT-X-BYTERANGE:18988@1076112
HLS_270.ts
#EXTINF:3,
#EXT-X-BYTERANGE:19552@1273136
HLS_270.ts
#EXTINF:3,
#EXT-X-BYTERANGE:22184@1432184
HLS_270.ts
#EXTINF:3,
#EXT-X-BYTERANGE:19740@1635600
HLS_270.ts
#EXTINF:3,
#EXT-X-BYTERANGE:24064@1792580
HLS_270.ts
#EXTINF:2.9,
#EXT-X-BYTERANGE:23312@1970804
HLS_270.ts
#EXTINF:3,
#EXT-X-BYTERANGE:43992@2142636
HLS_270.ts
#EXTINF:3,
#EXT-X-BYTERANGE:47376@2305632
HLS_270.ts
#EXTINF:3,
#EXT-X-BYTERANGE:47940@2463740
HLS_270.ts
#EXTINF:3,
#EXT-X-BYTERANGE:23876@2655500
HLS_270.ts
#EXTINF:3,
#EXT-X-BYTERANGE:27448@2821880
HLS_270.ts
#EXTINF:0.3,
#EXT-X-BYTERANGE:20492@3000856
HLS_270.ts
#EXT-X-ENDLIST
```

Downloaded https://v.redd.it/pdv6ctgpud071/HLS_270.ts, which contains the entire (51-second) video, but no audio.

An audio .m3u8 looks like the video one (but with longer segments).

```
$ dog HLS_AUDIO_160_K.m3u8
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:5
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:5.9675,
#EXT-X-BYTERANGE:123403@0
HLS_AUDIO_160_K.aac
#EXTINF:5.9907,
#EXT-X-BYTERANGE:123753@123403
HLS_AUDIO_160_K.aac
#EXTINF:6.0604,
#EXT-X-BYTERANGE:124693@247156
HLS_AUDIO_160_K.aac
#EXTINF:5.9211,
#EXT-X-BYTERANGE:124639@371849
HLS_AUDIO_160_K.aac
#EXTINF:6.0836,
#EXT-X-BYTERANGE:124431@496488
HLS_AUDIO_160_K.aac
#EXTINF:5.8746,
#EXT-X-BYTERANGE:121149@620919
HLS_AUDIO_160_K.aac
#EXTINF:6.0372,
#EXT-X-BYTERANGE:123477@742068
HLS_AUDIO_160_K.aac
#EXTINF:6.0372,
#EXT-X-BYTERANGE:124482@865545
HLS_AUDIO_160_K.aac
#EXTINF:3.3205,
#EXT-X-BYTERANGE:68425@990027
HLS_AUDIO_160_K.aac
#EXT-X-ENDLIST
```

The audio file (https://v.redd.it/pdv6ctgpud071/HLS_AUDIO_160_K.aac) contains the entire audio.

**Comment by kikuyan** [comment]
It seems that video only stream is incorrectly labeled 'best'.
```
$ youtube-dl https://v.redd.it/pdv6ctgpud071/ -F
[Reddit] pdv6ctgpud071: Downloading m3u8 information
[Reddit] pdv6ctgpud071: Downloading MPD manifest
[info] Available formats for pdv6ctgpud071:
format code          extension  resolution note
hls-0-audio_0        mp4        audio only 
hls-1-audio_1        mp4        audio only 
dash-audio_0_131791  m4a        audio only DASH audio  131k , m4a_dash container, mp4a.40.2 (48000Hz)
hls-347              mp4        400x226     347k , avc1.42001e, video only
hls-444              mp4        400x226     444k , avc1.42001e, video only
hls-543              mp4        480x270     543k , avc1.42001e, video only
dash-video_572996    mp4        426x240    DASH video  572k , mp4_dash container, avc1.4D401E, 30fps, video only
hls-640              mp4        480x270     640k , avc1.42001e, video only
dash-video_741765    mp4        640x360    DASH video  741k , mp4_dash container, avc1.4D401E, 30fps, video only (best)
```
If you remove `-f best`, dash-video_741765 + dash-audio_0_131791 will be downloaded.

And looking at the source code, you don't need HLSPlaylist.m3u8 part in the url. youtube-dl automatically appends it for HLS (and DASHPlaylist.mpd for DASH).

**Comment by dstftw** [comment]
https://v.redd.it/pdv6ctgpud071/HLSPlaylist.m3u8 has no audio+video formats.
