### ISSUE TITLE
Support for developer.ibm.com videos

### ISSUE THREAD

**Issue by xmstspider** [ytdl-org/youtube-dl#29133]
## Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running youtube-dl version **2021.05.16**
- [X] I've searched the bugtracker for similar feature requests including closed ones

## Description

It would be great to gave support for videos from developer.ibm.com

**Video example**: [https://developer.ibm.com/conferences/aot-prevail/availability/wd1_hopkins_emea_keynotes/](https://developer.ibm.com/conferences/aot-prevail/availability/wd1_hopkins_emea_keynotes/)

### youtube-dl output:

[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--ignore-errors', '--no-overwrites', '--add-metadata', '--keep-video', '-o', '%(title)s.%(ext)s', '--format', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', 'https://developer.ibm.com/conferences/aot-prevail/availability/wd1_hopkins_emea_keynotes/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.05.16
[debug] Python version 3.9.5 (CPython) - Linux-5.12.6-300.fc34.x86_64-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[generic] wd1_hopkins_emea_keynotes: Requesting header
WARNING: Falling back on generic information extractor.
[generic] wd1_hopkins_emea_keynotes: Downloading webpage
[generic] wd1_hopkins_emea_keynotes: Extracting information
ERROR: Unsupported URL: https://developer.ibm.com/conferences/aot-prevail/availability/wd1_hopkins_emea_keynotes/
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 814, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 835, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/generic.py", line 3520, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://developer.ibm.com/conferences/aot-prevail/availability/wd1_hopkins_emea_keynotes/

**Comment by xmstspider** [comment]
I am using youtube-dl version **2021-06-06**, it is not working:
`youtube-dl -v https://developer.ibm.com/conferences/aot-prevail/availability/wd1_hopkins_emea_keynotes/
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://developer.ibm.com/conferences/aot-prevail/availability/wd1_hopkins_emea_keynotes/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.5 (CPython) - Linux-5.12.9-300.fc34.x86_64-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[generic] wd1_hopkins_emea_keynotes: Requesting header
WARNING: Falling back on generic information extractor.
[generic] wd1_hopkins_emea_keynotes: Downloading webpage
[generic] wd1_hopkins_emea_keynotes: Extracting information
[ustream] 127810545: Downloading JSON metadata
[ustream] 127810545: Downloading connection info
[ustream] 127810545: Downloading stream info
[ustream] 127810545: Downloading connection info (try 2)
[ustream] 127810545: Downloading stream info (try 2)
[ustream] 127810545: Downloading connection info (try 3)
[ustream] 127810545: Downloading stream info (try 3)
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 814, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 835, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/ustream.py", line 220, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`
