### ISSUE TITLE
Cannot download Episode from CBS.com (ERROR: No video formats found)

### ISSUE THREAD

**Issue by rgiuffre** [ytdl-org/youtube-dl#29170]
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2021.05.16**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.cbs.com/shows/macgyver/video/7e5AojM8iWLYUpCjTi1cpaeA2c1JSDbU/macgyver-abduction-memory-time-fireworks-dispersal/']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2021.05.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-05-26-git-7a879cce37-full_build-www.gyan.dev, ffprobe 2021-05-26-git-7a879cce37-full_build-www.gyan.dev
[debug] Proxy map: {}
[CBS] 7e5AojM8iWLYUpCjTi1cpaeA2c1JSDbU: Downloading XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\extractor\cbs.py", line 115, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\extractor\cbs.py", line 97, in _extract_video_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8rlhijs0\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

## Description

Cannot download this link:
https://www.cbs.com/shows/macgyver/video/7e5AojM8iWLYUpCjTi1cpaeA2c1JSDbU/macgyver-abduction-memory-time-fireworks-dispersal/

**Comment by rgiuffre** [comment]
Same error with 2021-06-06 version of youtube-dl.exe (Windows 10)

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.cbs.com/shows/macgyver/video/7e5AojM8iWLYUpCjTi1cpaeA2c1JSDbU/macgyver-abduction-memory-time-fireworks-dispersal/']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-06-02-git-071930de72-full_build-www.gyan.dev, ffprobe 2021-06-02-git-071930de72-full_build-www.gyan.dev
[debug] Proxy map: {}
[CBS] 7e5AojM8iWLYUpCjTi1cpaeA2c1JSDbU: Downloading XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\cbs.py", line 115, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\cbs.py", line 97, in _extract_video_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by rgiuffre** [comment]
Can someone take a look at this? I'm afraid the episode is going to be "locked" soon. It aired on April 30th, 2021 and I don't know how long it's going to be unlocked.
Thanks!

**Comment by rgiuffre** [comment]
I don't think the issue is DRM. ALL of the previous episodes are playable/downloadable.  So why make 1 and only 1 episode DRM?
Doesn't make sense.
