### ISSUE TITLE
unable to download age restricted videos

### ISSUE THREAD

**Issue by beans-coding** [ytdl-org/youtube-dl#29194]
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2021.05.16**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl https://www.youtube.com/watch?v=Iy5wBJ9_GTI -f 18 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=Iy5wBJ9_GTI', '-f', '18', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2020-10-11-git-7ea4bcff7b-full_build-www.gyan.dev, ffprobe 2020-10-11-git-7ea4bcff7b-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] Iy5wBJ9_GTI: Downloading webpage
[youtube] Iy5wBJ9_GTI: Refetching age-gated info webpage
WARNING: unable to download video info webpage: HTTP Error 404: Not Found
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\youtube.py", line 1698, in _real_extract
youtube_dl.utils.ExtractorError: Sign in to confirm your age
This video may be inappropriate for some users.
```

## Description

when i try to download an age restricted video it tells me to log in. i didnt have to log in before, why do i have to now?
there is a similar issue but i am not trying to pass cookies as i didnt previously have to, and i am using an american vpn node

**Comment by colethedj** [comment]
Should be fixed by https://github.com/ytdl-org/youtube-dl/commit/24297a42efc52862cb9510d32b28efd7faf49af6, but the release is still to come.
