### ISSUE TITLE
Extraction error on vimeo.com/channel/staffpicks/ URLs

### ISSUE THREAD

**Issue by veikk0** [ytdl-org/youtube-dl#29205]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.05.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose https://vimeo.com/channels/staffpicks/507304309
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://vimeo.com/channels/staffpicks/507304309']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.05.16
[debug] Python version 3.8.5 (CPython) - Linux-5.8.0-53-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg N-102461-g8649f5dca6, ffprobe N-102461-g8649f5dca6
[debug] Proxy map: {}
[vimeo] 507304309: Downloading webpage
ERROR: Unable to extract config URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/veikk0/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/veikk0/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/veikk0/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/veikk0/.local/lib/python3.8/site-packages/youtube_dl/extractor/vimeo.py", line 682, in _real_extract
    config_url = self._html_search_regex(
  File "/home/veikk0/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/veikk0/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract config URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

youtube-dl errors on extraction when a URL from the [Vimeo Staff Picks channel](https://vimeo.com/channels/staffpicks) is provided. "Non-channelified" URLs to the same videos work fine though.

* Works: https://vimeo.com/539298497
* Doesn't work: https://vimeo.com/channels/staffpicks/539298497
* Works: https://vimeo.com/556349462
* Doesn't work: https://vimeo.com/channels/staffpicks/556349462

There seems to be something special about these staff picks channel pages, since URLs from other channels I've tried work fine. For example, there's no issue with these URLs:

* https://vimeo.com/channels/musicvideoland/496270099
* https://vimeo.com/channels/booooooom/552912710

**Comment by october262** [comment]
for this link - https://vimeo.com/channels/staffpicks/539298497  
try with youtube-dl --force-generic-extractor https://vimeo.com/channels/staffpicks/539298497

same goes for this link - https://vimeo.com/channels/staffpicks/556349462

**Comment by Kikobeats** [comment]
I have the same error:

```
youtube-dl https://vimeo.com/channels/staffpicks/287117046
[vimeo] 287117046: Downloading webpage
ERROR: Unable to extract config URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

My youtube-dl is the latest in this moment:

```bash
youtube-dl --version
2021.06.06
```

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29764
