### ISSUE TITLE
Twitch Clips Downloading Broken, HTTP Error 404

### ISSUE THREAD

**Issue by mugenmidget** [ytdl-org/youtube-dl#29213]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.05.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
D:\videos\v108>youtube-dl -v https://clips.twitch.tv/BetterOpenRaisinHumbleLife-S0R5kF6eGb8nEd6d
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://clips.twitch.tv/BetterOpenRaisinHumbleLife-S0R5kF6eGb8nEd6d']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.02.10
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-94324-g806ac7da69, ffprobe N-94324-g806ac7da69
[debug] Proxy map: {}
[twitch:clips] BetterOpenRaisinHumbleLife-S0R5kF6eGb8nEd6d: Downloading clip GraphQL
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://production.assets.clips.twitchcdn.net/AT-cm%7C1194711128.mp4'
ERROR: unable to download video data: HTTP Error 404:
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym44\build\youtube_dl\YoutubeDL.py", line 1963, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym44\build\youtube_dl\YoutubeDL.py", line 1902, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym44\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym44\build\youtube_dl\downloader\http.py", line 351, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym44\build\youtube_dl\downloader\http.py", line 116, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym44\build\youtube_dl\downloader\http.py", line 110, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym44\build\youtube_dl\YoutubeDL.py", line 2275, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404:
```

## Description

Getting an "unable to download video data" error and "HTTP Error 404" for Twitch clips in Youtube-DL 2021.05.16.  It was working fine a couple of weeks ago.  No credentials should be required.  These are viewable in a browser and the download link provided by Twitch works.

Some example commands/URLs:

youtube-dl https://clips.twitch.tv/BetterOpenRaisinHumbleLife-S0R5kF6eGb8nEd6d
youtube-dl https://clips.twitch.tv/SplendidSucculentPeachPunchTrees-sxReptXUjosu9VpI
youtube-dl https://clips.twitch.tv/ColdbloodedElegantLattePipeHype-rngvz16JJE5MxsuU
youtube-dl https://clips.twitch.tv/VastKindPicklesYouDontSay-y98cI0RbzwVgn7jK
youtube-dl https://clips.twitch.tv/AverageSparklingCarabeefNotLikeThis-WKKG5JOpwQ3uE8AW
youtube-dl https://clips.twitch.tv/SleepyBreakableHippoRalpherZ-hkapS0eVrbnVcc_5
youtube-dl https://clips.twitch.tv/ImpossibleAmazonianSardineEleGiggle-upg3kTLv8LQnpvH4
youtube-dl https://clips.twitch.tv/ResourcefulLittleRedpandaKippa-VfKaoC2owCrDz9UD
youtube-dl https://clips.twitch.tv/SilkyCloudyWaspJebaited-PzG-I_8QuH2CEtrb
youtube-dl https://clips.twitch.tv/DrabSolidConsolePlanking-Ip5aHxyc0Cox_Oqn
youtube-dl https://clips.twitch.tv/GorgeousSaltyTrayPeteZaroll-9_FOWe44_Cym1OVz
youtube-dl https://clips.twitch.tv/SpotlessShakingWombatPeteZarollTie-_cB6nczOSjBMHYcC
youtube-dl https://clips.twitch.tv/AffluentSpunkyMouseCeilingCat-CD4yyyk-otxxEmZy
youtube-dl https://clips.twitch.tv/CreativeUgliestTurtleTwitchRPG-g6Kby9Sy8Dr5E3OO
youtube-dl https://clips.twitch.tv/RespectfulSquareTigerBIRB-psXGoldDYOy3llXQ
youtube-dl https://clips.twitch.tv/PoorFragileSageNomNom-o3cAcau6UOcZeoPj
youtube-dl https://clips.twitch.tv/EnergeticCloudyPotatoTooSpicy-dQHJelfuPCEVFucD
youtube-dl https://clips.twitch.tv/PlainIgnorantEndiveYouDontSay-E_1Y5o9OKE4s66YL
youtube-dl https://clips.twitch.tv/GentleCleverSalamanderWoofer-Mpj_d34LFkpGUL9s
youtube-dl https://clips.twitch.tv/BrightCuriousSwordTheRinger-FsBtd0RwtrrmxhPp
youtube-dl https://clips.twitch.tv/ShakingComfortableSnoodBudStar-dWCC0Kz0p2Rvh_NB
youtube-dl https://clips.twitch.tv/ConfidentLovelyPlumOSfrog-pbt1LHI85gRMvgOi

**Comment by mugenmidget** [comment]
What's also strange is that the URL retrieved by the downloader is correct/valid and can be downloaded manually without issue (https://production.assets.clips.twitchcdn.net/AT-cm%7C1194711128.mp4).

**Comment by mugenmidget** [comment]
Duplicate of https://github.com/ihabunek/twitch-dl/issues/64
