### ISSUE TITLE
Some publicly available videos on mediaset play do not work (geographical restriction from youtube-dl but no such restriction from the browser)

### ISSUE THREAD

**Issue by bugnano** [ytdl-org/youtube-dl#29218]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.05.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.mediasetplay.mediaset.it/video/indaginiadaltaquotastagioneiv/in-caduta-libera_F307562901000202']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.05.16
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-72-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[Mediaset] F307562901000202: Downloading JSON metadata
[Mediaset] F307562901000202: Downloading MPEG4 SD SMIL data
[Mediaset] F307562901000202: Downloading MPEG4 HD SMIL data
ERROR: This content is not available in your location.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "/home/bgj/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/bgj/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/bgj/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/bgj/.local/lib/python3.8/site-packages/youtube_dl/extractor/mediaset.py", line 157, in _real_extract
    raise first_e
  File "/home/bgj/.local/lib/python3.8/site-packages/youtube_dl/extractor/mediaset.py", line 142, in _real_extract
    tp_formats, tp_subtitles = self._extract_theplatform_smil(
  File "/home/bgj/.local/lib/python3.8/site-packages/youtube_dl/extractor/theplatform.py", line 47, in _extract_theplatform_smil
    self.raise_geo_restricted(error_element.attrib['abstract'])
  File "/home/bgj/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 947, in raise_geo_restricted
    raise GeoRestrictedError(msg, countries=countries)
youtube_dl.utils.GeoRestrictedError: This content is not available in your location.

## Description

I get that youtube-dl does not work with DRM restricted videos, but on mediaset play usually they are behind a login wall.

Some videos on Mediaset Play work fine on youtube-dl, and some others don't.

This is an example of a video that works fine in a browser, without needing to log in, but does not work with youtube-dl.

The error is more strange, in the sense that I get that contents from Mediaset Play are restriced to Italy, but I tried both the browser and youtube-dl from Italy, so the geographical restriction makes absolutely no sense here.

**Comment by dirkf** [comment]
Apparently need to back-port https://github.com/yt-dlp/yt-dlp/commit/02226207254f6f694462d40b41e5deb4ccc25588 ?

**Comment by 89z** [comment]
geo block:

> For you who live abroad with an Italian heart
> the international channel of Mediaset visible only outside the Italian territory
