### ISSUE TITLE
Twitch.tv ERROR: unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by ballsystemlord** [ytdl-org/youtube-dl#29221]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--socket-timeout', '60', '-i', '--no-call-home', '--restrict-filenames', '--yes-playlist', '--hls-prefer-native', '--write-auto-sub', '--write-description', '--reject-title', 'dark souls', '--write-sub', 'https://www.twitch.tv/deosbestiary/videos?filter=all&sort=time', '--verbose']
[debug] Encodings: locale ANSI_X3.4-1968, fs ascii, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.5.3 (CPython) - Linux-5.11.17-nopreempt-AMDGPU-dav12-x86_64-with-debian-9
[debug] exe versions: ffmpeg 3.2.15-0, ffprobe 3.2.15-0, rtmpdump 2.4
[debug] Proxy map: {}
[download] Downloading playlist: deosbestiary - All Videos sorted by Date
[TwitchVideos] deosbestiary: Downloading Videos GraphQL page 1
[TwitchVideos] playlist deosbestiary - All Videos sorted by Date: Downloading 76 videos
[download] Downloading video 1 of 76
[twitch:vod] 1042066185: Downloading stream metadata GraphQL
[twitch:vod] 1042066185: Downloading video access token GraphQL
[twitch:vod] 1042066185: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: There's no description to write.
[info] Writing video subtitles to: 3D_BLENDER_SCULPTING_lady_in_armour_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1042066185.rechat.json
[debug] Invoking downloader on 'https://d2vjef5jvl6bfs.cloudfront.net/d150e14501a657781076_deosbestiary_42156661997_1622520832/chunked/index-muted-YBFKVKVH75.m3u8'
[download] 3D_BLENDER_SCULPTING_lady_in_armour_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1042066185.mp4 has already been downloaded

[download] 100% of 6.03GiB
[debug] ffmpeg command line: ffprobe -show_streams file:3D_BLENDER_SCULPTING_lady_in_armour_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1042066185.mp4
[ffmpeg] Fixing malformed AAC bitstream in "3D_BLENDER_SCULPTING_lady_in_armour_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1042066185.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:3D_BLENDER_SCULPTING_lady_in_armour_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1042066185.mp4 -c copy -f mp4 -bsf:a aac_adtstoasc file:3D_BLENDER_SCULPTING_lady_in_armour_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1042066185.temp.mp4
[download] Downloading video 2 of 76
[twitch:vod] 1040368163: Downloading stream metadata GraphQL
[twitch:vod] 1040368163: Downloading video access token GraphQL
[twitch:vod] 1040368163: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: There's no description to write.
[info] Writing video subtitles to: 3D_BLENDER_SCULPTING_lady_in_armour_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1040368163.rechat.json
[debug] Invoking downloader on 'https://d2vjef5jvl6bfs.cloudfront.net/a31ff5418a820b115329_deosbestiary_42131237645_1622390785/chunked/index-dvr.m3u8'
[download] 3D_BLENDER_SCULPTING_lady_in_armour_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1040368163.mp4 has already been downloaded

[download] 100% of 1.36GiB
[debug] ffmpeg command line: ffprobe -show_streams file:3D_BLENDER_SCULPTING_lady_in_armour_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1040368163.mp4
[ffmpeg] Fixing malformed AAC bitstream in "3D_BLENDER_SCULPTING_lady_in_armour_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1040368163.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:3D_BLENDER_SCULPTING_lady_in_armour_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1040368163.mp4 -c copy -f mp4 -bsf:a aac_adtstoasc file:3D_BLENDER_SCULPTING_lady_in_armour_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1040368163.temp.mp4
[download] Downloading video 3 of 76
[twitch:vod] 1036844088: Downloading stream metadata GraphQL
[twitch:vod] 1036844088: Downloading video access token GraphQL
[twitch:vod] 1036844088: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: There's no description to write.
[info] Writing video subtitles to: Highlight_-_3D_BLENDER_SCULPTING_City_of_Heroes_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1036844088.rechat.json
[debug] Invoking downloader on 'https://d2vjef5jvl6bfs.cloudfront.net/30bf5f2ef796bb16fb79_deosbestiary_53034172636_9921703560/chunked/highlight-1036844088.m3u8'
[download] Highlight_-_3D_BLENDER_SCULPTING_City_of_Heroes_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1036844088.mp4 has already been downloaded

[download] 100% of 627.70MiB
[debug] ffmpeg command line: ffprobe -show_streams file:Highlight_-_3D_BLENDER_SCULPTING_City_of_Heroes_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1036844088.mp4
[ffmpeg] Fixing malformed AAC bitstream in "Highlight_-_3D_BLENDER_SCULPTING_City_of_Heroes_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1036844088.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:Highlight_-_3D_BLENDER_SCULPTING_City_of_Heroes_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1036844088.mp4 -c copy -f mp4 -bsf:a aac_adtstoasc file:Highlight_-_3D_BLENDER_SCULPTING_City_of_Heroes_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1036844088.temp.mp4
[download] Downloading video 4 of 76
[twitch:vod] 1036843872: Downloading stream metadata GraphQL
[twitch:vod] 1036843872: Downloading video access token GraphQL
[twitch:vod] 1036843872: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: There's no description to write.
[info] Writing video subtitles to: Highlight_-_3D_BLENDER_SCULPTING_City_of_Heroes_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1036843872.rechat.json
[debug] Invoking downloader on 'https://d2vjef5jvl6bfs.cloudfront.net/adf60ea853228dd754ca_deosbestiary_93789169332_7952167669/chunked/highlight-1036843872.m3u8'
[download] Highlight_-_3D_BLENDER_SCULPTING_City_of_Heroes_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1036843872.mp4 has already been downloaded

[download] 100% of 975.04MiB
[debug] ffmpeg command line: ffprobe -show_streams file:Highlight_-_3D_BLENDER_SCULPTING_City_of_Heroes_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1036843872.mp4
[ffmpeg] Fixing malformed AAC bitstream in "Highlight_-_3D_BLENDER_SCULPTING_City_of_Heroes_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1036843872.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:Highlight_-_3D_BLENDER_SCULPTING_City_of_Heroes_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1036843872.mp4 -c copy -f mp4 -bsf:a aac_adtstoasc file:Highlight_-_3D_BLENDER_SCULPTING_City_of_Heroes_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1036843872.temp.mp4
[download] Downloading video 5 of 76
[twitch:vod] 1036843344: Downloading stream metadata GraphQL
[twitch:vod] 1036843344: Downloading video access token GraphQL
[twitch:vod] 1036843344: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: There's no description to write.
[info] Writing video subtitles to: Highlight_-_3D_BLENDER_SCULPTING_City_of_Heroes_Pushing_myself_over_the_limit_yt_ig_CoinsShop-v1036843344.rechat.json
[debug] Invoking downloader on 'https://d2vjef5jvl6bfs.cloudfront.net/e3b039ac02b48c0036cc_deosbestiary_21957195972_9843073646/chunked/index-muted-OLAJQ5HNQA.m3u8'
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl-2021.6.6-py3.5.egg/youtube_dl/YoutubeDL.py", line 1976, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl-2021.6.6-py3.5.egg/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl-2021.6.6-py3.5.egg/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl-2021.6.6-py3.5.egg/youtube_dl/downloader/hls.py", line 64, in real_download
    urlh = self.ydl.urlopen(self._prepare_url(info_dict, man_url))
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl-2021.6.6-py3.5.egg/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

## Description

BEFORE you think of closing this because I didn't check one of the boxes, please be aware that yt-dl doesn't tell me which video URL it's trying to get so I can't test it in my browser. I do know that I could enter the m3u8 URL above into it (and I did try that without success), but then I might need some additional headers or cookies from the site to allow access. Alternatively, maybe yt-dl doesn't have the URL correct or something.
Since it's inside of the channel's videos list I'm assuming that it's not private or something.
If there is anything else you need in the way of information, just yell.

Thanks!

**Comment by dstftw** [comment]
Server side error. Video 1036843344 does not play in browser either.
