### ISSUE TITLE
m6 rtl no longer works

### ISSUE THREAD

**Issue by melanie-30** [ytdl-org/youtube-dl#29230]
### **Checklist**
✔️ I'm reporting a broken site support
✔️ I've verified that I'm running youtube-dl version **2021.06.06**
✔️ I've checked that all provided URLs are alive and playable in a browser
✔️ I've checked that all URLs and arguments with special characters are properly quoted or escaped
✔️ I've searched the bugtracker for similar issues including closed ones

### **Verbose log**
```
11:10  debian@toshiba  ~ ->
  $ ->  youtube-dl -F --verbose  https://www.6play.fr/zone-interdite-p_845/peres-maris-et-icones-du-foot-les-bleus-a-c-ur-ouvert-c_12874803
[debug] System config: []
[debug] User config: ['--cache-dir', '/tmp', '--no-playlist', '-o', '/mnt/DATA/Youtube-dl/%(title)s.%(ext)s', '-f', 'bestvideo[height<=4320]+bestaudio/best[height<=720]']
[debug] Custom config: []
[debug] Command-line args: ['-F', '--verbose', 'https://www.6play.fr/zone-interdite-p_845/peres-maris-et-icones-du-foot-les-bleus-a-c-ur-ouvert-c_12874803']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.2 (CPython) - Linux-4.19.0-16-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0
[debug] Proxy map: {}
[6play] 12874803: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/sixplay.py", line 113, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
### **Description**
Hey,
The replay sites of the m6 group no longer work with youtube-dl.
Everything works fine from Firefox.
The bug persists for several months now.

I tried from Debian, Manjaro, and Fedora, the bug is reproducible whether it is with the official repository package, or with the version taken from Github.

Thank you.

**Comment by october262** [comment]
try using the cookies.txt file command

**Comment by melanie-30** [comment]
can't a more user-friendly fix be made?
A month ago, the download from 6play was working normally.
Probably a problem with the DRM of the channel.

**Comment by melanie-30** [comment]
Closing the ticket because obviously no help or solution.

**Comment by dirkf** [comment]
See #24967.
