### ISSUE TITLE
Broken site: Hotstar.com ERROR Failed to parse JSON, caused by JSON Decode Error

### ISSUE THREAD

**Issue by TheJags** [ytdl-org/youtube-dl#29254]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.06.06**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE:

youtube-dl --version
2021.06.06

youtube-dl -Fv https://www.hotstar.com/in/tv/yeh-rishta-kya-kehlata-hai/586/kartiks-promise-to-sirat/1000262304
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-Fv', 'https://www.hotstar.com/in/tv/yeh-rishta-kya-kehlata-hai/586/kartiks-promise-to-sirat/1000262304']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.5 (CPython) - Linux-5.13.0-051300rc5-generic-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[hotstar] 1000262304: Downloading webpage
[hotstar] 1000262304: Downloading JSON metadata
ERROR: 1000262304: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 906, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 906, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/hotstar.py", line 140, in _real_extract
    self._USER_TOKEN = self._call_api_v2('um/v3/users', video_id, {
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/hotstar.py", line 63, in _call_api_v2
    message = self._parse_json(e.cause.read().decode(), video_id)['message']
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 910, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: 1000262304: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE:

`youtube-dl` used to work on `Hotstar.com` like a week ago, now I'm getting this:

````
ERROR: 1000262304: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)'))
````
I have tried few different videos from:

````
(1) Yeh Rishta Kya Kehlata Hai:
Series link:
https://www.hotstar.com/in/tv/yeh-rishta-kya-kehlata-hai/586#!

and 

(2) Saath Nibhaana Saathiya 2:
Series link:
https://www.hotstar.com/in/tv/saath-nibhaana-saathiya/693#!

Direct video (episode) link as an example:
https://www.hotstar.com/in/tv/yeh-rishta-kya-kehlata-hai/586/kartiks-promise-to-sirat/1000262304
````
but getting same error on every link I've tried. The same video does play just fine in browsers (Microsoft Edge for Linux and Chromium).

Thank you so much for youtube-dl.

OS: Ubuntu MATE 21.04
youtube-dl version: 2021.06.06

**Comment by TheJags** [comment]
@dstftw could you please point me to what this issue is duplicate of?

Thanks.

**Comment by Omi231** [comment]
@TheJags did you find any solution?
