### ISSUE TITLE
RAI Broken

### ISSUE THREAD

**Issue by PortPhil** [ytdl-org/youtube-dl#29278]
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
paul@paul-lm19:~$ youtube-dl --verbose http://www.tg1.rai.it/dl/tg1/2010/edizioni/ContentSet-c33de60a-a1bf-4300-ac15-b69858f98313-tg1.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.tg1.rai.it/dl/tg1/2010/edizioni/ContentSet-c33de60a-a1bf-4300-ac15-b69858f98313-tg1.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.17 (CPython) - Linux-5.4.0-73-generic-x86_64-with-LinuxMint-19-tara
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs 5, rtmpdump 2.4
[debug] Proxy map: {}
[Rai] c33de60a-a1bf-4300-ac15-b69858f98313: Downloading webpage
[Rai] 8da76491-af2d-4754-9795-30129ad96e42: Downloading video JSON
[Rai] 8da76491-af2d-4754-9795-30129ad96e42: Downloading XML metadata for platform mon
[Rai] 8da76491-af2d-4754-9795-30129ad96e42: Downloading XML metadata for platform flash
[Rai] 8da76491-af2d-4754-9795-30129ad96e42: Downloading XML metadata for platform native
[Rai] c33de60a-a1bf-4300-ac15-b69858f98313: Downloading video JSON
ERROR: Unable to extract relinker URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rai.py", line 451, in _real_extract
    return self._extract_from_content_id(content_item_id, url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rai.py", line 370, in _extract_from_content_id
    content_id, 'Downloading video JSON')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 899, in _download_json
    expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 877, in _download_json_handle
    expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 667, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 652, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rai.py", line 469, in _real_extract
    webpage, 'relinker URL', group='url'))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract relinker URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I know RAI geo block, but normally not news programmes. As of today I'm unable to download this programme

**Comment by mcagl** [comment]
Many raiplay videos seem to be DRM protected and thus youtube-dl cannot download them anymore.
And I'm in Italy, so this is not a geoblock problem.
