### ISSUE TITLE
"Could not find codec parameters" error

### ISSUE THREAD

**Issue by spacecraft1013** [ytdl-org/youtube-dl#29276]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.8 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-55702-g920046a, ffprobe N-55702-g920046a
[debug] Proxy map: {}
[youtube:tab] PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr: Downloading webpage
[download] Downloading playlist: Essence of calculus
[youtube:tab] playlist Essence of calculus: Downloading 12 videos
[download] Downloading video 1 of 12
[youtube] WUvTyaaNkzM: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r5---sn-p5qs7nsr.googlevideo.com/videoplayback?expire=1623521920&ei=IKbEYJKYHIeE_9EP4d2LqAs&ip=68.33.62.196&id=o-AEVIdtpQjAEeRVkOfYusclqDOme8iEqgtv82Be3G0BHL&itag=399&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=8g&mm=31%2C26&mn=sn-p5qs7nsr%2Csn-ab5sznld&ms=au%2Conr&mv=m&mvi=5&pl=17&initcwndbps=2121250&vprv=1&mime=video%2Fmp4&ns=a2kUj1vAUPjX9q0QKIHRETcF&gir=yes&clen=38104713&dur=1024.289&lmt=1588535879221869&mt=1623499718&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5531432&n=ujus0HRq9RsqOo5Z7tq&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAOOOCJe8hs3fzz_P3zyYAu74ehVpPAbvbfBhTU6M9e6XAiEA01gbE583b0-BwKbfQ78i3NuQ6BkCrZCEL6gtLi-QGss%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhALfn6W31jamOUgWJoFQdkJiTHghxTAI-tLdBHhUrjY5rAiA8ZZlsJebT9KTzZMTVTp2Qp6f3-3mElfzsDzVjrQp25A%3D%3D'
[download] Destination: The essence of calculus-WUvTyaaNkzM.f399.mp4
[download] 100% of 36.34MiB in 00:01
[debug] Invoking downloader on 'https://r5---sn-p5qs7nsr.googlevideo.com/videoplayback?expire=1623521920&ei=IKbEYJKYHIeE_9EP4d2LqAs&ip=68.33.62.196&id=o-AEVIdtpQjAEeRVkOfYusclqDOme8iEqgtv82Be3G0BHL&itag=140&source=youtube&requiressl=yes&mh=8g&mm=31%2C26&mn=sn-p5qs7nsr%2Csn-ab5sznld&ms=au%2Conr&mv=m&mvi=5&pl=17&initcwndbps=2121250&vprv=1&mime=audio%2Fmp4&ns=a2kUj1vAUPjX9q0QKIHRETcF&gir=yes&clen=16269850&dur=1024.348&lmt=1538116643685598&mt=1623499718&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5533332&n=ujus0HRq9RsqOo5Z7tq&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgJMyVn-AEn-q57JlQ2N2BuXvXpLYpmcXlffyfoRF-4pACIQCPGmb98LKEbQsS6XZN2ftMd2mT1Z02ucFqY0-mIg4vTg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhALfn6W31jamOUgWJoFQdkJiTHghxTAI-tLdBHhUrjY5rAiA8ZZlsJebT9KTzZMTVTp2Qp6f3-3mElfzsDzVjrQp25A%3D%3D'
[download] Destination: The essence of calculus-WUvTyaaNkzM.f140.m4a
[download] 100% of 15.52MiB in 00:00
[ffmpeg] Merging formats into "The essence of calculus-WUvTyaaNkzM.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:The essence of calculus-WUvTyaaNkzM.f399.mp4" -i "file:The essence of calculus-WUvTyaaNkzM.f140.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:The essence of calculus-WUvTyaaNkzM.temp.mp4"
ERROR: file:The essence of calculus-WUvTyaaNkzM.f399.mp4: could not find codec parameters
Traceback (most recent call last):
  File "c:\users\space\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 2115, in post_process
    files_to_delete, info = pp.run(info)
  File "c:\users\space\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 523, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "c:\users\space\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:The essence of calculus-WUvTyaaNkzM.f399.mp4: could not find codec parameters
```

## Description

I'm trying to download the "Essence of calculus" playlist from 3Blue1Brown, and I get this error. I have also tried to download the specific video that was causing the issue by just the link instead of the playlist, and I get the same error. I have both ffmpeg and youtube-dl installed through pip on windows 10. I also get this exact same error when downloading the "Essence of linear algebra", although the error shows up on video 14 of the playlist rather than video 1. I have tried reinstalling ffmpeg and youtube-dl.

**Comment by kikuyan** [comment]
Maybe your ffmpeg is just too old. Googled and found many 'ffmpeg version N-55702-g920046a Copyright (c) 2000-**2013**'.

**Comment by spacecraft1013** [comment]
I tried multiple versions of ffmpeg earlier (namely N-55702-g920046a and 4.0.2) and neither of those worked, so I somewhat ruled it out from my reasoning. After reading this comment, I tried out the latest build from gyan.dev, and that worked fine. It seems to just have been a ffmpeg issue then.
