### ISSUE TITLE
Add support for sketch.pixiv.net

### ISSUE THREAD

**Issue by git-test02** [ytdl-org/youtube-dl#29284]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://sketch.pixiv.net/@rune_q/lives/8393780287882279090

## Description

WRITE DESCRIPTION HERE
[debug] Command-line args: ['--cookies', '--force-generic-extractor', '-F', 'https://sketch.pixiv.net/@*/lives/*']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19043
[debug] exe versions: ffmpeg 2021-06-09-git-e01bf559df-full_build-www.gyan.dev, ffprobe 2021-06-09-git-e01bf559df-full_build-www.gyan.dev
[debug] Proxy map: {}
Traceback (most recent call last):
  File "./YoutubeDL.py", line 815, in wrapper
  File "./YoutubeDL.py", line 836, in __extract_info
  File "./extractor/common.py", line 534, in extract
  File "./extractor/generic.py", line 3520, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://sketch.pixiv.net/@*/lives/*

**Comment by SuperSonicHub1** [comment]
@git-test02 The URL redirects to an empty user page. Can you please give multiple functional URLs? Also, the test URL shown in the debug log seems to be broken, as it contains multiple asterisks. Is that intentional?

**Comment by apratsunrthd** [comment]
@git-test02 , checking in again. Are you still in need of this functionality? If so, please provide multiple functional URLs that have video content.
