### ISSUE TITLE
[aenetworks] "The signature is invalid."

### ISSUE THREAD

**Issue by 2011** [ytdl-org/youtube-dl#29300]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v -F 'https://play.mylifetime.com/shows/the-rap-game/season-1/episode-1'              
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--restrict-filenames', '-o', '%(title)s-%(id)s-%(uploader)s.%(ext)s', '-w', '-v', '-F', 'https://play.mylifetime.com/shows/the-rap-game/season-1/episode-1']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.5 (CPython) - Linux-5.10.27...
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[aenetworks] /shows/the-rap-game/season-1/episode-1: Downloading JSON metadata
[aenetworks] /shows/the-rap-game/season-1/episode-1: Downloading JSON metadata
[aenetworks] 593877571572: Downloading JSON metadata
[aenetworks] 593877571572: Downloading hls_high_ak SMIL data
[aenetworks] 593877571572: Downloading high_video_s3 SMIL data
[aenetworks] 593877571572: Downloading hls_high_fastly SMIL data
ERROR: The signature is invalid.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/aenetworks.py", line 174, in _real_extract
    return self._extract_aetn_info(domain, 'canonical', '/' + canonical, url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/aenetworks.py", line 93, in _extract_aetn_info
    info.update(self._extract_aen_smil(media_url, video_id, auth))
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/aenetworks.py", line 66, in _extract_aen_smil
    raise last_e
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/aenetworks.py", line 56, in _extract_aen_smil
    tp_formats, tp_subtitles = self._extract_theplatform_smil(
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/theplatform.py", line 51, in _extract_theplatform_smil
    raise ExtractorError(
youtube_dl.utils.ExtractorError: The signature is invalid.
```

## Description

I literally "saw" this break. Worked fine up until a few hours ago, and then, all of a sudden, every download attempt produces this message (even ones that had worked right before whatever change they made).

**Comment by rautamiekka** [comment]
I confirm it ain't working (I used PowerShell 7.1.3 on Win10):
```
PowerShell 7.1.3
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

Loading personal and system profiles took 1244ms.
(base) PS C:\Windows\System32> youtube-dl --ignore-config --verbose --verbose --ignore-errors --no-mark-watched --format "bestvideo+bestaudio/best" --audio-format best --audio-quality 0 --ffmpeg-location "C:/Users/Public/Downloads/ffmpeg/bin" --no-playlist --output "I:/SEAGATE_2TB_0/_DOWNLOADS_/_websites_/com/youtube/%(uploader_id)s/%(title)s %(resolution)s #%(id)s#.%(ext)s" --console-title --no-mtime --retries infinite --continue --no-overwrites --fragment-retries infinite -v -F 'https://play.mylifetime.com/shows/the-rap-game/season-1/episode-1'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '--verbose', '--verbose', '--ignore-errors', '--no-mark-watched', '--format', 'bestvideo+bestaudio/best', '--audio-format', 'best', '--audio-quality', '0', '--ffmpeg-location', 'C:/Users/Public/Downloads/ffmpeg/bin', '--no-playlist', '--output', 'I:/SEAGATE_2TB_0/_DOWNLOADS_/_websites_/com/youtube/%(uploader_id)s/%(title)s %(resolution)s #%(id)s#.%(ext)s', '--console-title', '--no-mtime', '--retries', 'infinite', '--continue', '--no-overwrites', '--fragment-retries', 'infinite', '-v', '-F', 'https://play.mylifetime.com/shows/the-rap-game/season-1/episode-1']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.10 (CPython) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2021-04-14-git-c5ca18fd1b-full_build-www.gyan.dev, ffprobe 2021-04-14-git-c5ca18fd1b-full_build-www.gyan.dev
[debug] Proxy map: {}
[aenetworks] /shows/the-rap-game/season-1/episode-1: Downloading JSON metadata
[aenetworks] 593877571572: Downloading JSON metadata
[aenetworks] 593877571572: Downloading hls_high_ak SMIL data
[aenetworks] 593877571572: Downloading high_video_s3 SMIL data
[aenetworks] 593877571572: Downloading hls_high_fastly SMIL data
ERROR: The signature is invalid.
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\extractor\aenetworks.py", line 174, in _real_extract
    return self._extract_aetn_info(domain, 'canonical', '/' + canonical, url)
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\extractor\aenetworks.py", line 93, in _extract_aetn_info
    info.update(self._extract_aen_smil(media_url, video_id, auth))
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\extractor\aenetworks.py", line 66, in _extract_aen_smil
    raise last_e
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\extractor\aenetworks.py", line 56, in _extract_aen_smil
    tp_formats, tp_subtitles = self._extract_theplatform_smil(
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\extractor\theplatform.py", line 51, in _extract_theplatform_smil
    raise ExtractorError(
youtube_dl.utils.ExtractorError: The signature is invalid.

(base) PS C:\Windows\System32>
```

**Comment by Mr-Jake** [comment]
Not every [aenetworks] is broken. Lifetime gives the "The signature is invalid." error, but the A&E and History sites still work.

**Comment by 2011** [comment]
> Not every [aenetworks] is broken. Lifetime gives the "The signature is invalid." error, but the A&E and History sites still work.

Unsurprisingly, History no longer works (with the same error message).

**Comment by m0n0th3ist** [comment]
I'm getting the same error, running Ubuntu's standard version 2021.04.07.

**Comment by ericblau** [comment]
Looks like they changed at least the secret and key (_THEPLATFORM_KEY and _THEPLATFORM_SECRET) that they use to construct the hmac signature.  Looks like the new secret should be 'S10BPXHMlb' (533130425058484d6c62), at least for History channel--haven't looked at any others.  My attempt to use hashcat to figure out the key failed--I'm not at all sure I wasn't doing something wrong.

**Comment by dwaderich** [comment]
same issue with some history videos:

C:\>youtube-dl.exe --verbose https://play.history.com/shows/the-machines-that-built-america/season-1/episode-1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://play.history.com/shows/the-machines-that-built-america/season-1/episode-1']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-89409-g4678339e74, ffprobe N-89409-g4678339e74
[debug] Proxy map: {}
[aenetworks] /shows/the-machines-that-built-america/season-1/episode-1: Downloading JSON metadata
[aenetworks] 1922850371860: Downloading JSON metadata
[aenetworks] 1922850371860: Downloading hls_high_ak SMIL data
[aenetworks] 1922850371860: Downloading high_video_s3 SMIL data
[aenetworks] 1922850371860: Downloading hls_high_fastly SMIL data
ERROR: The signature is invalid.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\aenetworks.py", line 174, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\aenetworks.py", line 93, in _extract_aetn_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\aenetworks.py", line 66, in _extract_aen_smil
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\aenetworks.py", line 57, in _extract_aen_smil
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\theplatform.py", line 52, in _extract_theplatform_smil
youtube_dl.utils.ExtractorError: The signature is invalid.

**Comment by wesnm** [comment]
@ericblau Where did you extract that secret from?

**Comment by wesnm** [comment]
Update. The new parameters are (thank you chrome):
    _THEPLATFORM_KEY = 'S10BPXHMlb'
    _THEPLATFORM_SECRET = '43jXaGRQud'

But I'm still getting a signature error, so it must be more that just those having changed.

**Comment by goatmale** [comment]
> Update. The new parameters are (thank you chrome): _THEPLATFORM_KEY = '43jXaGRQud' _THEPLATFORM_SECRET = 'S10BPXHMlb'
> 
> Can download from history.com now.

Thanks man - editing "C:\Users\{USERNAME}\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\youtube_dl\extractor\aenetworks.py" manually with the keys you referenced worked right away in Windows 10!

**Comment by eflister** [comment]
just hit this with https://play.history.com/shows/alone/season-1/episode-5, the key/secret worked, thanks!  any way to get this merged?
