### ISSUE TITLE
Hotstar broken since 2021.06.06

### ISSUE THREAD

**Issue by wtluke** [ytdl-org/youtube-dl#29302]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
ubuntu@ip-172-31-13-67:~$ youtube-dl -o test.mp4 https://www.hotstar.com/can-you-not-spread-rumours/1000076273 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'test.mp4', 'https://www.hotstar.com/can-you-not-spread-rumours/1000076273', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.6.9 (CPython) - Linux-5.4.0-1049-aws-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[hotstar] 1000076273: Downloading webpage
[hotstar] 1000076273: Downloading JSON metadata
ERROR: 1000076273: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 906, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 906, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/youtube_dl/extractor/hotstar.py", line 146, in _real_extract
    'type': 'device_id',
  File "/home/ubuntu/.local/lib/python3.6/site-packages/youtube_dl/extractor/hotstar.py", line 63, in _call_api_v2
    message = self._parse_json(e.cause.read().decode(), video_id)['message']
  File "/home/ubuntu/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 910, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: 1000076273: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Hotstar is no longer working. I've tried with multiple URLs, including the test URL in the code (https://www.hotstar.com/can-you-not-spread-rumours/1000076273)

Must be a change to the API that's caused it but I can't see what or why. Grateful for any help in fixing,

Thanks

**Comment by ProTrooper** [comment]
You might need a Hotstar Subscription Logged in probably and then denying access or maybe it is just a problem

**Comment by dy** [comment]
Same thing in latest version 2021.12.17

**Comment by dirkf** [comment]
Same problem as #27614.
