### ISSUE TITLE
NickDeIE is dead

### ISSUE THREAD

**Issue by J0hsHH** [ytdl-org/youtube-dl#29319]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [none of them] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
➜  ~ youtube-dl -v "https://www.nickelodeon.no/episodes/2z17bh/familien-thunderman-eventyrlige-barnevakter-sesong-1-episode-1"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.nickelodeon.no/episodes/2z17bh/familien-thunderman-eventyrlige-barnevakter-sesong-1-episode-1']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.5 (CPython) - macOS-10.15.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[nick.de] familien-thunderman-eventyrlige-barnevakter-sesong-1-episode-1: Downloading webpage
ERROR: Unable to extract mrss url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/site-packages/youtube_dl/extractor/nick.py", line 191, in _real_extract
    mrss_url = self._extract_mrss_url(webpage, host)
  File "/usr/local/lib/python3.9/site-packages/youtube_dl/extractor/nick.py", line 180, in _extract_mrss_url
    return update_url_query(self._search_regex(
  File "/usr/local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract mrss url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by matkoniecz** [comment]
So entire website is down, right?

In such case youtube-dl is unable to magically download videos from nonexisting site.

**Comment by J0hsHH** [comment]
> So entire website is down, right?
> 
> In such case youtube-dl is unable to magically download videos from nonexisting site.

think its the regex

**Comment by matkoniecz** [comment]
Have you did this step:

> I've checked that all provided URLs are alive and playable in a browser

?

**Comment by J0hsHH** [comment]
> Have you did this step:
> 
> > I've checked that all provided URLs are alive and playable in a browser
> 
> 

old url: http://www.nickelodeon.no/program/2626-bulderhuset/videoer/90947-femteklasse-veronica-vs-vanzilla

new urls {
video:https://www.nickelodeon.no/episodes/vtn167/bulderhuset-morgenoppgaven-feriedebatten-sesong-1-episode-8
playlist:https://www.nickelodeon.no/shows/1rak95/the-loud-house
}

**Comment by J0hsHH** [comment]
https://github.com/blackjack4494/youtube-dlc/commit/51707d9a7a4b7808d350bfa6565f8668e4a30dd9
it works in youtube-dlc
