### ISSUE TITLE
Nuvid failing - RegExNotFound error

### ISSUE THREAD

**Issue by gtTracy** [ytdl-org/youtube-dl#29321]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
tracy@tracy-HP17:/media/tracy/Testing/DL$ youtube-dl --config-location ~/.config/youtube-dl/config.sex -v https://www.nuvid.com/video/2070161/teen-girl-with-a-fetish-for-balloons
[debug] System config: []
[debug] User config: []
[debug] Custom config: [u'-o', u'/media/tracy/Testing/DL/sex/%(title)s.%(ext)s', u'--netrc', u'--sleep-interval', u'0', u'--max-sleep-interval', u'5', u'--no-overwrites', u'--download-archive', u'~/.config/youtube-dl/archive-list', u'--yes-playlist', u'--mark-watched', u'--ignore-errors']
[debug] Command-line args: [u'--config-location', u'/home/tracy/.config/youtube-dl/config.sex', u'-v', u'https://www.nuvid.com/video/2070161/teen-girl-with-a-fetish-for-balloons']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18 (CPython) - Linux-5.8.0-55-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[Nuvid] 2070161: Downloading video page
[Nuvid] 2070161: Downloading video page for MP4 format
ERROR: Unable to extract 2070161; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/nuvid.py", line 39, in _real_extract
    video_url = self._html_search_regex(html5_video_re, webpage, video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract 2070161; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

The Nuvid extractor seems to be failing - apparently something has changed on the site, as the error coming back is RegExNotFound. I tested against 52 URLs for the site, an example is:

https://www.nuvid.com/video/2070161/teen-girl-with-a-fetish-for-balloons

I have verified that these URLs (including the sample listed above) work correctly in Chrome Version 91.0.4472.101 (Official Build) (64-bit), running on Ubuntu 20.04

Other open bug reports on this issue exist, specifically:

https://github.com/ytdl-org/youtube-dl/issues/27578
https://github.com/ytdl-org/youtube-dl/issues/15355

**Comment by dirkf** [comment]
As with many other sites, the desired content no longer appears from the supposed URL. Instead, it's populated with asynchronous JavaScript after the page has loaded. When the extractor searches for the `<video>` element, it isn't present.

By observing what is loaded by the browser one can see that the video details are in JSON retrieved from `https://www.nuvid.com/player_config_json/?vid=`video_id.

See PR #29332
