### ISSUE TITLE
Crackle not working

### ISSUE THREAD

**Issue by Mitshah0506** [ytdl-org/youtube-dl#29335]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2021.06.06**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
Youtube-dl -f best --all-subs --embed-subs --embed-thumbnail -a "C:\Users\misch\Downloads\youtube-dl\Shows\Startup\Startup Episode List\startup_season_1.txt" -o "/Show/%(series)s/%(season_number)s %(season)s/Episode %(episode_number)s [%(episode)s].%(ext)s" --download-archive C:\Users\misch\Downloads\youtube-dl\Show\Archive\archive_startup.txt --verbose

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', '--embed-subs', '--embed-thumbnail', '-a', 'C:\\Users\\misch\\Downloads\\youtube-dl\\Shows\\Startup\\Startup Episode List\\startup_season_1.txt', '-o', '/Show/%(series)s/%(season_number)s %(season)s/Episode %(episode_number)s [%(episode)s].%(ext)s', '--download-archive', 'C:\\Users\\misch\\Downloads\\youtube-dl\\Show\\Archive\\archive_startup.txt', '--verbose']
[debug] Batch file urls: ['https://www.crackle.com/watch/2992/2499348', 'https://www.crackle.com/watch/2992/2499382', 'https://www.crackle.com/watch/2992/2499440', 'https://www.crackle.com/watch/2992/2499448', 'https://www.crackle.com/watch/2992/2499522', 'https://www.crackle.com/watch/2992/2499520', 'https://www.crackle.com/watch/2992/2499539', 'https://www.crackle.com/watch/2992/2499547', 'https://www.crackle.com/watch/2992/2499546', 'https://www.crackle.com/watch/2992/2499553']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
[Crackle] 2499348: Downloading media JSON as US
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\crackle.py", line 133, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I recently found this show I liked on crackle.com and decided to try and download it because it was listed on sites that worked with youtube-dl. When I try to use youtube-dl it keeps saying there are no video formats. You don't need any login credentials to view the show.
[startup_season_1.txt](https://github.com/ytdl-org/youtube-dl/files/6679503/startup_season_1.txt)

**Comment by kikuyan** [comment]
DRM protected.

**Comment by dirkf** [comment]
That is, all the media URLs returned were protected by DRM that yt-dl doesn't handle, but the extractor doesn't say so.

The condition could be detected and raised as `ExtractorError('No non-DRM video formats found', expected=True)`.

If doing so, the check for DRM needs to be fixed:
```
                if e.get('UseDRM') is True:
```
Should be:
```
                if e.get('UseDRM') == 'True':
```
Also, the extractor logic loops over countries until it sees no geo-restriction and a media list, but not if none of the URLs in the media list are non-DRM.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/25791
