### ISSUE TITLE
[cnbc] extractor does not work on article pages

### ISSUE THREAD

**Issue by 2011** [ytdl-org/youtube-dl#29342]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v -f best 'https://www.cnbc.com/2021/06/12/bitcoin-taproot-upgrade-what-it-means.html'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--restrict-filenames', '-o', '%(title)s-%(id)s-%(uploader)s.%(ext)s', '-w', '-v', '-f', 'best', 'https://www.cnbc.com/2021/06/12/bitcoin-taproot-upgrade-what-it-means.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.5 (CPython) - Linux-5.10.27...
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[generic] bitcoin-taproot-upgrade-what-it-means: Requesting header
WARNING: Could not send HEAD request to https://www.cnbc.com/2021/06/12/bitcoin-taproot-upgrade-what-it-means.html: HTTP Error 503: Service Unavailable
[generic] bitcoin-taproot-upgrade-what-it-means: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] bitcoin-taproot-upgrade-what-it-means: Extracting information
ERROR: Unsupported URL: https://www.cnbc.com/2021/06/12/bitcoin-taproot-upgrade-what-it-means.html
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/generic.py", line 3520, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.cnbc.com/2021/06/12/bitcoin-taproot-upgrade-what-it-means.html
```

## Description

Even falling back to the generic extractor, I believe that youtube-dl should download the video in the page. The page source contains a .m3u8 URL, which youtube-dl handles without any problem when supplied directly as the argument.

**Comment by 2011** [comment]
Duplicate of (very old) #9011
