### ISSUE TITLE
ERROR: No video formats found | ParamountPlus video playable in browser

### ISSUE THREAD

**Issue by 42-North** [ytdl-org/youtube-dl#29351]
C:\Users\user\Downloads>youtube-dl --verbose https://www.paramountplus.com/shows/rupauls-drag-race/video/XeLhvObaelBXGoTnchPDWHH2_W76Jwgc/rupaul-s-drag-race-drama-queens/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.paramountplus.com/shows/rupauls-drag-race/video/XeLhvObaelBXGoTnchPDWHH2_W76Jwgc/rupaul-s-drag-race-drama-queens/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-04-20-git-718e03e5f2-full_build-www.gyan.dev, ffprobe 2021-04-20-git-718e03e5f2-full_build-www.gyan.dev
[debug] Proxy map: {}
[CBS] XeLhvObaelBXGoTnchPDWHH2_W76Jwgc: Downloading XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\cbs.py", line 115, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\cbs.py", line 97, in _extract_video_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Users\user\Downloads>

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30491

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/pull/30085

**Comment by 89z** [comment]
DRM
