### ISSUE TITLE
Pornhub extractor broke recently

### ISSUE THREAD

**Issue by kwagner137** [ytdl-org/youtube-dl#29375]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-i', '-f', 'bestvideo[height<=1080]+bestaudio/best[height<=1080]', '-o', '~/Documents/stuff/%(uploader)s/%(title)s.%(ext)s', '-u', 'PRIVATE', '-p', 'PRIVATE', '--external-downloader', 'aria2c', '--external-downloader-args', '-c -j 3 -x 3 -s 3 -k 1M --file-allocation=none', 'https://www.pornhub.com/model/SisyCat', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.0 (CPython) - macOS-10.13.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[PornHubPagedVideoList] Downloading pornhub login page
[PornHubPagedVideoList] Logging in to pornhub
[download] Downloading playlist: model/SisyCat/videos
[PornHubPagedVideoList] model/SisyCat/videos: Downloading page 1
[PornHubPagedVideoList] playlist model/SisyCat/videos: Downloading 24 videos
[download] Downloading video 1 of 24
[PornHub] Downloading pornhub login page
[PornHub] ph5f93f6160e68c: Downloading pc webpage
[PornHub] ph5f93f6160e68c: Downloading tv webpage
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhub.py", line 385, in _real_extract
    js_vars = extract_js_vars(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhub.py", line 322, in extract_js_vars
    assignments = self._search_regex(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

pornhub extractor was working fine a week ago. Updated ytdl and tried again, still the same extraction error.

**Comment by kwagner137** [comment]
Hmm any thoughts?
