### ISSUE TITLE
YouTube "refetching age-gated info webpage" Error 404

### ISSUE THREAD

**Issue by zefie** [ytdl-org/youtube-dl#29372]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'Ka4FTcPV_Co']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-17-amd64-x86_64-with-debian-10.10
[debug] exe versions: ffmpeg 4.1.6, ffprobe 4.1.6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Ka4FTcPV_Co: Downloading webpage
[youtube] Ka4FTcPV_Co: Refetching age-gated info webpage
WARNING: unable to download video info webpage: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/media/yt/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/media/yt/bin/youtube-dl/youtube_dl/__init__.py", line 475, in main
  File "/media/yt/bin/youtube-dl/youtube_dl/__init__.py", line 465, in _real_main
  File "/media/yt/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2069, in download
  File "/media/yt/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
  File "/media/yt/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
  File "/media/yt/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
  File "/media/yt/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
  File "/media/yt/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1503, in _real_extract
  File "/media/yt/bin/youtube-dl/youtube_dl/compat.py", line 2644, in compat_parse_qs
  File "/media/yt/bin/youtube-dl/youtube_dl/compat.py", line 2614, in _parse_qsl
AttributeError: 'bool' object has no attribute 'split'

```

## Description

It appears YouTube has changed how age-gating works (again), and as such causes youtube-dl to throw a 404 error on any age gated videos. Some examples:

https://youtu.be/8n1OJoHpDSc
https://youtu.be/9Ej9QOOGkWQ
https://youtu.be/cJQjeBWvm-0
https://youtu.be/Dkldmp016xk
https://youtu.be/Ka4FTcPV_Co

**Comment by wmorgansoftware** [comment]
I can also confirm this, attempting youtube-dl https://www.youtube.com/watch?v=C5ngJ1eYcpk .

**Comment by wschmrdr** [comment]
Attempted youtube-dl https://www.youtube.com/watch?v=C5ngJ1eYcpk and received the same.
