### ISSUE TITLE
Ytdl still saying that i need to update when i already updated

### ISSUE THREAD

**Issue by joabutti** [ytdl-org/youtube-dl#29405]
Ytdl keeps saying that i need to update even when i have updated.

WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".
MinigetError: play(hall of fame) encountered:
Status code: 404
    at ClientRequest.<anonymous> (C:\Users\leejo\Desktop\Discordbots\Musically\node_modules\miniget\dist\index.js:210:27)
    at Object.onceWrapper (events.js:483:26)
    at ClientRequest.emit (events.js:376:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10) {
  statusCode: 404
}

**Comment by joabutti** [comment]
Pls help

**Comment by kikuyan** [comment]
Wrong place. Ask anywhere else.

**Comment by joabutti** [comment]
then where
