### ISSUE TITLE
Downloading from RaiPlay.it doesn't work anymore

### ISSUE THREAD

**Issue by NoxWW** [ytdl-org/youtube-dl#29413]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\david>youtube-dl -v https://www.raiplay.it/video/2021/06/Euro-2020-Campionati-Europei-di-calcio-Notti-Europee-del-26-06-2021-04a92871-8436-41b1-9e8e-d358209a5ef7.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.raiplay.it/video/2021/06/Euro-2020-Campionati-Europei-di-calcio-Notti-Europee-del-26-06-2021-04a92871-8436-41b1-9e8e-d358209a5ef7.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-05-02-git-5541cffa17-full_build-www.gyan.dev, ffprobe 2021-05-02-git-5541cffa17-full_build-www.gyan.dev
[debug] Proxy map: {}
[RaiPlay] 04a92871-8436-41b1-9e8e-d358209a5ef7: Downloading video JSON
[RaiPlay] 04a92871-8436-41b1-9e8e-d358209a5ef7: Downloading XML metadata for platform mon
[RaiPlay] 04a92871-8436-41b1-9e8e-d358209a5ef7: Downloading m3u8 information
[RaiPlay] 04a92871-8436-41b1-9e8e-d358209a5ef7: Downloading XML metadata for platform flash
[RaiPlay] 04a92871-8436-41b1-9e8e-d358209a5ef7: Downloading f4m manifest
[RaiPlay] 04a92871-8436-41b1-9e8e-d358209a5ef7: Downloading XML metadata for platform native
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://b70cb04c54ab478189e9d8ee45637b13.msvdn.net/ostr2/podcastcdn/verimatrix_root/DRMEuro2021/14813126_,1800,2401/manifest_mvnumber.mpd?hdnea=st=1624794130~exp=1624794280~acl=/*~hmac=37aff979524c9c19b9b59c519faa69e6a97edb3a5c74b7bab6fa1a0a140dfea6'
[download] Notti Europee-04a92871-8436-41b1-9e8e-d358209a5ef7.mpd has already been downloaded
[download] 100% of 7.34KiB
```

## Description

There are problems downloading from RaiPlay.it, youtube-dl downloads only a .mpd file without audio and video.

https://www.raiplay.it/video/2021/06/Euro-2020-Campionati-Europei-di-calcio-Notti-Europee-del-26-06-2021-04a92871-8436-41b1-9e8e-d358209a5ef7.html

This is the show I tried to download, it can be watched for free on the site

**Comment by R8s6** [comment]
I confirm that i'm also experiencing this as of 2021-07-05.

Note: to test the videos on raiplay.it website, one must either have an Italian IP or use a VPN server located in Italy.

**Comment by kikuyan** [comment]
PR #18742 seems to address the problem. Still not merged, unfortunately.

**Comment by gorghino** [comment]
I tried PR #18742 with latest version (2021.12.17) with "https://www.raiplay.it/video/2021/12/una-tigre-all-ora-del-te-20d0cf50-8638-4bc0-a54d-75faa3178459.html" but it doesn't download the video due to false georestriction:

```
gorgo@pop-os:~/youtube-dl$ python -m youtube_dl --verbose "https://www.raiplay.it/video/2021/12/una-tigre-all-ora-del-te-20d0cf50-8638-4bc0-a54d-75faa3178459.html"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.raiplay.it/video/2021/12/una-tigre-all-ora-del-te-20d0cf50-8638-4bc0-a54d-75faa3178459.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 5014bd67c
[debug] Python version 3.9.7 (CPython) - Linux-5.15.8-76051508-generic-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[RaiPlay] 20d0cf50-8638-4bc0-a54d-75faa3178459: Downloading video JSON
[RaiPlay] 20d0cf50-8638-4bc0-a54d-75faa3178459: Downloading XML metadata for platform mon
[RaiPlay] 20d0cf50-8638-4bc0-a54d-75faa3178459: Downloading MPD manifest
[RaiPlay] 20d0cf50-8638-4bc0-a54d-75faa3178459: Downloading XML metadata for platform flash
[RaiPlay] 20d0cf50-8638-4bc0-a54d-75faa3178459: Downloading XML metadata for platform native
ERROR: This video is not available from your location due to geo restriction
This video is available in Italy.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "/home/gorgo/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gorgo/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/gorgo/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/gorgo/youtube-dl/youtube_dl/extractor/rai.py", line 176, in _real_extract
    relinker_info = self._extract_relinker_info(video['content_url'], video_id)
  File "/home/gorgo/youtube-dl/youtube_dl/extractor/rai.py", line 100, in _extract_relinker_info
    self.raise_geo_restricted(countries=self._GEO_COUNTRIES)
  File "/home/gorgo/youtube-dl/youtube_dl/extractor/common.py", line 947, in raise_geo_restricted
    raise GeoRestrictedError(msg, countries=countries)
youtube_dl.utils.GeoRestrictedError: This video is not available from your location due to geo restriction
```


My IP is actually italian.

**Comment by kikuyan** [comment]
> it doesn't download the video due to false georestriction:
> My IP is actually italian.

Similar to mediaset.it case: #29998, #29218, PR #30450.
New PR for raiplay.it is needed, probably.
