### ISSUE TITLE
No Formats Found for a Periscope Video

### ISSUE THREAD

**Issue by balupton** [ytdl-org/youtube-dl#29419]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
> youtube-dl \
      --all-formats \
      --all-subs \
      --geo-bypass \
      --write-all-thumbnails \
      --write-annotations \
      --write-auto-sub \
      --write-description \
      --write-info-json \
      --write-sub \
      --verbose \
      'https://www.periscope.tv/balupton/1dRJZmOWmYVGB'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--all-formats', '--all-subs', '--geo-bypass', '--write-all-thumbnails', '--write-annotations', '--write-auto-sub', '--write-description', '--write-info-json', '--write-sub', '--verbose', 'https://www.periscope.tv/balupton/1dRJZmOWmYVGB']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.5 (CPython) - macOS-11.4-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, rtmpdump 2.4
[debug] Proxy map: {}
[periscope] 1dRJZmOWmYVGB: Downloading JSON metadata
[periscope] 1dRJZmOWmYVGB: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/periscope.py", line 135, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I'm making a backup of all my content online, and archiving my Periscope videos failed on this one video, which is playable via the web browser: https://www.periscope.tv/balupton/1dRJZmOWmYVGB

**Comment by kikuyan** [comment]
Adding `--referer https://www.periscope.tv/` seems to work.
I'm not sure if this is extractor problem or specific to that url.

**Comment by balupton** [comment]
Thanks, can confirm it works. I've updated my scripts to auto attach the referrer property:

- https://github.com/balupton/dotfiles/commit/b58b5f6e2308d2d62e4232f019d278a138131208
- https://github.com/bevry/dorothy/commit/96d9793d60d3ecc5d8288909cab04adb4a99ad69
