### ISSUE TITLE
Downloading video from NY Times fails

### ISSUE THREAD

**Issue by luvvie** [ytdl-org/youtube-dl#29447]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl --version
2021.06.06

$ youtube-dl -U
youtube-dl is up-to-date (2021.06.06)

$ youtube-dl --verbose https://www.nytimes.com/2021/06/30/us/jan-6-capitol-attack-takeaways.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.nytimes.com/2021/06/30/us/jan-6-capitol-attack-takeaways.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4-tessus, ffprobe 4.4-tessus
[debug] Proxy map: {}
[NYTimesArticle] jan-6-capitol-attack-takeaways: Downloading webpage
ERROR: Unable to extract podcast data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/nytimes.py", line 222, in _real_extract
    webpage, 'podcast data')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract podcast data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call

```

## Description

Attempted to download the single prominent video from the following URL:

    https://www.nytimes.com/2021/06/30/us/jan-6-capitol-attack-takeaways.html

I did find several closed NY Times related issues, but the most recent was closed. I apologize if I missed something more current.

**Comment by dirkf** [comment]
The NYT extractor knows about videos identified by `data-videoid`, and  Podcasts, but there aren't any on this page. Possibly the site technology has changed, as the linked page has a familiar structure: the page is partially rendered on the server and sent with a JavaScript constant that represents the page content (JS `window.__preloadedData`) and further rendered for display by client-side scripts. The extraction target of the existing `NYTimesArticleIE` extractor may not exist in the downloaded webpage until the scripts have run, or may no longer exist in the same form.

In the linked page, if the page state has been converted from JSON into the variable `preloaded_state`, the desired video can be found as follows:
* set the variable `display_id` to the path fragment of the URL ('/2021/06/30/us/jan-6-capitol-attack-takeaways.html') or possibly `preloaded_state['initialLocation']['pathname']` (same value);
* construct the `attribute_name` `'workOrLocation({"id":"%s"})' % display_id`;
* set the `article_id` to `preloaded_state['initialState']['ROOT_QUERY'][attribute_name]`
* find `preloaded_state['initialState'][article_id]['promotionalMedia']` with these properties
```
{ 'type': 'id',
  'typename': 'Video'
}
```
and its 'id' property is the `video_id` ('Video:VmlkZW86bnl0Oi8vdmlkZW8vZjViYThkYmItNTFkMC01ZDE1LWE1MjAtYWVkM2YwNDEwMjFl');
* find `preloaded_state['initialState'][video_id]` and extract metadata for the video;
* for each `rendition` in `preloaded_state['initialState'][video_id]['renditions']`, extract the format specified in `preloaded_state['initialState'][rendition['id']]` (url, width, height, type as format_id).
