### ISSUE TITLE
Cannot extract from RTP play [maybe similar to #26657]

### ISSUE THREAD

**Issue by KataKlimax** [ytdl-org/youtube-dl#29458]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.rtp.pt/play/p5355/as-horas-extraordinarias
- Single video: https://www.rtp.pt/play/p8291/e555562/o-ultimo-apaga-a-luz

## Verbose log

```
C:\Program Files\youtube-dl>youtube-dl -v https://www.rtp.pt/play/p8291/e555562/o-ultimo-apaga-a-luz
[debug] System config: []
[debug] User config: ['-f', 'mp4', '-o', 'C:/Users/ricar/Videos/%(title)s.%(ext)s', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.rtp.pt/play/p8291/e555562/o-ultimo-apaga-a-luz']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-06-30-git-de8e6e67e7-full_build-www.gyan.dev, ffprobe 2021-06-30-git-de8e6e67e7-full_build-www.gyan.dev
[debug] Proxy map: {}
[RTP] e555562: Downloading webpage
ERROR: e555562: Failed to parse JSON  (caused by ValueError("Expecting ',' delimiter: line 2 column 36 (char 37)",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 906, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 359, in raw_decode
ValueError: Expecting ',' delimiter: line 2 column 36 (char 37)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 906, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 359, in raw_decode
ValueError: Expecting ',' delimiter: line 2 column 36 (char 37)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\rtp.py", line 37, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 910, in _parse_json
youtube_dl.utils.ExtractorError: e555562: Failed to parse JSON  (caused by ValueError("Expecting ',' delimiter: line 2 column 36 (char 37)",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Cannot download and merge any videos from RTP play website at https://www.rtp.pt/player. RTP is the Portuguese public television broadcaster, and videos of most programmes are freely available at their website. When trying to use youtube-dl to pull any videos from this site the "failed to parse JSON" error occurs. Tried with many different freely available programmes, always the same error.

**Comment by dirkf** [comment]
Let's look at the first video (the second looks similar).

At l.1130ff., we see this (details depend on when the page was retrieved):
```
    <script>

      var x1 = decodeURIComponent(["https://cdn-ondemand.rtp.pt/nas2.share/h264/512x384/p5449/preview/p5449_1_201901231263_videoprv.mp4"].join(""));

      if ($("#player_prog").length > 0) {
      /*  var player1 = new RTPPlayer({
            file: {hls : atob( decodeURIComponent(["aHR0cHM","6Ly9zdH","JlYW1pb","mctb25k","ZW1hbmQ","ucnRwLn","B0L25hc","zIuc2hh","cmUvaDI","2NC81MT","J4Mzg0L","3AxNTI1","L3AxNTI","1XzFfMj","AyMTA0M","jA1OTk2","L21hc3R","lcnMubT","N1OA%3D","%3D"].join(""))), dash : atob( decodeURIComponent(["aHR0cHM6Ly","9zdHJlYW1p","bmctb25kZW","1hbmQucnRw","LnB0L25hcz","Iuc2hhcmUv","aDI2NC81MT","J4Mzg0L3Ax","NTI1L3AxNT","I1XzFfMjAy","MTA0MjA1OT","k2L21hc3Rl","cnMubXBk"].join(""))) },
                                      seekBarThumbnailsLoc: '//cdn-images.rtp.pt/multimedia/screenshots/p1525/preview/p1525_1_202104205996_preview.vtt',      }); */
        var f = {hls : atob( decodeURIComponent(["aHR0cH","M6Ly9z","dHJlYW","1pbmct","dm9kLn","J0cC5w","dC9kcm","0tZnBz","L25hcz","Iuc2hh","cmUvaD","I2NC81","MTJ4Mz","g0L3Ax","NTI1L3","AxNTI1","XzFfMj","AyMTA1","MTA2MT","E4Lm1w","NC9tYX","N0ZXIu","bTN1OA","%3D%3D"].join(""))), dash : atob( decodeURIComponent(["aHR0cH","M6Ly9z","dHJlYW","1pbmct","dm9kLn","J0cC5w","dC9kcm","0tZGFz","aC9uYX","MyLnNo","YXJlL2","gyNjQv","NTEyeD","M4NC9w","MTUyNS","9wMTUy","NV8xXz","IwMjEw","NTEwNj","ExOC5t","cDQvbW","FuaWZl","c3QubX","Bk"].join(""))) };

        var f = {hls : atob( decodeURIComponent(["aHR0cHM6L","y9zdHJlYW","1pbmctdm9","kLnJ0cC5w","dC9obHMvb","mFzMi5zaG","FyZS9oMjY","0LzUxMngz","ODQvcDUzN","TUvcDUzNT","VfMV8yMDE","5MTIzMTIw","MDkyNDY3N","TMubXA0L2","1hc3Rlci5","tM3U4"].join(""))), dash : atob( decodeURIComponent(["aHR0cHM6Ly","9zdHJlYW1p","bmctdm9kLn","J0cC5wdC9k","YXNoL25hcz","Iuc2hhcmUv","aDI2NC81MT","J4Mzg0L3A1","MzU1L3A1Mz","U1XzFfMjAx","OTEyMzEyMD","A5MjQ2NzUz","Lm1wNC9tYW","5pZmVzdC5t","cGQ%3D"].join(""))) };
        var player1 = new RTPPlayer({
          id: "player_prog",
          fileKey: atob( decodeURIComponent(["L25hczIuc","2hhcmUvaD","I2NC81MTJ","4Mzg0L3A1","MzU1L3A1M","zU1XzFfMj","AxOTEyMzE","yMDA5MjQ2","NzUzLm1wN","A%3D%3D"].join(""))),
          file: f,
                                  seekBarThumbnailsLoc: '//cdn-images.rtp.pt/multimedia/screenshots/p5355/preview/p5355_1_201912312009246753_preview.vtt',
                      adsType: 'dfp',
          subadUnit: 'Play',
          streamType:"ondemand",
          googleCast: true,
          drm : false,          //extraSettings: { googleCastReceiverAppId:'1A6F2224', skin:'s3',  skinAccentColor: '0073FF'},
          extraSettings: { googleCastReceiverAppId:'1A6F2224'},
          mediaType: "video",
          poster: "https://cdn-images.rtp.pt/EPG/imagens/36733_52570_94593.jpg?v=3&w=1170",
          modules: [{ name: 'RTPFavIcon', bucket: '1' }],
          metadata: {
            id: "794169"
          }
        });
```
`var x1` is not interesting: it's a preview of other weird stuff.

The commented assignment initialises a player with:
```
hls: https://streaming-ondemand.rtp.pt/nas2.share/h264/512x384/p1525/p1525_1_202104205996/masters.m3u8,
dash: https://streaming-vod.rtp.pt/dash/nas2.share/h264/512x384/p5355/p5355_1_201912312009246753.mp4/manifest.mpd
```
The HLS URL gives error 400. The DASH URL gives:
```
format code  extension  resolution note
a1-x3        m4a        audio only DASH audio  127k , m4a_dash container, mp4a.40.2 (48000Hz)
v1-x3        mp4        1024x576   DASH video 2056k , mp4_dash container, avc1.640029, 25fps, video only (best)
```
Next the first `var f`. This evaluates to:
```
hls: https://streaming-vod.rtp.pt/drm-fps/nas2.share/h264/512x384/p1525/p1525_1_202105106118.mp4/master.m3u8,
dash: https://streaming-vod.rtp.pt/drm-dash/nas2.share/h264/512x384/p1525/p1525_1_202105106118.mp4/manifest.mpd
```
The HLS URL gives:
```
format code  extension  resolution note
2047         mp4        1920x1080  2047k , avc1.640028, 25.0fps, mp4a.40.2
```
The DASH URL seems to have PlayReady DRM.

Next the second `var f`. This evaluates to 
```
hls: https://streaming-vod.rtp.pt/hls/nas2.share/h264/512x384/p5355/p5355_1_201912312009246753.mp4/master.m3u8,
dash: https://streaming-vod.rtp.pt/dash/nas2.share/h264/512x384/p5355/p5355_1_201912312009246753.mp4/manifest.mpd
```
HLS
```
format code  extension  resolution note
2184         mp4        1024x576   2184k , avc1.640029, 25.0fps, mp4a.40.2
```
DASH
```
format code  extension  resolution note
a1-x3        m4a        audio only DASH audio  127k , m4a_dash container, mp4a.40.2 (48000Hz)
v1-x3        mp4        1024x576   DASH video 2056k , mp4_dash container, avc1.640029, 25fps, video only (best)
```
Finally, looking at the actual player initialisation, the `fileKey` used to initialise the player evaluates to `/nas2.share/h264/512x384/p5355/p5355_1_201912312009246753.mp4`, and gives a playable video for As Horas Extraordinárias when expanded with the parameter provided:
`https://cdn-ondemand.rtp.pt/nas2.share/h264/512x384/p5355/p5355_1_201912312009246753.mp4?googleCastReceiverAppId=1A6F2224`

So the target should be the second `var f` and the `filekey`. A regex that targets `var f = {...}; var player1 = new RTPPlayer({...});` avoids confusion from the duplicated lines and the commented assignment.

In this [comment](https://github.com/ytdl-org/youtube-dl/issues/23707#issuecomment-576041184), it's also pointed out that the trailing comment `//extraSettings: { googleCastReceiverAppId:'1A6F2224', skin:'s3',  skinAccentColor: '0073FF'},` breaks the `js_to_json()` function from `utils.py`. A [modified version was proposed](https://github.com/ytdl-org/youtube-dl/pull/23877) but as it and the original code both rely on more than usually obscure use of regexes its validity is difficult to verify. However it's easy enough to change a trailing `r'\s//[^\n]*\n'` to `'\n'` which solves this case.

PR #28205 might address this issue, but the modified code looks rather tightly linked to the page source. Also more test URLs are needed for the extended `_VALID_URL`.

Finally issue #4939 asks for playlist support. As most, if not all, programme pages have the current episode as the main media and also the entire episode list, this runs into the problem of the semantics of `--no-playlist` and `--yes-playlist`. If the extractor could download the playlist, the single download should still be the default, but `--yes-playlist` isn't an actual option that the extractor can check (just the absence of `--no-playlist`), so the extractor can't distinguish between a command that uses `--yes-playlist` and one with no `--yes/no-playlist` option. Apparently playlist processing would have to navigate to each video page in turn and run the single video extraction.
