### ISSUE TITLE
Failed to download m3u8 information - No video formats found on CBS / Paramount+

### ISSUE THREAD

**Issue by jefft666** [ytdl-org/youtube-dl#29454]
Some (not all) file downloads failing when downloading from CBS / Paramount+

Episodes not able to download are playable via the web interface.

Have tried getting updated cookies.txt file but this did not resolve the issue.

Example details...

../youtube-dl --cookies ../cookies.txt --add-metadata -o "%(series)s.S%(season_number)02dE%(episode_number)02d.%(title)s.%(height)sp.DSCP.WEB-DL.%(ext)s" https://www.paramountplus.com/shows/star-trek-discovery/video/trdn_QshF1DlbsdedG6xdsnd5WwF6032/star-trek-discovery-si-vis-pacem-para-bellum/ --verbose

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--cookies', u'../cookies.txt', u'--add-metadata', u'-o', u'%(series)s.S%(season_number)02dE%(episode_number)02d.%(title)s.%(height)sp.DSCP.WEB-DL.%(ext)s', u'https://www.paramountplus.com/shows/star-trek-discovery/video/trdn_QshF1DlbsdedG6xdsnd5WwF6032/star-trek-discovery-si-vis-pacem-para-bellum/', u'--verbose']

[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.16 (CPython) - Darwin-20.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.2-tessus, ffprobe 3.4.2-tessus
[debug] Proxy map: {}

[CBS] trdn_QshF1DlbsdedG6xdsnd5WwF6032: Downloading XML
[CBS] trdn_QshF1DlbsdedG6xdsnd5WwF6032: Downloading StreamPack SMIL data
[CBS] trdn_QshF1DlbsdedG6xdsnd5WwF6032: Downloading m3u8 information

WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found

ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Traceback (most recent call last):
  File "../youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "../youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "../youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "../youtube-dl/youtube_dl/extractor/cbs.py", line 115, in _real_extract
    return self._extract_video_info(content_id)
  File "../youtube-dl/youtube_dl/extractor/cbs.py", line 97, in _extract_video_info
    self._sort_formats(formats)
  File "../youtube-dl/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')

ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jefft666** [comment]
I've added a --referer https://www.paramountplus.com/ command-line option to see if this resolves the issue (as described in the https://github.com/ytdl-org/youtube-dl/issues/29419 bug-report) but this was not able to resolve the issue.

If the dash file content might be of help I have one example attached.

[stream.mpd.txt](https://github.com/ytdl-org/youtube-dl/files/6758537/stream.mpd.txt)

**Comment by kikuyan** [comment]
This mpd contains `ContentProtection` tag and DRM protected.

**Comment by jefft666** [comment]
Yes, but so does this one (see attached) and it downloads just fine.

../youtube-dl --cookies ../cookies.txt --add-metadata -o "%(series)s.S%(season_number)02dE%(episode_number)02d.%(title)s.%(height)sp.DSCP.WEB-DL.%(ext)s" "https://www.paramountplus.com/shows/star-trek-discovery/video/UF5kG511ESgjBRjYvmmmJFGso_wKdLPg/star-trek-discovery-such-sweet-sorrow/"

[stream.mpd.2.txt](https://github.com/ytdl-org/youtube-dl/files/6758587/stream.mpd.2.txt)

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30491

**Comment by 89z** [comment]
I cant get `trdn_QshF1DlbsdedG6xdsnd5WwF6032`, but the other one works, even without cookies:

~~~
PS C:\> paramount -i -b UF5kG511ESgjBRjYvmmmJFGso_wKdLPg
Star Trek: Discovery -  Such Sweet Sorrow
Bandwidth:93000 Codecs:mp4a.40.2
Resolution:640x360 Bandwidth:495000 Codecs:avc1.640028, mp4a.40.2
Resolution:768x432 Bandwidth:833000 Codecs:avc1.640028, mp4a.40.2
Resolution:960x540 Bandwidth:1600000 Codecs:avc1.640028, mp4a.40.2
Resolution:1024x576 Bandwidth:2190000 Codecs:avc1.640028, mp4a.40.2
Resolution:1280x720 Bandwidth:3063000 Codecs:avc1.640028, mp4a.40.2
Resolution:1920x1080 Bandwidth:4525000 Codecs:avc1.640028, mp4a.40.2
~~~

https://github.com/89z/mech/blob/v1.49.3/paramount/paramount.go#L38-L59

**Comment by 89z** [comment]
Looks like `trdn_QshF1DlbsdedG6xdsnd5WwF6032` is using DRM, I checked both the Web and Android clients.

**Comment by 89z** [comment]
This video:

https://www.paramountplus.com/shows/video/trdn_QshF1DlbsdedG6xdsnd5WwF6032/

seems to require login. I think I had done the free trial, but that's expired now. I might have a solution for this, but I need someone to provide a login.
