### ISSUE TITLE
TubiTv - ValueError: unknown url type: ''

### ISSUE THREAD

**Issue by dare2** [ytdl-org/youtube-dl#29470]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://tubitv.com/tv-shows/591983/s01-e02-voodoo-parent-trap', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-81707-g11777eb, ffprobe N-81707-g11777eb, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 6.60.232.86 (US) as X-Forwarded-For.
[TubiTv] 591983: Downloading JSON metadata
[TubiTv] 591983: Downloading m3u8 information
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\__init__.py", line 465, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2069, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\tubitv.py", line 80, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1643, in _extract_m3u8_formats
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 667, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 629, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\utils.py", line 2158, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: ''

```

## Description

Only certain movies or shows on TubiTV produce this error. There is a closed issue from 4 months ago (#28369), but it was closed by the author saying that it resolved itself. I posted in that closed issue but I doubt I'll get any responses to a closed issue, so I'm opening a new one. The one thing that the other issue mentioned was to manually name the output file, which either didn't work for me or I didn't do it right.

**Comment by october262** [comment]
it looks like a DRM  issue - https://github.com/ytdl-org/youtube-dl/issues/28067

**Comment by dare2** [comment]
Thanks for verifying, and sorry to waste your time.
