### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by TruncatedDinosour** [ytdl-org/youtube-dl#29483]
## Checklist

- [x] I'm reporting a bug
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '[INSERT MY YOUTUBE PLAYLIST URL HERE (no, this is nor litaral, i just replaced this)]',
'--yes-playlist', '--extract-audio', '--audio-format', 'mp3']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.5 (CPython) - Linux-5.12.14-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[youtube:tab] PL7UuKajElTaChff3BkcJE6620lSuSUaDC: Downloading webpage
[download] Downloading playlist: Music
[youtube:tab] playlist Music: Downloading 30 videos
[download] Downloading video 1 of 30
[youtube] Zdt4UwbbQnc: Downloading webpage
[debug] Invoking downloader on 'https://r2---sn-uxv-3awl.googlevideo.com/videoplayback?expire=1625613704&ei=J5HkYIW9PNOD0u8P-pihuAE&ip=[INSERT MY IP HERE]&id=o-ABt-M1euqK_Ss_xUUli_Pf-XU2YRb9wMAnauzwgGqV_K&itag=251&source=youtube&requiressl=yes&mh=0e&mm=31%2C29&mn=sn-uxv-3awl%2Csn-f5f7lne7&ms=au%2Crdu&mv=m&mvi=2&pl=22&initcwndbps=1535000&vprv=1&mime=audio%2Fwebm&ns=i9i3CNMH6DjJODW0fYPfcogG&gir=yes&clen=1896933&dur=110.861&lmt=1577488598764383&mt=1625591809&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5431432&n=JFIQo-ALsgkUQt&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgTcgICd4duWgxj7ClLxZxVycFpN_6CVJVLXntOD9ADCoCIQCGCiYFS7u6fyGDyYUNy3LEQSeyMmIJvmYkN5vhaidwHg%3D%3D&sig=AOq0QJ8wRQIgbfq77Tg4FhDs6uFpabgf3wGnpbqznw9rMvx7AnR8kxgCIQDegNoGpO4t5LQCcRCE5i5y3q2tdfDu6z1cYW-txl1vPA=='
```

## Description

I was trying to download my playlist, but i get an error
```
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/ari/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 1976, in process_info
    success = dl(filename, info_dict)
  File "/home/ari/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "/home/ari/.local/lib/python3.9/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/home/ari/.local/lib/python3.9/site-packages/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/home/ari/.local/lib/python3.9/site-packages/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
  File "/home/ari/.local/lib/python3.9/site-packages/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/ari/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by dbedrenko** [comment]
Had the same error today. After retrying it worked for me.

**Comment by TruncatedDinosour** [comment]
> Had the same error today. After retrying it worked for me.

Worked now, thanks

**Comment by dimsanchuk** [comment]
I have the same problem too. A simple restart helps, yes, but it's too unstable.
I tried to reset cache with `--rm-cache-dir`, but it does not help. The download crashes on another video.
