### ISSUE TITLE
Servus TV not working anymore

### ISSUE THREAD

**Issue by IVleafclover** [ytdl-org/youtube-dl#29485]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

.\youtube-dl.exe -v -F https://www.servustv.com/unterhaltung/v/aa-1vrgdg2yd1w12/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.servustv.com/unterhaltung/v/aa-1vrgdg2yd1w12/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-01-05-git-66deab3a26-full_build-www.gyan.dev, ffprobe 2021-01-05-git-66deab3a26-full_build-www.gyan.dev
[debug] Proxy map: {}
[generic] aa-1vrgdg2yd1w12: Requesting header
WARNING: Falling back on generic information extractor.
[generic] aa-1vrgdg2yd1w12: Downloading webpage
[generic] aa-1vrgdg2yd1w12: Extracting information
ERROR: Unsupported URL: https://www.servustv.com/unterhaltung/v/aa-1vrgdg2yd1w12/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\generic.py", line 3520, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.servustv.com/unterhaltung/v/aa-1vrgdg2yd1w12/

## Description

Youtube-dl is not working with Servus TV, after Servus TV changed their website today.
Seems like every command is failing, even the example command for finding the available formats.
Example command: youtube-dl -v -F https://www.servustv.com/unterhaltung/v/aa-1vrgdg2yd1w12/

**Comment by kikuyan** [comment]
In case you need temporary workaround, old style url might work for some videos. Change
h<span></span>ttps://www.servustv.com/**unterhaltung/v**/aa-1vrgdg2yd1w12/
to
h<span></span>ttps://www.servustv.com/**videos**/aa-1vrgdg2yd1w12/

**Comment by chrisausat** [comment]
What must i change for:
https://www.servustv.com/wissen/v/aa-1x7uv5sfw1w12/

**Comment by MuenchenSued** [comment]
Use "videos" instead of "wissen/v"
https://www.servustv.com/videos/aa-1x7uv5sfw1w12/

**Comment by macpingel** [comment]
The workaround doesn't work anymore as of today:
youtub-dl --list-formats https://www.servustv.com/videos/aa-22avg2pf11w12/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--list-formats', u'https://www.servustv.com/videos/aa-22avg2pf11w12/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.16 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4-tessus, ffprobe 4.4-tessus
[debug] Proxy map: {}
[Servus] AA-22AVG2PF11W12: Downloading token
ERROR: Unable to download JSON metadata: HTTP Error 401:  (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by hebrit** [comment]
youtube-dl.exe --no-check-certificate --verbose https://www.servustv.com/videos/aa-24z4dm6ah1w12/

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-check-certificate', '--verbose', 'https://www.servustv.com/videos/aa-24z4dm6ah1w12/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.12.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[Servus] AA-24Z4DM6AH1W12: Downloading token
ERROR: Unable to download JSON metadata: HTTP Error 401:  (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpz3dfuc4o\build\youtube_dl\extractor\common.py", line 632, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpz3dfuc4o\build\youtube_dl\YoutubeDL.py", line 2248, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by uahim** [comment]
in-browser solution until someone fixes the extractor; bookmarklets:
https://gist.github.com/uahim/b0c4b43101440b1f1525ef647025a9f2
