### ISSUE TITLE
IMDB is partially broken - need support for new URL scheme

### ISSUE THREAD

**Issue by someziggyman** [ytdl-org/youtube-dl#29516]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v -F "https://www.imdb.com/title/tt12801262/?ref_=hm_tpks_tt_t_3_pd_tp1_cp"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.imdb.com/title/tt12801262/?ref_=hm_tpks_tt_t_3_pd_tp1_cp']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Git HEAD: 35b15af40
[debug] Python version 3.9.6 (CPython) - macOS-11.4-arm64-arm-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] ?ref_=hm_tpks_tt_t_3_pd_tp1_cp: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?ref_=hm_tpks_tt_t_3_pd_tp1_cp: Downloading webpage
[generic] ?ref_=hm_tpks_tt_t_3_pd_tp1_cp: Extracting information
ERROR: Unsupported URL: https://www.imdb.com/title/tt12801262/?ref_=hm_tpks_tt_t_3_pd_tp1_cp
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/generic.py", line 3520, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.imdb.com/title/tt12801262/?ref_=hm_tpks_tt_t_3_pd_tp1_cp
```

## Description

Looks like the imdb now has a new URL scheme that has .../title/... path in the middle. 
These links return "unsupported site error". Regular links with .../video/.. path are working just fine.

**Links that fail:**
https://www.imdb.com/title/tt12801262/?ref_=hm_tpks_tt_t_3_pd_tp1_cp
https://www.imdb.com/title/tt0804484/?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=332cb927-0342-42b3-815c-f9124e84021d&pf_rd_r=VW90BD8BJ57TZ09DVA0G&pf_rd_s=center-1&pf_rd_t=15506&pf_rd_i=tvmeter&ref_=chttvm_tt_34

**Links that work:**
https://www.imdb.com/video/vi521123609?playlistId=tt5028002&ref_=tt_pr_ov_vi
https://www.imdb.com/video/vi33734681?ref_=hp_hp_e_3&listId=ls053181649

../title/.. links are generated from lists like that:
https://www.imdb.com/chart/tvmeter/?ref_=nv_tvv_mptv
Or from the main page clicking on any movie poster in TopPicks, Fan favourites collections..

**Comment by Gloster10** [comment]
Perhaps the same issue. Since last week. I get the same error as described above, refer to link :
https://www.servustv.com/unterhaltung/v/aa-2376p8pc11w12/
See also the attached file.

[youtube-dlOutput.txt](https://github.com/ytdl-org/youtube-dl/files/6805784/youtube-dlOutput.txt)

**Comment by kikuyan** [comment]
For servustv.com, go #29485.

**Comment by Gloster10** [comment]
Thanks kikuyan, it works fine.
