### ISSUE TITLE
ABC iview no longer supported

### ISSUE THREAD

**Issue by hansworzt** [ytdl-org/youtube-dl#29512]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

youtube-dl -f "best[height<720]" --verbose https://iview.abc.net.au/video/DO1840H001S00
and
youtube-dl -f "best[height<720]" --verbose https://iview.abc.net.au/show/australia-remastered-australia-s-oceans/series/0/video/DO1840H001S00
result in:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best[height<720]', '--verbose', 'https://iview.abc.net.au/video/DO1840H001S00']
[debug] Encodings: locale cp65001, fs mbcs, out cp65001, pref cp65001
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg n4.3.1-19-gaf2a430bb1, ffprobe n4.3.1-19-gaf2a430bb1
[debug] Proxy map: {}
[debug] Using fake IP 1.149.91.156 (AU) as X-Forwarded-For.
[abc.net.au:iview] DO1840H001S00: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('playlist',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\abc.py", line 135, in _real_extract
KeyError: 'playlist'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\abc.py", line 135, in _real_extract
KeyError: 'playlist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 547, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('playlist',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

ABC iView no longer supported as they recently added DRM to all the streams.

**Comment by hansworzt** [comment]
Seems to be geoblocking issue as it still works using an Australian VPN.

**Comment by misuchiru03** [comment]
> Seems to be geoblocking issue as it still works using an Australian VPN.

Concur on geoblocking. If you have VPN and it still isn't working, your VPN may be bad (some don't allow streaming) or it isn't configured to route ipv6 as was my case. I found `--force-ipv4` corrected the issue for me.

**Comment by hansworzt** [comment]
> I found --force-ipv4 corrected the issue for me.

Your suggestion can only be used/tested with a VPN that works at OS level, not using a VPN plugin from the browser.

**Comment by misuchiru03** [comment]
> > I found --force-ipv4 corrected the issue for me.
> 
> Your suggestion can only be used/tested with a VPN that works at OS level, not using a VPN plugin from the browser.

I assume this to be correct as I understand it. I was using OpenVPN, so I apologize for the missing information there. That option was for Openvpn using cyberghost vpn service (which for some reason ipv6 was not configured correctly or at all).
