### ISSUE TITLE
[rtve.es:alacarta] Base URL changed while renaming service

### ISSUE THREAD

**Issue by fcaneva-arg** [ytdl-org/youtube-dl#29522]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.06.06**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v 'https://www.rtve.es/play/videos/saber-y-ganar/edicion-fin-semana-11-07-21/5977613/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.rtve.es/play/videos/saber-y-ganar/edicion-fin-semana-11-07-21/5977613/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-66-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 5977613: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 5977613: Downloading webpage
[generic] 5977613: Extracting information
ERROR: Unsupported URL: https://www.rtve.es/play/videos/saber-y-ganar/edicion-fin-semana-11-07-21/5977613/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/generic.py", line 3520, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.rtve.es/play/videos/saber-y-ganar/edicion-fin-semana-11-07-21/5977613/

```

## Description

Radio Televisión Española (RTVE, Spanish for _Spanish Radio & Television Company_) is changing the name of his site "A la carta" (_On demand_) to "RTVE Play", also modifying their URLs for accessing contents. The URL changed slightly, modifying the folder `alacarta` for `play`, making the current extractor version unable to continue processing the page and falling back to the `generic` extractor (which also fail).

Old URLs had the following structure (for example, the last emission of "Saber y Ganar" as of today, July 11 2021):
```https://www.rtve.es/alacarta/videos/saber-y-ganar/edicion-fin-semana-11-07-21/5977613/```
While new URLs have the following structure:
```https://www.rtve.es/play/videos/saber-y-ganar/edicion-fin-semana-11-07-21/5977613/```

Manually modifying the URL before running the command (i.e. changing `play` for `alacarta`) results in a **successful execution**:

```
$ youtube-dl -v https://www.rtve.es/alacarta/videos/saber-y-ganar/edicion-fin-semana-11-07-21/5977613/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.rtve.es/alacarta/videos/saber-y-ganar/edicion-fin-semana-11-07-21/5977613/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-66-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[rtve.es:alacarta] Fetching manager info
[rtve.es:alacarta] 5977613: Downloading JSON metadata
[rtve.es:alacarta] 5977613: Downloading url information
[rtve.es:alacarta] 5977613: Downloading m3u8 information
[rtve.es:alacarta] 5977613: Downloading m3u8 information
[rtve.es:alacarta] 5977613: Downloading MPD manifest
[rtve.es:alacarta] 5977613: Downloading MPD manifest
[rtve.es:alacarta] 5977613: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 503: Service Unavailable
[rtve.es:alacarta] 5977613: Downloading m3u8 information
[rtve.es:alacarta] 5977613: Downloading m3u8 information
[rtve.es:alacarta] 5977613: Downloading MPD manifest
[rtve.es:alacarta] 5977613: Downloading MPD manifest
[rtve.es:alacarta] 5977613: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 503: Service Unavailable
[rtve.es:alacarta] 5977613: Downloading m3u8 information
[rtve.es:alacarta] 5977613: Downloading m3u8 information
[rtve.es:alacarta] 5977613: Downloading MPD manifest
[rtve.es:alacarta] 5977613: Downloading MPD manifest
[rtve.es:alacarta] 5977613: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 503: Service Unavailable
[rtve.es:alacarta] 5977613: Downloading m3u8 information
[rtve.es:alacarta] 5977613: Downloading m3u8 information
[rtve.es:alacarta] 5977613: Downloading MPD manifest
[rtve.es:alacarta] 5977613: Downloading MPD manifest
[rtve.es:alacarta] 5977613: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 503: Service Unavailable
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://rtve-hlsvod.secure.footprint.net/resources/TE_NGVA/mp4/4/6/1625644120564.mp4/video.mpd?idasset=5977613'
[dashsegments] Total fragments: 550
[download] Destination: Saber y ganar. Edición de fin de semana - 11_07_21-5977613.fdash-video=4000000-1.mp4

... (Log was cut)
```

## Ideas for fix:
- Drop support for `alacarta` in favour of `play`
- Add the support for `play`, redirecting the download process to `alacarta`

**Comment by dirkf** [comment]
Just changing the URL pattern appears to fix this, as expected from the problem description: eg, change the fragment `(alacarta/videos|filmoteca)` in the definition  of `_VALID_URL` to `((alacarta|play)/videos|filmoteca)` in `extractor/rtve.py`.

**Comment by arturoherrero** [comment]
Possible fix https://github.com/ytdl-org/youtube-dl/pull/29816.
