### ISSUE TITLE
Got no video format error

### ISSUE THREAD

**Issue by bittusharma0** [ytdl-org/youtube-dl#29532]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/dispatcher.py", line 217, in handler_worker
    await handler.callback(self.client, *args)
  File "/app/handlers/play.py", line 507, in play
    file_path = await converter.convert(youtube.download(url))
  File "/app/downloaders/youtube.py", line 18, in download
    info = ydl.extract_info(url, True)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2021-07-13 11:04:20,526 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): youtube.com:443
2021-07-13 11:04:20,550 - urllib3.connectionpool - DEBUG - https://youtube.com:443 "GET /results?search_query= HTTP/1.1" 301 0
2021-07-13 11:04:20,552 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): www.youtube.com:443
2021-07-13 11:04:20,597 - urllib3.connectionpool - DEBUG - https://www.youtube.com:443 "GET /results?search_query HTTP/1.1" 200 None.... How to fix it

**Comment by kikuyan** [comment]
This is not the log of youtube-dl, you are not describing the situation, not showing the url or options.
