### ISSUE TITLE
[VrtNU] Authentication failed

### ISSUE THREAD

**Issue by cyberox** [ytdl-org/youtube-dl#29534]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.vrt.be/vrtnu/a-z/de-zevende-dag/2021/de-zevende-dag-d20210627/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[VrtNU] Logging in
[VrtNU] Requesting a token
WARNING: [VrtNU] Authentication failed
[VrtNU] Waiting for 1 seconds before trying again
[VrtNU] Requesting a token
WARNING: [VrtNU] Authentication failed
[VrtNU] Waiting for 1 seconds before trying again
[VrtNU] Requesting a token
WARNING: [VrtNU] Authentication failed
[VrtNU] Waiting for 1 seconds before trying again
[VrtNU] de-zevende-dag-d20210627: Downloading webpage
[Canvas] pbs-pub-0a163591-000e-4f09-bf70-8c0e3347045a$vid-2daf5010-a534-49b9-940b-cbe40cb96384: Downloading token
[Canvas] pbs-pub-0a163591-000e-4f09-bf70-8c0e3347045a$vid-2daf5010-a534-49b9-940b-cbe40cb96384: Downloading video JSON
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\canvas.py", line 77, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 943, in raise_login_required
youtube_dl.utils.ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
```

## Description

Altough I'm using correct credentials, youtube-dl is unable to download content, because of the _Authentication failed_ warning.
The correct cookie is not set. I've noticed also that https://token.vrt.be is no longer accessible.

**Comment by bergoid** [comment]
By changing the login procedure I got rid of the "Authentication failed" warning:

https://github.com/bergoid/youtube-dl/commit/c9c5165ab9952b1d79acb8eeb9b8db4e3bc9435e

Not sure if that means a lot, though.

The download still fails for the same reason, because since recently the "vualto video aggregator" API demands a signed JWT token ('identityToken') before handing out the 'vrtPlayerToken'.

Any help would be much appreciated.

**Comment by pgaig** [comment]
I wrote a fix #29614 heavily inspired from add-ons/plugin.video.vrt.nu#885 and the comments in #29044.

**Comment by bergoid** [comment]
> 
> 
> I wrote a fix #29614 heavily inspired from [add-ons/plugin.video.vrt.nu#885](https://github.com/add-ons/plugin.video.vrt.nu/pull/885) and the comments in #29044.

Thank you!
It works like a charm.

**Comment by sharethewisdom** [comment]
@pgaig  hmm I tried your branch at https://github.com/pgaig/youtube-dl/commit/03d89133f32a77d424b61279b4714778d06d9c15 but it didn't work for me (I double checked for correct credentials)

```
[debug] System config: ['--no-call-home', '--socket-timeout', '9', '--restrict-filenames']
[debug] User config: ['-o', '/tmp/2021_%(title).50s.%(id)s.%(ext)s', '-f', 'worst,mp4', '--socket-timeout', '20', '--write-description', '--continue', '--no-call-home', '--cookies', '~/downl/cookies/cookies.Google.txt']
[debug] Custom config: []
[debug] Command-line args: ['--netrc', '--verbose', 'https://www.vrt.be/vrtnu/a-z/de-zevende-dag/2021/de-zevende-dag-d20210627/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.6 (CPython) - Linux-5.13.4-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[VrtNU] Logging in
[VrtNU] Requesting a token
WARNING: [VrtNU] Authentication failed
[VrtNU] Waiting for 1 seconds before trying again
[VrtNU] Requesting a token
WARNING: [VrtNU] Authentication failed
[VrtNU] Waiting for 1 seconds before trying again
[VrtNU] Requesting a token
WARNING: [VrtNU] Authentication failed
[VrtNU] Waiting for 1 seconds before trying again
[VrtNU] de-zevende-dag-d20210627: Downloading webpage
[Canvas] pbs-pub-0a163591-000e-4f09-bf70-8c0e3347045a$vid-2daf5010-a534-49b9-940b-cbe40cb96384: Downloading token
[Canvas] pbs-pub-0a163591-000e-4f09-bf70-8c0e3347045a$vid-2daf5010-a534-49b9-940b-cbe40cb96384: Downloading video JSON
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/canvas.py", line 77, in _real_extract
    self.raise_login_required()
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 941, in raise_login_required
    raise ExtractorError(
youtube_dl.utils.ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
```

**Comment by pgaig** [comment]
Hi @sharethewisdom , I tried to download the example you mentioned and it works for me:

```
$ git clone https://github.com/pgaig/youtube-dl.git
$ git checkout test-vrtnu-logon
$ cd youtube-dl
$ python3 -m youtube_dl https://www.vrt.be/vrtnu/a-z/de-zevende-dag/2021/de-zevende-dag-d20210627/ --netrc
[VrtNU] Login data
[VrtNU] Requesting XSRF Token
[VrtNU] Requesting a token
...
```
Note that you get old VrtNU loglines, so my guess is that you're using an older version of youtube-dl. Maybe `export PYTHONPATH=.` and execute from the checkedout path?

**Comment by sharethewisdom** [comment]
ok super, thanks, it seems to work, sorry I was hasty and assumed I could just run it as `./bin/youtube-dl` :roll_eyes:

**Comment by xplorr** [comment]
Works perfect here! Thx!

**Comment by BelgianNoise** [comment]
For people ending up in this issue you can always download with a little more effort (even no authentication needed):

1. Load the video page and open dev tools
2. Go to the network tab and refresh
3. filter by "pbs" and select the only filtered request
4. in `targetUrls` find the `type: "hls_aes"` and use that uri to simply `youtube-dl <uri>` in the cli

![image](https://user-images.githubusercontent.com/38424924/130657609-199a4855-63ae-492f-92bb-d18b244d90d3.png)

**Comment by GitMew** [comment]
@BelgianNoise Although this does work for me for [this video](https://www.vrt.be/vrtnu/a-z/goulag--une-histoire-sovietique/1/goulag--une-histoire-sovietique-s1a1), it spams my CLI with alternating "Invalid timestamps" and "Invalid DTS" messages:
![image](https://user-images.githubusercontent.com/37484463/132598431-8928dd0a-2260-4200-90be-0cd1109e3d48.png)
Is that supposed to happen? The `targetUrl` of type `hls_aes` is `https://remix-cf-vrt.akamaized.net/remix/8f9121a3-5eb4-4735-8ed4-51d68d74967a/remix_aes.ism/.m3u8`.

**Comment by BelgianNoise** [comment]
@GitMew weird, I will try this tomorrow with the link you provided.

**Comment by BelgianNoise** [comment]
@GitMew I am not sure if I have seen that before, also I mostly only look at the output file and check if it plays.

I ill try it out with the link you provided when I got the time.

**Comment by xplorr** [comment]
Problem still continues again with error:
`ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.`

**Comment by sharethewisdom** [comment]
same here.


```
$ PYTHONPATH=. python -m youtube_dl --netrc --verbose  -f worst https://www.vrt.be/vrtnu/a-z/terzake/2021/terzake-d20211105/
[debug] System config: ['--no-call-home', '--socket-timeout', '9', '--restrict-filenames']
[debug] User config: ['-o', '/tmp/2021_%(title).50s.%(id)s.%(ext)s', '-f', 'worst,mp4', '--socket-timeout', '20', '--write-description', '--continue', '--no-call-home', '--cookies', '~/downl/cookies/cookies.Google.txt']
[debug] Custom config: []
[debug] Command-line args: ['--netrc', '--verbose', '-f', 'worst', 'https://www.vrt.be/vrtnu/a-z/terzake/2021/terzake-d20211105/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Git HEAD: e0556cd9
[debug] Python version 3.9.7 (CPython) - Linux-5.14.14-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[VrtNU] Login data
[VrtNU] Requesting XSRF Token
[VrtNU] Requesting a token
[VrtNU] terzake-d20211105: Downloading webpage
[Canvas] pbs-pub-ab4a82f9-9d23-4016-bc45-5fad8b7a85c6$vid-84d20842-0307-4edb-b623-4467b3fd8084: Downloading token
[Canvas] pbs-pub-ab4a82f9-9d23-4016-bc45-5fad8b7a85c6$vid-84d20842-0307-4edb-b623-4467b3fd8084: Downloading video JSON
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "/home/bart/repos/github/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/bart/repos/github/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/bart/repos/github/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/bart/repos/github/youtube-dl/youtube_dl/extractor/canvas.py", line 77, in _real_extract
    self.raise_login_required()
  File "/home/bart/repos/github/youtube-dl/youtube_dl/extractor/common.py", line 941, in raise_login_required
    raise ExtractorError(
youtube_dl.utils.ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
```

**Comment by Dre62** [comment]
Same here, a few weeks ago it still worked, now I have the same error while I provide the correct credentials.

**Comment by brechtm** [comment]
This is fixed in [yt-dlp](https://github.com/yt-dlp/yt-dlp)

**Comment by lajawi** [comment]
> This is fixed in [yt-dlp](https://github.com/yt-dlp/yt-dlp)

It does not (anymore).

**Comment by brechtm** [comment]
Many videos on VRT nu are now DRM protected, so they can't be downloaded by youtube-dl or yt-dlp anymore (https://github.com/yt-dlp/yt-dlp/issues/2678).

**Comment by BelgianNoise** [comment]
There is always another way.
