### ISSUE TITLE
Could not send HEAD request to https://playlist.megaphone.fm/ & Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] 

### ISSUE THREAD

**Issue by MagTun** [ytdl-org/youtube-dl#29539]
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2021.06.06**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -ciw -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0  "https://playlist.megaphone.fm/?e=FULLCAST5192859578" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-ciw', '-f', 'bestaudio', '--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0', 'https://playlist.megaphone.fm/?e=FULLCAST5192859578', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] ?e=FULLCAST5192859578: Requesting header
WARNING: Could not send HEAD request to https://playlist.megaphone.fm/?e=FULLCAST5192859578: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[generic] ?e=FULLCAST5192859578: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\utils.py", line 2737, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
```

## Description

I am trying to download this podcast `https://playlist.megaphone.fm/?e=FULLCAST5192859578` but I get an error. `megaphone.fm` is in the list of the [supported websites](https://ytdl-org.github.io/youtube-dl/supportedsites.html)

Windows 10

**Comment by kikuyan** [comment]
Your OS problem:
> ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))

**Comment by MagTun** [comment]
@kikuyan , I don't understand what you mean by "your OS problem" as youtube-dl works fine with links from youtube for example. 

In the meantime, I did more debugging.

The debug from above comes from the youtube-dl.exe (for windows). But I also have another` youtube-dl` installed from python (also the 2021.06.06 version). And here is the debug:

```
youtube-dl -ciw -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0  "https://playlist.megaphone.fm/?e=FULLCAST5192859578" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-ciw', '-f', 'bestaudio', '--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0', 'https://playlist.megaphone.fm/?e=FULLCAST5192859578', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.6.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] ?e=FULLCAST5192859578: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?e=FULLCAST5192859578: Downloading webpage
[generic] ?e=FULLCAST5192859578: Extracting information
ERROR: Unsupported URL: https://playlist.megaphone.fm/?e=FULLCAST5192859578
Traceback (most recent call last):
  File "c:\users\me\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\me\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\me\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\users\me\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\generic.py", line 3520, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://playlist.megaphone.fm/?e=FULLCAST5192859578
```

It seems that youtube-dl.exe doesn't flash the right error, as youtube-dl from Python says that the link is actually unsupported. 


Also another thing that is strange from the debug from youtube-dl.exe is that it mentions this path `C:\Python\Python34`. It seemed weird as I don't have a Python34 installation, I only have python 3.6 and 3.9. Also I don't install my python in `C:\Python` but in `appdata`. So I checked the link and it doesn't exist. 

Just to be sure, I tried a debug with a youtube link with youtube-dl.exe and it also mention the Python 3.4 but it doesn't mention the path:
```
youtube-dl -ciw -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0  "https://www.youtube.com/watch?v=oMcX4AKvfvE" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-ciw', '-f', 'bestaudio', '--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0', 'https://www.youtube.com/watch?v=oMcX4AKvfvE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube] oMcX4AKvfvE: Downloading webpage
```
---
Just in case this info is needed: when pasting the debug from `youtube-dl.exe`, I have renamed the command to `youtube-dl` but actually I use `youtubedl` for this version  (without the -)  and `youtube-dl` for the python version and so that I know which one I call.

**Comment by dirkf** [comment]
The `megaphone.fm` extractor knows about URLs like `http://player.megaphone.fm/...`. The hint that the URL isn't supported is that the `[generic]` extractor appears in the log.

*However*, it looks like the site has been React-ified and the extractor's knowledge is wrong.

The playlist link retrieves a JSON playlist `https://player.megaphone.fm/playlist/episode/FULLCAST5192859578` including an `episodes` member which is a list containing the data for each episode. In this case there's just one, which you could equally access as `https://player.megaphone.fm/FULLCAST5192859578`. In the episode data is the audio URL `https://traffic.megaphone.fm/FULLCAST5192859578.mp3`.

**Comment by MagTun** [comment]
Thanks for you comment. I tried again with the link you provided and it is strange: it works well with youtube-dl from python but not with youtube-dl.exe

● debug from youtube-dl.exe: same error 

```
youtube-dl -ciw -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0  "https://traffic.megaphone.fm/FULLCAST5192859578.mp3" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-ciw', '-f', 'bestaudio', '--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0', 'https://traffic.megaphone.fm/FULLCAST5192859578.mp3', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] FULLCAST5192859578: Requesting header
WARNING: Could not send HEAD request to https://traffic.megaphone.fm/FULLCAST5192859578.mp3: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[generic] FULLCAST5192859578: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\utils.py", line 2737, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
```

● debug youtude-dl from pythonL: it's working

```
youtube-dl -ciw -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0  "https://traffic.megaphone.fm/FULLCAST5192859578.mp3" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-ciw', '-f', 'bestaudio', '--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0', 'https://traffic.megaphone.fm/FULLCAST5192859578.mp3', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.6.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] FULLCAST5192859578: Requesting header
[redirect] Following redirect to https://dcs.megaphone.fm/FULLCAST5192859578.mp3?key=c7f8709d8f6b282a3da799e78820eaf2
[generic] FULLCAST5192859578: Requesting header
[debug] Invoking downloader on 'https://dcs.megaphone.fm/FULLCAST5192859578.mp3?key=c7f8709d8f6b282a3da799e78820eaf2'
[download] Resuming download at byte 32273833
[download] Destination: FULLCAST5192859578-FULLCAST5192859578.mp3
[download]  62.7% of 52.28MiB at  3.55MiB/s ETA 00:05
```
Once again both youtube-dl python and youtube-dl.exe are the same version: 2021.06.06


Also it would be nice if youtube-dl could transform itself the link from `https://playlist.megaphone.fm/?e=FULLCAST5192859578` to `https://traffic.megaphone.fm/FULLCAST5192859578.mp3`

**Comment by dirkf** [comment]
The extractor needs a rewrite.

There seems to be a problem with the SSL support (missing CA certificates?) in the Python 3.4 used in the first case. Clearly you should use the Pythonic version, which also has a newer Python base.

**Comment by MagTun** [comment]
Thanks for your help @dirkf
