### ISSUE TITLE
AtomicParsley (included in latest debian/ubuntu) cannot embed JPEG thumbnails that are not JFIF

### ISSUE THREAD

**Issue by sebma** [ytdl-org/youtube-dl#29555]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```python
$ ytdlnoconfig --embed-thumbnail -v https://www.dailymotion.com/video/x2ehr3o
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '--embed-thumbnail', '-v', 'https://www.dailymotion.com/video/x2ehr3o']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-77-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] Downloading Access Token
[dailymotion] x2ehr3o: Downloading media JSON metadata
[dailymotion] x2ehr3o: Downloading metadata JSON
[dailymotion] x2ehr3o: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[dailymotion] x2ehr3o: Downloading thumbnail ...
[dailymotion] x2ehr3o: Writing thumbnail to: L'esclavage moderne-x2ehr3o.jpg
[debug] Invoking downloader on 'https://proxy-034.dc3.dailymotion.com/sec(z1LdIxCmoIMisR-U4IapUaEcgnLOEo2HA01OqdyJmwybOePxVY4hKRNWRBGg1mIO7tSS0Dj4s3S7dSyXyXwmiw)/video/252/572/145275252_mp4_h264_aac_hq_2.mp4'
[download] Destination: L'esclavage moderne-x2ehr3o.mp4
[download] 100% of 117.59MiB in 16:01
[atomicparsley] Adding thumbnail to "L'esclavage moderne-x2ehr3o.mp4"
[debug] AtomicParsley command line: AtomicParsley 'L'"'"'esclavage moderne-x2ehr3o.mp4' --artwork 'L'"'"'esclavage moderne-x2ehr3o.jpg' -o 'L'"'"'esclavage moderne-x2ehr3o.temp.mp4'
ERROR: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 2115, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/postprocessor/embedthumbnail.py", line 116, in run
    raise EmbedThumbnailPPError(msg)
youtube_dl.postprocessor.embedthumbnail.EmbedThumbnailPPError

```

## Description

The AtomicParsley tool supplied in the latest release of debian and ubuntu does not support JPEG thumbnails that are not JFIF : 
```
$ file "L'esclavage moderne-x2ehr3o.jpg" 
L'esclavage moderne-x2ehr3o.jpg: JPEG image data, baseline, precision 8, 1884x1080, components 3
```

Can you please convert the downloaded thumbnails with `convert` of `ffmpeg` before actually calling AtomicParsley.

N.B. : If I download and convert the thumbnail myself to JFIF before calling `youtube-dl`, then `youtube-dl` re-downloads it and overwrites my newly converted thumbnail :

**Comment by kikuyan** [comment]
Although AtomicParsley hasn't been updated for years, why not filing a bug report to AtomicParsley and/or asking Debian/Ubuntu package managers to include forked version of [AtomicParsley](https://github.com/wez/atomicparsley)?
Besides, you know the forked version well.

I feel this request is strange, even if changing youtube-dl is not difficult.

**Comment by sebma** [comment]
@kikuyan I understand but in the meantime that debian/ubuntu update their package into their repositories, can please prevent `youtube-dl` from overwriting the (the manually pre-downloaded) thumbnail to the filesystem in the case where the video has never been downloaded by `youtube-dl` ?

**Comment by 89z** [comment]
You can embed image with FFmpeg now, so you don't even need AtomicParsley:

~~~
youtube-dl -g https://www.dailymotion.com/video/x2ehr3o

aria2c -x 9 -s 9 -k 1048576 --disable-ipv6 `
'https://proxy-14.nyc.dailymotion.com/sec(SKdPEVqvKmvPRLaUbPCevLKKsEfMlLXNTczrAvaWjFqqCOy7cqyA52EehUWhgIUxxs8w7vxnPfTRkvAbWmjETw)/video/252/572/145275252_mp4_h264_aac_hq_2.mp4'

ffmpeg -i http://s2.dmcdn.net/v/8gBbq1VtIDl9VF0Wf/x720 `
-i before.mp4 -map 0 -map 1 -c copy -disposition:v:0 attached_pic after.mp4
~~~
