### ISSUE TITLE
DW News

### ISSUE THREAD

**Issue by mnlmsf** [ytdl-org/youtube-dl#29553]
- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

https://www.dw.com/en/top-stories-in-90-seconds/av-49496622
https://p.dw.com/p/3LgKc

## Description

Daily 90 seconds news bulletin from DW News.

I used to download this every evening. Looks like they've blocked it, I don't know, I don't understand.

**Comment by mnlmsf** [comment]
[07/15/21 22:13:39] [debug] System config: []
[07/15/21 22:13:39] [debug] User config: []
[07/15/21 22:13:39] [debug] Custom config: []
[07/15/21 22:13:39] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\manue\\Videos\\%(title)s.%(ext)s', '--ignore-config', '--hls-prefer-native', '--verbose', 'https://p.dw.com/p/3LgKc']
[07/15/21 22:13:39] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[07/15/21 22:13:39] [debug] youtube-dl version 2021.06.06
[07/15/21 22:13:39] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[07/15/21 22:13:39] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[07/15/21 22:13:39] [debug] Proxy map: {}
[07/15/21 22:13:39] ERROR: An extractor error has occurred. (caused by KeyError('file_name',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[07/15/21 22:13:39] Traceback (most recent call last):
[07/15/21 22:13:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
[07/15/21 22:13:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\dw.py", line 66, in _real_extract
[07/15/21 22:13:39] KeyError: 'file_name'
[07/15/21 22:13:39] Traceback (most recent call last):
[07/15/21 22:13:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
[07/15/21 22:13:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\dw.py", line 66, in _real_extract
[07/15/21 22:13:39] KeyError: 'file_name'
[07/15/21 22:13:39] 
[07/15/21 22:13:39] During handling of the above exception, another exception occurred:
[07/15/21 22:13:39] 
[07/15/21 22:13:39] Traceback (most recent call last):
[07/15/21 22:13:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
[07/15/21 22:13:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
[07/15/21 22:13:39]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 547, in extract
[07/15/21 22:13:39] youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('file_name',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[07/15/21 22:13:39]

**Comment by dirkf** [comment]
Working OK in UK for both links.

Are they actually playable in your browser?

**Comment by mnlmsf** [comment]
Yes, it works again now. Downloading didn't work for several days.
