### ISSUE TITLE
ServusTV no longer working

### ISSUE THREAD

**Issue by busybit** [ytdl-org/youtube-dl#29554]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.06.06**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v 'https://www.servustv.com/aktuelles/v/aa-28a3dbyxh1w11/'
[debug] System config: []
[debug] User config: [u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.servustv.com/aktuelles/v/aa-28a3dbyxh1w11/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.16 (CPython) - Linux-3.16.85+-aarch64-with-debian-10.0
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[generic] aa-28a3dbyxh1w11: Requesting header
WARNING: Falling back on generic information extractor.
[generic] aa-28a3dbyxh1w11: Downloading webpage
[generic] aa-28a3dbyxh1w11: Extracting information
ERROR: Unsupported URL: https://www.servustv.com/aktuelles/v/aa-28a3dbyxh1w11/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2503, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2571, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2560, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3520, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.servustv.com/aktuelles/v/aa-28a3dbyxh1w11/
```

## Description

ServusTV Mediathek no longer working. Looks like the site changed in some way.

**Comment by kikuyan** [comment]
Go #29485 and try a workaround for the time being.
