### ISSUE TITLE
Paramount+ downloads no longer working

### ISSUE THREAD

**Issue by Grandfather-Paradox** [ytdl-org/youtube-dl#29564]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.paramountplus.com/shows/catdog/video/Oe44g5_NrlgiZE3aQVONleD6vXc8kP0k/catdog-climb-every-catdog-the-canine-mutiny/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.6 (CPython) - Linux-5.10.50-1-lts-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[CBS] Oe44g5_NrlgiZE3aQVONleD6vXc8kP0k: Downloading XML
ERROR: Could not find XML element title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/cbs.py", line 115, in _real_extract
    return self._extract_video_info(content_id)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/cbs.py", line 65, in _extract_video_info
    title = xpath_text(video_data, 'videoTitle', 'title', True)
  File "/usr/lib/python3.9/site-packages/youtube_dl/utils.py", line 1911, in xpath_text
    n = xpath_element(node, xpath, name, fatal=fatal, default=default)
  File "/usr/lib/python3.9/site-packages/youtube_dl/utils.py", line 1904, in xpath_element
    raise ExtractorError('Could not find XML element %s' % name)
youtube_dl.utils.ExtractorError: Could not find XML element title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

When trying to download from Paramount+, I get the "could not find XML element title" error message. I checked several episodes, including ones that were previously downloaded successfully, with the same result.

**Comment by Mr-Jake** [comment]
The "could not find XML element title" error means CBS added DRM to the video. First DRM was only applied to movies, then they added it to recently aired TV episodes, and now it seems they are slowly adding DRM to everything including the Nick shows.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30066

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30491
