### ISSUE TITLE
[ADN] Subtitles download support broken

### ISSUE THREAD

**Issue by Gaby13627** [ytdl-org/youtube-dl#29586]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '-f', 'best[height=1080]/best', '--all-subs', '--convert-subs', 'srt', '-v', 'https://animedigitalnetwork.fr/video/buso-renkin/537-episode-1-une-nouvelle-vie']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.1 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
[ADN] Logging in
[ADN] 537: Downloading player config JSON metadata
[ADN] 537: Downloading access token
[ADN] 537: Downloading links JSON metadata
[ADN] 537: Downloading vostf mobile JSON metadata
[ADN] 537: Downloading m3u8 information
[ADN] 537: Downloading vostf sd JSON metadata
[ADN] 537: Downloading m3u8 information
[ADN] 537: Downloading vostf auto JSON metadata
[ADN] 537: Downloading m3u8 information
[ADN] 537: Downloading additional video metadata
[ADN] 537: Downloading subtitles location
[ADN] 537: Downloading subtitles data
Traceback (most recent call last):
  File "C:\Users\gabri\Desktop\Nouveau dossier (30)\youtube_dl\__main__.py", line 19, in <module>
    youtube_dl.main()
  File "C:\Users\gabri\Desktop\Nouveau dossier (30)\youtube_dl\__init__.py", line 475, in main
    _real_main(argv)
  File "C:\Users\gabri\Desktop\Nouveau dossier (30)\youtube_dl\__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "C:\Users\gabri\Desktop\Nouveau dossier (30)\youtube_dl\YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "C:\Users\gabri\Desktop\Nouveau dossier (30)\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\gabri\Desktop\Nouveau dossier (30)\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\gabri\Desktop\Nouveau dossier (30)\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\gabri\Desktop\Nouveau dossier (30)\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\gabri\Desktop\Nouveau dossier (30)\youtube_dl\extractor\adn.py", line 260, in _real_extract
    'subtitles': self.extract_subtitles(sub_url, video_id),
  File "C:\Users\gabri\Desktop\Nouveau dossier (30)\youtube_dl\extractor\common.py", line 2968, in extract_subtitles
    return self._get_subtitles(*args, **kwargs)
  File "C:\Users\gabri\Desktop\Nouveau dossier (30)\youtube_dl\extractor\adn.py", line 96, in _get_subtitles
    dec_subtitles[:-compat_ord(dec_subtitles[-1])].decode(),
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 3: invalid continuation byte
```

## Description

Hello,

Since a few days it is impossible for me to download the subtitles from the ADN website. I changed the subtitle key every time it didn't work, as explained here [#12724 (comment)](https://github.com/ytdl-org/youtube-dl/issues/12724#issuecomment-481673353), and it worked fine.

But lately it doesn't seem to work anymore, I try to change the key and I always get the same one, so I can't download the subtitles anymore.

Does anyone have a solution to this problem?

Thank you for your help.

**Comment by SMods11** [comment]
Same problem here
