### ISSUE TITLE
AdultSwim 

### ISSUE THREAD

**Issue by peskin55** [ytdl-org/youtube-dl#29602]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

$ youtube-dl -F --console-title -v "https://www.adultswim.com/videos/rick-and-morty/amortycan-grickfitti"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '--console-title', '-v', 'https://www.adultswim.com/videos/rick-and-morty/amortycan-grickfitti']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.10.0b4 (CPython) - Linux-5.12.19-gentoo-dist-x86_64-Intel-R-_Core-TM-_i7-10750H_CPU_@_2.60GHz-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[AdultSwim] amortycan-grickfitti: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/youtube-dl", line 33, in <module>
    sys.exit(load_entry_point('youtube-dl==2021.6.6', 'console_scripts', 'youtube-dl')())
  File "/usr/lib/python3.10/site-packages/youtube_dl/__init__.py", line 475, in main
    _real_main(argv)
  File "/usr/lib/python3.10/site-packages/youtube_dl/__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/adultswim.py", line 131, in _real_extract
    video_data = show_data['getVideoBySlug']
TypeError: 'NoneType' object is not subscriptable

## Description

WRITE DESCRIPTION HERE

AdultSwim seemed to have changed their system.

**Comment by october262** [comment]
try logging in with your cable provider and then retry downloading the episode
using  the  cookies.txt file command.

**Comment by peskin55** [comment]
> try logging in with your cable provider and then retry downloading the episode
> using the cookies.txt file command.

It worked when on xfinitywifi (rather than home network). Must've blocked my ip.
