### ISSUE TITLE
TVE support broken

### ISSUE THREAD

**Issue by jEsuSdA** [ytdl-org/youtube-dl#29613]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v https://www.rtve.es/play/videos/masterchef/programa-12/5974958/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.rtve.es/play/videos/masterchef/programa-12/5974958/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.7.5 (CPython) - Linux-5.10.0-0.bpo.4-amd64-x86_64-with-debian-bullseye-sid
[debug] exe versions: ffmpeg 4.1.6, ffprobe 4.1.6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 5974958: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 5974958: Downloading webpage
[generic] 5974958: Extracting information
WARNING: [generic] 5974958: Failed to parse JSON Invalid control character at: line 13 column 474 (char 1019)
ERROR: Unsupported URL: https://www.rtve.es/play/videos/masterchef/programa-12/5974958/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/generic.py", line 3520, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.rtve.es/play/videos/masterchef/programa-12/5974958/

```

## Description

tve website has changed and youtube-dl is not capable of downloading streams now.

Thanks a lot! ;)

**Comment by dirkf** [comment]
See #29522.

**Comment by jEsuSdA** [comment]
> See #29522.

Thank you so much.
I could solve the problem making the changes at these link.
Thank you @dirfk ;)

**Comment by arturoherrero** [comment]
Possible fix https://github.com/ytdl-org/youtube-dl/pull/29816.

**Comment by manuhortet** [comment]
#29816 works for me. 
In the meantime, content is still exposed in the old urls, which work correctly. So to download, for example, `https://www.rtve.es/play/videos/imprescindibles/imprescindibles-roberto-bolano-ultimo-maldito/3861185/`, simply substitute `/play/` for `/alacarta/`.
