### ISSUE TITLE
Not working with linkedin learning now

### ISSUE THREAD

**Issue by ukreddy-erwin** [ytdl-org/youtube-dl#29637]
I tried with latest version as of data and getting below errors when the download is beginned.

```
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "c:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "c:\python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\python39\lib\site-packages\youtube_dl\extractor\linkedin.py", line 127, in _real_extract
    self._sort_formats(formats, ('width', 'height', 'source_preference', 'tbr', 'abr'))
  File "c:\python39\lib\site-packages\youtube_dl\extractor\common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

The command used:
youtube-dl --username "myaccount" --password "mypassword" --verbose --sleep-interval 120 "https://www.linkedin.com/learning/using-python-with-excel"

**Comment by Nico207** [comment]
Hi ! 
Try using this command :

> youtube-dl --cookies cookies.txt --sleep-interval 120 https://www.linkedin.com/learning/using-python-with-excel -o "/output/folder/%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.mp4" --write-sub --playlist-start 1

`--cookies cookies.txt` : **!!! Required** cookie from Linkedin. You can use [cookies.txt](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/) add-on for Firefox to get it (you must log in before)

`--sleep-interval 120` : wait 120 seconds between 2 videos.

`-o "/output/folder/%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.mp4"` : to get a good formatted output file name.

` --write-sub` : if you want subtitles (if present).

`--playlist-start 1` : very useful when you want to restart from  a particular video from the playlist.

**Comment by ukreddy-erwin** [comment]
Thank you @Nico207 it is working.
But there is a small problem, --playlist-start option is not working and it starts from first video again if any course failed during download and want to resume from there.
It is manageable at present as I am downloading from a remote machine where internet disconnection is rare.

Also, can you please suggest how to download a complete learning path.

**Comment by speedyjohnny** [comment]
I'm having the same problem. Can someone explain further the part about the cookies? Is this a file I need to download and place in the same directory as youtube-dl?  Is there an option for people who use linked-in on chrome-based browsers like Edge or Opera?
