### ISSUE TITLE
[nbcolympics:stream]

### ISSUE THREAD

**Issue by ProgrammerAKL** [ytdl-org/youtube-dl#29665]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe "https://stream.nbcolympics.com/golf-channel-210726-live-from-the-olympics" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://stream.nbcolympics.com/golf-channel-210726-live-from-the-olympics', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[nbcolympics:stream] golf-channel-210726-live-from-the-olympics: Downloading webpage
ERROR: Unable to extract resource; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\nbc.py", line 500, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract resource; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

extractor update clearly required, hopefully within a short time

**Comment by wesnm** [comment]
Try this patch. I don't have an MSO account to test further, but it seems like it should work.

```
--- nbc.py~     2021-05-16 10:59:22.000000000 -0500
+++ nbc.py      2021-07-28 10:54:37.409769000 -0500
@@ -495,9 +495,9 @@
         display_id = self._match_id(url)
         webpage = self._download_webpage(url, display_id)
         pid = self._search_regex(r'pid\s*=\s*(\d+);', webpage, 'pid')
-        resource = self._search_regex(
-            r"resource\s*=\s*'(.+)';", webpage,
-            'resource').replace("' + pid + '", pid)
+        #resource = self._search_regex(
+        #    r"resource\s*=\s*'(.+)';", webpage,
+        #    'resource').replace("' + pid + '", pid)
         event_config = self._download_json(
             self._DATA_URL_TEMPLATE % ('event_config', pid),
             pid)['eventConfig']
@@ -506,7 +506,7 @@
             self._DATA_URL_TEMPLATE % ('live_sources', pid),
             pid)['videoSources'][0]['sourceUrl']
         media_token = self._extract_mvpd_auth(
-            url, pid, event_config.get('requestorId', 'NBCOlympics'), resource)
+            url, pid, event_config.get('requestorId', 'NBCOlympics'), pid)
         formats = self._extract_m3u8_formats(self._download_webpage(
             'http://sp.auth.adobe.com/tvs/v1/sign', pid, query={
                 'cdn': 'akamai',


```

**Comment by nchilada** [comment]
@wesnm good guess, but it looks like the `resource` needs to be something different. I have a solution in #29688 which I think is finally ready to be used, though I haven't yet polished it and submitted it for review and merging.

It's interesting that youtube-dl has continued to work on [http://stream.nbcolympics.com/2018-winter-olympics-nbcsn-evening-feb-8](http://stream.nbcolympics.com/2018-winter-olympics-nbcsn-evening-feb-8), the current test case. That old stream doesn't render at all in my web browser(s), and conversely, youtube-dl has rejected all the current streams. I only noticed this when I stumbled across #596.

Speaking of which: thank you @wesnm for taking care of #596! I chose Sling TV myself and had just realized it was going to need a gnarly fix!
