### ISSUE TITLE
Unable to download Bitchute Playlist

### ISSUE THREAD

**Issue by BioBox** [ytdl-org/youtube-dl#29664]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
+ ~/vids/WORLD PEACE$ youtube-dl -v --yes-playlist -f 'best[ext=mp4]' -o './%(title)s.%(ext)s' "https://www.bitchute.com/playlist/9UsDwfa6PzoQ/"
[debug] System config: []
[debug] User config: ['-o', '%(title)s.%(ext)s', '-f', 'mp4']
[debug] Custom config: []
[debug] Command-line args: ['-v', '--yes-playlist', '-f', 'best[ext=mp4]', '-o', './%(title)s.%(ext)s', 'https://www.bitchute.com/playlist/9UsDwfa6PzoQ/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.6 (CPython) - Linux-5.10.49-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 9UsDwfa6PzoQ: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 9UsDwfa6PzoQ: Downloading webpage
[generic] 9UsDwfa6PzoQ: Extracting information
ERROR: Unsupported URL: https://www.bitchute.com/playlist/9UsDwfa6PzoQ/
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/generic.py", line 3520, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.bitchute.com/playlist/9UsDwfa6PzoQ/
```

## Description

The program gives me a "Unsupported URL" error when attempting to download a playlist from Bitchute. URLs of the form `https://www.bitchute.com/playlist/XXXXXXXXXX` will fail, but downloading individual videos from the playlist works fine. There really ought to be support for the `--yes-playlist` option so that we can download a playlist. Thanks in advance.

**Comment by kikuyan** [comment]
There's a PR #26725 (but seems to need a little fix).
