### ISSUE TITLE
ERROR: No video formats found

### ISSUE THREAD

**Issue by VirusIn0014** [ytdl-org/youtube-dl#29687]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/dispatcher.py", line 217, in handler_worker
    await handler.callback(self.client, *args)
  File "/app/handlers/play.py", line 507, in play
    file_path = await converter.convert(youtube.download(url))
  File "/app/downloaders/youtube.py", line 19, in download
    info = ydl.extract_info(url, False)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by kikuyan** [comment]
> Be sure to call youtube-dl with the --verbose flag and include its 
> **complete output**.

Do not ignore this.

**Comment by hessaum** [comment]
What was the original command you ran that provided this output?

**Comment by VirusIn0014** [comment]
> What was the original command you ran that provided this output?

dude ... i have a music bot ... i got this error in logs of that bot
