### ISSUE TITLE
Retrieve Failure

### ISSUE THREAD

**Issue by sfoxyz** [ytdl-org/youtube-dl#29720]
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
$ youtube-dl --verbose https://nypost.com/2021/01/08/trump-supporters-attack-associated-press-photographer-in-dc/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://nypost.com/2021/01/08/trump-supporters-attack-associated-press-photographer-in-dc/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.16 (CPython) - Linux-5.4.134-16092-g4da17551e2e8-x86_64-with-debian-10.10
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[generic] trump-supporters-attack-associated-press-photographer-in-dc: Requesting header
WARNING: Falling back on generic information extractor.
[generic] trump-supporters-attack-associated-press-photographer-in-dc: Downloading webpage
[generic] trump-supporters-attack-associated-press-photographer-in-dc: Extracting information
[Instagram] CJxKMArpN0_: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/instagram.py", line 240, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1130, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```


## Description

<!--
Provide an explanation of your issue in an arbitrary form. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

WRITE DESCRIPTION HERE
Failed to retrieve video that played in Chrome browser.

**Comment by kikuyan** [comment]
It's Instagram video and same as #28021
```
[Instagram] CJxKMArpN0_: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
No problem to me. 
```
$ youtube-dl --ignore-config https://nypost.com/2021/01/08/trump-supporters-attack-associated-press-photographer-in-dc/
[generic] trump-supporters-attack-associated-press-photographer-in-dc: Requesting header
WARNING: Falling back on generic information extractor.
[generic] trump-supporters-attack-associated-press-photographer-in-dc: Downloading webpage
[generic] trump-supporters-attack-associated-press-photographer-in-dc: Extracting information
[Instagram] CJxKMArpN0_: Downloading webpage
[download] Destination: AP @apnews photographer attacked-CJxKMArpN0_.mp4
[download]   4.3% of 43.84MiB at  2.30MiB/s ETA 00:18^C
```
