### ISSUE TITLE
Error while downloading Vimeo Staff Picks

### ISSUE THREAD

**Issue by 6if89** [ytdl-org/youtube-dl#29764]
Hi 
I'm trying to download all Vimeo Staff Picks videos but I get this error .
is this even possible?

[vimeo:channel] staffpicks: Downloading page 1257
[vimeo:channel] staffpicks: Downloading page 1258
[vimeo:channel] staffpicks: Downloading page 1259
[vimeo:channel] playlist Vimeo Staff Picks: Downloading 15099 videos
[download] Downloading video 1 of 15099
[vimeo] 585385587: Downloading webpage
ERROR: Unable to extract config URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\vimeo.py", line 683, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1021, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract config URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
Staff Picks are a Channel. The links to Channel videos are like `.../channels/channel_name/video_id`.

A different method of finding the program metadata is used for such URLs. If it doesn't work, the method(s) used for non-Channel videos ought to be tried.
