### ISSUE TITLE
ERROR downloading subtitles when there's a scheduled event

### ISSUE THREAD

**Issue by superbonaci** [ytdl-org/youtube-dl#29777]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v --write-auto-sub --convert-subs=srt --skip-download https://www.youtube.com/c/Wifistudy
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--write-auto-sub', '--convert-subs=srt', '--skip-download', 'https://www.youtube.com/c/Wifistudy']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-08-10-git-c245963a21-full_build-www.gyan.dev, ffprobe 2021-08-10-git-c245963a21-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube:tab] Wifistudy: Downloading webpage
[download] Downloading playlist: wifistudy - Home
[youtube:tab] playlist wifistudy - Home: Downloading 9 videos
[download] Downloading video 1 of 9
[youtube:tab] Wifistudy: Downloading webpage
[download] Downloading playlist: wifistudy - Videos
[youtube:tab] Downloading page 1
[youtube:tab] playlist wifistudy - Videos: Downloading 34 videos
[download] Downloading video 1 of 34
[youtube] F6kp6nwBo1U: Downloading webpage
ERROR: This live event will begin in 76 minutes.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1713, in _real_extract
```

## Description

Intent to download all subtitles from a channel. If there's any scheduled event it will break.

**Comment by dirkf** [comment]
Try `--ignore_errors`.

**Comment by superbonaci** [comment]
> 
> 
> Try `--ignore_errors`.

Thank you it worked, although it's `--ignore-errors`.
````
youtube-dl --ignore-errors --write-auto-sub --convert-subs=srt --skip-download https://www.youtube.com/c/Wifistudy
````
