### ISSUE TITLE
beeg broken

### ISSUE THREAD

**Issue by badproject** [ytdl-org/youtube-dl#29781]
youtube-dl -v "https://beeg.com/1039870776"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://beeg.com/1039870776']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-161-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: none
[debug] Proxy map: {}
[Beeg] 1039870776: Downloading webpage
[Beeg] 1039870776: Downloading JSON metadata
WARNING: [Beeg] 1039870776: Failed to parse JSON No JSON object could be decoded
[Beeg] 1039870776: Downloading JSON metadata
ERROR: 1039870776: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 906, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/beeg.py", line 74, in _real_extract
    fatal=api_path == 'api.', query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 899, in _download_json
    expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 883, in _download_json_handle
    fatal=fatal), urlh
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 910, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: 1039870776: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by kikuyan** [comment]
Open the link in the browser.

**Comment by dirkf** [comment]
This particular video is missing.

However there are clips from most of the video could be assembled listed in JSON at `'https://store.externulls.com/facts/file/%0.11d' % video_id`. The clip URLs have the path from the `resources` of each of the `fc_facts`, prefixed by `https://video.beeg.com`.

When a video is present, full video URLs can be found in the `resources` of the `file` object in the JSON.

Possibly the site has changed its API, as a similar video that does exist is not found by yt-dl, with a log like OP's.
