### ISSUE TITLE
ESPN+ UnicodeEncodeError

### ISSUE THREAD

**Issue by judgefudge34** [ytdl-org/youtube-dl#29815]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v --ignore-config -o %(title)s.%(ext)s --restrict-filenames --add-header "Authorization:eyJ6aXAiOiJERUYiLCJraWQiOiJNZHRlcVJ2R04yTDg3dW5OM2g5QzdReF9MUGNRdGN4VTZZNnk5UjF4eHBFIiwiY3R5IjoiSldUIiwiZW5jIjoiQzIwUCIsImFsZyI6ImRpciJ9..sz5MNJI6GkFO0BH7.gp_XPIV0sN3fywpx3eUtt16xcvgoU2CvpCZlPDHc87-tdjPlmvLcMiDS4wXUrlngpHZuZ9Glf4Ujh7qUeipv4gM7zvViS_mNhnBL1Lk0mOscadT3PrkknvneZHIrEb-W8zHKFyveUA6P2kpOt_YDa8vi-FAuXFSYzY6jH89VNTgwyXeE-2X6a-d3tGU2h7P-Td-n9BmTGaQkQTXrNCg_dPAhCB3Ng68jAhXjXZ_ezmxviCqh2vvv4sh1qbicXg6PNILXsKB67bcEaAlxO1W-nvNkhniALMJrmhj5QkEKqXZCM2Eu5qaTW6SysX8e7aAvYkUKAbsXRWb2ub4h6y6n3UskNCsiid-EyS8cY…Z0xbvKCGUehZOn0z-ZvVAjo_zeajTPHEmZIX2_0rPx69VhwnxtdzfYKzzzH21-gOScO90QobBw8rVNicqrAzwlegJ9Igmbg8rJXC45qIcDUWYuYoWrzCgrHKmkmTKGjHAIPcSLcdWyq69ZKlIqeU-D03Cq72crAdX-50ZOe1AEg3FUzxBOic373mmuSb4R8N8_elKmrcX7xOgUC7GRxWK2f8yFYN13eOpRC8OiJOqZf7ips-6N3b8txD85rKiIxmH7dRiJsXMU-7E2yVjVk35htUF0C8J0X9re02MknGcUggu0KDzQ3NmeYKhXPQShaiHvoosaIGGSLM5DIz0NF9LCbb_sftGATD5qa_q6ZSPQAkJhAPW3ZGqP9kHUK-fS6UAMO9BaPWPb75BbqOQh3fMWHXE6li0SiFj4-6EVRaDXcApAOCjOAtJZYvUklfJdxmW8qcT01FTn5dYk43wRJP2FzOcaMEOAD2r7uwKCeI.usMcPq3nVrAiFc71y_s-AQ" "https://hlsvod-akc-clt1.media.plus.espn.com/ps01/espn/hls/ecc0594b-6076-4fa8-9d17-6c37333d110f/r/7583794f-467b-406e-8083-1c0dd2521f74/43a1-MAIN/e375b3c9-f9f8-442f-8ead-328ab0b194eb/7000_complete.m3u8"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', '-o', '%(title)s.%(ext)s', '--restrict-filenames', '--add-header', 'Authorization:eyJ6aXAiOiJERUYiLCJraWQiOiJNZHRlcVJ2R04yTDg3dW5OM2g5QzdReF9MUGNRdGN4VTZZNnk5UjF4eHBFIiwiY3R5IjoiSldUIiwiZW5jIjoiQzIwUCIsImFsZyI6ImRpciJ9..sz5MNJI6GkFO0BH7.gp_XPIV0sN3fywpx3eUtt16xcvgoU2CvpCZlPDHc87-tdjPlmvLcMiDS4wXUrlngpHZuZ9Glf4Ujh7qUeipv4gM7zvViS_mNhnBL1Lk0mOscadT3PrkknvneZHIrEb-W8zHKFyveUA6P2kpOt_YDa8vi-FAuXFSYzY6jH89VNTgwyXeE-2X6a-d3tGU2h7P-Td-n9BmTGaQkQTXrNCg_dPAhCB3Ng68jAhXjXZ_ezmxviCqh2vvv4sh1qbicXg6PNILXsKB67bcEaAlxO1W-nvNkhniALMJrmhj5QkEKqXZCM2Eu5qaTW6SysX8e7aAvYkUKAbsXRWb2ub4h6y6n3UskNCsiid-EyS8cY…Z0xbvKCGUehZOn0z-ZvVAjo_zeajTPHEmZIX2_0rPx69VhwnxtdzfYKzzzH21-gOScO90QobBw8rVNicqrAzwlegJ9Igmbg8rJXC45qIcDUWYuYoWrzCgrHKmkmTKGjHAIPcSLcdWyq69ZKlIqeU-D03Cq72crAdX-50ZOe1AEg3FUzxBOic373mmuSb4R8N8_elKmrcX7xOgUC7GRxWK2f8yFYN13eOpRC8OiJOqZf7ips-6N3b8txD85rKiIxmH7dRiJsXMU-7E2yVjVk35htUF0C8J0X9re02MknGcUggu0KDzQ3NmeYKhXPQShaiHvoosaIGGSLM5DIz0NF9LCbb_sftGATD5qa_q6ZSPQAkJhAPW3ZGqP9kHUK-fS6UAMO9BaPWPb75BbqOQh3fMWHXE6li0SiFj4-6EVRaDXcApAOCjOAtJZYvUklfJdxmW8qcT01FTn5dYk43wRJP2FzOcaMEOAD2r7uwKCeI.usMcPq3nVrAiFc71y_s-AQ', 'https://hlsvod-akc-clt1.media.plus.espn.com/ps01/espn/hls/ecc0594b-6076-4fa8-9d17-6c37333d110f/r/7583794f-467b-406e-8083-1c0dd2521f74/43a1-MAIN/e375b3c9-f9f8-442f-8ead-328ab0b194eb/7000_complete.m3u8']
[debug] Adding header from command line option Authorization:eyJ6aXAiOiJERUYiLCJraWQiOiJNZHRlcVJ2R04yTDg3dW5OM2g5QzdReF9MUGNRdGN4VTZZNnk5UjF4eHBFIiwiY3R5IjoiSldUIiwiZW5jIjoiQzIwUCIsImFsZyI6ImRpciJ9..sz5MNJI6GkFO0BH7.gp_XPIV0sN3fywpx3eUtt16xcvgoU2CvpCZlPDHc87-tdjPlmvLcMiDS4wXUrlngpHZuZ9Glf4Ujh7qUeipv4gM7zvViS_mNhnBL1Lk0mOscadT3PrkknvneZHIrEb-W8zHKFyveUA6P2kpOt_YDa8vi-FAuXFSYzY6jH89VNTgwyXeE-2X6a-d3tGU2h7P-Td-n9BmTGaQkQTXrNCg_dPAhCB3Ng68jAhXjXZ_ezmxviCqh2vvv4sh1qbicXg6PNILXsKB67bcEaAlxO1W-nvNkhniALMJrmhj5QkEKqXZCM2Eu5qaTW6SysX8e7aAvYkUKAbsXRWb2ub4h6y6n3UskNCsiid-EyS8cY…Z0xbvKCGUehZOn0z-ZvVAjo_zeajTPHEmZIX2_0rPx69VhwnxtdzfYKzzzH21-gOScO90QobBw8rVNicqrAzwlegJ9Igmbg8rJXC45qIcDUWYuYoWrzCgrHKmkmTKGjHAIPcSLcdWyq69ZKlIqeU-D03Cq72crAdX-50ZOe1AEg3FUzxBOic373mmuSb4R8N8_elKmrcX7xOgUC7GRxWK2f8yFYN13eOpRC8OiJOqZf7ips-6N3b8txD85rKiIxmH7dRiJsXMU-7E2yVjVk35htUF0C8J0X9re02MknGcUggu0KDzQ3NmeYKhXPQShaiHvoosaIGGSLM5DIz0NF9LCbb_sftGATD5qa_q6ZSPQAkJhAPW3ZGqP9kHUK-fS6UAMO9BaPWPb75BbqOQh3fMWHXE6li0SiFj4-6EVRaDXcApAOCjOAtJZYvUklfJdxmW8qcT01FTn5dYk43wRJP2FzOcaMEOAD2r7uwKCeI.usMcPq3nVrAiFc71y_s-AQ
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-05-23-git-4c0d6c91f6-full_build-www.gyan.dev, ffprobe 2021-05-23-git-4c0d6c91f6-full_build-www.gyan.dev
[debug] Proxy map: {}
[generic] 7000_complete: Requesting header
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\__init__.py", line 465, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2069, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\generic.py", line 2411, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\utils.py", line 2737, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1177, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1109, in putheader
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 512: ordinal not in range(256)
```

## Description

I'm having an issue downloading a 30 for 30 video on ESPN+. From what I've gathered the encoding error is an issue with Python. I assume the title uses a latin character. I've found various resolutions and error threads about this error in Python and other programs, but not for youtube-dl and nothing on how to implement a fix in youtube-dl.

I've followed the method for downloading ESPN+ videos from these threads: 
https://github.com/ytdl-org/youtube-dl/issues/16359
https://www.reddit.com/r/youtubedl/comments/owsiay/tips_on_getting_espn_to_work_with_youtubedl/

**Comment by dirkf** [comment]
Your `Authorization` header contains a Unicode HORIZONTAL ELLIPSIS character, which headers aren't meant to have. Possibly it was inserted by whatever program displayed the header that you cut-and pasted, because the header value is so long?

It might be a defect that yt-dl fails to warn if manually added headers contain invalid (according to the RFCs) characters. Instead you get the error as shown in your log.

**Comment by judgefudge34** [comment]
I needed to select "raw" for the request headers in Firefox to get the full string, but now I am having another issue. Thanks
