### ISSUE TITLE
Please add support for https://play.tv2.dk/

### ISSUE THREAD

**Issue by Porkeld** [ytdl-org/youtube-dl#29830]
## Checklist

- [ ] I'm reporting a new site support request
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that none of provided URLs violate any copyrights
- [ ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

## Description

WRITE DESCRIPTION HERE

Please add support for https://play.tv2.dk/

H:\YoutubeDL>youtube-dl.exe --verbose -u, --username stivan@youmail.dk -p, --password Sille2sen https://play.tv2.dk/programmer/serier/komedie/minkavlerne/momsfri-mandag-243931
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-u,', '--username', 'PRIVATE', '-p,', '--password', 'PRIVATE', 'https://play.tv2.dk/programmer/serier/komedie/minkavlerne/momsfri-mandag-243931']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.21390
[debug] exe versions: none
[debug] Proxy map: {}
[generic] momsfri-mandag-243931: Requesting header
WARNING: Falling back on generic information extractor.
[generic] momsfri-mandag-243931: Downloading webpage
[generic] momsfri-mandag-243931: Extracting information
ERROR: Unsupported URL: https://play.tv2.dk/programmer/serier/komedie/minkavlerne/momsfri-mandag-243931
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\generic.py", line 3520, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://play.tv2.dk/programmer/serier/komedie/minkavlerne/momsfri-mandag-243931

**Comment by tozedascoves** [comment]
@Porkeld please edit your issue and remove your login credentials.

**Comment by Foxite** [comment]
Even if they remove it, the old revision will still be there; this issue should be deleted entirely by a maintainer or someone else with the right permissions. In the worst case OP might have to contact Github to get it done. OP can re-create it then.

@Porkeld , change your password if you haven't done so already.
