### ISSUE TITLE
youtube-dl refuse to give real direct stream link, reports unavailable, but downloads it without problems

### ISSUE THREAD

**Issue by TCH68k** [ytdl-org/youtube-dl#29832]
- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.06.06**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

Trying to get the direct stream URL (fails, reports it as unavailable):
```
# youtube-dl -v --format 244 --skip-download --youtube-skip-dash-manifest --get-url https://youtube.com/watch?v=gcFM3QdZe5w
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--format', u'244', u'--skip-download', u'--youtube-skip-dash-manifest', u'--get-url', u'https://youtube.com/watch?v=gcFM3QdZe5w']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-16-amd64-x86_64-with-debian-9
[debug] exe versions: avconv 4.2.2, avprobe 4.2.2, ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 847, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 881, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1684, in process_video_result
    expected=True)
ExtractorError: requested format not available
```

Trying to download the video (works perfectly):
```
# youtube-dl -v --format 244 https://youtube.com/watch?v=gcFM3QdZe5w
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--format', u'244', u'https://youtube.com/watch?v=gcFM3QdZe5w']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-16-amd64-x86_64-with-debian-9
[debug] exe versions: avconv 4.2.2, avprobe 4.2.2, ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] gcFM3QdZe5w: Downloading webpage
[youtube] gcFM3QdZe5w: Downloading MPD manifest
[debug] Invoking downloader on u'https://manifest.googlevideo.com/api/manifest/dash/expire/1629497432/ei/-NMfYe_8BYyP-gavqKzYBg/ip/178.164.222.226/id/81c14cdd07597b9c/source/youtube/requiressl/yes/playback_host/r2---sn-qpbpu8-c0ql.googlevideo.com/mh/fk/mm/31%2C29/mn/sn-qpbpu8-c0ql%2Csn-c0q7lnse/ms/au%2Crdu/mv/m/mvi/2/pl/24/tx/24027704/txs/24027703%2C24027704%2C24027705%2C24027706/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1155000/vprv/1/mt/1629475493/fvip/2/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRAIgQfFxdRi5tiiga09VArHKejInt1HpE5ImzMHDeAh6Ha4CIEC1Rn5nEqrutjh3uMc7a6Z9leQLlJxaT3MWpbHsYxPp/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRAIgaNt0E2gyYqn7Wl9uWd-7JWtF2kjelZ26_fA61ijf-mgCIF9G4y1to7oe2CqCI83rmIqMEVvBBz_RXz4Z8gexkDlq'
[dashsegments] Total fragments: 107
[download] Destination: Nu Pogodi 17 vypusk iz 20 1993 XviD DVDRip-gcFM3QdZe5w.webm
[download] 100% of 36.73MiB in 00:08
```

Trying to get the direct URL without `youtube-skip-dash-manifest` (fails, gives back a link which is not the direct stream's link):
```
# youtube-dl -v --format 244 --skip-download --get-url https://youtube.com/watch?v=gcFM3QdZe5w
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--format', u'244', u'--skip-download', u'--get-url', u'https://youtube.com/watch?v=gcFM3QdZe5w']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-16-amd64-x86_64-with-debian-9
[debug] exe versions: avconv 4.2.2, avprobe 4.2.2, ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
https://manifest.googlevideo.com/api/manifest/dash/expire/1629497409/ei/4dMfYaCeK4bFgAfC8byICw/ip/178.164.222.226/id/81c14cdd07597b9c/source/youtube/requiressl/yes/playback_host/r2---sn-qpbpu8-c0ql.googlevideo.com/mh/fk/mm/31%2C29/mn/sn-qpbpu8-c0ql%2Csn-c0q7lnse/ms/au%2Crdu/mv/m/mvi/2/pl/24/tx/24070733/txs/24070731%2C24070732%2C24070733%2C24070734%2C24070735%2C24070736%2C24070737%2C24070738/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1155000/vprv/1/mt/1629475493/fvip/2/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRAIgKxwcQTJHbhqwRJo1bj2fLKbMcbaZW3FWXIvgWVHzRicCIEPfLeco3YBCuXcNgAMaO1K3K26kTz778I_xhx81LOAl/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIgTtasoBEhWbg7dUM4COxwIDfdRRIds8go9BJImoaEPd4CIQC_ZZt6CJ2D7yKza9m4xpfplUqZ-zEnK4WPCcCVxBWYZw%3D%3D
```

## Description

I am trying to get the direct stream link of a video. If i try to get it by this:
```
youtube-dl -v --format 244 --skip-download --youtube-skip-dash-manifest --get-url https://youtube.com/watch?v=gcFM3QdZe5w
```
Then it reports the video is unavailable. If i try the same without `youtube-skip-dash-manifest`:
```
youtube-dl -v --format 244 --skip-download --get-url https://youtube.com/watch?v=gcFM3QdZe5w
```
Then it gives back a manifest link, not the direct stream link. If i try to download the video:
```
youtube-dl -v --format 244 https://youtube.com/watch?v=gcFM3QdZe5w
```
Then it downloads the video. If it is unavailable, how can it download it? If it is available, then why i cannot get the direct link?

Also, `mpv` can play it without problems:
```
mpv https://youtube.com/watch?v=gcFM3QdZe5w --ytdl-format=244
```

**Comment by coletdjnz** [comment]
I'm pretty sure the "non-manifest" link doesn't exist for that format* (well, it does, but it doesn't work hence why youtube-dl skips it and opts for the manifest one).

*for this video at least. Some other videos may have the same format code but it will be non-manifest.

(someone correct me if I'm wrong, it has been a while since I looked at this.)

**Comment by TCH68k** [comment]
Impossible. There must be a direct link to the stream or else neither `youtube-dl` could download it, nor `mpv` play it.

**Comment by coletdjnz** [comment]
> Impossible. There must be a direct link to the stream or else neither `youtube-dl` could download it, nor `mpv` play it.

because youtube-dl is downloading using the link provided in the manifest (the one it gives you)? If you run with --verbose you can see what url the downloader is using.

**Comment by TCH68k** [comment]
I've checked the manifest link and took the corresponding format's (`Representation`'s) `BaseURL` (here it is: `https://r2---sn-qpbpu8-c0ql.googlevideo.com/videoplayback/expire/1629561536/ei/YM4gYcOdOInlgAe_hYmQBA/ip/178.164.205.77/id/81c14cdd07597b9c/itag/244/source/yt_otf/requiressl/yes/mh/fk/mm/31,29/mn/sn-qpbpu8-c0ql,sn-c0q7lnse/ms/au,rdu/mv/m/mvi/2/pl/24/initcwndbps/1163750/vprv/1/ratebypass/yes/mime/video%2Fwebm/otfp/1/otf/1/lmt/1594612822775490/mt/1629539570/fvip/2/keepalive/yes/fexp/24001373,24007246/sparams/expire,ei,ip,id,itag,source,requiressl,vprv,ratebypass,mime,otfp,otf,lmt/sig/AOq0QJ8wRQIhAJquWIamxH1slsQWtMDPGt6tto5wCpkudy7zKb9Va39kAiAdwGVidxw-gkZQr1CIFdDXKC_KiPsFIUM9NSetQm_F0g%3D%3D/lsparams/mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRgIhAOYlJBXQiVMXcqA2O6CxLCYLT89bisf3HsMT1NoeC76UAiEAncu87xyinfruddDoJtuOMpqZabG3yN1KsRd5OYMPi5s%3D/`) and it gives back a 404. I've ran `youtube-dl` with `--verbose` as you can see in the logs, but even at the download, it has shown the manifest URL.

What i would like to get is the direct stream URL. There must be a way to obtain it, or else it would not be possible to play or download the stream.

**Comment by MinePlayersPE** [comment]
Direct URL from adaptiveFormats is skipped due to https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1623

**Comment by MinePlayersPE** [comment]
I'm guessing the reason youtube-dl won't give a non-manifest link is that you'll have to figure out the sequences from the manifest either way (i.e:
```
https://r2---sn-qpbpu8-c0ql.googlevideo.com/videoplayback/expire/1629561536/ei/YM4gYcOdOInlgAe_hYmQBA/ip/178.164.205.77/id/81c14cdd07597b9c/itag/244/source/yt_otf/requiressl/yes/mh/fk/mm/31,29/mn/sn-qpbpu8-c0ql,sn-c0q7lnse/ms/au,rdu/mv/m/mvi/2/pl/24/initcwndbps/1163750/vprv/1/ratebypass/yes/mime/video%2Fwebm/otfp/1/otf/1/lmt/1594612822775490/mt/1629539570/fvip/2/keepalive/yes/fexp/24001373,24007246/sparams/expire,ei,ip,id,itag,source,requiressl,vprv,ratebypass,mime,otfp,otf,lmt/sig/AOq0QJ8wRQIhAJquWIamxH1slsQWtMDPGt6tto5wCpkudy7zKb9Va39kAiAdwGVidxw-gkZQr1CIFdDXKC_KiPsFIUM9NSetQm_F0g%3D%3D/lsparams/mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRgIhAOYlJBXQiVMXcqA2O6CxLCYLT89bisf3HsMT1NoeC76UAiEAncu87xyinfruddDoJtuOMpqZabG3yN1KsRd5OYMPi5s%3D/sq/0
https://r2---sn-qpbpu8-c0ql.googlevideo.com/videoplayback/expire/1629561536/ei/YM4gYcOdOInlgAe_hYmQBA/ip/178.164.205.77/id/81c14cdd07597b9c/itag/244/source/yt_otf/requiressl/yes/mh/fk/mm/31,29/mn/sn-qpbpu8-c0ql,sn-c0q7lnse/ms/au,rdu/mv/m/mvi/2/pl/24/initcwndbps/1163750/vprv/1/ratebypass/yes/mime/video%2Fwebm/otfp/1/otf/1/lmt/1594612822775490/mt/1629539570/fvip/2/keepalive/yes/fexp/24001373,24007246/sparams/expire,ei,ip,id,itag,source,requiressl,vprv,ratebypass,mime,otfp,otf,lmt/sig/AOq0QJ8wRQIhAJquWIamxH1slsQWtMDPGt6tto5wCpkudy7zKb9Va39kAiAdwGVidxw-gkZQr1CIFdDXKC_KiPsFIUM9NSetQm_F0g%3D%3D/lsparams/mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRgIhAOYlJBXQiVMXcqA2O6CxLCYLT89bisf3HsMT1NoeC76UAiEAncu87xyinfruddDoJtuOMpqZabG3yN1KsRd5OYMPi5s%3D/sq/1/dur/6.400
...
https://r2---sn-qpbpu8-c0ql.googlevideo.com/videoplayback/expire/1629561536/ei/YM4gYcOdOInlgAe_hYmQBA/ip/178.164.205.77/id/81c14cdd07597b9c/itag/244/source/yt_otf/requiressl/yes/mh/fk/mm/31,29/mn/sn-qpbpu8-c0ql,sn-c0q7lnse/ms/au,rdu/mv/m/mvi/2/pl/24/initcwndbps/1163750/vprv/1/ratebypass/yes/mime/video%2Fwebm/otfp/1/otf/1/lmt/1594612822775490/mt/1629539570/fvip/2/keepalive/yes/fexp/24001373,24007246/sparams/expire,ei,ip,id,itag,source,requiressl,vprv,ratebypass,mime,otfp,otf,lmt/sig/AOq0QJ8wRQIhAJquWIamxH1slsQWtMDPGt6tto5wCpkudy7zKb9Va39kAiAdwGVidxw-gkZQr1CIFdDXKC_KiPsFIUM9NSetQm_F0g%3D%3D/lsparams/mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRgIhAOYlJBXQiVMXcqA2O6CxLCYLT89bisf3HsMT1NoeC76UAiEAncu87xyinfruddDoJtuOMpqZabG3yN1KsRd5OYMPi5s%3D/sq/8/dur/5.800
```
and so on...

**Comment by pukkandan** [comment]
@colethedj is correct

```
$ youtube-dl gcFM3QdZe5w -F --youtube-skip-dash
[youtube] gcFM3QdZe5w: Downloading webpage
[info] Available formats for gcFM3QdZe5w:
format code  extension  resolution note
251          webm       audio only tiny  116k , webm_dash container, opus @116k (48000Hz), 9.16MiB
140          m4a        audio only tiny  127k , m4a_dash container, mp4a.40.2@127k (44100Hz), 9.96MiB
134          mp4        480x360    360p  393k , mp4_dash container, avc1.4d4015@ 393k, 25fps, video only, 30.81MiB
18           mp4        480x360    360p  579k , avc1.42001E, 25fps, mp4a.40.2 (44100Hz), 45.44MiB (best)

$ youtube-dl gcFM3QdZe5w -F
[youtube] gcFM3QdZe5w: Downloading webpage
[youtube] gcFM3QdZe5w: Downloading MPD manifest
[info] Available formats for gcFM3QdZe5w:
format code  extension  resolution note
139          m4a        audio only DASH audio   51k , m4a_dash container, mp4a.40.5 (22050Hz), 3.74MiB
251          webm       audio only tiny  116k , webm_dash container, opus @116k (48000Hz), 9.16MiB
140          m4a        audio only tiny  127k , m4a_dash container, mp4a.40.2@127k (44100Hz), 9.96MiB
278          webm       192x144    DASH video   95k , webm_dash container, vp9, 25fps, video only
160          mp4        192x144    DASH video  108k , mp4_dash container, avc1.4d400b, 25fps, video only
242          webm       320x240    DASH video  220k , webm_dash container, vp9, 25fps, video only
133          mp4        320x240    DASH video  242k , mp4_dash container, avc1.4d400c, 25fps, video only
134          mp4        480x360    360p  393k , mp4_dash container, avc1.4d4015@ 393k, 25fps, video only, 30.81MiB
243          webm       480x360    DASH video  405k , webm_dash container, vp9, 25fps, video only
244          webm       640x480    DASH video  752k , webm_dash container, vp9, 25fps, video only
135          mp4        640x480    DASH video 1155k , mp4_dash container, avc1.4d4014, 25fps, video only
18           mp4        480x360    360p  579k , avc1.42001E, 25fps, mp4a.40.2 (44100Hz), 45.44MiB (best)
```

The `244` format is only available in dash manifest and doesn't have a direct URL that youtube-dl can download. The format does actually has a direct URL, but as @MinePlayersPE said it is intentionally skipped since youtube-dl cannot download from it

> Impossible. There must be a direct link to the stream or else neither youtube-dl could download it, nor mpv play it.

No, youtube-dl can download videos from dash manifest, no direct URL needed

**Comment by TCH68k** [comment]
@MinePlayersPE:
You're right, i've put the segment texts after the base URL and managed to download them each by each. After concatenating, the video is working. Thanks.
I think there should be an option to get the URL list by this logic.

@pukkandan:
`mpv` is somehow able to get these URL-s from `youtube-dl`. Or it is just concatenating the content from the URL-s?

**Comment by pukkandan** [comment]
Look at the `-j` output. You can see `fragments` and `fragment_base_url` which together can be used to get all the fragment URLs

**Comment by TCH68k** [comment]
Okay, but how can i make a single string from them which can be passed to `mpv`? Can `youtube-dl` output an "EDL URL" out of them? If i use
```
mpv https://youtube.com/watch?v=gcFM3QdZe5w --ytdl-format=244
```
And extract the stream path by adding
```
ctrl+r run "/bin/sh" "-c" "echo \"${stream-path}\" | xsel -b -i"
```
to `input.conf` and then copy the string, it is an "EDL URL" with all the segments in a single string. How can `youtube-dl` output this link? Or this link was made by `mpv` itself?

**Comment by TCH68k** [comment]
I've managed to come up with this shell/javascript script (nodejs needed for JSON parsing):
http://oscomp.hu/depot/get_edl.sh
If i do
```
./get_edl.sh https://youtube.com/watch?v=gcFM3QdZe5w 244
```
it prints out the EDL list, although the separator numbers between the % signs are erroneous as i have no idea what should be there and i found no info about it.

**Comment by TCH68k** [comment]
Okay, i've got a sudden idea and tried it out and it worked: those numbers are the length of the base url plus the path together.
So, it is possible to make an URL which can be used directly for streaming.
