### ISSUE TITLE
abc iview is not working (August 2021)

### ISSUE THREAD

**Issue by GeneralMidi** [ytdl-org/youtube-dl#29848]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

08/23/21 18:46:06] [debug] System config: []
[08/23/21 18:46:06] [debug] User config: []
[08/23/21 18:46:06] [debug] Custom config: []
[08/23/21 18:46:06] [debug] Command-line args: ['--newline', '-i', '-o', 'C:\\Users\\Luke\\Desktop\\%(title)s.%(ext)s', '-f', 'webm', '-v', '--ignore-config', '--hls-prefer-native', 'https://iview.abc.net.au/video/ZW1343A026S00']
[08/23/21 18:46:06] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[08/23/21 18:46:06] [debug] youtube-dl version 2021.06.06
[08/23/21 18:46:06] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[08/23/21 18:46:06] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[08/23/21 18:46:06] [debug] Proxy map: {}
[08/23/21 18:46:06] ERROR: Unable to download webpage: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[08/23/21 18:46:06]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
[08/23/21 18:46:06]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
[08/23/21 18:46:06]   File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
[08/23/21 18:46:06]   File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
[08/23/21 18:46:06]   File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
[08/23/21 18:46:06]   File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
[08/23/21 18:46:06]   File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
[08/23/21 18:46:06] 

################################################################

This url does not work

youtube-dl "https://iview.abc.net.au/video/ZW1343A026S00"

I'm connected via vpn. Date/time on my machine changed to match vpn. Video plays on browser. ffmpeg installed. Error seems to be

ERROR: Unable to download webpage: HTTP Error 401: Unauthorized (caused by HTTPError())

**Comment by dirkf** [comment]
You ticked this
> I've checked that all provided URLs are alive and playable in a browser

Is that really so? I guess that the site is blocking you based on VPN IP.

Unless you need the VPN to get to the real Internet, you could try going directly, but then I get this:
```
$ youtube-dl -v -F 'https://iview.abc.net.au/show/wallykazam/series/0/video/ZW1343A026S00'
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://iview.abc.net.au/show/wallykazam/series/0/video/ZW1343A026S00']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[debug] Using fake IP 1.140.194.49 (AU) as X-Forwarded-For.
[abc.net.au:iview] ZW1343A026S00: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('playlist',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/abc.py", line 135, in _real_extract
    stream = next(s for s in video_params['playlist'] if s.get('type') in ('program', 'livestream'))
KeyError: 'playlist'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/abc.py", line 135, in _real_extract
    stream = next(s for s in video_params['playlist'] if s.get('type') in ('program', 'livestream'))
KeyError: 'playlist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 547, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('playlist',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$
```

**Comment by GeneralMidi** [comment]
> Is that really so?

yes, it is really so.

**Comment by section83** [comment]
Both URLs work inside Australia.  So, it really looks like geo-blocking or a temporary glitch on the iView site.

**Comment by GeneralMidi** [comment]
But it works in the browser! Is this normal that iview can determine if
youtube-dl is pulling the stream, or a browser? I really don't get it...

**Comment by section83** [comment]
Try removing "--hls-prefer-native'" from your command line.  For me, YTDL says:

> WARNING: hlsnative has detected features it does not support, extraction will be delegated to ffmpeg

**Comment by dirkf** [comment]
`--hls-prefer-native` wouldn'r cause OP's issue which is not being able to download the page to extract the media URL(s) and metadata.

The site might need some cookie or `Referer` header in the request that is sent by the browser but not by the `abc.net.au:iview` extractor. However this doesn't match what I see, which is of limited use as I'm not using an Oz IP and the site doesn't believe `X-Forwarded-For:`.

The extractor gets metadata JSON from 'https://iview.abc.net.au/api/programs/_VIDEO_ID_'. This works for me, but indicates out-of-region error by omitting the `playlist` member and including a `statusMessage` promoting ABC's iview app for some shows available 'outside Australia'. An `episodeCount` is sent, but `episodeCount: 10` is weird unless the number is base 5 (episode number) or 13 (number of episodes). The absence of `playlist` isn't trapped as an expected extractor error (which would be a possible improvement) and causes the backtrace I posted earlier.

The browser gets metadata JSON from 'https://api.iview.abc.net.au/api/v2/video/_VIDEO_ID_'. This works for me, with no cookie, `Referer` or `Origin` header, but indicates out-of-region error with `playable: false` and `unavailableMessage: 'Video unavailable outside Australia ...'`. The metadata is more extensive than the previous API but doesn't send the `episodeCount` member.

Might OP's browser have some add-on that routes via another VPN unblocked by ABC?

**Comment by GeneralMidi** [comment]
Thanks for all your help everyone!

I don't connect to any other vpn services via browser add-ons etc. If it's
of any use, I'm using pia as the vpn provider and Firefox as the browser. I
will try later on on Chrome and Opera and report back.

**Comment by GeneralMidi** [comment]
> Might OP's browser have some add-on that routes via another VPN unblocked by ABC?

checked. Definitely not. Works in Chrome and Edge too. No add-ons whatsoever.

**Comment by section83** [comment]
Apologies for not understanding the issue.  In case it helps I've attached a copy of the verbose response from YTDL in downloading the video OP trying to get.  I did this from the command line (i.e. Terminal in macOS). No cookies, VPN or anything between YTDL and iView.

[The Chickephant's Getting Married-ZW1343A026S00.txt](https://github.com/ytdl-org/youtube-dl/files/7042569/The.Chickephant.s.Getting.Married-ZW1343A026S00.txt)

Downloaded file has AAC and H.264 codecs; resolution 1024x576.  Good luck.

**Comment by GeneralMidi** [comment]
Thanks so much. I take it you're in Australia?

I hope your efforts will assist someone here to find the issue. I really am
clueless.

**Comment by dirkf** [comment]
If OP has a utility like [wget](https://eternallybored.org/misc/wget/) or [curl](https://curl.se/windows/) it would be intreresting to see what happens when retrieving the URL https://iview.abc.net.au/api/programs/ZW1343A026S00 using that utility from the same command-line where yt-dl appears to fail.

```
wget -S -O ZW1343A026S00.json "https://iview.abc.net.au/api/programs/ZW1343A026S00"
```
or
```
curl -L -v -o ZW1343A026S00.json "https://iview.abc.net.au/api/programs/ZW1343A026S00"
```

**Comment by GeneralMidi** [comment]
I'll try this later on and let you know!

**Comment by GeneralMidi** [comment]
any thoughts?

**Comment by commentator8** [comment]
Just came across this - I was trying to access the play school section of the site and encountered the same issue. I am using Windscribe as my VPN. When i changed from using the Adelaide proxy to the "Good Koala" proxy it worked. So it is possible that the specific proxy IP is blocked and it would be worth it checking another. Best of luck!

**Comment by dirkf** [comment]
@GeneralMidi, apologies for losing track of this issue. Do you still have the problem?
