### ISSUE TITLE
Beeg plugin is broken after site update

### ISSUE THREAD

**Issue by campones** [ytdl-org/youtube-dl#29850]
ps: I know that server is old but happened the same on newer platforms.

youtube-dl -vvv https://beeg.com/-01859901571
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vvv', u'https://beeg.com/-01859901571']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.6 (CPython) - Linux-3.13.0-170-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-76159-gda43e9e, ffprobe N-76159-gda43e9e, rtmpdump 2.4
[debug] Proxy map: {}
[generic] -01859901571: Requesting header
WARNING: Falling back on generic information extractor.
[generic] -01859901571: Downloading webpage
[generic] -01859901571: Extracting information
ERROR: Unsupported URL: https://beeg.com/-01859901571
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2503, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2571, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2560, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 7, column 31
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 3520, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://beeg.com/-01859901571

**Comment by dirkf** [comment]
See #29781. 

A PR should appear to fix this, as my development version handles this URL (with the `-` removed). If links are being made with the `-` as above, presumably that format should also be supported.
