### ISSUE TITLE
newgrounds.com unable to extract.

### ISSUE THREAD

**Issue by zimakkkk** [ytdl-org/youtube-dl#29858]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.newgrounds.com/portal/view/810848', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.6 (CPython) - Windows-10-10.0.19043-SP0
[debug] exe versions: phantomjs 2.1.1
[debug] Proxy map: {}
[Newgrounds] 810848: Downloading webpage
ERROR: Unable to extract ; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\amak1\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\amak1\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\amak1\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\users\amak1\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\newgrounds.py", line 64, in _real_extract
    media_url = self._parse_json(self._search_regex(
  File "c:\users\amak1\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract ; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

i opened another one of these 7 months ago and its still broken. maybe i'm doing it wrong? i tried downloading multiple links but none worked.

**Comment by kikuyan** [comment]
There's a PR #29325.
