### ISSUE TITLE
ERROR: Unsupported URL (waklov.com)

### ISSUE THREAD

**Issue by raph2705** [ytdl-org/youtube-dl#29856]
Hello, I'm reporting a new site support request, [youtube-dl](https://github.com/ytdl-org/youtube-dl) is currently unable to handle videos on [waklov.com](http://waklov.com):
- [X] I'm running youtube-dl version 2021.06.06 on Debian, kernel &#35; 1 SMP Debian 5.10.46-4 (2021-08-03);
- [X] The provided URL is live and playable in a browser, no authentication needed;
- [X] No similar bug found for this website, including closed ones;

I'm not familiar with the project, but I assume it could be fixed either by extending the generic information extractor, or by adding a specific information extractor as a plugin. Here is the output of `--dump-pages`: [logs.txt](https://github.com/ytdl-org/youtube-dl/files/7039993/logs.txt).

```
$ youtube-dl -v 'http://waklov.com/xl3k3rw/b/waklov/458976375'                             
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://waklov.com/xl3k3rw/b/waklov/458976375']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-8-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 458976375: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 458976375: Downloading webpage
[generic] 458976375: Extracting information
ERROR: Unsupported URL: http://waklov.com/xl3k3rw/b/waklov/458976375
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/generic.py", line 3520, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://waklov.com/xl3k3rw/b/waklov/458976375
```

**Comment by dirkf** [comment]
In this example, the video is in an `<iframe>` and if you change the `a.php` in its `src` attribute to `d.php` (which happens when you cliques ici pour afficher le lecteur) you then have the document in which the video is placed as a standard `<video>` element with M3U8 `<src>` (for which yt-dl has a library extraction routine).

If that's repeatable, it looks like a very good 'My First YT-DL Extractor' project.

**Comment by raph2705** [comment]
Thank you very much for your input @dirkf, I'll give it a try when I'm done with my current engagement.
