### ISSUE TITLE
Dailymotion abrupt 404

### ISSUE THREAD

**Issue by attinderdhillon** [ytdl-org/youtube-dl#29867]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.06.06**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
youtube-dl https://www.dailymotion.com/video/x2kxdqm -f best --verbose
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.dailymotion.com/video/x2kxdqm', '-f', 'best', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.6 (CPython) - Linux-5.13.9-200.fc34.x86_64-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[dailymotion] Downloading Access Token
[dailymotion] x2kxdqm: Downloading media JSON metadata
[dailymotion] x2kxdqm: Downloading metadata JSON
[dailymotion] x2kxdqm: Downloading m3u8 information
[debug] Invoking downloader on 'https://proxy-033.ix7.dailymotion.com/sec(TKCcVu7iYSGl26pWZ5hLrDOpeUuCwx0CZ-BO2JvAqk74w167ldzGxMNU5KuQtbdz71NLGoF_jr7APquz2lbrqg)/video/621/280/156082126_mp4_h264_aac_hq.mp4'
[download] Destination: GP1 Season Review 1990-001-x2kxdqm.mp4
[download]  38.0% of 315.47MiB at 125.17KiB/s ETA 26:39[download] Got server HTTP error: Downloaded 125829120 bytes, expected 330789408 bytes. Retrying (attempt 1 of 10)...
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 1975, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 1914, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2287, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib64/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

## Description

After downloading 100-200MB it abruptly throws a 404 error , resuming doesn't work either ( 404 )

**Comment by kikuyan** [comment]
Is the 480p video actually playable to the end in the browser?
I tried with Firefox and it stopped about 20+ minutes past and got this:

> Unexpected error
> This video can’t be displayed right now, sorry
> Report ID: 1fe4t5qc71hpubnv3mb

and in the DevTools:

> GET https://proxy-018.dc3.dailymotion.com/sec(49Ubi9udHuLcl5WIYb0CSl5xgR3WKYoiwr2GCdWn4OAwdqJchZj5kUffotQR_kUU2q3vw5dw2uf1NSH6a4ST0USTTEhyjrplvfuf0t-2Wyg)/frag(133)/video/621/280/156082126_mp4_h264_aac_hq.ts
> 
> 503 Service Unavailable
>

**Comment by attinderdhillon** [comment]
I confirm 480p stopped working about 20+ minutes past. I checked some more videos I had errors that wouldn't play past xx minutes.
So the issue is at Dailymotion.  youtube-dl works fine when the video is playable till the end.
