### ISSUE TITLE
[lbry] unable to download video data transport endpoint not connected

### ISSUE THREAD

**Issue by wishgranter14** [ytdl-org/youtube-dl#29878]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://odysee.com/@MichaelLuzzi:7/i-broke-my-ps5:b']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.6 (CPython) - Linux-5.13.10-artix1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[lbry] @MichaelLuzzi#7/i-broke-my-ps5#b: Downloading stream JSON metadata
[lbry] b1442768ee10103e39744a5d21c0a627ec858aa6: Downloading streaming url JSON metadata
[lbry] @MichaelLuzzi#7/i-broke-my-ps5#b: Downloading streaming redirect url info
[lbry] @MichaelLuzzi#7/i-broke-my-ps5#b: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://use-p3.lbryplayer.xyz/api/v4/streams/tc/i-broke-my-ps5/b1442768ee10103e39744a5d21c0a627ec858aa6/f445e4e2efe5b90953ac53c7b33e7dea90154aded0a01cbaa6c0480ce8d7e7f0ede685dcbef6c0523192deb239363d74/stream_0.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1
[download] Destination: I BROKE My PS5-b1442768ee10103e39744a5d21c0a627ec858aa6.mp4
ERROR: unable to download video data: [Errno 107] Transport endpoint is not connected: 'I BROKE My PS5-b1442768ee10103e39744a5d21c0a627ec858aa6.mp4.ytdl'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 1976, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/hls.py", line 112, in real_download
    self._prepare_and_start_frag_download(ctx)
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/fragment.py", line 69, in _prepare_and_start_frag_download
    self._prepare_frag_download(ctx)
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/fragment.py", line 182, in _prepare_frag_download
    self._write_ytdl_file(ctx)
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/fragment.py", line 87, in _write_ytdl_file
    frag_index_stream, _ = sanitize_open(self.ytdl_filename(ctx['filename']), 'w')
  File "/usr/lib/python3.9/site-packages/youtube_dl/utils.py", line 2055, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
OSError: [Errno 107] Transport endpoint is not connected: 'I BROKE My PS5-b1442768ee10103e39744a5d21c0a627ec858aa6.mp4.ytdl'
```

## Description

I try to download the video and it gives me this error.  Not really sure what else to say.

**Comment by kikuyan** [comment]
No problem here. Maybe temporary server error or problem of your network.
```
$ youtube-dl https://odysee.com/@MichaelLuzzi:7/i-broke-my-ps5:b --ignore-config
[lbry] @MichaelLuzzi#7/i-broke-my-ps5#b: Downloading stream JSON metadata
[lbry] b1442768ee10103e39744a5d21c0a627ec858aa6: Downloading streaming url JSON metadata
[lbry] @MichaelLuzzi#7/i-broke-my-ps5#b: Downloading streaming redirect url info
[lbry] @MichaelLuzzi#7/i-broke-my-ps5#b: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1
[download] Destination: I BROKE My PS5-b1442768ee10103e39744a5d21c0a627ec858aa6.mp4
[download] 100% of 1.68MiB in 00:00
[ffmpeg] Fixing malformed AAC bitstream in "I BROKE My PS5-b1442768ee10103e39744a5d21c0a627ec858aa6.mp4"
```
