### ISSUE TITLE
youtube-dl does not download cartoons from ivi.ru

### ISSUE THREAD

**Issue by EgorKuzevanov** [ytdl-org/youtube-dl#29879]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.ivi.ru/watch/kindi-kids/434759']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
[ivi] 434759: Downloading video JSON
ERROR: This feature does not work from bundled exe. Run youtube-dl from sources.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\ivi.py", line 146, in _real_extract
youtube_dl.utils.ExtractorError: This feature does not work from bundled exe. Run youtube-dl from sources.
```

## Description

The cartoon plays fine in Yandex.Browser. But if I'm running youtube-dl I got this error: **This feature does not work from bundled exe. Run youtube-dl from sources.**

**Comment by kikuyan** [comment]
Follow the error message first. For ex. use the version installed with pip.

But even after that, you may fail. The page you are trying to download seems to require an account, but according to the comments from the dev at https://github.com/ytdl-org/youtube-dl/issues/23552, user authentication or cookies doesn't work.
