### ISSUE TITLE
[zdf/arte] Extractor error (KeyError) with at least one title

### ISSUE THREAD

**Issue by mklein-de** [ytdl-org/youtube-dl#29893]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ ~/youtube-dl --verbose 'https://www.zdf.de/arte/arte-plus-7/page-video-artede-der-mit-dem-wolf-tanzt-100.html'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.zdf.de/arte/arte-plus-7/page-video-artede-der-mit-dem-wolf-tanzt-100.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18 (CPython) - Linux-5.10.0-7-amd64-x86_64-with-debian-11.0
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 53.77.8.185 (DE) as X-Forwarded-For.
[ZDF] page-video-artede-der-mit-dem-wolf-tanzt-100: Downloading webpage
[ZDF] page-video-artede-der-mit-dem-wolf-tanzt-100: Downloading JSON content
ERROR: An extractor error has occurred. (caused by KeyError(u'http://zdf.de/rels/streams/ptmd-template',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/michael/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/michael/youtube-dl/youtube_dl/extractor/zdf.py", line 292, in _real_extract
    return self._extract_regular(url, player, video_id)
  File "/home/michael/youtube-dl/youtube_dl/extractor/zdf.py", line 241, in _extract_regular
    return self._extract_entry(player['content'], player, content, video_id)
  File "/home/michael/youtube-dl/youtube_dl/extractor/zdf.py", line 204, in _extract_entry
    'http://zdf.de/rels/streams/ptmd-template'].replace(
KeyError: u'http://zdf.de/rels/streams/ptmd-template'
Traceback (most recent call last):
  File "/home/michael/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/michael/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/michael/youtube-dl/youtube_dl/extractor/common.py", line 547, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'http://zdf.de/rels/streams/ptmd-template',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Video plays fine in Firefox

**Comment by dirkf** [comment]
In this page, the extractor is looking for somewhere to find metadata, using the JSON returned from the `api.zdf.de`.

It looks for `content['mainVideoContent']['http://zdf.de/rels/target']`, which is like this:
```
  'mainVideoContent': {
    'http://zdf.de/rels/target': {
      'title': 'Der mit dem Wolf tanzt',
      'duration': 10302,
      'visible': true,
      'visibleFrom': '2021-08-29T05:00:00.000+02:00',
      'visibleTo': '2021-09-05T05:00:00.000+02:00',
      'aspectRatio': '16:9',
      'profile': 'http://zdf.de/rels/content/content-video-vod-partner-player',
      'self': '/content/documents/zdf/arte/arte-plus-7/vod-artede-der-mit-dem-wolf-tanzt-100.json?profile=player',
      'canonical': '/content/documents/vod-artede-der-mit-dem-wolf-tanzt-100.json',
      'streams': {
        'default': {
          'label': 'Normal',
          'extId': 'video_artede_097462-000-A',
          'http://zdf.de/rels/streams/ptmd-template': '/content/documents/vod-artede-der-mit-dem-wolf-tanzt-100.json?profile=tmd'
        }
      }
    },
    'profile': 'http://zdf.de/rels/content-reference/video-content'
  }
```
Within that, it looks for the item named `http://zdf.de/rels/streams/ptmd` but doesn't find it. It then looks for an item `http://zdf.de/rels/streams/ptmd-template` and fails.

Apparently instead of failing there it should look in `['streams']['default']`.

**Comment by Fabian42** [comment]
I'm probably experiencing the same bug as here, but the exact output has changed since then:

```bash
[fabian@manjaro ~]$ youtube-dl --verbose "https://www.zdf.de/comedy/heute-show/what-the-fakt-querdenker-corona-leugner-impfstoff-idar-oberstein-verfassungsschutz-102.html"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.zdf.de/comedy/heute-show/what-the-fakt-querdenker-corona-leugner-impfstoff-idar-oberstein-verfassungsschutz-102.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.7 (CPython) - Linux-5.10.63-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 53.247.234.54 (DE) as X-Forwarded-For.
[ZDF] what-the-fakt-querdenker-corona-leugner-impfstoff-idar-oberstein-verfassungsschutz-102: Downloading webpage
[ZDF] what-the-fakt-querdenker-corona-leugner-impfstoff-idar-oberstein-verfassungsschutz-102: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('basename')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/zdf.py", line 294, in _real_extract
    return self._extract_mobile(video_id)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/zdf.py", line 251, in _extract_mobile
    content_id = document['basename']
KeyError: 'basename'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/zdf.py", line 294, in _real_extract
    return self._extract_mobile(video_id)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/zdf.py", line 251, in _extract_mobile
    content_id = document['basename']
KeyError: 'basename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 547, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('basename')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[fabian@manjaro ~]$ youtube-dl --version
2021.06.06
```

**Comment by Fabian42** [comment]
In case you saw my previous comment: Nevermind, they linked a text article with image in a series of videos and made it look like just another video, but it's actually not. I guess youtube-dl _could_ download the image, but I wouldn't expect it. It's definitely not this bug.

**Comment by dirkf** [comment]
@mklein-de, do you have a similar link that is still current? This patch seems to work with current videos in the unit tests:
```
         t = content['mainVideoContent']['http://zdf.de/rels/target']
 
-        ptmd_path = t.get('http://zdf.de/rels/streams/ptmd')
+        def get_ptmd_path(d):
+            return (
+                d.get('http://zdf.de/rels/streams/ptmd')
+                or d.get('http://zdf.de/rels/streams/ptmd-template',
+                         '').replace('{playerId}', 'ngplayer_2_4'))
 
+        ptmd_path = get_ptmd_path(t)
+
         if not ptmd_path:
-            ptmd_path = t[
-                'http://zdf.de/rels/streams/ptmd-template'].replace(
-                '{playerId}', 'ngplayer_2_4')
+            tt = try_get(t, lambda x: x['streams']['default'], dict)
+            if tt:
+                ptmd_path = get_ptmd_path(tt)
 
         info = self._extract_ptmd(
             urljoin(url, ptmd_path), video_id, player['apiToken'], url)
```

**Comment by mklein-de** [comment]
> @mklein-de, do you have a similar link that is still current?

unfortunately no, this was only link that gave me that kind of error.

**Comment by heinzl66** [comment]
This might be a similar error:

`youtube-dl.exe --verbose https://www.zdf.de/serien/auckland-detectives-toedliche-bucht/aus-dem-nichts-110.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.zdf.de/serien/auckland-detectives-toedliche-bucht/aus-dem-nichts-110.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.4-essentials_build-www.gyan.dev, ffprobe 4.4-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[debug] Using fake IP 53.246.216.113 (DE) as X-Forwarded-For.
[ZDF] aus-dem-nichts-110: Downloading webpage
[ZDF] aus-dem-nichts-110: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('basename',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\zdf.py", line 294, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\zdf.py", line 251, in _extract_mobile
KeyError: 'basename'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\zdf.py", line 294, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\zdf.py", line 251, in _extract_mobile
KeyError: 'basename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 547, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('basename',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by tstelzle** [comment]
I have the same issue with the following video: [Krabat](https://www.zdf.de/arte/arte/page-video-artede-krabat-100.html)

This is the verbose output:
```console
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.zdf.de/arte/arte/page-video-artede-krabat-100.html', u'--verbose']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-91-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg present, ffprobe present, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 53.214.210.190 (DE) as X-Forwarded-For.
[ZDF] page-video-artede-krabat-100: Downloading webpage
[ZDF] page-video-artede-krabat-100: Downloading JSON content
ERROR: An extractor error has occurred. (caused by KeyError(u'http://zdf.de/rels/streams/ptmd-template',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/zdf.py", line 292, in _real_extract
    return self._extract_regular(url, player, video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/zdf.py", line 241, in _extract_regular
    return self._extract_entry(player['content'], player, content, video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/zdf.py", line 204, in _extract_entry
    'http://zdf.de/rels/streams/ptmd-template'].replace(
KeyError: u'http://zdf.de/rels/streams/ptmd-template'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 547, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'http://zdf.de/rels/streams/ptmd-template',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Hope this helps!

**Comment by mklein-de** [comment]
This seems to be a regression. The link works with youtube-dl 2021.06.06 from Debian Bullseye, but fails with 2021.12.17

**Comment by dirkf** [comment]
Fixed in git master, presumably by merging the PR above. Hence why the issue is closed.
