### ISSUE TITLE
Special formatting sequences do not work for --download-archive

### ISSUE THREAD

**Issue by XZenon2000** [ytdl-org/youtube-dl#29894]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
 4:25:15,50|C:\Users\user>ytdl -v --download-archive "D:\user-pc\Users\user_old\Desktop\Misc\Musik, Videos\Zu Bearbeiten\YouTube Downloads\%(channel)s\archive.txt" --ignore-errors --format bestvideo[ext=mp4]+bestaudio[ext=m4a] --merge-output-format mp4 --embed-thumbnail -o "D:\user-pc\Users\user_old\Desktop\Misc\Musik, Videos\Zu Bearbeiten\YouTube Downloads\%(channel)s\%(upload_date)s - %(title)s.%(ext)s" https://www.youtube.com/user/SteffanieRainbow/videos
[debug] System config: []
[debug] User config: ['-o', 'D:/user-pc/Users/user_old/Desktop/Misc/Musik, Videos/Zu Bearbeiten/YouTube Downloads/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', '--download-archive', 'D:\\user-pc\\Users\\user_old\\Desktop\\Misc\\Musik, Videos\\Zu Bearbeiten\\YouTube Downloads\\%(channel)s\\archive.txt', '--ignore-errors', '--format', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]', '--merge-output-format', 'mp4', '--embed-thumbnail', '-o', 'D:\\user-pc\\Users\\user_old\\Desktop\\Misc\\Musik, Videos\\Zu Bearbeiten\\YouTube Downloads\\%(channel)s\\%(upload_date)s - %(title)s.%(ext)s', 'https://www.youtube.com/user/SteffanieRainbow/videos']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-94664-g0821bc4eee, ffprobe N-94664-g0821bc4eee
[debug] Proxy map: {}
[youtube:tab] SteffanieRainbow: Downloading webpage
[download] Downloading playlist: Steffanie Rainbow - Videos
[youtube:tab] playlist Steffanie Rainbow - Videos: Downloading 16 videos
[download] Downloading video 1 of 16
[youtube] NXe5xnXYdno: Downloading webpage
[youtube] NXe5xnXYdno: Downloading thumbnail ...
[youtube] NXe5xnXYdno: Writing thumbnail to: D:\user-pc\Users\user_old\Desktop\Misc\Musik, Videos\Zu Bearbeiten\YouTube Downloads\Steffanie Rainbow\20210519 - 【VTuber】Showcase - Niji (Live2D).jpg
[debug] Invoking downloader on 'https://r1---sn-4g5ednd7.googlevideo.com/videoplayback?expire=1630485134&ei=LuYuYf3AG9CWgQfLnbLYAg&ip=2a00%3A5ba0%3A8000%3A6c90%3Add3f%3A5449%3Ae685%3A58d9&id=o-AC7cXaG2S1OoC3mGHzR0FIPlgPlannrXMTL7IBCiHj0H&itag=299&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C308&source=youtube&requiressl=yes&mh=mM&mm=31%2C26&mn=sn-4g5ednd7%2Csn-i5h7lnll&ms=au%2Conr&mv=m&mvi=1&pl=29&initcwndbps=1141250&vprv=1&mime=video%2Fmp4&ns=LrgC_UMmaOozMtB7na6qngQG&gir=yes&clen=22346557&dur=51.716&lmt=1621454480340674&mt=1630463335&fvip=1&keepalive=yes&fexp=24001373%2C24007246&beids=9466588&c=WEB&txp=6216224&n=iL0kDRj-bBDSff9j&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANGbSkmBrbGt5GOL_uUydh0hp_TswUzRyVwDj07ObGPsAiEAgnYcL59khfA7IOXXUZ2Qqmo7go1-_rPOE_ZxWOHAhlc%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgDUdO13w5jIc6stFekqyC2ef5vewydo592rtTy9WxUhUCIQCoRYcCb3EBf7g-IIh8Pyep9QGeZRw415Pn8pXAJqDxLQ%3D%3D'
[download] Destination: D:\user-pc\Users\user_old\Desktop\Misc\Musik, Videos\Zu Bearbeiten\YouTube Downloads\Steffanie Rainbow\20210519 - 【VTuber】Showcase - Niji (Live2D).f299.mp4
[download] 100% of 21.31MiB in 06:07
[debug] Invoking downloader on 'https://r1---sn-4g5ednd7.googlevideo.com/videoplayback?expire=1630485134&ei=LuYuYf3AG9CWgQfLnbLYAg&ip=2a00%3A5ba0%3A8000%3A6c90%3Add3f%3A5449%3Ae685%3A58d9&id=o-AC7cXaG2S1OoC3mGHzR0FIPlgPlannrXMTL7IBCiHj0H&itag=140&source=youtube&requiressl=yes&mh=mM&mm=31%2C26&mn=sn-4g5ednd7%2Csn-i5h7lnll&ms=au%2Conr&mv=m&mvi=1&pl=29&initcwndbps=1141250&vprv=1&mime=audio%2Fmp4&ns=LrgC_UMmaOozMtB7na6qngQG&gir=yes&clen=838767&dur=51.780&lmt=1621454473205639&mt=1630463335&fvip=1&keepalive=yes&fexp=24001373%2C24007246&beids=9466588&c=WEB&txp=6211224&n=iL0kDRj-bBDSff9j&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAKYu81l-T4QiUQmLn8G5gF2NUOAQPK-R4lrAwA5mmRCMAiBV8RV2v1syuk-gHkko4x2nftAENutQwWceojIGlRhb1w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgDUdO13w5jIc6stFekqyC2ef5vewydo592rtTy9WxUhUCIQCoRYcCb3EBf7g-IIh8Pyep9QGeZRw415Pn8pXAJqDxLQ%3D%3D'
[download] Destination: D:\user-pc\Users\user_old\Desktop\Misc\Musik, Videos\Zu Bearbeiten\YouTube Downloads\Steffanie Rainbow\20210519 - 【VTuber】Showcase - Niji (Live2D).f140.m4a
[download] 100% of 819.11KiB in 00:13
[ffmpeg] Merging formats into "D:\user-pc\Users\user_old\Desktop\Misc\Musik, Videos\Zu Bearbeiten\YouTube Downloads\Steffanie Rainbow\20210519 - 【VTuber】Showcase - Niji (Live2D).mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:D:\user-pc\Users\user_old\Desktop\Misc\Musik, Videos\Zu Bearbeiten\YouTube Downloads\Steffanie Rainbow\20210519 - 【VTuber】Showcase - Niji (Live2D).f299.mp4" -i "file:D:\user-pc\Users\user_old\Desktop\Misc\Musik, Videos\Zu Bearbeiten\YouTube Downloads\Steffanie Rainbow\20210519 - 【VTuber】Showcase - Niji (Live2D).f140.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:D:\user-pc\Users\user_old\Desktop\Misc\Musik, Videos\Zu Bearbeiten\YouTube Downloads\Steffanie Rainbow\20210519 - 【VTuber】Showcase - Niji (Live2D).temp.mp4"
Deleting original file D:\user-pc\Users\user_old\Desktop\Misc\Musik, Videos\Zu Bearbeiten\YouTube Downloads\Steffanie Rainbow\20210519 - 【VTuber】Showcase - Niji (Live2D).f299.mp4 (pass -k to keep)
Deleting original file D:\user-pc\Users\user_old\Desktop\Misc\Musik, Videos\Zu Bearbeiten\YouTube Downloads\Steffanie Rainbow\20210519 - 【VTuber】Showcase - Niji (Live2D).f140.m4a (pass -k to keep)
[ffmpeg] Correcting extension to webp and escaping path for thumbnail "D:\user-pc\Users\user_old\Desktop\Misc\Musik, Videos\Zu Bearbeiten\YouTube Downloads\Steffanie Rainbow\20210519 - 【VTuber】Showcase - Niji (Live2D).jpg"
[ffmpeg] Converting thumbnail "D:\user-pc\Users\user_old\Desktop\Misc\Musik, Videos\Zu Bearbeiten\YouTube Downloads\Steffanie Rainbow\20210519 - 【VTuber】Showcase - Niji (Live2D).webp" to JPEG
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:D:\user-pc\Users\user_old\Desktop\Misc\Musik, Videos\Zu Bearbeiten\YouTube Downloads\Steffanie Rainbow\20210519 - 【VTuber】Showcase - Niji (Live2D).webp" "-bsf:v" mjpeg2jpeg "file:D:\user-pc\Users\user_old\Desktop\Misc\Musik, Videos\Zu Bearbeiten\YouTube Downloads\Steffanie Rainbow\20210519 - 【VTuber】Showcase - Niji (Live2D).jpg"
[atomicparsley] Adding thumbnail to "D:\user-pc\Users\user_old\Desktop\Misc\Musik, Videos\Zu Bearbeiten\YouTube Downloads\Steffanie Rainbow\20210519 - 【VTuber】Showcase - Niji (Live2D).mp4"
[debug] AtomicParsley command line: AtomicParsley "D:\user-pc\Users\user_old\Desktop\Misc\Musik, Videos\Zu Bearbeiten\YouTube Downloads\Steffanie Rainbow\20210519 - 【VTuber】Showcase - Niji (Live2D).mp4" --artwork "D:\user-pc\Users\user_old\Desktop\Misc\Musik, Videos\Zu Bearbeiten\YouTube Downloads\Steffanie Rainbow\20210519 - 【VTuber】Showcase - Niji (Live2D).jpg" -o "D:\user-pc\Users\user_old\Desktop\Misc\Musik, Videos\Zu Bearbeiten\YouTube Downloads\Steffanie Rainbow\20210519 - 【VTuber】Showcase - Niji (Live2D).temp.mp4"
ERROR: [Errno 2] No such file or directory: 'D:\\user-pc\\Users\\user_old\\Desktop\\Misc\\Musik, Videos\\Zu Bearbeiten\\YouTube Downloads\\%(channel)s\\archive.txt'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 847, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 881, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 1692, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2054, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2171, in record_download_archive
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\utils.py", line 3328, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\user-pc\\Users\\user_old\\Desktop\\Misc\\Musik, Videos\\Zu Bearbeiten\\YouTube Downloads\\%(channel)s\\archive.txt'

[download] Downloading video 2 of 16
```

## Description

I have noticed that the special formatting sequences that can be used with the -o option cannot be used with the --download-archive option.
I want the archive.txt file to be generated in the %(channel)s\ subfolder of the folder Youtube Downloads\ but while the subfolder is accepted by the -o option, this doesn't work for the --download-archive option.
Writing it as "%%(channel)s" doesn't change anything.
Is this a bug or has this not been implemented yet?

Thank you for your help.

**Comment by dirkf** [comment]
Whatever filename you give as the value of the `--download-archive` option is used as-is.

You could try generating a filename with `--get-filename` using a template such as `-o "Youtube Downloads\%(channel)s\archive.txt" (%% in a Windows batch script) and use that.

The [`for /f` command](https://ss64.com/nt/for_cmd.html) is useful in a Windows batch (cmd) script to set a variable to the output of a command, as with `$(command)` in a POSIX shell script.

**Comment by tursi960** [comment]
I experience this issue myself. This is particularly annyoing when trying to download Music Playlists as using a global archive means that each song can only be in the first playlist it is mentioned in. 

This is not a bug, it's just not implemented. Don't know if I have the time for it righ now

**Comment by Lee-Carre** [comment]
> using a global archive means that each song can only be in the first playlist it is mentioned in.

Don't set an absolute path, then.

I simply set a filename, so that the current working directory of wherever I'm downloading to, is used.
I tend to organise downloads into directories. A playlist would have its own subdirectory.

I've not encountered any problems with this approach. If entries from a file in a different directory are needed, there's various methods to do that (including concatenating with the entries in the CWD).

No need to make `youtube-dl` more complex when the command line itself can already do as you wish.
