### ISSUE TITLE
2021.05.06 and YouTube Rumble - No longer supported?

### ISSUE THREAD

**Issue by superchap** [ytdl-org/youtube-dl#29938]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

[LinuxMint user]

As per github here --> https://github.com/ytdl-org/youtube-dl/commit/f47627a1c9a790fac29d5c166bc0f7944fcb1a98 , at the bottom of the page, it appears that YouTube (and Rumble) may not work with youtube-dl any longer. Is this a correct conclusion?

Fortunately, I did find the same video on Bitchute and it downloaded with youtube-dl just fine (again, as per the above referenced link or supported sites; which excludes reference to YouTube and Rumble). So, that's good!

Here is the error report when trying to download from both YouTube and Rumble.

========================================
WHEN attempting download from YouTube ...
========================================

~ $ youtube-dl --verbose -i -o "/media/jeff/Seagate Backup Plus Drive/911/Playlist_index)s - %(title)s.%(ext)s" https://www.youtube.com/watch?v=9Wf3O93I4lI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-i', u'-o', u'/media/jeff/Seagate Backup Plus Drive/911/Playlist_index)s - %(title)s.%(ext)s', u'https://www.youtube.com/watch?v=9Wf3O93I4lI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-210-generic-x86_64-with-LinuxMint-18.1-serena
[debug] exe versions: ffmpeg 3.2.2-2, ffprobe 3.2.2-2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 9Wf3O93I4lI: Downloading webpage
[youtube] 9Wf3O93I4lI: Refetching age-gated info webpage
WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: 'bool' object has no attribute 'split'
Traceback (most recent call last):
  File "/home/jeff/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jeff/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/jeff/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/jeff/.local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1503, in _real_extract
    }, fatal=False)),
  File "/home/jeff/.local/lib/python2.7/site-packages/youtube_dl/compat.py", line 2644, in compat_parse_qs
    encoding=encoding, errors=errors)
  File "/home/jeff/.local/lib/python2.7/site-packages/youtube_dl/compat.py", line 2614, in _parse_qsl
    pairs = [s2 for s1 in qs.split('&') for s2 in s1.split(';')]
AttributeError: 'bool' object has no attribute 'split'

========================================
AND when attempted to download from RUMBLE ...
========================================

 ~ $ youtube-dl --verbose -i -o "/media/jeff/Seagate Backup Plus Drive/911/Playlist_index)s - %(title)s.%(ext)s" https://rumble.com/vjzfki-jfk-t0-911-everything-is-a-rich-mans-trick-must-see-chilling-documentary.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-i', u'-o', u'/media/jeff/Seagate Backup Plus Drive/911/Playlist_index)s - %(title)s.%(ext)s', u'https://rumble.com/vjzfki-jfk-t0-911-everything-is-a-rich-mans-trick-must-see-chilling-documentary.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-210-generic-x86_64-with-LinuxMint-18.1-serena
[debug] exe versions: ffmpeg 3.2.2-2, ffprobe 3.2.2-2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] vjzfki-jfk-t0-911-everything-is-a-rich-mans-trick-must-see-chilling-documentary: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vjzfki-jfk-t0-911-everything-is-a-rich-mans-trick-must-see-chilling-documentary: Downloading webpage
[generic] vjzfki-jfk-t0-911-everything-is-a-rich-mans-trick-must-see-chilling-documentary: Extracting information
ERROR: Unsupported URL: https://rumble.com/vjzfki-jfk-t0-911-everything-is-a-rich-mans-trick-must-see-chilling-documentary.html
Traceback (most recent call last):
  File "/home/jeff/.local/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 2503, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/home/jeff/.local/lib/python2.7/site-packages/youtube_dl/compat.py", line 2571, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/home/jeff/.local/lib/python2.7/site-packages/youtube_dl/compat.py", line 2560, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/home/jeff/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jeff/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/jeff/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/jeff/.local/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 3520, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://rumble.com/vjzfki-jfk-t0-911-everything-is-a-rich-mans-trick-must-see-chilling-documentary.html

Thanks in advance for the great service and program!
Kindly,
- jeff

**Comment by kikuyan** [comment]
Read [this](https://github.com/ytdl-org/youtube-dl#does-the-issue-involve-one-problem-and-one-problem-only) first.
As to the youtube url, try passing cookies, or read [other reports](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+is%3Aopen+age+gated).

**Comment by superchap** [comment]
Thank you. Reading soon.

**Comment by superchap** [comment]
Not seeing the relevant content in those links.

**Comment by dirkf** [comment]
Supposing that OP had asked just one question and it was the one about Rumble ...

The Rumble extractor works, but only understands embed URLs. You can get the embed URL https://rumble.com/embed/vhd9f8/?pub=4 for the linked video using the EMBED button under the video player.

yt-dl doesn't have a specific option for immediately deleting a file after downloading it, which might apparently be useful for this content.

The extractor could be extended to handle plain Rumble URLs by looking at the `<script type="application/ld+json">` in the `<HEAD>` element of the page, whose content is a JSON list containing an object of type `VideoObject` with `'embedUrl': 'https://rumble.com/embed/vhd9f8/'`.

**Comment by superchap** [comment]
let me give that a try! Thx.

**Comment by superchap** [comment]
Yep! That's the magic right there!
Thanks a lot for sticking with me.

**Comment by dirkf** [comment]
Problem URLs no longer valid.
