### ISSUE TITLE
Can't download from novaplus.nova.cz

### ISSUE THREAD

**Issue by pparik** [ytdl-org/youtube-dl#29967]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://novaplus.nova.cz/porad/svatba-na-prvni-pohled/epizoda/79738-1-dil']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.7 (CPython) - Linux-5.13.14-100.fc33.x86_64-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2
[debug] Proxy map: {}
[Nova] 79738-1-dil: Downloading webpage
[NovaEmbed] 8qOo75hGchs: Downloading webpage
ERROR: Unable to extract formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 814, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 835, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/nova.py", line 72, in _real_extract
    self._search_regex(
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Can't download https://novaplus.nova.cz/porad/svatba-na-prvni-pohled/epizoda/79738-1-dil

**Comment by dirkf** [comment]
In the UK I need to use `--geo-bypass-country CZ`.

Then the extractor finds the embed link https://media.cms.nova.cz/embed/8qOo75hGchs and redirects to using the `url_transparent` method. The embed page sends JS that includes an unexpected expression: specifically, where the extractor expects a JSON object delimited by `{}`, it's being sent `personalizedAds ? json1: json2`.

The first JSON block could be skipped with this change (`extractor/nova.py` ll.40-43)

```
         player = self._parse_json(
             self._search_regex(
-                r'Player\.init\s*\([^,]+,\s*({.+?})\s*,\s*{.+?}\s*\)\s*;',
+                r'Player\.init\s*\([^,]+,\s*(?:\w+\s*\?\s*{.+?}\s*:\s*)?({.+?})\s*,\s*{.+?}\s*\)\s*;'
                 webpage, 'player', default='{}'), video_id, fatal=False)
```
Then everything should work as before.
