### ISSUE TITLE
Funimation Updated Site

### ISSUE THREAD

**Issue by card0z** [ytdl-org/youtube-dl#29963]
Can you update youtube-dl to work with the latest version of funimation. It seems to have a /v/ in the middle of the url. For eg:https://www.funimation.com/v/black-clover/vice-captain-langris-vaude instead of https://www.funimation.com/en/black-clover/vice-captain-langris-vaude. I can drag and drop the url from edge beta into mpv and it plays but not on firefox.
Thank you.

**Comment by card0z** [comment]
No it isn't working. it says site not supported. For the url which includes the /v/

**Comment by card0z** [comment]
Will it be updated any time soon?

**Comment by meap98** [comment]
> Yea it still can download the audio and video and then you can ffmpeg them together but its better to have youtube-dl parse and do it all.

So I was wondering how do you get the m3u8 files because at the curent time it might be our only work around since Funimation switched over to the new video player

**Comment by Rocksteady18** [comment]
In firefox dev tools turn on responsive mode and set to ipad and then reload the page and look in network tab of dev tools it will use hls player and you will get m3u8 link.

**Comment by meap98** [comment]
> In firefox dev tools turn on responsive design mode and set to ipad and then reload the page and look in network tab of dev tools it will use hls player and you will get m3u8 link.

so with funimation you can't load into a video in firefox while in incognito mode and I don't want to use my Funimation account for this because I'm just doing testing rn

**Comment by Rocksteady18** [comment]
It’s usually the first one which is the master.  It’s the same thing youtube-dl sees when it’s working and you do youtube-dl -F

**Comment by meap98** [comment]
> It’s usually the first one which is the master. It’s the same thing youtube-dl sees when it’s working and you do youtube-dl -F

okay so is it the first one in this case
![Screenshot 2021-10-10 111710](https://user-images.githubusercontent.com/47130959/136702017-a1e2b351-5a10-4c9f-91d3-b040bf5e6d50.png)

**Comment by joshbrown50** [comment]
I am also getting the 403 Forbidden error

**Comment by Rocksteady18** [comment]
Would be good to have it fixed.  I hope the devs are aware.

**Comment by Rocksteady18** [comment]
Using yt-dlp now it works great.
https://github.com/yt-dlp/yt-dlp

**Comment by card0z** [comment]
Thank you so much!! Appreciate it!

**Comment by dnordel** [comment]
I was having the same issue, and when I changed the "/v/" in the URL to "/shows/" and added "/?lang=English" (which does work to access the show directly) to the end of the URL, it no longer throws off this error. However, I am now getting the following error:

Microsoft Windows [Version 10.0.19045.2251]
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd C:\youtube-dl

C:\youtube-dl>youtube-dl --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" -u chrisnordel@gmail.com -p Tor105/5 --cookies cookies-funimation-com.txt --embed-subs --embed-thumbnail --add-metadata -o %(episode_number)s-%(title)s.%(ext)s --recode-video mkv --sleep-interval 5 -a Links.txt
[Funimation] Logging in
[Funimation] zs-ambition-lily-the-little-giant: Downloading webpage
WARNING: [Funimation] zs-ambition-lily-the-little-giant: Failed to parse JSON Expecting value: line 1 column 1 (char 0)
ERROR: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


C:\youtube-dl>youtube-dl -v https://www.funimation.com/shows/one-piece/zs-ambition-lily-the-little-giant/?lang=English
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.funimation.com/shows/one-piece/zs-ambition-lily-the-little-giant/?lang=English']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2022-11-03-git-5ccd4d3060-full_build-www.gyan.dev, ffprobe 2022-11-03-git-5ccd4d3060-full_build-www.gyan.dev
[debug] Proxy map: {}
[Funimation] zs-ambition-lily-the-little-giant: Downloading webpage
WARNING: [Funimation] zs-ambition-lily-the-little-giant: Failed to parse JSON Expecting value: line 1 column 1 (char 0)
ERROR: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\funimation.py", line 104, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1142, in _html_search_meta
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1021, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dnordel** [comment]
I also tried removing the -u -p, as https://github.com/ytdl-org/youtube-dl/issues/30056 suggests, but still get the error:

C:\youtube-dl>youtube-dl.exe --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" --cookies cookies-funimation-com.txt --embed-subs --embed-thumbnail --add-metadata -o %(episode_number)s-%(title)s.%(ext)s --recode-video mkv -v https://www.funimation.com/shows/one-piece/zs-ambition-lily-the-little-giant/?lang=English
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36', '--cookies', 'cookies-funimation-com.txt', '--embed-subs', '--embed-thumbnail', '--add-metadata', '-o', '%(episode_number)s-%(title)s.%(ext)s', '--recode-video', 'mkv', '-v', 'https://www.funimation.com/shows/one-piece/zs-ambition-lily-the-little-giant/?lang=English']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2022-11-03-git-5ccd4d3060-full_build-www.gyan.dev, ffprobe 2022-11-03-git-5ccd4d3060-full_build-www.gyan.dev
[debug] Proxy map: {}
[Funimation] zs-ambition-lily-the-little-giant: Downloading webpage
WARNING: [Funimation] zs-ambition-lily-the-little-giant: Failed to parse JSON Expecting value: line 1 column 1 (char 0)
ERROR: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\funimation.py", line 104, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1142, in _html_search_meta
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1021, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
