### ISSUE TITLE
Multi-threaded download from YouTube fails

### ISSUE THREAD

**Issue by timelessnesses** [ytdl-org/youtube-dl#29960]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
Exception in thread Thread-21:
Traceback (most recent call last):
  File "C:\Users\moopi\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\moopi\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\moopi\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\moopi\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\youtube.py", line 1715, in _real_extract
    self._sort_formats(formats)
  File "C:\Users\moopi\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.       

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "d:\downloaderyoutubemp3.py", line 18, in download
    info = ydl.extract_info(url, download=False)
  File "C:\Users\moopi\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\moopi\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\moopi\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\moopi\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
```

## Description

So I try to download multiple videos and convert them to mp3 with ffmpeg with using multi thread to download it.  
Suddenly some videos is undownloadable and throw error above.  
Code written in python
```py
import youtube_dl
from threading import Thread
from requests import get

print("Testing urls. URL count are",len(open("youtube.txt").readlines()),".")

for url in open("youtube.txt").read().split("\n"):
	try:
		print(f"Result {url} is alive is",get(url).status_code == 200 or get(url).status_code == 202)
	except:
		print(f"{url} Unreachable.")
	else:
		print(f"Pass {url}")
def download(url):
	ydl_opts = {
		'format': 'bestaudio/best',
		'postprocessors': [{
			'key': 'FFmpegExtractAudio',
			'preferredcodec': 'mp3',
			'preferredquality': '192',
		}],
		'outtmpl': '%(title)s.%(ext)s',
		'noplaylist': True,
		"quiet": False,
		"debug":True
	}
	info = None
	with youtube_dl.YoutubeDL(ydl_opts) as ydl:
			info = ydl.extract_info(url, download=False)
	try:
		with youtube_dl.YoutubeDL(ydl_opts) as ydl:
			info = ydl.extract_info(url, download=False)
			print("Video name is "+info['title']+".")
			print("Downloading..."+info['title']+".mp3")
			ydl.download([url])
	except:
		print("Error downloading video name "+info['title']+".")
	else:
		print("Done downloading "+info['title']+".mp3")
	finally:
		print("Closing thread.")
for url in open('youtube.txt').read().split("\n"):
	if url != "":
		Thread(target=download, args=(url,)).start()
```
youtube.txt
```
https://www.youtube.com/watch?v=TSDKhs56ASk
https://www.youtube.com/watch?v=hMj1X80kUcI
https://www.youtube.com/watch?v=8qN2ZkuEXzQ
https://www.youtube.com/watch?v=fkjLKlhx9lU
https://www.youtube.com/watch?v=twPfxOVczUs
https://www.youtube.com/watch?v=7wFKCj7zz0w
https://www.youtube.com/watch?v=j1iIwQyrVyk
https://www.youtube.com/watch?v=91DIPPYD98Q
https://www.youtube.com/watch?v=VjWXt2Fnu7I
https://www.youtube.com/watch?v=PivPBSJcRcI
https://www.youtube.com/watch?v=_k8tkIo59Fg
https://www.youtube.com/watch?v=GwxfgZ2fPIE
https://www.youtube.com/watch?v=lZVvfyA0qAc
https://www.youtube.com/watch?v=an9kRPCtHjs
https://www.youtube.com/watch?v=5R3aGuvY5BI
https://www.youtube.com/watch?v=g9bo2nkzZm0
https://www.youtube.com/watch?v=BXC6kB2zPjg
https://www.youtube.com/watch?v=zom2dcXbjJ0
https://www.youtube.com/watch?v=EgG7Mm0bYQE
https://www.youtube.com/watch?v=_WQc-frKiDo
https://www.youtube.com/watch?v=8z7x22PGJTY
https://www.youtube.com/watch?v=lFt5iM9_sZ4
https://www.youtube.com/watch?v=PivPBSJcRcI
https://www.youtube.com/watch?v=y-EPL7LfDC0
https://www.youtube.com/watch?v=x8CnnFLskic
https://www.youtube.com/watch?v=91DIPPYD98Q
https://www.youtube.com/watch?v=fyzXdml8WZk
https://www.youtube.com/watch?v=an9kRPCtHjs
```

**Comment by dirkf** [comment]
This version of yt-dl doesn't expect to be run multi-threaded. Either just run the downloads sequentially, or use a shell script to run independent downloads using the yt-dl program in different directories.
