### ISSUE TITLE
Broken streaming.media.ccc.de support

### ISSUE THREAD

**Issue by mcnesium** [ytdl-org/youtube-dl#29987]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v https://streaming.media.ccc.de/datenspuren21/relive/141
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://streaming.media.ccc.de/datenspuren21/relive/141']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.7 (CPython) - Linux-5.13.12-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 141: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 141: Downloading webpage
[generic] 141: Extracting information
ERROR: Unsupported URL: https://streaming.media.ccc.de/datenspuren21/relive/141
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/generic.py", line 3520, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://streaming.media.ccc.de/datenspuren21/relive/141
```

## Description

`youtube-dl -g`  will not find the actual streaming-url of the video content on https://streaming.media.ccc.de

**Comment by dirkf** [comment]
The link in this example is in plain sight (and not exactly a streaming link, either), so yt-dl is not needed.

In the browser, right-click on the download link and Copy Link Location (details of the procedure may vary according to your browser, installed extensions, etc -- refer to the browser help).

**Comment by mcnesium** [comment]
Sorry, I was not aware of a yt-dl policy to only support sites with obfuscated streaming addresses.

Actually I was aiming at being able to do `youtube-dl -g https://streaming.media.ccc.de/datenspuren21/gs` to get the live streaming URL `https://cdn.c3voc.de/hls/s4/native_hd.m3u8`. But since [this conference](https://datenspuren.de/2021/) is only this weekend, I decided to not use the live stream page as an example, because when people process this issue at some time in the future, there will not be a stream anymore.

**Comment by dirkf** [comment]
I don't think there's a policy, but practically, as releases have stalled for now, you have more chance of getting the URL from the browser than having it supported in yt-dl.

Having said that, the generic extractor might do a better job of finding the URL(s).

Apparently the live streaming links are in the Formats tab under the video.
