### ISSUE TITLE
No video format found

### ISSUE THREAD

**Issue by auscia** [ytdl-org/youtube-dl#30038]
C:\dplay>youtube-dl https://www.raiplay.it/video/2013/04/Luca-Massari-Un-tassista-perbene---Un-giorno-in-Pretura-del-130413-11557453-276c-4734-9610-fe82693b85f3.html --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.raiplay.it/video/2013/04/Luca-Massari-Un-tassista-perbene---Un-giorno-in-Pretura-del-130413-11557453-276c-4734-9610-fe82693b85f3.html', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Proxy map: {}
[RaiPlay] 11557453-276c-4734-9610-fe82693b85f3: Downloading video JSON
[RaiPlay] 11557453-276c-4734-9610-fe82693b85f3: Downloading XML metadata for platform mon
[RaiPlay] 11557453-276c-4734-9610-fe82693b85f3: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[RaiPlay] 11557453-276c-4734-9610-fe82693b85f3: Downloading XML metadata for platform flash
[RaiPlay] 11557453-276c-4734-9610-fe82693b85f3: Downloading XML metadata for platform native
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\rai.py", line 174, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found;

**Comment by dirkf** [comment]
Works for me. Perhaps RAI failed to renew a certificate (use `--no-check-certificate` to bypass such an error, if you accept the "risk") and have now done so?

**Comment by auscia** [comment]
right option! Thank you! ;-D

**Comment by dirkf** [comment]
This may be related: https://go.theregister.com/feed/www.theregister.com/2021/09/30/lets_encrypt_xero_slack_outages/.
