### ISSUE TITLE
UnsupportedError: Unsupported URL: https://app.konf.co/event/nV9LOoiQ/session/4675?wvideo=4nh2gmql2j

### ISSUE THREAD

**Issue by chris2614** [ytdl-org/youtube-dl#30041]
## Checklist

- [x ] I'm reporting a new site support request
- [x ] I've verified that I'm running youtube-dl version **2021.06.06**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that none of provided URLs violate any copyrights
- [x ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

## Description

WRITE DESCRIPTION HERE
**************************************************************

Verbose output is here: (version is 2021.06.06) - thanks

chris@aranda:/media/chris/One Touch
$ youtube-dl -v https://app.konf.co/event/nV9LOoiQ/session/4675?wvideo=4nh2gmql2j
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://app.konf.co/event/nV9LOoiQ/session/4675?wvideo=4nh2gmql2j']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.13 (CPython) - Linux-4.19.0-5-amd64-x86_64-with-MX-18.3-Continuum
[debug] exe versions: ffmpeg 3.3.4-1mx17, ffprobe 3.3.4-1mx17, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 4675?wvideo=4nh2gmql2j: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 4675?wvideo=4nh2gmql2j: Downloading webpage
[generic] 4675?wvideo=4nh2gmql2j: Extracting information
ERROR: Unsupported URL: https://app.konf.co/event/nV9LOoiQ/session/4675?wvideo=4nh2gmql2j
Traceback (most recent call last):
  File "/home/chris/.local/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 2503, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/home/chris/.local/lib/python2.7/site-packages/youtube_dl/compat.py", line 2571, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/home/chris/.local/lib/python2.7/site-packages/youtube_dl/compat.py", line 2560, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/home/chris/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/chris/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/chris/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/chris/.local/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 3520, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://app.konf.co/event/nV9LOoiQ/session/4675?wvideo=4nh2gmql2j

*********************************************************

**Comment by dirkf** [comment]
1. You've provided example URLs from YouTube rather than the site being proposed.
2. The URL in your log seems to redirect to the event page (once JS is enabled): presumably you need to provide login details.

**Comment by chris2614** [comment]
Thankyou, I will review.

**Comment by chris2614** [comment]
Previous info applies.

Please note that video plays directly in browser from link without needing to provide login details.

https://app.konf.co/event/nV9LOoiQ/session/4675?wvideo=4nh2gmql2j

Something else is occurring???

**Comment by dirkf** [comment]
For me your link always redirects to https://konf.co/event/nV9LOoiQ/go. Possibly a browser compat issue, or might you have a persistent cookie from a previous login?

**Comment by chris2614** [comment]
Yes - good tip - I think I need to work out which cookie - when I try another computer I also get sent to  https://konf.co/event/nV9LOoiQ/go
