### ISSUE TITLE
Cbc gems not working (used to)

### ISSUE THREAD

**Issue by crazytrain411** [ytdl-org/youtube-dl#30043]
.\youtube-dl.exe --verbose -f best https://gem.cbc.ca/media/dino-ranch/s01e18
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'best', 'https://gem.cbc.ca/media/dino-ranch/s01e18']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1-2021-01-01-full_build-www.gyan.dev, ffprobe 4.3.1-2021-01-01-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] Using fake IP 99.241.7.109 (CA) as X-Forwarded-For.
[cbc.ca:watch] d: Downloading XML
[cbc.ca:watch] d: Downloading XML
ERROR: cbc.ca:watch said: We are sorry, but the selected video is currently unavailable.; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\cbc.py", line 436, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\cbc.py", line 261, in _call_api
youtube_dl.utils.ExtractorError: cbc.ca:watch said: We are sorry, but the selected video is currently unavailable.; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
**Reading the error message**, isn't it actually the case that 
>We are sorry, but the selected video is currently unavailable

? Try the page in your browser again.

I believe that the CBC extractor should use the `expected` flag at l.261, as this sort of error isn't attributable to yt-dl itself but just reporting what the site said:
```
-            raise ExtractorError('%s said: %s' % (self.IE_NAME, error_message))
+            raise ExtractorError('%s said: %s' % (self.IE_NAME, error_message), expected=True)
```

**Comment by crazytrain411** [comment]
The link is valid and working in browser, you can try it yourself. YouTube dl is getting tripped up somehow or the site is rejecting it.

**Comment by dirkf** [comment]
The link doesn't work in the UK. The extractor doesn't just scrape the page (there's not enough in it without running JS); it gets the program information from an API call to https://api-cbc.cloud.clearleap.com/cloffice/client/web/browse/d. The API call does return this:
```
<result><errorCode>CL2000</errorCode><status>failure</status><userMessage>We are sorry, but the selected video is currently unavailable.</userMessage><systemMessage>Asset doesn’t exist</systemMessage></result>
```
Which is consistent with the error message, if not with your browsing experience. One of the test videos returns the same, while another returns 'Payment required': so it's not just that the API is consistently returning 'unavailable'.

This needs research by someone in Canada to identify how the browser is now fetching the video vs what the CBC extractor is doing.

There is something wrong, if not magical, about the way the API is called, as it makes two attempts and 
* returns the second result if both work, or
* returns the first result if only the first worked, or
* returns the second result if the first failed because the device token had expired and the second succeeded, or
* returns None if the first failed for another reason and the second failed.

**Comment by crazytrain411** [comment]
I ran a Fiddler Capture of the video playing in Chrome.

Looks like it goes to https://gem.cbc.ca/media/dino-ranch/s01e18 first, then

A flurry of javascript downloading, then

It Gets some JSON files from

https://gem.cbc.ca/akam/11/7175378c

https://match.adsrvr.org/track/rid?ttd_pid=casale&fmt=json&p=182851 
https://www.cbc.ca/network/includes/stats/master-switch.json 

https://dpm.demdex.net/id?d_visid_ver=4.4.0&d_fieldgroup=MC&d_rtbd=json&d_ver=2&d_orgid=951720B3535680CB0A490D45%40AdobeOrg&d_nsid=0&ts=1633201533517

https://services.radio-canada.ca/ott/cbc-api/v2/assets/dino-ranch/s01e18

https://services.radio-canada.ca/media/validation/v2?appCode=gem&idMedia=942193&manifestType=desktop&output=json&tech=hls 

Then on and on.

Including the full capture here too (I Couldn't attach here)

https://www.filemail.com/d/sqmbtnnnthlftze

**Comment by crazytrain411** [comment]
Looks like this works with yt-dlp

**Comment by mshiels** [comment]
Totally new api, but yes yt-dlp seems to work better for me in a number of situations for major US streaming channels.

**Comment by crazytrain411** [comment]
Im a bit  confused, why do we have these two streams when only one is updated and works? Should we officially retire this one and point to yt-dlp? I only found out about it today  because of this issue reading other issues.

**Comment by nicolaasjan** [comment]
> Should we officially retire this one and point to yt-dlp? I only found out about it today because of this issue reading other issues.

Yes, this issue was [fixed](https://github.com/yt-dlp/yt-dlp/pull/1013) 2 weeks ago in [yt-dlp](https://github.com/yt-dlp/yt-dlp).

**Comment by dirkf** [comment]
> Im a bit confused, why do we have these two streams when only one is updated and works?

Actually there are 6032 streams, according to GitHub, as well as 416 based on yt-dlp.

The main reason for not adopting yt-dlp is that your platform doesn't support Python 3.6+ or some other new dependency of yt-dlp.

**Comment by 89z** [comment]
> The link doesn't work in the UK

@dirkf I have an interest in this site, so I looked into this.

The web client [1] wont even allow you to create an account:

> Accounts cannot be created outside of Canada.

but the Android client [2] allows you to create an account with no problems. Further, I found the media request works, as long as you add `--geo-bypass-country CA` (X-Forwarded-For):

~~~
GET /media/validation/v2?appCode=gem&idMedia=929078&manifestType=mobile&output=json&tech=hls HTTP/1.1
Host: services.radio-canada.ca
x-claims-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJIYXNIRCI6IkZhbHNlIiwiV...
X-Forwarded-For: 99.246.97.250
~~~

1. https://gem.cbc.ca/join-now
2. https://play.google.com/store/apps/details?id=ca.cbc.android.cbctv

**Comment by 89z** [comment]
If it helps, I have now documented the login process:

https://github.com/89z/mech/tree/e668f84e/research/cbc

as well as added a reference for the country IP blocks.
