### ISSUE TITLE
southpark.de broken

### ISSUE THREAD

**Issue by Tabascl** [ytdl-org/youtube-dl#30059]
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.southpark.de/folgen/2bf9a5/south-park-hashtag-aufwaermen-staffel-18-ep-9', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22000
[debug] exe versions: none
[debug] Proxy map: {}
[generic] south-park-hashtag-aufwaermen-staffel-18-ep-9: Requesting header
WARNING: Falling back on generic information extractor.
[generic] south-park-hashtag-aufwaermen-staffel-18-ep-9: Downloading webpage
[generic] south-park-hashtag-aufwaermen-staffel-18-ep-9: Extracting information
ERROR: Unsupported URL: https://www.southpark.de/folgen/2bf9a5/south-park-hashtag-aufwaermen-staffel-18-ep-9
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\generic.py", line 3520, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.southpark.de/folgen/2bf9a5/south-park-hashtag-aufwaermen-staffel-18-ep-9
```

## Description

I suspect that the URL's for southpark.de changed again. I tried fixing it by myself, but then the MTVServicesInfoExtracter, which the SouthParkDE extractor derives from, fails.

URL's I tried:
- https://www.southpark.de/folgen/2bf9a5/south-park-hashtag-aufwaermen-staffel-18-ep-9

But this is happening with every episode.

**Comment by dirkf** [comment]
https://github.com/yt-dlp/yt-dlp/pull/812 should give some hints as to what needs changing.

**Comment by sewe** [comment]
This affects not only the German-language episodes offered by southpark.de (whose URLs like like https://www.southpark.de/folgen/yy0vjs/south-park-das-pandemie-special-staffel-24-ep-1), but also the English-language ones (https://www.southpark.de/en/episodes/vrwkb7/south-park-pajama-day-season-25-ep-1). Hope this helps.
