### ISSUE TITLE
urlopen error EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by alectprasad** [ytdl-org/youtube-dl#30051]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
 youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 --external-downloader aria2c --external-downloader-args "-j 8 -s 8 -x 8 -k 5M" --cookies youtube.com_cookies.txt -v https://www.youtube.com/watch?v=I5jgN3NtW6s
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio', '--merge-output-format', 'mp4', '--external-downloader', 'aria2c', '--external-downloader-args', '-j 8 -s 8 -x 8 -k 5M', '--cookies', 'youtube.com_cookies.txt', '-v', 'https://www.youtube.com/watch?v=I5jgN3NtW6s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.10 (CPython) - Linux-4.4.0-22000-Microsoft-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube] I5jgN3NtW6s: Downloading webpage
[youtube] I5jgN3NtW6s: Downloading MPD manifest
[debug] Invoking downloader on 'https://r3---sn-3jja-jv3s.googlevideo.com/videoplayback?expire=1633364288&ei=4NRaYamCG8DP4-EP962UwAE&ip=103.161.144.87&id=o-AIbPzm_RW5Xxlj3glct9WTlhAG9KSAtHRrq-DXiRwOMJ&itag=136&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=youtube&requiressl=yes&mh=Ca&mm=31%2C29&mn=sn-3jja-jv3s%2Csn-h5576n7k&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=24&initcwndbps=935000&vprv=1&mime=video%2Fmp4&ns=CT67IWMAMzudeZIEz8QphoEG&gir=yes&clen=95004798&otfp=1&dur=573.989&lmt=1624517067634489&mt=1633342373&fvip=3&keepalive=yes&fexp=24001373%2C24007246&beids=9466586&c=WEB&txp=1211224&n=pSwEixn3HTgSpa1-&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRAIgZ_fifGeuKzzc7l6paocZNDjWres9O2cxfUI3LNI29pYCIB9Qe02fiFRYHU5NRV6yyUew-YIzsmVMdc2L6efQRp3x&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgFw-RJaAvLwpvyCom6o4AqmNCnbfy1-nlvu-VwZABowUCIBa_pfhuSEYUoEM6A4iraGTIOEhnVEUwOSOWMSV2TFrb'
[download] Resuming download at byte 3033445
ERROR: unable to download video data: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1421, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 1970, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/utils.py", line 2735, in https_open
    return self.do_open(functools.partial(
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>
```

## Description

The above URL is an example but it's happened with numerous other videos on youtube

**Comment by dirkf** [comment]
There's some sort of network error between yt-dl and YT, probably closer to you.

The `--external-downloader ...` specified is not being used for the selected format.
