### ISSUE TITLE
[CBS] Could not find XML element title

### ISSUE THREAD

**Issue by 2011** [ytdl-org/youtube-dl#30066]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v 'https://www.paramountplus.com/shows/survivor/video/Rcmd9CGvysrl13uSff93up_SnD5RzVfH/survivor-my-million-dollar-mistake/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--restrict-filenames', '-o', '%(title)s-%(id)s-%(uploader)s.%(ext)s', '-w', '-v', 'https://www.paramountplus.com/shows/survivor/video/Rcmd9CGvysrl13uSff93up_SnD5RzVfH/survivor-my-million-dollar-mistake/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.6 (CPython) - Linux-5.10.52-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[CBS] Rcmd9CGvysrl13uSff93up_SnD5RzVfH: Downloading XML
ERROR: Could not find XML element title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/cbs.py", line 115, in _real_extract
    return self._extract_video_info(content_id)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/cbs.py", line 65, in _extract_video_info
    title = xpath_text(video_data, 'videoTitle', 'title', True)
  File "/usr/lib/python3.9/site-packages/youtube_dl/utils.py", line 1911, in xpath_text
    n = xpath_element(node, xpath, name, fatal=fatal, default=default)
  File "/usr/lib/python3.9/site-packages/youtube_dl/utils.py", line 1904, in xpath_element
    raise ExtractorError('Could not find XML element %s' % name)
youtube_dl.utils.ExtractorError: Could not find XML element title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Worked fine in the past (and the first two episodes of this season still work), but the latest episode does not.

**Comment by dirkf** [comment]
I get the same API result in UK but the target URL redirects to a "Paramount+ coming soon to your region" page so it's not possible to reproduce the item playing in the browser.

@2011, you checked the statement that the URL played in the browser for you. Can you confirm that? Was any special procedure needed (login, geo-bypass, etc)?

**Comment by october262** [comment]
> This issue is not specific to the one particular episode of Survivor but instead appears to be the majority of new content (but definitely not all) added to Paramount+ on or after 10/4/2021. Some more examples URLs that exhibit the same behavior (all episodes that aired on or after 10/4/2021:
> 
> https://www.paramountplus.com/shows/bull/video/TUT_4UVB87huHEOfPCjMkxOW_Xe1hNWw/bull-gone
> 
> https://www.paramountplus.com/shows/ncis/video/LzcJLBA2OGq_fE1bDD3NF7lx_zGEyt3L/ncis-road-to-nowhere
> 
> https://www.paramountplus.com/shows/csi-vegas/video/ct82smMrQDbogrBqISHZEJKj3IUOI1yo/csi-vegas-legac
> 
> https://www.paramountplus.com/shows/fbi-most-wanted/video/xKRZ7nMYi0i9WjKk5yUBwIPmmEVRrXvM/fbi-most-wanted-tough-love/

can confirm all 4 of your test URLs work with yt-dlp

**Comment by dirkf** [comment]
Also see #29564.

**Comment by superclarkk** [comment]
Another example...

```
youtube-dl --verbose https://www.cbsnews.com/video/paul-mccartney-the-compromise-inside-the-epidemic/
[debug] System config: ['-o', '/path/to/youtube-dl/%(extractor)s/%(series)s/%(series)s-%(uploader)s-%(title)s.%(ext)s', '--write-sub', '--write-auto-sub', '--sub-lang', 'en,it']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.cbsnews.com/video/paul-mccartney-the-compromise-inside-the-epidemic/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.10 (CPython) - Linux-5.11.0-38-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[cbsnews] paul-mccartney-the-compromise-inside-the-epidemic: Downloading webpage
[cbsnews] 81Vb59Y_YNG_XzqL_SV7AARydZLiXNQv: Downloading XML
ERROR: Could not find XML element title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/3rdparty/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/3rdparty/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/3rdparty/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/3rdparty/youtube-dl/youtube-dl/youtube_dl/extractor/cbsnews.py", line 108, in _real_extract
    return self._extract_video_info(item['mpxRefId'], 'cbsnews')
  File "/usr/local/bin/3rdparty/youtube-dl/youtube-dl/youtube_dl/extractor/cbs.py", line 65, in _extract_video_info
    title = xpath_text(video_data, 'videoTitle', 'title', True)
  File "/usr/local/bin/3rdparty/youtube-dl/youtube-dl/youtube_dl/utils.py", line 1911, in xpath_text
    n = xpath_element(node, xpath, name, fatal=fatal, default=default)
  File "/usr/local/bin/3rdparty/youtube-dl/youtube-dl/youtube_dl/utils.py", line 1904, in xpath_element
    raise ExtractorError('Could not find XML element %s' % name)
youtube_dl.utils.ExtractorError: Could not find XML element title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30197

**Comment by jefft666** [comment]
Se also [30247](https://github.com/ytdl-org/youtube-dl/issues/30247)

**Comment by 89z** [comment]
Ive been ignoring these as they require sign in, but if someone can provide credentials I can look into fixing it. If you want to, run the following command and reply back with the output:

~~~
echo USER:PASS | age -a -r age1zkz9g0kld97vs826j0r7p3ghvz3zcyd4tcqr2vrxpt0uux7mkycsl77hy6
~~~

https://github.com/FiloSottile/age

**Comment by jefft666** [comment]
Maybe just look at the same code in YT-DLP and see what they did to fix it?

**Comment by 89z** [comment]
@jefft666 I am not going to implement a fix on something I cant even test.

**Comment by dirkf** [comment]
> Maybe just look at the same code in YT-DLP and see what they did to fix it?

Done it. Feel free to test PR #30085 as linked above.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30417

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30491

**Comment by 89z** [comment]
The patch seems to work for all the videos on this page:

cbs.com/shows/survivor/video/EktRdacCXDsJo8Qqyw18Rg26tLwfzk4N/survivor-juggling-chainsaws
https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/09/21/1951002179554/CBS_SURVIVOR_4102_PRORES_2997_846322_,503,4628,3128,2228,1628,848,000.mp4.csmil/master.m3u8?hdnea=acl=/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/09/21/1951002179554/CBS_SURVIVOR_4102_PRORES_2997_846322_*~exp=1646520979~hmac=598cbf18d8261a446978746b7b26197016dd1ae3b9e8827b7ed540f7461bcbaa

cbs.com/shows/survivor/video/Rcmd9CGvysrl13uSff93up_SnD5RzVfH/survivor-my-million-dollar-mistake
https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/09/28/1953791555546/CBS_SURVIVOR_4103_PRORES_2997_873188_,503,4628,3128,2228,1628,848,000.mp4.csmil/master.m3u8?hdnea=acl=/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/09/28/1953791555546/CBS_SURVIVOR_4103_PRORES_2997_873188_*~exp=1646520980~hmac=506b72a271405ef1cf49414573f130f418015369d5e6842d0115aff0c8494aa9

paramountplus.com/shows/bull/video/TUT_4UVB87huHEOfPCjMkxOW_Xe1hNWw/bull-gone
https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/09/29/1954671683728/CBS_BULL_601_PRORES_2398_881248_,503,4628,3128,2228,1628,848,000.mp4.csmil/master.m3u8?hdnea=acl=/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/09/29/1954671683728/CBS_BULL_601_PRORES_2398_881248_*~exp=1646520980~hmac=fac5513eab1a70c0eb3c74909b68dd10a8fb47843ded6ad6eaeb834f54729315

paramountplus.com/shows/csi-vegas/video/ct82smMrQDbogrBqISHZEJKj3IUOI1yo/csi-vegas-legac
https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/09/29/1954245699947/CBS_CSI_VEGAS_101_UHD_FIX_R1_1122829_,503,4628,3128,2228,1628,848,000.mp4.csmil/master.m3u8?hdnea=acl=/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/09/29/1954245699947/CBS_CSI_VEGAS_101_UHD_FIX_R1_1122829_*~exp=1646520980~hmac=4596d6d806f49db22f6c11c350e293cd94b7ddb6000eddfa8a70b388d17b8b2a

paramountplus.com/shows/fbi-most-wanted/video/xKRZ7nMYi0i9WjKk5yUBwIPmmEVRrXvM/fbi-most-wanted-tough-love
https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/09/28/1953787459869/CBS_FBI_MW_303_WB_2398_917161_,503,4628,3128,2228,1628,848,000.mp4.csmil/master.m3u8?hdnea=acl=/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/09/28/1953787459869/CBS_FBI_MW_303_WB_2398_917161_*~exp=1646520981~hmac=6660382837a910759b4b1ee631a40934cdc0e6dece605de4d45c6261c3ada771

paramountplus.com/shows/ncis/video/LzcJLBA2OGq_fE1bDD3NF7lx_zGEyt3L/ncis-road-to-nowhere
https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/09/28/1953779779705/CBS_NCIS_421_2398_865739_,503,4628,3128,2228,1628,848,000.mp4.csmil/master.m3u8?hdnea=acl=/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/09/28/1953779779705/CBS_NCIS_421_2398_865739_*~exp=1646520981~hmac=36e0ed5be142a3edd34d9e0bb2e5a8d68c3535cca16e89b96de3212964d87752

paramountplus.com/shows/survivor/video/Rcmd9CGvysrl13uSff93up_SnD5RzVfH/survivor-my-million-dollar-mistake
https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/09/28/1953791555546/CBS_SURVIVOR_4103_PRORES_2997_873188_,503,4628,3128,2228,1628,848,000.mp4.csmil/master.m3u8?hdnea=acl=/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/09/28/1953791555546/CBS_SURVIVOR_4103_PRORES_2997_873188_*~exp=1646520981~hmac=e2af427ea1f948ab2708faaefe5d22c144eda52503f329f4a3630b53637a63a4

but it does fail with some others:
paramountplus.com/shows/the-harper-house/video/eyT_RYkqNuH_6ZYrepLtxkiPO1HA7dIU/the-harper-house-the-harper-house
