### ISSUE TITLE
youtube-dl stopped working on unraid...

### ISSUE THREAD

**Issue by LVLAaron** [ytdl-org/youtube-dl#30123]
I've run youtube-dl on my unraid system for quite some time, but I'm afraid something got updated and now receive the following error when running youtube-dl. I could use some help trying to understand where to look. 

```
root@Tower:/mnt/user/YouTubeArchive# youtube-dl
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib64/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib64/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib64/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib64/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib64/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib64/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 16, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 15, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/options.py", line 8, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/__init__.py", line 3, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 10, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 30, in <module>
  File "/usr/lib64/python2.7/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: libssl.so.1: cannot open shared object file: No such file or directory
root@Tower:/mnt/user/YouTubeArchive# 
```

**Comment by 89z** [comment]
What is unraid?

**Comment by dirkf** [comment]
If your NAS has directories with '64' in the names, maybe it should meet Python 3?

Regarding YT download rates, see #29326 and https://github.com/ytdl-org/youtube-dl/issues/30097#issuecomment-946231355.
