### ISSUE TITLE
vk.com: Unable to login, incorrect username and/or password

### ISSUE THREAD

**Issue by olbrichj** [ytdl-org/youtube-dl#30163]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --write-thumbnail -u "REDACTED" -p "REDACTED" -i "https://vk.com/video143790756_162105035" --verbose
[debug] System config: []
[debug] User config: ['-o', '~/Movies/%(title)s/%(title)s-%(id)s.%(ext)s', '--download-archive', '~/.config/youtube-dl/downloaded.txt']
[debug] Custom config: []
[debug] Command-line args: ['--write-thumbnail', '-u', 'PRIVATE', '-p', 'PRIVATE', '-i', 'https://vk.com/video143790756_162105035', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.7 (CPython) - macOS-11.4-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[vk] Downloading login page
[vk] Logging in
ERROR: Unable to login, incorrect username and/or password
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 533, in extract
    self.initialize()
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 437, in initialize
    self._real_initialize()
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/vk.py", line 63, in _real_initialize
    self._login()
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/vk.py", line 59, in _login
    raise ExtractorError(
youtube_dl.utils.ExtractorError: Unable to login, incorrect username and/or password
```

## Description

For a few days now every now and then the login didn't work with the above problem. Now it's 100% of all trys. Manual login still works, so the credentials are correct.

**Comment by sildvauresberg** [comment]
I faced this problem today, but due to vk.com specifics, I was able to download videos without login/password/cookies.

**Comment by AlexIs387** [comment]
> Maybe you can provide your [logged-in browser session cookies](https://github.com/ytdl-org/youtube-dl#user-content-i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser) instead?

And exactly how do I do that? I don't understand what it says on that link.
