### ISSUE TITLE
ERROR: unable to download video data: Remote end closed connection without response

### ISSUE THREAD

**Issue by arabesc** [ytdl-org/youtube-dl#30189]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--retries', '100', '--fragment-retries', '200', '--recode-video', 'mkv', '-k', 'https://www.youtube.com/watch?v=pxhvGk81Q_4']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.7 (CPython) - macOS-12.0.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://192.168.0.1:3128', 'https': 'http://192.168.0.1:3128'}
[youtube] pxhvGk81Q_4: Downloading webpage
[youtube] pxhvGk81Q_4: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1635907399/ei/56KBYeDRM_6E6dsPkvSWuA4/ip/46.242.8.5/id/a7186f1a4f3543fe/source/youtube/requiressl/yes/playback_host/r1---sn-gvnuxaxjvh-c35s.googlevideo.com/mh/69/mm/31%2C29/mn/sn-gvnuxaxjvh-c35s%2Csn-gvnuxaxjvh-n8vr/ms/au%2Crdu/mv/m/mvi/1/pl/22/tx/24008108/txs/23997970%2C24008108/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/gcr/ru/initcwndbps/1630000/vprv/1/mt/1635885411/fvip/1/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cgcr%2Cvprv%2Citag/sig/AOq0QJ8wRQIgGipyoLHzZvt3E-wK5z94OdsbRZafVNzW8Ho0rzQF-twCIQCR-sfDHXxEEjw61FvayNL3Oi2IrNAbXkJ16_HgAsCrPA%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIhAPX0P-MAk0obe4YhNWdrkpG__2E-TwS2bMdPmmqf-djxAiABdWeExNrVZJuoeVZ7MpOBlB-etxGXfFABLGIYji3uow%3D%3D'
[dashsegments] Total fragments: 1310
[download] Destination: Лекция №20 'Особенности поведения и внутривидовое взаимодействие акул'-pxhvGk81Q_4.f247.webm
[download]  55.5% of ~280.07MiB at 15.66MiB/s ETA 01:20ERROR: unable to download video data: Remote end closed connection without response
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 1970, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/downloader/dash.py", line 48, in real_download
    success, frag_content = self._download_fragment(ctx, fragment_url, info_dict)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/downloader/fragment.py", line 104, in _download_fragment
    success = ctx['dl'].download(fragment_filename, fragment_info_dict)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/utils.py", line 2735, in https_open
    return self.do_open(functools.partial(
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1350, in do_open
    r = h.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 288, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

## Description

There is unhandled exception.

**Comment by 89z** [comment]
Thats a DASH manifest video, I dont know if its supported by this package.

**Comment by kikuyan** [comment]
Cannot reproduce. Should be a temporary network error.
```
$ youtube-dl https://www.youtube.com/watch?v=pxhvGk81Q_4 --ignore-config --id
[youtube] pxhvGk81Q_4: Downloading webpage
[youtube] pxhvGk81Q_4: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[dashsegments] Total fragments: 1310
[download] Destination: pxhvGk81Q_4.f247.webm
[download] 100% of 301.64MiB in 43:35
[download] Destination: pxhvGk81Q_4.f140.m4a
[download] 100% of 107.69MiB in 25:27
[ffmpeg] Merging formats into "pxhvGk81Q_4.mkv"
Deleting original file pxhvGk81Q_4.f247.webm (pass -k to keep)
Deleting original file pxhvGk81Q_4.f140.m4a (pass -k to keep)
```

**Comment by dirkf** [comment]
It certainly is, but apparently there is some network, proxy or server problem in the quoted log:
```
[dashsegments] Total fragments: 1310
[download] Destination: Лекция №20 'Особенности поведения и внутривидовое взаимодействие акул'-pxhvGk81Q_4.f247.webm
[download] 100% of 301.64MiB in 18:03
```
See also #17533.

**Comment by arabesc** [comment]
I expect that according to `--retries` switch it will try to reconnect instead of throwing an unhandled exception.

**Comment by dirkf** [comment]
The exception is thrown by the HTTP client library, and these `HTTPException`s aren't trapped in the HTTP downloader, only certain HTTP server codes and socket errors. The code doesn't give any rationale of the error handling strategy.

See  https://github.com/ytdl-org/youtube-dl/issues/29672#issuecomment-900332002 for similar background.

One might try tweaking `downloader/http.py` by inserting this before line 190:
```
            except http.client.HTTPException as err:
            # Python 2: except httplib.HTTPException as err:
                raise RetryDownload(err)
```
If you do this, please let us know how it goes.
