### ISSUE TITLE
CBS ghosts episode 5 fail

### ISSUE THREAD

**Issue by iknowu812** [ytdl-org/youtube-dl#30197]
## Checklist

- [x ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.06.06**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
~/Downloads/ghosts$ ~/bin/youtube-dl/youtube-dl --verbose https://www.cbs.com/shows/ghosts/video/UKvheucnBSOwnIfXsa3KJ70ydG8_GxUO/ghosts-halloween/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.cbs.com/shows/ghosts/video/UKvheucnBSOwnIfXsa3KJ70ydG8_GxUO/ghosts-halloween/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-9-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0, rtmpdump 2.4
[debug] Proxy map: {}
[CBS] UKvheucnBSOwnIfXsa3KJ70ydG8_GxUO: Downloading XML
ERROR: Could not find XML element title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/kdibble/bin/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kdibble/bin/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/kdibble/bin/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/kdibble/bin/youtube-dl/youtube-dl/youtube_dl/extractor/cbs.py", line 115, in _real_extract
    return self._extract_video_info(content_id)
  File "/home/kdibble/bin/youtube-dl/youtube-dl/youtube_dl/extractor/cbs.py", line 65, in _extract_video_info
    title = xpath_text(video_data, 'videoTitle', 'title', True)
  File "/home/kdibble/bin/youtube-dl/youtube-dl/youtube_dl/utils.py", line 1911, in xpath_text
    n = xpath_element(node, xpath, name, fatal=fatal, default=default)
  File "/home/kdibble/bin/youtube-dl/youtube-dl/youtube_dl/utils.py", line 1904, in xpath_element
    raise ExtractorError('Could not find XML element %s' % name)
youtube_dl.utils.ExtractorError: Could not find XML element title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

Download fails per above.

**Comment by kikuyan** [comment]
> ERROR: Could not find XML element title

Duplicate #30066

**Comment by 89z** [comment]
I cant even get that to play in a browser, I get

> OOPS! We're having some trouble playing this video. Please try again. If you continue to experience issues, check your internet connection or restart your router.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30417

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30066
