### ISSUE TITLE
Cannot extract certain podcast from podcast.apple.com

### ISSUE THREAD

**Issue by ejoebstl** [ytdl-org/youtube-dl#30216]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--skip-download', 'https://podcasts.apple.com/podcast/4-on-the-horn-with-adam-kovacevich/id1585883787?i=1000539806607', '--write-info-json', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.6 (CPython) - Linux-5.13.9-100.fc33.x86_64-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2
[debug] Proxy map: {}
[ApplePodcasts] 1000539806607: Downloading webpage
ERROR: Unable to extract ember data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/applepodcasts.py", line 42, in _real_extract
    ember_data = self._parse_json(self._search_regex(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract ember data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Attempting to use youtube-dl on [this page](https://podcasts.apple.com/podcast/4-on-the-horn-with-adam-kovacevich/id1585883787?i=1000539806607). Did not work, log output asked me to post here. 

Other podcasts on podcast.apple.com work.

**Comment by dirkf** [comment]
The test podcast from the extractor doesn't work either.

This patch appears to fix the new format, which doesn't have JSON in a `<script>` element with `id` `shoebox-ember-data-store` but instead a somewhat different JSON format in a `<script>` element with `id` `shoebox-media-api-cache-amp-podcasts`. 
```
--- old/youtube_dl/extractor/applepodcasts.py
+++ new/youtube_dl/extractor/applepodcasts.py
@@ -3,7 +3,9 @@
 
 from .common import InfoExtractor
 from ..utils import (
+    clean_html,
     clean_podcast_url,
+    get_element_by_class,
     int_or_none,
     parse_iso8601,
     try_get,
@@ -14,15 +16,15 @@
     _VALID_URL = r'https?://podcasts\.apple\.com/(?:[^/]+/)?podcast(?:/[^/]+){1,2}.*?\bi=(?P<id>\d+)'
     _TESTS = [{
         'url': 'https://podcasts.apple.com/us/podcast/207-whitney-webb-returns/id1135137367?i=1000482637777',
-        'md5': 'df02e6acb11c10e844946a39e7222b08',
+        'md5': '41dc31cd650143e530d9423b6b5a344f',
         'info_dict': {
             'id': '1000482637777',
             'ext': 'mp3',
             'title': '207 - Whitney Webb Returns',
-            'description': 'md5:13a73bade02d2e43737751e3987e1399',
+            'description': u'md5:75ef4316031df7b41ced4e7b987f79c6',
             'upload_date': '20200705',
-            'timestamp': 1593921600,
-            'duration': 6425,
+            'timestamp': 1593932400,
+            'duration': 6454,
             'series': 'The Tim Dillon Show',
         }
     }, {
@@ -39,17 +41,36 @@
     def _real_extract(self, url):
         episode_id = self._match_id(url)
         webpage = self._download_webpage(url, episode_id)
-        ember_data = self._parse_json(self._search_regex(
-            r'id="shoebox-ember-data-store"[^>]*>\s*({.+?})\s*<',
-            webpage, 'ember data'), episode_id)
-        ember_data = ember_data.get(episode_id) or ember_data
-        episode = ember_data['data']['attributes']
+        episode_data = {}
+        ember_data = {}
+        amp_data = self._parse_json(self._search_regex(
+            r'(?s)id="shoebox-media-api-cache-amp-podcasts"[^>]*>\s*({.+?})\s*<',
+            webpage, 'AMP data', default='{}'), episode_id, fatal=False) or {}
+        amp_data = try_get(amp_data,
+                           lambda a: self._parse_json(
+                               next(a[x] for x in iter(a) if episode_id in x),
+                               episode_id),
+                           dict) or {}
+        amp_data = amp_data.get('d') or []
+        episode_data = try_get(
+            amp_data, 
+            lambda a: next(x for x in a 
+                           if x['type'] == 'podcast-episodes' and x['id'] == episode_id),
+            dict)
+        if not episode_data:
+            ember_data = self._parse_json(self._search_regex(
+                r'(?s)id="shoebox-ember-data-store"[^>]*>\s*({.+?})\s*<',
+                webpage, 'ember data'), episode_id) or {}
+            ember_data = ember_data.get(episode_id) or ember_data
+            episode_data = try_get(ember_data, lambda x: x['data'], dict)
+        episode = episode_data['attributes']
         description = episode.get('description') or {}
 
         series = None
-        for inc in (ember_data.get('included') or []):
+        for inc in (amp_data or ember_data.get('included') or []):
             if inc.get('type') == 'media/podcast':
                 series = try_get(inc, lambda x: x['attributes']['name'])
+        series = series or clean_html(get_element_by_class('podcast-header__identity', webpage))
 
         return {
             'id': episode_id,
```

**Comment by 89z** [comment]
I have an alternate tool that works:

~~~
apple https://podcasts.apple.com/podcast/4-on-the-horn-with-adam-kovacevich/id1585883787?i=1000539806607
~~~

https://github.com/89z/mech

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30250

**Comment by 89z** [comment]
I have an alternate tool that works:

~~~
PS C:\> apple.exe -i https://podcasts.apple.com/podcast/4-on-the-horn-with-adam-kovacevich/id1585883787?i=1000539806607
GET https://podcasts.apple.com/podcast/4-on-the-horn-with-adam-kovacevich/id1585883787?i=1000539806607
{ArtistName:Paraag Sarva
AssetURL:https://www.buzzsprout.com/1853079/9437981-4-on-the-horn-with-adam-kovacevich.mp3
Duration:38m24s Name:#4 - On the Horn with Adam Kovacevich
ReleaseDateTime:2021-10-26T19:00:00Z}
~~~

https://github.com/89z/mech

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30413

**Comment by martin-ward** [comment]
For this particular podcast (and other Apple podcasts I have tried) if you download the web page "https://podcasts.apple.com/podcast/4-on-the-horn-with-adam-kovacevich/id1585883787?i=1000539806607" with wget or some other downloader, then you can find a link to an mp3 file in the page: in this case it is https://www.buzzsprout.com/1853079/9437981-4-on-the-horn-with-adam-kovacevich.mp3

You can then download this mp3 file with wget or some other downloader.

**Comment by dirkf** [comment]
But ... avoiding that sort of palaver is the point of using yt-dl, especially since it extracts metadata beyond the media URL!

**Comment by tpo** [comment]
thanks for merging @dirkf !
