### ISSUE TITLE
Cannot download YouTube membership videos

### ISSUE THREAD

**Issue by yuusakuri** [ytdl-org/youtube-dl#30217]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe -u $env:YOUTUBE_MAILADDRESS -p $env:YOUTUBE_PASSWORD --verbose https://youtu.be/ENU8tSMqxjY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--verbose', 'https://youtu.be/ENU8tSMqxjY']
[debug] Encodings: locale cp1252, fs mbcs, out cp65001, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg n4.3.1-29-g89daac5fe2, ffprobe n4.3.1-29-g89daac5fe2
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
[youtube] ENU8tSMqxjY: Downloading webpage
ERROR: This video is available to this channel's members on level: メン限動画＋ファミ通声優番組のアーカイブ見放題 (or any higher level). Join this channel to get access to members-only content and other exclusive perks.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1713, in _real_extract
youtube_dl.utils.ExtractorError: This video is available to this channel's members on level: メン限動画＋ファミ通声優番 組のアーカイブ見放題 (or any higher level). Join this channel to get access to members-only content and other exclusive perks.
```

## Description

I logged in to that account in the Secret tab of my Chrome browser and confirmed that the video was playable. But youtube-dl cannot download the video.

**Comment by pukkandan** [comment]
username + password dont work for youtube. Pass cookies instead

**Comment by yuusakuri** [comment]
Thank you, I understand. But I hope it is supported.

**Comment by pukkandan** [comment]
Google's bot detection is extremely complex. I doubt it will ever be supported
