### ISSUE TITLE
URPlay not working anymore

### ISSUE THREAD

**Issue by HenrikElofsson** [ytdl-org/youtube-dl#30213]
Downloading content from URPlay has recently stopped working. I downloaded the episode before this one about a week ago, and that worked fine. Watching it in the browser works fine.

~/youtube-dl/youtube-dl/youtube-dl --verbose https://urplay.se/program/221059-jarnvagar-och-arkitektur-55-broadway-i-london
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://urplay.se/program/221059-jarnvagar-och-arkitektur-55-broadway-i-london']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.8 (CPython) - Linux-5.14.15-gentoo-falcon-x86_64-AMD_Ryzen_5_5600X_6-Core_Processor-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1
[debug] Proxy map: {}
[URPlay] 221059: Downloading webpage
ERROR: Unable to extract urplayer data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/henrik/youtube-dl/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/henrik/youtube-dl/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/henrik/youtube-dl/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/henrik/youtube-dl/youtube-dl/youtube-dl/youtube_dl/extractor/urplay.py", line 54, in _real_extract
    accessible_episodes = self._parse_json(self._html_search_regex(
  File "/home/henrik/youtube-dl/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/henrik/youtube-dl/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract urplayer data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
The target metadata is now served as JSON in a `<script>` element with `id` `__NEXT_DATA__`.

This patch seems to work:
```
--- old/youtube_dl/extractor/urplay.py
+++ new/youtube_dl/extractor/urplay.py
@@ -5,6 +5,7 @@
 from ..utils import (
     dict_get,
     int_or_none,
+    try_get,
     unified_timestamp,
 )
 
@@ -23,7 +24,7 @@
             'upload_date': '20171214',
             'series': 'UR Samtiden - Livet, universum och rymdens märkliga musik',
             'duration': 2269,
-            'categories': ['Kultur & historia'],
+            'categories': ['Vetenskap & teknik'],
             'tags': ['Kritiskt tänkande', 'Vetenskap', 'Vetenskaplig verksamhet'],
             'episode': 'Om vetenskap, kritiskt tänkande och motstånd',
         },
@@ -51,9 +52,19 @@
         url = url.replace('skola.se/Produkter', 'play.se/program')
         webpage = self._download_webpage(url, video_id)
         vid = int(video_id)
-        accessible_episodes = self._parse_json(self._html_search_regex(
-            r'data-react-class="routes/Product/components/ProgramContainer/ProgramContainer"[^>]+data-react-props="({.+?})"',
-            webpage, 'urplayer data'), video_id)['accessibleEpisodes']
+        urplayer_json = self._html_search_regex(
+            r'(?s)<script\s[^>]*?id\s*=\s*(?P<q>"|\'|\b)__NEXT_DATA__(?P=q)[^>]*?>\s*(?P<json>\{.+?\})\s*</script>',
+            webpage, 'urplayer data', fatal=False, group='json')
+        if urplayer_json is not None:
+            urplayer_json = try_get(urplayer_json,
+                                    lambda x: self._parse_json(x, video_id, fatal=False)['props']['pageProps'],
+                                    dict)
+        if not urplayer_json:
+            urplayer_json = self._html_search_regex(
+                r'data-react-class="routes/Product/components/ProgramContainer/ProgramContainer"[^>]+data-react-props="({.+?})"',
+                webpage, 'urplayer data')
+            urplayer_json = self._parse_json(urplayer_json, video_id)
+        accessible_episodes = urplayer_json['accessibleEpisodes']
         urplayer_data = next(e for e in accessible_episodes if e.get('id') == vid)
         episode = urplayer_data['title']
         raw_streaming_info = urplayer_data['streamingInfo']['raw']
```

**Comment by Minherre** [comment]
Henrik!

The project Youtube-dl is dead, and has been since june 2021.

Instead go for Svtplay-dl at

https://github.com/spaam/svtplay-dl

Download at

https://svtplay-dl.se/

And also you have the yt-dlp that replaces Youtube-dl, at

https://github.com/yt-dlp/yt-dlp/releases/tag/2021.10.22

**Comment by dirkf** [comment]
Or just apply the patch that I posted, like this for Henrik.
```
(cd ~/youtube-dl/youtube-dl/youtube-dl && patch -p 1 -i path_to_patch_file/patch_file_name)
```
