### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by Rourke101** [ytdl-org/youtube-dl#30237]
Why am I getting this error?

youtube-dl.exe "https://videodelivery.net/[.....] W-3Y3r9FjYA/manifest/video.m3u8" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://videodelivery.net/....W-3Y3r9FjYA/manifest/video.m3u8', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-02-03-1c15111, ffprobe git-2020-02-03-1c15111
[debug] Proxy map: {}
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\__init__.py", line 465, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2069, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\cloudflarestream.py", line 57, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 906, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 312, in loads
TypeError: the JSON object must be str, not 'bytes'

**Comment by 89z** [comment]
Please provide full, unredacted link.

**Comment by Rourke101** [comment]
Can I do it privately?

**Comment by 89z** [comment]
Run this command:

~~~
echo 'https://videodelivery.net/.....W-3Y3r9FjYA/manifest/video.m3u8' |
age -a -r age1zkz9g0kld97vs826j0r7p3ghvz3zcyd4tcqr2vrxpt0uux7mkycsl77hy6
~~~

and comment back here with the output.

https://github.com/FiloSottile/age

**Comment by Rourke101** [comment]
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTDM0a1J6NkdjZHdTRUhQ
RzdwR3VUdENSNFk2alBIYytKUkdsV1NNWXc0CmFSclpHU3V0eldPWGErUG8xWUox
Q3pzZVQ3TlI3bWhaVXVjazBhUm5VMlkKLS0tIHpqdkFKeEo4aWw3aUNtMmhJbm5a
OVFxcDcwY1VVbHhYWjBtbUM4VEY3OEEKJNjeuWuS7XqzMkmnmgYQj1YH35ur7x76
/xKJxv/ZET/9/wvnX35K7Ji+YxpCxRBmDbzV8onQMmAjjMv8JpKSdt7GfkFAlanL
JhjHEWR/sQSu1izyTtC4Qf3jVZjq7mv8tkAZUMZ0qPmxHNGjA/zLkXy71f2SBVNU
HUpHiHNKv7wN+jCFpa6jM5IdE1YPCzyTdngRKd8Ylc+Rab6sacM2OmTMnJ0bt3Sx
z3fnLjbFsetp83re4mvTcQkik2X38zbML+W5tg7h2ItlI79jr0Gphoppl4XZBIoo
tW1oeVxtY9T6ghwgnhiW9ZHiUNzqjbjm06U2ZUQ/v+YF14XhxpX6GO0+H4WYuCmn
oBxyfw/8cqclEuyJexHruR3GrMLjzuM7vHm5ymXiTlPibP3HKeY1wTAkUZ7EMI/a
oDTDrC/99oQjZYpTqDPNLuYkgoTmnbqcejo/nFaLAvG9HSf3zFSDCsjKsZPUn62O
3xrH6HoqNyH8OfXh4PNwYo1DoKJpJS3wZduPqU0H3Nl7kG5aYn6dWxnfi9GVyDho
PcwKMNO8WigBm7kh/cs/Eotqw8+AWgG3E62o5tAUe7FEtg411KND83UCW+EmQzeU
4QNf+xNs+/galSjh1ok/ZJSoE0QDEZZxFkARa8oGAlHAJG6DdO4T2ufliEFG7J5g
CvdFEVI3DrVy7dAUZyAJ/pjhzp+BvULWEeyPGspHDL5aqiZysrqjPjax9R2M4w2V
GNFUWgsiIlCS0tsWBxGKD8v6koHSP6WpcAhjvaue41uoVE2rYi17NWgopogbk13i
HWsobAYKi/JpQRSrZ3CPNU8DOA==
-----END AGE ENCRYPTED FILE-----

**Comment by 89z** [comment]
OK I got the full link. However it seem like a normal M3U, in which case you dont need YouTube-DL. You can just use FFmpeg:

~~~
ffmpeg -i https://videodelivery.net/eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.../manifest/video.m3u8 -c copy out.mp4
~~~

**Comment by Rourke101** [comment]
I did not know ffmpeg could do that!   And I did not know about different flavours of M3Us, ones that need Youtube-dl for it. Where can I read more about that?  Thanks!

**Comment by 89z** [comment]
In general, I dont think you need YouTube-DL for any M3U, its just provided as a convenience, so people can use one tool for everything. Its possible YouTube-DL can handle some M3U encryption that FFmpeg cannot, but I dont think so.
