### ISSUE TITLE
Getting a "Could not find XML element title" on some (but not all) cbs.py downloads.

### ISSUE THREAD

**Issue by jefft666** [ytdl-org/youtube-dl#30247]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
```
../youtube-dl --verbose --cookies ../cookies.txt --write-info-json --add-metadata -o "%(series)s.S%(season_number)02dE%(episode_number)02d.%(title)s.%(height)sp.PMNT.WEB-DL.%(ext)s" "https://www.paramountplus.com/shows/star-trek-prodigy/video/3htV4fvVt4Z8gDZHqlzPOGLSMgcGc_vy/star-trek-prodigy-dreamcatcher/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--cookies', u'../cookies.txt', u'--write-info-json', u'--add-metadata', u'-o', u'%(series)s.S%(season_number)02dE%(episode_number)02d.%(title)s.%(height)sp.PMNT.WEB-DL.%(ext)s', u'https://www.paramountplus.com/shows/star-trek-prodigy/video/3htV4fvVt4Z8gDZHqlzPOGLSMgcGc_vy/star-trek-prodigy-dreamcatcher/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18 (CPython) - Darwin-21.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-103122-g8b83dad825, ffprobe N-103122-g8b83dad825, rtmpdump 2.4
[debug] Proxy map: {}
[CBS] 3htV4fvVt4Z8gDZHqlzPOGLSMgcGc_vy: Downloading XML
ERROR: Could not find XML element title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "../youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "../youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "../youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "../youtube-dl/youtube_dl/extractor/cbs.py", line 115, in _real_extract
    return self._extract_video_info(content_id)
  File "../youtube-dl/youtube_dl/extractor/cbs.py", line 65, in _extract_video_info
    title = xpath_text(video_data, 'videoTitle', 'title', True)
  File "../youtube-dl/youtube_dl/utils.py", line 1911, in xpath_text
    n = xpath_element(node, xpath, name, fatal=fatal, default=default)
  File "../youtube-dl/youtube_dl/utils.py", line 1904, in xpath_element
    raise ExtractorError('Could not find XML element %s' % name)
ExtractorError: Could not find XML element title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```
```

## Description

Having an issue downloading the specific file due to a "Could not find XML element title" error. Other files on the site seem to be working fine.

**Comment by kikuyan** [comment]
Duplicate of #30066 as you noticed, and #30197.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30066

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30066

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30491
