### ISSUE TITLE
Failed to parse JSON (using the tvplay.py extractor)

### ISSUE THREAD

**Issue by kareiva** [ytdl-org/youtube-dl#30243]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://play.tv3.lt/lives/tv3-lt,live-2831094/tv3-vakaro-zinios,programme-3548369', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-80-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[TVPlayHome] 3548369: Downloading JSON metadata
ERROR: 3548369: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/common.py", line 906, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/tvplay.py", line 459, in _real_extract
    urljoin(url, '/sb/public/asset/' + video_id), video_id)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 899, in _download_json
    expected_status=expected_status)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 883, in _download_json_handle
    fatal=fatal), urlh
  File "./youtube-dl/youtube_dl/extractor/common.py", line 910, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: 3548369: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Trying to fetch random news from the TVPlay archive. Example URL:

https://play.tv3.lt/lives/tv3-lt,live-2831094/tv3-vakaro-zinios,programme-3548369

Probably incorrect URL is generated to fetch the metadata (returns HTML instead of JSON).

Also checked the `tvplay.py` extractor:
https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/tvplay.py#L63

The URL used in the above test returns 200 but it's actually a 'not found' page.

**Comment by dirkf** [comment]
The extractor tries to get metadata from https://play.tv3.lt/sb/public/asset/3548369 but this URL format is no longer valid ("UPS ..." presumably "Oops ..."?).

In the browser this `https://play.tv3.lt/api/products/4537452/videos/playlist?platform=BROWSER&videoType=CATCHUP&lang=LT&tenant=AVOD_LT` playlist is fetched whose content does not bode well (DRM):
```
{
  'sources': {
    'DASH': [
      {
        'src': '//cdnlb.tvplayhome.lt/nPVR/eds/GO3_4537452/GO3_LIVE_DASH/TV3_LT_SD.mpd',
        'aspectWidth': 16,
        'aspectHeight': 9
      }
    ],
    'HLS': [
      {
        'src': '//cdnlb.tvplayhome.lt/nPVR/eds/GO3_4537452/GO3_LIVE_HLS/TV3_LT_SD.m3u8',
        'aspectWidth': 16,
        'aspectHeight': 9,
        'cert': 'https://r.static.go3.tv/file/go3/resources/cert/fairplay/amb.cer'
      }
    ],
    'SS': [
      {
        'src': '//cdnlb.tvplayhome.lt/nPVR/eds/GO3_4537452/GO3_LIVE_SS/Manifest?test=.ism/Manifest',
        'aspectWidth': 16,
        'aspectHeight': 9
      }
    ]
  },
  'drm': {
    'FAIRPLAY': {
      'src': 'https://play.tv3.lt/api/products/4537452/drm/fairplay?platform=BROWSER&type=CATCHUP&tenant=AVOD_LT',
      'cert': 'https://r.static.go3.tv/file/go3/resources/cert/fairplay/amb.cer'
    },
    'WIDEVINE': {
      'src': 'https://play.tv3.lt/api/products/4537452/drm/widevine?platform=BROWSER&type=CATCHUP&tenant=AVOD_LT'
    },
    'PLAYREADY': {
      'src': 'https://play.tv3.lt/api/products/4537452/drm/playready?platform=BROWSER&type=CATCHUP&tenant=AVOD_LT'
    }
  }
}
```

**Comment by Vangelis66** [comment]
@dirkf wrote: 

> playlist is fetched, whose content **does not bode well (DRM)**:

You are right, I did try **in a browser** the URI OP included in the description of this issue, 
https://play.tv3.lt/lives/tv3-lt,live-2831094/tv3-vakaro-zinios,programme-3548369
(the site demanded I first disable my adblocker 😠 ), and **cenc** MPEG-DASH streams were loaded: 

![DRM](https://user-images.githubusercontent.com/9669492/142508444-34b69486-501b-4a13-8438-9d73dae76351.JPG)

https://cdnlb.tvplayhome.lt/nPVR/eds/GO3_4537452/GO3_LIVE_DASH/TV3_LT_SD.mpd =>
https://cdn4.tvplayhome.lt/nPVR/eds/GO3_4537452/GO3_LIVE_DASH/TV3_LT_SD.mpd

But, guess what? The `'sources'` streams contained in the **playlistAPI JSON response** you attached are **clear**, i.e. non-DRM 😜 👍 ... E.g., for the HLS master playlist URI, 
`https//cdnlb.tvplayhome.lt/nPVR/eds/GO3_4537452/GO3_LIVE_HLS/TV3_LT_SD.m3u8`,
I get: 
```
youtube-dl -F "https//cdnlb.tvplayhome.lt/nPVR/eds/GO3_4537452/GO3_LIVE_HLS/TV3_LT_SD.m3u8" => 

[generic] TV3_LT_SD: Requesting header
[redirect] Following redirect to https://cdn25.tvplayhome.lt:443/nPVR/eds/GO3_4537452/GO3_LIVE_HLS/TV3_LT_SD.m3u8
[generic] TV3_LT_SD: Requesting header
[generic] TV3_LT_SD: Downloading m3u8 information
[info] Available formats for TV3_LT_SD:
format code               extension  resolution note
audio-AACL-96-Lithuanian  mp4        audio only [lt]
732                       mp4        1024x576    732k , avc1.4d401f, 25.0fps, video only
1368                      mp4        1024x576   1368k , avc1.4d401f, 25.0fps, video only
2428                      mp4        1024x576   2428k , avc1.4d401f, 25.0fps, video only (best)
```
Thus, e.g. 
```
youtube-dl --console-title --hls-prefer-native -c --no-part -f "1368+audio-AACL-96-Lithuanian" "https://cdnlb.tvplayhome.lt/nPVR/eds/GO3_4537452/GO3_LIVE_HLS/TV3_LT_SD.m3u8" -o "TV3_News_20211115_2130.mp4" => 

[generic] TV3_LT_SD: Requesting header
[redirect] Following redirect to https://cdn8.tvplayhome.lt:443/nPVR/eds/GO3_4537452/GO3_LIVE_HLS/TV3_LT_SD.m3u8
[generic] TV3_LT_SD: Requesting header
[generic] TV3_LT_SD: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 300
[download] Destination: TV3_News_20211115_2130.f1368.mp4
[download] 100% of 433.75MiB in 14:46
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 300
[download] Destination: TV3_News_20211115_2130.faudio-AACL-96-Lithuanian.mp4
[download] 100% of 50.93MiB in 06:13
[ffmpeg] Merging formats into "TV3_News_20211115_2130.mp4"
Deleting original file TV3_News_20211115_2130.f1368.mp4 (pass -k to keep)
Deleting original file TV3_News_20211115_2130.faudio-AACL-96-Lithuanian.mp4 (pass -k to keep)
```

**Comment by dirkf** [comment]
In which case this patch appears to do the job, as far as @Vangelis66's example goes.

Apparently the series/episode/etc metadata isn't available from the end-points I'm using, though there is an end-point for subscribers that gives 403 without authentication. Some may be available from the page itself but that requires more Baltic Slavonic skills than I have: no doubt [Letts can do it](https://www.themusicallyrics.com/c/530-cole-porter-lyrics/7524-lets-do-it-lets-fall-in-love-lyrics.html).

--- old/youtube_dl/extractor/tvplay.py
+++ new/youtube_dl/extractor/tvplay.py
@@ -6,6 +6,7 @@
 from .common import InfoExtractor
 from ..compat import (
     compat_HTTPError,
+    compat_str,
     compat_urlparse,
 )
 from ..utils import (
@@ -417,6 +418,8 @@
 
 class TVPlayHomeIE(InfoExtractor):
     _VALID_URL = r'https?://(?:tv3?)?play\.(?:tv3\.lt|skaties\.lv|tv3\.ee)/(?:[^/]+/)*[^/?#&]+-(?P<id>\d+)'
+    _METADATA_URL_TMPL = 'https://play.tv3.lt/api/products/lives/programmes/%s?platform=BROWSER&lang=LT&tenant=AVOD_LT'
+    _PLAYLIST_URL_TMPL = 'https://play.tv3.lt/api/products/%s/videos/playlist?platform=BROWSER&videoType=CATCHUP&lang=LT&tenant=AVOD_LT'
     _TESTS = [{
         'url': 'https://tvplay.tv3.lt/aferistai-n-7/aferistai-10047125/',
         'info_dict': {
@@ -456,37 +459,44 @@
         video_id = self._match_id(url)
 
         asset = self._download_json(
-            urljoin(url, '/sb/public/asset/' + video_id), video_id)
-
-        m3u8_url = asset['movie']['contentUrl']
-        video_id = asset['assetId']
-        asset_title = asset['title']
-        title = asset_title['title']
-
-        formats = self._extract_m3u8_formats(
-            m3u8_url, video_id, 'mp4', 'm3u8_native', m3u8_id='hls')
+            self._METADATA_URL_TMPL % (video_id, ),
+            video_id)
+
+        title = asset['title']
+        programme_id = compat_str(asset['programRecordingId'])
+        pl_url = self._PLAYLIST_URL_TMPL % (programme_id, )
+        pl = self._download_json(pl_url, programme_id) or {}
+        formats = []
+        for tag, src in pl.get('sources').items():
+            src = try_get(src, lambda x: x[0]['src'], compat_str)
+            if not src:
+                continue
+            src = urljoin(pl_url, src)
+            ext = determine_ext(src)
+            if ext == 'mpd':
+                formats.extend(self._extract_mpd_formats(src, programme_id, mpd_id=tag, fatal=False))
+            elif ext == 'ism':
+                formats.extend(self._extract_ism_formats(src, programme_id, ism_id=tag, fatal=False))
+            elif ext == 'm3u8':
+                formats.extend(self._extract_m3u8_formats(src, programme_id, 'mp4', 'm3u8_native', m3u8_id=tag, fatal=False))
         self._sort_formats(formats)
 
-        thumbnails = None
-        image_url = asset.get('imageUrl')
-        if image_url:
-            thumbnails = [{
-                'url': urljoin(url, image_url),
-                'ext': 'jpg',
-            }]
-
-        metadata = asset.get('metadata') or {}
+        description = asset.get('description')
+        thumbnails = [{'id': t_id, 'url': imgs[0]['miniUrl'], } for t_id, imgs in asset.get('images', {}).items()]
+        timestamp = parse_iso8601(asset.get('since'))
+        if timestamp is not None:
+            end_stamp = parse_iso8601(asset.get('till'))
+            duration = end_stamp and (end_stamp - timestamp)
+        else:
+            duration = None
 
         return {
-            'id': video_id,
+            'id': programme_id,
+            'display_id': video_id,
             'title': title,
-            'description': asset_title.get('summaryLong') or asset_title.get('summaryShort'),
+            'description': description,
             'thumbnails': thumbnails,
-            'duration': parse_duration(asset_title.get('runTime')),
-            'series': asset.get('tvSeriesTitle'),
-            'season': asset.get('tvSeasonTitle'),
-            'season_number': int_or_none(metadata.get('seasonNumber')),
-            'episode': asset_title.get('titleBrief'),
-            'episode_number': int_or_none(metadata.get('episodeNumber')),
+            'duration': duration,
+            'timestamp': timestamp,
             'formats': formats,
         }
```

**Comment by 89z** [comment]
Issue should be closed, URL is dead
