### ISSUE TITLE
[TVPlaySportPlusHD] No video formats found

### ISSUE THREAD

**Issue by kotuk** [ytdl-org/youtube-dl#30289]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://cdnlb.tvplayhome.lt/live/eds/TVPlaySportPlusHD/GO3_LIVE_DASH/TVPlaySportPlusHD.mpd?begin=1638186375']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-90-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg N-102732-g5509235818, ffprobe N-102732-g5509235818
[debug] Proxy map: {}
[generic] TVPlaySportPlusHD: Requesting header
[redirect] Following redirect to https://cdn9.tvplayhome.lt:443/live/eds/TVPlaySportPlusHD/GO3_LIVE_DASH/TVPlaySportPlusHD.mpd?begin=1638186375
[generic] TVPlaySportPlusHD: Requesting header
WARNING: Falling back on generic information extractor.
[generic] TVPlaySportPlusHD: Downloading webpage
[generic] TVPlaySportPlusHD: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/generic.py", line 2525, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to callyoutube-dl with the --verbose flag and include its complete output.
```

## Description

Just tried to download DASH stream, and get error that No video formats found

**Comment by kotuk** [comment]
No video formats found

How to workaround

**Comment by 89z** [comment]
Please provide an uncensored example URL

**Comment by kotuk** [comment]
edited main post with uncensored example URL

**Comment by Vangelis66** [comment]
Two things: 

1. This is a **dynamic** MPD, IOW it's a **LIVE** MPEG-DASH stream, and `yt-dl`, to the best of my knowledge, doesn't support LIVE MPEG-DASH streams (only `static` MPDs are supported).

2. Both Audio and Video elementary streams use **Common Encryption** (cenc), specifically Microsoft PlayReady (**MSPR**) DRM:
```xml
<MPD 
  xmlns="urn:mpeg:dash:schema:mpd:2011" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"  
  xmlns:cenc="urn:mpeg:cenc:2013" 
  xmlns:mspr="urn:microsoft:playready" 
  profiles="urn:mpeg:dash:profile:isoff-live:2011" 
  type="dynamic" availabilityStartTime="2021-11-29T11:46:15Z" 
  publishTime="2021-11-29T22:29:57.841001Z" 
  minimumUpdatePeriod="PT2H" 
  minBufferTime="PT10S" 
  timeShiftBufferDepth="PT10H43M38S" 
  maxSegmentDuration="PT8S">
```
Sorry, doesn't seem to be recordable... 😉
