### ISSUE TITLE
niconico dl not working

### ISSUE THREAD

**Issue by lord-aceldama** [ytdl-org/youtube-dl#30316]
for link: https://www.nicovideo.jp/watch/sm12745574

```
aceldama@DietPi3LLMP:~/mnt/hdd-a/music/000-new $ youtube-dl https://www.nicovideo.jp/watch/sm12745574 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.nicovideo.jp/watch/sm12745574', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.2 (CPython) - Linux-5.10.63-v7+-armv7l-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.3-0, ffprobe 4.3.3-0
[debug] Proxy map: {}
[niconico] sm12745574: Downloading webpage
[niconico] sm12745574: Downloading flv info
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/niconico.py", line 291, in _real_extract
    video_real_url = api_data['video']['smileInfo']['url']
KeyError: 'smileInfo'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/niconico.py", line 291, in _real_extract
    video_real_url = api_data['video']['smileInfo']['url']
KeyError: 'smileInfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/niconico.py", line 310, in _real_extract
    raise ExtractorError('Unable to find video URL')
youtube_dl.utils.ExtractorError: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

aceldama@DietPi3LLMP:~/mnt/hdd-a/music/000-new $
```

**Comment by kikuyan** [comment]
Duplicate. Please search before post.

It's been broken since the site was changed around mid-March.
