### ISSUE TITLE
Chinese `bilibili` anime

### ISSUE THREAD

**Issue by c2xusnpq6** [ytdl-org/youtube-dl#30315]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Hong Kong, Macau and Taiwan

### Example URLs

`bilibili` anime: https://www.bilibili.com/anime/

- Single video: https://www.bilibili.com/bangumi/play/ep268185
- Playlist: https://www.bilibili.com/bangumi/media/md26360655/

### Description

`bilibili` anime: https://www.bilibili.com/anime/

You can find all the information for a specific episode via this link:
https://api.bilibili.com/pgc/player/web/playurl?ep_id=268185
Guest: https://api.bilibili.com/pgc/player/web/playurl?fnval=0&ep_id=268185
Logged-in: https://api.bilibili.com/pgc/player/web/playurl?fnval=80&ep_id=268185
(N/A): https://api.bilibili.com/pgc/player/web/playurl?fnval=100&ep_id=268185
I'm not so sure what it is about. The `fnval` value...

If you get this, it means that the video is available in your current location:
```
{"code":0,"message":"success" ...
```

`https://api.bilibili.com/pgc/player/web/playurl?fnval=0&ep_id=268185`:
```
{"code":0,"message":"success","result":{"accept_format":"hdflv2,flv,flv720,flv480,mp4","code":0,"seek_param":"start","is_preview":0,"fnval":0,"video_project":true,"fnver":0,"type":"FLV","bp":0,"result":"suee","seek_type":"offset","from":"local","video_codecid":7,"durl":[{"size":131167024,"ahead":"","length":1437245,"vhead":"","backup_url":[],"url":"https://upos-hz-mirrorakam.akamaized.net/upgcxcode/92/93/100279392/100279392_da8-1-32.flv?e=ig8euxZM2rNcNbRVhwdVhwdlhWdVhwdVhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1638588710&gen=playurlv2&os=akam&oi=618985272&trid=003c40ce3c2b4719abbbd9a01a7a0bcbp&platform=pc&upsig=a998a05293dd4718653f72747a3bd73d&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&hdnts=exp=1638581510~hmac=aabe5fa485eef99411714f24440345e1f92ae173d7e04753d089ae3bc71dee57&mid=0&bvc=vod&nettype=0&orderid=0,1&agrr=0&bw=91278&logo=80000000","order":1,"md5":""}],"no_rexcode":0,"format":"flv480","support_formats":[{"display_desc":"1080P","superscript":"高码率","need_login":true,"format":"hdflv2","description":"高清 1080P+","need_vip":true,"quality":112,"new_description":"1080P 高码率"},{"display_desc":"1080P","superscript":"","need_login":true,"format":"flv","description":"高清 1080P","quality":80,"new_description":"1080P 高清"},{"display_desc":"720P","superscript":"","need_login":true,"format":"flv720","description":"高清 720P","quality":64,"new_description":"720P 高清"},{"display_desc":"480P","superscript":"","format":"flv480","description":"清晰 480P","quality":32,"new_description":"480P 清晰"},{"display_desc":"360P","superscript":"","format":"mp4","description":"流畅 360P","quality":16,"new_description":"360P 流畅"}],"message":"","accept_quality":[112,80,64,32,16],"quality":32,"timelength":1437245,"has_paid":false,"clip_info_list":[],"accept_description":["高清 1080P+","高清 1080P","高清 720P","清晰 480P","流畅 360P"],"status":2}}
```

If you get this, it means that the video is not available in your current location:
![image](https://user-images.githubusercontent.com/75058881/144684035-a9efff75-fcc9-4bca-a997-d259b9c2855c.png)

https://api.bilibili.com/pgc/view/web/season?ep_id=268176
```
{"code":0,"message":"success","result":{"activity":{"head_bg_url":"","id":0,"title":""},"alias":"","areas":[{"id":2,"name":"日本"}],"bkg_cover":"","cover":"http://i0.hdslb.com/bfs/bangumi/0b9718fbeefb2b645428b3a1c577c00d882a7ef3.png","episodes":[{"aid":50762638,"badge":"","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":""},"badge_type":0,"bvid":"BV1o4411b7LX","cid":100279344,"cover":"http://i0.hdslb.com/bfs/archive/86d9f7c662170b47ae7b68cb9219ecd7d993b62c.jpg","dimension":{"height":1080,"rotate":0,"width":1920},"duration":1437203,"from":"bangumi","id":268176,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep268176","long_title":"初始的街道","pub_time":1556473200,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《進擊的巨人 第三季 Part.2（僅限台灣地區）》第13话 初始的街道","share_url":"https://www.bilibili.com/bangumi/play/ep268176","short_link":"https://b23.tv/ep268176","status":2,"subtitle":"已观看440.4万次","title":"13","vid":""},{"aid":51549723,"badge":"","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":""},"badge_type":0,"bvid":"BV1z4411i7Yj","cid":90232794,"cover":"http://i0.hdslb.com/bfs/archive/0a84e8031e178e57bab439fa876e27211c6cc2c9.jpg","dimension":{"height":1080,"rotate":0,"width":1920},"duration":1437203,"from":"bangumi","id":268177,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep268177","long_title":"雷槍","pub_time":1557078000,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《進擊的巨人 第三季 Part.2（僅限台灣地區）》第14话 雷槍","share_url":"https://www.bilibili.com/bangumi/play/ep268177","short_link":"https://b23.tv/ep268177","status":2,"subtitle":"已观看440.4万次","title":"14","vid":""},{"aid":52178767,"badge":"","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":""},"badge_type":0,"bvid":"BV1m4411h7y5","cid":91334799,"cover":"http://i0.hdslb.com/bfs/archive/69917b991b54b8f96f29a1787d55c8579d031998.jpg","dimension":{"height":1080,"rotate":0,"width":1920},"duration":1437203,"from":"bangumi","id":268178,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep268178","long_title":"光臨","pub_time":1557682800,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《進擊的巨人 第三季 Part.2（僅限台灣地區）》第15话 光臨","share_url":"https://www.bilibili.com/bangumi/play/ep268178","short_link":"https://b23.tv/ep268178","status":2,"subtitle":"已观看440.4万次","title":"15","vid":""},{"aid":52972297,"badge":"","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":""},"badge_type":0,"bvid":"BV194411L7ej","cid":92683542,"cover":"http://i0.hdslb.com/bfs/archive/76ca2104024244ba8236f22b0dfb4cab05b8e7cb.jpg","dimension":{"height":1080,"rotate":0,"width":1920},"duration":1437203,"from":"bangumi","id":268179,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep268179","long_title":"完全比賽","pub_time":1558287600,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《進擊的巨人 第三季 Part.2（僅限台灣地區）》第16话 完全比賽","share_url":"https://www.bilibili.com/bangumi/play/ep268179","short_link":"https://b23.tv/ep268179","status":2,"subtitle":"已观看440.4万次","title":"16","vid":""},{"aid":53750209,"badge":"","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":""},"badge_type":0,"bvid":"BV1y4411p77q","cid":94022221,"cover":"http://i0.hdslb.com/bfs/archive/a24ac46c1d507aa8c37b2455ef32bb1dffc90882.jpg","dimension":{"height":1080,"rotate":0,"width":1920},"duration":1437203,"from":"bangumi","id":268180,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep268180","long_title":"勇者","pub_time":1558933200,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《進擊的巨人 第三季 Part.2（僅限台灣地區）》第17话 勇者","share_url":"https://www.bilibili.com/bangumi/play/ep268180","short_link":"https://b23.tv/ep268180","status":2,"subtitle":"已观看440.4万次","title":"17","vid":""},{"aid":54448471,"badge":"","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":""},"badge_type":0,"bvid":"BV1m4411n7kg","cid":95234342,"cover":"http://i0.hdslb.com/bfs/archive/e8b4360c060445f387c49255e012772b334c78f9.jpg","dimension":{"height":1080,"rotate":0,"width":1920},"duration":1437203,"from":"bangumi","id":268181,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep268181","long_title":"白夜","pub_time":1559538000,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《進擊的巨人 第三季 Part.2（僅限台灣地區）》第18话 白夜","share_url":"https://www.bilibili.com/bangumi/play/ep268181","short_link":"https://b23.tv/ep268181","status":2,"subtitle":"已观看440.4万次","title":"18","vid":""},{"aid":55146916,"badge":"","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":""},"badge_type":0,"bvid":"BV1Y4411N7Tc","cid":96431575,"cover":"http://i0.hdslb.com/bfs/archive/ce4a1ba2500264ee8af18372a280f0fd721502a7.jpg","dimension":{"height":1080,"rotate":0,"width":1920},"duration":1437203,"from":"bangumi","id":268182,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep268182","long_title":"地下室","pub_time":1560142800,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《進擊的巨人 第三季 Part.2（僅限台灣地區）》第19话 地下室","share_url":"https://www.bilibili.com/bangumi/play/ep268182","short_link":"https://b23.tv/ep268182","status":2,"subtitle":"已观看440.4万次","title":"19","vid":""},{"aid":55861231,"badge":"","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":""},"badge_type":0,"bvid":"BV1X441137zn","cid":97653586,"cover":"http://i0.hdslb.com/bfs/archive/81fcc522a4b9a26356f5184b30d4f645d085fe7a.jpg","dimension":{"height":1080,"rotate":0,"width":1920},"duration":1437203,"from":"bangumi","id":268183,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep268183","long_title":"那一天","pub_time":1560747600,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《進擊的巨人 第三季 Part.2（僅限台灣地區）》第20话 那一天","share_url":"https://www.bilibili.com/bangumi/play/ep268183","short_link":"https://b23.tv/ep268183","status":2,"subtitle":"已观看440.4万次","title":"20","vid":""},{"aid":56660669,"badge":"","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":""},"badge_type":0,"bvid":"BV1Hx411o7d5","cid":98988334,"cover":"http://i0.hdslb.com/bfs/archive/ce780b9504a1fae515e9196f9180bdb8325daab2.jpg","dimension":{"height":1080,"rotate":0,"width":1920},"duration":1437203,"from":"bangumi","id":268184,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep268184","long_title":"進擊的巨人","pub_time":1561352400,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《進擊的巨人 第三季 Part.2（僅限台灣地區）》第21话 進擊的巨人","share_url":"https://www.bilibili.com/bangumi/play/ep268184","short_link":"https://b23.tv/ep268184","status":2,"subtitle":"已观看440.4万次","title":"21","vid":""},{"aid":57437208,"badge":"","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":""},"badge_type":0,"bvid":"BV1Nx411X7CA","cid":100279392,"cover":"http://i0.hdslb.com/bfs/archive/2b4d9e791aec588a7ee5cecde5cce97a1dd67a80.jpg","dimension":{"height":1080,"rotate":0,"width":1920},"duration":1437203,"from":"bangumi","id":268185,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep268185","long_title":"城牆的另一端","pub_time":1561957200,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《進擊的巨人 第三季 Part.2（僅限台灣地區）》第22话 城牆的另一端","share_url":"https://www.bilibili.com/bangumi/play/ep268185","short_link":"https://b23.tv/ep268185","status":2,"subtitle":"已观看440.4万次","title":"22","vid":""}],"evaluate":"歷經百年的時光，將人類與外側世界隔開的牆壁。在牆壁的另一側，似乎有前所未見的世界延伸開來。\n火焰之水、冰之大地、砂之雪原……。記載在書中的，儘是些激發少年探究心的文字。\n在時間流轉，牆壁被巨人毀壞的現在，人類正一步步接近世界的真相。\n巨人的真實身份是什麼？為何牆壁中會埋著巨人？巨人化的艾倫·耶格爾所持有的「坐標」之力是？以及，西斯托利亞·雷斯究竟知道這個世界的什麼事情？\n在艾倫等104期兵的加入下，建立新體制的利威爾班。最強最惡的敵人，阻攔在開始行動的他們面前。","freya":{"bubble_show_cnt":0,"icon_show":0},"jp_title":"","link":"http://www.bilibili.com/bangumi/media/md26360655/","media_id":26360655,"mode":2,"new_ep":{"desc":"已完结, 全10话","id":268185,"is_new":0,"title":"22"},"positive":{"id":36503,"title":"正片"},"publish":{"is_finish":1,"is_started":1,"pub_time":"2019-04-29 01:40:00","pub_time_show":"2019年04月29日01:40","unknow_pub_date":0,"weekday":0},"rating":{"count":20937,"score":9.8},"record":"","rights":{"allow_bp":0,"allow_bp_rank":0,"allow_download":0,"allow_review":1,"area_limit":333,"ban_area_show":1,"can_watch":1,"copyright":"bilibili","forbid_pre":0,"is_cover_show":0,"is_preview":0,"only_vip_download":0,"resource":"","watch_platform":0},"season_id":26963,"season_title":"進擊的巨人 第三季 Part.2（僅限台灣地區）","seasons":[{"badge":"","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":""},"badge_type":0,"cover":"http://i0.hdslb.com/bfs/bangumi/f0841da0acbb37bfd2d51700cc2a6c4dfa045295.jpg","media_id":5970,"new_ep":{"cover":"http://i1.hdslb.com/bfs/archive/7cfb9820d7232ed6503b842d197c777a92d23eb3.jpg","id":103747,"index_show":"全12话"},"season_id":5970,"season_title":"第二季（僅台灣）","season_type":1,"stat":{"favorites":913834,"series_follow":1325139,"views":3524672}},{"badge":"","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":""},"badge_type":0,"cover":"http://i0.hdslb.com/bfs/bangumi/e78da885c7ae738674894508f453410a0f8aefe6.png","media_id":117372,"new_ep":{"cover":"http://i0.hdslb.com/bfs/archive/e0e048c98538df91d7ea45ef4554b0671213f6af.jpg","id":234669,"index_show":"全12话"},"season_id":24629,"season_title":"第三季（僅台灣）","season_type":1,"stat":{"favorites":330706,"series_follow":1325139,"views":3714941}},{"badge":"","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":""},"badge_type":0,"cover":"http://i0.hdslb.com/bfs/bangumi/0b9718fbeefb2b645428b3a1c577c00d882a7ef3.png","media_id":26360655,"new_ep":{"cover":"http://i0.hdslb.com/bfs/archive/2b4d9e791aec588a7ee5cecde5cce97a1dd67a80.jpg","id":268185,"index_show":"全10话"},"season_id":26963,"season_title":"第三季 Part.2（僅台灣）","season_type":1,"stat":{"favorites":464691,"series_follow":1325139,"views":4403751}},{"badge":"","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":""},"badge_type":0,"cover":"http://i0.hdslb.com/bfs/bangumi/image/1cf38598c7053813b24664673b397564cfc5a13f.png","media_id":28233436,"new_ep":{"cover":"http://i0.hdslb.com/bfs/archive/42af86e329510a6dbfc704e2160c318b91dc79bf.png","id":380335,"index_show":"全16话"},"season_id":37757,"season_title":"第四季（僅港澳台）","season_type":1,"stat":{"favorites":1249950,"series_follow":1325139,"views":2919990}},{"badge":"","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":""},"badge_type":0,"cover":"http://i0.hdslb.com/bfs/bangumi/image/7eb49f4b6ade60703c7d119826a016bfb2dc23c8.png","media_id":28235576,"new_ep":{"cover":"http://i0.hdslb.com/bfs/archive/63972f1891ece91218b5b5967d78bacb591ccc5e.png","id":429402,"index_show":"更新至–Part Two–"},"season_id":39882,"season_title":"OAD（僅港澳台）","season_type":1,"stat":{"favorites":7868,"series_follow":1325139,"views":55732}},{"badge":"","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":""},"badge_type":0,"cover":"http://i0.hdslb.com/bfs/bangumi/image/29688a5e8bfb22d53d45a86696eb390371cf49f4.png","media_id":28235730,"new_ep":{"cover":"http://i0.hdslb.com/bfs/archive/fa5561c27daf68a94e7dc613f1875d5852c4a0b6.png","id":433226,"index_show":"全2话"},"season_id":40030,"season_title":"OAD2（僅港澳台）","season_type":1,"stat":{"favorites":3806,"series_follow":1325139,"views":10908}},{"badge":"","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":""},"badge_type":0,"cover":"http://i0.hdslb.com/bfs/bangumi/image/755f38cd64c7923a62dff0a9af4940de74e88c9e.png","media_id":28235731,"new_ep":{"cover":"http://i0.hdslb.com/bfs/archive/88bc417ac6642f2dc41a4790fd891f6184212dd6.png","id":433241,"index_show":"全1话"},"season_id":40031,"season_title":"OAD3（僅港澳台）","season_type":1,"stat":{"favorites":3352,"series_follow":1325139,"views":9654}}],"series":{"series_id":2442,"series_title":"進擊的巨人（僅限港澳台等地區）"},"share_copy":"《進擊的巨人 第三季 Part.2（僅限台灣地區）》","share_sub_title":"","share_url":"https://www.bilibili.com/bangumi/play/ss26963","show":{"wide_screen":0},"square_cover":"http://i0.hdslb.com/bfs/bangumi/f5d1a61085d464e9d494168ec994fcf0594b0ba5.jpg","stat":{"coins":51544,"danmakus":105421,"favorite":0,"favorites":464691,"likes":0,"reply":24389,"share":4889,"views":4403751},"status":2,"subtitle":"已观看440.4万次","title":"進擊的巨人 第三季 Part.2（僅限台灣地區）","total":10,"type":1}}
```

You can find found if the video got a subtitle via this link: (`JSON` format subtitle)
https://api.bilibili.com/x/player/v2?aid=549498610&cid=449402027&ep_id=433241&season_id=40031
![image](https://user-images.githubusercontent.com/75058881/144688473-05594809-b858-4202-8949-f6cc1e2ab601.png)

### Verbose log

```shell
# yt-dlp -v -Uv "https://www.bilibili.com/bangumi/play/ep268185"
[debug] Command-line config: ['-v', '-Uv', 'https://www.bilibili.com/bangumi/play/ep268185']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.9.9 (CPython 64bit) - Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.4.1-1 (setts), ffprobe 4.4.1-1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [generic] Extracting URL: https://www.bilibili.com/bangumi/play/ep268185
[generic] ep268185: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] ep268185: Downloading webpage
[generic] ep268185: Extracting information
[debug] Looking for video embeds
WARNING: [generic] ep268185: Failed to parse JSON Invalid control character at: line 11 column 94 (char 554)
ERROR: Unsupported URL: https://www.bilibili.com/bangumi/play/ep268185
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 1329, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 1398, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/common.py", line 597, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/generic.py", line 3813, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.bilibili.com/bangumi/play/ep268185
```

**Comment by c2xusnpq6** [comment]
https://github.com/yt-dlp/yt-dlp/issues/1878

**Comment by kikuyan** [comment]
Wrong place. This is youtube-dl repository.

**Comment by dirkf** [comment]
See #29852, and also #30007.

**Comment by c2xusnpq6** [comment]
> Wrong place. This is youtube-dl repository.

Because I want `youtube-dl` can also support this~

**Comment by c2xusnpq6** [comment]
> See #29852, and also #30007.

Mine is more detailed.

**Comment by dirkf** [comment]
Sure, but this isn't really a new site support request. Let's see where yt-dlp goes with it and back-port that if practical.

**Comment by kikuyan** [comment]
> Because I want youtube-dl can also support that~

Make a proper report. The template you've shown and the log is not of youtube-dl.

**Comment by 89z** [comment]
geo block:

> We are sorry, but according to the copyright holder's request
> This film cannot be viewed in your region

**Comment by c2xusnpq6** [comment]
> geo block:
> 
> > We are sorry, but according to the copyright holder's request
> > This film cannot be viewed in your region

Most of its animations are only open to Hong Kong, Taiwanese and Macau people.

So you may need to use to vpn.
