### ISSUE TITLE
Unable to extract video id

### ISSUE THREAD

**Issue by MaskOfDeath** [ytdl-org/youtube-dl#30362]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.06.06**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Program Files\_ytdl>youtube-dl -U
youtube-dl is up-to-date (2021.06.06)

C:\Program Files\_ytdl>youtube-dl --cookies cookies.txt https://www.raywenderlich.com/28684964-swiftui-layout-interfaces --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'cookies.txt', 'https://www.raywenderlich.com/28684964-swiftui-layout-interfaces', '--verbose']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Proxy map: {}
[RayWenderlichCourse] 28684964-swiftui-layout-interfaces: Downloading webpage
[download] Downloading playlist: SwiftUI: Layout & Interfaces
[RayWenderlichCourse] playlist SwiftUI: Layout & Interfaces: Collected 18 video ids (downloading 18 of them)
[download] Downloading video 1 of 18
[RayWenderlich] 28684964-swiftui-layout-interfaces/18: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\raywenderlich.py", line 105, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

It looks like the site has changed the output of the video id and now the extractor\raywenderlich.py does not work correctly. Can someone help?

**Comment by dirkf** [comment]
I believe that must be so.

This patch gets a video on the free pages but I have no idea about the new subscription pages:

```
--- old/youtube-dl/youtube_dl/extractor/raywenderlich.py
+++ new/youtube-dl/youtube_dl/extractor/raywenderlich.py
@@ -7,11 +7,17 @@
 from ..compat import compat_str
 from ..utils import (
     ExtractorError,
+    clean_html,
+    get_element_by_attribute,
+    get_element_by_class,
     int_or_none,
     merge_dicts,
+    parse_duration,
+    str_or_none,
     try_get,
     unescapeHTML,
     unified_timestamp,
+    unified_strdate,
     urljoin,
 )
 
@@ -82,7 +88,10 @@
             webpage, default=None) or self._html_search_meta(
             'twitter:image', webpage, 'thumbnail')
 
-        if '>Subscribe to unlock' in webpage:
+        if self._search_regex(
+            ('>Subscribe to unlock',
+             r'<a\s[^>]*?\bdata-subscription-required\s*=\s*(?:\'|"|\b)true(?:\'|"|\b)'),
+            webpage, 'subscription needed', default=False, group=0):
             raise ExtractorError(
                 'This content is only available for subscribers',
                 expected=True)
@@ -91,8 +100,25 @@
             'thumbnail': thumbnail,
         }
 
-        vimeo_id = self._search_regex(
-            r'data-vimeo-id=["\'](\d+)', webpage, 'vimeo id', default=None)
+        vimeo_url = self._og_search_property('video:url', webpage, fatal=False)
+        if vimeo_url:
+            info.update({
+                '_type': 'url_transparent',
+                'title': self._og_search_title(webpage),
+                'description': clean_html(self._og_search_description(webpage)),
+                'duration': parse_duration(get_element_by_class('c-box-list__item-duration', webpage)),
+                'upload_date': unified_strdate(
+                                   re.split(r'[^\w\s]',
+                                            get_element_by_class('c-written-tutorial__meta', webpage))[0].strip()),
+                'creator': clean_html(str_or_none(get_element_by_class('c-content-author__title', webpage)))
+            })
+
+        if not vimeo_url:
+            vimeo_id = self._search_regex(
+                r'data-vimeo-id=["\'](\d+)', webpage, 'vimeo id', default=None)
+        else:
+            vimeo_id = self._search_regex(
+                r'https?://player\.vimeo\.com/external/(\d+)', vimeo_url, 'vimeo id', default=None)
 
         if not vimeo_id:
             data = self._parse_json(
```

**Comment by Diodor7** [comment]
> I believe that must be so.
> 
> This patch gets a video on the free pages but I have no idea about the new subscription pages:
> 
> ```
> ```

Hi, dirkf!
Yes, now this code allows you to download the free part of the video, but the subscription video is not downloaded.
Please tell me what needs to be changed in the code for this? where to dig?

**Comment by dirkf** [comment]
Try passing `--cookies` extracted from the browser with a logged-in account that has the relevant subscription.

**Comment by Diodor7** [comment]
> Try passing `--cookies` extracted from the browser with a logged-in account that has the relevant subscription.

I was passing --cookies cookies.txt with a extension "Get cookies.txt"

**Comment by dirkf** [comment]
Sounds good: verbose log (`-F -v`, eg)?

**Comment by Diodor7** [comment]
@dirkf 
`[debug] Command-line config: ['--cookies', 'rw.txt', 'https://www.raywenderlich.com/22246944-cloud-firestore-on-android-getting-started/', '-v']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, err utf-8, pref cp1251
[debug] yt-dlp version 2021.12.27 [6223f67a8] (win_exe)
[debug] Python version 3.10.1 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 2021-12-12-git-996b13fac4-full_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [RayWenderlichCourse] Extracting URL: https://www.raywenderlich.com/22246944-cloud-firestore-on-android-getting-started/
[RayWenderlichCourse] 22246944-cloud-firestore-on-android-getting-started: Downloading webpage
[download] Downloading playlist: Cloud Firestore on Android - Getting Started
[RayWenderlichCourse] playlist Cloud Firestore on Android - Getting Started: Collected 10 videos; downloading 10 of them[download] Downloading video 1 of 10
[debug] [RayWenderlich] Extracting URL: https://www.raywenderlich.com/22246944-cloud-firestore-on-android-getting-started/lessons/1
[RayWenderlich] 22246944-cloud-firestore-on-android-getting-started/1: Downloading webpage
[debug] [vimeo] Extracting URL: https://player.vimeo.com/video/647287328#__youtubedl_smuggle=%7B%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fwww.raywenderlich.com%2F22246944-cloud-firestore-on-android-getting-started%2Flessons%2F1%22%7D%7D
[vimeo] 647287328: Downloading webpage
[vimeo] 647287328: Downloading akfire_interconnect_quic m3u8 information
WARNING: [vimeo] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[vimeo] 647287328: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 647287328: Downloading fastly_skyfire m3u8 information
[vimeo] 647287328: Downloading fastly_skyfire m3u8 information
[vimeo] 647287328: Downloading akfire_interconnect_quic MPD information
[vimeo] 647287328: Downloading akfire_interconnect_quic MPD information
[vimeo] 647287328: Downloading fastly_skyfire MPD information
[vimeo] 647287328: Downloading fastly_skyfire MPD information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 647287328: Downloading 1 format(s): http-720p
[debug] Invoking downloader on "https://vod-progressive.akamaized.net/exp=1641134806~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F4457%2F25%2F647287328%2F2969148271.mp4~hmac=5092a1c4f756d15e10e93e4aa94a8d039010d4b79213ef71abbfab1d2f66e5c3/vimeo-prod-skyfire-std-us/01/4457/25/647287328/2969148271.mp4"
[download] Destination: Cloud Firestore on Android - Getting Started, Episode 1 - What is Cloud Firestore [647287328].mp4
[download] 100% of 7.17MiB in 00:02
[download] Downloading video 2 of 10
[debug] [RayWenderlich] Extracting URL: https://www.raywenderlich.com/22246944-cloud-firestore-on-android-getting-started/lessons/2
[RayWenderlich] 22246944-cloud-firestore-on-android-getting-started/2: Downloading webpage
[debug] [vimeo] Extracting URL: https://player.vimeo.com/video/647287409#__youtubedl_smuggle=%7B%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fwww.raywenderlich.com%2F22246944-cloud-firestore-on-android-getting-started%2Flessons%2F2%22%7D%7D
[vimeo] 647287409: Downloading webpage
[vimeo] 647287409: Downloading akfire_interconnect_quic m3u8 information
WARNING: [vimeo] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[vimeo] 647287409: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 647287409: Downloading fastly_skyfire m3u8 information
[vimeo] 647287409: Downloading fastly_skyfire m3u8 information
[vimeo] 647287409: Downloading akfire_interconnect_quic MPD information
[vimeo] 647287409: Downloading akfire_interconnect_quic MPD information
[vimeo] 647287409: Downloading fastly_skyfire MPD information
[vimeo] 647287409: Downloading fastly_skyfire MPD information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 647287409: Downloading 1 format(s): http-1080p
[debug] Invoking downloader on "https://vod-progressive.akamaized.net/exp=1641134816~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F4457%2F25%2F647287409%2F2969150312.mp4~hmac=6e46d81f2623febad24fc996d014c289f89bf5832ae752d8e16d1807798c2c4a/vimeo-prod-skyfire-std-us/01/4457/25/647287409/2969150312.mp4"
[download] Destination: Cloud Firestore on Android - Getting Started, Episode 2 - Set Up Firebase [647287409].mp4
[download] 100% of 17.10MiB in 00:04
[download] Downloading video 3 of 10
[debug] [RayWenderlich] Extracting URL: https://www.raywenderlich.com/22246944-cloud-firestore-on-android-getting-started/lessons/3
[RayWenderlich] 22246944-cloud-firestore-on-android-getting-started/3: Downloading webpage
[debug] [vimeo] Extracting URL: https://player.vimeo.com/video/647287744#__youtubedl_smuggle=%7B%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fwww.raywenderlich.com%2F22246944-cloud-firestore-on-android-getting-started%2Flessons%2F3%22%7D%7D
[vimeo] 647287744: Downloading webpage
[vimeo] 647287744: Downloading akfire_interconnect_quic m3u8 information
WARNING: [vimeo] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[vimeo] 647287744: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 647287744: Downloading fastly_skyfire m3u8 information
[vimeo] 647287744: Downloading fastly_skyfire m3u8 information
[vimeo] 647287744: Downloading akfire_interconnect_quic MPD information
[vimeo] 647287744: Downloading akfire_interconnect_quic MPD information
[vimeo] 647287744: Downloading fastly_skyfire MPD information
[vimeo] 647287744: Downloading fastly_skyfire MPD information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 647287744: Downloading 1 format(s): http-720p
[debug] Invoking downloader on "https://vod-progressive.akamaized.net/exp=1641134828~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F4457%2F25%2F647287744%2F2969150545.mp4~hmac=2b5916aa6ffa787fc3b1a36ca5ac0735a45e26d35f4b3afcc77b10e18dec3f8f/vimeo-prod-skyfire-std-us/01/4457/25/647287744/2969150545.mp4"
[download] Destination: Cloud Firestore on Android - Getting Started, Episode 3 - Run the Sample Project [647287744].mp4
[download] 100% of 15.23MiB in 00:04
[download] Downloading video 4 of 10
[debug] [RayWenderlich] Extracting URL: https://www.raywenderlich.com/22246944-cloud-firestore-on-android-getting-started/lessons/4
[RayWenderlich] 22246944-cloud-firestore-on-android-getting-started/4: Downloading webpage
ERROR: [RayWenderlich] 4: This content is only available for subscribers
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\raywenderlich.py", line 95, in _real_extract

[download] Downloading video 5 of 10
[debug] [RayWenderlich] Extracting URL: https://www.raywenderlich.com/22246944-cloud-firestore-on-android-getting-started/lessons/5
[RayWenderlich] 22246944-cloud-firestore-on-android-getting-started/5: Downloading webpage
ERROR: [RayWenderlich] 5: This content is only available for subscribers
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\raywenderlich.py", line 95, in _real_extract

[download] Downloading video 6 of 10
[debug] [RayWenderlich] Extracting URL: https://www.raywenderlich.com/22246944-cloud-firestore-on-android-getting-started/lessons/6
[RayWenderlich] 22246944-cloud-firestore-on-android-getting-started/6: Downloading webpage
ERROR: [RayWenderlich] 6: This content is only available for subscribers
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\raywenderlich.py", line 95, in _real_extract

[download] Downloading video 7 of 10
[debug] [RayWenderlich] Extracting URL: https://www.raywenderlich.com/22246944-cloud-firestore-on-android-getting-started/lessons/7
[RayWenderlich] 22246944-cloud-firestore-on-android-getting-started/7: Downloading webpage
ERROR: [RayWenderlich] 7: This content is only available for subscribers
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\raywenderlich.py", line 95, in _real_extract

[download] Downloading video 8 of 10
[debug] [RayWenderlich] Extracting URL: https://www.raywenderlich.com/22246944-cloud-firestore-on-android-getting-started/lessons/8
[RayWenderlich] 22246944-cloud-firestore-on-android-getting-started/8: Downloading webpage
ERROR: [RayWenderlich] 8: This content is only available for subscribers
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\raywenderlich.py", line 95, in _real_extract

[download] Downloading video 9 of 10
[debug] [RayWenderlich] Extracting URL: https://www.raywenderlich.com/22246944-cloud-firestore-on-android-getting-started/lessons/9
[RayWenderlich] 22246944-cloud-firestore-on-android-getting-started/9: Downloading webpage
ERROR: [RayWenderlich] 9: This content is only available for subscribers
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\raywenderlich.py", line 95, in _real_extract

[download] Downloading video 10 of 10
[debug] [RayWenderlich] Extracting URL: https://www.raywenderlich.com/22246944-cloud-firestore-on-android-getting-started/lessons/10
[RayWenderlich] 22246944-cloud-firestore-on-android-getting-started/10: Downloading webpage
ERROR: [RayWenderlich] 10: This content is only available for subscribers
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\raywenderlich.py", line 95, in _real_extract

[download] Finished downloading playlist: Cloud Firestore on Android - Getting Started`

**Comment by dirkf** [comment]
OK, so the tell that the extractor uses to detect subscriber content is still there. If you visit one of the subscription pages with your login you should be able to see if that's also true. The patterns for the tell are in the hunk '@@ -82,7 +88,10 @@' of the patch.

Then:
* if the page still has the tell, maybe we need to find some way to distinguish when the subscribed content is actually accessible;
* if not, just passing the cookies is not allowing the extractor to get the same sort of page that the browser sees: either the cookies are not actually being sent (you can see that with `--print-traffic`) or some further headers (a User-Agent that matches the cookies, Referer, or whatever) are being required by the site.

**Comment by Diodor7** [comment]
@dirkf, sorry, I updated the cookies and the errors have changed:

```
WARNING: [RayWenderlich] unable to extract OpenGraph video:url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
ERROR: [RayWenderlich] 9: Unable to extract video id; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\raywenderlich.py", line 130, in _real_extract
  File "yt_dlp\extractor\common.py", line 1173, in _search_regex
```

**Comment by Diodor7** [comment]
[raywenderlich.ry](https://github.com/ytdl-org/youtube-dl/files/7799177/raywenderlich.md)

I modified the raywenderlich.py file manually, I think was not mistaken in this.

**Comment by dirkf** [comment]
It's the same as the patched yt-dl file, except for Windows line endings and this line, which only works if you're using a modified `extractor/common.py`, such as the one from yt-dlp:
```
-        mobj = re.match(self._VALID_URL, url)
+        mobj = self._match_valid_url(url)
```
But as you're actually using that version, you should carry on the issue in the yt-dlp tracker, where there is the benefit that probably more eyes will see it.

**Comment by Diodor7** [comment]
@dirkf ok, thanks!

**Comment by Diodor7** [comment]
@dirkf, hi again! I didn't get a response from the yt-dlp tracker.
Maybe something else can be done? I could send you cookies if needed
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'rw.txt', 'https://www.raywenderlich.com/29104906-beginning-flutter-debugging/', '-v']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.1 (CPython) - Windows-10-10.0.19044-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[RayWenderlichCourse] 29104906-beginning-flutter-debugging: Downloading webpage
[download] Downloading playlist: Beginning Flutter Debugging
[RayWenderlichCourse] playlist Beginning Flutter Debugging: Collected 11 video ids (downloading 11 of them)
[download] Downloading video 1 of 11
[RayWenderlich] 29104906-beginning-flutter-debugging/1: Downloading webpage
[vimeo] 654476491: Downloading webpage
[vimeo] 654476491: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 654476491: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 654476491: Downloading fastly_skyfire m3u8 information
[vimeo] 654476491: Downloading fastly_skyfire m3u8 information
[vimeo] 654476491: Downloading akfire_interconnect_quic MPD information
[vimeo] 654476491: Downloading akfire_interconnect_quic MPD information
[vimeo] 654476491: Downloading fastly_skyfire MPD information
[vimeo] 654476491: Downloading fastly_skyfire MPD information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://skyfire.vimeocdn.com/1646954260-0x51360394e775f54495ff4c91c8b9c60dde87abf2/a690522d-3dc0-46e9-8c6c-ed9b4506ac31/video/a031736c,bd7d6d41,a4e9aa5b,eaafee17,917bc655/audio/6dcc1370,8b201854/master.mpd?query_string_ranges=1&base64_init=1'
[dashsegments] Total fragments: 33
[download] Destination: Beginning Flutter Debugging, Episode 1 - Understand Debugging-654476491.mp4
[download] 100% of 9.71MiB in 00:13
[download] Downloading video 2 of 11
[RayWenderlich] 29104906-beginning-flutter-debugging/2: Downloading webpage
WARNING: unable to extract OpenGraph video:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Program Files\_ytdl\youtube-dl-2021.12.17\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\_ytdl\youtube-dl-2021.12.17\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Program Files\_ytdl\youtube-dl-2021.12.17\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Program Files\_ytdl\youtube-dl-2021.12.17\youtube_dl\extractor\raywenderlich.py", line 130, in _real_extract
    data, lesson_id) or self._search_regex(
  File "C:\Program Files\_ytdl\youtube-dl-2021.12.17\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Diodor7** [comment]
@dirkf, free videos stopped loading again, if you can help with the paid ones too, I can provide you with cookies.
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'rw.txt', 'https://www.raywenderlich.com/28092310-material-motion-for-android', '-v']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.1 (CPython) - Windows-10-10.0.19044-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[RayWenderlichCourse] 28092310-material-motion-for-android: Downloading webpage
[download] Downloading playlist: Material Motion for Android
[RayWenderlichCourse] playlist Material Motion for Android: Collected 6 video ids (downloading 6 of them)
[download] Downloading video 1 of 6
[RayWenderlich] 28092310-material-motion-for-android/1: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Program Files\_ytdl\youtube-dl-2021.12.17\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\_ytdl\youtube-dl-2021.12.17\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Program Files\_ytdl\youtube-dl-2021.12.17\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Program Files\_ytdl\youtube-dl-2021.12.17\youtube_dl\extractor\raywenderlich.py", line 130, in _real_extract
    data, lesson_id) or self._search_regex(
  File "C:\Program Files\_ytdl\youtube-dl-2021.12.17\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by Diodor7** [comment]
Help :]

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31244
