### ISSUE TITLE
[Windows] [Twitter] "[Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by a-raccoon** [ytdl-org/youtube-dl#30361]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
F:\Youtube-DL>youtube-dl.exe --ignore-config --verbose https://twitter.com/cassandrawebbtv/status/1470124083547418624
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '--verbose', 'https://twitter.com/cassandrawebbtv/status/1470124083547418624']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg n4.4-6-g7e9b9f24df, ffprobe n4.4-6-g7e9b9f24df
[debug] Proxy map: {}
[twitter] 1470124083547418624: Downloading guest token
[twitter] 1470124083547418624: Downloading JSON metadata
[twitter] 1470124083547418624: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://video.twimg.com/ext_tw_video/1470124003201273856/pu/vid/720x1060/KKdVKnZxI47Oihej.mp4?tag=12'
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'Cassandra Webb - MUST WATCH - A man from #Kentucky lost his home after the #tornado Yet, here he sits at his piano playing the @Gaithermusic tune, "There's Something About That Name." The peace that passes understanding. #ARwx @FOX16News @KARK4News @NWS @HaydenNix-1470124083547418624.mp4.part'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\downloader\http.py", line 260, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\utils.py", line 2055, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'Cassandra Webb - MUST WATCH - A man from #Kentucky lost his home after the #tornado Yet, here he sits at his piano playing the @Gaithermusic tune, "There's Something About That Name." The peace that passes understanding. #ARwx @FOX16News @KARK4News @NWS @HaydenNix-1470124083547418624.mp4.part'
```

## Description

youtube-dl experiences recurrent issues with grabbing videos from Twitter owing to Windows filesystem errors from erroneous characters or total length.  sanitize isn't doing its job.

**Comment by wxolp** [comment]
https://github.com/yt-dlp/yt-dlp/issues/1136

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29239

**Comment by wxolp** [comment]
https://github.com/yt-dlp/yt-dlp/issues/1136

**Comment by dirkf** [comment]
Same work-around as https://github.com/yt-dlp/yt-dlp/issues/1999:  `-o "%(title).200s.%(ext)s"`
