### ISSUE TITLE
Signature extraction failed when fetching meta-data with -F option

### ISSUE THREAD

**Issue by finnianr** [ytdl-org/youtube-dl#30387]
youtube-dl is up-to-date (2021.06.06)
OS is Linux Mint 17
```
finnian@MacMini ~/Music/X1/Chopin $ sudo youtube-dl -U
[sudo] password for finnian: 
youtube-dl is up-to-date (2021.06.06)
finnian@MacMini ~/Music/X1/Chopin $ youtube-dl -F https://www.youtube.com/watch?v=hrlfdX-BouI
[youtube] hrlfdX-BouI: Downloading webpage
[youtube] hrlfdX-BouI: Downloading player f3c4e04d
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1349, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by 89z** [comment]
This is the second issue youve posted today, and neither time did you check that 10 issues are already open on the same problem:

https://github.com/ytdl-org/youtube-dl/search?o=desc&q=Signature+in%3Atitle&s=created&state=open&type=issues

please stop.

**Comment by finnianr** [comment]
> This is the second issue youve posted today, and neither time did you check that 10 issues are already open on the same problem:
The first time I accidentally hit wrong button without realizing, sorry. I looked at a similar issue but the line numbers were different so figure it might be a different but perhaps related issue.
