### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by haveweotbefore** [ytdl-org/youtube-dl#30399]
## Checklist

- [X ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.instagram.com/p/CB7CmZ7JiNl/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.2-2021-02-27-essentials_build-www.gyan.dev, ffprobe 4.3.2-2021-02-27-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[Instagram] CB7CmZ7JiNl: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\instagram.py", line 240, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1130, in _og_search_video_url
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1021, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

WRITE DESCRIPTION HERE
It seems that certain videos on Instagram result in this issue.

**Comment by dirkf** [comment]
Duplicate of #30106, and, as there, works for me:
```
$ youtube-dl -v -F 'https://www.instagram.com/p/CB7CmZ7JiNl/'
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.instagram.com/p/CB7CmZ7JiNl/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[Instagram] CB7CmZ7JiNl: Downloading webpage
[info] Available formats for CB7CmZ7JiNl:
format code  extension  resolution note
0            mp4        750x750    
$
```

**Comment by 89z** [comment]
@dirkf example only works for a limited number of tries. In my case, it works three times then failed exactly as the Author. In which case, I have an alternative tool that allows authentication for further requests:

~~~
PS C:\> instagram -a -v CB7CmZ7JiNl
GET /p/CB7CmZ7JiNl/?__a=1 HTTP/1.1
Host: www.instagram.com
Authorization: Bearer IGT:2:eyJkc191c2VyX2lkIjoiNDkzNzgxNzEzMzQiLCJzZXNzaW9ua...
User-Agent: Instagram 214.1.0.29.120 Android

GET https://scontent-hou1-1.cdninstagram.com/v/t50.2886-16/104889613_300054504485744_7972794599033206493_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InZ0c192b2RfdXJsZ2VuLjcyMC5mZWVkLmRlZmF1bHQifQ&_nc_ht=scontent-hou1-1.cdninstagram.com&_nc_cat=108&_nc_ohc=la1OgP36oNsAX8-_eX4&edm=AABBvjUBAAAA&vs=17891794249542449_3392401259&_nc_vs=HBksFQAYJEdBMTlRQVp3TXlmaTVSQUJBTjMyaGpaeURxVnVia1lMQUFBRhUAAsgBABUAGCRHRmF5UWdaUDNlOXFzcmtKQUU1MnVRSURvYXdUYmtZTEFBQUYVAgLIAQAoABgAGwGIB3VzZV9vaWwBMBUAACbins3tvp%2FIPxUCKAJDMywXQCghysCDEm8YEmRhc2hfYmFzZWxpbmVfMV92MREAdeoHAA%3D%3D&_nc_rid=76156ed093&ccb=7-4&oe=61C0144C&oh=00_AT99MREUS3RcH-ZDfC7rwaRAxuQHrMNIyqnjFKgO_XJw5A&_nc_sid=83d603
~~~

https://github.com/89z/mech

**Comment by dirkf** [comment]
See https://github.com/ytdl-org/youtube-dl/issues/30106#issuecomment-997267629
