### ISSUE TITLE
[Niconico]Unable to find video URL

### ISSUE THREAD

**Issue by unSerori** [ytdl-org/youtube-dl#30395]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
Microsoft Windows [Version 10.0.19043.1348]
(c) Microsoft Corporation. All rights reserved.

D:\>youtube-dl --version
2021.12.17

D:\>youtube-dl "https://www.nicovideo.jp/watch/sm34923907"
[niconico] sm34923907: Downloading webpage
[niconico] sm34923907: Downloading flv info
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

D:\>youtube-dl "https://www.nicovideo.jp/watch/sm34923907" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.nicovideo.jp/watch/sm34923907', '--verbose']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
[niconico] sm34923907: Downloading webpage
[niconico] sm34923907: Downloading flv info
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\niconico.py", line 291, in _real_extract
KeyError: 'smileInfo'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\niconico.py", line 291, in _real_extract
KeyError: 'smileInfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\niconico.py", line 310, in _real_extract
youtube_dl.utils.ExtractorError: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


D:\>
```

## Description

If my memory is certain, this software about 2 years ago used to be able to download NiconicoVideo.
However, after that, although it became impossible to download, it was possible to download by using aria2c until around version 2021.4.26.
After that, I tried various things, but I couldn't download it anymore. And that's still going on as of version 2021.12.17.
My English is so poor, I'm sorry...

**Comment by dirkf** [comment]
Unmerged PR #30329 should solve your problem.

As you have Windows, presumably >XP, you could try the [yt-dlp](https://github.com/yt-dlp/yt-dlp/releases) version from which the PR was back-ported.
