### ISSUE TITLE
Videa extractor crashes

### ISSUE THREAD

**Issue by eegerferenc** [ytdl-org/youtube-dl#30416]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
~$ youtube-dl --verbose https://videa.hu/videok/film-animacio/stephen-king-a-ragyogas-1980.-115-perc-angol-amerikai-thriller-AbnZmvpLVyvkrVCn
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://videa.hu/videok/film-animacio/stephen-king-a-ragyogas-1980.-115-perc-angol-amerikai-thriller-AbnZmvpLVyvkrVCn']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-163-generic-i686-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, rtmpdump 2.4
[debug] Proxy map: {}
[Videa] AbnZmvpLVyvkrVCn: Downloading webpage
[Videa] AbnZmvpLVyvkrVCn: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube-dl/youtube_dl/__init__.py", line 475, in main
  File "./youtube-dl/youtube-dl/youtube_dl/__init__.py", line 465, in _real_main
  File "./youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 2069, in download
  File "./youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
  File "./youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
  File "./youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/videa.py", line 121, in _real_extract
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/videa.py", line 94, in rc4
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 168: ordinal not in range(128)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
ImportError: No module named apport.fileutils

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube-dl/youtube_dl/__init__.py", line 475, in main
  File "./youtube-dl/youtube-dl/youtube_dl/__init__.py", line 465, in _real_main
  File "./youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 2069, in download
  File "./youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
  File "./youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
  File "./youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/videa.py", line 121, in _real_extract
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/videa.py", line 94, in rc4
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 168: ordinal not in range(128)

```

## Description

Youtube-dl crashes when download from Videa is requested. Example URL is provided above.

**Comment by kikuyan** [comment]
Reproduces with 2.7. Works with 3.9, so if you can use 3.x, that may be a faster solution than waiting for a fix.

**Comment by dirkf** [comment]
The fix is easy, though:
```
--- old/youtube-dl/youtube_dl/extractor/videa.py
+++ new/youtube-dl/youtube_dl/extractor/videa.py
@@ -91,7 +91,7 @@
             k = S[(S[i] + S[j]) % 256]
             res += compat_struct_pack('B', k ^ compat_ord(cipher_text[m]))
 
-        return res.decode()
+        return res.decode('utf-8')
 
     def _real_extract(self, url):
         video_id = self._match_id(url)
```
