### ISSUE TITLE
Mediaset [ITA] Not Working

### ISSUE THREAD

**Issue by botolo** [ytdl-org/youtube-dl#30411]
Unfortunately it looks like youtube-dl is not working with videos from Mediaset website in Italy.

URL: https://www.grandefratello.mediaset.it/video/ventinovesima-puntata_27071.shtml

Verbose report from youtube-dl

youtube-dl -v https://www.grandefratello.mediaset.it/video/ventinovesima-puntata_27071.shtml
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.grandefratello.mediaset.it/video/ventinovesima-puntata_27071.shtml']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 96137bc19
[debug] Python version 3.10.1 (CPython) - macOS-12.1-arm64-arm-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] ventinovesima-puntata_27071: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ventinovesima-puntata_27071: Downloading webpage
[generic] ventinovesima-puntata_27071: Extracting information
[Mediaset] F310293901002901: Downloading JSON metadata
[Mediaset] F310293901002901: Downloading MPEG4 SD SMIL data
[Mediaset] F310293901002901: Downloading MPEG4 HD SMIL data
ERROR: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/mediaset.py", line 157, in _real_extract
    raise first_e
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/mediaset.py", line 142, in _real_extract
    tp_formats, tp_subtitles = self._extract_theplatform_smil(
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/theplatform.py", line 51, in _extract_theplatform_smil
    raise ExtractorError(
youtube_dl.utils.ExtractorError: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences

**Comment by kikuyan** [comment]
#19076, #27439, which have the same error message, are labeled DRM by the dev member.

Please try unchecking "Play DRM-controlled content" in Firefox (or in any other browser that has similar settings) and test if the video can be played.

**Comment by nixxo** [comment]
It's a DRM related issue.
