### ISSUE TITLE
NCIS Hawai'i episode fails on CBS

### ISSUE THREAD

**Issue by octavioj** [ytdl-org/youtube-dl#30417]
We are able to download all episodes but one. It is episode 7 or the first season, called rescuer. Here is the URL:

https://www.cbs.com/shows/ncis-hawaii/video/BbRwfYOuYUs21CyT40kNXUA_Upkg63XU/ncis-hawai-i-rescuer/

Here is the output of youtube-dl with --verbose:

youtube-dl --verbose https://www.cbs.com/shows/ncis-hawaii/video/BbRwfYOuYUs21CyT40kNXUA_Upkg63XU/ncis-hawai-i-rescuer
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.cbs.com/shows/ncis-hawaii/video/BbRwfYOuYUs21CyT40kNXUA_Upkg63XU/ncis-hawai-i-rescuer']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.7 (CPython) - Linux-5.13.0-22-generic-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[CBS] BbRwfYOuYUs21CyT40kNXUA_Upkg63XU: Downloading XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cbs.py", line 115, in _real_extract
    return self._extract_video_info(content_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cbs.py", line 97, in _extract_video_info
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
With PR #30085, the problem is clarified:
```
[CBS] BbRwfYOuYUs21CyT40kNXUA_Upkg63XU: Downloading XML
ERROR: BbRwfYOuYUs21CyT40kNXUA_Upkg63XU: Only DRM formats found
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "youtube_dl/extractor/cbs.py", line 72, in _real_extract
    return self._extract_video_info(self._match_id(url))
  File "youtube_dl/extractor/cbs.py", line 159, in _extract_video_info
    raise ExtractorError('Only DRM formats found', video_id=content_id, expected=True)
ExtractorError: BbRwfYOuYUs21CyT40kNXUA_Upkg63XU: Only DRM formats found
```

**Comment by octavioj** [comment]
> With PR #30085, the problem is clarified:
> 
> ```
> [CBS] BbRwfYOuYUs21CyT40kNXUA_Upkg63XU: Downloading XML
> ERROR: BbRwfYOuYUs21CyT40kNXUA_Upkg63XU: Only DRM formats found
> Traceback (most recent call last):
>   File "youtube_dl/YoutubeDL.py", line 815, in wrapper
>     return func(self, *args, **kwargs)
>   File "youtube_dl/YoutubeDL.py", line 836, in __extract_info
>     ie_result = ie.extract(url)
>   File "youtube_dl/extractor/common.py", line 534, in extract
>     ie_result = self._real_extract(url)
>   File "youtube_dl/extractor/cbs.py", line 72, in _real_extract
>     return self._extract_video_info(self._match_id(url))
>   File "youtube_dl/extractor/cbs.py", line 159, in _extract_video_info
>     raise ExtractorError('Only DRM formats found', video_id=content_id, expected=True)
> ExtractorError: BbRwfYOuYUs21CyT40kNXUA_Upkg63XU: Only DRM formats found
> ```

Thank you. That is interesting as it seems to be the only episode that has DRM.

**Comment by dirkf** [comment]
It's also possible that the PR is failing to extract a usable format, but you could check with yt-dlp as well.

**Comment by nicolaasjan** [comment]
Yt-dlp fails as well:

`ERROR: [CBS] BbRwfYOuYUs21CyT40kNXUA_Upkg63XU: BbRwfYOuYUs21CyT40kNXUA_Upkg63XU: This video is DRM protected`

**Comment by octavioj** [comment]
That seems to explain it. Thank you all.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30477

**Comment by 89z** [comment]
> With PR #30085, the problem is clarified:

I would be wary of any PR from @dirkf, he is a known copyright violator:

https://github.com/ytdl-org/youtube-dl/pull/30184#issuecomment-958689745

**Comment by 89z** [comment]
I think these are only DRM temporarily, as that URL works now:

~~~
GET http://link.theplatform.com/s/dJ5BDC/media/guid/2198311517/BbRwfYOuYUs21CyT40kNXUA_Upkg63XU?format=preview
HEAD http://link.theplatform.com/s/dJ5BDC/media/guid/2198311517/BbRwfYOuYUs21CyT40kNXUA_Upkg63XU?assetTypes=StreamPack&formats=MPEG4%2CM3U
GET https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/10/28/1968780355504/CBS_NCIS_HAWAII_107_UHD_FIX_NA_R1_1122873_,503,4628,3128,2228,1628,848,000.mp4.csmil/master.m3u8?hdnea=acl=/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/10/28/1968780355504/CBS_NCIS_HAWAII_107_UHD_FIX_NA_R1_1122873_*~exp=1653753259~hmac=18ff43aa7bacd45ab9fdce062f44ea4c21c3c272b43990eb89bdcbb2adbbe01b
GET https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/10/28/1968780355504/CBS_NCIS_HAWAII_107_UHD_FIX_NA_R1_1122873_,503,4628,3128,2228,1628,848,000.mp4.csmil/index_3_av.m3u8?null=0&id=AgBItRcmFy81SjNFkmJGPYvbN9VoEtIaut1l6M5j6UnRafG9SzkXq9q151QbrjGcgSgfdsteJNr2OA%3d%3d&hdntl=exp=1653839539~acl=%2fi%2ftemp_hd_gallery_video%2fCBS_Production_Outlet_VMS%2fvideo_robot%2fCBS_Production_Entertainment%2f2021%2f10%2f28%2f1968780355504%2fCBS_NCIS_HAWAII_107_UHD_FIX_NA_R1_1122873_*~data=hdntl~hmac=a49dcbe1ea2c151e11483b5fb876721b66027daf7259ccdb6c76161fea140af7
GET https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/10/28/1968780355504/CBS_NCIS_HAWAII_107_UHD_FIX_NA_R1_1122873_,503,4628,3128,2228,1628,848,000.mp4.csmil/crypt.key?null=0&id=AgBItRcmFy81SjNFkmJGPYvbN9VoEtIaut1l6M5j6UnRafG9SzkXq9q151QbrjGcgSgfdsteJNr2OA%3d%3d&hdntl=exp=1653839539~acl=/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/10/28/1968780355504/CBS_NCIS_HAWAII_107_UHD_FIX_NA_R1_1122873_*~data=hdntl~hmac=a49dcbe1ea2c151e11483b5fb876721b66027daf7259ccdb6c76161fea140af7
1.6%    11.081 MB       16.640 MB/s
~~~
