### ISSUE TITLE
TikTok unable to extract data

### ISSUE THREAD

**Issue by Janitsu** [ytdl-org/youtube-dl#30439]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: ['--no-mtime', '--merge-output-format', 'mp4', '-o', 'D:\\YouTube-dl\\downloads\\%(id)s.%(ext)s', '--restrict-filenames']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.tiktok.com/@imchase6/video/7044750503141444911']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-10-28-git-e84c83ef98-full_build-www.gyan.dev, ffprobe 2021-10-28-git-e84c83ef98-full_build-www.gyan.dev
[debug] Proxy map: {}
[TikTok] Setting up session
[TikTok] 7044750503141444911: Downloading webpage
ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\tiktok.py", line 112, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Trying to download anything from TikTok seems to result in an error (ERROR: Unable to extract data). I tried this with multiple different links, checking that they work in the browser. Also tried to download them separately, without my user configuration, and all in one big bunch, but it didn't seem to help. It would appear that TikTok has implemented a Captcha system on the site because I had to pass it a few times over the course of testing and I suspect that it might be the reason why it is not working properly.

After trying out a multiple of links that I had saved up, I looked up a new link that was popular on the site and inserted that into the command line. It resulted in a similar verbose log and didn't work. I selected one that was quite popular and didn't seem to have any people in it to protect people's identities. Here's the link to that video: https://www.tiktok.com/@karenlafleur/video/6913759091974262022

**Comment by 89z** [comment]
I have an alternate tool that works:

~~~
PS C:\> tiktok -i 7044750503141444911
GET http://api2.musical.ly/aweme/v1/aweme/detail/?aweme_id=7044750503141444911
Author: imchase6
Create_Time: 2021-12-22 22:29:55 -0600 CST
Duration: 5.106s
Width: 532
Height: 1072
URL_List:
- https://v16m-default.akamaized.net/ee9bcc6bd6eb90e336901cf1ef1a193e/61cc0183/video/tos/maliva/tos-maliva-ve-0068c799-us/26b32333bc12450ba10a691da5883d14/?a=0&br=2558&bt=1279&cd=0%7C0%7C0&ch=0&cr=0&cs=0&cv=1&dr=0&ds=6&er=&ft=~pxS9z4Hh~06B8exqp6HJPD1&l=2021122900343901018905301603FD5780&lr=all&mime_type=video_mp4&net=0&pl=0&qs=0&rc=amRldzY6ZjV5OjMzZzczNEApaTtlOmc2OGRkN2Y2PDVkOWdubF9jcjRfai5gLS1kMS9zczEyYi5hYmEtM2NfNTMzM2A6Yw%3D%3D&vl=&vr=
- https://v16m.byteicdn.com/ee9bcc6bd6eb90e336901cf1ef1a193e/61cc0183/video/tos/maliva/tos-maliva-ve-0068c799-us/26b32333bc12450ba10a691da5883d14/?a=0&br=2558&bt=1279&cd=0%7C0%7C0&ch=0&cr=0&cs=0&cv=1&dr=0&ds=6&er=&ft=~pxS9z4Hh~06B8exqp6HJPD1&l=2021122900343901018905301603FD5780&lr=all&mime_type=video_mp4&net=0&pl=0&qs=0&rc=amRldzY6ZjV5OjMzZzczNEApaTtlOmc2OGRkN2Y2PDVkOWdubF9jcjRfai5gLS1kMS9zczEyYi5hYmEtM2NfNTMzM2A6Yw%3D%3D&vl=&vr=
- https://api16-normal-c-useast1a.tiktokv.com/aweme/v1/play/?video_id=v12044gd0000c71vm2bc77u3ftbboaqg&line=0&is_play_url=1&source=PackSourceEnum_AWEME_DETAIL&file_id=6ca6269638cb4fa6a05d3edd71be85f4
~~~

https://github.com/89z/mech

**Comment by Janitsu** [comment]
Thanks @89z, I'll take a look at it 👍

**Comment by dirkf** [comment]
TikTok may unpredictably serve different page versions.

Duplicate of #30251.

**Comment by apogay37** [comment]
@dirkf, it was "sometimes". I had to do up to 6 attempts to download one video. But now it doesn't work at all.  
Applied your patch https://github.com/ytdl-org/youtube-dl/issues/30251#issuecomment-976947005 and it works every time now.    
Thanks.

**Comment by dirkf** [comment]
That's consistent with what was observed in #30251, ie the same page being served using two different JS framework technologies.

**Comment by Menard01** [comment]
Ok that's the same problem I have today to well begin the new year !!! Happy new year they said :(
