### ISSUE TITLE
TikTok Error

### ISSUE THREAD

**Issue by UnixCro** [ytdl-org/youtube-dl#30445]
```
~/files/Tiktok $ youtube-dl --verbose https://vm.tiktok.com/ZM8Kf5sqY/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://vm.tiktok.com/ZM8Kf5sqY/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.1 (CPython) - Linux-4.14.87+-armv8l-with-libc
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1
[debug] Proxy map: {}
[generic] ZM8Kf5sqY: Requesting header
[redirect] Following redirect to https://www.tiktok.com/@elektrokurzschluss/video/7042661503035526406?_d=secCgwIARCbDRjEFSACKAESPgo8Py%2BWHrKmQ8k916xwcDBjDWlzWI3uyW3d84Z2wwgZBwA6dO9mCxynY1r%2BVVrZKE4rOvdHB5S4NR7cJt0sGgA%3D&language=de&preview_pb=0&sec_user_id=MS4wLjABAAAAwkLYynP5HnlwKtmz4yBJ6cCjmTTfkDfupLpi6htOTGYDBqQw03ruYBKCSem4mD-x&share_app_id=1233&share_item_id=7042661503035526406&share_link_id=5391ca27-a864-405f-84d3-8fec6466ad88&source=h5_m&timestamp=1640954903&u_code=de7i359c99ad13&user_id=6866698620222948358&utm_campaign=client_share&utm_medium=android&utm_source=copy&_r=1
[TikTok] Setting up session
[TikTok] 7042661503035526406: Downloading webpage
ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/youtube_dl/extractor/tiktok.py", line 110, in _real_extract
    page_props = self._parse_json(self._search_regex(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment]
Duplicate of #30251, where a patch that [appears to work](https://github.com/ytdl-org/youtube-dl/issues/30439#issuecomment-1003349234) is provided.

**Comment by 89z** [comment]
I have an alternate tool that works:

~~~
PS C:\> tiktok 7042661503035526406
GET http://api2.musical.ly/aweme/v1/aweme/detail/?aweme_id=7042661503035526406
GET http://v16m-default.akamaized.net/a99e8db45291a5293145c9a2a0710399/61cf7de8/video/tos/useast2a/tos-useast2a-pve-0068/51931beb812543279c0fe48e3a7cbf21/
~~~

https://github.com/89z/mech

**Comment by UnixCro** [comment]
No thx

**Comment by p1ratrulezzz** [comment]
Applied patch from  [#30251 (comment)](https://github.com/ytdl-org/youtube-dl/issues/30251#issuecomment-976947005) and it worked for me.

Tutorial: 
1. Save patch as /tmp/tiktok.patch. Open it and change first lines as following:
```
--- old/youtube-dl/youtube_dl/extractor/tiktok.py
+++ new/youtube-dl/youtube_dl/extractor/tiktok.py
```

to 

```
--- old/extractor/tiktok.py
+++ new/extractor/tiktok.py
```
2. if you use venv - activate it by 
```bash
source venv/bin/activate
```
2. Find out site-packages folder location by running
```bash
venv_dir=$(python3 -c "import sysconfig; print(sysconfig.get_path('purelib'))")
echo $venv_dir
```
4. change dir to site-packages and apply the patch
```bash
cd $venv_dir/youtube_dl
patch -p1 < /tmp/tiktok.patch
```
5. It should work now.

**Comment by 89z** [comment]
@fstirlitz I see your little downvote. One day you are going to realize that downvoting me, and doxxing me [1], is not going to stop me from trying to help people.

1. https://github.com/ytdl-org/youtube-dl/issues/30398#issuecomment-1003400328

**Comment by dirkf** [comment]
>Save patch as /tmp/tiktok.patch. (or download attachment). Open it and change first lines as following:

Or use `patch -p2 ...` later on (step 4). `-p` says how many of the leading directories in the patch script to strip when finding the file to be patched, which obviously depends on where the patch is relative to the package being patched.

**Comment by p1ratrulezzz** [comment]
> `-p` says how many of the leading directories in the patch script to strip

Thanks, for some reason I didn't even try to check manual, just was using p1 as I got used to many years ago. Now it I knew something new! 

Yes, I believe people mostly use pip to install this package, as I'm not a python dev I even searched if there is a way to say pip to apply patch but haven't found anything. I hope the solution is temporary unless it will be fixed someday... 

I also checked solution with go script by @89z and it also works, I was able to build it under ubuntu 20.04 and go 1.17 but it lacks of some nice paratemeters like "set output filename" or download using shortcut as youtube-dl does.

**Comment by 89z** [comment]
> I also checked solution with go script by @89z and it also works, I was able to build it under ubuntu 20.04 and go 1.17 but it lacks of some nice paratemeters like "set output filename"

@p1ratrulezzz this is fixed now:

~~~
PS C:\> tiktok -o output.mp4 7042661503035526406
GET http://api2.musical.ly/aweme/v1/aweme/detail/?aweme_id=7042661503035526406
GET http://v16m-default.akamaized.net/a8b3bfff48d6af93cd965e3137c43d03/61cfb6ad/video/tos/useast2a/tos-useast2a-pve-0068/51931beb812543279c0fe48e3a7cbf21/
~~~

https://github.com/89z/mech

**Comment by p1ratrulezzz** [comment]
wow thanks! I'll use it in bot, I was about to add this output argument by myself but you did it so fast and this is very nice!

**Comment by UnixCro** [comment]
I LOVE YOU DUDE. IT WORKED YOU A GENIUS BRO @p1ratrulezzz

**Comment by UnixCro** [comment]
Good Morning,

after the patch everything went as usual, but this morning I noticed that `youtube-dl` was getting problems, regardless of which Tiktok video.  It stops at `Session` and doesn't do anything anymore.

```
youtube-dl -v https://vm.tiktok.com/ZM8o81GJ6/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vm.tiktok.com/ZM8o81GJ6/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.1 (CPython) - Linux-4.14.87+-armv8l-with-libc
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1
[debug] Proxy map: {}
[generic] ZM8o81GJ6: Requesting header
[redirect] Following redirect to https://www.tiktok.com/@tal_dahan_98/video/7024900237076483329?_d=secCgwIARCbDRjEFSACKAESPgo8YrY3EKdj1E6gxwNUHIw1x1pyS1GuRWH%2B7yBvtTroH1PZUFsEa6LLl7vAD373o7DlJP0ex0LcUx3xx5RIGgA%3D&checksum=86caa7b721ef97df33eae17f7050f10a2df3b3563b7dbad85fc24c6108f71d6d&language=de&preview_pb=0&sec_user_id=MS4wLjABAAAAwkLYynP5HnlwKtmz4yBJ6cCjmTTfkDfupLpi6htOTGYDBqQw03ruYBKCSem4mD-x&share_app_id=1233&share_item_id=7024900237076483329&share_link_id=B9546FAF-D8BE-478F-B1D6-A82C83A8DCD6&source=h5_m&timestamp=1641475816&tt_from=copy&u_code=de7i359c99ad13&user_id=6866698620222948358&utm_campaign=client_share&utm_medium=ios&utm_source=copy&_r=1
[TikTok] Setting up session
```

Has anyone noticed the same bug?

**Comment by dirkf** [comment]
See #30251.

**Comment by UnixCro** [comment]
Thank you @dirkf.  But how exactly do I install the new version now?

**Comment by dirkf** [comment]
You have to replace the extractor module with the one from the PR. See https://github.com/ytdl-org/youtube-dl/pull/30479#issuecomment-1007495127.

**Comment by dirkf** [comment]
> ... (substitute PR number 30479 and file youtube_dl/extractor/tiktok.py as appropriate) ...

You installed PR #30184 instead of #30479!

**Comment by UnixCro** [comment]
Ah nice 😂😂. It worked @dirkf.  Hopefully 100 years with you.

```
pip install --force-reinstall -U git+https://github.com/ytdl-org/youtube-dl@refs/pull/30479/merge
```

**Comment by VasiliPupkin256** [comment]
@dirkf this PR doesn't work anymore. "Could not send HEAD request to https://www.tiktok.com/....: The read operation timed out"

**Comment by dirkf** [comment]
Indeed, that's why it hasn't been merged: #30538.
