### ISSUE TITLE
HRTi support?

### ISSUE THREAD

**Issue by IamMusavaRibica** [ytdl-org/youtube-dl#30448]
## Checklist
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
D:\YoutubeDL>youtube-dl -u hakadi1457@saturdata.com -p <hidden> --verbose https://hrti.hrt.hr/home?id=369683456
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--verbose', 'https://hrti.hrt.hr/home?id=369683456']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-103022-gf614390ecc-20210721, ffprobe N-103022-gf614390ecc-20210721
[debug] Proxy map: {}
[generic] home?id=369683456: Requesting header
WARNING: Falling back on generic information extractor.
[generic] home?id=369683456: Downloading webpage
[generic] home?id=369683456: Extracting information
ERROR: Unsupported URL: https://hrti.hrt.hr/home?id=369683456
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\generic.py", line 3489, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://hrti.hrt.hr/home?id=369683456



D:\YoutubeDL>youtube-dl -u hakadi1457@saturdata.com -p <hidden> --verbose https://hrti.hrt.hr/#/video/show/2181385/republika-dokumentarna-serija-16-hd
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--verbose', 'https://hrti.hrt.hr/#/video/show/2181385/republika-dokumentarna-serija-16-hd']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-103022-gf614390ecc-20210721, ffprobe N-103022-gf614390ecc-20210721
[debug] Proxy map: {}
[HRTi] Downloading uuid
ERROR: Unable to download uuid: <urlopen error [Errno 11001] getaddrinfo failed> (caused by URLError(gaierror(11001, 'getaddrinfo failed'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\utils.py", line 2581, in http_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
```
Yes, i know this looks unfinished, but it is the complete log https://prnt.sc/25fvpsa

## Description

First of all, I'm sure HRTi changed the way urls work because it is not that simple to get one anymore. To get a URL, one should share a resource (tv show) then open the url that copied, and after the redirect should get a URL with this format: https://hrti.hrt.hr/home?id=369683456

Judging by https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/hrti.py there should be a JSON client api located at http://clientapi.hrt.hr/client_api.php/config/identify/format/json, however seems like it got removed .
Last issue to mention this is #17275 and it is from 2018. Last commit to hrti.py was in 2019. The site changed much since. 
I would like support for HRTi.hrt.hr to be added

**Comment by dirkf** [comment]
The extractor isn't even running because it apparently expects `hrti:369683456`, `https://hrti.hrt.hr/video/show/369683456/stuff` or `https://hrti.hrt.hr/#/video/show/369683456/stuff`. Try the first one (with your credentials) to see how the extractor works today.

**Comment by IamMusavaRibica** [comment]
> The extractor isn't even running because it apparently expects `hrti:369683456`, `https://hrti.hrt.hr/video/show/369683456/stuff` or `https://hrti.hrt.hr/#/video/show/369683456/stuff`. Try the first one (with your credentials) to see how the extractor works today.

Unable to download UUID.

As i mentioned before, it is most likely outdated, since there is nothing at http://clientapi.hrt.hr/client_api.php/config/identify/format/json

**Comment by dirkf** [comment]
Definitely, then.

The existing extractor was inspired (according to comment at the top) by the site JS, so someone, possibly with site credentials, possibly in Croatia or the Balkans, is going to have to re-analyze the site to fix it.

**Comment by IamMusavaRibica** [comment]
Well, I used a temp-mail service to create a throwaway account. It worked.
As of right now, the site's frontend is sorted with webpack, and fetches
chunks of video from aviioon.tv
