### ISSUE TITLE
Tiktok 

### ISSUE THREAD

**Issue by Menard01** [ytdl-org/youtube-dl#30454]
`youtube-dl -v https://www.tiktok.com/@sweetbodymary4/video/7045707407799880965
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.tiktok.com/@sweetbodymary4/video/7045707407799880965']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-91-generic-x86_64-with-LinuxMint-20.2-uma
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[TikTok] Setting up session
[TikTok] 7045707407799880965: Downloading webpage
ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tiktok.py", line 112, in _real_extract
    webpage, 'data'), video_id)['props']['pageProps']
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by Menard01** [comment]
I am used to have some fails sometimes, but today it is constant

**Comment by kikuyan** [comment]
Duplicate of #30445, #30439.

**Comment by Menard01** [comment]
Now it appears you don't need youtube-dl ... you only have to right click on the tiktok and chose download the video :)

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30580
