### ISSUE TITLE
cannot download video from facebook url 

### ISSUE THREAD

**Issue by khitran-AB** [ytdl-org/youtube-dl#30474]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', '-F', 'https://www.facebook.com/groups/352666925484718/permalink/1112505706167499/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-91-generic-x86_64-with-glibc2.29
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 1112505706167499: Downloading webpage
Traceback (most recent call last):
  File "/home/videodl/vdl/vdl_env/bin/youtube-dl", line 8, in <module>
    sys.exit(main())
  File "/home/videodl/vdl/vdl_env/lib/python3.8/site-packages/youtube_dl/__init__.py", line 475, in main
    _real_main(argv)
  File "/home/videodl/vdl/vdl_env/lib/python3.8/site-packages/youtube_dl/__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/videodl/vdl/vdl_env/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "/home/videodl/vdl/vdl_env/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/home/videodl/vdl/vdl_env/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/videodl/vdl/vdl_env/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/videodl/vdl/vdl_env/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/videodl/vdl/vdl_env/lib/python3.8/site-packages/youtube_dl/extractor/facebook.py", line 680, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/home/videodl/vdl/vdl_env/lib/python3.8/site-packages/youtube_dl/extractor/facebook.py", line 499, in _extract_from_url
    parse_attachment(attachment)
  File "/home/videodl/vdl/vdl_env/lib/python3.8/site-packages/youtube_dl/extractor/facebook.py", line 480, in parse_attachment
    media = attachment.get(key) or {}
AttributeError: 'NoneType' object has no attribute 'get'

```

## Description

Youtube-dl was working with the same url, username and password. It stopped working recently. video url given in verbose.

**Comment by dirkf** [comment]
The Facebook extractor is pretty complicated and I have no idea which extraction technique stopped working.

However this patch gets a video from the problem page:
```
--- old/youtube-dl/youtube_dl/extractor/facebook.py
+++ new/youtube-dl/youtube_dl/extractor/facebook.py
@@ -591,6 +591,11 @@
             video_data = extract_from_jsmods_instances(tahoe_js_data)
 
         if not video_data:
+            twip = self._html_search_meta('twitter:player', webpage)
+            if twip:
+                return self.url_result(twip)
+
+        if not video_data:
             raise ExtractorError('Cannot parse data')
 
         if len(video_data) > 1:
```

**Comment by khitran-AB** [comment]
Thanx @dirkf it worked.

**Comment by wankio** [comment]
imported cookies still not working, some public page still downloadable , but some just failed, 



below is in private group
```
[facebook] 4743714749016405: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyc", line 475, in main
  File "youtube_dl\__init__.pyc", line 465, in _real_main
  File "youtube_dl\YoutubeDL.pyc", line 2068, in download
  File "youtube_dl\YoutubeDL.pyc", line 808, in extract_info
  File "youtube_dl\YoutubeDL.pyc", line 815, in wrapper
  File "youtube_dl\YoutubeDL.pyc", line 836, in __extract_info
  File "youtube_dl\extractor\common.pyc", line 534, in extract
  File "youtube_dl\extractor\facebook.pyc", line 680, in _real_extract
  File "youtube_dl\extractor\facebook.pyc", line 499, in _extract_from_url
  File "youtube_dl\extractor\facebook.pyc", line 480, in parse_attachment
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by dirkf** [comment]
I updated the patch above to add error-checking that should avoid the crash above, though that may not affect whether media are found.

**Comment by wankio** [comment]
edit like ur posted patch, still

```
C:\Users\GEN32UC>youtube-dl https://www.facebook.com/Ulquiorra123/videos/4743714749016405
[facebook] 4743714749016405: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyc", line 475, in main
  File "youtube_dl\__init__.pyc", line 465, in _real_main
  File "youtube_dl\YoutubeDL.pyc", line 2068, in download
  File "youtube_dl\YoutubeDL.pyc", line 808, in extract_info
  File "youtube_dl\YoutubeDL.pyc", line 815, in wrapper
  File "youtube_dl\YoutubeDL.pyc", line 836, in __extract_info
  File "youtube_dl\extractor\common.pyc", line 534, in extract
  File "youtube_dl\extractor\facebook.pyc", line 680, in _real_extract
  File "youtube_dl\extractor\facebook.pyc", line 499, in _extract_from_url
  File "youtube_dl\extractor\facebook.pyc", line 480, in parse_attachment
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by dirkf** [comment]
That seems unlikely: the line numbers would have changed.

**Comment by wankio** [comment]
i'm just edit file in : C:\Users\GEN32UC\AppData\Local\Programs\Python\Python38\Lib\site-packages\youtube_dl\extractor\facebook.py

**Comment by dirkf** [comment]
Try:
```
cd C:\Users\GEN32UC\AppData\Local\Programs\Python\Python38\Lib\site-packages
python -m youtube_dl ...
```
where `...` are all the options you'd put after youtube-dl.exe.

If that does something different:
```
where youtube-dl.exe
```

**Comment by wankio** [comment]
nvm i found it, in enviroment path there was standalone exe, just delete it and look like my edited file is wrong

```
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python38\Scripts\youtube-dl.exe\__main__.py", line 4, in <module>
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python38\lib\site-packages\youtube_dl\__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python38\lib\site-packages\youtube_dl\extractor\__init__.py", line 9, in <module>
    from .extractors import *
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python38\lib\site-packages\youtube_dl\extractor\extractors.py", line 65, in <module>
    from .ard import (
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python38\lib\site-packages\youtube_dl\extractor\ard.py", line 8, in <module>
    from .generic import GenericIE
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python38\lib\site-packages\youtube_dl\extractor\generic.py", line 91, in <module>
    from .facebook import FacebookIE
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python38\lib\site-packages\youtube_dl\extractor\facebook.py", line 498
    continue
           ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by dirkf** [comment]
Ideally, save the patch as a text file and apply it with [_patch_](https://stackoverflow.com/questions/517257/how-do-i-apply-a-diff-patch-on-windows).

In an editor, set the option to use spaces only and not tabs.

**Comment by wankio** [comment]
```
C:\Users\GEN32UC>youtube-dl https://www.facebook.com/Ulquiorra123/videos/4743714749016405 --verbose
[debug] System config: []
[debug] User config: ['-o', 'I:/youtube-dl/%(extractor)s/%(title)s-%(uploader)s-%(channel_id)s-%(channel)s-%(id)s.%(ext)s', '-f', 'bestvideo[height<=?1080]+bestaudio/best', '--write-thumbnail', '--cookies', 'C:/Users/GEN32UC/AppData/Roaming/youtube-dl/cookies.txt', '--write-sub', '--write-auto-sub', '--sub-lang', 'en-GB']
[debug] Custom config: []
[debug] Command-line args: ['https://www.facebook.com/Ulquiorra123/videos/4743714749016405', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.2 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-92966-gd52a1be4e3, ffprobe N-92966-gd52a1be4e3
[debug] Proxy map: {}
[facebook] 4743714749016405: Downloading webpage
[download] Downloading playlist: 4743714749016405
[facebook] playlist 4743714749016405: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: 4743714749016405
```

no video still

**Comment by marcelosomers** [comment]
@dirkf I applied your patch above but it appears this isn't working with private videos where it was working a few weeks back same as @wankio. Instead of throwing the error (before the patch) it doesn't seem to find the video on the page.

```
~ youtube-dl --cookies ~/Desktop/facebook.com_cookies.txt -a files.txt                                           
[facebook] 667930413557652: Downloading webpage
[download] Downloading playlist: 667930413557652
[facebook] playlist 667930413557652: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: 667930413557652
```

Is it ok to post a private video here? Not sure how much that might help.

**Comment by wankio** [comment]
and looks like with cookies imported, my account always get checkpoint, i will try use clone account without 2auth to see if this really caused checkpoint

**Comment by dirkf** [comment]
>...  checkpoint ...

Do you mean a Python backtrace? Anyhow, let us know what happens in your test.

**Comment by wankio** [comment]
tried download these vids from public profile https://www.facebook.com/iris.void.12/videos with cookies from clone acc no 2auth, 2 videos downloaded without any problems and then it can't download anymore, i think facebook detected BOT then flagged account, -> checkpoint aka locked

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30650

**Comment by SwapnilSoni1999** [comment]
facing same

**Comment by sskras** [comment]
Applied @dirkf [patch](https://github.com/ytdl-org/youtube-dl/issues/30474#issuecomment-1006525415).
Same, it collects 0 video ids with the patch:
```
$ youtube-dl -v https://www.facebook.com/groups/633618889989485/posts/7333128686705105
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.facebook.com/groups/633618889989485/posts/7333128686705105']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.10 (CPython) - Windows-10-10.0.19042-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 7333128686705105: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 7333128686705105: Downloading webpage
[generic] 7333128686705105: Extracting information
[facebook] 639013017349591: Downloading webpage
[download] Downloading playlist: 639013017349591
[facebook] playlist 639013017349591: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: 639013017349591
```

**Comment by 89z** [comment]
@sskras please open a new issue, or comment on one of the open Facebook issues.
