### ISSUE TITLE
Unable to extract and use metadata like title, description, etc from facebook videos

### ISSUE THREAD

**Issue by elpresti** [ytdl-org/youtube-dl#30472]
Hello team, since about one month ago I'm unable to get and use some metadata from the videos that I download from Facebook using your app.
It results on NA or empty or uses a VideoID number, but we can't get basic info like title or description from videos. In the past it was working good, but since a month ago it started to replace that data with out the expected data.
Some extra info and examples:
**C:\Temp\tmp>youtube-dl.exe --version**
2021.12.17

**C:\Temp\tmp>youtube-dl.exe --write-info-json https://es-la.facebook.com/bbcnews/videos/961274387845017/**
[facebook] 961274387845017: Downloading webpage
[download] Downloading playlist: 961274387845017
[facebook] playlist 961274387845017: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[info] Writing video description metadata as JSON to: Facebook video #961274387845017-961274387845017.info.json
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: Facebook video #961274387845017-961274387845017.f419123339909945v.webm
[download] 100% of 37.43MiB in 00:03
[download] Destination: Facebook video #961274387845017-961274387845017.f630290158419467a.m4a
[download] 100% of 1.14MiB in 00:00
[ffmpeg] Merging formats into "Facebook video #961274387845017-961274387845017.mkv"
Deleting original file Facebook video #961274387845017-961274387845017.f419123339909945v.webm (pass -k to keep)
Deleting original file Facebook video #961274387845017-961274387845017.f630290158419467a.m4a (pass -k to keep)
[download] Finished downloading playlist: 961274387845017

The results:
C:\Temp\tmp\Facebook video #961274387845017-961274387845017.info.json
C:\Temp\tmp\Facebook video #961274387845017-961274387845017.mkv

And the content of the .info.json file does not contains any title or description or any text from the post of the video, that we need to use to name the file properly.
Hope you can help me to solve this issue.
Thanks in advance, and your software rocks!

**Comment by kikuyan** [comment]
Duplicate of other issue reports, and there's a PR #29796. Using this PR, you'd get:
```
... -j | jq "{title, description}"
{
  "title": "Bangkok station reaches the end of the line",
  "description": "Hua Lamphong railway station in Bangkok is closing most of its routes after more than 100 years of service.   https://bbc.in/3Hzz5Es"
}
```
But it might be better to try yt-dlp, though I don't know if the problem has been resolved.

**Comment by dirkf** [comment]
https://github.com/yt-dlp/yt-dlp/commit/a181cd0c600409a11f3f5e8448eaef4c63fdf1ed, apparently.

**Comment by elpresti** [comment]
@kikuyan I'm not sure if that issue is exactly the same, at least they can extract %(title), but it is pretty close to mine, that's why I have created a new bug. Anyway, don't care, thanks for your proposal, but how can I test the solution in PR#29796? because I need it to execute using the "youtube-dl.exe" version. Is this fix already done and will be included in future releases? cause I'm using the last EXE but it's not working.

By the way, thanks @kikuyan and @dirkf for recommending yt-dlp, I didn't knew about the existence of it, but unfortunately I'm not being able to make it work on my PC with the EXE that they provide:
**C:\Temp\tmp>yt-dlp.exe -version**
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 17, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "multiprocessing\__init__.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "multiprocessing\context.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "multiprocessing\reduction.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "socket.py", line 49, in <module>
ImportError: DLL load failed while importing _socket: El parámetro no es correcto.
[8464] Failed to execute script 'pyi_rth_multiprocessing' due to unhandled exception!

Do you know what can I do to make it work?
Thanks in advance!
Regards!

**Comment by 89z** [comment]
@elpresti thats a known issue with Python 3.10, workaround is to use Python 3.9

https://bugs.python.org/issue46276

**Comment by dirkf** [comment]
Good catch! Unfortunately I expect that the Python version is coming from the yt-dlp self-extracting archive so there isn't any choice here, without installing (eg) Python 3.9 and then installing yt-dlp in a Pythonic way, _pip_ or whatever.

To clarify, the `_socket` module being unpacked from the yt-dlp self-extracting archive expects a different version of some DLL from the one that is installed, and so `El parámetro no es correcto`. It may depend on the Windows version. `iphlpapi.dll`, mentioned in the Python issue, does seem like something `_socket` might want to use. Best to follow this up in the yt-dlp tracker. Note that there are at least two yt-dlp downloads for Windows, so you could try a different one.

Problems like this remind us what an enormous amount of work is saved for Python programmers by the Python library that largely hides weird behaviour of the underlying platform.

Anyhow, yt-dlp is the best bet for a simple upgrade to solve OP's problem.

**Comment by kikuyan** [comment]
> Is this fix already done and will be included in future releases? 

Not merged or reviewed by the developer yet. Further, I think it will be hard to expect new releases since the development has been practically stopped.
