### ISSUE TITLE
Pluralsight Http Error 403

### ISSUE THREAD

**Issue by chrispaivacwb** [ytdl-org/youtube-dl#30487]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
D:\Videos\01 Programas\01 Youtube-dl>youtube-dl --add-header "Cookie:JSESSIONID=fe79b226abf08b92" "https://app.pluralsight.com/library/courses/powershell-getting-started/table-of-contents" --verbose --sleep-interval 120 --all-subs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--add-header', 'Cookie:JSESSIONID=fe79b226abf08b92', 'https://app.pluralsight.com/library/courses/powershell-getting-started/table-of-contents', '--verbose', '--sleep-interval', '120', '--all-subs']
[debug] Adding header from command line option Cookie:JSESSIONID=fe79b226abf08b92
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-07-13-7772666
[debug] Proxy map: {}
[pluralsight:course] powershell-getting-started: Downloading JSON metadata
[download] Downloading playlist: PowerShell: Getting Started
[pluralsight:course] playlist PowerShell: Getting Started: Collected 61 video ids (downloading 61 of them)
[download] Downloading video 1 of 61
[pluralsight] 3415d839-fb0c-4ca8-94b2-864e92da5d3f-0: Downloading JSON metadata
[pluralsight] 3415d839-fb0c-4ca8-94b2-864e92da5d3f-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] 3415d839-fb0c-4ca8-94b2-864e92da5d3f-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] 3415d839-fb0c-4ca8-94b2-864e92da5d3f-0: Waiting for 10 seconds to avoid throttling
[pluralsight] 3415d839-fb0c-4ca8-94b2-864e92da5d3f-0: Downloading captions JSON
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Course Overview-0337b16d-b196-406b-895d-57349a984c8f.en.srt
[debug] Invoking downloader on 'https://vid5.pluralsight.com/expiretime=1641701836/a00847d45adda700af9fda32e90848d9/clips/resolution/0337b16d-b196-406b-895d-57349a984c8f/current/mp4/1280x720.mp4'
[download] Sleeping 120 seconds...
[download] Destination: Course Overview-0337b16d-b196-406b-895d-57349a984c8f.mp4
[download] 100% of 3.56MiB in 00:03
[download] Downloading video 2 of 61
[pluralsight] powershell-getting-started-m1-0: Downloading JSON metadata
[pluralsight] powershell-getting-started-m1-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] powershell-getting-started-m1-0: Downloading mp4-high-widescreen viewclip JSON
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] powershell-getting-started-m1-0: Waiting for 10 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\pluralsight.py", line 421, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Tried to download pluralsight video using cookies and it fails after getting the first video of the playlist.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30540

**Comment by dirkf** [comment]
See also #29776.
