### ISSUE TITLE
youtube-dl saying can't find XML element title and crashed

### ISSUE THREAD

**Issue by acer2004** [ytdl-org/youtube-dl#30491]
$ youtube-dl --verbose --all-subs --embed-subs  https://www.paramountplus.com/shows/star-trek-prodigy/video/3htV4fvVt4Z8gDZHqlzPOGLSMgcGc_vy/star-trek-prodigy-dreamcatcher
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--all-subs', '--embed-subs', 'https://www.paramountplus.com/shows/star-trek-prodigy/video/3htV4fvVt4Z8gDZHqlzPOGLSMgcGc_vy/star-trek-prodigy-dreamcatcher']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-93678-g4b7166c9d5, ffprobe N-93678-g4b7166c9d5
[debug] Proxy map: {}
[CBS] 3htV4fvVt4Z8gDZHqlzPOGLSMgcGc_vy: Downloading XML
ERROR: Could not find XML element title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\cbs.py", line 115, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\cbs.py", line 65, in _extract_video_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\utils.py", line 1911, in xpath_text
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\utils.py", line 1904, in xpath_element
youtube_dl.utils.ExtractorError: Could not find XML element title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by kikuyan** [comment]
Duplicate of #30066, etc.
PR #30085.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30066

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30247

**Comment by 89z** [comment]
This is a literal duplicate of #30247, its even the same URL

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29454

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29351

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29223

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29089
