### ISSUE TITLE
tele5.de

### ISSUE THREAD

**Issue by dsan0815** [ytdl-org/youtube-dl#30499]
## Checklist
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose  -F https://tele5.de/mediathek/gene-roddenberrys-andromeda/der-aussatzige/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-F', 'https://tele5.de/mediathek/gene-roddenberrys-andromeda/der-aussatzige/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Using fake IP 53.176.250.227 (DE) as X-Forwarded-For.
[Tele5] der-aussatzige: Downloading webpage
ERROR: Unable to extract jwplatform id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\tele5.py", line 102, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\tele5.py", line 95, in extract_id
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1021, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract jwplatform id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

via powershell

youtube-dl -F https://tele5.de/mediathek/gene-roddenberrys-andromeda/der-aussatzige/

[Tele5] der-aussatzige: Downloading webpage
ERROR: Unable to extract jwplatform id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by efferle** [comment]
Same here, with the exact same output submitted by dsan0815. As youtube-dl worked perfectly early this morning -- @ about 3:00 a.m. -- it seems the TV channel Tele5 changed it's back end during the day, as well as their obvious redesigned front end.

**Comment by Joker52** [comment]
Same here 22.01.11 22:45
C:\Program Files (x86)\YDG>youtube-dl -f bestvideo+bestaudio/best https://tele5.de/mediathek/angel-of-mine/ -v --no-check-certificate
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo+bestaudio/best', 'https://tele5.de/mediathek/angel-of-mine/', '-v', '--no-check-certificate']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Using fake IP 53.252.110.156 (DE) as X-Forwarded-For.
[Tele5] angel-of-mine: Downloading webpage
ERROR: Unable to extract jwplatform id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\tele5.py", line 102, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\tele5.py", line 95, in extract_id
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1021, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract jwplatform id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
C:\Program Files (x86)\YDG>

**Comment by dirkf** [comment]
Apparently tele5.de is (now) just another Discovery Networks site and can be handled using the DPlayIE extractor, as attached (added `.txt` needed to satisfy GH).

With this technique, 'Angel of Mine' can be extracted, but the Andromeda show gives `ERROR: Missing deviceId in context`, which may indicate either a further level of handshake needed for precious content, or DRM: see also #26186.

The test URL `https://www.tele5.de/mediathek/filme-online/videos?vid=1549416` is no longer available, so a valid replacement would be good for testing; or perhaps this URL format is no longer used.

[tele5.py.txt](https://github.com/ytdl-org/youtube-dl/files/7851523/tele5.py.txt)

**Comment by Gloster10** [comment]
a valid replacement :  https://tele5.de/mediathek/jack-hunter-das-zepter-des-lichts/

**Comment by dirkf** [comment]
That URL gives the 'deviceId' error; also what I was asking for was a show whose URL is like '.../mediathek/filme-online/videos?vid=...'

**Comment by Gloster10** [comment]
There is no one anymore

**Comment by pukkandan** [comment]
https://tele5.de/mediathek/angel-of-mine

**Comment by rsc27** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30499#issuecomment-1011029275

I do not agree - there is still one to find. You have simply move to "all parts of the series"
Example is for one of the currently available...

https://tele5.de/mediathek/gene-roddenberrys-andromeda/die-wahrheitsliebenden/

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30604
