### ISSUE TITLE
ServusTV

### ISSUE THREAD

**Issue by Ciccione70** [ytdl-org/youtube-dl#30493]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
command line used:

youtube-dl.exe https://www.servustv.com/unterhaltung/v/aa-1xxrnzgy11w12/

[debug] System config: []
[debug] User config: ['--no-check-certificate', '--geo-bypass-country', 'DE', '-
-hls-prefer-native', '--ffmpeg-location', 'C:\\Program Files (x86)\\Multimedia\\
FFMPEG\\bin']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.servustv.com/unterhaltung/v/aa-1x
xrnzgy11w12/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-93439-gb073fb9eea, ffprobe N-93439-gb073fb9eea
[debug] Proxy map: {}
[debug] Using fake IP 53.107.214.156 (DE) as X-Forwarded-For.
[generic] aa-1xxrnzgy11w12: Requesting header
WARNING: Falling back on generic information extractor.
[generic] aa-1xxrnzgy11w12: Downloading webpage
[generic] aa-1xxrnzgy11w12: Extracting information
WARNING: [generic] aa-1xxrnzgy11w12: Failed to parse JSON Expecting ',' delimite
r: line 1 column 1790 (char 1789)
ERROR: Unsupported URL: https://www.servustv.com/unterhaltung/v/aa-1xxrnzgy11w12
/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c
6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c
6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c
6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c
6w\build\youtube_dl\extractor\generic.py", line 3489, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.servustv.com/unt
erhaltung/v/aa-1xxrnzgy11w12/

## Description

WRITE DESCRIPTION HERE
Download of videos from ServusTV.com doesn't work. 
Apparently something has changed there!

**Comment by dirkf** [comment]
Duplicate of #29485, and see also #30245, PR #29556.

**Comment by flashdagger** [comment]
Aaaaand #30436 ...

**Comment by dirkf** [comment]
I didn't mention that issue as it doesn't show the same error and according to the PR author isn't reproducible with the PR installed. If there is any evidence to contrary it would be useful to submit it as a comment on the PR.

**Comment by AlphaTucanae** [comment]
The problem is actual again, tested with the following links (only log of the first is inserted below):

https://www.servustv.com/unterhaltung/v/aa6g2nyt5ktnzuspwkjg/
https://www.servustv.com/volkskultur/b/hoagascht/aa-1q22345s91w11/

In both cases, and different to the original verbose log of this issue, a "Failed to parse JSON Expecting property name enclosed in double quotes" is added in the log.

```
C:\>youtube-dl -v "https://www.servustv.com/unterhaltung/v/aa6g2nyt5ktnzuspwkjg/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.servustv.com/unterhaltung/v/aa6g2nyt5ktnzuspwkjg/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-107944-g4fce3bab64-20220830, ffprobe N-107944-g4fce3bab64-20220830
[debug] Proxy map: {}
[generic] aa6g2nyt5ktnzuspwkjg: Requesting header
WARNING: Falling back on generic information extractor.
[generic] aa6g2nyt5ktnzuspwkjg: Downloading webpage
[generic] aa6g2nyt5ktnzuspwkjg: Extracting information
WARNING: [generic] aa6g2nyt5ktnzuspwkjg: Failed to parse JSON Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
ERROR: Unsupported URL: https://www.servustv.com/unterhaltung/v/aa6g2nyt5ktnzuspwkjg/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\generic.py", line 3489, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.servustv.com/unterhaltung/v/aa6g2nyt5ktnzuspwkjg/
```
