### ISSUE TITLE
NDR.de downloads broken

### ISSUE THREAD

**Issue by jtotht** [ytdl-org/youtube-dl#30512]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```console
$ youtube-dl --verbose https://www.ndr.de/fernsehen/sendungen/grossstadtrevier/Der-Weihnachtsmuffel,weihnachtsmuffel108.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.ndr.de/fernsehen/sendungen/grossstadtrevier/Der-Weihnachtsmuffel,weihnachtsmuffel108.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-18-amd64-x86_64-with-debian-10.11
[debug] exe versions: ffmpeg 4.1.8-0, ffprobe 4.1.8-0
[debug] Proxy map: {}
[ndr] Der-Weihnachtsmuffel: Downloading webpage
[generic] weihnachtsmuffel108-ardplayer: Requesting header
WARNING: Falling back on generic information extractor.
[generic] weihnachtsmuffel108-ardplayer: Downloading webpage
[generic] weihnachtsmuffel108-ardplayer: Extracting information
ERROR: Unsupported URL: https://www.ndr.de/fernsehen/sendungen/grossstadtrevier/weihnachtsmuffel108-ardplayer.html
Traceback (most recent call last):
  File "/var/www/html/youtube-dl/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2477, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/var/www/html/youtube-dl/bin/youtube-dl/youtube_dl/compat.py", line 2571, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/var/www/html/youtube-dl/bin/youtube-dl/youtube_dl/compat.py", line 2560, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 15, column 65
Traceback (most recent call last):
  File "/var/www/html/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/var/www/html/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/var/www/html/youtube-dl/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/var/www/html/youtube-dl/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3489, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.ndr.de/fernsehen/sendungen/grossstadtrevier/weihnachtsmuffel108-ardplayer.html
```

## Description

It looks like it can correctly extract the URL https://www.ndr.de/fernsehen/sendungen/grossstadtrevier/weihnachtsmuffel108-ardplayer.html from the page https://www.ndr.de/fernsehen/sendungen/grossstadtrevier/Der-Weihnachtsmuffel,weihnachtsmuffel108.html, but then it uses the generic extractor for that second download instead of the NDR one. Changing [line 294 of extractor/ndr.py](https://github.com/ytdl-org/youtube-dl/blob/11f3471c4be16d0f848c72a4b4915f5f81d4f337/youtube_dl/extractor/ndr.py#L294) to
```python
_VALID_URL = r'https?://(?:www\.)?ndr\.de/(?:[^/]+/)*(?P<id>[\da-z]+)-(?:player|externalPlayer|ardplayer)\.html'
```
(i.e. to include `|ardplayer`) seems to fix the issue.

**Comment by dirkf** [comment]
Exactly. Or insert `(?:ard)?` before `player.

Several of the extractor tests fail even after this fix. More work needed.

In particular the `audio51535` main page has no `embedUrl` now and we have to invent one: it looks like `'https://www.ndr.de/info/%s-player.html' % 'audio51535'` should work but it may not work in general.
