### ISSUE TITLE
YouTube Music

### ISSUE THREAD

**Issue by skjhfds** [ytdl-org/youtube-dl#30523]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://music.youtube.com/playlist?list=OLAK5uy_kCojn7glfsyciYDykEr5JHWbM8YfGLSnM']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.6 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2.2.2
[debug] Proxy map: {}
[youtube:tab] OLAK5uy_kCojn7glfsyciYDykEr5JHWbM8YfGLSnM: Downloading webpage
[download] Downloading playlist: Album - Commodores
[youtube:tab] playlist Album - Commodores: Downloading 9 videos
[download] Downloading video 1 of 9
[youtube] E6n4pkqXdoo: Downloading webpage
WARNING: Unable to download webpage: HTTP Error 429: Too Many Requests
[youtube] E6n4pkqXdoo: Downloading API JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\hc\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\hc\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\hc\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\users\hc\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\youtube.py", line 1733, in _real_extract
    self._sort_formats(formats)
  File "c:\users\hc\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Up until recently, probably 1 or 2 days ago, yt-dl could download music from music.youtube.com (YouTube Music). Now it cannot. I'm guessing this is due to some new security measures from their end. I hope this issue is resolved.

**Comment by dirkf** [comment]
WFM, but then I haven't made `HTTP Error 429: Too Many Requests`.
