### ISSUE TITLE
TikTok: youtube-dl hangs after "Requesting Header"

### ISSUE THREAD

**Issue by hessijames79** [ytdl-org/youtube-dl#30538]
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

$ youtube-dl -v 'https://vm.tiktok.com/ZMLesneqK/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vv', 'https://vm.tiktok.com/ZMLesneqK/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-10-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ZMLesneqK: Requesting header
`

## Description
After Requesting header, youtube-dl hangs forever.

**Comment by 89z** [comment]
I have an alternative tool that works:

~~~
PS C:\> tiktok 7054218882072055046
GET http://api2.musical.ly/aweme/v1/aweme/detail/?aweme_id=7054218882072055046
GET http://v16m-default.akamaized.net/bb1e3c559856a6d6935094a7a3aa0d5e/61e76899/video/tos/useast2a/tos-useast2a-pve-0068/f0c23a741a524610965084b623dae3cc/
~~~

https://github.com/89z/mech

**Comment by dirkf** [comment]
This looks like a wider occurrence of this noted in PR #30479:

>Also, extraction could fail with a timeout (Error 60 in Windows, SSLError('The read operation timed out',) in Linux) or connection reset (Error 54 in Windows) due to some weird blocking by whatever fronts TikTok's pages (Akamai, apparently).

OP's URL isn't known to the TT extractor, so the error occurs in the generic extractor. However, even if the TT extractor does handle the URL the same error occurs.

More research needed.

The tool illustrated above uses an API that doesn't have this problem. If, as with some YT APIs, this API can't currently be changed because of unmodifiable deployed clients, the API may be a safer target.

**Comment by 89z** [comment]
Running MITM Proxy with this:

~~~
youtube-dl --proxy 127.0.0.1:8080 --no-check-certificate https://vm.tiktok.com/ZMLesneqK/
~~~

returns this request:

~~~
GET /@eddysayi/video/7054218882072055046?_d=secCgwIARCbDRjEFSACKAESPgo8Ny%2BRiWmH3OT6VFDDOKQe%2FjdU6QNg2QvER6kPZv8%2BV8iBx6SaSGyiLedX5PcIDqwq0EOwLe84aH6c7rDnGgA%3D&checksum=f558941cd65da22b6359be076ef87f6ffe1d4188d600d52331e2263cc6baa1a8&language=de&preview_pb=0&sec_user_id=MS4wLjABAAAAOkEM5UFx0tM8hhBkjW8D1xAadF1RU12kEXRBL0Kub2pz70wmTYEXuYh8MdtS57Vj&share_app_id=1233&share_item_id=7054218882072055046&share_link_id=EA78C111-0165-44E0-9A7F-D0FC02C4B110&source=h5_m&timestamp=1642491289&tt_from=copy&u_code=dh6jgh57j8hf20&user_id=6931555450693420037&utm_campaign=client_share&utm_medium=ios&utm_source=copy&_r=1 HTTP/1.1
Host: www.tiktok.com
Cookie: tt_csrf_token=ktN2OjWZZMQWAGM6D2GZwNBC; ttwid=1%7CqIiscS4pgQeTVk0uFHAX0l-KEk7oZgOe0LjnRPn8oL4%7C1642543728%7C29167665eddcfc5e466b61d76dfff4becb4c372ad4123ebb79b8e3945034cbff; msToken=jp-iTbOp2KWQYpZbeWPqSsbht2F31vyZZdyqLNEc1D7NV_95N7Q7FabFmHi6t9Y1exG-ZYhVHt9kpuekhiBczl0xIhvnBS_NtSDjxyX1T4rFJyMU9FfiUm4=; _abck=FB3DD3C5B399B2EF619C7EEC07796561~-1~YAAQWjkvF0VD+Wt+AQAAwkc8bwe9JtJ9/ZBw7Nx1GU05VSIDzIcB15En3jv12fqnOI1mBvlm5vbSMIOOWfvfqM4EmuxtBzpjgjElezBs05HVcmp2oPLH4riG6GWfEQ6SQ/1WTuRQc7EwuZg7jDlxiKgK8A4Ip9nLuaXywJLCNU8ZXqk4viYmGppJu2Kxv05OoI8AKUe6tYS0U6o+4JnskuoA5GuGcl97Iocq4u8TrnZyRTAElrU948WV6SJqFrU+5lNVUN6gAd1GM8HWWMwFlxC26rwRTvzZStK9WWf+RTs+dmUXQyXZDibfIzHR4U9FhPhBWtJ7Zdk5wPOgiQYof1aDEcG5Es/rhMTKIm+3JKUy7FtZsfRdFLLo+s0=~-1~-1~-1; bm_sz=D3DA201CB162136CA131CF18B14CFDD0~YAAQWjkvF0ZD+Wt+AQAAwkc8bw4/IrqlYMKwpTpoozbYFFtw3Sl57pGUO9D6MK2gf/eY/VB/YRCSUdlhDA1tIZkWbzCVV2Qgp8pM3y78kSkbdnziiv/d+E1vBoC601NSnEUYgGLWpEy3NY50QlJu2NefoeI/Nxu33WEQqik50K8aqbV/Jj+9xC5UFl9sCIwhso86e4xGC/eGHkS6ZaRRlxIjax0LbfgIgX28AHmoGucoZxhXtrXGD0qBoyMcM4eC7b2fESV3yA6cFTSQpigqnyI72d4mk6PIjuIYK0idVJo3gBE=~3424565~3552560
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3530.4 Safari/537.36
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-us,en;q=0.5
Connection: close
content-length: 0
~~~

which does hang for me as well. YouTube-DL seems to be using wrong User-Agent, as well as adding a bunch of extra bullshit to the request. Something like this works fine:

~~~
GET /@eddysayi/video/7054218882072055046 HTTP/1.1
Host: www.tiktok.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
~~~

**Comment by dirkf** [comment]
As to the headers:
* yt-dl  picks a random UA for each session, but it can be overridden; as detailed UAs are being deprecated yt-dl should eventually just send something like `Mozilla/5.0 (platform stuff) (like Gecko)`, but the time hasn't come yet;
* the `Accept` header is probably unnecessary, as is `Accept-Charset`;
* the `Cookie` comes from the 302 Redirect response to GET https://vm.tiktok.com/ZMLesneqK/, and actually is the reason why the yt-dl TT extractor makes a dummy request before trying to fetch the TT page itself, as TT gave 403 otherwise;
* the others seem to be reasonable, and none are incorrect according to protocol.

This piece of `utils.py` is relevant:
```
std_headers = {
    'User-Agent': random_user_agent(),
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'Accept-Encoding': 'gzip, deflate',
    'Accept-Language': 'en-us,en;q=0.5',
}
```
I wasn't been able to break through the block even by clearing headers deep in the Python HTTP routines, whereas apparently similar requests formulated with _curl_ or _wget_ are OK. Presumably whatever MITM Proxy does also passes the block.

yt-dlp uses the aweme API.

**Comment by 89z** [comment]
Not sure why this is so hard for you, but works fine here:

~~~py
import requests

headers = {
   'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0'
}

res = requests.get(
   'http://www.tiktok.com/@eddysayi/video/7054218882072055046', headers=headers
)

print(res.text)
~~~

**Comment by hessijames79** [comment]
Hi!

Apparently, changing the user agent is the only change needed to fix it:

```
youtube-dl -v --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0""https://vm.tiktok.com/ZMLesneqK/"

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0', 'https://vm.tiktok.com/ZMLesneqK/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-10-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ZMLesneqK: Requesting header
[redirect] Following redirect to https://www.tiktok.com/@eddysayi/video/7054218882072055046?_d=secCgwIARCbDRjEFSACKAESPgo8Ny%2BRiWmH3OT6VFDDOKQe%2FjdU6QNg2QvER6kPZv8%2BV8iBx6SaSGyiLedX5PcIDqwq0EOwLe84aH6c7rDnGgA%3D&checksum=f558941cd65da22b6359be076ef87f6ffe1d4188d600d52331e2263cc6baa1a8&language=de&preview_pb=0&sec_user_id=MS4wLjABAAAAOkEM5UFx0tM8hhBkjW8D1xAadF1RU12kEXRBL0Kub2pz70wmTYEXuYh8MdtS57Vj&share_app_id=1233&share_item_id=7054218882072055046&share_link_id=EA78C111-0165-44E0-9A7F-D0FC02C4B110&source=h5_m&timestamp=1642491289&tt_from=copy&u_code=dh6jgh57j8hf20&user_id=6931555450693420037&utm_campaign=client_share&utm_medium=ios&utm_source=copy&_r=1
[TikTok] 7054218882072055046: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://v16-webapp.tiktok.com/1ffb32527bc5dff792ca125bb76ac0f8/61e84c1c/video/tos/useast2a/tos-useast2a-ve-0068c004/5275f8639ba84d90999c6371ae527141/?a=1988&br=1370&bt=685&cd=0%7C0%7C0&ch=0&cr=0&cs=0&dr=0&ds=2&er=&ft=Yu12_F5qkag3-I&l=202201191136110101920580770DA82470&lr=tiktok_m&mime_type=video_mp4&net=0&pl=0&qs=0&rc=M3A8ODs6ZnhzOjMzNzczM0ApO2c4PDs2Zzs0NzdlNzRnZmdqM2gucjRnb2ZgLS1kMTZzc19iMzQzLV5gY182XmNgLV46Yw%3D%3D&vl=&vr='
[download] EddY-7054218882072055046.mp4 has already been downloaded

[download] 100% of 1.49MiB
```

Patrick

**Comment by dirkf** [comment]
> This works fine for me:

Thanks, I confirm that for Py 2.7.17/3.5.5/3.9.7, so some junk header must be confusing things.

**Comment by Menard01** [comment]
To download tiktok videos, you have only to right click and "Download the video" #noobs 
(No need a youtube-dl here)

**Comment by 89z** [comment]
I found if you instead use the host `api2.musical.ly`, then you dont need to worry about a specific User-Agent:

https://github.com/89z/mech/blob/v1.46.7/tiktok/tiktok.go#L32-L38

**Comment by dirkf** [comment]
Yes, but you already told us that, and the information was [noted](https://github.com/ytdl-org/youtube-dl/issues/30538#issuecomment-1015864370), and then your post magically vanished...

**Comment by 89z** [comment]
I dont know what you want from me, Im just trying to help

**Comment by fuzzy76** [comment]
FWIW, I see this failing with "Unable to extract data" after adding the user-agent.

**Comment by 89z** [comment]
@fuzzy76 please provide example URL

**Comment by fuzzy76** [comment]
@89z the one in the issue description.

```
fuzzy76@laptop ~ % youtube-dl -v --user-agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0' 'https://vm.tiktok.com/ZMLesneqK/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0', 'https://vm.tiktok.com/ZMLesneqK/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.2 (CPython) - macOS-12.3.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 5.0.1, ffprobe 5.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ZMLesneqK: Requesting header
[redirect] Following redirect to https://www.tiktok.com/@eddysayi/video/7054218882072055046?_d=secCgwIARCbDRjEFSACKAESPgo8Ny%2BRiWmH3OT6VFDDOKQe%2FjdU6QNg2QvER6kPZv8%2BV8iBx6SaSGyiLedX5PcIDqwq0EOwLe84aH6c7rDnGgA%3D&checksum=f558941cd65da22b6359be076ef87f6ffe1d4188d600d52331e2263cc6baa1a8&language=de&preview_pb=0&sec_user_id=MS4wLjABAAAAOkEM5UFx0tM8hhBkjW8D1xAadF1RU12kEXRBL0Kub2pz70wmTYEXuYh8MdtS57Vj&share_app_id=1233&share_item_id=7054218882072055046&share_link_id=EA78C111-0165-44E0-9A7F-D0FC02C4B110&source=h5_m&timestamp=1642491289&tt_from=copy&u_code=dh6jgh57j8hf20&user_id=6931555450693420037&utm_campaign=client_share&utm_medium=ios&utm_source=copy&_r=1
[TikTok] Setting up session
[TikTok] 7054218882072055046: Downloading webpage
ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/tiktok.py", line 110, in _real_extract
    page_props = self._parse_json(self._search_regex(
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
fuzzy76@laptop ~ % 
```
