### ISSUE TITLE
Does youtube-dl need certain certificate to operate? Got the Empty certificate data error

### ISSUE THREAD

**Issue by OnionSalt** [ytdl-org/youtube-dl#30533]
OS is Windows 10 home edition 21H1
OS build 19043.1466

I got the following error, seems certain certificate is missing, the system runs fine, so I don't know which certificate youtube-dl needs

Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\__init__.py", line 442, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 422, in __init__
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2395, in _setup_opener
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\utils.py", line 2297, in make_HTTPS_handler
  File "C:\Python\Python34\lib\ssl.py", line 439, in create_default_context
  File "C:\Python\Python34\lib\ssl.py", line 390, in load_default_certs
  File "C:\Python\Python34\lib\ssl.py", line 382, in _load_windows_store_certs
ValueError: Empty certificate data

I searched old post, a user "julenuri" mentioned the registry entries:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SystemCertificates\CA\Certificates
For me its empty, except the string value "(Default)"
I also checked
HKEY_CURRENT_USER\SOFTWARE\Microsoft\SystemCertificates\CA\Certificates
Same, empty
So I don't know what it supposed to look like and how to fix it.

**Comment by 89z** [comment]
Please provide example command

**Comment by OnionSalt** [comment]
> Please provide example command

Not sure if you mean this, but commands I used are
youtube-dl -F xxxxxxxxx
youtube-dl -f22 xxxxxxxxx

**Comment by 89z** [comment]
If you want help, you need to provide full, unedited example URL.

**Comment by OnionSalt** [comment]
> If you want help, you need to provide full, unedited example URL.

I don't see why this is relevant, but here you go
youtube-dl -F U3W84wb5jKo
Or any other video, same error

**Comment by 89z** [comment]
Using version 2021.12.17, I get expected result:

~~~
PS C:\>  youtube-dl -F U3W84wb5jKo
[youtube] U3W84wb5jKo: Downloading webpage
[info] Available formats for U3W84wb5jKo:
format code  extension  resolution note
249          webm       audio only tiny   50k , webm_dash container, opus @ 50k (48000Hz), 9.17MiB
250          webm       audio only tiny   58k , webm_dash container, opus @ 58k (48000Hz), 10.67MiB
251          webm       audio only tiny  105k , webm_dash container, opus @105k (48000Hz), 19.27MiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 23.54MiB
160          mp4        256x144    144p   31k , mp4_dash container, avc1.4d400c@  31k, 30fps, video only, 5.64MiB
394          mp4        256x144    144p   54k , mp4_dash container, av01.0.00M.08@  54k, 30fps, video only, 9.99MiB
278          webm       256x144    144p   71k , webm_dash container, vp9@  71k, 30fps, video only, 12.99MiB
133          mp4        426x240    240p   49k , mp4_dash container, avc1.4d4015@  49k, 30fps, video only, 9.02MiB
395          mp4        426x240    240p   69k , mp4_dash container, av01.0.00M.08@  69k, 30fps, video only, 12.66MiB
242          webm       426x240    240p   70k , webm_dash container, vp9@  70k, 30fps, video only, 12.80MiB
134          mp4        640x360    360p   89k , mp4_dash container, avc1.4d401e@  89k, 30fps, video only, 16.27MiB
243          webm       640x360    360p  123k , webm_dash container, vp9@ 123k, 30fps, video only, 22.54MiB
396          mp4        640x360    360p  125k , mp4_dash container, av01.0.01M.08@ 125k, 30fps, video only, 22.73MiB
135          mp4        854x480    480p  132k , mp4_dash container, avc1.4d401f@ 132k, 30fps, video only, 24.13MiB
244          webm       854x480    480p  174k , webm_dash container, vp9@ 174k, 30fps, video only, 31.75MiB
397          mp4        854x480    480p  210k , mp4_dash container, av01.0.04M.08@ 210k, 30fps, video only, 38.35MiB
136          mp4        1280x720   720p  242k , mp4_dash container, avc1.4d401f@ 242k, 30fps, video only, 44.03MiB
247          webm       1280x720   720p  293k , webm_dash container, vp9@ 293k, 30fps, video only, 53.40MiB
398          mp4        1280x720   720p  416k , mp4_dash container, av01.0.05M.08@ 416k, 30fps, video only, 75.81MiB
399          mp4        1920x1080  1080p  773k , mp4_dash container, av01.0.08M.08@ 773k, 30fps, video only, 140.58MiB
248          webm       1920x1080  1080p  914k , webm_dash container, vp9@ 914k, 30fps, video only, 166.20MiB
137          mp4        1920x1080  1080p  953k , mp4_dash container, avc1.640028@ 953k, 30fps, video only, 173.29MiB
18           mp4        640x360    360p  367k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz), 66.83MiB
22           mp4        1280x720   720p  371k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
~~~

I would recommend installing via PIP, if youre not already doing so:

~~~
pip uninstall -y (pip freeze)^
pip install youtube-dl
~~~

**Comment by OnionSalt** [comment]
pip install youtube-dl
Installing collected packages: youtube-dl
Successfully installed youtube-dl-2021.12.17

youtube-dl.exe -F U3W84wb5jKo
Same error

Also, I know the problem is on my end, that's why I ask if youtube-dl needs certain certificate to operate(judging by the error message, but I'm not sure), so I might be able to fix it.

**Comment by 89z** [comment]
Sorry, I dont know then. I have an alternate tool, if you want to try it:

~~~
youtube U3W84wb5jKo
~~~

https://github.com/89z/mech/releases/download/v1.44.0/youtube-windows.zip

**Comment by dirkf** [comment]
Clearly OP's Windows is broken, since the error occurs as Python tries to load certificates from Windows. This is only incidentally a problem for yt-dl but OP's Python is confused.

A similar diagnostic should be generated by just typing 'import ssl' at the Python command prompt, unlike the successful case below:
```
$ python
Python 3.5.2 (default, Sep 13 2021, 12:22:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> <ctrl+D>
$
```
(For Windows, exit with ctrl+Z, I expect)

See https://docs.microsoft.com/en-us/windows-hardware/drivers/install/local-machine-and-current-user-certificate-stores

You may want to roll back using System Restore to some point where the system certificates had not been erased, or re-install the 21H1 update.

**Comment by OnionSalt** [comment]
I found the problem, it is indeed on my end.
I checked the certificate one by one, and found out I'm missing a intermediate CA
"GTS CA 1C3" to be specific.
I import the CA and everything works find now.
Thanks everyone
Closing the topic
