### ISSUE TITLE
Some ted.com videos broken

### ISSUE THREAD

**Issue by ole-tange** [ytdl-org/youtube-dl#30561]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl --verbose https://www.ted.com/talks/rha_goddess_and_deepa_purushothaman_4_ways_to_redefine_power_at_work_to_include_women_of_color
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.ted.com/talks/rha_goddess_and_deepa_purushothaman_4_ways_to_redefine_power_at_work_to_include_women_of_color']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-91-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, phantomjs 2.1.1
[debug] Proxy map: {}
[ted] rha_goddess_and_deepa_purushothaman_4_ways_to_redefine_power_at_work_to_include_women_of_color: Downloading webpage
ERROR: Unable to extract info json; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ted.py", line 151, in _real_extract
    return self._talk_info(url, name)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ted.py", line 182, in _talk_info
    info = self._extract_info(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ted.py", line 139, in _extract_info
    info_json = self._search_regex(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract info json; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

JSON does not contain publishing date.

**Comment by dirkf** [comment]
The problem page has a Next.js structure which is not what the TED extractor expects. It needs an overhaul.

**Comment by 89z** [comment]
I have an alternate tool that works:

~~~
PS C:\> ted rha_goddess_and_deepa_purushothaman_4_ways_to_redefine_power_at_work_to_include_women_of_color
GET https://devices.ted.com/api/v2/videos/rha_goddess_and_deepa_purushothaman_4_ways_to_redefine_power_at_work_to_include_women_of_color/react_native_v2.json
GET https://download.ted.com/products/146437.mp4
16.4%   4.211 MB        8.400 MB/s
~~~

https://github.com/89z/mech

**Comment by wxolp** [comment]
https://github.com/yt-dlp/yt-dlp/issues/2343

**Comment by wxolp** [comment]
https://github.com/yt-dlp/yt-dlp/issues/2491

**Comment by dirkf** [comment]
https://github.com/yt-dlp/yt-dlp/pull/2359, as referenced in the above issue, needs to be back-ported.

**Comment by 89z** [comment]
If you use the host `devices.ted.com` instead of the main site, you can avoid parsing HTML or JavaScript.

https://github.com/89z/mech/blob/v1.46.7/ted/ted.go#L21-L28
