### ISSUE TITLE
[orf] No video formats found; please report this issue on https://yt-dl.org/bug

### ISSUE THREAD

**Issue by meisterluk** [ytdl-org/youtube-dl#30564]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v "https://tvthek.orf.at/profile/Wenn-der-Impfstreit-Familien-spaltet/13893585/Wenn-der-Impfstreit-Familien-spaltet-ORF1-Spezial-mit-Mariella-Gittler-und-Christoph-Feurstein/14121921"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://tvthek.orf.at/profile/Wenn-der-Impfstreit-Familien-spaltet/13893585/Wenn-der-Impfstreit-Familien-spaltet-ORF1-Spezial-mit-Mariella-Gittler-und-Christoph-Feurstein/14121921']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-96-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[orf:tvthek] 14121921: Downloading webpage
[orf:tvthek] 15088802: Downloading m3u8 information
[orf:tvthek] 15088802: Downloading m3u8 information
[orf:tvthek] 15088802: Downloading m3u8 information
[orf:tvthek] 15088802: Downloading m3u8 information
[orf:tvthek] 15088802: Downloading m3u8 information

[…]

[orf:tvthek] 15088852: Checking dash-Q1A-Niedrig-p0va0br316315 video format URL
[orf:tvthek] 15088852: Checking dash-Q1A-Niedrig-p0aa0br125425 video format URL
[orf:tvthek] 15088852: Checking dash-Q4A-Mittel-p0va0br806256 video format URL
[orf:tvthek] 15088852: Checking dash-Q4A-Mittel-p0aa0br192070 video format URL
[orf:tvthek] 15088852: Checking dash-Q6A-Hoch-p0va0br1812027 video format URL
[orf:tvthek] 15088852: Checking dash-Q6A-Hoch-p0aa0br192070 video format URL
[orf:tvthek] 15088852: Checking dash-Q8C-Sehr hoch-p0va0br3016333 video format URL
[orf:tvthek] 15088852: Checking dash-Q8C-Sehr hoch-p0aa0br192070 video format URL
[orf:tvthek] 15088852: dash-Q8C-Sehr hoch-p0aa0br192070 video format URL is invalid, skipping: <urlopen error [Errno 113] No route to host>
[orf:tvthek] 15088852: Checking dash-QXB-Adaptiv-p0va0br806256 video format URL
[orf:tvthek] 15088852: dash-QXB-Adaptiv-p0va0br806256 video format URL is invalid, skipping: <urlopen error [Errno 113] No route to host>
[orf:tvthek] 15088852: Checking dash-QXB-Adaptiv-p0va0br1812027 video format URL
[orf:tvthek] 15088852: dash-QXB-Adaptiv-p0va0br1812027 video format URL is invalid, skipping: <urlopen error [Errno 113] No route to host>
[orf:tvthek] 15088852: Checking dash-QXB-Adaptiv-p0va0br3016333 video format URL
[orf:tvthek] 15088852: dash-QXB-Adaptiv-p0va0br3016333 video format URL is invalid, skipping: <urlopen error [Errno 113] No route to host>
[orf:tvthek] 15088852: Checking dash-QXB-Adaptiv-p0aa0br192070 video format URL
[orf:tvthek] 15088852: dash-QXB-Adaptiv-p0aa0br192070 video format URL is invalid, skipping: <urlopen error [Errno 113] No route to host>
[orf:tvthek] 15088849: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 113] No route to host>
[orf:tvthek] 15088849: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 113] No route to host>
[orf:tvthek] 15088849: Downloading m3u8 information
[orf:tvthek] 15088849: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 113] No route to host>
[orf:tvthek] 15088849: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 113] No route to host>
[orf:tvthek] 15088849: Downloading f4m manifest
WARNING: Unable to download f4m manifest: <urlopen error [Errno 113] No route to host>
[orf:tvthek] 15088849: Downloading f4m manifest
WARNING: Unable to download f4m manifest: <urlopen error [Errno 113] No route to host>
[orf:tvthek] 15088849: Downloading f4m manifest
WARNING: Unable to download f4m manifest: <urlopen error [Errno 113] No route to host>
[orf:tvthek] 15088849: Downloading f4m manifest
WARNING: Unable to download f4m manifest: <urlopen error [Errno 113] No route to host>
[orf:tvthek] 15088849: Downloading f4m manifest
WARNING: Unable to download f4m manifest: <urlopen error [Errno 113] No route to host>
[orf:tvthek] 15088849: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [Errno 113] No route to host>
[orf:tvthek] 15088849: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [Errno 113] No route to host>
[orf:tvthek] 15088849: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [Errno 113] No route to host>
[orf:tvthek] 15088849: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [Errno 113] No route to host>
[orf:tvthek] 15088849: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [Errno 113] No route to host>
[orf:tvthek] 15088849: Checking hls-Q6A-Hoch-2205 video format URL
[orf:tvthek] 15088849: hls-Q6A-Hoch-2205 video format URL is invalid, skipping: <urlopen error [Errno 113] No route to host>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/meisterluk/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/meisterluk/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/meisterluk/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/meisterluk/bin/youtube-dl/youtube_dl/extractor/orf.py", line 134, in _real_extract
    self._sort_formats(formats)
  File "/home/meisterluk/bin/youtube-dl/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Thank you for supporting the ORF TVThek platform. Downloading worked quite fine (since I use it regularly), but it stopped recently. I think ORF changed something serverside.

**Comment by meisterluk** [comment]
There are videos that can still be downloaded from ORF. One example is:

`youtube-dl "https://tvthek.orf.at/topic/Dokus-Magazine/13869359/Heimat-Oesterreich-Winter-im-Muerztal/14121963/Heimat-Oesterreich-Winter-im-Muerztal/15088629"`

**Comment by dirkf** [comment]
This page doesn't seem to be geo-restricted so I was able to test it in the UK.

The page has a featured video and a playlist below.

The extractor correctly finds the JSON that includes the required metadata and media URLs. The data for the featured video is in the `selected_video` object, while `playlist.videos` is a list of similar data for each playlist video.

When I run yt-dl with `-F -v` it appears to try to get the entire playlist and ignore the featured video, which is consistent with the code. But your problem seems to be some separate networking issue.

I made these changes and was able to run a test download of the show:
```
--- old/youtube_dl/extractor/orf.py
+++ new/youtube_dl/extractor/orf.py
@@ -15,6 +15,7 @@ from ..utils import (
     remove_end,
     str_or_none,
     strip_jsonp,
+    try_get,
     unescapeHTML,
     unified_strdate,
     url_or_none,
@@ -69,9 +70,12 @@ class ORFTVthekIE(InfoExtractor):
             self._search_regex(
                 r'<div[^>]+class=(["\']).*?VideoPlaylist.*?\1[^>]+data-jsb=(["\'])(?P<json>.+?)\2',
                 webpage, 'playlist', group='json'),
-            playlist_id, transform_source=unescapeHTML)['playlist']['videos']
+            playlist_id, transform_source=unescapeHTML)
+        selected_video = try_get(data_jsb, lambda x: x['selected_video']['is_enabled'], bool)
+        data_jsb = (data_jsb['selected_video'], ) if selected_video else datadata_jsb['playlist']['videos']
 
         entries = []
+
         for sd in data_jsb:
             video_id, title = sd.get('id'), sd.get('title')
             if not video_id or not title:
@@ -174,6 +178,8 @@ class ORFTVthekIE(InfoExtractor):
                 'thumbnails': thumbnails,
             })
 
+        if len(entries) == 1:
+            return entries[0]
         return {
             '_type': 'playlist',
             'entries': entries,
```
So I don't believe that the site is doing anything much different.
```
$ python -m youtube_dl --verbose --test 'https://tvthek.orf.at/profile/Wenn-der-Impfstreit-Familien-spaltet/13893585/Wenn-der-Impfstreit-Familien-spaltet-ORF1-Spezial-mit-Mariella-Gittler-und-Christoph-Feurstein/14121921'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--test', u'https://tvthek.orf.at/profile/Wenn-der-Impfstreit-Familien-spaltet/13893585/Wenn-der-Impfstreit-Familien-spaltet-ORF1-Spezial-mit-Mariella-Gittler-und-Christoph-Feurstein/14121921']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Git HEAD: 51d3d0c9f
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[orf:tvthek] 14121921: Downloading webpage
> /home/df/Documents/src/youtube-dl/youtube_dl/extractor/orf.py(70)_real_extract()
-> data_jsb = self._parse_json(
(Pdb) c
[orf:tvthek] 15088802: Downloading m3u8 information
[orf:tvthek] 15088802: Downloading m3u8 information
[orf:tvthek] 15088802: Downloading m3u8 information
[orf:tvthek] 15088802: Downloading m3u8 information
[orf:tvthek] 15088802: Downloading m3u8 information
[orf:tvthek] 15088802: Downloading f4m manifest
[orf:tvthek] 15088802: Downloading f4m manifest
[orf:tvthek] 15088802: Downloading f4m manifest
[orf:tvthek] 15088802: Downloading f4m manifest
[orf:tvthek] 15088802: Downloading f4m manifest
[orf:tvthek] 15088802: Downloading MPD manifest
[orf:tvthek] 15088802: Downloading MPD manifest
[orf:tvthek] 15088802: Downloading MPD manifest
[orf:tvthek] 15088802: Downloading MPD manifest
[orf:tvthek] 15088802: Downloading MPD manifest
[orf:tvthek] 15088802: Checking hls-Q1A-Niedrig-502 video format URL
[orf:tvthek] 15088802: Checking hls-Q4A-Mittel-1127 video format URL
[orf:tvthek] 15088802: Checking hls-Q6A-Hoch-2229 video format URL
[orf:tvthek] 15088802: Checking hls-Q8C-Sehr hoch-3568 video format URL
[orf:tvthek] 15088802: Checking hls-QXB-Adaptiv-992 video format URL
[orf:tvthek] 15088802: Checking hls-QXB-Adaptiv-1992 video format URL
[orf:tvthek] 15088802: Checking hls-QXB-Adaptiv-3192 video format URL
[orf:tvthek] 15088802: Checking hds-Q1A-Niedrig-430 video format URL
[orf:tvthek] 15088802: Checking hds-Q4A-Mittel-974 video format URL
[orf:tvthek] 15088802: Checking hds-Q6A-Hoch-1949 video format URL
[orf:tvthek] 15088802: Checking hds-Q8C-Sehr hoch-3121 video format URL
[orf:tvthek] 15088802: Checking hds-QXB-Adaptiv-968 video format URL
[orf:tvthek] 15088802: Checking hds-QXB-Adaptiv-1945 video format URL
[orf:tvthek] 15088802: Checking hds-QXB-Adaptiv-3117 video format URL
[orf:tvthek] 15088802: Checking dash-Q1A-Niedrig-p0va0br315480 video format URL
[orf:tvthek] 15088802: Checking dash-Q1A-Niedrig-p0aa0br125426 video format URL
[orf:tvthek] 15088802: Checking dash-Q4A-Mittel-p0va0br805787 video format URL
[orf:tvthek] 15088802: Checking dash-Q4A-Mittel-p0aa0br192071 video format URL
[orf:tvthek] 15088802: Checking dash-Q6A-Hoch-p0va0br1804671 video format URL
[orf:tvthek] 15088802: Checking dash-Q6A-Hoch-p0aa0br192071 video format URL
[orf:tvthek] 15088802: Checking dash-Q8C-Sehr hoch-p0va0br3004763 video format URL
[orf:tvthek] 15088802: Checking dash-Q8C-Sehr hoch-p0aa0br192071 video format URL
[orf:tvthek] 15088802: Checking dash-QXB-Adaptiv-p0va0br805787 video format URL
[orf:tvthek] 15088802: Checking dash-QXB-Adaptiv-p0va0br1804671 video format URL
[orf:tvthek] 15088802: Checking dash-QXB-Adaptiv-p0va0br3004763 video format URL
[orf:tvthek] 15088802: Checking dash-QXB-Adaptiv-p0aa0br192071 video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[download] Signation _ Begrüßung-15088802.mp4 has already been downloaded and merged
df@Spiridion:~/Documents/src/youtube-dl$ rm Signation\ _\ Begrüßung-15088802.mp4 
df@Spiridion:~/Documents/src/youtube-dl$ python -m youtube_dl --verbose --test 'https://tvthek.orf.at/profile/Wenn-der-Impfstreit-Familien-spaltet/13893585/Wenn-der-Impfstreit-Familien-spaltet-ORF1-Spezial-mit-Mariella-Gittler-und-Christoph-Feurstein/14121921'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--test', u'https://tvthek.orf.at/profile/Wenn-der-Impfstreit-Familien-spaltet/13893585/Wenn-der-Impfstreit-Familien-spaltet-ORF1-Spezial-mit-Mariella-Gittler-und-Christoph-Feurstein/14121921']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Git HEAD: 51d3d0c9f
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[orf:tvthek] 14121921: Downloading webpage
[orf:tvthek] 15088802: Downloading m3u8 information
... 4 repeats ...
[orf:tvthek] 15088802: Downloading f4m manifest
... 4 repeats ...
[orf:tvthek] 15088802: Downloading MPD manifest
... 4 repeats ...
[orf:tvthek] 15088802: Checking hls-Q1A-Niedrig-502 video format URL
[orf:tvthek] 15088802: Checking hls-Q4A-Mittel-1127 video format URL
[orf:tvthek] 15088802: Checking hls-Q6A-Hoch-2229 video format URL
[orf:tvthek] 15088802: Checking hls-Q8C-Sehr hoch-3568 video format URL
[orf:tvthek] 15088802: Checking hls-QXB-Adaptiv-992 video format URL
[orf:tvthek] 15088802: Checking hls-QXB-Adaptiv-1992 video format URL
[orf:tvthek] 15088802: Checking hls-QXB-Adaptiv-3192 video format URL
[orf:tvthek] 15088802: Checking hds-Q1A-Niedrig-430 video format URL
[orf:tvthek] 15088802: Checking hds-Q4A-Mittel-974 video format URL
[orf:tvthek] 15088802: Checking hds-Q6A-Hoch-1949 video format URL
[orf:tvthek] 15088802: Checking hds-Q8C-Sehr hoch-3121 video format URL
[orf:tvthek] 15088802: Checking hds-QXB-Adaptiv-968 video format URL
[orf:tvthek] 15088802: Checking hds-QXB-Adaptiv-1945 video format URL
[orf:tvthek] 15088802: Checking hds-QXB-Adaptiv-3117 video format URL
[orf:tvthek] 15088802: Checking dash-Q1A-Niedrig-p0va0br315480 video format URL
[orf:tvthek] 15088802: Checking dash-Q1A-Niedrig-p0aa0br125426 video format URL
[orf:tvthek] 15088802: Checking dash-Q4A-Mittel-p0va0br805787 video format URL
[orf:tvthek] 15088802: Checking dash-Q4A-Mittel-p0aa0br192071 video format URL
[orf:tvthek] 15088802: Checking dash-Q6A-Hoch-p0va0br1804671 video format URL
[orf:tvthek] 15088802: Checking dash-Q6A-Hoch-p0aa0br192071 video format URL
[orf:tvthek] 15088802: Checking dash-Q8C-Sehr hoch-p0va0br3004763 video format URL
[orf:tvthek] 15088802: Checking dash-Q8C-Sehr hoch-p0aa0br192071 video format URL
[orf:tvthek] 15088802: Checking dash-QXB-Adaptiv-p0va0br805787 video format URL
[orf:tvthek] 15088802: Checking dash-QXB-Adaptiv-p0va0br1804671 video format URL
[orf:tvthek] 15088802: Checking dash-QXB-Adaptiv-p0va0br3004763 video format URL
[orf:tvthek] 15088802: Checking dash-QXB-Adaptiv-p0aa0br192071 video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://apasfiis.sf.apa.at/dash/cms-worldwide/2022-01-26_2108_tl_01_Wenn-der-Impfst_Signation---Beg__14121921__o__3472894016__s15088802_2__ORF1HD_21092412P_21102302P_QXB.mp4/manifest.mpd'
[dashsegments] Total fragments: 1
[download] Destination: Signation _ Begrüßung-15088802.fdash-QXB-Adaptiv-p0va0br3004763.mp4
[download] 100% of 714.00B in 00:00
[debug] Invoking downloader on u'https://apasfiis.sf.apa.at/dash/cms-worldwide/2022-01-26_2108_tl_01_Wenn-der-Impfst_Signation---Beg__14121921__o__3472894016__s15088802_2__ORF1HD_21092412P_21102302P_QXB.mp4/manifest.mpd'
[dashsegments] Total fragments: 1
[download] Destination: Signation _ Begrüßung-15088802.fdash-QXB-Adaptiv-p0aa0br192071.m4a
[download] 100% of 637.00B in 00:00
[ffmpeg] Merging formats into "Signation _ Begrüßung-15088802.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Signation _ Begrüßung-15088802.fdash-QXB-Adaptiv-p0va0br3004763.mp4' -i 'file:Signation _ Begrüßung-15088802.fdash-QXB-Adaptiv-p0aa0br192071.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:Signation _ Begrüßung-15088802.temp.mp4'
Deleting original file Signation _ Begrüßung-15088802.fdash-QXB-Adaptiv-p0va0br3004763.mp4 (pass -k to keep)
Deleting original file Signation _ Begrüßung-15088802.fdash-QXB-Adaptiv-p0aa0br192071.m4a (pass -k to keep)
$
```

**Comment by dirkf** [comment]
> There are videos that can still be downloaded from ORF. One example is:
> 
> `youtube-dl "https://tvthek.orf.at/topic/Dokus-Magazine/13869359/Heimat-Oesterreich-Winter-im-Muerztal/14121963/Heimat-Oesterreich-Winter-im-Muerztal/15088629"`

Using `--geo-bypass-country AT`, this works from UK with the unpatched extractor (gets a .m3u8), and also with the above patch (gets a .mpd, DASH download).

**Comment by meisterluk** [comment]
I have difficulties understanding the situation here from my apartment in Austria. But …

* download succeeds with your patch
* download still fails without your patch
* both implementations with `--geo-bypass-country AT` fail

To revise your patch: Does anyone know what the expected behavior for youtube-dl is? Should it download the playlist or just the first video? I tend to believe the entire playlist.

**Comment by dirkf** [comment]
In my view what is important is the intent conveyed by the page URL. For instance, the BBC page URLs were designed to convey intent, with elements like `/episode/xxxx`, `/series/yyyy`, `/programmes/zzzz`. At ORF, but maybe it's my fault for poor German language skills, it seems less clear; also there don't seem to be series pages with several videos, perhaps because the shows expire so quickly that only the just-broadcast episode is relevant.

Here are the test URLs in the extractor, plus the ones previously mentioned in this issue, plus another that I checked for comparison:
1. http://tvthek.orf.at/program/Aufgetischt/2745173/Aufgetischt-Mit-der-Steirischen-Tafelrunde/8891389: program id 8896777
2. http://tvthek.orf.at/topic/Im-Wandel-der-Zeit/8002126/Best-of-Ingrid-Thurnher/7982256: program id 7982259
3. http://tvthek.orf.at/topic/Fluechtlingskrise/10463081/Heimat-Fremde-Heimat/13879132/Senioren-betreuen-Migrantenkinder/13879141: no longer available, redirects to generic page
4. http://tvthek.orf.at/profile/Universum/35429: program id 15087592
5. https://tvthek.orf.at/profile/Wenn-der-Impfstreit-Familien-spaltet/13893585/Wenn-der-Impfstreit-Familien-spaltet-ORF1-Spezial-mit-Mariella-Gittler-und-Christoph-Feurstein/14121921: program id 15088802
6. https://tvthek.orf.at/topic/Dokus-Magazine/13869359/Heimat-Oesterreich-Winter-im-Muerztal/14121963/Heimat-Oesterreich-Winter-im-Muerztal/15088629: program id 15088629
7. https://tvthek.orf.at/history/Die-politische-Landschaft-in-Deutschland/6524565: playlist with 29 videos.

The first-level URL components use variously  `program`, `topic`, `profile`, `history`. As far as I can see, there's no pattern in the URLs that would allow you to distinguish between single video pages, playlist pages, and combination pages.

Pages 1, 2, 4, 6 are all single video pages.

Page 5, OP's original problem page, is similar but has a ribbon of video clips under the main video. I believe that the extractor should extract the main video (the patch above tested for that object having its `is_enabled` flag set), since the clips are just some extras. yt-dl has a `--no-playlist` option from which  an extractor can tell how to handle a playlist page with a playable video, but no option exists for this reverse situation (`--yes-playlist` doesn't mean what it should). Each clip has a URL with a corresponding page where the clip is the `selected_video` and is highlighted in the ribbon below, eg https://tvthek.orf.at/profile/Wenn-der-Impfstreit-Familien-spaltet/13893585/Wenn-der-Impfstreit-Familien-spaltet-ORF1-Spezial-mit-Mariella-Gittler-und-Christoph-Feurstein/14121921/Die-Parallelwelt-der-Ungeimpften/15088805.

Page 7 is an actual example of a playlist with no featured video, but it isn't handled correctly by the extractor with or without the patch, because these playlist items are actual links in the HTML and not hidden in a JSON VideoPlaylist as with eg page 5. The extractor ought to handle those too.

If ORF users know of other page types that should be handled, I hope OP won't object to them being posted here.

**Comment by prokls** [comment]
Thank you very much @dirkf for your detailed analysis. Indeed, this issue is about a specific type of URL. I agree regarding your point on URL design and come to the conclusion that without more URLs, it is difficult to understand what the desired behavior is supposed to look like.

My personal strategy would be to collect more URLs and then discuss an appropriate patch for specific URL formats. But at this point, I don't think we have enough data and we should just close this issue for now (@dirkf, please do if you agree).

**Comment by meisterluk** [comment]
(Sorry, I posted this comment first with the wrong account)

Thank you very much @dirkf for your detailed analysis. Indeed, this issue is about a specific type of URL. I agree regarding your point on URL design and come to the conclusion that without more URLs, it is difficult to understand what the desired behavior is supposed to look like.

My personal strategy would be to collect more URLs and then discuss an appropriate patch for specific URL formats. But at this point, I don't think we have enough data and we should just close this issue for now (@dirkf, please do if you agree).

**Comment by dirkf** [comment]
Just to add another element of hazard, the playlist page # 7 has three groups of videos which arguably should be extracted as separate playlists. An attempt to extract the page as a master playlist with a nested playlist for each group of videos in the page breaks yt-dl code that was added to detect infinite playlist loops when YT appeared to have one.

The issue could be left open until the extractor is updated, in case further information or site requirements become available.

**Comment by dirkf** [comment]
Superseded by #32798.
