### ISSUE TITLE
Problem downloading a clip from the BBC's website

### ISSUE THREAD

**Issue by LimehouseJohn** [ytdl-org/youtube-dl#30565]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PS C:\Users\John\OneDrive\Downloads\Youtube-dl> .\youtube-dl --verbose https://www.bbc.co.uk/news/av/uk-politics-60159228
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.bbc.co.uk/news/av/uk-politics-60159228']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-11-03-git-08a501946f-full_build-www.gyan.dev, ffprobe 2021-11-03-git-08a501946f-full_build-www.gyan.dev
[debug] Proxy map: {}
[bbc] uk-politics-60159228: Downloading webpage
ERROR: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\bbc.py", line 1255, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

PS C:\Users\John\OneDrive\Downloads\Youtube-dl>
```

## Description

Hi, apologies if I am misusing this site.  I am a 'user' of youtube-dl (which I consider a brilliant piece of software) rather than a 'developer' - so please just ignore this message if I am misusing it.  My problem is simple, I wanted to download this 35 second clip from the BBC's website and it doesn't seem to work (the first time that this has happened to me with the BBC's website).  If it is possible to say what I am doing wrong, I should be grateful - thanks.

**Comment by dirkf** [comment]
There are some pending PRs for BBC and I hope that one of them should catch this item.

By inspection of the escaped JSON sent by the site,
```
'media':
{
  '__typename': 'ElementsMediaPlayer',
  'smpAppName': 'news-sfv',
  'items': [
    {
      'id': 'p0bkp6nx',
      'kind': 'programme',
      'title': 'Johnson\'s \'brilliant new strategy\' from 2006',
      'duration': 35,
      'holdingImageUrl': 'https://ichef.bbci.co.uk/images/ic/$recipe/p0bkpb60.jpg',
      'durationFormatted': '1 day ago',
      'guidance': null,
      'isEmbeddingAllowed': true,
      'isAdvertisingAllowed': true,
      'adCampaignKeyword': null
    }
  ]
}
...
```
we can see that the program id is `p0bkp6nx` and therefore its canonical URL is `https://www.bbc.co.uk/programmes/p0bkp6nx`, which should be accessible using the yt-dl release version.

**Comment by LimehouseJohn** [comment]
Thanks dirkf, - I couldn't even pretend to understand the technical aspects of your (I'm perfectly sure) obviously good explanation.  However, I could easily understand the 'canonical URL' you gave me - and that allowed me to achieve my objective - so thank you again and long may youtube-dl last and be available to non-technicians like me.  Best regards.

**Comment by 89z** [comment]
I have an alternate tool that works with the original URL:

~~~
PS C:\> bbc https://www.bbc.co.uk/news/av/uk-politics-60159228
GET http://walter-producer-cdn.api.bbci.co.uk/content/cps/news/uk-politics-60159228
GET http://open.live.bbc.co.uk/mediaselector/6/select/version/2.0/mediaset/pc/vpid/p0bkp6nx
GET http://vod-hls-ww-live.akamaized.net/usp/auth/vod/piff_abr_full_sd/14108c-p0bkp6nx/vf_p0bkp6nx_26295b22-9a8e-439b-8f34-0b439c77deb5.ism/pc_hd_abr_v2_hls_master.m3u8?__gda__=1643423598_88e946e0bcc49ca18d4d69ed9439f6ff
GET http://vod-hls-ww-live.akamaized.net/usp/auth/vod/piff_abr_full_sd/14108c-p0bkp6nx/vf_p0bkp6nx_26295b22-9a8e-439b-8f34-0b439c77deb5.ism/vf_p0bkp6nx_26295b22-9a8e-439b-8f34-0b439c77deb5-audio_eng=96000-video=281000.m3u8
0.0%    394.424 kB      4.153 MB/s
20.0%   770.800 kB      5.101 MB/s
~~~

https://github.com/89z/mech

**Comment by 89z** [comment]
I found you can take the URL:

https://www.bbc.co.uk/news/av/uk-politics-60159228

and extract everything after the last slash

~~~
uk-politics-60159228
~~~

and use that with further processing.

https://github.com/89z/mech/blob/v1.46.7/bbc/bbc.go#L60-L67
