### ISSUE TITLE
newgrounds video error

### ISSUE THREAD

**Issue by momoe** [ytdl-org/youtube-dl#30575]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
PS C:\Users\User\Downloads> .\youtube-dl.exe -v  https://www.newgrounds.com/portal/view/830258
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.newgrounds.com/portal/view/830258']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[Newgrounds] 830258: Downloading webpage
ERROR: Unable to extract ; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\newgrounds.py", line 65, in _real_extract  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract ; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
Yes, the page structure isn't as expected by the extractor. It looks like the page has to be requested again, with the additional header`X-Requested-With: XMLHttpRequest` to get a nice JSON version of the page that includes the media links:
```
{
    "id": 830258,
    "title": "moving in",
    "author": "wavetro",
    "sources": {
        "1080p": [
            {
                "type": "video\/mp4",
                "src": "https:\/\/uploads.ungrounded.net\/alternate\/1815000\/1815460_alternate_169154.1080p.mp4?1642878046"
            }
        ],
        "720p": [
            {
                "type": "video\/mp4",
                "src": "https:\/\/uploads.ungrounded.net\/alternate\/1815000\/1815460_alternate_169154.720p.mp4?1642878046"
            }
        ],
        "360p": [
            {
                "type": "video\/mp4",
                "src": "https:\/\/uploads.ungrounded.net\/alternate\/1815000\/1815460_alternate_169154.360p.mp4?1642878046"
            }
        ]
    }
}
```
