### ISSUE TITLE
Ketnet - Brokes site support - No video formats found

### ISSUE THREAD

**Issue by Krisverr** [ytdl-org/youtube-dl#30581]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[01/31/22 19:13:10] 
[01/31/22 19:15:45] [debug] System config: []
[01/31/22 19:15:45] [debug] User config: []
[01/31/22 19:15:45] [debug] Custom config: []
[01/31/22 19:15:45] [debug] Command-line args: ['--newline', '-i', '-o', 'E:\\%(title)s.%(ext)s', '-f', 'mp4', '-v', '--ignore-config', '--hls-prefer-native', '--no-mtime', 'https://www.ketnet.be/kijken/s/sisters/2/sisters-s2a1']
[01/31/22 19:15:45] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[01/31/22 19:15:45] [debug] youtube-dl version 2021.12.17
[01/31/22 19:15:45] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[01/31/22 19:15:45] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[01/31/22 19:15:45] [debug] Proxy map: {}
[01/31/22 19:15:45] WARNING: Unable to download asset JSON: <urlopen error [Errno 11001] getaddrinfo failed>
[01/31/22 19:15:45] WARNING: [Canvas] Unknown MIME type application/mp4 in DASH manifest
[01/31/22 19:15:45] ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[01/31/22 19:15:45] Traceback (most recent call last):
[01/31/22 19:15:45]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
[01/31/22 19:15:45]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
[01/31/22 19:15:45]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
[01/31/22 19:15:45]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\canvas.py", line 109, in _real_extract
[01/31/22 19:15:45]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
[01/31/22 19:15:45] youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[01/31/22 19:15:45] 
[01/31/22 22:45:30] [debug] System config: []
[01/31/22 22:45:30] [debug] User config: []
[01/31/22 22:45:30] [debug] Custom config: []
[01/31/22 22:45:30] [debug] Command-line args: ['--newline', '-i', '-o', 'E:\\%(title)s.%(ext)s', '-f', 'mp4', '-v', '--ignore-config', '--hls-prefer-native', '--no-mtime', 'https://www.ketnet.be/kijken/d/de-smurfen/4/de-smurfen-d20161006-s4a2-leerlingsmurf-in-de-ban-van-gargamel']
[01/31/22 22:45:30] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[01/31/22 22:45:30] [debug] youtube-dl version 2021.12.17
[01/31/22 22:45:30] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[01/31/22 22:45:30] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[01/31/22 22:45:30] [debug] Proxy map: {}
[01/31/22 22:45:30] WARNING: Unable to download asset JSON: <urlopen error [Errno 11001] getaddrinfo failed>
[01/31/22 22:45:30] WARNING: [Canvas] Unknown MIME type application/mp4 in DASH manifest
[01/31/22 22:45:30] ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[01/31/22 22:45:30] Traceback (most recent call last):
[01/31/22 22:45:30]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
[01/31/22 22:45:30]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
[01/31/22 22:45:30]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
[01/31/22 22:45:30]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\canvas.py", line 109, in _real_extract
[01/31/22 22:45:30]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
[01/31/22 22:45:30] youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[01/31/22 22:45:30] 
```

## Description

Afther 'processing' , the lines youtube-dl in goes to 'error' 0%
I tried to "return to an old windows recovery point" - didn't changed anything.
Downloading from youtube still works, so i don't think it is a problem with youtube-dl. (it was smarter to first test, that one, I know).
Video's that worked in the past (1 month ago) can't be downloaded now.
The side 'Ketnet' changes it videos reguraly (weekly), so i used a link that is there fore multiple weeks to demostrate.
The side 'VRT' (family-group of Ketnet and Canvas (also mentionned in error-repord) had in the past a change that not all the video's where working anymore, so i think it is a setting of the site that is tranfered from one site (VRT) and now also used on the Ketnet site as well.
(VRT you have to create a log in, for Ketnet you don't, so i used the Ketnet site in this example problem.)
The above example is a 'sort -10min video' example (Sisters) or 20min (smurfs)
A smaller one (5min)  is on "https://www.ketnet.be/kijken/g/grizzy-de-lemmings" but the end changes reguraly: 'https://www.ketnet.be/kijken/g/grizzy-de-lemmings/1/grizzy---the-lemmings-s1a40-construction-bear' so probably it won't work when you read this.

**Comment by Kristof-V** [comment]
For your information: concerning the geo-restricted label, I'me in the same country (Belgium (.be)).

**Comment by 89z** [comment]
@Kristof-V its usually the duty of the poster, to provide a proxy. Otherwise, if people arent able to access the site, then less chance they are able to help you.

**Comment by Kristof-V** [comment]
Sorry, I didn't know that.
It is a little bit logical when I think about it now.
Then I think it ends here for me. I searched, but i didn't find one that was in the same geo region (.be) and worked.
The closest ones (*) was from our neighboring country (The Netherlands):
https://rackstack.online/kijken/s/sisters/2/sisters-s2a1?__cpo=aHR0cHM6Ly93d3cua2V0bmV0LmJl
https://178.63.3.173/kijken/s/sisters/2/sisters-s2a1?__cpo=aHR0cHM6Ly93d3cua2V0bmV0LmJl
But it won't work, the page opens, but the video doesn't play.
(*) Comparing to a US proxy, who opens the site only for 5%.
Is there an other solution possible what i can do?
(an easy one (can't create my om proxy server - it is a little high tech for me))

**Comment by 89z** [comment]
From my experience, most free proxy servers are garbage. If you find free one that works, then that is excellent, I can try to fix support for this site. Otherwise you may need to invest in a paid proxy, which you can provide to people when you are having trouble.
