### ISSUE TITLE
[Linux] Youtube RegexNotFoundError

### ISSUE THREAD

**Issue by raffaele-sanzi** [ytdl-org/youtube-dl#30606]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -f bestvideo[height=1080]+bestaudio -o '/mnt/DATA/%(title)s.%(ext)s' 'https://www.youtube.com/watch?v=35xTYr2PSH8' --sleep-interval 30 --mark-watched --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo[height=1080]+bestaudio', '-o', '/mnt/DATA/%(title)s.%(ext)s', 'https://www.youtube.com/watch?v=35xTYr2PSH8', '--sleep-interval', '30', '--mark-watched', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.13.0-28-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 35xTYr2PSH8: Downloading webpage
[youtube] 35xTYr2PSH8: Downloading player 0cd11746
ERROR: 35xTYr2PSH8: Traceback (most recent call last):
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1434, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1407, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1394, in _extract_n_function_name
    return self._search_regex(
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1434, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1407, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1394, in _extract_n_function_name
    return self._search_regex(
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1434, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1407, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1394, in _extract_n_function_name
    return self._search_regex(
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1866, in _real_extract
    self._unthrottle_format_urls(video_id, player_url, formats)
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1451, in _unthrottle_format_urls
    n_response = self._n_descramble(n_param, player_url, video_id)
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1441, in _n_descramble
    raise ExtractorError(traceback.format_exc(), cause=e, video_id=video_id)
youtube_dl.utils.ExtractorError: 35xTYr2PSH8: Traceback (most recent call last):
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1434, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1407, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1394, in _extract_n_function_name
    return self._search_regex(
  File "/home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Hi, I'm experiencing this bug for Youtube. It just happened at random 4-5 days ago. Before that, I could download perfectly fine.

I'm suspecting it's just Youtube, as the error report is mainly pointing to the Youtube extractor .py file, and I've triied with Crunchyroll (for another unrelated video of course) and it seems to work as normal.
The problem started appearing a little before the release of both a kernel upgrade and the update of Python 3.8 for my system (I'm running Linux Mint 20.3, if that helps), which however didn't solve the problem.
I tried reinstalling youtube-dl following the official instructions, but to no avail. I don't know if there's a way to completely wipe all files related to youtube-dl, in order to start fresh with the installation process, but just using the commands provided in the instructions didn't solve it.
I'm also dual booting Windows 10, where I don't have Python installed and downloaded the youtube-dl exe 2021.12.17 some time ago. Surprisingly, although with extremely low download speed, this one works!

Hope I could give the best explanation possible!

**Comment by october262** [comment]
does youtube-dl say it's up to date if you run sudo youtube-dl -U ??

**Comment by dirkf** [comment]
You have [this problem](https://github.com/ytdl-org/youtube-dl/issues/30583#issuecomment-1027312830), fixed in git master.

**Comment by raffaele-sanzi** [comment]
@october262 Yes, it does say I'm up to date

@dirkf  I did happen to read the issue you mention, but it didn't feel "similar enough" if that makes sense.
Thanks a bunch for the help, looking forward to the next release! :smile:

**Comment by dirkf** [comment]
As in the linked issue, with your configuration, you can install from the repo using _pip_.

**Comment by raffaele-sanzi** [comment]
I tried installing via _pip_ on top of the current installation (done via _wget_), and I'm getting the same error... Maybe the two versions are in conflict?

When I try uninstalling with _pip_ it wants to remove from:

    /usr/local/bin/youtube-dl
    /usr/local/etc/bash_completion.d/youtube-dl.bash-completion
    /usr/local/etc/fish/completions/youtube-dl.fish
    /usr/local/lib/python3.8/dist-packages/youtube_dl-2021.12.17.dist-info/*
    /usr/local/lib/python3.8/dist-packages/youtube_dl/*
    /usr/local/share/doc/youtube_dl/README.txt
    /usr/local/share/man/man1/youtube-dl.1

While the error message i get when trying to download points to:

    /home/raffaele/.local/lib/python3.8/site-packages/youtube_dl/

Is there a way i can delete all files related to youtube-dl, so I can be sure I don't have rogue files messing it up? I'll open a new issue if needed

**Comment by dirkf** [comment]
The first set of files looks like an installation from a distro package. As I understand it, `pip --user` puts stuff in the `.local/.../site_packages` directory.

**Comment by raffaele-sanzi** [comment]
Yes, the first set was listed to me when i tried uninstalling youtube-dl with **pip**.

I could find and delete what I was looking for with the search function for my File Manager.
I tried installing with **pip** only, and it works! Download speed is back to super low, but after reading the comments to issue #30583 it seems like the next release will ultimately fix it.

I'll try and stick with the **pip** install then. As far as I understood it collects the updated single files from the git repo, while **wget** or **curl** don't, is it  correct?
