### ISSUE TITLE
'sockssocket' object has no attribute 'proxy'

### ISSUE THREAD

**Issue by Tkeng-tefs** [ytdl-org/youtube-dl#30632]
Hello!
I try to use youtube_dl in python, but I get an error on the proxy, it says "AttributeError: 'sockssocket' object has no attribute 'proxy'".
My setup is like this:
y_opts = {
'proxy': 'socks5://127.0.0.1:10808',
'outtmpl': outtmpls,
'format': formats
}
Hope to get your answer, thank you very much!

**Comment by Tkeng-tefs** [comment]
Here are the details:

Traceback (most recent call last):
  File "D:\YouTube.py", line 693, in run
    ydl.download([s])
  File "C:\Users\tken\miniconda3\envs\py39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "C:\Users\tken\miniconda3\envs\py39\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\tken\miniconda3\envs\py39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\tken\miniconda3\envs\py39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\tken\miniconda3\envs\py39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\tken\miniconda3\envs\py39\lib\site-packages\youtube_dl\extractor\youtube.py", line 1493, in _real_extract
    webpage = self._download_webpage(
  File "C:\Users\tken\miniconda3\envs\py39\lib\site-packages\youtube_dl\extractor\common.py", line 798, in _download_webpage
    res = self._download_webpage_handle(
  File "C:\Users\tken\miniconda3\envs\py39\lib\site-packages\youtube_dl\extractor\common.py", line 667, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "C:\Users\tken\miniconda3\envs\py39\lib\site-packages\youtube_dl\extractor\common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\tken\miniconda3\envs\py39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\tken\miniconda3\envs\py39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\tken\miniconda3\envs\py39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\tken\miniconda3\envs\py39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\tken\miniconda3\envs\py39\lib\site-packages\youtube_dl\utils.py", line 2735, in https_open
    return self.do_open(functools.partial(
  File "C:\Users\tken\miniconda3\envs\py39\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\tken\miniconda3\envs\py39\lib\http\client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\tken\miniconda3\envs\py39\lib\http\client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\tken\miniconda3\envs\py39\lib\http\client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\tken\miniconda3\envs\py39\lib\http\client.py", line 1034, in _send_output
    self.send(msg)
  File "C:\Users\tken\miniconda3\envs\py39\lib\http\client.py", line 974, in send
    self.connect()
  File "C:\Users\tken\miniconda3\envs\py39\lib\site-packages\youtube_dl\utils.py", line 2703, in connect
    self.sock.connect((self.host, self.port))
  File "C:\Users\tken\miniconda3\envs\py39\lib\site-packages\youtube_dl\socks.py", line 270, in connect
    self._make_proxy(socket.socket.connect, address)
  File "C:\Users\tken\miniconda3\envs\py39\lib\site-packages\youtube_dl\socks.py", line 258, in _make_proxy
    result = connect_func(self, (self._proxy.host, self._proxy.port))
  File "C:\Users\tken\miniconda3\envs\py39\lib\site-packages\socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\tken\miniconda3\envs\py39\lib\site-packages\socks.py", line 761, in connect
    password) = self.proxy
AttributeError: 'sockssocket' object has no attribute 'proxy'

**Comment by dirkf** [comment]
Apparently you have some package `socks.py` that is not part of a base Python 3.9 installation (well, not mine) and may be clashing with the `sockssocket` object that is part of yt-dl.

**Comment by Tkeng-tefs** [comment]
Thanks for your reply, this issue has been resolved.
