### ISSUE TITLE
ZDF Arte Mediathek does not work

### ISSUE THREAD

**Issue by mowgli** [ytdl-org/youtube-dl#30652]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser (Well, I checked but as no video site works in my browser, youtube-dl is the only way for me to watch any online video. So, I checked but obviously it will never work in my browser to watch videos.)
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
~> youtube-dl -v https://www.zdf.de/arte/mit-offenen-karten/page-video-artede-mit-offenen-karten---die-alpen-ein-europaeisches-gebirge-100.html
[debug] System config: []
[debug] User config: ['--no-part', '--no-check-certificate', '--force-ipv4', '--prefer-free-formats']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.zdf.de/arte/mit-offenen-karten/page-video-artede-mit-offenen-karten---die-alpen-ein-europaeisches-gebirge-100.html']
[debug] Encodings: locale ISO-8859-1, fs iso8859-1, out iso8859-1, pref ISO-8859-1
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.10 (CPython) - Linux-5.13.4-x86_64-with-glibc2.33
[debug] exe versions: avconv 4.4.1, avprobe 4.4.1, ffmpeg 4.4.1, ffprobe 4.4.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 53.166.135.149 (DE) as X-Forwarded-For.
[ZDF] page-video-artede-mit-offenen-karten---die-alpen-ein-europaeisches-gebirge-100: Downloading webpage
[ZDF] page-video-artede-mit-offenen-karten---die-alpen-ein-europaeisches-gebirge-100: Downloading JSON content
ERROR: An extractor error has occurred. (caused by KeyError('http://zdf.de/rels/streams/ptmd-template')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/zdf.py", line 292, in _real_extract
    return self._extract_regular(url, player, video_id)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/zdf.py", line 241, in _extract_regular
    return self._extract_entry(player['content'], player, content, video_id)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/zdf.py", line 203, in _extract_entry
    ptmd_path = t[
KeyError: 'http://zdf.de/rels/streams/ptmd-template'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/zdf.py", line 292, in _real_extract
    return self._extract_regular(url, player, video_id)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/zdf.py", line 241, in _extract_regular
    return self._extract_entry(player['content'], player, content, video_id)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/zdf.py", line 203, in _extract_entry
    ptmd_path = t[
KeyError: 'http://zdf.de/rels/streams/ptmd-template'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 547, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('http://zdf.de/rels/streams/ptmd-template')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

There is different bugs about several ARTE pages but not about the ZDF Arte Mediathek, so I opened this bug.

As written above, youtube-dl is the only way for me to watch online resources. I never got videos to work in my browser (firefox), not on youtube, not on zdf page, nowhere.

The main zdf mediathek page works fine. Only the ARTE videos give the error mentioned above.

I have that error for long time now but until now I was just patient to wait if it will be fixed eventually.

**Comment by dirkf** [comment]
Duplicate of #29893 (yes, really).

Fixed in git master with merger of #30527:
```
$ python -m youtube_dl -v -F 'https://www.zdf.de/arte/mit-offenen-karten/page-video-artede-mit-offenen-karten---die-alpen-ein-europaeisches-gebirge-100.html'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.zdf.de/arte/mit-offenen-karten/page-video-artede-mit-offenen-karten---die-alpen-ein-europaeisches-gebirge-100.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: d42e90091
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[debug] Using fake IP 53.243.98.161 (DE) as X-Forwarded-For.
[ZDF] page-video-artede-mit-offenen-karten---die-alpen-ein-europaeisches-gebirge-100: Downloading webpage
[ZDF] page-video-artede-mit-offenen-karten---die-alpen-ein-europaeisches-gebirge-100: Downloading JSON content
[ZDF] page-video-artede-mit-offenen-karten---die-alpen-ein-europaeisches-gebirge-100: Downloading JSON metadata
[ZDF] video_artede_098814-011-A: Downloading m3u8 information
[info] Available formats for video_artede_098814-011-A:
format code                        extension  resolution note
hls-61                             mp4        audio only   61k , mp4a.40.2
http-h264_aac_mp4_http_na_na-low   mp4        unknown    [deu] low 
http-h264_aac_mp4_http_na_na-high  mp4        unknown    [deu] high 
hls-344                            mp4        384x216     344k , avc1.66.30, mp4a.40.2
hls-895                            mp4        640x360     895k , avc1.77.30, mp4a.40.2
hls-1541                           mp4        720x406    1541k , avc1.77.30, mp4a.40.2
hls-2203                           mp4        1280x720   2203k , avc1.77.30, mp4a.40.2 (best)
$
```
Pending the next release, you could [install it locally](https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/) with `pip3 --user`.

**Comment by dirkf** [comment]
Please open a new issue if this is still a problem after the next update of the ZDF extractor.
