### ISSUE TITLE
MTV.com broken

### ISSUE THREAD

**Issue by mr100percent** [ytdl-org/youtube-dl#30678]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.mtv.com/video-clips/s5iqyc/mtv-cribs-dj-khaled']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 2dc375acc
[debug] Python version 3.10.2 (CPython) - macOS-12.2.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.0, ffprobe 5.0
[debug] Proxy map: {}
[mtv] mtv-cribs-dj-khaled: Downloading webpage
Traceback (most recent call last):
  File "/opt/homebrew/bin/youtube-dl", line 33, in <module>
    sys.exit(load_entry_point('youtube-dl==2021.12.17', 'console_scripts', 'youtube-dl')())
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/__init__.py", line 475, in main
    _real_main(argv)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/mtv.py", line 300, in _real_extract
    mgid = self._extract_mgid(webpage)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/mtv.py", line 293, in _extract_mgid
    mgid = video_player['props']['media']['video']['config']['uri']
TypeError: 'NoneType' object is not subscriptable

## Description

Using M1 macOS, able to properly download on other sites. It appears all video clips are no longer downloadable when they had been on prior releases a few months ago. It's unclear whether the site changed.

**Comment by dirkf** [comment]
I expect this is the same problem as found for related sites that use the same technology and should be fixed by PR #30149 when it's revived and merged.

**Comment by 89z** [comment]
Hey, look what I found:

- https://neutron-api.viacom.tech/api/2.9/property?brand=mtv&platform=web&region=US-PHASE1&type=episode&shortId=scyb0g
- https://neutron-api.viacom.tech/api/2.9/property?brand=mtv&platform=web&region=US-PHASE1&type=showvideo&shortId=s5iqyc

**Comment by 89z** [comment]
If it helps, I think I have a working implementation of this now:

~~~
PS C:\> mtv -i -a mtv.com/episodes/scyb0g
GET https://neutron-api.viacom.tech/api/2.9/property?brand=mtv&platform=web&region=US-PHASE1&shortId=scyb0g&type=episode
GET https://topaz.viacomcbs.digital/topaz/api/mgid:arc:episode:mtv.com:96defb28-d238-11e1-a549-0026b9414f30/mica.json?clientPlatform=android
GET https://topaz.viacomcbs.digital/h/a/dG9wYXoxYDk2ZGVmYjI4LWQyMzgtMTFlMS1hNTQ5LTAwMjZiOTQxNGYzMGA3YzMwNTVhM2QzZjQ1ZGY0ZjUyZDkzZGZjZTE0NGQwMTQ4NTZjYzUyYFNrZkhuTWZPS1pXR1dHSnM4MFJQSFMxTGZ0VV9yTzBhdWtQU3hrTTRKc2c/master.m3u8?mgid=mgid:arc:episode:mtv.com:96defb28-d238-11e1-a549-0026b9414f30&ts=1633969951-0&pthash=7c3055a3d3f45df4f52d93dfce144d014856cc52&hdnts=exp=1646347175~acl=/h/a/dG9wYXoxYDk2ZGVmYjI4LWQyMzgtMTFlMS1hNTQ5LTAwMjZiOTQxNGYzMGA3YzMwNTVhM2QzZjQ1ZGY0ZjUyZDkzZGZjZTE0NGQwMTQ4NTZjYzUyYFNrZkhuTWZPS1pXR1dHSnM4MFJQSFMxTGZ0VV9yTzBhdWtQU3hrTTRKc2c/*~hmac=cf1875f91a6f4f35eddd27ceb7a9023d83429d02b47c52486430cf1cf2ded01c
Resolution:320x240 Bandwidth:268860 Codecs:avc1.4d401e,mp4a.40.2 Audio:audio0
Resolution:480x360 Bandwidth:410154 Codecs:avc1.4d401f,mp4a.40.2 Audio:audio0
Resolution:576x432 Bandwidth:659235 Codecs:avc1.4d401f,mp4a.40.2 Audio:audio0
Resolution:640x480 Bandwidth:910392 Codecs:avc1.4d401f,mp4a.40.2 Audio:audio0
Resolution:768x576 Bandwidth:1287890 Codecs:avc1.4d401f,mp4a.40.2 Audio:audio0
~~~

Its challenging, as MTV uses separate video and audio tracks, and they also encrypt both, with separate keys. In addition, the keys use relative paths, so you have to make sure to resolve them.

https://github.com/89z/mech/blob/v1.48.9/cmd/mtv/mtv.go#L66-L96

**Comment by 89z** [comment]
FYI I discovered that the Topaz API has been blocked for some episodes of Aeon Flux. For example, 1x1 works fine:

https://topaz.viacomcbs.digital/topaz/api/mgid:arc:episode:mtv.com:96defb28-d238-11e1-a549-0026b9414f30/mica.json?clientPlatform=desktop

supposedly 1x3 should work, but if you try it on the website, you get:

> Sorry, this video is not available from your location

and the API fails with `desktop` or `android`:

https://topaz.viacomcbs.digital/topaz/api/mgid:arc:episode:mtv.com:96defbbe-d238-11e1-a549-0026b9414f30/mica.json?clientPlatform=desktop

https://topaz.viacomcbs.digital/topaz/api/mgid:arc:episode:mtv.com:96defbbe-d238-11e1-a549-0026b9414f30/mica.json?clientPlatform=android

YT-DLP has a workaround using the MediaGenerator API, but its slow, and it pulls the episode in chapters, rather than one long file. Personally I am switching to Paramount for this show:

https://paramountplus.com/shows/aeon-flux

as the extractor doesnt have these issues.

**Comment by 89z** [comment]
Maybe off topic, but I just noticed that both MTV and Paramount only offer season one of Aeon Flux:

- https://www.mtv.com/shows/aeon-flux
- https://www.paramountplus.com/shows/aeon-flux

**Comment by notsolowki** [comment]
I'm also having a problem with mtv "Http Internal Server Error 500" Has anyone managed to get it working yet?

**Comment by dirkf** [comment]
See https://github.com/ytdl-org/youtube-dl/issues/31056#issuecomment-1351661662.
