### ISSUE TITLE
AttributeError when trying to download a video from Facebook

### ISSUE THREAD

**Issue by nolemretaWxd** [ytdl-org/youtube-dl#30681]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
E:\Pobrane>youtube-dl --cookies cookies.txt -v https://www.facebook.com/stoneheart.sakamaki/videos/702961650712479
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'cookies.txt', '-v', 'https://www.facebook.com/stoneheart.sakamaki/videos/702961650712479']
[debug] Encodings: locale cp1250, fs utf-8, out utf-8, pref cp1250
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.7 (CPython) - Windows-10-10.0.22557-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] 702961650712479: Downloading webpage
Traceback (most recent call last):
  File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\Scripts\youtube-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\__init__.py", line 475, in main
    _real_main(argv)
  File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\facebook.py", line 680, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\facebook.py", line 499, in _extract_from_url
    parse_attachment(attachment)
  File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\facebook.py", line 480, in parse_attachment
    media = attachment.get(key) or {}
AttributeError: 'NoneType' object has no attribute 'get'
```

## Description

When trying to download a video from private Facebook group, I get an Attribute error saying that object has no attribute get. cookies.txt are extracted from Facebook cookies via a Firefox extension (tested with --username and --password as well)

**Comment by 89z** [comment]
Please provide username and password or cookies.

**Comment by nolemretaWxd** [comment]
> Please provide username and password or cookies.

XD you want me to give username and password to my Facebook account?

**Comment by 89z** [comment]
How else are we supposed to troubleshoot the problem, the force?

**Comment by nolemretaWxd** [comment]
> How else are we supposed to troubleshoot the problem, the force?

Without my Facebook account. Tf are you thinking that I'll give you access to my account, my personal info, my friends personal info and everything about me.

**Comment by 89z** [comment]
If no one can access the video in question, then it will be difficult to help you. Good luck.

**Comment by nolemretaWxd** [comment]
> If no one can access the video in question, then it will be difficult to help you. Good luck.

I can give you link to the group and you can join it. But I won't give you my Facebook account.

**Comment by 89z** [comment]
Look, do whatever you want. But again, unless people can get to the video somehow, its not really possible to help you. Someone could test on another private video, but nothing guarantees that each video will have the same extraction process.

**Comment by nolemretaWxd** [comment]
No one who's thinking straight would (and will) intentionally give out their Facebook account to some random person on the internet (or any account).

**Comment by nolemretaWxd** [comment]
https://www.facebook.com/groups/205783714575737
Here's a link to that group. Join it yourself and use your account info

**Comment by 89z** [comment]
Youre the one who wants help. If you want help, this is how you get it. When you take your car to the shop, do you refuse to give them your car key?

**Comment by nolemretaWxd** [comment]
Car keys aren't credentials to your account with personal information like school I go to, my first name and surname, town I live in, and my friends info.

**Comment by 89z** [comment]
Look, I dont care about any of that stuff. I was only concerned to help you access the video. But based on your attitude, I am not interested to do that anymore.

**Comment by nolemretaWxd** [comment]
> I was only concerned to help you access the video.
By wanting my personal info?

**Comment by 89z** [comment]
Good luck to you.

**Comment by nolemretaWxd** [comment]
> Good luck to you.

And to you with thinking that someone will give you private accounts.

**Comment by 89z** [comment]
I see previous comments were removed, so I'm just going to restate my original point. If you wish for help, you're going to need to provide username and password, or cookies. People need to be able to access the video somehow, to fix the extractor. This could mean you making a dummy account and posting your own private video, or similar methods. But unless people can access the video you're talking about, its going to be difficult to help.

**Comment by nolemretaWxd** [comment]
> I see previous comments were removed, so I'm just going to restate my original point. If you wish for help, you're going to need to provide username and password, or cookies. People need to be able to access the video somehow, to fix the extractor. This could mean you making a dummy account and posting your own private video, or similar methods. But unless people can access the video you're talking about, its going to be difficult to help.

Once again: I'm not gonna give out my account credentials to some random on the internet (thus giving also my personal information). I can give link to the group video is on, but I'm not gonna give out my Facebook account

**Comment by 89z** [comment]
> Once again: I'm not gonna give out my account credentials to some random on the internet (thus giving also my personal information)

No one here cares about your personal information. People are just here trying to help. If you don't want to share your credentials, even a dummy account credentials, of course that's your choice. But don't be surprised if your issue just sits here. I linked to one just now that was posted about three years ago, still sitting open. That could be yours as well. Fair warning.

**Comment by nolemretaWxd** [comment]
> [89z](https://github.com/89z) mentioned this issue 1 minute ago Censored Facebook videos #22322

It's a diffrent issue XD

**Comment by nolemretaWxd** [comment]
> No one here cares about your personal information. 

Still it's my PERSONAL account, and also with that account I use a password that I use with a lot of sites so yeah XD.
You can just join the group the video is on. I would also need to join it from a dummy account so no diffrence XD

**Comment by 89z** [comment]
Look at this:

https://github.com/ytdl-org/youtube-dl/search?q=label:account-needed&state=open&type=issues

nearly 200 issues that are open for the same reason.

**Comment by nolemretaWxd** [comment]
> Look at this:
> 
> https://github.com/ytdl-org/youtube-dl/search?q=label:account-needed&state=open&type=issues
> 
> nearly 200 issues that are open for the same reason.

You could just join the group. But you're too lazy to do that and try to get someone's account on Facebook.
https://www.google.com/search?channel=nrow5&client=firefox-b-d&q=why+you+shouldn%27t+give+your+account+info+to+some+random+people+on+the+internet <-- read this

**Comment by nolemretaWxd** [comment]
And also as I remember correctly, you don't want to help anymore so why do you give a shit about this issue XD

![obraz](https://user-images.githubusercontent.com/31414969/155802688-ba8b642e-f5f1-493f-b574-41f768891686.png)

**Comment by 89z** [comment]
I have put countless hours into developing several extractors, so I dont think lazy would be a good way to describe me.

**Comment by nolemretaWxd** [comment]
> I have put countless hours into developing several extractors, so I dont think lazy would be a good way to describe me.

Yeah it is

**Comment by nolemretaWxd** [comment]
And also you can't see that owners of this repo are deleting your comments because you're trying to get into my personal Facebook account? Or you're too dumb (because I can't put your way of thinking in any other way) to see that and still think that people are giving their accounts to some random strangers on the internet

**Comment by 89z** [comment]
> And also you can't see that owners of this repo are deleting your comments because you're trying to get into my personal Facebook account?

I have been deleting my own comments, as pretty much all of this back and forth is pointless of topic nonsense. And I am not trying to "get into your account", I am just trying to help.

> Or you're too dumb (because I can't put your way of thinking in any other way) to see that and still think that people are giving their accounts to some random strangers on the internet

I am not a random person, I have developed several extractors, which you can see from my profile page. Again, if you dont want to share account information, even for a dummy account, thats your choice. But by doing that, you risk going into the "account-needed" graveyard. Good luck to you.

**Comment by nolemretaWxd** [comment]
> I am not a random person, I have developed several extractors, which you can see from my profile page.

Yes you ARE because I DON'T know you.

> And I am not trying to "get into your account", I am just trying to help.

No?
![obraz](https://user-images.githubusercontent.com/31414969/155803845-3a5f3fcb-b1e7-4ef0-af6a-2eb204450593.png)

> Again, if you dont want to share account information, even for a dummy account, thats your choice.

You can join the group that the video is on, and it would be faster than me making a brand new account.

**Comment by 89z** [comment]
> You can join the group that the video is on, and it would be faster than me making a brand new account.

Youre the one who needs help. You should be making the process easy for people trying to help, not the other way around.

**Comment by nolemretaWxd** [comment]
> > You can join the group that the video is on, and it would be faster than me making a brand new account.
> 
> Youre the one who needs help. You should be making the process easy for people trying to help, not the other way around.

I would, that's why I said that I would assist you with joining the group (because it's in Polish) to make it easy for you. I simply do not trust you with giving my account because I don't know what you could do on it.

**Comment by nolemretaWxd** [comment]
And why still do you give a shit about this issue even you don't want to help, you're just wasting my time.

**Comment by 89z** [comment]
If you do not want to share credentials on main account, please provide credentials for dummy account. Thank you.

**Comment by nolemretaWxd** [comment]
> If you do not want to share credentials on main account, please provide credentials for dummy account. Thank you.

I would have to make that account + join the group, which you could also do.

If you still want access to my account, give access to yours, then I would give access to mine.

**Comment by october262** [comment]
> ## Checklist
> * [x]  I'm reporting a broken site support issue
> * [x]  I've verified that I'm running youtube-dl version **2021.12.17**
> * [x]  I've checked that all provided URLs are alive and playable in a browser
> * [x]  I've checked that all URLs and arguments with special characters are properly quoted or escaped
> * [x]  I've searched the bugtracker for similar bug reports including closed ones
> * [x]  I've read bugs section in FAQ
> 
> ## Verbose log
> ```
> E:\Pobrane>youtube-dl --cookies cookies.txt -v https://www.facebook.com/stoneheart.sakamaki/videos/702961650712479
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['--cookies', 'cookies.txt', '-v', 'https://www.facebook.com/stoneheart.sakamaki/videos/702961650712479']
> [debug] Encodings: locale cp1250, fs utf-8, out utf-8, pref cp1250
> [debug] youtube-dl version 2021.12.17
> [debug] Python version 3.9.7 (CPython) - Windows-10-10.0.22557-SP0
> [debug] exe versions: none
> [debug] Proxy map: {}
> [facebook] 702961650712479: Downloading webpage
> Traceback (most recent call last):
>   File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\Scripts\youtube-dl.exe\__main__.py", line 7, in <module>
>   File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\__init__.py", line 475, in main
>     _real_main(argv)
>   File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\__init__.py", line 465, in _real_main
>     retcode = ydl.download(all_urls)
>   File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2068, in download
>     res = self.extract_info(
>   File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
>     return self.__extract_info(url, ie, download, extra_info, process)
>   File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
>     return func(self, *args, **kwargs)
>   File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
>     ie_result = ie.extract(url)
>   File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
>     ie_result = self._real_extract(url)
>   File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\facebook.py", line 680, in _real_extract
>     return self._extract_from_url(real_url, video_id)
>   File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\facebook.py", line 499, in _extract_from_url
>     parse_attachment(attachment)
>   File "C:\Users\nolemretaW\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\facebook.py", line 480, in parse_attachment
>     media = attachment.get(key) or {}
> AttributeError: 'NoneType' object has no attribute 'get'
> ```
> 
> ## Description
> When trying to download a video from private Facebook group, I get an Attribute error saying that object has no attribute get. cookies.txt are extracted from Facebook cookies via a Firefox extension (tested with --username and --password as well)

play the video and click the 3 dots ... in the upper right hand corner of the video select copy link and see if that'll work in downloading the video.

**Comment by nolemretaWxd** [comment]
Still doesn't work

**Comment by october262** [comment]
> https://www.facebook.com/stoneheart.sakamaki/videos/702961650712479

copy this link - https://www.facebook.com/stoneheart.sakamaki/videos/702961650712479
now, open a new browser tab, paste the link and change www to mbasic, will
the video now play ??

**Comment by nolemretaWxd** [comment]
> > https://www.facebook.com/stoneheart.sakamaki/videos/702961650712479
> 
> copy this link - https://www.facebook.com/stoneheart.sakamaki/videos/702961650712479 now, open a new browser tab, paste the link and change www to mbasic, will the video now play ??

yes

**Comment by october262** [comment]
> > > https://www.facebook.com/stoneheart.sakamaki/videos/702961650712479
> > 
> > 
> > copy this link - https://www.facebook.com/stoneheart.sakamaki/videos/702961650712479 now, open a new browser tab, paste the link and change www to mbasic, will the video now play ??
> 
> yes

does right clicking on the video give you the option to save the video ??
you may have to have a browser add-on that allows right click.

**Comment by nolemretaWxd** [comment]
it allows but it tries to save as htm file, used 4k video downloader to download the actual video

**Comment by dirkf** [comment]
Regardless of all the above, the original issue looks like the same problem as #30650 and #30474.
