### ISSUE TITLE
[macOS] "image not found" error for youtube playlist

### ISSUE THREAD

**Issue by alex4200** [ytdl-org/youtube-dl#30724]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl -v --yes-playlist --audio-format mp3 https://www.youtube.com/playlist?list=PLgtfSiKjx3eDcbBThQPYJt8Mw1Bvs2Poa
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--yes-playlist', '--audio-format', 'mp3', 'https://www.youtube.com/playlist?list=PLgtfSiKjx3eDcbBThQPYJt8Mw1Bvs2Poa']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.6.9 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg present, ffprobe present, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] PLgtfSiKjx3eDcbBThQPYJt8Mw1Bvs2Poa: Downloading webpage
[download] Downloading playlist: Station Eleven Soundtrack
[youtube:tab] playlist Station Eleven Soundtrack: Downloading 33 videos
[download] Downloading video 1 of 33
[youtube] -XHqXhET5rQ: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://rr2---sn-hgn7rne7.googlevideo.com/videoplayback?expire=1646668732&ei=W9clYtX6O_2Ax_AP8_mLWA&ip=92.184.100.55&id=o-ADVVX_g7ui9bWRJXNPA23hgOTOBs5e0qWM1nnj--jY_B&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=Iv&mm=31%2C29&mn=sn-hgn7rne7%2Csn-hgn7yn7e&ms=au%2Crdu&mv=m&mvi=2&pl=22&gcr=fr&initcwndbps=1067500&vprv=1&mime=video%2Fwebm&ns=YRV2gWv0tDzT-cyevhpN2e0G&gir=yes&clen=13869095&dur=175.720&lmt=1615791144252167&mt=1646646785&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=2311222&n=UvJnjN7-1YOsuPStn&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAPF8m6C9Cb4Ez7FckJnbVIhzE1sxic7IvzKeckI0nr3VAiACFVzWdjuejq1AOUZizKkDgjrIQm9h6TVNEU7G5S8t0Q%3D%3D&sig=AOq0QJ8wRAIgY-QWKM7ay49aBjQaFlQNvIAgQO_hhBcdPGKX30_ESeQCIA4q6tuFtLaoOX39jdOorX4BitufE4zCgLItqdMae-4-'
[download] Destination: Turn Around, Look At Me (Remastered 2003)--XHqXhET5rQ.f248.webm
[download] 100% of 13.23MiB in 02:47
[debug] Invoking downloader on 'https://rr2---sn-hgn7rne7.googlevideo.com/videoplayback?expire=1646668732&ei=W9clYtX6O_2Ax_AP8_mLWA&ip=92.184.100.55&id=o-ADVVX_g7ui9bWRJXNPA23hgOTOBs5e0qWM1nnj--jY_B&itag=251&source=youtube&requiressl=yes&mh=Iv&mm=31%2C29&mn=sn-hgn7rne7%2Csn-hgn7yn7e&ms=au%2Crdu&mv=m&mvi=2&pl=22&gcr=fr&initcwndbps=1067500&vprv=1&mime=audio%2Fwebm&ns=YRV2gWv0tDzT-cyevhpN2e0G&gir=yes&clen=3021703&dur=175.741&lmt=1615790775970025&mt=1646646785&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=2311222&n=UvJnjN7-1YOsuPStn&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgQ_iGVDjME0Ae2ETMwMjRtIZzJEYctP_BMzH1-ZqrgV0CIDLh57JbRTFO6JMeaEEKc0UfrdhZWRPbWGqhYKWQJ9Xr&sig=AOq0QJ8wRAIgMfOMqFhBaDNiOA0VzDDEW9sf4kUpi-zCNChkNDvmomUCIBUX5dBCxMj0WwguxP7gwvD-4GdzvX6XwwURQwL8WHqY'
[download] Destination: Turn Around, Look At Me (Remastered 2003)--XHqXhET5rQ.f251.webm
[download] 100% of 2.88MiB in 00:36
[ffmpeg] Merging formats into "Turn Around, Look At Me (Remastered 2003)--XHqXhET5rQ.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Turn Around, Look At Me (Remastered 2003)--XHqXhET5rQ.f248.webm' -i 'file:Turn Around, Look At Me (Remastered 2003)--XHqXhET5rQ.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Turn Around, Look At Me (Remastered 2003)--XHqXhET5rQ.temp.webm'
[debug] dyld: Library not loaded: /usr/local/opt/libffi/lib/libffi.7.dylib
  Referenced from: /usr/local/opt/p11-kit/lib/libp11-kit.0.dylib
ERROR:   Reason: image not found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2115, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 526, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 238, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Reason: image not found
```

## Description

I am trying to download a playlist from youtube, which results in an "image not found" error.

**Comment by dirkf** [comment]
_ffmpeg_ is broken on your Mac (a shared library is missing). Reinstall it.

Or [these people](https://github.com/platformio/platform-lattice_ice40/issues/7) have had some success by creating a symlink for the missing library.

**Comment by alex4200** [comment]
Yes, a re-install of `ffmpeg` seem to have fixed this problem. Thanks for the solution.
