### ISSUE TITLE
YouTube videos download html files?

### ISSUE THREAD

**Issue by mjreagle** [ytdl-org/youtube-dl#30735]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
mjreagle@R-NAS-1:/volume5/docker/youTubeDl$ ./downloadYouTube.sh
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--playlist-reverse', '--dateafter', 'now-25weeks', '--download-archive', '/volume5/docker/youTubeDl/downloaded.txt', '-i', '-o', '%(uploader)s/%(playlist)s/%(playlist)s - S01E%(playlist_index)s - %(title)s [%(id)s].%(ext)s', '--add-metadata', '--write-thumbnail', '--no-check-certificate', '-v', '--abort-on-error', '--cache-dir', '/volume5/docker/youTubeDl/cache', '--batch-file=/volume5/docker/youTubeDl/channelList.txt']
[debug] Batch file urls: ['https://www.youtube.com/watch?v=TWTfhyvzTx0']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.8 (CPython) - Linux-3.10.108-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.1.6
[debug] Proxy map: {}
[youtube] TWTfhyvzTx0: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[youtube] TWTfhyvzTx0: Downloading thumbnail ...
[youtube] TWTfhyvzTx0: Writing thumbnail to: Star Wars/NA/NA - S01ENA - Obi-Wan Kenobi _ Teaser Trailer _ Disney+ [TWTfhyvzTx0].jpg
[debug] Invoking downloader on 'https://rr3---sn-uhvcpax0n5-no5z.googlevideo.com/videoplayback?expire=1647055551&ei=X74rYqXoCYeGkgb8-7nQCw&ip=172.58.21.88&id=o-AM_r_kV4tecRBU36PeKdsa5beZid88pQWOjd4n3KvOrW&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=Hr&mm=31%2C29&mn=sn-uhvcpax0n5-no5z%2Csn-a5mekn6d&ms=au%2Crdu&mv=m&mvi=3&pl=22&initcwndbps=317500&vprv=1&mime=video%2Fmp4&ns=5TXIUikbqRD2tbVIkhcIH9kG&gir=yes&clen=24344738&dur=105.980&lmt=1646804933708342&mt=1647033671&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=6310224&n=JsYLtIv1Ey9rmVwzzx&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgILf8BZUigmPUsb-UEH8X871h9xm4jJZQh5Ygzf0raTQCIF87q3yC_9Cn2IZlTKWYSS4u_fGlFgQ8yHYJQHXgqDfQ&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhALOwDrqaj0vBStgF4PwbHuj_4RtLlJlXx5NrsSV4xnQDAiEAyxTgFh7Nts-rfkYjJw9sR_3qxKmvNEQ6KMGOYvsPlcs%3D'
[download] Destination: Star Wars/NA/NA - S01ENA - Obi-Wan Kenobi _ Teaser Trailer _ Disney+ [TWTfhyvzTx0].f137.mp4
[download] 100% of 463.00B in 00:00
[debug] Invoking downloader on 'https://rr3---sn-uhvcpax0n5-no5z.googlevideo.com/videoplayback?expire=1647055551&ei=X74rYqXoCYeGkgb8-7nQCw&ip=172.58.21.88&id=o-AM_r_kV4tecRBU36PeKdsa5beZid88pQWOjd4n3KvOrW&itag=140&source=youtube&requiressl=yes&mh=Hr&mm=31%2C29&mn=sn-uhvcpax0n5-no5z%2Csn-a5mekn6d&ms=au%2Crdu&mv=m&mvi=3&pl=22&initcwndbps=317500&vprv=1&mime=audio%2Fmp4&ns=5TXIUikbqRD2tbVIkhcIH9kG&gir=yes&clen=1716561&dur=106.022&lmt=1646804918944709&mt=1647033671&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=6310224&n=JsYLtIv1Ey9rmVwzzx&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAIOECeVSNUH76gyTlo8l13O3AKsZM_zADwBKxxujh9f1AiEA15tKqeO69QnYiOI3a8BfnSbIAuybMS7Q_wkTj9p7LC4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhALOwDrqaj0vBStgF4PwbHuj_4RtLlJlXx5NrsSV4xnQDAiEAyxTgFh7Nts-rfkYjJw9sR_3qxKmvNEQ6KMGOYvsPlcs%3D'
[download] Destination: Star Wars/NA/NA - S01ENA - Obi-Wan Kenobi _ Teaser Trailer _ Disney+ [TWTfhyvzTx0].f140.m4a
[download] 100% of 463.00B in 00:00
[ffmpeg] Merging formats into "Star Wars/NA/NA - S01ENA - Obi-Wan Kenobi _ Teaser Trailer _ Disney+ [TWTfhyvzTx0].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Star Wars/NA/NA - S01ENA - Obi-Wan Kenobi _ Teaser Trailer _ Disney+ [TWTfhyvzTx0].f137.mp4' -i 'file:Star Wars/NA/NA - S01ENA - Obi-Wan Kenobi _ Teaser Trailer _ Disney+ [TWTfhyvzTx0].f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Star Wars/NA/NA - S01ENA - Obi-Wan Kenobi _ Teaser Trailer _ Disney+ [TWTfhyvzTx0].temp.mp4'
[debug] ffmpeg version 4.1.6 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7.5.0 (GCC)
  configuration: --prefix=/usr --incdir='${prefix}/include/ffmpeg' --arch=i686 --target-os=linux --cross-prefix=/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --enable-cross-compile --enable-optimizations --enable-pic --enable-gpl --enable-shared --disable-static --disable-stripping --enable-version3 --enable-encoders --enable-pthreads --disable-protocols --disable-protocol=rtp --enable-protocol=file --enable-protocol=pipe --disable-muxer=image2 --disable-muxer=image2pipe --disable-swscale-alpha --disable-ffplay --disable-ffprobe --disable-doc --disable-devices --disable-bzlib --disable-altivec --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libmp3lame --disable-vaapi --disable-cuvid --disable-nvenc --disable-decoder=amrnb --disable-decoder=ac3 --disable-decoder=ac3_fixed --disable-encoder=zmbv --disable-encoder=dca --disable-decoder=dca --disable-encoder=ac3 --disable-encoder=ac3_fixed --disable-encoder=eac3 --disable-decoder=eac3 --disable-encoder=truehd --disable-decoder=truehd --disable-encoder=hevc_vaapi --disable-decoder=hevc --disable-muxer=hevc --disable-demuxer=hevc --disable-parser=hevc --disable-bsf=hevc_mp4toannexb --x86asmexe=yasm --cc=/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-wrap-gcc --enable-yasm --enable-libx264 --enable-encoder=libx264
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1626440] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1626440] moov atom not found
ERROR: file:Star Wars/NA/NA - S01ENA - Obi-Wan Kenobi _ Teaser Trailer _ Disney+ [TWTfhyvzTx0].f137.mp4: Invalid data found when processing input
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2115, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 526, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 238, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:Star Wars/NA/NA - S01ENA - Obi-Wan Kenobi _ Teaser Trailer _ Disney+ [TWTfhyvzTx0].f137.mp4: Invalid data found when processing input
```

## Description

Likely an issue with how I have it setup.

When executing youtube-dl and attempting to download any YouTube video - I get 3 files as expected - an mp4, and m4a, and a jpeg thumbnail.  The thumbnail is fine - but both the audio & video files when downloaded are exactly 463 bytes....which if you open the contents of, are actually html files (see attached).  Thus, as expected FFMPEG is failing when trying to combine them since they are not of the proper type.

This is occurring for all YouTube videos - but below is an example of one.

Service: YouTube
Example Video Link:  https://www.youtube.com/watch?v=TWTfhyvzTx0
Parameters used for download:

/usr/local/bin/youtube-dl --playlist-reverse \
		   --dateafter now-25weeks \
		   --download-archive /volume5/docker/youTubeDl/downloaded.txt \
		   -i \
		   -o "%(uploader)s/%(playlist)s/%(playlist)s - S01E%(playlist_index)s - %(title)s [%(id)s].%(ext)s" \
		   --add-metadata \
		   --write-thumbnail \
		   --no-check-certificate \
		   -v \
		   --abort-on-error \
		   --cache-dir /volume5/docker/youTubeDl/cache \
		   --batch-file=/volume5/docker/youTubeDl/channelList.txt

Sample of the html file generated attached (extension changed to txt manually).

[NA - S01ENA - Obi-Wan Kenobi _ Teaser Trailer _ Disney+ [TWTfhyvzTx0].f137.mp4.txt](https://github.com/ytdl-org/youtube-dl/files/8236168/NA.-.S01ENA.-.Obi-Wan.Kenobi._.Teaser.Trailer._.Disney%2B.TWTfhyvzTx0.f137.mp4.txt)

**Comment by 89z** [comment]
Not sure why youre giving playlist arguments to a single video. At any rate, this works as expected:

~~~
PS C:\> youtube-dl TWTfhyvzTx0
[youtube] TWTfhyvzTx0: Downloading webpage
[download] Destination: Obi-Wan Kenobi _ Teaser Trailer _ Disney+-TWTfhyvzTx0.f137.mp4
[download]   1.8% of 23.22MiB at 39.43KiB/s ETA 09:52
~~~
