### ISSUE TITLE
ABC iview does not work anymore

### ISSUE THREAD

**Issue by lamjoey** [ytdl-org/youtube-dl#30753]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```ShellSession
>youtube-dl --all-subs --download-archive downloaded.txt --verbose https://iview.abc.net.au/video/CH2003Q001S00
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--all-subs', '--download-archive', 'downloaded.txt', '--verbose', 'https://iview.abc.net.au/video/CH2003Q001S00']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-07-29-cbb6ba2, ffprobe git-2020-07-29-cbb6ba2
[debug] Proxy map: {}
[debug] Using fake IP 1.147.146.198 (AU) as X-Forwarded-For.
[abc.net.au:iview] CH2003Q001S00: Downloading JSON metadata
[abc.net.au:iview] CH2003Q001S00: Downloading webpage
[abc.net.au:iview] CH2003Q001S00: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Bedroom-CH2003Q001S00.en.vtt
[debug] Invoking downloader on 'https://iview-vod-hls.akamaized.net/prod/ch2/CH2003Q001S00MA1D1/20211121092403/hls/4500000/hdntl=exp=1647703220~acl=%2f*~data=hdntl~hmac=010b307d4fffb7985eada307ce49073a3149be7fb30e767bd5227582767abd81/stream.m3u8?aka_me_session_id=AAAAAAAAAAC09DViAAAAAMLTmt88EDOtmRnn69Pgf0Skvh8izohioo2JMY9rW%2fO6%2fePCX4BrqIv5y%2fTqt7%2fqEDsDCyhnqIWx&aka_media_format_type=hls'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 42
[download] Destination: Bedroom-CH2003Q001S00.mp4
[download]  21.4% of ~52.01MiB at Unknown speed ETA Unknown ETATraceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\__init__.py", line 465, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2069, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 847, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 881, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 1692, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 1976, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 1915, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\downloader\hls.py", line 180, in real_download
  File "C:\Python\Python34\lib\site-packages\Crypto\Cipher\blockalgo.py", line 295, in decrypt
ValueError: Input strings must be a multiple of 16 in length
```

## Description

I was able to download videos from ABC iview, however, it stopped working recently.

The video can be viewed from a browser, connection must be from within Australia.

**Comment by dirkf** [comment]
Is this repeatable? It looks like the data being decoded as AES-CBC is somehow invalid. As you say, it needs AU IP to debug.

**Comment by lamjoey** [comment]
> Is this repeatable? It looks like the data being decoded as AES-CBC is somehow invalid. As you say, it needs AU IP to debug.

Yes, this is repeatable.

All the videos from ABC iview produce similar error.

**Comment by gamer191** [comment]
> All the videos from ABC iview produce similar error.

Not for me (I haven't tried your example)

```
youtube-dl https://iview.abc.net.au/video/NC2103H039S00 --verbose --ffmpeg-location "C:\Users\REDACTED\ffmpeg\bin"
[debug] System config: []
[debug] User config: ['-o', '%userprofile%\\youtube.dl\\%(title)s.%(ext)s', '--abort-on-error']
[debug] Custom config: []
[debug] Command-line args: ['https://iview.abc.net.au/video/NC2103H039S00', '--verbose', '--ffmpeg-location', 'C:\\Users\\REDACTED\\ffmpeg\\bin']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-105580-g68595b46cb-20220213, ffprobe N-105580-g68595b46cb-20220213
[debug] Proxy map: {}
[debug] Using fake IP 1.128.98.218 (AU) as X-Forwarded-For.
[abc.net.au:iview] NC2103H039S00: Downloading JSON metadata
[abc.net.au:iview] NC2103H039S00: Downloading webpage
[abc.net.au:iview] NC2103H039S00: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://iview-vod-hls.akamaized.net/prod/nc2/NC2103H039S00ED1D1/20211108191354/hls/4500000/hdntl=exp=1647855236~acl=%2f*~data=hdntl~hmac=155c547280ab53ffeb89ba288b8cc77c540447424977c03f87489c3e32d2ce6a/stream.m3u8?aka_me_session_id=AAAAAAAAAACERjhiAAAAAP7DWKJJL1GQqjobvClGC3qh2VoisWg+b9aOHJJyfCJTw7NCl5c1Sv1jjbcGgsQxv7E%2fboyFnsyo&aka_media_format_type=hls'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 291
[download] Destination: C:\Users\REDACTED\youtube.dl\Series 2021 Obeid Inc.mp4
[download] 100% of 734.38MiB in 04:02
[debug] ffmpeg command line: "C:\Users\REDACTED\ffmpeg\bin\ffprobe" -show_streams "file:C:\Users\REDACTED\youtube.dl\Series 2021 Obeid Inc.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "C:\Users\REDACTED\youtube.dl\Series 2021 Obeid Inc.mp4"
[debug] ffmpeg command line: "C:\Users\REDACTED\ffmpeg\bin\ffmpeg" -y -loglevel "repeat+info" -i "file:C:\Users\REDACTED\youtube.dl\Series 2021 Obeid Inc.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:C:\Users\REDACTED\youtube.dl\Series 2021 Obeid Inc.temp.mp4"
```

**Comment by gamer191** [comment]
> All the videos from ABC iview produce similar error.

Maybe send a list of videos that you tried it in and got that error, if you happen to remember them?

**Comment by dirkf** [comment]
If you had time to check OP's video, that could be useful.

**Comment by gamer191** [comment]
It works for me:
```
youtube-dl https://iview.abc.net.au/video/CH2003Q001S00 --verbose
[debug] System config: []
[debug] User config: ['-o', '%userprofile%\\youtube.dl\\%(title)s.%(ext)s', '--abort-on-error', '--ffmpeg-location', 'C:\\Users\\REDACTED\\ffmpeg\\bin']
[debug] Custom config: []
[debug] Command-line args: ['https://iview.abc.net.au/video/CH2003Q001S00', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-105580-g68595b46cb-20220213, ffprobe N-105580-g68595b46cb-20220213
[debug] Proxy map: {}
[debug] Using fake IP 1.137.112.249 (AU) as X-Forwarded-For.
[abc.net.au:iview] CH2003Q001S00: Downloading JSON metadata
[abc.net.au:iview] CH2003Q001S00: Downloading webpage
[abc.net.au:iview] CH2003Q001S00: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://iview-vod-hls.akamaized.net/prod/ch2/CH2003Q001S00MA1D1/20211121092403/hls/4500000/hdntl=exp=1647866175~acl=%2f*~data=hdntl~hmac=39d393e043cecdf7e55eadb54198f6a832560ab0cf2d72122799da7ce7a2012d/stream.m3u8?aka_me_session_id=AAAAAAAAAAA%2fcThiAAAAAHcdhNAxIbgyWivGKeEuvX6rjspoepjhbTfmgbkhFBJpM9scsUsiQl0p4QCmBej2guRtkqQm937d&aka_media_format_type=hls'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 42
[download] Destination: C:\Users\REDACTED\youtube.dl\Bedroom.mp4
[download] 100% of 49.33MiB in 00:13
[debug] ffmpeg command line: "C:\Users\REDACTED\ffmpeg\bin\ffprobe" -show_streams "file:C:\Users\REDACTED\youtube.dl\Bedroom.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "C:\Users\REDACTED\youtube.dl\Bedroom.mp4"
[debug] ffmpeg command line: "C:\Users\REDACTED\ffmpeg\bin\ffmpeg" -y -loglevel "repeat+info" -i "file:C:\Users\REDACTED\youtube.dl\Bedroom.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:C:\Users\REDACTED\youtube.dl\Bedroom.temp.mp4"
```

**Comment by gamer191** [comment]
@Iamjoey Does the video work in your browser? If it does work in your browser, does it work using YT-DLP?

**Comment by lamjoey** [comment]
Thank you all for testing it out, I just tried again and it is working this time.  I will try and find out what was wrong and report back.

> >youtube-dl --all-subs --download-archive downloaded.txt --verbose https://iview.abc.net.au/video/CH2003Q001S00
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--all-subs', '--download-archive', 'downloaded.txt', '--verbose', 'https://iview.abc.net.au/video/CH2003Q001S00']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2022-03-21-git-505a7d39cd-essentials_build-www.gyan.dev, ffprobe 2022-03-21-git-505a7d39cd-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[debug] Using fake IP 1.152.93.24 (AU) as X-Forwarded-For.
[abc.net.au:iview] CH2003Q001S00: Downloading JSON metadata
[abc.net.au:iview] CH2003Q001S00: Downloading webpage
[abc.net.au:iview] CH2003Q001S00: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Bedroom-CH2003Q001S00.en.vtt
[debug] Invoking downloader on 'https://iview-vod-hls.akamaized.net/prod/ch2/CH2003Q001S00MA1D1/20211121092403/hls/4500000/hdntl=exp=1648198916~acl=%2f*~data=hdntl~hmac=3c9f737f0957cdb86725cc2e6fda9efaca0decec485db58381d3c01ed799b442/stream.m3u8?aka_me_session_id=AAAAAAAAAAAEhT1iAAAAABeokFl+NPEXd640MaXidv4nhRyplG6af7OlihLfft9cdFGGCMsznU1lPBbYxG2M7OM6HQrNcXx4&aka_media_format_type=hls'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 42
[download] Destination: Bedroom-CH2003Q001S00.mp4
[download] 100% of 49.33MiB in 01:23
[debug] ffmpeg command line: ffprobe -show_streams "file:Bedroom-CH2003Q001S00.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "Bedroom-CH2003Q001S00.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Bedroom-CH2003Q001S00.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:Bedroom-CH2003Q001S00.temp.mp4"``

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30934

**Comment by Arsyad1105** [comment]
Hope nothing gone wrong this June.

**Comment by gamer191** [comment]
> Hope nothing gone wrong this June.

Huh? What's happening in June?

**Comment by Arsyad1105** [comment]
> 
> Huh? What's happening in June?

New episodes coming this June on ABC iView so I'm hoping YouTube-dl still can get video from ABC iView since they platform need to login now before watching.

**Comment by gamer191** [comment]
Fortunately you don't need to login or pass cookies to download ABC iview videos using youtube-dl

**Comment by dirkf** [comment]
See https://github.com/yt-dlp/yt-dlp/issues/1297#issuecomment-2408580037.
