### ISSUE TITLE
RTVE play doesn’t worb

### ISSUE THREAD

**Issue by Mimoza** [ytdl-org/youtube-dl#30754]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v "https://www.rtve.es/play/videos/cuentame-como-paso/t22-episodio-7-cansado-pequeno/6439165/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.rtve.es/play/videos/cuentame-como-paso/t22-episodio-7-cansado-pequeno/6439165/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.2 (CPython) - Linux-5.16.14-1-MANJARO-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0, ffprobe 5.0, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 6439165: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 6439165: Downloading webpage
[generic] 6439165: Extracting information
WARNING: [generic] 6439165: Failed to parse JSON Invalid control character at: line 13 column 510 (char 1100)
ERROR: Unsupported URL: https://www.rtve.es/play/videos/cuentame-como-paso/t22-episodio-7-cansado-pequeno/6439165/
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/generic.py", line 3489, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.rtve.es/play/videos/cuentame-como-paso/t22-episodio-7-cansado-pequeno/6439165/
```

## Description

I’ve seen the #30671 issue but as the error message and URL is different I think it can be better to make a separate report

**Comment by dirkf** [comment]
You have to back a bit further, This is actually the issue from #29522, for which there is a fix PR #29816.

Until this gets merged, RSN, just change '/play/' to '/alacarta/'.

**Comment by Mimoza** [comment]
Ok, sorry for the noise

**Comment by dirkf** [comment]
No problem.
