### ISSUE TITLE
Multiple issues with BBC Iplayer.

### ISSUE THREAD

**Issue by BlueHippo73** [ytdl-org/youtube-dl#30757]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
VERBOSE LOG 1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'mf_cloudfront-5510-1', 'https://www.bbc.co.uk/iplayer/episode/b09p5lt7/hairy-bikers-mediterranean-adventure-series-1-3-corsica', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-94421-gb3b7523feb, ffprobe N-94421-gb3b7523feb
[debug] Proxy map: {}
[bbc.co.uk] b09p5lt7: Downloading video page
[bbc.co.uk] b09p5lt7: Downloading playlist JSON
ERROR: Unable to download JSON metadata: HTTP Error 502: Bad Gateway (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

VERBOSE LOG 2
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'mf_cloudfront-5510-1', 'https://www.bbc.co.uk/iplayer/episode/b09p5lt7/hairy-bikers-mediterranean-adventure-series-1-3-corsica', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-94421-gb3b7523feb, ffprobe N-94421-gb3b7523feb
[debug] Proxy map: {}
[bbc.co.uk] b09p5lt7: Downloading video page
ERROR: Unable to download webpage: <urlopen error _ssl.c:584: The handshake operation timed out> (caused by URLError(timeout('_ssl.c:584: The handshake operation timed out',),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\utils.py", line 2737, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open

VERBOSE LOG 3
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'mf_cloudfront-5510-1', 'https://www.bbc.co.uk/iplayer/episode/b09p5lt7/hairy-bikers-mediterranean-adventure-series-1-3-corsica', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-94421-gb3b7523feb, ffprobe N-94421-gb3b7523feb
[debug] Proxy map: {}
[bbc.co.uk] b09p5lt7: Downloading video page
[bbc.co.uk] b09p5lt7: Downloading playlist JSON
[bbc.co.uk] b09p5lsl: Downloading media selection JSON
[bbc.co.uk] b09p5lsl: Downloading m3u8 information
[bbc.co.uk] b09p5lsl: Downloading m3u8 information
[bbc.co.uk] b09p5lsl: Downloading m3u8 information
[bbc.co.uk] b09p5lsl: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error _ssl.c:584: The handshake operation timed out>
[bbc.co.uk] b09p5lsl: Downloading m3u8 information
[bbc.co.uk] b09p5lsl: Downloading m3u8 information
WARNING: Failed to download m3u8 information: ''
[bbc.co.uk] b09p5lsl: Downloading MPD manifest
[bbc.co.uk] b09p5lsl: Downloading MPD manifest
[bbc.co.uk] b09p5lsl: Downloading MPD manifest
[bbc.co.uk] b09p5lsl: Downloading MPD manifest
ERROR: A network error has occurred. (caused by IncompleteRead(0 bytes read, 4073 more expected))
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\bbc.py", line 571, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\bbc.py", line 467, in _download_playlist
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\bbc.py", line 349, in _download_media_selector
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\bbc.py", line 361, in _download_media_selector_url
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\bbc.py", line 396, in _process_media_selector
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 2079, in _extract_mpd_formats
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 827, in _download_xml_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 671, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 721, in _webpage_read_content
  File "C:\Python\Python34\lib\http\client.py", line 549, in read
  File "C:\Python\Python34\lib\http\client.py", line 701, in _safe_read
http.client.IncompleteRead: IncompleteRead(0 bytes read, 4073 more expected)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\bbc.py", line 571, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\bbc.py", line 467, in _download_playlist
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\bbc.py", line 349, in _download_media_selector
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\bbc.py", line 361, in _download_media_selector_url
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\bbc.py", line 396, in _process_media_selector
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 2079, in _extract_mpd_formats
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 827, in _download_xml_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 671, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 721, in _webpage_read_content
  File "C:\Python\Python34\lib\http\client.py", line 549, in read
  File "C:\Python\Python34\lib\http\client.py", line 701, in _safe_read
http.client.IncompleteRead: IncompleteRead(0 bytes read, 4073 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 545, in extract
youtube_dl.utils.ExtractorError: A network error has occurred. (caused by IncompleteRead(0 bytes read, 4073 more expected))



VERBOSE LOG 4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'mf_cloudfront-5510-1', 'https://www.bbc.co.uk/iplayer/episode/b09p5lt7/hairy-bikers-mediterranean-adventure-series-1-3-corsica', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-94421-gb3b7523feb, ffprobe N-94421-gb3b7523feb
[debug] Proxy map: {}
[bbc.co.uk] b09p5lt7: Downloading video page
ERROR: Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)> (caused by URLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:600)'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\utils.py", line 2737, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open



VERBOSE LOG 5
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'mf_cloudfront-5510-1', 'https://www.bbc.co.uk/iplayer/episode/b09p5lt7/hairy-bikers-mediterranean-adventure-series-1-3-corsica', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-94421-gb3b7523feb, ffprobe N-94421-gb3b7523feb
[debug] Proxy map: {}
[bbc.co.uk] b09p5lt7: Downloading video page
ERROR: Unable to download webpage: '' (caused by BadStatusLine("''",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\utils.py", line 2737, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1186, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1227, in getresponse
  File "C:\Python\Python34\lib\http\client.py", line 386, in begin
  File "C:\Python\Python34\lib\http\client.py", line 356, in _read_status





```

## Description

I've been having problems downloading from BBC Iplayer for the last week or two.
All but one of the UK locations on my VPN have started giving the 502 Bad Gateway error in VERBOSE LOG 1. Videos play fine in browser though.
The only VPN location that did still work, had extremely slow download speeds usually anywhere between 5 to 200kbs a second. Unfortunately that VPN location is now not working and giving the errors in VERBOSE LOG 2 TO 5. I'm now having trouble getting videos to work in browser for this location too, they'll load a little before giving an error message.
If anyone knows what the problem here is or could give any help at all, it would be greatly appreciated.

**Comment by 89z** [comment]
website uses geo-blocking

**Comment by dirkf** [comment]
>website uses geo-blocking

Indeed it probably has a VPN bl[oa]ck-list and certainly refused my connection when I was last in a position to use a corporate (not UK-based) IP address from the UK.

>Videos play fine in browser though.

How is that connecting, then?

Here's the UK trace:
```ShellSession
$ python -m youtube_dl -v -F 'https://www.bbc.co.uk/iplayer/episode/b09p5lt7/hairy-bikers-mediterranean-adventure-series-1-3-corsica'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.bbc.co.uk/iplayer/episode/b09p5lt7/hairy-bikers-mediterranean-adventure-series-1-3-corsica']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: a631e79b3
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[bbc.co.uk] b09p5lt7: Downloading video page
[bbc.co.uk] b09p5lt7: Downloading playlist JSON
[bbc.co.uk] b09p5lsl: Downloading media selection JSON
[bbc.co.uk] b09p5lsl: Downloading m3u8 information
[bbc.co.uk] b09p5lsl: Downloading m3u8 information
[bbc.co.uk] b09p5lsl: Downloading m3u8 information
[bbc.co.uk] b09p5lsl: Downloading m3u8 information
[bbc.co.uk] b09p5lsl: Downloading m3u8 information
[bbc.co.uk] b09p5lsl: Downloading m3u8 information
[bbc.co.uk] b09p5lsl: Downloading MPD manifest
[bbc.co.uk] b09p5lsl: Downloading MPD manifest
[bbc.co.uk] b09p5lsl: Downloading MPD manifest
[bbc.co.uk] b09p5lsl: Downloading MPD manifest
[bbc.co.uk] b09p5lsl: Downloading MPD manifest
[bbc.co.uk] b09p5lsl: Downloading MPD manifest
[info] Available formats for b09p5lsl:
format code                         extension  resolution note
mf_akamai-audio_eng_1=128000-0      m4a        audio only [en] DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
mf_akamai-audio_eng_1=128000-1      m4a        audio only [en] DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
mf_bidi-audio_eng_1=128000-0        m4a        audio only [en] DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
mf_bidi-audio_eng_1=128000-1        m4a        audio only [en] DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
mf_cloudfront-audio_eng_1=128000-0  m4a        audio only [en] DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
mf_cloudfront-audio_eng_1=128000-1  m4a        audio only [en] DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
mf_akamai-video=827000-0            mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_akamai-video=827000-1            mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_bidi-video=827000-0              mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_bidi-video=827000-1              mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_cloudfront-video=827000-0        mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_cloudfront-video=827000-1        mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_akamai-video=1570000-0           mp4        704x396    DASH video 1570k , mp4_dash container, avc3.64001F, 50fps, video only
mf_akamai-video=1570000-1           mp4        704x396    DASH video 1570k , mp4_dash container, avc3.64001F, 50fps, video only
mf_bidi-video=1570000-0             mp4        704x396    DASH video 1570k , mp4_dash container, avc3.64001F, 50fps, video only
mf_bidi-video=1570000-1             mp4        704x396    DASH video 1570k , mp4_dash container, avc3.64001F, 50fps, video only
mf_cloudfront-video=1570000-0       mp4        704x396    DASH video 1570k , mp4_dash container, avc3.64001F, 50fps, video only
mf_cloudfront-video=1570000-1       mp4        704x396    DASH video 1570k , mp4_dash container, avc3.64001F, 50fps, video only
mf_akamai-video=2812000-0           mp4        960x540    DASH video 2812k , mp4_dash container, avc3.64001F, 50fps, video only
mf_akamai-video=2812000-1           mp4        960x540    DASH video 2812k , mp4_dash container, avc3.64001F, 50fps, video only
mf_bidi-video=2812000-0             mp4        960x540    DASH video 2812k , mp4_dash container, avc3.64001F, 50fps, video only
mf_bidi-video=2812000-1             mp4        960x540    DASH video 2812k , mp4_dash container, avc3.64001F, 50fps, video only
mf_cloudfront-video=2812000-0       mp4        960x540    DASH video 2812k , mp4_dash container, avc3.64001F, 50fps, video only
mf_cloudfront-video=2812000-1       mp4        960x540    DASH video 2812k , mp4_dash container, avc3.64001F, 50fps, video only
mf_akamai-video=5070000-0           mp4        1280x720   DASH video 5070k , mp4_dash container, avc3.640020, 50fps, video only
mf_akamai-video=5070000-1           mp4        1280x720   DASH video 5070k , mp4_dash container, avc3.640020, 50fps, video only
mf_bidi-video=5070000-0             mp4        1280x720   DASH video 5070k , mp4_dash container, avc3.640020, 50fps, video only
mf_bidi-video=5070000-1             mp4        1280x720   DASH video 5070k , mp4_dash container, avc3.640020, 50fps, video only
mf_cloudfront-video=5070000-0       mp4        1280x720   DASH video 5070k , mp4_dash container, avc3.640020, 50fps, video only
mf_cloudfront-video=5070000-1       mp4        1280x720   DASH video 5070k , mp4_dash container, avc3.640020, 50fps, video only
mf_akamai-1013-0                    mp4        704x396    1013k , avc1.4D401F@ 827k, 25.0fps, mp4a.40.2@128k
mf_akamai-1013-1                    mp4        704x396    1013k , avc1.4D401F@ 827k, 25.0fps, mp4a.40.2@128k
mf_bidi-1013-0                      mp4        704x396    1013k , avc1.4D401F@ 827k, 25.0fps, mp4a.40.2@128k
mf_bidi-1013-1                      mp4        704x396    1013k , avc1.4D401F@ 827k, 25.0fps, mp4a.40.2@128k
mf_cloudfront-1013-0                mp4        704x396    1013k , avc1.4D401F@ 827k, 25.0fps, mp4a.40.2@128k
mf_cloudfront-1013-1                mp4        704x396    1013k , avc1.4D401F@ 827k, 25.0fps, mp4a.40.2@128k
mf_akamai-1800-0                    mp4        704x396    1800k , avc1.64001F@1570k, 50.0fps, mp4a.40.2@128k
mf_akamai-1800-1                    mp4        704x396    1800k , avc1.64001F@1570k, 50.0fps, mp4a.40.2@128k
mf_bidi-1800-0                      mp4        704x396    1800k , avc1.64001F@1570k, 50.0fps, mp4a.40.2@128k
mf_bidi-1800-1                      mp4        704x396    1800k , avc1.64001F@1570k, 50.0fps, mp4a.40.2@128k
mf_cloudfront-1800-0                mp4        704x396    1800k , avc1.64001F@1570k, 50.0fps, mp4a.40.2@128k
mf_cloudfront-1800-1                mp4        704x396    1800k , avc1.64001F@1570k, 50.0fps, mp4a.40.2@128k
mf_akamai-3117-0                    mp4        960x540    3117k , avc1.64001F@2812k, 50.0fps, mp4a.40.2@128k
mf_akamai-3117-1                    mp4        960x540    3117k , avc1.64001F@2812k, 50.0fps, mp4a.40.2@128k
mf_bidi-3117-0                      mp4        960x540    3117k , avc1.64001F@2812k, 50.0fps, mp4a.40.2@128k
mf_bidi-3117-1                      mp4        960x540    3117k , avc1.64001F@2812k, 50.0fps, mp4a.40.2@128k
mf_cloudfront-3117-0                mp4        960x540    3117k , avc1.64001F@2812k, 50.0fps, mp4a.40.2@128k
mf_cloudfront-3117-1                mp4        960x540    3117k , avc1.64001F@2812k, 50.0fps, mp4a.40.2@128k
mf_akamai-5510-0                    mp4        1280x720   5510k , avc1.640020@5070k, 50.0fps, mp4a.40.2@128k
mf_akamai-5510-1                    mp4        1280x720   5510k , avc1.640020@5070k, 50.0fps, mp4a.40.2@128k
mf_bidi-5510-0                      mp4        1280x720   5510k , avc1.640020@5070k, 50.0fps, mp4a.40.2@128k
mf_bidi-5510-1                      mp4        1280x720   5510k , avc1.640020@5070k, 50.0fps, mp4a.40.2@128k
mf_cloudfront-5510-0                mp4        1280x720   5510k , avc1.640020@5070k, 50.0fps, mp4a.40.2@128k
mf_cloudfront-5510-1                mp4        1280x720   5510k , avc1.640020@5070k, 50.0fps, mp4a.40.2@128k (best)
$
```

**Comment by BlueHippo73** [comment]
> website uses geo-blocking

I know. I've been using a VPN to watch and download things from BBC Iplayer for months, without issue.





> > Videos play fine in browser though.
> 
> How is that connecting, then?
> 

> ```
I'm not exactly sure what you mean here. I just set my VPN to a UK location and visit BBC Iplayer in Firefox.

**Comment by 89z** [comment]
> > website uses geo-blocking
> 
> I know. I've been using a VPN to watch and download things from BBC Iplayer for months, without issue.

Comment was not for you.

**Comment by BlueHippo73** [comment]
> > > website uses geo-blocking
> > 
> > 
> > I know. I've been using a VPN to watch and download things from BBC Iplayer for months, without issue.
> 
> Comment was not for you.

Oh. Sorry.

**Comment by dirkf** [comment]
>I'm not exactly sure what you mean here. I just set my VPN to a UK location and visit BBC Iplayer in Firefox.

That's a bit weird then. Apparently something in the VPN route is screwing with your data for yt-dl but not for Firefox. Maybe HTTP/2 or such is the difference. You could try `--user-agent ...` with the UA string from your FF, but I wouldn't be confident of success.

Otherwise, maybe sign up another VPN and see if it still happens.

**Comment by BlueHippo73** [comment]
> > I'm not exactly sure what you mean here. I just set my VPN to a UK location and visit BBC Iplayer in Firefox.
> 
> That's a bit weird then. Apparently something in the VPN route is screwing with your data for yt-dl but not for Firefox. Maybe HTTP/2 or such is the difference. You could try `--user-agent ...` with the UA string from your FF, but I wouldn't be confident of success.
> 
> Otherwise, maybe sign up another VPN and see if it still happens.

Do you have any specific things in mind that I can read about user agents and how to use them in ytdl? I've tried googling and and just get overwhelmed by all the results.

**Comment by dirkf** [comment]
Read the manual; see [an example](https://github.com/ytdl-org/youtube-dl/issues/30251#issuecomment-1026177294).
