### ISSUE TITLE
youtube-dl gives me a 403 error when downloading Bilibili audio

### ISSUE THREAD

**Issue by frostnotfall** [ytdl-org/youtube-dl#30768]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
 youtube-dl --cookies "D:\Downloads\cookies.txt" $URL --rm-cache-dir -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'D:\\Downloads\\cookies.txt', 'https://www.bilibili.com/audio/au1707726', '--rm-cache-dir', '-v']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.1 (CPython) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg n4.4-15-ge87e006121, ffprobe n4.4-15-ge87e006121
[debug] Proxy map: {}
Removing cache dir C:\Users/.cache\youtube-dl ..
[BilibiliAudio] 1707726: Downloading JSON metadata
[BilibiliAudio] 1707726: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://upos-sz-mirrorcos.bilivideo.com/ugaxcode/m200712a23meb2aah2gges1opbtewjdl-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1648147982&gen=playurlv2&os=cosbv&oi=1928749355&trid=796d34743e5e479dbd325606c78804dbB&platform=pc&upsig=34452e35f091d30547bc499fa6a6f0c7&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&bvc=vod&nettype=0&orderid=0,1&logo=00000000'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "D:\Program Files\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 1976, in process_info
    success = dl(filename, info_dict)
  File "D:\Program Files\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "D:\Program Files\Python\Python310\lib\site-packages\youtube_dl\downloader\common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "D:\Program Files\Python\Python310\lib\site-packages\youtube_dl\downloader\http.py", line 351, in real_download
    establish_connection()
  File "D:\Program Files\Python\Python310\lib\site-packages\youtube_dl\downloader\http.py", line 116, in establish_connection
    raise err
  File "D:\Program Files\Python\Python310\lib\site-packages\youtube_dl\downloader\http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "D:\Program Files\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "D:\Program Files\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "D:\Program Files\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "D:\Program Files\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "D:\Program Files\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\Program Files\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

## Description

issue only for bilibili music , eg: https://www.bilibili.com/audio/au1707726, difference with normal URL but youtibe-dl supported in "https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/bilibili.py"

**Comment by dirkf** [comment]
I got 403 too.

This is the work-around (`--referer ...` option)
```
$ youtube-dl -v --test 'https://www.bilibili.com/audio/au1707726' --referer 'https://www.bilibili.com/audio/au1707726'
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--test', 'https://www.bilibili.com/audio/au1707726', '--referer', 'https://www.bilibili.com/audio/au1707726']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[BilibiliAudio] 1707726: Downloading JSON metadata
[BilibiliAudio] 1707726: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://upos-sz-mirrorcos.bilivideo.com/ugaxcode/m200712a23meb2aah2gges1opbtewjdl-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1648157961&gen=playurlv2&os=cosbv&oi=856054262&trid=1e9080a7b14943f0ba50f335e7d23550B&platform=pc&upsig=d03af7d0109b6bf6218cafcbd445d545&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&bvc=vod&nettype=0&orderid=0,1&logo=00000000'
[download] Destination: 【周杰伦 x Reol】本草纲目x烦恼游戏 Remix by 厌食同学-1707726.m4a
[download] 100% of 10.00KiB in 00:09
$
```
The extractor needs to send this automatically; PRs welcome.

**Comment by frostnotfall** [comment]
I created a related [PR](https://github.com/ytdl-org/youtube-dl/pull/30763).
