### ISSUE TITLE
Downloading of a live video from ceskatelevize.cz stopped to work

### ISSUE THREAD

**Issue by hawkinsjim** [ytdl-org/youtube-dl#30769]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
e:\PETR\FILMY\POM>youtube-dl.exe https://www.ceskatelevize.cz/porady/14890395001-spolecne-koreny-koncert-s-ukrajinou/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.ceskatelevize.cz/porady/14890395001-spolecne-koreny-koncert-s-ukrajinou/', '--verbose']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-91146-gfe84f70819-vdhcoapp, ffprobe N-91146-gfe84f70819-vdhcoapp
[debug] Proxy map: {}
[CeskaTelevizePorady] 14890395001-spolecne-koreny-koncert-s-ukrajinou: Downloading webpage
ERROR: Unable to extract iframe player url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\ceskatelevize.py", line 285, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract iframe player url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


e:\PETR\FILMY\POM>
```

## Description

WRITE DESCRIPTION HERE
Czech TV has its web. Some videos on the web are playable only in a time of broadcasting of the same program. It was possible to download these videos without problem during the broadcasting. The Czech TV changed its web and now I am not able to download it. Please, could you look at it and modify the program?
Regards
Jim

**Comment by dirkf** [comment]
The released extractor has known issues. I tried PR #30713, but it failed to extract.

The site reported "Pořad je možné přehrát pouze souběžně s televizním vysíláním" which I would add to the error text search in the PR as 'program can only be played simultaneously with TV broadcast'.

If you can find a way of playing the show in your browser, please pass on the URL used for that.

**Comment by hawkinsjim** [comment]
I am sorry but I don't know what I shall do for the issue. Does your comment mean that you are prepareing a new version?
The url is https://www.ceskatelevize.cz/porady/14890395001-spolecne-koreny-koncert-s-ukrajinou/ but the broadcast ended and the video isn't playable.

**Comment by hawkinsjim** [comment]
I found a same cases with a different videos. Urls of the videos:
27. 3. 2022 20:00 CEST (UTC + 2) https://www.ceskatelevize.cz/porady/12708168413-velka-prestrelka/
3. 4. 2022 21:40 CEST (UTC + 2) https://www.ceskatelevize.cz/porady/10237905100-rok-draka/

**Comment by hawkinsjim** [comment]
Next:
31. 3. 2022 20:15 CEST (UTC + 2) https://www.ceskatelevize.cz/porady/13194341639-zena-jde-napred/

**Comment by dirkf** [comment]
I won't be able to monitor the 27 March show but let's have a look at the 31 March one, Woman Walks Ahead.

I wonder if it's a policy to make certain foreign movies available only at the time of broadcast for rights reasons.

**Comment by hawkinsjim** [comment]
Next:
8. 4. 2022 20:00 CEST (UTC + 2) https://www.ceskatelevize.cz/porady/1050569104-neuplatni/
9. 4. 2022 23:50 CEST (UTC + 2) https://www.ceskatelevize.cz/porady/12265655393-odnikud/

**Comment by hawkinsjim** [comment]
Next:
11.04.2022 21:55 https://www.ceskatelevize.cz/porady/13561739142-parazit/
12.04.2022 20:10 https://www.ceskatelevize.cz/porady/1002370362-tankovy-prapor/

**Comment by nesnera** [comment]
I am also interested in this issue. Some archival records are time-limited for licensing reasons, and I have also encountered limitations of availability on the Czech Republic's teriotorium. However, this should not be a problem for e.g. this interview with Sir Terry Pratchett - https://www.ceskatelevize.cz/porady/1093836883-na-plovarne/211522160100014/, but better check.
