### ISSUE TITLE
Pornhd Grabber Not Working

### ISSUE THREAD

**Issue by Happybeel** [ytdl-org/youtube-dl#30776]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

/usr/bin/python3 /usr/local/bin/youtube-dl --verbose https://www.pornhd.com/videos/15597/brunette-mom-jessica-jaymes-gets-facial-jizzed-hd-porn-video?gravity=1&recId=l16mzpev-93otxreukge-S.MAIN_PAGE-115gvuo
[1] 2686257
[root@ns31447863 tmp]# [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.pornhd.com/videos/15597/brunette-mom-jessica-jaymes-gets-facial-jizzed-hd-porn-video?gravity=1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.6.8 (CPython) - Linux-4.18.0-348.7.1.el8_5.x86_64-x86_64-with-centos-8.5.2111
[debug] exe versions: ffmpeg 4.2.5, ffprobe 4.2.5
[debug] Proxy map: {}
[PornHd] brunette-mom-jessica-jaymes-gets-facial-jizzed-hd-porn-video?gravity=1: Downloading webpage
ERROR: Unable to extract error message; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/pornhd.py", line 73, in _real_extract
    webpage, 'error message', group='value')
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract error message; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[1]+  Exit 1

## Description

PornHD grabber isn't working anymore, I have the latest version.

Thank you.

**Comment by dirkf** [comment]
The page has a useful ld+json element. Use `--force-generic-extractor` as a work-around.

**Comment by barbertoclean21** [comment]
What you want me to ask for you now
