### ISSUE TITLE
NicoNico Douga is broken as of March 2022

### ISSUE THREAD

**Issue by ctrlcctrlv** [ytdl-org/youtube-dl#30790]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl --verbose https://www.nicovideo.jp/watch/sm34706723
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.nicovideo.jp/watch/sm34706723']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.7 (CPython) - Linux-5.16.11-76051611-generic-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg N-106415-gfa12d808d7, ffprobe N-106415-gfa12d808d7, rtmpdump 2.4
[debug] Proxy map: {}
[niconico] sm34706723: Downloading webpage
[niconico] sm34706723: Downloading flv info
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/fred/.local/bin/youtube-dl/youtube_dl/extractor/niconico.py", line 291, in _real_extract
    video_real_url = api_data['video']['smileInfo']['url']
KeyError: 'smileInfo'
Traceback (most recent call last):
  File "/home/fred/.local/bin/youtube-dl/youtube_dl/extractor/niconico.py", line 291, in _real_extract
    video_real_url = api_data['video']['smileInfo']['url']
KeyError: 'smileInfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fred/.local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/fred/.local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/fred/.local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/fred/.local/bin/youtube-dl/youtube_dl/extractor/niconico.py", line 310, in _real_extract
    raise ExtractorError('Unable to find video URL')
youtube_dl.utils.ExtractorError: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Ubuntu 21.04.
Link: https://www.nicovideo.jp/watch/sm34706723 (title: **【FLASH黄金時代】「例のアレ」再現してみた**)

**Comment by aipkoubou** [comment]
The NicoNicoDouga won't support HTTP streams.
2023-06-14~ ( HLS only )

https://blog.nicovideo.jp/niconews/194301.html

https://twitter.com/sigekun/status/1662055555446484993

and if you know 
3rd party Vod can use IPv6 now. 
https://www.janog.gr.jp/meeting/janog35/download_file/view/121/153/index.pdf

**Comment by ctrlcctrlv** [comment]
![image](https://github.com/ytdl-org/youtube-dl/assets/838783/f596038c-aa03-4b4c-a311-7f4d8aa2f630)

冗談でしょ、これ。
IPv6のアドレスを入力するための特別なテンキーがあるなんて、なんて愚かなじゃんね。

**Comment by dirkf** [comment]
With [this WIP](https://github.com/ytdl-org/youtube-dl/issues/33243#issuecomment-3834888792) and Py3:
```console

$ python3 -m youtube_dl -vF 'https://www.nicovideo.jp/watch/sm34706723'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vF', 'https://www.nicovideo.jp/watch/sm34706723']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 71ac16cbc
[debug] Python 3.11.2 (CPython i686 32bit) - Linux-6.1.0-40-686-pae-i686-with-glibc2.36 - OpenSSL 3.0.18 30 Sep 2025 - glibc 2.36
[debug] exe versions: ffmpeg 5.1.8-0, ffprobe 5.1.8-0
[debug] Proxy map: {}
[niconico] Extracting URL: https://www.nicovideo.jp/watch/sm34706723
[niconico] sm34706723: Downloading API JSON
[niconico] sm34706723: Downloading JSON metadata
[niconico] sm34706723: Downloading m3u8 information
[info] Available formats for sm34706723:
format code             extension  resolution note
audio-aac-128kbps       mp4        audio only Main Audio , aac  @138k (44100Hz)
audio-aac-64kbps        mp4        audio only Main Audio , aac  @ 99k (44100Hz)
video-h264-360p-lowest  mp4        480x360     300k , avc1.42c01e, 30.0fps, video only
video-h264-360p         mp4        480x360     594k , avc1.4d401e, 30.0fps, video only
video-h264-480p         mp4        640x480    1974k , avc1.4d4020, 60.0fps, video only
video-h264-720p         mp4        960x720    2013k , avc1.4d4020, 60.0fps, video only (best)
$
```
