### ISSUE TITLE
Cannot download video from Facebook (Live)

### ISSUE THREAD

**Issue by nanaditza** [ytdl-org/youtube-dl#30803]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```ShellSession
aa@tcm73:~$ youtube-dl "https://www.facebook.com/watch/live/?ref=watch_permalink&v=279718980981125" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.facebook.com/watch/live/?ref=watch_permalink&v=279718980981125', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.6.9 (CPython) - Linux-5.3.0-62-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: avconv 3.4.6, ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[facebook] 279718980981125: Downloading webpage
[facebook] 279718980981125: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 680, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 594, in _extract_from_url
    raise ExtractorError('Cannot parse data')
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description
WRITE DESCRIPTION HERE
Cannot download the video from Facebook. The video plays well in the browser. 
Thanks.

**Comment by 89z** [comment]
> This content isn't available right now
