### ISSUE TITLE
TVer.jp broken 

### ISSUE THREAD

**Issue by 04cabbies** [ytdl-org/youtube-dl#30812]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl https://tver.jp/episodes/epwkkm1yzt
[generic] epwkkm1yzt: Requesting header
WARNING: Falling back on generic information extractor.
[generic] epwkkm1yzt: Downloading webpage
[generic] epwkkm1yzt: Extracting information
ERROR: Unsupported URL: https://tver.jp/episodes/epwkkm1yzt
elwoodchu@M1-Mac-mini video % 
elwoodchu@M1-Mac-mini video % 
elwoodchu@M1-Mac-mini video % youtube-dl -v https://tver.jp/episodes/epwkkm1yzt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://tver.jp/episodes/epwkkm1yzt']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 5f5af4324
[debug] Python version 3.10.2 (CPython) - macOS-12.3.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.0, ffprobe 5.0, rtmpdump 2.4
[debug] Proxy map: {}
[generic] epwkkm1yzt: Requesting header
WARNING: Falling back on generic information extractor.
[generic] epwkkm1yzt: Downloading webpage
[generic] epwkkm1yzt: Extracting information
ERROR: Unsupported URL: https://tver.jp/episodes/epwkkm1yzt
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/generic.py", line 3489, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://tver.jp/episodes/epwkkm1yzt
```

## Description

After TVer.jp is revamped on 1 Apr 2022, the TVer plugin can no longer work as described.

**Comment by dirkf** [comment]
> - [x] I've searched the bugtracker for similar issues including closed ones

Apparently not, or you would have found #30798.
