### ISSUE TITLE
Youtube-dl unexpected behaviour on some youtube videos, seemingly randomly freezing or not downloading

### ISSUE THREAD

**Issue by GhostDog98** [ytdl-org/youtube-dl#30832]
## Checklist

- [] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v "wDgQdr8ZkTw"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'wDgQdr8ZkTw']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.2 (CPython) - macOS-11.2-x86_64-i386-64bit
[debug] exe versions: ffmpeg 5.0.1, ffprobe 5.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] wDgQdr8ZkTw: Downloading webpage
[youtube] wDgQdr8ZkTw: Downloading player 3b5d5649
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://rr2---sn-uxanug5-hxaes.googlevideo.com/videoplayback?expire=1649403330&ei=YpFPYvCCHfHCpgeS5YOQBQ&ip=2001%3A8004%3A4490%3A45f7%3A25c0%3Ae6d%3A9b6e%3A61f9&id=o-ALfxKUwhnF6Ih50c24DpYGDXySmgRzr54Fi5CWuRX0rL&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=3t&mm=31%2C29&mn=sn-uxanug5-hxaes%2Csn-hxa76n7s&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=44&initcwndbps=1448750&spc=4ocVC7hVVILSGgJA_C87miVUbNhj&vprv=1&mime=video%2Fwebm&ns=2jP4NU4hoBbk813GNG3AkA0G&gir=yes&clen=1828087&dur=313.133&lmt=1648681318986957&mt=1649381578&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=4535434&n=IfeWO0ny-qCjf4693m&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgX3YMafEonnLtfu6OQwnsPzlw1_zJJLhnMqk8VsQWHcMCICTYLuOgqRCzs9FQGHlDF1CVBS283qdxzd043fRGG5Cy&sig=AOq0QJ8wRQIhAO8tkzJex5W1hV9F2LvA7XGxSj4iDIKl4oYx6_J2EusKAiA3Zgme5CFQhoXkYrNzRbiDPz8V2FgbALV7L23Q0neJ9w=='
ERROR: unable to download video data: Remote end closed connection without response
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 1970, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/utils.py", line 2735, in https_open
    return self.do_open(functools.partial(
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

## Description

Hi, I'm having a problem with some videos refusing to download, despite the fact that they will download when retried, for example, after the above log, I tried the same command with the output of:
```
$ youtube-dl -v "wDgQdr8ZkTw"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'wDgQdr8ZkTw']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.2 (CPython) - macOS-11.2-x86_64-i386-64bit
[debug] exe versions: ffmpeg 5.0.1, ffprobe 5.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] wDgQdr8ZkTw: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://rr2---sn-uxanug5-hxaes.googlevideo.com/videoplayback?expire=1649403451&ei=25FPYq7DD6Dz4-EP_4yL6Ak&ip=2001%3A8004%3A4490%3A45f7%3A25c0%3Ae6d%3A9b6e%3A61f9&id=o-AOR2VrSma6WmpQZDBN_0NHYB7ut5LlfB2XZ4JuWp8Xn3&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=3t&mm=31%2C29&mn=sn-uxanug5-hxaes%2Csn-hxa7zn7s&ms=au%2Crdu&mv=m&mvi=2&pl=44&initcwndbps=1448750&spc=4ocVC5vwe1NnROL7CHMKi0RM5j2F&vprv=1&mime=video%2Fwebm&ns=F4b7hYX2ErZ6TepXPFikpPYG&gir=yes&clen=1828087&dur=313.133&lmt=1648681318986957&mt=1649381578&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=4535434&n=JTisPn8yofqvkqaukb&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgRpbgxiZJIrWgktm2jQV-qnGUa2VZ8tHlwWmmIQ0V4Q4CIEwkfM7LpdPunGF5Mh_Sn-u4JDmGWxBhhsclkqIb0AmB&sig=AOq0QJ8wRQIhAOCJlZWZVtJPh_TxkKZUv34ihqOpBtdUV7tnqSIiuDnIAiAj2kU_OhIXbtRmvc6D1r6Nid65Go4dhv-YhSXJ9UppXA=='
[download] Destination: Undertale - Megalovania-wDgQdr8ZkTw.f248.webm
[download]   1.7% of 1.74MiB at 62.03KiB/s ETA 00:28^C
ERROR: Interrupted by user
```
This remained stuck at 1.7% for about 1 minute with the same download speed and eta until I quit using CTRL+C. 
I'm unsure why this happened, as I did not change networks. The very next try however (of the same video), it failed, with the exact same output log, and I'm not sure why? I repeated this about five times with the exact same output...

This initially seems similar to issues #30189 and #17533, however it "works" partway sometimes.

**Comment by 89z** [comment]
Cannot repro:

~~~
PS C:\> youtube-dl wDgQdr8ZkTw
[youtube] wDgQdr8ZkTw: Downloading webpage
[youtube] wDgQdr8ZkTw: Downloading player 3b5d5649
[download] Destination: Undertale - Megalovania-wDgQdr8ZkTw.f248.webm
[download] 100% of 1.74MiB in 00:00
[download] Destination: Undertale - Megalovania-wDgQdr8ZkTw.f251.webm
[download] 100% of 5.15MiB in 00:00
~~~

**Comment by GhostDog98** [comment]
That's strange, I wonder why that's happening, the same version of python?

**Comment by 89z** [comment]
3.10.4 here - out of 9 tries, how many fail for you?

**Comment by GhostDog98** [comment]
I tried 20 times, every one failed, same error for each one.

**Comment by 89z** [comment]
I tried 9 times, everyone one was successful

**Comment by GhostDog98** [comment]
Strange.... Don't think there's much we can do though if anyone has ideas let me know, but for now might as well close the issue and avoid wasting anyone's time, sorry about that.
