### ISSUE TITLE
youtube shorts fail to download

### ISSUE THREAD

**Issue by chaseunc0** [ytdl-org/youtube-dl#30834]
works fine with regular videos, but it fails with shorts

OUTPUT:

youtube-dl --verbose https://youtube.com/shorts/npiLJLEpPhE
[debug] System config: []                               [debug] User config: []                                 [debug] Custom config: []                               [debug] Command-line args: ['--verbose', 'https://youtube.com/shorts/npiLJLEpPhE']                              [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8                                                [debug] youtube-dl version 2021.12.17                   [debug] Python version 3.10.4 (CPython) - Linux-4.19.220-g71dc7826df87-aarch64-with-libc                        [debug] exe versions: ffmpeg 5.0, ffprobe 5.0           [debug] Proxy map: {}                                   [youtube:tab] shorts: Downloading webpage               ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.               Traceback (most recent call last):                        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)                    File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 2862, in _real_extract
    raise ExtractorError('Unable to recognize tab page')
youtube_dl.utils.ExtractorError: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by 89z** [comment]
Thank you for being the first person to post this issue. Man, I wish this tracker had some way to search the issues.

**Comment by dirkf** [comment]
Duplicate of #30269; fixed in git master.

If you had used one of the relevant issue templates you would have been prompted thus:

>- [ ] I've searched the bugtracker for similar bug reports including closed ones

The search that you would have carried out would have revealed the original issue.
