### ISSUE TITLE
nick.com and paramountplus.com doesn't work anymore

### ISSUE THREAD

**Issue by Taylor7812** [ytdl-org/youtube-dl#30848]
I'm reporting a broken site support
My youtube-dl --version is 2021.12.17
They urls are working in the browser
i tried with ' and " and other arguments but it doesn't work.
i didn't found a post with the same issue so that's why i post it.

Output 1: (nick.com)
youtube-dl -v https://www.nick.com/episodes/cbum0f/the-loud-house-the-boss-maybe-family-bonding-season-5-ep-2
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.nick.com/episodes/cbum0f/the-loud-house-the-boss-maybe-family-bonding-season-5-ep-2']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 5.0-essentials_build-www.gyan.dev, ffprobe 5.0-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[generic] the-loud-house-the-boss-maybe-family-bonding-season-5-ep-2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-loud-house-the-boss-maybe-family-bonding-season-5-ep-2: Downloading webpage
[generic] the-loud-house-the-boss-maybe-family-bonding-season-5-ep-2: Extracting information
ERROR: Unsupported URL: https://www.nick.com/episodes/cbum0f/the-loud-house-the-boss-maybe-family-bonding-season-5-ep-2
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\generic.py", line 3489, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.nick.com/episodes/cbum0f/the-loud-house-the-boss-maybe-family-bonding-season-5-ep-2

Output 2: (paramountplus.com)
youtube-dl -v "https://www.paramountplus.com/shows/video/pa7hNJyhGqjW35UIALIsYVypeBc1G2oH"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.paramountplus.com/shows/video/pa7hNJyhGqjW35UIALIsYVypeBc1G2oH']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 5.0-essentials_build-www.gyan.dev, ffprobe 5.0-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[generic] pa7hNJyhGqjW35UIALIsYVypeBc1G2oH: Requesting header
[redirect] Following redirect to https://www.paramountplus.com/shows/video/pa7hNJyhGqjW35UIALIsYVypeBc1G2oH/
[generic] pa7hNJyhGqjW35UIALIsYVypeBc1G2oH: Requesting header
WARNING: Falling back on generic information extractor.
[generic] pa7hNJyhGqjW35UIALIsYVypeBc1G2oH: Downloading webpage
[generic] pa7hNJyhGqjW35UIALIsYVypeBc1G2oH: Extracting information
ERROR: Unsupported URL: https://www.paramountplus.com/shows/video/pa7hNJyhGqjW35UIALIsYVypeBc1G2oH/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\generic.py", line 3489, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.paramountplus.com/shows/video/pa7hNJyhGqjW35UIALIsYVypeBc1G2oH/

If i want to download something from nick.com and paramountplus.com it just shows me unsupported URL.

**Comment by dirkf** [comment]
Regarding Paramount+, try adding a component after `.../shows/` (doesn't matter what): https://www.paramountplus.com/shows/x/video/pa7hNJyhGqjW35UIALIsYVypeBc1G2oH/

However you may also have to install PR #30085.

**Comment by dirkf** [comment]
The Nick extractor is obsolete. You could try yt-dlp. Let us know if it works as I can merge in the changes from that version.

**Comment by october262** [comment]
can confirm nick.com does work with yt-dlp
