### ISSUE TITLE
[Instagram] Unable to extract video url

### ISSUE THREAD

**Issue by AtomicNess123** [ytdl-org/youtube-dl#30851]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```ShellSession
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.instagram.com/p/Ca9rQElKKIt/', '--cookies', '/pat-to-my-cookies-file/instagram.com_cookies.txt']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.7.6 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[Instagram] Ca9rQElKKIt: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/user/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/user/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/user/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/Users/user/.local/lib/python3.7/site-packages/youtube_dl/extractor/instagram.py", line 240, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/Users/user/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1130, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/Users/user/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/Users/user/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Can't seem to download instagram videos even after updating and using the cookies file.
Do not understand the error output.

**Comment by dirkf** [comment]
Duplicate of #28021 (admittedly rather old, but the extractor hasn't been changed significantly).

Also, WFM, though Insta is prone to allow access initially and then demand a login:
```ShellSession
$ youtube-dl -v -F 'https://www.instagram.com/p/Ca9rQElKKIt/'
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.instagram.com/p/Ca9rQElKKIt/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[Instagram] Ca9rQElKKIt: Downloading webpage
[info] Available formats for Ca9rQElKKIt:
format code  extension  resolution note
0            mp4        640x1137   
$
```

**Comment by 89z** [comment]
If you try it four times, it will fail:

~~~
PS D:\Desktop> youtube-dl -F https://www.instagram.com/p/Ca9rQElKKIt/
[Instagram] Ca9rQElKKIt: Downloading webpage
[info] Available formats for Ca9rQElKKIt:
format code  extension  resolution note
0            mp4        640x1137

PS D:\Desktop> youtube-dl -F https://www.instagram.com/p/Ca9rQElKKIt/
[Instagram] Ca9rQElKKIt: Downloading webpage
[info] Available formats for Ca9rQElKKIt:
format code  extension  resolution note
0            mp4        640x1137

PS D:\Desktop> youtube-dl -F https://www.instagram.com/p/Ca9rQElKKIt/
[Instagram] Ca9rQElKKIt: Downloading webpage
[info] Available formats for Ca9rQElKKIt:
format code  extension  resolution note
0            mp4        640x1137

PS D:\Desktop> youtube-dl -F https://www.instagram.com/p/Ca9rQElKKIt/
[Instagram] Ca9rQElKKIt: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
~~~

**Comment by dirkf** [comment]
Join the club, I think. Once you've had however many accesses (in some period TBD), Instagram wants you to log in. In theory logging in in your browser, exporting a cookie file and using that with `--cookies ...` should restore access, but possibly the site sends a different page for logged-in users that the extractor can't grok

**Comment by 89z** [comment]
> possibly the site sends a different page for logged-in users that the extractor can't grok

I haven't messed with my Instagram extractor in a few weeks, but yes this was the case. Instagram has been return different JSON from the exact same request, depending on if your logged in or not. This is a ridiculous practice, and the only site Ive ever seen do this. Regardless, it appears to be the current state of the site. So you need different code for anonymous and authenticated requests.


> possibly the cookie(s) expire too quickly to be useful, or are tied to the browser through its `User-agent` string or otherwise.

I use `/api/v1/accounts/login/` to login, but yes, Instagram does also seem to require an elaborate [1] User-Agent with authenticated requests. Again an awful design choice, as User-Agent strings don't have any define structure, only common uses.

1. https://github.com/89z/mech/blob/v1.51.4/instagram/version.go#L86-L133

**Comment by AtomicNess123** [comment]
Yes, I have generated the cookie file every time but wouldn't let me. Also logged out and in, generated it, and nothing. I guess I'll try tomorrow again. Thanks to all for your feedbacks.

**Comment by 89z** [comment]
> possibly the site sends a different page for logged-in users that the extractor can't grok

I haven't messed with my Instagram extractor in a few weeks, but yes this was the case. Instagram has been return different JSON from the exact same request, depending on if you're logged in or not. This is a ridiculous practice, and the only site Ive ever seen do this. Regardless, it appears to be the current state of the site. So you need different code for anonymous and authenticated requests.


> possibly the cookie(s) expire too quickly to be useful, or are tied to the browser through its `User-agent` string or otherwise.

I use `/api/v1/accounts/login/` to login, but yes, Instagram does also seem to require an elaborate [1] User-Agent with authenticated requests. Again an awful design choice, as User-Agent strings don't have any define structure, only common uses.

1. https://github.com/89z/mech/blob/v1.51.4/instagram/version.go#L86-L133

**Comment by 89z** [comment]
asdfasdf

**Comment by dirkf** [comment]
So just `Mozilla/5.0` doesn't work?

**Comment by 89z** [comment]
The current one I'm using looks like this:

~~~
Instagram 222.0.0.15.114 Android (99/9; density; 9999x9999; brand; model; device; platform
~~~

I think other ones are accepted as well, but what will happen is the response will be different. For example, you might get `200 OK`, and you might get a JSON response that looks good, but it will be different. For example, the best quality media is usually under `video_dash_manifest`, but that key will be missing if you use the wrong User-Agent. So maybe only lower quality media will be returned.
