### ISSUE TITLE
ThisVid Support Broken

### ISSUE THREAD

**Issue by nutsinu** [ytdl-org/youtube-dl#30867]
## Checklist

- [ ] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v "https://thisvid.com/videos/gacha-emeto-drunk-mom-spewing-taco-bell/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://thisvid.com/videos/gacha-emeto-drunk-mom-spewing-taco-bell/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.7.9 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 3.4, ffprobe N-91565-g1940c27c82
[debug] Proxy map: {}
[generic] gacha-emeto-drunk-mom-spewing-taco-bell: Requesting header
WARNING: Falling back on generic information extractor.
[generic] gacha-emeto-drunk-mom-spewing-taco-bell: Downloading webpage
[generic] gacha-emeto-drunk-mom-spewing-taco-bell: Extracting information
[download] Downloading playlist: None
[generic] playlist None: Collected 4 video ids (downloading 4 of them)
[download] Downloading video 1 of 4
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://thisvid.com/members/%ID%/'
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 1976, in process_info
    success = dl(filename, info_dict)
  File "C:\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "C:\Python37\lib\site-packages\youtube_dl\downloader\common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "C:\Python37\lib\site-packages\youtube_dl\downloader\http.py", line 351, in real_download
    establish_connection()
  File "C:\Python37\lib\site-packages\youtube_dl\downloader\http.py", line 116, in establish_connection
    raise err
  File "C:\Python37\lib\site-packages\youtube_dl\downloader\http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "C:\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

```

## Description

ThisVid support seems broken. I can't download anything and I get an HTTP 400 error.

**Comment by nutsinu** [comment]
The extractor in this [commit](https://github.com/ytdl-org/youtube-dl/pull/29187/commits/47b5b5586f606ed7f23ee7a98d04ae85936fe34e) from June, 2021 still works fine,
but it is missing from youtube-dl version 2021.12.17. Maybe it was removed for some legal issue?

**Comment by dirkf** [comment]
No, the PR was never merged because the maintainers took a break around that time.

**Comment by FraFraFra-LongD** [comment]
> No, the PR #29187 was never merged because the maintainers took a break around that time. Without that PR, the site is not specially supported and the generic extractor fails to find the video.

yes, the generic extractor doesn't work. with #29187 YouTube-dl could support not only public videos, but private videos providing cookies as well

**Comment by afterdelight** [comment]
@dirkf the maintainer is now back. can you review the code again?
