### ISSUE TITLE
ERROR: An extractor error has occurred. (caused by KeyError('asset',)) // Sportdeutschland.tv 

### ISSUE THREAD

**Issue by kkuez** [ytdl-org/youtube-dl#30866]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

PASTE VERBOSE LOG HERE
```
PS C:\Windows\system32> youtube-dl "https://sportdeutschland.tv/handball-bundesliga-frauen/hbf-sg-bbm-bietigheim-vs-buxtehuder-sv-1" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://sportdeutschland.tv/handball-bundesliga-frauen/hbf-sg-bbm-bietigheim-vs-buxtehuder-sv-1', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev, ffprobe 4.4.1-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[SportDeutschland] handball-bundesliga-frauen/hbf-sg-bbm-bietigheim-vs-buxtehuder-sv-1: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('asset',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\sportdeutschland.py", line 53, in _real_extract
KeyError: 'asset'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\sportdeutschland.py", line 53, in _real_extract
KeyError: 'asset'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 547, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('asset',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

URL 
https://sportdeutschland.tv/handball-bundesliga-frauen/hbf-sg-bbm-bietigheim-vs-buxtehuder-sv-1

- Installed youtube-dl via chocolately today
- Windows

**Comment by dirkf** [comment]
The fix for #30348 finds the video:
```ShellSession
$ python -m youtube_dl -v -F 'https://sportdeutschland.tv/handball-bundesliga-frauen/hbf-sg-bbm-bietigheim-vs-buxtehuder-sv-1'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://sportdeutschland.tv/handball-bundesliga-frauen/hbf-sg-bbm-bietigheim-vs-buxtehuder-sv-1']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 675e4ca6d
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[SportDeutschland] handball-bundesliga-frauen/hbf-sg-bbm-bietigheim-vs-buxtehuder-sv-1: Downloading JSON metadata
[SportDeutschland] 9454a4b2-1f95-49fd-8152-cf9f6eb72478: Downloading SMIL file
[SportDeutschland] 9454a4b2-1f95-49fd-8152-cf9f6eb72478: Downloading m3u8 information
[info] Available formats for 9454a4b2-1f95-49fd-8152-cf9f6eb72478:
format code  extension  resolution note
hls-1        mp4        unknown    avc1.4d401f, 50.0fps, mp4a.40.2
```
The modified extractor is available from this user's fork: https://github.com/FriedrichRehren/youtube-dl/raw/aa0b30825bdba36b3337255b534bfbe6efea9092/youtube_dl/extractor/sportdeutschland.py.

If Chocolatey installed yt-dl as a Python module, you can find the `youtube_dl/extractor/sportdeutschland.py` file and replace it. Otherwise (if yt-dl is a single ~2MB executable) uninstall yt-dl, install Python and use _pip_ to install yt-dl as a module.
