### ISSUE TITLE
No video formats found: vodafone.hu MPD file

### ISSUE THREAD

**Issue by vbela0** [ytdl-org/youtube-dl#30886]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
D:\Movies\_temp>youtube-dl "https://vtvmag1es3.vodafone.hu/vtvrrscs1.vodafone.hu/LIVE/4014/sfmt=sdash/2.mpd?start=2022-04-22T09:32:00Z&end=2022-04-22T10:35:00Z&device=DASH_STB_NGRSSP_LIVE_HD_ONLY&from=4&validdev=258,254&hms_devid=254,258&pbf=2_5_1_2546239560" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vtvmag1es3.vodafone.hu/vtvrrscs1.vodafone.hu/LIVE/4014/sfmt=sdash/2.mpd?start=2022-04-22T09:32:00Z&end=2022-04-22T10:35:00Z&device=DASH_STB_NGRSSP_LIVE_HD_ONLY&from=4&validdev=258,254&hms_devid=254,258&pbf=2_5_1_2546239560', '--verbose']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
[generic] 2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2: Downloading webpage
[generic] 2: Extracting information
WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\generic.py", line 2499, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

youtube dl gives a video format not found error when using with a url which points to an mpd file. I attach the mpd file. The mpd file link is taken from the main website (tv.vodafone.hu) while starting a video playback. By looking in the MPD file  there are multiple video streams defined.

In addition there is a warning about an unknown mime type. (application/mp4). By looking in the MPD file it seems that it is a subtitle stream.

[2.zip](https://github.com/ytdl-org/youtube-dl/files/8543083/2.zip)

**Comment by 89z** [comment]
DRM:

~~~xml
<?xml version="1.0" encoding="utf-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-live:2011" xmlns:cenc="urn:mpeg:cenc:2013" xmlns:mspr="urn:microsoft:playready" availabilityStartTime="1970-01-01T00:00:00Z" type="static" minBufferTime="PT2.005S" mediaPresentationDuration="PT3782.000S" xmlns:huaweijitx="urn:huawei:jitx" >
  <huaweijitx:metainfo value="eyJkcm1NZXRhSW5mbyI6IFt7ImRybUNvbnRlbnRpZCI6ICI0MDE0IiwiZGlzdHJpYnV0aW9uTW9kZSI6ICJMSVZFIiwiZHJtTGlzdCI6IFtdfV19"/>
  <Period id="0" start="PT0.000S" >
    <AdaptationSet segmentAlignment="true" contentType="video" maxWidth="1920" maxHeight="1080" maxFrameRate="50/1" >
      <Representation id="video_4" bandwidth="7634856" codecs="avc1.640029" priAvgBw="3995290" mimeType="video/mp4" width="1280" height="720" frameRate="25/1" sar="1:1" >
      <ContentProtection value="cenc" schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="a966f74d-7ca1-405b-863c-065411bde447" />
        <ContentProtection value="MSPR 2.0" schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95"><mspr:pro xmlns:mspr="urn:microsoft:playready">oAMAAAEAAQCWAzwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADAALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsARQBZAEwARQBOAD4AMQA2ADwALwBLAEUAWQBMAEUATgA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEAD4AVABmAGQAbQBxAGEARgA4AFcAMABDAEcAUABBAFoAVQBFAGIAMwBrAFIAdwA9AD0APAAvAEsASQBEAD4APABDAEgARQBDAEsAUwBVAE0APgBRAEUAaABLAFYANABNAG4AMQBsAGcAPQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APABMAEEAXwBVAFIATAA+AGgAdAB0AHAAcwA6AC8ALwB2AGQAaAA5ADkAcwA2AHMALgBhAG4AeQBjAGEAcwB0AC4AbgBhAGcAcgBhAC4AYwBvAG0ALwBWAEQASAA5ADkAUwA2AFMALwBwAHIAbABzAC8AYwBvAG4AdABlAG4AdABsAGkAYwBlAG4AcwBlAHMAZQByAHYAaQBjAGUALwB2ADEALwBsAGkAYwBlAG4AcwBlAHMAPAAvAEwAQQBfAFUAUgBMAD4APABDAFUAUwBUAE8ATQBBAFQAVABSAEkAQgBVAFQARQBTAD4APABuAHYAOgBDAG8AbgB0AGUAbgB0AEkAZAAgAHgAbQBsAG4AcwA6AG4AdgA9ACIAdQByAG4AOgBzAGMAaABlAG0AYQAtAHMAcwBwAC0AbgBhAGcAcgBhAC0AYwBvAG0AIgA+ADQAMAAxADQAPAAvAG4AdgA6AEMAbwBuAHQAZQBuAHQASQBkAD4APAAvAEMAVQBTAFQATwBNAEEAVABUAFIASQBCAFUAVABFAFMAPgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</mspr:pro><cenc:pssh  xmlns:cenc="urn:mpeg:cenc:2013">AAADwHBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAA6CgAwAAAQABAJYDPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgBUAGYAZABtAHEAYQBGADgAVwAwAEMARwBQAEEAWgBVAEUAYgAzAGsAUgB3AD0APQA8AC8ASwBJAEQAPgA8AEMASABFAEMASwBTAFUATQA+AFEARQBoAEsAVgA0AE0AbgAxAGwAZwA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcABzADoALwAvAHYAZABoADkAOQBzADYAcwAuAGEAbgB5AGMAYQBzAHQALgBuAGEAZwByAGEALgBjAG8AbQAvAFYARABIADkAOQBTADYAUwAvAHAAcgBsAHMALwBjAG8AbgB0AGUAbgB0AGwAaQBjAGUAbgBzAGUAcwBlAHIAdgBpAGMAZQAvAHYAMQAvAGwAaQBjAGUAbgBzAGUAcwA8AC8ATABBAF8AVQBSAEwAPgA8AEMAVQBTAFQATwBNAEEAVABUAFIASQBCAFUAVABFAFMAPgA8AG4AdgA6AEMAbwBuAHQAZQBuAHQASQBkACAAeABtAGwAbgBzADoAbgB2AD0AIgB1AHIAbgA6AHMAYwBoAGUAbQBhAC0AcwBzAHAALQBuAGEAZwByAGEALQBjAG8AbQAiAD4ANAAwADEANAA8AC8AbgB2ADoAQwBvAG4AdABlAG4AdABJAGQAPgA8AC8AQwBVAFMAVABPAE0AQQBUAFQAUgBJAEIAVQBUAEUAUwA+ADwALwBEAEEAVABBAD4APAAvAFcAUgBNAEgARQBBAEQARQBSAD4A</cenc:pssh></ContentProtection>
        <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"><cenc:pssh xmlns:cenc="urn:mpeg:cenc:2013">AAAAOnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABoIARIQqWb3TXyhQFuGPAZUEb3kRyIENDAxNA==</cenc:pssh></ContentProtection>
        <ContentProtection schemeIdUri="urn:uuid:adb41c24-2dbf-4a6d-958b-4457c0d27b95" xmlns:prm="urn:nagra:prm:1-0:services:schemas:mpd"><prm:PRM><prm:PRMSignalization>eyJjb250ZW50SWQiOiI0MDE0Iiwia2V5SWQiOiJhOTY2Zjc0ZC03Y2ExLTQwNWItODYzYy0wNjU0MTFiZGU0NDcifQ</prm:PRMSignalization></prm:PRM><cenc:pssh>AAAAenBzc2gAAAAArbQcJC2/Sm2Vi0RXwNJ7lQAAAFpleUpqYjI1MFpXNTBTV1FpT2lJME1ERTBJaXdpYTJWNVNXUWlPaUpoT1RZMlpqYzBaQzAzWTJFeExUUXdOV0l0T0RZell5MHdOalUwTVRGaVpHVTBORGNpZlE=</cenc:pssh></ContentProtection>
~~~

**Comment by 89z** [comment]
actually, I think I have a way to get this. Do you have a shorter video though?

**Comment by dirkf** [comment]
The streams (`<AdaptationSet>`s) that aren't the subtitle stream say 
```
      <ContentProtection value="cenc" schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="a966f74d-7ca1-405b-863c-065411bde447" />
```
So DRM.

**Comment by 89z** [comment]
@dirkf I have been researching this some more, and I think some of these are downloadable. First you get the Widevine [1] PSSH:

~~~xml
<ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
   <cenc:pssh>
   AAAAOnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABoIARIQqWb3TXyhQFuGPAZUEb3kRyIENDAxNA==
   </cenc:pssh>
</ContentProtection>
~~~

Then you need the License URL. Sometimes the URL is in the manifest, but in this case it seems not. So I think someone just giving a MPD URL is not always going to be enough to solve it, even if someone is motivated to do so.

1. <https://dashif.org/identifiers/content_protection>

**Comment by dirkf** [comment]
There is no functionality in yt-dl for decrypting WideVine or other DRM schemes. Anyone should feel free to implement a decryption module but yt-dl wouldn't be distributing it under current conditions.

If a site obfuscates a link or a download and sends the code that reverses the obfuscation, yt-dl can reasonably use it or the underlying algorithm.

**Comment by 89z** [comment]
> There is no functionality in yt-dl for decrypting WideVine or other DRM schemes. Anyone should feel free to implement a decryption module but yt-dl wouldn't be distributing it under current conditions.

This is already possible with tools like `mp4decrypt` [1]. The tool just needs the key or keys to decrypt. So essentially YouTube-DL just needs something like `--allow-unplayable-formats`, in order to download the media, then post processing can decrypt. But if a user is going to pass a bare MPD, we might need another switch as well for License URL.

1. https://bento4.com/downloads

**Comment by 89z** [comment]
@vbela0 can you provide the source page for this MPD?

**Comment by vbela0** [comment]
I attach 2 files (zipped):
- https-107397028.zip : html source of page (https://tv.vodafone.hu/#!/search/programmeinfo/program/107397028) from developer console
- tv.vodafone.hu.har: network log from when I press "play video" on the page until the first few seconds played
[https-107397028..zip](https://github.com/ytdl-org/youtube-dl/files/8547376/https-107397028.zip)
[tv.vodafone.hu.har.zip](https://github.com/ytdl-org/youtube-dl/files/8547377/tv.vodafone.hu.har.zip)

hope it helps..

**Comment by 89z** [comment]
Does the web client not work?

> An unmissable TV experience anywhere, anytime!
> Get to know the Vodafone TV app
>
> Log in, discover the Vodafone TV app! If you get stuck, after logging in and selecting your main profile, select the Help and Information menu under the gear icon.

Sorry but I only speak English, so I need some help with this. I am able to decrypt Widevine in some cases, but I do not know Hungarian.

**Comment by vbela0** [comment]
Not sure if i get the question right, Do you mean a PC browser client? It works, I used it (MS Edge) to save the network log. (However it lags most of the time and impossible to watch a movie without tiny interruptions in the playback every two seconds. So I though to download tv programs and watch them offline later)
The site requires a login as it is a complimentary service for cable TV subscribers, this is the reason I attached a network log as well in the belief it helps to look at the network traffic.

**Comment by 89z** [comment]
Sorry, Widevine is extremely difficult to deal with already. Adding a non English website, and a login requirement, is a bridge too far for me. Good luck to you.

**Comment by vbela0** [comment]
no issues. thanks anyway

**Comment by 89z** [comment]
If you want to try it yourself, I have the process here:

https://github.com/89z/mech/blob/741d1067/research/cda.pl

its for another site, but the steps should be similar.
