### ISSUE TITLE
TikTok (tiktok.com) broken

### ISSUE THREAD

**Issue by apogay37** [ytdl-org/youtube-dl#30893]
## Verbose log

```
>youtube-dl https://www.tiktok.com/@surveyorjono/video/7060687520815762689 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.tiktok.com/@surveyorjono/video/7060687520815762689', '--verbose']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.1 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1-2021-01-01-full_build-www.gyan.dev, ffprobe 4.3.1-2021-01-01-full_build-www.gyan.dev
[debug] Proxy map: {}
[TikTok] Setting up session
ERROR: Unable to download webpage: The read operation timed out (caused by timeout('The read operation timed out'))
```

## Description

TikTok is not working. Probably for long time.
I found yotube-dl's fork and it works fine there https://github.com/yt-dlp/yt-dlp
I guess it is possible to move changes from yt-dlp to yotube-dl.
Can someone look into it?

**Comment by dirkf** [comment]
PR #30479, but it has never been found to work reliably.

The immediate problem is that TT's CDN blocks by user agent. Overcoming that, it fails later possibly in a way that the PR would fix:
```ShellSession
$ python -m youtube_dl 'https://www.tiktok.com/@surveyorjono/video/7060687520815762689' --verbose -F --user-agent 'Mozilla/5.0'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.tiktok.com/@surveyorjono/video/7060687520815762689', u'--verbose', u'-F', u'--user-agent', u'Mozilla/5.0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: c555e5e47
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[TikTok] Setting up session
[TikTok] 7060687520815762689: Downloading webpage
ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "youtube_dl/extractor/tiktok.py", line 112, in _real_extract
    webpage, 'data'), video_id)['props']['pageProps']
  File "youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$
```

**Comment by dirkf** [comment]
>... it fails later, possibly in a way that the PR would fix:

Well, no, but after some more tweaks (not yet posted to the PR), yes.

The hydration JSON can now also be in the `<script>` element with id `SIGI_STATE`.
```ShellSession
$ python -m youtube_dl -v -F --ignore-config 'https://www.tiktok.com/@surveyorjono/video/7060687520815762689'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'--ignore-config', u'https://www.tiktok.com/@surveyorjono/video/7060687520815762689']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: b428754fa
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[TikTok] Setting up session
[TikTok] 7060687520815762689: Downloading webpage
[info] Available formats for 7060687520815762689:
format code  extension  resolution note
0            mp4        576x1104   
$
```

**Comment by dirkf** [comment]
PR #30479 should now handle this, and other, TT URLs correctly.

**Comment by afterdelight** [comment]
pls merge

**Comment by jakobjjw** [comment]
Fyi, TikTok works with yt-dlp (https://github.com/yt-dlp/yt-dlp), at least as of right now.
