### ISSUE TITLE
SRF.ch temporarily rewatchable livestreams

### ISSUE THREAD

**Issue by infotimbo** [ytdl-org/youtube-dl#30897]
- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

https://www.srf.ch/play/tv/-/video/rad-luettich-bastogne-luettich?urn=urn:swisstxt:video:srf:1740962

> youtube-dl -v https://www.srf.ch/play/tv/-/video/rad-luettich-bastogne-luettich?urn=urn:swisstxt:video:srf:1740962
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['-v', 'https://www.srf.ch/play/tv/-/video/rad-luettich-bastogne-luettich?urn=urn:swisstxt:video:srf:1740962']
> [debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
> [debug] youtube-dl version 2021.12.17
> [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
> [debug] exe versions: ffmpeg git-2020-03-06-cfd9a65, ffprobe git-2020-03-06-cfd9a65
> [debug] Proxy map: {}
> [generic] rad-luettich-bastogne-luettich?urn=urn:swisstxt:video:srf:1740962: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] rad-luettich-bastogne-luettich?urn=urn:swisstxt:video:srf:1740962: Downloading webpage
> [generic] rad-luettich-bastogne-luettich?urn=urn:swisstxt:video:srf:1740962: Extracting information
> ERROR: Unsupported URL: https://www.srf.ch/play/tv/-/video/rad-luettich-bastogne-luettich?urn=urn:swisstxt:video:srf:1740962
> Traceback (most recent call last):
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\generic.py", line 3489, in _real_extract
> youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.srf.ch/play/tv/-/video/rad-luettich-bastogne-luettich?urn=urn:swisstxt:video:srf:1740962

## Description

Youtube-dl works perfectly fine for SRF's "Play SRF" on demand platform, but unfortunately I can't get it to work for those former livestreams, which are still available to watch for a day or two on the website after the sports event, but are not added to the on demand platform afterwards.

Is it possible to add Youtube-dl support for those as well? Thanks.

**Comment by dirkf** [comment]
The problem URL has an extra `srf:` before the numeric id.

Try this:
```py
--- old/youtube_dl/extractor/srgssr.py
+++ new/youtube_dl/extractor/srgssr.py
@@ -166,7 +166,7 @@ class SRGSSRPlayIE(InfoExtractor):
                             [^/]+/(?P<type>video|audio)/[^?]+|
                             popup(?P<type_2>video|audio)player
                         )
-                        \?.*?\b(?:id=|urn=urn:[^:]+:video:)(?P<id>[0-9a-f\-]{36}|\d+)
+                        \?.*?\b(?:id=|urn=urn:[^:]+:video:(?:(?P=bu):)?)(?P<id>[0-9a-f-]{36}|\d+)
                     '''
 
     _TESTS = [{
```

**Comment by dirkf** [comment]
The stream link, as listed, should be inside some manifest (.mpd, .m3u8) that is retrieved from a valid JSON API (not giving 404). This can't be traced from UK owing to geo-block but a HAR saved from the developer tools in a successful in-region browser test should show what's happening.

I see we should also handle `https://www.srf.ch/play/tv/sendung/...` pages, which is possible by searching for `urn=urn:...` and redirecting to the resulting `urn`. Also, I presume that the Flash formats are history and should be skipped, giving this resulting diff:
```py
--- old/youtube_dl/extractor/srgssr.py
+++ new/youtube_dl/extractor/srgssr.py
@@ -81,6 +81,11 @@ class SRGSSRIE(InfoExtractor):
 
         return media_data
 
+    # Don't actually try to extract these obsolete formats
+    # TODO: add a skip_protocols=['f4m'] kwarg to _extract_akamai_formats()
+    def _extract_f4m_formats(self, manifest_url, video_id, **kw):
+        return []
+
     def _real_extract(self, url):
         bu, media_type, media_id = re.match(self._VALID_URL, url).groups()
         media_data = self._get_media_data(bu, media_type, media_id)
@@ -156,6 +161,7 @@ class SRGSSRIE(InfoExtractor):
         }
 
 
+#https://www.srf.ch/play/tv/sendung/para-graf?id=be3b48a9-5ee6-48b3-a270-bdbe1ea1f2e2
 class SRGSSRPlayIE(InfoExtractor):
     IE_DESC = 'srf.ch, rts.ch, rsi.ch, rtr.ch and swissinfo.ch play sites'
     _VALID_URL = r'''(?x)
@@ -164,9 +170,10 @@ class SRGSSRPlayIE(InfoExtractor):
                         (?P<bu>srf|rts|rsi|rtr|swissinfo)\.ch/play/(?:tv|radio)/
                         (?:
                             [^/]+/(?P<type>video|audio)/[^?]+|
-                            popup(?P<type_2>video|audio)player
+                            popup(?P<type_2>video|audio)player|
+                            sendung/[^/]+?/?
                         )
-                        \?.*?\b(?:id=|urn=urn:[^:]+:video:)(?P<id>[0-9a-f\-]{36}|\d+)
+                        \?.*?\b(?:id=|urn=urn:[^:]+:video:(?:(?P=bu):)?)(?P<id>[0-9a-f-]{36}|\d+)
                     '''
 
     _TESTS = [{
@@ -249,4 +256,11 @@ class SRGSSRPlayIE(InfoExtractor):
         bu = mobj.group('bu')
         media_type = mobj.group('type') or mobj.group('type_2')
         media_id = mobj.group('id')
+        if media_type is None:
+            webpage = self._download_webpage(url, media_id, fatal=False) or ''
+            urn = self._html_search_regex(
+                r'''urn=urn:(%s:(?:video|audio):[0-9a-f-]+)['"]''' % re.escape(bu[:3]),
+                webpage, media_id, fatal=False)
+            if urn:
+                return self.url_result('srgssr:%s' % (urn, ), 'SRGSSR')
         return self.url_result('srgssr:%s:%s:%s' % (bu[:3], media_type, media_id), 'SRGSSR')
```
