### ISSUE TITLE
A&E - aetv.com - unable to extract post url

### ISSUE THREAD

**Issue by cbpxxiv** [ytdl-org/youtube-dl#30892]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ap-mso', 'DTV', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-f', 'best', 'https://play.aetv.com/shows/american-justice/season-15/episode-8', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[aenetworks] /shows/american-justice/season-15/episode-8: Downloading JSON metadata
[aenetworks] 2018431043857: Downloading JSON metadata
[aenetworks] 2018431043857: Downloading Provider Redirect Page
[aenetworks] 2018431043857: Downloading Provider Login Page
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\aenetworks.py", line 174, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\aenetworks.py", line 92, in _extract_aetn_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\adobepass.py", line 1513, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\adobepass.py", line 1365, in post_form
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1021, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

attempted to grab several separate videos from A&E, was directed here after posting in the reddit

**Comment by dirkf** [comment]
See #30726 for a related problem and linked discussions, but unfortunately no straightforward answers, and generally with Comcast rather than DTV.

You could try `--write-pages` to provide more debugging information but change your password around that if posting the result. Plainly the "Provider Login Page" being fetched is either not it, or it has an unexpected structure.

https://github.com/yt-dlp/yt-dlp/issues/3060 looks like the same problem.

**Comment by pto199** [comment]
Same problem her.  Unable to extract post URL.  A&E not working

**Comment by dirkf** [comment]
As before, it's actually the DirecTV login that seems to be the problem. This issue and [comment](https://github.com/yt-dlp/yt-dlp/issues/2188#issuecomment-1356345695) apply.

**Comment by pto199** [comment]
> As before, it's actually the DirecTV login that seems to be the problem. This issue and [comment](https://github.com/yt-dlp/yt-dlp/issues/2188#issuecomment-1356345695) apply.

I'm not sure what you mean.  I use Rogers to login and access A&E, not direct TV, and its not working.

**Comment by dirkf** [comment]
In that case it's Rogers, but the same point applies. I presume that yt-dl also fails for other services gated by Rogers in your case?

Support for Rogers was added for #10606, but something may well have changed since then.

**Comment by 3052** [comment]
usual rules apply. need account for testing. otherwise we can wait another two years.
