### ISSUE TITLE
not a valid url

### ISSUE THREAD

**Issue by ldwnt** [ytdl-org/youtube-dl#30916]
trying to download video https://www.youtube.com/watch?v=zJFfaWrVhdI

## Verbose log

```
C:\pro>youtube-dl.exe -v --proxy socks5://127.0.0.1:10802/ -f 'bestvideo+bestaudio/best' 'https://www.youtube.com/watch?v=zJFfaWrVhdI'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--proxy', 'socks5://127.0.0.1:10802/', '-f', "'bestvideo+bestaudio/best'", "'https://www.youtube.com/watch?v=zJFfaWrVhdI'"]
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {'https': 'socks5://127.0.0.1:10802/', 'http': 'socks5://127.0.0.1:10802/'}
ERROR: "'https://www.youtube.com/watch?v=zJFfaWrVhdI'" is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:'https://www.youtube.com/watch?v=zJFfaWrVhdI'" ) to search YouTube
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\generic.py", line 2364, in _real_extract
youtube_dl.utils.ExtractorError: "'https://www.youtube.com/watch?v=zJFfaWrVhdI'" is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:'https://www.youtube.com/watch?v=zJFfaWrVhdI'" ) to search YouTube
```

```
C:\pro>youtube-dl.exe -v --proxy socks5://127.0.0.1:10802/ -f 'bestvideo+bestaudio/best' "ytsearch:'https://www.youtube.com/watch?v=zJFfaWrVhdI'"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--proxy', 'socks5://127.0.0.1:10802/', '-f', "'bestvideo+bestaudio/best'", "ytsearch:'https://www.youtube.com/watch?v=zJFfaWrVhdI'"]
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {'https': 'socks5://127.0.0.1:10802/', 'http': 'socks5://127.0.0.1:10802/'}
[download] Downloading playlist: 'https://www.youtube.com/watch?v=zJFfaWrVhdI'
[youtube:search] query "'https://www.youtube.com/watch?v=zJFfaWrVhdI'": Downloading page 1
[youtube:search] playlist 'https://www.youtube.com/watch?v=zJFfaWrVhdI': Downloading 1 videos
[download] Downloading video 1 of 1
[youtube] zJFfaWrVhdI: Downloading webpage
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 847, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 881, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 1684, in process_video_result
youtube_dl.utils.ExtractorError: requested format not available
```

**Comment by dirkf** [comment]
In Windows _cmd_, [use "double quotes" around the URL](https://ss64.com/nt/syntax-esc.html).

**Comment by 89z** [comment]
@dirkf did you get my email?

**Comment by ldwnt** [comment]
> youtube-dl.exe -v --proxy socks5://127.0.0.1:10802/ -f 'bestvideo+bestaudio/best' 'https://www.youtube.com/watch?v=zJFfaWrVhdI'

It works. Thank you!

**Comment by 89z** [comment]
I think I answered my own question `github.com/ytdl-org/youtube-dl/issues/2238`
