### ISSUE TITLE
[ARTE.tv] Unable to download JSON metadata

### ISSUE THREAD

**Issue by sebastienadam** [ytdl-org/youtube-dl#30919]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
user@user-VirtualBox:~/Téléchargements$ youtube-dl --verbose https://www.arte.tv/fr/videos/097516-000-A/operation-1005-les-effaceurs-de-crimes/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.arte.tv/fr/videos/097516-000-A/operation-1005-les-effaceurs-de-crimes/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.13.0-40-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[ArteTV] 097516-000-A: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

```

## Description

I was trying to download a video from website https://arte.tv/. Before, `youtube-dl` was working well with this site, but not anymore. I tried to re-download previously (successfully) downloaded videos, but I still receive the same error. I guess the page format changed.

Thanks for your job.

**Comment by dirkf** [comment]
Although the log is not exactly the same, see #30878.

**Comment by 89z** [comment]
Do they have any English stuff? I would be willing to look at this, but it needs to be something I might actually watch

**Comment by laryllian** [comment]
Sure they do, so much wonderful stuff:
https://www.arte.tv/en/

They even have full concerts: Rolling stones – A bigger bang
https://www.arte.tv/de/videos/105608-000-A/rolling-stones-a-bigger-bang/

I'd really apprechiate you looking into this. :D

Greetz and thank you
laryllian

Zombo schrieb am 05.06.22 um 19:08 Uhr:

**Comment by DDBE12** [comment]
I've found a very easy workaround for this arte.tv problem with their API. No need to do any updates, download new PY files, or switch to a different code/app. After hours and hours of googling, I found a casual remark that just said, "API 2 simply means that you need to find the m3u8 URL."

So basically, all one has to do is google how to find find the URL for a blob video in your specific browser (the routines are a little different in Firefor and Chrome, respectively). Once you've found it, you only need to fetch the URL for the m3u8 file and paste it into youtube-dl, done.

**Comment by oblab** [comment]
on firefox, open Developer Tools, go to Media tab, search for mp4 file, the copy the url : 
![Capture d’écran du 2022-09-09 13-27-04](https://user-images.githubusercontent.com/251367/189340079-5c7e4845-aa32-4d65-bf09-71384aafc657.png)

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31242

**Comment by Vangelis66** [comment]
... Backporting from current `yt-dlp` might be necessary to restore **ARTE.tv** downloads in `youtube-dl`;
 sample URL available (and working) at the time of writing: 

https://www.arte.tv/en/videos/067103-000-A/mariupol/
```
yt-dlp -v -F "https://www.arte.tv/en/videos/067103-000-A/mariupol/" --ie ArteTV => 

[debug] Command-line config: ['--ffmpeg-location', '..', '--downloader-args', 'ffmpeg:-v 8 -stats', '-v', '-F', 'https://www.arte.tv/en/videos/067103-000-A/mariupol/']
[debug] Encodings: locale cp1253, fs utf-8, pref cp1253, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] ytdl-patched/yt-dlp version 2022.09.19.40298 [bd21f4d] (win32_exe)
[debug] ** This build is unofficial daily builds, provided for ease of use.
[debug] ** Please do not ask for any support.
[debug] Python 3.7.9 (CPython 32bit) - Windows-Vista-6.0.6003-SP2
[debug] Checking exe version: "..\ffmpeg" -bsfs
[debug] Checking exe version: "..\ffprobe" -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.14, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1671 extractors
[debug] [ArteTV] Extracting URL: https://www.arte.tv/en/videos/067103-000-A/mariupol/
[ArteTV] 067103-000-A: Downloading JSON metadata
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7),vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 067103-000-A:
ID                             EXT RESOLUTION FPS |   FILESIZE   TBR PROTO | VCODEC        VBR ACODEC     MORE INFO
----------------------------------------------------------------------------------------------------------------------------------------------
VO-STA-program_audio_0-VO      mp4 audio only     |                  m3u8  | audio only        unknown    [ru] German (Subtitles) [subDE]
VO-STE_ESP_-program_audio_0-VO mp4 audio only     |                  m3u8  | audio only        unknown    [ru] Spanish (Subtitles) [OGsub-ESP]
VO-STE_ITA_-program_audio_0-VO mp4 audio only     |                  m3u8  | audio only        unknown    [ru] Italian (Subtitles) [OGsub-ITA]
VO-STE_POL_-program_audio_0-VO mp4 audio only     |                  m3u8  | audio only        unknown    [ru] Polish (Subtitles) [OGsub-POL]
VO-STF-program_audio_0-VO      mp4 audio only     |                  m3u8  | audio only        unknown    [ru] French (Subtitles) [subFR]
VO-STE_ANG_-program_audio_0-VO mp4 audio only     |                  m3u8  | audio only        unknown    [ru] English (Subtitles) [OGsub-ANG]
VO-STA-426                     mp4 384x216     25 | ~248.75MiB  426k m3u8  | avc1.42e00d  426k video only German (Subtitles) [subDE]
VO-STE_ESP_-426                mp4 384x216     25 | ~248.75MiB  426k m3u8  | avc1.42e00d  426k video only Spanish (Subtitles) [OGsub-ESP]
VO-STE_ITA_-426                mp4 384x216     25 | ~248.75MiB  426k m3u8  | avc1.42e00d  426k video only Italian (Subtitles) [OGsub-ITA]
VO-STE_POL_-426                mp4 384x216     25 | ~248.75MiB  426k m3u8  | avc1.42e00d  426k video only Polish (Subtitles) [OGsub-POL]
VO-STF-426                     mp4 384x216     25 | ~248.75MiB  426k m3u8  | avc1.42e00d  426k video only French (Subtitles) [subFR]
VO-STA-927                     mp4 640x360     25 | ~541.19MiB  927k m3u8  | avc1.4d401e  927k video only German (Subtitles) [subDE]
VO-STE_ESP_-927                mp4 640x360     25 | ~541.19MiB  927k m3u8  | avc1.4d401e  927k video only Spanish (Subtitles) [OGsub-ESP]
VO-STE_ITA_-927                mp4 640x360     25 | ~541.19MiB  927k m3u8  | avc1.4d401e  927k video only Italian (Subtitles) [OGsub-ITA]
VO-STE_POL_-927                mp4 640x360     25 | ~541.19MiB  927k m3u8  | avc1.4d401e  927k video only Polish (Subtitles) [OGsub-POL]
VO-STF-927                     mp4 640x360     25 | ~541.19MiB  927k m3u8  | avc1.4d401e  927k video only French (Subtitles) [subFR]
VO-STA-1617                    mp4 768x432     25 | ~943.97MiB 1617k m3u8  | avc1.4d401e 1617k video only German (Subtitles) [subDE]
VO-STE_ESP_-1617               mp4 768x432     25 | ~943.97MiB 1617k m3u8  | avc1.4d401e 1617k video only Spanish (Subtitles) [OGsub-ESP]
VO-STE_ITA_-1617               mp4 768x432     25 | ~943.97MiB 1617k m3u8  | avc1.4d401e 1617k video only Italian (Subtitles) [OGsub-ITA]
VO-STE_POL_-1617               mp4 768x432     25 | ~943.97MiB 1617k m3u8  | avc1.4d401e 1617k video only Polish (Subtitles) [OGsub-POL]
VO-STF-1617                    mp4 768x432     25 | ~943.97MiB 1617k m3u8  | avc1.4d401e 1617k video only French (Subtitles) [subFR]
VO-STA-2313                    mp4 1280x720    25 | ~  1.32GiB 2313k m3u8  | avc1.4d401f 2313k video only German (Subtitles) [subDE]
VO-STE_ESP_-2313               mp4 1280x720    25 | ~  1.32GiB 2313k m3u8  | avc1.4d401f 2313k video only Spanish (Subtitles) [OGsub-ESP]
VO-STE_ITA_-2313               mp4 1280x720    25 | ~  1.32GiB 2313k m3u8  | avc1.4d401f 2313k video only Italian (Subtitles) [OGsub-ITA]
VO-STE_POL_-2313               mp4 1280x720    25 | ~  1.32GiB 2313k m3u8  | avc1.4d401f 2313k video only Polish (Subtitles) [OGsub-POL]
VO-STF-2313                    mp4 1280x720    25 | ~  1.32GiB 2313k m3u8  | avc1.4d401f 2313k video only French (Subtitles) [subFR]
VO-STE_ANG_-426                mp4 384x216     25 | ~248.75MiB  426k m3u8  | avc1.42e00d  426k video only English (Subtitles) [OGsub-ANG]
VO-STE_ANG_-927                mp4 640x360     25 | ~541.19MiB  927k m3u8  | avc1.4d401e  927k video only English (Subtitles) [OGsub-ANG]
VO-STE_ANG_-1617               mp4 768x432     25 | ~943.97MiB 1617k m3u8  | avc1.4d401e 1617k video only English (Subtitles) [OGsub-ANG]
VO-STE_ANG_-2313               mp4 1280x720    25 | ~  1.32GiB 2313k m3u8  | avc1.4d401f 2313k video only English (Subtitles) [OGsub-ANG]
```

**Comment by Vangelis66** [comment]
> I just figured out that 
https://github.com/yt-dlp/yt-dlp 
appears to work

... The sample `ARTE.tv` link I used [back in Sep of last year](v) now produces different results with latest `yt-dlp`: 
```shell
[debug] Command-line config: ['--ffmpeg-location', '..\\FFmpeg', '--downloader-args', 'ffmpeg:-v 8 -stats', '-v', '-F', 'https://www.arte.tv/en/videos/067103-000-A/mariupol/', '--ie', 'ArteTV']
[debug] Encodings: locale cp1253, fs utf-8, pref cp1253, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version 2023.02.14 [8b37c58f8] (win_x86_exe)
[debug] Python 3.8.16 (CPython x86 32bit) - Windows-Vista-6.0.6003-SP2 (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg n5.2-dev-2245-N-109649-gab8cde6 (setts), ffprobe n5.2-dev-2245-N-109649-gab8cde6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Extractor Plugins: AGB+NSIG (YoutubeIE)
[debug] Plugin directories: ['<redacted>\\yt-dlp-plugins\\YTAgeGateBypass.zip\\yt_dlp_plugins', '<redacted>\\yt-dlp-plugins\\YTNSigProxy.zip\\yt_dlp_plugins']
[debug] Loaded 1 extractors
[ArteTV] Extracting URL: https://www.arte.tv/en/videos/067103-000-A/mariupol/
[ArteTV] 067103-000-A: Downloading JSON metadata
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 067103-000-A:
ID                        EXT RESOLUTION FPS |   FILESIZE   TBR PROTO | VCODEC      VBR ACODEC     MORE INFO
------------------------------------------------------------------------------------------------------------------------------------
VO-STF-program_audio_0-VO mp4 audio only     |                  m3u8  | audio only        unknown    [ru] French (Subtitles) [subFR]
VO-STF-426                mp4 384x216     25 | ~248.75MiB  426k m3u8  | avc1.42e00d  426k video only French (Subtitles) [subFR]
VO-STF-927                mp4 640x360     25 | ~541.19MiB  927k m3u8  | avc1.4d401e  927k video only French (Subtitles) [subFR]
VO-STF-1617               mp4 768x432     25 | ~943.97MiB 1617k m3u8  | avc1.4d401e 1617k video only French (Subtitles) [subFR]
VO-STF-2313               mp4 1280x720    25 | ~  1.32GiB 2313k m3u8  | avc1.4d401f 2313k video only French (Subtitles) [subFR]
```
... And a "word" of caution: 
```shell
yt-dlp "https://www.arte.tv/en/videos/067103-000-A/mariupol/" --list-subs => 

[ArteTV] Extracting URL: https://www.arte.tv/en/videos/067103-000-A/mariupol/
[ArteTV] 067103-000-A: Downloading JSON metadata
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[info] Available subtitles for 067103-000-A:
Language Formats
en       vtt
fr       vtt
de       vtt
es       vtt
pl       vtt
it       vtt
```
If you prefer your subs (like myself :wink:) in the old but trusted `.srt` format, 
```shell
yt-dlp "https://www.arte.tv/en/videos/067103-000-A/mariupol/" --skip-download --write-subs --sub-langs en --convert-subs srt => 

[ArteTV] Extracting URL: https://www.arte.tv/en/videos/067103-000-A/mariupol/
[ArteTV] 067103-000-A: Downloading JSON metadata
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[info] 067103-000-A: Downloading subtitles: en
[info] 067103-000-A: Downloading 1 format(s): VO-STF-2313+VO-STF-program_audio_0-VO
[info] Writing video subtitles to: Mariupol [067103-000-A].en.vtt
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1
[download] Destination: Mariupol [067103-000-A].en.vtt
[download] 100% of   39.89KiB in 00:00:02 at 19.65KiB/s
[SubtitlesConvertor] Converting subtitles
Deleting original file Mariupol [067103-000-A].en.vtt (pass -k to keep)
```
... will leave you with an **empty** `Mariupol [067103-000-A].en.srt` file 😞 😭 😠 ...
This is because the specific `webvtt` subs format ARTE serve is **not palatable** to **FFmpeg**, used for the conversion `vtt => srt`... 

Simply fetch the original `vtt` subs: 
```
yt-dlp "https://www.arte.tv/en/videos/067103-000-A/mariupol/" --skip-download --write-subs --sub-langs en
```
and use another tool to convert them to `.srt` (I found fairly recent :wink: releases of [SubtitleEdit](https://github.com/SubtitleEdit/subtitleedit/releases) to work OK for the task 👍 ) ...

**Comment by dirkf** [comment]
As the PR for the yt-dlp extractor has been merged, the only reason not to update the yt-dl extractor is that yt-dl doesn't have the subtitle extraction API used by yt-dlp, but I see that is problematic, pending a fix for the format conversion. So:
```shellsession
$ python -m youtube_dl -v -F 'https://www.arte.tv/en/videos/067103-000-A/mariupol/'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.arte.tv/en/videos/067103-000-A/mariupol/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: dd9aa74be
[debug] Python version 2.7.18 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[ArteTV] 067103-000-A: Downloading JSON metadata
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[info] Available formats for 067103-000-A:
format code                     extension  resolution note
VO-STE_ANG_-program_audio_0-VO  mp4        audio only [ru] English (Subtitles) [?] 
VO-STE_ANG_-1617                mp4        768x432    English (Subtitles) [?] 1617k , avc1.4d401e, 25.0fps, video only
VO-STE_ANG_-2313                mp4        1280x720   English (Subtitles) [?] 2313k , avc1.4d401f, 25.0fps, video only
VO-STE_ANG_-927                 mp4        640x360    English (Subtitles) [?]  927k , avc1.4d401e, 25.0fps, video only
VO-STE_ANG_-426                 mp4        384x216    English (Subtitles) [?]  426k , avc1.42e00d, 25.0fps, video only (best)
$
```
If anyone has a replacement test video for `ArteTVEmbed`, please submit it. It might be like this one that is no longer valid:
`https://www.arte.tv/player/v5/index.php?json_url=https%3A%2F%2Fapi.arte.tv%2Fapi%2Fplayer%2Fv2%2Fconfig%2Fde%2F100605-013-A&lang=de&autoplay=true&mute=0100605-013-A`
G doesn't admit to having indexed any pages with URL `https://www.arte.tv/player/v5/...`.

Otherwise this extractor will be marked as not `_WORKING`.

**Comment by andreygursky** [comment]
The following video https://www.arte.tv/de/videos/060738-167-A/blow-up-rainer-werner-fassbinder-in-bildern/ (ID: 060738-167-A) is claimed to be available until 01.08.2114 (though it might change without notice, which renders such availability declarations ad absurdum).

**Comment by Vangelis66** [comment]
... Apparently, a "fix" for (default) **format sorting (according to increasing resolution)** will also be needed: 
```shell
(redacted for brevity)
VO-STE_ANG_-program_audio_0-VO  mp4        audio only [ru] English (Subtitles) [?] 
VO-STE_ANG_-1617                mp4        768x432    English (Subtitles) [?] 1617k , avc1.4d401e, 25.0fps, video only
VO-STE_ANG_-2313                mp4        1280x720   English (Subtitles) [?] 2313k , avc1.4d401f, 25.0fps, video only
VO-STE_ANG_-927                 mp4        640x360    English (Subtitles) [?]  927k , avc1.4d401e, 25.0fps, video only
VO-STE_ANG_-426                 mp4        384x216    English (Subtitles) [?]  426k , avc1.42e00d, 25.0fps, video only (best)
```
Notice how `216p` has been labeled as "**(best)**"? 
Reminds me of a similar issue with the `dwIE` I reported [here](https://github.com/dirkf/youtube-dl/commit/76d2e50a853b514262b3a8bebd33416bc9959652#commitcomment-85207652)...

**Comment by Vangelis66** [comment]
> see updated PR https://github.com/ytdl-org/youtube-dl/pull/29653.

At its latest commit, cdcb4af1c3257d955404ac5ea34becbb2bb1b1d3, works adequately well, **without addressing the format sorting issue** I reported above: 
```shell 
yt-dl -vF "https://www.arte.tv/en/videos/067103-000-A/mariupol/" => 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', '.\\FFmpeg', '--external-downloader-args', '-v 8 -stats', '-vF', 'https://www.arte.tv/en/videos/067103-000-A/mariupol/']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2023.02.14.1919
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg n5.2-dev-2245-N-109649-gab8cde6, ffprobe n5.2-dev-2245-N-109649-gab8cde6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[ArteTV] 067103-000-A: Downloading JSON metadata
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[ArteTV] 067103-000-A: Downloading m3u8 information
[info] Available formats for 067103-000-A:
format code                extension  resolution note
VO-STF-program_audio_0-VO  mp4        audio only [ru] French (Subtitles) [subFR]
VO-STF-1617                mp4        768x432    French (Subtitles) [subFR] 1617k , avc1.4d401e, 25.0fps, video only
VO-STF-2313                mp4        1280x720   French (Subtitles) [subFR] 2313k , avc1.4d401f, 25.0fps, video only
VO-STF-927                 mp4        640x360    French (Subtitles) [subFR]  927k , avc1.4d401e, 25.0fps, video only
VO-STF-426                 mp4        384x216    French (Subtitles) [subFR]  426k , avc1.42e00d, 25.0fps, video only (best)
```

**Comment by dirkf** [comment]
>... a "fix" for (default) format sorting (according to increasing resolution) will also be needed:

How true. You can imagine the back-porting process:
1. Think "remember to find where the formats are collected and sort them, since yt-dlp moved that to the core".
2. Fix a swathe of minor issues.
3. "Yay, the tests all pass".
4. Forget (1).

The PR was updated from the same code as used above and will shortly be brought into line.

Given the change in (1), a test for `height` or some similar metadata item needs to be included in at least one test-case for each back-ported extractor.

>The following video ... is claimed to be available ...

Thanks, but that's just a normal `ArteTV` URL. I'm looking for a URL that matches the pattern `r'https?://(?:www\.)?arte\.tv/player/v\d+/index\.php\?.*?\bjson_url=.+'`, eg has `/player/v` after the domain name and a query parameter `json_url`, as in the existing test URL shown above.

**Comment by andreygursky** [comment]
> ... I'm looking for a URL ...
Following works in a browser tab:
https://www.arte.tv/player/v7/index.php?json_url=https://api.arte.tv/api/player/v2/config/de/060738-167-A
Optional appending "?lang=de&autoplay=false&mute=0"

**Comment by dirkf** [comment]
Thanks, both variants of that are working with the PR code. Actually I realised that you can invent these URLs from any non-embedded URL, so I used this:
```
https://www.arte.tv/player/v5/index.php?json_url=https%3A%2F%2Fapi.arte.tv%2Fapi%2Fplayer%2Fv2%2Fconfig%2Fpl%2F100103-000-A&lang=pl&autoplay=true&mute=100103-000-A
```

**Comment by mk-pmb** [comment]
I tried https://www.arte.tv/de/videos/132147-004-A/ad-infinitum/

Attempt 1: master branch, URL from browser.

<details><summary>Unable to download JSON metadata: HTTP Error 404: Not Found</summary>

```text
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-call-home', '--abort-on-error', '--no-overwrites', '--keep-video', '--restrict-filenames', '--output', '…', '--verbose', '--list-formats', '--', 'https://www.arte.tv/de/videos/132147-004-A/ad-infinitum/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2025.04.07
[debug] Git HEAD: 956b8c585
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-…-x86_64-with-glibc… - OpenSSL 1.1.1f  31 Mar 2020 - glibc …
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {…}
[ArteTV] 132147-004-A: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on […]
  File "/…/youtube_dl/extractor/common.py", line 682, in _request_webpage: return self._downloader.urlopen(url_or_request)
  File "/…/youtube_dl/YoutubeDL.py", line 2495, in urlopen: return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/[…]
```

</details>

Attempt 2: master branch, constructed API URL from the example in dirkf's message above.

<details><summary>Unable to download JSON metadata: HTTP Error 404: Not Found</summary>

```text
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-call-home', '--abort-on-error', '--no-overwrites', '--keep-video', '--restrict-filenames', '--output', '…', '--verbose', '--list-formats', '--', 'https://www.arte.tv/player/v7/index.php?json_url=https://api.arte.tv/api/player/v2/config/de/132147-004-A']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2025.04.07
[debug] Git HEAD: 956b8c585
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-…-x86_64-with-glibc… - OpenSSL 1.1.1f  31 Mar 2020 - glibc …
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {…}
[ArteTV] 132147-004-A: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on […]
  File "/…/youtube_dl/extractor/common.py", line 682, in _request_webpage: return self._downloader.urlopen(url_or_request)
  File "/…/youtube_dl/YoutubeDL.py", line 2495, in urlopen: return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/[…]
```

</details>

Attempt 3: master branch, rebase on [commit a4759ae "Fix ArteTVEmbedIE"](https://github.com/casaper/youtube-dl-1/commit/a4759ae8ea18bc13cb4342d8ec5d498a8a309e4a), original URL

<details><summary>WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG_MA / ERROR: No video formats found</summary>

```text
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-call-home', '--abort-on-error', '--no-overwrites', '--keep-video', '--restrict-filenames', '--output', '…', '--verbose', '--list-formats', '--', 'https://www.arte.tv/de/videos/132147-004-A/ad-infinitum/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2025.04.07
[debug] Git HEAD: d371bc338
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-…-x86_64-with-glibc… - OpenSSL 1.1.1f  31 Mar 2020 - glibc …
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {…}
[ArteTV] 132147-004-A: Downloading JSON metadata
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG_MA
ERROR: No video formats found; please report this issue on […]
Traceback (most recent call last):
  File "/…/youtube_dl/YoutubeDL.py", line 882, in wrapper: return func(self, *args, **kwargs)
  File "/…/youtube_dl/YoutubeDL.py", line 978, in __extract_info: ie_result = ie.extract(url)
  File "/…/youtube_dl/extractor/common.py", line 574, in extract: ie_result = self._real_extract(url)
  File "/…/youtube_dl/extractor/arte.py", line 213, in _real_extract: self._sort_formats(formats)
  File "/…/youtube_dl/extractor/common.py", line 1551, in _sort_formats: raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on […]
```

</details>

Attempt 4: master branch, rebase on [commit a4759ae "Fix ArteTVEmbedIE"](https://github.com/casaper/youtube-dl-1/commit/a4759ae8ea18bc13cb4342d8ec5d498a8a309e4a), generated API URL

<details><summary>WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG_MA / ERROR: No video formats found</summary>

```text
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-call-home', '--abort-on-error', '--no-overwrites', '--keep-video', '--restrict-filenames', '--output', '…', '--verbose', '--list-formats', '--', 'https://www.arte.tv/player/v7/index.php?json_url=https://api.arte.tv/api/player/v2/config/de/132147-004-A']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2025.04.07
[debug] Git HEAD: d371bc338
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-…-x86_64-with-glibc… - OpenSSL 1.1.1f  31 Mar 2020 - glibc …
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {…}
[ArteTV] 132147-004-A: Downloading JSON metadata
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG_MA
ERROR: No video formats found; please report this issue on […]
Traceback (most recent call last):
  File "/…/youtube_dl/YoutubeDL.py", line 882, in wrapper: return func(self, *args, **kwargs)
  File "/…/youtube_dl/YoutubeDL.py", line 978, in __extract_info: ie_result = ie.extract(url)
  File "/…/youtube_dl/extractor/common.py", line 574, in extract: ie_result = self._real_extract(url)
  File "/…/youtube_dl/extractor/arte.py", line 213, in _real_extract: self._sort_formats(formats)
  File "/…/youtube_dl/extractor/common.py", line 1551, in _sort_formats: raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on […]
```

</details>

**Comment by dirkf** [comment]
Attempt 4 was the only one likely to succeed. The skipped protocol shouldn't be. Then:
```console
$ python -m youtube_dl -vF 'https://www.arte.tv/de/videos/132147-004-A/ad-infinitum/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vF', u'https://www.arte.tv/de/videos/132147-004-A/ad-infinitum/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 71ac16cbc
[debug] Python 2.7.15 (CPython i686 32bit) - Linux-6.1.0-40-686-pae-i686-with-debian-12.14 - OpenSSL 1.1.1a  20 Nov 2018 - glibc 2.1.3
[debug] exe versions: ffmpeg 5.1.9-0, ffprobe 5.1.9-0
[debug] Proxy map: {}
[ArteTV] Extracting URL: https://www.arte.tv/de/videos/132147-004-A/ad-infinitum/
[ArteTV] 132147-004-A: Downloading JSON metadata
[ArteTV] 132147-004-A: Downloading m3u8 information
[info] Available formats for 132147-004-A:
format code                            extension  resolution note
VO-audio_0-Originalversion__Original_  mp4        audio only [und] Originalfassung [OV], mp4a.40.2
VO-427                                 mp4        384x216    Originalfassung [OV],  427k, avc1.42000D@ 427k, 25.0fps, video only
VO-728                                 mp4        640x360    Originalfassung [OV],  728k, avc1.4D001E@ 728k, 25.0fps, video only
VO-1376                                mp4        768x432    Originalfassung [OV], 1376k, avc1.4D001E@1376k, 25.0fps, video only
VO-2262                                mp4        1280x720   Originalfassung [OV], 2262k, avc1.4D001F@2262k, 25.0fps, video only
VO-2264                                mp4        1280x720   Originalfassung [OV], 2264k, hev1.2.4.L120.B0@2264k, 25.0fps, video only
VO-2498                                mp4        1920x1080  Originalfassung [OV], 2498k, avc1.4d0028@2498k, 25.0fps, video only
VO-2501                                mp4        1920x1080  Originalfassung [OV], 2501k, hev1.2.4.L123.B0@2501k, 25.0fps, video only (best)
$
```
