### ISSUE TITLE
[Teachable] Unable to find video URL

### ISSUE THREAD

**Issue by CanisHelix** [ytdl-org/youtube-dl#30929]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies=../cookies-teachable.txt', '--download-archive', 'archive.txt', '-o', './%(chapter_number)s-%(chapter)s/%(autonumber)03d-%(title)s.%(ext)s', 'https://unf-vault.teachable.com/courses/enrolled/1696460', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-16-amd64-x86_64-with-debian-10.9
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[generic] 1696460: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1696460: Downloading webpage
[generic] 1696460: Extracting information
[TeachableCourse] 1696460: Downloading webpage
[download] Downloading playlist: Creating an Interactive Menu in UE5 in the Style of Genshin Impact
[TeachableCourse] playlist Creating an Interactive Menu in UE5 in the Style of Genshin Impact: Collected 82 video ids (downloading 82 of them)
[download] Downloading video 1 of 82
[Teachable] 38493768: Downloading webpage
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/teachable.py", line 176, in _real_extract
    raise ExtractorError('Unable to find video URL')
youtube_dl.utils.ExtractorError: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

All courses from https://unf-vault.teachable.com/ are now producing the above error, 2-4 weeks ago these were working just fine. I have updated my cookies file today incase that was a problem.

There are other issues with Teachable reported, but none of them reference a 'Unable to find video URL' error.

**Comment by CanisHelix** [comment]
@dirkf [38493768_https_-_unf-vault.teachable.com_courses_1696460_lectures_38493768.log](https://github.com/ytdl-org/youtube-dl/files/8675522/38493768_https_-_unf-vault.teachable.com_courses_1696460_lectures_38493768.log)

I renamed the .dump as .log due to git's upload restrictions.

**Comment by AlphaTurtlee** [comment]
I also have the same issue.
Could I be notified when this gets fixed?

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31133
