### ISSUE TITLE
ERROR: An extractor error has occurred. (caused by KeyError('vkey',)) on www.empflix.com

### ISSUE THREAD

**Issue by KimuraHajime** [ytdl-org/youtube-dl#30937]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
> youtube-dl -v 'https://www.empflix.com/asian-pom/softcore-asian-schoolgirl-bra-panty-upskirt-tease/video691737'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.empflix.com/asian-pom/softcore-asian-schoolgirl-bra-panty-upskirt-tease/video691737']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22000
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev, ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Proxy map: {}
[EMPFlix] softcore-asian-schoolgirl-bra-panty-upskirt-tease: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('vkey',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\tnaflix.py", line 95, in _real_extract
KeyError: 'vkey'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\tnaflix.py", line 95, in _real_extract
KeyError: 'vkey'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 547, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('vkey',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I can't download any movies from www.empflix.com.
Please check it.
Thanks.

**Comment by dirkf** [comment]
The page format has changed. An update to `extractor/tnaflix.py` is needed. No-one has complained about the other sites supported by the extractor and they don't seem to have this new format.
