### ISSUE TITLE
VIU.COM (za) "unsupported URL

### ISSUE THREAD

**Issue by drav3nat0r** [ytdl-org/youtube-dl#30941]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['-v', 'https://www.viu.com/ott/za/en/all/video-english-drama-tv_shows-7delaan_s23_ep_96_wed_11_may-1166000526?containerId=playlist-26272329']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade65] (win_exe)
[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.14.1, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.viu.com/ott/za/en/all/video-english-drama-tv_shows-7delaan_s23_ep_96_wed_11_may-1166000526?containerId=playlist-26272329
[generic] video-english-drama-tv_shows-7delaan_s23_ep_96_wed_11_may-1166000526?containerId=playlist-26272329: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] video-english-drama-tv_shows-7delaan_s23_ep_96_wed_11_may-1166000526?containerId=playlist-26272329: Downloading webpage
[generic] video-english-drama-tv_shows-7delaan_s23_ep_96_wed_11_may-1166000526?containerId=playlist-26272329: Extracting information
[debug] Looking for video embeds
[debug] Identified a JSON LD
[debug] [generic] Extracting URL: https://www.viu.com/ott/za/en/all/video-english-drama-tv_shows-7delaan_s23_ep_96_wed_11_may-1166000526?containerId=playlist-26271810#__youtubedl_smuggle=%7B%22force_videoid%22%3A+%22video-english-drama-tv_shows-7delaan_s23_ep_96_wed_11_may-1166000526%3FcontainerId%3Dplaylist-26272329%22%2C+%22to_generic%22%3A+true%7D
[generic] video-english-drama-tv_shows-7delaan_s23_ep_96_wed_11_may-1166000526?containerId=playlist-26272329: Requesting header
[generic] video-english-drama-tv_shows-7delaan_s23_ep_96_wed_11_may-1166000526?containerId=playlist-26272329: Downloading webpage
[generic] video-english-drama-tv_shows-7delaan_s23_ep_96_wed_11_may-1166000526?containerId=playlist-26272329: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.viu.com/ott/za/en/all/video-english-drama-tv_shows-7delaan_s23_ep_96_wed_11_may-1166000526?containerId=playlist-26271810
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1400, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1470, in __extract_info
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\generic.py", line 4037, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.viu.com/ott/za/en/all/video-english-drama-tv_shows-7delaan_s23_ep_96_wed_11_may-1166000526?containerId=playlist-26271810
```

## Description

I am trying to download the FREE video at the mentioned URL but I am getting an "Unsupported URL" error.  The site is www.viu.com (supported afaik).

**Comment by 89z** [comment]
Looks like its a hard geo block. I tried Bahrain:

~~~
GET /ott/za/en/all/video-english-drama-tv_shows-7delaan_s23_ep_96_wed_11_may-1166000526?containerId=playlist-26272329 HTTP/2.0
Host: www.viu.com
X-Forwarded-For: 37.131.0.0
~~~

and still get a redirect:

~~~
HTTP/1.1 307 Temporary Redirect
Location: https://www.viu.com/ott/no-service/
~~~

https://github.com/ytdl-org/youtube-dl/blob/c7965b9fc2cae54f244f31f5373cb81a40e822ab/youtube_dl/utils.py#L5153

**Comment by drav3nat0r** [comment]
Hi, thanks for the quick response, however it can't be a geo block issue as I am in South Africa trying to download a South African stream that I can watch live without any issues

**Comment by 89z** [comment]
previous comment wasn't for you

**Comment by dirkf** [comment]
The problem URL:
`https://www.viu.com/ott/za/en/all/video-english-drama-tv_shows-7delaan_s23_ep_96_wed_11_may-1166000526?containerId=playlist-26272329`

The format supported by the Viu extractor, designed (apparently) for India and Indonesia:
`https://www.viu.com/en/media/1116705532?containerId=playlist-22168059`

Assuming that the ID of the problem URL is `1166000526` and that the same web API applies, try `viu:1166000526`. If that works, we just need to tweak the `_VALID_URL` to handle the problem URL format (and so more examples of video page URLs from the site would be helpful).
