### ISSUE TITLE
[make] ImportError: cannot import name 'YoutubeSearchURLIE' ...

### ISSUE THREAD

**Issue by KACTbIJIb** [ytdl-org/youtube-dl#30948]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Description

I have downloaded latest version from master branch and "makefile".
geting this error on start:
```
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/__init__.py", line 4, in <module>
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 16, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 15, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/options.py", line 8, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/__init__.py", line 23, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/niconico.py", line 11, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/__init__.py", line 9, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/extractors.py", line 1617, in <module>
ImportError: cannot import name 'YoutubeSearchURLIE' from 'youtube_dl.extractor.youtube' (/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py)
```

**Comment by dirkf** [comment]
In your configuration, just install the master branch using _pip_.
```
python -m pip install 'https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.tar.gz'
```
See https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/.

It looks like you're trying to build the self-extracting executable version but Python is finding modules on its path instead of the ones in the build directory. Setting `PYTHONPATH` or otherwise concealing the installed yt-dl modules might solve the logged issue.

**Comment by KACTbIJIb** [comment]
> In your configuration, just install the master branch using _pip_.
> 
> ```
> python -m pip install 'https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.tar.gz'
> ```
> 
> See https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/.
> 
> It looks like you're trying to build the self-extracting executable version but Python is finding modules on its path instead of the ones in the build directory. Setting `PYTHONPATH` or otherwise concealing the installed yt-dl modules might solve the logged issue. Or are you trying to run a version that tried to build (would have been clear if the actual failing command-line was given)?

failing command-line was given when i tried to run version that apeared after build

**Comment by KACTbIJIb** [comment]
> In your configuration, just install the master branch using _pip_.
> 
> ```
> python -m pip install 'https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.tar.gz'
> ```
> 
> See https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/.
> 
> It looks like you're trying to build the self-extracting executable version but Python is finding modules on its path instead of the ones in the build directory. Setting `PYTHONPATH` or otherwise concealing the installed yt-dl modules might solve the logged issue. Or are you trying to run a version that tried to build (would have been clear if the actual failing command-line was given)?

lines that i get while building (win 10 wsl debian)
kek@DESKTOP-5OGGE1L:/mnt/e/youtube-dl-master$ make
mkdir -p zip
for d in youtube_dl youtube_dl/downloader youtube_dl/extractor youtube_dl/postprocessor ; do \
  mkdir -p zip/$d ;\
  cp -pPR $d/*.py zip/$d/ ;\
done
touch -t 200001010101 zip/youtube_dl/*.py zip/youtube_dl/*/*.py
mv zip/youtube_dl/__main__.py zip/
cd zip ; zip -q ../youtube-dl youtube_dl/*.py youtube_dl/*/*.py __main__.py
rm -rf zip
echo '#!/usr/bin/env python' > youtube-dl
cat youtube-dl.zip >> youtube-dl
rm youtube-dl.zip
chmod a+x youtube-dl
/usr/bin/env python devscripts/prepare_manpage.py youtube-dl.1.temp.md
pandoc -s -f markdown-smart -t man youtube-dl.1.temp.md -o youtube-dl.1
rm -f youtube-dl.1.temp.md
/usr/bin/env python devscripts/bash-completion.py
/usr/bin/env python devscripts/zsh-completion.py
/usr/bin/env python devscripts/fish-completion.py

**Comment by KACTbIJIb** [comment]
then i put executable file on server (also debian) and get 
danya@debian:/tmp$ youtube-dl
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/__init__.py", line 4, in                                                                                                                                                              <module>
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 16, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 15, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/options.py", line 8, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/__init__.py", line 23, i                                                                                                                                                             n <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/niconico.py", line 11, i                                                                                                                                                             n <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/__init__.py", line 9, in                                                                                                                                                              <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/extractors.py", line 1617                                                                                                                                                             , in <module>
ImportError: cannot import name 'YoutubeSearchURLIE' from 'youtube_dl.extractor.                                                                                                                                                             youtube' (/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py)
danya@debian:/tmp$

**Comment by dirkf** [comment]
Try `make clean all`.

**Comment by KACTbIJIb** [comment]
root@debian:/tmp# youtube-dl
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/__init__.py", line 4, in                                                                                                                                                              <module>
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 16, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 15, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/options.py", line 8, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/__init__.py", line 23, i                                                                                                                                                             n <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/niconico.py", line 11, i                                                                                                                                                             n <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/__init__.py", line 9, in                                                                                                                                                              <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/extractors.py", line 1617                                                                                                                                                             , in <module>
ImportError: cannot import name 'YoutubeSearchURLIE' from 'youtube_dl.extractor.                                                                                                                                                             youtube' (/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py)

Ive rebuild and upload . error still there

**Comment by pukkandan** [comment]
`ModuleNotFoundError` is a subclass of `ImportError`! OP's issue seems to be that they are mixing extractor files from different commits

**Comment by dirkf** [comment]
So make sure that any existing yt-dl installation or modules on the build machine are removed or hidden from Python before checking out the desired commit and running `make`. Then likewise on the target server.

**Comment by KACTbIJIb** [comment]
thx that helped

**Comment by dirkf** [comment]
So OK to close then?
