### ISSUE TITLE
Getting error Unablr to find video URL

### ISSUE THREAD

**Issue by bagwanwasim01** [ytdl-org/youtube-dl#30955]
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/teachable.py", line 176, in _real_extract
    raise ExtractorError('Unable to find video URL')
youtube_dl.utils.ExtractorError: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by bagwanwasim01** [comment]
I am passing --cookies that i am getting from chrome extension **Get Cookies txt**

**Comment by dirkf** [comment]
You are raising a site support issue. Why not use the template  that has been provided for that? I've edited your issue to include the template. Please complete it as indicated.

**Comment by bagwanwasim01** [comment]
What template I have to include?

**Comment by bagwanwasim01** [comment]
I have completed. Please help me resolve the issue.

**Comment by dirkf** [comment]
And the full log please ... How are we meant to guess what page isn't working?

**Comment by bagwanwasim01** [comment]
youtube-dl -i --cookies cantrill.io_cookies.txt --verbose "https://learn.cantrill.io/courses/730712"

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-i', u'--cookies', u'cantrill.io_cookies.txt', u'--verbose', u'https://learn.cantrill.io/courses/730712']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.17.5-76051705-generic-x86_64-with-Pop-21.10-impish
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 730712: Requesting header
[redirect] Following redirect to https://learn.cantrill.io/courses/enrolled/730712
[generic] 730712: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 730712: Downloading webpage
[generic] 730712: Extracting information
[TeachableCourse] 730712: Downloading webpage
[download] Downloading playlist: AWS Certified Solutions Architect - Associate (SAA-C02 & SAA-C03)
[TeachableCourse] playlist AWS Certified Solutions Architect - Associate (SAA-C02 & SAA-C03): Collected 330 video ids (downloading 330 of them)
[download] Downloading video 1 of 330
[Teachable] 13876041: Downloading webpage
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/teachable.py", line 176, in _real_extract
    raise ExtractorError('Unable to find video URL')
ExtractorError: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[download] Downloading video 2 of 330
[Teachable] 14040874: Downloading webpage
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/teachable.py", line 176, in _real_extract
    raise ExtractorError('Unable to find video URL')
ExtractorError: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[download] Downloading video 3 of 330
[Teachable] 14040865: Downloading webpage
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/teachable.py", line 176, in _real_extract
    raise ExtractorError('Unable to find video URL')
ExtractorError: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


Full logs for the command that I have ran

**Comment by dirkf** [comment]
Please try the same thing but for the page URL of a specific lecture, such as the first one (13876041).

**Comment by bagwanwasim01** [comment]
I tried it for the page URL of specific lecture for e.g. https://learn.cantrill.io/courses/730712/lectures/13876041

Also, tried with --write-pages flag, still the error persist.

**Comment by islamCodehood** [comment]
Have you found a solution, @bagwanwasim01 ?

**Comment by bagwanwasim01** [comment]
No, I haven't. @islamCodehood

**Comment by dirkf** [comment]
Probably the answer is the same as that for #30929, which is that Teachable is using a new video host not yet supported by yt-dl.

Any new information is welcome in that issue.

**Comment by hjoseph96** [comment]
Also running into this issue...

Looks like it's using the Hotmart player, if that means anything.

Using this tool makes life easier, but I suppose we'll have to go one by one
