### ISSUE TITLE
[Go/abc.com] An extractor error has occurred. (caused by KeyError('video',))

### ISSUE THREAD

**Issue by Fetch-user** [ytdl-org/youtube-dl#30964]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ
c:\Tmp>youtube-dl --version
2021.12.17
youtube-dl --verbose -f "[height <=? 720][tbr>1500]" https://abc.com/tv/shows/life-below-zero-next-generation/episode-guide/season-04/episode-12-call-of-the-mountain/vdka27155346  -o "Life Below Zero Next Generation S04E12 Call of the Mountain [ABC].mp4"
## Verbose log

```
PASTE VERBOSE LOG HERE
c:\Tmp>youtube-dl --verbose -f "[height <=? 720][tbr>1500]" https://abc.com/tv/shows/life-below-zero-next-generation/episode-guide/season-04/episode-12-call-of-the-mountain/vdka27155346  -o "Life Below Zero Next Generation S04E12 Call of the Mountain [ABC].mp4"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', '[height <=? 720][tbr>1500]', 'https://abc.com/tv/shows/life-below-zero-next-generation/episode-guide/season-04/episode-12-call-of-the-mountain/vdka27155346', '-o', 'Life Below Zero Next Generation S04E12 Call of the Mountain [ABC].mp4']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-06-12-38737b3, ffprobe git-2020-06-12-38737b3
[debug] Proxy map: {}
[Go] vdka27155346: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('video',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\go.py", line 210, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\go.py", line 156, in _extract_videos
KeyError: 'video'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\go.py", line 210, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\go.py", line 156, in _extract_videos
KeyError: 'video'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 547, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('video',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


c:\Tmp>

```

## Description

WRITE DESCRIPTION HERE youtube-dl fails with the above error

**Comment by 89z** [comment]
Is that a valid link?

> The content you’re looking for is not available.

**Comment by Fetch-user** [comment]
It was at the time I got the url 
Another one that WAS there is now gone .... note all the other downloads for (both) series worked. 😊

Title Port Protection Alaska S05E12

youtube-dl -f "[height <=? 720][tbr>1500]" https://abc.com/tv/shows/port-protection-alaska/episode-guide/season-05/episode-12-through-hell-or-high-water/vdka27169904 -o "Port Protection Alaska S05E12 Through Hell or High Water [ABC].mp4"
Title Life Below Zero Next Generation 12

youtube-dl -f "[height <=? 720][tbr>1500]" https://abc.com/tv/shows/life-below-zero-next-generation/episode-guide/season-04/episode-12-call-of-the-mountain/vdka27155346  -o "Life Below Zero Next Generation S04E12 Call of the Mountain [ABC].mp4"

Regards,
Mark
(Good judgment comes from experience; experience comes from bad judgment.)

**Comment by 89z** [comment]
please stop pasting dead links...

**Comment by dirkf** [comment]
The Go extractor could provide a better diagnostic. If there is enough information in the URL to find the video using http://api.contents.watchabc.go.com, the page isn't checked: then the empty metadata returned for the video causes the posted diagnostic.

Let's update PR #30649:
```ShellSession
$ python -m youtube_dl -F -v 'https://abc.com/tv/shows/life-below-zero-next-generation/episode-guide/season-04/episode-12-call-of-the-mountain/vdka27155346'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'-v', u'https://abc.com/tv/shows/life-below-zero-next-generation/episode-guide/season-04/episode-12-call-of-the-mountain/vdka27155346']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: ce49654dd
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[Go] vdka27155346: Downloading JSON metadata
ERROR: Go said: vdka27155346: No video found
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "youtube_dl/extractor/go.py", line 286, in _real_extract
    self._raise_extractor_error(video_id, 'No video found')
  File "youtube_dl/extractor/go.py", line 220, in _raise_extractor_error
    raise ExtractorError('%s said: %s: %s' % (self.IE_NAME, video_id, msg), expected=expected)
ExtractorError: Go said: vdka27155346: No video found

$ 
```

**Comment by Fetch-user** [comment]
Thanks for all your help :)
ABC was a bit slow to remove the links
