### ISSUE TITLE
Vk.com Not working anymore 

### ISSUE THREAD

**Issue by publicShield1** [ytdl-org/youtube-dl#30972]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-o', 'v01.mp4', '--cookies', 'cookies.txt', 'https://vk.com/video/tourisme?z=video-98811431_456239905%2Fpl_cat_trends', '--ffmpeg-location', 'C:\\Users\\ffmpeg.exe']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
[vk] -98811431_456239905: Downloading JSON metadata
ERROR: -98811431_456239905: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 906, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 906, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\vk.py", line 325, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\vk.py", line 70, in _download_payload
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 899, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 883, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 910, in _parse_json
youtube_dl.utils.ExtractorError: -210693141_456239793: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Lost support for vk.vom
Issue with  _download_payload in vk.py
Vk.com must have changed something with their log in because its pulling html as the payload.

**Comment by LandisTwo** [comment]
VK has been converting to a 'blob' steaming system.
less and less content is being streamed as an mpeg : (

**Comment by dirkf** [comment]
WFM:
```ShellSession
$ python -m youtube_dl -v -F 'https://vk.com/video/tourisme?z=video-98811431_456239905%2Fpl_cat_trends'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://vk.com/video/tourisme?z=video-98811431_456239905%2Fpl_cat_trends']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 73771cd76
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[vk] -98811431_456239905: Downloading JSON metadata
[vk] -98811431_456239905: Downloading m3u8 information
[info] Available formats for -98811431_456239905:
format code  extension      resolution note
url240       unknown_video  240p       
url360       unknown_video  360p       
url480       unknown_video  480p       
url720       unknown_video  720p       
hls-220      mp4            256x144     220k , 30.0fps
hls-459      mp4            426x240     459k , 30.0fps
hls-921      mp4            640x360     921k , 30.0fps
hls-1535     mp4            852x480    1535k , 30.0fps
hls-2729     mp4            1280x720   2729k , 30.0fps (best)
$
```
(and downloads with eg `-f url240`).

**Comment by publicShield1** [comment]
Thanks. This appears to be working now. Not sure what changed though.

**Comment by dirkf** [comment]
Feel free to close the issue before I do, then. I'm leaving it for a while in case of re-occurrence.

**Comment by publicShield1** [comment]
Working now
