### ISSUE TITLE
Intermittent Error: "Failed to parse JSON Unterminated string starting at: line 1 column" ; "The following content has been identified by the YouTube community as inappropriate..."

### ISSUE THREAD

**Issue by jiveandwail** [ytdl-org/youtube-dl#30988]
- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

youtube-dl -s -v https://www.youtube.com/watch?v=L4nyWlYga_w

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-s', '-v', 'https://www.youtube.com/watch?v=L4nyWlYga_w']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-113-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube] L4nyWlYga_w: Downloading webpage
WARNING: [youtube] L4nyWlYga_w: Failed to parse JSON Unterminated string starting at: line 1 column 52939 (char 52938)
[youtube] L4nyWlYga_w: Downloading API JSON
ERROR: The following content has been identified by the YouTube community as inappropriate or offensive to some audiences.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1731, in _real_extract
    raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: The following content has been identified by the YouTube community as inappropriate or offensive to some audiences.

this error occurs intermittently on videos placed in "Limited State", like above.

other examples:
youtube-dl -s -v https://www.youtube.com/watch?v=QVw4oV8ECaY
youtube-dl -s -v https://www.youtube.com/watch?v=k2zf5dpTZws

**Comment by 89z** [comment]
Issue should be closed:

> What is a holocaust? "It's a mental illness."

**Comment by dirkf** [comment]
In all cases I get (UK):
```
ERROR: Video unavailable
This content is not available on this country domain.
```

**Comment by coletdjnz** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30987#issuecomment-1140642230

**Comment by dirkf** [comment]
I'll assume that the fix for #30987 will sort this. The issue will be closed when that fix is merged. If it then reappears, please open a new issue referencing this.
