### ISSUE TITLE
Afreecatv not working

### ISSUE THREAD

**Issue by irjowo99** [ytdl-org/youtube-dl#30984]
## Checklist

- [x ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

C:\Users\Owner\Downloads>youtube-dl https://vod.afreecatv.com/player/87524568
[generic] 87524568: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 87524568: Downloading webpage
[generic] 87524568: Extracting information
ERROR: Unsupported URL: https://vod.afreecatv.com/player/87524568

C:\Users\Owner\Downloads>youtube-dl https://vod.afreecatv.com/player/87524568 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vod.afreecatv.com/player/87524568', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 87524568: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 87524568: Downloading webpage
[generic] 87524568: Extracting information
ERROR: Unsupported URL: https://vod.afreecatv.com/player/87524568
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\generic.py", line 3489, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://vod.afreecatv.com/player/87524568

## Description

Trying to download videos from afreecatv is not working at this time.

**Comment by dirkf** [comment]
The extractor expects VOD URLs to look like https://vod.afreecatv.com/PLAYER/STATION/nnnn. Replace `/player/` by `/PLAYER/STATION/` in your URLs to work around this.

This patch addresses the problem:
```py
--- old/youtube-dl/youtube_dl/extractor/afreecatv.py
+++ new/youtube-dl/youtube_dl/extractor/afreecatv.py
@@ -26,7 +26,7 @@
                                 /app/(?:index|read_ucc_bbs)\.cgi|
                                 /player/[Pp]layer\.(?:swf|html)
                             )\?.*?\bnTitleNo=|
-                            vod\.afreecatv\.com/PLAYER/STATION/
+                            vod\.afreecatv\.com/(?:PLAYER/STATION|player)/
                         )
                         (?P<id>\d+)
                     '''
```

**Comment by dirkf** [comment]
See also https://github.com/yt-dlp/yt-dlp/issues/3151.

Note that the patch can't easily be applied if you have a single-file `youtube-dl.exe` on Windows. Install Python 3 and use _pip_ to install from the master branch here; then apply the patch; or wait for a new release.

**Comment by irjowo99** [comment]
I manually inserted /PLAYER/STATION/ and it works now! Thanks!

**Comment by dirkf** [comment]
Keeping this open until the future PR based on the above commit is merged.
