### ISSUE TITLE
youtube channel with name in Russian lang

### ISSUE THREAD

**Issue by xoid** [ytdl-org/youtube-dl#31008]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[PASTE VERBOSE LOG HERE]
[root@avy sapojnik]# locale
LANG=en_US.UTF-8
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=ru_RU.UTF-8

[root@avy sapojnik]# youtube-dl 'https://www.youtube.com/c/АлексейРощин' --verbose --write-pages --print-traffic
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/c/АлексейРощин', '--verbose', '--write-pages', '--print-traffic']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: b03c5e1
[debug] Python version 3.6.8 (CPython) - Linux-5.4.17-2136.301.1.4.el7uek.x86_64-x86_64-with-oracle-7.9
[debug] exe versions: avconv 12.3, avprobe 12.3
[debug] Proxy map: {}
[youtube:tab] АлексейРощин: Downloading webpage
send: b'GET /c/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9%D0%A0%D0%BE%D1%89%D0%B8%D0%BD HTTP/1.1\r\nHost: www.youtube.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3584.0 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 302 Found\r\n'
header: Content-Type: application/binary
header: X-Content-Type-Options: nosniff
header: Cache-Control: no-cache, no-store, max-age=0, must-revalidate
header: Pragma: no-cache
header: Expires: Mon, 01 Jan 1990 00:00:00 GMT
header: Date: Mon, 06 Jun 2022 08:41:42 GMT
header: Location: https://consent.youtube.com/m?continue=https%3A%2F%2Fwww.youtube.com%2Fc%2F%25D0%2590%25D0%25BB%25D0%25B5%25D0%25BA%25D1%2581%25D0%25B5%25D0%25B9%25D0%25A0%25D0%25BE%25D1%2589%25D0%25B8%25D0%25BD%3Fcbrd%3D1&gl=DE&m=0&pc=yt&uxe=eomty&hl=en&src=1
header: Strict-Transport-Security: max-age=31536000
header: X-Frame-Options: SAMEORIGIN
header: Cross-Origin-Opener-Policy-Report-Only: same-origin-allow-popups; report-to="youtube_main"
header: Accept-CH: Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Model, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version
header: Vary: Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Model, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version
header: Permissions-Policy: ch-ua-arch=*, ch-ua-bitness=*, ch-ua-full-version=*, ch-ua-full-version-list=*, ch-ua-model=*, ch-ua-platform=*, ch-ua-platform-version=*
header: Report-To: {"group":"youtube_main","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/youtube_main"}]}
header: P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
header: Server: ESF
header: Content-Length: 0
header: X-XSS-Protection: 0
header: Set-Cookie: YSC=SYqYq0CIYws; Domain=.youtube.com; Path=/; Secure; HttpOnly; SameSite=none
header: Set-Cookie: YSC=SYqYq0CIYws; Domain=.youtube.com; Path=/; Secure; HttpOnly; SameSite=none
header: Set-Cookie: YSC=SYqYq0CIYws; Domain=.youtube.com; Path=/; Secure; HttpOnly; SameSite=none
header: Set-Cookie: YSC=SYqYq0CIYws; Domain=.youtube.com; Path=/; Secure; HttpOnly; SameSite=none
header: Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
header: Connection: close
send: b'GET /m?continue=https%3A%2F%2Fwww.youtube.com%2Fc%2F%25D0%2590%25D0%25BB%25D0%25B5%25D0%25BA%25D1%2581%25D0%25B5%25D0%25B9%25D0%25A0%25D0%25BE%25D1%2589%25D0%25B8%25D0%25BD%3Fcbrd%3D1&gl=DE&m=0&pc=yt&uxe=eomty&hl=en&src=1 HTTP/1.1\r\nHost: consent.youtube.com\r\nCookie: CONSENT=PENDING+937; YSC=SYqYq0CIYws; __Secure-YEC=CgtDNC1FUVRXbnRuUSjG-_aUBg%3D%3D\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3584.0 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: text/html; charset=utf-8
header: Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site
header: x-ua-compatible: IE=edge
header: Cache-Control: no-cache, no-store, max-age=0, must-revalidate
header: Pragma: no-cache
header: Expires: Mon, 01 Jan 1990 00:00:00 GMT
header: Date: Mon, 06 Jun 2022 08:41:42 GMT
header: Cross-Origin-Opener-Policy: unsafe-none; report-to="ConsentUi"
header: Report-To: {"group":"ConsentUi","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/ConsentUi/external"}]}
header: Permissions-Policy: ch-ua-arch=*, ch-ua-bitness=*, ch-ua-full-version=*, ch-ua-full-version-list=*, ch-ua-model=*, ch-ua-platform=*, ch-ua-platform-version=*
header: Accept-CH: Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Model, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version
header: Content-Security-Policy: require-trusted-types-for 'script';report-uri /_/ConsentUi/cspreport
header: Content-Security-Policy: require-trusted-types-for 'script';report-uri /_/ConsentUi/cspreport
header: Content-Security-Policy: require-trusted-types-for 'script';report-uri /_/ConsentUi/cspreport
header: Cross-Origin-Resource-Policy: same-site
header: Content-Encoding: gzip
header: Server: ESF
header: X-XSS-Protection: 0
header: X-Frame-Options: SAMEORIGIN
header: X-Content-Type-Options: nosniff
header: Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
header: Connection: close
header: Transfer-Encoding: chunked
[youtube:tab] Saving request to https_-_consent.youtube.com_mcontinue=https%3A%2F%2Fwww.youtube.com%2Fc%2F%25D0%2590%25D0%25BB%25D0%25B5%25D0%25BA%25D1%2581%25D0%25B5%25D0%25B9%25D0%25A0%25D0%25BE%25D1%2589%25D0%25B8%25D0%2_b9eb0e93693f85956593727a082ddcab.dump
ERROR: Unable to extract yt initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 2841, in _real_extract
    data = self._extract_yt_initial_data(item_id, webpage)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 301, in _extract_yt_initial_data
    self._YT_INITIAL_DATA_RE), webpage, 'yt initial data'),
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract yt initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

## Description

WRITE DESCRIPTION HERE

**Comment by xoid** [comment]
dump file content is cookie accept banner in Russian. Should youtube-dl accept it automatically?

**Comment by xoid** [comment]
[dump.html.txt](https://github.com/ytdl-org/youtube-dl/files/8843136/dump.html.txt)

**Comment by dirkf** [comment]
Two work-arounds:
* encode the URL https://www.youtube.com/c/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9%D0%A0%D0%BE%D1%89%D0%B8%D0%BD
 solutions
* manually send the consent cookie: `--add-header 'Cookie:CONSENT=YES+cb.20210328-17-p0.en+FX+232'`

And one (temporary?) solution:
* https://github.com/yt-dlp/yt-dlp/commit/d2558234cf5dd12d6896eed5427b7dcdb3ab7b5a

That will be pushed to yt-dl shortly.
