### ISSUE TITLE
viki.com got 422 http error

### ISSUE THREAD

**Issue by tia3** [ytdl-org/youtube-dl#31015]
## Checklist

- [ x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
c:\Users\user\Downloads\youtube>youtube-dl.exe https://www.viki.com/videos/1166283v-beautiful-reborn-flower-episode-1 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.viki.com/videos/1166283v-beautiful-reborn-flower-episode-1', '--verbose']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-99707-g2b702015d8, ffprobe N-99707-g2b702015d8
[debug] Proxy map: {}
[viki] 1166283v: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 422: Unprocessable Entity (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default


c:\Users\user\Downloads\youtube>455872
```

## Description

viki.com video got a http 422 error. Don't know why, could you please help how to fix this?
May I miss anything? Site working via chrome. Youtube-dl is working with different hosts.

**Comment by dirkf** [comment]
I've no idea what's giving 422, but as far as I know all Viki downloads are encrypted and not accessible to yt-dl as below:
```shellsession
$ python -m youtube_dl -F -v 'https://www.viki.com/videos/1166283v-beautiful-reborn-flower-episode-1'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'-v', u'https://www.viki.com/videos/1166283v-beautiful-reborn-flower-episode-1']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: ef044be34
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[viki] 1166283v: Downloading video JSON
[viki] 1166283v: Downloading video streams JSON
[viki] 1166283v: Downloading initial MPD manifest
[viki] 1166283v: Downloading MPD manifest
WARNING: [viki] Unknown MIME type image/jpeg in DASH manifest
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "youtube_dl/extractor/viki.py", line 288, in _real_extract
    self._sort_formats(formats)
  File "youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$
```

**Comment by 89z** [comment]
Not sure if this is on topic, but this is the Widevine key for this video:

~~~
c723f9654472964cde176bd2d17d69b0
~~~

**Comment by 89z** [comment]
Here is a command to download the video:

~~~
ffmpeg -cenc_decryption_key c723f9654472964cde176bd2d17d69b0 `
-i 'https://manifest-viki.viki.io/v1/1166283v/limelight/main/mpd/normal/viki/high/sd/ww/dt2_dt3/manifest.mpd?tag=mpdhd%3Ahigh%3Aww%3AsourceVIKI%3Ampd%3Acached%3Adt2_dt3&app=100000a&h_country=us&h_data_center=scr-2&h_host=playback-streams-db49cd5ff-m9ktz&h_timestamp=1654804383&sig=a263f53087d273fc4448339fdd58d21021c65307' `
-c copy -map 0:0 dec.mp4
~~~

**Comment by dirkf** [comment]
Be that as it may, yt-dl's position is that DRM files are only useful for disk stress testing, etc, and so they aren't downloaded. In case anyone wants to _research_ a particular file, the `--allow-unplayable-formats` yt-dlp option may be relevant.

**Comment by 89z** [comment]
@dirkf the above seems pretty innocent. I think if FFmpeg allows it, then YouTube-DL should be safe, as long as its implemented in a similar manner, where the user must provide the key. YouTube-DL is already decrypting some items in a similar fashion:

https://github.com/ytdl-org/youtube-dl/blob/5208ae92fc3e2916cdccae45c6b9a516be3d5796/youtube_dl/downloader/hls.py#L187-L199

only difference would be user providing key, instead of YouTube-DL extracting the key.

**Comment by issues101** [comment]
I get the same error trying to download a Viki video that I was able to download last year. Viki seems to have started using DRM recently. Viki should probably be removed from the supported sites list, since it's no longer possible to download anything from it. You can use StreamFab instead, if you don't mind paying....

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31049
