### ISSUE TITLE
ApplePodcasts: Unable to extract ember data

### ISSUE THREAD

**Issue by y0shir** [ytdl-org/youtube-dl#31017]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl --verbose "https://podcasts.apple.com/us/podcast/retronauts-episode-459-sonic-the-hedgehog-comics/id672857593?i=1000565401846"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://podcasts.apple.com/us/podcast/retronauts-episode-459-sonic-the-hedgehog-comics/id672857593?i=1000565401846']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.4 (CPython) - Linux-5.17.0-1-amd64-x86_64-with-glibc2.33
[debug] exe versions: none
[debug] Proxy map: {}
[ApplePodcasts] 1000565401846: Downloading webpage
ERROR: Unable to extract ember data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ivan/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ivan/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/ivan/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/ivan/.local/lib/python3.10/site-packages/youtube_dl/extractor/applepodcasts.py", line 42, in _real_extract
    ember_data = self._parse_json(self._search_regex(
  File "/home/ivan/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract ember data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I don't like DRM, so I tried to download podcast by using youtube-dl. As a result i got an error and was told to file and issue

**Comment by dirkf** [comment]
Also to 
>[ x] I've searched the bugtracker for similar issues including closed ones

This issue is fixed in the git master which you can [install using _pip_](https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/) from this repo.

Duplicate of #30216.
