### ISSUE TITLE
latin-1 codec can't encode character in title - UnicodeEncodeError

### ISSUE THREAD

**Issue by matt-matt1** [ytdl-org/youtube-dl#31014]
Some people post videos with emoji's in the title.  This causes youtube-dl to fail.
Here's an example:

[youtube] 7DeWifJOoWI: Downloading webpage
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 33, in <module>
    sys.exit(load_entry_point('youtube-dl==2021.6.6', 'console_scripts', 'youtube-dl')())
  File "/usr/lib/python3/dist-packages/youtube_dl/__init__.py", line 479, in main
    _real_main(argv)
  File "/usr/lib/python3/dist-packages/youtube_dl/__init__.py", line 469, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 847, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 933, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 1067, in __process_playlist
    entry_result = self.__process_iterable_entry(entry, download, extra)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 1076, in __process_iterable_entry
    return self.process_ie_result(
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 885, in process_ie_result
    return self.extract_info(ie_result['url'],
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 847, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 881, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 1692, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 1976, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "/usr/lib/python3/dist-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3/dist-packages/youtube_dl/downloader/http.py", line 352, in real_download
    return download()
  File "/usr/lib/python3/dist-packages/youtube_dl/downloader/http.py", line 259, in download
    ctx.stream, ctx.tmpfilename = sanitize_open(
  File "/usr/lib/python3/dist-packages/youtube_dl/utils.py", line 2055, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u3010' in position 0: ordinal not in range(256)

So while trying to download 25 videos (in the list), video 3 had a non-latin character in the title and so youtube-dl just stopped.  Now the only way, that I know of, is to manually download each with -o with a latin-1 charset name.

**Comment by dirkf** [comment]
Please post the **entire** verbose log. You can edit it into the original post. Use triple backquotes around it for formatting.

The full log shows the options, config settings, version, OS, etc and not just the final problem.

Meanwhile, `--restrict-filenames` works around your issue.

**Comment by dirkf** [comment]
WFM:
```shellsession
$ python -m youtube_dl -v --test '7DeWifJOoWI'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--test', u'7DeWifJOoWI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 14a087ec6
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] 7DeWifJOoWI: Downloading webpage
[debug] [youtube] Decrypted nsig bd192P5_MMEt7MTXTMb- => uhk4ttH9fuqXFw
[debug] [youtube] Decrypted nsig aFBdarCP31VZJfGuLhx2 => Sy0LtBvfVNmoIg
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://rr4---sn-cu-aigss.googlevideo.com/videoplayback?sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&fexp=24001373%2C24007246&ei=xJ2gYqfYN96Lp-oP8eG9qAg&ip=51.6.64.191&clen=202236959&spc=4ocVCwbPdIps4yCK84n00vLWodJdPaI&id=o-AC-BkyLQyWe8x7YIQjOdMdinuIVsUPu1QlMUasjXiKb0&txp=5535432&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&gir=yes&requiressl=yes&keepalive=yes&source=youtube&sig=AOq0QJ8wRQIhAJJe_L4S7XVlTVCSKg6gHmV40NAdHYfVG7r3zN7Y-fX5AiAEJN9gY7eDHIZJCPBZrUb-FclS3Rbt-B21ViQU4XKJew%3D%3D&pcm2cms=yes&dur=718.551&ns=GFwkTzoub-vrp887MdVyyD4G&initcwndbps=1281250&vprv=1&lsig=AG3C_xAwRQIhAOmdncZhdFr6eMQh6iqOdLFnvze32QQVasWisWcOoeL5AiAE6frryeoGBcxxzl5025nnglmLNtWN4y6bLqhXDPVpGA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lmt=1595755313698160&c=WEB&expire=1654714917&mime=video%2Fwebm&fvip=4&itag=248&mm=31%2C29&mn=sn-cu-aigss%2Csn-cu-c9is&mh=Ax&n=uhk4ttH9fuqXFw&mt=1654693032&mv=m&pl=26&ms=au%2Crdu&mvi=4'
[download] Destination: 【200万再生】1週間で激変！目の下のたるみをとるマッサージ＆エクササイズ夜の美顔ヨガ-7DeWifJOoWI.f248.webm
[download] 100% of 10.00KiB in 00:00
[debug] Invoking downloader on u'https://rr4---sn-cu-aigss.googlevideo.com/videoplayback?sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&fexp=24001373%2C24007246&ei=xJ2gYqfYN96Lp-oP8eG9qAg&ip=51.6.64.191&clen=12091578&spc=4ocVCwbPdIps4yCK84n00vLWodJdPaI&id=o-AC-BkyLQyWe8x7YIQjOdMdinuIVsUPu1QlMUasjXiKb0&txp=5531432&gir=yes&requiressl=yes&keepalive=yes&source=youtube&sig=AOq0QJ8wRQIgCUs5iJ6FDpRqACGnKOXKR8_Xpo2cQRBiLOriObDDRPwCIQCQLPhI8gNL7s3hUr7aFfiu5-U7JccReO7JZ7KFALUk6g%3D%3D&pcm2cms=yes&dur=718.581&ns=GFwkTzoub-vrp887MdVyyD4G&initcwndbps=1281250&vprv=1&lsig=AG3C_xAwRQIhAOmdncZhdFr6eMQh6iqOdLFnvze32QQVasWisWcOoeL5AiAE6frryeoGBcxxzl5025nnglmLNtWN4y6bLqhXDPVpGA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lmt=1595753902107358&c=WEB&expire=1654714917&mime=audio%2Fwebm&fvip=4&itag=251&mm=31%2C29&mn=sn-cu-aigss%2Csn-cu-c9is&mh=Ax&n=uhk4ttH9fuqXFw&mt=1654693032&mv=m&pl=26&ms=au%2Crdu&mvi=4'
[download] Destination: 【200万再生】1週間で激変！目の下のたるみをとるマッサージ＆エクササイズ夜の美顔ヨガ-7DeWifJOoWI.f251.webm
[download] 100% of 10.00KiB in 00:00
[ffmpeg] Merging formats into "【200万再生】1週間で激変！目の下のたるみをとるマッサージ＆エクササイズ夜の美顔ヨガ-7DeWifJOoWI.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:【200万再生】1週間で激変！目の下のたるみをとるマッサージ＆エクササイズ夜の美顔ヨガ-7DeWifJOoWI.f248.webm' -i 'file:【200万再生】1週間で激変！目の下のたるみをとるマッサージ＆エクササイズ夜の美顔ヨガ-7DeWifJOoWI.f251.webm' -c copy -map '0:v:0' -map '1:a:0' 'file:【200万再生】1週間で激変！目の下のたるみをとるマッサージ＆エクササイズ夜の美顔ヨガ-7DeWifJOoWI.temp.webm'
Deleting original file 【200万再生】1週間で激変！目の下のたるみをとるマッサージ＆エクササイズ夜の美顔ヨガ-7DeWifJOoWI.f248.webm (pass -k to keep)
Deleting original file 【200万再生】1週間で激変！目の下のたるみをとるマッサージ＆エクササイズ夜の美顔ヨガ-7DeWifJOoWI.f251.webm (pass -k to keep)
$
```

**Comment by matt-matt1** [comment]
> youtube-dl -f 22 https://www.youtube.com/watch\?v\=7DeWifJOoWI -v
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '22', 'https://www.youtube.com/watch?v=7DeWifJOoWI', '-v']
[debug] Encodings: locale ISO-8859-1, fs iso8859-1, out iso8859-1, pref ISO-8859-1
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.2 (CPython) - Linux-5.15.32-v8+-aarch64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 7DeWifJOoWI: Downloading webpage
[debug] Invoking downloader on 'https://rr8---sn-cxaaj5o5q5-tt1y.googlevideo.com/videoplayback?expire=1654812906&ei=ihyiYp_ICpaUlu8Pqf2-0AQ&ip=184.146.215.158&id=o-AEjlsBiAEapevecPUkUztdQlKMWeIsmG63QheyRbP0x2&itag=22&source=youtube&requiressl=yes&mh=Ax&mm=31%2C26&mn=sn-cxaaj5o5q5-tt1y%2Csn-vgqsrnsr&ms=au%2Conr&mv=m&mvi=8&pl=24&initcwndbps=1285000&spc=4ocVCz8dK3wtG36noZpY9YdBGAtO7g0&vprv=1&mime=video%2Fmp4&ns=of_hrJ2BMmvsGeXvO7-MOIoG&cnr=14&ratebypass=yes&dur=718.611&lmt=1595754437235052&mt=1654790942&fvip=2&fexp=24001373%2C24007246&c=WEB&txp=5535432&n=FoYUCxavUU2LqHX80&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgIzCQ34DgU6Pq9AzHVjsgBDOHJZYVCVk_pnTbc4o4Kv4CIEU-Uhwo_CvPPT9Wux37Ky2OaPRdnv9JlRQLUC4xXrzi&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAN4yd2qd4V3HXILsNL0gN3CdSLzrXVZG_OO8bduSmTr4AiEA2QJ8bCcvjYl-aI4gZgXJh3bXu0dpMFGBh1Bnw2vci2o%3D'
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 33, in <module>
    sys.exit(load_entry_point('youtube-dl==2021.6.6', 'console_scripts', 'youtube-dl')())
  File "/usr/lib/python3/dist-packages/youtube_dl/__init__.py", line 479, in main
    _real_main(argv)
  File "/usr/lib/python3/dist-packages/youtube_dl/__init__.py", line 469, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 847, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 881, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 1692, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 1976, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "/usr/lib/python3/dist-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3/dist-packages/youtube_dl/downloader/http.py", line 352, in real_download
    return download()
  File "/usr/lib/python3/dist-packages/youtube_dl/downloader/http.py", line 259, in download
    ctx.stream, ctx.tmpfilename = sanitize_open(
  File "/usr/lib/python3/dist-packages/youtube_dl/utils.py", line 2055, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u3010' in position 0: ordinal not in range(256)

```

**Comment by matt-matt1** [comment]
I will try to make the OS USE UTF8...
But these characters are not needed at all - the video author just wanted to add "sparkle" to their posts.  So I'd like it to save the title as only A-Z, a-z and 0-9 and common ASCII symbols (or whatever) etc.

**Comment by dirkf** [comment]
Just what `--restrict-filenames` does ... (RTFM).

**Comment by matt-matt1** [comment]
I beg to differ - the filename was like 'OK.mp4' and I needed to rename it manually.  And there is no need to imply obscene language!

**Comment by dirkf** [comment]
Read The Fine Manual, obvs. People write the documentation for a reason, you know.

To debug the issue with your filename you'd have to provide more details. I'd just show this example using the link you posted earlier (Linux UTF-8):
```shellsession
$ python -m youtube_dl --get-filename -f 22 'https://www.youtube.com/watch?v=7DeWifJOoWI'
【200万再生】1週間で激変！目の下のたるみをとるマッサージ＆エクササイズ夜の美顔ヨガ-7DeWifJOoWI.mp4
$ python -m youtube_dl --get-filename --restrict-filenames -f 22 'https://www.youtube.com/watch?v=7DeWifJOoWI'
200_1-7DeWifJOoWI.mp4
$
```
