### ISSUE TITLE
[SevenPlus] "Video not playable"??

### ISSUE THREAD

**Issue by FlaminHat** [ytdl-org/youtube-dl#31038]
What is going on when youtube-dl says the video is "unplayable" and doesn't try to download the video?

```shellsession
youtube-dl -v --no-check-certificate https://7plus.com.au/highway-patrol?episode-id=HWYP11-007 -o "Highway Patrol HWYP11-007.mp4"
---------This is what it said:-----------
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-check-certificate', 'https://7plus.com.au/highway-patrol?episode-id=HWYP11-007', '-o', 'Highway Patrol HWYP11-007.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.6.8 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[7plus] HWYP11-007: Downloading JSON metadata
ERROR: VIDEO_NOT_PLAYABLE
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/sevenplus.py", line 57, in _real_extract
    'videoType': 'vod',
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 899, in _download_json
    expected_status=expected_status)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 877, in _download_json_handle
    expected_status=expected_status)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/adobepass.py", line 1337, in _download_webpage_handle
    *args, **compat_kwargs(kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 667, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 652, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/sevenplus.py", line 57, in _real_extract
    'videoType': 'vod',
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 899, in _download_json
    expected_status=expected_status)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 877, in _download_json_handle
    expected_status=expected_status)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/adobepass.py", line 1337, in _download_webpage_handle
    *args, **compat_kwargs(kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 667, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 652, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/sevenplus.py", line 62, in _real_extract
    e.cause.read().decode(), episode_id)[0]['error_code'], expected=True)
youtube_dl.utils.ExtractorError: VIDEO_NOT_PLAYABLE
```

**Comment by dirkf** [comment]
This is a message passed directly from the API (https://videoservice.swm.digital/playback) used by the extractor when it returns a 403 Forbidden response.

The extractor's test video gets the same thing, indicating that some more general breakage may be present.

**Comment by gamer191** [comment]
> Is it possible that the site has implemented some geo-restriction that attempts to block access from outside Oz?

That's possible. I live in Australia, so I'll test it later today :)

**Comment by gamer191** [comment]
Technically youtube-dl should redirect to the latest episode, in line with the site behaviour, but I don't think anyone expects that

**Comment by gamer191** [comment]
by the way, youtube-dl's test video is long gone from 7Plus's website

**Comment by dirkf** [comment]
[Wikipedia says](https://en.wikipedia.org/w/index.php?title=List_of_Highway_Patrol_(Australian_TV_series)_episodes&section=13#Season_11_(2019)):
>... "Stolen Getaway"	30 October 2019

Isn't it just that the page is supposed to be showing S11E07 and so it omits that from the list of S11 episodes? Or is that screenshot of the entire series page?

**Comment by gamer191** [comment]
> Isn't it just that the page is supposed to be showing S11E07 and so it omits that from the list of S11 episodes?

Nah, it's identical for https://7plus.com.au/highway-patrol?episode-id=HWYP11-008 and https://7plus.com.au/highway-patrol?episode-id=HWYP11-009 etc. I don't know why that episode has been removed, but season 8's page (which shows episode 2 and 3 expiring soon, and 5 missing all together) gives me the impression that that website just removes random episodes at random times (perhaps they're clearing up storage)
![season 8's page](https://user-images.githubusercontent.com/83270075/174857066-65bab98c-fc12-4fb0-816d-c7b844af434c.png)
