### ISSUE TITLE
Udemy 'ERROR: No video formats found' issue

### ISSUE THREAD

**Issue by liamlacey** [ytdl-org/youtube-dl#31048]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.udemy.com/logic-pro-x-mixing-course/', '--cookies', '/Users/Liam/Desktop/udemy_cookies.txt', '-o', '%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s', '--playlist-start', '5', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 9a591af
[debug] Python version 3.10.4 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2, rtmpdump 2.4
[debug] Proxy map: {}
[udemy:course] logic-pro-x-mixing-course: Downloading webpage
[udemy:course] 2574866: Downloading course curriculum
[download] Downloading playlist: 2574866
[udemy:course] playlist 2574866: Collected 61 video ids (downloading 57 of them)
[download] Downloading video 1 of 57
[udemy] 16329090: Downloading webpage
[udemy] 16329090: Downloading lecture JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/udemy.py", line 408, in _real_extract
    self._sort_formats(formats, field_preference=('height', 'width', 'tbr', 'format_id'))
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
## Description

Attempting to download a certain course from Udemy.
The first 4 videos download fine, but the 5th and onwards videos produce the same error.
All videos are working if played from the browser.

**Comment by dirkf** [comment]
Check video 5 in the browser with DRM disabled. Or did you solve the problem?
