### ISSUE TITLE
[YouTube] Cannot download 

### ISSUE THREAD

**Issue by ZhengdiYu** [ytdl-org/youtube-dl#31052]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[youtube] fqps4pWMTM4: Downloading webpage
[youtube] fqps4pWMTM4: Downloading player 9c24c545
ERROR: fqps4pWMTM4: Traceback (most recent call last):
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/youtube.py", line 1434, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/youtube.py", line 1407, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/youtube.py", line 1394, in _extract_n_function_name
    return self._search_regex(
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(base) [root@VM-142-143-centos youtube_3d_hands]# ping youtube.com
PING youtube.com (103.200.30.143) 56(84) bytes of data.

^C
--- youtube.com ping statistics ---
9 packets transmitted, 0 received, 100% packet loss, time 8187ms

(base) [root@VM-142-143-centos youtube_3d_hands]# youtube-dl -v https://www.youtube.com/watch?v=fqps4pWMTM4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=fqps4pWMTM4']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.7 (CPython) - Linux-5.4.32-1-tlinux4-0001-x86_64-with-glibc2.28
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] fqps4pWMTM4: Downloading webpage
[youtube] fqps4pWMTM4: Downloading player 9c24c545
ERROR: fqps4pWMTM4: Traceback (most recent call last):
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/youtube.py", line 1434, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/youtube.py", line 1407, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/youtube.py", line 1394, in _extract_n_function_name
    return self._search_regex(
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/youtube.py", line 1434, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/youtube.py", line 1407, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/youtube.py", line 1394, in _extract_n_function_name
    return self._search_regex(
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/youtube.py", line 1434, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/youtube.py", line 1407, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/youtube.py", line 1394, in _extract_n_function_name
    return self._search_regex(
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/youtube.py", line 1866, in _real_extract
    self._unthrottle_format_urls(video_id, player_url, formats)
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/youtube.py", line 1451, in _unthrottle_format_urls
    n_response = self._n_descramble(n_param, player_url, video_id)
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/youtube.py", line 1441, in _n_descramble
    raise ExtractorError(traceback.format_exc(), cause=e, video_id=video_id)
youtube_dl.utils.ExtractorError: fqps4pWMTM4: Traceback (most recent call last):
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/youtube.py", line 1434, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/youtube.py", line 1407, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/youtube.py", line 1394, in _extract_n_function_name
    return self._search_regex(
  File "/apdcephfs/private_zhengdiyu/miniconda3/lib/python3.9/site-packages/youtube_dl-2021.12.17-py3.9.egg/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

**Comment by ZhengdiYu** [comment]
Also, I couldn't uninstall or update as well. 

`youtube-dl -U` will return :`It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.`

`yum remove -y youtube-dl` will return :
```
No match for argument: youtube-dl
No packages marked for removal.
Dependencies resolved.
Nothing to do.
Complete!
```

**Comment by dirkf** [comment]
If you'd installed with _yum_ I'd expect the installation to be under `.../dist-packages/`. The `.../site-packages/` path is characteristic of _pip_.

Otherwise, duplicate of #30856. The problem in your log is fixed in the git master. You can install that using _pip_, something like
To get a working up-to-date yt-dl with your configuration, do something like this:
```
python3 -m pip install --system 'https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.tar.gz'
```
See also https://github.com/ytdl-org/youtube-dl/issues/30871#issuecomment-1102666158.

**Comment by ZhengdiYu** [comment]
Thanks for your reply! After running the command above, it still doesn't work, however this time I could finally uninstall successfully using pip. Finally solved. Thank you.
