### ISSUE TITLE
VK "No JSON object could be decoded" error

### ISSUE THREAD

**Issue by Nicryc** [ytdl-org/youtube-dl#31053]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://vk.com/video222127078_456240791']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-11.3
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, rtmpdump 2.4
[debug] Proxy map: {}
[vk] 222127078_456240791: Downloading JSON metadata
ERROR: 222127078_456240791: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 906, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vk.py", line 325, in _real_extract
    payload = self._download_payload('al_video', video_id, data)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vk.py", line 70, in _download_payload
    headers={'X-Requested-With': 'XMLHttpRequest'})['payload']
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 899, in _download_json
    expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 883, in _download_json_handle
    fatal=fatal), urlh
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 910, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: 222127078_456240791: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I'm currently unable to download videos from VK. I'm getting a `Failed to parse JSON  (caused by ValueError('No JSON object could be decoded')` error. Although I'm unable to donwnload it with yt-dlp too but with a different error `Failed to parse JSON (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0))` so it could be linked to issue #30972, but I'm not sure.

**Comment by dirkf** [comment]
Apparently when you send the sort of request that the extractor uses, you get a "429 Too many requests" error page with a 200 code.

The initial solution was in [#31035]. Unfortunately it now doesn't seem to be working any better than the original code.

**Comment by dirkf** [comment]
Continued in #31035.
