### ISSUE TITLE
[abc.net.au:iview] extractor update required

### ISSUE THREAD

**Issue by BretherenM** [ytdl-org/youtube-dl#31063]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ yt-dlp --verbose "https://iview.abc.net.au/video/ZW3356A001S00"
[debug] Command-line config: ['--verbose', 'https://iview.abc.net.au/video/ZW3356A001S00']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e] (zip)
[debug] Python version 3.9.2 (CPython 32bit) - Linux-5.15.32-v7l+-armv7l-with-glibc2.31
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0
[debug] Optional libraries: certifi-2020.06.20, sqlite3-2.6.0
[debug] Proxy map: {'ftp': 'http://192.168.0.3:8080/', 'https': 'http://192.168.0.3:8080/', 'http': 'http://192.168.0.3:8080/'}
[debug] Using fake IP 1.129.159.26 (AU) as X-Forwarded-For
[debug] [abc.net.au:iview] Extracting URL: https://iview.abc.net.au/video/ZW3356A001S00
[abc.net.au:iview] ZW3356A001S00: Downloading JSON metadata
ERROR: ZW3356A001S00: An extractor error has occurred. (caused by KeyError('playlist')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 647, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/abc.py", line 198, in _real_extract
    stream = next(s for s in video_params['playlist'] if s.get('type') in ('program', 'livestream'))
KeyError: 'playlist'

```

## Description

The following URL (or other random URL's I've tried) doesn't work: https://iview.abc.net.au/show/why-didn-t-they-ask-evans/series/1/video/ZW3356A001S00

I am connected via VPN, but the video plays OK in browser (using same VPN connection).

**Comment by dirkf** [comment]
Apparently a duplicate of [#28823](https://github.com/ytdl-org/youtube-dl/issues/28823#issuecomment-1121930931).

PR #26318 is outstanding for this site but wouldn't affect this, I expect.

Same result from UK with no VPN with latest yt-dl and with latest yt-dlp

**Comment by dirkf** [comment]
With a patch similar to that in the linked comment, the actual error returned by the site is revealed:
```shellsession
$ python -m youtube_dl -v -F 'https://iview.abc.net.au/show/why-didn-t-they-ask-evans/series/1/video/ZW3356A001S00'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://iview.abc.net.au/show/why-didn-t-they-ask-evans/series/1/video/ZW3356A001S00']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 1625723ef
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[debug] Using fake IP 1.155.6.71 (AU) as X-Forwarded-For.
[abc.net.au:iview] ZW3356A001S00: Downloading JSON metadata
ERROR: Some ABC iview programs are now available outside Australia. For the best international experience, download ABC Australia iview on your local Google Play or App Store.
This video is available in Australia.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 816, in wrapper
    return func(self, *args, **kwargs)
  File "youtube_dl/YoutubeDL.py", line 837, in __extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "youtube_dl/extractor/abc.py", line 235, in _real_extract
    raise_error(video_params.get('statusMessage'))
  File "youtube_dl/extractor/abc.py", line 231, in raise_error
    self.raise_geo_restricted(countries=self._GEO_COUNTRIES, **compat_kwargs(kwargs))
  File "youtube_dl/extractor/common.py", line 947, in raise_geo_restricted
    raise GeoRestrictedError(msg, countries=countries)
GeoRestrictedError: Some ABC iview programs are now available outside Australia. For the best international experience, download ABC Australia iview on your local Google Play or App Store.

$
```

**Comment by BretherenM** [comment]
Looks like yt-dlp manages to download the file correctly (I'm assuming importing code from that repo may be a faster resolution) https://github.com/yt-dlp/yt-dlp

**Comment by BretherenM** [comment]
Have confirmed via another AU located host that this is some sort of geolocation issue (ytdl of same version does work correctly there). As this looks to be a duplicate (as above) I'll close this issue
