### ISSUE TITLE
Can't open microsoft stream after passing firefox cookies

### ISSUE THREAD

**Issue by aboss10123** [ytdl-org/youtube-dl#31129]
```
~/downloads yt-dlp -v --cookies cookies.txt "https://web.microsoftstream.com/video/xxxxxxxxxxxxxxxx"
[debug] Command-line config: ['-v', '--cookies', 'cookies.txt', 'https://web.microsoftstream.com/video/f1334280-2674-41d3-988d-49858db46fff']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.18.12-hardened1-2-hardened-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: Crypto-3.15.0, certifi-2022.06.15, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] [microsoftstream] Extracting URL: https://web.microsoftstream.com/video/xxxxxxxxxxxxxxxxxx
[microsoftstream] f1334280-2674-41d3-988d-49858db46fff: Downloading webpage
[microsoftstream] f1334280-2674-41d3-988d-49858db46fff: Downloading JSON metadata
[microsoftstream] f1334280-2674-41d3-988d-49858db46fff: Downloading ISM manifest
[microsoftstream] f1334280-2674-41d3-988d-49858db46fff: Downloading MPD manifest
[microsoftstream] f1334280-2674-41d3-988d-49858db46fff: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] f1334280-2674-41d3-988d-49858db46fff: Downloading 1 format(s): hls-579+hls-138
[debug] Invoking hlsnative downloader on "https://euno-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackUrl=https://streameuno1su021.azureedge.net//efd4c695-9934-4d69-bf12-99f82b8828bc/3-qyhhoviswgn2vxq7kdyjxjterb_enhanced.ism/QualityLevels(423000)/Manifest(video,format=m3u8-aapl)"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 136
[download] Destination: Lecture 1.fhls-579.mp4
[download]   0.7% of ~66.37MiB at    2.12MiB/s ETA 00:30 (frag 1/136)ERROR: unable to download video data: HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3142, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2860, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/hls.py", line 354, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 526, in download_and_append_fragments
    decrypt_fragment(fragment, self._read_fragment(ctx)), fragment['frag_index'], ctx)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 354, in decrypt_fragment
    decrypt_info['KEY'] = decrypt_info.get('KEY') or _get_key(info_dict.get('_decryption_key_url') or decrypt_info['URI'])
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 346, in _get_key
    _key_cache[url] = self.ydl.urlopen(self._prepare_url(info_dict, url)).read()
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3639, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

~/downloads ls
 cookies.txt
'Lecture 1.mp4.part'
'Lecture 1.mp4.part-Frag1'
'Lecture 1.fhls-579.mp4.ytdl'
~/downloads
```
Using 2022.07.18

**Comment by dirkf** [comment]
https://github.com/yt-dlp/yt-dlp/issues/new/choose
