### ISSUE TITLE
history channel: "The signature is invalid."

### ISSUE THREAD

**Issue by eflister** [ytdl-org/youtube-dl#31123]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl --verbose "https://play.history.com/shows/alone/season-1/episode-5"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://play.history.com/shows/alone/season-1/episode-5']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.4 (CPython) - macOS-11.6.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1
[debug] Proxy map: {}
[aenetworks] /shows/alone/season-1/episode-5: Downloading JSON metadata
[aenetworks] 485399619758: Downloading JSON metadata
[aenetworks] 485399619758: Downloading hls_high_ak SMIL data
[aenetworks] 485399619758: Downloading high_video_s3 SMIL data
[aenetworks] 485399619758: Downloading hls_high_fastly SMIL data
ERROR: The signature is invalid.
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/youtube_dl/extractor/aenetworks.py", line 174, in _real_extract
    return self._extract_aetn_info(domain, 'canonical', '/' + canonical, url)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/youtube_dl/extractor/aenetworks.py", line 93, in _extract_aetn_info
    info.update(self._extract_aen_smil(media_url, video_id, auth))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/youtube_dl/extractor/aenetworks.py", line 66, in _extract_aen_smil
    raise last_e
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/youtube_dl/extractor/aenetworks.py", line 56, in _extract_aen_smil
    tp_formats, tp_subtitles = self._extract_theplatform_smil(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/youtube_dl/extractor/theplatform.py", line 51, in _extract_theplatform_smil
    raise ExtractorError(
youtube_dl.utils.ExtractorError: The signature is invalid.
```

## Description

no additional info

**Comment by eflister** [comment]
dupe with https://github.com/ytdl-org/youtube-dl/issues/29300, the key/secret update there works
