### ISSUE TITLE
[zdf] ytdl fails with KeyError: 'basename'

### ISSUE THREAD

**Issue by Tafkas** [ytdl-org/youtube-dl#31149]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
➜  ~ youtube-dl --version
2021.12.17
➜  ~ youtube-dl --verbose https://www.zdf.de/gesellschaft/aktenzeichen-xy-ungeloest
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.zdf.de/gesellschaft/aktenzeichen-xy-ungeloest']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.5 (CPython) - macOS-12.5-x86_64-i386-64bit
[debug] exe versions: ffmpeg 5.1, ffprobe 5.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 53.60.232.50 (DE) as X-Forwarded-For.
[ZDFChannel] aktenzeichen-xy-ungeloest: Downloading webpage
[download] Downloading playlist: Aktenzeichen XY... ungelöst
[ZDFChannel] playlist Aktenzeichen XY... ungelöst: Collected 44 video ids (downloading 44 of them)
[download] Downloading video 1 of 44
[debug] Using fake IP 53.88.203.47 (DE) as X-Forwarded-For.
[ZDF] aktenzeichen-xy-ungeloest-vom-3-august-2022-100: Downloading webpage
[ZDF] aktenzeichen-xy-ungeloest-vom-3-august-2022-100: Downloading JSON content
[ZDF] aktenzeichen-xy-ungeloest-vom-3-august-2022-100: Downloading JSON metadata
[ZDF] 220803_sendung_axy: Downloading m3u8 information
[ZDF] 220803_sendung_axy: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://zdfvod-rwrtr.akamaized.net/i/,/mp4/none/zdf/22/08/220803_sendung_axy/6/220803_sendung_axy,_508k_p9,_808k_p11,_1628k_p13,_3328k_p15,v15.mp4.csmil/index-f4-v1-a1.m3u8'
[download] Aktenzeichen XY... ungelöst vom 3. August 2022-220803_sendung_axy.mp4 has already been downloaded
[download] 100% of 1.66GiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:Aktenzeichen XY... ungelöst vom 3. August 2022-220803_sendung_axy.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "Aktenzeichen XY... ungelöst vom 3. August 2022-220803_sendung_axy.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Aktenzeichen XY... ungelöst vom 3. August 2022-220803_sendung_axy.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:Aktenzeichen XY... ungelöst vom 3. August 2022-220803_sendung_axy.temp.mp4'
[download] Downloading video 2 of 44
[ZDF] xy580-fall1-kindermoerder-gesucht-100: Downloading webpage
[ZDF] xy580-fall1-kindermoerder-gesucht-100: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('basename')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/zdf.py", line 294, in _real_extract
    return self._extract_mobile(video_id)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/zdf.py", line 251, in _extract_mobile
    content_id = document['basename']
KeyError: 'basename'
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/zdf.py", line 294, in _real_extract
    return self._extract_mobile(video_id)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/zdf.py", line 251, in _extract_mobile
    content_id = document['basename']
KeyError: 'basename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 547, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('basename')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I was trying to download the current episode of Aktenzeichen XY from [https://www.zdf.de/gesellschaft/aktenzeichen-xy-ungeloest](https://www.zdf.de/gesellschaft/aktenzeichen-xy-ungeloest).

**Comment by dirkf** [comment]
What did you expect this page to be, a single video or a playlist?

yt-dl thinks it's a playlist (`ZDFChannelIE`) with 44 items, corresponding to the `data-plusbar-url` values in the page source. The first item is downloaded (3 August). Then, as item 2 has no video, it fails to get player data for it and crashes when falling back to the corresponding mobile page. If you use `--ignore-errors` this happens for items 3-7 too, until 8-10 which do have videos, and so on.

Use `--playlist-items 1` to avoid this and just get the first video (though I'm not sure that item 1 is guaranteed to be the newest). Use 

Single video pages (`ZDFIE`) have a `.html` extension in the URL.

There doesn't seem to be any metadata in the `data-plusbar...` blocks that would indicate when what appears to be a linked single video page actually has a video. We can fix the actual crash in the log but then your original command will just break on playlist item 2 with `ERROR: No video formats found` instead.

Using the _jq_ program, you can list the URLs of the playlist items and perhaps pick the one you want:
```
youtube-dl --flat-playlist -J 'https://www.zdf.de/gesellschaft/aktenzeichen-xy-ungeloest' | jq '.entries | .[] | .url'
```

**Comment by dirkf** [comment]
Actually, the page does show which items are videos. The `<div ...>` element that contains the `data-plusbar-url` attribute is enclosed in a link that contains a `data-target-video-type` attribute and a `data-target-id` that matches the `data-plusbar-id`. The video type `'novideo'` shows the items to skip.
