### ISSUE TITLE
RegexNotFound error affecting YouTube "Unable to extract Initial JS player n function list ($va[0])"

### ISSUE THREAD

**Issue by SerpentStare** [ytdl-org/youtube-dl#31165]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

-->

```
youtube-dl -x --audio-format mp3 https://www.youtube.com/watch?v=fsbkFkzRREc --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=fsbkFkzRREc', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Lazy loading extractors enabled
[debug] Python version 3.9.13 (CPython) - Linux-5.15.55-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] fsbkFkzRREc: Downloading webpage
[youtube] fsbkFkzRREc: Downloading MPD manifest
[youtube] fsbkFkzRREc: Downloading player 4c3f79c5
ERROR: fsbkFkzRREc: Traceback (most recent call last):
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1442, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1415, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1402, in _extract_n_function_name
    return self._parse_json(self._search_regex(
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function list ($va[0]); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function list ($va[0])\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1442, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1415, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1402, in _extract_n_function_name
    return self._parse_json(self._search_regex(
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function list ($va[0]); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1442, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1415, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1402, in _extract_n_function_name
    return self._parse_json(self._search_regex(
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function list ($va[0]); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1874, in _real_extract
    self._unthrottle_format_urls(video_id, player_url, formats)
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1459, in _unthrottle_format_urls
    n_response = self._n_descramble(n_param, player_url, video_id)
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1449, in _n_descramble
    raise ExtractorError(traceback.format_exc(), cause=e, video_id=video_id)
youtube_dl.utils.ExtractorError: fsbkFkzRREc: Traceback (most recent call last):
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1442, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1415, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1402, in _extract_n_function_name
    return self._parse_json(self._search_regex(
  File "/nix/store/wiz5mjg9fjq3in8n16p0faq3if9ynz25-python3.9-youtube-dl-2021.12.17/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function list ($va[0]); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function list ($va[0])\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

"Unable to extract Initial JS player n function list ($va[0])"
It looks like when I am trying to download video or extract audio from YouTube videos today... I just keep running into this error.

failed commands attempted: 
youtube-dl https://www.youtube.com/watch?v=RsunEchAEaI
youtube-dl -x --audio-format mp3 https://www.youtube.com/watch?v=RsunEchAEaI
youtube-dl -x --audio-format mp3 https://www.youtube.com/watch?v=fsbkFkzRREc

I seem to get the same error with each attempt. It seems notable that the same error apparently keeps interrupting itself. The verbose log reliably complains about being 'unable to extract Initial JS player n function list' **many times** for a single failure, even interrupting one error to have another version of what seems to be the same error.

(I say this because of the line which stands alone, "During handling of the above exception, another exception occurred:")

I don't know how to interpret most of the rest of this, but I find it funny to see this: 
The request to submit a bug report is repeated _8 times_ in this error log... I guess somebody _really wants me to do that_. So I have. I hope it helps!

For contrast, when I tried downloading audio from non-YouTube sites (https://clyp.it and soundcloud), it worked fine, so this might only be a problem with YouTube.

### System:

I'm using NixOS, but am very new with this OS and don't know the obvious ways to fix things in it yet.

I noticed this error with youtube-dl just after changing my configuration. 
I had not been trying to use youtube-dl directly before the changes.
I think it is **probably** not related at all - the error continued just the same for me when I tried going back to the previous configuration state. But in case I'm wrong...

What I changed:

I tried to enable xdg.portal and flatpaks by adding the following to my configuration.nix.
```
# Enable flatpak to try to run a less glitchy version of Steam
  xdg.portal.extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
  xdg.portal.enable = true;
  services.flatpak.enable = true;
  ```

**Comment by dirkf** [comment]
>... this might only be a problem with YouTube.

Exactly. This is the same problem as #31164 but with a different yt-dl version.
