### ISSUE TITLE
Can't download from BBC

### ISSUE THREAD

**Issue by bluerun27** [ytdl-org/youtube-dl#31160]
## Checklist

- [X ] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -F https://www.bbc.com/news/av/business-62476338 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.bbc.com/news/av/business-62476338', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.7.1-050701-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[bbc] business-62476338: Downloading webpage
ERROR: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/d4/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/d4/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/d4/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/d4/.local/lib/python3.8/site-packages/youtube_dl/extractor/bbc.py", line 1253, in _real_extract
    self._search_regex(
  File "/home/d4/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

No credentials needed. This site used to work before. 
I also inspected the html and tried downloading using some sort of canonical url (as explained elsewhere in the forum). 
youtube-dl -F https://www.bbc.co.uk/programmes/p0cry8vp 
to no avail.

**Comment by dirkf** [comment]
Works for me:
```shellsession
$ python -m youtube_dl -v -f worst --test 'https://www.bbc.com/news/av/business-62476338'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'worst', u'--test', u'https://www.bbc.com/news/av/business-62476338']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: e6a836d54
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[bbc] business-62476338: Downloading webpage
[bbc] p0cry1yw: Downloading media selection JSON
[bbc] p0cry1yw: Downloading m3u8 information
[bbc] p0cry1yw: Downloading m3u8 information
[bbc] p0cry1yw: Downloading MPD manifest
[bbc] p0cry1yw: Downloading MPD manifest
[bbc] p0cry1yw: Downloading m3u8 information
[bbc] p0cry1yw: Downloading m3u8 information
[bbc] p0cry1yw: Downloading MPD manifest
[bbc] p0cry1yw: Downloading MPD manifest
[bbc] p0cry1yw: Downloading m3u8 information
[bbc] p0cry1yw: Downloading m3u8 information
[bbc] p0cry1yw: Downloading MPD manifest
[bbc] p0cry1yw: Downloading MPD manifest
[download] Downloading playlist: Mining boss: 'One person doesn't have all the answers'
[bbc] playlist Mining boss: 'One person doesn't have all the answers': Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Invoking downloader on u'http://vod-pro-uk-live.akamaized.net/av_pv3_pa2/modav/bUnknown-c2698f15-196d-4f7b-9e2e-78d714d85832_p0cry1yw_cUnknown_1660033753011.mp4?__gda__=1660241407_52bf3591569e3aa6f0294ab1bfeb0b48'
[download] Destination: Mining boss - 'One person doesn't have all the answers'-p0cry1yw.mp4
[download] 100% of 10.00KiB in 00:00
[download] Finished downloading playlist: Mining boss: 'One person doesn't have all the answers'
$
```
(I asked for `-f worst` to get more video in the 10KB)

Also:
```shellsession
$ python -m youtube_dl -v -F 'https://www.bbc.co.uk/programmes/p0cry1yw'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.bbc.co.uk/programmes/p0cry1yw']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: e6a836d54
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[bbc.co.uk] p0cry1yw: Downloading video page
[bbc.co.uk] p0cry1yw: Downloading media selection JSON
[bbc.co.uk] p0cry1yw: Downloading MPD manifest
[bbc.co.uk] p0cry1yw: Downloading MPD manifest
[bbc.co.uk] p0cry1yw: Downloading MPD manifest
[bbc.co.uk] p0cry1yw: Downloading MPD manifest
[bbc.co.uk] p0cry1yw: Downloading MPD manifest
[bbc.co.uk] p0cry1yw: Downloading MPD manifest
[bbc.co.uk] p0cry1yw: Downloading m3u8 information
[bbc.co.uk] p0cry1yw: Downloading m3u8 information
[bbc.co.uk] p0cry1yw: Downloading m3u8 information
[bbc.co.uk] p0cry1yw: Downloading m3u8 information
[bbc.co.uk] p0cry1yw: Downloading m3u8 information
[bbc.co.uk] p0cry1yw: Downloading m3u8 information
[info] Available formats for p0cry1yw:
format code                         extension  resolution note
mf_akamai-audio_eng_1=128000-0      m4a        audio only [en] DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
mf_akamai-audio_eng_1=128000-1      m4a        audio only [en] DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
mf_bidi-audio_eng_1=128000-0        m4a        audio only [en] DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
mf_bidi-audio_eng_1=128000-1        m4a        audio only [en] DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
mf_cloudfront-audio_eng_1=128000-0  m4a        audio only [en] DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
mf_cloudfront-audio_eng_1=128000-1  m4a        audio only [en] DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
mf_akamai-video=827000-0            mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_akamai-video=827000-1            mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_bidi-video=827000-0              mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_bidi-video=827000-1              mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_cloudfront-video=827000-0        mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_cloudfront-video=827000-1        mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_akamai-video=1570000-0           mp4        704x396    DASH video 1570k , mp4_dash container, avc3.64001F, 50fps, video only
mf_akamai-video=1570000-1           mp4        704x396    DASH video 1570k , mp4_dash container, avc3.64001F, 50fps, video only
mf_bidi-video=1570000-0             mp4        704x396    DASH video 1570k , mp4_dash container, avc3.64001F, 50fps, video only
mf_bidi-video=1570000-1             mp4        704x396    DASH video 1570k , mp4_dash container, avc3.64001F, 50fps, video only
mf_cloudfront-video=1570000-0       mp4        704x396    DASH video 1570k , mp4_dash container, avc3.64001F, 50fps, video only
mf_cloudfront-video=1570000-1       mp4        704x396    DASH video 1570k , mp4_dash container, avc3.64001F, 50fps, video only
mf_akamai-video=2812000-0           mp4        960x540    DASH video 2812k , mp4_dash container, avc3.64001F, 50fps, video only
mf_akamai-video=2812000-1           mp4        960x540    DASH video 2812k , mp4_dash container, avc3.64001F, 50fps, video only
mf_bidi-video=2812000-0             mp4        960x540    DASH video 2812k , mp4_dash container, avc3.64001F, 50fps, video only
mf_bidi-video=2812000-1             mp4        960x540    DASH video 2812k , mp4_dash container, avc3.64001F, 50fps, video only
mf_cloudfront-video=2812000-0       mp4        960x540    DASH video 2812k , mp4_dash container, avc3.64001F, 50fps, video only
mf_cloudfront-video=2812000-1       mp4        960x540    DASH video 2812k , mp4_dash container, avc3.64001F, 50fps, video only
mf_akamai-video=5070000-0           mp4        1280x720   DASH video 5070k , mp4_dash container, avc3.640020, 50fps, video only
mf_akamai-video=5070000-1           mp4        1280x720   DASH video 5070k , mp4_dash container, avc3.640020, 50fps, video only
mf_bidi-video=5070000-0             mp4        1280x720   DASH video 5070k , mp4_dash container, avc3.640020, 50fps, video only
mf_bidi-video=5070000-1             mp4        1280x720   DASH video 5070k , mp4_dash container, avc3.640020, 50fps, video only
mf_cloudfront-video=5070000-0       mp4        1280x720   DASH video 5070k , mp4_dash container, avc3.640020, 50fps, video only
mf_cloudfront-video=5070000-1       mp4        1280x720   DASH video 5070k , mp4_dash container, avc3.640020, 50fps, video only
mf_akamai-1013-0                    mp4        704x396    1013k , avc1.4D401F@ 827k, 25.0fps, mp4a.40.2@128k
mf_akamai-1013-1                    mp4        704x396    1013k , avc1.4D401F@ 827k, 25.0fps, mp4a.40.2@128k
mf_bidi-1013-0                      mp4        704x396    1013k , avc1.4D401F@ 827k, 25.0fps, mp4a.40.2@128k
mf_bidi-1013-1                      mp4        704x396    1013k , avc1.4D401F@ 827k, 25.0fps, mp4a.40.2@128k
mf_cloudfront-1013-0                mp4        704x396    1013k , avc1.4D401F@ 827k, 25.0fps, mp4a.40.2@128k
mf_cloudfront-1013-1                mp4        704x396    1013k , avc1.4D401F@ 827k, 25.0fps, mp4a.40.2@128k
mf_akamai-1800-0                    mp4        704x396    1800k , avc1.64001F@1570k, 50.0fps, mp4a.40.2@128k
mf_akamai-1800-1                    mp4        704x396    1800k , avc1.64001F@1570k, 50.0fps, mp4a.40.2@128k
mf_bidi-1800-0                      mp4        704x396    1800k , avc1.64001F@1570k, 50.0fps, mp4a.40.2@128k
mf_bidi-1800-1                      mp4        704x396    1800k , avc1.64001F@1570k, 50.0fps, mp4a.40.2@128k
mf_cloudfront-1800-0                mp4        704x396    1800k , avc1.64001F@1570k, 50.0fps, mp4a.40.2@128k
mf_cloudfront-1800-1                mp4        704x396    1800k , avc1.64001F@1570k, 50.0fps, mp4a.40.2@128k
mf_akamai-3117-0                    mp4        960x540    3117k , avc1.64001F@2812k, 50.0fps, mp4a.40.2@128k
mf_akamai-3117-1                    mp4        960x540    3117k , avc1.64001F@2812k, 50.0fps, mp4a.40.2@128k
mf_bidi-3117-0                      mp4        960x540    3117k , avc1.64001F@2812k, 50.0fps, mp4a.40.2@128k
mf_bidi-3117-1                      mp4        960x540    3117k , avc1.64001F@2812k, 50.0fps, mp4a.40.2@128k
mf_cloudfront-3117-0                mp4        960x540    3117k , avc1.64001F@2812k, 50.0fps, mp4a.40.2@128k
mf_cloudfront-3117-1                mp4        960x540    3117k , avc1.64001F@2812k, 50.0fps, mp4a.40.2@128k
mf_akamai-5510-0                    mp4        1280x720   5510k , avc1.640020@5070k, 50.0fps, mp4a.40.2@128k
mf_akamai-5510-1                    mp4        1280x720   5510k , avc1.640020@5070k, 50.0fps, mp4a.40.2@128k
mf_bidi-5510-0                      mp4        1280x720   5510k , avc1.640020@5070k, 50.0fps, mp4a.40.2@128k
mf_bidi-5510-1                      mp4        1280x720   5510k , avc1.640020@5070k, 50.0fps, mp4a.40.2@128k
mf_cloudfront-5510-0                mp4        1280x720   5510k , avc1.640020@5070k, 50.0fps, mp4a.40.2@128k
mf_cloudfront-5510-1                mp4        1280x720   5510k , avc1.640020@5070k, 50.0fps, mp4a.40.2@128k (best)
$
```

**Comment by bluerun27** [comment]
Note: I had previously installed youtube-dl with

`pip install -U youtube-dl`

I uninstalled it and installed it again using:

```
mkdir youtube-dl && git clone --depth 1 --branch fix-function-sig-parser https://github.com/lanegramling/youtube-dl.git 
cd youtube-dl &&  python3 -m pip install -e . --user
```

Now everything is **working fine.**

**Comment by dirkf** [comment]
Yes, the git master fixes the problem in the release version through 58babe9af79215bd6bdf07da0a8ebb1d3650e00 (presumably).

Your installation is somewhat over-complicated and won't give you the latest version (depending on what Lane has committed to his branch).

Try this:
```
python3 -m pip install --force-reinstall --system 'https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.tar.gz'
```
See also https://github.com/ytdl-org/youtube-dl/issues/30871#issuecomment-1102666158.

**Comment by bluerun27** [comment]
`no such option: --system`
installed it without it and everything is fine. thanks.

**Comment by dirkf** [comment]
`--system`, the explicit opposite of `--user`, apparently disappeared somewhere between v8.1.1 and v21.3 of _pip_.
