### ISSUE TITLE
10play.com.au not downloading

### ISSUE THREAD

**Issue by aschaft** [ytdl-org/youtube-dl#31236]
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', '-i', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', 'https://10play.com.au/survivor-south-africa/episodes/season-9-return-of-the-outcasts/episode-1/tpv220717zymua']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.4 (CPython) - Linux-5.15.0-47-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[TenPlay] tpv220717zymua: Downloading JSON metadata
ERROR: tpv220717zymua: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 906, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 906, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tenplay.py", line 41, in _real_extract
    data = self._download_json(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 895, in _download_json
    res = self._download_json_handle(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 881, in _download_json_handle
    return self._parse_json(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 910, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: tpv220717zymua: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Trying on a aus based linode to download from 10play.com.au

**Comment by dirkf** [comment]
Thanks for that very thorough response.

The version of the tenplay.py extractor in this [zip archive](https://github.com/ytdl-org/youtube-dl/files/9584818/tenplay.py.zip) includes the yt-dlp changes plus some of mine.

As I can only get this
```
This video is not available from your location due to geo restriction
This video is available in Australia.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
```
without going to the lengths (1 & 2, as listed) above, I encourage any savvy 10Play subscriber with the sort of installation that allows individual files to be replaced to try the zipped module instead the shipped `extractor/tenplay.py`.

**Comment by Vangelis66** [comment]
... **dirkf**'s patch appears to work as expected (tested on the show in the OP): 

```
youtube-dl -v --proxy "https://proxyhost:proxyport" -u <redacted> -p <redacted> -F "https://10play.com.au/survivor-south-africa/episodes/season-9-return-of-the-outcasts/episode-1/tpv220717zymua" => 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--proxy', 'https://proxyhost:proxyport', '-u', 'PRIVATE', '-p', 'PRIVATE', '-F', 'https://10play.com.au/survivor-south-africa/episodes/season-9-return-of-the-outcasts/episode-1/tpv220717zymua']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2022.09.16.1919
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, phantomjs 2.1.1, rtmpdump 2.4

[debug] Proxy map: {'https': 'https://proxyhost:proxyport', 'http': 'https://proxyhost:proxyport'}
[TenPlay] tpv220717zymua: Downloading JSON metadata
[TenPlay] tpv220717zymua: Getting bearer token
[TenPlay] tpv220717zymua: Downloading video JSON
[TenPlay] tpv220717zymua: Downloading webpage
[TenPlay] tpv220717zymua: Downloading m3u8 information
[info] Available formats for 6309654142112:
format code  extension  resolution note
722          mp4        480x270     722k , avc1.4d4015, 25.0fps, mp4a.40.2
931          mp4        640x360     931k , avc1.4d401e, 25.0fps, mp4a.40.2
1695         mp4        960x540    1695k , avc1.4d401f, 25.0fps, mp4a.40.2 (best)
```
and
```
youtube-dl --proxy "https://proxyhost:proxyport" -u <redacted> -p <redacted> "https://10play.com.au/survivor-south-africa/episodes/season-9-return-of-the-outcasts/episode-1/tpv220717zymua" --hls-prefer-native => 
[TenPlay] tpv220717zymua: Downloading JSON metadata
[TenPlay] tpv220717zymua: Getting bearer token
[TenPlay] tpv220717zymua: Downloading video JSON
[TenPlay] tpv220717zymua: Downloading webpage
[TenPlay] tpv220717zymua: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 441
[download] Destination: Survivor South Africa - S9 Ep. 1-6309654142112.mp4
[download]   0.2% of ~542.88MiB at 160.38KiB/s ETA 01:51:13
```
(my free AU proxy has, expectedly, slow speeds 😜 ... )
