### ISSUE TITLE
Extractor raywenderlich is not working

### ISSUE THREAD

**Issue by aboba1337-afk** [ytdl-org/youtube-dl#31244]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\ytdl>youtube-dl.exe --cookies rw.txt https://www.raywenderlich.com/32317111-advanced-networking-with-urlsession --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'rw.txt', 'https://www.raywenderlich.com/32317111-advanced-networking-with-urlsession', '--verbose']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 5.1.1-full_build-www.gyan.dev, ffprobe 5.1.1-full_build-www.gyan.dev
[debug] Proxy map: {}
[RayWenderlichCourse] 32317111-advanced-networking-with-urlsession: Downloading webpage
[download] Downloading playlist: Advanced Networking with URLSession
[RayWenderlichCourse] playlist Advanced Networking with URLSession: Collected 13 video ids (downloading 13 of them)
[download] Downloading video 1 of 13
[RayWenderlich] 32317111-advanced-networking-with-urlsession/1: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\raywenderlich.py", line 105, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Hi everyone! The corresponding extractor for the site https://www.raywenderlich.com/ does not work. Please help me :[

**Comment by aboba1337-afk** [comment]
At that time, some download managers (like IDM) can download videos from there.

**Comment by 89z** [comment]
> At that time, some download managers (like IDM) can download videos from there.

https://youtube.com/watch?v=_K-L9uhsBLM&t=70s

**Comment by aboba1337-afk** [comment]
> https://youtube.com/watch?v=_K-L9uhsBLM&t=70s

yes, this too

**Comment by Vangelis66** [comment]
> but they **don't solve** the problem

... This is irrelevant; you aren't meant to open/submit a **duplicate** "new" issue just because the original "existing" one(s) remain open/unresolved... 

https://github.com/ytdl-org/youtube-dl#is-the-issue-already-documented

You may comment on/bump an **existing** issue similar/identical to the one you were about to submit, but please first read:

https://github.com/ytdl-org/youtube-dl#how-can-i-speed-up-work-on-my-issue

... not failing to pay attention to:

> If nobody is interested in solving your issue, you are welcome to take matters into your own hands and submit a pull request (or coerce/pay somebody else to do so).
