### ISSUE TITLE
404 error when downloading a video from Youtube

### ISSUE THREAD

**Issue by eetupr** [ytdl-org/youtube-dl#31264]
Attempting to download this video from youtube causes 404 error to be displayed.
https://www.youtube.com/watch?v=oaUC5vk2lKc

Reproduced in Windows and Linux.

Example output:

> .\youtube-dl.exe https://www.youtube.com/watch?v=oaUC5vk2lKc
[youtube] oaUC5vk2lKc: Downloading webpage
ERROR: unable to download video data: HTTP Error 404: Not Found

**Comment by dirkf** [comment]
Verbose log, please (see [here](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md)).

You may find that the format selected in your configuration hasn't been properly set up in YT's CDN. The YT media links contain fallback server names that are used by the web player but not (yet) by yt-dl. Selecting a different format may succeed.

I have no problem with `youtube-dl -v --test 'https://www.youtube.com/watch?v=oaUC5vk2lKc'`.

**Comment by Vangelis66** [comment]
> You may find that the format selected in your configuration hasn't been properly set up in YT's CDN.

` -F`-ing referenced YT video claims that the "best" format available is `-f 22`: 
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'oaUC5vk2lKc']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2022.09.30.334
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg 5.0, ffprobe 5.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] oaUC5vk2lKc: Downloading webpage
[debug] [youtube] Decrypted nsig mq_oq8Fo2N50xNpJ => QgME9EtcRA9YQQ
[debug] [youtube] Decrypted nsig FcthGSoCmXVjUiLi => 7-4aPdIJUvNqCw
[info] Available formats for oaUC5vk2lKc:
format code  extension  resolution note
249          webm       audio only tiny   50k , webm_dash container, opus @ 50k(48000Hz), 53.83MiB
250          webm       audio only tiny   57k , webm_dash container, opus @ 57k(48000Hz), 62.06MiB
251          webm       audio only tiny  106k , webm_dash container, opus @106k(48000Hz), 114.03MiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 139.20MiB
278          webm       256x144    144p  101k , webm_dash container, vp9@ 101k,30fps, video only, 108.97MiB
160          mp4        256x144    144p  107k , mp4_dash container, avc1.4d400c@ 107k, 30fps, video only, 115.77MiB
242          webm       426x240    240p  215k , webm_dash container, vp9@ 215k,30fps, video only, 231.41MiB
133          mp4        426x240    240p  242k , mp4_dash container, avc1.4d4015@ 242k, 30fps, video only, 260.30MiB
243          webm       640x360    360p  388k , webm_dash container, vp9@ 388k,30fps, video only, 418.19MiB
134          mp4        640x360    360p  533k , mp4_dash container, avc1.4d401e@ 533k, 30fps, video only, 574.13MiB
244          webm       854x480    480p  722k , webm_dash container, vp9@ 722k,30fps, video only, 776.33MiB
135          mp4        854x480    480p 1031k , mp4_dash container, avc1.4d401f@1031k, 30fps, video only, 1.08GiB
247          webm       1280x720   720p 1465k , webm_dash container, vp9@1465k, 30fps, video only, 1.54GiB
136          mp4        1280x720   720p 2047k , mp4_dash container, avc1.64001f@2047k, 30fps, video only, 2.15GiB
248          webm       1920x1080  1080p 2491k , webm_dash container, vp9@2491k, 30fps, video only, 2.62GiB
137          mp4        1920x1080  1080p 4234k , mp4_dash container, avc1.640028@4234k, 30fps, video only, 4.45GiB
18           mp4        640x360    360p  720k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz), 774.52MiB
22           mp4        1280x720   720p 2175k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
```
but do notice that **no (approximate) filesize** for ` -f 22` is being returned... 
Specifying ` -f 22` will **404** (and I believe that to be the case with the OP) : 
```
youtube-dl -v -f 22 "oaUC5vk2lKc" => 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '22', 'oaUC5vk2lKc']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2022.09.30.334
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg 5.0, ffprobe 5.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] oaUC5vk2lKc: Downloading webpage
[debug] [youtube] Decrypted nsig iSyoEtX0JRaJrScw => MBregZdtngDvgA
[debug] [youtube] Decrypted nsig lISc4RkmNGZvMjrF => PZvc6JgpwzuP6Q
[debug] Invoking downloader on 'https://rr1---sn-4vguioxu-n3bz.googlevideo.com/videoplayback?mm=31%2C29&mvi=1&pl=21&lmt=1663974810250740&mt=1664585396&c=WEB&ns=CAIfYXz5hLwfCYTb1BoSEGsI&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAPSt3s6y7neeDl-fKUb-bFwFd8_kaR3pUhxp7zt_Eh-sAiANbERvvnoEzuhmg28hWo2JVMy1DV9M_oBgEN_4znC1ig%3D%3D&mh=wq&n=PZvc6JgpwzuP6Q&requiressl=yes&cnr=14&expire=1664607781&fexp=24001373%2C24007246&ms=au%2Crdu&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&mv=m&itag=22&initcwndbps=681250&lsig=AG3C_xAwRQIhAKqUKIv2ZzRW-UDUH16bzwvnqFP3wyiGKTQg-sk-uIBqAiBpH_uDEmsth1RziF0tUiSONblJHI5hUvhGRNsFdRsjig%3D%3D&txp=6318224&vprv=1&mn=sn-4vguioxu-n3bz%2Csn-nv47lnsy&ei=xZE3Y5XEJYP-gQeEgYw4&fvip=4&dur=9019.234&id=o-AJaRWFJd9B3m0rD77jhuD0fUPiWk5ndyjsfZaEQFqsCK&ip=[redacted]&ratebypass=yes&source=youtube&mime=video%2Fmp4'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "D:\a\youtube-dl\youtube-dl\youtube_dl\YoutubeDL.py", line 1985, in process_info
  File "D:\a\youtube-dl\youtube-dl\youtube_dl\YoutubeDL.py", line 1924, in dl
  File "D:\a\youtube-dl\youtube-dl\youtube_dl\downloader\common.py", line 366, in download
  File "D:\a\youtube-dl\youtube-dl\youtube_dl\downloader\http.py", line 351, in real_download
  File "D:\a\youtube-dl\youtube-dl\youtube_dl\downloader\http.py", line 116, in establish_connection
  File "D:\a\youtube-dl\youtube-dl\youtube_dl\downloader\http.py", line 110, in establish_connection
  File "D:\a\youtube-dl\youtube-dl\youtube_dl\YoutubeDL.py", line 2300, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.4.4\x86\lib\urllib\request.py", line 470, in open
  File "C:\hostedtoolcache\windows\Python\3.4.4\x86\lib\urllib\request.py", line 580, in http_response
  File "C:\hostedtoolcache\windows\Python\3.4.4\x86\lib\urllib\request.py", line 508, in error
  File "C:\hostedtoolcache\windows\Python\3.4.4\x86\lib\urllib\request.py", line 442, in _call_chain
  File "C:\hostedtoolcache\windows\Python\3.4.4\x86\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```
OTOH, **not specifying any format** will result in `youtube-dl` fetching ` -f 137` (I didn't let it complete 😉 ) : 
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'oaUC5vk2lKc']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2022.09.30.334
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg 5.0, ffprobe 5.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] oaUC5vk2lKc: Downloading webpage
[debug] [youtube] Decrypted nsig OaY3m_FkTSIZv2Jz => g7Bgvuep94CVAw
[debug] [youtube] Decrypted nsig wjfA95n1oyidQLr6 => -d6k3uQwz3ecJQ
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://rr1---sn-4vguioxu-n3bz.googlevideo.com/videoplayback?keepalive=yes&mm=31%2C29&dur=9019.175&mvi=1&vprv=1&mn=sn-4vguioxu-n3bz%2Csn-nv47lnsy&pl=21&id=o-AMHOIKFJ5JSoyEkwqj0h6rhZqhNF6GHWu9U1mKpAw4W6&source=youtube&fexp=24001373%2C24007246&fvip=4&mime=video%2Fmp4&txp=6319224&lsig=AG3C_xAwRQIgTALFy5ga0ljiVSL7aPowz354I7FJoc_mSs1uVf83GAICIQCaJY9IYP_sD2GMzmWU4TFmq5ONHXFcficnNcMITVo3UQ%3D%3D&clen=4774180143&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&pcm2cms=yes&sig=AOq0QJ8wRQIhANP7hS00HIbhQjmE48LufSzn1iGPKiTKsbhbohlWA9LwAiBxB2c3IlqPBcIbPE1tFurobNNVZ54bVnXPN8apoxHC4Q%3D%3D&mt=1664586094&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lmt=1663973598547528&mh=wq&itag=137&ms=au%2Crdu&ip=[redacted]&n=g7Bgvuep94CVAw&gir=yes&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&requiressl=yes&ei=KZM3Y6SiJM7qgAfI0LK4CQ&expire=1664608137&initcwndbps=603750&c=WEB&mv=m&ns=GgvuNx1TCXwJxnnL2upIOcQI'
[download] Destination: Hyvi? uutisia! vko 38_2022  -  MANSEN M?RIN?T ERIKOISL?HETYS!-oaUC5vk2lKc.f137.mp4
[download]   0.6% of 4.45GiB at  1.29MiB/s ETA 58:31
```
A tangentially related "downstream" issue might be [#3372](https://github.com/yt-dlp/yt-dlp/issues/3372) ...

**Comment by dirkf** [comment]
And, if format 22 is involved, #30990 (which I was hinting at above).

**Comment by Vangelis66** [comment]
> Specifying ` -f 22` will **404** (and I believe that to be the case with the OP) :

FWIW, **Youtube** seem to have fixed this on their end on **Oct 14th** (that's when I tried it and it no longer generated the `Not Found` error): 
```
youtube-dl -vf 22 "oaUC5vk2lKc" =>

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vf', '22', 'oaUC5vk2lKc']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2022.10.20.810
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg 5.0, ffprobe 5.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] oaUC5vk2lKc: Downloading webpage
[debug] [youtube] Decrypted nsig i4GBnw3ZS5gopSbPJ => Tr0j1KrUCb6k3A
[debug] [youtube] Decrypted nsig 0daagqu-wduSMY_li => CDvG7K6EQzhSbw
[debug] Invoking downloader on 'https://rr1---sn-4vguioxu-n3bz.googlevideo.com/videoplayback?ip=REDACTED&mime=video%2Fmp4&itag=22&vprv=1&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&mh=wq&ms=au%2Crdu&lsig=AG3C_xAwRgIhAOM6wcd2ezyVS9rqxReAOvWaILbB_gxv0yx47YO5U-HeAiEA147nNw9IBwQ0hdmjDyseTbE8SI5YMs5-QSpeai68--M%3D&pl=21&mvi=1&ratebypass=yes&cnr=14&txp=4432434&initcwndbps=628750&lmt=1665609760634930&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&fvip=4&ns=jGuZYjQfqAWLOMd7_Y9AN64I&expire=1666325139&n=CDvG7K6EQzhSbw&mv=m&id=o-AEwtmKu2wva4gjXTO3bUTWNlS67PeqiiAXN2m9VDAUz8&mt=1666303018&fexp=24001373%2C24007246&ei=M8ZRY5fKHNyO1gKF3a_IBA&source=youtube&dur=9019.234&requiressl=yes&sig=AOq0QJ8wRAIgbqTL11T4CY3pOowEnUbzb_Swc9BZe6lXa7F6G8AIbCsCIDbd764NOVKQ81ra51vmBq0ruV4eYYpNqqJ77tUckTX1&c=WEB&mn=sn-4vguioxu-n3bz%2Csn-nv47lnsy&mm=31%2C29'
[download] Destination: Hyvi? uutisia! vko 38_2022  -  MANSEN M?RIN?T ERIKOISL?HETYS!-oaUC5vk2lKc.mp4
[download]   1.1% of 1.12GiB at  1.08MiB/s ETA 17:21
```

**Comment by dirkf** [comment]
That's as expected. In #30990, the errors typically disappeared after a few days, interpreted as the time taken for the full encoding of the video to be propagated to enough of the G servers that getting a bad copy is quite unlikely.

**Comment by dirkf** [comment]
Continued in #31247 (403 rather than 404, but I hope the same cause).
