### ISSUE TITLE
NDR Download not working

### ISSUE THREAD

**Issue by vschwaberow** [ytdl-org/youtube-dl#31271]
## Checklist

- [X ] I'm reporting a new site support request
- [X ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that none of provided URLs violate any copyrights
- [ X] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.ndr.de/fernsehen/sendungen/hallo_niedersachsen/Polizei-stoppt-Klima-Aktivisten-auf-der-A2,hallonds75878.html

## Description

Mediathek of NDR - German television

**Comment by dirkf** [comment]
Already supported:
```shellsession
$ python -m youtube_dl -v -F 'https://www.ndr.de/fernsehen/sendungen/hallo_niedersachsen/Polizei-stoppt-Klima-Aktivisten-auf-der-A2,hallonds75878.html'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.ndr.de/fernsehen/sendungen/hallo_niedersachsen/Polizei-stoppt-Klima-Aktivisten-auf-der-A2,hallonds75878.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: f838f3805
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[ndr] Polizei-stoppt-Klima-Aktivisten-auf-der-A2: Downloading webpage
[ndr:embed] hallonds75878: Downloading JSON metadata
[ndr:embed] hallonds75878: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 400: Bad Request
[ndr:embed] hallonds75878: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 502: Bad Gateway
[info] Available formats for hallonds75878:
format code  extension  resolution note
l            mp4        unknown    
xl           mp4        unknown    (best)
$
```
Please show verbose log of failure to continue the issue.

**Comment by vschwaberow** [comment]
```
youtube-dl -v -F 'https://www.ndr.de/fernsehen/sendungen/hallo_niedersachsen/Polizei-stoppt-Klima-Aktivisten-auf-der-A2,hallonds75878.html'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.ndr.de/fernsehen/sendungen/hallo_niedersachsen/Polizei-stoppt-Klima-Aktivisten-auf-der-A2,hallonds75878.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - macOS-12.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3, rtmpdump 2.4
[debug] Proxy map: {}
[ndr] Polizei-stoppt-Klima-Aktivisten-auf-der-A2: Downloading webpage
[generic] hallonds75878-ardplayer: Requesting header
WARNING: Falling back on generic information extractor.
[generic] hallonds75878-ardplayer: Downloading webpage
[generic] hallonds75878-ardplayer: Extracting information
ERROR: Unsupported URL: https://www.ndr.de/fernsehen/sendungen/hallo_niedersachsen/hallonds75878-ardplayer.html
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/generic.py", line 3489, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.ndr.de/fernsehen/sendungen/hallo_niedersachsen/hallonds75878-ardplayer.html
```

**Comment by dirkf** [comment]
Thanks. The difference is PR #30531. For the moment you can install the git master, which includes these fixes, using _pip3_.

**Comment by vschwaberow** [comment]
Thank you for your quick help.
