### ISSUE TITLE
Netease music throws error if downloading geo-restriction song (without handling it)

### ISSUE THREAD

**Issue by TimG233** [ytdl-org/youtube-dl#31298]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[netease:song] 1296550461: Downloading song info
[netease:song] 1296550461: Downloading JSON metadata
Traceback (most recent call last):
  File "... \netease_test.py", line 55, in <module>
    info = ydl.extract_info(url='https://music.163.com/#/song?id=1296550461', download=False)
  File "... \venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "... \venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "... \venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "... \venv\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "... \venv\lib\site-packages\youtube_dl\extractor\neteasemusic.py", line 212, in _real_extract
    formats = self.extract_formats(info)
  File "... \venv\lib\site-packages\youtube_dl\extractor\neteasemusic.py", line 119, in extract_formats
    if self._is_valid_url(song_url, info['id'], 'song'):
  File "...\ venv\lib\site-packages\youtube_dl\extractor\common.py", line 1469, in _is_valid_url
    if not (url.startswith('http://') or url.startswith('https://')):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

## Description

The Netease extractor can download the song with no geo-restriction. But if the song with geo-restriction, it will throw this error instead of handling and sending a note in the terminal.
Also, besides this handling issue, it seems like the extractor still fail for extracting the geo-restricted song **with a proxy in China** (I did it in YDL_opt as `'proxy': 'user:pw@ip:port'` format). I am not sure this is not supported or this is an issue with my proxy.
(blocking example: `https://music.163.com/#/song?id=1807381939` | non-blocking example: `https://music.163.com/#/song?id=1456673752`)

**Comment by dirkf** [comment]
It shouldn't be possible for this to happen as `song_url` can't be `None`. Has the `extractor/neteasemusic.py` file been modified, or is it an old version?

Please post a full verbose log using the released version, eg:
```
youtube-dl -v -F "https://music.163.com/#/song?id=1456673752"
```

**Comment by TimG233** [comment]
**It works properly with the non-blocking example, but the error that I had shown above is from blocking example.** (User doesn't know if the song blocking or not because the link (e.g: `https://music.163.com/#/song?id=1807381939`) is still working in the browser though audio playing is prohibited).
The version of `neteasemusic.py` and `aes.py` that I used is also the newest version in the repo (9 days ago update, not `2021.12.17` update)
Full verbose log for `https://music.163.com/#/song?id=1807381939`:
```
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 735cf45
[debug] Python version 3.9.12 (CPython) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 2021-11-25-git-522f577d7e-full_build-www.gyan.dev, ffprobe 2021-11-25-git-522f577d7e-full_build-www.gyan.dev
[debug] Proxy map: {}
[netease:song] 1807381939: Downloading song info
[netease:song] 1807381939: Downloading JSON metadata
Traceback (most recent call last):
  File "... \netease_test.py", line 57, in <module>
    info = ydl.extract_info(url='https://music.163.com/#/song?id=1807381939', download=False)
  File "... \venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "... \venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "... \venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "... \venv\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "... \venv\lib\site-packages\youtube_dl\extractor\neteasemusic.py", line 212, in _real_extract
    formats = self.extract_formats(info)
  File "... \venv\lib\site-packages\youtube_dl\extractor\neteasemusic.py", line 119, in extract_formats
    if self._is_valid_url(song_url, info['id'], 'song'):
  File "... \venv\lib\site-packages\youtube_dl\extractor\common.py", line 1469, in _is_valid_url
    if not (url.startswith('http://') or url.startswith('https://')):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

The code for producing the logs is:
```
YDL_OPTIONS = {'format': 'bestaudio/best', 'noplaylist': True, 'verbose': True, 'list-formats': True}

with YoutubeDL(YDL_OPTIONS) as ydl:
    info = ydl.extract_info(url='https://music.163.com/#/song?id=1807381939', download=False)
    print(info)
```

**Comment by TimG233** [comment]
I also sent a new issue #31301 about neteasemusic.py download error with a proxy, which is a different issue from this. This issue shows neteasemusic.py pops error with `AttributeError: 'NoneType' object has no attribute 'startswith'` if downloading a geo-restricted song **without proxy**. And #31301 shows a ytdl broken bug if downloading a geo-restricted song with a proxy in mainland China.

**Comment by dirkf** [comment]
Thanks, that explains it.

If I fix the crash `'NoneType' object has no attribute 'startswith'` at l.119, 
```diff
             for song in try_get(data, lambda x: x['data'], list) or []:
                 song_url = try_get(song, lambda x: x['url'])
-                if self._is_valid_url(song_url, info['id'], 'song'):
+                if song_url and self._is_valid_url(song_url, info['id'], 'song'):
                     formats.append({
```
we get this instead:
```shellsession
$ python3 -m youtube_dl -v -F 'https://music.163.com/#/song?id=1807381939'
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://music.163.com/#/song?id=1807381939']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: fdb16c0d6
[debug] Python version 3.9.14 (CPython) - Linux-4.4.0-210-generic-i686-with-glibc2.23
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[netease:song] 1807381939: Downloading song info
[netease:song] 1807381939: Downloading JSON metadata
[netease:song] 1807381939: Downloading JSON metadata
[netease:song] 1807381939: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/df/Documents/src/youtube-dl/youtube_dl/YoutubeDL.py", line 816, in wrapper
    return func(self, *args, **kwargs)
  File "/home/df/Documents/src/youtube-dl/youtube_dl/YoutubeDL.py", line 837, in __extract_info
    ie_result = ie.extract(url)
  File "/home/df/Documents/src/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/df/Documents/src/youtube-dl/youtube_dl/extractor/neteasemusic.py", line 213, in _real_extract
    self._sort_formats(formats)
  File "/home/df/Documents/src/youtube-dl/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$
```
The `data` returned as JSON metadata (l.116) looks like this:
```py
{'code': 200,
 'data': [{...
           'code': 404,
           ...
           # no URL here
         }]
}
```
In a successful case (eg https://music.163.com/#/song?id=1456673752), `code` is 200 (success) and there is a URL. Presumably 404 means that the site couldn't retrieve the playable song in its back-end processing.

With some error trapping the output can be like this:
```shellsession
...
ERROR: No media links found (site code 404)
Traceback (most recent call last):
  File "/home/df/Documents/src/youtube-dl/youtube_dl/YoutubeDL.py", line 816, in wrapper
    return func(self, *args, **kwargs)
  File "/home/df/Documents/src/youtube-dl/youtube_dl/YoutubeDL.py", line 837, in __extract_info
    ie_result = ie.extract(url)
  File "/home/df/Documents/src/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/df/Documents/src/youtube-dl/youtube_dl/extractor/neteasemusic.py", line 212, in _real_extract
    'id': song_id,
  File "/home/df/Documents/src/youtube-dl/youtube_dl/extractor/neteasemusic.py", line 132, in extract_formats
    raise ExtractorError(
youtube_dl.utils.ExtractorError: No media links found (site code 404)

```

CC: @xyb

**Comment by xyb** [comment]
@TimG233 @dirkf I added some defensive code: #31303
