### ISSUE TITLE
dailymotion.com video fails with 404 error at 17.9% on every attempt

### ISSUE THREAD

**Issue by mapellegrini** [ytdl-org/youtube-dl#31308]
## Checklist

- [ x] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
$ youtube-dl -v -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" https://www.dailymotion.com/embed/video/x6ch52f
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', u'https://www.dailymotion.com/embed/video/x6ch52f']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-126-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] Downloading Access Token
[dailymotion] x6ch52f: Downloading media JSON metadata
[dailymotion] x6ch52f: Downloading metadata JSON
[dailymotion] x6ch52f: Downloading m3u8 information
[debug] Invoking downloader on u'https://proxy-022.ix7.dailymotion.com/sec(1ICCrY_cXAxLyAXL9Xg4h-s1qPgKdEzldLFoDtkSD6mo88G4Zmh5HT7eENko-x_V9UTUBKq_ZKFdBf5ESvk6vQ)/video/761/257/383752167_mp4_h264_aac_hd_2.mp4'
[download] Destination: Soviet Storm׃ WW2 in the East 15_18 - The Secret War-x6ch52f.mp4
[download]  17.9% of 671.96MiB at 337.44KiB/s ETA 27:54[download] Got server HTTP error: Downloaded 125829120 bytes, expected 704603235 bytes. Retrying (attempt 1 of 10)...
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1976, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
HTTPError: HTTP Error 404: Not Found
```

## Description

Original URL: https://watchdocumentaries.com/soviet-storm-ww2-in-the-east/?video_index=14

I inspected the source code for each episode, extracted the video source URL, and downloaded them. All of them worked except episode 15, which fails at 17.9% every time. The source URL is https://www.dailymotion.com/embed/video/x6ch52f

Attempts to resume after a failed download immediately error out.

**Comment by dirkf** [comment]
Probably, the format is broken in the DM CDN, as in #29867.

All the formats found by yt-dl for this item are combined AVC1+AAC/MP4 streams. Your format option will have selected format `http-720-1`:
```
...
hls-720-0    mp4        1280x720   2149k , avc1.64001f, mp4a.40.2
hls-720-1    mp4        1280x720   2149k , avc1.64001f, mp4a.40.2
http-720-0   mp4        1280x720   2149k , avc1.64001f, mp4a.40.2
http-720-1   mp4        1280x720   2149k , avc1.64001f, mp4a.40.2 (best)
```
Try one of the other 720p formats, eg `-f hls-720-0`. If the 720p formats  all fail, try the similarly named 480p formats, then the 380p (which worked in #29867), ...

**Comment by dirkf** [comment]
Closing as duplicate: please reopen if there is new evidence to contradict that.
