### ISSUE TITLE
Neteasemusic.py shows "no video formats found" if using a proxy to download the geo-restricted song

### ISSUE THREAD

**Issue by TimG233** [ytdl-org/youtube-dl#31301]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 735cf45
[debug] Python version 3.9.12 (CPython) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 2021-11-25-git-522f577d7e-full_build-www.gyan.dev, ffprobe 2021-11-25-git-522f577d7e-full_build-www.gyan.dev
[debug] Proxy map: {'http': '112.6.117.178:8085', 'https': '112.6.117.178:8085'}
[netease:song] 1296550461: Downloading song info
[netease:song] 1296550461: Downloading JSON metadata
[netease:song] 1296550461: Downloading JSON metadata
[netease:song] 1296550461: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "... \venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "... \venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "... \venv\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "... \venv\lib\site-packages\youtube_dl\extractor\neteasemusic.py", line 213, in _real_extract
    self._sort_formats(formats)
  File "... \venv\lib\site-packages\youtube_dl\extractor\common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Traceback (most recent call last):
  File "... \venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "... \venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "... \venv\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "... \venv\lib\site-packages\youtube_dl\extractor\neteasemusic.py", line 213, in _real_extract
    self._sort_formats(formats)
  File "... \venv\lib\site-packages\youtube_dl\extractor\common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "... \netease_test.py", line 56, in <module>
    info = ydl.extract_info(url='https://music.163.com/#/song?id=1296550461', download=False)
  File "... \venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "... \venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "... \venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "... \venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Process finished with exit code 1

```

## Description

Netease music restricts playing many songs geologically for places outside of mainland China. With using a proxy in China (`112.6.117.178:8085`, checked by a geolocation site, located in Shandong, China). But ytdl shows no video formats found. I am not sure this is a bug with ytdl extractor or a bug of its proxy option.
The version of ytdl that I use is `2021.12.17`, and the `neteasemusic.py` and `aes.py` are the latest. (since there is an update these two files 9 days ago).
Code for producing the log:
```
YDL_OPTIONS = {'format': 'bestaudio/best', 'noplaylist': True, 'verbose': True, 'list-formats': True, 'proxy': '112.6.117.178:8085',  'force-ipv4': True}

with YoutubeDL(YDL_OPTIONS) as ydl:
    info = ydl.extract_info(url='https://music.163.com/#/song?id=1807381939', download=False)
    print(info)
```

**Comment by dirkf** [comment]
If you can, please set a break at l.119 of `extractor/neteasemusic.py` and display the value of `song_url` (maybe the whole `song` dict too - there may be 3 hits, one for each format b, m, h). Then we can tell whether the value(s) is actually not a valid URL or is being wrongly classified.

CC: @xyb

**Comment by TimG233** [comment]
It doesn't have any `song` or `song_url` since the `data` at l.116 is an empty dict. So, it won't even enter the `try_get` for-loop. It just skips it.

The print in `neteasemusic.py` (l.116 - l.127 originally)
```
...
            data = self._call_player_api(song_id, bitrate)
            print(f"data: {data}")
            for song in try_get(data, lambda x: x['data'], list) or []:
                print(f"song: {song}")
                song_url = try_get(song, lambda x: x['url'])
                if song_url and self._is_valid_url(song_url, info['id'], 'song'):
                    formats.append({
                        'url': song_url,
                        'ext': details.get('extension'),
                        'abr': float_or_none(song.get('br'), scale=1000),
                        'format_id': song_format,
                        'filesize': int_or_none(song.get('size')),
                        'asr': int_or_none(details.get('sr')),
                    })
            print("end of loop")
...
```

The terminal log (I didn't include all the errors text at the end, same error as posted above)
```
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 735cf45
[debug] Python version 3.9.12 (CPython) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 2021-11-25-git-522f577d7e-full_build-www.gyan.dev, ffprobe 2021-11-25-git-522f577d7e-full_build-www.gyan.dev
[debug] Proxy map: {'http': '112.6.117.178:8085', 'https': '112.6.117.178:8085'}
[netease:song] 1807381939: Downloading song info
[netease:song] 1807381939: Downloading JSON metadata
data: {}
end of loop
[netease:song] 1807381939: Downloading JSON metadata
data: {}
end of loop
[netease:song] 1807381939: Downloading JSON metadata
data: {}
end of loop
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
... more error text (same as the one above)
```

**Comment by dirkf** [comment]
Great, or not, perhaps. In that case, the extractor is behaving as expected. Maybe there's some HTTP code that's being masked in `_call_player_api()` immediately above. You could change the method like this to get better diagnostics:
```diff
         try:
-            return self._download_json(
+            msg = 'empty result'
+            result = self._download_json(
                 url, song_id, data=data.encode('ascii'), headers=headers)
+            if not result:
+                return result
         except ExtractorError as e:
             if type(e.cause) in (ValueError, TypeError):
                 # JSON load failure
                 raise
-        except Exception:
-            pass
+        except Exception as e:
+            from ..utils import error_to_compat_str
+            msg = error_to_compat_str(e)
+        self.report_warning('API call (%s, %s, %s) failed: %s' % (url, song_id, bitrate, msg))
         return {}
```

**Comment by TimG233** [comment]
Seems like it will pop out a warning showing the `empty result` of API call.
```
[netease:song] 1807381939: Downloading JSON metadata
WARNING: [netease:song] API call (https://interface3.music.163.com/eapi/song/enhance/player/url, 1807381939, 128000) failed: empty result
```

**Comment by dirkf** [comment]
So they're not telling you why you can't have the music, just returning an empty result. Unfortunately I don't know much about the site beyond what the extractor does.

What happens if you try to access the song URL with a browser?

Do you need an account that could be passed to yt-dl using browser cookies with `--cookies ...`?

**Comment by xyb** [comment]
@TimG233 Thanks for your report. I have double checked and the download function is working fine on both the China and US servers. And I also reproduced the error using your proxy server, so I added some suggestions in the log message: #31298 Hope these can help you.

**Comment by xyb** [comment]
@dirkf @TimG233 My guess is that Netease is not only blocking foreign addresses, but also blocking the IP addresses of some cloud platform providers within China. So not any Chinese IP can access Netease service normally.

**Comment by TimG233** [comment]
@xyb Thank you so much for the suggestions and defensive codes! Therefore, I have one last question (as mentioned by dirkf), if the proxy is working correctly (assumed), does Netease music check for the cookies, or does it only check for a "valid" IP address?

**Comment by xyb** [comment]
@TimG233 From my observations, the songs involved here are directly downloadable without special settings on my servers in China and the US; however, if the proxy service you gave earlier is set up, then an error is reported. I guess your proxy service should not be suitable for use here. So for this song, Netease only checks the IP address, cookies don't matter. But I also see that Netease has VIP songs, for example: https://music.163.com/#/song?id=32102397 . I guess downloading it requires cookies from users with play access to do so.
