### ISSUE TITLE
unable to download Platzi video with youtube-dl version 2021.12.17

### ISSUE THREAD

**Issue by rokmanhaman** [ytdl-org/youtube-dl#31315]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

e description is worded well enough to be understood, see https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

WRITE DESCRIPTION HERE

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--sleep-interval', '10', '--max-sleep-interval', '15', '--limit-rate', '1M', '-o', '%(playlist_index)s-%(chapter_number)s-%(title)s-%(resolution)s.%(ext)s', '--verbose', 'https://platzi.com/clases/1927-intro-selenium/29383-bienvenida-al-curso']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.15.0-52-generic-x86_64-with-glibc2.35
[debug] exe versions: none
[debug] Proxy map: {}
[Platzi] Downloading login page
[Platzi] Logging in
[Platzi] 29383: Downloading webpage
ERROR: Unable to extract client data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/rok/.local/lib/	
    return func(self, *args, **kwargs)
  File "/home/rok/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/rok/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/rok/.local/lib/python3.10/site-packages/youtube_dl/extractor/platzi.py", line 109, in _real_extract
    self._search_regex(
  File "/home/rok/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract client data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--sleep-interval', '10', '--max-sleep-interval', '15', '--limit-rate', '1M', '-o', '%(playlist_index)s-%(chapter_number)s-%(title)s-%(resolution)s.%(ext)s', '--verbose', 'https://platzi.com/clases/1927-intro-selenium/29383-bienvenida-al-curso']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.15.0-52-generic-x86_64-with-glibc2.35
[debug] exe versions: none
[debug] Proxy map: {}
[Platzi] Downloading login page
[Platzi] Logging in
[Platzi] 29383: Downloading webpage
ERROR: Unable to extract client data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/rok/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rok/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/rok/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/rok/.local/lib/python3.10/site-packages/youtube_dl/extractor/platzi.py", line 109, in _real_extract
    self._search_regex(
  File "/home/rok/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract client data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
Apparently a duplicate of #28536 which has an associated PR #30548.

**Comment by dirkf** [comment]
The updated PR code handles the problem URL as below:
```shellsession
$ python -m youtube_dl -v -F 'https://platzi.com/clases/1927-intro-selenium/29383-bienvenida-al-curso'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://platzi.com/clases/1927-intro-selenium/29383-bienvenida-al-curso']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: fdb16c0d6
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[Platzi] 29383: Downloading webpage
[Platzi] 29383: Downloading serverA MPD manifest
[Platzi] 29383: Downloading serverA m3u8 information
[Platzi] 29383: Downloading serverB MPD manifest
[Platzi] 29383: Downloading serverB m3u8 information
[Platzi] 29383: Downloading serverC m3u8 information
[info] Available formats for 29383:
format code                 extension  resolution note
hls-audio-aac_UND_2_128-0   mp4        audio only 
hls-audio-aac_UND_2_128-1   mp4        audio only 
dash-5_A_aac_UND_2_128_1-0  m4a        audio only DASH audio  127k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-5_A_aac_UND_2_128_1-1  m4a        audio only DASH audio  127k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-1_V_video_2-0          mp4        1280x720   DASH video  605k , mp4_dash container, avc1.42C01F, video only
dash-1_V_video_2-1          mp4        1280x720   DASH video  605k , mp4_dash container, avc1.42C01F, video only
hls-766-0                   mp4        1280x720    766k , avc1.42c01f, video only
hls-766-1                   mp4        1280x720    766k , avc1.42c01f, video only
dash-1_V_video_1-0          mp4        1920x1080  DASH video 1360k , mp4_dash container, avc1.42C028, video only
dash-1_V_video_1-1          mp4        1920x1080  DASH video 1360k , mp4_dash container, avc1.42C028, video only
hls-1537-0                  mp4        1920x1080  1537k , avc1.42c028, video only
hls-1537-1                  mp4        1920x1080  1537k , avc1.42c028, video only
hls-595                     mp4        1280x720    595k , avc1.42000d, mp4a.40.5
hls-1326                    mp4        1920x1080  1326k , avc1.42000d, mp4a.40.5 (best)
$
```
Please test and follow up in #30548.

**Comment by developcreativo** [comment]
@dirkf not working python -m youtube_dl -v -F 'https://platzi.com/clases/1927-intro-selenium/29383-bienvenida-al-curso'

**Comment by jadv1** [comment]
Same issue with me with different video:
\Videos>youtube-dl_2021.12.17.exe --verbose https://youtu.be/o1dq8H-2kLs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://youtu.be/o1dq8H-2kLs']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 3.4
[debug] Proxy map: {}
[youtube] o1dq8H-2kLs: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Obluchatel** [comment]
Same issue:
[youtube] Downloading just video QCv2udN2z2Y because of --no-playlist
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2023-04-10 20:43:43 ERROR    discord.ext.commands.bot Ignoring exception in command play
Traceback (most recent call last):
  File "C:\Users\kakab\PycharmProjects\pythonProject6\venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\kakab\PycharmProjects\pythonProject6\venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\kakab\PycharmProjects\pythonProject6\venv\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\kakab\PycharmProjects\pythonProject6\venv\lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "C:\Users\kakab\PycharmProjects\pythonProject6\venv\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
