### ISSUE TITLE
Add support for player.vod2.infomaniak.com/

### ISSUE THREAD

**Issue by yann1108** [ytdl-org/youtube-dl#31329]
## Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs violate any copyrights
- [X] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

## Description

youtube-dl -v https://player.vod2.infomaniak.com/embed/1jhvl2uqg6ywp

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://player.vod2.infomaniak.com/embed/1jhvl2uqg6ywp']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-131-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 1jhvl2uqg6ywp: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1jhvl2uqg6ywp: Downloading webpage
[generic] 1jhvl2uqg6ywp: Extracting information
ERROR: Unsupported URL: https://player.vod2.infomaniak.com/embed/1jhvl2uqg6ywp
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/generic.py", line 3489, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://player.vod2.infomaniak.com/embed/1jhvl2uqg6ywp

THANKS FOR YOUR WORK

**Comment by dirkf** [comment]
The problem URL has no useful data in the non-JS page the yt-dl sees, but loading it in a browser with JS enabled for vod2.infomaniak.com leads to this player JSON URL: https://res.vod2.infomaniak.com/1/vod/share/1jhvl2uqg6ywp.

Without studying the 1.5MB 1-line script, one might guess that this is formed by
1. changing the leading domain part to `res`
2. adding the first digit of the video ID `1jhvl2uqg6ywp` as the first path component
3. completing the path with `vod/share/{video_id}`.

Media links are found at `.data.media[].source.url` in the JSON, along with metadata such as title, duration.

**Comment by zhuasy** [comment]
Hey there! I'm currently a student in college and as part of my final project, I'm required to make contributions to an open-source project and write a report on my experiences (and inform the maintainers) . Could I take this issue?
