### ISSUE TITLE
Assistance downloading from Box url where extractor is not working 

### ISSUE THREAD

**Issue by xnileshx** [ytdl-org/youtube-dl#31337]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm not sure but im told that this might need update to the extractor
I'm hoping if someone could help me see if they are able to download from https://sunsetlearning.app.box.com/s/23inj0thkhosu34xqpg85v9rs4zgudqk/file/876001645317
All of my attempts have failed. Maybe I'm doing it wrong. 

```
C:\>youtube-dl https://sunsetlearning.app.box.com/s/23inj0thkhosu34xqpg85v9rs4zgudqk/file/875996902995 extractor Box

[Box] 875996902995: Downloading webpage
[Box] 875996902995: Downloading token JSON metadata
[Box] 875996902995: Downloading file JSON metadata
ERROR: unable to download video data: HTTP Error 403: Forbidden
```

Verbose

```
C:\Users\admin\Videos>youtube-dl https://sunsetlearning.app.box.com/s/23inj0thkhosu34xqpg85v9rs4zgudqk/file/876001645317 extractor Box -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://sunsetlearning.app.box.com/s/23inj0thkhosu34xqpg85v9rs4zgudqk/file/876001645317', 'extractor', 'Box', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2022-11-03-git-5ccd4d3060-full_build-www.gyan.dev, ffprobe 2022-11-03-git-5ccd4d3060-full_build-www.gyan.dev
[debug] Proxy map: {}
[Box] 876001645317: Downloading webpage
[Box] 876001645317: Downloading token JSON metadata
[Box] 876001645317: Downloading file JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://dl2.boxcloud.com/api/2.0/files/876001645317/content?access_token=1%216q7lXhrXftVRrsDHMLg4OGPDJcKBJ8yCrdR_MgbEvfCFJNDRjyb4AK6foQCDgyJYDtnGa-_DeHI6A2XOyGjGVF8wk6P9mxBYCkeqHojdX9HyMhaKonlCZBKgpZ4I0M8lboW0-cnvNIE5KPecWGw0zqSz65PFpRd_wSd0pycsv6Mk_vCZn4KXWy6LwmzpcAfh7-AvhZyqke0Wf1EwnkOZmfLFjieEcZMIN0xmAndvAE2l1zFnz-pU7sXCpif3E5f6iWh4v8fQ7YcEAQYBrG4ow_ROkXt7XYYlwkIc0OSCJF9o_8aO3YCQlGBRikrDRirTPB8JUj2b5aZn0LqzdIsc9_Q0o87cm1QzriOWaQiGrzhMw1UdFMCUti4MaoZJnLIMbGK6J1YssTi73G6rrScR_fpv_NvkFf3jeak_W_JhpWQGfnKdcvXLqR1z9hQ7z3RTFmWeXv9siku5VO5wYOUU0yAhzjUNvY0RlfRHD-6Vg_99JyPUwk4tyip6GpY6-LGimXxsXKO0lpS2YPS4ycLxWPPZBxaNaVp_4YZYeQcXL-tOQtZfZBvrSuA7nMmgibhkogNP&shared_link=https%3A%2F%2Fapp.box.com%2Fs%2F23inj0thkhosu34xqpg85v9rs4zgudqk'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 1976, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 1915, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\downloader\http.py", line 351, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\downloader\http.py", line 116, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\downloader\http.py", line 110, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

I have seen clearing cache solves this for some websites but did not work in this case. 
'youtube-dl --rm-cache-dir' was a nogo

I would appreciate any assistance with this, thanks.

**Comment by dirkf** [comment]
You have extraneous command parameters `extractor Box`, but yt-dl failed before trying to process these "URL"s.

Is this video playing in your browser in a private tab? I'm getting 400 and 403 codes in the browser.

If it plays for you, but not, or only after authenticating, in a private tab, try passing the browser cookies using `--cookies ...`.

yt-dlp, with essentially identical extractor code, shows the same behaviour.

**Comment by october262** [comment]
found this reddit thread - https://www.reddit.com/r/youtubedl/comments/xooryo/segmented_videom4s_from_appboxcom/

**Comment by dirkf** [comment]
The extractor does handle the token stuff as mentioned by the Redditors, but still gets a 403.

It looks like the mp4 video is set up to be downloadable only when logged in. JSON data including permissions to that level of granularity is fetched in the browser, but the extractor doesn't check that.

The DASH manifest could be streamable, but the code to do that is commented out. It needs to have the token-y query added to each downloaded fragment URL, but this doesn't work, because the Python `urlparse.urljoin()` library function that is used in the yt-dl utility function `urljoin()` doesn't replace a missing query part in the joined URL with the query part from the base URL.

We can finish the job that the extractor author left as `# TODO`; also, updating some things to match what's actually seen in a browser session:
```diff
--- old/youtube_dl/extractor/box.py
+++ new/youtube_dl/extractor/box.py
@@ -8,8 +8,9 @@
 from ..utils import (
     determine_ext,
     parse_iso8601,
-    # try_get,
+    try_get,
     update_url_query,
+    urljoin,
 )
 
 
@@ -36,12 +37,16 @@
             r'Box\.config\s*=\s*({.+?});', webpage,
             'Box config'), file_id)['requestToken']
         access_token = self._download_json(
-            'https://app.box.com/app-api/enduserapp/elements/tokens', file_id,
+            urljoin(url, '/app-api/enduserapp/elements/tokens'), file_id,
             'Downloading token JSON metadata',
             data=json.dumps({'fileIDs': [file_id]}).encode(), headers={
                 'Content-Type': 'application/json',
+                'Request-Token': request_token,
                 'X-Request-Token': request_token,
                 'X-Box-EndUser-API': 'sharedName=' + shared_name,
+                'X-Box-Client-Name': 'enduserapp',
+                'X-Box-Client-Version': '20.926.2',
+                'Referer': url,
             })[file_id]['read']
         shared_link = 'https://app.box.com/s/' + shared_name
         f = self._download_json(
@@ -49,7 +54,8 @@
             'Downloading file JSON metadata', headers={
                 'Authorization': 'Bearer ' + access_token,
                 'BoxApi': 'shared_link=' + shared_link,
-                'X-Rep-Hints': '[dash]',  # TODO: extract `hls` formats
+                'X-Rep-Hints': '[dash,mp4]',  # TODO: extract `hls` formats
+                'Referer': url,
             }, query={
                 'fields': 'authenticated_download_url,created_at,created_by,description,extension,is_download_available,name,representations,size'
             })
@@ -62,17 +68,25 @@
 
         formats = []
 
-        # for entry in (try_get(f, lambda x: x['representations']['entries'], list) or []):
-        #     entry_url_template = try_get(
-        #         entry, lambda x: x['content']['url_template'])
-        #     if not entry_url_template:
-        #         continue
-        #     representation = entry.get('representation')
-        #     if representation == 'dash':
-        #         TODO: append query to every fragment URL
-        #         formats.extend(self._extract_mpd_formats(
-        #             entry_url_template.replace('{+asset_path}', 'manifest.mpd'),
-        #             file_id, query=query))
+        for entry in (try_get(f, lambda x: x['representations']['entries'], list) or []):
+            entry_url_template = try_get(
+                entry, lambda x: x['content']['url_template'])
+            if not entry_url_template:
+                continue
+            representation = entry.get('representation')
+            if representation == 'dash':
+                # append query to every fragment URL
+                dash_fmts = self._extract_mpd_formats(
+                    update_url_query(entry_url_template.replace('{+asset_path}', 'manifest.mpd'), query),
+                    file_id, query=query, mpd_id='dash')
+                for f in dash_fmts:
+                    base = f['fragment_base_url']
+                    for frag in f['fragments']:
+                        frag['url'] = update_url_query(
+                            urljoin(base, frag.get('path') or frag.get('url')),
+                            query)
+                        f.pop('path', None)
+                formats.extend(dash_fmts)
 
         authenticated_download_url = f.get('authenticated_download_url')
         if authenticated_download_url and f.get('is_download_available'):
@@ -81,6 +95,7 @@
                 'filesize': f.get('size'),
                 'format_id': 'download',
                 'url': update_url_query(authenticated_download_url, query),
+                'http_headers': {'Referer': url},
             })
 
         self._sort_formats(formats)
```
Then
```
$ python -m youtube_dl -v --test  'https://sunsetlearning.app.box.com/s/23inj0thkhosu34xqpg85v9rs4zgudqk/file/876001645317'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--test', u'https://sunsetlearning.app.box.com/s/23inj0thkhosu34xqpg85v9rs4zgudqk/file/876001645317']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: fdb16c0d6
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[Box] 876001645317: Downloading webpage
[Box] 876001645317: Downloading token JSON metadata
[Box] 876001645317: Downloading file JSON metadata
[Box] 876001645317: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://dl2.boxcloud.com/api/2.0/internal_files/876001645317/versions/941459440917/representations/dash/content/manifest.mpd?access_token=1%2133ZC_kFiFWIXPRoZhx7sjGmR6LL9KeCmkMz_CkNVBwPrbUA0FTocp8XcedV5tNjqyO1Upu1iPacBCQzzmW1lpifW0UJ1G-F9KjfYpop8pWEVF2KaN9A1JB1fjnAx660obu7dZnBxQzvdWvcc0Gdx_nrcnAInkrDJGjN7szZRvlHDn6Ie93D_Uu87dABWGWBHzQtG_thAikE7VpmGYn2uWe6wPsZgfUl6ErbXq5rsTE4sdTKjAGLN94Egg5tFcFuFMkkXGHNmrA8nAzVARdi-DO5tOq7TTVGgeuQmY55hzxo1ok-cblaJBCV0oYgiIqllqYXOhwb3RixtAQiJvNStwS4RCrOQuo8msGmZHFHUKcTNPz6wSR8_okDP6920X4stNdgo2-iaRREU2-ZRp-BF2UabqIA9ri1r9VxrtWwtroyzcB9ytMXOS7fy4L9xskTsbNfUOHpbDK9gQhiTgd5x6itbdMMmeAV84R5-IRLIoxfSyDSsgTwjxBPlq5-nHfA7-c-E5ZCQVtprblufqLVpzJNlOdT9xLqWuVAmyl7lZhfe4N5hrQrNwxUck0PJJdRjRVa0&shared_link=https%3A%2F%2Fapp.box.com%2Fs%2F23inj0thkhosu34xqpg85v9rs4zgudqk'
[download] ENCOR Day 1 Part 1.mp4-876001645317.fdash-0.mp4 has already been downloaded
[download] 100% of 806.00B
[debug] Invoking downloader on u'https://dl2.boxcloud.com/api/2.0/internal_files/876001645317/versions/941459440917/representations/dash/content/manifest.mpd?access_token=1%2133ZC_kFiFWIXPRoZhx7sjGmR6LL9KeCmkMz_CkNVBwPrbUA0FTocp8XcedV5tNjqyO1Upu1iPacBCQzzmW1lpifW0UJ1G-F9KjfYpop8pWEVF2KaN9A1JB1fjnAx660obu7dZnBxQzvdWvcc0Gdx_nrcnAInkrDJGjN7szZRvlHDn6Ie93D_Uu87dABWGWBHzQtG_thAikE7VpmGYn2uWe6wPsZgfUl6ErbXq5rsTE4sdTKjAGLN94Egg5tFcFuFMkkXGHNmrA8nAzVARdi-DO5tOq7TTVGgeuQmY55hzxo1ok-cblaJBCV0oYgiIqllqYXOhwb3RixtAQiJvNStwS4RCrOQuo8msGmZHFHUKcTNPz6wSR8_okDP6920X4stNdgo2-iaRREU2-ZRp-BF2UabqIA9ri1r9VxrtWwtroyzcB9ytMXOS7fy4L9xskTsbNfUOHpbDK9gQhiTgd5x6itbdMMmeAV84R5-IRLIoxfSyDSsgTwjxBPlq5-nHfA7-c-E5ZCQVtprblufqLVpzJNlOdT9xLqWuVAmyl7lZhfe4N5hrQrNwxUck0PJJdRjRVa0&shared_link=https%3A%2F%2Fapp.box.com%2Fs%2F23inj0thkhosu34xqpg85v9rs4zgudqk'
[dashsegments] Total fragments: 1
[download] Destination: ENCOR Day 1 Part 1.mp4-876001645317.fdash-2.m4a
[download] 100% of 738.00B in 00:01
[ffmpeg] Merging formats into "ENCOR Day 1 Part 1.mp4-876001645317.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:ENCOR Day 1 Part 1.mp4-876001645317.fdash-0.mp4' -i 'file:ENCOR Day 1 Part 1.mp4-876001645317.fdash-2.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:ENCOR Day 1 Part 1.mp4-876001645317.temp.mp4'
Deleting original file ENCOR Day 1 Part 1.mp4-876001645317.fdash-0.mp4 (pass -k to keep)
Deleting original file ENCOR Day 1 Part 1.mp4-876001645317.fdash-2.m4a (pass -k to keep)
$
```
