### ISSUE TITLE
Can't download from tv2ostjylland.dk

### ISSUE THREAD

**Issue by hcgrove** [ytdl-org/youtube-dl#31347]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.tv2ostjylland.dk/nyhedsudsendelser?clip=326b07d8-b4fc-4e4e-be3a-c807ba5832e9']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-18-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0
[debug] Proxy map: {}
[TV2DK] nyhedsudsendelser: Downloading webpage
ERROR: Unable to extract kaltura id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/grove/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/grove/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/grove/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/grove/bin/youtube-dl/youtube_dl/extractor/tv2dk.py", line 93, in _real_extract
    kaltura_id = self._search_regex(
  File "/home/grove/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract kaltura id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I tried to download 'https://www.tv2ostjylland.dk/nyhedsudsendelser?clip=326b07d8-b4fc-4e4e-be3a-c807ba5832e9' ((a part of) a news broadcast in danish), it didn't work, and youtube-dl said to report it, so I'm doing so.

When I clicked the "New issue" button on the github page that I was redirected to from the link youtube-dl had outputted, I was asked to choose between 6 categories, as I've succesfully used this version of youtube-dl many times to download from other sites, I guess that the issue is related to the support of this particular site, and hope I've chosen the right category by that. If not you can move this issue or close it as you see fit.

**Comment by dirkf** [comment]
Thanks. I can see that this isn't working.

There aren't any test URLs like this news clip. The known tv2.dk URLs use Kaltura for the video (eg https://www.tv2lorry.dk/gadekamp/gadekamp-6-hoejhuse-i-koebenhavn from the last update), but this page doesn't seem to have the `entryId` for the video. My best guess from the Nuxt.js hydration data was 44173791, giving kaltura:2102081:1_44173791, but that's no good. Open to offers.

**Comment by october262** [comment]
video can be downloaded via the m3u8 file https://cdn-lt-hls-vod.tv2oj.dk/fhls/p/2102081/sp/210208100/serveFlavor/entryId/1_u7e3akz4/v/1/pv/1/ev/6/flavorId/1_boo9qjvh/name/a.mp4/index.m3u8
if fails with youtube-dl but works with yt-dlp

**Comment by dirkf** [comment]
So that looks like kaltura:2102081:1_u7e3akz4, which does work in yt-dl, but whence the `u7e3akz4`? This text is not apparently in the page. Presumably there is a lookup transaction where the clip id is turned into the the Kaltura entryId.

**Comment by october262** [comment]
> So that looks like kaltura:2102081:1_u7e3akz4, which does work in yt-dl, but whence the `u7e3akz4`? This text is not apparently in the page. Presumably there is a lookup transaction where the clip id is turned into the the Kaltura entryId.

there's also this here - https://cdnapisec.kaltura.com/p/2102081/sp/210208100/playManifest/entryId/1_u7e3akz4/protocol/https/format/applehttp/flavorIds/1_olqqcjln,1_lk0ullel,1_aqngx8jk,1_a1eub9yl,1_boo9qjvh/a.m3u8?uiConfId=44173791&playSessionId=aa6e8b5d-9c1c-22d0-c252-44d172a33f17:1d89e4f8-caa9-c2b3-bb3f-c4dd5a22cc2e&referrer=aHR0cHM6Ly93d3cudHYyb3N0anlsbGFuZC5kay9ueWhlZHN1ZHNlbmRlbHNlcj9jbGlwPTMyNmIwN2Q4LWI0ZmMtNGU0ZS1iZTNhLWM4MDdiYTU4MzJlOQ==&clientTag=html5:v7.55
