### ISSUE TITLE
ERROR: WARNING: unable to obtain file audio codec with ffprobe

### ISSUE THREAD

**Issue by Aromik** [ytdl-org/youtube-dl#31355]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', '-x', '--audio-format', 'mp3', 'http://www.youtube.com/playlist?list=PLPdMQYt4XeT3fNqs2ZM8xD7fkBfO05NUj']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.7.9 (CPython) - Darwin-22.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg present, ffprobe present, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] PLPdMQYt4XeT3fNqs2ZM8xD7fkBfO05NUj: Downloading webpage
[download] Downloading playlist: Фонотека
[youtube:tab] Downloading page 1
[youtube:tab] playlist Фонотека: Downloading 165 videos
[download] Downloading video 1 of 165
[youtube] zc2sIu0kB5k: Downloading webpage
[debug] Invoking downloader on 'https://rr3---sn-nx8xon3t-83ve.googlevideo.com/videoplayback?expire=1668479627&ei=K6ZyY-T-DML97ATiioGQCw&ip=81.200.16.188&id=o-AK0AF5XzHJGFnl1i5iE4z0cc1yBH3IeqJqeMbGfaAoFM&itag=251&source=youtube&requiressl=yes&mh=G8&mm=31%2C29&mn=sn-nx8xon3t-83ve%2Csn-n8v7znlr&ms=au%2Crdu&mv=m&mvi=3&pl=23&initcwndbps=1520000&vprv=1&mime=audio%2Fwebm&ns=abV6r3Ja_GCrE7Jo6Z3IJa0J&gir=yes&clen=66881842&dur=3682.241&lmt=1651944244002464&mt=1668457785&fvip=8&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5432434&n=bRrAovSaSbG9-ccaPNq&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAPba80BNbQb-5KdxwBjyHWkaWUqBYnsJA1968nZzDcxJAiEA7_BMk9El5R2getfOplz9RzWIDjYV3OAebHZMK161TA4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAIzmZknz1mHeJ8_6X_fcF8POyNW_ZdNRnUl4a8-HvBZYAiEA2tj50B6oItwqe479WWLNpZys3t04GQkqNNXqs6OaN0g%3D'
[download] Stone Rebel - Trinity (2022) [Full Album]-zc2sIu0kB5k.webm has already been downloaded
[download] 100% of 63.78MiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:Stone Rebel - Trinity (2022) [Full Album]-zc2sIu0kB5k.webm'
ERROR: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2115, in post_process
    files_to_delete, info = pp.run(info)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 277, in run
    raise PostProcessingError('WARNING: unable to obtain file audio codec with ffprobe')
youtube_dl.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe

```

## Description

I am trying to download a playlist using YouTube_dl.
But I get the error with ffprobe. I've searched similar issues, most of them are for Windows, I'm working with Mac OS. The only similar thing I found was #13398, but the solution from there didn't work.

**Comment by dirkf** [comment]
Presumably there is a problem with your _ffmpeg_ installation. Please tell us what _ffmpeg_ you have: `ffprobe --version` will do.

The debug line containing `ffprobe present` indicates that yt-dl tried to run that command and the command didn't fail, but the output was in an unexpected format. If the command is behaving strangely, that may also be happening when yt-dl tries to use _ffprobe_ to check which audio codec is in use.

You could also download the problem video (use `--playlist-item 1`) and try the failing command shown in the debug log: `ffprobe -show_streams 'file:Stone Rebel - Trinity (2022) [Full Album]-zc2sIu0kB5k.webm'`.

**Comment by Aromik** [comment]
When I try to do `ffprobe --version`, I get the following:
`ffprobe --version
dyld[71241]: Library not loaded: /opt/homebrew/opt/rav1e/lib/librav1e.0.5.dylib
  Referenced from: <27B0B520-BEFF-3B64-865E-95215A815251> /opt/homebrew/Cellar/ffmpeg/5.1.2/bin/ffprobe
  Reason: tried: '/opt/homebrew/opt/rav1e/lib/librav1e.0.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/rav1e/lib/librav1e.0.5.dylib' (no such file), '/opt/homebrew/opt/rav1e/lib/librav1e.0.5.dylib' (no such file), '/usr/local/lib/librav1e.0.5.dylib' (no such file), '/usr/lib/librav1e.0.5.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/rav1e/0.5.1/lib/librav1e.0.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/rav1e/0.5.1/lib/librav1e.0.5.dylib' (no such file), '/opt/homebrew/Cellar/rav1e/0.5.1/lib/librav1e.0.5.dylib' (no such file), '/usr/local/lib/librav1e.0.5.dylib' (no such file), '/usr/lib/librav1e.0.5.dylib' (no such file, not in dyld cache)
zsh: abort      ffprobe --version`

**Comment by dirkf** [comment]
Clearly it's broken, so you need to do whatever Homebrew requires to reinstall it, or use one of the solutions that a basic web search for `ffmpeg MacOS` will offer, or try a MacOS support forum.

The function that detects _ffmpeg_ and other dependent utilities ought to return a different string, like `broken`, if the test command fails (return code != 0), rather than `present`.

**Comment by dirkf** [comment]
Some patch like this should be applied:
```diff
--- old/youtube_dl/utils.py
+++ new/youtube_dl/utils.py
@@ -3828,15 +3828,21 @@
         ext)
 
 
-def check_executable(exe, args=[]):
-    """ Checks if the given binary is installed somewhere in PATH, and returns its name.
-    args can be a list of arguments for a short output (like -version) """
+def _check_executable(exe, args=[], check_result=True):
     try:
-        process_communicate_or_kill(subprocess.Popen(
-            [exe] + args, stdout=subprocess.PIPE, stderr=subprocess.PIPE))
+        p = subprocess.Popen(
+            [exe] + args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
+        process_communicate_or_kill(p)
+        if check_result and (p.returncode != 0):
+            return None
     except OSError:
         return False
     return exe
+
+def check_executable(exe, args=[], check_result=False):
+    """ Checks if the given binary is installed somewhere in PATH, and returns its name.
+    args can be a list of arguments for a short output (like -version) """
+    return _check_executable(exe, args=args, check_result=check_result)
 
 
 def get_exe_version(exe, args=['--version'],
@@ -3847,10 +3853,13 @@
         # STDIN should be redirected too. On UNIX-like systems, ffmpeg triggers
         # SIGTTOU if youtube-dl is run in the background.
         # See https://github.com/ytdl-org/youtube-dl/issues/955#issuecomment-209789656
-        out, _ = process_communicate_or_kill(subprocess.Popen(
+        p = subprocess.Popen(
             [encodeArgument(exe)] + args,
             stdin=subprocess.PIPE,
-            stdout=subprocess.PIPE, stderr=subprocess.STDOUT))
+            stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
+        out, _ = process_communicate_or_kill(p)
+        if p.returncode != 0:
+            return '**broken**'
     except OSError:
         return False
     if isinstance(out, bytes):  # Python 2.x
@@ -5888,8 +5897,8 @@
             except EnvironmentError as e:
                 raise XAttrMetadataError(e.errno, e.strerror)
         else:
-            user_has_setfattr = check_executable('setfattr', ['--version'])
-            user_has_xattr = check_executable('xattr', ['-h'])
+            user_has_setfattr = _check_executable('setfattr', ['--version'], check_result) or False
+            user_has_xattr = _check_executable('xattr', ['-h']) or False
 
             if user_has_setfattr or user_has_xattr:
 

```

**Comment by Aromik** [comment]
> Some patch like this should be applied:
> 
> ```diff
> --- old/youtube_dl/utils.py
> +++ new/youtube_dl/utils.py
> @@ -3828,15 +3828,21 @@
>          ext)
>  
>  
> -def check_executable(exe, args=[]):
> -    """ Checks if the given binary is installed somewhere in PATH, and returns its name.
> -    args can be a list of arguments for a short output (like -version) """
> +def _check_executable(exe, args=[], check_result=True):
>      try:
> -        process_communicate_or_kill(subprocess.Popen(
> -            [exe] + args, stdout=subprocess.PIPE, stderr=subprocess.PIPE))
> +        p = subprocess.Popen(
> +            [exe] + args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
> +        process_communicate_or_kill(p)
> +        if check_result and (p.returncode != 0):
> +            return None
>      except OSError:
>          return False
>      return exe
> +
> +def check_executable(exe, args=[], check_result=False):
> +    """ Checks if the given binary is installed somewhere in PATH, and returns its name.
> +    args can be a list of arguments for a short output (like -version) """
> +    return _check_executable(exe, args=args, check_result=check_result)
>  
>  
>  def get_exe_version(exe, args=['--version'],
> @@ -3847,10 +3853,13 @@
>          # STDIN should be redirected too. On UNIX-like systems, ffmpeg triggers
>          # SIGTTOU if youtube-dl is run in the background.
>          # See https://github.com/ytdl-org/youtube-dl/issues/955#issuecomment-209789656
> -        out, _ = process_communicate_or_kill(subprocess.Popen(
> +        p = subprocess.Popen(
>              [encodeArgument(exe)] + args,
>              stdin=subprocess.PIPE,
> -            stdout=subprocess.PIPE, stderr=subprocess.STDOUT))
> +            stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
> +        out, _ = process_communicate_or_kill(p)
> +        if p.returncode != 0:
> +            return '**broken**'
>      except OSError:
>          return False
>      if isinstance(out, bytes):  # Python 2.x
> @@ -5888,8 +5897,8 @@
>              except EnvironmentError as e:
>                  raise XAttrMetadataError(e.errno, e.strerror)
>          else:
> -            user_has_setfattr = check_executable('setfattr', ['--version'])
> -            user_has_xattr = check_executable('xattr', ['-h'])
> +            user_has_setfattr = _check_executable('setfattr', ['--version'], check_result) or False
> +            user_has_xattr = _check_executable('xattr', ['-h']) or False
>  
>              if user_has_setfattr or user_has_xattr:
>  
> ```

Ok, I shall try to do it myself because I guess the official patch won't be as fast

**Comment by dirkf** [comment]
Fixing ffprobe is necessary for you to be able use any features of yt-dl that use it.

The fix that I'm considering will just prevent yt-dl from reporting that a broken ffprobe (eg) is `present`. With a bit more work, it could be made to act on that so that instead of trying to run the broken program it would report that you aren't able to use that feature without a working version (as happens if the program is not found).
