### ISSUE TITLE
youku vedio download failure

### ISSUE THREAD

**Issue by cathaychen** [ytdl-org/youtube-dl#31384]
线程启动 2
线程启动 1
线程启动 5
server start localhost =  localhost , port =  5678
--------------当前没有下载任务--------------
recv_text  [{"url":"https://v.youku.com/v_show/id_XNTE5MTQ5OTQ4NA==.html?spm=a2h0c.8166622.PhoneSokuUgc_8.dscreenshot","fileName":"常式太极拳_108_式-体育-高清完整正版视频在线观看-优酷","islist":false,"youtube":true}]
[17:55:13] 线程 4 开始下载视频 : https://v.youku.com/v_show/id_XNTE5MTQ5OTQ4NA==.html?spm=a2h0c.8166622.PhoneSokuUgc_8.dscreenshot
CallYoutubeDownload 4 https://v.youku.com/v_show/id_XNTE5MTQ5OTQ4NA==.html?spm=a2h0c.8166622.PhoneSokuUgc_8.dscreenshot 
[youku] XNTE5MTQ5OTQ4NA: Retrieving cna info
[youku] XNTE5MTQ5OTQ4NA: Downloading JSON metadata
Error in connection handler
Traceback (most recent call last):
  File "site-packages\websockets\server.py", line 191, in handler
  File "webserver.py", line 486, in main_logic
  File "site-packages\websockets\protocol.py", line 439, in __aiter__
  File "site-packages\websockets\protocol.py", line 509, in recv
  File "site-packages\websockets\protocol.py", line 812, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code [internal]), no reason
ERROR: Youku server reported error -6001: ccode参数错误; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[17:55:24] 线程 4 文件下载完毕 : 4 https://v.youku.com/v_show/id_XNTE5MTQ5OTQ4NA==.html?spm=a2h0c.8166622.PhoneSokuUgc_8.dscreenshot
用时 : 10.81044340133667 秒 https://v.youku.com/v_show/id_XNTE5MTQ5OTQ4NA==.html?spm=a2h0c.8166622.PhoneSokuUgc_8.dscreenshot
--------------当前没有下载任务--------------

**Comment by dirkf** [comment]
For help with this, open a new issue by completing [this template](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md).
