### ISSUE TITLE
videa.hu: RegexNotFoundError: Unable to extract nonce;

### ISSUE THREAD

**Issue by bvirg** [ytdl-org/youtube-dl#31386]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://videa.hu/videok/film-animacio/wSTnXnWfh6EpBZLr']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.4 (CPython) - Linux-5.15.0-47-generic-x86_64-with-glibc2.35
[debug] exe versions: avconv 4.4.2, avprobe 4.4.2, ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[Videa] animacio/wSTnXnWfh6EpBZLr: Downloading webpage
ERROR: Unable to extract nonce; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/user/.local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/.local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/user/.local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/user/.local/bin/youtube-dl/youtube_dl/extractor/videa.py", line 102, in _real_extract
    nonce = self._search_regex(
  File "/home/user/.local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract nonce; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

There seems to be a RegexNotFoundError when trying to download a video from the specific site

**Comment by dirkf** [comment]
Reproducible in release version; fixed in git master, presumably since merging PR #30621.
