### ISSUE TITLE
[YouTube] Failed to parse JSON

### ISSUE THREAD

**Issue by antes857** [ytdl-org/youtube-dl#31383]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--extract-audio', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=m5sGROCRiDs', '--verbose']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev, ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] m5sGROCRiDs: Downloading webpage
[youtube] m5sGROCRiDs: Downloading API JSON
ERROR: m5sGROCRiDs: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 906, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 906, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1503, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 295, in _call_api
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 899, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 883, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 910, in _parse_json
youtube_dl.utils.ExtractorError: m5sGROCRiDs: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

failed to download mp3

**Comment by dirkf** [comment]
1. Please complete all the checkboxes or explain why an item doesn't apply.
2. You seem to have a network issue where something is causing a request for a JSON resource to return nothing. Perhaps some network proxy, antivirus, or ISP or State censorship is involved. The `Downloading API JSON` is only reached when the actual YT page was unexpectedly malformed (or empty), so the problem probably applies to all YT URLs.
3. WFM
```shell
$ youtube-dl -v -F  'https://www.youtube.com/watch?v=m5sGROCRiDs'
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.youtube.com/watch?v=m5sGROCRiDs']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
Removing cache dir /home/df/.cache/youtube-dl ...
[youtube] m5sGROCRiDs: Downloading webpage
[youtube] m5sGROCRiDs: Downloading player 4eb6b35d
[info] Available formats for m5sGROCRiDs:
format code  extension  resolution note
249          webm       audio only tiny   50k , webm_dash container, opus @ 50k (48000Hz), 2.08MiB
250          webm       audio only tiny   67k , webm_dash container, opus @ 67k (48000Hz), 2.77MiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 5.29MiB
251          webm       audio only tiny  133k , webm_dash container, opus @133k (48000Hz), 5.43MiB
160          mp4        256x144    144p   24k , mp4_dash container, avc1.4d400c@  24k, 25fps, video only, 1011.61KiB
278          webm       256x144    144p   50k , webm_dash container, vp9@  50k, 25fps, video only, 2.06MiB
242          webm       426x240    240p   45k , webm_dash container, vp9@  45k, 25fps, video only, 1.85MiB
133          mp4        426x240    240p   46k , mp4_dash container, avc1.4d4015@  46k, 25fps, video only, 1.91MiB
134          mp4        640x360    360p   86k , mp4_dash container, avc1.4d401e@  86k, 25fps, video only, 3.54MiB
243          webm       640x360    360p   87k , webm_dash container, vp9@  87k, 25fps, video only, 3.58MiB
135          mp4        854x480    480p  133k , mp4_dash container, avc1.4d401e@ 133k, 25fps, video only, 5.44MiB
244          webm       854x480    480p  137k , webm_dash container, vp9@ 137k, 25fps, video only, 5.62MiB
136          mp4        1280x720   720p  220k , mp4_dash container, avc1.4d401f@ 220k, 25fps, video only, 8.99MiB
247          webm       1280x720   720p  240k , webm_dash container, vp9@ 240k, 25fps, video only, 9.81MiB
248          webm       1920x1080  1080p  413k , webm_dash container, vp9@ 413k, 25fps, video only, 16.89MiB
137          mp4        1920x1080  1080p  778k , mp4_dash container, avc1.640028@ 778k, 25fps, video only, 31.80MiB
18           mp4        640x360    360p  215k , avc1.42001E, 25fps, mp4a.40.2 (44100Hz) (best)
$
```

**Comment by brudra0** [comment]
I'm also facing the similar issue.

```
PS E:\EDUCATION\Bhaskar\Networking\YouTube> .\youtube-dl.exe "https://app.pluralsight.com/library/courses/excel-2019-pro/table-of-contents" --username "xxxx" --password "xxxx" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://app.pluralsight.com/library/courses/excel-2019-pro/table-of-contents', '--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] excel-2019-pro: Downloading JSON metadata
[pluralsight:course] excel-2019-pro: Downloading JSON metadata
ERROR: excel-2019-pro: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 906, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 906, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\pluralsight.py", line 467, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\pluralsight.py", line 93, in _download_course
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 899, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 883, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 910, in _parse_json
youtube_dl.utils.ExtractorError: excel-2019-pro: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

PS E:\EDUCATION\Bhaskar\Networking\YouTube> .\youtube-dl.exe --version
2021.12.17
```

**Comment by dirkf** [comment]
No, because that's not YouTube. Your problem is the same as #30765.

**Comment by dirkf** [comment]
Closing for lack of response.
