### ISSUE TITLE
Can't download Iqiyi.com 

### ISSUE THREAD

**Issue by tobyfirst** [ytdl-org/youtube-dl#31397]
C:\Users\XXXXXi>C:\Users\XXXX\Desktop\youtube-dl.exe https://www.iqiyi.com/w_19rrzixid9.html --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.iqiyi.com/w_19rrzixid9.html', '--verbose']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
ERROR: Can't find any video; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\iqiyi.py", line 352, in _real_extract
youtube_dl.utils.ExtractorError: Can't find any video; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
Reproduces with git master, and with yt-dlp. Check that the issue [here](https://github.com/ytdl-org/youtube-dl/issues/29237) does not apply.

Otherwise changes similar to those suggested in https://github.com/yt-dlp/yt-dlp/issues/2740 may be needed.

**Comment by dirkf** [comment]
Yes, that works:
```
$ python -m youtube_dl -v -F 'https://www.iqiyi.com/w_19rrzixid9.html'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.iqiyi.com/w_19rrzixid9.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 774b346f9
[debug] Python version 2.7.18 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] ec8c2b94f499662aad70497ecb8e6b52: Downloading JSON metadata
[iqiyi] ec8c2b94f499662aad70497ecb8e6b52: Downloading m3u8 information
[iqiyi] ec8c2b94f499662aad70497ecb8e6b52: Downloading m3u8 information
[info] Available formats for ec8c2b94f499662aad70497ecb8e6b52:
format code  extension  resolution note
hls-0        mp4        unknown    
hls-1        mp4        unknown    (best)
$
```
PR to appear.
