### ISSUE TITLE
Paramount+ a few links are returning extractor errors for no video formats found

### ISSUE THREAD

**Issue by Go1den** [ytdl-org/youtube-dl#31423]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
H:\TV\Amazing Race\Season 34>youtube-dl https://www.paramountplus.com/shows/x/video/BLfZ2NmOdC6s7ESNp1lrtdzaxF9cKRMB/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.paramountplus.com/shows/x/video/BLfZ2NmOdC6s7ESNp1lrtdzaxF9cKRMB/', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-10-11-git-90a0da9f14-full_build-www.gyan.dev, ffprobe 2021-10-11-git-90a0da9f14-full_build-www.gyan.dev
[debug] Proxy map: {}
[CBS] BLfZ2NmOdC6s7ESNp1lrtdzaxF9cKRMB: Downloading XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "b:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "b:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "b:\python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "b:\python39\lib\site-packages\youtube_dl\extractor\cbs.py", line 115, in _real_extract
    return self._extract_video_info(content_id)
  File "b:\python39\lib\site-packages\youtube_dl\extractor\cbs.py", line 97, in _extract_video_info
    self._sort_formats(formats)
  File "b:\python39\lib\site-packages\youtube_dl\extractor\common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


H:\TV\Amazing Race\Season 34>youtube-dl https://www.paramountplus.com/shows/x/video/pTnw2RN7hMRYy4wruTBs4DeIFJOGBp91/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.paramountplus.com/shows/x/video/pTnw2RN7hMRYy4wruTBs4DeIFJOGBp91/', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-10-11-git-90a0da9f14-full_build-www.gyan.dev, ffprobe 2021-10-11-git-90a0da9f14-full_build-www.gyan.dev
[debug] Proxy map: {}
[CBS] pTnw2RN7hMRYy4wruTBs4DeIFJOGBp91: Downloading XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "b:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "b:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "b:\python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "b:\python39\lib\site-packages\youtube_dl\extractor\cbs.py", line 115, in _real_extract
    return self._extract_video_info(content_id)
  File "b:\python39\lib\site-packages\youtube_dl\extractor\cbs.py", line 97, in _extract_video_info
    self._sort_formats(formats)
  File "b:\python39\lib\site-packages\youtube_dl\extractor\common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


H:\TV\Amazing Race\Season 34>youtube-dl https://www.paramountplus.com/shows/x/video/fp0UpBYmsWgsJEn6kIZKKLqd2CIL2xGQ/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.paramountplus.com/shows/x/video/fp0UpBYmsWgsJEn6kIZKKLqd2CIL2xGQ/', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-10-11-git-90a0da9f14-full_build-www.gyan.dev, ffprobe 2021-10-11-git-90a0da9f14-full_build-www.gyan.dev
[debug] Proxy map: {}
[CBS] fp0UpBYmsWgsJEn6kIZKKLqd2CIL2xGQ: Downloading XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "b:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "b:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "b:\python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "b:\python39\lib\site-packages\youtube_dl\extractor\cbs.py", line 115, in _real_extract
    return self._extract_video_info(content_id)
  File "b:\python39\lib\site-packages\youtube_dl\extractor\cbs.py", line 97, in _extract_video_info
    self._sort_formats(formats)
  File "b:\python39\lib\site-packages\youtube_dl\extractor\common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


H:\TV\Amazing Race\Season 34>youtube-dl https://www.paramountplus.com/shows/x/video/hR9MY_yNXnGb_MOsSuVuyyeD55cIYe0H/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.paramountplus.com/shows/x/video/hR9MY_yNXnGb_MOsSuVuyyeD55cIYe0H/', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-10-11-git-90a0da9f14-full_build-www.gyan.dev, ffprobe 2021-10-11-git-90a0da9f14-full_build-www.gyan.dev
[debug] Proxy map: {}
[CBS] hR9MY_yNXnGb_MOsSuVuyyeD55cIYe0H: Downloading XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "b:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "b:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "b:\python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "b:\python39\lib\site-packages\youtube_dl\extractor\cbs.py", line 115, in _real_extract
    return self._extract_video_info(content_id)
  File "b:\python39\lib\site-packages\youtube_dl\extractor\cbs.py", line 97, in _extract_video_info
    self._sort_formats(formats)
  File "b:\python39\lib\site-packages\youtube_dl\extractor\common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I've been able to successfully download from Paramount+ in most cases, but for these few videos I am experiencing an Extractor Error that says no video formats were found. I am able to watch each of these episodes on Paramount+ without issue. Note that I am inserting the /x/ in each URL as downloading from Paramount+ doesn't work unless some dummy string is inserted between shows and video, but removing that /x/ and navigating to those links works fine.

**Comment by dirkf** [comment]
Other pages that are handled by the CBS extractor are typically only offering DRM-encumbered formats. That is true for https://www.paramountplus.com/shows/x/video/fp0UpBYmsWgsJEn6kIZKKLqd2CIL2xGQ/.

See #31361.
