### ISSUE TITLE
Site xvideos.com not downloading amateur-channels

### ISSUE THREAD

**Issue by draconis10** [ytdl-org/youtube-dl#31451]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
C:\!Scripts>youtube-dl -o "Z:\Smut\Test\%(title)s.%(ext)s" --cookies C:\!Scripts\cookies.txt --no-post-overwrites --fixup never --yes-playlist -f bestvideo[ext=mp4]+bestaudio/best[ext=mp4]/best --merge-output-format mp4 -ciw "https://www.xvideos.com/amateur-channels/closeupfantasy#_tabVideos"
[generic] closeupfantasy#_tabVideos: Requesting header
WARNING: Falling back on generic information extractor.
[generic] closeupfantasy#_tabVideos: Downloading webpage
[generic] closeupfantasy#_tabVideos: Extracting information
ERROR: Unsupported URL: https://www.xvideos.com/amateur-channels/closeupfantasy#_tabVideos

```

## Description

Site xvideos.com not downloading amateur-channels on Windows 10 using youtube_dl-2021.12.17, showing as unsupported URL

**Comment by dirkf** [comment]
The **flag** is `--verbose`, not `--verbose flag`!

Your issue is solved by PR #30774:
```
$ python -m youtube_dl -v -F 'https://www.xvideos.com/amateur-channels/closeupfantasy#_tabVideos'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.xvideos.com/amateur-channels/closeupfantasy#_tabVideos']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 774b346f9
[debug] Python version 2.7.18 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[XVideosChannel] closeupfantasy: Downloading webpage
[XVideosChannel] closeupfantasy: Downloading webpage
[XVideosChannel] closeupfantasy (+1): Downloading webpage
[XVideosChannel] closeupfantasy (+2): Downloading webpage
[XVideosChannel] closeupfantasy (+3): Downloading webpage
[XVideosChannel] closeupfantasy (+4): Downloading webpage
[XVideosChannel] closeupfantasy (+5): Downloading webpage
[download] Downloading playlist: closeupfantasy
[XVideosChannel] playlist closeupfantasy: Collected 196 video ids (downloading 196 of them)
[download] Downloading video 1 of 196
[XVideos] 74104369: Downloading webpage
[XVideos] 74104369: Downloading m3u8 information
[XVideos] 74104369: Checking hls-480p video format URL
[XVideos] 74104369: Checking hls-720p video format URL
[XVideos] 74104369: Checking hls-1080p video format URL
[XVideos] 74104369: Checking hls-360p video format URL
[XVideos] 74104369: Checking hls-250p video format URL
[info] Available formats for 74104369:
format code  extension  resolution note
mp4-low      mp4        unknown    
mp4-high     mp4        unknown    
hls-250p     mp4        444x250     155k 
hls-360p     mp4        640x360     423k 
hls-480p     mp4        854x480     763k 
hls-720p     mp4        1280x720   1327k 
hls-1080p    mp4        1920x1080  2760k  (best)
[download] Downloading video 2 of 196
[XVideos] 69496273: Downloading webpage
[XVideos] 69496273: Downloading m3u8 information
...
```

**Comment by draconis10** [comment]
Sorry see below...

C:\!Scripts>youtube-dl --verbose https://www.xvideos.com/amateur-channels/closeupfantasy#_tabVideos
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.xvideos.com/amateur-channels/closeupfantasy#_tabVideos']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg n4.3.1-26-gca55240b8c, ffprobe n4.3.1-26-gca55240b8c, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] closeupfantasy#_tabVideos: Requesting header
WARNING: Falling back on generic information extractor.
[generic] closeupfantasy#_tabVideos: Downloading webpage
[generic] closeupfantasy#_tabVideos: Extracting information
ERROR: Unsupported URL: https://www.xvideos.com/amateur-channels/closeupfantasy#_tabVideos
Traceback (most recent call last):
  File "C:\Users\Test\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 816, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Test\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 837, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Test\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\extractor\common.py", line 535, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Test\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\extractor\generic.py", line 3685, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.xvideos.com/amateur-channels/closeupfantasy#_tabVideos

I'm using CMD and running youtube-dl --verbose flag https://www.xvideos.com/amateur-channels/closeupfantasy#_tabVideos - Like I said I've tried using the youtube-dl.exe and same problem there also

Tried also uninstalling/updating however still the same problem

**Comment by dirkf** [comment]
Yes, the problem is valid, and the linked PR, which you could test, fixes it.
