### ISSUE TITLE
Embedded vimeo video not downloading 

### ISSUE THREAD

**Issue by AronDarling** [ytdl-org/youtube-dl#31461]
- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
kg6ejp@ICD-IdeaPad-3:~/Videos$ youtube-dl https://go.maxwellleadership.com/your-future-is-now-replay-ty --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://go.maxwellleadership.com/your-future-is-now-replay-ty', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.15.0-56-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.3.1
[debug] Proxy map: {}
[generic] your-future-is-now-replay-ty: Requesting header
WARNING: Falling back on generic information extractor.
[generic] your-future-is-now-replay-ty: Downloading webpage
[generic] your-future-is-now-replay-ty: Extracting information
[download] Downloading playlist: Replay - Your Future Is Now - Maxwell Leadership Certified Team
[generic] playlist Replay - Your Future Is Now - Maxwell Leadership Certified Team: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[vimeo] 788057250: Downloading webpage
ERROR: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 651, in _real_extract
    config = self._parse_json(self._search_regex(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```
WRITE DESCRIPTION HERE

Tried to download from ytdl cli.
It appears to be a Vimeo video; I cannot get it to download though.

**Comment by dirkf** [comment]
This is #31311, fixed in git master, or use the work-around with ID `788057250`.
