### ISSUE TITLE
Crash on tagesschau.de

### ISSUE THREAD

**Issue by ogermer** [ytdl-org/youtube-dl#31477]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.tagesschau.de/inland/ukraine-baerbock-tagesthemen-101.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 3e257890d
[debug] Python version 3.11.1 (CPython) - macOS-13.1-arm64-arm-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Tagesschau] ukraine-baerbock-tagesthemen-101: Downloading webpage
Traceback (most recent call last):
  File "/opt/homebrew/bin/youtube-dl", line 33, in <module>
    sys.exit(load_entry_point('youtube-dl==2021.12.17', 'console_scripts', 'youtube-dl')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/__init__.py", line 475, in main
    _real_main(argv)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 2068, in download
    res = self.extract_info(
          ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/tagesschau.py", line 281, in _real_extract
    for num, (entry_title, media_kind, download_text) in enumerate(re.findall(
                                                                   ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py", line 216, in findall
    return _compile(pattern, flags).findall(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 84
```

## Description

Fresh install via homebrew.

youTube-dl crashes with this URL. 

Other URLs work fine.

**Comment by dirkf** [comment]
Python 3.11 is complaining about a not entirely correct regular expression in the Tagesschau extractor that was accepted by earlier versions, such as 2.7 and 3.9. However with earlier Python versions, or after fixing the regular expression, the extractor still fails on this URL:
```shellsession
$ python -m youtube_dl -v -F 'https://www.tagesschau.de/inland/ukraine-baerbock-tagesthemen-101.html'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.tagesschau.de/inland/ukraine-baerbock-tagesthemen-101.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 774b346f9
[debug] Python version 2.7.18 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[Tagesschau] ukraine-baerbock-tagesthemen-101: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/df/Documents/src/youtube-dl/youtube_dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "youtube_dl/__init__.py", line 475, in main
    _real_main(argv)
  File "youtube_dl/__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "youtube_dl/YoutubeDL.py", line 2077, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "youtube_dl/YoutubeDL.py", line 810, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "youtube_dl/YoutubeDL.py", line 817, in wrapper
    return func(self, *args, **kwargs)
  File "youtube_dl/YoutubeDL.py", line 838, in __extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 539, in extract
    ie_result = self._real_extract(url)
  File "youtube_dl/extractor/tagesschau.py", line 291, in _real_extract
    formats = entries[0]['formats']
IndexError: list index out of range
$
```
The extractor from yt-dlp works and needs to be back-ported. Then:
```shellsession
$ python -m youtube_dl -v -F 'https://www.tagesschau.de/inland/ukraine-baerbock-tagesthemen-101.html'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.tagesschau.de/inland/ukraine-baerbock-tagesthemen-101.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 774b346f9
[debug] Python version 2.7.18 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[Tagesschau] ukraine-baerbock-tagesthemen-101: Downloading webpage
[Tagesschau] ukraine-baerbock-tagesthemen-101: Downloading m3u8 information
[download] Downloading playlist: Baerbock nach Ukraine-Besuch: Verständnis für "Leopard"-Forderungen
[Tagesschau] playlist Baerbock nach Ukraine-Besuch: Verständnis für "Leopard"-Forderungen: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[info] Available formats for ukraine-baerbock-tagesthemen-101-1:
format code  extension  resolution note
hls-968      mp4        960x540     968k , avc1.4d401f, 25.0fps, mp4a.40.2
hls-432      mp4        480x270     432k , avc1.42c015, 25.0fps, mp4a.40.2
hls-699      mp4        640x360     699k , avc1.42c01e, 25.0fps, mp4a.40.2
hls-1614     mp4        1280x720   1614k , avc1.64001f, 25.0fps, mp4a.40.2
hls-2928     mp4        1920x1080  2928k , avc1.640028, 25.0fps, mp4a.40.2
hls-128      mp4        audio only  128k , mp4a.40.2 (best)
[download] Downloading video 2 of 2
[info] Available formats for ukraine-baerbock-tagesthemen-101-2:
format code  extension  resolution note
0            mp3        audio only 
[download] Finished downloading playlist: Baerbock nach Ukraine-Besuch: Verständnis für "Leopard"-Forderungen
$
```
> Other URLs work fine.

From tagesschau.de, or elsewhere?

**Comment by ogermer** [comment]
I tried YouTube and Twitter - both worked fine.
Tagesschau.de failed.
Thx for spotting the issue with 3.11

**Comment by dirkf** [comment]
OK, what I expected. For the moment please use yt-dlp for Tagesshchau. Unfortunately the back-port is a bit too complicated to post as a patch.

The yt-dlp extractor and my back-port find two separate videos (one actually just mp3) on the problem page. Is that correct? It seems to me that the MP3 item is a playlist item ("Auch wenn das Herz brennt - Baerbock verspricht keine Kampfpanzer") that should not be returned if `--no-playlist` is specified.

**Comment by ogermer** [comment]
If you visit the page at `https://www.tagesschau.de/inland/ukraine-baerbock-tagesthemen-101.html` you will find that they have the video in the upper part of the page and an mp3 with additional commentary close to the bottom.

Personally (without further investigating default behaviours of yotube-dl) I would have expected to have the "correct" video file returned by default - although guessing user intent is usually a bit hard. But a `--no-playlist` behaviour as outlined above would probably be ok for most users.

Fortunately my immediate need was solved as I missed the download link that was already offered on the page. ;-)

In the meantime I will have a look at yt-dlp.

**Comment by dirkf** [comment]
This page is typical of many sites where a featured video is accompanied by other media. yt-dl should extract the featured media by default, but the `--yes-playlist` option can't be used to select extracting all the media on the page instead because it actually only means`--no-no-playlist`: presumably this was useful for YouTube. So we have to do it backwards.
