### ISSUE TITLE
First time using pluradl.py which requires youtube-dl ,threw an error on when it was trying to download a course

### ISSUE THREAD

**Issue by GISSIAH** [ytdl-org/youtube-dl#31480]
## Verbose log

```

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--sleep-interval', '150', '--max-sleep-interval', '200', '--limit-rate', '1M', '-o', '%(playlist_index)s-%(chapter_number)s-%(title)s-%(resolution)s.%(ext)s', '--verbose', 'https://app.pluralsight.com/library/courses/ASP.NET Core 6 Fundamentals']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.1 (CPython) - Windows-10-10.0.19044-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] ASP.NET Core 6 Fundamentals: Downloading JSON metadata
[pluralsight:course] ASP.NET Core 6 Fundamentals: Downloading JSON metadata
ERROR: ASP.NET Core 6 Fundamentals: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\bmalunje\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\common.py", line 906, in _parse_json
    return json.loads(json_string)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmalunje\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmalunje\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmalunje\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\bmalunje\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\common.py", line 906, in _parse_json
    return json.loads(json_string)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmalunje\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmalunje\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmalunje\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bmalunje\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmalunje\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\bmalunje\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmalunje\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\pluralsight.py", line 467, in _real_extract
    course = self._download_course(course_id, url, course_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmalunje\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\pluralsight.py", line 90, in _download_course
    return self._download_json(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmalunje\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\common.py", line 895, in _download_json
    res = self._download_json_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmalunje\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\common.py", line 881, in _download_json_handle
    return self._parse_json(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\bmalunje\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\common.py", line 910, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: ASP.NET Core 6 Fundamentals: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

## Description

I ran python pluradl.py , after giving it my credentials ,it started getting metadata for a course and then it threw that error message

**Comment by dirkf** [comment]
1. Raise the issue at https://github.com/leethobbit/issues, but don't expect a resolution for the reasons below.
2. The above repo hasn't been updated since 2020, so the tool probably doesn't work due to site changes at PluralSight that yt-dl hasn't tracked.
4. If you try running yt-dl manually instead of using Pluraldl, try passing cookies from your logged-in browser session with `--cookies ...` and omit `--username ...`, `--password ...`.
3. PluralSight is a difficult target for yt-dl: you need an account to test and debug the extractor fully, it may demand Captcha solutions (in login, eg), and see https://github.com/ytdl-org/youtube-dl/issues/29234#issuecomment-1031382362.

**Comment by dirkf** [comment]
Closing for lack of response.
