### ISSUE TITLE
[bilibili.tv] Failed to extract the Video Information

### ISSUE THREAD

**Issue by Angu0083** [ytdl-org/youtube-dl#31491]
```
C:\Users\0>youtube-dl -v -F https://www.bilibili.tv/en/video/2043748658
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.bilibili.tv/en/video/2043748658']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.1 (CPython) - Windows-10-10.0.22621-SP0
[debug] exe versions: ffmpeg N-92418-gee47ac97d7
[debug] Proxy map: {}
[generic] 2043748658: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2043748658: Downloading webpage
[generic] 2043748658: Extracting information
ERROR: Unsupported URL: **https://www.bilibili.tv/en/video/204374865**8
Traceback (most recent call last):
  File "C:\Users\0\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\0\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\0\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\0\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\generic.py", line 3489, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: ### https://www.bilibili.tv/en/video/2043748658
```

**Comment by dirkf** [comment]
Thanks. I'd rather leave this open until we update the extractor.

**Comment by Angu0083** [comment]
Ok, It's good to hear.
