### ISSUE TITLE
Unable to extract info section on www.unexploredfilms.com

### ISSUE THREAD

**Issue by rangmrm** [ytdl-org/youtube-dl#31503]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: ['-o', 'C:\\Users\\Michael\\Videos\\Youtube/%(title)s.%(ext)s', '--restrict-filenames']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.unexploredfilms.com/papua-new-guinea-land-of-the-unexpected/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[generic] papua-new-guinea-land-of-the-unexpected: Requesting header
WARNING: Falling back on generic information extractor.
[generic] papua-new-guinea-land-of-the-unexpected: Downloading webpage
[generic] papua-new-guinea-land-of-the-unexpected: Extracting information
[download] Downloading playlist: Papua New Guinea: Land of The Unexpected - Unexplored Films
[generic] playlist Papua New Guinea: Land of The Unexpected - Unexplored Films: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[vimeo] 144288579: Downloading webpage
ERROR: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\vimeo.py", line 652, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

I was able to watch the video using Firefox browser, but not download using youtube-dl. Fingers crossed this is something very simple for you to fix. Many thanks for all your work. You-tube-dl is a brilliant piece of software.

**Comment by dirkf** [comment]
It's an embedded video hosted on Vimeo and the issue was already fixed in the git master: see 

Also. once you have the Vimeo ID `144288579`, you can form a URL that can be extracted without the fix, as discussed in the oriogi

**Comment by rangmrm** [comment]
Many thanks for your help.
It is very much appreciated.
