### ISSUE TITLE
Youtube: Unable to recognize tab page

### ISSUE THREAD

**Issue by mbch331** [ytdl-org/youtube-dl#31502]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
 youtube-dl --add-metadata --prefer-ffmpeg --write-info-json --write-sub --write-auto-sub --sub-format srt --sub-lang nl,en --external-downloader aria2c --external-downloader-args "-c -j 3 -x 3 -s 3 -k 1M" -o "%(uploader)s %(title)s {%(upload_date).4s}.%(ext)s" -f bestvideo+bestaudio/best  "https://www.youtube.com/shorts/DV7k019n6gI" --no-check-certificate --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--add-metadata', '--prefer-ffmpeg', '--write-info-json', '--write-sub', '--write-auto-sub', '--sub-format', 'srt', '--sub-lang', 'nl,en', '--external-downloader', 'aria2c', '--external-downloader-args', '-c -j 3 -x 3 -s 3 -k 1M', '-o', '%(uploader)s %(title)s {%(upload_date).4s}.%(ext)s', '-f', 'bestvideo+bestaudio/best', 'https://www.youtube.com/shorts/DV7k019n6gI', '--no-check-certificate', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.15.0-58-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[youtube:tab] shorts: Downloading webpage
ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/youtube.py", line 2862, in _real_extract
    raise ExtractorError('Unable to recognize tab page')
youtube_dl.utils.ExtractorError: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I'm trying to download a YouTube short. URL provided by YouTube is https://www.youtube.com/shorts/DV7k019n6gI and this fails. I get the error message Unable to recognize tab page.

**Comment by dirkf** [comment]
> I've searched the bugtracker for similar bug reports including closed ones

Yet, [duplicate](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+Unable+to+recognize+tab+page+-label%3Aduplicate) of #30269.
