### ISSUE TITLE
Downloading video from VK.COM returns HTTP error 404

### ISSUE THREAD

**Issue by docryte** [ytdl-org/youtube-dl#31512]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
/usr/bin/python3.10 /home/docryte/PycharmProjects/utilabot/bug.py 
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.7 (CPython) - Linux-5.19.0-29-generic-x86_64-with-glibc2.36
[debug] exe versions: none
[debug] Proxy map: {}
[vk] -60099869_456246720: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/vk.py", line 325, in _real_extract
    payload = self._download_payload('al_video', video_id, data)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/vk.py", line 67, in _download_payload
    code, payload = self._download_json(
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 895, in _download_json
    res = self._download_json_handle(
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 874, in _download_json_handle
    res = self._download_webpage_handle(
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 667, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 652, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docryte/PycharmProjects/utilabot/bug.py", line 11, in <module>
    get_video()
  File "/home/docryte/PycharmProjects/utilabot/bug.py", line 9, in get_video
    youtube_dl.YoutubeDL({'outtmpl': name, 'cookiefile': './cookies.txt', 'verbose': True}).download([video])
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Process finished with exit code 1

```
## Description

I try to download any [video](https://vk.com/video/@pitbullmonster?z=video-60099869_456246720%2Fclub60099869%2Fpl_-60099869_-2) from vk.com and It returns HTTP error 404 as you can see. I use cookies to log in. In cookies.txt I have only vk.com cookies I downloaded with Get cookies.txt addon for Chrome. The video and URL surely exist. The python code you can see here:

```
import youtube_dl


def get_video():
    message_chat_id = 'any int'
    message_id = message_chat_id
    name = './tmp/' + message_chat_id + "_" + message_id
    video = 'https://vk.com/video/@pitbullmonster?z=video-60099869_456246720%2Fclub60099869%2Fpl_-60099869_-2'
    youtube_dl.YoutubeDL({'outtmpl': name, 'cookiefile': './cookies.txt', 'verbose': True}).download([video])

get_video()
```

**Comment by atsen-dev** [comment]
Hi, I've almost the same issue as you 

Here my log on verbose : 

```
[youtube] Bl_xxxxxxx: Downloading webpage
WARNING: Unable to download webpage: <urlopen error [Errno -2] Name or service not known>
[youtube] Bl_xxxxxxx: Downloading API JSON
ERROR: Unable to download API page: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known')))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2735, in https_open
    return self.do_open(functools.partial(
  File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open

```

**Comment by atsen-dev** [comment]
My issue seems to be unrelated, sorry

**Comment by dirkf** [comment]
Although I can't get the video without account details, I can't reproduce the problem with the yt-dl program (as opposed to your wrapper). Both the git master and release versions identify that I would need to be a registered user. Perhaps VK checks the user details before trying to find the referenced resource, and the 404 only arises then.

Please run `youtube-dl --cookies ./cookies.txt -v --ignore-config 'https://vk.com/video/@pitbullmonster?z=video-60099869_456246720%2Fclub60099869%2Fpl_-60099869_-2'`

**Comment by docryte** [comment]
Command returns the same. Also you can open this video by link in incognito mode and It will still work. I think, If there was a login problem, It would return an "This video is only available for registered users" error.
```
docryte@docryte:~/PycharmProjects/utilabot$ youtube-dl --cookies './cookies.txt' -v --ignore-config 'https://vk.com/video/@pitbullmonster?z=video-60099869_456246720%2Fclub60099869%2Fpl_-60099869_-2'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', './cookies.txt', '-v', '--ignore-config', 'https://vk.com/video/@pitbullmonster?z=video-60099869_456246720%2Fclub60099869%2Fpl_-60099869_-2']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.9 (CPython) - Linux-5.19.0-29-generic-x86_64-with-glibc2.36
[debug] exe versions: none
[debug] Proxy map: {}
[vk] -60099869_456246720: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by dirkf** [comment]
Indeed, "This video is only available for registered users" is what I get. What happens if you leave out the `--cookies ...`?

**Comment by october262** [comment]
this works  youtube-dl -o '%(title).20s' --no-part --restrict-filenames --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" --add-header "Cookie:tstc=p; Expires=Tue, 01 Feb 2033 08:39:34 GMT; Path=/; HttpOnly;" --referer "https://vk.com" "https://vkvd183.mycdn.me/?expires=1675759170076&srcIp=76.8.147.101&pr=40&srcAg=CHROME&ms=185.226.52.188&type=1&sig=0yVLdX9Gj88&ct=6&urls=45.136.21.139&clientType=13&appId=512000384397&id=1058544814656"

**Comment by dirkf** [comment]
Yes, but in order to get to that point yt-dl has to fetch the JSON that lists that URL. What about https://github.com/ytdl-org/youtube-dl/issues/31512#issuecomment-1416514038?

I wonder what the `tstc` cookie means.

**Comment by BudAlNik** [comment]
It seems I fixed this issue by replacing one of the arguments for `al_video.php` request. I replaced `'act': 'show_inline'` with `'act': 'show'` at 317 line of vk.py. After that, I was able to download the needed video, and I checked that it was working on a couple more. But it still doesn't work without cookies, and I couldn't understand why.

But I don't exactly understand what am I doing, so I wouldn't rather create a pull request.

**Comment by dirkf** [comment]
OK, that rings a bell: try the patch at https://github.com/ytdl-org/youtube-dl/issues/31035#issuecomment-1161719063 !

**Comment by docryte** [comment]
Well, fixes in both last two comments work, but now mostly the same code returns a different error. I think reason for this error isn't related to vk.py but I also didn't found someone with the same error. I can close the issue if you think i need open new issue to fix this.

Code:
```
import youtube_dl


def get_video():
    video = 'https://vk.com/video/@pitbullmonster?z=video-60099869_456246720%2Fclub60099869%2Fpl_-60099869_-2'
    youtube_dl.YoutubeDL({'cookiefile': './cookies.txt', 'verbose': True}).download([video])


get_video()
```

Log with verbose:
```
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-6.0.12-76060006-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0.2, ffprobe 5.0.2
[debug] Proxy map: {}
[vk] -60099869_456246720: Downloading JSON metadata
[vk] -60099869_456246720: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://vkvd183.mycdn.me/expires/1676501646457/srcIp/213.242.38.236/pr/40/srcAg/CHROME/ms/185.226.52.188/type/5/sig/AZMdHYOi0MU/ct/8/urls/45.136.21.139/clientType/13/id/1058544814656/video/'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1
[download] Destination: Уронил банку кваса--60099869_456246720.mp4
[download] 100% of 5.27MiB in 00:01
[debug] ffmpeg command line: ffprobe -show_streams 'file:Уронил банку кваса--60099869_456246720.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "Уронил банку кваса--60099869_456246720.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Уронил банку кваса--60099869_456246720.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:Уронил банку кваса--60099869_456246720.temp.mp4'
[debug] ffmpeg version 5.0.2 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.2.0 (GCC)
  configuration: --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --disable-debug --disable-doc --disable-static --enable-optimizations --enable-shared --disable-everything --enable-ffplay --enable-ffprobe --enable-gnutls --enable-libaom --enable-libdav1d --enable-libfdk-aac --enable-libmp3lame --enable-libfontconfig --enable-libfreetype --enable-libopus --enable-libpulse --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-openal --enable-opengl --enable-sdl2 --enable-vulkan --enable-zlib --enable-libv4l2 --enable-libxcb --enable-vdpau --enable-vaapi --enable-encoder='ac3,alac,flac,libfdk_aac,g723_1,mp2,libmp3lame,libopus,libspeex,pcm_alaw,pcm_mulaw,pcm_f32le,pcm_s16be,pcm_s24be,pcm_s16le,pcm_s24le,pcm_s32le,pcm_u8,tta,libvorbis,wavpack,' --enable-encoder='ass,ffv1,libaom_av1,libvpx_vp8,libvpx_vp9,mjpeg_vaapi,rawvideo,theora,vp8_vaapi,libopenh264' --enable-decoder='adpcm_g722,alac,flac,g723_1,g729,libfdk_aac,libopus,libspeex,mp2,mp3,m4a,pcm_alaw,pcm_mulaw,pcm_f16le,pcm_f24le,pcm_f32be,pcm_f32le,pcm_f64be,pcm_f64le,pcm_s16be,pcm_s16be_planar,pcm_s24be,pcm_s16le,pcm_s16le_planar,pcm_s24le,pcm_s24le_planar,pcm_s32le,pcm_s32le_planar,pcm_s64be,pcm_s64le,pcm_s8,pcm_s8_planar,pcm_u8,pcm_u24be,pcm_u24le,pcm_u32be,pcm_u32le,tta,vorbis,wavpack,' --enable-decoder='ass,ffv1,mjpeg,mjpegb,libaom_av1,libdav1d,libvpx_vp8,libvpx_vp9,rawvideo,theora,vp8,vp9,libopenh264' --enable-encoder='bmp,gif,jpegls,png,tiff,webp,' --enable-decoder='bmp,gif,jpegls,png,tiff,webp,' --enable-hwaccel='vp8_vaapi,mjpeg_vaapi,' --enable-parser='aac,ac3,flac,mjpeg,mpegaudio,mpeg4video,opus,vp3,vp8,vp9,vorbis,' --enable-muxer='ac3,ass,flac,g722,gif,matroska,mp3,mpegvideo,rtp,ogg,opus,pcm_s16be,pcm_s16le,wav,webm,' --enable-demuxer='aac,ac3,ass,flac,g722,gif,image_jpeg_pipe,image_png_pipe,image_webp_pipe,matroska,mjpeg,mov,mp3,mpegvideo,ogg,pcm_mulaw,pcm_alaw,pcm_s16be,pcm_s16le,rtp,wav,' --enable-filter='crop,scale,overlay,amix,amerge,aresample,format,aformat,fps,transpose,pad,' --enable-indev='v4l2,xcbgrab,' --enable-protocol='crypto,file,pipe,rtp,srtp,rtsp,tcp,udp,unix,' --arch=x86_64 --enable-libopenh264
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
Input #0, mpegts, from 'file:Уронил банку кваса--60099869_456246720.mp4':
  Duration: 00:00:08.33, start: 0.000000, bitrate: 5306 kb/s
  Program 1 
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
  Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1080x1080, 30 fps, 30 tbr, 90k tbn
  Stream #0:1[0x101](und): Audio: aac ([15][0][0][0] / 0x000F), 44100 Hz, stereo, s16, 212 kb/s
[NULL @ 0x55ca692cbf00] Requested output format 'mp4' is not a suitable output format
ERROR: file:Уронил банку кваса--60099869_456246720.temp.mp4: Invalid argument
Traceback (most recent call last):
  File "/home/docryte/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2115, in post_process
    files_to_delete, info = pp.run(info)
  File "/home/docryte/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 593, in run
    self.run_ffmpeg(filename, temp_filename, options)
  File "/home/docryte/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 242, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/home/docryte/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 238, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:Уронил банку кваса--60099869_456246720.temp.mp4: Invalid argument

Traceback (most recent call last):
  File "/home/docryte/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2115, in post_process
    files_to_delete, info = pp.run(info)
  File "/home/docryte/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 593, in run
    self.run_ffmpeg(filename, temp_filename, options)
  File "/home/docryte/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 242, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/home/docryte/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 238, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:Уронил банку кваса--60099869_456246720.temp.mp4: Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docryte/PycharmProjects/pythonProject/hueta.py", line 9, in <module>
    get_video()
  File "/home/docryte/PycharmProjects/pythonProject/hueta.py", line 6, in get_video
    youtube_dl.YoutubeDL({'cookiefile': './cookies.txt', 'verbose': True}).download([video])
  File "/home/docryte/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "/home/docryte/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/home/docryte/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/docryte/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 847, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/docryte/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 881, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/docryte/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 1692, in process_video_result
    self.process_info(new_info)
  File "/home/docryte/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2050, in process_info
    self.post_process(filename, info_dict)
  File "/home/docryte/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2117, in post_process
    self.report_error(e.msg)
  File "/home/docryte/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "/home/docryte/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: file:Уронил банку кваса--60099869_456246720.temp.mp4: Invalid argument

Process finished with exit code 1
```

**Comment by dirkf** [comment]
Will be fixed by back-port of newly updated yt-dlp extractor:
```
$ python -m youtube_dl -v -F 'https://vk.com/video/@pitbullmonster?z=video-60099869_456246720%2Fclub60099869%2Fpl_-60099869_-2'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://vk.com/video/@pitbullmonster?z=video-60099869_456246720%2Fclub60099869%2Fpl_-60099869_-2']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: dd9aa74be
[debug] Python version 2.7.18 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[vk] -60099869_456246720: Downloading JSON metadata
[vk] -60099869_456246720: Downloading m3u8 information
[info] Available formats for -60099869_456246720:
format code  extension      resolution note
url240       unknown_video  240p       
url360       unknown_video  360p       
url480       unknown_video  480p       
url720       unknown_video  720p       
url1080      unknown_video  1080p      
hls-222      mp4            144x144     222k , 30.0fps
hls-450      mp4            240x240     450k , 30.0fps
hls-899      mp4            360x360     899k , 30.0fps
hls-1495     mp4            480x480    1495k , 30.0fps
hls-3090     mp4            720x720    3090k , 30.0fps
hls-5306     mp4            1080x1080  5306k , 30.0fps (best)
$
