### ISSUE TITLE
Support for vrt

### ISSUE THREAD

**Issue by mahmoodn** [ytdl-org/youtube-dl#31526]
Hi,
Is there any support for vrt.be?

```
D:\Downloads>"youtube-dl.exe" --verbose https://www.vrt.be/vrtnu/a-z/het-verhaal-van-vlaanderen/1/het-verhaal-van-vlaanderen-s1a2/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.vrt.be/vrtnu/a-z/het-verhaal-van-vlaanderen/1/het-verhaal-van-vlaanderen-s1a2/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[VrtNU] het-verhaal-van-vlaanderen-s1a2: Downloading webpage
ERROR: Unable to extract media element; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\canvas.py", line 318, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract media element; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by dirkf** [comment]
Apparently vrt.be/vrtnu serves DRM-protected content. Check the discussion and tests at https://github.com/yt-dlp/yt-dlp/issues/2678. If the video won't play without DRM enabled in your browser, yt-dl won't be able to support it.

Also, though perhaps because I'm not in-region for the site, the non-JS page that the extractor sees and tries to analyse has no useful content now.

**Comment by dirkf** [comment]
Also, #30716.
