### ISSUE TITLE
This youtube clip consistently fails to download but works fine on the webpage

### ISSUE THREAD

**Issue by emojjon** [ytdl-org/youtube-dl#31551]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[johjo50ubuntu:~/usr/mnt/r../KarlBirgerBlomdahl]$ youtube-dl -i  --write-auto-sub --sub-format srt --restrict-filenames --socket-timeout 5 --no-check-certificate  -o '%(title)s.%(ext)s' 'https://www.youtube.com/watch?v=09yk-oVkpLk&t=483s'
[youtube] 09yk-oVkpLk: Downloading webpage
[youtube] 09yk-oVkpLk: Downloading player 11e3a4ec
[youtube] 09yk-oVkpLk: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Exit Code 1
[johjo50ubuntu:~/usr/mnt/r../KarlBirgerBlomdahl]$ youtube-dl -i  --write-auto-sub --sub-format srt --restrict-filenames --socket-timeout 5 --no-check-certificate  -o '%(title)s.%(ext)s' 'https://www.youtube.com/watch?v=09yk-oVkpLk&t=483s' --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-i', u'--write-auto-sub', u'--sub-format', u'srt', u'--restrict-filenames', u'--socket-timeout', u'5', u'--no-check-certificate', u'-o', u'%(title)s.%(ext)s', u'https://www.youtube.com/watch?v=09yk-oVkpLk&t=483s', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.17 (CPython) - Linux-5.4.0-139-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.11, ffprobe 3.4.11, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 09yk-oVkpLk: Downloading webpage
[youtube] 09yk-oVkpLk: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Exit Code 1
[johjo50ubuntu:~/usr/mnt/r../KarlBirgerBlomdahl]$                                                                                            ❮17:52❯

```

## Description

This download consistently fails. I can watch the video on youtube.

**Comment by dirkf** [comment]
> [x] I've searched the bugtracker for similar issues including closed ones

[Really?](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+uploader+-label%3Aduplicate) Duplicate of #31530.
