### ISSUE TITLE
Failed to download https://www.youtube.com/watch?v=I-bOfMQ2agA

### ISSUE THREAD

**Issue by gustaveWPM** [ytdl-org/youtube-dl#31552]
`youtube-dl -f 298 'https://www.youtube.com/watch?v=I-bOfMQ2agA'`

```
[youtube] I-bOfMQ2agA: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

`youtube-dl -U`

```
youtube-dl is up-to-date (2021.12.17)
```

---

`youtube-dl -F 'https://www.youtube.com/watch?v=I-bOfMQ2agA'` returns the same error message, but also provide the expected output times to times.

```
[youtube] I-bOfMQ2agA: Downloading webpage
[info] Available formats for I-bOfMQ2agA:
format code  extension  resolution note
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 1.07MiB
251          webm       audio only tiny  136k , webm_dash container, opus @136k (48000Hz), 1.12MiB
160          mp4        256x144    144p  116k , mp4_dash container, avc1.4d400c@ 116k, 30fps, video only, 980.98KiB
243          webm       640x360    360p  328k , webm_dash container, vp9@ 328k, 30fps, video only, 2.70MiB
134          mp4        640x360    360p  585k , mp4_dash container, avc1.4d401e@ 585k, 30fps, video only, 4.81MiB
136          mp4        1280x720   720p 2044k , mp4_dash container, avc1.64001f@2044k, 30fps, video only, 16.80MiB
298          mp4        1280x720   720p60 3169k , mp4_dash container, avc1.640020@3169k, 60fps, video only, 26.05MiB
18           mp4        640x360    360p  713k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz)
22           mp4        1280x720   720p 2172k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
```

Btw: same issues with `youtube-dl -f 298 'https://youtu.be/I-bOfMQ2agA'` and `youtube-dl -F 'https://youtu.be/I-bOfMQ2agA'`.

---

## Verbose outputs

`youtube-dl -f 298 'https://www.youtube.com/watch?v=I-bOfMQ2agA' --verbose`

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'298', u'https://www.youtube.com/watch?v=I-bOfMQ2agA', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.15.0-60-generic-x86_64-with-Zorin-16-focal
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {}
[youtube] I-bOfMQ2agA: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**(Always fail.)**

---

`youtube-dl -F 'https://www.youtube.com/watch?v=I-bOfMQ2agA' --verbose`

### Failure

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'https://www.youtube.com/watch?v=I-bOfMQ2agA', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.15.0-60-generic-x86_64-with-Zorin-16-focal
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {}
[youtube] I-bOfMQ2agA: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### Success

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'https://www.youtube.com/watch?v=I-bOfMQ2agA', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.15.0-60-generic-x86_64-with-Zorin-16-focal
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {}
[youtube] I-bOfMQ2agA: Downloading webpage
[info] Available formats for I-bOfMQ2agA:
format code  extension  resolution note
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 1.07MiB
251          webm       audio only tiny  136k , webm_dash container, opus @136k (48000Hz), 1.12MiB
160          mp4        256x144    144p  116k , mp4_dash container, avc1.4d400c@ 116k, 30fps, video only, 980.98KiB
243          webm       640x360    360p  328k , webm_dash container, vp9@ 328k, 30fps, video only, 2.70MiB
134          mp4        640x360    360p  585k , mp4_dash container, avc1.4d401e@ 585k, 30fps, video only, 4.81MiB
136          mp4        1280x720   720p 2044k , mp4_dash container, avc1.64001f@2044k, 30fps, video only, 16.80MiB
298          mp4        1280x720   720p60 3169k , mp4_dash container, avc1.640020@3169k, 60fps, video only, 26.05MiB
18           mp4        640x360    360p  713k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz)
22           mp4        1280x720   720p 2172k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
```

**Comment by Meteor0id** [comment]
noticed failed to download on
https://www.youtube.com/watch?v=fVkWwJl1h9M

**Comment by rklemme** [comment]
Also noticed similar errors for other URLs. Actually, I have some URLs for which download did work a few days ago, but fails now with the same error. So I assume there is a change on YT side which breaks the uploader_id extraction.

**Comment by Lukiahas1138** [comment]
I'm seeing the same thing:
```bash
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=SnEAlrKhKSI', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Windows-10-10.0.19043-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] SnEAlrKhKSI: Downloading webpage
[youtube] SnEAlrKhKSI: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Nathaniel\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Nathaniel\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Nathaniel\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Nathaniel\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "C:\Users\Nathaniel\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment]
> [x] I've searched the bugtracker for similar issues including closed ones

[Really?](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+uploader+-label%3Aduplicate) Duplicate of #31530.
