### ISSUE TITLE
ERROR: Unable to extract uploader id;

### ISSUE THREAD

**Issue by KaustavDBA** [ytdl-org/youtube-dl#31569]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
D:\Youtube video>youtube-dl https://www.youtube.com/watch?v=a3kP8JiQsvo --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=a3kP8JiQsvo', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22621
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] a3kP8JiQsvo: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Trying to download MP4 format of a youtube video using youtube-dl version 2021.12.17, but end up with the error 
ERROR: Unable to extract uploader id

**Comment by nicolaasjan** [comment]
>  I've searched the bugtracker for similar bug reports including closed ones

Hmm... Really? ;)
https://github.com/ytdl-org/youtube-dl/issues?q=Unable+to+extract+uploader+id

For reference; see [this megathread](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1434959710)

**Comment by comicsansgreenki** [comment]
yarp! issue #31570

**Comment by JohnTRL** [comment]
Y'all, go /youtube_dl/extractor/common.py.

Line 983 change `fatal=True` to `fatal=False`
