### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by fradooo** [ytdl-org/youtube-dl#31632]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by fradooo** [comment]
Unable to extract uploader id

**Comment by stuartlangridge** [comment]
A verbose log showing the same problem:

~/bin/youtube-dl --verbose https://www.youtube.com/watch?v=BaW_jenozKc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=BaW_jenozKc']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.15.0-60-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[youtube] BaW_jenozKc: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/user/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/user/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/user/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/home/user/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by tmrdev** [comment]
Getting the same issue on macOS BigSir 11.6 with homebrew install of youtube-dl. 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=8k0LgdtnOvc']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.2 (CPython) - macOS-11.6-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 8k0LgdtnOvc: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id;

**Comment by Vangelis66** [comment]
@fradooo : 

You haven't followed the **recommended procedure** on **submitting a new issue**, now a PINNED issue in the main repo: 

![NI](https://user-images.githubusercontent.com/9669492/220207414-6870b63d-e78a-4873-ade4-d55442c69aa9.png)

i.e. #30839 ; to add insult to injury, you lied by ticking

>  - [x] I've searched the bugtracker for similar bug reports including closed ones

Had you done that (or heed the steps outlined in #30839 ), you'd have discovered ca. **100 duplicate issues** with the same error message, plus links to the originating issue (now a megathread), with content and info on how to remedy your predicament... 

To ALL the rest: The same applies 😞 ...

**Comment by bolshoytoster** [comment]
Since there isn't much information here, I also had this issue.

I get this issue using [pipe-viewer](https://github.com/trizen/pipe-viewer), downloading from youtube, the full output is here:
```py
[debug] Command-line config: ['-vvv', 'https://www.youtube.com/watch?v=-j8th_nXyIE']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4]
[debug] Python 3.10.6 (CPython 64bit) - Linux-5.15.0-60-generic-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.14, mutagen-1.45.1, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=-j8th_nXyIE
[youtube] -j8th_nXyIE: Downloading webpage
[youtube] -j8th_nXyIE: Downloading android player API JSON
[debug] Loading youtube-nsig.11e3a4ec from cache
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = G5S9F6ZcgJY5PGCQ ; player = https://www.youtube.com/s/player/11e3a4ec/player_ias.vflset/en_US/base.js
[debug] [youtube] -j8th_nXyIE: Traceback (most recent call last):
  File "/home/a/.local/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 2580, in _decrypt_nsig
    self._player_cache[sig_id] = func(s)
  File "/home/a/.local/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 2612, in <lambda>
    return lambda s: jsi.extract_function_from_code(*func_code)([s])
  File "/home/a/.local/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 505, in resf
    ret, should_abort = self.interpret_statement(stmt, var_stack)
  File "/home/a/.local/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 120, in interpret_statement
    return self.interpret_expression(expr, local_vars, allow_recursion), should_abort
  File "/home/a/.local/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 156, in interpret_expression
    ret, should_abort = self.interpret_statement(try_expr, local_vars, allow_recursion - 1)
  File "/home/a/.local/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 120, in interpret_statement
    return self.interpret_expression(expr, local_vars, allow_recursion), should_abort
  File "/home/a/.local/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 156, in interpret_expression
    ret, should_abort = self.interpret_statement(try_expr, local_vars, allow_recursion - 1)
  File "/home/a/.local/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 120, in interpret_statement
    return self.interpret_expression(expr, local_vars, allow_recursion), should_abort
  File "/home/a/.local/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 227, in interpret_expression
    self.interpret_expression(sub_expr, local_vars, allow_recursion)
  File "/home/a/.local/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 303, in interpret_expression
    left_val, should_abort = self.interpret_statement(
  File "/home/a/.local/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 120, in interpret_statement
    return self.interpret_expression(expr, local_vars, allow_recursion), should_abort
  File "/home/a/.local/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 303, in interpret_expression
    left_val, should_abort = self.interpret_statement(
  File "/home/a/.local/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 120, in interpret_statement
    return self.interpret_expression(expr, local_vars, allow_recursion), should_abort
  File "/home/a/.local/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 433, in interpret_expression
    raise ExtractorError(f'Unsupported JS expression {expr!r}')
yt_dlp.utils.ExtractorError: Unsupported JS expression '0<=c[49]'; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
 (caused by ExtractorError("Unsupported JS expression '0<=c[49]'; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
ERROR: [youtube] -j8th_nXyIE: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/a/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 640, in extract
    ie_result = self._real_extract(url)
  File "/home/a/.local/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 3563, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/home/a/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1192, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```
The error can be reproduced by running something like this:
```py
yt-dlp -vvv https://www.youtube.com/watch?v=-j8th_nXyIE
```
I get this with every video.
