### ISSUE TITLE
ERROR: Unable to extract uploader id;

### ISSUE THREAD

**Issue by Deadlooks** [ytdl-org/youtube-dl#31639]
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.1 (CPython) - Linux-5.15.44-Re4son-v8l+-aarch64-with-glibc2.36
[debug] Python version 3.11.1 (CPython) - Linux-5.15.44-Re4son-v8l+-aarch64-with-glibc2.36
[debug] Python version 3.11.1 (CPython) - Linux-5.15.44-Re4son-v8l+-aarch64-with-glibc2.36
[debug] exe versions: ffmpeg 5.1.2-2, ffprobe 5.1.2-2
[debug] Proxy map: {}
[debug] exe versions: ffmpeg 5.1.2-2, ffprobe 5.1.2-2
[debug] Proxy map: {}
[debug] exe versions: ffmpeg 5.1.2-2, ffprobe 5.1.2-2
[debug] Proxy map: {}
[youtube] RquXIsIfv4M: Downloading webpage
[youtube] CqTAa9uXjGg: Downloading webpage
[youtube] IMdSG6PJXkc: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/deadlooks/Python/Practice/Scripts/YouTube/venv/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deadlooks/Python/Practice/Scripts/YouTube/venv/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/deadlooks/Python/Practice/Scripts/YouTube/venv/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deadlooks/Python/Practice/Scripts/YouTube/venv/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deadlooks/Python/Practice/Scripts/YouTube/venv/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Traceback (most recent call last):
  File "/home/deadlooks/Python/Practice/Scripts/YouTube/venv/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deadlooks/Python/Practice/Scripts/YouTube/venv/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/deadlooks/Python/Practice/Scripts/YouTube/venv/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deadlooks/Python/Practice/Scripts/YouTube/venv/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deadlooks/Python/Practice/Scripts/YouTube/venv/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[youtube] RquXIsIfv4M: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/deadlooks/Python/Practice/Scripts/YouTube/venv/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deadlooks/Python/Practice/Scripts/YouTube/venv/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/deadlooks/Python/Practice/Scripts/YouTube/venv/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deadlooks/Python/Practice/Scripts/YouTube/venv/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deadlooks/Python/Practice/Scripts/YouTube/venv/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by hexbenjamin** [comment]
i am unfortunately experiencing the same error, thrown by the same line in _search_regex, so it's not just you

**Comment by redsactive** [comment]
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. got this error

**Comment by XordK** [comment]
+1

**Comment by hexbenjamin** [comment]
whup hey, gonna tag all of you:
@Deadlooks @redsactive @XordK 


the issue has been fixed, but isnt out via pip yet. it's related to youtube introducing @handles in channel URLs.

see: [this comment](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435975611)

sorry dev team <3

**Comment by radl97** [comment]
Workaround until Pip update comes:

Find `extractor/youtube.py` and comment out the regex around line 1797 with a `#` character as shown below:

```
            #'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
```

Note that this -- naturally -- breaks the software, but it fixed it for me.

**Comment by Deadlooks** [comment]
the issue is fixed by downloading "pip install yt_dlp"

replace every where there is  youtube_dl in your code to yt_dlp

**Comment by dirkf** [comment]
Please follow #30839 in future.
