### ISSUE TITLE
What does "Unable to extract uploader id" mean, and how do I update YouTube-dl?

### ISSUE THREAD

**Issue by FlaminHat** [ytdl-org/youtube-dl#31645]
Verbose output is as follows:
--------------------
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=booR7hzZg2Y', '-o', 'We apologise for the difficulties....']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.6.8 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] booR7hzZg2Y: Downloading webpage
[youtube] booR7hzZg2Y: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
--------------------

When I try to update YouTube-dl with youtube-dl -U, it gives me this:
--------------------
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.
--------------------
How do I solve this?

**Comment by anjalafghan** [comment]
I have the same issue

**Comment by hexisXz** [comment]
same

**Comment by wastu01** [comment]
same

**Comment by learn-decentralized-systems** [comment]
same
```
$ ./youtube-dl --verbose "https://www.youtube.com/watch?v=bOi6OAwCNH4"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=bOi6OAwCNH4']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.14.0-1056-oem-x86_64-with-glibc2.29
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] bOi6OAwCNH4: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by j-sea** [comment]
Same issue on the Windows executable version:

```
$ ./youtube-dl.exe --verbose https://www.youtube.com/watch?v=REDACTED
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=REDACTED']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] REDACTED: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by WeaselGuns** [comment]
I have the same issue.

**Comment by fairfaxhshw** [comment]
I have the same issue.

**Comment by j-sea** [comment]
Cloning the repo and then running `python -m youtube_dl` from the cloned folder results in

```
$ python -m youtube_dl https://www.youtube.com/watch?v=REDACTED
[youtube] REDACTED: Downloading webpage
[youtube] REDACTED: Downloading player 11e3a4ec
WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

But then it downloads it afterward. Not sure why, but if anyone's in a pinch right now, they can try that.

**Comment by jeffsilverm** [comment]
Same issue

```
jeffs@jeffs-desktop:~/d/Music$ youtube-dl --verbose "https://www.youtube.com/watch?v=J9G1FhQUnSo&list=RDJ9G1FhQUnSo&start_radio=1"
[debug] System config: []
[debug] User config: ['-x', '--audio-format', 'mp3', '--no-mtime', '-o', '~/Music/%(title)s.%(ext)s', '--restrict-filenames', '--prefer-free-formats', '-x', '--audio-format', 'mp3']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=J9G1FhQUnSo&list=RDJ9G1FhQUnSo&start_radio=1']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.15.0-58-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[youtube:tab] Downloading playlist RDJ9G1FhQUnSo - add --no-playlist to just download video J9G1FhQUnSo
[youtube:tab] RDJ9G1FhQUnSo: Downloading webpage
[download] Downloading playlist: Mix - Sesame Street: Happy Furry Monsters Song with R.E.M
[youtube:tab] playlist Mix - Sesame Street: Happy Furry Monsters Song with R.E.M: Downloading 25 videos
[download] Downloading video 1 of 25
[youtube] J9G1FhQUnSo: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

jeffs@jeffs-desktop:~/d/Music$ 
```

**Comment by SNSTRUTHERS** [comment]
Same issue on Pop_OS
```
$ youtube-dl --audio-format mp3 https://www.youtube.com/watch?v=VA_hvqT9nJk
[youtube] VA_hvqT9nJk: Downloading webpage
[youtube] VA_hvqT9nJk: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(base) snstruthers@pop-os:~/Downloads$ youtube-dl --verbose --audio-format mp3 https://www.youtube.com/watch?v=VA_hvqT9nJk
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=VA_hvqT9nJk']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-6.0.12-76060006-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] VA_hvqT9nJk: Downloading webpage
[youtube] VA_hvqT9nJk: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by j-sea** [comment]
This pull request attempts to resolve this issue: https://github.com/ytdl-org/youtube-dl/pull/31568

However, I disagree with their new regular expression. This is the change I would make instead on `line 2126` of `extractor/youtube.py`:

```
                r'/(?:channel/|user/|@)([^/?&#]+)', owner_profile_url,
```

**Comment by comicsansgreenki** [comment]
To anyone and everyone with the same problem `ERROR: Unable to extract uploader id;`: 
**Please take a look at #31530 and #30839.** An issue is already up for this extractor error.
If you need an immediate solution, you can switch to [yt-dlp](https://github.com/yt-dlp/yt-dlp), a fork of this project, as a drop-in replacement while you wait for a backport/patch to the YT extractor.

Thanks u o>o <3
comicsansg (not a collaborator)

**Comment by comicsansgreenki** [comment]
@FlaminHat Also to answer your second question about updating youtube-dl, a new version isn't out (hopefully there will be - #31644). If you need it fixed ASAP, try cloning the repository like @j-sea did in [this comment](https://github.com/ytdl-org/youtube-dl/issues/31645#issuecomment-1439430735).

@j-sea AFAIK it's a warning message that got marked as fatal, when the extractor could've continued anyway without much problems.

**Comment by ananay** [comment]
@comicsansgreenki Cloning it works, just suggested it here as well: https://github.com/ytdl-org/youtube-dl/issues/31645#issuecomment-1439491615

**Comment by wastu01** [comment]
建議用 yt-dlp

**Comment by comicsansgreenki** [comment]
@wastu01 yes, agreed. Moving to yt-dlp is one of two working solutions until youtube-dl gets a new version.

Google Translate-ified:
@wastu01 对，同意。 在 youtube-dl 獲得新版本之前，遷移到 yt-dlp 是兩個可行的解決方案之一。
