### ISSUE TITLE
raise RegexNotFoundError('Unable to extract %s' % _name)

### ISSUE THREAD

**Issue by burntstore-studio** [ytdl-org/youtube-dl#31677]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', '--audio-format', 'mp3', '--verbose', 'https://www.youtube.com/watch?v=-gsDBuHwqbM']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.6 (CPython) - macOS-13.2.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2
[debug] Proxy map: {}
[youtube] -gsDBuHwqbM: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.9/lib/python/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/jim/Library/Python/3.9/lib/python/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/jim/Library/Python/3.9/lib/python/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/Users/jim/Library/Python/3.9/lib/python/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/Users/jim/Library/Python/3.9/lib/python/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


## Description

<!--
Provide an explanation of your issue in an arbitrary form. Please make sure the description is worded well enough to be understood, see https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

WRITE DESCRIPTION HERE

Good morning, I did find a bug report with the "Unable to extract uploader id", but that isn't the bare cause of the problem, which instead seems to be with the regex trying to extract the name.

Thank you for your diligent work and great product.

**Comment by burntstore-studio** [comment]
Good morning, dirkf, thank you so much if the fix has been implemented!  I worry, though, that it's marked as completed because I did something wrong.  If the latter, could you please let me know?  Thank you so much; this is my first ever bug report on anything and I was a bit nervous about the posting.

**Comment by dirkf** [comment]
It was this:
> [ ] I've searched the bugtracker for similar bug reports including closed ones

Read #30839, please.

**Comment by burntstore-studio** [comment]
Understood --- thank you very much for the quick and helpful reply!
