### ISSUE TITLE
[twitch] Error getting data in GQL response

### ISSUE THREAD

**Issue by DesweR** [ytdl-org/youtube-dl#31683]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2022.11.13 / last commit: 1a4fbe8**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl.exe -v -F https://www.twitch.tv/videos/1744660246

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.twitch.tv/videos/1744660246']
[debug] Encodings: locale cp1251, fs mbcs, out cp1251, pref cp1251
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}

[twitch:vod] 1744660246: Downloading stream metadata GraphQL

ERROR: An extractor error has occurred. (caused by KeyError('data',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "D:\Python27\Scripts\youtube-dl-master\dist\sse\youtube-dl.exe\youtube_dl\extractor\common.py", line 535, in extract
    ie_result = self._real_extract(url)
  File "D:\Python27\Scripts\youtube-dl-master\dist\sse\youtube-dl.exe\youtube_dl\extractor\twitch.py", line 332, in _real_extract
    info = self._download_info(vod_id)
  File "D:\Python27\Scripts\youtube-dl-master\dist\sse\youtube-dl.exe\youtube_dl\extractor\twitch.py", line 263, in _download_info
    'Downloading stream metadata GraphQL')[0]['data']
KeyError: 'data'
Traceback (most recent call last):
  File "D:\Python27\Scripts\youtube-dl-master\dist\sse\youtube-dl.exe\youtube_dl\extractor\common.py", line 535, in extract
    ie_result = self._real_extract(url)
  File "D:\Python27\Scripts\youtube-dl-master\dist\sse\youtube-dl.exe\youtube_dl\extractor\twitch.py", line 332, in _real_extract
    info = self._download_info(vod_id)
  File "D:\Python27\Scripts\youtube-dl-master\dist\sse\youtube-dl.exe\youtube_dl\extractor\twitch.py", line 263, in _download_info
    'Downloading stream metadata GraphQL')[0]['data']
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python27\Scripts\youtube-dl-master\dist\sse\youtube-dl.exe\youtube_dl\YoutubeDL.py", line 816, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Python27\Scripts\youtube-dl-master\dist\sse\youtube-dl.exe\youtube_dl\YoutubeDL.py", line 837, in __extract_info
    ie_result = ie.extract(url)
  File "D:\Python27\Scripts\youtube-dl-master\dist\sse\youtube-dl.exe\youtube_dl\extractor\common.py", line 548, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('data',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

The error description is [here](https://github.com/yt-dlp/yt-dlp/issues/6308).
The solution is [here](https://github.com/yt-dlp/yt-dlp/pull/6318).

```
    def _download_info(self, item_id):
        data = self._download_gql(
            item_id, [{
                'operationName': 'VideoMetadata',
                'variables': {
                    'channelLogin': '',
                    'videoID': item_id,
                },
            }],
            'Downloading stream metadata GraphQL')
        video = traverse_obj(data, (Ellipsis, 'data', 'video'), get_all=False)
        if video is None:
            raise ExtractorError(
                'Video %s does not exist' % item_id, expected=True)
        return self._extract_info_gql(video, item_id)
```

**Comment by dirkf** [comment]
Or this for patching a yt-dl like the release that doesn't have `traverse_obj()`:
```diff
-        video = traverse_obj(data, (Ellipsis, 'data', 'video'), get_all=False)
+        video = next(filter(None, (try_get(y, lambda x: x['data']['video']) for y in data or [])), None)
```
