### ISSUE TITLE
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug

### ISSUE THREAD

**Issue by Ramana3031** [ytdl-org/youtube-dl#31687]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ
## Verbose log

```
D:\YTBA>youtube-dl.exe --verbose  -f "best" "https://www.youtube.com/watch?v=c7LOfY-RE9w"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f best', 'https://www.youtube.com/watch?v=c7LOfY-RE9w']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] c7LOfY-RE9w: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

<!--
Provide an explanation of your issue in an arbitrary form. Please make sure the description is worded well enough to be understood, see https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

WRITE DESCRIPTION HERE
Recently, with updated youtube-dl, specific youtube URLs like these 2 =

https://www.youtube.com/watch?v=c7LOfY-RE9w
https://www.youtube.com/watch?v=NPXUPNvg98g

have produced the following error = 
"ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug". 

This is unlike previous and other URLs that worked OK with this youtube-dl on Windows 10 64 bit. Other than the above log from the CMD console, I can't think of other details. Sorry if my text does not conform exactly to your instructions, which I have done my best to understand and follow.  Please help?
```

**Comment by dirkf** [comment]
> [x] I've searched the bugtracker for similar bug reports including closed ones
> ...
> ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug ....

Try #30839 again.
