### ISSUE TITLE
ERROR: Unable to extract uploader id; please report this issue ...

### ISSUE THREAD

**Issue by schorschie** [ytdl-org/youtube-dl#31697]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
youtube-dl.exe --verbose --extract-audio --audio-format m4a --rm-cache-dir --add-metadata --format "bestaudio[ext=m4a]" --output "baby-shark.%(ext)s" https://www.youtube.com/watch?v=nwR6cCW4LsM
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--extract-audio', '--audio-format', 'm4a', '--rm-cache-dir', '--add-metadata', '--format', 'bestaudio[ext=m4a]', '--output', 'baby-shark.%(ext)s', 'https://www.youtube.com/watch?v=nwR6cCW4LsM']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.0 (CPython) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 4.2.3
[debug] Proxy map: {}
Removing cache dir C:\Users\grzeg/.cache\youtube-dl ..
[youtube] nwR6cCW4LsM: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\grzeg\.conda\envs\medias\Lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\grzeg\.conda\envs\medias\Lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\grzeg\.conda\envs\medias\Lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\grzeg\.conda\envs\medias\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract   
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\grzeg\.conda\envs\medias\Lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.``
```

## Description

I wanted to download the audio part of a video.

**Comment by imechemi** [comment]
Same here on MacOS Monterey, 

```
➜  youtube-downloads youtube-dl -U https://www.youtube.com/watch\?v\=BaW_jenozKc
youtube-dl is up-to-date (2021.12.17)
[youtube] BaW_jenozKc: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by nicolaasjan** [comment]
>  I've searched the bugtracker for similar bug reports including closed ones

https://github.com/ytdl-org/youtube-dl/issues?q=Unable+to+extract+uploader+id

 Please do that first.

And:

[Read this before opening a new issue](https://github.com/ytdl-org/youtube-dl/issues/30839)

> Known issues, fixed in git master code:
> 
> - [YouTube: Unable to extract uploader id](https://github.com/ytdl-org/youtube-dl/issues/31530)

**Comment by dirkf** [comment]
Nothing more to be said, thanks.
