### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by dl7ata** [ytdl-org/youtube-dl#31696]
```
youtube-dl -vx https://www.youtube.com/watch?v=yXUTVDRpGOk
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vx', u'https://www.youtube.com/watch?v=yXUTVDRpGOk']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.16 (CPython) - Linux-5.10.103-v7l+-armv7l-with-debian-10.13
[debug] exe versions: ffmpeg 4.1.10-0, ffprobe 4.1.10-0
[debug] Proxy map: {}
[youtube] yXUTVDRpGOk: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with 
the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract uploader id; 
```

**Comment by githiakalaban** [comment]
am still experiencing this too in the terminal when i try to download a youtube video

**Comment by nicolaasjan** [comment]
> [ x] I've searched the bugtracker for similar bug reports including closed ones

https://github.com/ytdl-org/youtube-dl/issues?q=Unable+to+extract+uploader+id

 Please do that first.

And:

[Read this before opening a new issue](https://github.com/ytdl-org/youtube-dl/issues/30839)

> Known issues, fixed in git master code:
> 
> - [YouTube: Unable to extract uploader id](https://github.com/ytdl-org/youtube-dl/issues/31530)

**Comment by githiakalaban** [comment]
TBH, I use youtube-dl from pip install. If, by any chance, you can access
the people/personnel concerned, please alert them. Maybe someone else like
me with a Linux distro is having the same issue as me. Also, contact those
from the apt install youtube-dl, because the issue persists. I had tried
both before posting the issue on GitHub.

**Comment by dirkf** [comment]
Follow the link in the issue to update your pip-based installation, and to read which methods **don't yet** work.

**Comment by githiakalaban** [comment]
Works now.  I used the pip install from GitHub directly.
