### ISSUE TITLE
Can't download video from YouTube

### ISSUE THREAD

**Issue by geoidesic** [ytdl-org/youtube-dl#31709]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[foundry@localhost music]$ youtube-dl --extract-audio --audio-format mp3 https://www.youtube.com/watch?v=2UUIyeEnjbg --output dolphins.mp3 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--extract-audio', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=2UUIyeEnjbg', '--output', 'dolphins.mp3', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.6.8 (CPython) - Linux-4.18.0-372.19.1.el8_6.x86_64-x86_64-with-almalinux-8.7-Stone_Smilodon
[debug] exe versions: ffmpeg 4.2.8, ffprobe 4.2.8
[debug] Proxy map: {}
[youtube] 2UUIyeEnjbg: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Um... I'm not sure what to say. It's not just this YouTube video. Here's another one that didn't work.
 https://www.youtube.com/watch?v=EvuL5jyCHOw

**Comment by geoidesic** [comment]
I think this may be a duplicate of this: #31530
Sorry, didn't realise it before opening the ticket. I did search but didn't know what I was looking for. However, searching allowed me to recognise the duplicate later.
