### ISSUE TITLE
Can't download any more on youtube 😢 

### ISSUE THREAD

**Issue by ArthurOllier** [ytdl-org/youtube-dl#31707]
Beware this youtube link may be a MHA spoil

```
Microsoft Windows [version 10.0.19045.2604]
(c) Microsoft Corporation. Tous droits réservés.

C:\Users\XXX>youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

C:\Users\XXX>youtube-dl -f mp4 --write-auto-sub --verbose https://www.youtube.com/watch?v=GgwUenaQqlM
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'mp4', '--write-auto-sub', '--verbose', 'https://www.youtube.com/watch?v=GgwUenaQqlM']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2020-10-17-git-62073cfa97-full_build-www.gyan.dev, ffprobe 2020-10-17-git-62073cfa97-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] GgwUenaQqlM: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


C:\Users\XXX>
```

**Comment by dirkf** [comment]
#30839
