### ISSUE TITLE
Unable to Extract Uploader id

### ISSUE THREAD

**Issue by Optical24** [ytdl-org/youtube-dl#31726]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: ['-x', '--audio-format', 'mp3', '--audio-quality', '320k', '--audio-quality', '0', '-o', 'C:/Users/brian/Downloads/%(title)s.%(ext)s', '--no-mtime', '-f', 'mp4', '-f', 'best', '-k']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=OyUu2yGxXPk']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 5.1-essentials_build-www.gyan.dev, ffprobe 5.1-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] OyUu2yGxXPk: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

The command I'm using is youtube-dl https://www.youtube.com/watch?v=OyUu2yGxXPk. Youtube-dl is up-to-date. I'm still somewhat new to youtube-dl. This is the first time I encounter this issue.

**Comment by Helpmeplease4321** [comment]
Been having the same issue for the last few days, also new to youtube-dl. Please advise

And I can say yes to all the above checkboxes. 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=pRSC06T4lKs', '--verbose', 'flag']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] pRSC06T4lKs: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by palmarci** [comment]
Yeah, same

**Comment by domoclick** [comment]
same error:
2023-02-28T21:10:07.594Z ERROR: Error while retrieving info on video with URL https://youtu.be/OyUu2yGxXPk with the following message: Error: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl -i -o audio/%(title)s.%(ext)s --write-info-json --print-json --audio-quality 0 -x --audio-format mp3 --write-thumbnail --dump-json https://youtu.be/OyUu2yGxXPk
ERROR: Unable to extract uploader id;

**Comment by dirkf** [comment]
#30839.

**Comment by Vangelis66** [comment]
> And I can say **yes** to **all** the above checkboxes.

... Even to 

>- [ ]  I've searched the bugtracker for similar bug reports including closed ones

? **New** or **old** user, the procedure to follow when about to open a `New issue` is the same... BTW, the last checkbox 

> - [ ]  I've read bugs section in FAQ

should have pointed you to: 

https://github.com/ytdl-org/youtube-dl#bugs

which also contains this important bit: 

>Is the issue already documented?
>
>Make sure that someone has not already opened the issue you're trying to open. Search at the top of the window or browse the [GitHub Issues](https://github.com/ytdl-org/youtube-dl/search?type=Issues) of this repository.
