### ISSUE TITLE
Unable to extract uploader id 

### ISSUE THREAD

**Issue by SukiiPooru** [ytdl-org/youtube-dl#31751]
Youtube-dl stopped downloading this week and was advised to use yd-dlp which worked previous night, but this morning there were no downloads due to this error:

ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

**Comment by dirkf** [comment]
#30839.

**Comment by SukiiPooru** [comment]
Fixed:
in sources add:
##For youtube-dl
 deb http://ftp.<CountryCode>.debian.org/debian sid main


then:
apt install -t=sid yt-dlp

downloads now working.
