### ISSUE TITLE
Cannot Extract Uploader ID

### ISSUE THREAD

**Issue by WinFan3672** [ytdl-org/youtube-dl#31754]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -f mp4 [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://youtu.be/WWURxfAqPCI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.9 (CPython) - Linux-6.2.1-zen1-1-zen-x86_64-with-glibc2.37
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] WWURxfAqPCI: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
return func(self, *args, **kwargs)
File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
ie_result = ie.extract(url)
File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
ie_result = self._real_extract(url)
File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sureto call youtube-dl with the --verbos
```

## Description

Attempting to download a YouTube video causes an error in which the uploader ID could not be found. I have tried:
* Specifying a format
* Using verbose output to work out the issue
* Using the -i flag
* Using the --ignore-certificate-check flag
* using -F
* using -f
* etc.
(Latest YTDL running on Arch installed through the AUR)

**Comment by Dysonsun** [comment]
same problem

**Comment by IshankDev** [comment]
Same issue happing

**Comment by tph5595** [comment]
This is fixed in the most recent version (not pushed out yet) if you clone the repo and run it form there you will be fine.

**Comment by tph5595** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31530

**Comment by dirkf** [comment]
> [x] I've searched the bugtracker for similar issues including closed ones

Read #30839 (again?) to learn how.
