### ISSUE TITLE
"Unable to extract uploader id; error" message after working fine for more then a month of sporadic use

### ISSUE THREAD

**Issue by Jmzgit** [ytdl-org/youtube-dl#31769]
## Checklist

- [x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
(base) <user>:~/Downloads$ youtube-dl -f 134+140 -v https://www.youtube.com/watch?v=LFMhE9nPrfU
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '134+140', '-v', 'https://www.youtube.com/watch?v=LFMhE9nPrfU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.5 (CPython) - Linux-5.4.0-139-generic-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2
[debug] Proxy map: {}
[youtube] LFMhE9nPrfU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File ".................................................../youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File ".................................................../youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File ".................................................../youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File ".................................................../youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File ".................................................../youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Has been working normallly, always use it for youtube urls, a few days ago it sent the error message with what I have always used it for: yt.

**Comment by aario** [comment]
Same here.

**Comment by dirkf** [comment]
> [x] I've searched the bugtracker for similar bug reports including closed ones

Learn how from #30839.
