### ISSUE TITLE
Error Unable to extract uploader id

### ISSUE THREAD

**Issue by kenpc-git** [ytdl-org/youtube-dl#31766]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\user>youtube-dl https://www.youtube.com/watch?v=fjxmkBFwyiA -x --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=fjxmkBFwyiA', '-x', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22621
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] fjxmkBFwyiA: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

**Comment by arssher** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31530

**Comment by ramkyc** [comment]
I too have been experiencing the same issue for the last couple of days.  My output:

![image](https://user-images.githubusercontent.com/9099873/222943936-9cbb1f61-6a0e-4c1e-8dd2-bf0584365f07.png)

I ran the youtube-dl -U command and it showed that I am using the latest program.

**Comment by n3wborn** [comment]
Same here

![image](https://user-images.githubusercontent.com/10246722/222957166-c5108353-21e3-4dcc-8ef9-06a791cb7860.png)

**Comment by arssher** [comment]
C'mon, could you please read my comment just above before posting?

**Comment by dirkf** [comment]
> [x] I've searched the bugtracker for similar bug reports including closed ones

Learn from #30839.
