### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by kozlovyuri** [ytdl-org/youtube-dl#31765]
```$ youtube-dl https://youtu.be/BqeSF-rydvM --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://youtu.be/BqeSF-rydvM', '--verbose']
[debug] Encodings: locale cp1251, fs utf-8, out cp1251, pref cp1251
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.10 (CPython) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] BqeSF-rydvM: Downloading webpage
[youtube] BqeSF-rydvM: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "D:/msys32/mingw32/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "D:/msys32/mingw32/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "D:/msys32/mingw32/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "D:/msys32/mingw32/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "D:/msys32/mingw32/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by oceatoon** [comment]
same here

**Comment by Charles9527** [comment]
same

**Comment by ismaelhf0** [comment]
same here

**Comment by Ay-can** [comment]
same here.

**Comment by damiencolas** [comment]
same here

**Comment by phbcanada** [comment]
I tried adding "fatal=False" to the regex _search_regex call and it seems to be working.

**Comment by BruceMcRooster** [comment]
Same problem with different video on MacOS

**Comment by dirkf** [comment]
#30839.
