### ISSUE TITLE
youtube-dl fails to extract for this YouTube URL - https://youtu.be/NAkAMDeo_NM

### ISSUE THREAD

**Issue by cameron-simpson** [ytdl-org/youtube-dl#31775]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[~]fleet2*> youtube-dl --verbose https://youtu.be/NAkAMDeo_NM
[debug] System config: []
[debug] User config: ['--cache-dir', '~/.cache/youtube-dl', '--add-metadata', '--xattrs', '--no-mtime', '-o', '%(title)s--%(uploader)s@youtube--%(upload_date)s--%(resolution)s--id=%(id)s.%(ext)s', '-f', 'bestvideo[ext=mp4]+bestaudio/best[ext=mp4]/best']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://youtu.be/NAkAMDeo_NM']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 5.1, ffprobe 5.1, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://127.0.0.1:3128', 'https': 'http://127.0.0.1:3128/'}
[youtube] NAkAMDeo_NM: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/cameron/var/venv/3.10.6_1-homebrew/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/cameron/var/venv/3.10.6_1-homebrew/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/cameron/var/venv/3.10.6_1-homebrew/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/Users/cameron/var/venv/3.10.6_1-homebrew/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/Users/cameron/var/venv/3.10.6_1-homebrew/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I get the same exception with the current PyPI version (2021.12.17) and after I installed the git master branch version with:
```
[~]fleet2*> py3 -m pip install git+https://github.com/ytdl-org/youtube-dl.git@master#egg=youtube_dl
Collecting youtube_dl
  Cloning https://github.com/ytdl-org/youtube-dl.git (to revision master) to ./tmp/pip-install-8vqbznun/youtube-dl_d731a9f67c7c418e8b128d3f143a5d35
  Running command git clone --filter=blob:none --quiet https://github.com/ytdl-org/youtube-dl.git /Users/cameron/tmp/pip-install-8vqbznun/youtube-dl_d731a9f67c7c418e8b128d3f143a5d35
  Resolved https://github.com/ytdl-org/youtube-dl.git to commit 3e92c60fcd94c37428d57153dbdd14cd0a1f9226
  Preparing metadata (setup.py) ... done
```
The `py3` above is my default python3 install, presently this:
```
Python 3.10.6 (main, Aug 11 2022, 13:47:18) [Clang 12.0.0 (clang-1200.0.32.29)] on darwin
```

I have seen issue #31530 but nothing I found there helps me (i.e. trying the current `master` branch).

**Comment by cameron-simpson** [comment]
A duplicate of _which_ issue please? - Cameron

**Comment by dirkf** [comment]
The one that you found (thanks) but didn't manage to apply. Read the Description and linked solutions and try again.
