### ISSUE TITLE
YouTubeDL : ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by fju10100** [ytdl-org/youtube-dl#31773]
Bonjour, 
i have this error when i dowload a file.
Is it a bug.

Merci
Frédéric

```
D:\Musique\_YoutubeDownload>set PATH=D:\Musique\_YoutubeDownload\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\OpenVPN\bin;C:\Program Files\Calibre2\;C:\Users\frede\AppData\Local\Microsoft\WindowsApps;

D:\Musique\_YoutubeDownload>youtube-dl.exe --verbose -i -x --audio-format mp3 -o "%(title)s.(ext)s" "https://www.youtube.com/watch?v=7DvJ982ePjQ"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-i', '-x', '--audio-format', 'mp3', '-o', '%(title)s.(ext)s', 'https://www.youtube.com/watch?v=7DvJ982ePjQ']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2019-10-31-7c872df, ffprobe git-2019-10-31-7c872df
[debug] Proxy map: {}
[youtube] 7DvJ982ePjQ: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


D:\Musique\_YoutubeDownload>pause
Appuyez sur une touche pour continuer...
```

**Comment by reinout** [comment]
Duplicate, see https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435975611

**Comment by dirkf** [comment]
And #30839.
