### ISSUE TITLE
Youtube - Unable to extract uploader id;

### ISSUE THREAD

**Issue by Reiner1210** [ytdl-org/youtube-dl#31771]
```
einer@reiner:~$ youtube-dl -v https://www.youtube.com/watch?v=rq0Rv84dqr8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=rq0Rv84dqr8']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.19.0-35-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] rq0Rv84dqr8: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by discosammyusa** [comment]
@Reiner1210 https://github.com/ytdl-org/youtube-dl/issues/31530 read the description here. This issue was addressed there. the -U command won't get the latest version.

**Comment by dirkf** [comment]
Also [re-]read #30839!

**Comment by Reiner1210** [comment]
@dirkf closing the bug does not fix it !

**Comment by Reiner1210** [comment]
No It is still here 
Version is 2021.12.17

**Comment by dirkf** [comment]
Looks like you have the problem that [this guy/gal had](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1454147571).
