### ISSUE TITLE
Fixed or not Fixed?

### ISSUE THREAD

**Issue by baqwas** [ytdl-org/youtube-dl#31811]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl -x --audio-format mp3  --audio-quality 0 --prefer-ffmpeg https://www.youtube.com/watch?v=QYVJfByx95s --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', '--audio-format', 'mp3', '--audio-quality', '0', '--prefer-ffmpeg', 'https://www.youtube.com/watch?v=QYVJfByx95s', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.7 (CPython) - Linux-5.19.0-35-generic-x86_64-with-glibc2.36
[debug] exe versions: ffmpeg 5.1.1, ffprobe 5.1.1
[debug] Proxy map: {}
[youtube] QYVJfByx95s: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Cannot download a single audio file from any arbitrarily chosen link that was working successfully a few months ago. Read about the issue and understood that a fix was going to be made available in due course. Read the announcement about the fix. Was unsuccessfully with the utility app a few minutes ago.

I have very little experience in these matters; my post could be in error but the fact that I am unable to download even a single audio currently implies that the fix does not work with the the parameters that I have used. Please advise.

**Comment by mmed-hajnasr** [comment]
i have the same issue
my version is also 2021.12.17 and this is the verbose log
```
[mmed@fedora ~]$ youtube-dl -x --audio-format mp3  --audio-quality 0 --prefer-ffmpeg https://www.youtube.com/watch?v=QYVJfByx95s --verbose
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', '--audio-format', 'mp3', '--audio-quality', '0', '--prefer-ffmpeg', 'https://www.youtube.com/watch?v=QYVJfByx95s', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.2 (CPython) - Linux-6.1.14-200.fc37.x86_64-x86_64-with-glibc2.36
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2
[debug] Proxy map: {}
[youtube] QYVJfByx95s: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to callyoutube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 814, in wrapper
return func(self, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 835, in __extract_info
ie_result = ie.extract(url)
^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
ie_result = self._real_extract(url)
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by baqwas** [comment]
Thanks a bunch for the quick response!

Regards.

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar bug reports including closed ones

You imply that you found the actual issue that covers this problem, then decided to open another issue. Why? Or read #30839 **again**.

**Comment by baqwas** [comment]
None of the _similar bug reports_ worked for me. I was simply thanking the respondent for the courtesy of a quick response. Sorry, I meant it as a thank you note. My apologies for letting me know that a thank you note is in appropriate.

My issue remains unresolved but I don't want you to spend any more time on it. I have to fry other fish right now.

Regards.

**Comment by dirkf** [comment]
There is only one "similar" bug report that is not a duplicate. That issue, which is **actually mentioned** in the pinned issue that you were supposed to read, explains what was wrong and what to do about it. If you have trouble implementing the advice there, the place to ask is in that (gigantic) issue. Try again if you wish.

**Comment by baqwas** [comment]
Sorry if I've offended you. I'm not a developer by any stretch of the imagination. I had an issue. I followed the steps but didn't quite understand and could not resolve it. Therefore I reported it. The incompetence is surely mine. Somebody was kind enough to respond. I thanked him. And now I'm moving on. 

Regards.
