### ISSUE TITLE
URL refuses download on latest YT-DL:    **https://youtu.be/9lembnHGIfU** 

### ISSUE THREAD

**Issue by mikeh007** [ytdl-org/youtube-dl#31821]
HI YTDL-ORG:  

I have used your marvellous code for years - thank you for it - it's been faultless for years.     

TODAY I've for the first time ever - hit one it can't download:       **https://youtu.be/9lembnHGIfU**

PLAYS fine - it's precious CSNY-at-Woodstock material.   But just refuses to download. 

BELOW is a full verbose output,  after checking I have latest copy.   This is on Antix Linux v19 on a Dell D830:

Would be marvellous if you can advise or fix :) 

Best Wishes
Mike H
London UK
~~~~~~~~~~~~~~~~
 ```
$ youtube-dl -U
youtube-dl is up-to-date (2021.12.17)
mikeh@Dell830-Antix1:/media/DATA/__MEDIA/Youtube_DLs
$ youtube-dl --verbose https://youtu.be/9lembnHGIfU
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://youtu.be/9lembnHGIfU']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.16 (CPython) - Linux-4.9.0-264-antix.1-amd64-smp-x86_64-with-antiX-19.4-buster
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 9lembnHGIfU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 ```

**Comment by dirkf** [comment]
Mike, #30839, please.
