### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by yte424** [ytdl-org/youtube-dl#31843]
no
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- x[ ] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --extract-audio --audio-format mp3 -o "C:\Users\yvette.teiken\Dropbox\Musik für Ada\youtube dl\%(title)s.%(ext)s" https://youtu.be/7FeqF1-Z1g0 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--extract-audio', '--audio-format', 'mp3', '-o', 'C:\\Users\\yvette.teiken\\Dropbox\\Musik für Ada\\youtube dl\\%(title)s.%(ext)s', 'https://youtu.be/7FeqF1-Z1g0', '--verbose']
[debug] Encodings: locale cp65001, fs mbcs, out cp65001, pref cp65001
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22621
[debug] exe versions: ffmpeg N-103272-g7bba0dd638-20210817, ffprobe N-103272-g7bba0dd638-20210817
[debug] Proxy map: {}
[youtube] 7FeqF1-Z1g0: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```


## Description
This kind of comando works fo me but about a month ago it stopped working. It has always the same problem. I tried it with different videos. 

Thanks fpr help

**Comment by nicolaasjan** [comment]
Read #30839 first before opening an issue.

**Comment by nitodico** [comment]
Possible duplicate
https://github.com/ytdl-org/youtube-dl/issues/31530

**Comment by comicsansgreenki** [comment]
Yep, duplicate. Please make sure to check for common issues in the list at the bottom of #30839 or search up your error _before_ posting about it.
The main open issue for this error is at #31530.

If you need an immediate solution, switching to [yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp) is essentially a drop-in replacement and has the related issue fixed.
This program, youtube-dl, also has the issue fixed, but a new release isn't out yet, so in order to update your copy, you'll need to do these steps (mostly applies to Linux-based systems):
```
git clone https://github.com/ytdl-org/youtube-dl
cd youtube-dl
make
sudo make install
```

**Comment by dirkf** [comment]
The template actually shows how to fill these in `[x]` in the way GH understands.

>[x ] I've searched the bugtracker for similar bug reports including closed ones

#30839 explains.

>x[ ] I've read bugs section in FAQ

This too.
