### ISSUE TITLE
Don't download the afreecatv video

### ISSUE THREAD

**Issue by zyz-1998** [ytdl-org/youtube-dl#31858]
`
D:\Software\youtube-dl>youtube-dl.exe -u XXXX-p XXXX@ -R 999 --ffmpeg-location "ffmpeg/bin" --hls-prefer-native "http://vod.afreecatv.com/PLAYER/STATION/98648999" --hls-prefer-native "http://vod.afreecatv.com/PLAYER/STATION/96685886" --hls-prefer-native "http://vod.afreecatv.com/PLAYER/STATION/96643150" --hls-prefer-native "http://vod.afreecatv.com/PLAYER/STATION/96687824" --hls-prefer-native "http://vod.afreecatv.com/PLAYER/STATION/96696144" --hls-prefer-native "http://vod.afreecatv.com/PLAYER/STATION/96696118" --hls-prefer-native "http://vod.afreecatv.com/PLAYER/STATION/96696108" --hls-prefer-native "http://vod.afreecatv.com/PLAYER/STATION/96694382" --hls-prefer-native "http://vod.afreecatv.com/PLAYER/STATION/96688070" --hls-prefer-native "http://vod.afreecatv.com/PLAYER/STATION/96687989" --hls-prefer-native "http://vod.afreecatv.com/PLAYER/STATION/96685988" --hls-prefer-native "http://vod.afreecatv.com/PLAYER/STATION/96685824"
[afreecatv] Logging in
[afreecatv] 98648999: Downloading webpage
ERROR: Unable to extract station; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`
How to download AfreecaTV 19+ vod,

**Comment by dirkf** [comment]
If logging in using `--password ...`/`-p ...` fails, try using `--cookies ...` as described in the Manual.

**Comment by dirkf** [comment]
Also see #30984.

**Comment by zyz-1998** [comment]
> Also see #30984.

Thanks for your reply, I will try to solve it

**Comment by zyz-1998** [comment]
> If logging in using `--password ...`/`-p ...` fails, try using `--cookies ...` as described in the Manual.

`D:\Software\youtube-dl>youtube-dl.exe --cookies cookies.txt -R 999 --verbose --ffmpeg-location "ffmpeg/bin" --hls-prefer-native "https://vod.afreecatv.com/PLAYER/STATION/99893293" --hls-prefer-native "https://vod.afreecatv.com/PLAYER/STATION/99674978" --hls-prefer-native "https://vod.afreecatv.com/PLAYER/STATION/99849894" --hls-prefer-native "https://vod.afreecatv.com/PLAYER/STATION/99516042" --hls-prefer-native "https://vod.afreecatv.com/PLAYER/STATION/99876635"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'cookies.txt', '-R', '999', '--verbose', '--ffmpeg-location', 'ffmpeg/bin', '--hls-prefer-native', 'https://vod.afreecatv.com/PLAYER/STATION/99893293', '--hls-prefer-native', 'https://vod.afreecatv.com/PLAYER/STATION/99674978', '--hls-prefer-native', 'https://vod.afreecatv.com/PLAYER/STATION/99849894', '--hls-prefer-native', 'https://vod.afreecatv.com/PLAYER/STATION/99516042', '--hls-prefer-native', 'https://vod.afreecatv.com/PLAYER/STATION/99876635']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-109535-gfcd557a2c2-20230106, ffprobe N-109535-gfcd557a2c2-20230106
[debug] Proxy map: {'ftp': 'ftp://127.0.0.1:7890', 'https': 'https://127.0.0.1:7890', 'http': 'http://127.0.0.1:7890'}
[afreecatv] 99893293: Downloading webpage
ERROR: Unable to extract station; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\afreecatv.py", line 233, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract station; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

Looking forward to your reply

**Comment by zyz-1998** [comment]
> Ah, sorry, it looks like there is a known issue: [yt-dlp/yt-dlp#6133](https://github.com/yt-dlp/yt-dlp/issues/6133), and a pending downstream PR. I'll pull that when it's ready.
> 
> Meanwhile the linked issue suggests `yt-dlp --force-generic ...` and the same option might help for yt-dl.

`D:\Software\youtube-dl>yt-dlp -vU --cookies cookies.txt  "https://vod.afreecatv.com/PLAYER/STATION/99893293"
[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://vod.afreecatv.com/PLAYER/STATION/99893293']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'https://127.0.0.1:7890', 'ftp': 'ftp://127.0.0.1:7890'}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: Unable to obtain version info; Please try again later or visit  https://github.com/yt-dlp/yt-dlp/releases/latest
[afreecatv] Extracting URL: https://vod.afreecatv.com/PLAYER/STATION/99893293
[afreecatv] 99893293: Downloading webpage
ERROR: [afreecatv] 99893293: Unable to extract station; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\afreecatv.py", line 232, in _real_extract
  File "yt_dlp\extractor\common.py", line 1242, in _search_regex`
Also does not work, looking forward to follow-up fixes
