### ISSUE TITLE
Unable to Extract Uploader ID is killing the download

### ISSUE THREAD

**Issue by ShelbyvonTrapp** [ytdl-org/youtube-dl#31860]
The following is the Verbose output of the error received when trying to send through the request. I have it up to date, and an unsure why it's failing at this point. I placed a test URL in, and this has happened on every download attempt I've made for YouTube.

```
python3 /usr/local/bin/youtube-dl -f 'best' -o '[**REMOVED FILE PATH**]/%(upload_date)s - %(title)s.%(ext)s' 'https://www.youtube.com/watch?v=g4mHPeMGTJM' --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '-o', '[**REMOVED FILE PATH**]%(upload_date)s - %(title)s.%(ext)s', 'https://www.youtube.com/watch?v=g4mHPeMGTJM', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.6 (CPython) - macOS-13.2.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.1-https, ffprobe 5.1-https
[debug] Proxy map: {}
[youtube] g4mHPeMGTJM: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Let me know if you have any questions regarding this issue. Please, and thank you!

**Comment by dirkf** [comment]
#30839 !
