### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by sumonst21** [ytdl-org/youtube-dl#31867]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
sumon@Sumonst21 MINGW64 /c/youtube-dl
$ ./youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

sumon@Sumonst21 MINGW64 /c/youtube-dl
$ ./youtube-dl.exe https://www.youtube.com/watch?v=rkpWkLgOzZs
[youtube] rkpWkLgOzZs: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

sumon@Sumonst21 MINGW64 /c/youtube-dl
$ ./youtube-dl.exe https://www.youtube.com/watch?v=rkpWkLgOzZs --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=rkpWkLgOzZs', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22621
[debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev, ffprobe 5.1.2-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] rkpWkLgOzZs: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Unable to extract uploader id

**Comment by sumonst21** [comment]
> #31865 is dupe

well, #31865 wasn't reported correctly

**Comment by ulidtko** [comment]
> well, #31865 wasn't reported correctly

yes, no care was applied, even to paste the `--verbose` log :/

**Comment by BartVermeir** [comment]
Have the same issue reported today. Same error. Simular verbose log

**Comment by ulidtko** [comment]
Looking into it.

Testing with video `fpT5X6HhK3g`  — the microformat data has `"ownerProfileUrl": "http://www.youtube.com/@Laboratoriumpiesni"`  but the regex extracting the `uploader_id` is `r'/(?:channel|user)/([^/?&#]+)'` i.e. expects `/channel/...` or `/user/...`. Has YouTube introduced shortened username/channel @urls ?

Anyhow, **I got it working** with the following regex tweak. `extractor/youtube.py` line 1794 (in version 2021.12.17):

                 'uploader_id': self._search_regex(r'/(?:channel/|user/|@)([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,

Will proceed to submit a PR patch.

**Comment by ulidtko** [comment]
Ah. Ofcourse. **This is already fixed** in master version:

https://github.com/ytdl-org/youtube-dl/blob/6fece0a96b3cd8677f5c1185a57c6e21403fcb44/youtube_dl/extractor/youtube.py#L455-L458

Don't be like me — using a 2-year old version. Install from git master like so:

    pip uninstall youtube-dl
    pip install --user git+https://github.com/ytdl-org/youtube-dl.git#branch=master

This works without any regex tweaks — and also downloads much much faster.

**Comment by sumonst21** [comment]
> Ah. Ofcourse. **This is already fixed** in master version:
> 
> https://github.com/ytdl-org/youtube-dl/blob/6fece0a96b3cd8677f5c1185a57c6e21403fcb44/youtube_dl/extractor/youtube.py#L455-L458
> 
> Don't be like me — using a 2-year old version. Install from git master like so:
> 
> ```
> pip uninstall youtube-dl
> pip install --user git+https://github.com/ytdl-org/youtube-dl.git#branch=master
> ```
> 
> This works without any regex tweaks — and also downloads much much faster.

Well, can we expect to have the binary fixed instead?

**Comment by ulidtko** [comment]
> Well, can we expect to have the binary fixed instead?

I'm not even a contributor here. The last few [releases][] were made by @dstftw — perhaps bother him or other repo owners somehow.

I also know there's a better-maintained fork called [youtube-dlp][], looks more up-to-date.

[releases]: https://github.com/ytdl-org/youtube-dl/releases
[youtube-dlp]: https://github.com/yt-dlp/yt-dlp

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar bug reports including closed ones

Obvs without properly studying #30839, as asked and expected, where there is a link to the actual issue covering this problem.

**Comment by sumonst21** [comment]
> > [x] I've searched the bugtracker for similar bug reports including closed ones
> 
> Obvs without properly studying #30839, as asked and expected, where there is a link to the actual issue covering this problem and where the questions asked here are answered.

man you really got out of your business, how I came to this? I was asked when I ran the binary which were previously working but that day it showed some error & referred to a link about posting a bug report, if #30839 had a solution/answer then what is the meaning of not providing that url directly from the binary instead of advertising your issue threads for alternatives, spamtalks etc, 

you can spend time on writing 200 chars story, can add "duplicate" label to thousands of opened issues, why can't you provide a new release if not fixed then at least save your time on marking issues as dups. 

@dirkf you doing great contributions, marking issues with different labels, colors. try doing some real contribution for the repo

I'v been reading news about people abusing the OSS community, today I saw it, can't belive people reached this level for ads. 

@ulidtko if you can't bother him then why bothering me? still you are doing much better job than @dirkf 

Shame on me, I'm this lazy, well I didn't had this experiance.

**Comment by ulidtko** [comment]
@sumonst21 so sorry for volunteering to help explain & resolve the issue you had reported :astonished: 

and in case you aren't aware, "ads" implies monetary payment — which I'm damn sure noone here gets a penny of.  so you'd better reconsider what you say to people who try to help you (and other OSS users) deal with technology, for free.

**Comment by sumonst21** [comment]
@dirkf @ulidtko and contributors, I appreciate all the work you put into maintaining this project and managing the issues—it’s a big job, especially in open source. I understand that marking issues as duplicates or referring to existing threads helps consolidate information.

However, I’d like to share some honest feedback. When I encountered this issue, it was frustrating to not find a direct solution link or explanation in the error message itself. If issue #30839 has a resolution, it would be really helpful for users if the binary provided that link directly. Redirecting users to open threads with similar issues can feel like a roundabout approach, especially when the problem hasn’t been directly addressed in the documentation or release notes.

I understand that you’re juggling a lot, and I’m grateful for the time you spend organizing, labeling, and responding to issues here. The dedication is clear, and I don’t mean to overlook that—I just wanted to raise this in case it might improve the experience for future users as well.

Thanks again, and I hope this feedback is helpful in the spirit of constructive improvement. 🙏

**Comment by dirkf** [comment]
Really, #30839 tells you what to do (it has done for some months):
>The 2021.12.17 release linked in the download instructions is now effectively obsolete; in particular, it does not generally work with YouTube itself. Before raising an issue, try a nightly release build.  ...

And "nightly release build" is the link you needed.

Similarly at the [Release page for the obsolete stable binaries](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.12.17).

[If a user had a new release, diagnostic messages might be more helpful but we can't retrospectively change the messages in the 2021 build](https://github.com/ytdl-org/youtube-dl/issues/31585).
