### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by JohelEGP** [ytdl-org/youtube-dl#31885]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['--rate-limit', '6000K', '--retries', 'infinite', '--fragment-retries', 'infinite', '--restrict-filenames', '--output', '%(title)s.%(id)s.%(ext)s', '--no-overwrites', '--format', 'bestvideo[height<=720]+bestaudio', '--add-metadata']
[debug] Command-line args: ['--config-location', '/home/johel/.config/youtube-dl/vconfig', '-v', 'https://www.youtube.com/watch?v=22JQW6wR9CM']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.10 (CPython) - Linux-6.2.7-arch1-1-x86_64-with-glibc2.37
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[youtube] 22JQW6wR9CM: Downloading webpage
[debug] [youtube] Decrypted nsig w17THomInb0cVe => 81p7cuA5XtfzTw
[debug] [youtube] Decrypted nsig t1EFhHDUoFxXB- => aXVWFexbBo_wUg
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://rr5---sn-ugpjvh-ixms.googlevideo.com/videoplayback?expire=1679293407&ei=fqcXZLy4OZjbhgays7mwDQ&ip=148.103.100.151&id=o-AI8ZHnV4YLZ-OAiPwR0hiEID8I9LV4w4hBg3N6HQQyeK&itag=136&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=hR&mm=31%2C29&mn=sn-ugpjvh-ixms%2Csn-hp57yn7r&ms=au%2Crdu&mv=m&mvi=5&pl=23&initcwndbps=306250&vprv=1&mime=video%2Fmp4&ns=CGfkgvD6ZEpAJ7pfIPinzjQL&gir=yes&clen=16720227&dur=173.399&lmt=1652282413363275&mt=1679271443&fvip=5&keepalive=yes&fexp=24007246&c=WEB&txp=5319224&n=81p7cuA5XtfzTw&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgPj_c2-jW1Cvqkn9P_nXzTKwlC--pjPBkrFXS_DH4LUgCIQC4-p1kgrdocp9J6nLCq9T8qlbUZ2ug67vEkC_DzVinvA%3D%3D&sig=AOq0QJ8wRQIgTPRJG0g1LEEB6-2URttIr-59WphjqTy0gRJ2tGCSJioCIQDbRp41JpmcHkwd0JWFmmYKe3mpp4U9OjCRadmobWvTBQ%3D%3D'
[dashsegments] Total fragments: 2
[download] Destination: LUCK_PLUS_-_Thunderbird.22JQW6wR9CM.f136.mp4
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 33, in <module>
    sys.exit(load_entry_point('youtube-dl==2021.12.17', 'console_scripts', 'youtube-dl')())
  File "/usr/lib/python3.10/site-packages/youtube_dl/__init__.py", line 475, in main
    _real_main(argv)
  File "/usr/lib/python3.10/site-packages/youtube_dl/__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2083, in download
    res = self.extract_info(
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 812, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 819, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 851, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 885, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 1696, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 1982, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 1927, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.10/site-packages/youtube_dl/downloader/common.py", line 376, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.10/site-packages/youtube_dl/downloader/dash.py", line 41, in real_download
    for count in range(fragment_retries + 1):
TypeError: 'float' object cannot be interpreted as an integer
```

## Description

Attempting to download https://www.youtube.com/watch?v=22JQW6wR9CM results in the error above. `youtube-dl` was freshly built from 6fece0a96. This was on Arch Linux, so it may be due to an updated dependency.

**Comment by dirkf** [comment]
Try `--fragment-retries 1000` or similar, and the next version will handle "infinite" again. Thanks.

**Comment by JohelEGP** [comment]
Thank you. That works. If the problem's with `--fragment-retries infinite` and it's a known issue, feel free to close. #31142 seems "out-of-scope", though.

**Comment by dirkf** [comment]
This is a new problem because I forgot that these values could be `float('inf')` (and there isn't a test case that exercises that ...).

The old issue was, I guess, because some script was launching yt-dl with a single argument `'--fragment-retries infinite'` instead of `'--fragment-retries', 'infinite'`.

**Comment by dirkf** [comment]
That would have worked and would probably have other uses. I went with `itertools.count()` which works well enough for what is a fairly tenuous loop.
