### ISSUE TITLE
[youtube] RegexNotFoundError: Unable to extract uploader id; 

### ISSUE THREAD

**Issue by verisimilidude2** [ytdl-org/youtube-dl#31891]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
 $ youtube-dl -v https://www.youtube.com/watch?v=EnXxO3BAgYk
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=EnXxO3BAgYk']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.7.3 (CPython) - Linux-5.10.103-v7l+-armv7l-with-debian-10.13
[debug] exe versions: ffmpeg 4.1.10-0, ffprobe 4.1.10-0
[debug] Proxy map: {}
[youtube] EnXxO3BAgYk: Downloading webpage
[youtube] EnXxO3BAgYk: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Trying to download a (specific) file from youtube resulted in a message that the uploader id could not be extracted.  This appears, from the traceback, to be due to a regex not finding information, causing python to raise an exception.

**Comment by rdragomir** [comment]
Same issue here. I'm using DSM 6.2.4-25556 Update 6 and latest Youtube Downloader.
I tried to DL the audio track of 6 different youtube videos and with all of them I had the same issue and they all failed.

**Comment by ruggeropintus** [comment]
Same issue here.

I am using the latest version. The output of ```youtube-dl -U``` is

```
youtube-dl is up-to-date (2021.12.17)
```

And the output of the command ```youtube-dl -F --verbose <youtube_link>``` is

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '--verbose', 'https://www.youtube.com/watch?v=T5k4hQNQOYE']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.10 (CPython) - Linux-6.2.7-arch1-1-x86_64-with-glibc2.37
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] T5k4hQNQOYE: Downloading webpage
[youtube] T5k4hQNQOYE: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by hsb5** [comment]
Та же самая ошибка. Пора обновлять библиотеку.

**Comment by Hxrshrathore** [comment]
I same Issue, already updated the module to the latest version still the issue is there.

`ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output`

**Comment by Thomas-Pnx** [comment]
Issue also replicated there

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar issues including closed ones

Learn how by reading #30839 properly (**again**?).
