### ISSUE TITLE
unable to extract uploader id

### ISSUE THREAD

**Issue by clitomen** [ytdl-org/youtube-dl#31906]
youtube-dl -F --verbose https://www.youtube.com/watch?v=oSOqQ3ZjnI4[debug] System config: 
[debug] User config: 
[debug] Custom config: 
[debug] Command-line args: ['-F', '--verbose', 'https://www.youtube.com/watch?v=oSOqQ3ZjnI4']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.2 (CPython) - Linux-6.1.0-6-amd64-x86_64-with-glibc2.36
[debug] exe versions: ffmpeg 5.1.2-3, ffprobe 5.1.2-3, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube] oSOqQ3ZjnI4: Downloading webpage
[youtube] oSOqQ3ZjnI4: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id;

**Comment by dirkf** [comment]
#30839 !
