### ISSUE TITLE
Can't download formats for youtube video

### ISSUE THREAD

**Issue by hemna** [ytdl-org/youtube-dl#31911]
```
└─> youtube-dl --verbose -F "http://www.youtube.com/watch?v=4gZ6K2gEciA"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-F', 'http://www.youtube.com/watch?v=4gZ6K2gEciA']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 13d85686
[debug] Python version 3.8.8 (CPython) - Linux-5.15.0-57-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[youtube] 4gZ6K2gEciA: Downloading webpage
[youtube] 4gZ6K2gEciA: Downloading m3u8 information
[youtube] 4gZ6K2gEciA: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/waboring/.pyenv/versions/3.8.8/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/waboring/.pyenv/versions/3.8.8/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/waboring/.pyenv/versions/3.8.8/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/waboring/.pyenv/versions/3.8.8/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/home/waboring/.pyenv/versions/3.8.8/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment]
#30839 !
