### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by tungtanium** [ytdl-org/youtube-dl#31954]
Hi I am experiencing the above error when trying to download a Youtube video (other URL also) via the follow command:

```bash
❯ youtube-dl.exe --verbose -x --audio-format mp3 --audio-quality 4 https://www.youtube.com/watch?v=r7qovpFAGrQ

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-x', '--audio-format', 'mp3', '--audio-quality', '4', 'https://www.youtube.com/watch?v=r7qovpFAGrQ']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22621
[debug] exe versions: ffmpeg git-2020-05-19-74dfc88, ffprobe git-2020-05-19-74dfc88
[debug] Proxy map: {}
[youtube] r7qovpFAGrQ: Downloading webpage
 please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

I am running the latest version `2021.12.17`. I am not sure why the Traceback started from `C:\Users\dst`. There is no such username on my computer.

Thank you for looking into this.

**Comment by mfld** [comment]
I believe this has already been reported.
See https://github.com/ytdl-org/youtube-dl/issues/31530 and https://github.com/ytdl-org/youtube-dl/pull/31675
