### ISSUE TITLE
TypeError: cannot pickle 'generator' object

### ISSUE THREAD

**Issue by antoinedelplace** [ytdl-org/youtube-dl#31999]
## Checklist

- [ x] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-8-341ffea1c7bf>](https://localhost:8080/#) in <cell line: 10>()
     11   # try:
     12     with youtube_dl.YoutubeDL(ydl_opts) as ydl:
---> 13         result = ydl.extract_info("{}".format(url))
     14         ydl.download([url])
     15         filename = ydl.prepare_filename(result)

17 frames
[/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py](https://localhost:8080/#) in extract_info(self, url, download, ie_key, extra_info, process, force_generic_extractor)
    810                                     'and will probably not work.')
    811 
--> 812             return self.__extract_info(url, ie, download, extra_info, process)
    813         else:
    814             self.report_error('no suitable InfoExtractor for URL %s' % url)

[/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py](https://localhost:8080/#) in wrapper(self, *args, **kwargs)
    817         def wrapper(self, *args, **kwargs):
    818             try:
--> 819                 return func(self, *args, **kwargs)
    820             except GeoRestrictedError as e:
    821                 msg = e.msg

[/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py](https://localhost:8080/#) in __extract_info(self, url, ie, download, extra_info, process)
    849         self.add_default_extra_info(ie_result, ie, url)
    850         if process:
--> 851             return self.process_ie_result(ie_result, download, extra_info)
    852         else:
    853             return ie_result

[/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py](https://localhost:8080/#) in process_ie_result(self, ie_result, download, extra_info)
    883         if result_type == 'video':
    884             self.add_extra_info(ie_result, extra_info)
--> 885             return self.process_video_result(ie_result, download=download)
    886         elif result_type == 'url':
    887             # We have to add extra_info to the results because it may be

[/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py](https://localhost:8080/#) in process_video_result(self, info_dict, download)
   1683         }
   1684 
-> 1685         formats_to_download = list(format_selector(ctx))
   1686         if not formats_to_download:
   1687             raise ExtractorError('requested format not available',

[/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py](https://localhost:8080/#) in selector_function(ctx)
   1284                 def selector_function(ctx):
   1285                     for f in fs:
-> 1286                         for format in f(ctx):
   1287                             yield format
   1288                 return selector_function

[/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py](https://localhost:8080/#) in final_selector(ctx)
   1400 
   1401             def final_selector(ctx):
-> 1402                 ctx_copy = copy.deepcopy(ctx)
   1403                 for _filter in filters:
   1404                     ctx_copy['formats'] = list(filter(_filter, ctx_copy['formats']))

[/usr/lib/python3.9/copy.py](https://localhost:8080/#) in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

[/usr/lib/python3.9/copy.py](https://localhost:8080/#) in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

[/usr/lib/python3.9/copy.py](https://localhost:8080/#) in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

[/usr/lib/python3.9/copy.py](https://localhost:8080/#) in _deepcopy_list(x, memo, deepcopy)
    203     append = y.append
    204     for a in x:
--> 205         append(deepcopy(a, memo))
    206     return y
    207 d[list] = _deepcopy_list

[/usr/lib/python3.9/copy.py](https://localhost:8080/#) in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

[/usr/lib/python3.9/copy.py](https://localhost:8080/#) in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

[/usr/lib/python3.9/copy.py](https://localhost:8080/#) in deepcopy(x, memo, _nil)
    170                     y = x
    171                 else:
--> 172                     y = _reconstruct(x, memo, *rv)
    173 
    174     # If is its own copy, don't memoize.

[/usr/lib/python3.9/copy.py](https://localhost:8080/#) in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    268     if state is not None:
    269         if deep:
--> 270             state = deepcopy(state, memo)
    271         if hasattr(y, '__setstate__'):
    272             y.__setstate__(state)

[/usr/lib/python3.9/copy.py](https://localhost:8080/#) in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

[/usr/lib/python3.9/copy.py](https://localhost:8080/#) in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

[/usr/lib/python3.9/copy.py](https://localhost:8080/#) in deepcopy(x, memo, _nil)
    159                     reductor = getattr(x, "__reduce_ex__", None)
    160                     if reductor is not None:
--> 161                         rv = reductor(4)
    162                     else:
    163                         reductor = getattr(x, "__reduce__", None)

TypeError: cannot pickle 'generator' object
```

## Description

Try to download with python API.
Worked yesterday. 
Maybe a problem with a new version of the deepcopy ?

Used code :
```
from __future__ import unicode_literals
import youtube_dl

url = "https://www.youtube.com/watch?v=trWrEWfhTVg"

ydl_opts = {"writeinfojson": True,
            "writesubtitles": True}

with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    result = ydl.extract_info("{}".format(url))
    ydl.download([url])
    filename = ydl.prepare_filename(result)
```

Installation was done with :
```
!pip install git+https://github.com/ytdl-org/youtube-dl.git@master#egg=youtube_dl
```

**Comment by dir01** [comment]
Came here to open the very same ticket, figured I'll attach one more repro:

Given this `Dockerfile`:

```
FROM ubuntu:latest

RUN apt update && apt install -y python3 python3-pip git

WORKDIR /app
RUN git clone https://github.com/ytdl-org/youtube-dl.git /app

ENV PYTHONPATH=/app
```

and this command: 
```
docker build . -t ytdl-31999; docker run ytdl-31999 python3 /app/bin/youtube-dl --dump-json 'https://www.youtube.com/watch?v=kPN-uWB28X8'
```

I'm getting this stacktrace
```
Traceback (most recent call last):
  File "/app/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/app/youtube_dl/__init__.py", line 475, in main
    _real_main(argv)
  File "/app/youtube_dl/__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "/app/youtube_dl/YoutubeDL.py", line 2083, in download
    res = self.extract_info(
  File "/app/youtube_dl/YoutubeDL.py", line 812, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/app/youtube_dl/YoutubeDL.py", line 819, in wrapper
    return func(self, *args, **kwargs)
  File "/app/youtube_dl/YoutubeDL.py", line 851, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/app/youtube_dl/YoutubeDL.py", line 885, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/app/youtube_dl/YoutubeDL.py", line 1685, in process_video_result
    formats_to_download = list(format_selector(ctx))
  File "/app/youtube_dl/YoutubeDL.py", line 1286, in selector_function
    for format in f(ctx):
  File "/app/youtube_dl/YoutubeDL.py", line 1402, in final_selector
    ctx_copy = copy.deepcopy(ctx)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 206, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'generator' object

```

**Comment by dir01** [comment]
It works in f35b757c826027ab5263d431bbe363c6403bd66d
It stops working in 88f28f620bcae7ba7302f8b049b74f0f8a12831f

**Comment by dir01** [comment]
it works in 45495228b7a6728b7e764bbcf1f38490cd3d8697
it stops working in f35b757c826027ab5263d431bbe363c6403bd66d

**Comment by ChrisCates** [comment]
Thank you @dirkf, a lot of us are probably not using new features. So the easier more automated way (without needing to fork) is to just run:

```bash
# If already installed and needs to be fixed
python -m pip uninstall youtube-dl

# Install from the last working commit
python3 -m pip install 'git+https://github.com/ytdl-org/youtube-dl.git@45495228b7a6728b7e764bbcf1f38490cd3d8697#egg=youtube_dl'
```

**Comment by dir01** [comment]
Does not seem to be fixed

**Comment by mlmoses** [comment]
I'm still getting the same error. My stack trace is different, but it looks like the same issue in a different part of the code:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mlmoses\Projects\ytdl-org\youtube-dl\youtube_dl\__main__.py", line 19, in <module>
    youtube_dl.main()
  File "C:\Users\mlmoses\Projects\ytdl-org\youtube-dl\youtube_dl\__init__.py", line 475, in main
    _real_main(argv)
  File "C:\Users\mlmoses\Projects\ytdl-org\youtube-dl\youtube_dl\__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mlmoses\Projects\ytdl-org\youtube-dl\youtube_dl\YoutubeDL.py", line 2083, in download
    res = self.extract_info(
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mlmoses\Projects\ytdl-org\youtube-dl\youtube_dl\YoutubeDL.py", line 812, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mlmoses\Projects\ytdl-org\youtube-dl\youtube_dl\YoutubeDL.py", line 819, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mlmoses\Projects\ytdl-org\youtube-dl\youtube_dl\YoutubeDL.py", line 851, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mlmoses\Projects\ytdl-org\youtube-dl\youtube_dl\YoutubeDL.py", line 885, in process_ie_result
    return self.process_video_result(ie_result, download=download)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mlmoses\Projects\ytdl-org\youtube-dl\youtube_dl\YoutubeDL.py", line 1685, in process_video_result
    formats_to_download = list(format_selector(ctx))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mlmoses\Projects\ytdl-org\youtube-dl\youtube_dl\YoutubeDL.py", line 1286, in selector_function
    for format in f(ctx):
                  ^^^^^^
  File "C:\Users\mlmoses\Projects\ytdl-org\youtube-dl\youtube_dl\YoutubeDL.py", line 1405, in final_selector
    return selector_function(ctx_copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mlmoses\Projects\ytdl-org\youtube-dl\youtube_dl\YoutubeDL.py", line 1296, in selector_function
    picked_formats = list(f(ctx))
                     ^^^^^^^^^^^^
  File "C:\Users\mlmoses\Projects\ytdl-org\youtube-dl\youtube_dl\YoutubeDL.py", line 1396, in selector_function
    video_selector(copy.deepcopy(ctx)), audio_selector(copy.deepcopy(ctx))):
                   ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\3.11\Lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\3.11\Lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\3.11\Lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\3.11\Lib\copy.py", line 206, in _deepcopy_list
    append(deepcopy(a, memo))
           ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\3.11\Lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\3.11\Lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\3.11\Lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\3.11\Lib\copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\3.11\Lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\3.11\Lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\3.11\Lib\copy.py", line 161, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle 'generator' object
```

**Comment by dirkf** [comment]
Indeed, I should have spotted that `deepcopy()` is also being used when video+audio is merged. I don't think [this](https://github.com/ytdl-org/youtube-dl/commit/317f7ab634) is needed now: the equivalent yt-dlp code was removed in https://github.com/yt-dlp/yt-dlp/pull/888. I'll update.
