### ISSUE TITLE
Signature extraction TypeError: string indices must be integers

### ISSUE THREAD

**Issue by Obliman** [ytdl-org/youtube-dl#32008]
## Checklist
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```console
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.7 (CPython) - Linux-5.19.0-21-generic-x86_64-with-glibc2.36
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[youtube] rNVmfztMtaw: Downloading webpage
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1367, in _decrypt_signature
    return func(s)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1266, in <lambda>
    return lambda s: ''.join(s[i] for i in cache_spec)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1266, in <genexpr>
    return lambda s: ''.join(s[i] for i in cache_spec)
TypeError: string indices must be integers
 (caused by TypeError('string indices must be integers')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1367, in _decrypt_signature
    return func(s)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1266, in <lambda>
    return lambda s: ''.join(s[i] for i in cache_spec)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1266, in <genexpr>
    return lambda s: ''.join(s[i] for i in cache_spec)
TypeError: string indices must be integers
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1367, in _decrypt_signature
    return func(s)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1266, in <lambda>
    return lambda s: ''.join(s[i] for i in cache_spec)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1266, in <genexpr>
    return lambda s: ''.join(s[i] for i in cache_spec)
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1641, in _real_extract
    signature = self._decrypt_signature(sc['s'][0], video_id, player_url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1370, in _decrypt_signature
    raise ExtractorError(
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1367, in _decrypt_signature
    return func(s)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1266, in <lambda>
    return lambda s: ''.join(s[i] for i in cache_spec)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1266, in <genexpr>
    return lambda s: ''.join(s[i] for i in cache_spec)
TypeError: string indices must be integers
 (caused by TypeError('string indices must be integers')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description
I have two versions of python installed in two different environments. Python 3.9 works, but for some reason my python 3.10 install produces this error. Both have the latest version of youtube-dl installed via pip. The target is a generic youtube video.
I noticed several other issues posted with a similar title, but they did not have the same error log I believe.

**Comment by dirkf** [comment]
Please review #30855 which appears to be a similar report.

**Comment by Obliman** [comment]
> Please review #30855 which appears to be a similar report.

If I'm interpreting that issue correctly then that error was caused by actually using an old version of youtube-dl(?)
I have ensured that youtube-dl is the latest version, which is confirmed in the error message:
`[debug] youtube-dl version 2021.12.17`.

**Comment by dirkf** [comment]
In #30855, there are two different versions. Try `youtube-dl --version`.

**Comment by Obliman** [comment]
> In #30855, there are two different versions. Try `youtube-dl --version`.

This command also returns `2021.12.17`

**Comment by dirkf** [comment]
How are your two Python installations configured?

Also, try using `--no-cache-dir`. If that works, run `youtube-dl --rm-cache-dir` and hope that future cached items have the correct format.

**Comment by Obliman** [comment]
Unforunately, messing with the cache didn't fix it. I decided to update my OS and after a fresh install I just have the popular "uploader id" bug to deal with. Might as well close this issue since I think it was just the result of many installs/uninstalls of various packages and random bits of software that corrupted my python environment in some way.
