### ISSUE TITLE
Youtube download not working: RegexNotFoundError

### ISSUE THREAD

**Issue by shawwn** [ytdl-org/youtube-dl#32003]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl 'https://www.youtube.com/watch?v=vYhtYjXNBCU&ab_channel=EventHorizon' --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=vYhtYjXNBCU&ab_channel=EventHorizon', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.6 (CPython) - macOS-13.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] vYhtYjXNBCU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/shawn/Library/Python/3.9/lib/python/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/shawn/Library/Python/3.9/lib/python/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/shawn/Library/Python/3.9/lib/python/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/Users/shawn/Library/Python/3.9/lib/python/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/Users/shawn/Library/Python/3.9/lib/python/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

This issue popped up when running the following command:

```sh
youtube-dl 'https://www.youtube.com/watch?v=vYhtYjXNBCU&ab_channel=EventHorizon' --verbose
```

**Comment by shawwn** [comment]
I sidestepped the bug by editing `/opt/homebrew/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py` line 1782 as follows:

```py
        owner_profile_url = microformat.get('ownerProfileUrl')
        owner_profile_url = None # TKTK: This sidesteps an error: https://github.com/ytdl-org/youtube-dl/issues/32003
```

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar issues including closed ones

Try again. Learn how from #30839.
