### ISSUE TITLE
Not able to Download playlist. 

### ISSUE THREAD

**Issue by AzadKshitij** [ytdl-org/youtube-dl#32013]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--extract-audio', '--audio-format', 'mp3', '--verbose', '--output', 'Music/YouTube/%(playlist_title)s/%(playlist_index)s - %(title)s.%(ext)s', 'PLhKO-ucc19G8hIYGNkHyeQouMBtmMQO_V']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22621
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev, ffprobe 5.1.2-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube:tab] PLhKO-ucc19G8hIYGNkHyeQouMBtmMQO_V: Downloading webpage
[download] Downloading playlist: english
[youtube:tab] playlist english: Downloading 26 videos
[download] Downloading video 1 of 26
[youtube] DKbfBSrjVHA: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

### My Bat file
```bat
for %%a in (%*) do (
.\youtube-dl.exe ^
--extract-audio ^
--audio-format mp3 ^
--verbose ^
--output "Music/YouTube/%%(playlist_title)s/%%(playlist_index)s - %%(title)s.%%(ext)s" ^
%%a
)
```

### Command
`Try.bat https://youtube.com/playlist?list=PLhKO-ucc19G8hIYGNkHyeQouMBtmMQO_V`
`youtube-dl is up-to-date (2021.12.17)`

**Comment by PrincessRTFM** [comment]
This _is_ a broken site support issue, isn't it? Either way, same problem here on WSL ubuntu 20.02: tried to download a [youtube playlist](https://www.youtube.com/playlist?list=PLaiPn4ewcbkHnY4DsMx7-jf5eOxTEOynP) with version `2021.12.17`, couldn't extract uploader ID. [Verbose output here](https://github.com/ytdl-org/youtube-dl/files/11185198/ytdl.log), command manually entered for debugging.

**Comment by dirkf** [comment]
>This is a broken site support issue, isn't it? 

Yes.

>[x] I've searched the bugtracker for similar bug reports including closed ones

Learn how by reading #30839 (**again**?).

>[x] I've read bugs section in FAQ

Apply this.
