### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by Arindam905** [ytdl-org/youtube-dl#32046]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
-->

```
<!--
youtube-dl --verbose https://youtu.be/dQw4w9WgXcQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://youtu.be/dQw4w9WgXcQ']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.2 (CPython) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev, ffprobe 6.0-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] dQw4w9WgXcQ: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\NeeD\Documents\Visual Studio 2022\PYTHON\wholeSomeBot\env\Lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NeeD\Documents\Visual Studio 2022\PYTHON\wholeSomeBot\env\Lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\NeeD\Documents\Visual Studio 2022\PYTHON\wholeSomeBot\env\Lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NeeD\Documents\Visual Studio 2022\PYTHON\wholeSomeBot\env\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract       
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NeeD\Documents\Visual Studio 2022\PYTHON\wholeSomeBot\env\Lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex        
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

**Comment by demurgos** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31530
