### ISSUE TITLE
STRETCHIT

### ISSUE THREAD

**Issue by slavakurilyak** [ytdl-org/youtube-dl#32041]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://player.vimeo.com/450c6176-2551-4855-a7ba-0737368a78f9
- Web app link: https://web.stretchitapp.com/app/packages/4/lesson/174

## Description

[STRETCHIT](https://web.stretchitapp.com/app/home) uses Vimeo for its classes.

Running `youtube-dl -v https://web.stretchitapp.com/app/packages/4/lesson/174\?event_id\=15222708` gives:

```bash
youtube-dl -v https://web.stretchitapp.com/app/packages/4/lesson/174\?event_id\=15222708
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://web.stretchitapp.com/app/packages/4/lesson/174?event_id=15222708']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.3 (CPython) - macOS-12.6.3-x86_64-i386-64bit
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 174?event_id=15222708: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 174?event_id=15222708: Downloading webpage
[generic] 174?event_id=15222708: Extracting information
ERROR: Unsupported URL: https://web.stretchitapp.com/app/packages/4/lesson/174?event_id=15222708
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/extractor/generic.py", line 3489, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://web.stretchitapp.com/app/packages/4/lesson/174?event_id=15222708
```

**Comment by dirkf** [comment]
This site is a JS application. The non-JS page seen by yt-dl doesn't include the Vimeo links, so there's no chance that yt-dl can find them with its generic extractor.

By tracing browser traffic and/or inspecting the site JS, it might be possible to emulate the site JS in an extractor. It may also be necessary to pass some site-specific data through to the Vimeo extractor, as with the Dropout extractor.

**Comment by dirkf** [comment]
Also: https://github.com/yt-dlp/yt-dlp/issues/6805
