### ISSUE TITLE
Youtube dlg bug

### ISSUE THREAD

**Issue by csorsz** [ytdl-org/youtube-dl#32062]
Hi!

I have an issue of youtube dlg.
[04/19/23 21:34:18] [debug] youtube-dl version 2021.12.17
[04/19/23 21:34:18] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[04/19/23 21:34:18] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[04/19/23 21:34:18] [debug] Proxy map: {}
[04/19/23 21:34:18] ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[04/19/23 21:34:18] Traceback (most recent call last):
[04/19/23 21:34:18]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
[04/19/23 21:34:18]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
[04/19/23 21:34:18]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
[04/19/23 21:34:18]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
[04/19/23 21:34:18]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
[04/19/23 21:34:18] youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[04/19/23 21:34:18] 

Can you check it? Thanks!!!

## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
#30839 !
