### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by exelar166** [ytdl-org/youtube-dl#32079]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
PS C:\Users\bilgi\OneDrive\Masaüstü\mmv wallapper> youtube-dl --verbose flag
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'flag']
[debug] Encodings: locale cp1254, fs utf-8, out utf-8, pref cp1254
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.2 (CPython) - Windows-10-10.0.22621-SP0
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev, ffprobe 5.1.2-full_build-www.gyan.dev
[debug] Proxy map: {}
ERROR: 'flag' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:flag" ) to search YouTube
Traceback (most recent call last):
  File "C:\Users\bilgi\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilgi\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\bilgi\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilgi\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\generic.py", line 2361, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: 'flag' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:flag" ) to search YouTube

**Comment by klekaelly** [comment]
Having a similar issue:

youtube-dl --audio-format mp3 -o "C:\Users\alek\Desktop" --verbose https://www.youtube.com/watch?v=kwWY14b5SnA
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--audio-format', 'mp3', '-o', 'C:\\Users\\alek\\Desktop', '--verbose', 'https://www.youtube.com/watch?v=kwWY14b5SnA']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev, ffprobe 5.1.2-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] kwWY14b5SnA: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by leoTlr** [comment]
Same problem:

youtube-dl --verbose https://www.youtube.com/watch\?v\=QVAD6VPIPSs                                                                                                                                                                                                ✔ 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=QVAD6VPIPSs']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.10 (CPython) - Linux-5.15.105-1-MANJARO-x86_64-with-glibc2.37
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[youtube] QVAD6VPIPSs: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
Follow #30839 **as requested**; use the checklist; use the right template if you do have to open an issue: you're trying, unnecessarily, to report a bug, not ask a question, unless the question is implicitly "Should I file a duplicate report for a known issue using the wrong template?". Unsurprisingly, no.
