### ISSUE TITLE
RegexNotFoundError

### ISSUE THREAD

**Issue by benjibasson83** [ytdl-org/youtube-dl#32082]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --no-cache-dir --extract-audio --audio-format mp3 -w -i -o "%(title)s.%(ext)s" https://m.youtube.com/watch?v=JQCD5LBJ1jU --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-cache-dir', '--extract-audio', '--audio-format', 'mp3', '-w', '-i', '-o', '%(title)s.%(ext)s', 'https://m.youtube.com/watch?v=JQCD5LBJ1jU', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.7 (CPython) - Linux-4.19.157-perf+-aarch64-with-libc
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2
[debug] Proxy map: {}
[youtube] JQCD5LBJ1jU: Downloading webpage
[youtube] JQCD5LBJ1jU: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Hi
Impossible to download any movie from YouTube. It is because the last available version is too old. ( 2021)
It occurs for 3 mounth with zero solution here.
Please give me the update

Cheers

**Comment by dirkf** [comment]
The solution was merged on 24 February, so get it yourself. Read and follow #30839, as asked, to find your solution.

**Comment by benjibasson83** [comment]
Hi
Unfortunately there is still zero solution neither fix


Hi
pip install --upgrade --force-reinstall git+
https://github.com/ytdl-org/youtube-dl.git
Collecting git+https://github.com/ytdl-org/youtube-dl.git
Give
```
  Cloning https://github.com/ytdl-org/youtube-dl.git to
/data/data/com.termux/files/usr/tmp/pip-req-build-zvolm8k6
  ERROR: Error [Errno 2] No such file or directory: 'git' while executing
command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your
PATH?
```


pip install --upgrade youtube-dl give
`Requirement already satisfied: youtube-dl in
/data/data/com.termux/files/usr/lib/python3.11/site-packages (2021.12.17)`

YouTube dl doesn't work for 3 mounth and there is zero solution. Zero fix
although in this forum it is printed it has been fixed and that there is a
2023's update
Please give me the fix for

 ```
youtube-dl --no-cache-dir --extract-audio --audio-format mp3 -w -i -o
"%(title)s.%(ext)s" https://m.youtube.com/watch?v=JQCD5LBJ1jU --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-cache-dir', '--extract-audio',
'--audio-format', 'mp3', '-w', '-i', '-o', '%(title)s.%(ext)s', '
https://m.youtube.com/watch?v=JQCD5LBJ1jU', '--verbose']
[debug] Encodings: locale utf-8, fs utf-8, out utf-8, pref utf-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.3 (CPython) -
Linux-4.19.157-perf+-aarch64-with-libc
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[youtube] JQCD5LBJ1jU: Downloading webpage
[youtube] JQCD5LBJ1jU: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on
https://yt-dl.org/bug . Make sure you are using the latest version; see
https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with
the --verbose flag and include its complete output.
Traceback (most recent call last):
  File
"/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py",
line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py",
line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File
"/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py",
line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File
"/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py",
line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)',
owner_profile_url, 'uploader id') if owner_profile_url else None,

 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py",
line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please
report this issue on https://yt-dl.org/bug . Make sure you are using the
latest version; see  https://yt-dl.org/update  on how to update. Be sure to
call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by benjibasson83** [comment]
Hi

In fact there is no solution at all neither fix
In fact

pip install --upgrade --force-reinstall git+https://github.com/ytdl-org/youtube-dl.git
Collecting git+https://github.com/ytdl-org/youtube-dl.git
Give 
```
  Cloning https://github.com/ytdl-org/youtube-dl.git to /data/data/com.termux/files/usr/tmp/pip-req-build-zvolm8k6
  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
```


pip install --upgrade youtube-dl give
`Requirement already satisfied: youtube-dl in /data/data/com.termux/files/usr/lib/python3.11/site-packages (2021.12.17)`

YouTube dl doesn't work for 3 mounth and there is zero solution. Zero fix although in this forum it is printed it has been fixed and that there is a 2023's update 
Please give me the fix for

 ```
youtube-dl --no-cache-dir --extract-audio --audio-format mp3 -w -i -o "%(title)s.%(ext)s" https://m.youtube.com/watch?v=JQCD5LBJ1jU --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-cache-dir', '--extract-audio', '--audio-format', 'mp3', '-w', '-i', '-o', '%(title)s.%(ext)s', 'https://m.youtube.com/watch?v=JQCD5LBJ1jU', '--verbose']
[debug] Encodings: locale utf-8, fs utf-8, out utf-8, pref utf-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.3 (CPython) - Linux-4.19.157-perf+-aarch64-with-libc
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[youtube] JQCD5LBJ1jU: Downloading webpage
[youtube] JQCD5LBJ1jU: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
