### ISSUE TITLE
Unable to use Youtube-dl again for some reason?

### ISSUE THREAD

**Issue by NickWinston123** [ytdl-org/youtube-dl#32080]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
myubuntu@myspc:/mnt/g/Music Production/+DRUM K!Ts/access/Spleeter$ youtube-dl --verbose --cookies utube_cookies.txt --extract-audio --audio-format mp3 https://www.youtube.com/watch?v=kUHtT0eXdbk
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--cookies', u'utube_cookies.txt', u'--extract-audio', u'--audio-format', u'mp3', u'https://www.youtube.com/watch?v=kUHtT0eXdbk']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube] kUHtT0eXdbk: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

myubuntu@myspc:/mnt/g/Music Production/+DRUM K!Ts/access/Spleeter$
```

## Description

Using this inside WSL2 on windows 11 - this was working before but recently I started using it again and came back to find it not working. I have tried to update my youtube-dl but nothing has helped. Also fails for any video I tried regardless of arguments

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar bug reports including closed ones

Learn how by studying #30839 (**again**?), or just follow the link there to the known master issue for your problem.

>[x] I've read bugs section in FAQ

Apply this.

> ... this was working before ...

If this was not an already known issue, something more accurate than "before" would have been useful.

You should probably update to an unofficial nightly build for POSIX, which you will be guided to find in the master issue linked from #30839.
