### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by gklimm** [ytdl-org/youtube-dl#32094]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://us02web.zoom.us/rec/share/9pdVT4f2XWBaEOSqDJagSsvI0Yu2ixXW0YcJGIVhfV19Zr7E1q5gf0wTMZHnqrvq.Yoq1dDHeeKjaVcv3']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-21-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.4.4, ffprobe 4.4.4, rtmpdump 2.4
[debug] Proxy map: {}
[zoom] 9pdVT4f2XWBaEOSqDJagSsvI0Yu2ixXW0YcJGIVhfV19Zr7E1q5gf0wTMZHnqrvq.Yoq1dDHeeKjaVcv3: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('topic')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/zoom.py", line 60, in _real_extract
    'title': data['topic'],
KeyError: 'topic'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/zoom.py", line 60, in _real_extract
    'title': data['topic'],
KeyError: 'topic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 547, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('topic')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
Does this play for you? I get "Untersuchungskurs Gruppe V- Shared screen with speaker view" and a player widget with an unresponsive play button and the text "No compatible source was found for this media."

However, I can reproduce the above.

yt-dlp also fails but with:
`[zoom] 9pdVT4f2XWBaEOSqDJagSsvI0Yu2ixXW0YcJGIVhfV19Zr7E1q5gf0wTMZHnqrvq.Yoq1dDHeeKjaVcv3: No video formats found!`

**Comment by october262** [comment]
video plays ok for me, you can also just right click on the video and click "save as" 
to download the video in mp4 format. yt-dlp & youtube-dl doesn't work for me either,
however ytdl-patched does download this video.

**Comment by gklimm** [comment]
Yes, ytdl-patched works fine!
Hope that @shiningw takes this in future for the [ncdownloader](https://github.com/shiningw/ncdownloader)

**Comment by gklimm** [comment]
This reads as if metadata would then come again and perhaps a meaningful file name would be generated. That would be awesome

**Comment by dirkf** [comment]
The problem page will generate this filename:
`Untersuchungskurs Gruppe V-9pdVT4f2XWBaEOSqDJagSsvI0Yu2ixXW0YcJGIVhfV19Zr7E1q5gf0wTMZHnqrvq.Yoq1dDHeeKjaVcv3.mp4`

Awesomeness may be in the eye of the beholder.

**Comment by dirkf** [comment]
If anyone cares to test the linked PR, please report there.
