### ISSUE TITLE
New version installed but still get this...

### ISSUE THREAD

**Issue by CodeKraft** [ytdl-org/youtube-dl#32100]
youtube-dl worked fine until a month ago when all of a sudden this kept on happening...

ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

so I issue the --verbose tag and it tells me nothing 

so I then use the youtube-dl -U and all it says is...

youtube-dl is up-to-date (2021.12.17)

I am not asking for any uploader ID to be called, yet this is the error.

**Comment by 1jamesthompson1** [comment]
I am getting a similiar issue however I have just installed it.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=Z7ztz3y8rMQ', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.0 (CPython) - Windows-10-10.0.22621-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Z7ztz3y8rMQ: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\james\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\james\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\james\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\users\james\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "c:\users\james\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by tonejito** [comment]
Same here on macOS Python 3.11. `youtube-dl` was installed via `brew`:

```
% which youtube-dl
/opt/homebrew/bin/youtube-dl

% youtube-dl --version
2021.12.17

% youtube-dl --verbose --no-progress 'https://www.youtube.com/watch?v=TdddA3hZjBs'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--no-progress', 'https://www.youtube.com/watch?v=TdddA3hZjBs']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.3 (CPython) - macOS-12.6.4-arm64-arm-64bit
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[youtube] TdddA3hZjBs: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/tonejito/Library/Python/3.11/lib/python/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tonejito/Library/Python/3.11/lib/python/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/Users/tonejito/Library/Python/3.11/lib/python/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tonejito/Library/Python/3.11/lib/python/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tonejito/Library/Python/3.11/lib/python/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by tonejito** [comment]
I think that the developers are aware of this issue, see #31530.

Also see #30839 for the issue template.

**Comment by CodeKraft** [comment]
So this has existed for more than a month and still not working... Are the devs going to get round to solving the problem?

It still downloads facebook and dailymotion videos... but youtube it complains about the vendor ID

Closing the topic isn't helpful and saying its not planned this week... then marking it duplicate and incomplete when the information has been provided... 

Is this download issue going to be resolved or not?

**Comment by dirkf** [comment]
The current solutions for your problem are clearly laid out in the master issue (linked in the post above) that you spammed. You would have been directed to that issue if you had bothered to read and follow #30839, as asked. As your issue **is** a duplicate, it is so marked and closed as not planned. Further posting in a closed duplicate issue is spam.

If you don't care for any solution offered, wait for one you like, or make your own.
