### ISSUE TITLE
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id - Cant download youtube video (id: U2kmria5JmU)

### ISSUE THREAD

**Issue by Daij-Djan** [ytdl-org/youtube-dl#32136]
## Checklist
- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
1. try (youtu.be url)
```
youtube-dl "https://youtu.be/U2kmria5JmU" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://youtu.be/U2kmria5JmU', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - macOS-13.3.1-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] U2kmria5JmU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

2. try (youtube.com url)
```
youtube-dl "https://www.youtube.com/watch?v=U2kmria5JmU" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=U2kmria5JmU', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - macOS-13.3.1-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] U2kmria5JmU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description
Trying to grab the movie with the id U2kmria5JmU from youtube, I always get 'youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id'

**Comment by nekoyama32767** [comment]
Same error. 
It sames that youtube has change some APIs.

**Comment by DJmong** [comment]
Same error
Maybe it's not a program error
version : 21.06.06
system : raspberry pi 4B+

**Comment by dmzoneill** [comment]
same issue

```
dave@dave-pc:~/Desktop$ youtube-dl "https://www.youtube.com/watch?v=cbIDH1Fnw3Y"
[youtube] cbIDH1Fnw3Y: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
dave@dave-pc:~/Desktop$ youtube-dl --version
2021.12.17

```

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar issues including closed ones

Learn how by reading #30839 (**again**?).

**Comment by Daij-Djan** [comment]
passive aggressiveness is not that cool ;) I did search and sorry I didnt find one which is my bad]
-- just wanted to share :)

**Comment by dirkf** [comment]
The issue is **actually listed** as a known issue in the pinned issue!

If you didn't find it there but followed the suggestions for searching:
* [here](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+Unable+to+extract+uploader+id+-label%3Aduplicate) it's in the first page of results (other results higher up may also link to it)
* [adding `in:title`](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+Unable+to+extract+uploader+id+-label%3Aduplicate+in%3Atitle) it's the first result

Would you prefer active aggression ;)?

**Comment by Daij-Djan** [comment]
I get that nobody pays you here but i wonder why it is hard to be nice
Ill delete this post and am sorry I ever bothered u
