### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by OlMi1** [ytdl-org/youtube-dl#32159]
## Checklist

- [x] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
C:\Users\Ole>C:\Users\Ole\Downloads\youtube-dl.exe -U
youtube-dl is up-to-date (2021.12.17)

C:\Users\Ole>C:\Users\Ole\Downloads\youtube-dl.exe --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s" "https://www.youtube.com/playlist?list=PLeVXhjd6cOIUAeR3NgR8pvPCTezXbWxMT" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--extract-audio', '--audio-format', 'mp3', '-o', '%(title)s.%(ext)s', 'https://www.youtube.com/playlist?list=PLeVXhjd6cOIUAeR3NgR8pvPCTezXbWxMT', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:tab] PLeVXhjd6cOIUAeR3NgR8pvPCTezXbWxMT: Downloading webpage
[download] Downloading playlist: DnB
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] playlist DnB: Downloading 251 videos
[download] Downloading video 1 of 251
[youtube] XU1x3o8DbTQ: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Command is in the log above. Reading the last few instances of this error does not have any result, just crosslinks to other issues where nothing was resolved.

**Comment by dirkf** [comment]
Nonetheless, study #30839 as asked, which **actually lists** the master issue for this problem, and which is also the top issue when searching the tracker for `Unable to extract uploader id -label:duplicate in:title` as suggested in #30839.
