### ISSUE TITLE
youtube-dl is unable to extract `uploader id`, can't download yt videos using python

### ISSUE THREAD

**Issue by Avinier** [ytdl-org/youtube-dl#32164]
## Checklist

- [ x] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[youtube] Vc9Huk0hy4U: Downloading webpage
[youtube] Downloading just video Vc9Huk0hy4U because of --no-playlist
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Kanyefy-AI-Voice\kanyefy-python-scripts\vocalbeats_finder.py", line 56, in <module>
    download_yt_mp3(yt_links[0])
  File "E:\Kanyefy-AI-Voice\kanyefy-python-scripts\vocalbeats_finder.py", line 48, in download_yt_mp3
    downloader.download([yt_url])
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py", line 2068, in download
    res = self.extract_info(
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

So this is my code-
`def download_yt_mp3(yt_url):
    ydl_options = {
        'format': 'bestaudio/best',
        'extractaudio': True,
        'audioformat': 'mp3',
        'outtmpl': '%(title)s.%(ext)s',
        'noplaylist': True,
        'nocheckcertificate': True,
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }],
    }

    with youtube_dl.YoutubeDL(ydl_options) as downloader:
        downloader.download([yt_url])

    print("Links downloaded!")
    return
    
  download_yt_mp3(yt_links[0])
`
and getting that above error, please help

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar bug reports including closed ones

Learn how by reading #30839 (**again**?).

>[x] I've read bugs section in FAQ

Apply this.

**Comment by Elpsico2** [comment]
LISTA DE VERIFICACION:
-He verificado que estoy ejecutando youtube-dl versión 2021.12.17
-He comprobado que todas las URL proporcionadas están vivas y se pueden reproducir en un navegador

REGISTRO DETALLADO:

ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Codigo

def run_assistant():
    while True:
        command = listen()
        if 'reproduce' in command and 'youtube' in command:
            video = command.replace('reproduce', '').replace('youtube', '').strip()
            print("Buscando video en YouTube:", video)
            talk("Buscando video en YouTube: " + video)
            try:
                # Realizar la búsqueda en YouTube
                ydl = youtube_dl.YoutubeDL({'format': 'best'})
                with ydl:
                    result = ydl.extract_info("ytsearch:" + video, download=False)
                    if 'entries' in result:
                        url = result['entries'][0]['webpage_url']
                        # Descargar el video de YouTube
                        file_path = './videos'
                        download_video(url, file_path)
                        # Reproducir el video descargado
                        print("Reproduciendo video:", video)
                        talk("Reproduciendo video: " + video)
                        play_video(file_path)
                    else:
                        print("No se encontraron resultados en YouTube para:", video)
                        talk("No se encontraron resultados en YouTube para: " + video)
            except Exception as e:
                print("Error al buscar y reproducir el video:", str(e))
                talk("Ocurrió un error al buscar y reproducir el video")
        elif 'detente' in command or 'para' in command:
            print("Deteniendo reproducción")
            talk("Deteniendo reproducción")
            stop_video()
        elif 'salir' in command:
            print("Saliendo del asistente")
            talk("Hasta luego")
            break

if __name__ == '__main__':
    run_assistant()

porfavor con el error
