### ISSUE TITLE
[Errno 13] Permission denied

### ISSUE THREAD

**Issue by ryanthackston** [ytdl-org/youtube-dl#32176]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
/usr/local/bin$ python3 $(which youtube-dl) --verbose https://www.youtube.com/watch?v=0IE-CXNs6Sw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=0IE-CXNs6Sw']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.15.0-71-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg present, ffprobe present
[debug] Proxy map: {}
[youtube] 0IE-CXNs6Sw: Downloading webpage
[debug] [youtube] Decrypted nsig ejO-eTyJvDCJZkk5F => S5oWTDyqWJLXlQ
[debug] [youtube] Decrypted nsig eHxBrHAmtl-uZFWx6 => 3JbxjdybiQQn9g
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://rr3---sn-q4fl6nsr.googlevideo.com/videoplayback?expire=1683849891&ei=Qy5dZNjyNrOZ2_gP_5i_kA4&ip=37.19.221.165&id=o-AIRNuNSg6xOfC-nIkHWaBXVNPkRU5DIjzG_276hF0vZl&itag=247&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=youtube&requiressl=yes&mh=Ip&mm=31%2C26&mn=sn-q4fl6nsr%2Csn-a5meknd6&ms=au%2Conr&mv=m&mvi=3&pl=25&initcwndbps=2302500&vprv=1&svpuc=1&mime=video%2Fwebm&ns=fhqWY3twwvAYPpZnhFODQKsN&gir=yes&clen=189117208&dur=4140.599&lmt=1590097998868296&mt=1683827836&fvip=5&keepalive=yes&fexp=24007246&c=WEB&txp=5432432&n=S5oWTDyqWJLXlQ&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKbOAuCjx83MWJgMq2g8-1aZPKWDeHEkgBd9BNkNQ3xCAiEAkTZRtP1tBoQYaCFfDXaJnftrZkzVFEKwyH0JCxcAJEA%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgEPoj9sFHYJ2IF1cGUhNxfH6i11NwT1LFEJDnWtcSh9MCIDbQnST0_JJX4zvib4KXXOeZpXgKW_7XbOK_C31_85Dy'
[dashsegments] Total fragments: 19
[download] Destination: Introduction to Data Streaming-0IE-CXNs6Sw.f247.webm
ERROR: unable to download video data: [Errno 13] Permission denied: 'Introduction to Data Streaming-0IE-CXNs6Sw.f247.webm.ytdl'
Traceback (most recent call last):
  File "/home/frog/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1984, in process_info
    partial_success = dl(fname, new_info)
  File "/home/frog/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1929, in dl
    return fd.download(name, info)
  File "/home/frog/.local/lib/python3.8/site-packages/youtube_dl/downloader/common.py", line 376, in download
    return self.real_download(filename, info_dict)
  File "/home/frog/.local/lib/python3.8/site-packages/youtube_dl/downloader/dash.py", line 30, in real_download
    self._prepare_and_start_frag_download(ctx)
  File "/home/frog/.local/lib/python3.8/site-packages/youtube_dl/downloader/fragment.py", line 69, in _prepare_and_start_frag_download
    self._prepare_frag_download(ctx)
  File "/home/frog/.local/lib/python3.8/site-packages/youtube_dl/downloader/fragment.py", line 193, in _prepare_frag_download
    self._write_ytdl_file(ctx)
  File "/home/frog/.local/lib/python3.8/site-packages/youtube_dl/downloader/fragment.py", line 87, in _write_ytdl_file
    frag_index_stream, _ = sanitize_open(self.ytdl_filename(ctx['filename']), 'w')
  File "/home/frog/.local/lib/python3.8/site-packages/youtube_dl/utils.py", line 2077, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
PermissionError: [Errno 13] Permission denied: 'Introduction to Data Streaming-0IE-CXNs6Sw.f247.webm.ytdl'

```

## Description

I was originally getting the common Uploader ID error and applied the fix dirkf gave from here:

https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435477247

but now I'm getting this **[Errno 13] Permission denied: 'Introduction to Data Streaming-0IE-CXNs6Sw.f247.webm.ytdl**

coming from this similar issue https://github.com/ytdl-org/youtube-dl/issues/16462

I applied ```sudo chmod u+w youtube-dl```
write permissions to my youtube-dl in /usr/local/bin

I've restarted the terminal and still getting the same issue. I'm not sure exactly what the problem is. Do I need to add permissions to something else?

I'm glad I'm getting the link to download but it would be really appreciated if you could point me in the direction to fix this one problem so the program can automatically download and save a few clicks.

**Comment by dirkf** [comment]
You are trying to run yt-dl in a directory where you have no write permission, specifically `/usr/local/bin`. Does that seem like a good idea? That directory should be on your `PATH` (`echo $PATH`) so the yt-dl that you have in that directory will be run if you use the command `youtube-dl` -- unless you have a yt-dl in one of the directories earlier in the `PATH`. If that is the case, remove whichever yt-dls you don't want.

**Comment by dirkf** [comment]
@ryanthackston ?

**Comment by dirkf** [comment]
Closing for lack of response.
