### ISSUE TITLE
Installing youtube-dl with python on Windows

### ISSUE THREAD

**Issue by Dosingr** [ytdl-org/youtube-dl#32180]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

When i first encountered the program, i struggled with the python installation so i settled for the .exe one (i'm on windows). But, as of now, i would like to be able to install and use it with python. The problem is, i am still struggling a lot with the python installation (spending multiple hours on trying to get it working). 

So how should i correctly install and use youtube-dl with python ? (I am using Pyzo but i don't think the IDE matters a lot)

I tried ```pip install youtube-dl``` and ```pip install --upgrade --force-reinstall git+https://github.com/ytdl-org/youtube-dl.git```. The files are indeed presents in my python libs folder but when i execute ```youtube-dl [Any URL]```, i always get "SyntaxError: invalid syntax" (I did import youtube-dl in the file). I also tried to run the "setup.py" file from the archive but the whole thing just shutdown, here is the error :
```
UserWarning: Skipping file youtube-dl.bash-completion since it is not present. Type  make  to build all automatically generated files.
  warnings.warn('Skipping file %s since it is not present. Type  make  to build all automatically generated files.' % fn)
C:\Users\dosin\Downloads\youtube-dl-master\setup.py:76: UserWarning: Skipping file youtube-dl.fish since it is not present. Type  make  to build all automatically generated files.
  warnings.warn('Skipping file %s since it is not present. Type  make  to build all automatically generated files.' % fn)
C:\Users\dosin\Downloads\youtube-dl-master\setup.py:76: UserWarning: Skipping file README.txt since it is not present. Type  make  to build all automatically generated files.
  warnings.warn('Skipping file %s since it is not present. Type  make  to build all automatically generated files.' % fn)
C:\Users\dosin\Downloads\youtube-dl-master\setup.py:76: UserWarning: Skipping file youtube-dl.1 since it is not present. Type  make  to build all automatically generated files.
  warnings.warn('Skipping file %s since it is not present. Type  make  to build all automatically generated files.' % fn)
usage:  [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or:  --help [cmd1 cmd2 ...]
   or:  --help-commands
   or:  cmd --help

error: no commands supplied

The kernel process exited. (1)
```

Could anyone provide me instructions or redirect me to a place where i can find the proper way to do things ? (I did lookup online before asking here)

**Comment by dirkf** [comment]
_pip_ should have done any setup that's necessary.

After paragraph 3 sentence 1, what command runs when you type `youtube-dl --version`? Also show the output from `youtube-dl --verbose`.

**Comment by Dosingr** [comment]
As of now, the code looks like this :
```
import youtube_dl

#youtube-dl --verbose https://youtu.be/Jl877KCP33M

youtube-dl --version
```

When i executed ```youtube-dl --verbose https://youtu.be/Jl877KCP33M```, i get ```SyntaxError: invalid syntax```.
As for, ```youtube-dl --version```, the result is ```NameError: name 'youtube' is not defined```.

**Comment by dirkf** [comment]
Is that your code or something installed by _pip_? If the former, what happens without it? I understood that Windows _pip_ created a command when installing.

Maybe you need to add `#egg=youtube-dl` to the URL when installing: see discussion in #31350 -- if you can somehow find it.

If I'd implemented this, I'd probably have put a file called `youtube-dl.com` in the `%PATH%` to launch Python running the yt-dl main program. I've never tried this config in native Windows (WSL FTW).

**Comment by Dosingr** [comment]
You're right, there is a file called "YoutubeDL.py". Sorry I didn't notice. (It seems to be the right thing to execute because there is YoutubeDL class defined in it with all the usual parameters).
Still, I got an error while executing it :
```
Traceback (most recent call last):
  File "C:\Users\dosin\AppData\Local\Programs\Python\Python39\Lib\site-packages\youtube_dl\YoutubeDL.py", line 33, in <module>
    from .compat import (
ImportError: attempted relative import with no known parent package
```

**Comment by dirkf** [comment]
The _pip_-based installation should have set up a `youtube-dl` command that you can run from a _cmd_ (or other) shell, so that you don't have to guess which Python source file to run. You may have to adjust your system PATH for the command to be found.

Such a command would essentially do `python ytdl_dir`, where `ytdl-dir` is the directory that contains the `YoutubeDL.py` that you found (and `__init__.py`, `__main__.py`).

[This SO](https://stackoverflow.com/a/75621320) answer suggests various possibilities for the directory. A _cmd_ script could do s/t like this.

```cmd
@echo off
python "C:\Program Files\Python310\Lib\site-packages\youtube_dl" %*
```

**Comment by Dosingr** [comment]
I apologize for the delay in answering. 
I tried to make .bat file with the provided script (I did change the path according to mine) and it didn't work. I tried another time after adding the python folder to the path and it didn't work either. Perhaps, I need to reboot the computer for taking into account the change in the PATH var ? I don't know much about it

**Comment by dirkf** [comment]
Try showing us the terminal log of your _pip_-based installation (with `--force-reinstall`) and then the result of a command `youtube-dl --verbose` and of `python dir`, where `python` is how you invoke your Python and `dir` is the pathname of the directory that contains `YoutubeDL.py`.

When I used to use Windows more than once a year, you had to use the terminal window menu to copy text. This may no longer be necessary, depending on settings.

**Comment by Dosingr** [comment]
I tried different methods since last time.

First, making a file with the script found in this issue : #32164

```
import youtube_dl

def download_yt_mp3(yt_url):
    ydl_options = {
        'format': 'bestaudio/best',
        'extractaudio': True,
        'audioformat': 'mp3',
        'outtmpl': '%(title)s.%(ext)s',
        'noplaylist': True,
        'nocheckcertificate': True,
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }],
    }

    with youtube_dl.YoutubeDL(ydl_options) as downloader:
        downloader.download([yt_url])

    print("Links downloaded!")
    return download_yt_mp3(yt_links[0])

download_yt_mp3(["https://youtu.be/Jl877KCP33M"])
```

The error is still about compat :

```
Traceback (most recent call last):
  File "C:\Users\dosin\Gate.py", line 1, in <module>
    import youtube_dl
  File "c:\users\dosin\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\__init__.py", line 45, in <module>
    from .YoutubeDL import YoutubeDL
  File "c:\users\dosin\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 33, in <module>
    from compat import (
ModuleNotFoundError: No module named 'compat'
```

I wasn't able to execute directly ```youtube-dl --verbose https://youtu.be/Jl877KCP33M``` because it would return ```SyntaxError: invalid syntax``` and trying to import the module from the python shell also return the error : 
```
>>> import youtube_dl
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "c:\users\dosin\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\__init__.py", line 45, in <module>
    from .YoutubeDL import YoutubeDL
  File "c:\users\dosin\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 33, in <module>
    from compat import (
ModuleNotFoundError: No module named 'compat'
```


For the examples you asked, i opened a powershell in the directory containing YoutubeDL.py.
For the verbose test : 
```
PS C:\Users\dosin\AppData\Local\Programs\Python\Python39\Lib\site-packages\youtube_dl> youtube-dl --verbose https://youtu.be/Jl877KCP33M
youtube-dl : Le terme «youtube-dl» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou
programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès
est correct et réessayez.
Au caractère Ligne:1 : 1
+ youtube-dl --verbose https://youtu.be/Jl877KCP33M
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (youtube-dl:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

For the  ```python dir```  test : 

```
C:\Users\dosin\AppData\Local\Programs\Python\Python39\Lib\site-packages\youtube_dl> python C:\Users\dosin\AppData\Local\Programs\Python\Python39\Lib\site-packages\youtube_dl
Traceback (most recent call last):
  File "E:\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\dosin\AppData\Local\Programs\Python\Python39\Lib\site-packages\youtube_dl\__main__.py", line 16, in <module>
    import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'
```


I then tried to install it with Anaconda, just in case my usual IDE setup would conflict with it (we never know).
I followed those steps : 

Anaconda -> environments -> create youtubedelenv
anaconda prompt -> activate youtubedelenv -> pip install --upgrade --force-reinstall "git+https://github.com/ytdl-org/youtube-dl.git"

Output : 

```
(youtubedelenv) C:\Users\dosin>pip install --upgrade --force-reinstall "git+https://github.com/ytdl-org/youtube-dl.git"
Collecting git+https://github.com/ytdl-org/youtube-dl.git
  Cloning https://github.com/ytdl-org/youtube-dl.git to c:\users\dosin\appdata\local\temp\pip-req-build-wjcjqby2
  Running command git clone --filter=blob:none --quiet https://github.com/ytdl-org/youtube-dl.git 'C:\Users\dosin\AppData\Local\Temp\pip-req-build-wjcjqby2'
  Resolved https://github.com/ytdl-org/youtube-dl.git to commit d1c6c5c4d618fa950813c0c71aede34a5ac851e9
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: youtube-dl
  Building wheel for youtube-dl (setup.py) ... done
  Created wheel for youtube-dl: filename=youtube_dl-2021.12.17-py2.py3-none-any.whl size=1935449 sha256=03e0b5970664ae5c16a8932405eaeba3f2344b3654eb0ead504a6638adb5791d
  Stored in directory: C:\Users\dosin\AppData\Local\Temp\pip-ephem-wheel-cache-6fmcyfgb\wheels\64\8e\40\866e846163e3e4859bbe820ff8847ec97f4320864f1525aa9a
Successfully built youtube-dl
Installing collected packages: youtube-dl
Successfully installed youtube-dl-2021.12.17
```

Then, I tried directly with the same youtube link i tried previously (https://youtu.be/Jl877KCP33M) but it didn't work (Error number -22). So i tried once again with verbose to get details : 

```
(youtubedelenv) C:\Users\dosin>youtube-dl --verbose https://youtu.be/Jl877KCP33M
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://youtu.be/Jl877KCP33M']
[debug] Encodings: locale cp932, fs utf-8, out utf-8, pref cp932
[debug] youtube-dl version 2021.12.17
[debug] Python 3.10.11 (CPython 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023, -)
[debug] exe versions: ffmpeg N-55702-g920046a, ffprobe N-55702-g920046a
[debug] Proxy map: {}
[youtube] Jl877KCP33M: Downloading webpage
[debug] [youtube] Decrypted nsig oOO6MfCaVNNLpaPF => fg0Gs8XLRRD-0A
[debug] [youtube] Decrypted nsig WkSNf1BlFjxVGRVG => 1deKC3PV6HWb_A
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://rr3---sn-cv0tb0xn-qpwl.googlevideo.com/videoplayback?expire=1684616791&ei=9-FoZOS4NdKixN8PofWryAw&ip=176.190.146.39&id=o-AISBxIpUJxQBg7DIfUxgYZgcJqalNgYM-03FoSuaRWp7&itag=247&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C394%2C395%2C396%2C397%2C398&source=youtube&requiressl=yes&mh=_n&mm=31%2C29&mn=sn-cv0tb0xn-qpwl%2Csn-25ge7nzd&ms=au%2Crdu&mv=m&mvi=3&pl=19&initcwndbps=1778750&vprv=1&svpuc=1&mime=video%2Fwebm&ns=o-IBrugCviKnPOuhckwUgtsN&gir=yes&clen=12488672&dur=264.764&lmt=1540656285687279&mt=1684594866&fvip=1&keepalive=yes&fexp=24007246%2C51000022&c=WEB&txp=5432432&n=fg0Gs8XLRRD-0A&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAI7R36x0NhJndZQJhsd5CoNUW_OWYc_qXJlKaCeGARtHAiB7bYer-7Ojg_Tdzpm5PNbdXDVPqYBD8R8gbYMh6Taptw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgSpUVUjK1rWIRvtXDAlVSQvCDVDvpgCyUFZrbSj08hW8CIQD79LW65jH-gC2sU1xtTtePX5O5qQukk1JNV41eF3INPQ%3D%3D'
[download] GATE Ost 01 Kanochi nite ~ Main Theme-Jl877KCP33M.f247.webm has already been downloaded
[download] 100% of 11.91MiB
[debug] Invoking downloader on 'https://rr3---sn-cv0tb0xn-qpwl.googlevideo.com/videoplayback?expire=1684616791&ei=9-FoZOS4NdKixN8PofWryAw&ip=176.190.146.39&id=o-AISBxIpUJxQBg7DIfUxgYZgcJqalNgYM-03FoSuaRWp7&itag=251&source=youtube&requiressl=yes&mh=_n&mm=31%2C29&mn=sn-cv0tb0xn-qpwl%2Csn-25ge7nzd&ms=au%2Crdu&mv=m&mvi=3&pl=19&initcwndbps=1778750&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=o-IBrugCviKnPOuhckwUgtsN&gir=yes&clen=4378377&dur=264.781&lmt=1540656488132381&mt=1684594866&fvip=1&keepalive=yes&fexp=24007246%2C51000022&c=WEB&txp=5411222&n=fg0Gs8XLRRD-0A&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgMHjL3nRBrbqtWy4WoVP5FneebvM0RjSVnj-aN2yJsjsCIF_ErP1KRH0lF9kD1KtD7wC8d4ECrUUExLrcPKu2C2By&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgSpUVUjK1rWIRvtXDAlVSQvCDVDvpgCyUFZrbSj08hW8CIQD79LW65jH-gC2sU1xtTtePX5O5qQukk1JNV41eF3INPQ%3D%3D'
[download] GATE Ost 01 Kanochi nite ~ Main Theme-Jl877KCP33M.f251.webm has already been downloaded
[download] 100% of 4.18MiB
[ffmpeg] Merging formats into "GATE Ost 01 Kanochi nite ~ Main Theme-Jl877KCP33M.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:GATE Ost 01 Kanochi nite ~ Main Theme-Jl877KCP33M.f247.webm" -i "file:GATE Ost 01 Kanochi nite ~ Main Theme-Jl877KCP33M.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:GATE Ost 01 Kanochi nite ~ Main Theme-Jl877KCP33M.temp.webm"
[debug] ffmpeg version N-55702-g920046a Copyright (c) 2000-2013 the FFmpeg developers
  built on Aug 21 2013 18:10:00 with gcc 4.7.3 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetype --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      52. 42.100 / 52. 42.100
  libavcodec     55. 29.100 / 55. 29.100
  libavformat    55. 14.101 / 55. 14.101
  libavdevice    55.  3.100 / 55.  3.100
  libavfilter     3. 82.100 /  3. 82.100
  libswscale      2.  5.100 /  2.  5.100
  libswresample   0. 17.103 /  0. 17.103
  libpostproc    52.  3.100 / 52.  3.100
[matroska,webm @ 0000000000efcfa0] Unknown entry 0x55B0
Input #0, matroska,webm, from 'file:GATE Ost 01 Kanochi nite ~ Main Theme-Jl877KCP33M.f247.webm':
  Duration: 00:04:24.77, start: 0.000000, bitrate: 377 kb/s
    Stream #0:0(eng): Video: vp9, 1280x720, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 1k tbc (default)
[matroska,webm @ 0000000000df85a0] Unknown entry 0x56AA
[matroska,webm @ 0000000000df85a0] Unknown entry 0x56BB
Input #1, matroska,webm, from 'file:GATE Ost 01 Kanochi nite ~ Main Theme-Jl877KCP33M.f251.webm':
  Duration: 00:04:24.78, start: 0.000000, bitrate: 132 kb/s
    Stream #1:0(spa): Audio: opus, 48000 Hz, stereo, s16 (default)
[webm @ 0000000000ef7520] Only VP8,VP9 video and Vorbis,Opus(experimental, use -strict -2) audio and WebVTT subtitles are supported for WebM.
Output #0, webm, to 'file:GATE Ost 01 Kanochi nite ~ Main Theme-Jl877KCP33M.temp.webm':
  Metadata:
    encoder         : Lavf55.14.101
    Stream #0:0(eng): Video: vp9, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 1k tbn, 1k tbc (default)
    Stream #0:1(spa): Audio: opus, 48000 Hz, stereo (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Error number -22 occurred
Traceback (most recent call last):
  File "C:\Users\dosin\anaconda3\envs\youtubedelenv\lib\site-packages\youtube_dl\YoutubeDL.py", line 2161, in post_process
    files_to_delete, info = pp.run(info)
  File "C:\Users\dosin\anaconda3\envs\youtubedelenv\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 527, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "C:\Users\dosin\anaconda3\envs\youtubedelenv\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 239, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Could not write header for output file #0 (incorrect codec parameters ?): Error number -22 occurred
```

So, with this method, it seems to work at least partially because there are indeed files waiting to be merge in the folder but it apprently can't write the final file correctly.

**Comment by dirkf** [comment]
In the last log, yt-dl is a new version (good), but your _ffmpeg_ is from  2013: I suppose it's confused by the fancy new formats YT is sending.

1. Try `-f mp4` or `-f best[ext=mp4]` to avoid invoking _ffmpeg_ for merging and to avoid webm (you should get format 18: see below). Report if that fails.
2. Update _ffmpeg_ to a version that's not more than 5 years old, and try your command above again (you should get formats 247+251 merged: as above, and see below).

```console
$ python -m youtube_dl -F 'Jl877KCP33M'
[youtube] Jl877KCP33M: Downloading webpage
[youtube] Jl877KCP33M: Downloading player e50626d8
[info] Available formats for Jl877KCP33M:
format code  extension  resolution note
249          webm       audio only tiny   50k , webm_dash container, opus  (48000Hz), 1.60MiB
250          webm       audio only tiny   67k , webm_dash container, opus  (48000Hz), 2.13MiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2 (44100Hz), 4.09MiB
251          webm       audio only tiny  132k , webm_dash container, opus  (48000Hz), 4.18MiB
160          mp4        256x144    144p   10k , mp4_dash container, avc1.4d400c, 24fps, video only, 349.67KiB
394          mp4        256x144    144p   28k , mp4_dash container, av01.0.00M.08, 24fps, video only, 912.00KiB
278          webm       256x144    144p   30k , webm_dash container, vp9, 24fps, video only, 982.50KiB
133          mp4        426x240    240p   18k , mp4_dash container, avc1.4d4015, 24fps, video only, 596.66KiB
395          mp4        426x240    240p   38k , mp4_dash container, av01.0.00M.08, 24fps, video only, 1.23MiB
242          webm       426x240    240p   58k , webm_dash container, vp9, 24fps, video only, 1.84MiB
134          mp4        640x360    360p   30k , mp4_dash container, avc1.4d401e, 24fps, video only, 972.40KiB
396          mp4        640x360    360p   70k , mp4_dash container, av01.0.01M.08, 24fps, video only, 2.21MiB
243          webm       640x360    360p  110k , webm_dash container, vp9, 24fps, video only, 3.48MiB
135          mp4        854x480    480p   42k , mp4_dash container, avc1.4d401e, 24fps, video only, 1.35MiB
244          webm       854x480    480p  118k , webm_dash container, vp9, 24fps, video only, 3.73MiB
397          mp4        854x480    480p  124k , mp4_dash container, av01.0.04M.08, 24fps, video only, 3.92MiB
136          mp4        1280x720   720p  115k , mp4_dash container, avc1.4d401f, 24fps, video only, 3.65MiB
398          mp4        1280x720   720p  320k , mp4_dash container, av01.0.05M.08, 24fps, video only, 10.10MiB
247          webm       1280x720   720p  377k , webm_dash container, vp9, 24fps, video only, 11.91MiB
18           mp4        640x360    360p  159k , avc1.42001E, 24fps, mp4a.40.2 (44100Hz) (best)
$
```

**Comment by Dosingr** [comment]
Thanks, it works now (with ```-f best[ext=mp4]```) !
I also downloaded the last ffmpeg to update later on.

Thanks a lot for your help, your time and your advices !
