### ISSUE TITLE
Issue when downloading: RegexNotFoundError: Unable to extract uploader id

### ISSUE THREAD

**Issue by SteppingHat** [ytdl-org/youtube-dl#32187]
When downloading any video, the following error occurs:

```
$ youtube-dl https://www.youtube.com/watch\?v\=Y54BAsqIdG4 -x --audio-format wav --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=Y54BAsqIdG4', u'-x', u'--audio-format', u'wav', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-144-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {}
[youtube] Y54BAsqIdG4: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

I have run `youtube-dl -U` and the error persists.
```
$ youtube-dl -U
youtube-dl is up-to-date (2021.12.17)
```

This happens with or without the flags I used (`-x`, or `--audio-format`) or when any other video is provided.
This occurs on Ubuntu Server 23.04 (Bullseye)

**Comment by dirkf** [comment]
Really? What a surprise! #30839 !

**Comment by SteppingHat** [comment]
Sorry, I just followed the link that the error provided.
May I suggest setting up a issue template? If there's no template, and a link directing me to do something, then I suspect others may do the same.

**Comment by SteppingHat** [comment]
Sorry, I just followed the link the error provided, and GitHub stripped the template away. Please don't get upset.

**Comment by dirkf** [comment]
That's fine, but the bold caps text saying "READ THIS BEFORE OPENING A NEW ISSUE! THIS MEANS YOU!" wasn't stripped, was it? The GH template bug is the first point covered there, and your issue is linked from the list of significant "known issues" at the end.

**Comment by SteppingHat** [comment]
I'm sorry, I simply didn't see it. I was unaware of the template bug and expected to see a template with instructions.
Thank you for linking the issue.
