### ISSUE TITLE
FFPROBE detected codec type is set to `video` instead of `audio`

### ISSUE THREAD

**Issue by HGStyle** [ytdl-org/youtube-dl#32183]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

(i have modified a little the ffmpeg.py file so i can have more infos about errors, i only added print instructions...
dont ask about the "if condition" thingy that is printed, i added it to know if the error occured in some if condition instead of a else condition...)

```
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python 3.10.8 (CPython 64bit) - Linux-5.19.0-1022-gcp-x86_64-with-glibc2.35 (OpenSSL 3.0.7 1 Nov 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[youtube] KPBuPBYo2wA: Downloading webpage
[debug] [youtube] Decrypted nsig ef-DjLsUTexhl2QcPA => lJiJSEaUs2mxbQ
[debug] [youtube] Decrypted nsig ZL75MoLR7bcLSQR9XZ => Fv3MYlYflDdblA
[youtube] KPBuPBYo2wA: Downloading thumbnail ...
[youtube] KPBuPBYo2wA: Writing thumbnail to: RUSH E & RUSH E 2.jpg
[debug] Invoking downloader on 'https://rr2---sn-qxoedne7.googlevideo.com/videoplayback?expire=1683993767&ei=R2BfZMfaJ4KakwafxKPoAQ&ip=34.127.7.96&id=o-ACikW-Y_4EHaC8eBBGSpre4zKUwqbbR9QMP0o4DvrwLg&itag=299&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=MX&mm=31%2C26&mn=sn-qxoedne7%2Csn-5goeenes&ms=au%2Conr&mv=u&mvi=2&pl=21&vprv=1&svpuc=1&mime=video%2Fmp4&ns=3mr18dqAZaw6bPjMnAEi5KQN&gir=yes&clen=181392495&dur=301.249&lmt=1669483448385141&mt=1683971254&fvip=4&keepalive=yes&fexp=24007246&c=WEB&txp=5535434&n=lJiJSEaUs2mxbQ&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgdNJhbUc-fCLM4KnppZrw7XqllTFnZ6GrXohd7cjWMlYCIHb8PYkOHoHq7gc08lg9QVCO8anThqZ4nt_PVTCF-8ZT&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRAIgH1i4g0NNTb9wCOIXn8QyEcFwtcUNxKPbErrvnoaQ6wUCIGJnFdKH9OD4XYZ7j0_p1X7veiQC478y7x7Un2bE2rEZ'
[download] RUSH E & RUSH E 2.mp4 has already been downloaded
[download] 100% of 172.99MiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:RUSH E & RUSH E 2.mp4'
if condition
[STREAM]   [{[explanation: this is the output of ffprobe that youtubedl got, added by myself]}]
index=0
codec_name=h264
audio_codec set to h264       [{[explanation: when the audio codec is set to a new value it prints a message like this with the new value, added by myself]}]
codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
profile=High
codec_type=video    [{[here is the problem: the codec_type is set to video instead of audio, so the loop is stuck forever and never returns anything, so it returns None and raises an error]}]
codec_tag_string=avc1
codec_tag=0x31637661
width=1920
height=1080
coded_width=1920
coded_height=1080
closed_captions=0
has_b_frames=1
sample_aspect_ratio=1:1
display_aspect_ratio=16:9
pix_fmt=yuv420p
level=42
color_range=tv
color_space=bt709
color_transfer=bt709
color_primaries=bt709
chroma_location=left
field_order=progressive
refs=1
is_avc=true
nal_length_size=4
id=N/A
r_frame_rate=60/1
avg_frame_rate=60/1
time_base=1/15360
start_pts=0
start_time=0.000000
duration_ts=4627200
duration=301.250000
bit_rate=15401
max_bit_rate=N/A
bits_per_raw_sample=8
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
TAG:creation_time=2022-11-26T17:06:41.000000Z
TAG:language=und
TAG:handler_name=ISO Media file produced by Google Inc.
TAG:vendor_id=[0][0][0][0]
[/STREAM]

what   [{[uhh dont ask about that this was to test if the function exits with the final return None line that is impossible to happen but it happened]}]
ERROR: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "/home/runner/downloader/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2161, in post_process
    files_to_delete, info = pp.run(info)
  File "/home/runner/downloader/venv/lib/python3.10/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 283, in run
    raise PostProcessingError('WARNING: unable to obtain file audio codec with ffprobe')  [{[this is ran when the function get_audio_codec returns None]}]
youtube_dl.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe

Traceback (most recent call last):
  File "/home/runner/downloader/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2161, in post_process
    files_to_delete, info = pp.run(info)
  File "/home/runner/downloader/venv/lib/python3.10/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 283, in run
    raise PostProcessingError('WARNING: unable to obtain file audio codec with ffprobe')
youtube_dl.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 69, in <module>
    download_video('https://www.youtube.com/watch?v=KPBuPBYo2wA&pp=ygURcnVzaCBlICYgcnVzaCBlIDI%3D')
  File "main.py", line 66, in download_video
    ytdl.download([link])
  File "/home/runner/downloader/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2087, in download
    res = self.extract_info(
  File "/home/runner/downloader/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 817, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/home/runner/downloader/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 824, in wrapper
    return func(self, *args, **kwargs)
  File "/home/runner/downloader/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 856, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/runner/downloader/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 890, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/runner/downloader/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 1700, in process_video_result
    self.process_info(new_info)
  File "/home/runner/downloader/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2066, in process_info
    self.post_process(filename, info_dict)
  File "/home/runner/downloader/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2163, in post_process
    self.report_error(e.msg)
  File "/home/runner/downloader/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 637, in report_error
    self.trouble(error_message, tb)
  File "/home/runner/downloader/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 607, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: WARNING: unable to obtain file audio codec with ffprobe
```

## Description

In the programm output I added some comments that are writen like this: [{[this is a comment]}]
Can anyone help me how to fix this ? Its been an hour I'm working on this error.
Thanks in advance !

**Comment by HGStyle** [comment]
Here is the modified function `get_audio_codec` to get more infos:
```python
def get_audio_codec(self, path):
        if not self.probe_available and not self.available:
            raise PostProcessingError('ffprobe/avprobe and ffmpeg/avconv not found. Please install one.')
        try:
            if self.probe_available:
                cmd = [
                    encodeFilename(self.probe_executable, True),
                    encodeArgument('-show_streams')]
            else:
                cmd = [
                    encodeFilename(self.executable, True),
                    encodeArgument('-i')]
            cmd.append(encodeFilename(self._ffmpeg_filename_argument(path), True))
            if self._downloader.params.get('verbose', False):
                self._downloader.to_screen(
                    '[debug] %s command line: %s' % (self.basename, shell_quote(cmd)))
            handle = subprocess.Popen(
                cmd, stderr=subprocess.PIPE,
                stdout=subprocess.PIPE, stdin=subprocess.PIPE)
            stdout_data, stderr_data = process_communicate_or_kill(handle)
            expected_ret = 0 if self.probe_available else 1
            if handle.wait() != expected_ret:
                return None
        except (IOError, OSError):
            return None
        output = (stdout_data if self.probe_available else stderr_data).decode('ascii', 'ignore')
        if self.probe_available:
            print('if condition')
            audio_codec = None
            for line in output.split('\n'):
                print(line)
                if line.startswith('codec_name='):
                    audio_codec = line.split('=')[1].strip()  # set new audio_codec
                    print('audio_codec set to', audio_codec)
                elif line.strip() == 'codec_type=audio' and audio_codec is not None:  # here is the problem: the video codec type is `codec_type=video` instead of `codec_type=audio` ...
                    print('returning audio codec:', audio_codec)
                    return audio_codec
        else:
            # Stream #FILE_INDEX:STREAM_INDEX[STREAM_ID](LANGUAGE): CODEC_TYPE: CODEC_NAME
            mobj = re.search(
                r'Stream\s*#\d+:\d+(?:\[0x[0-9a-f]+\])?(?:\([a-z]{3}\))?:\s*Audio:\s*([0-9a-z]+)',
                output)
            if mobj:
                return mobj.group(1)
        print('what')
        return None   # this is normally impossible (as far as i know) but it happened
```

**Comment by HGStyle** [comment]
So what should I do ?

**Comment by HGStyle** [comment]
Here is the options:
```python
{
        'format': 'bestvideo/best',
        'outtmpl': '%(title)s.%(ext)s',
        'postprocessors': [
            {
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'mp4'
            }, {
                'key': 'EmbedThumbnail'
            }, {
                'key': 'FFmpegMetadata'
            }
        ],
        'prefer_ffmpeg': True,
        'writethumbnail': True,
        'quiet': False,
        'verbose': True
    }
```

**Comment by HGStyle** [comment]
Wait I think Im just dumb about one thing...

**Comment by HGStyle** [comment]
Ok no Im just dumb sorry...
