### ISSUE TITLE
youtube, instant 429/http from different IPs

### ISSUE THREAD

**Issue by lizenko** [ytdl-org/youtube-dl#32182]
Subj, Ubuntu 20.04 LTS
at least from 3 addresses got the following or similar:

```
 youtube-dl -F --verbose --force-ipv4 --rm-cache-dir -x https://www.youtube.com/watch?v=YoTdzJFuV4I
[debug] System config: []
[debug] User config: ['-x', '--audio-format', 'mp3', '--audio-quality', '0', '--add-metadata']
[debug] Custom config: []
[debug] Command-line args: ['-F', '--verbose', '--force-ipv4', '--rm-cache-dir', '-x', 'https://www.youtube.com/watch?v=YoTdzJFuV4I']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-148-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Proxy map: {}
Removing cache dir /home/omega/.cache/youtube-dl ..
[youtube] YoTdzJFuV4I: Downloading webpage
[youtube] YoTdzJFuV4I: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 429: Too Many Requests
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
```
youtube-dl --version
2021.12.17
```

**Comment by dirkf** [comment]
Yes, but that's not your main problem. Do **read #30839 as asked** where issues for **both** your `WARNING` and your `ERROR` are linked.
