### ISSUE TITLE
SBS.COM.AU giving HTTP error 403: Forbidden

### ISSUE THREAD

**Issue by Spin35** [ytdl-org/youtube-dl#32192]
## Checklist

- [ X] I'm reporting a broken site support
- [X ] I've verified that I'm running youtube-dl version **2021.12.17**
- [X ] I've checked that all provided URLs are alive and playable in a browser 
- * Edge OK, Chrome Incognito OK, error with normal Chrome
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[SBS] 2164870723719: Downloading JSON metadata
[ThePlatform] W6_zRgjU4xOq: Downloading SMIL data
[ThePlatform] W6_zRgjU4xOq: Downloading MPD manifest
.
.
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'D:\\J-P\\Videos\\Processed Recordings\\rogue heroes s01e01.mp4', '-f', 'mp4', '--restrict-filenames', '--ignore-errors', '--continue', '--retries', '10', '--skip-unavailable-fragments', '--fragment-retries', '10', '--no-overwrites', '--verbose', 'https://www.sbs.com.au/ondemand/watch/2164870723719']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-81592-g2793ebd, ffprobe N-81516-gbe07c25
[debug] Proxy map: {}
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\theplatform.py", line 309, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Downloading from SBS On Demand seems to be broken.  I think they have made a change to the site recently as I needed to login when using the Android viewer app on my Nvidia Shield which normally keeps you logged in, and similarly on my PC.

I tried to download an episode of a show.  The link to the show plays using MS-Edge browser and Incognito Chrome, but it won't play in a normal chrome browser session.  The error message that pops up on the viewing area is:
_Video Playback Error
Sorry, we've encountered an error playing this video.  If you have an ad blocker turned on, try turning it off or whitelisting our website before trying again.  This may prevent you from loading videos._

I tried to download a program that I had previously downloaded successfully a couple of weeks ago and it gave the same error 403 as above.
I tried using the -u and -p options to pass username and password to the site but it gave the same error.

**Comment by Spin35** [comment]
I've tried using the latest patch version - 2023.05.15.40298, but I got the same error.

**Comment by dirkf** [comment]
Duplicate of #31841.

Please test the PR linked from there and comment in the PR.

The PR isn't included in the unofficial nightly builds.
