### ISSUE TITLE
Youku server reported error -6004: 客户端无权播放

### ISSUE THREAD

**Issue by dpoettler** [ytdl-org/youtube-dl#32195]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-v', 'https://v.youku.com/v_show/id_XNTk1MjQxNjQzMg==.html?']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python 3.11.3 (CPython 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1t  7 Feb 2023, -)
[debug] exe versions: none
[debug] Proxy map: {}
[youku] XNTk1MjQxNjQzMg: Retrieving cna info
[youku] XNTk1MjQxNjQzMg: Downloading JSON metadata
ERROR: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\david\Downloads\youtube-dl-master\youtube_dl\YoutubeDL.py", line 824, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\Downloads\youtube-dl-master\youtube_dl\YoutubeDL.py", line 845, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\david\Downloads\youtube-dl-master\youtube_dl\extractor\common.py", line 535, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\Downloads\youtube-dl-master\youtube_dl\extractor\youku.py", line 189, in _real_extract
    raise ExtractorError(msg)
youtube_dl.utils.ExtractorError: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

After fixing a bug with the ccode i got this error and now i have no idea what to do.

**Comment by dirkf** [comment]
>...a bug with the ccode ...

Please explain.

Does the URL actually end in `?`?

My testing with yt-dl gives -6001, while (sometimes at least) yt-dl appears to work.

**Comment by dpoettler** [comment]
> Does the URL actually end in `?`?
The URL works with or without '?'.  ytdl works wizh neighter. Before i got a -6001 ccode error. I fixed it by searching the new ccode in chrome dev tools. Chnaged it and i got to this new error

**Comment by dirkf** [comment]
You mean #32194? That matches what I reported above.

I guess the value you found needs other parameters to have corresponding values, different from those in the extractor. Try the value `0524` from yt-dlp instead, as above.
