### ISSUE TITLE
[weibo]no matches found

### ISSUE THREAD

**Issue by sunddytwo** [ytdl-org/youtube-dl#32220]
cmdline>>  youtube-dl -v https://weibo.com/tv/show/1042211:4903603312459904?from=old_pc_videoshow

output message>>zsh: no matches found: https://weibo.com/tv/show/1042211:4903603312459904?from=old_pc_videoshow

anyone help

**Comment by dirkf** [comment]
1. #30839
2. **Quote the URL**: `?` is a special character in_zsh_.

**Comment by WGroleau** [comment]
I'm getting the same message on https://www.youtube.com/watch?v=RYYQnUFgHsQ

```
Is it the same thing?  youtube-dl --verbose exits after the message with no further output.  Using https://youtu.be/RYYQnUFgHsQ gets: WGroleau@MBP TEMP % youtube-dl  --keep-fragments --verbose https://youtu.be/RYYQnUFgHsQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--keep-fragments', '--verbose', 'https://youtu.be/RYYQnUFgHsQ']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.13 (CPython) - macOS-13.5.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[youtube] RYYQnUFgHsQ: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  **https://yt-dl.org/update**  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
See also issue #32536

**Comment by dirkf** [comment]
No, this issue, which OP abandoned after failing to provide the requested information, would have been about Weibo, not YT.

**Comment by Vangelis66** [comment]
>4. Even after adapting the extractor's URL pattern, the extractor fails to find any video (**stuck on login page**)
>5. The page appears to be a **JS app**, so the extractor's tactics won't work: the **webpage traffic would have to be analysed** to create a new extractor.

I just tried the **OP**'s URI (minus the query, seems unnecessary 😉 ) in my **browser**: 

https://weibo.com/tv/show/1042211:4903603312459904

After a successful GET request to the typed URI, **several cycles** of **URL redirections** took place, in what I can best describe as a **client (browser) test and sanctioning procedure**; the GET requests included 
```
https://passport.weibo.com/visitor/visitor
https://passport.weibo.com/js/visitor/mini_original.js
https://weibo.com/login.php
```
, a POST request to 
```
https://passport.weibo.com/visitor/genvisitor
```
followed by several additional GET requests to 
```
https://weibo.com/login.php
https://passport.weibo.com/visitor/visitor
https://passport.weibo.com/js/visitor/mini_original.js
https://login.sina.com.cn/sso/prelogin.php
```
The redirections ultimately stopped and the URL address in my browser settled to: 

https://weibo.com/login.php

**However**, the browser tab did not display a **log-in page** per se, but what looked to me like the homepage of `weibo.com` (as you can imagine, I'm not fluent in Chinese 😜 ) ... 

What I then did was to `Copy and paste`, on that same tab, the original URI and, lo and behold, this time **there were no redirection cycles**, instead the program's page loaded normally and, soon after, **video playback started**, without me being in any way logged in to `weibo.com`; via **URL sniffing**, I got the **direct URI** to the HLS manifest: 
```
https://live.video.weibocdn.com/72e07815-f251-4493-b8a7-6ff69287c4c7_index.m3u8?media_id=4903603312459904&tp=:Dcg29nGjWos2g9yAdLY9NTL&us=0&ori=1&bf=2&ot=h&ps=3lckmu&uid=3ZoTIp&ab=&Expires=1693681789&ssig=L9Pp4urRNI&KID=unistore,video
```
![weibo](https://github.com/ytdl-org/youtube-dl/assets/9669492/5e1314cc-4e57-4904-a9a6-ae793370cced)

After some debugging, it appears what `yt-dl` probably needs is fetched via a POST request to: 
```
https://weibo.com/tv/api/component?page=%2Ftv%2Fshow%2F1042211%3A4903603312459904
```
; the request involves below POST _data_:
```
data{"Component_Play_Playinfo":{"oid":"1042211:4903603312459904"}}
```
while several **authentication/session** cookies (PC_TOKEN, login_sid_t, X-XSRF-TOKEN, WBPSESS e.a.), set previously, are also "involved" 😉 ; the response is JSON formatted and, when prettified, looks like this: 

<details>
<summary>weibo.com API JSON response</summary>

```json
{
  "msg": "succ",
  "data": {
    "Component_Play_Playinfo": {
      "reposts_count": "2",
      "oid": "1042211:4903603312459904",
      "mid": 4901954029879563,
      "ip_info_str": "发布于 广东",
      "attitude": false,
      "attitude_dynamic_adid": "",
      "nickname": "视频华夏",
      "video_orientation": "horizontal",
      "verified_type_ext": 0,
      "comment_manage_info": {
        "approval_comment_type": 0,
        "comment_permission_type": -1
      },
      "user_video_count": 2,
      "is_follow": false,
      "topics": null,
      "url_short": "http://t.cn/A6NrLUVx",
      "cooperate_video": 0,
      "is_contribution": 0,
      "verified_type": 0,
      "play_start_time": 0,
      "scrubber": [],
      "followers_count": "1.2万",
      "idstr": "1042211:4903603312459904",
      "cover_image": "//wx3.sinaimg.cn/large/007GoAJbly8hdzyqx9pbfj316c0nt438.jpg",
      "reward": {
        "welfare": 0,
        "mid": "4901954029879563",
        "reward_button_scheme": "https://reward.media.weibo.com/v1/public/h5/pay/reward?bid=1000303201&oid=4901954029879563&rewardsource=2&seller=7039396993&showmenu=0&topnavstyle=1&sign=13f4563d652b15f0f70c9484dd957469",
        "version_state": 1,
        "state": 1,
        "user": {
          "vclub_member": 0,
          "wbcolumn_ability": 0,
          "geo_enabled": true,
          "gender": "m",
          "avatar_large": "https://tvax1.sinaimg.cn/crop.0.0.500.500.180/007GoAJbly1gl87bhjoqpj30dw0dwjrs.jpg?KID=imgbed,tva&Expires=1693688990&ssig=g57AM2%2B%2FCs",
          "following": false,
          "follow_me": false,
          "followers_count_str": "1.2万",
          "url": "",
          "allow_all_act_msg": false,
          "statuses_count": 2521,
          "friends_count": 28,
          "chaohua_ability": 0,
          "credit_score": 80,
          "user_ability_extend": 1,
          "has_service_tel": false,
          "verified_contact_email": "",
          "video_play_count": 0,
          "verified_type_ext": 0,
          "verified_trade": "",
          "video_mark": 14,
          "newbrand_ability": 0,
          "live_ability": 1,
          "block_word": 0,
          "video_status_count": 810,
          "like_me": false,
          "verified_detail": {
            "custom": 0,
            "data": [
              {
                "key": 1,
                "desc": "佛山云分发科技有限公司 主播",
                "weight": 100
              }]
          },
          "verified_state": 0,
          "live_status": 1,
          "brand_ability": 0,
          "pc_new": 7,
          "mbtype": 0,
          "mbrank": 0,
          "light_ring": false,
          "vplus_ability": 0,
          "special_follow": false,
          "planet_video": 2,
          "domain": "",
          "screen_name": "视频华夏",
          "is_teenager_list": 0,
          "user_ability": 8650760,
          "brand_account": 0,
          "pagefriends_count": 0,
          "verified_reason_url": "",
          "verified_type": 0,
          "profile_image_url": "https://tvax1.sinaimg.cn/crop.0.0.500.500.50/007GoAJbly1gl87bhjoqpj30dw0dwjrs.jpg?KID=imgbed,tva&Expires=1693688990&ssig=DDnVQx9okJ",
          "ecommerce_ability": 0,
          "followers_count": 12454,
          "avatar_hd": "https://tvax1.sinaimg.cn/crop.0.0.500.500.1024/007GoAJbly1gl87bhjoqpj30dw0dwjrs.jpg?KID=imgbed,tva&Expires=1693688990&ssig=QUymtJohlv",
          "insecurity": {
            "sexual_content": false
          },
          "green_mode": 0,
          "idstr": "7039396993",
          "description": "颠覆式的数字传媒，重新定义直播！",
          "verified_reason_modified": "",
          "block_me": 0,
          "wenda_ability": 0,
          "is_guardian": 0,
          "location": "其他",
          "avatar_type": 0,
          "remark": "",
          "block_app": 0,
          "verified_contact_mobile": "",
          "bi_followers_count": 7,
          "created_at": "Wed Mar 20 15:07:26 +0800 2019",
          "profile_url": "u/7039396993",
          "online_status": 0,
          "favourites_count": 4,
          "id": 7039396993,
          "cover_image_phone": "https://ww1.sinaimg.cn/crop.0.0.640.640.640/549d0121tw1egm1kjly3jj20hs0hsq4f.jpg",
          "urisk": 8796093022208,
          "urank": 4,
          "hongbaofei": 0,
          "verified": true,
          "hardfan_ability": 0,
          "verified_source_url": "",
          "province": "100",
          "video_total_counter": {
            "play_cnt": 2302160
          },
          "verified_level": 3,
          "interaction_user": 0,
          "paycolumn_ability": 0,
          "story_read_state": -1,
          "gongyi_ability": 0,
          "unfollowing_recom_switch": 1,
          "vvip": 0,
          "svip": 0,
          "star": 0,
          "name": "视频华夏",
          "like": false,
          "lang": "zh-cn",
          "verified_reason": "佛山云分发科技有限公司 主播",
          "allow_all_comment": true,
          "city": "1000",
          "class": 1,
          "verified_source": "",
          "status_total_counter": {
            "comment_cnt": 6710,
            "like_cnt": 3838,
            "total_cnt": 12368,
            "comment_like_cnt": 208,
            "repost_cnt": 1612
          },
          "nft_ability": 0,
          "block": 0,
          "super_topic_not_syn_count": 0,
          "weihao": "",
          "mb_expire_time": 0,
          "ptype": 0,
          "verified_contact_name": "",
          "is_teenager": 0
        },
        "desc": "点赞是美意，赞赏是鼓励",
        "reward_params": "bid=1000303201&oid=4901954029879563&rewardsource=2&seller=7039396993&showmenu=0&topnavstyle=1&sign=13f4563d652b15f0f70c9484dd957469"
      },
      "id": "1042211:4903603312459904",
      "verified": true,
      "duration": "3:12:31",
      "allow_comment": false,
      "attitudes_count": 7,
      "real_date": 1684593597,
      "title": "戏聚高平·擂响中华——中国梆子大会|5.20",
      "uuid": "4903603318816796",
      "user": {
        "id": 7039396993
      },
      "urls": {
        "高清 720P": "//live.video.weibocdn.com/72e07815-f251-4493-b8a7-6ff69287c4c7_index.m3u8?media_id=4903603312459904&tp=:Dcg29nGjWos2g9yAdLY9NTL&us=0&ori=1&bf=2&ot=h&ps=3lckmu&uid=3ZoTIp&ab=&Expires=1693681789&ssig=L9Pp4urRNI&KID=unistore,video"
      },
      "text": "【5月20日】《戏聚高平·擂响中华》中国梆子大会，将于5月18日在喜镇苏庄拉开大幕，全国梆子戏名家新秀将相约表里山河，擂响中华之声。《戏聚高平·擂响中华》中国梆子大会开幕式全国梆子戏老中青名家名段演唱会，中国梆子大会闭幕式全国戏曲老中青名家名段演唱会将分别于5月18日和24日隆重举行。   <a target=\"_blank\" href=\"http://t.cn/A6NrLUVb\">http://t.cn/A6NrLUVb</a>",
      "live": true,
      "verified_reason": "佛山云分发科技有限公司 主播",
      "date": "3月前",
      "avatar": "//tvax1.sinaimg.cn/small/007GoAJbly1gl87bhjoqpj30dw0dwjrs.jpg?KID=imgbed,tva&Expires=1693688989&ssig=54%2FbLDALF8",
      "author": "视频华夏",
      "is_show_bulletin": 2,
      "play_start": 0,
      "duration_time": 11551,
      "media_id": 4903603312459904,
      "play_count": "268",
      "comments_count": "0"
    }
  },
  "code": "100000"
}
```

</details>

Hope I've helped 😄 ...
