### ISSUE TITLE
ERROR: Unable to extract uploader id;

### ISSUE THREAD

**Issue by ENG-AbdelrahmanGamal** [ytdl-org/youtube-dl#32226]
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by AbdElrahmanShaker446** [comment]
hello, i have the same issue , did u solve it ?

**Comment by ENG-AbdelrahmanGamal** [comment]
[sad]   abdelrahman Gamal sophi reacted to your message:
________________________________

**Comment by ENG-AbdelrahmanGamal** [comment]
No 😑😑 still have issues.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by FDNash** [comment]
Same here...
[youtube] aowSGxim_O8: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on ....

**Comment by revint** [comment]
Same issue, here is my verbose output.

```
youtube-dl.exe https://youtu.be/0000 --verbose                                                                                                                                                                    
[debug] System config: []                                                                                                                                                                                                             
[debug] User config: []                                                                                                                                                                                                               
[debug] Custom config: []                                                                                                                                                                                                             
[debug] Command-line args: ['https://youtu.be/0000', '--verbose']                                                                                                                                                              
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252                                                                                                                                                                     
[debug] youtube-dl version 2021.12.17                                                                                                                                                                                                 
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041                                                                                                                                                                        
[debug] exe versions: ffmpeg N-110715-g877ccaf776-20230522, ffprobe N-110715-
g877ccaf776-20230522                                                                                                                                     
[debug] Proxy map: {}                                                                                                                                                                                                                 
[youtube] 0000: Downloading webpage                                                                                                                                                                                            
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make 
sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-
dl with the --verbose flag and include its complete output.                                                                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                                                      
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper                                                                                                 
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info                                                                                          
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract                                                                                          
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract                                                                                  
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex                                                                                 
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . 
Make sure you are using the latest version; type  youtube-dl -U  to update. 
Be sure to call youtube-dl with the --verbose flag and include its complete output. 
```

**Comment by jm9151821** [comment]
same issue here 
debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=F_3p81GmHEg', '-verbose']
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: invalid rate limit specified

**Comment by mdavis-xyz** [comment]
> PASTE VERBOSE LOG HERE
> WRITE DESCRIPTION HERE

@ENG-AbdelrahmanGamal this is an open source project. You shouldn't expect people to put effort into solving your problem if you didn't put any effort into telling us your problem.

See the checklist in your post which is unchecked? Did you attempt to complete the checklist?

> [ ] I've searched the bugtracker for similar issues including closed ones

If you do that, you'll find #31530. Note that if you find existing issues, then you can hopefully find existing solutions faster than waiting for people to respond to you. Searching for existing issues is good for both problem solvers and problem havers.

>  I've verified that I'm running youtube-dl version 2021.12.17

Did you verify that? What version are you running?

Did you read the pinned post:

> [READ THIS BEFORE OPENING A NEW ISSUE! THIS MEANS YOU!](https://github.com/ytdl-org/youtube-dl/issues/30839)

Or [contributing.md](https://github.com/ytdl-org/youtube-dl/blob/d1c6c5c4d618fa950813c0c71aede34a5ac851e9/CONTRIBUTING.md)?
