### ISSUE TITLE
Gothenburg Symphony Orchestra videos (gso.se)

### ISSUE THREAD

**Issue by pstrg** [ytdl-org/youtube-dl#32234]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

https://www.gso.se/en/gsoplay/video/stravinsky-psalmsymfoni/
(Any other video will also do).

## Description

No credentials required.

WRITE DESCRIPTION HERE

c:\Progs\youtube-dl>youtube-dl --verbose https://www.gso.se/en/gsoplay/video/stravinsky-psalmsymfoni/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.gso.se/en/gsoplay/video/stravinsky-psalmsymfoni/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2.3
[debug] Proxy map: {}
[generic] stravinsky-psalmsymfoni: Requesting header
WARNING: Falling back on generic information extractor.
[generic] stravinsky-psalmsymfoni: Downloading webpage
[generic] stravinsky-psalmsymfoni: Extracting information
[download] Downloading playlist: Stravinsky: Symphony of Psalms
[generic] playlist Stravinsky: Symphony of Psalms: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[vimeo] 823047843: Downloading webpage
ERROR: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\vimeo.py", line 652, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
The video on the site is hosted on Vimeo.

The extraction from Vimeo fails because of a known issue fixed in the master code, as listed in #30839. Follow one of the suggestions in #31530 to update your yt-dl.
```console
$ python -m youtube_dl -v -F 'https://www.gso.se/en/gsoplay/video/stravinsky-psalmsymfoni/'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.gso.se/en/gsoplay/video/stravinsky-psalmsymfoni/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 48140135d
[debug] Python 2.7.18 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial - OpenSSL 1.1.1t  7 Feb 2023 - glibc 2.15
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[generic] stravinsky-psalmsymfoni: Requesting header
WARNING: Falling back on generic information extractor.
[generic] stravinsky-psalmsymfoni: Downloading webpage
[generic] stravinsky-psalmsymfoni: Extracting information
[download] Downloading playlist: Stravinsky: Symphony of Psalms
[generic] playlist Stravinsky: Symphony of Psalms: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[vimeo] 823047843: Downloading webpage
[vimeo] 823047843: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 823047843: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 823047843: Downloading fastly_skyfire m3u8 information
[vimeo] 823047843: Downloading fastly_skyfire m3u8 information
[vimeo] 823047843: Downloading akfire_interconnect_quic MPD information
[vimeo] 823047843: Downloading akfire_interconnect_quic MPD information
[vimeo] 823047843: Downloading fastly_skyfire MPD information
[vimeo] 823047843: Downloading fastly_skyfire MPD information
[info] Available formats for 823047843:
format code                                        extension  resolution note
hls-akfire_interconnect_quic_sep-audio-high-audio  mp4        audio only 
hls-fastly_skyfire_sep-audio-high-audio            mp4        audio only 
dash-akfire_interconnect_quic_sep-audio-4f24f717   m4a        audio only DASH audio   70k , m4a_dash container, opus  (48000Hz)
dash-fastly_skyfire_sep-audio-4f24f717             m4a        audio only DASH audio   70k , m4a_dash container, opus  (48000Hz)
dash-akfire_interconnect_quic_sep-audio-6ef3c539   m4a        audio only DASH audio  102k , m4a_dash container, opus  (48000Hz)
dash-fastly_skyfire_sep-audio-6ef3c539             m4a        audio only DASH audio  102k , m4a_dash container, opus  (48000Hz)
dash-akfire_interconnect_quic_sep-audio-ca340e66   m4a        audio only DASH audio  194k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-fastly_skyfire_sep-audio-ca340e66             m4a        audio only DASH audio  194k , m4a_dash container, mp4a.40.2 (48000Hz)
hls-akfire_interconnect_quic-314                   mp4        426x240     314k , avc1.640015, 25.0fps, video only
hls-fastly_skyfire-314                             mp4        426x240     314k , avc1.640015, 25.0fps, video only
dash-akfire_interconnect_quic-video-5a4702fa       mp4        426x240    DASH video  346k , mp4_dash container, avc1.640015, 25fps, video only
dash-akfire_interconnect_quic_sep-video-5a4702fa   mp4        426x240    DASH video  346k , mp4_dash container, avc1.640015, 25fps, video only
dash-fastly_skyfire-video-5a4702fa                 mp4        426x240    DASH video  346k , mp4_dash container, avc1.640015, 25fps, video only
dash-fastly_skyfire_sep-video-5a4702fa             mp4        426x240    DASH video  346k , mp4_dash container, avc1.640015, 25fps, video only
hls-akfire_interconnect_quic_sep-508               mp4        426x240     508k , avc1.640015, 25.0fps, video only
hls-fastly_skyfire_sep-508                         mp4        426x240     508k , avc1.640015, 25.0fps, video only
hls-akfire_interconnect_quic-705                   mp4        640x360     705k , avc1.64001E, 25.0fps, video only
hls-fastly_skyfire-705                             mp4        640x360     705k , avc1.64001E, 25.0fps, video only
dash-akfire_interconnect_quic-video-2d72e3f3       mp4        640x360    DASH video  800k , mp4_dash container, avc1.64001E, 25fps, video only
dash-akfire_interconnect_quic_sep-video-2d72e3f3   mp4        640x360    DASH video  800k , mp4_dash container, avc1.64001E, 25fps, video only
dash-fastly_skyfire-video-2d72e3f3                 mp4        640x360    DASH video  800k , mp4_dash container, avc1.64001E, 25fps, video only
dash-fastly_skyfire_sep-video-2d72e3f3             mp4        640x360    DASH video  800k , mp4_dash container, avc1.64001E, 25fps, video only
hls-akfire_interconnect_quic_sep-899               mp4        640x360     899k , avc1.64001E, 25.0fps, video only
hls-fastly_skyfire_sep-899                         mp4        640x360     899k , avc1.64001E, 25.0fps, video only
hls-akfire_interconnect_quic-1479                  mp4        960x540    1479k , avc1.64001F, 25.0fps, video only
hls-fastly_skyfire-1479                            mp4        960x540    1479k , avc1.64001F, 25.0fps, video only
hls-akfire_interconnect_quic_sep-1673              mp4        960x540    1673k , avc1.64001F, 25.0fps, video only
hls-fastly_skyfire_sep-1673                        mp4        960x540    1673k , avc1.64001F, 25.0fps, video only
dash-akfire_interconnect_quic-video-9ba90e81       mp4        960x540    DASH video 1689k , mp4_dash container, avc1.64001F, 25fps, video only
dash-akfire_interconnect_quic_sep-video-9ba90e81   mp4        960x540    DASH video 1689k , mp4_dash container, avc1.64001F, 25fps, video only
dash-fastly_skyfire-video-9ba90e81                 mp4        960x540    DASH video 1689k , mp4_dash container, avc1.64001F, 25fps, video only
dash-fastly_skyfire_sep-video-9ba90e81             mp4        960x540    DASH video 1689k , mp4_dash container, avc1.64001F, 25fps, video only
hls-akfire_interconnect_quic-2544                  mp4        1280x720   2544k , avc1.640020, 25.0fps, video only
hls-fastly_skyfire-2544                            mp4        1280x720   2544k , avc1.640020, 25.0fps, video only
hls-akfire_interconnect_quic_sep-2738              mp4        1280x720   2738k , avc1.640020, 25.0fps, video only
hls-fastly_skyfire_sep-2738                        mp4        1280x720   2738k , avc1.640020, 25.0fps, video only
dash-akfire_interconnect_quic-video-a635df31       mp4        1280x720   DASH video 3034k , mp4_dash container, avc1.640020, 25fps, video only
dash-akfire_interconnect_quic_sep-video-a635df31   mp4        1280x720   DASH video 3034k , mp4_dash container, avc1.640020, 25fps, video only
dash-fastly_skyfire-video-a635df31                 mp4        1280x720   DASH video 3034k , mp4_dash container, avc1.640020, 25fps, video only
dash-fastly_skyfire_sep-video-a635df31             mp4        1280x720   DASH video 3034k , mp4_dash container, avc1.640020, 25fps, video only
hls-akfire_interconnect_quic-5318                  mp4        1920x1080  5318k , avc1.64002A, 25.0fps, video only
hls-fastly_skyfire-5318                            mp4        1920x1080  5318k , avc1.64002A, 25.0fps, video only
hls-akfire_interconnect_quic_sep-5512              mp4        1920x1080  5512k , avc1.64002A, 25.0fps, video only
hls-fastly_skyfire_sep-5512                        mp4        1920x1080  5512k , avc1.64002A, 25.0fps, video only
dash-akfire_interconnect_quic-video-7b0eff24       mp4        1920x1080  DASH video 5898k , mp4_dash container, avc1.64002A, 25fps, video only
dash-akfire_interconnect_quic_sep-video-7b0eff24   mp4        1920x1080  DASH video 5898k , mp4_dash container, avc1.64002A, 25fps, video only
dash-fastly_skyfire-video-7b0eff24                 mp4        1920x1080  DASH video 5898k , mp4_dash container, avc1.64002A, 25fps, video only
dash-fastly_skyfire_sep-video-7b0eff24             mp4        1920x1080  DASH video 5898k , mp4_dash container, avc1.64002A, 25fps, video only
hls-akfire_interconnect_quic-11696                 mp4        2560x1440  11696k , avc1.640033, 25.0fps, video only
hls-fastly_skyfire-11696                           mp4        2560x1440  11696k , avc1.640033, 25.0fps, video only
hls-akfire_interconnect_quic_sep-11890             mp4        2560x1440  11890k , avc1.640033, 25.0fps, video only
hls-fastly_skyfire_sep-11890                       mp4        2560x1440  11890k , avc1.640033, 25.0fps, video only
dash-akfire_interconnect_quic-video-8357845a       mp4        2560x1440  DASH video 14448k , mp4_dash container, avc1.640033, 25fps, video only
dash-akfire_interconnect_quic_sep-video-8357845a   mp4        2560x1440  DASH video 14448k , mp4_dash container, avc1.640033, 25fps, video only
dash-fastly_skyfire-video-8357845a                 mp4        2560x1440  DASH video 14448k , mp4_dash container, avc1.640033, 25fps, video only
dash-fastly_skyfire_sep-video-8357845a             mp4        2560x1440  DASH video 14448k , mp4_dash container, avc1.640033, 25fps, video only
hls-akfire_interconnect_quic-23753                 mp4        3840x2160  23753k , avc1.640034, 25.0fps, video only
hls-fastly_skyfire-23753                           mp4        3840x2160  23753k , avc1.640034, 25.0fps, video only
hls-akfire_interconnect_quic_sep-23947             mp4        3840x2160  23947k , avc1.640034, 25.0fps, video only
hls-fastly_skyfire_sep-23947                       mp4        3840x2160  23947k , avc1.640034, 25.0fps, video only
dash-akfire_interconnect_quic-video-a1c7e943       mp4        3840x2160  DASH video 26455k , mp4_dash container, avc1.640034, 25fps, video only
dash-akfire_interconnect_quic_sep-video-a1c7e943   mp4        3840x2160  DASH video 26455k , mp4_dash container, avc1.640034, 25fps, video only
dash-fastly_skyfire-video-a1c7e943                 mp4        3840x2160  DASH video 26455k , mp4_dash container, avc1.640034, 25fps, video only
dash-fastly_skyfire_sep-video-a1c7e943             mp4        3840x2160  DASH video 26455k , mp4_dash container, avc1.640034, 25fps, video only (best)
[download] Finished downloading playlist: Stravinsky: Symphony of Psalms
$
```
