### ISSUE TITLE
I have a bug with reading

### ISSUE THREAD

**Issue by moreartyondsc** [ytdl-org/youtube-dl#32231]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
023-05-24 06:58:48 INFO     discord.voice_client Connecting to voice...
2023-05-24 06:58:48 INFO     discord.voice_client Starting voice handshake... (connection attempt 1)
2023-05-24 06:58:48 INFO     discord.voice_client Voice handshake complete. Endpoint found frankfurt2157.discord.media
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.11 (CPython) - Linux-5.10.0-21-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0
[debug] Proxy map: {}
[youtube] dSy2DcATYUo: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/container/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/container/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/container/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/home/container/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

The bot manages to connect, but the reading does not work, the bot has the administrator permission, does anyone have a solution?

**Comment by xenon-a** [comment]
Yeah I'm getting the Same error.

**Comment by moreartyondsc** [comment]
I don't know, I can send my code if needed

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar bug reports including closed ones

Learn how by reading #30839 (**again**?).

>[x] I've read bugs section in FAQ

Apply this.

**Comment by moreartyondsc** [comment]
I have already searched but I did not find a similar case, would it be possible to refer me to a similar case?

**Comment by dirkf** [comment]
Read the pinned issue fully: the link is there.
