### ISSUE TITLE
Simple musical dont work

### ISSUE THREAD

**Issue by betonomochalka** [ytdl-org/youtube-dl#32241]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

When trying to !play https://www.youtube.com/watch**********
Have error in console
Whats wrong?

Code:
import discord
from discord.ext import commands
import youtube_dl

# Create a bot instance
bot = commands.Bot(command_prefix='!', intents=discord.Intents.all())

@bot.command()
async def play(ctx, url):
    voice_channel = ctx.author.voice.channel
    voice_client = await voice_channel.connect()

    ydl_opts = {
        'format': 'bestaudio/best',
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }],
        'extractor_args': {
            'extract_flat': 'in_playlist',
        },
    }

    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=False)
        url2 = info['formats'][0]['url']
        voice_client.play(discord.FFmpegPCMAudio(url2))

# Rest of the code

bot.run("MTExMjEwNTIzNjMwNDI1MzA5MA.Gg5zQq.1qiB1zSxyh0SOycxIvrzKb3JoslOB2x2e5kRcE")
Console Log:
2023-05-27 23:10:02 INFO     discord.client logging in using static token
2023-05-27 23:10:03 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: 389dffd97f334fc5400fc94a76487c26).
2023-05-27 23:10:09 INFO     discord.voice_client Connecting to voice...
2023-05-27 23:10:09 INFO     discord.voice_client Starting voice handshake... (connection attempt 1)
2023-05-27 23:10:09 INFO     discord.voice_client Voice handshake complete. Endpoint found bucharest2737.discord.media
[youtube] rgS_OOA12NA: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2023-05-27 23:10:10 ERROR    discord.ext.commands.bot Ignoring exception in command play
Traceback (most recent call last):
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beton\Desktop\bot_all_might\gpt_test\main.py", line 26, in play
    info = ydl.extract_info(url, download=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\ext\commands\core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2023-05-27 23:10:30 ERROR    discord.voice_client Disconnected from voice... Reconnecting in 0.42s.
Traceback (most recent call last):
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\voice_client.py", line 456, in poll_voice_ws
    await self.ws.poll_event()
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\gateway.py", line 1006, in poll_event
    raise ConnectionClosed(self.ws, shard_id=None, code=self._close_code)
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 4006
2023-05-27 23:10:30 INFO     discord.voice_client The voice handshake is being terminated for Channel ID 1111906493915222019 (Guild ID 1111906492619169825)
2023-05-27 23:10:30 INFO     discord.voice_client Connecting to voice...
2023-05-27 23:10:30 INFO     discord.voice_client Starting voice handshake... (connection attempt 2)
2023-05-27 23:10:31 INFO     discord.voice_client Voice handshake complete. Endpoint found bucharest2737.discord.media
2023-05-27 23:10:33 ERROR    discord.voice_client Disconnected from voice... Reconnecting in 1.94s.
Traceback (most recent call last):
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\voice_client.py", line 456, in poll_voice_ws
    await self.ws.poll_event()
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\gateway.py", line 1006, in poll_event
    raise ConnectionClosed(self.ws, shard_id=None, code=self._close_code)
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 4006
2023-05-27 23:10:35 INFO     discord.voice_client The voice handshake is being terminated for Channel ID 1111906493915222019 (Guild ID 1111906492619169825)
2023-05-27 23:10:35 INFO     discord.voice_client Connecting to voice...
2023-05-27 23:10:35 INFO     discord.voice_client Starting voice handshake... (connection attempt 3)
2023-05-27 23:10:35 INFO     discord.voice_client Voice handshake complete. Endpoint found bucharest2737.discord.media
2023-05-27 23:11:18 ERROR    discord.voice_client Disconnected from voice... Reconnecting in 5.51s.
Traceback (most recent call last):
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\voice_client.py", line 456, in poll_voice_ws
    await self.ws.poll_event()
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\gateway.py", line 1006, in poll_event
    raise ConnectionClosed(self.ws, shard_id=None, code=self._close_code)
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 4006
2023-05-27 23:11:24 INFO     discord.voice_client The voice handshake is being terminated for Channel ID 1111906493915222019 (Guild ID 1111906492619169825)
2023-05-27 23:11:24 INFO     discord.voice_client Connecting to voice...
2023-05-27 23:11:24 INFO     discord.voice_client Starting voice handshake... (connection attempt 4)
2023-05-27 23:11:24 INFO     discord.voice_client Voice handshake complete. Endpoint found bucharest2737.discord.media
2023-05-27 23:11:59 ERROR    discord.voice_client Disconnected from voice... Reconnecting in 4.51s.
Traceback (most recent call last):
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\voice_client.py", line 456, in poll_voice_ws
    await self.ws.poll_event()
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\gateway.py", line 1006, in poll_event
    raise ConnectionClosed(self.ws, shard_id=None, code=self._close_code)
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 4006
2023-05-27 23:12:04 INFO     discord.voice_client The voice handshake is being terminated for Channel ID 1111906493915222019 (Guild ID 1111906492619169825)
2023-05-27 23:12:04 INFO     discord.voice_client Connecting to voice...
2023-05-27 23:12:04 INFO     discord.voice_client Starting voice handshake... (connection attempt 5)
2023-05-27 23:12:04 INFO     discord.voice_client Voice handshake complete. Endpoint found bucharest2737.discord.media
2023-05-27 23:13:03 ERROR    discord.voice_client Disconnected from voice... Reconnecting in 20.85s.
Traceback (most recent call last):
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\voice_client.py", line 456, in poll_voice_ws
    await self.ws.poll_event()
  File "C:\Users\beton\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\gateway.py", line 1006, in poll_event
    raise ConnectionClosed(self.ws, shard_id=None, code=self._close_code)
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 4006
2023-05-27 23:13:24 INFO     discord.voice_client The voice handshake is being terminated for Channel ID 1111906493915222019 (Guild ID 1111906492619169825)
2023-05-27 23:13:24 INFO     discord.voice_client Connecting to voice...
2023-05-27 23:13:24 INFO     discord.voice_client Starting voice handshake... (connection attempt 6)
2023-05-27 23:13:24 INFO     discord.voice_client Voice handshake complete. Endpoint found bucharest2737.discord.media

**Comment by dirkf** [comment]
#30839 !
