### ISSUE TITLE
[v.2021.12.17 snap] Unable to extract uploader id

### ISSUE THREAD

**Issue by michaeltebo** [ytdl-org/youtube-dl#32250]
Here is the error from terminal.

```

user@lubuntu:~$ youtube-dl -v -f mp4 https://www.youtube.com/watch?v=OKi-1nk-Sck
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'mp4', 'https://www.youtube.com/watch?v=OKi-1nk-Sck']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.15.0-72-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] OKi-1nk-Sck: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

user@lubuntu:~$ youtube-dl --version
2021.12.17

```
The only edits were personal info.

Error thrown on each attempt.

**Comment by cperepelitsa** [comment]
Same here (example URL: `https://www.youtube.com/watch?v=025X_K8OySM`). Verbose output for me was identical, except for:
```
[debug] Python version 3.10.10 (CPython) - Linux-6.1.29-1-MANJARO-x86_64-with-glibc2.37
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0, rtmpdump 2.4
```
Is uploader ID strictly necessary to download a video if that information isn't being used in e.g. the output template?

**Comment by IAowSwels** [comment]
Same issue for me using debian 11 and installed yt-dl from official repo.

**Comment by mansj** [comment]
Same for me, Mac OS Ventura 13.3.1 and Python 3.10.11, installed via Homebrew.

**Comment by gnthibault** [comment]
Same issue here with version:
`youtube-dl is up-to-date (2021.12.17)
`

**Comment by nicolaasjan** [comment]
> Unable to extract uploader id

Already reported: #31530

Also read:
#30839
