### ISSUE TITLE
Cannot download series from tv.nrk.no

### ISSUE THREAD

**Issue by marcelpogorzelski** [ytdl-org/youtube-dl#32252]
## Checklist

- [ x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--yes-playlist', 'https://tv.nrk.no/serie/bernie/sesong/1']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.2 (CPython) - macOS-13.4-arm64-arm-64bit
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[debug] Using fake IP 84.208.218.89 (NO) as X-Forwarded-For.
[NRKTVSeason] bernie/1: Downloading season JSON
ERROR: bernie/1: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/mpo023/.pyenv/versions/youtube/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 906, in _parse_json
    return json.loads(json_string)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpo023/.pyenv/versions/3.11.2/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpo023/.pyenv/versions/3.11.2/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpo023/.pyenv/versions/3.11.2/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/mpo023/.pyenv/versions/youtube/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 906, in _parse_json
    return json.loads(json_string)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpo023/.pyenv/versions/3.11.2/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpo023/.pyenv/versions/3.11.2/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpo023/.pyenv/versions/3.11.2/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mpo023/.pyenv/versions/youtube/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpo023/.pyenv/versions/youtube/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/Users/mpo023/.pyenv/versions/youtube/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpo023/.pyenv/versions/youtube/lib/python3.11/site-packages/youtube_dl/extractor/nrk.py", line 604, in _real_extract
    data = self._call_api(
           ^^^^^^^^^^^^^^^
  File "/Users/mpo023/.pyenv/versions/youtube/lib/python3.11/site-packages/youtube_dl/extractor/nrk.py", line 60, in _call_api
    return self._download_json(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpo023/.pyenv/versions/youtube/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 895, in _download_json
    res = self._download_json_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpo023/.pyenv/versions/youtube/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 881, in _download_json_handle
    return self._parse_json(
           ^^^^^^^^^^^^^^^^^
  File "/Users/mpo023/.pyenv/versions/youtube/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 910, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: bernie/1: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I am trying to download series from tv.nrk.no. It seems that the extractor fails. I tested on two different macs.

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar bug reports including closed ones

Yet your problem is #31285, fixed in master.
