### ISSUE TITLE
youtube-dl --verbose

### ISSUE THREAD

**Issue by ap7zzz** [ytdl-org/youtube-dl#32272]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/jishaku/features/invocation.py", line 168, in jsk_debug
    await alt_ctx.command.invoke(alt_ctx)
  File "/home/user_203869495486316544/.local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user_203869495486316544/.local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
#30839 !
