### ISSUE TITLE
[YouTube] New player 8c7583ff breaks native jsinterp.py

### ISSUE THREAD

**Issue by Vangelis66** [ytdl-org/youtube-dl#32292]
## Checklist

- [x] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```console
yt-dl -vf 140-0 "byV5cdjspXs" --fixup never => 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', '.\\FFmpeg', '--external-downloader-args', '-v 8 -stats', '-vf', '140-0', 'byV5cdjspXs', '--fixup', 'never']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2023.06.08.40298 (single file build)
[debug] Python 3.4.4 (CPython x86 32bit) - Windows-Vista-6.0.6003-SP2 - OpenSSL1.0.2d 9 Jul 2015
[debug] exe versions: ffmpeg n6.1-dev-1149-N-111033-gf11515c, ffprobe n6.1-dev-1149-N-111033-gf11515c, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] byV5cdjspXs: Downloading webpage
[youtube] Confirming age
[youtube] byV5cdjspXs: Downloading API JSON
[youtube] byV5cdjspXs: Downloading player 8c7583ff
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled
 (Unhandled exception in decode; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
 Traceback (most recent call last):
  File "D:\a\youtube-dl\youtube-dl\youtube_dl\extractor\youtube.py", line 1674, in _n_descramble
youtube_dl.utils.ExtractorError: 
Unhandled exception in decode; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.)
[debug] Invoking downloader on 'https://rr2---sn-4vguioxu-n3bz.googlevideo.com/videoplayback?expire=1686291610&ei=OnCCZM-VJ4zJ1gKevYuIDQ&ip=<redacted>&id=o-ADQ0W8pDv3oefStG68y67zTjGmnnUHkgpj8ijQpfp-eu&itag=140&source=youtube&requiressl=yes&mh=XT&mm=31%2C29&mn=sn-4vguioxu-n3bz%2Csn-nv47znel&ms=au%2Crdu&mv=m&mvi=2&pl=22&initcwndbps=835000&vprv=1&svpuc=1&mime=audio%2Fmp4&ns=gvLiz7maHkcpvyXJzg-t-88N&gir=yes&clen=9079821&dur=560.994&lmt=1650706237448239&mt=1686269580&fvip=4&keepalive=yes&fexp=24007246%2C24363393&beids=24350018&c=TVHTML5_SIMPLY_EMBEDDED_PLAYER&txp=5432434&n=DCYoFlCUN53KtD_oBe&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKk2EtmJm4EZMhc0LH7PWqH9_Sjjv4cEeNNU5mq8_YYOAiEApRKNmY8hOPTmzh79MAupAbvjDnIYzGhQ6mhWDAlWFMo%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAP436cD-FVgJQr_R_5g7K6hU5D_Q_g0lHSlBcbWlGaXBAiEAk4qhmNFD46_MBEAnupU6xkJCfib7BTrRbFAqjJsFu5U%3D'
[dashsegments] Total fragments: 1
[download] Destination: Sex, Pleasure, Kink and BDSM _ Love Against The Odds _ Channel 4-byV5cdjspXs.m4a
[download]   2.6% of ~8.66MiB at 40.43KiB/s ETA 03:33
ERROR: Interrupted by user
```

## Description

A short while after **Jun 9th 2023 00:00 GMT**, **youtube** (Google 😡 ) have started serving their new **yt-player**, `8c7583ff` , selectively (for me) on **age-gated content** of the **Channel 4** (UK) yt channel: 
https://www..youtube.com/@Channel4Documentaries

Other videos (on that same channel, as well as on the **rest of youtube**, at this time at least 😉 ) seem to still be using previous **yt-player** `b128dda0`, which doesn't break the native JS interpreter; but I suppose this is CDN-propagation related, it's conceivable this new `8c7583ff` player will soon be the "norm" in all of youtube 😭 ...

NB: My Windows build, 
```
[debug] youtube-dl version 2023.06.08.40298 (single file build)
```
has been compiled from `master` HEAD (b8a86dc) ; I hope this latest breakage doesn't turn out to be "a hard nut to crack" 😜 ...

Thanks for your efforts, kind regards 😃 ...

**Comment by dirkf** [comment]
I'm getting player b128dda0 with your problem video, but as you suggest it may be propagating through CDNs.

**Comment by Vangelis66** [comment]
I'm attaching [8c7583ff.json](https://github.com/ytdl-org/youtube-dl/files/11700416/8c7583ff.json.txt), in the hope it helps in debugging this 😉 ...

**Comment by dirkf** [comment]
Well, it's reached the UK now.

The last expression being evaluated before the error is `new Date("1970-01-01T09:15:00.000+09:15")/1E3`. I'll dig further.

**Comment by bashonly** [comment]
Simple fix:
```diff
diff --git a/youtube_dl/jsinterp.py b/youtube_dl/jsinterp.py
index dc580943e..77551123d 100644
--- a/youtube_dl/jsinterp.py
+++ b/youtube_dl/jsinterp.py
@@ -82,7 +82,7 @@ def _js_arith_op(op):
 
 
 def _js_div(a, b):
-    if JS_Undefined in (a, b) or not (a and b):
+    if JS_Undefined in (a, b) or not (a or b):
         return _NaN
     return operator.truediv(a or 0, b) if b else float('inf')
 

```

**Comment by Vangelis66** [comment]
... Can confirm the fix by **bashonly** works as advertised 👍 : 

```console
yt-dl -vf 140-0 "byV5cdjspXs" --fixup never => 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', '.\\FFmpeg', '--external-downloader-args', '-v 8 -stats', '-vf', '140-0', 'byV5cdjspXs', '--fixup', 'never']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2023.06.11.0 (single file build)
[debug] Python 3.4.4 (CPython x86 32bit) - Windows-Vista-6.0.6003-SP2 - OpenSSL1.0.2d 9 Jul 2015
[debug] exe versions: ffmpeg n6.1-dev-1149-N-111033-gf11515c, ffprobe n6.1-dev-1149-N-111033-gf11515c, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] byV5cdjspXs: Downloading webpage
[youtube] Confirming age
[youtube] byV5cdjspXs: Downloading API JSON
[debug] [youtube] Decrypted nsig W4cqVwlYooslsAXNQC => 9I3x0u7t3sakpA
[debug] [youtube] Decrypted nsig Fqo_VnXKp8F6HtAkbh => XUAO48p7bNno1A
[debug] Invoking downloader on 'https://rr2---sn-4vguioxu-n3bz.googlevideo.com/videoplayback?itag=140&gir=yes&sig=AOq0QJ8wRgIhAM6D0ztDWY3PiW2zrd1VkgKVUEr7SBKFUSaYzF-p2EqxAiEAwOZxmhT5DO9hAenf1HxA69TuyLgoe3j33zd46mMagpw%3D&ns=r037iHOMZ-tFqATFNJVa7FcN&lsig=AG3C_xAwRQIhAOq7xtv0v2db6RneP3-WZHKKoHGPgujPW-ymJOg6rSrPAiA6yF2ccg3fFcW0YYt6LgbxKAs7YaaUEpSpPOyBxD_3jQ%3D%3D&pl=21&initcwndbps=911250&mh=XT&dur=560.994&n=9I3x0u7t3sakpA&mm=31%2C29&id=o-AMRSPtDeqsS6A0AwES1baLKKcCozMEgDC5y4vaO9iZXU&source=youtube&mv=m&ms=au%2Crdu&expire=1686468648&fexp=24007246%2C24363393&svpuc=1&mime=audio%2Fmp4&keepalive=yes&txp=5432434&mn=sn-4vguioxu-n3bz%2Csn-nv47lnsy&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&mt=1686446730&clen=9079821&requiressl=yes&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&ip=<redacted>&fvip=1&vprv=1&lmt=1650706237448239&ei=yCOFZIKzEZKN1gK_lIeIBg&mvi=2&c=TVHTML5_SIMPLY_EMBEDDED_PLAYER'
[dashsegments] Total fragments: 1
[download] Destination: Sex, Pleasure, Kink and BDSM _ Love Against The Odds _ Channel 4-byV5cdjspXs.m4a
[download] 100% of 8.66MiB in 00:03
```
Many thanks, indeed ❤️ ...

**Comment by dirkf** [comment]
In this case the `blame` subcommand of _git_ is well named. Thanks to G and bashonly for debugging my typo.

**Comment by pukkandan** [comment]
Next broken player: https://github.com/yt-dlp/yt-dlp/commit/cd810afe2ac5567c822b7424800fc470ef2d0045

**Comment by dirkf** [comment]
Thanks, not yet seen in UK:
```diff
--- a/youtube_dl/extractor/youtube.py
+++ b/youtube_dl/extractor/youtube.py
@@ -1628,8 +1628,9 @@ class YoutubeIE(YoutubeBaseInfoExtractor):
             if real_nfunc:
                 return real_nfunc
         return self._parse_json(self._search_regex(
-            r'var %s\s*=\s*(\[.+?\]);' % (re.escape(nfunc), ), jscode,
-            'Initial JS player n function name ({nfunc}[{idx}])'.format(**locals())), nfunc, transform_source=js_to_json)[int(idx)]
+            r'var %s\s*=\s*(\[.+?\])[;,]' % (re.escape(nfunc), ), jscode,
+            'Initial JS player n function name ({nfunc}[{idx}])'.format(**locals())),
+            nfunc, transform_source=js_to_json)[int(idx)]
 
     def _extract_n_function(self, video_id, player_url):
         player_id = self._extract_player_info(player_url)
```

**Comment by pukkandan** [comment]
Don't think it's location based. I got the player once and then same video changed to 6ed0d907, so it's likely just starting rollout.

**Comment by dirkf** [comment]
Sure, the roll-out will be by CDN which must be correlated with (IP) geography. The `uploader_id` change took several days to appear here.

**Comment by Vangelis66** [comment]
... New **yt-player** `b7910ca8` has just come to my neck of the woods 😜 : 
```console
yt-dl -vF "b5A8Zy6tgcg" => 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', '.\\FFmpeg', '--external-downloader-args', '-v 8 -stats', '-vF', 'b5A8Zy6tgcg']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2023.06.22.334 (single file build)
[debug] Python 3.4.4 (CPython x86 32bit) - Windows-Vista-6.0.6003-SP2 - OpenSSL 1.0.2d 9 Jul 2015
[debug] exe versions: ffmpeg n6.1-dev-1239-N-111123-g6f2cf88, ffprobe n6.1-dev-1239-N-111123-g6f2cf88, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] b5A8Zy6tgcg: Downloading webpage
[youtube] Confirming age
[youtube] b5A8Zy6tgcg: Downloading API JSON
[youtube] b5A8Zy6tgcg: Downloading player b7910ca8
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled
 (Unable to extract Initial JS player n function alias (Usa[0]); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  Traceback (most recent call last):
  File "youtube.py", line 1672, in _n_descramble
  File "youtube.py", line 1644, in _extract_n_function
  File "youtube.py", line 1629, in _extract_n_function_name
  File "common.py", line 1013, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function alias (Usa[0]); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.)
[info] Available formats for b5A8Zy6tgcg:
format code  extension  resolution note
249-0        webm       audio only tiny   50k , webm_dash container, opus  (48000Hz), 1.02MiB
249-1        webm       audio only tiny   50k , webm_dash container, opus  (48000Hz), 1.03MiB
250-0        webm       audio only tiny   63k , webm_dash container, opus  (48000Hz), 1.28MiB
250-1        webm       audio only tiny   63k , webm_dash container, opus  (48000Hz), 1.28MiB
251-0        webm       audio only tiny  113k , webm_dash container, opus  (48000Hz), 2.29MiB
251-1        webm       audio only tiny  113k , webm_dash container, opus  (48000Hz), 2.30MiB
140-0        m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2 (44100Hz), 2.62MiB
140-1        m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2 (44100Hz), 2.62MiB
278          webm       256x144    144p  105k , webm_dash container, vp9, 30fps, video only, 2.14MiB
160          mp4        256x144    144p  112k , mp4_dash container, avc1.4d400c, 30fps, video only, 2.28MiB
242          webm       426x240    240p  244k , webm_dash container, vp9, 30fps, video only, 4.94MiB
133          mp4        426x240    240p  250k , mp4_dash container, avc1.4d4015, 30fps, video only, 5.07MiB
243          webm       640x360    360p  460k , webm_dash container, vp9, 30fps, video only, 9.32MiB
134          mp4        640x360    360p  566k , mp4_dash container, avc1.4d401e, 30fps, video only, 11.45MiB
244          webm       854x480    480p  869k , webm_dash container, vp9, 30fps, video only, 17.58MiB
135          mp4        854x480    480p 1096k , mp4_dash container, avc1.4d401f, 30fps, video only, 22.17MiB
247          webm       1280x720   720p 1797k , webm_dash container, vp9, 30fps, video only, 36.34MiB
136          mp4        1280x720   720p 2225k , mp4_dash container, avc1.4d401f, 30fps, video only, 44.99MiB
248          webm       1920x1080  1080p 2913k , webm_dash container, vp9, 30fps, video only, 58.90MiB
137          mp4        1920x1080  1080p 4605k , mp4_dash container, avc1.640028, 30fps, video only, 93.10MiB
271          webm       2560x1440  1440p 8588k , webm_dash container, vp9, 30fps, video only, 173.60MiB
313          webm       3840x2160  2160p 17197k , webm_dash container, vp9, 30fps, video only, 347.63MiB
18           mp4        640x360    360p  694k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz)
22           mp4        1280x720   720p 2354k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
```
The `videoID=b5A8Zy6tgcg` corresponds to an **age-gated** clip, so, if you also take into account the first post (mine 😜 ) of this thread, 

> **youtube** (Google 😡 ) have started serving their new yt-player, `8c7583ff` , selectively (for me) on **age-gated** content 

one can conclude that **Google** are serving their "new" yt-players **first** on **age-gated** IDs...

FWIW, the "fix" from https://github.com/dirkf/youtube-dl/commit/9112e668a5ea6376017718db9ff13b369d53ad7a has been tested to just work: 

```console
yt-dl -vF "b5A8Zy6tgcg" => 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', '.\\FFmpeg', '--external-downloader-args', '-v 8 -stats', '-vF', 'b5A8Zy6tgcg']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2023.06.23.0 (single file build)
[debug] Python 3.4.4 (CPython x86 32bit) - Windows-Vista-6.0.6003-SP2 - OpenSSL 1.0.2d 9 Jul 2015
[debug] exe versions: ffmpeg n6.1-dev-1239-N-111123-g6f2cf88, ffprobe n6.1-dev-1239-N-111123-g6f2cf88, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] b5A8Zy6tgcg: Downloading webpage
[youtube] Confirming age
[youtube] b5A8Zy6tgcg: Downloading API JSON
[debug] [youtube] Decrypted nsig t5HZdvNqDUjHI6E => NxF8Fn9CpsnP-g
[debug] [youtube] Decrypted nsig d5_izeRWbEsyik1 => Ers8l0K8X8y0kg
[info] Available formats for b5A8Zy6tgcg:
format code  extension  resolution note
249-0        webm       audio only tiny   50k , webm_dash container, opus  (48000Hz), 1.02MiB
249-1        webm       audio only tiny   50k , webm_dash container, opus  (48000Hz), 1.03MiB
250-0        webm       audio only tiny   63k , webm_dash container, opus  (48000Hz), 1.28MiB
250-1        webm       audio only tiny   63k , webm_dash container, opus  (48000Hz), 1.28MiB
251-0        webm       audio only tiny  113k , webm_dash container, opus  (48000Hz), 2.29MiB
251-1        webm       audio only tiny  113k , webm_dash container, opus  (48000Hz), 2.30MiB
140-0        m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2 (44100Hz), 2.62MiB
140-1        m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2 (44100Hz), 2.62MiB
278          webm       256x144    144p  105k , webm_dash container, vp9, 30fps, video only, 2.14MiB
160          mp4        256x144    144p  112k , mp4_dash container, avc1.4d400c, 30fps, video only, 2.28MiB
242          webm       426x240    240p  244k , webm_dash container, vp9, 30fps, video only, 4.94MiB
133          mp4        426x240    240p  250k , mp4_dash container, avc1.4d4015, 30fps, video only, 5.07MiB
243          webm       640x360    360p  460k , webm_dash container, vp9, 30fps, video only, 9.32MiB
134          mp4        640x360    360p  566k , mp4_dash container, avc1.4d401e, 30fps, video only, 11.45MiB
244          webm       854x480    480p  869k , webm_dash container, vp9, 30fps, video only, 17.58MiB
135          mp4        854x480    480p 1096k , mp4_dash container, avc1.4d401f, 30fps, video only, 22.17MiB
247          webm       1280x720   720p 1797k , webm_dash container, vp9, 30fps, video only, 36.34MiB
136          mp4        1280x720   720p 2225k , mp4_dash container, avc1.4d401f, 30fps, video only, 44.99MiB
248          webm       1920x1080  1080p 2913k , webm_dash container, vp9, 30fps, video only, 58.90MiB
137          mp4        1920x1080  1080p 4605k , mp4_dash container, avc1.640028, 30fps, video only, 93.10MiB
271          webm       2560x1440  1440p 8588k , webm_dash container, vp9, 30fps, video only, 173.60MiB
313          webm       3840x2160  2160p 17197k , webm_dash container, vp9, 30fps, video only, 347.63MiB
18           mp4        640x360    360p  694k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz)
22           mp4        1280x720   720p 2354k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
```

**Comment by dirkf** [comment]
And now pushed to master.

**Comment by Vangelis66** [comment]
`<rant mode ON>`

> because the arses responsible for the `setup-python` GH action decided to spend time 
> breaking the action by removing Py2.7, instead of **fixing some real problem**.

... That's so typical of **Microsoft** during the last years 😡 ; they'd go the extra mile at no time just for the sake of exterminating everything "legacy" 😢 ... Currently using **GitHub** itself in a somewhat **broken state** since June 16th on my **UXP**-based browser, because MS pushed [CSS code with max()](https://developer.mozilla.org/en-US/docs/Web/CSS/max) on the **main** GH stylesheets, and this mix of **JS+CSS** isn't supported by the platform; @dirkf, you used to use **SeaMonkey**, does it render GH properly now?

`<rant mode OFF>`

**Comment by Vangelis66** [comment]
> And now **pushed** to `master`,

... Due to **4** (!) consecutive **failed** `Rebase on Upstream` workflow runs, 

![WFR](https://github.com/ytdl-org/youtube-dl/assets/9669492/0f723d43-31c2-4a84-bcf0-0536c541ae05)

the `yt-dl` [unofficial "daily" builds](https://github.com/ytdl-patched/youtube-dl/releases) (linked to in this tracker as one of the available _ways_ to update `yt-dl` itself) have been "frozen" for four days now on source code snapshot 07af479, which doesn't contain the "fix" for yt-player `b7910ca8` 😞 ; pinging @Lesmiscore for a manual "intervention"... Thanks in advance! 😄

**Comment by dirkf** [comment]
It needs a workflow token because of the arses mentioned above.

**Comment by pukkandan** [comment]
Lesmiscore's been inactive for a few weeks now. Don't count on a manual fix immediately. Perhaps @dirkf should fork it as https://github.com/ytdl-org/youtube-dl-nightly or something.

**Comment by pukkandan** [comment]
> (unless they're being pushed by a bot 😜 ...)

They are https://github.com/ytdl-patched/ytdl-patched/actions/workflows/generate-files-automatic.yml

**Comment by dirkf** [comment]
Try this: https://github.com/ytdl-org/ytdl-nightly/releases/tag/2023.07.03.19419

**Comment by dirkf** [comment]
>It needs a workflow token because of the arses mentioned above.

The issue in the original workflow was that `actions/checkout` needed to be passed a workflow-enabled token but wasn't being passed any explicit token

**Comment by MysticMerlin** [comment]
Again thanks for the dedication by peeps like dirkf, Vangellis66 & others for keeping youtube-dl working.
I hope I'm not out of order in asking how are things going with the 'Unable to extract params' error?
I'm sure that there would be loads of people that would like to know & not just me.
If & when there is a fix will running youtube-dl -U be the best way to update to the latest?
Thanks very much, Mystic.

**Comment by dirkf** [comment]
@MysticMerlin, see https://github.com/ytdl-org/youtube-dl/issues/32292#issuecomment-1617134680: https://github.com/ytdl-org/ytdl-nightly/releases/

Follow #32410 for news on that problem.
