### ISSUE TITLE
I think this is a bug help me!!

### ISSUE THREAD

**Issue by hanseungwan5676** [ytdl-org/youtube-dl#32307]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.2023-06-16 13:14:15 ERROR    discord.client Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\H1405\AppData\Roaming\Python\Python38\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "c:/Users/H1405/Desktop/안아줘요 PJ/안아줘요3.py", line 29, in on_message
    info = ydl.extract_info(f"ytsearch:{music_name}", download=False)
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 847, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 933, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 1067, in __process_playlist
    entry_result = self.__process_iterable_entry(entry, download, extra)
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 1076, in __process_iterable_entry
    return self.process_ie_result(
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 885, in process_ie_result
    return self.extract_info(ie_result['url'],
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Program Files\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag 
and include its complete output.

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
Help yourself by **reading and following** #30839 and by **completing the checklist** before (if necessary) creating a new issue.
