### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by RestSon** [ytdl-org/youtube-dl#32305]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'H:\\Converted Music\\%(playlist)s\\%(title)s.%(ext)s', '--add-metadata', '-x', '--audio-format', 'mp3', '--download-archive', 'archive.txt', '--ignore-errors', '--cookies', 'youtube.com_cookies.txt', 'https://www.youtube.com/playlist?list=PL64gVhBgjAmClD6T8wrw2nlhmwSO7l6Zn', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-107256-ga526f0cc3a-20220627, ffprobe N-107256-ga526f0cc3a-20220627
[debug] Proxy map: {}
[youtube:tab] PL64gVhBgjAmClD6T8wrw2nlhmwSO7l6Zn: Downloading webpage
[download] Downloading playlist: New Music (Move to Music)
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] playlist New Music (Move to Music): Downloading 295 videos
[download] Downloading video 1 of 295
[youtube] JClZ06vwU6Y: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[download] Downloading video 2 of 295
[youtube] Plspkxh1r7A: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[download] Downloading video 3 of 295
[youtube] XZ3OpiPciLU: Downloading webpage

ERROR: Interrupted by user
```

## Description

"ERROR: Unable to extract uploader id" is the issue I'm facing right now when trying to do a routine playlist download. Playlist is public, all videos are playable. Up to date with youtube-dl "youtube-dl is up-to-date (2021.12.17)". Redownloaded youtube-dl.exe from the yt-dl.org and then reran the update command for youtube-dl.exe to verify I definitely have the newest version.

Primary reason for still using ytdl over ytdlg is the archive function with all previous downloads being logged in an archive.txt. Am I able to just place the arguments "'-o', 'H:\\Converted Music\\%(playlist)s\\%(title)s.%(ext)s', '--add-metadata', '-x', '--audio-format', 'mp3', '--download-archive', 'archive.txt', '--ignore-errors', '--cookies', 'youtube.com_cookies.txt'" into the DLG > Options > Extra with no issues? Thanks

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar bug reports including closed ones

Learn how by reading #30839 (**again**?).

>[x] I've read bugs section in FAQ

Apply this.

**Comment by RestSon** [comment]
Apologies, I did go through those sections but obviously didn't delve deep enough. Updated via https://github.com/ytdl-patched/youtube-dl/releases, latest release installed and resolved my issue. Thanks for the quick response :)
