### ISSUE TITLE
youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id;

### ISSUE THREAD

**Issue by mominurr** [ytdl-org/youtube-dl#32313]
[youtube] hjeCJSGtyag: Downloading webpage
[youtube] hjeCJSGtyag: Downloading player 0c9b5d20
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Mominur Rahman\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper       
    return func(self, *args, **kwargs)
  File "C:\Users\Mominur Rahman\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Mominur Rahman\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Mominur Rahman\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "C:\Users\Mominur Rahman\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the 
latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\RI Rijan Vhai Project\WALKSCORE\python source code\test.py", line 16, in <module>
    ydl.download([video_url])
  File "C:\Users\Mominur Rahman\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "C:\Users\Mominur Rahman\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info       
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\Mominur Rahman\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\Mominur Rahman\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error       
    self.trouble(error_message, tb)
  File "C:\Users\Mominur Rahman\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

How to solve this problem. please give me solution.

**Comment by dirkf** [comment]
Solve it yourself by thoroughly reading and following #30839 as asked.
