### ISSUE TITLE
Error: Unable to extract uploader ID

### ISSUE THREAD

**Issue by MeMyself-tech** [ytdl-org/youtube-dl#32312]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm using the latest version but still can't download videos. It gives the error that I mentioned in the title. Tried with different videos. How can I fix this?

**Comment by Mochuleo** [comment]
Same here.

**Comment by shoorick** [comment]
I have seen the same error
```console
$ youtube-dl zbWTqY4aWy0 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['zbWTqY4aWy0', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-23-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] zbWTqY4aWy0: Downloading webpage
[youtube] zbWTqY4aWy0: Downloading m3u8 information
[youtube] zbWTqY4aWy0: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1776, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

If I specify URL https://www.youtube.com/watch?v=zbWTqY4aWy0 or https://www.youtube.com/live/zbWTqY4aWy0?feature=share as first parameter, I see the same. Video is available in Google Chrome.

Debian 11 "bullseye", youtube-dl is installed via `apt`.

I tried to uninstall that version, install new 2021.12.17 via `pip` as described at https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl and then run installed youtube-dl — without any success.

**Comment by dirkf** [comment]
You're reporting a bug, not asking a question, but you shouldn't be, because it's a known issue in #30839 and also supposedly

>[x] I've searched the bugtracker for similar questions including closed ones

Use the right template when reporting a bug.
