### ISSUE TITLE
YT-DL Cmd error

### ISSUE THREAD

**Issue by RetroClassic** [ytdl-org/youtube-dl#32325]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
C:\Users\(User)>youtube-dl.exe https://www.youtube.com/watch?v=5axVgHHDBvU
WARNING: parsing .netrc: Could not find .netrc: $HOME is not set
[youtube] 5axVgHHDBvU: Downloading webpage
[youtube] 5axVgHHDBvU: Downloading player 6ed0d907
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1361, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1277, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1344, in <lambda>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\jsinterp.py", line 258, in resf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\jsinterp.py", line 182, in interpret_expression
KeyError: 'QV'
 (caused by KeyError('QV',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output

## Description

WRITE DESCRIPTION HERE
 Yeah im running into an issue while I was trying to download a test video using a guide I tried to follow on YT. I ran the link in the cmd prompt but I got an error with key things noted as  "Could not find .netrc: $HOME is not set" and Key error qv. Did anyone else run into a issue like this? Maybe I downloaded the wrong thing?

**Comment by camopants** [comment]
Identical error message running from the shell on Ubuntu Linux:

raj@huey[pts/8 2023-06-19 17:30:19] PTP-CTF-202301[l]:~$ youtube-dl "https://www.youtube.com/watch?v=eo2gUQvM1RU"
[youtube] eo2gUQvM1RU: Downloading webpage
[youtube] eo2gUQvM1RU: Downloading player 6ed0d907
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1585, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1506, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1573, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 964, in resf
    ret, should_abort = self.interpret_statement(code.replace('\n', ' '), var_stack, allow_recursion - 1)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 403, in interpret_statement
    ret, should_return = self.interpret_statement(sub_stmt, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 855, in interpret_statement
    return eval_method(), should_return
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 847, in eval_method
    return obj[idx](argvals, allow_recursion=allow_recursion)
KeyError: u'QV'
 (caused by KeyError(u'QV',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
raj@huey[pts/8 2023-06-19 17:30:27] PTP-CTF-202301[l]:~$ youtube-dl --version
2021.12.17

Annotation doesn't show it, but this is the patched release of 2021.12.17
