### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xsmaxx** [ytdl-org/youtube-dl#32322]
(venv) PS D:\Repo\VSCode\jemb> youtube-dl -v  "https://www.youtube.com/watch?v=rK_d5g3pBb8" -j
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=rK_d5g3pBb8', '-j']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.12.0a4 (CPython) - Windows-11-10.0.22621-SP0
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1360, in _decrypt_signature
    func = self._extract_signature_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1277, in _extract_signature_function
    cache_res = res(test_string)
                ^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1344, in <lambda>
    return lambda s: initial_function([s])
                     ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\jsinterp.py", line 182, in interpret_expression
    return obj[member](argvals)
           ~~~^^^^^^^^
KeyError: 'QV'
 (caused by KeyError('QV')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1360, in _decrypt_signature
    func = self._extract_signature_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1277, in _extract_signature_function
    cache_res = res(test_string)
                ^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1344, in <lambda>
    return lambda s: initial_function([s])
                     ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\jsinterp.py", line 182, in interpret_expression
    return obj[member](argvals)
           ~~~^^^^^^^^
KeyError: 'QV'
Traceback (most recent call last):
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1360, in _decrypt_signature
    func = self._extract_signature_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1277, in _extract_signature_function
    cache_res = res(test_string)
                ^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1344, in <lambda>
    return lambda s: initial_function([s])
                     ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\jsinterp.py", line 182, in interpret_expression
    return obj[member](argvals)
           ~~~^^^^^^^^
KeyError: 'QV'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1641, in _real_extract
    signature = self._decrypt_signature(sc['s'][0], video_id, player_url)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1370, in _decrypt_signature
    raise ExtractorError(
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1360, in _decrypt_signature
    func = self._extract_signature_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1277, in _extract_signature_function
    cache_res = res(test_string)
                ^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1344, in <lambda>
    return lambda s: initial_function([s])
                     ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\VSCode\jemb\venv\Lib\site-packages\youtube_dl\jsinterp.py", line 182, in interpret_expression
    return obj[member](argvals)
           ~~~^^^^^^^^
KeyError: 'QV'
 (caused by KeyError('QV')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by nicolaasjan** [comment]
> KeyError: 'QV'

Duplicate of #32314.

**Comment by dirkf** [comment]
#30839 !
