### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by nickstaves** [ytdl-org/youtube-dl#32344]
Hi!

Downloader not working with following video:
https://www.youtube.com/watch?v=YCCfVbmEVHw

Here is the command line and return:

D:\Media\youtube-dl>youtube-dl.exe -F --verbose https://www.youtube.com/watch?v=YCCfVbmEVHw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '--verbose', 'https://www.youtube.com/watch?v=YCCfVbmEVHw']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2022-08-08-git-56973eb687-essentials_build-www.gyan.dev, ffprobe 2022-08-08-git-56973eb687-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] YCCfVbmEVHw: Downloading webpage
WARNING: Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>
[youtube] YCCfVbmEVHw: Downloading API JSON
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thanks!

**Comment by facundoq** [comment]
Same with https://www.youtube.com/watch?v=8j9WFCltESU

**Comment by dirkf** [comment]
#30839 !
