### ISSUE TITLE
Unable to decode n-parameter: download likely to be throttled

### ISSUE THREAD

**Issue by vvvm23** [ytdl-org/youtube-dl#32346]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
(venv) ➜  zh-yt git:(main) ✗ youtube-dl --verbose -s "https://youtu.be/eN76oJoNE1k"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-s', 'https://youtu.be/eN76oJoNE1k']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: e3b447b
[debug] Python 3.11.3 (CPython 64bit) - Linux-6.3.9-arch1-1-x86_64-with-glibc2.37 (OpenSSL 3.1.1 30 May 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[youtube] eN76oJoNE1k: Downloading webpage
[youtube] eN76oJoNE1k: Downloading player b7910ca8
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unable to extract Initial JS player n function alias (Usa[0]); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/home/alex/work/zh-yt/venv/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1670, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/work/zh-yt/venv/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1642, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/work/zh-yt/venv/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1625, in _extract_n_function_name
    real_nfunc = self._search_regex(
                 ^^^^^^^^^^^^^^^^^^^
  File "/home/alex/work/zh-yt/venv/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1013, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function alias (Usa[0]); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
[debug] Default format spec: bestvideo+bestaudio/best
```

## Description

Getting this error message installing from `master` today. This occurs without the `-s` flag, just using here for debug purposes. Like the message says, the download will be throttled.

Thanks~

**Comment by vvvm23** [comment]
By the way, I did check closed issues and saw this same issue had occurred recently, but supposedly it has been fixed on `master`, which isn't the case here. Just something to emphasize..

**Comment by dirkf** [comment]
Please refresh your version to commit 9112e66 or later to get the fix.
```console
$ python -m youtube_dl -v -F  HG9kCMU24x8
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'HG9kCMU24x8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 58fc5bde4
[debug] Python 2.7.18 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial - OpenSSL 1.1.1t  7 Feb 2023 - glibc 2.15
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] HG9kCMU24x8: Downloading webpage
[youtube] HG9kCMU24x8: Downloading player b7910ca8
[debug] [youtube] Decrypted nsig AxT9rrznZbDk4B3 => w_CGHX-e5hj9lQ
[debug] [youtube] Decrypted nsig gCqFS-lmLWRjUIE => oopF5idGnyCQzQ
[info] Available formats for HG9kCMU24x8:
format code  extension  resolution note
251          webm       audio only tiny   85k , webm_dash container, opus  (48000Hz), 299.83MiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2 (44100Hz), 456.37MiB
160          mp4        256x144    144p   53k , mp4_dash container, avc1.4d400c, 30fps, video only, 187.83MiB
243          webm       640x360    360p  185k , webm_dash container, vp9, 30fps, video only, 653.54MiB
134          mp4        640x360    360p  220k , mp4_dash container, avc1.4d401e, 30fps, video only, 777.63MiB
136          mp4        1280x720   720p  781k , mp4_dash container, avc1.64001f, 30fps, video only, 2.69GiB
18           mp4        640x360    360p  315k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz), 1.08GiB
22           mp4        1280x720   720p  910k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
$ 
```

**Comment by vvvm23** [comment]
Apologies, I ran `pip install git+https://github.com/ytdl-org/youtube-dl.git` and it didn't seem to use the most recent commit. Even doing `pip install git+https://github.com/ytdl-org/youtube-dl.git@fa7f0effbe4e14fcf70e1dc4496371c9862b64b9` didn't work too.

However, uninstalling then reinstalling did work. Thanks for the quick response and sorry for the time waste :)

**Comment by danx0r** [comment]
I've been having this problem too and I just want to point out that because the version number is not bumped with these fixes, PIP will not automatically upgrade. You need to uninstall and reinstall with pip.

Kudos for the project!!

**Comment by dirkf** [comment]
`--force-reinstall` may have been  necessary, as (now) mentioned in the interim upgrade suggestions.

We should probably revisit #32039.
