### ISSUE TITLE
youtube-dl reports some kind of python error

### ISSUE THREAD

**Issue by fizwack729** [ytdl-org/youtube-dl#32353]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

[youtube] leFcE7Nke-Q: Downloading webpage
[youtube] leFcE7Nke-Q: Downloading player b7910ca8
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unable to extract Initial JS player n function alias (Usa[0]); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "C:\Users\mwh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\youtube_dl\extractor\youtube.py", line 1672, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "C:\Users\mwh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\youtube_dl\extractor\youtube.py", line 1644, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "C:\Users\mwh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\youtube_dl\extractor\youtube.py", line 1627, in _extract_n_function_name
    real_nfunc = self._search_regex(
  File "C:\Users\mwh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\youtube_dl\extractor\common.py", line 1013, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function alias (Usa[0]); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Something new that youtube-dl didn't do yesterday, it now does today
This is also a fairly fresh install, about 3 days old

**Comment by dirkf** [comment]
This is fixed in a later master version: #32346

**Comment by fizwack729** [comment]
Windows version would be nice....

**Comment by dirkf** [comment]
Review the issue linked above for the link with update suggestions, including Windows. However you appear to have an installation that can be updated with _pip_.

**Comment by fizwack729** [comment]
Ok, thanks, a bit hard to understand, but I just did a pip --force-install
and that looks like it worked - I re-downloaded the same video
in a few minutes compared to hours, & no error messages.
