### ISSUE TITLE
Discord Bot

### ISSUE THREAD

**Issue by Vortex11242456** [ytdl-org/youtube-dl#32370]
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\cyber\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cyber\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\cyber\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cyber\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1690, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cyber\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cyber\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "C:\Games\Discord Bot\main.py", line 593, in on_message
    await play_song(ctx, video_id)
  File "C:\Games\Discord Bot\main.py", line 201, in play_song
    ydl.download([video_url])
  File "C:\Users\cyber\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 2055, in download
    res = self.extract_info(
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\cyber\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 799, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cyber\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\cyber\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\cyber\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
Review #30839 **as asked**.
