### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by Sklecs** [ytdl-org/youtube-dl#32371]
B:\MyProjectPython\pythonProject\downloadYT>youtube-dl --verbose https://www.youtube.com/playlist?list=PLyc_E1fmJGpK-95isgLF4ktmXrXpjZyOO
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/playlist?list=PLyc_E1fmJGpK-95isgLF4ktmXrXpjZyOO']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:tab] PLyc_E1fmJGpK-95isgLF4ktmXrXpjZyOO: Downloading webpage
[download] Downloading playlist: Прочее
[youtube:tab] playlist Прочее: Downloading 2 videos
[download] Downloading video 1 of 2
[youtube] ClhGKuoeJhE: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

There is the latest version youtube-dl . I do not know what to do, I'm trying to fix the second day.

**Comment by dirkf** [comment]
Did you read the pinned issue #30839 ?
