### ISSUE TITLE
Trouble to Download Playlist

### ISSUE THREAD

**Issue by larry77** [ytdl-org/youtube-dl#32380]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl --verbose https://www.youtube.com/playlist?list=PLstKoj57gWXWXEwbW7tP9HnfTh4EX-Z8B
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/playlist?list=PLstKoj57gWXWXEwbW7tP9HnfTh4EX-Z8B']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.2 (CPython) - Linux-6.1.0-9-amd64-x86_64-with-glibc2.36
[debug] exe versions: ffmpeg 5.1.3-1, ffprobe 5.1.3-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] PLstKoj57gWXWXEwbW7tP9HnfTh4EX-Z8B: Downloading webpage
[download] Downloading playlist: Moominland, un mondo di serenità - Episodi ITA
[youtube:tab] playlist Moominland, un mondo di serenità - Episodi ITA: Downloading 25 videos
[download] Downloading video 1 of 25
[youtube] a0Q70zESbhg: Downloading webpage
[youtube] a0Q70zESbhg: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

I am trying to download the playlist at 

https://www.youtube.com/playlist?list=PLstKoj57gWXWXEwbW7tP9HnfTh4EX-Z8B

but I get an error message. I run debian stable and I have just installed youtube-dl with

sudo -H pip install  --break-system-packages  --upgrade youtube-dl

**Comment by dirkf** [comment]
#30839 ! Use the checklist !
