### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by chatarny** [ytdl-org/youtube-dl#32405]
C:\youtube-dl> youtube-dl --verbose https://www.youtube.com/watch?v=4r1USrd4vB0 -x
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=4r1USrd4vB0', '-x']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22621
[debug] exe versions: ffmpeg N-111332-g9ff834c2a0-20230704, ffprobe N-111332-g9ff834c2a0-20230704
[debug] Proxy map: {}
[youtube] 4r1USrd4vB0: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
#30839 !

**Comment by chatarny** [comment]
Where is the duplicate @dirkf? I have been trying to find a solution for two days :(

**Comment by dirkf** [comment]
Did you actually read #30839?

**Comment by chatarny** [comment]
Yes, but I am that good like you who can find things with just a snap of fingers :( 
Plz help. just a link to the article wd be enough @dirkf

**Comment by dirkf** [comment]
Read through to the "known issues" ...
