### ISSUE TITLE
Error: Unable to extract

### ISSUE THREAD

**Issue by riddle00** [ytdl-org/youtube-dl#32404]
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
[youtube] 0R9c5fFVtBI: Downloading webpage
[youtube] 0R9c5fFVtBI: Downloading player 23604418
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

----------------------- verbose command line and log --------------------------------

youtube-dl --ignore-errors                \
>    --no-playlist                          \
>    --no-check-certificate                 \
>    --skip-unavailable-fragments           \
>    --restrict-filenames                   \
>    --format mp4                           \
>    --hls-prefer-native                    \
>    -o "%(title)s.%(ext)s"       -v        https://www.youtube.com/watch?v=0R9c5fFVtBI

[youtube] 0R9c5fFVtBI: Downloading webpage
[youtube] Downloading just video 0R9c5fFVtBI because of --no-playlist
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
usr1:12:09:46:Videos>> youtube-dl --ignore-errors                   --no-playlist                             --no-check-certificate                    --skip-unavailable-fragments              --restrict-filenames                      --format mp4                              --hls-prefer-native                       -o "%(title)s.%(ext)s"       -v          https://www.youtube.com/watch?v=0R9c5fFVtBI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-errors', '--no-playlist', '--no-check-certificate', '--skip-unavailable-fragments', '--restrict-filenames', '--format', 'mp4', '--hls-prefer-native', '-o', '%(title)s.%(ext)s', '-v', 'https://www.youtube.com/watch?v=0R9c5fFVtBI']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.6.15 (CPython) - Linux-5.14.21-150400.24.66-default-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 3.4.12, ffprobe 3.4.12
[debug] Proxy map: {}
[youtube] 0R9c5fFVtBI: Downloading webpage
[youtube] Downloading just video 0R9c5fFVtBI because of --no-playlist
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


## Description

<!--
Provide an explanation of your issue in an arbitrary form. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
#30839 ! Use the checklist !
>[ ] I've searched the bugtracker for similar issues including closed ones

Why not?

**Comment by riddle00** [comment]
Because if the solution were in the bug tracker, it would have been fixed
by now. This problem was not caused by a user input error. This is a
software problem that I hope you can resolve. Thank you.

**Comment by dirkf** [comment]
Obviously it is in the tracker and also **actually listed** in the [pinned issue](https://github.com/ytdl-org/youtube-dl/issues/30839) that you were asked to read.
