### ISSUE TITLE
Pornuhb extractor no longer working, unable to extract encoded URL

### ISSUE THREAD

**Issue by alcxander** [ytdl-org/youtube-dl#32448]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

D:\Software\Youtube-dl>youtube-dl https://www.pornhub.com/view_video.php?viewkey=ph60a8e6fd7b54c --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.pornhub.com/view_video.php?viewkey=ph60a8e6fd7b54c', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[PornHub] ph60a8e6fd7b54c: Downloading pc webpage
[PornHub] ph60a8e6fd7b54c: Downloading tv webpage
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\pornhub.py", line 401, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\pornhub.py", line 338, in extract_js_vars
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

trying to download this link, not working something wrong with the 'encoding' on the URL. not sure whats going on, went around and looked at other examples online like
youtube-dl https://www.pornhub.com/view_video.php?viewkey=ph5a591d4cdaa82 (found on https://old.reddit.com/r/DataHoarder/comments/88444v/youtubedl_and_pornhub_channels/) which shows as working for them but no longer works for me same debug message above. so i assume something has changed on the site if previous URLS work but not for me now and I dont think i can make the command any simpler to test other things. 

also updates to latest version: 
D:\Software\Youtube-dl>youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

**Comment by dirkf** [comment]
Reproducible with master code. There are outstanding PR changes and also recent updates that could be back-ported from yt-dlp.

**Comment by alcxander** [comment]
sorry @dirkf do you mean you want me to merge some previous PR's to do this or someone else is going to do this merge and republish to download?

**Comment by dirkf** [comment]
Someone has to review the existing code and potential updates and produce a PR (and not then close it in a strop). If it's not me doing that, it may happen sooner.

**Comment by mnplly** [comment]
##[👉🔴 Click Here >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
##[👉🔴 Click Here >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
##[👉🔴 Click Here >>](https://securecd-smrtnd.com/s?a=256440&sm=46517&co=316585&mt=5)
🚀 How to Use Eporner – A Quick Guide!
Hey everyone! 👋 If you're exploring ways to use Eporner, here's a quick guide to get you started:

Steps to Use pornhub.com: ##[👉🔴 Click Here >>](https://securecd-smrtnd.com/s?a=256440&sm=46517&co=316585&mt=5)
Visit the Official Website: Head over to Eporner for a wide range of free content.
Search What You Need: Use the search bar to find specific videos or categories that interest you.
Customize Your Experience: Create an account to save favorites and access advanced features.
💡 Pro Tip: Make sure to check out the "HD" section for the best quality videos!

Let me know if you have any questions, or drop a comment below with your experience. 👍
