### ISSUE TITLE
HiDive Download Error

### ISSUE THREAD

**Issue by YewTreeWeb** [ytdl-org/youtube-dl#32441]
Hi everyone, I'm trying to download from HiDive as I found that there is an extractor and previous PR so that HiDive was supported.  I'm running version `2021.12.17` of youtube-dl and when I try to download from HiDive with the command `youtube-dl -u USERNAME -p PASSWORD https://www.hidive.com/stream/farming-life-in-another-world/s01e001 --user-agent "Mozilla/5.0"`, I always get an error:

```
[HiDive] None: Downloading webpage
[HiDive] Logging in
[HiDive] farming-life-in-another-world/s01e001: Downloading JSON metadata
ERROR: HiDive said: PremiumContent
```
I have tried adding --referrer  and/or --cookies as well to the command but still get an error. I'm pretty new to HiDive but from what I read about them was that they didn't offer a free plan like Crunchyroll and instead only offered a paid plan so the error `PremiumContent` threw me. However, when doing a verbose output I get this more detailed error hinting that it is an issue with the extractor:

```
ERROR: HiDive said: PremiumContent
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 824, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 845, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 535, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/hidive.py", line 75, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: HiDive said: PremiumContent
```

Any help or suggestions you have would be appreciated. Thanks for taking the time to look at my ticket

**Comment by dirkf** [comment]
Instead of using `-u USERNAME -p PASSWORD`, try `--cookies ...` with a cookie file extracted from a logged-in browser session.

**Comment by YewTreeWeb** [comment]
Hi @dirkf, thanks for the reply. I did try `--cookies` but it initially didn't work but has now, so I must have done something wrong. Instead, the issue now is I'm just getting the HIDIVE logo and not the actual episode. I can see it trying to access but there is a 403 error happening.

```
[https @ 0x7f9797204ec0] HTTP error 403 Forbidden
[crypto @ 0x7f9797204ac0] Unable to open resource: https://video.hidive.com/content/FAW/HLS/HLS1080p/FAW_s01e001_tv_br_or_ja_xx_HLS1080p_16x9_00_v00146.ts?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vdmlkZW8uaGlkaXZlLmNvbS9jb250ZW50L0ZBVy9ITFMvKi9GQVdfczAxZTAwMV90dl9icl9vcl9qYV94eCoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2ODk1OTgwMTh9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiOTIuMjEuOTAuMjUyLzMyIn0sIkRhdGVHcmVhdGVyVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjg5NTkwNTE4fX19XX0_&Signature=oD4KX2sO8sKzxjNqvNbdDvfBHXhL6u8I1Gi5aV4wD2dG6VC3lQYZzITabCE1twnPSqE8rDDLppcEPowJ71vG1qsLw7noyWoya3v85cYrjPajf97ouWlY~Fh2Kn0ckWwmppMBA~tfn8XM9dL1xs7uzxbW-2K0Pu1zJsc~FggbxnsT3V2wLroJC9XNx-~TArvhO1FWu4CcKl--Th4EhgYI5rmDnlvStTZ7p7qzVnGh6Ei0mJEQskwsI52zpSHj1xb6~gNyjl2A6rKteWvFscdpKFgdYgRVquf1YDmaRslHp2pER~9c7amclijJbTWNEf~vBk2UIpK1nqxrwkQT4H3SyA__&Key-Pair-Id=KH8YN22TJF8FN
```

**Comment by dirkf** [comment]
Definitely try `--referer URL` when accessing `URL` as well as `--cookies ...`. This is built into the yt-dlp (fork) version. Using cookies wouldn't have worked if you also had `--user ...`/`-u ...`.

**Comment by dirkf** [comment]
In https://github.com/ytdl-org/youtube-dl/issues/17168#issuecomment-1637920044, OP wrote:
>I had the same issue but got it to work with `youtube-dl $URL --user-agent "Mozilla/5.0" --cookies "www.hidive.com_cookies.txt" --referer "$URL"` You can't use -u or -p and instead a generated cookie.txt file while you're logged into the HIDIVE site. I use 'GET cookies.txt LOCALLY' extension to download them.

Is the `--user-agent ...` parameter critical? If so, we can code that (and the `--referer`) into a new version of the extractor.

**Comment by dirkf** [comment]
From https://github.com/ytdl-org/youtube-dl/issues/28575#issuecomment-813254154:
>Of note is that HiDive has added a Google Captcha to the login page that I don't believe was there previously. It seems to be the kind that users don't see, but is watching them for bot-like behaviour (i.e. ReCAPTCHA V3). I had to enable scripts from google.com on uBlock Origin before I could login on Firefox.

This alone would have broken the login procedure in the extractor.
