### ISSUE TITLE
Kinetic video not downloading, 400 error , same code was working a couple of days back !

### ISSUE THREAD

**Issue by skr2538** [ytdl-org/youtube-dl#32458]
Guys,

i was using youtube dl to download the kinetic dataset videos , its giving me 400 bad request error, however the code worked a couple of days back , anyone else facing this issue with youtube dl now, here is the full description of error. STUCK here , need urgent help

Error verbose -

Failed to download video  Error message: [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--postprocessor-args', '-ss 0 -to 10', 'https://www.youtube.com/watch?v=imZxxximci0', '-o', '/content/drive/MyDrive/kinetic_unknown/javelin throw/imZxxximci0.%(ext)s', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.109+-x86_64-with-glibc2.31 - OpenSSL 1.1.1f  31 Mar 2020 - glibc 2.31
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {'colab_language_server': '/usr/colab/bin/language_service'}
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 2126, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 2065, in dl
    return fd.download(name, new_info)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/downloader/common.py", line 380, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/downloader/http.py", line 349, in real_download
    establish_connection()
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 2489, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by dirkf** [comment]
Follow #30839 !

Having said that, I could reproduce the problem, so it wasn't your proxy setup.

The video link from my debug output played OK in _mpv_ showing a javelin thrower.

**But**, now it works with all these, of which the first two failed with 400 when first tested:
* nightly POSIX build (selected 135+140)
* current master (ditto)
* yt-dlp stable (selected 244+150).

So I suppose this was a glitch in YT's content serving.
