### ISSUE TITLE
[youtube] Add Google Sign-in for Age Confirmation 

### ISSUE THREAD

**Issue by bomb0000** [ytdl-org/youtube-dl#32459]
## Checklist

- [*] I'm reporting a feature request
- [*] I've verified that I'm running youtube-dl version **2021.12.17**
- [*] I've searched the bugtracker for similar feature requests including closed ones

## Description

Some youtube video need "Sign in to confirm your age".  I don't have youtube a/c, but I can sign-in google for confirmation.
Would you add option to sign-in google?

**Comment by dirkf** [comment]
The master version has an age-gate bypass, which enables content available to ages of `--age-limit ...` or higher (default 18) where possible. Try using that: #30839.

Otherwise, use your browser cookies with `--cookies ...`.

**Comment by bomb0000** [comment]
cookies? Is file %APPDATA%\Mozilla\Profiles\Firefox\Profiles\xx.default\cookies.sqlite
but it fails with below error
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\__init__.py", line 442, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 422, in __init__
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2379, in _setup_opener
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\utils.py", line 2832, in load
  File "C:\Python\Python34\lib\codecs.py", line 319, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 16: invalid start byte

**Comment by dirkf** [comment]
https://github.com/ytdl-org/youtube-dl#user-content-how-do-i-pass-cookies-to-youtube-dl

**Comment by dirkf** [comment]
> Nevertheless, I will try yt-dlp.

That should also work (maybe use its `--cookies-from-browser` option if needed instead of the FAQ above) but wasn't suggested. The yt-dl version in the nightly release repo linked above has the age-gate bypass.

**Comment by bomb0000** [comment]
it works with yt-dlp
