### ISSUE TITLE
 Could not find object iI 

### ISSUE THREAD

**Issue by steelliberty** [ytdl-org/youtube-dl#32462]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

(transcriber) root@transcriber:~# youtube-dl --verbose https://youtube.com/watch?v=Dk2QFXMHM88
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://youtube.com/watch?v=Dk2QFXMHM88']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python 3.10.11 (CPython x86_64 64bit) - Linux-5.19.0-46-generic-x86_64-with-glibc2.36 - OpenSSL 1.1.1t  7 Feb 2023 - glibc 2.36
[debug] exe versions: ffmpeg 5.1.1, ffprobe 5.1.1
[debug] Proxy map: {}
[youtube] Dk2QFXMHM88: Downloading webpage
[youtube] Dk2QFXMHM88: Downloading player 8e83803a
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1589, in _decrypt_signature
    func = self._extract_signature_function(
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1510, in _extract_signature_function
    cache_res = res(test_string)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1578, in <lambda>
    return lambda s: initial_function([s])
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 36, in __call__
    return self.func(*args, **kwargs)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 1037, in resf
    ret, should_abort = self.interpret_statement(code.replace('\n', ' '), var_stack, allow_recursion - 1)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 441, in interpret_statement
    ret, should_return = self.interpret_statement(sub_stmt, local_vars, allow_recursion)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 915, in interpret_statement
    return eval_method(), should_return
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 800, in eval_method
    self._objects[variable] = self.extract_object(variable)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 952, in extract_object
    raise self.Exception('Could not find object ' + objname)
youtube_dl.jsinterp.JSInterpreter.Exception: **Could not find object iI; please report this issue on https://yt-dl.org/bug** . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by Exception('Could not find object iI; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1589, in _decrypt_signature
    func = self._extract_signature_function(
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1510, in _extract_signature_function
    cache_res = res(test_string)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1578, in <lambda>
    return lambda s: initial_function([s])
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 36, in __call__
    return self.func(*args, **kwargs)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 1037, in resf
    ret, should_abort = self.interpret_statement(code.replace('\n', ' '), var_stack, allow_recursion - 1)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 441, in interpret_statement
    ret, should_return = self.interpret_statement(sub_stmt, local_vars, allow_recursion)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 915, in interpret_statement
    return eval_method(), should_return
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 800, in eval_method
    self._objects[variable] = self.extract_object(variable)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 952, in extract_object
    raise self.Exception('Could not find object ' + objname)
youtube_dl.jsinterp.JSInterpreter.Exception: Could not find object iI; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1589, in _decrypt_signature
    func = self._extract_signature_function(
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1510, in _extract_signature_function
    cache_res = res(test_string)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1578, in <lambda>
    return lambda s: initial_function([s])
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 36, in __call__
    return self.func(*args, **kwargs)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 1037, in resf
    ret, should_abort = self.interpret_statement(code.replace('\n', ' '), var_stack, allow_recursion - 1)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 441, in interpret_statement
    ret, should_return = self.interpret_statement(sub_stmt, local_vars, allow_recursion)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 915, in interpret_statement
    return eval_method(), should_return
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 800, in eval_method
    self._objects[variable] = self.extract_object(variable)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 952, in extract_object
    raise self.Exception('Could not find object ' + objname)
youtube_dl.jsinterp.JSInterpreter.Exception: Could not find object iI; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 825, in wrapper
    return func(self, *args, **kwargs)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 846, in __extract_info
    ie_result = ie.extract(url)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 535, in extract
    ie_result = self._real_extract(url)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 2032, in _real_extract
    signature = self._decrypt_signature(sc['s'][0], video_id, player_url)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1599, in _decrypt_signature
    raise ExtractorError(
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1589, in _decrypt_signature
    func = self._extract_signature_function(
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1510, in _extract_signature_function
    cache_res = res(test_string)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1578, in <lambda>
    return lambda s: initial_function([s])
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 36, in __call__
    return self.func(*args, **kwargs)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 1037, in resf
    ret, should_abort = self.interpret_statement(code.replace('\n', ' '), var_stack, allow_recursion - 1)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 441, in interpret_statement
    ret, should_return = self.interpret_statement(sub_stmt, local_vars, allow_recursion)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 915, in interpret_statement
    return eval_method(), should_return
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 800, in eval_method
    self._objects[variable] = self.extract_object(variable)
  File "/var/miniconda3/envs/transcriber/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 952, in extract_object
    raise self.Exception('Could not find object ' + objname)
youtube_dl.jsinterp.JSInterpreter.Exception: Could not find object iI; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by Exception('Could not find object iI; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

I was using youtube-dl and attempted this video and was presented with a new issue -- The video: https://youtube.com/watch?v=Dk2QFXMHM88

I can play the video and I tried downloading it from the command line as well as in my code and the message is the same. I do not see this issue elsewhere in the issues forum. 

Thank you - JM

**Comment by dirkf** [comment]
I can't reproduce this with the master code, or with a recent nightly build:
```console
 ./youtube-dl-20230718 -v -F 'https://youtube.com/watch?v=Dk2QFXMHM88'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://youtube.com/watch?v=Dk2QFXMHM88']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2023.07.18 [47214e46d] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 2.7.18 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial - OpenSSL 1.1.1u  30 May 2023 - glibc 2.15
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] Dk2QFXMHM88: Downloading webpage
[debug] [youtube] Decrypted nsig QaolwXKp7MnaizsPWh => OHgJh6GcgpQTDA
[debug] [youtube] Decrypted nsig wmXojlgp76qQm0xmVw => cITJP9FhgZQUYQ
[info] Available formats for Dk2QFXMHM88:
format code  extension  resolution note
249          webm       audio only tiny   49k , webm_dash container, opus  (48000Hz), 64.69MiB
250          webm       audio only tiny   62k , webm_dash container, opus  (48000Hz), 81.48MiB
251          webm       audio only tiny  119k , webm_dash container, opus  (48000Hz), 155.04MiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2 (44100Hz), 168.17MiB
160          mp4        256x144    144p   28k , mp4_dash container, avc1.4d400c, 30fps, video only, 36.56MiB
278          webm       256x144    144p   45k , webm_dash container, vp9, 30fps, video only, 58.83MiB
133          mp4        426x240    240p   52k , mp4_dash container, avc1.4d4015, 30fps, video only, 67.79MiB
242          webm       426x240    240p   69k , webm_dash container, vp9, 30fps, video only, 90.16MiB
134          mp4        640x360    360p   90k , mp4_dash container, avc1.4d401e, 30fps, video only, 117.70MiB
243          webm       640x360    360p  143k , webm_dash container, vp9, 30fps, video only, 186.74MiB
135          mp4        854x480    480p  142k , mp4_dash container, avc1.4d401f, 30fps, video only, 185.16MiB
244          webm       854x480    480p  213k , webm_dash container, vp9, 30fps, video only, 277.02MiB
136          mp4        1280x720   720p  238k , mp4_dash container, avc1.4d401f, 30fps, video only, 309.29MiB
247          webm       1280x720   720p  359k , webm_dash container, vp9, 30fps, video only, 466.68MiB
248          webm       1920x1080  1080p  589k , webm_dash container, vp9, 30fps, video only, 766.27MiB
137          mp4        1920x1080  1080p  680k , mp4_dash container, avc1.640028, 30fps, video only, 884.07MiB
18           mp4        640x360    360p  309k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz), 402.52MiB
22           mp4        1280x720   720p  367k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
$ 
```
Although the actual crash is different, your diagnostic and line numbers match #32314. Presumably new YT player JS is crashing that version of `jsinterp.py` in a different way.

Please update your yt-dl code again from the master or from the [nightly](https://github.com/ytdl-org/ytdl-nightly/releases/latest) `.tar.gz`, or install a nightly build. See #30839.

**Comment by dirkf** [comment]
`--force-reinstall` may have helped in the first case.
