### ISSUE TITLE
Error downloading YouTube video with expiration feature

### ISSUE THREAD

**Issue by tony-fernandes** [ytdl-org/youtube-dl#32478]
## Checklist

- [x] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-4vC', '--retries', 'infinite', '--fragment-retries', 'infinite', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; rv:102.0) Gecko/20100101 Firefox/102.0', '--recode-video', 'mp4', '--audio-format', 'mp3', '--audio-quality', '0', '--embed-thumbnail', '-o', '%(title)s %(release_date)s', 'https://www.youtube.com/watch?v=eL5tVGEuPK8']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Linux-6.1.0-1parrot1-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0
[debug] Proxy map: {}
[debug] Public IP address: 177.37.248.6
[youtube] eL5tVGEuPK8: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

It seems to be an error in the Python code regarding the uploader id extraction. I don't know Python, or I'd have fixed it myself and posted the solution here, so I don't know what might be relevant. The only thing that comes to mind is that this video has an expiration period feature enabled. I don't know how long this feature has been around on YouTube, though. The way I see it, adding an option for disabling the uploader id extraction might be a workaround. I don't know how to be of more help, I'm sorry for that.

**Comment by dirkf** [comment]
#30839 !
