### ISSUE TITLE
Unable to download from ITVX

### ISSUE THREAD

**Issue by kentcb** [ytdl-org/youtube-dl#32486]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-part', '--restrict-filenames', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0', '--add-header', "Cookie:_abck=4B10A7C58AC33803FFF1A5C55B6216D1~-1~YAAQ3T9lX93nkZeJAQAANAJvqQrJ7k+3A1F9w1t6G/3HTo74hsulXRGg5AGDSO5269Np5qS5PKJnOups1SxVtpId4VgsHNLQ97J8SDX3bvGdSVjxQHGz0DZHQrlEvtiTq3Vk8vgqX9FKTaEBugUpbZI8JOl4ZfXSuJUNQy/ofuF5mboBOJsR0sN2PsHoPEbH/wU/h7PT4/Le56O2S60YZvAcTdO4liI690guukk5UDTf1eJGDHrAGFFUiTWt92C37GthPoo/Vn47Lvom4eF1HCh+YS1bA35JMEw7Yr4AKAREsIrBPicA/lBEEiWIUGemBhEa3zLjddHotf8U1Jr4zWWgU1ZNHxsmH1gPlesX0ApYeNjZjhSupjbzbcmQjgwQQwAOQJ2UYqY=~-1~-1~-1; Itv.Session={'tokens':{'content':{'entitlement':{'purchased':[],'source':'','failed_availability_checks':[]},'email_verified':true,'token_type':'bearer','access_token':'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2F1dGguaXR2LmNvbSIsInN1YiI6ImE3OTBiOTcwLTc3NmEtNDk1NC1hM2RkLTRkZWFkM2MyZDkyNyIsImV4cCI6MTY5MDg1OTEwMywiaWF0IjoxNjkwNzY5MTAzLCJicm9hZGNhc3RFcnJvck1zZyI6IiIsImJyb2FkY2FzdFJlc3BvbnNlQ29kZSI6IjIwMCIsImJyb2FkY2FzdGVyIjoiSVRWIiwiaXNBY3RpdmUiOnRydWUsIm5vbmNlIjoiY2VyYmVydXMtYXV0aC1yZXF1ZXN0LTE2OTAwNzE4NDE1NDEiLCJuYW1lIjoiS2VudCIsInNjb3BlIjoiY29udGVudCIsImVudGl0bGVtZW50cyI6W10sInBheW1lbnRTb3VyY2UiOiIiLCJzaG93UHJpdmFjeU5vdGljZSI6ZmFsc2UsInVuZGVyMTgiOmZhbHNlLCJhY2NvdW50UHJvZmlsZUlkSW5Vc2UiOiJhNzkwYjk3MC03NzZhLTQ5NTQtYTNkZC00ZGVhZDNjMmQ5MjdfMCIsInJlZ2lvbiI6ImxvbmRvbiIsInBvc3Rjb2RlQ2FwdHVyZWRPbiI6MTY5MDA3MDQwMDAwMH0.RtUf4VXtF7FNB8woCpdCva9E4tfdrTu2Utq0KWBZ_uijyiaPzQ_k03x9uUicEmejjVucjwVlLucfUT89k5Z_o56CyNyS8hQxZLtQmDXuyr_0rpiY5fvjDCvy_8jJ6jIHbEli2vNU_XQJedkJ1I3jdUkD954VL8omZYsA_cIZaYd8K5BUvZ2cDW6KvH06dPpMiZAavLm3Tf-FKIeaMYqQWCZPw4b_du164-PXhz48oKoNYlbhcUuqPatr1O2Yc14bUk-EHWbvPTsTWUkHlfoX8DO4DHwA0ffxEuwqaTyOfgVVw7Ee3O44z02BsNdXngwguEd-eyNFxXYXYvMjldXVzw','refresh_token':'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2F1dGguaXR2LmNvbSIsInN1YiI6ImE3OTBiOTcwLTc3NmEtNDk1NC1hM2RkLTRkZWFkM2MyZDkyNyIsImV4cCI6NDg0NjQ0MjcwMywiaWF0IjoxNjkwNzY5MTAzLCJub25jZSI6ImNlcmJlcnVzLWF1dGgtcmVxdWVzdC0xNjkwMDcxODQxNTQxIiwic2NvcGUiOiJjb250ZW50IiwiYXV0aF90aW1lIjoxNjkwNzY5MTAzLCJhY2NvdW50UHJvZmlsZUlkSW5Vc2UiOiJhNzkwYjk3MC03NzZhLTQ5NTQtYTNkZC00ZGVhZDNjMmQ5MjdfMCJ9.IK3hkKXMrUDrFsTFNFRR64Ip-NT6qmYb5wO0N2vbwUI8xuK3ETi7Lg7zuxhNGdW6pVtF7fICE-bJ4NCl84ngGujd69JY1ht6_bNyzq3nqy0Z1a-jjnfjeIy6Osy8S4LcKMJNV1uNFQ3EdJUmCnU_Hg4qjhIEdyZPTIYoF0ieDk6W7BEgV1mf2USz1z0pu5o17zXz9ReJzIuHK6yov-KvXe7SX1vpItGpEXwniOK6YwbWinynwmU_EPYevriWZ-_mfdlupbQ39MvnLvzRs40Xb1-ocxBzn3_BV-lTy__On-ehg3O6fUOZQ6VAM4DVneNlHcSDNPIL4xRM5g5uSKn6Cw'}},'sticky':false,'redirect':'/watch/fifa-womens-world-cup-2023/10a4671/10a4671a0009'}; bm_sz=89C7370AC9DF09A6988C0065B3099C81~YAAQ3T9lX97nkZeJAQAANAJvqRTGYlSFcrciszVRtIJONFweI0XpKeAHCUdvl7xwe1gZVn1leVON6TyrfKqKMsjrcWMGsOI43CGHFjPdrW5LLd//31/rVuf2wUKe8C5tfZU/B9zlDpZopTKSSKe4U+cPu+17hjHHsOwXfCB7Hnjg0RxGHF9gu92/pb9w8far8W0kmK3+kErPy7au2aRWkhzyiwhKZ41FMT0h9FGYN/42LFAvsD2JDlBvdKu9tyzkPgUIiFetiKxP7clYunrlZ9nS4RKUi/o842wp4OGsq8k=~3225138~4600886; Itv.Cid=894978cc-dd16-4d25-aefb-40c3af385881; SyrenisGuid_213aea86-31e5-43f3-8d6b-e01ba0d420c7=d6fbec20-8637-4a46-bbe0-40f7e0d3a7b0; SyrenisCookieIDs_213aea86-31e5-43f3-8d6b-e01ba0d420c7=[]; SyrenisCookieFormConsent_213aea86-31e5-43f3-8d6b-e01ba0d420c7=[{'FieldID':'s122_c113','IsChecked':1},{'FieldID':'s135_c126','IsChecked':1},{'FieldID':'s134_c125','IsChecked':1},{'FieldID':'s138_c129','IsChecked':1},{'FieldID':'s157_c147','IsChecked':1},{'FieldID':'s136_c127','IsChecked':1},{'FieldID':'s137_c128','IsChecked':1}]; SyrenisCookiePrivacyLink_213aea86-31e5-43f3-8d6b-e01ba0d420c7=1; SyrenisRunFirstCookieIDs_213aea86-31e5-43f3-8d6b-e01ba0d420c7=[]; SyrenisCookieConsentDate_213aea86-31e5-43f3-8d6b-e01ba0d420c7=1690764790690.9; SyrenisCustom_213aea86-31e5-43f3-8d6b-e01ba0d420c7=[]; Itv.cck={}; hdntl=exp=1690851239~acl=%2f10-4671-0009-001%2f*~data=hdntl,nohubplus~hmac=949240e593528c66072ee61d634214579c0502d3e989a5c384f5c036a72c866f; topid=DM:A790B970-776A-4954-A3DD-4DEAD3C2D927", '--referer', 'https://www.itv.com/', 'https://itvpnpdotcom.blue.content.itv.com/10-4671-0009-001/34/1/VAR028-HD-s/10-4671-0009-001_34_1_VAR028-HD-s.ism/.mpd?filter=%28%28type%3D%3D%22video%22%26%26DisplayHeight%3C%3D720%29%7C%7C%28type%21%3D%22video%22%29%29&hdnea=st%3D1690769096~exp%3D1690790696~acl%3D/10-4671-0009-001/%2A~data%3Dnohubplus~hmac%3D931594dac049db2db664785c81a1875172476bf3030cece490fdbdc20bc5ad82']
[debug] Adding header from command line option Cookie:_abck=4B10A7C58AC33803FFF1A5C55B6216D1~-1~YAAQ3T9lX93nkZeJAQAANAJvqQrJ7k+3A1F9w1t6G/3HTo74hsulXRGg5AGDSO5269Np5qS5PKJnOups1SxVtpId4VgsHNLQ97J8SDX3bvGdSVjxQHGz0DZHQrlEvtiTq3Vk8vgqX9FKTaEBugUpbZI8JOl4ZfXSuJUNQy/ofuF5mboBOJsR0sN2PsHoPEbH/wU/h7PT4/Le56O2S60YZvAcTdO4liI690guukk5UDTf1eJGDHrAGFFUiTWt92C37GthPoo/Vn47Lvom4eF1HCh+YS1bA35JMEw7Yr4AKAREsIrBPicA/lBEEiWIUGemBhEa3zLjddHotf8U1Jr4zWWgU1ZNHxsmH1gPlesX0ApYeNjZjhSupjbzbcmQjgwQQwAOQJ2UYqY=~-1~-1~-1; Itv.Session={'tokens':{'content':{'entitlement':{'purchased':[],'source':'','failed_availability_checks':[]},'email_verified':true,'token_type':'bearer','access_token':'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2F1dGguaXR2LmNvbSIsInN1YiI6ImE3OTBiOTcwLTc3NmEtNDk1NC1hM2RkLTRkZWFkM2MyZDkyNyIsImV4cCI6MTY5MDg1OTEwMywiaWF0IjoxNjkwNzY5MTAzLCJicm9hZGNhc3RFcnJvck1zZyI6IiIsImJyb2FkY2FzdFJlc3BvbnNlQ29kZSI6IjIwMCIsImJyb2FkY2FzdGVyIjoiSVRWIiwiaXNBY3RpdmUiOnRydWUsIm5vbmNlIjoiY2VyYmVydXMtYXV0aC1yZXF1ZXN0LTE2OTAwNzE4NDE1NDEiLCJuYW1lIjoiS2VudCIsInNjb3BlIjoiY29udGVudCIsImVudGl0bGVtZW50cyI6W10sInBheW1lbnRTb3VyY2UiOiIiLCJzaG93UHJpdmFjeU5vdGljZSI6ZmFsc2UsInVuZGVyMTgiOmZhbHNlLCJhY2NvdW50UHJvZmlsZUlkSW5Vc2UiOiJhNzkwYjk3MC03NzZhLTQ5NTQtYTNkZC00ZGVhZDNjMmQ5MjdfMCIsInJlZ2lvbiI6ImxvbmRvbiIsInBvc3Rjb2RlQ2FwdHVyZWRPbiI6MTY5MDA3MDQwMDAwMH0.RtUf4VXtF7FNB8woCpdCva9E4tfdrTu2Utq0KWBZ_uijyiaPzQ_k03x9uUicEmejjVucjwVlLucfUT89k5Z_o56CyNyS8hQxZLtQmDXuyr_0rpiY5fvjDCvy_8jJ6jIHbEli2vNU_XQJedkJ1I3jdUkD954VL8omZYsA_cIZaYd8K5BUvZ2cDW6KvH06dPpMiZAavLm3Tf-FKIeaMYqQWCZPw4b_du164-PXhz48oKoNYlbhcUuqPatr1O2Yc14bUk-EHWbvPTsTWUkHlfoX8DO4DHwA0ffxEuwqaTyOfgVVw7Ee3O44z02BsNdXngwguEd-eyNFxXYXYvMjldXVzw','refresh_token':'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2F1dGguaXR2LmNvbSIsInN1YiI6ImE3OTBiOTcwLTc3NmEtNDk1NC1hM2RkLTRkZWFkM2MyZDkyNyIsImV4cCI6NDg0NjQ0MjcwMywiaWF0IjoxNjkwNzY5MTAzLCJub25jZSI6ImNlcmJlcnVzLWF1dGgtcmVxdWVzdC0xNjkwMDcxODQxNTQxIiwic2NvcGUiOiJjb250ZW50IiwiYXV0aF90aW1lIjoxNjkwNzY5MTAzLCJhY2NvdW50UHJvZmlsZUlkSW5Vc2UiOiJhNzkwYjk3MC03NzZhLTQ5NTQtYTNkZC00ZGVhZDNjMmQ5MjdfMCJ9.IK3hkKXMrUDrFsTFNFRR64Ip-NT6qmYb5wO0N2vbwUI8xuK3ETi7Lg7zuxhNGdW6pVtF7fICE-bJ4NCl84ngGujd69JY1ht6_bNyzq3nqy0Z1a-jjnfjeIy6Osy8S4LcKMJNV1uNFQ3EdJUmCnU_Hg4qjhIEdyZPTIYoF0ieDk6W7BEgV1mf2USz1z0pu5o17zXz9ReJzIuHK6yov-KvXe7SX1vpItGpEXwniOK6YwbWinynwmU_EPYevriWZ-_mfdlupbQ39MvnLvzRs40Xb1-ocxBzn3_BV-lTy__On-ehg3O6fUOZQ6VAM4DVneNlHcSDNPIL4xRM5g5uSKn6Cw'}},'sticky':false,'redirect':'/watch/fifa-womens-world-cup-2023/10a4671/10a4671a0009'}; bm_sz=89C7370AC9DF09A6988C0065B3099C81~YAAQ3T9lX97nkZeJAQAANAJvqRTGYlSFcrciszVRtIJONFweI0XpKeAHCUdvl7xwe1gZVn1leVON6TyrfKqKMsjrcWMGsOI43CGHFjPdrW5LLd//31/rVuf2wUKe8C5tfZU/B9zlDpZopTKSSKe4U+cPu+17hjHHsOwXfCB7Hnjg0RxGHF9gu92/pb9w8far8W0kmK3+kErPy7au2aRWkhzyiwhKZ41FMT0h9FGYN/42LFAvsD2JDlBvdKu9tyzkPgUIiFetiKxP7clYunrlZ9nS4RKUi/o842wp4OGsq8k=~3225138~4600886; Itv.Cid=894978cc-dd16-4d25-aefb-40c3af385881; SyrenisGuid_213aea86-31e5-43f3-8d6b-e01ba0d420c7=d6fbec20-8637-4a46-bbe0-40f7e0d3a7b0; SyrenisCookieIDs_213aea86-31e5-43f3-8d6b-e01ba0d420c7=[]; SyrenisCookieFormConsent_213aea86-31e5-43f3-8d6b-e01ba0d420c7=[{'FieldID':'s122_c113','IsChecked':1},{'FieldID':'s135_c126','IsChecked':1},{'FieldID':'s134_c125','IsChecked':1},{'FieldID':'s138_c129','IsChecked':1},{'FieldID':'s157_c147','IsChecked':1},{'FieldID':'s136_c127','IsChecked':1},{'FieldID':'s137_c128','IsChecked':1}]; SyrenisCookiePrivacyLink_213aea86-31e5-43f3-8d6b-e01ba0d420c7=1; SyrenisRunFirstCookieIDs_213aea86-31e5-43f3-8d6b-e01ba0d420c7=[]; SyrenisCookieConsentDate_213aea86-31e5-43f3-8d6b-e01ba0d420c7=1690764790690.9; SyrenisCustom_213aea86-31e5-43f3-8d6b-e01ba0d420c7=[]; Itv.cck={}; hdntl=exp=1690851239~acl=%2f10-4671-0009-001%2f*~data=hdntl,nohubplus~hmac=949240e593528c66072ee61d634214579c0502d3e989a5c384f5c036a72c866f; topid=DM:A790B970-776A-4954-A3DD-4DEAD3C2D927
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: abef53466
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35 - OpenSSL 3.0.2 15 Mar 2022 - glibc 2.35
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/youtube-dl/youtube_dl/YoutubeDL.py", line 859, in wrapper
    return func(self, *args, **kwargs)
  File "/youtube-dl/youtube_dl/YoutubeDL.py", line 955, in __extract_info
    ie_result = ie.extract(url)
  File "/youtube-dl/youtube_dl/extractor/common.py", line 565, in extract
    ie_result = self._real_extract(url)
  File "/youtube-dl/youtube_dl/extractor/generic.py", line 2693, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "/youtube-dl/youtube_dl/extractor/common.py", line 1444, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I'm trying to download from ITV, e.g. [this](https://www.itv.com/watch/fifa-womens-world-cup-2023/10a4671/10a4671a0009). Using the Stream Detector plugin inside Firefox, I get:

```
yt-dlp --no-part --restrict-filenames -N 4 --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0" --add-header "Cookie:_abck=4B10A7C58AC33803FFF1A5C55B6216D1~-1~YAAQ3T9lX93nkZeJAQAANAJvqQrJ7k+3A1F9w1t6G/3HTo74hsulXRGg5AGDSO5269Np5qS5PKJnOups1SxVtpId4VgsHNLQ97J8SDX3bvGdSVjxQHGz0DZHQrlEvtiTq3Vk8vgqX9FKTaEBugUpbZI8JOl4ZfXSuJUNQy/ofuF5mboBOJsR0sN2PsHoPEbH/wU/h7PT4/Le56O2S60YZvAcTdO4liI690guukk5UDTf1eJGDHrAGFFUiTWt92C37GthPoo/Vn47Lvom4eF1HCh+YS1bA35JMEw7Yr4AKAREsIrBPicA/lBEEiWIUGemBhEa3zLjddHotf8U1Jr4zWWgU1ZNHxsmH1gPlesX0ApYeNjZjhSupjbzbcmQjgwQQwAOQJ2UYqY=~-1~-1~-1; Itv.Session={'tokens':{'content':{'entitlement':{'purchased':[],'source':'','failed_availability_checks':[]},'email_verified':true,'token_type':'bearer','access_token':'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2F1dGguaXR2LmNvbSIsInN1YiI6ImE3OTBiOTcwLTc3NmEtNDk1NC1hM2RkLTRkZWFkM2MyZDkyNyIsImV4cCI6MTY5MDg1OTEwMywiaWF0IjoxNjkwNzY5MTAzLCJicm9hZGNhc3RFcnJvck1zZyI6IiIsImJyb2FkY2FzdFJlc3BvbnNlQ29kZSI6IjIwMCIsImJyb2FkY2FzdGVyIjoiSVRWIiwiaXNBY3RpdmUiOnRydWUsIm5vbmNlIjoiY2VyYmVydXMtYXV0aC1yZXF1ZXN0LTE2OTAwNzE4NDE1NDEiLCJuYW1lIjoiS2VudCIsInNjb3BlIjoiY29udGVudCIsImVudGl0bGVtZW50cyI6W10sInBheW1lbnRTb3VyY2UiOiIiLCJzaG93UHJpdmFjeU5vdGljZSI6ZmFsc2UsInVuZGVyMTgiOmZhbHNlLCJhY2NvdW50UHJvZmlsZUlkSW5Vc2UiOiJhNzkwYjk3MC03NzZhLTQ5NTQtYTNkZC00ZGVhZDNjMmQ5MjdfMCIsInJlZ2lvbiI6ImxvbmRvbiIsInBvc3Rjb2RlQ2FwdHVyZWRPbiI6MTY5MDA3MDQwMDAwMH0.RtUf4VXtF7FNB8woCpdCva9E4tfdrTu2Utq0KWBZ_uijyiaPzQ_k03x9uUicEmejjVucjwVlLucfUT89k5Z_o56CyNyS8hQxZLtQmDXuyr_0rpiY5fvjDCvy_8jJ6jIHbEli2vNU_XQJedkJ1I3jdUkD954VL8omZYsA_cIZaYd8K5BUvZ2cDW6KvH06dPpMiZAavLm3Tf-FKIeaMYqQWCZPw4b_du164-PXhz48oKoNYlbhcUuqPatr1O2Yc14bUk-EHWbvPTsTWUkHlfoX8DO4DHwA0ffxEuwqaTyOfgVVw7Ee3O44z02BsNdXngwguEd-eyNFxXYXYvMjldXVzw','refresh_token':'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2F1dGguaXR2LmNvbSIsInN1YiI6ImE3OTBiOTcwLTc3NmEtNDk1NC1hM2RkLTRkZWFkM2MyZDkyNyIsImV4cCI6NDg0NjQ0MjcwMywiaWF0IjoxNjkwNzY5MTAzLCJub25jZSI6ImNlcmJlcnVzLWF1dGgtcmVxdWVzdC0xNjkwMDcxODQxNTQxIiwic2NvcGUiOiJjb250ZW50IiwiYXV0aF90aW1lIjoxNjkwNzY5MTAzLCJhY2NvdW50UHJvZmlsZUlkSW5Vc2UiOiJhNzkwYjk3MC03NzZhLTQ5NTQtYTNkZC00ZGVhZDNjMmQ5MjdfMCJ9.IK3hkKXMrUDrFsTFNFRR64Ip-NT6qmYb5wO0N2vbwUI8xuK3ETi7Lg7zuxhNGdW6pVtF7fICE-bJ4NCl84ngGujd69JY1ht6_bNyzq3nqy0Z1a-jjnfjeIy6Osy8S4LcKMJNV1uNFQ3EdJUmCnU_Hg4qjhIEdyZPTIYoF0ieDk6W7BEgV1mf2USz1z0pu5o17zXz9ReJzIuHK6yov-KvXe7SX1vpItGpEXwniOK6YwbWinynwmU_EPYevriWZ-_mfdlupbQ39MvnLvzRs40Xb1-ocxBzn3_BV-lTy__On-ehg3O6fUOZQ6VAM4DVneNlHcSDNPIL4xRM5g5uSKn6Cw'}},'sticky':false,'redirect':'/watch/fifa-womens-world-cup-2023/10a4671/10a4671a0009'}; bm_sz=89C7370AC9DF09A6988C0065B3099C81~YAAQ3T9lX97nkZeJAQAANAJvqRTGYlSFcrciszVRtIJONFweI0XpKeAHCUdvl7xwe1gZVn1leVON6TyrfKqKMsjrcWMGsOI43CGHFjPdrW5LLd//31/rVuf2wUKe8C5tfZU/B9zlDpZopTKSSKe4U+cPu+17hjHHsOwXfCB7Hnjg0RxGHF9gu92/pb9w8far8W0kmK3+kErPy7au2aRWkhzyiwhKZ41FMT0h9FGYN/42LFAvsD2JDlBvdKu9tyzkPgUIiFetiKxP7clYunrlZ9nS4RKUi/o842wp4OGsq8k=~3225138~4600886; Itv.Cid=894978cc-dd16-4d25-aefb-40c3af385881; SyrenisGuid_213aea86-31e5-43f3-8d6b-e01ba0d420c7=d6fbec20-8637-4a46-bbe0-40f7e0d3a7b0; SyrenisCookieIDs_213aea86-31e5-43f3-8d6b-e01ba0d420c7=[]; SyrenisCookieFormConsent_213aea86-31e5-43f3-8d6b-e01ba0d420c7=[{'FieldID':'s122_c113','IsChecked':1},{'FieldID':'s135_c126','IsChecked':1},{'FieldID':'s134_c125','IsChecked':1},{'FieldID':'s138_c129','IsChecked':1},{'FieldID':'s157_c147','IsChecked':1},{'FieldID':'s136_c127','IsChecked':1},{'FieldID':'s137_c128','IsChecked':1}]; SyrenisCookiePrivacyLink_213aea86-31e5-43f3-8d6b-e01ba0d420c7=1; SyrenisRunFirstCookieIDs_213aea86-31e5-43f3-8d6b-e01ba0d420c7=[]; SyrenisCookieConsentDate_213aea86-31e5-43f3-8d6b-e01ba0d420c7=1690764790690.9; SyrenisCustom_213aea86-31e5-43f3-8d6b-e01ba0d420c7=[]; Itv.cck={}; hdntl=exp=1690851239~acl=%2f10-4671-0009-001%2f*~data=hdntl,nohubplus~hmac=949240e593528c66072ee61d634214579c0502d3e989a5c384f5c036a72c866f; topid=DM:A790B970-776A-4954-A3DD-4DEAD3C2D927" --referer "https://www.itv.com/" "https://itvpnpdotcom.blue.content.itv.com/10-4671-0009-001/34/1/VAR028-HD-s/10-4671-0009-001_34_1_VAR028-HD-s.ism/.mpd?filter=%28%28type%3D%3D%22video%22%26%26DisplayHeight%3C%3D720%29%7C%7C%28type%21%3D%22video%22%29%29&hdnea=st%3D1690769096~exp%3D1690790696~acl%3D/10-4671-0009-001/%2A~data%3Dnohubplus~hmac%3D931594dac049db2db664785c81a1875172476bf3030cece490fdbdc20bc5ad82"
```

Trying to run with this gives an error about the `-N` not being supported, so I removed that (along with the `4` that follows it).

The result is:

```
generic] *~data=nohubplus~hmac=931594dac049db2db664785c81a1875172476bf3030cece490fdbdc20bc5ad82: Requesting header
WARNING: Falling back on generic information extractor.
[generic] *~data=nohubplus~hmac=931594dac049db2db664785c81a1875172476bf3030cece490fdbdc20bc5ad82: Downloading webpage
[generic] *~data=nohubplus~hmac=931594dac049db2db664785c81a1875172476bf3030cece490fdbdc20bc5ad82: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

What's interesting is that it's not even selecting the ITV extractor. Looking at the code, I suspect the regex isn't matching, but I'm not really sure how to change it so that it correctly identifies the ID and what-not.

PS. Just a general note: I was very confused as to the version being reported as `2021.12.17`, even though I eventually found that is expected. I ended up running from source inside a Docker container just to be sure I wasn't running out-of-date code. I guess I'm just wondering why the version isn't revving more quickly than it is, perhaps even generating a timestamp of the build rather than a hard-coded value...

**Comment by dirkf** [comment]
The plugin gave you a _yt-dlp_ command that you tried to run with yt-dl. You should probably be running yt-dlp instead.

Having said that, ITVX was supposed to be supported by both programs without any browser plugin stuff, but neither is working at the moment because of site issues, as you should have seen when you read **#30839**, where you would have learned how to find the relevant issue:

>[x] I've searched the bugtracker for similar bug reports including closed ones

Possibly, if the show you want is available in Scotland, you could try the URL for the show on STV: the STV site is different and hasn't been reported as broken.
