### ISSUE TITLE
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.facebook.com/stories/166832464814864/UzpfSVNDOjU4MDM4NzUyNDE3MjM0Mw==/?bucket_count=9&source=story_tray

### ISSUE THREAD

**Issue by bilalcontent** [ytdl-org/youtube-dl#32492]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
root@DESKTOP-825U10N:~# youtube-dl  --cookies ./cookies.txt  --verbose 'https://www.facebook.com/stories/166832464814864/UzpfSVNDOjU4MDM4NzUyNDE3MjM0Mw==/?bucket_count=9'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', './cookies.txt', '--verbose', 'https://www.facebook.com/stories/166832464814864/UzpfSVNDOjU4MDM4NzUyNDE3MjM0Mw==/?bucket_count=9']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ?bucket_count=9: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?bucket_count=9: Downloading webpage
[generic] ?bucket_count=9: Extracting information
ERROR: Unsupported URL: https://www.facebook.com/stories/166832464814864/UzpfSVNDOjU4MDM4NzUyNDE3MjM0Mw==/?bucket_count=9
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/generic.py", line 3489, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.facebook.com/stories/166832464814864/UzpfSVNDOjU4MDM4NzUyNDE3MjM0Mw==/?bucket_count=9
```

## Description

I'm trying to download facebook stories with youtube-dl. but it's returns unsupported url error.
I gone through many issues and articles but couldn't figure it out.
Firstly it gives error of invalid url error. i.e
https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Fstories%2F166832464814864%2FUzpfSVNDOjY3OTEyMjQxNjg4NDgzMA%3D%3D%2F%3Fbucket_count%3D9&_fb_noscript=1

but this issue is resolved by adding cookies in command. it fixed but now issue changed.
I tried simple facebook videos with this package and it's working. facebook reels are also downloading but unfortunately it does not downloading.

any help would be appreciated.

here is my command.

**youtube-dl  --cookies ./cookies.txt  --verbose 'https://www.facebook.com/stories/166832464814864/UzpfSVNDOjU4MDM4NzUyNDE3MjM0Mw==/?bucket_count=9'**

**Comment by dirkf** [comment]
Believe what it says: facebook.com/stories/... isn't supported.

Perhaps it could be if someone would implement it.

_yt-dlp_ doesn't know about these URLs either, so simple plagiarism won't be enough.

**Comment by baptx** [comment]
Related: https://github.com/ytdl-org/youtube-dl/issues/21899

**Comment by dirkf** [comment]
Let's leave that issue in the cemetery where it belongs.

Your [script](https://gist.github.com/baptx/8a1549d91996a37378faca159b3adc17) expects to find a `<video>` element with a `captureStream` (or `mozCaptureStream`) attribute. Probably that is dynamically constructed and not available to yt-dl.

The normal [site support procedure](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=site-support-request&projects=&template=2_site_support_request.md) will have to be adapted for these pages, since the content is transient.

To enable someone to implement the extraction, a requester will need to provide a HAR trace of a session opening the URL and starting to play the target video content, using the browser's development tools option.

The current extractor does know about `.../story.php?...` URLs FWIW.

**Comment by baptx** [comment]
@dirkf Yes, youtube-dl would do it another way, I just shared my script as an alternative solution that is not specific to a website like Facebook.
Usually, it is better to keep the original issue active instead of creating duplicates.

**Comment by dirkf** [comment]
Usually, I agree, and the posting guidelines say so. But that issue was (a) using an old version (b) closed as incomplete. Since this issue does exist, it's a better target: adding to the old one is "necroposting". Thorough maintenance would have identified the duplicate even if OP hadn't, thanks for IDing it; if your post had been made here but linking the defunct issue it would have been even more helpful.

Also FWIW, an Instagram story page has a media link in ld+json which should be found by the generic extractor. This obviously didn't happen with the FB stories for OP.
