### ISSUE TITLE
[Youtube] unable to extract player URL

### ISSUE THREAD

**Issue by 2blocksdown** [ytdl-org/youtube-dl#32500]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=XYV8Zt2k0RQ']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35 - OpenSSL 3.0.2 15 Mar 2022 - glibc 2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] XYV8Zt2k0RQ: Downloading webpage
[youtube] XYV8Zt2k0RQ: Downloading API JSON
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/lj/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 825, in wrapper
    return func(self, *args, **kwargs)
  File "/home/lj/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 846, in __extract_info
    ie_result = ie.extract(url)
  File "/home/lj/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 535, in extract
    ie_result = self._real_extract(url)
  File "/home/lj/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 2119, in _real_extract
    self._sort_formats(formats)
  File "/home/lj/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1375, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

This occurs randomly with all youtube video urls for me. Sometimes the download works, but sometimes the above error happens.

**Comment by vince-666** [comment]
Yes, I get this problem often. However when I get this problem and I terminate the download by CTRL C, remove the partial download and start again, the problem disappears.  
Today as soon as I started to download using the youtube link with “-f 22” option, I get the same/similar problem consistently and the problem is repeatable. However the download works fine.
yt-dlp_linux -f 22 https://www.youtube.com/watch?v=0w_ZHcvfm4U

If I use the same youtube link and do not specify any option (without -f 22), I do not get any warning or error. I do not get any error if I use -f 18 option too. 
yt-dlp_linux -f 18 https://www.youtube.com/watch?v=0w_ZHcvfm4U
yt-dlp_linux https://www.youtube.com/watch?v=0w_ZHcvfm4U
The above commands works just fine without any warning/s.

This is the output of executing the above command with “-vU” option.
<========================================================>

$ yt-dlp_linux -vU -f 22 https://www.youtube.com/watch?v=0w_ZHcvfm4U
[debug] Command-line config: ['-vU', '-f', '22', 'https://www.youtube.com/watch?v=0w_ZHcvfm4U']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (linux_exe)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.4.0-42-generic-x86_64-with-glibc2.31 (OpenSSL 3.1.1 30 May 2023, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 0556fff82db6c942a5dfbb9583e2896013847b28b95186b3800f730a8d5e0c0a
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=0w_ZHcvfm4U
[youtube] 0w_ZHcvfm4U: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] 0w_ZHcvfm4U: Downloading ios player API JSON
[youtube] 0w_ZHcvfm4U: Downloading android player API JSON
[youtube] 0w_ZHcvfm4U: Downloading iframe API JS
[youtube] 0w_ZHcvfm4U: Downloading player 3cd2d050
[youtube] 0w_ZHcvfm4U: Downloading web player API JSON
[youtube] 0w_ZHcvfm4U: Downloading m3u8 information
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] 0w_ZHcvfm4U: Downloading initial data API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] 0w_ZHcvfm4U: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr5---sn-aigzrnss.googlevideo.com/videoplayback?expire=1691884765&ei=fcjXZMzCOO2vmLAPgteD-A0&ip=80.229.8.200&id=o-ACq51BIshId_IZahA5qFHdd_tTDgmZhoO4koTzChNfvB&itag=22&source=youtube&requiressl=yes&mh=C6&mm=31%2C26&mn=sn-aigzrnss%2Csn-5hne6nsk&ms=au%2Conr&mv=m&mvi=5&pl=22&initcwndbps=1318750&spc=UWF9f9XcPZzOqh1Hd2FlNRC7Le7_TJE&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=2092.303&lmt=1691730524679558&mt=1691862796&fvip=4&fexp=24007246%2C24363391&beids=24350018&c=ANDROID&txp=3308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMDr8CoGFvuIGQqwN6KKDCR430XGhUSs1ZcKWD-dlOEKAiEAsoy1wj3fcQUvffy2SFpUSTjOHqXB4QhnNJyXwua-bTE%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKXk7v38c_xGNHeuGKnUgvIhuuuc0-CvB_stBcU9zws8AiEAjyZJzGXKhz321frhs2hG5rsqIlzfHT1zbXZQAcyICsM%3D"
[download] Destination: Se multiplican los AVISTAMIENTOS DE NAVES NO HUMANAS en el mundo [0w_ZHcvfm4U].mp4
[download] 100% of  384.38MiB in 00:01:32 at 4.17MiB/s

**Comment by nicolaasjan** [comment]
@vince-666 

> yt-dlp_linux -vU -f 22 [Se multiplican los AVISTAMIENTOS DE NAVES NO HUMANAS en el mundo](https://www.youtube.com/watch?v=0w_ZHcvfm4U)
> [debug] Command-line config: ['-vU', '-f', '22', 'https://www.youtube.com/watch?v=0w_ZHcvfm4U']
> [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version stable@2023.07.06 [b532a3481] (linux_exe)

You are _not_ using **youtube-dl**... 😉

But **yt-dlp** is supposed to have fixed [this issue](https://github.com/yt-dlp/yt-dlp/issues/7594) in the [nightly build](https://github.com/yt-dlp/yt-dlp-nightly-builds). 🙂

You can use `yt-dlp_linux --update-to nightly` if you have at least yt-dlp 2023.03.03 installed.

```
yt-dlp_linux -vU -f 22 https://www.youtube.com/watch?v=0w_ZHcvfm4U
[debug] Command-line config: ['-vU', '-f', '22', 'https://www.youtube.com/watch?v=0w_ZHcvfm4U']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.12.235909 [339c339fe] (linux_exe)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.4.0-155-generic-x86_64-with-glibc2.31 (OpenSSL 3.1.2 1 Aug 2023, glibc 2.31)
[debug] exe versions: ffmpeg N-111711-gd295b6b693-Nico-20230808 (fdk,setts), ffprobe N-111711-gd295b6b693-Nico-20230808, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1860 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.08.12.235909, Current version: nightly@2023.08.12.235909
Current Build Hash: 2da48d4646431e8a8d2871f180e36dad6a83b0e548d8758023f516918b949aef
yt-dlp is up to date (nightly@2023.08.12.235909)
[youtube] Extracting URL: https://www.youtube.com/watch?v=0w_ZHcvfm4U
[youtube] 0w_ZHcvfm4U: Downloading webpage
[youtube] 0w_ZHcvfm4U: Downloading ios player API JSON
[youtube] 0w_ZHcvfm4U: Downloading android player API JSON
[youtube] 0w_ZHcvfm4U: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] 0w_ZHcvfm4U: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr3---sn-5hnednsz.googlevideo.com/videoplayback?expire=1691927652&ei=BHDYZP-7It_Cx_AP1tOVqAo&ip=94.213.6.2yt-dlp_linux -vU -f 22 https://www.youtube.com/watch?v=0w_ZHcvfm4U
[debug] Command-line config: ['-vU', '-f', '22', 'https://www.youtube.com/watch?v=0w_ZHcvfm4U']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.12.235909 [339c339fe] (linux_exe)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.4.0-155-generic-x86_64-with-glibc2.31 (OpenSSL 3.1.2 1 Aug 2023, glibc 2.31)
[debug] exe versions: ffmpeg N-111711-gd295b6b693-Nico-20230808 (fdk,setts), ffprobe N-111711-gd295b6b693-Nico-20230808, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1860 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.08.12.235909, Current version: nightly@2023.08.12.235909
Current Build Hash: 2da48d4646431e8a8d2871f180e36dad6a83b0e548d8758023f516918b949aef
yt-dlp is up to date (nightly@2023.08.12.235909)
[youtube] Extracting URL: https://www.youtube.com/watch?v=0w_ZHcvfm4U
[youtube] 0w_ZHcvfm4U: Downloading webpage
[youtube] 0w_ZHcvfm4U: Downloading ios player API JSON
[youtube] 0w_ZHcvfm4U: Downloading android player API JSON
[youtube] 0w_ZHcvfm4U: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] 0w_ZHcvfm4U: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr3---sn-5hnednsz.googlevideo.com/videoplayback?expire=1691927652&ei=BHDYZP-7It_Cx_AP1tOVqAo&ip=<Redacted>&id=o-AM99deF8HbAu2Xtl_jM_zPsEjLOYMUuQ8dvX6hnKYQ8d&itag=22&source=youtube&requiressl=yes&mh=C6&mm=31%2C26&mn=sn-5hnednsz%2Csn-4g5e6nz7&ms=au%2Conr&mv=m&mvi=3&pl=14&initcwndbps=2652500&spc=UWF9f8Hoy1j_u4dM7aCmBKGv1VCdAys&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=2092.303&lmt=1691730524679558&mt=1691905757&fvip=1&fexp=24007246%2C51000023&beids=24350018&c=ANDROID&txp=3308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgVIbR3Tvc_fnkDd4uosFL7mLX2kBa25n2Id2BLYWssQMCICKmCOffoj2iRItJgBcnJvdVu_9-MlxHbd3q3w0Vw18W&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgPhkqStNnn2fuvt2phiPNw6iPOh3xpqKkSF9LV6dcvq8CIQCEWfGK2FErmYAzZ5gyC9i5QdNfZ8cCTKrmZvImAFG9Xw%3D%3D"
[download] Destination: Se multiplican los AVISTAMIENTOS DE NAVES NO HUMANAS en el mundo [0w_ZHcvfm4U].mp4
[download] 100% of  384.38MiB in 00:00:37 at 10.27MiB/s
36&id=o-AM99deF8HbAu2Xtl_jM_zPsEjLOYMUuQ8dvX6hnKYQ8d&itag=22&source=youtube&requiressl=yes&mh=C6&mm=31%2C26&mn=sn-5hnednsz%2Csn-4g5e6nz7&ms=au%2Conr&mv=m&mvi=3&pl=14&initcwndbps=2652500&spc=UWF9f8Hoy1j_u4dM7aCmBKGv1VCdAys&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=2092.303&lmt=1691730524679558&mt=1691905757&fvip=1&fexp=24007246%2C51000023&beids=24350018&c=ANDROID&txp=3308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgVIbR3Tvc_fnkDd4uosFL7mLX2kBa25n2Id2BLYWssQMCICKmCOffoj2iRItJgBcnJvdVu_9-MlxHbd3q3w0Vw18W&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgPhkqStNnn2fuvt2phiPNw6iPOh3xpqKkSF9LV6dcvq8CIQCEWfGK2FErmYAzZ5gyC9i5QdNfZ8cCTKrmZvImAFG9Xw%3D%3D"
[download] Destination: Se multiplican los AVISTAMIENTOS DE NAVES NO HUMANAS en el mundo [0w_ZHcvfm4U].mp4
[download] 100% of  384.38MiB in 00:00:37 at 10.27MiB/s

```

Also, it is advised to update your ffmpeg (and ffprobe of course).
You can get daily builds [here](https://github.com/yt-dlp/FFmpeg-Builds/releases).

**Comment by dirkf** [comment]
The consent issue is #32499.

**Comment by potmo** [comment]
I can confirm `yt-dlp` version `stable@2023.07.06` works for me with 
python `Python 3.11.5 (CPython x86_64 64bit) - macOS-13.4.1-x86_64-i386-64bit (OpenSSL 3.1.2 1 Aug 2023)`
ffmpeg `ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4`
macOSX `Ventura 13.4.1 (c)`

but not 
youtube-dl version `2021.12.17`.

Both installed with `brew`

**Comment by ATLAbanana35** [comment]
The website for python version is just down
