### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by LloydLynx** [ytdl-org/youtube-dl#32508]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **stable@2023.07.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

```
[james@voidD620 ~]$ yt-dlp "https://www.youtube.com/watch?v=otB7OgkpdWI" --no-config --verbose
[debug] Command-line config: ['https://www.youtube.com/watch?v=otB7OgkpdWI', '--no-config', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.4 (CPython x86_64 64bit) - Linux-6.3.13_1-x86_64-with-glibc2.36 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 4.4.4 (setts), ffprobe 4.4.4, phantomjs 2.1.1
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=otB7OgkpdWI
[youtube] otB7OgkpdWI: Downloading webpage
[youtube] otB7OgkpdWI: Downloading ios player API JSON
[youtube] otB7OgkpdWI: Downloading android player API JSON
[youtube] otB7OgkpdWI: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] otB7OgkpdWI: Downloading 1 format(s): 616+251
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1692163326/ei/ngjcZNaOGdX5ir4P3vmC8AM/ip/97.127.13.74/id/a2d07b3a09297562/itag/616/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D404480055%3Bdur%3D1035.234%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1692128956920672/hls_chunk_host/rr1---sn-jxou0gtapo3-hn2e.googlevideo.com/mh/SQ/mm/31,29/mn/sn-jxou0gtapo3-hn2e,sn-vgqsknzd/ms/au,rdu/mv/m/mvi/1/pl/17/initcwndbps/933750/vprv/1/playlist_type/DVR/dover/13/txp/3308224/mt/1692141198/fvip/1/short_key/1/keepalive/yes/fexp/24007246,51000022/beids/24350017/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,vprv,playlist_type/sig/AOq0QJ8wRgIhAN7pKbVa4XHsBa_y-jWN-bSXdAa6WeagVWCWwzt3kizkAiEAzlfN57NgwFi92q7Otm4WvBxou2FBPZ7bwhCJeS7lkPM%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRQIgSheI8cT2zPtsduGu4wo0Jt2XuBQXjsWvhqZeH6kqzrcCIQCP_vCbeWCCLxgE1rFBFSK7bMQOKftuV0E_GPlImnho9Q%3D%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3345, in process_info
    partial_success, real_download = self.dl(fname, new_info)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3084, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 461, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/hls.py", line 77, in real_download
    urlh = self.ydl.urlopen(self._prepare_url(info_dict, man_url))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3863, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

```
[james@voidD620 ~]$ yt-dlp -U --no-config --verbose
[debug] Command-line config: ['-U', '--no-config', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.4 (CPython x86_64 64bit) - Linux-6.3.13_1-x86_64-with-glibc2.36 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 4.4.4 (setts), ffprobe 4.4.4, phantomjs 2.1.1
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
```

## Description

I first noticed the issue by giving yt-dlp the URL without any flags. yt-dlp can't download https://www.youtube.com/watch?v=otB7OgkpdWI with a 404 error, but it can download other videos fine. The video plays fine in Qutebrowser. wget reaches the URL, so the problem is deeper than page access. I don't understand much beyond this so I can't suggest a solution.

**Comment by dirkf** [comment]
#30839: "... if you were actually running _yt-dlp_ ..."
