### ISSUE TITLE
unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by heishuaiguo** [ytdl-org/youtube-dl#32528]
yt-dlp --verbose 'https://www.youtube.com/watch?v=EXD-AMXeaQY'
[debug] Command-line config: ['--verbose', 'https://www.youtube.com/watch?v=EXD-AMXeaQY']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.8.8rc1 (CPython x86_64 64bit) - macOS-10.16-x86_64-i386-64bit (OpenSSL 1.1.1i  8 Dec 2020)
[debug] exe versions: rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'}
[debug] Loaded 1786 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=EXD-AMXeaQY
[youtube] EXD-AMXeaQY: Downloading webpage
[youtube] EXD-AMXeaQY: Downloading android player API JSON
[debug] Loading youtube-nsig.c153b631 from cache
[debug] [youtube] Decrypted nsig ZpqTvGJBksbsaGkP => fLW8WyEz3WnCgQ
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] EXD-AMXeaQY: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr5---sn-oguesn6r.googlevideo.com/videoplayback?expire=1692966640&ei=kEroZISlJZSPs8IP2-eaiAo&ip=133.125.59.33&id=o-ADZ_67bwBY-ximbLttmr7zgwxPsqc6navvcnvW8Qt7yS&itag=22&source=youtube&requiressl=yes&mh=2x&mm=31%2C26&mn=sn-oguesn6r%2Csn-3pm76nes&ms=au%2Conr&mv=m&mvi=5&pl=19&initcwndbps=1027500&spc=UWF9f8AInRRjm3vvsuUC5sbNMwxAfhyCfseq-rO6nQ&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=632.952&lmt=1692322396150037&mt=1692944712&fvip=2&fexp=24007246%2C51000024&beids=24350018&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALB6PFEVEpjNKbJHL1WpfFZy0NdTl63gevx2CGgHqHKOAiEAh2EcBLi50OajGY9ze8uA-c_7brvk0JgTKXHaF3feeO0%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgVVndcmHUZ4h49LWHfzUNlDNX-ai1CD5AJ0E4zdhCjiYCIQCEtb8D1L3WagrlQ0u0vIlImMxDH-cZ77aS_pymyGlPrg%3D%3D"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3248, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2971, in dl
    return fd.download(name, new_info, subtitle)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/downloader/http.py", line 376, in real_download
    establish_connection()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/downloader/http.py", line 129, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3743, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by heishuaiguo** [comment]
Sorry, it's been solved: python3 -m pip install -U yt-dlp

**Comment by dirkf** [comment]
Also, #30839: "... if you were actually using _yt-dlp_...".
