### ISSUE TITLE
Please update website : https://www.youku.tv/. Thanks !

### ISSUE THREAD

**Issue by jayt1990** [ytdl-org/youtube-dl#32524]
## Checklist

- [ ] I'm reporting a feature request
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

**Comment by jayt1990** [comment]
Please update website : https://www.youku.tv/. Thanks !

**Comment by dirkf** [comment]
How? Why?

Maybe you meant to open a broken site support issue, with the required supporting information?

**Comment by Vangelis66** [comment]
FWIW:

`www.youku.com` is the **Chinese** version of **youku**, and there's already an IE for that, `youku.py`: 
```python
class YoukuIE(InfoExtractor):
    IE_NAME = 'youku'
    IE_DESC = '优酷'
    _VALID_URL = r'''(?x)
        (?:
            https?://(
                (?:v|player)\.youku\.com/(?:v_show/id_|player\.php/sid/)|
                video\.tudou\.com/v/)|
            youku:)
        (?P<id>[A-Za-z0-9]+)(?:\.html|/v\.swf|)
    '''
```
I can't check `www.youku.com` in `yt-dl`  and in my browser, because it's mostly geo-blocked for **non-Chinese** IPs... 

https://github.com/ytdl-org/youtube-dl/issues?q=youku.com+is%3Aopen

and 

https://github.com/ytdl-org/youtube-dl/issues?q=youku.com+is%3Aclosed

both suggest the `youku.com` IE **might be broken** (up for investigation by _Chinese_ natives) ... 

OP is asking for support of `www.youku.tv`, which is the **international** version of **youku** 😜 ; below URI:

https://www.youku.tv/v/v_show/id_XNTk3NTM3NTU4OA==.html

**plays fine** (**no account** required, **no DRM** enforced) in my South European location; but there's a catch: the first time you load `www.youku.tv` in your browser, you're presented with a "smart captcha" challenge (please, slide [towards the right] to verify [you're not a bot]): 

![sc](https://github.com/ytdl-org/youtube-dl/assets/9669492/adfcf6ed-1b40-41f2-ad36-2e1b355c2188)

not sure if/how `yt-dl` will be able to cope with that...

FTR: 
```console
yt-dl -vF "https://www.youku.tv/v/v_show/id_XNTk3NTM3NTU4OA==.html" => 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', '.\\FFmpeg', '--external-downloader-args', '-v 8 -stats', '-vF', 'https://www.youku.tv/v/v_show/id_XNTk3NTM3NTU4OA==.html']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2023.08.04.2154
[debug] Lazy loading extractors enabled
[debug] Single file build
[debug] Python 3.4.10 (CPython x86 32bit) - Windows-Vista-6.0.6003-SP2 - OpenSSL 1.0.2k  26 Jan 2017
[debug] exe versions: ffmpeg n6.1-dev-1700-N-111584-ga4e6168, ffprobe n6.1-dev-1700-N-111584-ga4e6168, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] id_XNTk3NTM3NTU4OA==: Requesting header
WARNING: Falling back on generic information extractor.
[generic] id_XNTk3NTM3NTU4OA==: Downloading webpage
[generic] id_XNTk3NTM3NTU4OA==: Extracting information
WARNING: [generic] id_XNTk3NTM3NTU4OA==: Failed to parse JSON Invalid control character at: line 12 column 1367 (char 1817)
ERROR: Unsupported URL: https://www.youku.tv/v/v_show/id_XNTk3NTM3NTU4OA==.html
Traceback (most recent call last):
  File "C:\Python3410-32\yt-dl_pycompile\youtube_dl\YoutubeDL.py", line 859, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Python3410-32\yt-dl_pycompile\youtube_dl\YoutubeDL.py", line 955, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Python3410-32\yt-dl_pycompile\youtube_dl\extractor\common.py", line 565, in extract
    ie_result = self._real_extract(url)
  File "C:\Python3410-32\yt-dl_pycompile\youtube_dl\extractor\generic.py", line 3704, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.youku.tv/v/v_show/id_XNTk3NTM3NTU4OA==.html
```
> meant to open a **broken site** support issue,

more like a `Site Support Request` 😜 (hopefully, a "fixed" `youku.py` can handle both `*.youku.com` and `*.youku.tv` URIs ) ...

**Comment by jayt1990** [comment]
> FWIW:
> 
> `www.youku.com` is the **Chinese** version of **youku**, and there's already an IE for that, `youku.py`:
> 
> ```python
> class YoukuIE(InfoExtractor):
>     IE_NAME = 'youku'
>     IE_DESC = '优酷'
>     _VALID_URL = r'''(?x)
>         (?:
>             https?://(
>                 (?:v|player)\.youku\.com/(?:v_show/id_|player\.php/sid/)|
>                 video\.tudou\.com/v/)|
>             youku:)
>         (?P<id>[A-Za-z0-9]+)(?:\.html|/v\.swf|)
>     '''
> ```
> 
> I can't check `www.youku.com` in `yt-dl` and in my browser, because it's mostly geo-blocked for **non-Chinese** IPs...
> 
> https://github.com/ytdl-org/youtube-dl/issues?q=youku.com+is%3Aopen
> 
> and
> 
> https://github.com/ytdl-org/youtube-dl/issues?q=youku.com+is%3Aclosed
> 
> both suggest the `youku.com` IE **might be broken** (up for investigation by _Chinese_ natives) ...
> 
> OP is asking for support of `www.youku.tv`, which is the **international** version of **youku** 😜 ; below URI:
> 
> https://www.youku.tv/v/v_show/id_XNTk3NTM3NTU4OA==.html
> 
> **plays fine** (**no account** required, **no DRM** enforced) in my South European location; but there's a catch: the first time you load `www.youku.tv` in your browser, you're presented with a "smart captcha" challenge (please, slide [towards the right] to verify [you're not a bot]):
> 
> ![sc](https://user-images.githubusercontent.com/9669492/262811100-adfcf6ed-1b40-41f2-ad36-2e1b355c2188.png)
> 
> not sure if/how `yt-dl` will be able to cope with that...
> 
> FTR:
> 
> ```
> yt-dl -vF "https://www.youku.tv/v/v_show/id_XNTk3NTM3NTU4OA==.html" => 
> 
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['--ffmpeg-location', '.\\FFmpeg', '--external-downloader-args', '-v 8 -stats', '-vF', 'https://www.youku.tv/v/v_show/id_XNTk3NTM3NTU4OA==.html']
> [debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
> [debug] youtube-dl version 2023.08.04.2154
> [debug] Lazy loading extractors enabled
> [debug] Single file build
> [debug] Python 3.4.10 (CPython x86 32bit) - Windows-Vista-6.0.6003-SP2 - OpenSSL 1.0.2k  26 Jan 2017
> [debug] exe versions: ffmpeg n6.1-dev-1700-N-111584-ga4e6168, ffprobe n6.1-dev-1700-N-111584-ga4e6168, phantomjs 2.1.1, rtmpdump 2.4
> [debug] Proxy map: {}
> [generic] id_XNTk3NTM3NTU4OA==: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] id_XNTk3NTM3NTU4OA==: Downloading webpage
> [generic] id_XNTk3NTM3NTU4OA==: Extracting information
> WARNING: [generic] id_XNTk3NTM3NTU4OA==: Failed to parse JSON Invalid control character at: line 12 column 1367 (char 1817)
> ERROR: Unsupported URL: https://www.youku.tv/v/v_show/id_XNTk3NTM3NTU4OA==.html
> Traceback (most recent call last):
>   File "C:\Python3410-32\yt-dl_pycompile\youtube_dl\YoutubeDL.py", line 859, in wrapper
>     return func(self, *args, **kwargs)
>   File "C:\Python3410-32\yt-dl_pycompile\youtube_dl\YoutubeDL.py", line 955, in __extract_info
>     ie_result = ie.extract(url)
>   File "C:\Python3410-32\yt-dl_pycompile\youtube_dl\extractor\common.py", line 565, in extract
>     ie_result = self._real_extract(url)
>   File "C:\Python3410-32\yt-dl_pycompile\youtube_dl\extractor\generic.py", line 3704, in _real_extract
>     raise UnsupportedError(url)
> youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.youku.tv/v/v_show/id_XNTk3NTM3NTU4OA==.html
> ```
> 
> > meant to open a **broken site** support issue,
> 
> more like a `Site Support Request` 😜 (hopefully, a "fixed" `youku.py` can handle both `*.youku.com` and `*.youku.tv` URIs ) ...

Yes please update youku.tv into [youku] extractor. Thanks so much!

**Comment by Vangelis66** [comment]
@jayt1990 

Please, there was no need **to quote the bulk of my comment**, especially since it was **immediately preceding yours** 😉 ...

I can also understand English not being your "forte", but, be that as it may, you should have started by first reading _fully_ the PINNED issue #30839 and then proceeding to file a proper `Site Support Request` (by complying fully to its template), if you were so inclined...

There's currently only one person taking on "maintainer duties" and it's hard for him to process `incomplete` issue reports; I hope you do understand that 😄 ...

Regards.

**Comment by dirkf** [comment]
See https://github.com/yt-dlp/yt-dlp/issues/8058
