### ISSUE TITLE
youtube-dl fresh install broken

### ISSUE THREAD

**Issue by bryanbutler2** [ytdl-org/youtube-dl#32532]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

titan% youtube-dl -v --extract-audio --audio-format mp3 0lDui3tDaWM
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/youtube-dl", line 33, in <module>
    sys.exit(load_entry_point('youtube-dl==2021.12.17', 'console_scripts', 'youtube-dl')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/bin/youtube-dl", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for youtube-dl

## Description

WRITE DESCRIPTION HERE

Fresh install of youtube-dl via homebrew on macOS Ventura 13.4.

The install goes fine; output at the end:
...
Pruned 0 symbolic links and 6 directories from /opt/homebrew
==> Caveats
==> youtube-dl
Bash completion has been installed to:
  /opt/homebrew/etc/bash_completion.d

(no error messages).

But executing youtube-dl results in the error message above.  The fundamental error seems to be the last message - the metadata for the version number seems to be missing?

I tried a full uninstall and reinstall via homebrew, with the same results.

**Comment by bryanbutler2** [comment]
I found my problem - it was a python3 issue that needed a wraparound for macOS Monterey that is no longer needed for Ventura.  Closing the ticket.
