### ISSUE TITLE
WARNING: [youtube] Unable to decode n-parameter (again...)

### ISSUE THREAD

**Issue by nicolaasjan** [ytdl-org/youtube-dl#32534]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2023.08.04**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```shell
youtube-dl -v -f 299+140 --ignore-config "https://www.youtube.com/watch?v=aKAcT2X9lkU"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '299+140', '--ignore-config', 'https://www.youtube.com/watch?v=aKAcT2X9lkU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2023.08.04
[debug] Lazy loading extractors enabled
[debug] Single file build
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-156-generic-x86_64-with-glibc2.29 - OpenSSL 1.1.1f  31 Mar 2020 - glibc 2.31
[debug] exe versions: ffmpeg N-111711-gd295b6b693-Nico-20230808, ffprobe N-111711-gd295b6b693-Nico-20230808, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] aKAcT2X9lkU: Downloading webpage
[youtube] aKAcT2X9lkU: Downloading API JSON
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (expected string or bytes-like object Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl.orig/youtube_dl/extractor/youtube.py", line 1679, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/usr/local/bin/youtube-dl.orig/youtube_dl/extractor/youtube.py", line 1644, in _extract_n_function
    player_id = self._extract_player_info(player_url)
  File "/usr/local/bin/youtube-dl.orig/youtube_dl/extractor/youtube.py", line 1476, in _extract_player_info
    id_m = re.search(player_re, player_url)
  File "/usr/lib/python3.8/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
)
[youtube] aKAcT2X9lkU: Downloading API JSON
[debug] Invoking downloader on 'https://rr4---sn-5hne6nsd.googlevideo.com/videoplayback?expire=1693255255&ei=97HsZMHZLJaPx_APsrqD0A8&ip=<REDACTED>&id=o-AAb-paIYXkfkSkfIHlGqN92XFKIfC7lQ3AUNhFbG8QK7&itag=299&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C308%2C315%2C394%2C395%2C396%2C397%2C398%2C399%2C400%2C401&source=youtube&requiressl=yes&mh=JT&mm=31%2C26&mn=sn-5hne6nsd%2Csn-4g5ednds&ms=au%2Conr&mv=m&mvi=4&pl=14&initcwndbps=2540000&spc=UWF9f-CDJ8nOjOCutQrgKsxpgvzTiruX9kuoCINCDw&vprv=1&svpuc=1&mime=video%2Fmp4&ns=PUfX0awdKfxYbsSyFFBHNgEP&gir=yes&clen=284760251&dur=804.416&lmt=1693118848928099&mt=1693233449&fvip=4&keepalive=yes&fexp=24007246%2C51000023&c=WEB&txp=5532434&n=47IksHcAZBwAdfkckY&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAJWpYTZwu6LngY_oth5Xqmw1HXceo8ldmgHe39_gknYKAiA0XDjgcd6rsyCkgkSiBY2ktinKnTEqUJvMUKCCXTUdYw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAPaOLNmGKd44DXdwjndr7aPQAm1L9kHIjqtm_jdRb1fLAiARn3XoAqq_SzrjL3c2W6H3H2mzk3PwIO81gBQh1Q37_Q%3D%3D'
[dashsegments] Total fragments: 28
[download] Destination: Evidence For The Biggest Impact Crater on Earth At 520 km Across-aKAcT2X9lkU.f299.mp4
[download]   0.3% of ~280.00MiB at 42.84KiB/s ETA 01:51:15^C
ERROR: Interrupted by user

```

## Description

`Unable to decode n-parameter: download likely to be throttled`
And it sure is...
`[download]   0.3% of ~280.00MiB at 42.84KiB/s ETA 01:51:15^C`

**Comment by nicolaasjan** [comment]
From yt-dlp verbose log:

```shell
[youtube] aKAcT2X9lkU: Downloading player c153b631
[debug] Saving youtube-nsig.c153b631 to cache
[debug] [youtube] Decrypted nsig xLOrjnf4nBSn-xZu => TGN_3foSsKSJZQ

```

There the download went fine (~10MiB/s)

**Comment by dirkf** [comment]
```console
youtube-dl-20230718 "https://www.youtube.com/watch?v=aKAcT2X9lkU"
[youtube] aKAcT2X9lkU: Downloading webpage
WARNING: Unable to download webpage: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found
[youtube] aKAcT2X9lkU: Downloading API JSON
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (expected string or buffer Traceback (most recent call last):
  File "youtube-dl-20230718/youtube_dl/extractor/youtube.py", line 1679, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "youtube-dl-20230718/youtube_dl/extractor/youtube.py", line 1644, in _extract_n_function
    player_id = self._extract_player_info(player_url)
  File "youtube-dl-20230718/youtube_dl/extractor/youtube.py", line 1476, in _extract_player_info
    id_m = re.search(player_re, player_url)
  File "/home/df/miniconda3/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer
)
...
```
I expect that, because of #32499, `player_url` isn't being set, and so the search for the player ID crashes.
