### ISSUE TITLE
[xhamster] An extractor error has occurred. (caused by KeyError('videoModel',)

### ISSUE THREAD

**Issue by Womble7** [ytdl-org/youtube-dl#32539]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: ['--prefer-free-formats', '--add-header', 'Cookie:']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-a', '10.txt']
[debug] Adding header from command line option Cookie:
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17 (single file build)
** This build is unofficial daily builds, provided for ease of use.
** Please do not ask for any support.
[debug] Python 3.6.8 (CPython x86_64 64bit) - Linux-4.18.0-477.21.1.el8_8.x86_64-x86_64-with-centos-8.8-Green_Obsidian - OpenSSL 1.1.1k  FIPS 25 Mar 2021 - glibc 2.3.4
[debug] exe versions: ffmpeg 4.2.9, ffprobe 4.2.9
[debug] Proxy map: {}
[XHamster] xhU8Xan: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('videoModel',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 535, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/xhamster.py", line 158, in _real_extract
    video = initials['videoModel']
KeyError: 'videoModel'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 535, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/xhamster.py", line 158, in _real_extract
    video = initials['videoModel']
KeyError: 'videoModel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 825, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 846, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 548, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('videoModel',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Extractor now fails - possibly due to a website update. Working fine until approx. 25th August 2023.
Removed pre-packaged version and built nightly release to test. Fault present in youtube-dl-2023.09.01.334 nightly release.

**Comment by dirkf** [comment]
Yet you will have to provide an incriminating test URL ... !

**Comment by Womble7** [comment]
Example URL: https://xhamster.com/videos/young-blond-exhibitionist-wife-walking-nude-around-stowmarket-england-xhA4jwM

**Comment by dirkf** [comment]
The site is returning a captcha page or similar for the UA sent by yt-dl. These worked for me (for Windows _cmd_ change `'...' to `"..."`):
`--user-agent Mozilla`
`--user-agent '10000'`
`--user-agent ''`
`--user-agent Mozilla Firefox 110'`

**Comment by Womble7** [comment]
youtube-dl --user-agent Mozilla -a batch.txt works. Thank you.

**Comment by osiris000** [comment]
Fix in xhamster.py

import youtube_dl.utils
youtube_dl.utils.std_headers['User-Agent'] = 'Mozilla'
