### ISSUE TITLE
uploader ID → RegexNotFoundError('Unable to extract %s' % _name)

### ISSUE THREAD

**Issue by WGroleau** [ytdl-org/youtube-dl#32537]
## Checklist

- [x ] I'm reporting a new site support request
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that none of provided URLs violate any copyrights  ??
- [x ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://youtube.c0m/watch?v=RYYQnUFgHsQ 
- Single video: https://youtu.be/RYYQnUFgHsQ

## Description
First URI gets "no match found" (issue #32220).
Second gets:

```
WGroleau@MBP TEMP % youtube-dl  --keep-fragments --verbose https://youtu.be/RYYQnUFgHsQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--keep-fragments', '--verbose', 'https://youtu.be/RYYQnUFgHsQ']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.13 (CPython) - macOS-13.5.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[youtube] RYYQnUFgHsQ: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by dirkf** [comment]
You have the wrong template. This one is to request support for a new site. Since the log contains `[youtube]` this site (surprisingly, considering the name of the program) is supported.

The message "no match found" probably means that you have the _zsh_ shell (especially given macOS) but didn't quote the "URL" containing `?`.

See #30839 regarding the `uploader id` error and also duplicate issues in general, which both of these are.
