### ISSUE TITLE
youtube: Unable to extract player URL

### ISSUE THREAD

**Issue by andreas-gruenbacher** [ytdl-org/youtube-dl#32540]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=gav66byYJMw']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Single file build
[debug] Python 3.11.4 (CPython x86_64 64bit) - Linux-6.4.12-200.fc38.x86_64-x86_64-with-glibc2.37 - OpenSSL 3.0.9 30 May 2023 - glibc 2.37
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[youtube] gav66byYJMw: Downloading webpage
[youtube] gav66byYJMw: Downloading API JSON
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/$USER/git/youtube-dl/./youtube-dl/youtube_dl/YoutubeDL.py", line 859, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$USER/git/youtube-dl/./youtube-dl/youtube_dl/YoutubeDL.py", line 955, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/$USER/git/youtube-dl/./youtube-dl/youtube_dl/extractor/common.py", line 565, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$USER/git/youtube-dl/./youtube-dl/youtube_dl/extractor/youtube.py", line 2128, in _real_extract
    self._sort_formats(formats)
  File "/home/$USER/git/youtube-dl/./youtube-dl/youtube_dl/extractor/common.py", line 1444, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I cannot download any youtube videos at the moment; youtube-dl fails to extract the player URL.

**Comment by andreas-gruenbacher** [comment]
Providing the following user agent:
```
--user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
```
fixes the issue, with following output:
```
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--user-agent', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36', '-v', 'https://www.youtube.com/watch?v=psyv8G0mk3U']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Single file build
[debug] Python 3.11.4 (CPython x86_64 64bit) - Linux-6.4.12-200.fc38.x86_64-x86_64-with-glibc2.37 - OpenSSL 3.0.9 30 May 2023 - glibc 2.37
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[youtube] psyv8G0mk3U: Downloading webpage
[youtube] psyv8G0mk3U: Downloading API JSON
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (expected string or bytes-like object, got 'NoneType' Traceback (most recent call last):
  File "/home/$USER/git/youtube-dl/./youtube-dl/youtube_dl/extractor/youtube.py", line 1679, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$USER/git/youtube-dl/./youtube-dl/youtube_dl/extractor/youtube.py", line 1644, in _extract_n_function
    player_id = self._extract_player_info(player_url)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$USER/git/youtube-dl/./youtube-dl/youtube_dl/extractor/youtube.py", line 1476, in _extract_player_info
    id_m = re.search(player_re, player_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/__init__.py", line 176, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
)
[youtube] psyv8G0mk3U: Downloading API JSON
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://rr4---sn-h0jeln7l.googlevideo.com/videoplayback?expire=1693695459&ei=gmnzZNfXOuGG6dsP6N20uAs&ip=84.115.217.88&id=o-AJOsd9Kb90JefTK0HiR6Qw3UVeGXhpcQo2JoaghYj5zl&itag=135&aitags=133%2C134%2C135%2C160%2C242%2C243%2C244%2C278&source=youtube&requiressl=yes&mh=0b&mm=31%2C26&mn=sn-h0jeln7l%2Csn-5hneknee&ms=au%2Conr&mv=m&mvi=4&pl=16&initcwndbps=2258750&spc=UWF9f0GzDLZc97hdRxm5bkyvZ9Cm7DkgVKxAjcMU_A&vprv=1&svpuc=1&mime=video%2Fmp4&ns=VDqAWUD07qUSzp3N9S4v4mkP&gir=yes&clen=6246756&dur=155.840&lmt=1559455023384768&mt=1693673400&fvip=3&keepalive=yes&fexp=24007246%2C24363393%2C51000011&beids=24350017&c=WEB&txp=5432432&n=ptkGTWZbvP0lTfijKe&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIWZ3kHDyWjo9Uj5lq-Ob9j1vVHUCiwybJ2uYaLbq3slAiBsUMK8BipIiUytq8tsxa51xlN5x7i6dU2JskikKXCvKw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANBx7Nh67ITTA-B6icuFqHYTemifew3c0K-bXVUD1pWlAiBI9jJGO_IMYf-1dGPIPaivV5w1e1xBckwNwDPhKYqXlw%3D%3D'
[dashsegments] Total fragments: 1
[download] Destination: Billy Joel on Song Melody (1993)-psyv8G0mk3U.f135.mp4

[download]   0.0% of ~5.96MiB at  2.88KiB/s ETA 35:21
[download]   0.0% of ~5.96MiB at  8.62KiB/s ETA 11:47
[download]   0.1% of ~5.96MiB at 20.10KiB/s ETA 05:03
[download]   0.2% of ~5.96MiB at 43.03KiB/s ETA 02:21
[download]   0.5% of ~5.96MiB at 58.81KiB/s ETA 01:43
[download]   1.0% of ~5.96MiB at 55.72KiB/s ETA 01:48
[download]   1.9% of ~5.96MiB at 53.68KiB/s ETA 01:51
[download]   2.7% of ~5.96MiB at 57.34KiB/s ETA 01:43
[download]   3.9% of ~5.96MiB at 59.56KiB/s ETA 01:38
[download]   4.9% of ~5.96MiB at 59.41KiB/s ETA 01:37
[download]   5.9% of ~5.96MiB at 59.05KiB/s ETA 01:37
[download]   6.8% of ~5.96MiB at 58.56KiB/s ETA 01:37
[download]   7.8% of ~5.96MiB at 59.46KiB/s ETA 01:34
[download]   8.9% of ~5.96MiB at 60.43KiB/s ETA 01:32
[download]  10.0% of ~5.96MiB at 58.91KiB/s ETA 01:33
[download]  10.8% of ~5.96MiB at 59.56KiB/s ETA 01:31
[download]  11.9% of ~5.96MiB at 59.75KiB/s ETA 01:29
[download]  12.9% of ~5.96MiB at 59.77KiB/s ETA 01:28
[download]  13.9% of ~5.96MiB at 59.66KiB/s ETA 01:28
[download]  14.9% of ~5.96MiB at 60.16KiB/s ETA 01:26
[download]  16.0% of ~5.96MiB at 60.74KiB/s ETA 01:24
[download]  17.1% of ~5.96MiB at 59.91KiB/s ETA 01:24
[download]  17.9% of ~5.96MiB at 60.16KiB/s ETA 01:23
[download]  19.0% of ~5.96MiB at 60.23KiB/s ETA 01:22
[download]  20.0% of ~5.96MiB at 60.20KiB/s ETA 01:21
[download]  21.0% of ~5.96MiB at 60.10KiB/s ETA 01:20
[download]  22.0% of ~5.96MiB at 60.53KiB/s ETA 01:18
[download]  23.1% of ~5.96MiB at 60.15KiB/s ETA 01:17
[download]  24.0% of ~5.96MiB at 60.59KiB/s ETA 01:16
[download]  25.3% of ~5.96MiB at 60.35KiB/s ETA 01:15
[download]  26.2% of ~5.96MiB at 60.63KiB/s ETA 01:14
[download]  27.3% of ~5.96MiB at 60.20KiB/s ETA 01:13
[download]  28.2% of ~5.96MiB at 60.51KiB/s ETA 01:12
[download]  29.3% of ~5.96MiB at 60.75KiB/s ETA 01:10
[download]  30.5% of ~5.96MiB at 60.29KiB/s ETA 01:10
[download]  31.3% of ~5.96MiB at 60.34KiB/s ETA 01:09
[download]  32.3% of ~5.96MiB at 60.35KiB/s ETA 01:08
[download]  33.3% of ~5.96MiB at 60.71KiB/s ETA 01:07
[download]  34.5% of ~5.96MiB at 60.58KiB/s ETA 01:05
[download]  35.5% of ~5.96MiB at 60.44KiB/s ETA 01:05
[download]  36.4% of ~5.96MiB at 60.64KiB/s ETA 01:04
[download]  37.5% of ~5.96MiB at 60.31KiB/s ETA 01:03
[download]  38.4% of ~5.96MiB at 60.53KiB/s ETA 01:02
[download]  39.5% of ~5.96MiB at 60.71KiB/s ETA 01:00
[download]  40.6% of ~5.96MiB at 60.82KiB/s ETA 00:59
[download]  41.7% of ~5.96MiB at 60.37KiB/s ETA 00:58
[download]  42.5% of ~5.96MiB at 60.84KiB/s ETA 00:57
[download]  44.0% of ~5.96MiB at 60.75KiB/s ETA 00:56
[download]  45.0% of ~5.96MiB at 60.60KiB/s ETA 00:55
[download]  45.9% of ~5.96MiB at 60.73KiB/s ETA 00:54
[download]  47.0% of ~5.96MiB at 60.55KiB/s ETA 00:53
[download]  47.9% of ~5.96MiB at 60.66KiB/s ETA 00:52
[download]  49.0% of ~5.96MiB at 60.76KiB/s ETA 00:51
[download]  50.0% of ~5.96MiB at 60.70KiB/s ETA 00:50
[download]  51.0% of ~5.96MiB at 60.62KiB/s ETA 00:49
[download]  51.9% of ~5.96MiB at 60.82KiB/s ETA 00:48
[download]  53.1% of ~5.96MiB at 60.69KiB/s ETA 00:47
[download]  54.1% of ~5.96MiB at 60.50KiB/s ETA 00:46
[download]  54.9% of ~5.96MiB at 60.65KiB/s ETA 00:45
[download]  56.1% of ~5.96MiB at 60.76KiB/s ETA 00:44
[download]  57.2% of ~5.96MiB at 60.83KiB/s ETA 00:42
[download]  58.2% of ~5.96MiB at 60.78KiB/s ETA 00:41
[download]  59.2% of ~5.96MiB at 60.70KiB/s ETA 00:41
[download]  60.1% of ~5.96MiB at 60.60KiB/s ETA 00:40
[download]  61.0% of ~5.96MiB at 60.74KiB/s ETA 00:39
[download]  62.2% of ~5.96MiB at 60.54KiB/s ETA 00:38
[download]  63.0% of ~5.96MiB at 60.63KiB/s ETA 00:37
[download]  64.1% of ~5.96MiB at 60.72KiB/s ETA 00:36
[download]  65.2% of ~5.96MiB at 60.70KiB/s ETA 00:34
[download]  66.2% of ~5.96MiB at 60.65KiB/s ETA 00:34
[download]  67.1% of ~5.96MiB at 60.78KiB/s ETA 00:32
[download]  68.3% of ~5.96MiB at 60.72KiB/s ETA 00:31
[download]  69.3% of ~5.96MiB at 60.57KiB/s ETA 00:30
[download]  70.1% of ~5.96MiB at 60.64KiB/s ETA 00:30
[download]  71.2% of ~5.96MiB at 60.71KiB/s ETA 00:28
[download]  72.3% of ~5.96MiB at 60.74KiB/s ETA 00:27
[download]  73.3% of ~5.96MiB at 60.69KiB/s ETA 00:26
[download]  74.2% of ~5.96MiB at 60.61KiB/s ETA 00:25
[download]  75.1% of ~5.96MiB at 60.69KiB/s ETA 00:24
[download]  76.3% of ~5.96MiB at 60.77KiB/s ETA 00:23
[download]  77.4% of ~5.96MiB at 60.79KiB/s ETA 00:22
[download]  78.4% of ~5.96MiB at 60.79KiB/s ETA 00:21
[download]  79.4% of ~5.96MiB at 60.76KiB/s ETA 00:20
[download]  80.3% of ~5.96MiB at 60.68KiB/s ETA 00:19
[download]  81.2% of ~5.96MiB at 60.78KiB/s ETA 00:18
[download]  82.4% of ~5.96MiB at 60.66KiB/s ETA 00:17
[download]  83.3% of ~5.96MiB at 60.72KiB/s ETA 00:16
[download]  84.4% of ~5.96MiB at 60.77KiB/s ETA 00:15
[download]  85.4% of ~5.96MiB at 60.76KiB/s ETA 00:14
[download]  86.4% of ~5.96MiB at 60.73KiB/s ETA 00:13
[download]  87.4% of ~5.96MiB at 60.66KiB/s ETA 00:12
[download]  88.3% of ~5.96MiB at 60.72KiB/s ETA 00:11
[download]  89.4% of ~5.96MiB at 60.81KiB/s ETA 00:10
[download]  90.5% of ~5.96MiB at 60.70KiB/s ETA 00:09
[download]  91.4% of ~5.96MiB at 60.71KiB/s ETA 00:08
[download]  92.4% of ~5.96MiB at 60.71KiB/s ETA 00:07
[download]  93.4% of ~5.96MiB at 60.69KiB/s ETA 00:06
[download]  94.3% of ~5.96MiB at 60.80KiB/s ETA 00:05
[download]  95.5% of ~5.96MiB at 60.71KiB/s ETA 00:04
[download]  96.4% of ~5.96MiB at 60.77KiB/s ETA 00:03
[download]  97.6% of ~5.96MiB at 60.82KiB/s ETA 00:02
[download]  98.6% of ~5.96MiB at 60.66KiB/s ETA 00:01
[download]  99.4% of ~5.96MiB at 60.69KiB/s ETA 00:00
[download] 100.0% of ~5.96MiB at 60.85KiB/s ETA 00:00
[download] 100.0% of ~5.96MiB at 60.85KiB/s ETA 00:00
[download] 100% of 5.96MiB in 01:40
[debug] Invoking downloader on 'https://rr4---sn-h0jeln7l.googlevideo.com/videoplayback?expire=1693695459&ei=gmnzZNfXOuGG6dsP6N20uAs&ip=84.115.217.88&id=o-AJOsd9Kb90JefTK0HiR6Qw3UVeGXhpcQo2JoaghYj5zl&itag=251&source=youtube&requiressl=yes&mh=0b&mm=31%2C26&mn=sn-h0jeln7l%2Csn-5hneknee&ms=au%2Conr&mv=m&mvi=4&pl=16&initcwndbps=2258750&spc=UWF9f0GzDLZc97hdRxm5bkyvZ9Cm7DkgVKxAjcMU_A&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=VDqAWUD07qUSzp3N9S4v4mkP&gir=yes&clen=2621238&dur=156.041&lmt=1559454990453862&mt=1693673400&fvip=3&keepalive=yes&fexp=24007246%2C24363393%2C51000011&beids=24350017&c=WEB&txp=5432432&n=ptkGTWZbvP0lTfijKe&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhALwhD60OM_UYYDpGFyHvaJIfYW2UlhKThATibGBzH8dWAiAtPr1jAbI3dqHrrdH8PdMzJenY7bxokB1g9XogHU-shQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANBx7Nh67ITTA-B6icuFqHYTemifew3c0K-bXVUD1pWlAiBI9jJGO_IMYf-1dGPIPaivV5w1e1xBckwNwDPhKYqXlw%3D%3D'
[dashsegments] Total fragments: 1
[download] Destination: Billy Joel on Song Melody (1993)-psyv8G0mk3U.f251.webm

[download]   0.0% of ~2.50MiB at  3.41KiB/s ETA 12:29
[download]   0.1% of ~2.50MiB at 10.23KiB/s ETA 04:09
[download]   0.3% of ~2.50MiB at 23.84KiB/s ETA 01:47
[download]   0.6% of ~2.50MiB at 51.04KiB/s ETA 00:49
[download]   1.2% of ~2.50MiB at 65.59KiB/s ETA 00:38
[download]   2.5% of ~2.50MiB at 58.60KiB/s ETA 00:42
[download]   4.5% of ~2.50MiB at 55.18KiB/s ETA 00:44
[download]   6.6% of ~2.50MiB at 58.54KiB/s ETA 00:40
[download]   9.2% of ~2.50MiB at 60.50KiB/s ETA 00:38
[download]  11.8% of ~2.50MiB at 60.16KiB/s ETA 00:37
[download]  14.1% of ~2.50MiB at 59.68KiB/s ETA 00:36
[download]  16.3% of ~2.50MiB at 59.09KiB/s ETA 00:36
[download]  18.5% of ~2.50MiB at 59.95KiB/s ETA 00:34
[download]  21.1% of ~2.50MiB at 60.59KiB/s ETA 00:33
[download]  23.7% of ~2.50MiB at 60.90KiB/s ETA 00:32
[download]  26.2% of ~2.50MiB at 60.99KiB/s ETA 00:30
[download]  28.6% of ~2.50MiB at 60.46KiB/s ETA 00:30
[download]  30.7% of ~2.50MiB at 59.94KiB/s ETA 00:29
[download]  32.8% of ~2.50MiB at 60.33KiB/s ETA 00:28
[download]  35.5% of ~2.50MiB at 60.47KiB/s ETA 00:27
[download]  37.9% of ~2.50MiB at 60.47KiB/s ETA 00:26
[download]  40.2% of ~2.50MiB at 60.20KiB/s ETA 00:25
[download]  42.4% of ~2.50MiB at 60.79KiB/s ETA 00:24
[download]  45.3% of ~2.50MiB at 60.54KiB/s ETA 00:23
[download]  47.6% of ~2.50MiB at 60.15KiB/s ETA 00:22
[download]  49.6% of ~2.50MiB at 60.50KiB/s ETA 00:21
[download]  52.4% of ~2.50MiB at 60.85KiB/s ETA 00:20
[download]  55.0% of ~2.50MiB at 60.27KiB/s ETA 00:19
[download]  57.0% of ~2.50MiB at 60.35KiB/s ETA 00:18
[download]  59.5% of ~2.50MiB at 60.39KiB/s ETA 00:17
[download]  61.9% of ~2.50MiB at 60.87KiB/s ETA 00:16
[download]  64.8% of ~2.50MiB at 60.65KiB/s ETA 00:14
[download]  67.0% of ~2.50MiB at 60.45KiB/s ETA 00:13
[download]  69.2% of ~2.50MiB at 60.76KiB/s ETA 00:12
[download]  72.0% of ~2.50MiB at 60.54KiB/s ETA 00:11
[download]  74.2% of ~2.50MiB at 60.77KiB/s ETA 00:10
[download]  76.9% of ~2.50MiB at 60.97KiB/s ETA 00:09
[download]  79.5% of ~2.50MiB at 60.46KiB/s ETA 00:08
[download]  81.4% of ~2.50MiB at 60.61KiB/s ETA 00:07
[download]  84.0% of ~2.50MiB at 60.61KiB/s ETA 00:06
[download]  86.4% of ~2.50MiB at 60.56KiB/s ETA 00:05
[download]  88.7% of ~2.50MiB at 60.83KiB/s ETA 00:04
[download]  91.6% of ~2.50MiB at 60.76KiB/s ETA 00:03
[download]  93.9% of ~2.50MiB at 60.52KiB/s ETA 00:02
[download]  95.9% of ~2.50MiB at 60.67KiB/s ETA 00:01
[download]  98.6% of ~2.50MiB at 60.76KiB/s ETA 00:00
[download] 100.0% of ~2.50MiB at 60.84KiB/s ETA 00:00
[download] 100.0% of ~2.50MiB at 60.84KiB/s ETA 00:00
[download] 100% of 2.50MiB in 00:42
[ffmpeg] Merging formats into "Billy Joel on Song Melody (1993)-psyv8G0mk3U.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Billy Joel on Song Melody (1993)-psyv8G0mk3U.f135.mp4' -i 'file:Billy Joel on Song Melody (1993)-psyv8G0mk3U.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Billy Joel on Song Melody (1993)-psyv8G0mk3U.temp.mkv'
Deleting original file Billy Joel on Song Melody (1993)-psyv8G0mk3U.f135.mp4 (pass -k to keep)
Deleting original file Billy Joel on Song Melody (1993)-psyv8G0mk3U.f251.webm (pass -k to keep)
```

**Comment by 1268** [comment]
works fine with current master.

**Comment by andreas-gruenbacher** [comment]
I'd not have created this bug report if the current master (2021.12.17-284-g31f50c819) did work for me :)

**Comment by 1268** [comment]
seems like a you problem:

~~~
> pip install https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.zip
Created wheel for youtube-dl:
filename=youtube_dl-2021.12.17-py2.py3-none-any.whl size=1940290
sha256=0e6a70123b29ef3295acc817d501556cba7cb0a96d0260972501e6e8b4c909ed

> youtube-dl --prefer-free-formats gav66byYJMw
[youtube] gav66byYJMw: Downloading webpage
[dashsegments] Total fragments: 2
[download] Destination: Billy Joel - Lullabye (Goodnight, My Angel) (Audio)-gav66byYJMw.f248.webm
[download] 100% of 17.95MiB in 00:00
~~~

**Comment by dirkf** [comment]
#32499

The consent page (or some other interstitial page bypassed by consent cookies) may appear for some users and not others, depending on ?factors?.

**Comment by fireflycons** [comment]
@andreas-gruenbacher 

I had this too. I worked out that it was being redirected to a consent page by using `--print-traffic` argument.
In a browser I pasted the consent URL and accepted the consent. Then I grabbed the cookies from the browser as netscape cookie format and created a `cookies.txt` file to use with `--cookies` argument to youtube-dl. 

It then worked.

**Comment by dirkf** [comment]
As in the master issue linked above.
