### ISSUE TITLE
ERROR: Unable to extract uploader id [youtube-dl API]

### ISSUE THREAD

**Issue by yuchdev** [ytdl-org/youtube-dl#32574]
## Description

Trying to download Youtube playlist using Youtube-dl API
OS: MacOS BigSur 11.7.9 (20G1426)
```
python3 --version
Python 3.8.9
```

## Steps to Reproduce

The issue is being 100% reproducible during calling the following Python code:
```
import youtube_dl

def download_playlist(playlist_url, output_dir):
    # Create the output directory if it doesn't exist
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # Set the output template to save videos in the specified directory
    ydl_opts = {
        'format': 'best',
        'quiet': False,
        'outtmpl': os.path.join(output_dir, '%(title)s.%(ext)s'),
    }

    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download([playlist_url])
        
download_playlist("https://youtube.com/playlist?list=PLlb7e2G7aSpQhNphPSpcO4daaRPeVstku", "output")
```

## Verbose log

Providing the stacktrace
```
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/atatat/Projects/HomeDir/venv/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/atatat/Projects/HomeDir/venv/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/atatat/Projects/HomeDir/venv/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/Users/atatat/Projects/HomeDir/venv/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1776, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/Users/atatat/Projects/HomeDir/venv/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment]
#30839 !

**Comment by domdfcoding** [comment]
So will this ever be fixed?

**Comment by yuchdev** [comment]
> #30839 !

I apologize if it's a duplicate, but I did not find any through the Github search. Many issues feature "unable to extract" something, but none related to uploader ID in relation to Python API.

Can I have a link to the initial ticket?

**Comment by dirkf** [comment]
API usage is not the problem. The relevant issue is linked in the pinned issue.
