### ISSUE TITLE
Youtube: HTTP Error 403, giving up after 10 fragment retries

### ISSUE THREAD

**Issue by MarkJeronimus** [ytdl-org/youtube-dl#32603]
## Checklist
- [x] I'm reporting a broken site support
- [-] I've verified that I'm running youtube-dl version **2021.12.17** — I'm using 2023.09.25
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
zom-b@zomb-pc-2020:/mnt/nasu/nasu/Anime/Anime/Nodame Cantabile 1$ Nodame Cantabile/Nodame Cantabile OST$ ~/Downloads/youtube-dl --verbose -f "bestaudio" https://www.youtube.com/watch?v=bU7snGx1f98
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'bestaudio', 'https://www.youtube.com/watch?v=bU7snGx1f98']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2023.09.25 [00ef748cc] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.15.0-86-generic-x86_64-with-glibc2.29 - OpenSSL 1.1.1f  31 Mar 2020 - glibc 2.31
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {}
[youtube] bU7snGx1f98: Downloading webpage
[youtube] bU7snGx1f98: Downloading API JSON
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (expected string or bytes-like object Traceback (most recent call last):
  File "/home/zom-b/Downloads/youtube-dl/youtube_dl/extractor/youtube.py", line 1679, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/home/zom-b/Downloads/youtube-dl/youtube_dl/extractor/youtube.py", line 1644, in _extract_n_function
    player_id = self._extract_player_info(player_url)
  File "/home/zom-b/Downloads/youtube-dl/youtube_dl/extractor/youtube.py", line 1476, in _extract_player_info
    id_m = re.search(player_re, player_url)
  File "/usr/lib/python3.8/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
)
[youtube] bU7snGx1f98: Downloading API JSON
[debug] Invoking downloader on 'https://rr4---sn-uhvcpaxoa-guhe.googlevideo.com/videoplayback?expire=1697572689&ei=8ZIuZd2wHY_t1gK356DwAg&ip=143.178.88.101&id=o-AMtZC04kPFPwCOH1OKkGEu0btT4VjivqTwe3eiJhIGpP&itag=251&source=youtube&requiressl=yes&mh=DO&mm=31%2C29&mn=sn-uhvcpaxoa-guhe%2Csn-5hne6nzd&ms=au%2Crdu&mv=m&mvi=4&pl=21&initcwndbps=1768750&spc=UWF9f2kkPcJTOJztj_zIivhe7phlubjPbrMb0z2CRA&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=aD89BDZ-wqY4Dh4tsAtvbDMP&gir=yes&clen=4885217&dur=268.621&lmt=1671468807818790&mt=1697551025&fvip=3&keepalive=yes&fexp=24007246&beids=24350018&c=WEB&txp=5432434&n=BdPa9rbakKAJNLZh3Q&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRgIhAOoc00ABDi6EnQC6mAtlr81f_yhFJk1SSec36GxMpEdHAiEAmK1XMyRU2PhhM-QImtuNKODz_iOYKH_a63kc_NrZBU8%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRQIgEevlEZvAwVqOrT3bAwvurte_xZ8j9cjTg5C-r2CEpTACIQC0-V_Hh9qVFSB8FMLeK1YNtDf8HUw2UleiHnunPNsDxA%3D%3D'
[dashsegments] Total fragments: 1
[download] Destination: 29.l 【Two Pianos】 Rachmaninoff Pianoconcerto No.2 Op.18-1 Nodame Cantabile anime-bU7snGx1f98.webm
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 10 of 10)...
ERROR: giving up after 10 fragment retries
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zom-b/Downloads/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/home/zom-b/Downloads/youtube-dl/youtube_dl/__init__.py", line 473, in main
    _real_main(argv)
  File "/home/zom-b/Downloads/youtube-dl/youtube_dl/__init__.py", line 463, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/zom-b/Downloads/youtube-dl/youtube_dl/YoutubeDL.py", line 2222, in download
    res = self.extract_info(
  File "/home/zom-b/Downloads/youtube-dl/youtube_dl/YoutubeDL.py", line 856, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/home/zom-b/Downloads/youtube-dl/youtube_dl/YoutubeDL.py", line 863, in wrapper
    return func(self, *args, **kwargs)
  File "/home/zom-b/Downloads/youtube-dl/youtube_dl/YoutubeDL.py", line 970, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/zom-b/Downloads/youtube-dl/youtube_dl/YoutubeDL.py", line 1004, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/zom-b/Downloads/youtube-dl/youtube_dl/YoutubeDL.py", line 1839, in process_video_result
    self.process_info(new_info)
  File "/home/zom-b/Downloads/youtube-dl/youtube_dl/YoutubeDL.py", line 2127, in process_info
    success = dl(filename, info_dict)
  File "/home/zom-b/Downloads/youtube-dl/youtube_dl/YoutubeDL.py", line 2066, in dl
    return fd.download(name, new_info)
  File "/home/zom-b/Downloads/youtube-dl/youtube_dl/downloader/common.py", line 380, in download
    return self.real_download(filename, info_dict)
  File "/home/zom-b/Downloads/youtube-dl/youtube_dl/downloader/dash.py", line 73, in real_download
    self.report_error('giving up after %s fragment retries' % count)
  File "/home/zom-b/Downloads/youtube-dl/youtube_dl/downloader/common.py", line 175, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/home/zom-b/Downloads/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in report_error
    self.trouble(*args, **kwargs)
  File "/home/zom-b/Downloads/youtube-dl/youtube_dl/YoutubeDL.py", line 618, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

## Description

It only happens when I try to extract audio with 'bestaudio'. It works fine if I first find the format code with `-F` and then specify it manually with `-f 251`.

Is it related to the anti-adblocker campaign? Because it was working for similar URLs 2 weeks ago (with version 2021.04.26 even)

It also mentions throttling, but I haven't been on YT yet today (apart from ~4 attempts with older versions)

**Comment by dirkf** [comment]
Try again?
```console
$ ./youtube-dl-20230925 --verbose -f bestaudio 'https://www.youtube.com/watch?v=bU7snGx1f98'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-f', u'bestaudio', u'https://www.youtube.com/watch?v=bU7snGx1f98']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2023.09.25 [00ef748cc] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 2.7.18 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial - OpenSSL 1.1.1w  11 Sep 2023 - glibc 2.15
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] bU7snGx1f98: Downloading webpage
[youtube] bU7snGx1f98: Downloading API JSON
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (expected string or buffer Traceback (most recent call last):
  File "./youtube-dl-20230925/youtube_dl/extractor/youtube.py", line 1679, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "./youtube-dl-20230925/youtube_dl/extractor/youtube.py", line 1644, in _extract_n_function
    player_id = self._extract_player_info(player_url)
  File "./youtube-dl-20230925/youtube_dl/extractor/youtube.py", line 1476, in _extract_player_info
    id_m = re.search(player_re, player_url)
  File "/usr/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer
)
[youtube] bU7snGx1f98: Downloading API JSON
[debug] Invoking downloader on u'https://rr2---sn-cu-aigss.googlevideo.com/videoplayback?expire=1697622448&ei=UFUvZZrILqKMp-oP4Nm1qAY&ip=46.208.6.61&id=o-AABvv4qM0Xo0eehHANAI4LYwzzveBpGYvy3YWQ-pFMAp&itag=251&source=youtube&requiressl=yes&mh=DO&mm=31%2C29&mn=sn-cu-aigss%2Csn-cu-c9id&ms=au%2Crdu&mv=u&mvi=2&pl=25&spc=UWF9f0PIagEbaExQF95ylfJ-HS9vVhMmMDwVd8_yqw&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=xtvj_3lYSYLGyOjeEQEkBU8P&gir=yes&clen=4885217&dur=268.621&lmt=1671468807818790&mt=1697600500&fvip=3&keepalive=yes&fexp=24007246&beids=24350018&c=WEB&txp=5432434&n=v-KB54GEvvQixehRl0&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRQIhAMDLsXxebHsaaFIVZRWSdckzDuuIJOF2nla05snCz8kZAiB28gple8U6mk9XieF0JxcWeXbCiBTdA9pTDxTYuQ0izQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AK1ks_kwRAIgOpn_Azp3-LskMxKyVrzs-8UxbWRFd17ecw5mqbOcomUCIBHKt5QUq2sqIiEFFamzkkMJhSoGEmc4KOcrt818lRA5'
[dashsegments] Total fragments: 1
[download] Destination: 29.l 【Two Pianos】 Rachmaninoff Pianoconcerto No.2 Op.18-1 Nodame Cantabile anime-bU7snGx1f98.webm
[download] 100% of 4.66MiB in 03:38
$
```
Maybe an issue, possibly transient, at YT, such as a bug in the CDN roll-out/caching. If it still doesn't work for you, I'd suggest asking for a different format, but it worked when you asked for the **same** format.

**Comment by GrumpyGiuseppe** [comment]
I got mostly the same issue:

`[download]  23.3% of  309.54MiB at  547.60KiB/s ETA 07:24[download] Got error: HTTP Error 503: Service Unavailable. Retrying (1/10)...
[download]  24.6% of  309.54MiB at  144.64KiB/s ETA 27:33[download] Got error: HTTP Error 503: Service Unavailable. Retrying (2/10)...
[download]  27.1% of  309.54MiB at  387.86KiB/s ETA 09:55[download] Got error: HTTP Error 503: Service Unavailable. Retrying (3/10)...
[download]  28.4% of  309.54MiB at  279.47KiB/s ETA 13:31[download] Got error: HTTP Error 503: Service Unavailable. Retrying (4/10)...
[download]  31.0% of  309.54MiB at  537.61KiB/s ETA 06:46[download] Got error: HTTP Error 503: Service Unavailable. Retrying (5/10)...
[download]  33.0% of  309.54MiB at  207.53KiB/s ETA 17:04[download] Got error: HTTP Error 503: Service Unavailable. Retrying (6/10)...
[download]  34.2% of  309.54MiB at  276.89KiB/s ETA 12:32[download] Got error: The read operation timed out. Retrying (7/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (8/10)...
[download] Got error: The read operation timed out. Retrying (9/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (10/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Giving up after 10 retries`

In the browser it's the same.
The video loads if I reload the page but after the first loading it stops loading further.
If I disable adblock it works.

**Comment by dirkf** [comment]
No, because 503 != 403.

>If I disable adblock it works.

Does this fix the 503 issue, or just loading in the browser?

If the 503 issue is fixed, what sort of ad-blocker are you using?

**Comment by GrumpyGiuseppe** [comment]
> Does this fix the 503 issue, or just loading in the browser?

Just loading in the browser.
I use Ublock Origin.

I did a internet connection reset for a new IP adress and it works again for now.
But I never had this problem, so I guess it will come back sooner or later.
