### ISSUE TITLE
Twitter/X media page

### ISSUE THREAD

**Issue by am517** [ytdl-org/youtube-dl#32627]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v https://twitter.com/TrumpWarRoom/media
[debug] System config: []
[debug] User config: ['--cookies', '/Users/me/.config/youtube-dl/cookies', '--cache-dir', '/Users/me/.config/youtube-dl/', '--user-agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:85.0) Gecko/20100101 Firefox/85.0', '-u', 'PRIVATE', '-p', 'PRIVATE', '-i', '--no-mark-watched', '--no-warnings', '--retries', 'infinite', '--fragment-retries', 'infinite', '--download-archive', '/Users/me/.config/youtube-dl/downloads.txt', '-o', '/Volumes/Movies/Youtubes/%(uploader)s/%(playlist_title)s/%(upload_date)s - %(title)s.%(ext)s', '-f', 'bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a][abr<=192]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio/best', '--write-sub', '--write-auto-sub', '--sub-lang', 'en,ja', '--embed-subs', '--embed-thumbnail', '--add-metadata', '--xattrs', '--audio-format', 'm4a', '--recode-video', 'mp4']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://twitter.com/TrumpWarRoom/media']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 83b4b2f2f
[debug] Python version 3.11.6 (CPython) - macOS-14.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0, rtmpdump 2.4
[debug] Proxy map: {}
[generic] media: Requesting header
[generic] media: Downloading webpage
[generic] media: Extracting information
ERROR: Unsupported URL: https://twitter.com/TrumpWarRoom/media
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/generic.py", line 3489, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://twitter.com/TrumpWarRoom/media


## Description

<!--
Provide an explanation of your issue in an arbitrary form. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

I would like to download all videos from the media tab of a twitter profile. There may be images posted here too, but I imagine they can be skipped. I only want the videos posted by the user (media tab), not just shared (main twitter stream).

**Comment by dirkf** [comment]
I don't think the Twitter/X extractor is working properly at the moment and the site is even more aggressive against third-party tools. Even when it was working I believe it just picked media from a single tweet. Still, your suggestion seems reasonable.
