### ISSUE TITLE
Python Import Error

### ISSUE THREAD

**Issue by visor841** [ytdl-org/youtube-dl#32633]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] ~~I've verified that I'm running youtube-dl version **2021.12.17**~~ (I am running the latest nightly)
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/bin/youtube-dl/__main__.py", line 16, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 14, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/options.py", line 8, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/__init__.py", line 3, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 30, in <module>
  File "/usr/lib/python3.11/ssl.py", line 100, in <module>
    import _ssl             # if we can't import it, let the error propagate
    ^^^^^^^^^^^
ImportError: /usr/lib/python3.11/lib-dynload/_ssl.cpython-311-x86_64-linux-gnu.so: undefined symbol: _PyModule_Add
```

## Description

Running the lastest nightly, I am unable to run youtube-dl in any capacity due to the python error above. Any combination of arguments I try on youtube-dl gives the error.

**Comment by dirkf** [comment]
Please show a full verbose log.

However, it looks like a problem with your Python setup. What happens if you run `/usr/bin/python3.11 -c "import ssl"`?
