### ISSUE TITLE
"Please Report This Issue"

### ISSUE THREAD

**Issue by MarkP2015** [ytdl-org/youtube-dl#32652]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] Ixve checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ I can't find the bugtracker ] I've searched the bugtracker for similar bug reports including closed ones
- [I can't find bugs ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
exocom@exocom-X540YA:~$ youtube-dl --verbose --extract-audio --audio-format mp3 https://www.youtube.com/watch?v=pyJ0DZIl3Os&t=1874[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--extract-audio', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=pyJ0DZIl3Os']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.12 (CPython) - Linux-5.15.0-89-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] pyJ0DZIl3Os: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

^C
[1]+  Exit 1                  youtube-dl --verbose --extract-audio --audio-format mp3 https://www.youtube.com/watch?v=pyJ0DZIl3Os
exocom@exocom-X540YA:~$ youtube-dl -U
ERROR: can't find the current version. Please try again later.

```

## Description

WRITE DESCRIPTION HERE

I don't know enough to write something here. PLEASE FORGIVE THIS.

**Comment by dirkf** [comment]
Why not read #30839 where your issue is listed?
