### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by durack1** [ytdl-org/youtube-dl#32668]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
bash-3.2$ youtube-dl https://www.youtube.com/watch?v=otNh9bTjXWg --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=otNh9bTjXWg', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.10 (CPython) - macOS-14.1.2-arm64-arm-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] otNh9bTjXWg: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I seem to be hitting this "ERROR: Unable to extract uploader id;" no matter what site I am hitting. This appears to be a particular problem with youtube. I have tried numerous wrap the URL techniques, none of which appear to solve the issue

**Comment by durack1** [comment]
This does not appear to be solved in the latest nightly build:

```
(base) paully@airy2 ~ % youtube-dl https://www.youtube.com/watch?v=lFEolmXl_4E
zsh: no matches found: https://www.youtube.com/watch?v=lFEolmXl_4E
(base) paully@airy2 ~ % youtube-dl '{https://www.youtube.com/watch?v=lFEolmXl_4E}'
ERROR: '{https://www.youtube.com/watch?v=lFEolmXl_4E}' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:{https://www.youtube.com/watch?v=lFEolmXl_4E}" ) to search YouTube
(base) paully@airy2 ~ % youtube-dl '{https://www.youtube.com/watch?v=lFEolmXl_4E}' --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['{https://www.youtube.com/watch?v=lFEolmXl_4E}', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2023.12.07 [be008e657] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 3.10.10 (CPython arm64 64bit) - macOS-14.1.2-arm64-arm-64bit - OpenSSL 3.1.0 14 Mar 2023
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: '{https://www.youtube.com/watch?v=lFEolmXl_4E}' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:{https://www.youtube.com/watch?v=lFEolmXl_4E}" ) to search YouTube
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 863, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 959, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 565, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2555, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: '{https://www.youtube.com/watch?v=lFEolmXl_4E}' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:{https://www.youtube.com/watch?v=lFEolmXl_4E}" ) to search YouTube
```
