### ISSUE TITLE
youtube-dl Fails to Parse Public Facebook Video Data

### ISSUE THREAD

**Issue by Fares-Abubaker** [ytdl-org/youtube-dl#32665]
**Checklist:**
- [x] Reporting a broken site support issue
- [x] Running latest youtube-dl version
- [x] URL is alive and playable in a browser
- [x] URLs and special characters properly quoted/escaped
- [x] Searched bugtracker for similar reports
- [x] Read bugs section in FAQ

**Verbose Log:**
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.facebook.com/mousa.madfa/videos/378107074704278/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: c32bd1c7c
[debug] Python version 3.12.1 (CPython) - macOS-14.1.2-arm64-arm-64bit
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 378107074704278: Downloading webpage
[facebook] 378107074704278: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.12/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.12/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.12/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.12/site-packages/youtube_dl/extractor/facebook.py", line 680, in _real_extract
    return self._extract_from_url(real_url, video_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.12/site-packages/youtube_dl/extractor/facebook.py", line 594, in _extract_from_url
    raise ExtractorError('Cannot parse data')
```

**Description:**
Encountering an issue with `youtube-dl` when trying to download a public Facebook video. The command used was `youtube-dl -v https://www.facebook.com/mousa.madfa/videos/378107074704278/`. Despite the video being publicly accessible, `youtube-dl` fails to parse the data, leading to an error. The verbose log is provided for detailed examination.

**Comment by dirkf** [comment]
#30872
