### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by sugizo** [ytdl-org/youtube-dl#32685]
## Checklist

- [x ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', '%(uploader)s - %(title)s.%(ext)s', '-f', 'best', 'https://www.youtube.com/watch?v=fMi6Xi6Li2Q', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.12 (CPython) - Linux-6.1.58+-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {'colab_language_server': '/usr/colab/bin/language_service'}
[youtube] fMi6Xi6Li2Q: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

trying another youtube url got same result, 
trying from python code, got an error too :

```
[youtube] QYgaT9rF89g: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
---------------------------------------------------------------------------
RegexNotFoundError                        Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py](https://localhost:8080/#) in wrapper(self, *args, **kwargs)
    814             try:
--> 815                 return func(self, *args, **kwargs)
    816             except GeoRestrictedError as e:

9 frames
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

DownloadError                             Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py](https://localhost:8080/#) in trouble(self, message, tb)
    596             else:
    597                 exc_info = sys.exc_info()
--> 598             raise DownloadError(message, exc_info)
    599         self._download_retcode = 1
    600 

DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

best regards

**Comment by nicolaasjan** [comment]
> [ x] I've searched the bugtracker for similar bug reports including closed ones

Actually do this first.
[https://github.com/ytdl-org/youtube-dl/issues?q=Unable+to+extract+uploader+id](https://github.com/ytdl-org/youtube-dl/issues?q=Unable+to+extract+uploader+id)
