### ISSUE TITLE
Typical "ffmpeg could not be found" location problem? No it isn´t.

### ISSUE THREAD

**Issue by rocks-man** [ytdl-org/youtube-dl#32736]
## Checklist

- [ x] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi there, I have a question for you all.

I know I MUST look around for similar questions or troubleshooting but my problem is really different and yeah, I have looked so many pages without similar scenarios even.

I´m running this script https://github.com/MaZED-UP/bunny-cdn-drm-video-dl from a Macbook for your concern.

Problem.
There are a video series from a tutorial page I have been downloading (one by one) a long time ago but today I realized I can´t download a special one: it is posted in first place of the same section page I used to download.

The script still RUNS perfectly with other videos in the same section except for this one.

Following you´ll find the entire error message, and It would seems to be a ffmpeg permission or location directory problem but it doesn´t because (I repeat) the script runs perfectly with other videos in the same page section:

[generic] Extracting URL: https://iframe.mediadelivery.net/emedID/1920x1080/video.drm?context...74-aa33-96dfb607dbbd
[generic] video: Downloading webpage
[generic] video: Downloading m3u8 information
[generic] video: Checking m3u8 live status
[info] video: Downloading 1 format(s): 0
[download] Destination: /Users/---/Movies/.videofilename.mp4/videofilename.mp4
ERROR: m3u8 download detected but ffmpeg could not be found. Please install
Traceback (most recent call last):
  File "/Users/---/b-cdn-drm-vod-dl.py", line 188, in <module>
    video.download()
  File "/Users/---/b-cdn-drm-vod-dl.py", line 174, in download
    ydl.download(url)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3541, in download
    self.__download_wrapper(self.extract_info)(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3516, in wrapper
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1576, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1743, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1802, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 2952, in process_video_result
    self.process_info(new_info)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3418, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3139, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/downloader/external.py", line 50, in real_download
    retval = self._call_downloader(tmpfilename, info_dict)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/downloader/external.py", line 481, in _call_downloader
    self.report_error('m3u8 download detected but ffmpeg could not be found. Please install')
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1054, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 993, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: m3u8 download detected but ffmpeg could not be found. Please install

Thanks for your comments!!!!!

**Comment by dirkf** [comment]
#30839: "if you were actually running yt-dlp ..."

But what you will be asked there is this: what version of _ffmpeg_ is installed on your system (paste the text output of the command `ffmpeg -version` run in a Terminal), and, if none, why didn't you install it as the diagnostic asks.

yt-dl and yt-dlp can generally download media from m3u8 manifests but _ffmpeg_ is needed for "live" media.

**Comment by rocks-man** [comment]
Thanks Dirkf, You were totally right It wasn´t installed ffmpeg.

I already tried to install ffmpeg with this instructions (https://amiaopensource.github.io/ffmpeg-artschool/). I had already installed brew but I have the following error installing ffmpeg:

==> Fetching libvorbis
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/85c487f7d18b4c15cab0d4f3b22854cd03364fa6/Formula/lib/libvorbis.rb
################################################################################################################################################################ 100.0%
==> Downloading https://upload.wikimedia.org/wikipedia/commons/c/c8/Example.ogg
Already downloaded: /Users/rock/Library/Caches/Homebrew/downloads/e163886f3d57674f022eb584f07ef6d71dbbf58fb39c481a2c516ce6bfd4af18--Example.ogg
Error: ffmpeg: Failed to download resource "libvorbis"
Download failed: Homebrew-installed `curl` is not installed for: https://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.tar.xz

And ffmpeg was not installed.

Could you help me, please?

**Comment by dirkf** [comment]
Really you should ask at the brewery, but it seems to be saying that _curl_ is needed first.

**Comment by rocks-man** [comment]
Hey Dirkf, last was a Macos version problem I had to change to windows and now I have a new problem, sorry bother you with ths basic issues.

I really need ur help. I already install ffmpeg in Windows but I can´t still these two specific videos from a list of 20. The following is the new traceback and telling video url is not found but it really exists!!! I search for possible workarounds but I don´t find anything.

![Capture](https://github.com/ytdl-org/youtube-dl/assets/144400826/0ab39b0f-964d-4f1e-8860-35ba977e5962)


[generic] Extracting URL: https://iframe.mediadelivery.net/22f40a69-3da7-4047-818d-5d24936d0374/1982x1080/video.drm?context...0c-a5a1-4eba158173a9
[generic] video: Downloading webpage
[generic] video: Downloading m3u8 information
[generic] video: Checking m3u8 live status
[info] video: Downloading 1 format(s): 0
[download] Destination: C:\Users\Rock\Documents\.Premium-25-23022024.mp4\Premium-25-23022024.mp4
[https @ 0000021a1e4c4700] HTTP error 404 Not Found
[in#0 @ 0000021a1e4c21c0] Error opening input: Server returned 404 Not Found
Error opening input file https://iframe.mediadelivery.net/22f40a69-3da7-4047-818d-5d24936d0374/1982x1080/<html><head><title>404 - File Not Found</title><link href='/fonts.bunny.net/css?family=Rubik:300,400,500' rel='stylesheet' type='text/css'><style>html, body { width: 100%; margin: 0; padding: 0; text-align: center; font-family: 'Rubik'; background-repeat: no-repeat; background-position: bottom center; background-size: cover; color: white; height: 100%; background-color: #313335; } h1 {margin-bottom: 0px;font-weight: bold;font-size: 140px;font-weight: 500;padding-top: 130px;margin-bottom: -35px;}h2 {font-size: 45px;color: white; font-weight: 200;}</style></head><body><div id='content'><h1 style='margin-bottom: -35px;'>404</h1><h2>File Not Found</h2></div></body></html>.
Error opening input files: Server returned 404 Not Found


ERROR: ffmpeg exited with code 3419392776
Traceback (most recent call last):
  File "C:\Users\Rock\Documents\bunny2.py", line 188, in <module>
    video.download()
  File "C:\Users\Rock\Documents\bunny2.py", line 174, in download
    ydl.download(url)
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3511, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3486, in wrapper
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1556, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 2922, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3388, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3109, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\downloader\common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\downloader\external.py", line 80, in real_download
    self.report_error('%s exited with code %d' % (
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1045, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 984, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: ffmpeg exited with code 3419392776

**Comment by dirkf** [comment]
**yt-dlp** (wrong tracker), but neither project knows about your video host iframe.mediadelivery.net.  

Search the Web for that host name to find hints that may or (probably) may not help.

Or create a Site Support Request for the actual site that is using this video host.

**Comment by rocks-man** [comment]
Thanks man!!!!

Regards!!
