### ISSUE TITLE
Maybe you can provide your [logged-in browser session cookies](https://github.com/ytdl-org/youtube-dl#user-content-i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser) instead?

### ISSUE THREAD

**Issue by AlexIs387** [ytdl-org/youtube-dl#32746]
Maybe you can provide your [logged-in browser session cookies](https://github.com/ytdl-org/youtube-dl#user-content-i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser) instead?

And exactly how do I do this? I don't understand what it says on that link.

_Originally posted by @dirkf in https://github.com/ytdl-org/youtube-dl/issues/30163#issuecomment-953365381_

**Comment by AlexIs387** [comment]
I got this doing what I thought:

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\__init__.py", line 458, in _real_main
  File "C:\Python\Python34\lib\optparse.py", line 1568, in error
  File "C:\Python\Python34\lib\optparse.py", line 1558, in exit
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\__init__.py", line 468, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 569, in __exit__
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\utils.py", line 2775, in save
OSError: [Errno 22] Invalid argument: 'https://vk.com/video-206524420_456240519?list=a8453355d21678c967'
