### ISSUE TITLE
Unable to extract yt initial data

### ISSUE THREAD

**Issue by davidoiknine** [ytdl-org/youtube-dl#32749]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -f bestaudio --extract-audio --audio-format mp3 --verbose "https://www.youtube.com/playlist\?list\=PLKTAq7_g6xSeGLxysxrjx4j_1L-O4yZCz"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestaudio', '--extract-audio', '--audio-format', 'mp3', '--verbose', 'https://www.youtube.com/playlist\\?list\\=PLKTAq7_g6xSeGLxysxrjx4j_1L-O4yZCz']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.7 (CPython) - macOS-14.4-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:tab] playlist\: Downloading webpage
ERROR: Unable to extract yt initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 2841, in _real_extract
    data = self._extract_yt_initial_data(item_id, webpage)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 299, in _extract_yt_initial_data
    self._search_regex(
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract yt initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Hello,
I try to download the audio of the playlist https://www.youtube.com/playlist?list=PLKTAq7_g6xSeGLxysxrjx4j_1L-O4yZCz but it’s not working. Did I do something wrong?
Thank you for your help.
David

**Comment by dirkf** [comment]
Probably reading #30839 properly, where your problem is listed as a Known Issue fixed in the nightly build, or paying more attention to this
>[x] I've searched the bugtracker for similar bug reports including closed ones
>[x] I've read bugs section in FAQ

would be it.
