### ISSUE TITLE
DL fails "unable to extract uploader id"

### ISSUE THREAD

**Issue by LexaGV** [ytdl-org/youtube-dl#32774]
yt-dl fails to download video, this is dump:

```
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=TlZ6IDZm8Vc']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 7.0-full_build-www.gyan.dev, ffprobe 7.0-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] TlZ6IDZm8Vc: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl
e --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
```

**Comment by dirkf** [comment]
1. Review #30839 as asked for the solution to your **known problem**.
2. If that did not solve your problem (it will) **complete the issue template**.
