### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by ikus060** [ytdl-org/youtube-dl#32792]
## Checklist
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl -citk --verbose --extract-audio --audio-format mp3 "https://www.youtube.com/watch?v=HU08BcK5SUY&list=PL4OUuvE_31OQbvBMew3jxn9rJfrV2r4HQ"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-citk', '--verbose', '--extract-audio', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=HU08BcK5SUY&list=PL4OUuvE_31OQbvBMew3jxn9rJfrV2r4HQ']
WARNING: --title is deprecated. Use -o "%(title)s-%(id)s.%(ext)s" instead.
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.12 (CPython) - Linux-6.8.0-76060800daily20240311-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] Downloading playlist PL4OUuvE_31OQbvBMew3jxn9rJfrV2r4HQ - add --no-playlist to just download video HU08BcK5SUY
[youtube:tab] PL4OUuvE_31OQbvBMew3jxn9rJfrV2r4HQ: Downloading webpage
[youtube:tab] PL4OUuvE_31OQbvBMew3jxn9rJfrV2r4HQ: Downloading webpage
[download] Downloading playlist: 2024-ete
[youtube:tab] Downloading page 1
[youtube:tab] playlist 2024-ete: Downloading 15 videos
[download] Downloading video 1 of 15
[youtube] HU08BcK5SUY: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[download] Downloading video 2 of 15
...
```

## Description

I did not check if the webpage contains the expected regex pattern, but I cant it's youtube-dl is working for some but not all video in that playlist.

Thanks for helping.

**Comment by dirkf** [comment]
Please review #30839 **as asked** to find the solution for your **known issue**.
