### ISSUE TITLE
If the site (www.cda.pl) requires age confirmation, it does not display a list of available formats

### ISSUE THREAD

**Issue by gremlin4553** [ytdl-org/youtube-dl#32790]
If the site (www.cda.pl) requires age confirmation, it does not display a list of available formats.

-------------------------------------------------------------------------------------------------------------

log -v:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-check-certificate', '--list-formats', 'https://www.cda.pl/video/180010222f']
[debug] Encodings: locale cp1250, fs utf-8, out cp1250, pref cp1250
[debug] youtube-dl version 2021.12.17
[debug] Python 3.8.13+ (CPython x86 32bit) - Windows-XP-5.1.2600-SP3 - OpenSSL 3.1.0-dev
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: unable to extract default player_json; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest ver
sion; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
ERROR: No video formats found; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https:
//github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "D:\instal\YOUTUB~1\Python\src\youtube_dl\YoutubeDL.py", line 859, in wrapper
    return func(self, *args, **kwargs)
  File "D:\instal\YOUTUB~1\Python\src\youtube_dl\YoutubeDL.py", line 955, in __extract_info
    ie_result = ie.extract(url)
  File "D:\instal\YOUTUB~1\Python\src\youtube_dl\extractor\common.py", line 571, in extract
    ie_result = self._real_extract(url)
  File "D:\instal\YOUTUB~1\Python\src\youtube_dl\extractor\cda.py", line 212, in _real_extract
    self._sort_formats(formats)
  File "D:\instal\YOUTUB~1\Python\src\youtube_dl\extractor\common.py", line 1554, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the l
atest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.

**Comment by dirkf** [comment]
Looks like we need to update the extractor from [_yt-dlp_](https://github.com/yt-dlp/yt-dlp/pull/6638).
