### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by rusvet18** [ytdl-org/youtube-dl#32794]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ +] I've verified that I'm running youtube-dl version **2021.12.17**
- [ +] I've checked that all provided URLs are alive and playable in a browser
- [ +] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ +] I've searched the bugtracker for similar bug reports including closed ones
- [+ ] I've read bugs section in FAQ

## Verbose log

C:\Users\rusve\Downloads\Sublime Text Build 3211 x64>bot.py
[2024-05-23 11:00:54] [INFO    ] discord.client: logging in using static token
[2024-05-23 11:00:55] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ac8d8ce45257879c8a1f7c6ebf5e3193).
Ебанутый#5953 запущен
[2024-05-23 11:04:41] [INFO    ] discord.voice_client: Connecting to voice...
[2024-05-23 11:04:41] [INFO    ] discord.voice_client: Starting voice handshake... (connection attempt 1)
[2024-05-23 11:04:42] [INFO    ] discord.voice_client: Voice handshake complete. Endpoint found warsaw10152.discord.media
[youtube] mgQL2xeviN8: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[2024-05-23 11:04:44] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command play
Traceback (most recent call last):
  File "C:\Users\rusve\AppData\Local\Programs\Python\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\rusve\AppData\Local\Programs\Python\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\rusve\AppData\Local\Programs\Python\Python38\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\rusve\AppData\Local\Programs\Python\Python38\lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "C:\Users\rusve\AppData\Local\Programs\Python\Python38\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rusve\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\rusve\Downloads\Sublime Text Build 3211 x64\bot.py", line 125, in play
    информация = с_ссылкой.extract_info(url, download=False)
  File "C:\Users\rusve\AppData\Local\Programs\Python\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\rusve\AppData\Local\Programs\Python\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\rusve\AppData\Local\Programs\Python\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\rusve\AppData\Local\Programs\Python\Python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rusve\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\rusve\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\rusve\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
```

## Description

I made code for music on Discord.py, but it gives this error

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
Please review #30839 **as asked** for the solution to this **known problem**.
