### ISSUE TITLE
nable to extract uploader id; 

### ISSUE THREAD

**Issue by rain1** [ytdl-org/youtube-dl#32813]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\youtube>youtube-dl https://www.youtube.com/watch?v=BaW_jenozKc --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=BaW_jenozKc', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.7 (CPython) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 4.2.3
[debug] Proxy map: {}
[youtube] BaW_jenozKc: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Rain\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Rain\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Rain\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Rain\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "C:\Users\Rain\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


C:\youtube>
```

## Description
In common.py line 991 there is `re.search(pattern, string, flags)`. Arguments are the following: pattern: `'/(?:channel|user)/([^/?&#]+)'`
string: `'http://www.youtube.com/@PhilippHagemeister'`flags: `0` so the call itself is `re.search('/(?:channel|user)/([^/?&#]+)', 'http://www.youtube.com/@PhilippHagemeister', 0)` which returns `None`. After changing pattern variable to `'/@([^/?&#]+)'` then it correctly extracted 'PhilippHagemeister' for 'uploader_id' value in youtube.py 1794.   This new url format have been around for quite a while already. Is this project still being updated?

**Comment by kratess** [comment]
same error

**Comment by dirkf** [comment]
Review #30839 as asked for the solution to this (well) Known Issue.
