### ISSUE TITLE
Youtube: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug

### ISSUE THREAD

**Issue by udayb** [ytdl-org/youtube-dl#32817]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -f 18 https://www.youtube.com/watch?v=2gK-mb4zOik
[youtube] 2gK-mb4zOik: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(base) (uday@d920 youtube 2024-06-17 21:05:09) > youtube-dl -f 18 https://www.youtube.com/watch?v=2gK-mb4zOik --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '18', 'https://www.youtube.com/watch?v=2gK-mb4zOik', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.7 (CPython) - Linux-5.15.0-112-generic-x86_64-with-glibc2.35
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 2gK-mb4zOik: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/uday/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/uday/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/uday/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/uday/.local/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/home/uday/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Some extractions are failing with "Unable to extract uploader id. Please see the example above.
youtube-dl --version
2021.12.17

Command used: 
youtube-dl -f 18 https://www.youtube.com/watch?v=2gK-mb4zOik

Problem is seen even without the -f 18 option.

**Comment by dengruoqing** [comment]
i meet the problem the same with you

**Comment by fuad-daoud** [comment]
same here I can't use the tool

**Comment by dengruoqing** [comment]
now you can user this one to download videos. https://github.com/yt-dlp/yt-dlp

step1:
python3 -m pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz
step2:
yt-dlp URL

**Comment by dirkf** [comment]
Feel free to review #'0839 **as asked** for the solution to your **Known Issue**.
