### ISSUE TITLE
[Youtube] download error: Unable to extract yt initial data

### ISSUE THREAD

**Issue by TataneSan** [ytdl-org/youtube-dl#32826]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Hi, I've been trying to download some videos of some randoms YouTube channel, but it seems that there is a problem with it. I have the error "Unable to extract yt initial data".

**Comment by dirkf** [comment]
Review #30839 **as asked** to see if your problem is one of the **Known issues** and if it is solved in the master code and nightly release (hint: it appears to be).

If not, you need to **PASTE VERBOSE LOG HERE**, as the issue template expects, for further help

**Comment by Deepa-Aru** [comment]
```
python -m youtube_dl https://www.youtube.com/watch?v=V6R8uiaMtb0 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=V6R8uiaMtb0', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.12.4 (CPython) - Windows-11-10.0.22631-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] V6R8uiaMtb0: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\thanu\Downloads\youtube-dl-2021.12.17\youtube-dl-2021.12.17\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thanu\Downloads\youtube-dl-2021.12.17\youtube-dl-2021.12.17\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\thanu\Downloads\youtube-dl-2021.12.17\youtube-dl-2021.12.17\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thanu\Downloads\youtube-dl-2021.12.17\youtube-dl-2021.12.17\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thanu\Downloads\youtube-dl-2021.12.17\youtube-dl-2021.12.17\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Deepa-Aru** [comment]
```
python -m youtube_dl https://www.youtube.com/watch?v=ngMaV2Y_O0Q --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=ngMaV2Y_O0Q', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.12.4 (CPython) - Windows-11-10.0.22631-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] ngMaV2Y_O0Q: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\thanu\Downloads\youtube-dl-2021.12.17\youtube-dl-2021.12.17\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thanu\Downloads\youtube-dl-2021.12.17\youtube-dl-2021.12.17\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\thanu\Downloads\youtube-dl-2021.12.17\youtube-dl-2021.12.17\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thanu\Downloads\youtube-dl-2021.12.17\youtube-dl-2021.12.17\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thanu\Downloads\youtube-dl-2021.12.17\youtube-dl-2021.12.17\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment]
>Review #30839 as asked to see if your problem is one of the Known issues and if it is solved in the master code and nightly release (hint: it appears to be).

It is, although not the error that was originally suggested. Use the nightly release to resolve these Known Issues.

**Comment by dirkf** [comment]
@TataneSan ?

**Comment by bpfaust** [comment]
Not OP but @dirkf same issue happening for me:

➜  ~ youtube-dl -x -f m4a/bestaudio -o '<SAVE_PATH_HERE>' --rm-cache-dir --user-agent "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" --verbose https://music.youtube.com/playlist\?list\=OLAK5uy_knVyH4nmb1XF6igxBe6D3pyejUa2RHnRY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', '-f', 'm4a/bestaudio', '-o', '<SAVE_PATH_HERE>', '--rm-cache-dir', '--user-agent', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36', '--verbose', 'https://music.youtube.com/playlist?list=OLAK5uy_knVyH4nmb1XF6igxBe6D3pyejUa2RHnRY']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2025.01.06 [1036478d1]
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 3.11.4 (CPython arm64 64bit) - macOS-14.6.1-arm64-arm-64bit - OpenSSL 3.4.0 22 Oct 2024
[debug] exe versions: ffmpeg 7.1, ffprobe 7.1
[debug] Proxy map: {}
Removing cache dir <CACHE_PATH> ..
[youtube:tab] OLAK5uy_knVyH4nmb1XF6igxBe6D3pyejUa2RHnRY: Downloading webpage
ERROR: Unable to extract yt initial data; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "/Users/benfaust/.pyenv/versions/3.11.4/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 879, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benfaust/.pyenv/versions/3.11.4/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 975, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/Users/benfaust/.pyenv/versions/3.11.4/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 571, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benfaust/.pyenv/versions/3.11.4/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 3550, in _real_extract
    data = self._extract_yt_initial_data(item_id, webpage)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benfaust/.pyenv/versions/3.11.4/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 340, in _extract_yt_initial_data
    self._search_regex(
  File "/Users/benfaust/.pyenv/versions/3.11.4/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1101, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract yt initial data; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.

**Comment by dirkf** [comment]
Your log doesn't match OP's. Basically, you need the full fix for #32905 ut even then the result could be like that with _yt-dlp 2024.12.06_:
```
...
WARNING: [youtube:tab] YouTube Music is not directly supported. Redirecting to https://www.youtube.com/playlist?list=OLAK5uy_knVyH4nmb1XF6igxBe6D3pyejUa2RHnRY
[youtube:tab] OLAK5uy_knVyH4nmb1XF6igxBe6D3pyejUa2RHnRY: Downloading webpage
WARNING: [youtube:tab] YouTube said: INFO - 10 unavailable videos are hidden
...
```
