### ISSUE TITLE
yt_dlp.utils.DownloadError: ERROR: [vimeo]: Unable to download JSON metadata: HTTP Error 400: Bad Request 

### ISSUE THREAD

**Issue by SasaniP** [ytdl-org/youtube-dl#32834]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.07.01 from yt-dlp/yt-dlp [5ce582448] (pip) API
[debug] params: {'videopassword': '123', 'verbose': True, 'format': 'bestvideo+bestaudio', 'referer': 'https://vimeo.com', 'external_downloader': 'aria2c', 'external_downloader_args': ['-x', '16', '-s', '16', '-k', '5M', '--max-concurrent-downloads=16'], 'outtmpl': '/Users/sasanisulakshi/Desktop/vimeo_videos/%(title)s (%(format_id)s).%(ext)s', 'writeinfojson': True, 'nooverwrites': True, 'tempdir': '/var/folders/m7/n7p88dkn4wj496yhzls19tv40000gp/T', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.10.11 (CPython arm64 64bit) - macOS-14.4.1-arm64-arm-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 6.1.1-tessus (setts)
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1831 extractors
Video Downloading in best quality
[vimeo] Extracting URL: http://vimeo.com/587512620?share=copy
[vimeo] 587512620: Downloading webpage
[vimeo] 587512620: Downloading JSON metadata
[vimeo] 587512620: Downloading JSON metadata
ERROR: [vimeo] 587512620: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/vimeo.py", line 903, in _real_extract
    return self._extract_from_api(video_id)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/vimeo.py", line 756, in _extract_from_api
    video = self._download_json(
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1139, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1099, in download_handle
    res = self._download_webpage_handle(
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 960, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 909, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 896, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 4161, in urlopen
    return self._request_director.send(req)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/common.py", line 337, in send
    return self._send(request)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/_requests.py", line 361, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1622, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1757, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/vimeo.py", line 903, in _real_extract
    return self._extract_from_api(video_id)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/vimeo.py", line 756, in _extract_from_api
    video = self._download_json(
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1139, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1099, in download_handle
    res = self._download_webpage_handle(
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 960, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 909, in _request_webpage
    raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: [vimeo] 587512620: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/downloader.py", line 45, in vimeo_download
    result = ydl_worst.download([url])
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3603, in download
    self.__download_wrapper(self.extract_info)(
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3578, in wrapper
    res = func(*args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1611, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1640, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1088, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1027, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [vimeo] 587512620: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 896, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 4161, in urlopen
    return self._request_director.send(req)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/common.py", line 337, in send
    return self._send(request)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/_requests.py", line 361, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request

Traceback (most recent call last):
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 896, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 4161, in urlopen
    return self._request_director.send(req)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/common.py", line 337, in send
    return self._send(request)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/_requests.py", line 361, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1622, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1757, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/vimeo.py", line 903, in _real_extract
    return self._extract_from_api(video_id)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/vimeo.py", line 756, in _extract_from_api
    video = self._download_json(
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1139, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1099, in download_handle
    res = self._download_webpage_handle(
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 960, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 909, in _request_webpage
    raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: [vimeo] 587512620: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/downloader.py", line 45, in vimeo_download
    result = ydl_worst.download([url])
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3603, in download
    self.__download_wrapper(self.extract_info)(
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3578, in wrapper
    res = func(*args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1611, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1640, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1088, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1027, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [vimeo] 587512620: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 896, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 4161, in urlopen
    return self._request_director.send(req)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/common.py", line 337, in send
    return self._send(request)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/_requests.py", line 361, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1622, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1757, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/vimeo.py", line 903, in _real_extract
    return self._extract_from_api(video_id)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/vimeo.py", line 756, in _extract_from_api
    video = self._download_json(
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1139, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1099, in download_handle
    res = self._download_webpage_handle(
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 960, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 909, in _request_webpage
    raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: [vimeo] 587512620: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/downloader.py", line 66, in <module>
    vimeo_download(vimeo_link_password)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/downloader.py", line 51, in vimeo_download
    result = ydl_best.download([url])
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3603, in download
    self.__download_wrapper(self.extract_info)(
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3578, in wrapper
    res = func(*args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1611, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1640, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1088, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1027, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [vimeo] 587512620: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

Process finished with exit code 1
```

## Description

WRITE DESCRIPTION HERE

I am using the yt_dlp-2024.7.1 from pypi and i have used 2024.7.2 as well.
I am trying to download a password protected vimeo video in formats, `worstvideo+worstaudio` and `bestvideo+bestaudio`. the issue is not in any of these formats.

```
yt_dlp_options_worst = {
        "videopassword": password,
        "verbose": True,
        "format": "worstvideo+worstaudio",
        "referer": "https://vimeo.com",
        "external_downloader": "aria2c",
        "external_downloader_args": ["-x", "16", "-s", "16", "-k", "5M", "--max-concurrent-downloads=16"],
        "outtmpl": os.path.join(destination_folder, "%(title)s (%(format_id)s).%(ext)s"),
        "writeinfojson": True,
        "nooverwrites": True,
        "tempdir": tempfile.gettempdir()
    }

    yt_dlp_options_best = {
        "videopassword": password,
        "verbose": True,
        "format": "bestvideo+bestaudio",
        "referer": "https://vimeo.com",
        "external_downloader": "aria2c",
        "external_downloader_args": ["-x", "16", "-s", "16", "-k", "5M", "--max-concurrent-downloads=16"],
        "outtmpl": os.path.join(destination_folder, "%(title)s (%(format_id)s).%(ext)s"),
        "writeinfojson": True,
        "nooverwrites": True,
        "tempdir": tempfile.gettempdir()
    }
```

I am trying to download the following Vimeo video. And the video is playable in the private tab in chrome.
You can reproduce this error. `Link: http://vimeo.com/587512620` with the `Password: 123`.

These are the packages and their versions i am using.
```
python 3.10
Brotli 1.1.0
certifi 2024.6.2
charset-normalizer 3.3.2
idna 3.7
mutagen 1.47.0
pip 23.2.1
pycryptodomex 3.20.0
requests 2.32.3
setuptools 68.2.0
urllib3 2.2.2
websockets 12.0
wheel 0.41.2
yt-dip 2024.7.1
```

**Comment by dirkf** [comment]
https://github.com/yt-dlp/yt-dlp/issues/6603
