### ISSUE TITLE
ERROR: Unable to extract nsig jsi, player_id, func_codefunction code 

### ISSUE THREAD

**Issue by int512** [ytdl-org/youtube-dl#32852]
## Checklist

- [X ] I'm reporting a broken site support
- [X ] I've verified that I'm running youtube-dl version **2021.12.17**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
admin2@pc:/mnt/data/Private/Music/YT/New2$ youtube-dl -x https://www.youtube.com/watch?v=urV0coB1Ap0 --verbose
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', 'https://www.youtube.com/watch?v=urV0coB1Ap0', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-6.9.7-200.fc40.x86_64-x86_64-with-glibc2.39 - OpenSSL 3.2.1 30 Jan 2024 - glibc 2.39
[debug] exe versions: ffmpeg 6.1.1, ffprobe 6.1.1
[debug] Proxy map: {}
[youtube] urV0coB1Ap0: Downloading webpage
[youtube] urV0coB1Ap0: Downloading player 8d9f6215
ERROR: Unable to extract nsig jsi, player_id, func_codefunction code (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.')); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1637, in _decrypt_nsig
    jsi, player_id, func_code = self._extract_n_function_code(video_id, player_url)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1680, in _extract_n_function_code
    func_name = self._extract_n_function_name(jscode)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1660, in _extract_n_function_name
    func_name, idx = self._search_regex(
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/youtube_dl/extractor/common.py", line 1101, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1637, in _decrypt_nsig
    jsi, player_id, func_code = self._extract_n_function_code(video_id, player_url)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1680, in _extract_n_function_code
    func_name = self._extract_n_function_name(jscode)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1660, in _extract_n_function_name
    func_name, idx = self._search_regex(
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/youtube_dl/extractor/common.py", line 1101, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/youtube_dl/YoutubeDL.py", line 858, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/youtube_dl/YoutubeDL.py", line 954, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/youtube_dl/extractor/common.py", line 571, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 2108, in _real_extract
    self._unthrottle_format_urls(video_id, player_url, dct)
  File "/usr/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1725, in _unthrottle_format_urls
    n_response = decrypt_nsig(n_param)(n_param, video_id, player_url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1614, in inner
    raise ret
  File "/usr/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1606, in inner
    self._player_cache[cache_id] = func(*args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1639, in _decrypt_nsig
    raise ExtractorError('Unable to extract nsig jsi, player_id, func_codefunction code', cause=e)
youtube_dl.utils.ExtractorError: Unable to extract nsig jsi, player_id, func_codefunction code (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.')); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.

```

## Description

Not downloading

**Comment by int512** [comment]
i checked the latest nightly build and it works

**Comment by nPerriolat** [comment]
I got strictly the same problem in similarly conditions. The last time youtube-dl worked for me was on July 8. I installed it with dnf on Fedora so I reinstalled it but it doesn't solved the problem.

**Comment by int512** [comment]
> I got strictly the same problem in similarly conditions. The last time youtube-dl worked for me was on July 8. I installed it with dnf on Fedora so I reinstalled it but it doesn't solved the problem.

try the latest build from here https://github.com/ytdl-org/ytdl-nightly

**Comment by xihajun** [comment]
Hey @int512, thanks for your guidance, any idea of this issue?

```
ffmpeg] Merging formats into "youtube.mp4"
Deleting original file youtube.f136.mp4 (pass -k to keep)
Deleting original file youtube.f140-drc.m4a (pass -k to keep)
WARNING: [youtube] 6W-cu0yp5cA: Unable to decode n-parameter: download likely to be throttled (Unsupported string method prototype.split.call in: 'String.prototype.split.call(a,"")'; please report this issue on [https://github.com/ytdl-org/youtube-dl/issues](https://github.com/ytdl-org/youtube-dl/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen) , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output. Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1646, in _decrypt_nsig
    ret = extract_nsig(jsi, func_code)(n)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1702, in extract_nsig
    ret = func([s])
          ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 1051, in resf
    ret, should_abort = self.interpret_statement(code.replace('\n', ' '), var_stack, allow_recursion - 1)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 452, in interpret_statement
    ret, should_return = self.interpret_statement(sub_stmt, local_vars, allow_recursion)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 670, in interpret_statement
    ret, should_abort = self.interpret_statement(sub_expr, local_vars, allow_recursion)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 709, in interpret_statement
    local_vars[m.group('out')] = self._operator(
                                 ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 400, in _operator
    right_val = self.interpret_expression(right_expr, local_vars, allow_recursion)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 942, in interpret_expression
    ret, should_return = self.interpret_statement(expr, local_vars, allow_recursion)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 926, in interpret_statement
    return eval_method(), should_return
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 833, in eval_method
    raise self.Exception('Unsupported string method ' + member, expr=expr)
youtube_dl.jsinterp.JSInterpreter.Exception: Unsupported string method prototype.split.call in: 'String.prototype.split.call(a,"")'; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
)
WARNING: [youtube] 6W-cu0yp5cA: Unable to decode n-parameter: download likely to be throttled (Unsupported string method prototype.split.call in: 'String.prototype.split.call(a,"")'; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output. Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1646, in _decrypt_nsig
    ret = extract_nsig(jsi, func_code)(n)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1702, in extract_nsig
    ret = func([s])
          ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 1051, in resf
    ret, should_abort = self.interpret_statement(code.replace('\n', ' '), var_stack, allow_recursion - 1)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 452, in interpret_statement
    ret, should_return = self.interpret_statement(sub_stmt, local_vars, allow_recursion)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 670, in interpret_statement
    ret, should_abort = self.interpret_statement(sub_expr, local_vars, allow_recursion)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 709, in interpret_statement
    local_vars[m.group('out')] = self._operator(
                                 ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 400, in _operator
    right_val = self.interpret_expression(right_expr, local_vars, allow_recursion)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 942, in interpret_expression
    ret, should_return = self.interpret_statement(expr, local_vars, allow_recursion)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 926, in interpret_statement
    return eval_method(), should_return
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 833, in eval_method
    raise self.Exception('Unsupported string method ' + member, expr=expr)
youtube_dl.jsinterp.JSInterpreter.Exception: Unsupported string method prototype.split.call in: 'String.prototype.split.call(a,"")'; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
)
ffmpeg version 5.1.4-0+deb12u1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec[618](https://github.com/xihajun/speech2text/actions/runs/9922666378/job/27412069213#step:4:619)83 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
youtube-dl: Invalid data found when processing input
```

**Comment by dirkf** [comment]
Please review #30839.

Master code:
```console
$ python -m youtube_dl -vF 'https://www.youtube.com/watch?v=urV0coB1Ap0'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vF', u'https://www.youtube.com/watch?v=urV0coB1Ap0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 16f5bbc46
[debug] Python 2.7.18 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial - OpenSSL 1.1.1w  11 Sep 2023 - glibc 2.15
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] urV0coB1Ap0: Downloading webpage
[debug] [youtube] Decrypted nsig k5cRbzj7xthocThjfhz => 4CRNV5KQ7YoWlQ
[debug] [youtube] Decrypted nsig zpMJ2MXhx6py24xhScB => z9gXTiQDOnJ71Q
[info] Available formats for urV0coB1Ap0:
format code  extension  resolution note
249          webm       audio only audio_quality_low   50k , webm_dash container, opus  (48000Hz), 1.26MiB
250          webm       audio only audio_quality_low   67k , webm_dash container, opus  (48000Hz), 1.66MiB
140          m4a        audio only audio_quality_medium  129k , m4a_dash container, mp4a.40.2 (44100Hz), 3.20MiB
251          webm       audio only audio_quality_medium  133k , webm_dash container, opus  (48000Hz), 3.30MiB
160          mp4        256x144    144p   14k , mp4_dash container, avc1.4d400c, 30fps, video only, 375.60KiB
278          webm       256x144    144p   17k , webm_dash container, vp9, 30fps, video only, 446.77KiB
242          webm       426x240    240p   21k , webm_dash container, vp9, 30fps, video only, 532.78KiB
133          mp4        426x240    240p   25k , mp4_dash container, avc1.4d4015, 30fps, video only, 636.47KiB
243          webm       640x360    360p   33k , webm_dash container, vp9, 30fps, video only, 849.78KiB
134          mp4        640x360    360p   38k , mp4_dash container, avc1.4d401e, 30fps, video only, 976.53KiB
244          webm       854x480    480p   45k , webm_dash container, vp9, 30fps, video only, 1.11MiB
135          mp4        854x480    480p   61k , mp4_dash container, avc1.4d401f, 30fps, video only, 1.51MiB
247          webm       1280x720   720p   87k , webm_dash container, vp9, 30fps, video only, 2.17MiB
136          mp4        1280x720   720p   98k , mp4_dash container, avc1.64001f, 30fps, video only, 2.43MiB
248          webm       1920x1080  1080p  103k , webm_dash container, vp9, 30fps, video only, 2.55MiB
137          mp4        1920x1080  1080p  175k , mp4_dash container, avc1.640028, 30fps, video only, 4.33MiB
18           mp4        640x360    360p  134k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz), 3.32MiB (best)
$
```
And previously (note: same player code as OP's log):
```console
$ python -m youtube_dl -vF 6W-cu0yp5cA
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-Fv', u'6W-cu0yp5cA']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 16f5bbc46
[debug] Python 2.7.18 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial - OpenSSL 1.1.1w  11 Sep 2023 - glibc 2.15
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] 6W-cu0yp5cA: Downloading webpage
[youtube] 6W-cu0yp5cA: Downloading player 8d9f6215
[debug] [youtube] Decrypted nsig q0tUi3cz5yN070Y9Ka6 => 77X-vRQ7_Dd3cQ
[debug] [youtube] Decrypted nsig 0u5Rh5ubfPnJJCCzzpH => mKh6lnekhqNFGg
[info] Available formats for 6W-cu0yp5cA:
format code  extension  resolution note
251          webm       audio only audio_quality_medium  107k , webm_dash container, opus  (48000Hz), 37.32MiB
251-drc      webm       audio only audio_quality_medium  109k , webm_dash container, opus  (48000Hz), 38.19MiB
140          m4a        audio only audio_quality_medium  129k , m4a_dash container, mp4a.40.2 (44100Hz), 45.03MiB
140-drc      m4a        audio only audio_quality_medium  129k , m4a_dash container, mp4a.40.2 (44100Hz), 45.03MiB
160          mp4        256x144    144p   55k , mp4_dash container, avc1.4d400c, 25fps, video only, 19.33MiB
134          mp4        640x360    360p  218k , mp4_dash container, avc1.4d401e, 25fps, video only, 76.15MiB
136          mp4        1280x720   720p  823k , mp4_dash container, avc1.64001f, 25fps, video only, 286.30MiB
18           mp4        640x360    360p  347k , avc1.42001E, 25fps, mp4a.40.2 (44100Hz) (best)
$
```
And the bundled executable from the nightly release page:
```console
$ youtube-dl-20240711 -vF 'https://www.youtube.com/watch?v=urV0coB1Ap0'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vF', u'https://www.youtube.com/watch?v=urV0coB1Ap0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2024.07.11 [16f5bbc46] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 2.7.18 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial - OpenSSL 1.1.1w  11 Sep 2023 - glibc 2.15
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] urV0coB1Ap0: Downloading webpage
[debug] [youtube] Decrypted nsig at001fdGtBZAwpl3AHN => WoHHpcNx3Ymspw
[debug] [youtube] Decrypted nsig dq_czaCnuntTXIb82fO => sAKHujtni5gLfw
[info] Available formats for urV0coB1Ap0:
format code  extension  resolution note
249          webm       audio only audio_quality_low   50k , webm_dash container, opus  (48000Hz), 1.26MiB
250          webm       audio only audio_quality_low   67k , webm_dash container, opus  (48000Hz), 1.66MiB
140          m4a        audio only audio_quality_medium  129k , m4a_dash container, mp4a.40.2 (44100Hz), 3.20MiB
251          webm       audio only audio_quality_medium  133k , webm_dash container, opus  (48000Hz), 3.30MiB
160          mp4        256x144    144p   14k , mp4_dash container, avc1.4d400c, 30fps, video only, 375.60KiB
278          webm       256x144    144p   17k , webm_dash container, vp9, 30fps, video only, 446.77KiB
242          webm       426x240    240p   21k , webm_dash container, vp9, 30fps, video only, 532.78KiB
133          mp4        426x240    240p   25k , mp4_dash container, avc1.4d4015, 30fps, video only, 636.47KiB
243          webm       640x360    360p   33k , webm_dash container, vp9, 30fps, video only, 849.78KiB
134          mp4        640x360    360p   38k , mp4_dash container, avc1.4d401e, 30fps, video only, 976.53KiB
244          webm       854x480    480p   45k , webm_dash container, vp9, 30fps, video only, 1.11MiB
135          mp4        854x480    480p   61k , mp4_dash container, avc1.4d401f, 30fps, video only, 1.51MiB
247          webm       1280x720   720p   87k , webm_dash container, vp9, 30fps, video only, 2.17MiB
136          mp4        1280x720   720p   98k , mp4_dash container, avc1.64001f, 30fps, video only, 2.43MiB
248          webm       1920x1080  1080p  103k , webm_dash container, vp9, 30fps, video only, 2.55MiB
137          mp4        1920x1080  1080p  175k , mp4_dash container, avc1.640028, 30fps, video only, 4.33MiB
18           mp4        640x360    360p  134k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz), 3.32MiB (best)
$
```
