### ISSUE TITLE
When I tried to call this function on my personal project, I encountered an error saying "Unable to extract uploader ID."

### ISSUE THREAD

**Issue by ottopan** [ytdl-org/youtube-dl#32854]
## Description
my python code
```
# utils/youtube_helper.py

# 导入必要的库
import youtube_dl

# 定义下载函数
def download_video_and_audio(url, download_path):
    # 创建YouTube下载选项
    ydl_opts = {
        'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
        'outtmpl': download_path + '/%(title)s.%(ext)s',
        'noplaylist': True,
    }

    # 创建YouTube下载器实例
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        # 下载视频
        info = ydl.extract_info(url, download=True)

        # 获取视频和音频文件路径
        video_file = info.get('requested_downloads')[0].get('filepath')
        audio_file = info.get('requested_downloads')[1].get('filepath') if len(info.get('requested_downloads')) > 1 else None

        return video_file, audio_file

# 提示用户输入YouTube链接
url = input("请输入YouTube视频链接: ") # 新增的代码行

# 设置下载路径
download_path = "D:/codemaker/MapleMusic/downloads/video"

# 调用下载函数
video_file, audio_file = download_video_and_audio(url, download_path)

# 打印下载结果
print(f"视频文件: {video_file}")
print(f"音频文件: {audio_file}")
```
Terminal error
```
(maplemusic_env) PS D:\codemaker\MapleMusic\utils> python youtube_helper.py
请输入YouTube视频链接: https://www.youtube.com/watch?v=vPqBD7zhxQM&ab_channel=SlipySlidy
[youtube] vPqBD7zhxQM: Downloading webpage
[youtube] Downloading just video vPqBD7zhxQM because of --no-playlist
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "D:\codemaker\MapleMusic\maplemusic_env\Lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\codemaker\MapleMusic\maplemusic_env\Lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "D:\codemaker\MapleMusic\maplemusic_env\Lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\codemaker\MapleMusic\maplemusic_env\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\codemaker\MapleMusic\maplemusic_env\Lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\codemaker\MapleMusic\utils\youtube_helper.py", line 33, in <module>
    video_file, audio_file = download_video_and_audio(url, download_path)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\codemaker\MapleMusic\utils\youtube_helper.py", line 18, in download_video_and_audio
    info = ydl.extract_info(url, download=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\codemaker\MapleMusic\maplemusic_env\Lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\codemaker\MapleMusic\maplemusic_env\Lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "D:\codemaker\MapleMusic\maplemusic_env\Lib\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "D:\codemaker\MapleMusic\maplemusic_env\Lib\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Ted12357** [comment]
having a similar issue here too

**Comment by dirkf** [comment]
Review #30839 for the solution to you Known Issue
