### ISSUE TITLE
Suddenly getting 403 Forbidden since 2 days ago

### ISSUE THREAD

**Issue by FlyingThunder** [ytdl-org/youtube-dl#32856]
- [ ] I'm reporting a broken site support issue
- [X ] I've verified that I'm running youtube-dl version **2021.12.17**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X ] I've searched the bugtracker for similar bug reports including closed ones
- [X ] I've read bugs section in FAQ

## Verbose log

```
C:\Users\laure>youtube-dl -x --audio-format m4a https://www.youtube.com/watch?v=lFtL7bnekAs -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', '--audio-format', 'm4a', 'https://www.youtube.com/watch?v=lFtL7bnekAs', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.2 (CPython) - Windows-10-10.0.22631-SP0
[debug] exe versions: ffmpeg 2023-10-18-git-e7a6bba51a-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] lFtL7bnekAs: Downloading webpage
[youtube] lFtL7bnekAs: Downloading player 820bff3b
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "C:\Users\laure\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1669, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laure\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1641, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laure\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1617, in _extract_n_function_name
    nfunc_and_idx = self._search_regex(
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laure\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\common.py", line 1013, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
[debug] Invoking downloader on 'https://rr2---sn-i5h7lner.googlevideo.com/videoplayback?expire=1721137508&ei=BCWWZq_lBsTWi9oPwLWl6AQ&ip=91.59.199.61&id=o-AF8UAzz7IwdbJEIoCyfH43xHN6vvh0pKHSAIkiV-RpKj&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=ql&mm=31%2C26&mn=sn-i5h7lner%2Csn-4g5ednsy&ms=au%2Conr&mv=m&mvi=2&pl=26&initcwndbps=1656250&bui=AXc671I1Ug_FKnx5qzc5H4zbznG9xMGzby-zfxcSBsm2Lk4L4CvgmGcvCiCSudm9ygCqZL4xunG_W_si&spc=NO7bAVIZvlu1HYvQMmu7uc6ezVKu5ZYTpcs5ZnhO0Y1kLmDFmRMdiGurtxOo&vprv=1&svpuc=1&xtags=drc%3D1&mime=audio%2Fmp4&ns=IEqMep1HrhOic8R18s7s8TAQ&rqh=1&gir=yes&clen=2842031&dur=175.542&lmt=1656798296978764&mt=1721115673&fvip=3&keepalive=yes&c=WEB&sefc=1&txp=1432434&n=HJ0m9Ch8V_MbHPzW&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cxtags%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAPpa7FplRuFiQCYgurCce9o4TgAyiOreiCeSSBBPr9OhAiBO0ldf9rfkPx3lzApgCpuo3Q6fv7AtG-UJoyAjA-YQVw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIhAPK4ISIZqAThCQ6M63dZ27A_wTbQ6-hlIiYU8K7OSDz-AiApXD8koUWWLewSrLgImrsLWcvtxXbGsD4mN8JbuHkoEQ%3D%3D'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\laure\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 1985, in process_info
    success = dl(filename, info_dict)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laure\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 1924, in dl
    return fd.download(name, info)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laure\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\downloader\common.py", line 366, in download
    return self.real_download(filename, info_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laure\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\downloader\http.py", line 351, in real_download
    establish_connection()
  File "C:\Users\laure\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\downloader\http.py", line 116, in establish_connection
    raise err
  File "C:\Users\laure\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\downloader\http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laure\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 2300, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laure\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laure\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\laure\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laure\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\laure\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

## Description

Has been working as of around a week ago. 2-3 days ago i started getting 403 on any youtube URL.

**Comment by walterhackin** [comment]
+

**Comment by dirkf** [comment]
You used to get throttled downloads with the 2021.12.17 version because
```
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unable to extract Initial JS player n function name; ...
```
but now you get 403 instead. Please review #30839 for solutions.
