### ISSUE TITLE
ERROR: Unable to extract uploader id; #new error 7/20/24#

### ISSUE THREAD

**Issue by nekmin** [ytdl-org/youtube-dl#32869]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
PS C:\Users\nekmin\Downloads> .\youtube-dl.exe -v https://www.youtube.com/watch?v=tf1uLwUTDA0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=tf1uLwUTDA0']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22621
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] tf1uLwUTDA0: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

PS C:\Users\nekmin\Downloads>
```

## Description

It just stopped working for me today as of a couple months ago all was fine and now I am getting the above error. I posted the verbose. Maybe there has been a change in the way yt handles files?

**Comment by ConnorRigby** [comment]
Just got this same error today as well

**Comment by Novaflux** [comment]
Same thing for me.

youtube-dl --yes-playlist "https://youtube.com/playlist?list=PLF8wHqMhTvJj1PoXHhBBVXW53cphfXTWk&si=28qNdlZ_zfWKS9im"
[youtube:tab] PLF8wHqMhTvJj1PoXHhBBVXW53cphfXTWk: Downloading webpage
[download] Downloading playlist: B Down
[youtube:tab] Downloading page 1
[youtube:tab] playlist B Down: Downloading 12 videos
[download] Downloading video 1 of 12
[youtube] oHIqKVkjNMQ: Downloading webpage
WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
ERROR: unable to download video data: HTTP Error 403: Forbidden
ryan@Ryans-MBP-2 ~ % youtube-dl --yes-playlist --verbose  "https://youtube.com/playlist?list=PLF8wHqMhTvJj1PoXHhBBVXW53cphfXTWk&si=28qNdlZ_zfWKS9im"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--yes-playlist', '--verbose', 'https://youtube.com/playlist?list=PLF8wHqMhTvJj1PoXHhBBVXW53cphfXTWk&si=28qNdlZ_zfWKS9im']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.12.4 (CPython) - macOS-14.5-x86_64-i386-64bit
[debug] exe versions: ffmpeg 7.0.1, ffprobe 7.0.1
[debug] Proxy map: {}
[youtube:tab] PLF8wHqMhTvJj1PoXHhBBVXW53cphfXTWk: Downloading webpage
[download] Downloading playlist: B Down
[youtube:tab] Downloading page 1
[youtube:tab] playlist B Down: Downloading 12 videos
[download] Downloading video 1 of 12
[youtube] oHIqKVkjNMQ: Downloading webpage
WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://rr2---sn-vgqsrnld.googlevideo.com/videoplayback?expire=1721520724&ei=9P2bZuarJtCglu8Pj-uK4AU&ip=150.195.97.149&id=o-ANsx1uyFLDmEEJNaFEDZvDI6nNoneJJrU8qr-FsFnBLh&itag=136&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C394%2C395%2C396%2C397%2C398&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=oS&mm=31%2C29&mn=sn-vgqsrnld%2Csn-vgqsknld&ms=au%2Crdu&mv=m&mvi=2&pl=24&initcwndbps=1036250&bui=AXc671KcW1oi1Fqe9znQAkdbCNtfhLCIcnYoTYjbBQJJM4RPL9B2JxZIFNFWRP7y6nMpwsWIyPD47o5N&spc=NO7bAZ5Ubb_wKasNfSwQsUTUEKDANgGwr6_0eYaxgpWnvc1hzJF0YMTHcZ3o&vprv=1&svpuc=1&mime=video%2Fmp4&ns=Xn07rewNuFWbTvKfva8ECSMQ&rqh=1&gir=yes&clen=705757857&dur=14594.765&lmt=1714345785574685&mt=1721498689&fvip=1&keepalive=yes&c=WEB&sefc=1&txp=5432434&n=XmQOgCOq8fh2MvZl&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgKEZIuMyo-NyXpzCYmbJJikKXClb10gkLMUGprc3-fPICIQCQ1enTZBzlMY_ffQnobxeygODWRf0g_qvbAwb4nzAAig%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRgIhAMS3CZaIR9g22mDugkY7nBJxKLGX0kei5PKz60TFML0fAiEA209baNqPl3zUhWLJAN7uu9JGlHs_w_yWhjF-9M19op4%3D'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.12/site-packages/youtube_dl/YoutubeDL.py", line 1970, in process_info
    partial_success = dl(fname, new_info)
                      ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.12/site-packages/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.12/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.12/site-packages/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.12/site-packages/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.12/site-packages/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.12/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by nekmin** [comment]
I solved it by using the took ytdl. It is the same tool with a more robust
set of features. When I get home I can link the repository if needed.

**Comment by dirkf** [comment]
It's like none of you never bothered to read #30839 as asked.

This bug is now a little infant that can walk and talk, pull stuff out of cupboards and stick its fingers in mains sockets. Just install a nightly version that doesn't have it.

>It just stopped working for me today as of a couple months ago all was fine and now I am getting the above error.

I very much doubt that that is the full story.

@Novaflux, your error is different and does result from a change how YT handles download links where the n-sig challenge has not been solved, from throttling to 403. But this issue, another Known Issue listed in #30839, is also fixed in the latest nightly build.
