### ISSUE TITLE
installation pb   versus  python

### ISSUE THREAD

**Issue by luisgonzalez-moviments-net** [ytdl-org/youtube-dl#32917]
luis@luis-ThinkPad-E570:~$ **sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   384  100   384    0     0    678      0 --:--:-- --:--:-- --:--:--   678
luis@luis-ThinkPad-E570:~$ **sudo chmod a+rx /usr/local/bin/youtube-dl**
luis@luis-ThinkPad-E570:~$ **youtube-dl 'https://www.youtube.com/watch?t=4&v=BaW_jenozKc'**
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading player 43bc9526
ERROR: BaW_jenozKc: Traceback (most recent call last):
  File "/home/luis/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1434, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/home/luis/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1407, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/home/luis/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1394, in _extract_n_function_name
    return self._search_regex(
  File "/home/luis/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
luis@luis-ThinkPad-E570:~$ 

## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by luisgonzalez-moviments-net** [comment]
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-189-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4

**Comment by luisgonzalez-moviments-net** [comment]
Finaly, the solución is to install the new version 2024.08.06-1
Following https://forums.linuxmint.com/viewtopic.php?t=417452
That means uninstall 2022.03.08.1  version and to get the new one add new repository:
sudo add-apt-repository ppa:tomtomtom/yt-dlp    # Add ppa repo to apt
sudo apt update                                 # Update package list
sudo apt install yt-dlp                         # Install yt-dlp
After that everything runs ok.
