### ISSUE TITLE
[Bug] `youtube-dl https://www.youtube.com/watch?v=YFgRW58mbG4 [youtube] YFgRW58mbG4: Downloading webpage ERROR: Unable to extract uploader id`

### ISSUE THREAD

**Issue by SwuduSusuwu** [ytdl-org/youtube-dl#32918]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
Welcome to Termux

Docs:       https://doc.termux.com
Community:  https://social.termux.com

Working with packages:
 - Search:  pkg search <query>
 - Install: pkg install <package>
 - Upgrade: pkg upgrade

Report issues at https://bugs.termux.com
~ $ youtube-dl --version
2021.12.17
~ $ youtube-dl -v https://www.youtube.com/watch?v=YFgRW58mbG4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=YFgRW58mbG4']
[debug] Encodings: locale utf-8, fs utf-8, out utf-8, pref utf-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.9 (CPython) - Linux-5.10.198-android13-4-00050-g12f3388846c3-ab11920634-aarch64-with
-libc
[debug] exe versions: ffmpeg 6.1.1, ffprobe 6.1.1
[debug] Proxy map: {}
[youtube] YFgRW58mbG4: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are usin
g the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --ver
bose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrap
per
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __ex
tract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, 
in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794
, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owne
r_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012,
 in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.or
g/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to 
call youtube-dl with the --verbose flag and include its complete output.

~ $
```

## Description

Am author of this _Youtube_ production; it is set to *public* / *Creative Commons* (allows derivatives/mixes)
This is on _Termujx_. _Termux_'s developer says to ask authors of _youtubedr_ / _youtube-dl_ to assist (https://github.com/termux/termux-packages/issues/21199)

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar issues including closed ones

Or not. See #30839. The termux issue is not related.
