### ISSUE TITLE
Extraction Failure: Unable to Retrieve Video Formats from Filemoon.sx

### ISSUE THREAD

**Issue by hiruy56** [ytdl-org/youtube-dl#32946]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\hmets\youtube-dl>youtube-dl --verbose https://filemoon.sx/d/jv6whayugrjc/vif.mp4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://filemoon.sx/d/jv6whayugrjc/vif.mp4']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python 3.12.4 (CPython AMD64 64bit) - Windows-11-10.0.22631-SP0 - OpenSSL 3.0.13 30 Jan 2024
[debug] exe versions: none
[debug] Proxy map: {}
[XFileShare] jv6whayugrjc: Downloading webpage
ERROR: No video formats found; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "C:\Users\hmets\AppData\Local\Programs\Python\Python312\Lib\site-packages\youtube_dl-2021.12.17-py3.12.egg\youtube_dl\YoutubeDL.py", line 875, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hmets\AppData\Local\Programs\Python\Python312\Lib\site-packages\youtube_dl-2021.12.17-py3.12.egg\youtube_dl\YoutubeDL.py", line 971, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\hmets\AppData\Local\Programs\Python\Python312\Lib\site-packages\youtube_dl-2021.12.17-py3.12.egg\youtube_dl\extractor\common.py", line 571, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hmets\AppData\Local\Programs\Python\Python312\Lib\site-packages\youtube_dl-2021.12.17-py3.12.egg\youtube_dl\extractor\xfileshare.py", line 278, in _real_extract
    self._sort_formats(result['formats'])
  File "C:\Users\hmets\AppData\Local\Programs\Python\Python312\Lib\site-packages\youtube_dl-2021.12.17-py3.12.egg\youtube_dl\extractor\common.py", line 1558, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.

```

## Description

I am trying to download a video from filemoon.sx using the URL `https://filemoon.sx/d/jv6whayugrjc/vif.mp4`, but I am unable to retrieve the `.m3u8` stream link, which is essential for downloading the video. Despite using both the pip version and the GitHub version of `youtube-dl`, I encounter the same issue. 
When I run the command:
youtube-dl --verbose -f best -o output.mp4 https://filemoon.sx/d/jv6whayugrjc/vif.mp4
I receive an error stating: "No video formats found." This error persists even though the URL is accessible and playable in a browser. I would appreciate your assistance in resolving this issue with the extractor for filemoon.sx, as obtaining the `.m3u8` link is critical for my download needs.

**Comment by dirkf** [comment]
Review #30839 **as asked** to find out how to install a version of the program that should solve your problem.

Please post a verbose log if that version fails, or close the issue.

**Comment by hiruy56** [comment]
Thank you for your response! I tried using the older version of yt-dlp as suggested. Here are the details of what I encountered:

Command Used: `youtube-dl https://filemoon.sx/e/jv6whayugrjc/vif.mp4 -v`
Verbose Output:
```
c:\Users\hmets\yt-dlp>python youtube-dl https://filemoon.sx/e/jv6whayugrjc/vif.mp4 -v
python: can't open file 'c:\\Users\\hmets\\yt-dlp\\youtube-dl': [Errno 2] No such file or directory

c:\Users\hmets\yt-dlp>youtube-dl https://filemoon.sx/e/jv6whayugrjc/vif.mp4 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://filemoon.sx/e/jv6whayugrjc/vif.mp4', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python 3.12.4 (CPython AMD64 64bit) - Windows-11-10.0.22631-SP0 - OpenSSL 3.0.13 30 Jan 2024
[debug] exe versions: none
[debug] Proxy map: {}
[FileMoon] jv6whayugrjc: Downloading webpage
Traceback (most recent call last):
  File "\\?\C:\Users\hmets\AppData\Local\Programs\Python\Python312\Scripts\youtube-dl-script.py", line 33, in <module>
    sys.exit(load_entry_point('youtube-dl==2021.12.17', 'console_scripts', 'youtube-dl')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hmets\AppData\Local\Programs\Python\Python312\Lib\site-packages\youtube_dl-2021.12.17-py3.12.egg\youtube_dl\__init__.py", line 473, in main
    _real_main(argv)
  File "C:\Users\hmets\AppData\Local\Programs\Python\Python312\Lib\site-packages\youtube_dl-2021.12.17-py3.12.egg\youtube_dl\__init__.py", line 463, in _real_main
    retcode = ydl.download(all_urls)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hmets\AppData\Local\Programs\Python\Python312\Lib\site-packages\youtube_dl-2021.12.17-py3.12.egg\youtube_dl\YoutubeDL.py", line 2218, in download
    res = self.extract_info(
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hmets\AppData\Local\Programs\Python\Python312\Lib\site-packages\youtube_dl-2021.12.17-py3.12.egg\youtube_dl\YoutubeDL.py", line 852, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hmets\AppData\Local\Programs\Python\Python312\Lib\site-packages\youtube_dl-2021.12.17-py3.12.egg\youtube_dl\YoutubeDL.py", line 859, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hmets\AppData\Local\Programs\Python\Python312\Lib\site-packages\youtube_dl-2021.12.17-py3.12.egg\youtube_dl\YoutubeDL.py", line 955, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\hmets\AppData\Local\Programs\Python\Python312\Lib\site-packages\youtube_dl-2021.12.17-py3.12.egg\youtube_dl\extractor\common.py", line 571, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hmets\AppData\Local\Programs\Python\Python312\Lib\site-packages\youtube_dl-2021.12.17-py3.12.egg\youtube_dl\extractor\filemoon.py", line 30, in _real_extract
    packed = matches[-1]
             ~~~~~~~^^^^
IndexError: list index out of range
```
my downgraded version is `2021.12.17` because it is the version with the individual filemoon.sx python file

**Comment by dirkf** [comment]
If you're using yt-dlp, ask about it there, but the site you're using may not be supported.

The nightly build of this program, as linked from #30839, should support the site: it did when the extractor was last updated.

**Comment by dirkf** [comment]
From the UK the problem video is blocked `not available in your country`. This condition is not trapped, yet.

**Comment by Ionic** [comment]
It's broken indeed, but not severely.

They started using a "landing page" and embedding an `iframe` into that, which loads the actual page/player.

A quick and dirty fix is to change the extractor (`_real_extract`) to detect and fetch the content of the `iframe` instead:

```
        matched = self._search_regex(r'<iframe\b[^>]+\bsrc=(["\'])(?P<url>(?:https?:)?//(.*?/%s))\1' % video_id, webpage, 'embedded url', group=2, default=None, fatal=False)
        if matched:
            webpage = self._download_webpage(matched, video_id, 'Downloading embedded video page', headers={ 'Referer': url })
```

As said, quick and dirty, though. No idea what that might do to other XFileShare-supported sites, and I'm not in the mood to create a full PR for this.

**Comment by dirkf** [comment]
Exactly what I found (with a different page -- see below), so there's no need: see new update to #32944.

Regarding the problem page:
```console
$ python -m youtube_dl -vF 'https://filemoon.sx/d/jv6whayugrjc/vif.mp4'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vF', u'https://filemoon.sx/d/jv6whayugrjc/vif.mp4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: aae565d56
[debug] Python 2.7.15 (CPython i686 32bit) - Linux-6.1.0-25-686-pae-i686-with-debian-12.7 - OpenSSL 1.1.1a  20 Nov 2018 - glibc 2.1.3
[debug] exe versions: ffmpeg 5.1.6-0, ffprobe 5.1.6-0
[debug] Proxy map: {}
[XFileShare] jv6whayugrjc: Downloading webpage
ERROR: This video is not available from your location due to geo restriction
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 875, in wrapper
    return func(self, *args, **kwargs)
  File "youtube_dl/YoutubeDL.py", line 971, in __extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 571, in extract
    ie_result = self._real_extract(url)
  File "youtube_dl/extractor/xfileshare.py", line 216, in _real_extract
    self.raise_geo_restricted()
  File "youtube_dl/extractor/common.py", line 1025, in raise_geo_restricted
    raise GeoRestrictedError(msg, countries=countries)
GeoRestrictedError: This video is not available from your location due to geo restriction

$
```
If someone would care to test the PR in a location other than UK and post some other sort of result here, that would be reassuring (or helpful, if it failed).

**Comment by Ionic** [comment]
ACK. WORKSFORME.

**Comment by Ionic** [comment]
Ironically, though, there is another issue for this video (which I haven't seen with others) because they started to detect public VPNs (and which also produces broken HTML... *sigh*):

```
<body>
</body>
<div class="container">
  <div class="error geolimit">
    <div class="error-footer">
      <h1>Access Denied VPN Detected.</h1>
	  <p>FileMoon does not store nor track any data about you. We respect your privacy. In order to let us exist and watch the video please disable VPN/Proxy.</p>
	  <p>Your IP:<span id="ip">a.b.c.d</span></p>
	  <p id="asn" style="display:none">xyz</p>
	  <p id="info">You're not using VPN/Proxy? Click the button below to report false detection.</p>
      <a href="#" class="button" id="imnotvpn">I'm not using VPN!</a>
    </div>
  </div>
</div>
```

The geo block detection in 0ddcc15fd175a2a5962bc3f51dcaf89fbc18a9ab could be extended to match on the `geolimit` div class (I wouldn't trust parsing the message with a regexp, that might change more easily). Clicking the button does nothing, btw, so it's not a magic "LETMEIN" button.

**Comment by dirkf** [comment]
Are you able to test the problem video from a non-VPN-blocked IP address, maybe with a mobile hotspot? Just `-vF` is fine, no need to fetch the actual media. Or @hiruy56?

I take yr point on regexes but we're already deep in there; let's systematise:
```diff
--- f7dc45d/youtube_dl/extractor/xfileshare.py
+++ new/youtube_dl/extractor/xfileshare.py
@@ -206,18 +206,20 @@ class XFileShareIE(InfoExtractor):
             get_element_by_id('container', main)
             or get_element_by_class('container', main)
             or webpage)
-        if self._search_regex(
-                r'>This server is in maintenance mode\.', container_div,
-                'maint error', group=0, default=None):
-            raise ExtractorError(clean_html(container_div), expected=True)
-        if self._search_regex(
-                'not available in your country', container_div,
-                'geo block', group=0, default=None):
-            self.raise_geo_restricted()
-        if self._search_regex(
-                self._FILE_NOT_FOUND_REGEXES, container_div,
-                'missing video error', group=0, default=None):
-            raise ExtractorError('Video %s does not exist' % video_id, expected=True)
+
+        def raise_ExtractorError(html, expected=True):
+            raise ExtractorError(clean_html(html), expected=expected)
+
+        BADNESS = (
+            (r'>This server is in maintenance mode\.', 'maint error', raise_ExtractorError),
+            (r'>Access Denied VPN Detected\.', 'VPN error', raise_ExtractorError),
+            ('not available in your country', 'geo block', lambda _: self.raise_geo_restricted()),
+            (self._FILE_NOT_FOUND_REGEXES, 'missing video error',
+                lambda _: raise_ExtractorError('Video %s does not exist' % (video_id,), expected=True)),
+        )
+        for symptoms, desc, action in BADNESS:
+            if self._search_regex(symptoms, container_div, desc, group=0, default=None):
+                action(container_div)
 
         fields = self._hidden_inputs(webpage)
 
```

**Comment by Ionic** [comment]
I've tested the problematic video both with a VPN and with bypassing a VPN. :)

The youtube-dl output I posted for https://filemoon.sx/d/fbsxidybremo was without a VPN, which obviously worked fine, but with a VPN, the site only returned the error page described (with irrelevant data removed) in my later comment. It's been the same video, just one without and once with going through a VPN.

With that patch, the format selection still comes out without going through a VPN, with going through a VPN, the exception probably looks kinda confusing to users:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://filemoon.sx/d/fbsxidybremo', '-v', '--no-warnings', '--flat-playlist', '--sub-format', 'ass/srt/best', '--format', 'best', '--user-agent', 'Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0', '--verbose', '--all-subs', '--no-playlist', '-F']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: aae565d56
[debug] Python 3.10.2 (CPython x86_64 64bit) - Linux-6.9.1-x86_64-Intel-R-_Core-TM-_i7-7700K_CPU_@_4.20GHz-with-glibc2.34 - OpenSSL 1.1.1m  14 Dec 2021 - glibc 2.34
[debug] exe versions: ffmpeg 6.1.2, ffprobe 6.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[XFileShare] fbsxidybremo: Downloading webpage
 RROR: A  FileMoon does not store nor track any data about you. We respect your privacy. In order to let us exist and watch the video please disable VPN/Proxy.
Your IP:a.b.c.d
xyz
       I'm not using VPN!y? Click the button below to report false detection.
Traceback (most recent call last):
  File "/home/ionic/src/youtube-dl-git/youtube_dl/YoutubeDL.py", line 875, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ionic/src/youtube-dl-git/youtube_dl/YoutubeDL.py", line 971, in __extract_info
    ie_result = ie.extract(url)
  File "/home/ionic/src/youtube-dl-git/youtube_dl/extractor/common.py", line 571, in extract
    ie_result = self._real_extract(url)
  File "/home/ionic/src/youtube-dl-git/youtube_dl/extractor/xfileshare.py", line 226, in _real_extract
    action(container_div)
  File "/home/ionic/src/youtube-dl-git/youtube_dl/extractor/xfileshare.py", line 215, in raise_ExtractorError
    raise ExtractorError(clean_html(html), expected=expected)
 outube_  FileMoon does not store nor track any data about you. We respect your privacy. In order to let us exist and watch the video please disable VPN/Proxy.
Your IP:a.b.c.d
xyz
       I'm not using VPN!y? Click the button below to report false detection.

```

**Comment by Ionic** [comment]
> > ... probably looks kinda confusing to users
> 
> Agreed, but also your wrapper script seems to be eliding and/or mixing up some of the error text (`STDERR` vs `STDOUT`?), eg ` RROR: A FileMoon does not store nor track any data about you. ...`

I know, it looks as such, but really isn't the case. The wrapper is simple:

```bash
#!/bin/bash

typeset cur_arg=''
typeset -a new_args
new_args=()
for cur_arg in "${@}"; do
  if [ '--legacy-server-connect' != "${cur_arg}" ]; then
    new_args+=( "${cur_arg}" )
  fi
done
exec env 'PYTHONPATH=/home/ionic/src/youtube-dl-git' 'python3.10' -m 'youtube_dl' "${new_args[@]}"
```

and I'm getting the same output if ran directly:

```
ionic@apgunner~/src/youtube-dl-git(git)-[master] %  python3.10 -m youtube_dl 'https://filemoon.sx/d/fbsxidybremo' -v --no-warnings --flat-playlist --sub-format 'ass/srt/best' --format 'best' --user-agen
t 'Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0' --verbose --all-subs --no-playlist
[debug] System config: []                                                                            
[debug] User config: []                                                                              
[debug] Custom config: []                                                                            
[debug] Command-line args: ['https://filemoon.sx/d/fbsxidybremo', '-v', '--no-warnings', '--flat-playlist', '--sub-format', 'ass/srt/best', '--format', 'best', '--user-agent', 'Mozilla/5.0 (X11; Linux x
86_64; rv:96.0) Gecko/20100101 Firefox/96.0', '--verbose', '--all-subs', '--no-playlist']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: aae565d56
[debug] Python 3.10.2 (CPython x86_64 64bit) - Linux-6.9.1-x86_64-Intel-R-_Core-TM-_i7-7700K_CPU_@_4.20GHz-with-glibc2.34 - OpenSSL 1.1.1m  14 Dec 2021 - glibc 2.34
[debug] exe versions: ffmpeg 6.1.2, ffprobe 6.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[XFileShare] fbsxidybremo: Downloading webpage
 RROR: A  FileMoon does not store nor track any data about you. We respect your privacy. In order to let us exist and watch the video please disable VPN/Proxy.
Your IP:a.b.c.d
xyz
       I'm not using VPN!y? Click the button below to report false detection.
Traceback (most recent call last):
  File "/home/ionic/src/youtube-dl-git/youtube_dl/YoutubeDL.py", line 875, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ionic/src/youtube-dl-git/youtube_dl/YoutubeDL.py", line 971, in __extract_info
    ie_result = ie.extract(url)
  File "/home/ionic/src/youtube-dl-git/youtube_dl/extractor/common.py", line 571, in extract
    ie_result = self._real_extract(url)
  File "/home/ionic/src/youtube-dl-git/youtube_dl/extractor/xfileshare.py", line 226, in _real_extract
    action(container_div)
  File "/home/ionic/src/youtube-dl-git/youtube_dl/extractor/xfileshare.py", line 215, in raise_ExtractorError
    raise ExtractorError(clean_html(html), expected=expected)
 outube_  FileMoon does not store nor track any data about you. We respect your privacy. In order to let us exist and watch the video please disable VPN/Proxy.
Your IP:a.b.c.d
xyz
       I'm not using VPN!y? Click the button below to report false detection.

```

Whatever is mangling the output, it wasn't me doing it.

Yeah, with the modified `raise_ExtractorError` function, I'm seeing this, which is much clearer:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://filemoon.sx/d/fbsxidybremo', '-v', '--no-warnings', '--flat-playlist', '--sub-format', 'ass/srt/best', '--format', 'best', '--user-agent', 'Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0', '--verbose', '--all-subs', '--no-playlist', '-F']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: aae565d56
[debug] Python 3.10.2 (CPython x86_64 64bit) - Linux-6.9.1-x86_64-Intel-R-_Core-TM-_i7-7700K_CPU_@_4.20GHz-with-glibc2.34 - OpenSSL 1.1.1m  14 Dec 2021 - glibc 2.34
[debug] exe versions: ffmpeg 6.1.2, ffprobe 6.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[XFileShare] fbsxidybremo: Downloading webpage
ERROR: Access Denied VPN Detected.
Traceback (most recent call last):
  File "/home/ionic/src/youtube-dl-git/youtube_dl/YoutubeDL.py", line 875, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ionic/src/youtube-dl-git/youtube_dl/YoutubeDL.py", line 971, in __extract_info
    ie_result = ie.extract(url)
  File "/home/ionic/src/youtube-dl-git/youtube_dl/extractor/common.py", line 571, in extract
    ie_result = self._real_extract(url)
  File "/home/ionic/src/youtube-dl-git/youtube_dl/extractor/xfileshare.py", line 228, in _real_extract
    action(container_div)
  File "/home/ionic/src/youtube-dl-git/youtube_dl/extractor/xfileshare.py", line 215, in raise_ExtractorError
    raise ExtractorError(clean_html(self._search_regex(
youtube_dl.utils.ExtractorError: Access Denied VPN Detected.

```

(and, for some reason, the output isn't mangled any longer.)

**Comment by piotr47234** [comment]
Do you support downloading from: **filemoon.to** ? 

**Example URLs**
https://filemoon.to/e/ww8931by5kdw
https://filemoon.to/e/vxkeptfavoa6

**Complete Verbose Output**

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vU', 'https://filemoon.to/e/vxkeptfavoa6']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 55ad8a24c
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.15.158-2-pve-x86_64-with-glibc2.36 - OpenSSL 1.1.1w  11 Sep 2023 - glibc 2.36
[debug] exe versions: ffmpeg 4.3.8-0, ffprobe 4.3.8-0
[debug] Proxy map: {}
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.
[generic] vxkeptfavoa6: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vxkeptfavoa6: Downloading webpage
[generic] vxkeptfavoa6: Extracting information
ERROR: Unsupported URL: https://filemoon.to/e/vxkeptfavoa6
Traceback (most recent call last):
  File "/opt/youtube-dl/youtube_dl/YoutubeDL.py", line 875, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/youtube-dl/youtube_dl/YoutubeDL.py", line 971, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/youtube-dl/youtube_dl/extractor/common.py", line 571, in extract
    ie_result = self._real_extract(url)
  File "/opt/youtube-dl/youtube_dl/extractor/generic.py", line 3704, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://filemoon.to/e/vxkeptfavoa6

```

**Comment by dirkf** [comment]
Working in the linked PR, or will be when it's been updated to send the `Sec-Fetch-Dest` that Cloudflare wants when opening an iframe embed.
