### ISSUE TITLE
Servus TV live stream

### ISSUE THREAD

**Issue by Reiner1210** [ytdl-org/youtube-dl#32983]
https://www.servustv.com/jetzt-live/

Output:
`yt-dlp -v  https://www.servustv.com/jetzt-live/
[debug] Command-line config: ['-v', 'https://www.servustv.com/jetzt-live/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (zip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-49-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.46.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.1, urllib3-2.0.7, websockets-10.4
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[generic] Extracting URL: https://www.servustv.com/jetzt-live/
[generic] jetzt-live: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] jetzt-live: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.servustv.com/jetzt-live/
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1624, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1759, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2553, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.servustv.com/jetzt-live/`

**Comment by dirkf** [comment]
#30839: "... if you were actually running _yt-dlp_ ..."

Note to self: we need to back-port https://github.com/yt-dlp/yt-dlp/pull/10944 to close the antique issue #29485.
