### ISSUE TITLE
www.youtube.com ERROR: No video formats found; WARNING: Signature extraction failed using 2024.08.07 [c5098961b]

### ISSUE THREAD

**Issue by Ichigo271** [ytdl-org/youtube-dl#32993]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've also tried the latest nightly build youtube-dl version 2024.08.07 [c5098961b] (single file build)
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones (there are duplicates but with people using outdated builds)
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\Ichigo271\Downloads>youtube-dl --verbose "https://www.youtube.com/watch?v=v8l1AoETPiQ"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=v8l1AoETPiQ']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2024.08.07 [c5098961b] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 3.4.4 (CPython AMD64 32bit) - Windows-10-10.0.19041 - OpenSSL 1.0.2d 9 Jul 2015
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] v8l1AoETPiQ: Downloading webpage
[debug] [youtube] Extracting signature function js_5b77d519_110
[youtube] v8l1AoETPiQ: Downloading player 5b77d519
WARNING: [youtube] v8l1AoETPiQ: Signature extraction failed: Some formats may be missing
[debug] [youtube] Could not find JS function "decodeURIComponent"; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
[debug] [youtube] Extracting signature function js_5b77d519_106
ERROR: No video formats found; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\YoutubeDL.py", line 879, in wrapper
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\YoutubeDL.py", line 975, in __extract_info
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\common.py", line 571, in extract
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\youtube.py", line 2250, in _real_extract
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\common.py", line 1558, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.


C:\Users\Ichigo271\Downloads>youtube-dl --verbose -U
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-U']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2024.08.07 [c5098961b] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 3.4.4 (CPython AMD64 32bit) - Windows-10-10.0.19041 - OpenSSL 1.0.2d 9 Jul 2015
[debug] exe versions: none
[debug] Proxy map: {}
Latest version: 2024.08.07, Current version: 2024.08.07
youtube-dl is up to date (2024.08.07)
```

## Description

ERROR: No video formats found; using:
`youtube-dl --verbose "https://www.youtube.com/watch?v=v8l1AoETPiQ"`

Thank you

**Comment by Ichigo271** [comment]
duplicate https://github.com/ytdl-org/youtube-dl/issues/32986

**Comment by dirkf** [comment]
Actually #32986, I think.
