### ISSUE TITLE
add support for ets.org

### ISSUE THREAD

**Issue by Siddhant** [ytdl-org/youtube-dl#3873]
$ youtube-dl --verbose "https://www.ets.org/s/toefl/flash/15571_toefl_prometric.html"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.ets.org/s/toefl/flash/15571_toefl_prometric.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.10.02
[debug] Python version 2.7.8 - Linux-3.16.0-18-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] Proxy map: {'http': 'REDACTED', 'https': 'REDACTED'}
[generic] 15571_toefl_prometric: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 15571_toefl_prometric: Downloading webpage
[generic] 15571_toefl_prometric: Extracting information
ERROR: Unsupported URL: https://www.ets.org/s/toefl/flash/15571_toefl_prometric.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 524, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 191, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 897, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: https://www.ets.org/s/toefl/flash/15571_toefl_prometric.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by Siddhant** [comment]
This works now, albeit using the generic extractor:
```
youtube-dl.exe https://www.ets.org/s/toefl/flash/15571_toefl_prometric.html
[generic] 15571_toefl_prometric: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 15571_toefl_prometric: Downloading webpage
[generic] 15571_toefl_prometric: Extracting information
[Kaltura] 1_79agkdh8: Downloading video info JSON
[Kaltura] 1_79agkdh8: Downloading m3u8 information
[download] Destination: 15571_TOEFL_Prometric_Final-1_79agkdh8.flv
[download] 100% of 53.79MiB in 00:23
```
