### ISSUE TITLE
[YouTube] Error: YouTube said....Playback on other websites has been disabled by the video owner.

### ISSUE THREAD

**Issue by TheBoroer** [ytdl-org/youtube-dl#4162]
The error shows up when trying to download this video: `http://www.youtube.com/watch?v=HCtUQdQ--ME`

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.youtube.com/watch?v=HCtUQdQ--ME']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.11.09
[debug] Python version 2.6.6 - Linux-3.10.23-xxxx-std-ipv6-64-x86_64-with-centos-6.6-Final
[debug] exe versions: ffmpeg 0.6.5, ffprobe 0.6.5
[debug] Proxy map: {}
[youtube] Confirming age
[youtube] HCtUQdQ--ME: Downloading webpage
[youtube] HCtUQdQ--ME: Downloading video info webpage
[youtube] HCtUQdQ--ME: Refetching age-gated info webpage
ERROR: HCtUQdQ--ME: YouTube said: <a href="http://www.youtube.com/watch?v=HCtUQdQ--ME&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
Traceback (most recent call last):
  File "./youtube-link/youtube_dl/YoutubeDL.py", line 536, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-link/youtube_dl/extractor/common.py", line 199, in extract
    return self._real_extract(url)
  File "./youtube-link/youtube_dl/extractor/youtube.py", line 717, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: HCtUQdQ--ME: YouTube said: <a href="http://www.youtube.com/watch?v=HCtUQdQ--ME&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
```

**Comment by bbashy** [comment]
Did you use login to confirm age?

**Comment by The-Compiler** [comment]
I just got the same on 2016.07.03.1, even when logging in:

```
$ youtube-dl -v 'https://www.youtube.com/watch?v=DJOX0c60wQE' --netrc
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=DJOX0c60wQE', '--netrc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.03.1
[debug] Python version 3.5.2 - Linux-4.6.2-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Logging in
[youtube] DJOX0c60wQE: Downloading webpage
[youtube] DJOX0c60wQE: Downloading embed webpage
[youtube] DJOX0c60wQE: Refetching age-gated info webpage
ERROR: DJOX0c60wQE: YouTube said: <a href="http://www.youtube.com/watch?v=DJOX0c60wQE&feature=player_embedded" target="_blank">Watch this video on YouTube.</a>
Playback on other websites has been disabled by the video owner.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 681, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 343, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1317, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: DJOX0c60wQE: YouTube said: <a href="http://www.youtube.com/watch?v=DJOX0c60wQE&feature=player_embedded" target="_blank">Watch this video on YouTube.</a>
Playback on other websites has been disabled by the video owner.
```

**Comment by bbashy** [comment]
@The-Compiler Just looks like it's been updated by YT. Also see #4627

**Comment by Kaos-Industries** [comment]
Also having the same problem. Successfully used the `-u` and `-p` options to login via `cmd` on Windows, but unfortunately the video still can't be downloaded to the embedding issue. Does anyone if there's a workaround for this yet?

**Comment by HermitCountry** [comment]
Same issue as above. Login through --netrc works but getting 'Playback on other websites has been disabled by the video owner' error. 

```
[debug] System config: [u'-o', u'~/Movies/%(title)s.%(ext)s', u'--write-sub', u'--convert-subs', u'srt', u'--embed-subs']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--netrc', u'-f', u'bestvideo[ext=mp4]+bestaudio', u'https://www.youtube.com/watch?v=_by9vE3trI8', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.26
[debug] Python version 2.7.12 - Linux-4.4.0-34-generic-x86_64-with-LinuxMint-18-sarah
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[youtube] Downloading login page
[youtube] Logging in
[youtube] _by9vE3trI8: Downloading webpage
[youtube] _by9vE3trI8: Downloading embed webpage
[youtube] _by9vE3trI8: Refetching age-gated info webpage
ERROR: _by9vE3trI8: YouTube said: <a href="http://www.youtube.com/watch?v=_by9vE3trI8&feature=player_embedded" target="_blank">Watch this video on YouTube.</a>
Playback on other websites has been disabled by the video owner.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1388, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: _by9vE3trI8: YouTube said: <a href="http://www.youtube.com/watch?v=_by9vE3trI8&feature=player_embedded" target="_blank">Watch this video on YouTube.</a>
Playback on other websites has been disabled by the video owner.
```

**Comment by yan12125** [comment]
Works for me. Could you watch that video with the provided account?
```
$ youtube-dl --netrc _by9vE3trI8 -v 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--netrc', '_by9vE3trI8', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.26
[debug] Git HEAD: b62985a9a
[debug] Python version 3.6.1 - Linux-4.10.11-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Logging in
[youtube] _by9vE3trI8: Downloading webpage
[youtube] _by9vE3trI8: Downloading video info webpage
[youtube] _by9vE3trI8: Extracting video information
[youtube] _by9vE3trI8: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r3---sn-u5oxu-un5e.googlevideo.com/videoplayback?id=fdbcbdbc4dedac8f&itag=134&source=youtube&requiressl=yes&pl=21&initcwndbps=6853750&mv=m&ms=au&mn=sn-u5oxu-un5e&mm=31&pcm2cms=yes&ei=jxADWYv1PJSV4AKv2aTACw&ratebypass=yes&mime=video/mp4&gir=yes&clen=177339236&lmt=1432564147323547&dur=6069.028&key=dg_yt0&mt=1493372726&signature=6D0C0224F8B7CEBE5B4EEFE5F9EF88EE0D7399FF.12D18E96CBFBB827DF012542D6B787394B7F7A8B&upn=Mesf06Eekbc&ip=140.112.28.103&ipbits=0&expire=1493394672&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,initcwndbps,mv,ms,mn,mm,pcm2cms,ei,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: 길소뜸 Kilsodeum (1985)-_by9vE3trI8.f134.mp4
[download]   9.5% of 169.12MiB at  9.51MiB/s ETA 00:16^CException ignored in: <_io.FileIO name='길소뜸 Kilsodeum (1985)-_by9vE3trI8.f134.mp4.part' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedWriter name='길소뜸 Kilsodeum (1985)-_by9vE3trI8.f134.mp4.part'>

ERROR: Interrupted by user
```

**Comment by HermitCountry** [comment]
Thank you for the response, that saved me a lot of time. It was something with the Google account I was using. 2-step authentication was off and it looked like it was logging in in the debugger but it kept going to the embedded video. I'm not sure why.

I created a new account and it works as expected. Thanks again.

**Comment by dirkf** [comment]
Tier 4 in https://github.com/yt-dlp/yt-dlp/pull/575#issuecomment-888837000.
