### ISSUE TITLE
Problem with downloading a video from Google Plus

### ISSUE THREAD

**Issue by dmitripavlov** [ytdl-org/youtube-dl#4955]
~: youtube-dl -v https://plus.google.com/+AndrejBauer/posts/U5krg2ygZzL
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://plus.google.com/+AndrejBauer/posts/U5krg2ygZzL']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.11
[debug] Python version 3.4.2 - Linux-3.14.4-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.5.4, ffprobe 2.5.4, rtmpdump 2.4
[debug] Proxy map: {}
[plus.google] U5krg2ygZzL: Downloading entry webpage
WARNING: unable to extract OpenGraph description; please report this issue on http://yt-dl.org/bug
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2015.2.11', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.4/site-packages/youtube_dl/**init**.py", line 388, in main
    _real_main(argv)
  File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 378, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1387, in download
    res = self.extract_info(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 633, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 270, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/googleplus.py", line 32, in _real_extract
    title = self._og_search_description(webpage).splitlines()[0]
AttributeError: 'NoneType' object has no attribute 'splitlines'

**Comment by katamari1992** [comment]
Looks like I've got the same thing

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-F', 'https://www.youtube.com/playlist?list=PL20AF733A429E766E', '-v']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.16.0-34-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] Proxy map: {}
[youtube:playlist] PL20AF733A429E766E: Downloading page #1
WARNING: [youtube:playlist] PL20AF733A429E766E: Playlist page is missing OpenGraph title, falling back ...
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1511, in _real_extract
    playlist_title = self._og_search_title(page)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 428, in _og_search_title
    return self._og_search_property('title', html, **kargs)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 416, in _og_search_property
    escaped = self._search_regex(self._og_regexes(prop), html, name, flags=re.DOTALL, **kargs)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1517, in _real_extract
    r'<h1 class="pl-header-title">(.*?)</h1>', page, u'title')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 366, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by jaimeMF** [comment]
@katamari1992 your issue is unrelated, [you have to update youtube-dl](https://github.com/rg3/youtube-dl/blob/50b901306406d5c37f31880860e2a4dbb5e0a165/README.md#how-do-i-update-youtube-dl).
