### ISSUE TITLE
Add support for external.global.media.yahoo.com

### ISSUE THREAD

**Issue by mgilbir** [ytdl-org/youtube-dl#5743]
Example: https://external.global.media.yahoo.com/video/yahoo-trust-unconference-tls-adam-223046696.html?format=embed&player_autoplay=false

**Comment by jaimeMF** [comment]
Note that https://screen.yahoo.com/yahoo-trust-unconference-tls-adam-223046696.html (and other yahoo urls) are supported. I guess we could add support for the embedded url, but where did you get it?

**Comment by mgilbir** [comment]
I got the link directly in a [tweet](https://twitter.com/FredericJacobs/status/600030812789149696).

If there is a predictable way to convert the embedded URLs to something that is already supported it would be a great UX improvement.

**Comment by mgilbir** [comment]
I found the video again, and checked that it does not work with `2018.08.04`

https://www.yahoo.com/news/video/yahoo-trust-unconference-tls-adam-223046696.html

**Comment by mgilbir** [comment]
@remitamine Has this been fixed? I just tried with the 2019.10.29 version and it still doesn't work.

**Comment by remitamine** [comment]
external.global.media.yahoo.com domain is dead.
and for the second URL it works just fine.

**Comment by mgilbir** [comment]
```
$ youtube-dl --verbose https://www.yahoo.com/news/video/yahoo-trust-unconference-tls-adam-223046696.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.yahoo.com/news/video/yahoo-trust-unconference-tls-adam-223046696.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.29
[debug] Python version 2.7.17 (CPython) - Darwin-19.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, rtmpdump 2.4
[debug] Proxy map: {}
[Yahoo] yahoo-trust-unconference-tls-adam: Downloading webpage
ERROR: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/yahoo.py", line 350, in _real_extract
    CONTENT_ID_REGEXES, webpage, 'content ID')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by remitamine** [comment]
with the latest release:
```
youtube-dl https://www.yahoo.com/news/video/yahoo-trust-unconference-tls-adam-223046696.html
[Yahoo] yahoo-trust-unconference-tls-adam: Downloading webpage
[Yahoo] yahoo-trust-unconference-tls-adam: Downloading webm video info
[Yahoo] yahoo-trust-unconference-tls-adam: Downloading mp4 video info
[Yahoo] 893f78e4-af4b-3fda-8475-d55277fb129b: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[download] Destination: Yahoo Trust Unconference - TLS, Adam Langley-893f78e4-af4b-3fda-8475-d55277fb129b.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  857M    0 1217k    0     0   295k      0  0:49:32  0:00:04  0:49:28  295k
```
and did make some improvements that willl take effect in the next version:
```
python __main__.py https://www.yahoo.com/news/video/yahoo-trust-unconference-tls-adam-223046696.html
[Yahoo] yahoo-trust-unconference-tls-adam-223046696: Downloading content JSON metadata
[Yahoo] 893f78e4-af4b-3fda-8475-d55277fb129b: Downloading video JSON metadata
[Yahoo] 893f78e4-af4b-3fda-8475-d55277fb129b: Downloading webm JSON metadata
[Yahoo] 893f78e4-af4b-3fda-8475-d55277fb129b: Downloading mp4 JSON metadata
[Yahoo] 893f78e4-af4b-3fda-8475-d55277fb129b: Downloading m3u8 information
[download] Destination: Yahoo Trust Unconference - TLS, Adam Langley-893f78e4-af4b-3fda-8475-d55277fb129b.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  857M    0 80716    0     0  14638      0 17:03:53  0:00:05 17:03:48 16489
```
