### ISSUE TITLE
Please add support for www.avclub.com

### ISSUE THREAD

**Issue by clampak** [ytdl-org/youtube-dl#5756]
Example link: http://www.avclub.com/video/bela-fleck-and-abigail-washburn-cover-final-countd-219612

```
$ youtube-dl -v http://www.avclub.com/video/bela-fleck-and-abigail-washburn-cover-final-countd-219612
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.avclub.com/video/bela-fleck-and-abigail-washburn-cover-final-countd-219612']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.15
[debug] Python version 2.7.9 - CYGWIN_NT-5.1-2.0.2-0.287-5-3-i686-32bit
[debug] exe versions: ffmpeg N-72211-g451be67, ffprobe N-72211-g451be67, rtmpdump 2.4
[debug] Proxy map: {}
[generic] bela-fleck-and-abigail-washburn-cover-final-countd-219612: Requesting header
WARNING: Falling back on generic information extractor.
[generic] bela-fleck-and-abigail-washburn-cover-final-countd-219612: Downloading webpage
[generic] bela-fleck-and-abigail-washburn-cover-final-countd-219612: Extracting information
ERROR: Unsupported URL: http://www.avclub.com/video/bela-fleck-and-abigail-washburn-cover-final-countd-219612
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 937, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/lib/python2.7/site-packages/youtube_dl/utils.py", line 1558, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: undefined entity: line 39, column 75
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1467, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.avclub.com/video/bela-fleck-and-abigail-washburn-cover-final-countd-219612

```

**Comment by TRox1972** [comment]
To developers: onionstudioes embed.
