### ISSUE TITLE
[site-support-request] rat-porn.com

### ISSUE THREAD

**Issue by NyeMitchLee** [ytdl-org/youtube-dl#5931]
Example URL:
http://www.rat-porn.com/video/312/pretty-18yo-blonde-fucked-on-cam

```
$ youtube-dl -v 'http://www.rat-porn.com/video/312/pretty-18yo-blonde-fucked-on-cam'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.rat-porn.com/video/312/pretty-18yo-blonde-fucked-on-cam']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.29
[debug] Python version 3.4.3 - Linux-4.0.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] pretty-18yo-blonde-fucked-on-cam: Requesting header
WARNING: Falling back on generic information extractor.
[generic] pretty-18yo-blonde-fucked-on-cam: Downloading webpage
[generic] pretty-18yo-blonde-fucked-on-cam: Extracting information
ERROR: Unsupported URL: http://www.rat-porn.com/video/312/pretty-18yo-blonde-fucked-on-cam
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 1504, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.rat-porn.com/video/312/pretty-18yo-blonde-fucked-on-cam
```

**Comment by dirkf** [comment]
Site gone.
