### ISSUE TITLE
EOnline Videos - UnsupportedError

### ISSUE THREAD

**Issue by MaryCoding** [ytdl-org/youtube-dl#6198]
I tried to download a video from www.eonline.com  but it currently is not supported by youtube-dl. Below are details. Thanks for your help.

```
youtube-dl -v -o "/media/test.%(ext)s" "http://www.eonline.com/videos/237478/check-out-the-craziest-celeb-comments"
[debug] System config: [u'--ffmpeg-location', u'/home/mary/bin/ffmpeg']
[debug] User config: []
[debug] Command-line args: [u'-v', u'-o', u'/media/test.%(ext)s', u'http://www.eonline.com/videos/237478/check-out-the-craziest-celeb-comments']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.9 - Linux-3.19.0-21-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: ffmpeg 2.6.git, ffprobe 2.6.git, rtmpdump 2.4
[debug] Proxy map: {}
[generic] check-out-the-craziest-celeb-comments: Requesting header
WARNING: Could not send HEAD request to http://www.eonline.com/videos/237478/check-out-the-craziest-celeb-comments: HTTP Error 405: Method Not Allowed
[generic] check-out-the-craziest-celeb-comments: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] check-out-the-craziest-celeb-comments: Extracting information
ERROR: Unsupported URL: http://www.eonline.com/videos/237478/check-out-the-craziest-celeb-comments
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1092, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1562, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 141, column 30
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1663, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.eonline.com/videos/237478/check-out-the-craziest-celeb-comments
```

_UPD by dstftw:_
Geo restricted example URL: `http://www.eonline.com/videos/237478/check-out-the-craziest-celeb-comments`. US or CA IP is required.
Geo unrestricted example URL: `http://uk.eonline.com/videos/237549/ariana-grande-posts-video-apology-for-doughnut-fiasco`

**Comment by dstftw** [comment]
Gives HTTP Error 404: Not Found for me.

**Comment by MaryCoding** [comment]
@dstftw The URL is valid. Below is a screenshot.
![eonline](https://cloud.githubusercontent.com/assets/10625322/8638210/bd0f2302-2881-11e5-82e4-64775aabcae4.png)

**Comment by MaryCoding** [comment]
@dstftw thanks for the follow up. Will this get fixed? I tried using a geo unrestriced url(as mentioned above) but it redirects back to the US site(as I am in the US).

**Comment by MaryCoding** [comment]
Hi, Sorry to bother. You all do a great job. Has there been a solution for this particular video extractor?

**Comment by dstftw** [comment]
Not yet as you can see.

**Comment by TRox1972** [comment]
The site is using ThePlatform.

**Comment by StevenDTX** [comment]
** Bump

URL:  http://www.eonline.com/now/famously-single/full-episode/do-you-trust-me/717540931533

```
E:\>youtube-dl --verbose --netrc "http://www.eonline.com/now/famously-single/full-episode/do-you-trust-me/717540931533"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--netrc', 'http://www.eonline.com/now/famously-single/full-episode/do-you-trust-me/717540931533']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.31
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-72383-g7206b94, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 717540931533: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 717540931533: Downloading webpage
[generic] 717540931533: Extracting information
ERROR: Unsupported URL: http://www.eonline.com/now/famously-single/full-episode/do-you-trust-me/717540931533
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6cf1z6ka\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6cf1z6ka\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6cf1z6ka\build\youtube_dl\extractor\generic.py", line 2388, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.eonline.com/now/famously-single/full-episode/do-you-trust-me/717540931533
```

This should be similar to BravoTV.  Thanks!

**Comment by TRox1972** [comment]
I added a PR for this a while back: https://github.com/rg3/youtube-dl/pull/9611

**Comment by StevenDTX** [comment]
@TRox1972 

I saw that you added that pull request. That extractor does not exist in the code. I'm fairly new to this, so do that mean someone has to "approve" and add it before it gets added to the next build?

**Comment by TRox1972** [comment]
@StevenDTX yes, it needs to be approved by the developers. But there are few developers and a lot of issues/PRs, so it may take some time before it's implemented.

Note that currently, the code in that PR doesn't seem to be working. And the generic extractor seems to catch videos os theplatform embeds, but fails to download them. You could wan't to add an issue report for that.

**Comment by TRox1972** [comment]
@remitamine  This is working for the requested URL since 433af6ad3002424ecb316e23946722d54010dbe1. Close this?

**Comment by remitamine** [comment]
urls similar to the url posted by @StevenDTX require a new extractor.

**Comment by MrRobot12** [comment]
AdobeHDS works on E! and other NBC Universal sites.

https://github.com/K-S-V/Scripts/wiki

**Comment by tv21** [comment]
Here would be a more current URL:

http://www.eonline.com/now/the-arrangement/full-episode/pilot/883821635771
Or
http://www.eonline.com/now/the-arrangement/full-episode/the-ex/895569987839
Or
http://www.eonline.com/now/so-cosmo/full-episode/is-he-truly-into-you/892677699900

This seems to be the format they are using now.  When I try this in youtube-dl it comes back with this:

    ~$ youtube-dl http://www.eonline.com/now/the-arrangement/full-episode/pilot/883821635771
    [generic] 883821635771: Requesting header
    WARNING: Falling back on generic information extractor.
    [generic] 883821635771: Downloading webpage
    [generic] 883821635771: Extracting information
    ERROR: Unsupported URL: http://www.eonline.com/now/the-arrangement/full-episode/pilot/883821635771

The URL is not really similar to Bravo at all, an example Bravo URL would be
http://www.bravotv.com/imposters/season-1/ep-1-my-so-called-wife

I suspect it is this difference in the URL format that is confusing the issue.  The format for eonline full episodes seems to be:

    http://www.eonline.com/now/<show name>/full-episode/<episode name>/<12 digit number>

Clips take a completely different format, here is an example:

    http://www.eonline.com/shows/so_cosmo/videos/257866/james-and-steven-dish-on-the-diandra-drama

I get a different output if I try to download a clip:

    ~$ youtube-dl http://www.eonline.com/shows/so_cosmo/videos/257866/james-and-steven-dish-on-the-diandra-drama
    [generic] james-and-steven-dish-on-the-diandra-drama: Requesting header
    WARNING: Could not send HEAD request to http://www.eonline.com/shows/so_cosmo/videos/257866/james-and-steven-dish-on-the-diandra-drama: HTTP Error 405: Method Not Allowed
    [generic] james-and-steven-dish-on-the-diandra-drama: Downloading webpage
    WARNING: Falling back on generic information extractor.
    [generic] james-and-steven-dish-on-the-diandra-drama: Extracting information
    [download] Downloading playlist: James and Steven Dish on the Diandra Drama on So Cosmo
    [generic] playlist James and Steven Dish on the Diandra Drama on So Cosmo: Collected 1 video ids (downloading 1 of them)
    [download] Downloading video 1 of 1
    [ThePlatform] cwqm1Kh0CAYx: Downloading SMIL data
    [ThePlatform] cwqm1Kh0CAYx: Downloading JSON metadata
    [download] Destination: James and Steven Dish on the Diandra Drama-cwqm1Kh0CAYx.flv
    ERROR: RTMP download detected but "rtmpdump" could not be run. Please install it.

Installing rtmpdump doesn't really help; instead of the ERROR line shown above I get these:

    [rtmpdump] 0 bytes


    ERROR: rtmpdump exited with code 1

Which means nothing to me

I'm not really looking to download clips anyway, but it appears there are two problems here.  First, it is apparently not parsing the URL properly for full episodes, and second, for whatever reason it thinks it should be doing an RTMP download, whatever that is.  This is something I haven't seen with any other site, so I kind of question whether it's misinterpreting the download type.

**Comment by tv21** [comment]
I ran the clip again with the -v option:
```
~$ youtube-dl http://www.eonline.com/shows/so_cosmo/videos/257866/james-and-steven-dish-on-the-diandra-drama -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.eonline.com/shows/so_cosmo/videos/257866/james-and-steven-dish-on-the-diandra-drama', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.15
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.7
[debug] exe versions: avconv 11.8-6, avprobe 11.8-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] james-and-steven-dish-on-the-diandra-drama: Requesting header
WARNING: Could not send HEAD request to http://www.eonline.com/shows/so_cosmo/videos/257866/james-and-steven-dish-on-the-diandra-drama: HTTP Error 405: Method Not Allowed
[generic] james-and-steven-dish-on-the-diandra-drama: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] james-and-steven-dish-on-the-diandra-drama: Extracting information
[download] Downloading playlist: James and Steven Dish on the Diandra Drama on So Cosmo
[generic] playlist James and Steven Dish on the Diandra Drama on So Cosmo: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[ThePlatform] cwqm1Kh0CAYx: Downloading SMIL data
[ThePlatform] cwqm1Kh0CAYx: Downloading JSON metadata
[debug] Invoking downloader on u'rtmp://cp423311.edgefcs.net/ondemand/'
[download] Destination: James and Steven Dish on the Diandra Drama-cwqm1Kh0CAYx.flv
[debug] rtmpdump command line: rtmpdump --verbose -r rtmp://cp423311.edgefcs.net/ondemand/ -o 'James and Steven Dish on the Diandra Drama-cwqm1Kh0CAYx.flv.part' --playpath mp4:transcoded/rtmp/769/87/cosmo_104_bonus_a_257866_1600k.flv --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : cp423311.edgefcs.net
[rtmpdump] DEBUG: Parsed app     : ondemand
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : cp423311.edgefcs.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:transcoded/rtmp/769/87/cosmo_104_bonus_a_257866_1600k.flv
[rtmpdump] DEBUG: tcUrl    : rtmp://cp423311.edgefcs.net:1935/ondemand
[rtmpdump] DEBUG: app      : ondemand
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Type Answer   : 03
[rtmpdump] DEBUG: HandShake: Server Uptime : 1544740205
[rtmpdump] DEBUG: HandShake: FMS Version   : 5.0.7.1
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: HandleServerBW: server BW = 1250000
[rtmpdump] DEBUG: HandleClientBW: client BW = 1250000 2
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 242 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             fmsVer, STRING:	FMS/5,0,7,7054>
[rtmpdump] DEBUG: Property: <Name:       capabilities, NUMBER:	127.00>
[rtmpdump] DEBUG: Property: <Name:               mode, NUMBER:	1.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetConnection.Connect.Success>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Connection succeeded.>
[rtmpdump] DEBUG: Property: <Name:     objectEncoding, NUMBER:	0.00>
[rtmpdump] DEBUG: Property: <Name:               data, ECMA_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            version, STRING:	5,0,7,7054>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <connect>
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: Invoking createStream
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 21 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onBWDone>
[rtmpdump] DEBUG: Invoking _checkbw
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 29 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <createStream>
[rtmpdump] DEBUG: SendPlay, seekTime=0, stopTime=0, sending play: mp4:transcoded/rtmp/769/87/cosmo_104_bonus_a_257866_1600k.flv
[rtmpdump] DEBUG: Invoking play
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 10275 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 20515 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 275 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	error>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.StreamNotFound>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Failed to play transcoded/rtmp/769/87/cosmo_104_bonus_a_257866_1600k.flv; stream not found.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:	transcoded/rtmp/769/87/cosmo_104_bonus_a_257866_1600k.flv>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:	qAADg9LA>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.StreamNotFound
[rtmpdump] ERROR: Closing connection: NetStream.Play.StreamNotFound
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : cp423311.edgefcs.net
[rtmpdump] DEBUG: Parsed app     : ondemand
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : cp423311.edgefcs.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:transcoded/rtmp/769/87/cosmo_104_bonus_a_257866_1600k.flv
[rtmpdump] DEBUG: tcUrl    : rtmp://cp423311.edgefcs.net:1935/ondemand
[rtmpdump] DEBUG: app      : ondemand
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.


ERROR: rtmpdump exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 454, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1883, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 772, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 950, in process_ie_result
    extra_info=extra)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 833, in process_ie_result
    extra_info=extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 772, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 826, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1527, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1791, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1733, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 162, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 589, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 551, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

**Comment by tv21** [comment]
And, not that it will likely help, but here is the full episode (which is what I am most concerned about) with the -v option:

```
~$ sudo youtube-dl http://www.eonline.com/now/the-arrangement/full-episode/pilot/883821635771 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.eonline.com/now/the-arrangement/full-episode/pilot/883821635771', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.15
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.7
[debug] exe versions: avconv 11.8-6, avprobe 11.8-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 883821635771: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 883821635771: Downloading webpage
[generic] 883821635771: Extracting information
ERROR: Unsupported URL: http://www.eonline.com/now/the-arrangement/full-episode/pilot/883821635771
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1779, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 8, column 410
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2648, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.eonline.com/now/the-arrangement/full-episode/pilot/883821635771
```

**Comment by tchawes** [comment]
Did this ever get addressed?  I am still getting an unsupported URL error:

```youtube-dl.exe http://www.eonline.com/now/keeping-up-with-the-kardashians/full-episode/clothes-
quarters/1078359108000 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.eonline.com/now/keeping-up-with-the-kardashians/full-episode/clothes-quarters/1078359108000', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.10.20
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-86383-g4705edb, ffprobe N-86383-g4705edb
[debug] Proxy map: {}
[generic] 1078359108000: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1078359108000: Downloading webpage
[generic] 1078359108000: Extracting information
ERROR: Unsupported URL: http://www.eonline.com/now/keeping-up-with-the-kardashians/full-episode/clothes-quarters/1078359108000
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvdixi2dy\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvdixi2dy\build\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvdixi2dy\build\youtube_dl\extractor\generic.py", line 3059, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.eonline.com/now/keeping-up-with-the-kardashians/full-episode/clothes-quarters/1078359108000```

**Comment by StevenDTX** [comment]
Bump.  Eonline seems to use the same Platform player as Bravo and other NBC sites.  

Here is a video available without login:  http://www.eonline.com/now/citizen-rose/full-episode/citizen-rose/1149898819562

```
E:\>youtube-dl --verbose http://www.eonline.com/now/citizen-rose/full-episode/citizen-rose/1149898819562
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://www.eonline.com/now/citizen-rose/full-episode/citizen-rose/1149898819562']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.02.11
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-89980-ge752da5464, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 1149898819562: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1149898819562: Downloading webpage
[generic] 1149898819562: Extracting information
ERROR: Unsupported URL: http://www.eonline.com/now/citizen-rose/full-episode/citizen-rose/1149898819562
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\generic.py", line 3111, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.eonline.com/now/citizen-rose/full-episode/citizen-rose/1149898819562
```

**Comment by noped** [comment]
Having the same issue, wondering when will there be a update on this, as iam getting Unsupported, in latest version, will it ever be added for full episodes, will e online be added to the list for supported tv provider like other sites. thanks

**Comment by noped** [comment]
Having the same issue, wondering when will there be a update on this, as iam getting Unsupported URL with my tv provider login, in latest version, auy update would great, can it be supported?

**Comment by roadzy** [comment]
adding to this:

youtube-dl --cookies cookies.txt http://www.eonline.com/watch/very-cavallari/full-episode/sunday-not-so-funday/1269538371591 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'cookies.txt', 'http://www.eonline.com/watch/very-cavallari/full-episode/sunday-not-so-funday/1269538371591', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.09
[debug] Python version 3.6.1 (CPython) - Linux-3.10.0-862.3.2.el7.x86_64-x86_64-with-centos-7.5.1804-Core
[debug] exe versions: ffmpeg 3.4.5, ffprobe 3.4.5
[debug] Proxy map: {}
[generic] 1269538371591: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1269538371591: Downloading webpage
[generic] 1269538371591: Extracting information
ERROR: Unsupported URL: http://www.eonline.com/watch/very-cavallari/full-episode/sunday-not-so-funday/1269538371591
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 522, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 3320, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.eonline.com/watch/very-cavallari/full-episode/sunday-not-so-funday/1269538371591

youtube-dl --version
2019.03.09

**Comment by remitamine** [comment]
watch/now URLs redirect not NBC website.
