### ISSUE TITLE
BFI support

### ISSUE THREAD

**Issue by GuyRWells** [ytdl-org/youtube-dl#6559]
Would it be possible to add support for the British Film Institute?

$ uname -a
CYGWIN_NT-6.1 MYBOX 2.2.0(0.289/5/3) 2015-08-03 12:51 x86_64 Cygwin

$ python --version
Python 2.7.10

$ youtube-dl --version
2015.08.09

$ youtube-dl --verbose "http://player.bfi.org.uk/film/watch-barging-through-london-1924"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://player.bfi.org.uk/film/watch-barging-through-london-1924']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.09
[debug] Python version 2.7.10 - CYGWIN_NT-6.1-2.2.0-0.289-5-3-x86_64-64bit
[debug] exe versions: ffmpeg SVN-r21566-xuggle-3.4.843
[debug] Proxy map: {}
[generic] watch-barging-through-london-1924: Requesting header
[redirect] Following redirect to http://player.bfi.org.uk/film/watch-barging-through-london-1924/
[generic] watch-barging-through-london-1924: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch-barging-through-london-1924: Downloading webpage
[generic] watch-barging-through-london-1924: Extracting information
ERROR: Unsupported URL: http://player.bfi.org.uk/film/watch-barging-through-london-1924/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1211, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1594, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 75, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 286, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1804, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://player.bfi.org.uk/film/watch-barging-through-london-1924/

**Comment by emma-goldman** [comment]
I'd second that!

PS C:\Users\Xyz\Videos> youtube-dl --verbose https://player.bfi.org.uk/free/film/watch-unfaithful-wife-c1900-1900-online --geo-bypass-country GB
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://player.bfi.org.uk/free/film/watch-unfaithful-wife-c1900-1900-online', u'--geo-bypass-country', u'GB']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.01.27
[debug] Python version 2.7.14 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[debug] Using fake IP 25.192.172.101 (GB) as X-Forwarded-For.
[generic] watch-unfaithful-wife-c1900-1900-online: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch-unfaithful-wife-c1900-1900-online: Downloading webpage
[generic] watch-unfaithful-wife-c1900-1900-online: Extracting information
ERROR: Unsupported URL: https://player.bfi.org.uk/free/film/watch-unfaithful-wife-c1900-1900-online
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\extractor\generic.py", line 2192, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "c:\python27\lib\site-packages\youtube_dl\compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "c:\python27\lib\site-packages\youtube_dl\compat.py", line 2531, in _XML
    parser.feed(text)
  File "c:\python27\lib\xml\etree\ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "c:\python27\lib\xml\etree\ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 13, column 339
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\generic.py", line 3108, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://player.bfi.org.uk/free/film/watch-unfaithful-wife-c1900-1900-online

**Comment by dirkf** [comment]
Resolved by https://github.com/ytdl-org/youtube-dl/commit/4810655cd65f9bdde1ad240adf7334828243fb0a.
