### ISSUE TITLE
[cbsnews] Add support for playlists

### ISSUE THREAD

**Issue by ceriibro** [ytdl-org/youtube-dl#7234]
It's been working fine for months now...  Here it is;

C:\Notify+>C:\Python27\Scripts\youtube-dl.exe --verbose -o r:+cbs-60.minutes.fl
v --ffmpeg-location=c:\python27\scripts --recode-video=mp4 http://www.cbsnews.co
m/latest/60-minutes/full-episodes/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-o', u'r:\+cbs-60.minutes.flv', u'-
-ffmpeg-location=c:\python27\scripts', u'--recode-video=mp4', u'http://www.cbs
news.com/latest/60-minutes/full-episodes/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.10.18
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-72086-g51f6455, ffprobe N-72086-g51f6455, rtmpdum
p 2.4
[debug] Proxy map: {}
[CBSNews] full-episodes: Downloading webpage
ERROR: Unable to extract video JSON info; please report this issue on https://yt
-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  t
o update. Be sure to call youtube-dl with the --verbose flag and include its com
plete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 661, in extract_info
  File "youtube_dl\extractor\common.pyo", line 291, in extract
  File "youtube_dl\extractor\cbsnews.pyo", line 53, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 594, in _html_search_regex
  File "youtube_dl\extractor\common.pyo", line 585, in _search_regex
RegexNotFoundError: Unable to extract video JSON info; please report this issue
on https://yt-dl.org/bug . Make sure you are using the latest version; type  you
tube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and in
clude its complete output.

**Comment by dstftw** [comment]
cbsnews playlist were never supported.

**Comment by f4evafly** [comment]
The supported sites listings seems to indicated that it does or should...

https://rg3.github.io/youtube-dl/supportedsites.html
CBS
CBSNews: CBS News
CBSSports

**Comment by hesco** [comment]
$ youtube-dl https://www.cbsnews.com/news/family-separation-1556-more-migrant-families-were-separated-under-trump-than-previously-known/ 

[cbsnews] family-separation-1556-more-migrant-families-were-separated-under-trump-than-previously-known: Downloading webpage

ERROR: Unable to extract video JSON info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
The original problem URL is no longer valid. Anyone who wants support of (eg) http://www.cbsnews.com/60-minutes/full-episodes/ could open a new issue according to #30839.

The problem link in https://github.com/ytdl-org/youtube-dl/issues/7234#issuecomment-546982148 doesn't appear to have a video now (empty manifest) and is anyway superseded by #32011.
