### ISSUE TITLE
Site Support Request: Kelbyone

### ISSUE THREAD

**Issue by ghost** [ytdl-org/youtube-dl#7733]
I noticed that the HD videos on this site are segmented, is this a possibility?

```
$ youtube-dl -jv http://kelbyone.com/course/pcollins_beginnersphotography_illustrated/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-jv', u'http://kelbyone.com/course/pcollins_beginnersphotography_illustrated/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.27.1
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://kelbyone.com/course/pcollins_beginnersphotography_illustrated/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1282, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 248, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 237, in _XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 86, column 3
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1887, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://kelbyone.com/course/pcollins_beginnersphotography_illustrated/
```

**Comment by jaan143** [comment]
Hi philberndt
did you use pluralsight ? 
and did you download pluralsight lectures with youtube-dl ?

**Comment by Astalaseven** [comment]
Hi jaan143, I tried to download some videos from Pluralsight but without success.

```
 youtube-dl --verbose  --username "***@hotmail.com" --password "***" --rate-limit 50K --sleep-interval 600 -o "%(autonumber)s - %(title)s.%(ext)s" "https://app.pluralsight.com/library/courses/advanced-javascript"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--rate-limit', u'50K', u'--sleep-interval', u'600', u'-o', u'%(autonumber)s - %(title)s.%(ext)s', u'https://app.pluralsight.com/library/courses/advanced-javascript']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.9 - Linux-4.1.13+-armv6l-with-debian-8.0
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] advanced-javascript: Downloading course JSON
[pluralsight:course] advanced-javascript: Downloading course data JSON
[download] Downloading playlist: Advanced JavaScript
[pluralsight:course] playlist Advanced JavaScript: Collected 56 video ids (downloading 56 of them)
[download] Downloading video 1 of 56
[pluralsight] Downloading login page
[pluralsight] Logging in as ***@hotmail.com
[pluralsight] advanced-javascript-m1-0: Downloading webpage
[pluralsight] advanced-javascript-m1-0: Downloading mp4-high-widescreen URL
WARNING: Unable to download webpage: HTTP Error 400: Bad Request
[pluralsight] advanced-javascript-m1-0: Waiting for 3 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 315, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/pluralsight.py", line 226, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 828, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by keepreason** [comment]
Allavsoft works and supports kelbyone

**Comment by Electricpinet** [comment]
You can use allavsoft to download Kelbyone Video Courses to MP4, AVI on Mac and Windows.

**Comment by janemaydaily** [comment]
Allavsoft has supported Kelbyone
http://www.allavsoft.com/how-to/download-kelbyone-video-courses.html

**Comment by dirkf** [comment]
https://github.com/ytdl-org/youtube-dl/issues/14949#issuecomment-2118477681
