### ISSUE TITLE
Add support for flashedu.rai.it (RAI 5 etc.)

### ISSUE THREAD

**Issue by nemobis** [ytdl-org/youtube-dl#7735]
```
$ youtube-dl http://rai5.rai.it/articoli/lo-stato-dellarte-undicesima-puntata-wikipedia-o-treccani/31724/default.aspx
[generic] default: Requesting header
WARNING: Falling back on generic information extractor.
[generic] default: Downloading webpage
[generic] default: Extracting information
ERROR: Unsupported URL: http://rai5.rai.it/articoli/lo-stato-dellarte-undicesima-puntata-wikipedia-o-treccani/31724/default.aspx
[federico@a88x Federico]$ youtube-dl --verbose http://rai5.rai.it/articoli/lo-stato-dellarte-undicesima-puntata-wikipedia-o-treccani/31724/default.aspx
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://rai5.rai.it/articoli/lo-stato-dellarte-undicesima-puntata-wikipedia-o-treccani/31724/default.aspx']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.13
[debug] Python version 2.7.8 - Linux-4.1.13-100.fc21.x86_64-x86_64-with-fedora-21-Twenty_One
[debug] exe versions: none
[debug] Proxy map: {}
[generic] default: Requesting header
WARNING: Falling back on generic information extractor.
[generic] default: Downloading webpage
[generic] default: Extracting information
ERROR: Unsupported URL: http://rai5.rai.it/articoli/lo-stato-dellarte-undicesima-puntata-wikipedia-o-treccani/31724/default.aspx
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1241, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/lib/python2.7/site-packages/youtube_dl/compat.py", line 248, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/lib/python2.7/site-packages/youtube_dl/compat.py", line 237, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 78, column 15
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1839, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://rai5.rai.it/articoli/lo-stato-dellarte-undicesima-puntata-wikipedia-o-treccani/31724/default.aspx

```

The mp4 is directly downloadable from an URL in the page source:

```
                       {
                           0: { src: 'http://flashedu.rai.it/ieduportale/rai5/lo_stato_dellarte___wikipedia.MP4', type: "video/mp4" },

                       }
```

**Comment by remitamine** [comment]
No Longer accessible.
