### ISSUE TITLE
Site support request: tvnz.co.nz/ondemand

### ISSUE THREAD

**Issue by GaryElmes** [ytdl-org/youtube-dl#8094]
Any chance of getting suport for TVNZ's "OnDemand" service?

An example URL is:
 https://www.tvnz.co.nz/ondemand/when-we-go-to-war/26-04-2015/series-1-episode-1-2

Current output from youtube-dl is:

$ youtube-dl -v https://www.tvnz.co.nz/ondemand/when-we-go-to-war/26-04-2015/series-1-episode-1-2
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.tvnz.co.nz/ondemand/when-we-go-to-war/26-04-2015/series-1-episode-1-2']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.31
[debug] Python version 2.7.10 - Linux-4.2.0-22-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.3-0ubuntu0.15.10.1, ffprobe 2.7.3-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] series-1-episode-1-2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] series-1-episode-1-2: Downloading webpage
[generic] series-1-episode-1-2: Extracting information
ERROR: Unsupported URL: https://www.tvnz.co.nz/ondemand/when-we-go-to-war/26-04-2015/series-1-episode-1-2
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1289, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 248, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 237, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 120, column 2
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1908, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.tvnz.co.nz/ondemand/when-we-go-to-war/26-04-2015/series-1-episode-1-2

**Comment by davidjameshowell** [comment]
I believe this is using Brightcove as well. It is geo-restricted.

**Comment by 89z** [comment]
Issue should be closed, URL is dead
