### ISSUE TITLE
Wistia IFrame embeds not detected

### ISSUE THREAD

**Issue by pbowyer** [ytdl-org/youtube-dl#8347]
On this page: http://humanisetheweb.com/videos-london-2015/

The videos from Wistia are not being detected correctly. Only one video is picked up, and when downloaded (4.3GB) it played for 1:58 and had audio only (tested in VLC and Windows Media Player).

A full transaction is:

```
λ python youtube-dl.py http://humanisetheweb.com/videos-london-2015/ -v --skip-download
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://humanisetheweb.com/videos-london-2015/', u'-v', u'--skip-download']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.01.27
[debug] Python version 2.7.11 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] videos-london-2015: Requesting header
WARNING: Falling back on generic information extractor.
[generic] videos-london-2015: Downloading webpage
[generic] videos-london-2015: Extracting information
[Wistia] f6xvmtmyb3: Downloading JSON metadata
```

If I give the embed URLs manually to youtube-dl it works fine.

**Comment by thomasrussellmurphy** [comment]
Another instance with Wistia embeds that does not get correctly detected: https://www.subzero-wolf.com/company/careers/videos/your-career. In this case, the generic extractor finds nothing:

```
$ youtube-dl https://www.subzero-wolf.com/company/careers/videos/your-career -v --skip-download 
[debug] System config: []
[debug] User config: ['--hls-prefer-native', '--format', 'bestvideo[height<1400]+bestaudio/best[height<1400]/sd/hd/0/bestaudio', '--default-search', 'ytsearch']
[debug] Custom config: []
[debug] Command-line args: ['https://www.subzero-wolf.com/company/careers/videos/your-career', '-v', '--skip-download']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.01.15
[debug] Python version 3.8.1 (CPython) - macOS-10.14.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[generic] your-career: Requesting header
WARNING: Falling back on generic information extractor.
[generic] your-career: Downloading webpage
[generic] your-career: Extracting information
ERROR: Unsupported URL: https://www.subzero-wolf.com/company/careers/videos/your-career
Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3347, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.subzero-wolf.com/company/careers/videos/your-career
```

**Comment by remitamine** [comment]
@thomasrussellmurphy, not the same issue, this issue is about not downloading all Wistia videos in a webpage(only the first), your issue is an embed not picked because the Wistia script is not loaded directly in the webpage(loaded from another script) which will cause [this part](https://github.com/ytdl-org/youtube-dl/blob/2a5c26c9803ed8801bac2419128f1778bae558df/youtube_dl/extractor/wistia.py#L53-L59) to fail.
