### ISSUE TITLE
[RTLXL] IndexError: list index out of range 

### ISSUE THREAD

**Issue by GijsTimmers** [ytdl-org/youtube-dl#8689]
```
$ youtube-dl -v 'http://rtlxl.nl/#!/weet-ik-veel-295922/5f149254-d234-3b11-9a05-7cc171e7c133'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://rtlxl.nl/#!/weet-ik-veel-295922/5f149254-d234-3b11-9a05-7cc171e7c133']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 3.4.3+ - Linux-4.2.0-30-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 2.7.6-0ubuntu0.15.10.1, avprobe 2.7.6-0ubuntu0.15.10.1, ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[rtl.nl] 5f149254-d234-3b11-9a05-7cc171e7c133: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/__init__.py", line 411, in main
    _real_main(argv)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/__init__.py", line 401, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/YoutubeDL.py", line 1692, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/common.py", line 316, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/rtlnl.py", line 76, in _real_extract
    material = info['material'][0]
IndexError: list index out of range
```

**Comment by dstftw** [comment]
This video is geo restricted. Can you watch it in browser?

**Comment by GijsTimmers** [comment]
Not really, it says it needs Silverlight, and I'm running Ubuntu, which Silverlight doesn't support. I'll check on a Windows pc asap.

**Comment by Reino17** [comment]
The video from the program-url you're trying to open is behind a paywall. Hence the error.
Only the [latest episode](http://rtlxl.nl/#!/weet-ik-veel-295922/3b9eaf97-8df3-350b-958d-247189052d60) is still freely available.

**Comment by 89z** [comment]
Issue should be closed, URL is dead
