### ISSUE TITLE
[franceculture.fr] Support emissions

### ISSUE THREAD

**Issue by Rudloff** [ytdl-org/youtube-dl#8878]
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.franceculture.fr/emissions/grands-portraits-de-scientifiques/michel-serres-lenchanteur-du-monde-nouveau', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.14
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
[debug] exe versions: avconv 11.6-6, avprobe 11.6-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] michel-serres-lenchanteur-du-monde-nouveau: Requesting header
WARNING: Falling back on generic information extractor.
[generic] michel-serres-lenchanteur-du-monde-nouveau: Downloading webpage
[generic] michel-serres-lenchanteur-du-monde-nouveau: Extracting information
[redirect] Following redirect to http://www.franceculture.fr/emissions/grands-portraits-de-scientifiques/michel-serres-lenchanteur-du-monde-nouveau?PageSpeed=noscript
[generic] michel-serres-lenchanteur-du-monde-nouveau?PageSpeed=noscript: Requesting header
WARNING: Falling back on generic information extractor.
[generic] michel-serres-lenchanteur-du-monde-nouveau?PageSpeed=noscript: Downloading webpage
[generic] michel-serres-lenchanteur-du-monde-nouveau?PageSpeed=noscript: Extracting information
ERROR: Unsupported URL: http://www.franceculture.fr/emissions/grands-portraits-de-scientifiques/michel-serres-lenchanteur-du-monde-nouveau?PageSpeed=noscript
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1314, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 248, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 237, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 2, column 11
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 320, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1961, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.franceculture.fr/emissions/grands-portraits-de-scientifiques/michel-serres-lenchanteur-du-monde-nouveau?PageSpeed=noscript
```

**Comment by MartinDelille** [comment]
I do reproduce the problem.

**Comment by hamlet** [comment]
Works now. You should close.
Regards
