### ISSUE TITLE
[Facebook] The video is not available

### ISSUE THREAD

**Issue by kotofond** [ytdl-org/youtube-dl#8954]
Hi,

```
C:\WINDOWS\system32>youtube-dl --verbose "https://m.facebook.com/story.php?story_fbid=1153357864675917&id=100000051446447"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://m.facebook.com/story.php?story_fbid=1153357864675917&id=100000051446447']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.18
[debug] Python version 3.5.1 - Windows-10-10.0.10586-SP0
[debug] exe versions: ffmpeg N-78358-g674cc26, ffprobe N-78358-g674cc26
[debug] Proxy map: {}
[facebook] 1153357864675917: Downloading webpage
[facebook] 1153357864675917: Downloading webpage
ERROR: The video is not available, Facebook said: "The link you followed may have expired, or the page may only be visible to an audience you&#039;re not in."
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 320, in extract
    return self._real_extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\facebook.py", line 308, in _real_extract
    video_id, fatal_if_no_video=True)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\facebook.py", line 236, in _extract_from_url
    expected=True)
youtube_dl.utils.ExtractorError: The video is not available, Facebook said: "The link you followed may have expired, or the page may only be visible to an audience you&#039;re not in."
```

However I can view this video in a browser without logging in

Thanks

**Comment by yan12125** [comment]
It's a youtube-dl bug. For now you can use the following URL to download this video:
```
youtube-dl "https://www.facebook.com/100000051446447/posts/1153357864675917/"
```

**Comment by kotofond** [comment]
The bug still persists in the latest version of youtube-dl (2016.05.01)

**Comment by remitamine** [comment]
will be fixed in the next version.
